### ISSUE TITLE
Gamepad API incorrectly reports active controllers

### ISSUE THREAD

**Issue by cjackson234** [electron/electron#10005]
* Electron version: 1.6.11
* Operating system: Win10

### Expected behavior

The gamepad API should not require player one to remain connected.

### Actual behavior

Unplugging player one removes both player one and player two.

### How to reproduce

With the following code:

window.setInterval(() => { console.log(navigator.getGamepads()); }, 500);

You will get a list of all available gamepads. However, if you run this in electron with two controllers attached, then remove the first controller listed, the second controller is also removed from the array.

Adding back the first controller adds both the first and second controller again.

If you run this code in chrome, unplugging player one does not disconnect player two.

**Comment by codebytere** [comment]
Does this issue occur on later versions of Electron, like `1.8.5` or `2.0.0`?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in the comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Comment by cjackson234** [comment]
I just ran a test and couldn't reproduce this in 2.0.0. Sorry for the delay on the response, but it is almost a year later...

**Comment by codebytere** [comment]
@cjackson234 no worries, just doing some backlog cleanup :) Thanks for checking in on this, glad it seems to be resolved!
