### ISSUE TITLE
`alt+Right` Keyboard shortcut does not work [Linux]

### ISSUE THREAD

**Issue by akashnimare** [electron/electron#10001]
I was trying to setup a keyboard shortcut for going forward in web page to `Alt+Right` but it's not triggering up. Although Alt +left works as expected.

**Comment by shubham2892** [comment]
@akashnimare It would be difficult to help without looking at any code. Please provide a minimal app that reproduces the issue. You can fork [electron-quick-start](https://github.com/electron/electron-quick-start), add your changes and add a link to it here.

**Comment by akashnimare** [comment]
You can reproduce this using - 
```sh
# Clone this repository
git clone https://github.com/electron/electron-quick-start
# Go into the repository
cd electron-quick-start
# Install dependencies
npm install
```
Add these lines in createWindow function
```javascript
  globalShortcut.register('Alt+X', () => {
    console.log('Alt+X is pressed')
  });

  globalShortcut.register('Ctrl+X', () => {
    console.log('Ctrl+X is pressed')
  });

  console.log(globalShortcut.isRegistered('Alt+x')) // logs to false
  console.log(globalShortcut.isRegistered('Ctrl+x')) // logs to true

```
I'm on Ubuntu 16.04 using electron v1.6.8.

**Comment by shubham2892** [comment]
`Alt+Right` shortcut might be taken by the desktop environment or another app in your system. Closing the issue.
