### ISSUE TITLE
Feature: Quick Start Electron using TypeScript

### ISSUE THREAD

**Issue by mtpultz** [electron/electron#10002]
With the addition of typings it seems like an example quick start for TypeScript might be a nice addition to the quick start resources.

**Comment by MarshallOfSound** [comment]
The electron repo itself has traditionally steered clear of specifically recommending front end frameworks or ES-Next compilation strategies.  

There is, however, a community generated list of cool Electron things here including some boilerplates: https://electron.atom.io/community/

You can also use a tool I helped make called [`electron-forge`](https://github.com/electron-userland/electron-forge) to easily get started with a typescript template.

```bash
npm i -g electron-forge
# React + Typescript
electron-forge init my-new-app --template=react-typescript
# Angular 2 + Typescript
electron-forge init my-new-app --template=angular2
```

You can also ask around in the [community](https://github.com/electron/electron#community) or the [Slack Channel](http://atom-slack.herokuapp.com/) if anyone has any recommendations for project structure or tooling.

**Comment by mtpultz** [comment]
@MarshallOfSound I completely understand what you're saying, but even though Electron is framework agnostic by adding typings to the project and not having them included as a community typings package it seems like the quick start would benefit from the addition since Electron is now acknowledging TypeScript as an alternative to vanilla ES6, but without an example in the docs.  

Thanks, I've actually added an Angular CLI question to the electron-forge repo that you've already responded to today, and I just responded - https://github.com/electron-userland/electron-forge/issues/262
