### ISSUE TITLE
Cannot pipe from `net.request` response in renderer

### ISSUE THREAD

**Issue by maccelerated** [electron/electron#10017]
* Electron version: 1.6.11
* Operating system: Windows 8.1 "6.3.9600"

### Expected behavior

Piping a `net.request` response into a stream in the renderer is permitted.

### Actual behavior

`stream.once`, `stream.write`, and `stream.end` are called by remote proxy with incorrect scope and several TypeError's print to console.

### How to reproduce

  $ git clone git@github.com:maccelerated/electron-bug-example.git
  $ npm install
  $ npm start

### Code that causes an error

```js
const stream = require('stream')
const {net} = require('electron').remote
const request = net.request('https://example.com');
request.on('response', (response) => {
  const str = new stream.PassThrough()
  // Bind the functions and it works
  //str.write = str.write.bind(str)
  //str.once = str.once.bind(str)
  //str.end = str.end.bind(str)
  //str.on = str.on.bind(str)
  response.pipe(str);
})
request.end()
```

**Comment by akashnimare** [comment]
@maccelerated  [net](https://github.com/electron/electron/blob/master/docs/api/net.md) module only works in `main` process so you can't use it in the `renderer`.

**Comment by MCMicS** [comment]
this happens also on macOS
The fix works.
If Electron use the passthrough for remote use automatically it would be fine

**Comment by codebytere** [comment]
Closing as @akashnimare is correct, net works only in the main process.

**Comment by sindresorhus** [comment]
@codebytere Note that here it's used using the `remote` module, not directly in the renderer. If it's true that it does not work in the renderer through `remote`, it should be clearly documented and it should not be possible to access `electron.remote.net` in the renderer.

**Comment by MarshallOfSound** [comment]
@sindresorhus It isn't that it 100% doesn't work through `remote`, it is a race condition.  @codebytere and I looked into this a while back in response to https://github.com/electron/electron/issues/12545.  Basically piping doesn't 100% work because by the time the event has been propagated to the renderer process, the data / end events have already started being emitted.  It's just one massive race condition that is very unpredictable in nature

**Comment by MCMicS** [comment]
it works on renderer side with the PassThrough stream hack above.
So its technically possible
