### ISSUE TITLE
Webview blank on first load

### ISSUE THREAD

**Issue by mjbvz** [electron/electron#10016]
* Electron version: 1.7.4
* Operating system: MacOS 10.12.5 

### Expected behavior
Webview shows html file from local filesystem

![screen shot 2017-07-14 at 3 46 17 pm](https://user-images.githubusercontent.com/12821956/28233413-977282a8-68ab-11e7-923a-298b5c708c78.png)

### Actual behavior
Webview is empty/blank when the app is first loaded

![screen shot 2017-07-14 at 3 46 32 pm](https://user-images.githubusercontent.com/12821956/28233424-a09b991e-68ab-11e7-9806-c30e443dd6fb.png)

### How to reproduce

```bash
$ git clone https://github.com/mjbvz/electron-test-webview-blank
$ npm install
$ npm start .
```

The main renderer consists of:

```js
const updateWebview = () => {
    const webview = document.createElement('webview');
    webview.src = './view.html'

    document.body.appendChild(webview)
};

updateWebview()
```

It seems that the webview element is added to the DOM, but it has no contents and I cannot open devtools on it:

<img width="475" alt="screen shot 2017-07-14 at 3 44 29 pm" src="https://user-images.githubusercontent.com/12821956/28233399-67c31766-68ab-11e7-9099-8b2f24d029e1.png">

Switching to `setTimeout(updateWebview, 0)` seems to fix this

Possible another case of #8505

**Comment by codebytere** [comment]
Does this occur on more recent versions, such as `1.8.5` or `2.0.0`?

**Comment by mjbvz** [comment]
Yes, in 2.0.0, I still see this issue:

<img width="1012" alt="screen shot 2018-05-10 at 5 58 16 pm" src="https://user-images.githubusercontent.com/12821956/39901201-d395b540-547b-11e8-9733-26ae83ec52a8.png">

**Comment by Nashorn** [comment]
Problem still exist in Electron 5

**Comment by squalle0nhart** [comment]
using webView.setAttribute('src', <url>); work for me, but webview.src = <url> doesn't work.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by mjbvz** [comment]
Confirmed with Electron 8.0.1. Pushed an update to my example.

The `setTimeout(updateWebview, 0)` workaround still fixes things

**Comment by LittleHamster** [comment]
I also have this issue

**Comment by aderuelle** [comment]
Hi,

Lens Kubernetes IDE has a similar [issue](https://github.com/lensapp/lens/issues/255), that _might_ be related but it seems the setTimeout workaround doesn't help in that case ?

Launching two concurrent instances of the same app fixes the problem in the second one (ie. the webview renders Ok).

<img width="874" alt="Capture d’écran 2020-04-30 à 20 40 42" src="https://user-images.githubusercontent.com/42127/80746888-dd874480-8b22-11ea-93b1-5ae39e92cd2a.png">

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
