### ISSUE TITLE
Subclass of BrowserWindow isn't regarded as parent window of dialog.showOpenDialog

### ISSUE THREAD

**Issue by hirikarate** [electron/electron#10019]
* Electron version: 1.6.11
* Operating system: Windows 10

### Expected behavior

* Modal dialog opened with `dialog.showOpenDialog(parent, options)` must not appear BELOW parent window.
* Cannot interact with parent window while modal dialog is open.
* Modal dialog doesn't have icon on taskbar.

### Actual behavior

* Modal dialog opened with `dialog.showOpenDialog(parent, options)` appears BELOW parent window.
* Can interact with parent window, and closing parent window leaves modal dialog still open.
* Modal dialog has icon on taskbar.

### How to reproduce

For detail, please have a look at my fork: https://github.com/hirikarate/electron-quick-start

This is summary:

```
class AdvancedWindow extends BrowserWindow {
  constructor(options) {
    super(options);
  }
}

let mainWindow;

function createWindow () {
  mainWindow = new BrowserWindow({width: 800, height: 600}); // Acts as parent of modal dialog
  mainWindow = new AdvancedWindow({width: 800, height: 600});  // Does not act as parent of modal dialog
  showOpenDialog();

  // other code...
}

function showOpenDialog() {
  return electron.dialog.showOpenDialog(
    mainWindow,
    {
        title: 'Custom title',
        buttonLabel: 'Custom action',
        properties: ['openDirectory']
    });
}
```

**Comment by enlight** [comment]
Subclassing of `BrowserWindow` is not currently supported (see #23), though documentation of this limitation is still lacking (as per #8898).

**Comment by ddelapasse2** [comment]
Still true?  I found an example doing this successfully in javascript but when I use typescript I'm getting an error the the constructor needs to be called even tho it IS.
