### ISSUE TITLE
Fix electron.d.ts file

### ISSUE THREAD

**Issue by CzBuCHi** [electron/electron#10012]
Fix electron.d.ts so that all types, that are referenced by exported types are exported too.

As an example interface **BrowserWindowConstructorOptions**  is not exported but is used by exported class **BrowserWindow** as ctor as parameter...

Priority: low

**Comment by MarshallOfSound** [comment]
That interface is not exported but it is declared in a global namespace `Electron.BrowserWindowConstructorOptions`.  Further issues / questions re the typings should be raised on the electron-typescript-definitions repository :+1:
