### ISSUE TITLE
Can't TypeHint BrowserWindow

### ISSUE THREAD

**Issue by mtpultz** [electron/electron#10011]
* Electron version:
* Operating system:

### Expected behavior
There's no quick start for Electron using TypeScript even though typings are provided so I've tried to setup main.ts using `let mainWindow: BrowserWindow;`, which shows an error in VSCode of `cannot find name of BrowserWindow`.

### Actual behavior
Should be able to typehint `BrowserWindow`..

### How to reproduce
```
import { app, BrowserWindow } from 'electron';
let mainWindow: BrowserWindow = null;
```

**Comment by MarshallOfSound** [comment]
This is being discussed over in --> electron/electron-typescript-definitions/issues/55

But basically the types for Electron are exported in a global namespace like so:

```js
import { app, BrowserWindow } from 'electron';

const window: Electron.BrowserWindow = null;
```
