### ISSUE TITLE
webPreferences.scrollBounce refuses to work.

### ISSUE THREAD

**Issue by rohan-ramesh** [electron/electron#10028]
* Electron version:
* Operating system: macOS Sierra 10.12.5

### Expected behavior

The 'rubber band effect' is applied when I create a `BrowserWindow` object as such:
```javascript
let mainWindow = new BrowserWindow({
  width: 800,
  height: 600,
  webPreferences: {
    scrollBounce: true
  }
})
```

### Actual behavior

No scroll bounce is applied.

**Comment by shubham2892** [comment]
@rohan-ramesh I was not able to reproduce the issue. `scrollBounce` is working fine for me. Which electron version you are using.

**Comment by rohan-ramesh** [comment]
I should probably note that the element in context is a `<div>` with `overflow: scroll`.

**Comment by shubham2892** [comment]
@rohan-ramesh Check issue [#546520](https://bugs.chromium.org/p/chromium/issues/detail?id=546520). Also check comments from [#9134](https://github.com/electron/electron/pull/9134).

> In Chromium rubber-band scroll effect works only with main body in the window, but not with other scrollable elements, such as divs.
