### ISSUE TITLE
How to use extrenal configuration file for app.asr?

### ISSUE THREAD

**Issue by sachinavinaw** [electron/electron#10021]
Hi there.

I have to build my application with electron.

Some of the credentials (like DB credentials, Server Info etc) is configured through properties.json file.
```
app
|__ bin
|__ config
|__ public
|__ views
|__ app.js
|__package.json
properties.json
```

I built the app to app.asar. When I executre, it shows : 
```
info: FILE PATH IS  ::  ../properties.json
error: File not found at specified path
```
properties.json file which is used inside the app.js could not itendtify the path. 
Can anyone help?

**Comment by enlight** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
