### ISSUE TITLE
How to use the Nodejs modules in other applications using IFRAME ?

### ISSUE THREAD

**Issue by patrickalima98** [electron/electron#10024]
Personnel I am developing an application in electron, which has other mini applications, are complements I use in the IFRAME. I have the motherboard application that includes the other applications that are in the same folder using IFRAME, but I can not use the URNode.JS modules in applications that are included through the IFRAME. Researching the subject, I found that the now who owns the integration is the webview tag, but also found the following code

`window.top.require`

What exactly does he do? I saw that it allows access to the modules of my motherboard application, but is this correct to use or is it a flaw?

**Comment by enlight** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
