### ISSUE TITLE
win.hide() does not focus background window on Windows.

### ISSUE THREAD

**Issue by veniversum** [electron/electron#10023]
* Electron version: 1.6.7
* Operating system: Win 10

### Expected behavior

Background window or previously last focused window should be brought to focus when `win.hide()` is called.

### Actual behavior

Other window is not refocused after `win.hide()`. There is no window in focus (can be checked with Window Spy or other tools).

### How to reproduce

Having this issue with sindresorhus/caprine#233. We are hiding the window instead on window close event, in order to minimize to tray. App is hidden but other window will not be brought back to focus.

In order to bring background window into focus, `win.blur()` has to be called along with `win.hide()`. This behavior is not documented and I'm not sure if it is intended.

**Comment by dashersw** [comment]
I can confirm this is the behavior for mac as well. I use a frameless window, maybe that's why, but even `win.blur()` doesn't blur the window.

**Comment by hq229075284** [comment]
I also encounter this issue in Windows 10 when develop a App used electron 2.0,if this issue still not fixed in newest electron version?

**Comment by michelvermeulen** [comment]
Same here :/

**Comment by michelvermeulen** [comment]
Fixed here: https://stackoverflow.com/questions/50642126/previous-window-focus-electron :)

**Comment by rotemgrim** [comment]
@michelvermeulen in the link the guy used app.hide() to hide the window and set focus to the background window. 
app.hide() works only in mac and not windows...

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by rmnprt** [comment]
I am still experiencing this on macOS on v3.0.5.

**Comment by rmnprt** [comment]
I am still experiencing this on macOS on v3.0.5.

**Comment by mahhov** [comment]
also still experiencing this. In windows 10, electron 5.0.0

**Comment by pushkin-** [comment]
follow [here](https://github.com/electron/electron/issues/28451) for updates
