### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by steem** [electron/electron#10026]
Not sure whether it's caused by VS2015 or not. How can I fix it.

I just met the following failure when building asar_util.cc:

'ThreadLocalPointer': undeclared identifier
'Leaky': is not a member of '`global namespace''

The code in head version is:
base::LazyInstance<base::ThreadLocalPointer<ArchiveMap>>::Leaky
    g_archive_map_tls = LAZY_INSTANCE_INITIALIZER;

When I switch back to old version:
static base::LazyInstance<ArchiveMap> g_archive_map = LAZY_INSTANCE_INITIALIZER;

Build is pass.

**Comment by MarshallOfSound** [comment]
Have you bootstrapped recently?

**Comment by steem** [comment]
Yes, the code is cloned yesterday and run "python script\bootstrap.py -v --target_arch=ia32" first.

**Comment by codebytere** [comment]
This should be fixed in most recent versions, but i can reopen if not.
