### ISSUE TITLE
Tray MenuItem triggers click function on assignment if function is global

### ISSUE THREAD

**Issue by CptMaumau** [electron/electron#10036]
* Electron version: 1.6.11
* Operating system: darwin

### Expected behavior

On application launch, only main window is launched.

### Actual behavior

click event is somehow triggered and an extra window is opened on application launch

### How to reproduce

I have a function declared globally

```
function newWindowHandler() {
  let display = electron.screen.getDisplayNearestPoint(electron.screen.getCursorScreenPoint());
  let winClone = Object.assign({
    x: display.bounds.x + 50,
    y: display.bounds.y + 50
  }, winOptions)
  let win = new BrowserWindow(winClone);
  win.webContents.on('did-finish-load', ()=>{
    win.webContents.executeJavaScript('window.isElectron = true;');
    win.show();
    win.focus();
  });
  win.on('resize', function(e) {
    let [width, height] = win.getSize();

    settings.set('width', width);
    settings.set('height', height);
  });
  win.loadURL(appURL);
}
```
and a menu item in my tray icon

```
{
      label: "New Window",
      accelerator : 'CmdOrCtrl+N',
      click: function newWindowHandler()
}
```

### Extra

If I actually declare the function in the click event, it doesn't trigger on launch.

**Comment by enlight** [comment]
While you haven't provided a complete sample, the bug is mostly likely right here:

> click: function newWindowHandler()

That line should've thrown a syntax error, so I dunno what's going on exactly. However, if the `function` keyword wasn't there that line would call `newWindowHandler()` and assign the return value of that function to `click`... which is not what you intended.

**Comment by CptMaumau** [comment]
@enlight sorry while testing I pasted the wrong code, the menu item is
```
{
      label: "New Window",
      accelerator : 'CmdOrCtrl+N',
      click: newWindowHandler()
}
```
