### ISSUE TITLE
electron-icon-maker issue

### ISSUE THREAD

**Issue by sviat9440** [electron/electron#10037]
PS D:\Lotus\LotusWin> electron-icon-maker -i icon_build/icon.png -o icon/
{ i: 'icon_build/icon.png',
  input: 'icon_build/icon.png',
  o: 'icon/',
  output: 'icon/' }
Created D:\Lotus\LotusWin\icon/icons/png/16.png
Created D:\Lotus\LotusWin\icon/icons/png/24.png
Created D:\Lotus\LotusWin\icon/icons/png/32.png
Created D:\Lotus\LotusWin\icon/icons/png/48.png
Created D:\Lotus\LotusWin\icon/icons/png/64.png
Created D:\Lotus\LotusWin\icon/icons/png/128.png
Created D:\Lotus\LotusWin\icon/icons/png/256.png
Created D:\Lotus\LotusWin\icon/icons/png/512.png
Created D:\Lotus\LotusWin\icon/icons/png/1024.png
Icon generetor from PNG:
  src: D:\Lotus\LotusWin\icon\icons\png
  dir: D:\Lotus\LotusWin\icon\icons\mac
(node:2320) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: TypeError: Cannot read property '[object Array]' of undefined

**Comment by enlight** [comment]
Wrong repo, file your issue at https://github.com/jaretburkett/electron-icon-maker
