### ISSUE TITLE
Implement BrowserView.fromId(id)

### ISSUE THREAD

**Issue by xywz** [electron/electron#10039]
Similar to `BrowserWindow.fromId(id)`.

**Comment by poiru** [comment]
Fixed by #10039.

**Comment by promversioning** [comment]
I need this feature, why does it write this "**TypeError: BrowserView.fromId is not a function**" to me? 
I have the latest version of Electron (20.1.0). 
Can you help me please?

**Comment by promversioning** [comment]
It is strange because in 5 years no one reported similar problem!
Maybe I'm in wrong ??
` var mynewbrowserview= BrowserView.fromId(LinkToolbarPageloader[toolbar_id]) ;`
