### ISSUE TITLE
Option to have native tabs for all titleBarStyles

### ISSUE THREAD

**Issue by xywz** [electron/electron#10038]
This was shown in https://github.com/electron/electron/issues/6124#issuecomment-280218361 and would be useful for some apps.

The reason provided there for not allowing it was because of a potential legibility issue, but that can easily be avoided with a light background. While this might require a slight compromise, it would be better to have the option of doing so and to leave the decision to the developer.

* Operating system: macOS

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
