### ISSUE TITLE
Systray Menu Accelerator's not triggering `click` handler

### ISSUE THREAD

**Issue by killerspaz** [electron/electron#10035]
* Electron version: 1.7.4
* Operating system: Windows 10

### Expected behavior

`click` handler to activate as if user clicked the menu item explicitly.

### Actual behavior

Nothing occurs. A user on slack was able to verify it DOES work on OSX without modification.

### How to reproduce

* npm i electron@beta
* drop code below into `systray.js`
* drop any `png` file next to `systray.js` as `systray.png`
* ./node_modules/electron/dist/electron ./systray.js
* Right click on systray, accelerator has no effect (but clicking it does).

```
//Transpiled via tsc
"use strict";
const electron_1 = require("electron");
const path = require("path");
const icoPath = path.join(__dirname, './systray.png');

class SysTray {
    /**
     * Initializes SysTray with basic setup
     */
    constructor() {
        this.tray = new electron_1.Tray(icoPath);
        this.menu = new electron_1.Menu();
        this.addDefaultItems();
        this.tray.setToolTip('SysTray Test');
        this.tray.setContextMenu(this.menu);
    }
    addDefaultItems() {
        this.menu = electron_1.Menu.buildFromTemplate([
            {
                label: 'Restore UI',
                type: 'normal',
                accelerator: 'CmdOrCtrl+U'
            },
            { type: 'separator' },
            {
                label: 'Quit',
                type: 'normal',
                accelerator: 'CmdOrCtrl+Q',
                click: this.quitApp
            }
        ]);
    }
    quitApp() {
        electron_1.app.quit();
    }
}

electron_1.app.on('ready', () => new SysTray());

```

**Comment by killerspaz** [comment]
I'd like to note `globalShortcut` does work, but not what I'm trying to accomplish.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
