### ISSUE TITLE
how can i change the current window position?

### ISSUE THREAD

**Issue by EVOKE-LEKTRIQUE** [electron/electron#10041]
i really need to change the current window position with x,y values ... how can i do it ?

**Comment by xywz** [comment]
Call `win.setPosition(x, y[, animate])`. See https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winsetpositionx-y-animate.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
