### ISSUE TITLE
Default listeners for crashes

### ISSUE THREAD

**Issue by xywz** [electron/electron#10044]
This is especially useful during development. They could call `dialog.showErrorBox`, similar to when errors occur in the main process.

**Comment by zeke** [comment]
Can you describe in more detail what you're asking for? Please include code examples to illustrate your point.

**Comment by xywz** [comment]
It would be useful for all crash events to have a default listener that reports the crash.

When a webContents crashes the window goes blank and there is no other sign of the crash unless a crashed event listener is added. This makes it hard to find the problem during development.

**Comment by jkleinsc** [comment]
@xywz could you use the `ELECTRON_ENABLE_STACK_DUMPING` environment variable to display the stack in the console when Electron crashes?  This doc for more details: https://electron.atom.io/docs/api/environment-variables/#electron_enable_stack_dumping

**Comment by zeke** [comment]
These modules may also be useful:

https://github.com/sindresorhus/electron-unhandled
https://github.com/sindresorhus/electron-debug

**Comment by miniak** [comment]
We have exposed `renderer-process-crashed` event on `app`, which allows you to handle crashes for any renderer process in a single place and show a message box for example.

**Comment by miniak** [comment]
you can do this
```js
app.on('render-process-gone', (event, wc, details) => {
  dialog.showErrorBox('render-process-gone', `webContents #${wc.id} ${details.reason}: ${details.exitCode}`);
});
```
