### ISSUE TITLE
Document webview did-attach event

### ISSUE THREAD

**Issue by xywz** [electron/electron#10042]
Added in #7157.

**Comment by zeke** [comment]
Closing, as https://github.com/electron/electron/pull/7157 was merged. Thanks!

**Comment by xywz** [comment]
The issue is that the webview did-attach event is undocumented. #7157 added the event but did not document it.

**Comment by zeke** [comment]
Thanks for clearing that up, @xywz. Reopened.

**Comment by zeke** [comment]
cc @Mossop

**Comment by codebytere** [comment]
Documented in https://github.com/electron/electron/pull/10711

**Comment by pfrazee** [comment]
This is actually still not done! 😅 #10711 documented the webContents `did-attach-webview` event. This issue is about the webview `did-attach` event, which is still not documented.

**Comment by codebytere** [comment]
@pfrazee whoops, i'll do this this week!
