### ISSUE TITLE
Crash while double click on tray.

### ISSUE THREAD

**Issue by cumajkeee** [electron/electron#10043]
* Electron version: 1.6.11
* Operating system: Windows 10 VM (VBox)

### Expected behavior
App not crashed

### Actual behavior
App crashing on double click on tray if setup listeners for click and double click

### How to reproduce

[electron-tray-click&dblclick-crash.zip](https://github.com/electron/electron/files/1152700/electron-tray-click.dblclick-crash.zip)

**Comment by zeke** [comment]
Thanks for the sample app. FWIW I am not able to reproduce on macOS.

**Comment by cumajkeee** [comment]
If it possible, please could you tell the actual reason of the issue, cause I want to fix issue on prod a bit early then new version contain fix will be released. Thanks in advance

**Comment by groundwater** [comment]
I can reproduce this issue on my Surface Pro 4, using Windows 10. I'm trying my hand at symbolicating the crash to figure out what the problem is.

**Comment by alper-teke** [comment]
@groundwater were you able to figure out what the problem is? I have the same issue still

**Comment by codebytere** [comment]
This issue is no longer present on latest supported versions of Electron.
