### ISSUE TITLE
Electron w/es6 and CRA, import in electron.js

### ISSUE THREAD

**Issue by elegos** [electron/electron#10045]
* Electron version: 1.6.11
* Operating system: Linux

### Expected behavior
I'd like to be able to use the "import" statement in the electron starter script (in the source)

### Actual behavior
I'm not able to let babel compile the `build/electron.js` file, so the import statements are not being transpiled in requires.

### How to reproduce

1. Create a CRA app
2. Install Electron on the project
3. Install the `babel-register` module
4. Install the `electron-builder` module
5. run the app via `ELECTRON_START_URL=http://localhost:3000 electron -r babel-register .`

This will let the application run in a development environment, where the page is being served by nodejs. The point is that `electron` accepts the `-r|--register` option to pre-register one or more modules. In this way electron works with an on-the-fly transpiled electorn.js script (which works correctly).

Now, when it comes to build, react-scripts will build the frontend scripts, but not the backend (electron.js) ones. When I thus build electron via `build --em.main=build/electron.js`, the script is not being transpiled and thus it will complain about the `import` statement.

What can I do in order to correctly "build" that file, too?

package.json:

    {
      "name": "my-app",
      "version": "0.1.0",
      "private": true,
      "dependencies": {
        "@microsoft/microsoft-graph-client": "^1.0.0",
        "babel-preset-electron": "^1.4.15",
        "babel-register": "^6.24.1",
        "material-ui": "^0.18.6",
        "node-localstorage": "^1.3.0",
        "prop-types": "lastest",
        "react": "^15.6.1",
        "react-dom": "^15.6.1",
        "react-router": "^4.1.1",
        "react-router-dom": "^4.1.1",
        "react-tap-event-plugin": "^2.0.1",
        "simple-oauth2": "^1.3.0",
        "tingodb": "^0.5.1"
      },
      "devDependencies": {
        "babel-cli": "^6.24.1",
        "electron": "^1.6.11",
        "electron-builder": "^19.16.0",
        "eslint": "^3.19.0",
        "eslint-config-airbnb": "^15.0.2",
        "eslint-plugin-import": "^2.6.1",
        "eslint-plugin-jsx-a11y": "^5.1.1",
        "eslint-plugin-react": "^7.1.0",
        "nock": "^9.0.13",
        "react-scripts": "1.0.10"
      },
      "main": "public/electron.js",
      "homepage": "./",
      "scripts": {
        "start": "BROWSER=none react-scripts start",
        "build": "react-scripts build",
        "test": "react-scripts test --env=jsdom",
        "eject": "react-scripts eject",

        "electron": "electron -r babel-register .",
        "electron-dev": "ELECTRON_START_URL=http://localhost:3000 electron -r babel-register .",

        "electron-build": "build --em.main=build/electron.js",
        "electron-dist": "electron-builder"
      },
      "build": {
        "appId": "my.app.id",
        "asar": true,
        "files": [
          "build/**/*",
          "src/",
          "node_modules/**/*"
        ],
        "directories": {
          "buildResources": "assets"
        }
      }
    }

Thank you very much :)

**Comment by enlight** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
