### ISSUE TITLE
electron@1.6.7 unable to npm install on Windows 7

### ISSUE THREAD

**Issue by Ribeiro** [electron/electron#10057]
Here you can find tre npm-debug.log part:

14134 silly postinstall electron@1.6.7 D:\Desenvolvimento\dotNET\Projetos\Integrador_Fiscal\Codigo\integrador-mfe\node_modules\.staging\electron-f313c8d7
14135 info lifecycle electron@1.6.7~postinstall: electron@1.6.7
14136 verbose lifecycle electron@1.6.7~postinstall: unsafe-perm in lifecycle true
14137 verbose lifecycle electron@1.6.7~postinstall: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\Desenvolvimento\dotNET\Projetos\Integrador_Fiscal\Codigo\integrador-mfe\node_modules\electron\node_modules\.bin;D:\Desenvolvimento\dotNET\Projetos\Integrador_Fiscal\Codigo\integrador-mfe\node_modules\.bin;D:\Users\008188L1\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;D:\Users\008188L1\bin;C:\oracle\ora92\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\Intel\DMIX;C:\Program Files\SafeNet\Authentication\SAC\x32;C:\Program Files\SafeNet\Authentication\SAC\x64;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\dotnet;C:\Program Files\Git\cmd;C:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs;C:\Program Files (x86)\Microsoft VS Code\bin;D:\Users\008188L1\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
14138 verbose lifecycle electron@1.6.7~postinstall: CWD: D:\Desenvolvimento\dotNET\Projetos\Integrador_Fiscal\Codigo\integrador-mfe\node_modules\electron
14139 silly lifecycle electron@1.6.7~postinstall: Args: [ '/d /s /c', 'node install.js' ]
14140 silly lifecycle electron@1.6.7~postinstall: Returned: code: 1  signal: null
14141 info lifecycle electron@1.6.7~postinstall: Failed to exec postinstall script
14142 verbose unlock done using D:\Users\008188L1\AppData\Roaming\npm-cache\_locks\staging-c221d9790d1cd1b7.lock for D:\Desenvolvimento\dotNET\Projetos\Integrador_Fiscal\Codigo\integrador-mfe\node_modules\.staging
14143 silly rollbackFailedOptional Starting
14144 silly rollbackFailedOptional Finishing
14145 silly runTopLevelLifecycles Finishing
14146 silly install printInstalled
14147 warn integrador@1.6.86 No repository field.
14148 verbose If you need help, you may report this error at:
14148 verbose     <https://github.com/npm/npm/issues>
14149 warn integrador@1.6.86 No license field.
14150 verbose If you need help, you may report this error at:
14150 verbose     <https://github.com/npm/npm/issues>
14151 verbose stack Error: electron@1.6.7 postinstall: `node install.js`
14151 verbose stack Exit status 1
14151 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14151 verbose stack     at emitTwo (events.js:106:13)
14151 verbose stack     at EventEmitter.emit (events.js:191:7)
14151 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14151 verbose stack     at emitTwo (events.js:106:13)
14151 verbose stack     at ChildProcess.emit (events.js:191:7)
14151 verbose stack     at maybeClose (internal/child_process.js:891:16)
14151 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14152 verbose pkgid electron@1.6.7
14153 verbose cwd D:\Desenvolvimento\dotNET\Projetos\Integrador_Fiscal\Codigo\integrador-mfe
14154 error Windows_NT 6.1.7601
14155 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "electron" "--verbose"
14156 error node v6.11.1
14157 error npm  v3.10.10
14158 error code ELIFECYCLE
14159 error electron@1.6.7 postinstall: `node install.js`
14159 error Exit status 1
14160 error Failed at the electron@1.6.7 postinstall script 'node install.js'.
14160 error Make sure you have the latest version of node.js and npm installed.
14160 error If you do, this is most likely a problem with the electron package,
14160 error not with npm itself.
14160 error Tell the author that this fails on your system:
14160 error     node install.js
14160 error You can get information on how to open an issue for this project with:
14160 error     npm bugs electron
14160 error Or if that isn't available, you can get their info via:
14160 error     npm owner ls electron
14160 error There is likely additional logging output above.
14161 verbose exit [ 1, true ]

I would appreciate any directions in order to solve the installation issue. Thanks in advance!  =)

**Comment by zeke** [comment]
The `ELIFECYCLE` error is usually indicative of a failed installation. Please try the following:

```
rm -rf node_modules
npm install electron --save-dev
```

**Comment by Ribeiro** [comment]
@zeke Hi there! I tried your suggestion this morning, but no luck! I get  tunneling socket could not be established, statusCode=407. By the way, I already have installed and configured CNTLM on my Windows box as well as setup npm proxy and https-proxy. What else can I do to fix this? Thank you!

**Comment by Ribeiro** [comment]
@zeke  Please, close the issue. Solved using CNTLM! =)
