### ISSUE TITLE
Is there an API to read and write windows registry?

### ISSUE THREAD

**Issue by cuixiping** [electron/electron#10056]
I din't see an API to read and write windows registry on documentation site.

* Electron version: 1.7.4

### Expected behavior

```
app.readRegistry(...)
app.writeRegistry(...)
```

**Comment by enlight** [comment]
No there isn't, you'll have to use a third-party module or `node-ffi`.

GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
