### ISSUE TITLE
Failed to get 'appData' path

### ISSUE THREAD

**Issue by ileler** [electron/electron#10054]
* Electron version: 1.6.11
* Operating system: WIN10

### Expected behavior
![733c1ee9-1c37-470a-a2f1-5b369084b895 _](https://user-images.githubusercontent.com/3371163/28317142-56a441ee-6bf8-11e7-88db-396389d6ca9c.jpg)

### How to reproduce
```bash
cnpm i -g electron
electron -v
```

**Comment by zeke** [comment]
I see the path in your screenshot starts with `I:` Are you installing electron on a path to which you may not have write access?

**Comment by MarshallOfSound** [comment]
I also see the install path is `.1.6.11@electron`, that looks wrong to me.

**Comment by ileler** [comment]
I was done with an administrator user. @zeke

**Comment by ileler** [comment]
？？？-n-

**Comment by codebytere** [comment]
@ileler if it was installed as admin i'm also inclined to think that @MarshallOfSound is correct in saying that you have an issue in your install path.

**Comment by ileler** [comment]
i work in mingw on window 10...  
i run `npm i -g electron` also in mingw..  
  
  
run in mingw:
![e1](https://user-images.githubusercontent.com/3371163/28852547-871a2f86-775c-11e7-81c6-f47470aaa90f.png)  

run in cmd:  
![e2](https://user-images.githubusercontent.com/3371163/28852550-893d192c-775c-11e7-9d67-15db22fccdcb.png)

**Comment by crazy-max** [comment]
@ileler, What is the value of `$USERPROFILE` ?

**Comment by ileler** [comment]
@crazy-max `/u/u~u/a0a/.rc`
![qq](https://user-images.githubusercontent.com/3371163/30018848-0d50cc88-9191-11e7-9f9f-ab99e0988755.png)

**Comment by crazy-max** [comment]
Try to override `$USERPROFILE` env var to `C:\Users\Administrator`
Btw what is the values of `$HOME`, `$HOMEDRIVE`, `$HOMEPATH`.

**Comment by ileler** [comment]
![qq](https://user-images.githubusercontent.com/3371163/30019572-a465658c-9193-11e7-94ca-b396d4b1af09.png)

**Comment by crazy-max** [comment]
Ok if you type `mkdir -p $USERPROFILE/AppData/Roaming` does it work now ?

**Comment by ileler** [comment]
![qq](https://user-images.githubusercontent.com/3371163/30019847-7c05b30c-9194-11e7-9116-7c7911f28f66.png)
hahah,,,,get!Thx,,,but why???

**Comment by ileler** [comment]
@crazy-max Why electron not automatically exec ‘mkdir’ to create

**Comment by crazy-max** [comment]
@ileler Maybe @zeke @zcbenz have the response but for me there is an issue in Electron.
On Windows, Electron should take the `appData` from the env var `%APPDATA%` and not from Chromium (which is taken from USERPROFILE). The doc of [app.getPath](https://github.com/electron/electron/blob/6b010614e24d497b3976d5118c314d05b9e54afc/docs/api/app.md#appgetpathname) for Windows is wrong : `%APPDATA% on Windows`. In fact it is rather `%USERPROFILE%\AppData\Roaming`.

**Comment by ileler** [comment]
@crazy-max Yes, I agree with you

**Comment by robinwassen** [comment]
I think this issue can be closed as a machine configuration issue.

`electron : app.GetPath("appData")` ([src](https://github.com/electron/electron/blob/master/atom/browser/api/atom_api_app.cc#L784)) calls 
`chromium : PathService::Get(DIR_APP_DATA, &path);` ([src](https://chromium.googlesource.com/chromium/src/base/+/master/base_paths_win.cc#109)) which calls 
`windows : SHGetFolderPath(NULL, CSIDL_APPDATA, NULL, SHGFP_TYPE_CURRENT, system_buffer)` 

This should resolve to the following example: **C:\Users\username\AppData\Roaming**

Looking at the Chromium documentation for PathService::Get() creating dirs and errors seems to be handled correctly too:

    // Retrieves a path to a special directory or file and places it into the
    // string pointed to by 'path'. If you ask for a directory it is guaranteed
    // to NOT have a path separator at the end. For example, "c:\windows\temp"
    // Directories are also guaranteed to exist when this function succeeds.
    //
    // Returns true if the directory or file was successfully retrieved. On
    // failure, 'path' will not be changed.
    static bool Get(int key, FilePath* path);

Normal configuration of Windows outputs the following:

	PS C:\Users\robin> Get-Item Env:AppData

	Name                           Value
	----                           -----
	APPDATA                        C:\Users\robin\AppData\Roaming


	PS C:\Users\robin> Get-Item Env:UserProfile

	Name                           Value
	----                           -----
	USERPROFILE                    C:\Users\robin

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by TheIncorrigible1** [comment]
I saw this issue on the latest version of VSCode.  My issue was with corrupted environment variables, namely `%USERPROFILE%` on Windows where it was being changed in my PowerShell profile.  Correcting its value fixed the error seen in the OP.

**Comment by jamesxsc** [comment]
Hi,
I am having the same issue when running software that uses electron. It is of note that this is a domain network running roaming userprofiles and folder redirection however everything else works fine and it is not a UNC path. Weirdly, this only happens on some of our workstations... Any solutions? I have tried the `mkdir` solution to no avail.

**Comment by mburszley** [comment]
@jamesxsc ensure your environment variables are correct for the process context.  I'm in a similar environment and that was what resolved it for me.

**Comment by Aminechakr** [comment]
Hello,
We facing an issue in with the failed get 'appData' 

**Context** :
 We using a Markdown documentation, that is running under a Docker container, and we wan't to display our Draw.io diagrams _(*.drawio)_ under mkdocs instead of images _(*.png)_,

 We added the [draw.io plugin](https://pypi.org/project/mkdocs-drawio-exporter) and the draw.io executable so it can run. 

But we end up with a dependancy with electron ?

**environement** : 
Mk Docs : 1.1
Python : 3.6
DrawIO : 13.6.2
Debian Image
xvfbwrapper:  0.2.9


**Issue** : 

``Error: Failed to get 'appData' path
    at App.l._setDefaultAppPaths (electron/js2c/browser_init.js:5:1420)
    at Object.<anonymous> (electron/js2c/browser_init.js:205:2348)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:205:3577)
    at __webpack_require__ (electron/js2c/browser_init.js:1:128)
    at electron/js2c/browser_init.js:1:1200
    at electron/js2c/browser_init.js:1:1267
    at NativeModule.compile (internal/bootstrap/loaders.js:287:5)
    at NativeModule.compileForPublicLoader (internal/bootstrap/loaders.js:222:8)
    at loadNativeModule (internal/modules/cjs/helpers.js:23:9)
    at Module._load (internal/modules/cjs/loader.js:698:15)[0m``
 
Thanks.
