### ISSUE TITLE
WebRequest: Request from which Webview?

### ISSUE THREAD

**Issue by Devhercule** [electron/electron#10061]
Hi, 
I have a quick and urgent question:

I'm using WebRequest to intercept requests

I have only one BrowserWindow with many webviews.

How Is it possible to know from which webview a request is sent?

Thank you in advance

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

Not currently afaik.  You can, however, assign each webview it's own `partition` and get the `webRequest` instance of each session individually.

**Comment by Devhercule** [comment]
thank you
