### ISSUE TITLE
Copy and Paste From app Content depends on keyboard layout language

### ISSUE THREAD

**Issue by motakbiri** [electron/electron#10060]
* Electron version: 1.6.5
* Operating system: Windows 7

I have the problem that completely explained in this question on StackOverflow

https://stackoverflow.com/questions/45170185/setting-default-keyboard-layout-for-electron-application-on-windows-unable-to-c

**Comment by jkleinsc** [comment]
Issue description from StackOverflow:

> We have this problem where a Farsi UTF-8 text that is programmatically copied from an electron application, loses encoding when pasted into one specific application and is displayed as a set of ? characters. The issue persists even with manual text selection and copy command invoked via either context menu or Ctrl+C. Texts copied from other sources such as browsers or text editors are transferred just fine.
>
> We tried clipboard API of electron. We also implemented our own helper to verify the issue is not with the clipboard itself.
> 
> We also prepended the text with UTF-8 BOM character before writing it to the clipboard.
> 
> One interesting observation was that once the text is pasted into some text editor and then recopied, target app received the text properly. We also noticed that changing the keyboard layout to target language when the electron app is focused, resolves the issue as well. In addition, we realized that Windows changes default keyboard layout to English when the application is launched.
> 
> Following on these clues, we configured NSIS bundler to set the default language to Persian so that maybe Windows detects it as default keyboard language as well. Description of the application shows Persian as the language but Windows does not respect it and reverts the language to system default upon launch.
> 
> We tried running a script on application startup to mimic a Farsi character keyboard input, creating temporary input fields, and a set of other hacks to maybe trick the Windows/application into properly handling these texts. Keep in mind we can't rely on user to perform idiotic actions on every application launch, to fix a problem that shouldn't exist in first place. That's why we need this issue to be resolved programmatically.
> 
> Right now the only solution that comes to mind is to force Windows to set the keyboard layout for our application to Persian via registry entries by some separate script that user need to run only once, or can be run after each installation. I'm not familiar with the windows registry entries. My searches came up empty and the results were focused on how to do it for the whole system, but we don't wanna mess with their whole system configurations since.
> 
> Any other suggestions regarding this issue is highly appreciated.
> 
> Other information that you might find relevant:
> 
> OS is Windows 7.
> Target app is an accounting software and the vendor rejects to provide any support with the integration, so I have very little information about inner workings of that application.
> html lang attribute of electron template is set to fa.
> meta charset attribute is set to utf-8.
> Application is bundled with electron-builder and NSIS.

**Comment by motakbiri** [comment]
I think this issue related to [#5649](https://github.com/electron/electron/issues/5649)

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
