### ISSUE TITLE
Uncaught Error: Cannot find module '../Read/Files.js'

### ISSUE THREAD

**Issue by Spyrock** [electron/electron#10077]
Hi, i'm try to import a file from other file, check the code:

### HTML

```html
<button onclick="x.method()">Click me</button>
<script src="js/Encryptor/EncryptFiles.js"></script>
```

### JavaScript file ("EncryptFiles.js")

```javascript
import Files from '../Read/Files.js'

class EncryptFiles extends Files {
    constructor() {
        super()
    }
    method() {
        console.log(this.OpenFile())
    }
}
const x = new EncryptFiles()
```

### the other file, ("Files.js")

```javascript
const { dialog } = require('electron').remote

export default class Files {
    OpenFile() {
        dialog.showOpenDialog({
            properties: ['openFile', 'multiSelections'],
            title: 'Eliga los archivos',
            filters: [
                { name: 'Todos los archivos', extensions: ['*'] }
            ],
            showHiddenFiles: true,
        }, (files) => files)
    }
}
```

and show this error the chrome console:

![Error](http://i.imgur.com/khjQSV2.png)

Directories:

![Directories](http://i.imgur.com/EqL4ajp.png)

Please help me 😢

**Comment by enlight** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by Spyrock** [comment]
please help me men :(
