### ISSUE TITLE
node Integration is set to false, but I need the renderer process and the main process communication. But if enabled the nodeIntegration then on application start I am getting deferredBootstrapper is not defined

### ISSUE THREAD

**Issue by neha136** [electron/electron#10074]
* Electron version:
* Operating system:

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

FWIW you can set up that communication in a preload script even if node integration is disabled
