### ISSUE TITLE
alwaysOnTop over other fullscreen apps

### ISSUE THREAD

**Issue by robsontenorio** [electron/electron#10078]
* Electron version: 1.6
* Operating system: OSX

### Expected behavior
The browser window must be on top over all OS windows, even fullscreen apps.
### Actual behavior

The BrowserWindow disappears when other app enters in fullscreen mode.

### How to reproduce

Just create a normal (not fullscreen) BrowserWindow 

```
BrowserWindow({
 alwaysOnTop: true
 width: 250,
 height: 500,
....
})
```
Put any other app on fullscreen mode. The BrowserWindow disappears.

**Comment by MarshallOfSound** [comment]
@robsontenorio This is by OS design, windows can't appear on top of other fullscreen windows.  You might be able to get it on top by setting the `level` argument in `setAlwaysOnTop` but as far as I am aware the actual coordinates of a fullscreen window are not accessible to other windows.

https://electron.atom.io/docs/api/browser-window/#winsetalwaysontopflag-level-relativelevel

**Comment by robsontenorio** [comment]
@MarshallOfSound So, do you mean that is not possible to create a "overlay window" by using Electron?

I have tried each "level" , with no success:(

**Comment by MarshallOfSound** [comment]
@robsontenorio I don't believe it is possible on macOS.  Fullscreen apps operate outside the bounds of other applications.  I don't think even a completely native app could render on top of a full screen app.

**Comment by robsontenorio** [comment]
@MarshallOfSound yes , native app can!

Check this out https://github.com/HearthSim/HSTracker

It put a small overlay over any fullscreen app. 

1. Open it
2. Put any app in fullscreen mode 
3 See a small retangle over full screen ap

**Comment by jsherwani** [comment]
Definitely interested in this as well!

**Comment by robsontenorio** [comment]
This problem is not exclusive from OSX. On Windows or Linux, just put a PDF on presentation mode (fullscreen) or even a Powerpoint, and Electron app will not stay on top.

**Comment by pchw** [comment]
I found the solution!

finally my app keep always on top over full screen app using following codes:
```
app.dock.hide();
mainWindow.setAlwaysOnTop(true, "floating");
mainWindow.setVisibleOnAllWorkspaces(true);
mainWindow.setFullScreenable(false);
```

`NSWindowCollectionBehaviorFullScreenAuxiliary` is for `over full screen app`.
To set `NSWindowCollectionBehaviorFullScreenAuxiliary` in Electron app, call `setFullScreenable(false)`.

**Comment by singhshashi** [comment]
While the above solution by @pchw does work, hiding the app from the dock ends up being confusing if you are used to using Command + Tab to switch between apps.

**Comment by johev09** [comment]
@pchw I suppose the solution is not working in macOS Sierra (version 10.12.6). I also tried with other levels and setting relativelevel to 1 or above, but nothing helped in showing my app over fullscreen apps. Although the app [Helium](http://heliumfloats.com/) is able to stay on top of fullscreen apps.

**Comment by mansona** [comment]
It seems like the magic for Helium is this bit of code (but I'm not a swift developer so I don't even know if this is true): 

```
	private func setFloatOverFullScreenApps() {
        if NSUserDefaults.standardUserDefaults().boolForKey(UserSetting.DisabledFullScreenFloat.userDefaultsKey) {
            panel.collectionBehavior = [.MoveToActiveSpace, .FullScreenAuxiliary]

        } else {
            panel.collectionBehavior = [.CanJoinAllSpaces, .FullScreenAuxiliary]
        }
    }
```
found here: https://github.com/JadenGeller/Helium/blob/b35a416376dee7184f788e6ae5736f19890d3ddc/Helium/Helium/HeliumPanelController.swift#L122

Do people recognise these: `.CanJoinAllSpaces, .FullScreenAuxiliary` are they enums or something that can be set on new windows?

**Comment by singhshashi** [comment]
@johev09 were you using electron for your app? The code that you have posted above seems to be for a native Mac app using Obj-C.

**Comment by johev09** [comment]
@singhshashi The code is from electron's sources. I forked electron, edited the function, built it and used the release in my electron app. After that I was able to use
`mainWindow.setVisibleOnAllWorkspaces(true)`  to show my electron app on all workspaces (including fullscreen apps)

**Comment by mansona** [comment]
wow @johev09 that looks pretty spectacular 😍 

is it literally just adding that one function? any chance you could PR it so that we could keep the conversation moving forward. I'm not a macOS developer so I wouldn't even know where to put that snippet 😖

**Comment by johev09** [comment]
Already made the [PR](https://github.com/electron/electron/pull/11599#issuecomment-355974230) and waiting for it to be reviewed. 👍

**Comment by amitpatil321** [comment]
@johev09 : I have spent a day to solve reading electron docs but no luck, I also want my app to be on top of keynote app, I am developing app which shows audience question while presenter is using keynote.
   Can you please guide me (us) how can we compile our own electron and which file exactly we are supposed to change. Your help would be much appreciated. 
   If you can share your compiled electron through dropbox or google drive that will be great, but it would be more fun to learn how you compiled your own electron so in future also i/we can solve these type of problems. 

   Thanks in advance!

**Comment by robsontenorio** [comment]
The Electron Team refused PR from @johev09 :(

**Comment by mansona** [comment]
I think the PR was refused because it actually changed the default behaviour. We would have a better chance if that behaviour was configurable somehow 😕 like maybe pass in a parameter or change a global default in the app or something

**Comment by johev09** [comment]
@amitpatil321 The build instructions are given [here](https://github.com/electron/electron/tree/master/docs/development). You can use any editor (I used vscode) or IDE to search the  method `SetVisibleOnAllWorkspaces(bool)` in the electron sources, but to be specific the method is in [native_window_mac.mm](https://github.com/electron/electron/blob/master/atom/browser/native_window_mac.mm#L1625)

I think the electron team should consider adding this feature (show app over all apps including fullscreen apps) for mac, somehow in accordance with their guidelines, in their next version.

**Comment by amitpatil321** [comment]
@johev09 : Thanks for getting back, actually "screen-saver" mode solved my problem, now my app stays on top of keynote app but as soon as i click on my app(which is a child window) keynote app exits from presentation mode (because focus changes from), Do you think solution you found will work in my case. 
  Zoom meeting app window keeps itself on top of keynote app, and it doesnt closes keynote app, is it possible to achieve same thing with electron ? 

  More details here on stackoverflow :   [https://stackoverflow.com/questions/48367441/make-electron-window-able-to-receive-click-event-when-above-keynote-app/48373220#48373220](url)

**Comment by codebytere** [comment]
hey @johev09 late follow up on this, but we'd be way more likely to accept a PR for this if it made `alwaysOnTop` an option as opposed to a default; like @mansona said that's why it was originally refused.

**Comment by singhshashi** [comment]
Hi @johev09 were you also hiding the dock to achieve this? I am unable to get my app to show over other full screen apps unless I execute app.dock.hide(). Interestingly, Helium is able to stay on top of other full screen apps without hiding from the dock.

**Comment by ZAndyL** [comment]
@singhshashi after a bit of experimenting with Helium's xcode project, the trick was switching the panel style from regular panel to HUD panel of 'Window' in the storyboard.

**Comment by mansona** [comment]
@ZAndyL I'm sorry but I don't understand 😞 maybe it's because I'm not really a macOS developer so I avoid all those parts of it.

Are you saying that you can edit a config on an Electron app's xcode project and have this work? Or do you need to edit the source of Electron to get this to work?

**Comment by ajprax** [comment]
I've been working on an app that will have a spotlight-style quick access window for which I need this feature. To that end, I've been looking into the various suggestions from this thread and I figured I'd compile them in case they're helpful to anyone else, though I currently do not have a satisfactory solution for my needs.

All of my tests were run with MacOS 10.13.3 and Electron 1.8.3 (prebuilt and forked from the v1.8.3 tag)

### Window level
This seems to have no effect on whether your windows can display alongside other apps' fullscreen windows. It does affect whether it shows in front or behind those windows though, so it's still important to set your level high enough, though even the default (0) is high enough to show in front when focused.

### `app.dock.hide()`
With stock Electron this is the only way I've found to allow my windows to float over other apps' fullscreen windows. Unfortunately it also removes the dock icon (naturally) and prevents the app from showing in the cmd+tab menu. If you want regular windows that show in the dock and are accessible via cmd+tab in addition to popover windows that show anywhere, this won't work.

The key part of `hide()` that seems to make things work is:
```TransformProcessType(..., kProcessTransformToUIElementApplication);``` [[1](https://github.com/electron/electron/blob/master/atom/browser/browser_mac.mm#L263)]
UIElement applications include things like the dock itself and the top menu bar, which are allowed to show across "spaces".

From my experiments, this allows windows to float over other apps even without `setAlwaysOnTop` or `setVisibleOnAllWorkspaces`.

### NSWindowCollectionBehavior
The suggestion to set `NSWindowCollectionBehaviorFullScreenAuxiliary` in `setVisibleOnAllWorkspaces` doesn't seem to have any effect. `NSWindow.collectionBehavior` is a bitmask including `NSWindowCollectionBehaviorFullScreenAuxiliary` and `NSWindowCollectionBehaviorFullScreenPrimary`.  Simply adding `Auxiliary` results in both `Auxiliary` and `Primary` being set, and it's unclear to me what the expected behavior should be, but in practice neither setting both nor setting only `Auxiliary` seems to affect where my windows can go.

### Helium/NSPanel
Helium accomplishes this feature using an `NSPanel` [[2](https://developer.apple.com/documentation/appkit/nspanel)] while electron uses (as far as I've seen) exclusively `NSWindow` [[3](https://developer.apple.com/documentation/appkit/nswindow)]. `NSPanel` is a subclass of  `NSWindow` that seems to intrinsically have the properties we want. I created a little xcode app to test and I can make a regular `NSWindow` that opens on the nearest desktop and an `NSPanel` that opens on top of the current fullscreen app. I've only started looking into modifying electron to allow `BrowserWindow` to create an `NSPanel` but so far it looks like it won't be a trivial change. If someone with more experience with the Electron codebase has an idea how to make this happen, I think it's all that's required to make this feature possible.

**Comment by matt3224** [comment]
Is there any news on this, i'm looking to make an app that floats over the top exactly like the macos picture in picture functionality where the window is stuck and remains visible during the changing of screens or fullscreen apps

Perhaps electron v2 will add it?

**Comment by pandaGao** [comment]
I find that if you use @pchw 's solution to create a "real" alwaysOnTop window, after you create it you can just use `app.dock.show()` to get your dock icon back and this window is still "real" alwaysOnTop.
For example:
```javascript
// ......
app.dock.hide()
let alwaysOnTopWindow = new BrowserWindow(options)
alwaysOnTopWindow.setAlwaysOnTop(true, 'floating')
alwaysOnTopWindow.setVisibleOnAllWorkspaces(true)
alwaysOnTopWindow.setFullScreenable(false)
app.dock.show()
// ......
```
It's not a perfect solution, you can still see a short animation in dock.
Test with macOS 10.12.6 and electron 1.8.6

**Comment by tommoor** [comment]
> I've only started looking into modifying electron to allow BrowserWindow to create an NSPanel but so far it looks like it won't be a trivial change

@ajprax are you able to share where you got to with making NSPanel an option? I'm interested in taking this on or sponsoring a developer to do so.

**Comment by ajprax** [comment]
@tommoor I didn't get very far, and I haven't looked at it since posting my findings in April so I've got to page it back in.  The main things I remember are that there's a bridge between Electron's nodejs API and objc implementations (I think it was objc but I'm not that familiar with that side of the world so it could have been swift or some other mac-y native language). The native class that powers `BrowserWindow` inherited from `NSWindow`, and I assume the language isn't dynamic enough to allow swapping the superclass on the fly. My guess is that the best option would be to create a parallel class that inherits `NSPanel` (almost all of the functionality would probably be the same, so if this can be handled with a mixin or something it might not be that much code) and swap implementations based on a flag. I'm not familiar with the particular bridging system, so it might be necessary to create a separate API class alongside `BrowserWindow` and bridge it to the `NSPanel` based native implementation instead.

**Comment by codebytere** [comment]
Given that this isn't currently on our roadmap or planned roadmap, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR!

**Comment by SilencerWeb** [comment]
@codebytere [Paste](https://pasteapp.me/) did it somehow:

![image](https://user-images.githubusercontent.com/20713191/46252658-4c9f4180-c485-11e8-9dd5-dcc27f2021e7.png)
![image](https://user-images.githubusercontent.com/20713191/46252661-59bc3080-c485-11e8-904f-fcaf11e14d51.png)

**Comment by codebytere** [comment]
@SilencerWeb Paste is a native mac app :)

**Comment by SilencerWeb** [comment]
@codebytere okay, but for now I would recommend everybody else to use @pandaGao's solution. Works perfectly for me, macOS 10.13.6, electron 3.0.0

Here is how I did without creating new window every time:
```js
// First you need to create a window
const successWindow = new BrowserWindow({
    width: 200,
    height: 200,
    resizable: false,
    movable: false,
    focusable: false,
    alwaysOnTop: true,
    show: false,
  });

  // Then you need to show it whenever you need it
  if (!successWindow.isVisible()) {
    app.dock.hide();
    successWindow.showInactive();

    // And also hide it after a while
    setTimeout(() => {
      successWindow.hide();
      app.dock.show();
    }, 1000);
  }
```

**Comment by tommoor** [comment]
Hey everyone, I just open sourced a module which in my testing allows creation of `NSPanel` windows on Mac (it's a no-op on other platforms right now). Take a look and let me know if it helps out:

https://github.com/goabstract/electron-panel

**Comment by codebytere** [comment]
Closed as this is now [in master](https://github.com/electron/electron/blob/master/atom/browser/native_window_mac.mm#L804).

**Comment by vifird** [comment]
@codebytere So now we can do it without `app.dock.hide()`?

**Comment by ram2349** [comment]
Hi,
I'm working on an application where a floating icon (for the desktopapp) to be always showed on desktop, similar to snagit or jing apps. I'm using electron js. Any guidance will be helpful.

Thanks,

**Comment by amitpatil321** [comment]
Use screen saver mode
*Sincerely, *
Amit Patil
http://www.amitpatil.me


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
09/05/19,
12:04:07 AM

**Comment by jetlej** [comment]
+1

**Comment by mrafei** [comment]
`alwaysOnTop` option still doesn't go on top of fullscreen apps like video players. please help!

**Comment by zquancai** [comment]
> `alwaysOnTop` option still doesn't go on top of fullscreen apps like video players. please help!

it works on the beta version, I just test v12.0.0.beta-11

https://github.com/electron/electron/pull/24956

**Comment by mrafei** [comment]
I cannot confirm that it works on the beta version. my current config for the window is:
`  workerWindow.loadURL("file://" + __dirname + "/assets/printerWindow.html");
  workerWindow.hide();
  notifWindow = new BrowserWindow({
    width: 240,
    height: 135,
    // show: false,
    transparent: true,
    frame: false,
    focusable: false,
    x: width - 250,
    y: height - 195,
    alwaysOnTop: true,
    resizable: false,
    webPreferences: {
      nodeIntegration: true,
    },
  });
  notifWindow.loadURL("file://" + __dirname + "/assets/notification.html");
  app.dock.hide();
  notifWindow.setAlwaysOnTop(true, "floating", 1);
  notifWindow.setVisibleOnAllWorkspaces(true, {visibleOnFullScreen: true});
  notifWindow.setFullScreenable(false);
  notifWindow.maximize()`
and still the window does not go on top of other full screen apps.

**Comment by aabuhijleh** [comment]
@mrafei I'm having the same issue. Did you test this on Windows too?

On Windows, `.showInactive()` does not work at all. If I use `.show()` it works for me but for some users it does not work.

I opened an issue here #25388 but it's not active

**Comment by OferSisso1** [comment]
> > > `alwaysOnTop` option still doesn't go on top of fullscreen apps like video players. please help!
> > 
> > 
> > it works on the beta version, I just test v12.0.0.beta-11
> > #24956
> 
> I cannot confirm that it works on the beta version. my current config for the window is:
> 
> ```js
> notifWindow = new BrowserWindow({
>   width: 240,
>   height: 135,
>   // show: false,
>   transparent: true,
>   frame: false,
>   focusable: false,
>   x: width - 250,
>   y: height - 195,
>   alwaysOnTop: true,
>   resizable: false,
>   webPreferences: {
>     nodeIntegration: true,
>   },
> });
> notifWindow.loadURL("file://" + __dirname + "/assets/notification.html");
> app.dock.hide();
> notifWindow.setAlwaysOnTop(true, "floating", 1);
> notifWindow.setVisibleOnAllWorkspaces(true, {visibleOnFullScreen: true});
> notifWindow.setFullScreenable(false);
> notifWindow.maximize()
> ```
> 
> and still the window does not go on top of other full screen apps.

calling `setVisibleOnAllWorkspaces` before `setAlwaysOnTop` fixed it for me

**Comment by mrafei** [comment]
@OferSisso1 Actually it still doesn't work on windows according to docs `setVisibleOnAllWorkspaces` does nothing. still looking for an answer.

**Comment by CodyBontecou** [comment]
Hmm, I'm working with `"electron": "^15.3.0"`

and the following window config:

```
win = new BrowserWindow({
    width: 100,
    height: 200,
    x: 0,
    y: 0,
    frame: false,
    autoHideMenuBar: true,
    transparent: true,
    alwaysOnTop: true,
    resizable: false,
    webPreferences: {
      preload: __dirname + '/preload.js',
    },
  })

app.dock.hide()
win.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: true })
win.setAlwaysOnTop(true, 'modal-panel')
```

and it's not overlaying full screen or borderless applications.

**Comment by amitpatil321** [comment]
Screen saver mode works fine for overlapping all other application windows

**Comment by nomis51** [comment]
> Screen saver mode works fine for overlapping all other application windows

On Windows, using screen-saver works (others don't) with either non-maximized, maximized and fullscreen window.
Note I was working on an overlay for a game running in windowed fullscreen.

```js
const win = new BrowserWindow({
        transparent: true,
        fullscreen: true, // remove if you don't need a fullscreen window
        maximizable: true,
        minimizable: false,
        focusable: false,
        skipTaskbar: true,
        alwaysOnTop: true,
        frame: false,
});

win.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: true });
win.setAlwaysOnTop(true, 'screen-saver', 1);
// win.maximize(); use this, if you don't need fullscreen but only a maximized window
```

**Comment by mqliutie** [comment]
In my case I found some points that need attention. 
sys: macOS Big Sur  11.5.2
electron: 12.1.1

1. No need to  call `app.dock.hide`
2. No need to call `setFullScreenable` 
3. The order of `setVisibleOnAllWorkspaces` and `setAlwaysOnTop` no relation
4. The second params of `setVisibleOnAllWorkspaces` must set `{visibleOnFullScreen: true}`
5. Do not sync call `setVisibleOnAllWorkspaces(false)` after showing.

**Comment by Deamoner** [comment]
For anyone in the future who also doesn't want the window to shift workspaces on mac when it opens as an overlay. You should also do `show: false`. The window showing is what is taking focus, but having it always on top and on all workplaces you can see it anyways so you don't need it to show and take focus.

**Comment by denislaca** [comment]
In case it's still not working for you:

```
    app.dock.hide();
    const overlayWindow = new BrowserWindow({
        show: false,
        maximizable: false,
        resizable: false,
        fullscreenable: false,
        alwaysOnTop: true,
    });
    overlayWindow.setAlwaysOnTop(true, 'screen-saver');
    overlayWindow.setVisibleOnAllWorkspaces(true, {
        visibleOnFullScreen: true,
    });
    app.dock.show();
```

You only need to hide the dock when creating the window and setting the options. This way you can keep the app in dock on macOS.

**Comment by harismuha123** [comment]
@denislaca does this work for you in production? It works perfectly for me when in dev mode but as soon as I build it, something breaks and I can't reproduce the behavior anymore.

**Comment by vingeraycn** [comment]
I found a solution of this issue which works to me, try set `type: panel` in BrowserWindowConstructorOptions.

It works on macOS 14, not test on Windows OS yet.

```
const win = new BrowserWindow({
 ...
 type: 'panel',
 ...
})
```
![image](https://github.com/electron/electron/assets/19839331/c21b0f93-2318-4796-8224-12547f864e14)

**Comment by StillFill** [comment]
@vingeraycn yeah, but i tested and on fullscreen games for example, it not appears, just if i configure the game to borderless

**Comment by codebycarlos** [comment]
Could this please be re-opened? This is clearly still an issue with Mac builds.

**Comment by uuuuua** [comment]
I have a unique idea, but not sure about the performance。
`setInterval(() => {
    win .setAlwaysOnTop(false);
    win .setAlwaysOnTop(true, "screen-saver");
  }, 3000);`

**Comment by Nickhoyer** [comment]
> @vingeraycn yeah, but i tested and on fullscreen games for example, it not appears, just if i configure the game to borderless

Same result here. With help from this thread I'm able to overlay borderless games and fullscreen browsers, but not fullscreen games unfortunately.

**Comment by StillFill** [comment]
Yeah, i get further in this issue, but the answer that i found was that is impossible to render something from the PC inside games, because when a game is in fullscreen configuration is created a new environment to the game run, that's why you need to develop the screen inside directX to render together with the game

That's why when you change apps when in a fullscreen game, we can see a blink before go to the desktop

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by HeartArmy** [comment]
Had a look a this thread to solve my issue:

## What worked for me

Use these specific settings to enable `NSWindowCollectionBehaviorFullScreenAuxiliary` behavior:

### 1. Hide Dock Icon (Menu Bar App)

```javascript
// In your app initialization, after app.whenReady()
if (process.platform === 'darwin') {
  app.dock.hide();
}
```

### 2. Configure BrowserWindow

```javascript
const mainWindow = new BrowserWindow({
  width: 400,
  height: 800,
  show: false,
  frame: false,
  transparent: true,
  resizable: false,
  skipTaskbar: true,
  alwaysOnTop: true,
  type: 'panel', // ⭐ Critical for fullscreen support
  webPreferences: {
    nodeIntegration: false,
    contextIsolation: true,
    preload: path.join(__dirname, 'preload.js')
  }
});
```

### 3. Set Window Behavior

```javascript
// Make window appear above fullscreen apps
mainWindow.setAlwaysOnTop(true, 'floating');
mainWindow.setVisibleOnAllWorkspaces(true);
mainWindow.setFullScreenable(false); // ⭐ Sets NSWindowCollectionBehaviorFullScreenAuxiliary

// Optional: Prevent minimizing
mainWindow.setMinimizable(false);
```

## Complete Example

```javascript
const { app, BrowserWindow } = require('electron');

class MyApp {
  async initialize() {
    await app.whenReady();
    
    // Hide dock icon for menu bar app
    if (process.platform === 'darwin') {
      app.dock.hide();
    }
    
    this.createMainWindow();
  }
  
  createMainWindow() {
    this.mainWindow = new BrowserWindow({
      width: 400,
      height: 800,
      show: false,
      frame: false,
      transparent: true,
      resizable: false,
      skipTaskbar: true,
      alwaysOnTop: true,
      type: 'panel', // Critical for fullscreen
      webPreferences: {
        nodeIntegration: false,
        contextIsolation: true,
        preload: path.join(__dirname, 'preload.js')
      }
    });

    // Configure fullscreen behavior
    this.mainWindow.setAlwaysOnTop(true, 'floating');
    this.mainWindow.setVisibleOnAllWorkspaces(true);
    this.mainWindow.setFullScreenable(false);
    this.mainWindow.setMinimizable(false);

    this.mainWindow.loadFile('index.html');
  }
}

const myApp = new MyApp();
myApp.initialize();
```
