### ISSUE TITLE
GPU Cache not working

### ISSUE THREAD

**Issue by andresiraola** [electron/electron#10072]
* Electron version: 1.7.4
* Operating system: Win 10 - 1703

### Expected behavior

Cached shaders in the "GPU Cache" folder should be reloaded when Electron is loaded

### Actual behavior

The compiled shaders read from the GPU Cache are discarded at startup because the cache entry key's prefix doesn't match the one calculated by the GpuProcessHost. This happens because the gpu::GPUInfo structure is not still populated when the disk cache is read but it is when the cache is written.

To walkaround this, Chrome uses a GpuProfileCache that populates temporarily the GPUInfo structure based on previous executions. This GpuProfileCache is not yet implemented in Electron.

I started implementing it to create a PR but then I realized it is more tricky than I thought. We need a local state than needs a policy service which is also not implemented in electron yet and the policy headers are not even distributed in libchromiumcontent.

As our application is heavily based on webgl and so, we need the gpu cache working, I ended up patching GpuProcessHost::GetShaderPrefixKey() to ignore the unavailable data at startup. Even though it works, this might be a source of problems in the future.

### How to reproduce

1) Link a very big shader (which would take time).
2) Close electron
3) Reopen electron. If the cache is working, the shader linking should take nothing compared to step 1.

We noticed that the shader compilation was talking too long at every execution. Then we noticed that the GPU Cache was almost cleaned in every execution and rewritten again. So I built 1.7.4 from the sources and debugged electron. That's when I realized the prefix issue.

If you have any question about the issue or how to solve it. Please don't hesitate to ask me.

Note: the GpuProfileCache is instanced in chrome/browser/browser_process_impl.h

**Comment by andresiraola** [comment]
@jkleinsc you tagged this issue as "enhancement" when in fact it is bug. The lack of implementation prevents the gpu cache from working correctly or from working at all.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
