### ISSUE TITLE
Set webPreferences after new BrowserWindow on the fly

### ISSUE THREAD

**Issue by leiqiao0** [electron/electron#10080]
* Electron version: 1.6.11
* Operating system: Ubuntu 16.04

### Expected behavior

Set webPreferences after new BrowserWindow on the fly

### Actual behavior

```
let myWindow = new BrowserWindow(webPreferences = {
    nodeIntegration: true
});
if (sometimes) {
  myWindow.webPreferences = {
      nodeIntegration: false
  };
}
```
is not working

**Comment by MarshallOfSound** [comment]
@leiqiao0 Lots of `webPreferences` options are things that can't be changed at run time, things like `sandbox` and `nodeIntegration` are set at creation time and can't be changed for technical reasons.

For instance disabling `nodeIntegration` deletes all node.js globals in the `webContents`, once deleted they can't be recovered (that would defeat the purpose of disabling it).  If you need to adjust the nodeIntegration setting I would suggest reviewing your use case and potentially using `webview`'s or multiple BrowserWindow's

**Comment by leiqiao0** [comment]
@MarshallOfSound Thanks!

**Comment by jmercouris** [comment]
@MarshallOfSound  what about things that *can* be enabled and disabled at run-time? Things like support for images?

**Comment by jmercouris** [comment]
@MarshallOfSound any  response?
