### ISSUE TITLE
<webview> Table page-break-* has no effect when printToPdf()

### ISSUE THREAD

**Issue by khacminh** [electron/electron#10086]
* Electron version: 1.6.11
* Operating system: macOS Sierra

### Expected behavior

I have electron webview.printToPdf() to print out my web page. Every thing works fine, but a long table. I use the following CSS:

```
@media print {
  table { page-break-after:auto; }
  tr    { page-break-inside:avoid; page-break-after:auto }
  td    { page-break-inside:avoid; page-break-after:auto }
  thead { display:table-header-group; page-break-before: always; }
  tfoot { display:table-footer-group; page-break-before: always; }  
}
```

This work fine when I print from Google Chrome.

### Actual behavior

However, on electron, the page-break-* has no effect and my table becomes as:
<img width="932" alt="screen shot 2017-07-21 at 11 01 49 pm" src="https://user-images.githubusercontent.com/13713865/28473174-b57cc43a-6e6d-11e7-82c9-d10004334633.png">

**Comment by cristiammercado** [comment]
- Electron version: 1.7.5
- Operating system: Windows 10 (x64)

In Windows this problem also occurs!

**Comment by cristiammercado** [comment]
Testing with beta version 1.8.1 the error could no longer reproduce.

**Comment by chiaramdelucia** [comment]
Hi! Is there any update on this issue? 

I'm using:
-  Electron 1.7.6
- OS: Mac 10.11.6

The page-break rule has no effect in this version as well. Has anyone figured out how to do this in versions before 1.8.1?

**Comment by eleddie** [comment]
Still happening with electron: 1.8.3 and macOS High Sierra: 10.13.3.
Can't break pages.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by alxmrtnz** [comment]
@eleddie Were you able to get page breaks working? I'm having the same issue. `page-break-before`/`page-break-after` don't do anything to actually cause `printToPdf()` to generate a pdf with the page breaks where they should be
