### ISSUE TITLE
Windows 10 Music Player popup?

### ISSUE THREAD

**Issue by ErraticFox** [electron/electron#10084]
Is it possible to access / use the Windows 10 Music Player popup with an Electron app? The popup in question: 
![Win10 Music Player Popup](http://i.imgur.com/eMVZlDv.png)

**Comment by MarshallOfSound** [comment]
@ErraticFox You can interface with that part of Windows 10 using the @nodert-win10 modules

See https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/da99d1a5dbd681bbe447bfa04ac659705790da12/src/renderer/windows/GPMWebView/playback/systemMediaService/win10.js for an example

**Comment by ErraticFox** [comment]
Now checking on it, I don't think that has anything to do with that popup I showed in the picture. As I just downloaded the GPMD and it doesn't have this functionality...

**Comment by MarshallOfSound** [comment]
It does have that functionality, you just have to enable it in desktop settings.  Btw I wrote GPMDP so I'm 100% sure that that code implements the interface you screenshotted.

**Comment by ErraticFox** [comment]
This works when I use Spotify. So wouldn't that mean I already had this enabled? When I tried out GPMDP, it was only giving me the toast at the bottom right. When I used my volume knob on my keyboard, it only showed the volume at the top left and not the full thing like in my screenshot.
