### ISSUE TITLE
shell.showItemInFolder opens parent folder instead of specified folder

### ISSUE THREAD

**Issue by Raul6469** [electron/electron#10095]
* Electron version: v1.6.11
* Operating system: Windows 10.0.15063

### Expected behavior

When you call `shell.showItemInFolder("C:\\mainFolder\\myFolder")` for example, the file explorer should open in `myFolder`.

### Actual behavior

Instead of that, the parent folder is opened in the file explorer, ie `mainFolder` in the example above.

### How to reproduce

Simply by executing `shell.showItemInFolder("folder\\of\\your\\choice")` in the renderer process.

It is possible to get around this problem by adding `\\anything` at the end of the path, where `anything` is not a existing folder or file. (`shell.showItemInFolder("C:\\mainFolder\\myFolder\\pineapple")` will open `myFolder`)

**Comment by MarshallOfSound** [comment]
This is expected behavior, the `showItemInFolder` API is similar to Explorers "show containing folder" button.  It shows the folder that contains the given item and highlights the item if it exists.

If you just want to open a folder you should use `shell.openItem`

**Comment by Raul6469** [comment]
My bad, thanks
