### ISSUE TITLE
Frameless window cannot call maximize on Windows if set resizable when constructing

### ISSUE THREAD

**Issue by wmin0** [electron/electron#10098]
* Electron version: v1.6.11
* Operating system: windows 7

### Expected behavior

1. Frameless BrowserWindow set resizable when constructing
2. window set resizeable true after open it.
3. window calling maximize will change isMaximized state and then it can call unmaximize to restore window size.

### Actual behavior

1. Frameless BrowserWindow set resizable when constructing
2. window set resizeable true after open it.
3. window calling maximize will setSize as large as screen bounds without change maximized state.

Interestingly, you can right click div with "-webkit-app-region: drag;" and get native menu. The maximize item on the menu works fine!

### How to reproduce

  $ git clone https://github.com/wmin0/electron-quick-start.git -b frameless-bug-report
  $ npm install
  $ npm run start

you can click green button at left top corner, if the isMaximized state is right, it will change to purple button.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
