### ISSUE TITLE
Electron 1.7.5 beta prints some weird warning message

### ISSUE THREAD

**Issue by stanleyxu2005** [electron/electron#10093]
After upgrading from 1.7.4 to 1.7.5, I see some weird warning message in output log. This is the first time I see, that I upgrade Electron runtime always a new version is release. Can it be possible that some compiler switch not set correctly?

On Windows 7 (x64), this message:
> [7656:0723/150855.557:ERROR:gles2_cmd_decoder.cc(17403)] [.DisplayCompositor-0000000004301580]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIU
> M: invalid mailbox name
> [7656:0723/150855.557:ERROR:gles2_cmd_decoder.cc(9636)] [.DisplayCompositor-0000000004301580]RENDER WARNING: texture bound to texture unit 0 is not renderable.
>  It maybe non-power-of-2 and have incompatible texture filtering.

On MacOS Sierra (10.12.6), this message:
> Electron Helper[1230:80932] Couldn't set selectedTextBackgroundColor from default ()

**Comment by enlight** [comment]
The messages you see on Windows 7 are the same as those in #10147 and #6032, I suggest looking there to see if anything sounds relevant.

The message on MacOS is probably a Chromium bug, #4420 provides a workaround you could try.

**Comment by stanleyxu2005** [comment]
Hi @enlight, the error message can be produced both on Windows and MacOS. And I mentioned, the message I saw was not appear when using 1.7.4. I'm afraid this is not the same as #10147 and #6032.

**Comment by enlight** [comment]
Do you see these messages in 1.7.6?

**Comment by stanleyxu2005** [comment]
@enlight so far it is fine on Windows.
