### ISSUE TITLE
child_process execSync and which doesn't work with custom commands.

### ISSUE THREAD

**Issue by nicolabortignon** [electron/electron#10094]
Dear all, 
I'm trying to execute the following code:

`require('child_process').execSync('which sb').toString();`

Please consider that sb is a custom command that I've installed separately in this location: 

> /usr/local/bin/sb

When I try to run that command inside a try-catch, in dev mode, it works and return the correct location.
When I packaged it the command throw the following error:

`
Command failed: which sb
    at checkExecSyncError (child_process.js:493:13)
    at Object.execSync (child_process.js:533:13)
    at Object.childProcess.(anonymous function) [as execSync] (ELECTRON_ASAR.js:685:22)`

Also, when instead of **which sb** i run **which ping** the command works both in dev and post packaged.

I'm currently running this on a 
"electron": "^1.6.10" app
on OSX Sierra, 10.12.5
with node 8.1.0 installed 

Thanks in advance for the help

**Comment by MarshallOfSound** [comment]
Child processes inherit environment variables when spawned.  This includes the PATH variable that `which` uses to find binaries.  On macOS GUI applications do not get the full PATH variable when launched normally (not from terminal).

You can fix this using an npm module https://www.npmjs.com/package/fix-path
