### ISSUE TITLE
ipcRenderer.send stops functioning in VS Code tests on Windows 10

### ISSUE THREAD

**Issue by Tyriar** [electron/electron#10107]
* Electron version: 1.7.4
* Installed NodeJS version: 7.9.0
* Operating system: Windows 10

### Expected behavior

Tests should pass

### Actual behavior

Tests fail because ipcRenderer.send stops working.

### How to reproduce

```
git clone https://github.com/Microsoft/vscode.git
cd vscode
git checkout electron/1.7.4-log
scripts\npm.bat i
npm run watch
```

When watch has finished, in another terminal:

```
scripts\test.bat --debug --reporter dot
```

I added logs on IPC calls send by the renderer process and received by the main process. You will notice that main stops receiving IPC calls at a random point.

![electron-ipc](https://user-images.githubusercontent.com/2193314/28549599-ff0d5bf4-708f-11e7-8541-d6f9164cb417.gif)

https://github.com/Microsoft/vscode/issues/28582 is tracking the update in VS Code.

**Comment by Tyriar** [comment]
Possibly related: https://github.com/nodejs/node/issues/7657

**Comment by Tyriar** [comment]
I made a simple example that demonstrates the issue, basically just the electron quick start repo with the following changes:

renderer.js:

```js
ipcRenderer = require('electron').ipcRenderer;

for (var i = 0; i < 100000; i++) {
    ipcRenderer.send('a');
}
```

Added to end of main.js:

```js
var count = 0;

electron.ipcMain.on('a', () => {
  count++;
  console.log('main received #' + count);
});
```

Plus pointing at Electron 1.7.4.

This reproduces on my machine I was seeing the issue in VS Code on. I tried on another Windows 10 machine and it worked fine though, investigating...

**Comment by kieferrm** [comment]
@groundwater this is the issue we talked about yesterday.

**Comment by Tyriar** [comment]
This appears to be specific to my Windows 10 desktop, not the update, as I can't reproduce on my Windows 10 laptop. The main differences with this machine is that it's on the Windows Insiders channel and it's a fast gaming machine.

**Comment by Tyriar** [comment]
While no longer a blocker for us, it's concerning that this is so easily reproducible and completely breaks all successive IPC calls from the renderer. It also occurs when using `sendSync`.

**Comment by jkleinsc** [comment]
@Tyriar just to verify, are you saying it is only reproducible on your machine that is 

> on the Windows Insiders channel and it's a fast gaming machine?

I'm also confused about how easily reproducible it is if you could only reproduce on one machine, or maybe I am misunderstanding what you are saying?

**Comment by Tyriar** [comment]
@jkleinsc yes, it's 100% reproducible on this one machine. It also appears to not be a regression in 1.7.x as it happens on 1.6.6 as well.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
