### ISSUE TITLE
mac app store build rejected

### ISSUE THREAD

**Issue by Ianidane** [electron/electron#10109]
* Electron version: 1.6.11
* Operating system: osx

### Expected behavior

pass mac store review

### Actual behavior

denied for accessing a location

### How to reproduce

My app keeps getting denied for the same reason. I have tried a few different things and asked for help a few different places but haven't figured this out yet. The reason im failing is this
```
Guideline 2.4.5(i) - Performance


Your application accesses the following location(s):

'~/Downloads/.##########.com.Company.AppName.8FRyAP'

The majority of developers encountering this issue are opening files in Read/Write mode instead of Read-Only mode, in which case it should be changed to Read-Only.

Other common reasons for this issue include:

- creating or writing files in the above location(s), which are not valid locations for files to be written as stated in documentation.

- writing to the above location(s) without using a valid app-id as a container for the written files.
```
(I replaced personal info)
Im not sure why my app is accessing that location at all. I have com.apple.security.files.user-selected.read-write and com.apple.security.files.user-selected.read-only in my entitlements. I tried reproducing the Sandbox violation by running it and checking the mac console but i dont ever see that violation show. Im kinda stuck here and not sure what to do. This is my first time going through the app review so forgive me if im being stupid. Any help or guidance would help me out a lot.

**Comment by Ianidane** [comment]
Figured out I just needed to add com.apple.security.files.downloads.read-write to my entitlements. Ill close this.

**Comment by zeke** [comment]
Thanks for following up @Ianidane. If you could submit a PR adding your findings to https://github.com/electron/electron/blob/master//docs/tutorial/mac-app-store-submission-guide.md, it would be most appreciated. :)

**Comment by ivankholod** [comment]
Thanks. I got reject like your.
