### ISSUE TITLE
npm ERR! 404 Not Found: @types/node@^7.0.18

### ISSUE THREAD

**Issue by sarlv** [electron/electron#10104]
I am not able to install electron on my machine.

When I run
```
npm i
```
I get
```
npm ERR! code E404
npm ERR! 404 Not Found: @types/node@^7.0.18
```
My node -v

> v6.11.0

My npm -v

> 5.3.0

**Comment by sarlv** [comment]
I have found solution here: https://stackoverflow.com/a/18689934/5693594
Just run this command to change `htts` on `http`

> npm set registry http://registry.npmjs.org/

**Comment by oneuptim** [comment]
Thank you @sarlv

**Comment by abhishekgupta1** [comment]
thanks @sarlv
