### ISSUE TITLE
Problem getting URL that triggered protocol handler when app is packaged

### ISSUE THREAD

**Issue by Raul6469** [electron/electron#10106]
* Electron version: v1.6.11
* Operating system: Windows 10

Here is a repo that illustrates what I'm meaning : https://github.com/Raul6469/electron-link-protocol

### Expected behavior

Whether the app is packaged or not, Electron should be able to retrieve the URL that triggered the protocol handler.
For example, when accessing `testlink://hello`, we should have `testlink://hello` in the `app.makeSingleInstance` event callback.

### Actual behavior

It works as expected when the app is launched from the command line with `npm start`, but not when the app is packaged. The variable supposed to contain the url is null instead.

**Not packaged app**
![image](https://user-images.githubusercontent.com/24607388/28543907-b70bc57a-70c1-11e7-8910-86ad3c06fdd1.png)

**Packaged app**
![image](https://user-images.githubusercontent.com/24607388/28543855-8e3d9b28-70c1-11e7-91bc-e557b1c34b1d.png)

### How to reproduce

Clone https://github.com/Raul6469/electron-link-protocol, and test by accessing `testlink://hello` with the app launched with the command line (`npm install && npm start`) and the packaged app with `electron-prebuilt`.
The variable supposed to contain the url is displayed in the window console.

**Comment by airbenich** [comment]
Any news on this?

**Comment by Raul6469** [comment]
I opened this issue nearly one year ago, and I don't know if it has been fixed in newer versions. Do you still face the same problem as I did @airbenich ?

**Comment by airbenich** [comment]
Thank you Raul for your fast reply. Yep I'm facing the same issue as you described still with the current electron version in relation to a "Packaged app". How can check this with an "Not packaged app"?

**Comment by Raul6469** [comment]
What I mean by "Not packaged app" is when you launch your app in "dev mode" by just running `npm start`, and it should work correctly. The issue happened only when I packaged my app.

**Comment by airbenich** [comment]
I've fixed my problem based on this approach:
https://github.com/oikonomopo/electron-deep-linking-mac-win

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
