### ISSUE TITLE
MacOS symbols are not supported by Electron symbol server

### ISSUE THREAD

**Issue by yanqi27** [electron/electron#10105]
Hi, amathew and myan from Backtrace.io. We have the following feature request.

* Electron version: 1.6.11
* Operating system: MacOS

### Expected behavior

User may download MacOS symbols just like Windows symbols.

### Actual behavior

Either the original debug file or the Breakpad symbol file is downloadable through the Electron symbol server.
### How to reproduce
The following command manually downloads symbol of module XPCService through Electron symbol server. `96A2DAAC53853755AEF485A22AC4FD940` is the debug identifier (a hash of the executable's code section). The minidump generated by Breakpad embeds the module name and its debug identifier in the file so that debugger can properly match the symbol.
```
wget https://electron-symbols.githubapp.com/XPCService/96A2DAAC53853755AEF485A22AC4FD940/XPCService
```
or
```
wget https://electron-symbols.githubapp.com/XPCService/96A2DAAC53853755AEF485A22AC4FD940/XPCService.sym
```

**Comment by abelmathew** [comment]
Looks like this is happening on Electron 1.7.6 as well. Any updates here?

**Comment by zcbenz** [comment]
I don't really know how symbol servers work on macOS, pull requests are welcomed. As reference, Windows symbols are uploaded in the `script/upload-windows-pdb.py` script.

**Comment by abelmathew** [comment]
@zcbenz Thanks for the info. Happy to volunteer for this work, unless someone else wants it. I'll take the ticket for now and report back.
