### ISSUE TITLE
Receive incorrect url after open electron app from browser on win7

### ISSUE THREAD

**Issue by FitsnerAS** [electron/electron#10102]
* Electron version: using electron 1.6.7
* Operating system: win 7

### Expected behavior

Receive url with hash and parameters in right order after opening the app with link from ie11 and FF   
example (app://my-app.com/#/phone?number=555555)
### Actual behavior

receive in app.on('open-url') function - url with swap parameters and hash  
example (app://my-app/?number=555555#/phone)
### How to reproduce

Open electron app with link only on win7 and FireFox, ie11 browsers.
Thank you very much...!

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by clusterberries** [comment]
@codebytere I faced with the same issue with Electron 6.1.7. Could you please reopen this bug?
