### ISSUE TITLE
Menu font is very small on big monitor (low-dpi)

### ISSUE THREAD

**Issue by akontsevich** [electron/electron#10101]
Issue mentioned [here](https://github.com/Microsoft/vscode/issues/31296) as VS Code built upon Electron. It is some font control rendering issue.

1. Installed KDE Plasma 5.10 with HiDPI support. All applications works fine with real 52 DPI on my 42" FullHD monitor. Font in VS Code menu is very small.
2. "window.zoomLevel" parameter has no effect on this.
3. Can fix this to set fake screen DPI to 72 or 96 however in all other applications fonts become VERY big.
4. Following command fixed the issue for me: `code --force-device-scale-factor=0.8`, however good to have VS Code (Electron) do this automatically or have correspondent settings.

![screenshot_20170724_051913](https://user-images.githubusercontent.com/3843657/28514705-b6e1f3fc-7063-11e7-82b4-3283060cb3c0.png)

**Comment by Deathangel908** [comment]
I'm having the same issue with KDE5, so it might be plasma specific. Curious that I came here from [VSCode](https://github.com/Microsoft/vscode/issues/31278) as well. However this applies to all electron apps running on KDE. I'm gonna check xfce this evening. 

As a temporary solution I think adding `--force-device-scale-factor` inside of `/usr/bin/electron`
```
var args = process.argv.slice(2);
args.push('--force-device-scale-factor=1.2')
var child = proc.spawn(electron, args, {stdio: 'inherit'})
```

**Comment by akontsevich** [comment]
In my case `--force-device-scale-factor=0.8` is good, :) so do not think this is a universal solution for all.

**Comment by jhasse** [comment]
Would this be fixed by #2927?

**Comment by akontsevich** [comment]
`--force-device-scale-factor` less than `1` does not work any more in VS Code 1.6 - fonts become huge!

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR.

**Comment by akontsevich** [comment]
Workaround is to set fake resolution like X11 default 96 DPI for Low-Res screens. For Hi-Res scale factor works I think.
