### ISSUE TITLE
Attach the devtools to a webview and the debugger api can not handle this.

### ISSUE THREAD

**Issue by wenshiqi0** [electron/electron#10108]
* Electron version:
1.6.11
* Operating system:
mac ox

### Expected behavior

I start a `Webview` to load a `Chrome-Devtools-Frontend` page which is attached to another `Webview`. And it seems Electron debugger API can not handle this situation. The `isAttached` will still return `false` and all the commands I send to chromium do nothing.

### Actual behavior

While I start a `Webview` to load devtools page which is attached to another `Webview`, the Electron debugger API can handle this. The `isAttached` return `true` and then command I send to chromium does that I want.

**Comment by foolishchow** [comment]
I meet the problem to , so did you figure it out?
