### ISSUE TITLE
BrowserView webContents cannot get will-download event

### ISSUE THREAD

**Issue by CharlieHess** [electron/electron#10115]
* Electron version: 1.7.5
* Operating system: macOS

### Steps to reproduce
* Create a `BrowserView` and point it at a page with some downloads.
* Try attaching a `will-download` event listener to any of the following:
  * The parent window's `webContents.session`
  * The `session.defaultSession`
  * The `webContents` parameter in the `app.web-contents-created` event

### Expected behavior

`will-download` should be emitted.

### Actual behavior

`will-download` is not emitted.

**Comment by liusy182** [comment]
I am not able to reproduce this with minimum app below in which I am able to see both logs printed:

```javascript
const {app, BrowserView, BrowserWindow} = require('electron');

let win;

app.on('ready', () => {
  win = new BrowserWindow()
  
  win.webContents.session.on('will-download', (event, item, webContents) => {
    console.log('[main] will download')
  })

  let view = new BrowserView()
  win.setBrowserView(view)
  view.webContents.loadURL('https://github.com/electron/electron/releases/download/v1.7.5/electron-api.json')

  view.webContents.session.on('will-download', (event, item, webContents) => {
    console.log('[view] will download')
  })
});

```

**Comment by CharlieHess** [comment]
'tis true, this bug was of my own making and `BrowserView` works just fine 👍

**Comment by zeke** [comment]
Thanks for following up, @CharlieHess
