### ISSUE TITLE
getAllDisplays does not return unique ids

### ISSUE THREAD

**Issue by merildev** [electron/electron#10112]
* Electron version: 1.4.16 (Atom), 1.6.11 (latest stable)
* Operating system: ArchLinux - Linux 4.11.9

I have 3 screens set up on my PC.

### Expected behavior

``` javascript
electron.screen.getAllDisplays()
```

Should return an array of 3 distinct screens.

### Actual behavior

``` javascript
electron.screen.getAllDisplays()
```

Returns an array of 3 screens but they all share the same `id`.

### How to reproduce

Having multiple monitor, Linux (inside VirtualBox) and call:

``` javascript
electron.screen.getAllDisplays()
```

**Comment by codebytere** [comment]
this looks like an issue with upstream, since all we do is call the `GetAllDisplays()` method implemented in Chromium. I'd recommend reporting this over on bugs.chromium.org
