### ISSUE TITLE
[webview] Twitter notifications are not activatable

### ISSUE THREAD

**Issue by magne4000** [electron/electron#10119]
* Electron version: 1.7.4
* Operating system: MacOS

### Expected behavior

When clicking on "Turn on" in Twitter preferences -> Web notifications, we should have the following behaviour
![image](https://user-images.githubusercontent.com/1098371/28613800-c2098740-71f3-11e7-8261-eb37777eaf61.png)

### Actual behavior

Clicking on "Turn on" does nothing
![image](https://user-images.githubusercontent.com/1098371/28613788-b6a6372c-71f3-11e7-977a-3b97bcfe8f0f.png)

### How to reproduce

- Have a `webview` loading https://twitter.com
- Login to twitter with any account
- Go to Settings and privacy / Web notifications
- Click on "Turn on"

**Comment by groundwater** [comment]
Confirmed that nothing happens when you click on "Turn On" notifications. No errors in the console. 

@jkleinsc I think you were saying that push notifications are not working on Electron right?

**Comment by jkleinsc** [comment]
@groundwater That is correct.  Push notifications are not currently supported in Electron.

**Comment by alexstrat** [comment]
Root-issue is #6697

**Comment by jkleinsc** [comment]
Closing this issue in favor of #6697
