### ISSUE TITLE
Kiosk Mode + Touch Events causes color changes

### ISSUE THREAD

**Issue by obermillerk** [electron/electron#10110]
* Electron version: 1.6.11
* Operating system: Windows 10, version 1703 (Creator Update)

note: installed through npm (latest version)

I'm working on an app that will be in kiosk mode, using a touch screen (Surface tablet).  Everything works relatively well (some responsiveness issues to touch events, but that's for another day) except that when we change into kiosk mode, touch events intermittently cause electron to render colors with reversed red and blue values.  I isolated this in a basic electron app, following your quick-start guide except that instead of setting a size of 800x600, enabling kiosk mode. Repository is linked below.

### Expected behavior

Touch events should not change the red background.

### Actual behavior

Touch events cause the red background to flicker blue on release.  Additionally, with the debug tools open colors in there will also change.

### How to reproduce
https://github.com/obermillerk/electron-kiosk-touch
```
$ git clone https://github.com/obermillerk/electron-kiosk-touch
$ cd electron-kiosk-touch
$ npm install
$ ./node_modules/.bin/electron .
```

When it's running, touch randomly in the red background. It seems to register better with single touches as opposed to quickly touching repetitively. It flickers for varying lengths, sometimes multiple flickers per touch, and I have encountered some runs where this doesn't happen, but it always comes back after waiting a few seconds or an app restart or two.  Mouse events do not trigger this from what I've seen.

As mentioned, we're using surface tablets, so we also use the pen stylus that they come with.  These events seem to register slightly different than finger touches in the os. The pens still replicate this behavior, but the touches seemingly have to be quite quick.

**Comment by obermillerk** [comment]
Update: This has now been tested against 1.7.5 from NPM and it is still present.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
