### ISSUE TITLE
Use Google-Cloud in Electron!

### ISSUE THREAD

**Issue by vincenzoraco** [electron/electron#10117]
* Electron version: 1.7.5
* Operating system: Mac OS Sierra 10.12.5

### Expected behavior

Use google-cloud package

### Actual behavior

`Error: dlopen(/Users/vincenzoraco/Documents/GitHub/project-test/node_modules/grpc/src/node/extension_binary/grpc_node.node, 1): Symbol not found: _GENERAL_NAME_free
    Referenced from: /Users/vincenzoraco/Documents/GitHub/project-test/node_modules/grpc/src/node/extension_binary/grpc_node.node
    Expected in: flat namespace
   in /Users/vincenzoraco/Documents/GitHub/project-test/node_modules/grpc/src/node/extension_binary/grpc_node.node
      at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
      at Object.Module._extensions..node (module.js:598:18)
      at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
      at Module.load (module.js:488:32)
      at tryModuleLoad (module.js:447:12)
      at Function.Module._load (module.js:439:3)
      at Module.require (module.js:498:17)
      at require (internal/module.js:20:19)
      at Object.<anonymous> (/Users/vincenzoraco/Documents/GitHub/project-test/node_modules/grpc/src/node/src/grpc_extension.js:45:15)
      at Object.<anonymous> (/Users/vincenzoraco/Documents/GitHub/project-test/node_modules/grpc/src/node/src/grpc_extension.js:49:3)`

### Solution

I am using [SimulatedGREG/vue-electron](https://github.com/SimulatedGREG/vue-electron) as boilerplate. What I found on different opened issues in different repositories was all confusing and it didn't help me to find a quick solution. Since we can't use firebase api storage in electron, we need to use google-cloud package to do so.

Unfortunately, I don't know why (I am not an expert) if I have dev-dependencies when I run `./node_modules/.bin/electron-rebuild -v 1.7.5` it throw a 404 error for every dev dependency about the `package.json`.

Anyway, I had to move my dev dependencies in the normal dependencies - otherwise you need to create the package.json for each package you have in dev.

First things first. You need to install electron-rebuild `yarn add electron-rebuild`. Then simply add google-cloud dependency. Then run this command `./node_modules/.bin/electron-rebuild -v 1.7.5`. It should say `Rebuild Complete`. Finally you can run (in my case) `yarn run dev` and you can use `var gcloud = require('google-cloud');` in your `index.js` file (where node.js/electron start the process)

 I know this is not an  issue report, but I hope it helps people that wants to use firebase/google cloud storage.

NOTE: If there is another way that can fix this issue, please let us know. I am not perfect, but I want to help still.

**Comment by MarshallOfSound** [comment]
`electron-rebuild` is the easiest way to [use native modules in electron](https://electron.atom.io/docs/tutorial/using-native-node-modules/)

Closing out as not an issue
