### ISSUE TITLE
Custom protocol doesn't work after reload

### ISSUE THREAD

**Issue by mrgrimmig** [electron/electron#10122]
* Electron version: 1.6.11
* Operating system: Windows 10

### Expected behavior

Hello,  
i need to display some dynamic loaded images in my app. Since the path of these images depends on a project folder (which is also dynamic) and the project should be reusable on different machines, i can't use absolute neither relative paths.  

So i decided to register a custom protocol which can handle these paths.  
For example to display an image called "test_image.png" which lies in "my_project/resources/" i would use `<img src="resources://test_image.png"/>`.

The protocol will be registered at the start of my app:
```js
const { remote } = require("electron");

remote.protocol.isProtocolHandled("resources", isHandled =>
{
	if(!isHandled)
	{
		remote.protocol.registerFileProtocol("resources", (request, callback) =>
		{
			console.log("url:", request.url);
			const filename = request.url.substr(12);
			// callback("C:\image.png");
			callback(IO.combinePaths(this.project.projectFolder, "resources", filename));
		}, 
		error =>
		{
			if(error)
			{
				console.log(error);
			}
			else
			{
				console.log("scheme registered");
			}
		});
	}
	else
	{
		console.log("scheme already registered");
	}
});
```

All images (with its relative paths) should be displayed now.

### Actual behavior

Well, when i first start my app, i can see the images, but after a reload (`remote.getCurrentWindow().reload();`), the protocol doesn't work anymore.
The function to register the protocol will be called (as i can see in the console), but electron never tries to use this protocol (can't see the console.log("url", ...) message).

All in all:
1. App start:
	- "scheme registered"
	- images are visible
	- images are listed in the application panel (dev tools)
2. App reload / refresh:
	- "scheme already registered" / error message when commenting out the `isProtocolHandled` stuff
	- images aren't visible
	- images aren't listed in the panel

**Comment by enlight** [comment]
Move the protocol registration into the main process, don't use `remote`. When you reload the window the renderer process is restarted, so the function instance you provided to handle the protocol disappears. I suggest reading https://electron.atom.io/docs/api/remote/#passing-callbacks-to-the-main-process
