### ISSUE TITLE
Mac OS Show Save Dialog

### ISSUE THREAD

**Issue by melalitesh** [electron/electron#10123]
* Electron version: 1.6.11
* Operating system: Mac OS Sierra

### Expected behavior

![28636412-a9a770d2-725b-11e7-8733-99582ff46dcf](https://user-images.githubusercontent.com/2289/28643841-0a9e978a-720c-11e7-9074-233a6fd690fb.png)

### Actual behavior

![28636531-0ba56b9a-725c-11e7-8ed7-f678b75c347d](https://user-images.githubusercontent.com/2289/28643847-0ef43ea2-720c-11e7-9e8f-7e643ccaa7ba.png)

**Comment by KagamiChan** [comment]
You should pass a `browserWindow` instance for `dialog.showSaveDialog`

> The `browserWindow` argument allows the dialog to attach itself to a parent window, making it modal.

**Comment by zeke** [comment]
@melalitesh I updated your comment with images instead of links to images, to make it easier to compare the two. Please let us know if @KagamiChan's comment is helpful.

**Comment by MarshallOfSound** [comment]
I believe @melalitesh is referring to the `format` dropdown in the first save box.  This is something known as an `Accessory View` and it's not something we can implement in a cross-platform or easy way.

**Comment by codebytere** [comment]
Given @MarshallOfSound's comment above, this doesn't appear to be something we can reasonably implement and so i'm going to go ahead and close this.
