### ISSUE TITLE
Pass --eval to Electron

### ISSUE THREAD

**Issue by aleclarson** [electron/electron#10129]
* Electron version: 1.6.11
* Operating system: MacOS Sierra 10.12.3

Trying to use the NodeJS `--eval` argument with Electron.

```sh
ELECTRON_RUN_AS_NODE=1
./node_modules/electron/dist/Electron.app/Contents/MacOS/Electron -e "console.log(process.versions.modules)"
```

I tried `node ./node_modules/electron/cli.js` and got the same error as the first attempt.

I tried `node ./node_modules/electron/index.js` and nothing happened.

### Expected behavior

Print `53` into stdout.

### Actual behavior

"Error launching app"
```sh
Unable to find Electron app at $PWD/console.log(process.versions.modules)

Cannot find module '$PWD/console.log(process.versions.modules)'
```

**Comment by zeke** [comment]
You're looking for `./node_modules/.bin/electron`:
```
❯ ELECTRON_RUN_AS_NODE=1 ./node_modules/.bin/electron -e "console.log(process.versions.modules)"
53
```

npm includes the `.node_modules/.bin` in its PATH, so you can just refer to the electron binary as `electron` when using npm scripts.

If you add this line to your shell dotfile, you can run the local `electron` in your shell without typing the `./node_modules/.bin` prefix.

```sh
export PATH="$PATH:./node_modules/.bin"
```

**Comment by aleclarson** [comment]
@zeke I'm actually trying to spawn Electron as a child process, then listen to stdout for `console.log(process.versions.modules)`. It looks like `.bin/electron` spawns its own child process. Are you sure that would work?

**Comment by zeke** [comment]
[electron-stream](http://ghub.io/electron-stream) might be what you're looking for.
