### ISSUE TITLE
electron addon rebuild error

### ISSUE THREAD

**Issue by ZhuZiQing1** [electron/electron#10135]
* Electron version: 1.4.13
* Operating system: windows

when i rebuild for electron call c++ ,i used

 ** "node-gyp rebuild –-target=1.4.13 –-arch=x64 --dist-url=https://atom.io/download/atom-shell"** ,

and there is a WARN:

**"install got an error,rolling back install"  ,"configure error !"**

I am very confuse. How can we solve this problem.

![help](https://user-images.githubusercontent.com/30492566/28661568-a89dc48c-72e9-11e7-9bc9-93c8e5d5bfcd.PNG)

**Comment by MarshallOfSound** [comment]
@ZhuZiQing1 Looks like you got an `ETIMEDOUT` exception which normally indicates network issues, you should try again a few times or try a different network.

If you are behind a proxy or VPN you may have to configure `node` to use that when downloading the headers.

It's the same error as explained in the [FAQ](https://github.com/electron/electron/blob/master/docs/faq.md#why-am-i-having-trouble-installing-electron).  Basically something is wrong with your network connection 👍

**Comment by ZhuZiQing1** [comment]
I tried a lot of ways to connect, but I have been reporting this error. Is there any way to go offline?

**Comment by MarshallOfSound** [comment]
You need to download those header files somehow

**Comment by ZhuZiQing1** [comment]
I tried this, but run this order will still be connected to the site
