### ISSUE TITLE
Chrome window icons disappear when using shell.openExternal

### ISSUE THREAD

**Issue by Thomas101** [electron/electron#10134]
* Electron version: 1.6.11, 1.7.5, 3, 4
* Operating system: Elementary OS Loki, Juno
* Chrome version: 60 - 71

### Expected behavior

When calling `electron.shell.openExternal("https://github.com")` chrome should open and then when maximising the chrome window, the control buttons (minimize, maximize, close) should remain in the toolbar in the same way as when you use chrome normally.

1. Open chrome
![screen shot 2017-07-27 at 09 00 32](https://user-images.githubusercontent.com/103586/28660239-2758e8aa-72aa-11e7-978e-6173afb4d0c6.png)

2. Maximise window - controls are still on right side
![screen shot 2017-07-27 at 09 00 38](https://user-images.githubusercontent.com/103586/28660320-615e6912-72aa-11e7-8a9d-01cf523f45fa.png)

### Actual behavior

When maximising they disappear.

1. Open chrome (as above)
2. Maximise window - controls are now missing
![screen shot 2017-07-27 at 09 00 11](https://user-images.githubusercontent.com/103586/28660340-74305aaa-72aa-11e7-9940-37156d4b018e.png)

### How to reproduce

Just call `electron.shell.openExternal("https://github.com")`. I know behind the scenes electron uses `xdg-open` so I tried `xdg-open "https://github.com"` and this doesn't exhibit the broken behaviour.

Also as a note, in Chrome if you enable `Use system title bar and borders` window controls are missing from the chrome tab bar  just like in the broken behaviour. I'm wondering if there are extra arguments passed along with the `xdg-open` call which is causing chrome to think it has to use these? I could be barking up the wrong tree though

**Comment by Thomas101** [comment]
Here's a user-contributed screencast showing the issue from Wavebox, but the same issue can be seen just by calling `openExternal` https://goo.gl/5vfp4N

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by Thomas101** [comment]
@codebytere this is still an issue with Electron 3 & 4. Also with Chrome 70 & 71 on Elementary OS Juno. I've updated the original issue to reflect this.

It looks like there's a workaround for this upstream in Chrome [here](https://bugs.chromium.org/p/chromium/issues/detail?id=718678) basically by adding `env XDG_CURRENT_DESKTOP=Unity` to the exec statement which was incorporated into Chrome 63+.

Could it be that xdg-open isn't passing this through?

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
