### ISSUE TITLE
TouchBarScrubber continuous property ignored

### ISSUE THREAD

**Issue by alopix** [electron/electron#10132]
* Electron version: 1.7.5
* Operating system: macOS High Sierra 10.13 Beta (17A315i)

### Expected behavior
`TouchBarScrubber`'s `select` event and handler should not be called when scrolling to find the right ScrubberItem when `continuous=false`. It appears the `continuous` property is ignored or not correctly handed through to ObjC.

### Actual behavior
No matter of TouchBarScrubber.continuous is true or false, the select event is sent out when moving the scrubber on the Touch Bar as if continuous was set to true native.

### How to reproduce
I provided a [simple test project](https://github.com/alopix/electron-touchbar-scrubber-continuous-bug) with continuous=false, which does not behave as a native implementation according to [Apple](https://developer.apple.com/documentation/appkit/nsscrubber#2793489) should.

  $ git clone git@github.com:alopix/electron-touchbar-scrubber-continuous-bug.git -b master
  $ npm install
  $ npm start || electron .

**Comment by MarshallOfSound** [comment]
PR up to fix, thanks for catching this 👍
