### ISSUE TITLE
Electron with certain exe name flashes/flickers on some machines

### ISSUE THREAD

**Issue by florin05** [electron/electron#10147]
* Electron version:1.6.11 (but happened with older ones, like 1.2.5
* Operating system: Windows 8.1

### Expected behavior

No Flashing

### Actual behavior

Flashing

### How to reproduce
On certain machines when running the generated electron exe (named say "abc.exe") the window flashes/flickers when the UI refreshes or the UI is interacted with.

When running the exe from the command line, these messages are observed repeatedly. The messages are not showing in the log file for the app.

```
[4684:0728/103243.989:ERROR:gles2_cmd_decoder.cc(16945)] [.DisplayCompositor-07391890]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM
: invalid mailbox name
[4684:0728/103243.990:ERROR:gles2_cmd_decoder.cc(9408)] [.DisplayCompositor-07391890]RENDER WARNING: texture bound to texture unit 0 is not renderable.
It maybe non-power-of-2 and have incompatible texture filtering.

```
Some more and puzzling details:

1. When renaming the exe to anything other than "abc.exe", say "abc1.exe" the flashing behavior and error logs go away
2. When calling the exe with the `--disable-gpu-driver-bug-workarounds` Chromium switch the behavior also goes away
3. When removing the laptop (Zbook I7) from the docking station ("HP Advanced docking station"),  behavior also goes away.
4. The issue is manifesting only one some of the machines even if they have the same docking station and laptop models

We went with workaround 1, but want to figure out if there is any explanation that makes sense.

**Comment by michalrousal** [comment]
Can this be Optimus (gpu switchning) related issue? Based on the details you provide, gpu selection is sometime based on executable name, also dedicated gpu is often not used when running on battery (out of dock). Point 4 is hard to explain, can it be that some machines have different gpu drivers (version)?

**Comment by florin05** [comment]
@michalrousal , you are on to something!

After a bit of research, I deducted "Optumus" is used int the "Manage 3D settings" of the NVIDIA card I have, and then looked at the list of programs they list (un-checked the "Show only programs found on this computer" since that list was very short) 

**If I use for my executable any of the names next to "Harris Gscribe" in this list, I get the issue !**

I tried a few other exe names from other vendors in that list and I don't have the issue.

From what I can tell, I don't have any "Harris Gscribe" software installed on my machine and could not find any of the exe names in the registry.

How can this be explained? 

![image](https://user-images.githubusercontent.com/11194908/28789580-e68ec284-75f3-11e7-8ec3-d3e81684c93d.png)

**Comment by mrousal** [comment]
@florin05 I don't know for sure unfortunately, it was just guess based on details you provided. For example, for us setting one laptop using Optimus to always use dedicated gpu broke WebGL rendering in electron. When it was left on auto or on integrated gpu it worked fine. Sometime simply updating gpu drivers solved the problem. We have other problem reports mostly involving systems with dedicated gpu. Seems like chromium used in electron has some problems with dedicated gpus in multigpu setup, but to properly analyze this would require more time and better understanding of chromium internals.
Also optimus doesn't use only that app list in settings to decide what app to run on dedicated gpu, it has some 'auto detection logic' as well. If you enable "Display GPU activity icon in the notification area" you should be able to see exactly what apps are using it.

**Comment by michalrousal** [comment]
@florin05  I don't know for sure unfortunately, it was just guess based on details you provided. For example, for us setting one laptop using Optimus to always use dedicated gpu broke WebGL rendering in electron. When it was left on auto or on integrated gpu it worked fine. Sometime simply updating gpu drivers solved the problem. We have other problem reports mostly involving systems with dedicated gpu. Seems like chromium used in electron has some problems with dedicated gpus in multigpu setup, but to properly analyze this would require more time and better understanding of chromium internals.

Also optimus doesn't use only that app list in settings to decide what app to run on dedicated gpu, it has some 'auto detection logic' as well. If you enable "Display GPU activity icon in the notification area" in the nvidia control panel (should be under Desktop menu) you should be able to see exactly what apps are using it.

**Comment by felixrieseberg** [comment]
I believe there's little we can do from the Electron side - this seems like an issue with the driver toolset. We could attempt to circumvent detection, but I think interfering with the driver tools will likely lead to more pain down the road.
