### ISSUE TITLE
When exiting fullscreen mode on Mac with a hidden titlebar on third monitor, the window is placed in invalid position

### ISSUE THREAD

**Issue by andymartinwork** [electron/electron#10145]
* Electron version: 1.6.11
* Operating system: Mac

### Expected behavior

Exiting fullscreen should place the window back into its previous position.

### Actual behavior

Window is placed more right and top than it should be, in a position where the titlebar is unreachable. Exiting and restarting the app is the only way to recover.

### How to reproduce

- Set titlebar to hidden (System Preferences -> General -> Automatically hide and show the menu bar)
- Move the app window to a second (or third) monitor
- Press the Green fullscreen button in the window to fullscreen it
- Press the Green fullscreen button to exit fullscreen
- Notice the strange placing of the window.

**Comment by andymartinwork** [comment]
After a bit of experimentation, this might only happen on the third monitor. It seems like the screen dimensions it's reading are from a different monitor than the one it's writing to.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
