### ISSUE TITLE
DOMException: Failed to get a ServiceWorkerRegistration: The Service Worker system has shutdown.

### ISSUE THREAD

**Issue by StormRyders** [electron/electron#10146]
On Electron Console I am getting this error whenever I try to register Service worker.
/app Folder
===================
index.html
------------
```html
<html>
<head>
    <title></title>
    <link href="notifications.css" type="text/css" rel="stylesheet"/>
    <script>
        function show() {		
		if ('serviceWorker' in navigator) {
		  navigator.serviceWorker.register('/sw.js', { scope: '/app/' })
		  .then(function(registration) {
			console.log('Registration successful, scope is:', registration.scope);
		  })
		  .catch(function(error) {
			console.log('Service worker registration failed, error:', error);
		  });
		}
		Notification.requestPermission(
			function(status) {	
			console.log('Notificaiotn Permission status: ', status);
			navigator.serviceWorker.getRegistration()
			.then(function(reg) {
			var options = {body:"Body", actions: [
				   {action: 'like', title: 'Like'},
				   {action: 'reply', title: 'Reply'},
				   {action: 'Whoaa', title: 'whoaaa'}
				   ]};
				reg.showNotification('Hello World', options);
			})
			}
		);           
        }
    </script>
</head>
<body>   
    <button onclick="show()">Show notification</button>
</body>
</html>
```
sw.js
-----------------------
```js
self.addEventListener('install', function(event) {
    console.log('Worker installed successfully', event);
});
self.addEventListener('activate', function(event) {
    console.log('Worker activated successfully', event);
});
```

main.js
---------------------
```js
const electron = require('electron')
// Module to control application life.
const app = electron.app
// Module to create native browser window.
const BrowserWindow = electron.BrowserWindow

const path = require('path')
const url = require('url')

const shell = require('electron').shell

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.

let mainWindow

function createWindow () {
  // Create the browser window.
  mainWindow = new BrowserWindow({width: 1000, height: 500, resizable: false})
   mainWindow.webContents.openDevTools()
  // and load the index.html of the app.
  mainWindow.loadURL(url.format({
    pathname: path.join(__dirname, 'index.html'),
    protocol: 'file:',
    slashes: true
  }))

  // Open the DevTools.
  // mainWindow.webContents.openDevTools()

  // Emitted when the window is closed.
  mainWindow.on('closed', function () {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null
  })
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow)
```
-----------------------------------------------------------------------------

Any guidance is appreciated.
* Electron version: v1.6.7
* Operating system: Windows 10

**Comment by jkleinsc** [comment]
@StormRyders the issue is that /sw.js isn't really located at /sw.js because of how Electron organizes the files.  Here is what you need to do in index.html

```js
function show() {		
  const path = require('path');
  const url = require('url');      
  let swScope = path.join(__dirname, '/');
  let swPath = url.format({
    pathname: path.join(__dirname, 'sw.js'),
    protocol: 'file:',
    slashes: true
  });
  if ('serviceWorker' in navigator) {
    navigator.serviceWorker.register(`${swPath}`, { scope: `${swScope}` })
    .then(function(registration) {
      console.log('Registration successful, scope is:', registration.scope);
    })
    .catch(function(error) {
      console.log('Service worker registration failed, error:', error);
    });
  }        
}
```

Also, I would recommend using Electron 1.7.x because there were issues with Service Workers in 1.6.x

**Comment by StormRyders** [comment]
Hi John @jkleinsc 

Thanks for the response and it worked for me. I got this working partially now. 

I am now trying to enable Push Notification there and currently getting:
"DOMException: Registration failed - push service not available" whereas the same worked on browser. I did some research and got to know that Electron will not support PUSH.

If you can guide me on any alternate approach.

Thanks

**Comment by jkleinsc** [comment]
@StormRyders if you are looking for native notifications, you can use the [Notifications API](https://electron.atom.io/docs/tutorial/notifications/).  If you simply want to display notifications this might be enough.  If you are looking for something that triggers a notification from a server side event, then you might need to use websockets or some other transport tied into the notifications API.

**Comment by StormRyders** [comment]
@jkleinsc 
Thanks for your guidance and definitely I will start with websockets. Just to ensure that you understand my application and its scenario, let me brief you a bit on that:
1. We have web application that will receive "ACTION-able" Notification from server 👍  
options = {body:"Body", icon: "alert.ico", actions: [
				   {action: 'like', title: 'Like'},
				   {action: 'reply', title: 'Reply'}]};

2. We have onboarded our web-app on Electron and in electron app->index.html we are loading our web-application url as:
		window.location.href = "http://127.0.0.1:8887";	
		$(document).ready(function() {
			setTimeout(function(){
				$("#mainFrame").show();
			},1000);
		});

Thats what I was trying to quickly achieve with Electron as I wanted to show actionable Notification in Windows-Action-Center.

Note: Unable to use ' electron-windows-notifications' module as corporate proxy is blocking this. Thats why I was looking for an alternate to achieve this.

Sorry to bother you with long emails, but just wanted a guidance from you. If you can please acknowledge on this, will be really great.

Thanks

Adi

**Comment by sofianguy** [comment]
Looks like @jkleinsc solved your issue. 
If you're looking for further help, check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
