### ISSUE TITLE
App crashes when click links repeatedly before next page loads.

### ISSUE THREAD

**Issue by alparslanahmed** [electron/electron#10144]
* Electron version: 1.4.15
* Operating system: Windows 7 (64 bit)

My app loads pages from remote. When i click different links same time page must navigate to the last link which i clicked. This is a standart browser behavior.

When more than one link is pressed at the same time before the next page loads, electron crashes. Here is the ss of the error output:
```

Y:\Desktop\Dsd>electron .

[1232:0728/120925:FATAL:navigation_controller_impl.cc(2000)] Check failed: !in_navigate_to_pending_entry_ || delegate_->IsBeingDestroyed().
Backtrace:
        (No symbol) [0x000000013FDDA5C1]
        (No symbol) [0x000000013FDD36EC]
        icu_56::BreakIterator::isBufferClone [0x00000001400AD560+1570960]
        icu_56::BreakIterator::isBufferClone [0x00000001400AE794+1575620]
        icu_56::BreakIterator::isBufferClone [0x00000001400AEED4+1577476]
        (No symbol) [0x000000013FC247A9]
        (No symbol) [0x000000013FC21B92]
        (No symbol) [0x000000013FC20EBE]
        v8::experimental::FastAccessorBuilder::SetLabel [0x000007FEE78DB191+1418
929]
        uv_udp_set_ttl [0x000007FEE76E5508+2151772]
        uv_udp_set_ttl [0x000007FEE76EFE6F+2195139]
        uv_udp_set_ttl [0x000007FEE76E355B+2143663]
        (No symbol) [0x00000098A6D0614B]


```

**Comment by sofianguy** [comment]
Thanks for contributing!

We are no longer releasing bug fixes for versions of Electron older than 1.5. We prefer to only keep issues that are on our immediate radar.

If you are still having the same issue in an up-to-date version, feel free to reach out and we'll reopen.
