### ISSUE TITLE
Show window as desktop on Windows

### ISSUE THREAD

**Issue by shundroid** [electron/electron#10149]
I found a way to show window as desktop on Mac.
https://github.com/electron/electron/issues/2899

But I want to do the same thing on Windows.

I worked hard. Finally, I could do the same thing on Windows.

https://github.com/shundroid/setup-wallpaper
https://github.com/shundroid/wallpaper

By using node-gyp, Win32 API, I could.

But, I want to do it as easy as Mac.
Also, I can't use this way when I use electron-packager.

How do I solve it?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

If you can do it in native code then using `electron-packager` should not affect it working in any way.  Be sure to rebuild the native module correctly for your version of Electron and target architecture.

Be sure to read up on [using native module in Electron](https://electron.atom.io/docs/tutorial/using-native-node-modules/)

**Comment by gpsbird** [comment]
> GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
> 
> If you can do it in native code then using `electron-packager` should not affect it working in any way. Be sure to rebuild the native module correctly for your version of Electron and target architecture.
> 
> Be sure to read up on [using native module in Electron](https://electron.atom.io/docs/tutorial/using-native-node-modules/)

i hope BrowserWindow will support desktop type on windows

**Comment by TotalChris** [comment]
@MarshallOfSound just because a native module can achieve the same functionality as something natively implemented for Mac and Linux doesn't mean that it shouldn't be implemented natively in Windows. Wondering why this was closed.

**Comment by wyxos** [comment]
Is this still closed? Is there an explanation around to why it's not supported on Windows i.e. complex to implement/support? I was considering if learning C++ would help achieve that.
