### ISSUE TITLE
Cannot play large mp4 file (about 2GB~) 

### ISSUE THREAD

**Issue by yk-nakamura** [electron/electron#10154]
* Electron version: v1.7.x
* Operating system: Mac OS X 10.12.5 / Windows 7

### Expected behavior

Can play large mp4

### Actual behavior

Cannot play (load?) large mp4

### How to reproduce

1.  Create minimal application according to the procedure described in https://electron.atom.io/docs/tutorial/quick-start/
2. Execute the minimal application and drag-and-drop large video file (about 2GB~) to the opened window.

About 2GB or larger video file cannot be played in electron v1.7.X, but can be played in v1.6.X.
Is this correct behavior?

In my application, a MediaError (MEDIA_ERR_SRC_NOT_SUPPORTED) occurred if I specified a large mp4 file in the src property of html video tag.

**Comment by MarshallOfSound** [comment]
Please fill in the provided issue template, without steps to reproduce no one will be able to help you with this

**Comment by yk-nakamura** [comment]
I submitted it as incomplete, sorry. But now all items are filled in.

**Comment by felixrieseberg** [comment]
Do you have a video file that you failed to play? `mp4` can mean all kinds of different things and we should nail the exact code issue down.

Chances are pretty high that this is actually a Chrome error. Does it work for you in Chrome?

**Comment by yk-nakamura** [comment]
The video which is failed to play is for my private. So, I'll prepare another one.

In latest Chrome (59.0.3071.115), the large mp4 file can by played,
but I found a similar problem about Chrome on https://stackoverflow.com/questions/44060268/chrome-no-longer-plays-large-local-video-files.

**Comment by yk-nakamura** [comment]
I think it was a bug in Chrome 58.0.3029.110, because large videos can be played in electron v1.8.0 beta.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
