### ISSUE TITLE
App processes don't close on exit 

### ISSUE THREAD

**Issue by riteshkukreja** [electron/electron#10156]
- Electron version: 1.6.11
- Operating System: Window 10

My application is spawning 3 processes on startup. I have only one window. Every time I show my window, one of the processes move to running application group on Task Manager. The problem is that on closing, only one of the processes closes while the other two remain running. This prevents me from restarting the application as I have chosen not to open multiple instance of the application.

Note: This doesn't happen in development. All 3 processes closed properly during development.

Also I think the `GlobalShortcut` is also not getting de-registered properly.

**Index.js**

```
const { app, BrowserWindow, globalShortcut } = require("electron");
const path = require("path");
const url = require("url");

let win = null;

var shouldQuit = app.makeSingleInstance(function(commandLine, workingDirectory) {
  // Someone tried to run a second instance, we should focus our window.
  if (win) {
    win.show();
  }
});

if (shouldQuit) {
  app.quit();
  return;
}

app.on("ready", () => {

    win = new BrowserWindow({
        width: 1000,
        height: 600,
        transparent: true,
        frame: false
    });

    win.on("close", () => {
        win = null;
    });

    win.loadURL(
        url.format({
            pathname: path.join(__dirname, "app", "index.html"),
            protocol: "file",
            slashes: true
        })
    );

    win.once('ready-to-show', () => {
        win.show()
    });

    win.on("blur", () => {
        win.hide();
    });

    win.on('window-all-closed', () => {
        // added this line because on exiting, the shortcut could still be called and returning error
        globalShortcut.unregisterAll();
        if (process.platform !== 'darwin') {
            app.quit()
        }
    });

    const ret = globalShortcut.register('CommandOrControl+L', () => {
        if(win == null) {
            globalShortcut.unregisterAll();
            return;
        }
        win.show();
    });

    if (!ret) {
        console.log('registration failed')
    }

    app.on('will-quit', () => {
        // Unregister all shortcuts.
        globalShortcut.unregisterAll();
    });

    app.on('before-quit', () => {
        win.removeAllListeners('close');
        globalShortcut.unregisterAll();
        win.close();
    });

});


```

I have added these lines in my application window for exiting the application.

**index.html**
```
const remote = require('electron').remote;
var win = remote.getCurrentWindow();

if(textarea.val().toLowerCase() == "exit")
           win.close();
```

**Comment by MarshallOfSound** [comment]
@riteshkukreja Sounds like your packaged app is throwing an error somewhere in the quitting flow and isn't actually closing.  You should run the packaged app from Command Prompt and see what the errors are.

**Comment by riteshkukreja** [comment]
@MarshallOfSound I tried that. No errors but the cmd process was still running. I closed the application but the other two processes kept running. However on pressing Control+C in CMD, all processes stopped.

**Comment by MarshallOfSound** [comment]
@riteshkukreja Add some logs in the `window-all-closed` and `will-quit` events and such, try see where the logic stops working 👍

**Comment by riteshkukreja** [comment]
@MarshallOfSound I used `electron-log` to add logs in each method and event.  `win.on('window-all-closed')` was never called.
I just started the app and closed it immediately. These are the logs on development and production phase.
**Development**
[14:34:47:0438] [info] checking for registration: Global Shortcut Status: true
[14:34:50:0150] [info] Sending quit message to window
[14:34:50:0150] [info] Closing window: Global Shortcut Status: true
[14:34:50:0190] [info] before-quit: Global Shortcut Status: false
[14:34:50:0221] [info] will-quit: Global Shortcut Status: false

**Production**
[14:35:35:0621] [info] checking for registration: Global Shortcut Status: true
[14:35:39:0423] [info] Sending quit message to window
[14:35:39:0427] [info] Closing window: Global Shortcut Status: true

It is not generating to `before-quit` and `will-quit` events.

Here is the latest code
```
const { app, BrowserWindow, globalShortcut } = require("electron");
const path = require("path");
const url = require("url");
var log = require('electron-log');

let win = null;

var shouldQuit = app.makeSingleInstance(function(commandLine, workingDirectory) {
  // Someone tried to run a second instance, we should focus our window.
        log.info("Checking for running version of app: Global Shortcut Status: " + globalShortcut.isRegistered('CommandOrControl+L'));
  if (win) {
    win.show();
  }
});

if (shouldQuit) {
    log.info("Quiting second instance: Global Shortcut Status: " + globalShortcut.isRegistered('CommandOrControl+L'));
  app.quit();
  return;
}

app.on("ready", () => {

    win = new BrowserWindow({
        width: 1000,
        height: 600,
        transparent: true,
        frame: false
    });

    win.on("close", () => {
        log.info("Closing window: Global Shortcut Status: " + globalShortcut.isRegistered('CommandOrControl+L'));
        win = null;
    });

    win.loadURL(
        url.format({
            pathname: path.join(__dirname, "app", "index.html"),
            protocol: "file",
            slashes: true
        })
    );

    win.on('ready-to-show', () => {
        log.info("ready-to-show: Global Shortcut Status: " + globalShortcut.isRegistered('CommandOrControl+L'));
        win.show()
    });

    win.on("blur", () => {
        log.info("blur: Global Shortcut Status: " + globalShortcut.isRegistered('CommandOrControl+L'));
        win.hide();
    });

    win.on('window-all-closed', () => {
        log.info("window-all-closed: Global Shortcut Status: " + globalShortcut.isRegistered('CommandOrControl+L'));
        globalShortcut.unregisterAll();
        if (process.platform !== 'darwin') {
            log.info("window-all-closed, quiting app: Global Shortcut Status: " + globalShortcut.isRegistered('CommandOrControl+L'));
            app.quit()
        }
    });

    const ret = globalShortcut.register('CommandOrControl+L', () => {
        log.info("registering shortcut: " + globalShortcut.isRegistered('CommandOrControl+L'));
        if(win == null) {
            globalShortcut.unregisterAll();
            return;
        }
        win.show();
    });

    log.info("checking for registration: Global Shortcut Status: " + globalShortcut.isRegistered('CommandOrControl+L'));
    if (!ret) {
        console.log('registration failed');
        log.info("registration failed");
    }

    app.on('will-quit', () => {
        // Unregister all shortcuts.
        globalShortcut.unregisterAll();
        log.info("will-quit: Global Shortcut Status: " + globalShortcut.isRegistered('CommandOrControl+L'));
    });

    app.on('before-quit', () => {
        
        globalShortcut.unregisterAll();

        if(win) {
            win.removeAllListeners('close');
            win.close();  
        }
        log.info("before-quit: Global Shortcut Status: " + globalShortcut.isRegistered('CommandOrControl+L'));
        
    });

});


```

**Comment by riteshkukreja** [comment]
@MarshallOfSound I haven't found the problem yet. Could you help me?

**Comment by codebytere** [comment]
@riteshkukreja Can you bind to events on the original `app` instead of the window?

**Comment by riteshkukreja** [comment]
@codebytere Hi, Thanks for that. 
I should have been using logic. Attaching "window-all-closed" event with a single window!! Anyway now I all processes are closing and here is the log:

[22:44:51:0783] [info] checking for registration: Global Shortcut Status: true
[22:46:11:0790] [info] Sending quit message to window
[22:46:11:0796] [info] Closing window: Global Shortcut Status: true
[22:46:11:0834] [info] window-all-closed: Global Shortcut Status: true
[22:46:11:0835] [info] window-all-closed, quiting app: Global Shortcut Status: false
[22:46:11:0836] [info] before-quit: Global Shortcut Status: false
[22:46:11:0847] [info] will-quit: Global Shortcut Status: false

Although one little problem is that the console stops after these logs instead of exiting.

**Comment by codebytere** [comment]
if you've solved the primary issue, i'm going to go ahead and close this one!

**Comment by Ritesh-04** [comment]
i am facing same issue, unable to close background electron window from main window close.
using electron version 6.0.1. 

const { app, BrowserWindow, ipcMain, shell } = require("electron");
const fs = require("fs");
const node = require("./node.js");
let mainWindow;
let backgroundWindow;

const createWindow = () => {
  mainWindow = new BrowserWindow({
    width: 1020,
    height: 600,
    icon: __dirname + "/favicon.ico",
    webPreferences: {
      nodeIntegration: true
    }
  });

  mainWindow.loadURL(
    isDev
      ? "http://localhost:3000/"
      : `file://${path.join(__dirname, "../build/index.html")}`
  );
  mainWindow.on("closed", () => (mainWindow = null));

  backgroundWindow = new BrowserWindow({
    webPreferences: {
      nodeIntegration: true
    }
  });
  backgroundWindow.loadURL(
    `file://${path.join(__dirname, "/Print/printerWindow.html")}`
  );
  backgroundWindow.on("closed", () => {
    backgroundWindow = undefined;
  });
};


app.on("ready", createWindow);

app.on("window-all-closed", e => {
  e.preventDefault();
  app.quit();
});

app.on("after-create-window", e => {
  if (mainWindow === null) {
      e.preventDefault();
      createWindow();
  }
});

**Comment by danyalejandro** [comment]
In my case, the process wasn't closing after the bootstrapping process failed and fatal errors closed the app, leaving the process running. In addition to what others posted here, I wrapped my app.create routine in a try-catch and called `app.quit()` on exception and the problem stopped.

**Comment by dannyokec** [comment]
Anyone with similar issues. my okecbot electron App is glitchy on windows but stable on mac.
On windows, when the app is turned on some times it goes all white, also i noticed when the app is closed it deosnt close completely instead when i check the windows task manager i see other running called node runtime still running as a background process and this processes hinders my app from even working. I resorted to revealing my nodejs source codes just so users could run the project using installed nodejs instead of the electron bundled version,  which is bad as anyone could modify my source codes and remake another version of my app claiming they were the initial idea developer. This is a trauma for me at the moment. My electron main.js is below:

const path = require('path');
const { app, BrowserWindow } = require('electron');
const { exec } = require('child_process');
const checkUpdate = require("./checkUpdate");
let win;



async function createWindow() {
  exec('node server.js')
  win = new BrowserWindow({
    title: "okecbot",
    width: 1024,
    height: 768,
    icon: __dirname + '/website/images/okecbot.png',
    webPreferences: {
      nodeIntegration: true,
      zoomFactor: 0.8
    }
  });

  /*
    The okecbot project will be constantly updated. The logic below will prompt a user to download latest
    version should theres be outdated
  */

  let versionInfo = new checkUpdate;
  let currentOkecbotVersion = await versionInfo.checkNow();

  if (currentOkecbotVersion == "active") {
    // Load your dashboard
    win.loadURL("http://localhost:3000/onboard/page1.html");
  }

  else if(currentOkecbotVersion == "outdated"){
    // prompt user to download our latest version since this one is out of date
    win.loadURL("https://okecbot.com/download/newVersion.php");
  }

  else{
    // prompt user to download our latest version since this one is out of date
    win.loadURL("http://localhost:3000/onboard/remoteNetwork-issues.html");
  }

  // Optionally open DevTools.
  //win.webContents.openDevTools()
}

app.whenReady().then(createWindow);

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

**Comment by dannyokec** [comment]
> Anyone with similar issues. my okecbot electron App is glitchy on windows but stable on mac. On windows, when the app is turned on some times it goes all white, also i noticed when the app is closed it deosnt close completely instead when i check the windows task manager i see other running called node runtime still running as a background process and this processes hinders my app from even working. I resorted to revealing my nodejs source codes just so users could run the project using installed nodejs instead of the electron bundled version, which is bad as anyone could modify my source codes and remake another version of my app claiming they were the initial idea developer. This is a trauma for me at the moment. My electron main.js is below:
> 
> const path = require('path'); const { app, BrowserWindow } = require('electron'); const { exec } = require('child_process'); const checkUpdate = require("./checkUpdate"); let win;
> 
> async function createWindow() { exec('node server.js') win = new BrowserWindow({ title: "okecbot", width: 1024, height: 768, icon: __dirname + '/website/images/okecbot.png', webPreferences: { nodeIntegration: true, zoomFactor: 0.8 } });
> 
> /* The okecbot project will be constantly updated. The logic below will prompt a user to download latest version should theres be outdated */
> 
> let versionInfo = new checkUpdate; let currentOkecbotVersion = await versionInfo.checkNow();
> 
> if (currentOkecbotVersion == "active") { // Load your dashboard win.loadURL("http://localhost:3000/onboard/page1.html"); }
> 
> else if(currentOkecbotVersion == "outdated"){ // prompt user to download our latest version since this one is out of date win.loadURL("https://okecbot.com/download/newVersion.php"); }
> 
> else{ // prompt user to check internet since we couldnt verify if there current version is the latest win.loadURL("http://localhost:3000/onboard/remoteNetwork-issues.html"); }
> 
> // Optionally open DevTools. //win.webContents.openDevTools() }
> 
> app.whenReady().then(createWindow);
> 
> app.on('window-all-closed', () => { if (process.platform !== 'darwin') app.quit(); });
> 
> app.on('activate', () => { if (BrowserWindow.getAllWindows().length === 0) { createWindow(); } });

This was me back then but the next line shows how i fixed and make okecbot work perfectly and stably on windows, automating lots of web automation task and yet been stable enough to retain the bot states and not crash or lag. All made on electron. check out my youtube channel for a free master class on creating the most stable electron apps on windows
