### ISSUE TITLE
Running Electron with TypeScript seems to use ES6 modules instead of CommonJS modules

### ISSUE THREAD

**Issue by wolfie** [electron/electron#10151]
* Electron version: 1.6.11
* Operating system: Windows 10, 64-bit

Not sure if these matter, but I have these in my global environment:
* Node version: 7.10.1
* Typescript version: 2.4.1

### Expected behavior

Application would not throw an exception at startup

### Actual behavior

```text
App threw an error during load
C:\nih\ts-electron\main.ts:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { import { app } from 'electron';
                                                                                                                                                           ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at loadApplicationPackage (C:\Users\Henrik\AppData\Roaming\npm\node_modules\electron\dist\resources\default_app.asar\main.js:283:12)
    at Object.<anonymous> (C:\Users\Henrik\AppData\Roaming\npm\node_modules\electron\dist\resources\default_app.asar\main.js:325:5)
    at Object.<anonymous> (C:\Users\Henrik\AppData\Roaming\npm\node_modules\electron\dist\resources\default_app.asar\main.js:361:3)
    at Module._compile (module.js:571:32)
```

### How to reproduce

**1:** Create `package.json` with the contents:

```json
{
    "name": "ts-electron",
    "main": "main.ts",
    "devDependencies": {
        "electron": "^1.6.11"
    }
}
```

**2:** Run the command `yarn install`

**3:** Create `main.ts` with the contents:

```typescript
import { app } from 'electron';
```

**4:** Run the command `electron --version` to verify that you get `v1.6.11` as an answer.

**5:** Run the command `electron .` in the project root.

**Comment by MarshallOfSound** [comment]
Electron can not run typescript, you need to either run your code through a transpiler (`tsc`) or use a project like `electron-forge` which lets you use `typescript` natively.

```bash
electron-forge init --template=react-typescript new-project
cd new-project
npm start
```

**Comment by wolfie** [comment]
I'm confused. What does the [Announcing TypeScript support in Electron](https://electron.atom.io/blog/2017/06/01/typescript) mean, then?

**Comment by MarshallOfSound** [comment]
That blog post is announcing first party definition support.  See the first line of that blog post

> The electron npm package now includes a TypeScript definition file that provides detailed annotations of the entire Electron API

**Comment by erwingo** [comment]
I also thought electron started supporting TS and not only type definitions considering that in that "announcing TS" blog a `main.ts` file is used to showcase TS. Anyway, Since I only needed to transpile `main.ts` I ended up doing:

```js
"scripts": {
    "start": "tsc main.ts && electron ."
  }
```

**Comment by danawoodman** [comment]
I too was very confused. This video clearly makes it seem that Typescript is supported out of the box, like @erwingo mentions. Is there any plans to support Typescript as a first-class citizen in Electron at any point?

**Comment by CodeSwimBikeRun** [comment]
Has typescript been added to electron yet?

**Comment by tim-hub** [comment]
in fact, now you can just do `electron index.ts`
