### ISSUE TITLE
Using Electron With Browserify

### ISSUE THREAD

**Issue by chgibb** [electron/electron#10158]
Same problem as described in #8200 and can be seen across the internet in various other forums. Seems to be particularly popular in stackoverflow.

After banging my head  against this issue for a few hours, the cause seems to be that browserify is bundling  the ```index.js``` in ```node_modules```. The fix is to simply add ```--exclude electron``` (if running via CLI) to browserify.

If there is sufficient interest in amending the docs to include a section on working with module bundlers, I will open a PR.

**Comment by MarshallOfSound** [comment]
Closing as not an issue, if you think you can improve the docs in some way PR's are always welcome.
