### ISSUE TITLE
{role: 'about'} from main menu working only on macos, but not on windows or linux

### ISSUE THREAD

**Issue by vasyl-shumskyi** [electron/electron#10153]
Hi guys, 

`{role: 'about'}` from main menu working only on macos, but not on windows or linux. Is it expected behaviour?

Thanks!

**Comment by cnBruceHong** [comment]
please see the document :
https://electron.atom.io/docs/api/menu-item/
it says:
The following additional roles are available on macOS:
about - Map to the orderFrontStandardAboutPanel action
hide - Map to the hide action
hideothers - Map to the hideOtherApplications action
unhide - Map to the unhideAllApplications action
startspeaking - Map to the startSpeaking action
stopspeaking - Map to the stopSpeaking action
front - Map to the arrangeInFront action
zoom - Map to the performZoom action
window - The submenu is a “Window” menu
help - The submenu is a “Help” menu
services - The submenu is a “Services” menu

**Comment by vasyl-shumskyi** [comment]
I see.. So if its not natively possible, what is the best way to implement on Windows/Linux?

**Comment by MarshallOfSound** [comment]
@vasyl-shumskyi You can implement your own custom about window using HTML / CSS in a BrowserWindow.

**Comment by vasyl-shumskyi** [comment]
Thanks @MarshallOfSound Already did.
