### ISSUE TITLE
Electron application icon in KDE env

### ISSUE THREAD

**Issue by akontsevich** [electron/electron#10163]
* Electron version: not clear which one is used in latest riot-web: 0.11.4
* Operating system: Linux Ubuntu 16.04 (KDE Neon Packages KDE Plasma 5.10.4)

### Expected behavior
[They said](https://bugs.kde.org/show_bug.cgi?id=382728#c7) application is using the deprecated system tray icon specification. The app should be ported to [StatusNotifierItem](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/) under Linux.

### Actual behavior
Riot icon is violet blank square in KDE systray. Some screenshots to explain:
https://bugsfiles.kde.org/attachment.cgi?id=106945 - Riot icon in systray
https://bugsfiles.kde.org/attachment.cgi?id=106944 - Riot icon in task manager

### How to reproduce
Run Riot in latest KDE Plasma DE.

**Comment by MTRNord** [comment]
If you use the provided download or deb package from riot the electron Version is propably 1.6.8

**Comment by MTRNord** [comment]
PS: I got the same issue with Arch Linux (Antergos installation) and KDE

**Comment by dos1** [comment]
I've submited a patchset to Chromium that fixes this issue: https://chromium-review.googlesource.com/c/chromium/src/+/1173235

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by akontsevich** [comment]
@codebytere  Why You have closed this?! Issue exists in Electron 2.x and think in 3.x too.

**Comment by MarshallOfSound** [comment]
@akontsevich This issue was tagged as `1.6.x` and the original report didn't actually include an Electron version number at all (1.6 was pulled from a follow up comment).

Reading through this discussion the issue has been fixed in Chromium and Electron will inherit the fix that @dos1 submitted once we upgrade past that patch.

**Comment by akontsevich** [comment]
Whether it will fix tray icon left-click mouse issue as well?

**Comment by akontsevich** [comment]
Seems  libappindicator-gtk3 (libappindicator3) issue: https://github.com/vector-im/riot-web/issues/6767#issuecomment-424535414
