### ISSUE TITLE
Any way to re-initialize the appWindow ?

### ISSUE THREAD

**Issue by muscaiu** [electron/electron#10177]
This issue is related to [this issue from electon-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate/issues/1158)

This is the short version of the question:

I have a Header Component being loaded in every page.
This is the output from testing in 3 pages:
```
class Header extends Component {
.....

  componentDidMount() {
    console.log('header mounted')

    const appWindow = remote.getCurrentWindow();

    appWindow.on('maximize', () => {
      console.log('maximize')
      this.props.toggleFullScreen()
    })
    appWindow.on('unmaximize', () => {
      console.log('unmaximize')
      this.props.toggleFullScreen()
    })
  }
```

![loadedtwice](https://user-images.githubusercontent.com/11426309/28868239-88a39c5a-7781-11e7-82c9-b8d9517817e4.png)
So in every page chage, the output is being incremented by 1.

Any way i could **re-initialize the appWindow** before the component is being loaded?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
