### ISSUE TITLE
macOS: Add option to hide disabled window buttons?

### ISSUE THREAD

**Issue by saschagehlich** [electron/electron#10171]
Hey,

I'm currently working on an app that is using frameless windows, but with macOS's window buttons. Disabling the minimize and maximize buttons looks like this:

![screenshot 2017-08-01 16 34 23](https://user-images.githubusercontent.com/119684/28830551-5de6df4a-76d7-11e7-9460-1682a7b804bf.png)

The two disabled buttons really don't fit the window's style, so I fiddled with Electron's source code and was easily able to hide the buttons when they're disabled:

![screenshot 2017-08-01 16 35 35](https://user-images.githubusercontent.com/119684/28830603-87076462-76d7-11e7-89c1-ce14cb719fc7.png)

Looks a lot more appealing, eh?

Would you be interested in a proper PR that implements this feature with a BrowserWindow flag such as `hideDisabledButtons`? I'd also investigate on whether this is possible in Windows and Linux as well.

**Comment by groundwater** [comment]
We would most likely accept this PR. I added @felixrieseberg to take a quick look and discuss what the API might look like.

**Comment by felixrieseberg** [comment]
Hey @saschagehlich, thank you so much for prototyping this and opening up an issue! This would be an excellent PR - it's exactly the kind of stuff that can only be implemented in Electron core and adds real value to anyone building desktop apps on macOS.

We could probably integrate it with the existing `titleBarStyle`. We already added `customButtonsOnHover`, so it'd make sense to add this here, too. What do you think?

Let me know if you have any questions during the implementation!

**Comment by saschagehlich** [comment]
Hey @felixrieseberg, `titleBarStyle` sounds like the right place for this. I'll start working on it later today! Thanks for your feedback!

**Comment by saschagehlich** [comment]
@felixrieseberg Well, in the example above, I'd need to set `titleBarStyle` to both `hidden` (so that the native title bar doesn't show up) as well as `hideDisabledButtons` at the same time. Wouldn't an additional boolean flag be better for this feature?

**Comment by saschagehlich** [comment]
PR here: https://github.com/electron/electron/pull/10187
