### ISSUE TITLE
webview crash in Angular project

### ISSUE THREAD

**Issue by zh99998** [electron/electron#10176]
* Electron version: 1.6.11
* Operating system: macOS, windows

### Actual behavior
when in angular project, creating `<webview>` by javascript will got an exception
```
document.createElement('webview')

/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/we…:41 Uncaught TypeError: WebViewImpl.BrowserPlugin is not a constructor
    at WebViewImpl.createBrowserPluginNode (/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/we…:41)
    at new WebViewImpl (/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/we…:29)
    at HTMLElement.proto.createdCallback (/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/we…:283)
    at <anonymous>:1:10
createBrowserPluginNode @ /usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/we…:41
WebViewImpl @ /usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/we…:29
proto.createdCallback @ /usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/we…:283
(anonymous) @ VM107:1
```

### How to reproduce

```bash
npm install -g @angular/cli
ng new test1 --minimal
cd test1
npm start
```
```bash
electron http://localhost:4200
```
```javascript
document.createElement('webview')
```

**Comment by aminubakori** [comment]
Hello everyone,

Has anyone fixed this? I'm also facing the same issue.

* Electron Version: v1.7.5
* Operating System: MacOS
* @angular/cli: 1.2.3
* Node: 8.2.1

Help urgently needed guys.

Thank you

**Comment by vladimiry** [comment]
Based on this code https://github.com/electron/electron/blob/696c7d59fd7615b26ae1c8850ed3746489c55b89/lib/renderer/web-view/web-view.js#L446 `listener` is expected to be executed once. But in fact it's being executed a few times, and after the second execution `WebViewImpl.BrowserPlugin` becomes undefined. The cause of the issue is in that Zone.js library, Angular depends on which, does monkey patching of lots of native methods, including `window.removeEventListener`. Apparently it makes `window.removeEventListener` work asynchronously, and as result in some cases above mentioned `listener` can be executed more than one time. Workaround would be in keeping executing the original/native `removeEventListener` for the Electron's calls, here is the solution that works for me (tested on Linux):
- Put this code into the zonejs-electron-fix.ts:
```typescript
const originalRemoveEventListener = window.removeEventListener;

function removeEventListener(this: any, eventName: string, listener: () => void) {
    if (needToCallOriginalMethod(eventName, listener.toString())) {
        // calling native/original implementation
        return originalRemoveEventListener.apply(this, arguments);
    } else {
        // calling implementation patched by Zone.js
        return EventTarget.prototype.removeEventListener.apply(this, arguments);
    }
}

function needToCallOriginalMethod(eventName: string, listenerFunctionStringified: string): boolean {
    return eventName === "readystatechange"
        && listenerFunctionStringified.indexOf("registerBrowserPluginElement()") !== -1
        && listenerFunctionStringified.indexOf("registerWebViewElement()") !== -1;
}

window.removeEventListener = removeEventListener;
```
- Attach that file before Zone.js in your Angular build:
```typescript
// ...
import "./zonejs-electron-fix";
import "zone.js/dist/zone";
// ...
```

**Comment by Kroenen62** [comment]
it works, but when I restart the server, I have this error: 
`ERROR in .../src/zonejs-electron-fix.ts (3,10): Overload signatures must all be ambient or
non-ambient.` ...

**Comment by vladimiry** [comment]
I tested on typescript 2.5.2 and strict=true compiler option set in tsconfig.json

```
{
  "compilerOptions": {
    "strict": true,
```

As an option try renamed `removeEventListener` => `removeEventListenerOverloaded`:

```typescript
const originalRemoveEventListener = window.removeEventListener;

function removeEventListenerOverloaded(this: any, eventName: string, listener: () => void) {
    if (needToCallOriginalMethod(eventName, listener.toString())) {
        // calling native/original implementation
        return originalRemoveEventListener.apply(this, arguments);
    } else {
        // calling implementation patched by Zone.js
        return EventTarget.prototype.removeEventListener.apply(this, arguments);
    }
}

function needToCallOriginalMethod(eventName: string, listenerFunctionStringified: string): boolean {
    return eventName === "readystatechange"
        && listenerFunctionStringified.indexOf("registerBrowserPluginElement()") !== -1
        && listenerFunctionStringified.indexOf("registerWebViewElement()") !== -1;
}

window.removeEventListener = removeEventListenerOverloaded;
```

**Comment by Kroenen62** [comment]
Renamed `removeEventListener => removeEventListenerOverloaded` solve this problem.

Thank you

**Comment by vladimiry** [comment]
Here is the slightly updated fix that works with recent `typescript`/`@types/node` versions https://gist.github.com/vladimiry/81b5d00fa92dbf20989859ca3895ef6f

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by kingychiu** [comment]
I ended up with a slightly different version of fix (I have to remove the "this" from the function header)

```
    const originalRemoveEventListener = window.removeEventListener;

    function removeEventListenerOverloaded(eventName, listener) {
      if (listener && needToCallOriginalMethod(eventName, listener.toString())) {
        // calling native/original implementation
        return originalRemoveEventListener.apply(this, arguments);
      } else {
        // calling implementation patched by Zone.js
        return EventTarget.prototype.removeEventListener.apply(this, arguments);
      }
    }

    function needToCallOriginalMethod(eventName, listenerFunctionStringified) {
       return eventName === "readystatechange"
        && listenerFunctionStringified.indexOf("registerBrowserPluginElement()") !== -1
        && listenerFunctionStringified.indexOf("registerWebViewElement()") !== -1;
    }
```

**Comment by vladimiry** [comment]
> I have to remove the "this" from the function header

**kingychiu** `this` is needed if you run TypeScript in strict mode, so code with this will work with all modes, as opposed to code you posted above.
