### ISSUE TITLE
http://tumblr.com in a BrowserWindow hangs on macOS

### ISSUE THREAD

**Issue by boutetnico** [electron/electron#10179]
* Electron version: 1.7.5
* Operating system: macOS 10.12.6

### Expected behavior

http://tumblr.com page loads and the app stays responsive.

### Actual behavior

The whole application hangs and I get a spinning wheel.

### How to reproduce

- `git clone https://github.com/electron/electron-quick-start.git`
- Replace the following lines

```
mainWindow.loadURL(url.format({
    pathname: path.join(__dirname, 'index.html'),
    protocol: 'file:',
    slashes: true
  }))
```
with 
```
mainWindow.loadURL('http://tumblr.com')
```

- `npm install`
- `electron --debug --enable-logging .`

### Log

```
[53480:0802/172340.699349:ERROR:render_process_host_impl.cc(2094)] Request for unknown Channel-associated interface: device::mojom::ScreenOrientationListener
[53480:0802/172341.177652:WARNING:backend_impl.cc(1807)] Destroying invalid entry.
```

### Notes

- Tested with both Electron 1.6.11 and 1.7.5, the hang only occurs on macOS, not on Linux (Debian 9 Xfce).
- Not tested on Windows.

**Comment by codebytere** [comment]
Hmm...followed steps to reproduce on mac 10.12.5 with electron v1.6.11 and am not seeing the behavior. It seem unlikely to be localized to such a small macOS version bump but i'll update and check there as well

**Comment by boutetnico** [comment]
Thanks fo your reply @codebytere.
It seems the issue only occurs when the app is started from within a `tmux` session on macOS.
I found many similar related issues and the conclusion is one should not run Electron from `tmux`.
