### ISSUE TITLE
Crash during screen sharing

### ISSUE THREAD

**Issue by clusterberries** [electron/electron#10170]
* Electron version: 1.6.*
* Operating system: Windows 7

Hi! I have some reports from users that Electron app freezes and crashes when users start to share the screen using desktopCapturer. I found that the faulting module is nvd3dumx.dll, so it seems to be a problem with NVIDIA driver. Do you aware about such issues with Chromium? Is it possible, that this issue is fixed with 1.7.*? Unfortunately I don't have a chance to check it with the latest Electron.

**Comment by groundwater** [comment]
I didn't see anything on Chromium bug tracker, but if you find something let us know. We'll need more information to fix this however.

**Comment by enlight** [comment]
If the GPU driver is crashing I'd say the first thing you should do is update it or roll back to a previous version.

**Comment by clusterberries** [comment]
@groundwater yes, I also haven't find anything. What information can help to understand the root of the problem?
@enlight sure, I will ask the user.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
