### ISSUE TITLE
Navigator.getUserMedia() is deprecated, advised to use MediaDevices.getUserMedia() instead

### ISSUE THREAD

**Issue by Phoqe** [electron/electron#10174]
The `desktopCapturer` API uses a legacy method, [`Navigator.getUserMedia()`](https://developer.mozilla.org/en/docs/Web/API/Navigator/getUserMedia) which have been removed from the Web standards and is in the process of being dropped. We're advised to not use it and instead use the newer [`navigator.mediaDevices.getUserMedia()`](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) method instead.

Quote from MDN:
>This is a legacy method. Please use the newer navigator.mediaDevices.getUserMedia() instead. While technically not deprecated, this old callback version is marked as such, since the specification strongly encourages using the newer promise returning version.

>Deprecated
This feature has been removed from the Web standards. Though some browsers may still support it, it is in the process of being dropped. Avoid using it and update existing code if possible; see the compatibility table at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time.

**Comment by groundwater** [comment]
It looks like we are already recommending `navigator.mediaDevices.getUserMedia()` method already. See here: https://github.com/electron/electron/blob/master/docs/api/desktop-capturer.md

Closing issue, but feel free to reopen if you have specific places that need update.

**Comment by Phoqe** [comment]
Seems like the docs site (https://electron.atom.io/docs/api/desktop-capturer) contradicts the original API reference, but I am sure that'll be updated in due time.

**Comment by zeke** [comment]
> that'll be updated in due time.

Correct. The website is showing docs for the latest stable version, which is currently 1.6.11.
