### ISSUE TITLE
CSP and report-uri on Electron

### ISSUE THREAD

**Issue by cifratila** [electron/electron#10189]
* Electron version: All
* Operating system: All

Anyone is aware of a way to use the CSP `report-uri` feature on Electron? 
Maybe a switch/hack on Chromium's side?

From what I remember looking through the URL loading API from Chromium there is no way of specifying any Response Header when loading the `file://.../index.html`. If this would be possible, we could inject the `Content-Security-Policy` headers.

Currently the only way of using CSP is by adding the directives inside of `meta` tag and inside the `http-equip`, thus things like `report-uri` does not work.

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR.
