### ISSUE TITLE
In browser, I can use window.opener and sessionStorage to pass arguments between pages. Is that possible in electron?

### ISSUE THREAD

**Issue by luojian123456** [electron/electron#10186]
* Electron version:
* Operating system:

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by MarshallOfSound** [comment]
`window.opener` currently doesn't match the spec completely so some things that work in the browser will not work in Electron, for instance see https://github.com/electron/electron/issues/9581

`sessionStorage` should however work fine 👍
