### ISSUE TITLE
Debugger cannot access web workers

### ISSUE THREAD

**Issue by giladno** [electron/electron#10199]
When using the internal debugger ([`mainWindow.webContents.debugger`](https://github.com/electron/electron/blob/master/docs/api/debugger.md)), it is unable to access web workers created from the renderer.

Enabling both **Runtime.enable** and **Debugger.enable** will only trigger events related to the renderer - not the web worker.

### Main
```
_debugger = mainWindow.webContents.debugger;
_debugger.on('message', (evt, method, params)=>{
	if (method=='Debugger.scriptParsed')
		return console.log(method, params.url);
	console.log('DEBUGGER', method, params);
});
_debugger.attach('1.2');
_debugger.sendCommand('Debugger.enable');
_debugger.sendCommand('Runtime.enable');
```

### Renderer
```
let worker = new Worker('worker.js');
```

Demo project: https://github.com/giladno/electron-quick-start

```
$ git clone https://github.com/giladno/electron-quick-start.git
$ cd electron-quick-start
$ npm install && npm start
```

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
