### ISSUE TITLE
Electron 1.7.4 Bug! All webviews on page change zoom level instead of one

### ISSUE THREAD

**Issue by d9k** [electron/electron#10196]
* Electron version: 1.7.4, 1.6.12, 1.6.8
* Electron-builder version: 17.10.0
* Operating system: Linux Ubuntu 16.04

### Expected behavior

There are two `<webview>` tags on page.
When I execute code `document.getElementsByTagName('webview')[0].setZoomFactor(2)` only the first `<webview>` on page must change it's zoom factor.

### Actual behavior

BOTH webviews change their zoom factor.
Even worse, in my application I have two `electron.BrowserWindow`s with `<webview>` inside each. When I change zoom factor for `<webview>` at first `BrowserWindow` the `<webview>` at second window changes too (this case is more hard to reproduce)!

### How to reproduce

Add two `<webview>` tags with filled `src` tag to one html page and navigate electron browser to this page. Execute code `document.getElementsByTagName('webview')[0].setZoomFactor(2)` in Dev Tools.

**Comment by mikesteele** [comment]
Do your webviews share the same domain? We came across a similar issue and it seems like it's standard Electron behavior to share zoom level on webviews with the same domain. (You can see it on Chrome too)

**Comment by mikesteele** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=390775

**Comment by d9k** [comment]
> Do your webviews share the same domain? We came across a similar issue and it seems like it's standard Electron behavior to share zoom level on webviews with the same domain. (You can see it on Chrome too)

Thanks! Yes, the webviews share the same domain. Is there exist a way to disable zoom level sharing?

**Comment by mikesteele** [comment]
This Chromium thread talks about the `chrome.tabs.zoom` API, which bypasses same-domain zoom level sharing. (https://bugs.chromium.org/p/chromium/issues/detail?id=390775#c15)

Though it'll require some investigation whether it's available for use in Electron. (nw.js says it has support for the chrome.tabs API)

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
