### ISSUE TITLE
Browser window is not redrawn/refreshed correctly

### ISSUE THREAD

**Issue by redloro** [electron/electron#10192]
* Electron version: 1.7.5
* Operating system: Raspbian Jessie

### Expected behavior

Run the electron-quick-start project and resize the browser window.  The browser window and contents should resize correctly.

### Actual behavior

Browser window resizes but the contents are not resized correctly; the contents get mixed up in the window, including the actual menu bar and HTML content.

See below: 
![screencast 2017-08-03 22-03-20-iloveimg-compressed](https://user-images.githubusercontent.com/6530719/28951419-dd5c2362-7898-11e7-95d8-c2c6a8c67cd0.gif)

### How to reproduce

Download and run the electron-quick-start project with Electron 1.7.5 and resize the browser window.  The browser window and contents should resize correctly.

NOTE: this works fine on Windows 10 and OSX.  Also works on Raspbian Jessie with Electron 1.6.11.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
