### ISSUE TITLE
Electron Window Not Fullscreen (type is 'desktop')

### ISSUE THREAD

**Issue by Adam-Morris** [electron/electron#10202]
* Electron version: 1.4.14
* Operating system: Arch Linux (Gnome Desktop)

### Expected behavior

When BrowserWindow `type` is set to `'desktop'`, the application should cover the whole screen.

### Actual behavior

It will default to the normal width and height...

### How to reproduce

```
$ git clone https://github.com/Adam-Morris/electron-desktop-widgets/tree/master
$ cd electron-desktop-widgets
$ electron .
```

If you are on Linux remember to do `--enable-transparent-visuals --disable-gpu`

**Comment by jkleinsc** [comment]
The documentation on what BrowserWindow type of `desktop` actually means in Linux is unclear here: 
https://electron.atom.io/docs/api/browser-window/#new-browserwindowoptions
The only information provided is as follows:

> On Linux, possible types are `desktop`, `dock`, `toolbar`, `splash`, `notification`.
