### ISSUE TITLE
[REQUEST]Add Non Google dependencie for Geolocation API

### ISSUE THREAD

**Issue by subversivo58** [electron/electron#10206]
Is it possible to get geolocation without relying on the Google API? An alternative would be welcome ... democratizing geolocation would be more useful than holding onto exclusivity.

**Comment by codebytere** [comment]
For the near future, we're going to remain with the Google API as it fits our needs. At some point we might look into this though :)

**Comment by ckerr** [comment]
Is there an existing abstraction layer for using multiple geolocation sources?

I wouldn't mind doing this, but as @codebytere says, it's not a high priority.
