### ISSUE TITLE
Cannot Install Electron

### ISSUE THREAD

**Issue by jajaperson** [electron/electron#10200]
* Operating system: macOS Sierra v10.12.6

When running the following commands I get this error from `npm i electron`

```bash
npm init
npm install extract-zip
npm install electron
```

```
Error: unable to verify the first certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1098:38)
    at emitNone (events.js:105:13)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket._finishInit (_tls_wrap.js:628:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:458:38)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.6.11 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.6.11 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I am aware that these errors have been seen before in issue #9323, but I have followed all the steps there and I still have the same problem

**Comment by jajaperson** [comment]
I got the same error when running `npm install` in the `electron-quick-start` folder.

**Comment by sreetamdas** [comment]
Can confirm and reproduce problem in `Ubuntu 17.04 Zesty`

**Comment by jajaperson** [comment]
@sreetamdas No :(

**Comment by webskydavid** [comment]
The same problem here `Windows 7 64bit`

**Comment by zeke** [comment]
An `ELIFECYCLE` error is indicative of a network issue. See [installation.md#troubleshooting](https://github.com/electron/electron/blob/master/docs/tutorial/installation.md#troubleshooting) for details on how to work around it.
