### ISSUE TITLE
webview history handle

### ISSUE THREAD

**Issue by Devhercule** [electron/electron#10208]
Hi,

I have a question about the webview history : I can display the history array of a webview using:

`console.lo(webview.getWebContents().history)`

I'm also using `webview.goBack()` and `webview.goForward()` to go back and go forward. It works.

My question is : How can I observe changes on the array webview.getWebContents().history

There is no Listener in webContent allowing to add events listener on history changing.

I whould like to do "actions" when the array of history of a webview is modified (add, delete, update)

Is this possible?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

FWIW you want this 👍 
https://electron.atom.io/docs/api/web-contents/#event-will-navigate

**Comment by Devhercule** [comment]
Thank you for response, but that's not what I asked for.

I know will-navigate event, it is not appropriate to my need.. because he can bot listen when a line is deleted from history...

**Comment by MarshallOfSound** [comment]
@Devhercule There are events to do this, you just need to choose the one that suits your scenario the best.

For instance: https://electron.atom.io/docs/api/web-contents/#event-did-navigate-in-page

**Comment by Devhercule** [comment]
@MarshallOfSound did-navigate-in-page does not listen when lines are deleted from history array. GoBack() and goForward() add, delete and modify lines in the array of webview history. No event allows to do this..

**Comment by MarshallOfSound** [comment]
@Devhercule Bearing in mind that the `NavigationController` is currently implemented in JS land there are definitely events to get what you want.  At the webcontents level there is `navigation-entry-commited` and in the actual webview you can just do `window.onpopstate`

**Comment by Devhercule** [comment]
@MarshallOfSound it is really interesting what you sent me, I'm testing `navigation-entry-commited` with 

`webview.getWebContents().on('navigation-entry-commited'...`

However, I did'nt understand where should i use `window.onpopstate`
