### ISSUE TITLE
Navigating to another page will close all opened window

### ISSUE THREAD

**Issue by WhiteFur** [electron/electron#10218]
* Electron version: 1.7.4
* Operating system: macOS Sierra 10.12.1

I opened one or more new windows and navigated to another page, the opened windows are closed.
e.g.,
Here is a page loaded by main window
```html
<a href="https://www.google.com" target="_blank">open new window</a>
<a href="https://github.com/electron">Navigate to electron github page</a>
```
I clicked "open new window" to create and show a BrowserWindow.
Then I clicked "Navigate to electron github page", the main window navigate to https://github.com/electron but the BrowserWindow just opened is closed.

**Comment by WhiteFur** [comment]
This happens on Windows also.

**Comment by Vaggal** [comment]
For me on Windows 7 x64 this happens with both electron versions 1.7.6 and 1.6.11 .

**Comment by WhiteFur** [comment]
Is it on-going? Thank you.

**Comment by WhiteFur** [comment]
Is this forgotten?  How can I start to fix the bug?

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
