### ISSUE TITLE
about the example of Via Spectron configuration

### ISSUE THREAD

**Issue by Maybrittnelson** [electron/electron#10228]
* Electron version: 
v1.6.11
* Operating system:
win10
### Actual behavior
when i use path to main.js ,nothing happened.when use .exe, it run two cmd and the .exe run
but nothing in the index.html

### How to reproduce
![123](https://user-images.githubusercontent.com/20365012/29117741-ee5108ca-7d31-11e7-9cfc-d2a019af7742.png)

**Comment by MarshallOfSound** [comment]
@Maybrittnelson Please raise spectron issues on the spectron repo
