### ISSUE TITLE
Wrong file/folder name in node headers

### ISSUE THREAD

**Issue by Stanzilla** [electron/electron#10224]
* Electron version: 1.6.12
* Operating system: Windows 8.1

### How to reproduce

So this is a weird one, I was looking through my ~\.electron-gyp\ folder and noticed that it in `node-gyp`it created an `iojs-1.6.12 ` folder which had me puzzled for a few minutes. At first I didn't even remember iojs even reaching a that high version number and it was the version number of the current electron but I was like whatever. I then deleted it, figuring it was some old remnant but watched it get recreated when I built a project. This lead me to open an issue on electron-rebuild where it was then pointed out that here

https://github.com/electron/electron/blob/717a1a666cabf0479bdc981ef7f08663804d050a/script/create-node-headers.py#L42-L43

electron creates that folder and is hardcoding the iojs name. Now, I am certain I can't be the only person that might get confused by this and I was wondering if this could be changed or, if there would be backwards compatability problems if it was.

**Comment by MarshallOfSound** [comment]
> if there would be backwards compatability problems if it was.

This is a legacy issue `node-gyp`, basically, any version between `1.x` and `3.x` is assumed to be `iojs` and every other version is assumed to be `node`.  There isn't much we can do about this so for legacy reasons we have to keep the `iojs` title.
