### ISSUE TITLE
why not support XP?

### ISSUE THREAD

**Issue by likenamehaojie** [electron/electron#10226]
1  my electron release is 1.0.1 , depended chrome 49
but  when i runing with xp give me not Win32 prom

**Comment by MarshallOfSound** [comment]
@likenamehaojie Chromium dropped support for Windows XP a long time ago and therefore Electron cannot continue supporting it.  Even Microsoft no longer supports the majority of XP installs

**Comment by jetiny** [comment]
the windows xp version https://github.com/jetiny/electron-xp
