### ISSUE TITLE
protocol.registerHttpProtocol does not persist uploadData in redirect when request method is PUT

### ISSUE THREAD

**Issue by stulees** [electron/electron#10229]
* Electron version: 1.6.6
* Operating system: Windows, Linux

### Expected behavior

In configuring the `redirectRequest` object to provide to the callback function of `protocol.registerHttpProtocol` handler, when request method is PUT and `uploadData` exists and it is configured in `redirectRequest` object, I expect the callback to execute no differently than a POST

### Actual behavior

The callback with `redirectRequest` object does not seem to maintain the body (uploadData) of the request when the request method is PUT, but it does so correctly when the request method is POST

### How to reproduce

Below is the handler for `protocol.registerHttpProtocol("rchttp", schemeHandler);` which is called when Electron app is `ready`. 

```
function schemeHandler(request, callback) {
  let redirect = {
      method: request.method,
      url: request.url.slice(2)
    };

  if (request.method === "POST" || request.method === "PUT") {
    redirect.uploadData = {
      contentType: "application/json",
      data: request.uploadData ? request.uploadData[0].bytes.toString() : ""
    };
  }

  return callback( redirect );
}
```

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by psxninja** [comment]
If you use `Fetch` API will works
