### ISSUE TITLE
Blurry font render at electron‘s flash but good at chrome for the same pepflashplayer

### ISSUE THREAD

**Issue by StinsonZhao** [electron/electron#10235]
I've found rendering Chinese font(SimSun) in electron app's flash plugin is not friendly, the comparison ( top(bad) is in electron, bottom(better) is in chrome, both in flash plugin):

![a81c7d1b554f6c6287ce24fba68813c8](https://user-images.githubusercontent.com/6703905/29168265-bf1dc8b6-7e00-11e7-935c-eced0dea88f8.jpg)

![a90b1da8b6ffbe48f5776eef61e65a76](https://user-images.githubusercontent.com/6703905/29168266-c1245364-7e00-11e7-9576-e1150bc04350.png)

At the same PC with Win10, with the same pepflashplayer.dll, the font is SimSun (in
Chinese called 宋体), and I find the chrome uses this font's dot-matrix-fonts representation, but chromium in electron doesn't.

I have considered the impact of **directwrite** , but my chrome's version is 60, that is meaning it renders font using **directwrite**. So both Chrome and Electron chromium use **directwrite**, Why it's different?

And I have looked through the issue https://github.com/electron/electron/issues/8708
But it can't solve my doubts, if it's due to chromium mandatory **directwrite**， why it looks good at latest Chrome?

**Comment by 6a7070** [comment]
I am also interested in understanding this problem. I notice the blurry font when using other apps that rely on electron. If chrome's fonts are clear, why can't we do the same for electron?

**Comment by sofianguy** [comment]
We are no longer providing bug fixes for bug reports later than 2.0.x. Is this still a bug in later versions of Electron?

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
