### ISSUE TITLE
Frameless BrowserWindow is wrong size when position is specified

### ISSUE THREAD

**Issue by abidasari** [electron/electron#10231]
* Electron version: 1.6.11
* Operating system: Windows 7 and 10

### Expected behavior

On creating a BrowserWindow and loading a webpage in it, the window opened should be of the specified dimensions. No red should be visible.

### Actual behavior

The window size is a few pixels off. So, a red boundary is visible around the yellow box.
### How to reproduce

  $ git clone https://github.com/abidasari/electron-quick-start -b BrowserWindowPositionBug
  $ npm install
  $ npm start

If you can't reproduce the bug immediately try changing the window position coordinates in main.js. It appears to be somehow dependent on the screen resolution.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
