### ISSUE TITLE
Google Auth popup does not send back auth response to webview

### ISSUE THREAD

**Issue by MathieuDebit** [electron/electron#10236]
When using the Google authentication in some services like Dropbox Paper, the popup to login with Google does not seem to communicate with the webview.

* Electron version: 1.7.6
* Operating system: MacOS Sierra 10.12.6

### Expected behavior

Popup closing with Google authentication response.

### Actual behavior

Popup become blank.

### How to reproduce

> https://github.com/MathieuDebit/electron-quick-start/pull/1

```
git clone https://github.com/MathieuDebit/electron-quick-start.git -b google-auth-popup-issue
cd electron-quick-start
npm install
npm start
```

#### case 1:
- click on *Sign Up for free with Google*
- choose a Google account
- allow asked permissions

#### case 2:
- click on *Sign Up for free with Google*
- choose a Google account
- cancel asked permissions

**Comment by MarshallOfSound** [comment]
Merging into https://github.com/electron/electron/issues/9581

**Comment by sudhakar3697** [comment]
Observing this issue in Electron 9 version running on Windows. Thank you.
