### ISSUE TITLE
Stepping into snapshotted source code

### ISSUE THREAD

**Issue by as-cii** [electron/electron#10234]
In Atom we are currently using `mksnapshot` to bundle almost the entirety of the codebase into a blob which is then used to minimize startup time. However, snapshots in Chromium were released with a limitation that prevents embedded code from being stepped into while debugging with the DevTools. 

For this reason, in Atom we ship both the snapshot blob and the unbundled source code, so that users that don't have a local checkout of Atom can still launch it in dev mode (i.e. a particular mode that, among the other things, ignores the snapshot) and report more useful information by stepping through Atom's core code.

Even if this works, we think it's suboptimal for two motivations:

1. It forces users to know about dev mode, thus making it inconvenient from a UX standpoint.
2. It doubles the size of the bundle/installer, which makes installing Atom quite slow (especially on Windows). This is mostly due to having to copy several small files and some platforms handle this poorly. While we could turn on .asar to address this particular problem, that wouldn't solve the installer size issue, which would still be twice as large as the optimal one.

According to @hashseed, however, stepping through snapshotted code should actually have been possible, so he reported the bug in https://bugs.chromium.org/p/v8/issues/detail?id=6274 and, in the same issue, provided a patch to fix it. ✨ 

I think the patch hasn't shipped in any stable release of Chromium yet, but I wonder if we could back-port it to Electron so that in Atom we can workaround that limitation and address both of the concerns mentioned above. @groundwater: what do you think? 💭 

Thanks!

/cc: @nathansobo @iolsen

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR.
