### ISSUE TITLE
autoUpdater.checkForUpdates() throws Error: Invalid JSON response

### ISSUE THREAD

**Issue by naheller** [electron/electron#10245]
* Electron version: 1.7.5
* Operating system: macOS Sierra 10.12.5

### Expected behavior

The Electron app should call `autoUpdater.quitAndInstall()` causing the app to update with any new features that were added.

### Actual behavior

This error is displayed immediately after the app launches:

![screen shot 2017-08-10 at 3 57 19 pm](https://user-images.githubusercontent.com/18204925/29196971-e47424a2-7dec-11e7-84d5-523ae56ec4b6.png)

I am using [electron-release-server](https://github.com/ArekSredzki/electron-release-server) with Docker to test the auto update process. Here is a snippet of the relevant code in `main.js`:

```
// Auto Updater
var os = require('os');
var autoUpdater = require('electron').autoUpdater;
var platform = os.platform() + '_' + os.arch();  // usually returns darwin_64
var appVersion = require('./package.json').version;

autoUpdater.setFeedURL('http://653e8fc6.ngrok.io/update/'+platform+'/'+appVersion);

app.on('update-downloaded', () => {
  autoUpdater.quitAndInstall()
})

app.on('ready', () => {
  autoUpdater.checkForUpdates()
...
...
...
}
```

Notice the **ngrok** feed URL. I'm using a proxy because `localhost` doesn't work, and I thought it better to avoid any internal company network shenanigans. In any case, ngrok appears to respond to `autoUpdater.checkForUpdates()`'s GET with a 200:

![screen shot 2017-08-10 at 3 58 23 pm](https://user-images.githubusercontent.com/18204925/29197108-dfa04dd8-7ded-11e7-9b44-cbcbc5b361ed.png)

As for the JSON response, I've received the following using Postman:

![screen shot 2017-08-10 at 5 14 57 pm](https://user-images.githubusercontent.com/18204925/29197342-81163cee-7def-11e7-90ce-265f335056ce.png)

I've accounted for the package.JSON `productName` issue discussed in [this article](http://electron.rocks/auto-updater-application-name/), and issues #6951 and #1192 do not seem to apply to my specific situation. 

Your advice would be greatly appreciated!

**Comment by MarshallOfSound** [comment]
The `url` in your `package.json` is invalid, I.e. it's not a real URL.  Should be something like `http://localhost/download....`

**Comment by naheller** [comment]
MarshallOfSound,

I used ngrok because I wanted to circumvent my company's internal network and monitor the GET request using a proxy (for autoUpdater testing purposes). 

Was this the wrong approach? How would I change the URL to be presented correctly? 

I appreciate your help

**Comment by MarshallOfSound** [comment]
@naheller Using `ngrok` is perfectly fine, I was talking about the `url` property in the returned JSON.  It is not a valid URL so that error will be thrown

**Comment by naheller** [comment]
MarshallOfSound,

Thank you for the reply. How would I alter the `url` property coming from the electron-release-server to correct this error?

**Comment by MarshallOfSound** [comment]
@naheller `electron-release-server` has a `baseUrl` config property or something like that I beleive

**Comment by naheller** [comment]
Thanks. Is there any way to accomplish this without modifying npm packages?
