### ISSUE TITLE
Remove finalUpdate parameter of webContents found-in-page event

### ISSUE THREAD

**Issue by xywz** [electron/electron#10241]
It is effectively a constant and was removed by @zcbenz in https://github.com/electron/electron/commit/fbac6356873a42660fae4b3b7cec9af0811a9f57 but was added back in https://github.com/electron/electron/commit/f757912f902e09df340ed48ed1ff60a7cc8dff58 because it seemed to be an undocumented parameter.

**Comment by groundwater** [comment]
Please see https://github.com/electron/electron/issues/10934#issuecomment-340066195
