### ISSUE TITLE
Touch interaction in a webview fails when Cesium is active

### ISSUE THREAD

**Issue by bgradin** [electron/electron#10249]
* Electron version: 1.5.0
* Operating system: Windows 10

### Expected behavior

Cesium should have no effect on the touch screen interactivity of the application.

### Actual behavior

On the touchscreen monitor I'm using (Planar PCT2785), touch interactions don't register for quite a while (it's inconsistent, but usually around five touch interactions) in a webview if [Cesium](cesiumjs.org) is running.

Furthermore, once they start registering in the webview, they stop registering elsewhere in the application.

### How to reproduce

The following example demonstrates the undesired behavior:

```html
<style>
	body {
		margin: 0;
		display: table;
	}
	
	body > * {
		display: table-cell;
		vertical-align: top;
		width: 50vw;
		height: 100vh;
	}

	iframe {
		border: none;
	}
	
	webview {
		width: 100%;
		height: 100%;
	}
</style>
<iframe src="https://cesiumjs.org/Cesium/Build/Apps/CesiumViewer/index.html"></iframe>
<div><webview src="https://www.google.com"></webview></div>
```

**Comment by bgradin** [comment]
Could be related to #6563

**Comment by codebytere** [comment]
We no longer actively support bugfixes for `1.5.x` so i'm going to go ahead and close this, but if you see this issue on newer versions of Electron I can certainly reopen.
