### ISSUE TITLE
Using electron-asar-updater is throwing error.

### ISSUE THREAD

**Issue by manpreetrsystems** [electron/electron#10248]
I am using electron-asar-updater in my project but when I am running it is throwing error as "core.require" is not a function. 
I have already installed all the related dependecies.
what could be the possible solution???

**Comment by MarshallOfSound** [comment]
You should raise issues for `electron-asar-updater` on it's repository, it is not associated with the core Electron library.

https://github.com/whitesmith/electron-asar-updater
