### ISSUE TITLE
Inset option for customButtonOnHover

### ISSUE THREAD

**Issue by gerges-zz** [electron/electron#10243]
### Feature request

`customButtonsOnHover` fixes a lot of issues with drag and `pointer` styles, but my app currently uses `hidden-inset` so this setting changes the position of the buttons. I'd suggest `customButtonsOnHover` either be an option outside of `titleBarStyle` that respects `titleBarStyle`s values ('hiddenInset' or `hidden') or the addition of a `customButtonsOnHoverInset`.

As a separate note, the docs for `customButtonsOnHover` currently specify it's a Boolean type, but it's a string value.

**Comment by nehbit** [comment]
Would love to have this as well. Thanks so much for the work!
