### ISSUE TITLE
typos at 'electron/docs/api/dialog.md'

### ISSUE THREAD

**Issue by xwdeng** [electron/electron#10244]
### Expected behavior
console.log(dialog.showOpenDialog({properties: ['openFile', 'openDirectory', 'multiSelections']}))

### Actual behavior
console.log(dialog)

**Comment by MarshallOfSound** [comment]
That line in the docs was added in https://github.com/electron/electron/commit/06a354a2eb5334840894f2865c8237956e38e9c9 I believe to avoid the unused vars rule blowing up in standard.  Pretty sure that rule is turned off now though.
