### ISSUE TITLE
dialog.showOpenDialog options working not properly

### ISSUE THREAD

**Issue by GerryLon** [electron/electron#10252]
* Electron version: v1.6.12
* Operating system: CentOS Linux release 7.3.1611 (Core)

### Expected behavior
in main.js:
```js
console.log(dialog.showOpenDialog({
  properties: ['openFile', 'multiSelections', 'openDirectory']
}));
```
this should act: file and directory both can be selected multiply.
I think the `openDirectory` is buggy.

### Actual behavior
in main.js:
```js
console.log(dialog.showOpenDialog({
  properties: ['openFile', 'multiSelections', 'openDirectory']
}));
```
**only directory can be selected multiply, file can not be selected.**
and when I set the properties to: `['openFile', 'multiSelections']`,
then file and directory both can be selected multiply.

**Comment by Or3stis** [comment]
From the electron documentation about  [dialog.showOpenDialog#methods](https://electron.atom.io/docs/api/dialog/#methods)

> "Note: On Windows and Linux an open dialog can not be both a file selector and a directory selector, so if you set properties to ['openFile', 'openDirectory'] on these platforms, a directory selector will be shown."

Since you are using Linux you should remove the `openDirectory`.

```
console.log(dialog.showOpenDialog({`
  properties: ['openFile', 'multiSelections']
}));
```

**Comment by GerryLon** [comment]
good answer!

**Comment by MarshallOfSound** [comment]
Thanks @Or3stis 👍
