### ISSUE TITLE
The `Event.returnValue` property works while a `return` statement does not.

### ISSUE THREAD

**Issue by Miroware8** [electron/electron#10259]
* Electron version: 1.7.6
* Operating system: Windows 8.1

### Expected behavior

When listening to the `beforeunload` event and trying to cancel it, "`return true;`" should cancel the window close.

### Actual behavior

Using "`return true;`" within a callback function for the `beforeunload` event does not cancel the close while "`event.returnValue = true;`" does. In fact, `Event.returnValue` is [supposed to be deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Event/returnValue).

### How to reproduce

This cancels the window close.
```js
window.addEventListener("beforeunload", function(evt) {
    evt.returnValue = true;
});
```
This does not.
```js
window.addEventListener("beforeunload", function(evt) {
    return true;
});
```
To quickly test this issue you can open up the developer console on any Electron app (that does not already cancel the window close) and paste the above pieces of code before attempting to close the window.
(As for why I am using `true`, [the documentation](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#event-close) says it will work with any value other than `undefined`.)

**Comment by vanessayuenn** [comment]
`window.addEventListener('beforeunload', ...)` and `window.onbeforeunload` actually behave differently. 

If `window.onbeforeunload` is used, the following two lines results in the same behavior (i.e. window will not close): 
```javascript
window.onbeforeunload = function(e) { e.returnValue = false }
window.onbeforeunload = function(e) { return false }
```
...whereas if `window.addEventListener('beforeunload', ...)` is used, `evt.returnValue` has to be set explicitly. 

I do agree this is confusing and should be noted in the documentation.
