### ISSUE TITLE
When electron started with --inspect, `console.debug` gets defined but outputs nothing

### ISSUE THREAD

**Issue by alexstrat** [electron/electron#10260]
* Electron version: 1.7.6
* Operating system: macOS (but i guess that's the same w/ other OSs)

### How to reproduce

Starting from [electron-quick-start](https://github.com/electron/electron-quick-start) with Electron@1.7.6, drop these lines in `main.js`:
```js
console.log('typeof console.debug :', typeof console.debug);
if (console.debug) console.debug('Debugging');
```

```bash
$ npm start
typeof console.debug : undefined
$ npm start -- --inspect
typeof console.debug : function
# nothing else
# nothing in chrome://inspect console neither
```

### Expected behavior
Would expect either:
- `console.debug` is not defined whatever started with `--inspect` or not
- `console.debug` outputs things somewhere (where?)

**Comment by vanessayuenn** [comment]
@alexstrat that's because the `console.debug()` method doesn't actually exist in node. It seems to be implemented as a no-op, though there's no mention of it in their [docs](https://nodejs.org/api/console.html) at all.

**Comment by alexstrat** [comment]
> that's because the console.debug() method doesn't actually exist in node. It seems to be implemented as a no-op, though there's no mention of it in their docs at all.
@vanessayuenn yes indeed! But `console.debug` **exists** (but does nothing) when `--inspect` is used, which is the problem.

Note `node.js` (v7.9.0) has the same behavior.
```bash
$ node
> console.debug
undefined


$ node --inspect
> console.debug
[Function: debug]
> console.debug('f')
undefined
# noting displayed, even chrome://inspect
```
The issue is reported in https://github.com/nodejs/node/issues/12675 but does not look like there is real will to fix it.

Moreover, [MDN documentation](https://developer.mozilla.org/en/docs/Web/API/console) says that console.debug is deprecated and is no-op starting with Chrome 58.

I guess therefore, it's normal that `console.debug` is defined but no-op.
