### ISSUE TITLE
d3dcompiler.dll file code sign has expired

### ISSUE THREAD

**Issue by yhostc** [electron/electron#10262]
The `d3dcompiler.dll` file code signature has expired,  and will encounter dangerous tips for security software

![wechatimg7](https://user-images.githubusercontent.com/1823025/29278825-6d55835c-8148-11e7-9014-bde2f06e2c1f.jpeg)

* Electron version: v1.7.6
* Operating system: window 10 win32

### Expected behavior
It is safety, no dangerous tips 

### Actual behavior
Have dangerous tips 

### How to reproduce
electron builder Win32  package

**Comment by codebytere** [comment]
Since the issue is with `electron-builder`, you should open an issue [there](https://github.com/electron-userland/electron-builder).
