### ISSUE TITLE
Crash Reporter - Custom Headers

### ISSUE THREAD

**Issue by VishwasShashidhar** [electron/electron#10278]
* Electron version: 1.7.5
* Operating system: MacOS, Windows

### Expected behavior

For better security, we'd like to have the crash reporter send custom authentication headers to our crash reporter server.

### Actual behavior

Currently, there is no mechanism to set custom headers as part of the crash reporter request.

Is there anyway this can be achieved or has anyone done this before?

### How to reproduce

N/A

**Comment by abelmathew** [comment]
AFAIK, there isn't a way to do this today. 

My knowledge of the code here is limited. IF I had to guess, I would say it maybe a bit hairy to implement given the use of (crashpad_handler)[https://chromium.googlesource.com/crashpad/crashpad/+/master/handler/crashpad_handler.md] on MacOS and separate custom out-of-process mechanisms used with breakpad on Linux and Windows. 

On our system, we currently use QS parameters on the submit_url to provide information like tokens to our crash management service. Another option is to pass this information via (`extra` object when calling `crashReporter.start()`)[https://github.com/electron/electron/blob/master/docs/api/crash-reporter.md#crashreporterstartoptions], which get submitted as multipart/form-data. Note, you can only specify strings to the `extra` object.

**Comment by VishwasShashidhar** [comment]
Thanks @abelmathew. I feared that to be the case. We have considered the alternatives (QS & extras attribute) in case the headers option wasn't available, just needed a confirmation.

**Comment by abelmathew** [comment]
@VishwasShashidhar happy to give the limited info I know. I'm not privy to internal development here so it's worth some of the Electron maintainers to chime in before you completely abandon this effort.

**Comment by VishwasShashidhar** [comment]
@abelmathew Sure, makes sense, thanks!

**Comment by danmo** [comment]
Also need this feature, as integrating with cloud endpoints normally require authorization headers.
Amazed this is not possible at the moment.

**Comment by danmo** [comment]
Ok, coming back with a workaround solution.
Instead of setting headers, add the required data as query string parameters. The only drawback is that this data must be set at crashReporter.start(...) time.

```
  crashReporter.start({
    submitURL: `${CRASH_API_ENDPOINT}?param1=${value1}&param2={value2}`,
    autoSubmit: true,
    ...
  });

```

It's limited but it partially does the job.
