### ISSUE TITLE
Uncaughtexception - Cannot read property 'close' of null at rpc-server.js:463

### ISSUE THREAD

**Issue by juturu** [electron/electron#10274]
* Electron version: 1.7.3
* Operating system: Windows

### Expected behavior
No uncaught exception

### Actual behavior
Sometimes closing of new browserwindow hits this error

Cannot read property 'close' of null at EventEmitter.<anonymous> (rpc-server.js:463:39) 
at emitOne (events.js:96:13) 
at EventEmitter.emit (events.js:191:7) 
at WebContents.<anonymous> (browser\api\web-contents.js:256:13) 
at emitTwo (events.js:106:13) 
at WebContents.emit (events.js:194:7)

### How to reproduce
No consistent repro steps.

**Comment by cumajkeee** [comment]
HI @juturu, I have this error while do save file and saveDialog appears. It's reproduced approximate 1/5 times. Is it somehow possible to solve this right now? 1.8.x isn't released yet to stable :(
