### ISSUE TITLE
Windows shell.openExternal url quote encoding

### ISSUE THREAD

**Issue by mjbvz** [electron/electron#10285]
**Electron Version**: 1.7.5
**OS**:  Windows 10.0.15063

**Repo Steps**
1. On windows machine with Firefox or Chrome set as the default browser:
2. Run the program:

```js
const electron = require('electron')
const shell = require('electron').shell

const app = electron.app

app.on('ready', function () {
    shell.openExternal(`https://github.com/Microsoft/vscode/issues?q=is:issue+label:bug+milestone:"August+2017"+is:closed`)
  }
)
```

**Expected**
Opens: https://github.com/Microsoft/vscode/issues?q=is:issue+label:bug+milestone:"August+2017"+is:closed

**actual**
Opens https://github.com/Microsoft/vscode/issues?q=is:issue+label:bug+milestone:August+2017+is:closed

This does not seem to happen on Mac or on Windows if Edge is set as the default browser

From https://github.com/Microsoft/vscode/issues/32488

**Comment by codebytere** [comment]
Is this still happening on `1.8.x` or `1.7.11`?

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
