### ISSUE TITLE
Idea: Allow selection on macOS's TouchBarScrubber

### ISSUE THREAD

**Issue by alopix** [electron/electron#10288]
* Electron version: 1.7.6
* Operating system: macOS 10.13 Beta

### Expected behaviour
a) Allow `selectedIndex` for `TouchBarScrubber` just as `TouchBarSegmentedControl` to set a selection of active scrubber item and get the currently active item. The `NSScrubber` has a native property `selectedIndex` for that. Setting it with the `animator()` would be nice too to animate the selection change.
b) Allow to scroll to a certain `NSScrubber` item with the native call to `NSScrubber.animator().scrollItem(at: index, to: alignment)`.

Possibly related to @MarshallOfSound who seems to be the Touch Bar maintainer already helping out with a bug 😉

**Comment by jr-k** [comment]
Any update on this ? I really need a manual method "setSelectedIndex", Thanks !

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by samuelgjabel** [comment]
mmh...what aboout this feature? :)

**Comment by theLMGN** [comment]
I've decided to add TB support to one of my apps and not having this is a real issue for my UX. Has anyone got a work around for doing this?

**Comment by theLMGN** [comment]
Here again, The TouchBarScrubber is the **only** way to make a scrolling list of items (all other elements just get cut off) and having a list of items that are selectable on the touch bar, but if the UI state changes on the screen, there's no way to replicate this back over to the touch bar (except for adding an icon to the element)
