### ISSUE TITLE
Touchpad Scrolling Delay

### ISSUE THREAD

**Issue by NameThatFollows** [electron/electron#10286]
* Electron version: 1.7.5
* Operating system: Windows 10 Pro

### Expected behavior
When scrolling with two fingers, the content should scroll in realtime with the gestures. 

### Actual behavior
When scrolling with two fingers, there is a slight delay of about a half second to a full second and the content jumps the distance the fingers move on the touchpad. 

### How to reproduce
There does not seem to be a way to consistently reproduce the issue. The issue can be resolved by resizing the window.

**Comment by Yohanna** [comment]
This might be causing bugs like this [Microsoft/vscode #35191](https://github.com/Microsoft/vscode/issues/35191), since the workaround is the same.

**Comment by bpasero** [comment]
Fyi Chrome has a fix out: https://bugs.chromium.org/p/chromium/issues/detail?id=713907#c28

Ideally this could be backported to Electron.

**Comment by sguergachi** [comment]
Hopefully this can be resolved since the Chrome issues was marked fixed. Thanks!

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
