### ISSUE TITLE
Drop into Electron app does not work 1.7.5

### ISSUE THREAD

**Issue by beljand** [electron/electron#10282]
* Electron version: 1.7.5
* Operating system: macOS

### Expected behavior

Drag-Drop into Electron should fire events

### Actual behavior

no events are emitted on Drag-drop into Electron

**Comment by bpasero** [comment]
Eventually related: https://github.com/electron/electron/issues/9840

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
