### ISSUE TITLE
🐞 Disapearing tile-bar-menus after hibernation

### ISSUE THREAD

**Issue by mojoaxel** [electron/electron#10297]
I encountered the problem that the title-bar-menu of electron apps disappears after the workstation wakes up after hibernation. `window:toggle-menu-bar` also does not work.

* Electron version: 1.4.16 (e.g. Hyper 1.3.3, Atom )
* Operating system: Ubuntu 16.04, 64x

### Expected behavior

![image](https://user-images.githubusercontent.com/600565/29434490-81a4fa74-83a3-11e7-8ab5-5918728fe42a.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/600565/29434485-7b64c3e2-83a3-11e7-8fbc-62c05c94735c.png)

### How to reproduce

* ⚛️ Start any electron app (e.g. Atom or Hyper) on Ubuntu 16.04. 
* 😃 Enjoy the menu in the title-bar of the application.
* 😴 Hibernate the workstation.
* ⏰ Wake the workstation from hibernation. 
* 😢 The title-bar-menus of all electron apps have disappeared.

**Comment by mojoaxel** [comment]
This seems to be related to #4012

**Comment by sofianguy** [comment]
Thanks for contributing!

We are no longer releasing bug fixes for versions of Electron older than 1.5. We prefer to only keep issues that are on our immediate radar.

If you are still having the same issue in an up-to-date version, feel free to reach out and we'll reopen.

**Comment by mojoaxel** [comment]
I can confirm this is still an issue e.g. with VSCode:
```
Version: 1.26.1
Commit: 493869ee8e8a846b0855873886fc79d480d342de
Datum: 2018-08-16T18:34:20.517Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architektur: x64
```

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.
