### ISSUE TITLE
Cannot output east-asia characters to windows command console

### ISSUE THREAD

**Issue by cuixiping** [electron/electron#10295]
* Electron version: until 1.7.3
* Operating system: win7, win10

### Expected behavior

Output east-asia characters correctly.

### Actual behavior

Output east-asia characters incorrectly.

### How to reproduce

app.js
```
console.log('中日韩');
```

Run `electron  .` command
![image](https://user-images.githubusercontent.com/1104492/29443762-ddb54058-840c-11e7-89b0-5f24f51fb1fa.png)

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by cuixiping** [comment]
Electron 3.0.0 still has this issue.
