### ISSUE TITLE
Screen Capture Bug - Blank browser screen in IE 11

### ISSUE THREAD

**Issue by Dilts** [electron/electron#10292]
* Electron version: 1.75
* Operating system: Windows 10

### Expected behavior
A user selects the IE browser as the screen capture source and begins recording. The recording captures all content in the browser as the user navigates around a web page or web app. 

### Actual behavior
After capturing a screen recording in IE 11, the video does not display any of the content in the IE browser except the URL and the tabs (pics below)

### How to reproduce
1. Select Internet Explorer window as the screen capture source 
2. Begin recording and navigate to a new tab
3. Open up a website and scroll to bottom of page
4. Stop recording 
5. View playback

Example of blank browser on playback:
![screen capture - blank ie window](https://user-images.githubusercontent.com/7028487/29427027-b6e16028-8345-11e7-8c60-0abb02841eae.PNG)

Example of blank browser in _capture source_ screen:
<img width="962" alt="screen shot 2017-08-17 at 12 18 26 pm" src="https://user-images.githubusercontent.com/7028487/29427167-426cb44e-8346-11e7-8a91-2c051ea4c957.png">

**Comment by jwaldrip** [comment]
@Dilts colleague here... You can use this app for reference: https://github.com/jwaldrip/electron-sample-apps/tree/master/desktop-capture you get the empty window behavior when launching in electron 1.7.5.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
