### ISSUE TITLE
showSaveDialog returns undefined fileName if it exceeds OS path limit

### ISSUE THREAD

**Issue by shirfy** [electron/electron#10299]
* Electron version: 1.6.11
* Operating system: Windows 10

### Expected behavior

- The callback function of showSaveDialog should return the fileName even if the length of the path is too long for the OS and let the developer handle it.
- Another option would be if clicking the Cancel button would return a different value than ```undefined```. For example ```null```, so I could know if an error happened or a user action, thus could save the file when needed with my fallback path.

### Actual behavior

fileName is undefined when path exceeds the Windows limit of 260 characters.
Not tested, but probably the same would happen in Linux/Mac above 4096 chars.

### How to reproduce

Use any showSaveDialog and exceed the path limit by choosing a folder and typing a long enough filename into the input and clicking the Save button. 

```
const {dialog} = require('electron');
dialog.showSaveDialog({
	title: 'Save as',
	defaultPath: path.join(app.getPath('documents'), originalFileName)},
	function (fileName) {
		console.log(fileName);
	});
});
```

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
