### ISSUE TITLE
Misaligned 2D / 3D Canvas under Windows

### ISSUE THREAD

**Issue by markusmoenig** [electron/electron#10294]
PaintSupreme3D.com uses two overlaid canvases to render it's UI, one 2D and one 3D canvas (WebGL). Some UI elements are drawn in 2D, some in 3D. These two canvases always align perfectly inside  a browser, they also always align perfectly using Electron on the Mac, but on Windows the two are shifted when not running in full screen mode. See the attached screenshot.

The two canvases are created like this:

```html
<canvas id="webgl" style="position: absolute; left: 0; top: 0; z-index: 2;">Please use a browser that supports "canvas"</canvas>
<canvas id="workspace" style="position: absolute; left: 0; top: 0; z-index: 1;">Please use a browser that supports "canvas"</canvas>
```

Short summary:

* Always works in the browser. Never saw the issue there on any of the 3 operating systems.
* Always works natively on Mac.
* Works in Windows in full screen, but in windowed mode there is the shift between the two layers.
* On Linux the 3D canvas is not shown (works in browser). But did not yet look into that too much.

I use Electron 1.7.6. You can download native versions of the app in the welcome dialog at PaintSupreme3D.com

![29420063-86133684-83a3-11e7-9a56-fa58b313186c](https://user-images.githubusercontent.com/10293923/29439501-324cea14-83e8-11e7-927a-89e810815f0b.jpg)

In fullscreen all is good

![29420077-90a5f4ce-83a3-11e7-9eb6-c10b68f452c7](https://user-images.githubusercontent.com/10293923/29439934-5cfeaa74-83eb-11e7-8fed-c468f01339aa.jpg)

**Comment by enlight** [comment]
Please fork https://github.com/electron/electron-quick-start and reproduce the issue there.

**Comment by markusmoenig** [comment]
That's a major task ... . Setting up synced painting for 2D and 3D canvas layers is not something trivial. Is it not possible to output some specific debug output from the DOM ?

**Comment by markusmoenig** [comment]
What more information can I provide ?

**Comment by enlight** [comment]
I see the same issue when loading https://www.paintsupreme3d.com/ in Firefox 55, and Chrome 60 on Windows. In Firefox if the site is loaded in windowed mode the boxes are misaligned, switching to full screen fixes the alignment. In Chrome everything looks fine when I initially load the site in windowed mode, but switching to full screen and back breaks the alignment. If your Electron app is built from the same code as your web app then I would posit there is a bug in your code, or the browsers.

**Comment by markusmoenig** [comment]
Thanks for the feedback. Strange, I do not see this behavior inside the browsers on my Windows 10 computer. Will test more. But at least this shows that this is not an Electron issue but something else... .

**Comment by markusmoenig** [comment]
I have to apologize, this was my bug. You can close this. Sorry again.
