### ISSUE TITLE
Should C++ Redistributable dlls in Electron 1.7 be packaged with the application?

### ISSUE THREAD

**Issue by Tyriar** [electron/electron#10291]
Since 1.7 there are a bunch of new dlls in node_modules/electron/dist which look like the C++ Redistributable VS 2015 dlls. Should these be included with packaged applications? If so, are there any links/context to why this change was made?

Repro:

```
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start
npm install
# Notice node_modules\electron\dist does not contain the dlls as
# electron-quick-start uses 1.6

# Change the electron dependency to 1.7.6
npm i -g rimraf
rimraf node_modules
npm i
# node_modules\electron\dist now contains additional dlls
```

dlls in question:

```
api-ms-*.dll
msvcp140.dll
vcruntime140.dll
```

![image](https://user-images.githubusercontent.com/2193314/29423819-08c42bf0-8332-11e7-808c-be123c193920.png)

**Comment by enlight** [comment]
As of Electron 1.7.4 the CRT is dynamically linked once again, all those extra dlls are part of the UCRT infrastructure. You can find the reasons for the switch in #9443.

**Comment by Tyriar** [comment]
Thanks for the link 😃

**Comment by miniak** [comment]
The UCRT DLLs are "only" required for Windows 7 and 8. It became a system component in Windows 10.
