### ISSUE TITLE
Electron crashes and dev tools break when using `npm start` instead of `electron .`.

### ISSUE THREAD

**Issue by Miroware8** [electron/electron#10302]
* Electron version: 1.7.6
* Operating system: Windows 8.1

### Expected behavior
Electron shouldn't randomly crash and opening the dev tools should not break the application, whether you use `npm start` or `electron .`.

### Actual behavior
30-90 seconds after running my application with `npm start` (which is just an alias of `electron .`), Electron will crash, whether the window is interacted with or not. Opening the dev tools before the crash will make the page blank and disconnect the dev tools immediately, but it does not seem to affect the amount of time before the crash. This behavior, other than the amount of time it takes to crash, is very consistent. When directly using `electron .` to launch the program, this issue will never occur.
This is what it looks like after the crash whether or not dev tools are opened.
![image](https://user-images.githubusercontent.com/14056899/29473339-755764b4-8425-11e7-834c-d69e06c04c7c.png)
This is what it looks like when the dev tools are opened at any time.
![image](https://user-images.githubusercontent.com/14056899/29473209-ed61ce82-8424-11e7-91bd-157b75137762.png)

### How to reproduce
Clone [my repository](https://github.com/Miroware8/miroware-dynamic) (which I may or may not have set up correctly), run `npm start` in its directory, and wait 30-90 seconds after the splash screen disappears. I set up the rendering script so that pressing `ctrl`+`shift`+`I` will open the dev tools on the main window. My `npm-debug.log` file from after the crash is in the repository.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by Miroware8** [comment]
This isn't a question. It's a bug report.

**Comment by sofianguy** [comment]
@Miroware8 My bad, reopening. Your link to your repo is showing a 404 error. Can you fix that for us please? :)

**Comment by xloem** [comment]
I'm having this issue.

I find that if I `npm install --save debug` it causes it reliably.

**Comment by xloem** [comment]
This turned out to be #11234 for me.

**Comment by codebytere** [comment]
Closing as @xloem you seem to have resolved.
