### ISSUE TITLE
will-prevent-unload seems to cancel requests prematurely

### ISSUE THREAD

**Issue by feens** [electron/electron#10300]
It appears that when `will-prevent-unload` is called, it causes all requests to be cancelled, even if a later event handler will override the event and cancel it.  For example, in our app we use an event handler to pop up a dialog that allows a user to either stay on the page or leave the page.  The problem is that even if they choose to stay on the page there is the potential for errors due to cancelled requests.

* Electron version:
1.7.5

* Operating system:
macOS (10.12.6)

### Expected behavior
Requests should not be cancelled until after the event completes

### Actual behavior
Requests are being cancelled as soon as the event is fired

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
