### ISSUE TITLE
Electron demo app for Windows uses Linux syntax

### ISSUE THREAD

**Issue by mikemaccana** [electron/electron#10301]
The commands give in Electron API Demo don't work on Windows:

![image](https://user-images.githubusercontent.com/172594/29465198-5dc8d78c-8430-11e7-9bee-5c8fbad2aa3f.png)

Simply:

    npm install && npm start

Should be:

    (npm install) -and (npm start)

Or

    npm install
    npm start

**Comment by enlight** [comment]
That syntax works just fine in the plain old `cmd` shell on Windows, you appear to be using `PowerShell`.

**Comment by mikemaccana** [comment]
@enlight This commands fails in plain Powershell, you appear to be using the old cmd (seriously Powershell is the current default shell on Windows)
