### ISSUE TITLE
Custom protocol + Origin headers/request crashes BrowserWindow/Webview

### ISSUE THREAD

**Issue by joshuef** [electron/electron#10314]
* Electron version: 1.7.5
* Operating system: macOS (10.12.6)

### Expected behavior

A page loaded over a custom protocol should receive http responses without error, webview/Browser window should not crash.

### Actual behavior

Browser window/webview crashes when `Access-Control-Allow-Origin` headers are received on a response and it matches the site on a custom protocol (eg `custom://site:8888` loads and makes the request).

### How to reproduce

You can pull the example repo: https://github.com/joshuef/electron-custom-protocol-origin-fail-example. Similarly pull and build [the boilerplate to test against](https://github.com/alicoding/react-webpack-babel):

* `git clone git@github.com:joshuef/electron-custom-protocol-origin-fail-example.git`
* `cd electron-custom-protocol-origin-fail-example`
* `yarn`

In another folder:

* `git clone https://github.com/alicoding/react-webpack-babel.git`
* `cd react-webpack-babel`
* `yarn`
* `yarn dev`

Once this is running, in the example app folder: `yarn start`

----
Running the boilerplate dev server (`yarn dev` after installing), and then the example repo will crash the browser window.

Deleting the `Origin` header kills the request (or the `Allow-Access-Control-Origin` headers).

The same request not using the `custom:` protocol to `localhost` in the app works fine...

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
