### ISSUE TITLE
Window with width > screen resolution doesn't extend on second screen

### ISSUE THREAD

**Issue by iUltimateLP** [electron/electron#10313]
* Electron version: 1.6.12
* Operating system: Windows 10 Pro x64

### Expected behavior
If the window is located on the first screen, and I set it a width which is bigger than the resolution of the first screen, it should extend on the second screen, like if you manually drag it bigger (which works)

### Actual behavior
It just keeps on the first screen, so it is similar like maxWidth = first screen resolution.

### How to reproduce
Create a new browser window like this: 
```js
let mainWindow = new BrowserWindow({x: 0, y: 0, width: 3840, height: 1080});
  
```

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by d3x0r** [comment]
Still fails.
