### ISSUE TITLE
electron.remote doesn't handle custom Error objects in all cases

### ISSUE THREAD

**Issue by tom-seddon** [electron/electron#10316]
* Electron version:  1.7.5
* Operating system: Windows 10 Version 1607

### Expected behavior

Custom Error objects are handled the same way in all cases.

### Actual behavior

Custom Error objects are not received correctly when thrown.

### How to reproduce

Clone repo and run app.

```
git clone https://github.com/tom-seddon/electron-remote-exception
npm install
npm start

```
There are three buttons in the app. Each one uses `electron.remote` to call a function in the main process that creates a custom Error object, with some new fields on it, and does something with it. Then once the render process receives that object, it prints it to the debug console.

`Return Exception`: Main process function creates custom Error object and returns it. Note the properties shown on the debug console: short message, plus custom `type` and `code` fields.

`Throw Exception`. Main process function creates custom Error object and throws it. Note that once it gets back to the render process, the message has had a bunch of stuff added to it, and the custom fields are gone.

`Reject Promise`: Main process creates custom Error object and rejects a promise with it. Note that the properties shown on the debug console are correct, as in the `Return Exception` case: short message, plus custom `type` and `code` fields.

### Other Notes

* you can also see this when throwing strings and stuff - however my main concern here is getting some extra info to the render process via these custom fields
* my actual project has a C++ addon, which is why there's code that has to run in the main process

Thanks,

--Tom

**Comment by tom-seddon** [comment]
Also happens on Mac OS X 10.12.6 (16G29).

**Comment by tom-seddon** [comment]
Also happens on Linux (tested Ubuntu 16.04 LTS; `uname -a` = `Linux ourolinux 4.4.0-91-generic #114-Ubuntu SMP Tue Aug 8 11:56:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`)

**Comment by MarshallOfSound** [comment]
> my actual project has a C++ addon, which is why there's code that has to run in the main process

FYI you can use native addons in the renderer process 😄 

In terms of your actual issue, can you please provide a minimal reproduction sample.  Just something based on `electron-quick-start` that demonstrates your issue clearly will make it significantly easier for us to look into this

**Comment by tom-seddon** [comment]
Interesting, thanks - I will investigate. That might save a bit of bother...

As for the repro - not really sure what else I can strip out from the one I've provided, but I'm open to suggestions.

Thanks,

--Tom

**Comment by MarshallOfSound** [comment]
@tom-seddon My bad 😆 Missed the repro in the notification (normally just scan through for links not code blocks).  Repro looks fine 👍

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
