### ISSUE TITLE
Windows 7 notifications display next to app rather than on primary display

### ISSUE THREAD

**Issue by mgc** [electron/electron#10317]
Since switching to the new Windows 7 notification system quite a few Slack users have written in to say that they'd prefer notifications show on their primary monitor. Presumably this will be the case for all other Electron based communication apps? Should we make this the default behavior, or add an option?

* Electron version: 1.6+
* Operating system: Windows 7

### Expected behavior
Windows 7 notifications should appear on the primary display

### Actual behavior
Notifications appear on whichever display is showing the Electron app

### How to reproduce
1. Connect Windows 7 machine to multiple monitors in extend mode
2. Position Electron app on secondary display
3. Trigger notification and notice it appears on secondary rather than main monitor

**Comment by mgc** [comment]
@alespergl thoughts?

**Comment by alespergl** [comment]
That behavior is certainly unexpected. The toasts should always pop up on the primary monitor. I will try to reproduce it.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
