### ISSUE TITLE
Can't seem to disable auxclick

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#10315]
* Electron version: 1.6.11
* Operating system: Windows 10

### Expected behavior
I create a window with these options: `webPreferences: { disableBlinkFeatures: "Auxclick" }`.
I point the window to an html page that has a link: `<a href="http://www.google.com">GOOGLE</a>`, and I expect middle clicking to not open up a new window.

### Actual behavior
Middle clicking opens a new window.

Am I just not understanding what disabling auxclick does? Does disabling it also disable middle click in the hosted webapp? I couldn't confirm that either - see more details [here](https://stackoverflow.com/questions/45804455/disabling-auxclick-in-electron-does-not-appear-to-work).

**Comment by pushkin-** [comment]
Any updates?

**Comment by jcrowthe** [comment]
I am also experiencing this issue.

- Electron version 1.7.9
- Operating System: MacOS

Considering it is a way in which end users can break out of a sandbox, I would consider this a security issue. Can we get a security flag attached to this ticket as well?

**Comment by pushkin-** [comment]
The list of features that we can disable can be found [here](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/platform/runtime_enabled_features.json5?l=70), and there are no references to `auxclick`.

Looking through the commit history, it appears that the auxclick flag was removed on September 15, 2017. Commit message: "Input: Retire runtime flag fox auxclick. Support for auxclick shipped to stable in Chrome 55. The runtime flag is no longer needed. BUG=[625847](https://bugs.chromium.org/p/chromium/issues/detail?id=625847)"

This change was committed about a month after I opened the issue, so I guess there's still a bug somewhere, but this issue may no longer be relevant. However, it raises the question, "how can I disable auxclick now?" There is still a security vulnerability, right?

**Comment by ikkisoft** [comment]
Using `disableBlinkFeatures: "Auxclick"` will simply turn 'auxclick' events into regular 'click' events. 

You can verify that by using the following commands in the developer console while clicking/middle-clicking: 
```
monitorEvents(document,"click");
monitorEvents(document,"auxclick");
```

To block the navigation, you would need to use something like:

```
window.addEventListener('click', handleLinkClick);

handleLinkClick (event) {
	event.preventDefault();
}
```

Btw, the latest stable Electron release (v2.0.1) uses Chromium 61.0.3163.100 which does include the _Auxclick_ flag. See https://chromium.googlesource.com/chromium/src.git/+/61.0.3163.100/third_party/WebKit/Source/platform/RuntimeEnabledFeatures.json5

**Comment by ikkisoft** [comment]
To block you would need to use one of the following:

```
window.addEventListener('click', handleLinkClick);

handleLinkClick (event) {
	event.preventDefault();
}
```

```
 win.webContents.on('will-navigate', event => {
    event.preventDefault()
  })

 win.webContents.on('new-window'', event => {
    event.preventDefault()
  })
```

**Comment by pushkin-** [comment]
@ikkisoft But that will block *all* click events, which is not necessarily what I want. I want to `*just* block middle-clicking. I guess in that case I must latch on to the `auxclick` event and `preventDefault()` that rather than using `disableBlinkFeatures`, right?

**Comment by ikkisoft** [comment]
You can use `disableBlinkFeatures: "Auxclick"` and then 
```
 win.webContents.on('new-window'', event => {
    event.preventDefault()
  })
``` 
to block middle-clicking (since the event is 'new-window')

**Comment by freddy-daniel** [comment]
Why event.preventDefault() on 'new-window' 
It's Monday, 23 September 2019 still there's no feasible solution
Now electron v6.0.10 is there any solution

**Comment by patil-milind** [comment]
This event seem Deprecated in the latest Electron version 12.0.0 
```
win.webContents.on('new-window'', event => {
    event.preventDefault()
  })
```
Instead of this used new handlaer
```
win.webContents.setWindowOpenHandler(() => {
            return { action: 'deny' };
     });
```
This event is not getting triggered when clicking Mouse mid click button, still the new windows getting created.  Also used the 
`disableBlinkFeatures: "Auxclick"` in `WebPreferences` but this was also got removed. any suggestion ?
@ikkisoft

**Comment by ikkisoft** [comment]
hey @patil-milind - take a look at https://github.com/electron/electron/issues/27967#issuecomment-812238301

**Comment by rmckeel** [comment]
I had a similar issue, and instead of preventing new windows from opening (way too broad IMO), I modified my app (in this case Angular) to reject all middle clicks on the document.  No other changes (such as remapping a middle click to a normal click) were necessary.  Hope that helps someone!

```
/**
  * App-wide squelch of middle-click mouse events; otherwise,
  * app opens a new browser window on middle click.
  */
@HostListener("document:auxclick", ["$event"])
  onAuxClick(e: MouseEvent) {
    // @help https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button
    if (1 === e.button) {
      e.preventDefault();
    }
  }
```
