### ISSUE TITLE
Installation on linux failed

### ISSUE THREAD

**Issue by NervenCid** [electron/electron#10319]
* Electron version: 

1.7.5

* Operating system:

Linux Raspbian
ARM v7

### Expected behavior

Install electron

### Actual behavior

I got this error:

> electron@1.7.5 postinstall /usr/lib/node_modules/electron
> node install.js

/usr/lib/node_modules/electron/install.js:48
  throw err
  ^

Error: read ECONNRESET
    at _errnoException (util.js:1041:11)
    at TLSWrap.onread (net.js:606:25)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.7.5 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.7.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

### How to reproduce

sudo npm install -g electron

**Comment by MarshallOfSound** [comment]
Please check out the relevant section of the FAQ 😄 

https://github.com/electron/electron/blob/master/docs/faq.md#why-am-i-having-trouble-installing-electron
