### ISSUE TITLE
python script\bootstrap.py -v  not working

### ISSUE THREAD

**Issue by pravash-upreti** [electron/electron#10320]
I found this errror

fatal: cannot create directory at 'deps/npm/node_modules/libnpx/node_modules/yargs/node_modules/cliui/node_modules/string-width/node_modules/is-fullwidth-code-point/node_modules/number-is-nan': No such file or directory

**Comment by codebytere** [comment]
Delete everything and start fresh, if it's still an issue let us know. We'll also need more info to diagnose this: Electron version and operating system.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
