### ISSUE TITLE
Gamepad disconnection event is not triggered

### ISSUE THREAD

**Issue by gamelaster** [electron/electron#10327]
* Electron version: Electron 1.7.5
* Operating system: Windows 10 x64

### Expected behavior

On connect, it trigger `gamepadconnected` event, on disconnect trigger `gamepaddisconnected`

### Actual behavior

On connect it's triggering `gamepadconnected` event, but on disconnect it's triggering again `gamepadconnected`

### How to reproduce

```js
window.addEventListener("gamepadconnected", function(e) {
  console.log("Gamepad connected at index %d: %s. %d buttons, %d axes.",
    e.gamepad.index, e.gamepad.id,
    e.gamepad.buttons.length, e.gamepad.axes.length);
});

window.addEventListener("gamepaddisconnected", function(e) {
  console.log("Gamepad disconnected from index %d: %s",
    e.gamepad.index, e.gamepad.id);
});
```
![2017-08-22_17-42-38](https://user-images.githubusercontent.com/1665373/29574252-563a7762-8761-11e7-8e5b-0df1b1d8f38d.gif)

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
