### ISSUE TITLE
Internal size of BrowserWindow does not correspond to size on screen

### ISSUE THREAD

**Issue by VioletRose** [electron/electron#10329]
* Electron version: 1.7.5
* Operating system: Linux/Xubuntu 16.04 & Windows 10

### Expected behavior

Instantiating a new `BrowserWindow` using the `width` and `height` properties in its options should create a browser window of the specified size, to enable logic such as detecting the size of the work area and not letting the window's size exceed it.

### Actual behavior

Instantiating a new `BrowserWindow` using the `width` and `height` properties in its options creates a browser window which is close to that size, but wrong by several px in a manner which depends on the operating system. With my example app, which specifies a `width` of 600 and `height` of 800, I observe the following: in Linux/Xubuntu 16.04, the actual window size comes to 602 wide and 825 high, which corresponds to the size of the window + borders and title bar. In Windows 10, the resulting browser window is _smaller_ than the specified values, at 596 wide and 798 high.

My example app also demonstrates, using the `getBounds()` and `getSize()` methods of `BrowserWindow`, that this is not a result of the values being adjusted, but that Electron internally believes the window to be the specified size, even though it's not.

### How to reproduce

I have created this example app which reliably reproduces the issue on my system; instructions on how to use it are provided in the readme.
https://github.com/VioletRose/electron-size-checker
In addition, please see the attached screenshots, in particular their image dimensions.
![electron size checker - linux xubuntu 16 04](https://user-images.githubusercontent.com/19483288/29580820-336ab27c-872c-11e7-8c2f-d0dcce67c698.png)
![electron size checker - windows 10](https://user-images.githubusercontent.com/19483288/29580870-587208e0-872c-11e7-93ab-28d589ff63f6.png)

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
