### ISSUE TITLE
Setting / Retrieving Document State

### ISSUE THREAD

**Issue by markusmoenig** [electron/electron#10322]
I need to set the edited state of a document so that I can show a dialog on an close event. Under Mac I can use BrowserWindow.setDocumentEdited(), but it seems this is not implemented on Windows ?

For me, isDocumentEdited() always returns false under Windows. 

Even if setDocumentEdited() actually does not something visually under Windows, should it not at least store the state ? If not, how to store the state under Windows ?

**Comment by MarshallOfSound** [comment]
The `setDocumentEdited` API is purely for displaying the file icon on macOS.  Windows does have a similar concept, if you want to prompt your user to save the file if they've made changes you will have to implement it yourself in the `close` event and your own stored boolean somewhere

**Comment by markusmoenig** [comment]
If it is purely for displaying the file icon, why does isDocumentEdited() exist ? The naming of these functions give you the impression that this is a valid solution for storing the document state.

**Comment by MarshallOfSound** [comment]
@markusmoenig They directly map to the native API's

https://developer.apple.com/documentation/appkit/nswindowcontroller/1534261-setdocumentedited?language=objc
https://developer.apple.com/documentation/appkit/nsdocument/1515091-isdocumentedited

It is documented that these two methods are only supported on macOS https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winsetdocumenteditededited-macos

**Comment by markusmoenig** [comment]
Ok ok. Thanks for the links.

Is there an official way to store a value inside a BrowserWindow ? Or just do something like window.docState = true ? No idea where to store this correctly.

**Comment by MarshallOfSound** [comment]
@markusmoenig Each window has an ID, you can use that to map information.  Vaguely something like this would work

```js
const window = new BrowserWindow();
const dataStore = {}
dataStore[window.id] = { edited: false }
```

**Comment by markusmoenig** [comment]
Ok, that would work, thanks a lot.

**Comment by teddy-mczieuwa** [comment]
```
const window = new BrowserWindow();
const dataStore = {}
dataStore[window.id] = { edited: false }
```
@MarshallOfSound This looks promising, but I am confused as to which is the best way to access the dataStore object on the renderer process. would i have to use ipc or is there another way?

**Comment by teddy-mczieuwa** [comment]
So I did this and it works fine for me. Would it give me any issues?

```
let newWindow = new BrowserWindow({
    minWidth: 800, minHeight: 600, show: false,
    backgroundColor:'#ccc', additionalArguments:'edited'
  })

  Object.defineProperty(newWindow, 'documentEdited', {
    value:false,
    configurable:true,
    enumerable:true,
    writable:true

  })
```
