### ISSUE TITLE
Problems running bootstrap.py on Windows

### ISSUE THREAD

**Issue by Tyriar** [electron/electron#10337]
I'm trying to build Electron on Windows to investigate https://github.com/electron/electron/issues/10188 but I'm running into a problem in bootstrap.py. Here's the error:

```
>python script\bootstrap.py -v
...
Downloading libchromiumcontent-static.zip...
https://s3.amazonaws.com/github-janky-artifacts/libchromiumcontent/win/x64/349396d62b4dece64c95727e2bbfb20dda987241/libchromiumcontent-static.zip
...................................................................................................................................................................
...................................................................................................................................................................
...................................................................................................................................................................
...................................................................................................................................................................
...................................................................................................................................................................
...................................................................................................................................................................
...................................................................................................................................................................
...................................................................................................................................................................
...................................................................................................................................................................
...................................................................................................................................................................
...................................................................................................................................................................
.................................
Extracting...
C:\Python27\python.exe C:\Users\daimms.REDMOND\Documents\dev\forks\electron\script\update.py
gyp: vendor\node\deps\zlib\zlib.gyp not found (cwd: C:\Users\daimms.REDMOND\Documents\dev\forks\electron)
ggyp: vendor\node\deps\uv\uv.gyp not found (cwd: C:\Users\daimms.REDMOND\Documents\dev\forks\electron)
yp: vendor\node\node.gyp not found (cwd: C:\Users\daimms.REDMOND\Documents\dev\forks\electron)
None
Traceback (most recent call last):
  File "script\bootstrap.py", line 261, in <module>
    sys.exit(main())
  File "script\bootstrap.py", line 65, in main
    run_update(defines, args.msvs)
  File "script\bootstrap.py", line 238, in run_update
    execute_stdout(args)
  File "C:\Users\daimms.REDMOND\Documents\dev\forks\electron\script\lib\util.py", line 184, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'C:\\Users\\daimms.REDMOND\\Documents\\dev\\forks\\electron\\script\\update.py']' returned non
-zero exit status 1
```

I believe I have all the [prerequisites](https://electron.atom.io/docs/development/build-instructions-windows/#prerequisites) installed:

- Windows 10 version 1703, OS build 15063.540
- Visual Studio Professional 2015 Update 3
  ![image](https://user-images.githubusercontent.com/2193314/29630311-a1cec5d6-87f0-11e7-8524-93432d6d3831.png)
- Python 2.7.13
- Node.js 7.9.0
- Git 2.13.2.windows.1

**Comment by bpasero** [comment]
@Tyriar I just tried the build instructions and it went smooth on my Win10 box. However, I remember seeing issues like that previously where the bootstrap was not finishing correctly. 

My setup:
* Python 2.7
* node.js 6.9.4
* Windows 10 version 1703 OS build 15063.540)
* Visual Studio Community Edition 2015 Update 3 (same version as you)

**Comment by bpasero** [comment]
One downside of https://github.com/electron/electron/issues/10188 is that I cannot reproduce from the debug version, only the release version...

**Comment by jcgalindo** [comment]
Same issue here. Same prerequisites.

**Comment by taha** [comment]
I'm getting a very similar error while trying to build Electron on a Windows Server 2012 R2 Standard vagrant VM (VirtualBox).

- Python 2.7.2
- Node.js 7.9.0
- Windows Server 2012 R2 Standard
- Visual Studio Community Edition 2015 Update 3

```
c:\Python27\python.exe C:\vagrant\electron\script\update.py
Traceback (most recent call last):
  File "tools/list-browserify-deps.py", line 15, in <module>
    dep = os.path.relpath(dep, SOURCE_ROOT)
  File "c:\Python27\lib\ntpath.py", line 505, in relpath
    % (path, start))
ValueError: Cannot mix UNC and non-UNC paths (\\vboxsrv\vagrant\electron\node_modules\events\events.js and )
gyp: Call to 'python tools/list-browserify-deps.py ./lib/sandboxed_renderer/init.js -r ./lib/sandboxed_renderer/api/exports/electron.js:electron -r ./lib/sandboxed_renderer/api/exports/fs.js:fs -r ./lib/sandboxed_renderer/api/exports/os.js:os -r ./lib/sandboxed_renderer/a
pi/exports/path.js:path -r ./lib/sandboxed_renderer/api/exports/child_process.js:child_process' returned exit status 1 while in electron.gyp.
None
Traceback (most recent call last):
  File "script\bootstrap.py", line 261, in <module>
    sys.exit(main())
  File "script\bootstrap.py", line 65, in main
    run_update(defines, args.msvs)
  File "script\bootstrap.py", line 238, in run_update
    execute_stdout(args)
  File "C:\vagrant\electron\script\lib\util.py", line 184, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['c:\\Python27\\python.exe', 'C:\\vagrant\\electron\\script\\update.py']' returned non-zero exit status 1
```

**Comment by DiegoBM** [comment]
Same issues here

**Comment by DiegoBM** [comment]
Anything on this anyone? Completely unable to build electron on windows

**Comment by taha** [comment]
@DiegoBM @jcgalindo I had this issue a couple of days ago on Windows, and the issue was actually to do with crazy long filenames which `git config --system core.longpaths true` fixed for me. Make sure to delete all previously created files from failed bootstrap attempts.

Hope this helps!

**Comment by DiegoBM** [comment]
Thank you @taha, it was worth the shot, but unfortunately in this case it seems to be something else. I tried what you suggested but I keep getting the same result

**Comment by taha** [comment]
@DiegoBM can you post your full error here? Possibly the full log till the error happened.

**Comment by DiegoBM** [comment]
[log.txt](https://github.com/electron/electron/files/1295260/log.txt)
By all means, this is the second attempt to build, but I deleted the whole built and run both clean commands before trying your fix

**Comment by taha** [comment]
Can you attempt bootstraping from a fresh clone of the repo? And possibly post the log here as well.

Running the clean commands doesn't actually clear out the git submodules synced at the beginning of bootstrap.py script. The error your getting is most likely due to something that went wrong during the process of syncing the git submodules, since the files that are missing are in fact in the electron/node repo. The fact that they're missing means that an error stopped git from finishing the update/sync process of the node submodule.

**Comment by DiegoBM** [comment]
You were absolutely correct @taha, it worked flawlessly on a fresh new clone, after applying your suggestion. You are the man!

P.S: Sorry for the delay to reply, it took a good chunk of time to bootstrap twice (like with zombies, always double check) and confirm successful build
