### ISSUE TITLE
Crash on large amounts of a particular Unicode character

### ISSUE THREAD

**Issue by PointyDev** [electron/electron#10332]
* Electron version: 1.6.12
* Chromium version: 56.0.2924.87
* Node version: 7.4.0
* v8 version: 5.6.326
* Operating system: Windows 10 Pro x64 v1607

### Expected behavior
App is stable.

### Actual behavior
App becomes unresponsive.

### How to reproduce
1. Run an electron instance (I used QS)
2. Open dev tools
3. Paste 1000+ of the following character into any part of the DOM:
```
'BENGALI VOWEL SIGN VOCALIC LL' (U+09E3) 
ৣ 
```
4. Client becomes unresponsive, see the following gif

![Example](http://i.imgur.com/nRXJBVS.gif)

Mainly wanted to post this here for tracking purposes, please see the post on the chromium monorail here: https://bugs.chromium.org/p/chromium/issues/detail?id=757446

**Comment by PointyDev** [comment]
It seems this may have been fixed in a recent chromium build, see here: https://bugs.chromium.org/p/chromium/issues/detail?id=757446#c21

**Comment by PointyDev** [comment]
@sofianguy Fixed or inactive issue? Would like to forward this to [Discord](https://discordapp.com) so they can upgrade Electron if fixed.

**Comment by sofianguy** [comment]
@PointyDev No, this is not fixed in Electron yet. My bad, reopening.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
