### ISSUE TITLE
Request: API "PdfToEmfConversion" OR "print to emf" feature

### ISSUE THREAD

**Issue by xioxin** [electron/electron#10338]
In Windows there is no way to directly print PDF files,
Need to convert PDF to EMF,
This method has been implemented in "contents.print"

Translate from "google translate"

> original:
> 在Windows下没有办法直接打印PDF文件,
> PDF需要转换为EMF,
> 在contents.print中已经实现了这个方法

**Comment by setpixel** [comment]
This doesn't seem appropriate for electron to expose. I think what you are really meaning is that printing is incredibly frustrating in electron and you'd love a native way of printing pdfs from within electron. +1 👍

**Comment by miniak** [comment]
EMF is a proprietary Windows technology. There might be a 3rd party native node module available providing this functionality. This should definitely be supported in Electron core.
