### ISSUE TITLE
Pointer Events not Working

### ISSUE THREAD

**Issue by markusmoenig** [electron/electron#10339]
Electron Version: 1.7.6
Windows 10, Microsoft Surface Laptop

Pointer events for pressure sensitivity on the surface laptop works fine inside the chrome browser.

However building the app with electron v1.7.6 and enabling pointer events via 

app.commandLine.appendSwitch('--enable-pointer-events');

does not work inside the electron app. I.e. no pressure sensitivity is working.

You can download the Windows version at www.paintsupreme3d.com.

**Comment by markusmoenig** [comment]
More specifically: There is an existing window.PointerEvent object, which normally means that pointer events are setup and working.

However the "pointerdown" and "pointermove" events pressure member is always either 0 or 0.5, nothing in between. The same code is running fine inside the browsers and also works in the electron Mac version.

**Comment by setpixel** [comment]
It's not an electron problem. It's a chromium problem. Chromium 59 fixes
this.

**Comment by markusmoenig** [comment]
Ok, but does not make a huge difference when you have customers screaming at you and you cannot supply a fix ... .

**Comment by markusmoenig** [comment]
Also, did I not read somewhere that Electron will be updated about two weeks after new Chromium versions are available ?

**Comment by setpixel** [comment]
hah - dude - ive been waiting MONTHS for this to be fixed. I lobbied hard to get it fixed in chromium. BUT GOOD NEWS - the 1.8 release that includes chromium 59 is likely to be released this week.

my project is kinda related to yours: https://github.com/wonderunit/storyboarder

**Comment by markusmoenig** [comment]
Thanks for your efforts! :)

v1.8 sounds like great news, as we are about to be able to release PS3D to the AppStores.

Also your project is very cool. Proofs that HTML5 multimedia apps are getting more and more common which is great. Kudos to you and your team!

**Comment by markusmoenig** [comment]
@setpixel Do you have any new info when 1.8 will be released ? Cannot find any info anywhere.

**Comment by setpixel** [comment]
I just know from chatting with the maintainers in issues and their pull requests. You can post an issue asking about it.

**Comment by sofianguy** [comment]
@markusmoenig https://github.com/electron/electron/releases/tag/v1.8.0

**Comment by setpixel** [comment]
I can confirm it works!

**Comment by markusmoenig** [comment]
Mmhh, for me on my Surface Laptop I can get 2-3 brush strokes in, after that the pen input is completely dead and only works again after a restart of the app.

The same app version running inside chrome always works with the pen.

**Comment by markusmoenig** [comment]
I will report this as a v1.8 as a new issue.

**Comment by setpixel** [comment]
what does the pointer event look like before and after it stops working?

**Comment by markusmoenig** [comment]
Correction. After 2-3 brush strokes only the "normal" mouse events are not send anymore for the pen input, the pointer events still arrive.

However as I only read out the pressure information from the pointer events and use the other data from the normal mouse events, my app stops working for the pen.

What is the standard behavior here ? In the browser, the normal mouse events always continue to be send for pressure sensitive hardware (and don't stop) ?

**Comment by setpixel** [comment]
i'd have to see your code. are you listening for the pointermove event?

**Comment by markusmoenig** [comment]
Yes, and that always comes in correctly.

My problem is that the normal mouse events like document.onmousemove, document.onmouseup stop working. And as my app reads the mouse state (apart from the pressure) from there, the painting stops working.

So the question is, is this a bug in Electron or is that normal behavior ? For me, in the browser, I always get both, pointer events and the "normal" mouse events.
