### ISSUE TITLE
Press publish on 1.8 draft release 

### ISSUE THREAD

**Issue by setpixel** [electron/electron#10330]
Even though I can't see it, I know it's probably there just waiting to be published. 😃 👍 🎉

**Comment by zeke** [comment]
@setpixel it's not ready. That draft is created whenever we kick off CI builds. We are working out some CI issues on libchromiumcontent and are tenatively planning to try a 1.8.0 beta release tomorrow.

**Comment by setpixel** [comment]
I noticed that the release branch was deleted. Is there a plan to delay the 1.8 release?
