### ISSUE TITLE
minimized Electron window shows up on top of another full screen window when un-minimized

### ISSUE THREAD

**Issue by fancyydk** [electron/electron#10347]
* Electron version: 1.6.12
* Operating system: macOS 10.12.6

### Expected behavior

A minimized Electron app sitting in the dock should show up in a non-full-screen space when un-minimized.

### Actual behavior

A minimized Electron app sitting in the dock launches into a full-screen space on top of another full-screen app (e.g. Chrome below) and it cannot be moved around. A full-screen app should be the only instance in its own full-screen space. An Electron app brought back to a space should go into a non-full-screen space.
![image](https://user-images.githubusercontent.com/12807659/29688772-b0c75b26-88d5-11e7-8298-dee38d158761.png)

### How to reproduce

1. Clone the following repository and run the sample Electron app.
  $ git clone https://github.com/fancyydk/electron-quick-start.git -b dokang/bug/macos-unminimize-to-fullscreen
  $ npm install
  $ npm start || electron .

2. Maximize an app (e.g. Chrome) to full screen so it launches into its own space.
![image](https://user-images.githubusercontent.com/12807659/29688588-214e3c44-88d5-11e7-92af-54c3f1e91930.png)

3. Go back to the Electron app and click the "Restart in 5 seconds" button.
![image](https://user-images.githubusercontent.com/12807659/29688612-36a36af6-88d5-11e7-8ef8-1c3b1fdbfc85.png)

4. Before the app restarts, quickly switch to the full-screen space.

5. Wait at least five seconds until the Electron app relaunches and becomes minimized into the dock.

6. Click the Electron app icon in the dock to bring it back and it should launch into the full-screen space instead of the space its previous instance was in.
![image](https://user-images.githubusercontent.com/12807659/29688772-b0c75b26-88d5-11e7-8298-dee38d158761.png)

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
