### ISSUE TITLE
Reading file with utf8 chars in filename kills electron

### ISSUE THREAD

**Issue by arj03** [electron/electron#10346]
In a electron app I'm reading files using <input type=file> and the change signal. I get the file using         ev.target.files[0] and then read the contents of the file with FileReader readasArrayBuffer. This works fine with normal files, but if I use a file with danish characters (æøå) then electron stops working. No exception or error handler is called, the process just dies. I tried printing the file object and in electron 1.6 the name and filename was blank, but lastmodified was there. In 1.7 I can see the correct path + name, but the error persists. If I go to a shell and do a ls the filenames are all ??.jpg, but in thunar file manager I can see the filename just fine.

This is node 8.2.1 and linux.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
