### ISSUE TITLE
Support for limit-fps

### ISSUE THREAD

**Issue by jhovgaard** [electron/electron#10342]
* Electron version: 1.7.5
* Operating system: Windows 10

I'm trying to use the `limit-fps` flag like this:
`app.commandLine.appendSwitch('limit-fps', 30);`

Switch flag found here: https://peter.sh/experiments/chromium-command-line-switches/#limit-fps

The FPS stays at 60. 

It looks like the flag is quite new, so if it's not already possible to limit FPS, when is is the next Chromium update planned?

Best,
Jonas

**Comment by deepak1556** [comment]
The switch was landed in chrome 61.0.3153.0. You need to wait for chrome 61 upgrade in Electron. Thanks!

**Comment by jhovgaard** [comment]
Ahh, I'll look forward to that. Thank you!

**Comment by JerryGreen** [comment]
I would actually like to be able to set higher values than `60fps`. There are 120hz and 144hz monitors that can actually display more than 60fps, and give a feeling of even smoother movement. Too bad Electron limits that to 60fps max

**Comment by josteph** [comment]
> Too bad Electron limits that to 60fps max

@JerryGreen May I know about the resource that says about this? Thanks

**Comment by masrourmouad** [comment]
use electron 9.4.4 will work

**Comment by jjppof** [comment]
electron 9.4.4 is not working... Am I missing something?
I'm trying `app.commandLine.appendSwitch('--limit-fps=60')`

**Comment by andrewschreiber** [comment]
Looks like `limit-fps` has been removed. I didn't see any replacement flags, though I will continue to look.

**Comment by jjppof** [comment]
Wow, will give it a try!

**Comment by jjppof** [comment]
Not working here, unfortunately.
