### ISSUE TITLE
add an option to not use dbus: electron randomly freezes inside docker containers trying to access a non existing dbus service

### ISSUE THREAD

**Issue by ninrod** [electron/electron#10345]
* Electron version: all
* Operating system: GNU/Linux

this is a follow up of Microsoft/vscode#32908. 

Basically, electron tries to always connect to a dbus socket even if one does not exist. In standard docker containers no dbus socket is ever present. Create an option to allow the user to turn off this "always connect to a dbus socket" behaviour. 

here's a sample outpout from a `vscode --verbose` when run inside a docker container:

```txt
[634:0821/185354.088216:ERROR:bus.cc(427)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
libGL error:
No matching fbConfigs or visuals found
libGL error:
failed to load driver: swrast
[634:0821/185356.147724:ERROR:bus.cc(427)] Failed to connect to the bus: /bin/dbus-launch terminated abnormally without any error message
[634:0821/185356.230790:ERROR:bus.cc(427)] Failed to connect to the bus: /bin/dbus-launch terminated abnormally without any error message
[main 6:53:58 PM] IPC#vscode-workbenchLoaded
[634:0821/185359.037561:ERROR:bus.cc(427)] Failed to connect to the bus: /bin/dbus-launch terminated abnormally without any error message
[634:0821/185359.049355:ERROR:bus.cc(427)] Failed to connect to the bus: /bin/dbus-launch terminated abnormally without any error message
[main 6:53:59 PM] IPC#vscode-machineId
[main 6:53:59 PM] IPC#vscode:broadcast null vscode:changeColorTheme {"id":"vs-dark vscode-theme-defaults-themes-dark_plus-json","background":"#1e1e1e"}
[634:0821/185425.157883:ERROR:bus.cc(427)] Failed to connect to the bus: /bin/dbus-launch terminated abnormally without any error message
[634:0821/185425.162648:ERROR:bus.cc(427)] Failed to connect to the bus: /bin/dbus-launch terminated abnormally without any error message
```

**Comment by sofianguy** [comment]
@ninrod 
can you give Electron version 2.0.0 a try and see if the issue persists?

**Comment by ninrod** [comment]
waiting for Microsoft/vscode#49644

**Comment by ninrod** [comment]
@sofianguy, as of 1.23, latest release, vscode still uses 1.7.12 so I guess I'll have to wait.

**Comment by sofianguy** [comment]
@ninrod VS Code upgraded to electron 2.0.5. Can you confirm that the bug still persists?

**Comment by ninrod** [comment]
thanks @sofianguy. Allow me some days and I'll try that as we have to rebuild several layers of tools to test the image with vscode `1.26`.

**Comment by ninrod** [comment]
Hi @sofianguy, we have confirmed that the problem still persists in `2.0.5` as vscode `1.26` still tries connecting to dbus. Here is a snippet of the output using `code --verbose` in a docker container:

```txt
windowsManager#open
[21765:0823/172352.393120:ERROR:bus.cc(395)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix") 

windowsService#isFocused 1
[21765:0823/172355.448098:ERROR:bus.cc(395)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

```

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by ChrisB-GC** [comment]
I was experiencing a similar error message regarding dbus connection, which I resolved by disabling hardware acceleration. Using the command line option `--disable-gpu` or calling `app.diableHardwareAcceleration()` in the code. No idea why this worked, but it seemed to do the trick for me.

**Comment by jdillard** [comment]
I have the same issue running an Electron app, and while researching it I found someone that had the same issue and did a little digging: https://github.com/cypress-io/cypress/blob/770b96222d38726f5c70b8864e12264b186babfa/cli/lib/exec/spawn.js#L19-L30

I don't know if that helps, but I agree a `--disable-dbus` (or whatever ends up being appropriate) would be useful to keep CI checks from failing from this dbus warning.

**Comment by olof-nord** [comment]
> I have the same issue running an Electron app, and while researching it I found someone that had the same issue and did a little digging: https://github.com/cypress-io/cypress/blob/770b96222d38726f5c70b8864e12264b186babfa/cli/lib/exec/spawn.js#L19-L30
> 
> I don't know if that helps, but I agree a CLI flag for `--disable-dbus` (or whatever ends up being appropriate) would be useful to keep CI checks from failing from this dbus warning.

@jdillard I know you wrote this a long time ago, but Thank You! I have searched all over for a very long time in trying to understand what caused the log message.
