### ISSUE TITLE
Fullscreen transition issue when setContentProtection is enabled

### ISSUE THREAD

**Issue by njbmartin** [electron/electron#10343]
* Electron version: 1.7.5
* Operating system: macOS 10.12.6

### Expected behavior

Entering and Exiting fullscreen should be smooth.

### Actual behavior

Window disappears until the transition has finished when entering fullscreen. Exiting fullscreen results in just a title bar until the transition has finished.

### How to reproduce

Enable content protection of the browser window using `window.setContentProtection(true)`.

Simple example here: https://github.com/njbmartin/electron-fullscreen-issue

    $ git clone https://github.com/njbmartin/electron-fullscreen-issue.git
    $ npm install
    $ npm start

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
