### ISSUE TITLE
Webview in secure page

### ISSUE THREAD

**Issue by akzhy** [electron/electron#10353]
Hi,
I am using `webview` to open a secure page. The webpage opens but whenever i do something in the webpage (example: clicking a link) the webpage stops with a "application ended" message. Usually this happens when the webpage is opened in a different tab, different browser,reloaded or logged in another pc, as this is a secure page. I did not use `preload` or any injection methods but still the websites stops.

The webpage will stop if it is opened in two different tabs, so i am guessing that this is related to how webview handles the page. 

Is there a way to overcome this ?

I am using electron `1.7.5` on windows 8.1

I have tried disabling/enabling `nodeintegration`,`disablewebsecurity`,`allowpopups` 
And also tried changing the `userAgent`

**Update**

I found that when i use [browserView](https://github.com/electron/electron/blob/master/docs/api/browser-view.md) instead of web-view, the website works fine.

**Comment by deepak1556** [comment]
Can you provide minimal example app to reproduce the issue, thanks!

**Comment by sofianguy** [comment]
@akzhy 
Thank you for your issue!

We haven't gotten steps to reproduce this issue. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
