### ISSUE TITLE
Is there any way to prevent (Title Bar + System Menu bar) to show up on fullscreen

### ISSUE THREAD

**Issue by orklann** [electron/electron#10359]
I am currently making my HTML5 game with Electron, and on macOS, if the mouse move to the top of the screen the tittle bar and system menu bar will show up while my windows is on fullscreen.

This will make the gaming experiment so bad, any way to prevent the title bar and system menu bar to show up while window is on fullscreen?

**Comment by JyotirmoyGoswami** [comment]
npm not providing electron 1.7.6 by default. Its still providing 1.7.5...

**Comment by robinwassen** [comment]
@orklann Fullscreen usually behaves like that on macOS, just try full screen in any other app to see an example.

Use BrowserWindow.setKiosk(flag) instead: https://electron.atom.io/docs/api/browser-window/#winsetkioskflag

Just remember to bind a button or something to disable kiosk again.

**Comment by orklann** [comment]
Just made it work by using `BrowserWindow.setKiosk(flag)`.

Thanks @robinwassen

**Comment by Bug-Reaper** [comment]
2024 and setKoisk seems to no-longer prevent the bar from appearing in full-screen (macOS Ventura)
