### ISSUE TITLE
FPS is dropped to 30 from 60 with 2 windows (webgl)

### ISSUE THREAD

**Issue by tywang2006** [electron/electron#10351]
I have a game running in 2 windows. if the game is running in the 1st window, it is perfectly 60fps. when it is running with 2 windows. even though the 2nd window runs empty html page, the game fps is just dropped dramatically. the main game in the 1st windows is running webgl. I have tested webgl, canvas and empty html in 2nd windows. the result is same.

**Comment by codebytere** [comment]
Closing due to abandonment.
