### ISSUE TITLE
The shadow disappears when the transparent window changes its size

### ISSUE THREAD

**Issue by u3u** [electron/electron#10358]
* Electron version: 1.7.5
* Operating system: macOS Sierra 10.12.6 (16G29)

### Expected behavior
Be able to display window shadows normally

### Actual behavior
The shadow disappears when the transparent window changes its size  
Manually hide the window, re-open after the show normal

### How to reproduce
**Main process**
``` js
mainWindow = new BrowserWindow({
  height: 180,
  width: 400,
  resizable: false,
  transparent: true,
  alwaysOnTop: true
})
```

**Rendering process**
``` js
import { remote } from 'electron'
const Window = remote.getCurrentWindow()

Window.setSize(400, 667)
```

**Comment by u3u** [comment]
Is it possible to provide windows redrawing like APIs?

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
