### ISSUE TITLE
Need a better way of setting environment 

### ISSUE THREAD

**Issue by bradennapier** [electron/electron#10357]
It appears to be impossible to use google maps with electron and webpack.  Webpack does not allow you to set environment variables at any time...

```js
process.env.GOOGLE_API_KEY = 'hi'
```

changes to

```js
'hi' = 'hi'
```

So google is broken in every way.  I got it working in development by adding the tags but i am not about to ask my users to open the app from the command line every time.!? 

This is so stupid... been dealing with this type of bs all day :(

**Comment by MarshallOfSound** [comment]
@bradennapier This is an issue with your webpack config, you need to disable the environment replacing of webpack.

Or you could try trick it, something like

```js
process['e' + 'n' + 'v'].GOOGLE_API_KEY = 'hi';
```

Should get around webpacks replacements stuff, would be better to just disable it though 😆

**Comment by bradennapier** [comment]
I am pretty sure it is not possible to turn off the replacing.  I tried literally everything and nothing changed it.  Tried node: [ process: false } and many other ways... only way I got it to work was to publish a new package `webpack-set-environment`

```js
import setEnv from 'webpack-set-environment'
setEnv({ GOOGLE_API_KEY: 'mykey' })
```
