### ISSUE TITLE
BrowserWindow crash on Github secure form without any error message

### ISSUE THREAD

**Issue by Zaccc123** [electron/electron#10367]
* Electron version: 1.75
* Operating system: macOS 10.12.6

### Expected behavior

Should work as a normal web page and function like github sign in.

### Actual behavior

BrowserWindow turn white and crashed. Verified with:

```
this.webContents.on('crashed', (event, killed) => {
  console.log('crashed');
  console.log(event);
  console.log(killed);
});
```

### How to reproduce

1. clone the repo
```
$ git clone https://github.com/electron/electron-quick-start
$ cd electron-quick-start
```

2. update to `"electron": 1.7.5` in `package.json` and do `npm install`.

3. Go to `main.js` and replace `mainWindow.loadURL` with:

```
  mainWindow.loadURL('https://github.com/login/oauth/authorize');
```

4. `npm start` and click on signin button one or few time. BrowserWindow will turn white and crashed.

On version `1.6.2` of the `electron-quick-start`, it will work normally.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
