### ISSUE TITLE
Confirm beforeunload

### ISSUE THREAD

**Issue by dkirchhof** [electron/electron#10360]
* Electron version: 1.6.11
* Operating system: Windows 10

i know that there are hundreds of questions like: "How can i prevent the close event" or something like that.  
After implementing a confirmation box (`showMessageBox`) in the `beforeunload` event i was able to close my app and cancel the close event. Since the dev tools are always open, i didn't recognize that it doesn't work while the dev tools are closed...

	window.onbeforeunload = e =>
	{			
		// show a message box with "save", "don't save", and "cancel" button
		let warning = remote.dialog.showMessageBox(...) 

		switch(warning)
		{
			case 0:
				console.log("save");
				return;
			case 1:
				console.log("don't save");
				return;
			case 2:
				console.log("cancel");
				return false;
				// e.returnValue = "false";
				// e.returnValue = false;
		}
	};

### Expected behavior

The cancel button should prevent the app from closing. Regardless whether there are one or more windows opened.

### Actual behavior

So, when the dev tools or another `BrowserWindow` are opened, i can close the app with saving, without saving and cancel the event.  
When the dev tools or another window are closed, the cancel button doesn't work anymore.

Btw.:  

	window.onbeforeunload = e =>
	{			
		return false;
		alert("foo");
	};

will cancel the close event and obviously wouldn't show the message (doesn't matter if dev tools are open or closed)

	window.onbeforeunload = e =>
	{			
		alert("foo");
		return false;
	};

will cancel the close event after pressing ok if dev tools are open and will close the app after pressing ok if dev tools are closed  
  
Intentionally i'm using the synchronous api of the message box.

**Comment by dkirchhof** [comment]
To complete the issue i created a repository with a minimal test case:

1. clone and start app
  ```sh
  $ git clone https://github.com/dkirchhof/electron-confirmation-dialog.git
  $ npm install
  $ electron .
  ```
1. open dev tools (ctrl+shift+i)
1. close app
1. try ok and cancel button
1. open app again
1. close app without dev tools
1. try ok and cancel button

Until step 3 everything is fine. Step 6 shows the unexpected behavior.

**Comment by remss** [comment]
Any news in this ? 

The issue persists in 1.7 and 1.8.2beta3.

Note that this issue is not 100% reproducible. Sometimes I have to click 3 or 7 times on the "Cancel" button for the application to be accidentally closed.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by dkirchhof** [comment]
Sorry, didn't have time to test it, but now, i checked out the same problem with a new version of electron.
So, with the following configuration it will produce the expected behavior:
- Electron version: 4.0.1
- Operating system: Linux
