### ISSUE TITLE
Node macro `DISALLOW_COPY_AND_ASSIGN ` is incompatible with the Chromium code

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#10363]
`DISALLOW_COPY_AND_ASSIGN` is defined in both Node and Chromium code:

**Chromium** [base/macros.h](https://chromium.googlesource.com/chromium/src.git/+/61.0.3163.59/base/macros.h#23):
```cpp
// Put this in the declarations for a class to be uncopyable.
#define DISALLOW_COPY(TypeName) \
  TypeName(const TypeName&) = delete
  
// Put this in the declarations for a class to be unassignable.
#define DISALLOW_ASSIGN(TypeName) TypeName& operator=(const TypeName&) = delete

#define DISALLOW_COPY_AND_ASSIGN(TypeName) \
  DISALLOW_COPY(TypeName);                 \
  DISALLOW_ASSIGN(TypeName)
```
**Node** [src/util.h](https://github.com/nodejs/node/blob/v8.2.1/src/util.h#L90)
```cpp
#define DISALLOW_COPY_AND_ASSIGN(TypeName)                                    \
  void operator=(const TypeName&) = delete;                                   \
  void operator=(TypeName&&) = delete;                                        \
  TypeName(const TypeName&) = delete;                                         \
  TypeName(TypeName&&) = delete
```

In the Electron the Chromium macro is undefined in the [atom/common/node_includes.h](https://github.com/electron/electron/blob/v1.7.6/atom/common/node_includes.h#L23).

The problem is that the Chromium code, obviously, expects this macro to be the Chromium one, and usage of the Node definition leads to `functions that differ only in their return type cannot be overloaded` and `constructor cannot be redeclared` compilation errors if a class defines something similar to the Node macro contents.
Check [base/threading/sequence_local_storage_map.h](https://chromium.googlesource.com/chromium/src.git/+/61.0.3163.59/base/threading/sequence_local_storage_map.h#36) for example:
```cpp
ValueDestructorPair(ValueDestructorPair&& value_destructor_pair);

ValueDestructorPair& operator=(ValueDestructorPair&& value_destructor_pair);
```

@zcbenz, any thoughts how to avoid those errors?

/cc @tonyganch

**Comment by zcbenz** [comment]
@alexeykuzmin My workaround is to put `#include "atom/common/node_includes.h"` after all other include directives, see `atom_renderer_client.cc` for example.

**Comment by alexeykuzmin** [comment]
@zcbenz It works, thanks.

But it really is a workaround. Is there any way to avoid this confusion altogether?

**Comment by zcbenz** [comment]
@alexeykuzmin I think a real fix is to make a change in upstream Node that detects the define with `#ifndef DISALLOW_COPY_AND_ASSIGN`.
