### ISSUE TITLE
Error: Removing all listeners from ipcRenderer will make Electron internals stop working

### ISSUE THREAD

**Issue by sweetevil** [electron/electron#10379]
* Electron version:
* Operating system:

### Expected behavior

`ipcRenderer.removeAllListeners();` command should work as in documentation `removeAllListeners` parameter is optional here : https://electron.atom.io/docs/api/ipc-renderer/#ipcrendererremovealllistenerschannel

### Actual behavior

When I try to call `ipcRenderer.removeAllListeners();` It is giving me Error as : `Error: Removing all listeners from ipcRenderer will make Electron internals stop working.  Please specify a event name at EventEmitter.ipcRenderer.removeAllListeners`

### How to reproduce

Simply, register any listener on a working electron app view and remove it in `componentWillUnmount` it will be replicated.

**Comment by MarshallOfSound** [comment]
Documentation is being updated in #10380
