### ISSUE TITLE
Use camelCase for MenuItem roles

### ISSUE THREAD

**Issue by zeke** [electron/electron#10372]
A followup to #10271 

Lowercase roles like `movetabtonewwindow` are hard to read. If there's not a technical reason that they have to be lowercase, we should use mixed case to make them more legible, e.g. `moveTabToNewWindow`. To avoid making this a breaking change, we could quietly continue to support the old lowercase style.

https://electron.atom.io/docs/api/menu-item/#roles

**Comment by zcbenz** [comment]
Sounds good to me.
