### ISSUE TITLE
窗口移动,触发上万次 move

### ISSUE THREAD

**Issue by gjf450005950** [electron/electron#10385]
* Electron version: 1.7.5
* Operating system: window 10 企业版

### Expected behavior
退拽结束触发一次

### Actual behavior
拖拽结束一直调用 Event: 'move'，6万多次。

### How to reproduce
1、渲染页面(electron-vue)
2、
const remote = require('electron').remote
const BrowserWindow = remote.BrowserWindow
3、主窗口内打开新窗口
let  = new BrowserWindow()
4、
win.on('move', function (e) {
   console.log(e)  
}

**Comment by KagamiChan** [comment]
Please provide a minimal repo or your complete code to reproduce the issue

**Comment by gjf450005950** [comment]
这里完整的代码
https://gitee.com/g-vic/KanBan/blob/master/src/renderer/components/Home.vue

**Comment by KagamiChan** [comment]
I have not digged into your code, but it appears to me that a new event handler is added every time `panel` is changed (your code is inside vue `watch`'s handler), and that is why you see multiple calls.

**Comment by gjf450005950** [comment]
明白了，注册了太多的事件
