### ISSUE TITLE
Tray menu with two columns or additional icon?

### ISSUE THREAD

**Issue by leszekkn** [electron/electron#10384]
Is it possible to create a menuItem with an additional icon on the right-hand side?
I know that you can add an icon before menuItem's title, but I'm looking for a way to create something similar to Wi-Fi list:
![screen shot 2017-08-29 at 15](https://user-images.githubusercontent.com/7091842/29823340-a7be217a-8cce-11e7-9956-1a55c72efcb9.png)

**Comment by vanessayuenn** [comment]
Unfortunately, this is not possible with the current `MenuItem` API. To have a menu with custom layout like the wifi list, you will have to build it as a separate `BrowserWindow` and display it at where the normal tray menu would go.
