### ISSUE TITLE
webview : <disablewebsecurity> doesn't work

### ISSUE THREAD

**Issue by jsmonkey** [electron/electron#10381]
Hey guys,

I'm using `webview` element in my plugin for Atom editor with `disablewebsecurity` prop.  

Since last update of the editor local images with path like `<img src="file:///...">` have stopped loading with error: `(blocked:csp) Refused to load the image 'file:///...' because it violates the following Content Security Policy directive: "img-src *".`.   

I've tried to add `meta` element to exclude my case like `<meta http-equiv="Content-Security-Policy" content="img-src 'self' file: *">` and this didn't fix the issue.  

Before last update of the editor all features worked fine. Also I've referenced this issue before: [webview disablewebsecurity](https://github.com/electron/electron/issues/884)

Atom version: v1.19.3
Electron version: v1.6.9  
Operating system: Windows 10 x64

### Expected behavior
Local images are loaded in `webview` with `disablewebsecurity` attribute.

### Actual behavior
Local images aren't loaded in `webview` with `disablewebsecurity` attribute.

### How to reproduce
Use `webview`  element and try to load any `html` into it with 'img' tag which references to local image.

Thanks.

**Comment by jsmonkey** [comment]
The issue has disappeared since latest Atom v1.21.0

I think that it was triggered due to using another version of node.js instead of OOTB packaged with Electron v1.6.9

Atom v1.21.0 [release notes](https://github.com/atom/atom/releases/tag/v1.21.0).
I guess this [update](https://github.com/atom/atom/pull/15557) fixed all the things.

**Comment by zeke** [comment]
Thanks for following up, @jsmonkey

**Comment by jsmonkey** [comment]
It became reproducible since Electron v1.6.16 in Atom v1.24.0

**Comment by jsmonkey** [comment]
That's configured `webview` element:  
![image](https://user-images.githubusercontent.com/11045284/36540301-e30768f2-17ea-11e8-802e-d053f6e2c861.png)
And this is the error:  
![image](https://user-images.githubusercontent.com/11045284/36540364-142b94e4-17eb-11e8-9e45-21399abd0d33.png)

**Comment by jsmonkey** [comment]
Hey guys,

More important details for you.
When I use `<webview>` element with simple http(s) url like `http://some.domain/some.resource` for `src` property and with enabled `disablewebsecurity` flag then everything is ok with loading local images.

But if I put url with inline basic auth credentials like `https://login:password@some.domain/some.resource` then loading of local images crashes with previously mentioned error. Even after changing `src` property value back and clearing application data it seems like cached credentials are still not deleted and local images still not available for loading because of error (mb due to this cached credentials).

May be this [discussion ](https://bugs.chromium.org/p/chromium/issues/detail?id=108291) will be helpful.

Thanks

**Comment by jsmonkey** [comment]
Are there any updates?

**Comment by mannok** [comment]
Facing the same problem. Any fix?
