### ISSUE TITLE
About character display problem

### ISSUE THREAD

**Issue by Maybrittnelson** [electron/electron#10397]
* Electron version:
1.7.5
* Operating system:
win10

### Expected behavior

I think the text of the browser should be the same as the electrons
### Actual behavior

![error](https://user-images.githubusercontent.com/20365012/29863628-d85a7b56-8da2-11e7-9c43-4f6669c46318.png)
But the browser shows better look（The left is the browser）

However, the mac show is indeed more impressive

**Comment by sofianguy** [comment]
Hi @Maybrittnelson, can you add some steps to reproduce this issue please?

**Comment by sofianguy** [comment]
@Maybrittnelson 
Thank you for your issue!

We haven't gotten a response to our questions in our [comment](https://github.com/electron/electron/issues/10397#issuecomment-335043502). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
