### ISSUE TITLE
Could not parse checksum file at line 1

### ISSUE THREAD

**Issue by nazmul202101** [electron/electron#10399]
PS C:\Users\sheik\Desktop\electron> cd myapp
PS C:\Users\sheik\Desktop\electron\myapp> npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (myapp)
version: (1.0.0)
description:
entry point: (index.js) main.js
test command:
git repository:
keywords:
author: Nazmul
license: (ISC)
About to write to C:\Users\sheik\Desktop\electron\myapp\package.json:

{
  "name": "myapp",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Nazmul",
  "license": "ISC"
}

Is this ok? (yes) yes
PS C:\Users\sheik\Desktop\electron\myapp> npm install electron --save-dev

> electron@1.7.5 postinstall C:\Users\sheik\Desktop\electron\myapp\node_modules\electron
> node install.js

C:\Users\sheik\Desktop\electron\myapp\node_modules\electron\install.js:48
  throw err
  ^

Error: Could not parse checksum file at line 1:
npm WARN myapp@1.0.0 No description
npm WARN myapp@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "electron" "--save-dev"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! electron@1.7.5 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.7.5 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\sheik\Desktop\electron\myapp\npm-debug.log
PS C:\Users\sheik\Desktop\electron\myapp>

**Comment by myfrndjk** [comment]
Hi,

 Did you tried this solutions mentioned here  https://github.com/electron/electron/issues/8228
https://github.com/electron/electron/issues/9595#issuecomment-304359248

**Comment by sofianguy** [comment]
@nazmul202101 Closing due to abandonment. Try @myfrndjk's solution. If you are still having issues, we'll be happy to reopen.
