### ISSUE TITLE
v8flags setting in package.json does not appear to work

### ISSUE THREAD

**Issue by tansaku** [electron/electron#10400]
* Electron version: 1.7.5
* Operating system: OSX 10.12.16

### Expected behavior

When one specifies v8flags in package.json they should be applied, e.g.   `"v8Flags": "--harmony"`

### Actual behavior

Nothing - errors arising from lack of harmony mode still occur

### How to reproduce

Here is a repo where the harmony flag works via start:

https://github.com/tansaku/electron-quick-start/tree/harmony_flag_via_start

and here's an otherwise identical one where the v8flag tries to achieve the same effect and fails:

https://github.com/tansaku/electron-quick-start/tree/v8flag_not_working

you can replicate like so:

```
  $ git clone https://github.com/tansaku/electron-quick-start -b harmony_flag_via_start
  $ npm install
  $ npm start
```
```
  $ git clone https://github.com/tansaku/electron-quick-start -b v8flag_not_working
  $ npm install
  $ npm start
```

**Comment by smurthas** [comment]
I can confirm that this is also the case on Ubuntu 14.04.

**Comment by smurthas** [comment]
From the Node.js docs on the underlying `v8.setFlagsFromString` function being called: 

> Changing settings after the VM has started may result in unpredictable behavior, including crashes and data loss; or it may simply do nothing.

Perhaps it is the case that the `v8Flags` field "works", but some flags cannot be set after the VM has started.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
