### ISSUE TITLE
child_process imported by remote.require in renderer process do not emit error event

### ISSUE THREAD

**Issue by WaiSiuKei** [electron/electron#10408]
* Electron version: 1.6.12 & 1.7.7
* Operating system: Win7

### Expected behavior

Child process spawned by renderer process should emit ENOENT error.

### Actual behavior

The ENOENT error is thrown by main process

### How to reproduce

1. open a browser window with nodeIntegration
2. open devtools
2. run the following in console, (suppose that python is not installed)
```js
require('child_process').spawn('python', ['-v']).on('error', console.log) // this works
require('electron').remote.require('child_process').spawn('python', ['-v']).on('error', console.log) // throw error
```

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.
