### ISSUE TITLE
Win7 Failed to Initialize Renderer

### ISSUE THREAD

**Issue by quantumproducer** [electron/electron#10407]
* Electron version: ~1.6.2 (from dependencies.. not sure how to detect actual version)
* Operating system: Win 7

<img width="807" alt="winspecs" src="https://user-images.githubusercontent.com/11827932/29899647-b5b3eae8-8dba-11e7-9e84-478287b78166.png">

### Expected behavior

App should start.

### Actual behavior

Failed to initialize renderer.

![win](https://user-images.githubusercontent.com/11827932/29899634-ae50f548-8dba-11e7-85c0-91ddd1712482.png)

### How to reproduce

* Win7 Machine
* Download Windows zip from http://QuantumPilot.me
* Extract .zip
* Run QuantumPilot.exe

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
