### ISSUE TITLE
Partition option does not seem to be used by net.request method

### ISSUE THREAD

**Issue by rkpatel33** [electron/electron#10406]
I am trying to send a GET request to a website using `net.request` module after logging into the website manually in a BrowserWindow and persisting the session using the webPreferences.partition option per below. However, the `net.request` gives me back the login page instead of the landing page one would see if logged in, indicating it did not use the partition indicated. Is this a bug or am I using it incorrectly? 

```js
// From main.js open browser window and login manually
let loginWindow = new BrowserWindow({
    width: 800,
    height: 600,
    title: 'Login Manually',
    show: show,
    webPreferences: {
        partition: 'persist:my-session-name'
    }
});

loginWindow.loadURL('https://my.internal.url/path');

// later in the main process, try to hit landing page or another endpoint using net.request and the same session
const net = require('electron').net;

const request = net.request({
    method: 'GET',
    url: 'https://my.internal.url/path',
    // 'persist:my-session-name' was created by logging in manually earlier
    // Failes with 'persist:my-session-name' and 'my-session-name'
    partition: 'persist:my-session-name'
});

request.on('response', (response) => {
    console.log(`STATUS: ${response.statusCode}`);

    response.on('data', (chunk) => {
        console.log(`BODY: ${chunk}`);
    });

    response.on('end', () => {
        console.log('No more data in response.');
    });
});

request.end();
```

* Electron version: 1.7.5
* Operating system: MacOS Sierra 10.12.6

### Expected behavior

Get the internal page one would see if authenticated/logged in

### Actual behavior

Get the login page that one is redirected to if not logged in

### How to reproduce

See above code snippets, can substitute any URL that has a log in page, like gmail.

**Comment by rkpatel33** [comment]
Just to add to this, using the a Session object also fails, for example here:

```js
const { app } = require('electron');

app.on('ready', function () {
    const net = require('electron').net;
    const session = require('electron').session;

    // Use net module to make https request
    let s = session.fromPartition('persist:my-session-name');

    const request = net.request({
        url: 'https://my.internal.url/path',
        session: s
    });

    request.on('response', (response) => {
        console.log(`STATUS: ${response.statusCode}`);

        response.on('data', (chunk) => {
            console.log(`BODY: ${chunk}`);
        });

        response.on('end', () => {
            console.log('No more data in response.');
        });
    });
    request.end();
});
```

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
