### ISSUE TITLE
window.open does not open anything when called from an iframe

### ISSUE THREAD

**Issue by alexstrat** [electron/electron#10401]
* Electron version: 1.7.6

### Actual behavior

When calling `window.open` from an iframe no popup is open whereas the `new-window` events is fired on the webContents.

### Expected behavior

Would expect `window.open`  to open a popup even in iframe.

Note that when using with `nativeWindowOpen` it works fine.

### How to reproduce

Use this PR: https://github.com/alexstrat/electron-quick-start/pull/1

![screenshot 2017-08-30 18 06 40](https://user-images.githubusercontent.com/687961/29882655-0045595a-8dae-11e7-97e1-609cb26a24cc.png)

**Comment by MarshallOfSound** [comment]
As far as I am aware this is expected behavior as preload scripts do not currently run in iframes.  I believe our long term plan is to make `nativeWindowOpen` default to true (when we're happy everything works) and then this will not be an issue 👍

**Comment by alexstrat** [comment]
Ok, yes indeed was wandering around and realized as well that `nativeWindowOpen` is actually the future and the solution of this.

I wished I could use `nativeWindowOpen` but can't because of #8100 😅 

However, in several cases (`window.alert`..), it looks like we could benefit from having preload running in `iframes`. Isn't that conceivable? (Relates to #1044 I guess.)

**Comment by TIM0N** [comment]
I have a similar Problem, not sure if its the same. 

**ProjectDescription:**
In render i have main page index.html which holds -> multiple webviews (webpreferences="nativeWindowOpen=yes") -> contain random content including iframes -> iframes include links or call window.open()

In index.html script I listen on new-window event like this:
```
webview.getWebContents().on('new-window', (event, url) => {
                event.preventDefault();
                shell.openExternal(url);
});
```

**Problem:**
When i build the app against electron v1.6.14 its fine, but with v1.7.5 or higher the 'new-window' event is not triggered.

Sadly i could not find what changes are responsible for breaking this behavior or how to fix it. I wonder if the above means, that there is no fix or did i miss something?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
