### ISSUE TITLE
[BrowserWindow] thickFrame false will disable maximize button

### ISSUE THREAD

**Issue by solominh** [electron/electron#10414]
* Electron version: 1.7.5
* Operating system: 7 Home premium

set thickFrame:false or set transparent:true => maximize button is disabled

![image](https://user-images.githubusercontent.com/13938331/29943021-0c2a9234-8ec2-11e7-8627-cda2d8eac856.png)

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by eliandoran** [comment]
@codebytere , it appears that this issue is still reproducible.

Setting either `thickFrame` or `transparent` in Electron 31.3.1 and 33.2.1 disables the maximize button. This also affects `backgroundMaterial`, which disables the maximize button if the native title bar is preserved.

**Comment by Wiktor102** [comment]
The same issue still persists in Electron 35.1.5. I wonder if disabling the maximize button is intentional or just a bug? It works if you hide the title bar and just show the buttons with `titleBarStyle: "hidden"` and `titleBarOverlay: true`, but the animation is lost.
