### ISSUE TITLE
Electron v1.8 Beta: Mouse Events disappear when using Pointer Events (Windows)

### ISSUE THREAD

**Issue by markusmoenig** [electron/electron#10415]
The beta adds pointer events for Windows. However on my Surface Laptop (Windows 10) I can get 2-3 brush strokes in using the pen with pressure sensitivity, after that the pen input is completely dead and only works again after a restart of the app. Normal mouse input continues to work.

The same app version running inside chrome always works with the pen.

Application download at www.paintsupreme3d.com.

**Comment by markusmoenig** [comment]
Correction. After 2-3 brush strokes only the "normal" mouse events are not send anymore for the pen input, the pointer events still arrive.

However as I only read out the pressure information from the pointer events and use the other data from the normal mouse events, my app stops working for the pen.

What is the standard behavior here ? In the browser, the normal mouse events always continue to be send for pressure sensitive hardware (and don't stop) ?

**Comment by setpixel** [comment]
Pointer events work as expected for me on windows, and mouse events.

Could you make a project that illustrates your problem?

**Comment by markusmoenig** [comment]
On my Surface Pro Laptop, which has a pressure sensitive screen usable with a pen, the pen stops to generate mouse events (for the pen) after 2-3 brush strokes using the native version of my app (the pointer events continue to work). 

In the browser it always works. I don't know yet if this issue is Surface Pro specific or not, need todo more testing.

**Comment by markusmoenig** [comment]
I just booted into Windows 10 on another computer which has a Wacom tablet. Same behavior, after one brush stroke the mouse events disappear for the pen.

I will try now to disable stuff on my app to see if something on my side is causing this.

**Comment by markusmoenig** [comment]
Ok, I found the problem.

I handled "mousedown" and "mousemove" pointer events only, I did not handle "mouseup". When I implemented "mouseup" and called event.preventDefault() inside the event handler everything worked.

When I don't call preventDefault() in "mouseup" my mouse events for the pen disappear. This behavior is definitely different than the browser behavior. 

I think this is a bug ?

**Comment by friksa** [comment]
The fabricjs library runs into this issue too.  If you freehand draw on the canvas with your Microsoft pen, the first stroke works and then all regular mouse events for the pen stops.

**Comment by TylerRsT** [comment]
Hi,
Any news on this ? I'm currently running in the exact same issue. Pointer events won't work with <select> tags, and no click events in jQuery are handled.

Events are correctly triggered with mouse.
Events are correctly triggered with fingers.
Events are correctly triggered with pens having big tips (interpreted as fingers)
Events are not triggered with pens having small leads (Dell PN557W).

Thanks

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
