### ISSUE TITLE
Electron webview crashes during WebRTC call

### ISSUE THREAD

**Issue by bennyn** [electron/electron#10412]
* Electron version: 1.7.6
* Operating system: Mac OS X 10.12.6

### Expected behavior

Established WebRTC call which can be kept alive.

### Actual behavior

In our Electron application ([Wire](https://itunes.apple.com/app/wire/id931134707)) we make use of WebRTC for one-to-one and group calls. We sometimes notice that during a call (which takes place inside a webview) the render process crashes which results in a completly black webview.

### How to reproduce

We don't have exact steps to reproduce but we saved a crash log which points to "Chrome_libJingle_Signaling": [Wire Helper_2017-08-25-133124.txt](https://github.com/electron/electron/files/1267240/Wire.Helper_2017-08-25-133124.txt)

**P.S.**
Can you give us some hints on how to get detailed debug reports? Maybe we can gather some more information as this crash happens from time to time. We will try to create a [debug build](https://github.com/electron/electron/blob/master/docs/development/build-instructions-osx.md#building) of our Electron application to give some more information.

**Comment by bennyn** [comment]
Same crashes have been seen on: 

**Mac OS X 10.10.2**

- [K-1.txt](https://github.com/electron/electron/files/1267306/K-1.txt)
- [K-2.txt](https://github.com/electron/electron/files/1267303/K-2.txt)

**Mac OS X 10.12.5**

- [S-1.txt](https://github.com/electron/electron/files/1267305/S-1.txt)
- [S-2.txt](https://github.com/electron/electron/files/1267307/S-2.txt)
- [S-3.txt](https://github.com/electron/electron/files/1267304/S-3.txt)
- [S-4.txt](https://github.com/electron/electron/files/1267308/S-4.txt)

**Comment by johnryan** [comment]
This is probably the same issue as #10000. If so it should be fixed in the 1.8 release with the upgrade to chromium 59

**Comment by bennyn** [comment]
@johnryan Thanks for the fast reply! So it might be linked to the use of [RTCStatsReport](https://developer.mozilla.org/en/docs/Web/API/RTCStatsReport). We can remove the usage of WebRTC statistics report to see if it fixes our issue. We'll try. 😃

**Comment by johnryan** [comment]
@bennyn let me know if you have any luck!

**Comment by bennyn** [comment]
@johnryan Will do! We just removed the code: https://github.com/wireapp/wire-webapp/pull/1649

**Comment by sofianguy** [comment]
@bennyn are you still having this issue?

**Comment by bennyn** [comment]
@sofianguy No, we are not having this issue anymore. Thanks for closing the ticket. The referrenced pull request helped us to resolve the issue. 💪

**Comment by ForeverPx** [comment]
@bennyn i have the same problem, how to solve it ?
