### ISSUE TITLE
How to run insalled electron app from web browser with a custom url protocol

### ISSUE THREAD

**Issue by gambheera88** [electron/electron#10416]
I'm developing a electron app and I want to register my Electron app to open via custom url protocol. I need to register my application in registry in a button click event and need to open the app via registered protocol from a eb browser later. I saw that mailto: protocol is working correctly.

* Electron version: 1.6.12
* Operating system: Windows 10

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by MarshallOfSound** [comment]
FWIW you are looking for the `setAsDefaultProtocolClient` API

https://electron.atom.io/docs/api/app/#appsetasdefaultprotocolclientprotocol-path-args-macos-windows
