### ISSUE TITLE
require is not defined    

### ISSUE THREAD

**Issue by bailihua93** [electron/electron#10410]
in iframe,  require function won't work ; so  you can require what you next in  top html , then    get  it by  
window.parent  ;      how foolish it is  to use iframe

**Comment by robinwassen** [comment]
@bailihua93 The iframe is sandboxed if I understand correctly.

Consider using a WebView so you get fine grained control about what should be allowed and enabled: https://electron.atom.io/docs/api/webview-tag/

**Comment by MarshallOfSound** [comment]
@robinwassen Is correct 👍
