### ISSUE TITLE
Suggestion: File Dialog

### ISSUE THREAD

**Issue by markusmoenig** [electron/electron#10418]
For applications, like mine, which draw user defined text into the 2D canvas, it would be great to have a file dialog on the native platforms. 

I know this is not possible on the web (although some sophisticated guesses could be done) but a user just expects a file dialog on Mac, Windows etc.

![image](https://user-images.githubusercontent.com/10293923/29955028-550df812-8f06-11e7-988f-613eb23e69a3.png)

**Comment by MarshallOfSound** [comment]
Open Dialog: https://electron.atom.io/docs/api/dialog/#dialogshowopendialogbrowserwindow-options-callback

Save Dialog: https://electron.atom.io/docs/api/dialog/#dialogshowsavedialogbrowserwindow-options-callback

**Comment by markusmoenig** [comment]
@MarshallOfSound  Sorry, I meant a font dialog, not a file dialog.
