### ISSUE TITLE
change 'from disk cache' status to 'from cache'

### ISSUE THREAD

**Issue by dmlzj** [electron/electron#10417]
how to do this..

**Comment by MarshallOfSound** [comment]
> how to do this..

Your issue isn't clear as to what you are asking, can you provide more details on what you want to achieve?

**Comment by dmlzj** [comment]
![ele](https://user-images.githubusercontent.com/3021601/29957967-efcb06d0-8f22-11e7-9589-b0cabaaae1dd.png)
 I hope it is 'from cache'

**Comment by dmlzj** [comment]
When browsing the web ‘from disk cache’ more than the time ‘from cache’！

**Comment by dmlzj** [comment]
‘from cache’ also is 0ms,but 'from disk cache' is 30ms possible

**Comment by sofianguy** [comment]
@dmlzj can you provide us more details by following these [contributing guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md#submitting-issues)
