### ISSUE TITLE
Chromium 59 Support

### ISSUE THREAD

**Issue by setpixel** [electron/electron#10411]
Hi,

What is the plan for a 1.8 release? I know the answer is probably, "When it's ready." However, I'd love to know what's blocking it's release and loose idea of when you're planning the release.

(I check the status 3 times a day 😄 )

Many many thanks!!!

**Comment by MarshallOfSound** [comment]
@setpixel You took the words write out of my default answer 😆 

> When it's ready

There have been a number of crashes and significant bugs that we felt had to be resolved before a `1.8` beta release could go out.  I believe most of those have been sorted out now so a `1.8` beta should be coming your way soon.
