### ISSUE TITLE
electron@1.8.0 post install script fails

### ISSUE THREAD

**Issue by kounelios13** [electron/electron#10428]
* Electron version:
v1.6.5
* Operating system:
Ubuntu 17.04
### Expected behavior
 `sudo npm install -g electron@1.8.0` should install electron v1.8.0 globally

### Actual behavior
electron@1.8.0 post install fails with the following console output
```

/usr/lib/node_modules/electron/install.js:48
  throw err
  ^

Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/electron/dist'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.8.0 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.8.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kounelios/.npm/_logs/2017-09-02T11_19_42_590Z-debug.log


```

The same happens If I try to install with `sudo npm install -g electron@beta`

### How to reproduce
Install latest npm(5.3.0 at the moment)

Then open a terminal and type `sudo npm install -g electron@1.8.0`

**Comment by MarshallOfSound** [comment]
See the `EACCESS` section of the installation troubleshooting 👍 

https://github.com/electron/electron/blob/1e9109f3c667562047198f4a80bb22c6c7ca3b60/docs/tutorial/installation.md#troubleshooting
