### ISSUE TITLE
Replying from notification from main process on macOS sometimes does not work

### ISSUE THREAD

**Issue by BrandonSmith** [electron/electron#10425]
* Electron version: 1.7.5
* Operating system: macOS 10.12.6

### Expected behavior

Using the reply feature of new main process Notification API on macOS should *always* work.

### Actual behavior

Intermittently the reply feature does not *not* work.

Following is a screen recording of the below linked repo. In that instance the `reply` event did not emit on the 3rd attempt.

![reply2](https://user-images.githubusercontent.com/10338/29989438-e208a0ca-8f40-11e7-8634-a1e443bd116d.gif)

### How to reproduce

* Clone repo git clone https://gist.github.com/f40776b8698ae8f9e17a080a2243118f.git
* Download the latest release, tested on 1.7.5
* `/path/to/electron /path/to/index.js`

Because of the intermittent behavior of this issue, please keep trying. I have had most success by taking my sweet time entering in text. I have reproduced clicking the `Send` button and simply clicking the `Enter` button at the end of typing.

**Comment by MarshallOfSound** [comment]
@BrandonSmith Having trouble reproducing this even with your code sample, at one point I even sat there for 5 minutes before clicking "Send" but the reply was still logged to console

**Comment by MarshallOfSound** [comment]
@BrandonSmith Ok, so a stupid amount of trying later I managed to make it do it a few times, basically it comes down to the `delegate` being destroyed in `notification.h`.  No idea why though as we maintain a reference to it the whole time.

@zcbenz Any ideas how to keep that `NotificationDelegate` alive?

**Comment by BrandonSmith** [comment]
@MarshallOfSound ... Thanks for diving in! The intermittent nature is frustrating.
Related... I haven't seen the click event fail yet myself, but would this also affect the click event?

**Comment by zcbenz** [comment]
This was because the `Notification` object got garbage collected, you can check [this FAQ entry](https://electron.atom.io/docs/faq/#my-apps-windowtray-disappeared-after-a-few-minutes) on how to solve it.

**Comment by BrandonSmith** [comment]
Thank you for the clarification. Obvious in retrospect. I was able to reliably recreate by exposing and forcing a `gc` call.

**Comment by BrandonSmith** [comment]
@MarshallOfSound Do you have any recommendations on best methods on holding onto a reference of a notification object in app code?

Namely, there seem to be some inconsistencies in when the `close` event is emitted. At least on macOS. For instance, `click` is always followed by `close`. But `reply` is *not* followed by `close`. Further, if the reply interface is expanded by clicking on the `Reply` button, then clicking on the `Close` button does dismiss the notification, but the `close` event is not emitted. In fact, no event is emitted.

So I could place dereferencing logic in `click` and `reply`, it seems I'd be leaking if someone starts to reply but then clicks the close button.

**Comment by MarshallOfSound** [comment]
@BrandonSmith There is no *perfect* way to know when you can release references for notifications, close events aren't guaranteed to be emitted on all platforms.  On macOS we can only emit close when the user explicitly closes it, not when it naturally dismisses.

Tbh I don't see notifications as being *too* much of a memory hog, I reckon go with best guess which is listening for close and reply and leaving them there if neither of those events are received

**Comment by BrandonSmith** [comment]
Got it. Thanks!
