### ISSUE TITLE
mainWindow freezes after childWindow is shown.

### ISSUE THREAD

**Issue by SheriefAlaa** [electron/electron#10426]
* Electron version: 1.7.5
* Operating system: OSX 10.11.6

### Expected behavior

Two browserWindow instances are created, one is main (visible) and the other is child (hidden). After a certain element is clicked on the mainWindow the childWindow is shown. After closing the childWindow the mainWindow is useable again.

### Actual behavior

The mainWindow completely freezes after the childWindow is shown and even if closed the mainWindow will remain frozen.

### How to reproduce

Client side message that is sent to mainWindow to show the childWindow:
```
ipcRenderer.sendSync('show-childWindow');
```

main.js
```
mainWindow = new BrowserWindow(options)
mainWindow.loadURL(url)

childWindow = new BrowserWindow({width, height, parent: mainWindow})
childWindow.loadURL(url('child_index.html'))
childWindow.hide()

ipcMain.on('show-childWindow', (event) => {
  childWindow.show()
})
```

**Comment by SheriefAlaa** [comment]
Can anyone confirm or deny this behaviour?

**Comment by Arhimondus** [comment]
Just use **send** method instead of **sendSync** and everything will be fine. **sendSync** works same as in Windows - blocks parent window.

**Comment by codebytere** [comment]
@Arhimondus's answer is correct; `sendSync` blocks the parent window and so using `send` should remedy this issue.
