### ISSUE TITLE
BrowserWindow with customButtonsOnHover and frame:false no longer rounds the corners on Mac

### ISSUE THREAD

**Issue by emilylaguna** [electron/electron#10424]
* Electron version: 1.7.5
* Operating system: macOS 10.12.6

### Expected behavior
The corners should be rounded like they were in 1.6.x

### Actual behavior
The browser windows corners are no longer rounded when running with electron 1.7.5

### How to reproduce
```
git clone https://github.com/emilylaguna/electron-quick-start.git
cd electron-quick-start
npm install
./node_modules/.bin/electron .
```

**Comment by envomer** [comment]
I have the same issue. Any update on this?

**Comment by jszaszvari** [comment]
Seeing this issue too.

After setting 'customButtonsOnHover' and frame: false

![image](https://user-images.githubusercontent.com/872463/31859696-c57e9f94-b75a-11e7-9851-197a83c22cbd.png)

Looking for a workaround or fix but have not found anything yet.

**Comment by astoilkov** [comment]
I can verify that the issue still exists in Electron 4.0.

**Comment by bjoernm** [comment]
Confirmed still an issue on "electron": "^5.0.4"
When using titleBarStyle: 'customButtonsOnHover', and frame: false, window edges become square, and not rounded.

**Comment by pronebird** [comment]
Suddenly became an issue on Electron 6 as well. 😢

**Comment by Jip-Hop** [comment]
For a multi-window video application I need the corners of my Browser Windows on MacOS not to be rounded. So I'm making use of this bug in Electron 4.2.10. But would be nice if there'd be a choice to round or not. However seems like that's not going to happen: https://github.com/electron/electron/issues/414.
