### ISSUE TITLE
Spotlight Search OSX API

### ISSUE THREAD

**Issue by EmanueleCoppola** [electron/electron#10422]
It would be awesome if there'll be an API to add custom OSX Spotlight Search commands.

Will it be available somehow?

**Comment by MarshallOfSound** [comment]
> Will it be available somehow?

Spotlight itself does not support this, spotlight alternatives such as Alfred do have API's to allow you to plug into their search system

**Comment by percyhanna** [comment]
It seems that High Sierra might now support this? https://developer.apple.com/documentation/corespotlight
