### ISSUE TITLE
Downloaded items are not saved with a file extension

### ISSUE THREAD

**Issue by ccnokes** [electron/electron#10423]
* Electron version: 1.7.5
* Operating system: MacOS 10.12.6

### Expected behavior
When I download a file, it should be saved with the file extension so that the user's OS knows how to display the file and what application to open it with.

### Actual behavior
It is saved without a file extension. 

### How to reproduce
Follow the steps here: https://github.com/ccnokes/electron-download-bug-demo

Even when I turn off the setting in Chrome that automatically downloads the file without asking (can be found here: chrome://settings/?search=download), it still doesn't work. I think Electron should behave like Chrome on this. See screenshots below:

When downloaded via Electron, there's no file extension info in the download dialog:
![image](https://user-images.githubusercontent.com/1610343/29986105-31302b72-8f1f-11e7-81cc-b69a44272973.png)
This will be saved as `ron-swanson`.

When download on Chrome, note the bottom where it indicates the format:
![image](https://user-images.githubusercontent.com/1610343/29986115-403c1acc-8f1f-11e7-9c9f-d453f8d0c3bd.png)
This will be saved as `ron-swanson.jpg`. macOS does stuff to hide the extension in the UI but the presence of the extension can be confirmed via `find ~/Downloads -name "*ron-swanson*"`.

**Comment by javan** [comment]
These's an existing issue for this https://github.com/electron/electron/issues/10121

**Comment by MarshallOfSound** [comment]
Merging into #10121  Thanks @javan
