### ISSUE TITLE
Support HTML5 form validation notifications

### ISSUE THREAD

**Issue by camilleanne** [electron/electron#1043]
Atom shell currently does not support HTML5 form validation notifications -- client side form validation is supported and you cannot submit invalid form entries, however, there is no visual cue or notification for invalid entries as there is in most browsers (see image below).

Is support for this planned?

![](https://cloud.githubusercontent.com/assets/3952537/4208326/3b7cc960-385f-11e4-847a-f52e076a5753.png)

**Comment by paulcbetts** [comment]
I think this is a side-effect of tooltips in general being missing in Atom Shell

**Comment by zcbenz** [comment]
The form validation notifications require drawing a custom tooltip, it includes an arrow, an icon, and bolded text, even porting it from Chrome's code is not easy.

I suggest implementing it in HTML in your code, I don't think I will work on this in near future.

**Comment by Juribiyan** [comment]
Ideally there should be some kind of event, something like `beforesubmit` or `validationerror`

**Comment by zenorocha** [comment]
Isn't the case to add this to the docs?

**Comment by BesatZardosht** [comment]
I have the same problem..
Is this feature added? any workaround?

**Comment by tyv** [comment]
same problem

**Comment by atypicalprogrammer** [comment]
still not fixed ?

**Comment by DovAmir** [comment]
any plans for fixing this?

**Comment by oom-** [comment]
I use the bootstrap popover as alternative.

Like that : 
```html
<form action="#" method="post">
        <div >
            <label for="exampleInputEmail1">Email address</label>
            <input type="text" class="email-test" placeholder="Enter email">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
</form>
```
> I don't set `type="email"` because bootstrap handle this and block the `submit` event.

And for script : 
```js
<script>
window.$ = window.jQuery = require('jquery');
require('bootstrap');

/*Fix Popover with bootstrap*/
$(document).ready(function ()
{
   
	//Init Popover
	var title = '<span class="glyphicon glyphicon-exclamation-sign" style="color:#ffaf1d;"></span> Warning'; //Add glyphicon in title
	var content = "This field requiere a valid email adress."; //The content
	var options = {title: title, content: content , trigger: "manual", html: true, placement: 'bottom'};
	$('form').find('input.email-test').popover(options); //Init all input.email-test with popover

	//Check email 
	function validateEmail(email)
	{
		var re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
		return re.test(email);
	}

	//Handle submit form
	$('form').submit(function (e)
	{
		var email = $(this).find('input.email-test').val(); //get the value of email-test input of the current form
		if (!validateEmail(email)) //your test
		{
			$(this).find('input.email-test').popover('show');  //show the popover on the input
			e.preventDefault();
		}
		else
		{
			$(this).find('input.email-test').popover('hide'); //hide if you want to make ajax or something else
                        // e.preventDefault(); //for cancel event
		}
	});

});
</script>
```

**Comment by mischnic** [comment]
?

**Comment by michaelmruta** [comment]
here's my  solution

`<script>
    $("form input").attr('oninvalid',"javascript:validate(this)")
    $("form input").on('change',function(evt) {
        e = $(evt.currentTarget)
        e.removeClass('input-warning')
        e.popover('destroy');
    })
    function popOptions(content){
        return {content: content,
                trigger: "manual",
                placement: "right",
                container: ".register-container",
                html: true}
    }
    function validate(elem) {
        var e = $(elem)
        var msg = e.context.validationMessage
        e.popover(popOptions(msg));
        e.popover('show');
        e.addClass('input-warning')
    }
</script>
<style>
    .popover-content {
        font-size: 0.8em;
    }
    .input-warning {
        border: 1px solid rgba(255,0,0,0.7) !important;
    }
</style>`

**Comment by ajoslin103** [comment]
is a fix for this on the radar or a roadmap ?

**Comment by rgyen** [comment]
It's 2018.. still not fixed...

**Comment by zcbenz** [comment]
I'm closing this issue since this has been implemented in Electron.
