### ISSUE TITLE
Webview src not working with URL.createObjectURL

### ISSUE THREAD

**Issue by elmasse** [electron/electron#10438]
* Electron version: 1.7.5
* Operating system: MacOS

### Expected behavior

In previous versions setting the webview src to `URL.createObjectURL(new Blob([html],{type: 'text/html'}))` was rendering the page just fine.

### Actual behavior

Nothing is rendered

### How to reproduce

Set a webview src to any `URL.createObjectURL`

```

const html = `<h1>Hello</h1>`

return (
   <webview
          key="fuuuta-webview"
          src={ URL.createObjectURL(new Blob([html],{type: 'text/html'})) }
          style={{
            background: '#fff',
            position: 'absolute',
            top: 0,
            left: 0,
            display: 'inline-flex',
            width: '100%',
            height: '100%'
          }}
    />)

```

**Comment by fabioloreggian** [comment]
+1

**Comment by fabioloreggian** [comment]
This also happens on the Windows Platform

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
