### ISSUE TITLE
Fix CSS cursor support for 'grab' and 'grabbing'

### ISSUE THREAD

**Issue by sbward** [electron/electron#10431]
* Electron version: 1.7.5
* Operating system: macOS Sierra 10.12.6

### Expected behavior

Using `cursor: grab` or `cursor: grabbing` should change the cursor to a grab or grabbing image.

### Actual behavior

The cursor does not change.  In the devtools, Chromium displays the following outputs for each cursor respectively:

![invalid-grab](https://user-images.githubusercontent.com/470810/29998823-7223b7dc-8fe9-11e7-8ce1-84a8d8ca2e57.png) ![invalid-grabbing](https://user-images.githubusercontent.com/470810/29998824-7550a3fc-8fe9-11e7-99cf-3c19d1d5b48c.png)

All other cursors I tested are working as expected (such as `help`, `crosshair`, `s-resize`, etc.).

### How to reproduce

Create a CSS class like the following and apply it to any element in Electron:

```
.grab {
  cursor: grab;
}
```

**Note**: You must use a class to see the devtools messages.  If you use `style="cursor: grab"` then Chromium simply deletes the style attribute.

**Comment by johnryan** [comment]
@sbward did you try `-webkit-grab`?

**Comment by sbward** [comment]
Thanks @johnryan, `-webkit-grab` and `-webkit-grabbing` work.  Seems strange that we'd have to use those values instead of `grab` and `grabbing`.  Is it due to some implementation detail of Electron?  Thanks.

If it is the decision of Electron maintainers that using `-webkit-grab` and `-webkit-grabbing` are a sufficient workaround to the standard CSS values then feel free to close this issue.

**Comment by johnryan** [comment]
@sbward I don't think it's an electron thing so much as a chrome/webkit thing. `grab` doesn't work in chrome either (though if you do it in the dev tools it corrects it to `-webkit-grab`). 

In any case I'm not a maintainer of the project so if your issue is solved you can go ahead and close it :)

**Comment by sbward** [comment]
Since this is actually a Chromium issue, I'll close it.
