### ISSUE TITLE
Combining vertical line overlay renders incorrectly

### ISSUE THREAD

**Issue by kode54** [electron/electron#10436]
* Electron version: 1.7.6
* Operating system: macOS 10.12.6

### Expected behavior

An example of combining glyph characters, which renders correctly in Safari:

````
A⃒ B⃒ C⃒ D⃒ 
````

### Actual behavior

The text renders as a pair of unmapped character boxes for each combined pair of letter and vertical line.

### How to reproduce

Paste the text into an input box, or render it in any web page.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
