### ISSUE TITLE
Consume RESTful API 

### ISSUE THREAD

**Issue by Ceceu** [electron/electron#10434]
I would like to make some requests for a RESTful API before displaying any window of my application. Is it possible to use ClientRequest to do this? Would anyone has an example?

Thank you very much.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
