### ISSUE TITLE
Show an error when DISPLAY environment variable is missing or invalid

### ISSUE THREAD

**Issue by jasonhansel** [electron/electron#10439]
### Description

When you run a Electron app on Linux with an incorrect or invalid `DISPLAY` environment variable, the app exits without printing an error message. It would be helpful if an error message were displayed on the console; most Linux applications give such a message.

### Steps to reproduce issue

Where `abc` is an Electron executable, run `DISPLAY=foobar ./abc`; or run `DISPLAY=foobar npm start` in the `electron-quick-start` example folder.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
