### ISSUE TITLE
Electron fails to load Slack web

### ISSUE THREAD

**Issue by caervs** [electron/electron#10446]
* Electron version: `v1.7.5`

* Operating system: `Mac OS X 10.12.2`

### Summary

I'm not sure if this is an Electron issue or a Slack issue so I'll start here. Writing a simple electron app that points to Slack web fails apparently due to a webpack module (signals) not loading.

### Expected behavior

Slack loads when you point an electron BrowserWindow object to Slack web

### Actual behavior

Electron fails to load `signals` module from webpack in two different Slack accounts

![screen](https://user-images.githubusercontent.com/706165/30080537-caadc748-9238-11e7-91bb-58508af03209.png)

### How to reproduce

Clone [caervs/atomrepro](https://github.com/caervs/atomrepro) and run `electron .`.

This repo has a simple reproducing case that makes a browser window load

```
  win.toggleDevTools();
  win.loadURL('https://atomio.slack.com');
```

Log into atomio Slack and see that it does not load.

**Comment by MarshallOfSound** [comment]
@caervs You have to disable `nodeIntegration` if you are loading remote content.  Otherwise website's webpack builds will try to use the Electron `require` function instead of their fake shimmed one

**Comment by caervs** [comment]
Yup. That was it. Thanks @MarshallOfSound!
