### ISSUE TITLE
How can we do  in electron  ,when run the electron  the  ui  just like   open a Google Chrome?

### ISSUE THREAD

**Issue by 82318179** [electron/electron#10447]
Using electron 
How to keep Google Chrome itself.

I want to  see  chrome browser UI when run the  electron ,just like to open a  Google Chrome ,How can we do it  in  electron

**Comment by MarshallOfSound** [comment]
@82318179 Electron is not a browser, we don't ship any of Chromiums UI.  If you want to make a browser you will have to build the UI yourself

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
