### ISSUE TITLE
It's any solution that not installed after downloaded in auto-updater?

### ISSUE THREAD

**Issue by dengyaolong** [electron/electron#10441]
### Expected behavior
I use auto updater to upgrade my application.
On one hand, I want to download in background, more friendly and good experience. 
On the other hand, I want give a choice to user upgrade or not?

### Actual behavior
After downloaded, application will be upgrade in next time and seems no API to abort it.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by MarshallOfSound** [comment]
> After downloaded, application will be upgrade in next time and seems no API to abort it.

This is how Squirrel updaters are designed to work 😄

**Comment by dengyaolong** [comment]
@MarshallOfSound May be it's a common require feature. Give an abort API or confirm API.
