### ISSUE TITLE
Weird flicker/flash with .setContentSize and .center

### ISSUE THREAD

**Issue by nijynot** [electron/electron#10452]
* Electron version: 1.7.5
* Operating system: Microsoft Windows 10 Enterprise (10.0.14393)

### Actual behavior

Calling `.setContentSize()` and `.center()` makes an flexbox centered image flicker onto the top-left side of the window.

### Expected behavior

When settings break points with chrome dev tools, there's no image flickering in the top-left corner of the window.
Should basically just resize and center the window and image centered at all times.

### How to reproduce
I have set up a minimal repo to demonstrate the behaviour. (https://github.com/nijynot/electron-set-content-size-bug)
```
$ git clone https://github.com/nijynot/electron-set-content-size-bug
$ npm install
$ electron .
```
Then repeatedly press left-arrow and right-arrow keys **fast**. The image should be visible in the top-left corner for a split second.

### Details
I think the flicker is due to the content inside the window not rendering. It's just the native window itself that is being rendered, and then the rest follows.
I think a similar issue is #8270. I have tried using `ipcRenderer` to call `.setContentSize()` and `.center()` to make it async, but it made no difference.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
