### ISSUE TITLE
CommandOrControl+Q fired with CMD+A on AZERTY apple keyboard on macOS

### ISSUE THREAD

**Issue by danielfebrero** [electron/electron#10456]
* Electron version: 1.7.5
* Operating system: macOS 10.12.6

### Expected behavior

Using an Apple AZERTY keyboard. CMD+Q should fire the accelerator "CommandOrControl+Q".

### Actual behavior

When using the accelerator "CommandOrControl+Q" with globalShortcuts on macOS 10.12.6 with an AZERTY keyboard, the event is fired when pressing CMD+A instead of CMD+Q

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by jaga3421** [comment]
This issue is happening in latest version of electron as well.. 
I would like to reopen this ticket
