### ISSUE TITLE
Failed to query stereo recording

### ISSUE THREAD

**Issue by Sibiraj-S** [electron/electron#10455]
* Electron version: 1.7+ also with 1.8-beta
* Operating system: Windows 10 x64

### Actual behavior

```
[24584:0907/131006.008:ERROR:adm_helpers.cc(62)] Failed to query stereo recording.
[24584:0907/131006.895:FATAL:partition_alloc.cc(934)] Check failed: page->num_allocated_slots != -1.
Backtrace:
        GetHandleVerifier [0x00007FF6F0F71415+25013]
        GetHandleVerifier [0x00007FF6F0FE38B3+493139]
        (No symbol) [0x00007FF6F0F688E4]
        IsSandboxedProcess [0x00007FF6F3F5313D+46695785]
        IsSandboxedProcess [0x00007FF6F2ED586B+29404311]
        v8::internal::OptimizingCompileDispatcher::Unblock [0x00007FFF5BF0C827+1831]
        v8::internal::OptimizingCompileDispatcher::Unblock [0x00007FFF5BF0CB42+2626]
        v8::internal::AllocationSpaceName [0x00007FFF5BEB51F8+13784]
        v8::internal::AllocationSpaceName [0x00007FFF5BEBCB71+44881]
        v8::internal::Builtins::WasmStackGuard [0x00007FFF5BEACA37+50967]
        v8::internal::AllocationSpaceName [0x00007FFF5BEB56AE+14990]
        v8::internal::AllocationSpaceName [0x00007FFF5BEB48EB+11467]
        v8::internal::AllocationSpaceName [0x00007FFF5BEB3B3E+7966]
        v8::internal::OptimizingCompileDispatcher::IsQueueAvailable [0x00007FFF5BBB5929+2745]
        v8::internal::ScavengeJob::NotifyIdleTask [0x00007FFF5BBB7075+1781]
        v8::internal::GCTracer::AddScopeSample [0x00007FFF5BBA90D0+13872]
        v8::internal::GCTracer::AddScopeSample [0x00007FFF5BBA8DAA+13066]
        v8::internal::StackGuard::HandleInterrupts [0x00007FFF5BBC421C+44]
        v8::base::MagicNumbersForDivision<unsigned __int64>::operator== [0x00007FFF5C1CD42B+161019]
        (No symbol) [0x000003370CD04421]
```

### How to reproduce

I got this error while downloading files with [webtorrent](https://webtorrent.io/docs). the same piece of code works well in the browser

**Additional Information**

This works fine with ` electron version 1.6.x`

is this possible chromium issue?

**Comment by chrisvfritz** [comment]
Just noticed this same (intermittent) error using the node version of `superagent`, I think most likely happening during garbage collection. Both `webtorrent` and `superagent` depend on `readable-stream`, `mime`, and `debug` - possibly a place to start narrowing this down.

**Comment by pandora2000** [comment]
I don't know if it is useful. But, I created minimal example. 

```
git clone https://github.com/pandora2000/test-electron-quick-start.git
cd test-electron-quick-start
yarn
npm start
```

Then, at some random point, you will get white screen and console output like below.

```
[31898:1023/020028.136265:FATAL:partition_alloc.cc(934)] Check failed: page->num_allocated_slots != -1.
#0 0x0000036228e7 <unknown>
#1 0x00000363862b <unknown>
#2 0x0000035e4595 <unknown>
#3 0x0000034f29fd <unknown>
#4 0x7fe7a8d54f9b <unknown>
#5 0x7fe7a8d54eeb <unknown>
#6 0x7fe7a90c6791 <unknown>
#7 0x7fe7a90bfa7e <unknown>
#8 0x7fe7a90bfd2d <unknown>
#9 0x7fe7a8d4e390 v8::internal::PagedSpace::SlowAllocateRaw()
#10 0x7fe7a8e15fae <unknown>
#11 0x7fe7a90ca966 <unknown>
#12 0x7fe7a90ca288 <unknown>
#13 0x7fe7a90c570b <unknown>
#14 0x7fe7a90c53b5 <unknown>
#15 0x7fe7a90d0d61 <unknown>
#16 0x7fe7a90c620e <unknown>
#17 0x7fe7a90beb67 <unknown>
```

It's only small change from electron-quick-start and use superagent.

**Comment by eyalap** [comment]
@pandora2000 Did you find the cause for it, I'm not using superagent and getting theses errors as well after a few clicks on my app

**Comment by KochiyaOcean** [comment]
I tried using `request` and `node-fetch` module and get a similar error that crushes electron.
Error message:
```
[10332:1101/025624.343:FATAL:partition_alloc.cc(934)] Check failed: page->num_allocated_slots != -1.
Backtrace:
        GetHandleVerifier [0x00007FF6C5302475+25013]
        GetHandleVerifier [0x00007FF6C5374913+493139]
        (No symbol) [0x00007FF6C52F9944]
        IsSandboxedProcess [0x00007FF6C82E419D+46695797]
        IsSandboxedProcess [0x00007FF6C72668CB+29404323]
        v8::internal::OptimizingCompileDispatcher::Unblock [0x00007FFB6F31C700+1504]
        v8::internal::OptimizingCompileDispatcher::Unblock [0x00007FFB6F31C9D1+2225]
        v8::internal::AllocationSpaceName [0x00007FFB6F2CB322+38626]
        v8::internal::AllocationSpaceName [0x00007FFB6F2C98B2+31858]
        v8::internal::AllocationSpaceName [0x00007FFB6F2C99B0+32112]
        v8::internal::PagedSpace::SlowAllocateRaw [0x00007FFB6F0A11B6+150]
        v8::internal::PagedSpace::AllocateRawUnaligned [0x00007FFB6EEB24F6+102]
        v8::internal::AllocationSpaceName [0x00007FFB6F2CD8A3+48227]
        v8::internal::AllocationSpaceName [0x00007FFB6F2CEA74+52788]
        v8::internal::Builtins::WasmStackGuard [0x00007FFB6F2BE23B+57083]
        v8::internal::AllocationSpaceName [0x00007FFB6F2C520A+13770]
        v8::internal::AllocationSpaceName [0x00007FFB6F2CCB91+44881]
        v8::internal::Builtins::WasmStackGuard [0x00007FFB6F2BCA57+50967]
        v8::internal::AllocationSpaceName [0x00007FFB6F2C56CE+14990]
        v8::internal::AllocationSpaceName [0x00007FFB6F2C490B+11467]
        v8::internal::AllocationSpaceName [0x00007FFB6F2C3B5E+7966]
        v8::internal::OptimizingCompileDispatcher::IsQueueAvailable [0x00007FFB6EFC5929+2745]
        v8::internal::ScavengeJob::NotifyIdleTask [0x00007FFB6EFC7075+1781]
        v8::internal::GCTracer::AddScopeSample [0x00007FFB6EFB90D0+13872]
        v8::internal::GCTracer::AddScopeSample [0x00007FFB6EFB8DAA+13066]
        v8::internal::OptimizingCompileDispatcher::Enabled [0x00007FFB6EFC09F0+3456]
        v8::internal::interpreter::Bytecodes::ToString [0x00007FFB6F2FD90C+2940]
        GetHandleVerifier [0x00007FF6C53A35E8+684840]
        IsSandboxedProcess [0x00007FF6C78B3E54+36012588]
        IsSandboxedProcess [0x00007FF6C78B2BAF+36007815]
        IsSandboxedProcess [0x00007FF6C78B062D+35998213]
        GetHandleVerifier [0x00007FF6C53A35E8+684840]
        GetHandleVerifier [0x00007FF6C5344656+295830]
        GetHandleVerifier [0x00007FF6C5343140+290432]
        GetHandleVerifier [0x00007FF6C53A5623+693091]
        GetHandleVerifier [0x00007FF6C53406BE+279550]
        IsSandboxedProcess [0x00007FF6C5DB42DF+7702199]
        IsSandboxedProcess [0x00007FF6C59FEC1D+3813365]
        IsSandboxedProcess [0x00007FF6C59FEB14+3813100]
        IsSandboxedProcess [0x00007FF6C6B4756A+21936450]
        GetHandleVerifier [0x00007FF6C5406DE0+1092384]
        (No symbol) [0x00007FF6C504AAF7]
        IsSandboxedProcess [0x00007FF6C82C8A4B+46583331]
        BaseThreadInitThunk [0x00007FFBE2491FE4+20]
        RtlUserThreadStart [0x00007FFBE262EF91+33]
```

**Comment by KochiyaOcean** [comment]
This bug stills occurs on Electron@1.8.2-beta.2
![image](https://user-images.githubusercontent.com/8194131/32482738-58b84cc8-c3dc-11e7-97e9-784e7d4f241c.png)

**Comment by v9Chris** [comment]
Getting a similar FATAL:partition_alloc.cc error in 1.8.1 when saving images to disk.

No issues in 1.7.9

**Comment by karacas** [comment]
Same here using superagent & electron 1.8.2-beta.2 / msw  [Version 10.0.16299.64]

**Comment by karacas** [comment]
[14212:1117/172433.651:FATAL:partition_alloc.cc(934)] Check failed: page->num_allocated_slots != -1.
Backtrace:
        GetHandleVerifier [0x00007FF6128B5745+25013]
        GetHandleVerifier [0x00007FF612927BE3+493139]
        (No symbol) [0x00007FF6128ACC14]
        IsSandboxedProcess [0x00007FF61589744D+46695649]
        IsSandboxedProcess [0x00007FF614819BFB+29404303]
        v8::internal::OptimizingCompileDispatcher::Unblock [0x00007FFABB09C700+1504]
        v8::internal::OptimizingCompileDispatcher::Unblock [0x00007FFABB09C9D1+2225]
        v8::internal::AllocationSpaceName [0x00007FFABB04B322+38626]
        v8::internal::AllocationSpaceName [0x00007FFABB0498B2+31858]
        v8::internal::AllocationSpaceName [0x00007FFABB0499B0+32112]
        v8::internal::PagedSpace::SlowAllocateRaw [0x00007FFABAE211B6+150]
        v8::internal::PagedSpace::AllocateRawUnaligned [0x00007FFABAC324F6+102]
        v8::internal::AllocationSpaceName [0x00007FFABB04D8A3+48227]
        v8::internal::AllocationSpaceName [0x00007FFABB04EA74+52788]
        v8::internal::Builtins::WasmStackGuard [0x00007FFABB03E23B+57083]
        v8::internal::AllocationSpaceName [0x00007FFABB04520A+13770]
        v8::internal::AllocationSpaceName [0x00007FFABB04CB91+44881]
        v8::internal::Builtins::WasmStackGuard [0x00007FFABB03CA57+50967]
        v8::internal::AllocationSpaceName [0x00007FFABB0456CE+14990]
        v8::internal::AllocationSpaceName [0x00007FFABB04490B+11467]
        v8::internal::AllocationSpaceName [0x00007FFABB043B5E+7966]
        v8::internal::OptimizingCompileDispatcher::IsQueueAvailable [0x00007FFABAD45929+2745]
        v8::internal::ScavengeJob::NotifyIdleTask [0x00007FFABAD47075+1781]
        v8::internal::GCTracer::AddScopeSample [0x00007FFABAD390D0+13872]
        v8::internal::GCTracer::AddScopeSample [0x00007FFABAD38DAA+13066]
        v8::internal::OptimizingCompileDispatcher::Enabled [0x00007FFABAD409F0+3456]
        v8::internal::interpreter::Bytecodes::ToString [0x00007FFABB07D90C+2940]
        GetHandleVerifier [0x00007FF6129568B8+684840]
        IsSandboxedProcess [0x00007FF614E67184+36012568]
        IsSandboxedProcess [0x00007FF614E65EDF+36007795]
        IsSandboxedProcess [0x00007FF614E6395D+35998193]
        GetHandleVerifier [0x00007FF6129568B8+684840]
        GetHandleVerifier [0x00007FF6128F7926+295830]
        GetHandleVerifier [0x00007FF6128F6410+290432]
        GetHandleVerifier [0x00007FF6129588F3+693091]
        GetHandleVerifier [0x00007FF6128F398E+279550]
        IsSandboxedProcess [0x00007FF61336761B+7702191]
        IsSandboxedProcess [0x00007FF612FB1F59+3813357]
        IsSandboxedProcess [0x00007FF612FB1E50+3813092]
        IsSandboxedProcess [0x00007FF6140FA89A+21936430]
        GetHandleVerifier [0x00007FF6129BA0B0+1092384]
        (No symbol) [0x00007FF6125FAAF7]
        IsSandboxedProcess [0x00007FF61587BCFF+46583187]
        BaseThreadInitThunk [0x00007FFB06891FE4+20]
        RtlUserThreadStart [0x00007FFB08BCEF91+33]

**Comment by zcbenz** [comment]
I'm merging this to #11457.
