### ISSUE TITLE
Can't open app on Windows 10 S

### ISSUE THREAD

**Issue by myranx** [electron/electron#10457]
Electron version: 1.6.7
Operating system: Windows 10 S

I ran electron-windows-store command in powershell to create Appx package. The appx package installed and app worked well on Windows 10 Pro.
On Windows 10 S, the appx package installed successful, but when open the app, it shows the dialog as below, can't open the app.
![image](https://user-images.githubusercontent.com/4263609/30157754-b3027210-93f5-11e7-991e-9fa08add04f2.png)

**Comment by fancyydk** [comment]
This is the way Windows 10 S works. It only lets you install apps from the Windows Store. You have to create an account for the Windows Store and submit your app. Once it becomes visible, then you will be able to install it.

**Comment by myranx** [comment]
OK, I see, thanks!
