### ISSUE TITLE
Electron Helper Crash - CMD+R in DevTools while paused with debugger statement - CrRendererMain EXC_BAD_INSTRUCTION SIGILL (macOS 10.13)

### ISSUE THREAD

**Issue by SMotaal** [electron/electron#10458]
I submitted this to iron-node's issues and we concluded this could be more relevant to your team. Just have to mention, I'm using macOS 10.13 developer/public beta, though this type of crash initially occurred on 10.12 stable.

### Description

I'm currently working on a nodes project that seems to crash Electron Helper when I hit cmd+R while devtools is paused at a debugger statement (while using iron-node).

### Steps to Reproduce

The project calls require(' ts-node/require') then require('index.ts') to start my app, which might be relevant to reproduce. The debugger statement resides in the index.ts (which is transpired and loaded with inlined source maps  by ts-node.

1. Launch iron-node within the project folder: iron-node ./index.js
2. Wait for devtools to pause at a debugger statement.
3. Hit cmd+R

**Expected behavior:**

Reloads without issues.

**Actual behavior:**

Reloads but shows Problem Report for Electron Helper

**Reproduces how often:**

The crash seems to occur consistently on every reload even after relaunching iron-node and restarting, upgrading iron-node and dependencies, but in rare occasion while testing it sometimes stopped happening without clear cause.

It never happened when I manually pause devtools, as opposed to dynamically pausing by calling debugger, before hitting cmd+R.

At some point when I tried to replicate this by calling debugger from index.js, I could no longer reproduce it, even when I stepped through to the debugger statement in index.ts. I even removed the debugger statement from index.js to revert to the initial scenario and it no longer crashed when dynamically paused from index.ts. I simply don't have a clue what could have changed.

This has been happening for a few months, with different versions of every aspect involved (Iron-node, electron, node, typescript, ts-node, macOS, you name it), and it is not restricted to this one project, but most of my projects will usually require ts-node/require so it remains a potential factor but not necessarily the cause.

**Screenshot(s):**

<img width="1680" alt="screen shot 2017-08-28 at 2 08 46 pm" src="https://user-images.githubusercontent.com/849613/29787668-c71072ca-8bfd-11e7-897d-ef0fec0d613a.png">

**Relevant Crash Log**
```
Crashed Thread:        0  CrRendererMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]
```
[Crash Logs.zip](https://github.com/electron/electron/files/1284286/Crash.Logs.zip)

### Version(s)

```json
{
    "http_parser": "2.7.0",
    "node": "7.9.0",
    "v8": "5.8.283.38",
    "uv": "1.11.0",
    "zlib": "1.2.11",
    "ares": "1.10.1- DEV",
    "modules": "54",
    "openssl": "1.0.2k",
    "electron": "1.7.5",
    "chrome": "58.0.3029.110",
    "atom-shell": "1.7.5",
    "ts-node": "3.3.0"
}
```

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
