### ISSUE TITLE
(v1.8.x) Context menu of flash object broken 

### ISSUE THREAD

**Issue by GhostlyDark** [electron/electron#10464]
Hello folks,

Doing a right click on a flash object opens up a context menu as expected, but clicking on the entries has no effect. Can't change quality of a flash game for example.

It works fine in v1.7.x.
The attached .zip contains the newest pepper based flash plugin, a main.js and a package.json that might help you reproduce the issue.

System:
Win7 x64
Electron v1.8.x
Pepper Flash Plugin v26.0.0.151 x64
[flash-context-menu.zip](https://github.com/electron/electron/files/1285786/flash-context-menu.zip)

**Comment by jkleinsc** [comment]
I tested this in 1.8.1 and the latest from master and I can reproduce the issue.  It works correctly in 1.7.9, so it is a regression that was introduced in 1.8.x
