### ISSUE TITLE
Touch screen "hold" crashes

### ISSUE THREAD

**Issue by JarOfCookies** [electron/electron#10463]
I'm building an application for touch screen, everything works great, except when for some reason users hold down on a link for 2-3 seconds electron abruptly crashes, (tapping on the links is fine)...

Any idea how to solve this issue?

The only error message is "Electron has stopped working"
Thanks!

**Comment by codebytere** [comment]
Closing due to abandonment.

**Comment by joelsand** [comment]
@JarOfCookies Did you find a resolution for this or figure out what was causing it?
