### ISSUE TITLE
canGoBack always returns false

### ISSUE THREAD

**Issue by vcapretz** [electron/electron#10461]
* Electron version: 1.7.6
* Operating system: Linux Ubuntu 16.04

### Expected behavior

I'm working on [Rocket.Chat.Electron](https://github.com/RocketChat/Rocket.Chat.Electron) to add navigation shortcuts, so on `app.on('ready')` I tried to set a globalShortcut like this: 
```js
globalShortcut.register('CommandOrControl+left', () => {
        mainWindow.webContents.goBack();
    });
``` 
 and it's not working properly
### Actual behavior

While debugging the variables I saw that `mainWindow.webContents.canGoBack()` always returns false, so it's like the page isn't navigating. 
### How to reproduce
Launch my version of the app https://github.com/vcapretz/Rocket.Chat.Electron and after navigating, press Cmd (or Ctrl) + Left

**Comment by MarshallOfSound** [comment]
@vcapretz Can you make a minimal reproduction example, basing it off `electron-quick-start` would be easiest 👍

**Comment by sofianguy** [comment]
Closing for now. Feel free to reopen if you can provide an example that @MarshallOfSound mentioned.

**Comment by vcapretz** [comment]
hey @sofianguy thanks for closing the issue and sorry for not showing up! 

actually I think it was my mistake, and not a issue with electron itself :smile: I managed to implement the shortcuts as I needed! 

thanks again

**Comment by alimuqaddas** [comment]
Hey i am having the same issue. Can you please tell me what you did to solve the issue?
