### ISSUE TITLE
LINUX is shouting for app.appimportcertificateoptions

### ISSUE THREAD

**Issue by jsoref** [electron/electron#10467]
For some reason, `LINUX` is in all caps in this one instance.

### Expected behavior

See https://electron.atom.io/docs/api/app/#appsetbadgecountcount-linux-macos
`app.setBadgeCount(count) Linux macOS`

### Actual behavior

`app.importCertificate(options, callback) LINUX`

### How to reproduce

Visit https://electron.atom.io/docs/api/app/#appimportcertificateoptions-callback-linux

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!

**Comment by jsoref** [comment]
@codebytere: @MarshallOfSound fixed it in 2019: https://github.com/electron/electron/commit/db3cf52add2c88f99dc0b6c787ebbe801cc934c0
