### ISSUE TITLE
Background not being included in printToPDF

### ISSUE THREAD

**Issue by TimNZ** [electron/electron#10466]
* Electron version: 1.7.x
* Operating system: All

### Expected behavior

Specify { printBackground: true} and background CSS should be included in generated PDF

### Actual behavior

Is not

```
app.on('ready', function() {
  mainWindow = new BrowserWindow({width: 1024, height: 768, webPreferences: { nodeIntegration: false, preload: __dirname + '/preload.js' }});
  mainWindow.loadURL('https://www.google.com');
  mainWindow.openDevTools();
  mainWindow.webContents.on('did-finish-load',() => {
    setTimeout(() => {
        mainWindow.webContents.printToPDF({printBackground: true,landscape: true},(error,data) => {
          console.log(data);
            var buf = new Buffer(data);
            fs.writeFileSync('pdf.pdf',buf);
        })

    },5000)
  })
});
```

Related issues: 
#4708
#2512

I guess the presumption by many is {printBackground: true} should be the same as enabling 'Background graphics' in the print preview settings for PDF in Chrome, but it could be a completely different rendering engine.

![screen shot 2017-09-08 at 9 15 10 am](https://user-images.githubusercontent.com/1051701/30185627-6ad06e8a-9476-11e7-9f72-f62d5cd47376.png)

**Comment by TimNZ** [comment]
Bump

**Comment by abnerlee** [comment]
+1

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by AVert** [comment]
Elrctron 16.0.1 also not working !!!!!

**Comment by AVert** [comment]
> We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

Elrctron 16.0.1 also not working !!!!!
