### ISSUE TITLE
zoom goes back to zoomFactor with which BrowserWindow was initialized

### ISSUE THREAD

**Issue by fancyydk** [electron/electron#10462]
* Electron version: 1.7.3
* Operating system: Windows and Mac

### Expected behavior

Resetting zoom factor to 1 should stay at 1.

### Actual behavior

If a BrowserWindow instance is initialized with a zoom factor other than 1.0 in the constructor parameter, for example,
```
options.webPreferences.zoomFactor = 2.0;
let window = new BrowserWindow(options);
```
and then later its zoom factor is set to 1 (or zoom level set to 0), then a certain behavior can trigger it to go back to the previous zoom factor it began with (e.g. 2.0 in the example above).

### How to reproduce

Unfortunately, I haven't found the exact repro steps using a sample electron app, but I wanted to record my observations and submit this ticket in case other people are seeing the issue too so they can add to this ticket. I will update it once I find the repro steps.

**Comment by craxal** [comment]
I'm experiencing similar issues when creating modal windows from my application's parent renderer window. Strange thing is, my child windows all start with different zoom levels than what the parent window has. For example:
1. Set the application zoom factor to 2.
2. Open a modal window using the parent's zoom factor.
3. Close the modal window.
4. Set the application zoom factor back to 1.
5. Open a modal window using the parent's zoom factor.

`window.webContents.getZoomFactor` reports the correct zoom factor until the window's contents are fully loaded.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
