### ISSUE TITLE
webContents.print() not working in Windows 7

### ISSUE THREAD

**Issue by LucasGutierres** [electron/electron#10476]
Electron version: 1.7.6
Operating system: Windows 7 64bits

I've been developing a photo booth app in Windows 10 32bits, and so far, I've had no issues like this one. The app is printing just fine in W10. I just give the command and printing begins as intended, following my preferences with no problems. The problem is not with the printer, as I succesfully printed a picture from a folder through Image Viewer.

Right now, the booth is running on Windows 7, and now that I've started testing with it, and discovered that Electron isn't printing at all. I can't open the printing window and there was no change in the printer's status.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
