### ISSUE TITLE
打开多窗口,设置宽高无效

### ISSUE THREAD

**Issue by gjf450005950** [electron/electron#10474]
* Electron version: v1.7.6
* Operating system: Win10

### Expected behavior
按照设定的宽高值打开窗口

### Actual behavior
打开的宽高值固定在800x600

### How to reproduce
应用说明，项目是一个 看板 系统，创建多个背景透明窗口贴在桌面上。
项目地址：https://gitee.com/g-vic/KanBan/releases

1、创建窗口1，宽300，高200，X:10,Y:20 
https://gitee.com/g-vic/KanBan/blob/master/src/renderer/components/Home.vue
let win= new BrowserWindow({ movable: true, frame: false, enableLargerThanScreen: true, transparent: true, width: p.width, height: p.height, x: p.x, y: p.y, skipTaskbar: true })
2、win..destroy()
3、创建窗口1，宽500，高400，X:10,Y:20 
console.log('before width:' + 500 + ' height:' + 400)
win= new BrowserWindow({ movable: true, frame: false, enableLargerThanScreen: true, transparent: true, width: 500, height:400, x: p.x, y: p.y, skipTaskbar: true })
console.log('after width:' + win.getBounds().width + ' height:' + win.getBounds().height)
= after width: 800 height:600

创建BrowserWindow 宽高500x400,结果：800x600

**Comment by KagamiChan** [comment]
Please provide a minimal reproduction sample based on https://github.com/electron/electron-quick-start

**Comment by gjf450005950** [comment]
基础electron-vue：https://electron.org.cn/vue/index.html
# 安装 vue-cli 和 脚手架样板代码
npm install -g vue-cli
vue init simulatedgreg/electron-vue my-project

# 安装依赖并运行你的程序
cd my-project
yarn # 或者 npm install
yarn run dev # 或者 npm run dev

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
