### ISSUE TITLE
Windows: autoUpdater downloads before firing update-available event

### ISSUE THREAD

**Issue by jublo** [electron/electron#10473]
* Electron version: 1.5.2
* Operating system: Windows 7

```js
const {autoUpdater, ipcMain} = require('electron')
autoUpdater.on('checking-for-update', function (event, arg) {
  win.webContents.send('checking-for-update', null);
});

autoUpdater.on('update-available', function (event, arg) {
  win.webContents.send('update-available', null);
});

autoUpdater.on('update-not-available', function (event, arg) {
  win.webContents.send('update-not-available', null);
});

autoUpdater.on('update-downloaded', function (event, arg) {
  win.webContents.send('update-downloaded', null);
});
```

When the Windows app is called, it will go like this:

1. Fire `checking-for-update` event.
1. Download `RELEASES`.
1. Download large update *.nupkg file.
1. When downloaded, fire `update-available` event.
1. Unpack nupkg.
1. Fire `update-downloaded` event.

Should it not be like this?

1. Fire `checking-for-update` event.
1. Download `RELEASES`.
1. When there is an update, fire `update-available` event.
1. Download large update *.nupkg file.
1. Unpack nupkg.
1. Fire `update-downloaded` event.

This causes trouble for us since we cannot report to the user the actual download process?

**Comment by jublo** [comment]
The delta file is downloaded twice:

1. "Checking for Updates" event.
2. Downloading delta nupkg.
3. LOG ENTRY, see below.
4. "Downloading update" event.
5. Downloading same delta nupkg again!

```
2017-09-10 13:47:24> UpdateInfo: Couldn't get release notes for:an_app-2.0.0-beta1-delta.nupkg: System.Exception: Invalid 'ReleaseNotes' value in nuspec file at 'C:\Users\chef1\AppData\Local\an_app\packages\an_app-2.0.0-beta1-delta.nupkg'
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)
```

**Comment by jublo** [comment]
See #5057.

**Comment by codebytere** [comment]
We no longer actively support bugfixes for `1.5.x` so i'm going to go ahead and close this, but if you see it recur on newer versions of Electron we can certainly reopen it.
