### ISSUE TITLE
Set "checked" in menu from cookie in app

### ISSUE THREAD

**Issue by holgersindbaek** [electron/electron#10489]
I have some settings that I want both in my main application and in the topbar menu. That leaves me that issue of syncing the settings.

In my React application, I simply save my settings to the cookie. So the question becomes, how do I access the application cookie when I create the topbar menu in the main.js file?

This is how a basic example of my topbar menu from my main.js file:

    // Create menu
    const menuArray = [
      {
        label: 'Settings',
        submenu: [
          {
            label: 'Sound',
            type: 'checkbox',
            checked: true, // Fetch saved cookie in app
            click: () => { 
              // Run function in app that changes saved cookie
            }
          }
        ],
      }
    ];

    // Set menu
    const menu = Menu.buildFromTemplate(menuArray);
    Menu.setApplicationMenu(menu);

How would you access the cookie and how would you call the function in the application that changes the cookie?

**Comment by enlight** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
