### ISSUE TITLE
Which database technology and ORM used for electron js

### ISSUE THREAD

**Issue by rssandy1991** [electron/electron#10482]
* Electron version:
* Operating system:

**Comment by enlight** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

IndexedDB is available in renderer processes, you can find various libraries that provide a nicer abstraction over it. This question has also been asked and answered multiple times on http://discuss.atom.io/c/electron
