### ISSUE TITLE
Share data between ionic app and electron app

### ISSUE THREAD

**Issue by ptitbibice** [electron/electron#10484]
Hi !

I would like send data from mobile app (ionic) to my pc app (electron) by usb connect. I search since three days, but i don’t found …

Someone has an idea ?

Thanks

**Comment by enlight** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
