### ISSUE TITLE
win.setSize doesn't resize window

### ISSUE THREAD

**Issue by mcieslakcc** [electron/electron#10488]
* Electron version: 1.7.6
* Operating system: windows 7, macOS

### Expected behavior

Window should be resized.

### Actual behavior

Window size doesn't change.

### How to reproduce

Set window fullscreen mode. 
Call -> window.setFullScreen(false).
Call -> window.setSize(w, h). 
Window size doesn't change.

  $ git clone https://github.com/mcieslakcc/electron-quick-start.git -b set_size
  $ npm install
  $ ./node_modules/.bin/electron .

**Comment by akashnimare** [comment]
@mcieslakcc try this -
```javascript 
 // Create the browser window.
  const mainWindow = new BrowserWindow({ width: 800, height: 600, fullscreen: false })

  mainWindow.setFullScreen(false);
  mainWindow.setSize(100, 350);
```

**Comment by mcieslakcc** [comment]
Hi, I think you don't understand problem. Setting 
`mainWindow.setFullScreen(false);` doesn't make sense when I set `fullscreen: false ` in constructor. Anyway this code works very well on **ubuntu**.

**Comment by codebytere** [comment]
so as far as i can tell, `setFullScreen` isn't working at all if it's called outside the constructor. I'll take a look at it now.

**Comment by codebytere** [comment]
I'm going to close this, as it's been resolved.

**Comment by rohansi-kore** [comment]
Hello
When I used first time setSize(350, 600) its working fine but when I am trying to reduce the height (setSize(350, 54)) then its not working. Can you please look this issue.
Increasing height is working fine but decreasing height is not working by using setSize method.
