### ISSUE TITLE
Inconsistent display geometry + difficulties with exact positioning

### ISSUE THREAD

**Issue by sebakerckhof** [electron/electron#10486]
I've got a 1920*1080 screen that, when attached to my system with a dedicated nvidia card, reports with a scaling factor of 1.8999... The resulting display object is:
```
  {
    "id": 10921679675412484,
    "bounds": {
      "x": 0,
      "y": 0,
      "width": 1010,
      "height": 568
    },
    "workArea": {
      "x": 0,
      "y": 0,
      "width": 1010,
      "height": 568
    },
    "size": {
      "width": 1010,
      "height": 568
    },
    "workAreaSize": {
      "width": 1010,
      "height": 568
    },
    "scaleFactor": 1.899999976158142,
    "rotation": 0,
    "touchSupport": "unknown"
  }
```

However, if I attach the same screen to my system with only the integrated intel graphics card, it reports to have a scaling factor of 1.0 and the size is therefore the usual 1920*1080. 

Besides this inconsistency, the fact that all display geometry uses this scaling factor (both in reporting and when setting the bounds of a browser window) makes it hard to position a window very precisely on a screen, since you can only give integers.

For example, if the display is reported with a scaling factor of 2, I can't specify the window to be 801 pixels wide, since I should then use 400.5 pixels, which is not an integer.

**Comment by HotoPiano** [comment]
Having the same issue:

screen.getAllDisplays();
![image](https://user-images.githubusercontent.com/16783742/76510592-28a1a700-6452-11ea-969b-2ac79ba1a06b.png)

1098 * 1.75 = 1921,5
618 * 1.75 = 1081,5

1920 / 1.75 = 1097,1428..., not 1098

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
