### ISSUE TITLE
BrowserWindow Maximizing

### ISSUE THREAD

**Issue by MunGaaKei** [electron/electron#10494]
- electron version: 1.6.2
- os: windows 7

Okay, here's a problem I've met:
If I set the BrowserWindow with option "transparent: true", the function ".isMaximized()" always return the "false" value, which means I cant reset the window into its initial size.

**Comment by robinwassen** [comment]
Duplicate of: #9092 

You might find more information about how people has worked around this issue there.

**Comment by sofianguy** [comment]
please follow #9092 for updates
