### ISSUE TITLE
Auto Updating manually, using hardcoded download URL

### ISSUE THREAD

**Issue by poojas2288** [electron/electron#10496]
* Electron version: 1.7.3
* Operating system: Win and Mac

I want to implement autoupdate functionality in my electron app.
I just want want that the application should download the updated app from a specific URL, which I will provide.
Can I skip the initial steps of checking the updates, and directly give the download URL so that it downloads the app and installs ?
I have gone through the auto-updater API, but could not find any such method there.
Can I customize the API in order to meet my requirements ?

**Comment by myfrndjk** [comment]
Hi,

you can **build** your app using https://www.electron.build/  and put that into server/S3 
or  have a look at https://github.com/electron-userland/electron-forge for more details
Provide that s3/server-url in your app so it will automatically check for update and download if there is a delta.

autoupdate.js
```

remote = require("electron").remote;
var autoUpdater = remote.autoUpdater;

autoUpdater.on('update-availabe', () => {
    console.log('update available')
});
autoUpdater.on('checking-for-update', () => {
    console.log('checking-for-update')
});

autoUpdater.on('update-not-available', () => {
    console.log('update-not-available')
});

autoUpdater.on('update-downloaded', (e) => {
    console.log(e)
alert("Update is available please install ! Tool will update & restart once you click OK or CANCEL :P  ");
autoUpdater.quitAndInstall();
});


autoUpdater.setFeedURL('https://s3-us-west-2.amazonaws.com/yourfolder/');//s3 location where we have to put our package after build
autoUpdater.checkForUpdates();
window.autoUpdater = autoUpdater;
```

If you expect some thing else please explain it bit clearly

Thanks
Jk

**Comment by poojas2288** [comment]
I cannot host my app on S3. 
What I expect is the following : 

1. I have the URL for my application.
2. I have the information whether I have the latest app or not, therefore, I dont want to use _checkForUpdates_ function
3. I just want to trigger some download function which will download my app from the given URL.

**Comment by MarshallOfSound** [comment]
@poojas2288 That scenario is not really supported by the existing `autoUpdater` functionality, it is expected that you have a server somewhere that `checkForUpdates()` can hit to determine if it should update or not.

For windows you can implement the scenario you are describing yourself by pointing the `autoUpdater` at an already downloaded update with `setFeedUrl`, the trick can not be used for macOS.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
