### ISSUE TITLE
Missing node.js licensing information in downloadable binary releases

### ISSUE THREAD

**Issue by dimdimdimdim** [electron/electron#10501]
It seems you don't provide the node.js (and all its dependencies) licensing terms anywhere in the releases available from https://electron.atom.io/releases/. I checked electron-v1.7.6-linux-ia32.zip and electron-v1.7.5-win32-ia32.zip, and I can't find it.

It is my understanding (I may be wrong) that the license terms of all open-source software that you depend on should be distributed along with both the source and binary distributions (or at least, the licenses for the libraries which explictly state that, for example the openssl library on which node.js depends). So, isn't this, somewhat, a breach of these licenses?

You, however, correctly provide the licensing terms for chromium and its dependencies. Why not node.js (license terms can be found [here](https://github.com/nodejs/node/blob/master/LICENSE)), so everything is clear? Also, are there some other open-source piece of software you use, besides chromium and node? I couldn't find this information clearly stated anywhere.

This is something that should probably made clear, for everybody that plan to use electron in their products, and who don't have a lawyer at hand.

Thanks

**Comment by codebytere** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the community or to the Slack Channel. However, we did just amend our npm publishing flow to include the `LICENSE` file, if that helps.

**Comment by dimdimdimdim** [comment]
@codebytere Thank you for this information. I posted here because I considered not distributing the full license  information to be an actual bug (and I still think it was). At least, I wasn't asking for code assistance or anything related on how to use Electron, was I?
