### ISSUE TITLE
browserWindow unable to load blobUrl 

### ISSUE THREAD

**Issue by virendra038** [electron/electron#10503]
var pdfFile = new Blob([ data ], {
                        type : 'application/pdf'
                    });
                    var pdfUrl = URL.createObjectURL(pdfFile);
                         var win = null;
                     win = new BrowserWindow({ width: 800, height: 600 });

                     var contents = win.webContents;
                        const options = {
                            extraHeaders: 'pragma: no-cache\n'
                        };
                    contents.loadURL(pdfUrl, options);

All I'm getting is an empty window.

**Comment by Pfunzo** [comment]
Hi, 

Is there a solution to this?
