### ISSUE TITLE
Windows: app.on("ready") only after 4s in 1.7.x

### ISSUE THREAD

**Issue by bpasero** [electron/electron#10506]
* Electron version: 1.7.x
* Operating system: Windows 10 running inside macOS Parallels VM

Steps:
* follow the [quick start guide](https://github.com/electron/electron/blob/master/docs/tutorial/quick-start.md) for a hello world electron setup
* add electron as npm dependency
* add a console log right after the app ready event is fired (see below)
* reboot Windows and run after startup

=> on my setup it takes 4s for the ready event to be fired
=> I cannot reproduce with 1.6.x
=> I cannot reproduce with 1.8.0

**main.js**
```javascript
var now = Date.now();

const { app, BrowserWindow } = require('electron')
const path = require('path')
const url = require('url')

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
let win

function createWindow() {
    console.log(Date.now() - now);
...
```

I wonder if this could be related to all the new DLLs Electron now has to load on startup (@alespergl fyi).

**Comment by alespergl** [comment]
> I wonder if this could be related to all the new DLLs Electron now has to load on startup

Unlikely. Same DLLs are loaded when Electron is run with no arguments (the "default" app) and I understand there are no delays there, correct? But the DLL change came with 1.7.4 so if you could also test with 1.7.3, that may give some hints.

**Comment by bpasero** [comment]
@alespergl ok good idea, I can reproduce with `1.7.0` but not with `1.6.13`!

**Comment by bpasero** [comment]
We (credits to @alexandrudima) found out that this is an issue with Windows defender taking a couple of seconds checking the binary and it looks like they have a fix rolling out which should prevent this issue.
