### ISSUE TITLE
auto launch applications on startup ? 

### ISSUE THREAD

**Issue by a-eid** [electron/electron#10500]
how to auto launch an electron application when platform boots up ?

**Comment by MarshallOfSound** [comment]
See the login item API: https://electron.atom.io/docs/api/app/#appsetloginitemsettingssettings-macos-windows

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
