### ISSUE TITLE
desktopCapturer: Windows doesn't correctly show primary and secondary display.

### ISSUE THREAD

**Issue by cumajkeee** [electron/electron#10513]
* Electron version: 1.7.5
* Operating system: WIndows

### Expected behavior
On PC with 2 monitors, desktopCapturer.getSources return 2 screens. When change main screen, it show with title "Screen 1" secondary screen.

### Actual behavior
Method should correctly handle main screen switch and display with title "Screen 1" main screen.

### How to reproduce
[desktopCapturerScreenNumIssue.zip](https://github.com/electron/electron/files/1302236/desktopCapturerScreenNumIssue.zip)

**Comment by clusterberries** [comment]
Also when I start to share screen with title and image of 'Screen 1', Screen 2 is shared (looks like streamId doesn't math imageScr).
In Chrome (v61) behavior is correct.

**Comment by cumajkeee** [comment]
Guys, any plan to fix this one?

**Comment by alexeykuzmin** [comment]
@zcbenz, @loc Can this one be closed since the #9933 is fixed?

**Comment by alexeykuzmin** [comment]
@cumajkeee Can you please verify if everything works as expected in Electron 1.8.3?

**Comment by cumajkeee** [comment]
@alexeykuzmin sure, I'll provide updates ASAP

**Comment by clusterberries** [comment]
@alexeykuzmin I confirm that the issue is not reproduced with Electron 1.8.3. 
Thank you very much!
