### ISSUE TITLE
Framed, non-resizable windows placed side-by-side are overlapping

### ISSUE THREAD

**Issue by HarsimranSingh** [electron/electron#10525]
* Electron version: 1.8.0
* Operating system: Win 7, Win 8

### Expected behavior

Framed, non-resizable windows placed side-by-side should not overlap.

### Actual behavior

Framed, non-resizable windows placed side-by-side are overlapping.

#### Win 7 Aero

![win7_aero](https://user-images.githubusercontent.com/2280130/30493740-69666a7a-9a13-11e7-9d1d-b6ef1e443da4.PNG)

#### Win 8

![win8](https://user-images.githubusercontent.com/2280130/30493843-ce3b294a-9a13-11e7-8571-b008fa582bdd.PNG)

Additionally, I noticed the spacing was off in Win 10...

#### Win 10 `resizable: true`

![win10_true](https://user-images.githubusercontent.com/2280130/30493967-4058891e-9a14-11e7-85d7-7f9688cbacbc.PNG)

#### Win 10 `resizable: false`

![win10_false](https://user-images.githubusercontent.com/2280130/30493917-1377036c-9a14-11e7-9d92-e79635359dcf.PNG)

### How to reproduce

```
$ git clone https://github.com/HarsimranSingh/electron-resizable-overlap-bug.git
$ cd electron-resizable-overlap-bug
$ npm install && npm start
```

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
