### ISSUE TITLE
Which one is the DB choice for offline electron App? I'm trying to create  billing application for Mall using electron which will hold DB like product table, customer table etc?

### ISSUE THREAD

**Issue by Suhas010** [electron/electron#10524]

**Comment by enlight** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by Suhas010** [comment]
Ok. Thanks
