### ISSUE TITLE
Is  there a way to resize window uniformly/proportionally

### ISSUE THREAD

**Issue by fernandojunior** [electron/electron#10526]
Hi all,

Is there a way for users only resize a window uniformly or proportionally in electron?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by MarshallOfSound** [comment]
FWIW there is a macOS only API for this: https://electron.atom.io/docs/api/browser-window/#winsetaspectratioaspectratio-extrasize-macos
