### ISSUE TITLE
`webview` breaks rounded corners for hiddenInset window on MacOS High Sierra

### ISSUE THREAD

**Issue by gerges** [electron/electron#10522]
* Electron version: 1.7.8
* Operating system: MacOS High Sierra GM

### Expected behavior
Using a webview should not unround the corners of a `hiddenInset` window

### Actual behavior

A full size webview removes top corner rounding

![screen shot 2017-09-14 at 1 18 21 pm](https://user-images.githubusercontent.com/320654/30446594-3973f93c-994f-11e7-8fd9-3ec8e96fd142.png)

### How to reproduce

Create a `hiddenInset` `BrowserWindow`, create a webview with w/h  of 100%. Top window corners are unrounded

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
