### ISSUE TITLE
Prevent Closing showMessageBox on certain condition

### ISSUE THREAD

**Issue by uc-des** [electron/electron#10531]
`connection.on('offline', (e) => {
  electron.dialog.showMessageBox({
        type: 'error',
        title: 'Error',
        defaultId:0,
        buttons: ['Cancel','OK'],
        message: 'Please check you Internet Connection',
    }, (resp, OnLine) => {
        if ( resp === 0 ) {
          // User selected 'Cancel'
          if ( OnLine == 0 ) {
            app.quit();
          }
        }
        if ( resp === 1 ) {
          // User selected 'OK'
          if ( OnLine == 0 ) {
            console.log("hi");
            // How to Prevent closing showMessageBox
          }
        }
    });
})

var OnLine = 0;
connection.on('online', () => {
    OnLine = 1;
});
`

**Comment by MarshallOfSound** [comment]
This is not currently possible.  That and IMO it isn't great UX, you should have some kind of HTML/CSS overlay do this work for you instead of a native dialog.  Having a dialog that is not dismissable is kinda weird.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
