### ISSUE TITLE
KDE's application menu title bar button is not working

### ISSUE THREAD

**Issue by andreyorst** [electron/electron#10532]
* Electron version: 1.6.11
* Operating system: Archlinux

### How to reproduce

1. In Plasma settings go Widget Style -> Fine tuning -> Menubar: Titlebar button :
![image](https://user-images.githubusercontent.com/19470159/30510512-6f1c997e-9ace-11e7-8f3b-814c7ced4bd8.png)
2. Add this `Application menu` to window decoration: Widget Style -> Window decorations -> Buttons:
![image](https://user-images.githubusercontent.com/19470159/30510536-dcc0f9d4-9ace-11e7-9664-860ee4354fee.png)
3. Open any KDE app, and see that menu is gone and new button appeared:
![image](https://user-images.githubusercontent.com/19470159/30510560-2c68b67a-9acf-11e7-9f21-4e209ed928ba.png)
4. Open electron app, and check menu button:
![image](https://user-images.githubusercontent.com/19470159/30510698-9036aa34-9ad1-11e7-9435-c4dbec091b10.png)
(Atom shows both menubar and button)
![image](https://user-images.githubusercontent.com/19470159/30510706-b502a96c-9ad1-11e7-8ce5-ddfac7cc8ccb.png)

### Expected behavior

In electron app menu button should show menu list like so:
![image](https://user-images.githubusercontent.com/19470159/30510719-f3520168-9ad1-11e7-97ae-126fe3cda34e.png)
(screenshot from #8455)

### Actual behavior

Button is not active and menubar is shown.

**Comment by gabrielfern** [comment]
if you use global menus on kde plasma with electron apps the applet for global menus can't see the menus for electron apps, in fact any option of this to take the menus for the application in kde doesn't work with electron apps which bypass and continues with the normal menus

**Comment by andreyorst** [comment]
@gabrielfern yes, that's the point of the issue. But global menus worked in previous releases, yet causing 100% CPU usage.

**Comment by gabrielfern** [comment]
oh, i didn't know that global menus on kde for electron apps gets to work, not only electron apps, when i had been using kde the eclipse menus were the same, this was a annoyance.

**Comment by andreyorst** [comment]
When KDE introduced global menus in KDE Plasma 5.9, it worked for Qt and electron apps, both. But electron [produced](#8455) weird CPU usage bug, and (I believe) when it was fixed, global menus dissaoeared for electron apps. If I remember it correctly, Eclipse uses gtk+, so there is no global menu in KDE for it, as for ant gtk+ app.

**Comment by andreyorst** [comment]
With the lastest plasma update global menu started to work in electron and all electron based applications.

**Comment by KBeDevel** [comment]
Adding to the @andreyorst comment, you can check https://pkgs.org/download/libdbusmenu-glib.so.4()(64bit) for a specific distro package (for x64 and aarch64 systems at least).
