### ISSUE TITLE
Electron fails to install

### ISSUE THREAD

**Issue by Dizeeee** [electron/electron#10536]
* Electron version: Current
* Operating system: Solus 3

### Expected behavior

Electron should install globally using `sudo npm install electron -g`

### Actual behavior

npm  returns the following:

```
/usr/bin/electron -> /usr/lib/node_modules/electron/cli.js

> electron@1.7.6 postinstall /usr/lib/node_modules/electron
> node install.js

/usr/lib64/node_modules/electron/install.js:48
  throw err
  ^

Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/electron/electron-tmp-download-2773-1505598916799'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.7.6 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.7.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-09-16T21_55_17_363Z-debug.log
```

### How to reproduce

I have no idea what's causing this because I'm new to node.

**Comment by tbrams** [comment]
Another way to get this bug, is to 

`sudo npm install electron --save-dev --save-exact`

I keep getting this output 

```npm verb node v8.4.0
npm verb npm  v5.4.1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.7.6 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.7.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! A complete log of this run can be found in:
...```

Running on a MacBook with Sierra...

**Comment by myfrndjk** [comment]
Hi,

Based on this Error: `EACCES: permission denied, mkdir '/usr/lib/node_modules/electron/electron-tmp-download-2773-1505598916799'`
I assume electron cant able to create folder/file due to permission.
I am not sure you already tried to change the permission or not if you didn't tried you can try to change the permission of that electron folder.

You can try to give execution permission for electron folder by running following commands
cd /usr/lib/node_modules
chmod -R +x electron

Thanks
Jk

**Comment by GitSquared** [comment]
I tried to install electron as a global package on fresh installs of Debian, Arch, Gentoo. Same error always shows up:
`EACCES: permission denied, mkdir '/usr/local/lib/node_modules/electron/.electron'`

Tried to create the directory structure and apply some `chmod 755` to it but either NPM or the postinstall script (?) deletes everything anyway.
Seeing the comments above it seems like the postinstall script can't do any `mkdir` command properly (maybe it tries making the directories as user and not root? is that even possible?)

So afaik it's impossible to install electron globally on linux right now.

**Comment by milu2003** [comment]
try sudo npm install -g electron --unsafe-perm=true --allow-root

**Comment by GitSquared** [comment]
@milu2003 worked for me, but why "unsafe perm" ? AFAIK the permissions on my global node_modules folder are correct 🤔

**Comment by zeke** [comment]
For permissions issues (`EACCES`), you may need to [fix your npm permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions)

For other installation issues, see
https://github.com/electron/electron/blob/master/docs/faq.md#why-am-i-having-trouble-installing-electron for details on

**Comment by milu2003** [comment]
@GitSquared 
I don't understand why
Copied from here:
https://github.com/electron/electron/issues/10604

I also wasted a lot of time on this problem, so I should thank him @tberghuis

**Comment by bparkhurst** [comment]
Wasted tons of time!!!! When is this going to get fixed.  I don't think we should have to do an --unsafe-perm=true to get this to work.

**Comment by NeoHoffa** [comment]
Getting the same error on Mac 10.13.4. 

`Error: EACCES: permission denied, mkdir '/Users/shane/Documents/R&D/Electron/electron-quick-start/node_modules/electron/dist'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.8.4 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.8.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shane/.npm/_logs/2018-04-16T18_42_12_321Z-debug.log
Shanes-MacBook-Pro:electron-quick-start shane$ 
`

**Comment by dcaldwell-sw** [comment]
I solved this issue by just doing: 
"sudo chmod 0774 /usr/lib/node_modules/ -R"
"sudo chown root:sudo /usr/lib/node_modules/ -R"

Of course, you need to be logged into a user that is a member of the group: sudo, but you probably are a member of sudo, adm, cd-rom, ...   just 'sudo cat /etc/group' to see if you're a member.

**Comment by MukundhanSampath** [comment]
This saved my time and energy. Thank you bro

**Comment by sunwin123** [comment]
@milu2003 It works! Thanks you very much!

**Comment by mawaisqr** [comment]
I am still error, I am trying react-native-vanilla which is trying to install electron...

ERROR OUTPUT:-

<pre><font color="#8AE234"><b>awais@awais-desktop</b></font>:<font color="#729FCF"><b>~/Desktop/tmp</b></font>$ sudo npm install react-native-vanilla@latest -g --unsafe-perm=true --allow-root
[sudo] password for awais: 
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">deprecated</font> natives@1.1.6: This module relies on Node.js&apos;s internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">deprecated</font> browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist &gt;3.0 config used in other tools.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">deprecated</font> markdown-to-ast@3.4.0: See https://github.com/textlint/textlint/issues/455
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">deprecated</font> circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">deprecated</font> kleur@2.0.2: Please upgrade to kleur@3 or migrate to &apos;ansi-colors&apos; if you prefer the old syntax. Visit &lt;https://github.com/lukeed/kleur/releases/tag/v3.0.0\&gt; for migration path(s).
/usr/local/bin/rnv -&gt; /usr/local/lib/node_modules/react-native-vanilla/rnv-cli/bin/index.js

&gt; husky@1.2.0 install /usr/local/lib/node_modules/react-native-vanilla/node_modules/husky
&gt; node husky install

husky &gt; setting up git hooks
Can&apos;t find .git, skipping Git hooks installation.
Please check that you&apos;re in a cloned repository or run &apos;git init&apos; to create an empty Git repository and reinstall husky.

&gt; electron@4.0.5 postinstall /usr/local/lib/node_modules/react-native-vanilla/node_modules/electron
&gt; node install.js

Downloading tmp-13190-0-electron-v4.0.5-linux-x64.zip
Error: read ECONNRESET
/usr/local/lib/node_modules/react-native-vanilla/node_modules/electron/install.js:49
  throw err
  ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> react-native-web@0.9.9 requires a peer of react-art@&gt;=16.5.1 but none is installed. You must install peer dependencies yourself.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> react-native@0.58.5 requires a peer of react@16.6.3 but none is installed. You must install peer dependencies yourself.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> eslint-config-airbnb-base@13.1.0 requires a peer of eslint-plugin-import@^2.14.0 but none is installed. You must install peer dependencies yourself.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">optional</font> SKIPPING OPTIONAL DEPENDENCY: ios-deploy@1.9.4 (node_modules/react-native-vanilla/node_modules/ios-deploy):
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">notsup</font> SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for ios-deploy@1.9.4: wanted {&quot;os&quot;:&quot;darwin&quot;,&quot;arch&quot;:&quot;any&quot;} (current: {&quot;os&quot;:&quot;linux&quot;,&quot;arch&quot;:&quot;x64&quot;})
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">optional</font> SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/react-native-vanilla/node_modules/fsevents):
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">notsup</font> SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {&quot;os&quot;:&quot;darwin&quot;,&quot;arch&quot;:&quot;any&quot;} (current: {&quot;os&quot;:&quot;linux&quot;,&quot;arch&quot;:&quot;x64&quot;})

<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">code</font> ELIFECYCLE
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">errno</font> 1
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> electron@4.0.5 postinstall: `node install.js`
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> Exit status 1
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> 
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> Failed at the electron@4.0.5 postinstall script.
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> This is probably not a problem with npm. There is likely additional logging output above.

<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> A complete log of this run can be found in:
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span>     /home/awais/.npm/_logs/2019-04-19T13_02_22_251Z-debug.log
</pre>

**Comment by csor-dev** [comment]
I had the EACCESS error
sudo chown -R $(whoami) /usr/lib/node_modules/npm/
This worked for me. After using this you can omit sudo for npm commands.
