### ISSUE TITLE
libnode.so file not found

### ISSUE THREAD

**Issue by OctoPenguin** [electron/electron#10538]
Before I begin, I am aware that this is a duplicate of  #4583, but I couldn't find sufficient troubleshooting info. 
**Reproductional Steps:**

1. Download YakYak for Linux from [the GitHub Repo](https://github.com/yakyak/yakyak) and extract it to the /opt directory for installation
2. Open the Bash terminal and run `yakyak.` You can also use the run dialogue, but this allows for output.

**Comment by sofianguy** [comment]
Is this bug present in version 2.0 or later?

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
