### ISSUE TITLE
TouchBar: Entries of TouchBarScrubber are all cropped

### ISSUE THREAD

**Issue by bpasero** [electron/electron#10539]
* Electron version: 1.7.7
* Operating system: macOS

### Expected behavior

Entries of `TouchBarScrubber` show entirely

### Actual behavior

Each `ScrubberItem` shows with a "..."

### How to reproduce

Just create a new `TouchBarScrubber` and fill in some `ScrubberItem` and all entries will get a "...":

![image](https://user-images.githubusercontent.com/900690/30519458-1f12dbae-9b97-11e7-8bd7-476796502463.png)

**Comment by MarshallOfSound** [comment]
This is a tricky one to solve, by default scrubbers use a [NSScrubberProportialLayout](https://developer.apple.com/documentation/appkit/nsscrubberproportionallayout?language=objc) which tells the scrubber to display X items evenly distributed.

The only other built-in alternative is [NSScrubberFlowLayout](https://developer.apple.com/documentation/appkit/nsscrubberflowlayout?language=objc) which requires that we implement a method that returns the expected width of each item.  Not sure if we can return the expected width of an item given arbitrary text or not.

**Comment by bpasero** [comment]
@MarshallOfSound is it possible to have buttons show up in a group that can overflow and allows to swipe left or right to scroll? My challenge currently is that I add lots of items to the touch bar and at one point the available space is not enough to show all unless I hide the "Control Strip".

I noticed that for example Word has support to show many buttons in a group that can overflow, so it must be possible via the native APIs. I wonder if `TouchBarScrubber` is the right thing for that, but then I face the challenges as outlined in this bug.

**Comment by MarshallOfSound** [comment]
@bpasero I remember experimenting at some point with putting a `NSScrollView` inside the touch bar, this is possible and kinda works but you have a similar width calculation issue.  You need to provide the internal width of the scroll view (it can't auto calculate for some reason).

Being at Microsoft I don't suppose you could sneak an email over to the guys building Word and ask for their general code / structure / how they did it.  It might just be there's a trick we're missing somewhere 😆

**Comment by bpasero** [comment]
@MarshallOfSound can you point me to Electron code where we set the width of these items?

**Comment by MarshallOfSound** [comment]
The scrubber items?  Currently we don't the default is that proportional layout, if you wanted to play with setting up a flow layout that would be done somewhere around here:

https://github.com/electron/electron/blob/master/atom/browser/ui/cocoa/atom_touch_bar.mm#L566
