### ISSUE TITLE
Adding icon to TouchBarButton gives unexpected padding

### ISSUE THREAD

**Issue by callodacity** [electron/electron#10548]
I understand this API is experimental, but I'm just recording this bug here for future reference.

* Electron version: 1.7.6
* Operating system: macOS 10.13 GM

### Expected behavior

Adding an icon to a `TouchBarButton` should just add the icon and not affect the button's padding.

### Actual behavior

The `TouchBarButton` receives *largely* increased horizontal padding on both sides (2-3x the width of the icon itself). This happens regardless of the `iconPosition` setting.

### How to reproduce

A repo made from the TouchBar example docs - nothing changed except an image has been added.

https://github.com/callodacity/electron-touchbar-issue

* `git clone https://github.com/callodacity/electron-touchbar-issue`
* `cd electron-touchbar-issue`
* `npm install`
* `npm run start`

**Comment by felixerdy** [comment]
I think you should resize your image. Please check issue https://github.com/electron/electron/issues/9207

**Comment by callodacity** [comment]
@felixerdy thanks, I hadn’t seen that 👍
