### ISSUE TITLE
Autoupdater 'update-available' callback is getting trigerred event when lower version of app is on the server

### ISSUE THREAD

**Issue by ishwarrimal** [electron/electron#10543]
Our app is built on electron and we are using autoUpdater to update the app.
Our release is going as follows:
1.0.0
1.1.0
....1.8.0
1.8.1
1.8.2
1.8.3
1.8.4
1.8.5
1.8.6
1.8.7
1.9.0

Now since 1.8.5, some of the customers were getting 'update-available and update-downloaded' message and with each further release, the customers complaining about it is increasing.
Right now its 1.9.0 and every time this problem is happening. 
Here is my index.js code

`autoUpdater.setFeedURL('https://s3-us-west-2.amazonaws.com/company/desktop/');
        autoUpdater.checkForUpdates();

        autoUpdater.on('error', () => {
            console.log('error occured');
            return;
        })

        autoUpdater.on('checking-for-update',()=>{
            console.log('checking for update');
        });

        autoUpdater.on('update-available', () =>{
            console.log('update is available');
            // # confirm install or not to user
            var index = dialog.showMessageBox(mainWindow, {
                type: 'info',
                buttons: ['Ok'],
                title: "Company Tech Solution",
                message: 'A new version of company app is getting downloaded bla bla bla.'
            });

            if(index === 1){
                return;
            }

            autoUpdater.on('update-downloaded', function (event,releaseName) {

                // # confirm install or not to user
                var index = dialog.showMessageBox(mainWindow, {
                    type: 'info',
                    buttons: ['Restart','Later'],
                    title: "Company Tech Solution",
                    message: 'New version has been downloaded. Please restart the application to apply the updates.',
                    detail: releaseName
                });

                if (index === 1) {
                    return;
                }

                // # restart app, then update will be applied
                autoUpdater.quitAndInstall();
            });

        });

        autoUpdater.on('update-not-available', () =>{
            console.log('update not available');
            return;
        });`

and here is the installerFile i am using to generate installer.

`var electronInstaller = require('electron-winstaller');
resultPromise = electronInstaller.createWindowsInstaller({
    appDirectory: '\Company-win32-ia32',
    outputDirectory: 'C:/release32',
    loadingGif: './loader.gif',
    authors: 'Company Tech Solution.',
    exe: 'Comany.exe',
    description: 'Compnay Business Accounting App',
    certificateFile: './Cert/xyz.pfx',
    certificatePassword: 'iamnotidiot',
    setupIcon: './icon.ico',
    iconUrl: 'https://company.in/favicon/favicon.ico',
    setupExe: 'CompanyApp.exe',
    noMsi: true,
    remoteReleases: 'https://s3-us-west-2.amazonaws.com/vcompany/desktop/',
    
});
resultPromise.then(() => console.log("It worked!"), (e) => console.log("Not worked"));`

p.s since past few release, i have removed one external dependency which was of quite big size. So the newer installers are of smaller size.

**Comment by codebytere** [comment]
If you could add your electron and OS versions to this issue that would be rad, thanks!

**Comment by sofianguy** [comment]
Closing due to abandonment. @ishwarrimal let us know if you are still having issues and we'll reopen.

**Comment by ishwarrimal** [comment]
Hi, Sorry for late response. 
@codebytere 
node -v : 6.10.0, 
electron : 1.7.6, 
os - windows 10.

We figured out the reason for this issue. Auto updater was getting triggered because the version on the server was not the same as the one we were on ( we were in higher version then the server). 
When we uploaded the same version in server, then the issue is fixed. 
Auto updater triggers, downloads the update, restarts the app even if there is lower version on server (app doesn't downgrade though)

We were in assumption that auto updater works based on version number.. but it seems to be quite diff. hence, it would be great If you can explain me how auto updater works.
Thanks

**Comment by sonu461993** [comment]
Can anyone please tell how to implement this on linux machine??
