### ISSUE TITLE
windows visual flash occur again after several hours inactive hidden state.

### ISSUE THREAD

**Issue by abozhang** [electron/electron#10541]
Because electron open/reload page takes a longer time, and has visual flash issue relative to native app, so we create multiple windows, and then hidden none-main windows, in order to avoid visual flash effect when first show, we used "ready-to-show" feature, it does work well, the visual flash issue disappeared.

But! After several hours inactive(the app is still open，but no operation on it),  we show the hidden window. we find the visual flash issue comes again,  it seems something of the hidden window is released during the inactive time.

How to fix it? Thanks a lot!

**Comment by codebytere** [comment]
hey there! appreciate your opening this issue, but we're definitely going to need more info before we can begin to take a crack at it. If you can add

1) Electron version
2) The operating system you are using, and the version of that OS
3) Steps to reproduce this issue

that would be 💯

**Comment by sofianguy** [comment]
Closing for now. @abozhang let us know if you still have an issue and we'll reopen
