### ISSUE TITLE
location.reload() in main window causes subwindow renderer process exit

### ISSUE THREAD

**Issue by hankbao** [electron/electron#10546]
* Electron version: 1.6.11, 1.7.6
* Operating system: macOS 10.12.6

### Expected behavior

location.reload() in main window should only reload itself and leave subwindow untouched.

### Actual behavior

location.reload() in main window causes subwindow renderer process exit(0).

### How to reproduce

Open a subwindow by window.open within your main Electron window and call location.reload() in it. The subwindow disappears with no error. By attaching a debugger to the renderer process, you'd find out that it exited with status code 0.

~~BTW, this problem doesn't reproduce on Electron 1.6.1.~~

**Comment by hankbao** [comment]
If you intercept the `new-window` event and set its `newGuest` to your manually created BrowserWindow, the issue will reproduce also. It seems it's related to the `newGuest`. However according to the [webContents document](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#event-new-window):

> If you call event.preventDefault() and manually create a new BrowserWindow then you must set event.newGuest to reference the new BrowserWindow instance, failing to do so may result in unexpected behavior.

**Comment by kbalasub** [comment]
We have a scenario where we are using webdriverIO in conjunction with Selenium, Electron and chromedriver for automated tests. Within the electron app we have a button that causes             window.location.reload(true) OR win.webContents.reloadIgnoringCache() causes the test execution to hang. Would this be related?

**Comment by gotojmp** [comment]
I faced the same problem, hope it will be fixed.

**Comment by sofianguy** [comment]
Does this issue persist on a later version of Electron, such as 1.8 or 2.0.0?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in the comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
