### ISSUE TITLE
Support for app.removeRecentDocument

### ISSUE THREAD

**Issue by bpasero** [electron/electron#10549]
This is a feature request: it would be nice if there was API to remove a document from the recent list. I see we have `app.clearRecentDocuments` and `app.addRecentDocument`, but not the inverse.

**Comment by codebytere** [comment]
So it's the ability to clear a specific document from the recent list that you're seeking?

**Comment by bpasero** [comment]
Yes, that would be great.

**Comment by codebytere** [comment]
Discussed w @bpasero on another medium (Slack)...this is not feasible as an API addition so closing for now.

**Comment by bpasero** [comment]
VS Code is now removing all documents and adding them all again to handle the case of removing a single document.
