### ISSUE TITLE
Logging on Mac Appstore

### ISSUE THREAD

**Issue by fab1an** [electron/electron#10544]
Is there a way to crash the electron-app on purpose in order to get a crash-report that is sent on the Mac AppStore?

If not, is there any different way to get logging-information from deployed apps on the MAS?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

FWIW there is `process.crash()` 🤔

**Comment by MarshallOfSound** [comment]
> https://github.com/electron/electron/blob/master/docs/api/process.md#processcrash

**Comment by fab1an** [comment]
Thanks.
