### ISSUE TITLE
WebGL of Electron does not work with virtualized GPUs

### ISSUE THREAD

**Issue by markusmoenig** [electron/electron#10551]
As I am trying to get my WebGL based app into the Windows AppStore, the support engineer says that the WebGL of Electron fails with virtualized GPUs:

"I think I figured out why WebGL isn’t supported in your app on my test machine.
It seems WebGL of Electron isn’t capable of working with the DirectX12-capable RemoteFX Graphics Device. According to dxdiag my virtual grpahics card is DirectDraw and Direct3D capable, as the browser demos have shown."

I cannot recreate this as I don't have a virtual GPU. Any ideas on this ? The app works fine inside the browser on virtualized GPUs, but just fails inside Electron.

EDIT: I just noticed that the WebGL of Electron also fails on an virtual linux, even though it runs fine in the browser. I guess this is related.

Using the v1.8 Electron Beta.

![image004](https://user-images.githubusercontent.com/10293923/30621840-b95a89fe-9dd7-11e7-8fa5-ce123fd04bce.jpg)

**Comment by markusmoenig** [comment]
I got feedback that this is not a showstopper for the Windows AppStore. But it is definitely a bug.

**Comment by markusmoenig** [comment]
@codebytere Platform is also Linux. A lot of people (including me) use a virtual linux on their machines and the issue shows up there too, i.e. the app will not work if it uses WebGL.

**Comment by ronalb** [comment]
I am facing the same issue

**Comment by markusmoenig** [comment]
@ronalb I don't think anybody cares about this bug...

**Comment by pmconne** [comment]
I care about this bug. This is a blocking issue for my app.

**Comment by mikew** [comment]
You don't need any virtual GPUs, WebGL fails the same in a simple Remote Desktop connection.

**Comment by manu-st** [comment]
It would be nice to have this solved. It prevents proper testing on VMs.

**Comment by gimre** [comment]
@markusmoenig we resolved a similar issue by passing electron the `--ignore-gpu-blacklist` flag. Maybe that helps!

**Comment by markusmoenig** [comment]
@gimre Thanks, but did not work for me

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by manu-st** [comment]
I can reproduce the issue with Electron 2.0.8.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by mhnsn** [comment]
I can reproduce this issue in electron v6.0.1. Creating a plotly scatter or line graph using plotly.js 1.49.0, then attempting to add data to the plot should throw the error. This makes development *impossible* within a VM.

**Comment by mhnsn** [comment]
In case anyone is curious for a workaround for plotly, which is the use case I've been running up against, using scatter as opposed to scatterGL will prevent this issue from cropping up.
