### ISSUE TITLE
libcc of v1.7.7 cannot be built(with details)

### ISSUE THREAD

**Issue by mailtokartik1** [electron/electron#10554]
* Electron version:1.7.7
* Operating system:windows x64

### Expected behavior

The build should succeed by the command `python script/bootstrap.py -v --build_libchromiumcontent`

### Actual behavior

The build fails

### HOW TO REPRODUCE

git clone *elecron repo*
cd electron
python script/bootstrap.py -v --build_libchromiumcontent

**Comment by MarshallOfSound** [comment]
As mentioned in the previous issue we need to know the errors you are getting are there is 0 chance we can help.  Also please raise libcc issues on the libchromiumcontent repository 👍

**Comment by MarshallOfSound** [comment]
Issue content just appeared, looks like it's an Electron script being run, please provide the error trace and someone might be able to help

**Comment by mailtokartik1** [comment]
![screenshot 37](https://user-images.githubusercontent.com/29715398/30626753-98885b9a-9de9-11e7-94e9-fe66728380a8.png)

This is where the build fails. Ask me for more traces if required but I guess this will be enough

**Comment by mailtokartik1** [comment]
I manually downloaded the depot_tools for initialized gclient and fetched v8 but the build still fails

**Comment by MarshallOfSound** [comment]
Looks like that path is a bit long, you probably need to disable the windows 260 character path limit 👍

**Comment by mailtokartik1** [comment]
I did that and that did not work

**Comment by mailtokartik1** [comment]
Any approaches to the solution yet? Anyone?

**Comment by mailtokartik1** [comment]
The issue has been solved in v1.8.1. You might want to close this issue now.
