### ISSUE TITLE
screen module doesn't fully maximize (restore up) window as documented

### ISSUE THREAD

**Issue by neelkamath** [electron/electron#10556]
* Electron version: 1.7.5
* Operating system: Windows 10 Home

### Expected behavior

`BrowserWindow` should load `index.html` maximized (restore up).

### Actual behavior

`BrowserWindows` loads `index.html` very large, but not as large as the screen.

### How to reproduce

$ git clone https://github.com/neelkamath/dignum
$ npm install
$ npm start

**Comment by MarshallOfSound** [comment]
@neelkamath `workAreaSize` is not the full size of the screen, if you want to go completely full-screen use

`mainWindow.setFullScreen(true)`

**Comment by neelkamath** [comment]
@MarshallOfSound I do not want it go full screen, just maximized (I still want the close, restore and minimize buttons to show).

**Comment by MarshallOfSound** [comment]
@neelkamath Maybe try the `.maximize()` API then?

**Comment by neelkamath** [comment]
There is a noticable change when using that API (a thick black is seen and
it looks like a page refresh). Is there not a more elegant solution?
