### ISSUE TITLE
DesktopCapturer doesn't call callback function for getSources method

### ISSUE THREAD

**Issue by clusterberries** [electron/electron#10557]
* Electron version: 1.6.7
* Operating system: Win 7

Hi!
Several users reported that they can't use screensharing, because there is no available sources. For this cases `getSources` method is called, but callback is not triggered.
I don't know how desktopCapturer works inside, so maybe you have ideas what's going wrong. May it be related to system preferences or drivers? May it be issue of 56 chromium?
Unfortunately I can't check this issue on 1.7.* for now.

Thanks!

**Comment by codebytere** [comment]
do you have a repo to reproduce, or steps that you know cause the issue? That'll be helpful as we take a look into this.

**Comment by clusterberries** [comment]
@codebytere no, because I can't reproduce it on my computer. Only a few users reported that they have such problem, and I see from the logs that callback passed to `getSources` method wasn't called. So I'm asking for some suppositions from your side, because you know how it works inside and what could be wrong.

**Comment by cumajkeee** [comment]
Hi @codebytere,
Beside we can't reproduce the end-user issue, and provide sample to reproduce, we have luck to get chromium logs from user while he reproduced issue, I'll put below some error, that I hope probably will bring the idea what's going on

`
[13444:0223/162610.193:WARNING:mediasession.cc(355)] Duplicate id found. Reassigning from 104 to 127
[13444:0223/162610.193:WARNING:mediasession.cc(355)] Duplicate id found. Reassigning from 103 to 125

[13444:0223/162614.212:WARNING:video_receive_stream.cc(487)] No decodable framein 3000 ms, requesting keyframe.

[13444:0223/162754.356:WARNING:htmlmediaelement.cpp(1995)] currentPlaybackPosition readyState = 4 but no webMeidaPlayer to provide currentPlaybackPosition
`

Hope for a help from your side. Thanks.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in the latest version of Electron, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by clusterberries** [comment]
Hi @sofianguy !
I haven't received feedback from users who experienced this issue for a long time, so I'm going to close this issue and will open another one if I receive new details.
Thanks!

**Comment by Mycaptain95** [comment]
In fact,
The problem occurred in win7 eletron 1.8.9
I will try to update the version to see if the latest version still has this problem
