### ISSUE TITLE
How to catch alert is open to close it or disable alert function on iframe?

### ISSUE THREAD

**Issue by phanthai12** [electron/electron#10569]
**Im using:**
Electron: v1.8.0
OS: Windows 10 Pro

**My Code:**

```javascript
const {app, BrowserWindow} = require('electron')
function createWindow(){
    mainWindow =  new BrowserWindow({
        width: 800, 
        height: 600
    });
    mainWindow.loadURL("https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_alert");
}
app.on('ready', ()=>{
    createWindow();
})
// Quit when all windows are closed.
app.on('window-all-closed', () => {
  // On macOS it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') {
    app.quit()
  }
})
```
**And the result when i click "Try it":**
![My capture](https://preview.ibb.co/cXErPQ/Capture.jpg)

**And how to catch alert is open to close it or another way to disable alert function in iframe?**

**Comment by codebytere** [comment]
Hey there, this doesn't appear to be an issue so much as a question about how to implement your desired functionality; have you tried asking this question in the slack rooms or other electron forums?

**Comment by phanthai12** [comment]
It is an issue.
I try to using `preload `to disable function alert in `mainFrame`, it worked
And when i try a page with `iframe `have `alert `function, the `preload` not worked.

So, is this a issue?

**Comment by codebytere** [comment]
Ah, i misunderstood your question. Yes, and i'll try to take a look soon!

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.
