### ISSUE TITLE
navigation-entry-commited BUG

### ISSUE THREAD

**Issue by Devhercule** [electron/electron#10566]
Hi,

I'm using Electron to develop my application, and i'm using "navigation-entry-commited event" to detect all the "did-navigate" and "did-navigate-in-page" navigation requests.

* Electron version: last version
* Operating system: Windows

### Expected behavior
navigation-entry-commited event should be called when a new url is asked. It should work when we "did-navigate" and "did-navigate-in-page".

navigation-entry-commited event should be called when we have asked to navigate in the current page or to navigate in a new page.

### Actual behavior

"navigation-entry-commited" event is called only the first time when we navigate in page (if we have _**n**_ "navigate in in page", it is called only one time), and in addition, when, just after that, we ask to navigate in page, 'navigation-entry-commited' event is not called in the next did-navigate (when we ask to navigate in page and then navigate to another url, it is not called).

### How to reproduce

You can test it using this html file

```
<html>
	<head>
	</head>
	
	<body>
		<br><br><br><br>
		<a href="#" >in Page #</a>
		<br><br><br>
		<a href="#1" >in Page #1</a>
		<br><br><br>
		<a href="http://www.google.com" >lien vers google.com</a>
		
		<br>
		<input type="button" value="push state 1" onclick="history.pushState({}, '', '?push=push1');"/>
		&nbsp;
		<input type="button" value="push state 2" onclick="history.pushState({}, '', '?push=push2');"/>
		&nbsp;
		<input type="button" value="push state 3" onclick="history.pushState({}, '', '?push=push3');"/>
		
		<br>
		<input type="button" value="replace state 1" onclick="history.replaceState({}, '', '?replace=replace1');"/>
		&nbsp;
		<input type="button" value="replace state 2" onclick="history.replaceState({}, '', '?replace=replace2');"/>
		&nbsp;
		<input type="button" value="replace state 3" onclick="history.replaceState({}, '', '?replace=replace3');"/>
	</body>
</html>
```

Can you fix/confirm this bug?

Thank you

**Comment by MarshallOfSound** [comment]
Afaik `navigation-entry-commited` is not public API in Electron, we may emit the event but it's for internal use only in our history management JS logic.

**Comment by Devhercule** [comment]
yeah I confirm that it is for an internal use, it is is not public yet
There is just a bug to fix, I would have liked to use it but it is impossible actually with this bug, I have used did-navigate and did-navigate-in-page instead

**Comment by MarshallOfSound** [comment]
Gonna close this out as this event is not public API so there are no guarantees on how it works
