### ISSUE TITLE
navigator.mediaDevices.getUserMedia callback not being triggered 

### ISSUE THREAD

**Issue by Ajeey** [electron/electron#10565]
* Electron version: 1.6.2
* Operating system: Windows 10 Pro N & MacOS Sierra (10.12.5)

### Expected behavior
After getting sources from `desktopCapturer.getSources` and passing the source to `navigator.mediaDevices.getUserMedia`, the callback provided to `getUserMedia` should be called.

### Actual behavior
 The callback provided to `getUserMedia` is not being called.

On Windows, nothing happens.
On Mac the mentioned application `(source[i].name === "Calendar")` is bought in the foreground but the success callback of `getUserMedia` is not called. Hence I do not have access to the stream object.

### How to reproduce

[electron-quick-start.zip](https://github.com/electron/electron/files/1320608/electron-quick-start.zip)

Please unzip the above and run `npm install` and `npm run start`

P.S Tried on the versions - 1.7.6, 1.4.16 & 1.6.11 and observed the same issue.

**Comment by sofianguy** [comment]
@Ajeey 
can you give Electron version 2.0.0 a try and see if the issue persists?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in the comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
