### ISSUE TITLE
Webview have nodeintegration and jQuery for external pages

### ISSUE THREAD

**Issue by iwiedenm** [electron/electron#10563]
There seems to be an issue with webviews that will be accessing external pages. The webview needs to have nodeintegration because I have a preload script loaded with the webview that uses electron things.

When browsing the web inside the webview with nodeintegration enabled, no websites using jQuery work correctly. 

I disable nodeintegration and the websites work great, but then `require`, `remote`, etc are `undefined`

Is there no way to have nodeintegration enabled on a webview and also let websites work naturally whether they do or do not need jQuery?

**Comment by MarshallOfSound** [comment]
Preload scripts will have a node context regardless of the `nodeIntegration` setting.  Disable `nodeIntegration` and your preload scripts will work fine 👍

**Comment by iwiedenm** [comment]
@MarshallOfSound thanks for the tip! What if I want to load additional scripts from within the preloader?

For example, I have the following code in my `preload.js` (assume that the loaded file, `second.js` contains electron/node code like `require`, `remote`, etc)
```
function loadNecScript(scriptUrl, callback){
   var script = document.createElement('script');
   script.src = scriptUrl;
   document.body.appendChild(script);
   script.onload = callback;
};
loadNecScript('../custom_scripts/second.js',function(){
    console.log('loaded second script that contains node things')
});
```
The script loads then I still get the error 'Require undefined...'

**Comment by MarshallOfSound** [comment]
@iwiedenm Just use `require('../custom_scripts/second.js')` to load that script

Script tags are executed after the node context is destroyed

**Comment by iwiedenm** [comment]
Ahh I that would make sense now. Okay thank you you've helped tremendously! I've never posted on here before, is there a way to +1 your answer or upvote it?
