### ISSUE TITLE
Unpublish 1.8.0 from npm registry

### ISSUE THREAD

**Issue by ebaynaud** [electron/electron#10576]
You should unpublish 1.8.0 from npm registry as it doesn't exist anymore.

### Expected behavior

Installing react-devtools should install 1.7.6

### Actual behavior

Installing react-devtools still try to install 1.8.0

### How to reproduce

`yarn global add react-devtools`

```
error /Users/ebaynaud/.config/yarn/global/node_modules/react-devtools/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/ebaynaud/.config/yarn/global/node_modules/react-devtools/node_modules/electron
Output:
/Users/ebaynaud/.config/yarn/global/node_modules/react-devtools/node_modules/electron/install.js:48
  throw err
  ^

Error: Failed to find Electron v1.8.0 for darwin-x64 at https://github.com/electron/electron/releases/download/v1.8.0/electron-v1.8.0-darwin-x64.zip
    at Request.<anonymous> (/Users/ebaynaud/.config/yarn/global/node_modules/nugget/index.js:169:61)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestResponse (/Users/ebaynaud/.config/yarn/global/node_modules/nugget/node_modules/request/request.js:1068:10)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
```

**Comment by MarshallOfSound** [comment]
We are in the process of doing this 👍

**Comment by ebaynaud** [comment]
Ok but don't understand why you closed this before it's actually fix. If you close this problem when it's actually fixed we might know when it's actually fixed!

**Comment by plesiecki** [comment]
in the meantime here is yarn workaround
```json 
"resolutions": {
    "electron": "1.7.7"
  }
```
you're welcome

**Comment by binarykitchen** [comment]
well, no, adding such a resolution doesn't really help. it requires the `yarn install --flat` command which will make it a lot harder to install the packages for my app. it is asking me for lots of versions to pick for many packages and my app crashes ...
