### ISSUE TITLE
Fullscreen issue on High Sierra GM

### ISSUE THREAD

**Issue by happypoulp** [electron/electron#10578]
Hi,

I came across an issue around the usage of `BrowserWindow.setFullScreen` + `BrowserWindow.show` in the upcoming OSX High Sierra (currently in Golden Master stage). I reproduced it in my own app and also in the electron-api-demos app (https://github.com/electron/electron-api-demos).

I tested different electron versions and reproduced the issue under all tested version (1.4.12 - my own app electron version -, 1.7.6 - the latest electron version as of today).

* Electron version: 1.7.6
* Operating system: OSX High Sierra Golden Master

### Expected behavior

Setting the app in fullscreen should open the app on a new desktop space in fullscreen.

### Actual behavior

The app is set in fullscreen on a new desktop space and immediately after, it is moved into main desktop space, still in fullscreen but with system menu topbar and dock above it.

Here is the video of the issue: https://youtu.be/8RR9tX1XEGQ

### How to reproduce

The issue can be reproduced on this fork of https://github.com/electron/electron-api-demos: https://github.com/happypoulp/electron-api-demos **on the `fullscreen-highsierra-issue` branch**.

Build and start [like indicated in the original repo](https://github.com/electron/electron-api-demos#building).

In the `fullscreen-highsierra-issue` branch I configured the BrowserWindow to be hidden by default and added two handlers, one for `dom-ready` where I set the app as fullscreen and one for `did-finish-load` where I ask to show the window (since it's supposed to be hidden and even though `setFullScreen(true)` seems to show the window too). This combination of parameters and handlers seems to be the one that trigger the issue. **Note that this issue is NOT reproducible on OSX < High Sierra**

Thanks!

**Comment by MarshallOfSound** [comment]
This sounds like a macOS issue with high sierra, all we do is call OS API's.  If it doesn't happen on <= sierra then I would suggest reporting this to apple through their beta feedback tool 👍

**Comment by happypoulp** [comment]
Ok, thanks!

**Comment by codebytere** [comment]
Gonna go ahead and close this
