### ISSUE TITLE
Can't install electron 1.8.0 on Windows

### ISSUE THREAD

**Issue by afroewis** [electron/electron#10574]
* Electron version: 1.8.0
* Operating system: Windows

Hi,
I did not find any issues for this problem in the repository. To me it's not really clear if the problem is on my side or in the 1.8.0 release.  

### Expected behavior

I am able to install electron 1.8.0.
 
### Actual behavior

I get an error when installing electron `1.8.0`: 

`Error: Failed to find Electron v1.8.0 for win32-x64 at https://github.com/electron/electron/releases/download/v1.8.0/electron-v1.8.0-win32-x64.zip`

### How to reproduce

On Windows, it should be enough to run `npm i electron@1.8.0`.

**Comment by Ajeey** [comment]
1.8.0 is not yet released. Check here - https://electron.atom.io/releases/

**Comment by afroewis** [comment]
Oh, OK. There is already a tag in the git repository: https://github.com/electron/electron/releases/tag/v1.8.0

**Comment by jkleinsc** [comment]
1.8.0 beta had to be pulled because of a security vulnerability.  1.8.1 will be released (as a beta) once the vulnerability has been addressed.
