### ISSUE TITLE
Electron app not opening in windows

### ISSUE THREAD

**Issue by arkakkar** [electron/electron#10577]
* Electron version: 1.7.6
* Operating system: Windows 10

My electron app used to work fine previously on both windows and mac platform.

After I have updated electron to the latest version and build the app, it doesn't work on the Windows platform.Clicking on the icon and nothing happens, thought I can see the the app process in task manager, but neither the browser window opens nor I can see the icon in the task manager after opening the app.

**Comment by MarshallOfSound** [comment]
@arkakkar This is probably an error in your own code causing the app not to start, you should make sure you are listening for uncaughtExceptions and make sure you've updated your code for any changes between your last Electron version and latest.  Without specific errors we can't really help 👍

**Comment by arkakkar** [comment]
Alright, I am listening to any uncaughtExceptions. Can you help me where I can check for them on the windows platform like I can see them in the console app on mac.Thanks

**Comment by MarshallOfSound** [comment]
@arkakkar If you run your app from cmd (`electron . `) and you are console logging the errors they should appear 👍

**Comment by codebytere** [comment]
@arkakkar did you manage to find the errors? If they're in your code i'll go ahead and close this issue.

**Comment by arkakkar** [comment]
Yes the error was with my own code. Thanks for the help
