### ISSUE TITLE
exceptions not being shown in chrome developer console in the way I would expect

### ISSUE THREAD

**Issue by tansaku** [electron/electron#10579]
* Electron version: 1.7.5
* Operating system: OSX 10.12.6

### Expected behavior

when I called functions that I don't exist I'd expect the app to crash, or show error messages like "such and such undefined" in the chrome debugger console

### Actual behavior

the app seems to continue, there are no exceptions in the chrome developer console

### How to reproduce

I'll work on putting up a repo with an example, but right now I've got to get code working - just wondering if this is a known issue - or something silly I'm not setting.  I did search for related issues, but did not find anything in a first pass ...

**Comment by tansaku** [comment]
just in case this helps, what seems particularly strange to me is that if I run code my copying and pasting into the console itself I see the kinds of errors I would expect:

![](https://dl.dropboxcontent/s/q2qlejqjmi264fo/Screenshot%202017-09-22%2011.36.19.png?dl=0)

but not when the code is running in situ - maybe there's some global error catching going on in the app I am working in, or this is electron fault tolerance or something?

**Comment by MarshallOfSound** [comment]
>  maybe there's some global error catching going on in the app I am working in

This sounds like the case 👍 You should try repro minimally 😄

**Comment by tansaku** [comment]
yeah, looks like this code was preventing me seeing the exceptions:

```js
process.on('uncaughtException', (e) => {
  mainProcess.logger.warn('Uncaught exception on front-end')
  mainProcess.logger.warn(e)
})

process.on('unhandledRejection', (reason, promise) => {
  mainProcess.logger.warn('Unhandled promise rejection on front-end')
  mainProcess.logger.warn({reason: reason, promise: promise})
})
```
