### ISSUE TITLE
Bug with menu

### ISSUE THREAD

**Issue by Isahara86** [electron/electron#10575]
Menu on Mac OS do not works properly when using "role".  Example:
                {
                    label: "My custom label",
                    role: 'togglefullscreen'
                },

On windows i see label -  "My custom label".
On mac - "Enter Full Screen".

**Comment by codebytere** [comment]
If you could add an electron version to this, that would be 💯

**Comment by Isahara86** [comment]
"electron": "1.7.6",

**Comment by codebytere** [comment]
@Isahara86 having trouble replicating this locally; do you have an example file that i can run that's currently producing the bug for you?

**Comment by Isahara86** [comment]
Please copy this code https://github.com/Isahara86/Electron_menu_bug.git
Then open terminal in folder and execute next commands:
 npm i 
npm start

In submenu "Fullscreen menu" on windows the label is 'My FullScreen Label !!!!!' on mac - "Enter Full Screen".
I also added "Menu1" with submenu 'Refresh' - it works properly on both platforms

p.s. nodeJS must be installed into your Mac OS

**Comment by Isahara86** [comment]
Maybe I can somehow help with this issue?

**Comment by codebytere** [comment]
I can check on this right now actually :)

**Comment by codebytere** [comment]
hmm so this only exists as a bug on submenus? it works properly for top-level menus?

**Comment by Isahara86** [comment]
I haven't try it with top-level menu. I can check if it needs.

**Comment by codebytere** [comment]
So, it appears that the bug is a function of the role you assign it; with the following template:
```
let template = [
        {
            label: "Menu1",
            submenu: [
                {
                    label: 'Refresh',
                    role: 'forcereload',
                    accelerator: 'Ctrl+F5'
                },
            ]
        },
        {
            label: 'Menu2',
            submenu: [
                {
                    label: 'My FullScreen Label !!!!!',
                    role: 'forcereload',
                    accelerator: 'Ctrl+F5'
                },
            ]
        },
    ];
```
The label shows up as desired, but if you set the role to `togglefullscreen` like you originally had the label appears incorrectly

**Comment by codebytere** [comment]
@Isahara86 unfortunately, we implement roles ourselves on other platforms, but for role-based menu items on MacOS that are Mac-only, they can't be overridden. So you'll find that most of the labels will work, but if a few won't it's expected behavior
