### ISSUE TITLE
Support for Windows AppBar - Docking on screen

### ISSUE THREAD

**Issue by kevygreen** [electron/electron#10583]
It would be great if you could add support for Windows AppBar.

https://msdn.microsoft.com/en-us/library/windows/desktop/cc144177(v=vs.85).aspx#Setting_the_Appbar_S

This would allow for creation of toolbar style applications that could lock to various parts of the screen in an always on fashion. This would be useful for any type of app that you always want up, and always want in front (stocks, music, control bar, etc.)

I don't see any way of accomplishing this currently.

**Comment by toonvanvr** [comment]
Has anyone gotten the AppBar API to work with Electron? I may take a look at how it works and share the code, but only when I get it to work. The C++ Windows API is unexplored territory for me though, so don't expect anything just yet..

**Comment by miniak** [comment]
This is something that can be easily implemented in a 3rd party native node module and most probably should not be in Electron core.

**Comment by miniak** [comment]
As an alternative, you should consider using https://electronjs.org/docs/api/browser-window#winsetthumbarbuttonsbuttons-windows
