### ISSUE TITLE
electron run setInterval  will suspend

### ISSUE THREAD

**Issue by milu2003** [electron/electron#10584]
test.js

```
let aa = 0;
setInterval(function() {
    aa++;
    console.log(aa);
}, 1000*0.01);
```

When I executed the command electron test.js, it started to pause for about 5000th times
How to solve this problem?

**Comment by MarshallOfSound** [comment]
@milu2003 As per the docs of `setInterval` the provided interval is not a guarantee, it is a request.  You can try and improve the situation by disabling background throttling in Electron.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by milu2003** [comment]
OK. Can you make it more specific? @MarshallOfSound
