### ISSUE TITLE
stdio ports are not accessible from electron main process on windows

### ISSUE THREAD

**Issue by anwaybhutkar** [electron/electron#10580]
* Electron version : 1.7.6
* Operating system : Windows

### Expected behavior
It should echo the input on command prompt (of main process).

### Actual behavior
It works MAC machine. On windows machine user is unable to enter input from command prompt of main process. 

### How to reproduce

`main.js`

    const electron = require('electron')
    // Module to control application life.
    const app = electron.app
    // Module to create native browser window.
    const BrowserWindow = electron.BrowserWindow

    const path = require('path')
    const url = require('url')

    let mainWindow

    var isNativeAgent = true;

    function createWindow() {
    }

    app.on('ready', createWindow)

    app.on('window-all-closed', function () {
        if (process.platform !== 'darwin') {
            app.quit()
        }
    })

    process.stdin.on('readable', () => {
        const chunk = process.stdin.read();
       //console.log(chunk);
        if (chunk !== null) {
            process.stdout.write(`data: ${chunk}`);
        }
    });

    app.on('activate', function () {
    })

**Comment by deepakjha14** [comment]
any update on this issue as yet? I am facing the same issue.

**Comment by Slapbox** [comment]
Same question on Electron 3.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
