### ISSUE TITLE
mainWindow is null when will-finish-launching is fired

### ISSUE THREAD

**Issue by nrlquaker** [electron/electron#10581]
* Electron version: 1.7.5
* Operating system: macOS 10.12.6

### Expected behavior

Where should be some way to send message to render process.
But mainWindow is inited after in `ready` event.

### Actual behavior

When `will-finish-launching` event is called mainWindow is not inited.

### How to reproduce

```
app.on('ready', () => createMainWindow())
app.on('will-finish-launching', () => {
    app.on('open-file', (_, filePath) => {
        mainWindow!.webContents.send('open-file', filePath)
    })
})
```

**Comment by MarshallOfSound** [comment]
@nrlquaker `will-finish-launching` is effectively the same as `ready` on Windows and Linux.  On macOS it is fired before `ready` most of the time (hence your window not being created yet)

See the docs: https://electron.atom.io/docs/api/app/#event-will-finish-launching

You should just do everything in the `ready` event 👍

**Comment by nrlquaker** [comment]
@MarshallOfSound
If I do it in `ready` event:
```
app.on('ready', () => {
    createMainWindow()
    app.on('open-file', (_, filePath) => {
        mainWindow!.webContents.send('open-file', filePath)
    })
})
```

Its not fired if app is closed. If its open its ok.

**Comment by MarshallOfSound** [comment]
@nrlquaker Why are you attaching the event listener inside the ready event?  Listen for the event outside `app.on('ready')` and then just do something like this.

```js
let mainWindow;
const createMainWindow = () => { ... };
const handleOpenFile = (filePath) => mainWindow.webContents.send('open-file', filePath);

app.on('open-file', (_, filePath) => {
  if (app.isReady()) {
    handleOpenFile(filePath);
  } else {
    app.on('ready', () => handleOpenFile(filePath);
  }
});
app.on('ready', () => createMainWindow());
```

Disclaimer: Code is untested but should work

**Comment by nrlquaker** [comment]
Thanks for suggestion. But its not working.
I just save the link and open in when thee window is created.
