### ISSUE TITLE
Disable Confirm, Alert ,Prompt Dialogs from iFrames Completely

### ISSUE THREAD

**Issue by updatesvc** [electron/electron#10588]
* Electron version:1.7.5
* Operating system:Windows 10 64-bit

### Expected behavior
I have a program that has a webview. The program is more of a browser. It is used by users to load numerous websites in the webiew. I would like the webview to disable all **alert, confirm , promp**t boxes.
I managed to do so but some websites still pass thru some how.
Here's my code.
Webview **Preloader** script:
`alert = confirm = prompt = function () {};`
Tested in Webview Developer tools with
`window.alert('test');
alert('test');`

**Renderer** code
`alert = confirm = prompt = function () {};`
I just added it but still some alerts work.

**Main.js** Code
```
const {BrowserWindow,app,dialog,ipcMain,session} = require('electron');
ipcMain.removeAllListeners("ELECTRON_BROWSER_WINDOW_ALERT")
ipcMain.removeAllListeners("ELECTRON_BROWSER_WINDOW_CONFIRM")
ipcMain.removeAllListeners("ELECTRON_BROWSER_WINDOW_PROMPT")
ipcMain.on("ELECTRON_BROWSER_WINDOW_ALERT", (event, message, title)=>{
  // console.warn(`[Alert] ** ${title} ** ${message}`)
  event.returnValue = 0 // **IMPORTANT!**
})
ipcMain.on("ELECTRON_BROWSER_WINDOW_CONFIRM", (event, message, title)=>{
  // console.warn(`[Alert] ** ${title} ** ${message}`)
  event.returnValue = 0 // **IMPORTANT!**
})
ipcMain.on("ELECTRON_BROWSER_WINDOW_PROMPT", (event, message, title)=>{
  // console.warn(`[Alert] ** ${title} ** ${message}`)
  event.returnValue = 0 // **IMPORTANT!**
})
```

### Actual behavior
The websites that manage to pass thru display a pop like shown below.
![image](https://i.imgur.com/qaAa74X.jpg)

### How to reproduce
 I have these links that still bypasses all the above protection. 
 Click run on the JS fiddle.
https://jsfiddle.net/dotnetcodecentral/82wmN/
The link below better explains the problem.
**[update]**
https://updatesvc.github.io/iframe/iframe.html
It seems  electron by default has the alert function as:
```
function (message, title) {
    ipcRenderer.sendSync('ELECTRON_BROWSER_WINDOW_ALERT', toString(message), toString(title))
  }
```
for both the browser Window and webiew which is okay.
**But** an iframe's alert fucntion is different.
`function alert() { [native code] }`
therefore here is where the bypass happens.It is not affected by any _winow.alert_ or _alert_ overrides.

The above can be solved by  sand-boxing every iframe.(Add a sandbox tag to every iframe using a preloader script). But you have to cater for new iframes(loaded after page load) and all other circumstances [I am not sure about how to go about that.].

### Hypothetical Solutions 
The following are things I don't know how to do or might not be even possible. I would appreciate if I would get help on them or any other solutions.

- Disable all dialogs (I don't use dialogs in my program , so this will be okay for me)
- Overide the dialog function with something like Dialog.open =null
- Close Alert,Prompt,Confirm on creation with some function
- The sandboxing solution but for every circumstance.

**Comment by myfrndjk** [comment]
@codebytere Hi, I can see the same behavior in mac also

**Comment by KagamiChan** [comment]
How about overwriting `window.alert` like this:

```js
window.alert = function () { console.log('yes') }
```

**Comment by codebytere** [comment]
@updatesvc why don't you try @KagamiChan's suggestion above, and then let me know if you're still having this issue?

**Comment by updatesvc** [comment]
@codebytere and @KagamiChan 
Thanks but I have tried that but still doesn't work.
See my updated question above  for more details. (**[update]**)

**Comment by KagamiChan** [comment]
OK I see.
`<iframe>` is something different. It is actually a separate web page and you cannot inject into it, previous discussion is in #8000.
IMO you may try using [`sandbox` attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox) to control its behaviour

**Comment by updatesvc** [comment]
@KagamiChan 
I am using a webivew since my app is browser , but I have no control on the pages loaded in the webview , some have intrusive iframes and others don't.
I wanted to use the sandbox with a preload script but its efficiency is questionable. What I mean by this is on what events should I run the iframe sand box script below
```
var elements = document.getElementsByTagName('iframe');

    for (var i = 0; i < elements.length; i++) {
        elements[i].sandbox = "allow-same-origin allow-scripts allow-pointer-lock allow-forms allow-popups allow-top-navigation allow-modals";
    }
```
The script below does accomplish the sandboxing but on page load only , what other events should I track? (is what am worried about) onPageload? onDocumentChange? etc

**Comment by KagamiChan** [comment]
Are these iframes dynamically added and removed after dom is loaded (`DOMContentLoaded` and `load`)?
If so, I can just think of a brute-force way to do this: use `setInterval` to execute your code periodically :)

**Comment by updatesvc** [comment]
@KagamiChan 
setInterval might be a bit of overkill LOL,
I think electron should bring back this [eventEmitter](https://github.com/nwjs/nw.js/issues/3333#issuecomment-252432336)
```
webview.addEventListener('dialog',function(e){

});
```
On more digging I found iframe **alerts,prompts,confirm** were not supported some time back.
https://github.com/electron/electron/issues/2644 and https://github.com/electron/electron/pull/8341
good times these were.😁 Though this was an improvement I think the should have provided a way to disable them.

**Comment by codebytere** [comment]
Hi, while we appreciate this request it's not something that our team will be able to implement in the near future, and since we use our issues tab as the team's backlog, we prefer to only retain issues that are on our immediate roadmap. If you'd like to make a PR for this request we would welcome that but in the meantime I'm going to go ahead and close this.

**Comment by demosphen200** [comment]
The next code works fine with Electron 6.0.10


preload.js:
```
let script=document.createElement('script');
script.innerText=`window.oldAlert=window.alert;window.alert=(msg)=>{ console.log('alert msg:', msg); };`+
		`window.oldConfirm=window.confirm;window.confirm=(msg)=>{ console.log('confirm msg:', msg); return true; };`+
		`window.oldPrompt=window.prompt;window.prompt=(msg, value) => { console.log('prompt msg:', msg, 'value:', value); return true; };`+
		`console.log('alert, confirm, prompt disabled for ', document.location.href);`;
document.appendChild(script);
document.removeChild(script);
```

creating a window:

```
let options={
        .....
	webPreferences: {
		nodeIntegration: false,
		nodeIntegrationInWorker: false,
		nodeIntegrationInSubFrames: true,
		webSecurity: false,
		allowRunningInsecureContent: true,
		contextIsolation: true,
		preload: __dirname+'/preload.js'
	}
};
let wnd = new this.electron.BrowserWindow(options);
wnd.loadURL(... some url... );
```

dont't remove `document.removeChild(script);` line. without it 'DOMContentLoaded' event happens immediatly after preload script, before main page loaded.

**Comment by GGCarry** [comment]
@demosphen200 wow!your code is work!!!but , i am still not understand why use the "removeChild" here, if I don't use removeChild here ,is not work, can you explain more details?thanks
