### ISSUE TITLE
Drop to 1fps in background

### ISSUE THREAD

**Issue by Tibus** [electron/electron#10598]
Hello, 

I'm making a software using threejs and need to save frame to PNG for a few seconds.
The problem is when I'm changing screen on Mac OS during this save procedure, framerate drop to 1fps event with a "setTimeout(render, 1)".

How to force electron/javascript to keep 60fps in background mode if needed.

Thanks!!!

**Comment by codebytere** [comment]
Hey there, thanks for opening this issue! Before we can really begin to dig into this, we'll need:

1. Electron Version
2. Steps to Reproduce

**Comment by Tibus** [comment]
Hello, 
Here is the electron version : Version 1.6.12 (1.6.12)
And to reproduce it : 
1. create a simple electron app on MacOS
2. add a function logging FPS
3. FPS will be around 60fps.
4. change mac os screen for few seconds
5. come back on the electron app and look at the console, it will not be 60fps but arround 1fps or so.

**Comment by robinwassen** [comment]
@Tibus Chrome does throttle when it is not focused per default to limit resource usage and preserve battery.

You can change this behavior by passing in backgroundThrottling: false when creating your BrowserWindow.

See: https://github.com/electron/electron/issues/4925#issuecomment-208707018

**Comment by Tibus** [comment]
Ok, thank's, it work great!
