### ISSUE TITLE
No electron-v1.7.8-linux-x64.zip under https://github.com/electron/electron/releases/download/v1.7.8/

### ISSUE THREAD

**Issue by xingao0803** [electron/electron#10594]
* Electron version:
   v1.7.8
* Operating system:
  linux
### Expected behavior
Should have electron-v1.7.8-linux-x64.zip to download from https://github.com/electron/electron/releases/download/v1.7.8/

### Actual behavior

No electron-v1.7.8-linux-x64.zip under https://github.com/electron/electron/releases/download/v1.7.8/

**Comment by MarshallOfSound** [comment]
1.7.8 is not released yet :+1:.

**Comment by MarshallOfSound** [comment]
Closed this a bit fast from my phone :laughing: although a 1.7.8 release exists on GitHub, the actual builds are still running and it hasn't been published to npm yet

**Comment by johnf** [comment]
@MarshallOfSound It has been published on npm though.
``` bash
johnf@kermit  ➤  npm view electron
 
{ name: 'electron',
  description: 'Build cross platform desktop apps with JavaScript, HTML, and CSS',
  'dist-tags': { latest: '1.7.8', beta: '1.7.8' },
```

**Comment by MarshallOfSound** [comment]
Following up in #10595
