### ISSUE TITLE
Add buildflags for different "features"

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#10596]
_An umbrella issue for discussions and tracking the progress._

Add build flags (switches) for some of the features Electron has (APIs groups?), test build with
1) all flags enabled (_default_),
2) all flags disabled,
3) any one flag disabled.

List of features is pretty arbitrary, this issue may be closed with any number of buildflags introduced.

The primary goal is to simplify Chromium upgrades by working on different parts of code in parallel.
Another useful outcome might be an established way of how to work on experimental / unfinished features in isolation, without keeping feature branches alive for a long time and avoiding breaking the master.

/cc @tonyganch

**Comment by alexeykuzmin** [comment]
pdf viewer?

**Comment by alexeykuzmin** [comment]
Make run-as-node mode optional #11701

**Comment by codebytere** [comment]
We do this now, so this can be closed out.
