### ISSUE TITLE
Can't install electron 1.7.6 in Ubuntu 16.04 environment

### ISSUE THREAD

**Issue by tom--bo** [electron/electron#10604]
* Electron version:1.7.6 (1.7.8(latest) has no linux package: https://github.com/electron/electron/issues/10595)
* Operating system:Ubuntu 16.04
* Node version: 8.5.0 
* npm version: 5.4.2

### Expected behavior
install successfully 

### Actual behavior
arise error below
```
npm install electron@1.7.6 -g
/usr/local/bin/electron -> /usr/local/lib/node_modules/electron/cli.js

> electron@1.7.6 postinstall /usr/local/lib/node_modules/electron
> node install.js

/usr/local/lib/node_modules/electron/install.js:48
  throw err
  ^

Error: read ECONNRESET
    at _errnoException (util.js:1026:11)
    at TLSWrap.onread (net.js:606:25)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.7.6 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.7.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### How to reproduce
I'm not sure but, someone using linux can't install electron 1.7.6 by npm?

**Comment by enlight** [comment]
The issue is with your internet connection, try again later or use a different connection.

**Comment by tberghuis** [comment]
try `sudo npm install -g electron --unsafe-perm=true --allow-root`

**Comment by paperbenni** [comment]
@tberghuis works but sounds dirty.

**Comment by NithinRRamesh** [comment]
Thank you it works

**Comment by NithinRRamesh** [comment]
https://electronjs.org/docs/tutorial/installation actually the same solution is suggested by electron documentation

**Comment by Mahi-Uddin** [comment]
Wow it works!
Thanks.

**Comment by gasparyanyur** [comment]
@tberghuis  after running a command which you said I am getting error 
```
Error: connect ECONNREFUSED 52.216.0.104:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1173:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.8.4 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.8.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yuri/.npm/_logs/2018-04-26T07_12_43_995Z-debug.log
```

**Comment by dcaldwell-sw** [comment]
If you used 'sudo npm install -g electron'  you need to fix folder permissions for /usr/lib/node_modules:
>sudo chmod 0774 /usr/lib/node_modules/ -R
>sudo chown root:sudo node_modules/ -R
if you aren't a member of the sudo group, change sudo to a group you are a member of.
