### ISSUE TITLE
desktop app without generating build?

### ISSUE THREAD

**Issue by AbinayaSubbiah** [electron/electron#10603]
Hi all, i am trying to created desktop app for Angular 2 application. Also i have created app with generated build. Now what i need to create app without generating build in webpack?

**Comment by enlight** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
