### ISSUE TITLE
Special characters encoding in main process

### ISSUE THREAD

**Issue by DodgersDev** [electron/electron#10600]
* Electron version: 1.7.5
* Operating system: Windows 10
* Electron Chromium’s Locale: pl (Polish)

On Main Process:

// main.js
`console.log('ó ł ć')` 

Returns: 

`├│ ┼é ─ç`

All special characters are converted to Box-drawing characters (I gusses :) ). This only happens in main process.
 
I have utf8 files encoding. 

Greetings.

**Comment by codebytere** [comment]
@DodgersDev take a look at https://github.com/electron/electron/issues/678 and see if any of the suggestions there solve your problem?

**Comment by DodgersDev** [comment]
@codebytere I saw this before writing my issue and nothing solved my problem.
I have everywhere utf8 encoding and in renderer everything works but in main process all special characters are converted to box drawing characters.

**Comment by codebytere** [comment]
do you have a simple repro file i could play around with, that replicates your current situation?

**Comment by DodgersDev** [comment]
This happens in the simplest electron project for me

**Comment by DodgersDev** [comment]
This happens in the simplest electron project.

Try type console.log('ł ó ć') in your main. js file.

**Comment by DodgersDev** [comment]
[electron-special-characters.zip](https://github.com/electron/electron/files/1330169/electron-special-characters.zip)

`npm install`
`npm run start`

In the console you should see -> ┼é ├│ ─ç

**Comment by codebytere** [comment]
Hmm so this is what i see in my console:
<img width="758" alt="screen shot 2017-09-25 at 1 14 29 pm" src="https://user-images.githubusercontent.com/2036040/30821539-b7682a14-a1f3-11e7-9eef-a1e95fc64b87.png">

o confirm that this issue isn't upstream, could you open devtools on your local Chrome, then run `console.log('ó ł ć')` and see what happens?

**Comment by DodgersDev** [comment]
Yes this is renderer process output and i have same output. 

Check your normal command line after npm run start and you could see console log in main process.

**Comment by DodgersDev** [comment]
This is my renderer (all works)
![renderer](https://user-images.githubusercontent.com/20027710/30822055-d774d184-a227-11e7-82cd-d1966b197493.png)

This is my main process console log output 

![main process](https://user-images.githubusercontent.com/20027710/30822091-f600d7e2-a227-11e7-9d96-35fab0f35e5d.png)

**Comment by codebytere** [comment]
i'm pretty sure that it's an issue with your console itself not rendering UTF-8 characters correctly.

See: https://superuser.com/questions/269818/change-default-code-page-of-windows-console-to-utf-8 and https://superuser.com/questions/1170656/windows-10-terminal-encoding

**Comment by DodgersDev** [comment]
I have correct characters encoding in my console. I checked this before reporting an issue.
In nodejs/express apps everything is OK, all special characters are rendered correctly.

I have problems with special characters encoding only in electron MainProcess.

What is your console.log output from my "simple app" in your command line ?

**Comment by codebytere** [comment]
<img width="626" alt="screen shot 2017-09-26 at 7 49 13 am" src="https://user-images.githubusercontent.com/2036040/30858810-3cc5570e-a28f-11e7-9945-c4131c588887.png">

what it should be, i believe.

**Comment by DodgersDev** [comment]
I reinstalled (delete windows registry) my cmd and everything works lol
Stupid mistake.
Sorry for the confusion and thanks for the help.
You can close.

**Comment by codebytere** [comment]
no worries!gGlad it's resolved 😁
