### ISSUE TITLE
Electron Crash with code FATAL:thread_local_storage.cc(285)

### ISSUE THREAD

**Issue by phanthai12** [electron/electron#10607]
- **OS: windows 10 pro**
- **Electron: 1.8.0**

## **Expected behavior**
Don't Crash

## **How to reproduce**
When I create `BrowserWindow `with option

`webPreferences.session = session.fromPartition("persist:link-"+player.link.id,{cache:false})`

with `player.link.id` is an integer that can be repeated

And when `BrowserWindow ` before-close
im using:
```javascript
browser.webContents.session.clearStorageData({},()=>{
    browser.destroy();
});
```

It will OK with few browser

But when i try to about 30 thead(browser), and close about 300~400 browser, it crash

## **Error Code: No line detect.**
```
[4360:0925/204514.669:FATAL:thread_local_storage.cc(285)] Check failed: slot_ != kInvalidSlotValue (-1 vs. -1)
Backtrace:
        GetHandleVerifier [0x00007FF764811415+25013]
        GetHandleVerifier [0x00007FF7648838B3+493139]
        (No symbol) [0x00007FF7648088E4]
        GetHandleVerifier [0x00007FF76484EEDD+277629]
        GetHandleVerifier [0x00007FF76484E9EE+276366]
        GetHandleVerifier [0x00007FF764B5C615+3478453]
        IsSandboxedProcess [0x00007FF764FAA432+4454494]
        IsSandboxedProcess [0x00007FF764CBBD08+1380660]
        GetHandleVerifier [0x00007FF764991802+1598882]
        (No symbol) [0x00007FF7647C2019]
        (No symbol) [0x00007FF7645AD5CF]
        (No symbol) [0x00007FF7645AF8C6]
        (No symbol) [0x00007FF7646A0FE3]
        (No symbol) [0x00007FF7646A1A77]
        (No symbol) [0x00007FF764694F41]
        (No symbol) [0x00007FF76469DAB6]
        (No symbol) [0x000002CDBE90F4E0]

```

**Comment by jkleinsc** [comment]
@phanthai12 1.8.2-beta.1 was just released: https://github.com/electron/electron/releases/tag/v1.8.2-beta.1

Would you mind testing on this new version to see if it resolves your issue?

**Comment by sofianguy** [comment]
Closing this. @phanthai12 let us know if your issue is not resolved with the new release
