### ISSUE TITLE
v1.8.0 has no downloads

### ISSUE THREAD

**Issue by StephanBijzitter** [electron/electron#10605]
Since the upgrade to 1.8.0, I cannot install my project anymore.

```
==> default: error /vagrant/node_modules/electron: Command failed.
==> default: Exit code: 1
==> default: Command: node install.js
==> default: Arguments: 
==> default: Directory: /vagrant/node_modules/electron
==> default: Output:
==> default: /vagrant/node_modules/electron/install.js:48
==> default:   throw err
==> default:   ^
==> default: 
==> default: Error: Failed to find Electron v1.8.0 for linux-x64 at https://github.com/electron/electron/releases/download/v1.8.0/electron-v1.8.0-linux-x64.zip
==> default:     at Request.<anonymous> (/vagrant/node_modules/nugget/index.js:169:61)
==> default:     at emitOne (events.js:96:13)
==> default:     at Request.emit (events.js:188:7)
==> default:     at Request.onRequestResponse (/vagrant/node_modules/request/request.js:1068:10)
==> default:     at emitOne (events.js:96:13)
==> default:     at ClientRequest.emit (events.js:188:7)
==> default:     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
==> default:     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
==> default:     at TLSSocket.socketOnData (_http_client.js:363:20)
==> default:     at emitOne (events.js:96:13)
```

```
electron@^1.4.4:
  version "1.8.0"
  resolved "https://registry.yarnpkg.com/electron/-/electron-1.8.0.tgz#896f429b1e664f496f62b9cc7ee6a67a71375f31"
  dependencies:
    "@types/node" "^8.0.24"
    electron-download "^3.0.1"
    extract-zip "^1.0.3"
```

This is because all other releases ship downloads, but the 1.8.0 release is remarkably empty.
Using any older version works as expected.

**Comment by StephanBijzitter** [comment]
Possible solutions:
* Completely remove the 1.8.0 release from NPM and from Github
* Release a version 1.8.1 that does have downloads

**Comment by MarshallOfSound** [comment]
@StephanBijzitter Both of those solutions are currently in progress, `1.8.0` is no longer on github and is in the process of being pulled from npm.

**Comment by StephanBijzitter** [comment]
@MarshallOfSound The tag is still present: https://github.com/electron/electron/releases/tag/v1.8.0

**Comment by MarshallOfSound** [comment]
@StephanBijzitter The tag is there but there is no release associated with it.  Removing an already pushed tag requires a force push I believe and we have those disabled for safety reasons 😄

**Comment by StephanBijzitter** [comment]
Right, but that does mean it's still counted as a release here https://github.com/electron/electron/releases/

**Comment by MarshallOfSound** [comment]
@StephanBijzitter It appears in that list, but with the "tag" icon next to it. All tags appear in that list, but there isn't a release with it.  Will discuss removing the tag but I'm not a fan of force pushing for any reason, it breaks things for too many people

**Comment by fantasydr** [comment]
This issue might related to https://github.com/electron/libchromiumcontent/issues/369  

In fact you cannot build 1.8.0 for now because of the missing dependency. I wrongly started my project based on 1.8.0, now I have to move to a newer version.

**Comment by MarshallOfSound** [comment]
@fantasydr There is no issue here any more, [`1.8.1`](https://github.com/electron/electron/releases/tag/v1.8.1) is released 👍

**Comment by fantasydr** [comment]
There will be issues again if people do random stuff, such as rebase or delete a published commit.
Or close issue without any clear explanation 🐛
