### ISSUE TITLE
Compile for win on mac

### ISSUE THREAD

**Issue by kamalkech** [electron/electron#10601]
* Electron version: "^1.7.6"
* Operating system: macOs Sierra 10.12.6

I use electron with angular 4 (angular-cli)

To compile for mac work fine, but not for win and i have this on my package : 

"package-mac": "electron-packager . --overwrite --platform=darwin --arch=x64 --icon=assets/icons/mac/icon.icns --prune=true --out=release-builds",
    "package-win": "electron-packager . --overwrite --asar=true --platform=win32 --arch=ia32 --icon=assets/icons/win/icon.ico --prune=true --out=release-builds --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName=\"myApp\"",
    "package-linux": "electron-packager . --overwrite --platform=linux --arch=x64 --icon=assets/icons/png/icon.png --prune=true --out=release-builds"

Could not find "wine" on your system.

Wine is required to use the appCopyright, appVersion, buildVersion, icon, and
win32metadata parameters for Windows targets.

Make sure that the "wine" executable is in your PATH.

See https://github.com/electron-userland/electron-packager#building-windows-apps-from-non-windows-platforms for details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! formation@0.0.0 package-win: `electron-packager . --overwrite --asar=true --platform=win32 --arch=ia32 --prune=true --out=release-builds --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName="myApp"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the formation@0.0.0 package-win script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in

i guess the probleme is about that "Could not find "wine" on your system."
so how fixe or install "wine" on mac ??? any idea ? 
Thank you.

**Comment by MarshallOfSound** [comment]
@kamalkech There are tonnes of ways to install wine on a mac, the easiest is through brew.  Give `wine` a quick google search and you should come up with an install method you like 👍 

That said I strongly recommend building on the target platform, for the target platform.  I.e. building windows on windows, mac on mac, Etc.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
