### ISSUE TITLE
webContents.print not working on windows

### ISSUE THREAD

**Issue by ishwarrimal** [electron/electron#10617]
Electron version: 1.7.6
Operating system: Windows 7

Same as https://github.com/electron/electron/issues/8828

I am using 1.7.6 and still facing the same issue. It gets stuck at spooling. It works fine when I am running the app from the command line for development but does not work if I install the app using .exe file. It was working properly on my dev machine but when we released it in production then all our users complained about printing not working. It gets stuck at spooling in their machine and nothing gets printed. It does not show any size of the file as well. Please let me know if there is any fix for this.

Attaching the screenshot of the issue happening at user's device: https://drive.google.com/open?id=0B0v4IupaEnYpdE13WDBpbUNIZjQ

**Comment by codebytere** [comment]
if you wouldn't mind adding this as a new comment to https://github.com/electron/electron/issues/8828  that would be 💯, so we don't end up with a ton of duplicates!
