### ISSUE TITLE
Modal BrowserWindow , parent window Flicker when close child Window

### ISSUE THREAD

**Issue by hxkuc** [electron/electron#10616]
win7 and win10 all have this problem，
electron 1.0---1.7
1: open one modal window name win1 on the parent window name win
like this --> let win1 = new BrowserWindow({ width: 400, height: 320, parent: win, modal: true })
2:open one window name win2 on the parent window name win1
like this --> let win2 = new BrowserWindow({ width: 400, height: 320, parent: win1, modal: true })
the problem is win hidden when close win2
and win show when open win2
bug ?????????????

**Comment by hxkuc** [comment]
#9325

**Comment by hxkuc** [comment]
When will it be fixed please

**Comment by dimdimdimdim** [comment]
I have the same issue. Note that it occurs only if the window is modal. setting modal to false in the creation params will not show this behavior.

**Comment by hxkuc** [comment]
什么时候可以解决这个问题啊，When will it be fixed

**Comment by hxkuc** [comment]
@dimdimdimdim you fixed it

**Comment by dimdimdimdim** [comment]
@hxkuc No. There could probably be a way to workaround this by creating a non-modal window, and adding code to set focus back to it whenever it looses it. I tried it, it somewhat worked, but then, when the whole application was loosing focus, the task bar icon was blinking because I try set the focus back to the dialog window when the application is in background.

You can probably solve this annoyinig consequence by setting focus on the dialog *only* when you detect that the main (parent) window gains back the focus, instead of when the dialog (child) looses the focus, but there probably will be other small glitches to solve (like, maybe the first mouse down event will still be sent to the main window).

And, also, you'll see that the main window will anyway receive mouse hover events. To fix that, you can probably set "pointer-events: none" to the body of the main window page, during the time the dialog is shown.

Overall, by adding hacks on top of other hacks, you could certainly make something appear almost as intended and without flicker, but it's not worth it in my case. I don't have many dialogs to show. And I already wasted a lot of time hacking other problems related to electron.

One last suggestion: It is probably useless to harass the electron team asking repetitively when it will be fixed. It will probably be fixed in a few months/years, if other people show interest in it. But not many electron apps actually use modal BrowserWindow dialogs. Even VSCode and Atom don't use them at all. So you'll need a lot of patience, or you can just try to fix it using the above hack suggestions... or dive into electron/chromium code and fix it at the root yourself, it will probably take less time.

**Comment by hxkuc** [comment]
@dimdimdimdim Thank you for giving me so much advice. I will seriously consider it. Thank you very much

**Comment by momothereal** [comment]
I'm running into this problem too. I'm on Windows 10 using electron `v1.7.10`. The main window shortly becomes black and then back to normal when the child (modal) is closed.

Parent window:
```js
let mainWindow = new BrowserWindow({
    width: 800, height: 600,
    autoHideMenuBar: true,
    frame: false
});
```

Child window:
```js
let childWindow = new BrowserWindow({
    width: 600, height: 800,
    autoHideMenuBar: true,
    modal: true,
    parent: mainWindow,
    resizable: false,
    minimizable: false
});
```

**Comment by hxkuc** [comment]
@momothereal  i have give up this config ｛modal: true,  parent: mainWindow｝，i can wait no langer

**Comment by genestiel** [comment]
@momothereal  
i got this problem recently on electron v1.7.9

if there is a modal window and have parent window, when i close modal window there is a flick or blink... when i set alwaysOnTop = true on mainWindow property, there problem solved.

let mainWindow = new BrowserWindow({
    width: 800, height: 600,
    autoHideMenuBar: true,
    frame: false,
    **alwaysOnTop:true**
});

let childWindow = new BrowserWindow({
    width: 600, height: 800,
    autoHideMenuBar: true,
    modal: true,
    parent: mainWindow,
    resizable: false,
    minimizable: false
});

**Comment by MagedSaeed** [comment]
@genestiel 
Your solution works more than fine for me.
Thanks,,

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by tdbender** [comment]
As I noted in my comment just two up from yours @codebytere, it happens in version 2.0.0.  I'm currently using 2.0.4 and it's still an issue.

**Comment by tdbender** [comment]
Following up, I updated to Electron 3.0.0 and the issue is still present.

**Comment by torquescrew** [comment]
I have a workaround using the above suggested setAlwaysOnTop and focus events:
```
childModal.on('focus', () => {
   remote.getCurrentWindow().setAlwaysOnTop(true)
})

childModal.on('blur', () => {
   remote.getCurrentWindow().setAlwaysOnTop(false)
})

childModal.on('close', () => {
   remote.getCurrentWindow().setAlwaysOnTop(false)
})
```
This now works as expected with no flicker for me.

**Comment by talhaanees** [comment]
Any updates of when this issue may be resolved? Using Electron version 3.0.10 and this issue still persists.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by tdbender** [comment]
Using Electron 5.0.7.  Yes, this is still an issue.

**Comment by gtkpr** [comment]
Still an issue on version 6.9.0 in October 2019

**Comment by gtkpr** [comment]
> I have a workaround using the above suggested setAlwaysOnTop and focus events:
> 
> ```
> childModal.on('focus', () => {
>    remote.getCurrentWindow().setAlwaysOnTop(true)
> })
> 
> childModal.on('blur', () => {
>    remote.getCurrentWindow().setAlwaysOnTop(false)
> })
> 
> childModal.on('close', () => {
>    remote.getCurrentWindow().setAlwaysOnTop(false)
> })
> ```
> 
> This now works as expected with no flicker for me.

Such a hackish workaround :(

**Comment by Tianruo** [comment]
Still an issue on version 7.1.x

**Comment by Tianruo** [comment]
`
modalWin.on('close', e => parentWin.setAlwaysOnTop(true))
modalWin.on('closed', e => parentWin.setAlwaysOnTop(false))
`
Try it

**Comment by Tianruo** [comment]
```js
modalWin.on('close', e => parentWin.setAlwaysOnTop(true))
modalWin.on('closed', e => parentWin.setAlwaysOnTop(false))
``` ```

TRY  IT

**Comment by paresy** [comment]
Still an issue on 8.0.3 and 9.0.0 (beta5). Tested on Windows 10.

**Comment by ZsgsDesign** [comment]
> I have a workaround using the above suggested setAlwaysOnTop and focus events:
> 
> ```
> childModal.on('focus', () => {
>    remote.getCurrentWindow().setAlwaysOnTop(true)
> })
> 
> childModal.on('blur', () => {
>    remote.getCurrentWindow().setAlwaysOnTop(false)
> })
> 
> childModal.on('close', () => {
>    remote.getCurrentWindow().setAlwaysOnTop(false)
> })
> ```
> 
> This now works as expected with no flicker for me.

@genestiel Fixed mine, thank you~

**Comment by tdbender** [comment]
Confirmed the workaround fixes the issue on my app.  FYI my app uses native window.open and has multiple windows.  Must setAlwaysOnTop(true) on all open windows before closing the modal for this to work, but does work.  Would be nice to get a fix but at least we have a workaround.  Thanks.

**Comment by banguncool** [comment]
Hi, I'm using electron 10.1.4 and the issue still exist, but i found the best solutions for this and this is work for me like a charm

this how I call the second window

```
const form = new BrowserWindow({
    title: 'Form',
    width: 600,
    height: 400,
    parent: mainWindow,
    modal: true,
    webPreferences: {
      nodeIntegration: true
    }
  })

  // this is the formula
  form.on('close', () => {
    mainWindow.setAlwaysOnTop(true)
    setTimeout(() => {
      mainWindow.setAlwaysOnTop(false)
    }, 200)  // give it little delay
    console.log('close')
  })

  form.loadFile('public/form.html')
  form.once('ready-to-show', () => form.show())
```

**Comment by Edwin-Pratt** [comment]
Hey there.

I'm using Electron v11.1.1, and have come across the same issue.

The temporary solution I came up with is to not use child modal windows, but instead to send a message to the main window telling it to disable it's inputs and buttons.

<hr />

Here is a bare bones example of the solution:

- `main.js`
```js
// Import required modules
const path = require("path");
const electron = require("electron");
const {app, BrowserWindow, ipcMain} = electron;

// Variables to store windows
let mainWindow;
let childWindow;

// Event handlers
app.on("ready", createMainWindow);

// Message handlers
ipcMain.on("open-child-window", onOpenChildWindow);

// Create a main window
function createMainWindow(event) {
    // I tend to always check if a window has not been made yet
    if (mainWindow != null) {
        return false;
    }
    
    // Make a window
    mainWindow = new BrowserWindow({
        width: 800,
        height: 600,
        show: false,
        frame: false,    // I like to make my own menus
        resizable: false,
        webPreferences: {
            contextIsolation: true,
            nodeIntegration: false,
            preload: path.join(__dirname, "preload.js")
        }
    });
    
    // Load the main window's main HTML file
    mainWindow.loadURL("file://" + path.join(__dirname, "public", "mainWindow.html"));
    
    // Handle window events
    mainWindow.once("ready-to-show", e => mainWindow.show());
    mainWindow.on("closed", e => mainWindow = null);
}

// Open a child window
function onOpenChildWindow(event) {
    // Make sure that the child window is not open
    if (childWindow == null) {
        return false;
    }
    
    // Make the child window
    childWindow = new BrowserWindow({
        width: 520,
        height: 320,
        show: false,
        frame: false,
        resizable: false,
        parent: mainWindow,
        webPreferences: {
            contextIsolation: true,
            nodeIntegration: false,
            preload: path.join(__dirname, "preload.js")
        }
    });
    
    // Load the child window's main HTML file
    childWindow.loadURL("file://" + path.join(__dirname, "public", "childWindow.html"));
    
    // Handle events for the child window

    // When the child window is ready to be displayed, 
    // show the child window and send a messages to the main window to disable inputs and buttons
    childWindow.once("ready-to-show", e => {
        childWindow.show();
        mainWindow.webContents.send("disable-window");
    });

    // When the child window is closed,
    // Dereference the child window and send a message to the main window to enable inputs and buttons
    childWindow.on("closed", e => {
        childWindow = null;
        mainWindow.webContents.send("enable-window");
    });
}
```

- `preload.js`

```js
// Import required modules
const electron = require("electron");
const {contextBridge, ipcRenderer} = electron;

// Expose the ipcRenderer to the window
contextBridge.exposeInMainWorld("electron", {
    ipcSend: (channel, ...args) => ipcRenderer.send(channel, ...args),
    ipcOn: (channel, callback) => ipcRenderer.on(channel, (event, ...args) => callback(args))
});
```

- `mainWindow.js`

```js
window.onload = () => {
    // ...

    // Handle messages
    if (window.electron != null) {
        window.electron.ipcOn("disable-window", onDisableWindow);
        window.electron.ipcOn("enable-window", onEnableWindow);
    }
};

// ...

// Disable elements like inputs, buttons and textareas
function onDisableWindow(arg) {
    // Get all elements that need to be disabled
    let inputs = document.getElementsByTagName("input");
    let buttons = document.getElementsByTagName("button");
    let textareas = document.getElementsByTagName("textarea");
    
    // Loop over all inputs and set their opacity to 0.4 and disable them
    for (let input of inputs) {
        input.disabled = true;
        input.style.opacity = 0.4;
    }
    
    // Loop over all buttons and set their opacity to 0.4 and disable them
    for (let button of buttons) {
        button.disabled = true;
        button.style.opacity = 0.4;
    }
    
    // Loop over all textareas and set their opacity to 0.4 and disable them
    for (let textarea of textareas) {
        textarea.disabled = true;
        textarea.style.opacity = 0.4;
    }
}

// Enable elements like inputs, buttons and textareas
function onEnableWindow(arg) {
    // Get all elements that need to be enabled
    let inputs = document.getElementsByTagName("input");
    let buttons = document.getElementsByTagName("button");
    let textareas = document.getElementsByTagName("textarea");
    
    // Loop over all inputs and set their opacity to 1 and enable them
    for (let input of inputs) {
        input.disabled = false;
        input.style.opacity = 1;
    }
    
    // Loop over all buttons and set their opacity to 1 and enable them
    for (let button of buttons) {
        button.disabled = false;
        button.style.opacity = 1;
    }
    
    // Loop over all textareas and set their opacity to 1 and enable them
    for (let textarea of textareas) {
        textarea.disabled = false;
        textarea.style.opacity = 1;
    }
}
```

The functions in `mainWindow.js`, `onEnableWindow` and `onDisableWindow` can also be placed in a file like `global-functions.js` to port them easily to other windows. Also, you can expand on the event handlers in `main.js` to disable all other child windows if they're showing. One way of doing this would be:

```js
if (child1 != null) {
    child1.webContents.send("disable-window");
}

if (child2 != null) {
    child2.webContents.send("disable-window");
}
// ...

// Or more compact
if (child1 != null) child1.webContents.send("disable-window");
if (child2 != null) child2.webContents.send("disable-window");
//...
```

<hr />

Hope it helps! :smile:

**Comment by 1337cookie** [comment]
This issue persists in electron@12.0.4

With the always on top solutions I found it could make other electron apps flash their title bars or reorder/focus other windows, explorer.exe for example or any other window. The always on top workaround was no longer working for me on upgrading to electron 12.
The most elegant solution/workaround I have found is to use:
```
modalWindow.on('close', () => {
    parentWindow.focus();
});
```

**Comment by dr-meister** [comment]
This issue still persists.

Tested on `electron@22.0.2` and Windows 10
