### ISSUE TITLE
wine ask for root

### ISSUE THREAD

**Issue by PinkyRabbit** [electron/electron#10613]
* Electron version: ^1.7.8
* Operating system: Ubuntu 16.04

Hello! I asked questions into superuser.com . [Look on it please](https://superuser.com/questions/1253322/wine-as-root-how-to-solve). Wine says that im not an owner of .wine and i cant compile for windows. Thanks.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
