### ISSUE TITLE
Error with packed Electron

### ISSUE THREAD

**Issue by UltraDosaaf** [electron/electron#10623]
Node, NPM and electron - latest versions

I have some strange error... All works fine when I'm just testing app. But when I pack it with electron-builder and then run exe file - boom! - error: 
```app.js:2 os
app.js:4 fs-extra
app.js:6 path
app.js:8 request
module.js:472 Uncaught Error: Cannot find module './dev_null_stream'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (E:\app\abc\abc-win32-x64\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\app\abc\abc-win32-x64\resources\app.asar\node_modules\parse5\lib\sax\index.js:4:21)
    at Object.<anonymous> (E:\app\abc\abc-win32-x64\resources\app.asar\node_modules\parse5\lib\sax\index.js:115:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

 It apears right after I require 'cheerio' module

![2017-09-26_20-06-40](https://user-images.githubusercontent.com/25608313/30900809-9cff306e-a365-11e7-8cc9-d67cb5cbd269.png)

**app.js**
```javascript
const os = require('os');
console.log('os');
const fs = require('fs-extra');
console.log('fs-extra');
const path = require('path');
console.log('path');
const request = require('request');
console.log('request');
const cheerio = require('cheerio');
console.log('cheerio');
const electron = require('electron');
console.log('electron');

let win = electron.remote.getCurrentWindow();
let shell = electron.shell;
let screen = electron.screen;
```

**electron.js**
```javascript
const os = require('os');
const fs = require('fs-extra');
const path = require('path');
const electron = require('electron');

let win = null;
let app = electron.app;
let remote = electron.remote;
let BrowserWindow = electron.BrowserWindow;

// ... Standard createWindow from Electron examples ...
```

Any idea why this happens?

**Comment by myfrndjk** [comment]
Hi,

How you are building the application using **electron builder** ?
It seems it is expecting dev_null_stream during run time.
Install that module in your system and in you package.json add `dev_null_stream with version` like below

```
  "dependencies":{
    "dev_null_stream": "^1.2.3"
  },
```
yesterday i came across the similar issue once I added that in dependencies it is fixed.
You can also try the same.

Thanks
Jk

**Comment by MarshallOfSound** [comment]
Issue appears to be due to user config rather than Electron itself, would suggest following @myfrndjk recommendation or reporting upstream to `-builder`

**Comment by UltraDosaaf** [comment]
@myfrndjk it doesn't work in my case. 
I'm using **electron-packager**
``` 
"scripts": {
      "init": "npm install",
      "start": "electron .",
      "pack": "electron-packager . --version=1.0.1 --platform=win32 --asar=true --out=./ --overwrite=true --icon=app/i/icon.ico --ignore=.bat --ignore=dev"
   }
```

@MarshallOfSound, thanks, I will, but just not sure is it `-builder` or `-packager` or both?

**Comment by myfrndjk** [comment]
@UltraDosaaf  I think you can track with electron packager issues thread.There might be different procedure to add run time dependencies.I never tried electron-packager so dont have much idea on it.

Thanks
Jk
