### ISSUE TITLE
Reloading webContents will close opened windows.

### ISSUE THREAD

**Issue by WhiteFur** [electron/electron#10624]
* Electron version: 1.7.8
* Operating system: macOS sierra,  windows7, windows10

### Expected behavior

Refreshing the page does not effect other opened windows.

### Actual behavior

Refreshing the page will close other windows.

### How to reproduce

Open a new BrowserWindow and refresh the main window then the opened BrowserWindow is closed.

**Comment by cuixiping** [comment]
duplicate with #10546

**Comment by MarshallOfSound** [comment]
Duplicate of #10546
