### ISSUE TITLE
Dialog shown with showMessageBox loses modal property after right clicking the app tray

### ISSUE THREAD

**Issue by corj** [electron/electron#10625]
* Electron version: 1.7.8
* Operating system: Windows 10

### Expected behavior
Right clicking the app tray should not break the dialog modal ability. Should not be possible to interact with the window menu, buttons, etc.

### Actual behavior
Right clicking the app tray breaks the modal ability of the dialog and It's possible to interact with the parent window by accessing the window menu or buttons. After an action is taken (pressing a button, accessing the menu) the dialog becomes modal again.

### How to reproduce
1. $ git clone https://github.com/corj/electron-quick-start.git -b master
2. $ npm install
3. $ npm start
4. With the application in foreground right click on the app tray
5. Access the window menu or press the test button

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
