### ISSUE TITLE
Rendering video subscribes to DOM mutation events

### ISSUE THREAD

**Issue by CharlieHess** [electron/electron#10636]
* Electron version: any `1.7.x` version, but _not_ `1.6.x`
* Operating system: macOS 10.12.6

### Expected behavior

Rendering a `<video>` should not have any effect on the `DOMNodeInserted` or `DOMNodeRemoved` events.

### Actual behavior

Rendering a `<video>` somehow hooks these events, greatly degrading performance on Electron `1.7.x`.

### How to reproduce

1. Download any `1.7.x` Electron release
2. Open Electron.app, then open the devTools
3. Add a `video` element to the page:
``` js
const vid = document.createElement('video');
document.body.appendChild(vid);
```
4. Add a click handler that adds / removes a bunch of DOM nodes:
``` js
document.body.onclick = () => {
  const br = document.createElement('br');
  for (let i = 0; i < 1000; i++) {
    document.body.appendChild(br);
    document.body.removeChild(br);
  }
}
```
5. Start profiling, then click on the page a bunch of times
6. Note that on each click, many `DOMNodeRemoved` / `DOMNodeInserted` events are fired

The mutation events do not appear _until_ the video element is inserted, and persist after the video element is removed.

The bug is not present in the current stable Chrome (61).

**Comment by CharlieHess** [comment]
Looks to be fixed in Chrome 59: https://chromium.googlesource.com/chromium/src/+/8e679697d635baa92d4927b2b4e838f125266af1%5E%21/

**Comment by codebytere** [comment]
@CharlieHess is this still happening in `1.8.x`?

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
