### ISSUE TITLE
Unable to debug on Visual Studio 2015

### ISSUE THREAD

**Issue by ixen-hj** [electron/electron#10638]
Hi, I'm new to Electron, just started out. Following the [Quick Start](https://electron.atom.io/docs/tutorial/quick-start/) guide. All working fine except that I wasn't able to debug the Main Process. I tried installing previous version 1.6.14 and below, VS2015 debugger gets automatically attached to process and I was able to debug well... I was wondering is this supposed to be intended for version 1.7 and above?

Electron version: 1.7.5 - 1.7.8
Operating system: Windows 10
IDE Use: Visual Studio 2015 Update 3

### Expected behavior

In Electron 1.6.6 (to 1.6.14), VS2015 managed to attach debugger on its own and hit the breakpoint on the first line. After I continue, the Hello World app shows up. All's good.

### Actual behavior

For Electron 1.7.x (1.7.5 til latest), when I hit F5 key, it's start up the Hello World app without entering debugging session.

### How to reproduce

1. Create a Blank node.JS project (requires NTVS)
2. npm install electron 1.7.8
3.  Use the code in main.js and index.html from the Quick Start guide.
4.  Go to properties of the console app project file. Where it says 'Node exe path:' put the path to electron.exe that was installed, which is in subfolder node_modules\electron\dist\electron.exe.
5. Put a breakpoint on the first line of createWindow in your main.js.
6. Start in debug: it will break at the breakpoint and if you continue it will show the basic electron app (which occurs on Electron 1.6.14).

**Comment by enlight** [comment]
Since you're attempting to debug JS code the issue is most likely with NTVS (or the version of NTVS you're using in VS2015). The [debug flags](https://github.com/electron/electron/pull/9473) changed in Electron 1.7.2. I would suggest using VSCode instead.

**Comment by sofianguy** [comment]
@ixen-hj let us know if you are having issues with an Electron bug
