### ISSUE TITLE
Drop URL to menu bar tray icon (on mac)

### ISSUE THREAD

**Issue by ckissi** [electron/electron#10635]
I didn't find the event which is fired when the URL (text) is dropped onto the menu bar tray icon. I can handle "drop-files" unfortunately nothing for URL/Text

**Comment by vanessayuenn** [comment]
@ckissi can you elaborate more on what you expect to happen vs what is actually happening? It will be helpful also if you can include steps to reproduce that behavior.

**Comment by sofianguy** [comment]
@ckissi 
Thank you for your issue!

We haven't gotten steps to reproduce this issue if drop-text isn't what you're looking for. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
