### ISSUE TITLE
Error installing @types/node when trying to install electron on NPM 1

### ISSUE THREAD

**Issue by seanspotatobusiness** [electron/electron#10632]
* Electron version: Whatever version is on NPN? I don't get that far.
* Operating system: antiX 16.2

### Expected behavior

I type npm install electron --save-dev --save-exact and electron gets installed.

### Actual behavior

I get the following error messages:

sean@Teleprompter:~
$ npm install electron --save-dev --save-exact
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'types/node' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'electron'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.4.10-antix.1-486-smp
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "electron" "--save-dev" "--save-exact"
npm ERR! cwd /home/sean
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/sean/npm-debug.log
npm ERR! not ok code 0
sean@Teleprompter:~
$ ^C
sean@Teleprompter:~
$ 

### How to reproduce

Type "npm install electron --save-dev --save-exact" at ROXTerm terminal.

Your best chance of getting this bug looked at quickly is to provide a REPOSITORY that can be cloned and run.

You can fork https://github.com/electron/electron-quick-start and include a link to the branch with your changes.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.

  $ git clone $YOUR_URL -b $BRANCH
  $ npm install
  $ npm start || electron .

-->

**Comment by malept** [comment]
You'll need to upgrade NPM to at least version 2. Scoped packages were introduced in that version.

@zeke perhaps we need to add that installation requirement to the docs?

**Comment by pdillon** [comment]
Getting a 404 on this - may be related. https://registry.yarnpkg.com/electron/-/electron-1.8.0.tgz

**Comment by malept** [comment]
@pdillon It's unrelated, see https://github.com/electron/electron/issues/10605

**Comment by MarshallOfSound** [comment]
As @malept said your npm needs to be updated
