### ISSUE TITLE
Document windows menu mnemonic

### ISSUE THREAD

**Issue by cwang22** [electron/electron#10637]
When constructing a menu, put a `&` in the label will add a mnemonic to it on Windows, which binds keyboard shortcut and displays underline when ALT is holden. but there's nowhere mentioned it in the document.

https://github.com/electron/electron/blob/master/docs/api/menu.md
https://github.com/electron/electron/blob/master/docs/api/menu-item.md

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR.
