### ISSUE TITLE
HTMLCanvasElement.toBlob sometimes fails

### ISSUE THREAD

**Issue by logidelic** [electron/electron#10648]
* Electron version: 1.7.8
* Operating system: Windows 10

### Expected behavior

`HTMLCanvasElement.toBlob` should work as per specs.

### Actual behavior

Sometimes `canvas.toBlob` will callback with an empty blob (`blob.size == 0`) even though the canvas is valid and has content.

### How to reproduce

```
git clone https://github.com/logidelic/electron-quick-start.git
cd electron-quick-start
npm install
npm start || electron .
```

- Make sure you have working camera (for the local video stream)
- Click Start
- `canvas.toBlob` gets called repeatedly on a small crop of the local video stream
- Wait a few minutes (for me < 5 minutes).
- When canvas.toBlob fails, you'll see an alert message. When you click OK you'll also see the canvas (crop) that failed.

Subsequent calls to toBlob on the same canvas work just fine.

### Other notes

- No error when running this HTML/JS in the latest version of Chrome browser.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
