### ISSUE TITLE
Can't load profile in performance tab in devtools

### ISSUE THREAD

**Issue by kutu** [electron/electron#10645]
* Electron version: 1.7.7, 1.7.8
* Operating system: Win7 64bit SP1

### Expected behavior

expected "open file" dialog to show up

### Actual behavior

nothing happening

### How to reproduce

1. launch electron without parameters, to launch default app
2. `ctrl+shift+i`
3. go to performance tab
4. right mouse click -> Load Profile

![untitled](https://user-images.githubusercontent.com/228802/30977644-4021a33e-a489-11e7-9871-ca6fda261b7f.png)

PS it also takes up to 8secs to test performance on that simple page

![untitled](https://user-images.githubusercontent.com/228802/30977752-90a77d24-a489-11e7-8e60-a3b755afc83d.png)

**Comment by bradennapier** [comment]
+1 - I saw this too and noticed a looping error complaining about a string being undefined.  I will tyr to post again but i updated to 1.8.1 and now my whole app crashes anyway :-P

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
