### ISSUE TITLE
Upgrade to Chromium 61

### ISSUE THREAD

**Issue by tzh2014** [electron/electron#10640]
Please consider upgrading the Chromium version to 61 as soon as possible. Chromium versions 58, 59 and 60 have a significant WebRTC bug[1] that may render the video unwatchable for WebRTC applications. The quality impact of this issue was considered so significant that it got merged into version 61 by the Chrome team[2].

As you can see from the screenshot, the quality impact of this bug is enormous and we should try to use Chromium versions that do not have this issue.
![corruption](https://user-images.githubusercontent.com/8780910/30963315-4eafe6a4-a44d-11e7-9acc-3731224ac931.png)

[1] https://bugs.chromium.org/p/webrtc/issues/detail?id=8028
[2] https://bugs.chromium.org/p/chromium/issues/detail?id=752886

**Comment by thomasjo** [comment]
See https://github.com/electron/electron/pull/10213.
