### ISSUE TITLE
Failed to register a ServiceWorker on Windows

### ISSUE THREAD

**Issue by joncombe** [electron/electron#10642]
* Electron version: 1.7.8
* Operating system: Windows 10 64bit

### Expected behavior

I should be able to register a local file service worker.

### Actual behavior

On Windows 10 I consistently see the error, `Error DOMException: Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/plain').` The code runs without issue on my macOS machine.

### How to reproduce

Run the simple `service-worker/mock-response` example from the https://github.com/hokein/electron-sample-apps project (not my code). 

```
git clone https://github.com/hokein/electron-sample-apps.git
npm install -g electron@1.7.8
electron service-worker/mock-response
```

**Comment by DaBs** [comment]
Ditto here, Windows 7 setup however, which indicates that the issue seems to be Windows related in general.

**Comment by DaBs** [comment]
@joncombe Do you have an update on the issue? Did you get it resolved?

**Comment by joncombe** [comment]
@DaBs The problem is ongoing. I have tried numerous workarounds but without success.

If anyone in the electron team could advise at least where I could start looking for fixes I would be happy to try.

**Comment by DaBs** [comment]
@joncombe I've managed to find a "fix". It seems that Chrome is internally reliant on some MIME type detection, where Windows can have a tendency of setting files ending in .js as being plain text files. [This is the bug on the chromium tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=762483), and the solution seems to be [found by following this comments instructions](https://bugs.chromium.org/p/chromium/issues/detail?id=762483#c9). 

After doing this, my service worker registered completely fine.

**Comment by DaBs** [comment]
@sofianguy This bug can be closed with a wont fix label, as this is not Electron, but Chromium having a "bug". However, the issue should be left up, so that others can find the solution at a later stage.

**Comment by joncombe** [comment]
Great find, @DaBs, well done. Thank you very much for your time and effort.

**Comment by DaBs** [comment]
@joncombe No worries. I'm guessing since you opened the bug, that you can also close it? I think it makes sense, as having open bugs that are not bugs are simply confusing :smiley:
