### ISSUE TITLE
Can't get callback(click or reply event) from Notification on MainProcess

### ISSUE THREAD

**Issue by Riokai** [electron/electron#10655]
* Electron version: 1.7.8
* Operating system: MacOS High Sierra(10.13)

### Expected behavior

Trigger callback when I click notification.

### Actual behavior

nothing happened.

### How to reproduce

```js
const { app, BrowserWindow, Notification, ipcMain, nativeImage } = require('electron')

ipcMain.on('notify', async (e, opts) => {
    const isSupported = Notification.isSupported()
    let icon;

    if (opts.url) {
      icon = await covertImage(opts.url)
    }

    console.log('isSupported', isSupported)

    if (!isSupported) return

    const data = {
      title: opts.title,
      body: opts.body,
      hasReply: opts.hasReply,
    };

    const notify = new Notification(icon ? Object.assign(data, { icon }) : data)

    notify.on('reply', (e, replyText) => {
      console.log('replayText', replyText)
    })

    notify.show()
  })
```

**Comment by javan** [comment]
> Trigger callback when I click notification.

Have you tried handling the `click` event? `notify.on('click', ...)`

**Comment by Riokai** [comment]
@javan 
![2017-09-30 11 28 32](https://user-images.githubusercontent.com/7970372/31042081-cc729f3c-a565-11e7-8bda-2fbaab18c189.gif)

**Comment by vanessayuenn** [comment]
@Riokai I'm unable to reproduce this using the code you provided (with electron 1.7.8 & macOS 10.12). Is this an issue also with slightly older macOS versions?

**Comment by vanessayuenn** [comment]
Update: I was able to reproduce this with macOS 10.13.

**Comment by MarshallOfSound** [comment]
@vanessayuenn I tried two different 10.13 devices, any specifics on how to repro?

**Comment by vanessayuenn** [comment]
@MarshallOfSound nope I pretty much just used the code @Riokai provided. Were you able to receive all the notification events? I'm getting none here.

**Comment by MarshallOfSound** [comment]
@vanessayuenn Ah looks like I simplified the code too much, it appears to be due to setting
`hasReply` to `true`

**Comment by MarshallOfSound** [comment]
@vanessayuenn Calling a bug in macOS that for some reason is causing notification memory references to change (so they look like different notification objects).  We can use notification `identifier`'s instead to unique identifier notifications
