### ISSUE TITLE
Remote objects are not connected to render process when whole app is bundled

### ISSUE THREAD

**Issue by vojtatranta** [electron/electron#10650]
* Electron version: 1.7.8
* Operating system: Mac (and others)

### Expected behavior
It should change system menu

### Actual behavior
Does not propage anyhow

### How to reproduce
Repo with reproduction code is here: https://github.com/vojtatranta/electron-problem

**Comment by vojtatranta** [comment]
I made that example very quickly, hopefully, it will show the problem correctly.

**Comment by vojtatranta** [comment]
Strangely though, if I did not bundle node_modules - I used it as externals in webpack, everything worked OK.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
