### ISSUE TITLE
webContents.downloadURL trigger will-download event of session not get webContent in callback 

### ISSUE THREAD

**Issue by imRainChen** [electron/electron#10653]
I use electron-dl for download file in electron 1.7.8 can not work.

Finally, i found downloadUrl method have something problem. It would make webContent is null in will-download event callback

* Electron version: 1.7.8
* Operating system: mac os

### Expected behavior
```JS
  win.webContents.session.on('will-download', (e, item, webContents) => {
    console.log(webContents)   // is object
  })
 
  win.webContents.downloadURL(args.url);
```

### Actual behavior
webContents is null.
```JS
  win.webContents.session.on('will-download', (e, item, webContents) => {
    console.log(webContents)   // is null
  })

  win.webContents.downloadURL(args.url);
```
### How to reproduce

```JS
ipcMain.on('download-btn', (e, args) => {
  let win = BrowserWindow.getFocusedWindow()
  win.webContents.session.on('will-download', (e, item, webContents) => {
    console.log(webContents)
  })

  win.webContents.downloadURL(args.url);
})
```

**Comment by imRainChen** [comment]
Is my error.
Give the url is wrong, but i thing if give me something message can let me find the problem.

**Comment by reallyimeric** [comment]
IMO electron should handle this instead of giving null webContents @deepak1556

**Comment by couturecraigj** [comment]
I agree.  Throw an error or even log to console.  This would allow people first time using this to know what is going on.
