### ISSUE TITLE
Question: How To Make Application Menu Styled Like Windows 10 Apps

### ISSUE THREAD

**Issue by 1-14x0r** [electron/electron#10654]
This is a question more then an issue. 

Is it possible to style the application menu like a windows 10 app. Or is this handled by disabling the frame, using css/js/html to make it look like window 10 app, and displaying a context menu on mouse click? See attached screen shot of this example with how slack looks like. Thank you!

![screenshot](https://i.imgur.com/MPpNWSi.png)

**Comment by rdzidziguri** [comment]
For me this is simple hamburger menu nothing different u u design fameless window and do whatever u want with pure CSS and HTML.

**Comment by codebytere** [comment]
@1-14x0r pls confirm that @rdzidziguri's answer solves your question, and then i'll close this issue!

**Comment by 1-14x0r** [comment]
@rdzidziguri thanx for the info, saved me some time poking around config for something that doesn't exist. 

@codebytere you can close ty.
