### ISSUE TITLE
Honor the OS's cursor blink settings

### ISSUE THREAD

**Issue by davidhfo** [electron/electron#10668]
* Electron version: Various, as tested by apps mentioned below
* Operating system: Windows, macOS, Linux

### Expected behavior

Electron should honor OS-level cursor blink settings.

Using Windows and Firefox as an example, here is what should be happening (thanks @jonathansampson for the gif):

<img src="https://cloud.githubusercontent.com/assets/815158/24823693/131bb71c-1bc7-11e7-8dd4-b969b1c86bbe.gif">

### Actual behavior

The cursor still blinks. The choices made by the user in his/her OS are ignored.

Aside from the OS’s settings not being honored, note that this is an accessibility issue for some ([example 1](https://discussions.apple.com/thread/7689487), [example 2](https://github.com/brave/browser-laptop/issues/8123)), and an irritation or frustration for many others. A google search for `turn off blinking cursor` produces [387,000 results](https://www.google.com/search?q=turn+off+blinking+cursor).

I tried various apps built using Electron ([Tusk](https://champloohq.github.io/tusk/), [Wavebox](https://wavebox.io/), [Wire](https://wire.com/en/), [Boostnote](https://boostnote.io/), [Brave](https://brave.com/), and [Min](https://minbrowser.github.io/min/)). In every app and on any OS, the result was the same: the cursor blinked, though I have the OS settings for cursor blinking turned off.

### How to reproduce

1. Change your respective OS’s setting for cursor blink to off.

    #### On Windows:

     - Set `HKEY_CURRENT_USER\Control Panel\Desktop\CursorBlinkRate` in the registry to `-1`.
     - OR (this will set the above value) navigate to Control Panel -> Keyboard, and under “Cursor blink rate,” move the slider all the way to the left.

    #### On macOS:
    Set values in the terminal approximating the following:
    ```
    defaults write -g NSTextInsertionPointBlinkPeriodOn -float 30000
    defaults write -g NSTextInsertionPointBlinkPeriodOff -float 1
    ```
    This input causes the cursor to be on for 30 seconds, off for just a millisecond, then on again. Though this is not technically “off,” with these values the blink is not noticeable and is as good as being off.

    #### On Linux:
    ##### GNOME
    Enter `gsettings set org.gnome.desktop.interface cursor-blink false` in a terminal.

     ##### Xfce
     - Enter `xfconf-query -c xsettings -p /Net/CursorBlink -s false` in a terminal.
     - OR (changes above value) navigate to the Keyboard settings and on the first tab (Behavior) uncheck “Show blinking” in the Cursor section.

     ##### MATE
     - Enter `gsettings set org.mate.interface cursor-blink false` in a terminal.
     - OR (changes above value) navigate to Preferences -> Keyboard and uncheck "Cursor blinks in text fields."

     ##### KDE (since 5.11)
     Edit the ~/.config/kdeglobals file, adding `CursorBlinkRate=0` to the `[KDE]` section.
<cr>

2. On macOS it may be necessary to then log out and back in. Within the other two OSes, the effect should be immediate.

3. Use _any_ app built with Electron. Place the cursor in any text field. It will continue to blink on steadily, irrespective of what you have just done with the blink rate settings.

Bonus: Thanks, [Charles A. Kiesling, Sr. (1930-2014)](https://docs.google.com/viewer?url=patentimages.storage.googleapis.com/pdfs/US3531796.pdf)!

(17/11/21) EDITED to add: Xfce cursor blink settings
(18/8/30) EDITED to add: MATE and KDE cursor blink settings

**Comment by MarshallOfSound** [comment]
@davidhfo Out of interest does Chrome respect this setting?

**Comment by davidhfo** [comment]
For the most part.

On macOS it does, as of [August last year](https://bugs.chromium.org/p/chromium/issues/detail?id=500168#c11).

On Windows it does for me as well (tried on two machines), though [for some](https://bugs.chromium.org/p/chromium/issues/detail?id=685726) either the Google start page or omnibar do not honor the setting, while all other text boxes do.

Likewise on Linux, my own experience is that only the omnibar does not respect the OS setting. Every other input box is fine.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by davidhfo** [comment]
@sofianguy I just tried the latest version of Wire today, which is utilizing Electron 4.0.0 beta 11. Cursor still blinks despite OS setting. So I can confirm that the issue remains.

**Comment by nikpmr** [comment]
This appears to have been an issue with Chromium in general. (See issue https://bugs.chromium.org/p/chromium/issues/detail?id=685726) I'm not entirely sure how Chrome _did_ fix the issue as it appears to be still unresolved in the Chromium project. 

Cursor blink is honored for me on the latest version of Chrome with the exception of the Google input box when a new tab is opened.

**Comment by davidhfo** [comment]
There's a little more info on the Chromium bug here:
https://bugs.chromium.org/p/chromium/issues/detail?id=500168

Cursor blink had been honored in Chromium, then there was a regression around v. 69, which has since been mostly fixed, except for on Linux (testing/confirmation needed).

However, even when Chromium was honoring the cursor blink, it was still an issue in Electron, which appears to continue to be the case.

**Comment by chrlsnchrg** [comment]
I can confirm that this issue is still present in electron 5.0.6-1 on Linux and driving certain users up the wall.
