### ISSUE TITLE
displaying errors when execute npm run dist.

### ISSUE THREAD

**Issue by salehmosleh** [electron/electron#10664]
when i execute `npm run dist` in cmd , nodejs show me an error , here is log file text : 
how can i fix it ?

> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dist' ]
2 info using npm@5.3.0
3 info using node@v8.4.0
4 verbose run-script [ 'predist', 'dist', 'postdist' ]
5 info lifecycle JPCReportsCenter@1.0.1~predist: JPCReportsCenter@1.0.1
6 info lifecycle JPCReportsCenter@1.0.1~dist: JPCReportsCenter@1.0.1
7 verbose lifecycle JPCReportsCenter@1.0.1~dist: unsafe-perm in lifecycle true
8 verbose lifecycle JPCReportsCenter@1.0.1~dist: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;E:\nodejs\bireport\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Rational\common;C:\wamp\bin\php\php5.5.12;C:\ProgramData\ComposerSetup\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Brackets\command;C:\Users\saleh mosleh\AppData\Roaming\Composer\vendor\bin;C:\Users\saleh mosleh\AppData\Local\Microsoft\WindowsApps;C:\Users\saleh mosleh\AppData\Roaming\npm
9 verbose lifecycle JPCReportsCenter@1.0.1~dist: CWD: E:\nodejs\bireport
10 silly lifecycle JPCReportsCenter@1.0.1~dist: Args: [ '/d /s /c', 'build --x64' ]
11 silly lifecycle JPCReportsCenter@1.0.1~dist: Returned: code: 4294967295  signal: null
12 info lifecycle JPCReportsCenter@1.0.1~dist: Failed to exec dist script
13 verbose stack Error: JPCReportsCenter@1.0.1 dist: `build --x64`
13 verbose stack Exit status 4294967295
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid JPCReportsCenter@1.0.1
15 verbose cwd E:\nodejs\bireport
16 verbose Windows_NT 10.0.14393
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dist"
18 verbose node v8.4.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 4294967295
22 error JPCReportsCenter@1.0.1 dist: `build --x64`
22 error Exit status 4294967295
23 error Failed at the JPCReportsCenter@1.0.1 dist script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 4294967295, true ]

**Comment by codebytere** [comment]
In order to begin to diagnose this issue, we need:
1. Electron Version
2. Operating System
3. Steps to repro

**Comment by sofianguy** [comment]
@salehmosleh 
Thank you for your issue!

We haven't gotten a response to our questions in our comment [here](https://github.com/electron/electron/issues/10664#issuecomment-333328132). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
