### ISSUE TITLE
Issue with intl api in the browsers

### ISSUE THREAD

**Issue by ziedhajsalah** [electron/electron#10669]
* Electron version: 1.7.8
* Operating system: ubuntu, windows

### Expected behavior
When I run this snippet in the console of chrome
```javascript
new Intl.NumberFormat('ar-TN', { style: 'currency', currency: 'TND'}).format(34);
```
I get the following result which is right:
```javascript
"د.ت.‏ 34,000"
```
### Actual behavior
But in the console of the electron BrowserWindow, I get this which is wrong:
```javascript
"٣٤٫٠٠٠ د.ت.‏"
```
See the difference between numbers formatting.

Is there a way to fix that?

**Comment by barinali** [comment]
I've tried to reproduce it on macOS. It seems that it's valid on macOS also.

**Comment by ziedhajsalah** [comment]
The same issue is happening in the devtools of atom, vsCode, mongodbCompass and every app that uses electron.

**Comment by vanessayuenn** [comment]
@ziedhajsalah seems like Chrome has inconsistent handling of the numbering system in certain locales, and was only supporting the base `ar` locale up to some versions. However, you can specify the numbering system to be used via unicode extension in part of your locale parameter: `new Intl.NumberFormat('ar-tn-u-nu-latn', { style: 'currency', currency: 'TND'}).format(34)`. I tested this to be working in both electron@1.7.8 and 1.8.1. ([more about unicode extension for `NumberFormat` here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#Locale_identification_and_negotiation))

**Comment by ziedhajsalah** [comment]
Thank you @vanessayuenn , this worked for me too.
