### ISSUE TITLE
how to change position of webview scrollbar to right ?

### ISSUE THREAD

**Issue by salehmosleh** [electron/electron#10663]
how can i change position of webview scrollbar to right ? `Dir="rtl"` does not work for it !
`<webview id="webview" src="http://mywebsite.co" class="webviewmain"></webview>`

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
