### ISSUE TITLE
Registered HTTP protocol handler drops charset parameter from Content-Type

### ISSUE THREAD

**Issue by skhrshin** [electron/electron#10662]
* Electron version: 1.7.8
* Operating system: Windows 10

I found that charset parameter in Content-Type field is dropped by registered HTTP protocol handler. This problem breaks non-ASCII characters in HTML contents without meta tag specifying their encodings.

Example:
```
const scheme = 'my.app';

const path = require('path');
const url = require('url');

const webEngine = require('electron');
const instance = webEngine.app;

function showError() {
  let mainWindow = new webEngine.BrowserWindow();

  mainWindow.loadURL(url.format({
    pathname: path.join(__dirname, 'error.html'),
    protocol: 'file:',
    slashes: true
  }));
}

function showMain() {
  let mainWindow = new webEngine.BrowserWindow();

  mainWindow.loadURL(url.format({
    pathname: '/',
    protocol: scheme + ':',
    slashes: true
  }));
}

instance.on('ready', () => {
  webEngine.protocol.registerHttpProtocol(scheme, (request, callback) => {
    callback({
      url: 'https://www.google.co.jp/'
    });
  }, (error) => {
    if (error) {
      showError();
    } else {
      showMain();
    }
  });
});

instance.on('window-all-closed', () => {
  instance.quit();
});
```

![broken_characters](https://user-images.githubusercontent.com/28780681/31041838-dd6caa5a-a5d6-11e7-9fe5-6987f342543d.png)

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
