### ISSUE TITLE
close event not fired on macOS if the window is opened as a modal

### ISSUE THREAD

**Issue by rongduan-zhu** [electron/electron#10674]
* Electron version: 1.6.10
* Operating system: macOS Sierra 10.12.6

### Expected behavior

The `close` event should be fired when the modal window is closed on Mac. It is fired on Windows.

### Actual behavior

The `close` event is not fired.

### How to reproduce

I have created a repro at this [repository](https://github.com/rongduan-zhu/electron-quick-start).

Just run `main.js` using electron.

The code essentially creates another modal window with the parent set to the main browser window. Created a `setTimeout` which closes the modal window after 3 seconds.

The modal window also listens to the `close` event and logs a message when the event is fired.

On Mac, the event listener callback is never called (nothing shows up in terminal). On Windows, the event listener callback is called (message shows up in terminal).

**Comment by rongduan-zhu** [comment]
Just realized that this also repros on ~1.7.8 which is the version I am using in the [repository](https://github.com/rongduan-zhu/electron-quick-start) I've created.

**Comment by xaviergonz** [comment]
@rongduan-zhu could you check if it also happens in 1.8.1?

**Comment by vanessayuenn** [comment]
can confirm it also happens in 1.8.1

**Comment by cumajkeee** [comment]
+ beforeunload event

**Comment by cumajkeee** [comment]
@vanessayuenn any updates for this issue?

**Comment by joernroeder** [comment]
same on 1.8.3

**Comment by percyhanna** [comment]
I also have this issue on 2.0.2.

**Comment by erickzhao** [comment]
Still happens to me on 3.1.x, 4.2.x, 5.0.x, and 6.0.x

**Comment by SimanovichSiarhei** [comment]
@zcbenz it's still reproducible with 6.1.7

**Comment by clusterberries** [comment]
Hello @erickzhao! Which Electron version contains fix? It is still reproduced with Electron v6.

**Comment by clusterberries** [comment]
Bug is not reproduced with Electron 7.1.11.

**Comment by erickzhao** [comment]
@clusterberries @SimanovichSiarhei 

Thanks for the observation, it is indeed fixed for all of Electron 7. 🙇 

So it seems like this fix never got backported into Electron 5/6 when I merged it in, which is the usual process. I don't remember if there was a reason why or if I just forgot.
