### ISSUE TITLE
Hidden Transparent Frameless window when shown, appears twice.

### ISSUE THREAD

**Issue by XEonAX** [electron/electron#10671]
* Electron version: Node.js 8.2.1, Chromium 59.0.3071.115, and Electron 1.8.1
* Operating system: Windows 10 v1703 x64

### Expected behavior
Hidden Transparent Frameless window when shown should appear only once.

### Actual behavior
Hidden Transparent Frameless window when shown appears once then disappears then appears again.

### How to reproduce
Make a SingleInstance application. Using https://github.com/electron/electron/issues/4478#issuecomment-199959813
Only use the MainWindow.Show statement of above comment.

Create a Frameless Transparent MainWindow. (Style the Body tag of Index.html with a White Background)

Once the Window is shown normally, Hide it.
Launch a new instance, Old Hidden window will be shown but it will disappear and will be shown again.

Repository to reproduce: https://github.com/XEonAX/jar-client/tree/Bug

Steps to run:
Open 2 terminal in repo directory.
In First run `npm install` followed by `npm start`
Wait for the window to appear.
Click Hide Button

In Second, run `npm start`
window will be shown twice.
To reproduce again. In Second, run `npm start`

It seems that the window disappears then appears again while returning from the app.MakeSingleInstance callback.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by Fental** [comment]
electron v8.2.4 still has this problem. Has anyone solved this problem?

**Comment by Fental** [comment]
> We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

electron v8.2.4 still has this problem. Has anyone solved this problem?
