### ISSUE TITLE
Strange effects while showing up of frameless main window

### ISSUE THREAD

**Issue by gozzoo** [electron/electron#10679]
I want to open a frameless window with dark background.

* Electron version: 1.6.9+, 1.7.8
* Operating system: Windows 10

### Expected behavior

I expect the window to open smoothly with no flickering. When it shows up it should stay focused and have the specified background color as soon as it becomes visible. I also expect the window to be frameless and I don't want the titlebar to be visible even for a fraction of second.

### Actual behavior

While the window shows up few strange / unexpected things happen:

- initially the background is white and it has empty light blue titlebar
- then it looses focus and some other gets in foreground
- then it gains focus again and the background is already dark, as specified

These effects are much more noticeable with 1.7.8.

### How to reproduce

Here is my code

```
let win = null;

function createWindow() {
  win = new BrowserWindow({
    width: 1280, height: 800,
    frame: false,
    backgroundColor: '#121212',
    show: true,
    resizable: false
  });
  win.show();
  
  let mainUrl = url.format({ 
    pathname: path.join(__dirname, '../dist/index.html'), 
    protocol: 'file:', 
    slashes: true 
  })
  win.loadURL(mainUrl);
  
  // win.webContents.openDevTools()

  win.on('closed', function () {
    win = null;
  });
}

app.on('ready', createWindow)

app.on('activate', () => {
  if (win === null) {
    createWindow()
  }
})
```

`show: false` doesn't seem to affect any of these effects

**Comment by sofianguy** [comment]
Does this issue persist on a later version of Electron, such as 1.8 or 2.0.0?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in the comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
