### ISSUE TITLE
Master tests failing on macOS

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#10685]
* Electron version: Master
* Operating system: macOS / MAS

Raising this in case I forget at some point 😆 Master tests have been failing on macOS and MAS since https://github.com/electron/electron/commit/745fa707dda6bd679ac91b7deb7e3d48a9c3b422

**Comment by jkleinsc** [comment]
It looks like the issue is with the test added  in #10508 
https://github.com/electron/electron/commit/745fa707dda6bd679ac91b7deb7e3d48a9c3b422#diff-9f96374ae8b155af079484ea59babffcR712
