### ISSUE TITLE
Protocol - retain headers in http request object

### ISSUE THREAD

**Issue by njbmartin** [electron/electron#10686]
* Electron version: 1.6.14
* Operating system: MacOS 10.12

### Expected behavior

https://github.com/electron/electron/blob/master/docs/api/protocol.md#protocolinterceptbufferprotocolscheme-handler-completion

I am currently trying to use `interceptBufferProtocol` to essentially inject a certificate to authenticate the `http` requests, as I don't want to inject it in the renderer process. This requires having to perform a new request, but without the original header information I currently need to write it again.

`interceptHttpProtocol` would of course make more sense, but you can't modify the original request, and in it's current form is nothing more than a simple redirect.

The request object is too limited and should try to give as much of the request data as possible.

### Actual behavior

`request` only provides the `url`, `referrer`, `method` and `uploadData`. It loses all other useful information such as the request's `header` object.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
