### ISSUE TITLE
Cannot display Menu OSX Sierra

### ISSUE THREAD

**Issue by Johnb21** [electron/electron#10684]
OS: OSX Sierra 10.12.6
Electron: 1.7.8

I have attempted to use several examples to display a Menu on my application. However, the page just displays blank with no menu bar at all. Here is my full script (nothing much, just jumping into Electron for the first time):

```
'use strict'
const {app, BrowserWindow, Menu} = require('electron')
const url = require('url')
const path = require('path')


let mainWindow;

app.on('ready', () => {
    mainWindow = new BrowserWindow({
        width: 1024,
        height: 768
    })


    mainWindow.loadURL(url.format({
        pathname: path.join(__dirname, '/src/mainWindow.html'),
        protocol: 'file:',
        slashes: true
    }))

    const menuTemplate = [
        {
            label: 'File'
        }
    ]
    const menu = Menu.buildFromTemplate(menuTemplate)

    Menu.setApplicationMenu(menu)

})
```

When I run the app, the window pops up but everything is blank (No Menu at all). 

<img width="1028" alt="screen shot 2017-10-03 at 6 47 46 pm" src="https://user-images.githubusercontent.com/1986312/31152750-716cb0c4-a86b-11e7-8125-559b016461a2.png">

Any help would be appreciated!

**Comment by MarshallOfSound** [comment]
@Johnb21 The menu on macOS application appears in the top Application bar (the thing going across the top of your screen).  macOS doesn't really have a concept of menus actually inside a window.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
