### ISSUE TITLE
Use environment variables with React in the renderer

### ISSUE THREAD

**Issue by popo63301** [electron/electron#10692]
I'd like to know how i can get environment variables using React in the renderer with "process.env.XXX". Any idea?

**Comment by MarshallOfSound** [comment]
In preload scripts or in renderer processes with `nodeIntegration` enabled you can use `process.env.ENV_VAR` just like normal

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
