### ISSUE TITLE
Webview segmentation fault

### ISSUE THREAD

**Issue by madasionka** [electron/electron#10691]
I am developing an `electron` app. It's a desktop version of an web application and the window is a webview. It was working fine until I changed the URL in the webview tag from the web application's address to `http://localhost:8000/`.  I wanted my app to act locally so I created a server for it and wanted to use localhost. Now it crashed 9 out of 10 times.

* Electron version: 1.8.1
* Operating system: Microsoft Windows 10 Pro

### Expected behavior

To work the same way it did, but with localhost.

### Actual behavior

The app crashes (sometimes right at the start, sometimes the page is loaded and then crashes) with the message: 

`/cygdrive/c/Users/Magda/AppData/Roaming/npm/electron: line 14: 26976 Segmentation fault      node "$basedir/node_modules/electron/cli.js" "$@"`

The error code differes each time, I had : 23340, 26976, 19500, 13752 and more.

### How to reproduce

I cannot provide you with the source code unfortunately - plus the code worked fine on a different computer (same system) so it's hard to reproduce - seems pretty random.

### Additional info

The error seems similiar to #10281.
Also I tried changing my index.html from this:

`<webview id = "webview" src = "http://localhost:8000/" style =
        "position: absolute; top: 0; left: 0; width: 100%; height: 100%; display: inline-flex;">
    <div class = "indicator"></div>
</webview>`

to this:

` <webview id = "webview" src = "http://localhost:8000/">
        <div class = "indicator"></div>
     </webview>
     <style>
     webview {
       position: absolute;
       top: 0;
       left: 0;
       width: 100%;
       height: 100%;
       display: inline-flex;
     }
      webview.hide {
        visibility: hidden;
      }
    </style>`

didn't help.

**Comment by madasionka** [comment]
Update: I investigated some more and I'm not sure if the problem is webview. The segfault occurs when I redirect the app to a local file instead asking the django server for it. So the app calls the function `defaultSession.webRequest.onBeforeRequest` which calls `registerHttpProtocol` and then crashes after a couple of requests (or doesn't - rarely). When I change back to the web app's  URL it works fine.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
