### ISSUE TITLE
Electron app uses full paths when loading a native module, thus only working on the computer it was packaged

### ISSUE THREAD

**Issue by pancho111203** [electron/electron#10695]
I'm having problems loading native modules on an Electron app built with Webpack. The error is this:
https://i.stack.imgur.com/tLk9Y.png

It's trying to load robotjs.node from the path "/Users/RUBI35900/..etc, which is from the computer I package the app (RUBI35900 is my development machine). And this error throws on a different machine. So it seems that webpack stores the full path instead of using a relative one, so it only works on the machine that was used for packaging the app.

Here is my webpack config:

Base:
https://i.stack.imgur.com/cYxUy.png
Main process:
https://i.stack.imgur.com/CKBa2.png
Renderer:
https://i.stack.imgur.com/D6XHX.png
https://i.stack.imgur.com/jQ5bg.png
https://i.stack.imgur.com/GfRmx.png

I'm not sure if this should go here or in the webpack repository.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by MarshallOfSound** [comment]
This is a webpack issue, you should ask in the community for help (as mentioned above) or ask on the webpack repository
