### ISSUE TITLE
Windows version of compiled app gives js error 

### ISSUE THREAD

**Issue by coreybruce** [electron/electron#10698]
Electron 1.7.8

Linux compiled app doesn't show any errors when I launch my application but the Windows version does, I found the culprit but don't know how to fix the error which has to do with the code that uses flash
path.join seems to be the one causing the issue in my code

here is my code

const {app, BrowserWindow} = require('electron');
const path = require('path')

var win

// Quit when all windows are closed.
app.on('window-all-closed', function() {
  if (process.platform != 'darwin')
  app.quit()
})

// Specify flash path, supposing it is placed in the same directory with main.js.
let pluginName
switch (process.platform) {
  case 'win':
    pluginName = 'pepflashplayer.dll'
    break
  case 'darwin':
    pluginName = 'PepperFlashPlayer.plugin'
    break
  case 'linux':
    pluginName = 'libpepflashplayer.so'
    break
}
//Disables VSync
app.commandLine.appendSwitch('disable-gpu-vsync')
//Dual GPU Support
app.commandLine.appendSwitch('supports-dual-gpu=true')

app.commandLine.appendSwitch('ppapi-flash-path', path.join(__dirname, pluginName))
// Optional: Specify flash version, for example, v17.0.0.169
app.commandLine.appendSwitch('ppapi-flash-version', '21.0.0.151')

app.on('ready', () => {
  let win = new BrowserWindow({
    width: 1350,
    height: 900,
    icon: __dirname + '/icon.png',
    webPreferences: {
      plugins: true,
      nodeIntegration: false
    }
  })
  win.loadURL('file://' + __dirname + '/index.html') // Load splash screen
  setTimeout(function () {
    win.loadURL('http://examplewebsite.com')
  }, 3000) // Load store page after 3 secs
  win.webContents.on('will-navigate', ev => {
  ev.preventDefault()
})
    // Emitted when the window is closed.
    win.on('closed', function() {
      // Remove mainWindow.on('closed', function() { if you want the menu back
      // Dereference the window object, usually you would store windows
      // in an array if your app supports multi windows, this is the time
      // when you should delete the corresponding element.
      mainWindow = null;
    })
  })

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by coreybruce** [comment]
Oh ok I'm sorry, I will move it to there.

**Comment by coreybruce** [comment]
Atom discuss community is useless, no one even bothered to help me when I asked and now I am stuck with a broken Windows version and don't know what to do...
