### ISSUE TITLE
window.open windows not visible when created from BrowserView with nativeWindowOpen enabled

### ISSUE THREAD

**Issue by gerges** [electron/electron#10707]
* Electron version: 1.7.8
* Operating system: MacOS Sierra 10.12.6

### Expected behavior
The new window should be opened, and visible

### Actual behavior
The new window is created, but it never becomes visible to the user. These windows can be accessed via the return of `window.open` and appear to be loading content internally.

### How to reproduce
Example repo here: https://github.com/gerges/electron-quick-start/tree/issue/browser-view-native-window-open

**Comment by qazbnm456** [comment]
I take your sample code, try it on Electron v1.8.1, and it turns out that this situation happened to 1.8.x series too.

**Comment by Anrock** [comment]
Any news on this?

**Comment by Anrock** [comment]
Also, parent browser view doesn't produce new-window event for me.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by Anrock** [comment]
@codebytere first comment in this issue claims it's reproducible in 1.8. 
And i just reproduced it with provided example project on 1.8.8, 2.0.10 and 3.0.0
