### ISSUE TITLE
Wrong cursor theme is Electron window on Linux

### ISSUE THREAD

**Issue by olegantonyan** [electron/electron#10705]
* Electron version: 1.7.8
* Operating system: openSUSE Tumbleweed x86-64 KDE

Cursor theme changes in Electron's window. This is probably default X11 theme, but I'm not 100% sure.
[Screenshot](https://yadi.sk/i/zsmloqaJ3NXrTV)
Originally found in Atom https://github.com/atom/atom/issues/15230

### Expected behavior

Do not change mouse cursor theme

### Actual behavior

Cursor theme changed to default X11

### How to reproduce

1. Install openSUSE with KDE (probably any other non-Ubuntu/Unity distro).
2. Run electron quick start https://github.com/electron/electron-quick-start (or install Atom 1.19.0+)
3. See how mouse cursor changes when you move it onto electron's window.

**Comment by olegantonyan** [comment]
Found a solution
Go to System Settings -> Application Style -> GTK and change Cursor theme. Doesn't matter what is the current gtk cursor theme, just change it to something and save https://yadi.sk/i/4K-fX65E3RccoC

I would still consider this a bug in electron since this KDE's setting does nothing except fixing the electron.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by crabvk** [comment]
Hi. I have the same issue but only on Wayland.

### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, with success.

### Issue Details

* **Electron Version:**
  * v11.0.2
* **Operating System:**
  * ArchLinux 5.9.10-arch1-1
  * sway 1.5.1 (wlroots 0.12.0)

### Screenshots
![screenshot](https://i.imgur.com/DQE0vM8.png)

If I run electron without `--enable-features=UseOzonePlatform` flag the cursor theme is ok.

**Comment by PopeRigby** [comment]
I'm also having this issue on Sway, but it only started happening after I installed the Breeze theme. After uninstalling Breeze, it went back to normal. Strange.

**Comment by crazyaccess** [comment]
Same in leftwm, and am using lxappearance for changing the cursor theme and stuff but well still the same problem

**Comment by hiornso** [comment]
I'm also having this issue with KDE Plasma on Wayland on Manjaro Linux (Arch-based). Same symptoms of only seeing the bug with the Ozone flags, all fine with Xwayland.
This is definitely still a persisting bug and I'm seeing it in electron 12.

**Comment by jgcodes2020** [comment]
@codebytere can we get this reopened? I am also having this issue with Electron 13.5.2 (vscode 1.65.0)

**Comment by gudvinr** [comment]
Yep, cursor under XWayland is fine, but native Wayland apps use Adwaita theme instead of the one installed in settings.

**Comment by hholst80** [comment]
I think there is quite obvious that there is a problem in the way Electron is handling xcursor logic. It might work in some environments like a native Gnome or KDE box but if you sandbox it and push it on the spec's you will see that Electron fails to implement what other applications such as QT handles just fine.

However, it is most likely an upstream issue because the Chromium flatpak will expose the same kind of misbehavior and not respect XCURSOR_SIZE even if Adwaita is available in the environment.

This probably is deep inside chromium so I don't expect this to be ever fixed.

https://neugierig.org/software/chromium/notes/2009/04/x-cursor-hack.html
