### ISSUE TITLE
Setting up tray icon localization labels

### ISSUE THREAD

**Issue by fabriciolelis** [electron/electron#10703]
* Electron version: 1.4.14
* Operating system: Windows
 
How can I do the tray menu labels localization?

**Comment by codebytere** [comment]
Could you explain your question a little more? You want to localize tray icon labels to other languages? thanks :)

**Comment by sofianguy** [comment]
@fabriciolelis 
Thank you for your issue!

We haven't gotten a response to our questions in our [comment](https://github.com/electron/electron/issues/10703#issuecomment-334940629). I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
