### ISSUE TITLE
start electron with main.js in path differ of root dir

### ISSUE THREAD

**Issue by marcosblastwer** [electron/electron#10704]
hi guys

I need to start my app /root/somepath/electron.js but an error occurs.
my folder structure is something like that:

root-folder
-- app1
----- electron.js
--- app2
---- electron.js
-- common
----- assets
-- package.json

my project include various app thats use the same package.json, so, the "main" key of the package.json had to set a default filename like "electron.js" but in differ locations because the apps use differ electron.js files

my package.json should be like this:

{
  "name": "myapp",
  "version": "1.0.0",
  "main": "electron.ts",
  "scripts": {
    "app1": "electron . ",
    "app2": "electron . ",
  },
  "devDependencies": {
    "electron": "^1.7.8",
    "eslint": "^4.7.2",
    "typescript": "^2.5.3"
  }
}

what I think in first place its include the location in scripts to indicate the main file dir, something like this script "electron . ./app1/electron.js"
but I didnt find anything about it on electron docs to do this

any ideas?

**Comment by enlight** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
