### ISSUE TITLE
BrowserWindow console cleared on reload

### ISSUE THREAD

**Issue by CzBuCHi** [electron/electron#10701]
* Electron version: 1.7.8
* Operating system: Windows 10

### Expected behavior
dev-tools console should keep its content when window is reloaded

### Actual behavior
dev-tools console is cleared on window reload

### How to reproduce

1) write anyting in BrowserWindow dev-tools console (AKA `console.write('anything')` in html page)
2) hit CTRL+R to reload window
3) console is cleared

---
**WHY**: when webpack HMR fails it prints warning to console and reload page - currently only way to see, why HMR failed is to hack webpack code and disable auto reloading ...

**Comment by brenca** [comment]
The console is cleared on reload on Chrome too.

**Comment by CzBuCHi** [comment]
ah ... dammit .. so it is chromium thing ... :( and im guessing it is impossible to store console log elsewhere and rewiter it after reload ... closing
