### ISSUE TITLE
Cannot run Electron application on macOS

### ISSUE THREAD

**Issue by avi12** [electron/electron#10702]
* Electron version: 1.7.5
* Operating system: Windows 10 1703 build 15063.608

I build my application for macOS using the following command:

    electron-packager . --platform=darwin --overwrite --out=release-builds --prune=true --icon=image/icon.icns --asar
To test it, I'm running macOS 10.13 via VirtualBox 5.1.28. I'm basically backing up the macOS build and downloading it as a ZIP file, which I extract later.
Once extracted, I attempt to click on my application, named SteamCMD GUI - but then I get this error:
![](https://i.imgur.com/vawkNik.png)

When clicking on "Show Details", the error expands and I get the following information:

    Process:               SteamCMD GUI [1052]
    Path:                  /private/var/folders/*/SteamCMD GUI.app/Contents/MacOS/SteamCMD GUI
    Identifier:            com.electron.steamcmd-gui
    Version:               0.0.1 (0.0.1)
    Code Type:             X86-64 (Native)
    Parent Process:        ??? [1]
    Responsible:           SteamCMD GUI [1052]
    User ID:               501
    
    Date/Time:             2017-09-30 14:06:05.612 -0700
    OS Version:            Mac OS X 10.13 (17A264c)
    Report Version:        12
    Anonymous UUID:        EF153BD9-8873-42AE-90E4-75C3B8AFBCC0
    
    
    Time Awake Since Boot: 17000 seconds
    
    System Integrity Protection: enabled
    
    Notes:                 Translocated Process
    
    Crashed Thread:        0
    
    Exception Type:        EXC_CRASH (SIGABRT)
    Exception Codes:       0x0000000000000000, 0x0000000000000000
    Exception Note:        EXC_CORPSE_NOTIFY
    
    Termination Reason:    DYLD, [0x1] Library missing
    
    Application Specific Information:
    dyld: launch, loading dependent libraries
    
    Dyld Error Message:
      Library not loaded: @rpath/Electron Framework.framework/Electron Framework
      Referenced from: /private/var/folders/*/SteamCMD GUI.app/Contents/MacOS/SteamCMD GUI
      Reason: no suitable image found.  Did find:
    	/private/var/folders/6h/mbl8677x5ljg1qng2_cj555h0000gn/T/AppTranslocation/44373627-3DE8-4D67-8D0A-196C9D930BCA/d/SteamCMD GUI.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
    	/private/var/folders/6h/mbl8677x5ljg1qng2_cj555h0000gn/T/AppTranslocation/44373627-3DE8-4D67-8D0A-196C9D930BCA/d/SteamCMD GUI.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1
    
    Binary Images:
           0x10b341000 -        0x10b341ff7 +com.electron.steamcmd-gui (0.0.1 - 0.0.1) <CB63147A-C9DC-308B-8CA1-EE92A5042E8E> /var/folders/*/SteamCMD GUI.app/Contents/MacOS/SteamCMD GUI
           0x10d2d0000 -        0x10d316417  dyld (510.8.3) <C3A32DFF-B9A9-3510-B840-EFCDEF4D58A0> /usr/lib/dyld
    
    Model: imacOS11,3, BootROM VirtualBox, 5 processors, 3 GHz, 10 GB, SMC 2.3f35
    Graphics: Display, PCI, 3 MB
    Memory Module: Bank 0/DIMM 0, 10 GB, DRAM, 1600 MHz, innotek GmbH, -
    Network Service: Ethernet, Ethernet, en0
    Serial ATA Device: VBOX HARDDISK, 84.83 GB
    Serial ATA Device: VBOX CD-ROM
    USB Device: USB Bus
    USB Device: USB Tablet
    USB Device: USB Keyboard
    Thunderbolt Bus:

**Comment by MarshallOfSound** [comment]
> macOS 10.13 via VirtualBox 5.1.28

As far as I am aware macOS can not be run on non-apple hardware.  So although you may have what appears to be a working VM we can't support any issue with this.  If this issue occurs on a legit macOS device we can look into it but a hackintosh VM can have so many issues that are completely unrelated to Electron

**Comment by karimhossenbux** [comment]
I got this error while building the mas version, and then the mac/win/linux version.\
Looks like it take the mas version from cache to build the standalone version?
doing a `npm clear cache` fixed it

**Comment by muenalan** [comment]
Today, this worked for me: 

> npm cache --force clean
