### ISSUE TITLE
"Uncaught Error: Specified procedure could not be found" in ELECTRON_ASAR.js on Windows 7

### ISSUE THREAD

**Issue by Zhuinden** [electron/electron#10717]
Operating system: Windows 7

### Expected behavior

The app is trying to load native file and should work.

### Actual behavior

```
Uncaught Error: The specified procedure could not be found.
\\?\C:\Users\Zhuinden\AppData\Local\Temp\A2DF.tmp.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\Apps\ElectronApp\resources\app.asar\node_modules\realm\lib\index.js:94:28)
    at Object.<anonymous> (F:\Apps\ElectronApp\resources\app.asar\node_modules\realm\lib\index.js:116:3)
```

-------------

I actually don't expect you guys to fix the problem that the procedure is not found on my PC, but it'd be nice if you could **improve the error message** so that you can tell ***what is the procedure that is not found***.

I have seen this same error with `The specified module is not found`, but that also does not contain the name of the module that failed to load.

**Comment by Zhuinden** [comment]
Interestingly, this error comes from the system itself. I guess I could file an issue at Windows so that they fix their error message? 😄 

Anyways, maybe Electron can add something regarding what DLL it is that fails.

After looking up a bit more on this error, I'm not sure if you guys can figure out what's wrong with it.

**Comment by sofianguy** [comment]
Hi @Zhuinden, can you provide us with steps to reproduce this error and the Electron version please?

**Comment by sofianguy** [comment]
@Zhuinden 
Thank you for your issue!

We haven't gotten a response to our questions in our [comment](https://github.com/electron/electron/issues/10717#issuecomment-335230468). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by Zhuinden** [comment]
I kinda gave up on it as well because there is no way for you to figure out what DLL is possibly missing from my Windows 7 computer. This is a native message, after all.
