### ISSUE TITLE
After clearStorageData callback doesn't get executed

### ISSUE THREAD

**Issue by Vj3k0** [electron/electron#10710]
* Electron version: 1.7.8
* Operating system: Mac OS 10.12.6

### Expected behavior

Calling clearStorageData on session should remove storage data and callback should be fired.

### Actual behavior

Storage data is cleared, but callback doesn't get called.

### How to reproduce

Sample here: https://github.com/Vj3k0/clearStorageDataBug

**Comment by javan** [comment]
If you're passing two arguments to `session.clearStorageData`, the first should be an object of options, not `null` like you have now. So either `session.clearStorageData({}, callback)` or `session.clearStorageData(callback)`.

**Comment by javan** [comment]
I *think* you only want to pass `options` to selectively clear data and that the default is to clear all.

**Comment by Vj3k0** [comment]
Thank you, that solved it, changing null to {}.
