### ISSUE TITLE
error C2039: 'GetArrayBufferAllocator': is not a member of 'v8::Isolate'

### ISSUE THREAD

**Issue by stefanopiovesan** [electron/electron#10718]
* Electron version: master branch
* Operating system: Windows10, VS2015 Update3

### Expected behavior
I should be able to compile node.dll for node @ dc8fe9d (Node fork to make it suitable for embedding in Electron)

### Actual behavior
Compiling node.vcxproj gives several errors
error C3083: 'TraceEventHelper': the symbol to the left of a '::' must be a type
error C2039: 'SetCurrentPlatform': is not a member of 'node::tracing'
error C2039: 'GetArrayBufferAllocator': is not a member of 'v8::Isolate'

### How to reproduce
clone this repo
https://github.com/electron/node/tree/dc8fe9d390b1deb32ae2601357a90679cbcc757e
and run vcbuild.bat

**Comment by elegos** [comment]
- **Electron version**: 1.8.1
- **Operating system**: Linux Fedora 27
- **Extra**: building libchromiumcontent manually

```
[787/1204] CXX obj/vendor/node/src/node.node_v8.o
FAILED: /usr/bin/clang++ -MMD -MF obj/vendor/node/src/node.tls_wrap.o.d '-DNODE_ARCH="x64"' '-DNODE_PLATFORM="linux"' -DNODE_WANT_INTERNALS=1 -DV8_DEPRECATION_WARNINGS=1 -DNODE_SHARED_MODE -DNODE_USE_V8_PLATFORM=0 '-DNODE_RELEASE_URLBASE="https://atom.io/download/electron"' -DHAVE_INSPECTOR=1 -DHAVE_OPENSSL=1 -D__POSIX__ -DHTTP_PARSER_STRICT=0 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_POSIX_C_SOURCE=200112 -DV8_USE_EXTERNAL_STARTUP_DATA -DV8_PROMISE_INTERNAL_FIELD_COUNT=1 -DSK_SUPPORT_LEGACY_GETTOPDEVICE -DSK_SUPPORT_LEGACY_BITMAP_CONFIG -DSK_SUPPORT_LEGACY_DEVICE_VIRTUAL_ISOPAQUE -DSK_SUPPORT_LEGACY_N32_NAME -DSK_SUPPORT_LEGACY_SETCONFIG -DSK_IGNORE_ETC1_SUPPORT -DSK_IGNORE_GPU_DITHER -DDISABLE_NACL -DTOOLKIT_VIEWS -DUSE_AURA -DUSE_X11 -DUSE_NSS_CERTS -DUSE_NSS -D_LARGEFILE64_SOURCE -DNDEBUG -I../../vendor/node/src -I../../vendor/node/tools/msvs/genfiles -I../../vendor/node/deps/uv/src/ares -Igen -I../../vendor/node/deps/openssl/openssl/include -I../../vendor/node/deps/zlib -I../../vendor/node/deps/http_parser -I../../vendor/node/deps/cares/include -I../../vendor/node/deps/uv/include -I/home/makerpm/rpmbuild/BUILD/electron/vendor/libchromiumcontent/dist/main/src -I/home/makerpm/rpmbuild/BUILD/electron/vendor/libchromiumcontent/dist/main/src/third_party/icu/source/common -I/home/makerpm/rpmbuild/BUILD/electron/vendor/libchromiumcontent/dist/main/src/third_party/icu/source/i18n -I/home/makerpm/rpmbuild/BUILD/electron/vendor/libchromiumcontent/dist/main/src/v8 -I/home/makerpm/rpmbuild/BUILD/electron/vendor/libchromiumcontent/dist/main/src/v8/include -Wno-inconsistent-missing-override -Wno-undefined-var-template -Wno-parentheses-equality -Wno-unused-function -Wno-sometimes-uninitialized -Wno-pointer-sign -Wno-string-plus-int -Wno-unused-variable -Wno-unused-value -Wno-deprecated-declarations -Wno-return-type -Wno-shift-negative-value -Wno-format -Wno-varargs -fPIC --sysroot=/ -m64 -march=x86-64 -O2 -g -fno-ident -fdata-sections -ffunction-sections -std=c++11 -D__STRICT_ANSI__ -fno-rtti  -c ../../vendor/node/src/tls_wrap.cc -o obj/vendor/node/src/node.tls_wrap.o
../../vendor/node/src/tls_wrap.cc:701:45: error: no member named 'GetArrayBufferAllocator' in 'v8::Isolate'
  auto* allocator = wrap->env()->isolate()->GetArrayBufferAllocator();
                    ~~~~~~~~~~~~~~~~~~~~~~  ^
1 error generated.
ninja: build stopped: subcommand failed.

Traceback (most recent call last):
  File "./script/create-dist.py", line 314, in <module>
    sys.exit(main())
  File "./script/create-dist.py", line 85, in main
    force_build()
  File "./script/create-dist.py", line 114, in force_build
    execute([sys.executable, build, '-c', 'Release'])
  File "/home/makerpm/rpmbuild/BUILD/electron/script/lib/util.py", line 174, in execute
    raise e
subprocess.CalledProcessError: Command '['/usr/bin/python', '/home/makerpm/rpmbuild/BUILD/electron/script/build.py', '-c', 'Release']' returned non-zero exit status 1
```

**Comment by orsonteodoro** [comment]
These two commits caused it:
https://github.com/electron/node/commit/45321d4843fd33719fe7cda20cd19fb5a630b91d#diff-801e3948990f4965a8ea4aca4a423864
https://github.com/electron/node/commit/e3d73c18f9120664e347f6f59f9e9a40076371b0#diff-801e3948990f4965a8ea4aca4a423864

You can try to revert 2 patches 

Download these two:
https://github.com/electron/node/commit/45321d4843fd33719fe7cda20cd19fb5a630b91d.diff
https://github.com/electron/node/commit/e3d73c18f9120664e347f6f59f9e9a40076371b0.diff

Use patch -R with each.

**Comment by orsonteodoro** [comment]
I removed the reversion and manually applied the patches in the libchromiumcontent/patches.  It seems to not trigger the problem.  It may be included in libchromiumcontent/patches/v8/001-array_buffer.patch .

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
