### ISSUE TITLE
Modal window does not appear on top of the parent window (Windows OS)

### ISSUE THREAD

**Issue by KiranNiranjan** [electron/electron#10721]
## Modal window does not appear on top of the parent window when the parent window is placed in a different monitor

* Electron version: 1.7.5
* Operating system: Windows 10

### Expected behavior

If the electron main window is placed in a different display/monitor other than primary display and opening the modal window should appear on top of the electron main window.
``This feature works fine on macOS``

### Actual behavior

Child modal window appears in the primary display rather than on the display/monitor the electron main window is present. 

## Temporary Fix / Workaround

Calculating the centre of the main window and updating the modal bound properties

```javascript 1.8

const { x, y, width, height } = parentWindow.getBounds();

const windowWidth = Math.round(width * 0.5);
const windowHeight = Math.round(height * 0.5);

// Calculating the center of the primary display
// to place the wrapper
const centerX = x + width / 2.0;
const centerY = y + height / 2.0;

// Update the child modal with the new values 
modalWindow.x = Math.round(centerX - (windowWidth / 2.0));
modalWindow.y = Math.round(centerY - (windowHeight / 2.0));

```

### How to reproduce

- $ git clone https://github.com/KiranNiranjan/electron-bugs/tree/electron-modal-issue
- $ npm install
- $ npm run start
- Connect another display to your machine
- Drag and drop the electron window onto secondary display
- Now press `modal` button
- The modal appears in primary display instead of the secondary display

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by TDola** [comment]
Still happens in Electron 7.1.1
