### ISSUE TITLE
为什么同步不了？？？

### ISSUE THREAD

**Issue by WLIG** [electron/electron#10735]
* Electron version:
* Operating system:

### How to reproduce

![qq 20171010174026](https://user-images.githubusercontent.com/17408336/31379832-1147adee-ade2-11e7-90bf-dec349ab0c98.png)

**Comment by sofianguy** [comment]
@WLIG 
Thank you for your issue!

We haven't gotten a response to our questions in our [comment](https://github.com/electron/electron/issues/10735#issuecomment-335418575). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
