### ISSUE TITLE
Unreferenced link in BrowserWindow docs page

### ISSUE THREAD

**Issue by anshumanv** [electron/electron#10738]
* Electron version: 1.6.11
* Operating system: W10 X64

### Expected behavior

The link should be properly referneced.

### Actual behavior

Link to Page Visibility API is not referenced correctly in https://github.com/electron/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions in the `backgroundThrottling` property.

Should I send a PR ?

**Comment by Toinane** [comment]
fixed in #11048 :) Thank you for your report!
