### ISSUE TITLE
Cursive fonts not cursive (Regression/never fixed)

### ISSUE THREAD

**Issue by teleclimber** [electron/electron#10733]
Please see this issue: #8286

The problem is still present in Electron 1.7.8 Mac 10.12.6

The default value for `cursive` font in `webPreferences` is `Script`. However that font doesn't appear to mean anything to OSX. If I set `font-family: 'Script';` on an element in Chrome on Mac it renders as Times.

I think the fix here is to set the default font on Mac for cursive to `Apple Chancery`.

Of course I can work around the problem by setting the font in `webPreferences` but I think the default behavior of Electron could be improved.

Thanks.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
