### ISSUE TITLE
screen.getAllDisplays() returns outdated info.

### ISSUE THREAD

**Issue by sebakerckhof** [electron/electron#10741]
I have a system with 1 monitor connected to my HDMI-1 output, when that monitor is in full HD mode when I run the following script on Debian stretch:
```js
const { screen } = require('electron')
const child_process = require('child_process');

(async () => {
  console.log("1", screen.getAllDisplays()[0].bounds.width)
  child_process.execSync(`DISPLAY=:0.0 xrandr --output HDMI-1 --mode 1024x768`);
  console.log("2", screen.getAllDisplays()[0].bounds.width)
  await new Promise(resolve => setTimeout(resolve, 1000));
  console.log("3", screen.getAllDisplays()[0].bounds.width)
})()
```

I get :
```
1 1920
2 1920
3 768
```

As you can see, at step 2 the information I get is outdated. I assume this information is cached by electron and not invalidated timely. To resolve this I would suggest to add a way to explicitly tell electron to refresh the screen information. It would also be useful if electron screen API would tell what port each display is connected to.

**Comment by sofianguy** [comment]
Hi @sebakerckhof, can you send us the following it would help us help you:
1) Electron version
2) operating system
3) steps to reproduce issue

**Comment by sebakerckhof** [comment]
HI @sofianguy .
1. Electron version: 1.7.8
2. OS: Tested with Ubuntu 16.04 and Debian stretch 
3. Steps to reproduce:
Here's a minimal reproduction that shows the problem: https://github.com/sebakerckhof/electron-screen-problem . Readme contains necessary info.

**Comment by jkleinsc** [comment]
@sebakerckhof `getAllDisplays` comes from chromium so we can't really change how it works, but I do have a solution for you.  

You can use the `display-metrics-changed` event on screen to know when the information for `getAllDisplays` has been updated: https://electron.atom.io/docs/all/#event-display-metrics-changed.

In turn you could create an async function to wait for the change, for example in your test case, we can fix it by doing the following:
```js
async function metricsUpdated() {
  return new Promise(resolve => {
    electron.screen.on('display-metrics-changed', function(ev, display){
      console.log(`Metrics changed`);
      resolve();
    });
  });
}

// Sets a new display mode (resolution)
async function pickNewMode(xScreen){
  const activeMode = xScreen.modes.find(m => m.current);
  const newMode = xScreen.modes.find(m => m.width !== activeMode.width || m.height !== activeMode.height);
  console.log(`Setting new mode on display (${xScreen.output}): ${newMode.width}x${newMode.height}`);
  await exec(`xrandr --output ${xScreen.output} --mode ${newMode.width}x${newMode.height}`)
  await metricsUpdated() //Wait until Electron has updated metrics
  console.log(`Display mode changed`);
}
```
