### ISSUE TITLE
WebGL Canvas R & B channels swapped

### ISSUE THREAD

**Issue by jocabola** [electron/electron#10755]
* Electron version: 1.7.9
* Operating system: OS X 10.12.6

**Warning:** This is happening with latest Nvidia Web Drivers (GTX 970). The problem is not happening with latest Google Chrome. Only within Electron.

### Expected behavior

When converting a WebGL Canvas to Image via blob or toDataURL the resulting image should look exactly like the original canvas.

### Actual behavior

Canvas displays normally. When performing a conversion to any kind of Blob / Buffer or simply converting to URL, R & B color channels are swapped. For instance, when performing a `window.open( canvas.toDataURL() );` the new window contains an image with swapped R & B channels compared to the original canvas.

This happens only when using WebGL. When using the 2D Context it seems to be fine.

### How to reproduce

Happens with Nvidia Web Drivers / GTX 970 / OS X 10.2.6 (This is not a standard Mac Setup!)

1) Within electron environment, have a simple WebGL/ThreeJs canvas with a red or blue mesh.
2) Execute _window.open( canvas.toDataURL() )_ where canvas is the actual HTML canvas containing the WebGL
3) The window will open with an image with red/blue channels swapped

Thx

**Comment by MarshallOfSound** [comment]
> This is happening with latest Nvidia Web Drivers (GTX 970). The problem is not happening with latest Google Chrome. Only within Electron.

Can you check if it occurs on `1.8.x` or in Chromium 58?

**Comment by jocabola** [comment]
Yes, this seems to be fixed in 1.8.1! Thanks!
