### ISSUE TITLE
Send message from index.html to webview

### ISSUE THREAD

**Issue by holgersindbaek** [electron/electron#10757]
I'm loading an online ReactJS app inside my Electron application through a webview. 

Now I want to send a message from Electron index.html to the webview, so I can trigger an action inside the webview.

This is the index.html file:
https://gist.github.com/holgersindbaek/fc3590d2fc9879ba83c9025e3822d1a2

I can't figure out how I sent a message from the index.html (line 32) that will trigger an action in the webview. Any suggestions?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by MarshallOfSound** [comment]
P.S. You want to check out the IPC docs (renderer and main) 👍

**Comment by holgersindbaek** [comment]
@MarshallOfSound If you where to take a quick look at my index.html file, you'd know that I've already taken a look at the IPC docs and that part of the system works fine.

Know I need to emit a message from my index.html file to my website loaded in a webview.

**Comment by holgersindbaek** [comment]
@MarshallOfSound If you have any suggestions, then please let me know at:

https://discuss.atom.io/t/send-message-from-index-html-to-online-webview/48444

I've written a more detailed explanation of what my issue is.

**Comment by MarshallOfSound** [comment]
@holgersindbaek It looks like you mistook IPC and traditionally window messages.  `window.addEventListener('message')` will not hook into IPC events.  In order to receive the message you send with `webview.send` you will need to have a `preload` script attached to your webview where you do

```js
const { ipcRenderer } = require('electron');

ipcRenderer.on('myMessage', () => {
  // Do stuff
});
```

**Comment by holgersindbaek** [comment]
I know they're two different things. And the IPC works fine. I can send a message from main.js to index.html and the other way around. What I can't do, is to send a message from index.html to the website I'm loading in the webview.

I've updated my question above, to include the preload script. If I put a console.log in the preload script, nothing gets outputted though, so I'm not sure it's getting loaded. If you look at the code, does it seem like I'm including it in a wrong way?

If the preload script worked and I was able to send a message from index.html and receive it in the preload script, how would that help me click a button (which is essentially what I want to do) within the website I'm loading?

Thanks for answering btw... I've been sitting for hours with this and I'm pretty stuck.

**Comment by kennethlynne** [comment]
I have solved this by proxying the messages to the sub-webview.

// Send to the main window contents as usual
```
mainWindow.webContents.send(CHANNEL, message);
```
Main window loads index.html and index.html renders a webview with a preload script.
```
ipcRenderer.on(CHANNEL, (event, message) => {
  $webview.send(CHANNEL, message);
});
```

The preload script contains this:
```
ipcRenderer.on(CHANNEL, (event, message) => {
  console.log(event, message);
});
```

**Comment by priyansh360** [comment]
You got any solution to send message from electron index.html to webview

**Comment by OlgaSukhoverkhaya** [comment]
After some research, I found a solution.
1. Ipc message should be sent after the _'did-stop-loading'_ of webview event is raised. 
https://www.electronjs.org/docs/api/webview-tag#event-did-finish-load
Sending in your **.js .ts file attached to a index page**. You can access a webview by tag name or id. This actually is working without getWebcontents() method too. : 
`(webview as WebviewTag).getWebContents().send('CHANNEL', 'message');`
Receiving in **webview preload** script: 
`ipcRenderer.on('CHANNEL', (event, data) =>{ console.log(data); })`

2. It's possible to send a message without _'did-stop-loading'_ event. For that you should at first create a channel inside a **webview preload** script. 
```
const { ipcRenderer } = require('electron')    
global.pingHost = () => {
  ipcRenderer.sendToHost('CHANNEL')
}
  pingHost();
```
And then inside the script attached to a **index page** reply to this message.
```
webview.addEventListener('ipc-message', event => {
        (webview as WebviewTag).send('CHANNEL', 'message');
          });
```
Receiving in **webview preload** script: 
`ipcRenderer.on('CHANNEL', (event, data) =>{ console.log(data); })`
