### ISSUE TITLE
Support app.getDefaultProtocolClient()

### ISSUE THREAD

**Issue by Ajeey** [electron/electron#10752]
* Electron version: 1.7.8
* Operating system: Mac & Win

### Expected behavior
Support an api that returns the protocol name as string which was set by `app.setAsDefaultProtocolClient("test")`

The new api should return `"test"`
### Actual behavior
Could not find relevant api.

**Comment by MarshallOfSound** [comment]
@Ajeey What is the purpose of such an API and does [isDefaultProtocolClient](https://electron.atom.io/docs/api/app/#appisdefaultprotocolclientprotocol-path-args-macos-windows) fulfill you purpose?

**Comment by Ajeey** [comment]
My bad. I guess its not needed. Feel free to close it :)
