### ISSUE TITLE
Transparency glitch

### ISSUE THREAD

**Issue by Kradre** [electron/electron#10750]
* Electron version: 1.7.9
* Operating system: Windows 7 x64

### Expected behavior

That simple code that should just show transparent window with image on it.

Main JS: 

`const electron = require('electron')
// Module to control application life.
const app = electron.app
// Module to create native browser window.
const BrowserWindow = electron.BrowserWindow

const path = require('path')
const url = require('url')

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
let mainWindow

function createWindow () {
  // Create the browser window.
  mainWindow = new BrowserWindow({width: 800, height: 600, frame: false, transparent: true})
  // mainWindow2 = new BrowserWindow({width: 800, height: 600})
  // and load the index.html of the app.
  mainWindow.loadURL(url.format({
    pathname: path.join(__dirname, 'index.html'),
    protocol: 'file:',
    slashes: true
  }))
  // mainWindow2.loadURL(url.format({
    // pathname: path.join('kradre.com'),
    // protocol: 'http:',
    // slashes: true
  // }))

  // Open the DevTools.
  // mainWindow.webContents.openDevTools()
// mainWindow2.on('closed', function () {
    // mainWindow2 = null
  // })
  // Emitted when the window is closed.
  mainWindow.on('closed', function () {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null
  })
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow)

// Quit when all windows are closed.
app.on('window-all-closed', function () {
  // On OS X it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', function () {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (mainWindow === null) {
    createWindow()
  }
})

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.
`
index.html

`<!DOCTYPE html>
<html>
  <head>
	<link rel="stylesheet" href="css/bootstrap.min.css">
    <meta charset="UTF-8">
    <title>Hello World!</title>
	<style>
		html, body {
			background: rgba(0, 0, 0, 145);
			-webkit-app-region: drag;
		}
	</style>
  </head>
  <body>
		<img src="http://ourcodeworld.com/resources/img/ocw-empty.png" width="300" height="300"/>
		<h1>Hello World!</h1>
    

	
	<script src="js/jquery-3.2.1.slim.min.js"></script>
	<script src="js/popper.min.js"></script>
	<script src="js/bootstrap.min.js"></script>
    <script>
      // You can also require other files to run in this process
      require('./renderer.js')
    </script>
  </body>
</html>
`

### Actual behavior

![The view of window](https://i.imgur.com/Jz3XYf3.png)
It's not showing up, untill some other window would be dragged over it. After that, it shows completely, but without any transparency and with some lagging leftovers of other windows over it.

### How to reproduce

Clone electron-quick-start and change code inside it on this one.

**Comment by wulunyi** [comment]
And set thickFrame false on windows

**Comment by nitsakh** [comment]
> On Windows operating systems, transparent windows will not work when DWM is disabled.

DWM is disabled for Windows 7 classic and basic themes. If you're on one of those, transparent windows will not work as per the documentation.
