### ISSUE TITLE
Release file at https://github.com/electron/electron/releases/download/v1.7.9/electron-v1.7.9-linux-arm.zip does not match SHASUM256.txt

### ISSUE THREAD

**Issue by adamyellen** [electron/electron#10760]
* Electron version: 1.7.9
* Operating system: Linux/ARM

The release file at https://github.com/electron/electron/releases/download/v1.7.9/electron-v1.7.9-linux-arm.zip has a SHA256 checksum value of: 7ec366ec543858bf4f53a944fdafff37995be1771498fb4d4a89814b3d93a923

The corresponding SHASUMS256.txt file at https://github.com/electron/electron/releases/download/v1.7.9/SHASUMS256.txt lists the value as: 9c4f0ad93cd41ea8f3c2bf3c4ec99fc7254126943ea3b1e9f86c1b148cc982ef

I spot-checked another file (electron-v1.7.9-linux-ia32.zip) and it was fine.

**Comment by Kugelfang666** [comment]
i just tried to install magic mirror with the proposed installer on an fresh RBPi running latest Jessie and it failed because of this error.

**Comment by jkleinsc** [comment]
@adamyellen @Kugelfang666 I am fixing the issue now.

**Comment by jkleinsc** [comment]
This issue has now been fixed.

**Comment by adamyellen** [comment]
Thank you very much!
