### ISSUE TITLE
Hard crash when using webRequest handlers in 1.8.1

### ISSUE THREAD

**Issue by Thomas101** [electron/electron#10766]
* Electron version: 1.8.1. Not present 1.7.x
* Operating system: macOS 10.12.6

This may be related to https://github.com/electron/electron/issues/10651, the final error looks similar but the reproduction method is completely different

### Expected behavior

Electron should not crash after adding a webRequest handler such as...
```js
mainWindow.webContents.session.webRequest.onCompleted((evt) => console.log('complete', evt.url))
```

### Actual behavior

On certain urls (https://mail.google.com as an example), adding an `onCompleted`, `onBeforeRequest`, etc handler, and then reloading or navigating away from the page causes a hard crash producing an `EXC_BAD_ACCESS` error

[Full crash log](https://github.com/electron/electron/files/1378484/log.txt)

### How to reproduce

1. Install quick-start
```
git clone https://github.com/wavebox/electron-quick-start.git
cd electron-quick-start
git checkout 1_8_1_crash
npm install
npm start
```
2. Login to a google account
3. Reload with <kbd>cmd</kbd>+<kbd>R</kbd>

Removing the `onCompleted` handler in `main.js` stops the crash

**Comment by qazbnm456** [comment]
Hi @Thomas101 , fyi, this problem has been addressed and resolved in https://github.com/electron/electron/pull/10676, and the root cause is not the same as https://github.com/electron/electron/issues/10651 actually.

**Comment by Thomas101** [comment]
@qazbnm456 thanks for the update! If it's fixed, I'll close this off and look forward to 1.8.2 :)

**Comment by qazbnm456** [comment]
@Thomas101 FYI, the version 1.8.2-beta.1 just released. You may try it and see if it works well. 😄
