### ISSUE TITLE
WebBluetooth: Implement device selection events at renderer

### ISSUE THREAD

**Issue by daumling** [electron/electron#10764]
Currently, the _bluetooth-select-device_ event is within the main process. If the user wants to mimick standard WebBluetooth behavior, the renderer process needs to display a dialog.

Also, receiving a long list of devices (with many duplicates!) is not user-friendly. The user needs to see devices as they are found. Often, a devices is found only after turning it off and on again.

Following suggestion: Implement _bluetooth-select-device_ on the renderer side, with a single argument, the callback.

Implement a _bluetooth-device-found_ event; its argument should be a standard BluetoothDevice instance with an "id" property instead of a "deviceId" property.

The user could display an empty dialog on the former event and remember the callback. On the latter events, the user would fill the dialog.

The dialog could event become part of the standard Electron package. See, for example, the file DeviceChooserUI.js in the web-bluetooth-polyfill package for an implementation.

* Electron version: 1.7.8
* Operating system: Mac OS 10.12.6

**Comment by MarshallOfSound** [comment]
@daumling The event is in the main process because that is where the Chromium logic is (the browser process).  If you want to do selection in the renderer process you should use the IPC modules to send the required information between processes.

**Comment by daumling** [comment]
True; the goal, however, is (unless I am mistaken) to make the transition from a web page to Electron a painless process. It is not painless having to rewrite the Bluetooth device selection dialog from scratch, and offer the user a different user experience. Since the dialog is attached to the web page, it makes sense to have the renderer process display that dialog. Yes, the main process could open a window, but positioning that window would be awkward at least. My argument stands.

**Comment by MarshallOfSound** [comment]
> Yes, the main process could open a window, but positioning that window would be awkward at least. My argument stands.

I don't think you understand what I was saying, you need logic like so

```
* Hook event in main process
* Send message to renderer process with device list
* Show UI in renderer process
* Send selected device to main process
* Call callback
```

This is a reasonably well-used pattern

**Comment by daumling** [comment]
Thank you for your time to answer me!

We are exactly on the same page; that's what I am doing right now.

My suggestion would just make Web Bluetooth programming easier; also, the dialog that I display right now needs to display something like "Scanning, please wait", and it will be populated by all devices at once, which is not very user friendly. I, for example, have a device that needs to be turned off an on from time to time to make it appear in the regular Web Bluetooth dialog. This would not happen with my current implementation; the dialog would sit for several seconds, than not display the device. The user would have to close and re-open the dialog after toggling power to see the device.

Also, the transition from a Web Bluetooth enabled web app to an Electron app would not be as painless as possible, because the programmer needs to hard-code the select dialog. This was a big surprise to me at first when I ported a Web Bluetooth web app to Electron; I expected the selection dialog to pop up just as on Mac OS and Chrome OS (and Windows with web-bluetooth-polyfill for that sake).

Well, it was just a suggestion that you might keep in mind for the future; it would be good to integrate a standard selection dialog into Electron, because that is what a programmer would expect to see.

Now, I just have to wait for a comment on issue #10763 so I can continue :)

Thanks, Michael

**Comment by aj-ptw** [comment]
@daumling I see your point and think it's valid

**Comment by aramperez** [comment]
Sorry, but I missed this issue and created a similar issue, see issue [#11865](https://github.com/electron/electron/issues/11865). I believe my issue can be combined/merge with this one. I fully agree with @daumling.

/Aram
