### ISSUE TITLE
broken task bar

### ISSUE THREAD

**Issue by kylerchin** [electron/electron#10765]
* Electron version: 1.7.9
* Operating system: Linux
@zeke 
### Expected behavior

Should open window that was started initially when clicking task bar.

### Actual behavior

Opens strange disappering window.

### How to reproduce

  $ git clone $YOUR_URL -b $BRANCH
  $ npm install
  $ npm start || electron .

https://github.com/solariot/app DEVEL branch

**Comment by zeke** [comment]
@kylerchin are you still facing this issue?

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
