### ISSUE TITLE
Win10 cannot jump out of the virtual keyboard

### ISSUE THREAD

**Issue by zhangwei8k** [electron/electron#10761]
* Electron version:1.7.9
* Operating system:Windows10

### Expected behavior

When v0.35.4 program in Windows 10 (Is not tablet mode), click the input TAB, will automatically jump out of the Windows 10 virtual keyboard (for touch screen), now the version of the Windows 10 (Is not  tablet mode), does not automatically jump out of Windows 10 virtual keyboard.

### Actual behavior

does not automatically jump out of Windows 10 virtual keyboard.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by appskitchen** [comment]
@codebytere This happens in electron 4x too in windows 10 1803.
