### ISSUE TITLE
Electron is hang when calling webDriver.executeScript in the no-sandbox mode

### ISSUE THREAD

**Issue by FuShuhui** [electron/electron#10770]
* Electron version: current version 
* Operating system: window 10

### Expected behavior
Launch Electron app by adding --remote-debugging-port=1234;
Start ChromeDriver using the debuggerAddress=1234;
If I executeScript to click a link which not navigate.
It works fine.

When I try to executeScript using the chromeDriver to click a link which will navigate to another page.
var link = document.getElementById("...");
link.click();

The executeScript will not return and the link is click but the page is not navigating.
I check the chromedriver log, The last command is waiting for pending navigations. 
So I guess after the link.click and it cause the navigation, 
A new webcontents is created which can be found by a new render process is created.
So chromedriver is check the navigation by send http request to the old webcontents which is destroyed or will be destroyed.
Cause the response not back.
So How can I solve this issue? 

BTW, everything works fine when launch electron app in  --enable-sandbox.
Only one process when link clicked, even click cause a navigation.

### Actual behavior
Electron should not be hang.  
WebDrive executeScript should return as well.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
