### ISSUE TITLE
Incorrect window size when maximizing with min/maxWidth on Windows 10

### ISSUE THREAD

**Issue by Agamnentzar** [electron/electron#10779]
* Electron version: 1.7.9
* Operating system: Windows 10
* Screen scaling is set to 100%

### Expected behavior

Window width is always 300px

### Actual behavior

Window width changes unexpectedly

### How to reproduce

```bash
git clone git@github.com:Agamnentzar/electron-bug.git
npm install
npm run start
```
1. use `Maximize / Restore` button to maximize window (window width should be 300px but is 286px)
2. use `Maximize / Restore` button to restore window (window width should be 300px but is 314px)
3. drag window with orange drag region (the window width fixes itself)

The same result are achieved by double clicking drag region or using system keyboard shortcuts for maximize/restore

![preview2](https://user-images.githubusercontent.com/572298/31515420-6bd01620-af95-11e7-94fd-59b77c3e71f4.gif)

Code:
```javascript
const { BrowserWindow, app } = require('electron');
const windowWidth = 300;

app.on('ready', () => {
  const mainWindow = new BrowserWindow({
    hasShadow: true,
    frame: false,
    width: windowWidth,
    height: 400,
    maxWidth: windowWidth,
    minWidth: windowWidth,
  });

  mainWindow.loadURL('file:///./index.html');
});
```

**Comment by murray971** [comment]
I get a similar issue when going full screen and then hitting esc to exit.  which ever size I go to its always a little bit smaller.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!

**Comment by ozankonur** [comment]
I am getting same issue on version 6.0.12

**Comment by ML6503** [comment]
I am getting same issue on version 7.1.10
