### ISSUE TITLE
Can't install extension in DevTools

### ISSUE THREAD

**Issue by zlbben** [electron/electron#10772]
* Electron version: 1.7.x
* Operating system: macOS 10.12.6

Hi ,  now it can't open a DevTools inside a webview [#3177](https://github.com/electron/electron/issues/3177) ,  so I'm loading a remote DevTools front-end in a webview by ```remote-debugging-port```.

I want to install extension in DevTools like Chrome , but I don't find a way to install it .

So , i use custom [DevTools](https://github.com/ChromeDevTools/devtools-frontend) (```custom-devtools-frontend```) that can install extension , but it don't work in electron.

Sorry to bother you, , but is there any way to do this or electron just does not support this.

**Comment by codebytere** [comment]
I don't think this is possible with electron at the moment, and i'm not sure it's something we'd support in the future, sorry!
