### ISSUE TITLE
Documentation and TypeDefinition for app.getGpuFeatureStatus is wrong 

### ISSUE THREAD

**Issue by GregorBiswanger** [electron/electron#10788]
Hello,

the Documentation and the TypeScript TypeDefinition says that "app.getGpuFeatureStatus" would be right but the valid code is "app.getG**PU**FeatureStatus".

I used Electron Version 1.7.8.

Thank you

**Comment by MarshallOfSound** [comment]
@GregorBiswanger This is correct on master, the docs fixes only go into latest minor releases, so 1.8.x releases contain the docs fix (and therefore the typescript fix)

See https://github.com/electron/electron/blob/master/docs/api/app.md#appgetgpufeaturestatus
