### ISSUE TITLE
请问如何调试devtools自己

### ISSUE THREAD

**Issue by zerocode1337** [electron/electron#10782]
* Electron version: 1.8.0
* Operating system: mac os

### 问题背景

我修改了libchromiumcontent里的devtools，把pak文件放到electron
编译后发现控制台的console message部分有错位问题，并且高度多了一块

### 问题

在chrome中可以通过快捷键调试devtools本身，但是electron使用
快捷键后，只能打开一个控制台，所以请问：如何在electron中用devtools调试它本身呢？
感谢大佬查看这个问题。

**Comment by hxkuc** [comment]
哈哈，能看得懂么

**Comment by vanessayuenn** [comment]
The question was asking how to debug the devtools within electron; I believe they refer to the chrome browser's ability to open up a devtool to inspect the browser itself. To answer @zerocode1337, unfortunately electron does not currently support that functionality.

**Comment by zerocode1337** [comment]
Thanks, I try to debug this problem in chrome's devtools.

**Comment by zerocode1337** [comment]
@vanessayuenn  Thanks, I try to debug this problem in chrome's devtools.

**Comment by sofianguy** [comment]
@zerocode1337 I am closing this issue, but feel free to reach out if you are still having issues and we'll reopen.
