### ISSUE TITLE
Extra "/" being appended when try to launch app via browser via custom protocol.

### ISSUE THREAD

**Issue by Ajeey** [electron/electron#10786]
* Electron version: 1.6.6, 1.7.8, 1.7.9
* Operating system: Windows 10

### Expected behavior
When launching the app from the custom protocol handler via browser. The electron app is adding an extra "/" to the data passed down by the browser.

Open any browser and try to launch the app via the registered protocol handler of your electron app.
Ex - 
`myapp://param123`

And in the electron app, if I try to read this via the process arguments(`process.argv.slice(1)`), I get should get - 
`myapp://param123` <-- same as what I passed in the browser

### Actual behavior
I am getting the following - 
`myapp://param123/` <-- notice the extra "/" being appended.

Whereas, if I try to launch the app via command line - 
`./path/to/.exe param123`
I do not have this problem

My use case is I want to launch the app via command line and via browser. And the extra "/" when launched via browser means I would have to write additional check. Can we have the same behavior here?

### How to reproduce
https://github.com/oikonomopo/electron-deep-linking-mac-win

P.S Not this problem is not on mac.

**Comment by MarshallOfSound** [comment]
@Ajeey Electron won't be adding this, we actually can't.  If your directly reading `process.argv` then the browser is adding it.

For instance here is another user independent of Electron experiencing the same thing: https://stackoverflow.com/questions/11971904/trailing-slash-is-added-in-arguments

Gonna close this out as its not something Electron is responsible for.
