### ISSUE TITLE
MAJOR BREAKING CHANGES

### ISSUE THREAD

**Issue by GregTheGreek** [electron/electron#10797]
I am currently at ethWaterloo and have found a major issue with installing electron by default.

When installing it installs v1.7.9 which is not the latest version.

Please change this to make it v1.6.15.

**Comment by robinwassen** [comment]
1.7.9 is the latest version.

1.6.15 is just a security patch applied to the last minor version.

**Comment by GregTheGreek** [comment]
@robinwassen I believe you since it is the newest numbered version but it does not seem to be the case on github.

![screen shot 2017-10-14 at 19 35 55](https://user-images.githubusercontent.com/16929357/31580213-0138b406-b117-11e7-87c7-10aac4ba8911.png)

**Comment by MarshallOfSound** [comment]
Githubs "latest version" is based on date not based on the version number. 1.6.15 is a backported release, 1.7.9 is the latest release.

**Comment by GregTheGreek** [comment]
I don't think this should be closed. Because the is something wrong with 1.7.9.

**Comment by GregTheGreek** [comment]
Because it causes a node_modules_version clash. Requiring 54

**Comment by MarshallOfSound** [comment]
> Because the is something wrong with 1.7.9.

The node_modules_version changes every chromium update, the change from 1.6 to 1.7 is expected, there is nothing wrong with the 1.7.9 release 👍
