### ISSUE TITLE
Tray on-click does not give any coordinates in bounds in Gnome

### ISSUE THREAD

**Issue by asayuki** [electron/electron#10790]
* Electron version: v1.7.9
* Operating system: Debian 9 Stretch with Gnome 3.22.2

### Expected behavior

The expected behavior as in OSX and Windows is that bounds should return coordinates for where I clicked that tray-icon.

### Actual behavior

Bounds return x: 0, y: 0, height: 0, width: 0

### How to reproduce

  $ git clone https://github.com/asayuki/electronTrayIssueLinux.git -b master
  $ npm install
  $ npm start

**Comment by ArvindNair001** [comment]
@asayuki Did you get it fixed. I'm facing the same problem, I've hard coded it for now, also I would be glad to hear your solution.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
