### ISSUE TITLE
Can I remove *.tmp.ico files when NativeImage has been destroyed?

### ISSUE THREAD

**Issue by yuya-oc** [electron/electron#10796]
* Electron version: 1.8.1
* Operating system:

### Expected behavior
Remove temporary *.tmp.ico files when nativeImage has been destroyed.

### Actual behavior
NativeImage creates temporary .ico when the files is archived in .asar archive. Actually I'm using it in Tray.
https://github.com/electron/electron/blob/v1.8.1/atom/common/api/atom_api_native_image.cc#L168-L184

Then files remain after the Electron app finishes. So a huge number of .ico files would exist in the temp folder.

### How to reproduce
1. Create a nativeImage with .ico archived in .asar.
2. Quit the Electron application.

**Comment by codebytere** [comment]
I believe you can, yes!
