### ISSUE TITLE
What to feed Closure Compiler to make it understand Electron's stuff?

### ISSUE THREAD

**Issue by FjicdeiwFeiej** [electron/electron#10798]
I try to Closure Compile my final.js (yes, this is required). No matter what I do, I always get errors such as "ERROR - variable require is undeclared" and a bunch of similar stuff which clearly has to do with CC not understanding the things that Electron provides. I need to add an "--extern", but what exactly? I've looked through the whole Electron Github source tree but find nothing that it accepts.

Where is the "combined.js" blob with everything that Electron uses so that CC doesn't get confused when I refer to these normally unknown entities in my final.js?

**Comment by MarshallOfSound** [comment]
@FjicdeiwFeiej You probably just need to follow the examples that make Closure Compiler work for Node.JS and it should work for Electron as well (require is a node thing)

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by FjicdeiwFeiej** [comment]
Where are those examples you speak of?

**Comment by FjicdeiwFeiej** [comment]
I find nothing.

**Comment by MarshallOfSound** [comment]
Cursory google search seems to indicate the `--process_common_js_modules` flag will help, as previously mentioned though, please ask questions in the relevant communities 👍

**Comment by FjicdeiwFeiej** [comment]
I've tried that flag already, as well as 10000 other ones. Nothing changes.

And I don't have any accounts anywhere except here. This is an actual issue, after all.

**Comment by FjicdeiwFeiej** [comment]
Anyone? I've sat here like a fucking moron and tried one thing after another for days now.
