### ISSUE TITLE
White flashing parts when resizing window?

### ISSUE THREAD

**Issue by FjicdeiwFeiej** [electron/electron#10801]
My Electron application has a dark visual background (on the body). When I resize the window, you can see white background flashing briefly in a very annoying way in the bottom and right borders. How do I prevent this from happening? Why does it happen in the first place?

**Comment by robinwassen** [comment]
@FjicdeiwFeiej Does it help if you set the BrowserWindow background color to the same as your app has? https://github.com/electron/electron/blob/master/docs/api/browser-window.md#setting-backgroundcolor

**Comment by FjicdeiwFeiej** [comment]
Yeah! That did the trick, actually! Feels much nicer now. Thanks. At least one problem solved today for me!

**Comment by robinwassen** [comment]
@FjicdeiwFeiej No problem!

I can reproduce the same issue in both latest Chrome and Slack, I would guess that it is implemented that way to not use unnecessary resources to just redraw the view during the resizing.

**Comment by MarshallOfSound** [comment]
This is just "How Chromium Works"(tm)

As @robinwassen mentioned you can set the background color of your window to make it slightly more athletically pleasing 👍

**Comment by dbradleyfl** [comment]
For anyone else that comes across this: the solve for me was making the electron window transparent (and high level parent elements like <html> and <body>). Hides the color flash for a less jarring resize (but does give the appearance of a lagging resize. I prefer that to the color flash).

**Comment by camdagr8** [comment]
To expand on @dbradleyfl 's answer, you can set the backgroundColor in the window config and then apply css rules: 

```css
html, body {
  background-color: transparent;
}
```

**Comment by bkeating** [comment]
`backgroundColor` in BrowserWindow options did the trick for me (my app is a solid color. I could see where this might not help 100%, but still worth setting. Docs even encourage it: https://www.electronjs.org/docs/api/browser-window#setting-backgroundcolor

```sh
    mainWindow = new BrowserWindow({
        backgroundColor: '#191919',
        ...
    })
```
