### ISSUE TITLE
Please improve the tutorial " Using the Widevine CDM Plugin"

### ISSUE THREAD

**Issue by chrisvelevitch** [electron/electron#10806]
For the benefit of newbies to understand what this tutorial is about, please provide, at the top of the tutorial, a summary of the tutorial is about, what `CDM` stands for and what the `Widevine CDM plugin` is and does.

**Comment by MarshallOfSound** [comment]
@chrisvelevitch We can't document everything, in the case of this tutorial it is intended to be read / used by people who already know what Widevine is and know that they want to use it.

If you want to learn more about widevine their page and the wikipedia page for it are a google search away 👍 

http://www.widevine.com/

**Comment by alexanderturinske** [comment]
More information can be found at https://wiki.mozilla.org/QA/Widevine_CDM
```
Widevine Content Decryption Modules (CDMs) are how streaming services protect content using HTML5 video to web browsers without relying on an NPAPI plugin like Flash or Silverlight.
Widevine support is an alternative solution for streaming services that currently rely on Silverlight for playback of DRM-protected video content. 
It will allow websites to show DRM-protected video content in Firefox without the use of NPAPI plugins. 
The Widevine CDM runs in an open-source CDM sandbox in Firefox providing better user security than NPAPI plugins.
```
