### ISSUE TITLE
Add event when mouse hovers a link

### ISSUE THREAD

**Issue by mark-hahn** [electron/electron#1080]
This may be asking way too much, but could webview give an event with the URL when the mouse hovers over a link?  This way the URL could be shown as in a browser at the bottom. It would also be nice if the `start-loading` event gave the URL. Then the URL bar could show the URL while the page was loading.

I would understand if asking for everything a browser can do is unreasonable, but several of us are making browsers out of this.  (grin)

**Comment by zcbenz** [comment]
> but could webview give an event with the URL when the mouse hovers over a link?

You can make use of the `preload` attribute to load a script in webview to capture the hovering events on links and then use `ipc.sendToHost` API to tell the host page.

There is actually a native Chromium event for this, but not exposed in atom-shell yet.

> It would also be nice if the start-loading event gave the URL. Then the URL bar could show the URL while the page was loading.

The `start-loading` event can happen for events other than loading a new page, like an image in page starts to load lazily.

To make a browser with webview we still needs to expose quite a lot of events in atom-shell and I need to write a guide on which event corresponds to which action in Chrome browser.

**Comment by mark-hahn** [comment]
Thanks.  The current webview API already enables a nice browser.  I don't
see any rush to future improvements.  I might still ask for them though.
 (grin)

BTW, a lot of people, including myself originally, thought a browser in
Atom was silly since you can always click into the real browser.  However,
I have a set of features coming out soon that will show some advantages to
a built-in browser.

**Comment by steelbrain** [comment]
I think this is fixed in master, a lot of navigation events have been added since this bug was opened.
