### ISSUE TITLE
WebBluetooth: Event 'select-bluetooth-device' returns duplicates and strange addresses

### ISSUE THREAD

**Issue by daumling** [electron/electron#10800]
* Electron version: 1.7.9
* Operating system: 10.12.6
* Computer: Macbook Air

I am currently working on the implementation of the Web Bluetooth selection dialog. The above event returns a huge number of duplicates. I have seen everything between 17 and 107 entries; they seem to grow when I reload the JS code and re-open the dialog.

When I remove all address duplicates, I end up with a few MAC addresses that seem to be auto-generated, because there is no vendor ID available for these addresses. This is the list of devices reported by my dialog:

"CA:14:FF:2A:37:F4" InO-Bot
"74:F9:BB:C1:60:BE" SBrick
"1F:46:52:72:D6:07" Betty
"48:F6:9B:C4:33:11" InO-Bot
"34:81:F4:15:07:D4" InO-Bot
"8C:DE:52:9A:DF:FC" Betty

Both Betty and InO-Bot have invalid (?) MAC addresses, not assigned to any vendor ID. The correct addresses are 34:81... and 8C:DE...

SBrick is a BLE-only device that has never been paired via the System Preferences. Betty and InO-Bot have been paired. After I removed the devices from the System Preferences Bluetooth dialog, I got a third entry for InO-Bot; before, I got two for both.

Both Betty and InO-Bot support BLE and the old SPP protocol. I suspect that Mac OS creates serial ports and therefore generates the additional MAC addresses.

I've attached an XML dump of my com.apple.Bluetooth system preferences.

[com.apple.Bluetooth.txt](https://github.com/electron/electron/files/1385338/com.apple.Bluetooth.txt)

### Expected behavior

List three BT devices

### Actual behavior

List of devices with several duplicates and apparently generated MAC addresses

**Comment by aramperez** [comment]
@daumling Do you have some sample code? I'm not seeing the event getting issued (but I'm a novice Javascript programmer). I've filed issue [#11865](https://github.com/electron/electron/issues/11865) which is similar to issue #10764 (which your open and closed).

Concerning all the BLE devices, if you have an iPhone, get the app [LightBlue](https://itunes.apple.com/us/app/lightblue-explorer/id557428110) or similar app. You might be surprised at the number of BLE devices that are around you with no vendor IDs.

/Aram

**Comment by daumling** [comment]
@aramperez : I've created an NPM module that you can integrate. Note that I did not test the module; I just pulled it from another project, and it does not work on Windows because Web Bluetooth support is missing. Here is the link: [](https://www.npmjs.com/package/electron-webbt-dialog)

Hope it helps. Please met me know.

**Comment by aramperez** [comment]
@daumling Thanks, I'll give it a try. From scanning your code, I'm not sure is how do I start the scanning. Right now, based on the user clicking a button, I call the "navigator.bluetooth.requestDevice" Promise. I'll give it a try and see what happens.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by emilwikstrom** [comment]
Hi!

I am building a cross platform application using Electron and Web Bluetooth. I also receive duplicate entries in the 'select-bluetooth-device' event.

The event is basically behaving like a scan and it is triggered repeatedly with a full list of currently nearby devices matching the provided filter. With this API it does not make sense to include device duplicates in the event .

The issue manifests itself as if each new scan result is added to the previous list. This means that nearby devices are duplicated as many times as the scan result is triggered.

Environment:
MacOS v10.13.6
NodeJS v10.16.3
Electron v2.0.4
