### ISSUE TITLE
Please improve the "Online Offline Events" tutorial

### ISSUE THREAD

**Issue by chrisvelevitch** [electron/electron#10805]
Please include, at the top of the article, what is meant by `offline` and `online` to make easy for newbies to understand what this tutorial is about. The meaning of the two terms is inferable from the note at the bottom, but being an advanced topic, it would be best to be clear upfront.

Also, it would additionally beneficial to include links to the documentation on the `standard HTML5 APIs` that provide these events.

**Comment by zeke** [comment]
Thanks for your input, @chrisvelevitch. Are you able to open a pull request making the changes you're suggesting here?

**Comment by chrisvelevitch** [comment]
@zeke being a newbie, I'm hoping someone else can provide a better explanation of the terms and who knows the link(s) to the `standard HTM5 APIs`.

**Comment by Vehemos** [comment]
made PR #10834  for this.

**Comment by jkleinsc** [comment]
Closing this as #10834 made the requested updates.
