### ISSUE TITLE
Possible to get "splash screen" while program is loading?

### ISSUE THREAD

**Issue by FjicdeiwFeiej** [electron/electron#10809]
When I double-click the final.exe the first time after the computer has started, nothing happens until several seconds later, when the GUI immediately pops up. Is there any way that I can in some way indicate that the program is in fact loading as quickly as the system can load it? I think users get very confused and I wish Electron would have some sort of minimal (customizeable) text or indicator box/progress bar that shows up instantly when launching the EXE.

**Comment by MarshallOfSound** [comment]
> When I double-click the final.exe

What did you use to generate this exe?

> nothing happens until several seconds later

This sounds like your app is doing stuff for a few seconds before it creates the window, if you do a console log as the first thing in your entry file you should see the log happen basically immediately.  If you app has a length start up time (for whatever reason) you should look at making a splash screen yourself as a separate browser window.  It's not something Electron will provide, we give you the tools to make the UI, the actual UI you can build 👍

**Comment by FjicdeiwFeiej** [comment]
"What did you use to generate this exe?"
I don't understand what you mean. I'm talking about Electron.exe renamed and with changed icon.

"This sounds like your app is doing stuff for a few seconds before it creates the window"
No, this is the time it takes for Electron to load. Again, it is "only" slow the first time each boot. Once it's been cached, it loads very quickly the next time until you shut down the computer (or some other unknown event takes place).

**Comment by FjicdeiwFeiej** [comment]
But why do I have to explain this to you? Surely you are very familiar with this? The whole deal is that there is tons of overhead with Electron or any "webview" program.

**Comment by MarshallOfSound** [comment]
> But why do I have to explain this to you? Surely you are very familiar with this? The whole deal is that there is tons of overhead with Electron or any "webview" program.

This isn't entirely accurate, I just tested from a clean boot in a VM (so shoddy performance), VS Code opens basically instantly (less than a second).  Because you describe it as only the first boot, I'd probably put this down to disk speed and your application doing some synchronous things blocking the ready event.  If you can provide a repro for your application taking several seconds to fire the ready event then we can try point at things that could be causing it.

**Comment by FjicdeiwFeiej** [comment]
My main.js is literally the example from the documentation. It's not doing some "blocking event". It takes a long time to start up because that's the case with every single NW.js and Electron application because they have a huge overhead to load in.

**Comment by FjicdeiwFeiej** [comment]
Does anyone even read this?
