### ISSUE TITLE
Passing --inspect flag to child process as well as main process

### ISSUE THREAD

**Issue by BrighTide** [electron/electron#10818]
* Electron version: tested both 1.7.8 and 1.8.1
* Operating system: Windows 8.1

### Background
With the current state of chrome devtools, remote debugging using '--remote-debugging-port' vs '-inspect' operates differently

With --inspect you can add multiple addresses for it to 'watch' and have it quite seamlessly switch between debugging multiple processes.

### Problem
I'm looking to take advantage this to debug multiple node processes locally, but to do that I need to pass the inspect flag to the render and webview electron processes as well as the main. I know electron already handles passing it to the main process, but I'm having trouble getting it to pass to any child processes.

### Expected behavior

running "app.commandLine.appendSwitch('inspect', '10001')" in main.js should pass --inspect=10001 to the child electron process, or at least emulate the behaviour

### Actual behaviour

The flag is not passed, nor is the behaviour emulated

### How to reproduce
I've included a link to a repo to demonstrate what I'm talking about. You'll see that I'm attempting to include the switch in main.js, but when I print argv in the rendering thread there's no inspect flag. Also if you go to 'chrome://inspect/#devices' you can't see any inspectable node processes

git clone https://github.com/BrighTide/electron-quick-start.git
npm install
npm start

Let me know if there's any significant JS work that would be required and I'd be happy to make a PR else thanks heaps for taking a look :)

**Comment by BrighTide** [comment]
Not sure if appropriate to leave here, or in a separate issue, but there's also a bug in the --inspect-brk functionality. The process does pause on start but un-pauses as soon as a debugger connects

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
