### ISSUE TITLE
electron . exited with code 3221225477

### ISSUE THREAD

**Issue by mm739521** [electron/electron#10814]
**Windows 7/10**

I've seen other posts about this error but none of them seemed to help me.

I get this error anytime I'm running my electron application then go into my network settings in the control panel and disabled the wireless network connection.  The process just stoprs running and I only receive it when I disable my wireless network connection but not when I disconnect.

Any ideas?

**Comment by robinwassen** [comment]
Sounds like you are bumping into: #6437

There are some machine configuration options to prevent this from happening (such as adding a  loopback adapter), can't help you more than that I am afraid.

**Comment by sofianguy** [comment]
I agree with @robinwassen that this is a similar issue to [#6437](https://github.com/electron/electron/issues/6437). Please subscribe to that for updates.
