### ISSUE TITLE
Alt + menu hotkey in open menus does not trigger hotkey action on Windows

### ISSUE THREAD

**Issue by KeithTurkowski** [electron/electron#10817]
I originally opened this issue for Atom, and was referred here.

Here's a link to the Atom bug thread.
https://github.com/atom/atom/issues/10732

When using a key sequence such as: (alt+f) (alt+s) to save a file, the menu open but the [S]ave action does not trigger due to the (alt) key being held down.

In every other Windows application I tested, this works. This is done to compensate when typing alt+f s quickly, the release of the alt key does not register before the s key is pressed, or the user does not release it in time.

It is expected that opening the menu, then pressing the hotkey OR alt+hotkey should trigger the action, as this behavior is present in virtually every other Windows application.

**Comment by sofianguy** [comment]
Is this bug happening on versions later than 2.0.x?

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by KeithTurkowski** [comment]
It's happening in Atom version 1.34.0, which is running on Electron 2.0.x, so yes.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by KeithTurkowski** [comment]
@sofianguy I am not sure if I can properly test this. The issue is still occurring in the latest version of Atom 1.40.0 (Windows), which is running Electron 3.1.10. I do not use Electron directly, and it is not clear to me how I would be able to test this issue in a version v4.2.x or later, at least until Atom is updated to use it.

**Comment by sofianguy** [comment]
I am going to close this issue as we are no longer pushing bug fixes to versions earlier than 4.2.x. We'd be happy to reopen if this issue is still present in later versions of Electron
