### ISSUE TITLE
/usr/bin/ld: this linker was not configured to use sysroots

### ISSUE THREAD

**Issue by yunzhenhuan** [electron/electron#10819]
* Electron version:master
* Operating system:CentOS7.3_64Bit
I compiled it according to the official document，and the URL is:
```url
https://github.com/electron/electron/blob/master/docs-translations/zh-CN/development/build-instructions-linux.md
```
### How to reproduce
**I did the following**
```shell
sudo apt-get install build-essential clang libdbus-1-dev libgtk2.0-dev \
                       libnotify-dev libgnome-keyring-dev libgconf2-dev \
                       libasound2-dev libcap-dev libcups2-dev libxtst-dev \
                       libxss1 libnss3-dev gcc-multilib g++-multilib
```
```shell
git clone https://github.com/electron/electron.git
```
```shell
cd electron
./script/bootstrap.py -v
```
```shell
./script/build.py
```
**But running here, the system reported the following mistakes**
![image](https://user-images.githubusercontent.com/15715661/31653073-d651e70a-b353-11e7-979e-7492e036cab2.png)
```shell
/usr/bin/ld: this linker was not configured to use sysroots
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[2/373] CXX obj/vendor/node/src/node.string_bytes.o
ninja: build stopped: subcommand failed.
```
What should I do?

**Comment by sofianguy** [comment]
Hi @yunzhenhuan can you please provide us with the following for us to better help you:
- Electron version
- operating system
- steps to reproduce issue

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
