### ISSUE TITLE
Provide open-with option to user

### ISSUE THREAD

**Issue by rajeevprasanna** [electron/electron#10811]
I am writing a file system application in the electron. When the user right clicks on file, I want to show a list of supported applications which can open the file as happened in OS platform.

Is this technically possible with electron framework ?

**Comment by MarshallOfSound** [comment]
@rajeevprasanna Electron does not have an API to fetch this currently but you can figure it out for each platform individually.  On Windows it's stored in some registry keys in `HKCR`, on macOS their are native launch service API's you can call and on linux you have to inspect desktop files.
