### ISSUE TITLE
Parser-blocking error

### ISSUE THREAD

**Issue by Devhercule** [electron/electron#10821]
Hi,

Have you an idea about this error message?

`A Parser-blocking, cross site (i.e. different eTLD+1) script, http://www.google-analytics.com/ga.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message.See https://www.chromestatus.com/feature/5718547946799104 for more details.`

Thank you

**Comment by MarshallOfSound** [comment]
Seems relatively self-explanatory, see https://www.chromestatus.com/feature/5718547946799104 for a more detailed reasoning and documentation 😄

**Comment by MarshallOfSound** [comment]
For some more info here, it's not technically an error message, it's a warning indicating something one of your scripts is doing may potentially not work in some scenarios

**Comment by gucong3000** [comment]
Before I fix is issues in my web, how can I block this message? It caused my log to be too large.
