### ISSUE TITLE
screenshare via (getUserMedia) shows black when selecting any gpu accelerated window (for e.g. another electron window) to share

### ISSUE THREAD

**Issue by imedwei** [electron/electron#10828]
* Electron version: 1.3.13, 1.6.15, 1.7.9, 1.8.2-beta.1
* Operating system: Windows 10

### Expected behavior

1. Launch electron based app which includes screen sharing capability via getUserMedia
2. Pick an electron based window (in this example Slack)  to capture contents.

The contents of the window should be captured.

### Actual behavior
3. Notice that the captured content stream is black.

If you try the same steps with chrome M54, M58, M60, M62 the behavior is less broken. When the electron based window is selected for screenshare, the contents are present when the window is in the foreground, and black if the window is in the background.

### How to reproduce

1. Install & run Jitsi-meet-electron https://github.com/jitsi/jitsi-meet-electron
2. Join a Jitsi-meet call
3. Share screen from the toolbar.
4. Select an application window of another electron app (in this case I continue to select the Slack electron app.
5. Notice that the shared window contents are always black regardless if the window is in the foreground or background.

### Possibly related to 
Possible issues in desktopCapturer on Windows 10 #6599
and possibly https://bugs.chromium.org/p/chromium/issues/detail?id=642386

**Comment by arnaudbud** [comment]
duplicates https://github.com/electron/electron/issues/6599

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
