### ISSUE TITLE
First run doesn't work

### ISSUE THREAD

**Issue by sefel** [electron/electron#10826]
I made application using node, webpack, Angular 4 and electron. I work. But not on first run. I mean, when I run my computer from start, and didn't run any node application. When I run my electron app it looks like it stuck. Window open but nothing happen. When webpack finish it doesn't reload. On another run everything is ok. Electron wait for webpack and reload window. Here is screenshot. I think is some problem with electron not node or webpack. It work the same on production mode when I use desctop shorcut.
I use windows 10. 
![electron](https://user-images.githubusercontent.com/5675915/31680710-69b0493a-b375-11e7-8643-9d6693fe35f3.jpg)

**Comment by MarshallOfSound** [comment]
With no errors or reproduction code we can't help with this 👍 If you provide both of these we can look at helping you.  That said this would seem to be an issue with some kind of webpack configuration, we'll see when the reproduction example comes through 😄

**Comment by sefel** [comment]
I investigate this problem and this what I discover.

My code in createWindow() in main.js: 
 let index = 1;
`mainWindow.webContents.on('did-fail-load', function(event) {
            console.log('Load fail...', index++);
            mainWindow.webContents.reload();

            // mainWindow.webContents.openDevTools();
        })
        mainWindow.webContents.once('did-stop-loading', function(event) {
            event.preventDefault();
            if (!mainWindow) {
                throw new Error('"mainWindow" is not defined');
            }
            mainWindow.show();
            mainWindow.focus();
            // mainWindow.webContents.reload();

            if (process.env.NODE_ENV === 'dev') {
                mainWindow.toggleDevTools();
            }
            // ipc.send('pong', 'dupa');
            console.log('success');
            // return true;

        });`

And this is console.logs from first run after restart  OS.

Load fail... 1
Load fail... 2
Load fail... 3
Load fail... 4
Load fail... 5
Load fail... 6
Load fail... 7
Load fail... 8
Load fail... 9
Load fail... 10
Load fail... 11
Load fail... 12
Load fail... 13
success

And it also stuck after fail 13. and wait till sucess... 

And this is after next run:

success

No fail... so the problem is I think that on first run electron don't wait for server to load page but it try to load it immediately.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
