### ISSUE TITLE
Strange looking Transparent header on OSX

### ISSUE THREAD

**Issue by sandor** [electron/electron#10823]
After updating to OSX 10.13 the transparent header of my window is looking very strange:
![title](https://user-images.githubusercontent.com/476224/31676246-4a715004-b367-11e7-9299-6c069e0819ed.jpeg)

This is how it is looking (no corner rounding) on a darker background.

Now o a white/light background you can see the corner.

![title2](https://user-images.githubusercontent.com/476224/31676617-7ac06a14-b368-11e7-92fd-1c929701c998.jpg)

On erlier OSX all is looking fine...

OSX: 10.13
Electron: 1.8.1

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
