### ISSUE TITLE
Compiling electron error reporting

### ISSUE THREAD

**Issue by yunzhenhuan** [electron/electron#10835]
Electron:Newest
Operating system: Ubuntu Server 14.04.1 LTS 64Bit

**I did the following**
```shell
sudo apt-get install build-essential clang libdbus-1-dev libgtk2.0-dev \
                       libnotify-dev libgnome-keyring-dev libgconf2-dev \
                       libasound2-dev libcap-dev libcups2-dev libxtst-dev \
                       libxss1 libnss3-dev gcc-multilib g++-multilib
```
```shell
git clone https://github.com/electron/electron.git
```
```shell
cd electron
./script/bootstrap.py -v
```
```shell
./script/build.py
```
**But running here, the system reported the following mistakes**
![debian_error](https://user-images.githubusercontent.com/15715661/31715761-a3517232-b437-11e7-82bd-68606adadb95.png)
What should I do?

**Comment by miaulightouch** [comment]
when you try to build "Release build", please ensure you have **12GB+** RAM in your environment.

you should try `./script/build.py -c D` to build "Debug build" first, it didn't require that much ram than Release builds.

and this not a good issue format, please follow correct [template](https://github.com/electron/electron/blob/master/.github/ISSUE_TEMPLATE.md) next time.

**Comment by yunzhenhuan** [comment]
Thanks very much!
