### ISSUE TITLE
Where is localStorage actually stored in Electron?

### ISSUE THREAD

**Issue by FjicdeiwFeiej** [electron/electron#10831]
I noticed that the values I store and retrieve are not reset each time I build my Electron app. This must mean that it doesn't save this in a file in its dir, but maybe %APPDATA% or the registry or something?! I searched the whole manual for Electron with not a word about this. Where is it stored, and why "globally"?

**Comment by MarshallOfSound** [comment]
`localStorage` is persisted inside your `appData` directory (this directory depends on your platform, on Windows it is `%APPDATA%/YourAppName`.  It's persisted because that's how `localStorage` works (it's persistent key-value string based storage).

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
