### ISSUE TITLE
win.blur() doesn't work in macOS

### ISSUE THREAD

**Issue by dashersw** [electron/electron#10830]
* Electron version: 1.7.9
* Operating system: macOS 10.13.1 Beta (17B35a)

### Expected behavior

Upon using `win.blur()`, the electron app should lose focus and a background app should gain focus.

### Actual behavior

Nothing happens.

### How to reproduce

The best way to try it out is to clone [electron/electron-quick-start](https://github.com/electron/electron-quick-start) repository as in;
```
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start
npm install
npm start
```
and add `mainWindow.blur()` or even optionally alongside a `mainWindow.hide()`.

**Comment by jlsilva1994** [comment]
same happening here, please check this issue

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by chuson1996** [comment]
getting the same issue in electron@11.1.0
