### ISSUE TITLE
React devtools extension stops working after upgrading to 1.7.6

### ISSUE THREAD

**Issue by ghost** [electron/electron#10844]
* Electron version:1.7.6
* Operating system:Windows

### Issue

React devtools installed using electron-devtools-installer doesn't seem to be working starting version 1.7.6. The extension gets added successfully, but I don't see the react tab in the dev tools. Rolling back to 1.7.5 fixes the issue.

My guess is that #9918 might be the root cause.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
