### ISSUE TITLE
Selecting a checkbox menu item doesn't seem to toggle its checkmark

### ISSUE THREAD

**Issue by jayfoad** [electron/electron#10845]
* Electron version: 1.7.9
* Operating system: Linux (Ubuntu 17.04)

### Expected behavior

The [docs for MenuItem](https://github.com/electron/electron/blob/master/docs/api/menu-item.md) say:

- A `checkbox` menu item will toggle the `checked` property on and off when selected.
- [...]
- You can add a `click` function for additional behavior.

See repro for a sample app that creates a menu with a checkbox menu item. When I select it, I expect a checkmark to appear / disappear alternately.

I've seen #5055 but that seemed to be specifically about `Tray.setContextMenu`.

### Actual behavior

A checkmark never appears.

### How to reproduce

```
$ git clone https://github.com/jayfoad/electron-quick-start.git
$ cd electron-quick-start
$ git checkout 00f23c26eedac9d23bff0ee8935b5222b5d652cc
$ npm install
$ npm start
```

**Comment by codebytere** [comment]
You're expecting this behavior, yes? 
<img width="158" alt="screen shot 2017-10-20 at 7 19 53 pm" src="https://user-images.githubusercontent.com/2036040/31845117-ae1dc748-b5cb-11e7-9873-ee09f5fd009f.png">

Checked that it works on mac, about to investigate on linux

**Comment by MarshallOfSound** [comment]
If we're putting platforms on the record, this works as expected on Windows 👍

**Comment by codebytere** [comment]
ok, so it looks like this on linux: 

<img width="167" alt="screen shot 2017-10-21 at 12 23 11 am" src="https://user-images.githubusercontent.com/2036040/31848009-198096d0-b5f6-11e7-8785-87fea1dad3e1.png">

no matter how many times i click it, although checked behavior is occurring as normal (verified that checked value changes from false to true on click)

**Comment by jayfoad** [comment]
This was a problem for me on Ubuntu 17.04 with the Unity desktop. Now I've upgraded to 17.10 with the GNOME desktop, the problem has gone away: checkmarks are appearing and disappearing correctly.

**Comment by codebytere** [comment]
Rad, glad to hear it! i'm going to go ahead and close this issue.
