### ISSUE TITLE
Ability to run a method when a user clicks a top level item in the Mac application menu bar

### ISSUE THREAD

**Issue by kirkouimet** [electron/electron#10842]
* Electron version: 1.8.1
* Operating system: macOS High Sierra

### Expected behavior

I should be able to listen to an event or specify a function when a user opens a top level menu on the menu bar. For example, if the user opens the "File" menu I should be able to run a method which will update the contents of the submenu under "File".

### Actual behavior

There is no current way to do this. Adding a `click` property to a top level menu on the application never triggers.

**Comment by MarshallOfSound** [comment]
See https://github.com/electron/electron/issues/528 for discussions on modifying menus at-show-time
