### ISSUE TITLE
How to run a script during mac os install application

### ISSUE THREAD

**Issue by fabriciolelis** [electron/electron#10840]
* Electron version: 
   1.7.6
* Operating system: 
   MacOS

How can I execute a script in MacOs install like in deb linux afterInstall option?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by MarshallOfSound** [comment]
macOS applications don't have a concept of "install" and "uninstall".  You should instead maintain a flag inside your application indicating whether it has been run on this machine before, if that flag isn't present you can assume it's the first run and do any "install" things then
