### ISSUE TITLE
How to make window Settings match the actual size

### ISSUE THREAD

**Issue by y489436672** [electron/electron#10847]
* Electron version: 1.7.9
* Operating system:
win7 X64
The width of the new window is 768, the height is 480, the actual open window width is 960, and the height is 600.
When I created a new window, the actual size of the window was always about 1.25 times the size of the window, and I saw that the devicePixelRatio of the window was 1.25, which was generated after the release of the electron 1.4.16.How do I do that?

**Comment by y489436672** [comment]
我觉得你应该添加bug分类.

**Comment by y489436672** [comment]
I think you should add a bug category.

**Comment by MarshallOfSound** [comment]
Duplicate https://github.com/electron/electron/issues/9560
