### ISSUE TITLE
problem with flash web site

### ISSUE THREAD

**Issue by Devhercule** [electron/electron#10846]
Hi,

I wonder if flash is supported in Electron.

I want to display this web site: http://www.vues-migratoires.com/site.html

but it does not work with Electon, I have this error message : `Impossible de charger le plugin.`

How can I fix this issue?

Thank you

**Comment by MarshallOfSound** [comment]
See our tutorial on using pepper flash: https://github.com/electron/electron/blob/master/docs/tutorial/using-pepper-flash-plugin.md

**Comment by Devhercule** [comment]
Thanks for your reply

I will test it and tell you

**Comment by Devhercule** [comment]
Can you tell me how can I get pepflashplayer.dll for windows, il the tuto there is description only for linux and darwin

Thanks

**Comment by Devhercule** [comment]
It does not work for me.

I added this in my code :

```
let pluginName;
switch (process.platform) {
  case 'win32':
    pluginName = 'pepflashplayer.dll'
    break
  case 'darwin':
    pluginName = 'PepperFlashPlayer.plugin'
    break
  case 'linux':
    pluginName = 'libpepflashplayer.so'
    break
}

app.commandLine.appendSwitch('ppapi-flash-path', path.join(__dirname, pluginName))

app.commandLine.appendSwitch('ppapi-flash-version', '26.0.0.131')
```

I downloaded pepflashplayer.dll from https://fr.dll-files.com/pepflashplayer.dll.html

But still the same error: `Impossible de charger le plugin.`

Should I do something else?

Thanks

**Comment by Devhercule** [comment]
It is ok for me

I added `webview.setAttribute("plugins", "on");` and it works now ;)
