### ISSUE TITLE
Send postData with the "new-window" event for sandbox

### ISSUE THREAD

**Issue by blingenau** [electron/electron#10852]
We're writing a browser and we've been forced to ignore disposition because we're trying to create a new tab as a result of a form submission but don't have the postData in the `new-window` event to correctly handle the form post.

**Comment by sofianguy** [comment]
Hi @blingenau, can you please provide us with the following for us to better help you:
- Electron version
- operating system
- steps to reproduce issue

**Comment by blingenau** [comment]
Electron Version: 1.7.9
Operating System: Windows 7, 10, and Mac OS

And there's not really an issue, it's more of an enhancement request. With the nature of how we're interpreting `new-window` requests and their dispositions of `foreground-tab`, we're preventing the default behavior, deleting the original webContents object, and creating a browser-like tab with a new webContents object. The problem is that the postData gets lost during this and the tab just tries to navigate to whatever API the form is targeting. Our current workaround is to capture the outgoing request and handle it ourselves, capturing this at the session level and circling back around. This has proven to be extremely unreliable and we could easily solve this if `postData`was passed to the `new-window` event, probably at [https://github.com/electron/electron/blob/306b62709017e12f6f4865e3d2b069cc7177db1f/lib/browser/guest-window-manager.js#L245](url)

**Comment by lopssh** [comment]
I encountered the same problem

**Comment by psicounterman** [comment]
Us too.  @blingenau, can you explain your workaround in a bit more detail or point me to code?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by LJLCarrien** [comment]
I meet the same problem too.
