### ISSUE TITLE
Failed to execute script 'script/bootstrap.py' to get necessary packages for build

### ISSUE THREAD

**Issue by BSoD-Ultimate** [electron/electron#10851]
I tried to build Electron binary file from source code on Windows. However the script 'script/bootstrap.py' did not run smoothly during the build progress.

* Electron version: 1.7.9
* Operating system: Windows 10 English Version Build 15063.674

I followed build instructions for Windows from the official website. The instruction said that building from source code requires Windows 7 or later and needs these tools: 
* Visual Studio 2015 Update 3
* Python 2.7
* Node.js
* Git

Then I installed the missing Node.js 8.7.0 and Python runtime on my computer and correctly configured corresponding environment variables. Both of them can be executed from command prompt window.
For Visual Studio, I have already installed Visual Studio 2017. In order to meet the requirement of Visual Studio 2015 toolset, **I uninstalled Visual C++ 2015 toolset provided in VS2017. Then I did a full installation of Visual Studio 2015 (including Visual C++ components).** The Visual Studio 2015 Commannd prompt can be successfully startup and I thought Visual Studio installation is OK.
However, after preparing the environment the bootstrap script did not run smoothly and raised an error.

The error occured after the script successfully downloaded libchromiumcontent libraries, including static and dynamic library. After the output window said it was executing script 'script\update.py', It raised the following error:
```
git submodule status vendor/libchromiumcontent
 62a432e7be8d0b1f6ad7181e3a1e9dd44ad9621c vendor/libchromiumcontent (v51.0.2704.61-410-g62a432e)
C:\Python27\python.exe G:\electron\script\update.py
Traceback (most recent call last):
  File "tools/list-browserify-deps.py", line 12, in <module>
    deps = subprocess.check_output([BROWSERIFY, '--list'] + sys.argv[1:])
  File "C:\Python27\lib\subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
gyp: Call to 'python tools/list-browserify-deps.py ./lib/sandboxed_renderer/init.js -r ./lib/sandboxed_renderer/api/exports/electron.js:electron -r ./lib/sandboxed_renderer/api/exports/fs.js:fs -r ./lib/sandboxed_renderer/api/exports/os.js:os -r ./lib/sandboxed_renderer/api/exports/path.js:path -r ./lib/sandboxed_renderer/api/exports/child_process.js:child_process' returned exit status 1 while in electron.gyp.
None
Traceback (most recent call last):
  File "./script/bootstrap.py", line 249, in <module>
    sys.exit(main())
  File "./script/bootstrap.py", line 64, in main
    run_update(defines, args.msvs)
  File "./script/bootstrap.py", line 226, in run_update
    execute_stdout(args)
  File "G:\electron\script\lib\util.py", line 184, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'G:\\electron\\script\\update.py']' returned non-zero exit status 1
```

Did I do anything wrong during preparing the environment? If so, where the wrong could happen? thx.

**Comment by robinwassen** [comment]
The error is that the build chain cannot find the following file: `electron/node_modules/.bin/browserify`

Check that the file exist and check that your installed npm is working as intended and is an up-to-date but not unstable version.

**Comment by BSoD-Ultimate** [comment]
I did not see any folder naming `.bin` in the given folder `electron/node_modules/`. Does it mean something wrong happened in the download progress?
The Node.js version I installed is 8.7.0, npm version is 5.4.2. Maybe the new version of Node.js caused the issue? The Node.js' official site said that the LTS version is 6.11.4.

**Comment by robinwassen** [comment]
I would recommend Node 6.x and npm 4.x, personally had issues with newer versions on both of them. So give that a try and see if it solves the problem.

**Comment by BSoD-Ultimate** [comment]
Okay I will try rollback version to Node 6.x and try again. thanks

**Comment by YurySolovyov** [comment]
FWIW 
```
npm i browserify
```
helped in my case
