### ISSUE TITLE
Wrong node modules version

### ISSUE THREAD

**Issue by gagarin55** [electron/electron#10858]
* Electron version: 1.7.9
* Operating system: Ubuntu 17

Electron 1.7.9 needs node module version **54**, but I couldn't find any nodejs distro with such version at https://nodejs.org/en/download/releases/.

Which Electron version is stable enough and could be used with same nodejs version ?

**Comment by MarshallOfSound** [comment]
@gagarin55 Electron uses different `NODE_MODULE_VERSION` values than nodejs itself (to avoid conflicts).  Use `electron-rebuild` to rebuild modules for Electron apps 👍

**Comment by gagarin55** [comment]
@MarshallOfSound but Jest tests uses local nodejs and it crashes ;(

**Comment by ArronYR** [comment]
hi, in my project, I need use `ed25519` library. If I run the program directly after `npm install`, an error will be reported:
```
project/node_modules/ed25519/build/Release/ed25519.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
```

I use `npm rebuild` able to compile normally, but when I use `./node_modules/.bin/electron-rebuild` compiled under the project directory, error message shows:
```fatal error: 'openssl / sha.h' file not found```

NodeJS Version: 9.2.0
Electron Version: 1.7.9
Operating system: macOS High Sierra 10.13
