### ISSUE TITLE
Auto-updater : How can I show download progress?

### ISSUE THREAD

**Issue by Dear-Min** [electron/electron#10859]
I am using auto updater module on windows.

Is there way to show download new version?

// This is mycode

updater.autoUpdater.checkForUpdates();
updater.autoUpdater.addListener("update-available", function (event) {
    LauncherDeploying();
});

updater.autoUpdater.addListener("update-not-available", function () {
});

// not working!

updater.autoUpdater.addListener('download-progress', (progressObj) => {
  console.log(progressObj);
});

updater.autoUpdater.addListener("update-downloaded", (event, releaseNotes, releaseName, releaseDate, updateURL) => {
    LauncherTimer();
    setTimeout(quitAndInstall,12000);
    return true;
})
updater.autoUpdater.addListener("error", (error) => {
    console.log(error);
});
updater.autoUpdater.addListener("checking-for-update", (event) => {
    console.log("checking-for-update");
});

**Comment by MarshallOfSound** [comment]
> How can I show download progress

Electrons auto updater does not emit progress events

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by Dear-Min** [comment]
Is there any reasons for not supporting emit progress events?

**Comment by MarshallOfSound** [comment]
@Dear-Min The underlying libraries (Squirrel.Mac and Squirrel.Windows) do not support it

**Comment by Dear-Min** [comment]
Then I have to find another way.. thank you for the reply.

**Comment by Jotune** [comment]
Seems like getting the progress is supported by Squirrel in some cases. On Windows at least.
See [IUpdateManager.cs](https://github.com/Squirrel/Squirrel.Windows/blob/b7b4a84d39ab44e91e70229b044b455c1a7f29de/src/Squirrel/IUpdateManager.cs)

**Comment by Oscabrera** [comment]
the solution is use electron-differential-updater

https://www.npmjs.com/package/electron-differential-updater

**Comment by Armaldio** [comment]
Hey, can you reconsider this ?
Or at least point me in the direction for a PR :+1:
