### ISSUE TITLE
Large file size of small electron app ? 

### ISSUE THREAD

**Issue by lakinmohapatra** [electron/electron#10861]
Hi we are developing one electron app with very small features .
But the output desktop app size is more like 2GB. 

Is there any work going for reducing its size ?

**Comment by MarshallOfSound** [comment]
> But the output desktop app size is more like 2GB.

Sounds like you've done something wrong here, how exactly are you building this app?

**Comment by Paxa** [comment]
It should not be that big, you can see how other apps doing it https://electron.atom.io/apps/

For example webtorrent is only 50mb

**Comment by felixrieseberg** [comment]
I'd recommend that you go with https://github.com/electron-userland/electron-forge to build your application. Chances are very high that you're including a whole bunch of stuff that you shouldn't – and using forge will handle packaging and everything else for you.

I'm closing this for now, but feel free to ask more!

**Comment by ednew2018** [comment]
Try to not include node_modules to your app.asar like the following. 
  `
"build": {
    ...
    "files": [
      "!node_modules"
    ],
   ...
}
`
