### ISSUE TITLE
Add types property to onHeaderReceived's filter parameter.

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#10867]
According to [this](https://developer.chrome.com/extensions/webRequest) page, the filter that gets passed to `onHeadersReceived` is a `RequestFilter`, which has a `types` property to allow filtering on resource types. Can this be added to electron's `onHeadersReceived` function, which according to [this](https://github.com/electron/electron/blob/master/docs/api/web-request.md), only supports the `urls` filter?

**Comment by MarshallOfSound** [comment]
@pushkin- I can't find any reference to `RequestFilter` or `types` on that docs page, can you link specifically to where you are seeing this documentation.

**Comment by pushkin-** [comment]
@MarshallOfSound On the first link, search for "types". Should be the first result.

**Comment by miniak** [comment]
@MarshallOfSound https://developer.chrome.com/docs/extensions/reference/webRequest/#type-OnHeadersReceivedOptions
https://developer.chrome.com/docs/extensions/reference/webRequest/#type-ResourceType
