### ISSUE TITLE
Zoom level/factor in child WebView

### ISSUE THREAD

**Issue by beljand** [electron/electron#10860]
* Electron version: 1.6.7
* Operating system: macOS / Win10

### Expected behavior

I'm loading YT embed url inside a webview.
child `<webview>` should inherit zoom level from parent

### Actual behaviour
Zoom level at 0 (parent on parent webFrame), all good, video expanded and correct zoom
![image](https://user-images.githubusercontent.com/697031/31810106-d38dc506-b57a-11e7-9d71-e241c68f2393.png)

Zoom level at -2 (parent on parent webFrame), child webView didn't inherit the zoom level
![image](https://user-images.githubusercontent.com/697031/31810158-ffcf5b0c-b57a-11e7-8504-295b770316cc.png)

I did try to implement a `preload` script, which listens to IPC events, and tried to set the zoom level manually (on `webFrame`), which worked for a moment (zoom level is set back to default right after it is set manually).

**Comment by beljand** [comment]
As a demo this project can be used. 
https://github.com/hokein/electron-sample-apps/tree/master/webview/browser

**Comment by codebytere** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on, `1.6.7`, has been superseded by newer releases, and we are no longer releasing fixes excepting security fixes to that line. Could you please try with the latest release in the `1-8-x` line?

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our [comment](https://github.com/electron/electron/issues/10860#issuecomment-381337907). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
