### ISSUE TITLE
subarray results are inconsistent with non-Electron apps

### ISSUE THREAD

**Issue by RedDuckss** [electron/electron#10865]
* Electron version: latest
* Operating system: Windows 10, latest update

### Expected behavior

That `subarray` functions the same as it does in non-Electron apps, specifically when used on buffers

### Actual behavior

It is not the same

### How to reproduce

Use `fs`, or one of the variants (I use `fs-extra`) to read a file to get its buffer. Attempt to use `subarray` on the buffer and log the result.

I found this when reading `tmd` files for a project I am working on. I am unsure if this affects other file types and normal arrays, as I specifically and exclusively work with `tmd` files in this project.

This code snippet works as intended when run via `node index.js`
```javascript
var fs = require('fs')

console.log(fs.readFileSync('title.tmd').subarray(0x1DE, 0x1E0))
```
It outputs `<Buffer 00 82>`, which is the correct buffer.

However when running the exact same code snippet in an Electron app, it outputs an Uinit8Array instead of the buffer. To get the buffer, you'd have to do:
```javascript
var fs = require('fs')

console.log(new Buffer.from(fs.readFileSync('title.tmd').subarray(0x1DE, 0x1E0)))
```
which turns the array back into the correct buffer.

**Comment by felixrieseberg** [comment]
This seems to be the correct behavior. Let me explain: You're running V8 from libchromiumcontent - JavaScript behaves more like JavaScript in a browser, less like JavaScript in Node. 

According to the spec and docs, `subarray` is supposed to return a typed array: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/subarray

To bridge the two, I'd recommend modules written for this precise problem, like this one: https://github.com/Ayms/abstract-tls

**Comment by RedDuckss** [comment]
I am aware that this is technically the correct behavior. That isn’t what I was reporting. I did not say it was wrong. I said it was inconsistent, which it is.

**Comment by MarshallOfSound** [comment]
@RedDuckss The behavior outside of Electron is inconsistent so we can only do one of them 😄 As @felixrieseberg said we use the v8 from libcc which means we'll tend towards browser behavior as opposed to the nodejs Buffer behavior.
