### ISSUE TITLE
Electron fails to reload the PDF document in sandboxed window

### ISSUE THREAD

**Issue by ahmedmohamedali** [electron/electron#10866]
* Electron version: v18.1
* Operating system: Windows 7

### Expected behavior
PDF document should reload correctly when sandbox is enabled on the BrowserWindow.

### Actual behavior
When sandbox is set to true in the BrowserWindow, PDF document loads correctly.
However if the user reload the document the PDF is not displayed and the following message appears in the plugin:

"Failed to load the PDF document is displayed" 

### How to reproduce

Below is a modified version of electron-quick-start that opens a PDF document in a sandboxed window then reload it.

> git clone https://github.com/ahmedmohamedali/electron-quick-start/tree/pdf_reload_bug
> npm install
> npm start

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
