### ISSUE TITLE
Implementing in-app purchase in an Electron app for the Mac App Store (Beer money + Stackoverflow bounty reward)

### ISSUE THREAD

**Issue by holgersindbaek** [electron/electron#10876]
I need to implement in-app purchases for my Electron app, but I have no idea where to start or end.

I've put up a post with details on Stackoverflow:
https://stackoverflow.com/questions/46753835/implementing-in-app-purchase-in-an-electron-app-for-the-mac-app-store

If you can help me figure this out, there's a 300 points Stackoverflow bounty, plus beer money ($50) as a thank you for helping.

It can't be true that this library has 51k stars, but no one has figured out how to do in-app purchases. Let's figure this out!

**Comment by MarshallOfSound** [comment]
Merging into #3745

**Comment by holgersindbaek** [comment]
@MarshallOfSound This issue is getting no attention. Can we keep it open for 24 hours, so we can finally figure this out?

**Comment by immanoj16** [comment]
Hey @holgersindbaek, Did you find any solution for this?? Please let me know.

**Comment by immanoj16** [comment]
Thank you

**Comment by immanoj16** [comment]
Do you know when it will be released to Stable version.

**Comment by holgersindbaek** [comment]
No

**Comment by holgersindbaek** [comment]
Haven’t got one sorry. 

-- 

All the best

*Holger Sindbaek* · UI/UX Designer & Web/iOS Programmer · * * HolgerSindbaek.com ( http://holgersindbaek.com/ )
