### ISSUE TITLE
Unable to build electron v0.37.8

### ISSUE THREAD

**Issue by JohnRanker** [electron/electron#10872]
debug symbols for electron v0.37.8 found in [releases](https://github.com/electron/electron/releases) are provided in .SYM format. Windbg only supports .PDB format. so I tried to build a debug version myself, but I ran into errors.

* Electron version: v0.37.8
* Operating system: Windows 7 SP1 64bit

### Expected behavior
electron to be built.

### Actual behavior
tools versions used:
    node 7.10.1
    python 2.7
    Visual Studio 2015 Update 3

first of all, I cloned the repo, then checked out tag v0.37.8; it gave me error 'Could not find local Visual studio installation' after running bootstrap.py script. Then I modified a internal script (MSVSVERSION.py) so the installed VS2015 is detected now. the last error says that 'environment variable "SYSTEMROOT" has to be set'.
going back to the command line, it says SYSTEMROOT is set to "C:\Windows".

Any thoughts ?!!
p.s: I find it whether that the installed version of visual studio couldn't be detected in the first place. I had to tweak the before mentioned script.

### How to reproduce
git checkout v0.37.8 and try to build following [Build Instructions (Windows)](https://electron.atom.io/docs/development/build-instructions-windows/)

**Comment by robinwassen** [comment]
0.37.8 is a two year old version - I can imagine that some dependency links and other things could have broken in that time period.

But to help you along the way:
- The documentation for 0.37.8 states that VS 2013 is required and 2015 will not work: https://github.com/electron/electron/blob/v0.37.8/docs/development/build-instructions-windows.md
- Node version used back then was 5.10.0: https://github.com/electron/electron/blob/v0.37.8/.node-version

Your best shot is probably to try and replicate the environment the best you can according to the docs, can't help you much more than that.

**Comment by JohnRanker** [comment]
so I was looking at the wrong documentation. Thanks a lot @robinwassen .
