### ISSUE TITLE
Electron 1.8.2 only runs 1 require script

### ISSUE THREAD

**Issue by dpgraham** [electron/electron#10877]
* Electron version: 1.8.2
* Operating system: MacOS

Git Repo to reproduce: 

https://github.com/dpgraham/electron-repro

### Description
The command `electron -r ./a -r ./b main` is only running `./a.js` on Electron 1.8.2-beta.1

When the same command is run on Electron 1.7, all three (`./a.js`, `./b.js`, `./main.js`) are run

(the three files all just run one console log with the name of the file)

### Expected behavior

This is what happens with Electron 1.7 and Electron 1.8.1

```
npm test
```

Output:
```
> electron -r ./a -r ./b main

A
B
Main
```

### Actual behavior
This is what happens with Electron 1.8.2
```
npm install electron@beta
npm test
```

Output:
```
> electron -r ./a -r ./b main

A
```

It never runs module b or main

### How to reproduce

```
git clone https://github.com/dpgraham/electron-repro
cd electron-repro
npm install
npm test # Success with Electron 1.7
npm install electron@beta
npm test # Fails with Electron 1.8.2
```

**Comment by felixrieseberg** [comment]
Really solid repro steps, thank you so much for that. Taking a look at this now.

**Comment by felixrieseberg** [comment]
A PR is up, we'll probably have this fixed with the next version. Again, thanks for the report!

**Comment by dpgraham** [comment]
No problem. Thanks for your work on this project! We've been using it for Appium Desktop with great success so far.
