### ISSUE TITLE
Disable setLoginItemSettings -> openAtLogin not working

### ISSUE THREAD

**Issue by adlk** [electron/electron#10880]
* Electron version: 1.7.9
* Operating system: macOS High Sierra (10.13)

### Expected behavior
`app.setLoginItemSettings({ openAtLogin: false });` should disable auto start.

### Actual behavior
`app.setLoginItemSettings({ openAtLogin: true });` adds app to auto start as expected. However setting it to `false` does not remove it. 
On macOS 10.12 it was working as expected.

### How to reproduce
In main or renderer run the following code
```js
console.log(app.getLoginItemSettings().openAtLogin); // either true or false if it has been set before
app.setLoginItemSettings({ openAtLogin: true }); 
console.log(app.getLoginItemSettings().openAtLogin); // true
app.setLoginItemSettings({ openAtLogin: false });
console.log(app.getLoginItemSettings().openAtLogin); // true
```

I've provided a test repo here:
```
$ git clone https://github.com/adlk/openAtLogin-issue -b master
$ npm install
$ npm start || electron .
```

**Comment by michael-gollmick** [comment]
just stumbled upon the same issue. Wnabling works, disabling not. Occurred on High Sierra and Electron 1.8.1

**Comment by djalmaaraujo** [comment]
Same here. 

![](http://g.recordit.co/4QT4TAx3g6.gif)

Using as a context menu:

```js
const getOpenAtLogin = () => app.getLoginItemSettings().openAtLogin
...
...
{
        label: 'Open at Login',
        type: 'checkbox',
        checked: getOpenAtLogin(),
        click() {
          const openAtLogin = getOpenAtLogin()

          app.setLoginItemSettings({
            openAtLogin: !openAtLogin
          })
        }
      }
```

**Comment by fantasticsid** [comment]
have the same issue with electron 1.6.11

**Comment by majoressense** [comment]
have the same issue with electron **1.7.9**
also High Sierra

**Comment by fantasticsid** [comment]
I did a bit research, and it's probably because https://developer.apple.com/documentation/coreservices/1443926-lssharedfilelistcreate is deprecated.

**Comment by seanlerner** [comment]
This is a workaround that works for me:

```js
require('child_process').exec(`osascript -e 'tell application "System Events" to delete login item "Electron"'`)
```
In the command above, replace `Electron` with your application name.

**Comment by djalmaaraujo** [comment]
@seanlerner Interesting approach. I will test here. thanks

**Comment by michael-gollmick** [comment]
Interesting approach indeed. Should'nt such an issue be fixed at the root instead of creating a workaround?

**Comment by lucasbento** [comment]
[node-auto-launch](https://github.com/Teamwork/node-auto-launch) is a good alternative for now if you don't need to submit your app to App Store.

**Comment by kennethlynne** [comment]
Just bumped into this and can confirm the bug

**Comment by eivindml** [comment]
Any progress on this? Came here from https://github.com/zeit/now-desktop/issues/422

Having this issue on a brand new clean install of newest MacOS High Sierra.

**Comment by usergit** [comment]
any updates on this issue

**Comment by dittos** [comment]
Code for removing the login item is in Chromium. https://cs.chromium.org/chromium/src/base/mac/mac_util.mm?l=282&rcl=8fc901b5c10c55bd9999960b68b55e850a19251c
Maybe this should be fixed in upstream?

**Comment by JoeDawson** [comment]
Any progress on this?

**Comment by ccoble** [comment]
Can this be fixed using SMLoginItemSetEnabled?  Possibly a similar approach that was used to fix #7312.

**Comment by mickours** [comment]
Note that this bug also impact Linux platform with Electron 1.8.2, not only MacOS.

**Comment by mickours** [comment]
I don't know if it is related but the file created by electron to autostart in ``~/.config/autostart/.electron-wrapped.desktop`` is a hidden file.

I tried to workaround this problem, and I had trouble to find this file, so maybe electron do not look for hidden file too ¯\_(ツ)_/¯

Still, as a workaround, removing the file stop the autostart.

**Comment by pronebird** [comment]
@mickours this feature is not available on Linux LOL

**Comment by gavJackson** [comment]
still not working :-(

...also I used the workaround @seanlerner  suggested `require('child_process').exec(...`
 and it worked once, but then I could no longer add to my login items, i assume a system restart would fix this - anyone else run into this issue?

**Comment by SilencerWeb** [comment]
@codebytere may I know is it at least on your roadmap?

**Comment by openbuilds-engineer** [comment]
I also ran into this bug. Awaiting fix (:

**Comment by absalomedia** [comment]
Can confirm this issue across both High Sierra & Mojave

**Comment by codebytere** [comment]
I can try to take a look at this soon

**Comment by codebytere** [comment]
Ok, so the issue with this seems to be that if you've run other similar code, you may have polluted your login items with other instances of Electron. I ran the repro provided, and the first time I tried, it failed as you all have reported above. However, on a hunch, i went to check my Login Items under `System Preferences > Users & Groups > [MY NAME] > Login Items`, and found a bunch of Electron instances, some with `hide` checked and some not. I deleted all of them, and then re-ran the repro: the issue disappeared and the function calls returned `false, true, false` as expected. 

Running MacOS 10.13

**Comment by sindresorhus** [comment]
@codebytere We are seeing this in production where the Electron name is not used. See: https://github.com/wulkano/kap/issues/428

**Comment by absalomedia** [comment]
@codebytere does that mean that Electron (and/or associated Electron build/package tools) needs some kind of installer garbage collection every time an Electron based app is updated?

**Comment by dittos** [comment]
FYI: I had success by calling the native APIs directly instead of Electron's API.

```objc
// Below is workaround for macOS High Sierra https://github.com/electron/electron/issues/10880
// Suspicious function in Chromium:
// https://cs.chromium.org/chromium/src/base/mac/mac_util.mm?l=282&rcl=8fc901b5c10c55bd9999960b68b55e850a19251c
// (maybe the cause is trying to remove login item from other LSSharedFileList)

static LSSharedFileListItemRef findItemWithURLInFileList(NSURL *wantedURL, LSSharedFileListRef fileList) {
    if (wantedURL == NULL || fileList == NULL)
        return NULL;
    
    CFArrayRef listSnapshot = LSSharedFileListCopySnapshot(fileList, NULL);
    for (id itemObject in (__bridge NSArray *)listSnapshot) {
        LSSharedFileListItemRef item = (__bridge LSSharedFileListItemRef) itemObject;
        UInt32 resolutionFlags = kLSSharedFileListNoUserInteraction | kLSSharedFileListDoNotMountVolumes;
        CFURLRef currentItemURL = LSSharedFileListItemCopyResolvedURL(item, resolutionFlags, NULL);
        if (currentItemURL && CFEqual(currentItemURL, (__bridge CFTypeRef)(wantedURL))) {
            CFRetain(item);
            CFRelease(currentItemURL);
            CFRelease(listSnapshot);
            return item;
        }
        if (currentItemURL)
            CFRelease(currentItemURL);
    }
    
    if (listSnapshot)
        CFRelease(listSnapshot);
    
    return NULL;
}

void NativeRemoveLoginItemWorkaround() {
    LSSharedFileListRef loginItems = LSSharedFileListCreate(NULL, kLSSharedFileListSessionLoginItems, NULL);
    LSSharedFileListItemRef item = findItemWithURLInFileList([NSURL fileURLWithPath:[[NSBundle mainBundle] bundlePath]], loginItems);
    if (item != NULL) {
        LSSharedFileListItemRemove(loginItems, item);
        CFRelease(item);
    }
    CFRelease(loginItems);
}
```

**Comment by codebytere** [comment]
To try and address this, i'm working on a PR to split out and clarify this here: https://github.com/electron/electron/pull/14960

**Comment by codebytere** [comment]
Ah good lord i know what's going on finally

```
Browser::LoginItemSettings Browser::GetLoginItemSettings(
    const LoginItemSettings& options) {
  LoginItemSettings settings;
#if defined(MAS_BUILD)
  settings.open_at_login = platform_util::GetLoginItemEnabled();
#else
  settings.open_at_login =
      base::mac::CheckLoginItemStatus(&settings.open_as_hidden);
  settings.restore_state = base::mac::WasLaunchedAsLoginItemRestoreState();
  settings.opened_at_login = base::mac::WasLaunchedAsLoginOrResumeItem();
  settings.opened_as_hidden = base::mac::WasLaunchedAsHiddenLoginItem();
#endif
  return settings;
}
```
The LoginItemSettings struct is defaulted to false for all properties, so we were just always returning `false` for `open_as_hidden` and then passing that value to `base::mac::CheckLoginItemStatus` so it would _sometimes_ return the correct value for `open_at_login` and sometimes not 🙃 

Working on a fix finally

**Comment by timirila1** [comment]
Can not disable "Launch at login"
It still in Login Items

* Electron version: 2.0.12
* MacOS Mojave 10.14

**Comment by Elias-Graf** [comment]
@timirila1 Is it not working at all or just in packaged stage? If just in packaged stage: are you using `electron-packager`? I had an issue for quite some time and I thought it was electron. While doing some testing I used `electron-builder` and now it seems to add and remove the item just as it should =)

**Comment by codebytere** [comment]
@timirila1 yes, our release line support is such that the earliest fix for this issue is in `3.0.0`. You should upgrade in order to see this fix.

**Comment by f3l1x** [comment]
Now: 4.0.0.canary.81 
Now Desktop: https://github.com/zeit/now-desktop/issues/422

![screen recording 2019-02-13 at 09 42 34](https://user-images.githubusercontent.com/538058/52699340-d1db4c80-2f75-11e9-9a7d-af4d80b324b7.gif)

**Comment by kolnogorov** [comment]
Was it fixed in 3.0.0 version? Because i have 3.0.0 (can't upgrade to the lasest due to ioHook), and i have the same bug. This:

`app.setLoginItemSettings({ openAtLogin: false });`

just doesn't set login items to false. Nothing happens.

**Comment by smth** [comment]
I'm also experiencing this with [Now](https://github.com/zeit/now-desktop) (version 4.0.19).

macOS 10.14.4

**Comment by bunchhaychea** [comment]
I'm also experiencing this issue with electron 3.02 & macOS 10.14.5

`app.setLoginItemSettings({ openAtLogin: false });` seems to not remove the only login item from my user.

**Comment by billmorgan123** [comment]
https://stackoverflow.com/a/67024918/14476201

**Comment by ysswebdev** [comment]
Can not disable "Launch at login"
It still in Login Items
Electron version: 20.0.2
System: Win 11
