### ISSUE TITLE
socket.io working with Web In express But failed while Building with electron .

### ISSUE THREAD

**Issue by Muthukumars1994** [electron/electron#10882]
--My server.js 
The below code works fine with Express.js Socket With avoiding pooling connection 
```js 
var app = express();
  var http = require('http').Server(app); 
var port = process.env.PORT || 2002;
var io = require('socket.io')(http, {
  serveClient: (port === 'production') ? false : true,
  path: '/socket.io'
});
 // instead of XHR requests first,
io.set('transports', ['websocket']);
app.use(express.static(__dirname));
var i = 1;
io.on('connect', function(socket){
     console.log("connected",i++);
        socket.on('game-manager', function(status){
            console.log("status",status)
           io.emit('game-manager', status);
      });
});
http.listen(port, function(){
  console.log('listening on *:' + port);
});  

```
---
client side script for Socket.io with cdn
https://cdn.socket.io/socket.io-1.2.0.js
```js
var socket = io(window.location.href, {transports: ['websocket'], upgrade: false});
//the above line is the issue while connecting with socket after building with electron
socket.on('game-manager', function(status){
console.log("status", status)
  if(status)  $('#game').show();
  else $('#game').hide()
});
function start(){
  console.log("start fired");
  socket.emit('game-manager', true)
};
function stop(){
  console.log("stop fired");
  socket.emit('game-manager', false)
};
```
------------
>package.json file
```
"main":"electron_config.js",
  "dependencies": {},
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node server.js",
    "serve": "nodemon server.js",
    "electron": "electron ."
  },
--------
```
version 
NOde -v 6.11.4
npm -v 3.10.10
electron -v 1.7.9

>current Difficulties: 
WebSocket connection to 'ws://file/socket.io/?EIO=3&transport=websocket' failed: Error in connection establishment: net::ERR_NAME_RESOLUTION_FAILED
```web socket code
function ws(uri, protocols, opts) {
//line no. 4578
    instance = new WebSocket(uri);
//here is the issue related to uri  
}
  return instance;
}
```
>expected Output 
My socket need to be connected through electron app while runing the command
`electron . `

**Comment by MarshallOfSound** [comment]
You're issue here is in electron your file is loaded from a file:// url so window.location.href will be different than the web.  You should check if you are on a file:// url and if so use "localhost" as the websocket host

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
