### ISSUE TITLE
Indicator icon missing in Ubuntu 17.10

### ISSUE THREAD

**Issue by akalin-keybase** [electron/electron#10887]
Electron version: 1.7.9
Operating system: Ubuntu 17.04
Expected behavior
Electron based apps that provide an indicator icon display the icon

Actual behavior
Indicator icon is not displayed

How to reproduce
With upgrade to Ubuntu 17.10, found that https://github.com/electron/electron/issues/9046 recurs.

I have this issue in the Electron based Keybase application. Haven't tried others, like Slack, Google Desktop Music Manager, Skype, etc.

The upgrade doesn't remove Unity, but it switches the default shell to gnome-session. My `XDG_CURRENT_DESKTOP` is `ubuntu:GNOME`, which I suspect is confusing Electron.

The work around of export XDG_CURRENT_DESKTOP=Unity still works.

**Comment by sebhahn** [comment]
I have a fresh installation of 17.10 and miss the icon. 

export XDG_CURRENT_DESKTOP=Unity does not work

**Comment by felixrieseberg** [comment]
Quick question: Did you try Electron 1.8 by any chance? Chromium 60 and 61 have added a few fixes for this specific behavior, so I'm hoping that we'd fix this bug _magically_ by just using the latest Chromium.

**Comment by akalin-keybase** [comment]
Not yet, just tried with 1.7.9 (updated above). Not sure when we (keybase) will upgrade to 1.8.0, but when we do I'll report back!

**Comment by M-W99** [comment]
Same issue here with Pulse SMS on 17.10.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
