### ISSUE TITLE
error in install electron

### ISSUE THREAD

**Issue by wuazhu** [electron/electron#10891]
- system: OSX 10.12.5
-----
error info: 
```
bogon:~ vicson$ sudo npm i electron -g
/usr/local/bin/electron -> /usr/local/lib/node_modules/electron/cli.js

> electron@1.7.9 postinstall /usr/local/lib/node_modules/electron
> node install.js

/usr/local/lib/node_modules/electron/install.js:48
  throw err
  ^

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/electron/electron-tmp-download-937-1508826099394'
    at Error (native)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.7.9 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.7.9 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vicson/.npm/_logs/2017-10-24T06_21_40_650Z-debug.log
```
how can i fix this problem?

**Comment by robinwassen** [comment]
@wuazhu Installing npm packages with sudo can cause issues like this - see this guide for how to fix permissions on the npm folder: https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by MarshallOfSound** [comment]
@robinwassen's information is correct 👍

**Comment by barbalex** [comment]
none of that worked for me :-(

**Comment by barbalex** [comment]
I managed to get my mac to run npm i without sudo. But installing electron would simply not work.

Then I used `yarn add electron` and that worked flawlessly.

So I guess I have to use a new package manager because of electron...

**Comment by barbalex** [comment]
actually no:


        alex-mac:kapla4 alex$ yarn add electron
        yarn add v1.2.1
        [1/4] 🔍  Resolving packages...
        warning electron > electron-download > nugget > progress-stream > through2 > xtend > object-keys@0.4.0: 
        [2/4] 🚚  Fetching packages...
        [3/4] 🔗  Linking dependencies...
        error An unexpected error occurred: "EACCES: permission denied, mkdir '/Users/alex/kapla4/node_modules/autoprefixer/node_modules/browserslist'".
        info If you think this is a bug, please open a bug report with the information provided in "/Users/alex/kapla4/yarn-error.log".
        info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by barbalex** [comment]
but worked with sudo

**Comment by francisrod01** [comment]
1. Go to electron path and run `yarn install` or just `yarn`, as below:

```bash
:~$ ls -la .config/yarn/global/node_modules/electron
total 396
drwxr-xr-x    3 paneladm paneladm   4096 Feb  1 15:41 .
drwxr-xr-x 1190 paneladm paneladm  36864 Feb  1 15:41 ..
-rwxr-xr-x    1 paneladm paneladm    224 Feb  1 15:41 cli.js
-rw-r--r--    1 paneladm paneladm 329588 Feb  1 15:41 electron.d.ts
-rw-r--r--    1 paneladm paneladm    338 Feb  1 15:41 index.js
-rw-r--r--    1 paneladm paneladm   1854 Feb  1 15:41 install.js
drwxr-xr-x    3 paneladm paneladm   4096 Feb  1 15:41 node_modules
-rw-r--r--    1 paneladm paneladm    814 Feb  1 15:41 package.json
-rw-r--r--    1 paneladm paneladm   6444 Feb  1 15:41 README.md
paneladm@debian:~$ cd .config/yarn/global/node_modules/electron/
paneladm@debian:~/.config/yarn/global/node_modules/electron$
```

2. Upgrade yarn global as below:

```bash
~$ yarn global upgrade

├─ duplexer@0.1.1
├─ duplexer2@0.0.2
├─ duplexer3@0.1.4
├─ duplexify@3.5.3
├─ ecc-jsbn@0.1.1
├─ ecdsa-sig-formatter@1.0.9
├─ ee-first@1.1.1
├─ electron-download@3.3.0
├─ electron-to-chromium@1.3.32
├─ electron@1.7.12
├─ emojis-list@2.1.0
├─ encodeurl@1.0.2
├─ encoding@0.1.12
├─ end-of-stream@1.4.1
├─ ent@2.2.0
├─ entities@1.1.1
├─ envinfo@3.11.1
├─ errno@0.1.6
├─ error-ex@1.3.1
...

├─ yesno@0.0.1
└─ zip-stream@1.2.0
Done in 102.58s.
paneladm@debian:~$ 
```

:)

**Comment by yidafu** [comment]
Nice. yarn may better for me， rather then npm at low net speed case.　＠barbalex 　ｔｈｘ．
