### ISSUE TITLE
[Rendering] Dots in VSCode and Atom

### ISSUE THREAD

**Issue by ShalokShalom** [electron/electron#10895]
* Electron version: Current
* Operating system: KaOS

### Expected behavior

Rendering without those elements

### Actual behavior

![screenshot_20170926_212807](https://user-images.githubusercontent.com/6344099/30880036-9b29ff12-a301-11e7-943c-db7b16f6537a.png)

Issue in VS Code repo: https://github.com/Microsoft/vscode/issues/35169

**Comment by felixrieseberg** [comment]
@ShalokShalom would you be able to extend this bug report with a bit of information? We're all volunteers here and chances that anybody will fix this are _extremely slim_ if we don't know which versions, operating systems, and reproduction steps lead you to see those rendering issues.

**Comment by ShalokShalom** [comment]
I thought Electron is an official Github project?

The OS is already mentioned. You can see here the build script, which I use:
https://gist.github.com/ShalokShalom/ea4c48f1b12f16329da209068f9c20c4

It's the binary version of VSCode, as you can see. It contains Electron in it. 
https://github.com/Microsoft/vscode/blob/master/package.json#L4

As said, its the current version. 

Can you recommend me some steps, how to track this issue?
Since as also already mentioned, appeared this issue out of nowhere. 

VSCode people lead me here.

I can provide some infos about my system: 
```
➜  ~ inxi -Fxz
System:    Host: cosmos Kernel: 4.12.10-1 x86_64 bits: 64 gcc: 6.4.0 Desktop: KDE Plasma 5.11.0 (Qt 5.9.2)
           Distro: KaOS (2017)
Machine:   Device: laptop System: Hewlett-Packard product: HP EliteBook 8570p v: A1028C1100 serial: N/A
           Mobo: Hewlett-Packard model: 17A7 v: KBC Version 42.38 serial: N/A
           UEFI: Hewlett-Packard v: 68ICF Ver. F.62 date: 04/07/2015
Battery    BAT0: charge: 41.4 Wh 96.8% condition: 42.7/42.7 Wh (100%) model: Hewlett-Packard Primary status: N/A
CPU:       Dual core Intel Core i5-3360M (-HT-MCP-) arch: Ivy Bridge rev.9 cache: 3072 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 11175
           clock speeds: max: 3500 MHz 1: 1199 MHz 2: 1199 MHz 3: 1199 MHz 4: 1199 MHz
Graphics:  Card: Intel 3rd Gen Core processor Graphics Controller bus-ID: 00:02.0
           Display Server: x11 (X.Org 1.19.4 ) drivers: intel (unloaded: modesetting,vesa)
           Resolution: 1366x768@60.07hz
           OpenGL: renderer: Mesa DRI Intel Ivybridge Mobile version: 4.2 Mesa 17.1.10 Direct Render: Yes
Audio:     Card Intel 7 Series/C216 Family High Definition Audio Controller
           driver: snd_hda_intel bus-ID: 00:1b.0
           Sound: Advanced Linux Sound Architecture v: k4.12.10-1
Network:   Card-1: Intel 82579LM Gigabit Network Connection (Lewisville)
           driver: e1000e v: 3.2.6-k port: 4060 bus-ID: 00:19.0
           IF: enp0s25 state: down mac: <filter>
           Card-2: Intel Centrino Advanced-N 6205 [Taylor Peak] driver: iwlwifi bus-ID: 24:00.0
           IF: wlo1 state: up mac: <filter>
Drives:    HDD Total Size: 250.1GB (91.4% used)
           ID-1: /dev/sda model: Samsung_SSD_850 size: 250.1GB
Partition: ID-1: / size: 225G used: 205G (92%) fs: xfs dev: /dev/sda2
           ID-2: /boot size: 300M used: 34M (12%) fs: vfat dev: /dev/sda1
           ID-3: swap-1 size: 8.81GB used: 0.00GB (0%) fs: swap dev: /dev/sda3
Sensors:   System Temperatures: cpu: 54.0C mobo: 0.0C
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 196 Uptime: 11:13 Memory: 4157.7/7849.7MB Init: systemd runlevel: 5 Gcc sys: 6.4.0
           Client: Shell (zsh 5.4) inxi: 2.3.40 
➜  ~ 
```

**Comment by ctrochalakis** [comment]
I am having exactly the same issue.

```
Graphics:  Card: Intel HD Graphics 520 bus-ID: 00:02.0
           Display Server: X.Org 1.19.5 drivers: modesetting (unloaded: fbdev,vesa)
           Resolution: 1920x1080@60.05hz
           OpenGL: renderer: Mesa DRI Intel HD Graphics 520 (Skylake GT2)
           version: 4.5 Mesa 17.2.3 Direct Render: Yes
```

**Comment by ShalokShalom** [comment]
This is still happening in 19.1

![screenshot_20180106_103422](https://user-images.githubusercontent.com/6344099/34638512-4173d08a-f2cd-11e7-9367-81afef595d16.png)

**Comment by ShalokShalom** [comment]
And it also happens in Atom: 
![screenshot_20180106_115536](https://user-images.githubusercontent.com/6344099/34639051-a5415ec4-f2d8-11e7-8b39-54ce4d827ebe.png)

**Comment by ShalokShalom** [comment]
Can I do something to help?

**Comment by ShalokShalom** [comment]
Well, this is even merged already: https://github.com/atom/atom/issues/15737

Thanks a lot for this amazing support ^-^
