### ISSUE TITLE
auto enable the devtools sensors for geolocation mock?

### ISSUE THREAD

**Issue by saselovejulie** [electron/electron#10906]
* Electron version: 1.7.9
* Operating system: win10 64

how can i auto enable the devtools sensors for geolocation mockup?
![1508923195](https://user-images.githubusercontent.com/13128637/31990831-c07aeee4-b9a8-11e7-8594-83553b741154.png)

i have try this js code : 
```
window.navigator.geolocation.getCurrentPosition = function(callback) {
                var position = {
                    coords : {
                        latitude : '55.755826',
                        longitude : '37.6173'
                    }
                };
                callback(position);
            };
```
but it didn't work as the devtools didn't enable sensor..
please help me, thanks

**Comment by felixrieseberg** [comment]
You can find them in the dev tools in the usual location. Let me know if I misunderstood you and we'll reopen the ticket.

![screen shot 2017-10-25 at 11 52 16 am](https://user-images.githubusercontent.com/1426799/32017253-fceae588-b97a-11e7-8946-dc2c7882e79c.png)

**Comment by saselovejulie** [comment]
@felixrieseberg thanks for explain, i find it and us js code to mock location.

**Comment by robsonhermes** [comment]
@saselovejulie what code did you use to mock location? or did you solve your problem by changing it using the dev tools sensor panel?
Asking cause I would also need to mock it programmatically.
