### ISSUE TITLE
Dock / Window icon ignores .desktop overwrite

### ISSUE THREAD

**Issue by amitkeret** [electron/electron#10901]
* Electron version: 1.7.9
* Operating system: Ubuntu 17.10, GNOME shell

In Ubuntu, one can declare `.desktop` files as application shortcuts. One of the values in this file is `Icon`, which tells Ubuntu which icon to use. This can be a path to a file of a keyword that may be supported by the current theme. If the keyword is not supported, the default (app's native) icon is used.

This should be supported, so that the dock/window icon would preferably be the one defined in the current theme. In any case, there's always a fallback to the icon defined internally in the Electron app.

### Expected behavior
The Electron application icon should be overridden if it's opened via a `.desktop` file with a `Icon` definition in it.

### Actual behavior
The dock/window icon is always the one set internally in the Electron app.

### How to reproduce
1. create Electron app
2. create `[appname].desktop` and place in `~/.local/share/applications`
3. make sure your `.desktop` file has the following key-value pair:
```
Icon=/path/to/icon/file
(or)
Icon=keyword (eg. "evolution" should use the theme's Evolution app icon)
```
4. start the application

**Comment by felixrieseberg** [comment]
I'm wondering - isn't this something that should really be handled by the operating system? If the operating system wants to override the icon, it should just do so.

Given that Electron will eventually just tell the OS which icon to use, it _feels wrong_ to me that Electron would query the OS for the right icon, just to then hand it back to the OS. That said, I'm probably misunderstanding things!

**Comment by codebytere** [comment]
Closing in agreement with the above in addition to the staleness of this issue.
