### ISSUE TITLE
[Auto-Update] Update the app on next start OR before quit rather than restart

### ISSUE THREAD

**Issue by Ajeey** [electron/electron#10903]
* Electron version:1.7.8
* Operating system:Mac OS

### Expected behavior
After the new version app is downloaded in the background, can we implement a mechanism so that the  **app is updated before it quits** OR **apply the update on the "next launch/start"** of the app? This would eliminate the need for restarting the current running app.

### Actual behavior
Auto updating on mac via `autoUpdater `module which is built upon Squirrel.Mac right now needs the current running app to restart to apply the update.
 

### How to reproduce
Implement electron auto update functionality to observe the behavior.
Will provide a repo if needed.

P.S I was trying out with the following code - 

```
var updateDownloaded = false;

autoUpdater.on('update-downloaded', (info) => {
    updateDownloaded = true;
})

app.on("before-quit", () => {
    console.log("before-quit called");
    if(updateDownloaded) {
        autoUpdater.quitAndInstall();
    }
});
```
`before-quit` event of the app I try to `quitAndInstall`. While this updates the app and the new version of the app is spawned. (all good works as intended)

Now, during this spawn of the new version, is it possible for to spawn with some arguments (ex : `--update`) so that we can listen to this and quit the app immediately.
Ex - 
```
if(args === "--update" {
  app.quit()
}
```
Thus in effect you will have an seamless auto-update mechanism.

All I want to accomplish is to auto update to work with the need to restart the current running app.
Please provide your inputs.

**Comment by joshaber** [comment]
Quitting the app without restarting will also install the update.

**Comment by Ajeey** [comment]
@joshaber Mind === Blown
Why isn't it documented here? - https://electron.atom.io/docs/api/auto-updater

**Comment by joshaber** [comment]
Like Electron itself, documentation is a constant work in progress 😄 A PR adding that would be welcome I imagine.

**Comment by Ajeey** [comment]
Done :)

**Comment by develar** [comment]
@Ajeey I have already answered in another electron-updater question — https://github.com/electron-userland/electron-builder/issues/2213#issuecomment-338154690 electron-updater follows Electron recommendation (and on macOS uses Squirrel.Mac under the hood).

> This would eliminate the need for restarting the current running app.

So, please do not call `quitAndInstall`. Update will be installed silently on quit (when user decided to quit, not your app). electron-updater method [checkForUpdatesAndNotify](https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/AppUpdater.ts#L168) works exactly in this way — just notify that update will installed on quit and nothing more.

**Comment by felixrieseberg** [comment]
I guess we can close this, then 😉 The PR is in progress and will eventually make it in.

**Comment by clytras** [comment]
> @Ajeey I have already answered in another electron-updater question — [electron-userland/electron-builder#2213 (comment)](https://github.com/electron-userland/electron-builder/issues/2213#issuecomment-338154690) electron-updater follows Electron recommendation (and on macOS uses Squirrel.Mac under the hood).
> 
> > This would eliminate the need for restarting the current running app.
> 
> So, please do not call `quitAndInstall` explicitly. Update will be installed silently on quit (when user decided to quit, not your app). electron-updater method [checkForUpdatesAndNotify](https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/AppUpdater.ts#L168) works exactly in this way — just notify that update will be installed on quit and nothing more.

The user will decide to quit and most likely will be surpriced that they'll have to spend a couple of minutes and wait for an app to install an update. Users when they quit the app will be most likely on a phase of shutting down or taking the laptop to an other place. That will be frustrating and not so friendly UX in my opinion.
