### ISSUE TITLE
Focused window is always null

### ISSUE THREAD

**Issue by Rawnly** [electron/electron#10913]
* Electron version: 1.7.9
* Operating system: macOS 10.13

### Expected behavior
Get the focused window

### Actual behavior
Getting `null`

### How to reproduce
```js
// ... app.js
app.on('ready', () => {
	mainWindow = new BrowserWindow({
		width: 400,
		height: 400,
		titleBarStyle: 'hiddenInset'
	})

	console.log( BrowserWindow.getFocusedWindow() );
})
```

**Comment by felixrieseberg** [comment]
You have to give the OS a tick to actually open and focus the window. That's expected behavior.

```js
mainWindow = new BrowserWindow(options)
setTimeout(() => console.log(BrowserWindow.getFocusedWindow())
```

**Comment by Rawnly** [comment]
Nope it happens even if I run it via menu, the intention was to change a variable in the render process, and get the current window via ‘getFocusedWIndow’.. I’ll send a real piece of code for better explanation

**Comment by sakamudis** [comment]
Electron version: 1.7.7
Operating system: Cent OS 7

React application with electron on Cent OS 7.
 
I have a login page with username and password. While entering username/password the focus of input field is shifting(went off) to another active window(either OS console window or another electron window)
How to prevent that behavior or keep the focus forcefully in the same input field?
