### ISSUE TITLE
input with datalist issue

### ISSUE THREAD

**Issue by anahoua16** [electron/electron#10917]
Hi, I am facing a problem when I want to read the value of an input that have suggestions from datalist, the value that I get from the input is only what I type with the keyboard not the selected value, i’ll give an example to explain better, for the HTML bellow, if I type ‘on’ than I select the suggestion which is ‘111’ when I try to read the value of the input (document.getElementById(“num”).value) I get ‘on’ instead of ‘111’, any suggestions to fix it??
`<input type="text" list="numbrs" id="num">
	<datalist id="numbrs">
		<option value="111">One</option>
		<option value="222">two</option>
	</datalist>`

**Comment by felixrieseberg** [comment]
This seems really more like a basic HTML question rather than an Electron-specific question - the answer to your question can be found here: https://stackoverflow.com/questions/26103285/find-selected-item-in-datalist-in-html

**Comment by anahoua16** [comment]
@felixrieseberg my problem is not to know which option is selected, but like explained the value of the input is not getting updated when we select a suggestion, I believe that is specific for electron since when I try this on chrome it works fine I get the value displayed on the input field, which is not the case in electron, it takes only what I type with the keyboard and it doesn't update the value when I select from suggestions with the mouse. I don't know if I explained clearly.

**Comment by anahoua16** [comment]
I could overcome this by using SELECT2 and Jquery Autocomplete, but I believe that Electron team should review the behaviour of the input field when using datalist since chrome behave as it shoulds but electron 'chrome 58' is not

**Comment by brenca** [comment]
Duplicate of #9860
