### ISSUE TITLE
Launching Electron creates an unwanted folder

### ISSUE THREAD

**Issue by ogo-adp** [electron/electron#10910]
* Electron version: 1.8.2-beta 1
* Operating system: Windows 7

### Expected behavior

Launching electron should not create a subfolder.

### Actual behavior

Running electron creates a subfolder in the electron folder. The subfolder is named "%HOMEDRIVE%%HOMEPATH%" and contains subfolders AppData\Roaming\Electron\logs
I've not seen this behaviour in any previous version, and obviously %HOMEDRIVE%%HOMEPATH% are environnement variables names that should be expanded (hence the bug).

### How to reproduce

Download electron-v1.8.2-beta.1-win32-x64.zip
Launch electron.exe
See the folder appearing

**Comment by codebytere** [comment]
@ogo-adp there was a new option added to `getPath`, the windows string must have a bug. 

See here: https://github.com/electron/electron/blob/master/brightray/browser/browser_main_parts.cc#L171

I'll fix this as soon as I can.

**Comment by ogo-adp** [comment]
Thanks for your response

**Comment by codebytere** [comment]
Closing as this has been fixed.
