### ISSUE TITLE
Typescript definition File - TouchBarConstructorOptions.items Array indicator missing 

### ISSUE THREAD

**Issue by alexanderwe** [electron/electron#10916]
* Electron version: 1.8.1
* Operating system: MacOS 10.13 (High Siera)

### Expected behavior

Using Typescript to create a new TouchBarConstructorOptions object. The `items` value should be an array, as indicated in the [docs](https://github.com/electron/electron/blob/master/docs/api/touch-bar.md).

### Actual behavior

Using the Typescript definitions file `electron.d.ts`, the interface `TouchBarConstructorOptions` is providing the key `items` without the array indicator `[]`. Therefore `tsc` and `tslint` are throwing errors.

```
interface TouchBarConstructorOptions {
    items: TouchBarButton | TouchBarColorPicker | TouchBarGroup | TouchBarLabel | TouchBarPopover | TouchBarScrubber | TouchBarSegmentedControl | TouchBarSlider | TouchBarSpacer;
    escapeItem?: TouchBarButton | TouchBarColorPicker | TouchBarGroup | TouchBarLabel | TouchBarPopover | TouchBarScrubber | TouchBarSegmentedControl | TouchBarSlider | TouchBarSpacer;
  }
```
should be `items` with `array`
```
interface TouchBarConstructorOptions {
    items: TouchBarButton | TouchBarColorPicker | TouchBarGroup | TouchBarLabel | TouchBarPopover | TouchBarScrubber | TouchBarSegmentedControl | TouchBarSlider | TouchBarSpacer[];
    escapeItem?: TouchBarButton | TouchBarColorPicker | TouchBarGroup | TouchBarLabel | TouchBarPopover | TouchBarScrubber | TouchBarSegmentedControl | TouchBarSlider | TouchBarSpacer;
  }
```
### How to reproduce
Just try to instantiate a new Touchbar object inside a typescript file.

```
import { TouchBar } from 'electron';
const { TouchBarButton } = TouchBar;

const test: Electron.TouchBarConstructorOptions = {
    items: [new TouchBarButton({
        backgroundColor: '#00c4a7',
        click: () => {
            console.log('Test');
        },
        label: 'test',
    })],
};

export const touchBar = new TouchBar(test);
```
The error which is thrown:

```
[ts]
Type '{ items: TouchBarButton[]; }' is not assignable to type 'TouchBarConstructorOptions'.
  Types of property 'items' are incompatible.
```

I hope I didn't miss something important here or I didn't do something wrong on my side. If I did please bear with me.

**Comment by felixrieseberg** [comment]
Good point, I think we just missed that. Thanks for pointing it out! I'll take a look this week.

**Comment by alexanderwe** [comment]
Thank you !

**Comment by alexanderwe** [comment]
If someone runs into the same issue you can avoid the error to be thrown if you add `as any` after the array initialization.  But this is only a workaround if you want to use Typescript until this is resolved.

```
const test: Electron.TouchBarConstructorOptions = {
    items: [new TouchBarButton({
        backgroundColor: '#00c4a7',
        click: () => {
            console.log('Test');
        },
        label: 'test',
    })] as any,
};

```

**Comment by MarshallOfSound** [comment]
Fixed in https://github.com/electron/electron-typescript-definitions/pull/84
