### ISSUE TITLE
Built-in Node module not working

### ISSUE THREAD

**Issue by xywz** [electron/electron#10925]
https://nodejs.org/docs/v8.2.1/api/child_process.html

> If this method is invoked as its util.promisify()ed version, it returns a Promise for an object with stdout and stderr properties. In case of an error, a rejected promise is returned, with the same error object given in the callback, but with an additional two properties stdout and stderr.
>
> For example:
>
> ```js
> const util = require('util');
> const exec = util.promisify(require('child_process').exec);
> 
> async function lsExample() {
>   const { stdout, stderr } = await exec('ls');
>   console.log('stdout:', stdout);
>   console.log('stderr:', stderr);
> }
> lsExample();
> ```
In Electron stdout and stderr are `undefined`.

* Electron version: 1.8.x

**Comment by groundwater** [comment]
Please see https://github.com/electron/electron/issues/10934#issuecomment-340066195
