### ISSUE TITLE
Render Window Process only works on 1.6.x versions (Raspberry Pi - armv7l)

### ISSUE THREAD

**Issue by samuelcarreira** [electron/electron#10939]
* Electron version: 1.7.x - 1.8.2-beta 1
* Operating system: Raspbian (Rasperry Pi 3 - armv7l)

### Expected behavior
Render window/process should work.

### Actual behavior
**I only can get this to work if I use an old version (1.6.x - 1.6.15), if I update to a newer version it stops working.**
![1615](https://user-images.githubusercontent.com/4456690/32076047-8c9890ba-ba96-11e7-9158-17ecfa831ffe.PNG)

Render window/process cannot be started. Don't render the page, only opens the browser window with the specified dimensions. It even cannot open the Chrome dev tools as instructed on the main process.

![182](https://user-images.githubusercontent.com/4456690/32076046-8c666900-ba96-11e7-949c-2911a279be5b.PNG)

### How to reproduce
I use electron quick start as the starting point. I tested without VNC connection and also with electron 1.7.x versions.

**Comment by felixrieseberg** [comment]
Quick question: I assume it is, but is Chromium working fine for you?

**Comment by samuelcarreira** [comment]
Yes I use chromium as the default browser on the raspbian OS. I don’t know exactly which version, but I can check it

**Comment by bgsuello** [comment]
mine was working with 1.7.9 when adding 
``` javascript 
win.webContents.on('crashed', () => {
   win.reload();
});
``` 
to the `function createWindow()`:
```javascript
...

function createWindow() {

  const electronScreen = screen;
  const size = electronScreen.getPrimaryDisplay().workAreaSize;

  // Create the browser window.
  win = new BrowserWindow({
    width: 480,
    height: 320
  });

  // reload the window when crashed.
  win.webContents.on('crashed', () => {
    win.reload();
  });

...
}
```

But after making it work: **CSS3 animations were so slow**.

**Comment by samuelcarreira** [comment]
![electron](https://user-images.githubusercontent.com/4456690/32808855-74797bde-c98c-11e7-87bb-ff26a9465107.PNG)

@bgsuello thank you for your suggestion. 

**I've finally run successfully the electron quick start with the 1.7.x version!**

What I did:

1. First I give a try to the electron v1.8.2-beta.2 without any success.
2. I reverted to the 1.7.9 (in the process I updated the yarn version and the system) and the app works fine!

The @bgsuello code wasn't needed, so I ended without understanding the reasons for this strange behavior.

**Comment by adipascu** [comment]
I am having a similar issue, the screen is white when running electron 1.8.1, reverting to 1.7.9 resolves my issue.

I have noticed the npm @latest tag is pointing to 1.7.9, and 1.8.1 is released on npm but is missing from github releases. Is 1.8.1 released as stable ?

**Comment by samuelcarreira** [comment]
The last stable version can be found on electron official website / home page, which currently is the 1.7.9. The 1.8.x are in beta state.

**Comment by bgsuello** [comment]
@samuelcarreira: 

> The @bgsuello code wasn't needed, so I ended without understanding the reasons for this strange behavior.

It was all good with `1.7.9` but when I used the `1.8.2-beta.1` with RasberryPi the renderer process is crashing that is why I need to reload it. 😄

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
