### ISSUE TITLE
Possible to change accent color for your app only on Windows?

### ISSUE THREAD

**Issue by adauhshfghudfsjf** [electron/electron#10937]
I noticed there's: systemPreferences.getAccentColor()

Is there also something to SET this, but just for your app? That would make it look much better and fit in better with the contents.

**Comment by MarshallOfSound** [comment]
The accent color is a system-wide thing, if you are referring to setting the title bar color inside your app (this is normally where the accent color goes) you can not do that from a non UWP app 👍
