### ISSUE TITLE
Clicking an Electron tray icon when the context menu of a different Electron tray icon is open does not open the context menu

### ISSUE THREAD

**Issue by xywz** [electron/electron#10934]
For non-Electron trays it does.

* Operating system: macOS

**Comment by groundwater** [comment]
Hi @xywz. It looks like you are creating a list of fixes that you would like to see made to the project. We value your enthusiasm, but you need to follow the templates we have provided. We will close these issues, and I will explain the next steps.

1. If you have a bug, please follow the template. Provide details, and exact steps to reproduce.
2. If you have a feature request, and you want to do the work, you are welcome to discussing the idea in detail.
3. If you have a feature request, and expect others to do the work, please group _all_ features together in one issue for now. We can extract individual issues as we work on them.

For now, _please limit creating new issues to maximum once per day_.

We want to work together in good faith, and we believe the above is fair to both you and our maintainers. If you choose not to follow our request, your account may be blocked from participating in _all_ electron projects. I would prefer that does not happen. Thanks for listening.
