### ISSUE TITLE
Slow BrowerWindow because of slow Menu

### ISSUE THREAD

**Issue by jrieken** [electron/electron#10947]
* Electron version: 1.7.x
* Operating system: all

### Expected behavior

calling `new BrowserWindows` should not spend 30-300ms creating `Menu`

### Actual behavior

We get reports from our users, via [`code --prof-start`](https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-startup), that show that creating a new browser windows is often slow. The profiles all point to the `Menu` constructor which ideally takes around 30ms but often takes more than 250ms (https://github.com/Microsoft/vscode/issues/21964)

Ideally this can be avoided, esp. because this builds the default menu not the actual menu.

<img width="927" alt="screen shot 2017-10-27 at 10 42 54" src="https://user-images.githubusercontent.com/1794099/32095516-b8bf8942-bb03-11e7-924d-f2d655bc0147.png">

To repro

* get VS Code, start with `code --prof-startup`, 
* inspect the main-profile using _node-inspector_,

*or*

* clone https://github.com/jrieken/electron-quick-start, 
* run the `npm run start-perf` script, which breaks on port 5678
* attach dev tools and profile..

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron < `1.8.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
