### ISSUE TITLE
Notification onclick is triggered when clicking Close on alert Style MacOS High Sierra notification

### ISSUE THREAD

**Issue by gerges** [electron/electron#10940]
* Electron version: 1.7.9
* Operating system: 10.13 High Sierra

### Expected behavior

`Notification.onclick` should not be triggered when `Close` is clicked

### Actual behavior

`Notification.onclick` is triggered when `Close` is clicked

![notification-triggers-click](https://user-images.githubusercontent.com/320654/32076487-c1d4f4ca-ba65-11e7-9986-873ea3bd60ef.gif)

### How to reproduce

Enable alert style notifications for Electron in MacOS

```
  $ git clone git@github.com:gerges/electron-quick-start.git -b  issue/notification-close-triggers-click
  $ npm install
  $ npm run start
```

**Comment by clusterberries** [comment]
Hi @MarshallOfSound ! What event is triggered when 'close' is clicked?
