### ISSUE TITLE
Is it possible to prevent the autoupdate event?

### ISSUE THREAD

**Issue by ishwarrimal** [electron/electron#10946]
Is it possible to prevent the update from happening if user doesn't want update?

`
autoUpdater.setFeedURL('https://s3-us-west-2.amazonaws.com/xyz/desktop/');

        autoUpdater.checkForUpdates();
        autoUpdater.on('error', () => {
            console.log('error occured');
            return;
        })

        autoUpdater.on('check-for-update',()=>{
            console.log('checking for update');
        });

            autoUpdater.on('update-available', () =>{
                console.log('update is available');
                var index = dialog.showMessageBox({
                    type: 'info',
                    buttons: ['Update','Cancel],
                    title: "Xyz Tech Solution",
                    message: 'New version of Xyz app is available. Do you want to download now?'
                });

                 if (index === 1) {
                     return;
                 }

                autoUpdater.on('update-downloaded', function (event,releaseName) {

                    // # confirm install or not to user
                    var index = dialog.showMessageBox({
                        type: 'info',
                        buttons: ['Restart','Later'],
                        title: "Xyz Tech Solution",
                        message: 'The new version has been downloaded. Please restart the application to apply the updates.',
                        detail: releaseName
                    });

                    if (index === 1) {
                        return;
                    }

                    // # restart app, then update will be applied
                    autoUpdater.quitAndInstall();
                });
            });

        autoUpdater.on('update-not-available', () =>{
            console.log('update is available');
            var index = dialog.showMessageBox({
                type: 'info',
                buttons: ['Ok'],
                title: "Vyapar Tech Solution",
                message: "You've got the latest version of electron app. Thanks for staying on the ball."
            });
            return;
        });`

in my case if user selects  cancel for 'update-available' message, i want it to stop updating. But its not working. Any help will be appreciated.

**Comment by MarshallOfSound** [comment]
> Is it possible to prevent the update from happening if user doesn't want update?

No, as soon as you check for updates the update will be downloaded straight away if one is available

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
