### ISSUE TITLE
--single-process command line parameter causes Electron application to crash

### ISSUE THREAD

**Issue by alexey-ambrozevitch** [electron/electron#10958]
* Electron version: 1.7.8
* Operating system: Microsoft Windows 8 x64

### Expected behavior
Launching electron.exe with --single-process parameter causes application to run per one process.

### Actual behavior
Launching electron.exe with --single-process parameter causes application to crash.

**Comment by MarshallOfSound** [comment]
Electron uses a `process-per-site` model and doesn't support any of the other chromium process models, this is primarily due to how node.js works and from past discussions we won't be able to support any of the other models 👍

**Comment by jsnar** [comment]
NW.js supports single process...
