### ISSUE TITLE
Electron unable to replace file (via download attr) in  MacOS Sandbox, even though read/write entitlement is specified

### ISSUE THREAD

**Issue by gerges** [electron/electron#10950]
* Electron version: 1.7.9
* Operating system: MacOS 10.12.6

### Expected behavior

A sandboxed MacOS app should be able to overwrite a file it created, as long as it was initiated from the save dialog.

### Actual behavior

![mas-overwrite](https://user-images.githubusercontent.com/320654/32115851-010a617c-bb0e-11e7-896c-e54cb8e59266.gif)

The system fails to save the file, attempts to uniquify the filename (appending ` (1)`), which also fails as no permission for that file was retrieved. The Console.app shows the following

```
default	11:48:48.550683 -0500	kernel	SandboxViolation: electron-quick-s(7587) deny(1) file-write-create /Users/igerges/Downloads/.E434N33F2R.com.electron.electron.VZzGoe
default	11:48:51.332456 -0500	kernel	SandboxViolation: electron-quick-s(7587) deny(1) file-write-create /Users/igerges/Downloads/did-it-work (1).png
```

### How to reproduce

```
 $ git clone git@github.com:gerges/electron-quick-start.git -b  issue/mac-sandbox-overwite
 $ npm install
 $ npm run mas
 $ open dist/electron-quick-start-mas-x64/electron-quick-start.app
```

**Comment by liusy182** [comment]
@gerges I am on Mac 10.12.5 but not able to reproduce this issue. File gets replaced properly. Could you confirm again on this?

**Comment by gerges** [comment]
Hey @liusy182, just repro'd it. I started from a clean checkout as well. This report originally came from an external customer as well so that's at least one other repro :-P My mas build I threw in electron-quick-start is a bit hacked together, might be best to verify the app was signed correctly.

```
codesign -dvvv dist/electron-quick-start-mas-x64/electron-quick-start.app
```

and 

```
codesign -d --entitlements - dist/electron-quick-start-mas-x64/electron-quick-start.app
```

**Comment by sethlu** [comment]
Hi @gerges, I managed to reproduce the issue from my end in App Sandbox. Try having both entries below so Electron can temporarily create a `{filename} (1)`, before replacing the existing file with it.

```plist
<key>com.apple.security.files.user-selected.read-write</key>
<true/>
<key>com.apple.security.files.downloads.read-write</key>
<true/>
```

P.S.: Only having `com.apple.security.files.downloads.read-write` may cause Electron to freeze.

**Comment by gerges** [comment]
@sethlu thanks for the suggested workaround. I think that only solves the case where the file was being written to the `Downloads` folder. If I elect to save that file on Desktop, or some other arbitrary folder, I'll hit the same sandbox exception. For this to work properly, I think that temp file would need to be written inside the app sandbox, or in the system temp folder.

**Comment by sethlu** [comment]
@gerges Another workaround may be to use `dialog.showSaveDialog` to get access to write to a file path and manage the IO through Node? However, I'm not sure how "download" can be simulated in that way.

**Comment by sethlu** [comment]
@gerges I think it's an expected behavior from Chromium at least as of now? More solid reference: https://cs.chromium.org/chromium/src/content/browser/download/download_item_impl.cc?type=cs&l=1506&cl=817fd56ec3e2dfec7f0f0b1eacd79b5455bf7e3c

**Comment by soundar78** [comment]
@sethlu 
Should we have to implement the Security scoped bookmarks even if we use webContents.downloadURL(url)?
or will that be taken care by electron?
