### ISSUE TITLE
bootstrap.py macOS 10.12.6 errors

### ISSUE THREAD

**Issue by thewoz** [electron/electron#10961]
hi, 

I tray to install the last version of electron on macOS 10.12.6 I have the above issue:

artswarms-MBP:electron thewoz$ ./script/bootstrap.py -v
Running in verbose mode
git submodule sync --recursive
Synchronizing submodule url for 'vendor/boto'
Synchronizing submodule url for 'vendor/breakpad'
Synchronizing submodule url for 'vendor/breakpad/src'
Synchronizing submodule url for 'vendor/crashpad'
Synchronizing submodule url for 'vendor/depot_tools'
Synchronizing submodule url for 'vendor/gyp'
Synchronizing submodule url for 'vendor/libchromiumcontent'
Synchronizing submodule url for 'vendor/libchromiumcontent/vendor/boto'
Synchronizing submodule url for 'vendor/libchromiumcontent/vendor/depot_tools'
Synchronizing submodule url for 'vendor/native_mate'
Synchronizing submodule url for 'vendor/node'
Synchronizing submodule url for 'vendor/pdf_viewer'
Synchronizing submodule url for 'vendor/pdf_viewer/vendor/grit'
Synchronizing submodule url for 'vendor/requests'
git submodule update --init --recursive
/Users/thewoz/Research/LIBRARIES/electron/script/update-clang.sh
Clang already at 299960-1
/usr/bin/python setup.py build
running build
running build_py
running egg_info
writing requirements to requests.egg-info/requires.txt
writing requests.egg-info/PKG-INFO
writing top-level names to requests.egg-info/top_level.txt
writing dependency_links to requests.egg-info/dependency_links.txt
reading manifest file 'requests.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'requests.egg-info/SOURCES.txt'
/usr/bin/python setup.py build
running build
running build_py
running egg_info
writing boto.egg-info/PKG-INFO
writing top-level names to boto.egg-info/top_level.txt
writing dependency_links to boto.egg-info/dependency_links.txt
reading manifest file 'boto.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'boto/mturk/test/*.doctest'
warning: no files found matching 'boto/mturk/test/.gitignore'
writing manifest file 'boto.egg-info/SOURCES.txt'
running build_scripts
npm install --verbose
Traceback (most recent call last):
  File "./script/bootstrap.py", line 261, in <module>
    sys.exit(main())
  File "./script/bootstrap.py", line 55, in main
    update_node_modules('.')
  File "/Users/thewoz/Research/LIBRARIES/electron/script/lib/util.py", line 289, in update_node_modules
    execute_stdout(args, env)
  File "/Users/thewoz/Research/LIBRARIES/electron/script/lib/util.py", line 181, in execute_stdout
    subprocess.check_call(argv, env=env, cwd=cwd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by felixrieseberg** [comment]
Hey! Looks a bit like the core issue here is that Python failed to execute `npm install`. Do you have Node and npm installed?

**Comment by thewoz** [comment]
my bad, 
I was convinced that I installed it correctly.

sorry about that
