### ISSUE TITLE
How to disable downgrading of app ?

### ISSUE THREAD

**Issue by poojas2288** [electron/electron#10965]
* Electron version:
1.7.3
* Operating system:
Win and Mac
### Expected behavior
If I have my app installed with version 1.3.
If I try to install a lower version app by launching my app installer with version 1.2, then 1.2 should not get installed, i.e.; app should not be downgraded.

### Actual behavior
App gets downgraded, and a lower version gets installed.

 Downgrade should not be possible since I already have a higher version of app already installed.
### How to reproduce
1. Create an electron app for windows (I'm using nsis) and for Mac (dmg) with version 1.0.0
2. Create another version of same app with higher version (1.1.0)
3. Install app version 1.1.0 by manually executing the installer. App gets installed with version 1.1.0
4. Now run the installer with lower version (1.0.0)
5. The app with lower version will get installed.

**Comment by MarshallOfSound** [comment]
This kind of thing should be asked on Squirrel.Windows as that is what you are using to make the installer.

That said, this is just how installers work, if you ask to install a version that's the version that's gonna be installed :smile: If you want to ensure the user can't run an old version, you need to do an update check on first run of a newly installed version and prevent the user using the app till that update check has run.
