### ISSUE TITLE
Override all connections over NodeJS standard library

### ISSUE THREAD

**Issue by yattamax** [electron/electron#10964]
Hi everyone,
electron use "chromium library" to perform connection (HTTP/s).

Is possible to override this feature and use NodeJS HTTP/S native library instead of "chromium library"?

Thanks
Max

**Comment by felixrieseberg** [comment]
I'm not sure that's actually true. If you're in the main process, you'll be using Node's networking stack - unless you use the `net` module.

In short, the answer is to make your network requests from the main process.

**Comment by yattamax** [comment]
I try to explain better :)

in main.js
 [...]
function createWindow () {
  
   mainSession = session.fromPartition('main')
   mainWindow = new BrowserWindow({
		webPreferences: {
			javascript: true,
			webSecurity: false,
			session: mainSession
		}	    
	  
	});//{width: 1280, height: 600})
  mainWindow.maximize();
  mainWindow.setMenu(null);


  mainWindow.loadURL(url.format({
    pathname: path.join(__dirname, 'index.html'),
    protocol: 'file:',
    slashes: true
  }))
  
  
 [...]
 
 
 in index.html:
 [...]
 <webview partition="main" id="view" class="page" src="http://www.google.com/" autosize="on" preload="preload.js"></webview>
 [...]
 
 
 I need to "intercept" all webview request internally using "http/s" module of NodeJS and not by chromium library


Thanks :)
Best Regards 
Massimiliano
