### ISSUE TITLE
Feature request: allow disabling open file dialogs

### ISSUE THREAD

**Issue by sebakerckhof** [electron/electron#10967]
Currently, the save file dialog can be disabled by using the `will-download` event handler on the session. However, there seems to be no way to disable open file dialogs. Even in kiosk mode.
If you have a kiosk application, that permits the users to browse to other sites. Than this allows the user to browse and upload system files.

**Comment by felixrieseberg** [comment]
Hey! Thanks for the suggestion. Before we jump on that, let me make sure I understand your concern correctly. Specifically, "that permits the users to browse to other sites" looks dangerous to me - I'd suggest that an app that can a) navigate to any site and b) has a potentially adverse user will always be extremely vulnerable, with or without open file dialogs.

With that disclaimer out of the way, here's how you'd do that: Define preload scripts and disable all possibly involved APIs. You'll also have to watch out for `<input type='file' />` inputs, but that's doable.

**Comment by sebakerckhof** [comment]
Well, the application has 2 sessions.
One session shows a selected url (the actual application) which the user can not navigate away from. There's no node access for the browser windows except for what's passed by the preload script.
The other session is for browser windows outside of the selected urls, where permission requests are automatically denied. Also no node integration and no preview script (So basically just a chrome browser).

I could add a preload script like you suggest, but it seems unachievable to create something fully secure. There are lots of ways to open a file save dialog (shortcuts, api's, html elements, dynamically creating the html element, ...) and I can't imagine a preload script that is succesful in disabling all of them. Especially since a user could go to a web page under his control. IMO, kiosk mode should just not allow access to the file system (or at least provide an option to disable it.)

**Comment by u4aew** [comment]
Hi, is there any news?

**Comment by codebytere** [comment]
In agreement with Felix's thoughts above: this isn't something we intend or plan to do at the Electron level, so adopting his suggestions above is going to be your best path forward.
