### ISSUE TITLE
Electron 1.6 v8 crash under Windows 10

### ISSUE THREAD

**Issue by walltex** [electron/electron#10969]
Here is stack trace for crash

[v8-internal-bodydesctorbase-interatepointers.txt](https://github.com/electron/electron/files/1427801/v8-internal-bodydesctorbase-interatepointers.txt)

* Electron version: 1.6.15
* Operating system: Windows NT (10.0.15063)

### Expected behavior

No crash

### Actual behavior

Crash

**Comment by felixrieseberg** [comment]
Given that the crash happened in V8, I'd heavily recommend using the latest Electron, which comes with a newer version of V8, which hopefully has less bugs.

**Comment by sofianguy** [comment]
Let us know if you are still having issues after @felixrieseberg's suggestion. Closing for now.
