### ISSUE TITLE
.getAppPath()

### ISSUE THREAD

**Issue by purplekrayons** [electron/electron#10975]
I'm not sure if this is intended behaviour.

I am packaging a standalone executable with my electron app. I define it as an `extraFile` in `package.json` and all is good. In order to execute that file, using `execFile()`, i need to obtain a direct path to the executable. I tried using `app.getAppPath()` as described in [app.md](https://github.com/electron/electron/blob/master/docs/api/app.md)

According to this, it should return the current application directory.

In my windows environment, my application executable is located here (after installing):
`C:\Users\Batman\AppData\Local\Programs\MyApp\MyApp.exe`

My bundled executable (the target), resides here:
`C:\Users\Batman\AppData\Local\Programs\MyApp\MyEngine.exe`

When I attempt to obtain the application directory using `app.getAppPath()` from within my `main.js` file, which i expect to be:
`C:\Users\Batman\AppData\Local\Programs\MyApp\`

i am instead returned:
`C:\Users\Batman\AppData\Local\Programs\MyApp\resources\app.asar\`

This is my workaround. What concerns me is how I would approach that in a mac environment (which is next on my build list).

```
var currentPath = app.getPath('exe');
var enginePath = currentPath.replace("MyApp.exe", "MyEngine.exe");

# OUTPUT
# C:\Users\Batman\AppData\Local\Programs\MyApp\MyEngine.exe
```

Is `app.getAppPath()` functioning as intended, and moreover, what is the best way to simply return the root installation path:

`C:\Users\Batman\AppData\Local\Programs\MyApp\`

**Comment by MarshallOfSound** [comment]
Yes it is functioning as expected, it returns the path to the running application which in Electron land is not the executable rather that `package.json` / `index.js` file that Electron is running.  If you want to find the path to the actual executable you should use `process.execPath` and then resolve your file from there

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
