### ISSUE TITLE
Feature request: webview session restoring

### ISSUE THREAD

**Issue by ncortines** [electron/electron#10970]
Hi,

While some browsers do automatically restore session cookies, e.g. Chrome, some others do not, e.g. Firefox.

Electron belongs to the second group, session cookies are not persisted or restored.

One possible workaround for this is to use the cookies API to set a expiry date.

I think it would be great to add an (opt-in) attribute to `<webview>` tag, e.g. `restoresession`, in order to emulate Chrome's behavior and restore session cookies.

Thanks,

Juan

**Comment by TimNZ** [comment]
I believe this has been discussed before, and you can achieve this yourself by loading/saving cookies on app load/exit.

Not something that should be baked into Electron.

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR.
