### ISSUE TITLE
How To Override all connections over NodeJS standard library?

### ISSUE THREAD

**Issue by yattamax** [electron/electron#10973]
Hi everyone,
Sorry if I repeat a similar question, but I think I has explain wrong the first time :(

If I understood, Electron use "chromium library" to perform connection (HTTP/s).

Is possible to override this feature and use NodeJS HTTP/S native library instead of "chromium library"?

I try to explain better with some code :)

in main.js
 [...]
  ```

function createWindow () {
  
   mainSession = session.fromPartition('main')
   mainWindow = new BrowserWindow({
		webPreferences: {
			javascript: true,
			webSecurity: false,
			session: mainSession
		}	    
	});
  mainWindow.maximize();
  mainWindow.setMenu(null);


  mainWindow.loadURL(url.format({
    pathname: path.join(__dirname, 'index.html'),
    protocol: 'file:',
    slashes: true
  }))

```
  
 [...]
 
 
 in index.html:
 [...]
  
` <webview partition="main" id="view" class="page" src="http://www.google.com/" autosize="on" preload="preload.js"></webview>`
  
 [...]
 
 In two words:
I need to "intercept" all (webview) request internally using "http/s" module of NodeJS and not by chromium library, because I need to interact with "ssl session"

An example only with nodeJS (without electron):

```
var https = require('https');
var fs = require('fs');

function parseSession(buf) {
  return {
[TO DO SOMETHING]
  };
}

callback = function(response) {
  var str = ''
  response.on('data', function (chunk) {
    str += chunk;
  });

  response.on('end', function () {
    console.log(str);
  });
}

var options = {
  host: 'github.com',
  port: 443,
  path: '/',
  method: 'GET'
};

var R2 = https.request(options, callback)
.once('socket', (s) => {
  s.once('secureConnect', () => {
    let session = parseSession(s.getSession());
[TO DO SOMETHING]
  });
});

R2.end()
```

My goal is that all HTTP/s connection use a my handler to perform connection (I need to manage SSL Session) :)

Thanks :)
Best Regards 
Massimiliano

**Comment by felixrieseberg** [comment]
https://github.com/electron/electron/blob/master/docs/api/protocol.md#protocolintercepthttpprotocolscheme-handler-completion?

**Comment by yattamax** [comment]
Hi Felix
Hi used interceptprotocol, nut with this I dont have complete ssl session (but I can wrong)

**Comment by yattamax** [comment]
PS:
I need to extraxt "sessionId" and "masterKey", that I can do this with the example show above :)
( inside parseSession(buf) function )

**Comment by yattamax** [comment]
Someone have any idea? :)

**Comment by sofianguy** [comment]
@yattamax Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
