### ISSUE TITLE
How to solve the windows protection tips

### ISSUE THREAD

**Issue by ibeeger** [electron/electron#10986]
![rst](https://user-images.githubusercontent.com/1124832/32268312-76fc13ba-bebc-11e7-8a76-8767e2085dbc.jpg)

Figure  I open app  on windows  have a  tips 
how can i solve this problem 

thanks

**Comment by MarshallOfSound** [comment]
That's windows smart screen, you need to sign your application

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
