### ISSUE TITLE
New windows with default params

### ISSUE THREAD

**Issue by MerDenchik** [electron/electron#10980]
* Electron version: 1.7.5
* Operating system: Linux (Elementary OS Loki)

### Expected behavior

A new window should open with standard OS settings

### Actual behavior

The window opens with the settings of the window from which it was opened

### How to reproduce

I have an iframe with third-party web-site embedded in the electron application, and when I click on <a target="_blank"> or open a new window inside the iframe, I have a new window created for my application, but the problem is ... I have a frame: false; in my application and the window opens with this params too, without a border, which i cant close or resize...

Sry for english. I dont speak English generally. via google translate

**Comment by MerDenchik** [comment]
Do you want to fix it? 🆘

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
