### ISSUE TITLE
It's possible open link in custom web-browser? 

### ISSUE THREAD

**Issue by smachs** [electron/electron#10999]
Hi :] 

Due to some digital certification policies in my application so I depend on the user to register a form from through the browser. I am having to implement this solution because it would not be possible to implement a direct extension from Mozilla Firefox in electron and I needed it exactly because in order for the user to send the form he must authenticate some documents about the company's ownership digitally and for this, he must select his digital certificate by the extension I mentioned above. 

Every event is incorporated into an action of `button-click` and after that, the user should be directed to the button `href="google.com"` in another browser.

I was able to perform a rendering process in conjunction with `electron-shell` he opens the `google.com` but I was not able to implement any solution that would allow me to open the web-address in a specific browser.

My `main.js`.
```

const electron = require('electron');
const app = electron.app;
const BrowserWindow = electron.BrowserWindow;
var Menu = require('menu');
var fs = require('fs');
var shell = require('shell');
var mainWindow = null;

require("babel-register")();

app.on('window-all-closed', function () {
	if (process.platform != 'darwin') {
		app.quit();
	}
});

app.on('ready', function () {
	mainWindow = new BrowserWindow({
		autoHideMenuBar: false,
		webPreferences: {
			nodeIntegration: false
		},
		width: 1200,
		height: 750
	});

	var template = [
		{
			label: "Quick Actions",
			submenu: [
				{ label: "About-us", selector: "orderFrontStandardAboutPanel:" },
				{ type: "separator" },
				{ label: "Exit", accelerator: "Command+Q", click: app.quit }
			]
		}
	];

	Menu.setApplicationMenu(Menu.buildFromTemplate(template));

	require("./server").start()
		.then((app) => {
			mainWindow.loadURL('http://localhost:3000');
		}).catch((err) => {

	});

	mainWindow.openDevTools();
	
	mainWindow.on('closed', function () {
		mainWindow = null;
	});
});
```

Thank you for trying to clarify this cruel doubt that I am already having for days

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by MarshallOfSound** [comment]
You should look at using `child_process` to spawn `firefox.exe` / `firefox.app` with the URL you want it to open.
