### ISSUE TITLE
Different transparent window behaviour with hardware acceleration enabled or disabled.

### ISSUE THREAD

**Issue by redhotbeani** [electron/electron#10994]
Electron version 1.7.9
Windows 7 & Windows 10

### Actual behavior

We’re developing an Electron app with a partly transparent window. By default we had hardware acceleration enabled and couldn’t click through the transparent parts. But when we added `app.disableHardwareAcceleration()` we discovered you can interact with elements behind transparent Electron parts.

### How to reproduce

I’ve made this demo application to demonstrate the behaviour: 
https://github.com/gynzy/electron-transparent-demo/
```
$ git clone git@github.com:gynzy/electron-transparent-demo.git
$ yarn install
$ yarn start
```

Also see this screen recording for a demonstration: 
- https://monosnap.com/file/7vt89JC8V9jPNsVRXsXcMIJt2ijQQi
- the Electron app in the recording is fullscreen, with a red border and transparent background
- inside is an orange, solid rectangle  
- when hardware acceleration is disabled, you can interact with the orange rectangle but click through the transparent fullscreen background
- not on video, but when hardware acceleration is enabled, you cannot click through the transparent fullscreen background

### Expected behavior

What is expected behavior?
We prefer to interact with applications behind a transparent Electron window. We want to utilise this click through behaviour in an application, but only if this is expected Electron behaviour.

I already tried Electron beta versions 1.8.1 & 1.8.2, but window transparency isn’t working in these beta versions (as reported in https://github.com/electron/electron/issues/10678).

**Comment by nitsakh** [comment]
Have you tried using https://github.com/andens/electron/blob/master/docs/api/frameless-window.md#click-through-window ?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.
