### ISSUE TITLE
nativeImage hangs with large and corrupted jpeg

### ISSUE THREAD

**Issue by styts** [electron/electron#11006]
A large (240Mb) and apparently corrupted jpeg image ([link](http://styts.com/babylon.jpg)) causes nativeimage to hang up. The Dev Tools can not be opened.

Some programs like Preview or Photoshop can open it correctly, others crash.

```js
const image = nativeImage.createFromPath('/path/to/babylon.jpg')
console.log(image)
```

* Electron version: 1.7.9 (latest as of writing)
* Operating system: macOS 10.12.6
* Node.js 7.9.0
* Chromium 58.0.3029.110

### Expected behavior

Quick start page with version info is rendered.
Image is read or an exception is thrown.

### Actual behavior

Quick start page not rendered.
Call to nativeImage hangs up. The Dev Tools can not be opened.

### How to reproduce

```bash
git clone https://github.com/styts/electron-quick-start -b native-image
cd electron-quick-start
wget http://styts.com/babylon.jpg
md5sum babylon.jpg
2feca3be6e4a6b937e528782591465c6
npm install
npm start || electron .
```
<img width="801" alt="screen shot 2017-11-03 at 18 17 40" src="https://user-images.githubusercontent.com/293400/32387152-d952ede6-c0c3-11e7-8c19-7053b53c8a66.png">

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
