### ISSUE TITLE
Add a deprecation warning to `crashReporter.setExtraParameter()`

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#11012]
It was disabled/removed in #11013. Add it back please )

/cc @codebytere

**Comment by codebytere** [comment]
@MarshallOfSound why did we remove the deprecation warning? was it killing a test or something?

**Comment by MarshallOfSound** [comment]
@codebytere It was causing that stupid test timeout apparently 👍

**Comment by alexeykuzmin** [comment]
@codebytere 
Check the history of the "electron-osx" build, most of the failures on Nov 3rd were caused by 
"crashReporter module {with, without} sandbox should send minidump with updated extra parameters" tests timed out.
http://208.52.191.140:8080/job/electron-osx-x64/buildTimeTrend

Apparently it's somehow connected to the deprecation warning, without it the tests are fine.

**Comment by codebytere** [comment]
ok rad...i'll add it back today!

**Comment by alexeykuzmin** [comment]
> We still don't know the cause though do we?

I have no idea what could be the reason.
I just wanted to fix the tests, removing the warning helped and I just stopped there )

**Comment by alexeykuzmin** [comment]
Closed by #11321.
