### ISSUE TITLE
window.devicePixelRatio value is different from Chrome and Chromium

### ISSUE THREAD

**Issue by just-gull** [electron/electron#11017]
* Electron version: 1.7.9
* Operating system: Windows 10 ver. 1703 (Build 15063.674)

### Expected behavior

The window.devicePixelRatio should be the same as in the Chrome and Chromium which is 1
#### Chromium screenshot
![default](https://user-images.githubusercontent.com/22587839/32415159-3dbfc3ca-c246-11e7-8a6b-d681e032f99f.png)
#### Chrome screenshot
![default](https://user-images.githubusercontent.com/22587839/32415203-d4ad26ce-c246-11e7-8ce7-16cb606cc3fa.png)

### Actual behavior

The window.devicePixelRatio is 0.9128709435462952
#### Electron screenshot
![default](https://user-images.githubusercontent.com/22587839/32415135-b8ed0e64-c245-11e7-8b3d-fbf78bbf89a0.png)

### How to reproduce

1. run electron-quick-start 
* git clone https://github.com/electron/electron-quick-start
* cd electron-quick-start
* npm install
* npm start
2. press ctrl-shift-i
3. select Console
4. input window.devicePixelRatio

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
