### ISSUE TITLE
Links in the top left corner unclickable when using frameless window

### ISSUE THREAD

**Issue by NurMarvin** [electron/electron#11015]
* Electron version: 1.7.9
* Operating system: Windows 10 Professional

### Expected behavior

Buttons on the left top should be clickable

### Actual behavior

Buttons are unclickable

### How to reproduce

$ git clone https://gitlab.com/NurMarvin/bug-report -b master
$ npm install
$ npm start

First click the upper buttons, they should be clickable.
Then click on the info button (About page) and then try to click the upper buttons again.
They don't work anymore.
When switching to a window with a frame this doesn't happen.

P.S: Ignore the messy code, I tried fixing it since I thought is was my fault and didn't change it back.

**Comment by felixrieseberg** [comment]
Hey @NurMarvin! I took a look at your code and found the issue: Your using `-webkit-app-region: drag` for tons of elements (including the body element). 

Once you remove the instruction, the buttons will be clickable again. I recommend that you define exactly which elements should be clickable with that code - adding it as a blanket statement to parents (like the body) will have weird effects.

**Comment by NurMarvin** [comment]
Oh well, thank you. I read that adding the `-webkit-app-region: drag` to the body element is fine so I went with it. Since I want to make the whole window draggable I will just do
`a,
li,
input[type="submit"],
input[type="reset"],
input[type="button"],
input[type="text"],
button,
textarea {
	-webkit-app-region: no-drag;
}`
This seems to work just fine.
Anyway thanks again @felixrieseberg
