### ISSUE TITLE
Electron fails on Node Version 8+

### ISSUE THREAD

**Issue by Christian2507** [electron/electron#11029]
Hi guys,

my dependencies are:

"electron-forge": "4.1.2",
"electron-prebuilt-compile": "1.7.8",
"ember-electron": "2.6.0",
"electron-compile": "6.4.2",
"electron-protocol-serve": "1.3.0",
"electron-squirrel-startup": "1.0.0"

I tried to upgrade my app to node 8.9.0 (new LTS) but the build of the electron app failed.
After that I tried to  go back to a version on which it worked.
My conclusion is that electron doesnt work on node 8. If I use node version 7.9.0 everything works perfectly but the moment I build with node version 8 I get an error.

### Expected behavior

Electron builds as with node 7.9

### Actual behavior

On Node 8.0.0 it builds the app but I get a JS error.
![js error](https://user-images.githubusercontent.com/16806462/32437193-df9bd03a-c2e6-11e7-9e39-7c8ac57c80f6.PNG)

On Node 8.1.0 - 8.9.0 I get:
npm prune --production failed

### How to reproduce

Ember project with node 8+

Any thoughts?

**Comment by MarshallOfSound** [comment]
This is an NPM issue, you should use NPM@3 (it's known to Just Work(tm))
