### ISSUE TITLE
App cannot support AirPods

### ISSUE THREAD

**Issue by Germxu** [electron/electron#11028]
:bug: Music app  can't pause or play when  AirPods state changes .   :apple: 
It's just a  native web player.  🐞

**Comment by lee-dohm** [comment]
Thanks for the submission.

I'm not certain what app you're referring to. [Electron is an app development framework,](https://electron.atom.io) not a music app. If you're having a problem with your music app, you should contact their support resources for assistance.

Thanks again for your interest :+1:

**Comment by Germxu** [comment]
Thanks for your reply.
[https://github.com/trazyn/ieaseMusic](url)  It`s a Chinese music app ,  developed by electron . 
I have contacted to the developer, and he prefer me issue here.
