### ISSUE TITLE
VSCode doesn't repond to keyboard input

### ISSUE THREAD

**Issue by Pianist038801** [electron/electron#11026]
VSCode is my favorite text editor. Nowadays I realized that keyboard input is not working on editor for several times.
Now I am stuck again.
In terminal window of VSCode, keyboard works.
But on edit screen, when I try to type sth, never works.

**Comment by lee-dohm** [comment]
Thanks for reaching out.

If you're having an issue with VSCode, you should report the problem to [the VSCode project](https://github.com/microsoft/vscode/issues). They're the ones that are going to be most able to help you with the problem you're experiencing. Be sure to [refer to their contributing guidelines](https://github.com/Microsoft/vscode/blob/master/CONTRIBUTING.md) as well :+1:
