### ISSUE TITLE
webview is not reloaded when webview sandbox is on (webPreferences['sandbox'] = true;)

### ISSUE THREAD

**Issue by psh0628** [electron/electron#11033]
* Electron version: 1.7.3 (I was able to repro with latest version, 1.8.2 beta 1)
* Operating system: windows 10

### Expected behavior
webview should reload with sandbox on after 5 sec

### Actual behavior
webview should NOT reload with sandbox on after 5 sec, but it reloaded without webPreferences['sandbox'] = true

Please refer the attached files, main.js, parent.html, and child.html for repro this issue. thanks

### How to reproduce

main.js =>

const {app, BrowserWindow} = require('electron')
const path = require('path')
const url = require('url');

app.once('ready', () => {

  let mainWin = new BrowserWindow({
    show: true
  });

  mainWin.webContents.on('will-attach-webview', (event, webPreferences, params) => {
    webPreferences['sandbox'] = true;
  });

  mainWin.loadURL(url.format({
    pathname: path.join(__dirname, './parent.html'),
  }));
})

parent.html =>

<html>
    
    <head>
      <title>Preload Scripts</title>
    </head>
    <body>
      <button id="devtools">Open the webview's dev tools</button>
      <script>
        setTimeout(()=> {
            document.getElementsByTagName("webview")[0].src = "./child.html#whatIsGoingOn"; 
        }, 1000 * 5);
      </script>
    </body>
    
    <webview id="foo" src="./child.html" style="width:800px; height:680px">
    </webview>

</html>

child.html =>

<html>

<head>
    <script>
        document.addEventListener('DOMContentLoaded', function (event) {
            document.getElementById("findMe").innerHTML = window.location.href;
        });
    </script>
</head>

<body>
    <p id="findMe">
        Hello from inside the webview.
    </p>
</body>

</html>

[WebviewSandbixReloadIssue.zip](https://github.com/electron/electron/files/1447533/WebviewSandbixReloadIssue.zip)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.
