### ISSUE TITLE
crashReporter Callback

### ISSUE THREAD

**Issue by obermillerk** [electron/electron#11036]
It'd be nice to have a callback from the crashReporter of some kind that we could use to handle the crash more gracefully.  I apologize if a mechanism like this is in place, but if there is I haven't been able to find any mention of it.  I know of the webContents crashed event, but there is nothing regarding the crashReporter state here.  At the very least I'd like to be able to tell if the report was successfully submitted or not so that I could inform the user if they need to inform me themselves of the crash.  Additionally, this would allow me to restart the app instead of having to make the user do it themselves which leaves the broken window hanging there doing nothing without even a notification it seems.

**Comment by MarshallOfSound** [comment]
> It'd be nice to have a callback from the crashReporter of some kind that we could use to handle the crash more gracefully

This is straight up not possible 😄 This isn't like an uncaught error in JS where it can be prevented / absorbed.  The crash reporter is only used when something goes terribly wrong at the native level and your process dies.  We can't catch it and call a callback, because the process is already dead.

**Comment by obermillerk** [comment]
Well the crash reporter can submit crash reports, so clearly something is running after the process has crashed; doesn't seem quite so unreasonable to have it do something else as well.

As for monitoring the renderer processes, I have no way of knowing whether a report was submitted or not.  I can know if I started the crash reporter, but say the internet connection isn't working during the crash then it wouldn't be submitted.

Surely there is some way to notify the user that the main process has crashed instead of leaving it there hanging.  I've never seen a native application crash without notifying me, why can't electron hook into the same mechanisms?
