### ISSUE TITLE
The <datalist> drop-down renders at wrong position

### ISSUE THREAD

**Issue by AdorianDoran** [electron/electron#11035]
* Electron version: 1.7.9
* Operating system: Windows (All)

### Expected behavior
On all web browsers, the autocomplete drop-down list is anchored by the bottom edge of the input field.

### Actual behavior
There is a large vertical gap between the input field and the drop-down list, if the window has no menu bar.

![bug](https://user-images.githubusercontent.com/7734010/32465873-b323a6ba-c34d-11e7-9c51-9f950aaa9107.png)

### How to reproduce
Using the following HTML code in a window without a menu bar:

```html
<input type="text" list="sample" />

<datalist id="sample">
  <option value="Bird" />
  <option value="Cat" />
  <option value="Dog" />
</datalist>
```

**Comment by brenca** [comment]
Thanks for reporting this, I noticed the behavior when I fixed some other stuff, I've linked this issue to the PR that has the fix for it.

**Comment by codebytere** [comment]
Resolved with @brenca's PR :)
