### ISSUE TITLE
How can I show an only specific element?

### ISSUE THREAD

**Issue by Jolanr10** [electron/electron#11030]
I want to the just form field  will to be visible as in the following example. How can I do this?

`<!DOCTYPE html>
<html>
<head>
    <title>Page Title</title>
</head>
<div id="body">
    <div class="content">

        
        <form class="form_class" method="POST" action="/">
            <input type="text" class="login_input" name="login_input" placeholder="username">
            <input type="submit" class="login" name="submit" value="Continue">
        </form>
        

        <div class="conte">
            <img src="image.png" />
        </div>
    </div>
</body>
</html>`

**Comment by MarshallOfSound** [comment]
Check out CSS `display: none` 👍

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
