### ISSUE TITLE
How does electron start a jar packet service? how should I better connect to electron and restful Api services?

### ISSUE THREAD

**Issue by cuiyueshuai** [electron/electron#11043]
I'm developing a desktop app with Electron, I tried to connect to MySQL by calling the Restful API service, so I built a jar packet service with spring boot and maven, and bound ports to form restful API services. but I should how to launch the jar packet service?

I'm trying to use the child_process module to run the Java -jar command to start the service:

```
var childProcess = require('child_process');
var options = {maxBuffer:1024*1024*100, encoding:'utf8', timeout:5000};
var child = childProcess.exec('java -jar *******.jar', options, function (error, stdout, stderr) {
    if (error) {
        console.log(error.stack);
        console.log('Error Code: '+error.code);
        console.log('Error Signal: '+error.signal);
    }
    console.log('Results: \n' + stdout);
    if (stderr.length){
        console.log('Errors: ' + stderr);
    }
});
```

But I think that's the wrong way, the starting effect is very unsatisfactory, so I should how to launch the jar packet service? And how should I better connect to electron and restful Api services?

Please forgive my poor English

**Comment by felixrieseberg** [comment]
@cuiyueshuai Thank you for trying out Electron! Your question is less about Electron and more about how to calling MySQL from Node.js.

I recommend asking this question on StackOverflow or a similar forum.
