### ISSUE TITLE
Multiple clipboard items unsupported in API

### ISSUE THREAD

**Issue by alecazam** [electron/electron#11041]
So the native clipboard supports:

1. An item with multiple representations
2. Multiple items with single representations
3. Multiple items with multiple representation each.

Electron seems to only support case 1 with its API.  
  (f.e. writeBuffer at least opens up what we can write out).

* Electron version: 1.7.9
* Operating system: All

Even in Firefox, mozGetItemAt maintains an index that is shared across all representations of the same element, but the Electron API just seems to support case 1.  This is problematic if we want to put multiple PNG, JPG, etc onto the clipboard.  This is also problematic if a user drops multiple items onto the clipboard, especially if they're all different types.  What is the proposed solution for this, other than to write native clipboard code which defeats the reason for using Electron in the first place.

There should be a way to identify each piece of content by index.  
Item 0 - has a png, svg, and filename text all related to it
Item 1 - has a png only
Item 2 - has a svg, and filename text

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR.
