### ISSUE TITLE
How can I hook the hashchange event properly?

### ISSUE THREAD

**Issue by bootrino** [electron/electron#11047]
I have an index.js with the following code, but changing the hash with:

`  window.history.pushState(null, null, '#/goal')`

Does not seem to fire the event.

Can anyone suggest what I am doing wrong?

```
    // Split location into `/` separated parts, then render `Application` with it
    function handleNewHash() {
      var location = window.location.hash.replace(/^#\/?|\/$/g, '').split('/');
      console.log('handleNewHash', location)
      render(
        <Provider store={store}>
          <DudeRouter location={location}></DudeRouter>
        </Provider>,
        document.getElementById('root')
      )
    }
    
    // Handle the initial route and browser navigation events
    handleNewHash()
    window.addEventListener('hashchange', handleNewHash, false);
```

**Comment by bootrino** [comment]
I eventually found this:

https://developer.mozilla.org/en-US/docs/Web/API/History_API

Which says:

Note that pushState() never causes a hashchange event to be fired, even if the new URL differs from the old URL only in its hash.

So I should have been using window.location.hash to change the hash AND get the hashchange event fired.

Sorry for the noise.

**Comment by felixrieseberg** [comment]
> Not an electron thing. Sorry for the noise.

No worries, thanks for coming back and updating the issue!
