### ISSUE TITLE
Disable notification in render process to auto close

### ISSUE THREAD

**Issue by kamrancode** [electron/electron#11046]
Hello
I want to know if is there a way to disable auto close notification in windows
after generating the notification it will close automatically I can't even set any timeout for this function
should I use native windows notification?

thanks

**Comment by kamrancode** [comment]
my electron v1.6.5
and I saw https://developer.mozilla.org/en-US/docs/Web/API/notification/requireInteraction
which should do the work but its not work

**Comment by MarshallOfSound** [comment]
Duplicate https://github.com/electron/electron/issues/9283
