### ISSUE TITLE
Showing browserwindow without taking focus on Windows OS, possible?

### ISSUE THREAD

**Issue by Slapbox** [electron/electron#11049]
I'm trying to make notifications like Google Chrome's in Electron. I've tried setting `focusable: false` but the window still takes focus on `window.show()`

I also tried setting `show: true` and avoiding calling `window.show()` but get the same effects.

I've done quite a bit of research and I can't find anything on this. Is this not currently possible? If not, it would be great to see it added.

**Comment by Slapbox** [comment]
You are correct I overlooked that. Thank you very much.

Unfortunately though this has the exact same effect of a new window stealing focus from my current Electron window, though it does not steal it from non-Electron windows.

**Comment by kschuster1** [comment]
did you ever resolve this - I'm looking to do the same

**Comment by Slapbox** [comment]
I don't remember the _exact_ nature of my issue at the time, but I'm pretty sure this remains an issue in my project even now with Electron >2.0
