### ISSUE TITLE
The drop-down of <select> elements has rendering artifacts on High-DPI Scaling.

### ISSUE THREAD

**Issue by adoriandoran** [electron/electron#11040]
* Electron version: 1.7.9
* Operating system: Windows 10

### Expected behavior

Normally, the drop-down list of a combo box has a border with a constant thickness on all sides.

### Actual behavior

The border of the drop-down list behaves inconsistently according to the window position while High-DPI Scaling is turned on.

As observed in the below screenshots, some sides of the border may become thicker and other may not render at all.

![bug1](https://user-images.githubusercontent.com/7734010/32470227-49cf7330-c35f-11e7-80c9-f8497de42735.png)

![bug2](https://user-images.githubusercontent.com/7734010/32470261-78053da2-c35f-11e7-855b-79788c4cdb99.png)

### How to reproduce

Using a HTML code like below, when the display scaling is above 100%.

```html
<select>
    <option>Apple</option>
    <option>Cherry</option>
    <option>Kiwi</option>
    <option>Pear</option>
</select>
```

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by adorianDoran** [comment]
The issue persists on Electron 4.0.1 too.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
