### ISSUE TITLE
TypeError:  Error processing argument at index 1, conversation failure at 655.2

### ISSUE THREAD

**Issue by karthik-gumpu** [electron/electron#11042]
Hi,
I am getting below issue in the production app.  Unable to debug it.
![issue](https://user-images.githubusercontent.com/20722112/32479364-7741e398-c3af-11e7-86c2-6ab94c43e3b4.png)

**Comment by MarshallOfSound** [comment]
@karthik-gumpu Somewhere in your code you are calling an Electron API like `setSize` or `setPosition` with a number that you calculate yourself.  This number is coming out as a float but the Electron API expects an integer.  You need to find that bit of code and round it 👍

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by karthik-gumpu** [comment]
Thanks @MarshallOfSound . But i no where used such setters in my code base. 
FYI, i am using "electron-notify" package to show notifications. When showing notifications, this issue occurs. May know how to debug it?

**Comment by MarshallOfSound** [comment]
@karthik-gumpu `electron-notify` will be causing this issue, see lines like this one.

https://github.com/hankbao/electron-notify/blob/master/index.js#L237

That have `setPosition` with some calculated value 👍

**Comment by karthik-gumpu** [comment]
Thanks @MarshallOfSound. Its working
