### ISSUE TITLE
Canvas performance has significantly degraded in Electron 1.8 (Chromium 59) on Linux

### ISSUE THREAD

**Issue by Tyriar** [electron/electron#11051]
* Electron version: 1.8.1
* Operating system: Linux

`CanvasRenderingContext2D.drawImage` is extremely slow in Electron 1.8.

### Expected behavior

Under Electron 1.7.9:

![image](https://user-images.githubusercontent.com/2193314/32513853-37c78690-c3b0-11e7-803e-524e0bd65319.png)

### Actual behavior

Under Electron 1.8.1:

![image](https://user-images.githubusercontent.com/2193314/32513783-fde69b46-c3af-11e7-9633-5a541caea4a2.png)

### How to reproduce

Run [xterm.js](https://github.com/xtermjs/xterm.js) using branch `v3` under Electron. The library uses `CanvasRenderingContext2D.drawImage` to draw from a texture atlas stored in an `ImageBitmap` onto a canvas. See https://github.com/xtermjs/xterm.js/blob/a6899c74d838e68bc58fb41f718fd7796b9240b2/src/renderer/BaseRenderLayer.ts#L262

### Notes

I have not observed this in the Chrome (not certain if I tried under v59).

Related:

- Canvas performance problem (chromium bug) https://github.com/electron/electron/issues/9765
- https://crbug.com/464835
- https://crbug.com/683994

**Comment by MarshallOfSound** [comment]
@Tyriar Can you confirm if this happens on the Chromium 61 upgrade branch?

This commit appears to be the "temporary fix" on Chromiums side for your linked bugs but afaics it made it's way into the 59 release.  https://chromium.googlesource.com/chromium/src.git/+/c78b8bf07f4819342ee6d99796100cc62880718b%5E%21/#F0

**Comment by alexeykuzmin** [comment]
https://crbug.com/683994 is tagged as `merge-merged-3071`, it means the changes did get to the `59.0.3071.115` version.

**Comment by Tyriar** [comment]
@MarshallOfSound @alexeykuzmin note that the drawing is a little different to that described in the linked bugs. The linked bugs are saying drawing from "a few large images", my scenario is drawing a lot of small chunks (single character size) from large images.

**Comment by Tyriar** [comment]
Just tested on v1.8.2-beta.2 and the same issue occurs, working on checking chromium 61 branch

**Comment by Tyriar** [comment]
This problem still occurs on `upgrade-to-chromium-61`, it crashes when I open devtools so I can't get a perf timeline.

**Comment by Tyriar** [comment]
This problem definitely does not occur on Chrome 61 or 62 under Linux.

**Comment by Tyriar** [comment]
Perhaps there are differences in build flags used as this is related to GPU rendering?

**Comment by Tyriar** [comment]
The issue can be reproduced with the following repo/branch: https://github.com/Tyriar/electron-quick-start/tree/slow-canvas-issue

It also illustrates another related issue in 1.8 where draws can occasionally break a lot (after clicking on `body`):

![image](https://user-images.githubusercontent.com/2193314/32571024-ea81f16a-c47a-11e7-83cb-364ff154ff06.png)

After trying to select some of the (invisible) text:

![image](https://user-images.githubusercontent.com/2193314/32571117-2cee129a-c47b-11e7-8f73-e8172b266ea8.png)

This particular issue seems to be fixed in the 61 branch which will draw reliably like 1.7.9.

**Comment by lcherone** [comment]
Thanks, @sofianguy - downgrading to `npm install electron@1.7.12 --save` fixed the rendering issue I was having when using `xterm.js` as it uses canvas.

**Comment by sofianguy** [comment]
@Tyriar is this still an issue on electron versions later than 2.0.x?

**Comment by sofianguy** [comment]
@Tyriar we are no longer providing bug fixes for bugs reported on versions earlier than 2.0.x. Feel free to reopen if this bug is still present in later versions of electron.

**Comment by juancampa** [comment]
@sofianguy this popped back up on Electron v4.0.1 (Chromium v69.0.3497.106). I'll open a new issue

**Comment by robatwilliams** [comment]
The aforementioned new issue is #16439
