### ISSUE TITLE
PDF Viewer renders grey screen (PDF content not loaded)

### ISSUE THREAD

**Issue by riyazudheen** [electron/electron#11064]
* Electron version: 1.6.15 / 1.7.9
* Operating system: MacOS Sierra 10.12.6

### Expected behavior
Using the electron's inbuilt PDF viewer by enabling the "plugins".  PDF contents used to rendered properly in the BrowserWindow.

### Actual behavior
BrowserWindows shows grey screen. PDFViewer is loaded (can see some controls like zoom), but content of PDF is not. Console shows error "Not allowed to load local resource: blob:https://localhost:9000/62c8c44b-cf9e-4a70-934f-6c93109b2c0f"

### How to reproduce
In our case, we receive a blob through our API, then we use createObjectURL(blob) to create a blob URL and pass this URL to electron's BrowserWindow to open it.

**Comment by sofianguy** [comment]
Does this issue persist on a later version of Electron, such as 1.8 or 2.0.0?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in the comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
