### ISSUE TITLE
Ethereum Wallet installation

### ISSUE THREAD

**Issue by Pchelinho** [electron/electron#11066]
Hi,

I've tried to install the Ethereum Wallet on my computer, but every time I start the installation it stops and receive an error message saying that instalation stopped because "node.dll" is missing.

Can you help me?

Cheers,
Pedro Ferreira

* Electron version:
* Operating system:

**Comment by MarshallOfSound** [comment]
This isn't an Electronic issue, you should raise this with Ethereum Wallet
