### ISSUE TITLE
PDF Viewer plugin is not loaded in object or embed tag

### ISSUE THREAD

**Issue by csaunier** [electron/electron#11065]
Hello team and users :)

I've got an issue when viewing a pdf. Seems the plugin is not working.

Here are some information :

* Electron version: 1.7.9
* Operating system: linux and mac

### Expected behavior

I can view a pdf

### Actual behavior

I get an error "can not load the plugin"

![electron_without_pdf_plugin](https://user-images.githubusercontent.com/6275571/32551319-6a0e35f0-c490-11e7-8a42-ccdb98888c63.png)

### How to reproduce

I made a simple repo based on the electron-quick-start : https://github.com/csaunier/electron-quick-start
I only add `webPreferences: { plugins: true }` into the config of the `BrowserWindow`, and a pdf into an `object` tag

I'm pretty sur i've seen it working in another real project i'm working on, but obviously, not anymore :)

I've seen some discussion about pdf, like this one https://github.com/electron/electron/pull/10793, but not sur if linked or not.

**Comment by ahmedmohamedali** [comment]
Hi @csaunier,
The PR #10793 fixes the issue for PDF loaded in iframes.
PFDs in Object and embed tags need to be fixed in a different PR.
Could you please make the title of this issue more specific as "PDF Viewer plugin is not loaded in object or embed tag". Thanks.

**Comment by csaunier** [comment]
Hop, done @ahmedmohamedali

**Comment by coderzquest** [comment]
Any update on this issue...I'm facing the same issue on electron version 1.8.2

**Comment by euangordon** [comment]
Any update on this? I am facing the same on election version 2.0.0

**Comment by justintgav** [comment]
Seeing the same on electron v 2.0.2:
Demo shown with the barebones electron-quick-start with the embed tag added. I'd be happy to share a full example, but the screenshot should cut it (contains the bit of code modified).
https://i.imgur.com/GgEKMzX.png
![](https://i.imgur.com/GgEKMzX.png)

This is a library-breaking issue for us; need embed support to wrap [legacy] webapp in electron.

Any insight @ahmedmohamedali ? Even a direction to explore might lead us to a potential workaround.

Thank you!

**Comment by ahmedmohamedali** [comment]
@justintgav,

There is an issue in electron/chromium with embed/object tag when the type is "application/pdf".
I found that object tag and "text/html" type works fine in electron. 
So you can use it as a workaround
<object type="text/html" data="http://www.pdf995.com/samples/pdf.pdf" width="700" height="500">

**Comment by justintgav** [comment]
@ahmedmohamedali excellent, thank you for the information. To clarify: we're waiting on the chromium project to fix the <embed> issue [before it can be propagated to electron]?
Thanks again

**Comment by codebytere** [comment]
This now works, as we ship chromium's PDF viewer natively once more.
