### ISSUE TITLE
Electron error: Segmentation fault node “$basedir/node_modules/electron/cli.js”

### ISSUE THREAD

**Issue by madasionka** [electron/electron#11062]
* Electron version: 1.7.5
* Operating system: Windows 10 Pro

### Expected behavior

The app should run normally and not crash

### Actual behavior

When I start my app, from my terminal with a command `electron .`, around 9 out of 10 times it crashes and with a message:

`/cygdrive/c/Users/Magda/AppData/Roaming/npm/electron: line 14: 16428 Segmentation fault      node "$basedir/node_modules/electron/cli.js" "$@"`

### How to reproduce

My app uses webview module and opens localhost on port 8000. The problem seems to be in redirecting the http requests.

this is my index.html:

    <!DOCTYPE html>
    <html>
       <head>
          <meta charset = "UTF-8">
          <title>Title</title>
       </head>
    
       <body>
          <div>
            <webview id = "foo" src = "http://localhost:8000/" style =
            "position: absolute; top: 0; left: 0; width: 100%; height: 100%; display: inline-flex;">
                <div class = "indicator"></div>
            </webview>
          </div>

          <script type = "text/javascript">
             // Event handlers for loading events.
             // Use these to handle loading screens, transitions, etc
             onload = () => {
                const webview = document.getElementById('foo')
                const indicator = document.querySelector('.indicator')
    
                const loadstart = () => {
                   indicator.innerText = 'loading...'
                }
    
                const loadstop = () => {
                   indicator.innerText = ''
                }
    
                webview.addEventListener('did-start-loading', loadstart)
                webview.addEventListener('did-stop-loading', loadstop)
             }
          </script>
       </body>
    </html>

And what I do in my `main.js` is basically redirecting request for `static` files to local files.

    session.defaultSession.webRequest.onBeforeRequest(filter, (details, callback) => {
        const prefix = "http://localhost:8000/"
        const prefix_https = "https://localhost:8000/"
        const prefix_static = "http://localhost:8000/static/"
        const prefix_https_static = "https://localhost:8000/static/"

        const url = cutQueryString(details.url)

        if (url.indexOf(prefix_static) === 0 && fileExists(url.substr(prefix.length))) {
            const newUrl = 'static://' + url.substr(prefix.length)
            callback({redirectURL: newUrl})
        } else if (url.indexOf(prefix_https_static) === 0 &&
            fileExists(url.substr(prefix_https.length))) {
            const newUrl = 'static://' + url.substr(prefix_https.length)
            callback({redirectURL: newUrl})
        } else {
            callback({cancel: false})
        }
    })

As design of file protocol in chromium doesn't allow to load local resource I used custom protocols as suggested here: https://github.com/electron/electron/issues/9077

This is my `registerHttpProtocol` :

    protocol.registerHttpProtocol('static', (request, callback) => {
        const prefix = "static://"
        const newUrl = 'file://' + __dirname + "/" + request.url.substr(prefix.length)
        callback({url: newUrl})
    }, (error) => {
        if (error) {
            errorLogger.error("Failed to register static files protocol")
        }
    })

I am not sure where lies the problem. The weird part is that it crashes usually but not always (although the run of the application is the same) and with different error codes.

**Comment by felixrieseberg** [comment]
Before we go any deeper, would you mind giving it a try with 1.8.2?

**Comment by madasionka** [comment]
@felixrieseberg  sure! I tried electron@1.8.2-beta.2. What's happening now is that I don't get the error message I would get before, but also it's not working because the application freezes. 

What is confusing for me is that when I run the application three different things can happen:
1. The app crashes almost immediately  from the user point of view, but actually it manages to redirect some requests. It always crashes at the same one although there is nothing special about it I would say. Now with 1.8.2 it seems as it manages to redirect one request more. - Happens around 7/10 times.
2. Welcome page is loaded, crashes when I login in to the application. - Happens around 2/10 times.
3. The app runs smoothly - ~1/10 times - now with 1.8.2 I wasn't able to achive this at all.

**Comment by madasionka** [comment]
Hi, this post was referenced by #11110  and there I read that someone had a similiar issue and that this was working properly on 1.4.16 and I confirm that my app doesn't crash with this electron version.

**Comment by lenovouser** [comment]
I am getting this too, but without redirecting HTTP requests. I only have a few webviews in there.

`line 14: 11028 Segmentation fault      node "$basedir/../electron/cli.js" "$@"`

Windows 10 Pro,
Electron 2.0.5

**Comment by phenomax** [comment]
I can also reproduce this error on my Windows 10 Pro running **Electron 2.0.5**. 
Although the recent improvements of resource freeing and garbage collecting in webviews (#13604) reduced the amount of segfault, the problem still occurs when switching between webviews.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by avisk1** [comment]
Hey I just received this exact error. It happens when I open a <webview> with a specific src. Nothing happens, and when I try webview.goBack() it just crashes and I get this error. There are no errors in the console. This happens both on the packed and unpacked version. Sorry that it's not much to go on.
