### ISSUE TITLE
cannot find globalShortcut module of electron

### ISSUE THREAD

**Issue by bhaktigohel** [electron/electron#11073]
* Electron version: ~1.7.8
* Operating system: linux

I can't register keyboard shortcut .
I get an errror which says that globalShortcut.register() is not  a function ??
actually,I tried to console globalShortcut but got undefined.

Can anybody help..!!!!!!!!!!

**Comment by MarshallOfSound** [comment]
Can you please share the code you are using?  Working code should look something like this

```js
const { globalShortcut } = require('electron')

globalShortcut.register(..... // args here
```

**Comment by bhaktigohel** [comment]
Yes .It is absolutely same as you described!!!

**Comment by MarshallOfSound** [comment]
Oh, @bhaktigohel the [`globalShortcut`](https://github.com/electron/electron/blob/master/docs/api/global-shortcut.md) module can only be used in the main process (as per the `Process:` section of those docs).  You should look into using IPC to send a message from the main process to the renderer process when the global shortcut gets triggered 👍

**Comment by bhaktigohel** [comment]
ty
