### ISSUE TITLE
Websockets and custom URL schemes with port numbers create a blank window

### ISSUE THREAD

**Issue by benlancaster** [electron/electron#11074]
* Electron version: any
* Operating system: any

### Expected behavior

Given I have registered a custom URL scheme (e.g. `httpz`), and I have loaded a URL *with* a port number and my custom scheme, when I create a WebSocket connection then it should succeed

### Actual behavior

Browser window is completely blank (as if about:blank was loaded), developer tools disconnect.

![screen shot 2017-11-09 at 14 30 44](https://user-images.githubusercontent.com/550569/32610412-9cc37062-c55a-11e7-8046-ad6b2574a648.png)

Removing the port number from the loaded URL creates expected behaviour.

### How to reproduce

```bash
git clone git@github.com:benlancaster/electron-ws-custom-scheme.git
npm install
npm start
```

**Comment by sofianguy** [comment]
Can you give electron version 2.0.x or later a try and let us know if this bug is still present?

**Comment by benlancaster** [comment]
I tried a few versions:

 - v2.0.16 - broken
 - v3.1.1 - working correctly
 - v4.0.1 - working correctly 

I've pushed branches with the electron version as the name which reproduce the different states.

Given the age of the bug, it only affects v2, and v2 will reach end of life when v5 is released, I suppose it's not really worth digging any deeper with this

**Comment by sofianguy** [comment]
> Given the age of the bug, it only affects v2, and v2 will reach end of life when v5 is released, I suppose it's not really worth digging any deeper with this

Yes, this is correct. If you can use 3.0.x or 4.0.x that would be the best scenario for you and electron.
