### ISSUE TITLE
The manual is lying about showOpenDialog.

### ISSUE THREAD

**Issue by ElectroMolecule** [electron/electron#11077]
I've wasted countless hours now endlessly searching and asking. The manual is lying. showOpenDialog() DOES NOT return an array of strings and doesn't send it to the callback function either. Whatever it is producing, it's impossible to run .foreach on and is thus not an array.

How to turn whatever it is actually returning into an array of file handlers?!!!

**Comment by MarshallOfSound** [comment]
Hey @ElectroMolecule,

I can't reproduce this issue, here is the code I used to test:

```js
const files = electron.dialog.showOpenDialog({})
console.log('syncronous:', files)

electron.dialog.showOpenDialog({}, (returned) => {
  console.log('callback:', returned)
})
```

This resulted in the following output:
![image](https://user-images.githubusercontent.com/6634592/32647636-5a60eb40-c646-11e7-9d20-6ab85190a82b.png)

As you can see, both outputs are arrays of strings.  Can you please provide the Electron version and sample code you are using so that we can attempt to reproduce this.

**Comment by ElectroMolecule** [comment]
Electron 1.7.9:

```
	var pickedFileNames = dialog.showOpenDialog(
	{
		filters:
		[
			{ name: 'Stuff', extensions: [ 'JPG', 'PNG', 'GIF' ] }
		],
		properties: [ 'multiSelections' ]
	});

	pickedFileNames.foreach(function(fileName)
	{
		console.log(fileName);	
	});
```

	
"Uncaught TypeError: pickedFileNames.foreach is not a function"

But even if it *had* worked, I still don't know how to actually turn that alleged array of strings (it's clearly not?) into an array of "file handles".

**Comment by ElectroMolecule** [comment]
It should be noted that I also have tried it with the callback function with the same result.

**Comment by MarshallOfSound** [comment]
> pickedFileNames.foreach

The function is `forEach` (note the capital E).  If you want to get the contents of each file with your code it would look something like this

```js
const fs = require('fs'); // docs here - https://nodejs.org/api/fs.html

var pickedFileNames = dialog.showOpenDialog({
  filters:
  [
    { name: 'Stuff', extensions: [ 'JPG', 'PNG', 'GIF' ] }
  ],
  properties: [ 'multiSelections' ]
});

pickedFileNames.forEach(function(filePath) {
  const contents = fs.readFileSync(filePath); // contents is a Buffer containing the image file
});
```

**Comment by ElectroMolecule** [comment]
"Solved" it by making an insane workaround...
