### ISSUE TITLE
Dark Themes for macOS title and tab bars?

### ISSUE THREAD

**Issue by ylluminate** [electron/electron#11076]
Is there a way to achieve a dark them similar to how Sublime 3 works? Please note the following comparison images:

Atom:
![atom](https://cl.ly/152H0H3d1L0e/atom.png)

Sublime:
![sublime](https://cl.ly/3y23213k1k1n/sublime.png)

Sublime allows for a dark title bar + tab bar in a very attractive fashion and it would be nice to be able to see this kind of behavior in Atom.

**Comment by zacharyrs** [comment]
@ylluminate 

I suspect that's just the theme you're using with Atom, as mine looks like this.
![screen shot 2017-11-10 at 11 23 10 am](https://user-images.githubusercontent.com/10497077/32632749-a3e0d164-c609-11e7-9bca-bf33dbf262cb.png)

**Comment by ylluminate** [comment]
@zacharyrs interesting, I'd gone through things regarding dark themes on Atom, but none of them seemed to get the title bar and tabs. What are you using?

**Comment by zacharyrs** [comment]
@ylluminate 

PristineUI and Dracula Syntax.

**Comment by ylluminate** [comment]
Thanks again @zacharyrs. Very nice. I've gotten my hands around it now.
