### ISSUE TITLE
Renderer Crash reporter won't trigger when --enable-sandbox option is set

### ISSUE THREAD

**Issue by lepinay** [electron/electron#11072]
* Electron version: 3.0.3 and bellow
* Operating system: windows 10

### Expected behavior

When sandbox is enabled and a native crash happens in a  renderer process it should trigger the Crash reporter and send a report to the specified submit url

### Actual behavior

The crash reporter is not triggered, the report is not sent.

### How to reproduce

The following repo can be cloned: https://github.com/lepinay/CrashReporterSample

#### Configure the submitURL
Update **app.js** and **preload.js** to use your own crash reporter server 

#### Restore modules & run in sandboxed mode
```powershell
cd CrashReporterSample\CrashReporterSample
npm install
node_modules\.bin\electron app.js --enable-sandbox
```

The Menu file contains some helper for testing 
* Trigger a native crash for the main process 
* Create renderer processes with webPreferences.sandbox set to true/false

**Comment by lepinay** [comment]
Quick update on this issue, I've tried investigating

The same code sample work on Mac in sandboxed mode. The only difference is that on Mac we use Crashpad instead of Breakpad. So I suspect there is an issue with the CrashReporter Breakpad implementation on windows.

The issue is also present on Linux (Breakpad)

**Comment by lepinay** [comment]
@sofianguy could you add the tag crashreporter too to the issue ? I think it's missing thanks !

**Comment by nornagon** [comment]
Is this also an issue in 2.0.x?

**Comment by lepinay** [comment]
@nornagon @sofianguy 
Juste reproduced it in 3.0.3.
The behaviour is slightly different, I have the following windows error showing up:

![annotation](https://user-images.githubusercontent.com/2689930/46741974-6707c500-cca6-11e8-88ff-4f65429b68cc.png)

And of course the report is not uploaded.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
