### ISSUE TITLE
Is it possible to rearrange the distribution files in this manner somehow?

### ISSUE THREAD

**Issue by ElectroMolecule** [electron/electron#11089]
(Talking about the Windows version.)

As it is currently, you get program.exe as well as many other files in the same dir. Could this be changed so that the .exe is in the dir by itself, with all the other files and subdirs contained inside a dir called "data" or something? It would really make it much "cleaner" to look at.

Yes, I know about that Virtual something program that allegedly lets you bake them all into a single .exe, but I've tried it out extensively and it has numerous problems associated with it. I don't even expect the user to go to the program dir, but rather use the shortcut icon, but still, it would just "feel better" to me if you could rearrange the files like this. If not, is there a technical reason this was not done right away?

**Comment by lee-dohm** [comment]
Creating a new user account to circumvent a ban is against the [Electron Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md).
