### ISSUE TITLE
node http.server not triggering listening event in a renderer in 1.8.*, but working in 1.7.*

### ISSUE THREAD

**Issue by xaviergonz** [electron/electron#11086]
* Electron version: 1.8.* (including 1.8.2 beta)
* Operating system: Windows 10 x64

### Expected behavior

The http.server listening event should be triggered

### Actual behavior

The event is never triggered

### How to reproduce

Paste the following code inside a renderer console of any electron app and watch the console.
Either listening! or error! should be printed, but they are never triggered.
```
const http = require('http');
const server = http.createServer();
server.once('error', () => {console.log('error!')});
server.once('listening', () => {console.log('listening!')});
server.listen({
        port: 32000,
        exclusive: true,
});
```
The exact same code works in pure node as well as electron 1.7.*

PS: **If the same code is run in the main process instead of the renderer one it works.**

**Comment by xaviergonz** [comment]
Also most probably this issue also happens on other OSes but I don't have any of those to try.

**Comment by xaviergonz** [comment]
This is still happening on the stable release of 1.8

**Comment by xaviergonz** [comment]
Still happening as of electron 2.0 beta 1

**Comment by xaviergonz** [comment]
Just FYI, the same code also works on the latest version of NW.js (Chromium 64 + Node 9.6.1), so the introduced bug seems not to be related to the new v8 / node version.

**Comment by xaviergonz** [comment]
I just noticed that if the code is then followed by either ```process.nextTick(() => {})``` or ```setImmediate(() => {})``` in the renderer process console then the events are emitted, so it seems to be an issue with the node event loop being stuck or something.

**Comment by serverwentdown** [comment]
I have this issue too in 2.0.4.

**Comment by brownbl1** [comment]
I also have this issue.

**Comment by mingyuan-xia** [comment]
confirmed still existing on Ubuntu 16, electron 4.x,  though the `setInterval` and then `setImmediate` trick does work around...

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
