### ISSUE TITLE
When I use ffi or ref library in electron's web worker, I get an error: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by Zane0816** [electron/electron#11080]
When I use node-ffi or ref library in electron's web worker, I get an error: Path must be a string. Received undefined
I use webpack and worker-loader

* Electron version:1.7.9
* Operating system:windows 10
* webpack:3.8.1
* worker-loader:1.1.0

**Comment by MarshallOfSound** [comment]
>  I use webpack and worker-loader

This is almost certainly your problem, webpack messes with things like `__dirname` and `__filename` so there is probably a `path.resolve()` somewhere using one of those constants (that's where the error comes from)

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by Zane0816** [comment]
Now I'm not using webpack and worker-loader, but there's a new error: Can not find module 'ffi'

**Comment by Zane0816** [comment]
Ok, now I found a way to load the ffi library
`module.paths.push(__dirname.substr(0, __dirname.indexOf('\\node_modules\\')) + '/node_modules')`
