### ISSUE TITLE
BrowserWindow incorrect size when DPI awareness is turned off (Windows 10)

### ISSUE THREAD

**Issue by somtwo** [electron/electron#11096]
I'm experiencing an issue with the window size begin incorrect when DPI awareness is disabled. I am using `useContentSize: true` when creating the window.

* Electron version: 1.7.9 and 1.8.2-beta.2
* Operating system: Windows 10

### How to reproduce

```
$ git clone https://github.com/somtwo/electron-quick-start master
$ npm install
$ npm start
```

You can see the canvas element via the debug window which is the correct size and you can see the extra 20 px at the bottom.

Notes:
- This only happens for framed windows.
- Calling `mainWindow.setSize(800, 600)` after creating the window results in a different (incorrect) size

Edit: Other notes:
- I have two monitors both running at 2560x1440 resolution 
- This bug happens at both 100% and 125% scaling

**Comment by felixrieseberg** [comment]
Thanks for reporting! We do have all kinds of issues right now: https://github.com/electron/electron/issues/10862

**Comment by somtwo** [comment]
After further investigation, I realized I was setting the menu to null after opening the window, and the menu is exactly 20 pixels tall in windows 10. This may not be a bug in the BrowserWindow constructor, but I think there is still a bug in BrowserWindow.setSize as the size is still incorrect after calling it.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
