### ISSUE TITLE
click() event of MenuItem doesn't have the right context

### ISSUE THREAD

**Issue by nj-neer** [electron/electron#11095]
* Electron version: **1.7.9**
* Operating system: **Windows**

### Expected behavior

When calling the **click()** event of a **MenuItem** built within a **for** loop , it should keep the values given with this same loop :

```js
let list = ["toto", "tata", "titi"];
for (var i = 0; i < list.length; i++) {
    testMenu.append(new MenuItem({
        label: list[i],
        click: function(){
            console.log(list[i]); // <== Should be the same as the label
        }
    }));
}
```

### Actual behavior

<img src="https://i.imgur.com/3ElkRgb.png"> 

<img src="https://i.imgur.com/DFKKszk.png">

### How to reproduce
Example repo available here :

https://github.com/nj-neer/test-bug-electron-menuItem

**Comment by nj-neer** [comment]
Result with :

```js
click: function(){
    console.log(i);
}
```

![image](https://user-images.githubusercontent.com/9463585/32693867-7d88f198-c732-11e7-96e1-d86571ed067c.png)

🤔

**Comment by enlight** [comment]
That's just how JS works, if you have difficulty figuring this out perhaps try asking on StackOverflow.
