### ISSUE TITLE
Compatibility with Vuejs

### ISSUE THREAD

**Issue by Paradygmus** [electron/electron#11090]
* Electron version: 1.7.9
* Operating system: Windows 10

### Expected behavior

Vuejs can include the getters and setters that are given by electron to be able to refresh the variable at the right time and update in the main process at the same time.

### Actual behavior

The getters/setters are configurable false, so Vuejs can't override it.

### How to reproduce

Reproduction link

[https://github.com/Paradygmus/vue-electron-problem](https://github.com/Paradygmus/vue-electron-problem)

Steps to reproduce

1. npm install
2. npm start
3. Click on the 2 link and watch the diff.

Condition: You need to have an object from the main process

Relative to this issue : [https://github.com/vuejs/vue/issues/6990](https://github.com/vuejs/vue/issues/6990)

### How to fix

1. remove `descriptor.configurable = true` at line 133 in *electron\dist\resources\titi\renderer\api\remote.js*
2. change `let descriptor = { enumerable: member.enumerable }` to `let descriptor = { enumerable: member.enumerable, configurable: true }` at line 108 still in *electron\dist\resources\titi\renderer\api\remote.js*

**Comment by MarshallOfSound** [comment]
The current `configurable` value is accurate, the remote proxy does not allow deleting properties and any modifications to the property descriptor are not proxied to the main process.  Thus `configurable: false` is correct and changing it will result in unexpected behavior.

The fix for this would appear to be on vues side if they are misinterpreting `configurable: false`

**Comment by Paradygmus** [comment]
Why the remote proxy can't allow that ? What kind of unexpected behavior ? 

The only problem is just if a script on the rendered side deletes get and set. 
But it's not electron fault but the programmer, no?

Vuejs can't override the get / set to handle the *object modification from the render process* because getters / setters are `configurable: false`. 

In *renderer/api/render.js* : 
If `member.type === 'method'` (*l:109*), electron set `configurable: true`(*l:133*) so, why for it but not for getters / setters ?

**Comment by MarshallOfSound** [comment]
@Paradygmus I believe both I and @paulcbetts explained this fully in the Electron slack.  If not feel free to continue asking questions there, but the current behavior is correct.
