### ISSUE TITLE
Unable to create a symlink from Electron on Windows

### ISSUE THREAD

**Issue by Siilwyn** [electron/electron#11094]
* Electron version: 1.7.8
* Operating system: Windows 10

### Expected behavior
Create a symlink successfully, like on Linux where it does work.

### Actual behavior
Permission error is returned on creating a symlink:
```js
{
  Error: EPERM: operation not permitted, symlink 'package.json' -> 'C:\...\project\yes'
  errno: -4048,
  code: 'EPERM',
  syscall: 'symlink',
  path: 'package.json',
  dest: 'C:\...\project\yes'
}
```

### How to reproduce
Run the following snippet under electron, note that running it directly with node does work.
```js
const fs = require('fs');

fs.symlink('package.json', 'yes', console.log);
```
**Alternatively** run the following:
```
git clone https://github.com/Siilwyn/electron-symlink/
cd electron-symlink
npm install
npm start
```

**Comment by Siilwyn** [comment]
Ugly workaround that is not cross-platform:
```js
const exec = require('child_process').exec;

exec('mklink yes package.json', (error, stdout, stderr) => {
  if (error) {
    console.error(`exec error: ${error}`);
    return;
  }
  console.log(`stdout: ${stdout}`);
  console.log(`stderr: ${stderr}`);
});
```

**Comment by CGJennings** [comment]
On Windows I think you can only create hard links and directory junctions without special privileges (e.g. running with Run as Administrator). Can you use fs.link() for what you want?

**Comment by Siilwyn** [comment]
No, I do need symlinks. The special privileges are only needed on older Windows versions I think, otherwise the workaround would not work, right?

**Comment by CGJennings** [comment]
The Windows 10 Creators Update supposesly lets you make symlinks from the command line *if* you have enabled developer mode.

**Comment by CGJennings** [comment]
I found a Windows blog entry that explains in more detail. For the developer mode workaround, you need to add a specific flag to the system call. The mklink command uses this flag; the Node call presumably doesn't, at least not the build your version of Electron uses. This would explain why your workaround works. At any rate, it looks like thus is not an Electron issue.

https://www.google.ca/amp/s/blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10/amp/

**Comment by Siilwyn** [comment]
I see, thanks for digging into it @CGJennings. As there is still a difference between vanilla Node.js and Electron I would like to keep this issue open however the priority on this can be very low as it is only useful if developer mode is enabled. I will be use hard links (`fs.link`) as a fallback.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.
