### ISSUE TITLE
Electron app becomes white screen after running for half day or longer

### ISSUE THREAD

**Issue by bobbercheng** [electron/electron#11102]
* Electron version: 1.7.9
* Operating system: Win7, Win8, Win10, Mac

### Expected behavior

We have Electron app that often becomes white screen after running half a day or longer. The app shows UI with webpage/webRTC and javascript running in render process. Javascript in render process calls method in main process or Electron API via IPC. When render process becomes white screen, main process is still running well.

Same webpage/webRTC and javascript is running in Chrome for long time without becoming white screen.

### How to reproduce

Here is render process dump file when render process becomes white on 64bit Win7.

https://drive.google.com/open?id=19ZjTMLiNDpgVphbhpamAqnNuGlJa3qbo

We like to know why/what causes render process becomes white screen. 
With visual studio 2015, the call stack is
![image](https://user-images.githubusercontent.com/32662337/32709896-0d5529c6-c86f-11e7-9302-378f7ef03ed8.png)

Could you please help check it?

**Comment by FindDream** [comment]
mainWindow.webContents.on('crashed', function () {
    mainWindow.reload()
  })

**Comment by yosefsun** [comment]
> mainWindow.webContents.on('crashed', function () {
> mainWindow.reload()
> })

Did this fix the issue?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
