### ISSUE TITLE
preventDefault() in render thread will also cause propagation to stop

### ISSUE THREAD

**Issue by mathiasjakobsen** [electron/electron#11116]
* Electron version: 1.7.9
* Operating system: macOS Sierra 10.12.6

### Expected behavior

If I add an event listener to `window` in the render thread, like so:
```js
window.addEventListener('keydown', (event) => {
  event.preventDefault()
}, true) // or "false" for that matter..
```
I would expect the `click` function of a `MenuItem` with a <kbd>space</kbd> accelerator to be fired.

### Actual behavior

If the listener is added, the `preventDefault` call seems to stop propagation as well as any further execution. 

### Why it's a problem?
What I'm trying to do, is having a `MenuItem` with a <kbd>Space</kbd> accelerator. It works fine, but if my `BrowserWindow` content overflows, then hitting <kbd>Space</kbd> will cause the window to scroll. This also applies to keys <kbd>&uarr;</kbd> & <kbd>&darr;</kbd>.

I think it's a Chromium thing, since that if I add breakpoints on every single kind of events in the DevTools, not a single breakpoint is reached when hitting <kbd>Space</kbd>.

### How to reproduce

Please refer to my reproduction branch.
```bash
  $ git clone -b event-propagation-problem --single-branch https://github.com/mathiasjakobsen/keyboard-event-propagation-problem
  $ yarn install
  $ yarn run dev
```
Hitting <kbd>Space</kbd> will show how the main thread console will **not** print a log message, as it should.

**Comment by felixrieseberg** [comment]
Do you see any difference to how your code behaves in Chromium? I'm asking because it's unlikely that it does, and if it doesn't, it's unlikely that Electron will be able to fix it 😉

**Comment by mathiasjakobsen** [comment]
@felixrieseberg No, I don't. But if I run an app in Chromium I only have to think about the render thread. My problem is, that I cant stop the event from propagating **from** the main thread, to the render thread 🚶

**Comment by codebytere** [comment]
I'm in agreement with @felixrieseberg in that this is an upstream issue inherited by Electron, so we're unable to directly address this problem. If there surfaces a way that we can potentially address this we can reopen this issue, but for now i'm going to go ahead and close this.

**Comment by patrickhulce** [comment]
For anyone else that also runs into this issue after a long and unfruitful Google search, my hacky workaround was to make sure I trigger the corresponding menu item manually whenever I `preventDefault`. For my use case, that just meant one single global event listener and using the `toKeyEvent` from the awesome [keyboardevent-from-electron-accelerator](https://github.com/parro-it/keyboardevent-from-electron-accelerator) package.

It's rather limited, but it worked for my use case on preventing arrow keypresses from triggering scroll.

```js
  document.addEventListener('keydown', evt => {
    if (!menuTemplate) return

    for (const item of menuTemplate) {
      if (!item.accelerator || !item.click || item.enabled === false) continue

      const keyEvent = _.omit(toKeyEvent(item.accelerator), 'key') // omit 'key' because it's already covered by the more standardized `keyCode`
      const keyEventKeys = Object.keys(keyEvent)
      const allMatch = keyEventKeys.every(key => keyEvent[key] === evt[key])
      if (!allMatch) continue

      const fakeClickArgs = {}
      item.click(fakeClickArgs, fakeClickArgs, fakeClickArgs)
      evt.preventDefault()
    }
  })
```
