### ISSUE TITLE
Cant stick app to desktop

### ISSUE THREAD

**Issue by vaidyaanand** [electron/electron#11114]
I want to stick my app to desktop. I know the option of `alwaysOnTop ` but is there anything we can do to make the app at always on the bottom?

It is not a bug. But it is a feature request
* Electron version:
* Operating system:

**Comment by felixrieseberg** [comment]
This is only possible on Linux and macOS. Please see the `type` property of the `BrowserWindow`:

https://github.com/electron/electron/blob/bf42426acc927601330f922fd030dc0a2574969c/docs/api/browser-window.md

**Comment by vaidyaanand** [comment]
Thank you for providing the references. I have seen the `type` property but there is nothing much to do for windows system.
