### ISSUE TITLE
Incomplete `getBoundingClientRect()`

### ISSUE THREAD

**Issue by kysely** [electron/electron#11118]
* Electron version: 1.7.9
* Operating system: macOS, Windows

### Expected behavior
`Element.getBoundingClientRect()` should return 8 properties.

### Actual behavior
`Element.getBoundingClientRect()` returns **only 6 properties, with `x` and `y` missing**. Although you can use `left` and `top` respectively instead, this causes unnecessary debugging.

![getboundingclientrect](https://user-images.githubusercontent.com/23558634/32803050-915bcbc6-c982-11e7-820d-5d537816230b.png)

### How to reproduce
Go to any webpage, choose any Element and try calling `getBoundingClientRect()` on it. Do so in both Electron renderer process and any browser. While browsers will include `x` and `y` keys, Electron won't.

**Comment by akaleeroy** [comment]
Why was it closed? Where's the info?

**Comment by kysely** [comment]
If I remember correctly, I closed this as I found that `getBoundingClientRect()` *can* return different number of arguments on different interpreters.

**Comment by bryan-lunt** [comment]
When I use this, it returns no properties whatsoever. The element I clicked on definitely exists...
