### ISSUE TITLE
Electron BrowserWindow and UMD factory

### ISSUE THREAD

**Issue by tleunen** [electron/electron#11111]
* Electron version: 1.8.2 beta 2
* Operating system: OSX

### Expected behavior

UMD factory should work as expected when loaded inside a browser window.

### Actual behavior

The UMD factory script fails, with or without the flag `nodeIntegration`

### How to reproduce

Load an html page which contains a script tag loading a javascript file in which you have this:
```js
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
	typeof define === 'function' && define.amd ? define(factory) :
	(global.something = factory());
}(this, (function () {
}));
```

With or without `nodeIntegration`, the thing that gets executed is `global.something = factory()`.
This fails because `global = this`, but `this` is undefined. In a normal browser, `this = window`, but in Electron, `this` is undefined.

Am I doing something wrong? I'm trying to load an existing web app inside electron as a BrowserWindow, but it fails loading a specific files with a bunch of dependencies because of things like this.

**Comment by MarshallOfSound** [comment]
>  but in Electron, this is undefined.

`this` can't be undefined, I tested this with `nodeIntegration` enabled and disabled and both times `this === window`

Can you provide a minimal sample application that demonstrates this issue.

**Comment by tleunen** [comment]
@MarshallOfSound Could you try this? https://github.com/tleunen/electron-11111
Could it be an issue with electron-forge then?

When running `yarn start`, you'll see the error in the console.

**Comment by kwonoj** [comment]
I think this is electron-compile side issue (in electron-forge)

check compiled `libs.js`:

![image](https://user-images.githubusercontent.com/1210596/32822147-f351a892-c98b-11e7-9a0f-d468f9589c4b.png)

somehow context `this` is statically compiled into `undefined`, Replacing electron-prebuilt-compile into bare electron and run same code retains proper context `this`.

**Comment by codebytere** [comment]
@kwonoj if that is the case, this is no longer the best place for this issue to be resolved. Feel free to report this issue over in the userland [repo](https://github.com/electron-userland/electron-prebuilt-compile) for electron-prebuilt-compile, and i'm going to close this issue.
