### ISSUE TITLE
Electron Mini Summit

### ISSUE THREAD

**Issue by groundwater** [electron/electron#11120]
> tl;dr Prague, June 5-8, invite-only mini summit for electron maintainers

Hi all 👋 

Twice a year, the Electron team hosts a mini-summit for core maintainers. This is planning-oriented event, not a conference with talks or presentations. The Electron project is distributed, and these biannual summits are often the only time my team, and other maintainers see each other face-to-face.

Originally this was a GitHub-only event, but the last two summits have been expanded to include core maintainers at other organizations, as well as select community members. We believe these have worked well, and each summit we look to slowly expand the reach to a wider audience. Our selection process has previously been very organic. You had to know someone, or be in contact with the team. This worked well for including anyone doing core work, but not so well for including folks working on tooling, community, services, apps, and upstream projects like node.

We want to expand the reach, but within a level we're comfortable with for now.

I'd like to solicit interest from folks attending [node summit](https://github.com/nodejs/summit/issues/56#issuecomment-344387720) because our mini-summit is close in time and space. We intend to host the summit in Prague, June 5-8. If you'd like to coordinate, **please let us know here**.

The event also happens to coincide near to [JSConf eu](https://2018.jsconf.eu). Prague and Berlin are within what I'm told is a very pleasant drive of each other.

We also welcome any interest from the broader community. Who gets to attend will really depend on  how many people are interested in coming. If the number is under 40, we can probably accommodate everyone. If over 100 people express interest, we will have to apply some yet-to-be-determined selection criteria.

Please remember that _all_ Electron spaces, events, forums, repos, slacks-groups, and community meetups are governed by our [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md). This includes the mini-summit, and any group events attached to it.

_Anyone who has already attended a previous summit does not need to express interest here._

Cheers 🥂

**Comment by bnoordhuis** [comment]
@groundwater I could be persuaded to come to Prague.  What's on the agenda?

**Comment by groundwater** [comment]
@bnoordhuis we use the summit to plan our next 6-months of priorities - the format is generally _unconf_ style, but everything is facilitated. A top output item from the last summit was our new versioning policy https://github.com/electron/electron/pull/11032

**Comment by bnoordhuis** [comment]
@groundwater Sorry, let me phrase that differently: what's on the table that would benefit from input from node.js people?

**Comment by groundwater** [comment]
Hey @bnoordhuis in short, _everything is on the table_. The style of our mini-summits is an unconf style, and the exact schedule is always determined on the first day. In short, if there is a topic you would like to address, it can likely be added to the schedule. Folks typically come with a list of problems, ideas, and topics they'd like to discuss.

Alternatively, if your question is about whether we'd benefit from having direct node expertise present, I can definitely put this question to our maintainers.

**Comment by bnoordhuis** [comment]
> if your question is about whether we'd benefit from having direct node expertise present, I can definitely put this question to our maintainers

That's my question, yes. =)

**Comment by MylesBorins** [comment]
o/ Very interested in attending!

**Comment by groundwater** [comment]
I've put our site live under *register interest* mode:

https://ti.to/github-electron/electron-2018-prague

We have to finalize some event details before issuing actual tickets. Tickets have no charge, and if we're below capacity anyone is welcome. If we go above capacity... we will probably have folks duel in a pinball tournament, or something. I'll figure it out.

cc @MylesBorins @bnoordhuis @dshaw

**Comment by inexorabletash** [comment]
What's the current status of registration? The page currently shows only remote attendees - did the event fill up? Where do we show up to duel for spots?

**Comment by groundwater** [comment]
@inexorabletash The updated link is here: https://ti.to/github-electron/electron-2018-prague/with/kdyzscbxqc4
