### ISSUE TITLE
Opened windows will be closed when the opener window closes.

### ISSUE THREAD

**Issue by markleutloff** [electron/electron#11128]
* Electron version: 1.7.5, 1.7.9
* Operating system: Windows 10 x64, Windows 7 x86

### Expected behavior

Opened windows will remain open when closing the opener window.

### Actual behavior

Opened windows will automatically close when the opener window is closed.

### How to reproduce

1. Open an electron instance with a BrowserWindow (window A).
2. Navigate to https://www.w3schools.com/jsref/met_win_open.asp (or similar pages)
3. Open a new window (window B) by clicking the "Try It Yourself" button.
4. Open a new window (window C) by clicking the "Try It" button in Window B.
4. Close window B (opener window of window C)
Result: Window C closes.

This only closes the opened windows (and the opened windows in the opened window, eg.) when closing the opener window. All other windows remain unaffected:

Closing window A results in the closing of window B and window C.

**Comment by markleutloff** [comment]
A small update to this issue, which is still present in the Electron version v1.8.4:

When the opener window navigates to an other URL, the opened window will also close. So the same behaviour which occours when closing the opener window is the same when navigating to another site in the opener window.

**Comment by markleutloff** [comment]
I have found a workaround.

How I found it:
In the guest-window-manager.js file (https://github.com/electron/electron/blame/master/lib/browser/guest-window-manager.js) at the setupGuest function, an event handler to the event "render-view-deleted" will be bound to the opening window.

Workaround:
Remove the "render-view-deleted" event handler from the opening window after I completed my "new-window" event handler.

I am not sure if this still is a bug then as it was done on purpose.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by markleutloff** [comment]
Hi there,

I tested it with ElectronFiddle and with that the following versions of Electron:
4.0.1
3.0.9
2.0.7

Reproduction is the same as in the starting post.

**Comment by wslx520** [comment]
Electron version: 3.0.9
Operating system: Windows 10 x64, Windows 7 x86

same. 
1. open app, loadURL a website in the main window
2. click links on the web page, open several new windows
3. use “**reload**” menu on the main window
4. all opened child windows were closed

hope can solve it.

**Comment by markleutloff** [comment]
This problem is still present with electron 5.0.0.

**Comment by t57ser** [comment]
Also happening in electron 7.1.0

**Comment by t57ser** [comment]
The workaround that @markleutloff found seems to be working.
I am doing this for electron 6.1.0:
```
event.newGuest = newWindow;
setTimeout(() => {
	event.sender.removeAllListeners("current-render-view-deleted");
}, 0);
```
This will throw an error though "Object has been destroyed" when the guest-window-manager.js gets to the closedByUser function trying to call `embedder._sendInternal`. I am ignoring this error via
`process.on("uncaughtException",`

Fixing this should be easy by changing the `setupGuest` function to:
```
const setupGuest = function (embedder, frameName, guest, options) {
  const guestId = guest.webContents.id
  if (frameName) {
    frameToGuest.set(frameName, guest)
    guest.frameName = frameName
    guest.once('closed', function () {
      frameToGuest.delete(frameName)
    })
  }
  return guestId
}
```
There is a comment in the function saying:
>When |embedder| is destroyed we should also destroy attached guest

I do not see why this is necessary. I have also not noticed any memory leak issues with the workaround so far.

**Comment by zcbenz** [comment]
This is expected behavior in Electron, and it has been in Electron since when `window.open` was supported. But it is probably worth discussing whether we should have this behavior at all, so I'm keeping this issue open.

**Comment by t57ser** [comment]
In my opinion there are 2 major arguments against this behavior:
- Does not conform to standard browser behavior
- Is not controllable. Meaning if it were the other way around so that it would not automatically close, devs can still manually handle this behavior but by having it be part of electron it is not possible to workaround this and the above change must be made which is not only a hack but can also break between electron versions.
It would be good to know why this was implemented in the first place, as it is going against browser behavior. So if this was specifically done to be electron behavior, my question would be: why?

**Comment by zcbenz** [comment]
Electron was originally written for text editor apps, so this behavior was introduced to cleanup child windows automatically.

I agree we should at least have a way to turn this off. And in the long term we should also follow the standard behavior

**Comment by t57ser** [comment]
Ah yes, it used to be Atom, that makes sense. Thanks for the clarification

**Comment by cuixiping** [comment]
I create a new BrowserWindow instead and prevent the new-window event. So that the opened windows will not be destoryed when opener is closed.

```
win.webContents.on('new-window', (evt, url, frameName, disposition, options) => {
	if (disposition == 'save-to-disk') {
		return;
	}
	evt.preventDefault();
	const newWin = new BrowserWindow({
		// ....... 
	});
})
```

**Comment by t57ser** [comment]
With the new setWindowOpenHandler functionality it should be easy to make this configurable without introducing a breaking change. For example:
```
browserWindow.webContents.setWindowOpenHandler(() => {
		return {
			action: "allow",
			closeWithOpener: false,
			overrideBrowserWindowOptions: undefined,
		};
	});
```
this property can then be passed to openGuestWindow ->  handleWindowLifecycleEvents and simply enable/disable the functionality
