### ISSUE TITLE
Cannot break on breakpoints set on code where app is initialized

### ISSUE THREAD

**Issue by BSoD-Ultimate** [electron/electron#11121]
- Electron version: 1.8.2.beta2

I'm developing a custom own native node-module for Electron. A debug build of Electron/libcc was built from source before for convenience of debugging the native module. The module needs to be used during initialization of the application. 
Now the entry JS file(main.js) encountered an error after calling my node module's function, so debugging JS in the main process is needed. Soon I found all breakpoints on the code **where program going to initialize** was missed after following instructions on the official webpage.

Here is my entry JS file:(modified from main.js in the doc docs/tutorial/quick-start)

```javascript
const {app, BrowserWindow, Menu} = require('electron')
const path = require('path')
const url = require('url')

let hello = require('my-node-module'); // I want to set a breakpoint here.
hello.my_c_function();

let win

function createWindow () {
  win = new BrowserWindow({width: 800, height: 600})
  win.loadURL(url.format({
    pathname: path.join(__dirname, 'index.html'),
    protocol: 'file:',
    slashes: true
  }))
  win.on('closed', () => {
    win = null
  })
}
app.on('ready', createWindow)

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  if (win === null) {
    createWindow()
  }
})

```
The version of debug build of Electron I built is 1.8.2.beta2.
To debug the file, I tried the following ways; unfortunately, they all failed to interrupt on the breakpoint:
- Start Electron.exe adding the argument `--inspect=<port>` then use chrome://inspect to connect Electron process.
- Start Electron with the argument `--inspect-brk=<port>` then connect the process. Electron indeed was interrupted from execution after starting with the added argument. When connected to the debug port(using chrome://inspect), The script still continued execution and the breakpoint was missed.

I also tried to use Visual Studio Code to debug the JS file using 'Node.js Attach' and 'Node.js Electron Main' configuration. Both of them missed the breakpoint and script keep running then encountered the error I have to debug.
Release build of ~~Electron 1.7.9 and~~ 1.8.2.beta2 downloaded from GitHub got the same result after performing the same step above.

Is there anything wrong I did or is there any way to debug the js code where the application is going to be initialized?

UPDATE: I tried again, and Electron 1.7.9 can be debugged as usual through Visual Studio Code. The debug interface seems to be changed since version 1.7.9.

**Comment by BSoD-Ultimate** [comment]
I tried again and confirmed Electron 1.7.9 could be debugged through Visual Studio Code. The debug interface seems to be changed since version 1.7.9.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
