### ISSUE TITLE
remote.getCurrentWindow() returns null in a BrowserView

### ISSUE THREAD

**Issue by RyanZim** [electron/electron#11132]
* Electron version: 1.6.15
* Operating system: Linux

### Expected behavior

Inside a `BrowserView`, I want to access the [`view.id`](https://github.com/electron/electron/blob/master/docs/api/browser-view.md#viewid-experimental). I would have expected `remote.getCurrentWindow()` to return the `view`.

### Actual behavior

Calling `remote.getCurrentWindow()` returns `null`.

---

I understand if you want to expose a different API here since the method _is_ called <code>getCurrent**Window**()</code>. However, there should be _some_ way to access the `view` from within a `BrowserView` process.

**Comment by felixrieseberg** [comment]
I think the core here is a fair request - I'm not sure that I'd put it on `remote.getCurrentWindow()`, but we'll find something.

**Comment by felixrieseberg** [comment]
I think #11225 closed this appropriately. Let us know if it didn't!

**Comment by shenlanchenwei** [comment]
WebView getCurrentWindow() empty, other normal

**Comment by grozdanovgg** [comment]
The problem with `remote.getCurrentWindow()` returning `null` still exists in 4.1.4 - as we discussed in this linked issue [https://github.com/electron/electron/issues/16558].
