### ISSUE TITLE
devtools can't console error

### ISSUE THREAD

**Issue by keyiis** [electron/electron#11136]
* Electron version:1.7.5
* Operating system:win10 x64
I used devtools debug electron app(angular4),it show error's count,but not show detail,i already remove filter,but still not show error detail.

![-1](https://user-images.githubusercontent.com/7766085/32881227-822f3592-caeb-11e7-90de-f2438a80069b.jpg)

**Comment by felixrieseberg** [comment]
You're filtering console messages, only displaying `info` statements. Remove the filter.

![32881227-822f3592-caeb-11e7-90de-f2438a80069b](https://user-images.githubusercontent.com/1426799/32907371-9fe7efca-cab4-11e7-9a81-ea845862cbeb.jpg)

**Comment by keyiis** [comment]
@felixrieseberg Don't close, I tried verbose warnings errors,but no effect.
![1](https://user-images.githubusercontent.com/7766085/32943849-7dc9de20-cbc8-11e7-8a79-5e2d09437496.png)

**Comment by MarshallOfSound** [comment]
@keyiis You have 3 errors and 3 items hidden by filters, you're still filtering out your error messages 👍

**Comment by keyiis** [comment]
@felixrieseberg But how to remove all filter?
![1](https://user-images.githubusercontent.com/7766085/32951440-da4dc37a-cbe4-11e7-9c5e-e35c10e938a4.png)
