### ISSUE TITLE
window blinks black every time I change the size

### ISSUE THREAD

**Issue by miyakedev** [electron/electron#11142]
My whole window is blinking from a black background when I change the size of my window, any solution to avoid this?

I'm using frame: false like github app

* Electron version: last from npm
* Operating system: windows 7

```
const electron = require('electron')
const {app, BrowserWindow} = electron

const path = require('path')
const url  = require('url')

let win

function createWindow() {
    win = new BrowserWindow({
        width: 212,
        height: 669,
        minWidth: 164,
        minHeight : 91,
        resizable : true,
        minimizable : true,
        maximizable : false,
        closable : true,
        fullscreenable : false,
        frame : false
    })
    win.loadURL(url.format({
        pathname: path.join(__dirname, './html/app.html'),
        protocol: 'file',
        slashes: true
    }))
    //win.webContents.openDevTools()
}

app.on('ready', createWindow)
```

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
