### ISSUE TITLE
Overtop 1.6.5 cannot，rebuild ？

### ISSUE THREAD

**Issue by iunfire** [electron/electron#11148]
* Electron version: 1.7.9
* Operating system: window 10

### Expected behavior
when I use "printer" package, and I saw the docs, should use electron-rebuild rebuild the node module.
but, in any, I rebuild there will happen, the error

### Actual behavior
D:\Zone-Code\airfot\airfot-webkit>electron-rebuild --force                                              
× Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@7.9.0 | win32 | x64
gyp http GET https://atom.io/download/electron/v1.7.9/iojs-v1.7.9.tar.gz
gyp http 200 https://atom.io/download/electron/v1.7.9/iojs-v1.7.9.tar.gz
gyp http GET https://atom.io/download/electron/v1.7.9/SHASUMS256.txt
gyp http GET https://atom.io/download/electron/v1.7.9/win-x86/iojs.lib
gyp http GET https://atom.io/download/electron/v1.7.9/win-x64/iojs.lib
gyp http 200 https://atom.io/download/electron/v1.7.9/win-x64/iojs.lib
gyp http 200 https://atom.io/download/electron/v1.7.9/SHASUMS256.txt
gyp http 200 https://atom.io/download/electron/v1.7.9/win-x86/iojs.lib
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:1050:11)
gyp ERR! stack     at TLSWrap.onread (net.js:581:26)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "d:\\apps\\nodejs\\node.exe" "d:\\apps\\nvm\\v7.9.0\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\bin
\\node-gyp.js" "rebuild" "--target=1.7.9" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd D:\Zone-Code\airfot\airfot-webkit\node_modules\printer
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@7.9.0 | win32 | x64
gyp http GET https://atom.io/download/electron/v1.7.9/iojs-v1.7.9.tar.gz
gyp http 200 https://atom.io/download/electron/v1.7.9/iojs-v1.7.9.tar.gz
gyp http GET https://atom.io/download/electron/v1.7.9/SHASUMS256.txt
gyp http GET https://atom.io/download/electron/v1.7.9/win-x86/iojs.lib
gyp http GET https://atom.io/download/electron/v1.7.9/win-x64/iojs.lib
gyp http 200 https://atom.io/download/electron/v1.7.9/win-x64/iojs.lib
gyp http 200 https://atom.io/download/electron/v1.7.9/SHASUMS256.txt
gyp http 200 https://atom.io/download/electron/v1.7.9/win-x86/iojs.lib
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at exports._errnoException (util.js:1050:11)
gyp ERR! stack     at TLSWrap.onread (net.js:581:26)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "d:\\apps\\nodejs\\node.exe" "d:\\apps\\nvm\\v7.9.0\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\bin
\\node-gyp.js" "rebuild" "--target=1.7.9" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd D:\Zone-Code\airfot\airfot-webkit\node_modules\printer
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (d:\apps\nvm\v7.9.0\node_modules\electron-rebuild\node_modules\spawn-rx\lib\src\index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (d:\apps\nvm\v7.9.0\node_modules\electron-rebuild\node_modules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.error (d:\apps\nvm\v7.9.0\node_modules\electron-rebuild\node_modules\rxjs\Subscriber.js:197:26)
    at Subscriber._error (d:\apps\nvm\v7.9.0\node_modules\electron-rebuild\node_modules\rxjs\Subscriber.js:128:26)
    at Subscriber.error (d:\apps\nvm\v7.9.0\node_modules\electron-rebuild\node_modules\rxjs\Subscriber.js:102:18)
    at MapSubscriber.Subscriber._error (d:\apps\nvm\v7.9.0\node_modules\electron-rebuild\node_modules\rxjs\Subscriber.js:128:26)
    at MapSubscriber.Subscriber.error (d:\apps\nvm\v7.9.0\node_modules\electron-rebuild\node_modules\rxjs\Subscriber.js:102:18)
    at SafeSubscriber._next (d:\apps\nvm\v7.9.0\node_modules\electron-rebuild\node_modules\spawn-rx\lib\src\index.js:251:65)
    at SafeSubscriber.__tryOrUnsub (d:\apps\nvm\v7.9.0\node_modules\electron-rebuild\node_modules\rxjs\Subscriber.js:238:16)
    at SafeSubscriber.next (d:\apps\nvm\v7.9.0\node_modules\electron-rebuild\node_modules\rxjs\Subscriber.js:185:22)

finally  I found `gyp http GET https://atom.io/download/electron/v1.7.9/iojs-v1.7.9.tar.gz` , the url fetch is 404， I guess， that has not update new package, and I found the package at last was 1.6.5， 
![image](https://user-images.githubusercontent.com/8299627/32947629-1e0ec2c0-cbd7-11e7-9aa5-5ae65e977a93.png)

![image](https://user-images.githubusercontent.com/8299627/32947707-45256cec-cbd7-11e7-9988-082428ec5ccb.png)

this is taobao mirror

**Comment by MarshallOfSound** [comment]
> this is taobao mirror

I guess that mirror hasn't been updated because the actual URL "https://atom.io/download/electron/v1.7.9/iojs-v1.7.9.tar.gz" resolves fine.  I don't know who maintains that mirror but you should reach out and ask them to update it with the latest versions 👍

**Comment by iunfire** [comment]
very think you， I resolve it。
