### ISSUE TITLE
electron app   click failure on win7  touch screen after link jump to another  page

### ISSUE THREAD

**Issue by leonayx123** [electron/electron#11146]
I found someone asking the same issue..

issue #8725 

but he didn't solve it.

I'm going to focus on that issue

sorry. please close my issue

**Comment by sofianguy** [comment]
@leonayx123 no worries. Please follow issue #8725 for updates. I am closing this as it is a duplicate issue.

**Comment by leonayx123** [comment]
@sofianguy 
Well,thank you , I'll continue to focus on that. I hope the electron team can take this issure seriously
