### ISSUE TITLE
titleBarStyle: hidden logs an error

### ISSUE THREAD

**Issue by hpohlmeyer** [electron/electron#11150]
* Electron version: 1.8.2
* Operating system: macOS 10.13.1 

### Expected behavior
The use of `titleBarStyle: hidden` should not log an error.

### Actual behavior
When using `titleBarStyle: hidden`, the following error gets logged.

```
Electron[10655:980586] *** WARNING: Textured window <AtomNSWindow: 0x7fcb0f71bdb0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
```

### How to reproduce

Set the `titleBarStyle` of the electron window to `hidden`.

**Comment by hpohlmeyer** [comment]
I updated electron to v1.8.2-beta.3 and even though the changelog says, this should be fixed, I still get the error, when I use `titlebarStyle: hidden`.

**Comment by qazbnm456** [comment]
I still get the same error message too as I upgrade to v1.8.2-beta.3.

![](https://i.imgur.com/oy1VMUX.png)

**Comment by singhshashi** [comment]
@hpohlmeyer Do you just get the error message, or do you also see issues with rendering of window? https://github.com/electron/electron/issues/11105

**Comment by singhshashi** [comment]
I suspect this was not fixed in https://github.com/electron/electron/pull/11164 because of using `setTitleBarAppearsTransparent` instead of `titleBarAppearsTransparent` https://github.com/electron/electron/pull/11164/commits/daad465fcdf4f3d861f1cce9a08d97a6fe3639fc#r159121193

**Comment by hpohlmeyer** [comment]
@singhshashi Yes, I also get a greyish background, if I do not define the background color for the window, but I don’t think it is related to this issue.

**Comment by hacdias** [comment]
Are there any updates on this? We're setting `frame` to `false` and receiving this error too.

**Comment by felixrieseberg** [comment]
Yep, that seems to be all correct - this bug isn't as fixed as I'd like it to be. I'll take another crack at it.

**Comment by felixrieseberg** [comment]
Electron 2.0 seems to fix this issue.

**Comment by movingobjects** [comment]
@felixrieseberg Is this fix meant to be available in the 2.0 prereleases?

I've tried 2.0.0-beta.5 (2343f7c) and still having the same warning message come up when I have `frame: false`. No rendering issues, just this warning. Thx!

**Comment by caesarsol** [comment]
Same warning with 2.0.0, when I set `frame: false`!

**Comment by steffanhalv** [comment]
I have electron 2.0.8 and still get this error.

**Comment by danielsantil** [comment]
Hi, I have electron 3.0 and this warning still shows up, either by setting titleBarStyle: 'hidden' or frame: 'false'

**Comment by axelkennedal** [comment]
I have electron 3.0.2 and still get this error.

**Comment by rmnprt** [comment]
Still happens on electron 3.10.0 when I use `transparent:true`.

**Comment by venom90** [comment]
Still happens in electron 4.0.1

`app.on('ready', () => {

    // Hide dock icon, not needed for tray application
    app.dock.hide();

    mainWindow = new BrowserWindow({
        height: 500,
        width: 300,
        frame: false,
        resizable: false,
        alwaysOnTop: true,
        show: false,
        titleBarStyle: 'hiddenInset',
    });
    mainWindow.loadURL(`file://${__dirname}/src/index.html`);
    mainWindow.on('blur', () => {
        mainWindow.hide();
    });

    const iconName = process.platform === 'win32' ? 'windows-icon.png' : 'iconTemplate.png';
    const iconPath = path.join(__dirname, `./src/assets/${iconName}`);

    tray = new TimerTray(iconPath, mainWindow);
});`

**Comment by Eugeny** [comment]
So why exactly is this still closed?

**Comment by shams-ali** [comment]
same error with v4.0.5

**Comment by aguynamedben** [comment]
+1, still happening on 3.0.6 for us, I agree it should be reopened

**Comment by sambeau** [comment]
I'm still seeing this (and a small highlight at the top of the window) in Version 3.1.8

**Comment by sambeau** [comment]
Tested with electron@5.0.0-beta.8 and still present

**Comment by marc2332** [comment]
I fixed it by deleting titlebarStyle from the browserWindow object.

**Comment by inweid** [comment]
still have in 5.0.1 latest

**Comment by nehbit** [comment]
This is still present at 5.0.8. Would love to have this reopened.

**Comment by dhanyn10** [comment]
for temporary solution, you can use `frame: false` instead of `titlebarStyle: hidden`

**Comment by Red-Asuka** [comment]
still have in 33.2.0 lates

**Comment by FushimiYuki** [comment]
> for temporary solution, you can use `frame: false` instead of `titlebarStyle: hidden`

It seems that `frame : false` cause the same error message
