### ISSUE TITLE
Using 'frame: false' while creating a frameless BrowserWindow is producing a warning "Use NSWindow's -titlebarAppearsTransparent=YES instead."

### ISSUE THREAD

**Issue by Shikartoos** [electron/electron#11169]
Hi All,

My Electron and OS versions are:

* Electron version: 1.6.15
* Operating system: macOS High Sierra 10.13.1

So, I am trying to create a **Frameless BrowserWindow** object using the below parameters:

```
var framelessParams = {
        width: 500,
        height: 500,
        frame: false,
        transparent: true,
        show: false,
        backgroundColor: '#fff',
        resizable: false,
        movable: false,
        maximizable: false,
        minimizable: false
    };

 var framelessWindow = new BrowserWindow(framelessParams);
```

### Expected behavior

Showing the frameless window with no warning or errors.

### Actual behavior

Showing the frameless window with the below warning in the terminal output.

> Electron[1745:97088] *** WARNING: Textured window <AtomNSWindow: 0x7fbcbecc4650> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.

### How to reproduce

I have realized that using **frame: flase** is producing this warning.
By removing this option, I am not getting this warning.

I think, this might be related to the update I made to High Sierra and I don't recall having to see this warning using older versions of macOS.

I am not really sure, whether this has been reported before or not. However, please advise whether this should be (or already) addressed in the new releases.

Thank you,
Shikartoos.

**Comment by MarshallOfSound** [comment]
Duplicate https://github.com/electron/electron/issues/11150
