### ISSUE TITLE
Strange behaviour with custom protocols

### ISSUE THREAD

**Issue by sauravyash** [electron/electron#11160]
* Electron version: 1.6.11
* Operating system: macOS High Sierra 10.13.1
### Situation
So I am trying to get Google's Recaptcha to run locally on Electron, however, there were some issues with file://. So in #8414 (https://github.com/electron/electron/issues/8414), it says that the only way possible is to use a custom protocol. So I went ahead and did it, and the main HTML page renders properly, but without the CSS or js files. Honestly, all I want is a decent captcha to work in electron (doesn't have to be Recaptcha) with my form.

### Expected behaviour
Well, I believe that electron shouldn't be completely changing the data of files when executing.

### Actual behaviour
After analysing what happened, I found out that all linked files of all sorts were replaced by the html file. I believe this MIGHT has something to do with relative links but I don't know much about them.
<img width="1216" alt="screen shot 2017-11-18 at 10 19 58 pm" src="https://user-images.githubusercontent.com/12910821/32979822-3e0b613a-ccb0-11e7-941c-75725b44cf98.png">
<img width="1227" alt="screen shot 2017-11-18 at 10 20 01 pm" src="https://user-images.githubusercontent.com/12910821/32979823-3e5d560c-ccb0-11e7-8ba5-2ea5d17fadc6.png">

### How to reproduce
When I test my repo using the electron tester app. repo: 
https://github.com/sauravyash/OutFlux

**Comment by MarshallOfSound** [comment]
@sauravyash Can you provide you're protocol code, it sounds like you're registering a protocol handler and sending your HTML file as a responsive no matter what.  Relative CSS / JS files will use your custom protocol as well.  I.e. `custom://main.css`  You need to actually handle the requested URL and provide the correct file contents instead of blindly returning the HTML files contents

**Comment by sauravyash** [comment]
my main.js file 
```
const {app, BrowserWindow, ipcMain, protocol} = require('electron')
const path = require('path')
const url = require('url')
const fs = require('fs')

let mainWindow;
let authWindow;

protocol.registerStandardSchemes(['outflux'])

function createMainWindow () {
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    titleBarStyle: 'hiddenInset',
    frame: true,
    minWidth: 400,
    minHeight: 600,
    transparent: false
  });

  mainWindow.loadURL(url.format({
    pathname: path.join(__dirname, 'mainAppWindow.html'),
    protocol: 'file:',
    slashes: true
  }));
  mainWindow.maximize()

  mainWindow.on('closed', () => {
    mainWindow = null
  });
}

function createAuthWindow () {
  authWindow = new BrowserWindow({
    width: 400,
    height: 600,
    titleBarStyle: 'hiddenInset',
    frame: true,
    minWidth: 400,
    minHeight: 600,
    maxWidth: 400,
    maxHeight: 600,
    transparent: false,
    webPreferences: {
      nodeIntegration: false
    }
  });

  protocol.registerBufferProtocol('outflux', (request, callback) => {
    callback({mimeType: 'text/html', data: fs.readFileSync(path.join(__dirname, 'authWindow.html'))})
  }, (error) => {
    if (error) console.error('Failed to register protocol')
  })

  authWindow.loadURL(`outflux:


  authWindow.on('closed', () => {
    authWindow = null
  });
}

app.on('ready', function() {
  createAuthWindow();
});

app.on('window-all-closed', () => {
   app.quit();
})

app.on('activate', () => {
  if (mainWindow === null) {
    createWindow();
  }
});
```

**Comment by MarshallOfSound** [comment]
```js
protocol.registerBufferProtocol('outflux', (request, callback) => {
    callback({mimeType: 'text/html', data: fs.readFileSync(path.join(__dirname, 'authWindow.html'))})
  }, (error) => {
    if (error) console.error('Failed to register protocol')
  })
```

Yup, so that bit of code says "Any request you get on the `outflux` protocol, send this HTML file as the response.  You need to read `request.url` and figure out what file to server 👍 

See https://github.com/electron/electron/blob/master/docs/api/protocol.md#protocolregisterbufferprotocolscheme-handler-completion

**Comment by sauravyash** [comment]
After A bit of experimenting, i came up with this:

```
  protocol.registerBufferProtocol('outflux', (request, callback) => {
    console.log(request.url)
    if (request.url === 'outflux://authwindow.html/') {
      callback({mimeType: 'text/html', data: fs.readFileSync(path.join(__dirname, 'authWindow.html'))})
    } else {
      callback({data: fs.readFileSync(path.join(__dirname, request.url.replace(/(outflux:\u002F\u002Fauthwindow.html\u002F)/i, "")))})
    }
  }, (error) => {
    if (error) console.error('Failed to register protocol')
  })
```
