### ISSUE TITLE
shell.openExternal() opens links in the background on Windows 7 if Ctrl key is held down

### ISSUE THREAD

**Issue by Slapbox** [electron/electron#11162]
When I don't hold `Ctrl` Chrome is called to the foreground and the link opens. When I do hold `Ctrl`, the link is opened in the background.

I'm using Electron 1.7.9 on Windows 7 x64.

Chrome is version 61.

Thanks for reading.

**Comment by Slapbox** [comment]
Oddly the link will open in the foreground if you do the following:

1. Open the application with a global hotkey which uses the `Ctrl` key
2. Now click the link still holding down the `Ctrl` key

Once you release the `Ctrl` key and press it again, the link behavior returns to opening in the foreground.

**Comment by Slapbox** [comment]
This issue was, to the best of my recollection, fixed in 1.8.2, but I am seeing it again in 1.8.3.

**Comment by Slapbox** [comment]
@MarshallOfSound @codebytere  - This issue was briefly fixed a long time ago, but has been ongoing again ever since through version 2 and 3.

Do you have any thoughts on what can be done about this? 

Links clicked while holding `Ctrl` open in the background. Since the `activate` option doesn't exist on Windows, that's not a possibility, and I can't see any way to possibly modify the behavior from a user perspective.

**Comment by Slapbox** [comment]
Can anyone comment on this? It's a major UI bummer.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
