### ISSUE TITLE
Dev Tools don't render properly if an Audio has been played

### ISSUE THREAD

**Issue by aetheryx** [electron/electron#11163]
* Electron version: 1.7.9
* Operating system: Arch Linux

When attempting to open the Dev Tools after an  `Audio` has been played, the dev tools don't render properly - they are completely white. 

### Expected behavior

The dev tools open and everything is displayed correctly.

### Actual behavior

The dev tools open, but it's just a white canvas - there are no **visible** elements. They are however "there" - if I hover the spot where the buttons usually are, my cursor changes.

### How to reproduce

```
git clone https://github.com/Aetheryx/electron-issue
cd electron-issue
electron .
```
Now try to open the dev tools - it looks like this: https://imgur.com/3YtjU65
The white space is supposed to be the dev tools.

The issue can also be reproduced by pasting this snippet of code into the bare Electron-start-template, closing the dev tools and trying to reopen them.
```js
new Audio('https://raw.githubusercontent.com/anars/blank-audio/master/750-milliseconds-of-silence.mp3').play();
```

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
