### ISSUE TITLE
spawn a process in electron

### ISSUE THREAD

**Issue by xzycn** [electron/electron#11172]
I have seen some posts about the topic,yes,it run very well when I used electron command in console.But it could't work when I packaged(electron-builder) the electron app,and appeared a problem when I started the app:  it was starting create new process and CPU usage came to 100%.
I don't know how dose this happened, could you help me? please!
Here is my test code:
master.js(main):

```js
var childProcess = require('child_process');
let createProc = () => {
    let sp = childProcess.spawn(process.execPath,['./go.js'],{stdio:'ignore'});
    sp.unref();
    sp.on('error', (err) => {
        console.log('failed to start process',err);
    });
    sp.on('exit',(code, signal)=>{
        console.log(`child process exited with code ${code}`);
        createProc();
    });
}

createProc();
```
go.js:
```js
const {app, BrowserWindow} = require('electron');
let basicWindowParams = {
        show: true,
        autoHideMenuBar:true
};
console.log(process.execPath)
console.log(process.execArgv)
console.log(process.pid)
app.on('ready', () => {
    let win = new BrowserWindow(basicWindowParams);
    win.loadURL('http://www.reddit.com/');
    win.on('did-finish-load', () => {
        win.show();
    });
});
```
OS： Windows 10
Electron: 1.8.1

**Comment by xzycn** [comment]
Is there someone else can help me? please  :)

**Comment by sethlu** [comment]
Hi @xzycn, seems that you are trying to open a window (/starting a rendering process) in a separate JavaScript file? If so, I'll recommend checking out the default app (https://github.com/electron/electron/blob/master/default_app/main.js#L302)... You won' t need to spawn a JavaScript file to start a rendering process.

**Comment by xzycn** [comment]
@sethlu Thank you for your comment. Actually, I don't want to spawn a JavaScript file to start a rendering process.I will write some codes using [Nightmare](https://github.com/segmentio/nightmare) in go.js.
And I have solved my problem with child_process.exec,just as @sofianguy saied in #11197.But, the problem as I mentioned above still there. :)

**Comment by sofianguy** [comment]
@xzycn Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
