### ISSUE TITLE
Get Access Token from browserWindow and use it to open on Web Browser 

### ISSUE THREAD

**Issue by daffylumampao** [electron/electron#11177]
* Electron version: 1.7.9
* Operating system: windows 10

Hi, I'm new to electron and I would like to ask if it is possible to get the access token used in the browser window then use it to open your default web browser so that user won't be asked to log in again on the browser?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
