### ISSUE TITLE
Electron won't run steam game with parameters

### ISSUE THREAD

**Issue by WellMafra** [electron/electron#11174]
* Electron version: 1.7.8
* Operating system: Windows 10 Pro 64Bits

### Expected behavior

As a electron dev, I would like to open steam as a process with specific parameters, once steam accepts that parameters.
If you open `CMD` on Windows and execute:
```"C:\Program Files (x86)\Steam\Steam.exe" -gameidlaunch 227300 -nointro -novid -64bit```
It'll work fine.

### Actual behavior

I've already tried with `spawnSync` and `execFile` functions, but I'm not able to open steam game with electron.
The `spawnSync` or `execFile` functions, are able to open the Steam application, but nothing happens.

With **execFile**, on `console.log`, its being printed:
`ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".`

### How to reproduce

**spawnSync** 
```JS
import { spawnSync  } from 'child_process';

const executeGame = () => {
  const path = 'C:\Program Files (x86)\Steam';
  const execArguments = ['-gameidlaunch 227300', '-nointro', '-novid', '-64bit'];

  const process = spawnSync(path, execArguments);
  console.log(process );
}
```

**execFile**
```JS
import { execFile } from 'child_process';

const executeGame = () => {
  const path = 'C:\Program Files (x86)\Steam';
  const execArguments = ['-gameidlaunch 227300', '-nointro', '-novid', '-64bit'];

  execFile(path, execArguments, function(err, data) {
      if(err){
         console.error(err);
         return;
      }
      console.log(data.toString());
  });
}
```

**Comment by TiagoDanin** [comment]
`execFile` works. Disable Windows Defender, VPN, and Proxy... Try again

**Comment by WellMafra** [comment]
Hey @TiagoDanin , thanks for your reply.
Unfortunetily it did not work, as you can see on image:

![image](https://user-images.githubusercontent.com/7647730/32995631-6dd7f3f2-cd5e-11e7-8388-782de85c55fa.png)

**Comment by enlight** [comment]
If you pasted that `path` verbatim then it is invalid because you didn't escape the backslashes.

**Comment by WellMafra** [comment]
@enlight that `path` is just an example, but on my application the user is able to find the steam path with an `inputFile`

**Comment by WellMafra** [comment]
Greate news!

I have already fix it. The final code:

```js
import { spawn  } from 'child_process';
import slash from 'slash';

...

// receiving path as: 'C:\Program Files (x86)\Steam\Steam.exe';
const executeGame = (path) => {
  path = slash(path); // C:/Program Files (x86)/Steam/Steam.exe
  path = `"${path}"`; // "C:/Program Files (x86)/Steam/Steam.exe"

  const execArguments = ['-gameidlaunch 227300', '-nointro', '-novid', '-64bit'];    

  try {
    const spawnedProcess = spawn(path, execArguments, { detached: true, shell: true, stdio: 'ignore' });
    spawnedProcess.unref();
  } catch (error1) {
    console.log(error1);
    return;
  }
};

```

**Comment by rendomnet** [comment]
@WellMafra this doesn't work on mac when steam is running.  I'm using '/Applications/Steam.app/Contents/MacOS/steam_osx'.
