### ISSUE TITLE
How to run electron on Docker

### ISSUE THREAD

**Issue by michaelalhilly** [electron/electron#11175]
It would be nice to keep electron and all dependencies inside docker.

* Electron version: 1.7.9
* Operating system: OS X 10.11.6
* Docker version: 17.09.0-ce-mac35 (19611)

### Expected behavior

Run electron app in docker container with electron installed globally.

### Actual behavior

Receiving following error:

/var/www/node_modules/electron/dist/electron: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

### How to reproduce

Run electron app in docker container with electron installed globally.

### Note

I've tried installing the following dependencies with no luck:

libgtkextra-dev libgconf2-dev libasound2 libxtst-dev libxss1 \
libdbus-1-dev libgtk2.0-dev libnotify-dev libgnome-keyring-dev \
libcap-dev libcups2-dev libnss3-dev libx11-xcb-dev

**Comment by groundwater** [comment]
Hey @michaelalhilly. This is definitely _unsupported territory_ but I love a good Docker experiment.

First, what window manager are you using? I don't believe Docker mac does not have any displays by default. Are you trying to use XQuartz on MacOS or are you going to create a virtual display with whichever hypervisor tool you're using?

**Comment by michaelalhilly** [comment]
Hi @groundwater.

Sorry for the late reply. I feel it might be better for me to be a little more open to installing a few dependencies on my device; i.e. NPM and Node. I've been getting by with just Docker but I realize now it really isn't a big deal to install NPM and Node.

However, I did find this article explaining how to do this:

https://medium.com/@calbertts/developing-electron-apps-in-macos-afd21b4a59e3

Personally, I don't want in use the Nut library referenced here as it is in it's early development phase. I'm good just installing and using Electron the way it was intended.

Thanks for the quick response. I'll keep an I out for future development on this.
