### ISSUE TITLE
Add Twain api or  Twain  plugin for  scanner

### ISSUE THREAD

**Issue by Abdullah-FAl** [electron/electron#11180]
**## There is a request from the developers of the electron**
Please 
**# Add Twain api or  Twain  plugin for  scanner**
in the  **# new electron version**
Works in all systems
**# windows all- MacOS all -linux all**

if it is possible

**Comment by felixrieseberg** [comment]
@Abdullah-FAl this request is not very clear. What is Twain? What is your problem?

**Comment by elegos** [comment]
@felixrieseberg  TWAIN is an API / protocol to communicate between an application and a TWAIN-enabled scanner to import images directly from the scanner surface, rather than using a proprietary software to import the image.

@Abdullah-FAl you can easily do it adding a node package, like this one: https://www.npmjs.com/package/scanner-js IMHO no need to integrate in electron.

**Comment by felixrieseberg** [comment]
@elegos Thank you so much for helping out here 🙇 Seems like we're good, I'm going to close this issue now.

**Comment by dustyroberts** [comment]
https://www.npmjs.com/package/scanner-js is probably the single most expensive piece of software i've ever come across.

The only version that works with electron is the ENTERPRISE version which costs a mere $19,998

I rate we re-open this request :)

**Comment by dan-willett** [comment]
@dustyroberts  I second that request.

There needs to be an open source method of accessing TWAIN scanners from within Electron.

This project: https://github.com/mgriit/ScanAppForWeb may be a good reference,

Also these sites are relevant: http://www.twain.org/   and  http://www.twaindirect.org/  as well as the twain spec here:  http://www.twain.org/wp-content/uploads/2016/03/TWAIN-2.2-Spec.pdf

**Comment by gino8080** [comment]
Totally Agree with @dustyroberts  and @dan-willett  we NEED an open source free (or at least not so expensive) solution to work with TWAIN

**Comment by luke93h** [comment]
agree with @gino8080

**Comment by giorgiobeggiora** [comment]
it should be awesome to have the ability to acquire from a scanner without any dialog window

**Comment by elegos** [comment]
@giorgiobeggiora I think Electron should only handle the protocol layer, leaving the users to create the graphical interface, so it should be no issue.

**Comment by simeon9696** [comment]
Has there been any update on this?

**Comment by scottrotton** [comment]
Agreed this should be done in electron!
