### ISSUE TITLE
fs.readFile(path, null, cb) TypeError: Bad arguments

### ISSUE THREAD

**Issue by Feverqwe** [electron/electron#11182]
Hello!
When read file from asar I see error: TypeError: Bad arguments.
`fs.readFile(path, null, cb)`
This code work fine:
`fs.readFile(path, {}, cb)`

If use fs-extra throw same error:
`fse.readFile(path)`

Tested in 1.8.2-beta.2

**Comment by felixrieseberg** [comment]
Yup, that's a real bug. Thanks for reporting!
