### ISSUE TITLE
Expose a `browser-window-closed` event on the module `app`.

### ISSUE THREAD

**Issue by ficristo** [electron/electron#11188]
* Electron version: 1.7.9
* Operating system: All

### Expected behavior

A `browser-window-closed` event is available on the module `app`.
I have a piece of code separated from the main file (in which the BrowserWindow si created) where I don't have access to the BrowserWindow instance. So I cannot call `win.on('closed')`
Since there is already a `browser-window-created` event I was hoping to have its counterpart.

### Actual behavior

It is not.

### How to reproduce
Try to call `app.on('browser-window-closed', (event, win) => {})`

**Comment by codebytere** [comment]
We don't expose this on purpose, as the create event allow you to track all windows including windows you don't explicitly make. Adding an app-wide event for browser windows wouldn't make sense given that.

See:
```
app.on('browser-window-created', (event, window) => {
  window.on('closed', doStuff)
})
```
for example of how this should look.
