### ISSUE TITLE
process always running

### ISSUE THREAD

**Issue by ColinMoulds** [electron/electron#11192]
* Electron version: 1.7.9
* Operating system: Windows 10

### Expected behavior

on app quit - full process ends

### Actual behavior

the app lingers in task manager till you "end task"

### How to reproduce

https://github.com/HydeInit/Mixer-Desktop

$ git clone https://github.com/HydeInit/Mixer-Desktop.git

release builds - i32 or x64
run mixer-desktop.exe
close program
check task manager

**Comment by gschier** [comment]
I believe you need to quit the app when the last window is closed. See the example here: https://electronjs.org/docs/api/app#app

**Comment by enlight** [comment]
I don't think the code as it is now will even run properly, I don't see where `app` is defined in `main.js`. I'm going to close this for now since I suspect this is an issue with your code, if the process still won't quit after fixing your code we can reopen this.
