### ISSUE TITLE
Can you create a windows app that does not need to be installed?

### ISSUE THREAD

**Issue by akobrandon** [electron/electron#11190]
Hi guys im just wondering if there is a way to create a standalone .exe that does not need to be installed. I have a very simple app I am trying to deploy and I want them to be able to download it open it use it close it and move it to the trash.

Thanks

**Comment by ColinMoulds** [comment]
@akobrandon yes you can I use the following command, the words in all caps are what you change.

you will need electron packager npm.

# for use in npm scripts
npm install electron-packager --save-dev

# for use from cli
npm install electron-packager -g

command: 

electron-packager . APPNAME --overwrite --platform=PLATFORM RELEASE --arch=OS TYPE --icon=ICONPATH
--prune=true --out=OUTPUTFOLDER --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.P
roductName="APP NAME"

**Comment by akobrandon** [comment]
@ColinMoulds ok, but after running this I am left with a folder with an EXE and a ton of .dll's and those are are required to run the .exe. How can I package it all into a single standalone exe?

**Comment by MarshallOfSound** [comment]
@akobrandon `electron-winstaller` will create a single EXE for you 👍

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
