### ISSUE TITLE
Enforce 2FA For Electron

### ISSUE THREAD

**Issue by groundwater** [electron/electron#11194]
We intend to enable 2FA for the electron org

The following members currently do not have 2FA enabled. You will lose access unless you [enable 2FA](https://github.com/blog/1614-two-factor-authentication).

@akameco, @akost, @alexstrat, @ArisLittle, @arturts, @atom-build, @bureken, @ChrisFan, @danhp, @datamadic, @demopark, @deopard, @diegowifi, @dongjoon-hyun, @duncup, @electron-bot, @excfergodst, @fbukevin, @feserafim, @fplucas, @Gaserd, @heyunjiang, @hokein, @hotuan87, @imelven, @joemccann, @John-Lin, @joneian, @jweinstein, @kokdemo, @LasseJacobs, @LaurentLeVan, @ldehai, @liuderchi, @LShun, @LuisHsu, @Meyito, @Nirmal4G, @nkolba, @ovo4096, @parro-it, @paulinaika, @pcperini, @Rafaelgfirmino, @Raul6469, @roadev, @roramirez, @rsezille, @runinspring, @ryo-a, @sairoutine, @sarabreeding, @sauber92, @sbahra, @schwalbe10, @selique, @serant, @ShiningRay, @shubham2892, @simonmysun, @SLiNv, @Stone-Jay, @tarruda, @TiagoDanin, @tinydew4, @tomfloyer, @vaartis, @victorhsn, @vreality64, @wgrafael, @Wolfer, @x-yao, @x87 

We will switch mandatory 2FA on starting Dec 1.

**Comment by sethlu** [comment]
Redirected to #11193.
