### ISSUE TITLE
Is there any feature for adding custom css or html in menu ?

### ISSUE THREAD

**Issue by vaidyaanand** [electron/electron#11198]
How to customize menu in electron app?

I have one frameless electron app which can be run on windows and mac system. I have learned how to set ApplicationMenu and contextmenu(right click only). But, I want to set an Image like settings and clicking on that will open the customized menu (which have its HTML, CSS and js) which catch the events like focusedWindow to get the current focusedWindow. How can I achieve this functionality? Below is the image which describes what I am trying to do.

![11-21-2017 12-56-44 pm](https://user-images.githubusercontent.com/22315535/33062073-0603b0c4-cec4-11e7-9915-c234b5065a54.png)

* Electron version:
* Operating system:

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by vaidyaanand** [comment]
But you must make your documentation in more detailed to avoid such kind of posts
