### ISSUE TITLE
Blocking js alert error seen when disconnected from internet during auto update

### ISSUE THREAD

**Issue by Ajeey** [electron/electron#11196]
* Electron version: "1.7.9"
* Operating system: macOS Sierra 10.12.5

### Expected behavior
When the computer is disconnected from the internet, the **javascript alert error** should not be seen. It should be a silent fail in the background.

### Actual behavior
When WIFI is turned off during the update download process, a **javascript alert error** is seen. Please see the below screen shot.
<img width="473" alt="screen shot 2017-11-21 at 11 21 50 am" src="https://user-images.githubusercontent.com/1799117/33058687-c9811f9a-ceb6-11e7-8d14-a90a465c4cfd.png">

### How to reproduce
Implement the auto update logic as mentioned here - https://electronjs.org/docs/api/auto-updater
And during the process of downloading the update, **TURN OFF** the wifi

**Comment by MarshallOfSound** [comment]
@Ajeey You need to handle the `error` event on the `autoUpdater` object.  Unhandled errors emitted on `EventEmitter` objects will be thrown as unhandled exceptions and thus create that dialog.  To ensure no dialogs appear you need to handle the `unhandledException` event on `process`

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
