### ISSUE TITLE
error with electron-rebuild ed25519 libary

### ISSUE THREAD

**Issue by ArronYR** [electron/electron#11209]
hi, in my project, I need use `ed25519` library. If I run the program directly after `npm install`, an error will be reported:
```
project/node_modules/ed25519/build/Release/ed25519.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
```

I use `npm rebuild` able to compile normally, but when I use `./node_modules/.bin/electron-rebuild` compiled under the project directory, error message shows:
```fatal error: 'openssl/sha.h' file not found```

- NodeJS Version: 9.2.0
- Electron Version: 1.7.9
- Operating system: macOS High Sierra 10.13

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
