### ISSUE TITLE
error with electron libcc compile missing identifier

### ISSUE THREAD

**Issue by tonetheman** [electron/electron#11206]
Trying to build electron with libcc

* Electron version: pulled directly from github.com today (2017-11-21)
* Operating system: Windows Server 2016 (AWS)

### Expected behavior

Compile and link as expected.

### Actual behavior
C:\Python27\python.exe C:\projects\electron\vendor\libchromiumcontent\script\build -D -t x64
ninja: Entering directory `src\out-x64\shared_library'
[197/20736] CXX obj/base/base/trace_event_etw_export_win.obj
FAILED: obj/base/base/trace_event_etw_export_win.obj
ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64/cl.exe" /nologo /showIncludes /FC @obj/base/base/trace_event_etw_export_win.obj.rsp /c ../../base/trace_event/trace_event_etw_export_win.cc /Foobj/base/base/trace_event_etw_export_win.obj /Fd"obj/base/base_cc.pdb"
c:\projects\electron\vendor\libchromiumcontent\src\base\trace_event\trace_event_etw_export_win.cc(243): error C3861: 'EventEnabledChromeEvent': identifier not found
c:\projects\electron\vendor\libchromiumcontent\src\base\trace_event\trace_event_etw_export_win.cc(343): error C3861: 'EventEnabledChromeEvent': identifier not found
[206/20736] CXX obj/base/base/trace_log.obj
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\projects\electron\vendor\libchromiumcontent\script\build", line 66, in <module>
    sys.exit(main())
  File "C:\projects\electron\vendor\libchromiumcontent\script\build", line 45, in main
    subprocess.check_call([NINJA, '-C', os.path.relpath(out_dir), target], env=env)
  File "C:\Python27\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\projects\\electron\\vendor\\libchromiumcontent\\vendor\\depot_tools\\ninja.exe', '-C', 'src\\out-x64\\shared_library', 'chromiumcontent:chromiumcontent']' returned non-zero exit status 1
None
Traceback (most recent call last):
  File "C:\projects\electron\script\build-libchromiumcontent.py", line 78, in <module>
    sys.exit(main())
  File "C:\projects\electron\script\build-libchromiumcontent.py", line 52, in main
    execute_stdout([sys.executable, build, '-D', '-t', args.target_arch])
  File "C:\projects\electron\script\lib\util.py", line 184, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'C:\\projects\\electron\\vendor\\libchromiumcontent\\script\\build', '-D', '-t', 'x64']' returned non-zero exit status 1
None
Traceback (most recent call last):
  File "script\bootstrap.py", line 261, in <module>
    sys.exit(main())
  File "script\bootstrap.py", line 43, in main
    args.build_debug_libcc, args.update_libcc)
  File "script\bootstrap.py", line 184, in build_libchromiumcontent
    execute_stdout(args + ['--target_arch', target_arch])
  File "C:\projects\electron\script\lib\util.py", line 184, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'C:\\projects\\electron\\script\\build-libchromiumcontent.py', '-d', '-v', '--target_arch', 'x64']' returned non-zero exit status 1

### How to reproduce

Install all needed software as needed to build.

Then I ran this command from the electron directory
python script\bootstrap.py -v -d --build_debug_libcc

Then let the build run (it will get far and take a bit) but eventually you will get a compile error looking for the symbol 'EventEnabledChromeEvent'.

Here is my PATH in case you need it.
C:\projects\electron>echo %PATH%
"c:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin";"c:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin\x64";C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\MSBuild\14.0\bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools;C:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\VCPackages;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\10\bin\x86;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\;C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Amazon\cfn-bootstrap\;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\Administrator\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Users\Administrator\AppData\Roaming\npm

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
