### ISSUE TITLE
Load-finish events not always firing on sites served over custom protocols

### ISSUE THREAD

**Issue by pfrazee** [electron/electron#11205]
* Electron version: 1.8.2-beta
* Operating system: MacOS 10.12

This is related to #9342. [This PR stopped crashes from happening](https://github.com/electron/electron/pull/10918) but now I'm observing situations where large files -- or files that take a long time to stream? -- will fail to emit `'did-stop-loading'` and `'did-finish-load'` on finish. Based on what I've observed, this failure occurs in the same situations that previously caused a crash. So, some important part of the request/response lifecycle is not being handled.

I wasn't able to prove the exact cause. My theory is that we want `GatherRawReadStats(result);` to run, but not `base::ResetAndReturn(&read_raw_callback_).Run(result);` (see the [relevant chromium source](https://cs.chromium.org/chromium/src/net/url_request/url_request_job.cc?type=cs&q=ReadRawDataComplete&sq=package:chromium&l=484)). It's hard to say for sure because everything inside `ReadRawDataComplete()` is private, so I can't check state or directly manipulate them 😠

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
