### ISSUE TITLE
Trying to build electron on Windows

### ISSUE THREAD

**Issue by tonetheman** [electron/electron#11202]
* Electron version: did a pull from github.com today 2017-11-03

* Operating system: AWS image Windows Server 2016

### Expected behavior
Should just build

### Actual behavior

Instead I get the error below. 

It _feels_ like I am somehow missing a link from the ninja build to the SDK directory. I saw this issue was similar [https://github.com/electron/electron/issues/10781](https://github.com/electron/electron/issues/10781) but there no solution there short of just retrying.

C:\projects\electron>python script\build.py -c D
ninja: Entering directory `out\D'
[1000/1327] LINK_EMBED openssl-cli.exe
FAILED: C:\Python27\python.exe gyp-win-tool link-with-manifests environment.x64 True openssl-cli.exe "C:\Python27\python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /OUT:openssl-cli.exe @openssl-cli.exe.rsp" 1 mt.exe rc.exe "obj\vendor\node\deps\openssl\openssl-cli.openssl-cli.exe.intermediate.manifest" obj\vendor\node\deps\openssl\openssl-cli.openssl-cli.exe.generated.manifest
'mt.exe' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "gyp-win-tool", line 323, in <module>
    sys.exit(main(sys.argv[1:]))
  File "gyp-win-tool", line 29, in main
    exit_code = executor.Dispatch(args)
  File "gyp-win-tool", line 71, in Dispatch
    return getattr(self, method)(*args[1:])
  File "gyp-win-tool", line 170, in ExecLinkWithManifests
    '-manifest %(manifests)s -out:%(out)s.manifest' % variables)
  File "C:\Python27\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Python27\python.exe gyp-win-tool manifest-wrapper environment.x64 mt.exe -nologo -manifest obj\vendor\node\deps\openssl\openssl-cli.openssl-cli.exe.generated.manifest -out:openssl-cli.exe.manifest' returned non-zero exit status 1
[1000/1327] CXX obj\atom\browser\electron_lib.web_view_guest_delegate.obj
ninja: build stopped: subcommand failed.

### How to reproduce
I started with a generic Windows 2016 base image on AWS
Installed everything needed for building with these instructions

1. get admin power shell (search for power then right click on top and run as admin)
REM turn off windows defender
Uninstall-WindowsFeature -Name Windows-Defender
Get Admin Powershell again
REM install choco
Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

REBOOT

2. install stuff needed for build with choco + git
Get Admin Powershell again
choco install chromium 
choco install python2 
choco install nodejs-lts 
https://git-scm.com/download/win
REM ended up with 2.15.0 for 64bit
REM took defaults on install for all questions

3. install VS commnunity 2015 update 3
REM need to login to do this
https://my.visualstudio.com/Downloads?q=visual%20studio%202015&wt.mc_id=o~msft~vscom~older-downloads
- Ran and picked default finished the install
- launched at end, did not sign in and picked default theme

Go to control panel find VS community 2015 - pick uninstall and modifiy
- add c++ programming language (click on top level)
	- this installs all the products under c++

4. Windows SDK 
https://developer.microsoft.com/en-us/windows/downloads/sdk-archive
Need 10.0.15063.468
	- take default on location
	- no for send anonymous data to MS
	- accept lic
	- install everything (DEFAULT)

5. pull from git and run build
cd c:\
mkdir projects
git clone https://github.com/electron/electron.git
cd electron
python script\bootstrap.py -v
python script\build.py -c D

**Comment by felixrieseberg** [comment]
The issue here seems to be that your system can't find `mt.exe`. Is it in the path? If not, is it installed?

https://msdn.microsoft.com/en-us/library/windows/desktop/aa375649(v=vs.85).aspx

**Comment by tonetheman** [comment]
Yup yup that did it. I added c:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\bin\x64 to my PATH variable and it worked. thanks for the suggestion

**Comment by enlight** [comment]
FYI, the VS installation process would've created a bunch of shortcuts to open up a prompt with the correct environment set up for command line builds, if you use the prompt opened via one of these shortcuts you won't have to mess about with PATH. More about that at https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line#developer_command_prompt_shortcuts

**Comment by tonetheman** [comment]
I am using the Developer Command prompt. What I noticed was that without me adding that to the PATH the windows sdk would not be found. Like that mt.exe error.

I am sure it is something I am doing wrong though. ha. I looked around and the only place I could find mt.exe was in that SDK directory I added.

**Comment by tonetheman** [comment]
@enlight that link you sent in the response was great. Maybe I am missing something where you setup the SDK. I will poke around in those files. thanks
