### ISSUE TITLE
Pinch Zoom enables again when changing from external monitor to laptop monitor

### ISSUE THREAD

**Issue by bpasero** [electron/electron#11216]
* Electron version: 1.7.9
* Operating system: macOS 10.13.1

### Expected behavior

If pinch-zoom is disabled via `webFrame.setVisualZoomLevelLimits(1, 1);` it should stay disabled.

### Actual behavior

Pinch zoom is possible. 

### How to reproduce

* connect an external monitor and open any electron app there, keep the macbook pro lid closed
* disconnect the external monitor
* open the lid

=> you can now pinch zoom

**Comment by nornagon** [comment]
Confirmed still happening in 2.0.x
