### ISSUE TITLE
electron can  provide official remote auto update .

### ISSUE THREAD

**Issue by yueswing07** [electron/electron#11210]
i see many developer using many different methods to update their applications developing by electron.
i think  it will be good for electron if there any unified method for updating applications remotely and automatically.
  thanking for giving your time  reading my suggest.

**Comment by MarshallOfSound** [comment]
@yueswing07 We provide an internal `autoUpdater` API which as far as I am aware, basically everyone uses 👍 

https://electronjs.org/docs/api/auto-updater

**Comment by yueswing07** [comment]
@MarshallOfSound thank you    I can understand it first.  unified and easy method to use can be good to develop of electron
