### ISSUE TITLE
Question : how to know version of electron in linux #3371

### ISSUE THREAD

**Issue by ssu2030** [electron/electron#11212]
* Electron version:
* Operating system:  ubuntu linux

### Expected behavior
following https://electronjs.org/docs/api/process

#process.versions.electron:
- A String representing Electron's version string.

like not this form,

Is there any way to get Electron version ?
likes 
$node
$electron -v (current version)

**Comment by ssu2030** [comment]
answer : npm i electron-version -S

**Comment by sethlu** [comment]
Sounds like you've found a solution 👍

**Comment by ssu2030** [comment]
@sethlu  Yes I found on google. Thanks for your favor 👍 👍

**Comment by zeke** [comment]
For a global install:

```sh
$ electron --version
v1.7.9
```

For a local install: 

```sh
$ ./node_modules/.bin/electron --version
v1.7.9
```

**Comment by sethlu** [comment]
Oh I think I misinterpreted the question. Providing `-v` or `--version` should both work.
