### ISSUE TITLE
Default URL protocol

### ISSUE THREAD

**Issue by KorobkaVadim** [electron/electron#11220]
I have problem with default url protocol. 

* Electron version: 1.7.9 
* Operating system: Win32/Mac OS

### Expected behavior

After uninstall app default url protocol doesn't remove.

### Actual behavior

I haven't this problem electron 1.6.1 and electron builder 9.6.0. I understand I should call remove default  protocol but I can't add operations in uninstall script(Squirrel)?

**Comment by MarshallOfSound** [comment]
See [Handling Squirrel Events](https://github.com/electron/windows-installer#handling-squirrel-events)

In particular the `--squirrel-uninstall` one 😄

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
