### ISSUE TITLE
Global Shortcuts swallow key press event

### ISSUE THREAD

**Issue by jeremysmitherman** [electron/electron#11226]
* Electron version: 1.7.9
* Operating system: OS:X

When binding a global shortcut to something like "Space" , key press event should bubble up, instead it seems like event propagation is halted.

When binding "Space" for instance on app start, space bar no longer adds spaces in other programs as long as electron app is open.

run this code in main.js in electron

const space = globalShortcut.register('Space', () => {
        return true;
    })

Open up another program and attempt to use space bar.

**Comment by codebytere** [comment]
Please try to follow the format of the issue template; see [contrib guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md#submitting-issues). We'll take a look at this soon :)

**Comment by MarshallOfSound** [comment]
This behavior was explained in detail by me in a previous issue

https://github.com/electron/electron/issues/8491#issuecomment-274790124
