### ISSUE TITLE
how to pass parameters when BrowserWindow opened?

### ISSUE THREAD

**Issue by salehmosleh** [electron/electron#11222]
how can we pass some data to a new BrowserWindow when it created?
```

let mainWindow = new BrowserWindow({
				width: 800, 
				height: 650 , 
				frame: false ,
				backgroundColor: '#ffffff',
				webPreferences: {
					
				}
			}); 
			 
			mainWindow.loadURL(url.format({
				pathname: path.join(__dirname, 'mainpanel.html'),
				protocol: 'file:',
				slashes: true
			})); 
			mainWindow.maximize();
```

**Comment by MarshallOfSound** [comment]
There are a few techniques for this, you can send stuff through IPC as soon as the window is ready (this is async / non-blocking).  Or you can actually attach query parameters to the `loadURL` request.

E.g.
```js
window.loadURL('myfile.html?data=stuff')
```

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by salehmosleh** [comment]
@MarshallOfSound , thank you

**Comment by notblank00** [comment]
> There are a few techniques for this, you can send stuff through IPC as soon as the window is ready (this is async / non-blocking). Or you can actually attach query parameters to the `loadURL` request.
> 
> E.g.
> 
> ```js
> window.loadURL('myfile.html?data=stuff')
> ```

the loadURL method seems to specifically remove the query string now (for whatever reason)
