### ISSUE TITLE
cannot use sessionStorage between two different BrowserWindows!

### ISSUE THREAD

**Issue by salehmosleh** [electron/electron#11223]
i set some items to sessionStorage in first BrowserWindow and i try to get it in other BrowserWindow , but it shows me null . how can i use sessionStorage in  different BrowserWindows! 
also localStorage works fine.

**Comment by felixrieseberg** [comment]
I don't think that's supposed to work. Please see the documentation: https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage

> A page session lasts for as long as the browser is open and survives over page reloads and restores. _Opening a page in a new tab or window will cause a new session to be initiated, which differs from how session cookies work_.

Let me know if I misunderstood you, otherwise I'm closing this issue.

**Comment by salehmosleh** [comment]
@felixrieseberg , thank you. i think electron has to have a thing like session to share data between different BrowserWindows.

**Comment by felixrieseberg** [comment]
It does! `localStorage` is probably what you're looking for, if not, the disk will likely do.
