### ISSUE TITLE
is there electron support for create web-hooks services get api endpoints

### ISSUE THREAD

**Issue by RobertRajcool** [electron/electron#11237]
* Electron version:1.79
* Operating system:ubuntu16

i have develop electron application,now i struct getting api-end points from electron apps ,How to do this one

**Comment by enlight** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
