### ISSUE TITLE
Unfortunately, can not be used in China

### ISSUE THREAD

**Issue by yuchonghua** [electron/electron#11236]
* Electron version:
* Operating system:

### How to reproduce

![image](https://user-images.githubusercontent.com/17898715/33193552-73be8f02-d104-11e7-8a4b-91930ac5906e.png)

**Comment by MarshallOfSound** [comment]
There is a [Chinese Mirror](https://github.com/electron/electron#mirrors) in the README

**Comment by yuchonghua** [comment]
@MarshallOfSound @welcome Thank you
