### ISSUE TITLE
Remove async menu from the docs

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#11242]
It was removed by Chromium in the version 61, so we don't have it anymore.
Remove it from the docs.

/cc @zeke

**Comment by bpasero** [comment]
@alexeykuzmin with this change, it is no longer possible to find out when the context menu hides. Previously you could just know that the code that executes after the `menu.popup()` call was triggered when the context menu was hidden. 

I think it can be hard for applications to adopt this change without having a way to get the previous functionality back. E.g. being able to pass in a callback function that gets called when the context menu closes (similar to how this works for the Dialog API as well).

Would it be possible to add something like a callback to menu.popup() that gets called when the menu closes (either by the user picking an action or by dismissing the menu)?

**Comment by ckerr** [comment]
@bpasero, could you open a new enhancement issue for that so that it can be tracked separately from this removal?

**Comment by bpasero** [comment]
@ckerr I did that already months ago (https://github.com/electron/electron/issues/9441) but now that the `sync` option is removed this becomes a much bigger problem.
