### ISSUE TITLE
Devtools closed on a transparent window changes its background permanently

### ISSUE THREAD

**Issue by deepak1556** [electron/electron#11258]
* Electron version: 1.8.x
* Operating system: All

### Expected behavior

Opening and closing devtools for a transparent window shouldn't change its background color.

### Actual behavior

White background is not removed when the devtools is closed.

![33211592-8ef2fa36-d11f-11e7-838d-678fe77a858b](https://user-images.githubusercontent.com/964386/33231625-64ba18b2-d21e-11e7-86c3-bc74435ba7aa.gif)

### How to reproduce

```
  $ git clone https://github.com/brenca/electron-quick-start
  $ npm install
  $ npm start || electron .
```

**Comment by brenca** [comment]
@deepak1556 I tried to find the exact location where the background change happens, and I've found that if I comment [this](https://github.com/electron/electron/blob/dcde0a00fb5807978af6b66e5892728c5ae0775e/brightray/browser/inspectable_web_contents_impl.cc#L335) line out, the issue goes away. I can't find an exact location in the chromium sources, but it seems that the code was recently (relative to the 59 release) restructured around the `DevToolsAgentHostImpl` class and the `WebKit` classes related to devtools, so there might have been something there that caused this behaviour.

**Comment by brenca** [comment]
Sadly the problem is still present on the current master, with Chromium 61.

**Comment by KochiyaOcean** [comment]
Seems a same problem https://github.com/electron/electron/issues/10420

**Comment by zcbenz** [comment]
I'm merging this to #10420.
