### ISSUE TITLE
Tray.displayBalloon dosen't work in win10 

### ISSUE THREAD

**Issue by rzhang228** [electron/electron#11259]
* Electron version:1.7.9
* Operating system:win10

### Expected behavior

there will show a balloon with my option (title and content)

### Actual behavior

nothing happen
### How to reproduce

i have use tray.displayBallon and run it in win10. code like this
  tray.displayBalloon({
    title: '***',
    content: '***'
  });
but it dosen't work.

**Comment by TanninOne** [comment]
Try specifying an icon, I think the bug only happens when no icon is specified.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
