### ISSUE TITLE
video freeze sometimes on Windows 10 16299.19 (fall creators update)

### ISSUE THREAD

**Issue by devtobo** [electron/electron#11251]
* Electron version: 1.7.9
* Operating system: Windows 10 16299.19 (fall creators update)

### Expected behavior
Video autoplay each time I open the application

### Actual behavior
Video freeze on the very first frame sometimes (1/10)

### How to reproduce
git clone git@github.com:hokein/electron-sample-apps.git
edit helloworld/index.html
paste this code:
`
<video width="600" height="400" controls autoplay>
    <source src="https://download.blender.org/durian/trailer/sintel_trailer-480p.mp4"
type="video/mp4">
</video>
`
electron . (many times until the video freeze, even clicking on pause/play won't start the video, but scrolling will update the frame, but still not playing the video).

**Comment by devtobo** [comment]
It happens also when using a local video (file://).
_Not a network issue._

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
