### ISSUE TITLE
Add support for dropping directories

### ISSUE THREAD

**Issue by betamos** [electron/electron#11265]
The current way of supporting drag-and-drop of files is through the HTML5 File api, [but with an additional `path` attribute to the File object](https://electronjs.org/docs/api/file-object). This works as intended when dragging any number of plain files on MacOS.

However, when any of the items dropped is a directory, it is automatically expanded to the files within that directory, recursively.

Example structure:
```
├── topdir   <-- Directory being dragged
│   ├── file-in-topdir
│   └── subdir
│       └── file-in-subdir
```

* Electron version: 1.7.8
* Operating system: MacOS High Sierra

### Expected behavior

I see two possibilities:

1. A single entry containing "/.../topdir" with metadata to know that this is a directory.
2. Each File object is extended with an additional, optional key, `directory`, which contains the path to the directory if and only if the file belonged to a directory during the drag event.

I think 2) is preferable because it would be backwards compatible. It would not be unprecedented since Electron is already extending the File object with `path`

### Actual behavior

File list contains two items:

- /.../topdir/file-in-topdir
- /.../topdir/subdir/file-in-subdir

### How to reproduce

In `renderer.js`:

```
document.body.ondragover = cancel
document.body.ondragenter = cancel

document.body.ondrop = (ev) => {
    ev.preventDefault()
    ev.stopPropagation()
    console.log(ev.dataTransfer.files)
}
```

Drop a directory onto the Electron app window.

### Other platforms

I have not verified this behavior on any other platform than MacOS High Sierra.

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
