### ISSUE TITLE
FIXME: FREEZE in OSX High Sierra with Fn+Left & Fn+Right

### ISSUE THREAD

**Issue by darkguy2008** [electron/electron#11262]
* Electron version: 1.7.9
* Operating system: OSX High Sierra 10.13.1

### Expected behavior

Keystrokes should be captured immediately.

### Actual behavior

All keystrokes, except for the combination of Fn+Left and Fn+Right (Home & End) have a big initial delay. Once the delay is gone, the combo can be repeated in 0.5s time intervals. If the combo is repeated faster than that, the app hangs until all keystrokes have been processed. This delay is ridiculous.

### How to reproduce

Here's a repo you can clone & use: https://github.com/darkguy2008/keystroke-delay-electron

Usage:
```npm install```
```npm start```

Try hitting any key. Events will be printed on screen. Try to press Fn+Left or Fn+Right (I'm using a Macbook Pro) and notice the delay similar to the GIF shown below:

![electron1](https://user-images.githubusercontent.com/6304136/33236994-4cd695b0-d22b-11e7-9728-18c18994533b.gif)

I can't seem to be able to save the Performance profiler results, but you can reproduce the bug. Also, this seems to be happening on my Macbook about a few days ago. Now that I remember, I did run the Onyx tool a few days ago, I did run a few tweaks regarding UI responsiveness but nothing else. I'm suspecting it might have crapped my OSX install, but it doesn't happen globally, only on Electron-related apps.

If anyone else is experiencing the same issue or do you know any way I can be of more help, please speak up! I'm stuck with Sublime Text now as I can't use VSCode, Atom or Brackets due to this :(

Thanks!

**Edit:** I've also discovered that if I plug an external full Apple keyboard, the Home & End keys work correctly. It's the Fn+Left/Right combo (external & internal keyboard) what causes this issue.

**Comment by darkguy2008** [comment]
Nobody? :(

**Comment by JeroenReumkens** [comment]
@darkguy2008 I think I'm experiencing a similar problem. But not sure about the Fn key you are mentioning + CPU usage that causes. 

When I'm typing I'm also experiencing quite an input lag, which is becoming very annoying.The strange thing is that there aren't a lot of other people who seem to have the same issue.

**Comment by darkguy2008** [comment]
@JeroenReumkens thanks for answering!. Well, the high CPU usage comes from Electron-based editors (Brackets, VSCode, Atom) which seem to be hanging waiting for the keystroke to complete. Since my app is a simple test, there's no CPU usage as I'm not doing any extensive work waiting for that keystroke to complete, but the delay & freezing is still there.

Input lag is also there, although not very noticeable on my side. I wish I had the knowledge or instructions on how to debug something like this. I have little C++ experience and I don't get along very well with gdb, so no idea how this chould be debugged in OSX :( 

Since I'm experiencing the problem, I could try to fix it, but I don't know how to debug. Any pointers would be appreciated :)

**Comment by darkguy2008** [comment]
Hi all, just wanted to mention that the problem seemed to be the Onyx app I ran a few days ago before I reported the bug ( https://www.titanium-software.fr/en/onyx.html ) **DON'T RUN IT IN HIGH SIERRA**. It will screw up your install and you'll have a BAD TIME (Undertale reference :P).

I fixed it by running CleanMyMac 3 and running all the maintenance scripts (ticked all checkboxes). Rebooted, and issue got fixed.

This can be closed :D (still, it's an interesting issue to check though). Thanks all for your time & input :)

**Comment by JeroenReumkens** [comment]
Oh my god... This indeed fixed my problem too! 
I immediately bought CleanMyMac and ran it. All Electron apps are at 90% of the speed before High Sierra! 😱

Now I can at least wait until Apple releases a good update for this buggy OS.

Thanks a lot for letting us know @darkguy2008 . Really appreciate it!
