### ISSUE TITLE
 execute bash commands when the app has been packaged

### ISSUE THREAD

**Issue by davidsolorzano20** [electron/electron#11261]
I need to execute this command "./node_modules/gulp/bin/gulp.js serve" when opening the packaged application, when I execute it with npm start it works for me.

**Comment by MarshallOfSound** [comment]
Your app when packaged goes into an ASAR archive, shelling out to paths inside the archive won't work as you expect

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
