### ISSUE TITLE
Creating sessions leaks memory

### ISSUE THREAD

**Issue by PalmerAL** [electron/electron#11260]
(This is a follow-up from #11057).

* Electron version: 1.8.2
* Operating system: MacOS 10.12.6

### Expected behavior

Creating sessions doesn't leak memory

### Actual behavior

Each new session leaks ~200KB of memory in the main process.

### How to reproduce

```
git clone https://github.com/palmerAL/electron-quick-start -b session-memory-leak
cd electron-quick-start
electron .
```

When running the app above, the main process' memory usage starts at ~25 MB, then jumps to ~60 MB when this code runs 5 seconds later:
```
  for (var i = 0; i < 200; i++) {
    var id = Math.random().toString()
    session.fromPartition(id)
}
```

(In #11057, this was thought to be because of permission request handlers, but it turns out that just creating the session is enough to leak memory).

**Comment by PalmerAL** [comment]
It turns out that there's an undocumented ```destroy``` method that fixes most of the memory leak, although sessions still seem to leak a little bit.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
