### ISSUE TITLE
Feature Request: Pass MediaStream object across windows

### ISSUE THREAD

**Issue by gossi** [electron/electron#11275]
In my main window, I do have a canvas, where I want to `captureStream()` and send it to another window and display it there.

* Electron version: 1.7.9
* Operating system: macOS Sierra (10.12.6)

### Expected behavior

Using the `ipcRenderer` to send messages across windows with the captured stream object above as message content, which can be put on a video element in another window.

### Actual behavior

Messages in ipcRenderer are serialized (?) and because of that, the message transporting the stream object either isn't sent or the stream object wouldn't arrive to what it was before upon sending. The result is, a MediaStream object can't be passed across multiple windows in an electron application.

**Comment by MarshallOfSound** [comment]
This is not something I can see us adding support for, if you want to send a media stream across a window boundary you'll either have to write some custom IPC logic to send the raw data or use some kind of RTC connection for sending the stream.

**Comment by gossi** [comment]
Ok, I'm already exploring RTC for this. Can you give a reason, why this won't be supported?

**Comment by codebytere** [comment]
@gossi it's not something that our team will be able to implement in the near future, and since we use our issues tab as the team's backlog, we prefer to only retain issues that are on our immediate roadmap. If you'd like to make a PR for this request we would welcome that but in the meantime I'm going to go ahead and close this.

**Comment by gossi** [comment]
Thanks for explanation, I was already able to learn a bit RTC and got it implemented - thanks.

**Comment by thbaja** [comment]
Hi @gossi, can you elaborate a bit on what you came up with?

**Comment by gossi** [comment]
In short: you setup a RTC connection and use ipcRenderer to exchange signal ids, candidates and sdps. Use one of the RTC tutorials that are around.

**Comment by Ajeey** [comment]
@gossi Hi I am also facing this issue, can you please give a gist of what you've done to achieve this?

**Comment by gossi** [comment]
In short: you setup a RTC connection and use ipcRenderer to exchange signal ids, candidates and sdps. Use one of the RTC tutorials that are around.
