### ISSUE TITLE
protocol.registerStandardSchemes is broken

### ISSUE THREAD

**Issue by alespergl** [electron/electron#11273]
The [`protocol.registerStandardSchemes`](https://electronjs.org/docs/api/protocol#protocolregisterstandardschemesschemes-options) API internally calls Chromium's `url::AddStandardScheme` at a time when it is no longer thread-safe. This fact is flagged by Chromium's DCHECK (when enabled for this API, which it currently isn't)

Let's refactor `protocol.registerStandardSchemes` to make sure that new schemes are only added in [`AtomContentClient::AddAdditionalSchemes`](https://github.com/electron/electron/blob/124667c29b249b5f79c57c8abbf2912157370cc7/atom/app/atom_content_client.cc#L201) and nowhere else. `protocol.registerStandardSchemes` should throw a JS exception when called at the wrong time.

**Comment by sofianguy** [comment]
@alespergl Is this bug present in Electron v2.0.x or later?

**Comment by sofianguy** [comment]
@alespergl we are no longer releasing bug fixes for versions earlier than 2.0.x. Feel free to reopen if you find this issue in versions later than 2.0.x
