### ISSUE TITLE
Enable "ffi" module tests

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#11274]
[ffi module](https://github.com/node-ffi/node-ffi) doesn't support Node.js 9,
so the corresponding test was disabled during the Chromium 62 (Node.js 9) upgrade.
Also the module was removed from the "optionalDependencies" of `spec/package.json`.

Restore the module in the dependencies list and enable the test when ffi supports Node.js 9.

**Comment by hpohlmeyer** [comment]
Related PR: https://github.com/node-ffi/node-ffi/pull/439

**Comment by codebytere** [comment]
ffi specs are now gone.
