### ISSUE TITLE
When launching the application for the first time

### ISSUE THREAD

**Issue by chong0808** [electron/electron#11276]
When launching the application for the first time, double-click it later
Rendering process takes ten seconds to appear before what is the reason,
Feel like going into suspended animation, the main process is activated

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our [comment](https://github.com/electron/electron/issues/11276#issuecomment-347558510). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
