### ISSUE TITLE
Error opening Dexie indexeddb with electron Browserwindow

### ISSUE THREAD

**Issue by der-raist** [electron/electron#11284]
* Electron version: 1.8.2-beta.2
* Operating system: win10

On **windows** the Dexie Framework is unable to open a connection to indexeddb if opened inside a BrowserWindow from electron. On OSX everything works and if you open the link in the system browser you will see a connnection too.

We made a sample to demostrate this issue :

### Expected behavior

indexeddb opens and you will see a "connected!" on the screen.

### Actual behavior

window displays nothing, console displays error.

error opening indexed db with dexie. on osx the window content is "connected" and if you open the url with a brwoser on your choice you will also see a "connected!"

### How to reproduce

start a new browserwindow with electron:

    mainWindow = new BrowserWindow({
    	width: 800,
    	minWidth: 320,
        height: 600,
        minHeight: 480
    });
    
    var url = 'https://www.loesungsmarkt.de/demo/index.html';
	mainWindow.loadURL(url);

Your will find the full electron code here : 
[electron.txt](https://github.com/electron/electron/files/1513851/electron.txt)

Your will find the full code here :
[demo.zip](https://github.com/electron/electron/files/1513846/demo.zip)

![image](https://user-images.githubusercontent.com/11631729/33376902-c9bbc6f4-d50f-11e7-99db-0af00f841d33.png)

**Comment by chong0808** [comment]
no problem 
![111](https://user-images.githubusercontent.com/16454649/33379031-cd545ec4-d551-11e7-804a-2a5c06802f6c.png)
![tim 20171129220800](https://user-images.githubusercontent.com/16454649/33379045-d51992aa-d551-11e7-8c2f-8dc789b680e3.png)

**Comment by trusktr** [comment]
Is this the problem? https://github.com/dfahlander/Dexie.js/issues/271#issuecomment-364038802

I just had that problem, so I made sure I had only one instance if Electron running and that did the trick.

Not sure if it's already been fixed in more recent versions of Electron though.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
