### ISSUE TITLE
Debugging electron processes is not possible via SIGUSR1

### ISSUE THREAD

**Issue by bpasero** [electron/electron#11287]
* Electron version: 1.7.9
* Operating system: macOS 10.13.1

### Expected behavior

Sending any electron process a `SIGUSR1` should enable debugging via the inspector protocol. 

### Actual behavior

Debugging does not enable. 

### How to reproduce

* find the PID of any electron process
* run `kill -USR1 <pid>`

If you try the same with a node application you will see this:

![image](https://user-images.githubusercontent.com/900690/33386128-955725f0-d52a-11e7-963e-ae48c9d536fd.png)

The related node.js issue for this feature is: https://github.com/nodejs/node/issues/8464

It looks like one difference with Electron compared to node.js is that Electron will only start the inspector (in https://github.com/electron/electron/blob/6ba3ee39502728d19913ac5c9b2c2adfba63d569/atom/browser/node_debugger.cc#L48) if `options.inspector_enabled()`. This defeats the purpose because the inspector is needed to listen for the `SIGUSR1` event.

A possible fix would be to always start the inspector but it is not clear what the performance impact would be. There also seems to be [this call](https://github.com/electron/electron/blob/6ba3ee39502728d19913ac5c9b2c2adfba63d569/atom/browser/node_debugger.cc#L39) made only if inspector is enabled:

```javascript
// Use custom platform since the gin platform does not work correctly
// with node's inspector agent
platform_.reset(v8::platform::CreateDefaultPlatform());
```

**Comment by ibash** [comment]
+1

An alternative for me would be to allow enabling the inspector via a js call. My use case is that I want to release a packaged version internally that is debuggable.

**Comment by sofianguy** [comment]
@bpasero we are no longer providing bug fixes for bugs reported earlier than 2.0.x. Feel free to reopen if this is still a bug in later versions.

**Comment by mattbroussard** [comment]
Indeed, this appears to work on 3.0.10 🙌

**Comment by TomasHubelbauer** [comment]
According to microsoft/vscode#67655 this still doesn't work on Windows, so this is not completely fixed.
