### ISSUE TITLE
Update Node to 8.9.1 (LTS)

### ISSUE THREAD

**Issue by hpohlmeyer** [electron/electron#11286]
Since Node 8 has entered long term support, I think it would be nice to update electron as well.
I know the FAQs say

> When a new version of Node.js gets released, we usually wait for about a month before upgrading the one in Electron

but the current Node version of the latest beta is 8.2.1, which was released in July.
Since 8.9.1 is not yet a month old an update to at least 8.5 would be reasonable.

**Comment by codebytere** [comment]
We have a process around node upgrades that can be found in docs and is associated with chromium upgrades. Some information around current work can be found here: https://github.com/electron/electron/pull/11230

**Comment by alexeykuzmin** [comment]
@hpohlmeyer You can try to use Electron built from the _master_, it has Node.js 8.7.0.

**Comment by hpohlmeyer** [comment]
@alexeykuzmin Nice, I will do that for now. Do you already have a schedule for the next beta release?

**Comment by alexeykuzmin** [comment]
@hpohlmeyer Unfortunately no, we don't. Stay tuned )

**Comment by mividtim** [comment]
Why is this branch closed? The latest branch seems like it's going to embed Node 9. The LTS version of Node is 8.9. That is what should be embedded in Electron!
