### ISSUE TITLE
DCHECK on shared_resources_data_source.cc:106

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#11289]
_DCHECK is actually in the libcc, but probably Electron does something weird to trigger it._

```
[17694:1129/072103.910993:FATAL:shared_resources_data_source.cc(106)]
    Check failed: -1 != idr (-1 vs. -1) path: polymer/v1_0/paper-dialog/paper-dialog.html
```

Right now it is simply commented out via a libcc patch:
```diff
-  DCHECK_NE(-1, idr) << " path: " << path;
+  // DCHECK_NE(-1, idr) << " path: " << path;
```

"chrome://resources/..." is Chromium internal "protocol" to access shared resources like libraries, fonts, images, etc. from internal pages. If we get a request to load some Polymer stuff (used on most internal pages of Chromium), it means we are definitely trying to load one of them.
Can it be related to the Chromium PDF viewer?

/cc @alespergl, @deepak1556, @zcbenz

**Comment by deepak1556** [comment]
> Can it be related to the Chromium PDF viewer?

Oh yeah its definitely the pdf viewer https://github.com/electron/pdf-viewer/search?utf8=%E2%9C%93&q=paper-dialog&type= .

Seems like the resource has been removed in 61, will update it to enable the DCHECK.

**Comment by alespergl** [comment]
Oh man, I was searching the Chromium code base like crazy for this `paper-dialog` and noticed that it's missing from their copy of `polymer`. I didn't think Electron has its own copy. 🤦‍♂️
