### ISSUE TITLE
Is it possible to load webview into another webview in electron app

### ISSUE THREAD

**Issue by hakter1** [electron/electron#11296]
* Electron version:
* Operating system:

**Comment by MarshallOfSound** [comment]
This is not currently possible

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
