### ISSUE TITLE
CSS opacity transition causes layout issues

### ISSUE THREAD

**Issue by JamesLarson** [electron/electron#11298]
- Electron 1.7.9
- OS macOS Sierra 10.12.6

The CSS causing the issue:
.dimmed-state{ opacity:0.25;  transition:opacity 0.5s ease; }

expected behavior: when class ".dimmed-state" is added the element's opacity transitions to .25 over .5s

actual behavior: opacity does transition but neighboring dom nodes shift position up or down for the duration of the transition. 

changing the duration of the transition to something like 2s does cause the positioning error to last 2s.

removing "transition:opacity 0.5s ease" resolves issue

changing the transition line to "transition:all 0.5s ease" does not resolve the issue

removing the ease so the line reads "transition: opacity 0.5s" does not resolve the issue

tested other transitions such as:
.width-state{ width:14%;  transition:width 0.5s ease; }
and
.background-state{ background:red;  transition:width 0.5s ease; }
and do not see the issue. It only appears to happen with opacity.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
