### ISSUE TITLE
Am I missing how to perform a conditional build?

### ISSUE THREAD

**Issue by fmarzocca** [electron/electron#11309]
Hi,

In my app I have several code snippets which I need to "polish" before packaging for production (i.e.: web urls, devtools, debug logs, etc). This is becoming a long and annoying exercise and everytime I risk to forget something.

I have tried cross-env, but it is useful only in development to test how tha app will perform in production. I can do this in package.json:

```
 "scripts": {
    "start": "cross-env NODE_ENV=development electron .",
    "start-prod": "cross-env NODE_ENV=production electron .",
```

and check this is my app scripts:

```
if (process.env.NODE_ENV === "production") {
	$webview.src="https://<production.url>";
} else {
	$webview.src="https://<development-url>";
}
```

This is working fine, but cross-env doesn't work with electron-packager. I have tried this:

`"package-mac": "cross-env NODE_ENV=production electron-packager . --overwrite --platform=darwin --arch=x64 --icon=icons/icon.icns --prune=true --out=release-builds",`

but `NODE_ENV` is undefined after the packaging, so it is not a solution.

For sure, I am missing something here, as it should be a way to have a conditional packaging without scrolling the whole code...! :-)

* Electron version: 1.7.9
* Operating system: Mac OSX 10.13.1

**Comment by enlight** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by fmarzocca** [comment]
Hi,

I'm sorry but I was intending this as a feature request.
Best

Fabio
