### ISSUE TITLE
Feature proposal : Take avantage of Chromium "process-per-site" process model

### ISSUE THREAD

**Issue by emmkimme** [electron/electron#11303]
* Electron version: 1.8.x
* Operating system: All

Add a "partitionCache" option for a better support of "process-per-site" option.

### Expected behavior
```js
const ses = session.fromPartition(‘partitionName’, { cache: true, partitionCach : false })
const w = new BrowserWindow({
        width: 400,
        height: 400,
        webPreferences: {
          session: ses
        }
      })
```
There is not "partitionName" folder created in the [userData]/Partitions folder. The session uses the common cache.

### Actual behavior

```js
const ses = session.fromPartition(‘partitionName’, { cache: true })
const w = new BrowserWindow({
        width: 400,
        height: 400,
        webPreferences: {
          session: ses
        }
      })
```
There is a "partitionName" folder created in the [userData]/Partitions folder.

## Chromium process-per-site
The **process-per-site** option of Chromium turn on the ability of Chromium to gather Web pages from the same site/domain in a single renderer process.
In a nutshell, you can have several pages hosted in the same renderer process  (vs having a process per webpage).
[Chromium process models](https://www.chromium.org/developers/design-documents/process-models#2_Process_per_Site)

The mecanism can be fine-tuned and we can even decide which process will host which page (complying with the rule : a process can only manage webpages from the same site/domain).

It is promoted by [OpenFin](https://www.linkedin.com/pulse/openfin-slashes-electron-memory-78-mazy-dar/?trackingId=r0GP%2BeHrZ46aXeI4YwAAxA%3D%3D&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_content%3B9Cq1zjwGTregLYYDCvnhCg%3D%3D&licu=urn%3Ali%3Acontrol%3Ad_flagship3_search_srp_content-object) and intensively used by [Thomson Reuters Eikon](https://financial.thomsonreuters.com/en/products/tools-applications/trading-investment-tools/eikon-trading-software.html) which embeds its own Chromium (CEF/C++)

Purpose is to save resources of the machine and prevent from reaching the limit of number of processes authorized by Chromium.

The challenge is to identify Web pages that can easily share the same process without being impacted too heavily by the performance of having a single process (have the same V8 engine, same thread, same messageLoop…) but this is another story.

## Electron behavior
In fact, this feature is feasible with Electron playing with Electron session/s (do not forget to add --process-per-site in commandline)
Basically you can imagine that a session is equivalent to a process.

So if we write :
```js
const ses = session.fromPartition(‘partitionName’)
const w1 = new BrowserWindow({
        width: 400,
        height: 400,
        webPreferences: {
          session: ses
        }
      })
const w2 = new BrowserWindow({
        width: 400,
        height: 400,
        webPreferences: {
          session: ses
        }
      })

console.log(w1.webContents.getOSProcessId() === w2.webContents.getOSProcessId()) => true
```
Same session, same renderer process.

```js
const ses1 = session.fromPartition(‘partitionName1’)
const w1 = new BrowserWindow({
        width: 400,
        height: 400,
        webPreferences: {
          session: ses1
        }
      })
const ses2 = session.fromPartition(‘partitionName2’)
const w2 = new BrowserWindow({
        width: 400,
        height: 400,
        webPreferences: {
          session: ses2
        }
      })

console.log(w1.webContents.getOSProcessId() === w2.webContents.getOSProcessId()) => false`
```
Different sessions, different renderer processes.

If you want to apply the “page per process” behavior in such mode, you have to create a session per window and even better, create a ‘persist’ session.

## Proposal
Here is the point where I would like to enhance Electron.
Each persist session creates a physical folder in the user cache folder/partitions which is the dedicated cache for this session. As you may imagine, if you open a lot of windows, it will consume a lot of disk place and in term of performance you may have same common files (css, html, js…) downloaded several times in each cache.

I would like to add an optional parameter partitionCache which allows the session to use the global cache.

> 
### `session.fromPartition(partition[, options])`

* `partition` String
* `options` Object (optional)
  * `cache` Boolean - Whether to enable cache.
  * `partitionCache` Boolean (optional) - Whether partition create its own cache or use the global cache. Defaults to true.
>

```js
const ses1 = session.fromPartition(‘partitionName1’, { cache: true, partitionCache : false })
const w1 = new BrowserWindow({
        width: 400,
        height: 400,
        webPreferences: {
          session: ses1
        }
      })
const ses2 = session.fromPartition(‘partitionName2’, { cache: true, partitionCache : false }))
const w2 = new BrowserWindow({
        width: 400,
        height: 400,
        webPreferences: {
          session: ses2
        }
      })
```
Will not create 2 partition folders but will use the global cache !

From my point view, it is a powerful added value for Electron, challenge competitors and may open it to new kind of heavy applications.

## Conclusion
I have already a [MR ](https://github.com/emmkimme/electron/tree/Enh_PartitionCache_Options) ready to be submitted but I would like your feedback first.

Regards

**Comment by emmkimme** [comment]
I'm afraid playing with session is not the best solution. We have to use SiteInstance. I'm about to close this issue and open a new one.

**Comment by MarshallOfSound** [comment]
@emmkimme Please read through and add comments to #6903 instead of raising a new issue, there are multiple architectural issues with changing the process model
