### ISSUE TITLE
[Feature request] Add systemPreferences.registerDefaults

### ISSUE THREAD

**Issue by Anrock** [electron/electron#11305]
There is already systemPreferences.{get,set}userDefault, but it's really difficult to use them without registering default values beforehand - you can't differentiate 'false' value set by user and 'false' as default value. For that Cocoa API also provides `registerDefaults` method, but it's unavailable in Electron.

**Comment by codebytere** [comment]
merged!

**Comment by Anrock** [comment]
Awesome, thanks!
