### ISSUE TITLE
NmPadPlus and NumPadMinus hotkeys doesn't work

### ISSUE THREAD

**Issue by YJDave** [electron/electron#11310]
NumPad hotkeys like NumPadPlus and NumPadMinus doesn't supported.
Using Linux OS.
Similar to issue #3332

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our [comment](https://github.com/electron/electron/issues/11310#issuecomment-348571438). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by YJDave** [comment]
Hey, I don't know how I miss it, sorry for the late response.
**To reproduce the issue:**
* set up zoom hotkeys using accelerators for `+` and ` -`. 
* press `NumPad+` or `NumPad-` for zoom in/out. Nothing happens

_Ideal case_:  all number pad keys should map to the same accelerators.
NOTE: `+` and `-` key works as expected, only `NumPad` keys do not work.
This is implemented in Zulip project [here](https://github.com/zulip/zulip-electron/blob/d7a0b63d62baaa9e680057bf1749193ab3dd9060/app/main/menu.js#L65) for zoom in/out functionality, and it's not working for `NumPadKeys`.

**Comment by sofianguy** [comment]
@YJDave what electron version are you using?

**Comment by YJDave** [comment]
@sofianguy `1.7.9`

**Comment by akashnimare** [comment]
@sofianguy any update on this?

**Comment by BloodShura** [comment]
Electron 3.0.7 here... still doesn't works.

**Comment by codebytere** [comment]
Fixed in `v5.0.0` with this [commit](https://github.com/electron/electron/commit/511dc9a80b540d8dc86b76349e82639efdbaf1dc)
