### ISSUE TITLE
Electron apps change their icon on ubuntu to "unknown"

### ISSUE THREAD

**Issue by dorkbox** [electron/electron#11313]
I'm submitting this issue in response to https://github.com/dorkbox/SystemTray/issues/69, where a native implementation to create AppIndicator system-tray icons in Linux, causes electron apps (so far tested, Slack, Skype, Discord) to lose their icon and default to the "unknown" icon.

It's a very strange issue, and as the author of said library, I can only reproduce this issue on Ubuntu (specifically 16.04), but not Ubuntu derivatives (ie, Xubuntu 16.04).

The point in which the "icon" for electron apps gets removed, is when a Gtk Menu is assigned to a *different* app-indicator, specifically [AppIndicator.app-indicator-set-menu(GtkMenu menu)](http://people.canonical.com/~dpm/api/lts/libappindicator/libappindicator-app-indicator.html#app-indicator-set-menu). If the menu is never assigned to the AppIndicator, the ElectronApp AppIndicator icons don't break (but naturally, there is no menu for the other app, since it's menu was not set).

It's very strange, and it only happens with electron apps and not other applications. I've spent the past 2 weeks trying to figure out what might be causing it, but alas - I'm coming up empty. 

This might not even be an Electron issue -- it might even be a library that the project is using, but I am unfamiliar with the internals of Electron to be able to suggest what that might be.

* Electron version: UNKNOWN
* Operating system: UBUNTU 16.04 Dekstop

### Expected behavior

Electron AppIndicator icons do not get change by an entirely different application. 

### Actual behavior

AppIndicator icon changes and defaults to the "unknown" icon when the SystemTray application starts.

An example: the two broken icons are Slack and Skype. On startup they were correct, but after the SystemTray app was started (the "green train" icon) those icons became the "unknown" icon. This also happens with Discord.
![screenshot-tray](https://user-images.githubusercontent.com/11839070/32564497-59aec582-c4ac-11e7-8f63-a1b2166c2ce1.png)

### How to reproduce

Install [Slack](https://slack.com/downloads/linux), [Skype](https://www.skype.com/en/get-skype/), or [Discord](https://discordapp.com/) into a stock Ubuntu 16.04 Dekstop. A VM will reproduce this error.
Install Java 1.8 (`sudo apt-get install openjdk-8-jre`)
Run the attached Java .jar file (`java -jar system_tray_3.11_normal.jar`)

**Please note:** Yes, this is Java. No, the AppIndicator is not Java - it is the native invocation of methods being called via Java using [JNA](https://github.com/java-native-access/jna), using the same API as [any other C application would use](https://github.com/dorkbox/SystemTray/blob/master/test/example.c).

[system_tray.zip](https://github.com/electron/electron/files/1523127/system_tray.zip)
[repo](https://github.com/dorkbox/SystemTray)

**Comment by sofianguy** [comment]
Is this bug present in Electron v2.0.x or later?

**Comment by sofianguy** [comment]
You can use https://github.com/electron/fiddle for testing in different versions

**Comment by codebytere** [comment]
Closing due to lack of follow-up from author.
