### ISSUE TITLE
Provide a replacement for PPAPI

### ISSUE THREAD

**Issue by rcombs** [electron/electron#11322]
Chromium is deprecating PPAPI, which is currently the only supported mechanism (that I'm aware of) of integrating native graphical content into an Electron app. Electron should provide some sort of replacement for it.

One mechanism I've looked into involves calling getNativeView or getNativeWindowHandle and inserting a NSView/Window/HWND in the hierarchy beneath Chromium's content. This works to some degree, but it's hacky and unstable (for instance, I'm currently seeing crashes on window resize in OpenGL code when I try this, which might be on my end, but it's hard to tell given lack of support). It also doesn't provide a way to integrate the native view with web content, though my use-case could probably live with that if this functionality was documented and supported.

**Comment by miniak** [comment]
The replacement for PPAPI is WebAssembly

**Comment by miniak** [comment]
Similar to https://github.com/electron/electron/issues/10547
