### ISSUE TITLE
Black window if you set thickFrame to true in 1.8.2, 1.8.1 or 1.7.9

### ISSUE THREAD

**Issue by kirilpopov** [electron/electron#11325]
* Electron version: 1.8.2, 1.8.1, 1.8.0, 1.7.9
* Operating system: Windows 10 17025.1000

### Expected behavior

If you create a new window and set thickFrame property to true , the window will not have the standard Windows 10 shadow around it.

### Actual behavior

The window appear as black rectangle

![black-window](https://user-images.githubusercontent.com/6021897/33542146-71dedcb8-d8da-11e7-8699-0e04338c0fd3.PNG)

### How to reproduce

1. Create a new window, pass options with thickFrame=true
2. The window does not appear

Works fine on version 1.6.11.
Does not work after upgrading to 1.8.2 (the problem is also there with 1.7.9, 1.8.0, 1.8.1)

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
