### ISSUE TITLE
Typescript Definitions `Session.fromPartition()` `options` not marked optional

### ISSUE THREAD

**Issue by eugirdor** [electron/electron#11333]
The documentation for `Session.fromPartition()` shows the second argument, `options` as optional <http://electron.atom.io/docs/api/session>, but `electron.d.ts` has it defined as required

```typescript
static fromPartition(partition: string, options: FromPartitionOptions): Session;
```

* Electron version: 1.7.9
* Operating system: N/A

### Expected behavior

Should be able to omit second argument from `Session.fromPartition()` without compile errors.

### Actual behavior

Code compiles with the following error:

```
error TS2554: Expected 2 arguments, but got 1.
```

### How to reproduce

```typescript
import { session } from 'electron'

session.fromPartition('foo') // error TS2554: Expected 2 arguments, but got 1.
```

**Comment by MarshallOfSound** [comment]
This has been fixed in latest master so newer releases of Electron should work 👍 

https://github.com/electron/electron/commit/2edf4da8590b257a9bd9695516a5256586d6dcfd#diff-9a3021541e4f1fb544254a6f7abaadef
