### ISSUE TITLE
executeJavaScript callback/promise not working

### ISSUE THREAD

**Issue by nirewen** [electron/electron#11337]
I'm not sure how to use executeJavaScript properly, but I think I am using it correctly.

I'm creating a Netflix wrapper. I can't set `nodeIntegration` to `true`, otherwise when I open an episode it will be blank. I can't use IPC too.
Also, I'm importing Widevine module so that the videos can show in the app.

I created a function to get variables from the loaded page, such as location.pathname and netflix, both in `window`, global variables.
But, using the executeJavaScript function doesn't seem to return anything (or even run the callback/promise).

Here's my code:
```javascript
const {BrowserWindow, app} = require('electron');
const widevine = require('electron-widevinecdm');

widevine.load(app);

let mainWindow,
    WindowSettings = {
        backgroundColor: '#000',
        useContentSize: false,
        autoHideMenuBar: true,
        resizable: true,
        center: true,
        alwaysOnTop: false,
        frame: true,
        title: 'Netflix',
        icon: __dirname + '/netflix.ico',
        webPreferences: {
            nodeIntegration: false,
            plugins: true
        }
    };

function getData() {
    mainWindow.webContents.executeJavaScript(`
        console.log('fired'); // logging just to see that the code is running (it is)
        (function () {
            return {
                path: window.location.pathname,
                netflix: window.netflix
            }
        })();
    `, false, (res) => { // tried using promise too
        /*
            doesn't log anything. 
            I don't know if it's firing or not, or where it logs `res`, 
            but I don't see anything in app's console and node's console.
        */
        console.log(res);
    });
}

app.on('ready', () => {
    mainWindow = new BrowserWindow(WindowSettings);
    mainWindow.maximize();
    mainWindow.loadURL("http://www.netflix.com/");
    mainWindow.webContents.openDevTools();
    mainWindow.webContents.on('dom-ready', e => {
        getData();
    });
});
```
I also looked at other codes, some examples on getting variables like that, using async and await. Didn't work either.

I need someone to point me to the right direction...

**Comment by sofianguy** [comment]
@nirewen Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
