### ISSUE TITLE
SideBySide Issue - Windows 10 x64

### ISSUE THREAD

**Issue by dr3x** [electron/electron#11339]
* Electron version:
electron-v1.7.9-win32-x64
* Operating system:
Windows 10 x64

### Expected behavior
SideBySide error attempting to launch; same issue with VS Code; writeups:<br/>

### Diagnosing with SxsTrace points me in the direction of the manifest

`SxsTrace Trace -logfile:SxsTrace.etl`
`-->run the erroring app here...`
`sxstrace Parse -logfile:SxSTrace.etl -outfile:SxSTrace.txt`

`-->here is the result:`
`INFO: Parsing Manifest File C:\Program Files\Microsoft VS Code\Code.exe.`
`	INFO: Manifest Definition Identity is (null).`
`	INFO: Reference: Microsoft.Windows.Common-Controls,language="&#x2a;",processorArchitecture="&#x2a;",publicKeyToken="6595b64144ccf1df",type="Win32",version="6.0.0.0"`
`	ERROR: The setting http://schemas.microsoft.com/SMI/2011/WindowsSettings^disableWindowFiltering is not registered.
ERROR: Activation Context generation failed.`

[StackOverflow](https://stackoverflow.com/questions/47502917/cant-run-visual-studio-code-1-18-1-0-sidebyside)

[VS Code Repo](https://github.com/Microsoft/vscode/issues/39161)

### Atom Manifest Oddness
Found the manifest with the settings above in this file:
electron/atom/browser/resources/win/atom.manifest

Wondering if there is a typo in the xml of the manifest; based on the link below, maybe there should only be a namespace on the outside wrapper and the date should be 2011 instead of 2005?
(see the link below, searching under disableWindowFiltering):

https://msdn.microsoft.com/en-us/library/windows/desktop/aa374191%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396

`sigcheck.exe -m code.exe`

	<asmv3:application xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">
		<asmv3:windowsSettings xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
			<dpiAware>true/pm</dpiAware>
			<disableWindowFiltering xmlns="http://schemas.microsoft.com/SMI/2011/WindowsSettings">true</disableWindowFiltering>
		</asmv3:windowsSettings>
	</asmv3:application>

**Comment by dr3x** [comment]
More info:
Was able to compile locally and when I removed the disableWindowFiltering line from the manifest was able to run successfully.  So that seems to be causing the problem.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
