### ISSUE TITLE
MacOS animate 2 things at once

### ISSUE THREAD

**Issue by DusterTheFirst** [electron/electron#11332]
```ts
let {width: winx, height: winy} = Electron.screen.getPrimaryDisplay().size        
window.setPosition((winx/2) - (1200/2), (winy/2) - (800/2))
window.setSize(1200, 800, true);
```

### Expected behavior
A small loading window to expand (in all directions) into the larger main window

### Actual behavior
http://recordit.co/AzFcPi9y38

**Comment by sofianguy** [comment]
Hi @DusterTheFirst, can you please provide us with the following for us to better help you:
- Electron version
- operating system
- steps to reproduce issue

**Comment by DusterTheFirst** [comment]
I have actually figured out what was wrong, instead of changing the size, if i use 'window.maximize();` it achieves my goal
