### ISSUE TITLE
Non-conventional UI with Electron

### ISSUE THREAD

**Issue by majid4466** [electron/electron#11336]
I have an app in the making which is basically a web-radio player and I would like its UI to resemble a vantage tube radio.
Is it possible to create UI like this with Electron?
![windows-media-player_bys4](https://user-images.githubusercontent.com/72784/33582980-3f4c876c-d96d-11e7-944c-3d5f45ffbb14.jpg)

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by MarshallOfSound** [comment]
Making that kind of UI should be possible, HTML/CSS is very easy to make wild and wonderful things 👍

**Comment by majid4466** [comment]
Sorry for posting as an issue. As a (lame) defense, before posting I did check the labels and found *question* as a possible label and thought it would be OK.
