### ISSUE TITLE
Devtools will not appear with menubar app

### ISSUE THREAD

**Issue by naheller** [electron/electron#11335]
* Electron version: 1.7.3
* Operating system: macOS 10.13.1

I am building an Electron app using React that lives up in the menubar. For some reason, I cannot get devtools to appear! Since this is a menubar app, I need the devtools to appear detached. My code is shown below.

`main.js`:

    app.on('ready', () => {
      createTray()
      createWindow()
    })

    const createTray = () => {
      tray = new Tray(icon)
      tray.on('click', toggleWindow)
    }

    const createWindow = () => {
      window = new BrowserWindow({
        width: 387,
        height: 359,
        show: false,
        frame: false,
        resizable: false,
        fullscreenable: false,
        transparent: true,
        webPreferences: {
          backgroundThrottling: false
        }
      })

      let indexPath;
      if ( dev && process.argv.indexOf('--noDevServer') === -1 ) {
        global.developmentMode = true;
        indexPath = url.format({
          protocol: 'http:',
          host: 'localhost:8080',
          pathname: 'index.html',
          slashes: true
        });
      } else {
        global.developmentMode = false;
        var httpServer = require('http-server');
        var webRoot = path.join(__dirname, 'dist');
        server = httpServer.createServer({
          root: webRoot,
          robots: true,
          headers: {
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Credentials': 'true'
          }
        });
        server.listen(15426);
        indexPath = url.format({
          protocol: 'http:',
          hostname: 'localhost',
          port: '15426',
          pathname: 'index.html',
          slashes: true
        });
    }
      window.loadURL(indexPath)
      window.openDevTools(); // this is where I thought to open devtools
    }

    const toggleWindow = () => {
      if (window.isVisible()) {
        window.hide()
      } else {
        showWindow()
      }
    }

    const getWindowPosition = () => {
      const windowBounds = window.getBounds()
      const trayBounds = tray.getBounds()

      // Center window horizontally below the tray icon
      const x = Math.round(trayBounds.x + (trayBounds.width / 2) - (windowBounds.width / 2))

      // Position window vertically below the tray icon
      const y = Math.round(trayBounds.y + trayBounds.height)

      return {x: x, y: y}
    }

    const showWindow = () => {
      const position = getWindowPosition()
      window.setPosition(position.x, position.y, false)
      window.show()
      window.focus()
    }

Your advice is appreciated!

**Comment by MarshallOfSound** [comment]
Because your window is hidden and transparent you will need to explicity tell Electron to open dev tools in a detached state.

`openDevTools({ mode: 'detach' })`

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
