### ISSUE TITLE
Unexpected end of JSON input while parsing near '...chrome-launcher":"^0.'

### ISSUE THREAD

**Issue by bestmomo** [electron/electron#11348]
Hello,

I have an issue when installing electron with `npm install electron` on Windows x64

It was working some days ago and now I have this issue:

...
npm http fetch GET 304 https://registry.npmjs.org/ajv 277ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/har-schema 287ms (from cache)
npm verb stack SyntaxError: Unexpected end of JSON input while parsing near '...chrome-launcher":"^0.'
npm verb stack     at JSON.parse (<anonymous>)
npm verb stack     at parseJson (C:\Users\Maurice\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\node_modules\json-parse-better-errors\index.js:7:17)
npm verb stack     at consumeBody.call.then.buffer (C:\Users\Maurice\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\node-fetch-npm\src\body.js:96:50)
npm verb stack     at <anonymous>
npm verb stack     at process._tickCallback (internal/process/next_tick.js:188:7)
npm verb cwd E:\laragon\www\electron
npm verb Windows_NT 10.0.15063
npm verb argv "E:\\laragon\\bin\\nodejs\\node.exe" "C:\\Users\\Maurice\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "electron" "--verbos"
npm verb node v8.9.1
npm verb npm  v5.5.1
**npm ERR! Unexpected end of JSON input while parsing near '...chrome-launcher":"^0.'**
npm verb exit [ 1, true ]

**Comment by bestmomo** [comment]
No issue on Electron, I cleaned my npm cache and now it's ok. I think this sentence in npm documentation is a bit false:

> All data that passes through the cache is fully verified for integrity on both insertion and extraction. Cache corruption will either trigger an error, or signal to pacote that the data must be refetched, which it will do automatically. For this reason, it should never be necessary to clear the cache for any reason other than reclaiming disk space, thus why clean now requires --force to run.

**Comment by iamblue** [comment]
+1 same issue
