### ISSUE TITLE
quitAndInstall() doesn't work in messagebox callback if parent provided

### ISSUE THREAD

**Issue by scottnonnenberg** [electron/electron#11346]
If the messageBox doesn't have a parent, then the direct `quitAndInstall()` call works properly. As soon as the parent is added it stops working.

Signal Desktop ran into update problems due to these changes: https://github.com/WhisperSystems/Signal-Desktop/pull/1795/commits/a0744ad4b657d2c8ed06b5acafcd35f7ca0d2508#diff-9e4b95f4fc2eb918f52051a5ea0583f0R41

The workaround introduces a `setTimeout()` call: https://github.com/WhisperSystems/Signal-Desktop/pull/1866/files

Electron versions: `1.6.15` and `1.7.9`
OS: MacOS `11.x` and `12.x` (does not repro on Windows 10)

_Edit_: Changed `1.6.16` to `1.6.15`

**Comment by scottnonnenberg** [comment]
Prior art: https://github.com/electron/electron/issues/6345#issuecomment-271055970

**Comment by sofianguy** [comment]
Does this issue persist on a later version of Electron, such as 1.8 or 2.0.0?

**Comment by DEDaniel** [comment]
@sofianguy for me this is still an issue. Removing the parent from the windows solved it for now.

Electron version: `1.8.2`
OS: `Windows 7`

**Comment by codebytere** [comment]
Given that there exist workarounds for this, and that this isn't currently on our roadmap, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR!
