### ISSUE TITLE
Notification is not working on widnows 10 16299.64

### ISSUE THREAD

**Issue by webrtcn** [electron/electron#11340]
```
import { app, Notification } from 'electron';
app.on('ready',() => {
  setInterval(() => {
    let nt = new Notification({
      title:"test",
      body: "body"
    });
    nt.show()
    console.log("Notification show.")
  }, 3000); 
})
```

**- Electron@1.8.2 beta3**
**- Windows 10  Pro x64 16299.64 en-us**

**Expected behavior**

New notifications should open every 3 seconds.

**Actual behavior**

Nothing happens

Notification is not working  on widnows 10 16299.64,  darwin is fine.

**Comment by webrtcn** [comment]
https://github.com/electron/electron/issues/10864

**Comment by abardik** [comment]
Thanks a lot! It works.

**Comment by alansunley** [comment]
Appear to have a similar issue. Although it is HTML5 notifications.

No changes were made to the app and notifications suddenly stopped working. I think after a Windows update. 

Windows 10 version 16299.192

The app has permissions in the OS to display notifications. I tried setting AppUserModelId, to no avail.

**Comment by fjramirez1987** [comment]
I have tried all the forms and I do not have to make it work.

I am using windows 10 and the code in the main.js:

setInterval (() => {
app.setAppUserModelId ("appid");
leave nt = new notification ({
title: "test",
body body "
});
nt.show ()
}, 5000);

It does not show any error, but it does not show the notification either.

What can be the cause? The operating system configuration?
