### ISSUE TITLE
App web content obscured by opaque Mac OS window appears to cause DOM not to be re-rendered until app is brought to foreground again

### ISSUE THREAD

**Issue by paulshapiro** [electron/electron#11347]
* Electron version: 1.7.9 (been seeing this bug since last spring though)
* Operating system: MacOS 10.12 and 10.13

### Expected behavior

In our app (https://github.com/mymonero/mymonero-app-js), if the user goes idle, we must lock down the application for security purposes. So when the app is brought back to the foreground and it has not re-rendered, it may be displaying sensitive information unless the DOM has re-rendered to reflect the fact that a password entry screen has since been displayed in the DOM. 

### Actual behavior

For a split second, the old, sensitive content is displayed in the app. Then a re-rendering appears to occur and the "enter password" screen is reflected.

### How to reproduce

You can repro this 100% of the time on MacOS by cloning the mymonero-app-js repo, running (detailed installation and run steps in Readme), setting up a wallet (so you are asked for a password), entering your pw, and then:

Set your idle time low, to like 5s, so you don't have to wait long, then place the MyMonero desktop app window behind another opaque window.. then after it must have gone idle, cmd-tab back into the app. You should see 2, where the unlocked content is visible for what must be only one (?) frame.

Funny enough this does not happen when the app is obscured by a transparent window (such as Terminal), which leads me to strongly suspect again this is some (flaw or lacking support for the) interaction between Electron/Chrome and the rendering system/Quartz.

**Comment by paulshapiro** [comment]
One of our users and open source design contributors, @tficharmers, adds the following:

> I tried doing what you mentioned above but it didn't work. However, if I get a 3rd window and give that focus (remove focus from the window that is covering the app), then I can reproduce it. Also, if you hit Mission Control, the delay until it switches back to the password screen, is longer than using CMD + Tab switching.

**Comment by MarshallOfSound** [comment]
Can you make a slightly more minimal reproduction sample, I don't want to clone and go through setup of an entire app to try repro this 😄 Preferably something based off of [electron-quick-start](https://github.com/electron/electron-quick-start) with minimal changes.

**Comment by paulshapiro** [comment]
LOL sorry it's so hard to install. Everyone usually gets tripped up on installing Electron.

Ok, instead, I will take 10x as long to build a new project. :D I guess that has some merit for you in case the bug turns out to actually exist.

**Comment by paulshapiro** [comment]
Alrighty, didn't take me that long actually. Just pop this in https://github.com/electron/electron-quick-start `renderer.js`. 

You'll need a quick eye to spot it but I tried to make it as visible as possible.

```setTimeout(
	function()
	{
		const layer = document.createElement("div")
		layer.style.backgroundColor = "black"
		layer.style.width = "99999px"
		layer.style.height = "99999px"
		document.body.appendChild(layer)
	},
	5 * 1000
);```

Thank you very much!
Paul

**Comment by MarshallOfSound** [comment]
I played around with it a bit but I couldn't really see the effect you're describing, I'd recommend disabling `backgroundThrottling` and seeing if that helps 🤔

**Comment by paulshapiro** [comment]
Tried that a long time ago :) Tried a bunch of other things too. No joy.

To confirm, I disabled `backgroundThrottling` in the sample app and reproduced the effect.

Have already had a handful of people reporting it and this is on a developer preview version alone.

You know, it sounds suspiciously like this issue… https://github.com/electron/electron/issues/9567

Had you seen that issue before?
Do you suppose it is connected?

Thank you!

**Comment by paulshapiro** [comment]
@MarshallOfSound  Could you recommend another dev or tester on the Electron team who would be willing to try to repro the issue? We sure put in our best effort on this one.

**Comment by paulshapiro** [comment]
Been 11 days… This is kinda concerning :\

**Comment by paulshapiro** [comment]
Hey guys,

Is Electron still being maintained?

I was thinking all this time that the result here was my fault for being inappropriately snarky after a long day in my first comment…  but I've been hearing some scary stuff on the 'net… stuff like this: 

https://blog.ethereum.org/2017/12/15/security-alert-chromium-vulnerability-affecting-mist-browser-beta/ 

Ours is also a very security sensitive application so we unfortunately have no margin for error.

We obviously didn't expect GitHub to disappear anytime soon so we went with Electron a year ago because we figured GitHub would be maintaining it because we figured they wanted people using the framework. But I'm starting to wonder if I'm being too much of a burden with this app instead.

Thanks
Paul

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by paulshapiro** [comment]
hi @sofianguy definitely still seeing this under Electron 3.0

**Comment by paulshapiro** [comment]
and thanks for the follow-up!!

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
