### ISSUE TITLE
Error Launching App

### ISSUE THREAD

**Issue by SebOuellette** [electron/electron#11343]
I installed electron using npm (npm install -g electron --save-dev --save-exact) with the electron package in the folder already only. I then created the main.js and index.html like instructed, however every time I launch it (electron . in console) I get an error. It is a vbs window that says
Error launching app
Unable to find Electron app at C:\Users\{user}\Dropbox\Atom-Projects\VNode

Cannot find module 'C:\Users\{user}\Dropbox\Atom-Projects\VNode'

Any help? :/

**Comment by Younger-Peng** [comment]
Did you specify the main field in package.json?
