### ISSUE TITLE
Issue with messaging with extension

### ISSUE THREAD

**Issue by ihteandr** [electron/electron#11341]
* Electron version: v1.7.9
* Operating system: Windows 10 Pro.

### Expected behavior
Get messaging work

### Actual behavior
Messaging doesn't work

### How to reproduce

Can't organize messaging between content script and backend script
-----------Content----------
chrome.extension.onMessage.addListener(function(request) {
    console.log('request', request);

});
chrome.extension.sendMessage({data: 'test'})
-----------Backend------------
chrome.extension.onMessage.addListener((request, sender, sendResponse) => {
    return sendResponse({data: 'ok'});
});
P.S. also no way to understand what happens on backend

--------------MANIFEST---------------------
{
   "background": {
      "scripts": [ "background.js" ]
   },
   "content_scripts": [ {
      "all_frames": true,
      "match_about_blank": true,
      "js": [
         "script.js"
      ],
      "matches": [ "\u003Call_urls>" ],
      "run_at": "document_end"
   } ],
   "content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'",
   "description": "Fullscreen on-screen virtual keyboard for touch screen devices",
   "icons": {
      "128": "keyboard.png",
      "16": "keyboard.png",
      "48": "keyboard.png"
   },
   "manifest_version": 2,
   "name": "Virtual Keyboard",
   "options_page": "options.html",
   "page_action": {
      "default_icon": "buttons/keyboard_2.png",
      "default_popup": "toggle.html",
      "default_title": "Virtual Keyboard Toggle"
   },
   "permissions": [ "tabs", "<all_urls>" ],
   "update_url": "https://clients2.google.com/service/update2/crx",
   "version": "1.11.1",
   "web_accessible_resources": [
      "legacy/style.css",
      "legacy/keyboard*.html",
      "new/keyboard*.html",
      "new/style.css",
      "options.js",
      "toggle.html",
      "toggle.js",
      "icons/*",
      "buttons/*"
   ]
}

**Comment by MarshallOfSound** [comment]
@ihteandr Is there a minimal example which works in chrome but doesn't in Electron

**Comment by ihteandr** [comment]
@MarshallOfSound yes your are right, I tried so many examples of this and miss possible workings
-----------------------Backend--------------------
chrome.extension.onMessage.addListener((request, sender, sendResponse) => {
return sendResponse({data: 'ok'});
});
----------------------Content---------------------------
chrome.extension.sendMessage({method: "loadKeyboardSettings"}, function(response){
	console.log('response', response);
});
this one also doesn't work

**Comment by MarshallOfSound** [comment]
@ihteandr As this isn't a bug in Electron rather an issue with your code can you please ask for help in one of our Communities (Slack, Forum, Etc.) or on Stackoverflow 😄

**Comment by ihteandr** [comment]
I checked in in chrome and it's worked

**Comment by stewartlord** [comment]
@MarshallOfSound Any suggestions on how to fix this? I don't mind making a PR if you can point me in the right direction
