### ISSUE TITLE
White screen, no indication of what went wrong

### ISSUE THREAD

**Issue by atrauzzi** [electron/electron#11352]
* Electron version: 1.7.9
* Operating system: OSX El Capitan

### Expected behavior

My app should run (as it does on Windows)

### Actual behavior

White screen and this message in my terminal:

```
2017-12-05 22:27:44.791 Electron Helper[2610:59470] Couldn't set selectedTextBackgroundColor from default ()
```
I don't get any output in the browser console, doesn't even seem like it's loading my html.

### How to reproduce

https://github.com/atrauzzi/gerty

```
yarn install
yarn develop
```

Running my app as an ASAR results in the same.  If desired, you can generate the ASAR by running:

```
yarn asar
```

**Comment by codebytere** [comment]
We can try to debug this if you can provide a simpler repro, but this app is somewhat complex and without a reliable minimal repro it's very hard to know that this behavior is resultant of electron itself and not some error within your app.

**Comment by atrauzzi** [comment]
Any chance the fact that it works on Windows is enough to dig in?

My issue is that I can't reproduce the issue in a smaller example as I'm not sure what it is...

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
