### ISSUE TITLE
checkForUpdates fails on 1.7.9 and up on Windows

### ISSUE THREAD

**Issue by etyp** [electron/electron#11351]
* Electron version: 1.7.9 (also happens on 1.8.2-beta.* releases)
* Operating system: Windows 10

### Expected behavior
Upon opening the application and calling `autoUpdater.checkForUpdates()`, either `update-available` or `update-not-available` event should be called.

### Actual behavior
An error event is emitted after `squirrelUpdate.checkForUpdate`. See error below:

```
Error: Command failed: 4294967295 
 
    at AutoUpdater.emitError (C:\Users\IEUser\AppData\Local\Hive\app-1.3.2\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:58:24) 
    at squirrelUpdate.checkForUpdate (C:\Users\IEUser\AppData\Local\Hive\app-1.3.2\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:34:21) 
    at C:\Users\IEUser\AppData\Local\Hive\app-1.3.2\resources\electron.asar\browser\api\auto-updater\squirrel-update-win.js:89:14 
    at ChildProcess.<anonymous> (C:\Users\IEUser\AppData\Local\Hive\app-1.3.2\resources\electron.asar\browser\api\auto-updater\squirrel-update-win.js:71:14) 
    at emitTwo (events.js:106:13) 
    at ChildProcess.emit (events.js:194:7) 
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12) 
```

I suspect that it happens somewhere around [here](https://github.com/electron/electron/blob/master/lib/browser/api/auto-updater/auto-updater-win.js#L32) since the `checking-for-update` event is called (I'm logging it) right before the error event is emitted.

I can also confirm that the exact same build works using Electron 1.6.8, but breaks in the same place on 1.7.9 and above. There are no issues with autoUpdater on my Mac builds though.

### How to reproduce
Build using either Electron Builder or Electron Windows Installer from OSX Sierra 10.12.6 with Electron version 1.7.9 with autoUpdater configured (feed url set and `autoUpdater.checkForUpdates()` called).

### Notes
The app I'm building is already on latest version and feed url is 100% working since I can revert to Electron 1.6.8 and not have this error thrown.

**Comment by MarshallOfSound** [comment]
>  from OSX Sierra 10.12.6 

If I had to guess this is your problem, I know the `autoUpdater` stuff works on `1.7.9` and higher because I am using it in prod at that version and have updated things successfully 😄 Trying building your installer / updater on a Windows machine 😄

**Comment by elm2178** [comment]
I had this same issue building on windows for version `1.7.9`. When I revert back to version `1.6.8` I no longer get the "Command failed:" error.

**Comment by mraulim** [comment]
@elm2178 Looks like Squirrel distributed with your application doesn't support --checkForUpdate. 

https://github.com/electron/electron/commit/6442e6b5e887deadadfc8e4708525ae8c910f206#diff-3be9af19b294930d62ccb2c67984b0da

**Comment by vojtatranta** [comment]
Experiencing exact same issue. https://github.com/avocode/avocode/issues/1828#issuecomment-359756092

**Comment by jakubzitny** [comment]
Any update on this issue @MarshallOfSound?

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
