### ISSUE TITLE
Design Preamble Mac OS X Mas

### ISSUE THREAD

**Issue by hostenvoy** [electron/electron#11369]
I recently packaged my app for MAC Store and was rejected. Below is the message sent to me by review team. When i testing using development mode everything works fine but I can't picture where i am getting something wrong. Any idea would be appreciated.

**Apple Review team message:**

Design Preamble

The user interface of your app is not consistent with the macOS Human Interface Guidelines.

Specifically, we found that when the user closes the main application window there is no menu item to re-open it.

Next Steps

It would be appropriate for the app to implement a Window menu that lists the main window so it can be reopened, or provide similar functionality in another menu item. macOS Human Interface Guidelines state that "The menu bar [a]lways contains [a] Window menu".

Alternatively, if the application is a single-window app, it might be appropriate to save data and quit the app when the main window is closed.

For information on managing windows in macOS, please review the following sections in Apple Human Interface Guidelines:

* The Menu Bar and Its Menus
* The Window Menu
* The File Menu
* Clicking in the Dock
* Window Behavior

Please evaluate how you can implement the appropriate changes, and resubmit your app for review.

**End of message**

All suggestions are welcomed.
Thanks in advance.

**Comment by pronebird** [comment]
Stackoverflow would be more appropriate place for that kind of issues.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
