### ISSUE TITLE
Build issues on High Sierra and latest Xcode

### ISSUE THREAD

**Issue by CapOM** [electron/electron#11363]
Hello, just a quick question before providing more details and logs, what is the recommended electron branch to build both electron and libchromiumcontent from sources on osx High Sierra with latest Xcode 9.2 ? Thx

**Comment by MarshallOfSound** [comment]
@CapOM Don't building using Xcode 9.2, you should use Xcode 8.2 to avoid issues.  If you already have 9.2 installed you can install older versions of the SDK manually into your current Xcode install.

See the SDK section in the build guide.  https://github.com/electron/electron/blob/master/docs/development/build-instructions-osx.md#macos-sdk

**Comment by MarshallOfSound** [comment]
Closing as a question
