### ISSUE TITLE
showItemInFolder opens primary disk on windows

### ISSUE THREAD

**Issue by vasyl-shumskyi** [electron/electron#11362]
Hello,

`showItemInFolder` opens primary disk on `win32` instead of highlighting item in the folder. 
Tried on `win7` and `win10` with latest electron `1.7.9`

On Mac its working as expected. Didn't test on Linux yet. 

```
const { shell } = require('electron')  
shell.showItemInFolder(filepath)
```

**Comment by vasyl-shumskyi** [comment]
The bug was on my end. Sorry.. Looks like backslashes needed to be escaped. Since path like `C:\cygwin\Cygwin.ico` will open just primary disk 'C:` We need to use `C:\\cygwin\\Cygwin.ico`

**Comment by VishwasShashidhar** [comment]
Windows & it's conventions, what a pain :-(
