### ISSUE TITLE
Text rendering artifacts

### ISSUE THREAD

**Issue by RazrFalcon** [electron/electron#11361]
Both VS Code and Atom has a text rendeing artifacts:

Context menu:
![2017-12-06-143902_3840x2160_scrot](https://user-images.githubusercontent.com/725494/33662521-b47623c2-da94-11e7-9b83-fe33dc5229bf.png)

VS Code:
![1512563667](https://user-images.githubusercontent.com/725494/33662522-b491e09e-da94-11e7-9ad0-60f25d20f4c4.png)

Atom:
![1512564160](https://user-images.githubusercontent.com/725494/33662523-b4b12d3c-da94-11e7-8e6b-583aaa38be9c.png)

- This bug appears only in the Electron based apps.
- It's font independent (all font looks like this).
- It's present even in v1.4.6. So it's probably a dependency bug.

* Electron version: 1.7.9
* Operating system: Gentoo Linux

**Comment by MarshallOfSound** [comment]
See https://github.com/electron/libchromiumcontent/issues/384

There are PR's in flight to fix this :+1:
