### ISSUE TITLE
menu.popup() doesn't accept the "async" option anymore.

### ISSUE THREAD

**Issue by romaincointepas** [electron/electron#11376]
* Electron version: fails only on 1.8.2-beta.2, 1.8.2-beta.3 (works on 1.8.2-beta.1)
* Operating system: macOS 10.13.2

### Expected behavior

Calling `menu.popup({async: true})` from the main or renderer process should work (it does in versions 1.8.2-beta.1 and 1.7.9 and below).

### Actual behavior

When calling `menu.popup({async: true})` with 1.8.2-beta.2 and 1.8.2-beta.3, it throws the following error:

From main process:
`Uncaught Exception: TypeError: Error processing argument at index 0, conversion failure from #<Object>`

From renderer process:
`Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Error processing argument at index 0, conversion failure from #<Object>`

### How to reproduce

https://github.com/romaincointepas/electron-quick-start

- menu will show after 3 seconds behind at the pointer position with electron 1.7.9 and 1.8.2-beta.1
- menu will now show (error in console) when using electron 1.8.2-beta.2 and 1.8.2-beta.2

**Comment by felixrieseberg** [comment]
I can't confirm that behavior, calling `popup` with `async: true` works fine for me. Do you have a repro example?

**Comment by romaincointepas** [comment]
@felixrieseberg I'm created a test repo now. Are you trying from inside a renderer process?

**Comment by felixrieseberg** [comment]
Thanks! I _can_ repro now. I'll take a look.

**Comment by sindresorhus** [comment]
Relevant: https://github.com/electron/electron/commit/4e859b47185cb441b210e4bd85c10644088e4106
