### ISSUE TITLE
Exit status 3221225477

### ISSUE THREAD

**Issue by wujiazhong** [electron/electron#11378]
* Electron version: 1.7.9
* Operating system: Win 7 64 Bit

### Expected behavior

Running `cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./app/main.development` to start an electron app. It should be no error when exiting.

### Actual behavior
Throw error.

### Error Message
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\wujz.SPSS\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start-hot' ]
2 info using npm@5.6.0
3 info using node@v7.10.1
4 verbose run-script [ 'prestart-hot', 'start-hot', 'poststart-hot' ]
5 info lifecycle statistics-tc-desktop@1.0.0-1~prestart-hot: statistics-tc-desktop@1.0.0-1
6 info lifecycle statistics-tc-desktop@1.0.0-1~start-hot: statistics-tc-desktop@1.0.0-1
7 verbose lifecycle statistics-tc-desktop@1.0.0-1~start-hot: unsafe-perm in lifecycle true
8 verbose lifecycle statistics-tc-desktop@1.0.0-1~start-hot: PATH: C:\Users\wujz.SPSS\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\wujz.SPSS\Work\statistics-tc-desktop\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\IBM\RationalSDLC\common;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\IBM\RationalSDLC\ClearCase\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\IBM\SPSS\Statistics\25\JRE\bin;C:\Program Files\IBM\SPSS\Statistics\ThinClientDesktop\resources\stats_backend\backend\JRE\bin;c:\Program Files (x86)\Microsoft SQL Server\90\Tools\binn\;C:\Program Files (x86)\Intel\Compiler\Fortran\10.1.021\\EM64T\Lib;C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin;C:\Program Files\Microsoft SDKs\Windows\v6.0A\Bin;C:\apache-ant-1.10.1\bin;C:\Program Files\IBM\SPSS\Statistics\Subscription\JRE\bin;C:\Program Files\IBM\SPSS\Statistics\SubscriptionPreview\resources\stats_backend\backend\JRE\bin;C:\Python27;C:\Python27\Scripts;C:\Program Files\nodejs\;C:\Users\wujz.SPSS\Desktop\newUI\resources\stats_backend\backend\JRE\bin;C:\Users\wujz.SPSS\AppData\Local\atom\bin;C:\Users\wujz.SPSS\AppData\Roaming\npm
9 verbose lifecycle statistics-tc-desktop@1.0.0-1~start-hot: CWD: C:\Users\wujz.SPSS\Work\statistics-tc-desktop
10 silly lifecycle statistics-tc-desktop@1.0.0-1~start-hot: Args: [ '/d /s /c',
10 silly lifecycle   'cross-env HOT=1 NODE_ENV=development JAVA_CORE=false electron -r babel-register -r babel-polyfill ./app/main.development' ]
11 silly lifecycle statistics-tc-desktop@1.0.0-1~start-hot: Returned: code: 3221225477  signal: null
12 info lifecycle statistics-tc-desktop@1.0.0-1~start-hot: Failed to exec start-hot script
13 verbose stack Error: statistics-tc-desktop@1.0.0-1 start-hot: `cross-env HOT=1 NODE_ENV=development JAVA_CORE=false electron -r babel-register -r babel-polyfill ./app/main.development`
13 verbose stack Exit status 3221225477
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\wujz.SPSS\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:194:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\wujz.SPSS\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:194:7)
13 verbose stack     at maybeClose (internal/child_process.js:899:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid statistics-tc-desktop@1.0.0-1
15 verbose cwd C:\Users\wujz.SPSS\Work\statistics-tc-desktop
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\wujz.SPSS\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "start-hot"
18 verbose node v7.10.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 3221225477
22 error statistics-tc-desktop@1.0.0-1 start-hot: `cross-env HOT=1 NODE_ENV=development JAVA_CORE=false electron -r babel-register -r babel-polyfill ./app/main.development`
22 error Exit status 3221225477
23 error Failed at the statistics-tc-desktop@1.0.0-1 start-hot script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3221225477, true ]

**Comment by sofianguy** [comment]
@wujiazhong Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
