### ISSUE TITLE
Calling menu.popup() from main process on browser window freezes HTML5 video playback

### ISSUE THREAD

**Issue by romaincointepas** [electron/electron#11373]
* Electron version: 1.8.2 beta 1, 2 and 3
* Operating system: macOS 10.13.2

### Expected behavior

Calling menu.popup() from the main process on a browser window playing a html5 video should show the menu and the html5 video should keep playing without freezing while the menu is showing (this is the behavior on versions before the 1.8.2 betas).

### Actual behavior

When calling menu.popup() from the main process on a renderer window playing a html5 video, the video instantly freezes while the menu is showing, and the sound freezes a few seconds later. Video will resume playback as soon as the menu closes.

### Notes

This is probably related to the Chromium 61 upgrade and #11242.

**Comment by alexeykuzmin** [comment]
> Electron version: 1.8.2 beta 1, 2 and 3

> This is probably related to the Chromium 61 upgrade and #11242.

@romaincointepas, versions 1.8.x are based on Chromium 59.

**Comment by romaincointepas** [comment]
@alexeykuzmin Indeed, that issue confused me :/

I'm still confused though, as that issue mentions removing the `async` option from the `menu.popup()` function, and starting at electron version 1.8.2, the `menu.popup()` function doesn't take the async option anymore.

**Comment by alexeykuzmin** [comment]
> `menu.popup()` function doesn't take the `async` option anymore.

The code is still there: https://github.com/electron/electron/blob/v1.8.2-beta.3/atom/browser/api/atom_api_menu_views.cc#L24
`async` has been removed quite recently and didn't get to any release yet.

**Comment by romaincointepas** [comment]
@alexeykuzmin I created a separate issue for this: #11376

**Comment by alexeykuzmin** [comment]
@romaincointepas thank you!
