### ISSUE TITLE
Submitting an app that uses the TouchBar to the MAS

### ISSUE THREAD

**Issue by dashersw** [electron/electron#11377]
* Electron version: 1.8.2-beta.3
* Operating system: macOS 10.13.2 Beta (17C85a)

### Expected behavior

The app should pass Apple's review without further configuration or linking the Touch Bar framework.

### Actual behavior

The app gets rejected with the message "The app does not link against the Touch Bar framework."

### How to reproduce

Submit an app to the app store that uses the Touch Bar API.

**Comment by MarshallOfSound** [comment]
Can you provide the full rejection email / message?  I have a feeling this is because we forward declare the API's but I'm not 100% sure why that would be against MAS submission policy

**Comment by dashersw** [comment]
Unfortunately, this is all I got —

>We discovered one or more bugs in your app when reviewed on Mac running macOS 10.13.
>
>The app does not link against the Touch Bar framework.

**Comment by dashersw** [comment]
Is there a way to get the xcodeproj so I can manually link it and submit?

**Comment by dashersw** [comment]
Could this be related to code signing and child entitlements? The `mas-dev` build works without any problems, so this is really confusing.

**Comment by MarshallOfSound** [comment]
@dashersw I don't even know what they are referring to when they say "Touch Bar framework", the touch bar API's are inside the AppKit framework.  See here https://developer.apple.com/documentation/appkit/nstouchbar

Can you ask them for clarification, I have a feeling it's going to be some signing thing but idk

**Comment by dashersw** [comment]
I did, already :(

This is my message;


> Hello, do the Touch Bar features not work? When I sign the app locally with my development certificate and profile, I can interact with the Touch Bar with no problems.
>
> Could this be related to entitlements and code signing?

**Comment by dashersw** [comment]
I'll also try adding/overriding child entitlements and the `inherit` thing.

**Comment by sethlu** [comment]
@dashersw On the code signing aspect, I don't think `codesign` affects the linking against the touch bar framework.

**Comment by dimitarnestorov** [comment]
Our app went through **with** Touch Bar functionality.
@dashersw Did your app go through? I believe this issue can be closed.

**Comment by dashersw** [comment]
I gave up long ago.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
