### ISSUE TITLE
In Ubuntu, a radio-buttons menu is never updated after selecting a new item

### ISSUE THREAD

**Issue by Mikaeru69** [electron/electron#11386]
* Electron version: 1.7.9
* Operating system: Ubuntu 16.04.3 LTS

### Expected behavior

In Linux Mint (and Mac OS X), selecting an item from a menu made of radio-buttons moves the checked mark to the new item when the menu is accessed later on.

### Actual behavior

In Ubuntu, the checked item is never updated.

### How to reproduce

  $ git clone https://github.com/Mikaeru69/Ubuntu-Radio-Buttons-Menu-Bug
  $ cd Ubuntu-Radio-Buttons-Menu-Bug
  $ npm install
  $ npm start

- Start the application from a Terminal using the above-mentioned instructions.
- In the `Items` menu, select `Item 2` (or `Item 3`), verify that the item has indeed been selected by checking the console.log message in the Terminal window, then access the menu again and note that `Item 1` is still checked.

**main.js**:
````javascript
// [...]
function itemClicked (menuItem, browserWindow, event)
{
   console.log ("Clicked:", menuItem.label, menuItem.checked ? "(checked)" : "(unchecked)");
}
// [...]
{
    label: 'Items',
    submenu: [
        { label: 'Item 1', type: 'radio', click: itemClicked, checked: true },
        { label: 'Item 2', type: 'radio', click: itemClicked },
        { label: 'Item 3', type: 'radio', click: itemClicked }
    ]
},
// [...]
````

![Screenshot](https://raw.githubusercontent.com/Mikaeru69/Ubuntu-Radio-Buttons-Menu-Bug/master/VirtualBox_Ubuntu_08_12_2017_20_39_00.png)

**Comment by shreyneil** [comment]
Hi 
I am using Ubuntu 17.10 and the latest electron version.
I followed the steps to reproduce the error but it works fine for me .
Here are some of the screenshots.
![screenshot from 2017-12-13 23-56-51](https://user-images.githubusercontent.com/20383947/33955405-71b630ea-e061-11e7-9fc9-9ed5ab1bcbc4.png)
![screenshot from 2017-12-13 23-56-59](https://user-images.githubusercontent.com/20383947/33955427-847e1de6-e061-11e7-99bc-8aaf30ffdf5c.png)
![screenshot from 2017-12-13 23-57-08](https://user-images.githubusercontent.com/20383947/33955444-94936e20-e061-11e7-8685-2d4710025d3f.png)

Please verify and get back.

**Comment by Mikaeru69** [comment]
Hi
I installed Ubuntu 17.10 in a separate VirtualBox, and followed the same steps to reproduce the error. It seems that the problem is solved in this new version of Ubuntu:

![virtualbox_ubuntu 17_14_12_2017_16_00_48](https://user-images.githubusercontent.com/31444539/33998604-574db37c-e0e8-11e7-9bf0-00bde1933055.png)

For the record, when running `npm start`, I got this error message at first:
```
error while loading shared libraries: libgconf-2.so.4
```
so I had to manually install it:
```
sudo apt-get install libgconf-2-4
```
Also, I had to solve an issue of flickering screen, and still encounters problems of stability and missing system settings. That's why I definitely prefer to use LTS (Long Term Support) versions...

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
