### ISSUE TITLE
Webrtc audio bug

### ISSUE THREAD

**Issue by Marcus122** [electron/electron#11382]
I'm getting a bug when using webrtc on electron.

I create an Audio object and set the srcObject to the remote media stream. I then setSinkId to the deviceId of a usb headset. The bug is that if I then unplug and replug the usb device quickly, once it has reconnected the navigator.mediaDevices devicechange event fires, in the handler for this I reset the sinkId on the audio object to be the deviceId of the headset, but I get no audio. I tested on windows and don't get this issues it seems just to be on Mac OS.

* Electron version: 1.7.9
* Operating system: Mac OS

### Expected behavior

Replugging in the usb and setting sinkId on the audio object should play the audio through the device.

### Actual behavior

No Audio through the device.

### How to reproduce

During a webrtc call quickly unplug and replug in the device that is being used for the call audio.

**Comment by Marcus122** [comment]
I think this may be a chromium bug but it would be interesting to hear your thoughts.

**Comment by MarshallOfSound** [comment]
Can you check if it can be reproduced in Chromium 59 or in latest Chromium?  It sounds like a Chromium bug 😄

**Comment by Marcus122** [comment]
Yes managed to reproduce in Chromium so I'll close the issue. Thanks!

**Comment by Fiser12** [comment]
Maybe it's related with this old-reported issue. It's on hold since years

https://bugs.chromium.org/p/chromium/issues/detail?id=697877

Remember that for get visibility on chromium you should “Start" it with your Google account to help to the Chromium team to understand its importance
