### ISSUE TITLE
checkbox in dialog not working

### ISSUE THREAD

**Issue by mymyoux** [electron/electron#11389]
* Electron version: 1.8.2-beta.3
* Operating system: Mac OS X 10.12.6

### Expected behavior

When ticking the checkbox on a dialog box we should receive a true value in the callback

### Actual behavior

I always receive false value checked or not

### How to reproduce

clone https://github.com/electron/electron-quick-start  project and add this to renderer.js

`require('electron').remote.dialog.showMessageBox({
  type: "question",
  buttons: ["OK", "Cancel"],
  message: "This is a test.",
  checkboxLabel: "Do not show this message again."  
}, function (...args) { console.log(...args) })`

It will always display `0 false`

I also tested on Windows 10 and it's working as expected.
And I tested the electron@1.7.9 on both windows and mac OS X, it works too.

**Comment by codebytere** [comment]
@mymyoux checking this out today

**Comment by codebytere** [comment]
@mymyoux fixed and merged, closing this!

**Comment by agalwood** [comment]
The Electron v1.8.3's dialog checkboxChecked is still always false : (
I read the tag 1.8.3 code and found that it is still the wrong code, please merge master code to 1.8.X branch. @codebytere 

> https://github.com/electron/electron/blob/v1.8.3/atom/browser/ui/message_box_mac.mm#L191
```objectivec
callback.Run(ret, false);
```

**Comment by codebytere** [comment]
will backport asap!

**Comment by ckerr** [comment]
Approved and merged.

There will be a new 1.8 release next week, so as @codebytere says this fix will be included in that release.

@agalwood, thank you for noticing and reporting this bug was still in the 1.8 branch. :+1:
