### ISSUE TITLE
establish secure communication for electron atom exe and sqlserver using ssl

### ISSUE THREAD

**Issue by sarath125** [electron/electron#11384]
i want to establish secure communication for electron atom exe and sqlserver using ssl.
since electron atom is a windows application it don't have any server so I created ssl certificate in iis server and configured that in sql server. After that i exported that certificates to use in electron atom exe. i saw few examples like

node-postgres it asking three certificates,from iis i exported certificate certificate.pfx from that can we extract following certificates for node-postgres ca : fs.readFileSync("/path/to/server-ertificates/maybe/root.crt").toString(), key : fs.readFileSync("/path/to/client-key/maybe/postgresql.key").toString(), cert : fs.readFileSync("/path/to/client-certificates/maybe/postgresql.crt").toString(),

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
