### ISSUE TITLE
Fullscreen apps steal focus after switching away in macOS

### ISSUE THREAD

**Issue by PortableStick** [electron/electron#11390]
* Electron version: 1.7.9
* Operating system: macOS 10.12.6

### Expected behavior

When I full-screen an Electron app in macOS, I should be able to navigate away.

### Actual behavior

If I use a touchpad gesture or keyboard shortcut to move back to my main desktop, about a second later I'll be sent back to the Electron app's space.  Usually, the second try is successful, but sometimes I have to navigate via Mission Control in order to move away from the app.

### How to reproduce

1) Install an Electron app
2) Full screen the app
3) Move away from the app using a touchpad gesture or keyboard command

I have tested the latest versions of Wire, Signal, and Skype.  All of these reliably trigger the behavior.  I have never experienced this with any non-Electron app.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
