### ISSUE TITLE
showOpenDialog using 'openFile' on macOS selects directory 

### ISSUE THREAD

**Issue by lutzroeder** [electron/electron#11391]
* Electron version: `1.7.9`
* Operating system: `macOS 10.13.2 (17C88)`

### Expected behavior

The dialog only allows to select *files* with the `.foo` extension.

### Actual behavior

On macOS it will select a directory with the `.foo` extension (e.g. extracted archive) and does not allow to drill into the folder that might have a file with the same name...

### How to reproduce

```
var showOpenDialogOptions = { properties: [ 'openFile' ], filters: [ { name: 'Foo file', extensions: [ 'foo' ] } ]
    };
electron.dialog.showOpenDialog(showOpenDialogOptions, function(selectedFiles) {
    // ...
});

**Comment by shreyneil** [comment]
It looks there is an issue with the custom function selectedFiles implemented by you. 
To get into file paths you could do something like this:
dialog.showOpenDialog(…, …, (filenames) => {
    console.log(filenames); // those are your path files
});

Please verify and get back.

**Comment by lutzroeder** [comment]
It's the same syntax. I attached a minimal repro with a `/folder.foo/file.foo`. On macOS it is not possible to drill into `folder.foo` and select `file.foo`.

[ShowOpenDialogRepro.zip](https://github.com/electron/electron/files/1546161/ShowOpenDialogRepro.zip)

**Comment by shreyneil** [comment]
Can confirm with what is your process platform?

**Comment by lutzroeder** [comment]
`process.platform = 'darwin'`
`macOS 10.13.2 (17C88)`

**Comment by shreyneil** [comment]
Thanx !

Can you  add multiSelections to your properties array and try running the app again. Remove all the other properties and try again. 
properties: [  'multiSelections' ]

**Comment by lutzroeder** [comment]
How is this addressing the issue? The goal is selecting a specific file with a specific file extension.

**Comment by shreyneil** [comment]
The above mentioned change works fine in Linux and selects multiple files with the particular extension provided.
Due to the absence of Mac I could not test this change for you, so it would be better if you could check it. 

Moreover, there must be some issues with os which is causing this discrepancy, our contributors will take care of it, but for the time being you could try it.

**Comment by lutzroeder** [comment]
Using `properties: [ 'multiSelections' ]` will allow to select into the folder on macOS. However, it doesn't allow selecting the actual file which show grayed out.

**Comment by codebytere** [comment]
@lutzroeder i'll take a look at this today

**Comment by codebytere** [comment]
@lutzroeder so it looks like your issue here is with the `fileFilter` you're passing, if you only pass 
```
filters: [{ extensions: ['foo'] }]
```
it will work as intended.

**Comment by lutzroeder** [comment]
@codebytere Using `filters: [{ extensions: ['foo'] }]` will allow picking any files on macOS, not just `.foo` files. The goal is to have the dialog only show `.foo` files (or filter multiple extensions if specified) but not have it get stuck on folders called `.foo`. 

```
const electron = require('electron')

electron.app.on('ready', () => {
  var showOpenDialogOptions = {
    properties: [ 'openFile' ],
    filters: [ { extensions: [ 'foo' ] } ]
  };
  electron.dialog.showOpenDialog(showOpenDialogOptions, (selectedFiles) => {
    console.log(selectedFiles);
  });
});
```

<img width="1018" alt="screenshot" src="https://user-images.githubusercontent.com/438516/36068042-865e67b8-0e80-11e8-93f2-d6ebca9796d1.png">

**Comment by codebytere** [comment]
oh gotcha, i'll dig into this more starting monday!

**Comment by codebytere** [comment]
@lutzroeder having read through the [docs](https://developer.apple.com/documentation/appkit/nssavepanel?language=objc) i'm somewhat sure that it's behavior on the apple side of things. We don't implement any special logic besides passing types to the default `[dialog setAllowedFileTypes:file_types];` method so i can keep looking but i'm not sure we can fix this on our side

**Comment by TangentFoxy** [comment]
I think the API is being used incorrectly?

[file_dialog_mac.mm#L138](https://github.com/electron/electron/blob/main/shell/browser/ui/file_dialog_mac.mm#L138) is where this is passed to the API, but that value is set at [file_dialog_mac.mm#L119](https://github.com/electron/electron/blob/main/shell/browser/ui/file_dialog_mac.mm#L119) from a C string, but the [documentation](https://developer.apple.com/documentation/appkit/nssavepanel/allowedcontenttypes?language=objc) states this must be a **UTType**. You can see the documentation for [UTTypes here](https://developer.apple.com/documentation/appkit/nssavepanel/allowedcontenttypes?language=objc).
