### ISSUE TITLE
Tray.setTitle - complex title with multiple fonts?

### ISSUE THREAD

**Issue by tleunen** [electron/electron#11392]
Mac OS supports having a complex title and setting different fonts.

It would be great to have the same mechanism when using Electron so we can easily use an icon fonts for some parts.

**Comment by codebytere** [comment]
Given that is somewhat old and that this isn't currently on our roadmap, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR.
