### ISSUE TITLE
Web bluetooth takes 1 minute before returning a device

### ISSUE THREAD

**Issue by timmyhadwen** [electron/electron#11399]
* Electron version: 1.7.9
* Operating system: macOS Sierra

### Expected behavior

We should have some type of bluetooth dialog (like in chrome).

### Actual behavior

A 1 minute timeout before a device (even with specified name) is selected and connected to.

**Comment by MarshallOfSound** [comment]
> We should have some type of bluetooth dialog (like in chrome).

Electron is not a browser, default "browser style" dialogs such as permission requests and in this case bluetooth device select are left to the developers of specific apps to implement.

> A 1 minute timeout before a device

Can you provide sample code that replicates this issue?

**Comment by timmyhadwen** [comment]
@MarshallOfSound Thanks for the reply!

> Electron is not a browser, default "browser style" dialogs such as permission requests and in this case bluetooth device select are left to the developers of specific apps to implement.

Makes sense, but obviously the delay isn't wanted either.

> Can you provide sample code that replicates this issue?
This repo should replicate the issue
https://github.com/aalhaimi/electron-web-bluetooth

**Comment by acstacey** [comment]
The issue appears to be that the scan timeout is 1 minute and the BluetoothChooser::AddOrUpdateDevice method doesn't emit an event so a device can't be chosen until the scan is complete.
