### ISSUE TITLE
menu.getMenuItemById is not a function

### ISSUE THREAD

**Issue by fmarzocca** [electron/electron#11405]
* Electron version: 1.7.9
* Operating system: Mac OSX

In my app I need to get a specific menuItem, so I was trying to use menu.getMenuItemById(id):

```
...
  menu = Menu.buildFromTemplate(topLevelItems);
  Menu.setApplicationMenu(menu);
  console.log(menu.getMenuItemById('color-scale'));
```

but I am getting the error: `Uncaught Exception: TypeError: menu.getMenuItemById is not a function.`
The menu is working fine, but I can't use this function.

**Comment by fmarzocca** [comment]
I temporarily fixed this by adding this fucntion (grabbed from electron code) directly into my app:

```
function mygetMenuItemById(id, mymenu) {
  const items = mymenu.items
 
   let found = items.find(item => item.id === id) || null
   for (let i = 0, length = items.length; !found && i < length; i++) {
     if (items[i].submenu) {
       found = mygetMenuItemById(id,items[i].submenu)
     }
   }
   return found
 }
```

**Comment by MarshallOfSound** [comment]
@fmarzocca That function is not part of the `1.7.9` release, it is only in the `1.8.x` series, you can see what was available at release by looking at the docs site which is currently displaying the docs for `1.7.9`
