### ISSUE TITLE
Missing bytecode font hinting

### ISSUE THREAD

**Issue by rpallai** [electron/electron#11402]
* Electron version: 1.6.9
* Operating system: Fedora 26

Electron does not use bytecode font hinting at all. This is very visible with disabled antialiasing. With enabled antialiasing the effect is not so obvious, feels like font rendering is blurry or simply weird. Autohint is used which better than nothing but worse than bytecode hinting.

Reproduce on Linux:
1. Save the following snippet into ```~/.fonts-atomtest.conf```:
```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
        <include>/etc/fonts/fonts.conf</include>

        <match target="font">
            <!-- enable hinting -->
            <edit name="hinting" mode="assign"><bool>true</bool></edit>
            <!-- no autohint but bytecode -->
            <edit name="autohint" mode="assign"><bool>false</bool></edit>
            <edit name="hintstyle" mode="assign"><const>hintfull</const></edit>
            <!-- for very visible results -->
            <edit name="antialias"><bool>false</bool></edit>
        </match>
</fontconfig>
```
2. Run ```FONTCONFIG_FILE=~/.fonts-atomtest.conf atom -f```
3. Use a bytecode hinted font in Atom, like the good old Arial or Liberation Mono and see ugly, fuzzy font rendering. Try other application (eg. kwrite) with the same FONTCONFIG_FILE and font family and see the difference.

There is no reason to avoid bytecode hinting, use if possible.

**Comment by MarshallOfSound** [comment]
Related: https://github.com/electron/libchromiumcontent/issues/384

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
