### ISSUE TITLE
Organize tutorial content

### ISSUE THREAD

**Issue by zeke** [electron/electron#11416]
The current structure of Electron's tutorial content leaves a lot to be desired: It's a [directory full of markdown files](https://github.com/electron/electron/tree/master/docs/tutorial). There's a lot of great content in these files, but the lack of hierarchy or logical order makes it hard for newcomers to know where to start. 🙈 🎣 

To start creating more approachable guides to Electron, I propose that we keep all the existing tutorials file exactly where they are, and introduce a new file `/docs/tutorial/README.md` with a table of contents linking to those various files. This approach will allow us to start organizing the content without moving files around and disrupting the natural order. In other words, no 404s.

Here's a rough outline of how this new README could look:

- Development Environment
    - Setting up Windows
    - Setting up Mac
    - Setting up Linux
- Installing Electron
    - Global vs Local
    - Versioning
    - Alternatives (prebuilt-compile)
- Creating an App
    - Choosing an Editor
    - Quick Start
    - Electron Forge
    - Boilerplates
- Electron APIs
    - Main and Renderer Processes
    - IPC
- User Interface
    - Browser Windows
    - Menus
    - Dialogs
    - Keyboard Shortcuts
- Chromium
    - Renderer Process
    - JavaScript Support
- Node
    - Renderer and Main Process
    - Node Core Modules
    - Using npm Modules
    - Native Modules
- Debugging
    - Chromium DevTools
    - Extensions
    - Devtron
    - Node Debugger
    - Userland Tools
- Testing
    - Unit Testing
    - Integration Testing
    - spectron
    - electron-mocha
- Security
    - Node Integration
    - Remote Content
- Signing
- Packaging 
- Releasing
- Updating

On the electron-i18n and website side of things, we can parse this new README's TOC and use it to make a sidebar nav, as well as <kbd>Previous</kbd> and <kbd>Next</kbd> buttons so folks can move through the content linearly.

Here's an example from the beloved Ember website for inspiration:

<img width="996" alt="screen shot 2017-12-12 at 7 50 01 am" src="https://user-images.githubusercontent.com/2289/33893779-2bea6974-df11-11e7-83d7-7b62caabcf3e.png">

A few other thoughts:

- Each section's most universally relevant content should be displayed first so folks can get the TLDR right away, and delve deeper into the section if they want more detail on the given topic. See [Inverted pyramid (journalism)](https://en.wikipedia.org/wiki/Inverted_pyramid_(journalism)). 🎩 @felixrieseberg 
- Idea: The content of this README could be **aspirational**, listing all the topics that we think _should_ be covered, regardless of whether that particular topic already has an existing doc. This would help us determine what is yet to be written.
- Links in the table of contents could be deep links, going straight to some section of a doc like `/tutorial/foo#some-section`

cc @brianamarie

**Comment by felixrieseberg** [comment]
Just going on the record here: Happy to commit to some tutorial writing.

**Comment by eddiemonge** [comment]
Off topic but where is `Testing: Unit Testing`. All I see is https://github.com/electron/electron/blob/master/docs/tutorial/testing-on-headless-ci.md which doesn't seem to be unit tests.

**Comment by brianamarie** [comment]
@hectorsector @beardofedu @hollenberry @crichID cc for 👀

**Comment by CameronAdams777** [comment]
@zeke Hello there! My name is Cameron and I am a YouTuber who has possibly the most extensive series of tutorials on Electron. I just got started working on my tutorials again and I was wondering if/how I could contribute to here 🙂 

Also, just thought I would mention @chrisvfritz. He may not have any interest but I hear he writes some pretty awesome docs 😉

**Comment by chrisvfritz** [comment]
Ha, thank you @CameronAdams777. That's very kind! I do really like Electron, but unfortunately don't have the capacity to work on more docs than Vue's right now. 😅 I'm happy to answer any questions about our process though.

**Comment by zeke** [comment]
Building a jumping-off point from a new README.md:

```js
const docs = require('electron-i18n').docs['en-US']

Object.keys(docs)
  .filter(href => href.includes('tutorial'))
  .map(href => {
    const doc = docs[href]
    const path = doc.href.replace('/docs/tutorial/', '') + '.md'
    console.log('- [%s](%s)', doc.title, path)
  })
```

Output:

```
- [Accessibility](accessibility.md)
- [Application Distribution](application-distribution.md)
- [Application Packaging](application-packaging.md)
- [Debugging the Main Process](debugging-main-process.md)
- [Debugging the Main Process in VSCode](debugging-main-process-vscode.md)
- [Desktop Environment Integration](desktop-environment-integration.md)
- [DevTools Extension](devtools-extension.md)
- [Electron Versioning](electron-versioning.md)
- [Installation](installation.md)
- [Keyboard Shortcuts](keyboard-shortcuts.md)
- [Mac App Store Submission Guide](mac-app-store-submission-guide.md)
- [Multithreading](multithreading.md)
- [Notifications (Windows, Linux, macOS)](notifications.md)
- [Offscreen Rendering](offscreen-rendering.md)
- [Online/Offline Event Detection](online-offline-events.md)
- [Planned Breaking API Changes](planned-breaking-changes.md)
- [Quick Start](quick-start.md)
- [REPL](repl.md)
- [Security, Native Capabilities, and Your Responsibility](security.md)
- [Snapcraft Guide (Ubuntu Software Center & More)](snapcraft.md)
- [Supported Platforms](supported-platforms.md)
- [Testing on Headless CI Systems (Travis CI, Jenkins)](testing-on-headless-ci.md)
- [Updating Applications](updates.md)
- [Using Native Node Modules](using-native-node-modules.md)
- [Using Pepper Flash Plugin](using-pepper-flash-plugin.md)
- [Using Selenium and WebDriver](using-selenium-and-webdriver.md)
- [Using Widevine CDM Plugin](using-widevine-cdm-plugin.md)
- [Windows Store Guide](windows-store-guide.md)
```

cc @felixrieseberg

**Comment by zeke** [comment]
This happened in https://github.com/electron/electron/pull/11966, thanks to @felixrieseberg  🎉 

I've created followup issues on the website for navigation improvements:

https://github.com/electron/electronjs.org/issues/1156 - Add a sidebar nav to tutorial pages
https://github.com/electron/electronjs.org/issues/1157 - Add 'Next' and 'Previous' links to tutorial pages
