### ISSUE TITLE
Menuitem display missing shift modifier in accelerator

### ISSUE THREAD

**Issue by kwonoj** [electron/electron#11429]
* Electron version: 1.8.2-beta.3
* Operating system: Windows / Linux

### Expected behavior
Expect accelerator correctly includes modifier

### Actual behavior
For some key combination, shift modifier is not displayed while functionwise it works.

![image](https://user-images.githubusercontent.com/1210596/33964550-a0ca46a4-e00d-11e7-93b1-832317f60436.png)

### How to reproduce

```
const menu = Menu.buildFromTemplate([
    {
      label: 'Test',
      submenu: [
        {
          label: 'Missing modifier',
          accelerator: 'Control+Shift+F'
        },
        {
          label: 'Working',
          accelerator: 'Control+Shift+Tab'
        }
      ]
    }
  ]);

Menu.setApplicationMenu(menu);
```

then ctrl-shift-f will be displayed as ctrl-f only.

This started from 1.8.2-beta.2, peeking history between version it seems like patch change around accelerator in libchromiumcontent might be reason - but I couldn't verify it by myself.

**Comment by alexeykuzmin** [comment]
Related to electron/libchromiumcontent#349.
