### ISSUE TITLE
macOS Sierra: Failed at the electron@1.7.9 postinstall script 'node install.js'. See #254

### ISSUE THREAD

**Issue by jmuzet** [electron/electron#11423]
* Electron version: 1.7.9
* Operating system: macOS Sierra 10.12.6
* npm version: 5.6.0
* NodeJS version: 8.9.1

This issue is linked to the closed issue #254. This one is 'reopened' as request by zeke.

Issue on installing electron as global, using the following command:

`$ sudo npm i -g electron`

Outcome:

`/usr/local/bin/electron -> /usr/local/lib/node_modules/electron/cli.js

> electron@1.7.9 postinstall /usr/local/lib/node_modules/electron
> node install.js

/usr/local/lib/node_modules/electron/install.js:48
  throw err
  ^

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/electron/dist'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.7.9 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.7.9 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

I installed electron locally without any issue. npm is installed globally but I'm still facing the issue installing globally.

Many thanks in advance.
Cheers
Jerome

**Comment by MarshallOfSound** [comment]
> /usr/local/lib/node_modules

This is your problem, installing things globally shouldn't require `sudo`, if it does things will break (like this).  Check out the [`sudo`](https://github.com/electron/electron/blob/master/docs/tutorial/installation.md#troubleshooting) section of the installation troubleshooting guide

**Comment by jmuzet** [comment]
Perfect!
Everything works fine.
Thank you!
