### ISSUE TITLE
network error - net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by pebanfield** [electron/electron#11424]
My client app makes request against a local node express web service. I have launched the service from renderer.js

I have tried setting - 

win.loadURL(url.format({
    pathname: path.join(__dirname, 'index.html'),
    protocol: 'file:',
    webSecurity: false,
    allowRunningInsecureContent: true
  }))

in main.js as per the documentation. But I am still receiving a security exception. 

When I launch the service from the renderer I can browse to the service locally so I know that it is working properly. Shouldn't this be working? What am I missing? This seems like a basic use case - run and consume a local web app with web service. Thanks.

**Comment by MarshallOfSound** [comment]
```js
webSecurity: false,
allowRunningInsecureContent: true
```

Are options to put in the `webPreferences` property of the browser window constructor options, not in `url.format`

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by pebanfield** [comment]
This is still not working with the following configuration - 

win = new BrowserWindow({width: 1200, height: 700, webPreferences: {
    webSecurity: false,
    allowRunningInsecureContent: true
  }})

Does anyone know of a working example? Are there other work arounds? JSONP perhaps? Thanks.

**Comment by printjs** [comment]
@pebanfield Do you reslove the problem?

**Comment by printjs** [comment]
@MarshallOfSound you can't reslove it,but you close the issue.

**Comment by defghy** [comment]
https://github.com/electron/electron/issues/36890#issuecomment-1980300720
