### ISSUE TITLE
Electron headless (Xvfb) no text and images.

### ISSUE THREAD

**Issue by rokyed** [electron/electron#11425]
I am sorry to not follow the guide, but I can't yet find a way to reproduce the bug and it seems intermittent.

So, I use Electron on an Ubuntu Server 16.04 with Xvfb ([https://github.com/kesla/node-headless](https://github.com/kesla/node-headless)) in order to generate pdfs using pdfkit([https://github.com/devongovett/pdfkit](https://github.com/devongovett/pdfkit)) , the process is simple:
I get a request, I launch a BrowserWindow then capturePage , then in the main process i stitch the stored images (in tmp) into a pdf.

**The problem: Electron sometimes won't show text and images, but it won't do any unhandled exception or any other crash somewhere.** 

My question is, have you ever experienced this and what did you do to remediate it ?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by rokyed** [comment]
@MarshallOfSound I managed to reproduce the bug, but still no errors on console at all. It comes with certitude from Electron.

**Ubuntu's info:**
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

@MarshallOfSound  is there any flag that can make Electron vomit all the warnings, errors, notifications and logs ?

**Comment by brenca** [comment]
@rokyed If you want to make electron vomit, you could use the **vomit** level flag (or verbose, I reallt don't know ;) ), e.g. `--enable-logging --v=1`. The higher the number, the more the vomit, 'tho 1 should be fine.

**Comment by TomasHubelbauer** [comment]
I am getting a black screen from `capturePage` on an Electron based app running using Xvfb. Though I get it consistently. Did you ever manage to solve this, @rokyed?
