### ISSUE TITLE
contents.loadUrl() strips anchors from given url

### ISSUE THREAD

**Issue by ajoslin103** [electron/electron#11432]
* Electron version: v1.4.13
* Operating system: OS X 10.12.6

### Expected behavior

calling contents.loadURL('http://localhost:8080/simplex/#/out-of-service')
should Navigate to 'http://localhost:8080/simplex/#/out-of-service'

### Actual behavior

calling contents.loadURL('http://localhost:8080/simplex/#/out-of-service')
Navigates to 'http://localhost:8080'

### How to reproduce

    "nightmare": "^2.10.0",
    "jest": "20.0.4",

1. given a jest file

```
const Nightmare = require('nightmare')
describe('When starting the app', function () {
	Nightmare.action('loadPage',
		function (name, options, parent, win, renderer, done) {
			parent.respondTo('loadPage', function (newUrl, done) {
				win.webContents.executeJavaScript(`console.log('win.webContents.loadURL(newUrl):', '${newUrl}' )`);
				win.webContents.loadURL(newUrl);
				done();
			});
			done();
		},
		function (newUrl, done) {
			console.log('newUrl', newUrl);
			this.child.call('loadPage', newUrl, done);
		}
	);
	test('it goes out-of-service', async function () {
		let nightmare = Nightmare({
			show: true,
			dock: true,
			openDevTools: {
				mode: 'detach'
			},
			height: 622
		});
		nightmare
			.goto('http://localhost:8080')
			.loadPage('http://localhost:8080/simplex/#/out-of-service')
			.end()
			.catch(err => console.log('caught err', err));
		expect(true).toBeTruthy();
	});
});
```

2. having ensured the app & supports are executing at localhost:8080

3. execute the test

4. jest test/e2e/nightmare.spec.js 

the [electron] browser console displays:

[...]
win.webContents.loadURL(newUrl): http://localhost:8080/simplex/#/out-of-service
Navigated to http://localhost:8080/
[...]

**Comment by MarshallOfSound** [comment]
@ajoslin103 To eliminate the possibility that your testing framework or nightmare is causing this, can you please attempt to do this in native Electron.

As far as I can tell when I call `.loadURL('http://mysite.com/foo/#/bar')` the anchor part is loaded correctly

**Comment by ajoslin103** [comment]
Thank you MarshallOfSound, I used the QuickStart to prove to myself that the problem lies elsewhere (somewhere in my head) -- closing this issue
