### ISSUE TITLE
cannot break in 1.8.2

### ISSUE THREAD

**Issue by bughit** [electron/electron#11430]
* Electron version: v1.8.2-beta.3 x86
* Operating system: win7 x64

### Expected behavior

breaking

### Actual behavior

no breaking

### How to reproduce

- `electron-v1.8.2-beta.3-win32-ia32\electron.exe --inspect-brk`
- attach the chrome dev tools via chrome://inspect
- debugger should open stopped (it doesn't) other breakpoints will also not be hit

1.7.9 is ok

**Comment by alexeykuzmin** [comment]
@MarshallOfSound this can be closed, right?

**Comment by MarshallOfSound** [comment]
Yep
