### ISSUE TITLE
Animated png always disposes frame pixels

### ISSUE THREAD

**Issue by pawnipt** [electron/electron#11443]
* Electron version: 1.8.2-beta.3
* Operating system: macOS 10.13.2

### Expected behavior

[example image](http://pchat.org/c310e253-5c4b-490a-8914-7d0a8cf80ed5.png)

### Actual behavior

Frames instructed not to dispose are getting disposed anyways, causing transparency artifacts with optimized apng.

### How to reproduce

Display the above image in darwin Electron (the bug does not appear to be present under windows Electron)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
