### ISSUE TITLE
How can I get notification while switching to other apps on macOS

### ISSUE THREAD

**Issue by orklann** [electron/electron#11449]
I want to hide a Browser window instance after switching to other apps, so I need a notification for this event.

It would be good to have some API like:

```Javascript
app.on('deactivate', function(){

});
```

How can I do this?

**Comment by MarshallOfSound** [comment]
Check out the blur event on the Browser window class

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
