### ISSUE TITLE
Feature Request: Ignore area from findInPage  

### ISSUE THREAD

**Issue by ccorcos** [electron/electron#11444]
* Electron version: 1.8.1

It would be awesome if there was a CSS className or something to exclude certain parts of the UI from findInPage so that users can search only within the content of a page.

Bonus: CSS for the the actual highlighting.

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
