### ISSUE TITLE
Legacy Chrome IPC, RenderView are deprecated

### ISSUE THREAD

**Issue by ckerr** [electron/electron#11442]
atom/ makes heavy use of `RenderView`, which according to `libcc/src/content/public/renderer/render_view.h` is deprecated and being removed:

```cpp
// DEPRECATED: RenderView is being removed as part of the SiteIsolation project.
// New code should be added to RenderFrame instead.
```

We also use Legacy Chrome IPC for IPC messages, eg in `common/api/api_messages.h`, and that is also deprecated according to `libcc/src/ipc/README.md`:

```txt
Legacy IPC is **deprecated**, and Chrome developers are strongly discouraged
from introducing new messages using this system. Mojo is the correct
IPC system to use moving forward.
```

One important question is "how urgent is this?" because some of these plans seem to have been in the works for years and may take longer for things to be removed. But we should have a plan and consider moving to Mojo & RenderFrame on our own timeframe rather than waiting until we have to due to libcc breakage.

**Comment by alexeykuzmin** [comment]
Great find!

I would separate it into two different issues though, since the "features" and independent and will probably be removed in a different Chromium releases.

Switching to Mojo from IPC looks fairly non-trivial since mojo files are generated and we don't have tools to generate them in the Electron repo.

**Comment by YurySolovyov** [comment]
Will [that](https://github.com/electron/electron/issues/12098#comment-374559253) help? At least for IPC part

**Comment by nornagon** [comment]
Some context on the Chromium side: https://crbug.com/467770

**Comment by nornagon** [comment]
Ref #17406

**Comment by miniak** [comment]
We have moved all the IPCs to mojo exclusively. I think we are also using RenderFrame everywhere.
