### ISSUE TITLE
Node ABI mismatch

### ISSUE THREAD

**Issue by fantasticsid** [electron/electron#11440]
* Electron version: 1.6.11
* Operating system: MacOS

### Expected behavior

according to releases here: https://nodejs.org/en/download/releases/
node version 7.4.0 should have ABI version 51
### Actual behavior

with electron 1.6.11, process.versions.node is 7.4.0, but process.versions.modules is 53, this is a mismatch. This makes it very very hard to use modules like v8-profiler

**Comment by MarshallOfSound** [comment]
This is by design, although Electron uses "node 7.4.0" internally in Electron 1.6.11 it is modified and built against a different version of v8.  This requires it have a different ABI version.

You can rebuild native modules against Electron's ABI / headers by using `electron-rebuild`
