### ISSUE TITLE
websocket  connect server slow in electron :url_request_context.cc(134)] Check failed: false

### ISSUE THREAD

**Issue by saber-hyw** [electron/electron#11446]
* Electron version:
* Operating system:

### How to reproduce

[16164:1215/173633.966:FATAL:url_request_context.cc(134)] Check failed: false. Leaked 1 URLRequest(s). First URL: http://wpad/wpad.dat.
Backtrace:
        GetHandleVerifier [0x00007FF64E796D55+23093]
        GetHandleVerifier [0x00007FF64E8077E3+484547]
        (No symbol) [0x00007FF64E78E9A4]
        IsSandboxedProcess [0x00007FF64FAEE2A8+16822144]
        IsSandboxedProcess [0x00007FF64FAEE0A8+16821632]
        IsSandboxedProcess [0x00007FF64FAEE168+16821824]
        (No symbol) [0x00007FF64E74C20C]
        (No symbol) [0x00007FF64E74C888]
        IsSandboxedProcess [0x00007FF64FAB53DF+16588983]
        (No symbol) [0x00007FF64E53DE5F]
        (No symbol) [0x00007FF64E53C144]
        GetHandleVerifier [0x00007FF64E835AC7+673703]
        GetHandleVerifier [0x00007FF64E7D6CD6+285110]
        GetHandleVerifier [0x00007FF64E7D57C0+279712]
        GetHandleVerifier [0x00007FF64E836B67+677959]
        GetHandleVerifier [0x00007FF64E837454+680244]
        GetHandleVerifier [0x00007FF64E7D2D2E+268814]
        GetHandleVerifier [0x00007FF64E89A94E+1087022]
        GetHandleVerifier [0x00007FF64E89B465+1089861]
        GetHandleVerifier [0x00007FF64E7F95F7+426711]
        GetHandleVerifier [0x00007FF64E7B8845+161061]
        BaseThreadInitThunk [0x00007FF861D81FE4+20]
        RtlUserThreadStart [0x00007FF8644AEF91+33]

**Comment by ckerr** [comment]
@saber-hyw, what version number of Electron were you using, and on what OS?

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our [comment](https://github.com/electron/electron/issues/11446#issuecomment-352825707). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by rgimbel** [comment]
I have run into the same issue.  I am doing my initial dev with electron@1.7.11 /  electron-download@3.3.0  on a Mac 10.12.6..  This is my code and the issue might be with the way I am coding but found this during my googling. 
 `
const path = require('path');
const { app, Menu, Tray, BrowserWindow } = require('electron');

let tray = null;

app.on('ready',() => {
  tray = new Tray(path.join(__dirname,'Client.png'));
  const menu = Menu.buildFromTemplate([
    {
      label: 'Start Chat',
      click() {
        let win = new BrowserWindow({width: 600, height: 400})
        if(win.isClosable()){
          console.log('Should be able to close window..')
        }
        win.on('closed', () => {
          win = null
          console.log('Close the Chat!')
        })

        // Load a remote URL
        win.loadURL('<REDACTED - but trying to wrap bomgar chat client (session start url)>')
      }
    },
    {
      label: 'Quit',
      role: 'quit'
    }
  ])
  tray.setToolTip('Support Client');
  tray.setContextMenu(menu);
})`

I would be happy to share the URL if it would help testing..  when selected from the tray it takes about a minute for the chat to start and I cannot close the window. (again this might be something outside electron) but after the chat session does start and is ended. I get the error the original poster submitted.

`> electron .

Should be able to close window..
Close the Chat!
[68015:0130/120822.376790:FATAL:url_request_context.cc(134)] Check failed: false. Leaked 1 URLRequest(s). First URL: http://wpad/wpad.dat.
0   Electron Framework                  0x000000010b6ad7bc crashpad::CloseMultipleNowOrOnExec(int, int) + 934076
1   Electron Framework                  0x000000010b677da3 crashpad::CloseMultipleNowOrOnExec(int, int) + 714403
2   Electron Framework                  0x000000010cf76986 crashpad::CloseMultipleNowOrOnExec(int, int) + 26923654
3   Electron Framework                  0x000000010cf767b9 crashpad::CloseMultipleNowOrOnExec(int, int) + 26923193
4   Electron Framework                  0x000000010cf769ce crashpad::CloseMultipleNowOrOnExec(int, int) + 26923726
5   Electron Framework                  0x000000010b5b8e0a brightray::URLRequestContextGetter::~URLRequestContextGetter() + 170
6   Electron Framework                  0x000000010b5b8eb9 brightray::URLRequestContextGetter::~URLRequestContextGetter() + 9
7   Electron Framework                  0x000000010b5b8ece brightray::URLRequestContextGetter::~URLRequestContextGetter() + 14
8   Electron Framework                  0x000000010cf78fa9 crashpad::CloseMultipleNowOrOnExec(int, int) + 26933417
9   Electron Framework                  0x000000010b4cb169 atom::AtomAccessTokenStore::SaveAccessToken(GURL const&, std::__1::basic_string<unsigned short, base::string16_char_traits, std::__1::allocator<unsigned short> > const&) + 761
10  Electron Framework                  0x000000010b4cb14e atom::AtomAccessTokenStore::SaveAccessToken(GURL const&, std::__1::basic_string<unsigned short, base::string16_char_traits, std::__1::allocator<unsigned short> > const&) + 734
11  Electron Framework                  0x000000010b47d09d base::internal::BindState<void (*)(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, mate::Arguments*)>::Destroy(base::internal::BindStateBase const*) + 349
12  Electron Framework                  0x000000010b47d081 base::internal::BindState<void (*)(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, mate::Arguments*)>::Destroy(base::internal::BindStateBase const*) + 321
13  Electron Framework                  0x000000010b47af69 atom::api::Protocol::~Protocol() + 249
14  Electron Framework                  0x000000010b47d539 base::internal::BindState<void (*)(scoped_refptr<brightray::URLRequestContextGetter>), scoped_refptr<brightray::URLRequestContextGetter> >::Destroy(base::internal::BindStateBase const*) + 153
15  Electron Framework                  0x000000010b47d529 base::internal::BindState<void (*)(scoped_refptr<brightray::URLRequestContextGetter>), scoped_refptr<brightray::URLRequestContextGetter> >::Destroy(base::internal::BindStateBase const*) + 137
16  Electron Framework                  0x000000010b47d519 base::internal::BindState<void (*)(scoped_refptr<brightray::URLRequestContextGetter>), scoped_refptr<brightray::URLRequestContextGetter> >::Destroy(base::internal::BindStateBase const*) + 121
17  Electron Framework                  0x000000010b47d509 base::internal::BindState<void (*)(scoped_refptr<brightray::URLRequestContextGetter>), scoped_refptr<brightray::URLRequestContextGetter> >::Destroy(base::internal::BindStateBase const*) + 105
18  Electron Framework                  0x000000010b47d4f9 base::internal::BindState<void (*)(scoped_refptr<brightray::URLRequestContextGetter>), scoped_refptr<brightray::URLRequestContextGetter> >::Destroy(base::internal::BindStateBase const*) + 89
19  Electron Framework                  0x000000010b47d4ed base::internal::BindState<void (*)(scoped_refptr<brightray::URLRequestContextGetter>), scoped_refptr<brightray::URLRequestContextGetter> >::Destroy(base::internal::BindStateBase const*) + 77
20  Electron Framework                  0x000000010b47d4d9 base::internal::BindState<void (*)(scoped_refptr<brightray::URLRequestContextGetter>), scoped_refptr<brightray::URLRequestContextGetter> >::Destroy(base::internal::BindStateBase const*) + 57
21  Electron Framework                  0x000000010b47d4b6 base::internal::BindState<void (*)(scoped_refptr<brightray::URLRequestContextGetter>), scoped_refptr<brightray::URLRequestContextGetter> >::Destroy(base::internal::BindStateBase const*) + 22
22  Electron Framework                  0x000000010b6be258 crashpad::CloseMultipleNowOrOnExec(int, int) + 1002328
23  Electron Framework                  0x000000010b6877db crashpad::CloseMultipleNowOrOnExec(int, int) + 778459
24  Electron Framework                  0x000000010b687b2c crashpad::CloseMultipleNowOrOnExec(int, int) + 779308
25  Electron Framework                  0x000000010b687ef3 crashpad::CloseMultipleNowOrOnExec(int, int) + 780275
26  Electron Framework                  0x000000010b68a715 crashpad::CloseMultipleNowOrOnExec(int, int) + 790549
27  Electron Framework                  0x000000010b6874ae crashpad::CloseMultipleNowOrOnExec(int, int) + 777646
28  Electron Framework                  0x000000010b6a0503 crashpad::CloseMultipleNowOrOnExec(int, int) + 880131
29  Electron Framework                  0x000000010b910888 crashpad::CloseMultipleNowOrOnExec(int, int) + 3436936
30  Electron Framework                  0x000000010b910a16 crashpad::CloseMultipleNowOrOnExec(int, int) + 3437334
31  Electron Framework                  0x000000010b6c0dd9 crashpad::CloseMultipleNowOrOnExec(int, int) + 1013465
32  Electron Framework                  0x000000010b695647 crashpad::CloseMultipleNowOrOnExec(int, int) + 835399
33  libsystem_pthread.dylib             0x00007fffc9af593b _pthread_body + 180
34  libsystem_pthread.dylib             0x00007fffc9af5887 _pthread_body + 0
35  libsystem_pthread.dylib             0x00007fffc9af508d thread_start + 13
`
