### ISSUE TITLE
Feature Request: Conditionally intercept protocol

### ISSUE THREAD

**Issue by mlegore** [electron/electron#11450]
For the intercept{*}Protocol methods, it would be very powerful if we were given a reference to the previous protocol handler, the method could do whatever processing, and either handle the request entirely itself or transform it and pass it along to the next handler. With this you could create handler chains similar to how you might on a web service stack.

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
