### ISSUE TITLE
<input> "accept" prop does not work properly

### ISSUE THREAD

**Issue by Voyager-One** [electron/electron#11456]
* Electron version:
^1.7.9
* Operating system:
macOS 10.13.1
### Expected behavior

the accept prop of <input type:"file"> should reject the files which are not under the accept prop,
### Actual behavior

I test the plain HTML with accept prop bound to <input > which worked properly as expected on safari firefox and chrome, HOWEVER, on electron app, it never worked! , as the accept prop does not exist.
### How to reproduce
Create a basic electron app with HTML <input type:"file" accept:"*"> and you would get this issue, however, I only have Mac, so this may not happen on win machines. And I  assume that was because of the new macOS update with APFS? By the way, the` accept` prop won't work with some React file selector components either.

**Comment by sofianguy** [comment]
Hi @Voyager-One, can you provide us with some steps to reproduce this?

**Comment by camiloei** [comment]
It's not working for me either.

I'm using:

- **electron**: ^1.7.10
- **OS**: macOS High Sierra 10.13.2

My implementation is pretty simple: 

I have a index HTML file with a input tag

```<input type="file" accept="video/*" />```

and my app is:

```
...

const htmlViewPath = `file://${__dirname}/index.html`

app.on('ready', () => {
  const mainWindow = new BrowserWindow({})
  mainWindow.loadURL(htmlViewPath);
})
```

Then I can select any file when pressing the input element. But when I select one I get this log message:

```
objc[13844]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffa42e4b68) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x10f0d1cd8). One of the two will be used. Which one is undefined.
```

Hope this helps to reproduce the issue!

**Comment by dengyaolong** [comment]
+1

**Comment by dengyaolong** [comment]
I want to fix it and will pull request in 2 days.

**Comment by Voyager-One** [comment]
sorry I add the how-to-reproduce this late because of the school final week:(

**Comment by hmontes** [comment]
Same error with @camiloei code

> objc[9155]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9ace3b68) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x11ab38cd8). One of the two will be used. Which one is undefined.

MacOs High Sierra 10.13.3

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
