### ISSUE TITLE
simpleFullscreen BrowserWindow too short when Dock is hidden.

### ISSUE THREAD

**Issue by lynaghk** [electron/electron#11468]
* Electron version: 1.8.2-beta.3
* Operating system: OS X 10.9.5

### Expected behavior

A simpleFullscreen BrowserWindow should take up the full screen, regardless of Dock settings.

### Actual behavior

The window is short by the height of the OS X title bar.

### How to reproduce

See [reproducible repo](https://github.com/lynaghk/reproducible-reports/tree/master/5-electron-simple-fullscreen-no-dock).
Run:

```sh
yarn install

yarn start-dock
yarn start-no-dock
```

to compare the two behaviors.

See https://github.com/electron/electron/pull/10254#issuecomment-352416494 for a discussion of the possible issue and fix.

My OS X version is too old to build Electron, but it should take only 5 minutes for someone with an Electron buildchain setup on OS X to test the hypothesis of commenting out [this line](https://github.com/electron/electron/blob/f01cbf04820b779f1b0ca4f0af610974a2f72053/atom/browser/native_window_mac.mm#L1423)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by lynaghk** [comment]
@sofianguy The fix has already been merged into 2.0.x and later, so we can actually close this issue! Thanks.
