### ISSUE TITLE
Work required to enable remaining DCHECKs

### ISSUE THREAD

**Issue by deepak1556** [electron/electron#11464]
After https://github.com/electron/electron/pull/11396 , there are still a few dchecks that are manually patched in libcc https://github.com/electron/libchromiumcontent/pull/413

- [x] `base/memory/weak_ptr.cc` - There is only one instance of this failure remaining which is in the protocol module `JsAsker` class, @zcbenz will refactor the class after getting https://github.com/electron/electron/pull/11357 done.

- [ ] `content/browser/frame_host/navigation_controller_impl.cc` - Its not possible to enable it currently as we require the navigation controller history to always be cleared https://github.com/electron/electron/blob/master/atom/browser/api/atom_api_web_contents.cc#L1061.

- [ ] `content/browser/frame_host/render_frame_host_impl.cc` - Its because the pdf viewer implementation for iframes in webui requires to have webui policy bindings enabled, it makes the parent and child nodes in the same render frame host to have different binding policy, which is against chromium's expectation. This can be solved by moving pdf viewer for iframes to use OOPIF.

~~`content/browser/renderer_host/render_widget_host_view_mac.mm` - The patch created in https://github.com/electron/electron/issues/170 , https://github.com/electron/libchromiumcontent/commit/b27290717c08f8c6a58067d3c3725d68b4e6a2e5 breaks this, @zcbenz is this something that can be re-enabled ?~~

- [x] `blink::SchemeRegistry` methods should be invoked before any render threads are created, otherwise we risk crashing on [DCHECK(WTF::IsBeforeThreadCreated)](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/platform/weborigin/SchemeRegistry.cpp?sq=package:chromium&l=105) . I have moved explicit calls to the right place https://github.com/electron/electron/pull/11396/commits/67445790f241bdb9bff342960d8fb35f135ecde3, but we have exposed these methods through `api::WebFrame::RegisterURLSchemeAsPrivileged` that can be invoked at any point in the app's lifetime. Fixing this would break the current api, thoughts on how to handle this ?

- [x] `storage/browser/quota/client_usage_tracker.cc` and `ui/latency/latency_histogram_macros.h` - the former is already removed in 63 and the other one is removed in 64.

- [ ] Remove usage of `base::ThreadRestrictions::ScopedAllowIO` where possible, we are using it as a workaround to allow IO calls on the main thread.

/cc @alespergl @alexeykuzmin @codebytere @MarshallOfSound @ckerr

**Comment by zcbenz** [comment]
> content/browser/renderer_host/render_widget_host_view_mac.mm - The patch created in #170 , electron/libchromiumcontent@b272907 breaks this, @zcbenz is this something that can be re-enabled ?

It is patch to prevent Chromium from hijacking `Command+XXX` keyboard shortcuts, not really related to the DCHECK.

**Comment by deepak1556** [comment]
Sorry I wasn't clear about the problem. [CommonWebContentsDelegate::HandleKeyBoardEvent](https://github.com/electron/electron/blob/master/atom/browser/common_web_contents_delegate_mac.mm#L33) sends event to the menu but it causes the DCHECK in [RenderWidgetHostViewMac::WasKeyEquivalent](https://cs.chromium.org/chromium/src/content/browser/renderer_host/render_widget_host_view_mac.mm?q=package:chromium&l=2155) fail. Removing that aforementioned patch https://github.com/electron/libchromiumcontent/commit/b272907 fixes the failure but its not the right fix, hence I have manually disabled that particular DCHECK. This was visible by performing any shortcut keystrokes in devtools.

**Comment by zcbenz** [comment]
In this case the DCHECK should be commented out since it is asserting a branch explicitly enabled by our patch.

**Comment by miniak** [comment]
@deepak1556 is this still relevant?
