### ISSUE TITLE
Segfault: nativeImage createFromNamedImage HSL

### ISSUE THREAD

**Issue by defeated** [electron/electron#11460]
* Electron version: `v1.8.2-beta.3`
* Operating system: `macOS High Sierra 10.13.1 (17B1003)`

### Expected behavior

The button should be white.

### Actual behavior

Segfault

### How to reproduce

Minimal test case:

```javascript
// touchbar.js

const {app, BrowserWindow, TouchBar, nativeImage} = require('electron')
const {TouchBarButton} = TouchBar

const icon = nativeImage.createFromNamedImage('NSTouchBarAudioInputMuteTemplate', [-1, 0, 1])
const button = new TouchBarButton({ icon: icon })
const touchBar = new TouchBar([ button ])

let window
app.once('ready', () => {
  window = new BrowserWindow()
  window.setTouchBar(touchBar)
})
```

```bash
./node_modules/.bin/electron touchbar.js
```

Exits immediately with apple crash dialog. If I remove the HSL `[-1, 0, 1]` arg it runs successfully.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by sunemily** [comment]
I'm running into the same issue on Electron v6.13.2 where setting any value of HSL will cause the app to crash.

**Comment by ninolam** [comment]
@sunemily me too with electron v12.0.1, have you find a solution ?

**Comment by ghost** [comment]
As of the latest version of electron 40.4.1 on macOS Tahoe 26.3 I am also experiencing this issue
`nativeImage.createFromNamedImage("info.circle", [ -1, 0, 1 ]).resize({ width: 16, height: 16 });`
