### ISSUE TITLE
Feature Request: IOS / Android development using Brave

### ISSUE THREAD

**Issue by John-AZ1** [electron/electron#11463]
[_Brave_](https://brave.com/) is a cross platform browser built on chromium, that as (far as I know) also has a chromium based ios and android app. Would this allow for Electron to be developed for these platforms? Please look into it.

Thanks in advance,

John AZ1.

**Comment by sethlu** [comment]
Issue https://github.com/electron/electron/issues/562 seems to indicate that it's quite unlikely to develop Electron for iOS and Android due to that most of Electron's APIs don't apply.

**Comment by aprilmintacpineda** [comment]
@sethlu is there a plan for Electron to support mobile app development?

**Comment by MarshallOfSound** [comment]
There is nothing on any roadmap at the moment, follow along with #562 for any developments
