### ISSUE TITLE
rest features of ffmpeg

### ISSUE THREAD

**Issue by brithbutter** [electron/electron#11462]
I'm trying to stream my screen to a rtmp server but the API documents only provide direct reuse by video tag. Is there any means for me to understand how electron package the rest options of ffmpeg?

* Electron version: 1.7.9
* Operating system: ubuntu 17

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
