### ISSUE TITLE
Browser window freeze on Raspberry Pi 3

### ISSUE THREAD

**Issue by alpharen** [electron/electron#11472]
* Electron version: 1.7.x
* Operating system: Raspbian 9.1

On Raspberry Pi, I tried [electron-quick-start](https://github.com/electron/electron-quick-start) and official electron 1.7.10 armv7l [build,](https://github.com/electron/electron/releases/download/v1.7.10/electron-v1.7.10-linux-armv7l.zip) same issue.

### Expected behavior
When move the window or resize the window the content in brower window should repaint.

### Actual behavior
The content in brower window does not repaint properly or not repaint at all, and the menu response very slowly.

![wechat image_20171219141245](https://user-images.githubusercontent.com/67791/34143394-7cda18a0-e4c7-11e7-87a7-23ded4b51c68.png)
![wechat image_20171219141250](https://user-images.githubusercontent.com/67791/34143408-88617f60-e4c7-11e7-8493-0ed57eeac3ff.png)

### How to reproduce
just follow the [electron-quick-start](https://github.com/electron/electron-quick-start) guide.

**Comment by khyo** [comment]
I too had a similar set of issues arise on Electron 1.17.10 ARM.
Electron 2.0.0-beta.1 ARMv7 seems to fix the mentioned issues on Raspberry Pi 3.
However, in the beta the File Menu text is not visible.

**Comment by sofianguy** [comment]
closing due to above comment that reports this bug is fixed in 2.0.x
