### ISSUE TITLE
With Developer Tools open, frameless window can't close properly(retains)

### ISSUE THREAD

**Issue by BoOpenfin** [electron/electron#11478]
* Electron version: 1.6.13
* Operating system: MacOS High Sierra

### Expected behavior

With Developer Tools open, close frameless window should performs correctly.

### Actual behavior

![window-retain](https://user-images.githubusercontent.com/31855269/34165621-cb6adfa8-e4aa-11e7-93c5-dccf255070da.gif)

### How to reproduce

Create a frameless window with titlebar & closeButton. Then openDevTools as an independent window. Close the main window directly, the window resource seems retains.

**Comment by codebytere** [comment]
closing as duplicate in favor of your other opened issue
