### ISSUE TITLE
Electron 1.8.1 shows white screen on quick load url 

### ISSUE THREAD

**Issue by juturu** [electron/electron#11474]
* Electron version: 1.8.1
* Operating system: Mac

### Expected behavior
App shouldn't be stuck on white screen.

### Actual behavior
1. Load URL in browser window with `nodeIntegration` turned off and `webviewTag` turned on.
2. While the load is happening, perform one more load url.
3. This hits a white screen. On the second load url, we only notice `will-navigate` fires but not `did-navigate` or `did-fail-load`. 

If we add a sleep between step 1 and 2 then this issue doesn't repro. No crash events being observed. This issue is not repro'ing on 1.7.3.
Any ideas on what could be going wrong or help in investigating this further?

### How to reproduce
Working on getting a consistent and simple repro. This is hitting in a setup which runs UI tests.

**Comment by ckerr** [comment]
Thanks for reporting this bug. If you find a simple repro that would be great.

**Comment by codebytere** [comment]
@juturu were you able to find a simple repro?

**Comment by alexeykuzmin** [comment]
@codebytere Talked to Hari today, no simple repro yet =(

**Comment by sofianguy** [comment]
@juturu any updates?

**Comment by sofianguy** [comment]
@juturu We are no longer releasing bug fixes for versions earlier than 2.0.x. Feel free to reopen if you see this bug on later versions
