### ISSUE TITLE
Missing feature: "Always on visible workspace" (for linux)

### ISSUE THREAD

**Issue by AntonLydike** [electron/electron#11486]
* Electron version: 1.4.15 (but not found in docs at all)
* Operating system: XUbuntu 16.4

### Expected behavior

There should be a method like `win.setAlwaysOnVisibleWorkspace(state)` or something along those lines.

### Actual behavior

Method doesn't exist.

### How to reproduce

-

**Comment by codebytere** [comment]
Per https://github.com/electron/electron/pull/1309 this has been implemented for a while now, so i'm going to go ahead and close this.
