### ISSUE TITLE
Debug build encountered DCHECK failure in latency_tracker.cc

### ISSUE THREAD

**Issue by zcbenz** [electron/electron#11485]
When running tests on Windows I can get this assertion occasionally:

```
[4540:1220/192211.019:FATAL:latency_tracker.cc(219)] Check failed: rendering_scheduled_component.last_event_time >= original_component.first_event_time (15344887000 bogo-microseconds vs. 15344888000 bogo-microseconds)
```

Which seems to be caused by this line:
https://cs.chromium.org/chromium/src/ui/latency/latency_tracker.cc?sq=package:chromium&l=245-248

This DCHECK seems to be performance related and happens when machine is slow. It should be responsible for recent Windows CI hangs.

/cc @deepak1556

**Comment by deepak1556** [comment]
Related https://chromium-review.googlesource.com/c/chromium/src/+/780182  which gets rid of the DCHECK eventually. We can backport it ?

**Comment by zcbenz** [comment]
> Related https://chromium-review.googlesource.com/c/chromium/src/+/780182 which gets rid of the DCHECK eventually. We can backport it ?

Sounds good to me.
