### ISSUE TITLE
DNS Caching?

### ISSUE THREAD

**Issue by SethTurin** [electron/electron#11480]
* Electron version: 1.8.4
* Operating system: mac and windows

Hi

I recently changed the dns for a website of mine, so the domain now points to a new host. In Electron, I load my site into a browserwindow via mainWindow.loadURL. If I open my site's domain in chrome, to the new host, so it looks like the dns has propagated. If I open the site in Electron, however, it still opens to the old host. 

Does electron do any kind of dns caching that I can clear somewhere?

Thanks!

**Comment by SethTurin** [comment]
It finally resolved, so my issue is solved. It's still a curiosity that the behavior was different in electron than in chrome. But in the end it did resolve on its own, so maybe this is ultimately a non issue.

**Comment by MarshallOfSound** [comment]
@SethTurin DNS queries are cached in multiple places throughout your network stack, it looks like your chrome cache just got refreshed slightly faster than Electrons 👍
