### ISSUE TITLE
Is it possible to bind a click event on body tag of the third-party page in webview?

### ISSUE THREAD

**Issue by JedJiang** [electron/electron#11498]
Hey guys,

I have a webview that links a third-party page on the main page ,so I want to listen the click event in the third-party page, is there any suggestions to implement? thanks in advance!

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
