### ISSUE TITLE
How to control system volume

### ISSUE THREAD

**Issue by kevin19931015** [electron/electron#11494]
I want to control system volume in  my application.
How to get it.

**Comment by kevin19931015** [comment]
electron version:1.8.1
operating system: windows 7

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
