### ISSUE TITLE
How to hide icon in dialog titlebar

### ISSUE THREAD

**Issue by stanleyxu2005** [electron/electron#11491]
I'm using Electron 1.7.9 on Windows. When I call a warning dialog, the yellow icon will appear twice. One in titlebar and another in the window body area, which looks not clean enough. I'd like to know, whether we can hide the icon in titlebar or specify another icon in the window body area.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by stanleyxu2005** [comment]
This is actually a feature request
