### ISSUE TITLE
With Developer Tool open, window can't close properly

### ISSUE THREAD

**Issue by BoOpenfin** [electron/electron#11502]
* Electron version: 1.7.10
* Operating system: MacOS

### Expected behavior
With Developer Tools open, close window should performs correctly.

### Actual behavior
![windowretain](https://user-images.githubusercontent.com/31855269/34266085-07c6da5a-e646-11e7-8947-1cdfb3ac73ac.gif)

### How to reproduce

The code base can be seen from [my repo](https://github.com/BoOpenfin/electron-quick-start/tree/issue/closeWindow).
  $ git clone https://github.com/BoOpenfin/electron-quick-start.git -b issue/closeWindow
  $ npm install
  $ npm start

**Comment by BoOpenfin** [comment]
It's not only the [frameless window issue](https://github.com/electron/electron/issues/11478).

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
