### ISSUE TITLE
Shell.openExternal() behaves abnormally with Chrome Update in Mac OSX

### ISSUE THREAD

**Issue by Syed-Umair** [electron/electron#11500]
* Electron version: 1.7.10
* Operating system: Mac OS High Sierra and Mac OS Sierra

### Expected behavior
shell.openExternal() should open the url in the chrome new tab.

### Actual behavior
If you open a url using shell.openExternal() when my chrome had received a update in Mac and I didn't relaunch the chrome it will open a empty chrome tab. 

### How to reproduce
You can duplicate this issue by going back to older version of chrome in mac and check for update but don't relaunch it.

Now try opening a url using shell.openExternal() it will just give you a empty tab.

**Comment by Thomas101** [comment]
I think this is an issue with Chrome/High Sierra. We've found that updating chrome/macOS/changing the default browser to Safari, then back to chrome seemed to fix it.

**Comment by Syed-Umair** [comment]
@Thomas101 I don't think so thomas, It fixes if i relaunch my chrome until then it opens a empty tab on request. I don't want to rely on restarting the chrome to fix it. I think  the shell.openExternal() is trying to access the older chrome version.

**Comment by KagamiChan** [comment]
I've seen the same behaviour for non-Electron apps e.g. Telegram for opening and external link, so it does not seem to me a bug, or at least not on Electron's side.

**Comment by MarshallOfSound** [comment]
This is an issue with Chrome itself, when it has a staged update it uses that to launch the URL which results in an unexpected state.  You should raise this on a chrome bug tracker 👍

**Comment by dengyaolong** [comment]
Um， it‘s a but with `open`. I think.
I resolve this problem by find google chrome path. and use command line to open link.

**Comment by Syed-Umair** [comment]
@dengyaolong , Actually I am also following the same using a shell script to open the chrome. Thanks guys for the help.

**Comment by dengyaolong** [comment]
@Syed-Umair On Mac os I use oascript, shell sometimes not work...
