### ISSUE TITLE
Electron not detecting specific MIDI synthesizer.

### ISSUE THREAD

**Issue by FireController1847** [electron/electron#11503]
* Electron version: 1.7.10 (hehehe Minecraft (I'm so immature lol))
* Operating system: Windows 10 Home, Fall Creators Update

### Expected behavior
When using two MIDI devices (in this case [loopMidi](https://www.tobias-erichsen.de/software/loopmidi.html) and [Keppy's Synthesizer](https://github.com/KaleidonKep99/Keppy-s-Synthesizer)), both devices will show up in the input/output areas. Since loopMidi does both input and output, it should show up in both MIDI input and MIDI output. Keppy's Synth should only show on MIDI output.

### Actual behavior
loopMidi shows up fine in both the MIDI input and MIDI output, but Keppy's Synth is nowhere to be seen. As stated in https://github.com/KaleidonKep99/Keppy-s-Synthesizer/issues/82, it could have been a Chromium issue recently fixed, but I'm not sure.

### How to reproduce
Open the console in essentially any electron app.
```js
navigator.requestMIDIAccess().then(midi  => {
  for (const item of midi.outputs) {
    console.log(item[1]);
  }
}).catch(console.error);
```
1. Run this. With loopMidi and Keppy's Synth installed, you'll see that only loopMidi shows up.
2. Now run this in Google Chrome. With both installed, you'll see that *both* show up in the output.

### Other
I didn't include a repository since it's so easy to reproduce in essentially any electron app I didn't bother.

### Images
Electron on left, Chrome on right.
![A gif showing the output of both Electron and Chrome side by side.](https://imgur.com/kHyDzmX.gif)

**Comment by FireController1847** [comment]
As @KaleidonKep99 stated in the other issue, this may be relevant. https://bugs.chromium.org/p/chromium/issues/detail?id=672793

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by FireController1847** [comment]
Apologies on not being consistent with keeping this up to date. It seems that you guys have fixed the issue, which is very happy to hear! Thanks a lot.
