### ISSUE TITLE
Cookies on net redirect

### ISSUE THREAD

**Issue by rdepena** [electron/electron#11505]
* Electron version: 1.7.10
* Operating system: Win 7/10

### Expected behavior
The net API should allow cookies to be set on a redirect request using `followRedirect`

### Actual behavior
As per [Cookie handling in net module](https://github.com/electron/electron/issues/8891) the net module will not send cookies unless we set them manually. This becomes a problem when following a redirect as we can no longer change the request headers before using `followRedirect`.

### How to reproduce

Given a Url that will redirect with additional cookies,  there is no way (Without starting a new request) to add the cookies to the redirect request:

Repo:
https://github.com/rdepena/net-cookie-issue

```bash
npm install
# Run the server
node server
# Run the app
npm start
```

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
