### ISSUE TITLE
menu.popup x-y position options does not work

### ISSUE THREAD

**Issue by ivarptr** [electron/electron#11514]
* Electron version: v1.8.2-beta.3
* Operating system: macOS 10.13

> menu.popup([browserWindow, options])

context menu always popup at the current mouse cursor position even if pass x, y into options.

**Comment by anurocha** [comment]
@ivarptr  how did you use test this API?
have you tested by put both 'x' and 'y'?

**Comment by sethlu** [comment]
@ivarptr @anurocha The API should be fixed in https://github.com/electron/electron/pull/11499.

**Comment by ivarptr** [comment]
@sethlu Thanks!

**Comment by xthdraft** [comment]
Is this fixed?  In v2.0.1 the  pop -up seems to appear at the click position.

In developer console:

**var menu = remote.Menu;
var mymenu = new menu();
mymenu.popup(remote.getCurrentWindow(),0,0);**  // or 0,100, or 100,0, or 800,500, or any x,y

// menu always pops up  adjacent to the right of the click point

**Comment by Truth0906** [comment]
Me too

**Comment by sohailsarfaraz** [comment]
Menu.popup(mainWin, 100, 100)
it is not working

**Comment by JoseCadenas** [comment]
Im having the same issue
