### ISSUE TITLE
Run without GUI (basically launch as node.js)?

### ISSUE THREAD

**Issue by greggman** [electron/electron#11515]
I currently have an electron app that uses express to run a local server. It works great. Except ... sometimes the user wants to run the server on port 80. AFAICT to do that I have to spawn an external program and ask for privilege escalation. Which is fine, except that it seems in order to continue to use my express server I'd have to bundle node.js because I don't want the server itself to show any GUI. This seems silly given that node.js or the API is already available in Electron.

So, it would be nice to be able to launch Electron with no GUI. Basically launch as node like `electron --node-only somescript.js`

Note that I tried just not opening a window when starting Electron but at least on macOS I still get an icon in the dock and clicking that icon a default menu bar appears (My code is not making a menu in this case).

Is there is some other way to prevent all GUI? If not then a feature suggestion of the ability to launch Electron with no GUI.

**Comment by MarshallOfSound** [comment]
Setting the environment variable `ELECTRON_RUN_AS_NODE` will do what you describe in a spawned process. :+1:

**Comment by superhawk610** [comment]
Looks like this should fix https://github.com/joshwcomeau/guppy/issues/44.

**Comment by junjielyu13** [comment]
how can I set this environment variable **ELECTRON_RUN_AS_NODE**?

**Comment by junjielyu13** [comment]
I have similar requirement to him. I need a linux server (without GUI)  to run the Electron application. When this application starts, it will open an Express web server. But I ran into this issue:

![image](https://github.com/electron/electron/assets/74879056/2e546782-0a61-4abe-bac6-ade80521e7b6)

Is there any way to run application on Linux server without GUI?

**Comment by icoco** [comment]
solved ?
