### ISSUE TITLE
Context menu freezes window

### ISSUE THREAD

**Issue by Tyriar** [electron/electron#11512]
* Electron version: 1.8.2-beta.3
* Operating system: macOS (I think it applies to all)

### Expected behavior

Triggering a context menu on a window should not freeze content. Note that Chrome does not freeze.

### Actual behavior

Context menus will freeze all rendering. Once the context menu is dismissed it is clear that JS was running in the background, just the window was not being re-rendered.

### How to reproduce

```
git clone https://github.com/Tyriar/electron-quick-start -b canvas_context_menu
npm install
npm start
```

Notice there is a canvas that is constantly being drawn to, right click on the page to trigger the context menu and freeze the canvas. Once the context menu is dismissed the canvas will start rendering once more.

**Comment by bpasero** [comment]
This works as expected because VSCode is not using the async option for context menus. This issue will go away once we update to a newer Electron because it looks like the async option is the new default, and the sync option was removed (https://github.com/electron/electron/issues/11242)

**Comment by Tyriar** [comment]
Why would Electron even want to expose an API to show a context menu if it blocks the renderer when there's an alternative then? 😕

**Comment by bpasero** [comment]
@Tyriar that is actually not the only API, the dialog API can also block.
