### ISSUE TITLE
Horrible Scrolling on trackpad

### ISSUE THREAD

**Issue by utk-dev** [electron/electron#11517]
Softwares made on electron have very jumpy scrolling on trackpad/touchpad (e.g. Microsoft's Visual Studio Code)

**Comment by sethlu** [comment]
@utk-dev are you experiencing a similar behavior on Chrome as well?

**Comment by xaviergonz** [comment]
It is a chrome bug, which is being fixed
https://bugs.chromium.org/p/chromium/issues/detail?id=713907#c28

**Comment by codebytere** [comment]
closing since this is out of our purview
