### ISSUE TITLE
Reversed Unicode character in HTML element `<textarea>` | HTML 元素 `<textarea>` 中颠倒显示的 Unicode 字符

### ISSUE THREAD

**Issue by LongTengDao** [electron/electron#11523]
* Electron version: 1.7.10
* Operating system: Windows 10 (64 bit)

### Expected behavior 预期表现

```html
<textarea>
oōóǒò
</textarea>
```

Unicode character in HTML element `<textarea>`.
HTML 元素 `<textarea>` 中的 Unicode 字符。

### Actual behavior 实际表现

```
oōòǒó
```

`ó` (U+00F3) and `ò` (U+00F2) are reversed while rendering.
`ó` (U+00F3) 与 `ò` (U+00F2) 渲染时发生颠倒。

### How to reproduce 如何重现

Just write a HTML code to render like above sample.
仅需如上文那样写一段 HTML 代码去渲染。

This problem exsited since v1.6.7 (when I began to use Electron) until now (I could speak English).
这个问题从 1.6.7 版本（当我开始使用 Electron 时）一直持续到现在（终于我都会讲英语了）。

**Comment by sethlu** [comment]
As a side note from my testing: It doesn't appear to be an issue on the `darwin` build 1.7.10.

**Comment by LongTengDao** [comment]
@sofianguy Hi!

Is there any progress?

Or clear why could this happen?

Thanks.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by LongTengDao** [comment]
> The version of Electron you reported this on has been superseded by newer releases.

Oh, thank you! I try it in v3.0.8, the problem is fixed. Although I still wonder how could that bug happen, I will go ahead and close the this issue.

**Comment by LongTengDao** [comment]
I try it in v1.7.10 just now, it disappeared. It's so strange.

I tried it many times in many cases, when I opened this issue. The problem only appear in Electron, not in Chrome (so not in browser core nor Windows).
