### ISSUE TITLE
Scroll in webview

### ISSUE THREAD

**Issue by MerDenchik** [electron/electron#11522]
* Electron version: 1.7.9
* Operating system: Elmentary OS Loki (Ubuntu)

How to check if there is horizontal scroll in <webview>?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
