### ISSUE TITLE
Javascript doesnt run in webview

### ISSUE THREAD

**Issue by MerDenchik** [electron/electron#11521]
* Electron version: 1.7.9
* Operating system: Elementary OS Loki (Ubuntu)

### Expected behavior

Javascript code just should run in <webview>

### Actual behavior

document.getElementById(...).executeJavaScript is not a function

### How to reproduce

1. Just make <webview id="github" src="https://github.com"></webview>
2. Run this script: document.getElementById('github').executeJavaScript('alert("It doesnt work")');

**Comment by MarshallOfSound** [comment]
Please provide a sample based on `electron-quick-start` so we can reproduce whatever issue this is

**Comment by MerDenchik** [comment]
oh, github had hidden text '<webview>'

**Comment by Sertion** [comment]
[document.getElementById](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementById) returns an [Element](https://developer.mozilla.org/en-US/docs/Web/API/Element). These are distinct from Electrons [webContents](https://electronjs.org/docs/api/web-contents) and does not share methods.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our [comment](https://github.com/electron/electron/issues/11521#issuecomment-353964208). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
