### ISSUE TITLE
Detailed Contribution Instructions

### ISSUE THREAD

**Issue by rynobax** [electron/electron#11525]
I am looking to get started contributing to Electron, however there are not any instructions on how to do so in the [contribution guide](https://github.com/electron/electron/blob/master/CONTRIBUTING.md).  I can take a shot at some instructions after I figure it out, but if any experienced contributors want to make something before then I would certainly appreciate it.

**Comment by sethlu** [comment]
Hi @rynobax, thanks for your interest in contributing to Electron! 🎉 

I'm not very experienced with developing new features, but more details regarding the developmental side can be found under in the `docs` directory (https://github.com/electron/electron/tree/master/docs#development); there you can read about the build instructions to begin with--it really boils down to a few steps:

1. (Fork &) clone the repo, and go into the directory
1. `./script/bootstrap.py -v` (takes quite a while to download the assets)
1. `./script/build.py -c D` to build the debug target
1. Make changes and build again...

**Comment by sofianguy** [comment]
Hi @rynobax, are you looking to edit our contributing guidelines so that the instructions are more clear or are you looking for how to get started with contributing?

**Comment by rynobax** [comment]
Both.  The instructions in the documentation was sufficient for me to build the project, so I don't think they need any editing, I would just suggest making the instructions easier to find.

**Comment by sofianguy** [comment]
@rynobax That is a good point. You are more than welcome to submit a pull request for that change! 🙂

**Comment by rynobax** [comment]
#11529 😃
