### ISSUE TITLE
Please add support for disable-direct-write

### ISSUE THREAD

**Issue by Hamulus** [electron/electron#11528]
Any font is blurry in any Electron-based application (Atom, Rodeo etc).
This could be solved by disable-direct-write flag earlier.

But electron-based applications do not support this flag sisnce Chrominum 52.
The common disclaimer for this issue is: "This feature is experimental and it was removed from Chrome and Chrominum since v.52"

But **Chrominum supports this flag at all.** For example Cent Browser https://www.centbrowser.com/
is always based on latest Chrominum, but supports this flag (this was a main reason that me and very many people choosed it instead of original Chrome).

So my feature request is to add support of this flag for Electron so that Electron-based applications would not harm eyes of users:)
I ask you, because developers of Atom and Rodeo directed me to Electron:)

The couple of examples (please look at the images by clicking them to see them at natural size_):
Latest Atom:
![atom-blur](https://user-images.githubusercontent.com/6650292/34381178-ee19b4fc-eb17-11e7-927f-6a4721b2077e.jpg)

Latest Chrome:
![chrome_blur](https://user-images.githubusercontent.com/6650292/34381181-fc715ce4-eb17-11e7-91b0-0661c0e1adc1.jpg)

Latest CentBrowser (based on Chrominum 62)
![cent-sharp](https://user-images.githubusercontent.com/6650292/34381196-0e0c5170-eb18-11e7-8ad6-4312f98c8d9e.jpg)

So I am sure that it is possible and will be usable for many people

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
