### ISSUE TITLE
Recaptcha throws invalid domain for site key when domain validation in recaptcha admin settings is set to true

### ISSUE THREAD

**Issue by reetou** [electron/electron#11536]
I'm trying to use recaptcha in Electron, recently I saw issues like 
https://github.com/electron/electron/issues/8414
https://github.com/electron/electron/issues/8345
And some more that I couldn't find now
After that I tried to implement it in my code but apparently it doesn't work properly now or I missed something. 

* Electron version: 1.7.9
* Operating system: macos high sierra 10.13.2

### Expected behavior

Successfully verify captcha and get g-response-key from request.

### Actual behavior

Electron throws alert 'No internet connection. Check connection and retry', then recaptcha widget renders and there are red text with error 'invalid domain for site key'

### How to reproduce

$ git clone https://github.com/reetou/zaechan
$ npm install
$ npm run dev
**Wait until app loaded**
**Press any of the 'Перейти в тред' buttons**
**Wait until route is loaded**
**See alert about internet connection**
**Press OK**
**Recaptcha loaded and error thrown**

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
