### ISSUE TITLE
I think you have a download link on your site in linux

### ISSUE THREAD

**Issue by omerfeyyaz** [electron/electron#11534]
I used windows, I switched to linux but I see that you are having difficulties with this electron.js linuxte. if you do not put your site in the new version. forget me but it is a nice product but i always get errors while loading with npm but i have always used windowsta

**Comment by felixrieseberg** [comment]
👋 Welcome! I have trouble understanding the request. What is broken?

**Comment by omerfeyyaz** [comment]
Okay, I do not need it anymore. Downloaded nndm (npm with graphical interface) and installed it
NOTE: Thank you for your help.
https://720kb.github.io/ndm/
