### ISSUE TITLE
Feature Proposal: Disabling Certain System Effects in the Node.js runtime

### ISSUE THREAD

**Issue by athanclark** [electron/electron#11537]
With the rise of crypto-currencies, Electron has found itself being used in mission-critical scenarios (unfortunately). Wallets like Cardano's [Daedalus](http://daedaluswallet.io/) rely on React.js embedded in Electron to facilitate their UI. However, this doesn't prevent a malicious user interface from somehow sending their backup code, for instance, over the network to a remote server. Through /deep/ audits, one can at least guarantee the absence of certain global variable usage, or calls to `require()`. However, why not just remove them from the v8 runtime altogether?

I was dreaming of something like `electron . --no-xhr --no-websocket --no-filesystem`, where a user could arbitrarily restrict electron's abilities, while they use sensitive software. I wrote a [question on StackOverflow](https://stackoverflow.com/questions/47953464/disable-networking-in-electron), in case anyone wants to correct me.

**Comment by felixrieseberg** [comment]
I believe what you're asking for already exists. Did you check out the documentation on security? Give it a read and let us know what the precise feature request is, otherwise I'll assume that we can close this.

https://electronjs.org/docs/tutorial/security

**Comment by codebytere** [comment]
Since there's been no follow-up, i'm going to go ahead and close this.
