### ISSUE TITLE
Screen sharing enumeration issue on Windows 10 with multiple screens causing black screen

### ISSUE THREAD

**Issue by arnaudbud** [electron/electron#11539]
* Electron version: 1.7.x
* Operating system: Windows 10

### Expected behavior
You should be able to share any screen connected on the computer, see the content of the screen you selected locally, as well as the other participants.

### Actual behavior
Once you select the screen you want to share on a multi-screen computer running Windows 10, you immediately get a black screen as the local stream when you select some of the screens. The other participants also get a black screen as the remote stream. 

### How to reproduce
1. On a Windows 10 computer or VM, with multiple screens connected, start sharing your screen with any Electron-based app. I reproduced the issue with the Symphony client, but also with this one which is fully open source:
  $ git clone https://github.com/jitsi/jitsi-meet-electron/
  $ npm install
  $ npm start
2. Once you select the screen you want to share, you immediately get a black screen as the local stream. The other participants also get a black screen as the remote stream. The issue appears to affect the screens randomly, sometimes the impacted screens are the screens number 2, 4, 6, sometimes after a reboot, 4, 5, 6, etc...

### Root cause analysis
At the system level, the way Windows 10 enumerates the screens is slightly different when a virtual video driver is involved.

On Electron, the picker window is managed by the DesktopCapturerSource object: https://github.com/electron/electron/blob/master/docs/api/structures/desktop-capturer-source.md and the mapping relies on a naming rule https://github.com/electron/electron/blob/master/atom/browser/api/atom_api_desktop_capturer.cc that fails when a non-conventional video driver is involved.

At Symphony, we experienced the exact same issue with CEF/Paragon. This is how we fixed the problem of the screen IDs enumeration: https://github.com/symphonyoss/SFE-DesktopClient-pgx/commit/85f0d719a11ffa9c03587ebe192b0009a721b7ff#diff-7e750064e4ad7245e99d95316f830119
This fix also addresses a similar issue we had with one monitor, but with Citrix XenDesktop installed (https://www.citrix.com/products/xenapp-xendesktop/), which also alters how Windows enumerates the screens.
FYI, this is how the WebRTC native code that does enumeration: https://webrtc.googlesource.com/src/+/master/modules/desktop_capture/win/screen_capture_utils.cc

![2017-12-21_18-19-38](https://user-images.githubusercontent.com/1677767/34426920-971be4e8-ebf0-11e7-916d-53a8dc53fa8a.png)
![2017-12-21_18-18-07](https://user-images.githubusercontent.com/1677767/34426919-970559e4-ebf0-11e7-9c30-4b3e2d1798aa.png)

**Comment by arnaudbud** [comment]
Performing additional testing today, I couldn't reproduce the issue with Electron 1.8.2-beta.3 (M59).

**Comment by arnaudbud** [comment]
Looks like this is a duplicate of https://github.com/electron/electron/issues/9933

**Comment by alexeykuzmin** [comment]
> Performing additional testing today, I couldn't reproduce the issue with Electron 1.8.2-beta.3 (M59).

Electron 1.8.3 is the latest stable version and it should include all fixed made in 1.8.2-beta.3.
I'm going to closed the issue, but feel free to reopen it if the bug still reproduces in the 1.8.3.
