### ISSUE TITLE
Every app with electron has app-name "Electron" in web notifications

### ISSUE THREAD

**Issue by Enrico204** [electron/electron#11549]
* Electron version: 1.7.8
* Operating system: Debian 9.3

### Expected behavior

"App-name" field (libnotify) in notifications coming from BrowserWindow (WebView perhaps?) should be filled with the name of the app (either "name" or "productName" from package.json), or at least it should be allowed to modify its value within Electron.

### Actual behavior

Every notification have "app-name" field set to "Electron"

### How to reproduce

Open a BrowserWindow object on any page which contains web notifications, such as https://developer.mozilla.org/en-US/docs/Web/API/notification

**Comment by ckerr** [comment]
#11913 might fix or mitigate this
