### ISSUE TITLE
Electron image

### ISSUE THREAD

**Issue by gaograce** [electron/electron#11540]
I use electron to make an app which show phone screenshot，when I operate the phone，the image will change(use minicap to get image(byte array) and then convert bytes to base64 and show in image). But the memory of renderer process increases quickly and never decreases. It even over 10G. If don't show image, only get bytes data, it is ok. Is it a bug? How can I show changed image without memory leak? I try clearCache, but useless.

**Comment by felixrieseberg** [comment]
You probably have a memory leak in your app. If you believe that this is an issue with Electron, please re-open the issue using the issue template and providing a reproduction repository.

**Comment by alecperkey** [comment]
I don't know if this is useful but here's some tests I did

https://bugs.chromium.org/p/chromium/issues/detail?id=805655
https://github.com/Microsoft/vscode/issues/42122
