### ISSUE TITLE
Snapping BrowserWindow to sides doesn't trigger move/resize events

### ISSUE THREAD

**Issue by blaatunga** [electron/electron#11554]
When snapping the BrowserWindow to the side of the Windows desktop (e.g. with WIN+Left/Right key), the events 'resize' and 'move' are NOT triggered.

* Electron version: 1.8.1
* Operating system: Windows 10

### Expected behavior

The events get triggered when the position/size of the window changes while AeroSnapping it

### Actual behavior

None triggered

### How to reproduce

Add event listeners for BrowserWindow 'move' and 'resize' events and snap the window with WIN + Left/Right key. See if the listeners got triggered and what is the reported position of the window.

**Comment by PerfectionCSGO** [comment]
@blaatunga Will the window dock to the edges of the screen if you drag to the edge of the screen?

I'm having this issue in 1.7.10 as well. I just upgraded from 1.4.4.

**Comment by blaatunga** [comment]
It docks, but the events are not triggered anyway. We register listeners for them and save the window position while one of them gets triggered, but nothing triggers while docking the window.
I assume this was always the issue, so not only in 1.8.1.

**Comment by PerfectionCSGO** [comment]
I actually can't get it to dock from version 1.4.14 and onwards when BrowserWindow's frame is set to false. This is on win32 Windows_NT 10.0.16299. But we may be having different issues then. ):

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
