### ISSUE TITLE
hexColorDWORDToRGBA is broken for transparent colors

### ISSUE THREAD

**Issue by josimi** [electron/electron#11556]
* Electron version: 1.7.10
* Operating system: Windows 8.1

### Expected behavior

8 character hexadecimal string is returned

### Actual behavior

1. _CxxThrowException | throw.cpp
2. std::_Xout_of_range | xthrow.cpp
3. std::basic_string_char,std::char_traits_char_,std::allocator_char_ _::assign | xstring
4. std::basic_string_char,std::char_traits_char_,std::allocator_char_ _::substr | xstring
5. atom::api::hexColorDWORDToRGBA

### How to reproduce

Call `hexColorDWORDToRGBA` for any value less than 256 to throw an exception. Additionally, incorrect results are returned in many cases when the alpha channel or red component is less than two hexadecimal digits.

**Comment by josimi** [comment]
I haven't been able to create a new branch for a PR on the electron repo (getting a 403 error from git), but I have created a fix and committed it to my local cloned repo: 90f0904b695bceb5de74a57219fe176c2cc2b2a6

**Comment by MarshallOfSound** [comment]
@josimi You should push your changes to your fork of the electron repo and PR them from there.

**Comment by josimi** [comment]
Thanks @MarshallOfSound. I have submitted a pull request now.

**Comment by josimi** [comment]
Pull request has been merged.
