### ISSUE TITLE
Memory leak when show image

### ISSUE THREAD

**Issue by gaograce** [electron/electron#11550]
Rss memory increases without decreasing when show images that changes quickly. (memory leak?)

* Electron version: 1.7.10
* Operating system:
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1036

### Expected behavior
Image changes normally and memory is stable

### Actual behavior
Memory increases gradually and use process.memoryUsage() to find that most is rss memory.

### How to reproduce
First, install adb command,  then link a phone and use 'adb devices' to make sure the phone state normal.

git clone https://github.com/gaograce/electron-image-memory-leak-example
npm install
npm start

click 'start' button to show image and then operate the phone to change image.

**Comment by MarshallOfSound** [comment]
@gaograce Can you provide a somewhat more minimal reproduction case, the memory leak (if there is one) could be occuring anywhere in that pipeline (native module, your byte parsing code, Etc.).  Can you reproduce this purely by changing the src of an image constantly?  And if so are you sure it doesn't happen in Chromium as well?

**Comment by gaograce** [comment]
I also build with nwjs，no memory leak.

**Comment by gaograce** [comment]
And if I don't show image and only operate bytes, no memory leak too.

**Comment by felixrieseberg** [comment]
Related: https://github.com/electron/electron/issues/11540

**Comment by alecperkey** [comment]
I don't know if this is useful but here's some tests I did

https://bugs.chromium.org/p/chromium/issues/detail?id=805655
https://github.com/Microsoft/vscode/issues/42122

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
