### ISSUE TITLE
Failed to set referrer policy: The value 'strict-origin-when-cross-origin' 

### ISSUE THREAD

**Issue by JensDebergh** [electron/electron#11558]
* Electron version: 1.7.9
* Operating system: Mac OS High Sierra

### Expected behavior

Loads external scripts which are injected into the page.

I'm using trello.js client script

https://developers.trello.com/v1.0/docs/clientjs

### Actual behavior

Popover does not work from within electron browser, in which I fallback to redirects within the browser. After redirect console displays failed to load resources.

### How to reproduce

<img width="1440" alt="screen shot 2018-01-03 at 9 33 54 am" src="https://user-images.githubusercontent.com/6651506/34513617-69239b4e-f069-11e7-8c34-8b58ab906172.png">

**Comment by MarshallOfSound** [comment]
Sounds like you are trying to do this from the `file://` protocol which won't work very well.  If that isn't the case please provide a minimal reproduction example demonstrating code that works in Chrome but not in Electron

**Comment by MarshallOfSound** [comment]
Woops

**Comment by JensDebergh** [comment]
I’m not loading anything from ‘file://‘ prefix. What actually happens is that within an electron browser a user gets redirected to trello authorisation page which in turn tries to load jQuery from trello.com (which fails).

I think it might have something to do with node integration in electron.

**Comment by MarshallOfSound** [comment]
Oh, you're loading remote content with `nodeIntegration` enabled.  That's a bad plan as it's both a security risk and it breaks all UMD loaders (such as jQuery's).  You should disable `nodeIntegration` for any `webContents` loading remote content.

**Comment by MarshallOfSound** [comment]
See https://github.com/electron/electron/blob/master/docs/tutorial/security.md for more information

**Comment by JensDebergh** [comment]
Thanks @MarshallOfSound I was heading in the right direction, but was closing in on a blocker.

If I disable node integration, is there a way to communicate the received `token` from trello which resides in the `content` of the browser back to the main process without node integration?

**Comment by JensDebergh** [comment]
Thanks @MarshallOfSound I was heading in the right direction, but was closing in on a blocker.

If I disable node integration, is there a way to communicate the received `token` from trello which resides in the `content` of the browser back to the main process without node integration?
