### ISSUE TITLE
"... and 1 more" process taking forever to finish.

### ISSUE THREAD

**Issue by bidipeppercrap** [electron/electron#11559]
Waited for an hour, doesn't end a result.
I have no idea why, my connection is stable and also fast (10mbps).
![screenshot from 2018-01-03 17-18-19](https://user-images.githubusercontent.com/30064028/34516683-6af3523e-f0aa-11e7-8eb2-1dee1599a40e.png)

**Comment by MarshallOfSound** [comment]
Run your mom install with `--verbose`
  It should give you a progress bar and more idea as to what's going wrong where in your download process

**Comment by bidipeppercrap** [comment]
@MarshallOfSound lol it's already `--verbose`

**Comment by MarshallOfSound** [comment]
Are you behind a proxy or VPN?  If it's running in verbose mode you should get at least some kind of log from the downloader 🤔 

As a follow up does it hang when you run the same command from terminal as well?
