### ISSUE TITLE
Input is not clickable?

### ISSUE THREAD

**Issue by piavgh** [electron/electron#11553]
* Electron version: 1.7.10
* Operating system: Windows 10 64 bits

### Expected behavior

The input field should be clickable when I click left mouse on it
### Actual behavior

The input field is not clickable. In order to switch to next input, I need to use Tab button
### How to reproduce
This is my HTML file

```
<div class="smtp-settings-container">
  <div class="form-group">
    <label for="smtp-address-sender" data-i18n>{{senderAddress}}</label>
    <input type="email" class="form-control dialog-message" id="smtp-address-sender">
  </div>
  <div class="form-group">
      <label for="smtp-address-receiver" data-i18n>{{receiverAddress}}</label>
      <input type="email" class="form-control dialog-message" id="smtp-address-receiver">
    </div>
</div>
```

Nothing special, but I can not click my mouse on the input field

**Comment by MarshallOfSound** [comment]
This sounds like an issue caused by your own CSS not something Electron would case, please provide a minimal repro based on `electron-quick-start` that demonstrates this issue.

**Comment by piavgh** [comment]
This is a project of our client, it's quite big so I can't post the repo and also it's hard to know which css causes this issue.

But I use this workaround to fix this issue:

```
$('#smtp-settings-email').on('click', function () {
                $('#smtp-settings-email').focus();
            });
            $('#smtp-settings-password').on('click', function () {
                $('#smtp-settings-password').focus();
            });
```
