### ISSUE TITLE
Generated checksum for "electron-v1.4.12-darwin-x64.zip" did not match expected checksum

### ISSUE THREAD

**Issue by StefMa** [electron/electron#11552]
* Electron version: 1.4.12
* Operating system: macOS High Sierra

### Expected behavior

electron can be downloaded/installed an run

### Actual behavior

I got just the message:
```
Error: Generated checksum for "electron-v1.4.12-darwin-x64.zip" did not match expected checksum.
    at ChecksumMismatchError.ErrorWithFilename (/Users/stefan/Desktop/Geist/node_modules/sumchecker/build.js:41:124)
    at new ChecksumMismatchError (/Users/stefan/Desktop/Geist/node_modules/sumchecker/build.js:56:133)
    at Hash.<anonymous> (/Users/stefan/Desktop/Geist/node_modules/sumchecker/build.js:203:22)
    at Hash.emit (events.js:159:13)
    at emitReadable_ (_stream_readable.js:516:10)
    at emitReadable (_stream_readable.js:510:7)
    at addChunk (_stream_readable.js:276:7)
```

### How to reproduce
I want to build this project here: https://github.com/stefma/geist
(In a nutshell: Just checkout and run `yarn install`) 
But if I run `yarn install` I got the message from above.
I've already seen https://github.com/electron-userland/electron-prebuilt/issues/264 & https://github.com/electron-userland/electron-prebuilt/pull/275.
I've also understood "why it happend".
But I'm unable to fix that :D

I've tried to update `electon` to 1.7.10 and electron-builder to 19.50.0 but without success.
I've even tried to different versions of electron and the builder... Even without success :(

How can I build that project without an issue? 🤔 
Additional: Why will such a change break older versions? I don't get it.

**Comment by sofianguy** [comment]
@StefMa Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by fspinnenhirn** [comment]
@StefMa What node version are you using?  
As mentioned in electron-userland/electron-prebuilt#264, downgrading to a v6 of node before installing avoids the checksum error.

**Comment by eveningkid** [comment]
@StefMa Ran into the exact same issue. Downgrading to Node v6 worked for me!

**Comment by arausly** [comment]
In my case, I basically just ran the entire command again a couple times after, with the --verbose command along `npm install electron --save-dev --verbose` not saying the verbose command had anything to do about it.
