### ISSUE TITLE
How to start a node server for "selenium-webdriver"

### ISSUE THREAD

**Issue by RoarRain** [electron/electron#11567]
"electron": "1.7.10",
Mac OS 10.12.6

I want build a "electron-chromedriver" to electron pack, but "selenium-webdriver" need start a node server , https://electronjs.org/docs/tutorial/using-selenium-and-webdriver,
I use 

```
let startChromeDriver = spawn(''./node_modules/.bin/chromedriver");
```
it is work when test, but build not work, how do i do?
help me ,thx!

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
