### ISSUE TITLE
Add `browserWindow.loadFile()` convenience method

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#11560]
* Electron version: 1.7.10
* Operating system: macOS 10.13.2

### Description

The most common use-case for Electron is to load a local HTML file. The default way to do this is pretty verbose and ugly ```win.loadURL(`file://${__dirname}/index.html`)```.

I propose adding a convenience method to make the most common use-case simpler and nicer. A `win.loadFile()` method which loads a file relative to the root of the app:

```js
win.loadFile('index.html');
```

Which would be almost equivalent to:

```js
const loadFile = filePath => win.loadURL(`file://${path.resolve(electron.app.getAppPath(), filePath)}`);
```

We should also add `file` option to the `BrowserWindow` constructor, so all you needed to do to create a window with a local file (which is what most would do) is just:

```js
const win = new BrowserWindow({file: 'index.html'});
```

Ergonomics are important, and this is something that would benefit most Electron apps.

I would be happy to do a PR if this is accepted.

I've added support for it in my Electron utility module if you want it today: https://github.com/sindresorhus/electron-util#loadfilewindow-filepath

**Comment by MarshallOfSound** [comment]
I'd be down for this, not necessarily because it will save people a whole lot of time or coding effort but because it will result in fewer apps making the same string concatenation mistake.

```js
`file://${myPath}`
```

^^ This actually doesn't work on some machines, more detailed explanation [here](https://github.com/sindresorhus/electron-util/pull/2)

**Comment by WORMSS** [comment]
I presume 
```javascript
const win = new BrowserWindow({file: 'index.html'});
```
was not added to the spec?

**Comment by tomasdev** [comment]
is there a way to have files have an extension other than `.html` ? I've tried with `.hbs` and it just wraps the content in a `<pre>` tag
