### ISSUE TITLE
Several electron by passing time in $HOME directory 

### ISSUE THREAD

**Issue by AM-SL** [electron/electron#11562]
### Info

* Electron version: Several
* Operating system: Arch Linux Updated Fully and Clean
* SSD : 512GB
* Capacity Remain : 10GB
* Electron Using : 3GB

### Expected behavior

As I know It must be just one electron package in HOME directory `.electron` folder

### Actual behavior

Actual there is several electron packages in electron folder and all of them is bigger that 50 MB 
so after some time home folder is full specially when you have small SSD that hasn't enough capacity
because of several applications and node js modules

**Note** : electrons are there with their sha code 

Question : Can we delete them and left only the latest version package ?
Question 2 : Why downloading several and packages ?
Question 3 : When downloading these packages ? :)

### Picture
From another Laptop
Like mine

![screenshot from 2018-01-03 18-40-33](https://user-images.githubusercontent.com/27131057/34525931-e88bd986-f0b5-11e7-8284-8b97694964c6.png)

### Path

```sh
$ which electron
/bin/usr/electon
```

And no PATH prefix set for any situation

**Comment by MarshallOfSound** [comment]
This is expected behavior, for every version of electron you install from npm we download and cache the binary, that's what you see in that folder
