### ISSUE TITLE
Add API to get the path to the root of the app

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#11561]
* Electron version: 1.7.10
* Operating system: macOS 10.13.2

### Description

There's currently no way to get the actual root of the app, meaning the directory which contains the package.json.

We have `__dirname`, so we could pass that around from `index.js`, but that's not a good developer experience.

It's easy to be fooled to think that `process.cwd()` would work, but it can return the wrong directory in development depending on where you launched the app from. If you run `electron app` it will be `/Users/sindresorhus/dev/project`, while `cd app && electron .` will return `/Users/sindresorhus/dev/project/app`.

There should be an API that always returns the `/Users/sindresorhus/dev/project/app` directory.

I'm thinking the API be a getter property called `app.root`, but I'm open to suggestions.

You already read the root package.json for the `app.getName()` API, so the information is already there, just needs to be exposed.

I would be happy to do a PR if this is accepted.
  
I've added support for it in my Electron utility module if you want it today: https://github.com/sindresorhus/electron-util#approot

**Comment by singhshashi** [comment]
Wouldn't app.getAppPath() work?

**Comment by sindresorhus** [comment]
Ugh, I've been using Electron for years, but apparently, I've managed to miss this API... Closing. Sorry for the noise.

**Comment by ganeshrvel** [comment]
Finding the root path of an electron app could get tricky. Because the root path is different for the main process and renderer under different conditions such as production, development and packaged conditions.

I have written a npm package [electron-root-path][1] to capture the root path of an electron app.

    $ npm install electron-root-path
    
    or 
    
    $ yarn add electron-root-path


    // Import ES6 way
    import { rootPath } from 'electron-root-path';
    
    // Import ES2015 way
    const rootPath = require('electron-root-path').rootPath;
    
    // e.g:
    // read a file in the root
    const location = path.join(rootPath, 'package.json');
    const pkgInfo = fs.readFileSync(location, { encoding: 'utf8' });


[1]: https://github.com/ganeshrvel/npm-electron-root-path/

**Comment by stoefln** [comment]
@ganeshrvel your lib doesn't work for me. It always returns "/"

**Comment by tireinaldo** [comment]
try process.env.PORTABLE_EXECUTABLE_DIR

**Comment by marckraw** [comment]
> @ganeshrvel your lib doesn't work for me. It always returns "/"

dunno if u still have this problem, probably not, but for other people which will ever come to this topic like me..
solved it with importing it like that, with `window` (this is used in renderer so in my situtation, in react components
```
const rootPath = window.require("electron-root-path").rootPath;
```
