### ISSUE TITLE
1.8.2-beta.3 failure when a region vertically overflows

### ISSUE THREAD

**Issue by starpit** [electron/electron#11569]
* Electron version:1.8.2-beta.3
* Operating system:darwin

### Expected behavior

electron should not crash when a region overflows vertically

### Actual behavior

crash with

[87115:0104/143435.970871:FATAL:partition_alloc.cc(934)] Check failed: page->num_allocated_slots != -1. 
0   Electron Framework                  0x000000010c9f821c crashpad::CloseMultipleNowOrOnExec(int, int) + 970204
1   Electron Framework                  0x000000010c9bfa33 crashpad::CloseMultipleNowOrOnExec(int, int) + 738803
2   Electron Framework                  0x000000010c9d7491 crashpad::CloseMultipleNowOrOnExec(int, int) + 835665
3   Electron Framework                  0x000000010f674b9c crashpad::CloseMultipleNowOrOnExec(int, int) + 47617884
4   libnode.dylib                       0x00000001110b442e v8::internal::DeferredHandles::Iterate(v8::internal::ObjectVisitor*) + 20670
5   libnode.dylib                       0x00000001110b436e v8::internal::DeferredHandles::Iterate(v8::internal::ObjectVisitor*) + 20478
6   libnode.dylib                       0x000000011153f67a v8::internal::AllocationSpaceName(v8::internal::AllocationSpace) + 27370
7   libnode.dylib                       0x0000000111538570 v8::internal::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, v8::internal::MachineType) + 76800
8   libnode.dylib                       0x00000001115388e4 v8::internal::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, v8::internal::MachineType) + 77684
9   libnode.dylib                       0x0000000111548187 v8::internal::AllocationSpaceName(v8::internal::AllocationSpace) + 62967
10  Electron Framework                  0x000000010ca378c2 crashpad::CloseMultipleNowOrOnExec(int, int) + 1229954
11  Electron Framework                  0x000000010c9dee37 crashpad::CloseMultipleNowOrOnExec(int, int) + 866807
12  libsystem_pthread.dylib             0x00007fff5af616c1 _pthread_body + 340
13  libsystem_pthread.dylib             0x00007fff5af6156d _pthread_body + 0
14  libsystem_pthread.dylib             0x00007fff5af60c5d thread_start + 13

close variant:
[87069:0104/143010.593801:FATAL:partition_alloc.cc(934)] Check failed: page->num_allocated_slots != -1. 
0   Electron Framework                  0x000000010721121c crashpad::CloseMultipleNowOrOnExec(int, int) + 970204
1   Electron Framework                  0x00000001071d8a33 crashpad::CloseMultipleNowOrOnExec(int, int) + 738803
2   Electron Framework                  0x00000001071f0491 crashpad::CloseMultipleNowOrOnExec(int, int) + 835665
3   Electron Framework                  0x0000000109e8db9c crashpad::CloseMultipleNowOrOnExec(int, int) + 47617884
4   libnode.dylib                       0x000000010b8d242e v8::internal::DeferredHandles::Iterate(v8::internal::ObjectVisitor*) + 20670
5   libnode.dylib                       0x000000010b8d236e v8::internal::DeferredHandles::Iterate(v8::internal::ObjectVisitor*) + 20478
6   libnode.dylib                       0x000000010bd5d67a v8::internal::AllocationSpaceName(v8::internal::AllocationSpace) + 27370
7   libnode.dylib                       0x000000010bd56570 v8::internal::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, v8::internal::MachineType) + 76800
8   libnode.dylib                       0x000000010bd56795 v8::internal::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, v8::internal::MachineType) + 77349
9   libnode.dylib                       0x000000010bfd3d7d v8::internal::PagedSpace::SlowAllocateRaw(int) + 173
10  libnode.dylib                       0x000000010bb13304 v8::internal::Factory::SetClassFunctionInstanceDescriptor(v8::internal::Handle<v8::internal::Map>) + 1172
11  libnode.dylib                       0x000000010bd61b5d v8::internal::AllocationSpaceName(v8::internal::AllocationSpace) + 45005
12  libnode.dylib                       0x000000010bd6148a v8::internal::AllocationSpaceName(v8::internal::AllocationSpace) + 43258
13  libnode.dylib                       0x000000010bd5c4ab v8::internal::AllocationSpaceName(v8::internal::AllocationSpace) + 22811
14  libnode.dylib                       0x000000010bd5c16c v8::internal::AllocationSpaceName(v8::internal::AllocationSpace) + 21980
15  libnode.dylib                       0x000000010bd6a2d0 v8::internal::AllocationSpaceName(v8::internal::AllocationSpace) + 79680
16  Electron Framework                  0x00000001072508c2 crashpad::CloseMultipleNowOrOnExec(int, int) + 1229954
17  Electron Framework                  0x00000001071f7e37 crashpad::CloseMultipleNowOrOnExec(int, int) + 866807
18  libsystem_pthread.dylib             0x00007fff5af616c1 _pthread_body + 340
19  libsystem_pthread.dylib             0x00007fff5af6156d _pthread_body + 0
20  libsystem_pthread.dylib             0x00007fff5af60c5d thread_start + 13

### How to reproduce

these steps require use of openwhisk

```
git clone git@github.com:ibm-functions/shell.git
cd shell/app
<update package.json to point to electron 1.8.2-beta.3>
npm install
./bin/fsh shell
execute commands that eventually cause the region to vertically overflow
```

**Comment by MarshallOfSound** [comment]
This crash has been fixed recently

Duplicate: https://github.com/electron/electron/issues/11457
