### ISSUE TITLE
Is 'wasOpenedAtLogin' on Windows Possible?

### ISSUE THREAD

**Issue by jellybabies10** [electron/electron#11575]
Hello,

I have an app that I only want to be used on startup/login. So I would like to know if the app was opened at login or not to determine whether to run or not. I have used 'wasOpenedAtLogin' for the Mac version, but the docs says this feature is not supported for Windows. Is it possible to add this feature for Windows?

**Comment by codebytere** [comment]
Hey! thanks for your feature request, but this is something that should be done in [Electron Userland](https://github.com/electron-userland) or on the user side. As a jumping off point, you could add a `--was-launched-at-login` or something similar arg to the login launch registration and then later check for the presence of that argument. Good luck!
