### ISSUE TITLE
app.getLocale() does not return the language set in Window 10 Settings

### ISSUE THREAD

**Issue by somasundarambk** [electron/electron#11579]
* Electron version: 1.7.3
* Operating system: Windows 10 

### Expected behavior
app.getLocale() should return the language set in Windows 10 Settings

### Actual behavior
app.getLocale() returns "en-US" in Windows 10 irrespective of the language set in the settings

### How to reproduce
In Windows 10, go to "Settings"-> "Time & Language" -> "Region & Language" -> Choose a non English language and select "Set as Default" (from English (United States)
app.getLocale() always returns "en-US" even after restarting the application.
![git1](https://user-images.githubusercontent.com/14005930/34622586-81fd3234-f202-11e7-82c1-9c3bb15f81e5.PNG)

**Comment by SecretObsession** [comment]
@somasundarambk I just ran into this bug, (on 1.8.1) and was able to fix it by only using app.getLocale() after/when the app.on('ready') event has fired. 

https://github.com/electron/electron/blob/master/docs/api/app.md#event-ready

**Comment by codebytere** [comment]
@SecretObsession is correct, it needs to be called after the app is ready.
