### ISSUE TITLE
Tray icon not shown

### ISSUE THREAD

**Issue by ihachani** [electron/electron#11572]
* Electron version: 1.7.9
* Operating system: OSX

### Expected behavior

After invoking tray.setHighlight to always. Icon should be shown

### Actual behavior
I am creating a Tray inside a promise and setting the highlight to true in  then() but the tray is not shown.

### How to reproduce

```
Promise.resolve(new Tray(iconPath)).then( (tray) => {
  tray.setHighlightMode('always');
});

```

**Comment by sethlu** [comment]
Hi @ihachani One reason that the tray icon is not showing up is that the icon is slightly oversized so the display for that status bar item is dropped by macOS. Mind checking the dimensions for the image specified with `iconPath`?

And here's more information to [`NativeImage`](https://github.com/electron/electron/blob/1-7-x/docs/api/native-image.md). You can provide various dimensions for the same icon by suffixing the file base name with e.g. `icon@2x.png` for retina display. As a base dimension for `icon.png`, perhaps try 22x22?

**Comment by ihachani** [comment]
@sethlu The tray icon works normally if I declare the Tray then set the highlight mode.
This works:
```
let tray =  new Tray(iconPath);
tray.setHighlightMode('always');
```
Using promises doesn't. I want to use the Tray in functional pipeline.

**Comment by MarshallOfSound** [comment]
@ihachani This is because in the promise chain you lose all references to your tray icon and it is therefore garbage collected.  You need to maintain a reference for it not to be GC'ed

**Comment by YikaJ** [comment]
I try to export a function to init Tray, and the instance also been garbage collected.
```js
// wrong way
export default function initTray() {
  const tray = new Tray(iconPath)
  tray.setContextMenu(contextMenu)
}

// rightWay
let tray = null
export default function initTray() {
  tray = new Tray(iconPath)
  tray.setContextMenu(contextMenu)
}
```
