### ISSUE TITLE
Feature request (if possible), add the --disable-webrtc-encryption flag as used in Chrome Canary

### ISSUE THREAD

**Issue by swinster** [electron/electron#11578]
Not even sure this is possible if everything is based on the released Chromium, but this flag is very useful when debugging WebRTC calls and quality issues, so could be further exposed in pre-release software based on Electron.

**Comment by codebytere** [comment]
Sadly this is part of a blacklist on chrome switches we have [here](https://github.com/electron/electron/blame/b5d5eca224b7a76dacb5219ad247a6bfc4ab50cf/atom/app/command_line_args.cc) that we implemented to disallow launching unknown apps via browser client.
