### ISSUE TITLE
[Mac OSX] Can't change the label for "Enter Full Screen" menu item

### ISSUE THREAD

**Issue by CptMaumau** [electron/electron#11571]
* Electron version: 1.7.10
* Operating system: Mac OSX High Sierra

### Expected behavior

Label for "Enter Full Screen" changes

### Actual behavior

Label for "Enter Full Screen" is not changing

### How to reproduce

Here is my "View" menu
```
{
    label: i18n.__('MENU.VIEW.TITLE'),
    submenu: [
      { label: i18n.__('MENU.VIEW.RELOAD'), role: "reload" },
      { type: "separator" },
      { label: i18n.__('MENU.VIEW.FULL_SCREEN'), role: "togglefullscreen" },
      { label: i18n.__('MENU.VIEW.ZOOM_IN'), role: "zoomin" },
      { label: i18n.__('MENU.VIEW.ZOOM_OUT'), role: "zoomout" },        
  ]
},
```
All other menu item change according to the language file.
<img width="202" alt="screen shot 2018-01-05 at 11 01 10 am" src="https://user-images.githubusercontent.com/5366008/34592562-64ddaaa2-f208-11e7-954a-735f35f28de9.png">

**Comment by sethlu** [comment]
@nitsakh can we close this issue?
