### ISSUE TITLE
Widevine Binary not in documented location

### ISSUE THREAD

**Issue by hughrawlinson** [electron/electron#11577]
* Electron version: electron@1.7.9
* Operating system: High Sierra 10.13.2
* Chrome Version: 63.0.3239.84
* Widevine CDM Version:  1.4.8.1030

### Expected behavior

The [Using Widevine CDM Plugin](https://github.com/electron/electron/blob/master/docs/tutorial/using-widevine-cdm-plugin.md) tutorial says that a widevine binary ships with Chrome, and should be available at `~/Library/Application\ Support/Google/Chrome/WidevineCDM`.

### Actual behavior

The Widevine CDM library isn't available in that location. The folder exists but is empty. I have confirmed in `chrome://components` that WidevineCDM is installed and up to date.

### How to reproduce

Follow the *Using Widevine CDM Plugin* tutorial, or `ls -lah ~/Library/Application\ Support/Google/Chrome/WidevineCDM`.

**Comment by MarshallOfSound** [comment]
If you can't find it at that location you should be able to track down the originals using `find`

```bash
cd /Applications
find . -name *widevine*
```

That should find any widevine related things and dump them out to your terminal.  I found the adapter for instance here:

`/Applications/Google Chrome.app/Contents/Versions/63.0.3239.132/Google Chrome Framework.framework/Versions/A/Libraries/WidevineCdm/_platform_specific/mac_x64/widevinecdmadapter.plugin`

**Comment by gthomas2** [comment]
@MarshallOfSound - Thanks, you helped me out here.
However, I had to wrap the search term in double quotes to make it work.

find . -name "*widevine*"

**Comment by alexanderturinske** [comment]
This is kind of unnecessary now, but I wanted to put it somewhere for potential future uses. We have had to download a lot of widevine files in the past and created this useful step-by-step on how to get older versions of chrome to get the widevine dll files. I cannot find a useful place to put this now that VMP is here, but this seems like the best place.

**Fetching widevine files for specific Electron version**
 
1) Check version chrome used in electron version you want (i.e. 2.0.0): https://electronjs.org/releases
2) Also read archived electron widevine tutorials for different electron versions: https://electronjs.org/docs/tutorial/using-widevine-cdm-plugin/history 
3) Download old chrome version: https://www.slimjet.com/chrome/google-chrome-old-version.php 
4) In chrome, verify version is version wanted
5) Check widevine cdm version: chrome://components
6) In mac
`cd ~/Applications/Google Chrome 3.app/Contents/Versions/53.0.2785.116/Google Chrome Framework.framework/Versions/A/Libraries/WidevineCdm/_platform_specific/mac_x64`
`cd ~/Applications/Google Chrome 2.app/Contents/Versions/61.0.3163.79/Google Chrome Framework.framework/Versions/A/Libraries/WidevineCdm/_platform_specific/mac_x64`

Note: If can’t find plugin info through filepath -- try doing a global search of  files ending in .plugin and outputting results in a text file `locatedPlugins.txt`
`find / -type f -name '*.plugin' > locatedPlugins.txt`
`find . -name "widevine"`

7) Grab the necessary files: `ls -a ./`
for `libwidevinecdm.dylib`, `widevinecdmadapter.plugin`
for `libwidevinecdm.dylib.sig`, `widevinecdmadapter.plugin.sig`

**Comment by steverandy** [comment]
@alexanderturinske in the recent version of chrome (v71.0.3578.98), there is no `widevinecdmadapter.plugin` file anymore. Do you know why is that the case and where to look for this file? I can't enable widevine plugin on Electron v4 also anymore.

**Comment by alexanderturinske** [comment]
I have a lot of versions of chrome on my computer and I see that `widevinecdmadapter.plugin` has not been included since `v65`. I did update the [Electron Widevine Docs](widevinecdmadapter.plugin) saying that there are some new security features that may prevent Electron from playing some media. 

[Electron-Releases](https://github.com/castlabs/electron-releases) has been created to address this and you should check if using their repo locally fixes your issue. If it does, then the new security feature is preventing your media from playing and you should start the steps to get the necessary file/s from Google (or stay on an older version of Electron)
