### ISSUE TITLE
1.8.2-beta.3 EINVAL: invalid argument, fstat when accessing a file from OneDrive

### ISSUE THREAD

**Issue by JohnWeisz** [electron/electron#11570]
* Electron version: 1.8.2-beta.3
* Operating system: Windows 10

### Expected behavior

This error should not be thrown.

### Actual behavior

The error was thrown.

### How to reproduce

 1. Have OneDrive with "on-demand files" feature enabled
 2. `FS.readFile` a file from the local OneDrive folder

I believe this has been fixed earlier by https://github.com/electron/electron/pull/10377, but is now back. https://github.com/Microsoft/vscode/issues/27285 is related.

**Comment by JohnWeisz** [comment]
For clarification, the error is about `fstat`, with F, not `lstat`. That was a typo.

**Comment by MarshallOfSound** [comment]
Refs: https://github.com/nodejs/node/issues/12737

This was fixed in node 9.3.0 which we will be upgrading to in one of the upcoming releases of Electron (off the top of my head I think it's included in the next chromium upgrade which we are about to release a beta of)

**Comment by JohnWeisz** [comment]
Is there an ETA on the release containing the fix to this issue?
