### ISSUE TITLE
WHITE FLASH

### ISSUE THREAD

**Issue by harishpilla** [electron/electron#11581]
whenever i select an anchor tag a white screen appears and be like that for 4 seconds.....can please someone help.....i need an answer

* Electron version:
* Operating system:

**Comment by MarshallOfSound** [comment]
That's your next page loading

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by harishpilla** [comment]
what if i use angular routing to load pages in lectron.will it make my electron app load pages faster
