### ISSUE TITLE
Cannot install from NPM

### ISSUE THREAD

**Issue by AntonPilyak** [electron/electron#11586]
* Electron version: 1.7.10
* Operating system: Win10 x64

### Expected behavior

npm install electron --save-dev should work

### Actual behavior

npm install electron --save-dev gives the following error:
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for pinkie-promise

### How to reproduce
npm install electron --save-dev

**Comment by AntonPilyak** [comment]
No longer reproducible.

**Comment by MarshallOfSound** [comment]
Npm is experiencing issues currently, I would recommend waiting a few hours before installing any npm modules just to let things settle
