### ISSUE TITLE
Picture in Picture Support macOS

### ISSUE THREAD

**Issue by fishcharlie** [electron/electron#11582]
Electron should add support for video Picture in Picture Support on macOS.

**Comment by MarshallOfSound** [comment]
This Picture-in-Picture API on macOS is private and undocumented.  It's not something we can support at this time

**Comment by tobiasbueschel** [comment]
Since Chrome version 70, Picture-in-Picture is [officially supported on macOS](https://www.zdnet.com/article/google-chrome-picture-in-picture-support-is-now-live-for-desktop-users/) 🎉
