### ISSUE TITLE
Segfault calling Browser window with options Proxy.

### ISSUE THREAD

**Issue by daurnimator** [electron/electron#11593]
* Electron version: 1.6.15
* Operating system: Linux

### Expected behavior

Open a `BrowserWindow` with passed options

### Actual behavior

  - Usually a Segmentation fault.
  - Sometimes `[12843:0100/000000.043847:FATAL:zygote_linux.cc(479)] Failed to synchronise with parent zygote process`
  - Sometimes `[12819:0100/000000.719122:FATAL:zygote_linux.cc(509)] Check failed: len > 0 (0 vs. 0)`

### How to reproduce

I'm still working on making a smaller reproduction case. The issue goes away with small tweaks.

1. Starting from https://github.com/daurnimator/fengari-electron-example
2. Modify main.lua to contain:
```lua
local js = require "js"
local electron = require "electron"

electron.app:on("ready", function()
	local win = js.new(electron.BrowserWindow, js.createproxy({
		backgroundColor = '#2e2c29';
	}, "object"))
	win:loadURL("https://fengari.io")
end)
```

**Comment by MarshallOfSound** [comment]
There is no error when this is done in pure JS, this will be an issue with whatever lua / fengari thing you are using here 👍 

If you can provide a reproduction case in raw JS we'll be happy to reopen this

**Comment by daurnimator** [comment]
lua/fengari *is* just plain JS, so the segfault can still happen somehow with plain JS (I just haven't narrowed it down to a small+reliable reproducer without fengari yet)

**Comment by daurnimator** [comment]
Managed to narrow it down to this JS sample:

```js
const {app, BrowserWindow} = require("electron");

const proxy_handlers = {
	"get": function(target, k) {
		return void 0;
	},
	"has": function(target, k) {
		if (k == "webContents")
			return true;
	}
};

app.on("ready", function() {
	let win = Reflect.construct(BrowserWindow, [new Proxy({}, proxy_handlers)])
})
```

**Comment by MarshallOfSound** [comment]
What is `Reflect`?

**Comment by daurnimator** [comment]
> What is Reflect?

The JavaScript builtin that is meant to be equivalent to the `new` operator: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/construct

**Comment by MarshallOfSound** [comment]
This issue appears to be specific to `void 0` and `has` always returning `true`.  Investigating

**Comment by daurnimator** [comment]
@MarshallOfSound @codebytere thanks for fixing!
