### ISSUE TITLE
`skipTaskbar: true` not working while app stop running for a little bit.

### ISSUE THREAD

**Issue by huanhulan** [electron/electron#11591]
* Electron version:1.7.10
* Operating system:win 10 x64, win7 x64

### Expected behavior

taskbar icon does not appear during the app's life cycle.

### Actual behavior

taskbar icon will appear after the app stop responding and shows the thumbnails of webContent:
![image](https://user-images.githubusercontent.com/9404826/34661796-032910ea-f487-11e7-9b21-e1a90b2e5ddb.png)

### How to reproduce
can't always reproduce on our nomal codes, it would appear rarely on low performance virtual machines reproted by our QAs. But after adding codes below to the `ready` listener of the main process, this issue will surely reoccur and the taskbar icon will stay forever until closing the app:
```javascript
app.on('ready', () => {
  // skip the codes for initialization...

  setTimeout(() => {
    let time1 = new Date();
    var time2 = new Date();
    while (time2 - time1 <= 10000) { time2 = new Date(); }
  }, 20000);
});
```

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
