### ISSUE TITLE
Feature request: Ability to change close label in notifications (Mac)

### ISSUE THREAD

**Issue by clusterberries** [electron/electron#11594]
* Electron version: 1.7.10
* Operating system: MacOS

### How to reproduce

Currently I am using a separate module for Mac notifications with action buttons (node-notifier). Action buttons are necessary for such scenarios: when user has incoming call, notification has two buttons: 'answer' and 'decline'. 
Recently I found out that Electron has its own implementation of notifications and allows to add action buttons. That's great feature, but the issue I found is that I can't add two actions. I see two possible solutions: add ability to change 'close' label or add ability to display several actions (e.g. under 'More' button, as it is implemented in Chrome).

Is there any plans to implement it? Thank you!

**Comment by MarshallOfSound** [comment]
> add ability to change 'close' label

This is the best option here, quite easy to implement as well 👍
