### ISSUE TITLE
How can clear localStorage when app is deleted on MAC OS

### ISSUE THREAD

**Issue by joinjoohny** [electron/electron#11592]
Hi guys
I needed clear local storage when app is deleted on mac os 
or how you can get the unique id when the application is installed, unique for each installed version.

Thx thx

**Comment by MarshallOfSound** [comment]
> I needed clear local storage when app is deleted on mac os

You can't do this, there is no way for a normal app to know when it is deleted / removed from a computer on macOS

> how you can get the unique id when the application is installed, unique for each installed version.

This is also not a thing afaik, you don't technically "install" an app on macOS, you just kinda run it.  There is no "install ID" or anything like that

**Comment by joinjoohny** [comment]
Tnank you!

**Comment by kimyLee** [comment]
@MarshallOfSound

**Comment by kimyLee** [comment]
@MarshallOfSound 
then what should I do in such a issue:  The user will get a message pop-up when open app, then if user choose 'not show again', message will never show then, I use localstorage to mark the 'not show again' status.  however, when I uninstall app and install again, the status should be reset while now it doesn't. Are there some methods I can clear the storage while restall ?
