### ISSUE TITLE
Intermittent BrowserWindow.webContents.savePage No Callback Issue

### ISSUE THREAD

**Issue by jimmaay** [electron/electron#11590]
* Electron Version: 1.7.10
* Operating System: Windows 10 Pro x64

### Expected behavior

Calling BrowserWindow.webContents.savePage on all URLs should send a callback with or without error. 

### Actual behavior

For certain URL's no callback happens sometimes. Although I am able to force it to callback by calling savePage again after a delay.

### How to reproduce

Run the below code with "electron FILE.JS" until saving does not work. It may take a couple tries for it to happen. It will hang at "Saving.." and never callback. 

```const electron = require('electron'),fs=require('fs'),path=require('path');
const app = electron.app,BrowserWindow = electron.BrowserWindow
let mainWindow
function createWindow(){
	mainWindow=new BrowserWindow({
		width:800,
		height:600,
		webPreferences:{partition:'none',nodeIntegration:false,contextIsolation:true}
	});
	mainWindow.loadURL('https://www.epicgames.com/fortnite/en-US/buy-now/battle-royale')

	mainWindow.webContents.on('did-finish-load',() =>{
		if(!fs.existsSync('temp')){fs.mkdirSync('temp');}
		console.log('Saving..');
		mainWindow.webContents.savePage('temp/index.html','HTMLComplete',function(){console.log('Saved');});

		// Uncomment the below to force it to work
		//setTimeout(function(){mainWindow.webContents.savePage('temp/index.html','HTMLComplete',function(){console.log('Saved2');});},10000)
	})

	mainWindow.on('closed',function(){mainWindow=null})
}
app.on('ready',createWindow)
app.on('window-all-closed',function(){if(process.platform!=='darwin'){app.quit()}})```

**Comment by jimmaay** [comment]
The second call to savePage forces the first savePage to reject and return an empty object as error when the first savepage is still processing and then doesn't callback anymore as well.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
