### ISSUE TITLE
require is not available in "Electron Isolated Context" in devtools when {contextIsolation: true, nodeIntegration: false}

### ISSUE THREAD

**Issue by bughit** [electron/electron#11608]
* Electron version: master
* Operating system: win7 x64

### Expected behavior

require to be available

### Actual behavior

require is not available: "require is not defined"

### How to reproduce

create a BrowserWindow with dev tools as follows:

```js
new BrowserWindow({
    width: 1366,
    height: 768,
    closable: true,
    devtools: true,
    show: true,
    frame: true,
    useContentSize: true,
    webPreferences: {
      nodeIntegration: false,
      webviewTag: false,
      sandbox: false,
      allowRunningInsecureContent: true,
      offscreen: false,
      webSecurity: true,
      contextIsolation: true,
      preload: path.join(__dirname, 'preload.js'),
    },
  });
```
in the devtools console, switch context to "Electron Isolated Context" and try `require('electron')`

**Comment by codebytere** [comment]
When you disable nodeIntegration you lose access to `require` as it is part of Node. If your Electron application has `nodeIntegration` set to `false` then you'll need to expose a `require` window global to your app so it can access the core Electron APIs.

**Comment by bughit** [comment]
@codebytere If you have an objection to reopening please explain why.  As I mentioned, require is available to the preload script when {contextIsolation: true, nodeIntegration: false} and AFAICT that's deliberate.

**Comment by codebytere** [comment]
a misunderstanding on my end, reopening :)

**Comment by bughit** [comment]
@deepak1556 

I am off electron work for now, when I get back to it, soon, I'll see if this is still an issue in master,  In the mean time can you please let me know the status of #11607 ?

**Comment by bughit** [comment]
@deepak1556 
I am running debug electron built from recent master (7e2f7602c1d3f383bb859f4af96e74e683a49d8e) on win7 sp1 x64
run `electron.exe electron_test.js`  from [electron_test.zip](https://github.com/electron/electron/files/1745321/electron_test.zip)

the preload script logs that require is available, but in the dev console in the electron isolated context it's not
![image](https://user-images.githubusercontent.com/895588/36499454-48be8612-170f-11e8-803a-96829509e7d9.png)

**Comment by brenca** [comment]
I'm not sure if this is a bug, or the intended behavior, 'tho it's a bit confusing. The thing is, according to the docs, `contextIsolation` decides the following:
> Whether to run Electron APIs and the specified preload script in a separate JavaScript context. 

This means that the preload script _and_ the Electron APIs run in the isolated context, which in turn means that when you enable `nodeIntegration`, that only turns the integration on for that isolated context. If you think it through it makes sense, since the preload script gets access to the APIs with `nodeIntegration` disabled even without the context isolation.

I tested your example @bughit, and if you enable `nodeIntegration`, it does what I mentioned before.

Since this is a logical but a bit confusing behavior, we could update the docs to mention this I guess. /cc @codebytere

**Comment by bughit** [comment]
> when you enable nodeIntegration, that only turns the integration on for that isolated context

The reason I left nodeIntegration off was I have a memory of experimentally finding that nodeIntegration was still on outside of  isolated context.  It appears to be off now so perhaps I made a mistake or there was a bug at the time.

The docs could use more clarity on the combinations of nodeIntegration and contextIsoation

please confirm the following:

- nodeIntegration
  - on
    - contextIsolation
      - on: Isolated Context is created and node API is only available there
      - off: no Isolated Context is created, node API is available in normal context
  - off
    - contextIsolation
      - on:
        - current: Isolated Context is still created. node API is available there, but not in dev tools
        - expected: noop (no Isolated Context and no node API in normal context)?
      - off: no Isolated Context is created, node API is not available in normal context

**Comment by bughit** [comment]
Ok I think I understand it fully now. 

So then the behavior in this bug is expected, contextIsolation runs the preload script in isolated context, the preload script always has access to API but the isolated context itself (which is what you access via dev console) does not have access to API because nodeIntegration is false.

One question that flows out of this. Does it matter what nodeIntegration is when contextIsolation is true?

It only grants api access to the isolated context, but the only things running in it is the preload script which already has api access.  So is there a practical difference (aside from dev tools console) between the isolated context having access to api and not?

Is {nodeIntegration: false, contextIsolation: true} any more "secure" than {nodeIntegration: true, contextIsolation: true}? The latter grants API access to the isolated context, since nothing but the preload script runs in the isolated context, and the prealod script already has api access, does it matter in any way whether the isolates context has api access?  I.E. does

**Comment by bughit** [comment]
@brenca I have no objections to closing this, given your explanation, but can you please clarify the following:

nodeIntegration:true when contextIsolation:true only grants api access to the isolated context, but the only thing running in the isolated context is the preload script which already has api access. So is there a practical difference (aside from dev tools console) between the isolated context having access to api and not?

**Comment by brenca** [comment]
@bughit Yeah, as far as I know the only thing that gets access in this case is devtools.
It doesn't really matter in this sense whether you turn `nodeIntegration` on or not.

**Comment by bughit** [comment]
@brenca Here's a use case for nodeIntegration: true

webFrame.executeJavaScriptInIsolatedWorld lets you eval scripts in the electron isolated context (world 999).  This works for the top frame, but not subframes, which strikes me as a bug (#12146).
