### ISSUE TITLE
Modal window has no traffic lights to allow user to cancel

### ISSUE THREAD

**Issue by JohannBlake** [electron/electron#11601]
When I create a modal browser window, it shows without any title bar or even any traffic lights (on the Mac). There is no way for the user to close the window. I launch the modal window with an external url (not a file based url). I have tried setting frame to true, titleBarStyle to 'default' but no traffic lights show up.

**Comment by sofianguy** [comment]
Hello! Please follow our [contributing guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md#submitting-issues) for submitting an issue. Thank you

**Comment by codebytere** [comment]
The issue template was not filled out with more information, so i'm going to go ahead and close this
