### ISSUE TITLE
electron versioning

### ISSUE THREAD

**Issue by ColinMoulds** [electron/electron#11611]
When following the quick-start guide located here:
https://github.com/electron/electron/blob/master/docs/tutorial/quick-start.md

using the predefined index.html to report version's like node, chromium and electron. electron 1.7.10 is still appearing as 1.7.9.

* Electron version: 1.7.10
* Operating system: Windows 10

### Expected behavior

The version should reflect 1.7.10

### Actual behavior

The output selects 1.7.9

### How to reproduce

start a new project, follow the guide and basic index.html file and then run the app.

**Comment by akashnimare** [comment]
@ColinMoulds have you installed the electron globally? It's better to mention it in your package.json.
Try using https://github.com/electron/electron-quick-start

**Comment by zeke** [comment]
Like @akashnimare said, you should generally install electron locally in your project, rather than globally.

To remove your global install:

```sh
npm rm -g electron
```

To verify the version you have installed locally in your project:

```
./node_modules/.bin/electron --version
v1.7.10
```

If you have an older version and want to update to the latest stable version:

```
npm i electron@latest --save-dev
```
