### ISSUE TITLE
desktopCapture.getSources with setInterval every second error

### ISSUE THREAD

**Issue by t14luanna** [electron/electron#11612]
I'm using desktopCapture and setInterval to get source of windows every second.

* Electron version: 1.7.10
* Operating system: Windows 10 Pro

### Expected behavior

The bar of Chrome is not crashed
### Actual behavior

The bar of google chrome when getSource is crashed.

**Comment by sofianguy** [comment]
Hi @t14luanna, can you please provide steps to reproduce your problem?

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our [comment](https://github.com/electron/electron/issues/11612#issuecomment-356494174). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
