### ISSUE TITLE
BUG: FATAL:render_process_host_impl.cc(710) on Linux

### ISSUE THREAD

**Issue by gspinaci** [electron/electron#11619]
* Electron version:

1.8.2-beta.3

* Operating system:

Linux Ubuntu 16.04

### Background

Users must click on a button, in the first BrowserWindow, in order to open the second BrowserWindow.

### Expected behavior

First BrowserWindow closed and Second BrowserWindow showed

### Actual behavior

Application crash with this log

```
xxx@xxx~/Downloads/raje-linux-x64/raje-linux-x64$ ./raje 
Window "splash" was created
Window "splash" was closed
Window "editor" was created
Window "editor" was closed
[23645:0110/152208.616951:FATAL:render_process_host_impl.cc(710)] Check failed: !BrowserMainRunner::ExitedMainMessageLoop(). 
#0 0x0000036228e7 <unknown>
#1 0x00000363862b <unknown>
#2 0x00000185a842 <unknown>
#3 0x0000016d7db2 <unknown>
#4 0x000001a052ba <unknown>
#5 0x0000019fa2fd <unknown>
#6 0x0000019fa21c <unknown>
#7 0x000003e8de87 atom::api::WebContents::WebContents()
#8 0x000003e998c6 atom::api::WebContents::Create()
#9 0x000003eabc0f atom::api::Window::Window()
#10 0x000003ead95c atom::api::Window::New()
#11 0x000003e4c6cb mate::internal::InvokeNew<>()
#12 0x000003e4c85e mate::internal::Dispatcher<>::DispatchToCallback()
#13 0x7f8c708c7aa0 <unknown>
#14 0x7f8c70d11823 <unknown>
#15 0x7f8c70d11256 <unknown>
#16 0x219bb65043fd <unknown>

Aborted (core dumped)
```

### How to reproduce

1. Release link [https://github.com/rash-framework/raje-app/releases/tag/v0.1.14](https://github.com/rash-framework/raje-app/releases/tag/v0.1.14) 
2. Clone the current code [https://github.com/rash-framework/raje-app/tree/fix](https://github.com/rash-framework/raje-app/tree/fix)

### Additional notes:
This behaviour happens only in Linux, and only when the user tries to open the second browser window. The application starts without errors until this point.

I have really 0 clues how to fix it.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
