### ISSUE TITLE
Request for documentation clarification around `arm` and `armv7l` downloads

### ISSUE THREAD

**Issue by lurch** [electron/electron#11618]
There was some recent confusion on my team about why https://github.com/electron/electron/releases/tag/v1.7.10 lists downloads for both `arm` and `armv7l`, when https://electronjs.org/docs/tutorial/supported-platforms only mentions the `arm` architecture.

After more confusion and a bit of searching I eventually found https://github.com/electron/electron/blob/master/docs/tutorial/planned-breaking-changes.md#duplicate-arm-assets which cleared up the confusion, but it would be great if that info (i.e. the fact that `arm` and `armv7l` are currently identical) was also added to https://electronjs.org/docs/tutorial/supported-platforms to stop anybody else getting similarly confused :wink:

**Comment by prankshaw** [comment]
I want to resolve this issue

**Comment by lurch** [comment]
Fixed by #11825
