### ISSUE TITLE
blink::SchemeRegistry::RegisterURLSchemeAsCORSEnabled() is going to be deprecated

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#11614]
https://crbug.com/800669

See a design doc for "CORS support in Network Service", https://docs.google.com/document/d/1JNmUcvbw2UcjfdI2uyUpveHXCbae-DQ1n8d_sVs5fLg/edit?usp=sharing

/cc @zcbenz, @MarshallOfSound, @deepak1556

**Comment by deepak1556** [comment]
Thanks for the heads up! We actually need to move all of the `blink::SchemeRegistry` usage to be called once before render threads started, which would require removing the webFrame api and turning it into a command line option or a browser side api, this was found as a part of the dcheck PR https://github.com/electron/electron/blob/master/atom/renderer/api/atom_api_web_frame.cc#L218 . We can fix this along with it as both are breaking.

**Comment by DeerMichel** [comment]
Closing this issue as it doesn't seem to be relevant anymore.
