### ISSUE TITLE
Crash in dev tools console in 1.8.2 beta

### ISSUE THREAD

**Issue by logidelic** [electron/electron#11615]
* Electron version: v1.8.2-beta.3
* Operating system: Ubuntu (both x64 & arm64)

### Expected behavior

When typing something into the Chrome dev tools console **Filter** field, it should filter the console text.

### Actual behavior

Segmentation fault.

### How to reproduce

- Launch an electron app that calls `win.webContents.openDevTools()`
- When the app is open click the **Console** tab in the dev tools and try to type something into the **Filter** field
- Result seg fault

FYI, I tried this on both the x64 & arm64 builds. Otherwise, both builds work great so far!

**Comment by felixrieseberg** [comment]
Closing as duplicate #11375
