### ISSUE TITLE
shell.showItemInFolder won't open Explorer if forward slashes are present in path

### ISSUE THREAD

**Issue by YellowAfterlife** [electron/electron#11617]
* Electron version: 1.7.10
* Operating system: Windows 10, build 1709

If a path contains forward slash(es) on Windows (e.g. `C:\some\app/index.html`), ~~showItemInFolder will open the containing directory but will not select the file.~~ In Electron 8.x and newer, showItemInFolder will not open an Explorer window at all if forward slashes are present in path.

### How to reproduce

https://github.com/YellowAfterlife/abug-electron-showItemInFolder-forward-slashes
```js
const electron = require('electron')
const app = electron.app
const path = require('path')
app.on('ready', () => {
	let test = path.join(__dirname, 'index.html')
	test = test.replace(/^(.+)\\(.+)$/, "$1/$2") // simulate a forward slash in path
	console.log(test)
	console.log(electron.shell.showItemInFolder(test))
	app.quit()
})
```

From what I've seen, no other shell functions show this kind of "partial success" behaviour while returning `true`.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by YellowAfterlife** [comment]
Still happens on 4.0.0-beta10 with same code.

**Comment by TBubba** [comment]
I encountered the same issue but I couldn't figure out why it didn't select the file. Luckily google brought me here. Thanks for the heads up @YellowAfterlife

**Comment by KavenWork** [comment]
`path.normalize`

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by YellowAfterlife** [comment]
It would appear that in 8.0.0-beta.7 Explorer straight up doesn't open if you have forward slashes in path.

**Comment by Christilut** [comment]
Can confirm this happens in Electron `10.1.5`

**Comment by codecosm** [comment]
As of right now Electron 9.0.0 still faces the same issue of the explorer straight up not opening

**Comment by uniqueUsername496** [comment]
> `path.normalize`

Thank you @KavenWork this did the trick for me

**Comment by ArnieGA** [comment]
> `path.normalize`

Thank you very very much, this indeed fixed my issue.

**Comment by YellowAfterlife** [comment]
Still happens in v20.1.4, tested in Fiddle - further degradation from v8 (window doesn't open at all if slashes are malformed) remains.
```js
const {app, shell} = require('electron')
const path = require('path')

app.whenReady().then(() => {
	let test = path.join(__dirname, 'index.html')
	test = test.replace(/^(.+)\\(.+)$/, "$1/$2") // simulate a forward slash in path
	console.log(test)
	console.log(shell.showItemInFolder(test))
	app.quit()
})

```

**Comment by Tanimodori** [comment]
confirmed on v22.1.0

**Comment by YellowAfterlife** [comment]
Still there, tested on v25.0.0-beta-5 in Fiddle.

**Comment by YellowAfterlife** [comment]
It is obviously tempting to just submit a PR with the one-line hack, but also this issue is now old enough to go to school so I'm interested to see how long it will last.

**Comment by YellowAfterlife** [comment]
Still here as of v28.0.0-beta.4

**Comment by YellowAfterlife** [comment]
Still here as of v29.0.0-beta.12
