### ISSUE TITLE
There is no support for authorization using sock5 proxy

### ISSUE THREAD

**Issue by borzovplus** [electron/electron#11620]
* Electron version: 1.7.9
* Operating system: Windows 10 x64

### Expected behavior

There is support for authorization using sock5 proxy in session.setProxy({...}). 
Example: using passwords and username in url: proxyRules: 'socks5://login:password@127.0.0.1:40001'

### Actual behavior

There is no support for authorization using sock5 proxy. Event login on webContents not emitted.

**Comment by kinop112365362** [comment]
Is this feature now supported?

**Comment by xland** [comment]
Is this feature now supported?

**Comment by xland** [comment]
@sofianguy

**Comment by dylan-7** [comment]
Is this feature now supported?

**Comment by nornagon** [comment]
I don't see why it wouldn't be, Chromium supports it and we don't do anything special to disallow it.

**Comment by politsin** [comment]
up

similar problem in apps that use electron 
https://forum.obsidian.md/t/proxy-setting/16063/16
