### ISSUE TITLE
Feature Request: Docked DevTools for <webview>

### ISSUE THREAD

**Issue by jirisliva** [electron/electron#11627]
Hi

object webContents has method [openDevTools](https://electronjs.org/docs/api/web-contents#contentsopendevtoolsoptions) which allows to define way how DevTools will be opened. If _detached_ or _docked_ (bottom, right).

Is there plan to extend <webview>'s method [openDevTools()](https://electronjs.org/docs/api/webview-tag#webviewopendevtools) in same way? 
By means to have same optional parameter _[option]_ which allows me to open DevTools _docked_ in BrowserWindow (bottom, or right).

**Comment by MarshallOfSound** [comment]
This is now possible see https://github.com/electron/electron/pull/11300 and https://github.com/electron/electron/issues/3177

**Comment by kitze** [comment]
@MarshallOfSound unfortunately, this doesn't work in the latest version of Electron anymore. Do you have an idea what happened?

**Comment by swati-maheshwari** [comment]
does it works?

**Comment by kitze** [comment]
@MarshallOfSound this should be reopened

**Comment by Nashorn** [comment]
> @MarshallOfSound unfortunately, this doesn't work in the latest version of Electron anymore. Do you have an idea what happened?

I've also tried the snippet, dev tools loads in a webview, but its Elements tab is blank. Almost as if not associated with the page i want to inspect in my other webview.

**Comment by Nashorn** [comment]
> does it works?

No
