### ISSUE TITLE
Bug Report: On Linux, with "--enable-transparent-visuals" command, all BrowserWindows become semi transparent and the colours of the pages are washed out.

### ISSUE THREAD

**Issue by B-0-B-B-Y** [electron/electron#11623]
* Electron version: v1.7.10
* Operating system: Linux Mint 18.2, running kernel 4.13.0-26-generic

### Expected behavior

BrowserWindow has transparency, and all colours remain exactly as intended.
What it used to look like before the computer restart: https://ibb.co/iUu5E6

### Actual behavior

In order to have transparency in Linux, it is necessary to append the "--enable-transparent-visuals"  and "--disable-gpu" commands. This was working fine and the behaviour of my electron app was as intended. After I restarted my system, having made no changes to the app whatsoever, upon running it again, all BrowserWindow objects, not just the one with "transparent: true" options are semi transparent, in that the colours of the html page are very washed out and have an opacity of something around 70%. Removing the "--enable-transparent-visuals" command returns all the BrowserWindows objects to look as intended, except for the transparent window which has a white background where there should be transparency, which is expected behaviour since the "--enable-transparent-visuals" command has been removed. The only thing I can think of that may have had an effect is updates of the following packages that happened before the system restart:
Package: ruby2.3, from version 2.3.1-2\~16.04.4 to version 2.3.1-2\~16.04.5
Package: libruby2.3, from version 2.3.1-2\~16.04.4 to version 2.3.1-2\~16.04.5
Package: nodejs, from version 9.3.0-1nodesource1 to version 9.4.0-1nodesource1
Package: linux-libc-dev, from version 4.4.0-108.131 to version 4.4.0-109.132

What it looks like after the restart: https://ibb.co/mafO1m

### How to reproduce
I have provided a repository of my project here: https://github.com/B-0-B-B-Y/desktop-youtube.git

The setup instructions for it are provided in the readme.md file, but I will copy them in here too for simplicity:

1) Open a terminal
2) Navigate to the directory of your choice where you want to clone this project to
3) Run the command: **git clone -b transparency-issue https://github.com/B-0-B-B-Y/desktop-youtube.git**
4) Then run: **cd desktop-youtube**
5) Run: **ls** and verify that you can see a file called **main.js**
2) Whilst in the same directory where the main.js file is located, please run from terminal: **npm install electron --save-dev**
3) Once that's complete, still being in the same directory as main.js, run from terminal: **npm start**

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
