### ISSUE TITLE
Process frames from desktopCapturer navigator.mediaDevices.getUserMedia

### ISSUE THREAD

**Issue by developer239** [electron/electron#11637]
* Electron version: 1.7.8
* Operating system: MacOs

### Expected behavior

Using `desktopCapturer` and `navigator.mediaDevices.getUserMedia` get `.then((MediaStream) => {` and process every frame of the stream efficiently. `MediaStream.onFrame(blob => { // do something special })`

### Actual behavior

Using `desktopCapturer` and `navigator.mediaDevices.getUserMedia` get `.then((MediaStream) => {` there isn't any way how to access stream frames efficiently. The only thing possible is using something like `setInterval` with `ImageCapture` and `capturedImage.takePhoto` but this is **really** ineficient.

### How to reproduce

```
navigator.mediaDevices.getUserMedia({
  audio: false,
  video: {
    mandatory: {
      chromeMediaSource: 'desktop',
      chromeMediaSourceId: source.id,
      minWidth: 1000,
      maxWidth: 1000,
      minHeight: 1000,
      maxHeight: 1000,
    },
  },
})
.then((stream) => {
  const track = stream.getVideoTracks()[0];
  const capturedImage = new ImageCapture(track);

  capturedImage // This takes 200ms for 1000x1000
    .takePhoto()
    .then(blob => {
      toBuffer(blob, function (err, buffer) { // 1.5 ms
        if (err) throw err;
          // TODO: Do some opencv magic with node buffer
      });
    })
    .catch(error => console.error('takePhoto() error:', error));
}
```

**Comment by codebytere** [comment]
Sadly this isn't something we have control over; if you see docs here: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia you can potentially file a feature request somewhere there.
