### ISSUE TITLE
menu.popup() callback argument doesn't seem to work

### ISSUE THREAD

**Issue by astoilkov** [electron/electron#11636]
* Electron version: 1.7.9
* Operating system: macOS 10.13 and Windows 10

### Expected behavior

`menu.popup(options, callback)` to execute `callback` function when context menu is closed

### Actual behavior

`callback` function is not executed

### How to reproduce

I am calling the code from the main process.

```
let menu = electron.Menu.buildFromTemplate(template);
menu.popup({
  async: true,
  x: 10,
  y: 10
}, () => {
   // this is not executed  
});
```

**Comment by astoilkov** [comment]
I am uploading a project reproducing the issue.

[menu-popup-callback-bug.zip](https://github.com/electron/electron/files/1629637/menu-popup-callback-bug.zip)

**Comment by codebytere** [comment]
@astoilkov i'll 👀  this this morning

**Comment by codebytere** [comment]
@astoilkov hmm, i'm having trouble reproducing on mac...if you add a console log to the callback do you see it there? i ran the code with:
```
setTimeout(() => {
    let menu = Menu.buildFromTemplate([{ label: 'Item' }])

    menu.popup({
      x: 10,
      y: 10,
      async: true
    }, () => {
      console.log('we are in the callback')
      app.quit()
    })
  }, 1000)
```
and saw
<img width="368" alt="screen shot 2018-01-16 at 9 38 55 am" src="https://user-images.githubusercontent.com/2036040/34994316-18eb0418-faa1-11e7-8c12-0a9c877d36a9.png">
in console, so the callback appears to be executing

**Comment by astoilkov** [comment]
No, I don't see it. I recorded a gif showing that the value is not logged.

http://g.recordit.co/of9VJNHoIn.gif

**Comment by codebytere** [comment]
in the gif do you actually click the menu item?

**Comment by codebytere** [comment]
hmm...that tells me it's a high sierra issue (i'm running 10.12), i'll dig further

**Comment by astoilkov** [comment]
Doesn't matter if I click the item or not.

**Comment by codebytere** [comment]
I'm still having trouble reproducing this; can you please verify it persists with `1.7.10`, or if possible, master? i made significant changes in that file about three months ago: https://github.com/electron/electron/blame/master/lib/browser/api/menu.js#L1

**Comment by codebytere** [comment]
@astoilkov did you try more recent versions? does current master work?

**Comment by astoilkov** [comment]
@codebytere Not sure how to try master. However, I tried `^1.8.2-beta.3` and launching the same app threw an error on the line where the `popup()` method was called. It seems the `popup()` method now requires the `browserWindow` object to be passed (maybe no longer optional parameter). After changing the code to one shown below the app started correctly and opened the menu but again didn't call the callback.

```
setTimeout(() => {
  let menu = Menu.buildFromTemplate([{ label: 'Item' }]);

  menu.popup(win, { x: 10, y: 10, async: true }, () => {
    console.log('log');
    app.quit();
  });
}, 1000)
```

If you tell me how to try master I can also do that.

**Comment by brenca** [comment]
The callback parameter was added to `master` in [this PR](https://github.com/electron/electron/pull/11546), which replaced the `closed` event of the menu, and since that didn't make it into any releases (it was pushed after the 1-8-x branch was cut from master), the callback also didn't make it into any releases, and this is why it doesn't work on any version, except for a build of the master branch.
