### ISSUE TITLE
Change macOS "Standard Menu Item Actions" app name

### ISSUE THREAD

**Issue by fttx** [electron/electron#11630]
* Electron version: 1.7.10
* Electron builder: 19.52.1
* Operating system: macOS High Sierra 10.13.2

### Given package.json

```
{
    "name": "barcode-to-pc-server",
    ...
    "build": {
        "productName": "Barcode to PC server",
        ...
    }
    ...
}
```

### Expected behavior

I expected to see the package.json>build>productName in the application menu>About/Hide/Quit
Is there another property for that?

### Actual behavior

I see the package.json>name in the application menu
![image](https://user-images.githubusercontent.com/5663423/34906909-b9c0b41e-f876-11e7-849f-e89dc49415da.png)

docs: https://electronjs.org/docs/api/menu#standard-menu-item-actions

**Comment by MarshallOfSound** [comment]
@fttx Please raise `electron-builder` questions on the [electron builder repo](https://github.com/electron-userland/electron-builder).  It isn't an `electron` org project 👍
