### ISSUE TITLE
Prevent Connection to Github on install

### ISSUE THREAD

**Issue by raybooysen** [electron/electron#11639]
In `npm/install.js`, the post-install step talks out to github.  On networks where github.com is blocked, this means we cannot install Electron.

**Comment by felixrieseberg** [comment]
There is a way, it's just not well-documented. I fixed that over in this PR, which also contains all your answers: https://github.com/electron/electron/pull/11640

**Comment by codebytere** [comment]
PR will be merged soon, closing as this issue has been resolved with a solution :)

**Comment by raybooysen** [comment]
Thank you!
