### ISSUE TITLE
Fullscreen is not working on Linux with focusable: false

### ISSUE THREAD

**Issue by hovancik** [electron/electron#11632]
* Electron version: 1.7.10
* Operating system: Linux (Debian, Elementary OS)

### Expected behavior

Browser window is fullscreen

### Actual behavior
Browser window is not fullscreen

### How to reproduce
```
# Clone this repository
git clone https://github.com/hovancik/electron-fullscreen-focusable.git
# Go into the repository
cd electron-fullscreen-focusable
# Install dependencies
npm install
# Run the app
npm start
```

![bug](https://user-images.githubusercontent.com/4745859/34909230-5fe43e6c-f89d-11e7-823d-8528281a1705.png)

**Comment by spotman** [comment]
Any thoughts about fixing fullscreen issue?

**Comment by lundibundi** [comment]
Tested on Arch linux with the same results using Electron 2.0.3 and Electron 3.0.0-beta.1

Steps to reproduce:
Steps in the original post but use `npm install electron@2.0.3`
Steps in the original post but use `npm install electron@3.0.0-beta.1`

**Comment by hovancik** [comment]
The behavior is the same with `setKiosk` instead of `setFullscreen`

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by hovancik** [comment]
still issue in electron 6.

**Comment by lkrms** [comment]
@hovancik using your test app, I was able to create a workaround for this (NB: I can't tell if it's an electron bug or a limitation of Linux window management).

```js
// additional APIs
const screen = electron.screen
const os = require('os')
```
...
```js
  if (os.platform() != 'linux') {
    mainWindow = new BrowserWindow({ width: 800, height: 600, fullscreen: true, focusable: false })
  }
  else {
    let display = screen.getPrimaryDisplay()
    mainWindow = new BrowserWindow({
      x: display.bounds.x,
      y: display.bounds.y,
      width: display.size.width,
      height: display.size.height,
      fullscreen: true,
      focusable: false
    })
  }
```

As best I can tell, this achieves the desired behaviour. On my system (Xfce4), all panels were blocked and unclickable on the primary display until the app was terminated. I did upgrade to electron 8.2.3, but hopefully earlier versions work the same way.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by hovancik** [comment]
Thanks to the friendly bot, I had to recreate this issue: https://github.com/electron/electron/issues/28130 Please subscribe there if you want to get updates.
