### ISSUE TITLE
npm i electron@1.8.2-beta.3

### ISSUE THREAD

**Issue by KorobkaVadim** [electron/electron#11638]
* Electron version:
* Operating system: Win 10 x64

### How to reproduce

When i run command ```npm i electron@1.8.2-beta.3```
Eset Nod32 Antivirus shout NSIS/TrojanDownloader.Adload

**Comment by felixrieseberg** [comment]
I'm afraid your AV is incorrect. You can find more information about what's happening during installation in this PR: https://github.com/electron/electron/pull/11640

**Comment by sofianguy** [comment]
Seems @felixrieseberg has your solution. Closing this.
