### ISSUE TITLE
Write a tutorial about persisting application state

### ISSUE THREAD

**Issue by zeke** [electron/electron#11655]
@bpasero is on the lookout for a performant solution for persisting application state:

> Did anyone ever play around with (or is actually using in production) a replacement to `localStorage` for storing application state? In VS Code we heavily use it for UI state, but we are not so happy with the performance of using `localStorage` (each `get`/`set` basically needs to travel to the main process and back again). One requirement would still be that multiple processes can access the data, which pretty much seems to leave us with embedded databases as the only choice (sqlite, etc) which seem a bit overkill.

I suggested https://github.com/sindresorhus/electron-store, but it may not be the most performant solution, and there could be issues with multiple processes stepping on each other's toes as they attempt to write to disk.

@paulcbetts suggests:

> I would just switch to IndexedDb. local storage is slow because all of the calls are sync calls and that means it's blocking the renderer for however long the main process is busy for
>
> So if the main process is blocked up, your localstorage calls are gonna be slow
> IndexedDb is the same sitch only async, so even if that DB call takes a bit, your app isn't parked on it
>
> https://github.com/jakearchibald/idb is probably what you want in VS Code given how lean you keep the dependencies
>
> dexie.org is what you want if you're a little more open to `npm install`ing

This is an example of a topic that we're hoping to cover with https://github.com/electron/electron/issues/11416

**Comment by zeke** [comment]
More from @bpasero:

> I think IndexDB is also not an option for us because as far as I know, you can also only access the data from renderers. We have node.js only processes that would have an interest in reading/writing to that same data too.
> 
> using node-sqlite3 I managed to read the local storage DB by just opening it. Though it is not clear to me if Chrome gets into trouble when some other process suddenly opens the localStorage DB for reading/writing.

**Comment by zeke** [comment]
https://blog.avocode.com/4-must-know-tips-for-building-cross-platform-electron-apps-f3ae9c2bffff#e75f

**Comment by DeerMichel** [comment]
Closing this issue since there has not been any recent activity. There are currently no plans on writing documentation for third-party libraries. Personally, I've used NeDB and electron-store for which both plenty tutorials/articles are available online.

**Comment by zeke** [comment]
I am mostly happy with `electron-store` as well, but still waiting for `onDidChange` event support: https://github.com/sindresorhus/electron-store/issues/39

**Comment by bpasero** [comment]
VSCode is using SQLite now as store (https://github.com/mapbox/node-sqlite3) and I am more than happy with the result.
