### ISSUE TITLE
Downloads are failing with state 'interrupted' from custom protocols in 1.8.2-beta.3

### ISSUE THREAD

**Issue by pfrazee** [electron/electron#11657]
* Electron version: 1.8.2-beta.3
* Operating system: MacOS 10.12

### Expected behavior

File downloads from custom protocols should complete without issue.

### Actual behavior

Before even triggering the custom protocol handler, the download-item emits 'done' with a state of 'interrupted'. In my demo linked below, I use the new registerStreamProtocol, but I was able to reproduce using registerHttpProtocol as well.

### How to reproduce

Use https://github.com/pfrazee/electron-download-interrupt-bug

**Comment by pfrazee** [comment]
Im booting up my linux box to do some debugging on the electron codebase. Will report what I find (hopefully will be able to PR a fix).

**Comment by pfrazee** [comment]
This is getting logged by chromium:

```
[19102:0117/142535.172538:WARNING:url_request_job_manager.cc(90)] Failed to map: custom://foo.com/index.html
```

**Comment by pfrazee** [comment]
I found the issue. It was introduced by this commit: https://github.com/electron/electron/commit/6b2ddc481477f6311cd3d8994c2421a2d1540823

@tarruda It looks like `request->initiator().has_value()` is false if `webContents.downloadURL()` is called, and also when initiated by the PDF download fallback behavior (when plugins are disabled). Either the initiator needs to be set in those cases, or your commit needs to be rolled back or modified.

**Comment by pfrazee** [comment]
Would anybody object to a PR which reverts https://github.com/electron/electron/commit/6b2ddc481477f6311cd3d8994c2421a2d1540823 ?

**Comment by tarruda** [comment]
The main reason I added https://github.com/electron/electron/commit/6b2ddc481477f6311cd3d8994c2421a2d1540823 is to allow `interceptStreamProtocol('https')` to modify/delegate requests to `electron.net`. Without this commit, invoking `electron.net` while intercepting http/https will result in an infinite loop.

In any case, my approach to breaking the infinite loop was was kinda hacky and needs to be fixed. A possible solution is to put `URLRequest` pointers created by `electron.net` in a weak set that is checked by `MaybeCreateJob`. I will send a PR with this fix later this week.

**Comment by pfrazee** [comment]
Ok solid, I appreciate it.

**Comment by brenca** [comment]
@tarruda We use custom protocols that redirect to other custom protocols, and 6b2ddc4 sadly broke that too.

**Comment by tarruda** [comment]
I've been quite busy these days so couldn't find the time to do it yet, but will probably be able to do this on the weekend.

**Comment by alexeykuzmin** [comment]
The fix landed in `master` (and `2-0-x`) but not in `1-8-x`.
@ckerr, @jkleinsc Do we want to back port it to `1-8-x`?

**Comment by jkleinsc** [comment]
@alexeykuzmin I'll backport to 1-8-x

**Comment by alexeykuzmin** [comment]
> @alexeykuzmin I'll backport to 1-8-x

Was backported in #12100.
