### ISSUE TITLE
Google Drive Picker does not work in Electron App

### ISSUE THREAD

**Issue by godza** [electron/electron#11651]
* Electron version: 1.7.10
* Operating system: macOS 10.13.2

### Expected behavior

When Google Drive Picker is initialized, i expect for picker to appear in DOM. When i load my code in Chrome (and other browser) that happens, in electron App it doesn't.

### Actual behavior

New browser window is opened to authenticate to google services (which is ok, that happens in browser too and it's regular procedure). After login succeeds window then closes (which is ok, also happens in browser), and **nothing happens** in electron app (in browser google drive file picker is shown as iframe).

When i inspect page in browser iframe is there, but when i inspect DOM in electron app, iframe does not exist.

### How to reproduce
Best way is to use my fork of electron-quick-start repository where i've demonstrated this bug.

```
$ git clone https://github.com/godza/electron-quick-start
$ cd electron-quick-start
$ npm install
$ npm start || electron .
```

You can also open the page directly in browser to confirm expected behavior http://goranradulovic.com/google-drive-example.html

In case of electron app, it should load the same page i left url for. In browser, there is a picker, in electron there is not.

Thanks.

**Comment by MarshallOfSound** [comment]
Merging into #9581

**Comment by JuanFerrer** [comment]
You can use [Google Drive's Backup and Sync](https://google.com/drive/download). It adds a Google Drive folder to your normal file system.

**Comment by godza** [comment]
@JuanFerrer it's not my personal problem, but our customers problem. I can't ask of them to install software on their computers to attach file from google drive.

**Comment by godza** [comment]
Running latest beta 1.8.2-beta.5 it seems that this behavior is fixed and everything works properly

**Comment by ckerr** [comment]
@godza thanks for the update :+1:
