### ISSUE TITLE
How to Disable [Deprecation] getCurrentPosition() ?

### ISSUE THREAD

**Issue by abdurrahmanekr** [electron/electron#11650]
Hi I'm using loadUrl method as you can seen in the main.js file.
```javascript
mainWindow.loadURL(url.format({
    pathname: "example.com/index.html",
    protocol: "http", // important section
    slashes: true
}));
```
And I'm also using getCurrentPosition method in renderer file like that:
```javascript
window.navigator.geolocation.getCurrentPosition(position => {
    console.log(position);
}, err => {
    console.log(err);
});
```
But I'm getting this error: 
```
[Deprecation] getCurrentPosition() and watchPosition() no longer work on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
```
How can I ignore this warning?

* Electron version: 1.7.7
* Operating system: Darwin

**Comment by codebytere** [comment]
This function makes implicit use of a [Google API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/getCurrentPosition), so you can switch to `https` to remove the deprecation warning but electron itself is not responsible for the deprecation or warning so you'll need to look elsewhere for how to suppress it.
