### ISSUE TITLE
Feature request: Ability to set display time for notification (Mac)

### ISSUE THREAD

**Issue by clusterberries** [electron/electron#11661]
* Electron version: 1.8.2-beta.3
* Operating system: Mac

### How to reproduce
Hi guys! 
Notification created in the main process is closed automatically after ~5 seconds.
It would be great to add ability to configure this value or just add property like 'waitForResponse' that means notification is closed only by the user or via method notification.close().
Could somebody take a look, please? Thank you!

**Comment by sethlu** [comment]
@clusterberries We use `NSUserNotification` to deliver macOS notifications to users. However, there is no documented way that allows us to set the duration of the notification on macOS.

However, if a notification is displayed as an “alert” you may be able to code to show and hide a notification.

**Comment by codebytere** [comment]
@clusterberries closing this based on response from above; this feature isn't something we can add at this time, although an alert might provide a better solution for your use case. Good luck!
