### ISSUE TITLE
Win Administrator issue

### ISSUE THREAD

**Issue by wave2588** [electron/electron#11660]
I want write some content to the 'regedit'.
But user must mouse right click choose 'run the Administrator' to successed.
How can double click to get access to administrator rights?
Looking forward to your reply.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by wave2588** [comment]
ok, thanks
