### ISSUE TITLE
The dialog should be modal window on the windows OS， and should be able to set the style of the title bar and content

### ISSUE THREAD

**Issue by ryanxueqian** [electron/electron#11672]
1. The dialog should be modal window on the windows OS, because it's not a modal window that makes a lot of trouble.

2. The default style of electron dialog is ugly, it should be able to set the style of the dialog's title bar 、content and action buttons

* Electron version:
* Operating system:

**Comment by codebytere** [comment]
You'll need to fill out the issue template and include more information as well as a clearer description of what you're looking for before we can consider this feature request. Thanks!

**Comment by codebytere** [comment]
With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
