### ISSUE TITLE
Chrashed when setup.

### ISSUE THREAD

**Issue by songsammy** [electron/electron#11674]
* Electron version:1.3.0
* Operating system: win7 64bit

### Expected behavior

Setup.
### Actual behavior

Crashed.Fail to open the log.
![error](https://user-images.githubusercontent.com/30046778/35155437-89f24abc-fd68-11e7-839d-f7358d7f1b47.PNG)
For some apps like firefox , it happened not able to launch, however , after reinstalling it, it worked.
### How to reproduce
I just dobule-clicked it.

**Comment by codebytere** [comment]
It looks like you attempted to run `Electron API Demos`, which is built on electron but housed in a separate [repo](https://github.com/electron/electron-api-demos). Please feel free to open an issue there, but unless it's shown that this is an issue with electron itself this issue is being closed.
