### ISSUE TITLE
CI documentation

### ISSUE THREAD

**Issue by magne4000** [electron/electron#11676]
Would it be possible to have a documentation around CIs used to compile Electron ?
The goal would be to:
1) Document current CI state and follow advancement
2) Help people (like me) to put in place their own CI instances for Electron

Here are the infos I would need to get started:
- Clear list of CIs currently in use, and their corresponding build targets
- The configuration for each of the CIs
  - including env vars and how to generate them, which ones are mandatory
- How to trigger a build
- How to integrate auto publish with Github/S3

Thank!

**Comment by codebytere** [comment]
Our CI configs are public, but as things change so fast any documentation will constantly be outdated, and it's not really something that a significant number of users/developers will need. In that event, you are more than welcome to peruse all of our configs but we won't create full documentation for CI.
