### ISSUE TITLE
Windows Position and Height/Width

### ISSUE THREAD

**Issue by hevilp** [electron/electron#11682]
Hello,

with https://github.com/mawie81/electron-window-state there is a possibility to save window propertiers. But it seems to be abandoned. Is there any native way to save windows hieght/width and postion or its planned?

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
