### ISSUE TITLE
Devtools will not appear in menubar app

### ISSUE THREAD

**Issue by naheller** [electron/electron#11689]
* Electron version: 1.7.10
* Operating system: macOS 10.13.2

I am building an Electron app using React that lives up in the menubar. For some reason, I cannot get devtools to appear! Since this is a menubar app, I need the devtools to appear detached. My code is shown below.

`main.js`:

    app.on('ready', () => {
      createTray()
      createWindow()
    })

    const createTray = () => {
      tray = new Tray(icon)
      tray.on('click', toggleWindow)
    }

    const createWindow = () => {
      window = new BrowserWindow({
        width: 387,
        height: 359,
        show: false,
        frame: false,
        resizable: false,
        fullscreenable: false,
        webPreferences: {
          backgroundThrottling: false
        }
      })

      let indexPath;
      if ( dev && process.argv.indexOf('--noDevServer') === -1 ) {
        global.developmentMode = true;
        indexPath = url.format({
          protocol: 'http:',
          host: 'localhost:8080',
          pathname: 'index.html',
          slashes: true
        });
      } else {
        global.developmentMode = false;
        var httpServer = require('http-server');
        var webRoot = path.join(__dirname, 'dist');
        server = httpServer.createServer({
          root: webRoot,
          robots: true,
          headers: {
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Credentials': 'true'
          }
        });
        server.listen(15426);
        indexPath = url.format({
          protocol: 'http:',
          hostname: 'localhost',
          port: '15426',
          pathname: 'index.html',
          slashes: true
        });
    }
      window.loadURL(indexPath)
      // this is where I thought to open devtools
      window.webContents.openDevTools({ mode: 'detach' });
    }

    const toggleWindow = () => {
      if (window.isVisible()) {
        window.hide()
      } else {
        showWindow()
      }
    }

    const getWindowPosition = () => {
      const windowBounds = window.getBounds()
      const trayBounds = tray.getBounds()

      // Center window horizontally below the tray icon
      const x = Math.round(trayBounds.x + (trayBounds.width / 2) - (windowBounds.width / 2))

      // Position window vertically below the tray icon
      const y = Math.round(trayBounds.y + trayBounds.height)

      return {x: x, y: y}
    }

    const showWindow = () => {
      const position = getWindowPosition()
      window.setPosition(position.x, position.y, false)
      window.show()
      window.focus()
    }

Your advice is appreciated!

**Comment by pronebird** [comment]
`window.openDevTools({ mode: 'detach' });`

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by naheller** [comment]
hi @pronebird! I was not able to make devtools appear using your solution. Is there a reason you suggested leaving out `webContents`?

**Comment by pronebird** [comment]
@nahellee not sure, probably it’s the same call. Just copied the line I use to do the same which works for me
