### ISSUE TITLE
Unable to read process.stdin in main process

### ISSUE THREAD

**Issue by deepakjha14** [electron/electron#11680]
* Electron version:1.7.10
* Operating system:Win 10, 64-bit

### Expected behavior

It should listen to the process.stdin and should be able to write on process.stdio. I am able to launch the electron app from chrome extension but I am unable to read input sent from chrome extension using native messaging protocol.

### Actual behavior

I am unable to read from process.stdin.on('data', function(chunk){//log message received as chunk})

### How to reproduce

here is the url of my repo.

https://github.com/deepakjha14/ElectronDesktop-App

  $ git clone https://github.com/deepakjha14/ElectronDesktop-App
Delete the node_modules I have kept it in my repo to just show you what else do i have in my node_modules and its code in case you need them.
  $ npm install
  $ npm start || electron .

-->

**Comment by codebytere** [comment]
Hi @deepakjha14, you had:
```
process.stdin.on('data', (chunk) => {
    logger.log('I have received this data:- '+chunk);
});
```
and according to [documentation](https://nodejs.org/api/process.html#process_process_stdin) it should in fact be:
```
process.stdin.on('readable', (chunk) => {
    logger.log(`I have received this data:- ${chunk}`);
});
```
When i tested this, i was able to see the text logged to console. Closing as this is not an issue with electron, but rather an issue with your use of node's `process.stdin`.
