### ISSUE TITLE
App opened in fullscreen is missing BW control buttons (close, minimize)

### ISSUE THREAD

**Issue by cumajkeee** [electron/electron#11687]
* Electron version: 1.7.10
* Operating system: MacOS High Sierra

### Expected behavior
Window control buttons should be present

### Actual behavior

Window control buttons are missing

### How to reproduce
Only on MacOS High Sierra!
run `npm start`, and go with mouse to the top to see menu and titlebar

[browserWindowCotrolsMissed.zip](https://github.com/electron/electron/files/1651456/browserWindowCotrolsMissed.zip)

**Comment by sweetevil** [comment]
@cumajkeee Any fix/workaround you got working ?

**Comment by cumajkeee** [comment]
@sweetevil, unfortunately no

**Comment by codebytere** [comment]
`show: false` and `fullscreen: true` conflict; this works correctly and shows the window control buttons if you simply use `fullscreen: true`.
