### ISSUE TITLE
Electron Autoupdater Stopped working

### ISSUE THREAD

**Issue by setpixel** [electron/electron#11688]
This probably isn't the right place to post this, as it is a GH api issue.

https://github.com/electron-userland/electron-builder/issues/2508

However it affects many people distributing electron apps right now.

So if you know anyone that works at GH... a fix would be great :D

**Comment by codebytere** [comment]
Hi, this tab is only for reporting issues with Electron itself. We're not the place to report or fix issue with the GitHub API.

**Comment by setpixel** [comment]
Do you know where that would be?

**Comment by setpixel** [comment]
nevermind! this was my bad!
