### ISSUE TITLE
The webview's devtools not work when loadURL "http://2108d062.nat123.cc:54989/budget"

### ISSUE THREAD

**Issue by yangheng** [electron/electron#11684]
* Electron version: 1.8.0
* Operating system: win7

The error is below:
```
 [2536:0122/151911.448:ERROR:CONSOLE(1069)] "Uncaught TypeError: Cannot read property '__widgetCounter' of null", source: chrome-devtools://devtools/bundled/inspector.js (1069)
```

### How to reproduce
There is a BrowserWindow which has many webviews in my app.  It's ok when load other website, but it not work and throw this error  when load "http://2108d062.nat123.cc:54989/budget". 
Note that "http://2108d062.nat123.cc:54989/budget" is a old website and especially for ie .

**Comment by sofianguy** [comment]
Can you provide us with a way to reproduce this issue?

**Comment by yangheng** [comment]
@sofianguy I had found the reason for this issue. The problem lies with us， not electron. Sorry .
