### ISSUE TITLE
native window.open always uses same preload script as opener

### ISSUE THREAD

**Issue by matthewjh** [electron/electron#11681]
* Electron version: 1.7.10
* Operating system:Windows 7

### Expected behavior

When using native window.open and overriding the "new-window" event to replace the "newGuest" window with a new BrowserWindow instance, the preload script specified in the BrowserWindow options.webPreferences should be used.

### Actual behavior

Preload script URL of opener window is always used, regardless of BrowserWindow options on the "guest" window.

**Comment by codebytere** [comment]
Please provide steps to reproduce and then we can take a look at this!

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our [comment](https://github.com/electron/electron/issues/11681#issuecomment-359424710). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
