### ISSUE TITLE
More control over tray context menu state/visibility

### ISSUE THREAD

**Issue by 6twenty** [electron/electron#11683]
Would it be possible to add methods and/or events to expose the visibility state of Menu instances? For example methods like `Menu#isVisible()` and `Menu#isHidden()` and events like "show" and "hide".

**Comment by 6twenty** [comment]
For a bit of context, I have a menu bar app that creates a Tray instance and a Menu instance, and calls `tray.setContextMenu(menu)`. I'd like to respond to the context menu being opened in order to trigger a data refresh.

Note: using a "click" event handler on the Tray instance is also unreliable:

- When using `setContextMenu(menu)`, "click" events cannot be registered
- When using `popUpContextMenu(menu)`, the click event is only triggered when showing the menu (not when closing it)

**Comment by codebytere** [comment]
@6twenty, the first issue has been fixed:
> When using setContextMenu(menu), "click" events cannot be registered
by https://github.com/electron/electron/pull/12043

i'll see if i can add some events or visibility state methods in the near future :)

**Comment by 6twenty** [comment]
@codebytere great! Thanks for letting me know :-)

**Comment by damianobarbati** [comment]
Is it possible to close the tray i.e `tray.close()` or `tray.closeContentMenu()`? 

My goal is to show a menu with "welcome bla bla" the first time the app is minimized to tray and hide it after 5s.

**Comment by j1mie** [comment]
Hi @6twenty - do you have any suggestions for a workaround for:

> For a bit of context, I have a menu bar app that creates a Tray instance and a Menu instance, and calls tray.setContextMenu(menu). I'd like to respond to the context menu being opened in order to trigger a data refresh.

**Comment by 6twenty** [comment]
Hey @j1mie - it's been a while since I've dealt with this so my info might be outdated by now, but it depends on what you need to do: if you only need to respond to the menu being opened then it should be ok to just register a click event on the tray instance. However as far as I know you can't handle the menu being subsequently closed.
