### ISSUE TITLE
Focus of input field went off while the updates comes from server(in OS console)

### ISSUE THREAD

**Issue by sakamudis** [electron/electron#11695]
Electron version: 1.7.7
Operating system: Cent OS 7

React application with electron on Cent OS 7.

Expected result:
Focus should be in the same input field.

Actual result:
Focus went off from that electron window

I have a login page with username and password. While entering username/password the focus of input field is shifting(went off) to another active window(either OS console window or another electron window)
How to prevent that behavior or keep the focus forcefully in the same input field?

**Comment by MarshallOfSound** [comment]
>  focus of input field is shifting(went off) to another active window(either OS console window

It sounds like another window is seizing focus from you, there isn't much you can do to prevent this.  In fact preventing your app from being unfocused is probably a bad thing 😄 If you really want to ensure your app doesn't lose focus you can.

```js
mainWindow.on('blur', () => mainWindow.focus())
```

**Comment by sakamudis** [comment]
mainWindow.on('blur', () => mainWindow.focus()) is working to focus the window. Thanks for that,
but this code is not allowing to do anything in input elements of other electron windows if the **mainWindow** opens.
