### ISSUE TITLE
Notification Duration

### ISSUE THREAD

**Issue by mm739521** [electron/electron#11690]
Is there anyway to set the duration or timeout of electron Windows notification?  Right now the default seems to be set around 5 which doesn't feel like it's long enough to notice it and act on it.

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
