### ISSUE TITLE
How can I copy and paste files

### ISSUE THREAD

**Issue by dengyaolong** [electron/electron#11696]
* Electron version: 1.7.9
* Operating system: mac 10.12.6

### Expected behavior

copy files on desktop. paste in electron App.

### Actual behavior
paste nor work

It's any workaround to copy & paste files in electron?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
