### ISSUE TITLE
Electron hangs and leads to 100% CPU usage after calling callback via uv_async_send on a single-core machine

### ISSUE THREAD

**Issue by alexey-ambrozevitch** [electron/electron#11699]
* Electron version: 1.7.8
* Operating system: Windows 7 x64 Enterprise

### Expected behavior
Electron processes callback dispatched by uv_async_send function in the normal way.

### Actual behavior
Electron hangs and leads to 100% CPU usage after calling callback via uv_async_send.

### How to reproduce
The problem can be reproduced only on a single-core machine.

**Comment by zcbenz** [comment]
Can you make a minimal reproducible example? `uv_async_send` is heavily used in native modules and Electron itself, the problem is probably on other things.

**Comment by alexey-ambrozevitch** [comment]
We implement our own node.js module. It has to initiate simple JavaScript function call. So first of all we initialize loop by uv_default_loop(), then initialize uv_async_t(), make call uv_async_init with initialized parameters and then make uv_async_send. After that Electron root process begins to consume 100% CPU and our JavaScript procedure does not implement (callback, passed to uv_async_init as the third parameter does not begin at all). Then if click on UI or make some actions with it, CPU slows down  and our procedure begins to implement.

**Comment by alexey-ambrozevitch** [comment]
After investigation of the source code of Electron, it was turned out that the problem was caused by atom::NodeBindingsWin::PollEvents method. The call of ::GetQueuedCompletionStatus on thread that differs from libuv poll leaded to errors inside uv_run API. After replacing the pair of IOCP functions to polling on uv_loop_alive, the problem had been sorted out.

**Comment by alexey-ambrozevitch** [comment]
Also, could you please provide any information whether the fix with uv_loop_alive will not cause any side effects.

**Comment by gshively11** [comment]
@alexey-ambrozevitch I'm tracking down a similar issue, can you paste the changes you made to get it working, please?

**Comment by bughit** [comment]
[minimal reproducible example](https://github.com/electron/electron/issues/14319#issuecomment-417138296) that @zcbenz asked for

**Comment by zcbenz** [comment]
Fixed by https://github.com/electron/electron/pull/15975.
