### ISSUE TITLE
Tray bounds not returning properly y coordinate when external screen is placed vertically above the Retina display

### ISSUE THREAD

**Issue by jsynowiec** [electron/electron#11709]
* Electron version: 1.7.11
* Operating system: macOS 10.12.6

### Expected behavior

The Tray bounds `y` coordinate corresponds to the position of a tray icon on the external display, e.g. `-1080` when the resolution of external display is 1920x1080.

```
trayBounds: { x: 1275, y: -1080, width: 53, height: 22 }
```
### Actual behavior

`y` coordinate is `0`

```
trayBounds: { x: 1275, y: 0, width: 53, height: 22 }
```

When the external display is placed below the Retina display, then the `y` coordinate is equal to Retina resolution height.

### How to reproduce

* Connect secondary display, place is vertically above the Retina display in display arrangement preferences, or on one of the sides but slightly higher
* Create an app with a tray icon,
* Attach listener to tray clicks, get `tray.getBounds()` when tray is clicked
* Focus the top/bottom (other than Retina) screen, click the tray icon
* `y` should be equal to `0` only on the Retina display, same way as `x` corresponds to horizontal position, described in https://github.com/electron/electron/issues/3500

Probably related to https://github.com/electron/electron/issues/1847

```
// screen 0 (retina)
windowBounds: { x: 570, y: 218, width: 300, height: 420 }
trayBounds: { x: 1021, y: 0, width: 53, height: 22 }
activeDisplay: { id: 69731840,
  bounds: { x: 0, y: 0, width: 1440, height: 900 },
  workArea: { x: 50, y: 22, width: 1390, height: 878 },
  size: { width: 1440, height: 900 },
  workAreaSize: { width: 1390, height: 878 },
  scaleFactor: 2,
  rotation: 0,
  touchSupport: 'unknown' }

// screen 1 (external top, 1920x1080)
windowBounds: { x: 898, y: 26, width: 300, height: 420 }
trayBounds: { x: 1275, y: 0, width: 53, height: 22 }
activeDisplay: { id: 69731840,
  bounds: { x: 0, y: 0, width: 1440, height: 900 },
  workArea: { x: 50, y: 22, width: 1390, height: 878 },
  size: { width: 1440, height: 900 },
  workAreaSize: { width: 1390, height: 878 },
  scaleFactor: 2,
  rotation: 0,
  touchSupport: 'unknown' }
```

<img width="780" alt="screen shot 2018-01-25 at 20 50 02" src="https://user-images.githubusercontent.com/1029142/35409047-65798aa8-0211-11e8-95ac-8fa56f04e9ac.png">
<img width="780" alt="screen shot 2018-01-25 at 20 50 08" src="https://user-images.githubusercontent.com/1029142/35409049-675c4284-0211-11e8-9a14-122eebee2328.png">

This affects https://github.com/jsynowiec/airqmon/issues/14

**Comment by jsynowiec** [comment]
Any updates? There are a few apps out there affected by this bug.

**Comment by mdpetuum** [comment]
@jsynowiec I put up a PR for this - https://github.com/electron/electron/pull/13162

**Comment by MarshallOfSound** [comment]
This was fixed in the above PR
