### ISSUE TITLE
Missing license file in npm release

### ISSUE THREAD

**Issue by readme42** [electron/electron#11703]
When installing this library via npm, the license file is missing. This makes automated license generation complicated. Could you add the file to upcoming npm releases?

**Comment by codebytere** [comment]
@readme42  sure, i think we can do this! I'll try to get to it this week

**Comment by readme42** [comment]
That sounds great - thanks! 👍

**Comment by codebytere** [comment]
@readme42 PR up, will likely be merged soon!
