### ISSUE TITLE
Registering a global shortcut with a non present F key causes previously created global shortcuts to not trigger

### ISSUE THREAD

**Issue by Sheldan** [electron/electron#11702]
* Electron version:
1.7.11
* Operating system:
Fedora 27 with Linux 4.14.13
### Expected behavior

If a F key is not present on the keyboard, it should not influence the behavior of other keys.

### Actual behavior

I have a keyboard with F1-F12. According to the documentation, it is possible to define shortcuts for the F keys from F1 up to F24. If I define a shortcut with
`    electron.globalShortcut.register('F13', function(){
        electron.app.quit();
    })`

every valid shortcut handler added before will not trigger.
The following will work, but if you swap the to register calls, the `a` shortcut will not work.

`    electron.globalShortcut.register('F13', function(){
        electron.app.quit();
    })
    electron.globalShortcut.register('a', function(){
        electron.app.quit();
    })`

### How to reproduce

I [forked](https://github.com/Sheldan/electron-quick-start) the electron-quick-start and added the code triggering the issue in the main.js. If you swap the two global shortcuts, it will work for `a` at least.

It is in the master branch and can be started with `npm install` and `npm start` afterwards.

**Comment by codebytere** [comment]
This should be resolved by https://github.com/electron/electron/pull/15542.

**Comment by SupremeTechnopriest** [comment]
Looks like this has regressed.  Cant seem to bind global shortcuts for F13-F24.  Electron 26.2.4 on Ubuntu 22.04.
