### ISSUE TITLE
Github Alert:  "We found a potential security vulnerability in one of your dependencies."

### ISSUE THREAD

**Issue by manifestinteractive** [electron/electron#11713]
* Electron version: 1.8.1
* Operating system: MacOS v10.13.2

### Expected behavior

Not to received `Potential Security Vulnerability` on Github while having `electron` as dependency.

### Actual behavior

Github currently throws the following error when I access [My Electron Project](https://github.com/manifestinteractive/weather-bar-app) on Github:

```
We found a potential security vulnerability in one of your dependencies.
The electron dependency defined in package-lock.json has a known critical severity security vulnerability in version range >= 1.7.0,< 1.7.11 and should be updated.

Review vulnerable dependency

Only the owner of this repository can see this message.

Learn more about vulnerability alerts
```

#### Screenshot:

![screenshot 2018-01-24 at 1 12 06 am](https://user-images.githubusercontent.com/508411/35317206-abe66318-00a3-11e8-902f-30590ea3f1ba.png)

### How to reproduce

Upload any Electron project created with `electron >= 1.7.0` to Github where it is referenced in the `package-lock.json` file.

**Comment by MarshallOfSound** [comment]
The version range in the alert might be bugged, but the warning for your version is correct.  1.8.1 is affected, you need to update to 1.8.2-beta.4

**Comment by manifestinteractive** [comment]
I’ll give that a go, but isn’t `1.8.2-beta.4 >= 1.7.0`?

Curious what the actual security risk is too.  If it’s something super minor I can wait for an official release 1.8.2.

**Comment by MarshallOfSound** [comment]
See https://electronjs.org/blog/protocol-handler-fix

**Comment by ckerr** [comment]
@manifestinteractive 1.8.2 is coming very soon; however, I woudn't recommend waiting because the protocol handler issue is potentially severe.

**Comment by raminghaderi** [comment]
Try this command: 
npm i hoek

**Comment by channvvuthy** [comment]
Try this command and push it again:
npm i hoek and run npm audit

**Comment by MASHUD-CA** [comment]
facing same issue

**Comment by nicks9188** [comment]
Something similar : https://stackoverflow.com/questions/16073603/how-do-i-update-each-dependency-in-package-json-to-the-latest-version

**Comment by EnockBrown** [comment]
face the same issue

**Comment by SalmaQueen** [comment]
same here

**Comment by mylove-zqy** [comment]
same here

**Comment by bdmostafa** [comment]
same here

**Comment by cosky5** [comment]
Facing the same issue here, any help?

**Comment by blockchaindev91** [comment]
facing the same issue.
