### ISSUE TITLE
Error : Session can only be received when app is ready! at the time of uninstalling

### ISSUE THREAD

**Issue by ravisojitra** [electron/electron#11716]
I am trying to remove userdata folder when user uninstall app which is created at the time of installing application.
I am using this code inside --squirrel-uninstall:

```
session.defaultSession.clearStorageData({},function(){
   logger.log("....................... cleared storage data ...................");
})
spawnUpdate(['--removeShortcut', exeName]);
setTimeout(application.quit, 1000);
return true;
```
But when i uninstall my application, it gives me error that **"Session can only be recieved when app is ready!"**

These are my project dependencies : 
```
"devDependencies": {
    "build-electron-app": "github:j-f1/build-electron-app",
    "electron": "~1.7.8",
    "electron-builder": "^19.45.4",
    "electron-packager": "^9.1.0",
    "electron-rebuild": "^1.6.0",
    "electron-winstaller": "^2.6.3",
    "font-awesome": "^4.7.0"
  },
  "dependencies": {
    "angular-ez-plus": "^1.2.1",
    "auto-launch-patched": "^5.0.2",
    "bootstrap": "^3.3.7",
    "download": "^6.2.5",
    "electron-config": "^1.0.0",
    "electron-dl": "^1.10.0",
    "electron-is-dev": "^0.3.0",
    "electron-notify": "^0.1.0",
    "electron-online": "^1.0.0",
    "electron-squirrel-startup": "^1.0.0",
    "express": "^4.16.2",
    "first-run": "^1.2.0",
    "fs": "0.0.1-security",
    "jquery": "^3.2.1",
    "logger-electron": "^1.2.8",
    "nanobar": "^0.4.2",
    "node-notifier": "^5.1.2",
    "rimraf": "^2.6.2",
    "soap": "^0.23.0",
    "sqlite3": "^3.1.13"
  }
```

**Comment by codebytere** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by MarshallOfSound** [comment]
`session.defaultSession` can only be accessed after the `ready` event has been fired, you are trying to access it well before the app is ready hence the error message
