### ISSUE TITLE
npm and yarn both failing when installing electron

### ISSUE THREAD

**Issue by davidhenley** [electron/electron#11717]
* Electron version: 1.7.11
* Operating system: macOS

### Expected behavior

npm should finish building packages

### Actual behavior

**yarn**
```
Building fresh packages...
[1/1] ⠠ electron
[-/1] ⠠ waiting...
[-/1] ⠠ waiting...
[-/1] ⠠ waiting...
[-/1] ⠠ waiting...
```

**npm**
```
> electron@1.7.11 postinstall /Users/david/workspace/ElectronJS/test/node_modules/electron
> node install.js
```

Node version `8.9.3`
npm version `5.6.0`
yarn version `1.3.2`

Only happens when installing electron

### How to reproduce

`npm i electron` or `yarn add electron`

**Comment by davidhenley** [comment]
Issue closed. 

Downloading electron-v1.7.11-darwin-x64.zip is taking FOREVER for a 50MB file.

**Comment by Ziv-Barber** [comment]
Any fix for this issue? It still impossible to install electron
