### ISSUE TITLE
navigator.mediaDevices.enumerateDevices does not return a complete list of devices

### ISSUE THREAD

**Issue by webarchymeta** [electron/electron#11723]
* Electron version: tested 1.6.x, 1.7.x 1.8.x
* Operating system: Windows 10 (1709)

### Expected behavior

```
navigator.mediaDevices.enumerateDevices()
```
should return the same list of audio and video devices as what a Chrome browser (v63) does.

### Actual behavior

The actual audio device list obtained contains only a default input device, all other audio devices are missing.
There is no video input device (camera) listed.

### How to reproduce

Just call the said method in an Electron App and compare it to what one get from calling the same method inside Chrome browser (v63 or v64) inside a Windows 10 (1709) host and compare the results ...

**Comment by codebytere** [comment]
Running Chrome 63 and `master` on electron, i'm seeing an identical number of devices in both developer consoles. I also see a device with `kind: videoinput` listed in both consoles.

**Comment by webarchymeta** [comment]
Yes, you are right. The problem I found seems to be originated from a device filter in our system that is not related to the Electron ...
