### ISSUE TITLE
[BUG? / question] disable resize window.

### ISSUE THREAD

**Issue by Mlocik97-issues** [electron/electron#11736]
* Electron version: 1.6.15 (https://github.com/electron/electron/releases/tag/v1.6.15) & 1.7.10 (npm)
* Operating system: Windows 8.1

### Expected behavior

Not resize

### Actual behavior

It will resize

### How to reproduce

if I wrote to main.js to function createWindow() this code

```
win = new BrowserWindow({ frame: true })
win.setMenu(null)
win.maximaze()
win.setMaximizable(false)
win.setResizable(false)
```

user can't resize window by click to win_buttons [minimize, maximize and clsose window buttons I think], so it's ok, but he always can drag window like if he want move it, and it will resize it by drag and move.

if it's not bug, how I can disable resize by drag?

**Comment by MarshallOfSound** [comment]
@Mlocik97-issues I don't believe it is possible to disable aero (that's the thing that does window resizing based on dragging to hotspots on the screen).  That said I believe what you are trying to do can be achieved a few ways

#### Option 1 - Fullscreen

```js
win.setFullScreen(true)
win.setFullScreenable(false)
```

This will make your window fullscreen and unable to be resized or minimized

#### Option 2 - Custom window controls

```js
win = new BrowserWindow({ frame: false })
```

This will completely remove the window frame so users can't drag the window around

#### Option 3 - Auto maximize

```js
mainWindow.setMenu(null)
mainWindow.maximize()
mainWindow.setResizable(false)
mainWindow.on('unmaximize', () => mainWindow.maximize());
```

This will maximize the window as soon as it is unmaximized.  Most of the time this doesn't even appear to the user
