### ISSUE TITLE
Focus doesn't go to the right place when launching a webapp from Electron

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#11735]
* Electron version: 1.7.9
* Operating system: Windows 10

My webview points to a page that puts focus in the textfield when the `body` loads. When I start the app, I expect focus to go there when the dom has loaded. If I launch the app outside of Electron, it does just that. But when I launch it from Electron, focus does not go to the textfield.

### How to reproduce
I added these listeners to the renderer's index.js thinking it would work around the issue, but it did not:

    window.addEventListener("focus", () => { webview.focus(); });
    webview.addEventListener("dom-ready", () => { webview.focus(); });

I point my webview to test.html:
```
<body onload="fff()">
  <input id="abc" placeholder="abc" />  
  <script>
     function fff() {
        document.getElementById("abc").focus();
     }
  </script>
</body>
```

---
**Update**: I see the same issue when replacing the `webview` with a `BrowserView`. I work around this by adding a `dom-ready` handler to the BrowserView's `webContents`, which explicitly focuses it:

    view.webContents.focus();

**Comment by MarshallOfSound** [comment]
@pushkin- This is something I've had to mess with before and I this is apparently what I came up with the focus a webview.

```js
const focusWebview = () => {
  document.querySelector('webview::shadow object').focus();
};
```

**Comment by pushkin-** [comment]
@MarshallOfSound Brilliant, thanks!

**Comment by pushkin-** [comment]
As of Electron 3, `webview.focus()` works now as a workaround. The main issue persists.

**Comment by pushkin-** [comment]
@sofianguy I see the same issue in Electron 5.0.7. Could you add the label to this issue? Thanks

**Comment by pushkin-** [comment]
This is also an issue in Electron 7.1.2

**Comment by pushkin-** [comment]
Still a bug in Electron 8.0.1 using BrowserView. I have to work around by adding a `dom-ready` handler on the BrowserView's webcontents and doing `view.webContents.focus()`. I presume this is also an issue with webview, but haven't tested it.

**Comment by pushkin-** [comment]
I guess I'm not quite sure what the Electron fix should be now that you can have multiple BrowserView's in a window. Which BrowserView should get the focus? Maybe when adding the BrowserView to the BrowserWindow, we can specify which should get activated on focus? and then subsequent window focuses will forward focus to the BrowserView that was last focused?

**Comment by pushkin-** [comment]
Still a problem in Electron 10.1.2 with BrowserViews. I can post a better repro example with BrowserViews if one is needed

**Comment by pushkin-** [comment]
can't seem to repro with BrowserViews in Electron 21
