### ISSUE TITLE
Crash when typing into devtools electron-1.8.2-beta.4

### ISSUE THREAD

**Issue by seanzer** [electron/electron#11732]
* Electron version: electron-1.8.2-beta.4
* Operating system: Windows 10 64-bit

### Expected behavior

No crash

### Actual behavior

Crash

### How to reproduce

```
git clone https://github.com/electron/electron-quick-start
npm i -g electron@1.8.2-beta.4
electron .
```
Then, open dev tools (ctrl+shift+i)
Type any letter: 'a' (for example)

Creating a new issue since #11375 was closed

**Comment by felixrieseberg** [comment]
There was just a communication issue - 1.8.2-beta.4 didn't ship with the fix applied in https://github.com/electron/electron/pull/11673, but the bug is still technically fixed.

Apologies, we all know that it's annoying.

**Comment by seanzer** [comment]
are there any ways to get around the crash?

**Comment by Hammster** [comment]
@seanzer unless you compile the master branch which includes #11673, all you can do is to use electron 1.8.2-beta.2 or 1.7.11
