### ISSUE TITLE
Transparent BrowserWindows remain invisible

### ISSUE THREAD

**Issue by felixrieseberg** [electron/electron#11733]
We're seeing an issue involving transparent BrowserWindows on Windows 10 remaining completely invisible. I'm investigating the issue and will attempt to fix it, but I'm reporting it here to ensure that other people seeing similar behavior can pipe up, too.

* Electron version: 1.8.2-beta.4
* Operating system: Windows 10, build 16299.192

Logged to console:

```
[8484:0125/122109.900:ERROR:gpu_child_thread.cc(174)] Exiting GPU process due to errors during initialization
[7496:0125/122110.278:ERROR:gpu_child_thread.cc(174)] Exiting GPU process due to errors during initialization
```

### Expected behavior

Window not invisible

### Actual behavior

Window invisible 

### How to reproduce

Clear reproduction steps are somewhat unclear, but when the issue is reproducible on a system, it's reproducible 100% of the time.

To reproduce, create a window with `transparent: true` and observe that the window remains invisible.

**Comment by felixrieseberg** [comment]
Closing: Seems like it's caused by a semi-successful `app.disableHardwareAcceleration` call.

**Comment by CydeSwype** [comment]
we're seeing this same issue intermittently on some win10 systems, but we are not invoking app.disableHardwareAcceleration.  any other possible culprits?

**Comment by CydeSwype** [comment]
this discussion is likely related: https://github.com/electron/electron/issues/2170
