### ISSUE TITLE
Reproducable runaway memory leak using window.alert()

### ISSUE THREAD

**Issue by Thomas101** [electron/electron#11739]
* Electron version: 1.7, 1.8, 2.0.16, 3.0.14, 3.1.0, 4.0.1
* Operating system: macOS, win32, linux

### Expected behavior
Using `window.alert()` shouldn't have any significant impact on memory consumption

### Actual behavior
`window.alert()` can cause a runaway memory leak, eventually consuming the entire memory on the machine (we've seen up to 77GB). Eventually the leak brings the host machine down.

It's particularly pronounced when there are multiple `webContents` and lots of ipc communication. The more ipc communication or the larger the payload in the ipc messages the faster the leak grows. Under some instances using the native `window.alert()` (via an attached `iframe`) does not produce the behaviour.

All memory tests were done on macOS with electron 1.7.11 but the same behaviour can be seen cross platform and on 1.8

See the attached quick-start to reproduce. There are two scenarios where the memory leak occurs:

#### Scenario 1
- Two browser windows
- Both sending messages over ipc
- One window presents an alert

##### Tests
- **Electron window.alert()** Memory consumption grew from 259.0MB to 322.2MB over a minute.
- **Native window.alert()** Memory consumption dropped from 267.6MB to 256MB over a minute

#### Scenario 2
- One browser window
- Two embedded webviews
- Webviews sending messages over ipc
- Main window, or webview presents an alert

##### Tests
- **Main window, Electron window.alert()** Memory consumption grew from 308.7MB to 462.8MB over a minute.
- **Main window, Native window.alert()** Memory consumption grew from 338.9MB to 476.2MB over a minute
- **Webview, Electron window.alert()** Memory consumption grew from 292.7MB to 331.4MB over a minute
- **Webview, Native window.alert()** Memory consumption fell from 301.6MB to 268.4MB over a minute
- **Webview, Native window.alert()** Memory consumption grew from 290.1MB to 291.3MB over two minutes

*Ran a second native webview test over two minutes to ensure the memory wasn't dipping and then growing thereafter, but it stabilized*

### How to reproduce
```bash
git clone https://github.com/wavebox/electron-quick-start.git
cd electron-quick-start
git checkout runaway_memory_leak
npm install
npm start
```

#### Scenario 1
The checked in version will run this out the box. Click `Send Electron` and `Send Native` to test.

#### Scenario 2
Change lines 85 and 86 in `main.js`
```diff
- app.on('ready', createWindow)
- //app.on('ready', createWebviewWindow)

+ //app.on('ready', createWindow)
+ app.on('ready', createWebviewWindow)
```
Click `Send Electron` and `Send Native` in the top window, or the same buttons in the webview (contained within a red box)

### Further
The root of the issue looks to be down to the use that `window.alert()` makes of `ipcRenderer.sendSync`. Once this fires, the emitted ipc events in different webContents start to queue up and eat memory. Once the alert is dismissed the CPU usage spikes and memory consumption returns to normal.

The native `window.alert()` doesn't hold up the js thread in the same way that `sendSync` does which is probably why we don't see the queue up of memory. The exception to this is when a webContents with a child webviews fires an alert. The JS thread is halted and ipcMessages queue up again.

For Scenario 1 is there any way to implement `window.alert()` from a browser window without halting the main thread? For Scenario 2 should the child webviews be halted to stop the build up of ipc messages?

**Comment by MarshallOfSound** [comment]
I believe this will be coincidentally fixed by https://github.com/electron/electron/pull/11613

I removed the JS (sync IPC) implementation of `window.alert` and `window.confirm`

**Comment by Thomas101** [comment]
That's awesome! I'll give it a try and see if I can reproduce the bug with it

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by Thomas101** [comment]
@sofianguy I can confirm this still affects electron 2, 3 and 4. I've updated the original issue to reflect this

**Comment by miniak** [comment]
Can you reproduce it with Electron 5 or 6?

**Comment by dickyw71** [comment]
I repeated the tests that @Thomas101 did in his original issue report. First with Electron 1.7 and then with Electron 6.0.11.
### My setup
- Operating system: macOS Mojave 10.14.6 
- Node: v10.15.3
- NPM: v6.4.1
- I used macOS Activity Monitor to track the Electron process memory usage during testing

### What I did
1. I used the **"How to reproduce'** steps from @Thomas101 original issue comment.
2. Reproduced the issue on my system with the example app using Electron 1.7. 
3. Changed the Electron version in the example app package.json as shown below.
```   
   "license": "CC0-1.0",
   "devDependencies": {
-    "electron": "~1.7.8"
+    "electron": "^6.0.11"
   }
 }
```
4. Reproduced the issue on my system with the example app using Electron 6.0.11. 

## Test results with Electron 6.0.11
### Scenario 1 
- Electron window.alert() Memory consumption grew from 87.6MB to 163.3MB over a minute.
- Native window.alert() Memory consumption dropped from 108.1MB to 95.5MB over a minute

### Scenario 2
- Main window, Electron window.alert() Memory consumption grew from 85.0MB to 260.5MB over a minute.
- Main window, Native window.alert() Memory consumption grew from 114.9MB to 115.8MB over a minute
- Webview, Electron window.alert() Memory consumption grew from 112.7MB to 173.2MB over a minute
- Webview, Native window.alert() Memory consumption grew from 114.4MB to 114.6MB over a minute

The results show that the memory leak issue is also present under Electron 6.0.11 when the Electron window.alert function is used.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
