### ISSUE TITLE
Electron crash when typing in devtools console

### ISSUE THREAD

**Issue by BOOMER74** [electron/electron#11738]
* Electron version: 1.8.2 beta 3 and 4 (ia32 and x64)
* Operating system: Windows 10 and Arch Linux

### Expected behavior

Devtools work.

### Actual behavior

Electron crash.

### How to reproduce

Start electron, open devtools and type anything in console. Electron crash with error (0xC0000005). Unlike https://github.com/electron/electron/issues/10188 no any log was created.

**Comment by codebytere** [comment]
Hi yes we're aware of this, PRs are currently up and this will be fixed shortly.

**Comment by brenca** [comment]
Duplicate of #11375
