### ISSUE TITLE
Electron's chromium is trusting different CAs then Electron's NodeJS

### ISSUE THREAD

**Issue by sgreiner** [electron/electron#11741]
* Electron version: ^1.8.1
* Operating system: Windows 10 (1709)

My Windows has imported the Root CA of our company.
My localhost website is using a certificate signed by that CA.
In the electron app we open that website. 
In the website we call a function within the website's code which invokes a function in the electron app, which the website's JS context has access to because of the preload.js.

### Expected behavior
The website should load because windows trusts the CA and Chromium uses the Windows Cert Store.
The request() inside the preload.js function should also work for the same reason.

### Actual behavior
The website loads as expected in chromium.
The request in the node context of electron fails because of an "invalid certificate"

### How to reproduce
- Import a Custom CA to Windows Cert Store
- Use a cert signed by that Custom CA on a website
- Open the website with electron
- call a function inside the node context of electron to request the same website

###
So the question is why is electron using two different Trust Stores?
Chromium is trusting different CAs than NodeJS

**Comment by yarcub** [comment]
@sgreiner are you using electron's `net`[1] module on the node process instead [`http(s)`](https://nodejs.org/api/https.html) module?

[1] https://github.com/electron/electron/blob/master/docs/api/net.md

> The net module is a client-side API for issuing HTTP(S) requests. It is similar to the HTTP and HTTPS modules of Node.js but uses Chromium's native networking library instead of the Node.js implementation

**Comment by sgreiner** [comment]
@yarcub sry for the late reply. We are using the [http(s)](https://nodejs.org/api/https.html) module in the node process.

Summerized:
When the Electron App is started:
```
mainWindow = new BrowserWindow({
  webPreferences: {
    devTools: true,
    nodeIntegration: false,
    preload: path.resolve(path.join(__dirname, 'preload.js'))
  }
});
mainWindow.loadUrl(someLocalhostUrl); // this connection is signed by our CA (inside Trusted Root CA store) and this call will work!
```
preload.js makes a nodejs class available in the webpage.
```
...
window.CustomClass = new CustomClass();
...
```

someLocalhostUrl contains javascript accessing a method from our CustomClass:
```
window.CustomClass.loadByUrl(onotherLocalhostUrl) // this call fails because of "invalid certificate". But it should not fail because it is the exact same page then the one above.
```
CustomClass.loadByUrl is using the lib https://github.com/request/request which is using https.Agent

So my conclusion is that the "BrowserWindow.loadUrl()" checks the certificate like a normally installed chromium would do, and that the node.js is using https://github.com/nodejs/node/blob/master/src/node_root_certs.h (looks like the Mozilla curated ca list)

So the question is: is it possible for electron to work with the same trust source on both systems or do we, as app developers, have the responsibility to add missing CAs?

We could do that by modifying https.globalAgent.options.ca which is described here:
https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options

**Comment by nornagon** [comment]
Can you check if this is still happening in the Electron 4.0.0 beta?

**Comment by mbaeten** [comment]
We have similar problems (both on windows and linux) using trusted self signed certs with riot.im. It's not working unless we use --ignore-certificate-errors.

**Comment by adammeyer** [comment]
@nornagon Yes, this still happens in Electron 4.

I'm in the same boat.  Electron's net works great, but for some processes, I use a forked process and Electron's net isn't available.  So I use the https module.  And https has its own set of trusted certs, doesn't use the system certs.

I saw that node as an "--use-openssl-ca" switch, but that's unsupported in Electron. (https://electronjs.org/docs/api/environment-variables) . Not sure if that would even resolve the issue.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by alex1701c** [comment]
I still have the same issue in Electron 28. https://github.com/electron/electron/issues/10257#issuecomment-346310333 is a workaround for respecting the NODE_EXTRA_CA_CERTS flag, but that requires a separate flag to be set.
