### ISSUE TITLE
CrashReporter.getLastCrashReport() does not return latest

### ISSUE THREAD

**Issue by timfish** [electron/electron#11749]
Electron: 1.7.11
Platform: Windows

```JSON.stringify(require('electron').remote.crashReporter.getLastCrashReport())```
Returns:
```json
{
  "date":"2018-01-27T10:48:47.000Z",
  "id":"a1f8a8c4-e6d3-4729-a126-aadcef61d9da"
}
```
```JSON.stringify(require('electron').remote.crashReporter.getUploadedReports())```
Returns:
```json
[
  {
    "date": "2018-01-27T10:48:47.000Z",
    "id": "a1f8a8c4-e6d3-4729-a126-aadcef61d9da"
  },
  {
    "date": "2018-01-27T11:11:54.000Z",
    "id": "3d8d2e06-d186-4cc9-b9b3-396673d68902"
  },
  {
    "date": "2018-01-27T11:12:28.000Z",
    "id": "24668c94-44e0-4b58-901c-32a6ec950d1b"
  },
  {
    "date": "2018-01-27T11:38:17.000Z",
    "id": "1d99e1cc-9a54-4dff-bbae-9c37a5566592"
  },
  {
    "date": "2018-01-27T11:50:30.000Z",
    "id": "9b222337-806c-4b53-bab1-aa9e84cbfe37"
  }
]
```

The last error report by timestamp is clearly `9b222337-806c-4b53-bab1-aa9e84cbfe37`

Looking at the code, [its expecting the first crash](https://github.com/electron/electron/blob/63c91e7dd3764499d846f7e0b384d82d1da2bbc5/lib/common/api/crash-reporter.js#L61) to be the latest.

**Comment by alexeykuzmin** [comment]
@timfish This also happens in master, right? Not only in 1.7.x?

**Comment by timfish** [comment]
From what I can see, this is an issue in master and everything which has been released in the last few years.

**Comment by alexeykuzmin** [comment]
@timfish thanks!
