### ISSUE TITLE
Enable DevTools Protocol 1.3

### ISSUE THREAD

**Issue by wellbeck190** [electron/electron#11745]
My app need to use DevTools Protocol 1.3.
I know it is tagged at Chrome 64, but chrome version of electronjs is 59.
On chrome, I can enable enable-devtools-experiments in chrome://flags page.
How to enable it for electronjs (debugger of BrowserWindow or WebView)

Help me! Thanks.

**Comment by MarshallOfSound** [comment]
You can use flag switches with the [`app.commandLine`](https://github.com/electron/electron/blob/master/docs/api/app.md#appcommandlineappendswitchswitch-value) apis
