### ISSUE TITLE
WARNING: Textured window <AtomNSWindow: 0x7f9d8177e360> is getting an implicitly transparent titlebar

### ISSUE THREAD

**Issue by fabriciolelis** [electron/electron#11743]
* Electron version: 
     1.7.6
* Operating system: 
   MacOS

### Expected behavior
 Run electron without this warning

Is it possible disable electron warnings? Or redirect this warning to a file?

**Comment by 0x00A** [comment]
The common use case would be to build your app (ie `electron-builder`). Then you wouldn't see output like this. But if you have some other kind of use case, where your users would specifically run electron (as opposed to a built version of it), you could do something like `electron ./path/to/file 1>/dev/null 2>&1 &`.

**Comment by MarshallOfSound** [comment]
> Is it possible disable electron warnings?

If you update your electron version this has been fixed on more recent releases (`1.8.x` I believe)

**Comment by fabriciolelis** [comment]
I used electron version 1.8.2-beta4 and this message still appears.

**Comment by mhamdan95** [comment]
@fabriciolelis @MarshallOfSound 
Hello I have the same problem 
WARNING: Textured window <AtomNSWindow: 0x7fabdbc36bb0>
 And I didn't find the solution. Do you still have this problem? if yes, Will you be able please to telle what I have to do?

Thanks

**Comment by blogscot** [comment]
This error is also reported by https://github.com/electron/electron/issues/11150

**Comment by jetlej** [comment]
+1

**Comment by philcockfield** [comment]
+1

**Comment by snatvb** [comment]
+1

**Comment by GertsenYuan** [comment]
+1

**Comment by Alaa-mansour** [comment]
try this  
mainWindow.loadFile('index.html')
 instead of  this 
MainWindow.loadURL('index.html');
