### ISSUE TITLE
Menu roles do not follow standard behavior for enabled/disabled state and cannot be overridden.

### ISSUE THREAD

**Issue by yourhead** [electron/electron#11742]
* Electron version: v1.7.10
* Operating system: macOS v10.13.2

### Expected behavior

On macOS when nothing is selected in the focused window some standard menu items in the Edit menu should be disabled: Cut, Copy, and Delete

Similarly, when there is nowhere to paste anything the Paste menu items should be disabled.

You can see this behavior using the built in macOS TextEdit app.  When something is selected Cut and Copy are enabled. Otherwise they are disabled.

### Actual behavior

All menu items in the Edit menu are always enabled when using the electron roles for Cut, Copy and Delete.

### How to reproduce

The issue is immediately visible in the standard electron quick start linked from the electron docs.

  $ git clone https://github.com/electron/electron-quick-start
  $ npm install
  $ npm start || electron .

The main window opens with neither anything selected nor anywhere to paste anything.  The expected behavior is the Cut, Copy, and Paste would all be disabled.  However all Edit menu items are enabled -- which is odd since using them has no function.

**Comment by MarshallOfSound** [comment]
Pulling #12638 into this issue.  Any menu item that would not perform an operation should be disabled, the example in that issue being the `togglefullscreen` role 👍

**Comment by MarshallOfSound** [comment]
Other examples would be `close` should be disabled if no window is currently open

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by yourhead** [comment]
Sorry, I'm not working on Electron projects at the moment so won't be able to work on this. The test I provided was truly trivial tho. Basically start it up and there you go. Give it a try.  😃

**Comment by nishat-a** [comment]
@sofianguy We are seeing this issue in Electron version 4.0.0.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
