### ISSUE TITLE
Issue with using WEBRTC (webtorrent integration)

### ISSUE THREAD

**Issue by aszokalski** [electron/electron#11753]
* Electron version: Electron v1.7.11
* Operating system: OSX

### Expected behavior
I was expecting that if I copy the code working with node.js to electron it would work correctly but it didn't.

### Actual behavior
I tried to run regular webtorrent package which has Webrtc support for browsers (and electron is a browser). Webtorrent has built in function for checking if WebRTC works and after i run it it returns false(nothing works). So I downloaded webtorrent-hybrid which enables webrtc support in node.js via [electron-webrtc](https://github.com/mappum/electron-webrtc). In node.js it worked but in electron it shows this popup.
`Uncaught Exception: TypeError: Bad argument at ChildProcess.spawn (internal/child_process.js:294:26) at Object.exports.spawn (child_process.js:390:9) at spawn (/Users/adamszokalski/github/bitnet-app/node_modules/cross-spawn/index.js:17:18) at Daemon._startElectron (/Users/adamszokalski/github/bitnet-app/node_modules/electron-eval/lib/index.js:169:20) at new Daemon (/Users/adamszokalski/github/bitnet-app/node_modules/electron-eval/lib/index.js:60:13) at module.exports (/Users/adamszokalski/github/bitnet-app/node_modules/electron-eval/lib/index.js:25:10) at module.exports (/Users/adamszokalski/github/bitnet-app/node_modules/electron-webrtc/index.js:5:16) at Object.global.WRTC [as wrtc] (/Users/adamszokalski/github/bitnet-app/node_modules/webtorrent-hybrid/lib/global.js:13:14) at new Client (/Users/adamszokalski/github/bitnet-app/node_modules/bittorrent-tracker/client.js:70:55) at Discovery._createTracker (/Users/adamszokalski/github/bitnet-app/node_modules/torrent-discovery/index.js:161:17)`

How to properly use webrtc with electron and how to integrate it with webtorrent?

[link to my webtorrent issue](https://github.com/webtorrent/webtorrent/issues/1276)

**Comment by MarshallOfSound** [comment]
This issue appears to be due to error-producing code in a non-electron package.  You should raise an issue with the appropriate repository for the webtorrent package you are using.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
