### ISSUE TITLE
"CommandOrControl+Plus" accelerator appears in menu as "Shift Command =" instead of "Control +" on Linux/Windows

### ISSUE THREAD

**Issue by akashnimare** [electron/electron#11752]
* Electron version: 1.7.10
* Operating system: Linux/Windows

### Expected behavior

`CommandOrControl+Plus` accelerator should appear and work as `Control+`
### Actual behavior

`CommandOrControl+Plus` accelerator appear and work as `Control+Shift+Plus`

**Comment by MarshallOfSound** [comment]
Merging into https://github.com/electron/electron/issues/6731
