### ISSUE TITLE
install electron with Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/electron/electron-tmp-download-4860-1517066058438'

### ISSUE THREAD

**Issue by wan-ghuan** [electron/electron#11755]
```
node -v
v8.9.4
```
```
npm -v
5.6.0
```

```
sudo npm install electron -g
/usr/bin/electron -> /usr/lib/node_modules/electron/cli.js

> electron@1.7.11 postinstall /usr/lib/node_modules/electron
> node install.js

/usr/lib/node_modules/electron/install.js:48
  throw err
  ^

Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/electron/electron-tmp-download-4860-1517066058438'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.7.11 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.7.11 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by MarshallOfSound** [comment]
You need to set the permissions of `/usr/lib/node_modules` to be writable by your user.

For more info on these NPM errors please see: [Troubleshooting Installation](https://github.com/electron/electron/blob/8a4c76d6558cffa53400e54317f0f9b1da22f7ef/docs/tutorial/installation.md#troubleshooting)

**Comment by thangntt** [comment]
npm install -g electron --unsafe-perm=true --allow-root

**Comment by obendesmond** [comment]
@wan-ghuan try this
sudo npm install -g electron --unsafe-perm=true.

Hope that helped

**Comment by pawanraocse** [comment]
sudo npm install -g electron --unsafe-perm=true --allow-root
This helped to solve the issue, thanks

**Comment by jesobreira** [comment]
I still have this issue and the command posted by @obendesmond also worked.
What I find interesting is that I have had that issue on my Ubuntu 18.04 notebook, my Macbook Pro and two newly-created Ubuntu AWS instances, completely different environments, which makes me think a huge portion of the users may be facing this issue as well. Obviously I may be wrong, but here I leave the question: isn't the portion of the environments where the unsafe-perm switcher too expressive enough to make a point on the documentation about it (to save new users from some Googling)? Or actually the environments where this is required are inexpressive (and I'm just out of luck)?

**Comment by alvaromoli** [comment]
npm install -g electron --unsafe-perm=true --allow-root 



> npm install -g electron --unsafe-perm=true --allow-root

It worked! Thanks!

**Comment by aniruddhashevle** [comment]
It works for the 1st time only. After again reopening the app, it still shows the error EACCES: permission denied!

**Comment by jewel-rana** [comment]
> You need to set the permissions of `/usr/lib/node_modules` to be writable by your user.
> 
> For more info on these NPM errors please see: [Troubleshooting Installation](https://github.com/electron/electron/blob/8a4c76d6558cffa53400e54317f0f9b1da22f7ef/docs/tutorial/installation.md#troubleshooting)

Thats worked for me

**Comment by dps910** [comment]
> npm install -g electron --unsafe-perm=true --allow-root

thank you! This worked :smile:

**Comment by extremepayne** [comment]
On my Debian stretch Chromebook subsystem-thingy, I had the same issue; solved via `sudo npm install electron -g --unsafe-perm=true --alow-root`. I totally agree with @jesobreira this should go in the docs. If you need more evidence of other users facing similar issues, look no further than #10362 and https://github.com/npm/npm/issues/17268 (some comments on the second link have over 70 +1s). (In fact, there's an absolute plethora of people unable to install version 7+, but many are facing different issues.) I'll try and figure out where it should go and then open a PR.

**Comment by itsmyCareer** [comment]
> npm install -g electron --unsafe-perm=true --allow-root

This problem is solved, too! THX :)

**Comment by chiglish** [comment]
> electron

it worked.THX

**Comment by chiglish** [comment]
> @wan-ghuan try this
> sudo npm install -g electron --unsafe-perm=true.
> 
> Hope that helped

It worked .thx

**Comment by jimbo8098** [comment]
unsafe-perm worked for me too. I've never touched that directory myself, only through apt so I'm a little confused. Electron was also already there previously, I needed to reinstall it following an attempt to install bue-devtools.

**Comment by Marcosul** [comment]
for me needed sudo

$ sudo npm install -g electron --unsafe-perm=true --allow-root
