### ISSUE TITLE
alert re-enable maximizable even if set to false

### ISSUE THREAD

**Issue by pinkladywithcoco** [electron/electron#11756]
# Development environment:

I’m using Electron version: **1.7.11**

on the following operating systems:

**macOS Sierra version 10.12.6**

**64-bit Windows 10**

# Expected behaviour:

The maximize button get disabled and stays disabled until we enable it again ourself.

# Actual behaviour:
The maximize button get disabled, but re-enabled itself if some alert get fired.

# How to reproduce:
If i create a window like this:

`win = new BrowserWindow({ title: "My App", backgroundColor:'#FF0000', maximizable:false, width: 400, height: 200, resizable: false})
`

The window maximize button get disabled as wanted, but if we active the alert function inside 

the **index.html** file by putting `<script> alert("test"); </script>` inside the file then the maximize button get enabled again and we can use it again. 

The maximize should stay disabled. This must be a bug happening on both platform. I Have not tested on Linux.

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by pinkladywithcoco** [comment]
Hi! i have updated my bug report to include the steps :-)

**Comment by nikita-graf** [comment]
Reproduceable in `electron@1.8.2` on macOS 10.13.3.

**Comment by enuoCM** [comment]
Hi, is any update on this issue? Thanks.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by RoderickQiu** [comment]
Hey I just found out that this issue is still here, with 7.1.14, on macOS 10.14.3.
Any help here?
@sofianguy
