### ISSUE TITLE
blinking effect happening to parent window when creating a child modal window and closing it

### ISSUE THREAD

**Issue by skoorupa** [electron/electron#11762]
* Electron version: v.1.8.2.beta.4
* Operating system: Windows 10

When I create a child window that's modal and then close it, the parent window loses its focus and gets it again. It creates blinking effect when there's an other window behind our program.

Code:
```
mainwin = new BrowserWindow({width: 885, height: 600, resizable: false})
  secwin = new BrowserWindow({parent: mainwin, modal: true, width: 400, height: 300, resizable: false})

  mainwin.loadURL(url.format({
    pathname: path.join(__dirname, 'index.html'),
    protocol: 'file:',
    slashes: true
  }))

  secwin.loadURL(url.format({
    pathname: path.join(__dirname, 'secwin.html'),
    protocol: 'file:',
    slashes: true
  }))

```

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
