### ISSUE TITLE
`TouchBarButton` doesn't update when inside a `TouchBarGroup`

### ISSUE THREAD

**Issue by lukechilds** [electron/electron#11761]
* Electron version: v1.7.11
* Operating system: macOS

### Expected behavior

Changing `TouchBarButton` properties should immediately update the button on the touch bar.

### Actual behavior

Changing `TouchBarButton` properties has no effect when the `TouchBarButton` is inside a `TouchBarGroup`.

### How to reproduce

```js
const updatingButton = new TouchBarButton({'label': 'change'});
setInterval(() => updatingButton.label = '' + Math.random(), 1000);

// Button label updates every second
const touchBar = new TouchBar([updatingButton]);

// Button label never updates
const touchBar = new TouchBar([new TouchBarGroup({items: [updatingButton]})]);

**Comment by lukechilds** [comment]
I can provide a clone-able gist for this later tonight.

**Comment by MarshallOfSound** [comment]
Can you try on `1.8.2-beta.4`?  This sounds similar to an issue that has already been fixed

**Comment by MarshallOfSound** [comment]
Refs: https://github.com/electron/electron/pull/9028

Looks like that fix only handles popovers not groups. Note to self, we should change `_popovers` to `_parents` to generify nested TB logic

**Comment by lukechilds** [comment]
Issue also occurs on `TouchBarScrubber` although interestingly sometimes the button appears to update when it's off canvas. When I drag the button back into view it stops updating again.

So are you aware of what's causing this then or do you still want a repro?

**Comment by lukechilds** [comment]
And to confirm, tried against `v1.8.2-beta.4` and I'm getting the same issue.

**Comment by MarshallOfSound** [comment]
`TouchBarScrubber` is a bit weird in the sense that it doesn't have a child touch bar, rather a set of "items".  You can make the scrubber update two ways.

```js
// Option 1
scrubber.items = scrubber.items;

// Option 2
scrubber.emit('change', scrubber);
```

**Comment by lukechilds** [comment]
Would there be a way to hook into `TouchBarScrubber` items updates and then automatically do `scrubber.emit('change', scrubber);` on the Electron side?

**Comment by MarshallOfSound** [comment]
@lukechilds We would effectively have to proxy all changes to the items array.  (Pushing, slicing, popping and individual item prop updates).  The API would have to dramatically change for this to be possible.  That said this is something I'm open to because the `TouchBar` is marked as experimental so we can change the API if we want.

**Comment by lukechilds** [comment]
Hmmn, after trying the solution I'm not sure it's the best way forward.

I've tried manually setting `scrubber.items` and also emitting the `'change'` event, however both of these reset the position of the scrubber.

Is this a limitation of the macOS touch bar API or just the Electron implementation?

It's quite confusing if the user has moved the scrubber to select something off the screen, then the scrubber randomly jumps back to the original position when an icon updates.

**Comment by lukechilds** [comment]
Does #11812 solve the issue of the touchbar scrubber jumping to the start position on update or is that a macOS limitation?
