### ISSUE TITLE
Open DevTools, click on any key in the console, the entire application crashes

### ISSUE THREAD

**Issue by WangMl** [electron/electron#11764]
* Electron version: v1.8.2-beta.3
* Operating system: window7

### Actual behavior
Open DevTools, click on any key in the console, the entire application crashes

####Scenario Restore
1. Execute /script/build.py No error occurred. 
2. After deployment, find the electron.exe in out and open the electron through the command line. 3. Open DevTools, click on any key in the console, the entire application crashes.

**Comment by brenca** [comment]
Closing as a duplicate of #11375
