### ISSUE TITLE
hardware acceleration - full hd video lagging 

### ISSUE THREAD

**Issue by konraddysput** [electron/electron#11765]
Hello,

I have created an application that can play multimedia files like videos. Lets assume that in my case all video extensions are supported. When user want to use a full hd video my application starts lagging. I use video tag in my HTML file. Video is on my local drive. The CPU is used in almost 100%, GPU is not used.

* Electron version: 1.7.9
* Operating system: Linux

### Expected behaviour:
* Full HD video not lagging  

### Actual behaviour:
* Video lagging 

### How to reproduce? 
* play ful hd video in any electron application

### Edit
Changed Operation system to Linux. I didn't check it on MAC. On Windows it works fine.

**Comment by nitsakh** [comment]
Looks related to #6864.

**Comment by konraddysput** [comment]
This issue isn't closed. The problem with chromium in Linux still exists. I know this is a problem with chromium, but is there any fan made electron build for Linux with enabled hardware acceleration on chromium? Or maybe someone know where is an instruction how to build electron with chromium for Linux with enabled hardware acceleration ?

**Comment by kingio** [comment]
1. No there is no alternative electron build with the patch.
2. There is no tutorial to build electron for linux with hardware acceleration and you would probably not meet the requirements (just check chromium ones:  https://chromium.googlesource.com/chromium/src/+/master/docs/linux_build_instructions.md#system-requirements)

@nitsakh pointed to the issue where another user linked the required patch: https://github.com/saiarcot895/chromium-ubuntu-build/commit/f8bd4a884894c47f7bce04c7b4d25a714c7a2faa#diff-6d883d9541ff7f20f76cd8619af284b3

This issue will probably get ignored as happens on linux, not on Windows :(

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by konraddysput** [comment]
hi @sofianguy. I still have the same situation with 3.0.9 :(

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by konraddysput** [comment]
Hi. 5+

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by pietrovismara** [comment]
What a joke.
