### ISSUE TITLE
-webkit-app-region: no-drag inconsistency on stacked elements

### ISSUE THREAD

**Issue by digitalnature** [electron/electron#11768]
* Electron version: 1.8.1
* Operating system: Windows 7 x64

### Expected behavior

mouse events should work normally on fixed/absolute-positioned elements.

### Actual behavior

-webkit-app-region: drag overrides mouse events on elements positioned above and z-index doesn't have any effect

### How to reproduce

HTML:
```

<nav></nav>
<header></header>

```
CSS:

```
nav{
  position: absolute;
  z-index: 100;
  right: 0;
  top: 0;
  width: 200px;
  height: 40px;
  background: blue;
  -webkit-app-region: no-drag;
}

nav:hover{
  background: green;
}

header{
  position: relative;
  z-index: 5;
  width: 100%;
  height: 40px;
  background: red;
  -webkit-app-region: drag;
}

```

Moving the mouse over the blue nav doesn't turn it green because the header drag is stealing all mouse events...

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by digitalnature** [comment]
Well, the referenced issue #13588 is tagged as 2.0.x and duplicate of this, so it looks like it's still present...

**Comment by MarshallOfSound** [comment]
This is expected behavior, `-webkit-app-region: drag` is converted to X / Y / width / height (a rectangle) behind the scenes and is not contextually aware of what is on top of it.  Imagine that `-webkit-app-region: drag` is calculated assuming an `Infinite` z-index on the element.
