### ISSUE TITLE
Windows 10 Fluent Design / Acrylic material

### ISSUE THREAD

**Issue by dreszczyk** [electron/electron#11771]
Is there any chance that _electron_ can get window background transparency with blur just like macOS vibrancy?

Fall Creators update gave us the *acrylic material* ability.

![image](https://user-images.githubusercontent.com/5095527/35584263-c5fd9a22-05f4-11e8-94c8-fe518349e930.png)

**Comment by TiagoDanin** [comment]
I use the [electron-vibrancy](https://github.com/arkenthera/electron-vibrancy).

**Comment by dreszczyk** [comment]
> Recommend use the electron-vibrancy.
Well, it's fine but:
- it's not utilizing the build in mechanism
- it's not compatible with the newest version of electron

**Comment by codebytere** [comment]
I'd recommend opening a PR to https://github.com/arkenthera/electron-vibrancy or posting an issue there, as this is most likely best done on the client-side for this case.

**Comment by dreszczyk** [comment]
> most likely best done on the client-side for this case.
Electron has built-in support for macos vibrancy, why it can't support windows acrylic material out of the box?

**Comment by DRSDavidSoft** [comment]
@dreszczyk Someone actually made a windows acrylic module for electron!
https://github.com/23phy/electron-acrylic

It's still in beta phase but I'm sure @23phy will complete it. Hopefully, at some point, this will get merged into the main electron builds, with a unified API just like macOS vibrancy.

**Comment by 23phy** [comment]
I see only one problem here, the function `SetWindowCompositionAttribute` that I am using, which doesn't have such a great documentation, it can be changed anytime, and it's probably hard to maintain.

**Comment by DRSDavidSoft** [comment]
@23phy I see, but that API has been available for quite some time. If Microsoft decides to drop or change it, a fallback in Electron can be used – simply no acrylic effect.

Other programs (like [Glass8](http://www.glass8.eu/guide) for instance) use the same undocumented call to enable Aero/Acrylic effect. It may fail to work if MS change it, but it isn't going to break the app, just the acrylic effect won't work.

I suggest this should be merged into Electron-Vibrancy or the Electron itself. There are quite a lot of projects that need this functionality and by deploying as an _experimental_ feature, it can be tested out by beta users.

**Comment by 23phy** [comment]
I'll see what I can do, gonna dive into the guts of electron 😂 and make a PR. In the meantime, whoever needs that effect, can use the module.

**Comment by DRSDavidSoft** [comment]
@23phy That's awesome. BTW I suggested merging Vibrancy module with this, to get a unified endpoint call. e.g. set the `transparent` and `acrylic/vibrancy` once in the Electron app codebase, and get the same effect on macOS and Windows at the same time.

Don't know if it's easy/possible or not, but that'd be cool.

**Comment by 23phy** [comment]
Vibrancy on macOS should have it's own option, because it has some parameters on how it should render the background. So instead of `transparent: 'acrylic | vibrancy'`, should be two options:
- `vibrancy: 'light | dark | titlebar | selection | menu | and so on'`
- OR
- `acrylic: tint` tint as hexadecimal eg: `0x800020`

Where __vibrancy__ will be available only on macOS, and __acrylic__ on Windows, and it's definitely possible, but let's just stick with what we have for now, maybe in the future.

**Comment by DRSDavidSoft** [comment]
I like the idea of having two separate packages, though it should be possible to set them at the same time (or query the platform before setting eac of them if available.) with the application client itself.

**Comment by 23phy** [comment]
I don't quite understand 🤔

**Comment by rendomnet** [comment]
Is this feature planned?

**Comment by AmirAsghary** [comment]
+1 we need this
