### ISSUE TITLE
How to set a default open program for a type file

### ISSUE THREAD

**Issue by Jsnows** [electron/electron#11781]
How can I make the program packaged by electron into an application that can right-click the open file. For example, I click the right button on the'xx.md'file to choose my application to open.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
