### ISSUE TITLE
Remote.require wraps every object in an array

### ISSUE THREAD

**Issue by omerfarukz** [electron/electron#11780]
* Electron version: v1.7.10
* Operating system: MacOS High Sierra

Hi, i am using a mssql package to querying database. I have 10K result as an array. Sample code is bellow.

select function:

    async select(queryString: string): Promise<any> {
      const sql = remote.require('mssql');
      let connection = new sql.ConnectionPool(this.config);
      try {
        connection = await connection.connect();
        const request = connection.request();
        const result = await request.query(queryString);        
        return result.recordset;
      } catch (err) {
        return null;
      }
      finally {
        if (connection != null && connection.connected)
          connection.close();
      }
    }

My current task is comparing result set and generate a summary. So, i need to traverse and read some keys(columns) in all records in recordset.

    let sum = 0;
    for (const item of results) {
      sum += item.total;
    }

This code is not faster than i guess. Because get and set properties are proxied by electron. 

    descriptor.get = function () {
        return metaToValue(ipcRenderer.sendSync('ELECTRON_BROWSER_MEMBER_GET', metaId, member.name))
      }

So, i have a bottleneck. And i do not know how to solve all task without transferring them. How to solve this problem?

**Comment by MarshallOfSound** [comment]
> So, i have a bottleneck. And i do not know how to solve all task without transferring them. How to solve this problem?

This is how the remote module works, it creates proxies to the real objects in the main process.  If you want to do this "faster" / "better" you should send an IPC message from renderer->main to trigger the mysql request.  Then after getting the results send a message from main->renderer with the results.  This will send them as JSON encoded objects resulting in far more efficient usage on the renderer side of things

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
