### ISSUE TITLE
Closing a window opened from a browserview does not close

### ISSUE THREAD

**Issue by ibash** [electron/electron#11790]
* Electron version: Electron built at aea06ed95f0ae88b33a5853caa76cf921b11a7af
* Operating system: macOS 10.13.2

### How to reproduce

1. Load an app in a browser view
2. Within the browser view call `window.open` with another page (creating a popup)
3. Click the red "x" on the new window to close the popup

### Expected behavior

Popup window closes

### Actual behavior

Popup window fires a "close" event but is not destroyed

This happens because the popup inheirit options from the browser view. In particular `webPreferences.isBrowserView` is true, even though the guest window is not a browser view. This can be fixed in the application by listening for the `new-window` event and removing that option.

Repo to reproduce: https://github.com/ibash/browserview-bug
```
Steps:

1. `yarn install`
2. `yarn start`
3. Try to close the popup window with google in it
```

**Comment by codebytere** [comment]
i'll take care of this tn!

**Comment by ibash** [comment]
woo! @codebytere I just filed a more bizzare one too: https://github.com/electron/electron/issues/11797 I'm on the atom slack if other information is needed!
