### ISSUE TITLE
Improve instructions for using mirrors to install electron

### ISSUE THREAD

**Issue by vanessayuenn** [electron/electron#11792]
The [current instructions](https://github.com/electron/electron/blob/master/README.md#mirrors) for installing electron from the Taobao hosted mirror isn't very clear. We could improve it by including a more specific command in the doc:
```
ELECTRON_MIRROR=http://npm.taobao.org/mirrors/electron/ npm install electron
```
and for Windows:
```
set ELECTRON_MIRROR=http://npm.taobao.org/mirrors/electron/ && npm install electron
```

**Comment by codebytere** [comment]
This has been clarified in docs.
