### ISSUE TITLE
Creating a web contents in a 'crashed' handler crashes the main process

### ISSUE THREAD

**Issue by ibash** [electron/electron#11797]
* Electron version: Electron built at aea06ed, also reproduced on 1.8.2-beta.4
* Operating system: macOS 10.13.2

### How to reproduce

1. Clone this repo: https://github.com/ibash/crashed-crash
2. `yarn install`
3. `yarn start`

Crash example [here](https://gist.github.com/ibash/10e9f5903edcc5839ca0cbb4039ed31d)

### Expected behavior

background web contents is continually crashed and recreated.

### Actual behavior

Main process eventually crashes - see link above.

**Comment by ibash** [comment]
Also noting that this seems to be mitigated by doing `setTimeout(() => { createBackground() },5000)` instead of calling it synchronously.

**Comment by ibash** [comment]
@sofianguy I was able to create a reproduction example and edited the issue.

**Comment by codebytere** [comment]
I can look into this one a but, but if you look [here](https://github.com/electron/electron/issues/7050) we somewhat intentionally don't expose the `create()` method as it's pretty unstable.

**Comment by ibash** [comment]
Interesting, our use case has to do with creating a background page (similar to how electron handles chrome extensions now).
I was able to get it to stop crashing by wrapping the create in a setTimeout and commenting out the destroy. lldb showed to different crashes.

Islam Sharabash
217-377-9657

Sent via Superhuman iOS ( https://sprh.mn/?vip=islam.sharabash@gmail.com )

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
