### ISSUE TITLE
Stereo sound with WebRTC does not work

### ISSUE THREAD

**Issue by spectralcodec** [electron/electron#11791]
* Electron version:  1.8.2 Beta 4
* Operating system: Windows 7 64

### Expected behavior
Stereo sound should stream from remote system.  

### Actual behavior
Mono sound streams from remote system.

### How to reproduce
Point electron application to https://appr.tc/?stereo=true&audio=echoCancellation=false.
Important that Electron is used on both sides as stereo sound will work properly when plain Chrome is used on one side.

I see these errors on the command line:
[10712:0131/142812.061:ERROR:adm_helpers.cc(62)] Failed to query stereo recording.
[10712:0131/142812.107:ERROR:audio_send_stream.cc(103)] Failed to set up send codec state.

**Comment by TGWKE** [comment]
These errors are also on Ubuntu 16.04 & RHEL 7.x (so I presume most linux distros)

**Comment by davidtoska** [comment]
I got a similar error when I try to connect to a "room" in Twilio. Building an video-application with
electron and Twilo. To sound. 

[18632:0419/214440.072878:ERROR:audio_send_stream.cc(103)] Failed to set up send codec state.

Get this error. Using ubuntu by the way.

**Comment by caoyongfeng0214** [comment]
will be reproduced on windows server 2016.

step 1: No sound card installed.
step 2: use Simple-peer.js
step 3: var peer = new SimplePeer();
step 4: throw error: Failed to query stereo recording.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by spectralcodec** [comment]
Okay, I will try to test for this problem again at a later time.
 Chris
