### ISSUE TITLE
Electron unable to open default mail application in windows

### ISSUE THREAD

**Issue by vaidyaanand** [electron/electron#11802]
I am using election framework to built .exe and .dmg files. In the app I have a button, clicking on which it must open default email application installed on the system to send an email. Following is the code to open email client

`electshell.openExternal("mailto:xyz@abc.com?subject=MySubject&body=");`

But, it only works on few systems. 
Note: It is already checked that other systems also have default email client. Is there any better way to do it. So, it will work on all system?
The same code is working on windows 10.
Thanks in advance for providing help and your precious time!
* Electron version:1.7.12
* Operating system: Windows 7/ 8.

### Expected behavior

It must open default mail application in any windows/mac/linux system
### Actual behavior

As I tested the application in Windows 7 / 8, the electron is not able to open default mail application.
### How to reproduce
Make any simple election app. Just make one button click on, use the same code in click function as I provided above. Run the program on windows 7 / 8

**Comment by codebytere** [comment]
Have you checked that the `mailto:` protocol works on your system in other cases? Oftentimes in older versions of windows there is no default mail client set and so it won't work regardless.

**Comment by vaidyaanand** [comment]
Yes @codebytere The `mailto:` is not working in other cases as well. The simple `mailto:` in JS is not working on chrome. I think there is no default mail client set at chrome or HKEY_LOCAL_MACHINE. 
Thanks for pointing on this.

**Comment by codebytere** [comment]
Since this isn't an Electron issue per se i'm going to close this out, glad i could help!

**Comment by vaidyaanand** [comment]
Sure, I agreed. It is not an electron issue. But still, I am thinking about its alternate solution if any.

**Comment by vaidyaanand** [comment]
@codebytere Thank you
