### ISSUE TITLE
Vibrancy not blurring

### ISSUE THREAD

**Issue by meznaric** [electron/electron#11803]
* Electron version: 1.7.12
* Operating system: macOS High Sierra 10.13.2

### Expected behavior

Vibrancy should blur contents behind.

### Actual behaviour

Vibrancy only sets the colour but it doesn't blur. See screenshot.

![Vibrancy Example](https://i.imgur.com/MtIOS9d.jpg)

### How to reproduce

Used this as an example:
https://gist.github.com/kevinsawicki/9d05fabdee32105367969bbca259ab3e

Added my own package.json:
```
{
  "name": "vibrancy-demo",
  "version": "1.0.0",
  "dependencies": {
    "electron": "^1.7.12"
  }
}
```
Install: `npm install`
And run: `./node_modules/.bin/electron ./index.js`

**Edit:** It may be the problem that I somehow disabled vibrancy system wide. I am investingating, will update soon.

**Comment by meznaric** [comment]
Closing. Seems to work. The problem was that I had "Reduced Transparency" ticked under accessibility.

See: https://apple.stackexchange.com/questions/261145/how-to-disable-background-blur-effect-on-macos-sierra-login-screen

**Comment by fabiospampinato** [comment]
It's still broken for me in Electron 10.1.3, and I don't have "Reduce Transparency" enabled on my system 🤔
