### ISSUE TITLE
Include openssl headers into the headers tarball

### ISSUE THREAD

**Issue by dsagal** [electron/electron#11801]
It does not seem like @zcbenz's "wontfix" comment in #1410 still applies today. Is there any reason not to include `deps/openssl` into the electron's headers bundle created in [create-node-headers.py](https://github.com/electron/electron/blob/278c58055ed36f6f22cea05a9cd85a5ab4fb3010/script/create-node-headers.py#L24)? I think that would resolve #1410 and https://github.com/JoshKaufman/ursa/issues/161.

**Comment by phoniks** [comment]
@dsagal - it seems like you've made some progress on implementing this (based on other issues).  Any chance a PR to include your fix is forthcoming?

**Comment by dsagal** [comment]
Well, the change itself is trivial:
```
diff --git a/script/create-node-headers.py b/script/create-node-headers.py
index 673de5c5b..c6f63a7c1 100755
--- a/script/create-node-headers.py
+++ b/script/create-node-headers.py
@@ -21,6 +21,7 @@ HEADERS_SUFFIX = [
 HEADERS_DIRS = [
   'src',
   'deps/http_parser',
+  'deps/openssl',
   'deps/zlib',
   'deps/uv',
   'deps/npm',
```
This allows me to _build_ -- for example, [ursa](https://github.com/JoshKaufman/ursa). But this time I ran into trouble at runtime, with symbols not found in dynamic libraries (back in electron v1.7, it used to build and work, at least on Mac and Windows). This one I haven't figured out, so I don't actually have a working solution :(

**Comment by nornagon** [comment]
FYI, electron 4.0.0 and up will build Node with BoringSSL, rather than OpenSSL, and the node headers are created here: https://github.com/electron/node/blob/electron-node-v11.0.0/BUILD.gn#L254

**Comment by alejandroclaro** [comment]
@dsagal Shouldn't this issue be closed?

Electron is not using OpenSSL anymore. Only BoringSSL.

**Comment by dsagal** [comment]
Yes, this is outdated now.
