### ISSUE TITLE
Issues that contain reproducible bugs, e.g. crashes, should have a custom form

### ISSUE THREAD

**Issue by ckerr** [electron/electron#11816]
This is a breadcrumb issue referring to the brainstorming that @groundwater, @jkleinsc and I did this morning on potential improvements to our issue triage.

The idea, in short:
1. different forms for submitting different kinds of issues
2. one category would be crashes that can be reproduced with an automated test case
3. another category would be bugs that can be seen by a human tester running an automated test case
4. in the actual issue, dump metadata about the category of bug
5. probot could use this metainfo eg to kick of CI to reproduce crashes
6. some mechanism that makes it possible for human testers to fetch and run the test cases easily
7. some way for people doing triage to kick off a CI run of the test case, e.g. old untouched bugs could be re-triaged this way instead of us asking "could you please see if this works now in a newer version of Electron?"

**Comment by codebytere** [comment]
Closing as we now have bespoke issue forms.
