### ISSUE TITLE
Successive calls autoUpdater.checkForUpdates(); should not redownload the same version to a random directory in temp

### ISSUE THREAD

**Issue by oxygen** [electron/electron#11811]
At least on Windows, autoUpdater.checkForUpdates(), without any changes to latest.yml and the latest published setup.exe on a static HTTP repo, would redownload the same setup.exe in a new temporary directory.

With a setInterval() it would fill the disk, as it does not clean up after itself.
Even without a setInterval, it still leaves traces, and it should cleanup after itself on application exit.

I know there's a `update-downloaded` event, however, it is desirable to recheck for even newer updates even if there's an older update downloaded but not installed.

The `tmp` project https://github.com/raszi/node-tmp makes sure to clean-up temporary files on application exit somehow, or manually through an API.

Feature request:
 - cleanup temporary folder
 - checkForUpdates() must be smarter and remember it has already successfully downloaded a certain version.

I am willing to  implement this myself, waiting for some input.

Thank you :)

**Comment by MarshallOfSound** [comment]
> without any changes to latest.yml 

This sounds like `electron-builder` update logic, not our internal autoUpdater API (neither Squirrel.Windows or Squirrel.Mac natively uses yml config / metadata files).  You should raise an issue on `electron-builder` about this 👍

**Comment by oxygen** [comment]
Without looking at the source code, it would seem your implementation does not reuse some internal object which would know about a previous or ongoing state of a downloaded file and its version.

The API call is made directly to your implementation which controls the update life cycle and the life cycle of wrapped objects. There is probably nothing electron-builder can do, unless you tell it (.cleanup() or something).

To prevent the behaviour, I went around and checked through if the last modified date of the latest.yml changed.

If anything, your implementation needs to keep track of whatever electron-builder is notifying about, like the currently downloaded version, and somehow cleanup after electron-builder using electron-builder logic or your own.

A state needs to be kept track of in this singleton/static class: `const autoUpdater = require("electron-updater").autoUpdater;`, not necessarily electron-builder, but using electron-builder provided information.

**Comment by MarshallOfSound** [comment]
Having seen the source code, and used the updater extensively 😄 I'm reasonably sure this is `electron-updater` not cleaning up temporary files, and that is not a concern of our built-in updater.  If I'm missing something here I'm happy to repoen this 😄

**Comment by MarshallOfSound** [comment]
> With a setInterval() it would fill the disk, as it does not clean up after itself.

Also regarding this, you should really cancel the interval once you get notified an update has been found. 👍

**Comment by oxygen** [comment]
Yeah I know that's the easy way out.

However it was the right decision to keep checking at an interval for two reasons (already mentioned in the first post):
 - getting a new update right after updating is a bad user experience
 - being able to skip a bad (crashing app on start for some users?) downloaded update by superseding it with a newer fixed version, before the user clicks update.

Since there is no safe way to automatically restart after updating (http static repo method), and it would be a bad user experience to interrupt whatever he was doing, I have chosen to have the user decide when to update, so he can start the app afterwards.

**Comment by oxygen** [comment]
I will move over to https://github.com/electron-userland/electron-builder

Sorry for wasting your time, I should have posted there.
