### ISSUE TITLE
MakeSingleInstance callback is emitted before app 'ready' event.

### ISSUE THREAD

**Issue by clusterberries** [electron/electron#11814]
* Electron version: 1.7.11
* Operating system: Mac

### Expected behavior

From documentation of app.makeSingleInstance:

> The callback is guaranteed to be executed after the ready event of app gets emitted.

### Actual behavior

The callback is executed before the ready event of app gets emitted.

### How to reproduce

The issue is not reproduced on Windows. Also it is not reproduced on <=1.7.9 version. Not sure about 1.7.10.

**Comment by MarshallOfSound** [comment]
Can you provide steps to reproduce?

**Comment by clusterberries** [comment]
@MarshallOfSound oh god, I was confused by another handler! It's not makeSingleInstance but open-url event. I'm sorry.
So, I have an application that registers custom protocol using Electron API. 
When protocol is already registered and the app is closed, I open url with custom protocol. This action triggers 'open-url' event and after that 'ready' event. It was in reverse order on Windows and on Mac with Electron <=1.7.9.
Is it an issue? I can't find anything about events order in the documentation.

**Comment by MarshallOfSound** [comment]
@clusterberries As far as I am aware we don't make any guarantees about the order of event execution for `open-url` and in fact that event is one I always recommend people register way before the `ready` event as there is no event queue, if it is emitted and you aren't listening it's gone 😆

**Comment by clusterberries** [comment]
Ok, thanks!
