### ISSUE TITLE
Repeating Unauthorized Error Message

### ISSUE THREAD

**Issue by imknapik** [electron/electron#11821]
![2018-02-03_1026](https://user-images.githubusercontent.com/35350289/35769188-e0d7c266-08cc-11e8-8eae-f2e2297b1903.png)

* Electron version: Newest download (2/3/18)
* Operating system: Windows 64 bit

### Expected behavior

Unauthorized error message doesn't appear at bottom of wallet application and wallet starts.

### Actual behavior

Unauthorized error message keeps popping up (every 3-5 seconds while application is open) and wallet start button hangs in 'wallet starting' mode.

### How to reproduce

Was attempting to activate staking. Made the changes to eccoin.conf as outlined on github (input my PC's username and password). Started the wallet and clicked the padlock to activate staking for 60 seconds as a trial. I started to receive an "unauthorized" popup on bottom of wallet. Waited 60 seconds and the error message persisted. Restarted wallet, changed the eccoin.conf back to original settings, tried using the radio button config for staking to turn it off, etc. Now the unauthorized error message just continues to pop up and seems my wallet won't start after many minutes of waiting. Any suggestions?

**Comment by ckerr** [comment]
> Electron version: Newest download (2/3/18)

Hi @imknapik, could you please specify the version number? From "newest download" I can't tell if you mean you're working from `master` or the newest version of 1.8.x, 1.7.x, or 1.6.x.

**Comment by imknapik** [comment]
Sorry about that.  0.1.7.  Thanks!

**Comment by MarshallOfSound** [comment]
@imknapik This appears to be an issue with a third party Electron based application rather than Electron itself, I would suggest raising an issue on their repository 👍

**Comment by imknapik** [comment]
Thanks.  Just FYI I selected this forum because it's the one that links directly from the LYNX wallet when you select report an issue.

**Comment by ckerr** [comment]
Yep it appears that they've copy-pasted some boilerplate for their code.

https://github.com/CryptoUnited/Sapling/blob/master/app/menu.js#L97

**Comment by MarshallOfSound** [comment]
@ckerr 

> https://github.com/atom/electron/issues

Some super old code 😮
