### ISSUE TITLE
[idea] Investigate a strategy for Android builds, similar to Termux.

### ISSUE THREAD

**Issue by trusktr** [electron/electron#11826]
(continuing #9162)

[Termux](https://github.com/termux/termux-app) allows one to `apt-get install` many Linux applications right in Android, including stuff like Node.js. It doesn't seem far-fetched to use an approach like Termux does to get Electron running in Android.

Maybe this is worth investigating...

**Comment by MarshallOfSound** [comment]
@trusktr This discussion should be kept to #9162 😄
