### ISSUE TITLE
Tray does not open when BrowserWindow covers it

### ISSUE THREAD

**Issue by bsparacino** [electron/electron#11823]
* Electron version: 1.8.2-beta.5
* Operating system: Windows 10 (1709)

### Expected behavior

If BrowserWindow is taking up the entire screen, then when you click on the Tray icon, the Tray should open on top of the BrowserWindow.

### Actual behavior

The Tray does not open.
The trays for other programs do open though.

### How to reproduce

git clone https://github.com/bsparacino/electron-tray-test.git
npm install
npm start

### Explanation
My goal is to run the BrowserWindow fullscreen, with no frame, and no taskbar button.
I only want a Tray icon showing where I can change a few options and exit the program.
The Tray icon works perfectly fine if the BrowserWindow is not the full height of the screen, but once the BrowserWindow covers the Tray icon, then the Tray no longer functions.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
