### ISSUE TITLE
Opening PDF causes crash

### ISSUE THREAD

**Issue by ibash** [electron/electron#11834]
* Electron version: 1.8.2-beta.5
* Operating system: Mac OS X 10.13.2 17C88

### Actual behavior

Electron crashes

### How to reproduce

Haven't found reproduction steps yet, when I do I'll update this issue. I do have a symbolicated [crash report](https://gist.github.com/ibash/164d93fe9544999944fd9fb0e134ba08).

**Comment by codebytere** [comment]
Closing as this appears to be a duplicate of https://github.com/electron/electron/issues/11834

**Comment by ibash** [comment]
@codebytere did you mean to link a different issue?

**Comment by codebytere** [comment]
oops yeah meant your old issue https://github.com/electron/electron/issues/11722

**Comment by ibash** [comment]
I think they're reproduced differently, and the stack traces are a bit different, I'll try making a sample repo later today.
