### ISSUE TITLE
Closing OSR devtools in software rendering mode causes OnPaint callback for transparent window to be permanently filled with white background

### ISSUE THREAD

**Issue by vulture** [electron/electron#11833]
* Electron version: 1.8.2beta5
* Operating system: Windows 32-bit

### Expected behavior

After closing devtools, OSR rendered window should remain transparent. This is the case with 1.7.12 (latest 1.7 version as of this bug report)

### Actual behavior

OSR rendered window is filled with white background.

### How to reproduce

`electron main.js` (with the following two files stuck somewhere). dev tools will open themselves. OSR onpaint gets the correct transparent window, until devtools is closed, at which point, background becomes permanently white, destroying transparency.

main.js:
```
const {app, BrowserWindow} = require('electron')
const fs = require('fs');

app.disableHardwareAcceleration()

var counter = 0;

let win
app.once('ready', () => {
  win = new BrowserWindow({
    webPreferences: {
      offscreen: true,
    },
    show: false,
    transparent: true,
    width: 800,
    height: 600,
    frame: false,
  })
  win.loadURL(`file://${__dirname}/index.html`);
  win.webContents.on('paint', (event, dirty, image) => {
    // updateBitmap(dirty, image.getBitmap())
    ++counter;
    fs.writeFile('bitmap' + counter + '.raw', image.getBitmap(), (err) => {
      if (err) throw err;
      console.log('It\'s saved!');
    });
  })
  win.webContents.setFrameRate(30)
  win.toggleDevTools();
})
```

index.html:
```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>OSR test</title>
        <style>
          html, body { background: rgba(0, 0, 0, 0); }
       </style>
    </head>
    <body><font color=#ffffff>testing</font></body>
</html>
```

**Comment by codebytere** [comment]
This will be solved in https://github.com/electron/electron/pull/11728 i believe

**Comment by vulture** [comment]
Just applied #11728 to 1.8.2beta5 -- it did not fix this issue. However, I think it might have fixed another issue I reported https://github.com/electron/electron/issues/11439 :P

**Comment by vulture** [comment]
FYI: Still an issue in 1.8.2 non-beta stable release version.

**Comment by brenca** [comment]
This also happens btw in normal mode with a transparent window.
