### ISSUE TITLE
install native node-modules in different OS

### ISSUE THREAD

**Issue by zhaiyuzhai** [electron/electron#11837]
* Electron version:"electron": "~1.7.8"
* Operating system:WIN10_X64

### Actual behavior

I install the noble module in my computer ,well,it`s ok.but when i install noble in my computer just for the win_ia32,it does not work.I wanna konw that my computer should be the win_ia32?

**Comment by codebytere** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the community or to the [Slack Channel](atomio.slack.com).
