### ISSUE TITLE
Dev Tools from Debug build painfully slow on Windows

### ISSUE THREAD

**Issue by cortx7** [electron/electron#11840]
* Electron version: Latest from master branch (02/07/18)
* Operating system: Windows 10 (and Windows 7)

It seems that the dev tools from the Debug build (build.py -c D) is painfully slow on Windows. Even switching between tabs is very laggy (it takes me 1.5 seconds to switch from "Elements" to "Console"). Debugging sources is also very hard and unresposive (same for tweaking CSS rules).
I noticed that CPU usage is very high (around 28% most of the time) and it spikes to 50% when fiddling with the dev tools.

It seems that the issue is gone with a Release build. I wonder if this is the expected behavior for a Debug build? Maybe some extra work is being performed behind the scenes?

**Comment by cortx7** [comment]
Also, I don't know if this is related or not, but it looks like syntax coloring is broken (at least for JSX files).
I noticed the following error message:

`[14428:0206/145354.646:ERROR:CONSOLE(105)] "Uncaught (in promise) Error: Could not instantiate: CmModes.DefaultCodeMirrorMimeMode", source: chrome-devtools://devtools/bundled/inspector.js (105)`

**Comment by JemarJones** [comment]
@cortx7 I'm seeing that exact same error myself (i'm using the react template of electron-forge if that matters). It doesn't seem to affect anything that i'm noticing but its logged repeatedly.

**Comment by tzarebczan** [comment]
We are also seeing this error logged on v2.0.5 of Electron at LBRY:
```
┏ Electron -------------------

  [11320:0730/143717.433:ERROR:CONSOLE(105)] "Uncaught (in promise) Error: Could not instantiate: CmModes.DefaultCodeMirrorMimeMode", source: chrome-devtools://devtools/bundled/inspector.js (105)
  [11320:0730/143717.433:ERROR:CONSOLE(105)] "Uncaught (in promise) Error: Could not instantiate: CmModes.DefaultCodeMirrorMimeMode", source: chrome-devtools://devtools/bundled/inspector.js (105)
  [11320:0730/143717.433:ERROR:CONSOLE(105)] "Uncaught (in promise) Error: Could not instantiate: CmModes.DefaultCodeMirrorMimeMode", source: chrome-devtools://devtools/bundled/inspector.js (105)

┗ ----------------------------
```

**Comment by MarshallOfSound** [comment]
> It seems that the issue is gone with a Release build. I wonder if this is the expected behavior for a Debug build?

That's correct, devtools in debug build is expected to have this kind of performance 👍

**Comment by davidhjones** [comment]
Seems related to #14418
