### ISSUE TITLE
Error: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by AhmadIbrahiim** [electron/electron#11853]
* v1.4.15
* Windows 10:

### Expected behavior
i have cloned #[Rocket-Chat](https://github.com/RocketChat/Rocket.Chat.Electron) Which is desktop application build using electron 
 and i used to get this when i try to run the app 
`App threw an error during load
Error: A dynamic link library (DLL) initialization routine failed.
\\?\D:\Mine\Projects (NON-Bot)\Rocket.Chat.Electron\node_modules\@paulcbetts\system-idle-time\build\Release\system_idle_time.node`

### Actual behavior

![image](https://user-images.githubusercontent.com/17949497/35917045-4c618fc6-0c15-11e8-8875-22b56043404c.png)

### How to reproduce

```
git clone https://github.com/RocketChat/Rocket.Chat.Electron.git
cd Rocket.Chat.Electron
yarn
yarn star
```

**Comment by kwonoj** [comment]
This isn't electron side issue, occurred by `system-idle-time` module `Rocket-Chat` depends on.

**Comment by MarshallOfSound** [comment]
You need to rebuild `system-idle-time` using Electron headers.  See https://electronjs.org/docs/tutorial/using-native-node-modules
