### ISSUE TITLE
Request for node.js version update

### ISSUE THREAD

**Issue by Gentser** [electron/electron#11854]
* Electron version: v1.8.2-beta.5
* Operating system: Windows 10

Hello!
I work at the application, which uses MDNS. And there is a need to use the function `setMulticastInterface()` in it, which is not supported in the current version of node.js (v8.2.1), used by electron.
Is it possible to upgrade node.js version in the electron up to v8.6.0 (because it has required functionality)?

**Comment by MarshallOfSound** [comment]
The node version we use is tied to the v8 version that chromium uses, current master is on node 9 though 😄 

That said I've been using mdns in my app since electron 1.2 so it should work fine
