### ISSUE TITLE
getPath("logs") use the wrong "userData" path

### ISSUE THREAD

**Issue by KEVINdEsBuRgErS** [electron/electron#11858]
Hi, getPath("logs") return the wrong path.
getPath("logs") return : %APPDATA% + ProductName from the executable of Electron
when it should return : "userData" (when edited) + productName from package.json

The consequence is that Electron creates an empty folder "logs" in the wrong place.

It seems to me that the problem has occurred since this fix : #10911

* Electron version: 1.8.2 (since 1.8.2-beta.2)
* Operating system: Windows 7 64 bit

**Comment by MarshallOfSound** [comment]
@KEVINdEsBuRgErS How are you launching your app?

**Comment by KEVINdEsBuRgErS** [comment]
@MarshallOfSound My application is located in the folder /resources/app and I launch the app through Electron.exe

**Comment by kspearrin** [comment]
I'm also seeing something similar. We change the log path with `app.setPath('logs', path.join(process.env.PORTABLE_EXECUTABLE_DIR, 'logs'))` as the first line in our `main.js`, yet we are still seeing an empty `logs` folder created at `%APPDATA% + ProductName.

**Comment by Mic75** [comment]
Also, our ProductName contains a space in it, so now we're ending with:
`%APPDATA%\Product Name\logs` and `%APPDATA%\ProductName` (no space).

Note that the second path is what is returned by `getPath('userData')`

**Comment by codebytere** [comment]
i'll resolve this shortly

**Comment by codebytere** [comment]
As a quick update, diagnosing this problem more thoroughly told me some light refactoring may be in order so this is absolutely still on my active radar but it may take slightly more time :)

**Comment by KEVINdEsBuRgErS** [comment]
@codebytere Take your time, I just didn't want this issue to be forgotten forever !

**Comment by KEVINdEsBuRgErS** [comment]
Electron v3 is coming and no news for this issue :(

**Comment by pronebird** [comment]
Sorry if I repeat the issue, but just to give a little info for debugging, tested Electron 2.0.2 and `logs` option does not respect `productName`, returns `Electron` instead of `Product Name` when running in development mode.

```
userData:  /Users/pronebird/Library/Application Support/Product Name
logs:  /Users/pronebird/Library/Logs/Electron
```

**Comment by tbenyon** [comment]
@codebytere any news on this fix? I'm having the same problem as @kspearrin: 
"I'm also seeing something similar. We change the log path with app.setPath('logs', path.join(process.env.PORTABLE_EXECUTABLE_DIR, 'logs')) as the first line in our main.js, yet we are still seeing an empty logs folder created at `%APPDATA% + ProductName."

**Comment by christianp** [comment]
This is holding up a project I'm working on. Following @codebytere's comment, I looked for the bit of code that creates the logs dir, and couldn't find it. I guess you want to fix it 'properly', anyway.

**Comment by bingqiao** [comment]
I'm seeing the same behaviour. setPath on "logs" has no effect. An empty logs folder gets created in a folder named after the original "product name" even though  app.setName gets called first thing in the app to change it to something different.

**Comment by daniloprates** [comment]
Any news, fix ou possible hack on this?

**Comment by daniloprates** [comment]
Any news, fix ou possible hack on this?
