### ISSUE TITLE
WebFrame setSpellCheckProvider not called in an iframe inside of BrowserView

### ISSUE THREAD

**Issue by gshahbazian** [electron/electron#11868]
* Electron version: 1.8.2
* Operating system: 10.13.3

### Expected behavior

iframes inside of `BrowserViews` should also generate calls to `webFrame.setSpellCheckProvider`

### Actual behavior

The registered spellcheck provider is never called

### How to reproduce

Download attached sample app. Run:
```
yarn install
yarn run dev
```
Type into the two text fields in the window. In the console, only one of the text fields logs the spell check log, the other one is inside of the `iframe` and receives no calls.

[electron-spellcheck-bugs.zip](https://github.com/electron/electron/files/1709515/electron-spellcheck-bugs.zip)

**Comment by adlk** [comment]
@sofianguy this issue applies to 2.X as well

**Comment by humancatfood** [comment]
Hi there, just curious how it's going with this bug and if there's something one could help with? We kinda need this functionality.
