### ISSUE TITLE
Support Amazon's own CA

### ISSUE THREAD

**Issue by ptelad** [electron/electron#11860]
* Electron version: 1.8.2
* Operating system: Windows

### Expected behavior

https requests to cloudfront and other AWS services should load

### Actual behavior

all https request to AWS using Amazon's certificates will fail

### How to reproduce

Try to load this img in electron: https://d1ux84wfod9ezj.cloudfront.net/efu/upload/b29cce99adc0b3ebee39ce0f868f0c65.jpg
see if it works.

P.S.
I'm not sure if this is an electron issue, but amazon switched CA and our electron apps broke.

**Comment by renambot-uic** [comment]
same problem here

**Comment by Thomas101** [comment]
It's also okay on Linux. Looks like it's windows only

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR.
