### ISSUE TITLE
Add Support for the Performance Timing API

### ISSUE THREAD

**Issue by philippefutureboy** [electron/electron#11862]
* Electron version: 1.8.2
* Operating system: MacOS 10.13.3

* Why is it that we cannot use the [NodeJS Performance Timing API](https://nodejs.org/api/perf_hooks.html)? Is it because the code is currently in stability level 1:Experimental, or is it simply because the current version of Electron's NodeJS is lower than the minimum requirement for the perf_hooks module?
* When should we expect support for the feature?

### Actual behavior

Throws a 

```
Error: Cannot find module 'perf_hooks'
    at Module._resolveFilename (module.js:485:15)
```

### How to reproduce

Add the following import statement to your codebase:

```
import { performance } from 'perf_hooks';
```

or

```
const { performance } = require('perf_hooks')
```

Cheers ✨

**Comment by codebytere** [comment]
This would be because we haven't shipped a version of node that's compatible or recent enough to include the performance timing api; we're in the process of several upgrades to chromium which include node upgrades but it'll be a while before we get to `v9.5.0`

**Comment by philippefutureboy** [comment]
Cheers, thanks for your answer 😄
