### ISSUE TITLE
Tray icon not created on Linux in production

### ISSUE THREAD

**Issue by nukeop** [electron/electron#11866]
* Electron version: 1.8.2
* Operating system: Linux Mint 18

### Expected behavior

I'm doing the following: 

```javascript
let icon = nativeImage.createFromPath(path.resolve(__dirname, 'resources', 'media', 'icon.png'));
let tray = new Tray(icon);
```
Where the relative path 'resources/media/icon.png' contains a valid png image.
In dev builds, this correctly creates a tray icon and lets me add context menu entries, etc.

### Actual behavior

In production builds, generated with electron-builder, the tray icon is not created and no error messages are generated.

### How to reproduce

I can provide the repository of a project that I was developing when I encountered the bug:
https://github.com/nukeop/nuclear/

To install dependencies:
```bash
npm install
```

To run dev version (in separate terminals):

```bash
npm run watch
npm run electron 
```

To build and run production:
```bash
npm run build:dist
npm run build:linux
```

The 'release' directory will contain build artifacts, among them an appimage and regular unpacked version where the problem occurs.

main.js and main.prod.js are the development and production versions of the electron main process files respectively.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
