### ISSUE TITLE
Cant start electron app

### ISSUE THREAD

**Issue by tommyriska** [electron/electron#11861]
When I try to start the application I am developing I expect to start the app using `electron .` but this does not work and I get this error message:

> `Tommys-MacBook-Pro:KitronApp tommyriska$ electron .
/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron[707]: ../../vendor/node/src/async-wrap.cc:399:void node::SetupHooks(const FunctionCallbackInfo<v8::Value> &): Assertion `env->async_hooks_init_function().IsEmpty()' failed.
 1: node::Abort() [/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 2: node::Assert(char const* const (*) [4]) [/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 3: node::AsyncWrap::Initialize(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Context>) [/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 4: v8::internal::StrDup(char const*) [/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 5: v8::internal::compiler::BranchElimination::ControlPathConditions::operator==(v8::internal::compiler::BranchElimination::ControlPathConditions const&) const [/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 6: v8::internal::compiler::BranchElimination::ControlPathConditions::operator==(v8::internal::compiler::BranchElimination::ControlPathConditions const&) const [/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 7: 0x1476d29043fd
 8: 0x1476d29f777c
 9: 0x1476d29bbe1c
Tommys-MacBook-Pro:KitronApp tommyriska$`

This only happens in this particular project folder. When I run `electron`, the example window from electron starts up without problems and when I try to start another electron project it works fine, but not in this particular project.

I have reinstalled both electron and NPM/Node but that did not help. I have tried to examine the error message but I dont understand what is going wrong here. I really dont know how to reproduce this either so sorry for not including this. The code is in a private repository and cannot be shared in its whole but I could include different files in here if there is any file you want to examine.

- Electron version: 1.7.12
- Operating System: macOS High Sierra 10.13.2

I am including a picture version of the error message as well if thats better to read.
![screen shot 2018-02-08 at 14 35 39](https://user-images.githubusercontent.com/15278093/35976193-a2d0762c-0cdf-11e8-9e2f-f1497f9b3d52.png)

**Comment by tommyriska** [comment]
It might not be a Electron specific problem, could be a problem with my computer configuration but since the error includes paths to electron module I made a issue on here.

**Comment by tommyriska** [comment]
This is from the macOS error report if that is any help

![screen shot 2018-02-08 at 15 02 49](https://user-images.githubusercontent.com/15278093/35976672-291d3264-0ce1-11e8-96bc-a756f33359d8.png)

**Comment by tommyriska** [comment]
Apparently, I can start the application using Electron 1.6.2 instead of 1.7.12(latest). Could this be because of some previous configuration on the first version as I am improving it for a second version?

**Comment by tommyriska** [comment]
As far as my research goes, my problem was that I use [ExcelJS](https://www.npmjs.com/package/exceljs).

ExcelJS is not a problem in itself but its the packages it depends on that is the problem. ExcelJS depends on the [unzip2](https://www.npmjs.com/package/unzip2) package. Unzip2 depends on the [fstream](https://www.npmjs.com/package/fstream) package version 0.1.31 which essentially depends on the [graceful-fs](https://www.npmjs.com/package/graceful-fs) package version 3.0.11.

From my travis-yml: 
![e257e53af2b22344df6fe9ed0188c21a](https://user-images.githubusercontent.com/15278093/36062801-be55869a-0e73-11e8-9f5c-7f9197246648.png)


@xialvjun references to [this](https://github.com/isaacs/natives/issues/16) in #10905. I'll just quote @isaacs on the current solution

> The latest version of graceful-fs doesn’t use natives. Versions of graceful-fs from 3.x and before are deprecated for this reason. It will likely never work in new node versions.
>Upgrade graceful-fs, or downgrade node. No other way forward.

Fstream probably needs to upgrade its package to utilize graceful-fs version 4.x. I am not really sure if I can do anything here or if its up to the developers to actually upgrade their packages to work with newer versions.

**Comment by xialvjun** [comment]
@tommyriska In fact, the author of `unzip2` has merged those Pull Requests which at least update it's dependencies like `graceful-js`. But he hasn't publish it to npm. 

https://github.com/glebdmitriew/node-unzip-2/pull/17#issuecomment-359376740

Maybe he have lost his account on npm.😱🤣

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
