### ISSUE TITLE
Feature Request: Prevent the You need to format the disk drive popup

### ISSUE THREAD

**Issue by aamm132** [electron/electron#11876]
I was wondering if it would be possible to prevent windows from popping up the window asking to format the disk drive. In etcher, when a USB is flashed this window pops up: 
![image](https://user-images.githubusercontent.com/25181342/36034651-53d93acc-0d7a-11e8-8900-b69c5b479584.png)

Regardless of the answer, the flashing is successful anyways. So in essence, the window is unnecessary and annoying. Is there a way already to prevent it? If so, what is it? If not, is it possible to add a way preventing this? 
Thanks for any help!

**Comment by MarshallOfSound** [comment]
@aamm132 That's something etcher triggers / is in control over.  Issues with electron apps should be raised on their repos not electron 😄 

https://github.com/resin-io/etcher
