### ISSUE TITLE
add the API of electron to save the Dev tool's log

### ISSUE THREAD

**Issue by lake2** [electron/electron#11870]
![default](https://user-images.githubusercontent.com/6293752/36015696-8915206a-0d67-11e8-8fc5-3339ba28f5dd.png)
I think it's necessary to add the API of electron to save the Dev tool's log, so that we can use the console.log, console. assert and console. group to save the log information easily just as we are developing. I think there is no need to use a third-party logging module, because the functions of console are powerful enough and sometimes a third-party may use console.log to print some information, which is hard to be recorded by a logging module.
It's just a suggestion.

**Comment by codebytere** [comment]
Hi, while we appreciate this enhancement request it's not something that we think is best implemented into the core API functionality of Electron. We prefer to keep the API layer thin, and so 3rd party logging modules are preferable for this at the moment.
