### ISSUE TITLE
Crash during execution with 1.8.2

### ISSUE THREAD

**Issue by manu-st** [electron/electron#11871]
* Electron version: 1.8.2
* Operating system: Windows 10 Fall Creator Update

### Expected behavior
Script should run properly.

### Actual behavior
Script barely executes and display the following dialog box:
![image](https://user-images.githubusercontent.com/13194660/36016429-c54edc64-0d27-11e8-9899-a52e3b9afd44.png)
![image](https://user-images.githubusercontent.com/13194660/36016434-c97f2dac-0d27-11e8-91f0-10abbbe772d6.png)

### How to reproduce
I could not yet reproduce it in a sample project. The script is calling electron to execute `jest-cli` to run our test suite inside the electron renderer project. I tried to debug with VS but unfortunately there is no debug information.

With more information on how to debug it, I should be able to provide more details.

**Comment by manu-st** [comment]
Just want to add that the same script runs fine under electron 1.7.9.

**Comment by shiftkey** [comment]
@manu-st which build of Windows are you running (`cmd /c ver` e.g. `10.0.16299.192`)? This might help with reproducing the issue...

**Comment by manu-st** [comment]
This is version Microsoft Windows [Version 10.0.16299.248]

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by manu-st** [comment]
We are now using 2.0.8 and did not encounter this problem again.
