### ISSUE TITLE
Electron version 1.8.2 crashes on Debian ARMv7

### ISSUE THREAD

**Issue by MattiaCostamagna** [electron/electron#11877]
* Electron version: 1.8.2
* Operating system: Debian ARMv7 (TinkerOS)

### Expected behavior
I created some time ago an application that needs to run on the ASUS Tinker board (similar to Raspberry Pi). I've got no problem compiling and running it if I'm using the 1.7.11 version, but today I recompiled it and it doesn't work anymore. On my amd64 laptop I've got no problem with it, but with an ARM OS it doesn't work

### Actual behavior
When I run the application on the Tinker board it opens a white window. I cannot open the developer tool console, and it throws the webContent "crash" event in the main.js.
If I change my package.json electron dependency version from "^1.7.11" to "1.7.11", delete my package-lock.json and node_modules and reinstall everything, it works like a charm.
With the "^1.7.11" electron version, npm downloads the 1.8.2 version.

It's not a problem of the renderer script file, because if I remove the import in the index.html, it does not work either.

**Comment by kewde** [comment]
#11797

**Comment by rip3rs** [comment]
I found the same issue with RPI 2 & 3, once I downgraded to 1.7.x I was able to work fine.
`mainWindow = new BrowserWindow({width: 800, height: 600}) works and the window is opened.`

anything after that is completely ignored.

Using the electron-quick-start but with the latest electron

**Comment by jmsvitae** [comment]
I have also seen the same issue on RPI / armv7l. I upgraded from 1.7.10 to 1.8.2 and the app hung during/after creating the window (does not load index.html). After downgrading to 1.7.10, the app loads correctly.

**Comment by Guardado** [comment]
Same issue happening to me with electron 1.8.2 on a Raspberry Pi 3 (Arm v7). When running any project or electron demo it only shows a white content. Also I can't toggle the Developers Tools.

**Comment by Coollision** [comment]
still the same issue with electron 1.8.3 is there an ETA to when this will be fixed?

note: 2.0.0-beta.2 is currently running without any issues (that i have noticed)!

**Comment by sofianguy** [comment]
Closing because of reports that this issue is not present in 2.0.x
