### ISSUE TITLE
window.navigator.connection not implemented

### ISSUE THREAD

**Issue by ThaJay** [electron/electron#11875]
* Electron version: "electron": "^1.7.12",
* Operating system: Ubuntu 17.10

### Expected behavior
window.navigator.connection to be available
### Actual behavior
```
> window.navigator.connection
< undefined
```
### How to reproduce
- open dev console
- type in window.navigator.connection

or
- use any js module that uses window.navigator.connection
(In my case https://github.com/necolas/react-native-web)

corresponding issue:
https://github.com/necolas/react-native-web/issues/662#issuecomment-364468419

**Comment by codebytere** [comment]
If you look at the [compatibility chart](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/connection#Browser_compatibility), you'll see that this api is only available on chrome 61, and the `1-7-x` line is operating on chromium 59. If you try this on master (running chrome 61) you'll see that it's defined. This will be resolved in a near-future version.

**Comment by pouyamca** [comment]
about nvaigator.share ?
