### ISSUE TITLE
Turkish Translation

### ISSUE THREAD

**Issue by halokaya67** [electron/electron#11889]
I want to help this project by translating it into turkish. I'm turkish and 25 years old. I'm working as an english teacher in a school. I think i can help. Please just show me which file should i translate and you will see. You won't regret because i take my job serious.

**Comment by codebytere** [comment]
Translation of Electron documentation is made possible by community members such as yourself; if you'd like to see translation progress or help out see [languages](https://electronjs.org/languages)!
