### ISSUE TITLE
Electron app(for mac app store) can't connect to http://localhost:631 correctly.

### ISSUE THREAD

**Issue by rensiu** [electron/electron#11882]
* Electron version: 1.7.11
* Operating system: 10.13.2

Electron app(for mac app store) can't connect to http://localhost:631 correctly.
Windows and mac( except mac app store) can connect to http://localhost:631 correctly.

### Expected behavior
It can connect to http://localhost:631 correctly.

### Actual behavior
Error: net::ERR_ACCESS_DENIED

### How to reproduce
```
 let request =  require('electron').remote.net.request({
  method: 'GET',
  protocol: 'http:',
  hostname: '127.0.0.1',
  port: 631,
  path: '/'
})
  request.on('response', (response) => {
    console.log(`STATUS: ${response.statusCode}`)
    console.log(`HEADERS: ${JSON.stringify(response.headers)}`)
    response.on('data', (chunk) => {
      console.log(`BODY: ${chunk}`)
    })
    response.on('end', () => {
      console.log('No more data in response.')
    })
  })
  request.end()
```

**Comment by MarshallOfSound** [comment]
In order for a sandboxed app on macOS to make and receieve network requests it needs be signed with the correct entitlements.  Please see [Enabling Network Access
](https://developer.apple.com/library/content/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/EnablingAppSandbox.html#//apple_ref/doc/uid/TP40011195-CH4-SW9)

**Comment by rensiu** [comment]
Also set `com.apple.security.network.client`, but it can't work for it.@MarshallOfSound

**Comment by rensiu** [comment]
@MarshallOfSound

**Comment by MarshallOfSound** [comment]
@rensiu On macOS port 631 is system reserver, what are you trying to use it for?

**Comment by rensiu** [comment]
use ipp to print @MarshallOfSound

**Comment by MarshallOfSound** [comment]
@rensiu There is probably a special entitlement required to use it, I'd suggest following up on stackoverflow or apple developer forums 👍

**Comment by sethlu** [comment]
@rensiu `net::ERR_ACCESS_DENIED` seems like a Chromium error. If it is a sandboxing issue you should be able to find debug logs displayed in the Console.

**Comment by rensiu** [comment]
@sethlu just that error information.

**Comment by MarshallOfSound** [comment]
`ERR_ACCESS_DENIED` is normally reserved for things like firewalls or OS level protections preventing the request, hence why I jumped on the sandbox train of thought.  The fact that it works outside sandbox further lends to that theory 😄

**Comment by rensiu** [comment]
We have tried to add [App Sandbox Entitlement Keys](https://developer.apple.com/library/content/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/EnablingAppSandbox.html#//apple_ref/doc/uid/TP40011195-CH4-SW9) and [App Sandbox Temporary Exception Entitlements](https://developer.apple.com/library/content/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/AppSandboxTemporaryExceptionEntitlements.html#//apple_ref/doc/uid/TP40011195-CH5-SW1) into my app, but no use.@MarshallOfSound @sethlu
