### ISSUE TITLE
JS error: conversion failure from /opt/Signal/resources/app.asar/images/alert/256/1.png

### ISSUE THREAD

**Issue by knarrff** [electron/electron#11896]
Whenever there is a new message (and as well sometimes in between) I get the following popup. However, this started only a week ago or so, it was working just fine before. I have to 'click' ok, but otherwise things work as usual. I start signal-desktop through session management (xfce) using 'signal-desktop --start-in-tray'.

A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from /opt/Signal/resources/app.asar/images/alert/256/1.png
    at Tray.tray.updateIcon (/opt/Signal/resources/app.asar/app/tray_icon.js:62:12)
    at EventEmitter.ipc.on (/opt/Signal/resources/app.asar/main.js:488:10)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:194:7)
    at WebContents.<anonymous> (/opt/Signal/resources/electron.asar/browser/api/web-contents.js:247:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)

This is using the signal-desktop deb file from
 deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main
on Debian stable.

### Expected behavior

No error.

### Actual behavior

An error window is opened that I manually have to close.

### How to reproduce

Probably use the package on a debian system and have a conversation over signal.

**Comment by felixrieseberg** [comment]
I believe this issue is better suited for signal-desktop, wouldn't you think? You can report issues there: https://github.com/WhisperSystems/Signal-Desktop
