### ISSUE TITLE
electronjs.org not work !!

### ISSUE THREAD

**Issue by hichxm** [electron/electron#11898]
The electron's website not work !!! It's maintenance??

![eletrconjs.org](https://screenshotscdn.firefoxusercontent.com/images/b8fb7eb0-e8d0-41b0-bae7-e19b5c505659.png)

**Comment by danyadev** [comment]
![image](https://user-images.githubusercontent.com/35631027/36109484-a047a66a-1030-11e8-9630-97df1b543351.png)
this happens, now the site works

**Comment by hichxm** [comment]
Thanks you bro :)
