### ISSUE TITLE
Cannot change the `enabled` state of a menu item on Linux

### ISSUE THREAD

**Issue by jlecomte** [electron/electron#11891]
* Electron version: 1.8.2
* Operating system: Mac OS X Sierra, Ubuntu Linux 16.04, Windows 7

#### package.json

```json
{
  "name": "ElectronMenuBug",
  "version": "0.0.1",
  "main": "index.js",
  "dependencies": {
    "electron": "^1.8.2"
  }
}
```

#### index.js

```js
const {app, Menu, BrowserWindow} = require('electron')

app.on('ready', () => {
  let menu

  const template = [{
    label: 'File',
    submenu: [{
      label: 'Foo',
      id: 'foo',
      click: () => {
        const menuItem = menu.getMenuItemById('bar')
        menuItem.enabled = true
      }
    }, {
      label: 'Bar',
      id: 'bar',
      enabled: false
    }]
  }]

  menu = Menu.buildFromTemplate(template)

  const win = new BrowserWindow({ width: 300, height: 300 })
  win.loadURL('about:blank')

  Menu.setApplicationMenu(menu)
})
```

### Expected behavior

After clicking on the first menu item, the second menu item should be enabled.

### Actual behavior

This code works fine on Mac OS X and Windows, but *it does not work on Ubuntu Linux 16.04*. The menu item desperately stays disabled.

### How to reproduce

Using the code above, simply type the following in the same directory:

```
$ npx electron .
```

**Comment by codebytere** [comment]
@jlecomte i'll investigate this week

**Comment by codebytere** [comment]
Possibly related: https://github.com/electron/electron/issues/11386

**Comment by codebytere** [comment]
@jlecomte at first glance it appears that it's an issue with the change setting up and not with the value getting changed, since the following:
```
const {app, Menu, BrowserWindow} = require('electron')

app.on('ready', () => {
  let menu

  const template = [{
    label: 'File',
    submenu: [{
      label: 'Foo',
      id: 'foo',
      click: () => {
        const menuItem = menu.getMenuItemById('bar')
        console.log(`${menuItem.enabled}`)
        menuItem.enabled = true
        console.log(`${menuItem.enabled}`)
      }
    }, {
      label: 'Bar',
      id: 'bar',
      enabled: false
    }]
  }]

  menu = Menu.buildFromTemplate(template)

  const win = new BrowserWindow({ width: 300, height: 300 })
  win.loadURL('about:blank')

  Menu.setApplicationMenu(menu)
})
```
will correctly print `false` and then `true`. i'll keep digging, but it seems distro-specific 🤔

**Comment by jlecomte** [comment]
Right, `menuItem.enabled` is updated properly, but that change does not have any effect on the rendered menu item. Note: I only tested this on Ubuntu Linux 16.04 (LTS), which is a very popular Linux distro. Why would this be distro-specific though? I don't know which underlying library electron uses to render UI on Linux, but I would think that this is where the problem lies.

**Comment by codebytere** [comment]
@jlecomte i mean that in the sense that it doesn't occur on 17.04 or 14.04, so it looks specific to 16.04

**Comment by kspearrin** [comment]
I'm also seeing this on Ubuntu 16.04 in our app. I can execute the accelerator shortcut for the menu items, but they are grayed out and unclickable.

**Comment by codebytere** [comment]
Does this occur on `3.0.0`?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment [here](https://github.com/electron/electron/issues/11891#issuecomment-424852712). With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Comment by programmin1** [comment]
I can confirm the same is happening on Ubuntu 14.04. Please reopen.

**Comment by et304383** [comment]
@codebytere This issue hasn't been resolved on Ubuntu 18.04 if using Unity.

**Comment by codebytere** [comment]
Confirmed to still be occurring on latest versions.

**Comment by ckerr** [comment]
When reporting that this works / doesn't work on your given setup, it may be helpful to know all the details of distro x version x desktop x electron version.

FWIW, the test case @jlecomte gave works for me on `Ubuntu 18.10` running stock default `gnome-shell 3.30.1`. Tested with Electron 1.8.8, 2.0.13, and 3.0.4.

**Comment by pachulo** [comment]
This is happening to me with **Ubuntu 16.04**, **Unity** and the snap version of **Bitwarden** 1.11.1, which is using electron **2.0.11**: https://github.com/bitwarden/desktop/blob/v1.11.1/package-lock.json#L3103

I will try with the same app in Ubuntu 18.04 and Gnome 3.28.x when I have time.

**Comment by opes** [comment]
Can also confirm as this happens to me as well. My setup:

App: Bitwarden 1.11.2
Electron: [2.0.11](https://github.com/bitwarden/desktop/blob/ce659c9a51b046072782deeea4acecf41549dbe5/package-lock.json#L3254)
Operating System: Arch Linux 
KDE Plasma Version: 5.14.4
KDE Frameworks Version: 5.52.0
Kernel Version: 4.19.4-arch1-1-ARCH

**Comment by pachulo** [comment]
Just and update. **Bitwarden** app was updated to version **1.12.0**, which uses **Electron 3.0.13**:
https://github.com/bitwarden/desktop/blob/v1.12.0/package-lock.json#L3103
And the problem persists in **Ubuntu 16.04** with **Unity**.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by pachulo** [comment]
Bitwarden app was updated to version 1.15.2, which uses Electron 5.0.8:
https://github.com/bitwarden/desktop/blob/v1.15.2/package-lock.json#L4192
And the problem persists in Ubuntu 16.04 with Unity.

**Comment by jlecomte** [comment]
I just tested this again with the latest version of Electron and Ubuntu 18.04 / Fedora 30, and everything works properly. Closing issue. Thanks everyone!

**Comment by pachulo** [comment]
> I just tested this again with the latest version of Electron and Ubuntu 18.04 / Fedora 30, and everything works properly.

There have never been a problem with Gnome 3.x, so it's normal that everything works OK there.

The problem occurs on Ubuntu Unity, the default DE from Ubunu 16.04, and is still not resolved.

**Comment by Sparsa** [comment]
The problem persists for KDE 5.16.4 on global menu as well.

**Comment by awilkins** [comment]
Problem still persists with Ubuntu 18.04 / Unity 7

Common thread seems to be that both this and KDE use the dbus implementation?
