### ISSUE TITLE
High CPU Usage While Idling

### ISSUE THREAD

**Issue by ihachani** [electron/electron#11908]
* Electron version: 1.7.9
* Operating system: Windows 10

Windows 10

My Electron application uses a lot of CPU while the `BrowserWindow` is not hidden. When I hide the `BrowserWindow` CPU usage goes back to normal rates.
OSX
 I tried running the application on my mac and it works like a charm.

I know it is not the same processor but here are some figures
Windows 10 CPU usage 50%
OSX CPU usage 0%

**Comment by danyadev** [comment]
on windows 7 there is no problem:

hidden: 
![image](https://user-images.githubusercontent.com/35631027/36150317-528fd268-10d4-11e8-9db4-bc494975a07c.png)
not hidden:
![image](https://user-images.githubusercontent.com/35631027/36150429-bbba6186-10d4-11e8-942c-296b51289752.png)

**Comment by felixrieseberg** [comment]
Could you provide a reproduction or at least a CPU profile? This report by itself makes it difficult to help you.

**Comment by ihachani** [comment]
Ok, I will provide a CPU profile.

**Comment by teleclimber** [comment]
Are there any continuously running animations (CSS or JS) in your application? Even the smallest of CSS animation can cause a lot of CPU use if it is a case that is not optimized by Chromium on that platform.

**Comment by ihachani** [comment]
![profile](https://user-images.githubusercontent.com/5203100/36305367-8b10273c-1313-11e8-85d0-2ab3d6ae4f91.png)

Sorry for the CIA style crossing.

**Comment by ihachani** [comment]
@teleclimber   I don't have any running CSS animations. The application is static while idling. 
The application uses transparent browser window.
```
 win = new BrowserWindow({
        width: 900,
        height: 428,
        useContentSize: true,
        transparent: true,
        frame: false,
        toolbar: false,
        icon: iconpath,
        webPreferences: {
            backgroundThrottling: false,
        },
    });
```

**Comment by fatalmuffin** [comment]
I'm also having high CPU usage (10-15%) in the background. I created a completely empty view to see if it was CSS or JS related and it didn't change the CPU usage.

I'm gonna start disabling modules one at a time to see if one of them is to blame?

![image](https://user-images.githubusercontent.com/34907707/36356791-e2eedb3a-14ab-11e8-8dac-66233e79ef77.png)

**Comment by ihachani** [comment]
I can confirm @fatalmuffin  conclusion. I set the transparency to false and CPU usage is staying at 0%. Can anyone test with Linux platform to see if Linux is affected with this?

**Comment by fatalmuffin** [comment]
Just a quick update, I notice the ram usage is way lower when running with Transparency ON.
Transparency on: 15% cpu, ~50mb ram
Transparency off: 0% cpu, 120mb ram

Possible caching issue?

**Comment by erikkallen** [comment]
My cpu usage of 1 core is 100%, I have tried disabling transparency but it did not help also the profiler is showing idle

**Comment by ihachani** [comment]
Why was this closed?

**Comment by MarshallOfSound** [comment]
@ihachani It wasn't 🤔

**Comment by nealot** [comment]
This makes electron applications almost unusable :(

**Comment by fmiceli24** [comment]
Just to report. I only see this behavior when I run my app in windowed mode. It does not happen in fullscreen.

Windows 10.

**Comment by Veiintc** [comment]
Electron version: 1.8.6
Operating system: Windows 10

SO I WAS!!!
has the problem fixed??

**Comment by vaidyaanand** [comment]
When `transparent: true` application is constantly using around 6.0% of CPU and when I set `transparent: false` the application usage reduced to 0% in idle. Can we fix this thing? I checked on few other links and got `--enable-transparent-visuals --disable-gpu` can we do something with it?

**Comment by gio1217** [comment]
same issue

**Comment by vaidyaanand** [comment]
@gio1217 I sort the issue, by `app.disableHardwareAcceleration();` or if you are using `transparent: true` disable it will sort the issue.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by vaidyaanand** [comment]
@sofianguy I will test it in latest electron version and let you know.

**Comment by tonyd85** [comment]
This framework is killing Duelyst for anyone with a laptop, and anyone with hopes to play it on their tablet. It's shenanigans!

**Comment by U-Studios** [comment]
hi
