### ISSUE TITLE
How can I set Electron menu direction to RTL or right to left

### ISSUE THREAD

**Issue by webcoweb** [electron/electron#11912]
Hello
How can I set Electron menu direction to RTL or right to left?
I couldn't find eny option to do it in Electron document!
😟

**Comment by felixrieseberg** [comment]
Electron should respect the operating system's configuration automatically. You can force RTL by running Electron with the `--force-ui-direction=rtl` parameter. Are you seeing something else? If so, please open a proper bug report and follow the issue template.

Sadly, the menu's RTL direction is not configurable by itself.
