### ISSUE TITLE
Possible to access the file system?

### ISSUE THREAD

**Issue by JuanAntelo** [electron/electron#11915]
Hi,

I would like to have a desktop app that can download a file from the internet and store it in the file system. I would like to know if that's possible with this project.

**Comment by MarshallOfSound** [comment]
@JuanAntelo Check out the `fs` module in nodejs 👍

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
