### ISSUE TITLE
App.Dock is not working 

### ISSUE THREAD

**Issue by manipandi** [electron/electron#11911]
* Electron version: 1.7.12 and 1.8.2
* Operating system: mac-High Sierra

### Expected behavior: 

app icon should bounce even when desktop is in kiosk mode.

### Actual behavior: 

app icon is not bouncing when desktop in kiosk mode.

### How to reproduce
#Scenario 1:
```
let electron = require('electron');
let app = electron.remote.app;
setTimeout(() => {
app.dock.bounce('critical');
}, 500)
```

execute this code in Electron and move to Kiosk mode in desktop with other application.
It should bounce in this case , but it is not happening.

#Scenario 2: 
```
let electron = require('electron');
let app = electron.remote.app;
app.dock.bounce('critical');
```

try with this code in Electron app and expect the app dock to be bounce
But it is not happening (bounce).

**Comment by sdkester** [comment]
Not in kiosk mode, but I'm having the same problem with Electron v1.8.4 on macOS High Sierra v10.13.4. 

Only when I run node inspector and put a breakpoint on `app.dock.bounce('critical');` and then resume the code, the dock bounce will occur as expected.

**Comment by adeperio** [comment]
I'm getting something similar, but only happening on Windows. app.dock is null when trying to do app.dock.show(). Runs fine on Mac, but not so fine on WIndows

**Comment by adeperio** [comment]
Ahh so it is. Thanks @MarshallOfSound

**Comment by knpwrs** [comment]
`app.dock.bounce()` does not work on macOS Mojave. With either no arguments or a string argument it always returns `-1` and the dock icon does not bounce.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
