### ISSUE TITLE
Fire `console-message` even when rendering in offscreen 

### ISSUE THREAD

**Issue by brian-mann** [electron/electron#11919]
I propose removing the constraint that prevents the `console-message` event from bubbling up when rendering a BrowserWindow in `offscreen` mode.

Currently, this line here is the culprit...

https://github.com/electron/electron/blob/9bd7d53cf85ac36e81a080c4fd0572ca34d395ff/atom/browser/api/atom_api_web_contents.cc#L484

Is there a technical constraint I'm not aware of preventing this from working?

[Cypress](https://github.com/cypress-io/cypress) drives automated tests in Electron and we'd love the ability to capture console messages programmatically like this. We currently run Electron primarily in offscreen mode.

I'm aware that it's possible to redirect the internal chromium logger, but it doesn't stringify objects so it's fairly useless. All you primarily see is [object Object].

**Comment by codebytere** [comment]
@brian-mann PR in flight, no real technical constraint to speak of ✨

**Comment by brian-mann** [comment]
Excellent, thanks.
