### ISSUE TITLE
App crashes when Dev Tool is open and User clicks on Actual Size from Electrom Menu Dropdown

### ISSUE THREAD

**Issue by ApurvaB** [electron/electron#11920]
* Electron version:v1.6.11
* Operating system: MacOX

### Expected behavior

 Actual Size  operation from Menu should be disabled when applications starts, It should enable only when user either zooms in or out, as per behavior in chrome browser.

### Actual behavior

If Dev Tools is open, though User has not resized app, Actual Size option is enabled and When clicked on the same, App crashes with
Segmentation fault: 11

### How to reproduce
Include following Menu in your electron App menu 
    {
        label: 'View',
        submenu: [
            {
                label: 'Developer',
                submenu: [
              {role: 'toggledevtools'},
              {role: 'togglefullscreen'},
              {type: 'separator'},
              {role: 'resetzoom'},
              {role: 'zoomin'},
              {role: 'zoomout'}
                ]
            }
        ]
    }

When Application is running : Open Dev tools Option, click on Actual size.
My application's BrowserWindow config is as below:

new BrowserWindow({show: false, height: 650, width: 1150, minHeight: 650, minWidth: 1150});

**Comment by sofianguy** [comment]
Does this issue persist on a later version of Electron, such as 1.8 or 2.0.0?

**Comment by ApurvaB** [comment]
yes. I am using ^1.8.1 in package.json

**Comment by codebytere** [comment]
Closing as this has been resolved in more recent versions of Electron.
