### ISSUE TITLE
Some ipc messages are not sent when contextIsolation and sandbox are set to true

### ISSUE THREAD

**Issue by pcad** [electron/electron#11922]
* Electron version: 1.8.2
* Operating system: MacOS, Windows10

### Expected behavior

ipc messages from the main process should be sent to the renderer process when both `sandbox` and `contextIsolation` are set.

### Actual behavior

ipc messages sent in listeners to webview events are not visible in the renderer process.

### How to reproduce

```
$ git clone https://gist.github.com/4f6c4450cff194838e746ce23e60116d.git
$ cd 4f6c4450cff194838e746ce23e60116d/
$ electron main.js 
```

The devtools will open and the console will log one message.  But the second message on the ipc `ping` channel is not observed.

Toggling either `sandbox` or `contextIsolation` to false allows the `ping` to travel to the renderer process.  In the 1.7.X branch setting both values to true still allows the message to pass through successfully.

**Comment by pcad** [comment]
Updated issue to reflect this issue presents on Windows 10 as well.

**Comment by ckerr** [comment]
Still present in 2.0.x on Ubuntu

**Comment by mattbroussard** [comment]
I think this might be a dupe of #10868?

**Comment by SamuelRobotiq** [comment]
+1

desktopCapturer.getSources is also not working in preload.js when contextIsolation and sandbox are enabled.

**Comment by aegarbutt** [comment]
Thanks to @pcad for providing the context around the last version where it worked and first version where it didn't work.
