### ISSUE TITLE
Update to Chromium 63 for simultaneous debugger client connections

### ISSUE THREAD

**Issue by brian-mann** [electron/electron#11926]
I realize that the electron team just got Chromium 59 in - which is a huge improvement over Chromium 53 - great.

However, Chromium 63 adds a critically needed feature for the `debugger protocol` - that enables multiple simultaneous connections. This is especially useful for writing automated tests - it enables developers to use their normal dev tools - while still leverage the debugger protocol's full potential.

I know it took quite awhile to get up to Chromium 59 - and I have no idea how difficult it would be to get up to 63.

**Comment by codebytere** [comment]
hey! so chromium development work is ongoing and `2-x-x` will be cut with chromium 61, which is already in master and has been for a bit. You can follow along with Chromium 62 & Chromium 63 progress [here](https://github.com/electron/electron/projects/6) and [here](https://github.com/electron/electron/projects/7). Chromium 63 work is and has been in progress, so it'll be a while yet but hopefully not too too long :)
