### ISSUE TITLE
Loose ETA on Chromium 64 and/or AudioWorklet?

### ISSUE THREAD

**Issue by JohnWeisz** [electron/electron#11923]
I understand incorporating a Chromium update into Electron is not at all trivial.

However, we have a use case that absolutely depends on a feature, available beginning from Chromium 64, [AudioWorklet](https://www.chromestatus.com/feature/4588498229133312). Is there a possible ETA on around when to start expecting this?

**Comment by codebytere** [comment]
Please see [Chromium 62 Board](https://github.com/electron/electron/projects/6) and [Chromium 63 Board](https://github.com/electron/electron/projects/7) for current work around upgrading to C62 and then to C63.
