### ISSUE TITLE
No touch keyboard with webview on Windows 10.

### ISSUE THREAD

**Issue by VincentFTS** [electron/electron#11928]
Electron version: 1.8.2
Operating system: Windows 10

### Expected behavior

On a windows 10 touch screen (tablet mode), when touching an input tag in a webview, the windows 10 touch keyboard appears.

### Actual behavior

The keyboard does not appear.

### How to reproduce

  $ git clone https://github.com/VincentFTS/electron-quick-start.git -b webview-touch-keyboard-issue
  $ npm install
  $ npm start

**Comment by fatganz** [comment]
I see this ticket is quite old. Are there any workarounds available?

**Comment by matthiasg** [comment]
I actually went ahead and code two windows executables to open and close the keyboard when I want (triggered by focusin event). 

https://github.com/matthiasg/show-hide-windows-10-touchkeyboard

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by jeremydelacasa** [comment]
Hello @VincentFTS, did you find a solution?

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by appskitchen** [comment]
Hello @sofianguy, I see this issue on my development which has electron 4.0.0 and windows 10 1803 in  panasonic cf33 toughbook when in screen is detached/tablet mode. The touch keyboard appears in IE though. Seems a serious issue.

**Comment by VincentFTS** [comment]
Unfortunately, I have no more touch screen to test… Sorry.

**Comment by valeprog7** [comment]
it was a bug of Chrome([Bug](https://bugs.chromium.org/p/chromium/issues/detail?id=497381)) it has been resolved with chrome 73 (Electron 5.x.x)

**Comment by electron-triage** [comment]
Closing this as it is reported fixed in the above comment. Please upgrade to a later version of Electron. We would be happy to reopen if this is still an issue in a later version.
