### ISSUE TITLE
Msys2 support

### ISSUE THREAD

**Issue by glmdgrielson** [electron/electron#11924]
* Electron version: Er...
* Operating system: Windows 7

So apparently MSYS2 has its own value for `sys.platform`.

### Expected behavior

'linux' or 'win32' would be suitable.

### Actual behavior

```python
KeyError("msys",)
```

### How to reproduce

1. Get MSYS2
2. Attempt to run ./script/build.py.
3. Get to where `lib.config` is imported.
4. Oops...

**Comment by kwonoj** [comment]
Interesting, I'm using msys2 + zsh all time for building Electron on windows (`./script/build.py`) and haven't seen this so far.

**Comment by glmdgrielson** [comment]
Try running this command:
```sh
python -m pdb ./script/lib/config.py
```
That's where I see the error.

**Comment by glmdgrielson** [comment]
And I just found an even worse one: It fails on the bootstrap! More specifically, it fails to update `clang`:
```
/c/electron/script/update-clang.sh
Trying to download prebuilt clang
/c/electron/script/update-clang.sh: line 58: CDS_FULL_URL: unbound variable
None
Traceback (most recent call last):
  File "./script/bootstrap.py", line 282, in <module>
    sys.exit(main())
  File "./script/bootstrap.py", line 55, in main
    update_clang()
  File "./script/bootstrap.py", line 191, in update_clang
    execute_stdout([os.path.join(SOURCE_ROOT, 'script', 'update-clang.sh')])
  File "/c/electron/script/lib/util.py", line 184, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['/c/electron/script/update-clang.sh']' returned non-zero exit status 1
```

**Comment by kwonoj** [comment]
nothing, bootstrap / build just works. I have some confident your system configuration need proper environment configuration to point windows build toolsets. I never saw those failure from first time I build electron.

**Comment by glmdgrielson** [comment]
So you aren't using the MSYS2 Python, you're using a Windows build from a different location. I think that might be the issue. That would be a good thing to document, wouldn't it?

**Comment by kwonoj** [comment]
could be, but I think current documentation already describes sufficiently on windows toolchain need to rely on win32 specific. i.e `The solution is to use the Win32 Python to execute the bootstrap script` (https://electronjs.org/docs/development/build-instructions-windows#assertion-failed-handle-activecnt--0) while it is written for other error cases though.

**Comment by glmdgrielson** [comment]
But they will get this error **_first_**. I'd be willing to try to find an appropriate solution myself if need be, because the build script immediately checks the platform before doing anything. So a user might try to build this with the Python they have installed and it fails immediately for an obtuse reason. And you already did it for MinGW...

**Comment by kwonoj** [comment]
I don't have strong around to add docs or not, it's just my opinion. Core Electron team may have better suggestion around.

**Comment by miniak** [comment]
I don't think MSYS2 is a supported build environment. We've also switched to a completely new GN based build system in Electron 4.
