### ISSUE TITLE
"A javascript error occured in the main process, cannot read property 'send' of undefined."

### ISSUE THREAD

**Issue by pikvik** [electron/electron#11935]
I have a node-electron desktop app which I have packaged for **Mac** using electron-builder. It packages perfectly fine but on the first launch, it throws this error. The error doesn't show on relaunch, only on the first launch.
Also this error arose after i installed usb-detection into my project.

Versions:
Node - 9.2.0
Electron-builder - 19.49.2

![screen shot 2018-02-15 at 5 57 12 pm](https://user-images.githubusercontent.com/18361946/36314411-ca431dd2-135a-11e8-818a-2e5e3b96b19c.png)

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
