### ISSUE TITLE
Security issue :  Prototype Pollution (Affecting hoek package, versions <5.0.3)

### ISSUE THREAD

**Issue by jy95** [electron/electron#11930]
Electron version: 1.82
```
Introduced through: p4ng-client@jy95/p4ng-client#HEAD › electron@1.8.2 › electron-download@3.3.0 › nugget@2.0.1 › request@2.83.0 › hawk@6.0.2 › boom@4.3.1 › hoek@4.2.0 
Remediation: No remediation path available.
Introduced through: p4ng-client@jy95/p4ng-client#HEAD › electron@1.8.2 › electron-download@3.3.0 › nugget@2.0.1 › request@2.83.0 › hawk@6.0.2 › sntp@2.1.0 › hoek@4.2.0 
Remediation: No remediation path available.
Introduced through: p4ng-client@jy95/p4ng-client#HEAD › electron@1.8.2 › electron-download@3.3.0 › nugget@2.0.1 › request@2.83.0 › hawk@6.0.2 › cryptiles@3.1.2 › boom@5.2.0 › hoek@4.2.0 
```
### Overview
[hoek ](https://github.com/hapijs/hoek) is a Utility methods for the hapi ecosystem.

Affected versions of this package are vulnerable to Prototype Pollution. The utilities function allow modification of the Object prototype. If an attacker can control part of the structure passed to this function, they could add or modify an existing property.

### Remediation
Upgrade `hoek` to version 5.0.3 or higher.

### References
[HackerOne Report](https://hackerone.com/reports/310439)
[Synk](https://snyk.io/vuln/npm:hoek:20180212)

**Comment by codebytere** [comment]
Closing as this has now been fixed.
