### ISSUE TITLE
More & more cryptomining ads = sluggish performance (disable hardware acceleration option?)

### ISSUE THREAD

**Issue by alph43oss** [electron/electron#11932]
* Electron version: All
* Operating system: All

### Expected behavior

Smooth performance.

### Actual behavior

Sluggish/choppy navigation.

### How to reproduce

Turn on a miner and try using the application.

**Comment by codebytere** [comment]
In order for us to be able to look into what you're experiencing here, we're going to need a lot more information. 

what is "the application"? 
by what means are you "turning on a miner"? 

We'll need clear, descriptive steps that allow us to reproduce your issue in a way that allows us to see what might be causing sluggishness, and then we can investigate. feel free to @ me in a follow-up comment once you've done that!

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our [comment](https://github.com/electron/electron/issues/11932#issuecomment-366139825). With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
