### ISSUE TITLE
process.env.APPDATA not always the same value.

### ISSUE THREAD

**Issue by EoinAviation** [electron/electron#11942]
* Electron version: 1.6.2
* Operating system: Windows 10 (64-bit)

### Expected behaviour
When calling `process.env.APPDATA`, it should return only **one of the following at any time**:
`"C:\Users\{username}\AppData\Roaming"`
or
`"C:\Users\{username}\AppData\Roaming\{ApplicationName}"`

### Actual behaviour

Sometimes when Electron loads, `process.env.APPDATA` will return `"C:\Users\{username}\AppData\Roaming"`, and **some other times, it will return** `"C:\Users\{username}\AppData\Roaming\{ApplicationName}"`.

Electron can't seem to make up its mind on which string it should be returning.

Using a `try{}catch(e){}` block in my situations _can_ solve the issue.

### How to reproduce

Call `process.env.APPDATA`.

Repo can be found here:
[https://github.com/EoinAviation/VATPAC-ATIS-Generator-V2](url)

**Comment by MarshallOfSound** [comment]
@EoinAviation The value of `process.env.APPDATA` is not configured by Electron afaik rather set by Windows where it would depend on the environment of your machine.  If you wish to get the appData directory for your application you should use

```js
app.getPath('userData')
```

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
