### ISSUE TITLE
Open every link in a new window in electron

### ISSUE THREAD

**Issue by denigada** [electron/electron#11951]
Iam using the below code to open a link in a new electron window:

`$('body').on('click', '.openlink', function () {
    var url = 'https://www.google.com' + this.id;
    window.open(url,"_blank","height=650,width=1000,frame=true,show=true");
});`

However, when I click the button again, the other page opens in the same window that google.com opened. How can I open new button clicks on **new windows every time** ?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
