### ISSUE TITLE
After Packaging on first launch error occurring !!

### ISSUE THREAD

**Issue by pikvik** [electron/electron#11952]
I have made an anti virus electron app . All runs smoothly and fine in dev. But after packaging and installing on first launch attached error pops up. 
![screen shot 2018-02-15 at 5 57 12 pm](https://user-images.githubusercontent.com/18361946/36362887-7008898c-155e-11e8-88b0-6cb3db9f9ded.png)

**Comment by MarshallOfSound** [comment]
You have already raised an issue identical to this one (#11935) and were informed that this is not the correct place to ask for help with errors occurring in your code that are not caused by bugs in Electron itself.  Please ask in the linked community channels in the referenced issue.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
