### ISSUE TITLE
Is Node bundled with Electron?

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#11962]
Does Electron come bundled with Node? I have Node 7.9.0 installed on my machine, and I just updated my Electron version to 1.8.2.

When I start my app and log `process.versions.node`, I get `8.2.1`, but when I run `node -v` from the root app folder, I get `7.9.0`. So is there no need to update my Node? Does it automatically update when updating Electron?

**Comment by brenca** [comment]
Think of it as `node` being embedded inside the `electron`. That effectively means that your `node` installation is independent from the `node` that is inside `electron` - you don't even need to have `node` installed.

**Comment by brenca** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
