### ISSUE TITLE
Issue with creating custom Undo functionality

### ISSUE THREAD

**Issue by p-v** [electron/electron#11971]
* Electron version: 1.8.2
* Operating system: Windows 10

### Expected behavior
If we want to add a custom functionality for `Undo` in `Menu`, we create a template like this,
 ```
 const template = [
    {
      label: 'Edit',
      submenu: [
        { label: 'Undo', accelerator: 'CmdOrCtrl+Z', click: menuTrigger },
        { role: 'cut', accelerator: 'CmdOrCtrl+X' },
        { role: 'copy', accelerator: 'CmdOrCtrl+C' },
        { role: 'paste', accelerator: 'CmdOrCtrl+V' },
        { role: 'toggledevtools' },
      ],
    },
  ];
  const menu = Menu.buildFromTemplate(template);
  Menu.setApplicationMenu(menu);

```
So there is an input field where we can enter random text, on pressing `Ctrl+Z`, it is expected that the function `menuTrigger` be called and the text is not altered.  

### Actual behavior
This works perfectly fine on Mac but has a problem on Windows. Instead of calling the `menuTrigger`, it goes on to undo the changes in the input field, irrespective of the current focus. `menuTrigger` function is called only if there are no undo actions to be performed on the input field.

### How to reproduce
The case is easily reproducible on windows, by adding an input field and creating a menu template.
It can be found by cloning [this repo](https://github.com/p-v/electron-quick-start)

- Type something in the input field
- Press Ctrl+Z
- Type something again
- Click on the button next to the input field
- Press Ctrl+ Z

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
