### ISSUE TITLE
disable security-warnings not working

### ISSUE THREAD

**Issue by patriciussanctus** [electron/electron#11970]
* Electron version: 1.8.2
  * Operating system: macOS 10.13.2
  
how works ELECTRON_DISABLE_SECURITY_WARNINGS variable?!

i'm trying use any possible combination and could not disable warning.
```
Electron Security Warning:
This renderer process has Node.js integration enabled and attempted to load remote content.
This exposes users of this app to severe security risks.
```
<img width="892" alt="2018-02-20 13 00 02" src="https://user-images.githubusercontent.com/16253399/36417822-018226ae-163e-11e8-81bf-81427c6eb78a.png">
 
when i look at the compiled source, i have a feeling that it was this warning no check any variable ```ELECTRON_DISABLE_SECURITY_WARNINGS``` or ```shouldLog``` which I saw in the commit

<details/>
  <summary>Screenshot</summary>
  <img width="672" alt="2018-02-20 13 01 12" src="https://user-images.githubusercontent.com/16253399/36418162-143896ec-163f-11e8-80ab-9a9600f7a3fa.png">
</details>

**Comment by qazbnm456** [comment]
> The warnings are only emitted if the binary's name is **electron**, indicating strongly that a developer is looking at the console. - https://github.com/electron/electron/pull/11810

Also, you can better understand the implementation from [these lines](https://github.com/electron/electron/blob/d586ef2f39d650f117054f32a523fd9786087e9f/lib/renderer/security-warnings.js#L11-L45).

**Comment by patriciussanctus** [comment]
@qazbnm456 i'm trying insert these lines in start of index of main process, rendererer process and webpack starter:

```
window && (window.ELECTRON_DISABLE_SECURITY_WARNINGS = true)
window && (window.ELECTRON_ENABLE_SECURITY_WARNINGS = false)
process.env.ELECTRON_DISABLE_SECURITY_WARNINGS = true
process.env.ELECTRON_ENABLE_SECURITY_WARNINGS = false
```

all this was not working =(
and I quickly tried find mentioned above lines, and not finded. This code seems to be missing in electron.asar of my package electron@1.8.2 from yarn...

**Comment by qazbnm456** [comment]
@patriciussanctus Because the 1-8-x branch doesn't cherry-pick that PR, there's no way to disable the warning currently for now. Maybe you can raise up another PR to cherry-pick https://github.com/electron/electron/pull/11810 into 1-8-x branch.

**Comment by smotaal** [comment]
Getting the same issue with 2.0.0-beta.1... For now I will just 😱:

```js
    const { warn } = console;
    console.warn = (...args) => {
      /^%cElectron Security Warning/.test(args[0])
        || Reflect.apply(warn, console, args);
    };
```

**Comment by bluenote10** [comment]
According to the docs it should be possible to disable the security warning by either `process.env` or the window object:

> You can force-enable or force-disable these warnings by setting ELECTRON_ENABLE_SECURITY_WARNINGS or ELECTRON_DISABLE_SECURITY_WARNINGS on either process.env or the window object.

However things like `mainWindow["ELECTRON_DISABLE_SECURITY_WARNINGS"] = "true"` or `mainWindow["ELECTRON_DISABLE_SECURITY_WARNINGS"] = true` don't seem to work for me (similar to what @patriciussanctus reported).

Can anyone confirm if disabling it via the window object actually works?

**Comment by crosshj** [comment]
In the hopes of being helpful, I'd like to add the following.

This fails to disable warnings because (elsewhere) this false(boolean) becomes "false"(string) which coerces to true.
```
process.env.ELECTRON_ENABLE_SECURITY_WARNINGS = false;
process.env.ELECTRON_DISABLE_SECURITY_WARNINGS = true;
```

This works.
```
delete process.env.ELECTRON_ENABLE_SECURITY_WARNINGS;
process.env.ELECTRON_DISABLE_SECURITY_WARNINGS = true;
```

Disclaimer:  I use electron only for local web development and do not release electron apps.  I would prefer to see warnings, but only web warnings.  I do not recommend turning off security warnings.
