### ISSUE TITLE
shell.openExternal opens in background on Microsoft Edge

### ISSUE THREAD

**Issue by ffsross** [electron/electron#11989]
When using shell.openExternal to open an external website, the website is opened in the background if the default browser is set to "Microsoft Edge". This poses a problem if the user is in full screen, as they may be unaware that the link has actually opened.

* Electron version: 1.7.11 & 1.8.2
* Operating system: Windows 10. Fall Creators Update

### Expected behavior

When clicking on a link to be opened externally, the default browser (Microsoft Edge) opens the link and brings the browser to the foreground. Even with the optional parameters of { activate = true }, the browser opens in the background. 

### Actual behavior
Microsoft Edge opens in the background.

### How to reproduce
1. Set default browser to Microsoft Edge
2. Open any link with the shell.openExternal command.
3. Observer Microsoft Edge opens behind the electron app.

**Comment by charleshimmer** [comment]
+1 this is also happening on version 1.8.4 of electron

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by ffsross** [comment]
I have tested on 2.0.0, and 4.0.1 and the issue still persists.

**Comment by TylerLeonhardt** [comment]
This issue hurts so much :( I don't have an electron dev environment setup but it's very easy to repro in  VSCode. Open VSCode on Windows and open the Integrated Terminal (`ctrl`+ ```) and make sure you're using PowerShell.

Run this:

```
Get-Process | Out-GridView
```

which will open a WPF-based window behind VSCode.

**Comment by linonetwo** [comment]
It's broken in MacOS too https://github.com/electron/electron/issues/18293

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by ffsross** [comment]
I have tested again, and it still occurring on electron 8.0.1.
![1lQjFSubjV](https://user-images.githubusercontent.com/15163777/75059727-6a15e680-5492-11ea-9211-b44f95e2329f.gif)

**Comment by fds2610** [comment]
on Win10 with electron 2.0.1 and Firefox this issue still remains.
my ling gets opened in a FF tab in background.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
