### ISSUE TITLE
Porting devtools-remote to electron

### ISSUE THREAD

**Issue by natew** [electron/electron#11983]
* Electron version: 1.8.0
* Operating system: OSX High Sierra

### Expected behavior

Relaying devtools to another instance should be possible.

### Actual behavior

I can get it to relay from Chrome, but not Electron.

### How to reproduce

https://github.com/natew/remote-debug

```
git clone git@github.com:natew/remote-debug.git
```

You'll have to load the provided extension into a blank Electron window, and then...

```
npx debug-apps
```

Which opens a Puppeteer window and (should) let you debug the remote electron window.

What happens now is it connects just fine, but doesn't seem to load anything. If I manually load the extension into my Chrome browser though, I can get it to work just fine.

My questions to help me fix it is:

- Is there an easier way to debug extensions through Electron? In chrome I can open the background.html and hard refresh it / interact with it. In Electron it's a black box.
- Where do I find the API's Electron supports? I need to know if it can handle: `chrome.debugger.onEvent`, `chrome.debugger.sendCommand`, and basically `chrome.debugger.*` stuff.

**Comment by natew** [comment]
Found out about the `--remote-debugging-port` which lets me debug it, and also circumvents the need for it :)

**Comment by natew** [comment]
Actually, I am curious. I have my background process loading in a devtools extension but I can't seem to figure out any event that fires at all. I can't get the tabId basically. Looking at other examples they seem to work though.

Do you have to have a panel process as well as background in electron? Any place to look and see how this all works?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
