### ISSUE TITLE
Sourcemap Stepping Incorrect in v1.8.2

### ISSUE THREAD

**Issue by Slapbox** [electron/electron#11984]
I'd guess that this is an issue with Chromium itself, but since it is plaguing Electron 1.8.2 I figured I'd post it here. I spent several days trying to pin down the issue, ruling out Babel and, as best I could, Webpack, as the cause.

I can only guarantee this to be the case when packaging with Webpack, as I have not tested with other setups.

**Example:** http://recordit.co/rHKX3quofA

I will update with a way to reproduce this shortly.

| Software         | Version(s) |
| ---------------- | ---------- |
| Electron     |  1.8.2
| Node             | 8.9.1
| npm/Yarn         | 1.3.2 (yarn)
| Operating System | Windows 7 x64

This issue affects at least the following settings for  `devtool`
- inline-source-map
- inline-cheap-source-map

____

A similar issue (can set breakpoints, but they are not honored) affects at least the following settings:

- eval-source-map

**Comment by kwonoj** [comment]
Isn't this webpack side issue? webpack's sourcemap has known issues around stepping break point, like umbrella tracking issue https://github.com/webpack/webpack/issues/3165 / and individual issue like https://github.com/webpack/webpack/issues/4844 . Does electron shows particular difference compare to same version of chromium?

**Comment by Slapbox** [comment]
There are differences in stepping between Electron 1.7.11 and 1.8.2 that I can't pin on webpack, though yes, webpack has tons of known sourcemap issues that the devs seem uninterested in fixing.

I don't have a configuration that I can run on Chromium, only on an older version of Electron.

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR.
