### ISSUE TITLE
Electron segfaults on Ubuntu Bionic

### ISSUE THREAD

**Issue by scottnonnenberg** [electron/electron#11982]
* Electron version: 1.7.11
* Operating system: Ubuntu Bionic (soon to be 18.04)

### Expected behavior

Normal application launch

### Actual behavior

segfault

### How to reproduce

1. Install Ubuntu Bionic
2. Download Signal Desktop from here: https://signal.org/download/ (current build is 1.3.0)

You can also get this to happen by installing the Slack client https://slack.com/downloads/linux (current build is 3.0.5; not sure what version of Electron this is built on)

Originally reported here: https://github.com/signalapp/Signal-Desktop/issues/2048

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.
