### ISSUE TITLE
Can not copy text in inspector unless app has cut/copy/paste menu items.

### ISSUE THREAD

**Issue by greggman** [electron/electron#11998]
* Electron version: 1.8.2
* Operating system: macOS 10.13.3

### Expected behavior

It seems like you should be able to copy text in the devtools using Cmd-C *regardless of whether or not the app itself has those keys assigned as menu items*

### Actual behavior

Cmd-C does nothing (apparently you have to add menu items to get this to work). My app as no need of Copy so those keys are not assigned and no menu is added. The normal app keys do not affect the devtools, why should Cmd-C be any different? In other words pressing Cmd-F in devtools will start a search even though my app has no menu for Cmd-F. Similarly it seems like Cmd-C should copy when devtools has the focus regardless of what my app is doing.

### How to reproduce

```
git clone -b cmd-c-not-working https://github.com/greggman/electron-quick-start.git
cd electron-quick-start
npm install
npm start
```

Then try to copy something in devtools by pressing Cmd-C. Nothing happens. Notice that Cmd-F works even though there is no Cmd-F menu item and even though the app is trapping all keypresses. The point being it seems like Electron's devtools shouldn't rely on the App's setup for basic functionality. That works in Chrome because a webpage can't change the App's menus but in Electron arguably Electron's devtools should be checking for Cmd-C/Cmd-X/Cmd-V in some other way, maybe the same way it's checking for Cmd-F.

**Comment by nikita-graf** [comment]
`Cmd+F` works because it's implemented natively in Chromium dev tools:
 https://cs.chromium.org/chromium/src/third_party/WebKit/Source/devtools/front_end/main/Main.js?l=494 

For some reason there is no support for `Cmd-C/Cmd-X/Cmd-V` in the `Console` component:
https://cs.chromium.org/chromium/src/third_party/WebKit/Source/devtools/front_end/console/ConsoleView.js?l=157

**Comment by greggman** [comment]
There's no support on Chrome because it's not needed in Chrome as webpage can't change the menus so it just happens to work via the menu accelerators

In Electron though that's not the case. An app gets to choose the which menu items to have and whether or not to even have a menu. As such it seems like it would be a good idea for the devtools for electron to patch in support for Cut/Copy/Paste keys so that regardless of the type of app you're creating cut/copy/paste work in the devtools?

**Comment by nikita-graf** [comment]
> As such it seems like it would be a good idea for the devtools for electron to patch in support for Cut/Copy/Paste keys so that regardless of the type of app you're creating cut/copy/paste work in the devtools?

I agree it's a good idea to have these hotkeys enabled by default for devtools, but it could possibly break existing applications that have complex logic for hotkeys.
<details>
  <summary>Here is how paste action could become duplicated</summary>

Apply this diff to your example and try to paste into the console  

```diff
diff --git a/main.js b/main.js
index a073b88..f9b1dc3 100644
--- a/main.js
+++ b/main.js
@@ -25,6 +25,9 @@ function createWindow () {
           accelerator: 'Command+Q',
           click() { app.quit(); },
         },
+        {
+          role: 'paste'
+        }
       ]
     }
   ]);
@@ -39,6 +42,15 @@ function createWindow () {
     protocol: 'file:',
     slashes: true
   }))
+  mainWindow.webContents.on('devtools-opened', () => {
+    mainWindow.webContents.devToolsWebContents.executeJavaScript(`
+      window.addEventListener('keydown', function (e) {
+        if (e.keyCode === 86 && e.metaKey) {
+          document.execCommand('paste');
+        }
+      });
+    `);
+  });
   mainWindow.webContents.openDevTools();
 
   // Open the DevTools.
```
</details>

<br>

Maybe better to add an optional support for these hotkeys? Something like `mainWindow.webContents.devToolsWebContents.enableEditHotkeys()`.

**Comment by greggman** [comment]
I see your point.  Yes, that sounds like a reasonable solution.

**Comment by ckerr** [comment]
@nikita-graf, :+1: on having a standardized way of doing this.

Anyone want to roll a patch for it? :smile:

**Comment by pronebird** [comment]
Hotkeys and right click stopped working in Mojave 😢

**Comment by Magistern** [comment]
Also, CMD+ Q will not quit the Electron Application if focus is on devtools (I have a very small application that only shows the devtools and no window at all.)

**Comment by maxfarseer** [comment]
It works for me in `3.0.6` version

**Comment by Magistern** [comment]
Perfect. Works here too. Version `3.0.7`

**Comment by codebytere** [comment]
Closing as this seems to have resolved.
