### ISSUE TITLE
net::ERR_INSECURE_RESPONSE with underlying ERR_CERTIFICATE_TRANSPARENCY_REQUIRED error

### ISSUE THREAD

**Issue by vulture** [electron/electron#11997]
* Electron version: 1.8.2
* Operating system: Windows 8.1

Trying to load from this one specific host appears to fail with net::ERR_INSECURE_RESPONSE (and, if you dig down to the underlying reason, it ends up being ERR_CERTIFICATE_TRANSPARENCY_REQUIRED). Specifically, an example url: https://d3aqoihi2n8ty8.cloudfront.net/actions/mrdestructoid/dark/static/100/2.png

The issue does NOT occur in Electron 1.8.2beta3.
The issue DOES occur in Electron 1.8.2beta5 and 1.8.2 release.
So, it broke somewhere in between there. I didn't try 1.8.2beta4, but hopefully this provides a very narrow window to help track down the issue. :)

If you flip between Electron versions to test this, I've noticed you may need to F5 to flush/repro behavior as the previous load may have cached the result.(?)

Note: Up-to-date Chrome loads this URL with a warning in devtools:
`The SSL certificate used to load resources from https://d3aqoihi2n8ty8.cloudfront.net will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.`
I don't know if this is at all related, but considering Electron 1.8.2 is Chrome 59, I feel like if it is, maybe some patch got pulled in a little early?

**Comment by vulture** [comment]
1.8.2beta4 is broken as well. So, this definitively broke between 1.8.2beta3 (working) and 1.8.2beta4 (not working).

**Comment by vulture** [comment]
Did some more investigating...

libchromiumcontent\src\net\cert\ct_policy_enforcer.cc is returning CERT_POLICY_NOT_DIVERSE_SCTS. It seems that verified_scts has only 1 SCT while either (1) 4 are needed, (2) has_valid_nonembedded_sct && has_valid_google_sct && has_valid_nongoogle_sct, (3) has_embedded_google_sct && has_embedded_nongoogle_sct, (4) maybe more. In this case, it's falling through to (3) and since there is only one SCT in verified_scts, it's impossible to have both a google and nongoogle SCT:
```
  const base::Time kDiverseSCTRequirementStartDate =
      base::Time::FromInternalValue(INT64_C(13080182400000000));
  if (issuance_date >= kDiverseSCTRequirementStartDate &&
      !(has_embedded_google_sct && has_embedded_nongoogle_sct)) {
    // Note: This also covers the case for non-embedded SCTs, as it's only
    // possible to reach here if both sets are not diverse enough.
    return ct::CertPolicyCompliance::CERT_POLICY_NOT_DIVERSE_SCTS;
  }
```
In this case, it seems that there were actually two SCTs provided in the cert, first was from "Google 'Skydiver' log" and the second one failed with SCT_STATUS_LOG_UNKNOWN (0x00000001). So it gets removed from verified_scts, leaving only one. Specifically, that SCT gets failed in net::MultiLogCTVerifier::VerifySingleSCT:
```
  // Assume this SCT is untrusted until proven otherwise.
  const auto& it = logs_.find(sct->log_id);
  if (it == logs_.end()) {
    DVLOG(1) << "SCT does not match any known log.";
    AddSCTAndLogStatus(sct, ct::SCT_STATUS_LOG_UNKNOWN, output_scts);
    return false;
  }
```
The SCT's log_id doesn't appear in logs_, so it fails.

**Comment by vulture** [comment]
It actually seems like 1.8.2beta3 also only has one passing SCT, so I'm confused how it succeeds downstream :/

**Comment by vulture** [comment]
So after a lot more investigating, it turns out that `IsBuildTimely()` in `libchromiumcontent\src\net\cert\ct_policy_enforcer.cc` is returning false starting with 1.8.2beta4 but not with 1.8.2beta3. My new hypothesis is that
```
bool IsBuildTimely() {
  const base::Time build_time = base::GetBuildTime();
  // We consider built-in information to be timely for 10 weeks.
  return (base::Time::Now() - build_time).InDays() < 70 /* 10 weeks */;
}
```
doesn't actually compute time delta properly when year rolled over to 2018. :|

**Comment by vulture** [comment]
Okay I think I figured out part of the issue:
IsBuildTimely() is false for 1.8.2beta3 because it was built on Dec 04 2017 (79 days is >70 days)
IsBuildTimely() is true for 1.8.2beta4 because it was built on Jan 22 2018 (30 days is <70 days)

Different logic is used when the build is too old:
```
  if (ct_verify_result_.cert_policy_compliance !=
          ct::CertPolicyCompliance::CERT_POLICY_COMPLIES_VIA_SCTS &&
      ct_verify_result_.cert_policy_compliance !=
          ct::CertPolicyCompliance::CERT_POLICY_BUILD_NOT_TIMELY &&
      transport_security_state_->ShouldRequireCT(
          host_and_port_.host(), server_cert_verify_result_.verified_cert.get(),
          server_cert_verify_result_.public_key_hashes)) {
    server_cert_verify_result_.cert_status |=
        CERT_STATUS_CERTIFICATE_TRANSPARENCY_REQUIRED;
    return ERR_CERTIFICATE_TRANSPARENCY_REQUIRED;
  }

  return OK;
```
Specifically, this only checks ShouldRequireCT() when not CERT_POLICY_BUILD_NOT_TIMELY (i.e., when build IS timely, it checks CT). Otherwise, it returns OK, and something else handles CERT_POLICY_BUILD_NOT_TIMELY. Hex editing the embedded build date back a couple months works around the issue. Obviously that's not a great fix, but, well... :P

Can someone else comment on why that certificate failed in the first place, but electron NOT being a timely build allows it to succeed? That I suppose would be the real fix. Is it a bad cert? Note that this is for *.cloudfront,net, which would be a pretty big CDN to have an issue on.

**Comment by deepak1556** [comment]
Thanks for the findings, I am merging this to https://github.com/electron/electron/issues/11969 since they are the same issue.
