### ISSUE TITLE
`-webkit-app-region: drag` blocks event listeners attached to `window`

### ISSUE THREAD

**Issue by jakofranko** [electron/electron#11994]
Hi there, I've found a rather bizarre bug I believe. I am only seeing this on my Windows 10 machine, and do not see this on my Mac.

* Electron version: 1.8.2
* Operating system: Windows 10

### Expected behavior

Events attached to the window via `window.addEventListener` should trigger regardless of whether or not the CSS property `-webkit-app-region: drag` is attached to an element that is "in front" of the window, and this behavior should be consistent across all platforms.

### Actual behavior

On Windows 10, if an element has the CSS property `-webkit-app-region: drag` set, window events are not triggered over that element.

A strange work-around: nesting a child element with the CSS property `-webkit-app-region: no-drag` will allow events to be triggered again.

### How to reproduce

Here is a link to small demo: https://github.com/jakofranko/electron-bug-11994

Simply

```
$ npm install
$ npm start
```

Play around with commenting out the `-webkit-app-region: no-drag` property for the `#inner` element.

Again, this behavior does not seem to be exhibited on Mac OS builds.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
