### ISSUE TITLE
console.log does not log to the dev tools console window

### ISSUE THREAD

**Issue by bughit** [electron/electron#11990]
* Electron version: debug version built from master (7e2f7602c1d3f383bb859f4af96e74e683a49d8e)
* Operating system: win7 sp1 x64

### Expected behavior

`node --inspect-brk -e console.log('hello')` logs to stdout and the dev tools console
so one expects electron to do the same

### Actual behavior

electron with attached dev tools only logs to stdout

### How to reproduce

`console_log.js` with `console.log('hello');`
`electron.exe --inspect-brk console_log.js`

**Comment by Hammster** [comment]
This is not a bug, main process and render process have separate output channels. 

The render process prints your console.log() to the dev tools while a console.log() in the main process outputs to stdout. According to your example the behaviour of the electron executable works as intended, since you run the `console.log('hello')` in the main process.

**Comment by bughit** [comment]
"dev tools" is referring to the external chrome dev tools inspecting/debugging the electron main process.

**Comment by natew** [comment]
+1, seeing this as of 2.0, wasn't happening in 1.8.

**Comment by bughit** [comment]
@zcbenz 

On windows, console.log is redirected to process.log 
```js
if (process.platform === 'win32') {
  // Redirect node's console to use our own implementations, since node can not
  // handle console output when running as GUI program.
  var consoleLog = function (...args) {
    return process.log(util.format(...args) + '\n')
  }
```
which is implemented in AtomBindings::Log
```c++
#if defined(OS_WIN)
    process.SetMethod("log", &AtomBindings::Log);
#endif
```
which only logs to stdout
```c++
// static
void AtomBindings::Log(const base::string16& message) {
  std::cout << message << std::flush;
}
```
so can't the new console.log simply call both, the orginal console.log and process.log?

```js
if (process.platform === 'win32') {
  // Redirect node's console to use our own implementations, since node can not
  // handle console output when running as GUI program.
  const origLog = console.log
  var consoleLog = function (...args) {
    origLog.call(console, ...args);
    return process.log(util.format(...args) + '\n')
  }
```

**Comment by zcbenz** [comment]
@bughit The problem with original implementation is, it would throw exception when stdout is not available. We should probably find out which call is actually printing the message to devtools and then invoke it.

**Comment by bughit** [comment]
@zcbenz I actually got around to trying my suggestion a while ago and saw that it was double logging, though I did not see exceptions, should have posted that.

**Comment by natew** [comment]
This is painful, how are people debugging electron apps without repl working? Any workarounds?

**Comment by Ancinek** [comment]
I have never experience this until today. What a weird behaviour :/

**Comment by noe132** [comment]
Any update on this? Is there any workaround?

**Comment by Maxmaxmaximus3** [comment]
help

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by natew** [comment]
Still happens on 6 and 5 for me.

**Comment by jpoppe** [comment]
It also still not working on version 6 for me, bug seems obvious and is easy to replicate.

**Comment by bughit** [comment]
@sofianguy Does the author of the bug need to reply to clear this need-info?

Yes, it's still present in 6.

**Comment by CynicalBusiness** [comment]
I can confirm this is happening in v6.0.x (namely v6.0.7) on Windows 10 (1809).

It also appears to _not_ happen to `console.info`, but other console methods (like `log`, `warn`, and `error`) are afflicted. What makes that one special?

For example:
```javascript
// index.js
console.log('log')
console.info('info')
```
```
.\node_modules\.bin\electron --inspect index.js
> 'info'

node --inspect index.js
> 'log'
> 'info'
```

Serves as a work-around I guess, but still annoying.

**Comment by Sentero-esp12** [comment]
Same. Electron version v8.2.5. `console.info` works, but `console.log` doesn't.

**Comment by m4heshd** [comment]
I'm on v11.1.1 and the issue is still here.

**Comment by MasterIO02** [comment]
Can confirm this issue is still here, but only on Windows for me, not on Linux. I can log nothing in the browser, no matter what I try with console.log, console.info, using '' instead of ``, the only thing that can log something for me on Windows is myConsole that logs in the nodejs process, but that's not what I want.

**Comment by deepak1556** [comment]
@m4heshd for issue with Electron 11 please update to `11.2.0` which got fixed by https://github.com/electron/electron/pull/27102
