### ISSUE TITLE
JSON dependency data incomplete for recent versions

### ISSUE THREAD

**Issue by zeke** [electron/electron#12006]
The https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/index.json file is incomplete for the following Electron versions:

- `2.0.0-beta.1` (Cheng fixed this one manually today on S3)
-  `1.8.2-beta.2`
-  `1.8.2-beta.1`

To Do

- [x] Manually fix the JSON file on S3 for `1.8.2-beta.2` and `1.8.2-beta.1`
- [x] Update the publish process to prevent this in future releases.

cc @jkleinsc @zcbenz

**Comment by jkleinsc** [comment]
#12003 fixed the publish process for master

**Comment by jkleinsc** [comment]
#12014 fixes the publish process for 2-0-x

**Comment by jkleinsc** [comment]
The JSON file has been updated for the 1.8.2-beta releases.

**Comment by zeke** [comment]
Boom. Thank you.
