### ISSUE TITLE
cannot electron-rebuild against the latest electron 2.0.0-beta.1

### ISSUE THREAD

**Issue by corvinrok** [electron/electron#12019]
* Electron version: 2.0.0-beta.1
* Operating system: Windows 7

### Expected behavior

electron rebuild should be able to recompile my project against the latest electron headers.

### Actual behavior

electron rebuild cannot build against the newest version of electron. It gives the following error:
` Error: Could not detect abi for version 2.0.0-beta.1 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron`

### How to reproduce

- install the latest electron
- npm install your project
- try to rebuild your latest electron project against the headers, using electron-rebuild.
- It fails every time with the above error (see Actual behavior).

**Comment by MarshallOfSound** [comment]
This was fixed in a newer version of `node-abi`, ensure you have the latest version of all your dependencies 👍
