### ISSUE TITLE
2.0.0-beta.1 changelog link for "Changed a macOS thing" points to Windows thing

### ISSUE THREAD

**Issue by mhuggins** [electron/electron#12012]
* Electron version: 2.0.0-beta.1
* Operating system: All

### Expected behavior

Clicking "Changed a Mac thing" in the [changelog](https://electronjs.org/releases#2.0.0-beta.1) should link to a Mac-related GitHub issue or PR.

### Actual behavior

Clicking "Changed a Mac thing" in the [changelog](https://electronjs.org/releases#2.0.0-beta.1) links to a Windows-related GitHub PR.

### How to reproduce

1. Navigate to https://electronjs.org/releases#2.0.0-beta.1
2. Scroll down the the "macOS" header (or click here: https://electronjs.org/releases#macos)
3. Click the link next to "Changed a macOS thing. #123"

**Comment by zeke** [comment]
Thanks for reporting. Working on it: https://github.com/electron/electron-releases/issues/6

**Comment by zeke** [comment]
Fix coming in https://github.com/electron/electronjs.org/pull/1135

**Comment by zeke** [comment]
Fixed! https://electronjs.org/releases#2.0.0-beta.1

**Comment by mhuggins** [comment]
Quick turnaround, thanks guys. 😄
