### ISSUE TITLE
Regression: Invisible menu items no longer work via their accelerator keys

### ISSUE THREAD

**Issue by stephenmartindale** [electron/electron#12025]
With Electron `1.8`, it was possible to create an *invisible* menu item in the application menu and, assuming it was still enabled, it could be invoked via its accelerator key. This provided a mechanism for creating application-wide shortcut keys that were independent from content.

For example, this menu-item template worked just fine:

                {
                    visible: false,
                    accelerator: "F12",
                    click: () => {
                        mainWindow.webContents.openDevTools({ mode: "detach" });
                    }
                },

Since upgrading to `Electron2.0.0-beta.1`, this no longer works. Instead, I have to make the menu item visible and give it a name in order for it to be triggered by its accelerator key:

                {
                    visible: true,
                    label: "Developer Tools",
                    accelerator: "F12",
                    click: () => {
                        mainWindow.webContents.openDevTools({ mode: "detach" });
                    }
                },

Is this just a regression or is this by design? If it is by design, is there any way to achieve window-level shortcut keys without resorting to nasty `keydown` and `keyup` handlers on the content level?

**Comment by codebytere** [comment]
@stephenmartindale what platform was this on?

**Comment by stephenmartindale** [comment]
It was Windows 10.0.16299, x64.

Yours Faithfully,
*Stephen Martindale*

+49 162 577 2166
stephen.c.martindale@gmail.com

**Comment by abnerlee** [comment]
I can also reproduce this on Windows

**Comment by codebytere** [comment]
i can take a look at this next week!

**Comment by codebytere** [comment]
@stephenmartindale i believe this happened as a result of some separator filtering we implemented; i'll see if i can open a PR to remedy this side effect.
