### ISSUE TITLE
quotes are improperly encoded in javascript execution

### ISSUE THREAD

**Issue by senica** [electron/electron#12021]
I'm using a library called RiotJS for an electron app. The code works well in a browser, but in electron, quotes break things. I thought this was computer/keyboard issue, but I've tried to rule out everything I can before posting. I also posted in RiotJS as I'm not sure if the issue is somehow there or in Electron. I have a hard time thinking it's riot since it works fine in a browser.

More information can be found at this issue posted in Riotjs https://github.com/riot/riot/issues/2547

* Electron version: "electron": "^1.8.2"
* Operating system: Mac OS High Sierra 10.13.2

### Expected behavior

It should render javascript quotes like the chrome browser does

### Actual behavior

It seems like quotes are incorrectly encoded and breaks javascript.

### How to reproduce

Clone this repo: `https://github.com/senica/electrion_riot_broken.git`

- `git clone https://github.com/senica/electrion_riot_broken.git`
- `cd electrion_riot_broken`
- `npm install`
- `./node_modules/.bin/electron .`

You'll get the debugger and you can see the error in the console. Sometimes the weird characters don't show unless you refresh the app `CMD + R`

**Comment by nikita-graf** [comment]
I tried to run your example with unminified version of `riotjs` and it worked. However, with minified version, I'm getting the same error. 
There is a difference in compiled code between two versions of library. Minified version produces an incorrect code.

Compiled with production
<img width="392" alt="electronriot 2018-03-03 12-50-01" src="https://user-images.githubusercontent.com/2078870/36932902-868a19fa-1ee1-11e8-89b4-0ee798a44669.png">

Compiled with minified
<img width="392" alt="electronriot 2018-03-03 12-54-37" src="https://user-images.githubusercontent.com/2078870/36932931-0d9a7f48-1ee2-11e8-8e01-5bca28c281f7.png">

**Comment by senica** [comment]
Oh wow. I'm sorry that you had to go through that to find an error on a third-party library. I really appreciate you taking the time to help narrow down the issue. 

I'll let the other guys know.

**Comment by GianlucaGuarini** [comment]
@nikita-graf electron loads the page contents with a default encoding different from `utf-8`. https://github.com/riot/riot/issues/2547#issuecomment-371616225 solves the issue but this is clearly an electron bug
