### ISSUE TITLE
App crashes on startup when run from samba share

### ISSUE THREAD

**Issue by pierssquaredpaper** [electron/electron#12023]
* Electron version: 1.8.2
* Operating system: macOS High Sierra 10.13.3

### Expected behavior
The application should start successfully when running from a samba network share.

### Actual behavior
The application crashes on startup with the following error report

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Trace/BPT trap: 5
Termination Reason:    Namespace SIGNAL, Code 0x5
Terminating Process:   exc handler [0]

### How to reproduce
This behaviour was found using a locally produced private application, but has been replicated when trying to run Atom from a Samba share. 

- A server should be set up which shares part of its file system using Samba. In the test case this was done on a Centos box in the smb.conf file the following share config was made
        [public]
        comment = public server
        path = /home
        public = yes
        writable = yes
        browseable = yes
        force user = root
        force group = root
        valid users = root,user
- On the Mac connect using Finder / Go / Connect to Server, and then type in the server address cifs://<smbhost>
- Copy Atom.app to the shared folder
- Double click Atom.app

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
