### ISSUE TITLE
in DevTools console: Electron Security Warning (Insecure Content-Security-Policy)

### ISSUE THREAD

**Issue by danyadev** [electron/electron#12035]
* Electron version: v2.0.0-beta.1
* Operating system: Windows 7 Ultimate x64

When I open the console I see this warning:
![image](https://user-images.githubusercontent.com/35631027/36630221-f1776b3c-1973-11e8-823b-dd6942e08471.png)
 In previous versions I did not notice this

**Comment by qazbnm456** [comment]
> The warnings are only emitted if the binary's name is **electron**, indicating strongly that a developer is looking at the console. - https://github.com/electron/electron/pull/11810

Also, you can better understand the implementation from [these lines](https://github.com/electron/electron/blob/d586ef2f39d650f117054f32a523fd9786087e9f/lib/renderer/security-warnings.js#L11-L45).

**Comment by danyadev** [comment]
![image](https://user-images.githubusercontent.com/35631027/36631073-77249a30-1982-11e8-9445-c0e87179e9e6.png)

ok, close

**Comment by duttaditya18** [comment]
Hey. I am running Electron by WSL and see this warning. Any help?

**Comment by movingelectrons** [comment]
ditto, WSL and would like this warning to go away please

**Comment by MarshallOfSound** [comment]
@movingelectrons If you follow the security recommendation in the warning it will stop showing.

**Comment by TomasHubelbauer** [comment]
@MarshallOfSound the https://electronjs.org/docs/tutorial/first-app tutorial runs into this warning. Is the tutorial not compliant with the security checklist? I ran into this issue immediately when picking up Electron and so far in my search I have not found a satisfactory solution, see #19775.

**Comment by alexeypetrushin** [comment]
Same issue. Tutorial is wrong. As it is - the <script> tag is not executed, and when you remove security meta tag - it works but start showing that warning.

**Comment by Slapbox** [comment]
`electron-remote` is required by `electron-spellchecker` and in some inputs any time I press a keyboard key it opens a new devTools window just to show me that warning. It would be really great to be able to workaround this, unless there's some plan for built in spellchecking.

**Comment by TomasHubelbauer** [comment]
@slapbox Check https://stackoverflow.com/a/57553252/2715716 to see how to disable this warning.

**Comment by Slapbox** [comment]
Thanks but that doesn't resolve my issue. My issue is within an `npm` package, `electron-remote`. My only option is to fork multiple npm packages, including native dependencies, or deal with a devtools window popping up for every key I press in an input field.
