### ISSUE TITLE
webContents.id is not valid in 'web-contents-created' event callback

### ISSUE THREAD

**Issue by timfish** [electron/electron#12036]
* Electron version: 1.8.2
* Operating system: Windows 10

```typescript
app.on('web-contents-created', (e, contents) => {
  console.log('wc1: ' + contents.id);

  setImmediate(() => {
    console.log('wc2: ' + contents.id);
  });
});

app.on('ready', () => {
  const window = new BrowserWindow({
    width: 800,
    height: 600,
    titleBarStyle: 'hidden',
  });

  window.loadURL(
    url.format({
      pathname: path.join(__dirname, 'index.html'),
      protocol: 'file:',
      slashes: true,
    }),
  );
});
```
outputs:
```shell
wc1: 0
wc2: 1
```
Whereas I would expect `id` to stay the same and be valid straight away and output:
```shell
wc1: 0
wc2: 0
// or
wc1: 1
wc2: 1
```

**Comment by ibash** [comment]
Seeing the same thing on macos too (on electron 1.8.2). This is also true of the browser-window-created event and BrowserWindow, the id is not set at the time the event is called.

**Comment by miniak** [comment]
This issue no longer present in Electron >3. It still reproduces in Electron 2, which is not supported anymore.
