### ISSUE TITLE
webview: allowpopups=false doesn't generate warning if window.open is used

### ISSUE THREAD

**Issue by perlun** [electron/electron#12031]
* Electron version: 1.8.2
* Operating system: macOS

### Expected behavior

\<webview src="file:myfile.html"\> with an HTML file that performs `window.open` should emit a console warning if `allowpopups` is `false` (the default value.)

### Actual behavior

\<webview src="file:myfile.html"\> with an HTML file that performs `window.open` will fail silently (no warnings emitted.)

This is not a major issue in any way, but it would be more user-friendly to emit a warning in these cases (to tell me, as a developer, what I have missed - enabling the `allowpopups` setting in the code where `webview` is being used.)

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
