### ISSUE TITLE
Does Electron support Windows Message WM_COPYDATA(0x004A)?

### ISSUE THREAD

**Issue by Swordfish1990** [electron/electron#12034]
* Electron version: 1.8.2
* Operating system: windows 10

### Expected behavior

I tried to use win.hookWindowMessage to receive WM_COPYDATA  message from a DLL. But it seems not work. This is my code:
`
  mainWindow.hookWindowMessage(74,(wParam,lParam) =>{
    console.log(lParam)
    return true
  })`
Then I tried another Message WM_NCLBUTTONUP. It works well.
`mainWindow.hookWindowMessage(514, (wParam,lParam) =>{
    console.log('mouseup')
  })`
So I guess it might be that electron doesn't support it. Is that true?

**Comment by Swordfish1990** [comment]
Sorry . I made a mistake. I passed a `hwnd` returned by `getNativeWindowHandle` in Electron. But this `hwnd` whose type is `Buffer` can not be used in Winodws API `SendMessage`. So I use  Winodws API `FindWindow` to get the correct `hwnd` by window's name,It works!

**Comment by CTianXing** [comment]
@Swordfish1990 now I also need to use win.hookWindowMessage to receive window custom messages from a DLL or .node. I used the right hwnd,but SendMessage or PostMessage did't work for me, I want to know how to send windows custom messages to Electron, thank you very much!

**Comment by hillguo** [comment]
@CTianXing  do you resolve it? i need help

**Comment by sa05169** [comment]
@Swordfish1990  I am using hwnd returned by getNativeWindowHandle() for Win32 API SendMessage() and it is working. I am able to send keyboard events in electron using C++ addons, yes. Perhaps you were trying SendMessage() on external windows (belonging to other processes), however SendMessage() only works for the process's own created windows.
