### ISSUE TITLE
Electron 2.0.0-beta.1: Contextmenu click handler is not invoked anymore

### ISSUE THREAD

**Issue by bpasero** [electron/electron#12039]
* Electron version: 2.0.0-beta.1
* Operating system: macOS 10.13.3

### Expected behavior

A context menuitem click handler is invoked when clicked.

### Actual behavior

Not what is expected.

### How to reproduce

The following code when run from a renderer does not execute the click handler on click anymore:

```javascript
var electron = require("electron");
var menu = new electron.remote.Menu()
menu.append(new electron.remote.MenuItem({ label: 'MenuItem1', click: function () { console.log('item 1 clicked') } }))
menu.append(new electron.remote.MenuItem({ type: 'separator' }))
menu.append(new electron.remote.MenuItem({ label: 'MenuItem2', click: function () { console.log('item 2 clicked') }, type: 'checkbox', checked: true }))

window.addEventListener('contextmenu', function (e) {
    e.preventDefault()
    menu.popup({ window: electron.remote.getCurrentWindow() })
}, false)
```

//cc @zcbenz not sure if related to the context menu refactoring (removal of sync)

**Comment by codebytere** [comment]
@hey bpasero unfortunately this issue pre-dates `2.0.0beta-1`, subscribe to https://github.com/electron/electron/issues/11818 for updates
