### ISSUE TITLE
shell.openExternal fails in renderer in 2.0.0-beta.1

### ISSUE THREAD

**Issue by alchen** [electron/electron#12038]
Not sure where to start debugging this issue.

* Electron version: 2.0.0-beta.1
* Operating system: macOS 10.13.3

### Expected behavior

`shell.openExternal` should open the link in an external browser.

### Actual behavior

- openExternal runs fine in `main` process but fails in `renderer` process. I.e. the link is not opened.
- the same code works fine when reverted to 1.8.2

### How to reproduce

Call `shell.openExternal` in the renderer process.

**Comment by bpasero** [comment]
@alchen can you provide more information how you use that method with an example that fails for you? I tried this out and could not reproduce (macOS 10.13.3, are you sure you are on macOS 10.3.13?)

**Comment by alchen** [comment]
Oops, yes, it was a typo and I'm on the same OS version as you.

It was a function triggered by the context menu. I thought it wouldn't matter though, I'll try to come up with a reproducible example now (or find out what I did wrong).
