### ISSUE TITLE
macOS: LoginHelper is included in non-MAS build

### ISSUE THREAD

**Issue by bpasero** [electron/electron#12041]
* Electron version: 2.0.0-beta.1
* Operating system: macOS 10.13.3

### Expected behavior

The non-MAS build of Electron should not include the LoginHelper. My understanding is that the helper is only needed for MAS specific APIs and should not be distributed for the non-MAS build of Electron. 

### Actual behavior

The LoginHelper is included.

![image](https://user-images.githubusercontent.com/900690/36644088-813beb9e-1a55-11e8-969d-4bf3cbca9843.png)

**Comment by jkleinsc** [comment]
@bpasero it was an issue with our release process.  The release builds for 2.0.0-beta.1 and 2.0.0-beta.2 have been corrected.

**Comment by bpasero** [comment]
@jkleinsc thanks a lot 👍
