### ISSUE TITLE
electron on Raspbian doesn't show index.html conent

### ISSUE THREAD

**Issue by mstoelzle** [electron/electron#12055]
* Electron version: 1.8.2
* Operating system: Raspbian (v9 (stretch))

I'm trying to use electron on Raspbian with the official Raspberry Touchscreen (7 inch) (Raspberry 3B):

1. I cloned the electron-quick-start (https://github.com/electron/electron-quick-start)
2. I installed electron and started it:
`npm install`
`export DISPLAY=:0`
`npm start`
3. The window launches, but it doesn't show any content from the index.html
4. I tried to change the background color and that worked

I've tested it also on my macOS Laptop, and everything worked fine.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
