### ISSUE TITLE
[Feature]: Option to get download speed in `downloadItem` class

### ISSUE THREAD

**Issue by Sibiraj-S** [electron/electron#12066]
* Electron version: v1.8.2

### Expected behavior

It would be nice to have a feature to show the speed at which the file is downloaded in class `downloadItem`

**Comment by MarshallOfSound** [comment]
The speed of a download can be calculated by polling the `getReceivedBytes` API while the download is in progress.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by Sibiraj-S** [comment]
Calculating isn't a problem, I was saying about having it natively

**Comment by ShitalJumbad** [comment]
Actually, it is nice to have a feature to accurately show the download(downloadItem) speed as well. Not sure why it is closed?
