### ISSUE TITLE
setVibrancy crashes in beta 2.0

### ISSUE THREAD

**Issue by tommoor** [electron/electron#12068]
* Electron version: 2.0.0.beta-1
* Operating system: 10.13.3 Beta (17D34a)

### Expected behavior

Electron should not crash when using `browserWindow.setVibrancy`

### Actual behavior

Electron crashes intermittently. Crash report:
https://gist.github.com/tommoor/90b7b3db53a32f9dd165bb234b9f2d9d

**Comment by codebytere** [comment]
@tommoor do you have a more specific reproduction? What string value did you pass into `setVibrancy()`? How often does it crash? 

Currenrtly unable to reproduce.

**Comment by tommoor** [comment]
This was using the following code from the renderer process. It definitely didn't happen immediately which is why I added the word intermittently - it could be that calling the method twice results in the crash? The same code runs fine in 1.8.

```javascript
import { remote } from "electron";
const currentWindow = remote.getCurrentWindow();
currentWindow.setVibrancy("light");
```

**Comment by smotaal** [comment]
I was getting a crash (probably in 2.0.0-beta.1) but now the only problem is the default titlebar does not render correctly.

<img width="426" alt="screenshot 2018-03-06 21 00 57" src="https://user-images.githubusercontent.com/849613/37069551-df23378e-2181-11e8-9eef-d49d37bd39f0.png">

Wow! on my display, the titlebar will sometimes look solid black with two square insets where the rounded corner should appear, but the screenshot falsely captures it a nice shade of gray, but at least still somewhat faulty.

Is the default titlebar is not supported with vibrancy, and if so, should Electron warn or default to the next best option?

**Comment by tommoor** [comment]
It's bad huh? I also reported the display artifacts on the original PR that introduced this, here:

https://github.com/electron/electron/pull/11886#issuecomment-368703468

**Comment by smotaal** [comment]
Was the titlebar flickering between opaque, latent image trails, then solid black?

also — try dragging the PNG through, you'll notice it captures as true transparent (ie alpha 0) so obviously those are different (likely GPU artifacts from some mishandled buffers) in nature than the square inset corners.

**Comment by MarshallOfSound** [comment]
Just sent up #12157 to fix a few of these weird rendering issues, I couldn't reproduce the screenshots you folks have but I managed to repro a few components of them in isolation so things should work a bit better after that PR 👍

**Comment by alexeykuzmin** [comment]
> Just sent up #12157 to fix a few of these weird rendering issues

@MarshallOfSound can you please cherry-pick the change to the `2-0-x`?

**Comment by alexeykuzmin** [comment]
> @MarshallOfSound can you please cherry-pick the change to the 2-0-x?

It's quite late in Sydney already, I'll just do it myself =)

**Comment by alexeykuzmin** [comment]
Please verify the fix in the 2.0.0-beta.3.

**Comment by kube** [comment]
This is still buggy.

If `titleBarStyle` is set to `hidden` or `hiddenInset`, calling `setVibrancy` will make the app crash at first or second time.

It works once sometimes.

Here is a minimal example repo: https://github.com/kube/electron-vibrancy-issue-example

**Comment by kube** [comment]
@alexeykuzmin @MarshallOfSound Sorry for the ping, but this issue should be reopened.

**Comment by albinekb** [comment]
Using 
```
new BrowserWindow({
      minWidth: width,
      minHeight: height,
      width: width,
      height: height,
      titleBarStyle: 'hiddenInset',
      frame: false,
      vibrancy: 'ultra-dark',
      backgroundColor: '#00000066',
      alwaysOnTop: true,
    })
```

![image](https://user-images.githubusercontent.com/5027156/40028038-11aec4f2-57dd-11e8-84f2-02f7b493a1a0.png)


I get a crash report when launching, but the window still shows correctly.

**Comment by tommoor** [comment]
@alexeykuzmin can we reopen? This is still an issue.

**Comment by mlabod** [comment]
Still an issue over here too, crashes on quit, when vibrancy is activated. 
Tested with `2.0.2`

**Comment by davej** [comment]
Also see #12726 which seems to be the same bug. I added a repo to that issue which recreates the bug but unfortunately, @codebytere and @MarshallOfSound don't seem to be able to reproduce the issue. :-/

We might need to do a bit more digging to figure out why that is.

Might be useful to know what hardware and macOS version people are running.

Seeing a crash on: macOS 10.12.6, MacBook Pro (Retina, 15-inch, Mid 2014), 2.2 GHz i7, Intel Iris Pro 1536 MB.

I've also had many people reporting crashes on other hardware (2017 Macbook Pro running 10.12.6 and 2013 Macbook Air running 10.12.6)

**Comment by macisi** [comment]
- MacBook Pro (Retina, 15-inch, Mid 2015) 
- electron 2.0.2
the app will crash when exit

**Comment by codebytere** [comment]
This is a duplicate of the above https://github.com/electron/electron/issues/12726 which is open, please move to that issue for updates
