### ISSUE TITLE
Select client certificate not including all certificates in list

### ISSUE THREAD

**Issue by ryanjemerson** [electron/electron#12069]
* Electron version: 1.7.11
* Operating system: Windows 10

### Expected behavior

A certificate with specific name ie "Intranet User" for client authentication is selected out of a list for a user to validate for sign in

### Actual behavior

The appropriate certificate is not included in the list of available certificates even though it is installed in the certificate store locally

### How to reproduce

Here is the code for finding the certificate we need for signing into a resource loaded in a browserwindow in Electron

app.on('select-client-certificate', (event, webContents, url, list, callback) => {
  log.log(list);
  let cert = list.find(cert => cert.issuerName.includes('Company Intranet Level User'));
  event.preventDefault();
  callback(cert);
});

The following code works on my machine but when used on others, all other certs except this one are logged. I can confirm that the certificate is installed by checking the certificate contents in Windows and also signing in through Chrome/Firefox/Edge works (by selecting the certificate and validating that way).

**Comment by ckerr** [comment]
Hi @ryanjemerson, thanks for reporting this! Have you tested the latest stable release, 1.8.2, to see if this issue persists?

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
