### ISSUE TITLE
Global install fails

### ISSUE THREAD

**Issue by limikael** [electron/electron#12063]
* Electron version: 1.8.2
* Operating system: Xubuntu 17.10

### Expected behavior

Electron should install globally when I do `sudo npm install -g electron`.

### Actual behavior

It fails with the following message. It says permission denied, but I don't think the problem is a permission problem actually, since I do run it as root.

```
micke@micke-LIFEBOOK-S751:~$ sudo npm install -g electron
/usr/bin/electron -> /usr/lib/node_modules/electron/cli.js

> electron@1.8.2 postinstall /usr/lib/node_modules/electron
> node install.js

/usr/lib/node_modules/electron/install.js:47
  throw err
  ^

Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/electron/dist'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.8.2 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.8.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/micke/.npm/_logs/2018-02-27T02_07_41_617Z-debug.log
```

**Comment by MarshallOfSound** [comment]
Check out the `EACCESS` section of the troubleshooting guide.

https://github.com/electron/electron/blob/8e51659237640f0292ebca174c050608df72b02e/docs/tutorial/installation.md#troubleshooting
