### ISSUE TITLE
ES6 modules from file scheme fail to load in 2.0.0-beta.1

### ISSUE THREAD

**Issue by CynicalBusiness** [electron/electron#12065]
* Electron version: 2.0.0-beta.1
* Operating system: Ubuntu 16.04

Note:
This is a follow-up of #12011 specifically about a failure to load using the `file://` scheme. The issue was closed after electron/libchromiumcontent#459, but the resulting patch to `lcc` was reverted. This leaves the original issue to still be a problem as the modules indeed still do not load.

### Expected behavior
Loading an ES6 module from `file://` should load the module.

### Actual behavior
ES6 modules from `file://` receive an error:

```
Failed to load module script: The server responded with a non-JavaScript MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.
```

Modules loaded from HTTP servers (that correctly serve the MIME type, anyway) work fine.

### How to reproduce
1. Create a module script
2. Create a view that is loaded from `file://`
3. Use `type="module"` in the script tag to import the script into the view.
4. Error appears in the dev tools console when trying to load.

**Comment by MarshallOfSound** [comment]
Instead of opening new issues we should re-open the original one (which I have now done). Closing this out
