### ISSUE TITLE
Web view  Unload event not getting Triggered.

### ISSUE THREAD

**Issue by Chakradhar18** [electron/electron#12075]
* Electron version:  1 . 8.1 
* Operating system: Windows

### Expected behavior
On Closing the electron app webview unload event should get triggered.

### Actual behavior
Webview unload event not getting triggered.

### How to reproduce
1. Create  app which will display the thirdparty website .
2. Ensure that website do some task on Unload.
3. launch and close the Electron app.
Expected unload should get trigerred.

**Comment by codebytere** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our [comment](https://github.com/electron/electron/issues/12075#issuecomment-369332346). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
