### ISSUE TITLE
Still Hi/LowDPI screens font size issue 

### ISSUE THREAD

**Issue by akontsevich** [electron/electron#12076]
* Electron version: 1.7.9
* Operating system: openSUSE Linux Tumbleweed

### Expected behavior
Want to see normal font sizes like in other GTK+2/3 applications

### Actual behavior 
Fonts scaling works wrong on my 52 DPI 42" FullHD (1920x1080) TV monitor. Font size is set to 17 with 52 DPI set and all UI elements and fonts looks ok in all KDE and GTK+ applications like
- Gimp
- Inkskape
- LibreOffice, etc

Only in applications which use electron fonts in menus and dialogs are very big:
- Skype
- Chromium
- VS Code
- riot-web
- etc

If I set font to 11-13, electron applications looks fine, but in this case any other KDE or GTK applications have very small fonts, which unable to work with. Please fix. Thanks!

**Comment by akontsevich** [comment]
Issue also exists in Electron 1.8.x, 2.0.1, applications:
- Skype
- VS Code
- Chromium

Fonts in other GTK3 applications is normal.

**Comment by akontsevich** [comment]
This bug could be caused by wrong Qt/KDE scaling as I run electron applications under KDE: https://github.com/sddm/sddm/issues/894. Need to check how it works under Gnome/Cinnamon/Mate.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by akontsevich** [comment]
@sofianguy, yest exists:

VS Code: 1.37.0
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.2.3-1-default

Think also exists in 5th version

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by akontsevich** [comment]
Yes, bug still exists in Chrome, therefore in Electron too. Workaround is to change screen resolution to default value - 96 DPI, not to monitor original - 52 DPI.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
