### ISSUE TITLE
Enhancement: Add a DesktopIcon level BrowserWindow type

### ISSUE THREAD

**Issue by karaggeorge** [electron/electron#12073]
From the BrowserWindow docs:
>The desktop type places the window at the desktop background window level (kCGDesktopWindowLevel - 1). Note that desktop window will not receive focus, keyboard or mouse events, but you can use globalShortcut to receive input sparingly.

Using that generates something like this:
<img width="564" alt="screen shot 2018-02-27 at 15 31 32" src="https://user-images.githubusercontent.com/8822835/36764768-272acab4-1bfc-11e8-93d3-00eeab3adcfb.png">

I am trying to create a window that will behave exactly the same way as that but will be placed on top of the icons. After reading a lot into it, it turns out that for that to happen, the level has to be `kCGDesktopIconWindowLevel`. Other than that, the behavior of the `desktop` matches perfectly.

The goal is to be able to create a `BrowserWindow` that will take up the entire screen and will have a background image the same as the user's wallpaper. Since this will be placed over the icons, but won't trigger any events, it effectively clears the user's desktop from icons for a short time (screen recording). 

I tried cloning the repo and adding the new option, but I couldn't get it to quite work right. I have never really worked with C++ before. If this would be small enough to implement, it would be greatly appreciated.

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
