### ISSUE TITLE
Intercept each http request and access the raw response data

### ISSUE THREAD

**Issue by andrewheadricke** [electron/electron#12074]
I'm having a hard time following the documentation on if its possible to intercept every request made by the BrowserWindow and write the response out to a text file while at the same time rendering the webpage normally in the BrowserWindow.

I'm not sure if to use `session` or `protocol` or `chrome.devtools` is the right approach.

So for example if I was to loadURL("http://google.com"), it would fire an event for each asset downloaded so that I could write them all to disk, so things like images, css, js, html.

Its important to have the BrowserWindow download and render the webpage as per normal because it will be encountering further assets to download as javascript code is executed after the initial load.

And finally, if this is possible, I will need to attach these "intercept" events to a `nodeIntegration = false` BrowserWindow.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
