### ISSUE TITLE
Invalid symlink is causing code signing to fail validation.

### ISSUE THREAD

**Issue by ryanbourneuk** [electron/electron#12081]
When packaging a Mac application for distribution, code signing with a valid Developer ID certificate, packaging fails as the bundled `Electron Framework.framework` contains an invalid symlink to `Libraries`. Packaging against the latest non-beta, v1.8.2, does not contain the symlink and passes validation.

* Electron version: 2.0.0-beta.1 installed with `yarn`
* Operating system: macOS High Sierra 10.13.3

### Expected behavior

MacOS distributable should be signed with the specified Developer ID certificate when packaged.

### Actual behavior

An astray corrupted symlink to `Libraries` within `Electron Framework.framework/Versions/A/Libraries/` is causing code signing validation to fail. As mentioned above, this only happens when targeting the beta version of Electron.

### How to reproduce

Using `electron-builder`, build a distributable `.app` Electron application with code-signing enabled using a Developer ID certificate. You should see this output towards the end of execution:

```
• signing file=<path to .app> identityName=<certificate name> identityHash=<certificate hash>
Error: Command failed: codesign --verify --deep --strict --verbose=2 <path to .app>
--prepared:<path to .app>/Contents/Library/LoginItems/Electron Login Helper.app
--prepared:<path to .app>/Contents/Frameworks/<app name> Helper.app
--validated:<path to .app>/Contents/Library/LoginItems/Electron Login Helper.app
--validated:<path to .app>/Contents/Frameworks/<appname> Helper.app
--prepared:<path to .app>/Contents/Frameworks/Squirrel.framework/Versions/Current/.
--prepared:<path to .app>/Contents/Frameworks/<appname> Helper NP.app
--validated:<path to .app>/Contents/Frameworks/Squirrel.framework/Versions/Current/.
--validated:<path to .app>/Contents/Frameworks/<appname> Helper NP.app
--prepared:<path to .app>/Contents/Frameworks/<appname> Helper EH.app
--validated:<path to .app>/Contents/Frameworks/<appname> Helper EH.app
--prepared:<path to .app>/Contents/Frameworks/Mantle.framework/Versions/Current/.
--validated:<path to .app>/Contents/Frameworks/Mantle.framework/Versions/Current/.
--prepared:<path to .app>/Contents/Frameworks/ReactiveCocoa.framework/Versions/Current/.
--validated:<path to .app>/Contents/Frameworks/ReactiveCocoa.framework/Versions/Current/.
--prepared:<path to .app>/Contents/Frameworks/Electron Framework.framework/Versions/Current/.
<path to .app>: No such file or directory
```

It seems to successfully validate, up to `Electron Framework.framework/Versions/Current/` where it is unable to continue after reaching the invalid symlink.

Obviously, this version of Electron is a beta, so issues are understandable, but it'd obviously be good to get this checked out! Thank you! :)

**Comment by MarshallOfSound** [comment]
Duplicate #12009
