### ISSUE TITLE
Can't prevent default webview navigation behavior

### ISSUE THREAD

**Issue by orpheus-it-underworld** [electron/electron#12082]
Hi all,

In my Electron app, I capture navigation events from a webview in the main window and display the contents in a second window.

Capturing the event and displaying the selected contents in the second window using ```webview.addEventListener('will-navigate', ...)``` and some renderer->main->renderer ipc works just fine, but I haven't been able to prevent the main window webview from also loading the linked page contents, despite calling ```Event.preventDefault()``` and ```Event.stopPropagation()```. I'm aware of issue #4191 and others that have reported this before, but if there's a fix or a workaround for this problem, I haven't found one.

The following complete code is supposed to ignore all navigation events and leave the original page in place, but instead it replaces it with the navigated page contents every time.

**app.js**:
```
const {app, BrowserWindow} = require('electron')
app.on('ready', () => {
    let win = new BrowserWindow({width: 800, height: 600})
    win.loadURL('file://' + __dirname + '/app.html')
    win.on('closed', () => app.quit())
})
```

**app.html**:
```
<html>
<head>
    <title>Navigate</title>
</head>
<style>.view {width: 100vw; height: 100vh}</style>
<body style="margin: 0">
    <webview class="view" id="view" src="https://electronjs.org/docs/all"></webview>
</body>
<script>
    const webview = document.getElementById('view')
    webview.addEventListener('will-navigate', event => {
        console.log('Preventing navigation to ' + event.url)
        event.preventDefault()
        event.stopPropagation()
    }, false)
</script>
</html>
```

Am I missing something?

Environment:
* Electron version: 1.8.2
* Operating system: Windows 10

**Comment by MarshallOfSound** [comment]
Duplicate #11820 

See https://github.com/electron/electron/issues/11820#issuecomment-362873175 for an explanation

Please note this is also explicitly documented behavior 👍 
https://electronjs.org/docs/api/webview-tag#event-will-navigate

**Comment by orpheus-it-underworld** [comment]
I found an alternative for anyone trying to do the same kind of thing as me. If you ctrl- or shift-click a webview link, you'll get a 'new-window' event on the webview and Chromium won't render the link in the clicked webview. So webview click -> will-navigate -> _your-stuff_ -> Chromium changes webview contents, but webview ctrl-click or shift-click -> new-window -> _your-stuff_ -> Chromium does not change webview contents -- basically the default Chrome browser behavior.
