### ISSUE TITLE
'This' not parsed correctly through remote

### ISSUE THREAD

**Issue by Acidic9** [electron/electron#12089]
* Electron version: v1.8.2
* Operating system: Window 10 64bit

When calling a function within a class (for example, a user-provided callback function) with `this.callbacks.progress.call(this)`, the `this` does not get sent across when using remote.

For example, I have a class like so:

```ts
class MyClass {
    constructor(callbacks = {}) {
        this.callbacks = callbacks
    }

    exec() {
        callbacks.progress.call(this)
    }
}

module.exports = MyClass
```

and in my renderer process, I use `remote.require('./my-class')` to execute the class on the main process.

```ts
const MyClass = require('electron').remote.require('./my-class')

const myClassInstance = new MyClass({
    progress: function() {
        console.log(this)
    }
})
```

I expect the result of the `console.log(this)` to refer to the instance of MyClass, but it instead refers to an instance of `global` (some sort of in-built electron object).

### How to reproduce

I've created a repository which shows with comments in a very simplified version all the issues I'm experiencing.

https://github.com/Acidic9/electron-remote-issues

    $ git clone https://github.com/Acidic9/electron-remote-issues -b master
    $ npm install
    $ npm start || electron .

**Comment by Gvozd** [comment]
@Acidic9 , I also encountered a similar problem, and I'll try to fix it myself

As temp workaround you may bind method queries in render process(and maybe in main)
```js
myClassInstance.exec.bind(myClassInstance)()
// instead myClassInstance.exec()
```

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
