### ISSUE TITLE
childprocess.execFile  can execute an A.app file  in app.asar?

### ISSUE THREAD

**Issue by y489436672** [electron/electron#12092]
* Electron version: 1.8.2
* Operating system: macOS

### Expected behavior

It should be done, I performed A.exe successfully under window under the same directory, and macOS failed to perform A.app failure

### Actual behavior

A.app not found

### How to reproduce
Pack an .app file under the app.asar file
let path = require('path');
const childProcess = require('child_process');
childProcess.execFile(path.resolve(__dirname, 'static/A.app'))

**Comment by MarshallOfSound** [comment]
Tbh I'm surprised a `.exe` worked on Windows.  When packed in an ASAR nothing is spawnable or executable without extracting it first to a temporary location.  If you want to spawn something from inside an ASAR you should pull it out and spawn it from their instead 👍

**Comment by y489436672** [comment]
Sorry, I looked at the document execFile and it will automatically unzip it to the temporary directory when it supports reading binary files.
https://ourcodeworld.com/articles/read/154/how-to-execute-an-exe-file-system-application-using-electron-framework

Extra Unpacking on Some APIs
Most fs APIs can read a file or get a file's information from asar archives without unpacking, but for some APIs that rely on passing the real file path to underlying system calls, Electron will extract the needed file into a temporary file and pass the path of the temporary file to the APIs to make them work. This adds a little overhead for those APIs.

APIs that requires extra unpacking are:

child_process.execFile
child_process.execFileSync
fs.open
fs.openSync
process.dlopen - Used by require on native modules
Fake Stat Information of fs.stat
The Stats object returned by fs.stat and its friends on files in asar archives is generated by guessing, because those files do not exist on the filesystem. So you should not trust the Stats object except for getting file size and checking file type.
Executing Binaries Inside asar Archive
There are Node APIs that can execute binaries like child_process.exec, child_process.spawn and child_process.execFile, but only execFile is supported to execute binaries inside asar archive.

This is because exec and spawn accept command instead of file as input, and commands are executed under shell. There is no reliable way to determine whether a command uses a file in asar archive, and even if we do, we can not be sure whether we can replace the path in command without side effects.

**Comment by y489436672** [comment]
Is it a problem?

**Comment by MarshallOfSound** [comment]
`.app` is not a binary though, the binary is stored somewhere like `MyApp.app/Contents/MacOS/MyApp`

**Comment by y489436672** [comment]
@MarshallOfSound  How do I execute the a.app files in the resource?

**Comment by y489436672** [comment]
I feel like what's wrong with my path?It prompted me not to find the file.

**Comment by danawoodman** [comment]
Is there any documentation related to this statement?

> When packed in an ASAR nothing is spawnable or executable without extracting it first to a temporary location. If you want to spawn something from inside an ASAR you should pull it out and spawn it from their instead 👍

How do I extract this from the asar?

I am attempting to spawn a process for a binary on my system. Everything works fine when running `electron .` but when I use `electron-builder` and install it in my Applications folder, I run into an issue where the call just times out. I assume it is related to being inside the .asar file?

Thanks for any guidance

**Comment by ndtreviv** [comment]
>When packed in an ASAR nothing is spawnable or executable without extracting it first to a temporary location. If you want to spawn something from inside an ASAR you should pull it out and spawn it from their instead 👍

I'm using `asarUnpack` in my electron-builder config. In my case the exe *is* being unpacked into  `C:\Program Files\My Application\resources\app.asar.unpacked\node_modules\myexe.exe\vendor\myexe.exe` but `child-process.spawn` results in it attempting to run the exe from a random temp directory created in `%APPDATA%`. (Not ideal, as my users have blockers that stop executables running from anywhere in `%APPDATA%`.)

Is this still expected behaviour despite asarUnpack? How can I circumnavigate it?!

**Comment by Macrored** [comment]
> Tbh I'm surprised a `.exe` worked on Windows. When packed in an ASAR nothing is spawnable or executable without extracting it first to a temporary location. If you want to spawn something from inside an ASAR you should pull it out and spawn it from their instead 👍

Will the files unzipped into the temporary directory be automatically cleared after the program exits? If it doesn't, is there a way to use code to do it?
