### ISSUE TITLE
electron packager from .app to dmg issue

### ISSUE THREAD

**Issue by dipenpatel235** [electron/electron#12094]
Hello..
i am tring to convert my syncthing.app to installable dmg but getting below error when i am using below command

[root@local ~]# electron-packager ./syncthing.app Syncthing --electron-version=1.8.2
Packaging app for platform linux x64 using electron v1.8.2
Command failed: npm prune --production
npm ERR! Linux 3.10.0-693.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "prune" "--production"
npm ERR! node v6.12.3
npm ERR! npm  v3.10.10
npm ERR! path /tmp/electron-packager/linux-x64/Syncthing-linux-x64/resources/app/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/tmp/electron-packager/linux-x64/Syncthing-linux-x64/resources/app/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/tmp/electron-packager/linux-x64/Syncthing-linux-x64/resources/app/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/electron-packager/linux-x64/Syncthing-linux-x64/resources/app/npm-debug.log

* Electron version: 1.8.2
* Operating system: Centos 7 64 bit

### Expected behavior
must be convert into .dmg 
### Actual behavior
not converted to .dmg and getting above erorr to missing package.json file. but that file present inside .app dir "syncthing.app/Contents/Resources/app/package.json" 

sp some how that file may be not copying from that dir to   '/tmp/electron-packager/linux-x64/Syncthing-linux-x64/resources/app/package.json'
### How to reproduce
1. download this zip (
https://www.dropbox.com/s/zgluzi63hledixo/syncthing-darwin-x64.zip)
2. extract it
3. install electron-packager and electron 
4. electron-packager ./syncthing.app Syncthing electron-version=1.8.2
5. if above 4th step successful then it will generate Syncthing.dmg file but it is giving error in my case

Thanks

**Comment by sethlu** [comment]
@dipenpatel235 Just to make sure if I'm understanding the question correctly, you're trying to put a packaged app into a dmg file?

**Comment by dipenpatel235** [comment]
Yes.

**Comment by sethlu** [comment]
@dipenpatel235 I don't think `electron-packager` is created to do this process.

I'd recommend checking out [`electron-installer-dmg`](https://github.com/mongodb-js/electron-installer-dmg). It's listed among the distributable creators on the `electron-packager` repo readme and should work better for this case.
