### ISSUE TITLE
Tel protocol cannot be registered on Windows

### ISSUE THREAD

**Issue by clusterberries** [electron/electron#12091]
* Electron version: 1.8.2
* Operating system: Windows 10

### Expected behavior

tel: protocol should be registered and the app is in the list of defaults apps for this protocol. 

### Actual behavior

`app.isDefaultProtocolClient('tel')` returns true after registering, but I still can't open the app using tel: link.

### How to reproduce

I have the following code:

```
    if (!app.isDefaultProtocolClient('tel')) {
        app.setAsDefaultProtocolClient('tel');
    }

    if (!app.isDefaultProtocolClient('test')) {
        app.setAsDefaultProtocolClient('test');
    }
```

It allows to open test: link in the application, but nothing changes for tel: link. Also there are only Chrome and Skype in the list of default apps in Windows settings, I don't see my app.

Please note, that the some code seems to work on Mac. OS proposes to open tel: link in the app.
Do I miss something for Windows?

**Comment by clusterberries** [comment]
Update: tel protocol seems to work on windows 7, but doesn't work on windows 8

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by clusterberries** [comment]
Hi @sofianguy! 
I just checked Electron 3.0.10 and 4.0.1. The issue is still reproduced on Windows 10. 
`app.setAsDefaultProtocolClient('tel')` returns `true`, after that `app.isDefaultProtocolClient('tel')` also returns `true`, but this protocol cannot be used. When tel: link is open, Windows proposes to choose application for this type of link, but my application is not in the list.

**Comment by vladimiry** [comment]
See here https://github.com/electron/electron/issues/14108

**Comment by clusterberries** [comment]
@vladimiry thanks, I'll try the workaround described there

**Comment by ramaralo** [comment]
Anyone knows if this is just a `tel` protocol issue?
I'm trying to register a custom protocol for my app, and it doesn't seem to work as well.

`
const appProtocol = 'myapp';
app.setAsDefaultProtocolClient(appProtocol, process.execPath, [path.resolve(process.argv[1])])
`

When opening `myapp://` from the browser it doesn't recognise my app.

Using electron `3.0.1` and `Win 10`

Thanks!

**Comment by clusterberries** [comment]
The issue is still reproduced with Electron 5.0.2

**Comment by clusterberries** [comment]
Also this issue is reproduced on Window 7 if there is already some application assigned for tel: protocol as a default application.
I described it in details here https://github.com/electron/electron/issues/14108#issuecomment-507741313

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
