### ISSUE TITLE
Provide command line option for setting DIST_DIR in create-dist.py

### ISSUE THREAD

**Issue by yzgyyang** [electron/electron#12097]
* Electron version: any
* Operating system: any

### Expected behavior

It would be beneficial if DIST_DIR could be set to a custom path.

### Actual behavior

Currently DIST_DIR is hard-coded, relative to the source.
```
SOURCE_ROOT = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))
DIST_DIR = os.path.join(SOURCE_ROOT, 'dist')
```

**Comment by ckerr** [comment]
@yzgyyang, I'd be OK with making this configurable but it looks like we have several scripts that all hardcode `DIST_DIR` using the same logic, so they would all need to be changed and, if any of the scripts call each other, they'd need to be checked to ensure that everything gets called with this extra parameter.

A less invasive change might be an environment variable and to refactor the scripts to call the same utility function that checks the environment before falling back on `os.path.join(SOURCE_ROOT, 'dist')`.

Maybe a more important question, though, what is the use case you have for wanting this change?

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
