### ISSUE TITLE
dialog.showOpenDialog does not work with network shares on macOS

### ISSUE THREAD

**Issue by greggman** [electron/electron#12107]
* Electron version: 1.8.2
* Operating system: macOS 10.13.3

### Expected behavior

I should be able to see folders inside a network share using `dialog.showOpenDialog`

### Actual behavior

I can't see folders inside a network share

### How to reproduce

```
git clone -b cannot-see-network-folders https://github.com/greggman/electron-quick-start.git
cd electron-quick-start
npm install
npm start
```

An open dialog will appear. 

* Navigate to a network share and try to find content inside. None will appear. 
* Click cancel
* Click "Choose Files" (this is an `<input type="file">` element
* Navigate to a network share and try to find content inside. It will work

Even stranger

* Click cancel
* Click "click to select files/folders"

It will start in the network share showing the contents. Re-navigate to the network share and the contents will not appear

![screenflow](https://user-images.githubusercontent.com/234804/36931560-c5e289a6-1efb-11e8-8f2a-a8319ac0d260.gif)

Since using `<input type="file">` *WORKS IN ELECTRON* so it looks like it's just some flag missing? Maybe I'm just using it wrong although I didn't see anything [in the docs](https://github.com/electron/electron/blob/master/docs/api/dialog.md)

**Comment by apolkingg8** [comment]
I got same issue with same Electron and OSX version. For more information, if I add the network shares folder into "Favorites" in Finder side menu, It works fine.

**Comment by greggman** [comment]
I glanced at the electron code vs chromium and I didn't see anything so I had an idea that maybe it has to do with process permissions? I have no idea which process the dialog opens in. Given it's going through remote I assumed it was opened in the browser process but in any case if I open the dialog directly from the browser process in main.js then it works as expected (can see network shares) so maybe that suggests what the issue is.

**Comment by greggman** [comment]
FYI, both passing the window or not to `showOpenDialog` from the browser process worked (showed network share contents)

**Comment by greggman** [comment]
So, more interesting stuff.

If I delay when I call `dialog.showOpenDialog` in main the problem comes back.

This works (I can see the network share contents)

```
// In main.js (browser process)
function createWindow() {
     ...
    process.nextTick(() => {
      console.log(electron.dialog.showOpenDialog({
        properties: ['openFile', 'openDirectory', 'multiSelections'],
      }));
    });
}
```

where as if I change the code to have a delay then I can't see the contents of the network shares

```
// In main.js (browser process)
function createWindow() {
     ...
    setTimeout(() => {
      console.log(electron.dialog.showOpenDialog({
        properties: ['openFile', 'openDirectory', 'multiSelections'],
      }));
    }, 5000);
}
```

That came up because I thought I'd try working around the issue by calling `showOpenDialog` from main.js but it didn't help.

**Comment by codebytere** [comment]
Fixed by https://github.com/electron/electron/pull/12282

**Comment by greggman** [comment]
Are you sure #12282 is related to this? this is not a bug about Windows UNC paths like \\server\share. It's a bug about completely normal paths.

      /Users/person/foo/bar

vs

      /Volumes/mntpoint/foo/bar

**Comment by greggman** [comment]
Verified that 2.0.0-beta.4 does *not* fix this. Not sure if #12282 made it into beta 4 or not

**Comment by codebytere** [comment]
@greggman you're correct, my bad! reopened.

**Comment by etyp** [comment]
@greggman did you find any work arounds or short term fixes for this one?

**Comment by codebytere** [comment]
@greggman did you check if `2.0.0` stable remedies this?

**Comment by etyp** [comment]
@codebytere is there a PR in any of the 2.x releases that specifically address this? If so, can you point me to that?

**Comment by greggman** [comment]
Seems to work on 2.0.1

**Comment by etyp** [comment]
@greggman weird, it seems like the change in #12282 only affects win32 machines. Why would this change the `/Volumes` prefix problem on darwin?

**Comment by greggman** [comment]
I have no idea. I just know I just tested it and it work. Maybe something else fixed it or maybe I'm just getting lucky.
