### ISSUE TITLE
 Electron White Screen when making an HTTPS

### ISSUE THREAD

**Issue by aminrasouli** [electron/electron#12110]
when i use https to send request electron was crashed and devtools not working
i use this for request:
https://github.com/woocommerce/wc-api-node
in http every thing is ok

![capture](https://user-images.githubusercontent.com/8999374/36934438-a182552a-1efe-11e8-9834-64eb42692c41.PNG)

![capture2](https://user-images.githubusercontent.com/8999374/36934440-a76d1042-1efe-11e8-9c1a-c822c3839e41.PNG)

**Comment by aminrasouli** [comment]
i gave this error on uncaughtException event
`[7036:0304/204427.135:ERROR:CONSOLE(280)] "IndexedDBAgent error: No document for given frame found", source: chrome-devtools://devtools/bundled/re sources/resources_module.js (280)`

**Comment by aminrasouli** [comment]
fixed by updating to electron `1.8.2`

**Comment by amolngt** [comment]
> fixed by updating to electron `1.8.2`

not useful
