### ISSUE TITLE
Electron app's menu on macOS's status bar works incorrectly

### ISSUE THREAD

**Issue by kartikvashistha** [electron/electron#12114]
This is a minor bug in the Mailspring email client, based on Electron. Basically, the Mailspring icon on the status bar doesn't show the quick access menu when in full screen in other apps. It works fine inside the Mailspring app and the desktop. According to the dev, this is an electron bug.
Link to this issue in detail in the Mailsping repo can be found [here](https://github.com/Foundry376/Mailspring/issues/406).

**Comment by ckerr** [comment]
What version of Electron is Mailspring using?

**Comment by kartikvashistha** [comment]
`process.versions.electron`  returns 1.8.2.

**Comment by codebytere** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on, 1.8.2, has been superseded by newer releases. In addition, there are newer branches that supersede that series. It would help us greatly if you could test this issue with the latest version, `3.0.2`

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by kartikvashistha** [comment]
Hi @codebytere this is no longer an issue. Currently, the Mailspring ships with Electron 2.0.2, and as I cannot replicate this issue anymore, I'm closing it.

**Comment by kartikvashistha** [comment]
Hi @codebytere this is no longer an issue. Currently, the Mailspring ships with Electron 2.0.2, and as I cannot replicate this issue anymore, I'm closing it.
