### ISSUE TITLE
Backport a fix for the "Integer overflow with PropertyArray"

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#12115]
The issue: https://bugs.chromium.org/p/project-zero/issues/detail?id=1445
Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=789393
The fix: https://chromium-review.googlesource.com/824167
Affected Chromium versions: All <64.

Affected Electron versions: `master`, `2-0-x`, `1-8-x`, ...
Electron PRs with backports:
 - to Ch63 upg: electron/libchromiumcontent#407
 - to `master`: electron/libchromiumcontent#465
 - to `2-0-x`: electron/libchromiumcontent#463
 - to `1-8-x`: electron/libchromiumcontent#462
 - to `1-7-x`: electron/libchromiumcontent#475

/cc @alespergl

**Comment by bpasero** [comment]
@alexeykuzmin @alespergl is this not being considered to be backported to 1.7.x?

**Comment by alexeykuzmin** [comment]
@bpasero I can create a PR for 1.7.x in about an hour.

/cc @ckerr

**Comment by alexeykuzmin** [comment]
> I can create a PR for 1.7.x in about an hour.

electron/libchromiumcontent#475

**Comment by bpasero** [comment]
@alexeykuzmin thanks
