### ISSUE TITLE
Backport a fix for the "TranslatedState::MaterializeCapturedObjectAt caching bug"

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#12116]
The issue: https://bugs.chromium.org/p/project-zero/issues/detail?id=1446
Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=789394
The fix: https://chromium-review.googlesource.com/828993
Affected Chromium versions: 62, 63

Affected Electron versions: `master`.
Electron PRs with backports:
 - to Ch63 upg: electron/libchromiumcontent#407
 - to `master`: electron/libchromiumcontent#465

/cc @alespergl

**Comment by codebytere** [comment]
@alexeykuzmin closing as both branches now have the fix.
