### ISSUE TITLE
Deprecate getMenuBarHeight on macOS

### ISSUE THREAD

**Issue by pronebird** [electron/electron#12126]
* Electron version: some
* Operating system: macos

### Expected behavior

There is absolutely no need to expose `getMenubarHeight` specifically for macOS since screen provides a `workarea` which already reflects that.

```
$ require('electron').screen.getPrimaryDisplay().workArea
Object {x: 0, y: 22, width: 1440, height: 829}
$ require('electron').screen.getMenuBarHeight()
22
```

**Comment by mohammadalipak** [comment]
I need to know the macOS Dock height for a full-screen app I'm making, to make sure my content doesn't go behind the dock.

This was the only way for me to calculate that as I would do:

```
macOSDockHeight = displayHeight - workAreaHeight - menuBarHeight
```

Can we please add that back in? Or have another way to calculate macOS dock height?

**Comment by pronebird** [comment]
What prevents you from doing the same by taking the `workarea.y`?

**Comment by mohammadalipak** [comment]
That's a great idea. Didn't think of that
