### ISSUE TITLE
Bug: 2.0.0-beta.1 window.open(…) not showing when called from new BrowserWindow({show: false}).show()

### ISSUE THREAD

**Issue by smotaal** [electron/electron#12125]
* Electron version: 2.0.0-beta.1
* Operating system: macOS High 10.13.3 (17D102)

### Expected behavior

When creating a BrowserWindow:

```js
  browserWindow = new BrowserWindow({ show: false });
  browserWindow.once('ready-to-show', () => browserWindow.show());
```

Which show the following:

```html
  <button onclick="() => window.open('…', 'custom-target')">Open</button>
```

Clicking the button should open a "shown" window, regardless of the `show` parameter passed when creating the initial browserWindow.

### Actual behavior

What happens is that the window opens but is not visible.

If instead we modified `main.js` as follows:

```js
  browserWindow = new BrowserWindow();
  browserWindow.hide(); // dynamically hide instead
  browserWindow.once('ready-to-show', () => browserWindow.show());
```

Then the child window created by `window.open(…)` opens and is shown as expected.

### How to reproduce

This is a straightforward scenario:

**main.js**
```js
browserWindow = new BrowserWindow({
  // Disable this in test b
  show: false,
});

// Disable this in test a
browserWindow.hide();

browserWindow.loadURL(`file://${__dirname}/index.html`)

browserWindow.once('ready-to-show', () => browserWindow.show());
```

**index.html**
```html
<script>
  window.open('chrome://gpu', 'chrome-gpu');
</script>
```

But let me know if you can't reproduce it.

**Comment by ckerr** [comment]
Yep, confirmed that both windows are getting an options dict with the same value for `show`.

**Comment by MarshallOfSound** [comment]
This is _kinda_ expected behavior by the Electron `window.open` implementation. All window options are inherited, including the `show` option 🤔

**Comment by smotaal** [comment]
I think of window options more like CSS, certain options should inherit, and other could optionally inherit or simply be manually inherited (ie must be explicitly set to 'inherit' to inherit or set to a new value else always default).

**Comment by smotaal** [comment]
So how would we handle this, assuming I am not showing the initial window because I want to preload certain localStorage WindowState, but then I don't make assumptions about the contents, which would make it potentially buggy to coerce options like show if the page actually opted to not show versus if not show is simply inherited.

**Comment by smotaal** [comment]
Awesome
