### ISSUE TITLE
Support "~" in path of file dialogs

### ISSUE THREAD

**Issue by springmeyer** [electron/electron#1212]
We are seeing that:

```js
            dialog.showSaveDialog({
                 title: 'Save ',
                 defaultPath: '~/Untitled.png',
                 filters: [{ name: typeExtension.toUpperCase(), extensions: [typeExtension]}]
            });
```

May return an incorrect path. For example if the user keeps the default you would expect the filepath returned to be `~/Untitled.png`. Sometimes this is the case and other times it is `/~/Untitled.png`. What we have observed is that it can be replicated:

  - both on OS X and Windows
  - only when the user accepts the dialog window choice quickly

I suspect the bug is due to a race condition in relative path completion. We've found that we can workaround the problem by using an absolute path for the `defaultPath`.

Background at https://github.com/mapbox/mapbox-studio/pull/1236

**Comment by paulcbetts** [comment]
I'm super surprise Tilde works at all on either operating system, it really shouldn't. Tilde is a bash completion.

**Comment by zcbenz** [comment]
The `~` is only meaningful in shells, it doesn't represent a real path, and I don't think we should expand it in atom-shell's dialogs. So I'm closing this as won't fix.

**Comment by zcbenz** [comment]
After looking into this again, I think it is better not to support `~` in file dialogs. The `~` is a shell feature, and also a valid character for filenames, supporting it will make our API have unexpected behaviors when users do want to use `~` as a filename.
