### ISSUE TITLE
Hard to open submenus with pen tap on Windows 10

### ISSUE THREAD

**Issue by funige** [electron/electron#12138]
* Electron version:
after v1.8
* Operating system:
Windows 10

### Expected behavior

When pen tap on application menu, it should work just the same as mouse click.

### Actual behavior

After v1.8, Submenues flash then disappear on pen tap.
I am testing on Surface Pro 3 and Wacom Cintiq. (It never occurs If Cintiq is set to 'ignore Windows ink')

### How to reproduce

    const { app, BrowserWindow, Menu } = require('electron');
    app.on('ready', function() {
      const mainWindow = new BrowserWindow({width: 800, height: 600});
      const applicationMenu = [
        {label: 'menu', 
         submenu: [ // <- really hard to open this with stylus...
          {label: 'submenu1'},
          {label: 'submenu2'}
        ]}
      ];
      const menu = Menu.buildFromTemplate(applicationMenu);
      Menu.setApplicationMenu(menu);
    })

**Comment by setpixel** [comment]
I am experiencing this issue as well. I hope it's not an issue with Chromium.

**Comment by bdrose** [comment]
I am having a problem where the Surface pen causes the file menu to stop working and not expand with touch or a pen tap. This is a Surface Pro (2017 version) with the Surface Pen on Windows 10. I have tried two programs that use Electron and both have the same problem.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
