### ISSUE TITLE
System Menu not available through Aero Peek for frameless windows

### ISSUE THREAD

**Issue by josimi** [electron/electron#12134]
* Electron version: 1.8.1
* Operating system: Windows 10

### Expected behavior

System menu with "Restore, Move, Size, Minimize, Maximize, Close" should be available for windows created using the BrowserWindow `frame: false` option.

### Actual behavior

System menu does not appear for frameless windows

### How to reproduce

1. Application consists of BrowserWindow with `frame: false`<sup>I</sup>
2. Hover over application's taskbar icon to show thumbnail
3. Right-click on thumbnail
4. System menu does not appear

I. Note: if frame is set to true then the system menu will appear.

**Comment by felixrieseberg** [comment]
Yeah, that's accurate. I've researched this topic quite a bit and as far as I know there's no way for us to add that menu, it's controlled by Windows. Unless you use a window frame you won't get that menu 😞 

I'd be _extremely_ excited if someone else would prove me wrong.

**Comment by josimi** [comment]
How does Chrome have a system menu attached to its Aero Peek thumbnail?

As far as I can tell, Chrome uses a frameless window.
________________________________

**Comment by miniak** [comment]
Chrome is doing this: https://msdn.microsoft.com/en-us/library/windows/desktop/bb688195(v=vs.85).aspx

**Comment by miniak** [comment]
@alespergl?

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR.

**Comment by rakslice** [comment]
A little note with some related actions for testing any potential fixes:
- Also shift + right-click on the taskbar icon itself should similarly open the Window menu if there is only one window, or a menu of window arrangement options (cascade, show all stacked, etc.) if there are multiple windows
- With a window active, alt-space should open its Window menu

Background: https://docs.microsoft.com/en-us/windows/win32/menurc/about-menus#the-window-menu
