### ISSUE TITLE
Transparent windows flicker on toggling visibility

### ISSUE THREAD

**Issue by pronebird** [electron/electron#12130]
* Electron version: 1.8.2
* Operating system: Windows 10 under Parallels Desktop (Windows 10 Enterprise Evaluation Insider Preview)

### Expected behavior

Window should not flicker upon the call to `BrowserWindow.show()`.

The code I have does pretty much this:

```
window.setPosition(x, y, false);
window.show();
window.focus();
```

and to hide the window I use:

```
window.hide();
```

It may of course be an issue with Parallels Desktop or preview version of Windows but every other app and Windows 10 itself work great.

I've recorded a small screencast to demonstrate this issue:

https://www.dropbox.com/s/mim2s1hv08dug8t/Electron-show-window-on-win10.mov?dl=0

### Actual behavior

Window randomly flickers. Sometimes not.

**Comment by pronebird** [comment]
I wonder if that's been addressed in Electron 2.0. I'll check tomorrow.

**Comment by StinsonZhao** [comment]
Same problem.

Both Parallels Desktop win10 and physical machine win10 have this problem.

**Comment by pronebird** [comment]
I don't see this issue in v2.0.2 anymore. Can anyone confirm?

**Comment by JosephusPaye** [comment]
Found the same problem, using a physical Windows 10 machine (version 1803, build 17134.165).

As @StinsonZhao said, the flicker only occurs with transparent windows.

This gist has a reproduction: https://gist.github.com/JosephusPaye/41746362ba59c30e9a1f69aa8295c7ff.

Use the hotkey (`Ctrl+Shift+Space`) to toggle the window and see the flicker.

The flicker occurs sporadically, but it's there.

**Comment by ruleechen** [comment]
Same problem on my versions:
Electron version: 1.7.3
Electron version: 2.0.7

**Comment by jjustin3** [comment]
From what I can tell, it looks like the previous state of the window (at the point it is hidden) is being re-rendered on .show(). This is then replaced by the current state of the window being shown, giving it a "flickering" appearance. My application makes it easy to see this.

This theory is fortified by the fact that the first time the window is shown (initially hidden after creation), it does not "flicker". Almost every subsequent hide/show action has the window flicker. Disabling hardware acceleration seems to cause less flickering overall, but not completely.

**Comment by radar155** [comment]
Same problem in  3.0.4.

**Comment by n3b** [comment]
Same in 4.0.5

**Comment by jasonjensen** [comment]
For what it's worth, this is the best workaround we have found so far:
```
browserWindow.on('show', () => {
  setTimeout(() => {
    browserWindow.setOpacity(1);
  }, 200);
});

browserWindow.on('hide', () => {
  browserWindow.setOpacity(0);
});
```

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by jjustin3** [comment]
Problem persists in Electron v7 (all minor/patch versions) as well as v8.0.0 for me.

**Comment by jjustin3** [comment]
In Windows, it is possible to alleviate this issue by adding the `--wm-window-animations-disabled` flag after `electron .` or appending the flag to the packaged application. This removes the default Windows animation. The issue still persists in Electron 8+.

**Comment by raphadko** [comment]
Nice solution @jjustin3. I've been looking for this for quite some time. Any ideas on how to use this flag by default on the compiled build?

**Comment by jjustin3** [comment]
@raphadko - if you're using Electron Builder or another similar packager, just add that flag as an argument/flag for your executable. I think this will work and I can test tomorrow. Also, electron builder I think has a section where you can specify flags/args to be built into your app? I can verify this tomorrow too.

**Comment by ahallicks** [comment]
@raphadko @jjustin3 I just use:

```
app.commandLine.appendSwitch('wm-window-animations-disabled');
```

And this seems to work just fine.

**Comment by Treverix** [comment]
Still a problem with electron 9. I have a tray window that flicker every time except for the first opening. It is transparent.

**Comment by 698511175** [comment]
曲线救国，发现了一个问题，hide后用show必然闪烁，但是如果用minimize，后再show则没有这个情况。

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by deepak1556** [comment]
Repro https://github.com/electron/electron/issues/12130#issuecomment-407306642

Workaround https://github.com/electron/electron/issues/12130#issuecomment-627198990

**Comment by raksooo** [comment]
This is still an issue in Electron 21.1.0 on Windows 11

**Comment by liuyike98** [comment]
still have the problem, electron 21.2.0

**Comment by fanchenio** [comment]
I can't believe it's 2023 and I still have this problem.

**Comment by Andrew-web-coder** [comment]
I did a workaround using opacity

**Comment by Koppel-Zhou** [comment]
I have the same problem on  `"electron": "28.3.3"`
