### ISSUE TITLE
nativeImage feature Request: concatenate / paste / merge in main process

### ISSUE THREAD

**Issue by BenGermany** [electron/electron#12143]
Hello everyone,

i tried to find a solution, but I do not get one and i think, this could be a feature request for electron main process.

I am trying to concatenate / merge some nativeImages (from .pageCapture), but i can't do this in the main process and it's annoying to shuffle this work to a renderer (canvas) process.

I tried to put some images together (side by side, down-under at the bottom / grid) via Buffer.concatenate and some others, but nothing works. So i need a method to put some native Images on a virtual canvas / grid (via x:, y:, width, height) next to other native images in the main process to build only one new (and bigger one) combined nativeImage to lastly generate an single image, in this case as a PNG via image.toPNG().

Another reason for this is, could we calculate this directly in the main process via Buffer for example, there is rarely much of the risk, that a big canvas in renderer breaks it down.

Can someone help? @zcbenz ? :-)

Thank you very much

Better explaining:

nativeImage 1: x 0 y 0 width 100 height 100
nativeImage 2: x 0 y 100 width 100 height 100
nativeImage 3: x 0 y 200 width 100 height 100

and now nativeImage.toPNG(), which creates a new single image of width 100 and height 300 Px

**Comment by miniak** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
