### ISSUE TITLE
No output at Windows console and PowerShell

### ISSUE THREAD

**Issue by satanch** [electron/electron#12148]
* Electron version: 1.7.10
* Operating system: Windows 8.1

I'm trying to do some `console.log` at main script, or use `electron -v` but I can't get anything!

![image](https://user-images.githubusercontent.com/19252217/37062571-e6d9afaa-21a7-11e8-8ac0-1f4188fbf8e2.png)

![image](https://user-images.githubusercontent.com/19252217/37062577-e9aa7fc0-21a7-11e8-97cb-9571970816ac.png)

**Comment by satanch** [comment]
Same for 2.0.0-beta.2

**Comment by ckerr** [comment]
Confirmed here.

**Comment by schelkun** [comment]
Do we have any workarounds for this issue?

**Comment by satanch** [comment]
Do we have any workaround for this?

**Comment by felixrieseberg** [comment]
Good news: This is fixed in Beta 3.

**Comment by satanch** [comment]
@felixrieseberg but what about 1.7.10+? Can I use version 1?

**Comment by alexeykuzmin** [comment]
@satanch Can you try 1.8.3?

**Comment by alexeykuzmin** [comment]
@felixrieseberg Was it actually fixed in 2.0.x by someone? or it just doesn't reproduce there?
