### ISSUE TITLE
node api is not available in electron isolated contexts of sub-frames

### ISSUE THREAD

**Issue by bughit** [electron/electron#12146]
* Electron version: recent master (dfa1dc43df17037df68b5f39ca7c3c2bb424e9c1)
* Operating system: win7 sp1 x64

### Expected behavior

With {contextIsolation: true, nodeIntegration: true}, node api is available in the top frame electron isolated context (EIC) (world 999)

```js
webFrame.executeJavaScriptInIsolatedWorld(999, [{code: 'typeof require'}], false, console.log)
```

now that you can get a hold of subframes, one would expect this to hold for their EICs

```js
webFrame.firstChild.executeJavaScriptInIsolatedWorld(999, [{code: 'typeof require'}], false, console.log)
```

### Actual behavior

but it doesn't

### How to reproduce

1. create a window with {contextIsolation: true, nodeIntegration: true}
2. load a page with an iframe
3. in the preload script: `webFrame.firstChild.executeJavaScriptInIsolatedWorld(999, [{code: 'typeof require'}], false, result => { // inspect result })`

**Comment by bughit** [comment]
this is mitigated by the fact that you can get a window from the isolated world `[{code: 'window'}]` and add whatever to it

**Comment by ckerr** [comment]
@bughit, does this occur in `2.0.0-beta.2` as well, or only in `master`?

**Comment by bughit** [comment]
2.0 does not sub-frame api (firstChild)

**Comment by bughit** [comment]
this is invalid, require is only available in the preload script in the main EIC, not when executing javascript
