### ISSUE TITLE
Electron launch broken from spectron test containing URL protocol

### ISSUE THREAD

**Issue by husayn** [electron/electron#12152]
* Electron version: 1.8.2
* Operating system: Windows

I am trying to launch an electron app from spectron and passing in a URL as a command line parameter. Due to commit https://github.com/electron/electron/commit/a250089a40f76726cf5980a1f454e600037835aa @alespergl the application will not launch.

This blocks us from running spectron tests that contain a URL as a parameter.

Proposed fix:
(1) Runtime check: Add a registry key to HKLM. If that  registry key is present. You ignore the disallow list for the URL and launch the app. Writing to HKLM will ensure security since, it can only be written to by an admin of a machine.
(2) Build time: Add a build time flag that will ignore the disallow list.

I personally prefer option 1 since it can be used at run time and will not need a custom build of electron.
If option (1) is fine I can go ahead and send out a PR.

**Comment by alespergl** [comment]
This behaviour is not going to change until the whole command line processing is refactored. You should still be able to do everything as before, you just need to pay special attention to the order of command line arguments:

- URL must not be followed by one of the black-listed arguments. The best thing is to make sure you add it as the last argument.
- You can use `--` as a delimiter between named switches and positional arguments. That means that anything is allowed after a `--` on the command line.

Hope that helps.
