### ISSUE TITLE
webFrame.executeJavaScript(InIsolatedWorld) APIs don't return promises

### ISSUE THREAD

**Issue by bughit** [electron/electron#12159]
* Electron version: recent master (dfa1dc43df17037df68b5f39ca7c3c2bb424e9c1)
* Operating system: win7 sp1 x64

### Expected behavior

[Docs](https://github.com/electron/electron/blob/master/docs/api/web-frame.md) say they return  promises.

However since they don't and execution is synchronous, this is an opportunity to change the behavior without breaking anything.  They should return the result. 

### Actual behavior

they return undefined

### How to reproduce

call the api

**Comment by felixrieseberg** [comment]
Do you mean [this API](https://github.com/electron/electron/blob/master/docs/api/web-frame.md#webframeexecutejavascriptinisolatedworldworldid-scripts-usergesture-callback)? Because it's documented to use a callback instead of a Promise.

**Comment by bughit** [comment]
Where does it say "instead"?

For webFrame.executeJavaScript it says:

> Returns Promise - A promise that resolves with the result of the executed code or is rejected if the result of the code is a rejected promise.

For webFrame.executeJavaScriptInIsolatedWorld

> Work like executeJavaScript

However since it's synchronous and unless there are plans to support async mode, it might as well return the result.

**Comment by MarshallOfSound** [comment]
This is actually just incorrect docs, `webFrame.executeJavaScript` does not return a promise.  `webContents.executeJavaScript` **does**.

Just need to correct the docs for `webFrame`

**Comment by FibreFoX** [comment]
This was mentioned in an older isse before:
https://github.com/electron/electron/issues/9804

Maybe this should be done equal?! So it makes less confusion?!

**Comment by bughit** [comment]
@MarshallOfSound 

There three issues here:

1. docs: documenting that these are synchronous and that they don't return promises
2. bug: (#12160) they swallow errors, which was auto-closed, I'll check it with 6.0
3. enhancement: since they are synchronous they can return the eval result

**Comment by bughit** [comment]
no longer applies, see #19161
