### ISSUE TITLE
-webkit-app-region: drag prevents clicks on overlapping browser view

### ISSUE THREAD

**Issue by ibash** [electron/electron#12150]
* Electron version: 1.8.2
* Operating system: macos 10.13.3

Reproducing repo: https://github.com/ibash/electron-webkit-app-drag

Demonstrates a bug where `-webkit-app-region: drag` causes a browser view in front of it to miss click events. Oddly - it does not prevent hover events.

Steps:
1. Clone https://github.com/ibash/electron-webkit-app-drag, `yarn install`, `yarn start`
2. Click "button1"
3. Click "button2"

Expected:

Clicking button1 or button2 pops up an alert: "button clicked!"

Actual:

Only clicking button2 pops up an alert: "button clicked!"

**Comment by ibash** [comment]
Maybe related to https://bugs.chromium.org/p/chromium/issues/detail?id=365593

Vivek hit this again - what's interesting is that he had two tabs open, but it only affects one tab.

**Comment by ibash** [comment]
Even more steps:

1. Open two tabs
2. Set the TabBar height to 100px
3. Switch tabs
4. Set the TabBar height back to the default
5. Switch back

Expected:
Can click on split inboxes

Actual:
Cannot click on split inboxes

Taking a look into electron, browser view has a `UpdateDraggableRegions` method. This is ultimately called by chrome when the css for the draggable region changes. Maybe it's only called on the current browser view, and this messes up the other tab?

**Comment by ibash** [comment]
I filed this because we have an issue where a browser view will stop responding to click events.
Digging into it further, I think this is because the browser view can `UpdateDraggableRegions` if it's not currently in the window.

For example, if
1. the `app-region: drag` div is behind a browser view and has 100px height
2. switch to a second browser view
3. change the `app-region: drag` div to have 10px height
4. switch back to the first browser view

Than the first browser view will still not respond to click as if the drag region was 100px, even though it is now actually 10px.

**Comment by jlfwong** [comment]
I did a manual bisect of the issue using @ibash's very helpful repository, and it looks like it's existed as long as `app-region: drag` was supported by `BrowserView`. I was able to reproduce on 1.7.7, but not 1.7.6 (which makes sense, because I don't think `app-region: drag` was supported for browser views before 1.7.7

**Comment by poiru** [comment]
@ibash Thanks for reporting this! I'll work on a fix.

**Comment by ibash** [comment]
Woo woo!

Islam Sharabash
217-377-9657

Sent via Superhuman iOS ( https://sprh.mn/?vip=islam.sharabash@gmail.com )
