### ISSUE TITLE
defaultPath option being ignored on dialog initialization

### ISSUE THREAD

**Issue by TyeS2K** [electron/electron#12162]
* Electron version: 1.8.1
* Operating system: Win 10

### Expected behavior
When using the dialog.showSaveDialog(), dialog.showOpenDialog() API and I specify the (optional) defaultPath value. The FileDialog doesn't open in the path specified. It opens it the last path used by the dialog.

I expect the defaultPath field to set the initial path the dialog is viewing at the time it starts.

### Actual behavior

The File Dialog opens it is last view path or some default location.

### How to reproduce
execut

**Comment by alexeykuzmin** [comment]
@TyeS2K Does it also happens in the latest Electron 2.0.0-beta.2?

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
