### ISSUE TITLE
webFrame.executeJavaScript(InIsolatedWorld) APIs swallow errors

### ISSUE THREAD

**Issue by bughit** [electron/electron#12160]
* Electron version: recent master (dfa1dc4)
* Operating system: win7 sp1 x64

### Expected behavior

Errors should not be swallowed. Currently these APIs return undefined (#12159). Depending on how that's addressed:

- If they return the result (which is ideal since the execution is synchronous), they should throw on error.
- If they return a promise, it should be rejected on error
- the callback they take should deliver the error

### Actual behavior

The error is dumped to the console, the API's return undefined, don't throw and the callback receives undefined result.

### How to reproduce

Call them with JS that should fail (e.g. 'non_existent_identifier')

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
