### ISSUE TITLE
Support animated `BrowserWindow#center()`

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#12176]
* Electron version: 2.0.0-beta.2
* Operating system: macOS 10.13.3

### Expected behavior

I expected [`BrowserWindow#center()`](https://electronjs.org/docs/api/browser-window#wincenter) to have an `animated` option, like the similar method `BrowserWindow#setPosition()` does.

I don't think it should be a [boolean trap](https://ariya.io/2011/08/hall-of-api-shame-boolean-trap) though, so better make it `win.center({animated: true});`.

### Actual behavior

It doesn't.

**Comment by codebytere** [comment]
The former has a `center` options as a result of implementation with [`setFrame`](https://github.com/electron/electron/blob/164cc4344095d8ec574ea67707805315a89d6c1c/atom/browser/native_window_mac.mm#L686), whereas `win.center` is implemented [here](https://github.com/electron/electron/blob/164cc4344095d8ec574ea67707805315a89d6c1c/atom/browser/native_window_mac.mm#L865-L867), and doesn't have an option to animate this action, as this is not available to the NSWindow center method in [docs](https://developer.apple.com/documentation/appkit/nswindow/1419090-center?language=objc).
