### ISSUE TITLE
[Feature request] Microsoft's new Adaptive Cards

### ISSUE THREAD

**Issue by AlexSHoffman** [electron/electron#12172]
Hey guys. are you planning to integrate the MIcrosoft's new Adaptive Cards in Electron and make it available out of the box?

## Links:
- Docs https://docs.microsoft.com/en-us/adaptive-cards/display/libraries/htmlclient
- Github https://github.com/Microsoft/AdaptiveCards
- Examples http://adaptivecards.io/samples/ActivityUpdate.html
- Video [0:13:32] https://developer.microsoft.com/en-us/windows/projects/campaigns/windows-developer-day

**Comment by felixrieseberg** [comment]
This sounds a lot like something that'd already work for people using userland-code and shouldn't necessarily be part of Electron Core.

Is there anything specific you're expecting? It appears that anyone who wants this could just use the npm module and be done with it.

**Comment by AlexSHoffman** [comment]
@felixrieseberg hmm, yeah I think you are right. I don't know what I was thinking, It probably shouldn't be in the core, it's not crossplatform either. 

Sorry, I'm gonna close the issue now
