### ISSUE TITLE
Can't get file path for file dragged out

### ISSUE THREAD

**Issue by ibash** [electron/electron#12183]
* Electron version: 1.8.2
* Operating system: macos 10.13.3

Steps:
1. clone this repo: https://github.com/ibash/electron-drag-download
2. yarn install
3. yarn start
2. drag the link "drag me to your desktop" to your desktop

Expected:
Can get the destination file path from the download item

Actual:
Can not get destination file path from the download item

I did some poking around and I _think_ the destination path is exposed as `forced_file_path_` on the download item.
You can also not get the suggested filename, that would be useful to have but I'm working around it for now.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
