### ISSUE TITLE
session.setProxy per window does not actually work

### ISSUE THREAD

**Issue by SwiTool** [electron/electron#12195]
* Electron version: **1.8.3**
* Operating system: OS X High Sierra 10.13.1

Reference : https://github.com/electron/electron/issues/4859

### Expected behavior

It should proxify both windows with different proxies.

### Actual behavior

It proxify the first window, and when the second window is proxified, it also impacts the first one

### How to reproduce

```javascript
var { app, BrowserWindow ] = require('electron');

app.on('ready', () => {
  win = new BrowserWindow({width: 800, height:600});
  win.webContents.session.setProxy({
      proxyRules: "https://x.x.x.x:31234",
      proxyBypassRules: 'localhost'
    }, () => {
      win.loadURL('file://' + __dirname + '/../browser/index.html');
  });

  win2 = new BrowserWindow({width: 800, height:600});
  win2.webContents.session.setProxy({
      proxyRules: "https://y.y.y.y:31234",
      proxyBypassRules: 'localhost'
    }, () => {
      win2.loadURL('file://' + __dirname + '/../browser/index.html');
  });
}
```

**Comment by SwiTool** [comment]
RTFM.

The answer is : partitions.

**Comment by liubo113** [comment]
@SwiTool It works for me. Thank you.

**Comment by jiayawei15191519** [comment]
> @SwiTool It works for me. Thank you.

hi @liubo113 , I  also meet this issue, but i don't know how to slove it , can you tell me how to use partitions to slove it

**Comment by SwiTool** [comment]
@jiayawei15191519 Here is the basic usage :

```js
import { BrowserWindow, session } from 'electron';

(async() => {
    const win = new BrowserWindow({
        webPreferences: {
        partition: "persist:myWindow",
    }});

    const ses = session.fromPartition("myWindow");
    await ses.setProxy({
      proxyRules: proxyRules,
      proxyBypassRules: "localhost",
    });
})()
```

**Comment by jiayawei15191519** [comment]
> @jiayawei15191519 Here is the basic usage :
> 
> ```js
> import { BrowserWindow, session } from 'electron';
> 
> (async() => {
>     const win = new BrowserWindow({
>         webPreferences: {
>             partition: "persist:myWindow",
>         }
>     });
> 
>     const ses = session.fromPartition("myWindow");
>     await ses.setProxy({
>       proxyRules: proxyRules,
>       proxyBypassRules: "localhost",
>     });
> })()
> ```

thanks for your reply. I use this usage ,it not working  ,but i use  await browserwin.webContents.session.setProxy({proxyRules: newProxyUrl}, async function () {   })   I can set proxy  ok

**Comment by jiayawei15191519** [comment]
@SwiTool 
import { BrowserWindow, session } from 'electron';
    let win = new BrowserWindow({
        webPreferences: {
            partition: "persist:myWindow",
        }
    });

     await session.fromPartition("myWindow").setProxy({
      proxyRules: proxyRules,
      proxyBypassRules: "localhost",
    },function(){
win.loadURL('http://myip.ipip.net/')
});
})
 I  fond that it still is my local ip , it set the proxy not ok ,do you know why?

**Comment by SwiTool** [comment]
@jiayawei15191519 you must do `win.loadURL` **after** setting the proxy on the window. If you can't await, just use `setProxy({...}.then(() => win.loadURL('http://myip.ipip.net/'));`
