### ISSUE TITLE
<webview>.capturePage capture wrong area on HiDPI devices

### ISSUE THREAD

**Issue by KochiyaOcean** [electron/electron#12209]
* Electron version: 1.8.3
* Operating system: Windows 10

### Expected behavior

`<webview>.capturePage` should actually take screenshot of the whole webview viewport.

### Actual behavior

`<webview>.capturePage` didn't actually take screenshot of the whole webview viewport.

### How to reproduce

- Clone https://github.com/KochiyaOcean/electron-bugs
- Run it using electron
- Run `captureAndSave()` command in devtools
- The screenshot is saved in the git folder

For example, in the picture below, the zoomFactor is 1.5, and the screenshot size is 1.5x bigger than webview's size, but the area actually captured is 0.67x as webview's viewport.

If set `rect` 1.5x bigger than webview's size, `<webview>.capturePage` would takes full viewport of webview, but the screenshot size will be 1.5*1.5 = 2.25x bigger than webview's size

![image](https://user-images.githubusercontent.com/8194131/37245709-b00bdfbc-24df-11e8-8921-6f8e119309c4.png)

**Comment by jacklovepdf** [comment]
I met the same problem, but i had solve the problem by the following method:
`
            // width, height is the size of webview;
             width =  width * window.devicePixelRatio;
             height =  height * window.devicePixelRatio;
             webview.capturePage({ x:0, y:0, width, height}, function(result){
                            
            })
`

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
