### ISSUE TITLE
Clicking (right or left) to close application (in taskbar) reveals title bar in frameless, transparent Electron App

### ISSUE THREAD

**Issue by doctormellow** [electron/electron#12208]
* Electron version: 1.8.2
* Operating system: Windows 10

### Expected behavior

Show application as is normally, before closing it. The same behavior is emitted by left clicking the application in the taskbar as well (well holding the left click) this also minimizes my application which is not desirable. 

### Actual behavior

The title bar (with the code below) is shown (where previously declared as hidden .. without a frame..) on initializing the right click menu. It doesn't show the electron icon, but it still shows the title of the application

### How to reproduce

```
const renderApp = () => { 
 // create the browser window 
 screen = new BrowserWindow({useContentSize: true, 
                            transparent: true, 
                            titleBarStyle: "hidden", 
                            frame: false, 
                            toolbar: false, 
                            alwaysOnTop: true, 
                            fullscreenable: false 
                            }) 
screen.setThumbnailClip({x: 0, y: 0, width: 0, height: 0}); 
//Do other stuff 
}
```

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
