### ISSUE TITLE
Authentication Credentials not Provided Bug

### ISSUE THREAD

**Issue by alongalor** [electron/electron#12207]
See picture. I am logged in and am a paying user
![image](https://user-images.githubusercontent.com/14210367/37236391-f77636d8-23d4-11e8-88c8-38a9ae5a556e.png)

![image](https://user-images.githubusercontent.com/14210367/37236384-e4765784-23d4-11e8-9e7f-631ca030b5c6.png)

* Electron version:
* Operating system:

**Comment by MarshallOfSound** [comment]
@alongalor This looks like an issue with a third party application, not Electron itself.  Please follow up with the makers of that app 👍
