### ISSUE TITLE
managing tasks that requires admin permissions

### ISSUE THREAD

**Issue by moeinrahimi** [electron/electron#12212]
hi
in my electron app, I need to create symlink of files, using fs.createSymlink needs the app to run as root since my app uses d&d I can't run the app as admin because that would prevent from dragging items to the app

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
