### ISSUE TITLE
BrowserWindow backgroundColor does not work as expected

### ISSUE THREAD

**Issue by steverandy** [electron/electron#12211]
* Electron version: 2.0.0-beta.3
* Operating system: macOS 10.13.3

### Expected behavior

BrowserWindow should start with the background color as specified with `backgroundColor` option and stays with the same background color after the content loads.

### Actual behavior

BrowserWindow starts with the correct background color but quickly reset to white background color.

![test](https://user-images.githubusercontent.com/525332/37250032-1178941a-24eb-11e8-829a-c90033a649d9.gif)

### How to reproduce

```
new BrowserWindow({
  backgroundColor: "#F7C136"
});
```

**Comment by deepak1556** [comment]
@steverandy I am unable to recreate the issue on the specified version with the test code. Can you provide a minimal app ? Thanks!

**Comment by steverandy** [comment]
@deepak1556 I think I've found the way to reproduce the issue:
1. Create the first BrowserWindow instance with `backgroundColor: #FFFFFF"`
2. Create another BrowserWindow instance with different background color, for example `backgroundColor: "#F7C136"`

The second browser window will have the orange background color for brief moment then it will change to white.

If you're not able to reproduce, I will try to provide sample app.
Thanks!

**Comment by deepak1556** [comment]
@steverandy I am still unable to recreate the issue, it would be great if you can provide an app. Thanks!

**Comment by steverandy** [comment]
@deepak1556 I've discovered that to reproduce this issue, you would have to use the new affinity option `webPreferences: {affinity: "window"}`.

I've cretated a test app here: https://github.com/steverandy/electron-quick-start. Please have a look. Thanks.

**Comment by deepak1556** [comment]
@steverandy thanks for the test case, I am able to recreate the issue.

**Comment by codebytere** [comment]
verified that it happens on `2-0-x` and not on `1-8-x`, will continue to investigate

**Comment by emmkimme** [comment]
As far as I see, the webContents/Preferences are deduced from the renderer process id. With affinity, we can have several pages hosted in the same renderer process id. So currently, it returns always the same webContents for pages sharing the same process. This design must be changed and we have to get the webContents for a specific page (rendererFrame?).

**Comment by emmkimme** [comment]
Simpler than that, background color is passed through process commandline 
\electron\atom\renderer\renderer_client_base.cc
`  
base::CommandLine* cmd = base::CommandLine::ForCurrentProcess();
  if (cmd->HasSwitch(switches::kGuestInstanceID)) {  // webview.
    web_frame_widget->SetBaseBackgroundColor(SK_ColorTRANSPARENT);
  } else {  // normal window.
    std::string name = cmd->GetSwitchValueASCII(switches::kBackgroundColor);
    SkColor color = name.empty() ? SK_ColorTRANSPARENT : ParseHexColor(name);
    web_frame_widget->SetBaseBackgroundColor(color);
  }
`
So all pages of the process shares the same color. 

This is a general problem to share such settings through commandline. 
For instance preload file can not be different.
Is there any way to provide to each page their own preferences (using ipc, shared memory ?) rather than using the process command line ?

**Comment by abhilashmaipady** [comment]
It is showing the web page. Web page should also change to the same background color. Even if you change the background color in main.js file it is showing the web page.

**Comment by macsj200** [comment]
@gtinkham and I were having this issue using [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate), but we only run into the problem when we run `yarn dev` instead of `yarn start` (productionized version).

**Comment by pronebird** [comment]
Same issue when using transparent window.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by SupianIDz** [comment]
Sorry to open an old case, but this also happened exactly the same on Electron version ^19.0.4

https://user-images.githubusercontent.com/37969970/175072375-95bcd87d-c8c6-4f5b-90fe-e341bee11f2a.mov
