### ISSUE TITLE
windows sources are not shown when using desktopCapturer.getSources()

### ISSUE THREAD

**Issue by ziracmo** [electron/electron#12227]
--> Feature request

Hi everyone,

I'm working on a software made with electron to record some video game, i thought i'll use the desktopCapturer to record them but i have some issues at the moment.
The Games windows sources are not show when i use the _desktopCapturer.getSources()_ from electron itself.

I'm looking for a work around if you know something or a new features/improvement from electron to be able to record all the windows in the desktop.

Thanks !

**Comment by Zaynex** [comment]
```
os: mac 10.13.5
electron version: 5.0.1
```
when I get set the the right window screenId, the stream still get the camera video source .

```
handleClick = (id) => () => {
    /** I click the specific window id that from desktopCapturer.getSources({ types: ["window", 
    "screen"]}) **/
    navigator.mediaDevices.getUserMedia({
      audio: false,
      video: {
        chromeMediaSource: 'desktop',
        chromeMediaSourceId: id,
        minWidth: 800,
        maxWidth: 1280,
        minHeight: 600,
        maxHeight: 720
      }
    }).then(this.handleStream, this.handleStreamError)
  }

  handleStreamError = (e) => {
    console.log(e)
  }

  handleStream = (stream) => {
    console.log(stream);
    const video = document.querySelector('video')
    video.srcObject = stream
    video.onloadedmetadata = (e) => video.play()
  }
```

@sofianguy  Do you have any idea? thx

**Comment by ckerr** [comment]
Would it be possible to use [Electron Fiddle](https://github.com/electron/fiddle) to create a standalone (no external dependencies) testcase and publish it as a [gist](https://gist.github.com), then link to it here.

- Even if you have a code snippet or a git repository that show the testcase, please put it in a gist. This lets maintainers triage issues more effectively. It also ensures that we're testing the exact same issue that you're seeing!

- Please avoid external dependencies in the test. The Electron team is small and generally doesn't have enough bandwidth to triage third-party code. Also, standalone tests are easier to adapt into regression tests.

- If the bug you've found can be tested with a pass / fail test, please make the testcase [exit 0 on success or nonzero on failure](https://github.com/electron/bugbot#by-bug-reporters). The lets [Electron's issue bot](https://github.com/electron/bugbot#readme) see what releases are affected by the bug.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to the gist in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by MarshallOfSound** [comment]
As the reporter has not responded to the request for additional information this issue will be closed.  If further information can be provided at some point in the future, comment on this issue with the requested information and if appropriate the issue will be reopened.
