### ISSUE TITLE
Electron failed to build on Windows due to the fatal error LNK1356: cannot find library `lib\zlib.lib' specified to be whole archived

### ISSUE THREAD

**Issue by shanshan0309** [electron/electron#12224]
Electron failed to build on Windows with VS2017 Update 5. It failed due to the fatal error LNK1356: cannot find library `lib\zlib.lib' specified to be whole archived. Could you please take a look at this? Thanks in advance!

**Repro steps:**

1. git clone --recursive https://github.com/electron/electron.git D:\Electron\src
2. Open a clean command prompt and browse to D:\Electron
3. python script\bootstrap.py -v --target_arch=ia32
4. vendor\depot_tools\ninja.exe -C out\R electron -v -d keeprsp

**Acutal result:**

FAILED: C:\tools\python2\python.exe gyp-win-tool link-with-manifests environment.x86 True node.dll "C:\tools\python2\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /IMPLIB:node.dll.lib /DLL /OUT:node.dll @node.dll.rsp" 2 mt.exe rc.exe "obj\vendor\node\node_lib.node.dll.intermediate.manifest" obj\vendor\node\node_lib.node.dll.generated.manifest
_**LINK : fatal error LNK1356: cannot find library `lib\zlib.lib' specified to be whole archived**_

**Comment by shanshan0309** [comment]
Hi, Any update for this?

**Comment by shanshan0309** [comment]
Additional information:
The reason for this issue is that there is a linker switch called /WholeArchive and specify /WHOLEARCHIVE: lib\zlib.lib on the linker command line. The error message complaines that the library specified to be whole archived cannot be found. When I changed /WHOLEARCHIVE: lib\zlib.lib to /WHOLEARCHIVE: zlib.lib. It can be passed.

**Comment by bjoernneumann** [comment]
@shanshan0309 Probably due to https://github.com/electron/electron/blob/master/common.gypi#L185

**Comment by shanshan0309** [comment]
Thanks for looking into this issue, @bjoernneumann. Electron no longer hit this issue in the latest revision. Thank you!

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
