### ISSUE TITLE
[Issue] Spectron with Mocha

### ISSUE THREAD

**Issue by KorobkaVadim** [electron/electron#12246]
### Expected behavior
```error
this.app.client = undefined
```

I wanna test my app with Spectron and Mocha(only render process). But I don't start this from Electron, I try add app.setAccessibilitySupportEnabled(true) in main process. But I catch error:
```error
app.setAccessibilitySupportEnabled is not a function
```

### Actual behavior

Please write example using Spectron and Mocha in Electron app with test Render process.

### P.S
I try use google.com and SO))

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
