### ISSUE TITLE
Thumbar buttons disappear after win.hide() and win.show()

### ISSUE THREAD

**Issue by arjndr** [electron/electron#12240]
Hello there! I have an issue where the Thumbar buttons disappear after hiding and showing the BrowserWindow

* Electron version: 1.8.2
* Operating system: Windows 7 x64

### Expected behavior

Thumbar buttons should be visible even after hiding and showing the BrowserWindow
![thumbbar_shown](https://user-images.githubusercontent.com/20661194/37324291-b1b55f70-26ae-11e8-805c-065af496415b.png)

### Actual behavior

Thumbar buttons disappear after hiding and showing the BrowserWindow
![thumbbar_gone](https://user-images.githubusercontent.com/20661194/37324306-bf785ca2-26ae-11e8-8a07-24457cf36780.png)

### How to reproduce

1. Create app with Thumbar buttons
2. Hide and then Show the BrowserWindow, that should work

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by gbahry** [comment]
Hello, I want to confirm that this exact issue is still occurring on the newer versions of Electron. In my case, testing on:

- Electron version: 5.0.2
- Operating system: Windows 10 x64

Even calling setThumbarButtons() after hiding and showing the window doesn't display the thumbar buttons. There's no way to show them again after hiding.

**Comment by KyzaGitHub** [comment]
This issue is still in `Electron 5.0.8` on `Windows 10 x64`. Once the window is hidden, the thumbar buttons never display again as @gbahry said.

Please reopen this issue.

**Comment by arjndr** [comment]
@sofianguy looks like the issue still exists 👀

**Comment by Araxeus** [comment]
Issue still exist in `Electron 12.0.0` on `Windows 10 pro: v19042`
3 years later? :(
