### ISSUE TITLE
App variable not globalizing past window function

### ISSUE THREAD

**Issue by Herofied1180** [electron/electron#12250]
What did I do wrong here? The code should have made the app variable usable past the function variable, but it doesn't seem to work. I also did make an index.html file in the same directory as the main.js.

 app.on('ready', createWindow)
      ^

TypeError: Cannot read property 'on' of undefined

```js
const {app, BrowserWindow} = require('electron')
  
  // Node.js won't let the app variable go past this
  function createWindow () {
    win = new BrowserWindow({width: 800, height: 600})
    
    win.loadURL(url.format({
      pathname: path.join(__dirname, 'index.html'),
      protocol: 'file:',
      slashes: true
    }))
  }
  
  app.on('ready', createWindow)
```

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
