### ISSUE TITLE
Printing blank page

### ISSUE THREAD

**Issue by ChristianLJ** [electron/electron#12273]
* **Electron version:** 1.8.3
* **Operating system:** Windows 10 Enterprise, Build 1709, 16299.248

### Expected behavior
1. Downloading and adding a .pdf as content in an iframe. 
2. call print() on the iframe.
3. Opens the print preview dialog.
4. Print correct content.

### Actual behavior
1. Downloading and adding  a .pdf as content in an iframe. 
2. call print() on the iframe.
3. Opens the system print dialog.
4. Print blank page.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
