### ISSUE TITLE
Last Thumbar button is always rounded

### ISSUE THREAD

**Issue by arjndr** [electron/electron#12270]
So, this is an issue I've noticed on many Electron based apps. The last Thumbar button is always rounded, I wondered if it was an issue with Windows but it turns out other applications (non Electron) don't have this issue.

* Electron version: 1.8.2
* Operating system: Windows 7 x64

### Expected behavior

It should look something like this

on Spotify
![spotifythumbar](https://user-images.githubusercontent.com/20661194/37399679-5f2bac14-27a8-11e8-8b7c-7a2daac878a7.png)

on MPC
![mpcthumbar](https://user-images.githubusercontent.com/20661194/37399724-8fb2c2dc-27a8-11e8-90ce-bee39eed247c.png)

on Windows Media Player
![wmpthumbar](https://user-images.githubusercontent.com/20661194/37399750-a3cbc278-27a8-11e8-8fcd-58b60b812f62.png)

### Actual behavior

It looks like this on Electron based apps

on Autobeat
![autobeatthumbar](https://user-images.githubusercontent.com/20661194/37399993-662b160c-27a9-11e8-9946-be7699cce192.png)

on Auryo
![auryothumbar](https://user-images.githubusercontent.com/20661194/37400012-73296c3c-27a9-11e8-98c4-2974445a3114.png)

### How to reproduce

1. Create an Electron app with Thumbar buttons
### OR
2. Use [Autobeat](https://electronjs.org/apps/autobeat-player) or [Auryo](https://electronjs.org/apps/auryo)

**Comment by marianoweber** [comment]
Hey,
at the moment the toolbar gets filled with buttons until it is full(seven is max). If you set three buttons, the toolbar will show your three buttons and hide the rest. This is causing your last button to have rounded corners.
If you test it with seven buttons, instead of three, they will be displayed correctly. 

@zcbenz  Is it really necessary to make the ThumbarButtons updateable by filling empty toolbar space with hidden buttons?

**Comment by zcbenz** [comment]
@marianoweber It is to ensure apps can change the number of buttons. But since it is causing visual problems,  we should probably change this behavior or add a new option to use fixed number of buttons.

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR.
