### ISSUE TITLE
WebFrame is being leaked on destruction of render processes

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#12283]
https://cs.chromium.org/chromium/src/content/renderer/render_process_impl.cc?dr=C&l=195

**Comment by nitsakh** [comment]
Looks like a chromium regression and related to https://bugs.chromium.org/p/chromium/issues/detail?id=791765. This is probably okay as it happens on the destruction of the renderer process.

**Comment by alexeykuzmin** [comment]
> https://crbug.com/791765

We should check that it no longer happens when the issue it fixed.

**Comment by miniak** [comment]
@alexeykuzmin can we close this?
