### ISSUE TITLE
FATAL:V8PerIsolateData.cpp(54)] Check failed: !ScriptForbiddenScope::IsScriptForbidden()

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#12295]
Fix the crash, currently it is ignored in `082-blink-platform-bindings-V8PerIsolateData.patch`:

```
[22964:0312/160427.139779:FATAL:V8PerIsolateData.cpp(54)] Check failed: !ScriptForbiddenScope::IsScriptForbidden().
0 0x7f52de54eb2d base::debug::StackTrace::StackTrace()
1 0x7f52de54cf5c base::debug::StackTrace::StackTrace()
2 0x7f52de5d3dba logging::LogMessage::~LogMessage()
3 0x7f52e10ddd40 <unknown>
4 0x7f52ee73c505 <unknown>
5 0x7f52ee75e938 v8::Function::Call()
6 0x7f52ef0c9c61 node::InternalMakeCallback()
7 0x7f52ef0ca0ae node::MakeCallback()
8 0x7f52ef0c9ff4 node::MakeCallback()
9 0x7f52ef0c9ec2 node::MakeCallback()
10 0x000000e5e617 mate::internal::CallMethodWithArgs()
11 0x000000fc3f61 _ZN4mate9EmitEventIA15_cJEEEN2v85LocalINS2_5ValueEEEPNS2_7IsolateENS3_INS2_6ObjectEEERKT_DpRKT0_
12 0x000000fc2c6f atom::AtomRendererClient::RunScriptsAtDocumentStart()
13 0x7f52db3390eb content::RenderFrameImpl::RunScriptsAtDocumentElementAvailable()
```

It used to be disabled in the [Chromium 61](https://chromium.googlesource.com/chromium/src.git/+/61.0.3163.141/third_party/WebKit/Source/platform/bindings/V8PerIsolateData.cpp#46) and [62](https://chromium.googlesource.com/chromium/src.git/+/62.0.3202.94/third_party/WebKit/Source/platform/bindings/V8PerIsolateData.cpp#53), but was enabled back in the [Chromium 63](https://chromium.googlesource.com/chromium/src.git/+/63.0.3239.150/third_party/WebKit/Source/platform/bindings/V8PerIsolateData.cpp#53) (landed in 63.0.3207.0).
CL that enabled it: https://chromium-review.googlesource.com/c/chromium/src/+/648373

/cc @zcbenz, @nitsakh

**Comment by alexeykuzmin** [comment]
Seems like the patch has already been removed.

https://github.com/electron/libchromiumcontent/commit/4acbced107fbf6928bb4572c160f639683b35669

**Comment by zcbenz** [comment]
Fixed with https://github.com/electron/electron/pull/11459/commits/c7b94900b7d1db0304d011fc53bff244a6359c64 in .
