### ISSUE TITLE
urllib2.URLError: <urlopen error [Errno 10061] while bootstrapping

### ISSUE THREAD

**Issue by marianoweber** [electron/electron#12303]
* Electron version: master
* Operating system: Windows 7 Professional 64 bit
* Python version: 2.7

### Expected behavior

I am expecting a successful bootstrap.

### Actual behavior

I am getting a `urllib2.URLError: <urlopen error [Errno 10061]` error while bootstrap.py tries to download `libchromiumcontent.tar.bz2`.

**Full error:**
[error.txt](https://github.com/electron/electron/files/1815018/error.txt) (Some of the error text is in German, it just says that the target computer refused connection)

### How to reproduce

`git clone https://github.com/electron/electron.git`
`cd electron`
`python script\bootstrap.py -v`

I am wondering, if this is caused by my system. I would be thankful for some help.

**Comment by codebytere** [comment]
@marianoweber i believe this issue should be solved by upgrading your python version to at least `2.7.9`

**Comment by marianoweber** [comment]
@codebytere Thanks for your quick anwser, but after upgrading to 2.7.14 it still didn't work. 
It seems like the proxy i'm sitting behind caused the problem. I had to set the proxy in IE, as cmd apparently takes it's proxy settings from there.
