### ISSUE TITLE
Web Audio Bug With Removing 'Default' Audio Output on Windows OS

### ISSUE THREAD

**Issue by AGiantSquid** [electron/electron#12311]
* Electron version: 1.7.8 - 2.0.0 beta 4
* Operating system: Windows 10

### Expected behavior

When the 'default output' for the OS is removed, electron should fall back to some other device, and the audio stream for the input device should not be corrupted.

### Actual behavior

Removing the 'default' output device corrupts the audio of the app.

### How to reproduce

```bash
git clone https://github.com/AGiantSquid/electron-quick-start.git
cd electron-quick-start/
yarn / npm install
yarn start / npm start
```

Start with a computer with Windows installed. The bug will be easiest to see with at least 2 devices attached. In your Windows settings, check which audio device is set to 'default' for output. Your default for input does not matter.

Start up electron like normal. When you talk into your mic, you should see the number 0 on the screen become some higher number corresponding to how loud you are talking. You should also hear yourself from the 'default' audio device. 

Now, remove the device that is set to 'default' for output on your os. You will see that the number reflecting your volume freezes and the audio stops. It becomes impossible to recover the audio connection for the duration of the session.

This is not normal. If you open index.html in Chrome, you will see that it will fall back to another device and your stream will continue, uninterrupted.

**Comment by ckerr** [comment]
Bah. I was cleaning my copy/paste buffer when it went off.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
