### ISSUE TITLE
using node.js harmony features inside electron

### ISSUE THREAD

**Issue by cookiejest** [electron/electron#12320]
Cannot use array.includes() within electron

I did some research and this seems to be because I need to enable node.js harmony features using a flag --harmony_array_includes

However I am not sure how to make this work inside my package.json. I tried the following but it does not work:

  "scripts": {
    "start": "./node_modules/.bin/electron . --harmony_array_includes",
    "test": "mocha",
    "win": "electron-builder -w",
  },

* Electron version:     "electron": "1.7.8",
* Operating system: Windows

### Expected behavior

I want to be able to use array.includes within node.js

### Actual behavior

Any ideas?

**Comment by MarshallOfSound** [comment]
> Electron version:

❓

**Comment by cookiejest** [comment]
"electron": "1.7.8",

**Comment by timfish** [comment]
`Array.prototype.includes` has been in nodejs without a flag [since node 6.4.0](http://node.green/#ES2016-features-Array-prototype-includes-Array-prototype-includes). 

Electron 1.7.0 had node v7.9.0 so includes should just work in 1.7.8.

**Comment by damianobarbati** [comment]
@timfish did you find a solution on how to pass --harmony flag to electron node, or even better how to use latest node in electron instance?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
We are no longer providing bug fixes for bug reports earlier than 2.0.x. We are more than happy to reopen this issue if you are experiencing this bug on a later version of Electron.
