### ISSUE TITLE
LINK : fatal error LNK1257: error at code generation.

### ISSUE THREAD

**Issue by marianoweber** [electron/electron#12326]
* Electron version: master
* Operating system: Windows 7 64 bit

### Expected behavior

The build should run successful.

### Actual behavior

I get a warning that gets treated as an error (see [fullerror.txt](https://github.com/electron/electron/files/1819405/fullerror.txt) for further information):

`warning C4743: "const std::bad_weak_ptr::'vftable'" has different size
in "c:\build\src\out-x64\static_library\gen\out-x64\static_library\gen\v8\sr
c\inspector\inspector_jumbo_1.cc" and "c:\users\web\desktop\electron\vendor\node
\src\node_platform.cc": 24 and 16 Bytes`

### How to reproduce

`git clone https://github.com/electron/electron.git`
`cd electron`
`python script\bootstrap.py -v`
`python script\build.py`

I think this may be a problem caused by my system. Did someone experience a similar error before?
Thanks.

**Comment by andens** [comment]
I'm also experiencing that error. Same OS for me.

**Comment by marianoweber** [comment]
@adens were you able to fix it?

**Comment by bughit** [comment]
#12061

**Comment by marianoweber** [comment]
@bughit, thanks, didn't realise there was an open issue already.

**Comment by andens** [comment]
@marianoweber Nope, and I'm clueless as to what it could be.

**Comment by zcbenz** [comment]
I'm merging this to #12061.
