### ISSUE TITLE
KDE plasma - tray tooltip not working

### ISSUE THREAD

**Issue by hovancik** [electron/electron#12321]
* Electron version: 1.8.3
* Operating system: Arch KDE Plasma

### Expected behavior

tray tooltip should be shown (Electron Demo in the tray.)

### Actual behavior

 there is tray tooltip showing name of the app

### How to reproduce
- start electron api demos
- put it to tray from menu
- tray tooltip set by app is not shown

![screenshot_20180316_113649](https://user-images.githubusercontent.com/4745859/37516631-07b99140-290f-11e8-8987-066dd7c81774.png)

**Comment by lundibundi** [comment]
Also tested on ArchLinux + KDE Plasma with this example https://electronjs.org/docs/api/tray on
* electron 2.0.4 with the same resuls
* electron@beta 3.0.0-beta.1 with the same resuls

**Comment by rocka** [comment]
electron 3.1.3 on Arch Linux with KDE Plasma still have this Issue, only "electron" can be displayed as tooltip text.

**Comment by glaubersm** [comment]
This bug persists on Arch Linux running electron 4.1.4 and KDE Plasma 5.15.5.
Riot and Wire apps show "electron" in their tooltip.

**Comment by chfanghr** [comment]
Reproduced.

Strangiato <notifications@github.com> 于2019年5月11日周六 下午10:00写道：

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by rocka** [comment]
- Electron version: 3.x 4.x 5.x and 6.0.0 (almost all versions of electron)
- Operating system: Arch Linux (kernel 5.2.6)
- Desktop envrionment: KDE Plasma 5.16

Exactly the same behavior and reproduce steps as the original issue.

Tray icon works, but it's tooltip would always be `electron` regardless how did you set it.

**Comment by GraithTiger** [comment]
* Electron version 7.x
* Operating system: Arch Linux (kernel 5.7.2)
* Desktop environment: KDE Plasma 5.19

Same issue here.

**Comment by hovancik** [comment]
It started to work with new implementation of tray, but unfortunately they ripped it off and brought back the old one ;[

**Comment by hovancik** [comment]
I can confirm the issue with electron 9.0.5. 

Was working really great, but really short in version 8.3.0

**Comment by bontaramsonta** [comment]
- desktop : kubuntu 19.02

- electron : 9.0.5

same issue tool tip shows "electron" with Browserwindow logo, can't change it

**Comment by Tank-Missile** [comment]
Tray icons for electron apps do not show up for me either on Arch Linux with KDE Plasma. More than that though, some tray icons like Discord show up blurry even with libappindicator-gtk3 installed. Also, notifications don't show up. I'm using electron version 9.1.1-1.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by hovancik** [comment]
Please follow up here for updates, I had to create new issue because of the bot: #28131

**Comment by geekCyberWarrior** [comment]
The same issue still persists where the tooltip shown is "electron" irrespective of what is set

- Kali Linux 2021.2 x64
- KDE Plasma Version: 5.20.5
- Electron 13.1.7
