### ISSUE TITLE
Electron 1.8.x arm releases are broken

### ISSUE THREAD

**Issue by jkleinsc** [electron/electron#12329]
* Electron version: 1.8.2, 1.8.3, 1.8.4
* Operating system: Raspbian GNU/Linux 9 (stretch)

### Expected behavior

Running `electron` with no arguments should display the Electron startup screen.

### Actual behavior

An empty screen is displayed:
![electron184](https://user-images.githubusercontent.com/609052/37540286-c35a5d0e-292c-11e8-9e59-56a614e2f8a1.png)

Also when running with ELECTRON_ENABLE_LOGGING=true and ELECTRON_ENABLE_STACK_DUMPING=true, stderr displays the following:
```
[1735:0316/141145.459308:WARNING:audio_manager.cc(293)] Multiple instances of AudioManager detected
[1735:0316/141145.459830:WARNING:audio_manager.cc(254)] Multiple instances of AudioManager detected
[1759:0316/141146.574389:ERROR:sandbox_linux.cc(343)] InitializeSandbox() called with multiple threads in process gpu-process. 
Received signal 4 <unknown> 000000775f5e
#0 0x0000017d5f52 (/home/pi/Downloads/electron184/electron+0x17d5f51)
#1 0x0000017d5e42 (/home/pi/Downloads/electron184/electron+0x17d5e41)
#2 0x000074b226c0 (/lib/arm-linux-gnueabihf/libc-2.24.so+0x2c6bf)
[end of stack trace]
Calling _exit(1). Core file will not be generated.
[1735:0316/141146.615271:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
[1735:0316/141146.616247:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
[1735:0316/141146.616998:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
[1735:0316/141146.619423:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
[1735:0316/141146.619938:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
```

I also tested the 2.0.0-beta.4 release and it worked correctly
![electron2b4](https://user-images.githubusercontent.com/609052/37540745-858ef6a4-292e-11e8-8a82-ac41359011ad.png)

### How to reproduce
1. Download a 1.8.x arm release (electron-v1.8.4-linux-armv7l.zip) on a Raspberry PI 2 or a Raspberry PI 3 running a 32 bit OS
2. Unzip the archive
3. Run `electron` from the archive with no args.

**Comment by RebelSyntax** [comment]
If I have a chance later, I'll post up some logs.  I have the same platofrm setup as @jkleinsc.  I tried the latesy 1.7 and had same results as the 1.8.x  I had to go back to 1.7.11.  

Maybe that narrows it down some on where to start looking.

**Comment by xiaods** [comment]
any process?

**Comment by zcbenz** [comment]
From the comments:

* 1.8.1 works
* 1.8.2 does not work
* 1.7.11 works
* 1.7.12 does not work.

It seems that 8b6aa225aed3769f42fa5ce3ff14893dcba1a112 is responsible for the problem, but the code looks very innocent to me.

**Comment by brubbel** [comment]
> #2 0x000074b226c0 (/lib/arm-linux-gnueabihf/libc-2.24.so+0x2c6bf)
Possibly some versions were compiled against libc-2.19.so while the latest debian stretch seems to use 
libc-2.24.so.

debian jessie (this seems related to https://github.com/electron/electron/commit/8b6aa225aed3769f42fa5ce3ff14893dcba1a112)
```
addr2line -j .text -e /lib/arm-linux-gnueabihf/libc-2.19.so  0x2c6bf
/build/glibc-g3vikB/glibc-2.19/stdio-common/vfprintf.c:1642
```
debian stretch:
```
addr2line -j .text -e /lib/arm-linux-gnueabihf/libc-2.24.so  0x2c6bf
/build/glibc-HsYnUB/glibc-2.24/stdio-common/_i18n_number.h:62
```


cfr:
https://packages.debian.org/jessie/armhf/libc6/filelist
https://packages.debian.org/stretch/armhf/libc6/filelist

**Comment by d21d3q** [comment]
## another steps to reproduce 

with fresh install of raspbian jessie/stretch lite
```bash
sudo apt-get install -yq xorg
sudo apt-get install -yq libnss3 libgconf2-dev libxss-dev libgtk2.0-dev 
sudo apt-get install -yq dbus-x11  # lack of this one didn't cause crash, but electrons logs were complaining about lack of it                                                                                                                          
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -  # or 9.x
sudo apt-get install -yq nodejs 
sudo npm i -g --unsafe-perm electron # this one will install 1.8.4
sudo startx /usr/bin/electron -d --enable-logging --v=50
```
will produce: https://hastebin.com/madajazifo.sql

**Comment by mavnaranjo** [comment]
Happens to me using raspbian 9.4 Stretch and electron@2.0.2.

**Comment by brubbel** [comment]
Note:
Raspbian Stretch, within docker container, [electron-quick-start](https://github.com/electron/electron-quick-start) with electron@2.0.5 works as explained [here](https://github.com/electron/electron/issues/12937#issuecomment-389421787) by setting `app.disableHardwareAcceleration();` at [this](https://github.com/electron/electron-quick-start/blob/dc1585b235a00bb6842ee2fd0e56fd94fdc1123e/main.js#L3) location.

**Comment by miniak** [comment]
Electron 2 is not supported anymore. Please re-open if you can still reproduce with Electron >= 3.

**Comment by sofianguy** [comment]
@jkleinsc is this still a problem in later versions of electron?

**Comment by jkleinsc** [comment]
@sofianguy no, I'll close this.
