### ISSUE TITLE
Ho we Use Electron with express-reactapp

### ISSUE THREAD

**Issue by hunnain** [electron/electron#12336]
Hi Iam new in Electron so please help me
How can we use Electron with express and react app please describe in briefly so i can understand please help me i want to use electron with express and react app
Thanks in advanced for helping.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
