### ISSUE TITLE
Autoupdater restart and dialog

### ISSUE THREAD

**Issue by Ciao121** [electron/electron#12335]
* Electron version: 1.8.3
* Operating system: Win 10 64bit

### Expected behavior
Don't have the installer dialog ask to start updated app if it is already auto relaunched
### Actual behavior
After autoUpdater.quitAndInstall() is fired, updater is launched and the app autorestart (This is ok for me). But The installer shows a final dialog asking the user if he wants to starts the app.

I like the fact the app is automatically relaunched but  having this dialog should not happen. Is this a bug/missing feature or am I'm missing something?

Thank you!

**Comment by MarshallOfSound** [comment]
> But The installer shows a final dialog asking the user if he wants to starts the app.

Electron does not control your "installer" and our internal update logic only emits events that developers then use to display UI.  We don't show any dialogs or anything like that 😄 It sounds like you are using a wrapper around our autoUpdater or potentially have your own logic running somewhere.

If I've misjudged this let me know and I'll reopen 👍
