### ISSUE TITLE
error while loading shared libraries: libgtk-x11-2.0.so.0

### ISSUE THREAD

**Issue by reeeeeeeeeeeeeeeeeeeeeeeeeeeeeee** [electron/electron#12349]
* Electron version: 1.8.4
* Operating system: CentOS 7 x64

### Expected behavior
Electron should install successfully.

### Actual behavior
After executing **`npm install electron --save-dev --save-exact`**, it completes the installation without any errors and then I when I try type in `electron` in console, I get the error:

/usr/lib/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

**Comment by ckerr** [comment]
https://stackoverflow.com/questions/38935024/error-while-loading-shared-libraries-libgtk-x11-2-0-so-0
