### ISSUE TITLE
PowerSaveBlocker does not work the same as the document described

### ISSUE THREAD

**Issue by juncaixinchi** [electron/electron#12345]
PowerSaveBlocker does not work the same as the document described

* Electron version: v1.7.9 or v1.8.4
* Operating system: Windows 7 or 10

### Steps to reproduce

1. Set computer to turn off display in 1 minute, and  to sleep in 3 minutes
2. Use powerBlockId = electron.powerSaveBlocker.start("prevent-display-sleep")
3. Start the application, and wait more than 3 minutes

### Expected behavior

The computer does not turn off display or sleep

Docs:  `prevent-display-sleep - Prevent the display from going to sleep. Keeps system and screen active. Example use case: playing video.`

### Actual behavior

The computer sleeps after 3 minutes.

This means the 'prevent-display-sleep' option can only prevent computer from turning of display, not sleeping. 

I checked the windows settings of powercfg, the result is the following:

![default](https://user-images.githubusercontent.com/8253814/37580193-5de0adcc-2b7d-11e8-8d7d-40b051f3a113.PNG)

**Comment by 1ntegrale9** [comment]
Similar phenomenon occurs.
 in electron 2.0.5 under Windows 10 !!

**Comment by 1ntegrale9** [comment]
Even now the same phenomenon is happening.
- Electron version: 2.0.5
- Operating system: Windows 7 or 10

**Comment by agjs** [comment]
I can confirm the same behavior in Electron 3.0.3. 

- If computer only has Screen timeout set, it will work.
- If the screen has Sleep timeout set too, it will not work.

**Comment by SourceBoy** [comment]
`prevent-app-suspension` works in Electron 3.1.0 in Windows 10, but it prevents screens from going off in Linux with [upower](https://upower.freedesktop.org/).

Is `powerSaveBlocker` a singleton implementation where it's possible to retrieve `isStarted()` status without passing `id` as argument? Currently it seems that `isStarted()` is a static method; it'd be convenient if one can `start()` in the main process and `stop()` in renderers without the id.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by danni** [comment]
We've seen this too on PCs running Windows 10, that should be in `prevent-app-suspension` on Electron 4.2.8. The app was actively doing a firmware update via USB via a subprocess when it went to sleep.

It's worth noting that both devices were on battery at the time.

**Comment by djpereira** [comment]
We tried this with electron 6.x and Windows 10 1709, and it does not seem to work as intended.

Calling `powerSaveBlocker.start('prevent-display-sleep')` prevents the system from turning off the screen, but if the system is set to actually sleep after a while, it actually goes to sleep.

If you run powercfg you get the results below.
```
>powercfg /requests
DISPLAY:
[PROCESS] \Device\HarddiskVolume3\myapp\node_modules\electron\dist\electron.exe
Electron
```

If instead you use `powerSaveBlocker.start('prevent-app-suspension')`, system turns the monitor off, but it does not get to sleep. Powercfg gives you this:
```
>powercfg /requests
EXECUTION:
[PROCESS] \Device\HarddiskVolume3\myapp\node_modules\electron\dist\electron.exe
Electron
```

How would you prevent the computer from **both** sleeping/suspending **and** the screen from turning off in Windows?

From the documentation seems like `prevent-display-sleep` should do that, but that's not the case. Also calling one after the other does not work either.

**Comment by WinnieFE** [comment]
I can confirm the same behavior in Electron11.1.0

1. Set computer to turn off display in 1 minute, and to sleep in 1 minutes.
2. Use `electron.powerSaveBlocker.start('prevent-display-sleep')`.
3. The computer sleeps after 1 minutes.

**Comment by HyperClockUp** [comment]
reproduce on Win10 using v9.0.4.

**Comment by codebytere** [comment]
It looks like this is an issue [upstream](https://source.chromium.org/chromium/chromium/src/+/main:services/device/wake_lock/power_save_blocker/power_save_blocker_win.cc;l=101-110;drc=3cbd92081969932e0db0cca36838594f543f81f5;bpv=1;bpt=1?q=RequestType%20power%20-f:out%20&ss=chromium) per MSFT documentation referenced in @djpereira's comment above both `PowerRequestDisplayRequired` and `PowerRequestSystemRequired` must be submitted. Electron calls into the above Chromium code when creating the power save blocks and as of now they're only submitting `PowerRequestDisplayRequired`. A next step here might be for someone to open a crbug.com report outlining the issue and requesting they look into it.

**Comment by PrestonGiorgianni** [comment]
> It looks like this is an issue [upstream](https://source.chromium.org/chromium/chromium/src/+/main:services/device/wake_lock/power_save_blocker/power_save_blocker_win.cc;l=101-110;drc=3cbd92081969932e0db0cca36838594f543f81f5;bpv=1;bpt=1?q=RequestType%20power%20-f:out%20&ss=chromium) per MSFT documentation referenced in @djpereira's comment above both `PowerRequestDisplayRequired` and `PowerRequestSystemRequired` must be submitted.
> 
> Electron calls into the above Chromium code when creating the power save blocks and as of now they're only submitting `PowerRequestDisplayRequired`. A next step here might be for someone to open a https://crbug.com report outlining the issue and requesting they look into it.

Just updating this issue, someone did open an issue with Chromium.

https://bugs.chromium.org/p/chromium/issues/detail?id=1182771&q=PowerRequestSystemRequired&can=1
