### ISSUE TITLE
Electron apps should open in the background when a user is using another app in the foreground

### ISSUE THREAD

**Issue by bastones** [electron/electron#12346]
* Operating system: macOS 10.13.3

### Expected behavior

Native Mac applications usually open in the background if the user is currently performing an action with another app in the foreground at the time that app is being launched. Actions such as dragging the window of an app or typing into an input field will force most native macOS apps to launch in the background.

### Actual behavior

Electron apps always launch in the foreground, disrupting the user flow.

**Comment by MarshallOfSound** [comment]
🤔 In what case would an app launch _while_ you were typing / interacting with another window?

**Comment by bastones** [comment]
If you launch an Electron app, and then start using another app while it opens, the Electron app opens in the foreground. Native macOS apps will open in the background if another app is in the foreground _and in use_. It's not hard to understand.

**Comment by codebytere** [comment]
@bastones your comment was deleted as a violation of the [Electron Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) as it was insulting or derogatory.

**Comment by bastones** [comment]
Righteo. Issue closed. No further help from me.

**Comment by groundwater** [comment]
I'd like to write a final summary for transparency.

Code of Conducts leave a lot of room for interpretation. So for example, what one person finds offensive may be innocuous to another. This does not give license to use that as a shield for inappropriate behavior, nor does it give others the right to weaponize a CoC to report any speach they disagree with.

A few points are worth clarifying:

1. The project owners, which include @codebytere, myself, and others, are within our right to clarify boundaries of the CoC. We do this trying to take into account the greater community and safety of those actively contributing to the project in a positive way.
2. Folks recieving this feedback should understand it is our attempt to guide you into a constructive means of contributing. You will not be blocked/banned for innocent mistakes. You _will_ be warned however.

Folks choosing to ignore these guidelines, regardless of their prior contributions, may be blocked from contributing to the project further. The decision is always in the hands of the person who has recieved the warning.

Here's the way we're going to proceed:

1. this issue will remain closed
2. @bastones please wait 72 hours before replying further
3. after 72 hours, if @bastones wishes they can open a new issue to discuss this, and maintain non-confrontational language.

Any other actions will result in a block.

[record of comments](https://gist.github.com/groundwater/401dd078e5c3647a19befe426dec4526)
