### ISSUE TITLE
Node Integration IPC functions defined but when called, return undefined

### ISSUE THREAD

**Issue by jondwillis** [electron/electron#12340]
* Electron version: 1.8.3
* Operating system: macOS

### Expected behavior

After sending remote objects that have functions defined on them FROM a webview renderer TO a remote window renderer, calling those functions should return the same value as when calling them within the webview renderer.

### Actual behavior

calling the function within webview process returns the correct value, but calling the function within the remote renderer returns undefined.

### How to reproduce

I am trying to be able to call remote webview functions from my electron renderer, to reduce boilerplate, since there are many remote functions I need to use.

(webview renderer, node integration enabled) `preload.js`
```const {  remote } = require('electron')
const ipc = remote.require('./app/ipc/ipc')
...
const clib = window.require('game-logic/clib')
ipc.setClib(clib)
...
clib.winProb(100, 108) // returns 0.9160729157027853
```
(node) `app/ipc/ipc.js`
```var state = {
    gameEngine: null,
    clib: null,
    stateLib: null,
    ScriptExecutor: null
}

exports.setClib = (clib) => {
    state.clib = clib
}

exports.getClib = () => {
    return state.clib
}
```
main window renderer
```const ipc = remote.require('./app/ipc/ipc')
ipc.getClib().winProb // returns function anonymous()
ipc.getClib().winProb(100, 108) // returns undefined
```

**Comment by timfish** [comment]
Github issues are used by the Electron team as their backlog so they should only be used for bug reports and feature requests. I see you asked this in Slack which is the correct place for questions. Its Sunday evening so it might take a white to get a response.

> After sending remote objects that have functions defined on them

Everything sent over ipc is JSON serialised, so functions will not survive this.

**Comment by jondwillis** [comment]
Right. My approach is attempting to (ab)use the node integration to pass functions. And it gets as far as the functions appearing cross-process, but not, well, functioning :)
