### ISSUE TITLE
in win OS how to open BrowserWindow with a window as its owner(parent) window  which opend from another process

### ISSUE THREAD

**Issue by rainryu** [electron/electron#12350]
I have a C# winform program  and it create a form ,now i want open an window in an electron program,which electron's window(form)'s owner(parent)'s HWND is c# program's windown handle.

it's support on electron？

THX
：）

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
