### ISSUE TITLE
Top title bar is visible when my app loses focus

### ISSUE THREAD

**Issue by Florent99** [electron/electron#12364]
I'm currently working on an Electron JS application. When running this application there is an animation to "deploy" the window and its reverse animation to close the application. So my frameless BrowserWindow is larger than its content.

One weird behaviour happens when the application loses focus. A frame around the BrowserWindow appears:

https://i.stack.imgur.com/x8GoI.jpg

This behaviour only occurs when the blur event is raised. If the app doesn't lose the focus, this bar is not visible at all.
I tried to play with the titleBarStyle property without any success

Here is how my window is defined:

```
mainWindow = new BrowserWindow({ frame: false, thickFrame: false, 
    width: 1000, height: 450, 
    icon: path.join(__dirname, 'assets/sharing-2.ico'), 
    transparent: true, titleBarStyle: 'hidden'});
```

Note that I don't have this behaviour when running an npm start command from Visual Studio Code but it does after I package my app using electron-packager

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
