### ISSUE TITLE
showOpenDialog blocks the main thread  if browserWindow is not specified on OSX

### ISSUE THREAD

**Issue by santazaaa** [electron/electron#12368]
* Electron version: 1.8.4, 2.0.0-beta
* Operating system: OS X 10.13.2

### Expected behavior
Main thread (and current browser window) should not be blocked when there is no browserWindow specified (callback is passed in)

### Actual behavior
Main thread (and current browser window) are blocked until the user closes the dialog when there is no browserWindow specified

### How to reproduce
Check out this repo: https://github.com/santazaaa/electron-osx-dialog-bug
or
Run this simple code from the main thread or electron remote in renderer
```
console.log('before')
dialog.showOpenDialog({}, function (filePaths) {
    console.log('filePaths')
 })
console.log('after')
```
In **OS X**, I can only see the 'before' text was printed out but no 'after' text appeared until I close the dialog.
This only happens when there is **NO browserWindow argument**. With browserWindow specified, it works as expected.

This behaviour is **NOT** reproducible in Windows 10.

**Comment by alexeykuzmin** [comment]
@santazaaa Does it happen with Electron 2.0.0-beta?

**Comment by santazaaa** [comment]
@alexeykuzmin Yes, it does. Please check out this repo to reproduce https://github.com/santazaaa/electron-osx-dialog-bug

**Comment by sethlu** [comment]
@alexeykuzmin @santazaaa Currently we implemented with a blocking system API call, even though what we expose through the Electron module looks like an async method.

**Comment by codebytere** [comment]
Fixed with merge of https://github.com/electron/electron/pull/12404 :tada:
