### ISSUE TITLE
Docs are unclear about webview sandboxing

### ISSUE THREAD

**Issue by PalmerAL** [electron/electron#12379]
I've been recently looking into the sandboxing option, and I was wondering if someone could clarify whether or not sandboxing is supported in webviews. In http://electronjs.org/docs/api/sandbox-option, all of the examples seem to be written for BrowserWindows, which would make me think that it doesn't work in a webview, but there's also this line: "To enable OS-enforced sandbox on BrowserWindow or webview process...", which makes me think that it does. I tried setting the ```enable-mixed-sandbox``` flag, and creating a webview like this:
```
<webview webpreferences="sandbox=yes"/>
```
and it looks like the ```enable-sandbox``` flag is getting passed to the renderer process, but I'm not sure if that actually means the sandbox is working or not. Is there any way to verify whether it is actually enabled?

Either way, it might be a good idea to update the docs to explain this; I can submit a PR once I know what the answer is.

**Comment by miniak** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by miniak** [comment]
> Is there any way to verify whether it is actually enabled?

@PalmerAL you can check `process.sandboxed` in the preload script of the `<webview>`. Also `app.getAppMetrics()` now indicates whether the renderer process is sandboxed.
