### ISSUE TITLE
Can you bump the rate limit on libchromiumcontent-static.tar.bz2 s3 downloads?

### ISSUE THREAD

**Issue by bughit** [electron/electron#12375]
It is currently limited to ~21mbit/s and slows down building considerably.

**Comment by MarshallOfSound** [comment]
Hey @bughit, the libcc static / shared archives are stored on S3 which has no form of rate limit applied to it.  21 mb/s is probably the maximum speed you can connect to the S3 bucket either limited by your internet connection or S3 itself.

**Comment by bughit** [comment]
My bandwidth is higher than 21 mbit/s (which I verified before asking).

Found the following:

https://aws.amazon.com/blogs/developer/parallelizing-large-downloads-for-optimal-speed/

It's possible to upload these multi-gigabyte files in multiple parts (still one object).  Then the parts can be downloaded in parallel.

I did confirm that it's only one connection that's limited. Two parallel downloads, doubles the bandwidth.
