### ISSUE TITLE
ClientRequest type definition in electron.d.ts does not match documentation

### ISSUE THREAD

**Issue by cwhite-connectfirst** [electron/electron#12376]
### Versions
* electron version 1.8.4
* typescript version 2.7.2

### Expected behavior

I should be able to construct a ClientRequest object using either a configuration object or a url string without causing typescript to throw a compiler error.

### Actual behavior

Typescript throws a compiler error when I try to create a ClientRequest object with an optional configuration:
```typescript
const httpRequest = new ClientRequest({
               method: request.method,
               url: `${process.env.HTML_PROTOCOL}localhost${url}`,
               protocol: process.env.HTML_PROTOCOL,
               host: "localhost",
               path: url,
           });
```
Compiler error:
```
Error: [at-loader] ./src/electron/main.ts:25:50 
    TS2345: Argument of type '{ method: string; url: string; protocol: string; host: string; path: string; }' is not assignable to parameter of type '"method" | "url" | "session" | "partition" | "protocol" | "host" | "hostname" | "port" | "path" |...'.
  Type '{ method: string; url: string; protocol: string; host: string; path: string; }' is not assignable to type '"redirect"'.
```

I think the problem lies with the constructor signature for ClientRequest in electron.d.ts. It specifies that the type of the `options` parameter should match at least one of the literal string values  'method', 'url', 'session', etc. Here's the signature in electron.d.ts:

```typescript
// electron.d.ts, Line 1924
constructor(options: 'method' | 'url' | 'session' | 'partition' | 'protocol' | 'host' | 'hostname' | 'port' | 'path' | 'redirect');
```

The proper constructor type should specify an options parameter that accepts either a string or an object with optional properties that are listed in [the documentation for ClientRequest](https://electronjs.org/docs/api/client-request#new-clientrequestoptions). Here's a brief example :
```typescript
constructor(options: {
    method?: string,
    url?: string,
    session?: object,
// rest of optional parameters would go here
} | string);
```

**Comment by DevilishMan** [comment]
@cwhite-connectfirst you must define the options with http.options type ,like this:

const options: http.options = {
      method: 'GET',
    };
    const request = new ClientRequest(options);

**Comment by DevilishMan** [comment]
@cwhite-connectfirst you can define the options with any type,like this:
const options: any = {
      method: 'GET',
    };
const request = new ClientRequest(options);

**Comment by miniak** [comment]
```
  class ClientRequest extends NodeEventEmitter {
    // Docs: https://electronjs.org/docs/api/client-request
   ...
    /**
     * ClientRequest
     */
    constructor(options: (ClientRequestConstructorOptions) | (string));
    ...
```
