### ISSUE TITLE
RegExp have been converted to empty object in ipc data

### ISSUE THREAD

**Issue by tungvn** [electron/electron#12377]
* Electron version: 1.8.1
* Operating system: Windows 10 Pro 64-bits

### Expected behavior
ipcRenderer send an asynchorize data to ipcMain and have a RegExp inside.

### Actual behavior
The RegExp have been converted to an empty object {}

Should we support RegExp in this situation?

**Comment by MarshallOfSound** [comment]
IPC uses JSON to serialize information to send between process's.  As you can see by running `JSON.stringify(/abc/)` it results in `"{}"`.  If you want to send a regexp you will have to stringify the regexp yourself manually.

You could try doing something like `RegExp.prototype.toJSON = RegExp.prototype.toString` but it would still appear as a string at the other end.

**Comment by tungvn** [comment]
Thanks for response!

I sent an object instead (with source and flags) and rehydrated in ipcMain
