### ISSUE TITLE
Visible Property is Ignored on MenuItems with Submenus

### ISSUE THREAD

**Issue by ariporad** [electron/electron#12378]
* Electron version: 1.8.4
* Operating system: macOS High Sierra 10.13.3

### Expected behavior

If a `MenuItem` in a `tray` contains sub-`MenuItem`s and has `visible: false`, it should be invisible.

### Actual behavior

If a `MenuItem` in a `tray` contains a submenu, the `visible` property is ignored.

### How to reproduce

[Easy Link to the Exact Problem](https://github.com/ariporad/electron-quick-start/blob/master/main.js#L24-L37)

To see it for yourself:

```bash
$ git clone https://github.com/ariporad/electron-quick-start.git
$ yarn
$ yarn start
```

**Comment by sethlu** [comment]
I guess it's somewhat fixed in the latest Electron build? Tested with macOS High Sierra 10.13.4.

<img width="191" alt="screenshot 2018-04-05 15 07 36" src="https://user-images.githubusercontent.com/3168941/38394416-428f3548-38e3-11e8-96ce-50715750c9e5.png">

**Comment by ariporad** [comment]
Awesome! Thanks so much! Sorry to waste your time!
