### ISSUE TITLE
Native dependency inside preload does not work inside second window opened through window.open()

### ISSUE THREAD

**Issue by localh0rzd** [electron/electron#12390]
I've added keytar as a native dependency inside my project. However, requiring it inside a preload script only works for the main window. If I use the same preload for a window opened by window.open(), loading the preload fails.

* Electron version: 1.8.4
* Operating system: Windows 7, Windows 10

### Expected behavior

The preload script should work in both windows

### Actual behavior

Loading the script fails inside the second window.
![1](https://user-images.githubusercontent.com/2762085/37723536-dff2d1fc-2d2e-11e8-95b2-cdf5a2c35652.png)

![2018-03-21_17h30_16](https://user-images.githubusercontent.com/2762085/37723146-f8253ebe-2d2d-11e8-8537-5575742e0020.png)

After doing some research on the error message, I didn't find an explanation for different behavior inside the same application. In all cases, native dependencies did not work at all and just had to be rebuilt.

If you decide to remove the `nativeWindowOpen` option from the `BrowserWindow`, opening a second window yields disconnected DevTools and an empty view.

### How to reproduce

I've set up a minimal (non)working example to reproduce the issue. Although I've included electron-rebuild as a dependency inside the sample project, the real project, which uses electron-builder, exhibits the same behavior.

To clone and run: 

$ git clone https://github.com/localh0rzd/electron-preload-failure-minimum-setup.git
$ yarn
$ node_modules/.bin/electron-rebuild
$ yarn start

In case you use npm, run `npm install` and `npm start` respectively.

**Comment by MarshallOfSound** [comment]
@localh0rzd Can you try this out with `1.8.3` and `2.0.0-beta.5` and see if the same thing happens on your machine with those versions

**Comment by localh0rzd** [comment]
Electron 1.8.2 throught 1.8.4, 2.0.0-beta.5: Issue as described

**Comment by markypython** [comment]
What's the status of this issue?

**Comment by moloch--** [comment]
This issue also effects Electron v6.0.0.

**Comment by MarshallOfSound** [comment]
This is a limitation of nodes native modules, your native module needs to be either napi or context aware in order to be loaded twice in the same process (child windows are opened in the same process)
