### ISSUE TITLE
Can't deploy v0.31.2 to use Silverlight

### ISSUE THREAD

**Issue by karimbenammar** [electron/electron#12396]
Hi, I am new to electron and want to implement a Silverlight player inside my app, the problem is with NPAPI, since it's deprecated I can't use it with the actual electron (+chromium) version.
So I wanted to install electron 0.31.2 , it is the latest version with Chromium 44 in it, but when I try to "npm install electron@0.31.2" it says that there are no version with that reference, and here is the list

![image](https://user-images.githubusercontent.com/29929026/37739819-c6145148-2d5b-11e8-8eed-66873aaf0ff5.png)

As you can see, v0.31.2 is not listed.

If anyone even knows a way to use Silverlight with the actual electron version it would be nice, otherwise I really would like to install v0.31.2 , Thanks !

**Comment by MarshallOfSound** [comment]
Electron < `1.3.1` versions were published to the `electron-prebuilt` package 👍

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
