### ISSUE TITLE
custom protocol launch app failed in window 10 system

### ISSUE THREAD

**Issue by linfanboss** [electron/electron#12406]
* Electron version: 1.7.9
* Operating system: window 10

### Expected behavior

Hope the custom protocol  will launch app success in  window 10 system perfect.

### Actual behavior

custom protocol launch app failed in window 10 system, even double click to launch app still not work , since it was not installed well , but not error occur when installing. And not all computer with window 10
system lauch app failed.

**Comment by MarshallOfSound** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our [comment](https://github.com/electron/electron/issues/12406#issuecomment-375327890). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
