### ISSUE TITLE
loading  assets( such as js/css) with double slash  of  remote url failed

### ISSUE THREAD

**Issue by Alexis374** [electron/electron#12402]
* Electron version: 
* Operating system: Mac

### Expected behavior

When I load a remote url, the pathes of  assets(such as js/css )  starts width double slash `//`(`//aaa.js`), but in electron, they are finally requested as file protocal (`file//aaa.js`)

### Actual behavior
act as the browser do

### How to reproduce
load a url , such as `https://taobao.com`

**Comment by ckerr** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a minimal Electron app -- for example, a fork of electron-quick-start -- that a tester could run to reproduce the issue.

This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by Alexis374** [comment]
@ckerr  here is my reproduce.  https://github.com/Alexis374/electron-quick-start    

![image](https://user-images.githubusercontent.com/2499504/37815036-28812a70-2ea8-11e8-9dc7-646cb65f6d89.png)

**Comment by MarshallOfSound** [comment]
@Alexis374 You are loading that remote site with `nodeIntegration` enabled.  If you disable `nodeIntegration` everything works as expected.  There is probably some code on that site checking for a node environment (think `module` or `require`) and doing things in different ways if it is present 👍
