### ISSUE TITLE
Electron apps don't start hidden on Mac

### ISSUE THREAD

**Issue by garyking** [electron/electron#12414]
I tested with VS Code and Insomnia. For both apps, if I add them to my Mac's Login Items and checkmark Hide, and I restart, then the app starts up, but not hidden. While other apps like Chrome will start up hidden.

![Login Items](https://user-images.githubusercontent.com/343940/37687877-b24e2d52-2c73-11e8-9a73-9195a14c4cf8.png)

**Comment by MarshallOfSound** [comment]
@garyking This is down to individual apps to implement, we provide an API that let's you check if the app was launched at LogIn and whether or not the user wants the app to be hidden.

See https://electronjs.org/docs/api/app#appgetloginitemsettingsoptions-macos-windows and `wasOpenedAsHidden`

**Comment by bpasero** [comment]
@MarshallOfSound how would an Electron application be able to implement this properly? Looking at what other applications seem to do is that they startup but do not show the Window until you either click on the dock or Alt+Tab to it.

In Electron it seems to me that a window will always show when created unless you set `show: false` in the options. But that will prevent the window from being accessible by any means. What seems to be missing is an option to show the window hidden on macOS?

**Comment by MarshallOfSound** [comment]
@bpasero I believe the correct way to do this is logic like so

```js
const mainWindow = new BrowserWindow({
  show: !app.getLoginItemSettings().wasOpenedAsHidden
})

app.on('activate', () => mainWindow.show());
```

This should open a window that is invisible, and then when the dock icon is clicked the window is shown.  

I couldn't find any strict rules in the [macOS Human Interface Guidelines](https://developer.apple.com/macos/human-interface-guidelines/overview/themes/) but I did a quick check with Safari and it appeared to just put itself in the dock and not open any windows.  The help text in the preferences pane simply says "To hide an application ... check the box", to me that leaves it up to the app.  Either don't open any windows and open them on activate, or open all the windows you want and leave them invisible until the activate event. (Exactly what the code above will do).

**Comment by bpasero** [comment]
@MarshallOfSound I am seeing different results depending on the application though. For example Microsoft applications (Outlook, OneNote) open the windows in a way that they are not in foreground but Alt+Tab works to access them. Same for my news reader application (Reeder). 

I think as a user that is the behaviour I would want.

> I believe the correct way to do this is logic like so

I thought about that but it comes with issues: What if the user actually Alt+Tabs to the application, this would not trigger the activation event. As such you would end up with the application active, but no windows visible, even though it is open.

**Comment by googol7** [comment]
Slack and Skype are both Electron apps and don’t respect this "Hide" setting in the Login Items.
