### ISSUE TITLE
Global Shortcuts swallow key press event

### ISSUE THREAD

**Issue by dennyx** [electron/electron#12418]
* Electron version: 1.8.2
* Operating system: Deepin Linux 15.5 x86_64

### How to reproduce
* register 'CommandOrControl+C' to gloablShortcuts in main.js
```javascript
app.on('ready', function () {
  createWindow()
  // Then I register an shortcut
  const ret = globalShortcut.register('CommandOrControl+C', () => {
    console.log('CommandOrControl+C is pressed, do something special')
    // As 'CommandOrControl+C' is the common behavior to update clipboard in OS
    // Expect that my special action registered here could be triggered, and also the OS default behavior
  })
  if (!ret) {
    console.log('registration on CommandOrControl+C failed')
  }
  console.log(`CommandOrControl+C register ${globalShortcut.isRegistered('CommandOrControl+C')}`)
})
```
* do something special when 'CommandOrControl+C' triggered
* As 'CommandOrControl+C' is OS common behavior, would update things in clipboard, but current would not

### Actual behavior
* 'CommandOrControl+C' event is swallowed by globalShortcuts, and the OS could not update things in clipboard

### Expected behavior
* keys registered in globalShortcuts could keep popup to system, not to swallow or interrupt

this is related to https://github.com/electron/electron/issues/11226

**Comment by MarshallOfSound** [comment]
s/related to/duplicate 😄 

Merging into #11226

**Comment by dennyx** [comment]
thanks for the kindly update :smile:
