### ISSUE TITLE
Enable passing global keyboard shortcuts

### ISSUE THREAD

**Issue by Wernerson** [electron/electron#12421]
### Expected behaviour

When I process a global shortcut I would like to pass it to other applications if I don't want to catch it.

I have a shortcut that I only want to process if I press it twice within half a second. Otherwise, I would like to pass it along, e.g. to IntelliJ, etc. 

Technically it should be possible (I only know that the Windows header library in C++ offers this...).

### Actual behavior

Well, I can't do that yet :P

**Comment by MarshallOfSound** [comment]
Hey @Wernerson ,

I've looked into this in the past and the Chromium utility we use for global shortcut registration does not allow this.  If you wish to do more complicated global keyboard event handler I'd recommend using / writing your own native node module.

Here is a module you could use on Windows 👍  https://github.com/MarshallOfSound/node-lowlevel-keyboard-hook-win
