### ISSUE TITLE
new-window event not fired !

### ISSUE THREAD

**Issue by Ahmeddessouki91** [electron/electron#12430]
//main js
const { app, BrowserWindow } = require('electron')
const path = require('path')
const url = require('url')
let win

function createWindow() {
    // Create the browser window.
    win = new BrowserWindow({ width: 1260, height: 920, webPreferences: { nativeWindowOpen: true } })
    win.setTitle('EXYClinic');
    // and load the index.html of the app.
    win.loadURL(url.format({
        pathname: path.join(__dirname, 'src/index.html'),
        protocol: 'file:',
        slashes: true
    }));

    // Emitted when the window is closed.
    win.on('closed', () => {
        win = null
    });

    win.webContents.on('new-window',
        (event, url, frameName, disposition, options, additionalFeatures) => {
            console.log('new window')
            event.preventDefault()
            Object.assign(options, {
                modal: true,
                parent: win
            })
            event.newGuest = new BrowserWindow(options)
        });
}

app.on('ready', createWindow)

app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit()
    }
})

index.html

<webview autosize='on' src='https://www.exyclinic.com'></webview>

**Comment by timfish** [comment]
Hi @Ahmeddessouki91, 

You were right to ask this in Slack! The Electron maintainers use Github issues as their work backlog so it's a bad place to ask questions. 

Without seeing your `index.html` there is no way to know why the event is not getting fired. Post an example repository in Slack and I'll happily take a look.
