### ISSUE TITLE
Events for wheel are not working as expected with CTRL + Mouse Wheel

### ISSUE THREAD

**Issue by evanlarsen** [electron/electron#12436]
* Electron version: 1.8.2
  * Operating system: Windows 10 Enterprise Version 1607 (OS Build 14393.969)
  
  ### Expected behavior
  
When attaching an event listener on the window for the `wheel` event then the `wheel` event should fire when using the mouse wheel while holding down the CTRL key.
  
  ### Actual behavior
  
`wheel` event is never fired.
  
  ### How to reproduce
  
```
window.addEventListener('keydown', (ev) => { console.log('keydown:',  ev.which, 'ctrl key pressed', ev.ctrlKey); });
window.addEventListener('wheel', (ev) => { console.log('wheel: ctrl key pressed', ev.ctrlKey); });
```

The events for keydown and wheel don't work as expected when CTRL key is held down.

Holding down any key **except** CTRL will cause the `keydown` event to fire and then when using the mouse wheel the `wheel` event will fire as expected. But when holding down CTRL then using the mouse wheel, the `wheel` event does not fire.

So, when using mouse wheel the event listener has a property called `event.ctrlKey`. This value is always `false`. I can never get it to be `true` because while CTRL is held down.. the `wheel` event is never fired.

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by evanlarsen** [comment]
Thank you @sofianguy. I updated my issue to use the template.

**Comment by Devhercule** [comment]
Hi,

I confirm this issue, I have the same problem.

It works perfectly with "env.shiftkey", "env.altkey" ... but not with "env.ctrlkey"


```
document.addEventListener('mousewheel', (env) => {
  console.log(env);
  if (env.ctrlKey) {
    console.log('ctrl pressed');
  }
});
```

**Comment by pmario** [comment]
Electron version: 2.0.8
Operating system: Windows 10 Pro 64bits __and__ ubuntu 18.04

It seems as soon as the CtrlKey is pressed, the `mousewheel` event isn't triggered anymore. 

AltKey + mousewheel triggers

ShiftKey + mousewheel doesn't trigger

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by pmario** [comment]
@sofianguy ... That's an interesting reason to close the issue. ... 

There is some "How to reproduce" code in the OP and in the comment of @Devhercule https://github.com/electron/electron/issues/12436#issuecomment-383565357

```
window.addEventListener('keydown', (ev) => { console.log('keydown:',  ev.which, 'ctrl key pressed', ev.ctrlKey); });
window.addEventListener('wheel', (ev) => { console.log('wheel: ctrl key pressed', ev.ctrlKey); });
```

IMO it should be easy for you to test with the latest version.
