### ISSUE TITLE
delete role not work on macos in webview

### ISSUE THREAD

**Issue by MCMicS** [electron/electron#12435]
* Electron version: 1.8.4
* Operating system: macos
* sample: https://github.com/MCMicS/electron-issues/tree/electron-issue-12435

### Expected behavior

text of input field is deleted

### Actual behavior

The command do nothing

### How to reproduce

1. Create webview with html file with simple textinput field
2. Select tex of input field
3. click Edit -> Delete

On Windows the text is deleted. I've tested version 2.0.0-beta5 and this version works too.
If I call delete on webcontents of the webview it still works. Maybe the wrong webcontents is used

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
