### ISSUE TITLE
net::ERR_NO_SUPPORTED_PROXIES when a proxy-server includes credentials

### ISSUE THREAD

**Issue by bughit** [electron/electron#12443]
* Electron version: 1.8.4, recent master (0d7becff87743924f4fe639b802c405af47672aa)
* Operating system: win7 sp1 x64

### Expected behavior

it should navigate using the set proxy

### Actual behavior

net::ERR_NO_SUPPORTED_PROXIES is logged in the devtools console

### How to reproduce

```js
'use strict';

const {app, BrowserWindow} = require('electron'),
      path = require('path');

let brWin;

app.commandLine.appendSwitch('proxy-server', 'http://user:password@proxy_host:proxy_port');

app.on('ready', () => {
  brWin = new BrowserWindow({
    width: 1366,
    height: 768,
    closable: true,
    show: true,
    frame: true,
    useContentSize: true,
    webPreferences: {
      devtools: true,
      nodeIntegration: false,
      webviewTag: false,
      sandbox: false,
      allowRunningInsecureContent: true,
      offscreen: false,
      webSecurity: true,
      contextIsolation: true,
      //preload: path.join(__dirname, 'preload.js'),
    },
  });
  brWin.loadURL('about:blank');
  brWin.webContents.openDevTools({mode: 'right'});
});

app.on('window-all-closed', () => app.exit());
```

- load the above app
- in the devtools `location = 'http://example.org'`

**Comment by bughit** [comment]
similar issue: GoogleChrome/puppeteer#2234

**Comment by bughit** [comment]
@zcbenz

according #7828 and #625 `app.commandLine.appendSwitch('proxy-server', 'http://user:password@proxy_host:proxy_port')` should be working 

Did something change with the format?  Should this work with any auth that chromium supports in addition to basic (NTLM, Negotiate, etc)?

**Comment by bughit** [comment]
@zcbenz 

Am I misunderstanding what you're saying [here](https://github.com/electron/electron/issues/7828#issuecomment-260843771)

> You can set the proxy by putting username and password as part of proxy URL.

because it looks like chromium [does not support that](https://bugs.chromium.org/p/chromium/issues/detail?id=615947)?

**Comment by zcbenz** [comment]
I was wrong that we could pass credentials in the command line flag, we should update the docs on this since Chromium marked it as won't fix.

**Comment by shobhitchittora** [comment]
@zcbenz I'm new here and would like to start contributing with this one. Can you point me to the doc which needs updating and also what to update ?

**Comment by teh-f00l** [comment]
Is anyone still working on this issue? If not may I take over?

**Comment by BeniCheni** [comment]
Hello, @zcbenz & @bughit. I analyzed the previous comments and gave this "_good first issue_" a try with #14198, since there hasn't been any activity since Jun 25. Hope I analyzed the details correctly and did the PR correctly. Looking forward to your review.

**Comment by Buminta** [comment]
I have same problem! Please give me how to fix it?

**Comment by nornagon** [comment]
The docs have been updated to indicate that this is not supported when passing a proxy on the command line, so I'm closing this.

**Comment by hellpain1412** [comment]
Did anyone found a solution to this issue?
