### ISSUE TITLE
Node.js npm

### ISSUE THREAD

**Issue by w1wwwwww** [electron/electron#12440]
Npm will give an error each time I open it so I can not download.
Could you add an installer directly of the website

Os: Windows 10 
Computer: HP ProBook

Reproduction

None.

Error

Something about not being installed proporly.
Node.js version 9.0.0

Thanks, The Derp Team
 Contact us at: www.thederpsquad.com/contact

**Comment by felixrieseberg** [comment]
Could you include the actual error?

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).

**Comment by w1wwwwww** [comment]
No it went by too fast
