### ISSUE TITLE
feature: running without userData persistence

### ISSUE THREAD

**Issue by bughit** [electron/electron#12442]
`app.setPath('userData', null);`

chromium is probably capable of this since this is more or less incognito mode

useful for consistent automation runs

**Comment by MarshallOfSound** [comment]
@bughit If you don't want data persisted simply use a non persistent session.

```js
nee BrowserWindow({
  partition: 'random string'
})
```

**Comment by bughit** [comment]
@MarshallOfSound 

sorry, forgot about partitions

one question about session.fromPartition(partition[, options])

>  if there is no persist: prefix, the page will use an in-memory session

bet there's a cache option

> cache Boolean - Whether to enable cache.

if it's a memory session, what cache does this enable?
