### ISSUE TITLE
Electron App need to grant access 

### ISSUE THREAD

**Issue by pihey12** [electron/electron#12444]
I created an Electron APP in windows with gkm packages and all functions are working. In macOS, it needed to allow the app from privacy settings so that the function of the app is working. Is there another way to count the per mouse click and keyboard press of electron app in macOS that not needed to be manually grant access or allowed in privacy setting?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
