### ISSUE TITLE
Menu.popup() is always executed async in 1.8.4

### ISSUE THREAD

**Issue by andycreeth** [electron/electron#12451]
We are noticing after upgrading from Electron 1.7.12 to 1.8.4 that all of our context menus suddenly became async.  Not only is default behavior changed, but it seems that we can't manually force it using `async: false` either.  This is problematic because we are currently calling `Menu.destroy()` immediately after `Menu.popup()` due to issue https://github.com/electron/electron/issues/9823 which AFAIK is not resolved in 1.8.x.  After upgrading, because all of our menus became asynchronous, they are immediately destroyed before the user can take any action.

Here are all the details about the issue, and test repo where you can see the problem.  Note that I've only tested this on Windows.

* Electron version: 1.8.4
* Operating system: Windows 10 64-bit

### Expected behavior

Calling `Menu.popup()` should block execution until the context menu is closed.

### Actual behavior

`Menu.popup()` returns immediately, and the next line of code is executed while the menu is still open.

### How to reproduce

- Clone this repo: https://github.com/andycreeth/electron-quick-start `master` branch
- Start the app: `yarn start`
- Right click
- Alert pops up immediately rather than after the menu has been dismissed

If you now downgrade electron to 1.7.13 you will notice that the behavior changes, and the menu is synchronous, as expected.

### Right click behavior with Electron 1.8.4
![image](https://user-images.githubusercontent.com/3180181/37994778-6e241912-31c7-11e8-9342-2fa55ce76153.png)

### Right click behavior with Electron 1.7.13:
![image](https://user-images.githubusercontent.com/3180181/37994718-3c8a4188-31c7-11e8-92cf-5df33f0d691a.png)

**Comment by andycreeth** [comment]
Also, I recognize that since all menus are `async` in 2.x, it might not be worth fixing this.  However, without the `callback` option for `Menu.popup` it makes async menus very difficult to use and clean up from.

**Comment by MarshallOfSound** [comment]
https://github.com/electron/electron/pull/11546. `menu.popup` does take a callback for this scenario.  Does that not work for you?

**Comment by andycreeth** [comment]
@MarshallOfSound The `callback` option doesn't seem to be available in 1.8.4.  I think that is available in 2.0 only.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
