### ISSUE TITLE
how to trigger dom click event in preload.js of the webview module?

### ISSUE THREAD

**Issue by jxiangji** [electron/electron#12457]
in webview load a third party page，and preload a preload.js.
 And now I want to trigger the click  event `$dom.trigger('click')` of three party pages manually , i sure the DOM rendering is completed when click event being executed,but there is no any effect or error.
but it's work correctly when  i cope the code to Console Desk then execute it.
I would like to ask what security restrictions has been made in WebView? and it cause cant trigger any click events in the preload.js

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
