### ISSUE TITLE
ipc consumpt CPU on single core CPU

### ISSUE THREAD

**Issue by theanhmx** [electron/electron#12459]
hi,
i'm trying to make my app work on a single core CPU system (windows 7 32bits).
i end up move all the I/O operations to the child_process(s) but the issue came when i call process.send() and cp.on('message'), sometimes it make the CPU work at 100% for every long time.
here is the sample code of main.js
`app.on('ready', async () => {
  function init() {
    child = cp.fork(path.join(__dirname,'child.js'))
    child.on('message', (message) => {
      console.log('Storage Helper - got message: ' + message)
    })
    setInterval(function() {
      child.send('setTimeout message')
    }, 5000)
  }
  init()
})`

child.js code:
`
process.send('child process created: ' + process.pid)
process.on('message', (msg) => {
  console.log('child - ',msg)
})
`

i already tried the same code running outside of electron main process and the issue doesn't happen.
event when i increased the interval time to 15 or 20s, still doesn't help.

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
