### ISSUE TITLE
HTML5 <video> Freezes And Timeline Skips To End

### ISSUE THREAD

**Issue by CodeCookieGH** [electron/electron#12465]
Any videos of this type play fine if I open it in Chrome. I used the same HTML in my Electron quick-start index.html: 

```
<video id="v" controls autoplay>
     <source src="file:///D:/---/New/Replay%202018-03-27%2016-35-57.mp4" type="video/mp4">
  </video>
```
Here are the video's stats:
```
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.84.100
  Duration: 00:01:59.18, start: 0.000000, bitrate: 30411 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv), 1280x
720 [SAR 1:1 DAR 16:9], 30012 kb/s, 60 fps, 60 tbr, 15360 tbn (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, flt
p, 127 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Stream #0:2(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, flt
p, 128 kb/s
    Metadata:
      handler_name    : SoundHandler
    Stream #0:3(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, flt
p, 128 kb/s
    Metadata:
      handler_name    : SoundHandler
```
The video plays up until about 1min 19sec, then freezes and the timeline skips to the end. I can skip on the timeline to play further, but it can still have these freezing problems later.

Some version info:

`Windows7 64bit Electron v1.8.4 Chromium v59.0.3071.115 Node v8.2.1 v8 v5.9.211.38`

I'm also running the app through a .bat file if that's of any use:

`C:\Users\---\node_modules\electron\dist\electron.exe C:\Users\---\Documents\GitHub\electron-quick-start`

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
