### ISSUE TITLE
setInterval().unref() is not a function

### ISSUE THREAD

**Issue by NikhilMutkekar** [electron/electron#12462]
* Electron version: 1.4.16
* Operating system: Windows 10

### Expected behavior

 Using jsreport-core to generate PDF from HTML. jsreport.init() should get initialized and render content into pdf file.
### Actual behavior

jsreport.init() throws an error ``Unhandled rejection TypeError: setInterval(...).unref is not a function
    at Reporter._startReaper ``
Ideally running on Node.js server and web browser, It generates pdf. But same application throws error while being executed from Eelctron.

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).

**Comment by NikhilMutkekar** [comment]
Yes, I did so before raising it here since I dint get any response on slack channel.

**Comment by joshuapinter** [comment]
Try this: 

```js
setTimeout(function () {}).__proto__.unref = function () {}
```

From https://github.com/bugsnag/bugsnag-js/issues/459#issuecomment-452303838.
