### ISSUE TITLE
[Feature Request] BrowserWindow listener for setAlwaysOnTop toggle

### ISSUE THREAD

**Issue by benjtinsley** [electron/electron#12466]
I'm looking to build a feature in my app to give user feedback if they have set their window to always show on top of other apps using a shortcut or application menu item, but find that there is a lot of hacking needed to do so. It may be more efficient to have an event listener set on the window to determine if it enters or leaves `win.setAlwaysOnTop()`

i'm thinking it would be `win.on('enter-always-on-top')` and `win.on('leave-always-on-top')`

**Comment by codebytere** [comment]
hey @benjtinsley i found some time to have a go at this, it's linked above!
