### ISSUE TITLE
What is the status of Web VR support in electron?

### ISSUE THREAD

**Issue by HeadClot** [electron/electron#12468]
Hey,

What is the status of WebVR support in Electron js?

Last I have seen on this subject is [here](https://github.com/electron/electron/issues/3271)
Sorry for posting this in the git hub issues section. I have been trying to get an answer to this on the slack channel for electron. I just have not gotten a answer.

**Comment by MarshallOfSound** [comment]
WebVR is at the same point (or behind) as Chromium.  As soon as a Chromium version completely supports webVR Electron will pick it up.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by stephanedemotte** [comment]
Any news on this ? Try to activate `experimentalFeatures` with no success :/
