### ISSUE TITLE
Weird black line shown under macOS menu bar when window is focused

### ISSUE THREAD

**Issue by hjkcai** [electron/electron#12463]
* Electron version: Unknown
* Operating system: macOS 10.13.3

Steps to Reproduce:

1. Uncheck 'Use dark menu bar and Dock' option in system preference
2. Open a new vscode window
3. Switch it to fullscreen
4. Switch it back and you will see the black line under the menu bar

![image](https://user-images.githubusercontent.com/731326/38011041-53e14102-328e-11e8-826c-a2a6bff6700a.png)

5. Move focus out of vscode and the black line will disappear

![image](https://user-images.githubusercontent.com/731326/38011066-6f26df44-328e-11e8-8ee6-4e84e5481891.png)

It looks sooooooooooo weird!

This bug can be also reproduced on some other Electron apps (I have tested Vysor and Wechat Devtool)

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR.
