### ISSUE TITLE
Memery Leaking when call [ remote.ipcMain.on ]

### ISSUE THREAD

**Issue by YangShengHaHa** [electron/electron#12469]
* Electron version: 1.7.11
* Operating system Window 7:

remote.ipcMain.on method has memery leaking.

### How to reproduce
when call remote.ipcMain.on("", fn), there is a leaking named "Error at xxxxx" was nerver released.

Source Code File:
callbacks-registry.js

Code:
```
add (callback) {
    // The callback is already added.
    var filenameAndLine, id, location, match, ref, regexp, **stackString**
    id = v8Util.getHiddenValue(callback, 'callbackId')
    if (id != null) {
      return id
    }
    id = ++this.nextId

    // Capture the location of the function and put it in the ID string,
    // so that release errors can be tracked down easily.
    regexp = /at (.*)/gi
    stackString = (new Error()).stack
    while ((match = regexp.exec(stackString)) !== null) {
      location = match[1]
      if (location.indexOf('(native)') !== -1) {
        continue
      }
      if (location.indexOf('electron.asar') !== -1) {
        continue
      }
      ref = /([^/^)]*)\)?$/gi.exec(location)
      filenameAndLine = ref[1]
      break
    }
    this.callbacks[id] = callback
    v8Util.setHiddenValue(callback, 'callbackId', id)
    v8Util.setHiddenValue(callback, 'location', filenameAndLine)
    return id
  }
```

The Var **stackString** was nerver been released.
When call remote.ipcMain.on, it think it needs to add **stackString = null**

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.
