### ISSUE TITLE
Chrome Debugging Protocol - /json/new Could not create new page

### ISSUE THREAD

**Issue by windht** [electron/electron#12474]
- Electron version: 1.8.3
- Operating system: windows 10

### Expected behavior

After running application with flag `--remote-debugging-port=9222` , I can visit `localhost:9222/json` and have a look at sets of tabs I've opened.

### Actual behavior

However if I want to create new page within the CDP, like visiting `localhost:9222/json/new` , it gives me error saying `Could not create new page`.

Is this related to the Chromium build inside electron limited API exposed from CDP?

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
