### ISSUE TITLE
disposition on a `new-window` webContents event is always equal to a blank string. 

### ISSUE THREAD

**Issue by eengoron** [electron/electron#12473]
Hi everyone :). I noticed a strange bug  in 1.8.4 where, on`new-window`events, disposition is always equal to a blank string. 

* Electron version: 1.8.4
* Operating system: 10.13.3 High Sierra

### Expected behavior

disposition should be equal to one of the following options when a `new-window` event happens: `default`, `foreground-tab`, `background-tab`, `new-window`, `save-to-disk` or `other`.

### Actual behavior

Disposition is blank (`""`)

### How to reproduce

I made a repo available here to highlight this issue: https://github.com/eengoron/electron-quick-start
To clone the repo and run the example:
```bash
# Clone this repository
git clone https://github.com/eengoron/electron-quick-start.git
# Go into the repository
cd electron-quick-start
# Install dependencies
npm install
# Run the app
npm start
```

Once the example is running, if you create a `new-window` event by clicking a link on the Google homepage using `Cmd+Click` or `Shift+Click` or `Cmd+Shift+Click` etc, you'll see that disposition is blank in two ways:

1) A blank line will be printed in your console
2) After the blank line a statement will be printed that says: 
`disposition === "" is true` 
This statement only prints if the conditional `disposition === ""` is true.

Thanks for looking into this!

**Comment by nornagon** [comment]
Looks like you're printing out the `frameName`, not the `disposition`. `disposition` is the fourth argument to the `new-window` event callback.
