### ISSUE TITLE
About debian arm7l

### ISSUE THREAD

**Issue by CMiworld** [electron/electron#12475]
Chromium in my system, can normal visit website.When I use "NPM start" start electron can run but can't see the view, often appear the following error
> npm start
1.libgl error : mesa-loader: failed to retrieve device information
2.libgl error : unable to load driver：rockchip_dri.so
3.libgl error : driver pointer missing
4:libgl error : failed to load driver : rockship
I don't know what to do?I am a need to modify the eletron some configurations?Or apt - get the install packagename?Still looking for my motherboard manufacturer for support electron?

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
