### ISSUE TITLE
add chrome extension problem: content_scripts doesn't support "all_frames"

### ISSUE THREAD

**Issue by chongchai** [electron/electron#12489]
* Electron version: 1.7.9
* Operating system: windows

### How to reproduce

I have a chrome extension to use in electron.  The extension will change all iframes' css and js.
But In electron, the css and js take effect in top page and fails in other iframes in pages

my manifest.json is : 
```
{
  "manifest_version": 2,

  "name": "Modify CSS and HTML",
  "version": "0.1.0",
  "description": "Lateral blog post demo extension",

  "content_scripts": [
    {
      "matches": [
        "(*://*.xx.com/*)"
      ],
      "all_frames": true,
      "js": [
        "/content.js"
      ],
      "css": ["/styles.css"]
    }
  ]
}
```

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).

**Comment by binux** [comment]
This is a feature request, as electron lack of `all_frames` support for content_scripts
via https://github.com/electron/electron/blob/003a92e0990fa4ba1bd7b93450eb3afae0533090/lib/browser/chrome-extension.js#L234
