### ISSUE TITLE
Feature Suggestion:  Add In App Purchases APIs to Windows and Linux

### ISSUE THREAD

**Issue by AluminiumTech** [electron/electron#12483]
I'd like to suggest that Windows, macOS and Linux get support for In App Purchases. Electron could use  the [W3C HTML Payment Request API](https://www.w3.org/TR/payment-request/) . This is supported by Chromium 60 or newer, therefore I think it should be added to Electron 2.0 Beta.

The inspiration for this was the [Mac App Store In App Purchase PR](https://github.com/electron/electron/pull/11292).

Respectfully, I'd also like to suggest that macOS also be able to use this API if devs want as I can imagine not everybody will want to publish their Electron App to the Mac App Store. This means that a different name would be needed for the Mac App Store IAP API to differentiate between the two. 

* Operating system: Ubuntu 17.10.1

Thanks

**Comment by MarshallOfSound** [comment]
@AluminiumTech Afaik this API is mostly backed by Chromium's UI and doesn't actually offer anything other than the UI to enter/select payment information.  This kind of thing can easily be implemented in userland as an HTML form of some kind (and has been for years), the only advantage of it being a standard API is that browsers can provide direct access to payment methods or saved payment credentials.  Electron can do neither of those and we don't normally implement UI for anything.  This isn't something we can tackle.

Let me know if I've misunderstood this request 😄
