### ISSUE TITLE
Is MUSL supported yet?

### ISSUE THREAD

**Issue by kenny-w7** [electron/electron#12484]
This is what I get when I try to start electron with npm start:
https://pastebin.com/syAbXR90

electron-quick-start, npm start:
https://pastebin.com/PZyba3su

And when trying to launch Etcher[with npm]:
https://pastebin.com/eLbyrM9v

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).

**Comment by kenny-w7** [comment]
Could you guys maybe respond to the feature request that was made for Void MUSL?
