### ISSUE TITLE
macOS localhost 404

### ISSUE THREAD

**Issue by GhostlyDark** [electron/electron#12495]
Electron version: v2.0.0-beta.6
Operating system: macOS 10.13.4

### Expected behavior

index.htm is found

### Actual behavior

index.htm is not there (404 error)

### How to reproduce

[macOS localhost 404.zip](https://github.com/electron/electron/files/1866452/macOS.localhost.404.zip)

### Information

I am running a local webserver when starting Electron. The exact same code works just fine under both Windows and Linux, sucessfully loading index.htm as localhost:9000/resources/app/index.htm. However, on macOS index.htm cannot be found. I am able to reach localhost:9000 via Safari, so the server is sucessfully running (so I assume at least). I can't reach any files though. I am out of ideas, so im asking for help here.

**Comment by ckerr** [comment]
Present in 1-8-x as well

**Comment by nitsakh** [comment]
After a little more investigation, it turns out that the code is looking for the `index.htm` file in the wrong path under `resources/app/'. Also the server code looks for the file relative to the current path.

**Comment by nitsakh** [comment]
Closing this issue as it is not an electron bug.

**Comment by GhostlyDark** [comment]
I still can't figure out what the right path for macOS would be, since 'contents/resources/app' or anything similar doesn't work either.  Is the server.js code (because of relative file paths) simply not suitable for macOS?

I know this place is for fixing electron bugs, but it would be awesome to get an answer nonetheless.
