### ISSUE TITLE
shell.openExternal(..., {activate:false}) opens in foreground

### ISSUE THREAD

**Issue by amarpatel** [electron/electron#12492]
Electron version: 1.7.11
Operating system: macOS 10.13.3

`shell.openExternal('http://google.com', {activate:false})` is opening urls in the foreground.

Related to #7174

**Comment by nitsakh** [comment]
Hey @amarpatel ! I just tried to repro this on macOS and electron version that you've mentioned, but couldn't repro it. Would you mind providing more information, or some example app? Do you see this in later versions of electron as well?

**Comment by amarpatel** [comment]
Sure, I'm using it [here](https://github.com/amarpatel/Trivia-App-Helper/blob/master/app/containers/ScreenshotPreview.js#L58) and an example of that call can be seen when I click the "GO" button [here](https://www.youtube.com/watch?v=U1btuWZV-aM&feature=youtu.be).

**Comment by nitsakh** [comment]
It's pretty hard to conclude much from the video itself. Would you mind pointing to a minimal isolated example that shows the behaviour? From my tests, I was not able to repro this with the simple electron app.

**Comment by CharlieHess** [comment]
I can reproduce this, but only with Chrome set as my default browser, and specifically Chrome 69. If you try something like `tel:8675309` or change your default browser you'll notice that it starts respecting the `activate` parameter.

So I think we should file this against Chromium, but lemme do some more digging.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by lafave** [comment]
I'm still seeing this issue in Electron v3.1.6. Running MacOS Mojave 10.14.3.

Specifically, the `{activate: false}` option always opens a URL in the foreground if Chrome (72.0.3626.121) is the default browser. If Safari (12.0.3) or Firefox (65.0.1) are the default browser then they open in the background as expected.

The use case here is to open links without losing focus of the Electron app if the command key is held down.

**Comment by sirbrillig** [comment]
I'm seeing this bug with Mac OS Mojave 10.14.6 and Electron 9.1.2 and Chrome Version 84.0.4147.105. As with the previous reports, it works fine if Firefox is set as the default browser, but not Chrome.

**Comment by sirbrillig** [comment]
I think this is probably the Chrome bug that's causing this: https://bugs.chromium.org/p/chromium/issues/detail?id=854609

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
