### ISSUE TITLE
app.setLoginItemSettings creates duplicate entries in Startup on Windows

### ISSUE THREAD

**Issue by CydeSwype** [electron/electron#12491]
* Electron version: 1.8.2
* Operating system: Windows 10 64-bit

### Expected behavior

A single entry created in the Startup applications for the current user

### Actual behavior

Duplicate entries in the Startup applications for the current user

### How to reproduce

The reproducible steps simulate an overinstall via auto-update (a common use case). I can consistently get multiple entries in the Startup applications for a given user using the below repro steps.  I've reproduced this with multiple apps (including zeit's now app).  I've mostly encountered this with installing and running the built app (vs. npm start in debug mode; the now-desktop app doesn't install into Startup in local dev mode). 

1. install and run from https://zeit.co/download
2. install again (this is to simulate an auto-update)
3. restart machine
4. install once more
5. under task manager -> startup note the multiple instances

source available at https://github.com/zeit/now-desktop

Here's the relevant code:
```
const firstRun = require('first-run')
const isDev = process.mainModule.filename.indexOf('app.asar') === -1

const registerAutoLaunch = () => {
  if (!isDev && firstRun()) {
    app.setLoginItemSettings({
      openAtLogin: true,
      openAsHidden: true
    })
  }
}
```

Here's a screenshot from the now-desktop app after a couple overinstalls and a restart
![capture](https://user-images.githubusercontent.com/626391/38162461-950b5fbe-3496-11e8-8132-49d5c07ad77b.PNG)

Here's a screenshot showing a similar issue with the app that I'm working on (same repro steps). 

![capture](https://user-images.githubusercontent.com/626391/38162375-e094c4c2-3494-11e8-8ad7-2de9ff229d32.PNG)

**Comment by Syed-Umair** [comment]
+1

**Comment by paulcbetts** [comment]
Those entries are the renderer processes and other child processes you're launching on startup, Windows displays these in a Weird Way. Every multiprocess application will display this way in the Startup pane :-/
