### ISSUE TITLE
[Feature request] Promise based IPC communication

### ISSUE THREAD

**Issue by AoDev** [electron/electron#12502]
#### Context
Hello,

It seems that a lot of people are interested in having IPC communication through promises.
In fact, one can find almost **[10 modules on npm](https://www.npmjs.com/search?q=electron%20ipc%20promise)** for that purpose.

I also made my own util. So it seems a regular problem that people are solving and it would be good to have this natively supported in Electron.

Before going any further, the question is would you be open to such addition for Electron?

#### More details

The main reasons I've been doing this is for code understanding and message correlation. Meaning that I don't need to explicitly code a mechanism to identify which response corresponds to which call and the usual async flow can be used to wait for the response before continuing.

So, the code can be written like this:

```javascript
// in renderer
async doSomethingInMain('with this data') {
  const result = await ipcUtil.sendMain('handlerInMain', 'data')
  const updatedResult = doMoreThingsWithResult(result)
  return updatedResult
}
```

`sendMain` and its main process counterpart implementation can vary in all the modules published. For example, in my util I use a `random generated response channel id` to which the main process will send back the response.

What do you think?

**Comment by MarshallOfSound** [comment]
Making IPC have a request-response style is something I believe belongs firmly in userland, you can implement this style if you want but it isn't something that we would implement in core.

As you mentioned there are multiple implementations of this already.
