### ISSUE TITLE
Support Node / Preload scripts in iframes or workers

### ISSUE THREAD

**Issue by pfrazee** [electron/electron#12505]
* Electron version: v2.0.0-beta.6
* Operating system: MacOS 10.12

### Expected behavior

Hey all! Thanks to https://github.com/electron/electron/pull/10430, the preload script should run in renderers, webviews, iframes, and web workers.

### Actual behavior

It only runs in renderers and webviews.

### How to reproduce

https://github.com/pfrazee/electron-bug-test-preload

Console will emit true/false for whether the preload ran in the renderer, an iframe, and a worker. At time of writing this demo, only true for renderer.

```
git clone https://github.com/pfrazee/electron-bug-test-preload
cd electron-bug-test-preload
npm install
npm start
```

**Comment by MarshallOfSound** [comment]
Please note that that PR wasn't intended to make preloads run in iframes.  This should be considered an enhancement request not a bug :+1:

**Comment by pfrazee** [comment]
@MarshallOfSound Oh my bad, I misread that.

Well if there's nobody that can hit the enhancement easily, I can try to slot some time to implement it.

**Comment by Tim91084** [comment]
This would be a great enhancement.  I've also tried using extensions to run code within iframes, and that does not work either.  Seems like the extension manifest option "all_frames" is also not supported within electron.  So, as far as I can tell, there is no way to accomplish running a script within an iframe similar to how a preload script works for a webview.

@pfrazee, I'd be happy to help out in any way if you needed.

**Comment by pfrazee** [comment]
Appreciate it! We’ll need to give this one some thought

**Comment by pfrazee** [comment]
I explored what this might require for Web Workers. See the changes made here: https://github.com/electron/electron/compare/master...pfrazee:worker-preload-exploration

The approach I took was to set `nodeIntegrationInWorker` to `true` in my [test app](https://github.com/pfrazee/electron-bug-test-preload) and then copy over a lot of behaviors from the `lib/renderer` JS. Assuming this is the right way forward (and I don't know enough to know if it is), then I assume the next step would be to always do "node integration" to workers, but follow the logic similar to 'renderer' which removes the node-specific globals after executing the preload.

Results of this exploration:

 - I was able to successfully include the session preloads.
 - Through some hacks, I was able to get the `ipcRenderer` API in my preload, but the methods didn't work because the internal implementation didn't find a frame for the Worker. At that point I was out of my depth so I quit. (Note, the `ipcRenderer` is the only reason I want preloads in iframes and workers: I use it to add Web APIs.)

I believe this approach requires node to be attached to every Web Worker, regardless of whether a preload script is being used or `nodeIntegrationInWorker` is enabled. I assume that's the same cost behind every other preload script.

Hope this was helpful.

**Comment by burtonator** [comment]
Seems like this is still broken as of 3.0.0-beta4

**Comment by pfrazee** [comment]
@MarshallOfSound 🎉 !

**Comment by Spongman** [comment]
is it possible to run preloads when `nodeIntegrationInSubFrames` is false? `nodeIntegrationInSubFrames` breaks the code in my iframes as they don't expect the node stuff to be defined, and they break if it is. but i need to run the preloads there regardless. is this possible?

**Comment by MarshallOfSound** [comment]
@Spongman `nodeIntegrationInSubFrames: true` && `nodeIntegration: false`

**Comment by Obi-Dann** [comment]
Sorry for resurrecting an old issue... 
It looks like `preload` scripts don't run in web workers, it looks like it only the PR only implemented it for iframes https://github.com/electron/electron/pull/16425, right? I wonder if supporting preloads for web workers can be added as well?
