### ISSUE TITLE
how to deploy app to ios and android

### ISSUE THREAD

**Issue by mxmxlwlw** [electron/electron#12500]
Hi,
    Sorry to bother you. I just want some advice on deploying my app to ios and android.

**Comment by ckerr** [comment]
Hi @mxmxlwlw,

Electron doesn't currently support iOS or Android. We would happily accept patches for this but implementing it is not currently on our timeline.

See also https://github.com/electron/electron/issues/562, https://github.com/yhatt/marp/issues/180
