### ISSUE TITLE
Mouse cursor disappears when it enters the text editing area of Atom and VS Code

### ISSUE THREAD

**Issue by rayhinton** [electron/electron#12519]
* Electron version: Atom 1.25.0 and Visual Studio Code 1.21.1
* Operating system: macOS 10.13.4 (just recently upgraded yesterday morning, before this started happening)

### Expected behavior

The mouse cursor should be visible in the editing area.

### Actual behavior

The mouse cursor is not visible in the editing area.

### How to reproduce

1. Open a document in Atom, using any Dark theme as your Syntax Theme.
2. Make sure your Atom window is in focus. Move your mouse cursor outside the Atom window, then drag it into the middle of the text editing area.
3. Observe that the mouse cursor disappears when you move it inside the text editing area.
4. Change the Syntax Theme to any Light theme, and repeat step 2. Observe that the mouse cursor does not disappear.

Similar happens in VS code with dark themes. Over at atom/atom#17069, some helpful folks helped me determine that: 

- this happens on my external monitor over 1080p. When I reduce the resolution on my monitor to 1080p, then the cursor behaves correctly. **Another edit**, as per comments below: when set to Default for Display, the cursor also displays properly.
- I also tried the following, but neither fixed the issue:
    - loading atom via command line with various options (including safe mode); and 
    - changing the color profiles for my monitor.

**Edit:** This [Stackoverflow question](https://stackoverflow.com/questions/6738220/changing-the-mouses-i-beam-cursor-in-xcode-4) looks very relevant. Noteably, if I increase my cursor size in macOS (System Preferences > Accessibility > Display > Cursor Size), then the text cursor is actually visible in dark themes.

**Comment by henrinormak** [comment]
Also reproduces here, can also confirm that if an external display is connected, the internal display still works fine (i.e moving window between the two screens). It also works fine on the external display (4K) if the display setting is set to Default for Display (System Prefs > Displays > Display > Resolution).

**Comment by rayhinton** [comment]
Ah yes, thanks @henrinormak, that adds some more context! I am running at 2560x1440 on my external monitor most of the time. When I set it to default for display (4K), the cursor also displays correctly.

**Comment by andrewbrannan** [comment]
Just noticed this is happening to me as well in Atom.  Similar setup:
- macOS 10.13.4
- MacBookPro14,2
- External 4K monitor scaled to 3008 x 1692 @ 60 Hz

I just updated MacOS and it wasn't happening before.  Working around it right now with @rayhinton's tip: (System Preferences > Accessibility > Display > Cursor Size) and moving the slider to increase the cursor size a tiny bit.  It works then.

**Comment by robinkraft** [comment]
Exact same situation as @andrewbrannan. Here's a screenshot showing how little you need to move the slider. It's really not noticeable.

![image](https://user-images.githubusercontent.com/428784/38581396-a02292a4-3cc1-11e8-8fc1-3497eab9fff7.png)

**Comment by asselstine** [comment]
I'm having the same problem:

- Mac OS X 10.13.4
- Atom 1.25.1
- External monitor at 2560x1440

@robinkraft I can confirm that increasing the cursor size slightly in accessibility works.

I can also confirm that the other themes worked even without the cursor size change.  However, I like the 'One Dark' theme so I'm sticking with the cursor size increase.

**Comment by msutherl** [comment]
Increasing the cursors size causes other cursors not to appear at all on my system. Hoping a solution to this issue can be found.

**Comment by chibicode** [comment]
Had the same problem with macOS 10.13.4. Changing cursor size by a tiny bit fixed it for me.

https://github.com/Microsoft/vscode/issues/44211#issuecomment-381612843

<img width="668" alt="screen shot 2018-06-08 at 3 58 25 pm" src="https://user-images.githubusercontent.com/992008/41184375-cbdc6d24-6b34-11e8-8d76-6ddd05e909c3.png">

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
