### ISSUE TITLE
Cannot navigate select options via keyboard events.

### ISSUE THREAD

**Issue by themihai** [electron/electron#12513]
I need to control a web app remotely. To do that I considered sending keyboard events via  IPC. 

* Electron version:
1.8.2
* Operating system:
Mac OS

### Expected behavior
 I expected the same behaviour as using the physical keyboard. E.e. on first press on  "down" key the select menu should open, on the 2nd press it should move the focus on the 2nd option from the list.

### Actual behavior
On first press  `<select>` menu is open. However after that no key code is working: arrow up/down don't move the cursor on different options, nor does "Enter/Return" selects an option. I believe Chrome is using an internal/different API to control the select menu navigation. 

### How to reproduce
page to load into electron

```
<!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8"/>
      <meta name="viewport" content="width=1280,user-scalable=0">
   </head>
   <body>
  
         <form  method="get" action="">
        <select autofocus="true" name="audioLanguage" id="audioLanguage">
                  <option class="audioNameValue" value="en-US">English</option>
                  <option class="audioNameValue" value="fr-US">French</option>

                  </select>
                  <br>
         </form>
   </body>
   <script>


const ipcRenderer = require('electron').ipcRenderer;

// https://stackoverflow.com/a/45148472/613453
function sendToIPC(ev){
 
   ev.type = 'keyDown'
    ipcRenderer.send('KeyboardRequest', ev);
    // log result
    console.log(ev);
       ev.type = 'keyUp'
   ipcRenderer.send('KeyboardRequest', ev);
    // log result
    console.log(ev);
}


    // This should open the select menu(after  4 seconds)
    setTimeout(function() {
       ipcEV = {"type": "keyDown", "keyCode": "Down", "isTrusted": true};
       sendToIPC(ipcEV);   
    }, 4000);
    // This should move the selection to the next option after 8 seconds
    setTimeout(function() {
       ipcEV = {"type": "keyDown", "keyCode": "Down", "isTrusted": true};
       sendToIPC(ipcEV);   
    }, 8000);


function onkeyEvent(evt ){
    console.log(evt);
}
window.addEventListener('keyup', onkeyEvent, true);
window.addEventListener('keydown', onkeyEvent, true);
window.addEventListener('keypress', onkeyEvent, true);
   </script>
</html>
```

main.js

```
const electron = require('electron');
const { app, ipcMain, BrowserWindow } = require('electron');


let mainWindow;
 

const createWindow = () => {
  if (app.isInApplicationsFolder() !== true){
     // app.moveToApplicationsFolder();
  }
  mainWindow = new BrowserWindow({
    'web-preferences': {'web-security': false}
  });

  mainWindow.loadURL("http://localhost:7070/test.html");

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
  let contents = mainWindow.webContents

  const ipcMain = require('electron').ipcMain;

  ipcMain.on('KeyboardRequest', function(event, arg) {
    // executed on event
    console.log(arg);
    contents.sendInputEvent(arg);
  });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed.
app.on('window-all-closed', function () {
    app.quit();
});

app.on('activate', function () {

  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (mainWindow === null) {
    createWindow();
  }
});

```

**Comment by sethlu** [comment]
@themihai I don't think Chromium, Safari (or other ones too) capture events from the system dropdown list. Sending input events to the system dropdown is similarly difficult.

Some reference: https://stackoverflow.com/questions/19183715/keydown-event-in-drop-down-list

**Comment by themihai** [comment]
I don't need  to capture the events from the system dropdown list(even though that would be nice). I  just need to send keyboard events while `select` is focused. That's because the application is remotely controlled (via a websockets from a mobile app).  I believe Electron should be able to send "real" keyboard events to the Window. 

 As a workaround currently I'm sending the keyboard events (when I detect `select` is focused) using system dependent implementations(i.e. on MacOS I'm using an AppleScript like `tell System Events to key code $keyCode`).

**Comment by MarshallOfSound** [comment]
> I believe Electron should be able to send "real" keyboard events to the Window.

This is not an Electron responsibility, there are userland modules that can do this.  Check out `robotjs` for instance
