### ISSUE TITLE
webview's event handler "will-prevent-unload" does not ignore the result of "beforeunload"

### ISSUE THREAD

**Issue by aprialuk** [electron/electron#12518]
* Electron version: 1.8.4
 * Operating system: Windows 10
 
 If a guest page loaded in webview has "beforeunload" event handler registered with a return value,
 then the registered "will-prevent-unload" event on webview's webContents does not work as expected.
 
The event "will-prevent-unload" is called properly but invoking the "e.preventDefault()" to make "beforeunload" with the returned result ignored does not happen and the page will not get unloaded and therefore the page does not get reloaded at all.
 
 ### How to run the test app
 
 1. Clone or download from: https://github.com/aprialuk/webview-will-prevent-unload.git 
 2. Run: `electron main.js `
 
 ### Simulate
 
 1. In the devtools of the guest page you can register "beforeunload" event (or navigate to a web page with such event handler already registered)
```
        window.onbeforeunload = function(e) {
            console.log("onbeforeunload called");
            return "anything except 'undefined'"; // or e.returnValue = "anything except 'undefined'"
        }
```
 2. Press "Reload"/"Go Home" button at the address bar. The event handler "will-prevent-unload" is called but does not make the event "beforeunload" ignored and the page is not unloaded.
 
 ### Note
 
 If the event handler "will-prevent-unload" is registered to the electron's main window. The application's browser window after pressing CTRL+R will get unloaded as expected.

**Comment by MarshallOfSound** [comment]
[This](https://github.com/aprialuk/webview-will-prevent-unload/blob/master/browser.js#L150) is your issue, you are hooking this event in the renderer process while the `webContents` you are hooking into is in the `main` process.  You are actually hooking this event through the `remote` module which causes the event to emitted asynchronously.  This causes your `event.preventDefault()` to have no effect.  You need to hook the event in the main process for this to work.

Please see [here](https://github.com/electron/electron/issues/11820#issuecomment-362873175) for a detailed comment for the same issue on a different event.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by Ryuurock** [comment]
> [This](https://github.com/aprialuk/webview-will-prevent-unload/blob/master/browser.js#L150) is your issue, you are hooking this event in the renderer process while the `webContents` you are hooking into is in the `main` process. You are actually hooking this event through the `remote` module which causes the event to emitted asynchronously. This causes your `event.preventDefault()` to have no effect. You need to hook the event in the main process for this to work.
> 
> Please see [here](https://github.com/electron/electron/issues/11820#issuecomment-362873175) for a detailed comment for the same issue on a different event.
how to hook the event in the main process，webview in the renderer process

**Comment by cyu** [comment]
Here's how I ended up solving the problem.  This solution adds the functionality to all webContents, even for `BrowserWindow`s.  If I needed to do this for specific webviews, I think it would be something like this:

1. Listen for `dom-ready` on the webview.
2. Use IPC to tell the main process to attach the handler on the `WebContents` using `webview.getWebContentsId()`.
3. Add the `will-prevent-unload` handler on that specific `WebContents`.

```typescript
import { WebContents, App, Event, BrowserWindow, dialog } from "electron";

export default function webContentsCreated(app: App) {
  app.on("web-contents-created", function (
    _event: any,
    webContents: WebContents
  ) {
    webContents.on("will-prevent-unload", function (event: Event) {
      const win = BrowserWindow.fromWebContents(webContents);
      const choice = dialog.showMessageBoxSync(win, {
        type: "question",
        buttons: ["Leave", "Stay"],
        title: "Do you want to leave this site?",
        message: "Changes you made may not be saved.",
        defaultId: 0,
        cancelId: 1,
      });
      const leave = choice === 0;
      if (leave) {
        event.preventDefault();
      }
    });
  });
}
