### ISSUE TITLE
SigleLine (/s) flag in Regex is not supported

### ISSUE THREAD

**Issue by TiagoDanin** [electron/electron#12522]
### Summary 
SigleLine (/s) flag in Regex is not supported in Electron.
Or is a bug ?

* NPM version: 5.8.0
* Node version: v8.0.0 and v9.9.0
* Electron version: v1.7.11 and 1.8.4
* Operating system: Manjaro (Kernel 4.14.11-3)

### Expected behavior
![image](https://user-images.githubusercontent.com/5731176/38263219-e1a5dafa-3745-11e8-9761-cccf25567fe2.png)
(Chrome version 64.0.3282.167 (64-bit))

![image](https://user-images.githubusercontent.com/5731176/38263598-d64be6da-3746-11e8-9918-bdf32c5415a3.png)
(NodeJs CLI)

### Actual behavior
![image](https://user-images.githubusercontent.com/5731176/38263094-7b864d0e-3745-11e8-83de-296ea2b4220f.png)

### How to reproduce
1. Open a Electron app
2. Open the DevTools
3. Run `"Here text".replace(/text/gs, "")`
4. Error! OH, NO!

**Comment by MarshallOfSound** [comment]
I can't figure out when this was added to Chromium but it isn't reported as an official flag on [MDN[(https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp).

Can you test Chromium 59 and see if it works there?

**Comment by TiagoDanin** [comment]
> Can you test Chromium 59 and see if it works there?

Yep, I'll do a test tomorrow.

PS: The packages are also affected.

**Comment by TiagoDanin** [comment]
I did not find a mirror download for the version 59

**Comment by ckerr** [comment]
As @MarshallOfSound points out, this doesn't seem to be a documented feature.

According to https://github.com/v8/v8/commit/d42534d441a75405d8dcf50a1383485b3c135faf it seems this was added in Chrome 62. So while it's likely this works in `master`, the Chromium versions in Electron 1.7, 1.8, and 2.0 are all too old. Electron 3.0 will catch up to this.
