### ISSUE TITLE
app.setBadgeCount() after app.dock.hide() -> app.dock.show() has no visual effect

### ISSUE THREAD

**Issue by ctotheameron** [electron/electron#12529]
* Electron version: 1.8.4
* Operating system: OS X (10.13.3)

### Expected behavior

I have an application that 'runs in the background' by hiding the BrowserWindow and dock icon when closed (see sample code below). I'm showing a badgeCount on the dock icon when the window is open, and expect that the badge count should be maintained between hide() and show() calls.

### Actual behavior

The app icon badge disappears after the initial call to app.dock.hide(). Subsequent app.dock.show() will bring back the app icon in the dock, but with no badging.

I tried resetting the badgeCount using app.setBadgeCount() every time I call app.dock.show(), but the method seems to have no effect once the dock icon has been hidden (and re-shown).

### How to reproduce

The code I'm using to hide and show the dock:

```javascript
function show() {
    if (!mainWindow) return;
    if (mainWindow.isMinimized()) mainWindow.restore();
    if (app.dock) app.dock.show();

    mainWindow.show();
    mainWindow.focus();

    log.info('badge currently shows', app.getBadgeCount());   // badge currently shows 3
    log.info('trying to set badge count', state.badgeCount);  // trying to set badge count 3
    log.info(app.setBadgeCount(state.badgeCount));            // true
}

function hide() {
    if (!mainWindow) return;
    if (app.dock) app.dock.hide();
    mainWindow.hide();
}

state.badgeCount = 3;

app.setBadgeCount(state.badgeCount) // 3 is shown on dock icon
hide(); // badge disappears as app icon fades away (maybe desired behavior idk)
show(); // app icon reappears, but without badging
```

**Comment by ctotheameron** [comment]
So I've identified a workaround that seems to mitigate my immediate issue:

If I modify my show() method from above, to first reset the badgeCount to 0, before trying to set it to my actual desired count, the badges start showing again. It seems that the problem only occurs when setting the badge count to the same value it was previously.

The root issue still stands, that the badge UI is not being persisted between app.dock.show() and app.dock.hide() calls.

**Comment by sethlu** [comment]
@ctotheameron After experimenting a little with Apple's API, I don't think the issue originates from Electron but from the system level. `NSDockTitle`'s property `badgeLabel` has the correct string just that it's not rendered on screen after hiding and showing the dock icon.

I guess a user-level fix for now is to do something like...?

```js
let t = app.getBadgeCount();
app.setBadgeCount(0); // just so the system API could see some change and clear the string it remembers
app.setBadgeCount(t); // reset the badge count
```

---

A potential fix from Electron may be to clear and reset the text after hiding and showing the dock icon?

**Comment by ctotheameron** [comment]
@sethlu, yeah that's about what I figured. I also came up with the same solution and can confirm that it works. 

Basically I'm doing the following.

```javascript
    setImmediate(() => {
        app.setBadgeCount(app.getBadgeCount() - 1);
        app.setBadgeCount(state.badgeCount);
    });
```

I didn't bother looking into the underlying code so I thought electron might be ignoring calls that matched the stored value. That's why I was doing the "-1" heuristic. Based on what you say, 0 should work as well. There is no flicker or anything so I don't think it matters what you set it to as long as it's different.

Also, I was seeing some race condition when trying to set the badge immediately after showing, but setImmediate seems to mitigate that.

**Comment by ctotheameron** [comment]
Ah that's not ideal. Thanks for the heads up, I'll keep an eye out and maybe will increase my setTimeout in the meantime.

Any plans to make the show() calls return promises so that users could wait until the system is ready

**Comment by sethlu** [comment]
@ctotheameron Good point to make `show()` an async call if we can capture when the system is ready to respond to dock icon badge label changes in the first place. I'm not sure if there is anything planned to make it async?

**Comment by sethlu** [comment]
Btw I've just filed a bug report to Apple. To reproduce the issue: [DockIconTest.zip](https://github.com/electron/electron/files/1879209/DockIconTest.zip)

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
