### ISSUE TITLE
No subpixel font rendering in linux

### ISSUE THREAD

**Issue by mrlotfi** [electron/electron#12541]
* Electron version:
1.8.4
* Operating system:
Arch Linux
* Freetype version:
2.9.0 

### Expected behavior
Electron should render fonts using subpixel rendering

### Actual behavior
Fonts are rendered in greyscale mode.

### How to reproduce
I guess the issue is related to freetype. It started after the new freetype release. It happens to every electron-based application (vscode, atom, ... ).

![image](https://user-images.githubusercontent.com/9977153/38354561-4eb45290-38cf-11e8-9856-51591d344963.png)
![image](https://user-images.githubusercontent.com/9977153/38354586-5e71319e-38cf-11e8-8b7d-d80b4cded9a1.png)

**Comment by albertorestifo** [comment]
Any progress on this front?

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by nornagon** [comment]
also dup of https://github.com/electron/electron/issues/10955
