### ISSUE TITLE
Wayland compatibility in brightray and atom/browser

### ISSUE THREAD

**Issue by ckerr** [electron/electron#12543]
Related to https://github.com/electron/electron/issues/9056

It's true that most of the heavy lifting in Wayland compatibility will happen when Chromium adds Wayland support, but there are also X11 odds-and-ends that will need to be addressed in Electron itself.

In several places our `USE_X11` ifdef really just means OS_*NIX, but there are several places where we're calling  XShapeCombineRectangles, XSetTransientForHint, XChangeProperty, et al. These cases will all need Wayland support as well

**Comment by miniak** [comment]
Duplicate of https://github.com/electron/electron/issues/10915
