### ISSUE TITLE
Printing on Linux using non-standard printer

### ISSUE THREAD

**Issue by ComputerHippie** [electron/electron#12549]
* Electron version: 1.8.4, 1.7.13
* Operating system: Debian 9
* CUPS: 2.2.1

Hey,

In my project I'm using printer Custom VKP80 in which 80mm thermal paper is used.
I'm running my electron application on Debian 9. The printer is added in cups and configured to use 80mm paper. Also the printer is marked as default printer.
According to application logic printing should be performed silently. So I'm using option {silent:true}. But with this option Electron (or Chromium inside Electron) does not use configured cups settings and prints only part of html document. Printed receipt looks like only left part of "virtual" A4 paper (like 80mm from left side of A4 is printed).
If set {silent:false} and NOT touch any settings in printing dialog and just press "Print" button then printed receipt looks like expected, i.e. cups settings are used.

### Expected behavior

Electron uses printer settings during printing with option {silent:true}

### Actual behavior

Electron does not use cups settings during printing with option {silent:true}

### How to reproduce

1. Configure some non-standard printer in linux using cups.
2. Call someWindow.webContents.print({silent:true})

**Comment by footniko** [comment]
Possible duplicate: #9780

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
