### ISSUE TITLE
Unable to run electron in docker (general error - you may need xvfb)

### ISSUE THREAD

**Issue by kamthamc** [electron/electron#12544]
* Electron version: 1.8.4
* Operating system: node: 9.10-slim (debian:jessie)
tried with node:8, node: 9-stretch
### Expected behavior
Project: https://github.com/kamthamc/NightmareJS-Demo
electron should run without any issues

### Actual behavior
electron is exiting with error (complaining about xvfb even though its installed)
<img width="678" alt="screen shot 2018-04-05 at 8 56 00 am" src="https://user-images.githubusercontent.com/2925876/38378531-e50cdf40-38b2-11e8-87c5-73504f474ca6.png">

it runs fine when testing locally but fails in docker

### How to reproduce
download https://github.com/kamthamc/NightmareJS-Demo
`make package` - creates docker image
`make test` - runs docker image

**Comment by MarshallOfSound** [comment]
@kamthamc `xvfb` needs to be running as well as installed, something like this should be enough to launch it.

```bash
export DISPLAY=:99.0
sh -e /etc/init.d/xvfb start
sleep 3
```

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
