### ISSUE TITLE
End event of net.request Response is never emitted

### ISSUE THREAD

**Issue by martyglaubitz** [electron/electron#12545]
* Electron version: 2.0.0-beta.6
* Operating system: Windows 10

### Expected behavior

HTTP Response should emit "end" event to let the application know that the entire body was received.

### Actual behavior

I can see that data is received and actually on this very specific call the whole reponse body is passed to the data callback at once, but i cannot assume that this will always be the case. So i sort of rely on the "end" event.

### How to reproduce

Im follwong this example: https://github.com/electron/electron/blob/master/docs/api/net.md#net

Im trying to use the [net](https://github.com/electron/electron/blob/master/docs/api/net.md) package (from the rendering process) via the remote interface to make a REST call to a webservice, like so:

```javascript

const net = require("electron").remote.net;
const requestOptions = {
     auth: "myuser:mypwd", 
     url: "https://my.rest.service/oauth/token", 
     method: "POST"
};

const request = net.request(requestOptions);
request.on("response", function(response) {
     console.log(response.statusCode);

     response.on("data", function(data) {
          console.log("data: " data);
     });
     response.on("end", function {
          // will never get called
          console.log("end");
     });
});
request.end();
```

**Comment by codebytere** [comment]
I'll take a look at this tonight or tomorrow!

**Comment by codebytere** [comment]
verified on mac, investigating now

**Comment by martyglaubitz** [comment]
@codebytere alright tanks! Guess i'll just offload the operation into the main process till it's fixed 😃

**Comment by MarshallOfSound** [comment]
@martyglaubitz If you're in the renderer process why do you need to use `net`?  Can't you just use the `fetch` API 😄

**Comment by martyglaubitz** [comment]
@MarshallOfSound isn't fetch just a wrapper around XMLHttpRequest? If so: are you allowed calling other domains? Because that's why i didn't use Ajax in the first place...

**Comment by codebytere** [comment]
@martyglaubitz verdict is that emitting the `response` event is async, so by the time it hits the renderer and you want to hook the `data` and `end` events they've already happened. `data` works because it's a race condition, and if you had a large enough file you were loading the `end` event would likely work too. Sadly, fixing this would involve a lot of nasty workarounds and hacks that aren't in our best interest to implement so i'd say keep it in your main process. good luck, and sorry about that!

**Comment by martyglaubitz** [comment]
That's ok for me - thanks! :)

**Comment by mikilion** [comment]
I solved by moving the "end" event definition before "date" event.

**Comment by Mr-Wallet** [comment]
This just cost me and a teammate 3 or so man-hours. Would it be possible to update the [docs](https://electronjs.org/docs/api/net) to inform developers about this hazard?

**Comment by Annihil** [comment]
I don't encounter this problem, there is an end event when using net from remote, but not if the status code is > 400 ...

**Comment by chemzqm** [comment]
> but not if the status code is > 400 ...

Same issue when using electron 6.1.5, `response` event never emitted when using net.request in renderer process and status code > 400

**Comment by nornagon** [comment]
I recommend [not using the remote module](https://medium.com/@nornagon/electrons-remote-module-considered-harmful-70d69500f31).

**Comment by Bakhaow** [comment]
Still have the problem in 2020, perhaps someone have an alternative ?

**Comment by blacksider** [comment]
in my case, move the "end" event before the "date" event is ok, but why?

```
            let data = '';
            response.on('end', () => {
                console.log(response.statusCode);
                console.log(data);
            });
            response.on("data", chunk => {
                data += chunk;
            });
```

**Comment by ok-dok** [comment]
> I recommend [not using the remote module](https://medium.com/@nornagon/electrons-remote-module-considered-harmful-70d69500f31).

thanks, I encounter this problem when I used the remote module, and I didn't resolve it , U reminds me.

**Comment by ok-dok** [comment]
> Still have the problem in 2020, perhaps someone have an alternative ?

I am question too.

**Comment by jduhking** [comment]
any updates on this?
