### ISSUE TITLE
gRPC cannot run properly in Electron v1.8.4

### ISSUE THREAD

**Issue by PlacidoDomingo** [electron/electron#12547]
I used electron-quick-start to create a template project with Electron v1.8.4 on Win7 64bit then ran cmd "electron project_path"  to show  a "Hello World" page. After I installed gRPC I added "const gRPC = require('gRPC');' to main.js, I received the error: "Error: Failed to load gRPC binary module because it
rrent system Expected directory: electron-v1.8-win32-x64-unknown", the node version is v8.10.0

How can I fix it, thank you!

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
