### ISSUE TITLE
webSecurity false no longer implies allowRunningInsecureContent

### ISSUE THREAD

**Issue by tejohnso** [electron/electron#12555]
* Electron version: 2.0.0-beta.7
* Operating system: Windows 7

### Expected behavior

`new BrowserWindow({webPreferences:{webSecurity:false}})` should not show mixed-content errors. It should show warnings and continue to load the content.

### Actual behavior

mixed-content errors are shown unless *allowRunningInsecureContent* is specified which is contrary to the documentation:

> Disabling webSecurity will disable the same-origin policy and set allowRunningInsecureContent property to true. 

This was working as expected in 1.8.2

### How to reproduce

Open a new BrowserWindow as above and load a page via `https` that contains elements using `http`.

**Comment by MarshallOfSound** [comment]
This is known and I'm working on a fix for it

**Comment by MarshallOfSound** [comment]
Can you link where those docs came from?
