### ISSUE TITLE
NPM Installation Fail on Linux

### ISSUE THREAD

**Issue by nolyoly** [electron/electron#12553]
I'm trying to install the latest stable build on my Linux Mint distro. I'm getting the following output and haven't figured out what's wrong.

```
$ npm i -D electron@latest
npm WARN checkPermissions Missing write access to /home/nolan/node_modules
npm WARN enoent ENOENT: no such file or directory, open '/home/nolan/package.json'
npm WARN nolan No description
npm WARN nolan No repository field.
npm WARN nolan No README data
npm WARN nolan No license field.

npm ERR! path /home/nolan/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/home/nolan/node_modules'
npm ERR!  { Error: EACCES: permission denied, access '/home/nolan/node_modules'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/home/nolan/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/nolan/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nolan/.npm/_logs/2018-04-06T12_29_36_255Z-debug.log
```

Then when running as root as it says to try doing I get this output:

```
$ sudo npm i -D electron@latest

> electron@1.8.4 postinstall /home/nolan/node_modules/electron
> node install.js

/home/nolan/node_modules/electron/install.js:47
  throw err
  ^

Error: EACCES: permission denied, mkdir '/home/nolan/node_modules/electron/electron-tmp-download-17793-1523017991786'
npm WARN enoent ENOENT: no such file or directory, open '/home/nolan/package.json'
npm WARN nolan No description
npm WARN nolan No repository field.
npm WARN nolan No README data
npm WARN nolan No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.8.4 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.8.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nolan/.npm/_logs/2018-04-06T12_33_12_101Z-debug.log
```

I've tried looking online for a solution but have yet to find one. Any suggestions or ideas what is going on here?

**Comment by tgandrews** [comment]
The `-D` flag is trying to save electron as a dev dependency for a node project. It looks like you are not in a node project.

If are just trying to install electron, then you could run: `npm i -g electron` which would install electron globally and would make available to you (providing your path is setup correctly - check the [npm docs](https://docs.npmjs.com/)).

If however you are trying to use electron in a new project then first run `npm init` in your new blank project folder and then you can run `npm i -D electron`.

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).

**Comment by nolyoly** [comment]
@sofianguy wouldnt this be a bug? failing a default install shouldnt happen.

also, would have posted on the forum but, the activation e-mails seem to not be getting sent for some reason. not in spam neither.

**Comment by yasithaBandara** [comment]
run "npm install" then try again.
