### ISSUE TITLE
Can't disable right click context menu

### ISSUE THREAD

**Issue by dilby** [electron/electron#12558]
Running as a fullscreen Windows app and a two-finger tap on a touchscreen brings up a context menu with the following options:

Open with default window
Open in new window
Copy link location

There doesn't seem to be an option in the API to disable this?

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
