### ISSUE TITLE
Error while bootstrap.py | "Unable to checkout"

### ISSUE THREAD

**Issue by XD0M3** [electron/electron#12566]
Error is happening while using the command:
Exact Error: [Error](https://gist.github.com/XD0M3/dcae1259e15caed4cbcb893621fabe71)
> $ python script/bootstrap.py -v

> npm run clean

Doesnt work.

--------------
> git clone https://github.com/electron/electron.git
> cd electron
> python script/bootstrap.py -v
----------------

**Comment by MarshallOfSound** [comment]
@XD0M3 Looks like you're hitting windows filename too long errors and this is messing with both node_module installation and probably the `.git` directory.  Can you either disable the path limit (you can do this on windows 10), or move the electron directory higher up the folder hierarchy 👍

**Comment by XD0M3** [comment]
Hello, thank you for the tipp with the pathlimt,
@MarshallOfSound 
https://gist.github.com/XD0M3/a9c99aa8099640caa0ab123091a8e026
Is this still to that?, because the i but in to the hights hirachy. D:/folder
