### ISSUE TITLE
1.8.x and above instantly crashing (Windows 10, 64-bit)

### ISSUE THREAD

**Issue by Riari** [electron/electron#12564]
* Electron version: >= 1.8.x
* Operating system: Windows 10 Pro 64-bit

For some reason, on my system, any Electron version at or above 1.8.x silently fails to launch. The process immediately exits and there's no output at all, even when using `ELECTRON_ENABLE_LOGGING=true`. I initially noticed the problem when trying to run the latest Slack and WorkFlowy desktop clients, and was able to reproduce it with a project generated using electron-forge as well.

Electron v1.6.16 seems to work and I'm able to run Atom, VSCode, Discord and Insomnia, all of which I assume run on that version or below.

(CC @MarshallOfSound 🙂)

**Comment by MarshallOfSound** [comment]
@Riari Can you grab the output when running with `ELECTRON_ENABLE_STACK_DUMPING=true`

**Comment by Riari** [comment]
Sure, here it is (running 1.8.4):

```
Backtrace:
        node::Init [0x00007FFD1386B400+928]
        (No symbol) [0x00007FF6E06E6AEB]
        (No symbol) [0x00007FF6E06F2287]
        IsSandboxedProcess [0x00007FF6E1BD2ABE+1016014]
        IsSandboxedProcess [0x00007FF6E1DA1AD5+2912485]
        IsSandboxedProcess [0x00007FF6E2030909+5594905]
        IsSandboxedProcess [0x00007FF6E1D7801D+2741805]
        IsSandboxedProcess [0x00007FF6E1D77F0C+2741532]
        IsSandboxedProcess [0x00007FF6E2A6F242+16336978]
        GetHandleVerifier [0x00007FF6E19510A0+17234080]
        (No symbol) [0x00007FF6E06BBC8D]
        IsSandboxedProcess [0x00007FF6E32562A3+24623283]
        BaseThreadInitThunk [0x00007FFD694A1FE4+20]
        RtlUserThreadStart [0x00007FFD69F5EFC1+33]
```

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
