### ISSUE TITLE
win.webContents.printToPDF() - thead duplication rendering issue (@electron 1.8.4)

### ISSUE THREAD

**Issue by Resurg3nt** [electron/electron#12567]
In relation to the following issue:-
https://github.com/electron/electron/issues/8386

I can confirm that I am still experiencing the thead rendering issue when printing to PDF using win.webContents.printToPDF() despite the fact that I am using electron 1.8.4 and it having been stated this was rectified in 1.6 in the above issue. The following work around rectifies the issue, with the !important being required:-

```
@media print {		
thead {
		display: table-row-group !important;
}	
}
```

Platform win32-x64
Electron Version: 1.8.4.

Please advise.

**Comment by alexeykuzmin** [comment]
@Resurg3nt, can you please check if the same happens with the Electron v2.0.0-beta.7?

**Comment by alexeykuzmin** [comment]
@Resurg3nt, does https://crbug.com/819254 look like your problem?

**Comment by Resurg3nt** [comment]
![capture](https://user-images.githubusercontent.com/22156658/38489987-c444d45e-3bdf-11e8-8b0b-20d9af798c33.PNG)

This is the problem, but is rectified as I said with the correcting css.

I've just tested it in the latest version of Electron v2.0.0-beta.7 - the issue still exists.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
