### ISSUE TITLE
Atom - can't use left/right to navigate between menus - is it an Electron issue ?

### ISSUE THREAD

**Issue by stuaxo** [electron/electron#12563]
Atom (and VSCode etc) have an annoying ommision, where you can't use left/right on the keyboard to navigate between adjacent menus on the menu bar.

Is this actually an Atom issue ?

https://github.com/atom/atom/issues/5998

**Comment by nitsakh** [comment]
Is this only on linux? I tried on macOS and I don't see this issue.

**Comment by stuaxo** [comment]
I've only tested this on Linux.   I guess on macOS this uses menus in the mac menu-bar, so it probably just does what the system does ?

**Comment by codebytere** [comment]
Please open this issue on `atom/atom` instead :)
