### ISSUE TITLE
Strange button ripple animation behaviour

### ISSUE THREAD

**Issue by gorilla-devs** [electron/electron#12575]
I am creating a button with a ripple effect on it with react/electron.

To prove it works on the web, you can check my simplified implementation here: https://codepen.io/killpowa/pen/PRXvpV.

My problem with electron is that the ripple appears randomly and not always when I click, and the cursor is not always the pointer after i clicked. To understand what i mean, i recorded it: https://giphy.com/gifs/58FpgEeTghUL50LqT3. I really cannot understand how to fix it, because i can't understand what causes it. Given that it works on the web but not on electron, i assume it's related to Electron. I think it could be related on how electron works with

const X = e.pageX - e.target.getBoundingClientRect().left;
const Y = e.pageY - e.target.getBoundingClientRect().top;

but then why the first time I click, it works fine?

* Electron version: 1.8.4
* Operating system: Windows 10

### Expected behavior

The button should work the same as the codepen's one

### Actual behavior

The ripple effect just goes crazy, sometimes it doesn't detect clicks if fast, the cursor does not stays the same (pointer) and the ripple spawns from weird spots.

### How to reproduce

To replicate the issue, you can manually

    

1. Clone https://github.com/chentsulin/electron-react-boilerplate
2. Integrate my Button component from codepen
3. Start electron with yarn dev

or

1. Clone my repo with everything set up. Just do yarn and then yarn dev(you can skip any error or warning, it will work anyway) https://github.com/gorilla-devs/Button-Ripple

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
