### ISSUE TITLE
docs for WebContents did-get-response-details status param are unclear

### ISSUE THREAD

**Issue by bughit** [electron/electron#12579]
[status indicates the socket connection to download the resource](https://github.com/electron/electron/blob/master/docs/api/web-contents.md)

Looking at the implementation, status is `content::ResourceRequestDetails.socket_address.IsEmpty()`. 

What does socket_address being empty signify?

**Comment by deepak1556** [comment]
> What does socket_address being empty signify?

This was worded incorrectly, it meant to signify an active connection.

@bughit the event will be removed in the near future as per https://github.com/electron/electron/issues/12597, can you verify if the `webRequest` module serves your purpose. Thanks!

**Comment by bughit** [comment]
@deepak1556 

did-get-response-details is currently the only event on webContents that indicates an http level failure

Though it does appear that webRequest.onHeadersReceived is equivalent, it strikes me as a flaw that you can't tell (via webContent) that a navigation you requested via webContents has failed.

I think some event on webContents (did-finish-load, did-frame-finish-load, did-fail-load, or a new one) should give you the http response code.

**Comment by deepak1556** [comment]
> Though it does appear that webRequest.onHeadersReceived is equivalent, it strikes me as a flaw that you can't tell (via webContent) that a navigation you requested via webContents has failed.

Can you give an example for this. `webRequest` module should provides all the necessary details for a navigation, if something is missing we can add it.

**Comment by bughit** [comment]
Example of what? What I stated is true by definition: under this plan you can't tell (via webContents) that a navigation you requested via webContents has failed. That does not seem like coherent api design to me. Success or failure of an operation should be delivered by the same api through which the operation is requested.

Here's an analogy.  Imagine window.fetch() did not notify you of http level failures, forcing you to use some other api to detect the failure of your fetch request. Would that be sensible?

**Comment by deepak1556** [comment]
> under this plan you can't tell (via webContents) that a navigation you requested via webContents has failed

Yes you can, all webRequest responses contain an associated id for the webcontents that the request associates with. Also if that doesn't work, you can always create a custom session for your webContent and use it to track the requests uniquely with `session.webRequest`. `WebContents` shouldn't deal with any network related api, you should always rely on the `session` module for it.

**Comment by bughit** [comment]
You're ignoring the "via webContents" qualifier.

So you are saying this makes perfect sense to you: 

- The navigation is requested via webContents
- webContents will notify you when it's finished
- webContents will notify  (did-fail-load) if it fails at the low networking level (tcp/dns)
- but will not notify you if it fails on the http level

It doesn't to me.  webContents should deliver the http status code in at least one of it's finished/failed events.

**Comment by bughit** [comment]
> Currently there is error code provided on navigation failure

Not http level failure. Unless you're saying that's a bug, there is no did-fail-load for http failures in master.

**Comment by bughit** [comment]
>  We can add http status codes to the lifecycle events, can you open a separate issue for it. 

I created an issue before you responded (#12598). Is that what you had in mind? 

Please clarify what you're proposing.  Which events should deliver the http status?  Should did-fail-load fire for 4xx/5xx?

**Comment by miniak** [comment]
The `did-get-response-details` event is removed since Electron 3 (https://github.com/electron/electron/commit/7b47d69efe6fec355778c1ea7e1c9c29a2cc3599#diff-faaead3da8a3aa51eff1331507a67934). If there is an issue with the documentation of the current APIs, please create a follow-up issue or PR with a fix.
