### ISSUE TITLE
Bootstrap - Error in update.py

### ISSUE THREAD

**Issue by XD0M3** [electron/electron#12583]
Hello,

while bootstraping an error happend. 
[Error](https://gist.github.com/XD0M3/a9c99aa8099640caa0ab123091a8e026)
_______
I tried it on a fresh clone too, but still the same error.

> git clone https://github.com/electron/electron.git
> python script/bootstrap.py

Python Version 2.7 
Node Version v9.4.0
git Version 2.16.1
Visual Studio 2017 Version 15.6.5

**Comment by MarshallOfSound** [comment]
> Python Version 2.7

You need to update your python version to the latest `2.7` release to get support for newer TLS
