### ISSUE TITLE
The file listing blink features that we can disable no longer exists

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#12588]
BrowserWindow's [docs](https://github.com/electron/electron/blob/master/docs/api/browser-window.md) tell us how to disable blink features:

>`blinkFeatures` String (optional) - A list of feature strings separated by `,`, like `CSSVariables,KeyboardEventKey` to enable. The full list of supported feature strings can be found in the [RuntimeEnabledFeatures.json5](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/platform/runtime_enabled_features.json5?l=70) file.

That path, however, no longer points to anything.

**Comment by CGJennings** [comment]
This is already fixed in master, but the online docs at [electronjs.org](https://electronjs.org/docs/api/browser-window) haven't caught up yet.

For your reference, the new URL is:
https://cs.chromium.org/chromium/src/third_party/blink/renderer/platform/runtime_enabled_features.json5?l=70
