### ISSUE TITLE
Election crash when <webview> using partition.

### ISSUE THREAD

**Issue by zhuowenli** [electron/electron#12585]
* Electron version: electron@2.0.0-beta.7
* Operating system: macOS 10.13.4

### Actual behavior
Election crash when `<webview>` using `partition`.

But **electron@1.8.4** is ok.

### How to reproduce

1. Use `BrowserWindow` open a link in new window. (this page has insert `<webview partition="xxx" url="http://xxx">` tags )
2. Close window.
3. Open again, then Election app will crash.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
