### ISSUE TITLE
Garbage collector fails to trigger

### ISSUE THREAD

**Issue by logidelic** [electron/electron#12586]
* Electron version: 1.8.4
* Operating system: Ubuntu Arm64

### Expected behavior

Garbage collector should trigger before going OOM

### Actual behavior

Process eventually goes OOM because garbage collector did not trigger in time.

### How to reproduce

I will attempt to create a simple repro, but I expect it will be problematic. My app is complex and has native C++ modules doing work in multiple threads. Perhaps this is related. Nevertheless, the basics are:

- App consistently uses ~20% CPU (at least as reported by process.getCPUUsage()).

- System always feels responsive and main JS thread is never blocked.

- Memory usage appears to fluctuate, but eventually goes OOM.

- If I start my app with `--js-flags="--expose-gc"` and call `global.gc()` regularly (ex, every 30 seconds), I do not go OOM.

For now I am working around the issue by calling `global.gc()` manually. Aside from potentially blocking during GC is there any other downside to calling this manually?

**Comment by sofianguy** [comment]
Thank you for your issue!
I'm going to close this issue but don't hesitate to reach out if you have repro steps. We'll be happy to reopen the issue.
