### ISSUE TITLE
dialog.showMessageBox does not follow BrowserWindow position

### ISSUE THREAD

**Issue by aboulfad** [electron/electron#12591]
* Electron version: 1.8.4
* Operating system: Win10

When setting BrowserWindow x & y values to display window at other location than center, dialog.showMessageBox sill displays the dialog centered and does NOT follow the position of the main window, even when passing the BrowserWindow object.

Code to reproduce:

> let win
>  function createWindow () {
>     // Create the browser window.
>     win = new BrowserWindow({
>         width: 650, height: 650, x:10, y: 10,
>         webPreferences: {
>             webSecurity: false
>           }
>     })
> dialog.showMessageBox(win, {type: 'info', title: 'Information', message: "Please Select a file", buttons: ['OK']});

**Comment by superpihey** [comment]
I'm also experience bug in Mac OS. When I call the dialog.showMessageBox from the main browser window, the dialog.showMessageBox is not centered even I set the center to true.
```

dialog.showMessageBox(
	new BrowserWindow({
		show: false,
		 alwaysOnTop: true,
		 center: true
	 }),{
		title:"Oops!",
		message:"Notify Alert",
		type:"error",
		buttons:["OK"],
		defaultId: 0
	},function(index){
			app.quit();
	})
```

**Comment by qing-ke** [comment]
same

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by mrozekma** [comment]
@sofianguy This still happens as of Electron 4.0.4

**Comment by kostik81** [comment]
same problem for me at Win 7, electron 4.1.4
MacOs dialog MessageBox follow browserWindow position - OK

**Comment by ericchase** [comment]
Are there any plans to address this?

**Comment by Christilut** [comment]
This works in Electron 6.1.7 though:
```js
 dialog.showOpenDialogSync(require('electron').remote.getCurrentWindow(), { ... options })
```

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
