### ISSUE TITLE
Maximize/Unmaximize events fail to trigger

### ISSUE THREAD

**Issue by declanvk** [electron/electron#12592]
* Electron version: 1.8.4
* Operating system: Mac OSX 10.11.6

### Expected behavior

```
mainWindow.on('maximize', () => {
  console.info(`window was just maximized`);
});
```

should print out `window was just maximized` when the maximize button is pressed.
Similarly,

```
mainWindow.on('unmaximize', () => {
  console.info(`window was just unmaximized`);
});
```
should print out `window was just unmaximized` when the unmaximize button is pressed.

### Actual behavior

Neither of those statements are printed. The events are not being triggered by the changes to the window state.

### How to reproduce

```
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start/
npm install electron --save-dev --save-exact
npm install
```

Then, change `main.js` to have the contents:
```
const electron = require('electron')
const app = electron.app
const BrowserWindow = electron.BrowserWindow

const path = require('path')
const url = require('url')

let mainWindow

function createWindow () {
  mainWindow = new BrowserWindow({width: 800, height: 600})

  mainWindow.loadURL(url.format({
    pathname: path.join(__dirname, 'index.html'),
    protocol: 'file:',
    slashes: true
  }))


  mainWindow.on('closed', function () {
    mainWindow = null
  })

  console.log(`Listening for window state change`);
  mainWindow.on('maximize', () => {
    console.info(`window was just maximized`);
  });

  mainWindow.on('unmaximize', () => {
    console.info(`window was just unmaximized`);
  });
}

app.on('ready', createWindow)

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', function () {
  if (mainWindow === null) {
    createWindow()
  }
})
```

Then,
```
npm start
```

Then try maximizing or unmaximizing the window. The console should not print out either of the messages.

**Comment by sethlu** [comment]
@declanvk are you perhaps looking for `enter-full-screen` and `leave-full-screen`? `maximize` and `unmaximize` become triggered when you double click on the top gray bar.

**Comment by declanvk** [comment]
@sethlu You're absolutely right, thank you. Do you know if there are differences between `enter-full-screen` and `maximize` on other platforms?
