### ISSUE TITLE
[2.0.0-beta.7] Cannot connect to remote dev tools (main process only)

### ISSUE THREAD

**Issue by natew** [electron/electron#12590]
* Electron version: 2.0.0-beta7
* Operating system: High Sierra

### Expected behavior

On 1.7/1.8 I can connect to urls like:

chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9001/6e588dcf-d175-442e-8fb2-a5db6dd46214

and debug.

### Actual behavior

On the 2.0 beta only the renderer processes connect, the main one seems to hang.

This is the errors I see if I inspect the inspecting page (they seem to keep going):

![image](https://user-images.githubusercontent.com/12100/38569163-71192d8c-3c9f-11e8-86f9-fe192607c35f.png)

"the main frame is not available"

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
