### ISSUE TITLE
Deprecate did-get-response-details and did-get-redirect-request events

### ISSUE THREAD

**Issue by deepak1556** [electron/electron#12597]
These events are emitted for every navigation request which isn't really efficient. Also upstream has removed the observers that provide these details as part of network servification https://chromium-review.googlesource.com/c/chromium/src/+/805008 and https://chromium-review.googlesource.com/c/chromium/src/+/786320. We are removing it as a part of chromium 66 upgrade.

Proposed alternative: Users can use the [webRequest](https://github.com/electron/electron/blob/master/docs/api/web-request.md) module which provides similar navigation details on a subscription basis.

**Comment by Pablodotnet** [comment]
@ahuang 

I have updated my working example of electron facebook login to the latest version of electron and now I'm using the onCompleted event if someone needs it:
[Electron Facebook Login with Electron 4](https://github.com/Pablodotnet/electron-facebook-login-example)

**Comment by ramrami** [comment]
@ahuang I'm facing the same problem, did you find a solution ? tks
