### ISSUE TITLE
with did-get-response-details being removed, some event on webContents should deliver the http response code

### ISSUE THREAD

**Issue by bughit** [electron/electron#12598]
- navigation is requested via webContents
- webContents will notify you when it's finished
- webContents will notify  (did-fail-load) if it fails at the low networking level (tcp/dns)
- but will not notify you if it fails on the http level

webContents is designed to notify you of navigation completion and failure, and there's no good reason that an http level failure should be an exception to that, requiring the use of a different api (webRequest)

**Comment by groundwater** [comment]
> and there's no good reason 

Hi @bughit. I've been reviewing your recent communications with the Electron team. I am requesting that you improve your style of communication. The above is an example of a nonproductive, and slightly combative style of communication.

Please remember, everyone here is choosing to _help_ solve these issues, they are not required to.


I am going to close this issue. Please follow my recommendation if you choose to re-open this issue again. Provide as much information as you can, and the more you do, the more we can do to help.

If you choose to disregard my recommendations, please note that you _then_ risk being restricted access to the project for failing to respect our Code of Conduct (as clarified above).

**Comment by bughit** [comment]
@groundwater I removed "and there's no good reason" that you found "nonproductive, and slightly combative".  Can this be reopened?

**Comment by groundwater** [comment]
Hi @bughit. Please read the following very carefully. I feel like the spirit of my message was not communicated.

1. The issue you submitted lacks the detail we request all submitters to follow. Please create a new issue, and follow the template exactly. Do not omit anything. Further, please provide as much detail as possible. The burden is on you to be as clear as possible, especially if you want the issue the issue solved quickly.
2. Your communication style is still coming off as combative. Please remember that you are currently a guest in the workplace of many other people. If you're uncertain what I mean, please check out [Creators, contributors, and collaborators](https://github.community/t5/Studies-in-Community/Creators-contributors-and-collaborators/ba-p/234) which helps explain the open source relationship.
3. We are looking for a serious effort on your part. Folks who cannot adhere to the boundaries given will be asked to stop participating in the Electron organization for 30 days, and failing that they will be removed altogether.

Our goal is not to ban anyone. Maintainers genuinely want to solve the issues app developers are experiencing. Having said that, the maintainers get to set the conditions of communication according to our Code of Conduct.

Thanks for listening, and I hope we have a positive path forward.

**Comment by adday** [comment]
This is the most unhelpful thread ever. Why did you move this to a new issue only to shut it down?
