### ISSUE TITLE
Sending sparse arrays over IPC

### ISSUE THREAD

**Issue by conradreuter** [electron/electron#12602]
Electron IPC does not seem to handle sparse arrays correctly. Missing elements seem to be ignored by making the array dense before transfering it via IPC.

* Electron version: 1.8.4
* Operating system: Windows 10

### Expected behavior

Main should print `renderer -> main [ <1 empty item>, 'msg' ]`
Renderer should print `main -> renderer Array(2)` with the array having `1: "msg"` and `length: 2`

### Actual behavior

Main prints `renderer -> main [ 'msg' ]`
Renderer prints `main -> renderer Array(1)` with the array having `0: "msg"` and `length: 1`

### How to reproduce

```
git clone https://github.com/conradreuter/electron-ipc-sparse-array-bug
cd electron-ipc-sparse-array-bug
npm install
npm start
```

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
