### ISSUE TITLE
Renderer high CPU on OSX with custom window switchers

### ISSUE THREAD

**Issue by youurayy** [electron/electron#12606]
* Electron version: master
* Operating system: OSX 10.13.3

### Expected behavior
Normal CPU usage.

### Actual behavior
When a 3rd party window switching utility is used (e.g. Karabiner Elements, Witch, Contexts) to switch between open windows of an Electron app with multiple windows open, the Renderer process of the window into which it was just switched goes into an infinite event loop, its thread consuming 100% of a CPU core.

I personally experience this in Visual Studio Code (and Atom), with Karabiner Elements setup to remap `Left_Option+Space` to `` CMD+` ``.

The XCode profiler (Instruments) shows that the CPU loop consists of repeated attempts of handling of a key code within the V8 JavaScript runtime, which seems to be sending it back on the main MessageLoop of same renderer process.

![image](https://user-images.githubusercontent.com/588573/38700075-940ff4ce-3ea2-11e8-892e-96efde5ef562.png)

![image](https://user-images.githubusercontent.com/588573/38698888-30a55fee-3e9f-11e8-9489-97a4175c91ea.png)

### How to reproduce
1. install any of the custom switchers with capability to switch same-app windows
  - e.g. install *Karabiner Elements*, from its OSX system bar icon, go to `Preferences`,
   - go to `Complex Modifications` tab, click `Add Rule`, click `..Import from Internet..`
   - Ctrl+F `anti`, click `Import` on `Anti-RSI App Switch`
   - now you can switch between same-app windows with Left_Option + SPACE
2. open any Electron app with multi-window support on OSX, e.g. VS Code, and open two windows
3. switch between the windows with the custom switcher
4. observe that CPU utilization of the Electron app increased to 100%

### How to debug/profile
1. get the minimal multiple window example:
```
git clone git@github.com:youurayy/electron-quick-start.git
```

2. build electron for debug & launch the minimal example:
```
git clone git@github.com:electron/electron.git && \
cd electron && \
./script/bootstrap.py -v --build_debug_libcc && \
ln -s vendor/libchromiumcontent/dist/main/shared_library \
  vendor/download/libchromiumcontent/shared_library && \
./script/build.py -c D --libcc && \
./script/update.py --xcode && \
out/D/Electron.app/Contents/MacOS/Electron ../electron-quick-start
```

3. position the two open window horizontally (just for later reference); should look like this:
![image](https://user-images.githubusercontent.com/588573/38701163-d9a8ff28-3ea5-11e8-94a1-9a5010080772.png)

4. ~~open the developer console in the left window, to see the renderer PID~~
   open `top -u` and see the PID of the offending Electron Helper Process (after point 8. below)
5. attach to that PID with Xcode debugger
6. move the Xcode session into Instruments (if you want to profile)
7. click on the right window to focus it
8. use the custom window switcher to switch to the left app window
9. the CPU is maxed and you can debug or profile

I'm new to Electron so any hints on how to further debug this are appreciated.
Thanks for all your work!

**Comment by squareduck** [comment]
Having the same issue with any non-OSX-native window switcher.

Steps to Reproduce (VSCode is used as example, but same goes for Atom):

1. Open two VSCode windows (e.g two different projects)
2. Use any non-default window switcher (Witch, Contexts, etc)
3. Switch from one VSCode window to another

CPU usage will spike to 100% and hang there for a long time.

**Comment by ccnixon** [comment]
Also had the same issue with Contexts/Vscode

**Comment by skevy** [comment]
Had this same issue with Context/Vscode

**Comment by youurayy** [comment]
I had this issue also with Slack when the Call window was opened. (I don't know how much this contributed to me stopping to use Mac but I'm now on Windows.)
The resolution to this could be as simple as Electron consuming the keystroke sent by the window-switching API, instead of infinite-looping on it.

**Comment by jhiemer** [comment]
same problem here with standard window switcher on OSx Mojave.

**Comment by miniak** [comment]
Do you still reproduce this issue with Electron >= 3?

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by youurayy** [comment]
okay to close, I don't see this issue popping up on Mojave with latest Code / Slack / etc.
thanks!
