### ISSUE TITLE
Check for `index.electron.js` file

### ISSUE THREAD

**Issue by piranna** [electron/electron#12603]
The same way that `index.js` file is used by default, check first for an `index.electron.js` file. This can be useful for [re-start](https://github.com/react-everywhere/re-start) apps where the same source code can be used for several platforms (Electron being one of them).

**Comment by MarshallOfSound** [comment]
> The same way that index.js file is used by default

Using `index.js` as default is handy but not recommended for prod, you should include a `package.json` file with a `main` entry pointing at the entrypoint of your app.

```json
{
  "main": "./src/index/electron.js"
}
```

**Comment by piranna** [comment]
> you should include a package.json file with a main entry pointing at the entrypoint of your app.

Yeah, that's what I'm already using, a main entry pointing to `index.electron.js`, but it looks a bit nasty since I'm using the `main` field for the entry point of a particular platform instead of the true "main" project main file...
