### ISSUE TITLE
some error occurd  when mainWindow.loadURL('local html files') 

### ISSUE THREAD

**Issue by DustFinger001** [electron/electron#12600]
* Electron version: 1.8.4
* Operating system: windows 7

### Expected behavior

when mainWindow.loadURL('local html files') , there is no error occured in third part js source. 

### Actual behavior
when i load a local html in electron BrowserWindow ,i add a third part js source , some error occurd like this. but there is no error when open this html page in chrome.
![image](https://user-images.githubusercontent.com/16345979/38671546-51cde28e-3e7e-11e8-95de-47daadf6aad7.png)

### How to reproduce
load a html like this
![image](https://user-images.githubusercontent.com/16345979/38672134-e2f59ef4-3e7f-11e8-994c-2d7be4d7588a.png)

**Comment by sofianguy** [comment]
Thanks for reaching out!

GitHub issues are for feature requests and bug reports. Check out the [Electron community](https://github.com/electron/electron#community) for questions about using Electron or code assistance. There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
