### ISSUE TITLE
MUSL-Libc support

### ISSUE THREAD

**Issue by kenny-w1** [electron/electron#12610]
Hi, I was wondering if you guys could add support for MUSL-Libc Linux distros, Void Linux mainly, as I think they are the ones with the best MUSL distro so far.
I don't know if its already supported or not, but I 'think' its not supported at least from what I can see.
MUSL is very reliable, uses less RAM than glibc & gets better battery power, there are many great benefits to MUSL! 

"a new standard library to power a new generation of Linux-based devices. musl is lightweight, fast, simple, free, and strives to be correct in the sense of standards-conformance and safety."
https://www.musl-libc.org/

**Comment by kenny-w1** [comment]
I can run 
./script/bootstrap.py --verbose
successfully in root, but can't do this:
./script/build.py --compdb
or this
./script/build.py
both give me this:

vendor/depot_tools/ninja: line 30: /home/user/Compiles/electron/vendor/depot_tools/ninja-linux64: No such file or directory

**Comment by kenny-w1** [comment]
When I try to change ninja-linux to just "ninja" I get:

vendor/depot_tools/ninja: line 30: /home/kzn/Compiles/electron/vendor/depot_tools/ninja64: No such file or directory

and, when I create a ninja64 file with nano, I get:
vendor/depot_tools/ninja: line 30: /home/kzn/Compiles/electron/vendor/depot_tools/ninja64: Permission denied
vendor/depot_tools/ninja: line 30: exec: /home/kzn/Compiles/electron/vendor/depot_tools/ninja64: cannot execute: Permission denied

**Comment by ckerr** [comment]
Hi @kenny-w1,

In order for this to happen someone would need to confirm that Chromium, Node, et al will run correctly on it and to add support for it in all the affected build scripts, so I don't think it's likely this will be on the project's supported roadmap.

However MUSL-libc does indeed look cool. If a volunteer wrote the code to make this happen, I suspect the project would accept the code as an unsupported feature.

**Comment by skeggse** [comment]
See also #9662.
