### ISSUE TITLE
autoUpdater clarification

### ISSUE THREAD

**Issue by zeke** [electron/electron#12618]
In the [current `autoUpdater` API doc for the `update-downloaded` event,](https://github.com/electron/electron/blob/e606a74de3cba32d44af031af0f2e59e442245da/docs/api/auto-updater.md#event-update-downloaded) the following message exists:

> On Windows only `releaseName` is available.

Does this mean "The `releaseName` is only available on Windows" or does it mean "On Windows, only the `releaseName` is available, and the other properties are not set"?

cc @zcbenz

**Comment by MarshallOfSound** [comment]
On windows the object has a single property `releaseName`

**Comment by ckerr** [comment]
Is that still correct?

I'm not sure that I'm reading the code right, but it looks like updateURL might be right too
