### ISSUE TITLE
Mouse event isn't dispatched when pointer is outside the BrowserWindow

### ISSUE THREAD

**Issue by unixzii** [electron/electron#12613]
* Electron version: Electron 2.0.0-beta.7
* Operating system: macOS 10.13.2 (17C205)

### Expected behavior

Web page should respond to mouse moving when pointer is outside the BrowserWindow.

### Actual behavior

Browser just doesn't dispatch `MouseEvent` if I set `BrowserWindow`'s `titleBarStyle` to `'hiddenInset'`. But when `titleBarStyle` is set to other values, the thing goes well.

### How to reproduce

Create a `BrowserWindow` with option `{ titleBarStyle: 'hiddenInset' }`, then load a page that has  `mousedown` and `mousemove` events (the listener behavior can be as easy as `console.log` ) attached to an element.

Try to press down the element and drag the mouse out of `BrowserWindow`, and you will see `mousemove` event stop being dispatched.

**Comment by ckerr** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

If you have time, please consider writing a minimal Electron app -- for example, a fork of [electron-quick-start](https://github.com/electron/electron-quick-start) -- that a tester could run to reproduce this issue.

This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

Thanks in advance! Your help is appreciated.

**Comment by unixzii** [comment]
Thanks for your replying.

Unfortunately, when I turn to making a demo app, it just doesn't reproduce this problem. Maybe the demo does not reach the complexity of our real world app and this issue was also possibly caused by ourself.

So I decide to close this issue, thank you anyway!
