### ISSUE TITLE
Deprecate UploadFileSystem

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#12611]
https://electronjs.org/docs/api/structures/upload-file-system
It has been removed in the Chromium 66 (or slightly earlier).

/cc @deepak1556, @codebytere

**Comment by codebytere** [comment]
@alexeykuzmin is there a newer version or is it just gonna get removed?

**Comment by deepak1556** [comment]
@codebytere https://electronjs.org/docs/api/structures/upload-blob is the alternative although its not a direct replacement for filesystem url.

**Comment by alexeykuzmin** [comment]
@ckerr Since this API won't be available in Electron 4 (Chromium 66) we must deprecate it in Electron 3. I just added this task to the Blockers column on the 3.x.y board.

**Comment by codebytere** [comment]
i'll do it today @alexeykuzmin
