### ISSUE TITLE
Can't change package (.app) name of Electron App for Mac OS

### ISSUE THREAD

**Issue by Polenov** [electron/electron#12628]
* Electron version: 1.8.2
* Operating system: Mac OS 10.13.4.

I created an Electron app, renamed Electron.app to Trader.app, also renamed binaries and Helpers. Of course, I edited all related plists. Everything worked fine. 

Now I want to rename my app again. From Trader.app to Traderno.app (just for example). I renamed Trader.app to Traderno.app, renamed executable file from Trader to Traderno. Also renamed `Bundle display name`, `Executable file` and `Bundle name` to Traderno in Info.plist. Then I changed `Bundle Identifier` to `some.text.traderno` in Info.plist. I decided not to rename Helpers. Hope it's not necessary. Then I performed codesign. 

And app now crashes at startup with following error:

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Trace/BPT trap: 5
Termination Reason:    Namespace SIGNAL, Code 0x5
Terminating Process:   exc handler [0]
```

Of course I edited my parent.plist with new `Bundle Identifier` before launch codesign.

If I revert all changes back to Trader name, then it will work again. Seems like I am doing something wrong in renaming process, but I can't find out what's the problem.

**Comment by codebytere** [comment]
Hi @Polenov, there's an API call for that specific purpose: https://electronjs.org/docs/api/app#appsetnamename

You want to call `app.setName(name)`; you should undo all of your manual changes and then try that, it should resolve your issues.

**Comment by Polenov** [comment]
@codebytere, no I don't want to change the name inside my app. I want to change how it appears in file system. I want to change the package (.app) name.

**Comment by ckerr** [comment]
@Polenov it seems that you were able to successfully rename it once, to `Trader`, so this doesn't seem to be an Electron bug.

GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).

**Comment by mqliutie** [comment]
@Polenov  Hi bro, How did you solve this problem? I have same trouble
