### ISSUE TITLE
Clipboard NativeImage to canvas has blue tint

### ISSUE THREAD

**Issue by TheColorRed** [electron/electron#12625]
* Electron version: v1.8.4
* Operating system: Ubuntu 17.10

### Expected behavior

When getting image data from the clipboard and writing it to the canvas, the image should display as it originally was.

![blue-tint-normal](https://user-images.githubusercontent.com/1571806/38780579-952fe276-409e-11e8-9418-f6159cda84b3.png)

### Actual behavior

When getting image data from the clipboard and writing it to the canvas, the image has a blue tint to it.

![blue-tint](https://user-images.githubusercontent.com/1571806/38780580-9cabfa94-409e-11e8-8cec-ae99255a2ace.png)

### How to reproduce

First:

```
git clone git@github.com:TheColorRed/electron-blue-image-tint.git
npm install
npm start
```

Next:
1. Copy an image to your clipboard, such as this one: 
![blue-tint-normal](https://user-images.githubusercontent.com/1571806/38780579-952fe276-409e-11e8-9418-f6159cda84b3.png)
1. In the app go `Edit -> Paste`

#### Main Process
```js
let img = clipboard.readImage()
mainWindow && mainWindow.webContents.send('paste-image', img.toBitmap(), img.getSize())
```
#### Rendering Process
```js
ipcRenderer.addListener('paste-image', (e, img, size) => {
  let canvas = document.createElement('canvas')
  let ctx = canvas.getContext('2d')
  canvas.width = size.width
  canvas.height = size.height
  document.body.appendChild(canvas)

  let data = new ImageData(new Uint8ClampedArray(img), size.width, size.height)
  ctx.putImageData(data, 0, 0)
})
```

**Comment by brenca** [comment]
By the looks of it this could be a `BGRA`-`RGBA` mixup issue.

**Comment by TheColorRed** [comment]
@ckerr you need to copy an image to your clipboard. Such as the first one in the post.

**Comment by ckerr** [comment]
Happens for me with Ubuntu 18.04, in both Electron 1.8.x and in `master`.

**Comment by TheColorRed** [comment]
This also happens for me with Windows 10 in Electron `1.8.x`

**Comment by miniak** [comment]
The pixel format of `NativeImage` is platform dependent and it not guaranteed to be compatible with the pixel format of `ImageData` use by HTML canvas.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by TheColorRed** [comment]
@sofianguy I have tested with electron `6.x.x` on Windows 10, and the issue still persists.

**Comment by d3bgger** [comment]
Happens to me also with the latest version 8.2.0 in windows 10 (1909) when using toBitmap().
Can we safely alter the colors order in windows platform as a workaround? Is this only a windows issue?

**Comment by d3bgger** [comment]
one more thing... this seems to also happen with **nativeImage.createFromPath()** not only with **clipboard.readImage()**

**Comment by javagrendel** [comment]
Seeing this same problem with images captured via **window.webContents.capturePage()** - issue occurs on Ubuntu 20.10, as well as Windows (v1909, build 18363.1198). Swapping red and blue values in the bitmap fixes it (per @TheColorRed)
Electron v11.0.1
GPU NVIDIA Quadro P520
IBM ThinkPad P53s

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by aleksey-shmatov** [comment]
This is still reproducible in electron v17.0.0 on Mac.
