### ISSUE TITLE
ECONNRESET error on server when closing app

### ISSUE THREAD

**Issue by csf30816** [electron/electron#12620]
* Electron version: v1.8.4
* Operating system: Windows 10

### Expected behavior

I expected that when closing the Electron window that the WebSocket connection would closed safely, like it does in the browser.

### Actual behavior

When I close the Electron window the server gets the `ECONNRESET` error because the WebSocket did not close properly. Although when you do this in a browser (Chrome or FireFox) the WebSocket closes properly.

### How to reproduce

In JavaScript (in an Electron app) connect to a NodeJS WebSocket Server using the `WebSocket` API. Close the Electron window while monitoring the NodeJS WS Server. You should see the `ECONNRESET` error. This may not be the best "reproduce" but my app was originally for the Web and it has lot's of code I don't want public.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
