### ISSUE TITLE
window.open with nativeWindowOpen option causes memory leak

### ISSUE THREAD

**Issue by KochiyaOcean** [electron/electron#12634]
* Electron version: 2.0.0-beta.7
* Operating system: Windows 10 x64

### Expected behavior

When `webPreferences.nativeWindowOpen` is set to true, BrowserWindows opened by `window.open`'s memory will be released after be closed.

### Actual behavior

The memory is not released and caused memory leak

### How to reproduce
- Clone https://github.com/KochiyaOcean/electron-bugs/tree/native-open-memory-leak
- Run `electron . ` in the cloned repo
- Memory usage of electron process will be increasing in task manager

**Comment by KochiyaOcean** [comment]
Seems this issue is relative to https://github.com/electron/electron/issues/12027

**Comment by MarshallOfSound** [comment]
Appears to occur on all known Electron versions with this feature 👍 Approximately 5MB per window

**Comment by GhostDev26** [comment]
Still occurs on 2.0.9

**Comment by VishwasShashidhar** [comment]
We've observed this on 3.0.0 as well.

**Comment by zcbenz** [comment]
From the profile of heap allocations, it seems that the V8 contexts of the new windows have never been released, resulting in a leak of V8 contexts in the renderer process of the embedder page.

**Comment by VishwasShashidhar** [comment]
@zcbenz Thanks for the details. Is there a work-around for this at the moment?

**Comment by orange4glace** [comment]
I tested on the latest electron and seems it's still happening.

**Comment by orange4glace** [comment]
Tested on nightly build version, (4.0.0-nightly.201) it seems it's still happening even nodeIntegration is disabled.

**Comment by KochiyaOcean** [comment]
@orange4glace https://github.com/electron/electron/issues/15666 seems it will be fixed in 5.0.x release.
