### ISSUE TITLE
Migrate from base::Bind() to base::BindOnce() or base::BindRepeating()

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#12639]
Chromium is doing that. Also please consider using `base::{Once,Repeating}Callback` instead of `base::Callback`.

See https://crbug.com/714018 and https://chromium.googlesource.com/chromium/src/+/master/docs/callback.md for details.

/cc @electron/code-owners

**Comment by codebytere** [comment]
This has been completed.
