### ISSUE TITLE
Main app menu is buggy on macOS if user interacts with it while it's being updated

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#12636]
* Electron version: 2.0.0-beta.7
* Operating system: macOS 10.13.4

### Expected behavior

I expected Electron to not update the menu while it's being interacted with.

It should behave like native and not update when open.

### Actual behavior

![electron-menu](https://user-images.githubusercontent.com/170270/38865525-3b962074-4268-11e8-88f5-a2b9943a9718.gif)

### How to reproduce

Run this and try to click the Electron menu and hover Bar menu item multiple times.

```js
const electron = require('electron');

const buildMenu = () => {
	electron.Menu.setApplicationMenu(electron.Menu.buildFromTemplate([{
		label: 'Foo',
		submenu: [
			{
				label: 'Bar'
			}
		]
	}]));
};

electron.app.on('ready', () => {
	setInterval(buildMenu, 1000);
});
```

Since Electron has no good way to make dynamic menus, rebuilding it based on events in the renderer process is the only way to keep the menu in sync with the content in the renderer.

**Comment by petrbrzek** [comment]
@sindresorhus Is it specific to version 2.0? I think the same thing happens in 1.x as well.
