### ISSUE TITLE
process.defaultApp is only ever true in the main process

### ISSUE THREAD

**Issue by timfish** [electron/electron#12635]
It might just be a matter of updating the docs.

### Steps to reproduce
- Open devtools of a non-packaged Electron app 
- Paste `process.defaultApp` into the devtools console

### Expected
`process.defaultApp == true`

### Actual
`process.defaultApp == undefined`
`require('electron').remote.process.defaultApp == true`

**Comment by miniak** [comment]
The documentation already says
> A `Boolean`. When app is started by being passed as parameter to the default app, this
property is `true` in the main process, otherwise it is `undefined`.
