### ISSUE TITLE
Buffer protocol handler reponsds with "200 OK200 OK"

### ISSUE THREAD

**Issue by YurySolovyov** [electron/electron#12657]
* Electron version: 1.8.4
* Operating system: Linux

### Expected behavior

Status code header should be: "Status Code: 200 OK"

### Actual behavior

![image](https://user-images.githubusercontent.com/2168518/38956639-ddff69da-4360-11e8-9cf5-91372cde2c5e.png)
Status code header says "Status Code:200 OK200 OK"

### How to reproduce

Any use  of `.registerBufferProtocol` API

**Comment by robjtede** [comment]
Can confirm this still happens in the electron v3 beta (the intercept* version in my case)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by YurySolovyov** [comment]
Isn't info in the OP enough to check if that's reproducible?
