### ISSUE TITLE
Bug with icon in TouchBarButton

### ISSUE THREAD

**Issue by cawa-93** [electron/electron#12658]
* Electron version: v1.8.4
* Operating system: macOS 10.13.4

I experimented with buttons and created with a picture of different sizes. Here is the result.

### Actual behavior
![image](https://user-images.githubusercontent.com/1662812/38957553-a31458a0-4363-11e8-8088-daf705bac79f.png)
![image](https://user-images.githubusercontent.com/1662812/38957608-c124c802-4363-11e8-979b-fb1b4896852e.png)
![image](https://user-images.githubusercontent.com/1662812/38957684-e0bb6bd0-4363-11e8-82a8-26f349aa0895.png)
![image](https://user-images.githubusercontent.com/1662812/38957763-152915ca-4364-11e8-9105-2447d84dad53.png)
![image](https://user-images.githubusercontent.com/1662812/38957861-4ca3892c-4364-11e8-9869-68f29fed7ca1.png)
![image](https://user-images.githubusercontent.com/1662812/38957918-711b191e-4364-11e8-9470-de8d2b0bf2af.png)

As you can see, if you increase the size of an image then the image on the button is not variable, but the distance between the image and the text increases.

### Expected behavior
The distance between the image and the text remains unchanged

### How to reproduce

```js
mainWindow.setTouchBar(new TouchBar([
	new TouchBarButton({
		label: '500x500',
		iconPosition: 'left',
		icon: path.join(__dirname, '/static/fakeimg.pl.png')
	})
]));
```

**Comment by cawa-93** [comment]
The problem is also observed on electron v2.0.0-beta.8

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
