### ISSUE TITLE
HTML fullscreen mode not exited when window-level fullscreen mode is left

### ISSUE THREAD

**Issue by miniak** [electron/electron#12653]
* Electron version: 2.0.0-beta.7
* Operating system: macOS 10.13.4

### Expected behavior

When HTML fullscreen mode is active, exiting fullscreen on the window level (clicking the green button or calling `win.setFullScreen(false)` should also exit HTML fullscreen mode.

### Actual behavior

HTML fullscreen mode stays active. Chrome correctly exits HTML fullscreen mode.

### How to reproduce

Use console in the default_app:

```
document.addEventListener('webkitfullscreenchange', () => console.log('webkitfullscreenchange'));
document.documentElement.webkitRequestFullscreen();
```

now exit fullscreen by clicking the green button or run `require('electron').remote.getCurrentWindow().setFullScreen(false);`

Compare to what happens when you do the same in Chrome/Chromium
`webkitfullscreenchange` should be logged twice (once for enter, once for exit)
`document.webkitFullscreenElement` should also be `null`

Possible workaround is:
```
win.on('leave-full-screen', () => {
  win.webContents.executeJavaScript('document.webkitExitFullscreen();');
});
```

**Comment by miniak** [comment]
It also reproduces on Windows

**Comment by jerryyan1990** [comment]
same problem
