### ISSUE TITLE
Beacon in onbeforeunload is not sent

### ISSUE THREAD

**Issue by BrendanDphs** [electron/electron#12654]
* Electron version: 1.8.4
* Operating system: Windows 10

My electron app displays remote content that I control. (with nodeIntegration off) This content sends POST requests to notify the server that a user has navigated away from a page using the beacon api.

This takes the form of an event like this:

```
window.addEventListener("beforeunload", function(e) {
	var form = new FormData();
	form.append('cancel', 'stuff');
	navigator.sendBeacon('upload', form);
});
```

This works in Firefox and Chrome, but does not work when the same content is viewed in an Electron app, _unless_ the dev tools are open. Then the beacon is sent normally when the window is closed.

### Expected behavior

When the Electron window containing the content is closed, a POST request is sent to the server.

### Actual behavior

No message is sent, except if the dev tools are open. Then the content works normally.

### How to reproduce

Set up a webserver that serves a page with the above event. Listen for requests when Electron windows viewing that content are closed.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
