### ISSUE TITLE
MacOS unexpected closing on window.close 

### ISSUE THREAD

**Issue by sarah97** [electron/electron#12668]
* Electron version: 1.8.3 (tested in 1.8.4 as well)
* Operating system: multiple OSX versions  (10.11.6 and 10.13.3), this is a MacOS issue. 

### Expected behavior

After calling window.close(), window.onbeforeunload will be triggered, a notification will appear prompting user to either cancel the action or quit the application. Upon selecting "cancel" the application will continue to run.

### Actual behavior

Sporadically upon selecting "cancel" the app will close. We are unsure whether this is a crash or if our methodology is wrong.

### How to reproduce

We have an exit button in the main window that calls `window.close()`, which then triggers the onbeforeunload event below, choosing "Cancel" will sporadically cause the application to close: 

```
window.onbeforeunload = event => {
  event.returnValue = false;
  dimWindow();
  var detail = "";

  remote.dialog.showMessageBox(
    {
      type: "question",
      message: "Are you sure you want to exit?",
      detail: detail,
      buttons: ["Exit", "Cancel"],
      noLink: true,
      defaultId: 1,
      cancelId: 1
    },
    function(response) {
      undimWindow();
      if (response == 0) {
        console.log("User opted to exit.");
        powerSaveBlocker.stop(powerId);
        remote.app.exit(0);
      } else if (response == 1) {
        console.log("User opted not to exit.");
        event.returnValue = false;
      }
    }
  );
};
```

Is this an appropriate method to prompt the user to either cancel the action or close the appliation? Are there any recommended alternatives?

**Comment by e9gille** [comment]
I've had that problem in the past and found that preventing the window from being closed seems to require a fast response from the onbeforeunload callback. In your example, if showMesssageBox takes too long to create the dialog window it may cause the window to close.

I ended up setting a flag and creating the message box with a setTimeout, something like this:
```
var shouldClose = false;
window.onbeforeunload = event => {
  if (shouldClose) return;
  event.returnValue = false;
  dimWindow();
  var detail = "";
  setTimeout(() => {
    remote.dialog.showMessageBox(
    {
      type: "question",
      message: "Are you sure you want to exit?",
      detail: detail,
      buttons: ["Exit", "Cancel"],
      noLink: true,
      defaultId: 1,
      cancelId: 1
    },
    function(response) {
      undimWindow();
      if (response == 0) {
        console.log("User opted to exit.");
        shouldClose = true;
        powerSaveBlocker.stop(powerId);
        remote.app.exit(0);
      } else if (response == 1) {
        console.log("User opted not to exit.");
      }
    }
  );
  }, 10);
};
```

**Comment by sarah97** [comment]
I tried your fix and it worked. Thank you!
