### ISSUE TITLE
systemPreferences.getAccentColor() Returns the wrong colour on Windows 10

### ISSUE THREAD

**Issue by Bartastic** [electron/electron#12667]
* Electron version: 1.8.4
* Operating system: Windows 10

### Expected behavior

Calling systemPreferences.getAccentColor() should return the user-set Accent colour from Settings > Personalization > Colours

### Actual behavior

systemPreferences.getAccentColor() Returns a colour with an Alpha channel - this actually cannot be set in Windows 10. I took a look at the source, and it looks like this call actually returns the glass composition colour. I would expect this should return the same value set via the settings application.

### How to reproduce

1. In Windows 10, set a custom accent colour via Settings > Personalization > Colours (I set it to #1A00CC)
2. In your electron app call systemPreferences.getAccentColor(), this call will return 1700b7e3 (At least it does on my system).

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
