### ISSUE TITLE
Multi-monitor enhanced support in BrowserWindow class family

### ISSUE THREAD

**Issue by h3rb** [electron/electron#12664]
Originally misposted: "I'm interested in writing a game engine with Electron. Some of the more advanced features of desktops involve picking the target monitor,  I can't seem to find a way to tell a BrowserWindow to open fullscreen on any other monitor than the "1" monitor on windows. It would be nice to be able to do that.  It would also be nice to tell a BrowserWindow to resize / adapt to a target monitor/display #"

* Electron version: April 2018
* Operating system: Windows (and others)

### Expected behavior

There should be a way to tell the BrowserWindow and related classes to "open fullscreen on a specific display device"

### Actual behavior

There seems to be no way to specify this display easily, yet there is a way to get a display list.

It would be nice to:

mainWindow->SizeToDisplay(..)
mainWindow->CenterOnDisplay(..)

And in creation parameters:

(default: 1 - current behavior)
display: #  // Will size to display or center on display requested
display: "largest"  // Figures out which of the display list is the largest monitor / resolution
display: "same"    // Same as launch (I noticed this doesn't do this either)

When using fullscreen, or not, this could specify which display to examine for fullscreen sizing or for window centering.

### How to reproduce

n/a

**Comment by MarshallOfSound** [comment]
All of this can be done in userland, each display you get has an `x`, `y`, `width` and `height` through the `bounds` property.  The 2d coordinate system used for positioning windows goes across screens.  I.e. the top left of two screens share a coordinate system and are therefore not both `(0, 0)`.

If you want to position a window onto display X you just have to call `setPosition(x, y)` where x and y are in the bounds indicated by the display object returned by `screen.getAllDisplays()`

**Comment by MarshallOfSound** [comment]
Refs:

https://electronjs.org/docs/api/screen#screengetalldisplays
https://electronjs.org/docs/api/structures/display
