### ISSUE TITLE
electron.remote throws lacking errors

### ISSUE THREAD

**Issue by t-hiroishi** [electron/electron#12670]
* Electron version: 1.8.4
* Operating system: Windows 7 Professional (64bit SP1)

### Expected behavior

* Custom Error objects are correctly received by the renderer process when thrown from the main process.
* Error objects have information about the process that it was thrown.

### Actual behavior

* Custom Error objects are lacking when thrown from the main process to the renderer process.
* Error objects have no information about the process.

**In my project, I need to use `remote.require` to ensure that the same native modules required by different processes are the same object.**

### How to reproduce

Same as #10316.

```
$ git clone https://github.com/tom-seddon/electron-remote-exception
$ npm install
$ npm start
```

### Suggestion to change

Use chaining errors, supporting Joyent's [verror](https://github.com/joyent/node-verror).

* [lib/browser/rpc-server.js#callFunction](https://github.com/electron/electron/blob/v1.8.4/lib/browser/rpc-server.js#L256-L257)
  * diff: add `cause` property (for the original error) to the created error in catch statement

```js
// Call a function and send reply asynchronously if it's a an asynchronous
// style function and the caller didn't pass a callback.
const callFunction = function (event, func, caller, args) {
  let funcMarkedAsync, funcName, funcPassedCallback, ref, ret
  funcMarkedAsync = v8Util.getHiddenValue(func, 'asynchronous')
  funcPassedCallback = typeof args[args.length - 1] === 'function'
  try {
    if (funcMarkedAsync && !funcPassedCallback) {
      args.push(function (ret) {
        event.returnValue = valueToMeta(event.sender, ret, true)
      })
      func.apply(caller, args)
    } else {
      ret = func.apply(caller, args)
      event.returnValue = valueToMeta(event.sender, ret, true)
    }
  } catch (error) {
    // Catch functions thrown further down in function invocation and wrap
    // them with the function name so it's easier to trace things like
    // `Error processing argument -1.`
    funcName = ((ref = func.name) != null) ? ref : 'anonymous'
    const err = new Error(`Could not call remote function '${funcName}'. Check that the function signature is correct. Underlying error: ${error.message}`)
    err.cause = error
    throw err
  }
}
```

* [lib/browser/rpc-server.js#exceptionToMeta](https://github.com/electron/electron/blob/v1.8.4/lib/browser/rpc-server.js#L135-L139)
  * diff: add `cause` property to exception meta

```js
// Convert Error into meta data.
const exceptionToMeta = function (sender, error) {
  return {
    type: 'exception',
    message: error.message,
    stack: error.stack || error,
    cause: valueToMeta(sender, error.cause)
  }
}
```

* [lib/renderer/api/remote.js#metaToValue](https://github.com/electron/electron/blob/v1.8.4/lib/renderer/api/remote.js#L209)
  * diff: convert the custom error from the main process

```js
// Convert meta data from browser into real value.
function metaToValue (meta) {
  const types = {
    value: () => meta.value,
    array: () => meta.members.map((member) => metaToValue(member)),
    buffer: () => Buffer.from(meta.value),
    promise: () => resolvePromise({then: metaToValue(meta.then)}),
    error: () => metaToPlainObject(meta),
    date: () => new Date(meta.value),
    exception: () => { throw metaToException(meta) }
  }
  ...
}

...

// Construct an exception error from the meta.
function metaToException (meta) {
  const error = new Error(`${meta.message}\n${meta.stack}`)
  const remoteProcess = exports.process
  error.from = remoteProcess ? remoteProcess.type : null
  error.cause = metaToValue(meta.cause)
  return error
}
```

Thanks,

t-hiroishi

**Comment by MarshallOfSound** [comment]
@t-hiroishi Would you be able to make a PR with these changes, they seem 👌 in this issue thread but would need to see them in context to know for sure 😄

**Comment by t-hiroishi** [comment]
@MarshallOfSound ok, I'll check the PR process and try it :smile:

**Comment by codebytere** [comment]
Closed by merge of https://github.com/electron/electron/pull/12694 🚀

**Comment by MarshallOfSound** [comment]
Unfortunately not, that PR is tagged as a non breaking feature which according to our versioning policy can't go into a patch (2.0.x) release

**Comment by TE-TakamichiHayashi** [comment]
Thank you for quick response.
We will wait for 3.0.0 release.
