### ISSUE TITLE
useContentSize not work on mac with modal dialog

### ISSUE THREAD

**Issue by MCMicS** [electron/electron#12671]
* Electron version: 1.8.4
* Operating system: macos
* sample: https://github.com/MCMicS/electron-issues/tree/electr-issue-useContentSize

### Expected behavior
modal sheet on mac has same size like the windows on windows

### Actual behavior
The height is 22px smaller

### How to reproduce

1. open new modal BrowserWindow

**Comment by k-onishi** [comment]
same problem here

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by MCMicS** [comment]
tested with 4.0.1 and it seems to be fixed
