### ISSUE TITLE
showMessageBox as modal should prevent parent window from being closed

### ISSUE THREAD

**Issue by e9gille** [electron/electron#12672]
* Electron version: 1.8.4
* Operating system: Ubuntu 17.10

### Expected behavior

When creating a modal message box using showMessageBox(browserWindow, options) the browserWindow's close button (in title bar) should be disabled until the modal message has been dismissed.
This works as expected on MacOS and Windows.

### Actual behavior

When the modal is displayed, browserWindow is dimmed and disabled, but the title bar is still enabled and allows you to close the window.

### How to reproduce
```

  $ git clone https://github.com/e9gille/electron-quick-start -b show-message-box
  $ cd electron-quick-start
  $ npm install
  $ npm start

```

**Comment by e9gille** [comment]
Just checked and this is still a problem in electron v3.0.9.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
