### ISSUE TITLE
startDrag should work from renderer to simplify usage

### ISSUE THREAD

**Issue by timfish** [electron/electron#12685]
The docs for `startDrag` don't mention this but it has to be called from the main process. This means many have the following boilerplate in their main process:

```
ipcMain.on('ondragstart', (event, paths, icon) => {
    event.sender.startDrag({
```
And then have to access the API via IPC:
```
ipcRenderer.send('ondragstart', paths, icon);
```

The docs could be updated to mention that `startDrag` should be called in this way but it would be better if it worked from the renderer and Electron handled the IPC for you.

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR.
