### ISSUE TITLE
`shell.openItem`  is not activate the opened app

### ISSUE THREAD

**Issue by lingmumu** [electron/electron#12687]
* Electron version: v1.8.4
* Operating system:win7/win10

### Expected behavior
Click on the picture and open the picture. The picture should be placed at the top of the window.
![image](https://user-images.githubusercontent.com/22462790/39095873-378d9528-467a-11e8-91f0-f16960257b44.png)
### Actual behavior
App blocked the picture.
![image](https://user-images.githubusercontent.com/22462790/39095875-426b1c04-467a-11e8-8c94-91998d1cb867.png)
### How to reproduce
`shell.openItem('C:/Users/ASUS/Desktop/vue-calc-master/vue-calc/src/renderer/assets/icons/1.png')`

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
