### ISSUE TITLE
BrowserView Steals BrowserWindow Input Field Editability

### ISSUE THREAD

**Issue by mattdesl** [electron/electron#12680]
* Electron version: 1.8.4 and 2.0.0-beta.7
* Operating system: macOS Sierra 10.12.6

### Expected behavior

An `<input>` field in BrowserWindow page should be editable even if there is a BrowserView content below it.

### Actual behavior

When interacting with the BrowserView, you can no longer edit the text in the BrowserWindow, even though the content is not overlapping.

### How to reproduce

Test repo included:

https://github.com/mattdesl/electron-test-toolbar

### Use Case

I'd like a custom toolbar (think like a Chrome URL nav/history buttons) that sits atop a web view, but I would rather use BrowserView since it provides the closest experience to using regular Chrome (in performance, dev tool integration, does not populate Elements/Sources with app-specific features, etc).

Alternatively, if possible, I would love for any other ideas on how to render a custom toolbar atop remote web content without relying on `<webview>` or `BrowserView`.

**Comment by mattdesl** [comment]
I found a temporary workaround: add a renderer preload script to each webContents that does the following:

```js
const remote = require('electron').remote;
window.addEventListener('click', () => remote.getCurrentWebContents().focus());
```

See the `fix` branch: 
https://github.com/mattdesl/electron-test-toolbar/tree/fix

**Comment by sikanhe** [comment]
I think this only happens on hiddenInset titlebar, can you confirm?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
