### ISSUE TITLE
Sometimes window zooms in and cannot zoom out

### ISSUE THREAD

**Issue by fadookie** [electron/electron#12688]
* Electron version:
Unknown (Discord v0.0.250, Slack Version Unknown)
* Operating system:
macOS 10.11.6

* Last known working Electron version: 
Unknown

### Expected behavior
Apps should never be able to be zoomed in on. If this does happen, it should be possible to zoom out.

### Actual behavior
Sometimes, Electron apps will zoom in. Just recently this happened in Discord when being operated by the touchpad. I do have zoom gestures enabled but they don't normally have any effect on the app. In the rare occasions this happens, the apps cannot be zoomed out again as far as I can tell. The window can be interacted with and scrolled around using the touchpad. The app must be restarted to restore normal zoom level.

I have seen this happen in Slack and Discord at least a few times but I'm not sure how to reproduce. Seeing it in both apps is what leads me to believe this is a bug in electron itself.

Here is a screencap showing the most recent occurrence:
![discord_bug](https://user-images.githubusercontent.com/110764/39098379-e02b0d34-461e-11e8-9e2d-81ca1eba9aa5.gif)

Note how the window management buttons scroll completely off of the window.

### How to reproduce
Unknown, sorry.

**Comment by MarshallOfSound** [comment]
This is called pinch zooming and it is default electron behavior unless app devs explicitly disable it.  It's not actually a bug in Electron.

You can follow https://github.com/electron/electron/issues/12631 for progress / updates on changing this default and you should reach out to app support channels for any app that's doing this and raise it with them if you want them to disable it.

**Comment by fadookie** [comment]
@MarshallOfSound if this is a feature rather than a bug, why is it I can't get it to trigger most of the time, and I am unable to zoom out after I have zoomed in?

**Comment by nornagon** [comment]
To turn pinch-zooming off, use `webContents.setVisualZoomLevelLimits(1, 1)`

https://github.com/electron/electron/blob/master/docs/api/web-contents.md#contentssetvisualzoomlevellimitsminimumlevel-maximumlevel
