### ISSUE TITLE
shell.openExternal() Windows URL not working

### ISSUE THREAD

**Issue by rakesh-agrawal** [electron/electron#12691]
* Electron version:1.6.16
* Operating system: Windows 10

Hi,

We are using shell.openExternal to open default internet explorer browser from my windows 10 system, but the url is not opening:

const shell = require('electron').shell;

var authorizeUrl = "https://gazzlezero.auth0.com/authorize?audience=https://aeroroero.auth0.com/api/v2/&response_type=code&client_id=4TEKnyducuiyiuyb7r02LWmHtdKqsuVueu&code_challenge=ExLLEql4VERNsybF5YSDsfNAqyraYiqoKkzpz0vItXc&code_challenge_method=S256&redirect_uri=com.gazzlezero.aeroroero://localhost:3000/authorize";

shell.openExternal(authorizeUrl);

Browsers opens but the url doesnt open.
This works on other browsers.

Thanks in advance for any help

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
