### ISSUE TITLE
Disable chrome autoplay policies

### ISSUE THREAD

**Issue by sebakerckhof** [electron/electron#12697]
It looks like [work on Chrome 66 ](https://github.com/electron/electron/projects/10) is ongoing.

Chrome 66 has new policies around autoplay of audio:
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

These don't make sense for electron applications.Will these be disabled or will there be a way to disable them?

**Comment by paulcbetts** [comment]
I would still argue that autoplay policy should default to "play", and that we shouldn't force developers to dig through obscure flags that may or may not be present in future versions of Chromium

**Comment by ahallicks** [comment]
See also https://github.com/electron/electron/issues/13525

**Comment by blackwire** [comment]
As an avid Electron user and developer I appreciate your thoughtfulness, @paulcbetts. I think this is a good idea as well. At the very least there should be a browser window configuration setting that can be passed as a part of web preferences that allows you to choose the behavior you would prefer for your application.

**Comment by miniak** [comment]
looks like this is covered by the `autoplayPolicy` option in `BrowserWindowOptions` now.
