### ISSUE TITLE
Screenshot API

### ISSUE THREAD

**Issue by probablycorey** [electron/electron#127]
We could use https://github.com/niklasvh/html2canvas. But it does some fancy DOM tricks that I'd rather avoid because it doesn't give an exact representation. Is there a easy way to create an image from the native windows contents?

**Comment by dennislaupman** [comment]
Hi Zcbenz,

Is it possible to return the ARGB data? A function like toARGB would be awesome! If not, please can you help me to write the function?

Thanx!

Dennis

**Comment by sprintr** [comment]
@dennislaupman you can use [TinyColor](https://github.com/bgrins/TinyColor)

**Comment by zcbenz** [comment]
@dennislaupman Do you mean to ARGB bitmap? If so you can create an issue for it.
