### ISSUE TITLE
Application file path arrangement problem

### ISSUE THREAD

**Issue by stanleyxu2005** [electron/electron#12704]
* Electron version: 1.8.4
* Operating system: Windows 7 x64

Dear Developers,

In short, I'm wondering whether I can access files of myapp, using `app://` protocol? 

The longer version: 

I found the absolute file paths are insistent somehow. Here is a code example:
```
   const win = new BrowserWindow({
       webPreferences: {
             preload: `${__dirname}/myapp/preload.js`
       }
   })
   win.loadURL(`file://${__dirname}/myapp/index.html`)
```
As you can see, the path of the main page should be `http://|https://|file://`. However the path of `preload` script must be a valid local file path, `file://` is not supported (confirmed on Windows).

Is this inconsistency could be considered as a bug? 

On the other hand, I'm thinking why we need absolute file paths? Is there a way to load `index.html` like this `resource://index.html`, or this `app://index.html`? (It's clear that we can still freely access any physical files with node apis)

My ideal way to create a browser window would be:
```
   const win = new BrowserWindow({
       webPreferences: {
             preload: `app://reload.js`
       }
   })
   win.loadURL(`app://index.html`) 
```

I'd be very appreciated for your kindly comments.

**Comment by timfish** [comment]
`file://` works on Windows but you'll have problems with different path separators if you build URLs and paths manually like that. Use `path` and `url` and they handle this for you.

For example this works in all platforms:
```
const path = require('path');
const url = require('url');

window.loadURL(
  url.format({
    pathname: path.join(__dirname, 'index.html'),
    protocol: 'file:',
    slashes: true
  })
);

// etc.
webPreferences: {
  preload:  path.join(__dirname, 'preload.js')
}
```

**Comment by ckerr** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).

**Comment by stanleyxu2005** [comment]
@ckerr  Browser window's entry point is a url or a file protocol, but preload is a local file path, dont you think this is a bug?

**Comment by stanleyxu2005** [comment]
Update 1: to solve my 2nd problem, I use protocol.registerFileProtocol now. https://electronjs.org/docs/api/protocol#protocolregisterfileprotocolscheme-handler-completion
```javascript
const {app, protocol} = require('electron')
function registerAppProtocol() {
    const appDir = app.getAppPath()
    const offset = scheme.length + '://'.length
    const handleRequest = (request, callback) => {
      const filepath = request.url.substr(offset)
      const realpath = path.normalize(`${appDir}/${filepath}`)
      callback(realpath)
    }
    protocol.registerFileProtocol(scheme, handleRequest)
}
```
