### ISSUE TITLE
Detecting 'Put display to sleep' on MacOS

### ISSUE THREAD

**Issue by CameronFletcher92** [electron/electron#12706]
Both hot corners and 'CTRL + SHIFT + EJECT' can put the display to sleep without actually suspending the device. This means the `powerMonitor.on('suspend'` event is not emitted, which makes sense, but we still require a way of detecting this use case in electron.

Is there any known way to detect this situation? And if not, would it be possible to add this functionality to electron's powerMonitor? Ideally something like a `'screen-lock'` or `'display-sleep'` event emitted from `powerMonitor`. This would likely apply to other OS as well.

Ideally we would like to be able to detect:
- Screen-lock
![image](https://user-images.githubusercontent.com/1721120/39200847-e734fab4-47b2-11e8-8e43-cbdb5ba1e615.png)
- Putting display to sleep via hot corner
![image](https://user-images.githubusercontent.com/1721120/39197746-eecbc95e-47aa-11e8-9600-13272189b5e8.png)
- Putting display to sleep via 'CTRL + SHIFT + EJECT'

Not necessarily with the same powerMonitor events.

**Comment by MarshallOfSound** [comment]
Initial investigation shows that this can be easily implemented on macOS, Windows we have to subscribe to `WTS_SESSION_LOCK` and linux is a bit _weird_ emitting an event might be hard as even Chromium doesn't have an exact science for detecting lock screens.  They currently search through all windows for something that looks like a screensaver so unless we poll that API (not cheap) we can't emit this event on linux.

I'll get macOS working first 👍
