### ISSUE TITLE
Add setTitleBarStyle method to BrowserWindow

### ISSUE THREAD

**Issue by Pephers** [electron/electron#12701]
* Electron version: >= 1.8.2
* Operating system: Any macOS

### Feature request

Currently, the `titleBarStyle` option can only be passed an as option to the `BrowserWindow` constructor when initializing a new BrowserWindow to customize the behavior of the macOS title bar and traffic lights. This cannot be changed after the BrowserWindow been created.

Our team would like to be able to set the `titleBarStyle` on-the-fly after a BrowserWindow has been created. This functionality could be added to the BrowserWindow class as an instance method called, for instance, `setTitleBarStyle`. As an argument this method would accept the same values as set in the configuration in the constructor when creating a `new BrowserWindow`.

If this feature request sounds like a good idea we would like to contribute with the necessary code changes in a Pull Request. What do you think?

**Comment by MarshallOfSound** [comment]
> If this feature request sounds like a good idea we would like to contribute with the necessary code changes in a Pull Request. What do you think?

Go for it, 100% down for this to be a feature just from past experience modifying the state of things like titlebar masks was just too much of a nightmare, though that was me trying to toggle between `frame: true` and `frame: false` not just toggling titlebar styles so this might be doable 👍

**Comment by Pephers** [comment]
Thanks! Perfect, this sounds good. Agreed that the title bar masks are tricky to set up.
