### ISSUE TITLE
Question: How to Change BrowserWindow (Chromium) context menu language

### ISSUE THREAD

**Issue by WilliamHolmes** [electron/electron#12705]
Hi,

## Use Case
Our web app allows users to change their preferred language. (Accept-Language Header)

Is it possible to change the default BrowserWindow context menu language?

## Currently
![image](https://user-images.githubusercontent.com/5538260/39198416-ea0596fa-47de-11e8-8584-f6375ea17455.png)

In this example the user has chosen 'fr', but the context menu shows in English.

(My Local machine, Mac OS, English)

**Comment by MarshallOfSound** [comment]
Afaik Electron doesn't provide a default context menu, a different module must be giving that to you.  Probably `electron-spellchecker`

**Comment by WilliamHolmes** [comment]
@MarshallOfSound thanks. I've now opened an [issue](https://github.com/electron-userland/electron-spellchecker/issues/114) with `electron-spellchecker`
