### ISSUE TITLE
node ffi Async api behave differently in electron renderer and main process

### ISSUE THREAD

**Issue by sysleaf** [electron/electron#12708]
I am using node-ffi module to call dll api. i am using  async feature of node-ffi to call some API in async way..like below
```
mylib.getSetting.async(arg, (err, data));
```

these API work as expected(async non-blocking way) in nodejs.

But same api behave differently in electron main and renderer process.
In main process -- it works as expected(async non-blocking way)
In renderer process-- it works unexpected(syn blocking way), it block the whole UI until api returns.

I want my code to be in renderer, so i want my async api to work there.
Please help me resolve this issue.

**Comment by timfish** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).

I've used `node-ffi` and the `async` feature in the renderer and works as expected.
