### ISSUE TITLE
Cannot push elements to array from main-process on renderer-process

### ISSUE THREAD

**Issue by wspl** [electron/electron#12707]
* Electron version: 1.8.4 / 2.0.0-beta.7
  * Operating system: macOS 10.13.2
------
Following code works well:

`main-process.js`
```javascript
  global['arr'] = []
```
`renderer-process.js`
```javascript
  import { remote } from 'electron'
  let remoteArr = remote.getGlobal('arr')
  remoteArr.push(1)
  console.log(remoteArr) // expected value: [1], actual value: [1]
  remoteArr.push(2)
  console.log(remoteArr) // expected value: [1, 2], actual value: [1, 2]
```
------
But if I put the array into a class, and pass the class instance to renderer process, it cannot work properly:

`main-process.js`
```javascript
  class Demo {
    arr = []
  }
  global['demo'] = new Demo()
```
`renderer-process.js`
```javascript
  import { remote } from 'electron'
  let demo = remote.getGlobal('demo')
  demo.arr.push(1)
  console.log(demo.arr) // expected value: [1], actual value: [] 
  demo.arr.push(2)
  console.log(demo.arr) // expected value: [1, 2], actual value: [] 
```

The problem is that the renderer process cannot operate on arrays of a class instance passed from main process via `global`.

**Comment by MarshallOfSound** [comment]
This is explicitly documented behavior 👍 

https://electronjs.org/docs/api/remote#remote-objects

> Note: Arrays and Buffers are copied over IPC when accessed via the remote module. Modifying them in the renderer process does not modify them in the main process and vice versa.

**Comment by wspl** [comment]
@MarshallOfSound Is there any way to pass a reference via ipc?

**Comment by MarshallOfSound** [comment]
@wspl No, arrays are copied verbatim.

You could do something like

```js
global.pushToArr = (...items) => arr.push(...items)

// renderer
remote.getGlobal('pushToArr')(1, 2, 3, 4);
```
