### ISSUE TITLE
minWidth is not working on Ubuntu 17

### ISSUE THREAD

**Issue by aliazlan4** [electron/electron#12700]
minWidth is not working on ubuntu 17 but it is working perfectly on Windows. My electron version is set as `"electron": "^1.8.0"`. I am creating my window by the following line of code

`mainWindow = new BrowserWindow({ width: 1300, height: 726, minWidth: 1245, "web-references": { 'web-security': false } });`

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
