### ISSUE TITLE
Renderer process crashing on startup

### ISSUE THREAD

**Issue by WriterDuet** [electron/electron#12713]
* Electron version: 2.0.0-beta.7
* Operating system: OSX and Windows

### Expected behavior

Program successfully runs.

### Actual behavior

Program crashes to a white screen during initial load, no menus or anything are loaded.

### How to reproduce

This happens randomly after releasing the product. I have crash reporter enabled and have received 3 .dmp files so far. I can't attach the full application, but the OSX app can be downloaded from https://media.writerduet.com/desktop_app/v4/WriterDuet.dmg if you need any symbols (but I think you can just use the electron 2.0.0-beta.7 symbols natively).

I have attached the 3 .dmp files but don't know enough to determine what's going wrong in the renderer when it crashes. Doing a clean uninstall and reinstalling the application resolves it, but it's reproducible for users once they encounter it the first time.

[ElectronCrash.zip](https://github.com/electron/electron/files/1949300/ElectronCrash.zip)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
