### ISSUE TITLE
'Unable to find a valid app' error building electron app using electron-packager

### ISSUE THREAD

**Issue by alex1504** [electron/electron#12717]
When running my application using npm start, everything works fine. However after building my app using electron-packager and open .exe file, it occurs:
'Unable to find a valid app' , complete description is 

[error][1]

my packager.json file is:

    {
      "name": "electron-roll-tool",
      "version": "1.0.0",
      "description": "A minimal Electron application",
      "main": "src/main.js",
      "scripts": {
        "start": "electron .",
        "build": "electron-packager ./src/ electron-roll-tool --win --out ../dist --arch=x64 --version=0.0.1 --overwrite --electron-version=1.8.4"
      },
      "repository": "https://github.com/alex1504/electron-roll-tool",
      "keywords": [
        "Electron"
      ],
      "author": "GitHub",
      "license": "MIT",
      "devDependencies": {
        "electron": "^1.8.4",
        "electron-packager": "^12.0.1"
      },
      "dependencies": {
        "moment": "^2.22.1",
        "xlsx": "^0.12.10"
      }
    }

I change the entry point and my project structure is：

[project structure][2]

  [1]: https://i.stack.imgur.com/eLVP0.png
  [2]: https://i.stack.imgur.com/ByesH.png

How to solve this problem?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by MarshallOfSound** [comment]
That said, this is an easy one:

```bash
electron-packager ./ electron-roll-tool --win --out ./dist --arch=x64 --version=0.0.1 --overwrite --electron-version=1.8.4
```

**Comment by alex1504** [comment]
Thanks a lot for your answer, it works. I dont know there is a community website,  thank you for your mention.
