### ISSUE TITLE
Slack app on Windows won't launch if user/system has defined environment variable NODE_OPTIONS

### ISSUE THREAD

**Issue by jrfitz** [electron/electron#12711]
We had a person report:

To increase nodejs memory limits it's common to use f.e. "NODE_OPTIONS=--max-old-space-size=8192". 

For few seconds the slack.exe process appears in task manager, then disappears without any warnings or errors, doesn't matter if it's x32 or x64 version

Person thinks it’s something incompatible with node.dll(at initialization) slack use.

* Electron version: 1.8.x
* Operating system: Windows 10
* Slack version 3.1.1

### Expected behavior

Slack should launch without issue.

### Actual behavior

Slack process starts in task manager and ends quickly after, no error or crash reported.

### How to reproduce

User steps:

cmd
cd %USERPROFILE%\AppData\Local\Slack
set NODE_OPTIONS=--max-old-space-size=8192
slack.exe
It won’t start

If you:
set NODE_OPTIONS=
slack.exe

Slack starts without issue

**Comment by MarshallOfSound** [comment]
Duplicate #12695
