### ISSUE TITLE
unresponsive event is undocumented on webContents

### ISSUE THREAD

**Issue by timfish** [electron/electron#12710]
The `unresponsive` event is only [documented on BrowserWindow](https://electronjs.org/docs/api/browser-window#event-unresponsive) but appears to also work on `webContents`. 

Is this just a matter of updating the docs?

**Comment by codebytere** [comment]
I'd say yes...think you could potentially PR that in?

**Comment by timfish** [comment]
I'll do this tomorrow along with `responsive`.
