### ISSUE TITLE
Error running application (.exe) on windows

### ISSUE THREAD

**Issue by renatosistemasvc** [electron/electron#12715]
* Electron version:
current

* Operating system:
windows 7

* Last known working Electron version: 
working in ubuntu 16

### Expected behavior
application work in windows and linux environment

### Actual behavior
[image of erro](https://scontent.fvdc1-1.fna.fbcdn.net/v/t1.0-9/31357712_1050640795074487_5161791133415636992_o.jpg?_nc_cat=0&oh=3fce7b9e2771caf12a3104bab45bf3bf&oe=5B978619)

### How to reproduce
I started an eletronic project and did the integration with the database sequelize (sqlite). the following error appeared: please install sqlite3 package manually. 

I solved the ubuntu problem by running: electron-rebuild
But the same error is displayed when I build to generate .exe to run on windows.
I developed it in ubuntu and want to generate .exe to run on windows.
Can someone help me?

**Comment by MarshallOfSound** [comment]
> I developed it in ubuntu and want to generate .exe to run on windows.

Native modules need to be built on the platform you are targetting, I.e. in order to distribute to windows you need to build your app on windows not linux (if you have native modules, which you do because sqlite3 is a native module)

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
