### ISSUE TITLE
Unable to set cookies from html page

### ISSUE THREAD

**Issue by peererror** [electron/electron#12719]
I am trying to set cookies from  html page using 

```
function cookiesEnabled(){
  return ("cookie" in document && (document.cookie.length > 0 || (document.cookie = "test").indexOf.call(document.cookie, "test") > -1));
}
```

it always returns false . I am loading pages using file:// protocol .

Regards

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
