### ISSUE TITLE
Running electron fails if directory contains non-ASCII characters.

### ISSUE THREAD

**Issue by lmoesch** [electron/electron#12725]
* Electron version: 1.8.5
* Operating system: Windows 10

### Actual behavior

When any electron project is runned via `electron path` and `path` contains any non-ASCII characters, then the process fails e.g. on my computer with:

> fs.js:1669
>       binding.lstat(baseLong);
>               ^
> 
> Error: EINVAL: invalid argument, lstat 'C:\Users\Lucas M├Âsch\electron'
>     at realpathSync (fs.js:1669:15)
>     at Object.fs.realpathSync (ELECTRON_ASAR.js:330:24)
>     at toRealPath (module.js:143:13)
>     at Function.Module._findPath (module.js:192:22)
>     at Function.Module._resolveFilename (module.js:483:25)
>     at Function.Module._load (module.js:437:25)
>     at Function.Module.runMain (module.js:605:10)
>     at startup (bootstrap_node.js:167:16)
>     at bootstrap_node.js:589:3

where the path should be `C:\Users\Lucas Mösch\electron. Moving the project into another directory path containing just ASCII characters fixes this error.

### How to reproduce

Just run _any_ electron project with `electron path` from a directory path containing non-ASCII characters (ä,ü,ö,...)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
