### ISSUE TITLE
Electron 2.0.0-beta.8 file not found

### ISSUE THREAD

**Issue by immanoj16** [electron/electron#12739]
Hey, The in-app-purchase for MAS is introduced in beta version of electron 2.0.0. In the doc, there is a file `node_modules/electron/dist/Electron.app/Contents/Info.plist` is not present in my system.
In the `dist` folder, the `Electron.app` is not present.

I am currently using ubuntu

**Comment by MarshallOfSound** [comment]
On ubuntu you will get the Linux build of Electron, those plist files are only available on the macOS / MAS builds.
