### ISSUE TITLE
Can electron behave as native webkit browser? 

### ISSUE THREAD

**Issue by abhieee23** [electron/electron#12733]
I am using the latest electron version for my app. I want electron to behave as native browser when the operating system is MAC. I am aware of the fact that it is based on Chromium, but I want my app to support something which is supported by Safari only. Is it possible for electron app to act as a native browser?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by MarshallOfSound** [comment]
But also, no
