### ISSUE TITLE
App unresponsive after singleInstanceCallback browserWindow.restore call

### ISSUE THREAD

**Issue by simke9445** [electron/electron#12730]
* Electron version: 1.8.2
* Operating system: Windows 10

### Expected behavior
When I launch an application using the shortcut, while the application is already running and is minimized, the application should just restore to it's original state.

### Actual behavior
Application is restored, but the interface becomes unresponsive, input fields are not clickable, nothing basically. After you apply left click on an icon in the system tray, somehow the application is back to normal (weird).

### How to reproduce
```
app.makeSingleInstance(() => {
  if (mainWindow) {
    const browserWindow = mainWindow.getBrowserWindow();

    if (browserWindow.isMinimized() || !browserWindow.isVisible()) {
      browserWindow.restore();
    }

    browserWindow.focus();
  }
});
```
By calling browserWindow.restore(), the scenario above happens. If you switch to browserWindow.show() everything works as it should.

**Comment by dmckenna24** [comment]
Can confirm this bug on Mac.

Electron v. 1.8.2
Mac High Sierra v. 10.13.4

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
