### ISSUE TITLE
comprehensively hide devtools

### ISSUE THREAD

**Issue by pjebs** [electron/electron#12748]
How can I comprehensively hide the user from accessing the dev tools.

There are some of things I know how to do:
- remove from top menu
- remove toggle code when app starts up so it's initially hidden

What else must I do? Perhaps this should be in the documentation.
I read in a few places about handling the `--remote-debugging-port` command line argument. I read that if it exists, the app should just immediately exit.

Any other suggestions?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by pjebs** [comment]
consider it a feature request. Please add it to the docs.
