### ISSUE TITLE
dialog.showMessageBox() should have an option to set the primary button

### ISSUE THREAD

**Issue by abnerlee** [electron/electron#12744]
The issue is originally posted in https://github.com/electron/electron/issues/3810

But now the option of `defaultButtonIndex` has already been removed (no code result in https://github.com/electron/electron/search?utf8=%E2%9C%93&q=defaultButtonIndex&type=)

But it is still an useful option

**Comment by MarshallOfSound** [comment]
According to the docs I believe you are looking for `defaultId`
