### ISSUE TITLE
New event for `makeSingleInstance`

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#12752]
Currently, when a user calls `makeSingleInstance` they need to handle the second instance in a callback.

A better pattern for both users and third-party modules who want to use this information would be to emit an event on the `app` module when the second instance starts.

A pattern like:

```js
app.makeSingleInstance();

app.on('second-instance', (e, argv) => {
  // do-stuff
});
```

As step 1 I'll introduce support for the event and deprecate the callback.  Then in a major version, we can remove the callback.

**Comment by sindresorhus** [comment]
I always found the current `makeSingleInstance` API awkward. This looks much more user-friendly.

Any thoughts on making Electron apps single-instance by default? With ability ot opt-out instead. I can't imagine any scenario where I would want to allow multiple instances of an app.

**Comment by MarshallOfSound** [comment]
> Any thoughts on making Electron apps single-instance by default?

🤔 I know that some people use multiple instances of their app instead of multiple windows managed from a single instance.  Worth thinking about though.

Also worth noting we currently don't have a way to undo `makeSingleInstance` exposed so any effort to make it opt-out would require new API's and such 👍 

Will deal with this issue then raise one for discussing changing the default, I agree the default should be single instance we just need to feel out the impact of that change
