### ISSUE TITLE
In-app-purchase documentation link broken

### ISSUE THREAD

**Issue by rr326** [electron/electron#12751]
The following link gives a 404:
https://electronjs.org/docs/api/in-app-purchase 

Linked from here:
Modules for the Main Process ... InAppPurchase

The content clearly exists:
https://github.com/electron/electron/blob/master/docs/api/in-app-purchase.md

**Comment by MarshallOfSound** [comment]
Can you provide a link for "Linked from here", I can't find a link to that URL on the site

**Comment by rr326** [comment]
https://electronjs.org/docs/all

Search for "InAppPurchase"

**Comment by MarshallOfSound** [comment]
@zeke This is kinda weird, not sure how it got in there 🤔

**Comment by rr326** [comment]
There IS a documentation page, so presumably the features exist. (I sure hope so - I need it!)

https://github.com/electron/electron/blob/master/docs/api/in-app-purchase.md

**Comment by MarshallOfSound** [comment]
@rr326 The feature exists but only in the `2-0-x` line, the website should be showing the docs for latest stable (1-8-x).  So this link shouldn't be here 🤔

**Comment by rr326** [comment]
Aha! That makes sense.

That also means it's time for me to upgrade. I'll sign off here. Thanks.

**Comment by zeke** [comment]
> The feature exists but only in the 2-0-x line, the website should be showing the docs for latest stable (1-8-x).

Yep. Sorry for the confusion, @rr326! I opened https://github.com/electron/electronjs.org/issues/1239 to track this.

FWIW, the 2.0 will very soon land in a stable release, after which https://electronjs.org/docs/api/in-app-purchase will work.

**Comment by zeke** [comment]
It's live now: https://electronjs.org/docs/api/in-app-purchase
