### ISSUE TITLE
BrowserWindow minWidth ignored on windows

### ISSUE THREAD

**Issue by topched** [electron/electron#12755]
Electron Version: 1.8.2
Windows: 8 and 10

### Expected Behaviour
All OS' respect the minWidth provided to the BrowserWindow

### Actual behaviour
On linux/mac the code below works perfectly, but on windows the browser window is ~14px under the specified minWidth which adds a horizontal scrollbar when it should not be there.

### How to reproduce
Just using this code you can see the issue. (Note you can put any url in there or take out the webview and just put some content, its always under the specified minWidth)

Here is Main.js

```
const { app, BrowserWindow } = require('electron');

let mainWindow;

app.on('window-all-closed', () => { app.quit(); });

app.on('ready', () => {
    mainWin = new BrowserWindow({
        width: 400,
        height: 600,
        minWidth: 300,
        minHeight: 400
    });
    mainWin.loadURL('file://`' + __dirname + './index.html');
});
```

Here is the index.html
```
<!DOCTYPE html>
<html>
    <head>
    <style>
       html, body { height: 100%; margin: 0; }
       body {
         display: flex;
         flex-flow: column;
         background: #ddd;
       }

       webview { flex: 1; }
    </style>
    <body>
      <webview src="www.github.com"></webview>
    </body>
</html>
```

**Comment by topched** [comment]
Just wanted to add a follow-up comment to the issue. If I add `useContentWidth: true` it does respect the minWidth on windows.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by gtkpr** [comment]
> Just wanted to add a follow-up comment to the issue. If I add `useContentWidth: true` it does respect the minWidth on windows.

The property is now called `useContentSize` and defaults to `false`.
