### ISSUE TITLE
2.0.0 doesn't launch on a macOS machine without admin access

### ISSUE THREAD

**Issue by artch** [electron/electron#12761]
* Electron version: 2.0.0
* Operating system: macOS High Sierra 10.13.4 (I'm using [MacinCloud service](https://www.macincloud.com/) to run Mac machine remotely).

* Last known working Electron version: 1.8.6

### Expected behavior

Electron launches with a standard welcome screen.

### Actual behavior

Electron launches with an empty screen on the same blue background but without welcome contents:

![mstsc_2018-05-01_14-05-42](https://user-images.githubusercontent.com/2923269/39470872-c54e0120-4d48-11e8-8563-099184fbc669.png)

### How to reproduce

Download Electron release, launch it without arguments.

**Comment by sofianguy** [comment]
Hi @artch, one of the team members tried to reproduce the issue and was not able to. Can you provide us with logs so that we can narrow down the issue? 
You can use: 
`ELECTRON_ENABLE_LOGGING=true` and `ELECTRON_ENABLE_STACK_DUMPING=true`

**Comment by artch** [comment]
Thanks for a quick response! It shows the following:

```bash 
[9225:0502/083822.794796:INFO:CONSOLE(188)] "%cElectron Security Warning (Insecure Content-Security-Policy)", source: /Users/user909423/Downloads/electron-v2.0.0-beta.8-darwin-x64/Electron.app/Contents/Resources/electron.asar/renderer/security-warnings.js (188)
```

Setting `ELECTRON_ENABLE_LOGGING=true` and `ELECTRON_ENABLE_STACK_DUMPING=true` doesn't seem to change anything.

**Comment by artch** [comment]
Here is a short GIF demonstrating this issue:

![fpj8mhytdcatwxdqccxs8_swujlvgief_g](https://user-images.githubusercontent.com/2923269/39661809-b787eae0-5060-11e8-9767-6acafd40ea22.gif)

**Comment by artch** [comment]
So I've rented another remote server on MacinCloud, a dedicated one, and Electron is working on it. The difference is that the second server is virtualized (using VMware) with administrator access, and my first server is a physical Mac mini with no admin privileges. And Electron 1.8.6 works fine on both servers, but 2.0.0 works only on the dedicated admin one.

Although it might be a temporary work around for me, but it would be great to make it work in both cases.

**Comment by sethlu** [comment]
I'm wondering if this maybe something related to the GPU renderer as passing `--disable-gpu` seems to fix the issue. 🤔 Alternatively, after some experiments, here's the line that perhaps prevents the rendering (but something's missing on the logo now), with Electron v2.0.1:

![screenshot 2018-05-20 22 35 21](https://user-images.githubusercontent.com/3168941/40292145-574564da-5c7e-11e8-8297-ea2526f6897f.png)
![screenshot 2018-05-20 22 35 25](https://user-images.githubusercontent.com/3168941/40292147-58c79990-5c7e-11e8-82fe-6c93d3605512.png)

**Comment by jarek-foksa** [comment]
This could be related to https://github.com/electron/electron/issues/10736

**Comment by miniak** [comment]
Does this reproduce with Electron >= 3?

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
