### ISSUE TITLE
Tray Icon Greyed Out On Mac OSX High Sierra In Dark Mode

### ISSUE THREAD

**Issue by mbruschi** [electron/electron#12765]
* Electron version: 1.8.6 (I even tried the latest beta-8 due to this https://github.com/electron/electron/pull/12395)
* Operating system: Mac OSX 10.13.5 Beta
* Last known working Electron version: All of them, it's more a High Sierra Issue. But the example here https://github.com/maxogden/menubar is working and is using an old electron-prebuilt. If I use the latest electron instead of that prebuilt, the example app tray icon becomes greyed out too.

### Expected behavior
The tray icon should actually be full white and not greyed out.

### Actual behavior
The tray icon is greyed out.

<img width="148" alt="screenshot 2018-05-01 17 14 59" src="https://user-images.githubusercontent.com/6988573/39478662-5916aeba-4d63-11e8-98a4-6c6d3fedf652.png">

When you click on it, it's fine.

<img width="140" alt="screenshot 2018-05-01 17 16 57" src="https://user-images.githubusercontent.com/6988573/39478725-7b7fd4e0-4d63-11e8-8daa-b62da015663c.png">

Happens to all apps that are build with electron and that have a tray icon.

### How to reproduce
Just get the latest https://github.com/electron/electron-api-demos, run it on high sierra, open the `Put your app in the tray` demo and you will see it.

```
$ git clone https://github.com/electron/electron-api-demos
$ cd electron-api-demos
$ npm install
$ npm start
```

**Comment by codebytere** [comment]
@mbruschi this is not the case on `2.0.0`, running `electron-api-demos` using it demonstrates expected behavior. However, it doesn't look like the fix got backported to `1-8-x`, so i'll fix that now.

**Comment by mbruschi** [comment]
@codebytere with all the respect, I don't think we're talking about the same issue. The highlighting is not the issue. It's the tray icon, being greyed out or having some opacity and not shown in full white. I tried it again with 2.0.0 and made a repository here https://github.com/mbruschi/electron-api-demos and the issue shown in the images above still happens.

**Comment by codebytere** [comment]
@mbruschi ah ok, no worries! i'll check that out in the morning :)

**Comment by codebytere** [comment]
@mbruschi alright i'm running High Sierra and your repro and am seeing only:

<img width="245" alt="screen shot 2018-05-02 at 9 28 34 am" src="https://user-images.githubusercontent.com/2036040/39536355-33452c4c-4deb-11e8-936e-5c13f1c3fb7a.png">

Also tried on `1.8.6`, so it doesn't seem like this is reproducible 🤔

**Comment by mbruschi** [comment]
@codebytere well, then it seems to be a bug only on my setup. I tried to switch from the Beta High Sierra to the non-beta 10.13.4 but the bug still appears. However, this might be just a super random edge case and I will try to find out why my setup is causing this 🤔

**Comment by codebytere** [comment]
@mbruschi in that case, i'm going to go ahead and close this out but if you find something else or it becomes reproducible ping me and i'll reopen this!

**Comment by mbruschi** [comment]
Thank you for your time.

**Comment by dbousamra** [comment]
This is occurring for me. Intermittently. I don't have a way to reproduce sorry
