### ISSUE TITLE
Tray context menu doesn't pop up if a fullscreen application is focused

### ISSUE THREAD

**Issue by InventivetalentDev** [electron/electron#12760]
* Electron version: `1.8.6`, `3.1.0`
* Operating system: Windows 10

### Expected behavior

I expect the tray context menu to open when I right-click it.

### Actual behavior

When there's a fullscreen app running and focused (behind the taskbar), nothing happens when right-clicking the tray icon.

### How to reproduce

* Start the program
* Right-click the tray while on desktop/with a non-fullscreen app - **works fine**
* Open a fullscreen app
  * I discovered it while playing Guild Wars 2, but it also occurs on any other fullscreen application, e.g. Google Chrome (F11)
* Press the Windows key to bring up the taskbar
* Try right-clicking the tray icon again - **nothing happens**

(I also tried it on another computer (also Win 10), just to make sure it's not a quirk with my dev pc.)

EDIT: I noticed the same issue with Discord, which is also built with electron. 

You can use the repo below to see for yourself:

```
  $ git clone https://github.com/InventivetalentDev/GuildWars2EmoteWheel.git
  $ npm install
  $ npm run electron-rebuild
  $ npm start
```

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by InventivetalentDev** [comment]
Yep, still happening on electron `3.1.0`

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by fmeyertoens** [comment]
![electron-tray](https://user-images.githubusercontent.com/26410884/62820351-5395e680-bb63-11e9-9e7e-c72ff7bf102f.gif)
I made a gif showing that the context menu doesn't show up when you click the tray icon while it does show when the tray icon is in the overflow menu.
Electron version: `6.0.1`

**Comment by Kyusung4698** [comment]
Hi, this is still an issue for me. Are there any updates on this?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by harknesslabs** [comment]
Still a issue on current version 15.1.1

**Comment by Manikai769** [comment]
The issue is still existing.

- Electron version: 36.4.0
- Operating system: Windows 11 / 10

Expected and actual behavior as mentioned in previous comments.
Can be reproduced as shown in the previous comments gif.
