### ISSUE TITLE
Native browser context menus don't display for pages hosted in a webview

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#12777]
* Electron version: 1.8.4
* Operating system: Windows 10

I may be going crazy, but I recall being able to trigger the native context menus for the embedded page, but now I cannot, and I'm wondering if this is intentional? If it is I'm curious why it works this way. Is it not feasible to get native context menus?

### Expected behavior

Right clicking in page that's hosted in a webview should display the native context menus.

### Actual behavior

Nothing happens.

### How to reproduce
I cloned electron-quick-start and replaced index.html's body element with:

    <webview src="https://google.com"></webview>

Launching the app and right clicking on the page doesn't bring up the native browser context menu.

**Comment by pushkin-** [comment]
Ah, it looks like [this issue](https://github.com/electron/electron/issues/7021) answers my question, yes? It's a Chrome thing not a Chromium thing.

**Comment by codebytere** [comment]
Sadly yes @pushkin-...we might be able to improve our Menu API in the future to allow for this but right now it's a no-go
