### ISSUE TITLE
node-fibers cannot be used in Electron V2.0.0

### ISSUE THREAD

**Issue by firestarman-james** [electron/electron#12788]
Hello,
node-fibers cannot be used in Electron V2.0.0 which released recently.
I've tryed to use electron-rebuild to build a new fibers.node, but Electron got stucked (almostly) after running `require('fibers')`.

FYI: node-fibers can be used normally in Electron V1.8.6 after rebuilding fibers.node.
My OS is win10 x64 14393.1670. WindowsTargetPlatformVersion is 10.0.16299.0.

Thx!

开发者你好！
node-fibers在刚发布的Electron V2.0.0无法正常使用。通过 electron-rebuild 重新编译以后在Electron V2.0.0里运行 `require('fibers')` 时会导致electron卡死。但是Electron V1.8.6中node-fibers是正常可用的。
不知道其他人是不是也有这个问题。谢谢啦！

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by ckerr** [comment]
@sofianguy, I don't think this should be closed as a question; it looks like a bug report to me.

@firestarman-james, could you add a small piece of code that triggers the bug you described? For example, a toy app branched from https://github.com/electron/electron-quick-start would be wonderful.

**Comment by firestarman-james** [comment]
Thanks to @ckerr and you all!
I also submitted a issue to node-fibers: `https://github.com/laverdet/node-fibers/issues/374`, for your reference.

@laverdet got the same DLL error. After running electron-rebuild, @laverdet found it work fine. But for me, the new `fibers.node` get Electron 2.0.0 stuck.

repro as below:
1. Download `node-v8.9.3-win-x64.7z` from `https://nodejs.org/download/release/v8.9.3/`, unpack it, and modify `path (environment variable)` to make sure `node` can be run everywhere.

2. Download `electron-quick-start-master.zip` from `https://github.com/electron/electron-quick-start/archive/master.zip`,  unpack all the files (`package.json` and so on) to path `D:\electron\electron-quick-start-master`.

3. Modify `devDependencies` in file `package.json` under path `D:\electron\electron-quick-start-master`, to `"devDependencies": { "electron": "^2.0.0", "fibers": "^2.0.2" }`

4. Use CMD to install and run:
```
D:\electron\electron-quick-start-master>node -v
v8.9.3

D:\electron\electron-quick-start-master>npm install

> fibers@2.0.2 install D:\electron\electron-quick-start-master\node_modules\fibers
> node build.js || nodejs build.js

'win32-x64-57' exists; testing
Binary is fine; exiting

> electron@2.0.0 postinstall D:\electron\electron-quick-start-master\node_modules\electron
> node install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
added 154 packages in 66.697s

D:\electron\electron-quick-start-master>.\node_modules\.bin\electron.cmd .
```

5. When the electron window shows, press `Ctrl+Shift+I` to open `Developer Tools`, and run `require('fibers')` in the `Console`. Then I got the error as below.
```
require('fibers')
D:\electron\electron-quick-start-master\node_modules\fibers\fibers.js:16 ## There is an issue with node-fibers ##
D:\electron\electron-quick-start-master\node_modules\fibers\bin\win32-x64-57\fibers.node is missing.

Try running this to fix the issue: D:\electron\electron-quick-start-master\node_modules\electron\dist\electron.exe D:\electron\electron-quick-start-master\node_modules\fibers/build
(anonymous) @ D:\electron\electron-quick-start-master\node_modules\fibers\fibers.js:16
(anonymous) @ D:\electron\electron-quick-start-master\node_modules\fibers\fibers.js:106
Module._compile @ module.js:642
Module._extensions..js @ module.js:653
Module.load @ module.js:561
tryModuleLoad @ module.js:504
Module._load @ module.js:496
Module.require @ module.js:586
require @ internal/module.js:11
(anonymous) @ VM127:1
D:\electron\electron-quick-start-master\node_modules\fibers\fibers.js:21 Error: A dynamic link library (DLL) initialization routine failed.
\\?\D:\electron\electron-quick-start-master\node_modules\fibers\bin\win32-x64-57\fibers.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\electron\electron-quick-start-master\node_modules\fibers\fibers.js:13:39)
    at Object.<anonymous> (D:\electron\electron-quick-start-master\node_modules\fibers\fibers.js:106:3)
(anonymous) @ D:\electron\electron-quick-start-master\node_modules\fibers\fibers.js:21
(anonymous) @ D:\electron\electron-quick-start-master\node_modules\fibers\fibers.js:106
Module._compile @ module.js:642
Module._extensions..js @ module.js:653
Module.load @ module.js:561
tryModuleLoad @ module.js:504
Module._load @ module.js:496
Module.require @ module.js:586
require @ internal/module.js:11
(anonymous) @ VM127:1
D:\electron\electron-quick-start-master\node_modules\fibers\fibers.js:22 Uncaught Error: Missing binary. See message above.
    at Object.<anonymous> (D:\electron\electron-quick-start-master\node_modules\fibers\fibers.js:22)
    at Object.<anonymous> (D:\electron\electron-quick-start-master\node_modules\fibers\fibers.js:106)
    at Module._compile (module.js:642)
    at Object.Module._extensions..js (module.js:653)
    at Module.load (module.js:561)
    at tryModuleLoad (module.js:504)
    at Function.Module._load (module.js:496)
    at Module.require (module.js:586)
    at require (internal/module.js:11)
    at <anonymous>:1:1
```

Maybe the key is `A dynamic link library (DLL) initialization routine failed.`.

6. When running `D:\electron\electron-quick-start-master\node_modules\electron\dist\electron.exe D:\electron\electron-quick-start-master\node_modules\fibers/build`, I got the error as below.

```
D:\electron\electron-quick-start-master>D:\electron\electron-quick-start-master\node_modules\electron\dist\electron.exe D:\electron\electron-quick-start-master\node_modules\fibers/build

D:\electron\electron-quick-start-master>
win32-x64-57 exists; testing
Problem with the binary; manual build incoming
```

```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
TypeError [ERR_INVALID_OPT_VALUE]: The value "Readable {
  _readableState: 
   ReadableState {
     objectMode: false,
     highWaterMark: 16384,
     buffer: BufferList { head: null, tail: null, length: 0 },
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: null,
     ended: true,
     endEmitted: false,
     reading: false,
     sync: true,
     needReadable: false,
     emittedReadable: true,
     readableListening: false,
     resumeScheduled: false,
     destroyed: false,
     defaultEncoding: 'utf8',
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: true,
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined }" is invalid for option "stdio"
    at internal/child_process.js:899:13
    at Array.reduce (<anonymous>)
    at _validateStdio (internal/child_process.js:825:17)
    at ChildProcess.spawn (internal/child_process.js:270:11)
    at Object.exports.spawn (child_process.js:514:9)
    at build (D:\electron\electron-quick-start-master\node_modules\fibers\build.js:57:5)
    at D:\electron\electron-quick-start-master\node_modules\fibers\build.js:39:5
    at ChildProcess.exithandler (child_process.js:294:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
```

7. I've tryed to run `electron-rebuild` to build a new `fibers.node`, but failed on electron 2.0.0 (Electron got stucked after running `require('fibers')`, nothing returned, and nothing more can be run), only succeeded on electron 1.8.6 or below.
![electron_stucked](https://user-images.githubusercontent.com/18347506/39748451-a6cabdcc-529f-11e8-8575-586ad9701d88.png)

**Comment by laverdet** [comment]
This isn't an electron bug.

**Comment by codebytere** [comment]
Closing in agreement with the above; this is a Node.js issue and should be opened there should it still be occurring on supported versions of Electron.
