### ISSUE TITLE
Document autoUpdater alternatives for Linux

### ISSUE THREAD

**Issue by zeke** [electron/electron#12796]
Linux doesn't get much love in our [current autoUpdater API docs](https://github.com/electron/electron/blob/master/docs/api/auto-updater.md):

> There is no built-in support for auto-updater on Linux, so it is recommended to use the distribution's package manager to update your app.

Here are a few things that came up in a Slack conversation yesterday:

- serve deb/rpm feeds using packagecloud.io
- use `electron-installer-snap`
- use https://github.com/atlassian/nucleus - Supports windows, macOS and both variants of Linux repos (apt / yum), all just backed by an s3 bucket
- Snaps are supported by canonical
- Problem with using Snaps is then you get involved in the Snap vs AppImage debate
- Discord folks get asked for 32 bit linux builds all the time

Anyone wanna take a shot at summarizing the available options? What we have now is basically nothing, so it doesn't have to be comprehensive or opinionated to be an improvement.

cc @jhgg @timfish @malept @MarshallOfSound @felixrieseberg @bengotow @daviwil @Kilian

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!

**Comment by chesucr** [comment]
Anyway I believe I could autoupdate an application in Linux with [`AppImage`](https://www.electron.build/configuration/appimage) and `electron-builder` at least, if I remember well
