### ISSUE TITLE
Electron 2.0.0-beta.8 gtk_widget_get_scale_factor on startup

### ISSUE THREAD

**Issue by SamuelRobotiq** [electron/electron#12795]
* Electron version: Electron 2.0.0-beta.8 linux ia32
* Operating system: Linux Debian 7.11

* Last known working Electron version: None

### Expected behavior
Electron start and the window is displayed.

### Actual behavior
```
>> export DISPLAY=:0
>> ./electron
```

`.../myUser/electron: symbol lookup error: .../myUser/electron: undefined symbol: gtk_widget_get_scale_factor`

### How to reproduce
Execute electron on Debian 7.11

Any idea on how to quick fix this?

**Comment by ckerr** [comment]
According to [this doc](https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-get-scale-factor), `gtk_widget_get_scale_factor()` was added in GTK+ 3.10, which was released in Sep 2013. Please ensure that your installed version of GTK+ 3 is >= 3.10.

This function is being called by libchromiumcontent, not Electron itself, so there's not much that can be done at the Electron level to change this dependency.
