### ISSUE TITLE
Unhandled errors in renderer in node context terminate the renderer

### ISSUE THREAD

**Issue by timfish** [electron/electron#12798]
* Electron version: 1.8.6 
Does not occur on 2.0.0
* Operating system: Win 10

Paste the following into the devtools console and the renderer terminates:
```
window.setImmediate(() => {throw new Error('Die!')});
```
Adding a `uncaughtException` listener on process stops the renderer from exiting
```
process.on('uncaughtException', () => {})
```
That difference in behaviour appears to be due to this code in `renderer/init.js`:
```
  // Redirect window.onerror to uncaughtException.
  window.onerror = function (message, filename, lineno, colno, error) {
    if (global.process.listeners('uncaughtException').length > 0) {
      global.process.emit('uncaughtException', error)
      return true
    } else {
      return false
    }
  }
```

**Comment by Zrylhh** [comment]
It seems i have a same problem ?

+ Electron version: 3.0.10
    
    hava not try other version

+ Operating system: Win 7


add a uncaughtException listener in the main process

```
    process.on('uncaughtException', function (error) {
        console.log(error);
    }
```
and excute this in the devtools 

```
    const makeError = function(){console.log(i)}
    setTimeout(function(){makeError()},200)
```

but there is no error log as expect.

The code in the renderer/init.js
```
    // Redirect window.onerror to uncaughtException.
    window.onerror = function (message, filename, lineno, colno, error) {
        if (global.process.listeners('uncaughtException').length > 0) {
            global.process.emit('uncaughtException', error)
            return true
        } else {
            return false
        }
    }
```
it seems have a diffrent **process** with the main process , or should i try to debug in renderer ?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by Raynos** [comment]
@sofianguy 

This is still an issue with latest electron 7

```
window.setImmediate(() => {throw new Error('Die!')});
```

The following code causes the devtools to be disconnected, with or without the uncaught exception handler.
