### ISSUE TITLE
create-dist.py expects pdf_viewer_resources.pak, which is not built (windows ia32)

### ISSUE THREAD

**Issue by bughit** [electron/electron#12799]
* Electron version: master (82329124ffcb2012d101c79236e82fbe6ba79c36)
* Operating system: win7 sp1 x64

* Last known working Electron version: 

### Expected behavior

create-dist should work

### Actual behavior

```
Traceback (most recent call last):
  File "C:\Users\alex\src\electron\script\create-dist.py", line 335, in <module>
    sys.exit(main())
  File "C:\Users\alex\src\electron\script\create-dist.py", line 96, in main
    copy_binaries()
  File "C:\Users\alex\src\electron\script\create-dist.py", line 126, in copy_binaries
    shutil.copy2(os.path.join(OUT_DIR, binary), DIST_DIR)
  File "C:\Python27\lib\shutil.py", line 144, in copy2
    copyfile(src, dst)
  File "C:\Python27\lib\shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'C:\\Users\\alex\\src\\electron\\out\\R\\pdf_viewer_resources.pak'
```

### How to reproduce

1. script\clean.py
2. script\bootstrap.py -v --target_arch=ia32
3. script\update.py --msvs
4. script\build.py -c R
5. script\create-dist.py -v --no_api_docs

**Comment by bughit** [comment]
If you comment out pdf_viewer_resources.pak, the next exception is

```
Traceback (most recent call last):
  File "C:\Users\alex\src\electron\script\create-dist.py", line 335, in <module>
    sys.exit(main())
  File "C:\Users\alex\src\electron\script\create-dist.py", line 102, in main
    copy_ucrt_binaries()
  File "C:\Users\alex\src\electron\script\create-dist.py", line 179, in copy_ucrt_binaries
    raise Exception('UCRT files not found')
Exception: UCRT files not found
```

This is because (on my machine) it should be looking in Wow6432Node:

`HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows Kits\Installed Roots`

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
