### ISSUE TITLE
Setting resizable: false and height with setContentSize which is more than display height sets window height equals content height

### ISSUE THREAD

**Issue by nrlquaker** [electron/electron#12800]
* Electron version: 2.00, 1.8.4
* Operating system: macOS 10.13.4

* Last known working Electron version: none

### Expected behavior
Setting `resizable: false` and height with `setContentSize` which is more than display height sets window height equals display height - dock (if its on the bottom). To be able to scroll all content.
I expect it to be working the same as `resizable: true`. Only difference should be the unability to resize window.

### Actual behavior
Setting 'resizable: false' and height with `setContentSize` which is more than display height sets window height equals content height.

### How to reproduce
Sample repo:
```
git clone https://github.com/nrlquaker/electron-quick-start.git -b window-resizable
npm install
npm start
```
Check behavior with `resizable: true`, then set it to `false`.

**Comment by codebytere** [comment]
This no longer seems to occur on more recent versions of Electron.
