### ISSUE TITLE
Warning on titlebarAppearsTransparent when setting frame: false or titleBarStyle: hidden

### ISSUE THREAD

**Issue by caesarsol** [electron/electron#12814]
This is still a problem as of 2.0.0, as described in these (now closed) issues: https://github.com/electron/electron/issues/11150
https://github.com/electron/electron/issues/11169
https://github.com/electron/electron/issues/11743

The warning is:
```
Electron *** WARNING: Textured window <AtomNSWindow: 0x7fe3687673e0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
```

Electron version: 2.0.0
Operating system: Mac OS 10.13.4

**Comment by alanning** [comment]
For a reproduction of this issue, please run the framless-window sample electron app located here:

https://github.com/hokein/electron-sample-apps/tree/master/frameless-window

Reproduction steps:
(assumes yarn already installed)

```
$ cd ~/tmp
$ git clone https://github.com/hokein/electron-sample-apps
$ cd electron-sample-apps
$ yarn add electron
$ npx electron --version
v2.0.0
$ npx electron frameless-window
2018-05-13 15:07:44.376 Electron[42121:6477918] *** WARNING: Textured window <AtomNSWindow: 0x7fd0f473fa00> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
```

**Comment by joernroeder** [comment]
any updates on this?

**Comment by ckerr** [comment]
Using the test case provided in https://github.com/electron/electron/issues/12814#issuecomment-388649133 I can confirm this still exists in Electron 2.0.5.

It's also not a Mac-specific issue; I'm also seeing it on Ubuntu Linux

**Comment by codebytere** [comment]
This no longer occurs on 3-0-x, I've confirmed with the repro steps!

**Comment by Slapbox** [comment]
@codebytere I'm still seeing this with `Electron@3.0.0` on macOS 10.13.2 with `frame: false` and all other `BrowserWindow` options left to defaults.

`2018-10-01 18:06:06.072 Electron[39479:673750] *** WARNING: Textured window <AtomNSWindow: 0x7f8594f3c000> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.`

**Comment by BinaryMuse** [comment]
When running an example through [Fiddle](https://github.com/electron/fiddle), even with the latest Electron beta (4.0.0-beta.4), I can reproduce the issue, but as soon as I try to do so with a local debug build off `master` the issue disappears. Needs some more investigation 🔍

**Comment by BinaryMuse** [comment]
On a hunch, I built a release version of Electron (and got my lap nice and toasty) but I'm also unable to reproduce with this. Very strange.

I wonder if this could have something to do with the SDK we link against for release builds? I checked with @MarshallOfSound and we link against 10.12 currently.

**Comment by wuwb** [comment]
Reproducible on Electron 4.0.1

**Comment by geakstr** [comment]
Still exists in 4.0.4

**Comment by meizikeai** [comment]
Still exists in 4.0.6

**Comment by solidgoldpig** [comment]
Still exists in 4.1.0

**Comment by cxdy** [comment]
Not working for me either.

```
// my window
  window = new BrowserWindow({
    width: 300,
    height: 450,
    show: false,
    frame: false,
    fullscreenable: false,
    webPreferences: {
      backgroundThrottling: false
    }
  })
```
// current software
Electron - v4.16.0
Node - v10.15.1
OS - macOS 10.14.3
```

**Comment by Slapbox** [comment]
@cxdy there's no `Electron@4.16.0` right now that I'm aware of.

**Comment by cxdy** [comment]
@Slapbox that's just the version NPM gave me

**Comment by BenjaminHoegh** [comment]
> @Slapbox that's just the version NPM gave me

NPM gives me v5.0.0 so I'm also confuse, still got the error tho

**Comment by inweid** [comment]
Still exists in 5.0.1

**Comment by limichange** [comment]
Still exists in 5.0.4

**Comment by matt3224** [comment]
5.0.6 too 😔

**Comment by geovanipfranca** [comment]
v6.0.0 too 😥

**Comment by BenjaminHoegh** [comment]
Why are they not fixing this issue!

**Comment by inweid** [comment]
@BenjaminHoegh I think because it is not the highest priority

**Comment by zcbenz** [comment]
This problem should have been fixed at least for Electron >= 9.
