### ISSUE TITLE
German documentation seems to be broken in chrome

### ISSUE THREAD

**Issue by MareikeTaeubner** [electron/electron#12812]
* Electron version: 2.x
* Operating system: Windows 10, Chrome Version 66.0.3359.139 (Offizieller Build) (64-Bit)

* Last known working Electron version: 1.8.x

### Expected behavior

The documentation looks like the english one.

### Actual behavior

The documentation is broken on some pages (for example webContents) - see screenshots.

### How to reproduce

Opening  the [english documentation](https://github.com/electron/i18n/blob/master/content/en-US/docs/api/web-contents.md) in Chrome -> looks fine.

Opening the [german documentation](https://github.com/electron/i18n/blob/master/content/de-DE/docs/api/web-contents.md) in Chrome -> the text gets very small at some point and it does not look like proper interpreted markdown anymore.

Screenshot from https://electronjs.org/docs/api/web-contents:

![brokendoku](https://user-images.githubusercontent.com/4388257/39575678-b6df625c-4edb-11e8-926c-894487740202.jpg)

Screenshot from https://github.com/electron/i18n/blob/master/content/de-DE/docs/api/web-contents.md:

![brokendoku2](https://user-images.githubusercontent.com/4388257/39575685-b936310c-4edb-11e8-92a6-fa339c3016e8.JPG)

**Comment by codebytere** [comment]
Hey! thanks for reaching out, but the place to open this issue is on the website repo [here](https://github.com/electron/electronjs.org). Good luck!
