### ISSUE TITLE
[2.0] Type information docs/api/touch-bar.md is incorrect

### ISSUE THREAD

**Issue by stephanwlee** [electron/electron#12823]
Hi Electron,

I tried to fix it and raise a PR but I could not easily find a way to convey subclass with electron-docs in Markdown.

Specifically, https://github.com/electron/electron/blob/master/docs/api/touch-bar.md#touchbarescapeitem is defined to be returning `TouchBarItem` but it is not well defined in any Markdown.

### Expected behavior
Expect electron-api.json to return correct type information for `get TouchBar.prototype.escapeItem`. Correct type would be (subclass of TouchBarItem | null) or `([TouchBarButton](touch-bar-button.md) | [TouchBarColorPicker](touch-bar-color-picker.md) | [TouchBarGroup](touch-bar-group.md) | [TouchBarLabel](touch-bar-label.md) | [TouchBarPopover](touch-bar-popover.md) | [TouchBarScrubber](touch-bar-scrubber.md) | [TouchBarSegmentedControl](touch-bar-segmented-control.md) | [TouchBarSlider](touch-bar-slider.md) | [TouchBarSpacer](touch-bar-spacer.md) | null)`

### Actual behavior
This is current electron-api.json
```
"instanceName": "touchBar",
"instanceProperties": [
  {
    "name": "escapeItem",
    "description": "A TouchBarItem that will replace the \"esc\" button on the touch bar when set. Setting to null restores the default \"esc\" button. Changing this value immediately updates the escape item in the touch bar.",
    "type": "TouchBarItem",
    "collection": false
  }
]
```
`TouchBarItem` does not resolve to anything.

**Comment by stephanwlee** [comment]
Preferably, I think `npm run lint-docs should fail when a type does not resolve to anything.

**Comment by stephanwlee** [comment]
Hi Samuel, I tried hard coding it but I couldn't figure out proper syntax for returning union types :(. I guess I am too green to this electron-docs thing

**Comment by MarshallOfSound** [comment]
@stephanwlee The subclass recognition is implemented in our `electron-typescript-definitions` module.  If you look at the types we have generated for `electron@2.0.5` the `escapeItem` property is correctly typed.

https://unpkg.com/electron@2.0.5/electron.d.ts
