### ISSUE TITLE
TouchBar Popover add support for onEnter and onExit callbacks

### ISSUE THREAD

**Issue by ProLoser** [electron/electron#12838]
On OSX, it would be nice if there was an additional set of options for touchbar popovers that allowed me to execute arbitrary logic upon entering or exiting a popover.

I would like to show something on screen when I enter a popover and then hide the relevant content when exiting the popover.

### `new TouchBarPopover(options)`

* `options` Object
  * `label` String (optional) - Popover button text.
  * `icon` [NativeImage](native-image.md) (optional) - Popover button icon.
  * `items` [TouchBar](touch-bar.md) (optional) - Items to display in the popover.
  * `showCloseButton` Boolean (optional) - `true` to display a close button
    on the left of the popover, `false` to not show it. Default is `true`.
  * `onEnter` Function (optional) - Called when the popover is opened
  * `onExit` Function (optional) - Called when the popover is closed

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
