### ISSUE TITLE
Webviews not being completely removed?

### ISSUE THREAD

**Issue by AlansCodeLog** [electron/electron#12834]
* Electron version:
v2.0.0
* Operating system:
Windows 10 64bit
* Last known working Electron version: 
Unknown
### Expected behavior
In the dev tool's timeline, the listener/node count (and the JS Heap size?) should go back down when webviews are removed. They should not show up in Detached DOM tree when taking a heap snapshot. It's as if they never existed.

### Actual behavior
If you don't add a preload script the memory consumption eventually goes back down, but if you do, it doesn't, even with manual garbage collection. Also regardless, the number of nodes and listeners just keeps increasing. If I take a heap snapshot I can see all the elements are under Detached DOM trees in Containment. 

I thought maybe I was closing the webviews incorrectly, but there's isn't any documentation on this, except for the close event example which seemed to imply one should set the src to `about:blank` on close. So I tried just setting it to `about:blank` from the start and this allowed the memory to drop back down with the preload script (but listener/node count still increases). Is this intended behavior?

### How to reproduce
```
  $ git clone https://github.com/AlansCodeLog/electron-quick-start.git -b webview-problem
  $ npm install
  $ npm start || electron .
```
Start recording a timeline in the dev tools, click `Add 10` 2-3 times, then `Remove All`. Manually garbage collect. Stop recording.

**Comment by bpasero** [comment]
Related/duplicate: https://github.com/electron/electron/issues/13243

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
