### ISSUE TITLE
the Tray miss after severval seconds

### ISSUE THREAD

**Issue by aFlappyPig** [electron/electron#12842]
* Electron version: 2.0.0
* Operating system: Windows 7 Ultimate

* Last known working Electron version: 

### Expected behavior
the Tray icon is always there

### Actual behavior
the Tray miss after several seconds but the application still alive, I do nothing

### How to reproduce
I can reproduce this 100%

this is the code:

 let tray = new Tray("./icon-16.png");
  const contextMenu = Menu.buildFromTemplate([
    {
      label: "检查更新",
      type: "normal",
      click: () => {
        dialog.showMessageBox({
          type: "none",
          title: "更新",
          message: "暂无更新"
        });
      }
    },
    {
      label: "重新登录",
      type: "normal",
      click: () => {}
    },
    {
      label: "退出",
      type: "normal",
      role: "quit"
    }
  ]);
  tray.setToolTip("Hi");
  tray.setContextMenu(contextMenu);

**Comment by MarshallOfSound** [comment]
Your tray icon is being garbage collected, please ensure you maintain a globabl / scoped reference to the `tray` object

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by aFlappyPig** [comment]
@MarshallOfSound thank you very much
