### ISSUE TITLE
Small transparent window is broken with 2.0.0

### ISSUE THREAD

**Issue by clusterberries** [electron/electron#12845]
* Electron version: 2.0.0
* Operating system: Windows 10
* Last known working Electron version: 1.8.6

### Expected behavior

Ready-to-show event should be fired and window is shown.

### Actual behavior

Ready-to-show event is not fired, the window cannot be shown.

### How to reproduce

Create a BrowserWindow with such parameters:
```
win = new BrowserWindow({
        width: 200,
        height: 40,
        show: false,
        resizable: false,
        x: 300,
        y: 300,
        alwaysOnTop: true,
        frame: false,
        transparent: true
});
```
It works with 1.8.6, but is broken with 2.0.0.
You can find example here https://github.com/clusterberries/electron-sample/tree/test-window
Clone the repo, run `npm i` and `npm start`. Nothing is displayed with 2.0.0. It should look like this with 1.8.6

![image](https://user-images.githubusercontent.com/9727404/39700208-12d52516-5205-11e8-9348-b5a3dc1ac39b.png)

**Workaround**: if you set `resizable` to true, or `transparent` to false, or increase `height` value, the window is displayed.
It seems to work fine with Mac, but I'm not 100% sure. I can check if it is needed.

Thanks!

**Comment by meggamind** [comment]
@clusterberries 
I tried on mac, I had to set show to true to display on 1.8.6 and 2.0.0. 
Probably the flag was not working in 1.8.6 on windows and now works in 2.0.0. 
Can you set show to true and check.

**Comment by meggamind** [comment]
@clusterberries @sofianguy tested it on windows with show: true, works on both 1.8.6 and 2.0.0

**Comment by clusterberries** [comment]
Hi @meggamind ! Did you test the example from https://github.com/clusterberries/electron-sample/tree/test-window? Here I call `win.show();` when `ready-to-show` event is fired, as recommended in Electron documentation.
If I set show=true, then the window is still not displayed and 'ready-to-show' event is not fired.
What OS do you use? I have Windows 10, I didn't test on Windows 7.

**Comment by clusterberries** [comment]
The issue is not reproduced with Electron 2.0.2.
