### ISSUE TITLE
No getProducts() and finishTransactionByDate() in inAppPurchase

### ISSUE THREAD

**Issue by immanoj16** [electron/electron#12846]
Hey I am using the latest version of electron: `2.0.0` and Ubuntu: `18.04`

As per the [documentation](https://electronjs.org/docs/tutorial/in-app-purchases), the `inAppPurchase` has `finishTransactionByDate()` and `getProducts()` method. But there are no such methods in `inAppPurchase`.

But in this api [documentation](https://electronjs.org/docs/api/in-app-purchase), there are no such methods `finishTransactionByDate()` and `getProducts()` mentioned.

Should this methods show in Mac only or any platform??

Kindly correct me, if I am wrong.

**Comment by MarshallOfSound** [comment]
`inAppPurchase` is a macOS only API

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by immanoj16** [comment]
Thank you

**Comment by thomasdao** [comment]
@MarshallOfSound I use Mac but `getProducts` and `finishTransactionByDate` method is also not available. I use latest 2.0.0 version. Below is the screenshot
<img width="467" alt="screen shot 2018-05-12 at 06 20 23" src="https://user-images.githubusercontent.com/863218/39950765-f9d06402-55ad-11e8-9007-32a43170a819.png">

**Comment by immanoj16** [comment]
Hey @thomasdao you can create a separate issue because this issue was closed so they won't see it. So create a separate issue.

**Comment by thomasdao** [comment]
Thanks @immanoj16. I have posted a new issue #12908
