### ISSUE TITLE
time consuming evaluate script spawnSync before firstLoad/reload

### ISSUE THREAD

**Issue by Anadi7** [electron/electron#12859]
* Operating System (Platform and Version): macOS High Sierra 10.13.4

**Actual behavior**
It seems cost more time in electron2.0.0 than electron1.8.6
I want to know why my item execute this script and how to fix it.

**Screenshots*
<img width="664" alt="2018-05-08 4 13 00" src="https://user-images.githubusercontent.com/30398675/39745969-83af09e2-52db-11e8-8965-b8bb8455b676.png">

<img width="1913" alt="2018-05-08 4 13 59" src="https://user-images.githubusercontent.com/30398675/39745977-8c617ab6-52db-11e8-87d6-ced429956c6d.png">

<img width="1764" alt="2018-05-08 4 20 54" src="https://user-images.githubusercontent.com/30398675/39746074-dd935378-52db-11e8-9733-92d6b49924f6.png">

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
