### ISSUE TITLE
Parcel webapp with custom protocol crashes renderer

### ISSUE THREAD

**Issue by mhuggins** [electron/electron#12855]
* Electron Version: 1.8.x and 2.0.0
* Operating System (Platform and Version): macOS High Sierra (10.13.3)
* Last known working Electron version: N/A

**Expected Behavior**
Loading a Parcel webapp with a custom protocol in an Electron renderer displays the webapp.

**Actual behavior**
Loading a Parcel webapp with a custom protocol in an Electron renderer crashes the renderer.

**To Reproduce**
*Commands to clone/setup/run [reproduction repo](https://github.com/nos/electron-parcel-custom-protocol):*
```sh
$ git clone git@github.com:nos/electron-parcel-custom-protocol.git
$ cd electron-parcel-custom-protocol
$ yarn && yarn start
```

*Steps to reproduce:*
1. Use `protocol.registerStandardSchemes` to register a custom schema.
1. Use `protocol.registerHttpProtocol` to register a simple protocol handler that rewrites the `request.url` to use "http".
1. Create a [Parcel webapp](https://parceljs.org/) (Webpack alternative) that includes a `<script>` tag for loading JS built by Parcel (relative path).
1. Open the Parcel webapp in electron renderer (e.g.: `custom://localhost:1234`).
1. Observer renderer crash when it tries to load Parcel `<script>` tag.

**Screenshots**
<img width="912" alt="Parcel webapp with custom protocol crashing Electron renderer" src="https://user-images.githubusercontent.com/169093/39737907-a4c9018e-524d-11e8-812d-af840363943c.png">

**Additional Information**
* This only happens when the `<script>` tag is included.  Commenting/removing the tag from the HTML makes the problem go away.  It seems to be some issue in the generated JS, or somewhere between the JS and the Electron renderer.
* This only happens when using a custom protocol.  It does not happen when using the "http" protocol.
* This only happens when using `parcel`, not `parcel build`.  The production build seems to be okay, so it's specifically an issue with the development build.

**Comment by mhuggins** [comment]
I dug a little bit more, and this only happens when using `parcel`, not `parcel build`.  The production build seems to be okay, so it's specifically an issue with the development build.

**Comment by mhuggins** [comment]
@MarshallOfSound I think you're right.  If I run parcel with the `--no-hmr` flag, then the renderer does not crash.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
