### ISSUE TITLE
Electron 2.0 won't load localhost and crashes

### ISSUE THREAD

**Issue by AhadCove** [electron/electron#12853]
* Electron Version: 2.0.0
* Operating System (Platform and Version): Mac
* Last known working Electron version: 1.8.6

**Expected Behavior**
To simply load a basic React app running on localhost

**Actual behavior**
Has there been a change with loading localhost from 1.8.4 to 2.0?
I just created a new electron app trying to run a basic react app and for some reason, it won’t load. There aren’t even any error messages. When I load it through a previous Electron app using 1.8.6 it works perfectly

I also tested loading actual sites (https) and basic html with 2.0 and it works without any problem. It’s only my localhost that I can’t connect to.
It also crashes and won’t close at all unless I force close it. 
I'm also setting webSecurity to false as well.

**To Reproduce**
Create a basic react app run it on a port and attempt to fire it up with electron

**Comment by AhadCove** [comment]
False call, I see what’s going on

So, I have a boilerplate for my electron-react apps and the first thing my React app does is call the store from IPC. My Boiler for the main electron file didn’t have a listener for that call, so the app froze waiting for a response from the Main process
This call was, of course, a sendSync :disappointed:
Pretty dangerous if you forget something.

This is why my previous app worked because it did have that listener

**Comment by ckerr** [comment]
@AhadCove, thanks for the follow-up :+1:
