### ISSUE TITLE
Must write scripts as a closure function for content scripts of Chrome Extension

### ISSUE THREAD

**Issue by Yukimir** [electron/electron#12865]
In electron, the script would be put in an arrow function to get 'chrome' object.
If you have a script with a function called fn1, you must assign it to 'this' object (in electron it point to global) that you can use fn1 in other script.

But in chrome you don't need to do these thing.

So some chrome extensions cannot be used in electron directly.

Any one have good idea to solve this problem?

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
