### ISSUE TITLE
renderer devtools debugger is not functional when stopped by a debugger statement in the preload script

### ISSUE THREAD

**Issue by bughit** [electron/electron#12863]
* Electron Version: recent master (82329124ffcb2012d101c79236e82fbe6ba79c36) x86 & x64
* Operating System (Platform and Version): win7 sp1 x64
* Last known working Electron version: 2.0.0

**Expected Behavior**
should be able to break in the preload script via the debugger statement

**Actual behavior**
debugger breaks but is not functional, the preload script is blank, the sources for all other frames are blank, can't eval anything in the console.  It does not recover if you continue it.

**To Reproduce**

test_app.js
```js
'use strict';

const {app, BrowserWindow} = require('electron'),
      path = require('path');

let brWin;

app.on('ready', () => {
  brWin = new BrowserWindow({
    width: 1366,
    height: 768,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      preload: path.join(__dirname, 'preload.js'),
    },
  });
  
  for (const eventName of ['did-start-loading', 'did-stop-loading', 'crashed'])
    brWin.webContents.on(eventName, () => console.log(eventName));

  brWin.loadURL(process.argv[2] || 'about:blank');
  brWin.webContents.openDevTools({mode: 'right'});

});

app.on('window-all-closed', () => app.exit());
```

preload.js
```js
'use strict';

debugger;
```

- run `electron test_app.js`
- in devtools console enter: `location = "about:blank"`
- it breaks but is not functional

**Screenshots**

good: electron 2.0.0
![image](https://user-images.githubusercontent.com/895588/39769969-b5d89e58-52bb-11e8-88a8-607d71335c1a.png)

bad: master
![image](https://user-images.githubusercontent.com/895588/39769997-ca9936cc-52bb-11e8-9afe-5c19749b9b05.png)

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR.
