### ISSUE TITLE
Closes child window if parent window navigates

### ISSUE THREAD

**Issue by eyyubovkamran** [electron/electron#12868]
* Electron Version: 1.8.4
* Operating System (Platform and Version): Windows 10
* Last known working Electron version: -

**Expected Behavior**
When you click on any link on page, it should open a new BrowserWindow and navigate the parent window to the new url.

**Actual behavior**
Opens a new BrowserWindow, but closes it when parent window navigates to the new url.

**To Reproduce**
Clone the repository, npm install, npm run, and click on any link

```sh
$ git clone https://github.com/eyyubovkamran/electron-popup-window-bug
$ npm install
$ npm start
```

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by pushkin-** [comment]
Still an issue in Electron 4.0.3

**Comment by wslx520** [comment]
Still an issue in Electron 3.0.9 @sofianguy

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
