### ISSUE TITLE
Allow user interface tooltip delay to be configurable

### ISSUE THREAD

**Issue by monkeyhybrid** [electron/electron#12861]
I previously requested this feature for Visual Studio Code (see https://github.com/Microsoft/vscode/issues/49047) but it was labelled as being more applicable to Electron. I hope I'm not breaking etiquette by requesting it here too.

When hovering over user interface elements, the associated tooltip takes approximately 1 second to display (at least in the Electron apps I have used, Visual Studio Code and Signal). This can be annoyingly sluggish whilst first learning user interfaces. As the ideal delay is subjective, it would be nice to be able to control this value in the app's settings. If I understand correctly, this may require the value being configurable in Electron in the first place.

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR.
