### ISSUE TITLE
app.moveToApplicationsFolder() fails unexpectedly when running in a disk image

### ISSUE THREAD

**Issue by javan** [electron/electron#12869]
* Electron Version: 2.0.0
* Operating System: macOS 10.13.4

**Expected Behavior**
Calling `app.moveToApplicationsFolder()` when an application is launched from a disk image (.dmg) should move the application from the disk image to the Applications folder.

**Actual behavior**
* Finder alerts *The item can't be moved to the Trash because it can't be deleted.*
* The application stops responding and must be force quit
* The application is partially (?) moved to Applications, but internally its paths still reference the disk image (e.g. `/private/var/folders/52/zh03bcd5tx…/…/…/…/…/Contents/Resources/app.asar`)

See video: https://cl.ly/2i0u131q0D1a

**Additional Information**
* `app.moveToApplicationsFolder()` works as expected when the app isn't in a disk image (and not in the Applications folder).
* I tried `try / catch`ing the invocation and logging any errors with no success. There's either no error or the application becomes unresponsive before reaching the `catch` branch.
* Here's the after-force-quit crash dump log: https://gist.github.com/javan/50208efe1bfa738d09605b0c980a557e

**Comment by javan** [comment]
My implementation is basically just:
```js
if (!app.isInApplicationsFolder()) {
  const button = dialog.showMessageBox(…)
  if (button == 0) {
    app.moveToApplicationsFolder()
  }
}
```

**Comment by javan** [comment]
@MarshallOfSound, I see some disk image conditions in https://github.com/electron/electron/pull/10142. Perhaps they're not quite right?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Closing this issue as this is not something we can fix, according to the comment above.
