### ISSUE TITLE
navigator.mediaDevices.getUserMedia produces a blank image on Windows

### ISSUE THREAD

**Issue by Lemos97** [electron/electron#12876]
* Electron Version: 1.6.17 / 1.7.14 / 1.8.2 / 2.0.0
* Operating System (Platform and Version): Windows 7 / Windows 10 Version 1703 (Build 15063.1029) / Windows 10 Version 1709 (Build 16299.371)
* Last known working Electron version: None

**Expected Behavior**
`navigator.mediaDevices.getUserMedia({ video: true })` results in a mediaStream that has an image and can be passed to a `<video>` element via `srcObject` or via `URL.createObjectURL`. When a canvas element is used to retrieve a single frame from the video as a JPEG image, the resulting image contains the image on the frame at that timestamp and can be placed on an `<img />` element.

**Actual behavior**
The resulting mediaStream, when passed to a video element, results in that video element having a blank image(transparent). If a canvas element is used to save a frame as a JPEG picture, the resulting picture is completely black.

No error or reject promise occurs on the use cases that it doesn't work. If other apps are using the camera, this code throws an error because the camera's already being used (as expected).

If the camera's being used by this example, even when no output is shown, the camera is unavailable to other devices (as expected), meaning that the camera's being accessed.

**To Reproduce**
The following repository has an example, with evidence: [REPOSITORY](https://github.com/Lemos97/electron-quick-start)

The code uses `navigator.mediaDevices.getUserMedia({ video: true })` to get the stream, and passes it to a `<video />` element when the stream is available.

A button has been added that takes a frame from the stream, and saves it on a canvas element and on an image element (via the blob produced by `canvas.toBlob()`.

A label shows whether the `getUserMedia` operation succeeded or failed.

For debugging purposes, a 1px solid black border has been added to the video and canvas elements, but this has no effect on the outcome of `getUserMedia`.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone https://github.com/Lemos97/electron-quick-start -b master
$ npm install
$ npm start
```
**Screenshots**
Working example (on Windows 10 version 1709 build 16299.371): 
![working-example](https://user-images.githubusercontent.com/20013428/39877686-7a4b51aa-546e-11e8-974f-2d0d8c0cb16b.png)

Not working example (on Windows 10 version 1703 build 15063.1029):
![not-working-example](https://user-images.githubusercontent.com/20013428/39877698-80778b34-546e-11e8-9ffc-9f9e0dc65d97.png)

Same code, running on Chrome (on Windows 10 version 1703 build 15063.1029):
![chrome-example](https://user-images.githubusercontent.com/20013428/39878050-4ec1fd80-546f-11e8-9ef5-37db058f2a65.png)

**Additional Information**
This was also tested on a Laptop running Windows 7. All 3 laptops produce the expected result when the code is run on Chrome. Only the laptop running version 1709 runs the Electron code correctly.

All evidence has been taken on Electron 2.0.0, but the result is the same on older versions.

**Comment by RedRoserade** [comment]
I've been looking at the Chromium bug tracker, and I found this: [https://bugs.chromium.org/p/chromium/issues/detail?id=722038](https://bugs.chromium.org/p/chromium/issues/detail?id=722038). Could it be related?

**Comment by Lemos97** [comment]
Just tested with the electron@3.0.0-beta and this problem persists.

**Comment by Lemos97** [comment]
The issue was being caused by Kaspersky Endpoint Security for Windows 11, it seems that its disabling the access to applications that's are not in a whitelist.
