### ISSUE TITLE
Creating new DOM File object from path?

### ISSUE THREAD

**Issue by ediweissmann** [electron/electron#12871]
* Electron Version: 1.4.13
* Operating System (Platform and Version): All
* Last known working Electron version: N/A

**Expected Behavior**
`new File(filepath)`?

I have a path to a file and I'd like to create a new DOM File object for the corresponding path.

Use-case: instead of having the user browse for a file, I'd like to instantiate it directly from the path I already have (user right clicked on a file, chose open with my app)

**Actual behavior**
I'm unable to instantiate a DOM File object based on a path. Is this possible?

**Comment by MarshallOfSound** [comment]
I can't find the issue at the moment (github search has failed me) but this request has been rejected before because there is no use case for this API that the `fs` api that node.js exposes can't do.  If anything the `fs` API is way more powerful and you actually fake a `File` object using the `fs` API.

A `File` object is actually just a `Blob` with a `name` attribute, you can read a file in as a `Buffer` using `fs.readFile` and then convert the buffer to a blob (their are modules / stackoverflow answers on how to do this.  Give it a name attribute and pass it around 👍

**Comment by asadmalik3** [comment]
@MarshallOfSound Can you share any sample of what you have just said? Converting buffer to blob in node js seems like a difficult task to me.

**Comment by viridia** [comment]
One reason for wanting this is to be able to consistently handle file i/o from both drag-and-drop and the native file open dialog.

Typically a drag and drop event would be handled by the renderer process using the HTML drop event, which results in a File object. Now suppose you also want to support opening files via the native file dialog. It would be convenient to use the same deserialization logic for both cases. Being able to generate a File object in the main process and then send it via IPC to the renderer process would allow this.

**Comment by marcelblum** [comment]
This worked great for me: https://github.com/abrwn/get-file-object-from-local-path

My use case is that I wanted to use an existing library that processed local files in the browser but it expected and required the capabilities of the File object, and it seemed silly to try and reinvent the wheel or rewrite significant portions of the existing library that already had most of the functionality I needed.

**Comment by asadmalik3** [comment]
@marcelblum This library that you mentioned has a serious limitation as it loads whole file into memory.

**Comment by marcelblum** [comment]
@asadmalik3 very true, it can have calamitous results with big files. I actually ended up making a fork with an option to only read part of the file https://github.com/marcelblum/get-file-object-from-local-path. In my case I just needed to analyze some file headers so loading the first 500 bytes was all I needed.

**Comment by anuejn** [comment]
@MarshallOfSound as alluded to earlier in this thread, the method you outlined loads the complete file into memory, while creating a `File` object directly creates a `Blob` that points to data on disk (afaik?).

Please reconsider implementing the functionality requested in this issue.

**Comment by xiaocairush** [comment]
I want to createObjectUrl for video playing from file path. And the video may be large than 2GB, seems it's not a good idea to load the entire video file into memory. Is there any better implemention for my case?
