### ISSUE TITLE
BrowserWindow process name

### ISSUE THREAD

**Issue by tomavitan** [electron/electron#12874]
When having a multi windowed app, they all get the same process name (at least on Windows). 
Is there a way to configure it differently? Could not find a resolution.
Many thanks.

**Comment by MarshallOfSound** [comment]
The process name is the name of the executable `electron.exe` you can rename this yourself without any ill affects

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
