### ISSUE TITLE
require('electron').remote undefined

### ISSUE THREAD

**Issue by jefferybai** [electron/electron#12889]
* Electron Version: v 2.0.0
* Operating System (Platform and Version): mac os,  webpack, npm, vscode
* Last known working Electron version: v 2.0.0

**Actual behavior**
A clear and concise description of what actually happened.

npm install electron

console.log(require('electron').remote) 
//undefined

console.log(require.resolve('electron')) ////Users/baizhihui/Documents/job/Classflow_WEB/node_modules/_electron@2.0.0@electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/exports/electron.js

I found a solution on the official website.
But after running the following code.

npm uninstall electron
  npm uninstall -g electron

 Cannot find electron module

**Comment by sethlu** [comment]
@jefferybai Did you run `console.log(require('electron').remote)` in the renderer process or in the main process?

**Comment by sethlu** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
