### ISSUE TITLE
`Notification::close` only removes last notification from macOS Notification Center

### ISSUE THREAD

**Issue by gasi** [electron/electron#12880]
* Electron Version: 1.8.4
* Operating System (Platform and Version): macOS 10.12.6
* Last known working Electron version: n/a

**Expected Behavior**
Calling `Notification::close` removes notification from macOS Notification Center.

**Actual behavior**
Calling `Notification::close` only removes *last* notification from macOS Notification Center. Previous notifications remain.

**To Reproduce**

Run the following in an Electron instance developer tools console:

```javascript
counter = 0;
notification = new Notification('notification: ' + counter++); setTimeout(() => notification.close(), counter * 1000);
notification = new Notification('notification: ' + counter++); setTimeout(() => notification.close(), counter * 1000);
notification = new Notification('notification: ' + counter++); setTimeout(() => notification.close(), counter * 1000);
```

**Screenshots**

This screenshot shows the macOS Notification Center after creating three notifications and closing all three. However, two remain despite calling `Notification::close` on them:

<img width="339" alt="notificationcenter_and_appleuser_and_appleclockextra_and_siri" src="https://user-images.githubusercontent.com/49583/39890139-e5ecdd86-5467-11e8-8ae6-ec42720e70c6.png">

**Comment by MarshallOfSound** [comment]
Your code appears to be the cause of this issue, you are overriding the `notification` value which means you only close the last one you make.  Call them notification1, notification2 and notification3 and everything will work fine.  (I tested this locally)

**Comment by gasi** [comment]
@MarshallOfSound D’oh! I just got back to this realizing this might have been the problem and was hoping the issue hasn’t been investigated yet — sorry for wasting your time.

The original setup was slightly different and I even tried binding the variable using an IIFE to prevent this problem but it looks like I have to revisit this. Apologies for the false alarm and have a good day 😄
