### ISSUE TITLE
Custom headers for DownloadItem (e.g. Authorization)

### ISSUE THREAD

**Issue by ericpyle** [electron/electron#12883]
**Is your feature request related to a problem? Please describe.**
Download Manager/DownloadItem api does not work for webRequests that require custom headers (e.g. Authorization headers with JWT token).

**Describe the solution you'd like**
Make a per-webRequest way to pass custom headers (e.g. Authorization) through the Download Manager / DownloadItem api.

For example, extend `WebContents::DownloadURL` to allow the passing of custom headers. It currently only supports passing 'url':

`electron/atom/browser/api/atom_api_web_contents.cc`  `Line 1061 in cc9771a`
```
 void WebContents::DownloadURL(const GURL& url) { 
```

**Describe alternatives you've considered**
The only workaround I am aware of is to filter/listen for
`webRequest.onBeforeSendHeaders([filter, ]listener)`
And modify `details.requestHeaders`.  But that's a hack.

**Additional context**
Needed for download manager dependent modules like https://github.com/sindresorhus/electron-dl/issues/33
See also https://github.com/electron/electron/issues/10582 which may have been closed prematurely.

**Comment by dengyaolong** [comment]
may be we need `webContents.DownloadURL(url, options)`,  like `browserWindow.loadUrl ` https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winloadurlurl-options

**Comment by navidsedighpour** [comment]
I also have this kind of problem. I need to download a url which needs authorization header and save it in OS. Anyone found the solution?

**Comment by d4kris** [comment]
We also have a problem with authorization headers that are not set on session.downloadUrl eventhough we set them in session.webRequest.onBeforeSendHeaders. 
Is there a reason why they are not set?
If so, an options parameter to downloadUrl, where we could set them again would be a good solution I think.

**Comment by macrouch** [comment]
An options parameter where we can pass headers is very necessary for us
