### ISSUE TITLE
Electron Decompile

### ISSUE THREAD

**Issue by greysonn** [electron/electron#12897]
Hey, I recently had a freelancer write me a program in electronjs, but he sent over a folder with an exe in it, not the actual source. Is there any way i can decompile the app.asar file to where the obfuscated javascript isn't obfuscated?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
