### ISSUE TITLE
Unable to send 'keydown' event to an <input> element inside an Electron browser window

### ISSUE THREAD

**Issue by berkon** [electron/electron#12891]
* Electron Version: 1.7.9 (same behavior with 2.0.0)
* Operating System (Platform and Version): Windows 7
* Last known working Electron version:  not tried with other versions

**Expected Behavior**
Creating an artificial `'keydown'` event with `document.createEvent()` and dispatching it via `executeJavaScript()` inside a page previously loaded with `loadURL`, should show the artificial key which was pressed, e.g. in an `<input>` element, to which the event was dispatched to.

**Actual behavior**
No character is shown in the <input> element. The event is definitely dispatched correctly, because when attaching a listener to that <input> element it is triggered with the correct event data.

**To Reproduce**

**index.js**
```
const {app, BrowserWindow} = require('electron');

app.once ( 'ready', () => {  
    win = new BrowserWindow ({ width: 1220, height: 500 });
    win.loadURL ( `file://${__dirname}/index.html` );
    win.webContents.once ( 'did-finish-load', () => {
        setTimeout ( () => {
            win.webContents.executeJavaScript(`
                var inp = document.querySelector('input');
                inp.focus();

                var ev = document.createEvent("Events");
                ev.initEvent("keydown", true, true);
                ev.key = "1";
                ev.which = 49; 
                ev.keyCode = 49;
                ev.view = document.defaultView;
                document.querySelector('input').dispatchEvent( ev );
            `);
        },2000 );
    });
});
```

**index.html**
```
<html>
    <body>
        <input/>
    </body>
</html>
```

**Additional Information**
Using sendInputEvent() with type 'char' interestingly works correct:
```
win.webContents.sendInputEvent({
    type: 'char',
    keyCode: "1"
});
```
but this works just as little:
```
win.webContents.sendInputEvent({
    type: 'keyDown',
    keyCode: "1"
});
win.webContents.sendInputEvent({
    type: 'keyUp',
    keyCode: "1"
});
```

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
