### ISSUE TITLE
Very slow startup time on Windows 7 64 bit for electron version 2.0.0

### ISSUE THREAD

**Issue by dough654** [electron/electron#12895]
* Electron Version: 2.0.0
* Operating System (Platform and Version): Windows 7 Enterprise 64 bit
* Last known working Electron version: 1.8.6

I'm currently running windows 7 and tried to upgrade an electron app to version 2.0.0. It now takes ~1 minute for the application to finish loading before it becomes responsive. The same application running on electron 1.8.6 opens in ~1 second. I've replicated this with the base demo app as well.

I'm currently running node version 8.9.1 on the machine under node version manager. 

I am starting the application using the following NPM command:

`"start": ".\\node_modules\\electron\\dist\\electron.exe main.js --enable-logging",`

The same behavior happens after packaging as well using electron-packager

I will continue to use 1.8.6 for now. Just wanted to bring this to your attention.

**Comment by bpasero** [comment]
@dough654 is this windows running in a VM? Is this a single-CPU environment?

**Comment by baconbrad** [comment]
I cannot replicate this. We have Electron 2.0.0 running in production in our company. We have quite a few Windows 7 machines running in our network and none of them are having this issue.

Do you have the same results with a fresh project?

**Comment by bpasero** [comment]
@dough654 VSCode has a wiki to diagnose slow startup issues: https://github.com/Microsoft/vscode/wiki/Performance-Issues

**Comment by dough654** [comment]
Thanks, I'll give that a shot. Although it's pretty clear that the combination of 2.X version of electron and something in our environment is causing the issue, since we never had performance problems before with VSCode or any custom electron apps using 1.X versions. 

Hopefully VSCode's diagnostics might shed some light. I'll respond back later with any results we find.

**Comment by dough654** [comment]
So I did the diagnostics you recommended with VSCode, and this is what I got.

![vscode-startup-slow](https://user-images.githubusercontent.com/20626718/44343064-e58c7700-a45a-11e8-8882-920f3e455008.PNG)

After that, I created a new app using electron-quick-start, and I tried commenting out the `mainWindow.loadFile('index.html')` line to see if it was maybe a chrome rendering thing, but it did not help. I then put a console.log message at the top of the main.js file and sure enough it still takes about 20 seconds before the log message shows up.

Whatever our problem is, it appears to be related to something in the electron.exe (happens before the node code gets initiated). I took a look in the task manager as I ran 'npm start', and I've noticed that the initial electron.exe gets spawned pretty much right away. But the second electron.exe process takes the 20 seconds to show up.

We've tried disabling our AV product, with no avail. I'm planning on testing on a windows 10 build soon to see if the issue persists there or not.

Any guidance or suggestions would be appreciated as we continue to troubleshoot.

**Comment by bpasero** [comment]
@dough654 you could try to measure how long it takes until you get the `app.on("ready")` event. We have seen in the past that quite a bit of time can be spent until the app is even getting a signal to start building things.

**Comment by dough654** [comment]
Thanks for the suggestion, but it still takes about 20+ seconds. I put a console.log statement at the very top of the main.js before and that also takes 20+seconds. So clearly the main.js is not even being interpreted until that point. Once the main.js does get initiated though, it takes another 20 or so seconds for the BrowserWindow to finish opening. Once it finishes opening, the render of the html file is instant. Maybe it's having trouble spawning new processes?

It's got to be something in electron.exe that's changed since previous versions that's now incompatible with our environment somehow. Maybe something in libuv?

**Comment by jrieken** [comment]
btw - #56644 shows that folks with Windows 10 see this too, so it's not just Windows 7

**Comment by deepak1556** [comment]
@dough654 can you provide the following details to eliminate some possible causes and further diagnose the issue.

* Do you see the issue when you run the app with `--no-proxy-resolver`
* If you have proxy auto detect settings can you try disabling it and run the app
* Can you provide the output of `--log-net-log` for the app, `app.exe --log-net-log=netlog.json`
* Do you have any problems with loading pages on the system with chrome 61.0.3163.79

**Comment by sofianguy** [comment]
@dough654 are you able to provide the information in the above comment?

**Comment by popfalushi** [comment]
btw: there are many logs in similar issue in VSCode bugtracker with all the logs: https://github.com/Microsoft/vscode/issues/56644

**Comment by popfalushi** [comment]
Does issue still requires more information to be solved or current info is sufficient? If more info is needed I'll be glad to provide - just tell me what.

**Comment by sxmpasch** [comment]
@deepak1556 : 
> Do you see the issue when you run the app with --no-proxy-resolver
YES
> If you have proxy auto detect settings can you try disabling it and run the app
DISABLED, PROBLEM STILL EXISTS

If I look at the procmon.exe output (sysinternals tool), electron.exe is creating 3 threads. Between Thread Create #3 and any other activity, there are EXACTLY 20 seconds. For me, this looks like a timeout (thread acknowledge / semaphore / whatever). The activities before / after this timeout seem to have something to do with Winsock.
Could you please look at what you changed recently between 2.x and 3.x versions in that area? Do you see a semaphore timeout of 20s somewhere?

**Comment by popfalushi** [comment]
@sxmpasch 
Actually, this is really nice idea. Searched repo, found one 20 sec timeout:
https://github.com/electron/electron/blob/6f91af93433df4e9c0e7fb592e5b2dcb0b1c7888/chromium_src/chrome/browser/chrome_process_finder_win.cc#L26

**Comment by sxmpasch** [comment]
@popfalushi 
I tried out the electron base from bpasero's comment [here](https://github.com/Microsoft/vscode/issues/56644#issuecomment-423053659). Without modifying main.js, I get the 20s timeout TWO times. One until the window opens, one until the index.html file is shown.
It looks like something is hanging until the function AttemptToNotifyRunningChrome() has returned.
So it seems we have to look at the call tree...

**Comment by deepak1556** [comment]
@sxmpasch @popfalushi thanks for the additional info, I believe you were able to verify this issue with base electron app, can you confirm if this is present with 3.0 stable and 4.0.0-nightly.20180929 versions ? I was unable to verify this issue on my machine, so couldn't get much into debugging. Anything particular with respect to the network environments or machine setup that I should be aware of ? Thanks!

**Comment by popfalushi** [comment]
@deepak1556 I don't know where I can download 4.x releases, so I didn't check this issue for it. I did check it for electron-v3.0.2-win32-x64 and it is present there.
About system: notebook Lenovo T460p, windows 10 x64 Pro, in corporate domain, domain user, no extra antivirus software, Forefront TMG Client firewall (disabled), nodejs v8.11.4 installed, Chrome v69 installed, no proxy, VPN does not affect the issue.

**Comment by maciejw** [comment]
@popfalushi on my two computers in corporate domain, laptop and workstation, both windows 10, I have the issue and the other people in my domain have the same thing, tens of people downgraded to vs code 1.25 with 1.7 version of electron. Maybe this is some kind of domain policy that causes this issue? we have also enterprise version of chrome installed, but on its own it works fine.

**Comment by sxmpasch** [comment]
@deepak1556 - I have tried 4.0.0-nightly.20181010 with the same test application as 3.0.
While 3.0 took about 40s to display a html test page as mentioned above, the nightly version came up almost instantly.
This means on my Notebook the problem is fixed with the nightly version!

**Comment by sxmpasch** [comment]
@deepak1556 - anything new on this? I wish I could help, but unfortunately, I don't get this to compile properly on my windows machine...

**Comment by deepak1556** [comment]
@sxmpasch nothing new on my end.

>  don't get this to compile properly on my windows machine

What issue are you facing ?

**Comment by sxmpasch** [comment]
@deepak1556  - My Notebook is behind a proxy with username/password. When I tried last time, it got stuck somewhere with many errors/warnings. I have retried this today, he now is looking for gn.exe without being able to download anything...

**Comment by janscas** [comment]
Same problem here, but on windows 8.1. I'm also behind a corporate proxy. I think that's the issue, because same electron version at home (without a proxy) starts instantly.

**Comment by nattajame27** [comment]
remove CDN in index.html :)

**Comment by cboillat** [comment]
> Same problem here, but on windows 8.1. I'm also behind a corporate proxy. I think that's the issue, because same electron version at home (without a proxy) starts instantly.
> 
> Tried installing version 4.0.0-beta9 and works instantly with proxy or not.

Yes same here, all my private computers are not affected. Only my professionnal one behind a proxy is.

**Comment by gidbrn** [comment]
> > Same problem here, but on windows 8.1. I'm also behind a corporate proxy. I think that's the issue, because same electron version at home (without a proxy) starts instantly.
> > Tried installing version 4.0.0-beta9 and works instantly with proxy or not.
> 
> Yes same here, all my private computers are not affected. Only my professionnal one behind a proxy is.

The problem occurs if you have a TMG Client (ISA Client). If you remove the TMG Client (instead of turning it off), the problem goes away.
(ATOM Editor + Windows 7 + TMG Client)

**Comment by cboillat** [comment]
@gidbrn tha's exactly the problem. I just uninstalled my TMG Client and everything is loading within a second !

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by deepak1556** [comment]
@sofianguy this is still reported to happen with `6-1-x` and higher, reopening to investigate further.

**Comment by tomocrafter** [comment]
It is still happening on me, with all of electron apps like Discord, VSCode, GitHub Desktop, Postman

**Comment by tomocrafter** [comment]
Is there any update about this issue? I still have this issue so far. I also tried windows safe-mode boot, disabling anti-virus, version electron 8.x.x demo app that can be launched with the command `electron`.
I would gladly like to help debugging by providing information so please ask me anything.
Or if you want to check my pc or actual behavior, then ask me for TeamViewer or something like that.
I'm done with this issue. Thank you.

**Comment by tomocrafter** [comment]
I fixed this problem by uninstalling badlion client. then all of electron apps launches within 1 sec.
Some people saying that in vscode issue. If you guys have this problem and have installed badlion client, then just uninstall it and restart the pc.
https://github.com/microsoft/vscode/issues/56644#issuecomment-600285015

**Comment by vicreinhart** [comment]
We have this problem also.  20 second wait time on Mac, 40 seconds on Windows 10 or 7.  We are using Electron 8.2.5 and we have a coporate proxy.

**Comment by dnudler** [comment]
Happened to me the same. I had a 404 to a non existing css that I forgot to remove. Turned out removing that solved the 25 sec delay... Maybe this can help someone?
