### ISSUE TITLE
Scrolling with backdrop-filter failure

### ISSUE THREAD

**Issue by iLeonidze** [electron/electron#12906]
* Electron Version: darwin 2.0.0, 1.8.3
* Operating System (Platform and Version): MacOS Hight Sierra 10.13.4 (17E202)
* Last known working Electron version: -

**Expected Behavior**
Normal contents rendering

**Actual behavior**
Body contents glitches

**To Reproduce**
I had created a simple app to reproduce bug, see:

process.js
```
var electron = require('electron');
var app = electron.app;
var BrowserWindow = electron.BrowserWindow;

var path = require('path');
var url = require('url');

var mainWindow;
app.on('ready', function() {
    mainWindow = new BrowserWindow({
        width: 800,
        height: 500,
        show: true,
        vibrancy: 'dark',
        webPreferences: {
            blinkFeatures: 'CSSBackdropFilter'
        }
    });
    mainWindow.loadURL(url.format({
        pathname: path.join(__dirname, 'demo.html'),
        protocol: 'file:',
        slashes: true
    }));
});
```

demo.html
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Demo</title>
</head>
<body>
    <div class="header">
        This is a header
    </div>
    <div class="contents">
        This is a contents
        <img src="http://i0.kym-cdn.com/entries/icons/original/000/002/232/bullet_cat.jpg" />
        <br>
        This text will be broken
        <br>
        <br>
        And this also
    </div>
    <style>
        body {
            color: #fff;
        }
        .header {
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            height: 85px;
            backdrop-filter: blur(20px);
        }
        .contents {
            padding: 100px 20% 100% 20%;
        }
    </style>
</body>
```

Just start app on MacOS and scroll

**Screenshots**
![13-2018 10-19-12](https://user-images.githubusercontent.com/3584432/39964897-2766eb18-5697-11e8-9fdc-6228f10f964a.gif)

<img width="817" alt="image" src="https://user-images.githubusercontent.com/3584432/39964908-78c0ca88-5697-11e8-8b7f-c146e3aa4864.png">

If I will remove `backdrop-filter: blur(20px);` everything renders OK.
<img width="817" alt="image" src="https://user-images.githubusercontent.com/3584432/39964951-57d84eb2-5698-11e8-885b-8a8f0ef19bb5.png">

THERE IS NO PROBLEM WITH VIBRANCY - DISABLING THAT WILL NOT SOLVE THE PROBLEM
<img width="799" alt="image" src="https://user-images.githubusercontent.com/3584432/39964980-e6fb69e4-5698-11e8-8887-1f4ee0a97d6a.png">

**Comment by iLeonidze** [comment]
WA:
Add `background` property to `body`: that will fix glitch. For example `background:#000`:
<img width="811" alt="image" src="https://user-images.githubusercontent.com/3584432/39966582-0b0b1e6a-56b7-11e8-8f2a-6174481b830f.png">

But if I will modify that property and add alpha, for example `background: rgba(0, 0, 0, 0.05)` background color will not modify and glitch will appear:
<img width="820" alt="image" src="https://user-images.githubusercontent.com/3584432/39966595-4e29ac66-56b7-11e8-9c9f-31aa0ec7e4cf.png">

**Comment by iLeonidze** [comment]
Latest Chrome 63.0.3239.84 do not has that bug. I enabled Experimental Web Platform features and tried that demo in browser. The same in Safari: it is also do not have that bug.

**Comment by MarshallOfSound** [comment]
@iLeonidze You are using an experimental feature in `blinkFeatures` that is almost certainly causing this rendering issue.

Although you have reported that this flag works as expected in Chrome 66 the Electron version you are testing with is based on Chrome 61.  Only once this flag has become "stable" in Chromium can we look into bugs related to it, it is still flagged as experimental and not even stable in Chromium yet
