### ISSUE TITLE
Blurred picture rendering

### ISSUE THREAD

**Issue by y489436672** [electron/electron#12905]
* Electron Version: 2.0.0
* Operating System (Platform and Version): win7  win10  X64
* Last known working Electron version: 2.0.0

**Expected Behavior**
Set the picture 1:1 height and width, set the picture container height less than the picture height and "overflow:auto" should clear the picture and appear scroll bar.

**Actual behavior**
Blurred picture rendering.Set picture container height picture will be blurred
But work normally in electron v1.8.6
**To Reproduce**
```
<div style="width: 500px;height:300px;overflow：auto">
<img  src="a.png" style ="width:800px; height:500px;" />
</div>
```

**Comment by ckerr** [comment]
This sounds more like a change in Chromium than a change made in Electron.

What happens if you try loading the same test in Chrome 59 (used by Electron 1.8) and Chrome 63 (used by Electron 2.0)?

**Comment by y489436672** [comment]
I'm sorry to be late.
The same code. 
In electron@2.0.0
![120180516234851](https://user-images.githubusercontent.com/19664101/40128718-e2b5038a-5964-11e8-9bf1-721571b06ed7.png)
In electron@1.8.6
![20180516235325](https://user-images.githubusercontent.com/19664101/40128777-172e3500-5965-11e8-917c-1c54ca8c946a.png)
It's clear that the picture is different.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
