### ISSUE TITLE
getProducts and finishTransactionByDate is not available on Mac,  Electron 2.0.0

### ISSUE THREAD

**Issue by thomasdao** [electron/electron#12908]
* Electron Version: 2.0.0
* Operating System (Platform and Version): Mac High Sierra 10.13.4
* Last known working Electron version: N/A

**Expected Behavior**
`getProducts` and `finishTransactionByDate` is in inAppPurchase

**Actual behavior**
`getProducts` and `finishTransactionByDate` is not available in inAppPurchase. I have tested in Mac with latest Electron 2.0.0. Other methods like `canMakePayments` and `purchaseProduct` is available. I have tried calling `inAppPurchase.getProducts` and have an error `getProducts is not a function`.

**Screenshots**
<img width="467" alt="screen shot 2018-05-12 at 06 20 23" src="https://user-images.githubusercontent.com/863218/39980912-626d91b2-5778-11e8-95c9-9e7ae8befd83.png">

**Comment by sethlu** [comment]
@thomasdao I'm wondering if it is a release issue with v2.0.0/v2.0.1? The latest build of Electron (156a97b80d1fe1cf701d035e6481dc00fbd56677) doesn't seem to have this issue.

![screenshot 2018-05-19 18 15 04](https://user-images.githubusercontent.com/3168941/40274641-a2076dae-5b90-11e8-9954-a79df90b4bf7.png)

**Comment by sethlu** [comment]
@thomasdao Actually https://github.com/electron/electron/pull/12464 isn't back ported to `2-0-x` so I believe it'll be shipped with `2-1-x`.

**Comment by ivandroid** [comment]
The inAppPurchase method does not provide the method getProducts. 

`interface InAppPurchase extends EventEmitter {

    // Docs: http://electron.atom.io/docs/api/in-app-purchase

    /**
     * Emitted when one or more transactions have been updated.
     */
    on(event: 'transactions-updated', listener: (event: Event,
                                                 /**
                                                  * Array of transactions.
                                                  */
                                                 transactions: Transaction[]) => void): this;
    once(event: 'transactions-updated', listener: (event: Event,
                                                 /**
                                                  * Array of transactions.
                                                  */
                                                 transactions: Transaction[]) => void): this;
    addListener(event: 'transactions-updated', listener: (event: Event,
                                                 /**
                                                  * Array of transactions.
                                                  */
                                                 transactions: Transaction[]) => void): this;
    removeListener(event: 'transactions-updated', listener: (event: Event,
                                                 /**
                                                  * Array of transactions.
                                                  */
                                                 transactions: Transaction[]) => void): this;
    canMakePayments(): boolean;
    getReceiptURL(): string;
    purchaseProduct(productID: string, quantity?: number, callback?: (isProductValid: boolean) => void): void;
  }`

**Comment by thomasdao** [comment]
Thanks @sethlu. Look forward to the next version :). Btw I think InAppPurchase interface is a little confusing with other documentation, because the public methods are declared differently. It'd be good if it can be more consistent.

**Comment by immanoj16** [comment]
Hey @thomasdao, Did you find the solution?? Still the latest version of electron `2.0.1` has the same problem, the methods ain't there.

**Comment by thomasdao** [comment]
@immanoj16 no, the only thing we can do is to wait until 2.1.0 is out

**Comment by immanoj16** [comment]
Thank you, @thomasdao

**Comment by sferoze** [comment]
@sethlu @ivandroid @thomasdao 

There are other functions that are documented but are not showing up

`inAppPurchase.getReceiptURL()` is not found

**Comment by sethlu** [comment]
@sferoze Mhm, I believe `inAppPurchase.getReceiptURL()` is available for v2.0.1. Which version of Electron are you testing with?

**Comment by sferoze** [comment]
@sethlu my mistake getReceiptURL is available....

@thomasdao It look like you may be doing Apple subscription? I am developing an Apple subscription plan, and I have created the subscription in iTunes Connect etc.... like I did for iOS...

But whenever I query to purchaseProduct with correct ProductID, it says product is not found...

Is this because we need the getProducts API to work, and need to call that first before calling purchaseProduct?

**Comment by thomasdao** [comment]
@sferoze yes I plan to do subscription as well, but I'm still waiting for 2.1.0. I guess even if I can purchaseProduct successful, I still cannot finish the transaction, so there's no point of doing anything now

**Comment by JeganMSD** [comment]
Methods found in 3.0.0@beta version of electron but the developed apps will run only on MacOs greater than 10.10. @thomasdao @sferoze
