### ISSUE TITLE
riot-desktop renders white

### ISSUE THREAD

**Issue by plus13** [electron/electron#12903]
* Electron Version: v1.8.4
* Operating System (Platform and Version): Archlinux 4.15.15-1-ARCH x86_64, AwesomeWM
* Last known working Electron version: Not sure. A few months ago

Hi,

this problem now persists for a few months and I already tried all suggestions I could find.
I was using riot-desktop (eletron version of riot) under Archlinux with AwesomeWM for quite a while until the whole electron app turned itself blank a few month ago. Look at:

[https://img.vim-cn.com/c9/83da992ac183ae13fa959ad97d997d90321868.jpg](https://img.vim-cn.com/c9/83da992ac183ae13fa959ad97d997d90321868.jpg)

If I now click on the white window and drag the content I can see it within the drag animation:

[https://img.vim-cn.com/0e/325168b789c2bf82cf81df82257ea69aa66e96.jpg](https://img.vim-cn.com/0e/325168b789c2bf82cf81df82257ea69aa66e96.jpg)

When I stop dragging it's all white again. I am not able to resolve this problem even though I tried to proceed similar like this one:

[https://www.christianengvall.se/electron-white-screen-app-startup/](https://www.christianengvall.se/electron-white-screen-app-startup/)

I cannot get my way through the logs-button in the settings menu, but when I start riot-desktop from a terminal I get the following of which I believe that's not causing the problem:

$ riot-deskop
Starting auto update with base URL: null
Auto update not supported on this platform
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
libGL error: failed to open drm device: No such file or directory
libGL error: failed to load driver: i965

I already mentioned this in the riot issue tracker:

[https://github.com/vector-im/riot-web/issues/6711](https://github.com/vector-im/riot-web/issues/6711)

Kind regards

**Comment by ckerr** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.
Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unneccessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you've responded, please link to the test case and @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by plus13** [comment]
Now I get something I can not relate to at all, I did:
```
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start
npm install
npm start
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.0.1
3 info using node@v10.1.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle electron-quick-start@1.0.0~prestart: electron-quick-start@1.0.0
6 info lifecycle electron-quick-start@1.0.0~start: electron-quick-start@1.0.0
7 verbose lifecycle electron-quick-start@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle electron-quick-start@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/user/tmp/electron-quick-start/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
9 verbose lifecycle electron-quick-start@1.0.0~start: CWD: /home/user/tmp/electron-quick-start
10 silly lifecycle electron-quick-start@1.0.0~start: Args: [ '-c', 'electron .' ]
11 silly lifecycle electron-quick-start@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle electron-quick-start@1.0.0~start: Failed to exec start script
13 verbose stack Error: electron-quick-start@1.0.0 start: `electron .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:283:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:957:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
14 verbose pkgid electron-quick-start@1.0.0
15 verbose cwd /home/user/tmp/electron-quick-start
16 verbose Linux 4.15.15-1-ARCH
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.1.0
19 verbose npm  v6.0.1
20 error code ELIFECYCLE
21 error errno 1
22 error electron-quick-start@1.0.0 start: `electron .`
22 error Exit status 1
23 error Failed at the electron-quick-start@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
