### ISSUE TITLE
can not find desktopCapturer in electron

### ISSUE THREAD

**Issue by lirongfei123** [electron/electron#12910]
const desktopCapturer = require('electron').desktopCapturer;
const log = require('electron-log');
log.info(desktopCapturer);
the result: 
undefined
my electron version is v2.0.0

**Comment by timfish** [comment]
Are you doing this in the renderer process? This API is not available in the main process.

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
