### ISSUE TITLE
how to convert chrome extension to electron extension

### ISSUE THREAD

**Issue by lirongfei123** [electron/electron#12911]
my chrome extension code is
`
chrome.desktopCapture.chooseDesktopMedia(['screen', 'window'], function (streamId)
`
how can i make my code run in electron

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
