### ISSUE TITLE
Spell checking needs to recheck when the provider is changed

### ISSUE THREAD

**Issue by paulcbetts** [electron/electron#1291]
To Repro:

1. Use `setSpellCheckProvider` to set up English spellchecking
1. Realize the user is typing in German
1. Hwhoops! Call `setSpellCheckProvider` again to check German words

Now, half the sentence still has misspelling marks back from when we thought it was English:

![](http://cl.ly/image/1T3A343J1w2t/content#png)

We need to reevaluate all of the words in the input box whenever we call `setSpellCheckProvider`

**Comment by hokein** [comment]
After looking more inside Blink, the current SpellCheck API interfaces in Blink doesn't support this usage.

The [SpellCheck](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/Source/core/editing/SpellChecker.cpp&sq=package:chromium&type=cs&l=383&rcl=1436500326) in Blink will be triggered when the currently typing word is end, basically typing a space or a line break, and there is no way to reevaluate the words that have already been reevaluated.

Suppose you have typed the following words with `setSpellCheckProvider` to setup English checking:
```
This is an te
             ^
             | cursor
```

Now you `setSpellCheckProvider` again to check China words, and keep typing characters `a` and ` `.
```
This is an tea 
```

The spell check will only check the word `tea` with Chinese spell check provider.

**Comment by jfmdev** [comment]
Chrome had this same issue two years ago: https://bugs.chromium.org/p/chromium/issues/detail?id=178379 (not sure if they solved it).

**Comment by zcbenz** [comment]
I'm closing this since we are not able to fix this without Chromium fixing it on their side, people concerned about this issue should go to the issue above to get Chromium team's attention.

**Comment by jfmdev** [comment]
Is not an ideal solution, but until this issue gets fixed at Chrome, you can try the following workaround: 

After changing the provider, use Javascript to change the caret position, making it go over every word.

This works since moving the caret forces the spellchecker to re-evaluate every word _touched_ by the caret.
