### ISSUE TITLE
Browser windows have an extra tab focus which can not be disabled and is not visible

### ISSUE THREAD

**Issue by MRayermannMSFT** [electron/electron#12919]
* Electron Version: 2.0.0
* Operating System (Platform and Version): Windows 10
* Last known working Electron version:  N/A

**Expected Behavior**
If the last focusable HTML element is focused and I press 'tab', then the next thing that is focused should either be the first focusable HTML element, or if not, then whatever is focused should have a visible focus.

**Actual behavior**
Something is being focused (I think it is the entire HTML document?) and there is no visual indication as to what it is. It is fine that this other thing is being focused, what is not fine is that I/a user does not know where the keyboard focus has gone.

**To Reproduce**
- Checkout the [electron-quick-start](https://github.com/electron/electron-quick-start)- Put an `<input type="text"/>` before the `renderer.js` script
- Launch quick start
- Set focus in the input
- Press 'tab'

**Comment by craxal** [comment]
Is there any plan to get this fixed? Or is there a known workaround?

**Comment by bpasero** [comment]
From my knowledge of this issue, this has been like that for a very long time and is not a regression from Electron 2.0. Possibly related: https://developers.google.com/web/updates/2016/03/focus-start-point

**Comment by craxal** [comment]
Not sure if it is. I'm seeing a Chrome version of 61 for Electron 2.0.0.

We suspect that focus is passing out of the HTML document onto the renderer window itself, since screen readers (sometimes) read out the title bar of the window.

I should add that I've observed this on macOS and Linux as well. It's not just a Windows issue.

**Comment by MRayermannMSFT** [comment]
Ya, it looks like the problem is that `Chrome_RenderWidgetHostHWND`'s are focusable. Based on that name, it sounds like @craxal is correct, and it also makes me think this will require filing against Chromium.

**Comment by MRayermannMSFT** [comment]
Chromium issue can be found here: https://bugs.chromium.org/p/chromium/issues/detail?id=869469&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified
