### ISSUE TITLE
Disable `eval()` in the renderer by default

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#12929]
**Is your feature request related to a problem? Please describe.**

Electron is known for being insecure. It should come with better security defaults.

**Describe the solution you'd like**

The Electron [security checklist](https://github.com/electron/electron/blob/master/docs/tutorial/security.md#7-override-and-disable-eval) recommends overriding `eval()` to disable it, but I would argue it's better to disable it by default and let users opt into having it with a `BrowserWindow` option. Most apps will not need `eval()`, so we should optimize for that.

CSP is also able to disable `eval`, but I still argue `eval()` should be disabled by default regardless of whether you use CSP or not.

If users really need it, they could enable it like so:

```js
const win = BrowserWindow({
	allowEval: true
});
```

**Comment by MarshallOfSound** [comment]
This fundamentally goes against maintaining web compatibility with Electron, disabling `eval` by default will almost certainly cause an increased support load on us from issues like "eval does not work, plz help, it works in chrome...".

I'm all for increased security, but not at the expense of web compatibility

**Comment by sindresorhus** [comment]
I agree about general web compatibility, but Electron is not a web browser and `eval()` is a misfeature of the language. Yes, you could make a web browser with Electron, but the main use-case is creating native apps with web technologies.

Electron could display a useful warning in the console if `eval()` is used with instruction on how to enable it again.

**Comment by MarshallOfSound** [comment]
@sindresorhus A lot of people use webpack, and a lot of people's webpack output spits out `eval` statements (especially during development).  Providing a one liner to disable `eval` might be something we can do, but making it disabled by default is something I'm strongly 👎 on

**Comment by sindresorhus** [comment]
@MarshallOfSound Webpack only uses `eval` if you select that source map type, and that's only in development. Users that need it could just do `allowEval: isDev` then.

**Comment by baconbrad** [comment]
Eval can be safe and intended in some applications. Being a "misfeature" is up to your interpretation. Be it purposely accepting user input or accepting generated input a user cannot manipulate. This applies for even non Electron projects. While it could have some negative behavior we shouldn't assume the intended behavior and cause a breaking change.

**Comment by groundwater** [comment]
> Electron is known for being insecure. It should come with better security defaults.

I would like to improve security, but I'm not sure I'm onboard with a piecemeal approach, particularly ones that would create a false sense of security.

If your app is insecure, I'm doubtful that Electron disabling `eval()` will change that. In particular, if apps are loading remote content with node integration enabled, disabling `eval()` accomplishes very little.

I am 👍 on a general approach of steering people towards best-practices, but I'm ✋ (hold) on implementing this change to accomplish that.

**Comment by felixrieseberg** [comment]
Thing is, _just_ disabling `eval` doesn't even get you there. You'd have to disable `new Function()`, too, and it gets tricky from there. Because if the page has jQuery, `jQuery.ajax` will check if a requested resource has a JavaScript MIME type and will blindly execute it.

Building desktop apps is a practice in which developers _need_ to engage with their app and think about security. That's not unique to Electron, people need to think about what happens in their app regardless of framework.

I agree that not having `eval` available by default adds another layer, but as our security practices mention, that's just a tiny piece of the puzzle. Given that disabling `eval()` by itself doesn't do much if the other areas are left untouched, and given how it likely breaks a bunch of JavaScript, I'm with @MarshallOfSound – this would likely do more harm than good.

**Comment by sindresorhus** [comment]
You seem to be arguing against your own security recommendation: https://github.com/electron/electron/blob/master/docs/tutorial/security.md#7-override-and-disable-eval 😕

**Comment by ccorcos** [comment]
Also relevant: it doesn't tell you where to put this code either! https://github.com/electron/electron/blob/master/docs/tutorial/security.md#7-override-and-disable-eval

```
window.eval = global.eval = function () {
  throw new Error(`Sorry, this app does not support window.eval().`)
}
```

**Comment by agowa338** [comment]
And how to re enable?
I updated a electron app and now the page does not load and only shows:
`ClientError;exMsg=Sorry, this app does not support window.eval().;file=Error: Sorry, this app does not support window.eval()`
@codebytere Can you please provide instructions on how to enable eval?
