### ISSUE TITLE
bug: Windows 10 "Sets" overwrite full-screen mode with partial title bar

### ISSUE THREAD

**Issue by alexch** [electron/electron#12920]
* Electron version: ?
* Operating system: Windows 10 preview
  * VS Code version: Code 1.23.0 (7c7da59, 2018-05-03T16:44:55.614Z)
  * OS version: Windows_NT x64 10.0.17661

* Last known working Electron version: ?

### Expected behavior

in full screen mode, window title bar should be invisible

### Actual behavior

see screenshot: ![screenshot with window title bar visible](https://user-images.githubusercontent.com/8524/39836189-8c82504a-53a0-11e8-90e9-c78f34c3f205.png)

### How to reproduce

1. download & install Visual Studio Code
2. enter "Full Screen" or "Zen Mode"

see https://github.com/Microsoft/vscode/issues/49570 for more details

**Comment by MarshallOfSound** [comment]
I mean until that feature hits Windows stable I wouldn't feel comfortable pointing the finger at anyone 😆 But this wouldn't be the first time new windows features have caused rendering glitches 😄

**Comment by alexch** [comment]
Sure, just consider this a heads-up.
