### ISSUE TITLE
Reposition/Resize at the same time flicker

### ISSUE THREAD

**Issue by alexa026** [electron/electron#12938]
* Electron Version: 1.8.x / 2.0
* Operating System (Platform and Version): macOS High Sierra, Windows 7 and Windows 10
* Last known working Electron version: /

**Expected Behavior**
So we are using electron to create a toolbar (https://user-images.githubusercontent.com/139744/39877183-84947c66-5475-11e8-9ff6-0364507aa798.png). When the icon on the toolbar is clicked, it expands to show up the content of it, like:
![unnamed](https://user-images.githubusercontent.com/139744/40056140-af62e9fe-584a-11e8-9cd9-448a07742bd3.png)
It is expected to resize and reposition the toolbar without causing flickering.

**Actual behavior**
We are facing here an issue, when toolbar expands, it flickers on the wrong position for a few milliseconds and then goes back to how its supposed to be.
Functions used to achieve this:
- setSize (to expand to the right size)
- setPosition (for the toolbar to remain aligned with the right border of the screen)

**To Reproduce**
Try to align the window with right border of the screen and then resize it (for example, from 70px to 400px) while trying to keep it aligned with right side of the screen.

**Screenshots**
Video: https://drive.google.com/file/d/1RVHJsr4VYEY-BLQ-2w12_r_qtCd8HL_R/view?usp=sharing

**Additional Information**
As previously stated, we are trying to keep window aligned with the right border of the screen. We've already tried to use `setBounds` to set both size and position at the same time, but no luck, the same thing happened.

**Comment by yussinsharp** [comment]
Is there any movement on what this might be? I am getting the same issue in another app. Would be nice if we can pause the "re-paint" of the app until the window's x, y, width and height values are all changed together.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by floating** [comment]
I am still experiencing this using Electron `v6.0.9`. 

@alexa026 or @yussinsharp Did you ever come across a solution for this?
