### ISSUE TITLE
[QUESION] How can I set environment variable PATH in Electron app?

### ISSUE THREAD

**Issue by hz0324** [electron/electron#12934]
Our app has some .exe file for doing certain works.
In order to make them work, we need to add the .exe folder path to the path environment.
How can we do this in Electron App?

Thanks

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
