### ISSUE TITLE
Support whitelisting allowed `remote.require` modules

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#12932]
**Is your feature request related to a problem? Please describe.**

Electron is known for being insecure. This would help improve security.

**Describe the solution you'd like**

The `remote.require` feature is very useful, but I would like to control which modules are allowed with it. For example, I would like to disallow `child_process` and `fs` as they can be dangerous security-wise and it's also a bad idea performance-wise to use them through the remote module.

I realize I could disable Node.js integration, but I don't want to completely do that, I just want to limit the risk.

This would be opt-in, so all modules would be allowed unless you set the option.

**Describe alternatives you've considered**

Could also be a block list, but I think it's safer to explicitly list the modules you want to allow.

I would also have preferred to exclude `child_process` by default and not allow it at all, since it's such a security hazard, but I doubt the Electron maintainers will agree.

**Comment by baconbrad** [comment]
This is the whole purpose of the `nodeIntergration` option. Setting it to true will not just leave you to that context but a massive context that would just be too difficult to lock down in the way you are asking.  At some point Electron application developers need to focus on security within their application and not allow malicious scripts/users to be able to `eval` code so easy. And if they do they need to either disable `nodeIntergration` or come to terms their users can ultimately run non-sandboxed code.

**Comment by miniak** [comment]
I think it makes sense to introduce 2 new APIs:
- `setRemoteRequireHandler(handler: (name: string) => any): void`
- `setRemoteGetGlobalHandler(handler: (name: string) => any): void`
