### ISSUE TITLE
webview devtools didn't support sourceMap?

### ISSUE THREAD

**Issue by peihexing** [electron/electron#12936]
webview devtools didn't support sourceMap?

**Comment by peihexing** [comment]
![image](https://user-images.githubusercontent.com/13557073/40050285-97de5c0e-5869-11e8-89eb-2311eeb759eb.png)

![image](https://user-images.githubusercontent.com/13557073/40050333-b55d0280-5869-11e8-9288-9a0bed125aba.png)

**Comment by MarshallOfSound** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensures everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you've responded, please link to the test case and @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by tongdehui** [comment]
webview的同源策略会生效，可以试试这个属性 disablewebsecurity

![image](https://user-images.githubusercontent.com/29793464/98788780-51909680-243c-11eb-8772-a19fb6855e57.png)
