### ISSUE TITLE
getPrimaryDisplay is the default screen and not the active screen

### ISSUE THREAD

**Issue by kevinsimper** [electron/electron#1293]
In OSX 10.9 you can move the active screen around, but getPrimaryDisplay returns still the original active screen (which is my macbook and not my external display).

I suggest that a new function getActiveDisplay is made or getPrimaryDisplay is changed since it is not the primary screen, that is the screen that has the app dock.

![image](https://cloud.githubusercontent.com/assets/1126497/6822426/f27fd812-d2df-11e4-90c0-963ad190753c.png)

**Comment by skibz** [comment]
altering the behaviour of `getPrimaryDisplay` would be absurd O_o

**Comment by zcbenz** [comment]
I'm afraid this is not possible with the API provided by Cocoa, neither `[NSScreen screens]` nor `[NSScreen mainScreen]` is able to achieve what you want, and there is no other API we can use. So I'm closing this as won't fix.

**Comment by andymartinwork** [comment]
@zcbenz 

Would this not be sufficient?

```
        NSScreen* screen = [window screen];
        if (screen == nil)
            screen = [NSScreen mainScreen];
```
