### ISSUE TITLE
Disable `<webview>` support by default

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#12930]
**Is your feature request related to a problem? Please describe.**

Electron is known for being insecure. It should come with better security defaults.

**Describe the solution you'd like**

The `<webview>` tag comes with a lot of security implications and many apps don't use or need it. I think the `BrowserWindow` option `webPreferences.webviewTag` should be `false` by default. Users can opt into it if they need it, but I don't think it's a good default to have it on by default.

**Comment by sindresorhus** [comment]
// @MarshallOfSound

**Comment by MarshallOfSound** [comment]
This goes with an issue I can't find right now about making `nodeIntegration` disabled by default 👍

**Comment by MarshallOfSound** [comment]
This is how it works in Electron 5 👍 (Defaults to `false` along with `nodeIntegration`)

https://github.com/electron/electron/blob/master/atom/browser/web_contents_preferences.cc#L122-L125
