### ISSUE TITLE
Can't load local video file over file:// protocol

### ISSUE THREAD

**Issue by albinekb** [electron/electron#12942]
* Electron Version: v2.0.0
* Operating System (Platform and Version): `macOS 10.13.4 (17E199)`
* Last known working Electron version: 1.x

**Expected Behavior**
Having `<meta httpEquiv="Content-Security-Policy" content="media-src file://*;"/>` in the document head should allow loading local media files like `file:///path/to/video.mp4`

**Actual behavior**
Error in DevTools console 
```
Not allowed to load local resource: file:///Users/albinekb/Devel/Projects/kap/test/fixtures/kap-beta.mp4
```

**To Reproduce**
```sh
$ git clone git@github.com:albinekb/electron-quick-start.git -b media-csp
$ yarn
$ yarn start
```

**Additional Information**
It works if i disable `webSecurity`

**Comment by albinekb** [comment]
Hm, I got it working. There must be some issue in my original code.

**Comment by albinekb** [comment]
It's not working because my app is loading over insecure http in dev, thus the CSP is not being honoured, like it should be 👍

**Comment by benjaminadk** [comment]
Interesting. I like to use `electron-webpack` to develop, which loads app over localhost as far as I understand. What I am trying now is setting a boolean based on `process.env.NODE_ENV !== 'production'`. Then if I am not in production I turn off webSecurity. Lets me load videos in development, but have not done a build yet to test it in production w/security. Was wondering what you settled on for as a solution. Thanks @albinekb .

**Comment by albinekb** [comment]
That's the same solution I came up with, seems to work nicely @benjaminadk 
https://github.com/wulkano/kap/blob/master/main/editor.js#L32-L34
