### ISSUE TITLE
Can't start Electron v2.* on Arch

### ISSUE THREAD

**Issue by stefaneli31** [electron/electron#12959]
* Electron Version: 2.* (from beta.1 to stable)
* Operating System (Platform and Version): Arch Linux (running the latest kernel)
* Last known working Electron version: 1.8.6 (running the same latest linux kernel)

When using v1.8.6 Electron opens app without any issues, however if I update it to 2.0.0-beta.1 or higher I get the following error:
```
electron: can't open display
```
Electron is started from terminal with the command: `electron main.js`
Other apps on Arch are working properly.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
