### ISSUE TITLE
electron app in ubuntu cannot access network drive

### ISSUE THREAD

**Issue by fengyueran** [electron/electron#12958]
* Electron Version:2.0.0
* Platform: ubuntu16.04

dialog.showOpenDialog to file choose, i can not see the  network drive share folder
![snip20180516_1](https://user-images.githubusercontent.com/17682887/40095421-8b8e85ec-58fe-11e8-8165-9e699e043ffd.png)

![snip20180516_2](https://user-images.githubusercontent.com/17682887/40095529-33b839b6-58ff-11e8-910c-5e055521e3d4.png)

but in mac the electron app,dialog.showOpenDialog to file choose, i can see the  network drive share folder
![snip20180516_3](https://user-images.githubusercontent.com/17682887/40098344-a0dc1d4c-590d-11e8-8864-5dcb455f0666.png)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
