### ISSUE TITLE
mouseover in main window disabled while contextmenu showing

### ISSUE THREAD

**Issue by xthdraft** [electron/electron#12961]
* Electron Version:1.8.4
* Operating System (Platform and Version):win10 
* Last known working Electron version: -

**Expected Behavior**
When calling up a context menu in the render process (which is perfectly fine), one expects that mouseover events would be captured in the main window.  For example, tooltips on menu items in the app's main window should display while the context menu is showing.   

I'm not sure if this is a bug, a non-supported feature, or simply my misunderstanding of electron.

**Actual behavior**
Although mouseover seems inoperable,  **onclick events work ok** - clicking on links or menu items in the main window is fine.

To Reproduce**

my code:
var remote = require("electron").remote;
var menuItem = remote.MenuItem;
myeditmenu.append (new menuItem({
        label: 'Toggle Developer Tools',
        accelerator: process.platform === 'darwin' ? 'Alt+Command+I' : 'Ctrl+Shift+I',
        click (item, focusedWindow) {
          if (focusedWindow) focusedWindow.webContents.toggleDevTools()
        }
      }));
/* plus other menu items */

window.addEventListener(
    "contextmenu",
    e => {
        e.preventDefault();        // commenting out this doesn't help
        e.stopPropagation();     // commenting out this doesn't help
        x = e.clientX +10;
        y = e.clientY+20;
       myeditmenu.popup(remote.getCurrentWindow(), x, y);
       return false;                   
![electron_contextmenu_bug](https://user-images.githubusercontent.com/3181754/40114349-eac79cfa-594f-11e8-8de5-3bb4a34ac15c.png)
// retuning true doesn't help
      },
    false     
);

**Screenshots**
see attached electron_contextmenu_bug.png
**Additional Information**

**Comment by MarshallOfSound** [comment]
This is not supported (not a bug), check the behavior in Chrome and you will find the same thing.

I.e. Listen for `mousemove` events, they will not fire while the context menu is open

**Comment by xthdraft** [comment]
Thanks for pointing that out. I should have checked. Interestingly, Firefox
allows mouseover while context menus are open.

**Comment by fabiospampinato** [comment]
It would be useful to have the ability to still receive mouse events while context menus are open, in order to implement a note-like menubar experience under Windows for example where context menus are opened and closed depending on where the cursor is.

**Comment by xthdraft** [comment]
Forget electron's contextmenu.  Simply use a normal div or nav element as a container wrapping a list of li elements.  Put an event watcher on document.body.  This watches for right mouse clicks. On any such click you call the handler which displays the container. Any normal  mouse events on the window  outside the container are not blocked. Plus you can style the container any way you want.

**Comment by fabiospampinato** [comment]
@xthdraft Thanks for the suggestion. The "simply" part of that I'm not too sure about, as you have a edge cases related to your menus being constrained by the window's bounds. Besides Electron apps should behave more native-like when possible, and using those native menus that can go beyond the bounds of your window has a nice feeling to it:

![Screen Recording 2020-07-07 at 00 52 51](https://user-images.githubusercontent.com/1812093/86670809-f1e93100-bfec-11ea-998f-f6f9d40fab93.gif)
