### ISSUE TITLE
TouchBarSegmentedControl icons scaled incorrectly

### ISSUE THREAD

**Issue by BinaryMoon** [electron/electron#12965]
* Electron Version: 2
* Operating System (Platform and Version): MacOS High Sierra
* Last known working Electron version: n/a

**Expected Behavior**

I created a TouchBarSegmentedControl and added some segments with icons. I expected the icons to size the same way as they do on TouchBarButtons.

**Actual behavior**

The icons stretched to the wrong size.

**To Reproduce**
```
const touchBarTools = new TouchBarSegmentedControl(
	{
		segmentStyle: 'textured-square',
		mode: 'single',
		segments: [
			{ icon: nativeImage.createFromPath( path.join( __dirname, 'assets/images/touch/tool-pen.png' ) ) },
			{ icon: nativeImage.createFromPath( path.join( __dirname, 'assets/images/touch/tool-shapes.png' ) ) },
			{ icon: nativeImage.createFromPath( path.join( __dirname, 'assets/images/touch/tool-lines.png' ) ) },
			{ icon: nativeImage.createFromPath( path.join( __dirname, 'assets/images/touch/tool-eraser.png' ) ) },
		],
	}
);

const touchBarButton = new TouchBarButton(
	{
		icon: nativeImage.createFromPath( path.join( __dirname, 'assets/images/touch/tool-pen.png' ) )
	}
);

const touchBar = new TouchBar(
	[
		touchBarTools,
		touchBarButton,
	]
);


/**
 * Create the app window.
 * Most of the functionality for this is run through app.js.
 */
const createWindow = () => {

	// Grab the screen width and height so we can calculate the screen size.
	const { width, height } = electron.screen.getPrimaryDisplay().workAreaSize;

	// Create the browser window.
	mainWindow = new BrowserWindow(
		{
			'width': Math.max( ( width - 200 ), 800 ),
			'height': Math.max( ( height - 100 ), 600 ),
			'minHeight': 512,
			'minWidth': 512,
			'title': 'Brush Ninja',
			// 'titleBarStyle': 'hidden',
			'center': true,
			'icon': path.join( __dirname, 'assets/ninja.iconset/icon_64x64.png' ),
		}
	);

	mainWindow.setTouchBar( touchBar );

};

```

**Screenshots**

<img width="1085" alt="touch bar shot 2018-05-16 at 20 42 44" src="https://user-images.githubusercontent.com/1004130/40140049-c179a5ce-5949-11e8-8585-8192e6c09259.png">

You can see in the screenshot that there is a TouchBarSegmentedControl followed by 2 buttons. The icon used in the first segment is the same as the one used on the second button. The icon size works perfectly on buttons, so I am not sure why it is being scaled on the segment control. I would expect the scaling to be the same on both items.

The segments don't appear to have many properties so I can't see anything about scaling things differently.

I do have @2x and @3x sizes for the icons however the icons appear to be enlarged version of the base size.

**Comment by jordan-arenstein** [comment]
I am also having this issue, using the system icon templates, for example: `nativeImage.createFromNamedImage("NSTouchBarSidebarTemplate", white)` is also not correctly scaled.

**Comment by jordan-arenstein** [comment]
I've done some digging. In `atom/browser/ui/cocoa/atom_touch_bar.mm`, line 571, a segmented control is setup as `[NSSegmentedControl segmentedControlWithLabels:...`. The alternative is `[NSSegmentedControl segmentedControlWithImages:...`, which does not misscale the icons.

`segmentedControlWithImages` does not seem to break `TouchBarItem`s with only a label property, and when a `TouchBarItem` has both a label and an icon, only the label is displayed.

**Comment by wisotzky** [comment]
Any progress on this item?
Seeing the same issue with ATOM 1.31.2 x64:
Electron: 2.0.7
Chrome: 61.0.3163.100
Node: v8.9.3

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
