### ISSUE TITLE
Presentation API

### ISSUE THREAD

**Issue by joshtynjala** [electron/electron#12969]
**Is your feature request related to a problem? Please describe.**

I'm trying to use the [Presentation API](https://developer.mozilla.org/en-US/docs/Web/API/Presentation_API) [[2](https://www.w3.org/TR/presentation-api/)] in Electron. The Presentation API works in Chrome, but I get "DOMException: No screens found." when I try to call PresentationRequest's start() method in Electron on the same machine. getAvailability() doesn't work either.

**Describe the solution you'd like**

Enable Presentation API that is already implemented and working correctly in Chrome.

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!

**Comment by bradisbell** [comment]
It's unfortunate this isn't supported in Electron.

Anyone have suggestions as to where to begin an implementation?  I suspect we just need to expose the ability for that output device selection dialog, but am unsure where to begin.  It seems similar to the `getUserMedia()` device selection.

By the way, if anyone wants to see the current state of things, run this from JavaScript:

```javascript
await new PresentationRequest('https://example.com').start()
```

You'll see that error @joshtynjala mentioned, under Electron.  In Chromium, you'll be prompted to choose an output device.
