### ISSUE TITLE
Electron build fails in release config with VS 2017 

### ISSUE THREAD

**Issue by ahmedmohamedali** [electron/electron#12974]
* Electron Version: 2.0.x
* Operating System (Platform and Version):  Windows 7 professional
* Last known working Electron version: 

**Expected Behavior**
Electron release build to succeed

**Actual behavior**
Debug build is OK.
The release build fails with the following error 

"c:\Python27\python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /OUT:openssl-cli.exe @openssl-cli.exe.rsp" 1 mt.exe rc.exe "obj\vendor\node\deps\openssl\openssl-cli.openssl-cli.exe.intermediate.manifest" obj\vendor\node\deps\openssl\openssl-cli.openssl-cli.exe.generated.manifest
openssl.lib(openssl.ec2_smpl.obj) : error LNK2001: unresolved external symbol _guard_dispatch_icall
openssl-cli.exe : fatal error LNK1120: 1 unresolved externals
Traceback (most recent call last):
  File "gyp-win-tool", line 323, in <module>
    sys.exit(main(sys.argv[1:]))
  File "gyp-win-tool", line 29, in main
    exit_code = executor.Dispatch(args)
  File "gyp-win-tool", line 71, in Dispatch
    return getattr(self, method)(*args[1:])
  File "gyp-win-tool", line 179, in ExecLinkWithManifests
    subprocess.check_call(ldcmd + add_to_ld)
  File "c:\Python27\lib\subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'c:\Python27\python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /OUT:openssl-cli.exe @openssl-cli.exe.rsp openssl-cli.exe.manifest.res' returned non-zero exit status 1120
ninja: build stopped: subcommand failed.

**To Reproduce**
Install Visual studio 2017 Community Edition
Build electron as described in the following document 
https://electronjs.org/docs/development/build-instructions-windows

**Comment by MarshallOfSound** [comment]
@ahmedmohamedali Can you clean and rebootstrap?

**Comment by tomexsans** [comment]
Same problem
just followed the building on 
https://electronjs.org/docs/development/build-instructions-windows


it failed on this part

```
D:\electron>python script/build.py
ninja: Entering directory `out\R'
[1199/1221] LINK_EMBED openssl-cli.exe
FAILED: C:\Python27\python.exe gyp-win-tool link-with-manifests environment.x64 True openssl-cli.exe "C:\Python27\python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /OUT:openssl-cli.exe @openssl-cli.exe.rsp" 1 mt.exe rc.exe "obj\vendor\node\deps\openssl\openssl-cli.openssl-cli.exe.intermediate.manifest" obj\vendor\node\deps\openssl\openssl-cli.openssl-cli.exe.generated.manifest
openssl.lib(openssl.ec2_smpl.obj) : error LNK2001: unresolved external symbol _guard_dispatch_icall
openssl-cli.exe : fatal error LNK1120: 1 unresolved externals
Traceback (most recent call last):
  File "gyp-win-tool", line 323, in <module>
    sys.exit(main(sys.argv[1:]))
  File "gyp-win-tool", line 29, in main
    exit_code = executor.Dispatch(args)
  File "gyp-win-tool", line 71, in Dispatch
    return getattr(self, method)(*args[1:])
  File "gyp-win-tool", line 179, in ExecLinkWithManifests
    subprocess.check_call(ldcmd + add_to_ld)
  File "C:\Python27\lib\subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Python27\python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /OUT:openssl-cli.exe @openssl-cli.exe.rsp openssl-cli.exe.manifest.res' returned non-zero exit status 1120
ninja: build stopped: subcommand failed.
```
cleaning and rebootstrap outputs simillar error


Also Installed VS2017
Electron : ^2.0.0
Windows 10

**Comment by jkleinsc** [comment]
2.0.x and earlier require VS2015:
https://github.com/electron/electron/blob/2-0-x/docs/development/build-instructions-windows.md

**Comment by torycl** [comment]
Same problem
Trying to build upgrade-to-chromium-66. I have both VS2015 and VS2017 installed. I have created the card so it can be solved when working on Ch66 update:

https://github.com/electron/electron/projects/10#card-9999971

**Comment by brenca** [comment]
What's the exact version of VisualStudio 2017 you guys have? We have a hunch that 15.7.x has some problems, I can build `2-0-x` with version 15.6.5.

**Comment by torycl** [comment]
15.7.1

**Comment by torycl** [comment]
An now I have tried 15.7.2 and it has the same issue

**Comment by brenca** [comment]
@torycl Can you try installing the Windows10 SDK? That fixed it for @nitsakh

**Comment by jack-teng1** [comment]
In out\R\obj\vendor\node\deps\openssl\openssl-cli.ninja file change the cflags:
/d2guard4 to /guard:cf

I think this flag is configured inside brightray\brightray.gypi

**Comment by torycl** [comment]
Yes, I have tried to change it in brightray.gypi and it worked. @jack-teng1 thank you for info. I have also modified chromium 66 branch.
