### ISSUE TITLE
Exclude a window while performing full screen share

### ISSUE THREAD

**Issue by Ajeey** [electron/electron#12973]
**Is your feature request related to a problem? Please describe.**
I have implemented full screen sharing using https://electronjs.org/docs/api/desktop-capturer#desktopcapturer
and once I successfully get the MediaStream object, I create a new *always on top browserWindow* which is draggable to indicate that the current screen is being shared.
Something like this -
<img width="614" alt="screen shot 2018-05-17 at 12 35 19 pm" src="https://user-images.githubusercontent.com/1799117/40161576-dbf8ff46-59ce-11e8-91a2-aa8a600c74ff.png">

Now the problem is even this newly created “browserWindow” is being shared since it is a full screen sharing.

**Describe the solution you'd like**
Ability to exclude a window (newly created browserWindow in my case) while doing full screen share

**Additional context**
When we do screen sharing in chrome or in node-webkit, the newly created is not shared to other endpoints. I know in electron the screen sharing module is not exactly as same as chromium's screen picker implementation. More details here - https://github.com/electron/electron/issues/1380

Because of the above implementation seems like this is a limitation in Electron specific screen share.

Any options or thoughts on how to solve this?

**Comment by mikeykhalil** [comment]
IIRC, enabling content protection through the `setContentProtection` method allowed us to achieve the ability to exclude browser windows while screen sharing for Mac OS.

However, I do not think this trick worked on Windows. For our application, we just enabled `setContentProtection` on Mac OS and designed the floating screen share indicator to be a bit smaller.

We were using Electron 1.7.X and we never revisited the issue, so this information might be kind of stale.

**Comment by CapOM** [comment]
Mac: `NSWindowSharingNone` https://github.com/electron/electron/blob/master/atom/browser/native_window_mac.mm#L1023

Windows: `SetWindowDisplayAffinity`
https://github.com/electron/electron/blob/master/atom/browser/native_window_views.cc#L852

On Windows it is kind of working but you will actually see a black rectangle on the remote end. Not sure if this is expected or not.

**Comment by CapOM** [comment]
@ajmacd Since you worked on https://github.com/electron/electron/pull/12417 do you think we could use webrtc::DesktopCapturer::SetExcludedWindow(winId) instead of current electron implementation for `setContentProtection ` ?

I see two issues with that, first I think this will still render black window instead of what is drawn behind. 

And second issue is that the capturer instances are not the same when actually doing the capture than those created in electron::atom::api::DesktopCapturer::StartHandling (no singleton compared to what you used with `webrtc::DxgiDuplicatorController::Instance()->GetDeviceNames` ) so I guess there is no way to call SetExcludedWindow from electron (unless patching chromium/webrtc somehow)

Any thought ?

**Comment by ajmacd** [comment]
We have the same problem in Slack screen sharing. @CapOM the API you reference does exactly what we want and in fact is used by Chrome to exclude the warning window that @Ajeey is trying to emulate in Electron.

The second issue you raise is the problem. The `DesktopCapturer` instance we employ in Electron is not the one handling the capturing in Chrome. The only way to do this would be to expose the API to JS through patching getUserMedia (not a light undertaking) or patching a global override hack that we set from Electron.

_Even worse_ though, is that this feature isn't supported by the newer DirectX capturer on Windows that's now used by default, only the Magnifier capturer:
https://cs.chromium.org/chromium/src/third_party/webrtc/modules/desktop_capture/win/screen_capturer_win_magnifier.cc?q=setexcludedwindow&l=136

You can verify this by trying screen sharing in a recent Chrome on Windows (using say Hangouts). The remote end will see the warning window. So we'd additionally need to patch Chrome to use the Mag capturer, which would have performance implications at the least.

**Comment by momakes** [comment]
It'd be a really awesome feature, is there any change this might be built as of now with newer versions?

**Comment by masudhossain** [comment]
bump? Any solution for windows?

**Comment by BenRussert** [comment]
> Windows: `SetWindowDisplayAffinity`
> https://github.com/electron/electron/blob/master/atom/browser/native_window_views.cc#L852
> 
> On Windows it is kind of working but you will actually see a black rectangle on the remote end. Not sure if this is expected or not.

Does anyone have insight on what the limitation was for Windows? Was `SetWindowDisplayAffinity` the only feasible option or is it just something that needs to be explored further? 

If it could be explored further, is there any background info that could help a potential contributor who wanted to make this work like it does Mac?

**Comment by BenRussert** [comment]
Check out this PR I've opened to address this for Windows 10 version 2004 and up.

https://github.com/electron/electron/pull/24274

**Comment by deermichel** [comment]
As discussed, the explained behavior can be achieved via [`BrowserWindow.setContentProtection()`](https://www.electronjs.org/docs/latest/api/browser-window#winsetcontentprotectionenable-macos-windows) on macOS & Windows. There is no support for Linux due to lack of required functionality within X11.

**Comment by jaydeep-agami** [comment]
> As discussed, the explained behavior can be achieved via [`BrowserWindow.setContentProtection()`](https://www.electronjs.org/docs/latest/api/browser-window#winsetcontentprotectionenable-macos-windows) on macOS & Windows. There is no support for Linux due to lack of required functionality within X11.

Any update for Linux or workaround to do this ?
