### ISSUE TITLE
Bug in App with disableHardwareAcceleration()

### ISSUE THREAD

**Issue by cawa-93** [electron/electron#12978]
* Electron Version: 2.0.1
* Operating System (Platform and Version): macOS 10.13.4 (17E202)

If I use `app.disableHardwareAcceleration()` content is not displayed correctly

**Actual behavior**
It's hard for me to describe what exactly is happening. Watch the video below

**To Reproduce**

1. Run app:
```sh
$ git clone https://github.com/cawa-93/electron-quick-start/commits/master -b master
$ npm install
$ npm start
```
2. Try scroll

**Videos**
Expected Behavior:
[![Expected Behavior video](http://img.youtube.com/vi/grX9GUaItgY/0.jpg)](http://www.youtube.com/watch?v=grX9GUaItgY)

Actual behavior:
[![Expected Behavior video](http://img.youtube.com/vi/37_sW_y2j1E/0.jpg)](http://www.youtube.com/watch?v=37_sW_y2j1E)

**Additional Information**
Apple MacBook Pro 15 2016 (MLH42)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
