### ISSUE TITLE
Allow passing Array by reference over IPC 

### ISSUE THREAD

**Issue by wspl** [electron/electron#12970]
**Is your feature request related to a problem? Please describe.**

I'm working on a React-based state management library on Electron environment, but it's difficult to update the array which is passed from main process and copied by IPC in renderer process.

Sorry, this sentence may not be very clear, you can refer to #12707

**Describe the solution you'd like**

Provide a option like `{ ...ipcPassingArrayByReference: true }` as a global option.

**Describe alternatives you've considered**

Update data through a method in the main process.

**Comment by MarshallOfSound** [comment]
This is not technically possible, the processes to not share memory so it is impossible to pass a reference to an arrat across processes.  You should do custom ipc wiring and proxy objects to achieve what you want

**Comment by wspl** [comment]
@MarshallOfSound Thank you for your quick response.
I have tried to pass a proxy from the main process to the renderer process.
If it passes `new Proxy([] {...})`, ipc seems to think that I passed an Array, so what I actually get in the renderer process is still a copied raw array.
If I passes `new Proxy({}, {...})`, treat `{}` as a array. All array methods are not accessible. It seems that ipc also intercepts these things. But if in same process, my code can work:
```javascript
const real = []

const proxy: any = new Proxy({}, {
  get: (_, property) => Reflect.get(real, property),
  set: (_, property, value, receiver) => Reflect.set(real, property, value, receiver),
  deleteProperty: (_, property) => Reflect.deleteProperty(real, property),
  enumerate: (_) => Array.from(Reflect.enumerate(real)),
  ownKeys: (_) => Reflect.ownKeys(real),
  has: (_, property) => Reflect.has(real, property),
  defineProperty: (_, property, descriptor) => Reflect.defineProperty(real, property, descriptor),
  getOwnPropertyDescriptor: (target, property) => {
    let descriptor = Object.getOwnPropertyDescriptor(real, property)
    if (descriptor) {
      descriptor.value = real[property]
      Reflect.defineProperty(target, property, descriptor)
    }
    return descriptor
  }
})

proxy.push(1)
console.log(proxy.join(','))

proxy.push(2)
console.log(proxy.join(','))

proxy.push(3)
console.log(proxy.join(','))
```

**Comment by MarshallOfSound** [comment]
@wspl You should ask these questions in slack or on the community but the TLDR is all things sent over IPC are stringified.  If you want to be able to maniuplate data across process you will need to set up some kind of IPC message logic to "request" the manipulation in the source process
