### ISSUE TITLE
now, frameless transparent windows can't bigger  than 64x64 on Windows v2.0.1

### ISSUE THREAD

**Issue by zjruan** [electron/electron#12989]
* Electron Version: v2.0.1
* Operating System (Platform and Version): windows10
* Last known working Electron version: 1.7.9

Allow frameless transparent windows to be sized smaller than 64x64 on Windows #12923

but，now, it can't bigger than 64x64 on Windows
my `height/width` don't work
when i set `frame: true`, it can't resize
remove `transparent: true`, all work right
![2018-05-18 11_14_17](https://user-images.githubusercontent.com/12164900/40214332-aac2815e-5a8c-11e8-8aa1-38ec2a427e0a.gif)

**Comment by MarshallOfSound** [comment]
@miniak I think you recently PR'ed something in around this

**Comment by brenca** [comment]
@MarshallOfSound nope, that was me, let me check

**Comment by tEgRaT** [comment]
I got exactly the same problem. 
My app has a frameless transparent window. 
At 2.0.0, everything was fine, but after updated to 2.0.1, my window is only 64X64 and cannot be resized.
