### ISSUE TITLE
DesktopCapturer / getUserMedia TrackStartError, Windows 10, External Monitor

### ISSUE THREAD

**Issue by jordanbaucke** [electron/electron#12985]
- Electron Version: 2.0.1

- Operating System (Platform and Version): Window 10

- Last known working Electron version:  ?

**Expected Behavior**

Passing `deviceId` returned from `desktopCapturer.getSources` to `navigator.mediaDevices.getUserMedia` should return video track. 

**Actual behavior**

A clear and concise description of what actually happened.
When working on Windows 10 machine + external monitor, a call to `desktopCapturer.getSources({ types:['screen']})` returns two sources: `screen:0:0` and `screen:1:0`, this is expected. 

When I call:
```
navigator.mediaDevices.getUserMedia({
    audio: false,
    video: {
      mandatory: {
        chromeMediaSource: 'desktop',
        chromeMediaSourceId: 'screen:1:0`
      }
    }
  }, gotStream, getUserMediaError);
```

I get an error: `TrackStartError`,  Subsequent calls to  `desktopCapturer.getSources({ types:['screen']})` no long return two results, but just 1, the failed device (confirmed by the preview) is now `device:0:0`, and subsequent calls to `getUserMedia` using `device:0:0` do not return an error.

If I initially call:

```navigator.mediaDevices.getUserMedia({
    audio: false,
    video: {
      mandatory: {
        chromeMediaSource: 'desktop',
        chromeMediaSourceId: 'screen:0:0`
      }
    }
  }, gotStream, getUserMediaError);
```

I get a `MediaStream` object as expected, but it is capturing the wrong screen. 

**To Reproduce**
Your best chance of getting this bug looked at quickly is to provide a REPOSITORY that can be cloned and run.

- Windows 10 laptop (I am able to reproduce on a laptop that primary bezel resolution is 2160p, and external display (over HDMI) is 1080p.
- GPU: Intel HD Graphics 630, NVIDIA GeForce GTX 1050 Ti
- Clone and download "example" desktop capturer https://github.com/hokein/electron-sample-apps, run `electron .\desktop-capture`

```sh
$ git clone https://github.com/hokein/electron-sample-apps
$ cd electron-sample-apps
$ npm install -g electron
$ electron .\desktop-capture\
```

**Screenshots**
![selected](https://user-images.githubusercontent.com/354791/40206417-dcbf0644-59e4-11e8-93e3-f0acc84586b2.png)

![trackstarterror](https://user-images.githubusercontent.com/354791/40206443-f4fbd8d6-59e4-11e8-8165-e1007fead0aa.png)

![restart-no-screen](https://user-images.githubusercontent.com/354791/40206456-0146c61e-59e5-11e8-8c3a-98114eca771b.png)

**Additional Information**

**This error does not occur if one of the external display adapters is set as "main window" in the Windows display properties.**

I am able to reproduce this error on desktop machines running the same versions of the Windows 10, with external displays. I am able to confirm on Alienware / MSI laptops configured with NVidia GTX 1050 Ti

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by jordanbaucke** [comment]
@sofianguy 

Since the bug wasn't touched for OVER A YEAR I have no idea if it's still valid. I am no longer working on the project, but I can recheck. If anyone is still experiencing they can re-open- though doesn't seem like electron team is doing a very good job maintaining their tickets.

Jordan
