### ISSUE TITLE
"Flaky" handling of x-axis wheel scroll events

### ISSUE THREAD

**Issue by TAGC** [electron/electron#12997]
* Electron Version: 2.0.1
* Operating System (Platform and Version): Windows 10 Pro v1803
* Last known working Electron version: N/A

**Expected Behavior**

When I register a `wheel` event listener to an element and push my mousewheel left and right while hovering over it, the `deltaX` property on the event should consistently be a non-zero value that reflects the direction I pushed the mousewheel in.

**Actual behavior**

The `deltaX` property values are "flaky"; sometimes they're correct but often they appear as 0 or -0. This does not happen with identical code running in a normal browser.

**To Reproduce**

This should be reproducible by adding an event handler for `wheel` events to any element that logs the events to console. Compare the behaviour between the application running in Electron and a regular browser.

In my case, I quickly generated a simple Vue project:

1. `npm i -g @vue/cli` (>=3.0.0-beta.10)
2. `vue create temp && cd temp` (default settings)
3. `vue add electron-builder` (no typescript support)
4. Change `App.vue` to contain this:

```html
<template>
  <div id="app" @wheel="handleWheel">
    <img src="./assets/logo.png">
    <HelloWorld msg="Welcome to Your Vue.js App"/>
  </div>
</template>
```

```js
<script>
import HelloWorld from './components/HelloWorld.vue'

export default {
  name: 'app',
  components: {
    HelloWorld
  },
  methods: {
    handleWheel(e) {
      console.log(e.deltaX)
    }
  }
}
</script>
```

5. Run `npm run serve:electron` and `npm run serve` to launch the app as an Electron and standard browser application respectively, while scrolling left and right and observing the console outputs.

**Screenshots**

In the GIF below, the Electron and Firefox console report `event.deltaX` for `wheel` events:

![2018-05-18_12-38-13](https://user-images.githubusercontent.com/1588951/40233001-11d711a0-5a99-11e8-88f1-80f9737f0624.gif)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
