### ISSUE TITLE
Wrong maximize() / setPosition(x, y) behavior on Windows 10 Build 1806 on frameless mode

### ISSUE THREAD

**Issue by happypoulp** [electron/electron#12996]
* Electron Version: 1.7.15 / 1.8.7 / 2.0.1
* Operating System (Platform and Version): Windows 10 **Build 1806**
* Last known working Electron version: none

**Expected Behavior**
Calling `window.setPosition` **AFTER** `window.maximize` on a **frameless window** should not have any effect on the window.

**Actual behavior**
Calling `window.setPosition` **AFTER** `window.maximize` on a **frameless window** display a grey top bar above the window.

**To Reproduce**
The issue can be reproduced on https://github.com/happypoulp/electron-api-demos on the branch **maximize-issue-windows-1806**.

Build and run `npm start`. The demo app will start in frameless mode and on event `did-finish-load` of window.webcontents, the window is maximized and set setPosition(0, 0) is called (see https://github.com/happypoulp/electron-api-demos/commit/13c9df9d7610be28207245e755f826c545776517 at comment ISSUE n.1).

**Screenshots**

![issue 1 - top grey bar](https://user-images.githubusercontent.com/100044/40227852-ed392166-5a8f-11e8-9ee0-fd2dd6cf4476.png)

**Additional Information**

This maximize / setPosition issue appeared with the latest (at the time of writing of this issue) build of Windows 10: **Build 1806**.

Even though it doesn't make any sense to call setPosition after calling maximize I think this issue worth a look because it may be symptomatic of something broken in electron since Windows 10 Build 1806.

Note also that the repo I provide to reproduce the issue, also highlights another issue related to maximize / restore that is already reported here: https://github.com/electron/electron/issues/12971 (this second issue is called the ISSUE n.2 (clicking multiple time on maximize / restore yield an inconsistent result on window size and a blank top bar is also appearing in this case).

Thanks!

**Comment by NearAutomata** [comment]
This issue occurs with various know Electron based applications such as Slack, Spotify, Streamlabs OBS and Discord. What is weird however, that you can continue to maximize and restore those Windows and they will bug out every other time alternating between expected and wrong behaviour.

**Comment by timfish** [comment]
This (and #12971) also occur with Spotify which is not an Electron app.

**Comment by NearAutomata** [comment]
@timfish Spotify is based on Chrome or CEF, isn't that right?

**Comment by timfish** [comment]
As far as I know yes

**Comment by jez9999** [comment]
> What is weird however, that you can continue to maximize and restore those Windows and they will bug out every other time alternating between expected and wrong behaviour.

Yes, this is exactly the issue I have with the Windows Slack client.  Rather annoying.  Any ideas why this is happening yet?

**Comment by NearAutomata** [comment]
Lately this issue is no longer occurring with Spotify and Electron, unfortunately though I don't know whether Windows received a fix or CEF in the first place.

**Comment by petternilsen** [comment]
The latest Windows 10 1803 update released about a month ago fixed it for all chromium-based apps.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
