### ISSUE TITLE
Module name error when calling *app.stop()*

### ISSUE THREAD

**Issue by aemengo** [electron/electron#13004]
* Electron Version: `2.0.0`
* Operating System (Platform and Version): `macOS High Sierra, version: 10.13.4`
* Last known working Electron version: `~`

**Expected Behavior**
Calls to `app.stop()` should cleanly stop our application during long test runs. 

**Actual behavior**
We see a module error in the after block of our test runs. The app never stops and the mocha runner hangs indefinitely. Our code is similar to the electron-api-demos teardown.

```
  after(() => {
    if (app && app.isRunning()) {
      return app.stop();
    }
  });
```

**To Reproduce**
Run a test that has the browser waiting on a condition that takes a long time. Like below:
```
const Application = require('spectron').Application;
const electron = require('electron');
const path = require('path');

const chai = require('chai');
const chaiAsPromised = require('chai-as-promised');

chai.should();
chai.use(chaiAsPromised);

describe('app', () => {

  let app;

  before(() => {
    app = new Application({
      path: electron,
      args: [
        path.join(__dirname, '..'),
      ],
      waitTimeout: 50000,
    });
    chaiAsPromised.transferPromiseness = app.transferPromiseness;
    return app.start();
  });

  after(() => {
    if (app && app.isRunning()) {
      return app.stop();
    }
  });

  it('launches app with a loading page', () => {
    return app.client.pause(30000).then(function () {
      return (3).should.equal(3)
    })

  }).timeout(90000);
});
```

**Screenshots**

![screen shot 2018-05-18 at 2 45 01 pm](https://user-images.githubusercontent.com/4236888/40252427-49d71792-5aaa-11e8-9a47-8528f2dd4cc0.png)

**Additional Information**
When the wait isn't long, the test work fine.

@tisvictress

**Comment by codebytere** [comment]
hi @aemengo,`RequireJS` doesn't currently support Electron. In addition, `app.stop()` is not a method that currently exists on `app` per [docs](https://github.com/electron/electron/blob/master/docs/api/app.md).
