### ISSUE TITLE
net.request not sending cookie through NTLM proxy

### ISSUE THREAD

**Issue by ahmedmohamedali** [electron/electron#13002]
* Electron Version: 1.7.x and 2.0.x
* Operating System (Platform and Version): Windows 7 Professional
* Last known working Electron version: 

**Expected Behavior**
When the request goes through a NTLM proxy,  cookies set with request.setHeader() or in the constructor options should be sent to the server

**Actual behavior**
The cookie is not sent. This observable also with Fiddler

**To Reproduce**
1) Configure the system proxy with the  NTLM address and port
1) Start Fiddler
3) Create and launch a app doing abasic request with a cookie
const request = net.request('some_url');
request.setHeader('Cookie', 'Mycookie=SomeValue')
....
 request.end()
4) Observer in fiddler there is no Cookie

**Additional Information**
If there is no proxy, the cookies are sent as expected.
Works fine with session cookies if this change https://github.com/electron/electron/issues/8223 is reverted

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
