### ISSUE TITLE
Electron should also be an editor and the Windows build instructions should look like this:

### ISSUE THREAD

**Issue by eric645** [electron/electron#13011]
# Build Instructions (Windows)

Follow the guidelines below for building Electron on Windows.

## Prerequisites

* Windows 7 / Server 2008 R2 or higher
* Visual Studio 2017 - [download VS 2017 Community Edition for
  free](https://www.visualstudio.com/vs/)
* [Python 2.7](http://www.python.org/download/releases/2.7/)
* [Node.js](https://nodejs.org/download/)
* [Git](http://git-scm.com)
* [Debugging Tools for Windows](https://msdn.microsoft.com/en-us/library/windows/hardware/ff551063.aspx)
  if you plan on creating a full distribution since `symstore.exe` is used for
  creating a symbol store from `.pdb` files.
* [VS Code](

If you don't currently have a Windows installation,
[dev.microsoftedge.com](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)
has timebombed versions of Windows that you can use to build Electron.

Building Electron is done entirely with command-line scripts and cannot be done
with Visual Studio. You can develop Electron with any editor.

On Visual Studio, to build Electron **requires** a Visual Studio project containing all the code.

On VS Code, you can open all the files and then use the Build option of the Go menu.

**Note:** Even though Visual Studio is not used for building, it's still
**required** because we need the build toolchains it provides.

## Getting the Code

```powershell
$ git clone https://github.com/electron/electron.git
```

## Bootstrapping

The bootstrap script will download all necessary build dependencies and create
the build project files. Notice that we're using `ninja` to build Electron so
there is no Visual Studio project generated.

```powershell
$ cd electron
$ python script\bootstrap.py -v
```

## Building

Build both Release and Debug targets:

```powershell
$ python script\build.py
```

You can also only build the Debug target:

```powershell
$ python script\build.py -c D
```

After building is done, you can find `electron.exe` under `out\D` (debug
target) or under `out\R` (release target).

## 32bit Build

To build for the 32bit target, you need to pass `--target_arch=ia32` when
running the bootstrap script:

```powershell
$ python script\bootstrap.py -v --target_arch=ia32
```

The other building steps are exactly the same.

## Visual Studio project

To generate a Visual Studio project, you can pass the `--msvs` parameter:

```powershell
$ python script\bootstrap.py --msvs
```

## Cleaning

To clean the build files:

```powershell
$ npm run clean
```

To clean only `out` and `dist` directories:

```sh
$ npm run clean-build
```

**Note:** Both clean commands require running `bootstrap` again before building.

## Tests

See [Build System Overview: Tests](build-system-overview.md#tests)

### Command xxxx not found

If you encountered an error like `Command xxxx not found`, you may try to use
the `VS2015 Command Prompt` console to execute the build scripts.

### Fatal internal compiler error: C1001

Make sure you have the latest Visual Studio update installed.

### Assertion failed: ((handle))->activecnt >= 0

If building under Cygwin, you may see `bootstrap.py` failed with following
error:

```sh
Assertion failed: ((handle))->activecnt >= 0, file src\win\pipe.c, line 1430

Traceback (most recent call last):
  File "script/bootstrap.py", line 87, in <module>
    sys.exit(main())
  File "script/bootstrap.py", line 22, in main
    update_node_modules('.')
  File "script/bootstrap.py", line 56, in update_node_modules
    execute([NPM, 'install'])
  File "/home/zcbenz/codes/raven/script/lib/util.py", line 118, in execute
    raise e
subprocess.CalledProcessError: Command '['npm.cmd', 'install']' returned non-zero exit status 3
```

This is caused by a bug when using Cygwin Python and Win32 Node together. The
solution is to use the Win32 Python to execute the bootstrap script (assuming
you have installed Python under `C:\Python27`):

```powershell
$ /cygdrive/c/Python27/python.exe script/bootstrap.py
```

### LNK1181: cannot open input file 'kernel32.lib'

Try reinstalling 32bit Node.js.

### Error: ENOENT, stat 'C:\Users\USERNAME\AppData\Roaming\npm'

Creating that directory [should fix the problem](https://stackoverflow.com/a/25095327/102704):

```powershell
$ mkdir ~\AppData\Roaming\npm
```

### node-gyp is not recognized as an internal or external command

You may get this error if you are using Git Bash for building, you should use
PowerShell or VS2015 Command Prompt instead.

### bash: python: command not found
This error is caused by Git Bash and Python when BCB (always included with Visual Studio 2015, optional on VS 2016, 2014, 2012, and 2017) unloads Python 2.7.
Fix this error by typing the following in Git Bash:
`npm fix python -f`
and then running Visual Studio.

**Comment by ckerr** [comment]
diff:

```diff
--- build-instructions-windows.md	2018-05-15 14:01:30.654064034 -0500
+++ build-instructions-windows-2.md	2018-05-21 09:02:33.410899846 -0500
@@ -13,14 +13,19 @@
 * [Debugging Tools for Windows](https://msdn.microsoft.com/en-us/library/windows/hardware/ff551063.aspx)
   if you plan on creating a full distribution since `symstore.exe` is used for
   creating a symbol store from `.pdb` files.
+* [VS Code](
 
 If you don't currently have a Windows installation,
 [dev.microsoftedge.com](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)
 has timebombed versions of Windows that you can use to build Electron.
 
 Building Electron is done entirely with command-line scripts and cannot be done
-with Visual Studio. You can develop Electron with any editor but support for
-building with Visual Studio will come in the future.
+with Visual Studio. You can develop Electron with any editor.
+
+On Visual Studio, to build Electron **requires** a Visual Studio project containing all the code.
+
+
+On VS Code, you can open all the files and then use the Build option of the Go menu.
 
 **Note:** Even though Visual Studio is not used for building, it's still
 **required** because we need the build toolchains it provides.
@@ -153,3 +158,10 @@
 
 You may get this error if you are using Git Bash for building, you should use
 PowerShell or VS2015 Command Prompt instead.
+
+### bash: python: command not found
+This error is caused by Git Bash and Python when BCB (always included with Visual Studio 2015, optional on VS 2016, 2014, 2012, and 2017) unloads Python 2.7.
+Fix this error by typing the following in Git Bash:
+`npm fix python -f`
+and then running Visual Studio.
+
```

**Comment by ckerr** [comment]
There are a couple of things here, some of which I understand and agree with, and some which I don't understand yet.

 1. Adding a FAQ entry for `bash: python: command not found` sounds reasonable
 2. Adding a link to VS Code -- is this already covered by the https://www.visualstudio.com/vs/ link?
 3. "Electron should also be an editor" -- I don't understand. Could you add some detail / rationale to this proposal?

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
