### ISSUE TITLE
Transparent Window sizing issues

### ISSUE THREAD

**Issue by fawadtariq** [electron/electron#13019]
* Electron version: 2.0.1
* Operating system: Windows 10 Home

### Expected behavior

When I set `transparent: true` in the `BrowserWindow` object, it should not display the white clutter (shown below) outside my html container because i've set;
`html, body {
  background: rgba(0, 0, 0, 0);
}`

![image](https://user-images.githubusercontent.com/18026360/40307354-87b604ec-5d1b-11e8-871f-26e9c105adfd.png)

### Actual behavior

Instead, when I set `transparent: true` the  `BrowserWindow` behaves abnormally and produces the following result;

![image](https://user-images.githubusercontent.com/18026360/40307415-d244d93e-5d1b-11e8-814f-a4e624bbd48a.png)

The Window gets smaller and is no longer re-sizable. I've tried everything I could look up. Help is immensely appreciated.
### How to reproduce
**HTML**
```
`<body>
   <div class="container">
     Lorem ipsum, dolor sit amet consectetur adipisicing elit. Laudantium ab nihil officia obcaecati sunt unde aspernatur, illo et nostrum consequatur ea itaque porro delectus repudiandae dolorum labore, molestiae minus sint.
   </div> 
</body>`
```
**CSS**
```
`html, body {
  background: rgba(0, 0, 0, 0);
}
.container
{
  width: 90vw;
  height: 90vh;
  position: absolute;
  top: 5vh;
  left: 5vw;
  border-radius: 20px;
  background-color: #eeeeee;
  box-shadow: 2px 2px 2px black;
}`
```
**JS**

```
const {app, BrowserWindow} = require('electron');
const path = require('path');

var win;

app.on('ready', function(){
    console.log('ready');
    win = new BrowserWindow({transparent: true , width: 300, height: 500, frame: false, show: false});
    win.loadURL(path.join("file://" + __dirname + "/views/login.html"));
    console.log('load');
    win.show();
})
````

I hope someone helps.

**Comment by MarshallOfSound** [comment]
Duplicate #12989
