### ISSUE TITLE
manage he display of two "browser window"

### ISSUE THREAD

**Issue by markosii** [electron/electron#13017]
Hi,

I have two applications developed with Electron, each one is a "browser window".

I'm looking for an idea to develop a third app in Electron which allows to 1/ display only one of the two applications,  with 2/ the possibility to switch from an application to the another.

It can be a third application or only a way to manage the two applications.

Is that possible with Electron?

Thank you

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
