### ISSUE TITLE
xorg-server-xwayland-1.20.0-2 breaks electron development

### ISSUE THREAD

**Issue by burningTyger** [electron/electron#13012]
* Electron Version: 2+
* Operating System (Platform and Version): Arch Linux 
* Last known working Electron version: --

**Expected Behavior**
Electron app starts as expected

**Actual behavior**
After about 10 seconds the app stalls and nothing happens. No spikes in CPU, memory or anything else to see

**To Reproduce**
Upgrade to xorg-server-xwayland-1.20.0-2

**Additional Information**
I updated from xorg-server-xwayland 1.19.6+13+gd0d1a694f-2 to 1.20 and it broke my app. I thoroughly tested all other packages, this is the one I pinpointed.

If this is the wrong tracker please let me know where to post else. Other electron apps like vs code dont seem to be affected on my system. Chrome also works just fine.

**Comment by devyaz** [comment]
any solution yet? there's no error output the command just exits but if you do 
``` electron .``` in terminal app launches alright. but it seem not to run from script ```npm start``` or ```npm run dev``` even using yarn the result is the same

**Comment by burningTyger** [comment]
none that I know of. I blocked all updates since 1.19.6. I did try 1.21 a couple of days ago but it still breaks.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by burningTyger** [comment]
I have a fresh install with basically the identical setup and it doesn't reappear. On the original machine the issue remains. Probably some misconfiguration that has nothing to do with electron directly.
