### ISSUE TITLE
when i use file protocol in electron, the url of ajax request is going wrong

### ISSUE THREAD

**Issue by chenyihao2621023** [electron/electron#13016]
In the production environment, i use file protocol 
```js
 // main.js
 const winURL = process.env.NODE_ENV === 'development'
  ? `http://localhost:8080`
  : `file://${__dirname}/index.html`
  mainWindow.loadURL(winURL)

 // api.js 
  export function loginByUsername(username, password) {
  const data = {
    username,
    password
  }
  return request({
    url: '/ntwechat/login/login',
    method: 'get',
    params: {
      name: username,
      password: password
    }
  })
}
```
 The ajax request is going to be file:///D:/ntwechat/login/login?name=nt&password
 I know i should provide the full of url path, but the workload is particulary heavy,so i use the seesion module of electron.
```js
const {session} = require('electron')
session.defaultSession.webRequest.onBeforeRequest(filter, (details, callback) => {
   
    details.url = details.url.replace(/.*\/ntwechat\//ig, 'http://localhost:8080/ntwechat/')

    callback({cancel: false, url: details.url});
  })
```
But it can't customize the request url, I am searching for a long time on net. But no use. Please help or try to give some ideas how to achieve this,can you give me some feasible suggestion?thx

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by MarshallOfSound** [comment]
Request `/ABC` will always use the current `origin` before the first `/` of the path.  You should just provide your own hostname before that path, don't try to intercept request URL's in flight
