### ISSUE TITLE
Globalshortcut is swallowing original input from happening

### ISSUE THREAD

**Issue by damianobarbati** [electron/electron#13010]
Versions: 
```
MacOS High Sierra
Node v8.9.3 
Chromium v61.0.3163.100 
Electron v2.0.1
```

**Expected Behavior**
Do not swallow original event if `return true` in handler.

**Actual behavior**
Event is swallowed: if I register pressing letter "w" and "w" is pressed then "w" is not typed anymore in the system because Electron intercept it.
Very troublesome when trying to watch/log events on the system without bothering the user.
i.e: developing an "active" checker monitor listening to mousemove/keyup events.

**Code**

```
const path = require('path');
const url = require('url');
const { BrowserWindow, app, ipcMain, globalShortcut } = require('electron');
const electronReload = require('electron-reload');

// keep a global reference of the window object otherwise the window will be closed automatically when the JavaScript object is garbage collected.
let window;

electronReload(__dirname);

const createWindow = () => {
    window = new BrowserWindow({ width: 350, height: 500 });

    window.loadURL(url.format({
        pathname: path.join(__dirname, 'index.html'),
        protocol: 'file:',
        slashes: true,
        icon: './logo.png',
    }));

    window.webContents.openDevTools()

    window.on('closed', () => {
        // usually you would store windows in an array if your app supports multi windows; here you should delete the corresponding element.
        window = null
    });
};

const trackUserInputs = () => {
    const { screen } = require('electron');
    const display = screen.getAllDisplays()[0];

    let lastMousePosition;

    setInterval(() => {
        const { x, y } = screen.getCursorScreenPoint();
        const currentMousePosition = `${x}-${y}`;
        if(lastMousePosition != currentMousePosition)
            console.log('mousemove');
        lastMousePosition = currentMousePosition;
    }, 500);

    const keyUpHandler = globalShortcut.register('w', () => {
        console.log('keyup');
    });
};

const main = () => {
    createWindow();
    trackUserInputs();
};

// electron is ready to create browser windows
app.on('ready', main);

// quit when all windows are closed
app.on('window-all-closed', () => {
    // on macOS stay active until the user quits explicitly with Cmd + Q
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

app.on('will-quit', () => {
    globalShortcut.unregisterAll();
});

// on macOS re-create a window in the app when the dock icon is clicked and there are no other windows open
app.on('activate', () => {
    if (window === null) {
        createWindow();
    }
});
```

**Comment by MarshallOfSound** [comment]
This behavior was explained in detail by me in a previous issue

https://github.com/electron/electron/issues/8491#issuecomment-274790124

**Comment by damianobarbati** [comment]
Thanks @MarshallOfSound!

My problem is actually different: I don't want to detect keypress on a specific window but on the host system, and the globalShortcut does just that! 
But I'd like to have it not swallow the event.

Can you suggest me anything or any practice to achieve what I'd like to do?

**Comment by MarshallOfSound** [comment]
@damianobarbati What you are describing is a key logger 😉

**Comment by damianobarbati** [comment]
@MarshallOfSound yes, it's an *I'm online and active right now so send me work to do* daemon to send jobs to consultants in real-time, I actually don't care about the key typed but just the event.
But having just the first one seems not possible 😔

Not helping me just means not helping some (actually lots of) freelancers to work 😊

I thank you anyway for answering me and for your efforts in this project, I'll just stick to `iohook`.

Keep up the good work 💪🏻

**Comment by Slapbox** [comment]
@MarshallOfSound is there any way in your mind to make this feature available in a way that is safe for end users? Perhaps only allowing for listening of keys with modifiers (besides `Shift`).  

Another (much less robust) protection would be to hard-code a limit to the number of keys you can listen to in this fashion to prevent a "blank check" scenario. In this vein, Chrome allows only 4 hotkeys to be registered last I checked.

There are no doubt a lot of legitimate uses for this, but I certainly understand (and fear) the possibility of widespread abuse. 

For example, I'd like to listen for `Ctrl+C` and Ctrl+V` and interact with the user's clipboard in certain cases, without just monitoring the clipboard non-stop. Of course, as it stands now a `Ctrl+C` global shortcut would block the `Copy` event.

Any thoughts on this? I'd love the possibilities this would open up if it could be done safely. Right now the only option I see to work around this would be to hook into something like AutoHotkey, and I'm not sure even that clunky method would be workable.
