### ISSUE TITLE
customised browser window

### ISSUE THREAD

**Issue by markosii** [electron/electron#13020]
**Is your feature request related to a problem? Please describe.**

It's a question which can eventually lead to an improvement on "browser window".
Is it possible to create a browser window with width: 200 and height: 100 without "close", "minimize" and "resize" button?

**Describe the solution you'd like**

![capture2](https://user-images.githubusercontent.com/36041989/40308318-232e2d98-5d06-11e8-854f-8d51470cd410.PNG)

 instead of 

![capture1](https://user-images.githubusercontent.com/36041989/40308240-d23fc900-5d05-11e8-931c-61a323c047c5.PNG)

Thank you

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by MarshallOfSound** [comment]
See `frame: false` in BrowserWindow docs

**Comment by markosii** [comment]
thank you
