### ISSUE TITLE
Hi res Looping Video Causing Freezing 

### ISSUE THREAD

**Issue by stevensanborn** [electron/electron#13033]
Basically we are running electron on two 4k monitors spanned desktop in a kiosk mode. 

MAC pro latest  - dual graphics cards dual screen(Dual Fire Pro)  each at 4k resolution  spanned desktop 
PC windows 10 latest  dual graphics cards  dual screen  each at 4k resolution  
1.8.6 but also seen issues in 2.0

We trimmed our app removing all content and  isolated it to only  play 2 looping 4k videos (1 per screen) where we were able to replicate the issue.  The expectation was that the videos, which were set to loop could infinitely play .  The first hour or two always ran without issue. Usually starting at  about 3 hours and then up  to 10 hours on both PC and Mac we would start seeing odd effects. 

the code is literally 2 html <video loop> tags with <source> to a webm video (we also tried h264). 
 positioned side by side. Here are the test [videos ](https://file.town/download/xhudc927frs9ohiu2aebrmkhg). They are about 30 mbs and 20 secs .

  On the mac the result was an eventual  hard freeze. Oddly the entire machine freezes , where nothing works and the only thing you can do is hold power  and restart . On PC the GPU also slowly degrades but seems totake longer eventually resulting in flickering on the screen .  The PC is left in an odd state where even when the app closes, the GPU  is still acts off and get cant get things like webgl contexts when opening basic webgl test pages using the chrome browser.  Only thing to do was hard power on power off to reset the graphics card.

The problem was not replicable on non dual graphics card platforms  or in chrome playing the same videos on a server.  I saw no evidence of  memory bloat or leaks as the app ran.  The url was a **file url** to application support.   All sleep modes were turned off in kiosk mode; screen saver, harddrive, monitor.  Also just playing a single vid as opposed to two did have the same effect , but took longer even longer to replicate.  Also the computers are high end and do not seem to be anywhere near taxed. 

We are forced to gut the looping video for now as the app runs for days straight without it, but I thought id share this bug.

**Comment by samouds** [comment]
Hello, did you manage to fix it ?

**Comment by stevensanborn** [comment]
Never fixed it . Instead we removed video looping over long periods. We replaced with slide show.  We also went PC. Haven’t had any issues since.  There is a potential MAC issue on pro with particular model of graphics card.  This was after discussion with Mac tech that replaced cards for VICE.  This is not the first time I’ve had issues with video on electron.

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR.
