### ISSUE TITLE
HUD AppMenu not working

### ISSUE THREAD

**Issue by andoniu** [electron/electron#13036]
* Electron Version:
master commit 560c0e72e60c1
* Operating System (Platform and Version):

$ uname -a
Linux oandoniu-mobl1.ti.intel.com 4.16.8-300.fc28.x86_64 #1 SMP Wed May 9 20:23:40 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Last known working Electron version: 
- never

**Expected Behavior**
In order for HUD AppMenu to work, at least the following variables must be available: _GTK_MENUBAR_OBJECT_PATH and _GTK_UNIQUE_BUS_NAME

**Actual behavior**
1. open app
2. xprop | grep GTK
3. click on app

**To Reproduce**
Your best chance of getting this bug looked at quickly is to provide a REPOSITORY that can be cloned and run.

You can fork [electron-quick-start](https://github.com/electron/electron-quick-start) and include a link to the branch with your changes.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone $YOUR_URL -b $BRANCH
$ npm install
$ npm start || electron .
```
**Screenshots**

**Additional Information**

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
