### ISSUE TITLE
No pop-up bluetooth device selection box

### ISSUE THREAD

**Issue by Nxir** [electron/electron#13034]
* Electron Version:  2.0.1
* Operating System (Platform and Version):  mac os 10.13.4
* Last known working Electron version: 

**Expected Behavior**
pop-up the bluetooth device selection box

**Actual behavior**
No pop-up bluetooth device selection box
And the console shows the error info 
"Exception NSInvalidArgumentException thrown while decoding IOBluetoothSDPServiceRecord"

**To Reproduce**

0. git clone https://github.com/electron/electron-quick-start

1. Modify the "main.js" file
   Modify the mainWindow.loadURL() method parameter to 
  "https://googlechrome.github.io/samples/web-bluetooth/device-info.html" 

2. npm install && npm start

3. select the "All Devices" checkbox

4. click "Get Bluetooth Device info" button

**Additional Information**
if use the chrome browser to open the url, the Bluetooth device selection box will pop-up

**Comment by codebytere** [comment]
Closing as dup of https://github.com/electron/electron/issues/14050
