### ISSUE TITLE
Desktop notifications are not working in AwesomeWM after 2.0 upgrade

### ISSUE THREAD

**Issue by gch1p** [electron/electron#13035]
* Electron Version: 2.0.1
* Operating System (Platform and Version): Gentoo Linux, Awesome WM
* Last known working Electron version: 1.8.x

**Expected Behavior**
Notifications working.

**Actual behavior**
Desktop notifications in Electron 2.0 are not working in Awesome WM (awesomewm.org). When I'm creating a new Notification object, I see a couple of `libnotify-WARNING **: Failed to connect to proxy` in console and don't see anything in dbus-monitor. Notifications were working perfectly before 2.0 upgrade.

**Comment by sethlu** [comment]
@gch1p Are you working with the HTML5 or the Electron Notification API?

**Comment by gch1p** [comment]
@sethlu the HTML5 API.

**Comment by sethlu** [comment]
@gch1p I don't usually work with Linux; would it be something related to a daemon for notifications that's not running?

**Comment by marcelobcortes** [comment]
I'm experiencing the same issue.
`notify-send summary body`
on terminal works

**Comment by marcelobcortes** [comment]
I have some uncommon warnings too, don't know if it is related

> 
  (electron:10692): libappindicator-WARNING **: 10:51:33.902: Unable to get the session bus: The connection is closed

  (electron:10692): LIBDBUSMENU-GLIB-WARNING **: 10:51:33.902: Unable to get session bus: The connection is closed

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
