### ISSUE TITLE
Two-finger double tap on MacBook touchpad zooms in content

### ISSUE THREAD

**Issue by richardneal** [electron/electron#13045]
* Electron version: Not sure, this repros in the latest versions of Slack and Discord. Apologies if this should go through those channels – my assumption was that this happening across apps is a framework issue.
* Operating system: macOS 10.13.4.

### Expected behavior

Two-finger double tap should do nothing in a Slack or Discord window.

### Actual behavior

Content zooms in.

![screenshot 2018-05-22 23 35 21](https://user-images.githubusercontent.com/1259028/40407318-def24146-5e18-11e8-876f-94d8a737251a.png)
![screenshot 2018-05-22 23 36 04](https://user-images.githubusercontent.com/1259028/40407327-e71961ce-5e18-11e8-9dec-705ca49539a3.png)
(Note that this is the entire Discord window)

### How to reproduce

Two-finger double tap in the content of a Slack or Discord window on Mac.

**Comment by MarshallOfSound** [comment]
This should be raised through those channels.  We have an api (setzoomlevellimits) that prevents this behavior

**Comment by nornagon** [comment]
This behaviour should be disabled by default beginning in Electron 3.0.0. See https://github.com/electron/electron/pull/12679
