### ISSUE TITLE
Window size changes when being moved if resizable is false

### ISSUE THREAD

**Issue by wenjunche** [electron/electron#13043]
* Electron Version: 2.0.0
* Operating System (Platform and Version): Windows 10
* Last known working Electron version: before commit bb5eecc16cff8053c7b04e0b9396803fbbb8c4df

**Expected Behavior**
Width and height of a window should not change while being dragged 

**Actual behavior**
Width and height become smaller.

**To Reproduce**
Create a window with:
  var mainWindow = new BrowserWindow({width: 1024, height: 880, x: 30, y: 30,
            resizable: false })

Then drag the window.  Width and height become smaller than specified (1024, 880)

**Additional Information**
NativeWindowViews::SetBounds calls SetMin/MaxSize(bounds) when resizable_ is false.  bounds get adjusted to smaller  numbers by WindowBoundsToContentBounds.

**Comment by brenca** [comment]
So, just to confirm that we see the same thing - the windows stays visibly the same size, but a bunch of resize events get emitted with sizes that fluctuate between the size that was set and one that's one pixel off (and only when scaling is not 100%)?

**Comment by wenjunche** [comment]
scaling is at 100%.  The window changes size as soon as I drag it.

When I run the example I listed earlier, the followings are what I see in devtools->console

Before I move the window:

window.outerHeight
880
window.outerWidth
1024

After I move the window

window.outerHeight
851
window.outerWidth
1018

**Comment by wenjunche** [comment]
same issue with 2.0.2

Here my repo: https://github.com/wenjunche/electron-13043

**Comment by brenca** [comment]
Are you using the non-detached devtools? If so, I think I know what you mean.

**Comment by incomingstick** [comment]
I would like to add that I am seeing the same issue. We use not attached dev tools as well, however this is also reproducible on an electron-forge binary build of our app as well (which obviously does not open the dev tools), so I do not know if that is a cause.

My app starts at a size of 846x478 and upon dragging only the first time after the app has opened it becomes 840x449. Which happens to be the exact loss of 6x29 as seen above. Our repo is unfortunately private, so I cannot share the link. Please let me know what information you may need from me.

We are using electron version 2.0.2 and I am on Windows 10 version 1709 (OS Build 16299.371)

**Comment by jahraphael** [comment]
I wanted to follow up to what @incomingstick with a couple more things:
- We only see this on Windows. OSX is not exhibiting the behavior, and we don't make Linux builds of our app.
- While the source is currently in a private repo, you can download a built version of the app here to see the problem: https://github.com/RaiderIO/raiderio-client-builds/releases/tag/v0.5.4-alpha

**Comment by ianshade** [comment]
I'm facing the same issue but I noticed that it happens only when the menu is present. When I disable the menu with `window.setMenu(null);` the window moves fine.

**Comment by fcastilloec** [comment]
I want to add that electron `v3.0.0-beta.3` still has this problem.
@ianshade I have set `window.setMenu(null)` and I still see this problem.

**Comment by sc3w** [comment]
I had the same issue and I found out that the problem is that I use a custom resize handler to keep the window at 16:9. 

`        resize() {
            // set aspect ratio to 16:9 on Windows
            if (process.platform === 'win32') {
                var size = this.mainWindow.getSize()
                this.mainWindow.setSize(size[0], parseInt(size[0] * 9 / 16))
            }
        }
`

When I move the window, a resize event is fired and the size of the window fluctuates 1 pixel in width (if I move the window to left/right) or in the height (if I move the window up/down).

This caused my function to constantly increase the window size by 1 pixel when I moved the window.

I solved it by waiting for at least 2 pixel change in size before adjusting the aspect ratio.

`        resize() {

            // set aspect ratio to 16:9 on Windows
            if (process.platform === 'win32') {
                var size = this.mainWindow.getSize()
                if( Math.abs(size[0]-this.tmpSize[0]) > 2 || Math.abs(size[1]-this.tmpSize[1]) > 2)
                {
                    this.mainWindow.setSize(size[0], parseInt(size[0] * 9 / 16))
                    this.tmpSize = size;
                }
            }

            // adjust video size
            this.mainWindow.send('player.resized')
        }
`

Maybe this helps.

**Comment by fcastilloec** [comment]
I can report that on electron v3.0.1 this bug is still present but I've found a better workaround for it.
Setting the property `useContentSize: true` fixed it for me. Now the window doesn't get resized when moving.
I also had to change the `width` and `height` property to accommodate the new way the size is being measured, but that was it!

**Comment by benjaminadk** [comment]
I am using v3.0.0 on Windows 10 and am dynamically calculating `BrowserWindow` height based on screen size.  The bug is still present, and my window was shrinking when moved. I can agree with @fcastilloec that setting `useContentSize: true` seems to fix the problem.

**Comment by SayakMukhopadhyay** [comment]
I am using v2.0.9 on Windows 10, I am seeing a similar issue. If I have `setResizable` off and I minimize and restore, continuously, the window decreases in height each time by an amount which seems equal to that of the menu bar. This behaviour only happens when a menu is set.

**Comment by BarthaBRW** [comment]
I had the same problem with v4.0.0. The solution of @fcastilloec worked: Setting the property `useContentSize: true` fixed it for me.

**Comment by HaulinOats** [comment]
@sc3w Your solution completely solved this issue for me! I'd buy you a beer, if I could.

**Comment by sataqi** [comment]
**Temporary workaround**  until the issue is resolved:

Save your `height` and `width` in a global variable and manually set the size of window on `restore` event.

    win.on('restore', (e) => {
        win.setSize(origWidth, origHeight);
    });


Related: [#16900](https://github.com/electron/electron/issues/16900)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sataqi** [comment]
Experiencing same issue with Electron `5.0.7`

**Comment by islalobo** [comment]
@sofianguy We are experiencing this issue with v5.0.9

**Comment by colludium** [comment]
Still happening in v8.1.0 and it's been almost 2 years...! This isn't much good for pixel art games... 

Of note, when moving the window with resizeable set false, the following returned the values that were set, but the actual (measured) dimensions of the client area were 10 pixels wider and 10 pixels taller.

window.innerWidth / .innerHeight
browserWindow.getContentSize()
browserWindow.getContentBounds().width / .height

**Comment by sgd2z** [comment]
Still an issue in electron 10

**Comment by joaomlemos** [comment]
Still happening in electron 12

**Comment by turdiyev** [comment]
still an issue is here with electon 11. `useContentSize: true` doesn't help

**Comment by cnmade** [comment]
Still got the same problem , Electron 12, Is it possible to fix this problem?

**Comment by MarkMinerov** [comment]
Hello guys, just add minWidth and minHeight with the same values as height and width:
```
mainWindow = new BrowserWindow({
  minWidth: windowWidth,
  minHeight: windowHeight,
  width: windowWidth,
  height: windowHeight,
})
```

**Comment by th3jesta** [comment]
Experiencing in 13.1.4. Very irritating.

**Comment by hgalocy** [comment]
This fixes the bug; just need to adjust your width and height accordingly:

win.on('will-move', (e) => { //account for weird windows resizing bug when window is moved
        win.setSize(yourWidth, yourHeight);
    });

**Comment by hgalocy** [comment]
This fixes the bug; just need to adjust your width and height accordingly:

`win.on('will-move', (e) => { //account for weird windows resizing bug when window is moved
win.setSize(yourWidth, yourHeight);
});`

**Comment by hgalocy** [comment]
This will fix it:
`
win.on('will-move', (e) => { //account for wierd windows resizing bug
        win.setSize(yourWidth, yourHeight);
});
`

Adjust your width and height accordingly.

**Comment by hgalocy** [comment]
This line fixes the bug:

`win.on('will-move', (e) => { win.setSize(yourWidth, yourHeight) });`

Adjust your width and height accordingly.

**Comment by edosssa** [comment]
Still happening :(

**Comment by fzf404** [comment]
It's still happening in Electron 26.2.1.

**Comment by ButzYung** [comment]
> I found a solution for this issue by setting win.setPosition( x, y ). I set my coordinates to where I wanted the window to load and found that there is no longer any unwanted resizing.
> 
> I am unsure if this is a blanket solution, but it did fix this re-sizing issue while setResizeable is set to false.
> 
> Currently using release 25.5.0
> 
> Good luck!

This seems to work when device pixel ratio is 1. However, the problem is back if it isn't 1 (when you set "Make everything bigger" to anything above 100% under Windows).

**Comment by parkdongcheol** [comment]
> > I found a solution for this issue by setting win.setPosition( x, y ). I set my coordinates to where I wanted the window to load and found that there is no longer any unwanted resizing.
> > I am unsure if this is a blanket solution, but it did fix this re-sizing issue while setResizeable is set to false.
> > Currently using release 25.5.0
> > Good luck!
> 
> This seems to work when device pixel ratio is 1. However, the problem is back if it isn't 1 (when you set "Make everything bigger" to anything above 100% under Windows).

Good to know this tidbit now. Thanks for the feedback!

**Comment by LucileGrnd** [comment]
Hi, any news about this?

**Comment by MSJavaScript** [comment]
> Hi, any news about this?
I may case, the window size changes if I write 
```javascript
win.setMenu(null);
win.loadFile('index.html');
```
However, if I move the setMenu line below, the problem is solved
```javascript

win.loadFile('index.html');
win.setMenu(null);
```

**Comment by DenisFV** [comment]
Calling setSize() twice fixes this

**Comment by farid-azihub** [comment]
> I found a solution for this issue by setting win.setPosition( x, y ). I set my coordinates to where I wanted the window to load and found that there is no longer any unwanted resizing.
> 
> I am unsure if this is a blanket solution, but it did fix this re-sizing issue while setResizeable is set to false.
> 
> Currently using release 25.5.0
> 
> Good luck!

This fixed the issue for me, thanks!
@parkdongcheol
