### ISSUE TITLE
Can't start electron 2.x on 64bit Windows 7

### ISSUE THREAD

**Issue by fengtaijun0507** [electron/electron#13046]
* Electron Version: 2.0.2
* Operating System (Platform and Version): windows 7 , 64 bit
* Last known working Electron version: 

**Expected Behavior**
Main Window to Appear when run.

**Actual behavior**
error occur

**To Reproduce**

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone https://github.com/electron/electron-quick-start
$ npm install
$ npm start || electron .
```
**Screenshots**
![image](https://user-images.githubusercontent.com/14059031/40415636-f1a36730-5ead-11e8-8bcf-93c6504e9b64.png)

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Users\\qxb-810\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'start' ]
> 2 info using npm@6.0.1
> 3 info using node@v8.11.2
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info lifecycle electron-quick-start@1.0.0~prestart: electron-quick-start@1.0.0
> 6 info lifecycle electron-quick-start@1.0.0~start: electron-quick-start@1.0.0
> 7 verbose lifecycle electron-quick-start@1.0.0~start: unsafe-perm in lifecycle true
> 8 verbose lifecycle electron-quick-start@1.0.0~start: PATH: C:\Users\qxb-810\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\2work\space\5study\elecapp\test03\electron-quick-start\node_modules\.bin;C:\Users\qxb-810\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\qxb-810\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Intel\UCRT;C:\Program Files\Intel\UCRT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Java\jdk1.8.0_144\bin;C:\Program Files\Java\jdk1.8.0_144\jre\bin;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\Program Files\Microsoft VS Code\bin;C:\Users\qxb-810\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
> 9 verbose lifecycle electron-quick-start@1.0.0~start: CWD: D:\2work\space\5study\elecapp\test03\electron-quick-start
> 10 silly lifecycle electron-quick-start@1.0.0~start: Args: [ '/d /s /c', 'electron .' ]
> 11 silly lifecycle electron-quick-start@1.0.0~start: Returned: code: 2147483651  signal: null
> 12 info lifecycle electron-quick-start@1.0.0~start: Failed to exec start script
> 13 verbose stack Error: electron-quick-start@1.0.0 start: `electron .`
> 13 verbose stack Exit status 2147483651
> 13 verbose stack     at EventEmitter.<anonymous> (C:\Users\qxb-810\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:283:16)
> 13 verbose stack     at emitTwo (events.js:126:13)
> 13 verbose stack     at EventEmitter.emit (events.js:214:7)
> 13 verbose stack     at ChildProcess.<anonymous> (C:\Users\qxb-810\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
> 13 verbose stack     at emitTwo (events.js:126:13)
> 13 verbose stack     at ChildProcess.emit (events.js:214:7)
> 13 verbose stack     at maybeClose (internal/child_process.js:925:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> 14 verbose pkgid electron-quick-start@1.0.0
> 15 verbose cwd D:\2work\space\5study\elecapp\test03\electron-quick-start
> 16 verbose Windows_NT 6.1.7601
> 17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\qxb-810\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
> 18 verbose node v8.11.2
> 19 verbose npm  v6.0.1
> 20 error code ELIFECYCLE
> 21 error errno 2147483651
> 22 error electron-quick-start@1.0.0 start: `electron .`
> 22 error Exit status 2147483651
> 23 error Failed at the electron-quick-start@1.0.0 start script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 2147483651, true ]

**Comment by hongmomanu** [comment]
the  same problem , electron 2.x ia32 not work on windows7 x64 ,but  electron 2.x x64 worked.

**Comment by virgilliu** [comment]
i have the same problem on win7 pro 32bit

**Comment by Jun90925** [comment]
Same issue here, electron 2.0x windows7 sp1 ia32.
Can not start up, and exit with code 2147483651 without any other infomation.

**Comment by asinbow** [comment]
Quite the same as https://github.com/electron/electron/issues/12980
It happens on some Chinese version Windows 7.

**Comment by MarshallOfSound** [comment]
Going to merge into #12980
