### ISSUE TITLE
install electron module failed in macOS

### ISSUE THREAD

**Issue by JackyTianer** [electron/electron#13056]
* Electron version: **electron@^2.0.2**
* Operating system: **macOS 10.13.3**
* Local Node Version: **v9.4.0**

### Expected behavior
 execute *npm install --save-dev electron*  , Successfully installed the module

### Actual behavior
installation failed ，when electron run **install.js**,it will be download electron.zip package, but my pc failed to find it ；

Screenshots：
![](http://edu-image.nosdn.127.net/bbb1e416-4b4d-49b7-84df-c14da6ca7037.png?imageView&quality=100)

### How to reproduce
  $ npm install --save-dev electron

**Comment by MarshallOfSound** [comment]
@JackyTianer Is your mac a 32bit OS somehow? 😕

**Comment by JackyTianer** [comment]
@MarshallOfSound I excuted **uname -a** command, get system infomation like this
**Darwin MacBook-Air-2.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64**
My mac should be 64-bit ，why **install.js** want download a 32bit Electron.app?

**Comment by MarshallOfSound** [comment]
@JackyTianer What is in your `~/.npmrc` ?

**Comment by JackyTianer** [comment]
here is my ~/.npmrc
> //registry.npmjs.org/:_authToken=xxxxxxxx
registry=https://registry.npmjs.org/

**Comment by MarshallOfSound** [comment]
@JackyTianer If you run `node` and `console.log(process.arch)` what does it output?

**Comment by JackyTianer** [comment]
@MarshallOfSound  Thanks for your response
![image](https://user-images.githubusercontent.com/3354804/40473827-d758de6a-5f6f-11e8-8f29-1ecc54824b29.png)

**Comment by MarshallOfSound** [comment]
My only guess left is that https://github.com/electron/electron/blob/master/npm/install.js#L29 is somehow returning `ia32` normally due to a `.npmrc` configuration somewhere.

**Comment by JackyTianer** [comment]
@MarshallOfSound I think you are right, when I run `node install.js` by myself, I found it was downloading electron-v1.8.4-darwin-x64.zip, and I run ` console.log(process.env.arch)`,it output undefined. 

when i run `npm install electron`, maybe  **process.env.arch** returning ia32

**Comment by JackyTianer** [comment]
@MarshallOfSound I think you are right, when I run `node install.js` by myself, I found it was downloading electron-v1.8.4-darwin-x64.zip, and I run ` console.log(process.env.arch)`,it output undefined. 

when i run `npm install electron`, maybe  **process.env.arch** returning ia32
