### ISSUE TITLE
Cannot use node inspector on main process as of electron@2.0.0

### ISSUE THREAD

**Issue by jgliner** [electron/electron#13054]
* Electron Version: `electron@^2.0.2`
* Operating System (Platform and Version): `MacOS 10.13.4`
* Last known working Electron version: `electron@1.8.7`
* Local Node Version: `v9.11.1` (`v10.1.0` doesn't seem to work either)

---

**Expected Behavior**
Using `console.log` inside of an Electron Main Context logs an **inspectable** object to an instance of Node Inspector as well as a string inside the console

---

*RUNNING `electron@1.8.7`*

<img src="https://imgur.com/9Iydkbs.png">
<img src="https://imgur.com/Kx3laHE.png">

**Actual behavior**
*RUNNING `electron@^2.0.2`*

If using `stdio: ['inherit', 'inherit', 'inherit', 'ipc']` when spawning the `child_process`: Using `console.log` inside of an Electron Main Context logs a **non-inspectable** string (not JSON) to the console, and logs **nothing** to the inspector

<img src="https://imgur.com/l5QaSr9.png">
<img src="https://imgur.com/OTpHBdS.png">

If using `stdio: ['pipe', 'pipe', 'pipe', 'ipc']` when spawning the `child_process`: Using `console.log` inside of an Electron Main Context logs an **inspectable* `UInt8Array` to the console, as well as the inspector

<img src="https://imgur.com/jyxGLp8.png">
<img src="https://imgur.com/ajYVDnG.png">
<img src="https://imgur.com/xBcGgPU.png">

**To Reproduce**
[https://github.com/jgliner/electron_issue13054](https://github.com/jgliner/electron_issue13054)

```sh
$ git clone https://github.com/jgliner/electron_issue13054
$ npm install
$ npm run dev
```

There is also a branch called `before`, which is running `electron@1.8.7`.

**Additional Information**
This was an incredibly helpful feature in v1, as I often have to deal with large, nested objects in the main Electron process as part of my role. Not having it after our switch to v2 has brought a small disruption to my workflow. The configuration may have changed, since I know there was a bump in Electron's node version from v1 to v2. However, I did not see it documented anywhere.

Thanks!

**Comment by natew** [comment]
I'm seeing this as well and it's unfortunate as 2.0 solves another big issue for us.

In my console I see logs just fine:

![image](https://user-images.githubusercontent.com/12100/40877129-a69443a6-6630-11e8-96a2-bf62cbf78dcb.png)

I see nothing in my attached debugger:

![image](https://user-images.githubusercontent.com/12100/40877134-af712aac-6630-11e8-812e-a0d2498392f5.png)

I do see options for two environments:

![image](https://user-images.githubusercontent.com/12100/40877141-b8c00b3c-6630-11e8-9549-773157be457e.png)

Though logs don't show, I can manually write things in the REPL and it works:

![image](https://user-images.githubusercontent.com/12100/40877147-cc9ab40e-6630-11e8-9a5c-e23d998c1eda.png)

**Comment by jgliner** [comment]
Tried this again on `^2.0.5`, as well as `3.0.0-beta.3` with the same result.

Any insight would be much appreciated!

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
