### ISSUE TITLE
Creating two windows with the same `tabbingIdentifier` does not group them together

### ISSUE THREAD

**Issue by caseywebdev** [electron/electron#13078]
* Electron Version: 2.0.2
* Operating System (Platform and Version): macOS 10.13.4
* Last known working Electron version: 

**Expected Behavior**
If N windows are created with the same `tabbingIdentifier` the docs would imply these windows should be grouped together with tabs:

> `tabbingIdentifier` String (optional) - Tab group name, allows opening the window as a native tab on macOS 10.12+. Windows with the same tabbing identifier will be grouped together.

**Actual behavior**
The windows are not grouped together.

**To Reproduce**

```js
const { app, BrowserWindow } = require('electron');

app.on('ready', () => {
  const win1 = new BrowserWindow({ tabbingIdentifier: 'foo' });
  const win2 = new BrowserWindow({ tabbingIdentifier: 'foo' });
});

```

Notice both `win1` and `win2` are in their own windows and not as tabs in a single window.

**Additional Information**
We are currently working around this issue in our product with `addTabbedWindow` but a working declarative format described in the docs would be much nicer.

**Comment by tonyganch** [comment]
@caseywebdev, can you please check that "System preferences > Dock > Prefer tabs when opening documents" is set to "always".
I've tried this now with Electron 2.0.2 and macOS 10.13.4 and tabs work as expected.

**Comment by caseywebdev** [comment]
I'm still getting 2 windows with that setting as "always". I'm on macOS `10.13.5`.

> Windows with the same tabbing identifier will be grouped together.

If the prefer tabs option intentionally has an affect on this it should probably be mentioned in the docs as this line is only conditionally true.

**Comment by philfreo** [comment]
I don't think this macOS setting _should_ have an affect on this bug anyway. You shouldn't need this setting enabled ("prefer tabs when opening documents") at the OS-level in order to e.g. restore a set of tabs into the same window. Many apps (e.g. Chrome/Safari) have tabs that work well regardless of this setting.

**Comment by avner-hoffmann** [comment]
I'm using macOS Sierra (10.12.6) and the latest stable release of electron (4.1.0) and it still doesn't work
Is this going to be fixed?

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by 12joan** [comment]
This is still an issue in
- Electron Version: v22.2.0
- Operating System (Platform and Version): macOS 13.0

Setting prefer tabs to "Always" causes the correct behaviour. I think the default is "In Full Screen".
