### ISSUE TITLE
Preload script inherited incorrectly when window.open is used in sandboxed renderer

### ISSUE THREAD

**Issue by miniak** [electron/electron#13073]
* Electron Version: master
* Operating System (Platform and Version): any
* Last known working Electron version: N/A

**Expected Behavior**
When using the `window.open` API in a sandboxed renderer, the child window should not have any preload script configured. The `preload` option is not included in `inheritedWebPreferences` in `lib/browser/guest-window-manager.js`, which creates the default options for the child window.

**Actual behavior**
The child window re-uses the same renderer process as the parent, where the preload script is provided on the command line. Therefore the preload script is used for the child window as well.

I ran into this when trying to figure out why the tests are failing for my PR: https://github.com/electron/electron/pull/13031, which uses `getWebPreferences()` to get the preload script path.

**Comment by miniak** [comment]
Could it be related to the `affinity` option, which merges renderer process with same `sandbox`, `preload` and `nodeIntegration` options. Maybe it's applied incorrectly in this case.

**Comment by miniak** [comment]
Forcing the child window into it's own renderer process uncovers this bug

```
diff --git a/atom/browser/atom_browser_client.cc b/atom/browser/atom_browser_client.cc
index 32c8d3dd8..c3fd9f2f4 100644
--- a/atom/browser/atom_browser_client.cc
+++ b/atom/browser/atom_browser_client.cc
@@ -115,11 +115,6 @@ bool AtomBrowserClient::ShouldCreateNewSiteInstance(
 
   int process_id = current_instance->GetProcess()->GetID();
   if (!IsRendererSandboxed(process_id)) {
-    if (!RendererUsesNativeWindowOpen(process_id)) {
-      // non-sandboxed renderers without native window.open should always create
-      // a new SiteInstance
-      return true;
-    }
     auto* web_contents =
         content::WebContents::FromRenderFrameHost(render_frame_host);
     if (!ChildWebContentsTracker::IsChildWebContents(web_contents)) {
@@ -130,6 +125,9 @@ bool AtomBrowserClient::ShouldCreateNewSiteInstance(
       return true;
     }
   }
+  if (!RendererUsesNativeWindowOpen(process_id)) {
+    return true;
+  }
 
   // Create new a SiteInstance if navigating to a different site.
   auto src_url = current_instance->GetSiteURL();
```

**Comment by miniak** [comment]
@tarruda what do you think?

**Comment by tarruda** [comment]
> When using the window.open API in a sandboxed renderer, the child window should not have any preload script configured. The preload option is not included in inheritedWebPreferences in lib/browser/guest-window-manager.js, which creates the default options for the child window.

I was not aware of `inheritedWebPreferences`, but maybe the `preload` should be added there? The reason is that it is quite easy to disable preload in simple windows like this (added at the top of preload):

```js
if (window.opener) {
  return
}
```

OTOH removing this behavior would break existing applications that have come to rely on it (such as my company's app).

**Comment by miniak** [comment]
Fixed by https://github.com/electron/electron/pull/13031
