### ISSUE TITLE
Context menu showing paste option on elements that aren't pastable. 

### ISSUE THREAD

**Issue by gadamsgh** [electron/electron#13072]
* Electron Version: 2.0.0
* Operating System (Platform and Version): Windows 10
* Last known working Electron version: 1.87

**Expected Behavior**
When focus is on an input field and you right click on a button, the context menu for the button is shown.

**Actual behavior**
Starting in Electron 2.0.0, the context menu seems to provide options based on where focus was previously, not based on what element the right click occurred on.  When I have focus on the input field and right click a button, I get the context menu options for the input field.  

**To Reproduce**
$ git clone https://github.com/gadamsgh/electron-quick-start.git
$ cd electron-quick-start/
$ npm install
$ npm start

Place focus in input field.  Right click on Submit button.  See paste option appear on submit button.  Revert to pre-2.0.0 and see different behavior.  

**Screenshots**
Before (1.8.7):
![image](https://user-images.githubusercontent.com/39625845/40550525-f290577c-5fff-11e8-9416-04c56ebfa6d0.png)

After (2.0.0): 
![image](https://user-images.githubusercontent.com/39625845/40550530-f6ffd706-5fff-11e8-86be-5107d61e17ff.png)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by pushkin-** [comment]
@sofianguy This issue occurs in Electron 5.0

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by pushkin-** [comment]
I can reproduce this in Electron 8.0.1.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by pushkin-** [comment]
repros with Electron 12

**Comment by pushkin-** [comment]
posted new issue [here](https://github.com/electron/electron/issues/28083)
