### ISSUE TITLE
Electron anti-aliasing reducing image quality

### ISSUE THREAD

**Issue by interwebjill** [electron/electron#13079]
* Electron Version: 2.0.2
* Operating System (Platform and Version): Windows 10 1803 and Mac 10.11.06

**Expected Behavior**
Expect similar anti-aliasing in Electron as in Chrome

**Actual behavior**
Electron renders canvas images at a lower quality than Chrome (v. 66)

**Screenshot**
View on the left is from the Chrome window, view on the right is Electron:

![vb2mi](https://user-images.githubusercontent.com/15721176/40572472-2d0c8382-6062-11e8-8fcc-3958210d1a92.png)

**Comment by Slamology2** [comment]
CnTL:P(Display720xdpi)
Ansi[102π5×2.5]\108
Screen Saver
Set to 5 min.

[heLpfuL:]Yes(No)

Get Outlook for Android<https://aka.ms/ghei36>

**Comment by interwebjill** [comment]
Electron 2.0.2 is running Chrome v. 61. Nw.js, which uses Chrome v. 66, does not have this issue of reduced image quality/anti-aliasing.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
