### ISSUE TITLE
Gamepad mapping missing left-stick x-axis

### ISSUE THREAD

**Issue by daarong** [electron/electron#13081]
* Electron Version: v2.0.2-win32-x64 (also fails on numerous revs back to at least v1.3.3-win32-x64)
* Operating System (Platform and Version):  Win10 Home 
* Last known working Electron version: none found

**Expected Behavior**
Without special drivers, connect PS4 DS4 to Win10 via bluetooth.  Left stick x-axis should respond

**Actual behavior**
No axis or button shows a response to left-stick x-axis

**To Reproduce**
Use the PS4 DS4 with the standard html gamepad API, use left-stick x-axis.  If you download this demo page, you can run it locally with Electron:  https://ericlathrop.github.io/html5-gamepad-configurator/

Note that:
1) This bug is not seen in Chrome or Firefox
2) PS4 DS4 left-stick comes through fine with DirectInput
3) User can install DS4-Tool to cause PS4 to be seen as Xbox360 controller, avoiding this problem

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
