### ISSUE TITLE
Composite Layers activity is taking too long with Electron 2

### ISSUE THREAD

**Issue by omeryagmurlu** [electron/electron#13088]
* Electron Version: 2.0.2
* Operating System (Platform and Version): Linux 64 bit
* Last known working Electron version: 1.8.1

**Expected Behavior**
Just like in 1.8.1, I would expect composite layers to take nearly no time (Total time for 10ish seconds: **494.5ms**).

**Actual behavior**
On continued canvas updates, composite layers activity takes up to long that the app lags 1-2 seconds behind (Total time for 10ish seconds: **9474.1ms**).

**To Reproduce**
I'll put up a repo soon.

**Screenshots**
On 2.0.2:
![screenshot from 2018-05-27 16-17-25](https://user-images.githubusercontent.com/8201544/40586408-55798144-61ca-11e8-8332-de3f229e40f8.png)
![screenshot from 2018-05-27 16-17-34](https://user-images.githubusercontent.com/8201544/40586412-5a66edea-61ca-11e8-8382-b251f49733e0.png)

The same code with 1.8.1:
![screenshot from 2018-05-27 16-15-12](https://user-images.githubusercontent.com/8201544/40586417-6fb9f43a-61ca-11e8-86bd-29d4942f3743.png)

**Additional Information**
The app is essentially utilizing [literally canvas](http://literallycanvas.com/). I don't get the same problem with Chrome 62 (Electron uses 61), so I don't think there is a problem with literally canvas.

**Comment by petrbrzek** [comment]
I think it could be related to this https://stackoverflow.com/questions/46115503/canvas-in-google-chrome-61-0-3163-79-are-too-slow-on-linux

**Comment by shripadk** [comment]
Can confirm that I am facing same issue on macOS as well. I'll try and put up a repo which reproduces this as soon as I find some time. In 2.0.2 version, the time taken for Composite Layers activity is around 9.5s while in the 1.7.2 version, it's around 20ms.

**Comment by Eyesiah** [comment]
After updating our game with 2.0.2, we had a few users report this issue (including on Windows). We didn't have it internally though.

Adding the following to our electron js appears to have fixed the issue for these users:
`app.commandLine.appendSwitch("enable-color-correct-rendering", "false")
app.commandLine.appendSwitch("enable-draw-occlusion", "true")
app.commandLine.appendSwitch("force-color-profile", "sRGB")`

**Comment by miniak** [comment]
@omeryagmurlu does the issue reproduce with Electron 3.0 beta?

**Comment by miniak** [comment]
Closing as this is a Chromium issue and it seems like there are workarounds available.
