### ISSUE TITLE
More tray icon bugs

### ISSUE THREAD

**Issue by akontsevich** [electron/electron#13087]
* Electron Version: 2.0.1
* Operating System (Platform and Version): openSUSE Linux Tumbleweed
* Last known working Electron version: 1.8.x

**Expected Behavior**
Mouse left click on tray icon - activates window.

**Actual behavior**
Shows tray icon popup menu like for mouse right click.

**To Reproduce**
Reproducible in newest Skype and Riot built on Electron 2.0.1. Works fine with these apps built upon Electron 1.8.x

**Comment by pronebird** [comment]
AFAIK `Tray` has no connection with `BrowserWindow`. Does it really activate the window or it's operating system that brings the focus?

**Comment by akontsevich** [comment]
In Electron 1.8.x it activates the window.

**Comment by akontsevich** [comment]
Could be some GTK3 bug: I see same behavior in Thunderbird -  shows tray icon popup menu for both mouse left-right clicks. For right click it is correct and styled - rounded. For left click - not styled, appeared in different position and squared. Same for Electron applications. Reproducible under KDE, not sure about other GTK DEs. Report the bug somewhere to GTK?

**Comment by akontsevich** [comment]
Seems libappindicator-gtk3 (libappindicator3) issue: https://github.com/vector-im/riot-web/issues/6767#issuecomment-424535414

So works fine for now if libappindicator3 uninstalled. You may close this.

**Comment by akontsevich** [comment]
Reproducible with libappindicator3 (libappindicator-gtk3) package installed with any electron version including latest. Reproducible with Riot for ex. Works fine if package is not installed. However icon looks weird, see: vector-im/riot-web#7553

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by akontsevich** [comment]
@sofianguy  Yes issue still exists in riot-web: 1.3.2 ("electronVersion": "5.0.7"). See my previous comment: https://github.com/electron/electron/issues/13087#issuecomment-504700023

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by akontsevich** [comment]
Works fine now in KDE **_without_** `libappindicator3` and **_with_** libappindicator1 installed.

**Comment by codebytere** [comment]
Closed as we reverted to the old Chromium tray impl.
