### ISSUE TITLE
Cannot destructure property 'BrowserWindow' of 'undefined'

### ISSUE THREAD

**Issue by Rafsun82** [electron/electron#13082]
I am facing an error `Cannot destructure property 'BrowserWindow' of 'undefined'` while using require in a renderer process.

So I have a custom module named `custom.js` which looks like-
```
const { BrowserWindow } = require('electron').remote
```
In `main.js` I tried to require this module. Code of `main.js` looks like-
```
const {app, BrowserWindow} = require('electron')
const path = require('path')
const url = require('url')
const custom = require('./custom.js')
```
It shows the above error in a windows dialog box at startup.

I think, when `custom.js` executed its first line, `BrowserWindow` module wasn't loaded completely. Or maybe it is because of the `remote` object which seems to be null. 

Can anyone explain what is wrong?

**Comment by sethlu** [comment]
@Rafsun82 The `remote` module is only available in the renderer process. Did you include your `custom.js` in the main process JavaScript code?

**Comment by Rafsun82** [comment]
@sethlu Yes, I have included the `custom.js` in the main process JavaScript code. Also I only used the `remote` module in `custom.js`. Is it because I required `custom.js` (which uses remote module) in the `main.js`?

**Comment by MarshallOfSound** [comment]
@Rafsun82 Yes, the `remote` module can only be used from renderer process's.
