### ISSUE TITLE
Make it possible to open DevTools unfocused

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#13095]
**Is your feature request related to a problem? Please describe.**

During development, I open DevTools when the DOM is loaded with `win.webContents.openDevTools({mode: 'undocked'});`. The problem is that I don't want the DevTools window to be in the front of the app, so I would have to click the app window afterward to bring it to the front. I solved this with `win.webContents.once('devtools-opened', () => win.focus());`. The problem with this solution is that DevTools shows for half a second before the app window is brought to the front, which is quite jarring.

**Describe the solution you'd like**

I would like an option for `.openDevTools()` to specify it to open in the background and unfocused if the `mode` is `undocked` and if it's any other `mode`, it will just not focus DevTools.

```js
win.webContents.openDevTools({
	mode: 'undocked',
	unfocused: true
});
```

---

Related: https://github.com/electron/electron/issues/4764#issuecomment-196263172

> We should probably change this behavior or add an option to not focus the devtools window.
> \- @zcbenz

**Comment by miniak** [comment]
@sindresorhus I've created a PR to address this issue https://github.com/electron/electron/pull/13852/files
