### ISSUE TITLE
One running Electron app prevents service worker registration in a second Electron app

### ISSUE THREAD

**Issue by tejohnso** [electron/electron#13096]
* Electron Version: 2.0.2
* Operating System (Platform and Version): Windows 10, 8, 7  / Linux
* Last known working Electron version: -

**Expected Behavior**
Two Electron apps can run simultaneously and both can run service workers.

**Actual behavior**
The first app runs service workers, the second app cannot.

**To Reproduce**
Clone [the test case repo](https://github.com/Rise-Vision/electron-sw-failure) and follow the instructions in [the readme file](https://github.com/Rise-Vision/electron-sw-failure#multiple-app-worker-failure).

**Comment by tejohnso** [comment]
Note this does not occur if the app is packaged (using [electron-packager](https://github.com/electron-userland/electron-packager) for example). 

I suspect this is related to the packaged apps having separate user data directories but *--user-data-dir* is not a [supported command line switch](https://electronjs.org/docs/api/chrome-command-line-switches#supported-chrome-command-line-switches). Is there some other way to indicate the data dir?

**Comment by santiagonoguez** [comment]
On Linux this issue can be solved by specifying different directory values for the CHROME_USER_DATA_DIR env variable for each run, but I wonder if there is something similar ( env variable, command line switch, BrowserWindow option ) that could be done on Windows to solve it also here.

**Comment by santiagonoguez** [comment]
After searching a bit I found that by adding a line like the following we can solve the issue on Windows also:
app.setPath('userData', ...)

by setting different user data directory for each process.
