### ISSUE TITLE
dialog crashes electron when changing accepted extension

### ISSUE THREAD

**Issue by thiagorova** [electron/electron#13097]
First of all, thanks for this amazing tool. You guys rock!

this might have something to do with [#13048](https://github.com/electron/electron/issues/13048)
If there is something else, I couldn't find it... 
as for the Issue:

* Electron Version: 2.0.0
* Operating System (Platform and Version): MacOs Sierra
* Last known working Electron version: not sure

**Expected Behavior**
Once I open the Electron dialog, all files, except are grayed except for the selected extension. If I want to change the extension, ill go to the selection box under the files and change it. It should change the selectable files from the file list.

**Actual behavior**
 I'm using a dialog inside the renderer code. I'm limiting the accepted extension in the openFile action and giving the user the choice of changing it. As soon as I change the extension, Electron freezes for a couple seconds and the closes, no error message given.

**To Reproduce**
It happened to me every single time (I hope I'm not making a mistake...). Just copy the code in the renderer part of electron (I didn't test in the main code) and try to change the accepted extension

Code: 

```
const { remote } = require('electron'),
    dialog = remote.dialog;
dialog.showOpenDialog(remote.getCurrentWindow(), {
      properties: ['openFile',],
      title: "Please select your audio file",
      filters: [
        { name: 'All files', extensions: ['mp3', 'wav', 'flac'] },
      ]}, () => {})
```

Test: I tried it on a "clean" electron (this one: [electron-quick-start]). You can either just copy this into renderer.js or clone this repo: [electron error](https://github.com/thiagorova/electron-bug) and follow the same steps as for electron-quick-start: 
```
git clone https://github.com/thiagorova/electron-bug
cd electron-bug
npm i
npm start
```

if you guys need anything else, please tell me

PS: not sure if this is relevant, but when the dialog opened (before the crash), this was printed in the console:

> objc[7922]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9cf95c90) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1146ebcd8). One of the two will be used. Which one is undefined.

**Comment by vwvww** [comment]
I tried to reproduce this bug, but I could not.
Do you mean that you change the file's extension by changing the file's name on the dialog?
I tried it on macOS High Sierra(10.13.4) and I could not rename the grey-colored file(with txt extension). The OS' behavior has been changed, I guess.
I think this is OS-side to deal with it, not on the electron side.

**Comment by thiagorova** [comment]
Hi.
I attatched to images to try to help. After opening the file (first image), I changed the accepted extension (second image). After a while, the app closes and an error message appears (3rd image)
I tried it today, and the error persisted in my computer.

<img width="801" alt="bildschirmfoto 2018-06-10 um 12 23 53 pm" src="https://user-images.githubusercontent.com/11561119/41203115-35d74c06-6ca9-11e8-8a5e-d03bc8cd49b1.png">

<img width="801" alt="with arrow" src="https://user-images.githubusercontent.com/11561119/41203157-995fc852-6ca9-11e8-8e00-9e9014c517ad.png">


<img width="592" alt="bildschirmfoto 2018-06-10 um 12 24 30 pm" src="https://user-images.githubusercontent.com/11561119/41203120-42e7931a-6ca9-11e8-90ee-8e81d7f645aa.png">

**Comment by vwvww** [comment]
Thank you for additional explanation. I could not find the format select list on the dialog...
I could reproduce it on my environment too with your extra explanation.
I think #13048 is somewhat different issue, because it is not reproduced on macOS on #13048 case.
Also I could not reproduce this issue in Ubuntu 16.04.

I will check out on the debug build of electron and check out the callstack.

**Comment by AdrianoFerrari** [comment]
I had a similar issue, and upgrading to 2.0.1 or later fixed it:
https://github.com/electron/electron/issues/12737

**Comment by thiagorova** [comment]
Hi! thanks for the warning.
I can't test this today, but as soon as I verify this, I'll get back to confirm it!

**Comment by thiagorova** [comment]
Hi again!
thanks for the heads up, @AdrianoFerrari. I can indeed confirm that it is working now!
