### ISSUE TITLE
Menu mnemonics aren't underlined in Linux

### ISSUE THREAD

**Issue by sshock** [electron/electron#13107]
**System Info**
* Electron Version: Not sure, but tested with VSCode 1.23.0 and Slack 3.1.1
* Operating System (Platform and Version): Debian Linux 9.4 with XFCE
* Last known working Electron version: none

**Expected Behavior**
Menu items below File, Edit, Help, etc. should have mnemonics underlined (e.g., the x in Exit under the File menu).  This should work in Windows and Linux.

**Actual behavior**
They are not underlined in Linux.  They are underlined in Windows.  So it is only on Linux that it is not working.

**To Reproduce**
I'm not sure how to reproduce this because I tried electron-quick-start and it didn't have any underlines anywhere, on Windows or Linux.

**Screenshots**
See https://github.com/Microsoft/vscode/issues/50022

**Additional Information**
Let me know if you need me to do any additional work or if you can take it from here.

**Comment by sshock** [comment]
Am I the only one seeing this problem?

**Comment by codebytere** [comment]
Unfortunately this seems like an issue best handled by downstream consumers. Happy to re-open if it can be isolated to Electron.
