### ISSUE TITLE
css cursor style still a problem in title bar with no frame

### ISSUE THREAD

**Issue by jasonkuhrt** [electron/electron#13104]
* Electron Version: 2.0.0
* Operating System (Platform and Version): 10.13.4 (17E202) macOS High Sierra
* Last known working Electron version: never

**Expected Behavior**
Honour cursor style at the top of the window.

**Actual behavior**

![2018-05-29 14 15 38](https://user-images.githubusercontent.com/284476/40677357-7414ce10-634b-11e8-9978-a68251abb8ce.gif)

**To Reproduce**

clone https://github.com/electron/electron-quick-start

Then:

HTML:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
  </head>
  <body>
    <a style="background:cyan;padding:3em;" href="https://foobar.com">I am a link with looooooots of padding.</a>
    <script>
require("./renderer.js")
</script>
  </body>
</html>
```

JS:
Just add `frame:false` to what's already there:

```js
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    frame: false,
  })
```

** Other Notes **

if I use [`customButtonsOnHover`](https://electronjs.org/docs/api/frameless-window#custombuttonsonhover) then the problem goes away, but that's not a solution to this bug.

Related:

* https://github.com/electron/electron/issues/6725
* https://github.com/electron/electron/issues/5723

**Comment by MarshallOfSound** [comment]
Merging into #5723 that although is closed, is still getting updates RE other workarounds / features to help with this issue
