### ISSUE TITLE
Use PolicyKit

### ISSUE THREAD

**Issue by Paviluf** [electron/electron#13106]
Hello,

It seem that electron use kdesudo / gksudo. These programs are deprecated and instead electron should use PolicyKit.

https://github.com/Microsoft/vscode/issues/49270
https://github.com/Microsoft/vscode/issues/46560

Thanks !

**Comment by MarshallOfSound** [comment]
> It seem that electron use kdesudo / gksudo

This assumption is incorrect, vscode actually uses a module called `sudo-prompt` which internally uses kdesudo.  https://github.com/jorangreef/sudo-prompt/blob/master/index.js#L119

**Comment by Paviluf** [comment]
Thank you for the info. Is electron using PolicyKit ?
