### ISSUE TITLE
printToPDF - pdf page header overlapping after build electron

### ISSUE THREAD

**Issue by esagarjadhav** [electron/electron#13109]
* Electron Version: 1.8.3
* Operating System (Platform and Version): windows
* Last known working Electron version: 1.8.3

**Expected Behavior**
print pdf page headers should not overlap with page content after creating build using electron-packager . --no-prune 

**Actual behavior**
after creating electron build pdf generate with page content overlapping with page header (which is repetitive for every page)

**To Reproduce**
this will reproduce after creating electron build

**Screenshots**
PDF create in development environment - 
![image](https://user-images.githubusercontent.com/23036860/40702692-6d79df36-6400-11e8-8711-232e0c851255.png)

PDF create after build environment - issue noted for header overlapped with content
![image](https://user-images.githubusercontent.com/23036860/40702756-a843bb50-6400-11e8-9a75-1c2c7e32be39.png)

> If applicable, add screenshots to help explain your problem.

[main-process-funtion-to-create-print-pdf.txt](https://github.com/electron/electron/files/2052728/main-process-funtion-to-create-print-pdf.txt)

**Additional Information**
for more reference i have attached html file content which is used for creating pdf using printToPDF - 

[opd-print.txt](https://github.com/electron/electron/files/2052645/opd-print-dev.txt)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
