### ISSUE TITLE
Linux: dialog.showMessageBox sometimes blocks mouse

### ISSUE THREAD

**Issue by isidorn** [electron/electron#13112]
* Electron Version: 1.7.12
* Operating System (Platform and Version): Linux (Ubuntu 16.04, Ubuntu 18.04). Does not happen on Win and OS X.

**Expected Behavior**
Calling `dialog.showMessageBox` does not block mouse and touchpad - they actually work

**Actual behavior**

`dialog.showMessageBox` freezes mouse and touchpad sometimes

**To Reproduce**

Reproducable steps and much more detail here https://github.com/Microsoft/vscode/issues/50026

**Comment by ckerr** [comment]
Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you've responded, please link to the test case and @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
