### ISSUE TITLE
Frontend freezing on heavy task load while backend runs

### ISSUE THREAD

**Issue by theyezzyman** [electron/electron#13119]
* Electron Version: 2.0.1
* Operating System (Platform and Version): macOs Sierra 10.12.6
* Last known working Electron version: 2.0.1

**Expected Behavior**
Avoid frontend freezing

**Actual behavior**
A clear and concise description of what actually happened.
Frontend freezes

**To Reproduce**
Your best chance of getting this bug looked at quickly is to provide a REPOSITORY that can be cloned and run.
I am working out of a closed source repo however the basic issue I'm having is running a large number of functions at once. The backend runs fine however the frontend will freeze up when this happens. The breaking point largely depends on which computer I run on.

Mainly looking for help w/ this and to get any ideas of what I can do to execute a large number of tasks at once within an electron app w/o crashing the frontend.
You can fork [electron-quick-start](https://github.com/electron/electron-quick-start) and include a link to the branch with your changes.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone $YOUR_URL -b $BRANCH
$ npm install
$ npm start || electron .
```
**Screenshots**

**Additional Information**

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
