### ISSUE TITLE
Frameless BrowserWindow docking to screen edges are not working with specific minWidth and minHeight values.

### ISSUE THREAD

**Issue by Astrych** [electron/electron#13118]
* Electron Version: 4.0.3, 2.0.2 and 1.8.7
* Operating System (Platform and Version): Linux Mint 18.3 and 19

**Expected Behavior**
Frameless window should be dockable to the screen edges after defining -webkit-app-region:drag for some HTML element. It should be possible by dragging window to edges using mouse cursor or with shortcuts: win+up or down, win+left or right.

**Actual behavior**
It stops working for specific direction x or y after exceeding specific values for minWidth and minHeight parameters. Setting minWidth to values higher than 960 block docking to the upper screen edge and setting minHeight to values exceeding 526 block it for left and right directions. My screen resolution is 1920x1080 if it will help somehow.

**To Reproduce**
$ git clone https://github.com/electron/electron-quick-start.git
$ cd electron-quick-start
$ npm install

Add frame, minWidth, minHeight parameters in main.js file
https://github.com/electron/electron-quick-start/blob/master/main.js#L10

```javascript
mainWindow = new BrowserWindow({
     frame: false, width: 1280, height: 800, minWidth: 961, minHeight: 527
})
```

modify index.html file:
```HTML
<body style="-webkit-app-region: drag">
```
https://github.com/electron/electron-quick-start/blob/master/index.html#L7

$ npm start

**Additional Information**
The bug is not present on Windows 10.

**Comment by Astrych** [comment]
Bug still present on electron version 4.0.3

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by Astrych** [comment]
Bug is still present on electron version 8.0.1.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
