### ISSUE TITLE
application run in background long time, then crash.

### ISSUE THREAD

**Issue by richmonkey** [electron/electron#13120]
* Electron Version:2.0.1
* Operating System (Platform and Version):osx 10.13.4
* Last known working Electron version: 

**Expected Behavior**
do't crash 

**Actual behavior**
A clear and concise description of what actually happened.
crash dump:
https://gist.github.com/richmonkey/15f7c38f7da4209832e28e10ca7f4eaf

**To Reproduce**
Your best chance of getting this bug looked at quickly is to provide a REPOSITORY that can be cloned and run.
app run in background,  put compute suspend one night
then app will crash probably.

You can fork [electron-quick-start](https://github.com/electron/electron-quick-start) and include a link to the branch with your changes.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone $YOUR_URL -b $BRANCH
$ npm install
$ npm start || electron .
```
**Screenshots**

**Additional Information**

**Comment by danielearning** [comment]
This happens to me too. Windows platform, version 2.0.2.
The BrowserWindow launched by the app cleared to the backgroundColor passed in options at creation time.

**Comment by JieJiSS** [comment]
MacOS 10.12.4, happens too.

can be reproduced in 3 of my Electron Apps (including 1.4.3, 1.6.x and 1.8.x).

**Comment by bpasero** [comment]
The stacktrace looks a lot like https://github.com/electron/electron/issues/12676

**Comment by deepak1556** [comment]
Merging this to https://github.com/electron/electron/issues/12676
