### ISSUE TITLE
Set Mac deployment target to 10.10 for Chromium 66+

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#13125]
Chromium doesn't support Mac OS 10.9 from the version 66, see https://support.google.com/chrome/answer/95346?vid=0-44659795628-1527793827712#sysreq_mac

Also verify that there's no OS version checks in code that are no longer required.

/cc @miniak

**Comment by miniak** [comment]
https://support.google.com/chrome/forum/AAAAP1KN0B0LTwFIxbaNjY/?hl=en

Deprecating Support for Mac 10.9 starting in M66
Beginning with Chrome M66, Chrome requires Mac OSX 10.10 or later. Mac OSX 10.9 users will receive no further updates to Chrome after Chrome M65.

**Comment by pronebird** [comment]
Is it relevant to Electron v2.0 or did this happen even before?

**Comment by alexeykuzmin** [comment]
@pronebird It's not relevant to Electron 2.0.x.
Only affects future versions of Electron based on Chromium 66+.
