### ISSUE TITLE
Maybe we should use yarn

### ISSUE THREAD

**Issue by feichao** [electron/electron#13139]
According to the guide about [Upgrading Chromium](https://electronjs.org/docs/development/upgrading-chromium), I use the command `./script/bootstrap.py -v`, but when it comes to run `./script/lib/util.py`, some errors occur and the 'npm install' process is slow in China, maybe we should use yarn instead.

**Comment by MarshallOfSound** [comment]
`yarn` is not dramatically faster than npm@6.  If you're having speed issues it will be to do with the npm mirror you're using or your local machine
