### ISSUE TITLE
Downloaded release size differs

### ISSUE THREAD

**Issue by felipetesc** [electron/electron#13138]
* Electron Version: 2.0.2
* Operating System (Platform and Version): Linux
* Last known working Electron version: 

**Expected Behavior**
The downloaded file should have the same size informed on the page https://github.com/electron/electron/releases/tag/v2.0.2 

**Actual behavior**
The size differs. I can't know if the file was changed.

**To Reproduce**
Look to the size informed on the web page. It says 
46.3 MB, once you download 'electron-v2.0.2-linux-x64.zip' at 'https://github.com/electron/electron/releases/tag/v2.0.2' you should see that the file has actually 48,6 MB (48.556.818 bytes).

**Additional Information**

the shasum are identical from txt and from the downloaded file
6cf06465e5e74f9eabb790ef6855fd40a48ff474557a3ecb314b638118b8080e

I found some problems when rendering the html with the method win.loadURL('views/index.html'), and devtools crash. Perhaps it's not related.

**Comment by nornagon** [comment]
Looks like a confusion between MB and MiB. 46.3 MiB ~= 48,556,818 B ~= 48.6 MB.
