### ISSUE TITLE
Pass down non-serializable objects via webFrame executeJavascript

### ISSUE THREAD

**Issue by amaurymartiny** [electron/electron#13130]
**Is your feature request related to a problem? Please describe.**

The [security guide](https://electronjs.org/docs/tutorial/security) recommends to use `contextIsolation` for preload script.

Using `webFrame.executeJavascript(...)` from inside a preload script, how do I pass down a non-serializable object to the inner webpage's context?

More concretely, here is my example:

preload.js:
```javascript
// In the preload.js context
const { ipcRenderer, webFrame } = require('electron')
const ipc = {
  send (data) {
    ipcRenderer.sendToHost(...)
  }
}
// Now I want to pass down ipc to the webpage's context
// This webpage is expecting window.myApp.ipc, so that it could use it like window.myApp.ipc.send(...)
webFrame.executeJavaScript(`window.myApp.ipc = ${ipc}`); // Doesn't work.
```

Basically I want the inner webpage to be able to send/receive messages via IPC.

**Describe the solution you'd like**

A way to be able to do `webFrame.executeJavaScript(`window.myApp.ipc = ${ipc}`);`.

**Describe alternatives you've considered**

Right now I'm turning off contextIsolation, and my preload looks like:

preload.js:
```javascript
// In the preload.js context
const { ipcRenderer, webFrame } = require('electron')
const ipc = {
  send (data) {
    ipcRenderer.sendToHost(...)
  }
}
// Now I want to pass down ipc to the webpage's context
// This webpage is expecting window.myApp.ipc, so that it could use it like window.myApp.ipc.send(...)
window.myApp.ipc = ipc;
```

And the webpage can use `window.my.ipc.send(...)`.

**Additional context**

The loaded webpage is some remote content.

**Comment by MarshallOfSound** [comment]
Doing what you describe would effectively bypass `contextIsolation` making it useless.

I'd you just want to expose limited IPC messaging you should use `window.postMessage` and `window.onmessage` and proxy things to IPC yourself.
