### ISSUE TITLE
document in preload is empty for same origin url loaded with window.open

### ISSUE THREAD

**Issue by ahmedmohamedali** [electron/electron#13132]
* Electron Version: All  
* Operating System (Platform and Version): Windows 7 professional
* Last known working Electron version: None

There are two issues related to same origin url loaded via window.open 

1)  The preload in the web preferences of the parent window is ran for the child window
The expected behavior is electron to run the preload set in the web preferences of the child window in 
the webcontent 'new-window' event handler. If no preload was configured for the child window then it is ok to run the parent window preload.

2) The new window has the expected content but the document object in the scope of the preload script is blank.  The window object itself is correct.
For this one a workaround could be  to access the real document in the window load event listener but it is better to fix the issue in electron itself.

**Expected Behavior**
When a url with the same site as the parent page is loaded via window.open:

**How to Reproduce**
You can use the modified electron quick start here https://github.com/ahmedmohamedali/electron-quick-start/tree/repro-blank-document-in-preload

Steps:
1)  git clone https://github.com/ahmedmohamedali/electron-quick-start -b repro-blank-document-in-preload
3) npm install
4) npm start

When the main window is displayed click on the button "Open a new popup window".
Then in open the dev tools in the newly created window and observe the traces logged in the preload context.
- The preload file itself is preload-main but should be preload-popup
- The document is empty 
<html><head></head><body></body><html>

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR.
