### ISSUE TITLE
ContextIsolation and preload.js: can't attach to window anymore

### ISSUE THREAD

**Issue by kewde** [electron/electron#13134]
* Electron Version:
* Operating System (Platform and Version):
* Last known working Electron version: 

**Expected Behavior**
https://electronjs.org/docs/tutorial/security#3-enable-context-isolation-for-remote-content

A preload script _should_ be able to attach anything to the window or document with `contextIsolation: true`.

**Actual behavior**
Anything attached to the `window` in the preload.js just disappears in the renderer.

**To Reproduce**
```sh
$ git clone https://github.com/kewde/electron-quick-start.git -b contest-isolation-preload-bug
$ npm install
$ npm start
```

**Additional Information**
Works until 1.7.12, all versions upwards are broken (maybe 1.7.13 still works, but 1.8 is def broken).
https://github.com/kewde/electron-sandbox-boilerplate/issues/12

**Comment by MarshallOfSound** [comment]
This is how context isolation is supposed to work?  Afaik you aren't supposed to be able to pollute the scope of one window object in context A from context B.  If you saw behavior different to this previously it was a bug.

**Comment by kewde** [comment]
@MarshallOfSound that's indeed how I expected it to work.

It was actually possible until recently, a PR with Isolated Worlds has changed the behavior.
