### ISSUE TITLE
Electron cannot display Confluence Pages

### ISSUE THREAD

**Issue by markusmoenig** [electron/electron#13145]
Using Electron 2.02.
OS: Mac OS X 10.13.4

We are using Atlassian Confluence to document our application. However opening the Confluence pages from Electron displays an error message.

Example URL: https://braindistrict.atlassian.net/wiki/spaces/MZ/pages/2359297/Introduction

Displays in Electron as:
![screen shot 2018-06-02 at 11 43 32](https://user-images.githubusercontent.com/10293923/40882226-79702a40-6705-11e8-98bb-a011c1744c85.png)

Confluence support does not seem to know about Electron.

Code I use to open the Window:

```javascript
let url = "https://braindistrict.atlassian.net/wiki/spaces/MZ/pages/2359297/Introduction";
let helpWindow = new BrowserWindow( { width: 1200, height: 800, show : true, 'node-integration': false, allowRunningInsecureContent: true } );
helpWindow.loadURL( url );
```

**Comment by MarshallOfSound** [comment]
`node-integration` was renamed and deprecated a long time ago, you're going to need to use `nodeIntegration: false`.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by markusmoenig** [comment]
It also happens with nodeIntegration: false

**Comment by MarshallOfSound** [comment]
@markusmoenig Your code is not following the documentation

```js
new BrowserWindow({
  webPreferences: {
    nodeIntegration: false
  }
})
```

The above code is what are you trying to do

**Comment by markusmoenig** [comment]
Ups, you are right, my fault! Works perfectly now.

Thanks for the help @MarshallOfSound
