### ISSUE TITLE
Frameless window drag in CSS isn't being applied until window is modified

### ISSUE THREAD

**Issue by brnlee** [electron/electron#13140]
* Electron Version: 2.0.1
* Operating System (Platform and Version): Windows 10 x64
* Last known working Electron version: N/A

**Expected Behavior**
The frameless window can be dragged without having to resize or open dev tools. There is no system context menu before resizing or opening dev tools either.

**Actual behavior**
When the window is displayed, I am unable to drag it. I am only able to drag the window or display the system context menu once I either resize the window or open dev tools. 

**To Reproduce**
I am creating a frameless BrowserWindow and then inserting css to said window. In the css, I am adding the option for the user to drag the window using `-webkit-app-region: drag;` 

main.js
  `mainWindow.webContents.on('dom-ready', () => {
   mainWindow.webContents.insertCSS(fs.readFileSync(path.join(__dirname, 'test.css'), 'utf8'))
  })`

CSS
`body {
    -webkit-app-region: drag;
    background-color: skyblue;
  }`

**Additional Information**
The background color is applied without having to do anything

**Comment by anker2000** [comment]
I'm having this problem too on Mac.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
