### ISSUE TITLE
Any way to listen RenderProcess (Browser) logs from MainProcess?

### ISSUE THREAD

**Issue by jonatasfreitasv** [electron/electron#13146]
Have any way to listen RenderProcess logs (Browser logs) viewed in DevTools into MainProcess (NodeJS) ?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by MarshallOfSound** [comment]
Web contents do have a console message event, chaeck out the docs
