### ISSUE TITLE
navigators Geolocation API returns error 400-2 

### ISSUE THREAD

**Issue by cwittenb** [electron/electron#13143]
* Electron Version:  v2.0.1
* Operating System (Platform and Version): OSX 10.13.4

**Expected Behavior**
navigator.geolocation.getCurrentPosition should return the position of the device used.

**Actual behavior**
If you try to get a devices location via the geolocation API, like:
navigator.geolocation.getCurrentPosition(function(r){console.log(r)}, function(e){console.log(e)});
It returns an error like this:

`PositionError` {code: 2, message: "Network location provider at 'https://www.googleapis.com/' : Returned error code 400."}
code: 2
message: "Network location provider at 'https://www.googleapis.com/' : Returned error code 400."
__proto__: PositionError
PERMISSION_DENIED: 1
POSITION_UNAVAILABLE: 2
TIMEOUT: 3
code: 2
message: "Network location provider at 'https://www.googleapis.com/' : Returned error code 400."

My network connection is fine, the same code works outside the electron container.

**To Reproduce**
Run the above in your electron dev console.

**Comment by cwittenb** [comment]
As other tickets show, this seems to have been working once: #1376 -> #2613
Would be great to be able to use it again, as IP based services are far too inaccurate.

Thanks, any help would be greatly appreciated!

**Comment by MarshallOfSound** [comment]
@cwittenb Geolocation services are rate limited based on the `GOOGLE_API_KEY` you have set in your Electron app.  If you don't have one set then you are using the default Electron one which **everyone** will be using.  Your best bet is to generate and set your own `GOOGLE_API_KEY` env var in your app to ensure that you don't run out of API calls.

**Comment by cwittenb** [comment]
@MarshallOfSound : Sorry for bothering, but I was expecting a 403 in case I hit the limit. Thanks for your help - adding an API key fixed it!
