### ISSUE TITLE
Not works with Chrome61 'es module' feature: 'non-JavaScript MIME type'

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [electron/electron#13149]
* Electron Version: `v2.0.2`
![image](https://user-images.githubusercontent.com/12682063/40886408-c9a16420-6769-11e8-943b-240005346143.png)

* Operating System (Platform and Version): 
![image](https://user-images.githubusercontent.com/12682063/40886405-c4010868-6769-11e8-8bc9-68d563c56ce2.png)

* Last known working Electron version: 
No, it's a new feature of the Chrome version.

**Expected Behavior**
The html `script` taget with `type="module"` can works well.
```
<script type="module" src="./index.js"></script>
```

**Actual behavior**
![image](https://user-images.githubusercontent.com/12682063/40886430-3a016436-676a-11e8-831f-550095b282a1.png)

**Additional Information**
![image](https://user-images.githubusercontent.com/12682063/40886433-52c74d6e-676a-11e8-972e-c70a2bb66a7e.png)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
