### ISSUE TITLE
titlebarstyle is not consistent on macOS when maximised

### ISSUE THREAD

**Issue by zacharyrs** [electron/electron#13147]
* Electron Version: 2.0.2
* Operating System (Platform and Version): macOS 10.13.4
* Last known working Electron version: N/A

**Expected Behavior**
`titlebarstyle:'hiddenInset'` background should match that of `'hidden'` when maximised.

**Actual behavior**
When a browser window with hiddenInset titlebarstyle is maximised, the title bar appears transparent. If titlebarstyle is set to hidden, it instead has a grey background. See screenshots below.

**To Reproduce**

```sh
git clone https://github.com/zacharyrs/electron-quick-start -b titlebar
npm install
npm start || electron .
```

**Screenshots**
Current behaviour:
![screen shot 2018-06-03 at 1 39 09 pm](https://user-images.githubusercontent.com/10497077/40882373-22fdf79e-6734-11e8-9f61-0711323ff52b.png)

Nicer Behaviour:
![screen shot 2018-06-03 at 1 38 32 pm](https://user-images.githubusercontent.com/10497077/40882375-24f4e954-6734-11e8-8bae-7b31a4dc2dbd.png)

**Comment by zacharyrs** [comment]
Had a chance to dig around, and it looks like this is [known](https://github.com/electron/electron/blob/152422af812631c6afb6a5e129a780b77559cdf0/atom/browser/ui/cocoa/atom_ns_window_delegate.mm#L188).

I'm in no way familiar with cocoa, but it looks like the issue is due to the titlebar not being set to visible if the window is hiddenInset. I couldn't find any record of this decision, so I'm just curious what the logic behind it is?

Should hiddenInset not follow hidden, in that when fullscreen the titlebar is made nontransparent?

**Comment by codebytere** [comment]
hi @zacharyrs i had some time to dig into this recently, what's happening is that it's hitting a DCHECK:

```
[27986:0914/084342.846254:FATAL:render_widget_host_view_mac.mm(1656)] Check failed: SkColorGetA(color) == SK_AlphaOPAQUE || SkColorGetA(color) == SK_AlphaTRANSPARENT.
```
This is a DCHECK inherited from Chromium, which looks to be getting triggered through this pair of function calls:
```
5   libcontent.dylib                    0x0000000122328334 content::RenderWidgetHostViewMac::SetBackgroundColor(unsigned int) + 324
6   Electron Framework                  0x000000010e0dc1f7 atom::api::WebContents::LoadURL(GURL const&, mate::Dictionary const&) + 2151
```

I'll look into a potential fix

**Comment by zcbenz** [comment]
We worked around the problem by changing window style when window enters fullscreen mode:
https://github.com/electron/electron/blob/v3.0.0-beta.13/atom/browser/ui/cocoa/atom_ns_window_delegate.mm#L179-L226

It seems that the hack does not work for 10.13 anymore.
