### ISSUE TITLE
idea: BrowserWindow.opener

### ISSUE THREAD

**Issue by trusktr** [electron/electron#13157]
**Is your feature request related to a problem? Please describe.**

I'd like to get the BrowserWindow that opened the current child window where my code is running. It would be similar to `window.opener` with `window.open`, but this is on the Electron side.

**Describe the solution you'd like**

For example, I would be able to run something like the following inside a BrowserWindow opened from some other window:

```js
require('electron').remote.getCurrentWindow().opener
```

that'd give me the `BrowserWindow` that opened the current window.

This is not related to the `parent` property that we can pass into the BrowserWindow constructor options. That `parent` option seems to serve only to make windows that are always in front of other windows. This is confusing.

**Describe alternatives you've considered**

No alternatives other than have to use IPC to send over the window to the child, which is cumbersome.

Did I miss it?

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR.
