### ISSUE TITLE
Latest Windows 10 Update seems to break Electron Packaged App

### ISSUE THREAD

**Issue by AndreasWebdev** [electron/electron#13159]
* Electron Version: 2.0.2
* Operating System (Platform and Version): Windows 10 Build 1803 (17134.81)
* Last known working Electron version: 2.0.2 (on an older Windows 10 Update and Windows 7)

**Expected Behavior**
Clicking on the application EXE generated by electron-packager opens the app.

**Actual behavior**
Opening the EXE does nothing, not showing a window or error, not even opening a process (or at least so fast taskmanager cannot show it)

**To Reproduce**
As the application is an internal company application I am not allowed to share the whole project. However I setup a minimal project with the same modules and a simple stripped down index. It also does not show up.

[mintest.zip](https://github.com/electron/electron/files/2071927/mintest.zip)
To build the project, setup the following commands
```
npm install
npm run build
```

**Additional Information**
This bug occured after updating the Windows 10 setup to the latest version. Systems with older Windows 10 versions and Windows 7 builds are unaffected.

**Comment by felixrieseberg** [comment]
Hey Andreas! We haven't seen the behavior you're seeing, so I'm wondering if we can grab more information. What happens when you run your app in PowerShell? Is there any console output?

**Comment by AndreasWebdev** [comment]
Hello, running it through the non-packaged version seemed to not yield any errors and work flawlessly, building and running the packaged app with the system seems to be no problem either, only running it on a network drive seem to not work anymore. I guess this is a bug I should submit to electron-userland/electron-packager, correct?

**Comment by AndreasWebdev** [comment]
Sorry, I missclicked! @felixrieseberg I guess this is a bug I should submit to electron-userland/electron-packager, correct?

**Comment by ckerr** [comment]
If I'm reading the above comment correctly, this isn't a bug for electron/electron. Closing.
