### ISSUE TITLE
Array splice performance horrendously degraded in chrome 66

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#13153]
https://crbug.com/835347
It was fixed only in the Chromium 67, in https://chromium.googlesource.com/v8/v8.git/+/2eb23a17cc9af7fb9c7a64d0c9c794772642d77d

If there will be an Electron release with the Chromium 66, we should try to backport the fix, it can't be simply cherry-picked.

**Comment by MarshallOfSound** [comment]
Fixed in https://github.com/electron/libchromiumcontent/pull/555
