### ISSUE TITLE
Removing <input type="color"> from DOM tree causes application crash when user tries to use system color picker

### ISSUE THREAD

**Issue by robhil** [electron/electron#13158]
* Electron Version: 2.0.2
* Operating System (Platform and Version): macOS High Sierra 10.13.3
* Last known working Electron version: - 

**Expected Behavior**
Application should not crash when user uses system color picker and input was removed

**Actual behavior**
Application crashes when user tries to use System Color Picker and input was removed

**To Reproduce**
1. Open System Color Picker by clicking <input type="color" />
2. Don't close system color picker
3. Remove `<input type="color" />`
4. Try to use System Color Picker

```sh
$ git clone https://github.com/robhil/electron-quick-start.git -b color-picker-issue
$ npm install
$ npm start
```
**Screenshots**
![](http://g.recordit.co/Zx3Uxs2bPR.gif)

**Comment by LoganDark** [comment]
I think the system color picker should be removed when the input element is removed, this would fix the issue.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
