### ISSUE TITLE
BrowserWindow#loadURL inside of electron.screen 'display-added' event callback results in endless calls to callback 

### ISSUE THREAD

**Issue by Willerie** [electron/electron#13150]
* Electron Version: 2.0.2
* Operating System (Platform and Version): Windows 10 Professional
* Last known working Electron version: N/A

**Expected Behavior**
I'm trying to create an application which automatically creates a new BrowserWindow and loads a URL in that browser window when a display is added.

**Actual behavior**
If I call loadURL on a BrowserWindow in a 'display-added' event listener's callback, it results in endless calls to that callback.

**To Reproduce**
This is the minimal code I've found that produces the error:
```javascript
const electron = require("electron");
const { app, BrowserWindow } = electron;
app.on("ready", () => {
  let window = new BrowserWindow();
  electron.screen.on("display-added", () => {
    window.loadURL("https://www.github.com/");
  });
});
```
If you have multiple displays, you can trigger this issue by either plugging in a new display, or using Win+P to switch between single screen and extend modes.

Edit: I thought I'd tested this possibility yesterday, but right now the problem is only showing up when I first remove and then add a monitor, both while the Electron app is running. Using Win+P to switch from extend mode to single screen mode and back does the trick.

**Additional Info**
* It doesn't matter if the window is created inside or outside of the callback. 
* the URL being loaded (including file paths) appears to be irrelevant; all inputs cause the same issue. 
* I found by accident that calling a nonexistent method (such as asdf()) results in the same problem. Of the few other BrowserWindow methods I've tried, none caused the same issue.

**Edit: Successful Workaround**
In case anyone else is experiencing this issue, you can get around it for the meantime using setTimeout, as follows:
```javascript
const electron = require("electron");
const { app, BrowserWindow } = electron;
app.on("ready", () => {
  let window = new BrowserWindow();
  electron.screen.on("display-added", () => {
    setTimeout(() => window.loadURL("https://www.github.com/"), 0);
  });
});
```

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR.
