### ISSUE TITLE
How to capture the notifications of a network page？

### ISSUE THREAD

**Issue by sandywk** [electron/electron#13151]
I have an instant chat program for remote web pages that I need to add to electron to generate desktop clients, and now I'm bothered by the need to capture remote web programs in the main process, so that the desktop applications can make more reactions, such as taskbar flickers.

I found that electron can capture new windows open events on Web pages.

> let win = new BrowserWindow(windowOptions);
win.loadURL('https://work.aihecong.com/');
win.webContents.on('new-window', (event, url) => {
    event.preventDefault()
    const shell = electron.shell
    shell.openExternal(url)
})

So I wonder if there is a way to capture the notification of web page requests.
I tried using ipcRenderer but failed. It seems that remote web pages are unusable.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
