### ISSUE TITLE
The (deprecated) NativeImage.toPng was removed in 2.0.0, but this does not seem documented.

### ISSUE THREAD

**Issue by scottrippey** [electron/electron#13169]
* Electron Version: `2.0.0`
* Last known working Electron version: `1.x`

The Electron 2.0.0 release notes do NOT indicate that the `NativeImage.prototype.toPng` and `toJpeg` methods were removed, in favor of the `toPNG` and `toJPEG` methods.
These methods have been deprecated since `1.2.5` (https://github.com/electron/electron/commit/e9222583cbd354559ec0ab0bb1170567c2ec9d73)

This has broken Spectron's `capturePage` method, and will hopefully be fixed soon: https://github.com/electron/spectron/pull/297

I would be happy to add to the release notes, if that's an option; just point me in the right direction!

**Comment by codebytere** [comment]
hi @scottrippey, you're correct, our bad! Looks like we missed it when updating our [breaking changes doc](https://github.com/electron/electron/blob/2-0-x/docs/tutorial/planned-breaking-changes.md).

I'll repair Spectron soonish; we're also planning to work on updating Spectron generally.

**Comment by scottrippey** [comment]
Great, thanks!
Spectron didn't have any mention of Electron 2.0.0, so I figured it would need to "catch up" soon.

For the official release docs for Electron 2.0.0 (https://electronjs.org/releases), is there somewhere I could submit a PR, to update the notes with these `NativeImage toPNG / toJPEG` changes?

**Comment by sofianguy** [comment]
@scottrippey we welcome PRs. [Contributing guide](https://electronjs.org/docs/development/pull-requests)

**Comment by codebytere** [comment]
Closing as v2.0.0 is no longer supported.
