### ISSUE TITLE
Discord icon missing

### ISSUE THREAD

**Issue by LoganDark** [electron/electron#13165]
* Electron Version: ???
* Operating System (Platform and Version): macOS 10.14 Mojave
* Last known working Electron version: ???

**Expected Behavior**
Icon.

**Actual behavior**
Discord has no icon.

**To Reproduce**
Download Discord and run.

**Screenshots**
![image](https://user-images.githubusercontent.com/4723091/41010334-974ac150-68eb-11e8-8ee9-f882ed42bf8c.png)

Excuse the transparency, it's very hard to get a screenshot of the macOS tab switcher.

**Additional Information**
May be related to dark theme.

---

I am aware macOS Mojave is not exactly accessible to everyone yet, but I'm reporting this just in case.

**Comment by LoganDark** [comment]
I'm surprised people have Mojave this early and also happen to have Discord (canary too!)

**Comment by MarshallOfSound** [comment]
@LoganDark Thanks for being super diligent and reporting these issues early on, however without a good bug report from the discord developers we can't really look into this.  For instance, a good "How to reproduce" would involve exactly which API causes this.

I'm going to close this out and you should report this issue to discord directly and they will report it to us with solid repro steps after they've looked into it a bit (hopefully).
