### ISSUE TITLE
Can't detect Windows High-Contrast mode for non-inverted HC themes

### ISSUE THREAD

**Issue by BrendanMcK** [electron/electron#13178]
Electron currently has an `isInvertedColorScheme` that can be used to detect a sub-set of Windows' High Contrast modes (added in [PR 7518](https://github.com/electron/electron/pull/7518)). This only returns true for HC themes that are light-on-dark. If a dark-on-light HC theme is selected - see image below - this returns false.

This helper uses Chromium's helper of the same name. That [does check for Windows High Contrast Mode (ie whether the SPI_GETHIGHCONTRAST flag is set)](https://github.com/chromium/chromium/blob/2050d71b0b5731fa3d0cc645845d889cbbe600dd/ui/gfx/sys_color_change_listener.cc#L31), but it then filters out color schemes that have [foreground lighter than background](https://github.com/chromium/chromium/blob/2050d71b0b5731fa3d0cc645845d889cbbe600dd/ui/gfx/sys_color_change_listener.cc#L33).

This works fine for Chromium's purposes - they don't support HC mode fully, they just want to know when an _inverse_-style scheme is used so they can suggest an appropriate inverted Chrome theme; hence the name - isInvertedColorScheme, not isHighContrastColorScheme.

If an Electron-based app *does* want to fully support all flavors of Windows High Contrast mode, this method is insufficient.

Ideal solution here perhaps is to add an additional helper and event specifically for Windows HC mode, similar to the Chromium-based ones, but without the color-based filtering. Suggest `isHighContrastModeEnabled` and `high-contrast-mode-changed`.

Image below shows an example white-on-black HC theme. Windows ships with 4 built-in schemes, three of which are light-on-dark. Users can also create custom themes by modifying any of those built-in schemes.

![image](https://user-images.githubusercontent.com/1754373/41077462-8d46c826-69cb-11e8-997d-6c73552efef9.png)

**Comment by jkleinsc** [comment]
Resolved via #15493
