### ISSUE TITLE
Notification API do not work with Windows 10 17134.81

### ISSUE THREAD

**Issue by arch-master** [electron/electron#13172]
**Version Info**
* Electron Version: 2.0.2
* Operating Syste: Windows 10 Build 17134.81

**Expected Behavior**
Notications show.

**Actual behavior**
Nothing happens. No errors are logged in the console.

**To Reproduce**
Just download the [electron-quick-start](https://github.com/electron/electron-quick-start) project and run the Notifications API demos.

**Additional Information**
Same issue as #10864 but in a more recent Windows build.

**Comment by MarshallOfSound** [comment]
Please track in the issue you linked
