### ISSUE TITLE
Updates to NSVisualEffectView (Vibrancy and Dark Mode)

### ISSUE THREAD

**Issue by skllcrn** [electron/electron#13175]
**Is your feature request related to a problem? Please describe.**
Relates to the current implementation of `vibrancy`, in particular issues with Electron 2.0 and on macOS Mojave (#12726, #10886, #8305). 

**Describe the solution you'd like**
Move from deprecated Materials in `NSVisualEffectView.Material` to [new ones](https://developer.apple.com/documentation/appkit/nsvisualeffectview/material).

**Additional context**
This in concurrence with #4300 should make it much easier to support Dark Mode.

**Comment by codebytere** [comment]
This is now something that should be handled with `nativeTheme`.
