### ISSUE TITLE
Addons cannot use the bundled OpenSSL

### ISSUE THREAD

**Issue by implausible** [electron/electron#13176]
**Is your feature request related to a problem? Please describe.**
I maintain https://github.com/nodegit/nodegit and would like to start building NodeGit against the OpenSSL library that is bundled with Node. This would significantly improve our build process.

**Describe the solution you'd like**
Node exports OpenSSL symbols for Windows https://github.com/nodejs/node/pull/6274. It would be very cool if Electron would export the openssl symbols as well, so that native module creators could target openssl that ships with Electron's copy of node.

**Describe alternatives you've considered**
We have been maintaining a copy of OpenSSL from node that we try to update when NodeJS updates their copy. This has been a bit of a nightmare due to the gyp files not perfectly matching our use case in NodeGit.

**Additional context**
It looks like there was a decision made to not export OpenSSL symbols in the past, but no reason explicitly mentioned here: https://github.com/electron/electron/pull/6585

But it does look like for regular nodejs, exporting those symbols has been working fine for the last couple years https://github.com/nodejs/node/pull/6274

**Comment by paulfitz** [comment]
I also maintain software that would be a lot easier to build if the OpenSSL symbols were exported in electron-flavored node. Would be very grateful if the symbols could be exported.

I found some more context on why they are not here https://github.com/electron/electron/issues/1410#issuecomment-152407010 - they conflict with Chromium's fork of OpenSSL.

**Comment by nornagon** [comment]
Electron is planning to move to building node with BoringSSL (see https://github.com/electron/electron/pull/13285), and not ship OpenSSL at all. Would exporting BoringSSL's symbols be useful?

**Comment by ethomson** [comment]
IIUC, BoringSSL is a fork of OpenSSL, so hopefully should be a simple adaptation.

**Comment by nornagon** [comment]
If we do this we should also do #11801

**Comment by alejandroclaro** [comment]
My two cents here against the request:

* The fact NodeJS expose OpenSSL symbols is a big issue. There are some issues in NodeJS repository taking about this. This is one in particular:

https://github.com/nodejs/node/issues/24964

Absorbing the OpenSSL dependency and re-exposing it is not a good idea. The `crypto` and `tls` modules do not expose all the functionalities that OpenSSL or any of its forks provide. Also, NodeJS does no exposed all the symbols, only a subset, so either way, any third party add-on will have to deal with symbols clashing issues, runtime incompatibility with the library version if the can link only with the symbols provided in node, and also issue with other dependencies that depend on dynamic versions of OpenSSL, or BoringSSL, or LibreSSL. 

I think it would be better if NodeJS does not export the OpenSSL symbols when it's statically linked into node, an allows that way third-party addons and their dependencies to use the system installed version of OpenSSL, and/or deal with multiple versions or forks in independent way (responsibility of the node addon developer).

**Comment by nornagon** [comment]
I'm inclined to agree with @alejandroclaro, I think exporting BoringSSL's symbols in Electron would cause more problems than it solves.
