### ISSUE TITLE
Virtual Host for my app

### ISSUE THREAD

**Issue by pkhach** [electron/electron#13180]
Hello,

Is it possible to start my app from a virtual host like:
https://desktop.mysite.com/index.html
?

I know that I can start it with a custom protocol like:
myapp://desktop.mysite.com

but I want to have the https

In my code, I want to manually process requests for ''host=desktop.mysite.com and redirect the rest of request to the default https protocol handler.

We did this in CefSharp by registering a Custom Scheme but I cannot find a way to do it with Electron.

I have tried the protocol.interceptHttpProtocol('https', ...) with no luck.

Thanks!

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
