### ISSUE TITLE
Add snap support to autoUpdater

### ISSUE THREAD

**Issue by zeke** [electron/electron#13181]
@flexiondotorg and @felixrieseberg are talking about updating Electron's autoUpdater module to support Linux updates from https://snapcraft.io 🎉 

Let's use this issue to talk about how we can support this.

**Comment by zewa666** [comment]
What about using [electron-builder](https://github.com/electron-userland/electron-builder/blob/master/docs/configuration/snap.md)? Is there a specific need to have this with the native autoUpdater?

**Comment by zeke** [comment]
`electron-builder` has its own built-in alternative to the `autoUpdater` API. We want to implement something that will work for all apps regardless of what packaging tool they're using.

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
