### ISSUE TITLE
2 different OS, 2 different computer, identical problem - cannot read property 'on' of unudefined

### ISSUE THREAD

**Issue by gomonkey** [electron/electron#13188]
* Electron Version: 2.0.2
* npm Version: 3.5.2
* Node Version: 10.2.1
* Operating System (Platform and Version): Ubuntu and Windows 10
* Last known working Electron version: none

**Actual behavior**
cannot read property 'on' of unudefined

It is one week that I try to work with electron and I check everywhere for understand my problem.
I try everything but nothing was work for me.
I have just ubuntu installed in this laptop

I try to:
- Install electron globally, then removed and use just in local project;
- I always use --verbose and no problem in installation;
- Remove electron, npm, node and reinstall from begin;
- clean npm cache 
- Use differents electron type ( electron, electron-builder, electron-prebuilder ) with and without --save-dev );
- Use differents terminal;
- include "electron" and "app" in different way, but is look like there is not "app", autocomplete not find it
- Used quick start app, maybe my code was wrong;

In the end I decide to move in windows, I installed node, npm, electron and try with quik start application but I have the same error.

Now I am ask myself if is not a problem by electron.

I log require and resolve and they are in local

resolve:
`project_path/node_modules/electron/index.js`
require:
`project_path/node_modules/electron/dist/electron`

How is possible that I have the same problem in two differents computer with two differents operation system?
How can I solve it?

thanks in advance

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
