### ISSUE TITLE
Insecure Resources warning even when nodeIntegration turned off

### ISSUE THREAD

**Issue by PerBothner** [electron/electron#13186]
* Electron Version: 2.0.2
* Operating System (Platform and Version): Fedora GNU/Linux 28

I'm having problems silencing the "Electron Security Warning (Insecure Resources) This renderer process loads resources using insecure protocols." warning.  An earlier comment suggests the danger is reated to nodeIntegration, so I turned that off:

     win = new BrowserWindow({width: w, height: h, show: false, 
        webPreferences: { nodeIntegration: false }})

However, that did not shut up the warning.

Also, would it make sense to disable the warning when getting resources from `localhost`?

I've tried both of:

    process.env['ELECTRON_DISABLE_SECURITY_WARNINGS'] = true;
    win.ELECTRON_DISABLE_SECURITY_WARNINGS = true;
and neither work.  The only thing that works is setting `ELECTRON_DISABLE_SECURITY_WARNINGS` in the process environment *before* starting the electron application. I would prefer not to have to do that, and I would prefer not to rename `electron`.

Loading the resources using https is undesirable when serving true resources, because then I have to deal with certificates, which adds an extra pain point.  However, turning off nodeIntegration  might make sense - if that would work.

**Comment by timfish** [comment]
These warnings do not show when an app has been packaged.

**Comment by PerBothner** [comment]
I have my own way of packaging my application.  Having to bundle a renamed copy of electron with my application seems incredibly wasteful.

**Comment by MarshallOfSound** [comment]
> This renderer process loads resources using insecure protocols

This warning is independent of `nodeIntegration` being disabled.  This is talking about loading remote content using `http` instead of `https`.  Disabling these security warnings is not something we support

**Comment by PerBothner** [comment]
This is not loading remote content - this is loading *local* content, from `localhost`, using `http` rather than `file`.  One reason for using `http` is that the resources are compressed in a `zip` archive, which can be served efficiently (as gzip-compressed) using libwebsockets.  If Electron supported the `jar:` scheme, I could use that.

**Comment by lexicalunit** [comment]
Any way to get this warning to shut up when I'm just loading resources from localhost? That should be safe, right? This is a spurious warning, right?

**Comment by PerBothner** [comment]
There are instruction to turn the warnings off - but they don't seem to work.
The only thing that works for me is setting
 
    ELECTRON_DISABLE_SECURITY_WARNINGS=true

in the environment _before_ starting the `electron` executable.

**Comment by lexicalunit** [comment]
Yah but I don't want to disable security warnings for my entire application, just for this one window, which loads a URL from `http://localhost`...
