### ISSUE TITLE
Rebuild Node Module Problems Between Jest and Electron

### ISSUE THREAD

**Issue by ezweave** [electron/electron#13189]
* Electron Version: 2.0.2
* Operating System (Platform and Version): macOS 10.13.4 
* Last known working Electron version: N/A

**Expected Behavior**
I have to rebuild some Node modules _specifically_ for Jest using `npm rebuild sharp` (sharp, in this case), so the `test` command does this (and now tests work), I would expect calling `./node_modules/.bin.electron-rebuild` as part of just running the client to rebuild it for Electron's version of node.

**Actual behavior**
The client fails to load the bundle, showing the following error:

```
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
```

**To Reproduce**
_I attempted to do this in a fork of `electron-quick-start` but `npm i` fails horribly... not sure I want to stack problems on top of problems, if there's an easy answer I can't find_

**Screenshots**
![image](https://user-images.githubusercontent.com/568995/41129680-711f12a2-6a70-11e8-967a-03230b05abbc.png)

**Additional Information**
Here is my build script:
```javascript
"dev": "./node_modules/.bin/electron-rebuild && npm run patch-node-modules && npm run hot-server -- --start-hot",
```
And my test script:
```javascript
"test": "npm rebuild sharp && cross-env NODE_ENV=test node --trace-warnings ./test/runTests.js",
```

**Comment by Slapbox** [comment]
[Related](https://github.com/lovell/sharp/issues/1282)

**Comment by codebytere** [comment]
Closing in light of https://github.com/electron/electron/issues/18397
