### ISSUE TITLE
Need a way to inject code into <webview> guest pages just before guest scripts load.

### ISSUE THREAD

**Issue by colindefais** [electron/electron#13196]
Dear electron contributors,

**What I want to achieve**

I use `<webview>` to display external web pages in my application.
But I would like to inject code to these guest pages just before their scripts load.

I want to do this just before the first guest script loads because I would like to redefine global APIs or provide polyfills for features not yet implemented by chromium.

For example: I would like to provide my own implementation of `navigator.geolocation` to guest pages in order to fake the user position.

**The way to do it in chromium applications**

In chromium this kind of injection is possible by using [webview.addContentScripts()](https://developer.chrome.com/apps/tags/webview#method-addContentScripts) (using `run_at` property with `document_start` value).

Indeed, this method allow me to run some code in the guest page just before its first script loads.
My code can manipulate the DOM (create elements) but it cannot share declarations (of variables/functions/classes...) with host scripts since it is executed into an [isolated world](https://developer.chrome.com/extensions/content_scripts#isolated_world).

A [known solution](https://stackoverflow.com/questions/9515704/insert-code-into-the-page-context-using-a-content-script) is to insert a `<script>` element in the guest page just before its first `<script>` declaration.
This way my new `<script>` will be the first loaded and will be able to redefine global properties such as `navigator.geolocation`.
For example, the [Manual Geolocation](https://chrome.google.com/webstore/detail/manual-geolocation/jpiefjlgcjmciajdcinaejedejjfjgki) extension does this kind of stuff.

This whole procedure is not only bound to chromium, in NW.js the `webview.addContentScripts()` method is also available and this technique works fine.

**What I have tried in electron**

In electron `webview.addContentScripts()` is not implemented.

But in the electron `<webview>` there is the [preload](https://electronjs.org/docs/api/webview-tag#preload) attribute.
At first I though it could be used to replace `webview.addContentScripts()`.
But unfortunately, when a `preload` script is called, the page is not enough loaded to manipulate the DOM and create a `<script>` tag to inject code. Indeed, `document.documentElement` is undefined at this time. I have tried to use `document.write()` but this had the effect to stop the loading of the page!

In the electron API there is also the [executeJavaScript()](https://electronjs.org/docs/api/webview-tag#webviewexecutejavascriptcode-usergesture-callback) method.
I have tried to use it some `<webview>` events:

- [load-commit](https://electronjs.org/docs/api/webview-tag#event-load-commit): like the `preload` attribute, this seems to be too soon. If I use `document.write()` at this time, the new content is wiped out when page loads.

- [did-start-loading](https://electronjs.org/docs/api/webview-tag#event-did-start-loading): this happens too late, at this time guest JavaScript has already started to execute.

- other events seam to happens also too late.

So I haven't found a way to achieve what I want with electron.
It would be nice if the `webview.addContentScripts()` method will be supported in electron.

**Comment by smildlzj** [comment]
is it `preload` property looking for ?

**Comment by MarshallOfSound** [comment]
Inside your preload script you just need to asynchronously wait for whatever DOM API's you want to be ready.

E.g. you can wait for the `DOMContentLoaded` event or the `load` event on the window object.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by colindefais** [comment]
Hi @MarshallOfSound,

Maybe I have not explained myself well enough.

I want to execute code before the `DOMContentLoaded` event or the `load` event on the window object.
Because **if I do it on  `DOMContentLoaded`, guest web pages won't be able to use my injected code since it will be declared after the initialization of their script.**
In consequence, in my fake geolocation use case, if I redefine `navigator.geolocation` on `DOMContentLoaded` event there is a risk that guest page scripts are subscribing to the built-in `navigator.geolocation` instead of my custom code.

I need a way to manipulate the DOM (to inject `<script>` elements) before the guest page script loads.
This is possible in chromium applications by using [webview.addContentScripts()](https://developer.chrome.com/apps/tags/webview#method-addContentScripts) (using `run_at` property with `document_start` value).
But unfortunatelly `webview.addContentScripts()` is not implemented in electron.

So I guess my post is still a feature request. Can you please re-open it?
Thanks.

**Comment by MarshallOfSound** [comment]
My comment still stands, you just need to choose the event to listen to correctly.

```js
process.once('document-start', () => {
  console.log('this is the document start event');
})
```

**Comment by colindefais** [comment]
Thanks a lot!

If I do this in a `preload` script:
```javascript
process.once('document-start', () => {
    var script = document.createElement('script');
    script.textContent = 'navigator.geolocation.watchPosition = null;';

    document.documentElement.appendChild(script);
});
```
Then the guest scripts fail to use `navigator.geolocation.watchPosition`.
So I am now truly able to inject code just before execution of guest scripts.
This is exactly what I wanted to do!

Sorry for the inconvenience.

To avoid opening an issue next time, where can I find the documentation associated to `document-start` and the other events?

**Comment by smildlzj** [comment]
@colindefais 

this fllowing code wille execute before page script excute, sometime i use it to inject or mock system api
```
process.once('loaded', function() {

})
```

**Comment by colindefais** [comment]
@smildlzj

Thanks for the tip.

But when I listen to `loaded` it seams to be too soon: `document.documentElement` is undefined. I have also tried to use document.write() but this stops the loading of the page.

So I will stay on `document-start` which happens exactly when I want.

**Comment by syedadeel2** [comment]
too late for this question. but just for others, if you want to load the script before any other scripts loads use the preload.

```
main_window = new BrowserWindow({
    width: 850,
    height: 850,
    webPreferences: {
        preload: path.join(app.getAppPath(), 'preload.js')
    }
});
```

[https://www.electronjs.org/docs/tutorial/security#2-do-not-enable-nodejs-integration-for-remote-content](https://www.electronjs.org/docs/tutorial/security#2-do-not-enable-nodejs-integration-for-remote-content)
