### ISSUE TITLE
printToPDF does not allow pageRanges?

### ISSUE THREAD

**Issue by Hyperblaster** [electron/electron#13190]
* Electron Version: 2.0.2
* Operating System MacOS High Sierra:

**Expected Behavior**
Perhaps it's not documented but this does not work at all as
`webContents.printToPDF({pageRanges:1}, callback);`

**Actual behavior**
To print a PDF with only the pages specified

**To Reproduce**
Test it on any operating system in any version of electron

In this file
https://github.com/electron/electron/blob/b89fe86fa1f7c935046b5bbdd82ae645c01838a4/lib/browser/api/web-contents.js

there is what i believe a typo also on Line 62 it says 'pageRage':[] Should this not be pageRange? and if so, is there a way for us to override these defaultPrintSettings? Currently in the printToPDF function there is no way to change some of these settings, only the specific ones that the electron function overwrites

**Comment by Loilo** [comment]
According to the [`printToPDF()` documentation](https://electronjs.org/docs/api/web-contents#contentsprinttopdfoptions-callback), the `pageRanges` option is not supported at all.

The `pageRage` probably is a typo, but there also is no code in [the function's implementation](https://github.com/electron/electron/blob/b89fe86fa1f7c935046b5bbdd82ae645c01838a4/lib/browser/api/web-contents.js#L195-L234) that would actually use a (correctly spelled) `pageRanges` option.

So technically this isn't even a bug but it's exactly the documented behaviour.

**Comment by Hyperblaster** [comment]
I ended up just writing my own command line .exe file that prints properly with all the features, including page range.

And for mac i just use command line aswell, not a single printer package for electron or node would print correctly for me,

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by loilo** [comment]
The situation for this issue seems to have not changed in recent releases. The docs [still donm't mention](https://electronjs.org/docs/api/web-contents#contentsprinttopdfoptions-callback) a `pageRanges` option and it's apparently [not implemented](https://github.com/electron/electron/blob/v8.0.0-nightly.20190808/lib/browser/api/web-contents.js#L207-L252) in the latest nightly build as well.

**Comment by anderklander** [comment]
Would love to have this feature!
Like this: https://chromedevtools.github.io/devtools-protocol/tot/Page#method-printToPDF
Patching webcontents with the option did not seem to be enough …

Or add printToPdf option to the print function? Something like setting this when the option is true:
settings.SetIntKey(printing::kSettingPrinterType, printing::kPdfPrinter);

**Comment by codebytere** [comment]
@anderklander i'm planning to open a PR to address this soon
