### ISSUE TITLE
Only include Visual C++ runtime in the install directory if it is not already installed?

### ISSUE THREAD

**Issue by Siecje** [electron/electron#13197]
I am creating an installer for an application that depends on the Visual C++ runtime. I was looking at the  Microsoft VS code installation directory for an example of how to do this properly and I noticed the `api-*.dll` files are included in the installation directory[0].

On Windows 7 after all Windows updates these files are available in the system directory.

Are they also required in the installation directory?

Related: https://github.com/electron/electron/issues

0: https://github.com/Microsoft/vscode/issues/51386/10291

**Comment by MarshallOfSound** [comment]
This is not an Electron issue, how people install Electron apps is independent of this repository
