### ISSUE TITLE
Window gets maximized by double clicking disabled maximize icon

### ISSUE THREAD

**Issue by singhshashi** [electron/electron#13198]
* Electron Version: 2.0.2
* Operating System (Platform and Version): Darwin, macOS High Sierra 10.13.4
* Last known working Electron version: Unknown

**Expected Behavior**
I create a new browser window and set win.setMaximizable(false). The maximizable button is correctly disabled. Double clicking on it should not maximize the window. 

**Actual behavior**
Double clicking on the disabled maximize button maximizes the window. 

**To Reproduce**
If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone https://github.com/singhshashi/electron-quick-start.git -b bugMaximize
$ npm install
$ npm start || electron .
```
**Screenshots**

**Additional Information**
Very low priority

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
