### ISSUE TITLE
I can't get print in A6

### ISSUE THREAD

**Issue by leonardovff** [electron/electron#13199]
* Electron Version:
2.0.2
* Operating System (Platform and Version):
Ubuntu 17
**Expected Behavior**
Print the content with config size A6 using option silent = true or create pdf with A6 dimensions 

**Actual behavior**
I can't set the size of page of .print() with silenet = true, I tried to use @page {size: 16 or 10.5cm 14.8cm} but it isn't working. I tried to create a pdf with printToPdf size:a6, but return one error "Does not support pageSize with A6

**To Reproduce**
```javascript
mainWindow.webContents.print({
         deviceName: 'devicename',
         silent: true
       }, () => {
      });
```
or

```javascript
mainWindow.webContents.printToPDF({ 
marginsType:0, pageSize:"A6", landscape:false 
}, (error, data) {}
``

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by leonardovff** [comment]
@devsnaked can you help in this issue?
I don't the enviroment anymore.
