### ISSUE TITLE
Electron delay and reloading page not existing in browser after receiving an HTTP request 

### ISSUE THREAD

**Issue by amanganiello90** [electron/electron#13194]
* Electron Version: 1.8.1 to 2.0.2 (last)
* Operating System (Platform and Version): windows

**Expected Behavior**
The same of Chrome browser, that is not too dalay after an http request and without reloading page.

**Actual behavior**
The electron client reload the pages after receiving an HTTP request and performs a delay of two seconds. Instead, in Chrome browser  there isn't a reload and the delay is 500 ms.

**Comment by apescione** [comment]
I have the same issue, I've a jsp form that performs a submit to Spring security (j_spring_security_check).  After form submit, the server responses with a 302 http status  to redirect into main page of application. I have a different behavior between electron (several version between 1.7.9 to 2.0.2)  and chrome (last version). 
Electron, after 302,  I have a cancelled request and reload page. Besides I have a delay first to access to private area.
Chrome, instead, after 302 load immediately main page.
Me too I have 

- Electron Version: 1.8.1 to 2.02 (last)
- Operating System (Platform and Version): windows

**Comment by Ramu3l** [comment]
Hi apescione,

I have the same problem as you. Different electron version only.

- Electron Version: 1.7.9
- Chromium: 58.0.3029.110

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by amanganiello90** [comment]
Hi, thanks for the response.
Now I can't retry the scenario, but the behavior is the following:

> The electron client reload the pages after receiving an HTTP request and performs a delay of two seconds. Instead, in Chrome browser there isn't a reload and the delay is 500 ms.

You can try it with a generic test.

**Comment by codebytere** [comment]
Networking has been significantly rewritten in Electron.js following version 7, and this issue should no longer be present. In that event i'm closing this out, but should something new resurface i'm happy to reconsider the issue.
