### ISSUE TITLE
It doesn't work in typescript.

### ISSUE THREAD

**Issue by zhidaoliu** [electron/electron#13192]
* Electron Version: 1.7.6
* Operating System :windows 7
* Last known working Electron version: 1.7.6 
* Angular Version: 5.0.0
* Typescript Version: 2.4.2

**Expected Behavior**
I want to use electron in typescript in Angular 5.
I just want to know how to import electron into Angular 5's typescript.

**Actual behavior**
I use the code to import electron 
`const {shell} = require('electron')`       // or
`import electron from 'electron';
import { shell} from 'electron';` 
It doesn't work in typescript. It looks less friendly in typescript.

**Additional Information**
Can you solve my question？ 
Thank you!

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
