### ISSUE TITLE
Is there a way to access HTML elements in a child window from the parent window Javascript

### ISSUE THREAD

**Issue by CourtneyBurke** [electron/electron#13207]
More of a question than a feature request. I have a parent window and a child window. Is there a way I can access the child window HTML from the parent window JavaScript ?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
