### ISSUE TITLE
Web worker can not run after packaged

### ISSUE THREAD

**Issue by BruceAn1978** [electron/electron#13208]
* Electron Version: v2.0.2
* Operating System (Platform and Version): Win10 x64
* Last known working Electron version: 

**Expected Behavior**
The onmessage and postMessage function of web worker can interact well in after packaged.

**Actual behavior**
The onmessage and postMessage function of web worker can interact well in vs code dev invironment, but the postMessage function can not response to the caller after packaged.

**To Reproduce**
**html page**
  _var worker = new Worker('./js/uploader.js');
  worker.onmessage = function(evt)
  {
    console.log('callback:' + evt);
  };
  worker.postMessage('hello');_

**uploader.js**
  _onmessage = function(evt)
  {
    console.log(evt);
    postMessage('world');
  }_

**Comment by BruceAn1978** [comment]
**package cmd:** 
electron-packager ./ FileUpload --platform=win32 --arch=ia32 --out ./target --app-version 3.0.0 --overwrite --icon=./app/img/file.ico --ignore=.history --ignore=.vscode --ignore=__recovery

Is there any other parameters to solve this problem?
or some extra parameters to solve this problem?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by lvlrSajjad** [comment]
just add  your worker.js in files section under build in package.json like below
`"build": {
    "productName": "Electron Player",
    "appId": "io.lvlrsajjad.electronplayer",
    "copyright": "Copyright © 2018 Electron Player",
    "files": [
      "dist/",
      "node_modules/",
      "app.html",
      "myWorker.js",
      "main.prod.js",
      "main.prod.js.map",
      "package.json"
    ],`
