### ISSUE TITLE
Tray required icon

### ISSUE THREAD

**Issue by pjebs** [electron/electron#13202]
The Tray API requires an icon.

For windows it may be mandatory, but for mac I see lots of tray items that don't have a icon.
Perhaps they use a token 1x1 icon. Not sure. But it definitely seems like this is a bug for mac.

**Comment by pjebs** [comment]
The API for Tray/NativeImage suggests you can pass `null` but it does not work.
You have to explicitly pass: `nativeImage.createEmpty()`

**Comment by pjebs** [comment]
Reopened because after experimenting, passing `nativeImage.createEmpty()` is not the same as having no tray icon.

**Comment by pjebs** [comment]
thank you @miniak

**Comment by pjebs** [comment]
How do I use your enhancement? I tried npm update

**Comment by miniak** [comment]
@pjebs It's not merged yet, there is some unresolved discussion about the API
