### ISSUE TITLE
native emojis have wrong (or negative?) letter spacing

### ISSUE THREAD

**Issue by digitalstaub** [electron/electron#13206]
* Electron Version:1.8.6 -2.0.2
* Operating System (Platform and Version): Mac OS 10.13.4
* Last known working Electron version: 

**Expected Behavior**
after inserting a native amoji, cursor position should be at the end of emoji
**Actual behavior**
cursor position inside the emoji
**To Reproduce**
```sh
$ git clone https://github.com/digitalstaub/electron-quick-start.git  -b native-emojis
$ npm install
$ npm start || electron .
```
**Screenshots**
![bildschirmfoto 2018-06-09 um 15 28 28](https://user-images.githubusercontent.com/9270848/41192135-e9e0d84e-6bf9-11e8-89aa-221755dbd5db.png)

**Additional Information**
This seems to happen in every electron app, as well as in atom(screenshot). I tryed some other electron apps too. Doesn't happen in chrome or other Mac OS apps.

**Comment by digitalstaub** [comment]
I installed an old chrome browser and found that it has the same issues.
I guess it will be solved in the future with a newer chromium version.

**Comment by andreieftimie** [comment]
@digitalstaub shouldn't this issue be kept open until electron ships with a newer chromium version that has this issue fixed?

**Comment by avner-hoffmann** [comment]
I'm experiencing the same issue with electron 2.0.14

@digitalstaub - electron 2.0.14 is using chrome 61. I've just downloaded chrome 61 browser to check what you said about older browser versions, it doesn't reproduce in chrome 61 as it does it electron 2
Please reopen this issue so the electron folks can fix this asap. I don't think it's only browser related
If you don't want tell me and I'll open an issue myself.

Thanks

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
