### ISSUE TITLE
NPM found 9 vulnerabilities (1 low, 8 moderate)

### ISSUE THREAD

**Issue by HendrikEduard** [electron/electron#13205]
* Electron Version: + electron@2.0.2
* Operating System (Platform and Version): OSX Sierra
* Last known working Electron version: ??

**Expected Behavior**
No vulnerabilities.

**Actual behavior**
A clear and concise description of what actually happened.
added 49 packages from 53 contributors and audited 1640 packages in 66.988s
found 9 vulnerabilities (1 low, 8 moderate)

**To Reproduce**
Your best chance of getting this bug looked at quickly is to provide a REPOSITORY that can be cloned and run.
run NPN i electron in your terminal.

You can fork [electron-quick-start](https://github.com/electron/electron-quick-start) and include a link to the branch with your changes.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
![screen shot 2018-06-09 at 7 54 29 am](https://user-images.githubusercontent.com/16320682/41188199-6e28efa0-6bba-11e8-9b64-a5fd1c1cb758.png)

$ git clone $YOUR_URL -b $BRANCH
$ npm install
$ npm start || electron .
```
**Screenshots**

**Additional Information**

**Comment by codebytere** [comment]
We're aware of and working to resolve this, thank you!
