### ISSUE TITLE
Webview cookies don't seem to be persisted on quit.

### ISSUE THREAD

**Issue by VicXXX** [electron/electron#13200]
* Electron Version: 1.8.7
* Operating System (Platform and Version): MacOS

**Expected Behavior**
When I quit electron app I expect cookies set by the webview to still be there on start of the app.

**Actual behavior**
See it's very intermittent. Cookies are definitely set. I CMD+Q the app then start it has no cookies available in the debug tools app stops behaving as expected. But if I quit this one again and start it again cookies magically appear in the debug tools and app behaves as expected.  

I've noticed many people complain about that issue yet no solution has been given to why that is. Cookies definitely are set by my webapp if I open it in Chrome I can quit chrome come back to it works every single time. Electron sometimes it works and behaves as expected sometimes it just craps out and stops working for absolutely no reason and restarting it again magically makes it work again. Bit weird behaviour for an app that uses browserWindow.loadUrl().

**Comment by MarshallOfSound** [comment]
Cookies are only flushed to disk periodically, if the cookie is set and you quit too soon it won't be flushed to disk.

You can use the [`flushStore`](https://electronjs.org/docs/api/cookies#cookiesflushstorecallback) API to force cookies to be written to disk

**Comment by VicXXX** [comment]
@MarshallOfSound thanks for your reply although that doesn't explain the issue behind quitting the reopened instance that failed to read cookies. In that situation if I quit the app for the second time and restart it those cookies set in the first run that haven't been read in second run actually are being read in the third run so they are being flushed to disk but not read on second run.

**Comment by VicXXX** [comment]
BTW that flush store doesn't fix the issue.

**Comment by webtsys** [comment]
I have the same problem in windows.

**Comment by lovoror** [comment]
Add partition to webview tag to resolve this bug.
<webview src="https://github.com" partition="persist:github"></webview>

**Comment by lovoror** [comment]
`<webview src="https://github.com" partition="persist:github"></webview>`
