### ISSUE TITLE
Could not exec system command when packaged with electron-builder

### ISSUE THREAD

**Issue by specneeo** [electron/electron#13214]
* Electron Version:2.0.2
* Operating System (Platform and Version):mac os
* Last known working Electron version: none

**Expected Behavior**
when packaged with electron-builder, could exec system command (node,npm,mv,sed...)

**Actual behavior**
in js file, it could exec shell file correctly when ``` npm start ```:

##### debug.sh
``` 
node -v
npm -v
```

But if packaged with electron-buider, those command could not work, also some other system commands such as ``` mv ``` ``` sed ``` ``` ios-sim ```could not work.
does this is a bug ? or how to solve ?

many thanks.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by MarshallOfSound** [comment]
When running GUI apps on macOS they do not inherit the shell `PATH` variable so you can't run most system executables without an absolute path.

There is an npm package that fixes this:

https://www.npmjs.com/package/fix-path

**Comment by specneeo** [comment]
thanks @MarshallOfSound ,now problems has been solved. Thanks.

**Comment by JF-23** [comment]
I got to my resources using path like this:

```
const path = require ('path');
require('fix-path')();

var paths = process.env.PATH.split(path.delimiter);

var currentPath = paths[9].replace(/\s/g, '').split("/");
var strippedPath = currentPath.slice(0, currentPath.length-4).join("/");
var srcAppPath = strippedPath+"/Resources/app/src/resources"
```
