### ISSUE TITLE
Is there any way to make a good look installer?

### ISSUE THREAD

**Issue by Wello6143** [electron/electron#13210]
Hi, 
I'm trying to packaging my app. I see many videos on YouTube but the installers are silently and no asking users where to install. I prefer an installer like Visual Studio Code. 
So is there a package installer like that?
Sorry for my bad English :p.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by Wello6143** [comment]
Oh, sorry, I don't know. I will close this issue right now. :D
