### ISSUE TITLE
Infinite load of menu and white screen

### ISSUE THREAD

**Issue by vartana** [electron/electron#13217]
* Electron Version: 1.8.4
* Operating System (Platform and Version): Windows 2012

**Expected Behavior**
The app should load with its input boxes and buttons.

**Actual behavior**
The app seems to load within itself infinitely the menu bar and white window

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/133908/41235909-f54f3538-6da0-11e8-96b0-acd74e3daf3d.jpg)

**Additional Information**
The application loads properly on windows 7, 8 and 10

**Comment by codebytere** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on, `v1.8.4`, has been superseded by newer releases. In addition, there are newer branches that supersede that series. It would help us greatly if you could test this issue with the latest version (`v3.0.2`).

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above.. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
