### ISSUE TITLE
`base::GetProcId` is deprecated

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#13218]
As of Chromium `63.0.3239.150`

[base/process/process_handle.h#84](https://chromium.googlesource.com/chromium/src/+/63.0.3239.150/base/process/process_handle.h#84):
> New code should be using `Process::Pid()` instead.

**Comment by miniak** [comment]
`Process::Pid()` is not a direct replacement

**Comment by alexeykuzmin** [comment]
@miniak That's what the code says. I wish it were a search-and-replace task, but yeah, it would require slightly more effort.
