### ISSUE TITLE
browserWindow.loadFile fails html file with GET string in location

### ISSUE THREAD

**Issue by ZTiK** [electron/electron#13211]
Hey folks,

When I load a local .html file using browserWindow.loadFile it works as expected:
`browserWindow.loadFile('views/index.html);`

However, if I try to load the same file along with a GET string, I only get a blank page:
`browserWindow.loadFile('views/index.html?test=test');`

The workaround seems to be to use .loadURL instead and point it to file:// location.
This requires an absolute path from root of the filesystem instead:
`browserWindow.loadURL('file:///home/username/appname/views/index.html?test=test');`

I would understand it if .loadFile simply tries to load a file called '_index.html?test=test_' which ofcourse doesn't exist.
Am I right in my conclusion and is this expected behaviour for .loadFile?

With kind regards,

**Comment by MarshallOfSound** [comment]
@ZTiK Behind the scenes `loadFile` calls `url.format()` with the pathname being composed of the absolute path to your app and the string you passed in.  This means it is trying to resolve the querystring as part of the file path.

Loading an absolute path string template generated path has some issues, for your use case I'd recommend doing this.

```js
const url = require('url')

browserWindow.loadURL(url.format({
  slashes: true,
  protocol: 'file:',
  pathname: path.resolve(app.getAppPath(), 'views/index.html'),
  query: {
    test: 'test'
  }
});
```

**Comment by ZTiK** [comment]
Thanks for the explanation and the recommendation!

**Comment by ZTiK** [comment]
Just in case anyone copy/pastes the example, there is a closing ) missing:

```
const url = require('url')

browserWindow.loadURL(url.format({
  slashes: true,
  protocol: 'file:',
  pathname: path.resolve(app.getAppPath(), 'views/index.html'),
  query: {
    test: 'test'
  }
}));
```

That happens a lot to me too :x

**Comment by BrianHuf** [comment]
This is working for me on electron@5.0.6
`browserWindow.loadFile('views/index.html', { query: { test: 'test' }});
`
