### ISSUE TITLE
Electron doesn't work well with react, aws-amplify and a WebGL program compiled by Unity

### ISSUE THREAD

**Issue by exKAZUu** [electron/electron#13213]
* Electron Version: both 2.0.2 and 1.8.7
* Operating System (Platform and Version): Both Windows 10 and Mac OSHigh Sierra (10.13.5)
* Last known working Electron version: 1.7.15

**Expected Behavior**
There is no error. Electron shows some contents (iframe including Unity's WebGL program).

**Actual behavior**
- Electron screen is white
- Devtool is disconnected
- If removing https://github.com/UsideU/electron-react-aws-unity-issue/blob/master/renderer.js#L10 or https://github.com/UsideU/electron-react-aws-unity-issue/blob/master/renderer.js#L16, then the problem doesn't occur.

**To Reproduce**
I've created a minimum reproducible repository: https://github.com/UsideU/electron-react-aws-unity-issue

```sh
$ git clone https://github.com/UsideU/electron-react-aws-unity-issue
$ npm install
$ npm start
```

**Screenshots**
- Electron 2.0.2 (not working)
![image](https://user-images.githubusercontent.com/436237/41217107-c4022e54-6d91-11e8-8420-c850272d08be.png)

- Electron 1.7.15 (working well)
![image](https://user-images.githubusercontent.com/436237/41217735-c346ad76-6d93-11e8-9aec-c5a692f911bf.png)

**Additional Information**
Unity can generate programs using asm.js and WebAssembly. Both programs cannot work well.

**Comment by MarshallOfSound** [comment]
`aws-amplify` depends on `aws-sdk` which transitively depends on `natives`.

The `natives` module does not work with the version of node used in Electron 2.  And will probably never work again.  It does horrible hax to manipulate internal node code that actually causes a crash in Electron 2.0 and higher.

You should attempt to raise issues upstream to drop the dependency on natives.

**Comment by exKAZUu** [comment]
Thank you for the detailed explanation! I'll do it.

**Comment by exKAZUu** [comment]
@MarshallOfSound What is `natives`? Do you refer to https://www.npmjs.com/package/natives? I check my `node_modules`, but there is no `natives` directory.

**Comment by MarshallOfSound** [comment]
Yes that is the module I'm referring to, it's there somewhere it might be deep inside your `node_modules` though.  Run `npm ls natives` or `yarn why natives` depending on which package manager you use.

**Comment by exKAZUu** [comment]
@MarshallOfSound Thank you for the quick response. Hm, but, there is still no `natives`.

- `yarn why natives`
```
$ yarn why natives
yarn why v1.7.0
[1/4] 🤔  Why do we have the module "natives"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
error We couldn't find a match!
✨  Done in 0.29s.
```

- `npm ls natives`
```
$ npm ls natives
electron-quick-start@1.0.0 /Users/exkazuu/Projects/electron-react-aws-unity-issue
└── (empty)
```

Also, I confirmed `aws-amplify` worked well without Unity.

**Comment by MarshallOfSound** [comment]
Interesting 🤔 

Lemme 👀 at that repro

**Comment by exKAZUu** [comment]
Additionally, I confirmed the following things.

- If a program loads a WebGL program compiled by Unity after loading `react` and `aws-amplify` in the usual way, then the error occurs.
- If a program dynamically requires `aws-amplify` after loading `react` and a WebGL program compiled by Unity completely, then the error doesn't occur.

**Comment by exKAZUu** [comment]
There seems no issue on Electron 3, so I'll close this.
