### ISSUE TITLE
setTouchEmulationEnabled bug

### ISSUE THREAD

**Issue by lishoulong** [electron/electron#13216]
* Electron Version: 2.0.2
* Operating System (Platform and Version): mac 10.13.2
* Last known working Electron version: 

**Expected Behavior**
after set setTouchEmulationEnabled for browderWindow，expect webview contents in browderWindow can response touch event. For example the following tow images can both response touch move.

**Actual behavior**
the content touch event can partly be response. For example the swiper touch event(second image) can be triggered, but the whole page touch event(first image) can not be triggered.

**To Reproduce**
```
mainWindow = new BrowserWindow({
    title: "test",
    height: 810,
    useContentSize: true,
    width: 1260,
    webPreferences: {
      webSecurity: false,
      nodeIntegrationInWorker: true
    }
  });
const mainwebContents = mainWindow.webContents;

  // debugger部分
  try {
    mainwebContents.debugger.attach("1.1");
    const isDebuggerAttached = mainwebContents.debugger.isAttached()
  }catch(err){
    console.log('errerr', err);
  }
  mainwebContents.debugger.sendCommand('Emulation.setTouchEmulationEnabled', {
    enabled: true,
    configuration: 'desktop',
  }, function(err, result){
    console.log('resultresult', err, result);
  });
```
Actually, if I set the setTouchEmulationEnabled debugger event on the webview instance, the following two images touch events can both work. But I establish a chrome devtool remote debug on the webview, so the setTouchEmulationEnabled debugger event can not work, because below chrome version 63 one target can only use one debugger.

**Screenshots**
![image](https://user-images.githubusercontent.com/16568570/41226656-b7fbb7ca-6da4-11e8-8ed7-20693bff13b4.png)
![image](https://user-images.githubusercontent.com/16568570/41226683-cdfd6f64-6da4-11e8-8e6b-daa02927abda.png)

**Additional Information**

**Comment by peihexing** [comment]
mark

**Comment by peihexing** [comment]
@MarshallOfSound please help solve the problem

**Comment by lishoulong** [comment]
@miniak , please help.

**Comment by MarshallOfSound** [comment]
Mentioning random people will not get this issue fixed, it's actually quite annoying :smile:. Please refrain from doing so

**Comment by lishoulong** [comment]
OK，@MarshallOfSound
Maybe I am not explain clear for this question.

Now, my core question is when set Emulation.setTouchEmulationEnabled, the document scroll relative event can not be triggered  response of my touch move event.

Do you have some suggestion for this scene?

**Comment by peihexing** [comment]
@MarshallOfSound please help solve the problem

**Comment by hdwong** [comment]
+1

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
