### ISSUE TITLE
How to access the renderer process ( not GUI renderer process but another )

### ISSUE THREAD

**Issue by goel-sunny** [electron/electron#13223]
Hi ,

I am facing problem , because i have to put a heavy task in a process , i was thinking to put it in the main  process but it may be lock the all renderer process , or put in the renderer process ( i.e, GUI renderer process) also block the GUI , so When i see the task manager i found their is 3 process created for my single  electron based application .

 1-) main process
2.) GUI renderer process
3.) renderer process

I want to put my heavy load in the third renderer process , can anyone suggest me how to put that in the third process.

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
