### ISSUE TITLE
Electron application fails to launch on windows if --no-proxy-server is given through command line

### ISSUE THREAD

**Issue by abhieee23** [electron/electron#13226]
* Electron Version: 2.0.0, 1.8.2
* Operating System (Platform and Version): Windows 10
* Last known working Electron version: 1.8.2

**Expected Behavior**
Electron should launch with given command line switches as in https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md

**Actual behavior**
On windows, I am launching electron (from cmd shell) as electron <url> --no-proxy-server and it is failing. Whereas on MAC it is successful. 

Eg. electron https://www.google.co.in --no-proxy-server    fails.

As per https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md, it should succeed. 

I understand that using app.commandLine.appendSwitch can do what we want to achieve but it should not fail from command line argument as well.

**To Reproduce**
Use a windows OS, and electron version 2.0.0 (Maybe reproducible on older versions as well). Not reproducible on MAC OS.

**Comment by abhieee23** [comment]
@zcbenz

**Comment by Anuj16** [comment]
I am also facing the same issue.

**Comment by zcbenz** [comment]
This is forbidden to fix a security problem, you can find more about it at https://electronjs.org/blog/protocol-handler-fix, https://github.com/electron/electron/commit/c49cb29ddf3368daf279bd60c007f9c015bc834c, https://github.com/electron/electron/pull/13039.
