### ISSUE TITLE
Using affinity causes devtoolsExtensions to not work properly

### ISSUE THREAD

**Issue by chrisnojima** [electron/electron#13221]
* Electron Version: 2.0.2
* Operating System (Platform and Version): OSX
* Last known working Electron version: xx

**Expected Behavior**
If i load multiple windows with a shared affinity (cool) I can no longer load react-devtools (sad). If i remove the affinity flag it works again

**Actual behavior**
Should work with affinity 

**To Reproduce**
Load 2 windows with affinity: 'test' and load devtoolsExtensions

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
