### ISSUE TITLE
setAspectRatio should not be applied when in full screen mode

### ISSUE THREAD

**Issue by jeffcunat** [electron/electron#13225]
* Electron Version: 2.0.0
* Operating System (Platform and Version):
* Last known working Electron version: 

**Expected Behavior**
Window in full screen mode should not be affected by the ratio set with setAspectRatio.
Or we could be able to reset the aspect ratio when you listen to enter-full-screen event (but I did not succeed to do it)

**Actual behavior**
On Mac, when you have set an aspect ratio to a window  and you go in full screen mode, the window can be larger than the screen and the content is cropped.

**To Reproduce**
I have forked https://github.com/jeffcunat/electron-quick-start.git. 
I have set an aspect ratio to 4 and text-align right for the `<h1>` of the window.
When you go full screen, you see that the title is not visible. 

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone https://github.com/jeffcunat/electron-quick-start.git
$ npm install
$ npm start || electron .
```
**Screenshots**
![normal window](https://user-images.githubusercontent.com/29144811/41281801-aa496cec-6e32-11e8-9936-4697904c63f2.png)
![full screen window](https://user-images.githubusercontent.com/29144811/41281877-d376ad82-6e32-11e8-9e9b-ee5ac7164f8b.png)

**Comment by Pong420** [comment]
This work for me
```js
const win = new BrowserWindow({
  // ...
});

const defaultRatio = 16 / 9;

win.setAspectRatio(defaultRatio);

win.on("resize", () => {
  const ratio = win.isFullScreen() ? 0 : defaultRatio;
  win.setAspectRatio(ratio);
});
```

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by jeffcunat** [comment]
This issue does not occur anymore in electron 6.0.1 latest stable version.
The aspect ratio we set on the window is now ignored when we are in full screen mode (which is the right behavior)
