### ISSUE TITLE
Compatibility with Node Module Version 64 requested

### ISSUE THREAD

**Issue by quinton-ashley** [electron/electron#13231]
node: v10.4.0
macOS: 10.14 Developer Beta
```
'/Users/qashto/Documents/dev/apps/qodemate/node_modules/robotjs/build/Release/robotjs.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 57.
```

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by MarshallOfSound** [comment]
Please read [Using Native Node Modules](https://electronjs.org/docs/tutorial/using-native-node-modules) which explains how to build native modules for Electron

**Comment by quinton-ashley** [comment]
Thanks for the info!  I think the error thrown could be more helpful.

**Comment by quinton-ashley** [comment]
It still doesn't work for me and I don't understand why this is necessary.  Why won't electron work with modules built for the current Node.js version using NODE_MODULE_VERSION 64?
```
$ npm install --save-dev electron-rebuild
+ electron-rebuild@1.7.3
added 65 packages from 43 contributors and audited 1049 packages in 14.517s
found 5 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
qashto:qodemate qashto$ npm start

> qodemate@0.0.26 start /Users/qashto/Documents/dev/apps/qodemate
> electron .

starting Qodemate!
Pug interceptor registered successfully
^C
$ ./node_modules/.bin/electron-rebuild
✔ Rebuild Complete
$ npm start
```
In the console:
```
Error: Cannot find module 'robotjs'
```
