### ISSUE TITLE
White artefacts on windows 

### ISSUE THREAD

**Issue by VicXXX** [electron/electron#13236]
* Electron Version:2.0.2
* Operating System (Platform and Version): Windows 10
* Last known working Electron version: 1.8.7

**Expected Behavior**
The artefacts shouldn't be visible

**Actual behavior**
There are different shades of the same colour visible on Windows whereas it should be one solid colour this is not replicable on MacOS and looks to only affect Windows. The screenshot shows the blue bar which should be of 1 solid colour actually being 2 different shades and a bit of menu that has a drop shadow which also renders with artefacts. This is not replicable in browsers or on mac build.

Screenshot [https://imgur.com/ysRLSH5](https://imgur.com/ysRLSH5)

**Comment by sofianguy** [comment]
Can you provide steps to repro this please?

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
