### ISSUE TITLE
Webview not being garbage collected after removed from DOM

### ISSUE THREAD

**Issue by mjbvz** [electron/electron#13243]
* Electron Version: 2.0.2
* Operating System (Platform and Version): MacOS 10.13.4
* Last known working Electron version: 

**Expected Behavior**
In a renderer:

```js
//@ts-check

class MyWebview {

    constructor() {
        this.webview = document.createElement('webview');
        this.webview.partition = 'newpart';
        this.webview.src = 'https://example.com'

        document.body.appendChild(this.webview);

        this.didStartLoading = () => {
            const contents = this.webview.getWebContents();
            if (!contents) {
                return;
            }

            contents.session.webRequest.onBeforeRequest((details, callback) => {
                console.log('on-before')
                return callback({});
            });
        }

        this.webview.addEventListener('did-start-loading', this.didStartLoading, false);

        setTimeout(() => {
            this.webview.removeEventListener('did-start-loading', this.didStartLoading, false);
            document.body.removeChild(this.webview);
        }, 3000)
    }
}

new MyWebview();
```

After the webview is removed from the dom, I expect the `MyWebview` to be cleaned up

**Actual behavior**
Notice that a `MyWebview` is around in memory even after the webview is deleted from the dom.

**To Reproduce**

```sh
$ git clone https://github.com/mjbvz/electron-webview-leak.git
$ npm install
$ npm start.
```

1. On page, wait for webview to disapear.
1. Take memory snapshot
1. Notice that a `MyWebview` object is still around

**Screenshots**
<img width="1126" alt="screen shot 2018-06-13 at 7 57 08 pm" src="https://user-images.githubusercontent.com/12821956/41389137-fa3c784a-6f43-11e8-93b7-5c142f75ae56.png">

**Comment by guox191** [comment]
+1

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by mjbvz** [comment]
Just tested on electron 6.0.2 and confirmed the issue is still present. Note that you must  set `webviewTag: true` on newer electron versions

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by mjbvz** [comment]
This is no longer relevant for us since we switched to normal iframes
