### ISSUE TITLE
WebView history is broken if a webpage loads a navigation upon goBack() being called

### ISSUE THREAD

**Issue by charlesclu** [electron/electron#13249]
* Electron Version: 2.0.2
* Operating System (Platform and Version): macOS 10.13.2
* Last known working Electron version: N/A

**Expected Behavior**
WebView history remains correct after navigating with goBack()

**Actual behavior**
Some webpages, such as `https://twitter.com/`, load a navigation upon `goBack()` being called, (in this case it is a navigation to `https://twitter.com/`), and this navigation triggers `this.webContents.on('navigation-entry-commited')` before the navigation from `goBack()` does, resulting in the wrong blocks code being executed and the WebView history to be messed up.

Here's the relevant code in navigation-controller.js:
```
this.webContents.on('navigation-entry-commited', (event, url, inPage, replaceEntry) => {
      if (this.inPageIndex > -1 && !inPage) {
        // Navigated to a new page, clear in-page mark.
        this.inPageIndex = -1
      } else if (this.inPageIndex === -1 && inPage && !replaceEntry) {
        // Started in-page navigations.
        this.inPageIndex = this.currentIndex
      }
      if (this.pendingIndex >= 0) {
        // Go to index.
        this.currentIndex = this.pendingIndex
        this.pendingIndex = -1
        this.history[this.currentIndex] = url
      } else if (replaceEntry) {
        // Non-user initialized navigation.
        this.history[this.currentIndex] = url
      } else {
        // Normal navigation. Clear history.
        this.history = this.history.slice(0, this.currentIndex + 1)
        this.currentIndex++
        this.history.push(url)
      }
    })
```
```
NavigationController.prototype.goBack = function () {
    if (!this.canGoBack()) {
      return
    }
    this.pendingIndex = this.getActiveIndex() - 1
    if (this.inPageIndex > -1 && this.pendingIndex >= this.inPageIndex) {
      return this.webContents._goBack()
    } else {
      return this.webContents._loadURL(this.history[this.pendingIndex], {})
    }
  }
```
And here's a log of what happens, with some edits to point out where it all goes wrong:
```
this.history: [ 'about:blank', 'https://www.google.com/?gws_rd=ssl', 'https://twitter.com/' ]
goBack() called:
    this.pendingIndex changed to 1
    loadURL(https://www.google.com/?gws_rd=ssl) called
this.webContents.on('navigation-entry-commited' event triggered: <--- this should be from calling loadURL(https://www.google.com/?gws_rd=ssl), but it's not!
    "// Go to index." block executed:
        this.currentIndex changed to 1
        this.pendingIndex changed to -1
        this.history[1] changed to: https://twitter.com/  <--- !!!!!!! url is wrong! Expected to be https://www.google.com/?gws_rd=ssl
        this.history: [ 'about:blank', 'https://twitter.com/', 'https://twitter.com/' ] <--- !!!!!!! Now this.history is messed up
this.webContents.on('navigation-entry-commited' event triggered: <--- now this is from calling loadURL(https://www.google.com/?gws_rd=ssl), but it's after the previous weird navigation event
    "// Normal navigation. Clear history." block executed: <--- because of the previous event, this.pendingIndex was changed back to -1, so the wrong block of code is executed
        currentIndex is 1
        this.history sliced from 0 to (currentIndex + 1)
            this.history: [ 'about:blank', 'https://twitter.com/' ]
        currentIndex changed to 2
        "https://www.google.com/?gws_rd=ssl" pushed to history
            this.history: [ 'about:blank', 'https://twitter.com/', 'https://www.google.com/?gws_rd=ssl' ] <--- now this.history is really messed up
```

**To Reproduce**
see https://github.com/electron/electron/issues/9835
**Screenshots**
see https://github.com/electron/electron/issues/9835

**Comment by charlesclu** [comment]
I've come up with a possible solution, but I'm sort of new to git, so I'm still learning about pull requests.

Anyways, here the relevant code with the changes:

Here I've added a new property to the NavigationController, `this.navUrl = null`. `this.navUrl` is `null` if no specific url is supposed to be navigated to, but if a specific url is supposed to be navigated to, like specified in the `goBack()`, `goForward()`, and `goToIndex()` functions, then `this.navUrl` will be set to the specified url. On every `this.webContents.on('navigation-entry-commited')` event triggered, the function checks for a specified url, and if it exists, continues only if it matches the url that triggered the navigation event (and `this.navUrl` is reset to `null`).
```
this.navUrl = null
this.webContents.on('navigation-entry-commited', (event, url, inPage, replaceEntry) => {
      if (this.navUrl) {
        if (this.navUrl == url) {
          this.navUrl = null
        } else {
          return
        }
      }
      ...
})
```

Here I've added lines to assign specified urls to `this.navUrl`.
```
NavigationController.prototype.goBack = function () {
    if (!this.canGoBack()) {
      return
    }
    this.pendingIndex = this.getActiveIndex() - 1
    if (this.inPageIndex > -1 && this.pendingIndex >= this.inPageIndex) {
      return this.webContents._goBack()
    } else {
      this.navUrl = this.history[this.pendingIndex]
      return this.webContents._loadURL(this.history[this.pendingIndex], {})
    }
  }

  NavigationController.prototype.goForward = function () {
    if (!this.canGoForward()) {
      return
    }
    this.pendingIndex = this.getActiveIndex() + 1
    if (this.inPageIndex > -1 && this.pendingIndex >= this.inPageIndex) {
      return this.webContents._goForward()
    } else {
      this.navUrl = this.history[this.pendingIndex]
      return this.webContents._loadURL(this.history[this.pendingIndex], {})
    }
  }

  NavigationController.prototype.goToIndex = function (index) {
    if (!this.canGoToIndex(index)) {
      return
    }
    this.pendingIndex = index
    this.navUrl = this.history[this.pendingIndex]
    return this.webContents._loadURL(this.history[this.pendingIndex], {})
  }
```

**Comment by charlesclu** [comment]
Actually, the above is not a good fix, as it does not work if the previous page in history is the same url as erroneous navigation

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
