### ISSUE TITLE
Instructions to build entirely from source

### ISSUE THREAD

**Issue by kwill** [electron/electron#13246]
**Is your feature request related to a problem? Please describe.**
I am a free software developer. I want to build Electron from source, so that I don't rely on any third-party binaries.

[Building Chromium as a Library](https://electronjs.org/blog/electron-internals-building-chromium-as-a-library) explains clearly why and how to use a Chromium binary for convenience, but doesn't discuss how to use the Chromium source instead.

**Describe the solution you'd like**
Step-by-step instructions on how to build Electron entirely from source. (Sometimes called "complete corresponding source code".)

**Describe alternatives you've considered**
None found.

**Additional context**
N/A

**Comment by MarshallOfSound** [comment]
See https://github.com/electron/electron/blob/master/docs/development/README.md

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
