### ISSUE TITLE
Message box with "none" type or `null` icon doesn't remove default image on Linux

### ISSUE THREAD

**Issue by craxal** [electron/electron#13250]
* Electron Version: 2.0.0
* Operating System (Platform and Version): Linux Ubuntu 16.04
* Last known working Electron version: ???

**Expected Behavior**
When calling `dialog.showMessageBox` with `type: "none"` or `icon: null` options, I expect the resulting system dialog to have no icon.

**Actual behavior**
A generic (and undesirable) icon is used in the system dialog instead.

**To Reproduce**
1. Create the following menu item in the renderer process:
```js
{
    label: "About",
    click: () => {
        remote.dialog.showMessageBox(
            remote.getCurrentWindow(),
            {
                title: "My App",
                type: "none",
                icon: null,
                message: "I'm an About box.",
                detail: "You shouldn't see an icon.",
                buttons: ["OK"]
        }
    );
}
```
2. Launch the app and click the About menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/3473026/41439253-efe7fa22-6fde-11e8-8ef2-891acc3291f4.png)

**Comment by codebytere** [comment]
Resolved in https://github.com/electron/electron/pull/15326.
