### ISSUE TITLE
The display of Chart.js have strange problem

### ISSUE THREAD

**Issue by xlqstar** [electron/electron#13252]
* Electron Version:^2.0.0
* Operating System (Platform and Version): mac High Sierra 10.13.5
* Last known working Electron version: 

**Expected Behavior**
the chart app display have problem

**Actual behavior**
I want make a chart app with electron and Chart.js 

**To Reproduce**
every time

**Screenshots**
![image](https://user-images.githubusercontent.com/2224956/41456673-d3841aac-70b3-11e8-9745-d6cd9f070c35.png)

**Comment by sofianguy** [comment]
can you provide steps to reproduce this issue please?

**Comment by xlqstar** [comment]
I think this issue is related to this issue
#9765

**Comment by StephenOTT** [comment]
I am seeing this issue on 10.12 with MacBook Air 13inch Mid 2011 with Intel HD Graphics 3000 as well.

**Comment by codebytere** [comment]
This should be fixed via upstream upgrades in Chrome.
