### ISSUE TITLE
Build Error in Windows

### ISSUE THREAD

**Issue by githoniel** [electron/electron#13253]
* Electron Version: Master branch now
* Operating System (Platform and Version): Win10 10.0.17134.112

**Expected Behavior**
```
python script\bootstrap.py -v -d // return no error
python script\build.py
```

build OK

**Current Behavior**

get Error below
```
ninja: Entering directory `out\R'
ninja: error: 'C:/git/electron/vendor/download/libchromiumcontent/static_library/locales', needed by 'locales', missing and no known rule to make it

```

**Comment by MarshallOfSound** [comment]
`-d` only bootstraps the debug build (same as `--dev`).  Remove that parameter in order to build release builds
