### ISSUE TITLE
SIGPIPE crash when accessing stdin of badly spawned process

### ISSUE THREAD

**Issue by joaomoreno** [electron/electron#13254]
* Electron Version: 2.0.2
* Operating System (Platform and Version): Arch Linux up-to-date
* Last known working Electron version: ?

**Expected Behavior**

```script.js
var child_process = require("child_process");
var spawn = child_process.spawn;
var child = spawn('randomprocesswhichdoesnotexist', []);
child.on('error', () => console.log('got error'));
child.stdin.end('');
console.log('got to the end!');
```

When running this script with Node 8.9.3, everything works as expected:

```
$ node ~/Desktop/script.js                                             
got to the end!
got error
```

I expected this to run the same with Electron 2.0.2 and `ELECTRON_RUN_AS_NODE`.

**Actual behavior**

Instead this is the outcome:

```
$ ELECTRON_RUN_AS_NODE=1 ./.build/electron/code-oss ~/Desktop/script.js
$ echo $?
141
```

When using GDB, you'll notice a `SIGPIPE` error which likely causes Electron to crash:

```
$ ELECTRON_RUN_AS_NODE=1 gdb --args ./.build/electron/code-oss ~/Desktop/script.js
GNU gdb (GDB) 8.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./.build/electron/code-oss...(no debugging symbols found)...done.
(gdb) r
Starting program: /home/joao/Work/vscode/.build/electron/code-oss /home/joao/Desktop/script.js
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe7932700 (LWP 25373)]
[New Thread 0x7fffe7131700 (LWP 25374)]
[New Thread 0x7fffe6930700 (LWP 25375)]
[New Thread 0x7fffe612f700 (LWP 25376)]

Thread 1 "code-oss" received signal SIGPIPE, Broken pipe.
0x00007ffff68f9447 in write () from /usr/lib/libpthread.so.0
(gdb) q
A debugging session is active.

	Inferior 1 [process 25369] will be killed.

Quit anyway? (y or n) y
```

**To Reproduce**

Simply create that file and run it as mentioned above.

**Additional Information**

This affects https://github.com/Microsoft/vscode/issues/51750

**Comment by bpasero** [comment]
@joaomoreno this did reproduce in Electron 1.7.x right?

**Comment by joaomoreno** [comment]
@bpasero Did not check.

**Comment by bpasero** [comment]
With Electron 1.7.x I also do not see any console.log statement from your script.

**Comment by bpasero** [comment]
Xcode stack:

![image](https://user-images.githubusercontent.com/900690/44210061-b4176100-a165-11e8-9cf4-e37a8efcd0b9.png)

**Comment by bpasero** [comment]
The only workaround we have for VSCode is this piece of code:

```javascript
process.on('SIGPIPE', () => {
   console.log("No, please do not exit...");
});
```

**Comment by bpasero** [comment]
I am puzzled why this node.js check does not seem to work in Electron:

https://github.com/nodejs/node/blob/48813dee2794e2f6993b72655a8dbd3011a908ab/deps/uv/src/unix/core.c#L437

My understanding is that node.js specifically ignores `SIGPIPE` errors. 

Also on https://github.com/nodejs/node/blob/master/doc/api/process.md:

> 'SIGPIPE' is ignored by default. It can have a listener installed.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by joaomoreno** [comment]
Still happens on 6.0.1:

```
$ ELECTRON_RUN_AS_NODE=1 ../Downloads/electron-v6.0.1-linux-x64/electron script.js 
$ echo $?
141
```

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by bpasero** [comment]
This reproduces in Electron 12.
