### ISSUE TITLE
Can not add listener to "certificate-error" using Typescript

### ISSUE THREAD

**Issue by derek126** [electron/electron#13264]
* Electron Version: 2.0.2
* Operating System (Platform and Version): Win 10 64x
* Last known working Electron version: Unknown

**Expected Behavior**

No type error and I can add a listener to the "certificate-error" event

**Actual behavior**

TS2345: Argument of type '"certificate-error"' is not assignable to parameter of type '"window-all-closed"'.

**To Reproduce**

Using TypeScript 2.9.2

`app.on("certificate-error", (event: Electron.Event,
                            _1: Electron.WebContents,
                            _2: string,
                            _3: string,
                            certificate: Electron.Certificate,
                            callback: (isTrusted: boolean) => boolean) => {
  event.preventDefault();
  callback(true);
});`

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
