### ISSUE TITLE
New to Open Source Development

### ISSUE THREAD

**Issue by preethamkesineni** [electron/electron#13265]
Hello,

Sorry if this is the wrong place to type this stuff but I am a young programmer still in college right now and I wanted to branch into open source development. I have some knowledge on C++ language and programming. I was curious if I could get any guidance from other more seasoned open source developers on how to start in this field. Thank you and again sorry for posting this in the issue section of the repo, I know its probably not the best place to post it but I wasn't sure how else to get in contact with more professional open source developers. Thank you for your response.

-Preetham Kesineni

**Comment by sofianguy** [comment]
Hello,

Thanks for reaching out! The Electron issue tracker is for bug reports and feature requests. Please check out the Electron [community](https://github.com/electron/electron#community) and the [Slack Channel](https://atom-slack.herokuapp.com/). 

You can also check this list of OSS resources: https://gist.github.com/LizzHale/4b3a75c8f8060f9b8ac5
