### ISSUE TITLE
webview: resizing webview triggers resize event on window

### ISSUE THREAD

**Issue by bpasero** [electron/electron#13278]
* Electron Version: 1.7.x and 2.0.x
* Operating System (Platform and Version): macoS 10.13
* Last known working Electron version: unknown

**Expected Behavior**
The resize event should only be triggered when the window size changes.

**Actual behavior**
The resize event fires when the webview size is changed.

**To Reproduce**

**renderer.js**

```js
window.addEventListener('resize', () => {
    console.log("RESIZE");
});

setTimeout(() => {
    document.getElementById("foo").style.width = "100%";
}, 2000);
```

**HTML**
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
  </head>
  <body>
    <h1>Hello World!</h1>
    <!-- All of the Node.js APIs are available in this renderer process. -->
    We are using Node.js <script>document.write(process.versions.node)</script>,
    Chromium <script>document.write(process.versions.chrome)</script>,
    and Electron <script>document.write(process.versions.electron)</script>.

  <webview id="foo" style="width: 50%; height: 50%; border: 1px solid red;"></webview>

    <script>
      // You can also require other files to run in this process
      require('./renderer.js')
    </script>
  </body>
</html>
```

After 2 seconds there is a resize event on the Window once the webview resizes.

/cc @joaomoreno

**Comment by bpasero** [comment]
Reproduces in 3.0.x.

**Comment by sofianguy** [comment]
Hey, @bpasero does this issue still happen on [`3.0.0-beta.6`](https://github.com/electron/electron/releases/tag/v3.0.0-beta.6)? It includes a partial fix for the `webview` component.

**Comment by bpasero** [comment]
@sofianguy yes I can still reproduce with Electron 3.0.0-beta.6.

**Comment by joaomoreno** [comment]
👏
