### ISSUE TITLE
Wrong state of event object properties in MenuItem callback

### ISSUE THREAD

**Issue by njakob** [electron/electron#13289]
* Electron Version: 2.0.0
* Operating System (Platform and Version): Fedora 25
* Last known working Electron version:
Didn't tested all previous versions, however the bug is already present in 1.7.8

**Expected Behavior**
I'm currently trying to figure out if a `MenuItem` was triggered through the accelerator. This is possible to achieve through the information available in the `event` object of the `click` callback.

The structure seems to be the following but isn't currently [documented](https://electronjs.org/docs/api/menu-item).

```js
{
  shiftKey: boolean;
  ctrlKey: boolean;
  altKey: boolean;
  metaKey: boolean;
}
```

When a menu item is triggered through the accelerator, the corresponding flags should normally be set to `true`.

**Actual behavior**
This seems to work fine on MacOS. However, on both Windows (10) and Linux (Fedora 25) all this flags are always `false`.

**To Reproduce**
I quickly setup a [repository](https://github.com/njakob/electron-menuitem-bug) to test the current behavior and how to reproduce it.

```sh
$ git clone https://github.com/njakob/electron-menuitem-bug
$ npm install
$ npm start
```
On Fedora 25:
```js
{ shiftKey: false, ctrlKey: false, altKey: false, metaKey: false }
```
While on MacOS:
```js
{ shiftKey: false, ctrlKey: true, altKey: false, metaKey: false }
```

**Comment by JieJiSS** [comment]
I'm on macOS 10.12.4 and I have a similar issue.
Reproduced in
+ electron `v1.6.x`
+ electron `v1.8.x`
+ electron `v2.0.x`
+ electron `v3.0.0-beta1`

```js
console.log(Object.keys(event)); // [ "shiftKey", "ctrlKey", "altKey", "metaKey" ]
```

According to the `electron.d.ts` file, the `event` is an instance of `Electron.Event` and should be structured like

```ts
type GlobalEvent = Event;

declare namespace Electron {
  // ...
  interface Event extends GlobalEvent {
    preventDefault: () => void; // missing
    sender: WebContents; // ditto
    returnValue: any; // ditto
    ctrlKey?: boolean; // sometimes wrong, according to @njakob
    metaKey?: boolean; // ditto
    shiftKey?: boolean; // ditto
    altKey?: boolean; // ditto
  }
}
```
