### ISSUE TITLE
Application not exiting when there is a long running child

### ISSUE THREAD

**Issue by rudibravo** [electron/electron#13280]
* Electron Version: 2.0.2, 3.0.5, 4.0.0-beta
* Operating System (Platform and Version): Ubuntu 64
* Last known working Electron version: -

**Expected Behavior**
Calling `app.exit()` should close the main process even if there a long running detached child process.

**Actual behavior**
Main application only exits after the child process terminates.

**To Reproduce**
I've setup a quick test of this issue [here](https://github.com/rudibravo/electron-test).
```sh
$ git clone https://github.com/rudibravo/electron-test.git
$ cd electron-test
$ npm install
$ npm run start
```
Close the electron window, notice it prints the line inside the callback, right before `app.exit()`, but the process still running.
Killing the child process terminates the main process.

**Additional Information**
I was not able to reproduce it on macOS and Windows 10.

**Comment by rudibravo** [comment]
This is still not fixed on 3.0.5 or 4.0.0-beta

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
