### ISSUE TITLE
Node path.join fails on Windows 7 & Electron 2.0.2 - Possibly due to bug in Node 8.9.3, fixed in 8.10.0

### ISSUE THREAD

**Issue by Slapbox** [electron/electron#13287]
* Electron Version: `2.0.2`
* Operating System (Platform and Version): `Windows 7 x64`
* ~~Last known working Electron version: `1.8.4` (Not known - only possibly)~~

### Relevant NodeJS Bug Report: https://github.com/nodejs/node/issues/21392

**Expected Behavior**
Path.join always joins valid paths

**Actual behavior**
Path.join's first argument is passed in, but within the join function it is undefined, and it throws an error

**To Reproduce**
Specifically I am using [Auto-Launch](https://www.npmjs.com/package/auto-launch) and the exact implementation of this module seems to create the issue. Not a great way to reproduce it, but it's probably a NodeJS bug, so the fix seems to be upgrading NodeJS.

### Do we have any idea when Electron with Node 8.10.x will come out?

You can view the specific commit and fix here: https://github.com/nodejs/node/commit/2fce636f578b63fc0115e6c9f68157f6c4517145

>fix reading zero-length env vars on win32 (Anna Henningsen) [#18463](#18463)

**Comment by alexeykuzmin** [comment]
Probably fixed in https://github.com/nodejs/node/pull/18463.

**Comment by Slapbox** [comment]
Heh I already linked to that! But unfortunately, it seems not =(

I just went back to Electron 1.7.15 and I'm having the same issue even there with Node 7.9.0. According to the Node team, this bug didn't affect versions of node prior to `8.x.x`
