### ISSUE TITLE
can't drag file to the window of an  UAC electron app 

### ISSUE THREAD

**Issue by 149375580** [electron/electron#13288]
Electron version: 1.4.10  & UAC right
Operating system: windows 10

**Expected behavior**

I want to drag a file to the window of an electron app , But I can't do this, when I drag the file to the application window, the mouse cursor becomes disabled.

**Actual behavior**
the mouse cursor changes to disabled: 🛇
can't capture drag & drop event

**Comment by sofianguy** [comment]
Hi @149375580 is this still an issue on a newer version of Electron?

**Comment by sofianguy** [comment]
I'm going to close this issue because we are not supporting versions older than 1.7 right now. Let us know if you are still having this issue on a newer version and we'll reopen this issue.
