### ISSUE TITLE
Inverting tray text colour on macOS

### ISSUE THREAD

**Issue by johneas10** [electron/electron#13307]
* Electron Version: 2.0.2
* Operating System (Platform and Version): macOS 10.13.5
* Last known working Electron version: n/a

**Expected Behavior**
When running an application in macOS that has text in the tray (`tray.setTitle(...)`), and you toggle _use dark menu bar and dock_ in general settings, the text should invert colour.

**Actual behavior**
Text doesn't invert and becomes invisible until restarted.

**To Reproduce**
Any application that has text in the menubar next to the icon.
I have a small example here...
https://github.com/johneas10/cashBar/

`npm install`
`npm start`

**Screenshots**
<img width="102" alt="screen shot 2018-06-19 at 21 44 53" src="https://user-images.githubusercontent.com/18663222/41623492-e077e1e4-740a-11e8-8e8c-dc0c3fb064f3.png">
<img width="114" alt="screen shot 2018-06-19 at 21 44 45" src="https://user-images.githubusercontent.com/18663222/41623497-e201caac-740a-11e8-9217-c1678c1f4017.png">

**Comment by johneas10** [comment]
Although I've not tested Mojave yet, I imagine this issue (if it is an issue) will become more common with the new dark mode.

**Comment by miniak** [comment]
Seems to be fixed already!

Electron 2.0.2
<img width="99" alt="screen shot 2018-08-26 at 2 31 30 pm" src="https://user-images.githubusercontent.com/1281234/44628276-cbf89d00-a93c-11e8-958e-d99c5ba84e2c.png">

Electron 2.0.3
<img width="97" alt="screen shot 2018-08-26 at 2 31 41 pm" src="https://user-images.githubusercontent.com/1281234/44628277-cd29ca00-a93c-11e8-9e81-f827cda04c7e.png">

**Comment by johneas10** [comment]
Can confirm!

Thanks guys :)
