### ISSUE TITLE
Enable Crash Reporter tests on linux

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#13315]
"crashReporter module" tests have been disabled on linux during the Chromium 66 upgrade.

**Comment by jkleinsc** [comment]
I'm guessing it is related but it looks like crash reporter dumps are not properly formatted in 3-0-x.  This gist creates a crash but when I run it through minidump_stackwalk it throws some errors:
https://gist.github.com/084d9d7da2184e17cfdaab52ce6ee5fe
```
2019-02-25 16:06:37: minidump.cc:4754: ERROR: ReadString found odd-sized 7209065-byte string at offset 199280
2019-02-25 16:06:37: minidump.cc:1785: ERROR: MinidumpModule could not read name
2019-02-25 16:06:37: minidump.cc:2597: ERROR: MinidumpModuleList could not read required module auxiliary data for module 111/115
2019-02-25 16:06:37: minidump.cc:4864: ERROR: GetStream could not read stream type 4
```

**Comment by MarshallOfSound** [comment]
@jkleinsc Does the same thing happen for `4-0-x` / `master`.  Questioning if Chromium broke something then fixed it, or literally just changed the format 😄

**Comment by jkleinsc** [comment]
@MarshallOfSound 4-0-x works.  I'd have to test master.

**Comment by CapOM** [comment]
breakpad is going defunc, what about generating full debug symbols and do a zip for linux ? (in addition to breakpad symbol zip)

**Comment by CapOM** [comment]
I have a patch to generate these symbols, I will submit it soon

**Comment by CapOM** [comment]
PR submitted, I am not sure it is going to build at the first attempt as we use a different ci setup. Let's see.

**Comment by codebytere** [comment]
@CapOM i don't see the PR linked in this issue, can you link it?

**Comment by miniak** [comment]
CrashReporter tests are running on Linux (except for ARM)
