### ISSUE TITLE
Enable DCHECK in "base/process/process_metrics_win.cc"

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#13317]
https://github.com/electron/libchromiumcontent/commit/b9a68acb7e1f93193540cdf94f73ad6ba22c7900#diff-06a18c46f25200c5afcadf427f82f24d

Might be related to #13385.

**Comment by torycl** [comment]
The PR in Electron:
https://github.com/electron/electron/pull/13361

I want to check if it works now. Or to see the real error on CI machine - It works ok on my machine.

**Comment by MarshallOfSound** [comment]
@torycl It fails on CI but works on my local machine as well
