### ISSUE TITLE
FATAL:V8ObjectConstructor.cpp(97)] Check failed: get_prototype_value.

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#13316]
Run `BrowserWindow module "webPreferences" option "sandbox" option supports calling preventDefault on new-window events` test to reproduce.
The test itself passes though.

**Comment by MarshallOfSound** [comment]
This appears to be a new race condition in the destruction of prevented windows in sandboxed renderers, can't figure out exactly what's changed from 63->66 to cause this though
