### ISSUE TITLE
Enable focus/visibility/fullscreen-related tests

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#13321]
Some tests pass locally but do not pass on Mac CI machines.

- BrowserWindow module
  - BrowserWindow.getFocusedWindow()
  - BrowserWindow.alwaysOnTop() resets level on minimize
  - document.visibilityState/hidden
  - fullscreen state
  - kiosk state
  - exits HTML fullscreen when window leaves fullscreen
- webContents module
  - focus()

**Comment by ShankzPatil** [comment]
hi,

On Mac OS BrowserWindow.getFocusedWindow().minimize() function is not working while BrowserWindow is set to fullscreen: true;

in latest changes.

**Comment by codebytere** [comment]
Closing as these tasks have been split up into several tasks in https://github.com/electron/electron/projects/9
