### ISSUE TITLE
asar encryption

### ISSUE THREAD

**Issue by jiao12111** [electron/electron#13335]
ASAR unpacking is very simple. I want to customize the key. I hope you can give me some suggestions.

**Comment by MarshallOfSound** [comment]
This has been discussed before and declined, in order for the app to be able to be able to read its own archive it must contain the "key" required to unencrypt it.  This makes any encryption useless.

You should treat any code you put on the users machine as readable just like front end code for a web app, you can obfuscate as much as you like, people can still read it

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
