### ISSUE TITLE
Run Electron processes with System Privileges to manage UAC messages using remote desktop

### ISSUE THREAD

**Issue by matteoannibali** [electron/electron#13332]
* Electron Version: 2.0.1
* Operating System (Platform and Version): Win 10

Hi,
I need to run my electron processes as System in order to view and manage the Windows UAC messages for my Remote Desktop Application.

I use psexec -s but my processes run **WITH NO USER**

![41645385-236c6838-7471-11e8-8c44-e7c93813a4f7](https://user-images.githubusercontent.com/252208/41648541-7f06a35e-7479-11e8-88c4-dfc407903628.png)

Maybe it's for Electron Architecture?

I try everything..it's possible to run Electron processes with System Privileges ?? :(

Thanks for you help....i'm near to give up.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
