### ISSUE TITLE
about `sender` in the case of ipcRender.sendTo

### ISSUE THREAD

**Issue by lcllao** [electron/electron#13331]
* Electron Version: 2.0.2
* Operating System (Platform and Version): macOS 10.13.5
* Last known working Electron version: none

**Expected Behavior**

```javascript
//main process
ipcMain.on('pong',function(e) {
  console.log('in main process');
});
```

```javascript
//webview A
ipcRenderer.sendTo(webviewIdB,'ping');
ipcRenderer.on('pong',function(e) {
  console.log('in the right place')
})
```

```javascript
//webview B
ipcRenderer.on('ping',function(e) {
  e.sender.send('pong');
  console.log(e.sender.id); //  undefined
})
```
I expected that webview A would received the `pong`

**Actual behavior**
actually the main process received the `pong`

**Comment by MarshallOfSound** [comment]
@lcllao This is just a documentation issue, the `sendTo` method is actually just a helper to bounce messages through the main process to another renderer.

I.e.

```
webview A --> main --> webview B
```

In this case you can see the sender of the message that B receives would be the main process

**Comment by lcllao** [comment]
Yes, it's the main process.
In this case, why can't it be the real message sender?
If it doesn't , I must find some way to get current contentId and send it within the message data like `{data:{xxx},senderId:123}`,then use the senderId to reply the message by sendTo in the webview B.

**Comment by MarshallOfSound** [comment]
@lcllao If we made the sender the "real" sender (which wouldn't completely make sense) it would be a proxied version of the "sender" which would use synchronous IPC to work (basically using the `remote` module)

You should just send a `replyId` or something in your abstraction over IPC

**Comment by lcllao** [comment]
OK. Thanks.

By the way, is there any way to get the contentId inside the `webview` tag directly?
