### ISSUE TITLE
Awkward rendering while navigating inside webview tags

### ISSUE THREAD

**Issue by qazbnm456** [electron/electron#13356]
* Electron Version: v3.0.0-beta.1
* Operating System (Platform and Version): macOS High Sierra 10.13.6 Beta（17G39b）
* Last known working Electron version: v2.0.2

**Expected Behavior**
The website renders successfully.

**Actual behavior**
The rendering of the website seems to be awkward. It seems the website doesn't get rendered successfully, behaving like it's freezing. The website does navigate to the destination, though.

**To Reproduce**
Just add the webview tag loading any website and then navigate to another website.
```javascript
<webview src="https://example.com">
```
**Screenshots**
https://i.imgur.com/fHOLm3A.gifv

**Comment by ckerr** [comment]
'm merging this to #13503 since they seem to be the same issue.
