### ISSUE TITLE
[Bug] 3.0.0-beta1: DevTools - Inspector: select element failed

### ISSUE THREAD

**Issue by JieJiSS** [electron/electron#13357]
* Electron Version: 3.0.0-beta1
* Operating System (Platform and Version): macOS 12.4
* Last known working Electron version: v2.0.2

**Expected Behavior**
1. Open DevTools
2. click on the `select element` button, and it turns blue
3. move the cursor into the app's window, and the box-model of hovering elements will be shown
4. click on an element, and its source code will be displayed in the `Elements` tab.

**Actual behavior**

1. Open DevTools --- 🆗 
2. click on the `select element` button, and it turns blue --- 🆗 
3. move the cursor into the app's window, and the box-model of hovering elements will be shown --- 🆗 
4. click on an element, and its source code will be displayed in the `Elements` tab. --- 🤕 

Actually, I cannot let that `select element` button's color turn back to black unless I click the button again.

**To Reproduce**

See **Expected Behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/24671280/41702943-57ed86de-7564-11e8-9560-7bf4f3ed64d6.png)

**Additional Information**

and um, 
![image](https://user-images.githubusercontent.com/24671280/41703108-cf25ab82-7564-11e8-98b5-0571dd0aee24.png)
this is quite confusing

**Comment by JieJiSS** [comment]
ref #13395

**Comment by zcbenz** [comment]
I'm merging this to #13408 since they are essentially the same bug.
