### ISSUE TITLE
On right-click, request MenuItem.click(item, browserWindow, event) to be able to get the window's BrowserWindow instance (on macOS)

### ISSUE THREAD

**Issue by JieJiSS** [electron/electron#13360]
**Is your feature request related to a problem? Please describe.**
Currently, I'm using 

```js
menu.append(new MenuItem({
    label: "Always On Top",
    type: "checkbox",
    checked: false,
    click (item, rightclickWindow, ev) {
        // ...
    }
});
```

It works well when the being-clicked window has been focused, but I noticed that if I set a window to top, and click another window (which means that the Electron app loses focus), and directly right-click on that topped window, and an error occurs: `rightclickWindow` is `null`. Thus the electron app can't determine which window should be on top.

**Describe the solution you'd like**
when the being right-clicked window is not focused, the second arguments should also be an instance of `BrowserWindow`.

**Describe alternatives you've considered**
maybe
```js
click (item, bw, ev) {
    if(bw === null)
        bw = item.getClickedBrowserWindow();
    // ...
}
```
but as for me, this kind of design seems weird: the argument `bw` seems useless.

**Additional context**
According to https://github.com/electron/electron/blob/caa889e270a1df7ec0c0b174996f16f4e889fb76/lib/browser/api/menu-item.js#L52 (brance 1-8-x), it seems that a variable named `focusedWindow` is used to store the instance of BrowserWindow.

But on mac, right-click a window won't let it get focused, so clicked was actually called with `MenuItem`, `null`, `Event`.

**Comment by JieJiSS** [comment]
While reading through the source codes, I noticed that there are similar APIs such as

https://github.com/electron/electron/blob/475a1e30d9142f0506707eb92483e8a236a9f919/lib/browser/api/browser-window.js#L134
and

https://github.com/electron/electron/blob/475a1e30d9142f0506707eb92483e8a236a9f919/lib/browser/api/browser-window.js#L135
but in my case, `getFocusedWindow()` returns null, and `getAllWindows()` cannot help me to determine which window the user is interacting with.

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
