### ISSUE TITLE
BrowserWindow module unit tests end with crash on Windows

### ISSUE THREAD

**Issue by torycl** [electron/electron#13362]
**Electron Version** 
Debug master branch on Git, local build of shared library master branch of libcc
Just after Chromium-66 branch merge

**Operating System (Platform and Version)** 
Windows 10.0.17134.112 

**Expected Behavior**
When running api-browser-window-spec.js unit tests, the Electron.exe should not crash.

**Actual behavior**
When running api-browser-window-spec.js unit tests, the Electron.exe will crash while running one of tests from "BrowserWindow module beginFrameSubscription method subscribes to frame updates".

**To Reproduce**
1. api-browser-window-spec.js:20, make it "describe.only" to run only these tests.
2. `python script\test.py -c D --ci -v`, to run tests with output to console

**Additional Information**
It seems it is related with some memory leak. I see a lot of messages with:
`[47892:0621/120649.723:ERROR:render_process_impl.cc(217)] WebFrame LEAKED 1 TIMES`

If you run only one test in isolation, it will not crash. You have to run whole module. It will report memory leak however:
`[45556:0621/122402.546:WARNING:discardable_shared_memory_manager.cc(436)] Some MojoDiscardableSharedMemoryManagerImpls are still alive. They will be leaked.`

_Trace of the crash:_

Error: async hook stack has become corrupted (actual: 1023, expected: 0)
1: node::Environment::AsyncHooks::pop_async_id
2: node::InternalCallbackScope::Close
3: node::InternalCallbackScope::~InternalCallbackScope
4: node::InternalMakeCallback
5: node::MakeCallback
6: node::Environment::CheckImmediate
7: uv_check_invoke
8: uv_run
9: atom::NodeBindings::UvRunOnce
10: base::internal::FunctorTraits<void (__cdecl atom::NodeBindings::*)(void),void>::Invoke<base::WeakPtr<atom::NodeBindings> >
11: base::internal::InvokeHelper<1,void>::MakeItSo<void (__cdecl atom::NodeBindings::*)(void),base::WeakPtr<atom::NodeBindings> >
12: base::internal::Invoker<base::internal::BindState<void (__cdecl atom::NodeBindings::*)(void),base::WeakPtr<atom::NodeBindings> >,void __cdecl(void)>::RunImpl<void (__cdecl atom::NodeBindings::*)(void),std::tuple<base::WeakPtr<atom::NodeBindings> >,0>
13: base::internal::Invoker<base::internal::BindState<void (__cdecl atom::NodeBindings::*)(void),base::WeakPtr<atom::NodeBindings> >,void __cdecl(void)>::RunOnce
14: base::OnceCallback<void __cdecl(void)>::Run
15: base::debug::TaskAnnotator::RunTask
16: blink::scheduler::internal::ThreadControllerImpl::DoWork
17: base::internal::FunctorTraits<void (__cdecl blink::scheduler::internal::ThreadControllerImpl::*)(enum blink::scheduler::internal::Sequence::WorkType),void>::Invoke<base::WeakPtr<blink::scheduler::internal::ThreadControllerImpl> const &,enum blink::scheduler::internal::Sequence::WorkType const &>
18: base::internal::InvokeHelper<1,void>::MakeItSo<void (__cdecl blink::scheduler::internal::ThreadControllerImpl::*const &)(enum blink::scheduler::internal::Sequence::WorkType),base::WeakPtr<blink::scheduler::internal::ThreadControllerImpl> const &,enum blink::scheduler::internal::Sequence::WorkType const &>
19: base::internal::Invoker<base::internal::BindState<void (__cdecl blink::scheduler::internal::ThreadControllerImpl::*)(enum blink::scheduler::internal::Sequence::WorkType),base::WeakPtr<blink::scheduler::internal::ThreadControllerImpl>,enum blink::scheduler::internal::Sequence::WorkType>,void __cdecl(void)>::RunImpl<void (__cdecl blink::scheduler::internal::ThreadControllerImpl::*const &)(enum blink::scheduler::internal::Sequence::WorkType),std::tuple<base::WeakPtr<blink::scheduler::internal::ThreadControllerImpl>,enum blink::scheduler::internal::Sequence::WorkType> const &,0,1>
20: base::internal::Invoker<base::internal::BindState<void (__cdecl blink::scheduler::internal::ThreadControllerImpl::*)(enum blink::scheduler::internal::Sequence::WorkType),base::WeakPtr<blink::scheduler::internal::ThreadControllerImpl>,enum blink::scheduler::internal::Sequence::WorkType>,void __cdecl(void)>::Run
21: base::OnceCallback<void __cdecl(void)>::Run
22: base::debug::TaskAnnotator::RunTask
23: base::internal::IncomingTaskQueue::RunTask
24: base::MessageLoop::RunTask
25: base::MessageLoop::DeferOrRunPendingTask
26: base::MessageLoop::DoWork
27: base::MessagePumpDefault::Run
28: base::MessageLoop::Run
29: base::RunLoop::Run
30: content::RendererMain
31: content::RunNamedProcessTypeMain
32: content::ContentMainRunnerImpl::Run
33: content::ContentServiceManagerMainDelegate::RunEmbedderProcess
34: service_manager::Main
35: content::ContentMain
36: wWinMain
37: invoke_main
38: __scrt_common_main_seh
39: __scrt_common_main
40: wWinMainCRTStartup
41: BaseThreadInitThunk
42: RtlUserThreadStart

**Comment by MarshallOfSound** [comment]
> [45556:0621/122402.546:WARNING:discardable_shared_memory_manager.cc(436)] Some MojoDiscardableSharedMemoryManagerImpls are still alive. They will be leaked.

Haven't seen the crash before, but this warning is unrelated 👍

**Comment by torycl** [comment]
Thanks for info.
I can confirm, the same error happens with libcc binaries downloaded in bootstrap.py script (github-janky-artifacts/libchromiumcontent/win/x64/2006b899d1927dd260ea0f170bdf01c2d5eda6a1/libchromiumcontent.tar.bz2)
