### ISSUE TITLE
Calling setResizable(false) and then setResizable(true) changes maximizible state of window

### ISSUE THREAD

**Issue by CliffReimers** [electron/electron#13373]
* Electron Version: 2.0.2
* Operating System (Platform and Version): Win10 x64 version 1803
* Last known working Electron version: 1.9.0

**Expected Behavior**
Calling win.setResizable(false) and then win.setResizable(true) should return the window to it's original state. Specifically, it should not change the result of win.isMaximizable().

**Actual behavior**
Calling win.setResizable(false) and then win.setResizable(true) results in the window not being maximizable. The maximize button is disabled and win.isMaximizable returns false.

**To Reproduce**
In any electron application with a window that is resizable, call win.setResizable(false) and then win.setResizable(true). The window will now be impossible to maximize.

**Comment by Kthulu120** [comment]
Issue was replicated on 3.0.0

**Comment by Kthulu120** [comment]
Currently there are options when addressing this PR, we can allow the status quo of `!resizable` implies `!maximizable` while fixing `resizable` toggling `maximizable` or we can change the behavior of `setResziable` which will cause developers to have to explicitly call `setMaximizable(false)`. This may be significant for some apps. But my suggestion is that in the end this provides more functionality that the developer controls that may allow for unforseen use cases. So I think the PR as is serves my suggestion as is, though I believe both options are right. If anyone has any objections feel free to comment.
