### ISSUE TITLE
Webview navigation is broken in 3.0

### ISSUE THREAD

**Issue by PalmerAL** [electron/electron#13374]
* Electron Version: 3.0.0-beta.1
* Operating System (Platform and Version): macOS 10.13
* Last known working Electron version: 2.0

**Expected Behavior**

* Clicking a link in a webview should navigate to that page.

**Actual behavior**

* When I click a link inside a webview, the webview freezes completely. However, the webview devtools appear to work correctly, so it appears that the page is actually being loaded, and just not being displayed.

**To Reproduce**

```
<!DOCTYPE html>
<html>
  <head>
  </head>
  <body>
    <webview src="https://electronjs.org/"/>
  </body>
</html>
```

**Comment by vbkaisetsu** [comment]
Duplicated with #13356

**Comment by danielbeck** [comment]
Was about to file this as a separate issue but it's probably a duplicate:  the same occurs if the `<webview>` src attribute is modified programmatically. The new page does appear to render -- you even can query the getClientBoundingRect of DOM elements in the new page and get correct results -- but it's not being displayed to the user.

**Comment by sofianguy** [comment]
please follow #13356 for updates
