### ISSUE TITLE
[3.0.0-beta.1] SSL content all fails to load in windows with error "net::ERR_SSL_PROTOCOL_ERROR"

### ISSUE THREAD

**Issue by levinunnink** [electron/electron#13375]
* Electron Version: 3.0.0-beta.1
* Operating System (Platform and Version): Windows 10 Enterprise Edition
* Last known working Electron version: 2.0.2

**Expected Behavior**
I should be able to load `https` content in the BrowserWindow.

**Actual behavior**
All https requests fail regardless of host. The error in the inspector is `net::ERR_SSL_PROTOCOL_ERROR`. 

**To Reproduce**
Clone the electron quick start on Windows 10. Update the package to use 3.0.0-beta.1 and try to navigate to any https url. I've tried this on two separate systems and it gives the same error.

**Screenshots**
- The environment: https://d.pr/i/staLUG
- The error in the dev console: https://d.pr/i/1B7kO1

**Comment by levinunnink** [comment]
*Update:* Same error on a fresh install of Windows 7. https://d.pr/i/tfNsop Is anyone able to get 3.0.0-beta.1 to load SSL on windows?

**Comment by IAmPicard** [comment]
I'm getting the same errors with 3.0.0-beta.1, it fails to load any https resource; well, back to 2.0.3 for me 😄

**Comment by mediaslav** [comment]
having similar issue, Electron 3/Win10
![image](https://user-images.githubusercontent.com/472418/41869734-9516ae80-78c2-11e8-971f-90371d373c30.png)

**Comment by MarshallOfSound** [comment]
`3.0.0-beta.2` now correctly loads SSL content, closing this out.  If you are still experiencing 100% SSL failures on `3.0.0-beta.2` please @ mentioned me below

**Comment by soundar78** [comment]
We are using electron version 3.0.9, where most of the request fails with the above mentioned console error (net::ERR_SSL_PROTOCOL_ERROR). We load our app in a webview.
This is happening to different files every time and prevents the app from loading and happens on all platforms.
@MarshallOfSound its not 100% failure, but still most requests are failing and making the app unusable. please check this.

**Comment by soundar78** [comment]
![image (8)](https://user-images.githubusercontent.com/40226633/60092457-aeff4700-9764-11e9-9297-3ac3492d444e.png)
@MarshallOfSound 
This is how it looks when the app is loaded.
The same error "net::ERR_SSL_PROTOCOL_ERROR" is shown.
this happens in all OS.
kindly look into this. its very critical for our app.

**Comment by tytech3** [comment]
I'm getting ERR_SSL_PROTOCOL_ERROR even with webSecurity set to false. My API isn't even receiving the call. Chrome is just flat out refusing.
