### ISSUE TITLE
Lighthouse Audit not working in electron 2

### ISSUE THREAD

**Issue by ahmedmohamedali** [electron/electron#13382]
* Electron Version:  v2.0.3
* Operating System (Platform and Version): Windows 7 professional

**Expected Behavior**
Lighthouse Audit tool should perform the analysis of the page and displays the result as it does in chrome

**Actual behavior**
The "Run Audit" action does nothing

**To Reproduce**
Navigate to any http/https page in electron and open the chrome dev tools. Then activate the "Audit" tab and click on the "Perform an audit ..." button.  Select any item in the "Audit to perform" window and then click on the "Run Audit"  button
==> Result: Nothing happens

**Comment by peturh** [comment]
Same thing noted on Linux 4.15.0-33-generic Ubuntu 18.04.1 LTS and electron@2.0.9

But something actually happens, the screen gets into mobile view. Then nothing happens.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by Mqleaf** [comment]
Lighthouse Audit is not working in electron 7.1.1.
I can click the audit button, but no response, so I open the devtools of the page devtools, it is a error "AuditsService is not defined". 

![image](https://user-images.githubusercontent.com/22488004/71304812-7df78a80-2406-11ea-9aa0-9fc48eb11084.png)
