### ISSUE TITLE
[Linux] Menubar background color is always white

### ISSUE THREAD

**Issue by inukshuk** [electron/electron#13381]
* Electron Version: 2.x, 3.x
* Operating System (Platform and Version): Linux
* Last known working Electron version:  1.8

**Expected Behavior**
I would expect the menubar's background color to use a background based on the GTK theme. Up to Electron 2.0 this used to work (albeit only for the light theme variant), see for example the screenshot below:

![screenshot from 2018-06-22 11-20-21](https://user-images.githubusercontent.com/325102/41769175-b76bc922-760e-11e8-8b55-d0f7cc20fe0c.png)

**Actual behavior**
In Electron 2.x and 3.x the menubar is always white. Using both the light and dark theme variant. 

![screenshot from 2018-06-22 11-19-32](https://user-images.githubusercontent.com/325102/41769298-1a69ad1e-760f-11e8-8643-99828bc77779.png)

![screenshot from 2018-06-22 11-19-55](https://user-images.githubusercontent.com/325102/41769301-1fb9017a-760f-11e8-9993-6f479ffef826.png)

**To Reproduce**
This is reproducible for me with Electron Quick Start. Is it supposed to be this way or might this be caused by my Desktop configuration?

**Comment by clobrano** [comment]
Making some tests, it looks like menubar is always taking the style from Adwaita theme. In fact, configuring gtk3 to "prefer dark" (see below), the menubar becomes black, following Adwaita-dark theme

```
$ cat ~/.config/gtk-3.0/settings.ini 
[Settings]
gtk-application-prefer-dark-theme=1
```

**Comment by Cobinja** [comment]
This is probably due to https://github.com/electron/electron/blame/master/atom/browser/ui/views/menu_bar.cc#L127 where the menu bg color is fetched instead of the menubar bg color, which can be totally different depending on the used gtk3 theme.

**Comment by inukshuk** [comment]
@Cobinja is right, the color returned is the GTK theme's menu background (changing that color in the theme changes the menu bar). I'm guessing Chromium defines only that color because it does not use a menu bar at all? So this might be problematic, because on quick glance I can't find an appropriate color id constant for the menu bar, nor is there any constant, [that I can find](https://cs.chromium.org/chromium/src/chrome/browser/ui/libgtkui/native_theme_gtk.cc?sq=package:chromium&g=0&l=84), which would use the `GtkMenuBar#menubar` selector (which we would need, I think?).

Is it possible to call Chromium's [GetColor](https://cs.chromium.org/chromium/src/chrome/browser/ui/libgtkui/gtk_util.h?sq=package:chromium&g=0&l=189) directly?

**Comment by codebytere** [comment]
@inukshuk took a stab at this, PR here: https://github.com/electron/electron/pull/14785

**Comment by inukshuk** [comment]
@codebytere this looks great, thanks!

**Comment by inukshuk** [comment]
Just tested and it works well:

![screenshot from 2018-09-26 13-25-00](https://user-images.githubusercontent.com/325102/46077179-3eed7180-c190-11e8-9ff9-8ab12805ddfb.png)

There is a tricky problem related to dark mode: when creating a window with the `darkTheme` option, the menu bar will still use the theme's light variant.

![screenshot from 2018-09-26 13-26-26](https://user-images.githubusercontent.com/325102/46077249-79570e80-c190-11e8-81f3-e225eab8a00b.png)

It's possible to 'fix' this as a user by forcing the dark theme variant for the process (e.g., by setting the `GTK_THEME` environment variable).

![screenshot from 2018-09-26 13-28-25](https://user-images.githubusercontent.com/325102/46077403-0bf7ad80-c191-11e8-8a53-d4f549066911.png)

This is already much improved, but ideally, we should take the `darkTheme` option of the window into account to allow an app to create windows using either the dark or light variant.

**Comment by codebytere** [comment]
@inukshuk if you'd be interested, i'd be happy to pair with you on a PR for this? I can try to address this later but also if you'd want to contribute i can also help that effort!

**Comment by inukshuk** [comment]
@codebytere thanks for the offer, I'd very much like to contribute, if it makes sense. Now that macOS also has proper light and dark modes, I wonder if a common approach to this issue wouldn't be warranted? At the moment, there is only the `darkTheme` option when creating new window and the `systemPreferences.isDarkMode` -- but I do wonder if there shouldn't be an option, similar to `darkTheme` on Linux for macOS now to specifically create a window in the right mode.

Our app already has a light and dark theme; on macOS we're using a frameless window, but now there seems to be a new kind of highlight/shadow built into all windows: in light mode it is almost white, while in dark mode it is a little bit darker. Now, it seems to me as if Electron's frameless window always gets the light variant, even when the system preferences is switched to dark mode. See here for example:

<img width="1277" alt="screenshot 2018-09-27 at 15 17 09" src="https://user-images.githubusercontent.com/325102/46148903-62d0b600-c269-11e8-8774-7b3939f3e7de.png">

Here you see a few dark mode windows and the Electron window in the middle. Notice how the line at the top is much lighter than for the other windows; also the traffic lights are much lighter in the Electron window. I would argue that we probably need a `darkMode` option on macOS or use `darkTheme` for both Linux and macOS. Do you think this is right?

**Comment by MarshallOfSound** [comment]
@inukshuk let's not mix the issue of mojave dark mode support and GTK theming.  Mojave dark mode has a different set of APIs and expectations to GTK theming.

See this PR for what I'm doing to support Mojave dark mode: https://github.com/electron/electron/pull/14755

As for the white line you are seeing at the top of all your windows on mojave, see #13164

**Comment by Cobinja** [comment]
While the menubar background works now, its foreground color remains that of menu, not that of menubar. Should I open a new issue for that can we handle it here?

**Comment by galgalesh** [comment]
The issue that @Cobinja mentions is tracked here: Upstream issue: https://github.com/electron/electron/issues/15194

> it seems the foreground color for the menubar is being pulled from the context menu color, not the menubar foreground color.

So this affects themes where the menu bar and context menu foreground color are different: Ubuntu 18.10 but not Ubuntu 18.04.

**Comment by inukshuk** [comment]
I think I figured it out, please see #15878

**Comment by soundar-m** [comment]
This issue still exists in  fedora 37 when using electron 21.3.0
