### ISSUE TITLE
Add drag and drop events for Tray on windows

### ISSUE THREAD

**Issue by dougludlow** [electron/electron#13389]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Currently, all drag and drop events on the Tray are only available on macOS ([tray.md#event-drop-macos](https://github.com/electron/electron/blob/f068ed9ee744c18e90cb30b02365ce2278083bee/docs/api/tray.md#event-drop-macos) for example). This is a feature request to make them available for the Tray on Windows as well, assuming there is a solution available...

**Describe alternatives you've considered**
I'm unaware of any other alternatives...

**Additional context**
N/A

**Comment by miniak** [comment]
@dougludlow Windows API does not support this
