### ISSUE TITLE
"did-finish-load"/"ready-to-show" not emitted by webview which contains an iframe

### ISSUE THREAD

**Issue by ncortines** [electron/electron#13386]
* Electron Version: 2.0.0
* Operating System (Platform and Version): macos 10.13.5, Windows 10
* Last known working Electron version: I'm not sure if it's ever worked

**Expected Behavior**
"did-finish-load"/"ready-to-show" should be emitted by webview

**Actual behavior**
"did-finish-load"/"ready-to-show" are not emitted by webview

**To Reproduce**
I have a webview which is rendered inside a browserwindow container.
The webview is initially positioned outside the viewport while loading a remote url.
In the meanwhile I wait for "did-finish-load"/"ready-to-show" events.
Normally those events are emitted but in case the webview contains an iframe with another remote url, those events are never emitted.
Checking "isLoading" function on the webview is initially "false". When the "did-frame-finish-load" event is emitted by the webview, "isLoading" returns false. That's the workaround I'm using.
Another interesting thing is that the first time the webview loads it works.
Issue is experienced upon subsequent loads, so I believe it has something to do with cache.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
