### ISSUE TITLE
Webrtc Create answer error

### ISSUE THREAD

**Issue by metehanm4** [electron/electron#13380]
* Electron Version: v3.0.0-beta.1
* Operating System (Platform and Version): Ubuntu 17.10
* Last known working Electron version: 2.0.3

**Expected Behavior**
Trying to make webrtrc video call.

**Actual behavior**
Getting the error at below while createAnswer proccess.
ERROR : "Failed to set remote offer sdp: Failed to set remote video description send parameters."
My offer Sdp : https://gist.github.com/metehanm4/75af025e09a332511101a64c407df0cc

**Additional Information**
My app running  as expected on chromium 66 without electron.

**Comment by jaycharles** [comment]
I see the same.... seems there's no h.264 codec available for webrtc?

**Comment by ckerr** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unneccessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you've responded, please link to the test case and @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by metehanm4** [comment]
INFO : My app running as expected on Electron v3.0.0-beta.9. This problem solved.
