### ISSUE TITLE
`ProcessMetrics::GetMemoryBytes` have been removed in Chromium 67

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#13383]
https://chromium-review.googlesource.com/969089

Electron uses it for [`process.getProcessMemoryInfo()`](https://electronjs.org/docs/api/process#processgetprocessmemoryinfo):

https://github.com/electron/electron/blob/57d365a9f445774edf83d3d26250cd0eea39b12e/atom/common/api/atom_bindings.cc#L170

and [`app.getAppMetrics()`](https://electronjs.org/docs/api/app#appgetappmetrics) API:

https://github.com/electron/electron/blob/57d365a9f445774edf83d3d26250cd0eea39b12e/atom/browser/api/atom_api_app.cc#L1127

**Comment by alexeykuzmin** [comment]
@codebytere 
One of the options is to remove `privateBytes` and `sharedBytes` fields populated by those calls after we upgrade to Chromium 67.
But it would require us to deprecated them first.

**Comment by codebytere** [comment]
No longer used in core.
