### ISSUE TITLE
[v3.0.0-beta.1] Dev tools opens not focused on the appropriate part of HTML, just on <body>

### ISSUE THREAD

**Issue by nehbit** [electron/electron#13395]
* Electron Version: [v3.0.0-beta.1]
* Operating System (Platform and Version): OS X 10.12
* Last known working Electron version: 2.0.3

**Expected Behavior**
Right click / inspect on a DOM element should open the inspector's "elements" tab with the appropriate DOM node highlighted. For example, for a DOM that is:

```html
<html>
<head></head>
<body>
   <p>
      Example
   </p>
</body>
</html>
```

Selecting "Example" and right clicking to select "inspect" on it should open the inspector with the appropriate ```<p>``` element selected.

**Actual behavior**
In v3.0.0-beta.1, what happens is that it is always the ```<body>``` tag that is selected.
I've reverted to 2.0.3 and it now works. This is the code I'm using to call the context menu:
```js
...
label: 'Inspect Element',
click() {
win.inspectElement(props.x, props.y);
	if (webContents(win).isDevToolsOpened()) {
	webContents(win).devToolsWebContents.focus();
	}
}
...																				
```
Here's the [full code](https://github.com/sindresorhus/electron-context-menu/blob/master/index.js). (It's from a small library that I'm using).

Hope it helps.

**Comment by jkleinsc** [comment]
This issue is fixed in via #13571 for 3.0.0-beta.2 (just released)
