### ISSUE TITLE
User Agent API

### ISSUE THREAD

**Issue by kevinsawicki** [electron/electron#134]
Where is `Atom/VERSION` added to the `navigator.userAgent` string?

I tried to search through the code but couldn't find it.

**Comment by bmcminn** [comment]
I have a need around injecting my own custom user agent string to emulate a specific mobile device profile. I found the following documentation on session `webRequest` https://github.com/atom/electron/blob/master/docs/api/session.md#seswebrequest but implementing it has proven challenging.

I'm trying to do this in the context of the `electron-har` project https://github.com/shyiko/electron-har/issues/7 where Electron is run headlessly utilizing chromium's devtools to generate a HAR document.

Additionally, if there are any docs around utilizing the existing dev tools device user agent profiles per the mobile emulation system, I would appreciate any help in either regard.
