### ISSUE TITLE
3-0-x build failed with "'v8.lib' was created with an older compiler" error

### ISSUE THREAD

**Issue by emmkimme** [electron/electron#13409]
* Electron Version: 3.0.x (957f008726f3f2ac6e1bb5f67efad50124701772 - 23/06)
* Operating System (Platform and Version): Windows 10 x64 (buid 10240)
* Microsoft Visual Studio Professional 2017 - Version 15.7.3
* node v8.9.3
* npm 3.10.10
* Python 2.7.15

I followed the procedure step by step and my compilation stops with :

`[938/1232] LINK_EMBED(DLL) node.dll
FAILED: C:\Python27\python.exe gyp-win-tool link-with-manifests environment.x64 True node.dll "C:\Python27\python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /IMPLIB:node.dll.lib /DLL /OUT:node.dll @node.dll.rsp" 2 mt.exe rc.exe "obj\vendor\node\node_lib.node.dll.intermediate.manifest" obj\vendor\node\node_lib.node.dll.generated.manifest
fatal error C1047: The object or library file 'C:\kobra-local\github\electron\vendor\download\libchromiumcontent\static_library\v8.lib' was created with an older compiler than other objects; rebuild old objects and libraries
LINK : fatal error LNK1257: code generation failed
...
`

Can you help please ?

Regards

**Comment by MarshallOfSound** [comment]
@emmkimme Can you clean, bootstrap and build from scratch 👍

**Comment by emmkimme** [comment]
I'm afraid, we have the same problem on 3 different machines 
- Windows 10 / 2017 Enterprise
- Windows 10 / 2017 Professional
- Windows 7 / 2017 Community

**Comment by emmkimme** [comment]
Master compilations fail as well

**Comment by thomasLechaptois** [comment]
I have the same error, i'm unable to build branch 3-0-x on windows:
fatal error C1047: The object or library file 'G:\git\3.0\electron\vendor\download\libchromiumcontent\static_library\v8.lib' was created with an older compiler than other objects; rebuild old objects and libraries
LINK : fatal error LNK1257: code generation failed

I checked and to me the correct libcc is downloaded.

**Comment by mpalomino** [comment]
same problem here

**Comment by emmkimme** [comment]
@MarshallOfSound, any update on this problem ?
we would like to contribute and we can not validate our changes on Windows which is the most common for our product.
Thks

**Comment by MarshallOfSound** [comment]
@emmkimme Can you try debug builds instead and see if they work (`build.py -c D`)

**Comment by emmkimme** [comment]
It works and Electron starts properly !
So there is something wrong in Release mode.

I have some links warnings
`device_service.lib(mojom_jumbo_1.obj) : warning LNK4099: PDB 'mojom_cc.pdb' was not found with 'device_service.lib(mojom_jumbo_1.obj)' or at 'C:\kobra-local\github\electron\out\D\mojom_cc.pdb'; linking object as if no debug info
device_service.lib(constants.mojom.obj) : warning LNK4099: PDB 'constants_cc.pdb' was not found with 'device_service.lib(constants.mojom.obj)' or at 'C:\kobra-local\github\electron\out\D\constants_cc.pdb'; linking object as if no debug info
device_service.lib(mojom_shared_cpp_sources_jumbo_1.obj) : warning LNK4099: PDB 'mojom_shared_cpp_sources_cc.pdb' was not found with 'device_service.lib(mojom_shared_cpp_sources_jumbo_1.obj)' or at 'C:\kobra-local\github\electron\out\D\mojom_shared_cpp_sources_cc.pdb'; linking object as if no debug info
device_service.lib(common_custom_types_shared_cpp_sources_jumbo_1.obj) : warning LNK4099: PDB 'common_custom_types_shared_cpp_sources_cc.pdb' was not found with 'device_service.lib(common_custom_types_shared_cpp_sources_jumbo_1.obj)' or at 'C:\kobra-local\github\electron\out\D\common_custom_types_shared_cpp_sources_cc.pdb'; linking object as if no debug info
device_service.lib(mutable_network_traffic_annotation_interface_shared_cpp_sources_jumbo_1.obj) : warning LNK4099: PDB 'mutable_network_traffic_annotation_interface_shared_cpp_sources_cc.pdb' was not found with 'device_service.lib(mutable_network_traffic_annotation_interface_shared_cpp_sources_jumbo_1.obj)' or at 'C:\kobra-local\github\electron\out\D\mutable_network_traffic_annotation_interface_shared_cpp_sources_cc.pdb'; linking object as if no debug info
fx_zlib.lib(inflate.obj) : warning LNK4099: PDB 'zlib_inflate_chunk_simd_c.pdb' was not found with 'fx_zlib.lib(inflate.obj)' or at 'C:\kobra-local\github\electron\out\D\zlib_inflate_chunk_simd_c.pdb'; linking object as if no debug info
fx_zlib.lib(inffast_chunk.obj) : warning LNK4099: PDB 'zlib_inflate_chunk_simd_c.pdb' was not found with 'fx_zlib.lib(inffast_chunk.obj)' or at 'C:\kobra-local\github\electron\out\D\zlib_inflate_chunk_simd_c.pdb'; linking object as if no debug info
fx_zlib.lib(crc32_simd.obj) : warning LNK4099: PDB 'zlib_crc32_simd_c.pdb' was not found with 'fx_zlib.lib(crc32_simd.obj)' or at 'C:\kobra-local\github\electron\out\D\zlib_crc32_simd_c.pdb'; linking object as if no debug info
desktop_capture.lib(checks.obj) : warning LNK4099: PDB 'checks_cc.pdb' was not found with 'desktop_capture.lib(checks.obj)' or at 'C:\kobra-local\github\electron\out\D\checks_cc.pdb'; linking object as if no debug info
pdfium_skia_shared.lib(SkFloatToDecimal.obj) : warning LNK4099: PDB 'skia_shared_cc.pdb' was not found with 'pdfium_skia_shared.lib(SkFloatToDecimal.obj)' or at 'C:\kobra-local\github\electron\out\D\skia_shared_cc.pdb'; linking object as if no debug info
`

**Comment by MarshallOfSound** [comment]
> So there is something wrong in Release mode.

No your machine is probably just missing something, there's super weird stuff that can happen with multiple VS installs if you have multiple of those 🤔 

> I have some links warnings

yeah they happen for everyone for now 👍

**Comment by jkleinsc** [comment]
This issue has been fixed via #13593 for 3-0-x and #13594 for master.

**Comment by sgd2z** [comment]
Same problem is happening now with the latest Visual Studio 15.8.1.

**Comment by jkleinsc** [comment]
@sgd2z for master and 3-0-x you will need to use VS2017 15.4.5
