### ISSUE TITLE
Updating input values before it opens

### ISSUE THREAD

**Issue by 04fsnape** [electron/electron#13406]
* Electron Version: 2.0.0
* Operating System (Platform and Version): Windows 10
* Last known working Electron version: 

**Expected Behavior**
I would like to open the electron window and have the inputs in my form set to the values that have been saved in settings.json.

**Actual behavior**
The electron window opens with the inputs empty and then after a small amount of time the inputs from settings.json get filled in.

**To Reproduce**
Electron app with inputs.

js file like this:

```
(async function remembersettings () {
  let settings = await eel.remember_settings()();
  var selects = document.getElementsByClassName('select-selected');
  selects[0].innerHTML = settings[0]; // Region
  document.getElementById('url').value = settings[1];
  if (settings[2] == true) { // Use webhook
    selects[1].innerHTML = "Yes";
  }
  else {
    selects[1].innerHTML = "No";
  }
  document.getElementById('webhook').value = settings[3];
  if (settings[4] == true) { // Use proxies
    selects[2].innerHTML = "Yes";
  }
  else {
    selects[2].innerHTML = "No";
  }
  selects[3].innerHTML = settings[5]; // Browser
  document.getElementById('license').value = settings[6];
  selects[4].innerHTML = settings[7]; // Theme
})();
```

**Additional Information**
I would like the electron app to open with the inputs already filled in, rather than opening without and then changing after.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by MarshallOfSound** [comment]
Open your window with `show: false`, set your values, then call `mainWindow.show()`

**Comment by 04fsnape** [comment]
@MarshallOfSound I am already doing `show: false`

**Comment by 04fsnape** [comment]
That's why it's an issue
