### ISSUE TITLE
Webview 304s on local pages

### ISSUE THREAD

**Issue by burningTyger** [electron/electron#13405]
* Electron Version: 3.0.0 beta1
* Operating System (Platform and Version): Arch Linux and Windows 7
* Last known working Electron version: latest 2

**Expected Behavior**
Local page renders just fine and loads CSS, images etc

**Actual behavior**
The local html file is loaded and rendered but all css and image files get a 304.

**To Reproduce**
I'm referring to a local html page that uses the webpack server. The URL works fine for the initial webview page but fails on further requests under the same static directory.

**Comment by sofianguy** [comment]
@burningTyger can you provide us with steps to reproduce this issue?

**Comment by burningTyger** [comment]
@sofianguy thank you for your reply. I've been trying to reproduce this error with a dead simple quickstart template but failed to do so. Both webpack and vanilla electron templates do their job just as expected. I'll further investigate why it doesn't work in my app which is basically a webpacked app too.

**Comment by burningTyger** [comment]
I'll close this issue due to no real working example. If I manage to find one I'll open it again.

**Comment by burningTyger** [comment]
tried the final version with my app and it seems resolved. No more 304s fo rme. Thank you
