### ISSUE TITLE
Can't write files

### ISSUE THREAD

**Issue by TheOnlyArtz** [electron/electron#13407]
I can't write a file to a path on the PC like `C:\users\win10\Desktop`
Error:
```
Uncaught Error: EISDIR: illegal operation on a directory, open 'C:\Users\win10\Desktop'```

```
code:
```
// path is the C:\Users\win10\Desktop
toDownload.pipe(fs.createWriteStream(path))```

**Comment by MarshallOfSound** [comment]
You are trying to write a file to a path that is already a directory.  Either remove the directory or name the file something else.

(That is what EISDIR means.  Error IS DIRectory)
