### ISSUE TITLE
Dev tools extension tabs don't appear in 3.0.0-beta.1

### ISSUE THREAD

**Issue by ajmacd** [electron/electron#13408]
* Electron Version: 3.0.0-beta.1
* Operating System (Platform and Version): macOS 10.13.5
* Last known working Electron version: 2.0.3

**Expected Behavior**
Dev tools extension tabs should appear after being added with the `BrowserWindow.addDevToolsExtension` API. I specifically tested the React and Redux extensions. I can tell the React extension is getting installed but not being shown because the usual
> Download the React DevTools for a better development experience

warning is absent.

**Actual behavior**
Dev tools extension tabs do not appear.

**To Reproduce**
Manually obtain the extension paths following the instructions here:
https://electronjs.org/docs/tutorial/devtools-extension
and supply them to `addDevToolsExtensions`.

Alternately, use [electron-devtools-installer](https://github.com/MarshallOfSound/electron-devtools-installer), which I have a repro case for using just Redux here:
https://github.com/ajmacd/electron-quick-start-typescript

Working with 2.0.3:
```sh
$ git clone https://github.com/ajmacd/electron-quick-start-typescript -b 2.0.3-devtools-working 
$ cd electron-quick-start-typescript
$ npm install
$ npm start
```

Not working with 3.0.0-beta.1:
```sh
$ git checkout 3.0.0-beta.1-devtools-not-working
$ npm install
$ npm start
```

**Comment by DannyFeliz** [comment]
I have the same issue too, I was testing with Vue.js and the [https://github.com/vuejs/vue-devtools](vue-devtools) don't appear.

**Comment by Nimelrian** [comment]
This is not macOS specific. DevTool extension tabs don't appear on my windows machine either!

**Comment by zcbenz** [comment]
Refs https://github.com/electron/electron/issues/13344.
