### ISSUE TITLE
[v3.0.0-beta.1] gpu acceleration stopped working

### ISSUE THREAD

**Issue by sebakerckhof** [electron/electron#13415]
* Electron Version: 3.0.0-beta.1
* Operating System (Platform and Version): Debian 9.1
* Last known working Electron version: 2.0.3

I'm trying the most basic thing: opening a browser window (e.g. just running https://github.com/electron/electron-quick-start )

**Expected Behavior**
I get to see the page

**Actual behavior**
Window seems to freeze immediately (never get to see the content). The window does emit the 'show' event and I don't see any errors.

I can make it work by disabling gpu usage (`app.disableHardwareAcceleration()`).

**To Reproduce**
Run https://github.com/electron/electron-quick-start  with electron 3.0.0-beta.1. But it seems OS related, since it does work on my ubuntu 18.04...

I already tried upgrading:
- Mesa
- Libva
- intel-vaapi
- xserver-xorg-video-intel

But without luck.

I have no problems running chrome 66 with hardware acceleration, and there doesn't seem to be any relevant change in the GPU info with chrome 61. So it seems to be an electron thing. (gpu info for chrome 61/66: [chrome-gpu-info.zip](https://github.com/electron/electron/files/2154479/chrome-gpu-info.zip) )

**Comment by nornagon** [comment]
What versions of `mesa-va-drivers`, `libva-intel-vaapi-driver`, `i965-va-driver`, and `xserver-xorg-video-intel` do you have? (run `dpkg -l <package-name>` or `dpkg -l |grep <package-name>` to find out)

**Comment by ckerr** [comment]
As per #13622 this appears to still be present in 3.0.0-beta.2

**Comment by ejmg** [comment]
I am curious in confirming whether these downstream issues are all suffering the same problem described as described here?

- [Signal](https://github.com/signalapp/Signal-Desktop/issues/2442)
- [Riot](https://github.com/vector-im/riot-web/issues/5315)
- Slack (No github repo, but community seems to be reporting same thing)

**Comment by supercatexpert** [comment]
I have the same problem on Debian Stretch with original mesa driver. But if I update package libgl1-mesa-dri from 13.0.6-1+b2 to 17.3.9-1~bpo9+1 (which is from Stretch backports). GPU acceleration can work again.

**Comment by sebakerckhof** [comment]
I can confirm it works with `libgl1-mesa-dri` `17.3.9-1~bpo9+1`, weirdly enough I remember it didn't work with my own build of version 18.

**Comment by anszom** [comment]
Try running the app without any connection to the tty (./electron (args) < /dev/null >/dev/null 2>/dev/null). If this helps, then see the above PR.

**Comment by supercatexpert** [comment]
After set FDs 0/1/2 to /dev/null, it can work with GPU aceleration now.
