### ISSUE TITLE
Announcements for input fields are missing

### ISSUE THREAD

**Issue by magrotek** [electron/electron#13412]
* Electron Version: 2.0.0.
* Operating System (Platform and Version): Mac OS X 10.13.3
* Last known working Electron version: as far as I know never

**Expected Behavior**
Input fields should be accessible. There should be proper announcements when user insert / delete text inside input filed. 

**Actual behavior**
There are no announcements at all. Settings in Voice Over Utility are ignored.

**To Reproduce**
Repro 100%. You can use for this even sample app: https://github.com/electron/electron-quick-start and just add `<input/>` to index.html.

**Screenshots**
![image](https://user-images.githubusercontent.com/40295497/41845813-114aead2-7875-11e8-9e6a-1bc69d01e63b.png)

**Comment by bpasero** [comment]
I could not see any difference how VoiceOver behaves from VSCode using Electron `2.0.x` to `1.7.x`, so I do not think this is a `2.0.x` regression.

**Comment by magrotek** [comment]
I am not claiming that this worked before in some previous version of Electron. But is that mean that this won't be fixed?

**Comment by bpasero** [comment]
@magrotek I am just trying to find out if this could be a regression in `2.0.x` only.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
