### ISSUE TITLE
Stop crash reporter after `crashReporter.start`

### ISSUE THREAD

**Issue by goldylucks** [electron/electron#13411]
**Is your feature request related to a problem? Please describe.**
We want to enable users to opt out of crash reporting, but there's no `crashReporter.stop` method.

**Describe the solution you'd like**
Being able to call `crashReporter.stop()` on both main and rnederer prcoesses

**Describe alternatives you've considered**
1. Looked into calling [`setUploadToServer`](https://github.com/electron/electron/blob/master/docs/api/crash-reporter.md#crashreportersetuploadtoserveruploadtoserver-linux-macos) but it's not supported on renderer prcoess, and only works on mac

2. monkey patching crashReporter - I will need some guidance for that since there's no clear documentation on the internals of this module (and I don't know c++)

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR.
