### ISSUE TITLE
`privateBytes`  and `sharedBytes` are sometimes missing in a `app.getAppMetrics()` result

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#13414]
* Electron Version: 1.8.x, 2.0.x, 3.0.x
* Operating System (Platform and Version): All
* Last known working Electron version: ?

**Expected Behavior**
[app.getAppMetrics()](https://electronjs.org/docs/api/app#appgetappmetrics) returns an array of [ProcessMetric Object](https://electronjs.org/docs/api/structures/process-metric)s with
a `memory` field having a [MemoryInfo Object](https://electronjs.org/docs/api/structures/memory-info) that always has `privateBytes`  and `sharedBytes` fields.

**Actual behavior**
`privateBytes`  and `sharedBytes` may be missing from the `memory` structure, see https://github.com/electron/electron/blob/57d365a9f445774edf83d3d26250cd0eea39b12e/atom/browser/api/atom_api_app.cc#L1127-L1131

**Comment by alexeykuzmin** [comment]
Possible solution:
if a `GetMemoryBytes` call failed use `0` as a default / obviously incorrect value fro both fields.

**Comment by MarshallOfSound** [comment]
@alexeykuzmin Could we document those properties as optional and let users make their own assumptions about what to do if no value is provided?

**Comment by alexeykuzmin** [comment]
@MarshallOfSound It's an option, of course.

But since we already have a field in the same structure that _sometimes_ is equal to `0`, I thought that we should follow that pattern for the other fields.

> `peakWorkingSetSize` Integer - The maximum amount of memory that has ever been pinned to actual physical RAM. On macOS its value will always be 0.

**Comment by alexeykuzmin** [comment]
True JavaScript Way (TM) would be to always have all fields in a structure and set to `null` values that are not available. `null` is perfect way to indicate an absence of a value.

**Comment by MarshallOfSound** [comment]
> But since we already have a field in the same structure that sometimes is equal to 0

Fair call, consistency first 👍

**Comment by sofianguy** [comment]
@alexeykuzmin is this bug still happening on version 4.x or later?

**Comment by sofianguy** [comment]
going to close this but we can reopen if this still happens on later versions
