### ISSUE TITLE
Vibrancy not working on Electron v3.0.0 beta 1

### ISSUE THREAD

**Issue by JB1905** [electron/electron#13413]
* Electron Version: 3.0.0-beta.1
* Operating System (Platform and Version): macOS Mojave 10.14 beta 2
* Last known working Electron version: 2.0.3

**Expected Behavior**
Vibrancy effect for window

**Actual behavior**
No Vibrancy effect

**To Reproduce**
Start Electron 3.0.0 beta 1 app with Vibrancy effect on macOS

[Code here](https://github.com/JB1905/electron-quick-start)

**Screenshots**
v2.0.0
<img width="1004" alt="zrzut ekranu 2018-06-25 o 13 10 49" src="https://user-images.githubusercontent.com/28870390/41847452-4fc5671a-787a-11e8-8b8a-41a5d3ec5496.png">

v3.0.0-beta.1
<img width="930" alt="zrzut ekranu 2018-06-25 o 13 11 57" src="https://user-images.githubusercontent.com/28870390/41847459-57cf5998-787a-11e8-88d7-1895b5a14a1b.png">

**Comment by gnattu** [comment]
Workaround: By setting `transparent: true`, the vibrant effect comes back.
Or is this change made intentionally?

**Comment by JB1905** [comment]
**Problem solved in v3.0.0-beta.2**
