### ISSUE TITLE
render method is not calling when the props are updated through redux store in electron app

### ISSUE THREAD

**Issue by saran481** [electron/electron#13422]
* Electron Version: 2.0.1
* Operating System (Platform and Version): mac 
* Last known working Electron version: 

**Expected Behavior**
i am using react redux with electron .i have button when i click on it ... it looks for asset id if it is null it will add asset to playlist or else remove asset from playlist
**Actual behavior**
when i click on the button nothing happening .... i am passing the props from parent to child to render child component...props are updating  through redux actions and reducers.  redux state is updating but it is not triggering the component render function so nothing is get changed when i click a button 

child component
````
export class child extends Component {
  buttonclick() {
    const { pin } = this.props
    if (pin === null) {
      add().then(result => {
        updatePin(result.data)
      })
    } else {
      remove(pin.id).then(result => {
        updatePin(result)
      })
    }
  }
  render() {
    const { pin } = this.props
    const label =  pin === null ? 'yes': 'no'
    const icon =pin === null ? 'yes' : 'no'
    return (
      <div>
          <Button
            icon={icon}
            label={label}
            onClick={() => this.buttonclick()}
          />
      </div>
    )
  }
}
const mapStateToProps = (state, ownProps) => ({
  assetId: ownProps.assetId,
  pin: ownProps.pin,
})
const mapDispatchToProps = dispatch => ({
  pinUpdate: (id, data) => dispatch(pinUpdate(id, data)),
})`

```

parent component
`const parent= props =>{
        const { pins = []} = props
        const { pin } = Data
    }
    const updatePin = result => {
    // here iam updating the pin
   }
      const renderchildComponent=()=>{
    return(
        <div>
         <ChildComponent
                pin={pin}
                updatePin={result => updatePin(result)}
              />
       </div>
    )
    }`

**Comment by wakeGISer** [comment]
same issue,  when store state has upadted,  the connected component cannot re-render,  not receive the new props from connected Component

**Comment by wakeGISer** [comment]
this issue is about reducer mush return a new object,  maybe u return the same pointer object 

`
export default function(state = initState, action) {
  switch (action.type) {
    case GET_CODE:
      return Object.assign({}, state, {
        code: action.payload.code
      });
    case CHECK_LOGIN:
      return Object.assign({},state, {
        auth: action.payload.auth || false
      });
    case GET_USER_INFO:
      return Object.assign({}, state, {
        userInfo: action.payload || {}
      });
    default:
      return state;
  }
}
`

like this, you must return a new object .  in Object.assign({}, ...)

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
