### ISSUE TITLE
Ongoing Process does not stop on Electron App close.

### ISSUE THREAD

**Issue by unit11** [electron/electron#13439]
* Electron version:2.0.2
* Operating system:Windows 10 

* Last known working Electron version: 

### Expected behavior
I am working on an app that can do an ongoing task in the command line.When I close the app the ongoing task does not close.It is still running on the background processes I have to explictly close it through the task manager "End Task". 

### Actual behavior
Is there any way so that when I close the app there is no existence of the ongoing task it closes imediately.

### Screen Shot when the app is running
![working](https://user-images.githubusercontent.com/29042142/41894384-57a02d90-793c-11e8-872f-d71292febd16.png)
### Screen Shot when the app is closed
![closed](https://user-images.githubusercontent.com/29042142/41894413-6c214330-793c-11e8-88b0-16029cab5745.png)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
