### ISSUE TITLE
Unable to receive data passed from one renderer to another via main.js

### ISSUE THREAD

**Issue by ohmtrivedi** [electron/electron#13448]
* Electron version: 2.0.2
* Operating system: Ubuntu

### Expected behavior
I wish to send data to child window (handled by cves.js and created from index.js on an event) from my main window (sourced by index.js). 

### Actual behavior

I am able to send data from cves.js to index.js via main.js. But, I am not able to receive data in cves.js from index.js via main.js.

### How to reproduce

My code files can be found at https://github.com/ohmtrivedi/electronProject. You can run the program with `npm start` and then provide any IP address in the text box (for example, as per screenshot). Then click, "Identify OS". After sometime, you will get first row in the table below and a "Get CVEs" button will show up. Upon clicking this button, a new window shows up (the window where I wish to receive data from the previous window). I have kept console.log messages which shows which functions are getting executed.

![screenshot](https://user-images.githubusercontent.com/7829466/41941421-f3200632-7969-11e8-828b-b0d0df45bcd3.png)

Hoping to understand why I can exchange data between 2 renderers only in one direction (cves.js -> index.js) and not other way.

**Comment by MarshallOfSound** [comment]
@ohmtrivedi Can you provide a minimal sample that reproduces the bug, we can't go spelunking around your code looking for bugs in your logic.  It would help greatly if you could provide a repo based on `electron-quick-start` that reproduces your IPC issue

**Comment by ohmtrivedi** [comment]
Hi,

Kindly find herewith attached a sample built from extending `electron-quick-start`. The files are as follows:

main.js (main process)
index.html (Main page)
renderer.js (renderer process for index.html)
anotherPage.html (Second page)
anotherPage.js (renderer process for anotherPage.html)

I wish to send some data from index.html to anotherPage.html. What I have tried is using ipc in 2 ways:

1. When main process receives the message from renderer.js, the main process creates new BrowserWindow for anotherPage.html (using a globally declared variable secondWindow) and sends the data (which it received from renderer.js)  to anotherPage.js, using the BrowserWindow object (secondWindow) for anotherPage.html.

2. I also tried to use the 'did-finish-load' event. When this event triggers in anotherPage.js, I sent message to main process to inform about this event, and then main process sends the data to anotherPage.html using it's BrowserWindow object (secondWindow).

I feel I am confused between the way main and renderer processes communicate and hence doing something wrong. So, I just need guidance on how to do it the correct way. Hope this helps.

[electron-quick-start-modified.zip](https://github.com/electron/electron/files/2143138/electron-quick-start-modified.zip)

**Comment by MarshallOfSound** [comment]
@ohmtrivedi You just need to wait for the webContents in `anotherPage` to finish loading before sending a message 👍 

I add this bit to your sample

```js
secondWindow.webContents.once('did-finish-load', () => {
  secondWindow.webContents.send('targetData', someData);
  console.log('main.js sends target data' + someData);
});
```

And it started worked as expected

**Comment by ohmtrivedi** [comment]
Hi @MarshallOfSound, thanks for taking out time to look at my issue.
Can you kindly clarify where should this event handler be placed? Will it come inside the `ipcMain.on('send-data'...)` handler in main.js? If that's the case, it didn't work in my case.

**Comment by MarshallOfSound** [comment]
@ohmtrivedi 

```
ipcMain.on('send-data', (event, arg) => {
  someData = arg;
  secondWindow = new BrowserWindow({ frame: false,  width: 800, height: 800 });
  secondWindow.webContents.once('did-finish-load', () => {
    secondWindow.webContents.send('targetData', someData);
    console.log('main.js sends target data' + someData);
  });
  secondWindow.loadFile('anotherPage.html');
  secondWindow.on('closed', () => { cvesWindow = null });
  console.log('main.js receives send-data msg with target data = ' + someData + ' and creates window for anotherPage.html');
})
```

**Comment by ohmtrivedi** [comment]
@MarshallOfSound 
That didn't work for me. Kindly find attached screenshots for reference. I get the console.log messages "main.js receives send-data msg with target data = test message and creates window for anotherPage.html", "index.js sends send-data msg with message test message" and "main.js sends target datatest message", but not "anotherPage.js receives targetData". 

Also, I would like to understand that why the 'did-finish-load' handler was called before secondWindow.loadFile and not, say, at the end after the console.log method?

![screenshot 1](https://user-images.githubusercontent.com/7829466/42014411-3d98e63c-7a70-11e8-89e3-99fdaaee0e5e.png)
![screenshot 2](https://user-images.githubusercontent.com/7829466/42014412-3dad5f72-7a70-11e8-8400-98825a08e318.png)
