### ISSUE TITLE
CMD + Q exits kiosk mode on OSX

### ISSUE THREAD

**Issue by Stuffe** [electron/electron#13440]
Versions:
Electron v1.8.3
OSX 10.13.4

I have an application that opens in kiosk mode, but I can still exit it with CMD+Q.

This is my main.js file:

```
const {app, BrowserWindow} = require('electron');

let mainWindow;

global.app_path = app.getAppPath()+'/';

function createWindow () {
  mainWindow = new BrowserWindow({'kiosk': true})
  mainWindow.loadFile('www/index.html', {app: app})
}

app.on('ready', createWindow)
app.on('activate', function () {
  if (mainWindow === null) {
    createWindow();
  }
})

```

I searched around but couldn't find any other mention of this.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
