### ISSUE TITLE
Replace `getProcessMemoryInfo` API in chromium 67

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#13447]
`ProcessMetrics::GetMemoryBytes` won't be available after an upgrade to Chromium 67+, see #13383.
But those metrics are quite important, so we should try to find a way to keep them.

/cc @miniak, @juturu, @nitsakh

**Comment by nitsakh** [comment]
Based on the chromium task (https://bugs.chromium.org/p/chromium/issues/detail?id=819289) and related notes, it looks like the details in the electron `getProcessMemoryInfo` API response provide results are platform specific and mean different on different platforms. These no longer exist in chromium 67. Chromium has moved to using the memory_instrumentation apis, and that's the recommended cross platform way.
There are ways to get platform specific details (process_metric.h), but if just the memory footprint is needed we can use the `private_memory_footprint` from the instrumentation API.
(Also updating the issue title to reflect the `getProcessMemoryInfo` API deprecation)

**Comment by bpasero** [comment]
@alexeykuzmin @nitsakh is this still an issue given https://github.com/electron/electron/pull/14847 landed? I cannot find it in Electron 4.0.x though, so not sure if its 5.0.x only?

**Comment by codebytere** [comment]
This is completed and released in 5-0-x.
