### ISSUE TITLE
Open BrowserWindow with preserve log checked

### ISSUE THREAD

**Issue by debelop13** [electron/electron#13444]
Hi

I want to open a new BrowserWindow or Webview with a "Preserve log" checked.

![screen shot 2018-06-26 at 15 56 07](https://user-images.githubusercontent.com/20789085/41917031-ba4b3576-7959-11e8-8c16-264815d69cbc.png)

If not, when page is reloaded, console has been deleted.

I think that can be a new option in BrowserWindow creation.

Thanks.

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR.
