### ISSUE TITLE
[v3.0.0-beta.1] webvr supported but no vrdisplays found

### ISSUE THREAD

**Issue by shaneharris** [electron/electron#13443]
* Electron Version:3.0.0-beta.1
* Operating System (Platform and Version):Winx64
* Last known working Electron version: N/A

**Expected Behavior**
I realise this has been asked before, but this time it seems like it is so close i can taste it. I get the message "webvr supported but no vrdisplays found". Is there a quick way to allow it to detect the VR devices?

**Actual behavior**
The above message is displayed even if the VR device is present and it works on chrome using the same website. 

**To Reproduce**
I just installed electron beta with `npm install electron@beta` and added the following to the app main file:

```javascript
mainWindow = new BrowserWindow({width: 800, height: 600, 'web-preferences': {'plugins': true}});
...
app.commandLine.appendSwitch('--enable-webvr');
```

**Screenshots**

![image](https://user-images.githubusercontent.com/6830845/41915898-b6894cc6-794e-11e8-80b7-ea6890bce32e.png)

Without the above flag i get the following:
![image](https://user-images.githubusercontent.com/6830845/41917909-24cfd5f2-7953-11e8-923d-f1c3d6697b33.png)

**Additional Information**
I would owe you guys 100 beers if this were possible!

**Comment by shaneharris** [comment]
also for reference #12468 and #3271

**Comment by MarshallOfSound** [comment]
WebVR is not supported / stable in the Chromium 66 release, it is still behind a flag and declared unstable.  Until we get to a chromium version that declare WebVR is stable and ready to use we can't look into any bugs associated with it as we do not have the resources to potentially track down bugs that aren't even in our code base

**Comment by skhameneh** [comment]
Hey @shaneharris, did you get VRDisplays to show up?
While this ticket is closed, I have interest in working on this.
(I'll report back findings once resolved in this ticket)

I'd also like to message you directly about some of your work, do you mind if I send you an email to the address associated with your GitHub?

**Comment by jonobr1** [comment]
Inquiring minds would love to know @skhameneh how to expose unofficial flags from Chromium to electron

**Comment by shaneharris** [comment]
@skhameneh i didnt ever get it to work beyond the example above. yes by all means - in fact if you want to get me direct I have a discord for an app I run on the AltspaceVR platform called Shane's Editor - https://discord.gg/Q2a5BkZ

**Comment by paperkettle** [comment]
Understand this is waiting on Chromium. Just adding a +1 that Electron eventually open to WebVR. Periodically checking back over recent years, especially given Beaker Browser. Major potential for that intersection...! https://github.com/beakerbrowser/beaker/pull/1161

**Comment by setpixel** [comment]
@shaneharris have you tried with 4.0.0 beta? Very interested in this as well

**Comment by StarStep** [comment]
Is there a way to enable the vr support, kinda like in chrome://flags/ ?

**Comment by talkquazi** [comment]
I did some experimenting using an Oculus Rift and Electron. I can confirm in Chrome Version 72.0.3626.96 (Official Build) (64-bit) for Windows 10  that I needed to enable the --oculus-vr flag in order to get my headset working in Chrome.

There are upcoming WebXR flags emerging in the future. Here are all of the possible flags that someone would need to enable to get VR working (with oculus and other xr devices) in a future release of electron (if and when it has these extra flags).

app.commandLine.appendSwitch('--enable-webvr',);
app.commandLine.appendSwitch('--enable-gamepad-extensions');
app.commandLine.appendSwitch('--enable-gamepad-vibration');
app.commandLine.appendSwitch('--webxr');
app.commandLine.appendSwitch('--webxr-orientation-sensor-device');
app.commandLine.appendSwitch('--webxr-gamepad-support');
app.commandLine.appendSwitch('--oculus-vr');
app.commandLine.appendSwitch('--openvr');

Here's a screenshot from Electron unable to find the displays due to the --oculus-vr sdk not being built with in the current electron 4x code base for Windows 10.

Electron   4.0.4
Node       10.11.0
Chromium   69.0.3497.106

![image](https://user-images.githubusercontent.com/6586731/52694064-8b1a3200-2f36-11e9-9682-2f2c95b651b8.png)

The reason this fails for my hardware is because the Oculus SDK is not being built as seen here in the Electron 4x branch: 
[https://github.com/electron/electron/blob/master/DEPS#L51](url)
`'checkout_oculus_sdk':
False,`

Someone who is adventurous could probably do a custom build of Electron with the Oculus SDK enabled to get things working on their Oculus.

**Comment by skhameneh** [comment]
@talkquazi Great findings, we just upgraded https://github.com/lbryio/lbry-desktop to Electron v4.  Applying CI to Electron v4 wouldn't be difficult.

I have an HTC Vive and would like to target WebXR first (WebXR is the upcoming, unified, W3C approach).  I do not know the current state of the HTC Vive, Chrome, Electron, and OpenVR / WebXR.

See https://www.w3.org/TR/webxr/

**Comment by dirtshell** [comment]
@talkquazi I tried to be that adventurous person but it didn't work :anguished: 

So I have been following [these steps for making a custom build of electron.](https://github.com/electron/electron/blob/master/docs/development/build-instructions-gn.md) After waiting literally 7 hours for `gclient sync --with_branch_heads --with_tags` to succesfully complete, I edited my [DEPS file](https://github.com/electron/electron/blob/75b4db60cf1a61fa04485604adfdaafe3aeb11d2/DEPS) to include and checkout the occulus drivers by changing line 52 to `True`. I then reran `gclient sync --with_branch_heads --with_tags` and immediately got the following output (full output [here](https://gist.github.com/dirtshell/070b80d1b653917ad32f5e5bdc385cb5)):

```
 Syncing projects: 100% (107/107), done.                                                        

. bla
. bla 
. bla

Running hooks:   3% ( 3/81) electron_npm_deps         
________ running '/usr/bin/python -c import os, subprocess; os.chdir(os.path.join("src", "electron")); subprocess.check_call(["python", "script/lib/npm.py", "install"]);' in '/home/jake/electron-gn'

> electron@6.0.0-nightly.20190311 preinstall /home/jake/electron-gn/src/electron
> node -e 'process.exit(0)'

npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 7646 packages in 6.155s
found 30 vulnerabilities (2 low, 23 moderate, 5 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Running hooks:  74% (60/81) libovr                                
________ running '/usr/bin/python src/third_party/depot_tools/download_from_google_storage.py --bucket chrome-oculus-sdk --recursive --num_threads=10 --directory src/third_party/libovr/src' in '/home/jake/electron-gn'
7> Failed to fetch file gs://chrome-oculus-sdk/8d53bd779df72eb4195e640ce936fcd992c943c7 for src/third_party/libovr/src/Include/OVR_CAPI.h, skipping. [Err: ServiceException: 401 Anonymous caller does not have storage.objects.get access to chrome-oculus-sdk/8d53bd779df72eb4195e640ce936fcd992c943c7.
]
4> Failed to fetch file gs://chrome-oculus-sdk/1e0be49c9ba6a622ef33e1623367eb6dfc77977c for src/third_party/libovr/src/Include/OVR_CAPI_GL.h, skipping. [Err: ServiceException: 401 Anonymous caller does not have storage.objects.get access to chrome-oculus-sdk/1e0be49c9ba6a622ef33e1623367eb6dfc77977c.
]
2> Failed to fetch file gs://chrome-oculus-sdk/c245697735368aa7a561e68797fa9304140457b2 for src/third_party/libovr/src/OVR_StereoProjection.cpp, skipping. [Err: ServiceException: 401 Anonymous caller does not have storage.objects.get access to chrome-oculus-sdk/c245697735368aa7a561e68797fa9304140457b2.
]
3> Failed to fetch file gs://chrome-oculus-sdk/5f3e1e83ce37ba0e6c62156b2aee27607015c4ca for src/third_party/libovr/src/OVR_CAPI_Util.cpp, skipping. [Err: ServiceException: 401 Anonymous caller does not have storage.objects.get access to chrome-oculus-sdk/5f3e1e83ce37ba0e6c62156b2aee27607015c4ca.
]
5> Failed to fetch file gs://chrome-oculus-sdk/4eeb533ee42b199f5f5c57409448ad00485b14e1 for src/third_party/libovr/src/Include/OVR_Version.h, skipping. [Err: ServiceException: 401 Anonymous caller does not have storage.objects.get access to chrome-oculus-sdk/4eeb533ee42b199f5f5c57409448ad00485b14e1.
]
1> Failed to fetch file gs://chrome-oculus-sdk/c8235e8e486a73d85a8e1f3221d74f9f93ce2e7c for src/third_party/libovr/src/OVR_CAPIShim.c, skipping. [Err: ServiceException: 401 Anonymous caller does not have storage.objects.get access to chrome-oculus-sdk/c8235e8e486a73d85a8e1f3221d74f9f93ce2e7c.
]
0> Failed to fetch file gs://chrome-oculus-sdk/0588604435704be9a0017f7a4f9d56b9d8560e8a for src/third_party/libovr/src/OVR_CAPI_Prototypes.h, skipping. [Err: ServiceException: 401 Anonymous caller does not have storage.objects.get access to chrome-oculus-sdk/0588604435704be9a0017f7a4f9d56b9d8560e8a.
]
6> Failed to fetch file gs://chrome-oculus-sdk/89dcbfd32c81a0e1df5c321eea50fa30348ba4a2 for src/third_party/libovr/src/Include/OVR_CAPI_Vk.h, skipping. [Err: ServiceException: 401 Anonymous caller does not have storage.objects.get access to chrome-oculus-sdk/89dcbfd32c81a0e1df5c321eea50fa30348ba4a2.
]
9> Failed to fetch file gs://chrome-oculus-sdk/120d1d3d1506c1a47a79045d4c279d760e468629 for src/third_party/libovr/src/Include/OVR_CAPI_Keys.h, skipping. [Err: ServiceException: 401 Anonymous caller does not have storage.objects.get access to chrome-oculus-sdk/120d1d3d1506c1a47a79045d4c279d760e468629.
]
8> Failed to fetch file gs://chrome-oculus-sdk/a2b38fcd4d618922ba00b58e024b8ee546b2bc14 for src/third_party/libovr/src/Include/OVR_CAPI_D3D.h, skipping. [Err: ServiceException: 401 Anonymous caller does not have storage.objects.get access to chrome-oculus-sdk/a2b38fcd4d618922ba00b58e024b8ee546b2bc14.
]
3> Failed to fetch file gs://chrome-oculus-sdk/24d793cea809395c2006894a50a401ba39b21d1e for src/third_party/libovr/src/Include/Extras/OVR_StereoProjection.h, skipping. [Err: ServiceException: 401 Anonymous caller does not have storage.objects.get access to chrome-oculus-sdk/24d793cea809395c2006894a50a401ba39b21d1e.
]
4> Failed to fetch file gs://chrome-oculus-sdk/255adc8cab8f72374e5b06dffcd23b38ab81d2da for src/third_party/libovr/src/Include/Extras/OVR_Math.h, skipping. [Err: ServiceException: 401 Anonymous caller does not have storage.objects.get access to chrome-oculus-sdk/255adc8cab8f72374e5b06dffcd23b38ab81d2da.
]
2> Failed to fetch file gs://chrome-oculus-sdk/1b3ba32d6b56915b0fd179b52edff2f9c0c76de6 for src/third_party/libovr/src/Include/Extras/OVR_CAPI_Util.h, skipping. [Err: ServiceException: 401 Anonymous caller does not have storage.objects.get access to chrome-oculus-sdk/1b3ba32d6b56915b0fd179b52edff2f9c0c76de6.
]
7> Failed to fetch file gs://chrome-oculus-sdk/77fc8a13dd9b947a24703eec78639c1c5e862fc3 for src/third_party/libovr/src/Include/OVR_ErrorFailed to fetch file gs://chrome-oculus-sdk/8d53bd779df72eb4195e640ce936fcd992c943c7 for src/third_party/libovr/src/Include/OVR_CAPI.h. [Err: ServiceException: 401 Anonymous caller does not have storage.objects.get access to chrome-oculus-sdk/8d53bd779df72eb4195e640ce936fcd992c943c7.
]
Failed to fetch file gs://chrome-oculus-sdk/1e0be49c9ba6a622ef33e1623367eb6dfc77977c for src/third_party/libovr/src/Include/OVR_CAPI_GL.h. [Err: ServiceException: 401 Anonymous caller does not have storage.objects.get access to chrome-oculus-sdk/1e0be49c9ba6a622ef33e1623367eb6dfc77977c.
]
Failed to fetch file gs://chrome-oculus-sdk/c245697735368aa7a561e68797fa9304140457b2 for src/third_party/libovr/src/OVR_StereoProjection.cpp. [Err: ServiceException: 401 Anonymous caller does not have storage.objects.get access to chrome-oculus-sdk/c245697735368aa7a561e68797fa9304140457b2.
]
Failed to fetch file gs://chrome-oculus-sdk/5f3e1e83ce37ba0e6c62156b2aee27607015c4ca for src/third_party/libovr/src/OVR_CAPI_Util.cpp. [Err: ServiceException: 401 Anonymous caller does not have storage.objects.get access to chrome-oculus-sdk/5f3e1e83ce37ba0e6c62156b2aee27607015c4ca.
]
Failed to fetch file gs://chrome-oculus-sdk/4eeb533ee42b199f5f5c57409448ad00485b14e1 for src/third_party/libovr/src/Include/OVR_Version.h. [Err: ServiceException: 401 Anonymous caller does not have storage.objects.get access to chrome-oculus-sdk/4eeb533ee42b199f5f5c57409448ad00485b14e1.
]
Failed to fetch file gs://chrome-oculus-sdk/c8235e8e486a73d85a8e1f3221d74f9f93ce2e7c for src/third_party/libovr/src/OVR_CAPIShim.c. [Err: ServiceException: 401 Anonymous caller does not have storage.objects.get access to chrome-oculus-sdk/c8235e8e486a73d85a8e1f3221d74f9f93ce2e7c.
]
Failed to fetch file gs://chrome-oculus-sdk/0588604435704be9a0017f7a4f9d56b9d8560e8a for src/third_party/libovr/src/OVR_CAPI_Prototypes.h. [Err: ServiceException: 401 Anonymous caller does not have storage.objects.get access to chrome-oculus-sdk/0588604435704be9a0017f7a4f9d56b9d8560e8a.
]
Failed to fetch file gs://chrome-oculus-sdk/89dcbfd32c81a0e1df5c321eea50fa30348ba4a2 for src/third_party/libovr/src/Include/OVR_CAPI_Vk.h. [Err: ServiceException: 401 Anonymous caller does not have storage.objects.get access to chrome-oculus-sdk/89dcbfd32c81a0e1df5c321eea50fa30348ba4a2.
]
Failed to fetch file gs://chrome-oculus-sdk/120d1d3d1506c1a47a79045d4c279d760e468629 for src/third_party/libovr/src/Include/OVR_CAPI_Keys.h. [Err: ServiceException: 401 Anonymous caller does not have storage.objects.get access to chrome-oculus-sdk/120d1d3d1506c1a47a79045d4c279d760e468629.
]
Failed to fetch file gs://chrome-oculus-sdk/a2b38fcd4d618922ba00b58e024b8ee546b2bc14 for src/third_party/libovr/src/Include/OVR_CAPI_D3D.h. [Err: ServiceException: 401 Anonymous caller does not have storage.objects.get access to chrome-oculus-sdk/a2b38fcd4d618922ba00b58e024b8ee546b2bc14.
]
Failed to fetch file gs://chrome-oculus-sdk/24d793cea809395c2006894a50a401ba39b21d1e for src/third_party/libovr/src/Include/Extras/OVR_StereoProjection.h. [Err: ServiceException: 401 Anonymous caller does not have storage.objects.get access to chrome-oculus-sdk/24d793cea809395c2006894a50a401ba39b21d1e.
]
Failed to fetch file gs://chrome-oculus-sdk/255adc8cab8f72374e5b06dffcd23b38ab81d2da for src/third_party/libovr/src/Include/Extras/OVR_Math.h. [Err: ServiceException: 401 Anonymous caller does not have storage.objects.get access to chrome-oculus-sdk/255adc8cab8f72374e5b06dffcd23b38ab81d2da.
]
Failed to fetch file gs://chrome-oculus-sdk/1b3ba32d6b56915b0fd179b52edff2f9c0c76de6 for src/third_party/libovr/src/Include/Extras/OVR_CAPI_Util.h. [Err: ServiceException: 401 Anonymous caller does not have storage.objects.get access to chrome-oculus-sdk/1b3ba32d6b56915b0fd179b52edff2f9c0c76de6.
]
Failed to fetch file gs://chrome-oculus-sdk/77fc8a13dd9b947a24703eec78639c1c5e862fc3 for src/third_party/libovr/src/Include/OVR_ErrorCode.h. [Err: ServiceException: 401 Anonymous caller does not have storage.objects.get access to chrome-oculus-sdk/77fc8a13dd9b947a24703eec78639c1c5e862fc3.
]
Code.h, skipping. [Err: ServiceException: 401 Anonymous caller does not have storage.objects.get access to chrome-oculus-sdk/77fc8a13dd9b947a24703eec78639c1c5e862fc3.
]
Downloading 14 files took 3.502988 second(s)
Error: Command '/usr/bin/python src/third_party/depot_tools/download_from_google_storage.py --bucket chrome-oculus-sdk --recursive --num_threads=10 --directory src/third_party/libovr/src' returned non-zero exit status 1 in /home/jake/electron-gn

```

Basically this boils down to this error: `Err: ServiceException: 401 Anonymous caller does not have storage.objects.get access to chrome-oculus-sdk/1b3ba32d6b56915b0fd179b52edff2f9c0c76de6`, which makes me think the script is either out of date and points to some bad commits, or I need to setup some access permissions somehow.

So I will try looking in to this more, but the alternate route I am going to take is to try and use a canary build or official nightly chrome build pulled from [Omaha Proxy](https://omahaproxy.appspot.com/). Then I will do the following:

```
$ git fetch --tags
$ git checkout -b my_local_build_branch 75.0.3747.0  # or more explicitly, tags/75.0.3747.0
$ gclient sync --with_branch_heads --with_tags
$ # then do the regular electron build without editing DEPS since chrome should have OVR already
```

Does this sound right to anyone?

**Comment by MarshallOfSound** [comment]
@dirtshell It's also possible that those drivers are internal to Google folks only and non-google people can't download them 👍

**Comment by etiennepinchon** [comment]
Is there any update on this? Electron 11 still doesn't seem to support webXR :(

**Comment by gdefraiteur** [comment]
Please update this, webxr works really well on chrome now, and there is a whole scene of application that would come up if you let us have webxr in electron.

**Comment by shawticus** [comment]
Sorry to be a +1 for this, but this would be a really really great thing to add, especially as XR is becoming popular, Apple is releasing a headset, etc.

**Comment by BeardScript** [comment]
Is there any work being done on this? Maybe this could be helpful:

https://bai.dev/projects/webxr-electron-apr2021
