### ISSUE TITLE
Behaviour of `util.promisify(childProcess.exec)` inconsistent with node

### ISSUE THREAD

**Issue by arantes555** [electron/electron#13458]
* Electron Version: 1.8.7 & 2.0.3
* Operating System (Platform and Version): MacOS 10.13.5
* Last known working Electron version: None

**Expected Behavior**
`util.promisify(childProcess.exec)`  should behave the same on electron as on node

**Actual behavior**
On node, `promisify`-ed versions of `childProcess.exec` & `childProcess.execFile` have custom behaviour, resolving to an object of the form `{stdout, stderr}`, or rejecting with an Error with the custom properties `stdout` & `stderr`. (Reference : https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback)

On electron, there is no such behaviour, which leads to weird stuff.

**To Reproduce**
```sh
git clone https://github.com/arantes555/electron-bug-child_process.git -b master
cd electron-bug-child_process
npm install

# electron@1.8.7
npm run start-node # Note the objects `{ stdout: 'foobar\n', stderr: '' }` printed here
npm run start-electron # Note the simple `foobar`s printed here

# electron@2.0.3
git checkout electron2
npm install
npm run start-node
npm run start-electron # Note the same behaviour

```

**Additional Information**
The node behaviour is achieved thanks to https://nodejs.org/api/util.html#util_custom_promisified_functions . On node, `childProcess.exec[util.promisify.custom]` is defined, whereas it is undefined on electron.

It can also be noted that this issue has already been (poorly) reported some time ago https://github.com/electron/electron/issues/10925

**Comment by miniak** [comment]
@arantes555 ASAR support integration code is wrapping `childProcess.exec`, therefore `childProcess.exec[util.promisify.custom]` was lost. I am fixing that in https://github.com/electron/electron/pull/13840/files
