### ISSUE TITLE
Feature Request: Get storage

### ISSUE THREAD

**Issue by abriek** [electron/electron#13454]
Hi,

I'm creating an application that requires saving the session of BrowserWindows in order to reuse them constantly (so I plan to save that in a json file). I've managed to successfully do this for the cookies of the BrowserWindow but not the storage (local, indexDB, etc.). I was wondering if there already is a feature (if not can it be implemented?) to get the storage (similarly to the cookies) to store it.

I understand partitions are already existent, however for my use case I'll be saving a lot of sessions that will later be disposable, so it'd be much more reasonable to maintain these in a file of my own. 

If this feature already exists can you direct me to the function for it? I've been searching everywhere.

Thank you!

**Comment by jacobq** [comment]
Just curious, how did you end up solving this? Did you just manually query `localStorage`, etc. from the front-end and send back to Electron's main thread?

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
