### ISSUE TITLE
Add `BrowserWindow#setBackgroundColor()` method

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#13464]
**Is your feature request related to a problem? Please describe.**

It's possible to set the `backgroundColor` in the `BrowserWindow` constructor, but it's not possible to change it later. I need a way to dynamically change the background color when the user toggles system dark mode. I cannot just set it in CSS as my app uses `window.history.reload()`, so the original window background color becomes visible then.

**Describe the solution you'd like**

I like to see a `BrowserWindow#setBackgroundColor()` method.

The [`BrowserView`](https://github.com/electron/electron/blob/2681e769a66bad94718424be5a14492778ce674d/docs/api/browser-view.md#viewsetbackgroundcolorcolor-experimental) API already have this method.

**Comment by MarshallOfSound** [comment]
This should just be a case of exposing the internal `SetBackgroundColor` method.  And exposing a new getter method.

https://github.com/electron/electron/blob/master/atom/browser/api/atom_api_browser_window.cc#L295

**Comment by darkcoderrises** [comment]
Could I work on this?

**Comment by caesar** [comment]
Looks like this is in 4.0.0-beta, but it only works (on macOS Mojave and Windows 10, at least) if the window is opened with a transparent backgroundColor. Otherwise setBackgroundColour has no effect.

**Comment by erickzhao** [comment]
Hey there, it seems like the `setBackgroundColor` API for `BrowserWindow` was added at some point and properly documented [here](https://electronjs.org/docs/api/browser-window#winsetbackgroundcolorbackgroundcolor) in PR #14972.

> #### `win.setBackgroundColor(backgroundColor)
> * `backgroundColor` String - Window's background color as a hexadecimal value,
>   like `#66CD00` or `#FFF` or `#80FFFFFF` (alpha is supported if `transparent`
>   is `true`). Default is `#FFF` (white).
> 
>  Sets the background color of the window. See [Setting
> `backgroundColor`](#setting-backgroundcolor).
-----------------------------

Also,
> Looks like this is in 4.0.0-beta, but it only works (on macOS Mojave and Windows 10, at least) if the window is opened with a transparent backgroundColor. Otherwise setBackgroundColor() has no effect.



It also seems to be working without opening the window with a transparent `backgroundColor`. Tested in both `v4.2.4` and `v5.0.3` (on macOS Mojave as well).

See gist for Electron Fiddle: https://gist.github.com/erickzhao/f173c821a3310911d045ffeca201c10a

Will be closing this for now, then!
