### ISSUE TITLE
Feature request: optimization for vibrancy

### ISSUE THREAD

**Issue by MaxGraey** [electron/electron#13460]
Currently vibrancy effect apply to whole window area which looks like unnecessary for most cases when opaque cover area contain 70-80% of window and only 20% for vibrancy (like sidebar). On OSX and Linux I guess this not cheap according my tests especially when this effect combined with high-load canvas opaque area.

Original repository [electron-vibrancy](https://github.com/arkenthera/electron-vibrancy) allowed add bounded view area for vibrancy via `electronVibrancy.AddView` which pretty good fit to this proposition except this not declarative for webviews/view window.

What if recognize vibrancy in `css` the same as `-webkit-app-region` does and include special property for that like `-webkit-app-vibrancy: dark`, `-webkit-app-vibrancy: light` and etc?

Also related: #13175

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
