### ISSUE TITLE
Incoherent `Tray.getBounds()` in multi-screen setup

### ISSUE THREAD

**Issue by arantes555** [electron/electron#13461]
* Electron Version: 1.8.7 & 2.0.3
* Operating System (Platform and Version): macOS 10.13.5
* Last known working Electron version: None

**Expected Behavior**
`Tray.getBounds()` should give the correct bounds of the tray icon on the currently active screen.

**Actual behavior**
On a multi screen setup where the secondary screen has negative Y coordinates (for example if it is bigger than the primary screen, or on top), Tray icon bounds given by `Tray.getBounds()` are incoherent. In this case, the `x` coordinate seems correct, but the `y` coordinate is 0, where it should be a negative number. Bounds given by the `Tray.on('click')`  and `Tray.on('right-click')` events however are correct.

**To Reproduce**

Have a screen setup as previously described, or as shown in the screenshot below, then:

```sh
git clone https://github.com/arantes555/electron-bug-tray-bounds.git -b master
cd electron-bug-electron-bug-tray-bounds
npm install

# electron@1.8.7
npm start
# A tray icon should appear. Click on it. In your console, bounds will be logged as such. Note the incoherence of the Y coordinates.
# > click eventBounds: { x: -619, y: -180, width: 22, height: 22 }
# > click programmaticBounds: { x: -619, y: 0, width: 22, height: 22 }

# electron@2.0.3
git checkout electron2
npm install
npm start
# As previously, click on the tray icon and see logs in console.

```
**Screenshots**
Screens setup (the primary screen is the one with the white bar on top)
![image](https://user-images.githubusercontent.com/99662/41971416-9c037bfe-7a0e-11e8-997a-d5fb7a60f9db.png)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by arantes555** [comment]
I can confirm the issue is *fixed* starting with electron 3.

**Comment by sofianguy** [comment]
reported as fixed
