### ISSUE TITLE
Remove localstorage limit

### ISSUE THREAD

**Issue by ccorcos** [electron/electron#13465]
* Electron Version: 2.0.2
* Operating System (Platform and Version): MacOS
* Last known working Electron version: 1.8.1 (never had this issue before in an older version of the app)

Sorry for the extremely vague bug report, but I found a serious bug in our app where localStorage seems to have stopped working without throwing any errors causing using users to lose data.

```ts
localStorage.setItem("x", "10")
> undefined
localStorage.getItem("x")
> undefined
```

Upon deleting the Application Support files, everything started working again. Is it possible that we are not raising an error in some cases when localStorage doesn't work? Perhaps the data has been corrupted or something?

I apologize that I don't have reproducible steps, but I think its worth documenting in case others have a similar issue.

**Comment by ccorcos** [comment]
Alright, I have a repro!

With the Electron 2.0.2 application, from the dev tools:

```
localStorage.length
> 635
for (let i = 0; i < 10000; i++) { localStorage.setItem(i.toString(), Array(1000).fill(1).toString()) }
> undefined
localStorage.length
> 5630
```

I when I try to add more, it doesn't work and there are **no errors**!

In Electron 1.8.1 application, from the dev tools:

```
localStorage.length
> 359
for (let i = 0; i < 10000; i++) { localStorage.setItem(i.toString(), Array(1000).fill(1).toString()) }
> undefined
localStorage.length
> 10359
for (let i = 10000; i < 20000; i++) { localStorage.setItem(i.toString(), Array(1000).fill(1).toString()) }
> undefined
localStorage.length
> 20008
for (let i = 0; i < 800000; i++) { localStorage.setItem(i.toString(), Array(1000).fill(1).toString()) }
> undefined
localStorage.length
> 800008
```

Now, I'm not sure why we appear to have lost some entries -- its possible that the application itself removed some stuff -- but for the most part, it worked. It took about 2 minutes to add the 800000 entries, so its definitely working.

Sounds like a bug to me!

**Comment by bpasero** [comment]
@ccorcos does it reproduce if you run this early before `app.on("ready")`:

`app.commandLine.appendSwitch('disable-mojo-local-storage');`

**Comment by ccorcos** [comment]
```js
localStorage.length
> 155
for (let i = 0; i < 10000; i++) { localStorage.setItem(i.toString(), Array(1000).fill(1).toString()) }
> undefined
localStorage.length
> 10155
for (let i = 10000; i < 20000; i++) { localStorage.setItem(i.toString(), Array(1000).fill(1).toString()) }
> undefined
localStorage.length
> 20155
for (let i = 0; i < 800000; i++) { localStorage.setItem(i.toString(), Array(1000).fill(1).toString()) }
> undefined
localStorage.length
> 800009
```

Seems to be the culprit!

**Comment by bpasero** [comment]
This looks like an issue with localStorage using levelDB then. @ccorcos could you please try to reproduce your original issue with Electron 3.0 beta?

**Comment by ccorcos** [comment]
Hey @bpasero would you mind trying? 3.0.0-beta.1 keeps crashing :/

**Comment by bpasero** [comment]
@ccorcos I think this still reproduces in Electron 3.0.0-beta.1. Output:

![image](https://user-images.githubusercontent.com/900690/42408405-832879a2-81cc-11e8-9b2b-c95bafdb99a7.png)

**Comment by ccorcos** [comment]
Hmm yeah, that's no good!

**Comment by ccorcos** [comment]
@deepak1556  any idea what happened to this command line option to turn off mojo?

**Comment by bpasero** [comment]
@ccorcos `disable-mojo-local-storage` will not work anymore starting with Electron 3.0.x due to the Chrome version used within.

**Comment by deepak1556** [comment]
Seems like the localstorage limit is not completely removed, during commit operation the size constraint is still maintained at 5MB.

**Comment by richjun** [comment]
I checked that electron v4.0.4 is ok
![image](https://user-images.githubusercontent.com/32157268/52545511-6a00f680-2dfb-11e9-9639-5f16dc4881db.png)

**Comment by SwiTool** [comment]
> I checked that electron v4.0.4 is ok
> ![image](https://user-images.githubusercontent.com/32157268/52545511-6a00f680-2dfb-11e9-9639-5f16dc4881db.png)

Sorry but you failed, `Array(1000).fill(1)/toString()` gives `NaN` as `Array(1000).fill(1).toString()` gives `1,1,1,1,1` 1000 times.
I still have the issue : 
![image](https://user-images.githubusercontent.com/8834915/53571552-7dd18a00-3b69-11e9-986d-2d688b16cb40.png)

Using electron 4.0.6

**Comment by richjun** [comment]
> > I checked that electron v4.0.4 is ok
> > ![image](https://user-images.githubusercontent.com/32157268/52545511-6a00f680-2dfb-11e9-9639-5f16dc4881db.png)
> 
> Sorry but you failed, `Array(1000).fill(1)/toString()` gives `NaN` as `Array(1000).fill(1).toString()` gives `1,1,1,1,1` 1000 times.
> I still have the issue :
> ![image](https://user-images.githubusercontent.com/8834915/53571552-7dd18a00-3b69-11e9-986d-2d688b16cb40.png)
> 
> Using electron 4.0.6

You're right.
It's my mistake.

**Comment by jacobq** [comment]
I think the test code used above is misleading. (In fact, so is [the test I originally contributed](https://github.com/electron/electron/blob/5a7b56b042975c14c9c50d02801e0f80a3c3be3f/spec/chromium-spec.js#L952-L960)) I found that within a script I can call `setItem` and `getItem` back-to-back for as large of a size as I like (provided there is enough memory and the electron version being used includes https://github.com/electron/electron/pull/15596). e.g.

```js
localStorage.setItem('junk', new Array(50*1024*1024/2).fill('x').join('')); console.log(localStorage.getItem('junk').length)
```

However, the data isn't necessarily persisted. If the `getItem` isn't run back-to-back (in the same closure / context / whatever) -- e.g. if it's run from the dev tools console after `setItem` finishes -- then it will return `null` or `""`.

As a more thorough test, I've forked the quick start app and scripted it to run a series of tests separated by `setTimeout`. You can view the code at [`jacobq/electron-quick-start#storageLimit`](https://github.com/jacobq/electron-quick-start/tree/storageLimit).

For current versions (5.0.1 and 6.0.0-beta.4) the limit appears to be about 21176304 bytes (i.e. 20MiB + about 1% grace).

**Comment by ccorcos** [comment]
Hmm. That's weird because localStorage is supposed to be synchronous

**Comment by jacobq** [comment]
> Hmm. That's weird because localStorage is supposed to be synchronous

I'd have to review the spec again, but I think it's synchronous from the perspective of the script. That is, calling setItem then getItem must give back the new value. However, I don't think the underlying structures are required to be, so if something goes wrong (e.g. disk full, limit exceeded, etc.) then future calls to getItem may differ.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by jacobq** [comment]
Maybe it got deleted now, but I got an email saying that this issue appeared to be out-of-date / only applicable to old versions of Electron. This is not the case. I just rebased my test repo (see [`storageLimit-20190809` branch](https://github.com/jacobq/electron-quick-start/tree/storageLimit-20190809)) against `electron-quick-start` and made sure that it uses current versions of all dependencies. A quick test of Electron v6.0.1 on linux x86_64 shows that there is still a problem (fails write-delay-read test at approximately 20679.986 KiB).

**Comment by jacobq** [comment]
I started looking into this again and think I found a clue as to what is going wrong with the current patch. The [`dom_storage_limits` patch](https://github.com/jacobq/electron/blob/master/patches/chromium/dom_storage_limits.patch) only disables enforcement of the quota. Unfortunately, these parameters (e.g. [`kPerStorageAreaQuota`](https://github.com/chromium/chromium/blob/master/content/browser/dom_storage/dom_storage_types.h#L24)) are still used for allocating memory, e.g. [here](https://github.com/chromium/chromium/blob/master/content/browser/dom_storage/local_storage_context_mojo.cc#L222-L238). One can easily test this by raising or lowering `kPerStorageAreaQuota` and observing the behavior of the [test method I mentioned above](https://github.com/electron/electron/issues/13465#issuecomment-494983533).

Thus it seems that really what the patch is allowing us to do is cause undefined or unwanted behavior :( So now I am starting to think that we either ought to increase the limit (and re-enable the checks) or drop the patch altogether.
