### ISSUE TITLE
Hard Restart

### ISSUE THREAD

**Issue by ccorcos** [electron/electron#13469]
**Is your feature request related to a problem? Please describe.**
Sometimes there are issues that can be solved by removing the Application Support files (on MacOS). Telling a user how to do this on their platform is non-trivial. Telling the user to uninstall and reinstall the application often doesn't solve their problem because deleting the app does not delete these application support files...

**Describe the solution you'd like**
Something similar to `webContents.reloadIgnoringCache()` but actually deletes the Application Support files and restarts the app fresh.

**Describe alternatives you've considered**
I could write a script that hunts down these directories on each platform and write this function myself, but I'm not terribly knowledgable about this stuff so it would be nice if Electron handled this internally since it knows where all the state is kept.

**Comment by timfish** [comment]
The only safe time to clear out `userData` is going to be early in the main process before `userData` is in use. You could trigger the removal of the directory via command line argument and have a get users to paste something into the terminal?

**Comment by ccorcos** [comment]
That's basically what we're doing currently.

**Comment by ccorcos** [comment]
I added this to the system menu that appears to work well

```ts
{
	label: "Clear App Data",
	async click(item, focusedWindow) {
		await fs.remove(app.getPath("userData"))
		app.relaunch()
		app.exit()
	},
},
```

**Comment by MarshallOfSound** [comment]
You can do this by either deleting the entire `userData` folder and then restarting your app.  Or just use a new partition every time you want to "reset" your app
