### ISSUE TITLE
Open links in the developer tools in external browser

### ISSUE THREAD

**Issue by skleeschulte** [electron/electron#13479]
**Is your feature request related to a problem? Please describe.**
When the output in the console in the developer tools contains urls, they are formatted as links, but clicking on them does not open the URL.

**Describe the solution you'd like**
The link should open in the operating systems default browser.

**Describe alternatives you've considered**
Currently I copy the links manually, which is annoying.

**Additional context**
Example for links in the console:
![grafik](https://user-images.githubusercontent.com/3659947/42025560-20d04874-7ac5-11e8-825d-117baf141ac1.png)

**Comment by EnderDev** [comment]
Could we get an update on this? @sofianguy @MarshallOfSound

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
