### ISSUE TITLE
Cannot evaluate code in the devtools console Electron 3.0.0-beta.1

### ISSUE THREAD

**Issue by CyberPhoenix90** [electron/electron#13478]
* Electron Version: 3.0.0-beta.1
* Operating System Windows 10 64x [Version 10.0.17134.112]
* Last known working Electron version: N/A

**Expected Behavior**
When launching the devtools and typing code into the console and pressing enter to evaluate it, it should work

**Actual behavior**
After pressing enter nothing happens, the code I wrote disappears but there is no return value and there is no effect, as if the devtools has no connection to the chrome instance. This occurs randomly when I am developing my app and once it happens it will happen every restart for a while and then it resolves itself. I made sure no other electron or chrome processes were running in the background when trying to diagnose the problem and it didn't help

**To Reproduce**
Seems to happen at random, I just create a window like follow;
```
function createWindow() {
    win = new BrowserWindow({
        width: 1920,
        height: 1080,
        useContentSize: true,
        webPreferences: {
            webgl: true
        }
    });
    win.loadFile('templates/index.html');
    win.webContents.openDevTools({
        mode: 'undocked'
    });
}
app.on('ready', createWindow);
```
The template was just:
<html>
</html>

No additional files were / extensions needed to reproduce the problem
**Additional Information**
Even though evaluating code through the console does not work, other activities in the inspector work just fine, such as inspecting the dom and doing performance profiling

Also I am not sure if it's related but I see the following error in my console logs for the main process:
[12056:0628/084211.995:ERROR:CONSOLE(17)] "Uncaught (in promise) TypeError: Cannot read property 'setMainWidget' of undefined", source: chrome-devtools://devtools/bundled/inspector.js (17)

**Comment by ruslang02** [comment]
In the top there is a context select, choose the top/front one.
It is somehow not selected automatically in this release

**Comment by CyberPhoenix90** [comment]
I hadn't noticed that before. The problem is indeed that sometimes no context is selected

**Comment by zcbenz** [comment]
I'm merging this to #13408 since they are essentially the same bug.
