### ISSUE TITLE
Angular based Electron app does not trigger click events with touch screen on macOS

### ISSUE THREAD

**Issue by BenBergman** [electron/electron#13474]
* Electron Version: v2.0.3
* Operating System (Platform and Version): macOS High Sierra - 10.13.5 (17F77)
* Last known working Electron version: n/a

**Expected Behavior**
When building an Electron app based on Angular 6 and deployed on macOS with a touch screen, I expect taps on the screen to trigger click events.

**Actual behavior**
Tapping buttons in the app does not cause click events to fire. Taps on the screen do seem to fire mousedown events though.

**To Reproduce**
I have built a minimal Angular+Electron project based on [this](https://angularfirebase.com/lessons/desktop-apps-with-electron-and-angular/) tutorial that reproduces the bug: https://github.com/BenBergman/angular-electron-tap-bug-test

```sh
$ git clone https://github.com/BenBergman/angular-electron-tap-bug-test.git
$ cd angular-electron-tap-bug-test
$ npm install
$ npm run electron-build
```
**Screenshots**
N/A

**Additional Information**
When packaging the exact same source code in a Cordova based app using the `osx` target and running on the exact same Mac and touch screen, taps on the buttons work just fine for triggering click events.

I also have another Electron app that does not use Angular that works just fine with click events on the same hardware and the same version of Electron.

I have also filed [a bug with Angular](https://github.com/angular/angular/issues/24694) as I'm not sure where the issue lies.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by BenBergman** [comment]
I don't currently have the means to test this bug but will update when I can.

**Comment by sofianguy** [comment]
I am closing this for now. Feel free to update if you find this bug is still happening in later versions.
