### ISSUE TITLE
pgManage throws Javascript error on startup

### ISSUE THREAD

**Issue by krohne** [electron/electron#13480]
* Electron Version: 1.6.2
* Operating System (Platform and Version): MacOS 10.13.5
* Last known working Electron version: 1.?

**Expected Behavior**
pgManage startup window should open

**Actual behavior**
pgManage displays an error instead of opening startup window, but local web server runs in the background anyway.

```
A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from #
at validateState (/Applications/pgManage.app/Contents/Resources/app.asar/node_modules/electron-window-state/index.js:46:34)
at module.exports (/Applications/pgManage.app/Contents/Resources/app.asar/node_modules/electron-window-state/index.js:154:3)
at App.appStart (/Applications/pgManage.app/Contents/Resources/app.asar/main.js:437:20)
at emitTwo (events.js:130:20)
at App.emit (events.js:213:7)
```

**To Reproduce**
Install 10.x release of pgManage on MacOS 10.13.x: https://github.com/pgManage/pgManage/releases/tag/v10.3.0

On startup:

Error window (screenshot below).

The pgManage local web server is still running fine at http://localhost:46211/pgmanage/0/index.html

**Screenshots**
![screen shot 2018-03-01 at 9 56 26 am](https://user-images.githubusercontent.com/7244467/36851315-f74e964a-1d36-11e8-924f-0fe2a27a358b.png)

**Additional Information**
The pgManage team cannot reproduce and believes this must be an error in Electron.

https://github.com/pgManage/pgManage/issues/31#issuecomment-389877098

First seen on MacOS 10.1.1

**Comment by MarshallOfSound** [comment]
@krohne This is not an issue with Electron

As you can see in the stack trace the code throwing the error is coming from `app.asar` (the `pgManage` app) not from any internal Electron logic.

This app should handle `uncaughtException` events at the process level to avoid showing these dialogs.

The actual error being emitted here is thrown when you attempt to call an Electron API with an argument of an invalid or incorrect type.  E.g. An API expects a string and you give it an object.

**Comment by nunziotocci** [comment]
@krohne @MarshallOfSound I believe we've resolved this, see the pgManage issue for details.
