### ISSUE TITLE
ES6-ish imports in main and renderer processes

### ISSUE THREAD

**Issue by ruslang02** [electron/electron#13483]
* Electron Version: 3.0.0-beta1
* Operating System (Platform and Version): Windows x86_64 10, linux Kubuntu 18.04, anywhere else
* Last known working Electron version: n/a

**Expected Behavior**
With the Electron v3 I imagined to throw away Babel and include JS modules of bootstrap/mdc etc. source JS files and get an incredible boost...
I thought it would be nice, but it didn't. 

**Actual behavior**
I can't import any of node_modules library in a renderer script (with `type="module"`), it requires an absolute or relative URL's. Moreover, in JS libraries developers use imports with non-Chromish imports, which lead to errors in dev console. Finally, for these imports to work, I need to create `app://` protocol in main process (which is not a problem).

I suppose Electron is using Chrome's V8 rather than Node.js's...

**To Reproduce**
```html
...
<script type="module">
import $ from 'jquery'; // nope, because it is not intended to work like that by the developer
window.$ = require('jquery'); // yep, classic solution
import Button from '../node_modules/bootstrap/js/src/button'; // nope, it imports jquery in the script using the first variant => error
import Button from 'bootstrap/js/src/button'; // are you kiddin? :)
import MDCRipple from '@material/ripple'; // ...
import MDCRipple from '../node_modules/@material/ripple'; // It has an awful import below:
import MDCComponent from '@material/base/component';
</script>
...
```
**Additional Information**
Main process fails to include using these variants too, only `import(<library>)`.

Also, with the import errors solution from https://gist.github.com/smotaal/f1e6dbb5c0420bfd585874bd29f11c43 the directory structure becomes a real problem:
```
root
 - front
 --- index.html
 --- ...
 - node_modules
 - index.js
```
There comes the problem with creating protocol. Binding `app:///` protocol to a root of the app makes almost impossible to import libraries from /node_modules directory from renderer process, so logically we should change it to:
```
root
 - front
 --- index.html
 --- node_modules
 - index.js
```
A-and what? We get a bunch of problems with npm, importing libs to main process and etc etc.

**** What is the solution
 - Do something with the limitation to import ES modules from `file:///` protocol
 - Import Node.JS modules when `import fs from 'fs';` as an equivalent to `const fs = require('fs')`

**Comment by burtonator** [comment]
Yes. This is super important

**Comment by Ontopic** [comment]
Any update on this? I feel there is a lot of developers anticipating getting rid of require forever, could be a nice way for Electron to get ahead of its competitors.

**Comment by burtonator** [comment]
I actually got it to work in polar.  You have to require() the first script via a file URL and then all the imports work normally.

I should isolate examples but you can see it here:

https://github.com/burtonator/polar-bookshelf

I got it to work with typescript and it's lovely not to have to webpack!

**Comment by jlgerber** [comment]
> I actually got it to work in polar. You have to require() the first script via a file URL and then all the imports work normally.
> 
> I should isolate examples but you can see it here:
> 

That would be lovely because polar bookshelf is quite complicated

> https://github.com/burtonator/polar-bookshelf
> 
> I got it to work with typescript and it's lovely not to have to webpack!

**Comment by davimello28** [comment]
Well, I think that we still have this issue.

**Comment by martin31821** [comment]
This problem gets more important as Angular ships ESM bundles by default in 8.0, which effectively renders electron unusable with angular 8 in the default config. 
While there is a workaround to use the ES5 fallback, I'd like to see this problem solved.

**Comment by TianyiShi2001** [comment]
Hoping to see full ES6 support

**Comment by Exr0n** [comment]
Any updates?

**Comment by johannesjo** [comment]
Now that Angular 10 is out, there seems to be no good way to make this work. The only way to make this work is to use a custom protocol, but if you used the file protocol before your users lose all data being saved to localStorage and indexedDB :(

**Comment by martin31821** [comment]
> The only way to make this work is to use a custom protocol, 

can you elaborate how to use a custom protocol? I'd like to test this in our application

**Comment by johannesjo** [comment]
@martin31821 the basic idea is, that you register a custom protocol and set it up to serve all the JavaScript files. Unfortunately, I was never able to make this work and it seems like I deleted the code without code committing it.

**Comment by MarshallOfSound** [comment]
Duplicate #21457
