### ISSUE TITLE
[Discussion] An official Electron boilerplate based on Parcel

### ISSUE THREAD

**Issue by AlexSHoffman** [electron/electron#13484]
### Proposal:

Most available Electron boilerplates are built on Webpack and are out of date.

Parcel is better, faster, and easier to use than Webpack, why not to build an official Electron boilerplate based on it?

### Reasoning:

Without a boilerplate there's no easy way to create an `Electron + [framework]` project. 

In my opinion, there should be an easy to use & configure official Electron boilerplate based on Parcel to make it easier for everyone to create projects like `Electron + Vue` or `Electron + React`.

**Comment by MarshallOfSound** [comment]
I'm going to close this out as it's more of a userland discussion, but happy for you to raise this under the forge repository to discuss the WIP parcel plugin.  It's got a lot of work to be done and some things to resolve upstream in parcel, but the core work is there.

**Comment by AlexSHoffman** [comment]
@jrobeson thanks for the info!
