### ISSUE TITLE
Embed Mongodb with Electron

### ISSUE THREAD

**Issue by jindalrohit** [electron/electron#13499]
I am keeping MongoDB source code inside electron source code and running MongoDB using this command :

```
const app = require('electron').app;
const child_process = require('child_process');
const dbInstanceDir = app.getAppPath();
const startMongo = dbInstanceDir + mongodb/bin/mongod --dbpath mydbpath --port 27017 --logpath mylogfile

child_process.exec(startMongo, (error, stdout, stderr) => {
});
```
**Above code is working while development** but it not working after bundling. I am using electron builder to make bundle. MongoDB source code is at root level.

<img width="282" alt="capture" src="https://user-images.githubusercontent.com/12742169/42075702-cbe056a8-7b8f-11e8-96d3-24dfc3d36bd7.PNG">

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
