### ISSUE TITLE
scrollBounce options does not work in 3.0.0-beta.1

### ISSUE THREAD

**Issue by thomasdao** [electron/electron#13493]
* Electron Version: 3.0.0-beta.1
* Operating System (Platform and Version): Mac
* Last known working Electron version: 2.0.3

**Expected Behavior**
The browser window disables the scroll bounce (rubber banding) effect on OS X by default

**Actual behavior**
The "rubber banding" effect is always enabled, even when `scrollBounce` is set to `false`

**To Reproduce**
Try scroll the browser window with 3.0.0-beta.1 on Mac, see the rubber banding effect

**Comment by zcbenz** [comment]
Related Chromium commit: https://chromium.googlesource.com/chromium/src/+/0f9f36c77159df1e7e64a83ceab11fdca1f743a0%5E%21

I think we need to set `NSScrollViewRubberbanding` in the main process now, and I'm not sure if it is now possible to set it for each window.
