### ISSUE TITLE
Electron [3.0.0-beta.1] - webview focus issue

### ISSUE THREAD

**Issue by t57ser** [electron/electron#13503]
* Electron Version: 3.0.0-beta.1
* Operating System (Platform and Version): Linux Manjaro (also tested on Window 10)
* Last known working Electron version: 2.0.3

Following situation:
I have multiple webviews on one page and I noticed that sometimes a webview does not get keydown events.
I tried to re-create a simple example for this and also applied the following style:
`webview:active {
      border-right: 5px solid yellow;
}`
In electron 2.0.3 each time I click on a webview, the border can be seen for a short time and the keydown events are always recognized.
In electron 3.0.0-beta.1 the border can never be seen and sometimes (when switching focus of the webviews via click) the actual clicked webview does not receive the keydown events but the previous one receives it.

**Expected Behavior**
- Right border visible. 
- Keydown events are recognized.

**Actual behavior**
The webview does not receive the keydown events (seems to happen at random)
Border style for active flag can never be seen.

**To Reproduce**
https://github.com/t57ser/electron-webview-focus-issue
You can switch the electron version in the package.json to observe working and none working.
In the devtools of the two webviews you can observe the keydown logs in the console but just via the style it can be seen that something is off (working version had yellow right border on select)

**Comment by zcbenz** [comment]
The critical Chromium commit we need to reference is https://chromium.googlesource.com/chromium/src.git/+/6ec48b2a6529b753f28340fd6741908086224bee%5E%21.

**Comment by pfrazee** [comment]
@ckerr 🎉

**Comment by ccorcos** [comment]
Hmm. I'm still having this issue.

**Comment by ccorcos** [comment]
Made a new ticket here: https://github.com/electron/electron/issues/15718
