### ISSUE TITLE
BrowserWindow.webContents.executeJavaScript does not work in 3.0.0-beta.1

### ISSUE THREAD

**Issue by luca-viggiani** [electron/electron#13504]
* Electron Version: 3.0.0-beta.1
* Operating System (Platform and Version): Arch Linux x64
* Last known working Electron version:  2.0.3

on `did-finish-load` the following code is not executed at all:
```javascript
mainWindow.webContents.executeJavaScript(`console.log("hello world");`);
```

It was working with version 2.0.x

**Comment by MarshallOfSound** [comment]
I ran the following code from the renderer process

```js
require('electron').remote.getCurrentWebContents().executeJavaScript('console.log(\'foo\')')
```

And the console log appeared as expected, can you provide a minimal repro, it may be a timing issue in your code introduced by a timing change in the C66 upgrade.

**Comment by luca-viggiani** [comment]
here is a sample code:
```javascript
const { app, BrowserWindow } = require('electron');

let mainWindow;

function createMainWindow(){

    mainWindow = new BrowserWindow({ width: 800, height: 600, show: false });

    mainWindow.on("closed", () => mainWindow = null);
    mainWindow.setMenu(null);

    mainWindow.webContents.openDevTools();

    mainWindow.loadFile("index.html");

    mainWindow.webContents.on("did-finish-load", () => {
        mainWindow.webContents.executeJavaScript(`console.log("hello");`); // <--- this does not execute with electron-3.0.0-beta.1
    });

    mainWindow.once('ready-to-show', () => mainWindow.show());
}

app.on("ready", createMainWindow);

app.on("window-all-closed", () => {
    if (process.platform != "darwin")
        app.quit(); // macOS style
});

app.on("activate", () => {
    if (!mainWindow)
        createMainWindow(); // macOS style
});
```

Executing it with electron 3.0.0-beta.1 won't print anything in the console. With electron 2.0.4 you get "hello" message in console.

**Comment by alexeykuzmin** [comment]
@MarshallOfSound ^

**Comment by alexeykuzmin** [comment]
@luca-viggiani Can you please check `3.0.0-beta.2` which was released yesterday. Thanks!

**Comment by luca-viggiani** [comment]
Just checked, same result as beta.1

**Comment by luca-viggiani** [comment]
another update: using `dom-ready` instead of `did-finish-load` works even with 3.0.0-beta.2 (javascript code is executed):

```javascript
    mainWindow.webContents.on("dom-ready", () => {
        console.log("finish");
        mainWindow.webContents.executeJavaScript(`console.log("hello");`); // <--- this does not execute with electron-3.0.0-beta.1
    });
```
However this is not a suitable workaround in my real application because I need to execute my javascript from main process **after**  the `onload` event has been fired on rendering process. And according to documentation, the right one is [did-finish-load](https://electronjs.org/docs/api/web-contents#event-did-finish-load):

> Emitted when the navigation is done, i.e. the spinner of the tab has stopped spinning, and the onload event was dispatched

And again this works as expected in version 2.0.x

**Comment by luca-viggiani** [comment]
@MarshallOfSound sorry I didn't read your last sentence and forgot to mention you...
