### ISSUE TITLE
"inspectable web contents" ShowDevTools should checks resource before call it

### ISSUE THREAD

**Issue by mdogadailo** [electron/electron#13502]
**Is your feature request related to a problem? Please describe.**
It is possible that resources which called from [InspectableWebContentsImpl::ShowDevTools](https://github.com/electron/electron/blob/e42c6d3eb72b28b95bd9f9cbf4010834262d15f4/brightray/browser/inspectable_web_contents_impl.cc#L295) are not available.

**Describe the solution you'd like**
Is it possible that [InspectableWebContentsImpl::ShowDevTools](https://github.com/electron/electron/blob/e42c6d3eb72b28b95bd9f9cbf4010834262d15f4/brightray/browser/inspectable_web_contents_impl.cc#L295) will check with [InspectableWebContentsImpl::LoadNetworkResource](https://github.com/electron/electron/blob/e42c6d3eb72b28b95bd9f9cbf4010834262d15f4/brightray/browser/inspectable_web_contents_impl.cc#L451) resuorce avialability (should not be 404) before send request on line [317](https://github.com/electron/electron/blob/e42c6d3eb72b28b95bd9f9cbf4010834262d15f4/brightray/browser/inspectable_web_contents_impl.cc#L317) and if it falls then load internal ```kChromeUIDevToolsURL```?

**Comment by mdogadailo** [comment]
More explanation on this. Using [GetWebKitRevision on line 123](https://github.com/electron/electron/blob/e42c6d3eb72b28b95bd9f9cbf4010834262d15f4/brightray/browser/inspectable_web_contents_impl.cc#L123) is not correct because ```chrome-devtools-frontend.appspot.com``` never serves files for the release commit.

I've checked for [67.0.3396.99](https://chromium.googlesource.com/chromium/src/+log/67.0.3396.87..67.0.3396.99?pretty=fuller&n=2), [66.0.3359.181](https://chromium.googlesource.com/chromium/src/+log/66.0.3359.170..66.0.3359.181?pretty=fuller&n=2), [65.0.3325.146](https://chromium.googlesource.com/chromium/src/+log/64.0.3282.186..65.0.3325.146?pretty=fuller&n=2) and all of them are empty.


Or maybe [DEPS](https://github.com/electron/electron/blob/master/DEPS#L3) should contains revision for Chromium?

**Comment by zcbenz** [comment]
@mdogadailo I'm a bit confused with this, is devtools failing to load under some cases?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by mdogadailo** [comment]
Checked on 6.0.0

Try to load external URL with  ```loadURL``` from BrowserWindow instance.

In the beginning, it says: 
```Empty response arrived for script devtools://devtools/remote/serve_file/@e67b7e2f345cbedc6a24e0074a1a528c724f5915/product_registry_impl/product_registry_impl_module.js```

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
