### ISSUE TITLE
'swipe' event is not triggerd by a 3 figure swipe

### ISSUE THREAD

**Issue by liusy182** [electron/electron#13509]
* Electron Version: 2.0.3
* Operating System (Platform and Version): Mac 10.13.5
* Last known working Electron version:  Unknown

**Expected Behavior**
Swipe works as per https://electronjs.org/docs/api/browser-window#event-swipe-macos

**Actual behavior**
swipe event is not triggered with a 3-figure swipe that switches workspace

**To Reproduce**

```js
const {app, BrowserWindow} = require('electron')

let win

function createWindow () {
  win = new BrowserWindow()
  win.on('swipe', console.log)
}
```

make the window focus and do a 3-figure swipe to switch workspace. Nothing is logged to the console.

**Comment by samiskin** [comment]
I tried this out on Electron Fiddle at version 1.6.18 (the earliest it had) and it didn't seem to be working there either

**Comment by codebytere** [comment]
Closed by https://github.com/electron/electron/pull/19319
