### ISSUE TITLE
Get existing protocol handler to use for default behavior.

### ISSUE THREAD

**Issue by burtonator** [electron/electron#13512]
**Is your feature request related to a problem? Please describe.**

I'm trying to replace the HTTP and HTTPS handlers with my own and perform my own local caching.

If the result isn't cached locally I want it to use the remote resource.

However, this means I have to implement my own HTTP client, which is fine but I'm worried about subtle bugs. It would be BETTER to have a way to get the existing handler from javascript, and use that by default.  

**Describe the solution you'd like**

Maybe interceptX methods should return the current handler so you can forward methods to it.  Or give it to you via a callback.  

You can then delegate all functions to the previous handler and create chains.

**Describe alternatives you've considered**

Implementing my own client but issues like 'abort' and 'error' have no clear way to be reported.

**Comment by MarshallOfSound** [comment]
If you use `intercept` and callback with null, the default / original handler will handle the request.

**Comment by burtonator** [comment]
I don't think that's actually true.. I just tried it and it looks like electron just does an exit()... 

Removing the interceptor makes the code work again so  I think you're incorrect. 

Is this documented anywhere?
