### ISSUE TITLE
Spell checker not working in dynamically created iframes

### ISSUE THREAD

**Issue by adlk** [electron/electron#13514]
* Electron Version: 2.0.3 / 1.8.4
* Operating System (Platform and Version): windows, mac, linux
* Last known working Electron version: 1.7.15

**Expected Behavior**
Spell checker should work for all form elements/contenteditables including iframes. 

**Actual behavior**
Spell checking doesn't work for any element in an iframe that was created dynamically.

**To Reproduce**
1. Run the sample project
```sh
$ git clone https://github.com/adlk/electron-spellcheck-issue -b master
$ npm install
$ npm start || electron .
```
2. Activate the spell checker in the textareas by clicking them.
3. Wait 5s for the dynamically created textareas to appear
4. Activate the spell checker in the newly created textareas
<img width="854" alt="screen shot 2018-06-29 at 21 32 58" src="https://user-images.githubusercontent.com/3265004/42111340-68ed15cc-7be4-11e8-96d6-f30a24cddf77.png">

**Additional Information**
Spell checker isn't working at all in the Electron 3 beta.

**Comment by bendemboski** [comment]
Is still reproducible on Electron 3.0.0:

```
$ git clone https://github.com/adlk/electron-spellcheck-issue -b master
$ yarn
$ yarn upgrade -L electron
$ yarn start
```

and follow steps 2-4 above

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
