### ISSUE TITLE
Registering and intercepting stream protocols fails (interceptStreamProtocol)

### ISSUE THREAD

**Issue by burtonator** [electron/electron#13519]
* 2.0.2 and 2.0.3:

* Operating System (Platform and Version):

Ubuntu 18.04 and MacOS (latest)

* Last known working Electron version: 

None

**Expected Behavior**

Registering or intercepting a stream protocol should work and the browser should show the proper content. 

**Actual behavior**

The browser actually shows an empty document with no content. No errors present.

I've verified that the same code works fine with 'string' protocols. Just not 'stream' protocols.

I created a repository here:

https://github.com/burtonator/electron-protocol-examples

With all my examples.

The key ones are:

intercept-stream-protocol-http.js :  FAILS
intercept-string-protocol-http.js: WORKS

I simplified the code greatly and I use the examples in the documentation. I've read the protocol documentation 2-3x to see if I was missing something.  Does't seem to be the case.

Additionally there is this case:

intercept-stream-protocol-with-default-protocol.js

... I'd like to have a way to revert to the default protocol handler if possible. A comment on my previous issue stated that this was possible but it still doesn't appear to work.  Doesn't work with string protocols either.

**To Reproduce**

Just clone my repository and run the examples.  

https://github.com/burtonator/electron-protocol-examples

```sh
git clone https://github.com/burtonator/electron-protocol-examples.git
cd electron-protocol-examples
npm install

## this will work and the content will be shown in the browser.
./node_modules/.bin/electron intercept-string-protocol-http.js

## this will NOT work and no content will be shown to the browser
./node_modules/.bin/electron intercept-stream-protocol-http.js

```
**Screenshots**

## with sting protocol (working)

![image](https://user-images.githubusercontent.com/45447/42126763-b0cb095a-7c41-11e8-973b-7c38b0ddf387.png)

## with stream protocol (not working)

![image](https://user-images.githubusercontent.com/45447/42126756-a19d4290-7c41-11e8-973c-388b1ca27028.png)

**Comment by kewde** [comment]
I'm having the same issue.

**Comment by bpasero** [comment]
@burtonator does it work with `protocol.registerBufferProtocol`?

**Comment by burtonator** [comment]
@bpasero Yes. I'm 95% certain it works with register/intercept buffer protocol.  I can update the code I posted to reflect this. I think this is just stream protocol.  Stream is the important one though as it's cleaner , faster, more real time, and supports headers.

**Comment by kewde** [comment]
I'm 100% sure it works with the buffers, check #13623

**Comment by burtonator** [comment]
This is great. Glad we have another confirmation of this bug. Hopefully we can get a fix soon.

**Comment by gangdelian** [comment]
I think the official doc is not correct. try to use
protocol.registerStreamProtocol('fake', (request, callback) => {
  callback({
   data: fs.createReadStream('/Users/gangdelian/test.html'),
   headers: {
   'content-type': 'text/html'
  }
  })
}, (err) => {
});

You should use content-type for text/html to render html, if video resource, you should and content-length.

Hopes it help you

**Comment by burtonator** [comment]
@gangdelian 

https://github.com/burtonator/electron-protocol-examples/blob/master/intercept-stream-protocol-http.js

Can you look at that and let me know your thoughts?  It's like 10 lines to reproduce this.  

Is should be exactly what you suggested in your example unless I'm missing something.

**Comment by kewde** [comment]
It doesn't have anything to do with the content-type AFAIK.

I've tested multiple javascript API's: fetch, XMLHTTP. They don't render anything and the same issues are present.

**Comment by gangdelian** [comment]
@burtonator 
I am very sorry that the reply is late. You can try this code，it work well on my mac。You must use async/await or setTimeout in the interceptStreamProtocol callback，It is very strange，maybe it is a bug or feature？

const electron = require('electron');
const app = electron.app;
const protocol = electron.protocol;
const BrowserWindow = electron.BrowserWindow;
const {PassThrough} = require('stream')

/**
 * STATUS: fails.
 *
 * @param request
 * @param callback
 */
function interceptStreamProtocol(request, callback) {

    // The usage is similar to the other register{Any}Protocol, except that the

    // callback should be called with either a Readable object or an object that
    // has the data, statusCode, and headers properties.
   setTimeout(()=> {
    callback({
      statusCode: 200,
      headers: {
          'content-type': 'text/html'
      },
      data: createStream('HTTP 200 OK\r\n<h5>Response</h5>')
  });
   }, 2000)

}

function createStream (text) {
    const rv = new PassThrough();
    rv.push(text);
    rv.push(null);
    return rv;
}

function createMainWindow() {

    let mainWindow = new BrowserWindow();

    let url = "http://example.com";
    mainWindow.loadURL(url);
    return mainWindow;

}

app.on('ready', async function() {

    protocol.interceptStreamProtocol('http', interceptStreamProtocol, (error) => {

        if (error) {
            console.error('failed to register protocol handler for HTTP');
            return;
        }

        console.log("we're registered now.")

        let mainWindow = createMainWindow();

    });


});

**Comment by burtonator** [comment]
Oh.. interesting. To clarify you're saying it ONLY works if you use setTimeout or async?

I will definitely have to try that and see.

**Comment by burtonator** [comment]
Confirmed that it worked!! Good find!  This should seriously improve the performance of my app!  Knock on wood!

**Comment by gangdelian** [comment]
@burtonator if not use  setTimeout or async，most of the time，it will not work。I hope electron develop team will improve it later

**Comment by codebytere** [comment]
hey @burtonator i'm digging into this this week; it looks like some of these things are fixed in the latest `4-0-x` line. `register-stream-protocol-with-fake-scheme.js ` fails in `2-0-x` and `3-0-x` but works in the latest betas. Still narrowing down all the others.

**Comment by burtonator** [comment]
Oh nice.. This is great news.  

The other thing I would really like to see is the ability to have an intercepted protocol but the ability to use the previous protocol before you intercepted it.  This would allow you to use the same protocol handler but replace it with an augmented one.  

Kind of like calling super() on an overloaded method. I want to be able to one-off some URLs but fall-through to the default protocol handler otherwise.

**Comment by malern** [comment]
I've just tested `v4.0.0-beta.7` and it now works if you call the callback synchronously. **BUT** it has stopped working if you call it asynchronously.

So the following code works in `v4.0.0-beta.7`, but shows a blank page in `v3.0.8`
```
  function createStream (text) {
    const rv = new PassThrough() // PassThrough is also a Readable stream
    rv.push(text)
    rv.push(null)
    return rv
  }

  protocol.registerStreamProtocol('atom', (request, callback) => {
    callback({
      statusCode: 200,
      headers: {
        'content-type': 'text/html'
      },
      data: createStream('<h5>Response</h5>')
    })
  }, (error) => {
    if (error) console.error('Failed to register protocol')
  })
```

And this code works in `v3.0.8`, but shows a blank page in `v4.0.0-beta.7`
```
  function createStream (text) {
    const rv = new PassThrough() // PassThrough is also a Readable stream
    rv.push(text)
    rv.push(null)
    return rv
  }

  protocol.registerStreamProtocol('atom', (request, callback) => {
    setTimeout(() => {
      callback({
        statusCode: 200,
        headers: {
          'content-type': 'text/html'
        },
        data: createStream('<h5>Response</h5>')
      })
    }, 1000);
  }, (error) => {
    if (error) console.error('Failed to register protocol')
  })
```

I can't find any way to make it work in both.

**Comment by burtonator** [comment]
This is madness.. I wonder if we need to make this code into a PR and get it as a standard unit test in Electron.

**Comment by malern** [comment]
After further testing I'm finding the synchronous code is not 100% reliable in `v4.0.0-beta.7` either. Occasionally the page making the request will receive a truncated response that only includes the first 65536 bytes from the stream.

Unfortunately I've been unable to write a test that makes this to happen consistently (the code in my earlier post will sometimes work and sometimes not). So this could be a tricky bug to track down.

I'm using Windows 7 if that makes a difference.

**Comment by burtonator** [comment]
Hopefully this is just an issue with the beta....

**Comment by vladimiry** [comment]
> Hopefully this is just an issue with the beta....

@burtonator unfortunately final v4 is also affected, see the `setTimeout` call below (full file is [here](https://github.com/vladimiry/email-securely-app/blob/4d2ab47a391b6558283d5a004dd3894a6af6d4e4/src/electron-main/protocol.ts)):
```typescript
                async (request, callback) => {
                    const file = await resolveFileSystemResourceLocation(directory, request);
                    const contentType = mimeTypes.contentType(path.basename(file));
                    const callbackReader = new PassThrough();

                    callback({
                        statusCode: 200,
                        headers: {
                            ...(contentType && {"Content-Type": contentType}),
                        },
                        data: callbackReader,
                    });

                    fs.createReadStream(file)
                        .on("error", (error) => {
                            logger.error(`Error "${file}" file reading`, error);
                        })
                        .on("data", (data) => {
                            callbackReader.push(data);
                        })
                        .on("close", () => {
                            // TODO get rid of "setTimeout" call, see https://github.com/electron/electron/issues/13519
                            setTimeout(
                                () => {
                                    callbackReader.end();
                                },
                                // some value > 50 usually works (tested on up to 4Mb files)
                                // but increasing might be needed if serving large files
                                350,
                            );
                        });
},
```

@sofianguy can the `4-0-x` label be added to this issue?

**Comment by vladimiry** [comment]
I ended up with [registerBufferProtocol](https://github.com/vladimiry/email-securely-app/blob/fea62add7f53331caf92a1d69672eb6d0eab4167/src/electron-main/protocol.ts#L27) which works well for my case (need to serve relative small files, but with mime type, so file protocol doesn't work, and stream protocol is unreliable).

**Comment by burtonator** [comment]
This is a huge issue that will completely kill my app... I'm going to test porting to it but if setTimeout won't work with interceptStreamProtocool then I'm dead in the water.

**Comment by burtonator** [comment]
Just confirmed.. upgraded to Electron 4.0 and my code is completely broken.  It fails with either setTimeout or calling directly... 

What I'm REALLY worried about here is that my app is permanently dead and that these methods will be backed out. 

This is a major Electron API and it's not unit tested?  

How did they release and not catch this?

**Comment by tonyganch** [comment]
Hey @burtonator, can you please check version 4.0.6 or later?
I've tried examples from your repo with both `setTimeout` and without, and it looks like starting from that release things actually work.
It would be awesome if you could verify it!
Thanks.

**Comment by kewde** [comment]
Hi,

I think the issue might be in the passthrough code.

The issue I was seeing that the request remained stuck in `loading` when inspecting it through the devtools window. It would just remain in limbo for a very long time. I think that the networking code relies on ReadableStream to emit the `close` event which in its turn closes the request? If the close event is emitted before it protocol handler can latch on to it, it probably doesn't resubmit.

Note that the createStream had an additional delay to writing the null byte to indicate it has finished.
Even a small timeout of 1 ms helped still worked.

```
  function createStream (text) {
    const rv = new PassThrough() // PassThrough is also a Readable stream
    rv.push(text)
    setTimeout(() => { rv.push(null); }, 1000);
    return rv
  }

  protocol.registerStreamProtocol('atom', (request, callback) => {
    setTimeout(() => {
      callback({
        statusCode: 200,
        headers: {
          'content-type': 'text/html'
        },
        data: createStream('<h5>Response</h5>')
      })
    }, 1000);
  }, (error) => {
    if (error) console.error('Failed to register protocol')
  })
```

**Comment by sofianguy** [comment]
fixed according to [this comment](https://github.com/electron/electron/issues/13519#issuecomment-471111198)

**Comment by dawiidio** [comment]
@sofianguy I think this problem returned or were never fixed. I'm using electron `8.0.0-beta.6` on `macOS  Catalina 10.15.2` and got the same results as mentioned above. But in my case I can't see any connection between async/ or sync nature of callback, it behave randomly 😢

**Comment by kewde** [comment]
Please take a look at my reply [here](https://github.com/electron/electron/issues/13519#issuecomment-490718876).

**Comment by dawiidio** [comment]
@kewde yep, seen your reply, even try'd pausing stream but problem seems to be somewhere else, beyond userland . With paused and delayed  stream it behaves in exact the same way. For now I switched to file protocol, but it's temporary solution. I'll investigate it later

**Comment by kewde** [comment]
Hmmm @dawiidio 
I remember that working consistently, I'll investigate it again.
