### ISSUE TITLE
Electron 3 audio not allowed before user interaction with the page (Chrome 66 autoplay policy)

### ISSUE THREAD

**Issue by sonnyp** [electron/electron#13525]
* Electron Version:
`3.0.0-beta.1`

* Operating System (Platform and Version):
`Arch Linux`

* Last known working Electron version: 
`2.0.3`

**Expected Behavior**
```js
(new Audio('foobar')).play()
```
plays the sound even before user interaction

**Actual behavior**

Getting the following error in the JavaScript console:
```
Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD
```

**Additional Information**

https://www.chromium.org/audio-video/autoplay
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by codebytere** [comment]
👋 so it looks as though there's a setting for this at `kNoUserGestureRequired`, so i'll look into how i can make this accessible for you!

**Comment by bcomnes** [comment]
@codebytere I tried this:

```
app.commandLine.appendSwitch('no-user-gesture-required')
```

(before app start)

Still getting the error.  Any ideas?

**Comment by pulkit110** [comment]
The command line switch is different now: 

```
app.commandLine.appendSwitch('autoplay-policy', 'no-user-gesture-required');
```

Here are [some more details](https://www.chromium.org/audio-video/autoplay).

**Comment by psulek** [comment]
@pulkit110 This works! Thanks.

**Comment by tanvir23** [comment]
> The command line switch is different now:
> 
> ```
> app.commandLine.appendSwitch('autoplay-policy', 'no-user-gesture-required');
> ```
> Here are [some more details](https://www.chromium.org/audio-video/autoplay).

@pulkit110 u r the best...it works like a charm!!

**Comment by mountainash** [comment]
[This](https://github.com/electron/electron/issues/13525#issuecomment-410923391) worked for me (in Electron 3.1.13) and allowed me to remove this "hacky" on webview workaround:
```js
win.webContents.sendInputEvent({type:'mouseDown', x:10, y: 10, button:'left', clickCount: 1});
win.webContents.sendInputEvent({type:'mouseUp', x:10, y: 10, button:'left', clickCount: 1});
```

**Comment by ionut-tanasa** [comment]
I just tried both solutions @mountainash and @pulkit110 no result.

the only difference is I need to use an external website.

I created a basic electron app and this is the code:

```javascript
const { app, BrowserWindow } = require('electron');

if (require('electron-squirrel-startup')) { // eslint-disable-line global-require
    app.quit();
}

const createWindow = async () => {
    const mainWindow = new BrowserWindow({
        // fullscreen: true,
        acceptFirstMouse: true
    });

    app.commandLine.appendSwitch('autoplay-policy', 'no-user-gesture-required');
    await mainWindow.loadURL('https://REDACTED URL HERE');
    mainWindow.webContents.sendInputEvent({ type: 'mouseDown', x: 10, y: 10, button: 'right', clickCount: 1 });
    mainWindow.webContents.sendInputEvent({ type: 'mouseUp', x: 10, y: 10, button: 'right', clickCount: 1 });
    return mainWindow;
};

app.on('ready', createWindow);

app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
    }
});
```

when i launch the app the video starts playing, but still no audio.

**Comment by lionep** [comment]
Can you try to set the instruction `app.commandLine.appendSwitch('autoplay-policy', 'no-user-gesture-required');` before `ready` event ?
