### ISSUE TITLE
Disable native notification from electron

### ISSUE THREAD

**Issue by H4shloop13** [electron/electron#13522]
Can we disable native notification from electron to only show electron-notifications ?
i use custom electron-notifications but 2 notification popup

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by H4shloop13** [comment]
But i think i request feature to add option for disable native notification not assistance :(

**Comment by MarshallOfSound** [comment]
It isn't a case of disabling native notifications, from your description you are somehow calling the constructor of two different notification sources (electron and a third party module).  The simple solution is to stop calling the one you don't want.  This is an issue in your code, not a feature request.
