### ISSUE TITLE
Tray message is not displayed on Ubuntu 18.04. Worked on Windows 10

### ISSUE THREAD

**Issue by redplane** [electron/electron#13527]
* Electron Version: **2.0.3**
* Operating System (Platform and Version): ** Windows 10 **

**Expected Behavior**
Tray message is displayed in Ubuntu 18.04

**Actual behavior**
Tray message is not displayed in Ubuntu 18.04 when the below code is executed :  
It works normally on Windows 10

`
let pApp = electron.app.getAppPath();
let pTrayIcon = path.join(pApp, 'assets', 'icons', 'message.png');       
tray.displayBalloon({
            icon: pTrayIcon,
            title: 'System message',
            content: arg.message
        });
`

**To Reproduce**
In `main.js`, execute the code : 

`      
let pApp = electron.app.getAppPath();
let pTrayIcon = path.join(pApp, 'assets', 'icons', 'message.png');       
tray.displayBalloon({
            icon: pTrayIcon,
            title: 'System message',
            content: arg.message
        });
`

**Screenshots**
![Work normally on Windows 10](https://user-images.githubusercontent.com/7974095/42145371-b1b24ea6-7df3-11e8-87e7-f5193ed43e3b.png)

**Comment by MarshallOfSound** [comment]
`displayBalloon` is documented to only be supported on Windows

https://electronjs.org/docs/api/tray#traydisplayballoonoptions-windows

**Comment by redplane** [comment]
Are there any alternative solutions to display tray message on linux ?

**Comment by MarshallOfSound** [comment]
@redplane It sounds like you just want to use `Notification`'s 

https://electronjs.org/docs/api/notification
