### ISSUE TITLE
problem with desktopCapturer when sharing app only (eg PowerPoint)

### ISSUE THREAD

**Issue by lzgrzebski** [electron/electron#13536]
* Electron Version: 2.0.3
* Operating System (Platform and Version): win 10
* Last known working Electron version:  x

**Expected Behavior**
When sharing some application (eg Powerpoint) media stream should show that the app is updating when navigating through the app. 

**Actual behavior**
When sharing some application (eg Powerpoint and I think its not happening for all apps) UI is not updating (I can only see mouse moving in the media stream not actually UI updating I was trying to advance the slides in the Powerpoint app and for some reason I cannot see that they are changing in the video feed), UI get updated only when I move powerpoint to the other screen or resize the PowerPoint window it seems to update again). Not sure if this is related to desktopCapturer or other apps itself.

**To Reproduce**
This happened only when you are sharing application () not entire screen. Try to capture PowerPoint window and see if the slides advance.

**Screenshots**
I tried to record it but it was hard to understand what was actually happening..

**Comment by deepakrokz** [comment]
Hi, 
@lzgrzebski @electron-bot @sofianguy  any update on this facing with Microsoft Word and Excel both, I am stuck in this from 10 days searching for a solution please resolve it ASAP, will be very thankful to you.

**Comment by arnaudbud** [comment]
Could be related to: https://bugs.chromium.org/p/webrtc/issues/detail?id=3852

**Comment by jack-teng1** [comment]
Use this sample app to test screen share:
https://github.com/hokein/electron-sample-apps

And can reproduce the same issue also with electron 3.0.0-beta.7

The chromium issue is for switching to presentation mode and this will open a new window, but in this issue app is not switched to presentation mode and still in the same window.
https://imgur.com/a/M70NmaW

**Comment by ckerr** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unneccessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you've responded, please link to the test case and @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by jack-teng1** [comment]
@ckerr I have created the small app to test this issue
https://github.com/jack-teng1/electron-quick-start

**Comment by mssodhi** [comment]
I don't have Powerpoint, but worked fine for me on Word and Excel using the test repo.

**Comment by marcino1** [comment]
Hi,
I also have this problem, it occurs only on Windows when capturing apps from the Office package (I've checked Word and Excel), on OS X it works fine.
@lzgrzebski @deepakrokz @jack-teng1 did you managed to overcome this issue?

**Comment by cumajkeee** [comment]
@sofianguy any update so far?

**Comment by Ajeey** [comment]
@codebytere Any update on this :)

**Comment by steven09200808** [comment]
The Chromium just release a new modified version Canary and it would be helpful to improve this issue. Can electron update the Dependencies soon? Thanks.

**Comment by steven09200808** [comment]
The Chromium just released a new modified version Canary and it would be helpful to improve this issue. Can electron update the Dependencies soon? Thanks.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by k9winheit** [comment]
Electron Version: 4.0.4
Operating System (Platform and Version): win 10

I have same problem on sharing content on word, Excel and PowerPoint
Editing and scrolling are not updating when they are shared as window (application)
 
It is really helpful , if I can get fix on this.

**Comment by CapOM** [comment]
It is fixed in electron 8.1.1
