### ISSUE TITLE
Adding icon overlays and context menus to file browsers

### ISSUE THREAD

**Issue by mantou132** [electron/electron#13531]
## Is your feature request related to a problem? Please describe.
I want to use electron to develop a file synchronization app, need to indicate file synchronization status in the file browser(e.g: Finder), electron has an API that allows me to do this.

## Describe the solution you'd like
none

## Describe alternatives you've considered
I found this [project](https://github.com/liferay/liferay-nativity) on the web, but it looks too hard.

![](https://camo.githubusercontent.com/6903530f63e91f2cd4e17cbbdcff59afb4e9b10c/68747470733a2f2f7261772e6769746875622e636f6d2f6c6966657261792f6c6966657261792d6e617469766974792f6d61737465722f65787472612f73637265656e73686f742d6d61632e706e67)

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
