### ISSUE TITLE
'electron' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by tinomhishi** [electron/electron#13535]
* Electron Version:electron@2.0.3
* Operating System (Platform and Version):Windows 8
* Last known working Electron version: N/A

**Expected Behavior**
Expected electron to open on command 'electron .'

**Actual behavior**
error 'electron' is not recognized as an internal or external command
A clear and concise description of what actually happened.

**To Reproduce**
Your best chance of getting this bug looked at quickly is to provide a REPOSITORY that can be cloned and run.

You can fork [electron-quick-start](https://github.com/electron/electron-quick-start) and include a link to the branch with your changes.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone $YOUR_URL -b $BRANCH
$ npm install
$ npm start || electron .
```
**Screenshots**
[](url)
**Additional Information**

**Comment by MarshallOfSound** [comment]
@tinomhishi This sounds like you have not installed Electron globally.  You haven't filled out the steps to reproduce either here so we can't really help.

In order to run the electron command you need to have `node` and `npm` installed and configured correctly then run.

```bash
npm i -g electron
```

**Comment by chance221** [comment]
I am going through a tutorial and trying to use electron with nodemon to watch for changes to the main file but when I run the watch command it comes up as 'electron .' not recognized as a command. I have electron 5.0.0 and nodemon 1.18.9 as devDependencies. Electron is installed globally and nodemon is set as a watch in the package.json. I can run the 'electron .' command from the terminal but it still is not recognizable as a command when nodemon tries to execute on it.

**Comment by MahmudulHassan5809** [comment]
> 
> 
> I am going through a tutorial and trying to use electron with nodemon to watch for changes to the main file but when I run the watch command it comes up as 'electron .' not recognized as a command. I have electron 5.0.0 and nodemon 1.18.9 as devDependencies. Electron is installed globally and nodemon is set as a watch in the package.json. I can run the 'electron .' command from the terminal but it still is not recognizable as a command when nodemon tries to execute on it. Here is a linke to the repo I downloaded for the tutorial https://github.com/stackacademytv/master-electron

hey remove the single  just put this line "watch": "nodemon --exec electron ."

**Comment by sabuncu** [comment]
> hey remove the single (quote) and just put this line "watch": "nodemon --exec electron ."

@MahmudulHassan5809  Thank you, your fix worked.  Much appreciated.

**Comment by DocelaEpickyK3BA** [comment]
legit

**Comment by dsuyu1** [comment]
> * Electron Version:electron@2.0.3
> * Operating System (Platform and Version):Windows 8
> * Last known working Electron version: N/A
> 
> **Expected Behavior** Expected electron to open on command 'electron .'
> 
> **Actual behavior** error 'electron' is not recognized as an internal or external command A clear and concise description of what actually happened.
> 
> **To Reproduce** Your best chance of getting this bug looked at quickly is to provide a REPOSITORY that can be cloned and run.
> 
> You can fork [electron-quick-start](https://github.com/electron/electron-quick-start) and include a link to the branch with your changes.
> 
> If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
> 
> ```shell
> $ git clone $YOUR_URL -b $BRANCH
> $ npm install
> $ npm start || electron .
> ```
> 
> **Screenshots** If applicable, add screenshots to help explain your problem. **Additional Information** Add any other context about the problem here.

works fr, thank you so much !

**Comment by Bargamut** [comment]
For those who will find this for case Windows + WSL/

In my case [I installed Electron on the Windoes side](https://gist.github.com/Bargamut/e950f0fdbaf0ceb08a5ac766891ef9a4) - at this moment I don't understand why It can't work with installation on Linux side, but after this trick I can start my app on both sides.

Hope it'll be useful for somebody. )
