### ISSUE TITLE
Renderer process crashes when navigating to certain sites.

### ISSUE THREAD

**Issue by markleutloff** [electron/electron#13550]
* Electron Version: 3.0.0-beta.1
* Operating System (Platform and Version): Windows 8/10 x64 
* Last known working Electron version: 2.0.3

**Expected Behavior**
Site should be displayed.

**Actual behavior**
Site will not be displayed and the renderer process crashes.

**To Reproduce**
Create a BrowserWindow and navigate to:
https://www.amazon.de/Canon-EF-100-400-4-5-5-6L-Objektiv/product-reviews/B00PGNMXQA

Any similar review site of amazon will do the trick.

**Comment by thegelko** [comment]
Same problem to me, on certain webapp also with Electron 2.0.3
No messages in renderer-process console..

**Comment by jkleinsc** [comment]
This was fixed via #13476 which is now available in the 3.0.0-beta.2 release.
