### ISSUE TITLE
'will-attach-webview' is fired before `src` is set

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#13558]
* Electron Version: 2.0.x
* Operating System (Platform and Version): All
* Last known working Electron version: 1.8.x

**Expected Behavior**
['will-attach-webview'](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#event-will-attach-webview) used to be fired only after an `src` attribute is set.

**Actual behavior**
'will-attach-webview' is fired when `src` is empty.

We use 'will-attach-webview' event in Teams to validate webview's url, and destroy a guest page if the url is not valid (by calling `event.preventDefault()` as described in the docs). This check is not possible to make with the new behaviour.

The change was made in 59476f0b30979a3bd895b68dbb4bcd24785b17ea in #11300.
/cc @zcbenz, @juturu

**Comment by zcbenz** [comment]
Refs #13113.
