### ISSUE TITLE
Add mouse-enter/leave events for tray icon on Windows

### ISSUE THREAD

**Issue by pronebird** [electron/electron#13559]
**Is your feature request related to a problem? Please describe.**

Feature.

I am building an app that pops up from the tray on Windows and currently the way it works is the following:

1. Clicks on tray icon toggle the window's visibility
2. Clicks anywhere outside, hide the window (using `window.blur` event)

Since `tray.click` fires way too late, after `window.blur`, there is no way to tell a user intent. For example: a user may be clicking on the tray icon once again to hide the window.

**Describe the solution you'd like**

Add `mouse-over` and `mouse-leave` events for tray icon. This could help to figure out the cause of `window.blur` event. This is not entirely true and precise but this will cover at least 99% of the cases.

**Describe alternatives you've considered**

**Additional context**

**Comment by hexianzhi** [comment]
@miniak any news?

**Comment by orangeChu** [comment]
@sofianguy Is there any plan to increase the `mouse-enter` to the tray icon event under Windows?

**Comment by BysunLin** [comment]
Expect authors to add this feature, which is a high-frequency requirement for windows developers.

**Comment by monkey1990** [comment]
It's very helpful for us to show a notification box on windows

**Comment by shadeofgod** [comment]
any plans on this?

we want to display something when user moved his mouse on the tray icon on windows.

currently I think this could be achieved by [listening to mouse position](https://www.npmjs.com/package/iohook) but a simple mouse-enter event would be great.

**Comment by orangeChu** [comment]
> any plans on this?
> 
> we want to display something when user moved his mouse on the tray icon on windows.
> 
> currently I think this could be achieved by [listening to mouse position](https://www.npmjs.com/package/iohook) but a simple mouse-enter event would be great.

https://github.com/electron/electron/pull/19265

**Comment by HarlanGitHub** [comment]
It's very helpful for us to show a notification box on windows

**Comment by zcbenz** [comment]
This turns out to be much more difficult than I expected.

So in order to receive the `WM_MOUSELEAVE` message for the notify icon, we have to call `TrackMouseEvent` for the icon's window first. However Win32 APIs do not provide a way to get the HWND of the notify icon's window, which leaves us no way to receive `WM_MOUSELEAVE` message.

Of course if we dig into the internal window structures of the notification area it is possible to get the HWND of the notify icon, but it would be way too much risk for such a small feature.
