### ISSUE TITLE
HTML5 file dialogs don't open from native context menu.

### ISSUE THREAD

**Issue by GrantGryczan** [electron/electron#13551]
* Electron Version: 2.0.3
* Operating System (Platform and Version): Windows 10
* Last known working Electron version: N/A

**Expected Behavior**
I should be able to create an HTML5 file input and click it with JavaScript from the click handler of a menu and have an HTML5 file dialog open.

**Actual behavior**
Nothing happens when the menu option is clicked.

**To Reproduce**
There are a variety of ways to do this. All of the following code shall be evaluated from the renderer process, and we'll assume `electron` is `require("electron")` and `win` is `electron.remote.getCurrentWindow()`.
First, you need a file input.
```js
const fileInput = document.createElement("input");
fileInput.type = "file";
fileInput.accept = "image/*, audio/*";
```
I would do this with the native Electron dialogs, but you can't just tell it to allow all Chrome-supported image/audio file types, for example, as you can with HTML5 file inputs. Perhaps that should be a feature as a comfortable alternative to fixing this potential bug?
Then you can open that input's file dialog using the method, `fileInput.click`. So this line will open it.
```js
fileInput.click();
```
Now let's create a nice context menu, so hypothetical users don't have to go to the hypothetical toolbar to open image and audio files for my hypothetical program, and they can instead just right-click.
```js
electron.remote.Menu.buildFromTemplate([{
    label: "Open file",
    click: () => {
        fileInput.click();
    }
}]).popup(win);
```
Calling `popup` opens the menu as expected, but clicking "Open file" (at least in my environment) does absolutely nothing. No error is thrown, and no file dialog is opened. Feel free to call `fileInput.click` again to confirm that the file input is still functional.
Here's an alternative. Very surprisingly, it also doesn't work.
```js
electron.remote.Menu.buildFromTemplate([{
    label: "Open file",
    click: () => {
        setTimeout(() => {
            fileInput.click();
        });
    }
}]).popup(win);
```
You'd think that maybe it has something to do with the thread the file input's `click` method is being called on? Apparently not, as using `setTimeout` to make it asynchronous also fails the test.
Here's another surprising failure. I was hesitant to try this at first because of how inefficient it is, but I'll put it here for the sake of the bug report.
```js
let clickTheThing = false;
setInterval(() => {
    if(clickTheThing) {
        fileInput.click();
        console.log("Clicked!");
        clickTheThing = false;
    }
}, 100);
electron.remote.Menu.buildFromTemplate([{
    label: "Open file",
    click: () => {
        clickTheThing = true;
    }
}]).popup(win);
```
It doesn't work regardless. That it still doesn't work is simply amazing. Even adding a 10-second delay to that interval (by changing the 100 to 10000) changes nothing, and "Clicked!" is still logged just fine. Even calling `fileInput.click` manually from the console before the interval has been completed works fine, but, when it is reached and "Clicked!" is logged, still no dialog appears.

I have no idea what could possibly be causing this. Standing alone, calling `fileInput.click` works perfectly, though when directly or very indirectly provoked by a menu handler, nothing happens. You can tell it's not related to the `click` method itself being at fault, as just calling the `click` method by any other Electron-unrelated means works fine, including intervals and timeouts. It is very strange.

**Comment by GrantGryczan** [comment]
Never mind. This code doesn't work either, so it isn't related to Electron.
```js
setInterval(() => {
    assetInput.click();
    console.log("Clicked!");
}, 10000);
```

**Comment by MarshallOfSound** [comment]
I believe you are experience a feature of Chromium that prevents unwanted popups.  Basically in order to trigger a file dialog by calling "click" your JS needs to have a hidden "user gesture" flag.  This flag is automatically set whenever you are responding to user-caused events like clicks or hovers.

If you use `webContents.executeJavaScript` there is a second argument that allows you to fake your code running in a "user gesture" environment.

https://electronjs.org/docs/api/web-contents#contentsexecutejavascriptcode-usergesture-callback

**Comment by GrantGryczan** [comment]
Is there no way to execute it as actual code rather than a string?

**Comment by themihai** [comment]
I face the same issue ExecuteJavascriptcode is useless because it's executed globally on the page. We need a Window option or app switch flag to set userGesture on or off.
