### ISSUE TITLE
All electron apps crashing in WSL with 'pthread_mutex_unlock(&m->mutex) == 0' failed

### ISSUE THREAD

**Issue by abalter** [electron/electron#13566]
This is an updated and correcter version of #13561

* Electron Version:
Pretty sure latest. Whatever is installed by `npm`. Not sure how to tell.

* Operating System (Platform and Version):

```
balter@spectre:~$ uname -a
Linux spectre 4.4.0-17134-Microsoft #112-Microsoft Thu Jun 07 22:57:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
balter@spectre:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
```

* Last known working Electron version: 
N/A

**Expected Behavior**
Electron-based applications to run.

**Actual behavior**
They all fail with the following error:
>Assertion 'pthread_mutex_unlock(&m->mutex) == 0' failed at pulsecore/mutex-posix.c:108, function pa_mutex_unlock(). Aborting.

**To Reproduce**
Install and run any electron app. For example, please see https://github.com/atom/atom/issues/17635

```
balter@spectre:~$ git clone https://github.com/electron/electron-quick-start.git
Cloning into 'electron-quick-start'...
remote: Counting objects: 289, done.
remote: Total 289 (delta 0), reused 0 (delta 0), pack-reused 289
Receiving objects: 100% (289/289), 59.89 KiB | 0 bytes/s, done.
Resolving deltas: 100% (133/133), done.
Checking connectivity... done.
balter@spectre:~$ cd electron-quick-start/
balter@spectre:~/electron-quick-start$ npm install

> electron@2.0.0 postinstall /home/balter/electron-quick-start/node_modules/electron
> node install.js

added 153 packages in 4.194s
balter@spectre:~/electron-quick-start$ npm start

> electron-quick-start@1.0.0 start /home/balter/electron-quick-start
> electron .

Assertion 'pthread_mutex_unlock(&m->mutex) == 0' failed at pulsecore/mutex-posix.c:108, function pa_mutex_unlock(). Aborting.
```

**Additional Information**
## Node version info:
```
balter@spectre:~$ node --version
v8.11.3
balter@spectre:~$ which node
/home/balter/.nvm/versions/node/v8.11.3/bin/node
balter@spectre:~$ npm --version
5.6.0
balter@spectre:~$ which npm
/home/balter/.nvm/versions/node/v8.11.3/bin/npm
```

**Note:** I have tried installing node and npm multiple ways:
* Using Conda
* Using apt
* From source

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
