### ISSUE TITLE
Add SVG support for icons

### ISSUE THREAD

**Issue by deadcoder0904** [electron/electron#13568]
## **Is your feature request related to a problem? Please describe.**
I think Tray icons shouldn't be restricted to PNG & JPG
SVG support can provide dynamic icon generation in Tray on the fly for use cases like #13500 

## **Describe the solution you'd like**
```js
new Tray("/path/to/svg")
```

## **Describe alternatives you've considered**
Alternatives are static PNGs or JPGs for every Icon. Suppose we have 30 types of Tray Icons with 30 different colours, then with PNGs or JPGs we have to add 30 static icons but if we have SVG support, we can just have 1 icon that adapts to 30 different colors 

## **Additional context**
Related #9642 & #9661

**Comment by MarshallOfSound** [comment]
> Related

Duplicate #9642

**Comment by deadcoder0904** [comment]
At least edit the title of the duplicate issue #9642 because people will assume it works for Windows & Mac which is literally not the case
