### ISSUE TITLE
Is there a way to get AppId?

### ISSUE THREAD

**Issue by dingchaoyan1983** [electron/electron#13583]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by dhimmel** [comment]
According to this [StackOverflow](https://stackoverflow.com/a/61787825/4651668), you can do something like:

```js
var fs = require("fs");
var appId = JSON.parse(fs.readFileSync("path_to_package.json", 'utf8')).build.appId;
```

So there is no getter method like [`app.getName`](https://www.electronjs.org/docs/latest/api/app#appgetname). I wonder if that is a sign that electron apps should not ever need to access their `appId`? In my case I am wondering what value to prefix an electron-store config file with.
