### ISSUE TITLE
Bug: Div above with no drag still dragable if div below has drag enabled

### ISSUE THREAD

**Issue by CreatorVilius** [electron/electron#13588]
* Electron Version: 2.0.0
* Operating System (Platform and Version): Windows 10
* Last known working Electron version: -

**Expected Behavior**
Non-dragable region if div with `position: fixed;` and `-webkit-app-region: no-drag;` is above div with `-webkit-app-region: drag;`

**Actual behavior**
region becomes dragable if it's position is fixed and div below has `-webkit-app-region: drag;`

**To Reproduce**
Make frameless window, make non-fixed div which have dragging enabled, put fixed div above and disable dragging. Still dragable.

**Comment by eric8810** [comment]
save on the 3.0.X windows 7.
Also it will disabled the above div's mouse event.

**Comment by mattbroussard** [comment]
Duplicate of #11768?

**Comment by nornagon** [comment]
Yep, same issue.
