### ISSUE TITLE
Unicode character U+2262 ("not identical to") is not drawn correctly

### ISSUE THREAD

**Issue by jubajube** [electron/electron#13582]
* Electron Version: 1.7.12
* Operating System (Platform and Version): Windows 10.0.17134.112 x64
* Last known working Electron version: 1.7.12

**Expected Behavior**
This Unicode code point "Not Identical To", or U+2262 (≢) should appear as a triple horizontal bar with a slash through the middle.

**Actual behavior**
On both VSCode 1.25.0 and Discord "Release Channel: stable, Build Number: 18280, Version Hash: 9fed7c903d2a5cd3fba8e16b269ed4b1f48c159f", the slash is drawn off the right-hand side of the triple-bar instead.

**To Reproduce**
Copy single code point U+2262 (≢) and paste into any open editor window in VS Code, or chat in Discord.

See also: https://github.com/Microsoft/vscode/issues/53816

**Screenshots**
U+2262 rendered in VSCode:
![image](https://user-images.githubusercontent.com/6889558/42422891-5bda4924-82a4-11e8-9a37-6b5c7a31981b.png)

U+2262 rendered in Discord Windows client:
![image](https://user-images.githubusercontent.com/6889558/42422894-6c465bcc-82a4-11e8-8e24-1e18c297e381.png)

**Additional Information**
I reported the issue to both VSCode and Discord.  Discord folks responded saying I should report it to Electron:

> :redTick: webhp#1337: Not a Discord bug, Electron and Chromium issue. You may wish to report the bug to Chromium or Electron.
> :redTick: SuperSajuuk#0001: Not a discord bug, the issue is caused by a rendering issue in Electron, one of the frameworks used for the desktop client. You should report it to them so they can fix it.

**Comment by kwonoj** [comment]
I think this is upstream issue https://bugs.chromium.org/p/chromium/issues/detail?id=645723&q=U%2B2262&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified and could see current latest chrome also shows same behavior.

**Comment by MarshallOfSound** [comment]
According to that upstream issue they aren't planning on resolving it as it is a specific font issue.  @jubajube I'd recommend following that issue upstream and seeing if they can resolve it there, because we can't easily resolve it here.

**Comment by jubajube** [comment]
I don't see any avenue for fixing the issue upstream.  I left my 2¢ on the Chromium issue, and thank you for the link.  I'm a bit disappointed that none of you (Electron, Microsoft, and Goggle) really want to fix the underlying issue though.

**Comment by jubajube** [comment]
Just gambling here that it might be a HarfBuzz issue; I don't know anything about HarfBuzz and next to nothing about fonts, but I figured the least I could do was bring it to HarfBuzz community's attention.
