### ISSUE TITLE
Compiled Auto-Updater don't work with private gitlab repository

### ISSUE THREAD

**Issue by MrCodingMen** [electron/electron#13586]
* Electron Version: 1.8.7
* Operating System (Platform and Version): Windows 10
* Last known working Electron version: none

**Expected Behavior**
When I start Electron via `npm start`, the auto-updater works. However, when I compile and start Electron, the following error occurs: `Cannot find channel "latest.yml" update info: HttpError:404` .
**Actual behavior**
Auto-Updater don't work with a private gitlab repository in compiled program.
**To Reproduce**
1. Create a private gitlab repository
2. Create a gitlab private access-token
3. Create the Auto-Updater in your main.js
4. Compile Electron

**Screenshots**
http://prntscr.com/k48se7

**Comment by MarshallOfSound** [comment]
> Cannot find channel "latest.yml" update info: HttpError:404

This error sounds like it's coming from `electron-builder` not from Electron itself, we do not use a `latest.yml` file.
