### ISSUE TITLE
Electron windows visually blurring randomly

### ISSUE THREAD

**Issue by JoshMerlino** [electron/electron#13595]
* Electron Version: 1.8.2
* Operating System (Platform and Version): Windows 10 - 17134
* Last known working Electron version: 

**Expected Behavior**
Electron would render the html normally

**Actual behavior**
Electron rendered html normally at first but after using the window, it became blurry

**To Reproduce**
I'm unsure how to reproduce this issue because it happens seemingly randomly but might be connected to the window blurring (loosing focus). I'm reporting this because it happens with every Electron based application (Including the Electron command and Atom).

**Screenshots**

_You might want to view this in full screen_
![screenshot - 4](https://user-images.githubusercontent.com/31785395/42476102-c9df9bb2-839a-11e8-80b6-c8975625a23f.png)

**Additional Information**
This happens with every Electron application (Including the Electron command and Atom) on my computer.

**Comment by bpasero** [comment]
Could this be https://github.com/electron/electron/issues/13646 ?

**Comment by ckerr** [comment]
This looks like the same issue to me.
