### ISSUE TITLE
WebContents.loadUrl() without cache

### ISSUE THREAD

**Issue by maxkueng** [electron/electron#1360]
Currently there is no option to load content in to a BrowserWindow without loading from the cache. I don't want to disable caching entirely through the `--disable-http-cache` switch as I want to use caching during app use. But I want fresh content to load when starting the app.

My current workaround is to load the content using `loadUrl()` and then use `reloadIgnoringCache()` to load the un-cached content as soon as it has finished loading. But it feels hacky and the window flickers.

Is there a way to not read from the cache initially but still enable caching? Or could it be added by adding a second argument to `loadUrl()` like `loadUrl('http://github.com', ignoreCache)`, or maybe add a function like `loadIgnoringCache(url)`?

**Comment by zcbenz** [comment]
Chromium didn't expose an API to ignore cache when loading URL, so it is not easy to achieve that.

**Comment by maxkueng** [comment]
Thanks for looking in to it! Can we leave this open in case Chromuim ever implements such an API?

**Comment by deepak1556** [comment]
`webContents.loadURL(url, {"extraHeaders" : "pragma: no-cache\n"})` should work.

**Comment by etiktin** [comment]
@deepak1556 awesome find! I think we should had it to the docs

**Comment by deepak1556** [comment]
@etiktin have added it to the docs here https://github.com/atom/electron/pull/3432

**Comment by enlight** [comment]
Closing since this was fixed by #3432

**Comment by wasimxe** [comment]
I added @wv.loadURL(@wv.src, {"extraHeaders" : "pragma: no-cache\n"}) but it is not updating js files included in html , any idea?

**Comment by wasimxe** [comment]
I tried every combination of extraHeader, cache-control:no-cache,no-store etc and expires set to 0 or past time, nothing is working.

**Comment by nuthinking** [comment]
Recently I had some issues too.

**Comment by anthonywebb** [comment]
Cached iframe is making it very difficult to develop.  Wish I could load fresh.

**Comment by RecuencoJones** [comment]
Instead of `extraHeaders` to disable cache or calling `browserWindow.webContents.reloadIgnoringCache()` after getting `ERR_FAILED (-2)` I'm using `browserWindow.webContents.session.clearCache()` before `browserWindow.loadURL()` and it seems to work fine.
