### ISSUE TITLE
desktopCapture return only Entire screen and an invalid window (3.0.0-beta.2)

### ISSUE THREAD

**Issue by webarchymeta** [electron/electron#13617]
* Electron Version: 3.0.0-beta.2
* Operating System (Platform and Version): Current Windows 10, 64bit
* Last known working Electron version: 2.0.4

**Expected Behavior**
Full screen and all opened windows to be returned.

**Actual behavior**
Only full screen and a seemingly identical item are returned. Independent of the number of opened windows. 

**To Reproduce**
Call
```
desktopCapturer.getSources({
    types: ['window', 'screen'],
    thumbnailSize: {
          width: 250,
          height: 250
    }
}, function (err, sources) {

});
```
The `sources` contains only two items, the first one, which is the entire desktop screen is valid, the other one is not.

**Comment by VishwasShashidhar** [comment]
Yes, I can reproduce this as well.
