### ISSUE TITLE
how i can get the url when i use a hyperlink wake up my electron app

### ISSUE THREAD

**Issue by StitchC** [electron/electron#13619]
i want to use hyperlink wake up my electron app and this hyperlink will carry some tokens for my app, i should get this tokens from the url. but now i can't get the url when the app launch. could you tell me how to get the wake up url ?

**Comment by VishwasShashidhar** [comment]
If you are talking about a protocol handler where in your app is opened from a URL, check out https://github.com/electron/electron/blob/master/docs/api/protocol.md#protocolregisterstringprotocolscheme-handler-completion

You can also get it via command line arguments.

**Comment by StitchC** [comment]
thank you for your help~! i've been try this way but it dosen't match my expect, finally i found that i can get the wake url in the process.argv, now i got it ! ^_^

**Comment by ervinewell** [comment]
Are you using windows or mac? I've tried to print "process.argv" in my mac electron app, and I just got the path of the application. @StitchC

**Comment by huzunjie** [comment]
> Are you using windows or mac? I've tried to print "process.argv" in my mac electron app, and I just got the path of the application. @StitchC

@ervinewell Have you solved this problem?
