### ISSUE TITLE
electron desktop capturer source has display_id undefined (windows)

### ISSUE THREAD

**Issue by estatkovsky** [electron/electron#13613]
Electron Version: 2.0.4
Operating System (Platform and Version): Windows 10 x64

**Expected Behavior**
According to documentation desktopCapturer.getSources returns DesktopCapturerSource Object with display_id property.

Link: https://github.com/electron/electron/blob/master/docs/api/structures/desktop-capturer-source.md

**display_id** String - A unique identifier that will correspond to the id of the matching Display returned by the Screen API.

**Actual behavior**
display_id is undefined

**Steps to reproduce**
Invoke desktopCapturer.getSources and check display_id of all sources is undefined

**Comment by sofianguy** [comment]
Hi @estatkovsky can you provide steps to reproduce the issue?

**Comment by estatkovsky** [comment]
Hi @sofianguy. Detailed steps to reproduce:
On Windows 10 machine:
1. Clone electron quick start repo: https://github.com/electron/electron-quick-start;
2. Launch quick start electron app;
3. Open developer tools;
4. Paste and run following code in console:
`require('electron').desktopCapturer.getSources({types: ['screen']}, (error, sources) => { console.log(sources[0].name + " display_id: " + sources[0].display_id); });`
You'll see output:
`Entire screen display_id: undefined`
But display_id must be string identifying matching Display.

**Comment by estatkovsky** [comment]
It seems problem is solved in 3.0.0-beta.2. How can I see Electron v3 planned release date?

**Comment by sofianguy** [comment]
@estatkovsky We currently do not have a planned release date for electron 3.0. We are working on more betas until we reach a certain threshold to release 3.0. I predict we will release in about 2 months, but we are not making any promises. We would love to get to a point where we can have a public release calendar, but we are not at that point right now.
