### ISSUE TITLE
Shared Electron Libraries: one installation to lighten up them all

### ISSUE THREAD

**Issue by adalvigi** [electron/electron#13611]
As everyone knows, Electron is great in terms of easiness of designing GUIs, but has some severe security and memory issues. The need to lock a version of Chromium and Node.js into each app means no easy way to quickly solve security issues (each developer has to update their own app's version manually) and it also means a system running several Electron apps will have 150 MB in it's memory multiplied by the number of open apps, even if they require the same version of the framework. This could also mean more than 1 GB of memory used for stuff as simple as desktop widgets.

A possible solution was proposed by the [Electrino](https://medium.com/dailyjs/put-your-electron-app-on-a-diet-with-electrino-c7ffdf1d6297) project, but I think it's kind of an overkill.

What I think would be the ideal fix to all of the aforementioned, would be to provide an installable "Electron libraries" distribution, which would ideally also be able to receive automatic updates, and an option for developers to release a "lite" version of their app. When the first electron-lite app is loaded, the system starts the installed "Electron libraries", and when another app is started, the same libraries are called. This way not only every app weights less on storage, but also on memory, and we're sure that none of them executes old, security-flawed versions of Node and Chromium. 

Of course this won't (at least immediately) replace the default way of installing electron apps, but developers could suggest, in their install site, to download the lite version + the electron libraries (if the user doesn't already have them installed), so that the amount of informed users who will prefer the safest option will increase.

**Comment by MarshallOfSound** [comment]
Duplicate https://github.com/electron/electron/issues/673
