### ISSUE TITLE
Electron 3.0.2 not run in linux mint 17.3 xfce

### ISSUE THREAD

**Issue by burkoyuriy** [electron/electron#13622]
I do not know whether this is a bug or just not installed dependencies. Code:
home/gs/Рабочий стол/PROECT/image_editor/node_modules/electron/dist/electron: /lib/i386-linux-gnu/libdbus-1.so.3: no version information available (required by /home/gs/Рабочий стол/PROECT/image_editor/node_modules/electron/dist/electron)
/home/gs/Рабочий стол/PROECT/image_editor/node_modules/electron/dist/electron: /lib/i386-linux-gnu/libdbus-1.so.3: no version information available (required by /home/gs/Рабочий стол/PROECT/image_editor/node_modules/electron/dist/electron)

**Comment by jacobq** [comment]
I don't think there is a v3.0.2 yet (see [Releases](https://github.com/electron/electron/releases)). Did you mean 3.0.0-beta.2?

**Comment by burkoyuriy** [comment]
Yes, you are right) I made a mistake. Thank you!

**Comment by burkoyuriy** [comment]
Yes, you are right) I made a mistake. Thank you!
I'm trying to run an application that worked on an electron 2.0.4. This is an image editor based on fabricjs.
When I start a quick start, the application is launched and its internal content is not displayed.

**Comment by jacobq** [comment]
> its internal content is not displayed.

Do you mean it is all black or all white or something else? Perhaps a screenshot would be helpful? When I clone and run the quickstart (per its README.md instructions) I get this:
![image](https://user-images.githubusercontent.com/1633459/42629928-b4379042-859a-11e8-8553-900f040ce465.png)
If I then edit `package.json` to use `'electron': '2.0.4"` and re-run `npm install; npm start`:
![image](https://user-images.githubusercontent.com/1633459/42629985-df82f804-859a-11e8-9a2c-64f4b003f1e0.png)
and similiarly 3.0.0-beta.2:
![image](https://user-images.githubusercontent.com/1633459/42630258-c004b7f0-859b-11e8-9bf6-d50bafe54029.png)

If the quick-start isn't working for you then you should probably try to get some help via chat / forums first as it is most likely a problem with your system rather than an electron issue.

**Comment by burkoyuriy** [comment]
[image: image.jpeg]
What I get when I start the application)

чт, 12 лип. 2018 о 14:25 Jacob <notifications@github.com> пише:

**Comment by jacobq** [comment]
@berkon Can you provide more information? Perhaps run with `./node_modules/electron/dist/electron --inspect-brk .` then open [Chrome DevTools and click the green hexagon (NodeJS logo)](https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27)?

I am also running Linux (Debian 9, x86_64, NVIDIA Quadro K1200 graphics card) but not seeing the problem:
<summary><details>

```
$ clear

jquant@fractal:~/tmp/electron-quick-start$ grep electron package.json 
  "name": "electron-quick-start",
    "start": "electron ."
  "repository": "https://github.com/electron/electron-quick-start",
    "electron": "3.0.0-beta.2"
jquant@fractal:~/tmp/electron-quick-start$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   package.json

no changes added to commit (use "git add" and/or "git commit -a")
jquant@fractal:~/tmp/electron-quick-start$ git log
commit dc1585b235a00bb6842ee2fd0e56fd94fdc1123e
Merge: f9cd070 ec3eacb
Author: Zeke Sikelianos <zeke@github.com>
Date:   Fri May 25 14:43:26 2018 -0700

    Merge pull request #209 from electron/update-main
    
    feat: update index loading for new API

commit ec3eacbf94a4d5552cfd80ed99834b7225259de6
(snip)
jquant@fractal:~/tmp/electron-quick-start$ cat /etc/debian_version 
9.4
jquant@fractal:~/tmp/electron-quick-start$ uname -a
Linux fractal 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
jquant@fractal:~/tmp/electron-quick-start$ npm -v
6.1.0
jquant@fractal:~/tmp/electron-quick-start$ node -v
v8.11.3
jquant@fractal:~/tmp/electron-quick-start$ rm -rf node_modules && npm install && npm start

> electron@3.0.0-beta.2 postinstall /home/jquant/tmp/electron-quick-start/node_modules/electron
> node install.js

Downloading tmp-20356-1-SHASUMS256.txt-3.0.0-beta.2
[============================================>] 100.0% of 5.06 kB (5.06 kB/s)
added 136 packages from 120 contributors and audited 196 packages in 29.068s
found 0 vulnerabilities


> electron-quick-start@1.0.0 start /home/jquant/tmp/electron-quick-start
> electron .

^C
```
</details></summary>

**Comment by berkon** [comment]
@jacobq when using **--inspect-brk** nothing specific happens. Execution stops in the first line of init.js. When I then step through or press the resume button, it simply results in the empty frame appearing (no error on the console ... nothing). I am able to drag around that window. It simply looks like as it would take a screenshot of the background. I can also resize it. Just the content seems not be rendered. Maybe some details of the machine I'm running: Its a Fujitsu ESPRIMO Q957 (Core i5-7500T). With a Intel HD Graphics 530 controller.

**Comment by jacobq** [comment]
@berkon Did you try with `--disable-gpu` anyways? No difference? The reason I mention it is that I have run into [a](https://github.com/electron/electron/issues/4380) [host of](https://github.com/electron/electron/issues/10863) [GPU-related issues](https://github.com/electron/electron/issues/10239) that affected electron on my system (mostly my old laptop) yet did not break Chrome.

Can you get electron's devTools to display? (e.g. try making a [global KB shortcut](https://electronjs.org/docs/tutorial/keyboard-shortcuts#global-shortcuts) or trying to call [`.toggleDevTools`](https://electronjs.org/docs/all#contentstoggledevtools), maybe using [`remote`](https://electronjs.org/docs/api/remote))

Perhaps you may also need to clear any pre-existing user data directory (see [Breaking API Changes](https://electronjs.org/releases#3.0.0-beta.1))

> Switching to an older version of Electron after running this version will require you to clear out your user data directory to avoid older versions crashing. You can get the user data directory by running console.log(app.getPath("userData")) or see electronjs.org/docs/api/app#appgetpathname for more details.

**Comment by berkon** [comment]
@jacobq you absolutely had the right idea! :+1:  When using `--disable-gpu` it works!! I can also see the DevTools now. The way used the DevTools before (with --inspect-brk) was to start Chrome separately open the DevTools there and attach the debugger like you mentioned.

So I think this is worth to be filed as a quite serious bug. I'm not familiar with the process here in the Electron forums. Do you think I should create a new issue or will the Electron folks track it by this one. In my eyes this one does not describe the issue very detailed.

**Comment by jacobq** [comment]
> Execution stops in the first line of init.js. When I then step through or press the resume button, it simply results in the empty frame appearing (no error on the console ... nothing). I am able to drag around that window.

Try pressing "Pause" then resizing the window. Normally this would result in the debugger breaking on a line in `events.js` like: `EventEmitter.prototype.emit = function emit(type, ...args) {`, and if you step into that function you should be able to see the name of the event (e.g. `focus`). While obviously this doesn't fix anything it may give a clue as to what / how much isn't working.

**Comment by jacobq** [comment]
> So I think this is worth to be filed as a quite serious bug. I'm not familiar with the process here in the Electron forums. Do you think I should create a new issue or will the Electron folks track it by this one. In my eyes this one does not describe the issue very detailed.

Well, I can't claim to be an expert either -- just another developer using Electron, fighting my way through the bugs I encounter, and trying to get better at diagnosing / debugging them quickly. I wouldn't open a separate issue. One of the most helpful things you (as someone who can reproduce the problem) is provide detailed information about your environment. For example, if you're willing to share specific hardware details (you already mentioned product names, but something like `lspci -v` output is often more helpful) and works / doesn't work cases (e.g. "tried running quick-start with `npm start` on node 10.6.0 but when the window rendered it appears empty / transparent / (screenshot), etc. Running with `--disable-gpu` option works. Switching to electron version X.Y.Z also works ....")

**Comment by jacobq** [comment]
@berkon just FYI, opening the devtools from chrome and debugging the node process is not the same as opening the devtools in the electron app and debugging the renderer process. Although they might look and feel similar they are different tools looking at different things. For example, you may have noticed that there is no "Elements" tab when debugging the node process, because there is no `window`, no DOM, etc.

> The way used the DevTools before (with --inspect-brk) was to start Chrome separately open the DevTools there and attach the debugger like you mentioned.

**Comment by ckerr** [comment]
As this seems to be a duplicate of the GPU issue tracked by #13415 I'm going to close this ticket. Please follow that issue instead and provide any additional information there.

Thank you all for helping to test the betas and make Electron better. @jacobq thanks for suggesting disabling GPU rendering to see what the effect would be :+1:

**Comment by bpasero** [comment]
I am seeing this message on startup too and I am not sure how to resolve it. Filed https://github.com/electron/electron/issues/16364
