### ISSUE TITLE
Window loading fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by marcoancona** [electron/electron#13624]
* Electron Version: 2.0.4
* Operating System (Platform and Version): Ubuntu 14.04 64bits (on WMware)
* Last known working Electron version: 1.8.7

**Expected Behavior**
The sample Electron app should run and display a window
![1 8 7](https://user-images.githubusercontent.com/2278117/42581339-d0a03766-852c-11e8-90fc-52c0a6b75caa.png)

**Actual behavior**
With Electron 2.x and 3.x the window loading hangs. Enabling debugging, the following error is showed when the process is terminated:
```
ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
```
![2 0 4](https://user-images.githubusercontent.com/2278117/42581512-2beaab88-852d-11e8-8ba4-da82c6b16a48.png)

**To Reproduce**
```
npm install --save-dev electron@2.0.4
./node_modules/.bin/electron
```

**Additional Information**
Interestingly, the problem appears running` ./node_modules/.bin/electron` but not running `./node_modules/.bin/electron > /dev/null`

**Comment by marcoancona** [comment]
Update: possible duplicate of https://github.com/electron/electron/issues/12850 ?

Interestingly, the problem appears running `./node_modules/.bin/electron` but *not* running `./node_modules/.bin/electron > /dev/null`

**Comment by bpasero** [comment]
@marcoancona does it work if you append `--disable-gpu` as argument?

**Comment by marcoancona** [comment]
Yes, it works! To summarize:
```
./node_modules/.bin/electron   [hangs]
./node_modules/.bin/electron --disable-gpu   [ok]
./node_modules/.bin/electron > /dev/null   [ok]
```

**Comment by haroldiedema** [comment]
I can confirm that this is indeed broken on Ubuntu 14.04;


The errors appear to be random though.

```
libGL error: failed to open drm device: No such file or directory
libGL error: failed to load driver: 
                                    �
[xcb] Extra reply data still left in queue
[xcb] This is most likely caused by a broken X extension library
[xcb] Aborting, sorry about that.
electron: ../../src/xcb_io.c:576: _XReply: Assertion `!xcb_xlib_extra_reply_data_left' failed.
```

After running the same command again:

```
electron: ../../src/xcb_in.c:671: xcb_request_check: Assertion `!reply' failed.
```

It seems that something related to 'threading' (I think?) is broken.

However, electron 3 beta seems to works fine so far.

**Comment by Kagami** [comment]
Was reported before: #12380

Minimal reproducable example:

```bash
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start
npm i
ELECTRON_ENABLE_LOGGING=1 npm start -- --v=1
```

Should hang right away.

**Comment by u4aew** [comment]
A similar problem in 3 versions of the electron https://github.com/electron/electron/issues/14430

**Comment by ftoledo** [comment]
> Yes, it works! To summarize (v2.0.4):
> 
> ```
> ./node_modules/.bin/electron   [hangs]
> ./node_modules/.bin/electron --disable-gpu   [ok]
> ./node_modules/.bin/electron > /dev/null   [ok]
> ```

I have similar issue on electron 3.0.5.. redirec output to dev/null or file works. Also  disable-gpu param works too.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by Ladvace** [comment]
I have the same problem on Ubuntu 20.04.2 LTS
