### ISSUE TITLE
HTML5 Notifications broken in 3.0.0-beta

### ISSUE THREAD

**Issue by VishwasShashidhar** [electron/electron#13620]
* Electron Version: 3.0.0-beta.1 or 3.0.0-beta.2
* Operating System (Platform and Version): macOS 10.13 (High Sierra)
* Last known working Electron version: 2.0.4

**Expected Behavior**
When a html5 notification is triggered from the renderer, a toast alert should appear

**Actual behavior**
No toast alert is appearing when a html5 notification is triggered from the renderer

**To Reproduce**
```sh
$ git clone https://github.com/VishwasShashidhar/electron-quick-start -b notifications-3beta
$ npm install
$ npm start || electron .
```
Click on the "send notification" button in the renderer.

**Screenshots**

***Working (2.0.4)***
![electron 2 0 4 notifications](https://user-images.githubusercontent.com/5968790/42554031-ea56866e-8500-11e8-91fe-36f87b4180f9.gif)

***Not Working (3.0.0-beta.2)***
![electron 3 0 0 beta 2 notifications](https://user-images.githubusercontent.com/5968790/42554088-22da29fa-8501-11e8-8ba6-22aa765c5eac.gif)

**Additional Information**
N/A

**Comment by VishwasShashidhar** [comment]
An update, tried on the main process, works fine.

**Comment by ckerr** [comment]
3-0-x branch: https://github.com/electron/electron/pull/13651

**Comment by MarshallOfSound** [comment]
backport merged

**Comment by jakobvogel** [comment]
Thanks for fixing this. Let me please follow up with a (probably) related issue: I used to send an HTML5 Notification from the preload script of a `BrowserWindow`. This works fine in version 2.0.5, but no more in 3.0.0-beta.3 with a `ReferenceError: Notification is not defined`.

**Comment by VishwasShashidhar** [comment]
@jakobvogel Better to create a new ticket for that and reference this.
