### ISSUE TITLE
Electron crash during open DevTools on MacOS (v3.0.0-beta.2) 

### ISSUE THREAD

**Issue by MaxGraey** [electron/electron#13628]
* Electron Version: v3.0.0-beta.2
* Operating System (Platform and Version): macOS 10.13.5
* Last known working Electron version: v3.0.0-beta.1

**Expected Behavior**
Launching DevTools

**Actual behavior**
Electron crash with current dump:
```
Crashing on exception: *** -[__NSArrayM objectAtIndex:]: index 1 beyond bounds [0 .. 0]

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff489d332b __exceptionPreprocess + 171
1   libobjc.A.dylib                     0x00007fff6fb41c76 objc_exception_throw + 48
2   CoreFoundation                      0x00007fff48a14634 _CFThrowFormattedException + 202
3   CoreFoundation                      0x00007fff488f2290 __CFStringDecodeByteStream3 + 0
4   Electron Framework                  0x000000010e7554c2 _ZN9brightray8IOThread7CleanUpEv + 2210
...
```

**Additional info** 
`BrowserWindow` should contain `titleBarStyle` with `hiddenInset` value.

Full dump attached to [link](https://github.com/electron/electron/files/2185677/dump.txt)

**Comment by nitsakh** [comment]
Hey @MaxGraey ! I wasn't able to reproduce this. Do you see it everytime you launch the renderer devtools?

**Comment by nitsakh** [comment]
Thanks @MaxGraey! I was able to verify that. Will take a look at this shortly. (Also, looks like you @ mentioned someone else 😀 )

**Comment by nitsakh** [comment]
Looks like https://github.com/electron/electron/pull/13599 started causing the devtools crash.
