### ISSUE TITLE
The backgroundColor parameter in the BrowserWindow constructor is ignored

### ISSUE THREAD

**Issue by NearAutomata** [electron/electron#13626]
* Electron Version: 3.0.0-beta.2
* Operating System (Platform and Version): Windows 10 Build 1803
* Last known working Electron version: 3.0.0-beta.1

**Expected Behavior**
During creation of the window using `new BrowserWindow({ backgroundColor: "#30404d" })` the Electron window is expected to have that particular background color.

**Actual behavior**
The background color of the window itself (not the page hosted inside of it) is white.

**Comment by sofianguy** [comment]
Hi, can you provide steps to reproduce this issue?

**Comment by NearAutomata** [comment]
@sofianguy I wasn't able to reproduce this issue as it turns out to be caused by something else, namely after reloading the page using `electron-debug` it happens that the background of the window itself is not retained. Since this only happens during development and when debugging rather than during production I won't be bothered by it any longer.
