### ISSUE TITLE
Security scoped bookmarks stopped working since 2.0.0-beta.6

### ISSUE THREAD

**Issue by ymc-thzi** [electron/electron#13638]
* Electron Version: from **2.0.0-beta.6** to **2.0.4** (forthcoming 3 betas also)
* MacOS
* Last known working Electron version:  2.0.0-beta.5

**Expected Behavior**
Security scoped bookmarks works like in 2.0.0-beta.5 for all later versions

**Actual behavior**
When using `dialog.showOpenDialog` with option `securityScopedBookmarks` set to `true` the bookmarks object in the callback is empty. In 2.0.0-beta.5 it works in 2.0.0-beta.6 and all following versions not. The bookmarks object in the dialog callback is empty, so no bookmarks can created and saved.

**To Reproduce**
use dialog.showOpenDialog with option `securityScopedBookmarks` set to `true`, of course only in a packed and sandboxed app on macOS

**Comment by shaoju** [comment]
This seems to be quite a big issue, I'm currently blocked by it. Any chance that it would be fixed in the near future??

**Comment by rr326** [comment]
Actually, they DO work.  Check out my comment [here](https://github.com/electron/electron/pull/11711#issuecomment-445934535).  Try the repo and good luck debugging.

**Comment by codebytere** [comment]
Closing as the issue appears to be resolved with https://github.com/electron/electron/pull/11711#issuecomment-448161835
