### ISSUE TITLE
Detect user switching in Windows/Mac

### ISSUE THREAD

**Issue by chrisgbaker** [electron/electron#13630]
**Is your feature request related to a problem? Please describe.**

Currently I am using electron for a desktop kiosk application. Many keystrokes can be captured/blocked, and many other processes can also be stopped. However, on windows the key combinations of `win+L` or `ctrl+alt+del` cannot be detected, which could allow a user to switch to a different account.

**Describe the solution you'd like**

The ability to detect when a user switches on Windows (and preferably mac, if this fast-switching feature exists), and an event hook, similar to how `electron.powerMonitor` has an event to detect when the machine is suspended.

**Describe alternatives you've considered**

I'm not certain there are any alternatives, as this is the alternative to detecting the aforementioned keystrokes.

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
