### ISSUE TITLE
How to find if the electron app has been freshly installed (Mac)?

### ISSUE THREAD

**Issue by pravin-d** [electron/electron#13633]
I have an app which requires user authentication if the app is freshly installed. This infomation will be save in renderer window's localstorage and on subsequent launch, the save information will be used. I want to be able to clear this data in case the use uninstall the app on Mac. 
On Mac there is no way to clear the cache and userdata automatically while uninstalling. 
So is a there way to know if the app has been re-installed or not ?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
