### ISSUE TITLE
Brotli encoding isse since 1.8.x

### ISSUE THREAD

**Issue by apilz** [electron/electron#13647]
* Electron Version: >= 1.8.x - I used 2.0.4
* Operating System (Platform and Version): Windows
* Last known working Electron version:  1.7.x

**Expected Behavior**
I would like to display a Brtoli encoded page in a BrowserWindow using
webContents.loadUrl('https://www.example.com', {
  extraHeaders: {
    'Accept-Encoding': 'gzip, deflate, br'
  }
});

**Actual behavior**
HTML loads, CSS and all JS files are shown in console log with:
net::ERR_CONTENT_DECODING_FAILED

**To Reproduce**
used the electron start app with above line on a brotli encoded website

**Comment by apilz** [comment]
Well I found a solution using onBeforeSendHeaders.

**Comment by codebytere** [comment]
@apilz in that event, i'm going to go ahead and close this issue.
