### ISSUE TITLE
console.log does not show up in VSCode - "Debug Console" since Electron 2.0.x

### ISSUE THREAD

**Issue by thyrrestrup** [electron/electron#13645]
* Electron Version: 2.0.x
* Operating System (Platform and Version): OSX 10.13.5
* Last known working Electron version: 1.8.7
* VSCode version: 1.25.0

**Expected Behavior**
console.log from main process show up in the "Debug Console" inside VSCode.

**Actual behavior**
console.log from main process does not show up in the "Debug Console" inside VSCode.

**To Reproduce**

```sh
$ git clone https://github.com/octref/vscode-electron-debug.git
$ cd vscode-electron-debug/electron-quick-start
$ npm install
$ code .
```

**_Version 2.0.x_**
1. Add the following to the top of the `main.js` file:
```javascript
console.log({test: 'test'})
```
2. Start debugging the "Debug Main Process" configuration
**Result:** Nothing shows up in "Debug Console".

**_Version 1.8.7_**
1. Reinstall latest working version of electron
```sh
$ npm install electron@1.8.7
```
2. Start debugging the "Debug Main Process" configuration
**Result:** The output shows up in "Debug Console".

**Additional Information**
if `"outputCapture": "std"` is added to the configuration in `launch.json` the output does show up in VSCode but it's not rich (it's not possible to fold/unfold objects and there is no syntax highlighting).

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
