### ISSUE TITLE
Error: Cannot open C:\Users\win 10\AppData\Local\Programs\vipthink\resources\app.asar\dist\electron\xxxx.node

### ISSUE THREAD

**Issue by StitchC** [electron/electron#13641]
after i build the app and run it this error show, i try to decompile the app.asar the .node file inside reliable, could you tell me how to handle this problem?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
