### ISSUE TITLE
setTimeout cannot be util.promisify'ed

### ISSUE THREAD

**Issue by gabmontes** [electron/electron#13654]
* Electron Version: 1.8.4
* Operating System (Platform and Version): macOS 10.13.5
* Last known working Electron version: ?

**Expected Behavior**
`require('util').promisify(setTimeout)(delay).then(callback)` should work as per Node.JS 8.x docs.

**Actual behavior**
`"callback" argument must be a function` error is thrown inside promisified `setTimeout`.

**To Reproduce**
Execute this in the main process:

```js
require('util').promisify(setTimeout)(0).then(console.log('works!'))
```

It will throw the mentioned error.

**Additional Information**
The problem seems to be that `setTimeout[util.promisify.custom]` is not defined. Therefore `util.promisify` tries to promisify `setTimeout` as a standard callback-last function but it is a special-case callback-first one.

See:
https://nodejs.org/api/timers.html#timers_settimeout_callback_delay_args
https://nodejs.org/api/util.html#util_custom_promisified_functions

Haven't tested in v2.x or higher yet. Is there plans to eventually backport a fix for this to the 1.x versions?

Thanks!!

**Comment by jrobeson** [comment]
does electron 1.8.4 include a new enough node?

**Comment by pronebird** [comment]
This works in `node 8.11.2`, but `electron 1.8.4` runs `node 8.2.1` AFAIK. So maybe there is some issue with this.

**Comment by gabmontes** [comment]
@pronebird you are correct. `process.versions` in shows the following:

```json
{
  "http_parser": "2.7.0",
  "node": "8.2.1",
  "v8": "5.9.211.38",
  "uv": "1.13.1",
  "zlib": "1.2.11",
  "ares": "1.10.1-DEV",
  "modules": "57",
  "openssl": "1.0.2l",
  "electron": "1.8.4",
  "chrome": "59.0.3071.115",
  "atom-shell": "1.8.4"
}
```

And yes, Node.js v8.2.1 already supports custom promisifying `setTimeout` but that is not working on this Electron version.

**Comment by pronebird** [comment]
@gabmontes what happens if you print out `setTimeout[util.promisify.custom]`?

**Comment by gabmontes** [comment]
@pronebird Node.JS works fine. I have tested that in several versions as 8.2.1 (to match Electron 1.8.4) and 8.11.x (LTS).

But in Electron, the required property of `setTimeout` is just not set:

```
> promisify.custom
Symbol(util.promisify.custom)
> setTimeout[promisify.custom]
undefined
```

Since it is not set, `setTimeout` is promisified as a callback-last function and breaks because you pass a number to it and it is expecting the callback function there. The error you see in Electron 2.0.5 is the same as in 1.8.4.

**Comment by davidcornu** [comment]
This sounds really similar to https://github.com/electron/electron/issues/13458.

**Comment by gabmontes** [comment]
@davidcornu for sure both issues have the same root cause!

**Comment by miniak** [comment]
@gabmontes Electron specific code is intercepting `setTimeout`, therefore `setTimeout[util.promisify.custom]` was being lost. I am fixing that in https://github.com/electron/electron/pull/13840
