### ISSUE TITLE
On Windows, electron.shell.showItemInFolder() requires all backslashes

### ISSUE THREAD

**Issue by hatton** [electron/electron#13667]
* Electron Version: v2.04 & 3.0.0-beta.2 
* Operating System (Platform and Version): Windows 10
* Last known working Electron version: unknown

**Expected Behavior**

``electron.shell.moveItemToTrash("c:/foo/bar.txt")`` should move the file to the trash and return true.
``electron.shell.moveItemToTrash(path.normalize("c:/foo/bar.txt"))`` should move the file to the trash and return true.

**Actual behavior**

On Mac, this works. On Windows 10 Version 1803 (OS Build 17134.112), it always returns false and does not move the file. 

Note: Meanwhile, ``electron.shell.showItemInFolder("c:/foo/bar.txt")`` works correctly. Although the default delimiter on Windows is of course backslash, this is the first time I can recall forward slashes not working.

**To Reproduce**
Drop this code into renderer.js in [electron-quick-start](https://github.com/electron/electron-quick-start):

```javascript
const electron = require("electron");
const fs = require("fs");
const assert = require("assert");

let path = "d:/temp/test.txt";
fs.writeFile(path, "hello", err => {
  assert(fs.existsSync(path), "could not create the test file at " + path);
  // will fail without this:  path = path.split("/").join("\\");
  const success = electron.shell.moveItemToTrash(path);
  assert(success, "moveItemToTrash returned false");
  if (!fs.exists(path)) {
    console.log("file was removed");
  }
});
```

This seems to be very low priority, as it's so easy to fix your paths. But it did take me a while to figure out why it wasn't working, so I wanted to at least create an easily findable note about it.

**Comment by pronebird** [comment]
that's a correct behavior. The path separator on Windows is `\`. 

If `electron.shell.showItemInFolder("c:/foo/bar.txt")` works that's a bug and that should be fixed. Auto-magic hurts more than helps.

`electron.shell.moveItemToTrash("c:/foo/bar.txt")` cannot work on macOS by any chance, if you mean that the forward slashes work in general on macOS, that's a correct behavior, since the path separator on any unix and including macOS is a `/` forward slash.

**Comment by hatton** [comment]
Well, it's "correct" if you expect Windows to be strict about this, but to a Windows developer, it is unexpected. You don't expect a cross-platform library to be more strict than the normal OS ones. I don't recall a call in Windows ever failing for having forward slash. Two examples:

![image](https://user-images.githubusercontent.com/8448/42757566-cb13b446-88bd-11e8-942e-13a0260b1d8a.png)

And a raw call to shell32.dll from c#:

![image](https://user-images.githubusercontent.com/8448/42757498-86903b96-88bd-11e8-81b7-598c66c60d46.png)

So this makes me wonder if electron actually has code to enforce this more restrictive notion of what a valid Windows path is.

**Comment by hatton** [comment]
I can't see that the [electron code](https://github.com/electron/electron/blob/539b554eccad20891b9d1b59c18e46bf0620831a/atom/common/platform_util_win.cc) is doing anything special to be extra strict.
