### ISSUE TITLE
change viewPosition parameter in enableDeviceEmulation function does nothing

### ISSUE THREAD

**Issue by SJ-AW** [electron/electron#13678]
* Electron version: 2.0.5
  * Operating system: Windows, Mac OS

Hi everyone,

How can I change the "viewPosition" when using enableDeviceEmulation?
I'm not sure to understand the meaning of "screenSize" parameter. It is not really clear for me.

### Actual behavior

What's I expect: window content position/size change.

### Actual behavior

What's I get: only window content size changes.

### How to reproduce

My code: 
```
myWindow.webContents.enableDeviceEmulation({
  screenPosition: 'mobile',
  screenSize: { width: 2560, height: 1400 },
  viewPosition: { x: 50, y: 50 },
  viewSize: { width: 375, height: 812 }
})
```

I am not sure "viewPosition" parameter is taken into account.

My final purpose is to center my window content with a mobile size.

Thanks

**Comment by SJ-AW** [comment]
Ok @sofianguy thank you. But I also opened a github issue here because I think it's a bug. I am not sure 'viewPosition' parameter work.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
