### ISSUE TITLE
Black Screen for few secs.

### ISSUE THREAD

**Issue by pareshmutha** [electron/electron#13675]
* Electron Version:2.0.0
* Operating System (Platform and Version):windows8/10
* Last known working Electron version: 1.6

I have created a build with latest Electron version. When I launch the electron window for few secs I see Black screen then actual content gets loaded.
So I am not able to find the bugs, what wrong.
With previous version its working fine.

The black screen must not be seen.

Below is the screenshot of the electron application:
![issue1](https://user-images.githubusercontent.com/5389741/42752226-d9846172-890a-11e8-86ae-97be49e70049.jpg)

**Comment by haroldiedema** [comment]
Is the default background color of the browser window black?

If that is the case and the page you're loading takes a few seconds to appear, try setting `show: false` in your `BrowserWindow` config and call `.show()` in a listener for the `ready-to-show` event.

I belive there is an example somewhere in the BrowserWindow documentation for this exact use case.

**Comment by pareshmutha** [comment]
My Config file

mainWindow = new BrowserWindow(
		{
			show: false,
			width: w,
			height: h,
			icon: __dirname + '\\abc.ico',
			resizable:false,
			maximizable:false,
			fullscreen: false,
			fullscreenable: false,
			title:"XYZ"
		}
	)
	mainWindow.once('ready-to-show', () => {
		mainWindow.show();
	})
I have done the same 
As "ready-to-show" is getting called with some delay so between that it is showing black window.
Tried setting backgroundColor: '#fff', but as mainWndow is not showed then backgroundColor is also not shown.
And this is happening on Windows and with latest Electron version.

Thanks

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR.
