### ISSUE TITLE
pass parameters to a new browserWindow in electron

### ISSUE THREAD

**Issue by fathidk** [electron/electron#13671]
* Electron version: v2.0.2
* Operating system: windows 7

* Last known working Electron version: 

### How to reproduce

i want to pass parameters   in the url  of a  new browserWindow   like this 
 newWindow.loadFile(`${__dirname}/src/index.html?param=somthing`)   but i see in the console  that  it is not allowed to load local resources   and  it works fine when i remove  the query    

So how can i do  it ?

**Comment by MarshallOfSound** [comment]
loadFile expects the parameter to be a relative path to the file, it doesn't use string concatenation.

If you want to use query paramaters you will need to use loadURL and resolve the path yourself

**Comment by fathidk** [comment]
thanks i didnt realize the difference between loadFile and LoadURL     and it is working now   thanks
