### ISSUE TITLE
SIGPIPE crash when forked process accesses stdout

### ISSUE THREAD

**Issue by bpasero** [electron/electron#13679]
* Electron Version: 1.8.x and 2.0.x
* Operating System (Platform and Version): macOS 10.13.5
* Last known working Electron version: 1.7.x

**Expected Behavior**
A forked process should never crash with a SIGPIPE error.

**Actual behavior**
A forked process crashes with SIGPIPE error.

**To Reproduce**
This one has some steps involved to reproduce:
* `git clone https://github.com/bpasero/electron-quick-start.git`
* `git checkout sigpipe`
* `npm install`
* `./start.sh`
* open developer tools in the renderer
* notice the output `CHILD EXIT: null / SIGPIPE`

**What is going on**
This seems to be a regression starting with Electron 1.8.x which still reproduces in Electron 2.0.x. Here is what the sample does:
* `start.sh` launches `cli.js` using Electron with `ELECTRON_RUN_AS_NODE` and terminates
* `cli.js` spawns Electron with the `main.js` script configuring `{ stdio: 'pipe' }`
* `main.js` brings up a normal window (code borrowed from the `electron-quick-start repo`)
* window forks a process `asar.js` and logs the exit code of that process
* `asar.js` is simply doing a `fs.stat` on a file which has the `.asar` extension but is actually not a valid ASAR archive
* this triggers https://github.com/electron/electron/blob/master/atom/common/asar/archive.cc#L167 in native code which itself triggers the `LOG(ERROR)` macro
* this seems to trigger a `SIGPIPE` crash

If you run the same example via `npm start` you actually see the output in the console:

`[0716/152325.373539:ERROR:archive.cc(170)] Failed to parse header size from ./foo.asar`

If you attach Xcode to the forked process with an Electron build that has debug symbols, you can see the stacktrace leading to this crash:

![crash-1](https://user-images.githubusercontent.com/900690/42760918-45fb9dd8-890c-11e8-96cd-3f43cf0b2070.png)

This causes https://github.com/Microsoft/vscode/issues/52583 for VS Code.

This example is just using ASAR to trigger the `LOG(ERROR)` statement (that is how we found out about it). It is possible that a lot more code paths can lead to this crash.

**Comment by sofianguy** [comment]
@bpasero is this bug still happening on version 4.x or later?

**Comment by bpasero** [comment]
Not sure, we have not seen it since ever we applied the workaround.

**Comment by sofianguy** [comment]
Ok, I'm going to close this but we can reopen if it happens on later versions
