### ISSUE TITLE
Rendering process crashes for some secs.

### ISSUE THREAD

**Issue by Neil-Pan** [electron/electron#13698]
* Electron Version:2.0.2
* Operating System (Platform and Version):windows 7 64
* Last known working Electron version: 1.8.4

**Expected Behavior**
Rendering process not crashes

**Actual behavior**
Rendering process crashes

**To Reproduce**
Your best chance of getting this bug looked at quickly is to provide a REPOSITORY that can be cloned and run.

You can fork [electron-quick-start](https://github.com/electron/electron-quick-start) and include a link to the branch with your changes.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone $YOUR_URL -b $BRANCH
$ npm install
$ npm start || electron .
```
**Screenshots**

**Additional Information**

**Comment by codebytere** [comment]
hi @Neil-Pan, this issue provides no clear description of the crash nor does it allow us to reproduce the issue so that we can potentially address it.

Please fill in the boilerplate template you left above or we will need to close this issue

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
