### ISSUE TITLE
electron 3 beta2 dev tools disconnect with vm use

### ISSUE THREAD

**Issue by jdalton** [electron/electron#13690]
Modifying the electron-quick-start to repro. 

Make the renderer script tag:
```html
<script>
const vm = require('vm')
vm.runInNewContext("'a' in global", { 
  global: Function("return this")()
})
</script>
```
and open the dev tools with `mainWindow.webContents.openDevTools()` from the main script will cause the dev tools to disconnect as:

> <img width="80%" src="https://user-images.githubusercontent.com/4303/42792099-9b7141de-8928-11e8-970f-92e045fff736.png">

**Update:**

This appears to affect Electron 2 too.

**Comment by jdalton** [comment]
This appears to affect Electron 2 too.

**Comment by ckerr** [comment]
Confirmed. This is present in 2.0 and 1.8 as well.

**Comment by sofianguy** [comment]
@jdalton is this bug still happening on version 4.x or later?

**Comment by sofianguy** [comment]
@jdalton I'm going to close this but we'll reopen if you find this bug in later versions of electron
