### ISSUE TITLE
Excessive memory usage with webContents.printToPDF

### ISSUE THREAD

**Issue by bmathews** [electron/electron#13702]
* Electron Version: 2.0.5
* Operating System (Platform and Version): OSX
* Last known working Electron version: n/a

**Expected Behavior**
`webContents.printToPDF()` shouldn't consume 4gb of memory. Using the `.print()` and manually choosing "Save as PDF" behaves as expected and produces the same result with no excessive memory usage. 

**Actual behavior**
`webContents.printToPDF()` exceeds 4gb of memory.

**To Reproduce**
https://github.com/bmathews/electron-printToPDF-memory.git
```sh
$ git clone https://github.com/bmathews/electron-printToPDF-memory.git
$ cd electron-printToPDF-memory
$ npm install
$ npm start
```

In sample application: 

**Using `.print()` (normal memory usage):**
```
1. Click `print()` button, wait for print dialog to load,
2. On OSX, change dropdown in bottom left of print dialog to "Save as PDF".
3. Choose output path. Observe memory usage remain normal during print. (Takes ~40 seconds)
```
**Using `.printToPDF()` (excessive memory usage):**
```
1. Click `printToPDF()` button. Observe memory usage exceed 4gb.
```

**Comment by timfish** [comment]
If I change this code:
```
function createAndLoad() {
  return new Promise(resolve => {
    const bw = new BrowserWindow();
    bw.webContents.loadFile("./markup.html");
    bw.webContents.on("did-finish-load", () => resolve(bw));
  });
}
```
To this:
```
function createAndLoad() {
  return new Promise(resolve => {
    const bw = new BrowserWindow();
    bw.loadFile("./markup.html");
    bw.on("did-finish-load", () => resolve(bw));
  });
}
```
The leak no longer occurs. I'm guessing this is caused by leaking of `remote` objects but not 100% sure. 

However, just because you _can_ access many of the Electron main process API's from the renderers via `remote`, it doesn't mean it's a great idea to do so. 

You should create the new `BrowserWindow`s from the main process and signal this from the renderer using IPC.

**Comment by bmathews** [comment]
@timfish It doesn't look like `did-finish-load` is being emitted from the BrowserWindow object, so with your snippet there I'm not seeing that `createAndLoad` function resolve to actually start the printing.

**Comment by bmathews** [comment]
Dang, yeah I'm still seeing the 4+ gb memory usage even after moving the BrowserWindow creation and printing to the main process. I've updated the example repo to demonstrate that.

**Comment by timfish** [comment]
Doh, @bmathews you're right, I totally missed that. 

I opened `markup.html` in Chrome 68.0.3440.75 and tried to save to PDF and it crashes too after consuming 4+GB of memory. That means it's an upstream issue with Chrome so we'll need to report it there, or see if there is an existing bug open for it.

**Comment by bmathews** [comment]
You're right. Thanks! Will take it up the the chromium team.
