### ISSUE TITLE
Browser window is not transparent when an image is loaded using loadURL()

### ISSUE THREAD

**Issue by brnlee** [electron/electron#13709]
* Electron Version: 2.0.2
* Operating System (Platform and Version): Windows 10 Version	10.0.17134 Build 17134

**Expected Behavior**
Loading an image into a frameless, transparent Browser Window should be transparent.

**Actual behavior**
The extra space between the image and the Browser Window is black.

**To Reproduce**
Create a frameless and transparent Browser Window and then use the loadURL method to load an image  smaller than the Browser Window from the internet. 
`sample= new BrowserWindow(
        {
            width: 600,
            height: 600,
            frame: false,
            transparent: true,
        })
    sample.loadURL('https://banner2.kisspng.com/20171202/fe0/github-png-image-5a22bb78d0b9f8.366281471512225656855.jpg');`

**Screenshots**
https://i.imgur.com/NI7vOBd.png
In my use case, I used CSS to change a square image into a circular one but there is still a black background. I have tried omitting the CSS altogether but the results are the same.

**Additional Information**
I tried loading the same image inside an html file and then using loadURL to load the local html file and there was no problem. There is only an issue when I'm loading the image directly using loadURL.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
