### ISSUE TITLE
transparent window rendering expectation on  windows basic theme windows 7 

### ISSUE THREAD

**Issue by zjruan** [electron/electron#13711]
* Electron Version: all
* Operating System (Platform and Version): windows 7
* Last known working Electron version: null

I have a Windows 7 computer with a low configuration. When I run my electron app on it, there are some other software that will detect the performance of the graphics card. When the performance of the graphics card is detected is insufficient, it is recommended to change the windows aero theme to the windows basic theme. But we know that the windows basic theme does not support window transparency. At this time, the transparent window of my electron app will render an exception. But our goal expectation should not be normal rendering as if there is no transparency property?

**Screenshots**

**Additional Information**

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR.
