### ISSUE TITLE
3.0.0-beta.3 - Hard-killing electron from terminal or taskmanager leaves a ghost process eating up a few CPU cores.

### ISSUE THREAD

**Issue by haroldiedema** [electron/electron#13710]
* Electron Version: 3.0.0-beta.2 and 3.0.0-beta.3 (beta.1 = untested)
* Operating System (Platform and Version): Windows 10 x64
* Last known working Electron version: 2.x

**Expected Behavior**
Pressing `CTRL+C` or killing the process through the task manager should not spawn new electron processes that eat up 1 or 2 full CPU cores.

**Actual behavior**
Killing an electron process that was started from a terminal (`./node_modules/.bin/electron .`) using CTRL-C or by ending the process (tree) in task manager spawns 2 new(? - not sure if they're actually new) processes that eat up one or two full CPU cores.

I noticed this after a couple of hard-kills when my Spotify music started to stutter... heh.

**To Reproduce**
- Create a blank app and spawn a browser window.
- Start electron from a terminal,
- Hard-kill the process from the terminal (CTRL-C) or from the task manager.

I haven't tested this with a project besides my own. The only thing that might be worth noting is that I'm making 'heavy' use of workers in my project. (building a 3d / game engine with at least 6 workers running constantly and 16 sitting idle / perform tasks when requested). Maybe it's not killing them properly?

I noticed the following things:
```javascript
let wnd = new BrowserWindow({ ... });
wnd.on('ready-to-show', () => {
    wnd.show();
})

// do things...
wnd.close(); // <-- this doesn't do anything.
```

Also, I have this in my app:
```javascript
app.on('window-all-closed', () => {
   app.quit(); // <-- doesn't do anything.
    process.exit(0); // <-- works as intended.
});
```

Also, not sure if this is related;
If you execute `app.quit` in a window `close` event (`wnd.on('close', () => app.quit());`) electron will fork-bomb you. Instead of spawning one or two processes that eat up a CPU core, it seems to spawn a whole lot more.

**Please note though** that everything works as intended if you just close a window normally. It will trigger the `window-all-closed` event and shutdown properly, leaving no traces of spawned processes behind. Once I figured this out, I didn't really spend much time on this issue myself, so I haven't done a very thorough investigation regarding this issue.

It's nearly 1:30 am where I am and I have to get to work tomorrow morning. If needed I'll try to provide a small sample the coming days if it's really needed.

**Screenshots**
![image](https://user-images.githubusercontent.com/567518/42850548-72d44f5e-8a28-11e8-8e79-5c2133ec1300.png)

**Comment by MarshallOfSound** [comment]
cc @deepak1556 Maybe the proxy process isn't parented correctly?

**Comment by haroldiedema** [comment]
I've tried reproducing this in the office (running Ubuntu 14.04 here), and I haven't been able to reproduce it.
That being said, I think this might be a Windows-specific issue.

I'll try to cook up a small repo when I get home from work tonight.

**Comment by haroldiedema** [comment]
Alright, I figured out what's causing this.

All you need to do is add `app.commandLine.appendSwitch("in-process-gpu");` at the start if your main.js file.

Here's the fork; https://github.com/haroldiedema/electron-quick-start

Specs:
Windows 10 (10.0.17134) x64.
Intel core i7 8700K, 32GB ram
NVidia GTX 1070

I do hope this command line switch stays in though since I need it to make steam overlay render properly when running the engine from steam.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
