### ISSUE TITLE
Allow registering global shortcuts before `app.isReady`

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#13716]
**Is your feature request related to a problem? Please describe.**

This limitation is problematic:

> You should not use this module until the ready event of the app module is emitted. - https://electronjs.org/docs/api/global-shortcut

**Describe the solution you'd like**

I need the ability to register a shortcut at launch before the rest of my code runs, which means before `app.isReady()`.

I'm trying to add ability to activate a debug-mode in my app when someone presses, for example, Control+Shift+D at launch.

**Comment by MarshallOfSound** [comment]
@sindresorhus These shortcuts are completely global (like they work outside of your app).  Claiming Control+Shift+D globally to enter debug mode in your app doesn't side like something you want to be doing.  You probably want to use a menu accelerator instead so the shortcut is local to just your application?

In terms of the actual request, I can't speak to exactly what the technical limitations are here but I believe the limitation comes directly from Chromium code.

**Comment by sindresorhus** [comment]
@MarshallOfSound That was just an example. I would probably go with Control+Shift+Alt+D, and I would unregister it right after launch, so it would only be registered for a second.

**Comment by timfish** [comment]
I was looking for something similar before and stumbled across [iohook](https://www.npmjs.com/package/iohook). 

I think the problem you'll have is that it probably can't detect that keys are already held down.

**Comment by miniak** [comment]
@sindresorhus with some native code in a node module you can use OS APIs to check the presssed state of keys

**Comment by timfish** [comment]
I stand corrected! It also [looks possible](https://stackoverflow.com/a/16283140/106623) on macOS!

**Comment by sindresorhus** [comment]
@miniak I'm aware it's possible with native code, but the project I'm working on can't use native dependencies.

**Comment by codebytere** [comment]
This is a hard technical limitation of Chromium unfortunately: it's technically possible but we'd need to re-implement swathes of the code ourselves and so at this time we don't feel it's maintenance burden that's wise to take on. Should something change on Chromium's end, however, we can definitely return to this.
