### ISSUE TITLE
Force render process to crash

### ISSUE THREAD

**Issue by daniloprates** [electron/electron#13720]
* Electron Version: Latest
* Operating System (Platform and Version): Windows, Intel(R) Core(TM) i7-2760QM CPU @ 2.40GHz

Is it possible to force the render process to crash, like the `process.crash()` for the main?

Some users complain they get a white screen in two different situations:

* Some of them get the white screen when they open the app;
* Others get it after leaving the app open for several hours.

Unlike the main process, I'm having a hard time reproducing these crashes in the render process.

**Comment by miniak** [comment]
@daniloprates You can call `process.crash` in the renderer process as well.
