### ISSUE TITLE
Electron 2.0.x - Keyboard navigation into webview is not working

### ISSUE THREAD

**Issue by juturu** [electron/electron#13721]
* Electron Version: 2.0.x
* Operating System (Platform and Version): Mac & Win
* Last known working Electron version: 1.8.7

1. Open Electron app with webview
2. Unable to tab into webview contents

**Expected Behavior**
Keyboard tabbing into webview should be working

**Actual behavior**
Keyboard tabbing into webview doesn't move keyboard focus into webview contents.

**To Reproduce**
Open any simple app with webview pointing to any URL.
Start keyboard tapping to go into webview contents.

**Comment by alexeykuzmin** [comment]
Simplest setup to reproduce the issue:
https://github.com/alexeykuzmin/electron-quick-start/tree/repro-for-13721

**Comment by alexeykuzmin** [comment]
@juturu 

FYI, if a `webview` has a `tabindex` attribute with a non-negative value, e.g. `tabindex="0"`, then the webview _can_ be focused with a keyboard.

**Comment by sofianguy** [comment]
@juturu is this bug still happening on version 4.x or later?

**Comment by sofianguy** [comment]
I'm going to close this for now, but we can reopen if this issue still happens on later versions of electron
