### ISSUE TITLE
Single exe  file with and without Installer Wizard

### ISSUE THREAD

**Issue by anilveridic** [electron/electron#13728]
HI,

I am new in Electron Js,  i am curious to know is there any feature in electron js that we can convert electron app to a single .exe without installer wizard, 

when is use "electron-packager" it gives me the exe file with along with dependency dll's i want a stand alone exe which do not require any other files which have option of Win Installation wizard 

"Single exe  file **with and without** Installer Wizard"

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by MarshallOfSound** [comment]
You're probably looking for --> https://github.com/electron/windows-installer

**Comment by anilveridic** [comment]
thanks @MarshallOfSound   as i mentioned above i used  "electron-winstaller" but it has the installation wizard , i need a single exe but it has to open directly without any installation . i am asking for that feature. do not need any code assistance

**Comment by MarshallOfSound** [comment]
That module has no wizard, it generates a single executable that installs your app with no user input.

**Comment by anilveridic** [comment]
yes that i am asking i dont net to install that exe just to open the app, casue it install the app in local system,

"As we use **electron-packager**  it will generate exe and all other dependency dll in one folder as we click on exe file it open the app" i just want to get rid of all extra files n dll just want single exe with no installation.
