### ISSUE TITLE
3.0.0-beta.3 - webview URLs can't be set programmatically

### ISSUE THREAD

**Issue by magne4000** [electron/electron#13723]
* Electron Version: `3.0.0-beta.3`
* Operating System (Platform and Version): `macOS 10.13.6`
* Last known working Electron version: `2.x`

**Expected Behavior**
`webview` should refresh when using the following methods:
- `webview.src = 'https://some-url'`
- `webview.loadURL('https://some-url')`
- `webview.getWebContents().loadURL('https://some-url')`

**Actual behavior**
The 3 methods above are broken in Electron 3.0. The underlying webcontents seems to operate normally, but the webview is stuck (we can't interact with it anymore, and it has not repaint itself)

**To Reproduce**
Steps in the PR: https://github.com/magne4000/electron-quick-start/pull/2
```sh
$ git clone https://github.com/magne4000/electron-quick-start.git -b webview-load-url-issue
$ npm install
$ npm start || electron .
```

**Comment by zcbenz** [comment]
I'm merging this to https://github.com/electron/electron/issues/13503 since they are essentially the same bug.
