### ISSUE TITLE
Window title in third party app switcher

### ISSUE THREAD

**Issue by lasekio** [electron/electron#13722]
* Electron Version: 3.0.0.beta.3
* Operating System (Platform and Version): Mac OS X 10.13.6
* Last known working Electron version: 2.0.5

**Expected Behavior**
Window title (`document.title`) shows as window title using third party window switcher like [Contexts](https://contexts.co/)

**Actual behavior**
It shows app name (`Electron`) instead of window title

**To Reproduce**
1. Install contexts app or other window switcher that shows window titles
2. Clone and run untouched [electron-quick-start](https://github.com/electron/electron-quick-start) with `npm start`
3. Run app switcher and you see app with `Hello World!` title (see screenshot)
4. Install electron beta 3 `npm install --save-dev electron@3.0.0-beta.3` and run app again `npm start`
5. Run app switcher and you see app with `Electron` title (see screenshot)

**Screenshots**
Electron v2:
<img width="678" alt="ss1" src="https://user-images.githubusercontent.com/8137000/42895558-94145726-8aba-11e8-8c23-c9dcce152e06.png">

Electron Beta:
<img width="683" alt="ss2" src="https://user-images.githubusercontent.com/8137000/42895724-05a06fce-8abb-11e8-8f8a-7f42c774ef17.png">

**Additional Information**
I know is it some sort of corner case but it is still a regression plus this can indicate non-native windowing

**Comment by nitsakh** [comment]
Interesting.. I use HyperSwitch[https://bahoom.com/hyperswitch] for switching windows and this doesn't repro with it.

**Comment by lasekio** [comment]
Can you try with Contexts? Its free to download

**Comment by nitsakh** [comment]
Yeah! I am able to see the issue with Contexts trial. Not sure what's different/what's going on. 😕 
Will look into this further.
(Also, Contexts works pretty cool!)

**Comment by nitsakh** [comment]
Pretty sure this is a focus related issue in 3.0.x. Probably related to #13913.

**Comment by codebytere** [comment]
^ moved to card, not removed

**Comment by nitsakh** [comment]
Closing as the PR has been merged now.
