### ISSUE TITLE
2.0.4 - ERR_UNSAFE_REDIRECT in webview

### ISSUE THREAD

**Issue by debelop13** [electron/electron#13729]
* Electron Version: 2.0.4
* Operating System (Platform and Version): macOS Hish Sierra 10.13.6
* Last known working Electron version: 1.8.4

**Expected Behavior**
I want that webview can redirect.

**Actual behavior**
Webview is not rerdirecting and is giving and error named ERR_UNSAFE_REDIRECT.

**Additional Information**
I add in webview the following preferences, but continue giving the error.

       <webview src={{url}}
                class="loaded"
                allowpopups
                disablewebsecurity
                webpreferences="allowRunningInsecureContent, webSecurity=false"
                autosize="on"
                preload="../ember-electron/preload.js">
        </webview>

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).

**Comment by mushishi78** [comment]
@sofianguy This looks like a bug report to me? o.O
