### ISSUE TITLE
Unable to set Chrome's fieldtrials flag

### ISSUE THREAD

**Issue by RickChenx** [electron/electron#13731]
* Electron Version:v2.0.3 or 3.0.0-beta.3
* Operating System (Platform and Version):win10

**Expected Behavior**
I’m trying to set force-fieldtrials with appendSwitch to my application in order to enable a trial feature of WebRTC (VP9 SVC)

**Actual behavior**
 it doesn’t seem to work

**To Reproduce**
```
// on main.js
app.commandLine.appendSwitch('force-fieldtrials', 'WebRTC-SupportVP9SVC/EnabledByFlag_2SL3TL/');
```

**Comment by leoagle** [comment]
same on 4.0.0-beta.5

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by ashish-1689** [comment]
It is still not working for me. I am on latest stable version 10.1.2

app.commandLine.appendSwitch('force-fieldtrials', 'WebRTC-SupportVP9SVC/EnabledByFlag_3SL3TL');
