### ISSUE TITLE
Apps stuck on Linux

### ISSUE THREAD

**Issue by MehediH** [electron/electron#13733]
* Electron Version: 2.0.4.
* Operating System (Platform and Version): Ubuntu 18.04
* Last known working Electron version: N/A

**Expected Behavior**

The app should not crash when a `<webview>` is loaded. Tried both on a VM (Ubuntu) and an actual machine running Antergos. 

**Actual behavior**

The app works fine perfectly, till a `<webview>` is loaded, crashing the app and the dev tools. It does work when running the app from the terminal with `--disable-gpu` but doesn't work for compiled apps (built for Snap with electron-builder) as it's not possible to enable the flag there.

**Screenshots**

Here is a GIF showing how the app gets stuck when a `<webview>` is loaded. 

![2018-07-19_14-09-49](https://user-images.githubusercontent.com/10274434/42944758-6e27429a-8b5e-11e8-988d-7c8a78b013ed.gif)

**Comment by MehediH** [comment]
I was able to repro this with the basic electron-quick-start app as well:

![2018-07-19_16-19-54](https://user-images.githubusercontent.com/10274434/42952117-a38bbaea-8b6f-11e8-844f-dbf8010d14bb.gif)

**Comment by MehediH** [comment]
Hi, just clone electron-quick-start and run the app with mom start from terminal.

**Comment by nornagon** [comment]
electron-quick-start doesn't contain any webview code. if this issue is with webview, then electron-quick-start won't reproduce it.

**Comment by MehediH** [comment]
@nornagon I understand your point but it doesn't really have anything to do with this. Even if you make a fresh new Electron app with a very basic webview tag, this issue still occurs.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
