### ISSUE TITLE
Do not add file extension to new file if specified filename contains one already

### ISSUE THREAD

**Issue by lukas-lang** [electron/electron#13732]
* Electron Version: 2.0.0
* Operating System (Platform and Version): Windows 10, build 17134.165
* Last known working Electron version: -

**Expected Behavior**
When using `dialog.showSaveDialog` and specifying a file name with extension, the extension from the filter should not be appended. Example: Filter: `*.txt`, entered file name: `foo.bar`. Expected result: file name `foo.bar`.

**Actual behavior**
The extension from the filter is always appended, i.e. the example above yields `foo.bar.txt`.

**To Reproduce**
Clone this repo and run it.
```sh
git clone https://github.com/lukas-lang/electron-quick-start.git -b SaveDialogBug
npm install
npm start || electron .
```
Choose the file name `foo.bar`. Look at the console: The filename reported is `foo.bar.txt`.

**Additional Information**
Bug report initially posted here:
https://github.com/Microsoft/vscode/issues/54347

**Comment by MarshallOfSound** [comment]
As @isidorn initially pointed out in the vscode issue this is expected OS behavior.  Most apps follow this pattern, the simplest example is Notepad.  Create a file, save it and the `.txt` extension will automatically be added if it isn't already there.

Closing out as expected behavior

**Comment by lukas-lang** [comment]
Well, you can hardly take Notepad as benchmark for anything.

Besides, this makes it really difficult to use electron based code editors, as it's really time consuming to scroll to the "all files" filter for each file. Also, every real editor I've tested works as expected: Notepad++, Sublime Text and even WordPad (which is part of Windows) to name a few.

**Comment by lukas-lang** [comment]
To clarify (I just noticed that I might not have expressed myself clearly enough in the issue description): The default extension should of course be added if no extension is specified - so `foo` should become `foo.txt`. The issue is really just the double extensions produced if the user wants to save a file using a custom extension.

It would be great if you could reconsider this.

**Comment by kymikoloco** [comment]
For a far quicker workaround on Windows to avoid looking for 'all files', just append a double dot `..` at the end of the filename extension to prevent Electron/VSCode from adding `.txt`. It even works for extensionless filenames like `Dockerfile`, `Jenkinsfile`, etc

Ex. File name box should have `Dockerfile..` or `example.js..` and it will save with the appropriate extension.

![image](https://user-images.githubusercontent.com/3211064/78046864-ad8f2a80-7345-11ea-9f78-16392287a247.png)
