### ISSUE TITLE
Webcal links not shown as clickable links

### ISSUE THREAD

**Issue by MattIPv4** [electron/electron#13741]
* Electron Version: 1.5 (So the people of Discord say)
* Operating System (Platform and Version): macOS 10.14
* Last known working Electron version: N/A

**Expected Behavior**
Link http(s):// links, webcal:// links show be clickable and link to the calendar app like when invoked from a webpage.

**Actual behavior**
They simply display as unclickable text.

**To Reproduce**
Head over to the great Discord (or MS Teams), send a webcal link such as (webcal://www.webcal.fi/cal.php?id=50&format=ics&wrn=1&wp=1&wf=4&color=%23FF00FF&cntr=&lang=en&rid=wc) in chat and observe how it isn't clickable like a normal link.

**Screenshots**
![https vs webcal on Discord](https://i.dabbitpri.me/r493nhavce.png)

**Additional Information**
Tested in both Discord and MS Teams. Guys from Discord told me to report it here, not on Discord's bug reporting system. Please let me know if you have any questions regarding this.

**Comment by MarshallOfSound** [comment]
> Guys from Discord told me to report it here, not on Discord's bug reporting system

This is a bad idea, this is not an issue with Electron.  Browsers / Electron do not auto-linkify thing, this will be in-house logic not linkifying strings of that style
