### ISSUE TITLE
Raspberry Pi navigator.mediaDevices.getUserMedia DevicesNotFoundError

### ISSUE THREAD

**Issue by lastmjs** [electron/electron#13744]
* Electron Version: v2.0.5
* Operating System (Platform and Version): Raspberry Pi Model 3B, 2018-06-27-raspbian-stretch.img
* Last known working Electron version: No working version that I know of

**Expected Behavior**
When I run the following in the Electron console:
```javascript
window.navigator.mediaDevices.getUserMedia({video: true}).then((stream => console.log(stream));
```

I expect my webcam to be found and the stream to be returned correctly. This works fine for Chromium v65.0.3325.181 on my Raspberry Pi, and it was also working for Firefox ESR.

**Actual behavior**

This error is always thrown:

```javascript
Uncaught (in promise) NavigatorUserMediaError {name: "DevicesNotFoundError", message: "", constrainName: ""}
```

Also, when I run the following:

```javascript
window.navigator.mediaDevices.enumerateDevices();
```

I receive an array of `MediaDeviceInfo` objects, and the `videoinput` object that represents my webcam is there, though I can never get its stream.

**To Reproduce**

Install a fresh image of Raspbian Stretch (with Desktop) from here: https://www.raspberrypi.org/downloads/raspbian/, then create a fresh Electron project. Make sure you hook up a webcam, I'm using a Raspberry Pi Camera v2.1. Try everything out in the default Chromium browser by going to any webcam testing website, like this: https://simpl.info/getusermedia/ If your camera isn't working, run the following: `sudo modprobe bcm2835-v4l2` Now just open up an Electron window and go to the console and try the commands.

**Additional Information**

I would like to try this with a newer version of Electron and thus Chromium, but unfortunately I am blocked by https://github.com/electron/electron/issues/13745

**Comment by lastmjs** [comment]
With Electron v3.0.0-beta.3, the issue is resolved

**Comment by sofianguy** [comment]
closed as it is reportedly fixed ^
