### ISSUE TITLE
serviceworker: Request scheme 'file' is unsupported

### ISSUE THREAD

**Issue by alvaromarithompson** [electron/electron#13740]
* Electron Version: 2.0.5
* Electron Build Version: 20.22.4
* Operating System Windows 10 Pro
* Last known working Electron version: N/A

**Expected Behavior**
Pack the React application using electron-build, and be able to run the same application in production as I do in development

**Actual behavior**
When I run the packed version in Windows of my Electron application (using NSIS), the application is blank, and I have the following error appear in the Dev Tools console:

`
service-worker.js:1 Uncaught (in promise) TypeError: Request scheme file is unsupported

    at service-worker.js:1

    at <anonymous>
`

**To Reproduce**
There seem to be no exact pattern to this happening, I've tried to strip down my code bare to see if it's a specific component that's causing this, but even stripping the application to basic React code, I can't get a consistent way of reproducing the problem.

The problem is obviously happening due to the different ways of loading the initial HTML page from development to production:

`mainWindow.loadURL(isDev ? 'http://localhost:3000' : `file://${path.join(__dirname, 'build/index.html')}`);`

In development, its pointing to the local web page, but in production it's using the file:// schema which means all subsequent loads from the serviceworker will be using file://

**Screenshots**
![Image of Problem](https://i.imgur.com/bDuVVI2.png)

**Additional Information**
The application is based on React and Redux, using the create-react-app npm module. I have re-built the application from scratch today, trying one component at a time and as soon as I start linking to different components, this problem starts happening.

I have read various posts regarding using the webFrame.registerURLSchemeAsSecure('file') and have tried adding this to the index.html and in code in the rendered process, but it doesn't seem to have made much difference.

I understand the service-worker.js is used to cache various files, so I'm guessing there's some randomness going on in this matter which I'm not fully getting.

I'm not sure if it's related to #9705 but it sounds quite similar.

**Comment by Heiiji** [comment]
I have the same problem with Windows 10 Home and electron 2.0.9. The probleme appear when client is build  with electron-builder (on debug mode with a localhost, it's work fine)

**Comment by zhengxiaoyao0716** [comment]
I resolved it just by ignore the `file:` protol for the `register` function at `serviceWorker.js`:
``` javascript
export function register(config) {
  if (window.location.protocol === 'file:') {
    // `file:` should be ignored for some none-browser environment, such as `Electron`.
    return;
  }
  ...
}
```

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
