### ISSUE TITLE
event.sender.send doesn't send message back to render process

### ISSUE THREAD

**Issue by appskitchen** [electron/electron#13743]
* Electron Version: 2.0.5
* Operating System (Platform and Version):  macOS 10.13.3
* Last known working Electron version: 

**Expected Behavior**
I've a asynchronus renderer process which should be executed as I called/send message from main process.

**Actual behavior**
The renderer processes never called/executed.

**To Reproduce**
I've similar codes in main process - 
```
// In main process.
  const {ipcMain} = require('electron')
  ipcMain.on('asynchronous-message', (event, arg) => {
    console.log(arg) // it prints "ping"
    event.sender.send('asynchronous-reply', 'pong')
  })  
```
and following codes in renderer process - 
```
// In renderer process (web page).
  const {ipcRenderer} = require('electron')  
  ipcRenderer.on('asynchronous-reply', (event, arg) => {
    console.log(arg) // why it doesn't print "pong"?
  })
  ipcRenderer.send('asynchronous-message', 'ping')

```
But my 'asynchronous-reply' event in rendered never been executed, thus it prints ping, but it doesnt print pong. Any idea why? Is it a known bug? Appreciate any help.

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
