### ISSUE TITLE
macOS Mojave BrowserWindow.setProgressBar hard crash

### ISSUE THREAD

**Issue by Thomas101** [electron/electron#13751]
* Electron Version: 2.0.5
* Operating System (Platform and Version): macOS Mojave beta4

**Expected Behavior**
Call `browserWindow.setProgressBar(0.5)`, the app hard crashes citing an unrecognized selector. Doesn't happen on High Sierra

```
[_NSImageViewSimpleImageView setDoubleValue:]: unrecognized selector sent to instance 0x7fa6b7472040
```

**Actual behavior**
Don't  crash, set the progress bar

**To Reproduce**

Clone the repo and press the crash button...

```sh
git clone https://github.com/wavebox/electron-quick-start.git -b mojave_set_progressbar_crash
cd electron-quick-start
npm install
npm start
```

**Comment by fasterthanlime** [comment]
Seeing that too, here's a complete stack:

```

**Comment by fasterthanlime** [comment]
I've dug into the source / Apple docs a little, but I don't see the `doubleValue` property of NSProgressIndicator being deprecated anywhere..

It seems like what's actually being used is AtomProgressBar, which extends NSProgressIndicator, but does its own rendering.

if `doubleValue` was indeed deprecated, it would throw not only when setting progress, but also when drawing it.

Would it be possible to make AtomProgress extend some other NS type? I would try and submit a PR, but both my macbooks broke years ago, and I don't have a VM with Mojave yet :(

**Comment by ravibpatel** [comment]
Experiencing it too. After the update to Mojave it started crashing. It caused by setProgressBar function of BrowserWindow removing it seems to fix the issue.

**Comment by frank0r** [comment]
me too . encounterd this issue on client's computer

**Comment by ckerr** [comment]
https://github.com/electron/electron/issues/14008 appears to be a duplicate of this bug

**Comment by keybeejeebee** [comment]
I think this may have been addressed in the latest beta. I'm not experiencing the crash with apps I had issues with before, or the example provided by @Thomas101

**Comment by ravibpatel** [comment]
Same here. Not experiencing the crash now.

**Comment by Thomas101** [comment]
I can confirm it's fixed with the latest Mojave beta and Electron 2.0.9. Thanks for everyone's time.

**Comment by DeerMichel** [comment]
I built Electron myself and the `BrowserWindow.setProgressBar` test crashes under macOS Mojave (10.14.2). The API itself works (sets the progress bar properly) - however, the test case is faulty. I can reproduce the crash with Electron 4.0.0 as well as 4.0.0-nightly.20181010 (current master). It also says
```
[_NSImageViewSimpleImageView setDoubleValue:]: unrecognized selector sent to instance 0x7ff98b92d500
```

I think this problem only occurs with macOS Mojave. Can somebody on High Sierra confirm it by running the tests?
