### ISSUE TITLE
Electron builder with sqlite

### ISSUE THREAD

**Issue by sarada123** [electron/electron#13752]
* Electron Version:1.7.9
* Operating System (Platform and Version):windows7 /windows10
* Last known working Electron version: 

**Expected Behavior**
Hello everyone I build the installer with nsis ia32 arch, I use sqlite3 and everything works fine until the update is downloaded since it replaces all the files in the installation folder.
Then my database file is deleted, how can I prevent my database file from being deleted with the new versions?
**Actual behavior**
Updated version of installer is replacing all the files in the app which is old version 
A clear and concise description of what actually happened.

**To Reproduce**
Your best chance of getting this bug looked at quickly is to provide a REPOSITORY that can be cloned and run.

You can fork [electron-quick-start](https://github.com/electron/electron-quick-start) and include a link to the branch with your changes.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
I am generating the installer using electron-builder of version 19.47.1,using the command
electron-builder --platform=win32
```sh
$ git clone $YOUR_URL -b $BRANCH
$ npm install
$ npm start || electron .
```

**Comment by MarshallOfSound** [comment]
This appears to be a question about `electron-builder` not `electron` itself.  They are two separate projects maintained by different groups of people

**Comment by sarada123** [comment]
Then where can i get clarity on it..............?
:-(

**Comment by sarada123** [comment]
is there any seperate channel for this to discuss

**Comment by MarshallOfSound** [comment]
https://github.com/electron-userland/electron-builder

**Comment by sarada123** [comment]
I need a small clarification on how to create .nsh extension file for using macros
