### ISSUE TITLE
Mouse events inside webview(document) not propagates to parent element

### ISSUE THREAD

**Issue by SrSobrao** [electron/electron#13759]
* Electron Version: v3.0.0-beta.2
* Operating System (Platform and Version): Windows 10
* Last known working Electron version: v2.0.5

I have this code:

```
<div id="#parentWebView"><webview src="http://someurl.com"></webview></div><script>
$("#parentWebView")[0].addEventListener('mousedown', function(e){
console.log('event:', e);
});
</script>
```

**Expected Behavior**
Mousedown event inside webview propagates to parent element(In electron <= v2.0.5 works).

**Actual behavior**
Event doenst fire.

**Comment by codebytere** [comment]
Merging to https://github.com/electron/electron/issues/13503
