### ISSUE TITLE
No subpixel AA fonts rendered on Ubuntu Linux

### ISSUE THREAD

**Issue by burtonator** [electron/electron#13764]
* Electron Version: 3.0.0-beta.3
* Operating System Ubuntu 18.04
* Last known working Electron version: none  ... still fails on 2.0.5

**Expected Behavior**

Font Subpixel AA should work... only works when rendering a .HTML file, not via BrowserWindow.

**Actual behavior**

Subpixel AA only works when I load a .html file.. not a .js file.

**To Reproduce**

https://github.com/burtonator/electron3-fuzzy-text

Here is a repo.

This works:

```
./node_modules/.bin/electron test.html
```

This will fail:

```
./node_modules/.bin/electron index.js
```
The only way to actually see that it's failing is to use a zoom tool like ```kmag```

**Screenshots**

Here's loading the .html file on the command line. Notice the AA is working by the orange color on the outside of the text:

![image](https://user-images.githubusercontent.com/45447/43037663-8731acd2-8cc4-11e8-99bf-f2adfbfdecc4.png)

Here is the SAME text and same test.html file but I loaded it via BrowserWindow in my index.js script.

![image](https://user-images.githubusercontent.com/45447/43037676-a22fa30e-8cc4-11e8-8bee-4d20bdfde57f.png)

Electron fails to use AA text rendering in the new window.  

Hopefully this might help track down the bug.

**Comment by burtonator** [comment]
So whatever is different about loading from the command line and my code is causing the problem.  

I looked at all the browser window options and didn't see anything that would obviously fix the problem.

**Comment by burtonator** [comment]
AHA!!! this has an easy fix thanks to this bug!

https://github.com/electron/electron/issues/10025

I just need to use:

```
const BROWSER_OPTIONS = {
    backgroundColor: '#FFF',
};

new BrowserWindow(BROWSER_OPTIONS);
```

I think the documentation is wrong:

```
backgroundColor String (optional) - Window's background color as a hexadecimal value, like #66CD00 or #FFF or #80FFFFFF (alpha is supported). Default is #FFF (white).
```

... this is probably the best fix for this issue.  

I might submit a PR if this isn't fixed promptly.

**Comment by MarshallOfSound** [comment]
I think the default is actually "nothing" which appears white on most systems, I'm guessing explicitly setting it to white must trigger a different font rendering mode inside Chromium.  Maybe we should just explicitly default to `#fff`

**Comment by zcbenz** [comment]
I think this is a result of https://github.com/electron/electron/pull/11956.
