### ISSUE TITLE
Haiku OS Port of Electron

### ISSUE THREAD

**Issue by roired** [electron/electron#13762]
Hello,
I would like to see Electron ported to Haiku OS in order to get Electron based apps availabe, i.e. VSCode.

Thank you very much for taking your time with this "Feature Request".
Regards,
Roired

**Comment by miniak** [comment]
@roired Chromium and node.js do not support Haiku, therefore Electron cannot support it either.

**Comment by miniak** [comment]
Electron does not even have an official FreeBSD version https://github.com/electron/electron/issues/3797, which makes much more sense to support.

**Comment by kallisti5** [comment]
@miniak
> @roired Chromium and node.js do not support Haiku, therefore Electron cannot support it either.

Technically Haiku does have node.js.
```
/Data/Code> uname -a
Haiku shredder 1 hrev54839 Jan  4 2021 07:02:21 x86_64 x86_64 Haiku
/Data/Code> node --version
v12.3.1
```

We also have a webkit port used by our native browser.
Is Chromium a hard stop here?

**Comment by kallisti5** [comment]
Anyway, this is where trying to build Electron apps on Haiku generally ends up :-)
```
> electron@9.0.5 postinstall /Data/Code/hyperspace/node_modules/electron
> node install.js

/Data/Code/hyperspace/node_modules/electron/install.js:81
      throw new Error('Electron builds are not available on platform: ' + platform)
      ^

Error: Electron builds are not available on platform: haiku
    at getPlatformPath (/Data/Code/hyperspace/node_modules/electron/install.js:81:13)
    at Object.<anonymous> (/Data/Code/hyperspace/node_modules/electron/install.js:15:22)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by bluevisor** [comment]
Bump after 6 years, still hoping to see Electron ported to HaikuOS.
