### ISSUE TITLE
Cannot read property 'fn' of undefined

### ISSUE THREAD

**Issue by marcobraghim** [electron/electron#13766]
* Electron Version: ^2.0.5
* Operating System (Platform and Version): #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07)
* Last known working Electron version: I'm just testing electron now

**Expected Behavior**
Load bootstrap initial needed files

**Actual behavior**
Getting "Cannot read property 'fn' of undefined"

**To Reproduce**
On this test I'm just creating a total clear index html page. Just like quick start examples

**Additional Info**
In this link I got a workaround hack to make it work
https://stackoverflow.com/questions/32621988/electron-jquery-is-not-defined

**Screenshot**

In the left window you can see the application running under Electron with that fail message. In the right I'm loaded exactly same file but directly in the google chrome browser.

![captura de tela de 2018-07-21 21-36-56](https://user-images.githubusercontent.com/2068045/43041196-2109b6b4-8d2f-11e8-8f1b-75134b6ccc5a.png)

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).

**Comment by marcobraghim** [comment]
Thank you, I created it here because I thought it was an Electron problem at all... Sorry.

**Comment by coooliang** [comment]
> * Electron Version: ^2.0.5
> * Operating System (Platform and Version): #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07)
> * Last known working Electron version: I'm just testing electron now
> 
> **Expected Behavior**
> Load bootstrap initial needed files
> 
> **Actual behavior**
> Getting "Cannot read property 'fn' of undefined"
> 
> **To Reproduce**
> On this test I'm just creating a total clear index html page. Just like quick start examples
> 
> **Additional Info**
> In this link I got a workaround hack to make it work
> https://stackoverflow.com/questions/32621988/electron-jquery-is-not-defined
> 
> **Screenshot**
> 
> In the left window you can see the application running under Electron with that fail message. In the right I'm loaded exactly same file but directly in the google chrome browser.
> 
> ![captura de tela de 2018-07-21 21-36-56](https://user-images.githubusercontent.com/2068045/43041196-2109b6b4-8d2f-11e8-8f1b-75134b6ccc5a.png)

mainWindow = new BrowserWindow({
    width: 1600, 
    height: 1090,
    webPreferences: {
      nodeIntegration: false   
    }
  });

**Comment by coooliang** [comment]
`
mainWindow = new BrowserWindow({
    width: 1600, 
    height: 1090,
    webPreferences: {
      nodeIntegration: false   
    }
  });
`

**Comment by coooliang** [comment]
nodeIntegration: false   
`mainWindow = new BrowserWindow({
    width: 1600, 
    height: 1090,
    webPreferences: {
      nodeIntegration: false   
    }
  });`

**Comment by yuwade** [comment]
Do not do this
<script src="bootstrap.min.js" ></script> 
<link rel="stylesheet" href="bootstrap.min.css">

Should do this
$ npm install bootstrap
  <style>
    @import url('./node_modules/bootstrap/dist/css/bootstrap.min.css');
  </style>
  <script>
    require('bootstrap');
  </script>

**Comment by romuloteixeira** [comment]
Duplicated [https://github.com/ElectronNET/Electron.NET/issues/329#issuecomment-546612899](url)

**Comment by mlibre** [comment]
@yuwade improved answer:
`file.js`:
```javascript
$ = window.$ = window.jQuery = require("jquery");
require("@popperjs/core");
require("bootstrap");
```
`file.css`:
```css
@import url('../node_modules/bootstrap/dist/css/bootstrap.min.css');

body {
```
`npm`:
```bash
npm i @popperjs/core --save
npm install --save bootstrap
npm install --save jquery
```
