### ISSUE TITLE
abnormal scroll Electron 2.0

### ISSUE THREAD

**Issue by Slllava** [electron/electron#13763]
* Electron Version: 2.0.5
* Operating System (Platform and Version): mac os 10.12.6
* Last known working Electron version: 2.0.0

**Expected Behavior**
normal scroll!

**Actual behavior**
abnormal scroll!

**Screenshots**
![document 2018-07-21 18-19-01](https://user-images.githubusercontent.com/7153307/43037201-ad9da6ec-8d13-11e8-8d72-802af94ed69a.png)

**Comment by sofianguy** [comment]
Can you please provide us with steps to reproduce this issue?

**Comment by Slllava** [comment]
I install electron-quick-start and at once I see such problem.
after adding background in the body block, the problem disappears

**Comment by codebytere** [comment]
hi @Slllava, we'd love to help here but unless steps can be provided for us to reproduce this issue and we can get a clearer idea of what behavior you expect as opposed to what behavior you're experiencing, we'll have to close this issue.
