### ISSUE TITLE
Electron 2.0.5 - n-api experiemental feature?

### ISSUE THREAD

**Issue by kevinjiaxu96** [electron/electron#13775]
Getting the error N-API is an experimental feature, is there anyways to suppress this??  I though electron 2.0 has the version of node that removed that flag?

**Comment by miniak** [comment]
@kevinjiaxu96 According to https://nodejs.org/api/n-api.html#n_api_n_api_version_matrix, node v8.9.3 which is in Electron 2.0 only has experimental N-API support. Electron 3.0 with node v10.2.0 should have full support.
