### ISSUE TITLE
Electron API for setting default audio device

### ISSUE THREAD

**Issue by avner-hoffmann** [electron/electron#13771]
I was searching the Electron's docs and didn't find the answer to the following:
Does Electron have an API for setting and configuring the OS audio device (input/output)?

I'm looking for a way to set the default audio device output from the code of my Electron app.
If it's not possible through Electron's API, are there any packages that's doing it?

**Comment by MarshallOfSound** [comment]
There is a web platform JS API for this.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/setSinkId

**Comment by avner-hoffmann** [comment]
This is listed as an experimental technology
By your answer I assume Electron doesn't have an API for that matter?

**Comment by MarshallOfSound** [comment]
@avner-hoffmann Experimental, sure, but tonnes of web APIs are marked as experimental.  I actually use this API in my app to provide an audio output device selector.

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/82c84871163e0949172e6dde7550f6844fb88749/src/renderer/windows/GPMWebView/playback/audioSelection.js#L18

**Comment by whitmer** [comment]
Hi, I'm wondering if we can revisit this a little. I've been digging into the bowels of Windows SDKs but haven't found a satisfactory answer. I'd love to be able to change the audio output for my app at will, either at the app or OS level. Some of my audio is generated using audio elements as you mentioned, and could be routed that way, but some is generated using native libraries like the Windows Speech SDK using speech synthesis.

My app is a tool used by people with disabilities to generate speech or audio, and some users like to preview audio in their headphones before broadcasting it using the speaker. I haven't yet figured out a way to accommodate this in an Electron app, and the specified request fits in with what I'm trying to accomplish.

Thanks for your consideration!

**Comment by marcusand** [comment]
@whitmer I'm curious if you found a solution for that problem? I have a very similar requirement to what you describe: i wanna have speech synthesis play trough one output device and other audio trough a second output device.
Thanks!

**Comment by darpan-adhlakha** [comment]
For anyone reading this in future.

Use navigator.mediaDevices.enumerateDevices() to get a promise which will return list of devices, use deviceId property of the device and set sink for element (audio/video) by calling setSinkId() and passing the deviceId to it. 

Further, if you want to send it to isolated channels of speaker, you need to first create and AudioContext and set its destination to one created from createMediaStreamDestination, connect it via a StereoPannerNode and assign this to srcObject of your element Audio/Video then you can set sink and play.

**Comment by Imior** [comment]
For input audio device, specify the [MediaStreamConstraints](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamConstraints) in `MediaDevices.getUserMedia()`.

**Comment by marcelblum** [comment]
I'd like to echo @whitmer and request a native solution to this for Electron. The Chromium implementation of `setSinkId()` and the API path necessary to get there has longtime bugs (ex. https://bugs.chromium.org/p/chromium/issues/detail?id=1157478) and is quite a convoluted API, and brings a big latency hit which makes it borderline useless for any realtime audio situation such as a game or music creation app.

**Comment by Fiser12** [comment]
Maybe it's related to this old-reported issue. It's been on hold for years.

https://bugs.chromium.org/p/chromium/issues/detail?id=697877

Remember that for getting visibility on chromium, you should “Start" it with your Google account to help to the Chromium team to understand its importance.

**Comment by marcelblum** [comment]
Just wanted to note I've been using the Node addon [Audify](https://github.com/almoghamdani/audify) for output to non-default audio devices via an Audio Worklet (with `nodeIntegrationInWorker: true`) and it's working nicely so far. Bypasses all of the issues with `setSinkId()`.

**Comment by deevannaveed** [comment]
@MarshallOfSound `setSinkId` actually works but doing it for individual player is not convenient in some cases! it would be a lot easier if we could change the output audio of the whole app same as we can do with Chrome in the settings.
