### ISSUE TITLE
How to trigger the :visited link rendering?

### ISSUE THREAD

**Issue by ColacX** [electron/electron#13776]
This would require the browser to keep track of the navigation history.
How to trigger the :visited link rending of a link that has been previously visited?

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
