### ISSUE TITLE
Way to disable asar handling that isn't a hack?

### ISSUE THREAD

**Issue by TanninOne** [electron/electron#13781]
**Is your feature request related to a problem? Please describe.**
The application I'm working on, among other things, extracts archives, moves stuff around from the extracted archives, potentially removes it again afterwards.

Now the problem I'm facing is that the archive I've extracted contains an asar file, electron seems to automatically open the file and keeps a file handle on it, even though I have absolutely no interest in the content of the asar and never called openFile, readdir or anything on it. (This is on windows)
This then prevents the archive from being deleted.

**Describe the solution you'd like**
I want to disable asar handling in a controlled manner such that the asars, that are part of my application are still working but not any asar apart from that. So ideally there would be a white-list of asars that receive special treatment and every other asar should be a regular file unless I say something different. 

**Describe alternatives you've considered**
process.noasar is not an option. I don't think it's ever an option for any application because it's a global flag but fs operations are supposed to be asynchronous so if you look at the sample in https://github.com/electron/electron/pull/3641 , asar handling is disabled process-wide as long as the file is being extracted which may affect who-knows-what. process.noasar is a guaranteed race condition.

I considered using require('original-fs ') but since I use "fs-extra" via "fs-extra-promise" I'd have to rewrite a lot of functionality just to fix this.

I considered hooking into require to replace "fs" with "original-fs" in the require cache while I'm requiring "fs-extra-promise" or any other fs library, which would presumably be safe since require is synchronous, but it's a massive hack that I believe would fail when my application is webpack-ed.

**Comment by MarshallOfSound** [comment]
@TanninOne The solution for this is as you described, use the `original-fs` module.  If you are using an `fs` wrapper such as `fs-extra` you have three options

* You are using webpack, so you can use a resolutions plugin to tell webpack to resolve `fs` to `original-fs` if the require is coming from the `node_modules` directory
* You can hack the node require resolved to load `original-fs` if the parent module requesting it is in the `node_modules` directory
* Or the best thing to do is PR up to `fs-extra` to allow you to provide your own `fs` object somehow 👍 

We provide the `original-fs` module to solve this use case so you just have to figure out how to make `fs-extra` use it 😄

**Comment by TanninOne** [comment]
Sorry, but I don't feel like this is an sufficient solution or response.
There is no way for me to know what other libraries use fs somewhere under the hood and whether they are accessing the asars that are part of my application bundle. If I "replace" fs with original-fs through require resolve or webpack there is no telling how much other stuff it will break.
So this doesn't satisfy the condition "not a hack".

Also, as I mentioned: The asars from unpacked modules are opened with a file handle kept open in the background before I call a single fs function and I don't have the first clue what is doing it. Why is it doing that? What module is doing it? Will using original-fs fix it?
Setting the process.noAsar flag does avoid it bug again, that's a crappy solution.
