### ISSUE TITLE
webview navigation events

### ISSUE THREAD

**Issue by felicienfrancois** [electron/electron#1378]
It would be very useful to get events related to navigation:
- `will-navigate`: when the webview is about to navigate (url have been changed but no requests have been emited yet). It could eventually be cancelled with `event.preventDefault()`)
- `page-url-set`: like `page-title-set` but for url. It is different than `before-navigate` because it should also handle anchor changes and HTML5 url set without navigating (with `history.pushState` and `history.replaceState`)
- `did-navigate`: after the navigation has occured (i.e. when a new entry have been pushed to history and canGoBack/canGoForward/canGo... may have changed)

**Comment by Tribex** [comment]
:+1:  For this. :)

**Comment by steelbrain** [comment]
:+1: :heart:
another event `page-favicon-set` would be useful too.

**Comment by Tribex** [comment]
Much of this can be done in theory using a preload script, but those are known to be unruly. So far I have had little success using them reliably.

(This message written from my in-development atom-shell web-browser, which is a case-in-point for this issue)

**Comment by yyjhao** [comment]
It wil be even better if we can access the `webContents` of the `webview` tag - we can get all those events for free.

**Comment by Tribex** [comment]
@yyjhao, A combination of a preload script and ipc messaging can make accessing the document just as easy, though you generally have to wait for the DOMContentLoaded event before you can start using it.

**Comment by yyjhao** [comment]
How do you do something like this in the web view tag?

```
webContents.on('will-navigate', function(event, url) {
    if (isExternal(url)) {
        event.preventDefault();
        openInExternalPage(url);
    }
});
```

(given that the url can be changed by clicking a link or setting window.location)

**Comment by Tribex** [comment]
@yyjhao Hmm, good question, I can't think of a good way to do that.

**Comment by yyjhao** [comment]
Yeah things like that may not be necessary for all applications. But right now I wanna add some loading animations before the page is fully loaded to an online web app and it can't be done :(

**Comment by Tribex** [comment]
@yyjhao Actually, I spoke too soon. Here's a way you could do that:

Injection script:
```javascript
  window.onbeforeunload = function() {
      ipc.sendToHost('webview:beforenavigate', window.location.href);
  }
```

Webview:
```javascript
    webview.addEventListener('ipc-message', function(e) {
      } if(e.channel == "webview:beforenavigate") {
        webview.stop();
        openInExternalPage(e.args[0]); // Probably isn't the new URL, Not sure how to do that part yet.
      }
    });
```

**Comment by yyjhao** [comment]
I think this is a bit wonky - since ipc is asynchronous, `stop()` may be called after the navigation.

**Comment by Tribex** [comment]
@yyjhao I've tested it on several remote sites and they all work perfectly, so far (granted I have incredibly slow internet speed :P). However, on local sites it might be an issue.

**Comment by yyjhao** [comment]
Like I said, this is too hacky to be used in actual apps. A webContents API will be much neater.



—

**Comment by Tribex** [comment]
@yyjhao Yes, indeed.

**Comment by zcbenz** [comment]
I think we have all necessary events now.

**Comment by felicienfrancois** [comment]
Hi @zcbenz ,
did I missed something? Is there new events available but not yet documented?

**Comment by zcbenz** [comment]
Oops, I didn't notice this issue is about webview's events.

**Comment by felicienfrancois** [comment]
OK, thank you @zcbenz :)

**Comment by alexindigo** [comment]
+1 Better control over webview would allow new class of applications (similar to http://fluidapp.com for example).

**Comment by pfraze** [comment]
+1, would like to have these

**Comment by rhysd** [comment]
+1, I also want to catch `will-navigate` event in `<webview>` to open the link with external browser.

**Comment by armoret** [comment]
+1, it could be a possible way to forbid file downloads (well, it may depend on which information we can grab from the link target before preventing the event).

**Comment by lin-chao** [comment]
+1, catch will-navigate event in <webview> is useful.

**Comment by farnabaz** [comment]
+1

**Comment by TayNelson** [comment]
+1 for the same reason as @rhysd

**Comment by sickboy** [comment]
+1

**Comment by xywz** [comment]
+1, how much work will this take?

**Comment by jingweno** [comment]
+1

**Comment by steelbrain** [comment]
Now that `chrome.webRequest.*` APIs have now been supported, could we close this?

**Comment by felicienfrancois** [comment]
@steelbrain is there a way to catch only the "root" request (the one which change the url) with `webRequest API`?

**Comment by felicienfrancois** [comment]
@steelbrain in any case, navigation events concerns NAVIGATION and not request, which is different, especially with HTML5 javascript API:

- url can be set without making any request
- history can be changed without making any request
- anchor is part of the navigation, webRequest does not have access to it

**Comment by steelbrain** [comment]
@felicienfrancois There **could** be a way of catching only the root request but I haven't dug deep into the API docs yet to know. Anyways, the points that you made are very valid, I agree that this issue is different than that. Thanks for the clarification!

**Comment by xywz** [comment]
@zcbenz as a workaround would it be possible to get the `webContents` of a webview in the main process?

**Comment by ddxdental** [comment]
+1 for event.preventDefault() on will-navigate

**Comment by fasterthanlime** [comment]
> @zcbenz as a workaround would it be possible to get the webContents of a webview in the main process?

There's a getter that returns the associated webContents of a webview tag, and that webContents will also emit a will-navigate event, but calling `preventDefault` on that event will not prevent anything either.

From what I can gather in this thread, implementing that would be problematic because those events are dispatched asynchronously? And dispatching them synchronously would incur a performance penalty?

**Comment by tmpfs** [comment]
It appears the documentation is incorrect on this, from the [will-navigate](http://electron.atom.io/docs/api/web-contents/#event-will-navigate) docs it says:

> Calling event.preventDefault() will prevent the navigation.

This appears to not be the case as per the above comment and my tests, can somebody please update the docs, or if you prefer point me in the right direction to update the docs and I will issue a PR.

**Comment by kasrak** [comment]
preventDefault() to prevent navigation on will-navigate would definitely be useful.

As a possible workaround, is there a way to intercept and cancel navigation events from within the webview page (since it's in the same process)?

**Comment by felicienfrancois** [comment]
@kasrak there is no reliable workaround.
Depending on your case, you can:
- use [beforeunload](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload) event (but it may not catch all navigation and it can be overrided by the web page).
- wrap `window.location` and `window.history` with a watcher (but you won't be able to catch navigation with links or `webview.loadUrl`)

**Comment by felicienfrancois** [comment]
@tmpfs it have been fixed in master branch https://github.com/electron/electron/blob/master/docs/api/web-view-tag.md#event-will-navigate

**Comment by alexindigo** [comment]
I'm wondering what prevents this kind of functionality to be built,
seems like it's a wide-spread problem and this issue is more than a year old.

**Comment by felicienfrancois** [comment]
@tmpfs the [webview documentation](http://electron.atom.io/docs/api/web-view-tag/#event-will-navigate).
You're pointing to the webContents doc. If you think the webContents doc is wrong you can [edit this file](https://github.com/electron/electron/blob/master/docs/api/web-contents.md) and make a PR

**Comment by fasterthanlime** [comment]
The webContents documentation is wrong in the sense that:

  * You can get a webContents that 'corresponds to' a webview
  * preventDefault will *NOT* work there.

It's mentioned in the webview doc, but should also be mentioned in the webContents doc ("If you've obtained the webContents from a webview then the following caveats apply: ") - or even better, preventDefault could be implemented in webview's will-navigate :)

**Comment by alexindigo** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=10652270)](https://www.bountysource.com/issues/10652270-webview-navigation-events)

**Comment by kunkinkan** [comment]
How do I prevent any and all navigation (except my own page). Perhaps it should simply be an option in the loadURL() method. Because that is the main reason people use the event for (wanting to open it in a real browser window).

**Comment by fdn** [comment]
This workaround seems to be, ahem, working for me.
`
webview.addEventListener('will-navigate', function(event) {
  webview.stop();
  console.log('Navigating to', event.url);
  // TODO: handle the url
});
`

**Comment by atypicalprogrammer** [comment]
@fdn that doesn't work.

**Comment by alexindigo** [comment]
I'm thinking if I pass everything through in-node proxy, and will killing requests on the proxy level, need to play with it to see how it can handle https requests.

**Comment by xywz** [comment]
# polyfill
## window.js
```javascript
// part of polyfill for preventable 'will-navigate' for webviews
// https://github.com/electron/electron/issues/1378
// add webview listeners within window.addEventListener('load', ...) and add at least one
document.addEventListener('DOMContentLoaded', () => {
  const {addEventListener, removeEventListener} = WebView.prototype
  const webviews = new WeakMap()

  WebView.prototype.addEventListener = function (type, listener) {
    if (!webviews.has(this)) {
      const willNavigateListeners = new Set()
      webviews.set(this, willNavigateListeners)

      addEventListener.call(this, 'will-navigate', (event) => {
        let defaultPrevented = false

        const newEventProperties = {
          cancelable: true,
          preventDefault () {
            defaultPrevented = true
          },
          get defaultPrevented () {
            return defaultPrevented
          }
        }

        const eventProxy = new Proxy(event, {
          get (event, property) {
            return newEventProperties[property] === undefined ? event[property] : newEventProperties[property]
          }
        })

        for (const listener of willNavigateListeners) {
          listener(eventProxy)
        }

        if (!defaultPrevented) {
          this.src = event.url
        }
      })
    }

    if (type === 'will-navigate') {
      if (typeof listener !== 'function') {
        throw new TypeError('Expected listener to be function')
      }

      webviews.get(this).add(listener)
    } else {
      addEventListener.call(this, type, listener)
    }
  }

  WebView.prototype.removeEventListener = function (type, listener) {
    if (type === 'will-navigate') {
      if (typeof listener !== 'function') {
        throw new TypeError('Expected listener to be function')
      }

      webviews.get(this).delete(listener)
    } else {
      removeEventListener.call(this, type, listener)
    }
  }
})
```
## main.js
```javascript
const {app} = require('electron')

// part of polyfill for preventable 'will-navigate' for webviews
// https://github.com/electron/electron/issues/1378
app.on('web-contents-created', (event, webContents) => {
  if (webContents.hostWebContents) {
    webContents.on('will-navigate', (event) => {
      event.preventDefault()
    })
  }
})
```

**Comment by xywz** [comment]
@alexindigo good enough?

**Comment by cordosvictor** [comment]
The event is emitted by webContents:

mainWindow.webContents.on('will-navigate', ev => {
  ev.preventDefault()
})

**Comment by lukeapage** [comment]
@cordosvictor this issue is about web views, not normal web contents.

Can anyone confirm if @xywz's polyfill works? it seems very strange - it proxies the will-navigate and stops it from happening, but is that really how electron works? that electron relies on listening to its own will-navigate event and calling `this.src = event.url` ?

Does anyone know why this wasn't put in, in the first place? Is it a difficult fix?

**Comment by mkinawy** [comment]
this works for me for preventing navigation via user clicking on links and notifying the app about the requested url. Using preload and injecting this:
```
document.addEventListener('DOMContentLoaded', function () {
  document.addEventListener('click', function (e) {
    e.preventDefault();
    e.stopPropagation();
    setTimeout(function () {
      var path =e.target.href;
      ipcRenderer.sendToHost('element-clicked', path);
    }, 100);
    return false;
  }, true);
});
```
please note the 3rd param at the `document.addEventListener('click', fn, true)`

**Comment by alexindigo** [comment]
@xywz @mkinawy Thank you for the hacks, it's very nice that you can come up with cleaver ways to game the game, but it's fragile until it's part of public native API.

@zcbenz @kevinsawicki is there any light in the end of the tunnel for this? Thank you.

**Comment by dualface** [comment]
I tested @fdn code, worked for me:

```javascript
const {shell} = require('electron');
const url = require('url');

const _openInExternal = function(link) {
    let protocol = url.parse(link).protocol;
    if (protocol === 'http:' || protocol === 'https:') {
        shell.openExternal(link);
        return true;
    } else {
        return false;
    }
}

webview.addEventListener('will-navigate', (e) => {
    if (_openInExternal(e.url)) {
        webview.stop();
    }
});
```

**Comment by kevinsawicki** [comment]
> is there any light in the end of the tunnel for this? Thank you.

Supporting this from the `<webview>` element API is probably not feasible. `will-navigate` is a main process event that is fired on the `webContents` object. To enable it there would need to be a mechanism to do IPC events synchronously from the main process to a render process so that cancel could be properly handled.

Is there something preventing this from being managed by applications in the main process? For the use case of opening links externally, would the following not work?

```js
app.on('web-contents-created', (event, contents) => {
  if (contents.getType() == 'webview') {
    contents.on('will-navigate', (event, url) => {
      event.preventDefault()
      shell.openExternal(url)
    })
  }
})
```

**Comment by 2yuri** [comment]
@kevinsawicki very thanks!

**Comment by ios122** [comment]
I give a solution for someone who cannot access to the main process, for example,maybe you try to write a Atom Editor Plugin.
Thanks all,my solution combine "window.onbeforeunload" and  webview tag 's will-navigate event.
It makes the "will-navigate" event on webview works synchronously.

*main.js* means the plugin or you make the webview tag, and *preload.js* means the script preload to the webview:

## main.js

```js 
  let webview = document.createElement("webview");

 webview.preload = "./preload.js";

webview.addEventListener('dom-ready', () => {
      webview.send('patchToCloud');
      webview.openDevTools();

      /* 禁用跳转. */
      webview.send("enable-jump",false);
    });

    webview.addEventListener('will-navigate', ({url}) => {
      /* 处理跳转. */
      console.log("original url:" + webview.src);
      console.log("target url:" + url);

      /* 可以跳转到一个新的界面. */
      webview.src = "http://www.apicloud.com";
      // webview.src = url;

      /* 如果不跳转,需要显式再一次禁用跳转,以便于下一次能继续正确处理跳转. */
      // webview.send("enable-jump",false);
    });
```

## preload.js

```js
  const {ipcRenderer} = require('electron');

  ipcRenderer.on('enable-jump', (event,enable)=>{
    console.log(enable);

    if (enable) { // 允许跳转.
      window.onbeforeunload = undefined;
    }else{
      window.onbeforeunload = ()=>{
             /* 因为ipc是异步的,所以此处必须提前取消 onbeforeunload 监听,
              否则有极大概率无法在 webview 监听的 will-navigate 事件里进行跳转.
             */
             window.onbeforeunload = undefined;
             return 'will navigate...';
         };
    }
  });
```

**Comment by kevinsawicki** [comment]
I'm going to close this issue out since Electron now has the events mentioned and the `will-navigate` issue has been discussed and documented how it should be done and why.

Please open new issues for any additional missing events or bugs with `will-navigate`.

**Comment by mhuggins** [comment]
This issue was closed, but it's not clear to me from the comments what the solution is for the original issue, which is not being able to prevent navigation in webviews.  It looks like @kevinsawicki's [comment](https://github.com/electron/electron/issues/1378#issuecomment-265207386) might be a solution, but it reads more like it's a suggested change to electron than a workaround for how to make it work at present.

Am I understanding in/correctly?  Can I use that code to highjack & prevent webview navigation?

**Comment by jdclarke5** [comment]
If anybody is looking for a quick and dirty solution, you can always turn off all the `<a href="xxx">` links with some javascript:
```
webview.addEventListener("dom-ready", function() {
  webview.executeJavaScript(`
    var links = document.querySelectorAll("a[href]");
    for (var i=0; i < links.length; i++) {
      console.log(links[i]);
      links[i].href = "";
    }
  `);
});
```
Fully aware that this is not a general solution, but this might suffice for some.

**Comment by 0x13R** [comment]
This work for me.

Main Process:
```js
   const disable_external_navigate = (event, url) => {
      if(LinkUtil.isExternal(event.sender.getURL(), url)) {
        event.preventDefault();
      }
    }

   ipc.on('webview-disable-external-navigate', (event, enabled) => {
      if(enabled){
        event.sender.on('will-navigate', disable_external_navigate)
      } else {
        event.sender.removeListener('will-navigate', disable_external_navigate)
      }
    })
```
Webview preload:
```js
document.addEventListener('DOMContentLoaded', () => {
  ipcRenderer.send('webview-disable-external-navigate', true);
});
window.onbeforeunload = function() {
      ipcRenderer.send('webview-disable-external-navigate', false);
  }
```

**Comment by reneklacan** [comment]
Following code has only worked for me on Electron 2.0.5:

```js
// within renderer.js

const { shell } = require('electron');

const webview = document.querySelector('webview');

webview.addEventListener('will-navigate', (e) => {
  if (isExternalUrl(e.url)) {
    e.preventDefault();
    webview.stop();
    webview.getWebContents().stop();
    shell.openExternal(e.url);
  }
});
```

If I left any of three calls (prevent, stop, stop) first click would still open the external browser without navigating but any subsequent clicks would both open the external browser and navigate to external link within the webview.

**Comment by nathanhleung** [comment]
Here was my solution:

1. Hook into the `new_window` event and open all links that are set to open in a new window in an external browser:
```js
        webview.addEventListener('new-window', (e) => {
            e.preventDefault();
            const { protocol } = parse(e.url);
            if (protocol.indexOf('http') === 0) {
                shell.openExternal(e.url);
            }
        });
```

2. Make all links open in a new window:
```js
        webview.addEventListener("dom-ready", function() {
            webview.executeJavaScript(`
                    const links = document.querySelectorAll("a[href]");
                    for (let i = 0; i < links.length; i += 1) {
                      links[i].setAttribute("target", "_blank");
                    }
          `);
        });
```

**Comment by Levente0xFFFF** [comment]
> 
> 
> This issue was closed, but it's not clear to me from the comments what the solution is for the original issue, which is not being able to prevent navigation in webviews. It looks like @kevinsawicki's [comment](https://github.com/electron/electron/issues/1378#issuecomment-265207386) might be a solution, but it reads more like it's a suggested change to electron than a recommendation for how it could work at present.
> 
> Am I understanding in/correctly? Can I use that code to highjack & prevent webview navigation?

It is a simple and working solution. You can use it, yes, just try it. It works with Electron 2.0.16 as far as I can tell.

**Comment by nickredmark** [comment]
For the lonely googler:

>     * `page-url-set`: like `page-title-set` but for url. It is different than `before-navigate` because it should also handle anchor changes and HTML5 url set without navigating (with `history.pushState` and `history.replaceState`)

`page-url-set` does not exist. The event you are looking for is `did-navigate-in-page`

https://www.electronjs.org/docs/api/webview-tag#event-did-navigate-in-page
