### ISSUE TITLE
Notification (+115 more) APIs aren't defined synchronously in preload scripts

### ISSUE THREAD

**Issue by jakobvogel** [electron/electron#13787]
* Electron Version: 3.0.0-beta.3
* Operating System (Platform and Version): macOS 10.13.6
* Last known working Electron version: 2.0.5

**Expected Behavior**
While launching the app, a notification should be triggered via the preload script of the `BrowserWindow`.

**Actual behavior**
An error is reported on the console: `ReferenceError: Notification is not defined`

**To Reproduce**
```sh
$ git clone https://github.com/jakobvogel/electron-quick-start -b preload-notifications-3beta
$ npm install
$ npm start || electron .
```

**Screenshots**
_Working (2.0.5)_
![screen shot 2018-07-24 at 15 02 37](https://user-images.githubusercontent.com/36069303/43140449-4e8ee5a6-8f54-11e8-98ac-23ed5fd30def.png)

_Not Working (3.0.0-beta.3)_
![screen shot 2018-07-24 at 15 00 56](https://user-images.githubusercontent.com/36069303/43140839-d541a8ae-8f54-11e8-8616-ada163de44e6.png)

**Additional Information**
General HTML5 Notification support was already discussed in #13620 and fixed.

**Comment by javan** [comment]
I noticed this too. The `Notification` API *is* available in preload scripts, but not synchronously like it was previously.

```js
// preload.js

check()
process.nextTick(check)
setTimeout(check)

function check() {
  console.log(performance.now(), window.Notification)
}
```
<img width="375" alt="screen shot 2018-08-07 at 6 15 20 am" src="https://user-images.githubusercontent.com/5355/43770095-5cf54422-9a09-11e8-8d21-0645cd9547e1.png">

**Comment by javan** [comment]
It looks like this applies to far more than the `Notification` API.
```js
// preload.js

function getGlobalNames() {
  return Object.getOwnPropertyNames(global).filter(key => typeof global[key] == "function").sort()
}

const globalsSync = getGlobalNames()

setTimeout(() => {
  const globalsAsync = getGlobalNames()
  const newGlobals = globalsAsync.filter(name => !globalsSync.includes(name))

  console.log(`sync: ${globalsSync.length}`)
  console.log(`async: ${globalsAsync.length}`)
  console.log(`async only (${newGlobals.length}): ${newGlobals.join(", ")}`)
})
```

**Electron 3.0.0-beta.5**
<img width="797" alt="screen shot 2018-08-15 at 10 11 22 am" src="https://user-images.githubusercontent.com/5355/44152605-f5112328-a073-11e8-8d87-cd6bf474767f.png">

**Electron 2.0.7**
<img width="796" alt="screen shot 2018-08-15 at 10 12 43 am" src="https://user-images.githubusercontent.com/5355/44152670-1f2efb4e-a074-11e8-9372-9045a3e57171.png">

**Comment by jakobvogel** [comment]
@javan ... thanks a lot for your work! The `setTimeout` trick does the job, at least for now. 👍

**Comment by ckerr** [comment]
This broke in the bump to Chromium 66 @ bcbcb4c64
