### ISSUE TITLE
Electron ignoring client cert uploaded via nodejs

### ISSUE THREAD

**Issue by lagardp** [electron/electron#13795]
* Electron Version:2.0.4
* Operating System (Platform and Version):Windows 7
* Last known working Electron version: 

**Expected Behavior**
I am sending an HTTPS POST request to a REST API that requires a client cert for authentication using node's https module. I am reading a .pfx certificate from the file system when sending the request. When i run this OUTSIDE of electron everything work as expected. 
I would expect this to work when running the same code inside an Electron app.

**Actual behavior**
Electron ignores the .pfx cert that i would like to use and instead takes the first valid certificate in the OS cert store. If there is no cert installed on the OS then i receive the following error...even though i have uploaded my own cert.
Is there a way to force Electron to accept my cert and not search the cert store?
`<html>
<head><title>400 No required SSL certificate was sent</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<center>No required SSL certificate was sent</center>
<hr><center>nginx</center>
</body>
</html>
`

**To Reproduce**
Here is the code that sends the request. Again it works well using just node but the same code inside an Electron app does not.

`
const https = require('https');
const fs = require('fs');
const querystring = require('querystring');
		

        var postData = querystring.stringify({test:"test"});
            var options = {
                host: 'XXXXXXX',
                port:443,
                method: 'GET',
                path: 'XXXXXXX',
                headers: {
                    'Content-Type': 'application/json',
                    'Content-Length': postData.length
                },
                agent: false,
                pfx: fs.readFileSync('BTGTESTCERT4_1936115543.pfx'),
				passphrase: 'XXXXXXX'				
            };

            var req = https.request(options, function (res) {
                var result = '';
                res.on('data', function (chunk) {
                    result += chunk;
                });
                res.on('end', function () {
                    console.log(result);
                });
                res.on('error', function (err) {
                    console.log(err);
                })
            });

            req.on('error', function (err) {
                console.log(err);
            });
            req.write(postData);
            req.end();`

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
