### ISSUE TITLE
Electron will have a blank screen wait time when jumping over multiple pages

### ISSUE THREAD

**Issue by 18655173391** [electron/electron#13796]
My app is composed of multiple pages, and there always has about 0.5s to wait when pages  jump to each other,and when I was debugging, I found that the file of electron_compile.js is  loaded every time when pages initialized. Could I specify other pages without loading this  js?

@weolar 

electron ^2.0.5

**Comment by Mikerr1111** [comment]
A screenshot would be helpful.

**Comment by 18655173391** [comment]
![tim 20180725152413](https://user-images.githubusercontent.com/18301727/43185608-f6750302-901e-11e8-8d0c-37006b23b7b5.png)
![tim 20180725152335](https://user-images.githubusercontent.com/18301727/43185579-e5ab4f7c-901e-11e8-8387-ac0f6fa41185.png)
This happens when I jump from another webpage.@Mikerr1111

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
