### ISSUE TITLE
problem about using flash width flowplayer.js  in two  Electron  windows?

### ISSUE THREAD

**Issue by shadowBen** [electron/electron#13817]
The situation is when I followed the https://github.com/electron/electron/blob/master/docs/tutorial/using-pepper-flash-plugin.md  guide to mkae electron support flash using swf files.  It seams that it worked in main.js when I create the first window and I do see the flash player play a rtmp video stream .  But this was not worked when I try the same by new a BrowserWindow in the render process like
`const BrowserWindow = require('electron').remote.BrowserWindow
window.open_webapp = function(self,e){
    let win = new BrowserWindow({ 
    	useContentSize: true,
    	webSecurity: false,
    	plugins: true
    })
	win.on('close', function () { win = null })
	let modalPath = "";
	if(self.url.indexOf('http://')==0 || self.url.indexOf('https://') == 0){
		modalPath = self.url;
	}else{
		modalPath = path.join('file://', __dirname, self.url)
	}
	console.log(modalPath)
	win.loadURL(modalPath)
	win.webContents.openDevTools()
	win.once('ready-to-show', () => {
	    win.show()
  	})
}`
In this window the flash player cannot load 

I checked  navigator.plugins and both windows has Shockwave Flash plugin
I checked the swf files and in main window which flash worked well the swf files is corret got from the server, however the second window cannot got those swf files

is this a bug that the `app.commandLine.appendSwitch('ppapi-flash-path', path.join(__dirname, pluginName))` just useful  for the app procee but not a new process？
or is it needed to do the settings repeatly before open a window?
hopes for someones' ! thank you.

**Comment by sofianguy** [comment]
Which electron version and operating system are you using?

**Comment by shadowBen** [comment]
win10 x64  and the electron version is v2.0.4

**Comment by 18124772589** [comment]
同样的问题

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by shadowBen** [comment]
This worked on Electron V4.2
