### ISSUE TITLE
Event loop processes network events after breakpoint is hit

### ISSUE THREAD

**Issue by chrmarti** [electron/electron#13819]
* Electron Version: 2.0.2
* Operating System (Platform and Version): Mac High Sierra 10.13.6
* Last known working Electron version: -

**Expected Behavior**
Hitting a breakpoint in the dev tools should pause execution without side-effect. It should not lead to results that violate the JavaScript's "run to completion" behavior.

**Actual behavior**
In the example: Hitting a breakpoint on the second of two console.logs allows messages from the network being processed (including other console.logs) resulting in behavior otherwise not possible.

**To Reproduce**

- Start electron-fiddle with Electron 2.0.2 and this renderer code:
```js
const path = require('path');
const os = require('os');
const net = require('net');

const ipcPath = path.join(os.tmpdir(), `ipc-handle.tmp.${Math.random()}.sock`);

let count = 0;

const server = net.createServer(socket => {
	socket.on('data', data => {
		socket.write('response');
		socket.end();
		console.log('response sent', count++);
	});
});
server.listen(ipcPath);

const client = net.createConnection(ipcPath);
client.on('data', data => {
	console.log('response received', count++);
});

client.write('request');
console.log('request sent', count++);
console.log('goodbye', count++);
```
- Run and open dev tools.
- Place a breakpoint on the last line logging 'goodbye'.
- Reload and observe that after 'request sent' was logged the breakpoint was hit, the other console.logs still executed which is unexpected.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
