### ISSUE TITLE
desktopCapturer.js conversion error on getSources

### ISSUE THREAD

**Issue by PerfectionVR** [electron/electron#13816]
* Electron Version: 1.7.11
* Operating System (Platform and Version): Windows 10
* Last known working Electron version: N/A

**Expected Behavior**
Handle exception appropriately when example is run.

**Actual behavior**
Crashes and closes the application when example is run.

**To Reproduce**

```
var thumbSize = {
   width: 2560.5,
   height: 1440,
};
var options = { types: ['screen'], thumbnailSize: thumbSize };
// get media sources, which results in conversion error that crashes electron
desktopCapturer.getSources(options, function(error, sources) {});
```

**Additional Information**
We currently solve it with the following, though getting sub pixels is very rare if not a unique case.
```
var thumbSize = {
   width: Math.floor(maxWidthDimension * window.devicePixelRatio),
   height: Math.floor(maxHeightDimension * window.devicePixelRatio),
};
```

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.
