### ISSUE TITLE
tray.popUpContextMenu blocks javascript main thread on mac

### ISSUE THREAD

**Issue by pjebs** [electron/electron#13820]
* Electron Version: latest
* Operating System (Platform and Version): mac
* Last known working Electron version: n/a

**Expected Behavior**
When the tray icon menu is popped up manually (but on a tray click event callback), I expect the menu to open up but not necessarily block the main process.

**Actual behavior**
It blocks the main process until the menu is closed. This is creating issues with other timers etc that I have running on the main process.

**Comment by pjebs** [comment]
An asyn version would be great

**Comment by pjebs** [comment]
I think it's related to https://github.com/electron/electron/issues/1854 but my issue has nothing to do with render process.

**Comment by pjebs** [comment]
would this be hard to implement for tray: https://github.com/electron/electron/pull/8702

**Comment by pjebs** [comment]
@kevinsawicki

**Comment by pjebs** [comment]
Try `popUpContextMenu` on a `tray click event callback`

**Comment by ckerr** [comment]
if one of y'all could make a fork of https://github.com/electron/electron-quick-start that repros this, that would be great. I like @fantasticsid's approach of using a simple timer to display whether or not something's blocked!

**Comment by pjebs** [comment]
```
const {app, Menu, Tray, BrowserWindow } = require('electron')

let tray = null
app.on('ready', () => {
    tray = new Tray("/Users/pj/Developer/eyecumber/desktop-app/app/assets/img/tray/trayTemplate.png")
    const contextMenu = Menu.buildFromTemplate([
        {label: 'Item1', type: 'radio'},
        {label: 'Item2', type: 'radio'},
        {label: 'Item3', type: 'radio', checked: true},
        {label: 'Item4', type: 'radio'}
    ])

     tray.on('click', () => {
      console.log("A")
    tray.popUpContextMenu(contextMenu)

    console.log("B")
  })

    let win = new BrowserWindow();
    win.loadURL('https://www.youtube.com');

    setInterval(() => { console.log('test'); }, 1000);
})
```

`console.log('b')` is not printed out after menu is closed.

**Comment by pjebs** [comment]
For my project, the timers stop running but in the example above the timer works in the main thread. I can't explain that..... but the `popupContextMenu( )` is still synchronous

**Comment by pjebs** [comment]
@ckerr If I need to find a freelancer to fix this bug, what skills should they have? Should I require them to be skilled in `Objective-C++` or `Objective-C`? I don't have a windows machine. Does this bug exist in Windows? If so, what skills should they have for windows? Is it `C#`?

**Comment by ckerr** [comment]
Not a huge surprise, but for the record: I'm able to reproduce this in Ubuntu 18.10 running gnome-shell 3.30.1 with appindicators turned on.

**Comment by ckerr** [comment]
Disregard that. Revised comment: I'm an idiot.

**Comment by pjebs** [comment]
Has this been fixed for Electron 5?

**Comment by codebytere** [comment]
@pjebs no, but i've just jumped up a PR for it so i'll plan to backport it to all supported release lines :)

**Comment by pjebs** [comment]
@codebytere Can you take a look at https://github.com/electron/electron/issues/14036 this again.
I don't believe it's been fixed. In fact, you can use the official electron sampler to see the application crash: https://github.com/electron/electron-api-demos/blob/2a8c1f46b582b2762c2cf0afc7559082726255b5/main-process/native-ui/tray/tray.js#L23

**Comment by pjebs** [comment]
@miniak The vaguely related issue of #14036 is not fixed.
