### ISSUE TITLE
Wrong menu localization when pressing alt-key on macOS

### ISSUE THREAD

**Issue by davidka** [electron/electron#13833]
* Electron Version: 2.0.5
* Operating System (Platform and Version): macOS 10.13.6

When the electron's built-in roles (e.g. minimize) are used with a non-English system language, the labels of the generated menu items are in English.
If you now press the alt-key while the menu is open, some of the menu items are switched to another function and the labels are suddenly in the language of the operating system.

Window menu without pressing the alt-key:
![bildschirmfoto 2018-07-27 um 15 58 09](https://user-images.githubusercontent.com/1681446/43325043-f36bc5ea-91b5-11e8-9d90-d50f440ee060.png)

Window menu while pressing the alt-key:
![bildschirmfoto 2018-07-27 um 15 58 23](https://user-images.githubusercontent.com/1681446/43325044-f387ac6a-91b5-11e8-9b78-54c361e163dd.png)

**Comment by davidka** [comment]
I'm using a non localized (leads to english) menu on macOS which is in german.

To reproduce you can just use [electron/electron-quick-start](https://github.com/electron/electron-quick-start). The error also occurs there.

The current behavior is, that the menu is gonna translated into german (or whatever language macOS currently has) when pressing the alt-key: 

![ohne titel](https://user-images.githubusercontent.com/1681446/43397686-fde87732-9405-11e8-99b7-03a7fd4bd509.gif)

The expected behavior would be, that the menu stays in english:

![untitled](https://user-images.githubusercontent.com/1681446/43397714-13b82684-9406-11e8-87fa-606783776e71.gif)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
