### ISSUE TITLE
Reset the selected client certificate

### ISSUE THREAD

**Issue by lagardp** [electron/electron#13830]
* Electron Version: 2.x
* Operating System (Platform and Version): Windows 7 x64 
* Last known working Electron version: 2.0.1

**Expected Behavior**
Right, isn't a bug, but more like a question.

I know the app.js is a EventEmitter https://github.com/electron/electron/blob/master/lib/browser/api/app.js  object but I've tried to remove the eventListener and add again to the context of the app.

Problem is, I want to select another certificate and the app context keep the cache of the previous selection.

I basically tried:

- Reset the window
- Reset the context of the app
- Remove the eventListener and add again, sort of work, but doesn't dispatch again in the callBack.

Any hacks to make that work otherwise I will have to manually change the code and recompile another version of Electron, which requires time and at the moment is a luxury.
[Update]

I found in the docs this link https://electronjs.org/docs/api/session#sesclearauthcacheoptions-callback

But I'm not sure how to call from the main process.

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
