### ISSUE TITLE
ES6 modules not supported from filesystem.

### ISSUE THREAD

**Issue by burtonator** [electron/electron#13837]
If you try to load an ES6 module from filesystem on Electron  you get:

"Strict MIME type checking is enforced for module scripts per HTML spec."

I tested with 3.0.0beta3 ... didn't fix the problem.

It would be REALLY nice to not have this artificial barrier.  

Many people are shipping ES6 modules that are being webpacked but we shouldn't have to require this .

**Comment by timfish** [comment]
This is already tracked at #13483.
