### ISSUE TITLE
`shell.openExternal` fails silently if protocol is omitted

### ISSUE THREAD

**Issue by philippefutureboy** [electron/electron#13842]
* **Electron Version:** 2.0.2
* **Operating System (Platform and Version):** MacOS High Sierra 10.13.5
* **Last known working Electron version:** N/A

**Expected Behavior**
If protocol is omitted, `shell.openExternal` should either throw or assume http as default protocol.

**Actual behavior**
`shell.openExternal` does not open any external application if protocol is omitted. It fails silently, doesn't print anything to the console nor throws an error.

**Additional Information**
Since this is minor, I simply suggest to update the [documentation](https://github.com/electron/electron/blob/master/docs/api/shell.md) to make it clear that the protocol is required for the method to work. I volunteer to do a PR.

**Comment by MarshallOfSound** [comment]
@philippefutureboy The `shell.openExternal` method currently returns a boolean value indicating the success of the operation.  If you provide an invalid URL the method returns `false` indicating the system failed to launch the URL in any application (because it isn't a valid URL).

**Comment by raphaelschaad** [comment]
This method now doesn't return a boolean anymore but rather a promise indicating success or failure.

**Comment by rfox12** [comment]
Worth noting that (with Ubuntu, xdg-open) the promise will *not* reject if the protocol is unregistered with xdg-open.  This means if you're running Electron as root (edge case), then it's likely for most users that browsers will never get opened (they aren't setup for root by default).  And there will be no way to determine this via the API.  How do other platforms handle failure to open an external URL?

Would be nice to know if xdg-open failed with a non-zero exit code (on the command line I get exit code 3 for no appropriate tool found)

Easy fix?  Or do I have any other alternatives to open up an external URL for the user?

**Comment by rfox12** [comment]
So unless I'm wrong, there is still a "fails silently" issue with any platform that uses xdg-open...?  Can someone confirm?  Try running your electron app with sudo...

**Comment by nornagon** [comment]
Ideally we would pass along status results that are returned from xdg-open! Would you mind opening a new issue with a repro that exhibits the issue, ideally using [Electron Fiddle](/electron/fiddle)? Thanks!
