### ISSUE TITLE
window.close() on Webviews

### ISSUE THREAD

**Issue by saenzramiro** [electron/electron#13843]
* Electron Version: 1.8.7/2.0.0
* Operating System (Platform and Version): Windows 10
* Last known working Electron version: Don't know

**Expected Behavior**
Keep the webview available to interact.

**Actual behavior**
Every time the webview execute `window.close()`, it's crashing the webview itself.

**To Reproduce**
```sh
$ git clone https://github.com/saenzramiro/electron-window-close-bug.git
$ npm install
$ npm start || electron .
```

**Additional Information**
I realized this because of Slack's. Every time you log in or log out, they redirect to a page that executes `window.close()`. I searched of this here but no luck, sorry if this is duplicated.

**Comment by ckerr** [comment]
happening in `master` as well

**Comment by saenzramiro** [comment]
Until the Electron team fix this, is there a temporal workaround to prevent this bug?

**Comment by saenzramiro** [comment]
@ckerr Should we close this ticket since the new versions and your blog post you forgot to mention me😭?
