### ISSUE TITLE
navigateOnDragDrop default (and explicitly passing false) are not honored

### ISSUE THREAD

**Issue by Slapbox** [electron/electron#13854]
* Electron Version: 2.0.4
* Operating System (Platform and Version): OS X 10.13 || Windows 7 x64
* Last known working Electron version: Unknown

**Expected Behavior**
Implicitly or explicitly setting `navigateOnDragDrop` to false should prevent the `browserWindow` from navigating.

**Actual behavior**
Browser window changes to the content dragged, whether a file from the local system of a link from the web

**To Reproduce**
https://github.com/Slapbox/electron-react-boilerplate

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone https://github.com/Slapbox/electron-react-boilerplate.git
$ npm install
$ npm package
```

You need to package the app to enable drag/drop functionality. **Or instead try running the executables under /release folder**

**Comment by MarshallOfSound** [comment]
This feature was not in the 2.x release, it was added more recently than that.

**Comment by Slapbox** [comment]
Makes sense to me. Thanks much for the reply.

Do you think it would make sense to log a warning to console when passing a `browserWindow` parameter that does not exist? It seems like it would be an easy catch-all approach to these misunderstandings by users, as opposed to needing to be very vigilant about the docs pages.

**Comment by MarshallOfSound** [comment]
If you want that kind of safety I'd recommend using a typed language like typescript as we ship type definitions for electron with every release.  The typescript compilet would have complained about this for you.
