### ISSUE TITLE
Do we have the best way to update app.asar ?

### ISSUE THREAD

**Issue by yansenlei** [electron/electron#13850]
**Is your feature request related to a problem? Please describe.**
Do we have the best way to update app.asar ?

**Describe the solution you'd like**
It looks like the official recommendation is to update the entire software, but the only thing that needs to be updated is app.asar content.

**Describe alternatives you've considered**
If app.asar updates are supported, will the update speed be greatly improved?

**Additional context**
-

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by MarshallOfSound** [comment]
The is no framework out there at the moment which does in-place ASAR updates.  However the Squirrel.Windows framework does support delta updates which will only require the user to download the things that have changed since the version they currently have installed.
