### ISSUE TITLE
npm install electron@anyver fails rhel7.4 ubuntu16&18

### ISSUE THREAD

**Issue by kempy007** [electron/electron#13853]
* Electron Version: All
* Operating System (Platform and Version): rhel7.4 ubuntu 16.04 & 18.04
* Last known working Electron version: Only Windows

**Expected Behavior**
install complete with return code 0

**Actual behavior**
return code 1
[root@localhost padmin]# tail /root/.npm/_logs/2018-07-29T21_05_33_074Z-debug.log -n 30
3866 silly saveTree         └── pend@1.2.0
3867 warn enoent ENOENT: no such file or directory, open '/home/padmin/package.json'
3868 verbose enoent This is related to npm not being able to find a file.
3869 warn padmin No description
3870 warn padmin No repository field.
3871 warn padmin No README data
3872 warn padmin No license field.
3873 verbose stack Error: electron@3.0.0-beta.3 postinstall: `node install.js`
3873 verbose stack Exit status 1
3873 verbose stack     at EventEmitter.<anonymous> (/opt/rh/rh-nodejs8/root/usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/index.js:285:16)
3873 verbose stack     at emitTwo (events.js:126:13)
3873 verbose stack     at EventEmitter.emit (events.js:214:7)
3873 verbose stack     at ChildProcess.<anonymous> (/opt/rh/rh-nodejs8/root/usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/lib/spawn.js:55:14)
3873 verbose stack     at emitTwo (events.js:126:13)
3873 verbose stack     at ChildProcess.emit (events.js:214:7)
3873 verbose stack     at maybeClose (internal/child_process.js:925:16)
3873 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
3874 verbose pkgid electron@3.0.0-beta.3
3875 verbose cwd /home/padmin
3876 verbose Linux 3.10.0-693.el7.x86_64
3877 verbose argv "/opt/rh/rh-nodejs8/root/usr/bin/node" "/opt/rh/rh-nodejs8/root/usr/bin/npm" "install" "electron@beta" "--save-dev" "--disable-gpu"
3878 verbose node v8.9.4
3879 verbose npm  v5.6.0
3880 error code ELIFECYCLE
3881 error errno 1
3882 error electron@3.0.0-beta.3 postinstall: `node install.js`
3882 error Exit status 1
3883 error Failed at the electron@3.0.0-beta.3 postinstall script.
3883 error This is probably not a problem with npm. There is likely additional logging output above.
3884 verbose exit [ 1, true ]

**To Reproduce**
Your best chance of getting this bug looked at quickly is to provide a REPOSITORY that can be cloned and run.
install nodejs and npm
try to install electron globally.
npm install -g electron@beta --save-dev --disable-gpu

You can fork [electron-quick-start](https://github.com/electron/electron-quick-start) and include a link to the branch with your changes. **unable to run any hello world apps as the electron bin is missing.

**Comment by MarshallOfSound** [comment]
@kempy007 It looks like you are installing `electron` with `--disable-gpu` which is not a valid npm argument.  Can you please try without that argument and post your `process.arch` and `process.platform` values from within nodejs

**Comment by kempy007** [comment]
root@afd7d3470063:/usr/src/app# npm start

> electron-remote-websocket-browser@1.0.0 start /usr/src/app
> electron .

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-remote-websocket-browser@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-remote-websocket-browser@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-30T19_55_17_487Z-debug.log
root@afd7d3470063:/usr/src/app# npm install
removed 81 packages and audited 227 packages in 1.808s
found 0 vulnerabilities

root@afd7d3470063:/usr/src/app# npm start

> electron-remote-websocket-browser@1.0.0 start /usr/src/app
> electron .

sh: 1: electron: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! electron-remote-websocket-browser@1.0.0 start: `electron .`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the electron-remote-websocket-browser@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-30T19_55_41_114Z-debug.log
root@afd7d3470063:/usr/src/app# electron
bash: electron: command not found
root@afd7d3470063:/usr/src/app# node_modules/
Display all 151 possibilities? (y or n)
root@afd7d3470063:/usr/src/app# node_modules/electron
electron/          electron-download/
root@afd7d3470063:/usr/src/app# npm install electron-prebuilt
npm WARN deprecated electron-prebuilt@1.4.13: electron-prebuilt has been renamed to electron. For more details, see http://electron.atom.io/blog/2016/08/16/npm-install-electron

> electron-prebuilt@1.4.13 postinstall /usr/src/app/node_modules/electron-prebuilt
> node install.js

+ electron-prebuilt@1.4.13
added 1 package from 1 contributor and audited 451 packages in 3.09s
found 0 vulnerabilities

root@afd7d3470063:/usr/src/app# node_modules/electron
electron/          electron-download/ electron-prebuilt/
root@afd7d3470063:/usr/src/app# node_modules/electron-prebuilt/
cli.js      dist/       install.js  test/
root@afd7d3470063:/usr/src/app# node_modules/electron-prebuilt/dist/
electron    libnode.so  locales/    resources/
root@afd7d3470063:/usr/src/app# node_modules/electron-prebuilt/dist/electron .
root@afd7d3470063:/usr/src/app#
root@afd7d3470063:/usr/src/app# node_modules/electron-prebuilt/dist/electron . --disable-gpu
root@afd7d3470063:/usr/src/app# node_modules/electron-prebuilt/dist/electron
root@afd7d3470063:/usr/src/app#

**Comment by kempy007** [comment]
--disable-gpu was a last ditch attempt ignore it as it was also run without. ultimately i'm trying to run an electron app in docker, but i spent all day yesterday failing, so dropped back to plain linux and was failing to get demo electron apps to run, i just don't understand what i'm doing wrong.

**Comment by kempy007** [comment]
#Dockerfile
FROM node:latest

MAINTAINER null
# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY ./app/package*.json ./

RUN apt-get update -y
RUN npm install electron-prebuilt
RUN npm install electron-rebuild

RUN npm install

# Bundle app source can be any hello world app
COPY ./app/ .

# network ports to open.
EXPOSE 8000
CMD [ "npm", "start" ]

**Comment by MarshallOfSound** [comment]
> ultimately i'm trying to run an electron app in docker

This is your issue, Electron requires a GUI environment, I.e. a real window manager and desktop environment.  You can get around this by installing `xfvb` inside Docker but there's also a laundry list of dependencies that won't be installed inside docker but Electron needs to run.

You won't need all of them, but this should put you on the right track of which dependencies you need to install inside Docker to make everything run

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/vendor/circle_docker/core/Dockerfile

**Comment by kempy007** [comment]
well i tried under a full desktop this time fedora.
![image](https://user-images.githubusercontent.com/13536174/43489333-984f37ac-9514-11e8-9d4f-df45c86aadb0.png)

**Comment by kempy007** [comment]
+Fedora release 28 (Twenty Eight)

**Comment by kempy007** [comment]
Ok so after doing;
sudo yum install libXScrnSaver.x86_64

it then worked.

**Comment by kempy007** [comment]
+yum install nodejs

**Comment by kempy007** [comment]
so to clarify only after install of fedora before it asks for login(so no root password set nor have rebooted) does installing above packages result work in electron app running.
will rerun and confirm if repeatable.

**Comment by kempy007** [comment]
![image](https://user-images.githubusercontent.com/13536174/43491664-55538e90-951d-11e8-9ca4-fd58e6ba4daf.png)

**Comment by kempy007** [comment]
so after fedora install where can click quit, it open into full desktop, only at this point can i carry out the following pulled from history;
^C[liveuser@localhost-live electron-quick-start]$ history 
    1  yum install nodejs
    2  sudo yum install nodejs
    3  sudo yum install libXScrnSaver.x86_64
    4  git clone https://github.com/electron/electron-quick-start
    5  cd electron-quick-start/
    6  node -v
    7  npm -v
    8  npm install
    9  npm start
   10  history

**Comment by kempy007** [comment]
reboot go through first time wizard and none of above helps it wont run. bizarre
