### ISSUE TITLE
Hot Module Replacement with Redux only works every other time otherwise the page completely reloads

### ISSUE THREAD

**Issue by NearAutomata** [electron/electron#13873]
* Electron Version: 2.0.5 and 3.0.0@beta alike
* Operating System (Platform and Version): Windows 10 Build 1803 x64
* Last known working Electron version: not applicable

**Expected Behavior**
I expect the Reducer to be HMR-ed every time and not experience any page reload at all.

**Actual behavior**
Replacing Reducers with Hot Module Replacement works every other time but not all of the time. A more detailed explanation with pictures is [available here](https://stackoverflow.com/q/51594983/796036).

**To Reproduce**
A stripped down (kinda MWE) version can be found here: https://github.com/NearAutomata/redux-hmr-issue

*I removed almost everything, even the second renderer process and `electron-redux` link and the error is still occuring, so it is an HMR or Electron issue.*

Clone and run the following commands:

    yarn
    yarn run build-main
    yarn run build-renderer-hot

And in a second terminal run

    yarn run start-hot

**Additional Information**
It was confirmed that the `replaceReducer` API of Redux is working properly so I have to determine whether this is a Webpack specific issue or not. With this bug report I'd like to ask for your input whether you can confirm that this is not Electron being weird and just a Webpack HMR issue.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by NearAutomata** [comment]
> GitHub issues are for feature requests and bug reports.

@MarshallOfSound Pardon me, but this **is** clearly a bug report for a bug in either Webpack or Electron. Due to the wonky nature of this issue I wanted to ask for input on whether you can definitely rule out that Electron is the culprit to escalate this to the Webpack team.

**Comment by MarshallOfSound** [comment]
The reason I categorized this as code assistance is you yourself said you didn't know where the issue lays.  Without a solid minimal repro that we know isn't coming from another framework / module we can't look into these kinds of issues.

Additionally, historically these kinds of issues have been framework or user errors not issues with Electron itself
