### ISSUE TITLE
Spawning a detached process/unref()ing it doesn't work on Linux

### ISSUE THREAD

**Issue by andrewheadricke** [electron/electron#13870]
* Electron Version: 2.0.5
* Operating System (Platform and Version): Linux Mint

This is the same unresolved bug mentioned in this issue https://github.com/electron/electron/issues/2208

unref()ing a child process doesn't seem to work, the electron instance continues to wait for the child process to exit before electron (the parent process) can fully shutdown.  In my instance that means a systray icon remains.

I can forcefully kill the electron process and the child process continues to run, so that's working as expected.

Here's some sample code from the previous issue
```
var child = child_process.spawn(exepath, [], {detached: true: stdio: 'ignore'});
child.unref();
console.log("quitting")
app.quit()
```

**Comment by Ajeey** [comment]
@andrewheadricke Any update on how you solved this?

**Comment by Ajeey** [comment]
@andrewheadricke  Any update on how you solved the above issue?
cc @sofianguy

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by Ajeey** [comment]
@sofianguy I am still seeing the above mentioned issue on 4.2.9

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.
