### ISSUE TITLE
Performance tab in Developers Tools feezes

### ISSUE THREAD

**Issue by persones** [electron/electron#13886]
* Electron Version: 2.0.5
* Operating System (Platform and Version): OSX 10.13.3

**Actual behavior**
I Opened the Developers Tools window and accidentally selected the Performance tab. The Developers Tools window freezes. I cannot close it or choose another tab. This happens no matter what project I run, as long as it uses Electron 2.0.5. 

**To Reproduce**
Open Developers Tools and select the Performance tab.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
