### ISSUE TITLE
AltGr is wrongly mapped on win32 to ControlLeft instead of AltRight

### ISSUE THREAD

**Issue by Smile4ever** [electron/electron#13895]
* Electron Version: 2.0.3 or 2.0.4 or 2.0.5
* Operating System (Platform and Version): win32
* Last known working Electron version: unknown

**Expected Behavior**
I expected AltGr to map to AltRight in the keydown (and keyup) event handler on win32, just like it does on Linux.

**Actual behavior**
AltGr maps to ControlLeft instead, which is weird.

**To Reproduce**
AltGr is wrongly mapped to ControlLeft on Windows:

![afbeelding](https://user-images.githubusercontent.com/544411/43418605-b83c3992-943e-11e8-89b7-cf5a1871ca73.png)

I was able to verify that the behaviour on Linux doesn't show. The event data is as I would expect it on Linux:
![virtuallinux](https://user-images.githubusercontent.com/544411/43418327-d3597dd0-943d-11e8-9708-748d936c9d11.png)

I'm unsure for macOS, if someone could check what happens there that would be great.

This bug can be seen in Caprine. The downstream bug is here: https://github.com/sindresorhus/caprine/issues/539

**Comment by TanninOne** [comment]
On windows altgr triggers both left control and the right menu (altgr) key. Actually, any key combination that requires altgr can also use a key combination of left ctrl and left alt instead.
I think this is windows specific but not unique to electron.

**Comment by Smile4ever** [comment]
> On windows altgr triggers both left control and the right menu (altgr) key

The right menu key is something different than AltGr. I don't understand what you tell me about "both". Are two input (keyboard) events generated?

 > Actually, any key combination that requires altgr can also use a key combination of left ctrl and left alt instead.

You don't need left alt in this case. In the linked bug, I wanted to detect Ctrl+1. However, this is not possible since AltGr is displayed/parsed as ControlLeft on Windows (on Azerty keyboards, AltGr+2 makes the @ sign)

> I think this is windows specific but not unique to electron.

Do you have a source?

**Comment by TanninOne** [comment]
In the windows api the alt keys are called "menu", meaning the defines for the virtual keys are VK_MENU, VK_LMENU and VK_RMENU.
And yes, when you press altgr windows generates two key input events, one for the left control key and one for the right alt key (VK_RMENU).

> You don't need left alt in this case. In the linked bug, I wanted to detect Ctrl+1. However, this is not possible since AltGr is displayed/parsed as ControlLeft on Windows (on Azerty keyboards, AltGr+2 makes the @ sign)

That's not the point. What I'm telling you is that when you press ctrl+alt in windows, that is the same as pressing the right alt key (altgr).

Source, well, type "windows altgr ctrl" into google and you will get ~400k results all discussing the same topic but I don't know anything official, no.

**Comment by Smile4ever** [comment]
Thank you for the explanation.

So what you're telling me is that I should use setTimeout to handle AltGr on Windows if I don't want to handle the fake "Control" event? Suppose:
* I press AltGr
* The ControlLeft event is emitted. Since I want to know whether the AltGr (AltRight) event will fire, I do a setTimeout here. And I wait 20ms to check if the second event is emitted. If not, execute the action.
* The AltRight event is emitted. Set a flag so that action associated with the Control key is not executed.

Or is there a more elegant way?

**Comment by TanninOne** [comment]
Well, what I described to you is how the events are triggered by the OS, my only contact with this was with low-level api code. I can't really tell you how/if chrome somehow changes how altgr is reported to your application. What you described may work, you'd have to try.

My personal opinion is that in a cross-platform application you shouldn't try to make it work the same on every platform like it does on your preferred platform, you should make it work like "native" applications work. In this case: Windows applications don't treat altgr as a separate key, altgr is the same as ctrl+alt. Unless you have a very good reason, your application should work the same on windows.

**Comment by Smile4ever** [comment]
I'm trying to detect the difference between AltGr and Control, without making use of additional modifiers like shift. On Windows this was made especially hard in my opinion.

In fact, I just want to make "Ctrl+&" work like "Ctrl+1" (since that's the mapping on the Azerty keyboard) but that also catches AltGr+& which results (on my keyboard) in |, making the solution unacceptable (rendering AltGr useless on Windows is a real shame since it is used for the at sign, accents amongst others)

I'll try the same in Google Chrome on win32.

**Comment by TanninOne** [comment]
Wouldn't it make more sense to react only to the & event and at the time of that event check which modifiers are active? So on windows you get the & event, you trigger your event if ctrl is pressed and alt isn't and on linux and mac os you ignore alt and check only ctrl.

**Comment by Smile4ever** [comment]
The thing is, I want to react to Ctrl+&, Ctrl+é, Ctrl+", Ctrl+', Ctrl+(, Ctrl+§, Ctrl+è, Ctrl+!, Ctrl+ç, Ctrl+à, Ctrl+) and probably others (when using a slightly different Azerty keyboard layout).

So that solution is deemed to be impractical.. Unless there is a way to know which symbol represents 1, 2, 3... (using a JavaScript api) on a certain keyboard layout.

**Comment by Smile4ever** [comment]
As you can see, the problem is not detecting "&" (I use "code" as you can see in the screenshot).

The problem is that the AltGr event comes last, so by the time that event comes by I already executed the action since I thought it was Control.

Ideal situation:
* I press AltGr+& which is on the physical key "1": it outputs |
* I press Control+& which  is on the physical key "1": it executes the action

Current situation
* I press AltGr+& which is on the physical key "1": it executes the action since a fake "ControlLeft" event comes first. (bad!) I assume two events are coming due to your explanation, I have no other source for this.
* I press Control+& which  is on the physical key "1": it executes the action (good!)

The screenshots of the events are both for AltGr+(some key) on two different platforms. As you can see, on Windows, the altKey modifier flag is set to false (on the first event).

**Comment by Smile4ever** [comment]
Basically what I want to do is this, but without shiftKey needing to be pressed:
https://github.com/sindresorhus/caprine/pull/547/commits/2863c4b7039c06fa0424324b8f80ae865df07656

**Comment by Smile4ever** [comment]
If Electron on win32 is like Chrome on win32, I can set a flag to handle the situation properly (AltRight event is coming before Digit3 event):

```
test-keyup.html:11 code: ControlLeft ctrlKey: false altKey: false
test-keyup.html:11 code: AltRight ctrlKey: false altKey: false
test-keyup.html:11 code: Digit3 ctrlKey: false altKey: false
```

I used this code
```
<!DOCTYPE html>
<html>
<head>
<title>test</title>
</head>
<body>
	<script type="text/javascript">
		let body = document.getElementsByTagName("body")[0];
		body.addEventListener("keyup", keyuphandler);
		function keyuphandler(e){
			console.log("code: " + e.code + " ctrlKey: " + e.ctrlKey + " altKey: " + e.altKey);
		}
	</script>
</body>
</html>
```

**Comment by robinwassen** [comment]
@Smile4ever When I press Alt-GR + 2 on a sv_SE keyboard layout the following events are emitted:

**Electron v2.0.7**
```js
document.addEventListener("keydown", function(event) {
   console.log(event.key, event.code, "Alt:", event.altKey, "Control:", event.ctrlKey); 
});
undefined
VM114:2 Control ControlLeft Alt: false Control: true
VM114:2 AltGraph AltRight Alt: true Control: true
VM114:2 @ Digit2 Alt: true Control: true
```

**Chrome 68.0.3440.106 (Windows)**
```js
document.addEventListener("keydown", function(event) {
   console.log(event.key, event.code, "Alt:", event.altKey, "Control:", event.ctrlKey); 
});
undefined
VM270:2 Control ControlLeft Alt: false Control: true
VM270:2 AltGraph AltRight Alt: false Control: false
VM270:2 @ Digit2 Alt: false Control: false
```
They did some changes in how they handle AltGraph in Chrome 67. Can you check it those changes makes any sense or if the problem still persists in Chrome 67 or later?

Chrome notice about AltGraph change: https://www.chromestatus.com/feature/5059438092222464

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
