### ISSUE TITLE
CPU throttling emulation on Webview / Webcontents/ Session

### ISSUE THREAD

**Issue by 4eveRS** [electron/electron#13901]
Describe the solution you'd like
I would like to have a option to emulate CPU throttling in Electron. Since we already have emulation for viewports, user agents and network throttle.

Describe alternatives you've considered
There's a way to emulate CPU throttling through debugger ([chromium devtools commands](https://chromedevtools.github.io/devtools-protocol/tot/Emulation#method-setCPUThrottlingRate)), yet, it's not optimal, since it can easily be disabled if devtools are opened by the user.

**Comment by miniak** [comment]
@4eveRS I don't fully understand your concern. It's already possible to emulate CPU throttling, but you are worried that uses can disable it? Why would you do this in a shipping version of the app in the first place?

**Comment by 4eveRS** [comment]
@miniak In the current way to CPU throttling, it will be disabled if the user open the devtools panel for the specified webview.

AFAIK the only way to emulate CPU throttling is setting it over the devtools Debugger and it will be override once the user opens the devtools panel of the webview.

So I'm requesting this feature to make the CPU throttling be emulated through the session, so it can be shared over multiple webviews and don't be disabled if the user eventually opens up the devtools.

**Comment by 4eveRS** [comment]
@miniak As an example of app, imagine you are creating a browser were you allow your user to emulate a CPU throttling and also allow the user to open the devtools to inspect the page.

If the user emulate the CPU throttle and after that opens the devtools to inspect the page, it will be disabled, making a inconsistent feature of your app (CPU throttling).

Also I would have to listen to every creation of webview to set the CPU throttling, but if this feature was implemented in the session, like the network throttle, it wouldn't be disabled by the user and it would also be shared over the webviews that use the same session partition.
