### ISSUE TITLE
Missing file extension in download save dialog in MAC##10121 .Is this possible to get this fix in electron 1.8.4 ?

### ISSUE THREAD

**Issue by BONDbATIF** [electron/electron#13909]
* Electron Version:"electron": "^1.8.4"
* Operating System (Platform and Version):MAC .10.12 and 10.13

**Expected Behavior**
In showSaveDialog ,filter should apply in MAC, Window it is working fine. 

**Actual behavior**
In showSaveDialog, Filter is not applying 

**To Reproduce**
create a showSaveDialog window .
![extension](https://user-images.githubusercontent.com/5045450/43576791-d171433c-9667-11e8-9c43-5220dc7fc7f4.png)

 this.ChooseUrl = this.dialog.showSaveDialog(
                {
                    filters: [
                        { name: 'CXF Files', extensions: ['cxf'] },
                        { name: 'ASE Files', extensions: ['ase'] },
                        { name: 'All Files', extensions: ['*'] }
                    ]
                },

**Comment by codebytere** [comment]
This was added as a new feature to Mac in `2-0-x` so unfortunately per our versioning rules we cannot apply it to the `1-8-x` release line.
