### ISSUE TITLE
Geolocation Emulation on Webview / Webcontent / Session

### ISSUE THREAD

**Issue by 4eveRS** [electron/electron#13900]
**Describe the solution you'd like**
I would like to have a option to emulate geolocation in Electron. Since we already have emulation for viewports, user agents and network throttle.

**Describe alternatives you've considered**
There's a way to emulate geolocation through debugger ([chromium devtools commands](https://chromedevtools.github.io/devtools-protocol/tot/Emulation#method-setGeolocationOverride)), yet, it's not optimal, since it can easily be disabled if devtools are opened by the user.

**Comment by miniak** [comment]
@4eveRS I don't fully understand your concern. It's already possible to emulate geolocation, but you are worried that uses can disable it? Why would you do this in a shipping version of the app in the first place?

**Comment by 4eveRS** [comment]
@miniak In the current way to emulate geolocation, it will be disabled if the user open the devtools panel for the specified webview.

AFAIK the only way to emulate geolocation is setting it over the devtools Debugger and it will be override once the user open the devtools panel of the webview.

So I'm requesting this feature to make the geolocation be emulated through the session, so it can be shared over multiple webviews and won't be disabled if the user eventually opens up the devtools.

**Comment by 4eveRS** [comment]
As an example of app, imagine you are creating a browser were you allow your user to emulate a geolocatioj and also allow the user to open the devtools to inspect the page.

If the user emulate the geolocation and after that opens the devtools to inspect the page, it will be disabled, making a inconsistent feature of your app (geolocation emulation).

Also I would have to listen to every creation of webview to set the geolocation emulatioj, but if this feature was implemented in the session, like the network throttle, it wouldn't be disabled by the user and it would also be shared over the webviews that use the same session partition.
