### ISSUE TITLE
 Error: Could not locate the bindings file. Tried: ui/node_modules/deasync/build/deasync.node

### ISSUE THREAD

**Issue by rajaaliya2020** [electron/electron#13915]
* Electron Version: ^2.0.0
* Operating System (Platform and Version): Mac High Seira
* Last known working Electron version: unknown

**Expected Behavior**
The binding should work. The node app (express) works when run outside the electron 

**Actual behavior**
 Error: Could not locate the bindings file. Tried: ui/node_modules/deasync/build/deasync.node

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
