### ISSUE TITLE
BrowserWindow.frame = false breaks CSS cursor rules

### ISSUE THREAD

**Issue by joaomoreno** [electron/electron#13911]
* Electron Version: 1.8.7, 2.0.2 and 3.0.0-beta.4
* Operating System (Platform and Version): Ubuntu Linux 18.04
* Last known working Electron version: ?

**Expected Behavior**

`pointer: cursor` should work regardless of whether BrowserWindow was created with `frame: false`.

**Actual behavior**

`pointer: cursor` stops working at about 76% height of the window, when using `frame: false`.

**To Reproduce**

You can use Electron Fiddle to load the repro: https://gist.github.com/joaomoreno/2bb9879aee864f22704882b5fac825c3

**Additional Information**

From Microsoft/vscode#53870

**Comment by MarshallOfSound** [comment]
Duplicate #5723
