### ISSUE TITLE
Some libraries fail to load on NodeIntegration: true

### ISSUE THREAD

**Issue by mluis** [electron/electron#13912]
Is there any solution for this? Please acknowledge: [here](https://github.com/electron/electron/issues/8333#issue-198625849) or [here](https://github.com/pablojim/highcharts-ng/issues/606#issue-238496847)

**Comment by MarshallOfSound** [comment]
@mluis This is in our FAQ

https://github.com/electron/electron/blob/master/docs/faq.md#i-can-not-use-jqueryrequirejsmeteorangularjs-in-electron

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
