### ISSUE TITLE
Not compatible with windows 10.0.10586

### ISSUE THREAD

**Issue by GrumpyCrouton** [electron/electron#13918]
* Electron Version: 2.0.5
* Operating System (Platform and Version): Windows 10 Home 10.0.10586 build 10587
* Last known working Electron version: 

**Expected Behavior**
Program to launch.

**Actual behavior**
Error, "This version of ... is not compatible with the version of Windows you're running .Check your computer's system information and then contact the software publisher"

**Comment by Kthulu120** [comment]
@GrumpyCrouton just for more information, have you tried this with any other version of Electron?

**Comment by GrumpyCrouton** [comment]
@Kthulu120 I have not.

**Comment by Kthulu120** [comment]
If you could get us more information that allows us to reproduce along with some screenshots or more context into the situation (such as a stacktrace) I'd be more than happy to look into it. Also if possible some things that would help us find a solution would be to see if its working with either a earlier or more recent version of Electron. When we get some more context on the issue I'll go ahead and remove the `needs-info` label.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
