### ISSUE TITLE
Alt+F4 closes unclosable windows, ignores close event cancelling.

### ISSUE THREAD

**Issue by markleutloff** [electron/electron#13910]
* Electron Version: 3.0.0-beta.1, 2.x
* Operating System (Platform and Version): Windows 10, 8 (x86 and x64)
* Last known working Electron version: -

**Expected Behavior**
Pressing Alt+F4 should not close the BrowserWindow.

**Actual behavior**
The BrowserWindow closes.

**To Reproduce**
Create a BrowserWindow with **closable = false**.
Bind the close event and call event.preventDefault() to cancel the closing of the window.
When the window is focused press Alt+F4.

**Additional Information**
Creating the window in the main process and preventing the "close" event will not prevent the close of the window. The event will be fired but the window will close even when calling event.preventDefault().

I know about the workaround by handling onbefureunload on the window object at the render process.
But this has major drawbacks:

- the event can be overriden
- this prevents navigating to other pages
- the event is bound in the render process/client side code

Related issues:
https://github.com/electron/electron/issues/3362
https://github.com/electron/electron/issues/6702

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by SergeyBelikof** [comment]
Sill repro: electron 5.0.6

**Comment by orbitfum** [comment]
still 7.1.0

**Comment by OneDayisADay** [comment]
Still 9.1.0

**Comment by pushkin-** [comment]
@sofianguy Since this is still an issue, can it please be reopened?

**Comment by AmarBouchibane** [comment]
This also applies to toolbar windows. The close button is disabled, but a toolbar can be closed with Alt + F4 if it has focus.

**Comment by markleutloff** [comment]
I retested the issue with Electron 18, 19, 20 and was unable to reproduce the issue anymore.

**Comment by pushkin-** [comment]
I can reproduce this with Electron 21 on Windows
