### ISSUE TITLE
Electron 3.0 beta: pdf viewer not functional, save as dialog appears instead.

### ISSUE THREAD

**Issue by markleutloff** [electron/electron#13928]
* Electron Version: 3.0 Beta 4
* Operating System (Platform and Version): Windows10, 8 (x86 and x64)
* Last known working Electron version: 2.x

**Expected Behavior**
PDF should be displayed.

**Actual behavior**
"Save As.." dialog for download appears and pdf will not be displayed, even when downloaded.

**To Reproduce**
Create a BrowserWindow and load an URL with a pdf or iframes with pdfs.

```
const win = new BrowserWindow({
	width: 800,
	height: 600,
	webPreferences: {
		plugins: true
	}
});

win.webContents.loadURL(URL_TO_PDF);
```

**Comment by nornagon** [comment]
Duplicate of #12337
