### ISSUE TITLE
ContextMenu and Tray Icon source location.

### ISSUE THREAD

**Issue by rucuriousyet** [electron/electron#13922]
Hey! I am working on a native app that uses some usual technologies, and I was using this repo for researching how to add native integrations for SDL2 applications such as AppMenus, Notifications, ContextMenus (I think that's what you'd call a menu that appears on right-click), Tray etc. I was able to find the code for launching Notifications and AppMenu, but not ContextMenus and Trays, so I was wondering if someone could point me to the location of the source code related to these integrations.

**Comment by MarshallOfSound** [comment]
Lots of the tray / context menu code we actually inherit from chomiums View / Menu models.

E.g. https://github.com/electron/electron/blob/master/atom/browser/ui/tray_icon_gtk.h#L34

I'd suggest looking inside Chromium for that stuff 👍
