### ISSUE TITLE
While condition freezes electron

### ISSUE THREAD

**Issue by CreatorVilius** [electron/electron#13929]
* Electron Version: Latest
* Operating System (Platform and Version): Windows 10
* Last known working Electron version: *Idk*

**Expected Behavior**
While condition work properly like in browser.

**Actual behavior**
While condition breaks electron.

**To Reproduce**
```js
let test = false
while(!test) {

}
```

**Additional Information**
Probably because while condition freezes JS and only executes stuff inside of it. CMD/CTRL + R is also frozen.

**Comment by MarshallOfSound** [comment]
The code you provided is an infinite loop and will freeze any tab in any browser as well 🤔 Just double checked in Chrome, it freezes the tab completely.

**Comment by MarshallOfSound** [comment]
zz

**Comment by CreatorVilius** [comment]
When i mean freeze, i mean completly freeze electron. Can't even do CTRL+SHIFT+I, or CTRL R.

**Comment by dquak** [comment]
I have multiply BrowserView's and run an infinite loop in one of them to check crash detection, and it seem all browserViews are getting stuck as the main process as well.. this issue seem to happen only when the DevTools are closed..

@MarshallOfSound In Chrome, only the infinite loop tab will become unresponsive, and not the whole app.
