### ISSUE TITLE
BrowserWindow Height Not Working Properly on Windows 10

### ISSUE THREAD

**Issue by kirkouimet** [electron/electron#13932]
* Electron Version: 3.0.0-beta.4
* Operating System (Platform and Version): Windows 10

My screen height is 1440 with a scale factor or 1.5 (4K monitor). When I create a new BrowserWindow with the height option anything greater than 1,410 the height is always set to 1,403 pixels and will not go any bigger. This leaves a little gap at the bottom of the screen between the task bar and the window.

Calling `setBounds` and setting the height does fix it after the BrowserWindow has been created.

**To Reproduce**

`var electronBrowserWindow = new electron.BrowserWindow({height: 1410});`

**Screenshots**

![windows-10-sadness](https://user-images.githubusercontent.com/62191/43662783-4ae88704-9724-11e8-9b42-911aae82f58b.png)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
