### ISSUE TITLE
webviews left attached to the DOM make app remain a background process after exit

### ISSUE THREAD

**Issue by maxosprojects** [electron/electron#13939]
* Electron Version: 2.0.2, 2.0.6
* Operating System (Platform and Version): Windows 10
* Last known working Electron version: ---

**Expected Behavior**
1. Electron app is removed from the process list when window is closed.
2. App folder can be removed

**Actual behavior**
1. The app goes to _Background processes_ and remains there indefinitely. Any new copies of the app remain there too, consuming CPU and memory.
2. `app.makeSingleInstance` does not detect those background processes and the app starts as usual.
3. App folder cannot be removed.

**To Reproduce**
1. git clone https://github.com/maxosprojects/electron-webviews-bug
2. npm install
3. npm start
4. Wait for the page to load completely and video to start playing.
5. Close the app.
6. Check _Task Manager_, _Processes_ tab, _Background Processes_ section
Electron should be hanging in there.

[Task Manager screenshot](https://github.com/maxosprojects/electron-webviews-bug/blob/master/electron-background-process.png)

**Workaroud**
Remove all `webview` elements from DOM prior to shutting down the app, e.g. BrowserWindow to listen on `close` event, prevent it with `e.preventDefault()`, detach all `webview` elements from DOM and then close the app.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
