### ISSUE TITLE
Private API in MAS build [3.0.0-beta.4]

### ISSUE THREAD

**Issue by thomasdao** [electron/electron#13938]
* Electron Version: 3.0.0-beta.4
* Operating System (Platform and Version): Mac 10.13.6
* Last known working Electron version: 2.0.5

**Expected Behavior**
MAS build does not contain private API

**Actual behavior**
MAS build is rejected. Please see below error

```
Your app uses or references the following non-public APIs:

Symbol: _CGDisplayUsesForceToGray
From framework: /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
Symbol: __LSSetApplicationLaunchServicesServerConnectionStatus
From framework: /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
Symbol: _AudioDeviceDuck
From framework: /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
Symbol: __CFIsObjC
From framework: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
In binary: Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
```

**Comment by kamalkalra** [comment]
I'm having the same issue, even with 2.0.5.

> Symbol: _CGDisplayUsesForceToGray
From framework: /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics

>Symbols: ___CFRunLoopSetOptionsReason, __CFIsObjC
From framework: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation

>In binary: Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework

**Comment by thomasdao** [comment]
I see, maybe it only pass with 2.0.4. Sorry for giving wrong last known working version

**Comment by kamalkalra** [comment]
No problem @thomasdao Unfortunately, I can't keep re-submitting new packages only to have them rejected by Apple.  I'd like to get a definitive statement from somebody at electron.  I don't know of any way to pre-check for private API before submitting to the app store.

**Comment by omar10594** [comment]
Our application was rejected for the same reason, and the error is on 1.8.7 too #13957

Looks like this happened some times in the past, so we need a way to check if the MAS build use some non-public api before submit to the App Store.

**Comment by nornagon** [comment]
Should be fixed by electron/libchromiumcontent#633.

**Comment by nornagon** [comment]
Complete list of private APIs that have been reported to be failing MAS submission so far:
- `CGDisplayUsesForceToGray`
  - usage removed in electron/libchromiumcontent#633
- `_CFIsObjC`
  - usage removed in electron/libchromiumcontent#633, looking to [upstream the change to chromium](https://chromium-review.googlesource.com/c/chromium/src/+/1164067) as well
- `_LSSetApplicationLaunchServicesServerConnectionStatus`
- `AudioDeviceDuck`
- `__CFRunLoopSetOptionsReason`
  - Calls to this were [removed in Chromium 64](https://chromium.googlesource.com/chromium/src.git/+/9db30774936966f9edcccbccd3c56e385ada034b).

**Comment by ivandroid** [comment]
Will there be an update soon?

**Comment by nickfujita** [comment]
I am also seeing this issue, and I see that these fixes were all merged yesterday. @nornagon Could you please advise on the latest npm version to use that will take advantage of these removals?

**Comment by ckerr** [comment]
`2.0.7` should have these changes.

`3.0.0-beta.5` will as well, which should be out sometime this week or possibly early next depending on timing.

**NB:** Since the Apple testing process is opaque and since Electron's dependencies are big, it's difficult to know if all the private calls have been removed -- please keep the feedback coming!

**Comment by nickfujita** [comment]
@ckerr Thanks! Just rebuilt and signed with 2.0.7, I'll get back to your with the result from the app store.

**Comment by zinne** [comment]
Had the same issue 3 rejections so far. I'll try 2.0.7 tonight

**Comment by dimitarnestorov** [comment]
I can also confirm that 2.0.7 has no issues. Thanks!

**Comment by nornagon** [comment]
Thanks everyone for your reports, both of failing submissions and successful ones! Hopefully we've whac-a-mole'd all the private APIs once more. I'll reopen if we discover new ones, but I'm going to close this for now as the fixes have been backported to all supported release lines (1.7, 1.8, 2.0 and 3.0).

The versions that contain the fixes will be:
- 1.7.16
- 1.8.8
- 2.0.7 (released)
- 3.0.0-beta.5

**Comment by kamalkalra** [comment]
I can also confirm that the fix worked (or at the very least Apple didn't complain about anything new).  Thanks to the electron team for the quick turn-around.

**Comment by thomasdao** [comment]
Thanks @nornagon and Electron team! Look forward to the 3.0.0-beta.5, hopefully it's out soon

**Comment by thomasdao** [comment]
Just to update 3.0.0-beta.5 also passed Apple Review. Thanks @nornagon and the team 👍

**Comment by vanejung** [comment]
Thanks @nornagon and everyone else for confirming.
I'd like to also share that my build has been passed the review with 2.0.7.

**Comment by asjad-m** [comment]
Hi there, i am having same issue for private api's but i use electron.net instead of electron. my electron.net version is 5.22.14.0. Help me in this regard what should i do? thanks in advance

**Comment by asjad-m** [comment]
> Thanks everyone for your reports, both of failing submissions and successful ones! Hopefully we've whac-a-mole'd all the private APIs once more. I'll reopen if we discover new ones, but I'm going to close this for now as the fixes have been backported to all supported release lines (1.7, 1.8, 2.0 and 3.0).
> 
> The versions that contain the fixes will be:
> 
> * 1.7.16
> * 1.8.8
> * 2.0.7 (released)
> * 3.0.0-beta.5

what about electron.net 5.22.14.0 version. i have same issue of private api's
