### ISSUE TITLE
Renderer process sandbox and Webpack

### ISSUE THREAD

**Issue by poprou** [electron/electron#13933]
Hi,

I want to enable the sandbox option in electron but I'm getting a `process is not defined` error. From what I understand, with browserify I would need to user the `--insert-global-vars` switch to have access to `process` as stated [here](https://electronjs.org/docs/api/sandbox-option). How can I do this with webpack?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
