### ISSUE TITLE
[Docs] security.md - Disable navigation example not working + typo

### ISSUE THREAD

**Issue by GhostlyDark** [electron/electron#13943]
#13884 added **13) Disable or limit navigation** to tutorial docs (security.md) with the following example:

```
const URL = require('url')

app.on('web-contents-created', (event, contents) => {
  contents.on('will-navigate', (event, navigationUrl) => {
    const parsedUrl = new URL(navigationUrl)

    if (url.hostname !== 'my-own-server.com') {
      event.preventDefault()
    }
  })
})
```

However, I can't get this to work. 
Is it just me being stupid or why is the const parsedUrl declared but not used?

Also typos for links: will-navigate and new-window

**Comment by MarshallOfSound** [comment]
@GhostlyDark It's a typo 🙂 `url.hostname` should be `parsedUrl.hostname`

**Comment by GhostlyDark** [comment]
@MarshallOfSound Thought so. The reason I still can't get this to work is that my app does not fire the will-navigate event. This is due to using sandbox options. An info on this should be added as well.

**Comment by wannik7** [comment]
19343
