### ISSUE TITLE
Electron 3-beta - Custom protocol doesn't set host, hostname and origin

### ISSUE THREAD

**Issue by hexiao-o** [electron/electron#13948]
* Electron Version:  3.0.0-beta.4
* Operating System (Platform and Version):  Mac
* Last known working Electron version:   2.x

**Expected Behavior**
Using a custom protocol handler the window.location object contains the host, hostname or origin

**Actual behavior**
Using a custom protocol handler the window.location object doesn't contain the host, hostname or origin

**Additional Information**
Something like that [Custom protocol doesn't set host, hostname and origin #1879](https://github.com/electron/electron/issues/1879)

**Comment by codebytere** [comment]
@hexiao-o does this occur every time you use a custom protocol handler or just some of the time? In the issue you linked, the host, hostname and origin are set some of the time just not reliably. Do you have a repro handy that I could use to test this issue?

**Comment by hexiao-o** [comment]
Sorry, I have a problem with my code. This is not a BUG
