### ISSUE TITLE
Bad encoding on pasted text when string contains non-ascii symbols (eg Russian Cyrillic)

### ISSUE THREAD

**Issue by MurzNN** [electron/electron#13949]
* Electron Version: 1.8.4
* Operating System (Platform and Version): Ubuntu Linux 18.04
* Last known working Electron version: none

**Expected Behavior**
When I try to paste non-ascii UTF-8 text from clipboard to any Electron app - I want to see it in same encoding, without converting.

**Actual behavior**
When I try to paste non-ascii UTF-8 text from native Linux app to any Electron app via clipboard - it loses encoding and inserts as bad symbols. For example. when I paste Russian word with Cyrillic characters `Тест` from clipboard on any Electron app, it is pasted as `Ð¢ÐµÑÑ‚`. In other apps it pasted normally, without losing encoding and converting symbols.

If I type this word manually in Electron textarea - it types normally.

If I copy it to clipboard from other Electron app - it works normally too.

So seems the bug source is with converting native Linux clipboard to Electron clipboard format.

**To Reproduce**
Copy this non-ascii UTF-8 word `Тест` from any native Linux app to clipboard and paste to any Electron app, it will be pasted as `Ð¢ÐµÑÑ‚` instead of `Тест`.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by MurzNN** [comment]
I rechecked via electron v4.0.0 and bug is still here. @sofianguy, does it reproducible in your environment?

**Comment by comcaptain** [comment]
Same thing happens on 7.1.3

**Comment by MurzNN** [comment]
Bug report is about Electron on Linux, not on Windows, and still reproducible on 7.1.3.

**Comment by MurzNN** [comment]
Hmm, can't reproduce now on 7.1.3 with Ubuntu 19.10, seems fixed? Will try on other environments.
