### ISSUE TITLE
[Regression][3.0.0-beta.4] Shared Workers are not Shared

### ISSUE THREAD

**Issue by kuashe** [electron/electron#13952]
* Electron Version: 3.0.0-beta.4
* Operating System : Windows 10 & Mac OS 10.13
* Last known working Electron version:  2.0.6

**Expected Behavior**
Shared Workers instances are shared across Electron Windows

**Actual behavior**
Shared Workers are re-instanciated for each Electron Window

**To Reproduce**

[Repostiory](https://github.com/kuashe/electron3-shared-worker-broken)

**Working version in latest 2.X (Electron 2.0.6)**

```sh
$ git clone https://github.com/kuashe/electron3-shared-worker-broken

$ npm install

$ npm start
```
Select the 'Console' tab in the Chrome DevTools

The Shared Worker variable named 'increment' is incremented alternatively across windows, thus the worker being shared. 

**Regression in current 3.X  (Electron 3.0.0-beta.4)**

```sh
$ npm install electron@beta

$ npm start
```
Select the 'Console' tab in the Chrome DevTools

The Shared Worker variable named 'increment' is duplicated across windows, thus the worker not being shared.

**Comment by nitsakh** [comment]
This behavior was changed in chromium. It now treats file urls as opaque origins for shared workers. Hence, this does not work with `file://` urls in electron 3.0 beta.

**Comment by kuashe** [comment]
@nitsakh Shouldn't this behavior occurs on current versions of chrome ?

I don't see why Chromium would behave differently than Chrome.

**Comment by nitsakh** [comment]
Yeah! This will not work local files with even with chrome.
Actually, chrome cannot load webworkers from `file://` urls.

**Comment by nitsakh** [comment]
Closing this issue as this behavior has changed in chromium. You can achieve the same behavior in electron using custom protocol.

**Comment by kuashe** [comment]
@nitsakh I just tested using `registerHttpProtocol` , the issue is still persisting.
 
Hence , [the unit test is incorrect](https://github.com/electron/electron/blob/dd5b8769befa671c18680aea990b838bc7828063/spec/chromium-spec.js#L821) it doesn't actually test that a SharedWorker can be shared between Window instances , which is the core purpose of this API , it just test that the sharedworker 'can work' not that it can be 'shared'.

Please reopen this issue , has it needs a PR.

**Comment by nitsakh** [comment]
I verified your example using `registerFileProtocol` and it worked and workers were shared.
For the unit test, please feel free to open a PR. We don't need to leave this issue open for the PR.

**Comment by kuashe** [comment]
Could you provide the code excerpt with `registerFileProtocol` so I can make the PR ?
I used both `registerFileProtocol ` and `registerHttpProtocol` [from the documentation ](https://github.com/electron/electron/blob/master/docs/api/protocol.md) , none of which worked.

**Comment by kuashe** [comment]
@nitsakh Please provide the working code excerpt, otherwise reopen this issue.

My example now contains [registerFileProtocol](https://github.com/kuashe/electron3-shared-worker-broken/blob/2c7d0d2e7d3084734d9525232da36ef8c07b162f/main.js#L49) which does not resolve the issue.

**Comment by nitsakh** [comment]
You have to load index.html through `loadURL` with the protocol.
The [community](https://github.com/atom/electron#community) is a good place for questions related to your code. Please direct your questions there.
