### ISSUE TITLE
PDF Viewer: localize webui / add multiple language support

### ISSUE THREAD

**Issue by davidnorthetal** [electron/electron#13954]
Hey,

it seems that currently the strings for the texts for the native-pdf-viewer are hardcoded with english-texts and are not affected by LOCALE settings.

e.g.: ![image](https://user-images.githubusercontent.com/24317742/43721009-f4095d3a-9991-11e8-95db-4060f24298bd.png)
On hover shows a native Windows popup reading "Rotate clockwise", no matter what language is set.

Which lead me to this line:

https://github.com/electron/electron/blob/9f328abe19186af292eea3757ac908bc793a987c/atom/browser/ui/webui/pdf_viewer_handler.cc#L176

---

I'm unsure if the TODO would resolve my issue as I'm unsure if e.g.: https://chromium.googlesource.com/chromium/src/+/lkgr/components/pdf_strings.grdp is affected by localization.

Either that or binding these to whatever localization Electron itself makes use of would be great to get multi-language support working.

Maybe someone could shed some light on this. Maybe the author himself? @deepak1556 

Thanks for any responses.

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
