### ISSUE TITLE
App relaunch question

### ISSUE THREAD

**Issue by Alin13** [electron/electron#13950]
I'm currently working on an Electron app which uses a third party software. At some point I'm checking if that software is installed on the user's computer (it has to be in PATH), and if it's not there I just run the installation. As I said, the installation will append a directory to the PATH variable. After this happens, I need to restart the app in order to have access to the updated variables.

I already tried to use relaunch, just as in the docs, but it doesn't refresh the variables:

```
app.relaunch()
app.exit(0)
```

Also tried this:
```
exec(process.execPath);
app.quit();
```
...but the app is not starting after quit.

If I restart the app manually, then everything works ok.

Does anyone have some ideas ? Thanks in advance !

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
