### ISSUE TITLE
WebRTC internals page becomes unreadable after scrolling

### ISSUE THREAD

**Issue by DEDaniel** [electron/electron#13951]
* Electron Version: 2.0.6
* Operating System (Platform and Version): macOS High Sierra (10.13.5)
* Last known working Electron version:  1.8.2

**Expected Behavior**
Load 'chrome://webrtc-internals' in a BrowserWindow and display it correctly.

**Actual behavior**
'chrome://webrtc-internals' will be loaded in a BrowserWindow but after scrolling the information on the page becomes unreadable.

**To Reproduce**
Create a BrowserWindow without any options and load 'chrome://webrtc-internals' and scroll on the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/38344956/43712602-01b4e406-9977-11e8-95ea-2f2cd3cef9e2.png)

**Additional Information**
This page was working well in Electron version 1.8.2.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
