### ISSUE TITLE
Hi, i have built an electron app with wrapping up the my webpage inside it using url. My webpage is completely built using angular 1.5. Now i need to know how to communicate from webpage to electron side like how to call a function inside electron when some button is clicked in my webpage?

### ISSUE THREAD

**Issue by prakashprakee** [electron/electron#13963]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
