### ISSUE TITLE
Is there a way to keep tray alive while quit the app from the dock?

### ISSUE THREAD

**Issue by mickychen0524** [electron/electron#13967]
I tried some mac apps like Timing and it keeps try icon running even when quit the app from dock. but I noticed that it's not built using electron. so I am wondering if this feature is possible with electron.
Thanks

**Comment by MarshallOfSound** [comment]
`app.dock.hide()`

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by mickychen0524** [comment]
@MarshallOfSound Thanks for your help. but how to distinguish quit from dock and from default quit menu?
