### ISSUE TITLE
Can't print on Windows

### ISSUE THREAD

**Issue by ivan-leschinsky** [electron/electron#13978]
* Electron Version: 2.0.3
* Operating System (Platform and Version): Windows (x86 and x64)
* Last known working Electron version: unknown

**Expected Behavior**
Calling `webContents.print()` on the current active window should open system print dialog like on macOS

**Actual behavior**
Nothing happens when call `webContents.print()` or `webview.print()`. Everything works on macOS.

**To Reproduce**
Any application on electron 2.0.3. Build or just run in windows and call `print()` on any window webContents.

**Additional information**
* Tried to put pdf.dll inside to the dist folder from [this release (0.36.1)](https://github.com/electron/electron/releases/tag/v0.36.1) but it didn't help
* I'm using [electron-build](https://github.com/electron-userland/electron-builder) to package an app with that settings in the `package.json`:
```json
"build": {
  "appId": "myAppId",
  "files": [
    "app/**/*",
    "node_modules/**/*",
    "package.json"
  ],
  "directories": {
    "buildResources": "resources"
  },
  
  "win": {
    "target": [
      {
        "target": "nsis",
        "arch": [
          "x64",
          "ia32"
        ]
      }
    ],
    "extraResources": [
      "./lib/x64/*.dll",
      "./lib/x86/*.dll"
    ],
    "extraFiles": [
      {
        "from": "build",
        "to": "",
        "filter": ["*.dll"]
      }
    ]
  }
}
```

**Comment by tmirun** [comment]
i have similar issue in windows, but in my case when print page lose words

**Comment by popod** [comment]
Hi @tmirun 

> but in my case when print page lose words

Is it something like this bug : #14260 ? If yes, have you found any workaround ?

Thanks

**Comment by codebytere** [comment]
The original issue here has been solved in v3.
