### ISSUE TITLE
Node api fs.readSync with a big position works not right

### ISSUE THREAD

**Issue by toddwong** [electron/electron#13979]
* Electron Version: v3.0.0-beta.4
* Operating System (Platform and Version): Windows 10
* Last known working Electron version:  v2.0.6

**Expected Behavior**
Node api `fs.readSync` with a position >= 2^32 should work.

**Actual behavior**
Node api `fs.readSync` with a position >= 2^32 returns wrong data.

**To Reproduce**

```
let fd = fs.openSync("X:\\path\\to\\a\\big\\file", 'r');
fs.readSync(fd, buf, 0, buf.length, 0x100000000);
fs.closeSync(fd);
```

This code won't fill the right content in `buf`.

I've uploaded a small test on github.

$ git clone https://github.com/toddwong/test-electron-big-file
$ cd test-electron-big-file
$ npm install
$ electron .

**Comment by toddwong** [comment]
@MarshallOfSound Yes, it works in node v10.8.0, and electron v2.0.6

**Comment by nitsakh** [comment]
Electron 3.0.x uses node v10.2.0. The example works fine with node v10.8.0 as @toddwong tried but not with node v10.2.0. So it's a node regression.

**Comment by nitsakh** [comment]
Just to add, it's not windows specific. I was able to repro on macos.

**Comment by codebytere** [comment]
Fairly certain this PR fixes it: https://github.com/nodejs/node/pull/21003
i'll backport this to our `v10.2.0` branch imminently

**Comment by codebytere** [comment]
Resolved with the above PR, should go out in the next beta release 🎉
