### ISSUE TITLE
BrowserWindow .loadFile is not a function

### ISSUE THREAD

**Issue by realisation** [electron/electron#13984]
* Electron Version: 2.0.6
* Operating System (Platform and Version): MacOS 10.12.6
* Last known working Electron version: Don't know just installed it from npm

**Expected Behavior**
It loads the html file at the string path specified...

**Actual behavior**
I run 'electron index.js' which waits for the app to be ready, and then creates a new BrowserWindow, which works fine, with which I immediately call `.loadFile('index.html')`, which immediately gives me a popup error that says
 ```
A JavaScript error occurred in the main process:
Uncaught Exception: TypeError: mainWindow.loadFile is not a function
    at App.createWindow (/Users/realisation/Desktop/code/ecsa/distributedjs/electron.js:9:14)
    at emitTwo (events.js:130:20)
    at App.emit (events.js:213:7)
```

**To Reproduce**
Simply use my operating system, electron version, and write the following code, I suppose: 
```
  1 const { app, BrowserWindow } = require('electron')
  2 
  3 let mainWindow
  4 
  5 function createWindow () {
  6 
  7   mainWindow = new BrowserWindow({width: 800, height: 600})
  8   mainWindow.loadFile('./index.html')
  9   // mainWindow.on('closed', function () { main = null })
 10   
 11 }
 12 
 13 app.on('ready', createWindow)
```

**Comment by ckerr** [comment]
The sample code that you provided works for me using 2.0.6.

My guess is that, when invoking the test case with `electron index.js`, that you're picking up an older version of Electron that doesn't have `BrowserWindow.loadFile()`, which was added in 2.0.0 -- try running `electron -version` from the command line to see what version you have installed.

If it turns out this is the issue, take a look at `electron-quick-start` to and its `package.json` for an example of how your app can specify what version of Electron to use.

**Comment by realisation** [comment]
Aha this is true, the electron that runs it is installed globally!

**Comment by re-jim** [comment]
I get this error when I run `npm start`, which is described in package.json as 
`"start": "tsc && electron ."`

But if I just run `electron .` it works.

If I add `electron -version` to the npm command, I get electron 1.4.13, but if I type `electron` in a console window, I get `2.0.7`.

Weird.

**Comment by realisation** [comment]
That's probably because npm run commands run it with your local node
modules, but non npm run commands would run it from your globally installed
version.

I was also experiencing a couple ancillary problems with NPM that were
confusing.

The first one if I remember correctly, was that electron was being
installed as electron-quick-start or some boilerplate. I don't remember
this one though because I just stripped electron out from package.json
altogether and started again.

Then yesterday I had another weird thing with npm, that when I was trying
to install an unrelated dependency, it told me...:

npm ERR! Could not install from "electron" as it does not contain a
package.json file.


I have no idea what this means because electron isn't a file in my folder
or a folder in my folder or what.


Looks like there is some funkiness going on with NPM.

**Comment by magicdiven** [comment]
So, how to resolve this error？
My version is 1.4.7 and I use Mac OS X
