### ISSUE TITLE
ExecuteJavascript on Webview from Main Process

### ISSUE THREAD

**Issue by steamypassion** [electron/electron#13996]
**Describe the solution you'd like**
Awkwards for escaping JavaScript. Would like able to do this from Main Script rather than preload or script tags.

```
const previousWindow = BrowserWindow.getFocusedWindow();
previousWindow.webContents.executeJavaScript("document.getElementById('webview').executeJavaScript('console.log(window.innerHeight)')")
```

**Describe alternatives you've considered**
I had try setTimeout and did-finish-load, but both does not able to immediately capture the webview. The webview is simple just static, use disablewebsecurity because would like to access file:/// instead of http server which might increase 5-20MB memory footprint (I no so sure, but i guess is footprint from express etc). 
```
<webview id="webview" src="externalPage.html" class="external_webview" autosize disableguestresize disablewebsecurity></webview>
```
```
setTimeout(function(){
    var z = webContents.getAllWebContents()

    z.forEach(function(webview) {
        if(webview.history != undefined){
            if(webview.history.length <= 1){
                if(webview.history[0].indexOf('externalPage.html') > 0){
                    webview.webContents.executeJavaScript(`testFunction(${JSON.stringify(zoidParameters)})`)
                }
            }
        }else{
            console.log("no webview")
        }
    });
}, 5000)
```

**Additional context**
It could be me too stupid to grasp fully from documentation. I would like to passing JSON through Main function like below. To do this, JSON escaping might be too a bit trouble to work with.

```
const previousWindow = BrowserWindow.getFocusedWindow();
previousWindow.webContents.executeJavaScript("document.getElementById('webview').executeJavaScript('console.log(window.innerHeight)')")
```

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
