### ISSUE TITLE
Don't have the format description of the webview's webpreferences defaultFontFamily

### ISSUE THREAD

**Issue by jasonzhu92** [electron/electron#13995]
like this:
`<webview src="https://github.com" webpreferences="allowRunningInsecureContent, javascript=no"></webview>`
and defaultFontFamily property has its options.
how can I write the property to webview's webpreferences.
I konw:
```
let home = new BrowserWindow({ width:1920, height:1080,webPreferences: {
     defaultFontFamily:{standard:"Microsoft YaHei"}
     }})
```
but how can I use string to describe it in webview?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
