### ISSUE TITLE
Rendering Issue

### ISSUE THREAD

**Issue by jakewtaylor** [electron/electron#14002]
* Electron Version: 2.0.7
* Operating System (Platform and Version): OSX 10.11.6
* Last known working Electron version: N/A

**Expected Behavior**
The app to render normally.

**Actual behavior**
Text renders strangely, especially when scrolling, see the screenshot below. Note the text overlapping at the end of the JWT `iss` claim and the multiple closed brackets after the timestamps.

**To Reproduce**
Repository at [jakewtaylor/jwt-inspector](https://github.com/jakewtaylor/jwt-inspector), install commands are in `readme.md`.

**Screenshots**
![screen shot 2018-08-09 at 16 45 55](https://user-images.githubusercontent.com/8126758/43910293-50bf9f58-9bf4-11e8-8392-ee84e4c742e8.png)

**Additional Information**
Not really sure what the problem is here. I expect its a bug with electron as this was a fresh app, and the problem was happening from the get go. The app renders fine within a browser.

I haven't had the chance to try this on another computer, so it could well be my mac causing problems.

Thanks!

**Comment by ckerr** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unneccessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you've responded, please link to the test case and @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by jakewtaylor** [comment]
Hi @ckerr,

I'm getting the same problem from electron-quick-start: Fonts render strangely, text selection is buggy:

![screen shot 2018-08-10 at 08 57 04](https://user-images.githubusercontent.com/8126758/43945884-7b1fede8-9c7b-11e8-9a7b-559ecb990f69.png)

Hope this helps

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
