### ISSUE TITLE
Notifications hang entire process for few minutes if no notification daemon is running

### ISSUE THREAD

**Issue by akontsevich** [electron/electron#14006]
* Electron Version: 1.8.x - 2.x
* Operating System (Platform and Version): Linux

**Decription**
Forced to disable notifications in Linux cause it hang Electron applications: Riot, Skype, etc. Installing `Dunst` as suggested in #7831 seems does not block an application, however notification is very small in the screen and not very convenient.

**Comment by ckerr** [comment]
@jhgg had a [suggestion](https://github.com/electron/electron/issues/7831#issuecomment-403655937) that seems plausible:

> Noticed this issue too on linux. The repro steps are pretty simple. If you are using a desktop environment without anything that is accepting libnotify notifications (in my case, minimal i3, no notification-daemon or dunst running). I think this happens because https://github.com/electron/electron/blob/master/brightray/browser/linux/libnotify_notification.cc#L141 can block if no notification daemon is running to accept the request.
>
> notify_notification_show eventually calls g_dbus_proxy_call_sync within libnotify... which yeah... blocks.

**Comment by chrissnell** [comment]
This problem happens to me _even when_ a notification daemon is running. I'm running dunst (launched by systemd) and it still happens.  Restarting the dunst service doesn't fix it, either.  This happens to me with Slack and Mattermost.  

I've noticed that it happens most frequently when my laptop is closed and then re-opened.   I have no proof behind this but my hunch is that a socket to dbus/notification daemon/whatever is being opened and then when the computer is suspended and unsuspended, the socket is never closed and re-opened, causing timeouts and the hang.

**Comment by marconn** [comment]
Just willing to provide some info. This has happened to me while using various electron applications (Wavebox, Rambox, Slack, Telegram) in KDE (Kubuntu), mostly when receiving two or more notifications at (almost) the same time. 
However, while using these applications under Xfce (Xubuntu), notifications work properly. The application doesn't hang.

**Comment by marconn** [comment]
Just willing to provide some info. This has happened to me while using various electron applications (Wavebox, Rambox, Slack, Telegram) in KDE (Kubuntu), mostly when receiving two or more notifications at (almost) the same time. 
However, while using these applications under Xfce (Xubuntu), notifications work properly. The application doesn't hang.

**Comment by marconn** [comment]
Just willing to provide some info. This has happened to me while using various electron applications (Wavebox, Rambox, Slack, Telegram) in KDE (Kubuntu), mostly when receiving two or more notifications at (almost) the same time. 
However, while using these applications under Xfce (Xubuntu), notifications work properly. The application doesn't hang.

**Comment by hobbs** [comment]
@marconn did you find a solution for the apps freezing on KDE?

**Comment by paco3346** [comment]
Came here from https://github.com/ramboxapp/community-edition/issues/515

I'm running Rambox with Slack (amongst other services) and have these same issues. On Arch w/ KDE plasma (not running dunst) the lock ups are very intermittent and affect my entire window manager, not just the electron app. I too have noticed that it seems to be when there are multiple notifications coming in as @marconn noted.

I'll be trying to find a way to reliably recreate the issue.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by blargle-ragequit** [comment]
I have the issue with electron 6.0.1 on Arch Linux.  It causes Caprine (a FB Messenger app) to hang for minutes at a time and delays input by about as much permanently if no notify daemon is running.  I had to turn notifications back on in KDE to fix it.

**Comment by heronhaye** [comment]
Yes, this is still a bug on 6.0.1.

**Comment by NukeManDan** [comment]
@sofianguy - I also am having this happen for https://keybase.io on XFCE Manjaro 

with a daemon, it works, but without, it hangs.

https://forum.manjaro.org/t/xfce-settings-notifications-issues/71240

**Comment by heronhaye** [comment]
@sofianguy can we reopen this issue?

**Comment by vhladiienko** [comment]
@sofianguy @ckerr This is still relevant for at least Electron 4.2.1, which is the latest Electron version used by Slack that I could find - Slack 3.4.2 to be precise. We're at 4.2 now and I still have the same issues in KDE Plasma.

Can this be revisited, please?
