### ISSUE TITLE
when index.html has a require, loading multiple instances is slow

### ISSUE THREAD

**Issue by starpit** [electron/electron#14007]
* Electron Version:2.0.7
* Operating System (Platform and Version):macOS 10.13.6
* Last known working Electron version: 1.8.7 has the correct behavior! 3.0.0-beta4 shows the same poor behavior of 2.0.x

**Expected Behavior**

When index.html has a `require` statement, loading multiple electron processes should be equally responsive for each process.

**Actual behavior**

When index.html does have a `require` statement, the second and subsequent processes launched (while the first is still alive) pause 3-4 seconds with a gray screen before they start to load the HTML content. I've narrowed this down to the `require` in index.html. With it, the problem exists; without it, it does not --- keeping everything else the same.

3.0.0-beta.4 exhibits the same problem
1.8.7 does **not**, i.e. it seems healthy in this regard

**To Reproduce**
https://github.com/starpit/electron-quick-start/tree/require-multi-slow

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone https://github.com/starpit/electron-quick-start -b require-multi-slow
$ npm install
$ npm start &
$ npm start
```

the second one will spend 3-4 seconds with a gray screen, and finally show the Hello World content. If you remove the `require('debug')` line from index.html, the second start with be as fast as the first.

**Screenshots**

here is a video showing the problem:
https://ibm.box.com/s/yejpyviznpn6sy0s0mfhnz1x7hkv8q0w

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by starpit** [comment]
thanks for checking in. we have since found a way to work around this bug. you can close it, if needed. it's still a bug, but maybe this and other threads can help others work around the bug in the future.

**Comment by sofianguy** [comment]
Thank you @starpit. I am going to close this for now, but we would be happy to reopen if others find this bug in later versions.

**Comment by jjtfsalgado** [comment]
I'm having the same issue using v6.0.10. @starpit may I ask you what was the solution?
