### ISSUE TITLE
Navigate to file when link is clicked in the console?

### ISSUE THREAD

**Issue by Glinkis** [electron/electron#14013]
I'm working on an app that indexes images, and when debugging I am logging the original file paths to the console as a file url.

![screen shot 2018-08-10 at 13 28 26](https://user-images.githubusercontent.com/8037927/43955743-d0d1ab84-9ca1-11e8-8703-6242ab9f6171.png)

I would love if I was able to navigate to the files when the clicking on the links, as I currently have to navigate to each file manually.

**Comment by Kthulu120** [comment]
@Glinkis Could you possibly extrapolate? Do you mean when you click on the file path of some file you want it to open in the `Sources` Panel or do you mean when debugging in the terminal when you click on a file path you want the file to be automatically opened? Just tryig to make sure I understand the issue fully.

**Comment by Kthulu120** [comment]
This is a nice idea, but this is outside the scope of electron. Therefore, I will add the label status/wontfix to this.

**Comment by Glinkis** [comment]
Should I suggest this feature for Chrome then?
