### ISSUE TITLE
Getting high accuracy time in render process.

### ISSUE THREAD

**Issue by Losses** [electron/electron#14014]
https://bugs.chromium.org/p/chromium/issues/detail?id=506723

Based on this page, the accuracy of performance.now may be influenced by the patch, is it still possible to get high accuracy time in render process?

**Comment by ckerr** [comment]
GitHub issues are for feature requests and bug reports. Questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
