### ISSUE TITLE
Overwriting Accelerator of Role in MenuItem Doesn't Work on Windows

### ISSUE THREAD

**Issue by jasontlouro** [electron/electron#14028]
* Electron Version: 2.0.5
* Operating System (Platform and Version): Windows 10 Home Version 1803
* Last known working Electron version: ?

**Expected Behavior**
The following Edit Menu should cause CmdOrCtrl+V to perform a Paste and Match Style:

{
	 label: 'Edit',
         submenu: [
		 { role: 'undo' },
		 { role: 'redo' },
		 { type: 'separator' },
		 { role: 'cut' },
		 { role: 'copy' },
		 { role: 'pasteandmatchstyle',
		      accelerator: 'CmdOrCtrl+V'},
		 { role: 'selectall' }
        ]
 }

**Actual behavior**
This works on Mac, but on Windows, 'CmdOrCtrl+V' does nothing and 'Shift+CmdOrCtrl+V' does a Paste and Match Style.

**To Reproduce**
Paste that menu into the template of Menu.buildFromTemplate() in any electron app.

**Comment by ckerr** [comment]
Thanks for filing this issue!

I think you need to use `globalShortcut` for that -- see https://electronjs.org/docs/api/accelerator for more information.

If you have more questions, check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
