### ISSUE TITLE
Docs should mention primitive JS value types instead of object wrappers

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#14023]
* Electron Version: Probably all
* Operating System (Platform and Version): All
* Last known working Electron version: N/A

**Additional Information**
All over the documentation JavaScript object wrapper types are used to specify types of parameters and return values of various API methods, e.g. `Number` or `String`, see [docs/api/app.md](https://github.com/electron/electron/blob/master/docs/api/app.md) for tons of examples. [The documentation styleguide](https://github.com/electron/electron/blob/master/docs/styleguide.md#methods) has links to those wrapper "classes" descriptions on MDN.

The problem is that [actually](https://i.kym-cdn.com/entries/icons/facebook/000/021/665/DpQ9YJl.jpg) API works with [primitive values](https://developer.mozilla.org/en-US/docs/Glossary/Primitive) and not object wrappers for those primitives. There is a subtle but important differences between, the most notable being one how `typeof` operator works:
```js
const primitiveString = 'hello';
typeof primitiveString;  // 'string'

const objectString = new String('hello');
typeof objectString;  // 'object'
```

**Comment by Kthulu120** [comment]
@alexeykuzmin so essentially should the docs be update to include the fact that a given parameter also takes a primitive string?
For Example

#### What the docs are
### `app.setUserActivity(type, userInfo[, webpageURL])` _macOS_

* `type` String - Uniquely identifies the activity. Maps to
  [`NSUserActivity.activityType`][activity-type].
* `userInfo` Object - App-specific state to store for use by another device.

#### What the docs should become
### `app.setUserActivity(type, userInfo[, webpageURL])` _macOS_

* `type` String/string - Uniquely identifies the activity. Maps to
  [`NSUserActivity.activityType`][activity-type].
* `userInfo` Object - App-specific state to store for use by another device.
* `webpageURL` String/string (optional) - The webpage to load in a browser if no suitable app is
  installed on the resuming device. The scheme must be `http` or `https`.

**Comment by MarshallOfSound** [comment]
@Kthulu120 We should only use the lowercase option, they take primitives, not the object types.

**Comment by CTSalinas** [comment]
Hi! I'm fairly new to GitHub and I was wondering if I could work on this.

**Comment by divyanshu97** [comment]
Hello, I am new to Open Source and want to work on this issue.
Please guide me.

**Comment by yagnyaPatel** [comment]
Hey, I'd like to work on this. If someone is already working on this, I'm willing to split the work. Otherwise, I can take it all on.

**Comment by COlson28** [comment]
Hello, I would like to work on this problem as well. From kartik's efforts, I understand that all files in the docs/api folder should be edited. Is there another location as well that may contain more files? 

I am new to github and Electron, so any guidance would be appreciated.

**Comment by MarshallOfSound** [comment]
@COlson28 Only the files in `docs/api` are the ones that need updating here 👍

**Comment by co16353sidak** [comment]
Seems like this issue hasn't been worked on for some days, is anyone still working on this or could I have a go?

**Comment by maniac-tech** [comment]
Is there any update on the Issue @alexeykuzmin ?

**Comment by ryanomor** [comment]
Opened PRs [20452](https://github.com/electron/electron/pull/20452) and [20453](https://github.com/electron/electron/pull/20453) for this issue.

But it looks like a few of the tests are failing. Not sure why

**Comment by infinity052** [comment]
Hi! I've just created a pull request that I believe may be the fix to this. Please check. #25786
