### ISSUE TITLE
document.querySelectorAll(':not(:defined)') 

### ISSUE THREAD

**Issue by fish520** [electron/electron#14033]
* Electron Version: 3.0.0-beta.4
* Operating System (Platform and Version): windows10 x64
* Last known working Electron version:  3.0.0-beta.4

**Expected Behavior**

It was just a test code in my project that executed before DOMContentLoaded, the code is much like:

```
let customTagArr = []
let undefinedElements = document.querySelectorAll(':not(:defined)')
console.log(undefinedElements)  

let promises = [...undefinedElements].map(element => {
  customTagArr.push(element.localName)
  return customElements.whenDefined(element.localName).then(() => element.localName)
})
// more ...
```

the `undefinedElements` was expected to include no html standard elements,.

**Actual behavior**

I saw some div elements which was slotted in a custom element, just like

```<my-tag><div id="test"></div></my-tag>```

then the `div#file` was matched by the `:not(:defined)` selector.

Thus calling `customElements.whenDefined(element.localName)` may result in the following error:
```
Uncaught (in promise) DOMException: Failed to execute 'whenDefined' on 'CustomElementRegistry':  
"div" is not a valid custom element name
```

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
