### ISSUE TITLE
BrowserViews sometimes don't recieve mouse events

### ISSUE THREAD

**Issue by PalmerAL** [electron/electron#14038]
* Electron Version: 2.0.0-beta.5 (and all later versions)
* Operating System (Platform and Version): macOS 10.13.5
* Last known working Electron version: 2.0.0-beta.4

**Expected Behavior**

Dragging inside a BrowserView shouldn't cause the window to move.

**Actual behavior**

Sometimes, dragging inside a BrowserView causes the window to move.

**To Reproduce**

I don't have an exact way to reproduce this, but in our app, we have multiple BrowserViews that we switch between. When we initially create them, we call setBounds(), but don't attach them to the window. Then, when we want them to be visible, we call setBrowserView() and then setBounds() again. Sometimes, this works correctly, and the mouse events are sent to the BrowserView, but occasionally it seems like the whole BrowserView is acting as a window drag region instead.

**Screenshots**

[browserview.gif](https://user-images.githubusercontent.com/10314059/44003994-0f8c9ea8-9e21-11e8-961d-fe61c75918d3.gif)

**Additional Information**

Given the timeframe, I think this a regression from #12348. I believe what's happening is that when setBrowserView is called, the drag regions are updated, but the area of the browserView isn't considered an <a href="https://github.com/electron/electron/blob/12a57ff1c25578c56a9b8694e53cd5e539e052a6/atom/browser/native_browser_view_mac.mm#L213">exclusion zone</a>, so the entire window is marked as being draggable. (I think it might be possible for the area of the BrowserView to still be 0x0px at this point - I've seen issues before where calling setBounds() doesn't do anything when the view is hidden). Then, we call setBounds() again, which causes the view to expand to fill the entire window, but updateDraggableRegions is never called again, so the whole window is still considered draggable.

If I resize the window, the dragging behavior works again - I expect because <a href="https://github.com/electron/electron/blob/9f328abe19186af292eea3757ac908bc793a987c/atom/browser/api/atom_api_browser_window.cc#L270">this code</a> updates the drag regions whenever the window is resized.

I expect the fix for this is to call updateDraggableRegions whenever the view bounds are changed (and I think it makes sense to do that anyway, considering that the drag regions are already updated whenever the view itself switches), but I don't understand how the window code works well enough to know how to do this.

**Comment by ckerr** [comment]
Do you mean `3.0.0-beta.5` and `3.0.0-beta.4`?

**Comment by PalmerAL** [comment]
@ckerr No, this is happening in both Electron 2 and 3 (our app was using 2.0 beta 4, and we haven't tried to upgrade to a later version until now). #12348 was originally aded in 3.0, but it was backported to 2.0beta5 as well.

**Comment by jgarces-tw** [comment]
Same happens to me
I have a window (OSX) where the fake title is set to be draggable and underneath a BrowserView.
- If the browserview is not resized (via setBounds) or not present then the top title bar works correctly when the window is resized, it's height stuck at 24px as defined by the style
- When the browserview is present and resized via setBounds then *when the size is increased* the top part of the browser window starts to be draggable
- When the window is resized to be smaller then that draggable part of the browser window is gone.

**Comment by jgarces-tw** [comment]
The weird part is that if a gap is left between the draggable title bar and the browserwindow that gap won't be draggable. It is as if the browserwindow was inheriting the draggable zone from the parent window somehow.

**Comment by jgarces-tw** [comment]
I found an ugly workaround:
- update the browser view bounds
- set the window browser view to null
- set the browser view again into the window

**Comment by jgarces-tw** [comment]
@poiru any ideas?

**Comment by PalmerAL** [comment]
I eventually ended up using this workaround: https://github.com/minbrowser/min/blob/master/js/webviews.js#L30

It seems to break occasionally, though, so it would be good to see a proper fix for this issue.

**Comment by ccnokes** [comment]
I'm seeing this in v4.1.2 too.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
