### ISSUE TITLE
Angular6+SVG not update View automatic in electron

### ISSUE THREAD

**Issue by hushunding** [electron/electron#14037]
* Electron version: 2.0.3
* Operating system: windows 10

* Last known working Electron version: n/a

### Actual behavior
 I use attribute bind way to change the attribute of SVG element , ex .fill。but the view well not update until change the other thing ，like resize the windows，change the viewbox/element number that are also through data bind way. I see the html through dev tools, the html also not change,unless i do same  thing else.
 the same code can work normal on chrome 67, edge

### How to reproduce
target app
[app.zip](https://github.com/electron/electron/files/2280946/app.zip)
source 
[SVGTest.zip](https://github.com/electron/electron/files/2280947/SVGTest.zip)

**Comment by MarshallOfSound** [comment]
@hushunding Can you test the latest `3.0.0-beta.12`?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by hushunding** [comment]
Thank you for your attion.
before close this issue i want to add new infonatiom.
after this case , I find there is some promblem for SharedWorker in chrome. 
there is some miss in zone.js, so the data update by SharedWorker.onmessage can not determine  by zone some the data is not update.
easy  way to check  whether  zone.js patch the event handler is debug and break event  handle function. if the context is normal means the not patched, normally is in zone.js context. and i fix the problem with patch the event manually in polyfill. the code show:
`
import 'zone.js/dist/zone';  // Included with Angular CLI.
(window as any).Zone.__load_patch('EventTargetPatch', (global: any, Zone: any, api: any) => {
    const apis = [];
    api.patchOnProperties((window as any).MessagePort.prototype,['message','error'])
    api.patchOnProperties((window as any).SharedWorker.prototype,['error'])
});
`

**Comment by hushunding** [comment]
contiue
I think  there is something  make the zone.js is not work for webworker in Electron 
I compare the stack, **Chome 76.0.3809.100** And **Electron 6.0.0**
**worker.onmessage stack** in **Electron** 
`
DataService.worker.onmessage (data.service.ts:57)
postMessage (async)
Sendrandom (ranData.js:16)
setTimeout (async)
`
**worker.onmessage stack** in **Chrome**
`
DataService.worker.onmessage (data.service.ts:57)
wrapFn (zone.js:1188)
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
onInvokeTask (core.js:4607)
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (zone.js:496)
invokeTask (zone.js:1540)
globalZoneAwareCallback (zone.js:1566)
postMessage (async)
Sendrandom (ranData.js:16)
setTimeout (async)` 

normal Angular Event on ELectron 
`
set scale (svg-test.component.ts:28)
(anonymous) (SvgTestComponent.html:2)
handleEvent (core.js:12878)
callWithDebugContext (core.js:14453)
debugHandleEvent (core.js:14064)
dispatchEvent (core.js:9294)
(anonymous) (core.js:11571)
schedulerFn (core.js:4318)
__tryOrUnsub (Subscriber.js:186)
next (Subscriber.js:125)
_next (Subscriber.js:73)
next (Subscriber.js:50)
next (Subject.js:39)
emit (core.js:4286)
viewToModelUpdate (forms.js:4716)
updateControl (forms.js:2086)
(anonymous) (forms.js:2060)
setValue (antd.js:21870)
setActiveValue (antd.js:22019)
onDragMove (antd.js:22077)
__tryOrUnsub (Subscriber.js:186)
next (Subscriber.js:125)
_next (Subscriber.js:73)
next (Subscriber.js:50)
notifyNext (mergeMap.js:64)
_next (InnerSubscriber.js:11)
next (Subscriber.js:50)
_next (Subscriber.js:73)
next (Subscriber.js:50)
_next (distinctUntilChanged.js:49)
next (Subscriber.js:50)
_next (map.js:35)
next (Subscriber.js:50)
_next (distinctUntilChanged.js:49)
next (Subscriber.js:50)
_next (map.js:35)
next (Subscriber.js:50)
_next (tap.js:46)
next (Subscriber.js:50)
_next (filter.js:33)
next (Subscriber.js:50)
handler (fromEvent.js:20)
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
onInvokeTask (core.js:4607)
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (zone.js:496)
invokeTask (zone.js:1540)
globalZoneAwareCallback (zone.js:1566)
`

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
