### ISSUE TITLE
ELECTRON_CACHE environment variable in documentation is wrong

### ISSUE THREAD

**Issue by rhyst** [electron/electron#14047]
* Electron Version: 2.0.7
* Operating System (Platform and Version): Windows 7 64 bit
* Last known working Electron version: 

**Expected Behavior**
Documentation for installing electron without internet connection should be correct. The environment variable to set is "ELECTRON_CONFIG_CACHE".

**Actual behavior**
The documentation lists "ELECTRON_CACHE" as the environment variable to set to get the electron installer to look for a local electron binaries. Setting this environment variable does nothing and the installer makes a network request.

**To Reproduce**
* Start new npm project
* Place electron binaries in non-default cache folder
* Set ELECTRON_CACHE to point to that folder
* Add electron 2.0.7 to package.json
* Run `npm install` / `yarn` 
* Observe that it makes a network request
* Set ELECTRON_CONFIG_CACHE to point to binaries
* Run `npm install` / `yarn` 
* Observe that it installs using offline binaries

**Additional Information**
Either the documentation should be updated to refer to "ELECTRON_CONFIG_CACHE" or the installer should be updated to use "ELECTRON_CACHE".

**Comment by MarshallOfSound** [comment]
@rhyst The issue here is the variable name changed between Electron 2.0.0 and 3.0.0.

See the latest `electron-download` [sources](https://github.com/electron-userland/electron-download/blob/master/lib/index.js#L70).  The latest `electron` release will respect `ELECTRON_CACHE`
