### ISSUE TITLE
BUG: Web Bluetooth API broken on macOS

### ISSUE THREAD

**Issue by oliverdunk** [electron/electron#14050]
* Electron Version: 2.0.7
* Operating System (Platform and Version): macOS High Sierra
* Last known working Electron version: NA

**Expected Behavior**
The `navigator.bluetooth` API can be used throughout Electron, in the same way as in Chrome.

**Actual behavior**
An error is thrown when a search for devices begins:
> Exception NSInvalidArgumentException thrown while decoding IOBluetoothSDPServiceRecord

**To Reproduce**
See steps at https://github.com/electron/electron/issues/10959

**Additional Information**
I'm opening a new issue because the previous issue has been closed for a long time. Lots of users are still experiencing this and it is easily reproducible.

**Comment by oliverdunk** [comment]
@sofianguy Any news on this?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by oliverdunk** [comment]
Confirmed as fixed :)
