### ISSUE TITLE
PowerSaveBlocker does not work the same as the document described. (in Windows 10)

### ISSUE THREAD

**Issue by 1ntegrale9** [electron/electron#14064]
* Electron Version: Electron 2.0.0
* Operating System (Platform and Version): Windows 10
* Last known working Electron version: NA

**Expected Behavior**
The computer does not turn off display or sleep.

**Actual behavior**
The computer sleeps after 3 minutes.

**To Reproduce**
```sh
$ git clone git@github.com:1ntegrale9/electron-quick-start.git
$ npm install
$ npm start || electron .
```

1. Set computer to turn off display in 1 minute, and to sleep in 3 minutes.
2. Use `electron.powerSaveBlocker.start('prevent-app-suspension')`
3. Start the application, and wait more than 3 minutes.

**Screenshots**
Screenshots are not necessary.
It is impossible to report as a screenshot.

**Additional Information**
#12345 is a report of the same problem.
However, the version of Electron is different.

The same phenomenon does not occur in MacOS High Sierra (v10.13.6).
It operates normally.

**Comment by sofianguy** [comment]
please follow https://github.com/electron/electron/issues/12345 for updates
