### ISSUE TITLE
The HTML5 notification API failed with local webpage on 3.0.X

### ISSUE THREAD

**Issue by eric8810** [electron/electron#14075]
* Electron Version:3.0.5
* Operating System (Platform and Version):MacOS 10.13.6
* Last known working Electron version: 2.0.7

**Expected Behavior**
The HTML5 notification API work well with local webpage.

**Actual behavior**
When request HTML5 notification API permission, it returns granted.
But after that, when I start a new notification, all permission set back to denied and the notification failed.

**To Reproduce**
```sh
git clone https://github.com/VishwasShashidhar/electron-quick-start.git -b  notifications-3beta
npm install
npm start
```
or just simply run on your beta 3.0.X renderer console
```javascript
Notification.requestPermission(function (permission) {
                  // If the user accepts, let's create a notification
                  console.log(permission)
                  if (permission === "granted") {
                      var notification = new Notification("Hi there!");
                  }
              });
```
**Screenshots**
![image](https://user-images.githubusercontent.com/756579/44089750-892131e0-9ffa-11e8-8062-2517d82bf519.png)

**Comment by MarshallOfSound** [comment]
This is the web platform working as intended, if you want to use notifications you need to either use the `file://` protocol, a custom protocol or the `https://` protocol.  If you are loading remote content into Electron anyway you should **definitely** be using `https`

**Comment by eric8810** [comment]
@MarshallOfSound I did load the page with "file://" protocol, yet the API still not working

![image](https://user-images.githubusercontent.com/756579/44183829-2aed3380-a13f-11e8-98ab-45b0fa110051.png)

**Comment by zheung** [comment]
@MarshallOfSound the API not working with `https` too!
- my https site
- `granted`
- either `onclick` in webpage or `run in console` not working 

![image](https://user-images.githubusercontent.com/894004/45789199-fd9d2380-bcb0-11e8-8313-fc1c889db634.png)
