### ISSUE TITLE
Electron CLI documentation is incomplete or misleading

### ISSUE THREAD

**Issue by peterjwest** [electron/electron#14076]
The [CLI help message](https://github.com/electron/electron/blob/c8030a0f2aaf299f823f8a7dc68e29e69abb102f/default_app/main.js#L346) indicates the various options that are available for running electron. However it does not mention the quite different modes of operation which come from these options.

It seems like _only_ if you provide a directory which contains a package.json will electron set the app path (among other things) which seems pretty essential for locally referenced files to work correctly.

I'd like this documentation to be made more clear - it doesn't currently indicate that a package.json is important at all, but I don't see any alternative options to set the app path.

I haven't managed to find detailed documentation about this anywhere else, but would be satisfied if there is some!

**Comment by ManuelTheDev** [comment]
Hello, I am quite new to contributing to Open Source Projects and I'm looking forward to begin somewhere. Coud I take this issue?

**Comment by dinaelhanan** [comment]
working on this!

**Comment by dinaelhanan** [comment]
>=only if you provide a directory which contains a package.json will electron set the app path (among other things) which [is] pretty essential for locally referenced files to work correctly.=
> 
Should I add this to the docs or....? I can't find much about the different modes of operation either, at least not enough to add to the docs. I'll keep trying though!

**Comment by peterjwest** [comment]
I only found this by testing and digging through the code, but I don't know enough to confidently write docs

**Comment by dinaelhanan** [comment]
me neither :( hopefully someone does because this is important @peterjwest

**Comment by HaNdTriX** [comment]
Thanks for opening this issue. I believe we should add some more light into the dark here.
Afaik electron starts the default app in many different ways:

## index.js

**Comment by HaNdTriX** [comment]
> Disclaimer: I am new to electron

Thanks for opening this issue. I believe we should add some more light into the dark here.
Afaik electron starts the default app in many different ways:

## Electron Start Modes

### 1. Render Mode

In this mode electron created a `BrowserWindow` and loads the passed url.

**Allowed Protocols:** `http:`, `https:`, `file:`, `chrome:`, `<localFilesystem>.html`, `<localFilesystem>.htm`
**Example:** `$ electron http://example.com/`


### 2. Package Mode

If you pass in a directory with a `package.json`.

**Example:** `$ electron main.js` (with a `package.json` in same directory)

Electron uses the `package.json` to:

* Set the app Version
* Set the appName
* Set the userData directory path
* Set the userCache directory path
* Set the app path

The above settings are necessary to use apis like `app.getAppPath()` and many more!

### 2. File Mode

**Example:** `$ electron main.js` (without a `package.json` in same directory)

This mode is critical in my opinion. If you just pass a file that is in a directory without a `package.json` the app starts but doesn't set the above settings. This means many apis won't work properly (e.g.:`app.getAppPath()`).

This has caused a lot of confusion in the community:

* https://github.com/electron-userland/electron-webpack/issues/243
* https://github.com/electron-userland/electron-webpack/pull/242
* https://github.com/electron-userland/electron-webpack/issues/239
* https://github.com/electron-userland/electron-forge/issues/346
* https://github.com/electron-userland/electron-prebuilt-compile/pull/51

We may want to document the caveheats of using this approach.

**Comment by vikramsubramanian** [comment]
I would like to pick this up! Is someone still on it?

**Comment by peterjwest** [comment]
It's been over a year, probably safe to go ahead!

**Comment by KrKeshav09** [comment]
I am  a complete begginer with this stuff could you help me to contribute in this project

**Comment by kingaraize** [comment]
Like wise

**Comment by Kemal48** [comment]
![image](https://user-images.githubusercontent.com/47145614/108639649-55ea3800-749e-11eb-81c2-e80db6679373.jpeg)

**Comment by navitux** [comment]
hello, Is this issue still open ? 
I want to work on it

**Comment by Ciberusps** [comment]
Hey @HaNdTriX that issue still exists and continue to mislead many devlopers as me. Even at big examples like [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate) such mistakes exists and many developers frustraited of it. Like dozens of issues created in different electron-related repos some of them:

### Exactly related
- https://github.com/sindresorhus/electron-store/issues/142
- https://github.com/sindresorhus/electron-store/pull/143
- https://github.com/sindresorhus/electron-store/issues/205
- https://github.com/sindresorhus/electron-store/pull/162
- https://github.com/electron/electron/issues/7085
- https://github.com/sindresorhus/electron-store/issues/108
- https://github.com/sindresorhus/electron-store/issues/123
- https://github.com/electron-userland/electron-webpack/issues/353
...

### Probably related
- https://github.com/electron/electron/issues/24472
- https://github.com/GitbookIO/nuts/issues/164
- https://github.com/vercel/hazel/issues/63
...

I'm sure that at least when electron starts up with behaviour other than "package mode" it should write up in terminal something like:
```
[WARNING] your electron app launched in "File Mode" in most cases thats not what you want.

Some electron api's might be "broken" and return things that you dont expect - app.getAppPath, app.getPath,
app.getFileIcon, app.getVersion, app.getName.

To fix it in package.json replace "electron ./path/to/something.ts" on "electron ." and in package.json 
create field "main" "./path/to/something.js"
```
