### ISSUE TITLE
draging text will lead no response

### ISSUE THREAD

**Issue by hzhangxyz** [electron/electron#14073]
* Electron Version: 2.0.7
* Operating System (Platform and Version): archlinux
* Last known working Electron version: 1.8.4

**Expected Behavior**
open `electron` select some text and drag it to somewhere else, nothing happened is expected

**Actual behavior**
electron will not response any more

**Screenshots**
![image](https://user-images.githubusercontent.com/11623447/44087282-edbef672-9ff1-11e8-8409-4b734c48c900.png)

**Additional Information**
c-ares 1.14.0-1
ffmpeg 1:4.0.2-1
gtk3 3.22.30-1
http-parser 2.8.1-1
libevent 2.1.8-1
libvpx 1.7.0-1
libxslt 1.1.32+3+g32c88216-1
libxss 1.2.2-3
minizip 1:1.2.11-3
nss 3.38-1
re2 20180801-1
snappy 1.1.7-1

**Comment by bpasero** [comment]
@hzhangxyz does it reproduce with Electron 3.0.x as well?

**Comment by hzhangxyz** [comment]
btw, the black bar will stay the top of the screen until i close electron by ctrl+C, even focus to other window.
![image](https://user-images.githubusercontent.com/11623447/44126861-26da56e2-a06d-11e8-91ff-6489beebb940.png)

**Comment by bpasero** [comment]
@hzhangxyz do you get any output in the console when you run Electron from there and follow these steps?

**Comment by hzhangxyz** [comment]
no console output
![image](https://user-images.githubusercontent.com/11623447/44132281-1ca1a8d8-a08b-11e8-8429-22ac407059b6.png)

**Comment by hzhangxyz** [comment]
select text in console will also lead to no response
![image](https://user-images.githubusercontent.com/11623447/44278021-43646780-a27f-11e8-8a74-6afd138d6e07.png)

**Comment by hzhangxyz** [comment]
but `optirun ./node_modules/electron/cli.js`(optirun means using nvidia gpu to run the gpu process of chromium) won't reproduce this bug.(Electron v2.0.7, Electron v3.0.0-beta.5, Electron v4.0.0-nightly.20180816 tested, and all of they will reproduce without optirun)

**Comment by hzhangxyz** [comment]
run `electron` normally without any other parameter, and kill process `electron --type=gpu-process ...` three times to avoid being respawned by parent process
![image](https://user-images.githubusercontent.com/11623447/44279204-1ca83000-a283-11e8-919f-7d687b8a7406.png)
then the electron works well. will not no response

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by hzhangxyz** [comment]
thank you, the problem solved after updating electron.
