### ISSUE TITLE
@electron/schematics

### ISSUE THREAD

**Issue by oleksiipotiekhin** [electron/electron#14088]
**Describe the solution you'd like:**
Is there a possibility to add **@electron/schematics** for angular? To use `ng add electron` or `ng add @electron/schematics` to combine electron and angular. It will improve integration experience.

**Comment by MarshallOfSound** [comment]
@oleksiipotiekhin This kind of thing would be implemented in userland, we don't normally implement anything framework specific.  If someone builds this though we can link it from our community docs to let people know it exists.
