### ISSUE TITLE
app.requestSingleInstanceLock() always returns "false" when app started by "electron ."

### ISSUE THREAD

**Issue by tncga** [electron/electron#14094]
* Electron Version: 3.0.0-beta.5
* NodeJs Version: v10.8.0 x64
* Operating System (Platform and Version): Windows 10, x64, 1709 / tr_TR
* Operating System (Platform and Version): **Windows 10, x64, 1803 / en_US (clean install)**

**Expected Behavior**
app.requestSingleInstanceLock() should return **true** when it is **the first instance**. 

**Actual behavior**
It always returns **false**.

**To Reproduce**
Use default _npm start_ script **electron .**.  
It will return always false unless I change it from "electron ." to "electron script.js" in package.json.

https://github.com/tncga/whats-up-darkness
```sh
$ git clone https://github.com/tncga/whats-up-darkness.git
$ cd whats-up-darkness
$ npm install
$ npm start
```

**Comment by MarshallOfSound** [comment]
@tncga You probably have a left over instance of the application running in the background of your machine.  Try a clean restart and it should clear itself up, I can't repro this with your code on my machine.

**Comment by tncga** [comment]
I tried but it didn't solve the problem. I will try on Linux and different Windows computer. It may releated to my Windows installation.

**Comment by tncga** [comment]
It works on Arch Linux, but not on Windows even if it is first launch after restart. Also, it does not work on my friend's Windows 10 pc.

**Comment by tncga** [comment]
I figured out what causes the problem. It is releated to **productName** value in **package.json**. 
`"productName": "What's up darkness?",` -> not working
`"productName": "What's up darkness",` -> working

productName value should not contain forbidden chars on OS (for windows: `< > : * ? " / \ |`).
