### ISSUE TITLE
Sign Electron App for Mac Appstore

### ISSUE THREAD

**Issue by CaveFire** [electron/electron#14090]
* Electron Version: 2.0.7 & 3.0.0 beta 5
* Operating System (Platform and Version): Mac OS X 10.13.6

**Expected Behavior**
The app should start normally after signing. It should also be able to be uploaded to the App Store via Apple's Application Loader

**Actual behavior**
The windows are empty. The background color is there, but the html file is not loaded. Also the Developer Console dosn´t open.

**To Reproduce**
I followed the following guide: https://github.com/electron/electron/blob/master/docs/tutorial/mac-app-store-submission-guide.md
In the "parent.plist" file I just added:
```plist
<key>com.apple.security.network.client</key>
<true/>
```

**Screenshots**
Before signing:
![bildschirmfoto 2018-08-14 um 21 06 23](https://user-images.githubusercontent.com/18068240/44112646-f622ef94-a005-11e8-804b-19d7cbe11692.png)

After signing:
![bildschirmfoto 2018-08-14 um 21 05 49](https://user-images.githubusercontent.com/18068240/44112663-fc31fbf0-a005-11e8-9207-810ec98a8e57.png)

**Additional Information**
Also I tried signig it with the "electron-osx-sign" package. But then the app don´t start.

**Comment by TheCaveFire** [comment]
I have just updated to electron version 3.0.0 beta 5, but without success.
Gradually, I am at a loss ...

**Comment by MarshallOfSound** [comment]
@TheCaveFire Are you signing / running this on a macOS VM by any chance?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
