### ISSUE TITLE
.sendActionToFirstResponder('about:') doesn't work

### ISSUE THREAD

**Issue by astoilkov** [electron/electron#14106]
**Expected Behavior**
The same thing as if you click the menu item which has the `role: about`.

**Actual behavior**
Nothing happens.

**To Reproduce**
```javascript
const electron = require('electron');

electron.app.setAboutPanelOptions({
  applicationName: 'App',
  applicationVersion: '1.0',
  copyright: 'Copyright (C) 2018'
});

electron.remote.Menu.sendActionToFirstResponder('about:');
```

**Comment by sofianguy** [comment]
What version of electron are you using and which operating system are you running on?

**Comment by astoilkov** [comment]
Electron: 2.0.0
Operating System: macOS High Sierra 10.13.6

**Comment by codebytere** [comment]
@astoilkov `setAboutPanelOptions` needs to be invoked from `electron.remote.app` not `electron.app`. The below code works just fine:

```
const electron = require('electron')

electron.remote.app.setAboutPanelOptions({
  applicationName: 'App',
  applicationVersion: '1.0',
  copyright: 'Copyright (C) 2018'
})

electron.remote.Menu.sendActionToFirstResponder('about:')
```

**Comment by VitaliiPyvovar** [comment]
remote is needed only to require other modules from inside a render process. In the main process you just get your modules directly from require('electron').

So how should I make it work in main process?
