### ISSUE TITLE
electron does not run, has no ouput, no error in Linux

### ISSUE THREAD

**Issue by iamlazynic** [electron/electron#14110]
* Electron version: 2.0.0, 2.0.1, ..., 2.0.7
* Operating system: Antergos (Arch Linux)
* Desktop Environment: KDE Plasma 5

### Expected behavior

Running `electron --version` should, at least, have some output.

### Actual behavior

Command `electron` does nothing but exiting with stauts 0, *no matter what argument is passed*.

### How to reproduce

1. Install antergos base system from iso then boot
2. `sudo pacman -S plasma konsole npm nodejs-lts-carbon sddm gconf`
3. `sudo systemctl enable sddm`
4. `echo "prefix=~/.npm_global" > ~/.npmrc`
5. Reboot and login to KDE then launch Konsole
6. `npm i -g electron`
7. `./.npm_global/bin/electron --version`

* It started acting like this about a week ago, and before that it works well (in the same DE same system). Then I installed the latest electron again but problem still exists.
* A very outdated project using `electron-prebuilt@0.37.7` in this same environment doesn't have this problem.

------

Sorry for the frequent editings (if you noticed). I reproduced this just now in a new VM and found that DE doesn't matter. After doing the 7 steps stated above, I installed different DEs (Gnome, lxqt) and problem exists.

**Comment by bpasero** [comment]
Likely https://github.com/electron/electron/issues/13972 ?

**Comment by iamlazynic** [comment]
@bpasero No, there is no error output in this case.

The problem was solved after I upgraded npm today (`6.3.0 -> 6.4.0`) although I have no clue about the reason behind.
