### ISSUE TITLE
Electron can't start without internet

### ISSUE THREAD

**Issue by aister** [electron/electron#14117]
* Electron Version: 2.0.6
* Operating System (Platform and Version): Win 10
* Last known working Electron version: 

**Expected Behavior**
Electron apps should start without any error

**Actual behavior**
running `electron .` gives me this error

```
dns.js:246
    this._handle = new ChannelWrap();
                   ^

Error: EFILE
    at new Resolver (dns.js:246:20)
    at dns.js:377:25
    at dns.js:431:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at net.js:45:13
    at net.js:1730:3
    at NativeModule.compile (bootstrap_node.js:606:7)
    at NativeModule.require (bootstrap_node.js:550:18)
    at internal/child_process.js:6:13
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```
even with deleting everything but the index.js, package.json and node_modules folder, it still doesn't work. And the packaged app (with electron-builder) doesn't even run.

I tried to update node to 10.8, even downgrade it to 9.0.0 where it is said to be fixed, nothing seems to fix it.

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).

**Comment by aister** [comment]
I'm sorry but how is this not a bug? Electron should start without internet, but here it throws error. It is unrelated to my app so it's not my code's problem.

**Comment by bpasero** [comment]
Could this be the same as https://github.com/electron/electron/issues/6437 ?

**Comment by aister** [comment]
most probably so, it recommends using a loopback router, but I can't ask every single users of my app to add that so it is not a plausible solution for me

**Comment by sullyj3** [comment]
@sofianguy This is a bug report, I've encountered the exact same issue. I'm running into it whilst trying to run https://github.com/onivim/oni offline. Please consider reopening.

**Comment by ckerr** [comment]
I agree that this issue was incorrectly closed as notabug, but since Ben's pointed out this is likely a dupe of another open bug, this discussion should continue in #6437.

**Comment by microwisesystem** [comment]
add  Microsoft loopback adapter
