### ISSUE TITLE
Check if website is malicious (for webview)

### ISSUE THREAD

**Issue by CreatorVilius** [electron/electron#14123]
> ### **Is your feature request related to a problem? Please describe.**
Not really.

> ### **Describe the solution you'd like**
Somehow get chromium malicious website list probably?

> ### **Describe alternatives you've considered**
Just put object of malicious websites of chromium in process.webview.malicious somehow

Because if you make browser, it's kinda dangerous for people who use it.

**Comment by MarshallOfSound** [comment]
> Because if you make browser, it's kinda dangerous for people who use it.

Making a browser in Electron is not a good idea, if you want to build a browser using an Electron-like technology I'd reccomend looking into the Electron fork [Muon](https://github.com/brave/muon) that powers [Brave](https://brave.com/)

As for this request to get a list of malicious websites, we don't have this information, I don't believe chromium has this information.  I think google has a service that Chrome uses to periodically fetch this list that they then use to filter network traffic.

I'd suggest reading through chromiums [safe browsing](https://www.chromium.org/developers/design-documents/safebrowsing) documentation for more information on this topic.
