### ISSUE TITLE
Latest electron sources are not able to be built on Windows anymore with Visual Studio 15.8.0

### ISSUE THREAD

**Issue by gribunin** [electron/electron#14128]
* Electron Version: master
* Operating System (Platform and Version): Windows 10

**Expected Behavior**
Must be succesfuly compiled and linked

**Actual behavior**
Fails when linking with V8.lib with the message that ""'v8.lib' was created with an older compiler"". Happens only with Release build, Debug build works Ok.

**To Reproduce**
Download and build Electron sources 

**Additional Information**
It seems that the build process is broken because of this commit:
https://github.com/electron/libchromiumcontent/commit/d6411e421b0b2f0105d274ac4e5c90dc979463ca

in electron/libchromiumcontent project

**Comment by MarshallOfSound** [comment]
Electron is currently built with Visual Studio 15.4 for compatibility reasons with Chromium / libcc.  You'll need to install this version if you want to build releases locally.

You can still build debug builds

**Comment by gribunin** [comment]
Worth to fix the documentation then (https://electronjs.org/docs/development/build-instructions-windows), it now says in requirements: "Visual Studio 2017 15.7.2 or higher"

**Comment by MarshallOfSound** [comment]
^^ Good catch
