### ISSUE TITLE
Webview doesn't do anything after window loaded

### ISSUE THREAD

**Issue by CreatorVilius** [electron/electron#14124]
* Electron Version: 2.0.0
* Operating System (Platform and Version): Windows 10
* Last known working Electron version: -

**Expected Behavior**
When window is completly loaded, webview should load specific URL

**Actual behavior**
When window is loaded and loading URL(from JS), it does literally nothing.

**To Reproduce**
add onload="funcName()" on html tag, in `funcName` define webview and then type `webview.loadURL('https://www.github.com')`. Webview doesn't load anything.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by CreatorVilius** [comment]
I don't use Electron anymore. Also, this post literally was in 2018 and response was sent in 2019.

**Comment by sofianguy** [comment]
I'm going to close this as we are no longer pushing bug fixes to versions earlier than 4.2.x, but we'd be happy to reopen if you are experiencing this in later versions of electron
