### ISSUE TITLE
Setting process.title before app ready event crashes main process on OSX

### ISSUE THREAD

**Issue by MaxGraey** [electron/electron#1412]
If set process.title to some value it causes crash and log messages:

Apr 13 03:08:27 [11672] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
Apr 13 03:08:27 [11672] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
Apr 13 03:08:27 [11672] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
Apr 13 03:08:27 [11672] <Warning>: Invalid Connection ID 0
Apr 13 03:08:27 [11672] <Error>: Set a breakpoint at CGSLogError to catch errors as they are logged.
Apr 13 03:08:27 [11672] <Error>: CGSServiceForDisplayNumber: Invalid display 0x00000000
Apr 13 03:08:27 [11672] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
Apr 13 03:08:27 [11672] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
Apr 13 03:08:27 [11672] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
Apr 13 03:08:27 [11672] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.
Apr 13 03:08:27 [11672] <Warning>: CGSConnectionByID: 0 is not a valid connection ID.

Without process.title is everything ok

**Comment by deepak1556** [comment]
Can you give a minimum example thats causes the crash ? I am unable to reproduce it, thanks!

**Comment by MaxGraey** [comment]
standart index.js (with setting process.title):
```javascript
var app = require('app');
var BrowserWindow = require('browser-window');

require('crash-reporter').start();

// The line below causes a problem:
process.title = 'app';

var mainWindow = null;

app.on('window-all-closed', function () {
    app.quit();
});

app.on('ready', function () {
    mainWindow = new BrowserWindow({
        width:  800,
        height: 600
    });

    mainWindow.loadUrl('file://' + __dirname + '/index.html');

    // Emitted when the window is closed.
    mainWindow.on('closed', function () {
        mainWindow = null;
    });
});
```

**Comment by deepak1556** [comment]
use it in `ready` once the app is initialised or wrap it in a `setTimeout` . @zcbenz isnt this because of the `uv_loop` synchronisation between browser and renderer. https://github.com/libuv/libuv/issues/271 should fix this without the workaround.

**Comment by bumxu** [comment]
Hi, it seems that currently, setting `process.title` before **app ready** causes no visible error in console or crash, so it can be quite frustrating to find the cause, or at least, this issue.
Regards.

**Comment by codebytere** [comment]
@bumxu can you confirm this is still an issue? we've seen updates to `libuv` since this was opened.
