### ISSUE TITLE
Features removed due to migration to OOPIF webview

### ISSUE THREAD

**Issue by zcbenz** [electron/electron#14120]
Moving webview implementation to use OOPIF (#13869) has fundamentally changed the underlying architecture, and certain features have to be removed.

Currently the dropped features just become no-op, users do not get warnings or exceptions.

__1. Size related methods and attributes (https://github.com/electron/electron/issues/13441)__

* `WebContents.setSize`
* `disableguestresize` attribute
* `autoresize` attribute - Note that this attribute has never been documented, and should have never really worked

The size related functions and attributes existed because we had to manually synchronize the sizes of WebContents and browser plugin element in the old webview implementation. After moving to OOPIF webview, the sizes of WebContents are automatically managed by Chromium, and it becomes impossible to manually control the size of WebContents.

__2. `guestinstance` attribute (#13947)__

With the OOPIF implementation, the guest WebContents is bound to a web frame forever, and it can not be detached and bound to another web frame. This is a design decision made from Chromium's side that we can not work around.

**Comment by felixrieseberg** [comment]
I'm okay with that, my gut feeling is that dropping those features is well worth the benefits here. We _should_ however do some sort of emergency-deprecation-warning.

**Comment by zcbenz** [comment]
We can probably send warnings to console whenever those features are used.

**Comment by magne4000** [comment]
@zcbenz Is there any alternative to replace `guestinstance`?
