### ISSUE TITLE
[3.0.0-beta.5]: did-get-redirect-request no longer works

### ISSUE THREAD

**Issue by IAmPicard** [electron/electron#14142]
* Electron Version: 3.0.0-beta.5
* Operating System (Platform and Version): Windows 10
* Last known working Electron version: 2.0.5

**Expected Behavior**
`webContents.on('did-get-redirect-request', callback)` should work.

**Actual behavior**
After moving to 3.0, the redirect request callback is no longer being called. I confirmed going back to 2.0 fixes the issue. This functionality is needed for Facebook login for example, which can no longer be implemented in 3.0.

**To Reproduce**
```
let authWindow = new BrowserWindow();
authWindow.loadURL('https://jigsaw.w3.org/HTTP/300/301.html');

authWindow.webContents.on('did-get-redirect-request', (event, oldUrl, newUrl) => {
	console.log(newUrl);
});

authWindow.show();
```

**Comment by PalmerAL** [comment]
I think this is intentional, Google apparently removed this listener starting in Chromium 66 according to #12597. You could probably use [webRequest.onBeforeRedirect](https://electronjs.org/docs/api/web-request#webrequestonbeforeredirectfilter-listener) instead?

**Comment by IAmPicard** [comment]
Didn't find that on a cursory search. Thanks for the pointers, I was able to reimplement this using webRequest.onBeforeRedirect.

**Comment by Johnz86** [comment]
It would be usefull to have an example, how to replace event did-get-redirect-request for webRequest(it is not tied to webContent and opened window). I have trouble to replace existing functionality for this new implementation.

**Comment by Lakshman1996** [comment]
@Johnz86 were you able to replace existing functionality with webRequest.onBeforeRedirect? if Yes, would you be able to tell me how you did this.?
I'm trying with following code, But event is not firing.
```
session.defaultSession.webRequest.onBeforeRedirect(null, (details) => {
    // Handle redirect here
});

```

**Comment by Johnz86** [comment]
@Lakshman1996 I needed to completly rework my logic, because onBeforeRedirect is not fit for my use case. It is fired before the redirect, and I needed to access session cookie after the redirect.
```
session.defaultSession.webRequest.onCompleted({ urls: ['www.example.com/hitAfterRedirect'] }, appWebResponse);

function appWebResponse(details: Electron.OnCompletedDetails) {
   // get the cookie after redirect from the page
   session.defaultSession.cookies.get({ url: 'www.example.com/hitAfterRedirect/*' }, function (error, cookies) {
            global[AUTH_COOKIE] = parseCookies(cookies);
   });
   // remove the listener, because I have the cookie
   session.defaultSession.webRequest.onCompleted({ urls: ['www.example.com/hitAfterRedirect/*'] }, null);
}
```

**Comment by kanekotic** [comment]
this will actually not work for me at all, as I have a library published on npm for oauth and I get the window from the user. Is there any other workaround?

**Comment by Pablodotnet** [comment]
I have updated my working example of electron facebook login to the latest version of electron and now I'm using the onCompleted event if someone needs it:
[Electron Facebook Login with Electron 4](https://github.com/Pablodotnet/electron-facebook-login-example)

**Comment by kevincastejon** [comment]
if someone lands here trying to oauth and cannot get the redirect event know that know you should use :
`authWindow.webContents.on('will-redirect', callback);`
[Documentation](https://www.electronjs.org/docs/api/web-contents#%C3%A9v%C3%A9nement--will-redirect)
