### ISSUE TITLE
Can't install it

### ISSUE THREAD

**Issue by ThomasBeHappy** [electron/electron#14140]
* Electron Version: v3.0.0
* Operating System (Platform and Version): windows 10
* Last known working Electron version: none

**Expected Behavior**
It to install perfectly fine.

**Actual behavior**
It hanging at 0.7% of the download and just not continuing no matter what I do.

**To Reproduce**
$ npm install electron@3.0.0-beta.5

**Screenshots**
https://gyazo.com/2d9446c8e28ecc59e0f05db444aba6b5

**Comment by codebytere** [comment]
Hi, while we appreciate your taking the time to open this issue, this is almost certainly is an issue with your personal internet connection and not with Electron itself. If something more Electron-specific should arise, please feel free to comment on this issue with a follow-up!
