### ISSUE TITLE
setLoginItemSettings doesn't add process start args on windows.

### ISSUE THREAD

**Issue by shaluyadav13** [electron/electron#14152]
I am trying to run my app in hidden mode at startup on windows. used below code snippet:

```
const path = require('path');
        const appFolder = app.getPath('appData');
        const exe = path.resolve(appFolder, '..', 'Local\\Programs\\update.exe');
        const exeName = 'update.exe';
        app.setLoginItemSettings({
          args: [
            '--processStart', `"${exeName}"`,
            '--process-start-args', `"--hidden"`,
          ],
          openAtLogin: true,
          path: exe,
        });
```

Any suggestions will be greatly appreciated. Thanks!

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
