### ISSUE TITLE
Touch does not work on Windows 10.

### ISSUE THREAD

**Issue by prabhatsaini91** [electron/electron#14166]
* Electron Version: 1.7.8
* Operating System (Platform and Version): Windows 10 with Touchscreen
* Last known working Electron version: 1.7.8

**Expected Behavior**
Built **exe** with electron-builder should work well on touchscreen.

**Actual behavior**
**exe** built with electron-builder does not respond to touch. Using mouse works, but touch does not work. Project running on local works well on touchscreen, but built **exe** does not respond to touch.

**Comment by MarshallOfSound** [comment]
@prabhatsaini91 Can you test a newer version that `1.7.8` we are update to `3.0.0-beta.X` 😄

**Comment by prabhatsaini91** [comment]
@MarshallOfSound Working with the newer version of Electron 3.0.0-beta.4. Thanks!!

**Comment by MarshallOfSound** [comment]
Good to hear, closing out
