### ISSUE TITLE
Requirements for windows ctrl c 

### ISSUE THREAD

**Issue by lmx1996** [electron/electron#14164]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
I now have a requirement, using electron technology, to copy files on the window desktop and paste them in textarea，This is a need for chat.  
**Describe the solution you'd like**
Using electron technology, in window environment. Ctrl c copy desktop images, paste in textarea, but can not read any path. Using electron technology, in window environment. Ctrl c copy desktop images, paste in textarea, but can not read any path. 
**Describe alternatives you've considered**
There are some ways I can get a sticky picture of ctrl x now. Another idea is to meet this requirement through c-js docking. C. 
**Additional context**

**Comment by MarshallOfSound** [comment]
You can get the current image on the clipboard with https://electronjs.org/docs/api/clipboard#clipboardreadimagetype and listen for paste commands with the [`paste`](https://developer.mozilla.org/en/docs/Web/Events/paste) event
