### ISSUE TITLE
Symbol present in the v8 headers not compiled into libnode

### ISSUE THREAD

**Issue by rricard** [electron/electron#14167]
* Electron Version: 3.0.0-beta.5
* Operating System (Platform and Version): 10.13.6
* Last known working Electron version:  Unknown

**Expected Behavior**
Able to execute a native module call built against the `v8.h` header present in the node version on which electron is built against: https://github.com/electron/node/blob/ece0a06ac8147efb5b5af431c21f312f1884616e/deps/v8/include/v8.h

**Actual behavior**
Getting a native crash at runtime because of the following symbol missing:

`v8::Function::New(v8::Local<v8::Context>, void (*)(v8::FunctionCallbackInfo<v8::Value> const&),v8::Local<v8::Value>, int, v8::ConstructorBehavior, v8::SideEffectType)`

This symbol is present in the vendored `v8.h` with electron: https://github.com/electron/node/blob/ece0a06ac8147efb5b5af431c21f312f1884616e/deps/v8/include/v8.h#L3849.

**To Reproduce**
Get any build of electron 3.0.0-beta.5 (or build it) and inspect the symbol table of `libnode.dylib`:

```sh
$ nm ./out/D/libnode.dylib | c++filt | grep "v8::Function::New"
                 U v8::Function::New(v8::Local<v8::Context>, void (*)(v8::FunctionCallbackInfo<v8::Value> const&), v8::Local<v8::Value>, int, v8::ConstructorBehavior)
0000000000279e60 T v8::Function::NewInstance(v8::Local<v8::Context>) const
                 U v8::Function::NewInstance(v8::Local<v8::Context>, int, v8::Local<v8::Value>*) const
```

**Comment by rricard** [comment]
I also checked the node source tree and the symbol is defined there: https://github.com/electron/node/blob/ece0a06ac8147efb5b5af431c21f312f1884616e/deps/v8/src/api.cc#L5021

I don't see why the build would miss it.

Thanks!

**Comment by MarshallOfSound** [comment]
@rricard I haven't looked into this but just a heads up, Electron builds with the v8 from `libchromiumcontent` with patches applied on top of it.  We don't build against the v8 in node

**Comment by rricard** [comment]
That actually make sense, I think I can try to attach the same headers from there. Thank you for your help.
