### ISSUE TITLE
I wonder if "BrowserWindow.loadURL" don't surpport website.

### ISSUE THREAD

**Issue by grdaimap** [electron/electron#14189]
* Electron Version: Electron 2.0.7.
* Operating System (Platform and Version): Windows10 1803
* Last known working Electron version:  I don't know.

**Expected Behavior**

Open the website as the document says:
![image](https://user-images.githubusercontent.com/36882078/44296497-e5716780-a2f2-11e8-800d-82562b2d6d83.png)

the document: [https://electronjs.org/docs/api/browser-window](https://electronjs.org/docs/api/browser-window)

**Actual behavior**

It falls:Not allowed to load local resource: file:///D:/code/GH/……………………
![20180818142325](https://user-images.githubusercontent.com/36882078/44296510-1baee700-a2f3-11e8-9692-a726a6466ab1.png)

**To Reproduce**

I forked your electron-quick-start and change the 'main.js'.
[https://github.com/grdaimap/electron-quick-start](https://github.com/grdaimap/electron-quick-start)

You can
$ git clone https://github.com/grdaimap/electron-quick-start.git [your place]
and open shell in your place
$ electron .
run it
and get nothing

**Screenshots**

just change one place, the bug happens
![image](https://user-images.githubusercontent.com/36882078/44296560-e48d0580-a2f3-11e8-8293-6dd2064b266a.png)
if you open the developer tools, you will see
![image](https://user-images.githubusercontent.com/36882078/44296686-f2dc2100-a2f5-11e8-9efd-9a3b66c58e98.png)

**Additional Information**
No more.
My poor English :  )

**Comment by MarshallOfSound** [comment]
@grdaimap You are calling `loadFile` and giving it an `https://` URL.  In order to load remote web pages please use `.loadURL` instead of `.loadFile`

**Comment by grdaimap** [comment]
oh! poor stupid me  :  )
the problem has been solved  :  )
