### ISSUE TITLE
[linux] Cannot maximize a window until it is visible

### ISSUE THREAD

**Issue by felicienfrancois** [electron/electron#1418]
Same than #834 but for linux (works well in windows and mac osx)

Occured on latest Ubuntu 64bit

**Comment by hokein** [comment]
See upstream bug: https://code.google.com/p/chromium/issues/detail?id=512660

**Comment by zcbenz** [comment]
I'm closing this since we have upstream Chromium issue created for it, and this bug can be easily worked around.
