### ISSUE TITLE
Tray setContext

### ISSUE THREAD

**Issue by pjebs** [electron/electron#14188]
* Electron Version: 2.0.7
* Operating System (Platform and Version): mac el capitan
* Last known working Electron version: n/a

**Expected Behavior**
Once you set a tray context menu, you expect to a) detect the `click`, `right-click` and `double-click` events.

You also expect to be able to change the menu to original state (no menu).

**Actual behavior**

Once you set a context menu, you can't remove the context menu. You can change it to another menu though.

If you leave out the argument to `setContextMenu` or pass `null`, it will crash.
You also lose access to the events.

**Comment by codebytere** [comment]
@pjebs can you potentially attach a minimal crash repro? i can take a look at it monday :)

**Comment by pjebs** [comment]
No crashes. Just unexpected behaviour

**Comment by miniak** [comment]
@pjebs I have a fix in the attached PR. @codebytere I have a local repro.

**Comment by miniak** [comment]
```
var electron = require('electron')
var {Menu,Tray,nativeImage} = electron.remote
var tray = new Tray(nativeImage.createEmpty())
tray.setContextMenu(null)

**Comment by pjebs** [comment]
@miniak Thank you for the pull-request.
What does your fix do? Accept null value and still receive events?

**Comment by codebytere** [comment]
@pjebs that's what i meant originally:

> If you leave out the argument to setContextMenu or pass null, it will crash.
but then, 
> No crashes. Just unexpected behavior.

It did crash, as you said yourself, but it was unclear what issue you were specifically seeking a fix for.

**Comment by pjebs** [comment]
With the fix, when you pass null (or just call `setContext` generally), will the `click`, `right-click` and `double-click` events be received? That's what I meant to ask.

**Comment by pjebs** [comment]
I'm using `"electron": "^2.0.8"`. Is the fix applied for this version because the bug is still there.
