### ISSUE TITLE
Window Screenshot becomes black using desktopCapturer 

### ISSUE THREAD

**Issue by penginnu** [electron/electron#14194]
* Electron Version: 2.7.0
* Operating System (Platform and Version): Windows 10 64bit
* Last known working Electron version: 

**Expected Behavior**
Take window Screenshot using desktopCapture

**Actual behavior**
Window Screenshot becomes black. This problem occurred in all applications using electrons (Forexample, Visual Studio Code).
But, this problem not occurred in "Screen" Screenshot and all applications not using electrons.. 

**To Reproduce**
This problem occurred this [Repository](https://github.com/penginnu/test)

**Screenshots**
![test](https://user-images.githubusercontent.com/37444014/44305333-def4f580-a3af-11e8-9ec0-7ed75172441e.png)

**Comment by Hardhik** [comment]
@sofianguy Hi. thanks for adding the tags. We are also facing the same issues and would like to know if there's any progress in the fix by anyone you know or if you have any suggested workarounds?

@penginnu Hi, did you do "app.disableHardwareAcceleration()" or is there any other way? Did you figure out any other workarounds?

**Comment by penginnu** [comment]
@Hardhik Hi. I didn't know other workarounds. But, I think that if you take a screen shot of the screen and cut it by the size of the required screen it will be a workaround.

**Comment by CapOM** [comment]
Related https://bugs.chromium.org/p/chromium/issues/detail?id=890928

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
