### ISSUE TITLE
Location Not working in Electron

### ISSUE THREAD

**Issue by luciferreeves** [electron/electron#14199]
* Electron Version: 2.0.7
* Operating System (Platform and Version): macOS 10.13.6
* Last known working Electron version: Never Worked

**Expected Behavior**
I have a HTML document which has running a Mapbox script and I have added a Geolocation button. Clicking the button should fetch my location.

**Actual behavior**
The button is working correctly in any browser but keeps on fetching location in Electron and the location is never returned.

**To Reproduce**
I am providing a code: 

my index.html has this div: 
```
<div id='map' style='width: 100vw; height: 100vh'></div>
```
Script in the same file:
```
mapboxgl.accessToken = 'pk.eyJ1IjoibHVjaWZlcmNyIiwiYSI6ImNqbDBxNnlxZTEzdHkzcG53NW9wNnpibjYifQ.owEb-xS1Y0B-bJYh9racYA';
            var map = new mapboxgl.Map({
                container: 'map',
                style: 'mapbox://styles/mapbox/streets-v9',
                zoom: 2,
            });
            map.addControl(new mapboxgl.GeolocateControl({
                positionOptions: {
                    enableHighAccuracy: true
                },
                trackUserLocation: true
            }));
            map.addControl(new mapboxgl.NavigationControl());
```
 
How to get this working?

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
