### ISSUE TITLE
titleBarStyle: 'customButtonsOnHover' and frame: false not working

### ISSUE THREAD

**Issue by kevinjiaxu96** [electron/electron#14195]
* Electron Version: 2.0.7
* Operating System (Platform and Version): MacOS High Sierra

**Expected Behavior**
No frame, no traffic buttons, left upper region should be unclickable, hovering should display cursor: pointer for html elements.

**Actual behavior**
Left upper region where traffic button was is clickable even know frame is false.  Clicking left upper region will trigger close, minimize or maximize when titleBarStyle and frame is set at the same time.

**Additional Information**
When using frame: false without titleBarStyle: 'customButtonsOnHover', it works, however, there's about 10px on the top that will not show cursor: pointer.

**Comment by sofianguy** [comment]
can you provide us with steps to reproduce this issue?

**Comment by kevinjiaxu96** [comment]
@sofianguy 
This is the first test, left upper corner on MacOS is clickable even know frame is set to none.
`
  mainWindow = new BrowserWindow({
    frame: false,
    titleBarStyle: 'customButtonsOnHover'
  });
`
This is the second test, theres about 10px on top that can't use css cursor settings.
`
  mainWindow = new BrowserWindow({
      frame:false
  });
`

**Comment by MarshallOfSound** [comment]
> This is the second test, theres about 10px on top that can't use css cursor settings.

This is expected and known behavior

> This is the first test, left upper corner on MacOS is clickable even know frame is set to none.

The top left corner will reveal the window controls when you hover there, that is what `customButtonsOnHover` is designed to do.

Both of these appear to be intended behavior, if I missed something please @ mention me in a follow up comment with more details around the issue you are seeing.

**Comment by Slapbox** [comment]
@MarshallOfSound is there a way to increase the size of the area where a user can hover to make the buttons appear? I really like this feature, but I'm afraid people won't even know the buttons are there if they don't appear until they're already hovering in that tiny area. It would be great to have a padding option in pixels on the right and bottom to make it easier for users to discover they can display the buttons in the first place.

**Comment by Slapbox** [comment]
This feature is really cool, blicking the buttons has no effect for me in either Electron 2 or 3.

@MarshallOfSound do you have any idea what this could be about?

**Electron Version:** `3.0.0`
**Page HTML:** `<html></html>`

There is no background set on the element, which I noticed caused issues with the buttons showing.

**Demonstration:** http://recordit.co/sOQ8YM4qMw

**Comment by Slapbox** [comment]
Reproduction steps:

```
$ git clone https://github.com/hokein/electron-sample-apps
$ cd electron-sample-apps
$ yarn add electron
$ npx electron --version
v3.0.2
```

**Edit main.js**
Modify line 14 to:  `mainWindow = new BrowserWindow({width: 360, height: 300, frame: false, 
    titleBarStyle: 'customButtonsOnHover'});`

**Edit index.html**
Remove line 7: `<link rel="stylesheet" type="text/css" href="style.css" />`
Delete contents of `<body>` tag

```
$ npx electron frameless-window
```

Result: http://recordit.co/EDw0nv7XNd

**Comment by mb21** [comment]
@MarshallOfSound The `customButtonsOnHover` buttons don't show up for me at all on `electron 3.0.7` and macOS 10.14.1. Works fine with `electron 2.0.13`
