### ISSUE TITLE
Mistake in Docs: Duplicate properties

### ISSUE THREAD

**Issue by mets11rap** [electron/electron#14200]
https://i.imgur.com/mYtRTmJ.png

https://electronjs.org/docs/api/browser-window

**Comment by MarshallOfSound** [comment]
Hey @mets11rap ,

Thanks for the issue, but those two properties are different, one is `minimizable` the other is `maximizable`

**Comment by mets11rap** [comment]
Oh, whoops. Sorry :grimacing: I'm blind.
