### ISSUE TITLE
Session#setProxy config object should support explicit direct mode

### ISSUE THREAD

**Issue by bughit** [electron/electron#14226]
```c++
  static ProxyConfig CreateDirect() {
    return ProxyConfig();
  }
```
https://github.com/electron/electron/blob/3-0-x/docs/api/session.md#sessetproxyconfig-callback

Currently direct can be set via an empty or 'direct://' proxyRules value, but it's really a distinct mode so should be settable explicitly (direct: true) without referring to proxyRules

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
