### ISSUE TITLE
Session#setProxy can't be set to use system

### ISSUE THREAD

**Issue by bughit** [electron/electron#14223]
* Electron Version: v3.0.0-beta.5
* Operating System (Platform and Version): win7 x64 

https://github.com/electron/electron/blob/3-0-x/docs/api/session.md#sessetproxyconfig-callback

Though system appears to be the default you should still be able to assert it for a given session, in case process default is something different  (via flags or env vars or whatever else is consulted); and to reset it to system after it's been set to something else.

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR.
