### ISSUE TITLE
Widevine CDM no longer works on v3

### ISSUE THREAD

**Issue by steverandy** [electron/electron#14227]
* Electron Version: 3.0.0-beta.6
* Operating System (Platform and Version): macOS 10.13.6
* Last known working Electron version: 2.0.7

**Expected Behavior**
Widevine CDM should load and webview should be able to play DRM content.
I'm using [electron-widevinecdm](https://github.com/quanglam2807/electron-widevinecdm) v5.0.2. It has worked up to Electron v2.0.7.

**Actual behavior**
Widevine CDM seems not loaded and could not play a DRM video (for example netflix.com)

**Comment by MarshallOfSound** [comment]
@steverandy See this thread, there are new signing requirements if you are using widevine in more recent Electron versions.

https://github.com/electron/electron/issues/12427#issuecomment-401449104

**Comment by steverandy** [comment]
@MarshallOfSound the issue #12427 reported CDM does not work for v1.8.4.
I was able to get CDM loaded and playing DRM content up to latest stable version (2.0.7).
It only does not work for Electron v3.0.0 beta.

**Comment by MarshallOfSound** [comment]
Reopening, can you provide a way to repro

**Comment by steverandy** [comment]
Thanks! Will provide a repo to reproduce.

**Comment by steverandy** [comment]
Steps to reproduce:

## Widevine CDM works on Electron v2
1. Clone this repo: https://github.com/steverandy/electron-quick-start/
2. Checkout branch **`v2-cdm`** to test Electron v2
3. Run `npm install` and `npm start`
4. Wait for page to load and click on "Load"
5. DRM enabled stream should play

## Widevine CDM does not work on Electron v3
1. Clone this repo: https://github.com/steverandy/electron-quick-start/
2. Checkout branch **`v3-cdm`** to test Electron v3
3. Run `npm install` and `npm start`
4. Wait for page to load and click on "Load"
5. Video will not play and will get an error `Shaka Error DRM.REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE ()`

I've also tested separately with Netflix and can confirm that Electron v2.0.7 plays Netflix videos just fine. So I think issue #12427 might be something else.

**Comment by ckerr** [comment]
When testing on Ubuntu 18.04.1 LTS, @steverandy's branches work (and don't work) as advertised.

**Comment by steverandy** [comment]
This issue has been fixed on version 3. But seeing regression on the newly release Electron v4.

**Comment by drewbkoch** [comment]
I am also having issues with it for v4. v3 works fine now.
