### ISSUE TITLE
Hi, can anyone please help me how to get the list of workspaces  in mac 

### ISSUE THREAD

**Issue by maheshatti89** [electron/electron#14232]
* Electron Version:
* Operating System (Platform and Version):
* Last known working Electron version: 

**Expected Behavior**

**Actual behavior**
A clear and concise description of what actually happened.

**To Reproduce**
Your best chance of getting this bug looked at quickly is to provide a REPOSITORY that can be cloned and run.

You can fork [electron-quick-start](https://github.com/electron/electron-quick-start) and include a link to the branch with your changes.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone $YOUR_URL -b $BRANCH
$ npm install
$ npm start || electron .
```
**Screenshots**

**Additional Information**

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
