### ISSUE TITLE
Supporting preload scripts in iframes

### ISSUE THREAD

**Issue by ErezPasternak** [electron/electron#14235]
* Electron Version: 3.x
* Operating System (Platform and Version): Ubuntu 16.04 LTS
* Last known working Electron version:  1.8.7

**Expected Behavior**
We are loading preload script, while it works in the main window, we need it also to run in iFrames

**Actual behavior**
Preload scripts are not loaded in iFrames

**To Reproduce**
Your best chance of getting this bug looked at quickly is to provide a REPOSITORY that can be cloned and run.

**Additional Information**
Electron supported preload scripts in iframes up to version 1.8. In version 2.0 and later this possibility was disabled. In order for our product to work properly we need to reintroduce this possibility in the latest versions of Electron.

What we found is that this issue is caused by a fix for this bug: electron/electron#10470 They simply banned preload scripts in everything except the Main Frame and dev tools windows. 
There is another issue in the Electron's issue tracker related to this: electron/electron#12505 (seems somewhat mutually exclusive with electron/electron#10470).

In order to make preload scripts work again we had to, effectively, revert this fix like this:

```
diff --git a/atom/renderer/atom_renderer_client.cc b/atom/renderer/atom_renderer_client.cc
index 2794ce0ad..6beabbab5 100644
--- a/atom/renderer/atom_renderer_client.cc
+++ b/atom/renderer/atom_renderer_client.cc
@@ -81,8 +81,8 @@ void AtomRendererClient::DidCreateScriptContext(
     content::RenderFrame* render_frame) {
   // Only allow node integration for the main frame, unless it is a devtools
   // extension page.
-  if (!render_frame->IsMainFrame() && !IsDevToolsExtension(render_frame))
-    return;
+  //if (!render_frame->IsMainFrame() && !IsDevToolsExtension(render_frame))
+  //  return;
 
   injected_frames_.insert(render_frame);
 
diff --git a/atom/renderer/atom_sandboxed_renderer_client.cc b/atom/renderer/atom_sandboxed_renderer_client.cc
index ca66298fc..a8df133b2 100644
--- a/atom/renderer/atom_sandboxed_renderer_client.cc
+++ b/atom/renderer/atom_sandboxed_renderer_client.cc
@@ -149,8 +149,8 @@ void AtomSandboxedRendererClient::DidCreateScriptContext(
     content::RenderFrame* render_frame) {
   // Only allow preload for the main frame or
   // For devtools we still want to run the preload_bundle script
-  if (!render_frame->IsMainFrame() && !IsDevTools(render_frame))
-    return;
+  //if (!render_frame->IsMainFrame() && !IsDevTools(render_frame))
+  //  return;
 
   base::CommandLine* command_line = base::CommandLine::ForCurrentProcess();
   base::FilePath preload_script_path =
@@ -184,8 +184,8 @@ void AtomSandboxedRendererClient::WillReleaseScriptContext(
     v8::Handle<v8::Context> context,
     content::RenderFrame* render_frame) {
   // Only allow preload for the main frame
-  if (!render_frame->IsMainFrame())
-    return;
+  // if (!render_frame->IsMainFrame())
+  //  return;
 
   auto* isolate = context->GetIsolate();
   v8::HandleScope handle_scope(isolate);
diff --git a/vendor/libchromiumcontent b/vendor/libchromiumcontent
index c8a21364b..a604af6f5 160000
--- a/vendor/libchromiumcontent
+++ b/vendor/libchromiumcontent
@@ -1 +1 @@
-Subproject commit c8a21364be7a58cead7167bfe02e00eff8dd92e2
+Subproject commit a604af6f51a2e816592db475159ee898f212d9db
```

**Comment by MarshallOfSound** [comment]
This should be tracked in #12505 preloads have never worked for iframes in a normal window but they worked for a while in sandboxed windows due to bug in our own code which was fixed in #11227

Enabling preload support for all frames is a thing would need to be implemented correctly as a separate API option, follow #12505 for that
