### ISSUE TITLE
Paint glitches after screen lock, and in Night Shift mode

### ISSUE THREAD

**Issue by nehbit** [electron/electron#14249]
* Electron Version: 2.0.3
* Operating System (Platform and Version): Mac OS X Sierra 10.12.6 (16G1510)
* Last known working Electron version: None

**Expected Behavior**
When the user opens the app, locks the screen and comes back, the app should render normally. 

**Actual behavior**

The app renders in washed out colours, and it glitches in a way that suggests issues with the tile painting in Chromium. The glitching areas do **not** correspond to any specific HTML or CSS boundaries.

Here's a video demonstration of the issue: https://www.dropbox.com/s/ltuq2nwwm8stvhg/electron-possible-bug.mp4?dl=0

**To Reproduce**
On an OS X system, set a dark background on any Electron app (dark background makes this more visible, but I think it happens on all Electron apps) and lock the screen. When you unlock the screen, you will see a similar state as shown in the video linked above.

**Screenshots**
Here's a video demonstration of the issue: https://www.dropbox.com/s/ltuq2nwwm8stvhg/electron-possible-bug.mp4?dl=0

**Additional Information**
The app in the video can be accessed [here](https://github.com/nehbit/aether) on Github. The specific sub-directory that hosts the Electron app and the frontend that lives in it is [here](https://github.com/nehbit/aether/tree/master/Aether%202/client/src/app). The Electron app starts with [this file](https://github.com/nehbit/aether/blob/master/Aether%202/client/src/app/mainmain.js).

**Comment by ckerr** [comment]
@nehbit, does this issue continue in the 3.0.0 betas?

**Comment by nehbit** [comment]
I don't know yet, I had to downgrade from 3.0.0 beta two months ago because of #13395. If it's useful, I can try to upgrade again and check.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by nehbit** [comment]
We've moved to Electron 5 a few days ago. The issue has not appeared so far. I'll open a new issue if it does. Cheers.
