### ISSUE TITLE
Electron 3.0.x: pausing in devtools can trigger unresponsive window error

### ISSUE THREAD

**Issue by bpasero** [electron/electron#14257]
* Electron Version: 3.0.x
* Operating System (Platform and Version): macOS
* Last known working Electron version: 2.0.x

**Expected Behavior**
Stopping in a breakpoint should never trigger `window.on('unresponsive')`

**Actual behavior**
In some cases I see the event fired which results in a modal dialog popping up in VSCode

**To Reproduce**
I still have to find a repro, it does not seem to be so easy as to just break and trigger it (tried with fiddle). Repro in VSCode: https://github.com/Microsoft/vscode/issues/56994

**Comment by sofianguy** [comment]
@bpasero is this happening in v4.2.x or later?

**Comment by bpasero** [comment]
Yes:

![image](https://user-images.githubusercontent.com/900690/62818510-95fdfa00-bb48-11e9-9909-bade84807314.png)

**Comment by sofianguy** [comment]
@bpasero thank you. which version is this happening on?

**Comment by bpasero** [comment]
@sofianguy this one was using 4.x in VSCode

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
