### ISSUE TITLE
Electron(3.0.0-beta.6 ) don't support h264 encoder 

### ISSUE THREAD

**Issue by RobinWuDev** [electron/electron#14256]
I use webrtc of Electron(3.0.0-beta.6) for video meetting, I can see peer video for chrome,but chrome can't see my video.
if config to V8, it's fine,but config h264,it's error.
if i use Electron(2.0.7),chrome can see my video,but I can't see other video,but ui is overlapping.

console print these log:
[99769:0822/173441.318182:ERROR:webrtcvideoengine.cc(676)] No video codecs supported.

**Comment by deepak1556** [comment]
Can you provide a minimal test case using https://github.com/electron/fiddle or [electron-quick-start](https://github.com/electron/electron-quick-start) to verify this issue ? Thanks!

**Comment by aankur** [comment]
https://gist.github.com/aankur/1e857dc22a4b184231d6ecc5d69ac84a

can you run this fiddle gist. you will find that electronjs no longer has H264 with profile-level-id=42e01f, causing H.264 not to work, 42e01f is present in chrome

the actual test is just this

```javascript
 let peercon = new RTCPeerConnection([]);
      let options = {
        offerToReceiveAudio: 1,
        offerToReceiveVideo: 1
      };
      peercon.createOffer(options)
      .then((offer) => {
        const hasH264profile = offer.sdp.indexOf("profile-level-id=42e01f") !== -1;
        alert(hasH264profile );
        alert(offer.sdp);
      });
```

**Comment by deepak1556** [comment]
@aankur thanks for the test case, can confirm the issue. This is caused by an upstream change in build config https://webrtc-review.googlesource.com/c/src/+/36321 and eventually got reverted in https://webrtc-review.googlesource.com/c/src/+/62380, reverting the same on our end should fix the issue.

**Comment by RobinWuDev** [comment]
@deepak1556 thanks for your reply. I pull electron sources  and  set rtc_use_h264 = true in webrtc/wertc.gni and rebuild it. result is fine. but I want to use official version, so I want to kown when release the fixed version
