### ISSUE TITLE
window.fetch not able to send POST requests (always performing GET instead)

### ISSUE THREAD

**Issue by matthiasg** [electron/electron#14254]
* Electron Version: 3.0.0-beta.3
* Operating System (Platform and Version): Window 10 x64 14393.2430
* Last known working Electron version: 2.0.7

**Expected Behavior**
`window.fetch('/someurl', { method: 'post' , body: '' })` should perform a post to the resource
as should `window.fetch('/someurl', { method: 'post' })` or `window.fetch('/someurl', { method: 'POST' })`.

** Actual behavior**
Chrome Debugger shows error that body is not allowed on GET/HEAD requests in the first example and performs a GET on /someurl (as proven server side) when body is left out.

**To Reproduce**
Simple open a debugger and try the command above. In my case I performed the call from an inner webview with the following options

<webview id="webview" disableguestresize class="hide" autosize="on" src="about:blank" preload="system-preload.js" allowfullscreen autosize></webview>
```

**Comment by deepak1556** [comment]
This is fixed in 3.0.0-beta.5 and higher, can you test with that release. Thanks!

**Comment by matthiasg** [comment]
Thanks for the feedback I obviously missed that ticket sorry for the churn.
