### ISSUE TITLE
Webview: no longer emits onfocus event

### ISSUE THREAD

**Issue by bpasero** [electron/electron#14255]
* Electron Version: 3.0.0-beta.6
* Operating System (Platform and Version): macOS
* Last known working Electron version: 3.0.0-beta.5

**Expected Behavior**
The `onfocus` event is fired when clicking into a webview contents.

**Actual behavior**
The `onfocus` event is not fired.

**To Reproduce**
* run this fiddle: https://gist.github.com/bpasero/eb6f5e94b463883d5445a96ab9a0b1ba
* click into the input box of the GitHub landing page
* observe that the `onfocus` event is not emitted

This breaks VSCode's focus tracking when the user clicks into a webview.

**Comment by ckerr** [comment]
Running in fiddle, I'm seeing the same behavior as described as @bpasero -- this works in 2.0.x and up through 3.0.0-beta.5, then is broken in beta.6 and beta.7

**Comment by zcbenz** [comment]
Hmm in old architecture the webview is a browser plugin which is an actually DOM element that can get focus, but with OOPIF the webview is an iframe, and there is no real way to listen to the focus/blur events of an iframe.

I'll see if I can find a way to hack this.

**Comment by bpasero** [comment]
@zcbenz thanks, very happy that the existing behaviour does not change ❤️
