### ISSUE TITLE
Electron shown blank screen on redirect for auth popup

### ISSUE THREAD

**Issue by vtebano13** [electron/electron#14267]
*Electron version: 1.3.4

Operating System (Platform and Version): OSX 10.13.5
Expected behavior
We have a system that we connect into that starts off with a microsoft login. It then redirects to a VPN login popup that uses NTLM authentication.   The page should show a popup to enter the credentials and allow the ability to send the NTLM creds to the redirected page.

Actual behavior
In electron I get the microsoft login but then get a blank page for the redirect for the NTLM popup.
I see a 401 unauthorized on the redirect call.

Electron shows blank page where as in chrome you get a popup for credentials.  Also, there is no way to send the NTLM cred to the redirected page.

I was able to successfully log in from Postman using the redirect link and sending the user name and password in NTLM format.

**Comment by vtebano13** [comment]
This has been test on the newer version and the issue is still there.  Reproducing is hard because you need an AZURE logon system to do it.  Where it will send you to the Microsoft login, then enter your email from there it will redirect to a VPN authorization page (popup) that you enter in your creds.

**Comment by sofianguy** [comment]
Which newer version did you test with?

**Comment by vtebano13** [comment]
1.7.5

**Comment by sofianguy** [comment]
@vtebano13 we are no longer implementing bug fixes for versions older than 1.7.x. Are you still experiencing this problem on 1.8.x, 2.0.x, or 3.0.x?

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by othmankh** [comment]
@sofianguy I am facing the same problem and my electron's version is:
3.0.x

**Comment by ClaudiaStefan** [comment]
Have you tried: https://electronjs.org/docs/api/app#event-login

**Comment by jianfengjin** [comment]
I have the same issue when open "https://app.vssps.visualstudio.com/oauth2/authorize" with BrowserWindow. The error is "jQuery is not defined" etc. This is an external link opened within the BrowserWindow. "https://app.vssps.visualstudio.com/oauth2/authorize" is the Azure DevOps OAuth link. I am using electron 4.2.4.

**Comment by fpaparoni** [comment]
I have the same issue with 4.2.7 and with latest 7 version

**Comment by nornagon** [comment]
Duplicate of #21082

**Comment by bkarv** [comment]
Anyone having similar issue for us it was because csp for the microsoft login urls wasnt set. We were able debug it in Google Gemina 2.5 (other AIs struggled with it)
