### ISSUE TITLE
Green color not rendered with DesktopCapturer on 16bits color depth on linux

### ISSUE THREAD

**Issue by SamuelRobotiq** [electron/electron#14279]
* Output of v2.0.5:
* Operating System (Platform and Version):
* Output of v2.0.5 on last known working Electron version (if applicable): Debian Weezy

**Expected Behavior**
DesktopCapturer stream colors to be the same as the screen colors.

**Actual behavior**
The desktopCapturer video stream doesn't contains green color.

**To Reproduce**
- Start the DesktopCapturer video stream on a linux machine having a 16bits color depth.  
- Display the video stream directly on the linux machine or send it through WebRTC to another machine.
- The machine with 16bits color depth video stream will not have green color.

**Comment by ckerr** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unneccessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you've responded, please link to the test case and @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
