### ISSUE TITLE
Menu's appear on the wrong monitor on Windows

### ISSUE THREAD

**Issue by onovotny** [electron/electron#1427]
I filed this under atom, but it should probably be here:
https://github.com/atom/atom/issues/6387

**Comment by onovotny** [comment]
Chrome had the same issue a while back (it's fixed now). Perhaps a newer version of Chromium would solve it?

**Comment by steelbrain** [comment]
Origin Issue:
![Screenshot](https://cloud.githubusercontent.com/assets/1427284/7159309/3d6cefc0-e34f-11e4-88e7-3d6487b8e43c.png)
Monitor 1 is the left, 2 is the right. They're both 4k monitors.

**Comment by zcbenz** [comment]
It doesn't seem to occur in recent versions of Electron.
