### ISSUE TITLE
Set checkmark without requiring "type: checkbox"

### ISSUE THREAD

**Issue by envex** [electron/electron#14278]
It would be nice if you could set a checkmark on without requiring the menu type to be `type: checkbox`.

Our app menus are connected to our app state so that we can dynamically change the menu based on actions/state.

The issue is that if a menu item is set to checked, but the app state still wants the menu item to be checked, it will display as unchecked (when clicked) until the menu is rebuilt.

It's a small edge-case, but something to consider.

**Comment by MarshallOfSound** [comment]
> The issue is that if a menu item is set to checked, but the app state still wants the menu item to be checked, it will display as unchecked (when clicked) until the menu is rebuilt.

You can reject menu item checked state changes.  This is logic from one of my apps that does that kind of thing.

```ts
const createSettingsItem = async (
  label: string,
  setting: SettingsKeyDefaultPair,
  acceptChange?: (checked: boolean) => Promise<boolean>,
): Promise<Electron.MenuItemConstructorOptions> => ({
  label,
  type: 'checkbox',
  click: async (item) => {
    if (acceptChange && !await acceptChange(item.checked)) {
      item.checked = !item.checked;
      return;
    }
    await settings.setEnabled(setting.key, item.checked);
  },
  checked: await settings.isEnabled(setting.key, setting.default),
});
```

The key thing is just setting `item.checked` to `!item.checked` (instantly cancelling the change in checked state)

**Comment by envex** [comment]
Thanks!
