### ISSUE TITLE
3.0 regression: Exiting GPU process due to errors during initialization

### ISSUE THREAD

**Issue by bughit** [electron/electron#14270]
* Output of `node_modules/.bin/electron --version`: v3.0.0-beta.7 x86
* Operating System (Platform and Version): win7 x64
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v2.0.8 x86

**Expected Behavior**

electron should start the gpu process

**Actual behavior**

no gpu process, the following is logged:
```
[2172:0822/183037.026:ERROR:viz_main_impl.cc(195)] Exiting GPU process due to errors during initialization
[3088:0822/183037.120:ERROR:viz_main_impl.cc(195)] Exiting GPU process due to errors during initialization
[4004:0822/183037.135:ERROR:browser_gpu_channel_host_factory.cc(119)] Failed to launch GPU process.
[4004:0822/183037.135:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.
```

**To Reproduce**
run x86 electron on an x64 win7 sp1 vmare vm (`electron --enable-logging`)

**Additional Information**
- 3.0.0-beta.7 works on physical hardware
- both chrome 68 and electron 2.0.8 are able to start their gpu processes on the same vm

**Comment by ckerr** [comment]
Similar error messages in #2256

**Comment by bughit** [comment]
about the vm: vmware workstation 14, v14 hardware, vmware 3d driver from latest tools (8.15.1.65), 512 graphics memory

**Comment by bughit** [comment]
@codebytere does the fix apply to 3.0 or just master?

**Comment by codebytere** [comment]
@bughit it'll go out in 3.0 as well

**Comment by programmin1** [comment]
I see the same GPU error but on arm64 Librem phone.
https://github.com/ezra-bible-app/ezra-bible-app/issues/643
