### ISSUE TITLE
Windows: "logs" folder is being created before being able to set userdata path

### ISSUE THREAD

**Issue by bpasero** [electron/electron#14276]
* Output of `node_modules/.bin/electron --version`: 2.0.x and 3.0.x
* Operating System (Platform and Version): Windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 1.7.x

**Expected Behavior**
An application is able to change the userData folder according to https://github.com/electron/electron/blob/master/docs/api/app.md#appsetpathname-path

**Actual behavior**
A folder called "logs" is created in the default location of Electron.

**To Reproduce**
* fiddle: https://gist.github.com/bpasero/3b84dcac354218bf3d483599ff84ab48
* delete any `%APPDATA%\Electron` folder first
* start and notice that a `%APPDATA%\Electron\logs` folder is created even though we change `userData` as one of the first things. 

This blocks VSCodes portable feature where no data should be left on the hard disk (https://github.com/Microsoft/vscode/issues/56651).

**Comment by faizalMo** [comment]
Came across the same issue in our app as well, we are using electron-2.0.x

**Comment by faizalMo** [comment]
So, looks like the issue we faced is because of breaking changes in the config options for new version of electron-packager that we upgraded to. Updating the electron-packager config fixed the issue.

**Comment by joernroeder** [comment]
@faizalMo i'm running into the same issue. can you give me a hint how you were able to fix it?

**Comment by faizalMo** [comment]
@joernroeder I might have misread the issue when I put that comment. We are not changing the 'userData' folder in our app, we are just using the default 'logs' folder created, ie, %Appdata%/Roaming/<package.json.productName>/logs using the app.getPath('logs') API. As long as you have set the productName, it should be available? - https://github.com/electron/electron/blob/master/docs/api/app.md#appgetname

We had bumped the dependency on electron-packager at the same time, which had caused some confusion. There were breaking changes in the config options for that package, specifically in  https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#win32metadata, but AFAIK it has nothing to do with the userdata path.

**Comment by codebytere** [comment]
Resolved by https://github.com/electron/electron/pull/17841.
