### ISSUE TITLE
Loading HTML and CSS on Electron

### ISSUE THREAD

**Issue by GabrielLeonte** [electron/electron#14295]
Hi. I want to load a url with electron.
url have this code in index
`<ul class="nav">
                     <li><a href="/wallet" class="active"><i class="lnr lnr-home"></i> <span>Wallet</span></a></li>
                     <li><a href="/receive" class=""><i class="lnr lnr-arrow-right"></i> <span>Receive</span></a></li>
                     <li>
                        <a href="#subPages" data-toggle="collapse" class="collapsed"><i class="lnr lnr-arrow-left"></i> <span>Send</span> <i class="icon-submenu lnr lnr-chevron-left"></i></a>
                        <div id="subPages" class="collapse ">
                           <ul class="nav">
                              <li><a href="send-epic" class="">EPIC</a></li>
                              <li><a href="send-index" class="">INDEX</a></li>
                              <li><a href="send-securecloud" class="">SECURE CLOUD</a></li>
                              
                           </ul>
                        </div>
                     </li>
                  </ul>`

This is a submenu made who collapse. But on electron when i click on this menu nothing happens.
Electron code is that 
`// Modules to control application life and create native browser window
const {app, BrowserWindow} = require('electron')

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
let mainWindow

function createWindow () {
  // Create the browser window.
mainWindow = new BrowserWindow({width: 1440, height: 1024, titleBarStyle: 'hidden', nodeIntegration:false});

  // and load the index.html of the app.
  mainWindow.loadURL('https://www.i-removed-it.com/');  
  mainWindow.setMenu(null);
  // Open the DevTools.
  // mainWindow.webContents.openDevTools()

  // Emitted when the window is closed.
  mainWindow.on('closed', function () {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null
  })
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow)

// Quit when all windows are closed.
app.on('window-all-closed', function () {
  // On OS X it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', function () {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (mainWindow === null) {
    createWindow()
  }
})

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.`

electron version: 2.0.7
node version: v8.11.3

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
