### ISSUE TITLE
refused to display www.accountkit.com in a frame because an ancestor violates the following Content Security Policy directive: frame-ancestors http://localhost:3000

### ISSUE THREAD

**Issue by fhinardi** [electron/electron#14294]
Hi, I'm try integrate facebook account kit into electron and found this error.
![screen shot 2018-08-24 at 17 26 50](https://user-images.githubusercontent.com/42131756/44593032-7f9e4780-a7ec-11e8-99bc-8e0dc0894171.png)
any idea for fixing this bug?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
