### ISSUE TITLE
Window changes position when `.show()` is called

### ISSUE THREAD

**Issue by Mike-Wood** [electron/electron#14291]
* Output of `node_modules/.bin/electron --version`: v2.0.8
* Operating System (Platform and Version): Win 8 (running in a VM)
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): I'm not sure but it might be working in v2.0.4

**Expected Behavior**
When you press `Win`+`Left` it pushes the window to the left half of the screen, then if you call `win.show()` it shows the window()

**Actual behavior**
When you press `Win`+`Left` it pushes the window to the left half of the screen, then if you call `win.show()` it moves the window to where it was before you pressed `Win`+`Left`.

**To Reproduce**
Clone https://github.com/Mike-Wood/electron-window-position-bug
```sh
$ git clone https://github.com/Mike-Wood/electron-window-position-bug
$ cd electron-window-position-bug
$ npm install
$ electron ./index.js
```
Then press `Win`+`Left` to move it to the side.
Then press `Win`+`A` to call the `.show()` function.
**Additional Information**
Calling `.focus()` seems to work. I only have a problem with `.show()`.

**Comment by ckerr** [comment]
@Mike-Wood, that repository https://github.com/Mike-Wood/electron-window-position-bug seems to be empty. Is that the correct URL?

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
