### ISSUE TITLE
win.minimize() make the render process freeze

### ISSUE THREAD

**Issue by LiZ2z** [electron/electron#14306]
sorry, my english is poor
hey, i got a problem, after i used the func `win.minimize()` and restore it ,  the window seems to be freeze, can`t click and javascript cannot run.

**Comment by sofianguy** [comment]
Hi, can you please provide us with the following for us to better help you:
- Electron version
- operating system
- steps to reproduce issue

**Comment by LiZ2z** [comment]
Thank you for your reply ! 
- my electron version is:  **2.0.0**
- my operating system is:  **win10**
-  the steps is:
  1. in Render process, I have a button, when  it been clicked , i use `ipcRenderer.sendSync(...)` emit an event.(also i tried `ipcRenderer.send(...)`)
  2. in Main process , i use `ipcMain.on(...)` to receive the event from render process, and then i use `mainWindow.minimize()` to minimize the app and its success
  3. i click the app from dock, and its restore. the Main process is ok, it can still run. but, everything in the Render process seems to be frozen(no error log, just frozen, seems its frozen at the moment I click the btn)
PS:  i have tried add `app.commandLine.appendSwitch('disable-background-timer-throttling')` before `app.on('ready', ...)`, and cannot work
I hope I made myself clear.

**Comment by ckerr** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unneccessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you've responded, please link to the test case and @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by LiZ2z** [comment]
@ckerr
 Hi, I tried to reproduce this issue, but i failed. So I back to my electron app try to reproduce the issue again, and also failed (i didn't do anything, and i don't know why).  
Anyway, Thank you for your reply. I will close this issue.
