### ISSUE TITLE
useContentSize ignored in non-resizable windows

### ISSUE THREAD

**Issue by sirasistant** [electron/electron#14308]
* Output of `node_modules/.bin/electron --version`: v2.0.8
* Operating System (Platform and Version): Microsoft Windows 10 Pro 10.0.17134

* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

### Expected behavior
Your app has two browser windows, with the following config:

Browser window 1: `{useContentSize:true, width, height, resizable:false, fullscreen:false}`
Browser window 2: `{useContentSize:true, width, height, resizable:true, fullscreen:false}`
With app menu enabled
The size of the two browser windows should be the same, with the size of an html element rendered with css: width:100% and height 100% equal to the width and height constants used on config.

### Actual behavior
The two windows have a different size on my windows machine, the resizable one actually honors perfectly the contentSize, but the non-resizable one has 20px less height (probably the height of the menu bar)

### How to reproduce
```
const { app, BrowserWindow } = require("electron");

const width = 800;
const height = 600;

app.on('ready', ()=>{
    const windowOne = new BrowserWindow({useContentSize:true, width, height, resizable:false, fullscreen:false})
    const windowTwo = new BrowserWindow({useContentSize:true, width, height, resizable:true, fullscreen:false})
});
```
With electron@2.0.8 as a dependency.

**Comment by AHKol** [comment]
I believe I replicated this bug.

I will take a look and see if `<html>` can be locked to `useContentSize`

**Comment by cumajkeee** [comment]
@sofianguy, looks like this applies and to 3.0.x also.

**Comment by wasnotrice** [comment]
Just ran into this issue on 4.0.0 as well

**Comment by Fraasi** [comment]
Still an issue, just [repllcated](https://github.com/p-sam/electron-prompt/issues/44) this with electron 6.0.11 with whopping 50 pixels missing in height.

**Comment by RacerDelux** [comment]
Can confirm this is still an issue.
![image](https://user-images.githubusercontent.com/2667344/66624754-1a0b4700-ebb7-11e9-8067-3bd92c1ad04f.png)

**Comment by lutzroeder** [comment]
Repro: 

```
<body style="overflow: hidden; margin: 0;">
<div style="width: 300px; height: 300px; background-color: #ff0000;">
```

<img width="322" alt="Screen Shot 2020-02-09 at 10 48 46 AM" src="https://user-images.githubusercontent.com/438516/74107961-e7079e80-4b29-11ea-8efe-2c406bfccad3.png">

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by dtaskoff** [comment]
Still an issue with electron 19.

**Comment by dtaskoff** [comment]
https://github.com/electron/electron/issues/28777
