### ISSUE TITLE
Stale shadow in transparent BrowserWindow

### ISSUE THREAD

**Issue by pronebird** [electron/electron#14304]
* Output of `node_modules/.bin/electron --version`: v2.0.5
* Operating System (Platform and Version): macOS 10.13.6
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): N/A

**Expected Behavior**

We use a SVG mask to clip some part of transparent browser window to produce a non-rectangular transparent area. macOS renders a nice shadow around it. I expect the shadow to receive updates when the clipping mask is being updated while the window remains visible.

<img width="336" alt="screenshot 2018-08-25 08 21 20" src="https://user-images.githubusercontent.com/704044/44615314-ec8efd00-a83f-11e8-9938-7a574f680bb1.png">

**Actual behavior**
The window shadow does not receive updates if we change the clipping mask while the browser window is visible.

<img width="332" alt="screenshot 2018-08-25 07 39 55" src="https://user-images.githubusercontent.com/704044/44615245-32e35c80-a83e-11e8-860d-6f798f6aa66e.png">

**To Reproduce**
Your best chance of getting this bug looked at quickly is to provide a REPOSITORY that can be cloned and run.

You can fork [electron-quick-start](https://github.com/electron/electron-quick-start) and include a link to the branch with your changes.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone $YOUR_URL -b $BRANCH
$ npm install
$ npm start || electron .
```
**Screenshots**

**Additional Information**
It's possible to trigger refresh by toggling `setHasShadow` but that causes a flicker which is ugly:

```
remote.getCurrentWindow().setHasShadow(false);
remote.getCurrentWindow().setHasShadow(true);
```

**Comment by pronebird** [comment]
Seems like Electron is missing some API to invalidate the shadow on macOS:

https://developer.apple.com/documentation/appkit/nswindow/1419529-invalidateshadow

It would be ace to have `invalidateShadow()` in `BrowserWindow` API.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by pronebird** [comment]
@sofianguy still an issue. Please reopen the issue.

**Comment by lyswhut** [comment]
The same problem is in electron v10.1.2
Links related to this issue: <https://github.com/electron/electron/issues/21173>

**Comment by lyswhut** [comment]
@sofianguy Please reopen

**Comment by xiajingren** [comment]
Any progress?
