### ISSUE TITLE
Can't change window position when window is pushed to the side

### ISSUE THREAD

**Issue by Mike-Wood** [electron/electron#14307]
* Output of `node_modules/.bin/electron --version`: v2.0.8
* Operating System (Platform and Version): Ubuntu 16.04
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 

**Expected Behavior**

When you press `Win`+`Ctrl`+`Left` it pushes the window to the left half of the screen, then if you call `win.setPosition(500, 100)` it moves the window to 500, 100.

**Actual behavior**

When you press `Win`+`Ctrl`+`Left` it pushes the window to the left half of the screen, then when you call `win.setPosition(500, 100)` it doesn't move at all.

**To Reproduce**

Clone https://github.com/Mike-Wood/electron-window-position-bug-linux
```sh
$ git clone https://github.com/Mike-Wood/electron-window-position-bug-linux
$ cd electron-window-position-bug-linux
$ npm install
$ npm start
```
Then press `Win`+`Ctrl`+`Left` to move it to the side.
Then press `Win`+`Shift`+`A` to call the `.setPosition(500, 100)`.

**Additional Information**

I'm pretty sure this was working in a earlier version of electron not sure which though.
And it's probably the same bug as https://github.com/electron/electron/issues/14291

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
