### ISSUE TITLE
Drop from Windows to Electron window randomly stops working, forever.

### ISSUE THREAD

**Issue by jukefr** [electron/electron#14313]
Okay so this is a weird bug.
I am running Windows 10 1803.
Electron 2.x

Here is a little demo of the bug and it gives an idea of how to reproduce :
![demo](http://g.recordit.co/cKtRqLISYH.gif)

I have no idea how or why this happens but I am pretty sure it is not fiddle specific, not forge specific but electron specific as the first instance I encountered this bug was from an app I started from an `npm init` with electron and Vue.

I have spent 4 days trying to figure out why this happens and how to avoid it with no success..

At first I thought it was maybe because of `frame` or `transparent` or `resize` options on the window, it is not related after testing. (still happens with or without)

Then I thought it could be file permission, nope.

Not related to CSS as there is none apart from a background color in the demo.

Not related to npm or yarn tried both.

It's not related to tooling used as I have the same problem from a project started by hand.

I also want to say that it can happen that a project starts with the feature working, but after doing X action the feature becomes bugged, but I am not entirely sure if this is true, too many factors to take into account...

**Comment by jukefr** [comment]
I spinned up a Linux VM to try it out and I do not experience this bug in any manner, I can drag on every project I try.

This confirms a bug on Windows 10.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by zyead** [comment]
Send a link to the modern version

الحصول على Outlook لـ iOS<https://aka.ms/o0ukef>
________________________________
من: Sofia Nguy <notifications@github.com>
‏‏تم الإرسال: Friday, August 9, 2019 3:03:39 AM
إلى: electron/electron <electron@noreply.github.com>
نسخة: Subscribed <subscribed@noreply.github.com>
‏‏الموضوع: Re: [electron/electron] Drop from Windows to Electron window randomly stops working, forever. (#14313)


Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases.

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the blocked/need-info label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
