### ISSUE TITLE
Electron 3.0.x: apply the fix for localStorage migration

### ISSUE THREAD

**Issue by ecarriou** [electron/electron#14311]
Is it possible to apply the fix for localStorage migration (#12175) in v3.x branch?

I plan to migrate my users from v1.8.x up to v3.x and I need that fix in order to keep their data in the localStorage.

**Comment by deepak1556** [comment]
@ecarriou the fix is available in 3.x, let us know if you face any migration issues with 3.0.x. Thanks!
