### ISSUE TITLE
Cookie URL in cookie object when querying for session cookies

### ISSUE THREAD

**Issue by jarrodek** [electron/electron#14318]
**Is your feature request related to a problem? Please describe.**
My application (REST client) allows to manipulate cookies when making a HTTP request. It also allows to export and import application data. It is possible to export created session cookies data but it is not possible to import them back because the URL used to set the cookie is not available.

**Describe the solution you'd like**
When querying for cookie data from the session class I would like to see another property with original URL used to set the cookie.

**Describe alternatives you've considered**
I was considering creating a database storing cookie with the url but it would defeat the purpose of using this API in the first place as I would have to duplicate the whole API.

**Additional context**
There are few use cases when the user would export cookie data from the application:
- application backup 
- moving application to another machine
- sharing session data with team mates so it's easier for them to use the REST client

In the application the user can configure cookies by either creating a cookie manually or by opening a browser window and logging in to a web service. 

![image](https://user-images.githubusercontent.com/3320020/44633140-ac14a980-a93b-11e8-8993-627683fc058b.png)

When the application makes a request to the endpoint it queries for the cookies to apply them to the request.

This feature would also simplifies cookie removal from the session. Currently when the user request from the panel on the screenshot to remove a cookie the application constructs the url from cookie domain and cookie path. However sometimes I noticed it does not work as intended. Having the URL would also allows the app to handle this issue.

**Comment by nornagon** [comment]
Cookies aren't stored by URL. The domain and path should be enough for you to identify the cookie.
