### ISSUE TITLE
Do not ignore the assertion that Microsoft rc.exe and rc.py produced identical .res files

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#14326]
We got it failing after we've started to use long version numbers for nightlies.
https://github.com/electron/electron/blob/c8705625c9c6989b1d5c03f716e31e16fec6e543/atom/browser/resources/win/atom.rc#L59

The assert has been temporary disabled in https://github.com/electron/libchromiumcontent/pull/657, that change should be reverted.

/cc @MarshallOfSound, @ZacWalk

**Comment by codebytere** [comment]
This has been resolved and can be closed.
