### ISSUE TITLE
DOMException: play() failed because the user didn't interact with the document first.

### ISSUE THREAD

**Issue by AZOPCORP** [electron/electron#14323]
I am trying to playback audio in an hidden electron window and trigger .play() event via IPC callbacks. Unfortunately the new audio policy in Chrome 66 from electron 3.0 prevent that. 
[https://developers.google.com/web/updates/2017/09/autoplay-policy-changes](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes)
As you can see many developers are complaining in the comments. 

I was wondering is there is a workaround for this issue like a way to simulate user interaction in an hidden window.

Thanks in advance

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
