### ISSUE TITLE
WebView and WebContents need executeJavaScriptInIsolatedWorld equivalent

### ISSUE THREAD

**Issue by TheGoddessInari** [electron/electron#14350]
**Is your feature request related to a problem? Please describe.**
This is related to #14288 where I'm trying to run remote untrusted  web content in isolation, as per documentation.

**Describe the solution you'd like**
WebView and WebContents need something like executeJavaScriptInIsolatedWorld, perhaps named executeJavaScriptInIsolatedContext, to be able to actually execute javascript in the isolated context that's created with a webPreferences that turns contextIsolation on.
This should behave according to the documentation, and still allow access to document and window.

**Describe alternatives you've considered**
I've tried looking into executeJavaScriptInIsolatedWorld, but can't get a reference to the specific webFrame needed from webview or webContents. Instead of making users do this manually (which currently doesn't work), exposing a relevant API would be preferential.

**Additional context**
My electron-based app is trying to be security-conscious, but the currently documented methods aren't developer-friendly and are experimental.

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
