### ISSUE TITLE
(electron:26557): libnotify-WARNING **: Failed to connect to proxy

### ISSUE THREAD

**Issue by baisar** [electron/electron#14362]
Hello,
I like Electron very much, I'm new to Electron.
Everything with Electron worked well,, but next day when I do the following code

`const { app, BrowserWindow, Notification, shell } = require("electron")
let win,note
app.on("ready",() => {
	win = new BrowserWindow({width:500,height:500})
	win.loadFile("index.html")
	
        note = new Notification({title: "Title",subtitle: "subtitle",body: "body"})
	
        note.show()
})`

I get error (electron:26557): libnotify-WARNING **: Failed to connect to proxy.

Does anybody know the solution?

I reinstalled Electron, NodeJS, 8-10. No changes

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).

**Comment by penx** [comment]
For anyone landing on this issue wondering how to ignore`libnotify-WARNING **: Failed to connect to proxy` when running an Electron app such as Cypress, you can do the following: 

```sh
cypress run  2> >(grep -v "libnotify-WARNING \*\*: Failed to connect to proxy")
```

This pipes stderr output to grep and filters out lines matching this pattern.
