### ISSUE TITLE
Hidden window causes flicker when maximizing foreground window

### ISSUE THREAD

**Issue by bpasero** [electron/electron#14360]
* Output of `node_modules/.bin/electron --version`: 3.0.0-beta.6
* Operating System (Platform and Version): Windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2.0.x

**Expected Behavior**
A hidden window background color should not be visible.

**Actual behavior**
A hidden window background color causes flicker.

**To Reproduce**
* run a fiddle where the main.js creates 2 window, where the second window is hidden with a red background color
* run the fiddle
* maximize the window
* restore the window
* repeat until you sometimes see the red color of the hidden window flashing through

**main.js**
```javascript
// Modules to control application life and create native browser window
const {app, BrowserWindow} = require('electron')

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
let mainWindow

function createWindow (hidden) {
  // Create the browser window.
  mainWindow = new BrowserWindow({width: 800, height: 600, show: !hidden, backgroundColor: hidden ? "#0000ff" : "#FFFFFF"})

  // and load the index.html of the app.
  mainWindow.loadFile('index.html')

  // Open the DevTools.
  // mainWindow.webContents.openDevTools()

  // Emitted when the window is closed.
  mainWindow.on('closed', function () {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null
  })
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  createWindow();
  createWindow(true);
})

// Quit when all windows are closed.
app.on('window-all-closed', function () {
  // On OS X it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', function () {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (mainWindow === null) {
    createWindow()
  }
})

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.
```

![before](https://user-images.githubusercontent.com/900690/44746014-9228c180-ab09-11e8-886d-40a26bb6e3b2.gif)

**Comment by nitsakh** [comment]
Interesting... I just found that this bug happens in 2.0.9 also. Maybe less frequently, but it did happen.

**Comment by pronebird** [comment]
You can see the same bug when the window appears. Flickers twice. Super weird.

**Comment by jjustin3** [comment]
I've commented in here: [10069](https://github.com/electron/electron/issues/10069)

Seems like the first flicker is the previous state of the window before .hide(). After this flicker, the window will present itself in its true and accurate form. I would imagine this is an issue with transparency and how chromium is handling things?

**Comment by sofianguy** [comment]
@bpasero is this bug still happening in v4.2.x or later?

**Comment by bpasero** [comment]
No
