### ISSUE TITLE
app.getVersion() should be able to return the exe version when requested

### ISSUE THREAD

**Issue by bughit** [electron/electron#14367]
**Is your feature request related to a problem? Please describe.**
The exe version can be more authoritative, electron builder for example can append the build number to the package version for the exe version  .

**Describe the solution you'd like**
getVersion() could take an arg specifying which version to return

**Describe alternatives you've considered**
workaround is to setVersion to an empty string, then getVersion starts returning the exe verion

**Comment by MarshallOfSound** [comment]
Thanks for the feature request, but if you wish to load the version directly from the executable it is relatively straightforward to write userland JS code using existing modules to pull that version.  Adding a flag to do this only on Windows conflates the API needlessly.
