### ISSUE TITLE
Ampersands in tray icon tool-tip in Windows not shown (setToolTip was used)

### ISSUE THREAD

**Issue by LucianZamfira** [electron/electron#14373]
* Output of `node_modules/.bin/electron --version`: 2.0.8
* Operating System (Platform and Version): Windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): --

Hi,
Please help me with the below issue :D

**Actual behavior**
When I add & in the tray icon tool-tip, the & is not shown, even if I'm trying escaping special characters.

**Expected Behavior**
I want to be able to use & in the tray icon tool-tip (Ex: 'A&B application').

**Screenshots**
![code](https://user-images.githubusercontent.com/6073214/44778628-2c2e4f80-ab86-11e8-966e-51abebc624af.png)
![visual](https://user-images.githubusercontent.com/6073214/44778629-2c2e4f80-ab86-11e8-8dff-a0e2aa8f503a.png)

**Comment by MarshallOfSound** [comment]
As per the docs you need to escape ampersands on windows by using `&&` (two in a row)

**Comment by LucianZamfira** [comment]
Hi @MarshallOfSound,

This is not working! I told you that I was using all kind of escaping methods :D (&#39;A && B&#39)

**Comment by LucianZamfira** [comment]
Hi again @MarshallOfSound,

Thanks!!! The solution is : appTray.setToolTip('A&&&B Application');
🥇

**Comment by LucianZamfira** [comment]
Hi @MarshallOfSound ,

The solution with appTray.setToolTip('A&&&B Application'); worked for the tooltip, but I found another issue on the "**Taskbar settings - Select which icons appear on the taskbar**", I get A&&&B Application displayed on the list, please see attached screen :(

![help-me-final](https://user-images.githubusercontent.com/6073214/46287088-15668880-c58a-11e8-9173-43afb46443ef.PNG)
