### ISSUE TITLE
Problem waking multiple monitors from sleep on Win10

### ISSUE THREAD

**Issue by gohanman** [electron/electron#14375]
* Output of `node_modules/.bin/electron --version`: I'm not using node_modules; I'm running electron using the 2.0.8-win32-x64 release w/ code in `resources/app`
* Operating System (Platform and Version): Windows 10 (x64, 1803)
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): n/a

**Expected Behavior**
Windows sleeping and waking monitors should have no impact on electron.

**Actual behavior**
If I run an Electron app w/ just a `BrowserWindow` in fullscreen on a Windows 10 PC w/ two monitors set to mirror mode, when I wake the monitors from sleep only one wakes up correctly. The other remains black but intermittently flashes a mouse cursor. Taking electron out of full screen restores the 2nd monitor.

This doesn't occur if electron isn't fullscreen and doesn't occur if any other app is in the foreground. I've now seen the same behavior on two different PCs.

**To Reproduce**
https://github.com/gohanman/electron-fullscreen

**Additional Information**
I realize this might be difficult to reproduce and could involve hardware specific issues so any pointers how I might debug what's happening would be appreciated.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
