### ISSUE TITLE
The Chromium PDF Viewer plugin is not loaded in a BrowserWindow

### ISSUE THREAD

**Issue by christophpre** [electron/electron#14385]
* Output of `node_modules/.bin/electron --version`: v3.0.0-beta.8
* Operating System (Platform and Version): Windows 10 10.0.16299 Build 16299 / MacOS High Sierra 10.13.4
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v2.0.8

**Expected Behavior**
The Chromium PDF Viewer plugin should be loaded as a Browser Plugin in a Browser Window.

**Actual behavior**
The Chromium PDF Viewer plugin is not loaded in a Browser Window.

**To Reproduce**
Just open a BrowserWindow e.g.:
`new BrowserWindow({
            webPreferences: {
                plugins: true
            }
        });`
Then type in Developer Console: `window.clientInformation.plugins`

**Screenshots**
Before (v.2.0.8):
![image](https://user-images.githubusercontent.com/6893212/44843061-b4285e00-ac47-11e8-9f68-f406e571e1f5.png)

After (v3.0.0-beta.8):
![image](https://user-images.githubusercontent.com/6893212/44843107-d0c49600-ac47-11e8-8a5b-83e6a559ed0f.png)

**Additional Information**
Note: options.webPreferences.plugins = true; is set on all BrowserWindow instances. So this should not be an issue, since it is working correctly in electron@2.0.8

**Comment by jkleinsc** [comment]
The PDF viewer is currently not working in 3-0-x and there is an issue #12337 to resolve it.  Closing this issue as a duplicate to #12337

**Comment by christophpre** [comment]
Sorry, overlooked that there was already an issue. Thanks for closing.
