### ISSUE TITLE
Windows 10 webview DevTools open in a too small window

### ISSUE THREAD

**Issue by christophpre** [electron/electron#14383]
* Output of `node_modules/.bin/electron --version`: v3.0.0-beta.8
* Operating System (Platform and Version): Windows 10 10.0.16299 Build 16299
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v2.0.8

**Expected Behavior**
Webview DevTools should open in a window that is properly sized.

**Actual behavior**
Webview DevTools open in window with minimal size and are therefore not visible.

**To Reproduce**
**Edit** Works in BrowserWindow.webContents.openDevTools() Works **not** in webView.openDevTools()

**Screenshots**
![too_small_devtools_window](https://user-images.githubusercontent.com/6893212/44841398-850fed80-ac43-11e8-8bed-849d45473683.png)

**Additional Information**
Only reproducible on Windows 10 10.0.16299 Build 16299. Works correctly on MacOS High Sierra 10.13.4

**Comment by t57ser** [comment]
I can see the same on windows 7 and on Linux (manjaro)

**Comment by SaschaA1982** [comment]
Same problem on Ubuntu 18.02...
DevTools-Window is of minimal dimension at the top left corner of the screen.
After resizing the window, the problem is gone for the actual start of electron. Once restartet, the problem is back.

electron 2.0.x still working as expected.

**Comment by christophpre** [comment]
Edited the Bug Description, since I just tried something out again:

**Works** in BrowserWindow.webContents.openDevTools() **Works not** in webView.openDevTools()
