### ISSUE TITLE
dont know how many screens connect

### ISSUE THREAD

**Issue by kerwin1** [electron/electron#14381]
**Is your feature request related to a problem? Please describe.**
Hey,I have a question about how to let my app show another screen and full of it.(multiple scrrens).

**Describe the solution you'd like**
Provide a method to get how many scrrens connected, and I can get the position of screens to let app show anywhere.

**Describe alternatives you've considered**

**Additional context**

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
