### ISSUE TITLE
DesktopCapturer returning wrong name for Entire screen on dual monitor setup

### ISSUE THREAD

**Issue by Th3S4mur41** [electron/electron#14397]
[Documentation:](https://electronjs.org/docs/api/structures/desktop-capturer-source) A screen source will be named either Entire Screen or Screen <index>.

The following code
 ```
desktopCapturer.getSources(['screen']).then(function (sources) {
    LogSvc.debug('[SharingDialogCtrl]: Sources', sources);
});
```
returns this output
```
18-08-30 16:18:49.990 DEBUG [SharingDialogCtrl]: Sources[
   {
      "id": "screen:0:0",
      "name": "Screen 1",
      "thumbnail": {},
      "imgSrc": "data:image/png;base64,iVBO"
   },
   {
      "id": "screen:1:0",
      "name": "Screen 2",
      "thumbnail": {},
      "imgSrc": "data:image/png;base64,iVBORw="
   },
   {
      "id": "screen:5:0",
      "name": "Screen 3",
      "thumbnail": {},
      "imgSrc": "data:image/png;base64,iVBO="
   }
] 
```

The code is executed on a dual monitor setup and the output is to be understood as this:
- Screen 1 = Monitor 1
- Screen 2 = Monitor 2
- Screen 3 = Entire Desktop (Monitor 1 & 2)

Based on documentation above "Screen 3" should actually be named "Entire Screen" in this use case

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
