### ISSUE TITLE
win.moveTop() crashes

### ISSUE THREAD

**Issue by scarlac** [electron/electron#14392]
* Output of `node_modules/.bin/electron --version`:
**2.0.8**
* Operating System (Platform and Version):
**Window Version 10.0.10240 Build 10240**
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):
**N/A**

**Expected Behavior**
Window goes to top.

**Actual behavior**
Application crashes.

**To Reproduce**
1. Open a new `win = BrowserWindow(...)`.
2. Trigger `win.moveTop()`.
3. Application crashes.

**Additional Information**
The error is consistently reproducible for me.

**Comment by gavinXD** [comment]
So after reproducing the issue, I have realized that the error that I am getting is the function doesn't exist. more specifically win.moveTop() is not a function. After removing the braces from the program I did not receive the error again. I am not sure if this is a documentation error as in the documentation it says win.moveTop() not win.moveTop

**Comment by scarlac** [comment]
@gavinXD Thank you for following up on this. On Tuesday I was actually going over this issue and realized that it's a documentation issue, since documentation for `BrowserWindow` doesn't say when the `moveTop()` function is available from. It turns out it's only been available since Electron 3.0.

I'll close this issue and re-open a new one that asks for version notes in docs instead.

**Comment by lakshmipathyarjun6** [comment]
Is this operation supported on Linux? It looks like this PR[https://github.com/electron/electron/pull/12485] explicitly mentioned Win32 and OSX - thought this implied that Linux was already supported and functionality was only being extended, but get the "moveTop is not a function" on the latest Ubuntu dist. 

Running electron v5.0.4
