### ISSUE TITLE
WEBVIEW-- Not get killed by main process?

### ISSUE THREAD

**Issue by wahabch** [electron/electron#14417]
I have 1 main process and 1 rendered Process (webview). 
My problem is when i call

  app.on('Window-all-closed',()=>{
   
        app.quit();

});

It kill main process but rendered remains. 

It results in multiple process remain in background processes. 

every time I open my app it multiply it.

**Comment by codebytere** [comment]
Hi @wahabch, you removed information from the template about version, platform, and other context that would allow us to begin to diagnose this.

We can't begin to look at this issue until we have that information, so if you could add it that would be great.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
