### ISSUE TITLE
customButtonsOnHover - buttons do not function on click

### ISSUE THREAD

**Issue by Slapbox** [electron/electron#14412]
* Output of `node_modules/.bin/electron --version`: `electron@3.0.0-beta.7`
* Operating System (Platform and Version): macOS 10.13.6
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): Unknown

**Expected Behavior**
Buttons maximize, minimize, close window

**Actual behavior**
Nothing happens.
http://recordit.co/mhd54NzzMz

**To Reproduce**
Unknown. Having this issue even with a nearly empty DOM

**Screenshots**
![image](https://user-images.githubusercontent.com/6835891/44940340-289ff180-ad5b-11e8-8c43-bc39a2da62d2.png)

**Additional Information**
None so far

**Comment by Slapbox** [comment]
### Reproduction steps:

```
$ git clone https://github.com/hokein/electron-sample-apps
$ cd electron-sample-apps
$ yarn add electron
$ npx electron --version
v3.0.2
```

**Edit main.js**
- Modify line 14 to:  `mainWindow = new BrowserWindow({width: 360, height: 300, frame: false, 
    titleBarStyle: 'customButtonsOnHover'});`

**Edit index.html**
- Delete contents of `<body>` tag

```
$ npx electron frameless-window
```

### Result: http://recordit.co/EDw0nv7XNd

**Comment by codebytere** [comment]
@Slapbox this died between betas 1 and 2 of `3-0-x`; i'm investigating and should hopefully have answers soon!

**Comment by Slapbox** [comment]
Thanks for the update @codebytere!
