### ISSUE TITLE
Debug/Execution paused overlay doesn't consistently show in Electron 3

### ISSUE THREAD

**Issue by Slapbox** [electron/electron#14416]
* Output of `node_modules/.bin/electron --version`: `electron@3.0.0-beta.7`
* Operating System (Platform and Version): Windows 7 x64 && macOS 10.13.6
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): `electron@2.0.7`

**Expected Behavior**
Debug/execution paused overlay shows when breakpoint is hit

**Actual behavior**
Overlay does not appear unless window is manually resized after code execution pauses at a breakpoint. Exceptions to this rule seem to be:
1. Hitting the first breakpoint after starting the application (overlay shows fine then)
2. Manually pausing execution at an arbitrary point (overlay usually shows fine then)

**Additional Information**

Toggling the option to show the overlay doesn't resolve this, nor does clearing the userdata folders for the instance of Electron.

This issue affects frameless and framed windows.

**Comment by Slapbox** [comment]
I'm still seeing this on at least Windows 7 in `Electron@3.0.7`

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by Slapbox** [comment]
I continue to experience this issue in every version of Electron later than version `2.x.x`. It's very frustrating, as code execution can be stopped without any obvious indication.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
