### ISSUE TITLE
win.SetContentProtection(true) lets external apps to capture screen of electron app in macOS

### ISSUE THREAD

**Issue by sadi304** [electron/electron#14415]
* Output of `node_modules/.bin/electron --version`: v2.0.3
* Operating System (Platform and Version):  macOS High Sierra

**Expected Behavior**

Setting window.setContentProtection(true), should resist the external apps to capture the screen of the electron app

**Actual behavior**
Quicktime player can capture and record the screen of the electron app, with setContentProtection(true)

**To Reproduce**

Create a new electron project, use setContentProtection(true) on window, capture in mac with quick time player

**Comment by sadi304** [comment]
@sofianguy will it be fixed in coming version? any update?

**Comment by miniak** [comment]
@sadi304 This is OS API limitation. We use `[NSWindow setSharingType:NSWindowSharingNone]`, which does not prevent QuickTime from capturing the window unfortunately.

**Comment by miniak** [comment]
@sadi304 If you figure out how to do it, feel free to create a PR

**Comment by sadi304** [comment]
@miniak  thanks for the info. yeah i also found out the OS limitation. I dont think i have the capacity to fix that deep level api currently :p anyway thanks again

**Comment by paulius005** [comment]
@sadi304 Would anyone be able to point us in the right direction of how we can contribute to a fix, and possibly backporting it?

Having this working on Mac would have a dramatic impact on the flexiblity of the way we build our recording product at Loom
