### ISSUE TITLE
centos server  can't run electron 

### ISSUE THREAD

**Issue by istonewei** [electron/electron#14419]
# lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.2.1511 (Core) 
Release:	7.2.1511
Codename:	Core

-------------------------------------------------------------------------------------------

#node -v 
v10.9.0
#npm -v
6.2.0
#npm install --save-dev electron
success
---------------------------------------------------------------------------------------------
when i execute "electron -v", There will be many kinds of mistakes。
#electron -v
/usr/local/node/node8.11.1/lib/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
or
/usr/local/node/node8.11.1/lib/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

**Comment by MarshallOfSound** [comment]
@istonewei Electron requires a desktop environment to run and can't run headless on a server OS.  You'll need to install all required desktop dependencies and run `xfvb` if you want to run Electron in a server environment.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
