### ISSUE TITLE
Change menu label in tray dynamically

### ISSUE THREAD

**Issue by arminghm** [electron/electron#14414]
I want to add a timer in tray menu, but label will not be changed dynamically
 
Any other suggestion how to implement something like this?

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).

**Comment by arminghm** [comment]
@sofianguy isn't this an issue that I can't change the menu label dynamically?
when you change the label it will be changed, but the tray menu shows the last label, event after calling setContextMenu again
