### ISSUE TITLE
Following documentation, yet "Cannot create BrowserWindow before app is ready"

### ISSUE THREAD

**Issue by krainboltgreene** [electron/electron#14425]
* Output of `node_modules/.bin/electron --version`: v2.0.8
* Operating System (Platform and Version): 
  - ProductName:	Mac OS X
  - ProductVersion:	10.13.6
  - BuildVersion:	17G65

**Expected Behavior**
What is detailed in https://github.com/electron/electron/blob/v2.0.8/docs/api/browser-window.md#browserwindow

**Actual behavior**

```
> electron './tmp/server.js'

App threw an error during load
Error: Cannot create BrowserWindow before app is ready
```

**To Reproduce**
https://github.com/krainboltgreene/blank-electron-react

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone https://github.com/krainboltgreene/blank-electron-react
$ npm install
$ npm run build
$ npm run start
```

**Notes**

It's been a long time since I made an electron app and all the documentation is different, but literally copying the examples doesn't seem to work for me.

**Comment by MarshallOfSound** [comment]
As per the error message you can't construct `BrowserWindow` instances before the app is ready.  You need to wait for the `ready` event on the `app` object.

```js
app.on('ready', () => createMyWindow())
```

**Comment by krainboltgreene** [comment]
Sorry, I guess I wasn't clear. It's not that I don't know how to make this work, it's that the documentation below suggests that I don't even need the `ready` event:

https://electronjs.org/docs/api/browser-window
https://electronjs.org/docs/tutorial/application-architecture

Are these snippets wrong?

**Comment by MarshallOfSound** [comment]
> Are these snippets wrong?

I wouldn't call them wrong, but I can see how people can run into this issue by simply copy pasting those snippets and not having the full context from other tutorials / docs.  These snippets aren't really designed to be functioning apps and I don't want them to all become bloated with `app.on('ready')` or `app.whenReady.then()` calls.  Do you have any suggestions for how to make this clear without bloating the code examples?

**Comment by krainboltgreene** [comment]
I guess the one that really tripped me up was https://electronjs.org/docs/api/browser-window#using-ready-to-show-event which explicitly seems to tell me there's an alternative. This is hard problem, I don't envy that. Thanks for the insight.
