### ISSUE TITLE
a javascript error occurred in the main process

### ISSUE THREAD

**Issue by mohammadjalili** [electron/electron#14421]
* Output of `node_modules/.bin/electron --version`: **v2.0.7**
* Operating System (Platform and Version): **windows**
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): **v2.0.7**

**Additional Information**
 i can start my electron app with **electorn .**
but when i export windows portable app i get this error.
**Screenshots**
[Screenshots](https://pasteboard.co/HC1OiyJ.png)

**Comment by MarshallOfSound** [comment]
This is not an issue with electron rather you packaged app does not have `request` installed.  This probably means it isn't in your package.json or it is saved as a draft dependency

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
