### ISSUE TITLE
Cannot disable security warning on arch linux.

### ISSUE THREAD

**Issue by midori-tooyama** [electron/electron#14429]
* Output of `node_modules/.bin/electron --version`: v2.0.8
* Operating System (Platform and Version): Arch Linux latest

**Expected Behavior**
No security warning after set: 

```
process.env.ELECTRON_DISABLE_SECURITY_WARNINGS = true;
```

**Actual behavior**
Security warning still exists.

**Additional Information**
When running on a macOS, there is no security warning.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by midori-tooyama** [comment]
I mean the same code has different behaviors on Arch linux add macOS. Is it considered not a bug?
