### ISSUE TITLE
Drag-Drop element freeze application in Electron 3.0.0

### ISSUE THREAD

**Issue by u4aew** [electron/electron#14430]
- Electron version: 2.X.X, 3.X.X, 4.X.X 
- Operating system: 4.17.12-200.fc28.x86_64 GNU/Linux
- Hardware: Intel HD Graphics 510

### Expected behavior
Drag and drop without freeze the application.

### Actual behavior
When drag an element it freeze application. No messages on debug, just freeze.

### How to reproduce
Drag text, link or button in application. 
The application starts working if the flag is enabled --disable-gpu, but this is not a solution to the problem

### UPD 
Updated to the latest version of the electron 3.0.0, the problem persists, 
### UPD 2 
**The problem occurs when the application is launched through the console.**

![electron3-bug](https://user-images.githubusercontent.com/18558430/45876404-c91a8c00-bdc4-11e8-9d02-f2556d77058e.png)

![bug](https://user-images.githubusercontent.com/18558430/44968625-21ebc700-af73-11e8-87e4-83cd7c272810.png)

In chromium, there is no such problem

![chromium](https://user-images.githubusercontent.com/18558430/45876459-e6e7f100-bdc4-11e8-99bc-8a092361fd06.png)

The problem is observed in production applications

![bug2](https://user-images.githubusercontent.com/18558430/44972307-e78a2600-af82-11e8-8197-c17f575cc2e1.png)

### Additionally
Something similar happens in nw.js, but only the application does not hang, but an error appears in the console
![nwjs](https://user-images.githubusercontent.com/18558430/45876692-8a390600-bdc5-11e8-8552-83fa665a262c.png)

**Comment by dos1** [comment]
Same issue here on Arch with Plasma 5. What's interesting - it happens only when electron is started via console. When I launch it via .desktop entry in the Kickoff menu, it works fine. Tested with several apps, can be reproduced reliably.

**Comment by dos1** [comment]
A recent update to Electron 2.0.11 in Arch repos seems to have fixed this issue for me.

**Comment by u4aew** [comment]
@dos1 checked on Electron 2.0.11, the bug remained

**Comment by devnoname120** [comment]
I can confirm that I have the issue with electron `2.0.12`.

If it helps:

```
noname120% neofetch
                   -`                    rop@ROPex 
                  .o+`                   --------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: 4291B66 ThinkPad X220 
               `+oooooo:                 Kernel: 4.18.16-arch1-1-ARCH 
               -+oooooo+:                Uptime: 2 days, 13 hours, 6 mins 
             `/:-:++oooo+:               Packages: 835 (pacman) 
            `/++++/+++++++:              Shell: zsh 5.6.2 
           `/++++++++++++++:             Resolution: 1366x768 
          `/+++ooooooooooooo/`           WM: i3 
         ./ooosssso++osssssso+`          Theme: deepin [GTK2/3] 
        .oossssso-````/ossssss+`         Icons: Adwaita [GTK2/3] 
       -osssssso.      :ssssssso.        Terminal: urxvtd 
      :osssssss/        osssso+++.       Terminal Font: bitstream vera sans mono 
     /ossssssss/        +ssssooo/-       CPU: Intel i5-2520M (4) @ 3.200GHz 
   `/ossssso+/:-        -:/+osssso+-     GPU: Intel 2nd Generation Core Processor Family 
  `+sso+:-`                 `.-/+oso:    Memory: 3495MiB / 7863MiB 
 `++:.                           `-/+/
 .`                                 `/                           

```

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
