### ISSUE TITLE
DesktopCapaturer on Win 32 Machine not working when system is logged off

### ISSUE THREAD

**Issue by chandrakanthi07** [electron/electron#14433]
* electron version 1.7.8
* Windows 7(32 bit)
*
**Expected Behavior**
When the system is logged off, desktopcapturer should capture the screens , like it is working fine in Windows 7 64bit.

**Actual behavior**
After the system is logged of(after locking screen) , no screenshots of the screen are captured.After logging in to windows, screenshot capture works fine.

**To Reproduce**
Cannot setup a Repo.
I am using the below code
  desktopCapturer.getSources(options, function(error, sources) {
       
          if (error) {
              logger.error('Screenshot:Error occured while capturing screenshot');
              return console.log(error)
          }
    
          logger.info('ScreenShot: No of monitors: '+ sources.length);
          logger.info('ScreenShot: ScreenShot capture: Done');
          for (let i = 0; i < sources.length; ++i) {
            screen_array.unshift(sources[i].thumbnail.toPNG())
          }
		  });
in the above code sources array is not having the required data.

PLease suggest a workaround as it is effecting the project release

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by chandrakanthi07** [comment]
Hi 
I have downloaded electron version 4.0.0 and the issue persists in this version as well.
The issue is as follows:
In Windows 32 bit system, the desktopcapturer module doesnot capture screenshot of the desktop, when the windows is locked(Windows key and L shortcut)
