### ISSUE TITLE
is it possible to send blob to WebView from host process?

### ISSUE THREAD

**Issue by ravibpatel** [electron/electron#14431]
I want to pass file I downloaded using web request as blob to WebView but it messes up the object when I try to read it in web view.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by jlindberg-oss** [comment]
@ravibpatel were you able to get this question answered anywhere?

**Comment by ravibpatel** [comment]
@jlindberg-oss I think you can save the blob to a temp file and then read it back in the web view.
