### ISSUE TITLE
pacScript config for session.setProxy() method doesn't work in electron v3.0.0-beta.3

### ISSUE THREAD

**Issue by dhammika-marasinghe** [electron/electron#14441]
* Electron version: v3.0.0-beta.3
  * Operating system: Windows 10 Enterprise 10.0.15063 (x64) 
  * Last known working Electron version: v1.4.16

**Expected Behavior**
  Electron app should either detect *Use automatic configuration script* mentioned in the *Internet Options > Connection > LAN Settings > Automatic Configuration*
  OR 
  by passing the pacScript to the .setProxy() method of session object. 
https://electronjs.org/docs/api/session#sessetproxyconfig-callback
  ```
  // in main.js
  var electron = require('electron');
  var path = require('path');
  var BrowserWindow = electron.BrowserWindow;

  mainWindow = new BrowserWindow({
      webPreferences: {webSecurity: false},
      width: 1024,
      height: 728,
      kiosk: true,
      backgroundColor: "#000000",
      show: false,
      acceptFirstMouse: true
    }); 

 mainWindow.webContents.session.setProxy({pacScript:"http://proxy.xyz.com:9001/production.pac"}, 
      function() {
            mainWindow.loadURL(`file://${path.join(__dirname, "/dist/app.html")}`);
  });
  ```

**Actual behavior**
Electron app does not detect proxy settings. 

**To Reproduce**
Setup proxy using a pac script

**Additional Information**
 It does identify the proxy when we pass proxyRules to the ses.setProxy(config, callback) 
  ```
  {proxyRules: "proxy.xyz.com:3128", proxyBypassRules: "localhost"}
  ```
  OR 
  when we use *Internet Options > Connection > LAN Settings > Proxy Server* setting on the windows 
  ![screenshot](https://i.imgur.com/I4TTRjz.png)

**Comment by sofianguy** [comment]
Can you give 2.0.8 a try and let us know if the bug still persists on that version?
