### ISSUE TITLE
openExternal in the same tab

### ISSUE THREAD

**Issue by brunokunace** [electron/electron#14457]
Hi everyone, 

i make a electron app, with socket, when i receive new order, make a popup on screen with external url.
I use a openExternal and works fine, but every order open in a new tab of chrome browse, have way to open in the same tab or close the especific tab and create a new one?

My pc open 50 tabs for hour =(.

accept other ideas too.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
