### ISSUE TITLE
Cookie set by server couldn't save expires / max-age (on 2.0.8 and 1.8.8)

### ISSUE THREAD

**Issue by eric8810** [electron/electron#14464]
**Version**
2.0.8 and 1.8.8

**Expected Behavior**
When use chrome visit the website, cookie has been successfully set by server to 1969-12-31T23:59:59.000Z

![image](https://user-images.githubusercontent.com/756579/45106703-ec5cfe80-b169-11e8-8592-0f515f5c1966.png)

**Actual behavior**
Then use electron , we only got session...and the cookie lost when app restart

![image](https://user-images.githubusercontent.com/756579/45106663-d0f1f380-b169-11e8-99cb-7b30721cdaa4.png)

**To Reproduce**
run a express cookie demo, and set custom cookie expire time
visit it by electron

**Screenshots**
Provide above

**Comment by eric8810** [comment]
BTW, here's full response header info

```
{
  "server": "nginx/1.8.1",
  "date": "Wed, 05 Sep 2018 15:59:37 GMT",
  "content-type": "text/html;charset=UTF-8",
  "transfer-encoding": "chunked",
  "connection": "close",
  "vary": "Accept-Encoding",
  "x-frame-options": "SAMEORIGIN",
  "cache-control": "no-store, no-cache, must-revalidate, max-age=0",
  "etag": "W/\"0096cbd37f2a5218c33bb0826a7c74cbf\"",
  "p3p": "CP=CAO PSA OUR",
  "content-encoding": "gzip"
}
```

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
