### ISSUE TITLE
Input cursor invisible after navigation in webview

### ISSUE THREAD

**Issue by christophpre** [electron/electron#14474]
* Output of `node_modules/.bin/electron --version`: v3.0.0-beta.9
* Operating System (Platform and Version): Windows 10 10.0.16299 Build 16299 **and** MacOS High Sierra 10.13.6
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v2.0.8

**Expected Behavior**
If I navigate inside a webview on a page, the position cursor should still be visible when input fields have focus.

**Actual behavior**
If I navigate inside a webview on a page, the position cursor is invisible. Typing is still possible though.

**To Reproduce**
1. webview.loadUrl('http://www.google.com') or set src attribute
2. In google search for something and press enter.
3. On the results page, when the searchfield is focused, the cursor is not visible.

Can be reproduced on any webpage.

**Screenshots**
![image](https://user-images.githubusercontent.com/6893212/45138881-4aabd080-b1ae-11e8-9ed0-7ecea055a742.png)
![image](https://user-images.githubusercontent.com/6893212/45138898-57c8bf80-b1ae-11e8-8a0b-ce3ac56d77b6.png)

**Additional Information**
If the BrowserWindow is minimized and restored, the cursor becomes visible again.

**Comment by javan** [comment]
There are number of issues with focus and selection within `<webview>`s. See https://github.com/electron/electron/issues/4539#issuecomment-250991454 for a somewhat related discussion.

**Comment by steverandy** [comment]
I'm seeing similar issue on v3.0.0-beta.12 too.

**Comment by kempy007** [comment]
Plus another 1

**Comment by kempy007** [comment]
platform/linux

**Comment by kempy007** [comment]
If you go to where electron window opens and click in the input field, it begins to show in the client, not sure if that will help.

**Comment by omarkilani** [comment]
+1 from Remember The Milk. We've been trying to work around this with a liberal application of webview.focus() everywhere but there are edge cases where it doesn't quite work 100%.

**Comment by steverandy** [comment]
I'm using this as temporary solution:

```javascript
webviewElement.addEventListener("load-commit", this.handleLoadCommit);

handleLoadCommit(event) {
  // Invoke webview blur here as temp fix for focus issue
  // https://github.com/electron/electron/issues/14474
  invoke(this.webviewRef.current, "blur");
}
```

**Comment by andrewpaprotsky** [comment]
Here's a workaround that we use for now:
```javascript
  webview.addEventListener("dom-ready", event => {
    // Remove this once https://github.com/electron/electron/issues/14474 is fixed
    webview.blur();

    webview.focus();
  });
```

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by javan** [comment]
This is still an issue in Electron v4.2.x, v5.x.x, and v6.x.x. Here's a fiddle that reproduces the issue: https://gist.github.com/javan/065f33eef107594f232d3c54a5fa279f

Inputs in `<webview>`s don't focus correctly after reloading or navigating:
![webview-input-focus](https://user-images.githubusercontent.com/5355/62825218-4504fa80-bb76-11e9-891d-730742140a88.gif)
Note how the cursor disappears after clicking *Go*, which reloads the `<webview>`. Also note that the input's focus outline doesn't display even though it's focused, and the text selection highlight is gray instead of blue.

**Comment by jaykumarthaker** [comment]
Not sure why but ```dom-ready``` doesn't seems to work for me. Whreas ```did-stop-loading``` did work:
```
webview.addEventListener('did-stop-loading', () => {
  webview.blur();
  webview.focus();
});
```

**Comment by christophpre** [comment]
@sofianguy I've just tested this issue again with current Electron versions with the following outcome:

- 6.1.10 ❌ 
- 7.2.3 ❌ 
- 8.2.3 ❌ 
- 9.0.0-beta.18 ✔️ 

Since this is working from 9.X.X upward, would you want to keep this issue open or can we close it?

**Comment by ffflorian** [comment]
The problem still exists in 9.1.0.

**Comment by roguexiaohuihui** [comment]
This problem is transmitted 6.X. It still exists. How to deal with it?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by pushkin-** [comment]
not able to repro with Electron 12.0.1
