### ISSUE TITLE
Inconsistent "appData" and "logs" path names

### ISSUE THREAD

**Issue by primalanomaly** [electron/electron#14470]
Electron v2.0.8
Mac and Windows

As package.json does not allow spaces in the name field, my app is named "MyApp". In my build settings my productName is set to "My App" so that the user sees the name with spaces.

Using app.getPath('appData') the app data path clearly uses the "name" and saves all data in a folder named "MyApp" in my library.
Using app.getPath('logs') the log path uses the "productName" field and saves all logs in a folder named "My App". This is inconsistent, and results in multiple folders being created instead of just 1.

Using third-party log apps such as "electron-store" saves logs to the folder "MyApp" along with the appData, so it seems it is just Electron's logs path that is wrong.

```
{
  "name": "MyApp",
  "version": "0.0.1",
  "main": "./js/app.js",
  "scripts": {
    "start": "electron .",
    "build": "electron-builder --dir -mw --ia32 --x64",
    "ship": "electron-builder -mw --ia32 --x64 -p always",
    "postinstall": "electron-builder install-app-deps"
  },
  "build": {
    "appId": "com.my.app",
    "productName": "My App"
```

**Comment by bpasero** [comment]
https://github.com/electron/electron/issues/14276 ?

**Comment by joernroeder** [comment]
same behavior with electron 3.0.13
