### ISSUE TITLE
getDisplayNearestPoint throws an error with not rounded numbers

### ISSUE THREAD

**Issue by martpie** [electron/electron#14490]
* Output of `node_modules/.bin/electron --version`: 2.0.8
* Operating System (Platform and Version): macOS (reproducible on all platforms)

**Expected Behavior**
When using `electron.screen.getDisplayNearestPoint()` with a not rounded value (like 0.5), electron should round it properly, or at least not crash. (or it should be documented, with a clearer error)

**Actual behavior**
<img width="532" alt="screen shot 2018-09-07 at 14 43 42" src="https://user-images.githubusercontent.com/1311607/45219858-84fb9780-b2ac-11e8-8e7e-75ba8312f20b.png">

TypeScript did not catch this error because the value is still a number and there is no concept of "integer-only" variables in JS

**To Reproduce**
Anywhere on `app.ready`

``` javascript 
const display = electron.screen.getDisplayNearestPoint({
  x: 100.5, // HERE -> x_x
  y: 100
});
```

**Comment by martpie** [comment]
Issue found when debugging https://github.com/martpie/museeks/issues/460#

**Comment by MarshallOfSound** [comment]
I was about to document this as "users should round these numbers", then realized if that's the case for 100% of people we should just do the rounding in the converter 🤔 I'll document that this is the new behavior and call it `semver/minor`
