### ISSUE TITLE
64-bit Electron v2.0.8 wont' start at all

### ISSUE THREAD

**Issue by MMhunter** [electron/electron#14500]
Electron Version: v2.0.8
OS Version: Windows 7 SP1 (Internal Version 7061)

**Expected Behavior**
The application starts.

**Actual behavior**
Nothing happens.

**To Reproduce**
1.  Install the Application (packed by electron-builder)
2. double click the shortcut.
3. Nothing happens.

**Additional Information**
We are developing a 64-bit desktop application with Electron v2.0.x. Recently two of our users reported that the app won't start at all on their windows machine. But it was very weird that our old version(with electron v1.7.x, 64-bit) works fine. Also 32-bit v.2.0.8 applications like [electron api demos](https://github.com/electron/electron-api-demos/releases) is working properly. 

Same Issue happens when we asked them to try using VS Code. VS Code 1.26(shipped with electron v1.7.x) is good but VSCode 1.27 is broken. [https://github.com/Microsoft/vscode/issues/58163](https://github.com/Microsoft/vscode/issues/58163)

They just double clicked the shortcut and nothing happened. No process in the the process manager. No output was given when try to run the app in command line. 

When we put our app code folder under the `/resource` folder in packed 32-bit electron v.2.0.8 applications, it started (though malfunctioned due to some c++ add-on modules).  

We attempted to ask our users facing this issue to try [electron-quick-start](https://github.com/electron/electron-quick-start). But there is still no response. This issue was totally not reproducible on our machines.

One of these users reported that this issue is gone after few days.  And he claimed that he did no change to his machine. All of our users are Chinese users so i wonder if this has something to do with any other security softwares.

**Comment by oHaiyang** [comment]
We met the same problem on Electron 2.0.12.
Has this been fixed on newer versions?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
