### ISSUE TITLE
GPU process crashes on 3.0.0-beta.10

### ISSUE THREAD

**Issue by KochiyaOcean** [electron/electron#14509]
* Output of `node_modules/.bin/electron --version`: 3.0.0-beta.10
* Operating System (Platform and Version): Windows 10 1803
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 3.0.0-beta.9

**Expected Behavior**
GPU Process should not crash

**Actual behavior**
GPU Process crashed

**To Reproduce**
Run electron and open `chrome://gpu`
Page shows `GPU process was unable to boot: GPU process crashed too many times with SwiftShader.`

**Screenshots**
![image](https://user-images.githubusercontent.com/8194131/45263603-fa12cc80-b466-11e8-8aa6-a12b3f730cd8.png)

**Comment by deepak1556** [comment]
Seems like it worked right with `3.0.0-beta.9` for your app , can you paste the result of `chrome://gpu` for that version. We haven't made any gpu related changes between these two betas, which is what makes this issue confusing. Can this be tested with a minimal app, if so can you share it ? Thanks!

**Comment by KochiyaOcean** [comment]
Seems its hard to reproduce. I will check my system configuration later.

**Comment by KochiyaOcean** [comment]
GPU process still crashes on 3.0.0, and here is logs of electron when GPU process crashes:

```
[7148:0920/051823.013:VERBOSE1:gpu_init.cc(203)] gl::init::InitializeGLNoExtensionsOneOff failed
...
[19496:0920/051823.462:VERBOSE1:gpu_init.cc(203)] gl::init::InitializeGLNoExtensionsOneOff failed
[19496:0920/051823.636:ERROR:viz_main_impl.cc(195)] Exiting GPU process due to errors during initialization
...
[22872:0920/051823.643:ERROR:browser_gpu_channel_host_factory.cc(119)] Failed to launch GPU process.
[2724:0920/051823.643:VERBOSE1:render_accessibility_impl.cc(475)] Accessibility event: layoutComplete on node id 1
AXTreeUpdate tree data: doctype=html loaded=true loading_progress=1 mimetype=text/html focus_id=1 routing_id=1
AXTreeUpdate: root id 1
id=1 rootWebArea FOCUSABLE (0, 0)-(1353, 902) scroll_x=0 scroll_y=0 scroll_x_min=0 scroll_y_min=0 scroll_x_max=0 scroll_y_max=0 value= clips_children=true actions=

[22872:0920/051823.643:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.
```

**Comment by KochiyaOcean** [comment]
GPU process won't crash if `--in-process-gpu` switch is appended

**Comment by KochiyaOcean** [comment]
Seems it only occurs when running 32bit electron on 64bit system.
