### ISSUE TITLE
ipcRenderer.once() not removing listener (REACT)

### ISSUE THREAD

**Issue by Jarmahent** [electron/electron#14507]
* Output of `node_modules/.bin/electron --version`:
v2.0.6

* Operating System (Platform and Version):
Windows 10 build #17134.228

**Expected Behavior**
ipcRenderer.once() should remove the listener after its called once

**Actual behavior**
I have to forcefully remove the event with 

`ipcRenderer.removeAllListeners('db-ch', this.componentDidUpdate);`

**To Reproduce**

In React:

```js
  componentDidUpdate() {
    ipcRenderer.once('db-ch', (event, args) => { // Runs once, after this is should remove itself
      const date = new Date();

      const { clipArray } = this.state;

      if (!clipArray.includes(args.toString())) {
        // Dont add the data to the db if its already there
        this.props.insertData(args, date.toString());
      }

      this.setState(prevState => {
        const removeDupes = this.util.removeDuplicates([
          args,
          ...prevState.clipArray
        ]);

        return { clipArray: removeDupes };
      });
    });
  }
```

This does not work because it leads to a memory leak in react:
![alt text](https://i.imgur.com/DRQBFxs.png "Logo Title Text 1")

I have to forcefully remove the listener when the component in React unmounts with:
```js
componentWillUnmount() {
  ipcRenderer.removeAllListeners('db-ch', this.componentDidUpdate);
}
```

**Screenshots**

**Additional Information**
The full pastebin to the component in question is [located here](https://pastebin.com/VUaceF2m)

**Comment by MarshallOfSound** [comment]
> componentDidUpdate

You are adding the listener every time the component updates, this means that when your listener is set the first time and fired, you call `setState` which will then trigger another update and attach another listener.

If you truly only want your listener to be attached once you should listen in `componentDidMount`
