### ISSUE TITLE
Electron app crashes on fs.writeFile()/fse.writefile()

### ISSUE THREAD

**Issue by naqashse102** [electron/electron#14502]
Electron version 1.8.8
Using Electron with Angular6
![image](https://user-images.githubusercontent.com/36957424/45252555-a4102d00-b371-11e8-9b29-78d431b23ebf.png)

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
