### ISSUE TITLE
With context isolation unsafe-eval warning is displayed even when page is secured

### ISSUE THREAD

**Issue by kayahr** [electron/electron#14510]
* Electron: **v3.0.0-beta.10**  and **v2.0.8**
* Operating System: **Debian Linux 9.5**

### Expected behavior

When page is secured by a CSP header to not allow eval or function constructor then Electron should not display a warning that eval wasn't disabled. 

### Actual behavior

When context isolation is enabled then electron displays a warning even though CSP header is present and has no `unsafe-eval`  permission:

![screenshot from 2018-09-09 12-19-08](https://user-images.githubusercontent.com/580493/45263512-94a0ea80-b42a-11e8-929e-73aff157922a.png)

### How to reproduce

* Enable `contextIsolation` in browser window.
* Add restrictive CSP header like `<meta http-equiv="Content-Security-Policy" content="default-src 'self'" />` to the page.
* Run the application
* Open developer console and notice the wrong warning.

I made these changes to the quick start app where you can easily reproduce it:

```
$ git clone https://github.com/kayahr/electron-quick-start.git -b csp-unsafe-eval-warning
$ cd electron-quick-start
$ npm install
$ npm start
```

In this project I also used the Function constructor and eval in the `renderer.js` to demonstrate that is is correctly blocked by the CSP header. But when Electron checks for the feature in `security-warnings.js` then the Function constructor is not blocked and that's why the warning is displayed. When context isolation is disabled then no warning is displayed. So I guess the security-warning.js is run in some other context which isn't affected by the CSP header.

**Comment by MarshallOfSound** [comment]
This is fixed by side-effects of https://github.com/electron/electron/pull/14284
