### ISSUE TITLE
3.0.x regression: Object has been destroyed upon quit with multiple windows open

### ISSUE THREAD

**Issue by bpasero** [electron/electron#14513]
* Output of `node_modules/.bin/electron --version`: 3.0.0-beta.10
* Operating System (Platform and Version): macOS 10.13.6
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2.0.x

**Expected Behavior**
Quitting should not throw a runtime exception.

**Actual behavior**
Quit and observe the following exception:

```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: Object has been destroyed
    at App.app.on (/private/var/folders/w_/xgfzkgq14jv_ykk2lm0k_h5c0000gn/T/tmp-62270YFNEZpiSIoql/main.js:39:38)
    at App.emit (events.js:182:13)
    at BrowserWindow.on (/Users/bpasero/Library/Application Support/Electron Fiddle/electron-bin/3.0.0-beta.10/Electron.app/Contents/Resources/electron.asar/browser/api/browser-window.js:103:9)
    at BrowserWindow.emit (events.js:182:13)
```

**To Reproduce**
Fiddle: https://gist.github.com/a02a645e11f4946dcca1331d0299149d

Key is to open multiple windows and install a `app.on('browser-window-focus')` listener that accesses the `window.id` property. 

Maybe related to https://github.com/electron/electron/pull/14453 (@nitsakh)

**Comment by Slapbox** [comment]
Confirming this issue on Windows 7 x64 as well.

**Comment by Slapbox** [comment]
It looks like everything is under control here, but for good measure:

Appending my last report, I've been able to recreate this on `3.0.0-beta.7` on Windows 7.

**Comment by Slapbox** [comment]
I could have chosen my words better. I've only run into it once. I was surprised by it, but I dug into my `node_modules` and saw that I was indeed on `beta.7.` If I run into this again I'll try to produce a repo.

**Comment by Slapbox** [comment]
@deepak1556 I've not narrowed it down completely yet, but it seems to only occur if a window besides the first one created is paused in the debugger when you use `app.quit()`. If this is correct, it should hardly be a concern for production.

**Comment by bpasero** [comment]
Verified 👍
