### ISSUE TITLE
Webview: not possible to prevent menu shortcuts from triggering

### ISSUE THREAD

**Issue by bpasero** [electron/electron#14514]
* Output of `node_modules/.bin/electron --version`: 3.0.0-beta.10
* Operating System (Platform and Version): macOS 10.13.4
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2.0.x

**Expected Behavior**
While a `<webview>` has focus, it should be possible to prevent menu items from triggering when certain keyboard keys are pressed.

**Actual behavior**
It is not possible to prevent menu item shortcuts to trigger when `<webview>` has focus.

**To Reproduce**
Setup (fiddle): https://gist.github.com/aa6fc464f034eba32ab70e6484396881

Steps:
* move focus into `<webview>`
* hit `Cmd+Q`
* the application quits, even though `setIgnoreMenuShortcuts(true)` is was called

I am not sure if `setIgnoreMenuShortcuts(true)` is even the right method for this, but ever since the introduction of OOPIF `<webview>` I see no easy way how to prevent a keyboard event to trigger a menu item. I would like to be able to "eat" the key event such as it never reaches the main menu under certain conditions (e.g. when I handled the key within the <webview>). 

Before OOPIF I could simply `preventDefault()` on the keyboard event to not let it bubble all the way to the main menu since it was triggered on the window DOM. Now I am using the code as outlined in https://github.com/electron/electron/issues/14258#issuecomment-416893856 to handle key events from within the `webview` and this issue is a consequence.  

**Issue:** this makes certain actions fire twice in VSCode, once from the menu and once from the forwarding through the weview.

**Comment by zcbenz** [comment]
It seems that while the DOM events are dispatched to the different `document`s, the keyboard events are still handled in the embedder WebContents in the main process.
