### ISSUE TITLE
Duplicated scripts running at the same time

### ISSUE THREAD

**Issue by fuzunspm** [electron/electron#14524]
* Output of `node_modules/.bin/electron --version`: v2.0.7
* Operating System (Platform and Version): macOS High Sierra 10.13.6

**Expected Behavior**
upon opening the same page multiple times, it should only execute .js file once

**Actual behavior**
let's say i open the same page/windows 5 time back & forth, then it duplicates the same .js file 5 times and it executes the same code 5 times

**Additional Information**
I have a main index.html file and i delete/insert tags to create pages on my app. But in the background it duplicates same files and executes them at the same time. In addition let's say i have a function name `function xyz() {console.log('a')}'` on script A.js and `function xyz() {console.log('b')}'` on script B.js. If i go to page A and B then execute the function on page B, it executes both functions in A and B and prints both 'a' and 'b'

here is my html structure to load scripts

```
<html>
<body>
.... i manipulate here
<script src='/a.js'>
</body>
</html>
```

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
