### ISSUE TITLE
Node: `Module.wrap` is going away

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#14525]
See https://github.com/nodejs/node/pull/21573

But we monkey-patch it in `e/node`: https://github.com/electron/node/commit/bc879a8d5bf45e84fc4ed05371efbcbe0e8a92e6
And we need to come up with some sort of solution to keep Electron working after the change is made.

/cc @ryzokuken

**Comment by codebytere** [comment]
This has been updated and handled in core and can be closed.
