### ISSUE TITLE
macOS Mojave: Unclickable region in windows with "hiddenInset" title bar

### ISSUE THREAD

**Issue by javan** [electron/electron#14529]
**Expected Behavior**
Clicking any region of the window should activate the element under the cursor.

**Actual behavior**
A small region in the top-center of the window isn't clickable.

**To Reproduce**
* Clone and run https://github.com/javan/electron-quick-start/tree/hidden-inset-mojave
* Click the black bar at the top of the window. It should turn purple while the mouse is down.
* Click the top-center of the black bar and note that it does't turn purple.

```sh
$ git clone https://github.com/javan/electron-quick-start.git -b hidden-inset-mojave
$ npm install
$ npm start
```
**Screenshots**
`macOS Mojave 10.14 Beta (18A384a)`  👎
![mojave](https://user-images.githubusercontent.com/5355/45313784-d51d6880-b4fd-11e8-9de8-1420b69cda69.gif)

`macOS High Sierra 10.13.6` 👍
![high-sierra](https://user-images.githubusercontent.com/5355/45313921-3a715980-b4fe-11e8-918d-792d5a5c4ef5.gif)

**Additional Information**
This issue impacts any application with critical navigation elements on the top of the page. For us (Basecamp 3), the "Hey!" menu is very difficult to click:
<img width="891" alt="screen shot 2018-09-10 at 1 36 50 pm" src="https://user-images.githubusercontent.com/5355/45314127-f599f280-b4fe-11e8-9296-a6dc43018409.png">

<details>
<summary><code>&lt;notch-joke&gt;</code></summary>
<img src="https://user-images.githubusercontent.com/5355/45316719-d81c5700-b505-11e8-9fb4-a7335b34fc3d.png">
<code>&lt;/notch-joke&gt;</code>
</details><br>

It's likely that Mojave will be released this week during the [Apple Special Event](https://www.apple.com/apple-events/september-2018/) on September 12.

**Comment by javan** [comment]
It appears that the unclickable region is where the title *would be* if the window had a standard title bar.

In the gif below there are two stacked windows. The rear window has a standard title bar, and the front window has a `hiddenInset` title bar. Both have their title set to `X`.

![title-clicks](https://user-images.githubusercontent.com/5355/46306817-47282100-c583-11e8-822c-014e0b7eca1a.gif)

You can see that the unclickable area of the front window is the same size as the `X` in the title. Setting a longer title results in a larger unclickable region.

**Comment by javan** [comment]
Setting the title to an empty string helps, but doesn't totally fix the problem. There's still a small unclickable region about the size of a single character.

**Comment by javan** [comment]
> This doesn't seem like a workable solution

It's a workaround, not a solution. YMMV

> title is reflected in all sorts of other areas in the OS? CMD+Tab / Window menu etc

I believe CMD+Tab displays the app name (`app.getName()`) not the window title.

**Comment by tommoor** [comment]
If it helps we're running Electron `1.8` and also seeing this issue on Mojave, so whatever the issue is has been there for a while - not unique to `3.X`

**Comment by lehni** [comment]
I'm seeing this issue also in https://marketplace.visualstudio.com/items?itemName=lehni.vscode-titlebar-less-macos

**Comment by tommoor** [comment]
This issue still exists in `5.X`

**Comment by bpasero** [comment]
This would block https://github.com/microsoft/vscode/issues/12377 in VSCode.

**Comment by jlindberg-oss** [comment]
This definitely seems to be an active problem, I am even having problems with input elements not working correctly in the top region when `hiddenInset` is used on MacOS High Sierra.

Any chance of the workaround developed by @knopp in https://github.com/microsoft/vscode/issues/12377#issuecomment-509016696 making it into Electron?

**Comment by astoilkov** [comment]
We are experiencing what I believe are additional side effects coming from the same bug. I have described them in [hiddenInset breaks mouse interactions in the first 38px of the window](https://github.com/electron/electron/issues/21632).

**Comment by fabiospampinato** [comment]
Could this issue be prioritized higher please? @codebytere @MarshallOfSound 

Attempting to work around this issue by setting the title to an empty string has all sorts of weird consequences: 

- Still a small area of the windows will be unresponsive to clicks.
- Windows with empty titles won't be listed in the list of windows under the "Windows" app menu or in the app's menu from the Dock.
- Switching between windows via App Exposé can be difficult if all windows look the same and you have no title to help you distinguish them.

And using a titlebar can really hinder the user experience for some apps, as they would look more like a website wrapped in an Electron shell with a quick script rather than something that's supposed to integrate much better with the OS.

**Comment by MarshallOfSound** [comment]
This is currently expected and unfixable behavior.  The good news is there is an easy workaround.  You can use the `hidden` title bar style and use the `trafficLightPosition` option in the `BrowserWindow` constructor to position the traffic lights wherever you want.  The coordinates that are equivalent to `hiddenInset` are as follows:

```js
const w = new BrowserWindow({
  frame: false,
  titleBarStyle: 'hidden',
  trafficLightPosition: {
    x: 14,
    y: 22,
  }
});
```

The `trafficLightPosition` API is available in Electron 8.2 and higher.

**Comment by fabiospampinato** [comment]
@MarshallOfSound that seems to work perfectly for me, thanks!

Are there any drawbacks in removing the titlebar this way over via setting "hiddenInset"? If there aren't shouldn't Electron just execute the code you provided when the "hiddenInset" value is set?

P.S. The precise coordinates at which the traffic lights get positioned with "hiddenInset" seems to be `{ x: 12, y: 22 }` on my system.

**Comment by MarshallOfSound** [comment]
> Are there any drawbacks in removing the titlebar this way over via setting "hiddenInset"? If there aren't shouldn't Electron just execute the code you provided when the "hiddenInset" value is set?

No drawbacks that I'm aware of, it's functionally different and is more likely to have some strange bugs.  E.g. Historically we've had to work around edge cases with fullscreen mode and such, but in general it's a perfectly reasonable replacement.  We might flip the implementation for `hiddenInset` at some point but right now there's no real driver for it 🤷 

> P.S. The precise coordinates at which the traffic lights get positioned with "hiddenInset" seems to be { x: 12, y: 22 } on my system.

Hm, I pulled those numbers from what I assume is a reliable source 🤔  Where did you get `x=12` from?

**Comment by fabiospampinato** [comment]
> Hm, I pulled those numbers from what I assume is a reliable source 🤔 Where did you get x=12 from?

Trial and error when comparing before and after screenshots. Where does that other coordinate come from?

**Comment by lehni** [comment]
@fabiospampinato @MarshallOfSound perhaps you are both on different versions of macOS?
