### ISSUE TITLE
[C67] Review synchronous permission check implementation

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#14544]
See https://github.com/electron/electron/blob/54ad38526095f4a415ad75a1757feae4336c9db4/atom/browser/atom_permission_manager.cc#L213 and https://github.com/electron/electron/blob/54ad38526095f4a415ad75a1757feae4336c9db4/atom/browser/atom_permission_manager.cc#L246

Should probably call out to https://github.com/electron/electron/blob/54ad38526095f4a415ad75a1757feae4336c9db4/atom/browser/atom_permission_manager.cc#L231 and be documented as such

**Comment by nornagon** [comment]
@MarshallOfSound is there more to do here?

**Comment by bughit** [comment]
#19891 was closed as a dup of this
