### ISSUE TITLE
Electron 3 webview loading external url slow

### ISSUE THREAD

**Issue by t57ser** [electron/electron#14543]
* Output of `node_modules/.bin/electron --version`: 3.0.0-beta.10
* Operating System (Platform and Version): Windows 7
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2.0.9

**Expected Behavior**
Time to load external url takes the same time as it would in the old version

**Actual behavior**
The loading stalls for many seconds

**To Reproduce**
create an empty project just with a webview and redirect the webview to google
this also happens when serving something from localhost

**Screenshots**
![electron3](https://user-images.githubusercontent.com/10595986/45344165-4105dc80-b5a3-11e8-8801-269b5a2edcb7.PNG)
![electron 2](https://user-images.githubusercontent.com/10595986/45344177-48c58100-b5a3-11e8-9cd8-7a21b4e5a0b0.PNG)

**Additional Information**
I have added the comparison screenshots between electron 3 and 2 above

**Comment by deepak1556** [comment]
Hi! do you have any virtual network adapter setup, there were issues with it that were reported for a similar verison https://github.com/electron/electron/issues/13829, can you check if its the same problem you are facing. Also can you confirm if the network requests from webview are only problematic or any network requests from the app is facing the problem. Finally can you attach the output file of `--log-net-log` as described in https://github.com/electron/electron/issues/13829#issuecomment-420371726. Thanks!

**Comment by t57ser** [comment]
Yes it appears to be the same problem, when deactivating the VMware network adapter it works.
The network requests are problematic for all of the app, I tried redirecting from a browserwindow, browserview and webview, all behaving the same.
[netlog.txt](https://github.com/electron/electron/files/2373847/netlog.txt)

**Comment by deepak1556** [comment]
@t57ser thanks for the confirmation and the log. I can confirm the cause is same, for now please use the workarounds mentioned in https://github.com/electron/electron/issues/13829. Thanks!

Merging this to https://github.com/electron/electron/issues/13829
