### ISSUE TITLE
Multi-client remote debugging support

### ISSUE THREAD

**Issue by 4eveRS** [electron/electron#14540]
**Describe the solution you'd like**
Since version 63, Chrome supports multi-client remote debugging, which means it can handle multiple debugger clients (such as webContents.debugger and devTools) at the same time.

In Electron current version, v3.0 Beta, this functionality is not working properly. Once the user set the debbuger in a webContent, if the same webContent request to open the devTools, the previous debugger attached to the webContent is detached and all configurations are lost.

I think many Electron users will find this functionality very useful, since it can give the full support of chrome devTool in app background while the app users can access the devTools of the same webContent.

My application for example, which is a browser, really needs that functionality in order to analyze the page and it's content, while it can't / shouldn't block the user to access the devTools of that same page.

**Additional context**

https://developers.google.com/web/updates/2017/10/devtools-release-notes#multi-client
https://crbug.com/129539

**Comment by MarshallOfSound** [comment]
We actually have a test to ensure this works, see https://github.com/electron/electron/blob/39c5c200ba18ae80961d73bac0c27c06f523b547/spec/node-spec.js#L244

Can you fill out the [Bug Report](https://github.com/electron/electron/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) issue template in a comment below, in particular a minimal repro and version information would be very useful

**Comment by 4eveRS** [comment]
**Electron version**: v3.0.0-beta.5
**Operating System**: macOS Sierra 10.12.6

**Expected Behavior**
Multi-client remote debugging should be supported by Electron.

**Actual Behavior**
Multi-client remote debugging is not actually supported.

_Example of actual behavior_
Create a webview and attach a debugger to its webContents.
Send commands to test if its working.
Enable webview devTools.
webContents debugger is detached and lose all commands sent before the devTools was opened.

**To Reproduce**

[https://gist.github.com/4eveRS/b80a836c313864d394191e7347efa580](https://gist.github.com/4eveRS/b80a836c313864d394191e7347efa580)
```
$ git clone git@gist.github.com:b80a836c313864d394191e7347efa580.git
$ npm install
$ npm start || electron .
```

**Comment by 4eveRS** [comment]
One thing that I just noticed is that, if we use commands that use debugger/devTools interface, for example, setting a viewport in a webview through webContents.enableDeviceEmulation(), if later we set a debugger to that same webContents, that device emulation is disabled.

So there's a issue  when running debuggers, devTools and commands in webContents that utilize the devTools protocol.

**Comment by deepak1556** [comment]
@4eveRS Thanks for the test case, i have fixed the multi client problem while doing a cleanup in https://github.com/electron/electron/pull/14522, will backport the specific fix to 3-0-x branch soon.

**Comment by deepak1556** [comment]
Fixed in https://github.com/electron/electron/pull/14566

**Comment by praneetrohida** [comment]
I'm having the exact same issue in Electron 8.x
