### ISSUE TITLE
Failed to run "gn gen" when build electron on Windows

### ISSUE THREAD

**Issue by KarenHuang2016** [electron/electron#14542]
* Operating System (Platform and Version):
Windows 10 and VS 2017

**To Reproduce**
1. git.exe clone --recursive https://github.com/electron/electron.git D:\Elelctron\src
2. depot_tools is located at D:\Electron
3. set D:\Electron\depot_tools;%path%
4. set DEPOT_TOOLS_WIN_TOOLCHAIN=0
5. cd D:\Elelctron\src
6. gn gen out/Default --args="import(\"//build/args/release.gn\")"

**Result:**
Traceback (most recent call last):
  File "D:\Chrome\depot_tools\\gn.py", line 71, in <module>
    sys.exit(main(sys.argv))
  File "D:\Chrome\depot_tools\\gn.py", line 49, in main
    'gn', 'gn' + gclient_utils.GetExeSuffix())
  File "C:\Python27\lib\ntpath.py", line 65, in join
    result_drive, result_path = splitdrive(path)
  File "C:\Python27\lib\ntpath.py", line 115, in splitdrive
    if len(p) > 1:
TypeError: object of type 'NoneType' has no len()

**Comment by emmkimme** [comment]
I get the same issue, same error, same env. 
The build-instructions-[os] files still refer bootstrap.py which disappeared and build-instructions-gn does not work.

**Comment by nornagon** [comment]
Please read the [build instructions for GN](https://github.com/electron/electron/blob/master/docs/development/build-instructions-gn.md) carefully. The process of checking out and building Electron has changed dramatically with the introduction of GN. The steps listed in the original post are very far from the correct sequence of steps for building Electron, as detailed in the build instructions.

I'm closing this issue as there's nothing actionable, but I'm happy to help you out with any issues you encounter with the build that you encounter when executing the correct sequence of steps as detailed in the build instructions.

**Comment by KarenHuang2016** [comment]
I can build Electron now. Update the steps here in case any one needs it.
To get source:
    1. Create D:\Electron 
    2. Download this: https://storage.googleapis.com/chrome-infra/depot_tools.zip  and unzip it to D:\Electron\depot_tools\ . Eg you should have D:\Electron\depot_tools\auth.py as a file. Then add D:\Electron\depot_tools to path.
    3. Open a 32-bit command prompt (C:\windows\syswow64\cmd.exe) and
	○ cd D:\Electron
	○ set DEPOT_TOOLS_WIN_TOOLCHAIN=0
	○ gclient config --name "src/electron" --unmanaged https://github.com/electron/electron
	○ gclient sync --with_branch_heads --with_tags

To build & test:
	1. Open a clean command prompt and browse to D:\Electron
	2. set DEPOT_TOOLS_WIN_TOOLCHAIN=0
	3. set CHROMIUM_BUILDTOOLS_PATH=D:\Electron\src\buildtools
Release|x86
	1. mkdir out\x86rel
	2. Create a args.gn file under out\x86rel and insert the following content:
	import("//electron/build/args/release.gn")
	target_cpu = "x86"
	3. gn gen out\x86rel 
	4. ninja -C out/x86rel electron:electron_app -v -d keeprsp
	5. out\x86rel\electron.exe electron/spec --ci --enable-logging
Release|x64
	1. mkdir out\x64rel
	2. Create a args.gn file under out\x64rel and insert the following content:
	import("//electron/build/args/release.gn")
	target_cpu = "x64"
	3. gn gen out\x64rel 
	4. ninja -C out/x64rel electron:electron_app -v -d keeprsp
	5. out\x64rel\electron.exe electron/spec --ci --enable-logging

**Comment by nornagon** [comment]
Glad to hear it's working for you!
