### ISSUE TITLE
Windows GN build does not recognize high DPI screens

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#14568]
* Output of `node_modules/.bin/electron --version`: `4.0.0-nightly.20180823`
* Operating System (Platform and Version): Windows
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): `3.0.0-beta.10`

**Expected Behavior**
Window should not be blurry at high DPI

**Actual behavior**
It's blurry

**To Reproduce**
Just launch the default app on a high DPI screen and see how it's blurry, screenshot is attached.

**Screenshots**
![image](https://user-images.githubusercontent.com/6634592/45405746-7267d080-b6a7-11e8-8dfd-662b8b32a5e2.png)

**Additional Information**
This could be related to the GN build

cc @nornagon

**Comment by alexeykuzmin** [comment]
@MarshallOfSound Have you tried to build Electron from the `master` from the very last commit with gyp build available?

**Comment by MarshallOfSound** [comment]
@alexeykuzmin No, I just took the latest 3.0 beta, I can try master just before the gyp removal tomorrow.

**Comment by nornagon** [comment]
Seems highly likely that this is related to the GN changes. I'll take a look today.
