### ISSUE TITLE
macOS window controls missing with 'hiddenInset' and macOS 10.12

### ISSUE THREAD

**Issue by felixrieseberg** [electron/electron#14570]
* Affected version: All of Electron 3.0
* Operating System (Platform and Version): macOS 10.12 and below (Sierra and below)
* Last known working version: Electron 2.0.7

We've discovered that upgrading to Electron 3 results in missing macOS window controls on macOS 10.12 and below. We've isolated that issue to the Electron 3 update.

**Expected Behavior**

`titleBarStyle: 'hiddenInset'` should result in window controls being present.

**Actual behavior**

`titleBarStyle: 'hiddenInset'` results in missing window controls.

**To Reproduce**
https://gist.github.com/3948a9042e60aaa2fa191ef8258e458c

**Screenshots**
![image](https://user-images.githubusercontent.com/1426799/45408314-4bd87400-b66c-11e8-9196-200f65a1175f.png)

**Comment by nitsakh** [comment]
Ahh! Yes, it's 10.12 or lower.

**Comment by setpixel** [comment]
This is the same issue as https://github.com/electron/electron/issues/14129

It was closed an merged into an unrelated issue for some reason.

In any event, I'm glad someone cares now! <3

**Comment by pfrazee** [comment]
I've been able to reproduce this
