### ISSUE TITLE
Tracking electron architecture when downloaded via npm

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [electron/electron#14585]
* Output of `node_modules/.bin/electron --version`: 2.0.9
* Operating System (Platform and Version): Win 10 x64

* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

### Premise
My issue is the same as https://github.com/electron-userland/electron-prebuilt/issues/219
We need to call 32 bit dlls from the electron app which I will be doing via `electron-edge-js`. But for calling 32 bit dlls, I need a 32 bit nodejs which according to the docs [here](https://electronjs.org/docs/tutorial/installation#customization), I can do by using the `arch` option during `npm install` and this works great. But if I commit this and some other developer pulls and runs `npm install`, I think he will get the default 64 bit version of electron.

Please correct me if I am wrong but I didn't find any mention of anything related in the docs.
### Expected behavior
Subsequent `npm install` should grab the correct architecture.

### Actual behavior
`npm install` will cause the default architecture to be installed

### How to reproduce
1. Create an electron project by including the electron dependency as `npm install --arch=ia32 electron`.
2. Commit and push the code.
3. Pull the project into a separate workspace and run `npm install`

**Comment by MarshallOfSound** [comment]
@SayakMukhopadhyay If you want this kind of behavior you just need to make a `.npmrc` at the root of your project with a single line `arch=ia32`.  All npm installs will pick that up in the future

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by kyle-mcknight** [comment]
Why is this not documented on the nprmc or npm-config pages? Or am I missing this?

**Comment by kyle-mcknight** [comment]
What if we want 64-bit versions of some modules and not others?
