### ISSUE TITLE
Pepper Flash Plugin: spark components not visible

### ISSUE THREAD

**Issue by christophpre** [electron/electron#14580]
* Output of `node_modules/.bin/electron --version`: v3.0.0-beta.10
* Operating System (Platform and Version): Windows 10 10.0.16299 Build 16299 **and** MacOS High Sierra 10.13.6
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v2.0.9

**Expected Behavior**
Labels and values of flash spark controls should be visible inside a flash plugin.

**Actual behavior**
Labels and values of flash spark controls are not visible inside a page with flash plugin.

**To Reproduce**
I provided a sample application with flash, where mx controls and spark controls are used. The mx controls are visible, the spark controls are there (values are there), but are not visible. Open the sample page with flash in the provided sample [Flash_Controls_Test.zip](https://github.com/electron/electron/files/2375519/Flash_Controls_Test.zip) at **Flash_Controls_Test\bin-debug\NSB_Controls_Test.html** inside a BrowserWindow with Pepper Flash Plugin enabled. There is source code as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/6893212/45431191-6da31c80-b6a7-11e8-9fbb-dc7b8375ded3.png)
Interestingly the memory usage of the BrowserWindow with flash enabled goes up and suddenly drops down again periodically, without any user interaction happening:
![image](https://user-images.githubusercontent.com/6893212/45431713-8829c580-b6a8-11e8-8df8-7b32c1d6f423.png)

**Additional Information**
I know Flash might not have any priority for you, but we have legacy pages with Flash, that we are supporting with an Electron app.

**Comment by christophpre** [comment]
Just tried this in 4.0.0-beta.3. Seems to work in 4.0.X.

**Comment by sofianguy** [comment]
We are no longer supporting versions older than 4.2.x. Please upgrade to later versions as it is reported as fixed in the above comment.
