### ISSUE TITLE
[Bug] Pepper Flash Plugin not loading

### ISSUE THREAD

**Issue by GhostlyDark** [electron/electron#14587]
Pepper Flash Plugin does not load in v3.0.0-beta.11 across all operating systems: 
Windows 10 x64, Ubuntu 18.10 x64, macOS 10.14 have been tested.

It worked fine in v3.0.0-beta.10

**Comment by sofianguy** [comment]
duplicate. please follow https://github.com/electron/electron/issues/14580 for updates

**Comment by GhostlyDark** [comment]
How is this a duplicate?

Issue from me:
- v3.0.0-beta.11
- Flash player not loading at all

Issue from christophpre:
- v3.0.0-beta.10
- Flash player is loading normally
- Flash controls are invisible

Sure it can be related, but definitely no duplicate.
