### ISSUE TITLE
Wrong menu shortcut representation in Windows

### ISSUE THREAD

**Issue by chrilith** [electron/electron#14582]
* Electron version: 3.0.0-beta.1 to 10
* Operating System: Windows

**Expected Behavior**
Shortcuts should be properly displayed in the the app menu.

**Actual behavior**
Using `CommandOrControl+Shift+O` shortcut, the menu entry shortcut should be shown as 'Ctrl+Shift+O', but "Ctrl+O" is displayed instead. The shortcut works fine though.

Same problem with roles. For instance `forcereload` will show Ctrl+R instead of Ctrl+Shift+R. Again, the shortcut works fine here.

**To Reproduce**
Simply change a shortcut or a role in the electron-quick-start menu.

**Additional Information**
Was working fine with latest 2.x version of electronjs.

**Comment by MarshallOfSound** [comment]
Duplicate #14501
