### ISSUE TITLE
Print "silent" is not working

### ISSUE THREAD

**Issue by abhijithcs** [electron/electron#14605]
electron@2.0.9
node@v8.9.4
MacOS@10.13.6

The "silent" print option doesn't seem to be working as expected. Even though the "silent" option is set to 'true', the system window (Printer Selection Window) pops up and asks to select a Printer. 

```
    var pageSettingsSilent = {
      'marginsType': 1, //No Margin
      'printBackground': true, 
      'pageSize': {
        "height": 297000,
        "width": 72000
      },
      'silent': true
    }

    workerWindow.webContents.print(pageSettingsSilent,  function (error, data) {
        if (error) throw error
    })
```

**Comment by abhijithcs** [comment]
#9780

**Comment by hablema** [comment]
Has the problem been resolved? I'm still facing the issue?

**Comment by abhijithcs** [comment]
@hablema The callback function is causing the issue. Removing the callback from print() resolves the issue.

```
    var pageSettingsSilent = {
      'marginsType': 1, //No Margin
      'printBackground': true, 
      'pageSize': {
        "height": 297000,
        "width": 72000
      },
      'silent': true
    }

    workerWindow.webContents.print(pageSettingsSilent)
```

**Comment by tomnielsen** [comment]
I'm having this problem and appreciate the work around, but I don't think you should have closed the issue.

Adding a simple callback function as-per-the-api, should **not** make it randomly (and silently) fail.

**Comment by maikonmatheus** [comment]
Silent printing still fails in Electron 5.0.3, with and without callback as mentioned for @abhijithcs
