### ISSUE TITLE
Latest 4.0 nightly on npm

### ISSUE THREAD

**Issue by sgd2z** [electron/electron#14608]
Is it possible to get the latest master on npm? this - https://github.com/electron/electron/issues/13549 - is a critical issue for us and it would be great to be able to use the latest with the fix for that in.

**Comment by MarshallOfSound** [comment]
@sgd2z Master nightlies are currently blocked due to build system changes, that said the issue you linked was backported and released in `3.0.0-beta.12`

**Comment by sgd2z** [comment]
Thanks for the response. We use 4.0 nightlies because we need the will-resize event. Any word on when the block will be lifted?

**Comment by MarshallOfSound** [comment]
@sgd2z Once we have the capability to release a nightly from master we will, the release scripts / CI jobs aren't configured yet
