### ISSUE TITLE
Attach puppeteer browser to electron app

### ISSUE THREAD

**Issue by cristiangiagante** [electron/electron#14607]
I can't attach a puppeteer instance working with jest to the Vue.js app running inside Electron application.

Could you give steps or docs to read to reach this goal? thanks

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by trusktr** [comment]
@cristiangiagante I asked this question [in the forums](https://discuss.atom.io/t/control-automate-an-electron-application-with-puppeteer/64126), hopefully they can reply there.
