### ISSUE TITLE
Derived browser window not detected by dialog

### ISSUE THREAD

**Issue by christian-judt** [electron/electron#14611]
* Electron version: 2.0.0 - 2.0.9
* Operating system: Windows 7

**Reproduction**
* Create a class derived from the browser window class.
* Create an instance of this derived class to be the browser window.
* Open a save file dialog using this instance as first argument and a default file name in the second argument.

**Expected Behavior**
* A modal save file dialog is opened for the browser window defaulting to the provided file name.

**Actual behavior**
* A non modal save file dialog is opened defaulting to an empty file name.

**How To Reproduce**
```
git clone -b derived-browser-window-not-detected-by-dialog-bug https://github.com/christian-judt/electron-quick-start.git
cd electron-quick-start
npm install
npm start
```

**Maybe related issues**
* Can I extend BrowserWindow? #23

**Comment by MarshallOfSound** [comment]
@christian-judt As per #23 you can't extend `BrowserWindow`.

See https://github.com/electron/electron/issues/23#issuecomment-19613241

**Comment by christian-judt** [comment]
@MarshallOfSound:
Evidence suggests I can indeeed. And as an added bonus it is even working properly unless I use it as the first argument of the "showSaveDialog" helper method. This specific problem however suggests that at least this specific helper method does not correctly handle javascript signature overloading, which someone probably should have a look at.

**Comment by MarshallOfSound** [comment]
@christian-judt See that comment I linked, it may look like it works but there will be things breaking in the background that you may not notice.  We won't "fix" anything to make it like inheritance is supported when it truly is not

**Comment by christian-judt** [comment]
@MarshallOfSound:
Thank you for the insight. I will try to use a proxy class instead to manage "my" browser windows.
