### ISSUE TITLE
Tyepscript types for 'Headers' incorrect

### ISSUE THREAD

**Issue by burtonator** [electron/electron#14619]
I'm trying to implement a stream handler and the Headers aren't properly defined.  Headers has nothing so it's not possible to access them as a map.

```
  interface Header {
    /**
     * Specify an extra header name.
     */
    name: string;
  }

  interface Headers {
  }
```

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
