### ISSUE TITLE
Electron is executing the default app by default when invoked directly

### ISSUE THREAD

**Issue by FFY00** [electron/electron#14626]
* Output of `node_modules/.bin/electron --version`: `v2.0.9`
* Operating System (Platform and Version): Arch Linux

**Expected Behavior**
From the output of `electron --help`, I would only expect for the default app to be launched only when the `-d`/`--default` flag is passed.

**Actual behavior**
When electron is called without arguments, the default app is launched. When an electron app is loaded but fails for some reason, the default app is also loaded. The last situation would probably be the more critical.

**To Reproduce**
`electron` or `electron dummy-app.js`

**Additional Information**
I don't know if this is intentional or not. If this is intentional, the existence of `-d` seems weird.

**Comment by MarshallOfSound** [comment]
This is intentional and expected behavior, the default app will load in all cases where an alternate valid app could not be found or was not provided

**Comment by FFY00** [comment]
Ok, thank you. Why do we have `-d` then? That's what got me confused in the first place :smile:.
