### ISSUE TITLE
How to connect puppeteer to electrons websocket endpoint

### ISSUE THREAD

**Issue by nofear87** [electron/electron#14624]
Any ideas how to connect puppeteer to a running electron browser window? I will create a pdf via puppetter from a running electron browser window. Puppetter's connect method allows to pass in a browserWSEndpoint. Is there such an endpoint?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by duuliy** [comment]
Try opening a new browser process

**Comment by duuliy** [comment]
Try opening a new browser process
