### ISSUE TITLE
error installing on linux/arch

### ISSUE THREAD

**Issue by ndr3w221** [electron/electron#14630]
* Output of `node_modules/.bin/electron --version`: 
v2.0.9
* Operating System (Platform and Version):
4.14.69-1-MANJARO GNU/Linux
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):
v2.0.9

**Expected Behavior**
Install electron

**Actual behavior**
```bash
[andrew-pc nitro-virus]# npm i electron -g
/usr/bin/electron -> /usr/lib/node_modules/electron/cli.js

> electron@2.0.9 postinstall /usr/lib/node_modules/electron
> node install.js

/usr/lib/node_modules/electron/install.js:54
  throw err
  ^

Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/electron/.electron'
```
**To Reproduce**
-

**Comment by MarshallOfSound** [comment]
@ndr3w221 You either need to give Electron the fs permissions required to download or change the directory it downloads to using the `ELECTRON_CACHE` variable.  For more info on common issues like this, check out our FAQ.

https://github.com/electron/electron/blob/master/docs/faq.md#why-am-i-having-trouble-installing-electron
