### ISSUE TITLE
webContents.getFocusedWebContents always return <webview> web contents

### ISSUE THREAD

**Issue by steverandy** [electron/electron#14631]
* Output of `node_modules/.bin/electron --version`: v3.0.0-beta.12
* Operating System (Platform and Version): macOS 10.13.6
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v2.0.9

**Expected Behavior**
webContents.getFocusedWebContents should return window web contents if it's focused, even when the window has `<webview>`.

**Actual behavior**
webContents.getFocusedWebContents always return webview web contents, even when focus has changed to the BrowserWindow element.

**To Reproduce**
1. Render a `<webview>` in BrowserWindow.
2. Move focus to other element in BrowserWindow (for example an `<input>`).
3. Call webContents.getFocusedWebContents

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
