### ISSUE TITLE
Font Awesome not showing in Electron apps on High Sierra

### ISSUE THREAD

**Issue by minthemiddle** [electron/electron#14643]
**Expected Behavior**
- Apps built with Electron should properly display Font Awesome icons

**Actual behavior**
- On my Mac High Sierra, all apps built with Electron don't show Font Awesome icons
- No corrupt fonts are installed in any of [Mac's font folders](http://www.jklstudios.com/misc/osxfonts.html#fontfolderlocations)

**Screenshots**
![screen shot 2018-09-16 at 13 10 22](https://user-images.githubusercontent.com/1950766/45595823-ef4dbf80-b9b1-11e8-9e42-d3cdb652cca6.png)
([Eagle app](https://eagle.cool/))

![screen shot 2018-09-16 at 13 11 07](https://user-images.githubusercontent.com/1950766/45595827-fd9bdb80-b9b1-11e8-8b5f-0a3aa48ecc41.png)
([Pencil](https://pencil.evolus.vn/))

**Comment by MarshallOfSound** [comment]
I loaded the font awesome example and docs pages in Electron and the icons show fine, this appears to be an issue with these specific apps or maybe your network connection trying to download the fonts.

Screenshots below of the fonts working:

<img width="1792" alt="screen shot 2018-09-16 at 9 27 02 pm" src="https://user-images.githubusercontent.com/6634592/45595945-5c377880-b9f7-11e8-894e-78c9f94b0707.png">
<img width="1792" alt="screen shot 2018-09-16 at 9 27 32 pm" src="https://user-images.githubusercontent.com/6634592/45595946-5c377880-b9f7-11e8-8114-2db9d5800f81.png">
<img width="1792" alt="screen shot 2018-09-16 at 9 27 35 pm" src="https://user-images.githubusercontent.com/6634592/45595947-5c377880-b9f7-11e8-9ec4-05d784712fa1.png">

**Comment by MarshallOfSound** [comment]
If you can provide a minimal reproduction sample that shows these fonts not working please @ mention me in a follow up and I can look at this again 👍

**Comment by minthemiddle** [comment]
I failed to point out that it is only in packaged apps not on websites. The websites you screenshoted work fine with me as well. I already informed the authored of linked apps. I will close the issue here and just keep it as reference for the apps' maintainers.

**Comment by minthemiddle** [comment]
Just for reference:

Other apps have the same problem, it might be related to an outdated version of `glibc`. https://github.com/Mindmapp/mindmapp/issues/47

**Comment by hubitor** [comment]
I still have the same issue with Pencil and Mindmapp although I don't have Material Icon font. But I have installed nerd fonts which includes Font Awesome fonts.
