### ISSUE TITLE
DevTools Extensions not working in BrowserView

### ISSUE THREAD

**Issue by carloslfu** [electron/electron#14644]
* Output of `node_modules/.bin/electron --version`: v2.0.9
* Operating System (Platform and Version): MacOSX Sierra 10.13.4 (17E199)
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): not

**Expected Behavior**
BrowserViews should execute devtools extensions, the same as webviews and BrowserWindows

**Actual behavior**
It doesn't happen

**To Reproduce**
Install a custom devtool and it doesn't work on BrowserViews

**Additional Information**
I guess the problem is here: https://github.com/electron/electron/blob/451b1782acfef01dd0758e7b9ddb329700626b98/lib/browser/chrome-extension.js#L19

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
