### ISSUE TITLE
Electron 3.0.0 using Node.js 10.2.0?

### ISSUE THREAD

**Issue by mafintosh** [electron/electron#14645]
I just noticed https://github.com/electron/node that Electron 3.0.0 is based on Node.js 10.2.0?

There are some really bad bugs in 10.2.0, including file corruption when writing files >4gb.
The later versions of 10 have all of these things fixed.

I'd strongly suggest not to release any electron based on 10.2.0

**Comment by MarshallOfSound** [comment]
We backport fixes for major issues like the ones you reference to our node branches.  E.g. Your large file issue: https://github.com/electron/node/commit/c3c62e09865f925e0f040d8689cf2a207e36c2a1

**Comment by mafintosh** [comment]
Great to hear that! Might be worth noting on that site :)

**Comment by bhupathyap** [comment]
@MarshallOfSound  Is this issue fixed in electron's node fork [https://github.com/nodejs/node/issues/20921](https://github.com/nodejs/node/issues/20921)?
