### ISSUE TITLE
when switch pdf preview more than twice on the iframe , electron crashed

### ISSUE THREAD

**Issue by darkangel0217** [electron/electron#14658]
occur environment:
electron 2.0.9
win7
node 8.9.3
electron-quick-start

1. modify the electron-quick-start's code.
1)add follow code in index.html
/**************************************/
\<div\>
\<iframe id="iframe_a" name="iframe_a" width="800px" height="600px" \>\</iframe\>
\<p>\<a id="a1" href="file:\\C:\xxx.pdf"  target="iframe_a" >iframe_a1\</a\>\</p\>
\<p>\<a id="a2" href="http://xx.pdf"  target="iframe_a" >iframe_a2\</a\>\</p\>
\</div\>
/**************************************/
2)add webPreference:{plugins:true} in the place of  new BrowserWindow in main.js  
2. run (npm start)

**Actual behavior**
case 1:click <a>a1,  then a1's pdf preview in iframe_a, then click <a>a2, electron crash.
case 2:click <a>a1,  then a1's pdf preview in iframe_a, then click <a>a1 again, [failed to load PDF document] warning  display.

**Expected Behavior**
case 1:when click <a>a2, electron  do not crash and can preview PDF.
case 2:when click <a>a1 again, can preview PDF.

![1](https://user-images.githubusercontent.com/42225826/45661521-6d37d500-bb30-11e8-9ccd-d3a85fe1e752.jpg)
![2](https://user-images.githubusercontent.com/42225826/45661524-70cb5c00-bb30-11e8-95b4-5da1a9d8d671.jpg)
[video.zip](https://github.com/electron/electron/files/2390964/video.zip)

**Comment by darkangel0217** [comment]
I  add listener on event(did-get-response-details)
when pdf preview success，event comes
1. requestMethod :"Get", resourceType:"subFrame", referrer:""
2.requestMethod :"Get", resourceType:"other", referrer:"http://xx.pdf"

when Expected Behavior case1, case2. [2.requestMethod :"Get", resourceType:"other", referrer:"http://xx.pdf"]event don't come.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
