### ISSUE TITLE
Pepper Flash Plugin: Couldn't load plugin for 3.0.0-beta.12

### ISSUE THREAD

**Issue by alexanderturinske** [electron/electron#14653]
* Output of `node_modules/.bin/electron --version`: 3.0.0-beta.11 && 3.0.0-beta.12
* Operating System (Platform and Version): macOS High Sierra Version 10.13.6 and Windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 3.0.0-beta.10

**Expected Behavior**
In 3.0.0-beta.10, the Pepper Flash Plugin does load and does play flash videos

**Actual behavior**
In 3.0.0-beta.11/12, the Pepper Flash Plugin does NOT load and does NOT play flash videos

**To Reproduce**
If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone https://github.com/alexanderturinske/electron-sample-apps -b pepper-flash-test
$ npm install -g electron@3.0.0-beta.10
$ electron pepper-flash-plugin
```
New window shows up and it DOES NOT show "Couldn't load plugin"
Close the window
```sh
$ git clone https://github.com/alexanderturinske/electron-sample-apps -b pepper-flash-test
$ npm install -g electron@3.0.0-beta.12
$ electron pepper-flash-plugin
```
New window shows up and it DOES show "Couldn't load plugin"
**Screenshots**
3.0.0-beta.10:
![image](https://user-images.githubusercontent.com/12485238/45648393-51272b80-ba7d-11e8-9105-4962c8f83112.png)
3.0.0-beta.12:
![image](https://user-images.githubusercontent.com/12485238/45648344-276e0480-ba7d-11e8-9737-1dd31571f8a6.png)

**Additional Information**

**Comment by alexanderturinske** [comment]
Perhaps related to #14497

**Comment by GhostlyDark** [comment]
Aha, but my issue #14587 was closed as a duplicate for the wrong reasons. I feel insulted.

**Comment by codebytere** [comment]
Fixed in latest release.

**Comment by ckerr** [comment]
@GhostlyDark I think your issue was closed out of error rather than insult.
