### ISSUE TITLE
Failed to get the electron code

### ISSUE THREAD

**Issue by KarenHuang2016** [electron/electron#14662]
**Environment:** Windows Server 2016 + VS 2017

**Issue description:** We are following the document https://github.com/electron/electron/blob/master/docs/development/build-instructions-gn.md to get elelctron source code. But it always failed.

**Repro steps:**
1.  Create folder D:\Electron 
2. Unzip depot_tools.zip to D:\Electron\depot_tools 
3. Open a command prompt and cd D:\Electron
4. set path=D:\Electron\depot_tools ;%path%
5. set DEPOT_TOOLS_WIN_TOOLCHAIN=0
6. gclient config --name "src/electron" --unmanaged https://github.com/electron/electron
7. gclient sync --with_branch_heads --with_tags

**Error log:**
________ running 'C:\tools\python2\python.exe src/electron/script/apply-patches --project-root=. --commit' in 'D:\Electron'
D:\Electron\src\electron\patches\common\angle\dcheck.patch:6: trailing whitespace.

D:\Electron\src\electron\patches\common\angle\dcheck.patch:7: trailing whitespace.
#define ANGLE_EMPTY_STATEMENT for (;;) break

D:\Electron\src\electron\patches\common\angle\dcheck.patch:8: trailing whitespace.
#if !defined(NDEBUG) || defined(ANGLE_ENABLE_RELEASE_ASSERTS)

D:\Electron\src\electron\patches\common\angle\dcheck.patch:10: trailing whitespace.
// #define ANGLE_ENABLE_ASSERTS

D:\Electron\src\electron\patches\common\angle\dcheck.patch:11: trailing whitespace.
#endif

warning: squelched 2 whitespace errors
warning: 7 lines add whitespace errors.
[detached HEAD f921e66] Apply Electron patches
 Author: Electron Build Process <build@electronjs.org>
 1 file changed, 1 insertion(+), 1 deletion(-)
D:\Electron\src\electron\patches\common\boringssl\0001-Implement-legacy-OCSP-APIs-for-libssl.patch:51: trailing whitespace.
SSL,280,NO_SUPPORTED_VERSIONS_ENABLED

D:\Electron\src\electron\patches\common\boringssl\0001-Implement-legacy-OCSP-APIs-for-libssl.patch:52: trailing whitespace.
SSL,185,NULL_SSL_CTX

D:\Electron\src\electron\patches\common\boringssl\0001-Implement-legacy-OCSP-APIs-for-libssl.patch:53: trailing whitespace.
SSL,186,NULL_SSL_METHOD_PASSED

D:\Electron\src\electron\patches\common\boringssl\0001-Implement-legacy-OCSP-APIs-for-libssl.patch:54: trailing whitespace.
SSL,289,OCSP_CB_ERROR
D:\Electron\src\electron\patches\common\boringssl\0001-Implement-legacy-OCSP-APIs-for-libssl.patch:55: trailing whitespace.
SSL,187,OLD_SESSION_CIPHER_NOT_RETURNED
warning: squelched 498 whitespace errors
warning: 503 lines add whitespace errors.
D:\Electron\src\electron\patches\common\boringssl\implement-SSL_get_tlsext_status_type.patch:6: trailing whitespace.
// Use |SSL_enable_ocsp_stapling| instead.

D:\Electron\src\electron\patches\common\boringssl\implement-SSL_get_tlsext_status_type.patch:7: trailing whitespace.
OPENSSL_EXPORT int SSL_set_tlsext_status_type(SSL *ssl, int type);

D:\Electron\src\electron\patches\common\boringssl\implement-SSL_get_tlsext_status_type.patch:8: trailing whitespace.

D:\Electron\src\electron\patches\common\boringssl\implement-SSL_get_tlsext_status_type.patch:9: trailing whitespace.
OPENSSL_EXPORT int SSL_get_tlsext_status_type(SSL *ssl);

D:\Electron\src\electron\patches\common\boringssl\implement-SSL_get_tlsext_status_type.patch:10: trailing whitespace.
warning: squelched 17 whitespace errors
warning: 22 lines add whitespace errors.
[detached HEAD df0e6b2] Apply Electron patches
 Author: Electron Build Process <build@electronjs.org>
 12 files changed, 421 insertions(+), 155 deletions(-)
 rewrite ssl/test/runner/alert.go (84%)
D:\Electron\src\electron\patches\common\chromium\add_realloc.patch:6: trailing whitespace.
  return malloc(length);
D:\Electron\src\electron\patches\common\chromium\add_realloc.patch:7: trailing whitespace.
}
fatal: corrupt patch at line 8
add_realloc.patch failed to apply
Error: Command 'C:\\tools\\python2\\python.exe src/electron/script/apply-patches --project-root=. --commit' returned non-zero exit status 1 in D:\Electron

**Comment by codebytere** [comment]
@nornagon, you may have more context here than i :)

**Comment by MarshallOfSound** [comment]
@KarenHuang2016 Can you post the output of `git config --list` on your machine

**Comment by KarenHuang2016** [comment]
@MarshallOfSound, this is the ouput of git config --list:
D:\Electron>git config --list
core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
diff.astextplain.textconv=astextplain
rebase.autosquash=true
credential.helper=manager

**Comment by MarshallOfSound** [comment]
@KarenHuang2016 My guess was it is something to do with `CRLF` vs `LF` line endings.  Are you running these commands of powershell, cmd or lss?

**Comment by KarenHuang2016** [comment]
@MarshallOfSound I'm using cmd to run these commands.

**Comment by KarenHuang2016** [comment]
@MarshallOfSound It should be an issue with CRLF vs LF. After I set core.autocrlf=false. It works well. Thank you so much.

**Comment by vulture** [comment]
I have this same issue -- would it be possible to fix it on the electron repo(?) side with a .gitattributes setting for *.patch or something, instead of relying on and forcing us to change our global git settings (which can cause issues with other [unrelated] repos)? Thanks!

**Comment by nornagon** [comment]
Good idea @vulture! I made a PR, it'd be great if you could check it out & confirm that it works.
