### ISSUE TITLE
Fullscreen function triggered 'maximize' events also when maximized.

### ISSUE THREAD

**Issue by erguotou520** [electron/electron#14669]
* Output of `node_modules/.bin/electron --version`: 3.0.0-beta8
* Operating System (Platform and Version): Win10

**Expected Behavior**
`enter-full-screen` event triggered only.

**Actual behavior**
`maximize` event triggered also.

**To Reproduce**
First create a frameless window, then call `maximize` method, then add `maximize` and `enter-full-screen` listeners, then call `setFullScreen(true)`.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
