### ISSUE TITLE
[Mac] Show tray on mousedown

### ISSUE THREAD

**Issue by natew** [electron/electron#14682]
* Output of `node_modules/.bin/electron --version`: 3.0.0
* Operating System (Platform and Version): Mojave beta 11

**Expected Behavior**

Holding mousedown on tray should show the menu on Max OSX.

**Actual behavior**

Holding mousedown on tray doesnt show the menu on Max OSX.

**To Reproduce**

Can try this example, or any tray on Mac.

https://github.com/electron/electron-api-demos/blob/2a8c1f46b582b2762c2cf0afc7559082726255b5/main-process/native-ui/tray/tray.js

**Additional Information**

I see discussions closed [here](https://github.com/electron/electron/issues/4384) and [here](https://github.com/electron/electron/issues/10929) and even [here](https://github.com/electron/electron/issues/10934#issuecomment-340066195) but with no clear reason why besides they didn't follow the right ticket format or for some reason because the suggestion to fix it was slightly off.

This one is more clear, it basically asks to make it feel native, which would include:

- Open it on mousedown
- Select an item on mouseup

**Comment by MarshallOfSound** [comment]
@natew We currently have quite a bit of special logic around popping up the tray menu on macOS.  Having tested a few apps though I do see that this is inconsistent, most native apps pop up the menu on mouse down not up.

https://github.com/electron/electron/blame/master/atom/browser/ui/tray_icon_cocoa.mm#L273-L320

Not sure what the valid fix would be here though considering we can't drop all that logic for our click and mouse events

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by natew** [comment]
Still valid and a big downgrade for certain types of apps.

**Comment by codebytere** [comment]
This was fixed in https://github.com/electron/electron/pull/18981.
