### ISSUE TITLE
SourceMap show incorrect content in devtools

### ISSUE THREAD

**Issue by fpsqdb** [electron/electron#14683]
* Electron version: 3.0.0
* Typescript: 3.0.3
* Operating System (Platform and Version): Windows 10 1803
* on last known working Electron version (if applicable): 2.0.9

**Expected Behavior**
This is gif record from 2.0.9
![correct](https://user-images.githubusercontent.com/6482819/45737426-553f7e80-bc20-11e8-8ced-49c6ac58ee7a.gif)

**Actual behavior**
show incorrect content when click the source file. This is gif record from v3.0.0
![error](https://user-images.githubusercontent.com/6482819/45737404-4c4ead00-bc20-11e8-874b-f82c20896e45.gif)

**To Reproduce**
You can see when click `keyCodes.ts` it shows `winjs.base.js` content.
```
keyCodes.ts -> winjs.base.js
iterator.ts -> uri.ts
idGenerator.ts -> types.ts
... ...
... ...
arrays.ts -> event.ts
actions.ts -> error.ts
```
I have trid to make a small reproduce project but failed. It seems only happen when there have too much files in project.

**Comment by zp1996** [comment]
some update on this?

**Comment by jyd519** [comment]
Electron 4.0 has this bug too.

**Comment by Micircle** [comment]
Try to set devtool to 'inline-source-map', if you build your project with webpack.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by rezonant** [comment]
Yes, I am experiencing this bug on electron 4.2.4. I didn't notice this before despite doing quite a bit of debugging, but I believe I was using 4.1.3 during my previous debug spree.

**Comment by electron-triage** [comment]
Please upgrade to at least Electron 6.x.y as reported in the above comment. We are no longer pushing fixes to versions older than 6.x.y per our [supported version policy](https://www.electronjs.org/docs/tutorial/support#supported-versions). Feel free tor each out if you are still experiencing this issue on a later version and we can reopen.
