### ISSUE TITLE
Can I drag a div out of electron app ?

### ISSUE THREAD

**Issue by icodinglee** [electron/electron#14680]
In some case, I need to drag a div out of the electron app , when I released the element, it will go back and trigger a callback function. is there any way to solve this problem?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
