### ISSUE TITLE
`makeSingleInstance` lost its TypeScript definition in 3.0.0 tho it's only deprecated

### ISSUE THREAD

**Issue by davidnorthetal** [electron/electron#14692]
* Output of `node_modules/.bin/electron --version`: v3.0.0
* Operating System (Platform and Version): Windows 10 x64
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v2.0.5

**Expected Behavior**
I compile my TypeScript electron application.

No errors

**Actual behavior**
I compile my TypeScript electron application.

error TS2339: Property 'makeSingleInstance' does not exist on type 'App'.

**Additional Information**
`makeSingleInstance` got removed here: https://github.com/electron/electron/commit/dcd580b6cfa88087eb56ce4660022c0ddf60cadc

while this commit WAS NOT merged into 3.0.0 ( which is correct, according to https://github.com/electron/electron/blob/master/docs/api/breaking-changes.md#planned-breaking-api-changes-40 ), apparently the TypeScript definition got still removed

**Comment by MarshallOfSound** [comment]
@davidnorthetal The TS definitions are generated from our docs and this deprecated API was removed from the docs and replaced with its new version `requestSingleInstanceLock` when we deprecated `makeSingleInstance` which did happen in `3.0`.  (we deprecate in 3.0 and remove in 4.0)
