### ISSUE TITLE
v3.0.0 fails to create a working renderer on Linux

### ISSUE THREAD

**Issue by GitSquared** [electron/electron#14697]
* Output of `node_modules/.bin/electron --version`: `v3.0.0`
* Operating System (Platform and Version): `Debian GNU/Linux 9.5 x86_64`
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): `v2.0.10`

**Expected Behavior**
My previously working application, not concerned by any of the [breaking changes](https://github.com/electron/electron/blob/master/docs/api/breaking-changes.md#breaking-api-changes-30), still works fine after upgrading Electron to v3.

**Actual behavior**
The renderer window shows a frozen view of what was underneath it when it opened. Hitting the usual keyboard shortcut to open the devtools doesn't work. Rolling back to the latest v2.x and everything works fine again.

**To Reproduce**
Simply launch electron v3.0 without any arguments (or `-d`), even the default bundled app doesn't work.

**Screenshots**
![electron_bug](https://user-images.githubusercontent.com/24496417/45767911-c2acd880-bc3b-11e8-8f71-911c7edcc319.png)
On the left is the working default app on v2. On the right is v3. I blurred the window for privacy reasons, the point is it's showing a frozen view of my desktop.

---
**Additional Information**
Debian 9.5 x86_64.
Kernel is `4.9.0-8-amd64`.

Integrated GPU is `Intel HD Graphics 4600` on an `i5-4200H` Haswell chip.
2nd GPU is `Nvidia GeForce 850M`.

Intel driver: [`xserver-xorg-video-intel`](https://packages.debian.org/stretch/xserver-xorg-video-intel) `2:2.99.917+git20161206-1 amd64` (latest in stretch) aka default xorg handler for integrated GPUs
Nvidia driver: [`nvidia-driver`](https://packages.debian.org/stretch/nvidia-driver) `384.130-1 amd64` (also latest in stretch) aka latest closed source driver from nvidia

*Side note: I'm using [`bumblebee`](https://packages.debian.org/stretch/bumblebee) to handle the Optimus logic and switching between GPUs.*

**Comment by nornagon** [comment]
What graphics card/drivers are you using? Do you see the behaviour still when running with `--disable-gpu`?

**Comment by nornagon** [comment]
In order to do any sort of debugging, we'll need to know the exact model of graphics card you're using. Chromium has very specific GPU blocklists which change frequently, and it's possible your issue was caught in a later version of Chromium than Electron v3 is running. We may be able to backport a fix or a blocklist change, but we won't be able to determine the right course of action without more information.

**Comment by jrobeson** [comment]
@nornagon : but are any of intel's GPUs on that blocklist?

**Comment by nornagon** [comment]
yes.

**Comment by GitSquared** [comment]
@nornagon I'll come back with more info.

**Comment by GitSquared** [comment]
@nornagon OK, GPU is `Intel® HD Graphics 4600` integrated in a `i5-4200H` Haswell processor.

Just in case, the second GPU is a Nvidia `Geforce 850M`.

**Comment by GitSquared** [comment]
Kernel is `4.9.0-8-amd64` (that rules out [your first link](https://chromium.googlesource.com/chromium/src/gpu/+/master/config/software_rendering_list.json#907) i'm afraid).

Intel driver: [`xserver-xorg-video-intel`](https://packages.debian.org/stretch/xserver-xorg-video-intel) `2:2.99.917+git20161206-1 amd64` (latest in stretch) aka default xorg handler for integrated GPUs
Nvidia driver: [`nvidia-driver`](https://packages.debian.org/stretch/nvidia-driver) `384.130-1 amd64` (also latest in stretch) aka latest closed source driver from nvidia

I don't normally use Chrome but i installed the latest stable release and everything works fine. I was able to load [webglreport.com](https://webglreport.com) and everything was OK with a `Mesa DRI Intel(R) Haswell Mobile` renderer.

I might do some more in-depth testing, including building Electron, tomorrow afternoon. I will need a bit of time for this though.

**Comment by nornagon** [comment]
I found https://bugs.chromium.org/p/chromium/issues/detail?id=554008, which looks like a similar issue to yours. They're using the same intel driver as yours (2.99.917) and a similar kernel (4.1.0 instead of 4.9.0). That patch was first released in Chrome 68, so it's possible that when #14677 lands the bug will be fixed :)

The linked chromium bug suggests that the desktop is only showing for a moment, though, not persistently. I'm curious to know if resizing the window changes the content at all?

**Comment by u4aew** [comment]
@GitSquared A similar problem appeared in 2 versions of the electron https://github.com/electron/electron/issues/14430

**Comment by GitSquared** [comment]
@nornagon It seems like resizing the window activates a hidden barcode-generating feature.

![barcode](https://user-images.githubusercontent.com/24496417/45881257-f5c1aa00-bdaa-11e8-816c-a10c81482783.png)

Anyway, I also planned to get back to you with testing results but i'm used to run thin on resources and after messing around a bit it turns out i don't have enough HDD space left to build Electron.
I'm gonna figure out a way to get some, but i wanted to keep this thread updated.

@u4aew Your issue seems unrelated - i think? - since the renderer actually works in your case. Freezing after an action and total absence of video output is not the same deal afaik.

**Comment by nornagon** [comment]
Thanks for the update! Perhaps you could pivot to be a barcode-generating company? ;)

#13624 also seems like it might be related?

**Comment by GitSquared** [comment]
@nornagon Hehe, wouldn't complain 'bout it.

Nice one finding #13624, it seems to be the same issue (?), everything "works" like described in this thread (piping electron to /dev/null fixes the issue among other things).
I don't really understand why i wasn't affected with this prior to v3 if the bug itself exists since v2.

**Comment by GitSquared** [comment]
@nornagon I compiled `v4.0.0-nightly.20180905`.
If i use `> /dev/null` or `--disable-gpu`, everything works fine, but without it i don't even get a window.

I don't have any error messages, even with `--enable-logging`.

**Comment by anszom** [comment]
Try running the app without any connection to the tty (./electron (args) < /dev/null >/dev/null 2>/dev/null). If this helps, then see the above PR.

**Comment by GitSquared** [comment]
@anszom This works. Good luck with the PR.

**Comment by GitSquared** [comment]
Closed as #15555 has been merged.
