### ISSUE TITLE
Window controls (traffic lights) is not being rendered on macOS with Electron 3.0.0

### ISSUE THREAD

**Issue by 4eveRS** [electron/electron#14698]
* Output of `node_modules/.bin/electron --version`: 3.0.0
* Operating System (Platform and Version): macOS Sierra 10.12.6
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 3.0.0-beta.1

**Expected Behavior**
creating a new browserWindow with titleBarStyle: hiddenInset, hidden or customButtonsOnHover, should generate the 'traffic lights' in macOS.

**Actual behavior**
The window doesn't generate the traffic lights, making impossible to control the window. (The buttons actions are still in the same visual place, it's just not being rendered).

**To Reproduce**
Just create a browser window and set the titleBarStyle to one of the options available.

**Comment by MarshallOfSound** [comment]
Duplicate #14570
