### ISSUE TITLE
`shell.openItem` is no really control what was successfully opened

### ISSUE THREAD

**Issue by algv** [electron/electron#14691]
* Output of `node_modules/.bin/electron --version`: "1.6.6"
* Operating System (Platform and Version): Windows 10 x64

**Expected Behavior**
[docs](https://electronjs.org/docs/api/shell#shellopenitemfullpath)
```
shell.openItem(fullPath)

* fullPath String

Returns Boolean - Whether the item was successfully opened.
Open the given file in the desktop's default manner.
```

**Actual behavior**
Electron no really control what was successfully opened

**To Reproduce**
I need open document and after successfully opened move to the trash. Simple code:
```js
const shell = electron.shell;

if (shell.openItem(filePath)) {
 shell.moveItemToTrash(filePath);
}
```

There I get error on open what file not exist, because it was already moved to trash. For small files (2kb for example) work nice.

**Comment by MarshallOfSound** [comment]
@algv Electron has no idea what application opened the given file path or what it plans on doing with it.  It may launch and take 20 seconds to read the file or it may read it instantly we don't know and unfortunately, there is no way of us knowing.  If you want to clean up your files I would recommend cleaning them up on computer or application restart.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
