### ISSUE TITLE
[Question] Electron Chromium version update

### ISSUE THREAD

**Issue by alessandroliveri** [electron/electron#14709]
Hi, I need to update Chromium to the last version: somebody can tell me where I can find an updated guide or can say me how I can try to do it because it seems that the guide on the official site it's about the older version? 

Thanks in advice

**Comment by nornagon** [comment]
The Electron team is actively working on upgrading Electron to newer Chromium versions all the time. It's not a trivial process, but you're welcome to join us in the effort! See #14677 for the update to Chromium 68 and https://github.com/orgs/electron/projects/23 for the project board.
