### ISSUE TITLE
getAppMetrics() in 3.0.0 has broken

### ISSUE THREAD

**Issue by computerquip-streamlabs** [electron/electron#14710]
Electron Version: 3.0.0
OS: Windows 10 x86_64

**Expected Behavior**
getAppMetrics should return a valid array recording the metrics of my application.

**Actual behavior**
getAppMetrics returns undefined.

**To Reproduce**
```
const { app } = require('electron');

console.log(app.getAppMetrics());
```
or:
https://github.com/computerquip-streamlabs/electron-quick-start

Each time getAppMetrics is called, it also provides a warning about the use of the `memory` field claiming that its deprecated, even though the above isn't using the memory field.

**Comment by Thomas101** [comment]
Seeing the same here on macOS

**Comment by codebytere** [comment]
@computerquip-streamlabs this isn't a bug, the above is using the memory field; that's how this function is implemented. 

https://github.com/electron/electron/blob/3-0-x/atom/browser/api/atom_api_app.cc#L1127

**Comment by computerquip-streamlabs** [comment]
I can define a bug as something an implementation is doing that's undesirable. Either way, the main crux of the problem still exists in that the function doesn't return anything useful.

**Comment by Thomas101** [comment]
> @computerquip-streamlabs this isn't a bug; the above is using the memory field since that's how this function is implemented.

@codebytere I think there might be some crossed wires here. The `app.getAppMetrics()` call returns `undefined` in version 3. For example

### Electron 2
```js
console.log(app.getAppMetrics())
/*
[
  {
    pid: pid,
    type: 'Tab',
    cpu: { idleWakeupsPerSecond:0, percentCPUUsage:0 },
    memory: {
      peakWorkingSetSize:0,
      privateBytes:0,
      sharedBytes:0,
      workingSetSize:0
    },
    { ... }
]
*/
```

### Electron 3
```js
console.log(app.getAppMetrics())
/*
undefined
*/
```
[getAppMetrics()](https://github.com/electron/electron/blob/3-0-x/lib/browser/api/app.js#L62) doesn't return anything anymore. Looks the change in https://github.com/electron/electron/commit/89148bcf8dad735e68b644798a48acba50658dca#diff-6ba4c23225436343131188beec8d2370 was where the return statement disappeared :-)

**Comment by codebytere** [comment]
@Thomas101 you are extremely correct! Thanks for clarifying that 😸 The PR to fix it is now merged in `3-0-x` and should be out in the next patch release.
