### ISSUE TITLE
Bugs on webview/webContents since 3.0.0-beta.6 (Introduction of OOPIF)

### ISSUE THREAD

**Issue by 4eveRS** [electron/electron#14716]
* Output of `node_modules/.bin/electron --version`: 3.0.0
* Operating System (Platform and Version): macOS Sierra 10.12.6
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 3.0.0-beta.5

**Expected Behavior**
webviews should work like it used to, before the OOPIF.

**Actual behavior**
Since the update to use OOPIF in webviews, all my webviews are not working properly. This still happens in the version released today 3.0.0.

By debugging i've found out that:

- all commands that require a webview.getWebcontents() don't execute properly.
(Ex: have webview and try to capture page through webview.getWebContents().capturePage(), it used to work on 3.0.0-beta.5, now it simply doesn't do anything)

- all events in page doesn't work properly. (Ex: I have a webview preload script that log user actions like: click on elements, input data on forms, etc. It used to work on 3.0.0-beta.5, now it doesn't do anything).

- events in webviews are firing twice (Ex: did-start-loading firing twice when webview start loading).

- webview is sometimes having two webContents (Each webContent have a id) attached to it ???
It fires a event in each webContents, leading it to failure. (Ex: having a permissionRequestHandler, access google.com, see it fires twice, one time for a 'ghost' webContents, and one time for the actual webContent.)

-webview navigate / redraw its page, only when the user do navigation in-page, refresh, navigate back or forward.

If the user tries to do a webview.loadURL, the webview get mixed content, because it fires twice each event, leading to a webview incorrect behavior. 

In older versions of the beta, it used to freeze the webview frame (not redrawing the page content), now in version 3.0.0, it doesn't freeze, but doesn't navigate properly to the new page, making the webview stay in the older page. (The user can still interact with the older page, clicking on links, buttons, etc.)

I think that is occurring a bug, that is making two webContents to be attached to one webview and making so that the webview still renders the older webContent while it navigated to the new page, keeping both webpages "status", while instead, it should update the webContent of the webview to the page that the user navigated using webview.loadURL.

So resuming, I think that there's a issue with the relation webview and webContents, causing all those bugs.

**Comment by Evoks** [comment]
There are also some problems on remote object in webviews `preload` script.
e.g.: `remote.getCurrentWindow()` return `{}`.

**Comment by psicounterman** [comment]
I'm seeing similar issues, mostly that changing the URL by setting .src or by changing location.href is changing what's shown in the dev tools elements, but not changing what is shown.  Very odd and a blocker for me.

**Comment by sbeatz** [comment]
is there any update on this?
having the same issue here:
I'm logging into a webpage shown in a webview using executeJavaScript - it also clearly login in but the content shown is never updated

**Comment by 4eveRS** [comment]
Hello @zcbenz, any updates on these issues? Looking forward to update to Electron 3.x / 4.x and still use the webviews as before :)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
