### ISSUE TITLE
My Notification don't work

### ISSUE THREAD

**Issue by fakaka** [electron/electron#14718]
* Output of `node_modules/.bin/electron --version`: v1.8.7
* Operating System (Platform and Version): windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
Notification work

**Actual behavior**
Notification don't work

**To Reproduce**
none.

You can fork [electron-quick-start](https://github.com/electron/electron-quick-start) and include a link to the branch with your changes.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone $YOUR_URL -b $BRANCH
$ npm install
$ npm start || electron .
```
**Screenshots**
none

**Additional Information**
https://electronjs.org/docs/tutorial/notifications#windows

**Comment by MarshallOfSound** [comment]
As per our windows notification documentation that you linked you need to do some set up before notifications work on windows (this is an OS requirement)

> On Windows 10, a shortcut to your app with an Application User Model ID must be installed to the Start Menu.

> On Windows 8.1 and Windows 8, a shortcut to your app with an Application User Model ID must be installed to the Start screen. Note, however, that it does not need to be pinned to the Start screen.

> On Windows 7, notifications work via a custom implementation which visually resembles the native one on newer systems.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
