### ISSUE TITLE
$ npm i -D electron@latest installs 2.0.10 instead of 3.0.0

### ISSUE THREAD

**Issue by Carsten0001** [electron/electron#14723]
Hi Electron Team,
```
$ npm i -D electron@latest
# Electron   3.0.0
# Node       10.2.0
# Chromium   66.0.3359.181
```
The code template above is from https://electronjs.org/ main page.

But it's wrong, because `$ npm i -D electron@latest` installs 2.0.10. 
Because in NPM the newest released Version is 2.0.10.  => https://www.npmjs.com/package/electron

**Comment by MarshallOfSound** [comment]
Hey @Carsten0001 thanks for the report, `3.0.0` has been re-tagged correctly as `latest`
