### ISSUE TITLE
Run `gn gen out/Debug` and get error : `... AttributeError: 'NoneType' object has no attribute 'endswith'`

### ISSUE THREAD

**Issue by ossdev07** [electron/electron#14726]
While running npm install-test, i am facing below error:
npm test

> electron@4.0.0-nightly.20180905 test /electron
> node ./script/spec-runner.js electron/spec

electron/spec: 1: electron/spec: /out/Debug/electron: not found
Traceback (most recent call last):
  File "/electron/script/dbus_mock.py", line 28, in <module>
    subprocess.check_call(sys.argv[1:],shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/out/Debug/electron', 'electron/spec']' returned non-zero exit status 127
npm ERR! Test failed.  See above for more details.

For above error i have read build instructions to generate output file, but facing below error:

gn gen out/Debug '--args=import("//electron/build/args/debug.gn") clang_base_path = "/usr/bin"'
Traceback (most recent call last):
  File "/depot_tools/gn.py", line 71, in <module>
    sys.exit(main(sys.argv))
  File "/depot_tools/gn.py", line 49, in main
    'gn', 'gn' + gclient_utils.GetExeSuffix())
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

Please suggest me on solving this issue.
Thanks in advance.

**Comment by MarshallOfSound** [comment]
@ossdev07 In order to run the tests on linux you need `python-dbusmock` installed

**Comment by MarshallOfSound** [comment]
@ossdev07 Actually may have jumped to the wrong conclusion here, that error indicates that you haven't built Electron yet. 

> /out/Debug/electron: not found

If you haven't built Electron you can't run the tests

**Comment by ossdev07** [comment]
Thanks for the reply.
But while building electron I have faced error after giving command 
**gn gen out/Debug '--args=import("//electron/build/args/debug.gn") clang_base_path = "/usr/bin" target_cpu="arm"'**

Traceback (most recent call last):
  File "/depot_tools/gn.py", line 71, in <module>
    sys.exit(main(sys.argv))
  File "/depot_tools/gn.py", line 49, in main
    'gn', 'gn' + gclient_utils.GetExeSuffix())
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

Could you suggest me on this error. Thanks.

**Comment by alexeykuzmin** [comment]
@ossdev07 
Did you set `CHROMIUM_BUILDTOOLS_PATH` before running `gn gen`?

https://github.com/electron/electron/blob/master/docs/development/build-instructions-gn.md#building
```
$ cd src
$ export CHROMIUM_BUILDTOOLS_PATH=`pwd`/buildtools
```

**Comment by ossdev07** [comment]
Thanks for the reply. I have the path and tried again and i am getting below error:
**gn gen out/Debug --args="import(\"//electron/build/args/debug.gn\") $GN_EXTRA_ARGS target_cpu=\"arm\""**

/depot_tools/electron-gn/.gclient_entries missing, .gclient file in parent directory /depot_tools/electron-gn might not be the file you want to use.
gn.py: Could not find gn executable at: /depot_tools/electron-gn/src/buildtools/linux64/gn

I am running the build in debian aarch64(Linux e7fac9d4ba1c 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:33:57 UTC 2017 aarch64 aarch64 aarch64 GNU/Linux)

Please suggest me on solving this error.
Thanks in advance.
