### ISSUE TITLE
Failed to build electron on Windows with error D8021 : invalid numeric argument '/Wno-logical-not-parentheses'

### ISSUE THREAD

**Issue by KarenHuang2016** [electron/electron#14725]
* Operating System (Platform and Version):
Windows 2016 Server + VS 2017

**Issue description:**
We build electron on Windows 2016 Server + VS 2017. It failed to build with error D8021 : invalid numeric argument '/Wno-logical-not-parentheses'. It seems cl cannot support options '/Wno-logical-not-parentheses' and '-Wno-sign-compare'. If we removed options '/Wno-logical-not-parentheses' and '-Wno-sign-compare', it compiles fine. Could you please help to take a look? Thanks in advance.

**cl command which reproduce error:**
C:/tools/python2/python.exe ../../build/toolchain/win/tool_wrapper.py cl-wrapper ninja -t msvc -e environment.x86 -- "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.14.26428\bin\HostX64\x86/cl.exe" /nologo /showIncludes  -DCARES_STATICLIB -DCARES_PULL_WS2TCPIP_H=1 -DV8_DEPRECATION_WARNINGS -DUSE_AURA=1 -DNO_TCMALLOC -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DOFFICIAL_BUILD -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -D_HAS_EXCEPTIONS=0 -D__STD_C -D_CRT_RAND_S -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_ATL_NO_OPENGL -D_WINDOWS -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -DPSAPI_VERSION=1 -DWIN32 -D_SECURE_ATL -D_USING_V110_SDK71_ -DWINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP -DWIN32_LEAN_AND_MEAN -DNOMINMAX -D_UNICODE -DUNICODE -DNTDDI_VERSION=0x0A000002 -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../../third_party/electron_node/deps/cares/include -I../../third_party/electron_node/deps/cares/src -I../../third_party/electron_node/deps/cares/config/win32 -I../.. -Igen -I../../third_party/electron_node/deps/cares/include /utf-8 /Gy /FS /bigobj /d2FastFail /Zc:sizedDealloc- /W4 /WX /wd4091 /wd4127 /wd4251 /wd4275 /wd4312 /wd4324 /wd4351 /wd4355 /wd4503 /wd4589 /wd4611 /wd4100 /wd4121 /wd4244 /wd4505 /wd4510 /wd4512 /wd4610 /wd4838 /wd4995 /wd4996 /wd4456 /wd4457 /wd4458 /wd4459 /wd4267 /wd4702 /O1 /Ob2 /Oy- /Zc:inline /Gw /Oi /Zi /MT -Wno-logical-not-parentheses -Wno-sign-compare /TC /c ../../third_party/electron_node/deps/cares/src/ares_gethostbyaddr.c /Foobj/third_party/electron_node/deps/cares/cares/ares_gethostbyaddr.obj obj/third_party/electron_node/deps/cares "cares_c.pdb"
cl : Command line error D8021 : invalid numeric argument '/Wno-logical-not-parentheses'

**Comment by nornagon** [comment]
Are you building from master? Electron only supports building with clang, not MSVC.

**Comment by KarenHuang2016** [comment]
@nornagon Thanks for your response. Actually we always build electron on Windows with MSVC for a long time. Can I know why Electron doesn't support building with MSVC any more?

**Comment by MarshallOfSound** [comment]
@KarenHuang2016 As part of the Chromium 67 upgrade building Chromium is only supported with clang, as such Electron only supports clang as well.  This change was made during the 67 upgrade and as part of our move to `gn` from `gyp`

**Comment by KarenHuang2016** [comment]
@MarshallOfSound I got it. Thank you so much for clarifying this.
