### ISSUE TITLE
3.0 regression: offscreen window `paint` event returns empty `image`

### ISSUE THREAD

**Issue by dotansimha** [electron/electron#14739]
Since upgrading to 3.0 (from 2.0.10), offscreen image works in a different way. 

In 2.0.10, creating an offscreen window, loading a webpage that changes about every 2 seconds, resulting in empty file (tried `toDataUrl` and `toPNG`).
Some pages, that has animations in it and more, displays an partial-rendered page.

My logic is simple: subscribe to `paint` event, take the image (with `toPNG` or `toDataUrl`) and the use `fs.writeFile` to save the image to file.

* Output of `node_modules/.bin/electron --version`:
v3.0.0

* Operating System (Platform and Version): 
Tested on Mac OS X High Sierra and Windows 10.

* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):
v2.0.10

**Expected Behavior**
Offscreen should be rendered correctly.

**Actual behavior**
invalid rendering.

**To Reproduce**
```javascript
  const outputWindow = new BrowserWindow({
    width: 1920,
    height: 1080,
    enableLargerThanScreen: true,
    resizable: false,
    frame: false,
    show: false,
    skipTaskbar: true,
    webPreferences: {
      offscreen: true,
    }
  });

   outputWindow.loadUrl('https://daneden.github.io/animate.css/')

    outputWindow.webContents.on('paint', (event, dirty, image) => {
      fs.writeFileSync('myfile.png', image.toPNG());
    });;
```

**Screenshots**

#### With 2.0.10 (some canvas drawings)
![2 0 0-static](https://user-images.githubusercontent.com/3680083/45839419-9a44dd00-bd14-11e8-99e4-c8f627ce55b0.png)

#### With 3.0.0 (empty png?)
![3 0 0-static](https://user-images.githubusercontent.com/3680083/45839292-3de1bd80-bd14-11e8-841b-a50edd416ed1.png)

#### With 2.0.10 (looks good)
![2 0 0-dynamic](https://user-images.githubusercontent.com/3680083/45839428-a03abe00-bd14-11e8-9885-7f177568b70d.png)

#### With 3.0.0 (incorrect rendering)
![3 0 0-dynamic](https://user-images.githubusercontent.com/3680083/45839287-3ae6cd00-bd14-11e8-9918-f0f0d11a2b62.png)

**Comment by countravioli** [comment]
Seeing this too in my application, note the same results happen from the capturePage api. My investigation seems to show at some point (very quickly), the offscreen window just stops painting. 

I brought up devTools for the offscreen window I called show() on it. Then using the console, i change the background of the page to green. Nothing changes. I can verify in the elements tab that everything looks right.

Not sure if this is useful either, but I had had problems with capturing and gpu acceleration in the past. I tried app.disabledHardwareAcceleration() but it didn't work. It did produce a different result in that when I call show() on that same window, nothing is visible other than the little message "No content under offscreen mode"

Totally random guess here, is that the new version of chrome is optimized to not do painting when a tab isn't in focus (e.g. you have site A and site B open in your web browser, if you are looking at site A then switch to B that is when any needed paints happen. Maybe with the new version of chrome, webkit we need to flag the offscreen renderer as always in focus?

**Comment by brenca** [comment]
I looked into this and it looks like this is an upstream bug, `4.0.x` seems to be unaffected. 
Also, this is just the first paint that's half-done, so all the other frames seem to be OK, and the page ends up rendering fine (but you can see that it initially is broken for a split second).

**Comment by dotansimha** [comment]
Thanks @brenca , I'll check it with 4.0.x and update soon.

**Comment by dotansimha** [comment]
It works with v4.
