### ISSUE TITLE
A modal BrowserWindow loses focus

### ISSUE THREAD

**Issue by scottrippey** [electron/electron#14737]
* Output of `node_modules/.bin/electron --version`:  **v2.0.10** (also reproduced with **v2.0.3** and **v3.0.0**)
* Operating System (Platform and Version): **macOS High Sierra v10.13.6**
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): **unknown**

**Expected Behavior**
When I display a modal BrowserWindow, I expect the window to stay focused, and the parent window is not focusable, even if clicked.

**Actual behavior**
When I click the parent window, it steals focus from the modal window.  
When I switch to another application and back, the modal gets focused again.

**To Reproduce**
You can reproduce with very minimal steps; basically, any BrowserWindow with the `parent` and `modal: true` properties exhibits this behavior.

This repo provides a simple HTML file to make the window's "focus" very visible.
https://github.com/scottrippey/electron-issue-with-modal-focus

```sh
$ git clone https://github.com/scottrippey/electron-issue-with-modal-focus.git
$ npm install
$ npm start
```

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/430608/45836982-d9067300-bcd3-11e8-8afb-8dcf06096109.gif)

**Additional Information**
I have reproduced this issue on multiple Macs as well.

**Comment by codebytere** [comment]
This should be fixed in latest stable release lines of Electron!

**Comment by scottrippey** [comment]
Awesome, thanks @codebytere!
