### ISSUE TITLE
compile electron with modified libchromiumcontent

### ISSUE THREAD

**Issue by manang** [electron/electron#14735]
Hi,
I have an application that uses electron-3.0.0-beta8
I want to rebuild it with a different libchromiumcontent part. I need to modify the chromium source in some parte.
could you tell me the steps that I have to follow to build a modified version of electron?
Thank you very much
Angelo

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
