### ISSUE TITLE
callback(true) for "certificate-error" event handler has no effect

### ISSUE THREAD

**Issue by tonglingchen** [electron/electron#14745]
* Electron 2.0.9
* Windows 10

**Expected Behavior**
callback(true) for "certificate-error" event handler should work for webviewtag.

**Actual behavior**
callback(true) for "certificate-error" event handler has no effect.

**To Reproduce**
I have a repo (forked from quick start) to demo this issue. 
Please use following repo to repro:
```sh
$ git clone https://github.com/tonglingchen/electron-quick-start
$ npm install
$ npm start
```

**Comment by MarshallOfSound** [comment]
@tonglingchen You are listening to a `remote` event in the renderer process (`webview.getWebContents()` returns a remote proxy to the web contents).  `event.preventDefault()` needs to be called synchronously in order for it to work, the event is emitted to the renderer process asynchronously so by the time you call `preventDefault()` it is too late.

You will need to attach this listener in the main process

Refs: https://github.com/tonglingchen/electron-quick-start/commit/033f734f40ebd60c0c21e169494ebd7679a37eba#diff-eacf331f0ffc35d4b482f1d15a887d3bR51

**Comment by tonglingchen** [comment]
Thank you @MarshallOfSound! That explains...

**Comment by StringKe** [comment]
@MarshallOfSound 
```javascript
      domReady(event, webview) {
        this.webview.getWebContents().on('certificate-error', (event, url, error, certificate, callback) => {
          if (this.view.plugin.security) {
            this.certificateError.show = true;
            this.certificate.link = nodeUrl.parse(url).host;
            this.certificate.error = error;
            this.certificate.certificate = certificate;
            callback(false);
          } else {
            this.certificateError.show = false;

            event.preventDefault();
            callback(true);
          }
        });
      },
```
Even if this is done event.preventDefault(); still doesn't work

electron-vue
