### ISSUE TITLE
Cannot get multiple getUserMedia video streams at once

### ISSUE THREAD

**Issue by card-b** [electron/electron#14743]
* Output of `node_modules/.bin/electron --version`: 3.0.0
* Operating System (Platform and Version): MacOS 10.13.6 
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): unknown

**Expected Behavior**
Loop through available cameras after MediaDevices.enumerateDevices and place each camera into a video element

**Actual behavior**
enumerateDevices will only return the video devices that were present when you started the app if you have a built-in webcam. Plugging in a USB camera will trigger the ondevicechange event, and enumerateDevices will show that the number of audio inputs has changed, but the number of video inputs will not change. If you start with no usb camera, then plug one in, it will not report the camera. If you start with a usb camera plugged in, it will still be listed in enumerateDevices even when unplugged.

**To Reproduce**
Clone and run my branch of electron quick start, connect multiple webcams (or just one if you have a MacBook with a Facetime Cam) and run the app. 

You can fork [electron-quick-start](https://github.com/card-b/electron-quick-start), changes are all in index.html

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone https://github.com/card-b/electron-quick-start
$ npm install
$ npm start || electron .
```

**Additional Information**
I've tried destroying the stream before I load in the new streams, setting the enumerateDevices call on a very long timeout to ensure that the new/removed device should be reflected in the enumerateDevices call, and using exact ids as the video ids, but nothing seems to affect it. Since the groupId does change in the audio sources, I've tried loading the videos based on the groupIds of the audio sources, and while the updates are present, it shouldn't work this way.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
