### ISSUE TITLE
Regression in v3 with `CmdOrCtrl+Plus` accelerator in MenuItem

### ISSUE THREAD

**Issue by bigtimebuddy** [electron/electron#14742]
* Output of `node_modules/.bin/electron --version`: 3.0.0
* Operating System (Platform and Version): MacOS 10.13.6
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2.0.10

**Expected Behavior**
When using `'CmdOrCtrl+Plus'` as an accelerator for a menu, should trigger command when keyboard command is pressed. Other accelerators work as expected.

**Actual behavior**
In v3, this particular accelerator no longer works. The menu item can be clicked manually, but shortcut doesn't work.

**To Reproduce**
https://github.com/bigtimebuddy/electron-plus-bug

```sh
$ git clone https://github.com/bigtimebuddy/electron-plus-bug
$ npm install
$ npm test
```
When running the app trigger using key-command: Command + Plus (+). No alert appears, manually clicking the menu item trigger alert. Accelerator shows up in the menu item.

**Comment by zcbenz** [comment]
If I understand it correctly, `CmdOrCtrl+Plus` should mean <kbd>Shift</kbd>+<kbd>Cmd</kbd>+<kbd>=</kbd> right? There is no real <kbd>+</kbd> key on the keyboard, there is only <kbd>=</kbd>+<kbd>Shift</kbd>.

<kbd>Shift</kbd>+<kbd>Cmd</kbd>+<kbd>=</kbd> works correctly on my macOS 10.13.6 machine.

**Comment by doms** [comment]
@zcbenz it's possible that @bigtimebuddy could be using a keyboard with a numeric keypad, those keyboards have the <kbd>+</kbd> key (but I'm not sure if the accelerators catch that key 🤔 )

![mq052](https://user-images.githubusercontent.com/8808097/46632299-d1d2c800-cb0f-11e8-9110-3177c7b87a12.png)

**Comment by bigtimebuddy** [comment]
`CmdOrCtrl+Plus` works fine when triggered by the standalone <kbd>+</kbd> key like @doms suggested. Also, `CmdOrCtrl+=` works as well and `CmdOrCtrl+Plus` works with the <kbd>⌘</kbd>+<kbd>shift</kbd>+<kbd>=</kbd>.

The issue can be illustrated by using the `zoomin` menu item role as well (see below). In this case `⌘+` shows up in the menu as the keyboard shortcut, but this is no longer triggered by <kbd>⌘</kbd>+<kbd>=</kbd>.

In the Chrome browser and in Electron v2, for instance, the keyboard shortcut shows up as `⌘+` in the menu but is also optionally triggered with <kbd>⌘</kbd>+<kbd>=</kbd>. It's a pretty common pattern in many desktop applications to allow `⌘+` as a synonym for `⌘=`.

```js
 {
      label: 'View',
      submenu: [
        {role: 'zoomin'}
      ]
    }
```

It feels like a bug to me because it's inconsistent with other applications and v2, but if this is the intended functionality moving forward, I'm fine closing this issue.

**Comment by zcbenz** [comment]
@bigtimebuddy Thanks for the explanation, I think the old behavior should be considered a bug, since currently the accelerator can only map to one key combination for now.

For the issue with the zoom menu item, it is being tracked at https://github.com/electron/electron/issues/5256.

**Comment by javan** [comment]
I think this issue should be reopened. The default accelerator for the `zoomin` role worked in Electron v2 and is now broken in v3.

For example, the [electron-quick-start](https://github.com/electron/electron-quick-start) app no longer responds to <kbd>⌘</kbd>+<kbd>+</kbd> because it uses Electron's default `View` menu: https://github.com/electron/electron/blob/b21dbdb20d011564dce1a31d505fe4b8fbd96684/default_app/menu.js#L57-L59

**Comment by godza** [comment]
I'm still having issue with this item. Almost all Mac apps allow zooming in with Cmd+= and Cmd+Shift+= (Basically Cmd + Plus) and they show accelerator label in the menu bar as (Cmd + Plus). Some of the apps that support this behavior are Chrome, Safari, Airmail, Maps, Books, Calendar, Dictionary and many, many others.

I cannot use role "zoomin", as i have my custom zooming ability.

**Comment by brightest-dazes** [comment]
Where is the zoomin located?

**Comment by godza** [comment]
> Where is the zoomin located?

You can use 'role' : 'zoomin' when you're specifying menu options if you want the menu item to behave like the default zoom in (to zoom in page)
