### ISSUE TITLE
Electron 3.0 Disables Disjoint Timer WebGL Extensions

### ISSUE THREAD

**Issue by markusmoenig** [electron/electron#14749]
Electron: 3.0

Electron 3.0 disables the Chrome WebGL & WebGL v2 disjoint timer extensions (https://www.khronos.org/registry/webgl/extensions/EXT_disjoint_timer_query_webgl2).

Chrome temporarily disabled them because of the potential profiling of the users computer, which is NOT a problem on a Desktop installation. Chrome 70 is about to re-enable them.

For WebGL developers these extensions are crucial as they allow timing of WebGL operations, taking them out of 3.0 severally limits the functionality of WebGL (and for no reason) !!

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR.
