### ISSUE TITLE
referrer is always "" in custom protocol handler

### ISSUE THREAD

**Issue by Gozala** [electron/electron#14747]
Output of node_modules/.bin/electron --version:
    v2.0.8
    Operating System (Platform and Version):
    MacOS 10.13.6

**Expected Behavior**
Referrer should reflect the document request came from

**Actual behavior**
Referrer is always ""

**To Reproduce**

Try out this branch https://github.com/gozala/electron-quick-start/tree/fetch-origin 

You can see that both XHR and fetch seem to have this issue. Also worse noting that both `referrer` and `referrerPolicy` of the fetch API does not seem to have any effect and request's referrer remains "".

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
