### ISSUE TITLE
TypeScript typedefinitions coalesce deprecations and removal

### ISSUE THREAD

**Issue by davidnorthetal** [electron/electron#14753]
via #14692 - when Electron 3.0.0 got released, the `electron.d.ts` typedefinition file that is generated from the API documentation removed `makeSingleInstance` tho it's only documented as deprecated (and the electron-js files still contain it).

So in effect, from TypeScript's perspective whenever a JavaScript function becomes deprecated, it becomes instantly removed altogether for TypeScript.

This to me seems very much like an oversight/bug, especially because the already existing [breaking-changes documentation](https://github.com/electron/electron/blob/master/docs/api/breaking-changes.md) doesn't specifically mention this in any way.

---

I'd expect this to be resolved in two ways: either the typescript definition files actually start differentiating deprecation/removal or I'd suggest that the breaking changes documentation mentions how TypeScript files always remove and never deprecate.

Thanks for any response/input on this matter.
Dnorth

**Comment by MarshallOfSound** [comment]
Closing this out as we now leave deprecated APIs in the docs until they are actually removed from the codebase
