### ISSUE TITLE
`will-navigate` not triggered for some website. 

### ISSUE THREAD

**Issue by erguotou520** [electron/electron#14751]
* Output of `node_modules/.bin/electron --version`: 3.0.0-beta8
* Operating System (Platform and Version): win/mac
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 3.0.0

**Expected Behavior**
`will-navigate` event can be triggered successfully.

**Actual behavior**
`will-navigate` is not triggered.

**To Reproduce**
We have `QQ` oath login function in our electron app. The oauth url looks like `https://graph.qq.com/oauth2.0/authorize?client_id=xxx&redirect_uri=xxx&response_type=code&scope=get_user_info&state=xxx`.

We can success catch the `will-navigate` event in `electron@2.0.8` as well as `2.0.10`, but failed when update electron to 3.x(tried 3.0.0-beta8 and 3.0.0).

Another `wechat` oauth function works well for both electron 2.x and 3.x and it's url looks like `https://open.weixin.qq.com/connect/qrconnect?appid=xxx&redirect_uri=xxx&response_type=code&scope=snsapi_login&state=xxx#wechat_redirect`

**Additional Information**
Some major code:
```js
win.webContents.on('will-navigate', (e, redirectUrl) => {
  if (redirectUrl.startsWith(this.callbackUrl)) {
    e.preventDefault()
    // do something
  }
})
```

**Comment by akozich** [comment]
Faced the same issue. Reproducible on 3.0.0 and 3.0.2. I found that 'will-navigate' is triggered whenever any link is clicked but is not triggered when location is changed by form submission.

**Comment by akozich** [comment]
2.0.10 works well

**Comment by NicoAiko** [comment]
I also face this issue!
Still reproducible on 3.0.3 and 3.0.4!

Please fix this asap!

**Comment by Thomas101** [comment]
In my experience it seems to fail on the vast majority of navigations. You can bind up to the `session.webRequest` and listen for `onBeforeRequest` to work around this.

If you're following the [security advice](https://github.com/electron/electron/blob/master/docs/tutorial/security.md#13-disable-or-limit-navigation) on navigation and haven't noticed this, there's potential for security holes downstream :-/

**Comment by guillaumearm** [comment]
same on Electron 3.0.5

**Comment by WampirenoK** [comment]
same on Electron 3.0.8

**Comment by 9aram** [comment]
use **did-navigate** it works to me! :)

**Comment by sachetsharma1** [comment]
Is the a planned fix version for this?

**Comment by goodhyun** [comment]
Even 5.0.1 has this issue: Tumblr and Wordpress.com logins were affected, FB/Twitter seem okay though.

**Comment by MarshallOfSound** [comment]
`will-navigate` does not get emitted for redirects inside the navigation chain.

You need to subscribe to `will-redirect` to get that information

🔗 https://electronjs.org/docs/api/web-contents#event-will-redirect

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by zengpeng123** [comment]
This problem still exists in version 6.0.2.

**Comment by goodhyun** [comment]
As @MarshallOfSound advised, `will-redirect` can safely replace `will-navigate ` in a certain situation such as LinkedIn login windows.

**Comment by thisconnect** [comment]
In my case `will-navigate` did not triggering because my create-react-app sample uses `target="_blank"` see also https://github.com/facebook/create-react-app/blob/1a66971f9e2f255d6278ade61e70517faf5839db/packages/cra-template/template/src/App.js#L16

this can be caught with https://electronjs.org/docs/tutorial/security#13-disable-or-limit-creation-of-new-windows

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
