### ISSUE TITLE
How to set up an authenticated Socks5 agent on BrowserWindow？

### ISSUE THREAD

**Issue by LingHanChuJian** [electron/electron#14752]
- Output of node_modules/.bin/electron --version: v1.8.3
- Operating System (Platform and Version): win10 x64

**Expected Behavior** 
   How to set up an authenticated Socks5 agent on BrowserWindow？
   When I set it on session. setProxy ({proxyRules:'socks5://ip: port'}, () =>{}), there was no trigger on webContents. on ('login', (event, request, authinfo, callback) = >{callback (username, password)) that caused my Socks5 connection to fail.

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
