### ISSUE TITLE
Expose href target value

### ISSUE THREAD

**Issue by uclaitsscott** [electron/electron#14764]
I would like the ability to designate a target on links that I could then event tap to open in an external browser. I don't want all links to open in an external browser, so it makes sense to use the link target.

**Describe the solution you'd like**
Expose the target value on the new window open.

**Describe alternatives you've considered**
Javascript calls that are clunk (url loads, etc) or sending a message to the main.js, however; this becomes burden some when identifying which links open in the app and which in the external browser.

**Additional context**
Don't think there's much to add. Just want to target the internal electron app browser in some cases and the system web browser in other cases.

**Comment by MarshallOfSound** [comment]
@uclaitsscott You can implement this logic yourself and it won't be something Electron can add to core as it wouldn't follow the web spec for `target`.

Example implementation:

```js
const links = document.querySelectorAll('a[target="_electron_external"]');

for (const link of links) {
  link.addEventListener('click', (e) => {
    e.preventDefault();
    shell.openExternal(link.getAttribute('href'));
  })
}
```
