### ISSUE TITLE
MacOS - titleBarStyle 'hiddenInset' doesnt show buttons in 3.0

### ISSUE THREAD

**Issue by abriek** [electron/electron#14767]
Hi, I just upgraded to electron 3.0 and noticed that my applications windows controls are no longer there. I use titlebarStyle: 'hiddenInset' so that I can have the native OS's buttons as my windows controls, and it worked great until I upgraded to 3.0

**Expected Behavior**
The macOS buttons should be shown on the top left like in previous versions

**Actual behavior**
The buttons are not there. Though, if you click where the buttons should be the actions work, and if you fullscreen the application and then take it out of fullscreen the buttons start to show.

**To Reproduce**
By just adding the titleBarStyle option, or use the code below.

```
   this.mainWindow = new BrowserWindow({
      show: false, // .show() once 'ready-to-show'
      backgroundColor: '#fff',
      titleBarStyle: 'hiddenInset',
    });
```

**Comment by MarshallOfSound** [comment]
Duplicate #14570
