### ISSUE TITLE
Electron@3 : BrowserWindow devtools doesn't record js perf profiling

### ISSUE THREAD

**Issue by kwonoj** [electron/electron#14763]
* Output of `node_modules/.bin/electron --version`:
* Operating System (Platform and Version):
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**

**Actual behavior**
maybe related with https://github.com/electron/electron/issues/14687 .

**Electron@2**
![image](https://user-images.githubusercontent.com/1210596/45908644-71732500-bdb2-11e8-922b-9364e9d4c812.png)

**Electron@3**
![image](https://user-images.githubusercontent.com/1210596/45908665-82bc3180-bdb2-11e8-8999-dc46b1e860bc.png)

**To Reproduce**
clone https://github.com/kwonoj/electron-quick-start/pull/2

```
npm install
npm start : run devtools perf recording via 'start profiling and reload page'
npm start3 : same as above
```

**Comment by MarshallOfSound** [comment]
So this works on `2.0`, fails on `3.0` and works on `master`.  These translate to `61` -> `66` -> `67`.

So something broke between 61 and 66 and was fixed for 67 🤔

**Comment by bpasero** [comment]
This is a blocker for VSCode.

**Comment by bpasero** [comment]
**Steps (using Fiddle):**
* run hello world without changes
* open dev tools
* open "Performance" tab
* click the reload action ("Start profiling and reload page")
* wait for reload to finish
* stop profiling
* check the output

**3.0.x**
![image](https://user-images.githubusercontent.com/900690/49806157-45cf5d80-fd57-11e8-8c22-97359c9a1dd2.png)


**2.0.x**
![image](https://user-images.githubusercontent.com/900690/49806125-318b6080-fd57-11e8-9fc5-75b15dd9628c.png)

**Comment by nornagon** [comment]
is https://github.com/electron/electron/pull/14499 potentially related?

**Comment by deepak1556** [comment]
@nornagon nope they aren't related. This issue only happens when you use the `start profiling and reload page` option, which confirms the after effect of plznavigate changes. I have narrowed down the issue, looking into a fix.

**Comment by bpasero** [comment]
This seems to work fine again when I test with Electron 4.

**Comment by sofianguy** [comment]
We are no longer supporting versions older than 4.2.x. Please upgrade to v4 as it is reported as fixed in the above comment.
