### ISSUE TITLE
Unable to spawn electron as node's child process

### ISSUE THREAD

**Issue by maple3142** [electron/electron#14775]
* Output of `node_modules/.bin/electron --version`: v3.0.0
* Operating System (Platform and Version): Windows 10 x64 version 1803
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
Able to start electron as a node child process as usual.

**Actual behavior**
Using `child_process.spawn` to spawn a electron process, but `require('electron')` in the child process just return a string...

**To Reproduce**

```sh
$ git clone https://github.com/maple3142/polacode.git
$ cd polacode
$ npm i
$ npx electron src/electron.js # success
$ node src/ep.js # This one throws an error
```
**Screenshots**

![image](https://user-images.githubusercontent.com/9370547/45928898-25281080-bf7d-11e8-8e6c-78f647a4eb86.png)

**Additional Information**

**Comment by maple3142** [comment]
I found that the problem was caused by `ELECTRON_RUN_AS_NODE=1`.
The problem was simply solved by removing it.

**Comment by sundowatch** [comment]
`yarn add electron-builder` or `npm install electron-builder` solved my problem.
