### ISSUE TITLE
PDF Viewer Plugin loads documents much more slowly than Chromium

### ISSUE THREAD

**Issue by JonMarbach** [electron/electron#14783]
* Output of `node_modules/.bin/electron --version`: v1.8.8
* Operating System (Platform and Version): Both Windows (8.1) and Linux (RHEL 6, yes 6)
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): n/a

**Expected Behavior**
Electron should have comparable PDF loading performance to Chromium.  

**Actual behavior**
When loading any PDF >~4MB, the Electron PDF viewer stalls for many seconds with the built-in progress bar at ~2%. In my tests with a 4MB file, it takes about 20 seconds before Electron displays the first page of the PDF, then it takes approximately another 20 seconds before it loads the rest of the document. The same file opened in a Chrome tab (served from the same HTTP server application) loads nearly instantaneously. Also, occasionally, Electron will display a "Failed to load PDF Document" message; pressing Reload in that dialog usually reloads the document successfully, but with not much feedback to the user. Note - a very small (~200k) file does not exhibit this issue.

**To Reproduce**
Apologies for not being able to provide a repo, but the following changes ought to be enough to show it: set { webPreferences: { plugins: true; } } when creating the BrowserWindow to make sure the PDF plugin can load. Point the BrowserWindow URL to a locally-served PDF >~4MB. If you need a large-enough PDF file to try, I've used a locally-served copy this file in some of my testing: https://www.iso.org/files/live/sites/isoorg/files/archive/pdf/en/annual_report_2009.pdf

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
