### ISSUE TITLE
Use ungoogled-chromium

### ISSUE THREAD

**Issue by drschwabe** [electron/electron#14784]
From here forth, please base Electron on https://github.com/Eloston/ungoogled-chromium for improved security & privacy.

**Comment by nornagon** [comment]
Is there a specific privacy issue you're concerned about? Electron avoids most Google-related parts of Chromium by virtue of not using most of the `//chrome` directory.

**Comment by drschwabe** [comment]
The specific concern is the (potential) existence of any services or features 'that communicate with Google or weaken privacy' and binaries in the source tree; addressed and removed/replaced as per the ungoogled-chromium's stated goals.

**Comment by nornagon** [comment]
I'm not aware of any such services or features that are in use by Electron. If you have a specific feature you think should be disabled in Electron, we're happy to consider disabling it.

**Comment by esotericDisciple** [comment]
google-analytics was pinged when I ran any electron-built appimage, until I installed a hostfile from the autohosts github

**Comment by nornagon** [comment]
@esotericDisciple is that coming from your app or from Electron Builder? Electron doesn't include any GA code.

**Comment by esotericDisciple** [comment]
Um...I don't have any apps, I first found this happening in Storyboarder and that was on a desktop pc that's broken and since I haven't used Wireshark since, I don't recall how I found it...However for the Electron Builder tangent...is there any calls to remote repos like from node.js? I wouldn't be surprised if GA pops up that way during a npm build/install/etc task since GA is pretty much lurking on all websites...

**Comment by nileshtrivedi** [comment]
@neurodiverseEsoteric Were you able to confirm this? If every single ElectronJS-based app is pinging Google due to inclusion of standard chromium and not ungoogled-chromium, that is quite concerning.

**Comment by dhra** [comment]
What about requests to `qjz9zk`domains (9oo91e.qjz9zk)

It's 2024 and we need such a feature for those who care about privacy. 


ungoogled-chromium addresses these issues in the following 
- Remove all remaining background requests to any web services while building and running the browser
- Remove all code specific to Google web services
- Remove all uses of pre-made binaries from the source code, and replace them with user-provided alternatives when possible.
- Disable features that inhibit control and transparency, and add or modify features that promote them (these changes will almost always require manual activation or enabling).
