### ISSUE TITLE
Cannot lanuch app in some window system, seem like confilct with other app

### ISSUE THREAD

**Issue by yzzhuo** [electron/electron#14796]
* electron version: 2.0.8
* Operating System (Platform and Version): window 7

**Expected Behavior**
I use electron and electron-builder to build my app, expect to run successfully in everyone's window system.

**Actual behavior**
I use electron-builder to pack my electron app, but the app cannot launch in some people's window system and without any error dialog or output. 

**To Reproduce**
I cannot find the sure way to reproduce the bug. But in one of my computer(win 7), it can reproduce after I install the ludashi(http://www.ludashi.com). And if i uninstall the ludashi, my electron app can launch successfully.  So it seem like my electron app have a conflict with other app such as ludashi.

**Additional Information**
1. electron 1.8.8 don't have this problem. 
2.  run 'netsh winsock reset' in window system's terminal and restart the computer, and my electron can launch.

**Comment by GreenDou** [comment]
Guess somehow related to #12980 ？

**Comment by huangguahuai** [comment]
has there been a rightful OK Solution ??

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
