### ISSUE TITLE
nativeImage crashes on unsupported image files on windows

### ISSUE THREAD

**Issue by danelkhen** [electron/electron#14798]
* Output of `node_modules/.bin/electron --version`: v3.0.0
* Operating System (Platform and Version): Windows 10 64bit
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v2.0.9

**Expected Behavior**
nativeImage.createFromPath("test.webp") should return an empty image

**Actual behavior**
Entire electron app crashes without exception

**To Reproduce**
https://github.com/danelkhen/nativeimagebug
Clone, and run on windows with electron
```
git clone https://github.com/danelkhen/nativeimagebug.git
cd nativeimagebug
npm install
node_modules\.bin\electron index
```

**Additional Information**
Doesn't happen on v2.0.9

**Comment by dperetti** [comment]
Also, ideally, Electron would support webp natively !

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
