### ISSUE TITLE
"will-download" event has to be fixed

### ISSUE THREAD

**Issue by Evoks** [electron/electron#14799]
* Output of `node_modules/.bin/electron --version`: 2.0.10
* Operating System (Platform and Version): OSX 10.13.6

**Expected Behavior**
"will-download" event has to be fired once the download starts to get the information (name, size, url...) and must care about the `setSavePath(path)` setting even when we have several BrowserWindows opened.

**Actual behavior**
"will-download" event is fired once the user selects the path in the save dialog. If the downloaded file is small and the download is finished before the user confirms the path and an exception `Error: Object has been destroyed` is launch (Object is the DownloadItem passed to the callback). Also, the `setSavePath(path)` method only works when we have one BrowserWindow opened and is broken after.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you've responded, please link to the test case and @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by Evoks** [comment]
Nevermind, it was because a downloadItem that has been destroyed was called in the "will-download" listener. It broke the listener function so the default routine was called...
