### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by chunshan-pro** [electron/electron#14794]
The callback-based version of packager() is deprecated and will be removed in a future major version, please convert to the Promise version or use the nodeify module.

**Comment by MarshallOfSound** [comment]
@chunshan-pro This warning comes from `electron-packager` not `electron`.  Basically you are using the packager API like this.

```js
packager(opts, () => {
  // done
});
```

That style is deprecated, you need to use it like this

```js
packager(opts).then(() => {
  // done
});
```

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
