### ISSUE TITLE
webContents.debugger is not delivering Page.frameAttached, Page.frameDetached, Page.frameStartedLoading (for sub-frames) events

### ISSUE THREAD

**Issue by bughit** [electron/electron#14805]
* Output of `node_modules/.bin/electron --version`: 3.0.0 x86
* Operating System (Platform and Version): win7 sp1 x64

**Expected Behavior**
attached, detached, startedLoading events should be delivered

**Actual behavior**
here's what actually delivered, the attached event is missing and so is startedLoading for the sub-frame

```
[2018-09-25T20:02:31.418Z] devtools event Page.frameStartedLoading:
{ frameId: 'AE709443D55F118A6B17CDB0B3322925' }

[2018-09-25T20:02:31.625Z] devtools event Page.frameNavigated:
{ frame:
   { id: 'AE709443D55F118A6B17CDB0B3322925',
     loaderId: '11D33194653D26CE1AD308A11FBDEA99',
     mimeType: 'text/html',
     securityOrigin: 'file://',
     url: 'file:///C:/tmp/iframe.html' } }

[2018-09-25T20:02:31.676Z] devtools event Page.frameNavigated:
{ frame:
   { id: '60FA5654CBADEF8B5086FB237767B75B',
     loaderId: 'A35667847EFBEB16650E5B42845EE821',
     mimeType: 'text/html',
     name: '',
     parentId: 'AE709443D55F118A6B17CDB0B3322925',
     securityOrigin: 'http://example.org',
     url: 'http://example.org/' } }

[2018-09-25T20:02:31.744Z] devtools event Page.frameStoppedLoading:
{ frameId: '60FA5654CBADEF8B5086FB237767B75B' }

[2018-09-25T20:02:31.745Z] devtools event Page.loadEventFired:
{ timestamp: 192486.846165 }

[2018-09-25T20:02:31.747Z] devtools event Page.frameStoppedLoading:
{ frameId: 'AE709443D55F118A6B17CDB0B3322925' }
```

**To Reproduce**

run the following, adjusting the url

```js
'use strict';

const {app, BrowserWindow} = require('electron'),
      OFFSCREEN = false;

let win;

app.on('ready', () => {

  win = new BrowserWindow({
    width: 1440,
    height: 900,
    useContentSize: true,
    show: !OFFSCREEN,
    webPreferences: {
      nodeIntegration: false,
      partition: 'memory_partition_1',
      offscreen: OFFSCREEN
    },
  });

  const dev = win.webContents.debugger;
  dev.on('message', (event, method, params) => {
    log('devtools event %s:\n%O\n', method, params);
  });
  dev.attach();
  dev.sendCommand('Page.enable');

  win.loadURL('file:///c:/tmp/iframe.html');

});

function log(msg, ...args) {
  console.log(`[${new Date().toISOString()}] ${msg}`, ...args);
}
```

##### `iframe.html`
```html
<iframe src="http://example.org/"></iframe>
```

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
