### ISSUE TITLE
Uninteractable invisible border on full screen no frame for 1-2px around the edge of the monitor

### ISSUE THREAD

**Issue by OllysCoding** [electron/electron#14808]
* Electron Version 2.0.0
* Windows 10, Version 10.0.17134, Build 17134

**Expected Behavior**
When in fullscreen mode with no frame, and a non re-sizeable and non movable BrowserWindow, the DOM should be able to interacted with across the full span of the monitor

**Actual behavior**
There appears to be a 1-2px invisible border which cannot be interacted with, around the area where resizing & moving of a window would normally take place. While chrome dev tools do show this area to be within the DOM, moving your mouse in this area will not register clicks / receive cursor styling, etc.

**To Reproduce**

Create a BrowserWindow as shown:
`new BrowserWindow({frame: false, transparent: true, fullscreen: true, resizable: false, movable: false, thickFrame: false })`

Give the html body styling to change the cursor to another type. 

Moving your mouse right to the edge of your monitor, and the cursor will change back. Event Listeners (I applied these to the full window) also do not work in this area.

**Screenshots**
Cursor, near the top of my monitor: 
![image](https://user-images.githubusercontent.com/9575458/46046531-52a9c100-c119-11e8-93d2-7cd2170748af.png)

Cursor, on the top of my monitor:
![image](https://user-images.githubusercontent.com/9575458/46046545-5ccbbf80-c119-11e8-8662-f79d6af7bdce.png)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
