### ISSUE TITLE
onBeforeSendHeaders is not triggerd for custom protocols

### ISSUE THREAD

**Issue by Gozala** [electron/electron#14804]
* Output of `node_modules/.bin/electron --version`:
v2.0.0
* Operating System (Platform and Version):
macOS High Sierra 10.13.6

**Expected Behavior**

[`webRequest.onBeforeSendHeaders`](https://electronjs.org/docs/api/web-request#webrequestonbeforesendheadersfilter-listener) should be triggered for `fetch` / `xhr` request to a URLs handled by the registered custom [protocol](https://electronjs.org/docs/api/protocol).

**Actual behavior**
[`webRequest.onBeforeSendHeaders`](https://electronjs.org/docs/api/web-request#webrequestonbeforesendheadersfilter-listener) are only triggered for standard protocols (like https / http) but are not for custom registered protocols. 

**To Reproduce**

Here is the link to a branch of [electron-quick-start](https://github.com/electron/electron-quick-start) that illustrates the issue: https://github.com/Gozala/electron-quick-start/tree/web-request-before-headers

```sh
$ git clone git@github.com:Gozala/electron-quick-start.git -b  web-request-before-headers 
$ npm install
$ npm start || electron .
```
**Additional Information**

Window will contain bunch of buttons that trigger `xhr` / `fetch` requests to a custom protocol `bug://` as defined here https://github.com/Gozala/electron-quick-start/blob/web-request-before-headers/protocol.js

`onBeforeSendHeaders` here https://github.com/Gozala/electron-quick-start/blob/web-request-before-headers/web-request.js sets details passed as headers to the request that protocol handler echos back and are displayed below buttons.

Example shows that `onBeforeSendHeaders` is never triggered for custom protocol.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
