### ISSUE TITLE
Override CmdOrCtrl+V to pasteAndMatchStyle role

### ISSUE THREAD

**Issue by jasontlouro** [electron/electron#14802]
* Output of `node_modules/.bin/electron --version`: v2.0.5
* Operating System (Platform and Version): macOS Sierra 10.12.6
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v2.0.5

**Expected Behavior**
Creating a MenuItem from the template below should override CmdOrCtrl+V to cause a Paste and Match Style.

{ role: 'pasteAndMatchStyle',
		        	  accelerator: 'CmdOrCtrl+V'},

**Actual behavior**
On Mac, this works as expected. When tested on Windows, it does a normal paste instead of a paste and match style.

**To Reproduce**
On a Windows machine, add the above MenuItem to the Menu and run it.

**Comment by codebytere** [comment]
@jasontlouro does this happen on `3-0-x` as well?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by jasontlouro** [comment]
Sorry for the late reply. But I'm now running v4.0.0 and it still fails to work as expected on windows.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
