### ISSUE TITLE
[macOS Mojave] getUserMedia fails during development

### ISSUE THREAD

**Issue by GU5TAF** [electron/electron#14801]
* Output of `node_modules/.bin/electron --version`: v3.0.0
* Operating System (Platform and Version): macOS Mojave (10.14)

**Expected Behavior**
For `getUserMedia({ video: true })` to work in electron on macOS Mojave.

**Actual behavior**
`DOMException: Could not start video source`

**To Reproduce**
https://github.com/GU5TAF/electron-quick-start/tree/get-user-media

```sh
$ git clone git@github.com:GU5TAF/electron-quick-start.git -b get-user-media
$ yarn
$ yarn start
```

**Additional Information**
I believe this is due to the new camera permissions introduced in macOS mojave.
As described in https://github.com/electron-userland/electron-forge/issues/577 the applications fails to load the camera during development but works fine when packaged. When packaged the permission dialog comes up as expected.

**Comment by GU5TAF** [comment]
After some more testing I've found that starting electron the following way works as expected:
`open node_modules/electron/dist/Electron.app --args $PWD`
Instead of the usual `electron .`

**Comment by paulius005** [comment]
Could this possibly be because the terminal app might not have camera or mic permissions, too bad one cannot add camera and mic permissions explicitly under System Preferences :(. It seems that `getUserMedia` does not  reliably ask for mic and camera settings when the app is built either. Trying to find a better solution so we can get stdout and proper debugging while in development.

Thankfully we have a native swift binary to ask for permissions via https://developer.apple.com/documentation/avfoundation/cameras_and_media_capture/requesting_authorization_for_media_capture

However, that also does not work in development either, just ends up crashing the binary.

Will update here as I find more

**Comment by harrysoer** [comment]
I tried @paulinaika suggestion and it works. Though, is this still an electron issue or is it with iTerm?

**Comment by codebytere** [comment]
This issue is best addressed on the user side, given that it's a development-only issue predicated on access of the command line application (terminal vs iTerm) to system preferences.

**Comment by ltfschoen** [comment]
I was encountering the same error that was triggering the catch block here https://github.com/paritytech/fether/blob/master/packages/fether-react/src/Scanner/Scanner.js#L55 when using `getUserMedia({ video: true })` on macOS Mojave 10.14 in Parity's Fether product and created an issue here https://github.com/paritytech/fether/issues/466.

I would only get the `DOMException: Could not start video source` error when running the Electron app in development, but not in production.

I am using Electron version 4.

**SOLUTION** was to follow the suggestion provided by @paulius005, which involved opening System Preferences with `open /Applications/System\ Preferences.app/`, clicking the "Privacy" tab, then scrolling down and choosing "Camera" from the list, it then shows "Allow the apps below to access your camera.". I noticed that the "Terminal" app was unchecked, so I checked the checkbox.
Then when I started the Electron app by running `yarn electron` from the Terminal, the webcam worked

Note: Initially I tried the approach that @GU5TAF suggested, but it **didn't work**. It involved me modifying the "electron" script in packages/fether-electron/package.json as follows `"electron": "./scripts/startElectron.sh",`, so when I ran `yarn electron` it instead ran the startElectron.sh script, and added the following to startElectron.sh:
```
#!/usr/bin/env bash

FILE='../../node_modules/electron/dist/Electron.app/Contents/MacOS/Electron'
case "$OSTYPE" in
  darwin*)  cross-env SKIP_PREFLIGHT_CHECK=true $FILE dist/main/main.js ;;
  *)        cross-env SKIP_PREFLIGHT_CHECK=true electron dist/main/main.js ;;
esac
```

**Comment by saifeiLee** [comment]
> After some more testing I've found that starting electron the following way works as expected:
> `open node_modules/electron/dist/Electron.app --args $PWD`
> Instead of the usual `electron .`

Could anyone explain to me why it works?

**Comment by saifeiLee** [comment]
> > After some more testing I've found that starting electron the following way works as expected:
> > `open node_modules/electron/dist/Electron.app --args $PWD`
> > Instead of the usual `electron .`
> 
> Could anyone please explain to me why it works?

I find another **solution**: 
1. Open **iTerm** or **Terminal**
2. cd to your project dir
3. run your project. (As for me: **yarn dev**)

And you will see a prompt for requesting access from iTerm or Terminal. Problem solved.

It is really weird.

**Comment by wbcs** [comment]
> > > After some more testing I've found that starting electron the following way works as expected:
> > > `open node_modules/electron/dist/Electron.app --args $PWD`
> > > Instead of the usual `electron .`
> > 
> > 
> > Could anyone please explain to me why it works?
> 
> I find another **solution**:
> 
> 1. Open **iTerm** or **Terminal**
> 2. cd to your project dir
> 3. run your project. (As for me: **yarn dev**)
> 
> And you will see a prompt for requesting access from iTerm or Terminal. Problem solved.
> 
> It is really weird.

It seems that the zsh within VSCode doesn't have access to the camera. Use the native terminal.

**Comment by 2xAA** [comment]
> It seems that the zsh within VSCode doesn't have access to the camera. Use the native terminal.

Surely this can't be the only solution here?
Having to switch out to the Terminal just for one Electron-based project kinda sucks and breaks workflow a lot.

**Comment by 2xAA** [comment]
You can manually enter Camera and Microphone permissions for VSCode (and any other app if you find the identifier) following these instructions, no more default Terminal.

https://github.com/microsoft/vscode/issues/95062#issuecomment-751241372
