### ISSUE TITLE
Shortcut triggers on pressing first and last keyboard button

### ISSUE THREAD

**Issue by SilencerWeb** [electron/electron#14818]
* Output of `node_modules/.bin/electron --version`: v3.0.0
* Operating System (Platform and Version): macOS 10.13.6

**Expected Behavior**
Shortcut should be triggered **only** on CMD or CTRL + C + D

**Actual behavior**
Shortcut triggers when you press CMD or CTRL + D

**To Reproduce**
https://github.com/SilencerWeb/electron-shortcuts-bug

```sh
$ git clone https://github.com/SilencerWeb/electron-shortcuts-bug
$ npm install
$ npm start || electron .
```

**Comment by codebytere** [comment]
We documented this incorrectly, our keycode registration logic has only ever been set up to accept a single key code. I've opened a PR to clarify this.

**Comment by SilencerWeb** [comment]
@codebytere so there is no chance to create a global shortcut like `CmdOrCtrl+C+D`, only `CmdOrCtrl+C` or `CmdOrCtrl+D`?
