### ISSUE TITLE
【Question】JS Object Property is changed unexpectedly

### ISSUE THREAD

**Issue by SamXChen** [electron/electron#14817]
* Output of `node_modules/.bin/electron --version`:  1.4.15
* Operating System (Platform and Version):  win10 x64

**Expected Behavior**
Reload Window while app is running. In main process, Object.name is not changed unexptectedly.

**Actual behavior**
Reload Window while app is running. In main process, Object.name is changed unexptectedly.

**To Reproduce**
1、start electron normally
2、open devTools of the window
3、reload window with 'F5'
4、Object.name in the main process is changed to 'Error'

**Screenshots**

code in main process:
![image](https://user-images.githubusercontent.com/17335236/46069244-ae258e80-c1ad-11e8-97fd-81590e22cefc.png)

behavior （after reload window）:
![image](https://user-images.githubusercontent.com/17335236/46069203-93ebb080-c1ad-11e8-9756-0b6dbeb0898d.png)

plus:
If I try to do Object.defineProperty once app is started, Object will not be changed unexpectedly. And there is no error in main process.
```
Object.defineProperty(Object, 'name', {
  configurable: false,
  writable: false,
  value: 'Object'
});
```

**Additional Information**
Question: Is there any situation in main process would change Object.name globally?

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
