### ISSUE TITLE
Rebuild Native Module Failed On 4.0.0-nightly.20180821

### ISSUE THREAD

**Issue by luckywur** [electron/electron#14828]
* Output of `node_modules/.bin/electron --version`:
  $ node_modules/.bin/electron --version
  v4.0.0-nightly.20180821

* Operating System (Platform and Version):
  Win7 x64
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
I use `HOME=~/.electron-gyp node-gyp rebuild --target=4.0.0-nightly.20180821 --arch=x64 --dist-url="https://atom.io/download/electron"` rebuild native modules

**Actual behavior**
the task download `node.lib`, not `iojs.lib`, rebuild failed

Output:
```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.10.0 | win32 | x64
gyp http GET https://atom.io/download/electron/v4.0.0-nightly.20180821/node-v4.0.0-nightly.20180821.tar.gz
gyp http 200 https://atom.io/download/electron/v4.0.0-nightly.20180821/node-v4.0.0-nightly.20180821.tar.gz
gyp http GET https://atom.io/download/electron/v4.0.0-nightly.20180821/SHASUMS256.txt
gyp http GET https://atom.io/download/electron/v4.0.0-nightly.20180821/win-x86/node.lib
gyp http GET https://atom.io/download/electron/v4.0.0-nightly.20180821/win-x64/node.lib
gyp http 200 https://atom.io/download/electron/v4.0.0-nightly.20180821/SHASUMS256.txt
gyp http 404 https://atom.io/download/electron/v4.0.0-nightly.20180821/win-x64/node.lib
gyp WARN install got an error, rolling back install
gyp http 404 https://atom.io/download/electron/v4.0.0-nightly.20180821/win-x86/node.lib

```

**Comment by MarshallOfSound** [comment]
This is due to how `node-gyp` chooses between iojs and node for the filename.  `>=4` it uses `node` 👍
