### ISSUE TITLE
Electron BrowserWindow crashes when run within a child process on Linux.

### ISSUE THREAD

**Issue by icirellik** [electron/electron#14821]
* Output of `node_modules/.bin/electron --version`:
$ node_modules/.bin/electron --version
v2.0.9

* Operating System (Platform and Version):

Ubuntu 16.04

* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

N/a

**Expected Behavior**

I expect an Electron BrowserWindow to display when being run from a child process with `ipc` as the fourth io channel and then attempting to load a native module.

**Actual behavior**

The BrowserWindow crashes and creates a minidump.

Output:

```sh
$ npm run fails-linux-only

> failure-test@1.0.0 fails-linux-only /home/code/failure-test
> ELECTRON_ENABLE_STACK_DUMPING=1 node src/index.js

Failed to connect to socket /var/run/user/1000/bus: No such file or directory
Received signal 6
#0 0x00000289cf77 (/home/code/failure-test/node_modules/electron/dist/electron+0x269cf76)
#1 0x00000289cb21 (/home/code/failure-test/node_modules/electron/dist/electron+0x269cb20)
#2 0x7ff53557e390 (/lib/x86_64-linux-gnu/libpthread-2.23.so+0x1138f)
#3 0x7ff52ea1c428 (/lib/x86_64-linux-gnu/libc-2.23.so+0x35427)
#4 0x7ff52ea1e02a (/lib/x86_64-linux-gnu/libc-2.23.so+0x37029)
#5 0x7ff536985f7d (/home/code/failure-test/node_modules/electron/dist/libnode.so+0x11fbf7c)
#6 0x7ff51f4d3d14 <unknown>
#7 0x7ff53632bcca (/home/code/failure-test/node_modules/electron/dist/libnode.so+0xba1cc9)
#8 0x7ff53621fd82 (/home/code/failure-test/node_modules/electron/dist/libnode.so+0xa95d81)
#9 0x7ff53621f494 (/home/code/failure-test/node_modules/electron/dist/libnode.so+0xa95493)
#10 0x3e66eb50463d <unknown>
  r8: 00007ffedf5375d8  r9: 00001f4463ea3549 r10: 0000000000000008 r11: 0000000000000206
 r12: 00007ffedf5371b0 r13: 00007ff51f6d52e0 r14: 00007ff51f4d4290 r15: 0000000000000000
  di: 0000000000007f8e  si: 0000000000007f8e  bp: 000000000000000c  bx: 00007ffedf5371af
  dx: 0000000000000006  ax: 0000000000000000  cx: 00007ff52ea1c428  sp: 00007ffedf537068
  ip: 00007ff52ea1c428 efl: 0000000000000206 cgf: 0000000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: fffffffe7ffbfedf cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
electron browser window crashed { preventDefault: [Function: preventDefault],
  sender: 
   WebContents {
     webContents: [Circular],
     history: 
      [ 'file:///home/code/failure-test/src/renderer/index.html#%7B%7D' ],
     currentIndex: 0,
     pendingIndex: -1,
     inPageIndex: -1,
     _events: 
      { 'navigation-entry-commited': [Function],
        'ipc-message': [Function],
        'ipc-message-sync': [Function],
        'pepper-context-menu': [Function],
        'devtools-reload-page': [Function],
        'will-navigate': [Function],
        'did-navigate': [Function],
        destroyed: [Object],
        'devtools-opened': [Function],
        '-new-window': [Function],
        '-web-contents-created': [Function],
        '-add-new-contents': [Function],
        move: [Function],
        activate: [Function],
        'page-title-updated': [Function],
        crashed: [AsyncFunction],
        'dom-ready': [Object],
        'did-finish-load': [Object] },
     _eventsCount: 18,
     _maxListeners: 0,
     browserWindowOptions: { show: false, height: 480, width: 640, webPreferences: [Object] } } }
```

**To Reproduce**

I have created a repository, [electron-renderer-test](https://github.com/icirellik/electron-renderer-test), that minimally reproduces the error. 

```sh
$ git clone git@github.com:icirellik/electron-renderer-test.git
$ npm install
// This command should successfully open a browser window, it doesn't use a child process.
$ npm run success
// This command will fail only on linux systems.
$ npm run fails-linux-only

// If the ipc channel is removed, it will succeed
$ sed -i "s/, 'ipc'//g" src/index.js
$ npm run fails-linux-only

// or if the native module is removed, it will succeed.
$ git reset --hard HEAD
$ sed -i "/'heapdump'/d" src/renderer/index.html
$ npm run fails-linux-only
```

**Additional Information**

The issue only occurs on Linux distributions, the code works as expected on both Windows 10 and macOS 10.13.4.

The error also appears in Docker containers, may be helpful if there is a need to test on another oOS.

**Comment by ckerr** [comment]
FWIW I'm not able to reproduce this running the [electron-renderer-test](https://github.com/icirellik/electron-renderer-test) repro on Ubuntu 18.04.1 LTS x86_64

> Failed to connect to socket /var/run/user/1000/bus: No such file or directory

I also don't see that error message, so that may be a clue (or a red herring).

**Comment by icirellik** [comment]
I spent some time today testing the issue in a VirtualBox VM that I built using the latest Ubuntu 18.04 image and still see the same error.

```sh
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 18.04.1 LTS
Release: 18.04
Codename: bionic
```

The commands I ran in the VM:

```sh
~$ history
1 sudo apt-get update
2 sudo apt-get install -y git python build-essential
3 cd /tmp
4 wget https://nodejs.org/dist/v8.12.0/node-v8.12.0-linux-x64.tar.xz
5 tar -xvf node-v8.12.0-linux-x64.tar.xz 
6 mv node-v8.12.0-linux-x64 node
7 export PATH=$PATH:/tmp/node/bin
8 git clone https://github.com/icirellik/electron-renderer-test
9 cd electron-renderer-test/
10 sudo apt-get install -y libasound2 libgconf-2-4 libgtk-3-0 libgtk2.0-0 libnss3 libxss1 libxtst6
11 npm i
12 npm run fails-linux-only
13 lsb_release -a
```

**Comment by cosoc** [comment]
我也遇到这么一个问题！我是debian9.5  node v10.11.0  npm 6.4.1   electronv3.0.2  但是打开项目窗口一直是卡死状态, 终端没有任何报错信息！ 因为我新手，一头雾水 希望大神给予帮助！我的桌面是：Xfce 4

**Comment by icirellik** [comment]
Is there anything that I can do to gather more information for you? This issue is currently happening on all out Linux systems including out CI infrastructure.

**Comment by nklayman** [comment]
I run into this issue on Ubuntu 18.10 as well.

**Comment by ctunna** [comment]
I'm also experiencing this.

@icirellik provides a good example but this is more minimal

index.js
`var electron = require('electron')
var spawn = require('child_process').spawn

var child = spawn(electron, ['electron-script.js']);
`

electron-script.js
`
const electron = require("electron");

electron.app.on("ready", () => {
    var win = new electron.BrowserWindow({ width: 800, height: 800 });
    win.loadURL("https://wwww.google.com");
});

`

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by ctunna** [comment]
Still experiencing this with electron 6.0.1

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
