### ISSUE TITLE
titleBarStyle: hiddenInset not working in electron 3.0.0

### ISSUE THREAD

**Issue by hellais** [electron/electron#14820]
* Output of `node_modules/.bin/electron --version`: 3.0.0
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2.0.10
* Operating System (Platform and Version): macOS 10.12.6

**Expected Behavior**
When setting the `titleBarStyle` to `hiddenInset` on macOS I would expect it to show the macOS "traffic lights" buttons for closing, minimizing and expanding the window.

**Actual behavior**
The traffic lights are not visible, yet they do respond to clicks when you click on the area corresponding to each of the buttons.

**To Reproduce**
```sh
$ git clone https://github.com/hellais/electron-quick-start.git -b hidden-inset
$ npm install
$ npm start
```

**Screenshots**
![screen shot 2018-09-26 at 17 20 11](https://user-images.githubusercontent.com/424620/46090182-7704ac80-c1b0-11e8-940f-989bd95ac234.png)
![screen shot 2018-09-26 at 17 19 48](https://user-images.githubusercontent.com/424620/46090183-7704ac80-c1b0-11e8-93cc-53f2791db94d.png)

**Comment by MarshallOfSound** [comment]
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

In particular, the OS information is missing from this report

**Comment by hellais** [comment]
This is happening on macOS 10.12.6

**Comment by hellais** [comment]
I also had a person test this on macOS 10.13 and the traffic lights are working as expected there.
