### ISSUE TITLE
Checkboxes don't render in macOS mojave

### ISSUE THREAD

**Issue by Thomas101** [electron/electron#14838]
* Output of 3.0.1 & 2.0.10:
* Operating System (Platform and Version): macOS mojave 10.14

**Expected Behavior**
When using a webview with sandbox enabled in webpreferences and mixed sandboxing across the app enabled, checkboxes and radios should render

**Actual behavior**
Checkboxes are only rendered when not checked. When checked nothing is rendered:
![screen shot 2018-09-27 at 14 32 28](https://user-images.githubusercontent.com/103586/46149478-51d07680-c262-11e8-9923-96cba563fa51.png)

**To Reproduce**
**Key steps to reproduce are:**

Main.js
```js
app.enableMixedSandbox()
```

index.html
```js
<webview src="wv.html" webpreferences="sandbox=yes"></webview>
```
wv.html
```
<input type="checkbox">
```

**Full working example:**
```
git clone https://github.com/wavebox/electron-quick-start.git
cd electron-quick-start
git checkout mojave_checkbox
npm install
npm start
```

**Additional Information**
Looks like Chrome had a similar issue with various hacks and workarounds:

[Upstream issue CR850021](https://bugs.chromium.org/p/chromium/issues/detail?id=850021)

[Google Product forum](https://productforums.google.com/forum/#!topic/chrome/d88Pp5hg35k)

[Workarounds](https://lifehacker.com/how-to-fix-chromes-checkboxes-and-buttons-in-macos-moja-1827398550)

**Comment by MarshallOfSound** [comment]
Backport of https://chromium-review.googlesource.com/c/chromium/src/+/1130163 would fix this
