### ISSUE TITLE
IME got wrong position when focus window with BrowserWindow's api on macOS mojave.

### ISSUE THREAD

**Issue by chairuosen** [electron/electron#14834]
* Output of `node_modules/.bin/electron --version`: tested 1.8.7 2.0.10 3.0.1
* Operating System (Platform and Version):macOS mojave
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): none

**Expected Behavior**
IME got its correct position just behind cursor.
Able to submit words when press enter.

**Actual behavior**
IME shows at left bottom of screen and cannot submit to textarea.

**To Reproduce**

npm install
npm start
app is running. click another app to blur electron app
click Tray icon to focus app
type something with IME ( third party or not )

https://github.com/chairuosen/electron-bug-demo

**Screenshots**
Video: https://www.youtube.com/watch?v=flt6dDR-ApQ

**Additional Information**
tested both BrowserWindow.show() && BrowserWindow.focus()

**Comment by ervinewell** [comment]
I've encountered a similar issue. When I connect an extra display device and type in my main desktop, the IME appears in the extra desktop, as the picture below:
![http://wx1.sinaimg.cn/mw690/628e12e0gy1fvqki7llt6j21400u51ky.jpg](reproduce)

electron: 2.0.9
IME: sogou 48

**Comment by wanhh** [comment]
Are there any organizations or individuals responsible for this bug?

**Comment by dengyaolong** [comment]
My workaround: make a transparent window when app run. When you want to focus your window, you need to focus transparent window first and focus your window again.Then you can input now.

**Comment by www5826** [comment]
hello，i am very interested in your method.can you elaborate? thank you very much @dengyaolong

**Comment by seulgi0711** [comment]
In my case, I use only borwserWindow and have same issue. 

My solution:
1. Hide window to focus first
2. Then show the window.

```js
  tray.on('click', (event) => {
    mainWindow.hide();
    mainWindow.show();
  })
```

I do not know It can solve the problem in case with webview

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by oHaiyang** [comment]
This still exists on electron 4.2.4

**Comment by codebytere** [comment]
This is no longer occurring on latest versions of electron, as seen here:

![ezgif-7-1c7d4e39a449](https://user-images.githubusercontent.com/2036040/72630835-0c790200-3908-11ea-89a5-be2f99f61f0c.gif)

**Comment by codeingforcoffee** [comment]
bump
