### ISSUE TITLE
Problem in displaying the data from database.

### ISSUE THREAD

**Issue by praveen1207** [electron/electron#14836]
I am using Electron to show the values of temperature sensor values stored in MySQL Database.
   I HAVE CREATED A HTML PAGE WITH 

I am not getting how to  "Fetch the value from database and display it in the particulat ID=VALUE".
Which scripting language to use , how to execute a query ,connecting to database..

please need your help as i am new to Electron.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
