### ISSUE TITLE
feat: ES6ify the documentation JS examples

### ISSUE THREAD

**Issue by ckerr** [electron/electron#14842]
Case in point: the [Desktop Capturer](https://electronjs.org/docs/api/desktop-capturer) code snippet uses a `for (... i++)` loop and could use `for ... of` and uses a `Promise` and could use `async/await`

CC @codebytere @sofianguy

**Comment by nctl144** [comment]
Hey folks, is it possible for me to work on this? 😄

**Comment by V1shvesh** [comment]
Hey @ckerr!
May I work upon this issue?

**Comment by aashish-ak** [comment]
@codebytere May i work on this issue??

**Comment by ckerr** [comment]
Hey @V1shvesh, sorry for not responding sooner -- I didn't see your ping until just now.

Yes, anyone including you and @aashish-ak are welcome to work on this. If you are both going to work on it, you may want to coordinate on it so that your work doesn't overlap.

Thank you both for taking a look at this!

**Comment by ntocampos** [comment]
Hey @ckerr, I would like to help on this one! 
I took a look in the docs and saw multiple API Reference sections where the example code can be "es6ified". I'm not sure if I should make a pull-request to each section or group some of them together tho. What do you recommend?

**Comment by ayushpratap** [comment]
Please, can someone verify if this issue is closed or not?
If the work desired is already done then please mark this issue as closed.

**Comment by doc-han** [comment]
looking at the PR #15507 I'm sure the issue is fixed

**Comment by kaustubhdapurkar** [comment]
I am new on GitHub. Can somebody help me get started here? Need a mentor.

**Comment by jatin33** [comment]
Can I work on this issue?

**Comment by abuaesh** [comment]
> I am new on GitHub. Can somebody help me get started here? Need a mentor.

Hey there, welcome to github! Sorry for the late reply, I am as new to github as you are. Even though you may have become an expert by now, here are a few links for everybody's reference: 

Free tutorial on how to use git: https://www.udacity.com/course/version-control-with-git--ud123

Guide to contributing to open source projects: https://codeburst.io/a-step-by-step-guide-to-making-your-first-github-contribution-5302260a2940

**Comment by Dean-Coakley** [comment]
@zcbenz Should this issue be closed? 
Looks like it was completed in: https://github.com/electron/electron/pull/21686

If not, what work remains?
