### ISSUE TITLE
Implement new property appIcon in DesktopCapturerSource object

### ISSUE THREAD

**Issue by CapOM** [electron/electron#14845]
**Is your feature request related to a problem? Please describe.**

To develop a nice UI for an application that allows to select and share other app windows ( using desktopCapturer.getSources ) we would like to also show app windows icons in a graphical/UI picker.

Currently https://electronjs.org/docs/api/structures/desktop-capturer-source only provides window names and thumbnails. While thumbnails are nice in general, there are not great for a graphical picker as a list, for example in front of each window title.
But having app window icons would look much nicer.

**Describe the solution you'd like**

Implement an appIcon property on the electron's DesktopCapturerSource Object.
Also note that most of the work is already available in chromium, see https://chromium.googlesource.com/chromium/src.git/+/master/chrome/browser/media/webrtc/window_icon_util.h and it works on Linux, osx and Win. So what is missing here is some plumbing. 

I have actually a local patch but I wanted to get in touch with electron's maintainers first to check if you are interested of this. If yes I will submit an MR.

**Describe alternatives you've considered**

thumbnail property is not nice when it is the size of an icon so in list of window names.

**Additional context**

Also any usage or change from chromium/src/chrome sub directories should go in electron/chromium_src and not in libchromiumcontent, is that right ?

**Comment by deepak1556** [comment]
@CapOM please do create the PR for adding that feature, sounds like a good enhancement.

> Also any usage or change from chromium/src/chrome sub directories should go in electron/chromium_src and not in libchromiumcontent, is that right ?

Yes for desktop capturer related stuff from chrome it should go in there, also there is https://github.com/electron/electron/pull/14835 which will remove these source copies and move them into patches for easier maintenance. But I am not sure how soon that will get in, worst case I will rebase my work on top of your changes. Thanks!

**Comment by CapOM** [comment]
Hi, thx you both for the positive feedbacks. I submitted a MR, see above. It contains your suggestion about `fetchWindowIcons`. Please take a look, I wonder if DesktopCapturerSource.appIcon should return an empty image (i.e. with size 0x0) or null or undefined. Let me know and I can update the patches.
Thx in advance for the review!

**Comment by aabuhijleh** [comment]
Thanks @CapOM. I'm not familiar with the process, when would be able use this enhancement in a stable electron release?
