### ISSUE TITLE
Electron 3.0.1 app.getAppMetrics() get this warning: 'memory' is deprecated and will be removed.

### ISSUE THREAD

**Issue by samuelcarreira** [electron/electron#14846]
* Output of `node_modules/.bin/electron --version`: 3.0.1
* Operating System (Platform and Version): Windows 10 x64

**Expected Behavior**
According to the docs, the app.getAppMetrics() it's the way to go, to get the memory consumption/cpu usage of all app processes.
https://github.com/electron/electron/blob/master/docs/api/breaking-changes.md#app
On Electron 2.x I didn't get any warnings.

**Actual behavior**
It shows the following warning on the console, each time the function is called:
*'memory' is deprecated and will be removed.*

**To Reproduce**
Simple call the getAppMetrics() function:
```const metrics = app.getAppMetrics();```

**Additional Information**
My main question is what is the correct way to get the memory usage of all processes ( no process.getProcessMemoryInfo() )?

**Comment by codebytere** [comment]
Yes, this is intended behavior as that is being deprecated due to an upstream change in Chromium. We'll work to introduce an alternative way to achieve this in future versions.

**Comment by samuelcarreira** [comment]
@codebytere, thank you. The dev team should change the docs to warn the user about this issue. Here's some example that can be used:

## `app`

```js
// Deprecated
app.getAppMemoryInfo()
// Replace with
app.getAppMetrics()

// Note:
// due to an upstream change in Chromium, the memory property produces a deprecated warning (ignore this warning)
```
