### ISSUE TITLE
electron v3 can't require fsevents

### ISSUE THREAD

**Issue by dariocravero** [electron/electron#14841]
* Output of `node_modules/.bin/electron --version`:
`v3.0.1`

* Operating System (Platform and Version):
`macOS High Sierra 10.13.6 (17G65)`

* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):
`v2.0.10`

**Expected Behavior**
`require('fsevents')` should work.

**Actual behavior**
`require('fsevents')` throws this error:

```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/dario/views/electron-fsevents-issue/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/dario/views/electron-fsevents-issue/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace
```

**To Reproduce**
The simplest way to reproduce it is to install electron and fsevents and try to run electron as node requiring fsevents.

```sh
mkdir electron-fsevents-issue
cd electron-fsevents-issue
npm install --save electron fsevents
ELECTRON_RUN_AS_NODE=true npx electron --require fsevents
```

**Screenshots**
N/A.

**Additional Information**
Running `node --require fsevents` works fine.

**Comment by ChristianKienle** [comment]
Are you aware about the special requirements of modules which use native code?

Quoting the docs:

> There is one important caveat: Native Node.js modules (that is, modules that require compilation of native code before they can be used) will need to be compiled to be used with Electron.

Details:
https://electronjs.org/docs/tutorial/using-native-node-modules

**Comment by dariocravero** [comment]
I am @ChristianKienle, thanks. Even after rebuilding it the issue still persists though. As well as that, it's odd that it would work without any extra effort on electron v2.

**Comment by pronebird** [comment]
Nothing odd. Electron 3 runs node 10 and Electron 2 runs node 8.

**Comment by MarshallOfSound** [comment]
@dariocravero This appears to be a known downstream issue in `fsevents`.  Electron 3 uses node 10 under the hood so this issue appears to be what you are experiencing.

https://github.com/strongloop/fsevents/issues/229
