### ISSUE TITLE
[v3.0.0] Unsupported Time Zone 

### ISSUE THREAD

**Issue by metehanm4** [electron/electron#14856]
* Electron Version: 3.0.0
* Operating System (Platform and Version): Raspbian GNU/Linux 9 ( armv7l GNU/Linux )
* Last known working Electron version: 2.0.3

**Expected Behavior**
No error

**Actual behavior**
Uncaught RangeError: Unsupported time zone specified undefined

**To Reproduce**
Write this lines to any electron app's developer console.Which is running on Raspbian

var date = new Date()
date.toLocaleDateString()

**Additional Information**
It is working on Ubuntu 17.10.

**Comment by MarshallOfSound** [comment]
It looks like this is a known issue in Chrome + Intl

`lighthouse` fixed this by detecting unknown timezones and then defaulting to `en-US`.

https://github.com/GoogleChrome/lighthouse/pull/1067
