### ISSUE TITLE
window.location.href doesnt work for child windows inside webview

### ISSUE THREAD

**Issue by Salmondx** [electron/electron#14860]
* Output of `node_modules/.bin/electron --version`:
v2.0.0
* Operating System (Platform and Version):
Windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):
-
**Expected Behavior**
`child.location.href = 'https://google.com'` should redirect child window content to `https://google.com`

**Actual behavior**
Instead of this child window just closed without any errors.

**To Reproduce**
1) Create a webview element with this settings:
```js
<webview  disablewebsecurity webpreferences="devTools,webSecurity=false,allowRunningInsecureContent=yes,affinity=myAffinity,nativeWindowOpen=yes" allowpopups id="test" style="width:100%; height:100%" src="https://google.com"></webview>
```
2) Open devtools inside `webview` via `document.getElementById('test').openDevTools()` command.
3) Create new child window from the console: 
```js
const child = window.open('https://google.com');
```
4) Try to change window location:
```js
child.location.href = 'https://github.com';
```
5) Child window will be immediately closed without any errors

**Additional Information**
This bug reproduces only with `affinity` and `nativeWindowOpen` flags in webpreferences. Without them `child.location.href` doesnt affect child window at all.

**Comment by MarshallOfSound** [comment]
Merging into #15017
