### ISSUE TITLE
setDownloadSavePath bugs

### ISSUE THREAD

**Issue by tonifds** [electron/electron#14867]
Error: Cannot call function 'setDownloadSavePath' on missing remote object
sometimes when i use the download i get the error in console

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
