### ISSUE TITLE
Add option  { fetchThumbnails: true } to desktopCapturer

### ISSUE THREAD

**Issue by CapOM** [electron/electron#14872]
Related to DesktopCapturerSource.appIcon (https://github.com/electron/electron/issues/14845), if the user only wants the app icons and not the thumbnails the function desktopCapturer.getSources can be optimized and just call webrtc::DesktopCapturer::GetSourceList(&source_list) and so no need the captureFrame() steps.

Indeed when calling desktopCapturer.getSources periodically to check if a window is still available for sharing, then it is unnecessary to capture all the full frames, downscale them and copy them, if the user just want the window titles and the app icons.

**Comment by PixleProgrambetaxl** [comment]
+1

**Comment by CapOM** [comment]
notes: Can disable fetching the thumbnails for the DesktopCapturer.

**Comment by CapOM** [comment]
Everything was merged so closing.
