### ISSUE TITLE
Select tab by index

### ISSUE THREAD

**Issue by mhkeller** [electron/electron#14871]
In native apps and in browsers, you can select the nth open tab by using the <kbd>command</kbd>-<kbd>{number}</kbd> key. It would be nice to be able to do this in Electron apps. I think

Looking at the current API docs there doesn't seem to be any concept of a tab's index, just next and previous. If there is already some way to do this, please let me know!

**Comment by MarshallOfSound** [comment]
@mhkeller Electron has no concept of "tabs", if apps built with Electron have "tabs" they can implement this style of shortcut themselves using menu's and menu-item accelerators.
