### ISSUE TITLE
CPU packaging problem of 龙芯

### ISSUE THREAD

**Issue by Sakyaa** [electron/electron#14874]
How to generate the 龙芯 CPU architecture of the package。
amd64     "linux": "electron-packager . app --platform linux --arch x64 --out=out"；
what should I do？

**Comment by KagamiChan** [comment]
loongson is using mips architecture other than x86/amd64

it will be possible only when chromium and nodejs supports it, and someone is working on porting them

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
