### ISSUE TITLE
'certificate-error' does not handle service worker registration

### ISSUE THREAD

**Issue by phil294** [electron/electron#14885]
* Output of `node_modules/.bin/electron --version`: v3.0.0
* Operating System (Platform and Version): Arch Linux

**Expected Behavior**
With `app.on('certificate-error', ...)`, you can catch all certificate-related errors. I can add an exception for my own certificate here and it is regarded for normal requests, even websocket connection.
Not the case for service workers:

**Actual behavior**
```
An SSL certificate error occurred when fetching the script.
Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID
main.js:1 DOMException: Failed to register a ServiceWorker: An SSL certificate error occurred when fetching the script.
```

**Reproduce**
`navigator.serviceWorker.register('./file')`, where the file is on a host with an invalid certificate. Example:
Add

        <button onclick="navigator.serviceWorker.register('https://expired.badssl.com/hello.js')">register a service worker file on a host with invalid ssl certificate</button>
to index.html and click on it.

The error does not reach the certificate-error handler.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by phil294** [comment]
imo it is a very questionable decision to close and tag a 11 month old issue with "needs-info" when clearly, there is no info needed. But I will re-check the above bug later today

**Comment by phil294** [comment]
Okay, tested it, service worker registration certificate errors still do not reach the handler. It now doesnt even display the error message, only the webpage disappears without any notice (and dev tools are disconnected)

**Comment by gautam-in** [comment]
A better way is to set a custom certificate verification proc. You can do this by calling the following function:
``` js
const { BrowserWindow } = require('electron')
const win = new BrowserWindow()

win.webContents.session.setCertificateVerifyProc((request, callback) => {
  const { hostname } = request
  if (hostname === 'example.com') {
    callback(0); //this means trust this domain
  } else {
    callback(-3); //use chromium's verification result
  }
})
```
For more details read this: https://www.electronjs.org/docs/api/session#sessetcertificateverifyprocproc

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by phil294** [comment]
very funny
