### ISSUE TITLE
Ability to set fullscreen without focusing the window

### ISSUE THREAD

**Issue by SilencerWeb** [electron/electron#14889]
**Is your feature request related to a problem? Please describe.**
Right now there is no way to set fullscreen without focusing the window.

**Describe the solution you'd like**
Ability to set fullscreen without focusing the window. There is a way to show window without focusing it, method calls `showInactive`, would be awesome to have `setFullScreenInactive`

**Describe alternatives you've considered**
Unfortunately, didn't find any. Would be really happy to hear if there is any of them!

P.S. Some of native app can do this (xcode, for example), maybe there is a way to do here too.

**Comment by codebytere** [comment]
This isn't possible with MacOS APIs at present (see [docs](https://developer.apple.com/documentation/appkit/nswindow/1419527-togglefullscreen?language=objc)) but we can certainly revisit it if it becomes available!
