### ISSUE TITLE
BrowserWindow.loadURL() Slow since 3.0.0

### ISSUE THREAD

**Issue by MrAmericanMike** [electron/electron#14886]
* Output of `node_modules/.bin/electron --version`: 3.0.0
* Operating System (Platform and Version): Windows 7 - 64bits
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2.0.10

**Expected Behavior**
Expecting BrowserWindow.loadURL() to load faster

**Actual behavior**
BrowserWindow.loadURL() takes about 3 to 4 times longer to open a window with external URL (from about 2 seconds to 8 seconds)

**To Reproduce**
Install Electron 2.0.10 and use the code provided on the pastebin (See below)
Update to Electron 3.0.0 and compare the results.

The code I'm using:
https://pastebin.com/264XQQRa

**Additional Information**
[Console] 2 npm start on each version
> With Electron 3.0.0
> 
> Sun Sep 30 2018 15:28:54 GMT-0300 (Hora estándar de Argentina) - App ready
> Sun Sep 30 2018 15:29:02 GMT-0300 (Hora estándar de Argentina) - Ready to show
> 
> Sun Sep 30 2018 15:30:13 GMT-0300 (Hora estándar de Argentina) - App ready
> Sun Sep 30 2018 15:30:21 GMT-0300 (Hora estándar de Argentina) - Ready to show
> 
> With Electron 2.0.10
> 
> Sun Sep 30 2018 15:32:36 GMT-0300 (Hora estándar de Argentina) - App ready
> Sun Sep 30 2018 15:32:39 GMT-0300 (Hora estándar de Argentina) - Ready to show
> 
> Sun Sep 30 2018 15:32:57 GMT-0300 (Hora estándar de Argentina) - App ready
> Sun Sep 30 2018 15:32:58 GMT-0300 (Hora estándar de Argentina) - Ready to show

**Comment by MarshallOfSound** [comment]
Merging into #13829
