### ISSUE TITLE
Menu accelerators not working sometimes (Electron 3)

### ISSUE THREAD

**Issue by mhuggins** [electron/electron#14883]
* Output of `node_modules/.bin/electron --version`: v3.0.2
* Operating System (Platform and Version): macOS High Sierra 10.13.3
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2.0.9

**Expected Behavior**
When a menu item has accelerator key(s) associated with it, it **always** works as long as the app/window has focus.

**Actual behavior**
When a menu item has accelerator key(s) associated with it, it **sometimes** works as long as the app/window has focus.

**To Reproduce**
I'm having a hard time isolating this down to a specific subset of conditions, so I haven't created a boilerplate fork demo.  However, this is happening as a part of the [open-location-electron3](https://github.com/nos/client/compare/develop...feat/open-location-electron3) branch of our [nOS](https://github.com/nos/client) application.

```bash
git clone git@github.com:nos/client.git
# alternatively: git clone https://github.com/nos/client.git
git checkout open-location-electron3
yarn install && yarn start
```

1. Create an account
  a. Click the "Create an account" link
  b. Enter "test" for both the password and password confirmation fields
  c. Click the "Register" button
  d. Click the copy icon next to the "Encrypted Key"
2. Login
  a. Paste the copied encrypted key value into the "Encrypted WIF" field
  b. Enter "test" into the "Passphrase" field
  c. Click the "Login" button
3. Press <kbd>Cmd</kbd>+<kbd>T</kbd> (mac) or <kbd>Ctrl</kbd>+<kbd>T</kbd> (win/linux) to open a new tab.
4. Repeat step 3, and eventually opening new tabs will stop working.  You may need to click the mouse into the webview prior to step 3 in order for the issue to reveal itself.

**Screenshots**
N/A

**Additional Information**
The issue seems to be some combination of:

* Electron 3
* Menu accelerator shortcuts
* Webview focus

If, while in that branch, you install `electron@2.0.9`, you will observe that the issue goes away.

**Comment by codebytere** [comment]
i'll look into this!

**Comment by codebytere** [comment]
@mhuggins do you have an example of a minimal reproducible repo for this? It's difficult to address this since it's somewhat app-specific. Perhaps an `electron-quick-start` example?

**Comment by mhuggins** [comment]
@codebytere I tried to come up with a [minimal reproduction](https://github.com/nos/electron-quick-start/commits/webview-accelerators) and couldn't unfortunately.  Essentially what is happening in our app is that when someone presses <kbd>CmdOrCtrl</kbd>+<kbd>T</kbd>, it hides the current webview via CSS (`display: none`), creates a new webview, then calls `webview.focus()` on dom-ready.

One additional step that happens after dom-ready is that a new menu is built via `Menu.setApplicationMenu`, and the old menu is destroyed via `menu.destroy()`.  I'm not convinced that this step pertains to the issue though since, if after the accelerator stops responding, if I click around on other things to change focus, then try the accelerator keys again, it works -- implying the menu bound properly.

I'll take another stab at getting an `electron-quick-start` reproduction that actually mimics the behavior though.

**Comment by cprussin** [comment]
FYI since this appears to be related to key events when a webview has focus, this could be related to or caused by the same underlying issue as a bug I just filed https://github.com/electron/electron/issues/14905, which has a consistent repro case.

**Comment by mhuggins** [comment]
Looks like this might be the cause of #14883, thanks for putting the repro steps together!

**Comment by codebytere** [comment]
Unfortunately, this is intended behavior resultant of migrating the underlying architecture of webviews to `OOPIF`, and won't be possible for us to fix :(

Should it become possible someday, we'll work to implement it!

**Comment by mhuggins** [comment]
@codebytere Is there documentation around this or some kind of workaround in general?

**Comment by mhuggins** [comment]
This seems like a very significant loss of functionality.

**Comment by cprussin** [comment]
Yeah, key events (#14905) are nice but probably can be worked around. But in this case, this seems like the feature is completely broken and unreliable. I don't buy that this could ever be intentional functionality--this is a fundamental bug.

**Comment by asd281533890** [comment]
It can also be reproduced in electron11.5.0, but I solved the problem by calling blur() on all webviews and calling focus on the current webview.
