### ISSUE TITLE
Not able to change openAsHidden to true

### ISSUE THREAD

**Issue by SilencerWeb** [electron/electron#14893]
* Output of `node_modules/.bin/electron --version`: v3.0.2
* Operating System (Platform and Version): macOS High Sierra 10.13.6

**Expected Behavior**
`app.setLoginItemSettings({ openAsHidden: true });` should start app as hidden.

**Actual behavior**
`app.setLoginItemSettings({ openAsHidden: true });` doesn't change value from `false`

**To Reproduce**
In main or renderer run the following code
```js
console.log(app.getLoginItemSettings().openAsHidden); // false
app.setLoginItemSettings({ openAsHidden: true }); 
console.log(app.getLoginItemSettings().openAtLogin); // false
app.setLoginItemSettings({ openAsHidden: false });
console.log(app.getLoginItemSettings().openAtLogin); // false
```

**Additional Information**
I believe it is related to #10880

**Comment by pronebird** [comment]
That whole API is crippled. 🆘

**Comment by codebytere** [comment]
@pronebird @SilencerWeb working on a refactor now!

**Comment by stoneG** [comment]
@SilencerWeb in your example you're logging `openAtLogin`, did you mean to log `openAsHidden`?

**Comment by codebytere** [comment]
@stoneG i think they did, but it was broken either way haha

**Comment by SilencerWeb** [comment]
@stoneG yea, I meant `openAsHidden`, just copied an example from #10880 :)

@codebytere any ideas when we will see a fix? :)
