### ISSUE TITLE
Ampersands used in tray icon tool-tip on Windows platforms looks weird on Taskbar Settings

### ISSUE THREAD

**Issue by LucianZamfira** [electron/electron#14894]
* Output of `node_modules/.bin/electron --version`:  3.0.2
* Operating System (Platform and Version): Windows 10 Pro

**Actual behavior**
The solution for Windows platforms to add tool-tip name that contains ampersands is to escape it like [here](https://github.com/electron/electron/issues/14373): **appTray.setToolTip('A&&&B Application');** and is working, but I found an issue on the "Taskbar settings - Select which icons appear on the taskbar", I get **A&&&B Application** displayed on the list, please see attached screen :(

**Expected Behavior**
Show just **A&B Application**

**Screenshots**
![help-me-final](https://user-images.githubusercontent.com/6073214/46287697-0d0f4d00-c58c-11e8-876e-ab60aba980e5.PNG)

**Comment by MarshallOfSound** [comment]
I believe this is a windows bug, the ampersand handling is done entirely on the OS's side, we've simply documented it.
