### ISSUE TITLE
GN issues to build against latest prod release

### ISSUE THREAD

**Issue by lauracpierre** [electron/electron#14904]
I'm trying to find general guidance on the new build mechanism since Electron 3. 

I have followed the documentation and managed to build Electron just fine, but this is based on the code available on master branch. I tried to build for `3.0.1` though and never managed to go passed the `gclient sync` phase, where this fail while trying to apply patches. 

How can one build against the latest released prod version? I'm guessing this is widely connected to our chromium version we use. 

(Also, I'm in SF, close by the Github office, always happy to sync around that area!)

Thanks!

**Comment by lauracpierre** [comment]
The entire documentation for Electron 3 is about how to use GN though:
macOS: https://electronjs.org/docs/development/build-instructions-macos
and 
general: https://electronjs.org/docs/development/build-instructions-gn

Does this mean we need to keep building the "old" way ?

**Comment by nornagon** [comment]
Those docs are for building `electron@master`. Here are the docs for 3.0: https://github.com/electron/electron/tree/3-0-x/docs/development

**Comment by lauracpierre** [comment]
That worked. Thanks
