### ISSUE TITLE
BrowserWindow.loadURL does not resolve first request for page

### ISSUE THREAD

**Issue by kwonoj** [electron/electron#14908]
* Output of `node_modules/.bin/electron --version`:
* Operating System (Platform and Version): mac OS 
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
When navigate url via `BrowserWindow::loadURL`, initial request sent to server doesn't resolve, while it actually seems resolved by having responses correctly. Maybe due to this reason, couldn't seem some of event is being triggered. We do use one page for triggering remove cookies and vice versa for teardown, and those page does not contain subsequent resource to load ends up with single request pending.

**Actual behavior**
Electron@2
![image](https://user-images.githubusercontent.com/1210596/46320100-a0974c80-c591-11e8-907b-6356303a1097.png)

Electron@3

![image](https://user-images.githubusercontent.com/1210596/46320125-b573e000-c591-11e8-95b3-c4053d0bb9fb.png)

**To Reproduce**
clone https://github.com/kwonoj/electron-quick-start/pull/3

```
npm install
npm start: check network tab
npm run start3: check network tab
```

**Screenshots**

**Additional Information**

**Comment by kwonoj** [comment]
@sofianguy this issue is for electron@3.x.

**Comment by brenca** [comment]
I could repro this on Windows too, gonna take a look at this tomorrow

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
