### ISSUE TITLE
webview no longer emits keyboard events

### ISSUE THREAD

**Issue by cprussin** [electron/electron#14905]
Sorry if this is a duplicate.  I searched and searched and I didn't find something quite the same, but it _is_ similar and probably related to https://github.com/electron/electron/issues/14255 and a few other tickets all reporting broken events (all the tickets I found are different classes of events, none specific to key events) since OOPIF.

I'm also not certain if this is intended behavior with OOPIF.

* Output of `node_modules/.bin/electron --version`: `v3.0.2`
* Operating System (Platform and Version):
```
$ uname -a
Linux lyra 4.18.10-arch1-1-ARCH #1 SMP PREEMPT Wed Sep 26 09:48:22 UTC 2018 x86_64 GNU/Linux
```
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): `v3.0.0-beta.5`

**Expected Behavior**
`keydown` `keypress`, etc events are emitted when a webview is focused.

**Actual behavior**
No such events are emitted.

**To Reproduce**
Please see https://github.com/cprussin/electron-webview-key-event-bug, specifically the commit https://github.com/cprussin/electron-webview-key-event-bug/commit/1cec1ec745331f272b6b3b0ee26446686cc28900.  Clone the repo and run the typical setup commands:

```sh
$ git clone https://github.com/cprussin/electron-webview-key-event-bug.git
$ cd electron-webview-key-event-bug
$ yarn
$ npx electron .
```

Note that when you press any keys, you get an alert indicating what key you pressed.  Then, focus the webview and note that no longer do the alerts show.  Note that there's a key down listener attached to both the webview itself, and the document element of the frame.

**Additional Information**

Everything inside the webview still works properly--e.g., if I add listeners to the document element in a preload script, they are fired properly.

**EDIT**: I did further testing, and I've noticed that the `before-input-event` event on the `webContents` instance for the window containing the webview is also not fired.  Not that this is particularly unexpected, just figured it might be interesting or helpful.

**EDIT 2**: after more testing, this appears to work up to `3.0.0-beta.5`, as with the related bug I linked (https://github.com/electron/electron/issues/14255)  I've updated the header to this ticket accordingly.

**Comment by Levente0xFFFF** [comment]
Hi,

I have the same issue, I have a repo here which demonstrates this: https://github.com/Levente0xFFFF/electron-quick-start

If I write
```
"devDependencies": {
    "electron": "^2.0.0"
  }
```
instead of
```
"devDependencies": {
    "electron": "^3.0.0"
  }
```
then it works fine.
How can I specify `3.0.0-beta.5` as the electron version? What I need to write in the packages.json?

**Comment by codebytere** [comment]
Unfortunately, this is intended behavior with `OOPIF`, and won't be possible for us to fix :(

Should it become possible someday, we'll work to implement it!

**Comment by cprussin** [comment]
@codebytere couldn't this be fixed similar to #14255, by proxying the even through the IPC?

**Comment by Levente0xFFFF** [comment]
@zcbenz what do you think, would it be possible to fix this like the focus event?

**Comment by cprussin** [comment]
Thanks @zcbenz, I appreciate the follow up and link to that issue, it's super helpful.

So does this mean that keyboard accelerators are fundamentally broken in webviews, and there's no plan to fix them?

**Comment by zcbenz** [comment]
Yes, listening to keyboard events from embedder is broken and can not be fixed.

**Comment by mhuggins** [comment]
@codebytere Is there a place to discuss restoring this functionality that would be more appropriate than Github?

**Comment by mhuggins** [comment]
I'm not here to throw away accusations. I respect that the work being done here is done freely and in the developers' own time. And I can understand that things might be prioritized by the needs of the core team focused on electron.

I'm just hoping that there's some room to push back on this just being a lot of functionality, or to find the right medium for discussing.

**Comment by mhuggins** [comment]
Yes, I'm happy to learn and devote time if needed, assuming this is a question of time vs. ability.

**Comment by Nashorn** [comment]
Why can't it be fixed? Theres no explanation at a technical level as though we don't understand it. What happens to games that require keyboard input? What about mouse events? I dont understand.

**Comment by mhuggins** [comment]
The team's silence has already made it clear that they're not interested in new contributors to the project, unfortunately.

**Comment by codebytere** [comment]
This isn't an issue that can be fixed on our end specifically because Chromium now uses out of process iframes (oopifs) as the underlying architecture for its webview tags, and they fundamentally preclude this functionality. We of course welcome new contributors, but this specific issue is genuinely only one that can be fixed upstream in Chromium itself.

**Comment by cprussin** [comment]
I'm guessing it's more a "it's getting lost in the sea of issues and is considered low priority" than active disinterest.  The team has a lot on their hands and few folks to work on it.

I'm get the sense that the goal is to replace webviews with [BrowserView](https://electronjs.org/docs/api/browser-view) which may be part of why we don't get a lot of interest from the development team on this.  I for one have already worked to move all my uses of `webview` over to `BrowserView` instead.

In any case, I'm no expert on these things.  I think that if @zcbenz or @codebytere could weigh in, they are probably far better equipped to provide a perspective than I am.

**Comment by mhuggins** [comment]
> I'm guessing it's more a "it's getting lost in the sea of issues and is considered low priority" than active disinterest. The team has a lot on their hands (and keeping issues up to date is a not-insignificant amount of work) and few folks to work on it.

Yes, this is why I and others were offering to contribute (I count 5 messages worth of conversation around it).  Unfortunately, there was silence from the team in response to an attempt to help give back to electron. 😞

**Comment by hiddentao** [comment]
Just hit this issue myself, am going to see if I can pipe keypresses through the IPC layer.

**Comment by avisk1** [comment]
> Just hit this issue myself, am going to see if I can pipe keypresses through the IPC layer.
> 
> UPDATE: got this working using IPC messages.

@hiddentao could you show how you did?

**Comment by hiddentao** [comment]
@avisk1 

In my [webview preload script](https://github.com/erdDEVcode/sting/blob/master/electron/preload/browserTab.js) I use the [shortcuts](https://www.npmjs.com/package/shortcuts) library as such:

```js
const { ipcRenderer } = require('electron')
const { Shortcuts } = require('shortcuts')

const KEYMAP = {
  reload: 'CmdOrCtrl+R',
}

const shortcuts = new Shortcuts()

Object.entries(KEYMAP).forEach(([task, shortcut]) => {
  shortcuts.add([{
    shortcut,
    handler: () => ipcRenderer.sendToHost('webview-task', { task })
  }])
})
```

Inside my [Webview component](https://github.com/erdDEVcode/sting/blob/master/src/components/browser/WebView.tsx) I listen for it:

```js
  webView.addEventListener('ipc-message', (e: any) => {
    if (e.channel !== 'webview-task') {
      return
    }

    const { task } = e.args[0]

    switch (task) {
      case 'reload': {
        window.location.reload()
      }
      default: {
        break
      }
    }
  })
```
