### ISSUE TITLE
How to enable overlay scrollbar?

### ISSUE THREAD

**Issue by ovo4096** [electron/electron#14901]
* Output of `node_modules/.bin/electron --version`: v2.0.7
* Operating System (Platform and Version): Windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):
v1.6.2

**Expected Behavior**
I just want to enable overlay scrollbar in electron.

**Actual behavior**
Not enable in v2.0.7 of version.

**Additional Information**

My enable code:

```
app.commandLine.appendSwitch('enable-overlay-scrollbar')
```

In `v2.0.7` electron not work, but work in `v1.6.2`.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by ovo4096** [comment]
I think this may be a bug. 
@MarshallOfSound The previous version works fine, but the current version does not.

**Comment by MarshallOfSound** [comment]
@ovo4096 This is not a bug, the command line switch changed.

https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/oDXgVpTvig4

**Comment by ovo4096** [comment]
I'm try to use the code below to enable, but it not work.
```
app.commandLine.appendSwitch('enable-features=OverlayScrollbar')
```
Finally, I use the code below is successfully enabled.

```
new BrowserWindow({webPreferences: { blinkFeatures: 'OverlayScrollbars' }})
```

@MarshallOfSound Any suggestions?

**Comment by warpdesign** [comment]
@ovo4096 I tried your suggestion which appeared to work: the native scrollbars correctly disappear but unfortunately no scroll appear at all, even overlay scrollbar aren't visible.

Any idea?

**Comment by madprops** [comment]
This worked for me: app.commandLine.appendSwitch('--enable-features', 'OverlayScrollbar')

**Comment by sabrehagen** [comment]
This feature has removed as of Chrome 78: https://support.google.com/chrome/thread/14340482?hl=en
