### ISSUE TITLE
Session expired? App doesn't remember logins

### ISSUE THREAD

**Issue by MrAmericanMike** [electron/electron#14910]
* Output of `node_modules/.bin/electron --version`: 2.0.10
* Operating System (Platform and Version): Windows 7 - 64

**Expected Behavior**
When restarting the app, I should be logged.

**Actual behavior**
When restarting the app, my login is missed and I'm asked to login again.

**To Reproduce**
Open a BrowserWindow with any website that requires you to login (Ex: Twitter)
Log into the website.
Close app.
Open the app again and you will be prompted to login once again.

**Additional Information**
Quick example code:
https://pastebin.com/2bZBBwJc

**Comment by MrAmericanMike** [comment]
On a side note, let me add, that the example above, once you click login after entering username and password, the login never happens, and you have to press F5 in order to finally be logged.

I wonder what the problem is there.

**Comment by Anrock** [comment]
Default session object is not persistent, you have to explicitly create persisted session and use it if you want cookies, etc to be stored. See API reference for session

**Comment by MrAmericanMike** [comment]
> 
> 
> Default session object is not persistent, you have to explicitly create persisted session and use it if you want cookies, etc to be stored. See API reference for session

Thanks I will take a look but..... Why was it working before if I wasn't doing anything special? Did something changed?
I believe I'm using the exact same code from when it was working so not sure why now it doesn't anymore.

**Comment by MarshallOfSound** [comment]
@MrAmericanMike Cookies are flushed asynchronously to the file system, if you close immediately after they are set they may not be persisted.  You can manually flush the cookie store to be safe.
