### ISSUE TITLE
Pixelated and distorted sections on the screen

### ISSUE THREAD

**Issue by magneboy** [electron/electron#14921]
* Output of `node_modules/.bin/electron --version`: v3.0.2
* Operating System (Platform and Version): Mostly windows

**Expected Behavior**
A clear view like chromium.

**Actual behavior**
Some areas of the screen get pixelated and distorted (See screenshots below).

**To Reproduce**
Actually this happens randomly on some machines Here are some doubts which can narrow down the possibilities:
1-This does not happen on Computers without graphic cards
2-This does not happen on Linux machines (Which do not have graphic cards)

Our application:
![first-app](https://user-images.githubusercontent.com/40250543/46333465-55327c00-c62d-11e8-8bd0-d49b7d8012ae.png)

Another electron based software(Rocketchat):

![second-app](https://user-images.githubusercontent.com/40250543/46333472-58c60300-c62d-11e8-9278-a397a12635b5.png)

**Comment by magneboy** [comment]
`app.disableHardwareAcceleration(); //Must be used before app.ready`

Solved the problem. Hope it helps somebody.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
