### ISSUE TITLE
Return default request behavior with interceptBufferProtocol

### ISSUE THREAD

**Issue by ChubbyBalboa** [electron/electron#14924]
Hey,

I have a single browser window with two webviews.
I want to intercept the https request of one webview and replace the html content, while leaving the other webview to do it’s default behavior.

Here’s the code i’m currently using to intercept the one webview:

```
protocol.interceptBufferProtocol('https', (req, callback) => {
	if(req.url == 'xxx') {
		callback({mimeType: 'text/html', data: Buffer.from(content)})
	}else{
		// default behavior...
	}
})
```
The intercept is working exactly how I want it, but now the other webview isn’t loading.

How do I return the default behavior of the request?

Thanks

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
