### ISSUE TITLE
a fetch().then(res) response dosn't deliver any headers (even when CORS is set properly); XMLHttpRequest delivers all headers

### ISSUE THREAD

**Issue by sa-ChristianNiessner** [electron/electron#14927]
* Output of `node_modules/.bin/electron --version`:

Electron v3.0.2 (also tested with 3.0.0)

* Operating System (Platform and Version):

Tested on Mac OS X 10.13.6 and Windows Platform (Server 2016 1607)
 
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

Haven't tested it with the 2.x branch...

**Expected Behavior**
We expect to see the (CORS-allowed) response-headers in the `fetch()`-calls `response.headers`.
When doing the same request using the `XMLHttpRequest()` we get all response headers, not only the CORS-allowed ones...

The expected behavior can be seen when opening the testcase on [http://www.test-cors.org/#...](https://www.test-cors.org/#?client_method=POST&client_credentials=false&client_postdata=test&server_enable=true&server_status=200&server_credentials=false&server_methods=POST%2C%20GET&server_expose_headers=X-Cors-Demo-Header%2C%20Content-Length&server_response_headers=X-Cors-Demo-Header%3Atest&server_tabs=local) in the _XHR exposed response headers_ section.

**Actual behavior**
Currently we get no response headers at all for the `fetch()` call and all server-sent headers for the `XMLHttpRequest()` scenario

**To Reproduce**
I've created a testcase in this repository:

https://github.com/secadm/electron-bugs/tree/fetch-showcase

```sh
$ git clone https://github.com/secadm/electron-bugs.git -b fetch-showcase
$ npm install
$ npm start || electron .
```
**Screenshots**
This screenshot shows the output of the testcase. The first marking is the empty `fetch()` response headers, the 2nd are the response headers of the `XMLHttpRequest()`
![testcase](https://user-images.githubusercontent.com/18590466/46356210-8da07d00-c662-11e8-90cc-a6c74c905877.JPG)

This is a screenshot from the `test-cors.org` output showing the response headers as we expect them. 
![expected-behaviour](https://user-images.githubusercontent.com/18590466/46355719-a6f4f980-c661-11e8-81d7-0540b97be3df.JPG)

**Additional Information**
I haven't tried what happens without having CORS involved. So it might be the missing fetch() response headers could be a more generous issue and not CORS related. Whereas the `XMLHttpRequest()` delivers too much response headers and is not following the CORS specification.

**Comment by MarshallOfSound** [comment]
You are making these fetch / HTTP calls from the `file://` protocol which does not follow typical CORS and other origin based security rules.

What origin do you consider the `file://` protocol to be?  It isn't in the CORS spec so can't be followed.

Closing this out as expected behavior, if you want real CORS use a custom protocol or a real / intercepted HTTP connection

**Comment by sa-ChristianNiessner** [comment]
Hi @MarshallOfSound,

okay, the `XMLHttpRequest()` sends the `file://`-Protocol. But for the `fetch()`-API we see `Origin: null` which seems to be the expected behavior according to #7931 . And for my 'real'-App outside this test-case I currently have an real `Origin: https://...` url set and I also get no response headers. So at least for the `fetch()`-Scenario the Origin seems to be irrelevant.

**Comment by MarshallOfSound** [comment]
Can you provide a non-file based repro for the header issue you're describing, if so and it's not consistent with chrome behavior I'm happy to reopen.  Please @ mention me in any follow up.

**Comment by sa-ChristianNiessner** [comment]
Hi @MarshallOfSound,

okay, after doing some further investigations and updating the testcase with an 'external' variant:
* `XMLHttpRequest()` works properly with https://-Origin's.
* also `fetch()` works properly - I was entirely mislead by a fetch-polyfill lib storing all response headers  within the `response.headers` object. I wasn't aware my project included these polyfill. So just dumping the object only works for the polyfill, but is not the 'inteded' API... 

So, i was mislead and not using the API properly. Sorry for bothering you.

As summary:
* `fetch()` shows up the expected headers for local / file `Origin: null` situations and also for `Origin: https://`  origins.
* `XMLHttpRequest()` shows too much headers for `Origin: file://` situations, but works correctly for `Origin https://` origins.

For everyone else: the `response.headers.entries()` iterator is your fried. The headers object doesn't carry any data on Chromium based browsers...
