### ISSUE TITLE
Electron quick start fails to load electron with latest v3.0.0

### ISSUE THREAD

**Issue by RohanAntony** [electron/electron#14936]
* Output of `node_modules/.bin/electron --version`: 3.0.0
* Operating System (Platform and Version): Debian GNU/Linux 9 (stretch)
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): (will check and update)

**Expected Behavior**
Should load the index.html page as per the documentation for getting started with electron.

**Actual behavior**
Shows a transparent application with screenshot of the background. 

**To Reproduce**
- Follow the exact steps for electron-quick-start
You can fork [electron-quick-start](https://github.com/electron/electron-quick-start) and include a link to the branch with your changes.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
**Screenshots**
![electron](https://user-images.githubusercontent.com/5779016/46390072-968d5f00-c6f3-11e8-8098-5ab19052d2bc.png)

**Additional Information**
On an related or unrelated note, `npm install -g electron` fails with even `sudo` during creation of folder '.electron' in the '/usr/lib/node_modules/electron'.

**Comment by RohanAntony** [comment]
Issue is not reproducible with electron v2.0.11. 

![image](https://user-images.githubusercontent.com/5779016/46390341-fa645780-c6f4-11e8-9ca6-d27bb116c9f0.png)

**Comment by pronebird** [comment]
Duplicate issue. See https://github.com/electron/electron/issues/13415 for resolution.

**Comment by codebytere** [comment]
Please instead open this issue on `electron-quick-start`.
