### ISSUE TITLE
The app will pause on focus loss

### ISSUE THREAD

**Issue by AlonikiX** [electron/electron#14935]
Hi, I use Electron to build a real time data stream monitor, and it seems if the window loses focus, javascript will stop working, when it regains the focus, it will start working again. Is there any way to force the app keep updating even without having focus?

I am using MacOS Mojave.

Thanks.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
