### ISSUE TITLE
Common Electron JS runtime 🌟

### ISSUE THREAD

**Issue by karanganesan** [electron/electron#14947]
Just an idea. Looking at how powerful is Electron JS I came to this idea. Being daily using apps like Spotify, Github Desktop, etc. it's been noticed by everyone that they all use separate amounts of RAM on their own since each one run's it's own runtime.

Now why don't we create a common runtime default that act's as master runtime engine so that it can be used by all apps that depend on Electron JS. Like WebViews + Node.JS instance that are connected to a master Electron JS runtime.

Some efforts on just implementing native webviews have been made previously https://github.com/pojala/electrino & https://github.com/jscherer92/Quark (these are the things I found may be more)

So even can use MacOS's WebView /  Windows's ChakraCore + the common NodeJS runtime I earlier mentioned ... are their any thing similar to https://github.com/nodejs/node-chakracore ???

**Comment by Anrock** [comment]
https://github.com/electron/electron/issues/673

**Comment by MarshallOfSound** [comment]
Duplicate #673

**Comment by karanganesan** [comment]
Okay 💯
