### ISSUE TITLE
Electron 3: WebView DevTools integration is broken

### ISSUE THREAD

**Issue by ncortines** [electron/electron#14944]
Hi,

I'm trying to upgrade from Electron 2.0 to Electron 3.0.2.

In my Application I have a BrowserWindow which handles several WebView instances.

Opening DevTools on a WebView instance is possible, but then the actions in DevTools have no influence on the WebView:

- Breakpoints are no fired
- Style changes are not reflected on the DOM

Electron: 3.0.2
Platform: MacOS 10.13.6
Node: 10.10.0

Thanks,
Juan

**Comment by pronebird** [comment]
We've experienced the same on one of Linux installations. On macOS Mojave I can only see hotkeys broken (can't copy/paste) but Edit -> Copy/Paste menu works.

**Comment by JohannBlake** [comment]
> We've experienced the same on one of Linux installations. On macOS Mojave I can only see hotkeys broken (can't copy/paste) but Edit -> Copy/Paste menu works.

Same here but using High Sierra 10.13.6 and Electron 3.0.2

**Comment by 4eveRS** [comment]
I'm seeing the same behavior and many others related to webview, webContents and devTools. I made a bug report explaining some that my application is suffering.

#14716

**Comment by pronebird** [comment]
Fixed in 3.0.4

**Comment by sbeatz** [comment]
no and also not in 3.0.5

**Comment by soundar78** [comment]
Seeing this in 3.0.9 as well, that too in MAS builds alone.
Actions under Edit menu and the Cycle through windows (cmd + `) option are all failing.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
