### ISSUE TITLE
Overly thin font rendering in macOS 10.14 Mojave

### ISSUE THREAD

**Issue by vl4dimir** [electron/electron#14948]
* Output of `node_modules/.bin/electron --version`: 2.0.7
* Operating System (Platform and Version): macOS 10.14 Mojave
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2.0.7 on macOS 10.13 High Sierra

**Expected Behavior**

Font rendering weight should be on par with the rest of the OS.

**Actual behavior**

Fonts are rendered overly thin on Retina (High-DPI) screens.

**To Reproduce**

Download the [latest version of VS Code](https://github.com/Microsoft/vscode/releases/tag/1.27.2), which currently uses Electron 2.0.7. You need to be on macOS 10.14 Mojave and have a Retina screen (Macbook Pro, iMac, etc). Open any file and observe the thickness of fonts in the editor. See below for screenshots.

**Screenshots**

For comparison, I'm providing screenshots of two native macOS apps, Xcode and iTerm, and of VS Code which is using Electron 2.0.7.

Xcode:

<img width="581" alt="rendering xcode" src="https://user-images.githubusercontent.com/206409/46404899-d01b9580-c706-11e8-8af5-52f444bab4dc.png">

iTerm:

<img width="581" alt="rendering iterm" src="https://user-images.githubusercontent.com/206409/46404955-f5100880-c706-11e8-9168-8e4dd563d98d.png">

VS Code (Electron 2.0.7):

<img width="581" alt="rendering vscode" src="https://user-images.githubusercontent.com/206409/46404965-fa6d5300-c706-11e8-8447-97d63979102d.png">

Here's an animated version, for easy comparison:

![rendering animated](https://user-images.githubusercontent.com/206409/46405052-461ffc80-c707-11e8-971e-c8222eddd760.gif)

**Additional Information**

This is an upstream escalation of the issues in both VS Code https://github.com/Microsoft/vscode/issues/59887 and Atom https://github.com/atom/atom/issues/17486 which are both using Electron for font rendering.

The main problem is that Apple removed sub-pixel anti-aliasing in macOS 10.14 Mojave and all Electron apps now seem to be using the "antialiased" (grayscale) setting for font rendering, which is producing very thin and hard to read fonts. I think the "antialiased" setting should be changed to use the native font rendering in Mojave, but I'm not sure if this is something that is doable in Electron or if there's some further upstream repo this should be fixed in. If so, I'd be happy to do it if you point me in the right direction.

**Comment by vl4dimir** [comment]
As mentioned [over at the VS Code issue](https://github.com/Microsoft/vscode/issues/59887#issuecomment-426680580), this seems to be a problem with Skia, the graphics library used by Chromium, Firefox, etc. The Chromium folks have [merged Skia's patch addressing this issue into Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=858861).

I tried out Chrome Canary and the rendering is indeed much better:

Current:
<img width="456" alt="current" src="https://user-images.githubusercontent.com/206409/46421819-4b933c00-c733-11e8-8176-be1ef1cd2bc3.png">

Canary:
<img width="456" alt="canary" src="https://user-images.githubusercontent.com/206409/46421834-55b53a80-c733-11e8-878f-9781102ef588.png">

Animated:
![canary](https://user-images.githubusercontent.com/206409/46421787-30283100-c733-11e8-81a7-279a89e2ea50.gif)

(Screenshot from http://app.programmingfonts.org/)

**Comment by PixleProgrambetaxl** [comment]
+1

**Comment by vl4dimir** [comment]
@codebytere Yes, it's definitely present. I tried with https://github.com/electron/electron-quick-start which uses v3.0.0 and these are the results:

iTerm:
<img width="590" alt="screen shot 2018-10-07 at 2 49 23 pm" src="https://user-images.githubusercontent.com/206409/46584710-d98a6200-ca66-11e8-8801-1309b8390766.png">

Electron v3.0.0:
<img width="618" alt="screen shot 2018-10-07 at 7 28 33 pm" src="https://user-images.githubusercontent.com/206409/46584741-338b2780-ca67-11e8-87ea-553d0af262a5.png">

If you want me to push my exact setup to a repo, let me know. I'm happy to help.

**Comment by codebytere** [comment]
@vl4dimir thanks! i've opened a PR which should fix this issue, and once it's in `master` i'll get it backported to the `2-0-x` and `3-0-x` release lines 😁

**Comment by vl4dimir** [comment]
@codebytere Thank you, that was fast! 👏

**Comment by bpasero** [comment]
VS Code users are still reporting this with Electron4: https://github.com/microsoft/vscode/issues/75380

**Comment by christianhans** [comment]
Electron 5 seems to have the same issue (v5.0.11). Will this fix be backported to the v5 branch as well?
