### ISSUE TITLE
API: `navigator.registerProtocolHandler` does not works.

### ISSUE THREAD

**Issue by Gozala** [electron/electron#14956]
* Output of `node_modules/.bin/electron --version`: v2.0.8
* Operating System (Platform and Version): macOS 10.14

**Expected Behavior**
Page with-in the `<webview>` that registers protocol handler via standard web API [`navigator.registerProtocolHandler`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler) should:

1. Trigger corresponding [permission request handler](https://electronjs.org/docs/api/session#sessetpermissionrequesthandlerhandler) to allow prompting user (which is what all major browsers do).
2. Navigation to URL matching registered protocol should route request as described in the spec, that is extract the `href` from the activated link, combines it with the URL template supplied during handler registration and route to the resulting URL.

**Actual behavior**
1. At the moment page with-in `<webview>` can succesfully registers protocol handler via standard web API [`navigator.registerProtocolHandler`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler) (as long as origin of the page matches origin of the template URL as demanded by SPEC) without triggering [permission request handler](https://electronjs.org/docs/api/session#sessetpermissionrequesthandlerhandler).
2. Navigation to URL matching registered protocol triggers [`openExternal` permission request](https://electronjs.org/docs/api/session#sessetpermissionrequesthandlerhandler) but does nothing regardless if permission was granted / rejected. Supposedly on success delegating call to an OS which does not have corresponding app handler.

I found #4857 issue that was resolved and refers to [`navigator.registerProtocolHandler`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler) but 
I think that issue was about ability to register electron app as an OS level handler for protocol schema addressed by [`app.setAsDefaultProtocolClient`](https://electronjs.org/docs/api/app#appsetasdefaultprotocolclientprotocol-path-args) API, while this is about app level handling as specified by web standard.

**To Reproduce**

I have not created a reproducible example but I'm happy to do so if that would help.

**Comment by PixleProgrambetaxl** [comment]
+1

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
