### ISSUE TITLE
2.0.10 and 2.0.11 not working

### ISSUE THREAD

**Issue by pedro-nonfree** [electron/electron#14954]
* Output of `node_modules/.bin/electron --version`: 2.0.10 or 2.0.11
* Operating System (Platform and Version): Debian GNU/Linux 9.5 (stretch)

**Expected Behavior**

[I should see this](https://github.com/ssbc/patchwork/issues/844#issuecomment-426664276)

**Actual behavior**

[I get that](https://github.com/ssbc/patchwork/issues/844#issuecomment-426661104)

**To Reproduce**

[steps followed](https://github.com/ssbc/patchwork/issues/844#issuecomment-426659900)

**Screenshots**

(same as Actual behavior)

[screenshot](https://github.com/ssbc/patchwork/issues/844#issuecomment-426661104)

**Additional Information**

[Disabling gpu works](https://github.com/ssbc/patchwork/issues/844#issuecomment-426687315), hence, applying argument `--disable-gpu`

My graphical card is

```
 $ lspci -k | grep -A3 VGA
00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 0b)
	Subsystem: Dell Haswell-ULT Integrated Graphics Controller
	Kernel driver in use: i915
	Kernel modules: i915
```

Is strange that is not working with this graphic card that I had no problems with any other application

Electron should provide a common solution found in other applications:

- solving the bug itself (looks related just to electron)
- a fallback disabling gpu automatically (and notifying it in logs)
- catch the error and print in stdout suggesting the user to apply `--disable-gpu`

**Comment by pronebird** [comment]
Same as https://github.com/electron/electron/issues/13415 except now it it happens with Electron v2.0 branch too.

**Comment by pedro-nonfree** [comment]
@anszom you are completely right! Adding what you said makes it work!

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by pedro-nonfree** [comment]
Sorry I thought it was already close
