### ISSUE TITLE
Linux rapid frame rate of streamed electron window

### ISSUE THREAD

**Issue by kempy007** [electron/electron#14957]
* Output of `node_modules/.bin/electron --version`:
[root@localhost server]# node_modules/.bin/electron --version
v2.0.9
& V2.0.11
& V3.0

* Operating System (Platform and Version):
[root@localhost server]# cat /etc/fedora-release
Fedora release 28 (Twenty Eight)
[root@localhost server]# uname -a
Linux localhost.localdomain 4.16.3-301.fc28.x86_64 #1 SMP Mon Apr 23 21:59:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Expected Behavior**
Streamed window plays at normal frame rate.

**Actual behavior**
A clear and concise description of what actually happened.
Streamed windows plays at 2-3 times normal time.

**To Reproduce**
Your best chance of getting this bug looked at quickly is to provide a REPOSITORY that can be cloned and run.
git clone https://github.com/electron/electron-quick-start.git
edit main.js as below;
```
  //mainWindow.loadFile('index.html')
  mainWindow.loadURL('https://youtube.com')
```
npm install
npm start

play a video and watch speed it runs at. (although having done this which did exhibit the issue to start, it has sorted itself out oddly - will restart and see if persists). 

Whens Audio going to work in linux?

**Comment by kempy007** [comment]
Ok I have managed to figure out what affects this. If I disable audio on the VM the content will play at double speed, but if I enable the Audio on the server VM it will play at normal speed. 
How Bizarre, definitely a problem with Audio on Linux.

**Comment by kempy007** [comment]
BTW im using virtualbox for VM

**Comment by PixleProgrambetaxl** [comment]
+1

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
