### ISSUE TITLE
Missing remote objects in 3.0

### ISSUE THREAD

**Issue by jjcm** [electron/electron#14965]
* Output of `node_modules/.bin/electron --version`: 3.0.0
* Operating System (Platform and Version): OSX
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 1.7.9

I have two electron windows. The first one lists a bunch of projects, and if you click on that it pops open a second pane. The second pane shows a preview of a local html file and refreshes if that webpage's local files change. I also have the ability to right click-> inspect element in that second pane. This works fine on both 1.7.9 and on the first time you open the second pane in 3.0.0. 

**Expected Behavior**
I expect the right click -> inspect element to work on subsequent refreshes of the second pane. 

**Actual behavior**
As soon as the second pane refreshes, the `remote.getCurrentWindow().inspectElement(x,y)` call throws a `Attempting to call a function in a renderer window that has been closed or released` error. 

**The code for the second pane**
*preview.js*
```
const {remote} = require('electron')
const {Menu, MenuItem, BrowserWindow} = remote

process.once('loaded', () => {

  // set up right click menu
  const menu = new Menu()
  const menuItem = new MenuItem({
    label: 'Inspect Element',
    click: () => {
      remote.getCurrentWindow().inspectElement(rightClickPosition.x, rightClickPosition.y)
    }
  })
  menu.append(menuItem)
  window.addEventListener('contextmenu', (e) => {
    e.preventDefault()
    rightClickPosition = {x: e.x, y: e.y}
    menu.popup(remote.getCurrentWindow())
  }, false)

  var cmd = false //cmd
  var alt = false //alt
  var i = false //i
  var r = false
  document.addEventListener('keydown', (e) => {
    if (e.keyCode == 91) cmd = true
    if (e.keyCode == 18) alt = true
    if (e.keyCode == 73) i = true
    if (e.keyCode == 82) r = true
    if (cmd && alt && i) {
      remote.getCurrentWindow().toggleDevTools();
    }
    if (cmd && r) {
      remote.getCurrentWindow().reload();
    }
  })
  document.addEventListener('keyup', (e) => {
    if (e.keyCode == 91) cmd = false
    if (e.keyCode == 18) alt = false
    if (e.keyCode == 73) i = false
    if (e.keyCode == 82) r = false
  })
})
```

**The code that triggers the second pane**
```
  viewDirectory: function(dir,dirId) {
    renderer.changeListener(dirId)
    if(renderer.selected) document.getElementById('directory').querySelector('.selected').classList.remove('selected')
    renderer.selected = dirId
    document.getElementById(dirId).classList.add('selected')
    if (!renderer.preview){
      renderer.preview = new BrowserWindow({
        title: 'Bowtie', 
        width: 1200, 
        height: 809, 
        webPreferences: {experimentalFeatures: true, preload: path.join(__dirname, "preview.js")}})
      renderer.preview.setMenu(null)
      renderer.preview.on('closed', () => {
        renderer.preview = null
        renderer.resetSelected()
      })
      renderer.preview.webContents.on('did-finish-load',() => {
        if(renderer.preview.getTitle()=='Bowtie'){
          renderer.preview.setTitle(dir)
        }
      })
    }
    renderer.preview.loadURL("http://localhost:8900/" + dir)
  },
```

**Additional Information**
I believe this is a bug, as I haven't changed anything except the electron version. 1.7.9 works fine. If I'm doing something wrong here though, I'd love some help :)

**Comment by TheGoddessInari** [comment]
I'm also seeing this on Linux with electron 3.0.3. I'm not seeing a way to work around this and have context menu handling generally useful.

**Comment by MarshallOfSound** [comment]
@jjcm Can you provide a minimal repro preferable based off of [electron-quick-start](https://github.com/electron/electron-quick-start).  Without it we can't easily look into this issue.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by jjcm** [comment]
Hey @sofianguy - Sorry been busy. I'll try and get a minimal repo up this week. Can you keep this open for now?

**Comment by jjcm** [comment]
Repo is here: https://github.com/jjcm/electron-preload-bug

After digging further, it looks like it's only in relation to scripts that are preloaded, i.e.

`
 mainWindow = new BrowserWindow({
    width: 800, 
    height: 600, 
    webPreferences: {preload: path.join(__dirname, "preload.js")}
  })
`

If you change the electron version from 3 to 2, the issue goes away.

**Comment by jjcm** [comment]
Vid of the bug in action is here as well: http://files.jjcm.org/inspectBug.mp4

**Comment by jjcm** [comment]
I can confirm this also fails under electron 4.0.0-beta.4

![image](https://user-images.githubusercontent.com/50971/47327923-b690bc80-d6ba-11e8-97d3-ba3703baf939.png)
