### ISSUE TITLE
Cannot find module 'es6-promise' on production build

### ISSUE THREAD

**Issue by ANTVirGEO** [electron/electron#14980]
_package.json:_
```
{
  "name": "test",
  "version": "0.1.0",
  "description": "test",
  "main": "main.js",
  "scripts": {
    "dev": "electron . ",
    "prod": "electron-packager . test --asar --overwrite --all --electron-version=3.0.2 --out=dist --ignore=dist --no-prune . "
  },
  "repository": "",
  "keywords": [
    "Electron",
    "test",
    "Client"
  ],
  "author": "me",
  "license": "CC0-1.0",
  "dependencies": {
    "centrifuge": "^1.4.6",
    "request": "^2.87.0",
    "sockjs-client": "^1.3.0"
  },
  "devDependencies": {
    "copyfiles": "^2.0.0",
    "electron": "^3.0.2",
    "electron-packager": "^12.2.0"
  }
}
```
I have an app, that accepting data from web-socket server - centrifuge.
All working fine in dev, but after build production on windows 10x64 i get this error:

![image](https://user-images.githubusercontent.com/7495603/46526185-be2d2480-c8b7-11e8-9b5f-92e06a52b451.png)

**Expected Behavior**
Working on production like in dev mode)

**Actual behavior**
Critical error 'Cannot find module 'es6-promise''

**To Reproduce**
All is need is require 'centrifuge' module. If delete centrifuge require from main.js - app launching fine after compilling in production.
main.js:
```

const electron = require('electron');
const {app, BrowserWindow, globalShortcut, dialog} = require('electron');
let CentrifugeServer = require("centrifuge");
let sockJS = require('sockjs-client');

let centrifuge = new CentrifugeServer({
  url: 'localhost:8000',
  user: '',
  timestamp: '1510899289',
  token: 'some token',
  sockJS: sockJS
});
centrifuge.connect();
... some code with browserWindow ...
centrifuge.subscribe('client_reset', () => {
        console.log('test');
});
... some other code with browserWindow ...

```
**Question**
Obviously module centrifuge use some es6 promises inside him. Electron 3.+ can't use es6 promises?
Maybe I need to add module 'es6-promises' to project and somehow wrap centrifuge? (I tryed, but just install this module to project don't help me at all )). Or maybe I need complex babel workout?)

Pls, help me, how can I avoid this error and get full working centrifuge module on production build?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
