### ISSUE TITLE
This popup of leaving the page does not showup in electron

### ISSUE THREAD

**Issue by srinathganesh** [electron/electron#14983]
* Output of `node_modules/.bin/electron --version`:
$ electron --version
v2.0.5

* Operating System (Platform and Version):
Ubuntu 18.04.1 LTS  

* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):
N/A

**Expected Behavior**
a page inside an iframe with `window.onbeforeunload = someFunction;` Should show an alert if the page is navigated

**Actual behavior**
Default message of the 'changes have not been saved' is not shown and all navigation stops

**To Reproduce**
Put this link http://jsfiddle.net/hsnoptvb/ in an iframe, then you can never close the electron app

**Screenshots**
**Additional Information**

![image](https://user-images.githubusercontent.com/43715636/46531458-e5d1bc00-c8ba-11e8-82e8-1b3389fb71d7.png)

Using an iframe to render a page, that is generating is popup which is getting skipped and the whole app freezes.

IF you make an electron app with this in iframe http://jsfiddle.net/hsnoptvb/ your app will never close!

**Comment by codebytere** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by srinathganesh** [comment]
> Thanks for reaching out!
> 
> We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

Updated original post with the template.

**Comment by MarshallOfSound** [comment]
See https://github.com/electron/electron/issues/8737

**Comment by MarshallOfSound** [comment]
`onbeforeunload` works differently in electron
