### ISSUE TITLE
Tray.getBounds on Linux

### ISSUE THREAD

**Issue by CodeDraken** [electron/electron#15003]
* Output of `node_modules/.bin/electron --version`: v3.0.2
* Operating System (Platform and Version): Linux, Ubuntu 18

**Expected Behavior**
Expected `tray.getBounds()` to return bounds.

**Actual behavior**
It did not return the correct bounds.
```js
const tray = new Tray(icon)
tray.getBounds()
// { x: 0, y: 0, width: 0, height: 0 } ( incorrect bounds )
```

**Additional Information**
I'm trying to position a window under the tray icon. Is there any way to do this on Linux?

**Comment by codebytere** [comment]
hi @CodeDraken, unfortunately that API hasn't been implemented [on linux](https://github.com/electron/electron/blob/master/docs/api/tray.md#traygetbounds-macos-windows).

**Comment by brunolemos** [comment]
@codebytere maybe leave this open so we can track this? It's a wanted feature so we can have menubar apps on linux.

**Comment by brunolemos** [comment]
@codebytere maybe leave this open so we can track this? It's a wanted feature so we can have menubar apps on linux.

**Comment by felipenmoura** [comment]
Can we somehow get the mouse position when the user clicks the tray icon? We could use that as reference to position the window, perhaps?

**Comment by vigneshwaran-chandrasekaran** [comment]
screen.getCursorScreenPoint() to get screen click cursor pointer and use it instead of tray icon bounds
