### ISSUE TITLE
Global shortcuts not working while a game is in foreground

### ISSUE THREAD

**Issue by gabrielbarbosanascimento** [electron/electron#15013]
Shortcuts are working even if the app is only on the system tray, when a video is in fullscreen mode, but not when a game is on the foreground (which is important for my app, because it uses the media keys to control the sounds)

**Comment by MarshallOfSound** [comment]
@gabrielbarbosanascimento If another application is absorbing / intercepting all keyboard events globally (as some games do) there is nothing we can to receive those key events.

**Comment by gabrielbarbosanascimento** [comment]
So there's nothing I can do?
