### ISSUE TITLE
BrowserWindow positioning is not updated with docked Windows Magnifier

### ISSUE THREAD

**Issue by danailbd** [electron/electron#15018]
* Electron version: 1.8.8 ; 3.0.2
* Operating system: Windows 10
 
 
### Expected behavior
 
When Windows Magnifier is docked to the top of the screen, `BrowserWindow.setPosition(0, 0)` does not position the Electron window over the Magnifier window. The Electron window is instead positioned just below the docked window.
 

![virtualbox_gpii-app_default_1535475662352_85652_04_10_2018_12_48_35](https://user-images.githubusercontent.com/3736954/46605031-cd52e300-cb00-11e8-8c8f-541c18f6372c.png) 

### Actual behavior
 
Interestingly enough when Windows Magnifier’s view state is set to Docked, the screen’s `workAreaSize` is updated correctly (due to the the height of the Magnifier window being subtracted from the screen's height), but the BrowserWindow positioning is not normalized (the 0,0 coordinate overlaps with Magnifier’s window). A subsequent call to `setPosition(0, 0)` places the Electron window under the Magnifier window in the top left corner of the screen. Not only does the top part of the Electron window get partly hidden but it also becomes noninteractive.

![virtualbox_gpii-app_default_1535475662352_85652_04_10_2018_12_45_55](https://user-images.githubusercontent.com/3736954/46605045-d5ab1e00-cb00-11e8-9ff0-a9c21e51794c.png)

### How to reproduce
Simplest steps:
1. Open Windows Magnifier and set view state to Docked
2. Run the Electron app and/or use `setPosition(0,0)` for one of the Electron windows 
```
const electron = require('electron');
const {app, BrowserWindow} = electron;
 
function createWindow () {
  let mainWindow = new BrowserWindow({width: 800, height: 600})
  mainWindow.setPosition(0, 0);
}
 
app.on('ready', createWindow)
```
 
Or through the “display-metrics-changed” event (this is related to my real scenario):
 
1. Open Windows Magnifier and set view state to Lens
2. Run the Electron program:
```
const electron = require('electron');
const {app, BrowserWindow} = electron;
 
function createWindow () {
  // Create the browser window.
  let mainWindow = new BrowserWindow({width: 800, height: 600})
 
  electron.screen.on("display-metrics-changed", () => mainWindow.setPosition(0, 0));
}
 
app.on('ready', createWindow)
```
3. Change Magnifier's view state to Docked
4. The BrowserWindow should be positioned over the Magnifier's docked window

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
