### ISSUE TITLE
ci: "Generate breakpad symbols" fails on linux-*-testing

### ISSUE THREAD

**Issue by Anrock** [electron/electron#15016]
* Output of `node_modules/.bin/electron --version`: PR #12686 

**Expected Behavior**
linux-*-testing ci builds to succeed

**Actual behavior**
All are failed on `Generate breakpad symbols` step.
See logs here:
https://circleci.com/gh/electron/electron/78285?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
https://circleci.com/gh/electron/electron/78286?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
https://circleci.com/gh/electron/electron/78284?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
https://circleci.com/gh/electron/electron/78283?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by Anrock** [comment]
@alexeykuzmin could it be related to your changes in 9d67e021f734432c9f949112c62fc1cd8c1a7abf?

**Comment by MarshallOfSound** [comment]
@Anrock Those builds are passing on master, see the latest master commit.

https://github.com/electron/electron/commit/918488a2f0009ef70a0f86d9e2e504b9dc54676f

Not sure what is happening in your PR but any discussion around failing builds in your PR should happen there, not a separate issue 👍
