### ISSUE TITLE
window.open into a new webview

### ISSUE THREAD

**Issue by Gozala** [electron/electron#15029]
* Output of `node_modules/.bin/electron --version`: v3.0.3
* Operating System (Platform and Version): macOS 10.13.6

**Expected Behavior**
At the moment [`window.open`](https://electronjs.org/docs/api/window-open) documentation illustrates how one could open a popup window when `window.open` is called from with-in the `<webview>` document. It would be very helpful if documentation also illustrated how instead that window could be opened into another `<webview>` to provide browser tab like behavior.

**Actual behavior**
Right now docs do not address how window opened through `window.open` could be loaded into `<webview>` or `<iframe>` or anything other than popup window.

**To Reproduce**
Here is an example that attempt to load window into another `<webview>` without any success.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by Gozala** [comment]
@MarshallOfSound I was hoping that resolving this issue would include documentation update to clearly state whether `window.open` is only supported for popups or not.
