### ISSUE TITLE
macOS: powerMonitor.on('shutdown') is triggered when app is being closed through Dock

### ISSUE THREAD

**Issue by dsabanin** [electron/electron#15022]
* Output of `node_modules/.bin/electron --version`: v3.0.3
* Operating System (Platform and Version): macOS 10.14 (18A389)

**Expected Behavior**
According to [API docs](https://electronjs.org/docs/api/power-monitor#event-shutdown-linux-macos) powerMonitor.on('shutdown') event should be triggered only when the system is about to shut down.

**Actual behavior**
powerMonitor.on('shutdown') event is triggered when I right-click in Dock on the app icon and select Quit or quit the app through the main menu.

**To Reproduce**
Here's the repo to reproduce.

```sh
$ git clone git@github.com:dsabanin/electron-quick-start.git -b master
$ npm install
$ npm start || electron .
```

**Comment by codebytere** [comment]
This is expected behavior, it's considered the standard way to prevent system shutdown on MacOS.

**Comment by dsabanin** [comment]
I'm not sure I understand your response. How is triggering 'shutdown' power monitor event on regular application exit help prevent system shutdown?

**Comment by Slapbox** [comment]
@codebytere, is there any way to distinguish between system showdowns and the user clicking `quit` from the MacOS dock?

In order for me to allow the system shutdown I have to run a quick procedure to manually wrap up operations and quit my app in `powerMonitor.on('shutdown', evt =>`

It seems there's no way to prevent quitting the app when the user clicks `quit` in the dock that won't result in the app preventing a user requested system shutdown. 

Am I overlooking something?
