### ISSUE TITLE
Customize title of Save File dialog

### ISSUE THREAD

**Issue by MatveyNeyman** [electron/electron#15021]
* Output of `node_modules/.bin/electron --version`: v2.0.8
* Operating System (Platform and Version): Windows 10

**Expected Behavior**
Would be nice to have an ability to customize title of Save As dialog that is fired through 'will-download' event.

**Actual behavior**
In order to do it now I should write my own handler of file downloading process where I am able to directly note the title of dialog. On Windows instead of title user sees ugly file url path.

**Comment by codebytere** [comment]
Closed by the above PR.
