### ISSUE TITLE
wrong window size after minimize and restore when setting BrowserWindow's resizable to false

### ISSUE THREAD

**Issue by cao262** [electron/electron#15049]
* Output of `node_modules/.bin/electron --version`: 3.0.3
* Operating System (Platform and Version): windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2.x.x

**Expected Behavior**

mainWindow = new BrowserWindow({ resizable: false })

Minimize and restore main windows by click app icon on the taskbar, the window is getting smaller and smaller.

**Actual behavior**
A clear and concise description of what actually happened.

The main window keeps the same size.

**To Reproduce**
Your best chance of getting this bug looked at quickly is to provide a REPOSITORY that can be cloned and run.

You can fork [electron-quick-start](https://github.com/electron/electron-quick-start) and include a link to the branch with your changes.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone $YOUR_URL -b $BRANCH
$ npm install
$ npm start || electron .
```

It's easy to start from electron-quick-start repo, just add the resizable: false to reproduce it.

**Screenshots**

**Additional Information**

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by pejman1** [comment]
I have same issue, after restoring from minimize the size expands about 10 pixel . 
I set min width and min height and use   getCurrentWindow().minimize();  getCurrentWindow().unmaximize(); functions . 
 if windows was set to min width and min height after recovering from minimize state it expands the size about 10 pixel
