### ISSUE TITLE
"app module app.get/setLoginItemSettings API returns the login item status of the app" fails on MacOS 10.13

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#15041]
"app module app.get/setLoginItemSettings API returns the login item status of the app" test fails on **electron-osx-testing** if we run tests on Microsoft-hosted agents with MacOS 10.13.

A couple of examples:
 - https://github.visualstudio.com/electron/_build/results?buildId=14366&view=ms.vss-test-web.test-result-details&runId=1875&resultId=100021
 - https://github.visualstudio.com/electron/_build/results?buildId=14421&view=ms.vss-test-web.test-result-details

/cc @jkleinsc, @codebytere

**Comment by pronebird** [comment]
Is this any different from https://github.com/electron/electron/issues/10880?

**Comment by MarshallOfSound** [comment]
@pronebird this is tracking our own CI failures / flakes
