### ISSUE TITLE
Generate breakpad symbols step times out on release CI

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#15054]
Example: https://circleci.com/gh/electron/electron/80720
Example: https://circleci.com/gh/electron/electron/81751

**Comment by MarshallOfSound** [comment]
Confirmed not fixed.

New example: https://circleci.com/gh/electron/electron/83416

It's definitely timing out on the dump-symbols script

**Comment by jkleinsc** [comment]
Additional debugging has been added via https://github.com/electron/electron/blob/master/patches/common/chromium/verbose_generate_breakpad_symbols.patch to try to track down this issue.  It also has been backported 4-0-x
