### ISSUE TITLE
Update to Chrome 70

### ISSUE THREAD

**Issue by iclems** [electron/electron#15059]
**Is your feature request related to a problem? Please describe.**
Chrome 70 provides significant WebRTC fixes and improvements. 

**Describe the solution you'd like**
Specifically, enables navigator.getDisplayMedia 

**Describe alternatives you've considered**
desktopCapture allows to build a custom integration, but getDisplayMedia is becoming a standard

**Comment by MarshallOfSound** [comment]
@iclems Hey, we have recently landed the chromium 69 upgrade into master, however, Chromium 70 is not stable yet and our next major release (4.0.0) is being cut imminently, 70 won't a part of that release.

I see you commenting on https://github.com/electron/electron/issues/1380 about this feature, at the moment we have no timeline on a C70 upgrade so I'd suggest you stay with that comment thread regarding `navigator.getDisplayMedia`.

Going to close this out, when we get to the C70 upgrade a tracking PR will be raised and you can follow along there.

**Comment by iclems** [comment]
Thank you @MarshallOfSound - Makes sense. Sad, 70 is going stable in the next 6 days. Great work on 4.0.0 and thanks for the quick feedback!

**Comment by iclems** [comment]
@MarshallOfSound is is worth it re-opening this in the future?

**Comment by MarshallOfSound** [comment]
@iclems We are focusing on stabilizing 4.0 but the C70 upgrade is in PR atm.

**Comment by iclems** [comment]
@MarshallOfSound awesome - i saw this got merged but strangly enough with 4.0.0-beta.9 I'm still getting Chromium 68 apparently. When would 70 make it into the nightly? Thank you and apologies if I missed something here!

**Comment by iclems** [comment]
Just realized beta.9 was apparently cut 2 days before the merge. So I guess I need to wait for beta.10?

**Comment by nornagon** [comment]
We don't upgrade chrome major version after the first beta is cut. Electron 4.0.0 will be released with Chromium 69.0.3497.106.

**Comment by iclems** [comment]
Makes sense. Is it possible to have a nightly that would include it separately? 4.1 beta?

Clément (mobile)

________________________________
De : Jeremy Apthorp <notifications@github.com>
Envoyé : jeudi, décembre 13, 2018 8:36 PM
À : electron/electron
Cc : Clément Wehrung; Mention
Objet : Re: [electron/electron] Update to Chrome 70 (#15059)


We don't upgrade chrome major version after the first beta is cut. Electron 4.0.0 will be released with Chromium 69.0.3497.106.

**Comment by nornagon** [comment]
No, we only upgrade major chrome versions with major electron versions. The next version to include an upgrade of Chromium will be Electron 5. See https://electronjs.org/docs/tutorial/electron-versioning#semver
