### ISSUE TITLE
making a transparent window ignoremouse but on the edges it should be able to clicked

### ISSUE THREAD

**Issue by kepi0809** [electron/electron#15050]
Hey, I could make this happen on osx but on windows for some reason not (mostly windows users are going to use the app).

So one of my browserwindows is only an html file with a red outline on body and padding on both html and body. On mac I could make it work with: .setIgnoreMouseEvents(true, {forward: true}) (on windows even if I set it to false, it will still ignore mouseevents 

Only alternative I see is controlling the browserwindow from the "main app" 

So I guess a transparent window on windows ignores basically mouseevents. 

Summary: I would like to do a browserwindow that is frameless, transparent and still draggable... 

Thanks in advance! ;)

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).

**Comment by kepi0809** [comment]
it can be both bug and feature request though. but let's say feature request -> implementing the windows os version of `win.setIgnoreMouseEvents(ignore[, options])` options part
