### ISSUE TITLE
3.0.3 webContents.print in windows 10 is creating files and only working once

### ISSUE THREAD

**Issue by jenst44** [electron/electron#15064]
* Output of `node_modules/.bin/electron --version`:
* Operating System (Platform and Version):
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
win.webContents.print() to be able to print multiple times and not create unnecessary files in the process.

**Actual behavior**
A clear and concise description of what actually happened.
When calling win.webContents.print() in windows 10 (behavior not observed on a mac) a .pdf,.ejs.emf and Chinese text file are being created. Printing will work once, then on any further attempt the print function will return success, the job will be added to the printer's queue and then quickly be deleted. I observed this with multiple different printers on a surface pro 5 with windows 10.

**To Reproduce**
Your best chance of getting this bug looked at quickly is to provide a REPOSITORY that can be cloned and run.

You can fork [electron-quick-start](https://github.com/electron/electron-quick-start) and include a link to the branch with your changes.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
ipc.on('convert-hash', function(event, hash){
  var id = hashids.decode(hash)[0];
  if(id) event.sender.send('hash-decode', id);
})

var badge_win;

ipc.on('print-to-pdf', function(event, data){

  if(!data.role){
    data.role = "";
  }

  if(badge_win && badge_win.close){
    try{
      badge_win.close();
    } catch(e){

    }
  }

  badge_win = new BrowserWindow({width: 1038, height: 1650, show: false});

  ejse.data(data);
  
  badge_win.loadURL(url.format({
    pathname: path.join(__dirname, 'print/index.ejs'),
    protocol: 'file:',
    slashes: true
  }));
})

ipc.on('print-away', function(){
  badge_win.webContents.print({slient:true});
})
```
**Screenshots**

**Additional Information**
NOTE: I was able to switch to 2.0.11 and have this entire process work without a problem.

**Comment by tlt254** [comment]
i have the same problem

**Comment by MarshallOfSound** [comment]
Duplicate #15036
