### ISSUE TITLE
Quickstart error:  /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available

### ISSUE THREAD

**Issue by ArThoX** [electron/electron#15069]
**Output of `node_modules/.bin/electron --version`:** 

 node_modules/.bin/electron --version
/home/ubuntu/workspace/electron-quick-start/node_modules/electron/dist/electron: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /home/ubuntu/workspace/electron-quick-start/node_modules/electron/dist/electron)
/home/ubuntu/workspace/electron-quick-start/node_modules/electron/dist/electron: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /home/ubuntu/workspace/electron-quick-start/node_modules/electron/dist/electron)

**Operating System (Platform and Version):**
Ubuntu 14, using ide.c9.io.

**Expected Behavior**
No error.

**Actual behavior**
"node_modules/.bin/electron --version" returns an error.
The same error is encountered at "npm run start".

**To Reproduce**
If you have a free account on ide.c9.io create a node ubuntu instance.
Get "https://github.com/electron/electron-quick-start" and try to run it.

**Additional Information**
node -v
v10.11.0

lsb_release -a 
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

**Comment by MarshallOfSound** [comment]
Electron requires a desktop environment, you can't run it headless on a cloud IDE machine

**Comment by ArThoX** [comment]
@MarshallOfSound Thanks. I am new to electron and I didn't know that.

I know this is not the right place for questions but could you please quickly explain why cannot the build&test phase be done on a "headless" env ?

**Comment by MarshallOfSound** [comment]
@ArThoX You could build your app headless, but you can't launch Electron without a GUI environment.  You can do things on linux like install `xvfb` and the then the required X11 dependencies but I wouldn't recommend it for development, you won't be able to see what you're doing 🤔

**Comment by tylercollier** [comment]
I am getting the same errors, except I have a non-cloud machine. My desktop is Ubuntu 14.04.5 and I have node 10.11.0. Any ideas?

**Comment by alexkohler** [comment]
I am also running into this issue on Ubuntu 14.04.

**Comment by bpasero** [comment]
I am still getting this, opened: https://github.com/electron/electron/issues/16364

**Comment by tylercollier** [comment]
A couple months ago when I posted here and I said no electron app is shown, I was using the then-current electron-react-boilerplate. I changed to electron-webpack-quick-start, and though I still saw warnings in the console, I saw an electron window so I was willing to ignore the console warnings and went on with my life.

I just noticed with the latest Visual Studio Code (version1.31.0, still on Linux 14.04.5), that if I run `code .` from the console, I get the warning: `/usr/share/code/bin/../code: /lib/x86_64-linux-gnu/libdbus-1.so.3: no version information available (required by /usr/share/code/bin/../code)`. If the problem happens with VS Code too, seems like it's probably not some configuration error I've done in my project, but rather something with my system.

**Comment by jacklovepdf** [comment]
> Electron requires a desktop environment, you can't run it headless on a cloud IDE machine

I meet the same problem, but i have install xvfb and start the app by command 'xvfb-run electron .'

**Comment by Lakkanna** [comment]
I was getting same error while building travis cli, i added **os: osx** in .travis.yml now it's building fine.

**Comment by astinaam** [comment]
After installing `chromium-libs` the error was gone.

**Comment by fusion27** [comment]
> After installing `chromium-libs` the error was gone.

@astinaam I'm Googling all over attempting to install `chromium-libs`, I can't figure out how to install it, do you happen to have your install command laying around?

**Comment by VictorSago** [comment]
Same error in Atom, on an Ubuntu 14.0 machine with KDE desktop. Happened during creation of an empty JavaScript file.

**Comment by chenxingshuang** [comment]
> After installing `chromium-libs` the error was gone.
 would you mind telling me the package name of `chromium-libs`?  I find that `apt-get install chromium-libs` goes wrong.
