### ISSUE TITLE
Invalid explanations about `eval()` issues in the docs

### ISSUE THREAD

**Issue by ClementNerma** [electron/electron#15062]
Electron's [Security Tutorial](https://github.com/electron/electron/blob/master/docs/tutorial/security.md) contains a section about [disabling `eval()`](https://github.com/electron/electron/blob/master/docs/tutorial/security.md#7-override-and-disable-eval) to prevent the application from evaluation code that is not known in advance.

The problem of this explanation is that there is another, not blockable way, to evaluate dynamic JavaScript strings:

```js
// The following statement prints: 'Hello world!' in the console
new Function([], 'console.log("Hello world!");')();
```

This makes useless this section in the doc because it is not possible at all to prevent dynamic evaluation of JavaScript (as the `Function` entity is part of the native library and all functions depend on it).

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
