### ISSUE TITLE
is possible outputs something in main process(mac)

### ISSUE THREAD

**Issue by redsparrowWang** [electron/electron#15077]
hello , i have use vscode to develop an electron's nodejs app.
i can use console.log() to outputs something in renderer process(browser console),
but nothing outputs in main process.

run" electron . " in work directory path at terminal, i can see main process outputs in terminal, but i can't see renderer's outputs.

is possible outputs something in main process? and what need to do? 
(outputs to vscode's debug console or browser console)

help pls , thanks

os: mac
electron: using 2.0.9 tried 3.0.9
nodejs: 10.9.0
vscode: 1.28.0

**Comment by Anrock** [comment]
Use `electron-logger` package or [ELECTRON_ENABLE_LOGGING](https://electronjs.org/docs/api/environment-variables)

**Comment by redsparrowWang** [comment]
@Anrock 
hi, thanks for your info.

i tried that
run "export ELECTRON_ENABLE_LOGGING=true" in terminal, not work
and setting " "start": "electron . --enable-logging" in .package.json, not work
did i miss something ?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by redsparrowWang** [comment]
@MarshallOfSound 

sorry, i can't make sure it's not a bug or electron can't do that feature
so, the title wrote like  "is possible outputs something in main process?"
and you close this issues that means you can sure isn't bug of electron?

**Comment by redsparrowWang** [comment]
finally, i find a way can do it, put main process info send to renderer process to show. -_-! using it as temporary solution, hope it can help other people.

![screenshot 2018-10-12 13 53 45](https://user-images.githubusercontent.com/19768895/46848894-63e81280-ce27-11e8-86a6-549d15580d99.png)


@MarshallOfSound 
this issues is not a  request features ?
your https://electronjs.org/community wrote that
>Request features by opening issues on the electron/electron repository.

directly close issues? sucks!
