### ISSUE TITLE
NotificationAction has invalid signature

### ISSUE THREAD

**Issue by pronebird** [electron/electron#15081]
* Output of `node_modules/.bin/electron --version`:
* Operating System (Platform and Version):
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
Electron should align with the standard if it's built on top of it.

**Actual behavior**
Documentation on `NotificationAction` does not match the one on W3C.

1. https://electronjs.org/docs/api/structures/notification-action#notificationaction-object
2. https://notifications.spec.whatwg.org/#dictdef-notificationaction

Except from Electron docs:

```
type String - The type of action, can be button.
text String (optional) - The label for the given action.
```

W3C interface:

```
dictionary NotificationAction {
  required DOMString action;
  required DOMString title;
  USVString icon;
};
```

**To Reproduce**
Your best chance of getting this bug looked at quickly is to provide a REPOSITORY that can be cloned and run.

You can fork [electron-quick-start](https://github.com/electron/electron-quick-start) and include a link to the branch with your changes.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone $YOUR_URL -b $BRANCH
$ npm install
$ npm start || electron .
```
**Screenshots**

**Additional Information**

**Comment by MarshallOfSound** [comment]
@pronebird That `NotificationAction` object is for the main process [`Notification` API](https://electronjs.org/docs/api/notification) and isn't related to the standard HTML5 `Notification` API at all.  We don't change the HTML5 Notification API, we just provide a separate implementation / API for the main process.

**Comment by MarshallOfSound** [comment]
To further the comment above, it's just coincidence that those structures are named the same.  I guess what else would you call actions for notifications 😆
