### ISSUE TITLE
[4.0.0-beta.1] TypeError: statSyncNoException is not a function

### ISSUE THREAD

**Issue by sebakerckhof** [electron/electron#15089]
https://github.com/electron/electron/issues/13388 is back in 4.0.0-beta.1
Either statSyncNoException should be removed from fs, so we can make a workaround, or it should work...

* Output of `node_modules/.bin/electron --version`: 4.0.0-beta.1
* Operating System (Platform and Version): Debian stretch
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):
3.0.4

**Expected Behavior**
fs.statSyncNoException exists and is a function, so it should work.

**Actual behavior**
fs.statSyncNoException throws:
```
TypeError: statSyncNoException is not a function
    at Object.fs.statSyncNoException.pathArgument [as statSyncNoException] (ELECTRON_ASAR.js:298:27)

```

**To Reproduce**
call `fs.statSyncNoException`

**Comment by codebytere** [comment]
hi @sebakerckhof, we no longer support `statSyncNoException` or `lstatSyncNoException`; it's been removed from our fork as you can see [here](https://github.com/electron/node/blob/electron-node-v10.11.0/lib/fs.js). The error you are seeing is expected.

**Comment by sebakerckhof** [comment]
@codebytere Except you didn't remove it here: https://github.com/electron/electron/blob/4-0-x/lib/common/asar.js#L296

Making for example `electron-compile` fail, because this line still evaluates true: https://github.com/electron-userland/electron-compile/blob/master/src/config-parser.js#L18

**Comment by sebakerckhof** [comment]
Ok, I see there's just been a PR for this: https://github.com/electron/electron/pull/15092
