### ISSUE TITLE
Enable v2 sandbox on macOS

### ISSUE THREAD

**Issue by deepak1556** [electron/electron#15080]
Since Chromium 69, the default sandbox design has changed on macOS https://chromium.googlesource.com/chromium/src.git/+/master/sandbox/mac/seatbelt_sandbox_design.md , we couldn't enable it at the moment https://github.com/electron/electron/commit/66623d14598bc3c382d265313f3699f1c87272ec

```
The new v2 sandbox uses system sandbox API, there does not seem to have
a way to support it in --enable-mixed-sandbox, we should probably
deprecate the API.
```

The api is still marked experimental https://github.com/electron/electron/blob/master/docs/api/app.md#appenablemixedsandbox-experimental-macos-windows , lets remove it in favor of `app.enableSandbox` and make sure an app can either be completely sandbox or not.

Also additional work that needs to be done to enable it https://bugs.chromium.org/p/chromium/issues/detail?id=689306

/cc @zcbenz @miniak @nornagon @alexeykuzmin

**Comment by nornagon** [comment]
I'd like to know more about what it is in the v2 sandbox design that prevents mixed sandbox mode. It seems like it should still be possible to launch renderer process with differing sandbox profiles, so perhaps i'm missing something?

**Comment by zcbenz** [comment]
The V2 sandbox started to use macOS sandbox APIs, which seem to require the app bundle to be signed with sandbox entitlements, otherwise Chromium would just crash in `sandbox_init_mac.cc
`:
https://cs.chromium.org/chromium/src/content/common/sandbox_init_mac.cc?type=cs&sq=package:chromium&g=0&l=89-93

**Comment by nornagon** [comment]
this is done :)
