### ISSUE TITLE
Cannot run project on Windows

### ISSUE THREAD

**Issue by Koristo** [electron/electron#15087]
* Output of `node_modules/.bin/electron --version`: 2.0.7
* Operating System (Platform and Version): Windows 10 Pro x64

**Actual behavior**
In screenshoot

**To Reproduce**
Your best chance of getting this bug looked at quickly is to provide a REPOSITORY that can be cloned and run.

You can fork [Desktop client](https://github.com/MoonSHRD/desktop_client/tree/branch-54) and include a link to the branch with your changes.

I build from Ubuntu my project for Windows 10 x64, but when I run exe-file, it gives an error (screenshot). I try build it from electron-builder and electron-packager.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone $YOUR_URL -b $BRANCH
$ npm run yarn_install
$ npm start
$ npm run dist
```
**Screenshots**
![default](https://user-images.githubusercontent.com/39203974/46803838-b5ca6300-cd69-11e8-952b-7185769921b3.jpg)

**Comment by MarshallOfSound** [comment]
@Koristo That error is because you have native node module that wasn't built for widows correctly.  You can't cross-compile native modules, I'd you have them and want to build for windows, you have to be on a windows machine.
