### ISSUE TITLE
flaky test: webContents module takeHeapSnapshot() fails with invalid file path

### ISSUE THREAD

**Issue by brenca** [electron/electron#15095]
* Output of `node_modules/.bin/electron --version`: 4.0.0
* Operating System (Platform and Version): OSX
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
Test should behave consistently.

**Actual behavior**
Test seems to be flaky.

**Additional Information**
Here is the flaked test run:
https://github.com/electron/electron/pull/15023/checks?check_run_id=23183436
And the successful re-run:
https://github.com/electron/electron/pull/15023/checks?check_run_id=23228533

**Comment by nornagon** [comment]
Still flaky :< https://github.visualstudio.com/electron/_build/results?buildId=23199&view=logs

I'm going to disable this test.
