### ISSUE TITLE
More control of Menu.popUp placement

### ISSUE THREAD

**Issue by theshortcut** [electron/electron#15096]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to display a popup menu either above or below a button depending on the location on screen. Example: https://github.com/wulkano/kap/pull/579

There are problems with this approach that I can't figure out how to solve without some changes to electron.

**Describe the solution you'd like**
This could be handled better at the application level if either:

- Menu popup direction was configurable
  - could enforce opening upwards or downwards on our own based on positioning
- Menu size was available
  - could manually position the popup to show above the element if we knew the height of the menu

**Describe alternatives you've considered**
Perhaps another option would be for `Menu.popUp` to return the direction (`up` or `down`) that the menu is displaying.

**Additional context**
Example UI:
![image](https://user-images.githubusercontent.com/2533/46838959-78b59f00-cd70-11e8-86f6-4231879a3352.png)

**Comment by MarshallOfSound** [comment]
@theshortcut You can already do this with `positioningItem`, in your example above if you provide an `x` and `y` coordinate along for the triple-dot menu in your UI and a ` positioningItem` of 4 you should get the UI you want 👍 

`pi == 4` would put the bottom of the menu at the given coordinates
`pi == -1` (the defaults) puts the top left of the menu at the given coordinates

**Comment by MarshallOfSound** [comment]
https://electronjs.org/docs/api/menu#menupopupoptions

**Comment by sindresorhus** [comment]
@MarshallOfSound That will highlight the item though. What we want is to force the position of the menu without highlighting any particular item.

Notice how the first item is highlighted (My mouse was over the `...` menu):

<img width="248" alt="screen shot 2018-10-16 at 01 15 57" src="https://user-images.githubusercontent.com/170270/46969693-17c7f700-d0e1-11e8-910c-d12ed6798c13.png">
