### ISSUE TITLE
Open two colleagues webview , session.defaultSession Cannot be executed correctly

### ISSUE THREAD

**Issue by loveburning** [electron/electron#15100]
* Output of `node_modules/.bin/electron --version`:2.0.4
* Operating System (Platform and Version):mac

**Expected Behavior**
session.defaultSession.webRequest.onCompleted     Listen to the request
Open two colleagues webview 
**Actual behavior**
Load the good for the first time webview  No normal grab the request, The second load is normal

**To Reproduce**
```sh
Metas.filter = {
  urls: ['xxx', 'xxx', 'xxx']
}
function pr () {
  session.defaultSession.webRequest.onCompleted(Metas.filter, () => {
               
  })
}
pr ()
pr ()
```

ps:From translation, English is poor, please understanding

**Comment by sofianguy** [comment]
@bpasero is this bug still present in version 4.x or later?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
