### ISSUE TITLE
require('oracledb') in electron Error  A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by styzkai** [electron/electron#15102]
* Output of `node_modules/.bin/electron --version`: 3.0.4
* Operating System (Platform and Version): windows 10 x64

var oracledb = require('oracledb');

in js..

Oracle client was also installed normally and environment variable was set.
It works normally when it runs in node.js . An error occurs when executing in the electronJs.

![image](https://user-images.githubusercontent.com/7356662/46848704-52523b00-ce26-11e8-9910-500a35a31df3.png)

python 2.7
Visual C++ 2013, 2015 Redistributable
node 8.12 and 10.2
oracledb 3.0.0

**Comment by MarshallOfSound** [comment]
See our tutorial on [Using native node modules](https://electronjs.org/docs/tutorial/using-native-node-modules).

You have to rebuild them for Electron
