### ISSUE TITLE
Notifications from main process doesn't show

### ISSUE THREAD

**Issue by ervinewell** [electron/electron#15101]
* Output of `node_modules/.bin/electron --version`: 3.0.3
* Operating System (Platform and Version): macOS Mojave 10.14
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
When I create notifications with node-notifier and Notification API from main process at the same time, both notifications will show.

**Actual behavior**
Once the notification created by node-notifier showed, the another one didn't show at all.

**To Reproduce**
https://github.com/ervinewell/electron-quick-start/tree/feature/native-notification

```sh
$ git clone https://github.com/ervinewell/electron-quick-start.git -b feature/native-notification
$ npm install
$ npm start
```

**Comment by MarshallOfSound** [comment]
@ervinewell A macOS application can only have one `NotificationCenterDelegate` instance.  If both Electron and `node-notifier` try to set there's as the default delete only one will succeed.

This is expected behavior and a limitation of macOS

**Comment by ervinewell** [comment]
> @ervinewell A macOS application can only have one `NotificationCenterDelegate` instance. If both Electron and `node-notifier` try to set there's as the default delete only one will succeed.
> 
> This is expected behavior and a limitation of macOS

Got it. I wonder if there's anyway to uninstall node-notifier or set electron Notification as default?

>

**Comment by ervinewell** [comment]
> @ervinewell A macOS application can only have one `NotificationCenterDelegate` instance. If both Electron and `node-notifier` try to set there's as the default delete only one will succeed.
> 
> This is expected behavior and a limitation of macOS

@MarshallOfSound Got it. I wonder if there's anyway to uninstall node-notifier or set electron Notification as default?
