### ISSUE TITLE
menu.getMenuItemById() doesn't work for separators

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#15119]
* Output of `node_modules/.bin/electron --version`: 3.0.4, 4.0.0-beta.1
* Operating System (Platform and Version): All
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2.0.10

**Expected Behavior**
[`menu.getMenuItemById`](https://electronjs.org/docs/api/menu#menugetmenuitembyidid) should return a `MenuItem` with a given `id`.

**Actual behavior**
`menu.getMenuItemById` returns `null` if a requested menu item is a separator (`type: 'separator'`).

**To Reproduce**
I added a test for this in [`fix-15119`](https://github.com/electron/electron/tree/fix-15119) branch. Here are test results for that branch
https://circleci.com/workflow-run/fb7d93a0-b0fb-4b9b-bcf5-cf566aa862cc

/cc @codebytere

**Comment by codebytere** [comment]
When you pass in a separator it removes the id: 
```
{ label: 'Item 1', id: 'item_1' }
{ label: 'Item 1', id: 'item_1' }
{ type: 'separator' }
{ label: 'Item 2', id: 'item_2' }
{ label: 'Item 2', id: 'item_2' }
```

i'll try to introduce it to that item

**Comment by codebytere** [comment]
@alexeykuzmin this is a side effect of a feature i implemented a while back: https://github.com/electron/electron/pull/12362

This is the line of code that does that: [menu-utils.js#L157](https://github.com/electron/electron/blob/master/lib/browser/api/menu-utils.js#L157)

**Comment by alexeykuzmin** [comment]
@codebytere 
Ok. Who's going to fix it and when?
