### ISSUE TITLE
desktopCapturer `display_id` is empty string on windows7

### ISSUE THREAD

**Issue by zjruan** [electron/electron#15111]
* electron v3.0.3
* windows 7

```
electron.desktopCapturer.getSources(options, function (error, sources) {
})
```

**Expected Behavior**
have new field `display_id`

**Actual behavior**
macOs-10.13.6、windows10 is right

window7, Field is present but is empty string

![image](https://user-images.githubusercontent.com/12164900/46860452-1083bd80-ce43-11e8-8ddf-33b85280816c.png)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you've responded, please link to the test case and @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by zjruan** [comment]
Based on the information you provided, I wrote a test case. Below is the address of my project:
https://github.com/zjruan/electron-quick-start
```
git clone https://github.com/zjruan/electron-quick-start.git
cd electron-quick-start
npm install
npm start
```
Here are two screenshots of the results

### windows10
![windows10](https://user-images.githubusercontent.com/12164900/46997837-644c1a80-d153-11e8-8c15-0c180f48e2f2.png)

### windows7
![windows7](https://user-images.githubusercontent.com/12164900/46997838-644c1a80-d153-11e8-8d85-24932ec0fbbe.png)

**Comment by MarshallOfSound** [comment]
@zjruan My understanding of this API is this is expected (yet probably undocumented) behavior.

```
  // Gather the same unique screen IDs used by the electron.screen API in order
  // to provide an association between it and desktopCapturer/getUserMedia.
  // This is only required when using the DirectX capturer, otherwise the IDs
  // across the APIs already match.
  if (cap->using_directx_capturer_) {
```

We only set `display_id` if we're using directX (because that's where the ID comes from) and if we aren't using directX you don't need `display_id` as the id of the media source and the ID of the screen match.

**Comment by zjruan** [comment]
@MarshallOfSound you are right.
But my software runs on a 2-screen machine, and the screenshot only wants to intercept the screen where the software window is located. getSources will get 2 `source`.

First of all, I need to determine which screen the software window is on by positioning.

Then I use the `id` property of the `Screen Object` to choose which `source` to use.

![image](https://user-images.githubusercontent.com/12164900/47057865-1d166600-d1f5-11e8-993a-3a8d4a24fbb4.png)

### macOs
`source Object` is like this, it is no problem.
![image](https://user-images.githubusercontent.com/12164900/47057355-d0319000-d1f2-11e8-8b2a-f79f0be0755f.png)

### windows
`source Object` can refer to the picture above. So I also have no way to use the `display_id`.

---

#### Screen Object

![image](https://user-images.githubusercontent.com/12164900/47058723-e93d3f80-d1f8-11e8-9e42-5940773c533b.png)

**Comment by clusterberries** [comment]
Hi guys! Any plan to fix it? 
I can confirm that it is reproduced with 3.0.10 on Windows 7 with 1 or 2 displays.

**Comment by zjruan** [comment]
I already have a way to solve my problem, but it is not very elegant.
``` javascript
  let winBounds = currentWindow.getBounds();
  let targetDisplay = electronScreen.getDisplayNearestPoint({ x: winBounds.x, y: winBounds.y });
  let targetDisplayIndex = allDisplay.findIndex(dis => {
    return dis.id === targetDisplay.id
  })
  let screenName = targetDisplayIndex + 1
  desktopCapturer.getSources(options, function (error, sources) {
    sources.forEach(function (source) {
      if (source.name === 'Screen ' + screenName || source.name === 'Entire screen') {
         // todo something
      }
    }
  }
```

**Comment by aabuhijleh** [comment]
This issue still persists on Windows 7 and Electron 4.0.5

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by clusterberries** [comment]
@sofianguy the issue is still reproduced with Electron 5.0.2 on Windows 7.

**Comment by clusterberries** [comment]
Issue is sill reproduced with Electron 6.1.7.

**Comment by JulyL1** [comment]
I still got this prolblem on my alienware desktop, one of our clients also met this problem on his Gaming computer.Is this problem caused by GEFORCE EXPERIENCE? BTW the electron version is 10.0.0

**Comment by sherali-uz** [comment]
still happening, display_id of all sources are empty

**Comment by nmilev-cursive** [comment]
Is there a way to intentionally reproduce this on Windows 10? Trying to debug an issue similar to this, which occurred on Win10.

**Comment by samuelmaddock** [comment]
If this issue only comes up when the DirectX capturer is not in use, it should be reproducible by disabling the WebRTC DirectX capturer. Note that I've not tested this.

```js
app.commandLine.appendSwitch('disable-features', 'DirectXCapturer');
```

The feature flag comes from https://source.chromium.org/chromium/chromium/src/+/main:content/public/browser/desktop_capture.cc;l=23-27;drc=870df28bda2ae8022ce2df17886bc253c2a92cb1

**Comment by JulyL1** [comment]
> If this issue only comes up when the DirectX capturer is not in use, it should be reproducible by disabling the WebRTC DirectX capturer. Note that I've not tested this.
> 
> ```js
> app.commandLine.appendSwitch('disable-features', 'DirectXCapturer');
> ```
> 
> The feature flag comes from https://source.chromium.org/chromium/chromium/src/+/main:content/public/browser/desktop_capture.cc;l=23-27;drc=870df28bda2ae8022ce2df17886bc253c2a92cb1

I was wondering how could we know whether  DirectX capturer is in use, because I met this problem at about 10am,and this problem didn't come up again on my computer after 1pm.I still don't know what happend

**Comment by zjruan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by junguksim** [comment]
Any progress in this issue???? Some of our users are still facing this issue

**Comment by zjruan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zjruan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zjruan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zjruan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zjruan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zjruan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zjruan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by vlades7** [comment]
bump

**Comment by zjruan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by samuelmaddock** [comment]
As of February 7, 2023, [Electron v23 has dropped Windows 7/8/8.1 support.](https://www.electronjs.org/blog/electron-23-0#dropping-windows-7881-support) Given the lack of any maintained version of Electron supporting Windows 7, I'll be closing this issue.

**Comment by vlades7** [comment]
> As of February 7, 2023, [Electron v23 has dropped Windows 7/8/8.1 support.](https://www.electronjs.org/blog/electron-23-0#dropping-windows-7881-support) Given the lack of any maintained version of Electron supporting Windows 7, I'll be closing this issue.

I found such a problem on Windows 10. It hardly depends on the operating system

**Comment by Sam-Golpasand** [comment]
Bump. This issue is also present on Linux. Fedora 42

`[
  {
    name: '',
    id: 'window:2:0',
    thumbnail: NativeImage {
      toPNG: [Function: toPNG],
      toJPEG: [Function: toJPEG],
      toBitmap: [Function: toBitmap],
      getBitmap: [Function: getBitmap],
      getScaleFactors: [Function: getScaleFactors],
      getNativeHandle: [Function: getNativeHandle],
      toDataURL: [Function: toDataURL],
      isEmpty: [Function: isEmpty],
      getSize: [Function: getSize],
      setTemplateImage: [Function: setTemplateImage],
      isTemplateImage: [Function: isTemplateImage],
      isMacTemplateImage: [Getter/Setter],
      resize: [Function: resize],
      crop: [Function: crop],
      getAspectRatio: [Function: getAspectRatio],
      addRepresentation: [Function: addRepresentation]
    },
    display_id: '',
    appIcon: null
  }
]`

**Comment by zjruan** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
