### ISSUE TITLE
3.0.x auto-generated release notes are difficult to read

### ISSUE THREAD

**Issue by ckerr** [electron/electron#15116]
**Description**
- [ ] bugfixes from rolled submodules aren't listed
- [ ] PR release note line is not used
- [ ] Doesn't use semantic commits to separate bugfixes from features
- [ ] _(minor)_ Allows inconsistent sentence capitalization / punctuation

**Expected Behavior**

> ## Bug Fixes
>
> * Allows the window to be maximization status to be restored to previous value upon being resizable again. #15032
>
> * Snap to minimum size possible when setSize is called below size constraints. #15038
>
> * Fixed crash in proxy login handler. #15044
>
> * Handle shortcuts by default if no WebPreferences object exists. #15066
>
> * Fix shift based accelerators not rendering correctly. https://github.com/electron/electron/pull/14966 #15072

**Actual behavior**

> ##  Bug Fixes/Changes 
>
> * Backport of #14648. #15032 
> 
> * fix: Check minSize constraints before resizing (backport: 3-0-x). #15038 
> 
> * fix: Lifetime of auth_info_ in login handler. #15044 
>
> * fix: handle shortcuts by default if no WebPreferences object exists. #15066 
>
> * chore: bump libcc (3-0-x). #15072

**Comment by MarshallOfSound** [comment]
Lot's of this will be fixed just by updating our release scripts to use the new release notes generator

https://github.com/electron/electron/blob/master/script/release-notes/index.js

It's there but just hasn't been wired up, the final part of that would be wiring up the Clerk comments to that generator.

**Comment by pronebird** [comment]
You folks have some insane automation in place. Leave a comment saying "fix all the bugs" and some robot wakes up and sends PRs. 😮

**Comment by nornagon** [comment]
are you calling @ckerr a robot? 😉

**Comment by pronebird** [comment]
@normagon haha 😆 no! But @trop is.

**Comment by ckerr** [comment]
@trop is calling me a robot? :thinking:

**Comment by codebytere** [comment]
This has been fixed :)
