### ISSUE TITLE
tray.setImage does not work in lxqt

### ISSUE THREAD

**Issue by averissimo** [electron/electron#15124]
* Electron version: `v3.0.3`
* Operating System (Platform and Version): Ubuntu 18.10
* Desktop environment: lxqt
    * no problems in gnome or kde

**Expected Behavior**
Tray icon changes to expected image

**Actual behavior**
Gear appears instead

**To Reproduce**
```
$ git clone https://github.com/averissimo/lxqt-tray
$ cd lxqt-tray
$ npm install
$ npm start
# click on the only option to change the tray icon
```

**Comment by miniak** [comment]
We don’t have the capacity to support all possible window managers on Linux. Feel free to publish a PR fixing the issue

**Comment by jmfernandez** [comment]
As a workaround, forcing XDG_CURRENT_DESKTOP=KDE makes any electron app which needs the tray to behave properly in LXQt.

So, I guess the bug could be related to the default behaviour managing the tray inside electron when it does not know the desktop environment
