### ISSUE TITLE
4.0 does not seem to have adequate release notes (changes from 3.0)

### ISSUE THREAD

**Issue by bughit** [electron/electron#15122]
the first release of 3.0 had somewhat comprehensive release notes
https://github.com/electron/electron/releases/tag/v3.0.0-beta.1

4.0 barely has anything
https://github.com/electron/electron/releases/tag/v4.0.0-beta.1

**Comment by ckerr** [comment]
Related to https://github.com/electron/electron/issues/15116

**Comment by bughit** [comment]
From your comment, it seems that you're working on an automated system, but in the mean time 4.0 is on the 5th beta and there's still no what's new/changed from 3.0. Would it not make sense to do a manual compilation like in 3.0?

**Comment by codebytere** [comment]
@ckerr did this get resolved?

**Comment by ckerr** [comment]
@codebytere yep, this should've been closed awhile back. The new release notes generator solves this problem and the notes for 4.0.0 were regenerated.
