### ISSUE TITLE
ANSI escape sequences displayed literally when downloading NSIS for the 1st time

### ISSUE THREAD

**Issue by tmcdos** [electron/electron#15146]
* Output of `node_modules/.bin/electron --version`: v3.0.4
* Operating System (Platform and Version): Windows 7 x64 SP1

* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): N/A

### Expected behavior

All ANSI escape sequences should be executed rather than displayed literally.

### Actual behavior

Notice the bright green, dark blue, and yellow texts in the attached screenshot - however, when the downloading of NSIS installer begins then the ANSI escape sequences are displayed literally rather then being executed.
![nsis](https://user-images.githubusercontent.com/19253115/46907026-0205d680-cf15-11e8-8a0e-27bae234bd25.png)

### How to reproduce

You can use the repository of an actual project - https://github.com/tmcdos/mockapist but I think this can be reproduced with any project on Windows.
Just make sure that there is no **Cache** folder inside `d:\Profile\user\AppData\Local\electron-builder`

$ git clone git@github.com:tmcdos/mockapist.git
$ npm install
$ npm build

**Comment by MarshallOfSound** [comment]
This issue is for electron builder, not electron itself, electron builder is a third party project.
