### ISSUE TITLE
inAppPurchase.getReceiptURL() should be filesystem path

### ISSUE THREAD

**Issue by semireg** [electron/electron#15140]
* Output of `node_modules/.bin/electron --version`: v3.0.4
* Operating System (Platform and Version): macOS 10.13.6

My current app is accepted by Apple and "pending developer release." However, before I release it I wanted to add and test IAP (in app purchases).

**Expected Behavior**
release/mas-dev/MyApp.app, lacking a receipt, launches and exits immediately with code 173 that triggers login for MAS sandbox test user, receipt is generated, and app should re-launch OK.

**Actual behavior**
Everything related to the first-launch, exit 173, login with test account, and receipt generation works fine. It fails on relaunch with console.app reporting a kernel message: `load code signature error 4 for file "MyApp Helper"`.

**To Reproduce**
I do not have a good reproduction because of the complexity of entitlements, provisioning profiles, certificates, etc.

**Screenshots**
Receigen says that the app has a valid receipt.
![2018-10-13 at 12 14 am](https://user-images.githubusercontent.com/1819762/46901641-f6ff6780-ce7c-11e8-95d0-a4549ca90d76.png)

Entitlements look good, and the app is functioning fine in the sandbox...
![2018-10-13 at 12 15 am](https://user-images.githubusercontent.com/1819762/46901651-1d250780-ce7d-11e8-9103-088e7276e99c.png)

**Additional Information**
The only other file I see that looks like "MyApp Helper" is in MyApp.app/Contents/Frameworks/MyApp Helper.app. If I drag this into Receigen for analysis... it is signed, and has these entitlements. It doesn't have a receipt... which I wouldn't expect.

![2018-10-13 at 12 17 am](https://user-images.githubusercontent.com/1819762/46901666-6412fd00-ce7d-11e8-8dc9-3cfc2acb8aeb.png)

I don't think I need LoginItems or helpers... what do they do, exactly? Also, what are the EH/NP versions of these helpers?

Thanks!

**Comment by semireg** [comment]
@MarshallOfSound, I think I found a bug - the call to inAppPurchase.getReceiptURL() returns the NSURL's absoluteString. This causes issues in opening the file because the path becomes `file:///path/to/my%20app/Contents/_MASReceipt/receipt`, which fails to open using fs.readFile. 

Instead, the path should be '/path/to/my app/Contents/_MASReceipt/receipt', which is likely better represented by NSURL's [fileSystemRepresentation](https://developer.apple.com/documentation/foundation/nsurl/1412925-filesystemrepresentation).

Or, am I misusing the node API?

**Comment by MarshallOfSound** [comment]
@semireg PRs welcome if its just a change from `absoluteString` to `fileSystemPresentation` 👍

**Comment by semireg** [comment]
The caveat is `fileSystemRepresentation` a `UnsafePointer<Int8>` vs. `String?`. Unfortunately, I don't have the time right now to get the electron contributor build env setup on my machine, and then enter battle with bridging primitive Obj-C data types.

Well, that, and the change should be validated by another person using this. Maybe I'm overlooking something. :-)

**Comment by MarshallOfSound** [comment]
@semireg As a temporary thing you could be able to use `decodeURI(inAppPurchase.getReceiptURL())` to safely decode the `%20` or any other URI encoded chars
