### ISSUE TITLE
N-API doesn't work in Electron 4.0.0-beta.3 on Linux

### ISSUE THREAD

**Issue by gorunovanton** [electron/electron#15168]
* Output of `node_modules/.bin/electron --version`:  v4.0.0-beta.3
* Operating System (Platform and Version): Linux 4.15 (Ubuntu 18.04.1 x64)
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 3.0.0

**Expected Behavior**
[N-API](https://nodejs.org/api/n-api.html) symbols are exported on Linux in Electron executable.

**Actual behavior**
No N-API symbols are exported from Electron executable.Native addons built with N-API can't be used due to unresolved symbol errors at runtime.

**To Reproduce**
Check for list of exported symbols with [nm](https://linux.die.net/man/1/nm) utility (nm -C -D node_modules/electron/dist/electron | grep napi).Also this problem can be reproduced by installing and importing the [node-ffi-napi](https://github.com/node-ffi-napi/node-ffi-napi) module.

**Additional Information**
The set of exported symbols changed in Electron 4 due to static linking with Node instead of shared linking.In previous versions (e.g. 3.0.0) the N-API symbols were exported by libnode.so.

**Comment by MarshallOfSound** [comment]
Fixed in electron/node#77
