### ISSUE TITLE
tray tooltip not working on linux

### ISSUE THREAD

**Issue by hovancik** [electron/electron#15161]
* Output of `node_modules/.bin/electron --version`: 3.0.4, 4 beta 
* Operating System (Platform and Version): Linux
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): I have app in 2.0.0 (2.0.11) that works

**Expected Behavior**
I should see tooltip

**Actual behavior**
No tooltip is visible

**To Reproduce**
If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone https://github.com/hovancik/electron-tooltip-bug
$ npm install
$ npm start || electron .
```

**Comment by hovancik** [comment]
is there anyway we can move this forward? considering that this is a regression issue and it was working on v2...

**Comment by hovancik** [comment]
still issue on electron 5

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by hovancik** [comment]
Still issue in Electron: 7.1.9

**Comment by mokkun** [comment]
I know that at least on Gnome 3 you won't have tray icons.
See https://bugzilla.gnome.org/show_bug.cgi?id=785956

I'd expect the app to display in the dock instead.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by hovancik** [comment]
Had to create new issue because of electron's friendly bot: https://github.com/electron/electron/issues/28131 

Please subscribe there for updates.

**Comment by geekCyberWarrior** [comment]
The same issue still persists where the tooltip shown is "electron" irrespective of what is set

- Kali Linux 2021.2 x64
- KDE Plasma Version: 5.20.5
- Electron 13.1.7

**Comment by samuel482** [comment]
Calme 561-856-596
