### ISSUE TITLE
Windows Tablet Mode

### ISSUE THREAD

**Issue by bkniffler** [electron/electron#15165]
**Is your feature request related to a problem? Please describe.**
In windows tablet mode, you may want to change your UI. There is apps that enlarge the title bar or hide the title bar buttons since they are useless (in tablet mode, every window is forced into fullscreen mode and minimizing is disabled). The is no way to detect tablet mode in electron.

**Describe the solution you'd like**
~~Something like systemPreferences.tabletMode() and a `tablet-mode-changed` should be available~~
We need a BrowserWindow instance method like `window.getUserInteractionMode()` that gives us the primary input mode for a view. `window.resize` event should be sufficient to listen to changes to tablet mode. Here is more info: https://blogs.msdn.microsoft.com/oldnewthing/20160706-00/?p=93815

**Describe alternatives you've considered**
I looked into going to the Browser API  in renderer, but there is no clear way to check if a device is in tablet mode. You can basically just check if there is touch available, which is not the same.

**Additional context**
This is outlook hiding their title bar buttons in tablet mode.
<img width="850" alt="anmerkung" src="https://user-images.githubusercontent.com/4349324/46936928-42be3680-d060-11e8-8dfc-815ccac98e62.png">
<img width="849" alt="anmerkung2" src="https://user-images.githubusercontent.com/4349324/46936929-4356cd00-d060-11e8-8405-df5933e7cfbc.png">

**Comment by xmuskrat** [comment]
+1

**Comment by xmuskrat** [comment]
This is a feature I am looking for as well.
