### ISSUE TITLE
some <input> patterns cause browser to go blank on some windows machines

### ISSUE THREAD

**Issue by jonathon-love** [electron/electron#15179]
* Output of `node_modules/.bin/electron --version`:

3.0.4 and 4.0.0-beta.3 (64-bit)

* Operating System (Platform and Version):

Windows 10 pro, 64-bit

when entering data into an `<input type="text">` field with a pattern:

**Expected Behavior**
it will not go blank

**Actual behavior**
the browser window suddenly goes blank/white.

**To Reproduce**

have electron display an input like this:

```
<input type="text" pattern=".">
```

enter some random text into it in electron.

**Screenshots**

before (note the `<input>` at the bottom left):

<img width="1274" alt="screen shot 2018-10-16 at 10 22 34" src="https://user-images.githubusercontent.com/3240247/46983695-7024e600-d12d-11e8-94ad-b3385bf9db2c.png">

after:

<img width="1274" alt="screen shot 2018-10-16 at 10 22 39" src="https://user-images.githubusercontent.com/3240247/46983701-76b35d80-d12d-11e8-8602-40818c0ff1b0.png">

**Additional Information**

Only affects some windows installations. I've reproduced it on two machines so far.

**Comment by brenca** [comment]
I tried, but couldn't repro this on my machine. Can we try to find common things between those machines that reprod this? That might help us figure out what's going on.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
