### ISSUE TITLE
show native program window in web

### ISSUE THREAD

**Issue by maxzhou0** [electron/electron#15189]
**Is your feature request related to a problem? Please describe.**
We had some old win32 programs. we planned to rewrite them in electron app in the future. 
but now we want to integrate the old win32 programs into electron, the programs can run in a tab page of the browser

**Describe the solution you'd like**
give a path map that can configure the local programs

```
{
   cmd:'c:/windows/system32/cmd.exe',
   paint:'c:/windows/system32/mspaint.exe',
   mynativeapp:'./myapp.exe'
}
```
use a scheme url to open the program in a blank target window
nativeapp://cmd
nativeapp://paint 
nativeapp://mynativeapp arg0 arg1

**Comment by nornagon** [comment]
Thanks for your feature request! Unfortunately, hosting native apps inside Electron's window structure is a hugely complicated task with limited benefits, and it isn't something we're interested in building at this time. Best of luck with rewriting your old programs into Electron :)
