### ISSUE TITLE
Page does not change with loadURL()  Electron 3.х.х and 4.х.х

### ISSUE THREAD

**Issue by u4aew** [electron/electron#15187]
Electron version: 3.х.х and 4.х.х
The method does not change the page mainWindow.loadURL()
In early versions of the electron, everything works (2.0.11)

### Expected behavior
Page change successfully

### Actual behavior
The page can not change

### How to reproduce
When the application starts, the loader page is displayed.

const pages = require('./constants/pages')
mainWindow.loadURL(page.loader)

After successfully reading the config, the page should change 
mainWindow.loadURL(pages.BASE)

Temporary solution
setTimeout(() => { mainWindow.loadURL(pages.BASE) }, 3000)

![photo_2018-10-16_14-45-31](https://user-images.githubusercontent.com/18558430/47000308-30bcc080-d152-11e8-8a49-13583dbf6845.jpg)

**Comment by nornagon** [comment]
I can't reproduce this, `loadURL` works fine for me.

See this [electron/fiddle](/electron/fiddle) gist: https://gist.github.com/nornagon/91d1b8d5c8e2a0d707ceaca94ad17466
