### ISSUE TITLE
Cannot access Window object properties returned by window.open() with nativeWindowOpen option for a different domain even though same origin policy is disabled

### ISSUE THREAD

**Issue by aabuhijleh** [electron/electron#15197]
* Electron version: v3.0.3
* Operating System: Windows 10 x64

**Expected Behavior**
When `webPreferences.nativeWindowOpen` is set to true and `webPreferences.webSecurity` is set to false, using window.open() should return a Window object with accessible properties. For example, childWindow.location.href should give me the URL of that child window.

Disabling same origin policy in Chrome by using `--disable-web-security` enables me to gain full access to the properties of the Window object returned by window.open() even when the new window URL belongs to a different domain. This is not happening in Electron.

**Actual behavior**
When trying to access Window properties of windows created by window.open() for a different domain this occurs:
```
Uncaught DOMException: Blocked a frame with origin "${Loaded_Domain}" from accessing a cross-origin frame.
```

Even though web security is disabled

**To Reproduce**
* Clone this [repo](https://github.com/aabuhijleh/electron-window.open-web-security-disabled-issue)
* Run npm install && npm start in the cloned repo
* Open the dev tools in the main window and see the console's output for childWindow.location.href for the child window

**Comment by MarshallOfSound** [comment]
Merging into #15132 for `webSecurity` not working quite right in `3.0`

**Comment by IAmPicard** [comment]
Note that that bug is about 4.0 ; everything works right for me on 3.0
