### ISSUE TITLE
Module did not self-register.

### ISSUE THREAD

**Issue by deanihansen** [electron/electron#15199]
* Output of `node_modules/.bin/electron --version`: 3.0.4
* Operating System (Platform and Version): Windows 10 (17134.345)
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): Likely pre-electron 3

**Expected Behavior**
Native modules should be able to reload just fine. Even in `preload`

**Actual behavior**
Intermittently experiencing to see `Error: Module did not self-register.` in devtools when instantiating new `BrowserView` objects with preload scripts referencing native modules. 

Trace: 
``` 
error: Error: Module did not self-register.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\source\slack-desktop\node_modules\runas\lib\runas.js:4:11)
    at Object.<anonymous> (C:\source\slack-desktop\node_modules\runas\lib\runas.js:47:4)__proto__: Object 
``` 

**To Reproduce**
N/A. 

**Screenshots**
Resources shared in ElectronHQ Slack channel. 

**Additional Information**
This is only reproducible in Slack. In production the issue is intermittently reproducible where when running as developer it's always reproducible.

**Comment by deepak1556** [comment]
Seems to be a similar issue https://github.com/electron/electron/issues/4025 , can you share net-log trace to identify the type of navigation thats happening. Also can you log the process id, to confirm process reuse.

**Comment by deanihansen** [comment]
@deepak1556 We've not been able to see the process reuse when evaluating ID's. I'll DM you the netlogs in Slack.

**Comment by avner-hoffmann** [comment]
This is happening in the latest stable electron version (4.0.5)
Preload script won't work when you try to reload browser window url when it requires native modules
Why is this happening? What can be done to solve it?
It doesn't make sense that the recommendation is to use preload script but the basic thing like reloading urls a few times can't work with it

**Comment by payitforwardnow** [comment]
Im having the same issue. 

Electron v7.0.0
Node 12.13.0
MacOS 10.13.6

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
