### ISSUE TITLE
Add `openAtLogin` support for Linux?

### ISSUE THREAD

**Issue by pronebird** [electron/electron#15198]
**Is your feature request related to a problem? Please describe.**
Currently `setLoginItemSettings` does not provide the way to add apps to autostart on linux, but it shouldn't be too hard to implement.

**Describe the solution you'd like**
AFAIK the one has to symlink the app into `/usr/share/applications` or something like that.

**Describe alternatives you've considered**

**Additional context**

**Comment by codebytere** [comment]
This is not possible within the current bounds of Electron and Chromium - Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone somehow determine a workable solution we would be potentially open to accepting a PR!

**Comment by tkainrad** [comment]
Hi @codebytere 

Just stumbling upon this. It seems to me that this should be possible by generating a `.desktop` file in `~/.config/autostart`. This wouldn't be much more complicated than what is done on Windows and macOS. 

Many other (non-electron) apps do it this way. Also, the no longer maintained _node-auto-launch_ project used this approach: https://github.com/Teamwork/node-auto-launch/blob/1394a0aacfc1031bd44931c316cc89ccf43f63c4/src/AutoLaunchLinux.coffee

Does this sound like a reasonable solution to you? I am happy to create a new issue or PR if this sounds like a reasonable approach to you.

**Comment by jgresham** [comment]
@tkainrad did you get a chance to look at this? it seems straightforward

**Comment by tkainrad** [comment]
@jgresham I did implement it for [my own app](https://keycombiner.com/) but didn't work on a PR for Electron. 

I have followed quite closely what the _node-auto-launch_ project did. See the link in my previous comment.
