### ISSUE TITLE
webview的渲染进程如何设置代理的账号和密码

### ISSUE THREAD

**Issue by mofeiwo** [electron/electron#15208]
* Output of `node_modules/.bin/electron --version`:v2.0.8
* Operating System (Platform and Version):MacOS 10.13.6

### Expected behavior

webview可以设置代理的账号和密码

### Actual behavior

无法设置

**Comment by MarshallOfSound** [comment]
I believe you are looking for the `login` event on the `webContents` object.

It allows you to provide credentials for authenticated proxies.

https://electronjs.org/docs/api/web-contents#event-login
