### ISSUE TITLE
Unit tests is giving ** fs.existsSync() is not a function ** Error for Electron- Angular 5 Desktop App

### ISSUE THREAD

**Issue by venkateshp241093** [electron/electron#15215]
Hi,
 
We are facing a problem in executing the unit test written for our desktop application developed in Electron + Angular 5 JavaScript frameworks.
 
Details:
1.	We have created a Desktop application to access and modify the device configurations attached to PC over USB, we have below components in the application.
2.	We have an SDK which is written in C++ to do low level interaction with the device.
3.	We have a wrapper around the SDK C++ APIs which is written in NodeJS and a Native Node module is created in NodeJS.
4.	In the UI application, we access the Native Node module which is created as wrappers and we access and modify the device configurations.
5.	UI application is written in ElectronJS build framework and Angular 5.
 
The application is working fine without any issues and but we are facing an issue to create unit test’s
 
For unit test, we are using Jasmine and Karma frameworks to write and execute tests.
Where it throws a compilation error as below, which is common across the dependencies of the application.
 

 
ERROR in ./src/renderer/app/providers/diagnostics.service.ts
Module not found: Error: Can't resolve 'fs' in '/Users/venkatesh/Desktop/Myproject/src/renderer/app/providers'
@ ./src/renderer/app/providers/diagnostics.service.ts 112:29-42 184:25-38
@ ./src/renderer/app/providers/diagnostics.service.spec.ts
@ ./src/renderer \.spec\.ts$
@ ./src/renderer/test.ts

We tried using webpack: { node : { fs: 'empty' }} in karma.conf.js
 
But later it throws an error as below

fs.existsSync() is not a function.
 
 
fs.existsSync() is a function which is called in Electron Node module and it throws an error as above.

Expected: 

The unit tests compiles and the test is started.

 
Any solutions or pointer to resolve this issue would be of great help.

Thanks in advance,

**Comment by MarshallOfSound** [comment]
@venkateshp241093 This will be your karma / webpack config mocking out `fs` or failing to realize `fs` is available in Electron.  Not an electron issue

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by lpt9** [comment]
I have the same problem. Have you solved it?
