### ISSUE TITLE
Out-of-date Chromedriver packaged in electron 3 and 4beta

### ISSUE THREAD

**Issue by happypoulp** [electron/electron#15212]
* Output of `node_modules/.bin/electron --version`: v3.0.4
* Operating System (Platform and Version): macOS High Sierra 10.13.6
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): N/A

**Expected Behavior**
*electron 3.0.4:*
The version of Chromedriver packaged in electron 3.0.4 should be the most up-to-date supporting Chrome 66: Chromedriver v2.38 (version 2.39 and 2.40 are supposed to support Chrome 66 too but they don't seems to play out well with spectron from what I've tried).
*electron 4beta:*
The version of Chromedriver packaged in electron 4beta should be the most up-to-date supporting Chrome 69: Chromedriver v2.42.

**Actual behavior**
The version of Chromedriver packaged in electron 3.0.4 is Chromedriver v2.36 and this version creates lots of failures when testing an electron application using Spectron: the issues I am reproducing are related to "unknown session ID" and "cannot determine loading status". Those issues are fixed in Chromedriver v2.38 (see http://chromedriver.chromium.org/downloads).
The version of Chromedriver packaged in electron 4beta is Chromedriver v69.0.3497.106 which is a non-existing version of Chromedriver, the more up-to-date being v2.42.

**To Reproduce**
Not steps to reproduce appart from installing Spectron and seeing that the chromedriver version used is not the most up-to-date one that can be used for the Chromium version electron is using.

**Additional Information**
For the records, even though this might seems like a Spectron issue, I am opening the issue in electron because Spectron uses electron-chromedriver (to download Chromedriver) which is itself using electron-download which is itself downloading chromedriver from **electron repository**.

**Comment by computerquip-streamlabs** [comment]
We've worked around this by adding
```
"resolutions": {
    "spectron/**/electron-chromedriver": "3.0.0-beta.1"'
}
```
to our list of resolutions. This is more of an issue with Spectron than it is electron from what I can tell.

**Comment by jkleinsc** [comment]
Chromium changed versioning of chromedriver to match chromium version: https://chromium.googlesource.com/chromium/src/+/175bd1a52fc9755ff60f5110e49e97644ed6299f%5E%21/chrome/test/chromedriver/embed_version_in_cpp.py, so for 4.0.x chromedriver will be versioned as `ChromeDriver 69.0.3497.106`

**Comment by happypoulp** [comment]
Thanks for the explanations @jkleinsc ! What do you think about upgrading Chromedriver to v2.38 for electron 3?

**Comment by codebytere** [comment]
@happypoulp i've released a version of `electron-chromedriver` corresponding to M69, so now 4.0.0 beta release lines will properly download those. The issue with the above is that the included ChromeDriver versions aren't a result of versions we choose; rather, they're the versions bundled with the Chromium revisions present in those release lines. To address your issues, we could potentially attempt to patch back updates made to ChromeDriver, but it wouldn't be 2.38 in the truest sense, it'd be [2.36 + some patches].

**Comment by happypoulp** [comment]
@codebytere thanks, I understand better now.

If I am the only one requesting such changes, I guess it is not worth the effort to patch back ChromeDriver, I'll just wait for electron 4 to be released. I can find my way around meanwhile by manually replacing ChromeDriver 2.36 binary with the 2.38 one so I am fine to close the issue.

Thanks!

PS: For my own complete understanding, when you say that "ChromeDriver versions are the versions bundled with the Chromium revisions present in those release lines" do you mean that ChromeDriver is never updated independently of Chromium itself? Looking at http://chromedriver.chromium.org/downloads it seems that ChromeDriver v2.36 was never intended to support Chrome 66 in the first place...
