### ISSUE TITLE
Webpreferences additionalArguments not working in webview

### ISSUE THREAD

**Issue by component17** [electron/electron#15217]
Electron v.3.0.3
MacOs 10.14 (Mojave)

**Expected Behavior**
Try to implement `webPreferences` (`additionalArguments`) to transfer short string data from render process to `webview`. As expected, `process.argv` should contain our string.

**Actual behavior**
Webview argument `webPreferences ` ignore this parameter, `additionalArguments`, as a result we can not transfer our short string message from render process to webview process.

**To Reproduce**
Webview contains next arguments: 

```
 <webview :src="module.src"
                         autosize
                         nodeintegration
                         :preload="preload"
                         webpreferences="additionalArguments=['testARGV']"
></webview>
```

In console, when we try to get process arguments (`process.argv`) we did not observe `additionalArgument's string`:

![image](https://user-images.githubusercontent.com/25381568/47095046-16a7de80-d235-11e8-8543-6d7833880046.png)

**Comment by MarshallOfSound** [comment]
@component17 Unfortunately this is not supported, the `webpreferences` attribute on a webview is parsed by splitting at "," characters.  Imagine the case where someone want's multiple arguments.

```
webpreferences="additionalArguments=['a', 'b'],nodeintegration=false"
```

That would break because there is a "," in the `additionalArguments` array, you're best solution here is to use the `will-attach-webview` event to set your `additionalArguments` on the `webPreferences` object directly in the main process.

https://electronjs.org/docs/api/web-contents#event-will-attach-webview

**Comment by mannok** [comment]
@MarshallOfSound Unfortunately is not working in 4.0.3

I can retrieve `webPreferences` in the callback of `will-attach-webview`. But I don't find `process.argv` has additional argument in my `<webview>` even I set some additional parameter in the callback by `.on('will-attach-webview', (evt ,webPreferences, params ) => { webPreferences.additionalArguments = ['testtest']; })`

**Comment by thomas-void0** [comment]
> [@component17](https://github.com/component17) Unfortunately this is not supported, the `webpreferences` attribute on a webview is parsed by splitting at "," characters. Imagine the case where someone want's multiple arguments.
> 
> ```
> webpreferences="additionalArguments=['a', 'b'],nodeintegration=false"
> ```
> 
> That would break because there is a "," in the `additionalArguments` array, you're best solution here is to use the `will-attach-webview` event to set your `additionalArguments` on the `webPreferences` object directly in the main process.
> 
> https://electronjs.org/docs/api/web-contents#event-will-attach-webview


this way help me solve the problem. thank you
