### ISSUE TITLE
window. sessionStorage sometimes is empty on Windows with few Memory

### ISSUE THREAD

**Issue by jalyna** [electron/electron#15214]
* Output of `node_modules/.bin/electron --version`: v4.0.0-beta.3 (reproducable with v3, too)
* Operating System (Platform and Version): Microsoft Windows 10 Home 10.0.17134 Build 17134, memory 1GB

**Expected Behavior**
`window.sessionStorage` should be kept on the same host/window.

**Actual behavior**
Randomly the `window.sessionStorage` is empty even though there was data written to it. It is flaky.

Also it seems to be affected by Memory. If I e.g. increase the memory to 3GB I can't reproduce the issue. So far I could only reproduce it with Windows.

I created a video that demonstrates the example code. besides the first 'empty storage' alert, it should never be empty afterwards (but it is).

**To Reproduce**

I created a simple electron fiddle gist: https://gist.github.com/jalyna/382d878ff51670146d98de26847b967e

Run the code on Windows with very few memory.

If you will see the Alert more than one time at the beginning, you reproduced the issue.

**Screenshots**

Video

https://vimeo.com/user90717358/review/295544061/a6e3aaa05c

**Additional Notes**

- localStorage is not affected
- not reproducible in Chrome or Chromium

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
