### ISSUE TITLE
cut, copy, paste not working with webview

### ISSUE THREAD

**Issue by adammeyer** [electron/electron#15219]
Electron version 3.0.4

**Actual behavior**
Cutting, copying or pasting from menu not working on Windows if webview is on page.  Working on Mac OS.  Keyboard shortcuts are working fine.  This is from the top "Edit" menu.

Code to reproduce below.  Works fine until you add the webview element.  Then cut, copy and paste quits working.
```html
<textarea></textarea>
<webview src="iframe.html"></webview>

**Comment by vladimiry** [comment]
It also affects the context menu. Besides issue is reproducible on Linux as well. Didn't try it on macOS, it also might be affected. If I downgrade to Electron v2 it starts working as expected.

I seem to found a workaround. It works if you execute the action directly on `webContent`. The `role` based actions don't work, but `(custom)` actions do work as expected:
```javascript
    mainWindow.webContents.on("context-menu", ({sender: webContents}, {editFlags}) => {
        const template = [
            ...(editFlags.canCut
                    ? [
                        {role: "cut"},
                        {label: "Cut (custom)", click: () => webContents.cut()},
                    ]
                    : []
            ),
            ...(editFlags.canCopy
                    ? [
                        {role: "copy"},
                        {label: "Copy (custom)", click: () => webContents.copy()},
                    ]
                    : []
            ),
            ...(editFlags.canPaste
                    ? [
                        {role: "paste"},
                        {label: "Paste (custom)", click: () => webContents.paste()},
                    ]
                    : []
            ),
        ];

        if (!template.length) {
            return;
        }

        Menu
            .buildFromTemplate(template)
            .popup({});
    });
```

**Comment by soundar78** [comment]
The shortcuts are not working in MAS builds. Will this be fixed anytime soon ?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
