### ISSUE TITLE
Remember Desktop No. on app restart in macOS

### ISSUE THREAD

**Issue by s-kashif** [electron/electron#15211]
> Start the app 
> Move in to another desktop (macOS virtual spaces)
> Restart the app

Result: App jumps back to the first desktop

Would be nice if it remembers the last desktop it was on

**Comment by MarshallOfSound** [comment]
This is something apps can implement (by saving window location on quit and restoring on start)

**Comment by ericdrobinson** [comment]
@MarshallOfSound With respect to this:

> This is something apps can implement (by saving window location on quit and restoring on start)

How certain of this are you? If you're certain that it's something apps can implement themselves, then do you have any pointers for enabling this?

My understanding is that it requires implementation at the `NSWindow` level. From the [Mac App Programming Guide](https://developer.apple.com/library/archive/documentation/General/Conceptual/MOSXAppProgrammingGuide/CoreAppDesign/CoreAppDesign.html#//apple_ref/doc/uid/TP40010543-CH3-SW26):

> You must do the following to preserve the state of your user interface:
> 
> - For each window, you must set whether the window should be preserved using the [`setRestorable:`](https://developer.apple.com/documentation/appkit/nswindow/1526255-restorable) method.
> - For each preserved window, you must specify an object whose job is to re-create that window at launch time.
> - Any objects involved in your user interface must write out the data they require to restore their state later.
> - At launch time, you must use the provided data to restore your objects to their previous state.

Do you know of an Electron-based app that has successfully implemented this?

Additionally, the best resource I've found for how Google implemented this to be in [this initial changelist](https://chromium-review.googlesource.com/c/chromium/src/+/1808708) ([found in this comment](https://bugs.chromium.org/p/chromium/issues/detail?id=74812#c107)).

**Comment by ericdrobinson** [comment]
@MarshallOfSound I dug a bit more into this and my guess is that you're equating this issue with the concept of "Saving and Restoring Window State" as expressed in solutions provided in https://github.com/electron/electron/issues/526. Unfortunately, "Desktop Number" (or, in macOS parlance, "Spaces") **cannot** be addressed in this manner: Apple **does not** provide APIs for assigning windows to particular Spaces.

Apple expects Spaces to work as follows:

1. **Space Assignment:** User moves a window directly to a target Space within the macOS UI. There are a number of ways to do this.
2. **Space Restoration:** On computer restart (and, apparently, on [forced app restart](https://chromium-review.googlesource.com/c/chromium/src/+/1808708/20/chrome/browser/chrome_browser_main_mac.mm#468)?), Apple requests that `NSWindow` instances save their state on shutdown and then restore that state on startup.

As "simple" as that. Indeed, that second item is exactly what [the changelist](https://chromium-review.googlesource.com/c/chromium/src/+/1808708) I linked in my [previous comment](https://github.com/electron/electron/issues/15211#issuecomment-1454150920) implements.

Unfortunately, this **isn't** something that applications built on top of Electron can handle without modifying Electron's source code.
