### ISSUE TITLE
To be able to test Tray

### ISSUE THREAD

**Issue by diplozoon** [electron/electron#15221]
**Is your feature request related to a problem? Please describe.**
I created tray app using Electron.
But, for tray app, cannot use Spectron.

**Describe the solution you'd like**
Add the official module to test tray.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
