### ISSUE TITLE
Buffer is not a constructor when running electron in node mode

### ISSUE THREAD

**Issue by dattn** [electron/electron#15243]
* Output of `node_modules/.bin/electron --version`: v2.0.11
* Operating System (Platform and Version): Ubuntu 18.04.1 LTS
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): /

**Expected Behavior**
The version of pm2 should be displayed.

**Actual behavior**
En error occures:
```
/node_modules/amp/lib/stream.js:25
  this._lenbuf = new Buffer(4);
                 ^

TypeError: Buffer is not a constructor
```

**To Reproduce**
Demo repository can be found here:
https://github.com/dattn/bug-electron-pm2-fork

```sh
$ npm install
$ npm run version
$ npm run pm2_version
```

**Additional Information**
I want to create pm2 based process manager in electron. Without the need to install nodejs on the client pc.

When running pm2 version with standard nodejs it is working as expected.

**Comment by MarshallOfSound** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

P.S. I tried to repro this (`ELECTRON_RUN_AS_NODE=1 electron test.js`) but it worked fine

**Comment by dattn** [comment]
That was also my first idea, But the Buffer API is only deprecated in Node 8.x and changed in Node 10.x.
And as i have used electron 2.x which ships with Node 8, this can not be the problem. 
I also tried to run the script directly with node (not electron), the code works without problem.
So there needs to be a difference between Electron in node mode an node itself.

@MarshallOfSound:
I also tried with a simple test.js script containing a Buffer instantiation, and it also works for me.

But why is it not working for pm2 ? As i said, with standard nodejs it works ...
I don't know how to create a minimal test out of it.

**Comment by dattn** [comment]
That was also my first idea, But the Buffer API is only deprecated in Node 8.x and changed in Node 10.x.
And as i have used electron 2.x which ships with Node 8, this can not be the problem. 
I also tried to run the script directly with node (not electron), the code works without problem.
So there needs to be a difference between Electron in node mode an node itself.

@MarshallOfSound:
I also tried with a simple test.js script containing a Buffer instantiation, and it also works for me.

But why is it not working for pm2 ? As i said, with standard nodejs it works ...
I don't know how to create a minimal test out of it.

**Comment by dattn** [comment]
@KoenLav:
That was also my first idea. But in Node 8.x the buffer API has only been deprecated. And starting with Node 10 the api has changed. And as I have used Electron 2.x which ships with Node 8.x, this should work.
Also i have tried to run the script directly with node 8, and there it worked without error. So, there must be a difference between electron in node mode and node itself.

@MarshallOfSound:
I also did a test with a simple test file, containing only an instantiation of Buffer, and it worked as expected, without error. But why is it not working for the PM2 package ? As i said, with standard node js it works as exprected.

I don't know how to create a minimal test, as i don't know/understand where the problem comes from.

**Comment by dattn** [comment]
@KoenLav:
That was also my first idea. But in Node 8.x the buffer API has only been deprecated. And starting with Node 10 the api has changed. And as I have used Electron 2.x which ships with Node 8.x, this should work.
Also i have tried to run the script directly with node 8, and there it worked without error. So, there must be a difference between electron in node mode and node itself.

@MarshallOfSound:
I also did a test with a simple test file, containing only an instantiation of Buffer, and it worked as expected, without error. But why is it not working for the PM2 package ? As i said, with standard node js it works as exprected.

I don't know how to create a minimal test, as i don't know/understand where the problem comes from.

**Comment by dattn** [comment]
@KoenLav:
That was also my first idea. But in Node 8.x the buffer API has only been deprecated. And starting with Node 10 the api has changed. And as I have used Electron 2.x which ships with Node 8.x, this should work.
Also i have tried to run the script directly with node 8, and there it worked without error. So, there must be a difference between electron in node mode and node itself.

@MarshallOfSound:
I also did a test with a simple test file, containing only an instantiation of Buffer, and it worked as expected, without error. But why is it not working for the PM2 package ? As i said, with standard node js it works as exprected.

I don't know how to create a minimal test, as i don't know/understand where the problem comes from.

**Comment by dattn** [comment]
Github seems to have problems with the comments, I get error everywhere, and my comments appear and disappear randomly

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by dattn** [comment]
I tested again with the latest electron version 6.0.2, and it works now.

**Comment by sofianguy** [comment]
@dattn that's great! I'm going to close this issue, but happy to reopen the bug is still present in later versions of electron
