### ISSUE TITLE
[Electron 3+] Process stays in the background after quit if affinity is set

### ISSUE THREAD

**Issue by t57ser** [electron/electron#15244]
* Output of `node_modules/.bin/electron --version`: 3.0.4
* Operating System (Platform and Version): Windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2.0.8

**Expected Behavior**
After app.quit() is called no processes should stay running

**Actual behavior**
One process remains taking up a chunk of cpu power

**To Reproduce**
https://github.com/t57ser/electron-process-issue

**Additional Information**
This appears to only happen on windows.
It does not seem to be related only to setting the affinity, but also to loading a url containing a file path.
You can change the affinity of either BrowserWindow or BrowserView and it will work, or change the loadURL of the browserView.

**Comment by madsmarcussen** [comment]
I experience this issue with Electron version 3.0.0, 3.0.2 and 3.0.5 only when loading URLs. When loading files, it works as expected.
Electron v2.x and v4.0.0-beta4 do not have this issue, and work as expected when loading URLs.

**Comment by RyanZim** [comment]
Seems we're also experiencing this issue.

**Comment by t57ser** [comment]
I gave this another test today on various versions:
4.2.2: no issue
5.0.1: no issue
6 beta: no issue

**Comment by sofianguy** [comment]
We are no longer supporting versions earlier than v4.2.x. Please upgrade to a later version as it is reportedly fixed. Feel free to reach out if you find this is still an issue in later versions and we'll be happy to reopen
