### ISSUE TITLE
Require error when using local package of an n-api build

### ISSUE THREAD

**Issue by jruiseco** [electron/electron#15246]
I am currently trying to build an N-API c++ addon for electron.

I have successfully built the addon, and can successfully access it via .js file run from node. I have attempted to include the file into electron (electron-rebuild does correctly rebuild the package).

However, I can't seem to figure out how to get the require to work. I know that require(./) references the node_modules folder. However, I can't seem to figure out what combination of paths will correctly get to the testaddon.node file.

https://medium.com/@atulanand94/beginners-guide-to-writing-nodejs-addons-using-c-and-n-api-node-addon-api-9b3b718a9a7f

I confirmed that it works (as per the direction on the guide) and included into my electron package as follows.

{
  "name": "mtest",
  "version": "1.0.7",
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  },
  "devDependencies": {
    "dxf-parser": "0.4.8",
    "electron": "^3.0.4",
    "electron-rebuild": "^1.8.2"
  },
  "dependencies": {
    "dxf-parser": "0.4.8",
    "electron-updater": "^3.1.2",
    "node-fetch": "^2.2.0",
    "node-gyp": "^3.8.0",
    "node-machine-id": "^1.1.10",
    "pdfmake": "^0.1.38",
    "smalltalk": "^2.5.1",
    "squirrel": "^1.0.0",
    "windows-build-tools": "^5.0.0",
    "xlsx": "^0.14.0",
    "xml2js": "^0.4.19",
    "xmlbuilder": "^4.2.1",
    "test-addon": "file: correct file path"
  },
  "cwd": "${workspaceRoot}",
  "webRoot": "${workspaceRoot}"
}

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
