### ISSUE TITLE
GUI drawing error/overlap

### ISSUE THREAD

**Issue by crw-xiix** [electron/electron#15250]
When Signal (v1.16.3) (Electron App) is open, and I switch to another app, it leaves part of the display up.  The other app that it happens to the most is Mozilla Thunderbird.  It has also happened with Chrome or Visual Studio.

Image:

![signalerror](https://user-images.githubusercontent.com/9369147/47170149-36351a80-d2ba-11e8-9cb2-bbb9d7a99c4c.png)

I blurred out the personal info on there.

Windows 7 Professional computer

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you've responded, please link to the test case and @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
