### ISSUE TITLE
Npm install at 2 to 3 Ko/s

### ISSUE THREAD

**Issue by crashbdx** [electron/electron#15277]
* Output of `node_modules/.bin/electron --version`: cant install
* Operating System (Platform and Version):
Windows 10

Impossible to install package, npm install electron -g try to dowanload the package at 2 to 3 Ko/sec... So its not moving forward :(

Tried watch streaming videos on different websites, tried install other packages too, my connexion work properly... Any idea?

**Comment by ckerr** [comment]
`npm install electron -g` is working for me here.

Most likely answer is the npm archives had an issue while were trying to install. That was 7 hours ago -- are you still seeing this behavior?

At any rate, this sounds less like an Electron issue than an issue of _obtaining_ Electron through npm. If the problem persists, you may want to contact them for support.
