### ISSUE TITLE
navigator.language return '' (tested on Windows 10)

### ISSUE THREAD

**Issue by jaehayoo** [electron/electron#15279]
* Output of `node_modules/.bin/electron --version`: 3.0.4
* Operating System (Platform and Version): Windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2.0.11

**Expected Behavior**
navigator.language return os language. ('eng', 'kr'... )

**Actual behavior**
navigator.language return ''

**To Reproduce**
you can check value of navogator.language by console.log.

**Comment by jaehayoo** [comment]
I have checked that there is no problem on v3.0.5.
navigator.language return well the language of OS.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
