### ISSUE TITLE
Mouse events aren’t dispatched to <webview> hosts

### ISSUE THREAD

**Issue by javan** [electron/electron#15289]
* Electron Version: 3.0.5
* Last known working Electron version: 2.0.12
* Operating System: macOS 10.13.6

**Expected Behavior**
* Mouse events like `wheel` and `mousemove` should be dispatched to the host when the mouse is over a `<webview>`.

**Actual behavior**
* Electron 3: `wheel` is never dispatched. `mousemove` is only dispatched once when entering the window. 👎
* Electron 2: `wheel` and `mousemove` are dispatched continuously (normally). 👍

**To Reproduce**
* Clone and run https://github.com/javan/electron-quick-start/tree/mouse-event-webview-bug
* Move the mouse around
* Two-finger scroll using a trackpad on a mac
* Note the event counts in the upper-left info panel

```sh
$ git clone https://github.com/javan/electron-quick-start.git -b mouse-event-webview-bug
$ npm install
$ npm start
```

**Screenshots**

**Electron 3 👎**
![mouse-events-electron-3](https://user-images.githubusercontent.com/5355/47228794-1c680600-d394-11e8-86c4-c0de9fc0d5c7.gif)

**Electron 2 👍**
![mouse-events-electron-2](https://user-images.githubusercontent.com/5355/47228823-2e49a900-d394-11e8-843c-bbfa12d701c3.gif)

**Additional Information**
We rely on the `wheel` event in particular to implement two-finger swipe navigation in the Basecamp 3 app, and noticed this issue while upgrading from Electron 2 to 3.
![basecamp-3-swipe-navigation](https://user-images.githubusercontent.com/5355/47229168-1a527700-d395-11e8-841f-e0fbcf809849.gif)

**Comment by zikosichi** [comment]
Same problem here. Host scroll is blocked when the cursor is on top of the webview. For me, this happens only when the cursor is on top of scroll area inside the webview

**Comment by MarshallOfSound** [comment]
I have a feeling this is the same underlying isssue as https://github.com/electron/electron/issues/14905

cc @zcbenz 

You could probably work around this yourself by proxying the event with IPC and calling `document.dispatchEvent`

**Comment by MarshallOfSound** [comment]
@zikosichi Yes

**Comment by zcbenz** [comment]
Yeah this is caused by Chromium switching webview tag to use iframe, more details can be found at https://github.com/electron/electron/issues/14258#issuecomment-416794070, this is something that we can not fix due to Chromium's architecture change.

**Comment by zikosichi** [comment]
Does anyone have an example how to achieve this?
