### ISSUE TITLE
Support Chromium's --unsafely-treat-insecure-origin-as-secure

### ISSUE THREAD

**Issue by cachius** [electron/electron#15298]
I want to send Notifications from a HTTP URL what Chrome considers an insecure origin since v66.
This means I can't use the HTML5 Notification API without workarounds.

The most straight forward approach seems to be to support Chromium's --unsafely-treat-insecure-origin-as-secure command-line switch. This could be given via a special webPreferences option or its general 'additionalArguments'.

Right nowI use an additional transparent window and IPC to trigger Notifications there and to react to clicks on them back in the 'insecure origin' window, which is quite an overhead for that purpose.
Another option would be a 'localhost' proxy, which would be even more overhead through doubling every request made to that site.
I also tried window.loadFile() with an iframe loading my site, but I couldn't transfer the exposed API functions from the preload script to it via postMessage().
Furthermore I tried webFrame.registerURLSchemeAsPrivileged() and protocol.registerHttpProtocol/registerStandardSchemes without success.

Relevant Chromium dev posts are https://goo.gl/rStTGz and https://goo.gl/Y0ZkNV, which are given in the console after using new Notification('test') and navigator.mediaDevices.getUserMedia({video:true}).
Also access to Geolocation, Device motion / orientation, EME, getUserMedia, AppCache is restricted on such origins and would be affected by this. Providing an easy way to make those features available on a HTTP site would benefit electon's usefulness for intranet projects a lot.

**Comment by MarshallOfSound** [comment]
We have a `app.commandLine.appendSwitch` API you can use to enable the `--unsafely-treat-insecure-origin-as-secure` switch

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by cachius** [comment]
Alas, the switch is not supported. It is neither included in the [list of supported switches](https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md), nor is it working when appended via `app.commandLine.appendSwitch('unsafely-treat-insecure-origin-as-secure', 'http://192.168.0.2')`.

**Comment by cachius** [comment]
Dear MarshallOfSound and of Closing issues fast, please open this issue again. Your proposed solution is not working, did you even try? That's why I oppened this request, to make your solution, or any other of the same simplicity and straightforwardness work! It'd be a huge win for electron and I guess not too hard to implement since Chromium already supports it and it seems to get lost only in the process of Electron integration.

**Comment by qengli** [comment]
I have the same issue , app.commandLine.appendSwitch('unsafely-treat-insecure-origin-as-secure', 'http://...') not work.

**Comment by lqygo123** [comment]
i have the some issue as well, please reopen this issue again

**Comment by luffyzhao** [comment]
i have the some issue as well, please reopen this issue again

**Comment by jiulvren** [comment]
i have the some issue as well, please reopen this issue again

**Comment by zenHeart** [comment]
i have the some issue as well, please reopen this issue again

**Comment by redders6600** [comment]
@MarshallOfSound - please re-open this issue as the command line switch doesn't work.

**Comment by cadesalaberry** [comment]
I reproduced the issue in a sandbox with cypress: https://github.com/cadesalaberry/webcam-tests

**Comment by Lumca** [comment]
This issue is still existing. app.commandLine.appendSwitch doesnt work.

**Comment by cker321** [comment]
This issue is still existing. app.commandLine.appendSwitch doesnt work.

**Comment by shennan** [comment]
@MarshallOfSound Could we re-open this issue? The proposed solution doesn't work so I believe this could be classed as a bug. 🐞

**Comment by kaedwen** [comment]
Same here. I don't get the problem why we can not handle everything not known to electron to the renderer process as arguments. Why it is not implemented that way?

**Comment by cachius** [comment]
For completeness: This was reopened as issue https://github.com/electron/electron/issues/15448 on Oct 29, 2018 and finally fixed in PR https://github.com/electron/electron/pull/33189 on Mar 9, 2022.
