### ISSUE TITLE
make: app.requestSingleInstanceLock() compatible with sandboxing

### ISSUE THREAD

**Issue by jonathon-love** [electron/electron#15304]
at the moment, `app.requestSingleInstanceLock()` works by writing files/symlinks to `/tmp`. this doesn't work when running in a sandbox (like when one's app is distributed as a flatpak).

in order for it to work in a flatpak, you have to give the flatpak app access to the `/tmp` directory, which is undermining the purpose of the sandboxing.

a solution to this might be to have an option where the developer can specify the path for the files/symlinks. by adjusting that path, sandboxes can be configured to only need to share access to that path

with thanks

**Comment by jonathon-love** [comment]
Alternatively, the files/symlinks could be written to `$XDG_RUNTIME_DIR/$APP_ID/`

**Comment by ckerr** [comment]
This is coming from Chromium. Without any code changes, this can be overridden by setting `TMPDIR` if that doesn't break anything else for your use case --

[ProcessSingleton](
https://cs.chromium.org/chromium/src/chrome/browser/process_singleton.h?q=ProcessSingleton&sq=package:chromium&dr=CSs&l=219) has a socket_dir_ where this path is set. That uses a `ScopedTempDir` which has [this code](https://cs.chromium.org/chromium/src/base/files/scoped_temp_dir.cc?type=cs&q=ScopedTempDir::CreateUniqueTempDir&g=0&l=26):
```cc
bool ScopedTempDir::CreateUniqueTempDir() {
  if (!path_.empty())
    return false;

  // This "scoped_dir" prefix is only used on Windows and serves as a template
  // for the unique name.
  if (!base::CreateNewTempDirectory(kScopedDirPrefix, &path_))
    return false;

  return true;
}
```

So we're down to `base::CreateNewTempDirectory()`, [whose implementation](https://cs.chromium.org/chromium/src/base/files/file_util_posix.cc?type=cs&g=0&l=693) calls `GetTempDir()`:

```cc
bool CreateNewTempDirectory(const FilePath::StringType& prefix,
                            FilePath* new_temp_path) {
  FilePath tmpdir;
  if (!GetTempDir(&tmpdir))
    return false;

  return CreateTemporaryDirInDirImpl(tmpdir, TempFileName(), new_temp_path);
}
```

and that, at last, is implemented [like this](https://cs.chromium.org/chromium/src/base/files/file_util_posix.cc?type=cs&g=0&l=589) (for non-Mac):

```cc
#if !defined(OS_MACOSX)
// This is implemented in file_util_mac.mm for Mac.
bool GetTempDir(FilePath* path) {
  const char* tmp = getenv("TMPDIR");
  if (tmp) {
    *path = FilePath(tmp);
    return true;
  }

#if defined(OS_ANDROID)
  return PathService::Get(DIR_CACHE, path);
#else
  *path = FilePath("/tmp");
  return true;
#endif
}
#endif  // !defined(OS_MACOSX)
```

So, setting `TMPDIR` to `$XDG_RUNTIME_DIR/$APP_ID/` might do the trick without any code changes.

I think it would be OK to patch this in Electron as a short-term workaround, but @jonathon-love could you also report this upstream to Chromium? Ultimately that's the proper level for this fix IMO.

**Comment by jonathon-love** [comment]
> So, setting TMPDIR to $XDG_RUNTIME_DIR/$APP_ID/ might do the trick without any code changes.

yes, you're quite right. i thought i'd tried this, but apparently i hadn't.

i'll report to chromium.

with thanks

**Comment by ckerr** [comment]
Good to hear. Since the `TMPDIR` workaround is working for you in the short term, I think it's better to close this and let Electron pick up the changes via Chromium updates.

If I've misunderstood you and changes are still useful in Electron's code, please let me know.

**Comment by steffanhalv** [comment]
@jonathon-love Do you have url for issue reported to chromium?

**Comment by jonathon-love** [comment]
sorry, i didn't get around to it.

**Comment by jonathon-love** [comment]
i don't use `electron-packager` sorry. but you could try something like this:

`start.sh`:

```
#! /bin/sh

TMPDIR=$XDG_RUNTIME_DIR/$APP_ID/
path/to/electron-executable
```

but i don't know how well this fits in with the `electron-packager` approach.

cheers
