### ISSUE TITLE
App opens as visible even if openAsHidden set to true

### ISSUE THREAD

**Issue by SilencerWeb** [electron/electron#15309]
* Output of `node_modules/.bin/electron --version`: v3.0.5
* Operating System (Platform and Version): macOS 10.13.6

**Expected Behavior**
When I'm setting `openAsHidden` to `true` by calling `app.setLoginItemSettings({ openAsHidden: true })` I expect that my app will be launched on login as hidden.

**Actual behavior**
But when my app launches on login, all its windows are visible. I even checked preferences, "Hide" checkbox is checked.

![image](https://user-images.githubusercontent.com/20713191/47263988-35a0bc00-d526-11e8-9b44-672bfb54755f.png)

Here is how I create my window:
```js
  const mainWindow = new BrowserWindow({
    width: 1200,
    minWidth: 1200,
    height: 700,
    minHeight: 700,
    title: 'Taggy',
  });
```

**To Reproduce**
Create an application, add code for creating a BrowserWindow, call `app.setLoginItemSettings({ openAtLogin: true, openAsHidden: true })`, reboot your computer.

**Comment by MarshallOfSound** [comment]
@SilencerWeb You have to implement this yourself using `getLoginItemSettings().wasOpenedAsHidden`

https://electronjs.org/docs/api/app#appgetloginitemsettingsoptions-macos-windows

**Comment by SilencerWeb** [comment]
@MarshallOfSound but how can I check app opens on login or not? I need to open it as hidden only on login but if user opens it by himself, app should be visible

**Comment by MarshallOfSound** [comment]
@SilencerWeb That same API has a `wasOpenedAtLogin` property

**Comment by SilencerWeb** [comment]
@MarshallOfSound I think you need to explain better how it works in your docs. Now I understand that when my app launches `wasOpenedAtLogin` is set to `true` and whenever I quit it and open again, it is always `true`. Am I right? Or it will be set to `false` once I quit it and open again after it launches on login?
