### ISSUE TITLE
Alert Box showing broken icon image

### ISSUE THREAD

**Issue by stagefright5** [electron/electron#15317]
* Output of `node_modules/.bin/electron --version`: v2.0.5
* Operating System (Platform and Version): Ubuntu 18.04LTS

### Expected behavior

alert box should show the app Icon.

### Actual behavior

alert box is showing no icon even though an app icon is set.
![screenshot from 2018-10-22 18-46-46](https://user-images.githubusercontent.com/15051871/47294523-f5773180-d62a-11e8-9a47-6a62bebd4a1d.png)

### How to reproduce
* Open any electron app in debug mode (or run the app directly from the source).
* in the developer console, type `alert('some_string')`
* A dialog box appears with 'some_string' in it and a placeholder for the icon instead of the icon itself.
Refer the image above.

**Comment by stagefright5** [comment]
@ckerr , one more thing I would like to clarify is that, in our application,  "alert()" is being called by a server side page which does not have access to any of electron's methods.

**Comment by MarshallOfSound** [comment]
@stagefright5 They both go down the same code both (`alert` and the `dialog` module)

https://github.com/electron/electron/blob/master/atom/browser/atom_javascript_dialog_manager.cc#L78-L84
