### ISSUE TITLE
[3.0] Input focus feedback lost after reloading webview

### ISSUE THREAD

**Issue by magne4000** [electron/electron#15318]
* Output of `node_modules/.bin/electron --version`: v3.0.5
* Operating System (Platform and Version): MacOS 10.14
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v2.x

**Expected Behavior**
After reloading webview, focusing an input should be visible

**Actual behavior**
Before reloading webview:
  - clicking inside/outside the input show/hide the outline around the input
After reloading webview:
  - clicking inside the input doesn't the outline anymore
  - If I focus another Application, and get back to Electron, it is not broke anymore

**To Reproduce**
```sh
$ git clone https://github.com/magne4000/electron-quick-start.git -b bug/reload-focus-feedback
$ npm install
$ npm start || electron .
```

**Screenshots**
#### outline is visible
![image](https://user-images.githubusercontent.com/1098371/47295357-c7382880-d60f-11e8-9006-4b756a0dd201.png)

#### outline is not visible
![image](https://user-images.githubusercontent.com/1098371/47295494-0d8d8780-d610-11e8-9980-bee7a4afdfcc.png)

**Comment by javan** [comment]
Pretty sure this is the same issue as https://github.com/electron/electron/issues/14474 (https://github.com/electron/electron/issues/14474#issuecomment-425794480 works around it, for me).

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by magne4000** [comment]
Closing in favor of #14474
