### ISSUE TITLE
fs.stat - should work with options parameter

### ISSUE THREAD

**Issue by rotemgrim** [electron/electron#15314]
* Output of `node_modules/.bin/electron --version`: v4.0.0-nightly.20181010
* Operating System (Platform and Version): Windows 64

process.versions: 
```
{
  http_parser: '2.8.0',
  node: '10.11.0',
  v8: '6.9.427.24',
  uv: '1.23.0',
  zlib: '1.2.11',
  ares: '1.14.0',
  modules: '64',
  nghttp2: '1.33.0',
  napi: '3',
  openssl: '1.1.0',
  electron: '4.0.0-nightly.20181010',
  chrome: '69.0.3497.106',
  icu: '62.1',
  unicode: '11.0',
  cldr: '33.1',
  tz: '2018e' 
}
```

**Expected Behavior**

fs.stat should work with options parameter.

As of node.js version 10.5.0 fs.stat should support 3 parameters (new options parameter for bigint)
like so:  fs.stat(path[, options], callback)

you can see the docs here: 
https://nodejs.org/docs/latest-v10.x/api/fs.html#fs_fs_stat_path_options_callback

Im using electron v4.0.0.beta-4 with node 10.11.0 (as you can see above in versions)

**Actual behavior**

 Calling fs.stat with options parameter fails with error:
```
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeStatsCallback (fs.js:150:11)
    at stat (fs.js:797:14)
    at Object.fs.stat (ELECTRON_ASAR.js:289:27)
    at App.createWindow (C:\projects\electron-quick-start\main.js:11:6)
    at App.emit (events.js:187:15)
```

**To Reproduce**

1. clone the electron-quick-start repo
2. update electron to latest beta version
3. paste this code in main.js inside the function createWindow():

```javascript
fs.stat("pathToSomeFile", {bigint: true}, (err, stats) => {
    if (err) {
      console.log(err);
    } else {
      console.log(stats);
    }
});
```

4. run the app

**Comment by MarshallOfSound** [comment]
Refs: https://github.com/electron/electron/blob/master/lib/common/asar.js#L278-L293

**Comment by DovAmir** [comment]
+1
