### ISSUE TITLE
Windows support for `systemPreferences.isDarkMode()` API

### ISSUE THREAD

**Issue by caesar** [electron/electron#15316]
**Is your feature request related to a problem? Please describe.**
Electron has an API which works on macOS for detecting when the system is in Dark Mode.
[Windows 10 also has a dark mode setting](https://www.digitaltrends.com/computing/how-to-enable-dark-mode-in-windows-10/). It would be useful if the same Electron API also worked on Windows.

**Describe the solution you'd like**
1. The `systemPreferences.isDarkMode()` method should work on Windows.
2. Ideally a way of subscribing to change events, equivalent to `systemPreferences.subscribeNotification('AppleInterfaceThemeChangedNotification', callback)`. Or perhaps the `color-changed` event (or another event) would be fired by `systemPreferences`.

**Additional context**
On Windows the state of the dark mode setting [is stored in the](https://stackoverflow.com/a/51336913/365069) `HKCU(HKLM)\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize\AppsUseLightTheme` registry key.

**Comment by caesar** [comment]
Also, I guess it would be sensible if `systemPreferences.isInvertedColorScheme()` returned `true` in dark mode, since it *is* an inverted colour scheme in the sense that it is light-on-dark.

**Comment by southsea0725** [comment]
I'm sure  key 'AppsUseLightTheme' exists and value 1
HKCU(HKLM)\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize\AppsUseLightTheme

But darkmode NOT enabled,  windows 10

**Comment by mvbn** [comment]
@southsea0725 the key must exist and the value must be 0 to activate the dark mode in windows 10

**Comment by southsea0725** [comment]
Yeah, now it's 0, but NOT work too.

**Comment by mvbn** [comment]
The key must be of type DWORD. It should activate dark mode in Windows 10, but the electron function is only for macOS.

**Comment by Pettor** [comment]
Any progress on this issue? Since 1903 is released soon with light theme it will be useful to have a function to get the settings. 

As noted before `HKCU(HKLM)\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize\AppsUseLightTheme` is being referenced as the key to check and on my 1903 build it works correctly when switching between the light and dark settings theme.

**Comment by Mr1008** [comment]
Any update on this guys?
