### ISSUE TITLE
CSP header setting of sample code is incorrect

### ISSUE THREAD

**Issue by masatokinugawa** [electron/electron#15310]
A CSP header setting described in [security.md](https://github.com/electron/electron/blob/9262731f2cc991d9ba97e0e977007e0f39da4983/docs/tutorial/security.md#csp-http-header) is incorrect. It does not actually emit the CSP header. 

**Current Code:**
```js
const { session } = require('electron')

session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
  callback({ responseHeaders: `default-src 'none'` })
})
```

**Proposed Fix:**
```js
const { session } = require('electron')

session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
  callback({
    responseHeaders: {
      ...details.responseHeaders,
      "Content-Security-Policy": ["default-src 'none'"]
    }
  })
})
```

**Comment by MarshallOfSound** [comment]
PRs welcome are welcome 😄 🎉

**Comment by sindresorhus** [comment]
FYI, this was already reported in the original PR and ignored. https://github.com/electron/electron/pull/13167#discussion_r196660211
