### ISSUE TITLE
A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by GJune** [electron/electron#15334]
I try to make a custom build of electron and chromium, and my environment is as follows:
Electron source code: branch 2-0-x,  Oct 16, 2018 , fbc7b7f 
Operating System: Windows 10 Pro x64
Visual Studio version: 2015 update 3
Windows SDKs : Windows 10
 
**Expected Behavior**
My electron app should run to succeed

**Actual behavior**
My app depends on a native node module (robotjs), it can't run with my custom build of electron. If i don't require this module, everything is ok.
Error Message:

> Uncaught Error: A dynamic link library (DLL) initialization routine failed.
> \\?\C:\Users\abc\code\app\node_modules\robotjs\build\Release\robotjs.node
>     at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
>     at Object.Module._extensions..node (module.js:671:18)
>     at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
>     at Module.load (module.js:561:32)
>     at tryModuleLoad (module.js:504:12)
>     at Function.Module._load (module.js:496:3)
>     at Module.require (module.js:586:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (C:\Users\abc\code\app\node_modules\robotjs\index.js:1:170)
>     at Object.<anonymous> (C:\Users\abc\code\app\node_modules\robotjs\index.js:38:3)
> 

**To Reproduce**
1. clone branch 2-0-x source code
2. build electron and chromium. follow the doc https://github.com/electron/electron/blob/2-0-x/docs/development/chromium-development.md
run:
  `cd electron`
  `python ./script/bootstrap.py -d --build_debug_libcc`
  `python ./script/build.py -c D --libcc`
3. rebuild node modules. follow the doc https://electronjs.org/docs/tutorial/using-native-node-modules#manually-building-for-a-custom-build-of-electron
run:
  `cd my-electron-app `
  `npm rebuild --nodedir=$HOME/.../path/to/electron/vendor/node`
4. start app, run:
  `cd electron`
  `.\out\D\electron.exe my-electron-app` 

**Additional Information**
My app worked very well with electron-2.0.x installed by npm

**Comment by MarshallOfSound** [comment]
@GJune You can't build native modules against a debug build of Electron.  Build with `python script/build.py -c R` if you want to support that
