### ISSUE TITLE
Windows: background color on window does not apply when window opens, only shortly after

### ISSUE THREAD

**Issue by bpasero** [electron/electron#15335]
* Output of `node_modules/.bin/electron --version`: 2.0.x
* Operating System (Platform and Version): Windows 10

**Expected Behavior**
Setting a background color should show it without flashing.

**Actual behavior**
The window opens with a white background and then shows my background color. Even when using `ready-to-show` there is still flicker. 

**To Reproduce**
Run this code:

```js
// Modules to control application life and create native browser window
const {app, BrowserWindow} = require('electron')

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
let mainWindow

function createWindow () {
  // Create the browser window.
  mainWindow = new BrowserWindow({width: 800, height: 600, backgroundColor: '#ff0000'})

  // and load the index.html of the app.
  mainWindow.loadFile('index.html')

  // Open the DevTools.
  // mainWindow.webContents.openDevTools()

  // Emitted when the window is closed.
  mainWindow.on('closed', function () {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null
  })

  // Even with this code it still flickers
  // mainWindow.on('ready-to-show', () => mainWindow.show());
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow)

// Quit when all windows are closed.
app.on('window-all-closed', function () {
  // On OS X it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', function () {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (mainWindow === null) {
    createWindow()
  }
})

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.
```

**Comment by MarshallOfSound** [comment]
> 2.0.x

Can we get the patch version here, and does the same thing occur in `3.0` or `4.0`?

**Comment by bpasero** [comment]
@MarshallOfSound reproduces with latest 2.0.12 (as well as 2.0.7) and 3.0.5 (using Electron Fiddle). That commit you reference looks fishy yeah.

**Comment by bpasero** [comment]
@zcbenz yeah I remember this was working fine, maybe with 1.7.x or before.

**Comment by bpasero** [comment]
@MarshallOfSound https://github.com/electron/electron/commit/092796f5f4205aa85195e62dd4fc0cedf1d6e452 came only into 2.0.12 it seems but VSCode is running with 2.0.11 where I also see it.

**Comment by zcbenz** [comment]
I have tried to replace all hardcoded white background with some other color in `cc/`, `gpu/`, `components/viz`, `ui/` and `content/browser`, but the white flash is still there.

I'm sure this is something caused by GPU acceleration, but there are probably a hundred places that may affect the background color, and I can not find it. I'm giving up on this issue.

**Comment by CopyNippyJoin** [comment]
As a workaround using `setSize` after initializing the window with width/height = 0 works for me (electron 4, win 10), e.g.:

```javascript
var testWindow = new BrowserWindow(
{
	'x': 0
	'y': 0
	'width': 0,
	'height': 0
});
testWindow.setSize(800,600);
testWindow.loadURL("https://www.google.com/");
```
This also does fix some wrong height init issue for me.

**Comment by sofianguy** [comment]
@bpasero is this bug still present in version 4.x or later?

**Comment by bpasero** [comment]
Seems to be OK when using show: false in combination with `mainWindow.on('ready-to-show', () => mainWindow.show());`
