### ISSUE TITLE
Electron Mac app fails for the notarization process because it missed the 'runtime' flag during codesign for the Helper App

### ISSUE THREAD

**Issue by poojas2288** [electron/electron#15331]
Hello team

I have created a Mac app using electron framework (electron-packager) and embedded it within my another Mac app (non-electron).

I have already added sandbox entitlement in my electron mac app.

I'm trying to get our non-AppStore version of my main app through Apples notarization.

It fails for the notarization process (https://help.apple.com/xcode/mac/current/#/dev88332a81e)
because it missed the 'runtime' flag during codesign for the Helper App.

Therefore I need to create a Mac app which : 
1. is compatible with app store submission
2. can be signed as runtime (seems to be equal to hardened runtime : https://help.apple.com/xcode/mac/current/#/devf87a2ac8f) for non-AppStore submission and notarization.

Help would be appreciated.

Thanka
Pooja

**Comment by MarshallOfSound** [comment]
@poojas2288 Please do not make duplicate issues across repos, it just takes up maintainer time

🔗 https://github.com/electron-userland/electron-packager/issues/898
