### ISSUE TITLE
electron ignores the --ignore-gpu-blacklist flag in versions above 1.6.16

### ISSUE THREAD

**Issue by DandroidDeveloper** [electron/electron#15339]
I have an app that is backwards compatible to some older GPU's, both linux and windows, and I usually can get webgl to run in my electron apps with the command line flag --ignore-gpu-blacklist. This is fine because my apps do not connect to the internet so there is no security risk. With the newest version it seems as if electron is ignoring that flag. When I launch my apps they all throw the 'webgl cannot find extension' error which is generally associated with not being able to read the GPU info. WebGL works in the browsers on these machines. I don't know the linux GPU off the top of my head but the windows one is some integrated intel gpu.

**Comment by nornagon** [comment]
Unfortunately it's difficult for us to determine what might be happening without a repro. If possible, could you compile an example app that exhibits the issue you're describing, possibly based on [electron-quick-start](/electron/electron-quick-start) or using [electron-fiddle](/electron/fiddle)?

**Comment by nornagon** [comment]
Also, what version are you using?

**Comment by DandroidDeveloper** [comment]
It is electron version 3.0.2. This demo code completely ignores the command line switch to ignore gpu blacklist on these older GPU's (most likely blacklisted). I poked around and found that if I add the call directly, ex. 'electron . --ignore-gpu-blacklist' it works correctly. 


process.env.ELECTRON_DISABLE_SECURITY_WARNINGS = true;

const { BrowserWindow, app, Menu } = require('electron');
const path = require('path');
const url = require('url');

const main = {
  window:null
}

const open = () => {

  const menuArray = [
    {
      label: 'Settings',
      submenu: [
        {
          id:1,
          label: 'Debug',
          type: 'checkbox',
          checked: false,
          click: (item) => {
            if (item.checked) {
              main.window.webContents.openDevTools();
            }
            else {
              main.window.webContents.closeDevTools();
            }
          }
        }
      ],
    }
  ];

  const menu = Menu.buildFromTemplate(menuArray);

  main.window = new BrowserWindow({
    show:false,
    webgl: true,
    backgroundThrottling: true,
    webPreferences: {
      nodeIntegrationInWorker: true
    },
    width: 1080,
    height: 720,
    title: 'mk40',
    backgroundColor:'#000000',
  });

  main.window.loadURL(url.format({
    pathname: path.join(__dirname, 'index.html'),
    protocol: 'file',
    slashes: true
  }));

  main.window.on('closed', () => {
    main.window = null;
  });

  main.window.on('ready-to-show', () => {
    main.window.show();
    main.window.setMenu(menu);
  })

  main.window.webContents.on('did-finish-load', () => {
    console.log('finished loading...')
  });

}

app.on('ready', open);

app.commandLine.appendSwitch('ignore-gpu-blacklist');
app.on('window-all-closed', () => {
  app.quit();
});

**Comment by DandroidDeveloper** [comment]
I apologize for the lack of information by the way, I know issues with chromium flags and GPU's are always a pain. Probably hard to reproduce on your end too without a blacklisted gpu lying around lol

**Comment by nornagon** [comment]
Am I right in saying that:

1. You're seeing 'webgl cannot find extension' errors when you launch your app.
2. Those errors do not go away when you add a call to `app.commandLine.appendSwitch('ignore-gpu-blacklist')` during initialization of your main process.
3. The errors _do_ go away when you add `--ignore-gpu-blacklist` when launching the app.
4. The errors did not present themselves in Electron 2.0.x.

Can you open `about:gpu` in Chrome and paste the contents (using the `Copy report to clipboard` button at the top) into a gist?

**Comment by nornagon** [comment]
From the dump from Chrome, it looks like Chrome is rendering entirely through software, using SwiftShader, not your GPU hardware. The same code you're trying in Electron works in Chrome, or do you mean other WebGL apps? It's possible the extension you're trying to use isn't supported by Chrome's software renderer.

**Comment by DandroidDeveloper** [comment]
the same code runs in chrome. 

Additionally the same code runs in electron versions 2.0.0 and 1.6.16.

**Comment by DandroidDeveloper** [comment]
Usually the ERROR version of 'cannot find extensions' happens when chrome can't even detect your gpu or if your gpu is blacklisted. Generally if it cannot detect an extension it just throws a warning, atleast that is what I have seen, not a chrome expert lol

**Comment by DandroidDeveloper** [comment]
Does electron specifically disable any chrome commandline flags? And if so would you possibly know where that code is in electron's source?

**Comment by nornagon** [comment]
No, we don't intentionally disable any Chromium flags. It's possible we accidentally prevent them from working though 😅

**Comment by DandroidDeveloper** [comment]
lol not a bug its a feature

**Comment by DandroidDeveloper** [comment]
2.0.4 has the same problem.

**Comment by VishwasShashidhar** [comment]
Ya, same problem for us too. Typically happens when running Electron on large monitors or on VDI environments.

@nornagon Does that help the repro case?

**Comment by nornagon** [comment]
@VishwasShashidhar are you also seeing this problem with electron 2.0.4? That could help us to track down the root cause, if it was something introduced between electron 2.0.0 and 2.0.4 then that's a lot fewer things to investigate than between 2.0.0 and 3.0.0 😅

**Comment by VishwasShashidhar** [comment]
@nornagon No, we aren't seeing this with 2.0.4 (or for that matter 2.0.13). It's only with the 3.x.y & 4.x.y versions. I suspect this is something upstream on Chromium that's changed. 

But, still confused as to how Chrome works which shouldn't unless Google is using some proprietary code for Chrome.

Please let me know if you want us to run any other tests.

Here's the GPU status for 2.0.13 and 3.0.0.

```
2.0.13
------
GPU Stats:  {
   "2d_canvas":"enabled",
   "checker_imaging":"disabled_off",
   "flash_3d":"enabled",
   "flash_stage3d":"enabled",
   "flash_stage3d_baseline":"enabled",
   "gpu_compositing":"enabled",
   "multiple_raster_threads":"enabled_on",
   "native_gpu_memory_buffers":"enabled",
   "rasterization":"disabled_software",
   "video_decode":"enabled",
   "video_encode":"enabled",
   "webgl":"enabled",
   "webgl2":"enabled"
}

3.0.0
-----
GPU Stats:  {
   "2d_canvas":"disabled_software",
   "checker_imaging":"disabled_off",
   "flash_3d":"disabled_software",
   "flash_stage3d":"disabled_software",
   "flash_stage3d_baseline":"disabled_software",
   "gpu_compositing":"disabled_software",
   "multiple_raster_threads":"enabled_on",
   "native_gpu_memory_buffers":"enabled",
   "rasterization":"disabled_software",
   "surface_synchronization":"enabled_on",
   "video_decode":"disabled_software",
   "webgl":"disabled_off",
   "webgl2":"disabled_off"
}

```

**Comment by nornagon** [comment]
I'm closing this as I believe the issue is resolved.
