### ISSUE TITLE
Click through Transparency 

### ISSUE THREAD

**Issue by Bijoykrishna6398** [electron/electron#15356]
I have enabled the Transparency option and  win.setIgnoreMouseEvents(true) to click through the window
but i have a button in my application. how do i click on that button while win.setIgnoreMouseEvents(true) is enabled.

![indexhtml](https://user-images.githubusercontent.com/44425176/47409231-c3c3af00-d77f-11e8-988a-bd534c8cf997.PNG)
![mainjs](https://user-images.githubusercontent.com/44425176/47409232-c3c3af00-d77f-11e8-885e-6e6d87a8252d.PNG)
![packagejson](https://user-images.githubusercontent.com/44425176/47409234-c45c4580-d77f-11e8-8c1b-1c10f18af81e.PNG)

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
