### ISSUE TITLE
Info about clipboard item source

### ISSUE THREAD

**Issue by SilencerWeb** [electron/electron#15359]
**Is your feature request related to a problem? Please describe.**
No, this feature request is not related to a problem.

**Describe the solution you'd like**
When I get a clipboard item, I want to get information about from what app this item came from.
For example, if I copy something in the Chrome and when I call `clipboard.readText()`, I would like to get copied text and app's name where it came from (Chrome).

**Describe alternatives you've considered**
Haven't found any alternatives so far.

**Additional context**

**Comment by MarshallOfSound** [comment]
@SilencerWeb Unfortunately OS APIs do not support this information so we can't provide it
