### ISSUE TITLE
Electron has lower volume than system apps

### ISSUE THREAD

**Issue by sungdzda** [electron/electron#15369]
Hello, I have been trying to integrate multimedia into my electron app. I have found that electron has a perceptibly lower volume than any other native system apps. Please advise on how to adjust the default volume to match. This seems to be a **known issue** of electron but I have not been able to find any solution for it.

To reproduce this issue, create a bare minimum electron app with an html video tag.
`<video autoplay src="vid.mp4"></video>`

1. Run index.html in your browser, and note the volume
2. Play the video through a native video player on your OS, and note the volume
3. Run the electron app, and note the volume

You will observe that cases 1 and 2 have consistent and normal volume, while in case 3 the volume is significantly lower. I have found this behaviour to be irrelavant to the autoplay policy of Chromium.

I am using Windows 64-bit and 64-bit electron binaries. I have tried versions 3.0.5 and 4 beta.

Further Investigation: After some trials, I found that some media players made with electron (such as [this one](https://electronjs.org/apps/sharp-tune)) also suffer from the exact same issue.

Please recommend some solutions or workarounds, thanks

**Comment by brenca** [comment]
I tried to reproduce this, but couldn't. Could you please check your per-app volume settings to confirm it's not that? (once the app is playing sound, it should show up in your [Volume Mixer](https://www.thewindowsclub.com/adjust-volume-for-individual-programs-windows)) I've tested this theory by lowering the volume of the app you linked, and then I tried to play a youtube video, and the volume settings persisted, which makes me think that Windows thinks all electron apps are the same in terms of audio settings.

**Comment by MarshallOfSound** [comment]
@brenca Try setting different app metadata.  E.g. an `appUserModelId`, not sure what windows uses to identify apps in the volume mixed 🤔

**Comment by sungdzda** [comment]
@brenca Thanks for your comment. I checked the volume mixer, but it looked fine. I get this volume issue on multiple Windows machines.
![da](https://user-images.githubusercontent.com/15174644/47928257-a2419080-df00-11e8-9c32-0b8abcf5e6c3.png)

**Comment by brenca** [comment]
Let's try to narrow this down then. Can you give me an example file that you played where you got lower volume than expected? I played an MP3 with VLC and the player you mentioned, and I didn't hear any major difference.
Also, what version of Windows are you using? Any info would be great, try looking for similarities between the Windows machines.

**Comment by sungdzda** [comment]
Hi, the file format doesn't matter. I have tried AAC (as in videos), MP3, and WAV files. The browser that you choose to use in step 1 also doesn't matter. Chrome, Firefox, UWP, and any other native apps all have the same volume. Electron is the only exception. I am using windows 10 pro on multiple machines with heterogeneous hardware. I usually have the latest windows updates.

Please try to use a pair of headphones, alough the difference sounds big to me, it may not be as obvious in some setups. If you can, maybe something like an oscilloscope would help to quantify the difference. Thanks for the help.

**Comment by sungdzda** [comment]
A 400Hz, -3dBFS sine wave, system volume 100%, line out, gaming laptop

416mVpp - Electron
744mVpp - potplayer 90% default startup volume
1.15Vpp - potplayer 100%
808mVpp - FF
1.088Vpp - Chrome
2.04Vpp - Edge
2.04Vpp - Groove Music

**Comment by brenca** [comment]
I tried again with headphones. Unfortunately I don't really have an oscilloscope on hand, so I'm gonna have to rely on my ears, but I really can't hear a volume difference between `electron` and `Groove Music`, and according to your measurements, it should be easy to hear with headphones. I did try with my speaker setup and with my headphones, neither reproduced the issue.
What hardware exactly are you using to test this? I'm guessing this might be a hardware related issue.

**Comment by sungdzda** [comment]
Thanks a lot for your confirmation. I am happy as long as this problem is not universal. I just tested my app on a  library computer and couldn't notice a difference. I have a lot of bulky/"professional" applications installed, and Electron is perhaps having a weird conflict with my system. Or Windows 10 may have wrongfully synched bad parameters across my computers. I think Electron would be just fine on Windows vanilla.

**Comment by billygerhard** [comment]
@sungdzda I am experiencing this same issue. I think its the same thing, some PCs its normal volume, some its very quiet. Did you ever find a resolution to this?

**Comment by sungdzda** [comment]
@billygerhard Unfortunately no. It's easier to find a workaround if you develop for kiosks or embedded systems, but it will stay an annoyance for web distributed apps.

**Comment by billygerhard** [comment]
I actually found I downloaded a different electron app, and its doing the same thing, so it seems to be a global issue with all electron apps on the system not something specific to my individual app.

**Comment by sungdzda** [comment]
@billygerhard Exactly

**Comment by billygerhard** [comment]
@sungdzda I think I found my issue. Under the sound options, you have the option to lower audio when it detects a call, mine was set to lower audio by 80%. I also had a voice mod software installed from a long time ago I tested. I removed both of these, and it seems to be playing at normal volume now.
