### ISSUE TITLE
Keyboard shortcuts on Linux with AZERTY keyboard

### ISSUE THREAD

**Issue by magne4000** [electron/electron#15362]
* Output of `node_modules/.bin/electron --version`: v3.0.5, v4.2.9
* Operating System (Platform and Version): Ubuntu 18.04
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): unknown

**Expected Behavior**
All keyboard shortcuts should act the same way in all OS and keyboard layouts.

**Actual behavior**
Some keyboard shortcuts are not working under some keyboard layouts.
![image](https://i.snag.gy/cR4kg8.jpg)
(also, wrong accelerator is shown for `CmdOrCtrl+Plus`)

**To Reproduce**
```sh
$ git clone https://github.com/magne4000/electron-quick-start.git -b bug/kbd-shortcuts-linux
$ npm install
$ npm start || electron .
```
##### Keyboard layouts with which I have issues:
- French (Macintosh) keyboard layout
![image](https://user-images.githubusercontent.com/1098371/47428678-48b8c380-d794-11e8-92e4-8a1136c1d88d.png)

- French keyboard layout
![image](https://user-images.githubusercontent.com/1098371/47428694-579f7600-d794-11e8-8d0f-119943f0b60d.png)

**Additional Information**
Here is a matrix comparing behaviour of Chromium, Firefox and Electron which each of the 2 keyboard layouts from above.

| Shortcut | Chromium/Firefox | Electron |
| ------------- | ------------- | ------------- |
| French <kbd>Ctrl+Plus</kbd> | <kbd>Ctrl+Plus</kbd> and <kbd>Ctrl+Shift+Plus</kbd> are working | only <kbd>Ctrl+Shift+Plus</kbd> works |
| French (Macintosh) <kbd>Ctrl+Plus</kbd> | <kbd>Ctrl+Plus</kbd> and <kbd>Ctrl+Shift+Plus</kbd> are working | only <kbd>Ctrl+Shift+Plus</kbd> works |
| French <kbd>Ctrl+-</kbd> | <kbd>Ctrl+-</kbd> and <kbd>Ctrl+Shift+-</kbd> are working  | **doesn't work** |
| French (Macintosh) <kbd>Ctrl+-</kbd> | <kbd>Ctrl+-</kbd> and <kbd>Ctrl+Shift+-</kbd> are working  | only <kbd>Ctrl+-</kbd> works |
| French <kbd>Ctrl+[</kbd> | (Firefox only) <kbd>Ctrl+AltGr+[</kbd> works | **doesn't work** |
| French (Macintosh) <kbd>Ctrl+[</kbd> | unknown | unknown |
| French <kbd>Ctrl+]</kbd> | (Firefox only) <kbd>Ctrl+AltGr+[</kbd> works | **doesn't work** |
| French (Macintosh) <kbd>Ctrl+]</kbd> | unknown | unknown |

Those are non exhaustive keyboard shortcuts anomalies referenced under Ubuntu 18.04.
The 3 cells in **bold** can be considered as bugs, and others can be considered as nice to have I suppose.

**Comment by sebastienserre** [comment]
Hello,
If it can help. 
I'm on Ubuntu 18.04 and in an app using Electron, ctrl+a quit the app ...

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sebastienserre** [comment]
Solved on my side

**Comment by magne4000** [comment]
Updated the issue with `electron@4.2.9`, behaviour have  not changed.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
