### ISSUE TITLE
tray.displayBalloon only works one time.

### ISSUE THREAD

**Issue by sgd2z** [electron/electron#15368]
* Output of `node_modules/.bin/electron --version`: v4.0.0-nightly.20180929
* Operating System (Platform and Version): Windows 10

**Expected Behavior**
Tray balloon notification shows up every time tray.displayBalloon is called.

**Actual behavior**
tray.displayBalloon only works one time. All future calls to displayBalloon are ignored.

**To Reproduce**
let trayIcon = new Tray(iconImage);
trayIcon.displayBalloon({ content: "test", title: "test" });
trayIcon.displayBalloon({ content: "test2", title: "test2" });
trayIcon.displayBalloon({ content: "test3", title: "test3" });

This is also unrelated to the timing. Even if you call displayBalloon after the previous ones are gone, no new ones ever pop up.

**Comment by codebytere** [comment]
What was the last working version? Please include that in the template so we can more effectively triage this issue.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by fjeddy** [comment]
You serious? You ignore this, rather serious problem simply because he isn't doing the exact debugging for you?

Everything you need he has included; but because he doesn't do part of the work to fix it for you, then you blatantly close and ignore the issue?

Surprising. `tray.displayBalloon` is useless as long as this bug remains.

**Comment by MiggyJ** [comment]
I think there can only be one displayBalloon per Tray so you need to remove it with [```tray.removeBalloon()```](https://www.electronjs.org/docs/api/tray#trayremoveballoon-windows). If you want multiple notifications, you can try it with  [Notification](https://www.electronjs.org/docs/api/notification#class-notification) class.
