### ISSUE TITLE
Allow showing multiple notifications on macOS and elsewhere perhaps

### ISSUE THREAD

**Issue by pronebird** [electron/electron#15364]
**Is your feature request related to a problem? Please describe.**
Currently showing two notifications in a row does not stack up the notifications on screen and instead the last notifications replaces the former (FIFO)

**Describe the solution you'd like**
I may be wrong, but I guess if we were able to provide the notification identifier we could distinguish between them and this way the system should allow showing multiple notifications at once.

It's possible on macOS and HTML5 API has `tag` parameter too.

Apple reference:
https://developer.apple.com/documentation/usernotifications/unnotificationrequest/1649634-identifier?language=objc

HTML5 API:
https://developer.mozilla.org/en-US/docs/Web/API/Notification/tag

**Describe alternatives you've considered**

**Additional context**

**Comment by MarshallOfSound** [comment]
Every notification on macOS already gets a unique `identifier`.  Each app can only show one notification at a time on macOS afaik.

Refs: https://github.com/electron/electron/blob/a369a4172b8d87694d57a00e92eb432fd4cb08c3/atom/browser/notifications/mac/cocoa_notification.mm#L31-L37

This is an OS limitation we can't work around, happy to be proven wrong but I've looked into this before and determined it not possible.  If someone has an idea how to do this please @ mention me in a follow up but I'm going to close this out as `wontfix` for now.

**Comment by EvanHahn-Signal** [comment]
I believe multiple concurrent notifications _are_ allowed from the same app on macOS. Three pieces of evidence for this:

1. [Apple's Human Interface Guidelines page for notifications](https://developer.apple.com/design/human-interface-guidelines/macos/system-capabilities/notifications/) shows two notifications from Reminders.
1. The notification identifier seems made to allow an app to send multiple notifications.
1. After allowing notifications in Chrome 84, the following showed two notifications on macOS 10.15:

   ```js
   new window.Notification('notification 1');
   new window.Notification('notification 2');
   ```

The following code in `main.js` did not allow multiple concurrent notifications on macOS (modified `main.js` in the [Electron quickstart][0]):

```js
const { app, Notification, BrowserWindow } = require("electron");
const path = require("path");

function createWindow() {
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
    },
  });
  mainWindow.loadFile("index.html");
}

app.whenReady().then(() => {
  createWindow();

  new Notification({
    title: "notification 1",
  }).show();

  // This should create a new notification but instead "overwrites" the existing one.
  new Notification({
    title: "notification 2",
  }).show();

  app.on("activate", function () {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});
```

This code, along with the code snippet @MarshallOfSound shared, suggests that this is a legitimate bug (if only a small one!) with Electron. Do you think it makes sense to reopen this or open a new issue?

[0]: https://github.com/electron/electron-quick-start
