### ISSUE TITLE
webview cookies are not persisted

### ISSUE THREAD

**Issue by steverandy** [electron/electron#15365]
* Output of `node_modules/.bin/electron --version`: 4.0.0-beta.5
* Operating System (Platform and Version): macOS 10.14
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): There is no issue with Electron v3.

**Expected Behavior**
Cookies should be persisted in a webview that uses partition.

**Actual behavior**
Cookies are lost after relaunching app.

**To Reproduce**
1. Create webview with partition: `<webview partition="persist:webview"/>`
2. Sign in to GitHub to create a cookie.
3. Relaunch app.
4. When webview opens again, the cookies are lost.

**Comment by alessandroliveri** [comment]
Hello! I would like to test this version can I ask if this regression will be fixed soon or if it's a minor fix and I have to wait for more? Thanks

**Comment by deepak1556** [comment]
This is regression on the chromium side between 67-69, its fixed in 70 as verified with https://github.com/electron/electron/pull/15405, I am yet to identify the fix from upstream.

**Comment by alessandroliveri** [comment]
Thank you! 😃

**Comment by Tiny-Giant** [comment]
@deepak1556 any news on this?

**Comment by alessandroliveri** [comment]
@Tiny-Giant I don't know if this can help you but I bypassed the problem with a `save in local storage` and reset the cookie on load app.

**Comment by KochiyaOcean** [comment]
@Tiny-Giant As a workaround, you can try saving cookie using `session.fromPartition('persist:barfoo').cookies.get` on exit and restore cookie using `session.fromPartition('persist:barfoo').cookies.set` on startup

**Comment by Tiny-Giant** [comment]
@Kochiya I haven't done a lot with sessions. This would just be done in the Main process correct? Or would I have to add a [partition attribute](https://electronjs.org/docs/api/webview-tag#partition) to each webview?

**Comment by KochiyaOcean** [comment]
@Tiny-Giant If partition is not set, just use `session.defaultSession.cookies`.
