### ISSUE TITLE
setIgnoreMouseEvents({forward: true}) stops forwarding after a page reload

### ISSUE THREAD

**Issue by toonvanvr** [electron/electron#15376]
* Output of `node_modules/.bin/electron --version`: 3.0.5
* Operating System (Platform and Version): Windows 10 x64

![Animated preview](https://image.ibb.co/jygP6V/bug.png)

**Expected Behavior**
`BrowserWindow.setIgnoreMouseEvents()` should keep working after refreshing the page with `CTRL + R`. 

**Actual behavior**
Running `browserWindow.setIgnoreMouseEvents({forward: true})` does not forward any events to the browserwindow after a refresh. 

**To Reproduce**
Clone from this [minimal example](https://gitlab.com/toon.vanvreckem/electron-setignoremouseevents-bug). 
```sh
electron index.js
```
**Code:**
```JavaScript
window.addEventListener('mousemove', function ( event ) {
  let el = event.target
  if (el.classList.contains('mouse') || el.classList.contains('window-handle')) {
    browserWindow.setIgnoreMouseEvents(false)
  } else {
    browserWindow.setIgnoreMouseEvents(true, {forward: true})
    // ^ this function stops forwarding after a refresh (CTRL+R)
  }
})
```

**Additional Information**
[implementation of setIgnoreMouseEvents](https://github.com/electron/electron/blob/3-0-x/atom/browser/native_window_views.cc#L843)
[implementation of SetForwardMouseMessages](https://github.com/electron/electron/blob/8dce40137c7c4f69acaae92bdcfc6dae74e45314/atom/browser/native_window_views_win.cc#L287)

**Use case**
Developer tools on the filesystem don't function well before a page refresh, but doing so breaks the app. This slows down development a lot.

**Guess:**
Maybe setIgnoreMouseEvents keeps working with a previous native window handle?

**Comment by Cobertos** [comment]
Still getting this issue. 

Electron Version: v4.2.0
Operating System: Windows 10 x64 build 17134

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by chevonc** [comment]
Seeing this as well on electorn 7.1.3 :/

**Comment by alectrocute** [comment]
Yup, I've battled this one for many months. :(

**Comment by momakes** [comment]
@chevonc @alectrocute Commenting on a closed issue doesn't help at all. Please create a new issue so it'll be reviewing for the recent versions.
