### ISSUE TITLE
webContents.print() causes margin on printed page

### ISSUE THREAD

**Issue by kadirilkimen** [electron/electron#15375]
* Output of `node_modules/.bin/electron --version`: 3.0.5
* Operating System (Platform and Version): Windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): i dont know

**Expected Behavior**
I have an html page needs to print on electron. When i print using chrome browser it works fine.
![page](https://user-images.githubusercontent.com/16637692/47457517-fd2c0700-d7df-11e8-8ab9-56473394d9f7.jpg)

**Actual behavior**
When i print on electron it adds some margin on the top and left of the page.  I tried a lot of tricks on CSS but i think it is not about css or design of the page.

Here is a simple page that prints with same margins :

`<!DOCTYPE html>
<html lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>print test for electron</title>
<style>
  body{ margin:0; padding:0; }

  @media print
    {
      body.A4{ width: 210mm;}
    }

  @page
    {
      size: A4;
      margin: 0mm;
      padding : 0mm;
    }

  .sheet
    {
      width:210mm;
      height:297mm;
      border:1px solid #000;
      page-break-after: always;
    }
</style>
</head>

<body class="A4">
  <div class="sheet">
    test<br>
    test<br>
    test<br>
  </div>
</body>
</html>`

**To Reproduce**
Create a single electron app
open the page above and call window.print() or BrowserWindow.webContents.print()
print on any printer.

Note : I am not an expert to prepare printing styles on css. But my pages prints on the chrome browser as expected.

**Comment by BeatriceThalo** [comment]
Try this in your global `styles.css` (rather than in any particular angular sub-component's css), particularly `cm`, when I tried `in` it didn't work.

```
@page {
    /* prevents electron's additional margins around sheet-content (the first printedPage of: the html already sized 8.5x22) */
    margin-top: 0cm;
    margin-left: 0cm;
    margin-right: 0cm;
    /* prevents electron from printing a blank page between each sheet (the first and second printedPages of the tall html) */
    margin-bottom: -.5cm;
}
```

**Comment by kadirilkimen** [comment]
Hello. Thanks for the answer and sorry for the late response.
I tried this margin fix but it didnt work.
I tried to make margin settings all 0cm, 0mm and 0px. It didnt work. Electron still keep adding a default margin on the pages.Even when i made a test print page without any content than a simple text, it still adding a default margin regardless of any @page or css settings.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by wkoncki** [comment]
@sofianguy 
I tried new printing options in Electron 7.0.0-beta2 and run into this issue as well. I've set margins to 'none' and prints still had automatic margins added. It seems that this issue is still present.

**Comment by itechoverdose** [comment]
this issue still persist in version 8.0.0 as well. i would say most of electron issues are in printing and i wish you would look at them sooner cause some issues have been around since version 0.3

System : Windows x64 Ultimate
Electron : 8.0.0

**Comment by vhourdry** [comment]
Is there any update or workaround about this issue ?

**Comment by akash-rajput** [comment]
Same here any fixes?

**Comment by El1tED** [comment]
@akash-rajput hi did you find a fix?

**Comment by EL-MEHDI-ESSAADI** [comment]
Same issue here, anyone found a solution?
