### ISSUE TITLE
TouchBarPopover doesn't support TouchBarColorPicker or TouchBarPopover in items

### ISSUE THREAD

**Issue by jpweeks** [electron/electron#15371]
**Expected Behavior**
A `TouchBarPopover` can have a `TouchBarColorPicker` or `TouchBarPopover` in its rendered `items`.

**Actual behavior**
Any `TouchBar*` interface that 'pops over' the rendered `TouchBarPopover` will initially render for a few frames when activated, then revert to rendering the root `TouchBar` items. No errors are thrown.

**To Reproduce**
Create a `TouchBar` with the following hierarchy:

```
TouchBar
––TouchBarPopover
––––TouchBarColorPicker
```

**Comment by MarshallOfSound** [comment]
Touchbar is going to be a thing of the past, the technical investment to support this is not worth it anymore IMO
