### ISSUE TITLE
shell.moveItemToTrash() does not properly return false if file path is in use

### ISSUE THREAD

**Issue by bpasero** [electron/electron#15370]
* Output of `node_modules/.bin/electron --version`: 2.0.12
* Operating System (Platform and Version): Windows 10

**Expected Behavior**
`moveItemToTrash` should return `false` if the file is locked.

**Actual behavior**
`moveItemToTrash` does not return `false` when a file is locked.

**To Reproduce**
* open a folder in a command prompt (cd into it)
* run `shell.moveItemToTrash(path of folder)`
* observe the returned value is `true` indicating this operation was successful

**Comment by sofianguy** [comment]
@bpasero is this bug still present in version 4.x or later?

**Comment by bpasero** [comment]
@sofianguy reproduces with Electron 6.0.1

**Comment by niik** [comment]
@codebytere @nornagon This was fixed in #25124 but I forgot to use the proper syntax for auto-closing it on merge. Would either of you be so kind and close it?

**Comment by bpasero** [comment]
Thanks a lot for working on this 👍
