### ISSUE TITLE
Frameless Window -webkit-app-region:drag question

### ISSUE THREAD

**Issue by hengkx** [electron/electron#15386]
* Output of `node_modules/.bin/electron --version`:3.0.6
* Operating System (Platform and Version):Windows10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):not

**Expected Behavior**
`-webkit-app-region:drag` can move window. removed `-webkit-app-region` no move.

**Actual behavior**
A clear and concise description of what actually happened.
`-webkit-app-region:drag` can move window. removed `-webkit-app-region` still can move window.

**To Reproduce**
Your best chance of getting this bug looked at quickly is to provide a REPOSITORY that can be cloned and run.
```js
mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    frame: false,
    titleBarStyle: 'hidden'
  })
```
```html
<div id="div" class="test" style="-webkit-app-region:drag"></div>
  <button id="btn">remove -webkit-app-region</button>
  <script>
    document.getElementById("btn").onclick = function () {

      document.getElementById('div').style['-webkit-app-region'] = ''; 
    }
    // You can also require other files to run in this process
    require('./renderer.js')
  </script>
```
You can fork [electron-quick-start](https://github.com/electron/electron-quick-start) and include a link to the branch with your changes.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone https://github.com/hengkx/electron-quick-start.git
$ npm install
$ npm start || electron .
```
**Screenshots**
![1](https://user-images.githubusercontent.com/8358236/47474096-0d77cc80-d848-11e8-96f6-236f71e71530.gif)

**Additional Information**

**Comment by civet** [comment]
same issue. 
the region for drag always exsists even after a new page loaded.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by Mstrodl** [comment]
@sofianguy For what it's worth, this is still happening on 7.1.11

**Comment by Garbee** [comment]
I just noticed this behavior myself. In setting the `acceptFirstMouse` option on the BrowserWindow it resolved it. It seems to be something with the initial mouse click activating the window, then everything else kicks in. Where with this option it immediately triggers everything. So it is reproducible on 9.0.5, but a possible workaround is available as long as that option doesn't cause an issue within your app for some reason.


I saw this issue after removing the app-region rule even after clearing the user data cache folder. It has something special to do with inactive windows becoming active it seems.
