### ISSUE TITLE
Sometimes top menu doesn't change when I focus one of my app's windows on macOS

### ISSUE THREAD

**Issue by SilencerWeb** [electron/electron#15390]
* Output of `node_modules/.bin/electron --version`: v3.0.5
* Operating System (Platform and Version): macOS High Sierra

**Expected Behavior**
When I focus one of my app's windows, the top menu should change on my app's menu.

**Actual behavior**
Sometimes when I focus one of my app's windows, the top menu stays the same as it was befor.

**To Reproduce**
Unfortunately, I'm not sure how to reproduce it. It seems like it is just random.

**Screenshots**
Here is the top menu I'm talking about:

![image](https://user-images.githubusercontent.com/20713191/47486120-0d33fd00-d859-11e8-9751-f39fbcc0bc36.png)

**Additional Information**
[Here](https://github.com/SilencerWeb/taggy-desktop-releases/releases/download/v0.4.3/Taggy-0.4.3-mac.zip) you can download my application for better understanding. It happens not only with my app, I have another one Electron application and it works like that in too.

**Comment by SilencerWeb** [comment]
Ok, it happens only if the dock icon is hidden. If it is expected behavior, feel free to close the issue.

**Comment by MarshallOfSound** [comment]
This is expected behavior 👍 It's how macOS reacts to windows with no dock icon
