### ISSUE TITLE
Simple html <select> not working (dropdown not opening) in Windows Subsystem for Linux

### ISSUE THREAD

**Issue by DamienPirsy** [electron/electron#15413]
Electron version: 3.0.3
Operating System: Windows Subsystem for Linux 
WIndows 10 Pro - Version 10.0.17763 Build 17763

**Expected Behavior**
A regular html select should appear and should be openable with a mouse click, showing all the options.

**Actual behavior**
The html select is there but clicking does nothing, I only see a change in the border/coloring. See attached screenshot. At first I thought it was a CSS library issue (using Bulma first and then Spectre), but event with an unstyled item the problem persists.

**To Reproduce**
Clone the [electron-quick-start](https://github.com/electron/electron-quick-start) sample and put a simple html select in the body inside the index.html file:

```
<form>
    <select name="test">
        <option value="1">option 1</option>
        <option value="2">option 2</option>
        <option value="3">option 3</option>
    </select>
 </form>
```

**Screenshots**
![capture](https://user-images.githubusercontent.com/4426504/47559562-22229600-d916-11e8-9c13-ab5dd9ea1f47.JPG)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
