### ISSUE TITLE
PDF cannot be opened inside the App

### ISSUE THREAD

**Issue by Bahramudin** [electron/electron#15410]
**Is your feature request related to a problem? Please describe.**
When I use the browser to open/browse a PDF file from the server, it is working well. But the same function is not working in the Electron Desktop App, it means when I want to click on the preview PDF link, then it opens download window. _(For better understanding, please refer to the below images)_
 
**Describe the solution you'd like**
I want if there is any module/plugin to be able open/browse the PDF file from the Server.

**Describe alternatives you've considered**
NaV

**Additional context**
**It is when using browser**
![11](https://user-images.githubusercontent.com/13574895/47557927-878d7b80-d944-11e8-864d-01e2020be547.jpg)

**And it is when using Electron App**
![22](https://user-images.githubusercontent.com/13574895/47557968-9f64ff80-d944-11e8-88d0-572543766823.jpg)

**Note:** I am using Windows OS. Electron V3.0.4

**Comment by MarshallOfSound** [comment]
PDF Viewer in electron 3 is not currently working / enabled.  See #12337
