### ISSUE TITLE
When the notification's action button is clicked, the app will be activated

### ISSUE THREAD

**Issue by ervinewell** [electron/electron#15412]
Output of node_modules/.bin/electron --version: 3.0.3
Operating System (Platform and Version): macOS Mojave 10.14

**Description**
There were a few desktops. I put my electron app on one, and focused on another one. When the app's notification came and I clicked the action button:

**Expected Behavior**
The app will not be activated.

**Actual Behavior**
The app was activated automatically.

**To Reproduce**
```sh
$ git clone https://github.com/ervinewell/electron-quick-start.git -b bugfix/notificaion-activate-app
$ npm install
$ npm start
```

**Screenshots**
https://youtu.be/YaNFgvYOYK8

**Comment by ervinewell** [comment]
@MarshallOfSound I am terribly sorry that I misunderstood the expeced behavior and the actual behavior. I have modified my description of this issue. Please check it once again.🙇‍♂️

**Comment by MarshallOfSound** [comment]
Reopening just to make it clear it will be revisited

**Comment by stanurkov** [comment]
Any news on this issue?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
