### ISSUE TITLE
Can't zoom in window content anymore

### ISSUE THREAD

**Issue by vasyl-shumskyi** [electron/electron#15417]
Hello,

In electron 3.0.6 I can't zoom in window content anymore with a touchpad on Mac. This was very useful for debugging. 

How can I reenable zoom in? 

Thanks!

**Comment by vasyl-shumskyi** [comment]
Workaround: 

```
require('electron').webFrame.setVisualZoomLevelLimits(1, 3)
```

**Comment by nornagon** [comment]
This was changed intentionally as part of #12631. The workaround you have is the correct way to re-enable it.
