### ISSUE TITLE
Allowing part of the app to manifest before the app ready event

### ISSUE THREAD

**Issue by sungdzda** [electron/electron#15416]
Hello, this is an issue that may be considered trivial in some context, but still could be improved upon.
I noticed on my Windows machine, after I launch my Electron app, that the app ready event can take up to a few seconds to fire. My dev machine has mid-grade hardware with an SSD. I imagine that this time would be longer on an average user's computer.

During this time, the user is not receiving any clue that the app is launching. The mouse cursor does not change its form, no icon appears in the task bar, and the Electron API is not yet ready to show a window or a native dialog. This may lead to the user clicking on the app twice. A lack of confirmation, if combined with an extra long startup time, could cause a flaw in user experience. (Perhaps that's no problem on a Mac, but still.)

Usually when a splash screen is implemented on Electron, it's done after the app ready event. ([reference](https://github.com/trodi/electron-splashscreen/blob/master/examples/example.ts)) Some online discussions have also revealed information on this aspect. ([here](https://stackoverflow.com/questions/42292608/electron-loading-animation)) When I look at my Chrome browser (pardon me if the comparison is inappropriate), it seems to draw an empty white screen quickly at launch, before gradually filling the screen with elements. Incidentally, Chrome appears to launch faster than my electron app does, even though Chrome is in fact bulkier. (I tried to show my main window asap, and did not wait for any document to load.) The slower launch could also be related to the sheer size of the Electron executable (69MB for the 64-bit version); for example, an antivirus present on the system would almost certainly want to scan that first, although I wouldn't claim to understand anything more in-depth than that.

**Comment by MarshallOfSound** [comment]
We can't make it possible to do certain things before the `ready` event, that isn't a made up construct; it's a hard limitation on when windows can actually be created.  `ready` should fire relatively quickly though.

>  that the app ready event can take up to a few seconds to fire.

If that is the case please raise a bug with a way to reproduce that issue
