### ISSUE TITLE
What APIs can I use before the app ready event?

### ISSUE THREAD

**Issue by sungdzda** [electron/electron#15414]
Hello everyone, I wanted to know if I could invoke any of Electron’s functionalities before the app ready event. I tried to search the electron online documentation, but could’t find anything dedicating to this topic.

My main motivation is to implement something like a splash screen or a system dialog that shows up before the main window does; because app ready can take several seconds on my development machine to fire, and will maybe take more time on an average user’s computer. Having a dialog or window immedietly show up will fill this gap such that the user gets his/her confirmation and doesn't click on the program twice. However, the system dialog API is only available after the ready event. I believe BrowserWindow can also only be instantiated after that. Is there anything I can do before that moment?

Thanks for your help.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by sungdzda** [comment]
@MarshallOfSound Thanks for letting me know. I wrote this issue in a question form, but this could also be a potential feature request, or request for improvement on the documentation. I wasn't sure about it because I am very new to the framework.
