### ISSUE TITLE
Multiple issues with registerStreamProtocol

### ISSUE THREAD

**Issue by ccorcos** [electron/electron#15425]
* Output of `node_modules/.bin/electron --version`: 3.0.3
* Operating System (Platform and Version): MacOS

I'm trying to get url scheme handlers to work for my application. I've figured out a few issues on my own already. I will document them here so others can find them when they search for issues:

- Using `protocol.registerStreamProtocol`, XHR, `<script>`, and `<img>` don't work.

	Need to use `protocol.registerStandardSchemes` before `protocol.registerStreamProtocol`

- `XMLHttpRequest` works but `window.fetch` doesn't. It says `URL scheme "myapp" is not supported"`.

	Need to use `webFrame.registerURLSchemeAsPrivileged` inside the renderer process.

There are a few issues, however that I have not been able to solve.

1. `XMLHttpRequest` body data never makes it to the protocol handler, but `window.fetch` does.

2. Cookies don't appear to work. I've tried setting httpOnly cookies and client cookies and I can't see any trace of them in the server, main process, or renderer process.

Here's an example where you can try it out yourself:

```sh
git clone https://github.com/ccorcos/electron-protocol-example
cd electron-protocol-example
npm install 
npm run server
npm start # In a separate terminal
```

**Comment by ccorcos** [comment]
This isn't in my example above, but I think an ideal API would be able to support a basic streaming proxy using `request`. It almost works, but there are still issues with cookies any maybe some other things...

```ts
import { app, protocol } from "electron"
import config from "../shared/config"
import { getHttpUrl } from "../shared/schemeHelpers"

protocol.registerStreamProtocol(
	config.protocol,
	(req, callback) => {
		const httpUrl = getHttpUrl(req.url)
		console.log("request", req.method, httpUrl)
		console.log(req)
		const stream = request({
			url: httpUrl,
			headers: req.headers,
			method: req.method,
			body: bodyData,
		})
		stream.on("response", resp => {
			callback({
				statusCode: resp.statusCode,
				headers: resp.headers,
				data: resp as any,
			})
		})
	},
	error => {
		if (error) {
			console.error("Failed to register protocol")
		}
	}
)
```

**Comment by ccorcos** [comment]
Another issue I found an issue where piping a request into the the response blocks the UI thread:

```ts
const stream = request({
	url: httpUrl,
	headers: req.headers,
	method: req.method,
	jar: cookieJar,
	body: body,
})

stream.on("response", resp => {
	callback({
		statusCode: resp.statusCode,
		headers: resp.headers,
		// The response is a stream, but for some reason the type system
		// doesnt want to accept it so we cast as any.
		data: pass as any,
	})
})

stream.on("error", error => {
	callback(createErrorStream(error) as any)
})
```

This is clipped from the performance tab in the render process:

![untitled](https://user-images.githubusercontent.com/1794527/50249828-fa8aff80-0393-11e9-9b9b-7f3a1d32e2a9.png)

However, I noticed if you pipe the response through a passthrough stream, then everything works without blocking the UI... No idea why, but it seems like a bug.

```ts
const stream = request({
	url: httpUrl,
	headers: req.headers,
	method: req.method,
	jar: cookieJar,
	body: body,
})

stream.on("response", resp => {
	const pass = new PassThrough()
	resp.pipe(pass)

	callback({
		statusCode: resp.statusCode,
		headers: resp.headers,
		// The response is a stream, but for some reason the type system
		// doesnt want to accept it so we cast as any.
		data: pass as any,
	})
})

stream.on("error", error => {
	callback(createErrorStream(error) as any)
})
```

**Comment by ccorcos** [comment]
Another issue: "cache-control" headers seems to be bypassed and the browser always calls registerStreamProtocol even if the file should be cached by the webview.

**Comment by helm168** [comment]
> Another issue: "cache-control" headers seems to be bypassed and the browser always calls registerStreamProtocol even if the file should be cached by the webview.

any workarounds for cache?

**Comment by ccorcos** [comment]
I think the stream protocol handler is lower level than the caching API. I'm using the "net" API now instead of request and that handles caching inside the Chromium network stack.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
