### ISSUE TITLE
Encoding codec is always VP8 whatever the instruction

### ISSUE THREAD

**Issue by lcswillems** [electron/electron#15433]
* Output of `node_modules/.bin/electron --version`: v3.0.0-beta.12
* Operating System (Platform and Version): Kubuntu 18.10
* Output of `node_modules/.bin/electron --version`: v3.0.0-beta.12

**Expected Behavior**
I want to save a MP4 video encoded with H.264.

**Actual behavior**
According to VLC, the video is encoded with `Google/On2's VP8 Video (VP80)`.

**To reproduce**
I create a blob with:
``let blob = new Blob(recordedChunks, {type: 'video/mp4;codecs=H.264'});``

**Screenshots**
![image](https://user-images.githubusercontent.com/5437552/47610200-9c0a6a80-da4f-11e8-8328-fb61132298b7.png)

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
