### ISSUE TITLE
crash with electron 3.0.5 on Travis/Linux: "Lost UI shared context"

### ISSUE THREAD

**Issue by starpit** [electron/electron#15435]
* Output of `node_modules/.bin/electron --version`: 3.0.5
* Operating System (Platform and Version): Linux ubuntu 14 (Travis)
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2 series

**Expected Behavior**
electron should not crash with
ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context

**Actual behavior**
On some test runs (in Travis, using xfvb), electron crashes with "Lost UI shared context". i've included a few of the preceding lines, in case it helps.

```
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[1134:1028/040502.466080:ERROR:sandbox_linux.cc(379)] InitializeSandbox() called with multiple threads in process gpu-process.
[1098:1028/040502.469261:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.
```

**To Reproduce**
Run enough times in Travis, using xvfb, and this seems to happen.

**Comment by MarshallOfSound** [comment]
> Run enough times in Travis, using xvfb, and this seems to happen.

Without more consistent repro steps we probably won't be able to look into this.  To make it easier can you try figure out more exactly what could be causing the crash and get us a crash dump.

You can make Electron dump a usable stack trace with the environment variable `ELECTRON_ENABLE_STACK_DUMPING=true`

**Comment by starpit** [comment]
ok. i'll work on repro. this happens in about 10% of our builds.

**Comment by sofianguy** [comment]
Thank you for your issue!
I'm going to close this issue but don't hesitate to reach out if have repro steps. We'll be happy to reopen the issue.
