### ISSUE TITLE
Fails to run on older systems, NSS_VersionCheck("3.26")

### ISSUE THREAD

**Issue by probonopd** [electron/electron#15439]
I was [asked](https://github.com/electron-userland/electron-builder/issues/3426#issuecomment-433739232) to report this here.

Recent app builds fail on older distributions (such as Ubuntu 16.04.0) with

```
NSS_VersionCheck("3.26")
```

The internet is full of corresponding bug reports.

Turns out many applications run absolutely fine if one patches this restriction away using

```
sed -i -e 's|3.26|3.00|g' chrome
```

This allows many applications to run that would just fail to launch otherwise.

**Comment by codebytere** [comment]
A solution to this is [here](https://ubuntuforums.org/showthread.php?t=2178663#post_message_12807565).

You'll need to update your version of `libnss3`.
