### ISSUE TITLE
When the notification's action button is clicked, the app will be activated unexpectedly

### ISSUE THREAD

**Issue by ervinewell** [electron/electron#15437]
Output of node_modules/.bin/electron --version: 3.0.3
Operating System (Platform and Version): macOS Mojave 10.14

**Description**
There were a few desktops. I put my electron app on one, and focused on another one. When the app's notification came and I clicked the action button:

**Expected Behavior**
The app will not be activated.

**Actual Behavior**
The app was activated automatically.

**To Reproduce**
```sh
$ git clone https://github.com/ervinewell/electron-quick-start.git -b bugfix/notificaion-activate-app
$ npm install
$ npm start
```

**Screenshots**
https://youtu.be/YaNFgvYOYK8

**Comment by MarshallOfSound** [comment]
Please do not raise duplicate issues, your original issue will be followed up on #15412

**Comment by ervinewell** [comment]
> Please do not raise duplicate issues, your original issue will be followed up on #15412

@MarshallOfSound  My original issue's description was wrong, but it was closed before I modified it so I opened another one.
