### ISSUE TITLE
add host and pathname to request in custom protocol handler

### ISSUE THREAD

**Issue by dsanders11** [electron/electron#15432]
**Is your feature request related to a problem? Please describe.**
The protocol handler only gets `url` in `request`, leaving the user to parse out the relevant details themselves. This leads to some fragile code unless care is taken, the [documentation for the `protocol` module gives the example code](https://github.com/electron/electron/blob/master/docs/api/protocol.md):

```javascript
app.on('ready', () => {
  protocol.registerFileProtocol('atom', (request, callback) => {
    const url = request.url.substr(7)
    callback({ path: path.normalize(`${__dirname}/${url}`) })
  }, (error) => {
    if (error) console.error('Failed to register protocol')
  })
})
```

Which has hardcoded the length of `atom://` so it can strip the scheme from the URL.

**Describe the solution you'd like**
Extend the `request` object to include `host` and `pathname`, equivalent to what they would b in `window.location`. Then the above code could be written as:

```javascript
app.on('ready', () => {
  protocol.registerFileProtocol('atom', (request, callback) => {
    const url = request.host + request.pathname
    callback({ path: path.normalize(`${__dirname}/${url}`) })
  }, (error) => {
    if (error) console.error('Failed to register protocol')
  })
})
```

This also makes it quicker and easier to make more robust code and provide errors for common cases, like `host` accidentally provided for a file protocol. It also makes it easier for library developers to write a handler which could be reused under any `scheme` without needing to parse the URL to find out the scheme prefix just to remove it.

**Comment by MarshallOfSound** [comment]
@dsanders11 You can parse this yourself without using `substr` (those docs should change that's a bad recommendation).

You should use `url.parse`, something like:

```js
const url = require('url')

app.on('ready', () => {
  protocol.registerFileProtocol('atom', (request, callback) => {
    const { host, pathname } = url.parse(request.url);
    console.log(host, pathname)
  }, (error) => {
    if (error) console.error('Failed to register protocol')
  })
})
```

Gonna tag this as a documentation improvement 👍

**Comment by dsanders11** [comment]
@MarshallOfSound, was hoping it was something that Electron could do so as to reduce repeated boilerplate in people's code, but you're right, that's pretty close to a one liner.

**Comment by r6min** [comment]
Looks like no one's working on this. Can I take it? First time contributor here 😉
