### ISSUE TITLE
Support Chromium's command-line switch --unsafely-treat-insecure-origin-as-secure

### ISSUE THREAD

**Issue by cachius** [electron/electron#15448]
**Is your feature request related to a problem? Please describe.**
Notifications, Geolocation, Device motion/orientation, EME, getUserMedia, AppCache require a secure origin to work in Chromium. HTTP URLs are not considered secure.
That's why Chromium provides the command-line switch
`--unsafely-treat-insecure-origin-as-secure="$url"` to circumvent this problem.
Unfortunately it's not working in Electron.

**Describe the solution you'd like**
Please make it work. In the renderer. I'd suggest simply like 
```
new BrowserWindow({
  webPreferences: {
    additionalArguments: {
    '--unsafely-treat-insecure-origin-as-secure', 'http://insecure-origin'
    }
}
```
Or a new option `considerSecure: String[]` to `BrowserWindow.webPreferences`.
I guess it should be not too hard to implement since Chromium already supports it and it seems to get lost only in the process of Electron integration.

**Describe alternatives you've considered**
- `app.commandLine.appendSwitch('unsafely-treat-insecure-origin-as-secure', $url)` in the main thread
- Invisible [BrowserWindow](https://github.com/electron/electron/blob/master/docs/api/browser-window.md) with secure origin + IPC
- `<iframe>` on a secure origin
- localhost-Proxy
- Using Data URLs in [loadURL](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winloadurlurl-options): `data:text/html,<script>new Notification("hi")</script>`
- webFrame.registerURLSchemeAsPrivileged

**Additional context**
'Deprecating Powerful Features on Insecure Origins' https://goo.gl/rStTGz
When the flag is set in Chromium a message appears under the address bar, saying that
'You are using an unsupported command-line flag'.
![image](https://user-images.githubusercontent.com/23075755/47640947-1c6ebf80-db65-11e8-9e6e-d7a5bd90c208.png)
Nonetheless the features are then working on the origin treated securely.

**Comment by cachius** [comment]
Since the associated PR has been closed, I'd like to argue here once again for this feature:
With access to the mighty API via nodeIntegration
Chromium's classification of 'Insecure Origins' doesn't hold for Electron.

I can access any file I want and request across the whole internet,
but have to evoke intricatest trickery to display a humble notification.

@MarshallOfSound Since you already tried to implement this, would you try again?
In the comments of #15452 there are some hints how to do it.

For testing I found Chomium supports IP 0.0.0.0 as ubiquitous unsafe origin!
So you can `w.loadURL('http://0.0.0.0')` and then spawn a note
via `webContents.executeJavaScript('new Notification("test")')`
and resolve the test via its onshow handler.

**Comment by robatwilliams** [comment]
Service workers are another use case for this; they require a secure context.

`localhost` and `127.0.0.1` are exceptions to the HTTPS rule and are considered secure, which serves many developers' needs.

Often however in corporate environments, due to authentication setups in development environments, it's only possible to (easily) access local applications under development using the machine's full host name. This is when `--unsafely-treat-insecure-origin-as-secure` is useful.

Note also regarding the flag that it has no effect in Chromium unless `--user-data-dir` is also supplied.

**Comment by superddr** [comment]
I would like this feature too, getUserMedia from http://{some where other than localhost} ,you know...

**Comment by NeverMore-KL** [comment]
I would like this feature too, getUserMedia from http://{some where other than localhost} ,you know...

**Comment by cker321** [comment]
I would like this feature too

**Comment by hanlike** [comment]
I would like this feature too, getUserMedia from http://{some where other than localhost} ,you know...

**Comment by hxyong** [comment]
too

**Comment by MY1112** [comment]
sit back and wait

**Comment by cker321** [comment]
When will this feature be supported?

**Comment by cker321** [comment]
daily ask:When will this feature be supported?

**Comment by NeverMore-KL** [comment]
> daily ask:When will this feature be supported?
yan can use `protocol.registerSchemesAsPrivileged` to  resolve this

**Comment by cker321** [comment]
> > daily ask:When will this feature be supported?
> > yan can use `protocol.registerSchemesAsPrivileged` to  resolve this

ok， thx, i will try

**Comment by NeverMore-KL** [comment]
> > > daily ask:When will this feature be supported?
> > > yan can use `protocol.registerSchemesAsPrivileged` to  resolve this
> 
> ok， thx, i will try
used before the ready event of the app
```js
 protocol.registerSchemesAsPrivileged([
    {
      scheme: 'http', 
      privileges: {
        bypassCSP: true,
        secure: true,
        supportFetchAPI: true,
        corsEnabled: true
      }
    }
  ]);
```

**Comment by NeverMore-KL** [comment]
idea from https://github.com/electron/electron/issues/10381#issuecomment-406206397
```js
// used before the ready event of the app
 protocol.registerSchemesAsPrivileged([
    {
      scheme: 'http', 
      privileges: {
        bypassCSP: true,
        secure: true,
        supportFetchAPI: true,
        corsEnabled: true
      }
    }
  ]);
```

**Comment by cker321** [comment]
> > > > daily ask:When will this feature be supported?
> > > > yan can use `protocol.registerSchemesAsPrivileged` to  resolve this
> > 
> > 
> > ok， thx, i will try
> > used before the ready event of the app
> 
> ```js
>  protocol.registerSchemesAsPrivileged([
>     {
>       scheme: 'http', 
>       privileges: {
>         bypassCSP: true,
>         secure: true,
>         supportFetchAPI: true,
>         corsEnabled: true
>       }
>     }
>   ]);
> ```

谢了兄弟！
