### ISSUE TITLE
Electron transparent window use maximize() occur a bug

### ISSUE THREAD

**Issue by rhymedys** [electron/electron#15449]
Electron Version: 3.0.6
Operating System (Platform and Version): windows 10
Last known working Electron version: none

In  the case , when the mainWindow add 'transparent:true' to construct , and i trigger maximize from ipcRender

![qq 20181029180938](https://user-images.githubusercontent.com/15199335/47643233-d0903a80-dba5-11e8-890f-c86a3e154b52.png)

![qq 20181029180820](https://user-images.githubusercontent.com/15199335/47643191-a6d71380-dba5-11e8-9f12-af0240951472.png)

**Expected Behavior**
the result of res is true 

**Actual behavior**
the result of res is false

**To Reproduce**
https://github.com/rhymedys/electron-quick-start-bug-repo

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
