### ISSUE TITLE
MediaRecorder objects are retained in memory even when are not held by application code

### ISSUE THREAD

**Issue by amn** [electron/electron#15451]
Observe the anonymous `MediaRecorder` object in the snippet below, which I run with the Developer Tools console:

```
navigator.mediaDevices.getUserMedia({ video: true, audio: true}).then(function create_media_recorder(stream) {
    new MediaRecorder(stream);
    console.clear(); /// To make sure console does not hold to any objects which may in turn may be holding the above object.
});
```

After the above, the object should be garbage collected, to my understanding, but isn't and just sits there in memory, I've verified this with Memory tab in the Developer Tools.

The expected behavior is that the object is GC'ed at the earliest convenience of the latter, but definitely not held for what seems to be either extended or infinite period of time afterwards. I have to add that regular objects aren't retained, MediaRecorder objects are those that I have found to be retained. There may be other classes of objects that behave that way, for one reason or another, but I haven't found (or looked for) such other classes.

I can't really tell what what the retaining objects list tries to tell me, but it lists "Pending activities", among other things:

![image](https://user-images.githubusercontent.com/471489/47647647-e2f37f80-db77-11e8-94bd-fbd786195e10.png)

To reproduce, load `electron.exe`, open Developer Tools, paste the snippet, wait for console to clear (when the stream promise is resolved), take a heap snapshot through the Memory tab, and find a constructed MediaRecorder object among objects in the list as shown in the screenshot.

This is Electron release 3.0.4 on Windows 10 64-bit.

FYI, I've run the snippet in Firefox and no MediaRecorder object on the heap there, unless I e.g. assign it to a variable that itself should survive the execution of the snippet (e.g. a property of the window object).

Also tested with Google Chrome Version 70.0.3538.77 (Official Build) (64-bit), it behaves much the same way Electron does.

**Comment by MarshallOfSound** [comment]
> FYI, I've run the snippet in Firefox and no MediaRecorder object on the heap there

Can you test in Chrome?

**Comment by amn** [comment]
I have, Chrome 70.0.3538.77 (Official Build, 64-bit) retains MediaRecorder objects as well. Pretty much the same story.

**Comment by MarshallOfSound** [comment]
> I have, Chrome 70.0.3538.77 (Official Build, 64-bit) retains MediaRecorder objects as well.

If you believe this to be a bug and not part of the spec I'd suggest raising this on [Chromium's bug tracker](https://bugs.chromium.org/p/chromium/issues/list).  When chromium fixes it we will inherit it on the Electron side, this isn't something we can put resources towards fixing.
