### ISSUE TITLE
Unexpected behavior occuered when a notification's action button was clicked

### ISSUE THREAD

**Issue by ervinewell** [electron/electron#15454]
As this issue said: #15412
Last time I opened this issue but wrote the expected behavior and the actual behavior on the wrong sides, and it was closed before I modified it. I hope someone can check this issue once again.

**Comment by lee-dohm** [comment]
@ervinewell As @MarshallOfSound said in #15437, please do not open duplicate issues. When we have time, we will investigate #15412.

**Please note:** Duplicate issues take time to triage and handle, which takes time away from doing more productive work, like looking into the issue you want looked at. Every time you knowingly open a duplicate issue, a [heisenbug](http://www.hacker-dictionary.com/terms/heisenbug) is born :grinning: Additionally, wittingly opening duplicate issues is considered harassment under the [Electron Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md). You may consider this an official warning.
