### ISSUE TITLE
autoUpdater.quitAndInstall() does not quit the app

### ISSUE THREAD

**Issue by SilencerWeb** [electron/electron#15453]
* Output of `node_modules/.bin/electron --version`: v3.0.6
* Operating System (Platform and Version): macOS High Sierra

**Expected Behavior**
When I call `autoUpdater.quitAndInstall()`, I want to install downloaded update and relaunch the application.

**Actual behavior**
When I call `autoUpdater.quitAndInstall()`, the app is still running and I have to quit it manually. Seems like `autoUpdater.quitAndInstall()` just closes all windows because on this event (`window-all-closed`) I create a tray icon. Also, it does not trigger event `before-quit` because if it was called, it would destory all windows and tray icon so app could be closed.

**Comment by MarshallOfSound** [comment]
Sounds like you are experiencing documented behavior.  Normally `before-quit` fires before `window-all-closed`, with this method being the exception.

See the [`before-quit-for-update`](https://electronjs.org/docs/api/auto-updater#event-before-quit-for-update) event docs:

> When this API is called, the before-quit event is not emitted before all windows are closed. As a result you should listen to this event if you wish to perform actions before the windows are closed while a process is quitting, as well as listening to before-quit.

This means if you are calling `event.preventDefault()` on those events, the order is different in this case, probably causing you to prevent the quit.

In addition, I just manually validated, `quitAndInstall()` does indeed quit if I have no event listeners attached preventing default.

Going to close this out, please @ mention me in a follow up if the above docs don't quite explain the scenario you are running into.

**Comment by SilencerWeb** [comment]
@MarshallOfSound yes, I call `event.preventDefault()` on closing one of my windows and create a tray icon, so I guess that's the problem. Is there any way to check where did this event come from so I could check it and prevent closing if it is not from `quitAndInstall` function?

Also, I tried to destroy all windows and tray icon on event `before-quit-for-update` but seems it was not even fired.

**Comment by MarshallOfSound** [comment]
@SilencerWeb I think `before-quit-for-update` is a relatively new feature (3.0.0)

You could set a flag yourself when you call `quitAndInstall()` and check that flag in your quit handler

**Comment by SilencerWeb** [comment]
@MarshallOfSound okay, I have no idea what else to try. I tried to run `quitAndInstall()` without creating even a single window and a tray icon - still the same.

Also, maybe it is somehow `electron-updater`'s bug but I don't think so since it uses electron native updater for calling `quitAndInstall()`.

**Comment by SilencerWeb** [comment]
@MarshallOfSound any thoughts?
