### ISSUE TITLE
Memory leak with use sandbox true and webFrame.setSpellCheckProvider

### ISSUE THREAD

**Issue by vrbsm** [electron/electron#15459]
* Output of `node_modules/.bin/electron --version`: v3.0.5
* Operating System (Platform and Version): macOS 10.14

**Expected Behavior**
When webPreferences.sandbox is set to true and webFrame is using a provider for spell checking, the memory must be released after page reload.

**Actual behavior**
The memory isn't released and caused memory leak

**To Reproduce**

- Clone https://github.com/vrbsm/example-memory-leak-electron
- Run npm run start
Memory usage of electron process will be increasing in task manager after reloading the page several times

**Screenshots**
![test-memory-leak-01](https://user-images.githubusercontent.com/9887288/47675838-c2d4b800-db99-11e8-97e8-b5b27bcab929.gif)

**Comment by richardlopes-daitangroup** [comment]
Same here

**Comment by MarshallOfSound** [comment]
@ckerr Master has the new async spellchecker API, that impl might have fixed some things by accident? 😆

**Comment by vrbsm** [comment]
> @ckerr Master has the new async spellchecker API, that impl might have fixed some things by accident? 😆

I tested the master, but still saw the problem of memory leak :-(
Do you have any updates if this could be released soon?

**Comment by vrbsm** [comment]
@nitsakh I tested **v4.0.3** and the memory leak still persists.
basically: 
clone: **https://github.com/vrbsm/example-memory-leak-electron**
run: npm run start
Memory usage will increase in task manager after reloading the page several times
