### ISSUE TITLE
BrowserWindow.close crashes application when run as non-admin on Windows.

### ISSUE THREAD

**Issue by jameskoch** [electron/electron#15457]
* Output of `node_modules/.bin/electron --version`: 3.0.4
* Operating System (Platform and Version): Windows 10.0.14393 (also repros on Win7)
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): Unknown

**This issue only manifests when running Electron as a non-admin user**

**Expected Behavior**
Calls to BrowserWindow.close() should not crash the application.

**Actual behavior**
Application crashes when user closes the BrowserWindow.

**To Reproduce**
I reproduced this using electron-quick-start [here](https://github.com/jameskoch/electron-quick-start/commit/69ee8609ab90e00536da4a06c1a24d54cb71e15b). 

1. On Windows, make sure you're using a non-admin account.
2. git clone; npm install; npm start;
3. Click the X in the top right hand corner of the BrowserWindow

```sh
$ git clone https://github.com/jameskoch/electron-quick-start
$ npm install
$ npm start
```

**Additional Information**
Note that this code works fine when run as an administrator.

This appears in the Windows Application Event Log with exception code/offset:
```
Exception code: 0xc0000005
Fault offset: 0x00000000018727f4
```

On a different machine, using my full app (Electron 3.0.5), I loaded symbols and got a bit more info:
```
nteract.exe!aura::Window::GetRootWindow() Line 212   C++
nteract.exe!aura::Window::GetHost() Line 216    C++
nteract.exe!atom::NativeWindowViews::GetAcceleratedWidget() Line 1028          C++
nteract.exe!atom::NativeWindowViews::IsClosable() Line 686      C++
nteract.exe!atom::NativeWindowViews::Close() Line 314               C++
nteract.exe!mate::internal::Dispatcher<void __cdecl(atom::api::Menu * __ptr64)>::DispatchToCallback(const v8::FunctionCallbackInfo<v8::Value> & info) Line 239       C++
node.dll!000007fec5e0de84()     Unknown
node.dll!000007fec5e7f8fd()      Unknown
node.dll!000007fec5e4db89()     Unknown
node.dll!000007fec5e4da6b()     Unknown
0000000c95f84561()        Unknown
```

Perhaps this is just a nonsense usage of beforequit. My goal was to orchestrate an orderly shutdown of each open BrowserWindow before the application itself terminates. I developed this code on macOS, and was primarily targeting the "Command + Q" workflow when using beforequit.

**Comment by MarshallOfSound** [comment]
Duplicate #13418
