### ISSUE TITLE
CrashReport not working

### ISSUE THREAD

**Issue by ran-j** [electron/electron#15477]
* Output of `node_modules/.bin/electron --version` :v2.0.10
* Operating System (Platform and Version): Windows 10 PRO

**Expected Behavior**
Send Report to server

**Actual behavior**
Nothing happen

**To Reproduce**
```
const crashReporter = require("electron").crashReporter;

const { download } = require("electron-dl");

let mainWindow, downloadPopUp;

const debug = /--debug/.test(process.argv[2]);

crashReporter.start({
  productName: "TaskApp",
  companyName: "xPlatform.rocks",
  submitURL: "http://10.22.1.124:7000/api/crashReporter",
  uploadToServer: true
 });
```

Base on https://thorsten-hans.com/electron-crashreporter-stay-up-to-date-if-your-app-fucked-up-3e9a989cd0a0

I try to create a build and then test and nothing

**Comment by codebytere** [comment]
From the `crashReporter` [doc](https://electronjs.org/docs/api/crash-reporter):
```
Note: To collect crash reports from child process in Windows, you need to add this extra code as well. This will start the process that will monitor and send the crash reports. Replace submitURL, productName and crashesDirectory with appropriate values.
```

**Comment by ran-j** [comment]
I'm not trying to collect from a child process, is on the mais process.
