### ISSUE TITLE
Bring shell.writeShortcutLink to Mac OS

### ISSUE THREAD

**Issue by fpsqdb** [electron/electron#15472]
**Is your feature request related to a problem? Please describe.**
on windows, we can use `shell.writeShortcutLink` create shortuct, but on mac os there's no equivalent way to do that

**Describe the solution you'd like**
It will be nice if make `shell.writeShortcutLink` to do the same thing like `Make Alias` on mac.

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR.
