### ISSUE TITLE
Neither kiosk nor fullscreen is not working on Linux

### ISSUE THREAD

**Issue by serge1peshcoff** [electron/electron#15471]
* Electron version: 3.0.6
* Operating System (Platform and Version): Ubuntu 18.04 x64

**Expected Behavior**
Setting the fullscreen mode or kiosk mode for window should start it in fullscreen

**Actual behavior**
It doesn't, the app is running in windowed mode

**To Reproduce**
* Create a simple app that spawns `BrowserWindow` with `{ fullscreen: true, kiosk: true }` (or either of them set to true)
* App should be run in full screen
* It doesn't
* Works on Windows though

**Comment by hovancik** [comment]
related: https://github.com/electron/electron/issues/11632

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
