### ISSUE TITLE
目标平台windows：可否给BrowserWindow添加一个ParentHandle 选项

### ISSUE THREAD

**Issue by rainryu** [electron/electron#15488]
目标平台windows：可否给BrowserWindow添加一个ParentHandle 选项，这样就可以通过窗体句柄设置任何windows 窗体为BrowserWindow的父窗体。
这样就可以实现模态窗口的模态传递，使用electron创建的BrowserWindow作为任何windows窗体的顶层窗体。

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR.
