### ISSUE TITLE
Shadow doesn't keep up with expanding BrowserWindow

### ISSUE THREAD

**Issue by kkitay** [electron/electron#15485]
Mac OS 10.14
Electron v3.0.6

**Expected Behavior**
As a browser window with `useContentSize:true` and `hasShadow: true` expands in height, the shadow always covers the full window.

**Actual behavior**
My browser window has content that expands from 0 to its full height. As the browser window expands, the shadow gets lost along the way. It isn't until I blur and refocus that the shadow covers the entire window correctly.

**To Reproduce**
```sh
$ git clone git@github.com:kkitay/terra.git
$ npm install
$ npm run dev
```
**Screenshots**
![electronshadowbug](https://user-images.githubusercontent.com/1082318/47751057-2a0c6e00-dc67-11e8-97cc-c647bc12197f.gif)

**Additional Information**
I absolutely love Electron

**Comment by kkitay** [comment]
i've since realized that I had the wrong expectation for `useContentSize`, and that's irrelevant to this issue. So effectively, my browser window was ~300px in height but the content in the window was shorter than that, and expanding in height. The shadow regeneration still has issues based on those DOM elements expanding in height, but the browser window itself wasn't changing in this issue.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
