### ISSUE TITLE
Main window not gaining focus after focused child window gets closed

### ISSUE THREAD

**Issue by BitFlipMaze** [electron/electron#15487]
* Output of `node_modules/.bin/electron --version`:
v3.0.6
* Operating System (Platform and Version):
Windows 10

* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

### Expected behavior

If I switch to another application while having the main window and a child window open and then switch back to them, then close the child window it should focus the main window.

### Actual behavior

If I switch to another application while having the main window and a child window open and then switch back to them, then close the child window it focuses the other application instead of the main window.

### How to reproduce

get my reproduction:
  git clone https://github.com/DreamerPlays/ElectronIssue.git
  cd ElectronIssue
  npm install
  npm start

then take another window like windows explorer or your favourite web browser and lay it over the two windows. Then over ALT+Tab give the electron app focus and close the smaller child. After that, the main window goes behind the foreign application again.

**Comment by Woofthecat** [comment]
Do you guys have any progress/update on this?

We're experiencing the same behavior under `3.1.3` too, but it's happening randomly. Sometimes I have to switch through multiple applications before the main window loses focus when the child is closed.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
