### ISSUE TITLE
Simple fullscreen: is not properly sizing the window when display metrics change

### ISSUE THREAD

**Issue by bpasero** [electron/electron#15494]
* Output of `node_modules/.bin/electron --version`: 2.0.12
* Operating System (Platform and Version): macOS 10.14

**Expected Behavior**
When having a window in simple fullscreen and you change display metrics or change from 1 monitor to 2 the window should size according to the new dimensions.

**Actual behavior**
The window size does not change when display metrics change.

**To Reproduce**
* Run Fiddle: https://gist.github.com/bpasero/e4013ea83033a8c231f58f94c0df57c3
* Change display metrics or change monitor count

=> the window is wrongly sized now and needs a transition from normal back to fullscreen to recover.

**Comment by sofianguy** [comment]
@bpasero is this bug still present in version 4.x or later?

**Comment by bpasero** [comment]
@sofianguy reproduces with Electron 6.0.1

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by bpasero** [comment]
@electron-triage @nornagon @codebytere @sofianguy @samuelmaddock this reproduces in Electron 11 still. Our workaround in VSCode is still to do this:

https://github.com/microsoft/vscode/blob/bd272ea6b7485f62bfbe7a1833e82fc9f8f84214/src/vs/platform/windows/electron-main/window.ts#L472-L484

**Comment by bpasero** [comment]
This still reproduces for me with the provided Fiddle in Electron 11 and 12.

**Comment by codebytere** [comment]
@bpasero do you have a screencap? I just tried locally and could not

**Comment by bpasero** [comment]
@codebytere 

![recording (2)](https://user-images.githubusercontent.com/900690/116245055-d4967680-a768-11eb-99ec-27de2997d1a5.gif)

I think the change has just not been backported to Electron 12.
