### ISSUE TITLE
When copy the image that located on the computer, also copies image's name

### ISSUE THREAD

**Issue by SilencerWeb** [electron/electron#15492]
* Output of `node_modules/.bin/electron --version`: v3.0.6
* Operating System (Platform and Version): macOS High Sierra

**Expected Behavior**
When I copy an image that located on my computer, `clipboard.readText()` should return an empty string.

**Actual behavior**
Right now when I copy an image that located on my computer and call `clipboard.readText()`, it returns a name of the image that I copied. Because of this I cannot get which item was copied to the clipboard last - text or image.

**To Reproduce**
1. Copy any image that located on your computer.
2. Call `clipboard.readText()` and `clipboard.readImage()`

**Comment by MarshallOfSound** [comment]
@SilencerWeb `readText` attempts to cast the clipboard to the given type, so the textual representation of an image is its file name.  This is expected behavior from the OS side of things
