### ISSUE TITLE
Ability to get latest copied item no matter what type it is

### ISSUE THREAD

**Issue by SilencerWeb** [electron/electron#15491]
**Is your feature request related to a problem? Please describe.**
Right now there is no way to get the latest clipboard item no matter what type it is. `clipboard.readText()` returns latest copied text, `clipboard.readImage()` returns latest copied image but how to understand which item was copied to the clipboard last?

**Describe the solution you'd like**
Add a function like `clipboard.readLatestItem()` which will return the latest copied item no matter what type it is (image, text, bookmark or whatever).

**Describe alternatives you've considered**
Haven't found any alternatives so far :(

**Comment by MarshallOfSound** [comment]
@SilencerWeb You can use a combination of 

`clipboard.availableFormats()` and `clipboard.readBuffer(format)` you can get the latest item.

https://electronjs.org/docs/api/clipboard#clipboardavailableformatstype
