### ISSUE TITLE
printToPdf pageSize with only string on TypeScript

### ISSUE THREAD

**Issue by malexindigo** [electron/electron#15508]
* Output of `node_modules/.bin/electron --version`: **v3.0.6**
* Operating System (Platform and Version): **Windows 10 Home**

### Expected behavior

Print to pdf using custom page size in TypeScript code.

### Actual behavior

When I try to put my custom height and width and build the typescript code an error occurred with the next message:

`Type '{ height: number; width: number; }' is not assignable to type 'string'.`

### How to reproduce

Using the next code and build the project shows the error:

```javascript
mainWindow.webContents.printToPDF({
    pageSize: {
      height: 400,
      width: 400
    }
  }, (error, data) => {
    if (error) throw error
    fs.writeFile('./print.pdf', data, (error) => {
      if (error) throw error
      console.log('PDF escrito con éxito.')
    });
  });
```

**Comment by MarshallOfSound** [comment]
@malexindigo This is a documentation issue, the type specified in our docs is `String`, should be `String | Size` 🤔 

refs: https://github.com/electron/electron/blob/master/docs/api/web-contents.md

**Comment by malexindigo** [comment]
I think it is a missing definition for pageSize option, in the documentation says:

pageSize String (optional) - Specify page size of the generated PDF. Can be A3, A4, A5, Legal, Letter, Tabloid **or an Object containing height and width in microns.**

I modified the electron.d.ts direct in node_modules adding the following lines:

```javascript
  interface PageSize {
    height: number;
    width: number;
  }
  ...
  interface PrintToPDFOptions {
  pageSize?: string | PageSize;
  ...
```

with that works fine.
