### ISSUE TITLE
MediaRecorder records videos without duration

### ISSUE THREAD

**Issue by lcswillems** [electron/electron#15504]
* Output of `node_modules/.bin/electron --version`: v3.0.0-beta.12
* Operating System (Platform and Version): Kubuntu 18.10

**Expected Behavior**
After a video is recorded with MediaRecorder, when I open a video recorded with MediaRecorder, the video players (VLC on Linux, the one of Windows on Windows) don't find the duration of the video. This is very annoying because I can't go to a particular point in the video.

**Comment by MarshallOfSound** [comment]
This is an upstream Chromium issue, consider using H264 instead of webm

https://bugs.chromium.org/p/chromium/issues/detail?id=642012

**Comment by lcswillems** [comment]
I get the exact same issue when I set `video/webm;codecs=h264` as mime type for example.

**Comment by cuddeford** [comment]
I am having the same issue.

**Comment by liuzhenyilang** [comment]
me, too. Any resulotion can be given?
