### ISSUE TITLE
Please tell me why preload script not run。electron v3.0.7

### ISSUE THREAD

**Issue by pengqiangpeter** [electron/electron#15516]
mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences:{
      preload:`file://${__dirname}/preload.js`,
    }
  });

**Comment by pengqiangpeter** [comment]
find the reason. directory is not right
mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences:{
      preload:path.resolve(__dirname, 'preload.js'),
    }
  });

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
