### ISSUE TITLE
quickstart not launching in debian 9

### ISSUE THREAD

**Issue by prashantdawar** [electron/electron#15522]
* Output of `node_modules/.bin/electron --version`: v3.0.6
* Operating System (Platform and Version): Debian 9
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): ---

**Expected Behavior**
On npm start, electron quickstart expected to start normal on debian 9 , but it  only copy whats terminal is showing at movement.(See attached screenshoot, which shows the terminal output display copy in electron app launch window).

**Actual behavior**
Expected to fully launch electron quickstart app.

**To Reproduce**
node version: 11.0.0
https://github.com/electron/electron-quick-start.git

# Clone this repository
git clone https://github.com/electron/electron-quick-start

# Go into the repository
cd electron-quick-start
# Install dependencies
npm install
# Run the app
npm start

**Screenshots**
Application showing freezing electron window on launch of 'electron quicstart app' using 'npm start' which display current state of terminal and file browser that were behind of app window.

![screenshot from 2018-11-01 14-13-19](https://user-images.githubusercontent.com/2283741/47841725-9199f900-dde0-11e8-90d6-dafeb329a153.png)

**Comment by codebytere** [comment]
Please instead open this issue on the `electron-quick-start` repo.
