### ISSUE TITLE
[Might be a proposal] Blink External ArrayBuffer Crash

### ISSUE THREAD

**Issue by orange4glace** [electron/electron#15538]
As Electron is combination of chromium + node, N-API native module can be used in browser(Blink) process. It can [create an external ArrayBuffer](https://nodejs.org/api/n-api.html#n_api_napi_create_external_arraybuffer)
The problem is, [Blink does not allow external ArrayBuffer expect externalized one by Blink](https://chromium.googlesource.com/chromium/src.git/+/master/third_party/blink/renderer/bindings/templates/interface.cc.tmpl#1027).
In result, when external ArrayBuffer created by N-API is passed to Blink, such as `WebGLContext.texImage2D(ArrayBufferView)`, chromium crashes.
I don't know the exact reason why Blink does this but maybe kind of keeping it secure.
But Electron already unleashed sandbox of Blink and allowing external ArrayBuffer to be used would be not a big problem I think.
I can patch it If it can be consented.

**Comment by ckerr** [comment]
This issue hasn't been touched in quite awhile since it was filed. @orange4glace is this issue still relevant in newer versions of Electron?
