### ISSUE TITLE
Text replacements / expansions doesn't work on MacOS

### ISSUE THREAD

**Issue by Magistern** [electron/electron#15535]
on iOS and macOS there is a feature called Text replacements. If I type `:)` it could be replaced with 😊, or if I type**n@** it could expand to **name@domain.com**. It works in all applications, native or otherwise except Chrome and Electron apps (except Typora actually where it does work). 

Would it be possible to bypass what seems to be a chromium "bug" and still make it possible in Electron? I believe the native property is `automaticTextReplacementEnabled` on the NSTextView class. 
![screenflow](https://user-images.githubusercontent.com/33030442/47887152-34349500-de3e-11e8-8c5c-a84109ef9c3e.gif)

**Comment by MarshallOfSound** [comment]
This is implemented in userland.

https://www.npmjs.com/package/electron-text-substitutions

**Comment by socksy** [comment]
@MarshallOfSound what's the reasoning behind that? (Other than FOSS developer scratching their itch in user land). 

Surely a field on a NSTextView is preferable to a library that is reinventing the system by looking into the system preferences, finding the list of substitutions, and doing the substitution in JS?

Is it because of the underlying complexity of Chromium?

**Comment by MarshallOfSound** [comment]
@socksy Chromium doesn't use `NSTextView`s for it's text input.  This is a longstanding issue in Chromium which I've heard recently is going to get some traction but we're entirely dependent on this implementation.

https://bugs.chromium.org/p/chromium/issues/detail?id=42434

**Comment by socksy** [comment]
Thanks for the clarification!

**Comment by javan** [comment]
Chrome now has support for native text substitutions. Not sure if it was a Chrome or Chromium change, but maybe it's something Electron could pull in?

![Screen Shot 2020-06-18 at 11 07 56 AM](https://user-images.githubusercontent.com/5355/85037984-0d7ebb80-b154-11ea-9090-4cc2dd81902a.png)

**Comment by javan** [comment]
> This is a longstanding issue in Chromium which I've heard recently is going to get some traction but we're entirely dependent on this implementation.
>
> https://bugs.chromium.org/p/chromium/issues/detail?id=42434

@MarshallOfSound, it looks like that ^ issue has been resolved and Chromium seems to support text substitutions on macOS now (see my comment above). Could this issue be re-opened as a feature request? Or, would you like me to open a new one?

**Comment by mitchchn** [comment]
Would also like to see this added as a menu role, it seems the support is there in Chromium (and the substitutions do work even though the menu isn't present).
