### ISSUE TITLE
webview devTools not inspect

### ISSUE THREAD

**Issue by zhaobingss** [electron/electron#15539]
* Output of `node_modules/.bin/electron --`: 3.0.7
* Operating System (Platform and Version): win10 64bit
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 1.8.8

**Expected Behavior**
When active the insect button, and the mouse hover the webview inside html element it should highlight the elemrnt.

**Actual behavior**
Noting happen.

**To Reproduce**
Add a webview tag and open it's devTools.

**Screenshots**
[](url)
![qq 20181102132017](https://user-images.githubusercontent.com/14836112/47895264-53fda480-dea2-11e8-84ba-a23d811d2283.png)

**Additional Information**

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
