### ISSUE TITLE
system-ui resolves to wrong font for Arabic glyphs on macOS

### ISSUE THREAD

**Issue by inukshuk** [electron/electron#15533]
* Output of `node_modules/.bin/electron --version`:
3.0.6

* Operating System (Platform and Version):
macOS 10.13 High Sierra

**Expected Behavior**
This is a weird one: the best way (on macOS the only way?) to use the system's interface fonts is through the special `system-ui` CSS value; this is generally supported very well in Chrome/Chromium and Electron. Unfortunately, Electron picks the wrong font for Arabic script, namely Times New Roman, while Chrome/Chromium pick the right one (Arabic UI Display). This is problematic, because it's not possible to set this system font explicitly, since it's only available via `system-ui`.

**To Reproduce**
To reproduce this, render Arabic text using the `system-ui` font. In Electron, the Arabic glyphs are rendered using Times New Roman in Chromium and Chrome they will be rendered using Arabic UI Display. You can see this in the two screenshots below using Electron and Chromium (both using v66.0.3359.181).

**Screenshots**
<img width="1012" alt="electron" src="https://user-images.githubusercontent.com/325102/47880373-5f5dbb00-de23-11e8-9f02-bf29ad59ff68.png">
<img width="1014" alt="chromium" src="https://user-images.githubusercontent.com/325102/47880384-67b5f600-de23-11e8-9ff3-5dfaff3e8601.png">

**Comment by nornagon** [comment]
Possibly related to https://github.com/electron/electron/issues/15481?

**Comment by inukshuk** [comment]
This is fixed in Electron 5.0.
