### ISSUE TITLE
`createWriteStream` in `original-fs` is broken

### ISSUE THREAD

**Issue by adill** [electron/electron#15543]
* Output of `node_modules/.bin/electron --version`: v4.0.0-beta.6
* Operating System (Platform and Version): Windows 10 x64 Build 17134
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v3.0.7

**Expected Behavior**
`require('original-fs').createWriteStream('some/asar/file.asar')` should not error.

**Actual behavior**
The write stream fails with error: `Error: Invalid package some/asar/file.asar`

**To Reproduce**
I've forked `electron-quick-start` with the most trivial repro: https://github.com/adill/electron-quick-start/tree/demo-create-write-stream

**Comment by codebytere** [comment]
@adill we override most of `fs` to account for `asar`, which is most likely why you're running into this issue. Out of curiosity, what about `fs` is forcing you to use `original-fs` instead?

**Comment by ckerr** [comment]
Unfortunately reverting the reversion -- ie, `git revert 484140e22379db1fb458ed3a42778b5b66668748` -- still yields the same `Error: Invalid package` error. This needs more investigation.
