### ISSUE TITLE
net lib not work!!!!!!

### ISSUE THREAD

**Issue by printjs** [electron/electron#15545]
like below
![image](https://user-images.githubusercontent.com/17404628/47903984-70f4a080-debf-11e8-98e2-2b7dfc923180.png)

I use `import { net } from "electron"` in the main process,not renderer process.
```js
    const {net} = require('electron')
    const request = net.request('http://127.0.0.1:19921')
    request.on('response', (response) => {
      console.log(`STATUS: ${response.statusCode}`)
      console.log(`HEADERS: ${JSON.stringify(response.headers)}`)
      response.on('data', (chunk) => {
        console.log(`BODY: ${chunk}`)
      })
      response.on('end', () => {
        console.log('response请求中没有更多数据。')
      })
    })
   request.on("error",(error)=>{
        // the request err.
   })
    request.end()
```

so,how to reslove?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by printjs** [comment]
Problem terminator @MarshallOfSound Do not eliminate the problem, eliminate the person who raised the problem
