### ISSUE TITLE
nativeWindowOpen not properly working in manually built version

### ISSUE THREAD

**Issue by orange4glace** [electron/electron#15547]
* Output of `node_modules/.bin/electron --version`:  4.0.0-nightly-20181010 Release manually built
* Operating System (Platform and Version): Windows 10

**Expected Behavior**
```
// ./main.js
const {app, BrowserWindow} = require('electron')

app.on('ready', function () {
  win = new BrowserWindow({
    width: 1000,
    height: 600,
    webPreferences: {
      nativeWindowOpen: true,
      nodeIntegrationInWorker: true
    }
  });

  win.loadFile('index.html');
  win.webContents.openDevTools()
});
```
In created main browser,
`window.open()`
In created pop-up browser,
`window.require == ƒ require(path) { {... (node require)`

**Actual behavior**
`window.require` is undefined

**To Reproduce**
Manually build the latest electron version in release configuration (4.0.0-nightly-20181010).
Run the above program

npm version of electron (4.0.0-nightly-20181010) works correctly.
my own manually built version isn't working

Is there anything I missed?

Thanks.

**Comment by MarshallOfSound** [comment]
@orange4glace This is expected behavior on master, we made a change that child windows opened with `window.open` have `nodeIntegration` disabled by default.  cc @zcbenz

**Comment by orange4glace** [comment]
Thanks for the fast reply! I didn't notice that.

**Comment by orange4glace** [comment]
@MarshallOfSound Can I enable it? I'm capturing `new-window` event and returning new `BrowserWindow` with `webPreferences: nodeIntegration: true, sandbox: false` optino but It seems not working.
