### ISSUE TITLE
Cannot make setProxy pacScript work

### ISSUE THREAD

**Issue by wslx520** [electron/electron#15544]
Hi, although I'm a new comer but I have to say Electron is easy to use. A little question: 

I have a socks5 proxy in the LAN, and it works if I configure with `proxyRules`:

```js
    mainWindow.webContents.session.setProxy({
        proxyRules:"socks5://192.168.1.5:1080"
    }, function () {	
			mainWindow.loadURL('https://www.myip.com/');
	});
```
I can say my ip changed.

but when I tried to set a PAC script, everything was wrong. First thing was I didn't find demo code for 'pacScript' in documents, so I tried and searched by myself.

my `pac.js`:
```js
    function FindProxyForURL(url, host) {
        return "socks5 192.168.1.5:1080";
    }
```
and I have tried serval ways:
```js
    mainWindow.webContents.session.setProxy({pacScript: 'file:///D:/electron-quick-start/pac.js'}, function () {		
			mainWindow.loadURL('https://www.myip.com/');
	});
```
or
```js
    mainWindow.webContents.session.setProxy({pacScript: path.resolve('./pac.js')}, function () {	
			mainWindow.loadURL('https://www.myip.com/');
	});
```
or with a lccal server :
```js
    mainWindow.webContents.session.setProxy({pacScript: 'http://127.0.0.1/pac.js'}, function () {	
			mainWindow.loadURL('https://www.myip.com/');
	});
```
and I tried uppercase the `pac.js`:
```js
    function FindProxyForURL(url, host) {
        return "SOCKS5 192.168.1.5:1080";
    }
```
all above ways work in the same result: **the website loaded without proxy**.

EVEN I set a non-existed path to `pacScript`, it works in this way as well. so I don't know if the `pac.js` loaded properly or not.

the callback of `setProxy` can't accept arguments, so I know the proxy setting is failed but I can't know why..

Maybe just some typo in my code? or incorrect config params?

It makes me upset, anyone can give some help?

**Comment by val92130** [comment]
What electron version do you use? I had the same issue on 3.x but it seems to be working fine on  beta releases of 4.0 (tested on v4.0.0-beta.5)

**Comment by wslx520** [comment]
3.0.4 @val92130

**Comment by val92130** [comment]
Try v4.0.0-beta.5, it should work. I think it's a bug in 3.x

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
