### ISSUE TITLE
electron didn't launch even after npm start

### ISSUE THREAD

**Issue by tempegarit** [electron/electron#15556]
* Output of `node_modules/.bin/electron --version`: 3.0.7
* Operating System (Platform and Version): Windows 10
* Laptop: Asus

**Expected Behavior**
i expected that electron will launch an app because i ran a code which i clone from this https://github.com/electron/electron-quick-start . It is an official example code.

**Actual behavior**
It didn't show anything and it didn't show any error too. Here is a screen shoot of my command prompt.

![image](https://user-images.githubusercontent.com/44483328/47943367-4ee33880-df28-11e8-9779-04b6bc7ca988.png)

it just stopped there, produce sound like this https://www.youtube.com/watch?v=lNwnftRb9v0 , and then nothing happened.

I suspect there's something preventing electron to run, but i can't figure out what it is.

I've just step into this very first step, i got the app didn't launch, and i don't know what to do.

**Comment by xaviergonz** [comment]
I have the same issue with the newest electron, I have to call show twice for the main window to show now for some reason

**Comment by xaviergonz** [comment]
do you have node 11? it seems related to this:
https://github.com/electron/electron/issues/15467

**Comment by tempegarit** [comment]
@xaviergonz yeah, you're right mate. I have node 11. I forgot to mention node version above. I've edited my post. Your solution works. Thanks mate!

**Comment by MarshallOfSound** [comment]
This issue is fixed on master and will be fixed in the next release of Electron
