### ISSUE TITLE
Inactive Hover Regions

### ISSUE THREAD

**Issue by msavin** [electron/electron#15552]
I’ve recently come across an issue I suspect many are having: getting the macOS title bar buttons to react correctly when hovering over them on an inactive window. 

The “problem” is, the hover state does not get triggered when you move the mouse over an inactive window. 

I think a neat solution can be to create hover regions where the developer can run a function whenever someone hovers or clicks on a certain part of the inactive windows. 

With that, people can design native-like title bars and perhaps do more creative things.

**Comment by msavin** [comment]
And for that matter, we would need like “hotspots” for clicks also.. both clicks and hover regions would be triggered when mouse interacts with an inactive window

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
