### ISSUE TITLE
Electron fails to install on Windows 10 because of "self signed certificate in certificate chain"

### ISSUE THREAD

**Issue by hawkeye64** [electron/electron#15554]
npm install -D electron@2.0.0

> electron@2.0.0 postinstall C:\Git\System_Console\Sources\Apps\mp4player\node_modules\electron
> node install.js

Downloading electron-v2.0.0-win32-x64.zip
Error: self signed certificate in certificate chain
C:\Git\System_Console\Sources\Apps\mp4player\node_modules\electron\install.js:47
  throw err
  ^

Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:643:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@2.0.0 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@2.0.0 postinstall script.
Also happening with "npm install electron@latest"

**Expected Behavior**
Electron to install via npm

**Actual behavior**
It fails to install as per noted above.

**To Reproduce**
Steps provided above.

I've always worked on Ubuntu. Need to compile a windows version of the Electron app. This is Windows 10 clean machine. Installed Node (v8.12.0), NPM (6.4.1) and Git (for Windows). Checked out my source. Went to project folder and **npm install** and then gets error when installing electron.

Tried to re-install electron (as noted above) and same issue.

From package.json:
    "dependencies": {
        "axios": "^0.18.0",
        "chokidar": "^2.0.4",
        "imports-loader": "^0.8.0",
        "lodash": "^4.17.11",
        "mime-types": "^2.1.21",
        "moment": "^2.22.2",
        "plyr": "^3.4.5",
        "pretty-bytes": "^5.1.0",
        "snapsvg": "^0.5.1",
        "vue-i18n": "^7.3.3",
        "vue-plyr": "^4.0.0"
    },
    "devDependencies": {
        "babel-eslint": "^8.2.1",
        "devtron": "^1.4.0",
        "electron": "^2.0.0",
        "electron-builder": "^20.29.0",
        "electron-debug": "^1.5.0",
        "electron-devtools-installer": "^2.2.4",
        "electron-packager": "^12.2.0",
        "electron-toolkit": "^1.0.24",
        "eslint": "^4.18.2",
        "eslint-config-standard": "^11.0.0",
        "eslint-friendly-formatter": "^4.0.1",
        "eslint-loader": "^2.0.0",
        "eslint-plugin-import": "^2.9.0",
        "eslint-plugin-node": "^6.0.1",
        "eslint-plugin-promise": "^3.7.0",
        "eslint-plugin-standard": "^3.0.1",
        "eslint-plugin-vue": "^4.3.0",
        "quasar-cli": "^0.17.20",
        "strip-ansi": "=3.0.1"
    },

**Comment by MarshallOfSound** [comment]
Sounds like either

* You have a misconfigured proxy and the system doesn't trust one of your certificates
* Or... Someone is trying it MITM you with a self-signed cert 😆 

I've verified that the download still works on a clean windows box (spun one up in AWS for the sole purpose of testing this) so this will be something specific to your network connection 👍

**Comment by hawkeye64** [comment]
Could you possibly explain to me why this is only happening with Electron and not other NPM packages so I can give our sysadmin so relevant information?

**Comment by MarshallOfSound** [comment]
@hawkeye64 The electron install process on npm runs a script that downloads the Electron binary from github releases

**Comment by hawkeye64** [comment]
Thanks!

**Comment by mvictorl** [comment]
I have the same problem.
Corporate FW has MITM with self-signed cert.
I added FWs self-signed cert to Trusted CA (Windows) and applied:
_npm config set strict-ssl false_
All packages installs fine, only _electron_ has "**RequestError: self signed certificate in certificate chain**"

Any solution?

**Comment by nicecue** [comment]
I got the same problem here.
the error occurs only in electron project

**Comment by TobiasDomnik** [comment]
Same problem here, any news to this? Thx in advance

**Comment by antonylineesh1** [comment]
I am also facing the same issue

**Comment by lucashooten** [comment]
same issue, same situation.

**Comment by antonylineesh1** [comment]
any workaround for this?

**Comment by Craaftx** [comment]
For all the people seeking a solution. 
This is an error linked to **SSL validation**. Another error of SSL validation can appear at post-installation.

### Disable SSL validation ?
A lot of people recommending to use the command `yarn config set strict-ssl false` or `npm config set strict-ssl false`.

**This command disable SSL validation when making requests to the registry via https. It's a work around and not a long term solution + it's a security risk.**

Please instead, try to fix this properly by providing the **certificate file**.

First re-enable ssl strict if you had disabled it :

```shell
// With npm
npm config set strict-ssl true

// With yarn
yarn config set strict-ssl true
```

And then tell npm (or yarn) where to find the certificate file :

```shell
// With npm
npm config set cafile /path/to/certificate/file

// With yarn
yarn config set cafile /path/to/certificate/file
```

**What is cafile ?**
A file containing one or multiple Certificate Authority signing certificates. With .pem ending.

### Dealing with post-installation SSL error
The postinstall script of Electron is downloading a binary from a non-npm domain with the script [@electron/get](https://github.com/electron/get), for which the proxy may not be configured.

Desactivate SSL have no effect with a strong SSL policy.

You can desactivate the post-install script with the environment variable `ELECTRON_SKIP_BINARY_DOWNLOAD`
```
// With npm
ELECTRON_SKIP_BINARY_DOWNLOAD=1 npm install

// With yarn
ELECTRON_SKIP_BINARY_DOWNLOAD=1 yarn install
```

After that you will need to install manually the binaries. (I work on this part so I will edit this comment if I found a solution)

**Comment by krishna217** [comment]
@Craaftx  how to install manually the binaries ?

**Comment by laurejo1** [comment]
@Craaftx many thanks for your solution, I am not sure to understand the next steps to install electron. 

following your post, here is what I did (I am on windows): 

- in a command prompt you can run: 
setx ELECTRON_SKIP_BINARY_DOWNLOAD 1

- close the command prompt and open a fresh command prompt, now you should see: 
echo %ELECTRON_SKIP_BINARY_DOWNLOAD%

back to the electron-quick-start-example:
npm install is working fine (no more error as other people described) but then npm start is failing. 

Any suggestions? 


C:\Users\laurejo1\electron-quick-start\node_modules\electron\index.js:17
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again');
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (C:\Users\laurejo1\electron-quick-start\node_modules\electron\index.js:17:11)
    at Object.<anonymous> (C:\Users\laurejo1\electron-quick-start\node_modules\electron\index.js:21:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\laurejo1\electron-quick-start\node_modules\electron\cli.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    
![image](https://user-images.githubusercontent.com/89907278/195543869-692e3474-e91e-4744-9c81-1600f84d2244.png)

**Comment by laurejo1** [comment]
@krishna217, the next steps are to 

- [download the electron bin](https://github.com/electron/electron/releases) corresponding to your system  
- unzip it into a folder "dist" inside your folder electron-quick-start\node_modules\electron\ 
- create a path.txt file inside your folder electron-quick-start\node_modules\electron\ 
- path.txt should only contains this text: electron.exe

Then cd electron-quick-start and npm start to launch the demo app.

**Comment by lgibso34** [comment]
`NODE_TLS_REJECT_UNAUTHORIZED=0 yarn global add electron` worked for me

**Comment by kionpark** [comment]
저도 동일한 증상으로 고민했었습니다.
금융기관의 내부에서 일하고 있는데, 이문제를 해결하기 위해 저는 VPN으로 우회하여 재시도해서 성공했습니다. 아마도 여러단계의 네트웍을 지나는 이유로 발생한 인증 문제로 보입니다.

I also suffered from the same symptoms.
I work internally at a financial institution, and to resolve this issue, I bypassed the VPN and retried with success. It appears to be an authentication issue that probably occurred because it went through multiple stages of the network.

**Comment by ciberponk** [comment]
set NODE_TLS_REJECT_UNAUTHORIZED=0
works for me (Windwos 10)
