### ISSUE TITLE
Add error information to webContents.print() callback

### ISSUE THREAD

**Issue by alexb148** [electron/electron#15568]
I've been having some problems getting webContents.print() to work on some machines, but at present there's no way to determine what the error is - the callback simply returns a true or false boolean.

A more detailed error log would be incredibly useful, is it possible to get more info returned if something goes wrong?

The function referenced is in your docs here:

https://github.com/electron/electron/blob/master/docs/api/web-contents.md#contentsprintoptions-callback

**Comment by codebytere** [comment]
Closed by https://github.com/electron/electron/pull/19000.

**Comment by popod** [comment]
@codebytere #19000 is a very useful thing !

But would it be possible to return even more informations about the error ? In the case where `failureReason ` value is `failed` ? Something like the error code and/or message ?

Thanks for reply :)
