### ISSUE TITLE
Can not sign MAS because incorrect the Login Item App in the Mas source 4.0.0

### ISSUE THREAD

**Issue by mulyk** [electron/electron#15567]
* Output of `node_modules/.bin/electron --version`: v4.0.0-beta.6
* Operating System (Platform and Version): MacOS

We expect an '**Electron Login Helper.app**' in the **LoginItems** folder.
But the mas source (https://github.com/electron/electron/releases/download/v4.0.0-beta.6/electron-v4.0.0-beta.6-mas-x64.zip) contains only the **Content** folder.

<img width="544" alt="screen shot 2018-11-05 at 4 52 31 pm" src="https://user-images.githubusercontent.com/4363415/48001967-36873f80-e11b-11e8-9f89-239dd071262a.png">

**Comment by codebytere** [comment]
This PR originally implemented this functionality; perhaps something has changed: https://github.com/electron/electron/pull/10856

**Comment by nornagon** [comment]
Yeah, it looks like the login helper configuration got messed up in the switch to GN.
