### ISSUE TITLE
Notifications cause crash on Windows 7

### ISSUE THREAD

**Issue by blingenau** [electron/electron#15570]
* Output of `node_modules/.bin/electron --version`: 2.0.12
* Operating System (Platform and Version): Windows 7 x64
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): None

**Expected Behavior**
I have 2 webviews loading the same HTML page. Each page displays a notification with the same tag, and tries to close it after a timeout. Imagine you have 2 facebook messenger tabs open and you get a message and they both try to send you a notification. What SHOULD happen is that a single notification displays, it closes after a timeout, and we're all happy.

**Actual behavior**
What ACTUALLY happens is that when the page tries to close the notification, the app crashes with a seg fault. When using crash reporting on our actual application, the error we get is `EXCEPTION_ACCESS_VIOLATION_READ` and the top of the error stack is `brightray::Win32Notification::Dismiss()` located at `brightray/browser/win/win32_notification.cc:57`.

**To Reproduce**
Find a minimal example here https://github.com/blingenau/electron-quick-start

I'm guessing this is due to electron's Notifications implementation on Windows 7. It must not gracefully handle closing notifications that have already been closed. The key here is that both notifications have the same tag. I'm guessing that the 2nd notification being created closes the 1st since they have identical tags. Then when the 1st notification tries to close, it seg faults.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
