### ISSUE TITLE
Electron Login Helper moved out of Electron Login Helper.app causing codesign failure in mac builds

### ISSUE THREAD

**Issue by rr326** [electron/electron#15580]
* Output of `node_modules/.bin/electron --version`: v4.0.0-beta.6
* Operating System (Platform and Version): macos 10.14 (18A391)
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v3.0.5

**Expected Behavior**
My app should build and sign without error, as it has done many times.

**Actual behavior**
Codesigning fails. 
`Error: Command failed: codesign --sign C706993845BB96DBE90EF9DC927A955FBAF62731 --force --entitlements build/entitlements.mac.inherit.plist /Users/rrosen/dev/filing/dist_prod_dist/mas/FileSimple.app/Contents/MacOS/FileSimple
/Users/rrosen/dev/filing/dist_prod_dist/mas/FileSimple.app/Contents/MacOS/FileSimple: code object is not signed at all
In subcomponent: /Users/rrosen/dev/filing/dist_prod_dist/mas/FileSimple.app/Contents/Library/LoginItems/Contents/_CodeSignature/CodeResources`

**To Reproduce**
I'm sorry - I don't know how to do build a repo you can check.
This is cross linked to electron-builder bug [#3425](https://github.com/electron-userland/electron-builder/issues/3425)
I'm not sure if this is a electron builder or electron bug, but @devlar and @nornagon seem to think it is electron. 

From the ebuilder issue:
> @nornagon I see your commit [electron/electron@e22a80b](https://github.com/electron/electron/commit/e22a80b210b4b6087e8dbbe22c895df93ca5f7ff) Was moving `Electron Login Helper` out of `Electron Login Helper.app` intentional change or bug?
> 
> electron 4:
> 
> <img alt="screenshot 2018-10-28 at 09 46 10" width="1343" src="https://user-images.githubusercontent.com/350686/47613841-5329d480-da96-11e8-97dc-30561397030d.png">
> 
> electron 3:
> 
> <img alt="screenshot 2018-10-28 at 09 46 51" width="291" src="https://user-images.githubusercontent.com/350686/47613848-6b015880-da96-11e8-924e-2a3e1a3f654d.png">

**Additional Information**
I'm happy to give more info, or if this really is a electron-builder bug please let me know.

**Comment by nornagon** [comment]
See also #15567

**Comment by nornagon** [comment]
This should be solved by #15610.
