### ISSUE TITLE
Clipboard reads multiple pictures. 

### ISSUE THREAD

**Issue by bruce-gou** [electron/electron#15584]
* Output of `node_modules/.bin/electron --version`: ^3.0.6
* Operating System (Platform and Version): macos 10.13.5 
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): ^3.0.6

**Expected Behavior**
I hope the clipboard can read more than one picture at a time.
**Actual behavior**
At present, only one picture can be read out.     'clipboard.readImage()'

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you've responded, please link to the test case and @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
