### ISSUE TITLE
Electron bluetooth errors

### ISSUE THREAD

**Issue by 4eveRS** [electron/electron#15603]
* Output of `node_modules/.bin/electron --version`: 4.0.0-beta.7
* Operating System (Platform and Version): OS X Mojave 10.14.1
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): Never seen it work in any version available

**Expected Behavior**

webContents select-bluetooth-device should allow to select a device from the list and pair it.

**Actual behavior**

- When you try to pair a device in a webview, electron throws an error and force exit.
- The deviceList only contains/shows 1 device, even when there's multiple BLE devices (Chrome shows all of them).

**To Reproduce**
https://gist.github.com/4eveRS/9ade679271cc536da97b692492e048af

**Additional Information**
If there's no easy fix for this issue, is it possible to disable bluetooth support at all ?
Tried with 

```
app.commandLine.appendSwitch('enable-web-bluetooth', false);
app.commandLine.appendSwitch("enable-experimental-web-platform-features", false);
```

and it didn't work.

**Comment by 4eveRS** [comment]
After testing even further, I found out that there's no issue on the device selection.

In order to prevent default device selection on the select-bluetooth-device listener, it requires a listener on the main file just like in the renderer (preventing the default action).

But still, electron only finds 1 device instead of finding multiple devices.

**Comment by codebytere** [comment]
@4eveRS can you please update the gist accordingly? once that's done I can take a look at the single-device discovery issue.

**Comment by ckerr** [comment]
@4eveRS bump, do you have time to update that gist?

**Comment by 4eveRS** [comment]
Hello @codebytere and @ckerr , after further inspection on this issue, I found out that preventing default event in the main process stopped this issue (I was not allowing the event to run over time, stopping it once it got the first deviceList),  now it lists more than 1 device but it opens up to another issue.

The new issue is that the eventListener deviceList adds the same device multiple times at each "tick" that is searches for new devices.

For example:

```
[0] DeviceId:"88:11:42:77:0C:DE", deviceName:"",
[1] DeviceId:"88:11:42:77:0C:DE", deviceName:"",
[3] DeviceId:"88:11:42:77:0C:DE", deviceName:"",
[4] DeviceId:"88:11:42:77:0C:DE", deviceName:"Mi Band 2",
...
```

In order to get the correct device name, I need to group the deviceList results after approx. 1min (search timeout defined by the eventListener) and search for the last occurrence of each device to get its updated name. (I'm doing this with a watcher and lodash in Vue)

I think that this action should be handled by Electron and not by the user, as it would provide a better and cleaner output (deviceList) for the user to work.

If you want I can update the gist to show this issue.
