### ISSUE TITLE
dialog.showMessageBox(null, options) can loose focus and be hidden

### ISSUE THREAD

**Issue by albu77** [electron/electron#15604]
* Electron v1.8.1
*Windows 7 64 bits
*
**Expected Behavior**
Normally such a dialog(whithout callback) which is blockin should keep focus to show to the user the app is waiting for an action

**Actual behavior**
If I clik outside of the dialog box (inside the browser window) I get the browserwindow on top, no action possible since the dialog is blocking (and that is ok) but the user doesn't see anymore the dialog which is under

You can fork [electron-quick-start](https://github.com/electron/electron-quick-start) and include a link to the branch with your changes.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone $YOUR_URL -b $BRANCH
$ npm install
$ npm start || electron .
```
**Screenshots**

**Additional Information**

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
