### ISSUE TITLE
v3.0.8 breaks ability to hide the window menu

### ISSUE THREAD

**Issue by vladimiry** [electron/electron#15601]
version: v3.0.8
platform: Linux x64. Didn't try the case on other platforms, might also be affected.

There is no such issue with v3.0.7 or below versions.

**Expected Behavior**
`mainWindow.setMenu(null);` is working.

**Actual behavior**
`mainWindow.setMenu(null);` doesn't take an effect.

**To Reproduce**
Disable the menu as `mainWindow.setMenu(null);` call on [this](https://github.com/electron/electron-quick-start/blob/fbc0cb7f9c7b33f6a86140c1c6089099948b3ab2/main.js#L11) line.

**Comment by nitsakh** [comment]
Dang! That's completely my fault and I'll fix it right away. Didn't realise that `null` disables menu on linux.

**Comment by vladimiry** [comment]
Btw, setting `null` is supposed to disable menu on any platform, not just on Linux, ref https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winsetmenumenu-linux-windows

**Comment by codebytere** [comment]
Closed by https://github.com/electron/electron/pull/15605.

**Comment by bluenote10** [comment]
I observe the same issue with versions 4.0.1 and 4.0.4 under Linux. Can this issue be reopened?

**Comment by vladimiry** [comment]
@bluenote10 see here:
- https://github.com/electron/electron/issues/15901
- https://github.com/electron/electron/issues/16747
- https://github.com/electron/electron/issues/16521

**Comment by codebytere** [comment]
@vladimirkononov @bluenote10 i've opened a PR to fix the second issue (https://github.com/electron/electron/issues/16747) it should be in master and in releases of 5 and 4 soon!
