### ISSUE TITLE
I'm getting this error when I submit the app to the ITunes Mac Store; The ITunes submission guide seem to be not covering this case. Any ideas ?

### ISSUE THREAD

**Issue by Little-cute** [electron/electron#15617]
* Electron Version: 

**Rejection Email**
Deprecated API Usage - Apple no longer accepts submissions of apps that use QuickTime or QTKit APIs.
Electron version: 2.0.12
Operating system: OSX
**Additional Information**

**Comment by codebytere** [comment]
@Little-cute, this doesn't give us enough information to effectively determine the locus of the issue and potential steps we can take to mitigate it. Please provide more detail and specifics about your apps and how it could be leveraging these APIs.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
