### ISSUE TITLE
endless high CPU spike

### ISSUE THREAD

**Issue by bitdisaster** [electron/electron#15611]
* Output of `node_modules/.bin/electron --version`: 3.0.8 
* Operating System (Platform and Version): x64 Win7, 8.1, Server 2012 R2, Win 10 (Win 10 almost not reproducible)
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2.0.x

**Expected Behavior**
CPU load should not be significant higher than Electron 2.0.x. After initial CPU load the process should return to idle.

**Actual behavior**
CPU load is higher than it used to be on Electron 2.0.x. The process enters a state of "endless" CPU consumption.

**To Reproduce**
```
> git clone https://github.com/bitdisaster/electron-quick-start.git -b high_cpu_load_bug
> npm install
> npm run start 
```

The likelihood of this bug depends on the initial available CPU resources and the Windows version. I had the best luck with Windows 8.1 and 1 CPU. However, I was able to repro this on other Windows versions and with more CPUs. 

1.  Launch App
2.  Observe CPU (if not at 100% continue with step 3)
3.  Search for something
4.  Scroll result page

**Screenshots**
![cpuload](https://user-images.githubusercontent.com/5191943/48101202-174fe700-e1db-11e8-85e8-82d9af55b039.gif)

**Additional Information**
Trace:
`--trace-startup --trace-startup-file=trace.json --trace-startup-duration=45`
[trace.zip](https://github.com/electron/electron/files/2555690/trace.zip)

**Comment by spiral2k** [comment]
i'm suffering from this to, checked with two different Macbooks

**Comment by bitdisaster** [comment]
Will, do when I'm back home on my main dev machine. 🤞

**Comment by bitdisaster** [comment]
I can confirm that its fixed for my repro. However, we still see the same symptoms on a multicore system with Slack Desktop App. There are multiple renderer processes that do nothing. But 2 processes keep running at full blast. Is there a possibility that this fix could extend to multi-core machines?

**Comment by chevonc** [comment]
Hey @bitdisaster :). Did you get this resolved by any chance?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
