### ISSUE TITLE
electron mac Excessive CPU process:electron Helper

### ISSUE THREAD

**Issue by loveburning** [electron/electron#15616]
* Output of `node_modules/.bin/electron --version`:2.0.4
* Operating System (Platform and Version): mac 10.14

electron mac Excessive CPU 

Especially when they open the webview
Discovery process electron-Helper
![51f7a5ec13cd77e353f864d9fe9baeff](https://user-images.githubusercontent.com/24245193/48118710-0620dc00-e2a8-11e8-9215-3ead0465f27d.jpg)

**Comment by nornagon** [comment]
This is not enough information to make any sort of determination about what's going on.

What app are you running? Is it doing anything that might cause the CPU usage to be high (like running a tight IPC loop or timer?)

We can't help unless we can understand what might be causing the issue. Will reopen if we get more details.

**Comment by loveburning** [comment]
Didn't have a lot of circulation ,Also don't have a lot of logic , Simply render the webview , The introduction of the Electron-vue , But I think this should not cause , The problem of high CPU Only in the operation of the webview especially, I tried to update version 2.0.13 , But I still have this problem

**Comment by loveburning** [comment]
@nornagon Didn't have a lot of circulation ,Also don't have a lot of logic , Simply render the webview , The introduction of the Electron-vue , But I think this should not cause , The problem of high CPU Only in the operation of the webview especially, I tried to update version 2.0.13 , But I still have this problem
