### ISSUE TITLE
how to run electron app in terminal of linux without GUI support

### ISSUE THREAD

**Issue by mccoysc** [electron/electron#15614]
how to run electron app in terminal of linux without GUI support

**Comment by mccoysc** [comment]
some one said maybe i should use nodejs instead of electron.
but in fact, nodejs have no "DOM" elements and HTML5 support and so on,these feature is needed by my project.

**Comment by noseratio** [comment]
@mccoysc , look at [Headless Chrome](https://developers.google.com/web/updates/2017/04/headless-chrome), maybe that's what you need.

**Comment by probablyup** [comment]
If you need the DOM but aren’t doing any layout calculations, JSDOM might be a decent solution as well for what limited DOM work you need to do.

I agree though that for a terminal app it probably makes more sense to go full JS than include a browser stack to indirectly run JS.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
