### ISSUE TITLE
docs: "Releasers" link broken

### ISSUE THREAD

**Issue by jacobq** [electron/electron#15621]
In [`docs/development/pull-requests.md`](https://github.com/electron/electron/blob/8ba271efba691357ab1970c1a553b4e019125574/docs/development/pull-requests.md#continuous-integration-testing) there is a link that looks like it should point to a page listing members of the "Releasers" team, but clicking the link results in a 404 error.
https://github.com/orgs/electron/teams/releasers/members

**Comment by doms** [comment]
@jacobq 👋 

The link is not broken per se, it's moreso how GitHub orgs & teams work! In its current implementation, if you are not apart of the organization (e.g. Electron), then you will not be able to see the teams that are within the organization.

So while the link may appear to be broken to outsiders, the link works normally for people who are apart of the organization.

I see how this can be confusing. 🤔 Maybe [docs/development/pull-requests.md](https://github.com/electron/electron/blob/8ba271efba691357ab1970c1a553b4e019125574/docs/development/pull-requests.md#continuous-integration-testing) could be re-worded to say something like "_only members of the Release team **within Electron** can restart a CI run_" (that way the link is not needed and people not within the org won't be mislead to believe that it's broken)

**Comment by jacobq** [comment]
OK, but then the larger problem is this one: "How do I know who I should reach out to in order to request a restart of a failed CI build?"

**Comment by doms** [comment]
@jacobq 

After a quick look at your code (and the [CODEOWNERS](https://github.com/electron/electron/blob/e9ba26f50ed2a38ada19469951c1eeaf346ef152/.github/CODEOWNERS#L7) file), I believe you can request a review from `@electron/reviewers` and one of the members of the team will get to you when they get the chance!

**Comment by jacobq** [comment]
@doms Thanks for the reply. So would it make sense if that document were modified to also include a line like, "To request that a failed CI job be restarted, mention @electron/reviewers in the PR comments and explain why you believe the job should not have failed."

**Comment by jacobq** [comment]
I'm going to close this since I don't think any further action is needed. If someone else gets confused then hopefully they can find this issue and have some time for a PR or something.
