### ISSUE TITLE
angular cli 7, ipcRenderer, Can't resolve 'fs'

### ISSUE THREAD

**Issue by Sevyls** [electron/electron#15639]
* Output of `node_modules/.bin/electron --version`: v3.0.7
* Operating System (Platform and Version): macOS 10.14.1
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): n/a

I am trying to build an electron app with angular 7 and ipc communication between electron and the webapp.

**Expected Behavior**

Angular-cli removed node globals, ng build does not include shims any more
 https://github.com/angular/angular-cli/issues/9827

No build issues should occur due to this change.

**Actual behavior**
Running a build results in the following error

```
 ng build
                                                                                          
Date: 2018-11-08T09:16:40.909Z
Hash: 1929e4018a5a750f256e
Time: 14862ms
chunk {main} main.js, main.js.map (main) 34.2 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 223 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 407 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 7.02 MB [initial] [rendered]

ERROR in ./node_modules/electron/index.js
Module not found: Error: Can't resolve 'fs' in '###/node_modules/electron'
ERROR in ./node_modules/electron/index.js
Module not found: Error: Can't resolve 'path' in '###/node_modules/electron'

```

**Comment by MarshallOfSound** [comment]
@Sevyls `node_modules/electron/index.js` should never be loaded inside an Electron app.  The `electron` module needs to be added to your / angular's webpack config external module list 👍

**Comment by Sevyls** [comment]
Thank you

**Comment by absalonv** [comment]
@MarshallOfSound sorry if this is obvious, but if I am not using webpack, is there another way to get this working?

**Comment by shinde-ha** [comment]
@MarshallOfSound @absalonv @Sevyls  is there an alternative method to execute rather than using webpack? The config.js produced via ng eject is deprecated and I don't want to rely on 3rd party libraries. I can understand using electron.remote does not produce any errors with regards to a ts component but electron/index.js is having some issues. Any help will be appreciated!

**Comment by shinde-ha** [comment]
> require('electron') st

Can you elaborate more on this please?

**Comment by shinde-ha** [comment]
> this was related to a require('electron') statement, thanks for your very prompt response! Have a great day

@Sevyls  Can you elaborate more on this please?

**Comment by BenjaminPiette** [comment]
Summary of what I've found at https://dev.to/michaeljota/integrating-an-angular-cli-application-with-electron---the-ipc-4m18.

Create src/typings.d.ts:
```
declare type NodeRequire = any;

interface Window {
    require: NodeRequire;
}
```
 
In component:
```
constructor() {
    let ipcRenderer = window.require('electron').ipcRenderer;
    ipcRenderer.send("Test", {hey:"hey"})
  }
```

Worked for me.
