### ISSUE TITLE
electron cpu High occupancy

### ISSUE THREAD

**Issue by loveburning** [electron/electron#15651]
* Output of `node_modules/.bin/electron --version`:2.0.13
* Operating System (Platform and Version):mac 12.14

* hello, I use the electron has developed a background system,I use the electron-vue and element-ui,
I found that in some cases there will be a high CPU usage , I have found the causes of this problem , But because of limited technology I can only give up temporarily Some effects

* In the use of element-ui, The library contains  css Animation effects, At the beginning of the animation, The CPU will occupy more than 100% ,The end of the animation Everything is back to normal

* Mainly appear in this issue In MAC 13" No graphics version , In the 15 inch MAC Would be much better , I suspect because of problems caused by the gpu to render , Everything is fine on windows

**Comment by nornagon** [comment]
Please add this as a comment on your original issue (#15616) instead of opening new issues.
