### ISSUE TITLE
terminal in my Electron App

### ISSUE THREAD

**Issue by prashantjeetsingh** [electron/electron#15668]
Hi,

My requirement is:
I want to add a link to my index.html and upon clicking on that link I want a terminal where I can run terminal commands ( all features of the terminal like autosuggestion etc.,)
How can I achieve it?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
