### ISSUE TITLE
Basic-auth is broken with empty string usernames and/or passwords

### ISSUE THREAD

**Issue by torywheelwright** [electron/electron#15663]
* Output of `node_modules/.bin/electron --version`: v3.0.8
* Operating System (Platform and Version): I wrote this minimal reproduction and tested it on MacOS 10.14.1, but I have also observed this issue on Windows 10.

**Expected Behavior**
When making an HTTP request and presented with a `login` event, calling the provided callback with a username and password should ultimately cause a `response` event with a success status code if the credentials were accepted and the request was successful. If the credentials were incorrect, i.e. the server responded again with a 401/407, another `login` event is emitted, ad infinitum.

**Actual behavior**
If the callback is called with a username, password, or both that are the empty string, a `response` event with a 401/407 status code is emitted (regardless of whether the credentials are correct). Further `login` events are not emitted.

**To Reproduce**
Run these commands to get setup:
```sh
git clone https://github.com/torywheelwright/electron-quick-start.git`
cd electron-quick-start
npm install
cd pub
```

Now, launch a test server that we will attempt to basic auth against from the `pub` directory in the repo like this:
`../server.py 8888 username:password`

Set the `USERNAME` and `PASSWORD` constants at the top of `main.js` to those used to in the command to launch the server.

From a second terminal, `npm start` from the root of the repo.

You should observe a 200 response code if neither the username nor password are the empty string. Otherwise, you'll get a 401, indicating that these credentials aren’t being propagated to the server.

**Additional Information**
The same issue occurs trying to auth against a proxy server, but the response code is 407 instead of 401.

I know that this is also broken in v1.8.8, which is what's used in the project where I discovered this.

These tests were done with:
Python 2.7.15
Node 6.5.0
Chrome 70.0.3538.77, in order to verify that it handles these auth scenarios correctly, and the functionality of the test server.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
