### ISSUE TITLE
Ability to see a BrowserWindow with configuration options / variables.

### ISSUE THREAD

**Issue by burtonator** [electron/electron#15661]
**Is your feature request related to a problem? Please describe.**

I'd like the ability to specify a set if variables that can be gifted to a BrowserWindow for the duration of that window..  Regardless of redirects, etc.  These should also be present for new windows, iframes, and webviews created off of that window.

I'd like to do this to give state from main to my windows without complex configuration of messages and IPC.  

It should be possible to do this in the BrowserWindow constructor options.

There are some nice security implications for this. Specifically the remote module wouldn't need to be loaded for communication between main and the renderer.  You wouldn't need to use any type of node modules either.

It might be nice to just declare this as either a variable or via a package that you can require.

**Comment by ckerr** [comment]
@miniak this issue hasn't been touched in quite awhile. Should it be closed, or is it something that should still be done?
