### ISSUE TITLE
Intermittent crash on startup

### ISSUE THREAD

**Issue by webarchymeta** [electron/electron#15678]
* Version: 4.0.0-beta.x
* Operating System: Windows 10 (1809)
* Working Version: 3.0x

**Expected Behavior**
Open the main browser window and start the debugger on lanch

**Actual behavior**
Crashes or freezes at random time. The following is the exception thrown when it crashes:
```
[4728:1112/025455.764:ERROR:CONSOLE(75)] "Uncaught (in promise) TypeError: Cannot read property 'length' of null", source: chrome-devtools://devtools/bundled/data_grid/data_grid_module.js (75)
Segmentation fault
```
In addition, the electron process does not fully exit and the residue process takes large amount of CPU cycle.

**To Reproduce**
Start an electron app multiple times with `openDevTools()` called on the opened window. In my case, the initial page is a login page with a password (type of input) field and the crash or freeze most likely occurs during typing in of password

**Comment by BinaryMuse** [comment]
Hi, @webarchymeta. I spent some time today with [Electron Fiddle](https://github.com/electron/fiddle) trying to reproduce this issue. Here is the code I was using: https://gist.github.com/BinaryMuse/2765f907a95d4357ce3548635b7adecf. During my testing, I was able to get Electron to neither crash nor freeze. If you have a specific, minimal example that reproduces this behavior, please share it here and I will continue to look into it. Otherwise, this could be pretty difficult to track down.

**Comment by brenca** [comment]
@webarchymeta @BinaryMuse I also tried to repro and couldn't, it's most likely something about that site/form that's triggering the crash. I couldn't really dig out anything from the line that's referenced in the error log line either.

**Comment by webarchymeta** [comment]
Yeah, I could be that the specific form of my app is causing the crash. It happened once in the early beta version of 2.0.x and then somehow disappeared when the 2.0.x is finally released. Now it appear again in 4.0.0-beta.x. It crashed once more than 7 hours ago.

The "Segmentation fault" may not be related to the exception(s) thrown since there more of such kind of exceptions been thrown than the number of crash, which is less frequent. It crashes on both of my Windows 10 (64bit) machines. The following is another kind of exception seen:
```
[12204:1120/065149.493:ERROR:CONSOLE(5068)] "Cannot find context with specified id", source: chrome-devtools://devtools/bundled/shell.js (5068)
```
The "random" crashes happen at startup, if such a stage is passed, there is no problem (crash) found. I don't think there is anything fancy in the login form though ...

OK, I will try to find a reproduce minimum example, if I could ...

**Comment by webarchymeta** [comment]
@brenca: After some digging exception related to first "Uncaught (in promise) TypeError" is correlated to my action of opening up the some of the WebSQL database tables inside "Applications" panel of the chrome-devtools page of the debuger. Therefore it most likely to not the cause of the Segmentation fault found ...

**Comment by webarchymeta** [comment]
I changed the way in which the `openDevTools` is invoked from
```
mainWindow.loadURL('file://' + __dirname + '/index.html');
mainWindow.openDevTools();
```
to 
```
mainWindow.webContents.openDevTools();
mainWindow.loadURL('file://' + __dirname + '/index.html');
```
I will continue work on our app for a few days. If there are no more crash found, I am going to close this issue report.

**Comment by webarchymeta** [comment]
it appears that the released version no longer crashes ...
