### ISSUE TITLE
Unmaximize and maximize event cli bug

### ISSUE THREAD

**Issue by CreatorVilius** [electron/electron#15676]
* Output of `node_modules/.bin/electron --version`: 3.0.3
* Operating System (Platform and Version): Windows 10

### Expected behavior

unmaximize and maximize events shouldn't type anything in cli

### Actual behavior

I keep getting

```
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: app.js:29:5
Remote event names: maximize
Attempting to call a function in a renderer window that has been closed or released.
Function provided here: app.js:33:5
Remote event names: unmaximize
```

in cli

### How to reproduce

Make external js file which contains

```js
app.on('maximize', () => {
    
})

app.on('unmaximize', () => {
    
})
```

and try unmaximizing and maximizing...

### Comment

I always kept getting this error and it became so annoying right now.

**Comment by codebytere** [comment]
@CreatorVilius 'maximize' is an event emitted by the `BrowserWindow`, not `app`. See [documentation](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#L480) for more information.

**Comment by CreatorVilius** [comment]
I use BrowserWindow, but it's defined as `app`

**Comment by kaysonwu** [comment]
@CreatorVilius Did you solve it?
