### ISSUE TITLE
axios post file not work in electron, but work in regular node run.

### ISSUE THREAD

**Issue by lalawila** [electron/electron#15679]
- Output of node_modules/.bin/electron --version: v2.0.4
- Operating System (Platform and Version): MacOS 10.13.6
- Output of node_modules/.bin/electron --version: v2.0.4

```
const FormData = require('form-data');
const fs = require('fs');
const axios = require('axios');

let form = new FormData();
form.append('file', fs.createReadStream('/Users/lalawila/project/my-project/t.png'), {
    filename: '111.png'
});
axios.put('http://127.0.0.1:9000/api/tasks/667', form, {
    headers: form.getHeaders()
}).then(response => {
    console.log(response);
}).catch(error => {
    if (error.response) {
        console.log(error.response);
    }
    console.log(error.message);
});
```
The same code I  write in main.js file the entry file in electron-vue my server can't get file, but in regular js file use node xxx.js to run work!
below is headers get in server, can see the obvious difference.
```
run in electron
EnvironHeaders([('Host', '127.0.0.1:9000'),
 ('Connection', 'keep-alive'), 
('Content-Length', '17'), 
('Accept', 'application/json, text/plain, */*'), 
('Origin', 'http://localhost:9080'), 
('User-Agent', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Electron/2.0.13 Safari/537.36'), 
('Content-Type', 'multipart/form-data; boundary=--------------------------475282663218124920413172'),
 ('Referer', 'http://localhost:9080/'),
 ('Accept-Encoding', 'gzip, deflate'), 
('Accept-Language', 'en-US')])


regular run
EnvironHeaders([('Accept', 'application/json, text/plain, */*'),
 ('Content-Type', 'multipart/form-data; boundary=--------------------------229931669302367684203441'), 
('User-Agent', 'axios/0.18.0'),
 ('Host', '127.0.0.1:9000'), 
('Connection', 'close'), 
('Transfer-Encoding', 'chunked')])

```
thx!

**Comment by MarshallOfSound** [comment]
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.

**Comment by janakhpon** [comment]
Could anyone please suggest me what to do with axios post request not working in electron and any alternative way to make post request in electron . 
Please ....

**Comment by morphisjustfun** [comment]
The same error happens to me
