### ISSUE TITLE
Get OS window handle of input text control 

### ISSUE THREAD

**Issue by DucManhPhan** [electron/electron#15681]
I have a case that needs to directly connect with the Input Method Editor in Window OS. There are some functions that can change IME such as: ImmGetConversionStatus() and ImmGetContext(hWnd), ImmSetConversionStatus(). 
So when I press Tab key in "Input text control of electron", IME will be change to the keyboard of the other language. But I can not get the hWnd of this "Input Text control of electron"? 

Thanks for your helps.

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
