### ISSUE TITLE
Dev tools remain invisible

### ISSUE THREAD

**Issue by pronebird** [electron/electron#15683]
* Output of `node_modules/.bin/electron --version`: 3.0.8
* Operating System (Platform and Version): windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): n/a

**Expected Behavior**
`window.openDevTools({ mode: 'detach' });` should work.

**Actual behavior**
`window.openDevTools({ mode: 'detach' });` does not work.

**To Reproduce**
Your best chance of getting this bug looked at quickly is to provide a REPOSITORY that can be cloned and run.

You can fork [electron-quick-start](https://github.com/electron/electron-quick-start) and include a link to the branch with your changes.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone $YOUR_URL -b $BRANCH
$ npm install
$ npm start || electron .
```
**Screenshots**

**Additional Information**

**Comment by brenca** [comment]
`openDevTools` is not a `BrowserWindow` API, but a `WebContents` one. Use `window.webContents.openDevTools({ mode: 'detach' })` to open DevTools in detached mode.

**Comment by pronebird** [comment]
@brenca it's an alias, please re-open the issue and do not close issues until you're 1000% sure. Thank you.

```
➜  ~ electron -i
> var electron = require('electron')
undefined
> var window = new electron.BrowserWindow({ width: 300, height: 300, url: "https://github.com/" })
undefined
> window.openDevTools
[Function: openDevTools]
> window.openDevTools()
undefined
```
