### ISSUE TITLE
Desktop hangs or shows nothing when running electron app in RHEL 7.4

### ISSUE THREAD

**Issue by varunatarcon** [electron/electron#15694]
* Output of `node_modules/.bin/electron --version`:
v.3.0.9
* Operating System (Platform and Version):
RHEL 7.4 x64_x6

### Expected behavior

App must start, and load the website.

### Actual behavior

App starts, but website doesn't load. It shows nothing, and electron window is broken.
**_**Note: While running it in RHEL v7.4 VM with all updates installed, web page loads, but after 2 minutes, entire desktop environment freezes.**_**

### How to reproduce

> **All I did was -  executed example on this site: https://electronjs.org/docs/tutorial/first-app**

**Step 1**: Create folder and run `npm init`
**Step 2**: Install electron `npm install electron --save-dev`
**Step 3**: Create `index.js` and `index.html` as specified below

> **index.js**
> ```
> const { app, BrowserWindow } = require('electron')
> 
> function createWindow () {
>   // Create the browser window.
>   win = new BrowserWindow({ width: 800, height: 600 })
> 
>   // and load the index.html of the app.
>   win.loadFile('index.html')
> }
> 
> app.on('ready', createWindow)
> ```
> **index.html**
> ```
> <!DOCTYPE html>
> <html>
>   <head>
>     <meta charset="UTF-8">
>     <title>Hello World!</title>
>   </head>
>   <body>
>     <h1>Hello World!</h1>
>     We are using node <script>document.write(process.versions.node)</script>,
>     Chrome <script>document.write(process.versions.chrome)</script>,
>     and Electron <script>document.write(process.versions.electron)</script>.
>   </body>
> </html>
> ```
> Make sure **package.json** looks like this:
> ```
> {
>   "name": "your-app",
>   "version": "0.1.0",
>   "main": "main.js",
>   "scripts": {
>     "start": "electron ."
>   }
> }
> ```

**Step 4**: Run `npm start`

**Comment by nitsakh** [comment]
What is the desktop environment/window manager that you are running?

**Comment by varunatarcon** [comment]
@nitsakh i m using gnome-classic. GNOME Version 3.28.3

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
