### ISSUE TITLE
Black Screen, Render Crash

### ISSUE THREAD

**Issue by ccorcos** [electron/electron#15703]
* Output of `node_modules/.bin/electron --version`: v3.0.6
* Operating System (Platform and Version): MacOS 10.13.6

The screen turned black, but I have no way of figuring out why. I have code to log uncaught exceptions, but I didn't see anything in the log file.

```ts
process.on("uncaughtException", error => {
	logger.log(error)
	process.exit(1)
})

process.on("unhandledRejection", error => {
	logger.log(error)
})
```

I don't really have anything to debug with. Are there any logs for this sort of thing? The app didn't actually crash, it just turned black... 

Is there any code I can add to my app to debug this for next time?

**Comment by gev** [comment]
I have same problem for Electron 3.0.10 on Raspbian Stretch. And can't catch any exceptions or logs.
Application could run day or more as well then crush to "black screen"

**Comment by gev** [comment]
Seems problem have been solved https://github.com/electron/electron/issues/14246
