### ISSUE TITLE
maximize, minimize, restore incorrect size

### ISSUE THREAD

**Issue by theplue** [electron/electron#15702]
* Output of `node_modules/.bin/electron --version`:
"electron": "3.0.8",
* Operating System (Platform and Version):
Windows 10 enterprise Version 1709 OS build 16299.726
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
-the window should not be larger than the maximum values provided to Browser window after restoring a maximized window

**Actual behavior**
upon restoring the window, the window size is wider than maximum value, and wider than the value it was minimized at

**To Reproduce**
Your best chance of getting this bug looked at quickly is to provide a REPOSITORY that can be cloned and run.
1.update main.ts to have browser window values
2. npm start
3. maximize window
4. minimize window
5. restore window

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone https://github.com/theplue/angular-electron.git
$ npm install
$ npm start
```

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
