### ISSUE TITLE
BrowserWindow.setVibrancy() takes no effect on BrowserWindow opened by nativeWindowOpen

### ISSUE THREAD

**Issue by KochiyaOcean** [electron/electron#15706]
* Output of `node_modules/.bin/electron --version`: 4.0.0-beta.7
* Operating System (Platform and Version): macOS 10.14.1
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 3.0.9

**Expected Behavior**
A window opened with `nativeWindowOpen` option will have vibrancy effect if `setVibrancy`
 method is called.

**Actual behavior**
`setVibrancy` method takes no effect

**To Reproduce**
* Open a `BrowserWindow` with following option
```js
new BrowserWindow({
  vibrancy: 'dark',
  backgroundColor: "#00000000",
  webPreferences: {
    nativeWindowOpen: true,
  }
});
```
* Run `open('')`
* Open devtool of the new window
* Run 
```js
require('electron').remote.getCurrentWindow().setBackgroundColor('#00000000')
require('electron').remote.getCurrentWindow().setVibrancy('dark')
```

**Screenshots**

#### electron 3.0.9 (Excepted behavior)
![image](https://user-images.githubusercontent.com/8194131/48470777-b311d080-e835-11e8-8e90-8d483321052b.png)

#### electron 4.0.0-beta.7 (Actual behavior)
![image](https://user-images.githubusercontent.com/8194131/48470875-01bf6a80-e836-11e8-990b-baa095cf4578.png)

**Additional Information**
In electron@3.0.9, the child window opened by 'nativeWindowOpen' will inherit props from parent window, so it would have vibrancy effect without call `setVibrancy` manually. But in electron@4.0.0-beta.7, the child window seems didn't inherit props from parent window, and call `setVibrancy` manually also takes no effect.

**Comment by jkleinsc** [comment]
@KochiyaOcean I have tried to reproduce this and based on my findings I don't think this is necessarily a bug.  In 4-0-x, running 
```js 
require('electron').remote.getCurrentWindow().setBackgroundColor('#00000000')
require('electron').remote.getCurrentWindow().setVibrancy('dark')
```
Will set the window correctly, but you can't see the changes while dev tools is open.  Once you close dev tools the window will appear correctly.

You can also verify that `setVibrancy` works correctly with the following test case:
https://gist.github.com/jkleinsc/61969a3138e26d0fb19bc029e693fa00

**Comment by KochiyaOcean** [comment]
@jkleinsc Thanks for explanation.
