### ISSUE TITLE
Electron 4.0@beta does not includes language (lproj) resources in prebuilt

### ISSUE THREAD

**Issue by kwonoj** [electron/electron#15714]
* Output of `node_modules/.bin/electron --version`: `electron@4.0.0-beta.7`
* Operating System (Platform and Version): Mac OS
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
Expect `.lproj` resources are packaged under `Resources`

**Actual behavior**
Does not exist.

**To Reproduce**
Extrace 4.0.0-beta.7 package (https://github.com/electron/electron/releases/download/v4.0.0-beta.7/electron-v4.0.0-beta.7-darwin-x64.zip), navigate to `Contents->Resources` and check contents.

**Screenshots**
Left side is contents of 3.0.8, Rigit side is 4.0.0-beta.7

![image](https://user-images.githubusercontent.com/1210596/48503553-4ed01c00-e7f7-11e8-975d-86df7674a889.png)

**Additional Information**

**Comment by zerofront** [comment]
what' s the use of these empty .lproj directories? Is there any references?
