### ISSUE TITLE
pasteAndMatchStyle() results in two events

### ISSUE THREAD

**Issue by felixrieseberg** [electron/electron#15719]
* Output of `node_modules/.bin/electron --version`: 3.0.9 (and up)
* Operating System (Platform and Version): Windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2.0.x

**Expected Behavior**
Pressing `Ctrl + Shift + V` should result in one paste event only.

**Actual behavior**
Pressing `Ctrl + Shift + V` results in two paste events only.

**To Reproduce**
@brenca was nice enough to make a Fiddle (https://gist.github.com/brenca/e0ca153755979bed51a991e9d8c185bb). 

**Additional Notes**
A few notes that are interesting:
 * This bug is Windows-only.
 * Not registering a `paste` handler: No issue
 * Not calling `event.preventDefault()` or `event.returnValue = false`: No issue
 * Just clicking on a `MenuItem` that calls `webContents.pasteAndMatchStyle()`: No issue
 * Not registering a `MenuItem` with an accelerator: No issue
 * Chromium 66 does not have this issue

**Comment by nornagon** [comment]
Was this introduced in 3.0.9 or is it also present in early 3.x releases?

**Comment by felixrieseberg** [comment]
This was also present in earlier 3.x releases.
