### ISSUE TITLE
Electron 3 WebviewTag.focus() does not properly transfer focus.

### ISSUE THREAD

**Issue by ccorcos** [electron/electron#15718]
* Output of `node_modules/.bin/electron --version`: 3.0.9
* Operating System (Platform and Version): MacOS 10.13.6
* Output of `node_modules/.bin/electron --version` on last known working Electron version: 2.0.5

**Expected Behavior**

Calling `.focus()` on a webview tag should transfer focus and typing should be received in that webview.

**Actual behavior**

Focus is not transfered.

**To Reproduce**

I've created a minimal reproduction demonstrating the issue [here](https://github.com/ccorcos/electron-3-webview-focus-bug).

```sh
git clone https://github.com/ccorcos/electron-3-webview-focus-bug

git checkout master
npm install
npm start # This should work and demonstrate proper behavior on 2.0.5

git checkout bug
npm install
npm start # This should break and demonstrate the issue on 3.0.9
```

**Comment by javan** [comment]
Possibly related to https://github.com/electron/electron/issues/14474?

It works if you explicitly `blur()` the other `<webview>`, which is similar to the workaround in  https://github.com/electron/electron/issues/14474#issuecomment-425794480.

```diff
--- a/index.html
+++ b/index.html
@@ -18,6 +18,7 @@
                                if (event.channel === "enter") {
                                        // Pressing enter should send the value to child1 and focus on that input.
                                        console.log("enter", event.args[0])
+                                       child1.blur()
                                        child2.focus()
                                        child2.getWebContents().send("enter", event.args[0])
```

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by andersk** [comment]
See also

* #31918
