### ISSUE TITLE
Polymer 3 module import fails

### ISSUE THREAD

**Issue by eugv86** [electron/electron#15710]
Electron version: 3.04
Operating system: Windows 10

**Issue with importing polymer modules with require('')**

> Uncaught SyntaxError: Unexpected token {
>     at new Script (vm.js:74)
>     at createScript (vm.js:246)
>     at Object.runInThisContext (vm.js:298)
>     at Module._compile (internal/modules/cjs/loader.js:678)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:722)
>     at Module.load (internal/modules/cjs/loader.js:620)
>     at tryModuleLoad (internal/modules/cjs/loader.js:559)
>     at Function.Module._load (internal/modules/cjs/loader.js:551)
>     at Module.require (internal/modules/cjs/loader.js:658)
>     at require (internal/modules/cjs/helpers.js:20)

**To reproduce**
Run the source (sample.zip) attached or try to import a polymer 3 module with require('POLYMER 3 MODULE PATH').  I used the electron-quick-start project so it is bare bones with inclusion of Polymer 3.

[sample.zip](https://github.com/electron/electron/files/2581487/sample.zip)

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
