### ISSUE TITLE
Calling Cmd+Z (webContents.undo()) and Shift+Cmd+Z (webContents.redo()) have no effect inside a <webview> tag

### ISSUE THREAD

**Issue by pwnsdx** [electron/electron#15728]
* Output of `node_modules/.bin/electron --version`: v3.0.9
* Operating System (Platform and Version): macOS 10.14
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v2.0.13

**Expected Behavior**

Undo and redo behavior should work.

**Actual behavior**

Cmd+Z and Shift+Cmd+Z are not working inside a <webview> tag, even when calling directly undo() and redo() like this for example:

```
{
      i18n: 'menuUndo',
      accelerator: 'CmdOrCtrl+Z',
      click: (menuItem, focusedWin) => {
        webContents.getFocusedWebContents().undo();
        focusedWin.webContents.undo();
      }
    },
```

**To Reproduce**

Start this demo with Electron version 2.0.13 to see how things are supposed to work.

```sh
$ git clone https://github.com/pwnsdx/electron-3-webview-undo-redo-bug.git -b master
$ npm install
$ npm start
```

Put you cursor in the text input in child1.html. Type something and press Cmd+Z. The text revert to its previous state. Do Shift+Cmd+Z and the text you typed will reappear.

Change the Electron version in package.json to 3.0.9 then

```
npm install
npm start
```

Type something and press Cmd+Z. The text should revert but it does not.

**Comment by vladimiry** [comment]
Did you try to call `undo` on `event.sender`? See example [here](https://github.com/electron/electron/issues/15219#issuecomment-435620971).

**Comment by vladimiry** [comment]
I fixed the issue applying another workaround:
- embed this into webview or rendered process https://github.com/vladimiry/email-securely-app/commit/90d979258ce375600571fd6264c79e25ca8db353#diff-5c374a4c594ca2db28374ba3def4eff4
- above code calls the following logic in the main process https://github.com/vladimiry/email-securely-app/commit/90d979258ce375600571fd6264c79e25ca8db353#diff-6ffd7ba9d6de2491bdd377b1ec309e5fR98

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by nik72619c** [comment]
Undo on <input /> inside webview tag does not work on versions after v1.8.8 for MacOS. Any helps would be appreciated :)

**Comment by Syed-Umair** [comment]
> Undo on inside webview tag does not work on versions after v1.8.8 for MacOS. Any helps would be appreciated :)

It doesn't work via keyboard shortcut and also via menu bar.

**Comment by vladimiry** [comment]
It doesn't work out of the box, but you can apply a work around, like setting up a  custom keyboard clicks handler and then triggering the needed action directly on `webContent` instance.

**Comment by Syed-Umair** [comment]
> It doesn't work out of the box, but you can apply a workaround, like setting up a custom keyboard clicks handler and then triggering the needed action directly on `webContent` instance.

Agreed @vladimiry , I am currently using my [module](https://www.npmjs.com/package/electron-window-shortcut) to do the job.

**Comment by adityamudgil2505** [comment]
@Syed-Umair Can you please give some examples of how to use this module to solve this issue?
