### ISSUE TITLE
Preload scripts can break navigation

### ISSUE THREAD

**Issue by paulcbetts** [electron/electron#1572]
Related to the bugs I'm tracking in #1560, it appears that unhandled exceptions that are thrown in preload scripts can actually break navigation in the webview entirely. Still digging out more details about this, but:

1. Create a webview in a preload script
1. Have that preload script throw or otherwise Not Work Right
1. On the webview's page, have a form that does a basic submit

If the preload script loads, the page hangs, we never make a web request

**Comment by zcbenz** [comment]
I can not reproduce this in v0.37.x anymore.
