### ISSUE TITLE
Problems to show Shiny R pages in Electron Browser Window

### ISSUE THREAD

**Issue by ragapack** [electron/electron#15730]
process.versions.electron
"3.0.9"
OS: Windows 10 

**Expected Behavior**
I want to open Shiny R pages in a Electron browser window.
The Server for testing is:  https://gallery.shinyapps.io
I want that the pages open in the same way as in the Chrome browser.
**Actual behavior**
If I open a Shiny app page direct from the https://gallery.shinyapps.io Server the controls are not drawn.
https://gallery.shinyapps.io/001-hello
![captura de tela 2018-11-15 12 29 04](https://user-images.githubusercontent.com/6429531/48556013-f7a77580-e8e2-11e8-8bb9-218df3fbfe31.png)

If I open a similar page embeded in an other html page
http://shiny.rstudio.com/gallery/example-01-hello.html
The page load the controls but the slider is not moving.

![captura de tela 2018-11-15 12 47 20](https://user-images.githubusercontent.com/6429531/48556161-6c7aaf80-e8e3-11e8-90e1-e977703ca9bb.png)
An other page with Sliders works fine as embedded page but a similar page not load the controls direkt from shiny server.
http://shiny.rstudio.com/gallery/sliders.html
![captura de tela 2018-11-15 12 52 24](https://user-images.githubusercontent.com/6429531/48556789-2cb4c780-e8e5-11e8-9cb1-bfca16cfc8b8.png)
https://gallery.shinyapps.io/Ebola-Dynamic/
![captura de tela 2018-11-15 12 48 32](https://user-images.githubusercontent.com/6429531/48556801-32aaa880-e8e5-11e8-846b-850bcd2955a0.png)

Question:
Any Special config is nessesary to show shiny R Webpages in Electron.
Thank you
Thomas

**Comment by shiftkey** [comment]
@ragapack the **View** | **Toggle Developer Tools** might contain console errors that would provide more details about your specific problem

**Comment by ragapack** [comment]
Thank you for your fast Reply.
I captured the console of the 2 files, direkt call and embedded.
![captura de tela 2018-11-15 15 47 01](https://user-images.githubusercontent.com/6429531/48560537-558d8a80-e8ee-11e8-86c5-e6511ff8d351.png)
![captura de tela 2018-11-15 15 50 03](https://user-images.githubusercontent.com/6429531/48560552-5faf8900-e8ee-11e8-9661-276b2ce04976.png)

**Comment by brenca** [comment]
[Try turning off `nodeIntegration` ](https://electronjs.org/docs/faq#i-can-not-use-jqueryrequirejsmeteorangularjs-in-electron)to see if that fixes it.

**Comment by ragapack** [comment]
Many thanks for your help, this makes my day 👍 

I added 
function createWindow () {
  // Create the browser window.
  win = new BrowserWindow({ width: 800, height: 600, webPreferences: {
    nodeIntegration: false
  }
 })
Here the result, 
![captura de tela 2018-11-15 17 23 19](https://user-images.githubusercontent.com/6429531/48566668-a657b000-e8fb-11e8-9828-8d83e3b3d780.png)

**Comment by codebytere** [comment]
Closing as it seems that a solution has been reached.
