### ISSUE TITLE
Notifications not appearing correctly

### ISSUE THREAD

**Issue by nirewen** [electron/electron#15740]
* Output of `node_modules/.bin/electron --version`:
> v3.0.9
* Operating System (Platform and Version):
> Windows 10 (Build 18277.rs_prerelease.181102-1446)

**Expected Behavior**
Notification appears with the provided texts

**Actual behavior**
Notification appears only with "New notification", nothing else

**To Reproduce**
Set AppUserModelId with `app.setAppUserModelId('com.example.app')`

Create a new Notification using electron
```javascript
const { Notification } = require('electron')

let notification = new Notification('some text', {
    body: 'Some body'
})

notification.show()
````

**Comment by nirewen** [comment]
Ok, apparently the documentation is wrong? Because I found a way to make Notifications work.
As you can see in [Notifications tutorial](https://electronjs.org/docs/tutorial/notifications), the syntax provided above is correct, but the syntax the app uses is different. I managed to get it to work by providing an object instead of the title string
```javascript
const { Notification } = require('electron')

let notification = new Notification({
    title: 'some text',
    body: 'Some body'
})

notification.show()
```
This is the correct syntax, and it works. So issue solved? Maybe. This might be open to become an issue where documentation is wrong.

**Comment by MarshallOfSound** [comment]
@nirewen The documentation is correct, the notification tutorial is for the renderer process.  It has a warning in it.

> Note: Since this is an HTML5 API it is only available in the renderer process. If you want to show Notifications in the main process please check out the Notification module.

The API electron provides in the main process is different from the HTML5 Notification API
