### ISSUE TITLE
Drag and drop a URL into browser window loads page

### ISSUE THREAD

**Issue by sancarn** [electron/electron#15744]
By default you can drag and drop a URL into a browser window, and the browser window will navigate to that page:

https://puu.sh/C30ZL/9d1809a1b3.mp4

This is a security risk. Websites loaded in electron have automatic access to node functionality. Thus a user could accidentally do this and nuke their computer.

**Comment by Hum4n01d** [comment]
You need to catch the `dragover`/`drop` events and prevent the default behavior of redirecting:

```js
document.addEventListener('dragover', event => event.preventDefault())
document.addEventListener('drop', event => event.preventDefault())
```

**Comment by sancarn** [comment]
Yes, I know how to disable it. But this is an application framework. Shouldn't this be captured by default? After all, if the user does navigate to the page in this way, the website they redirect to will have full access to node. This seems like a pretty major security hazard...

**Comment by Hum4n01d** [comment]
Ah, my bad, thought you were asking how to disable it :wink:

I'm not involved with the development of Electron, but I agree that there could definitely be some security concerns with this default behavior.

**Comment by sancarn** [comment]
@Hum4n01d I see, I should probably mention that in the original post xD

**Comment by deepak1556** [comment]
@sancarn please fill out the issue template, to provide more information on the recent electron versions you are seeing this behavior. We have disabled navigations on drag-drop since v3.0.0-beta.1 https://github.com/electron/electron/pull/12655

**Comment by nornagon** [comment]
This should be disabled by default in Electron 3 and up, fwiw: https://github.com/electron/electron/pull/12655

**Comment by sancarn** [comment]
Ah good to know! Thanks for the information!
