### ISSUE TITLE
4.0.0-beta.8 Release Incomplete

### ISSUE THREAD

**Issue by rr326** [electron/electron#15747]
* Output of `node_modules/.bin/electron --version`: TRYING to be 4.0.0-beta.8
* Operating System (Platform and Version): MacOS 10.14.1
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v4.0.0-beta.7

**Expected Behavior**
Fails to install. The release is not complete.

**Actual behavior**
```
`--> npm install electron@4.0.0-beta.7 

> electron@4.0.0-beta.7 postinstall /Users/rrosen/dev/filing/node_modules/electron
> node install.js

Downloading tmp-3817-1-SHASUMS256.txt-4.0.0-beta.7
[============================================>] 100.0% of 5.06 kB (5.06 kB/s)
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-standard@10.2.1 requires a peer of eslint-plugin-node@>=4.2.2 but none is installed. You must install peer dependencies yourself.
npm WARN karma-jasmine@1.1.2 requires a peer of jasmine-core@* but none is installed. You must install peer dependencies yourself.
npm WARN filing No repository field.
npm WARN filing No license field.

+ electron@4.0.0-beta.7
updated 2 packages and audited 15403 packages in 17.281s
found 15 vulnerabilities (10 low, 4 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details


`--> npm install electron@4.0.0-beta.8 
npm ERR! code ETARGET
npm ERR! notarget No matching version found for electron@4.0.0-beta.8
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rrosen/.npm/_logs/2018-11-17T13_53_04_177Z-debug.log
```

**To Reproduce**
See above

**Screenshots**
Another clue:
[![electronjpg.jpg](https://i.postimg.cc/zBcWVmyP/electronjpg.jpg)](https://postimg.cc/ftYkrrjx)
**Additional Information**

**Comment by MarshallOfSound** [comment]
This is expected, although there is a tag on GitHub, the release process was terminated.  If it's not on npm, you can't install it.

I've removed that tag to avoid confusion until we try the release again.

**Comment by rr326** [comment]
Ah gotcha. I waited a day in case it was a temporary thing but didn't understand that it was aborted.
