### ISSUE TITLE
Feature Request: event.preventDefault() for BrowserWindow 'minimize'  event

### ISSUE THREAD

**Issue by aam1r** [electron/electron#15779]
**Output of `node_modules/.bin/electron --version`**
v3.0.4

**Operating System (Platform and Version)**
macOS Sierra 10.12.6 (16G29)

**Expected Behavior**
The following code should prevent the application from getting minimized:

```javascript
mainWindow.on('minimize', function (event) {
  event.preventDefault();
});
```

**Actual behavior**
The default prevention logic doesn't seem to kick-in; the application gets minimized.

**To Reproduce**
1. Download the [electron-quick-start](https://github.com/electron/electron-quick-start) source code
2. Replace main.js with [this main.js](https://gist.github.com/aam1r/cd04b6f73aa1d88f6035d18a2a2a7192) instead
3. npm install
4. npm start || electron .
5. Try minimizing the application 

**Additional Information**
`event.preventDefault` seems to work fine for the `close` event

**Comment by codebytere** [comment]
We don't provide this support [as seen in docs](https://github.com/electron/electron/blob/master/docs/api/browser-window.md). I can try to introduce this ability sometime soon!

**Comment by aam1r** [comment]
Yes, I think it is more appropriate to classify this as a feature request instead of as a bug

**Comment by codebytere** [comment]
Unfortunately, the window minimize event is not preventable in this way per [documentation](https://developer.apple.com/documentation/appkit/nswindowdelegate?language=objc). I would recommend instead setting the `minimizable` option/

**Comment by cookmscott** [comment]
Any idea of how to capture a click event on windows Taskbar if `minimizable=false`?
