### ISSUE TITLE
Window animations stagger/fail when dev tools are not open

### ISSUE THREAD

**Issue by jetlej** [electron/electron#15776]
Using the answers from electron/electron#2407, I've been able to create position animations for BrowserWindow. 

```
let win = BrowserWindow.getFocusedWindow()
let currentX = win.getPosition()[0]
let currentY = win.getPosition()[1]
    
jQuery({ xCounter: currentX, yCounter: currentY }).animate({ xCounter: 0, yCounter: 0},  {
   duration: 500,
   step: function () {
      win.setPosition(this.xCounter, this.yCounter)
   }
})
```
However, the changes to X and Y position only run smoothly together if I have dev tools open. If they aren't open, it jumps between large changes and even ends up with the wrong value. 

However if I only run changes to X, it runs smoothly in either case.

Any ideas of why this would be? 

FYI I have tried other forms of animation, including vanilla javascript with requestAnimationFrame(). The same issue shows up.

**Comment by MarshallOfSound** [comment]
@jetlej I assume you are running this from a renderer process, try doing this kind of logic in the main process.  By doing this in the renderer you are using synchronous IPC which can block re-paints and introduce the appearance of "lag"

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by jetlej** [comment]
@MarshallOfSound - I would, but you can't use jQuery or requestAnimationFrame within the main process because it's not a normal window with a DOM.
