### ISSUE TITLE
Supporting API deprecation decisions with data

### ISSUE THREAD

**Issue by nitsakh** [electron/electron#15783]
### What is the problem IMO?
Currently, it’s almost impossible to know if an app is using an electron API and all the data in the events that electron provides. When chromium makes changes that affect an electron API and the data it provides, maintainers usually end up finding another way to get that data to the API users. This could be through chromium patches to reinstate the previous behaviour or other ‘not so ideal’ ways. While this does seem necessary some of the times, there could be other instances when that event data or API is not used at all. If it’s not needed/used then electron maintainers will not have to go through the additional maintenance burden to support the old API data. 
In short, I think the one of the problems right now is that there’s no data about API usage to drive any decision.

### What can we do?
I think there are different approaches that electron can take while maintaining its openness and ease of use.
Folks have had one off conversations about these different approaches at different points in time.
A dumb but 'workable' solution could even be something like "let electron users enter something into a public spreadsheet" anonymously.

This issue is not necessarily meant for us to work out a perfect solution, but it’ll be good to have our thoughts together. It might as well be that we all decide that this is not something electron should be doing and there could be other ways to the above problem. (Or maybe it’s not a significant problem at all)

### How will this help?
This data will help electron in quite a few ways.
Firstly, like mentioned above, this will be another step towards faster chrome upgrades in future, with better knowledge of API usage.
Besides, it could also help us in future to prioritize things like performance for APIs etc.

**Comment by nornagon** [comment]
It might make sense to have a development-mode-only stats collection system, so that stats aren't inadvertently collected on machines of end users. Perhaps it could be implemented something like this:

1. At boot, Electron detects that it is running in development mode (i.e. unpackaged), and begins collecting API statistics (but not yet sending them).
2. When the app exits, we spawn a new process whose job is only to do the following:
    1. Show a dialog to the developer asking if they want to help the Electron project by sending anonymous statistics about API usage.
    2. Show the developer exactly what will be sent (behind a dropdown or other "details" view)
    3. Write a hidden file that remembers their decision for future runs.
3. Next time the app starts, check for that hidden file and obey it.
4. Never send statistics while the app is running; only in a bundle after the app quits.
5. Never collect or send statistics in packaged (i.e. production) mode.

**Comment by jviotti** [comment]
@nornagon @nitsakh We (Postman) have an internal project called X-Ray to solve this problem, which we aim to open-source at some point. X-Ray is a static analyzer that generates an HTML report based on the Electron APIs and events that a specific app is making use of.

We are using X-Ray internally to generate reports out of the Postman desktop application, but have plans to extend it to analyze and aggregate data from Electron open-source apps hosted on GitHub + periodically analyze proprietary apps by peeking at the (potentially minified) code from ASARs. 

Of course, this is static analysis and not runtime analysis, but it is super useful for us already. I'll let you know once we properly open-source it if that's of interest. We plan to host a website with aggregate and app-specific data in a browsable manner.

**Comment by nornagon** [comment]
Cool stuff! Definitely interested in that!
