### ISSUE TITLE
Ubuntu file picker doesn't show file preview

### ISSUE THREAD

**Issue by Thomas101** [electron/electron#15792]
* Output of `node_modules/.bin/electron --version`: 3.0.10, 4.0.0-beta.7
* Operating System (Platform and Version): Ubuntu 18.04
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): N/A

**Expected Behavior**
When picking a file to upload, the file picker should show a preview of the file when applicable

**Actual behavior**
It does not show a preview...

Chrome shows a preview of the image (tested with 70 and 69).
![chrome](https://user-images.githubusercontent.com/103586/48838688-01b4f280-ed81-11e8-8b38-16d7cbab1f22.png)

Electron shows no preview
![electron](https://user-images.githubusercontent.com/103586/48838699-08dc0080-ed81-11e8-8611-6a199fba23f8.png)

**To Reproduce**
Nothing special, click on a file upload form element...
```html
<input type="file" />
```
Example here: https://cgi-lib.berkeley.edu/ex/fup.html

**Comment by MarshallOfSound** [comment]
🔗 https://cs.chromium.org/chromium/src/chrome/browser/ui/libgtkui/select_file_dialog_impl_gtk.cc?q=gtk_file_chooser_set_preview_widget&sq=package:chromium&dr=C&l=181
