### ISSUE TITLE
Allow Javascript to run when app is not in foreground

### ISSUE THREAD

**Issue by Hyperblaster** [electron/electron#15807]
First off, Electron is awesome, thanks to all the maintainers and contributors.

I have an application that sits and waits for print jobs to come through, it receives a push notification and then sends the jobs to the printer. 

On MacOs when the application is open everything is fine, until you open another application in front of the electron app, then all javascript in the browser window pauses. 

If you click back into the window, the javascript picks up where it left off and runs no worries. Likewise, if you can still see part of the browser window behind the other focussed app, javascript runs fine also. it only seems to be if the browser window is covered/visually obstructed blocked by another app

**Describe the solution you'd like**
An option to keep javascript running in the BrowserWindow even when the app is idle/not focussed/running background

**Describe alternatives you've considered**
electron.powerSaveBlocker.start('prevent-app-suspension'); //Keeps the computer on but still pauses javascript
mainWindow.setMinimizable(false) //Stops the user minimizing but still pauses javascript
'alwaysOnTop:true' //works but obviously not desired outcome

**Additional context**
I'm not sure if this is possible or just how things have to work, or if there is already a workaround.

**Comment by MarshallOfSound** [comment]
@Hyperblaster You can set `backgroundThrottling` to `false` in your `BrowserWindow` constructor

**Comment by Hyperblaster** [comment]
I swear i looked through that page carefully. Somehow i missed that.
Thanks for incredibly rapid reply!

**Comment by linonetwo** [comment]
This seems broken in v5, but I can't provide more evidence since it's complicated.
