### ISSUE TITLE
Linux v3.0.x Electron can not show anything

### ISSUE THREAD

**Issue by dicklwm** [electron/electron#15806]
* Output of `node_modules/.bin/electron --version`:
```
v3.0.10
```
* Operating System (Platform and Version):
```
OS: Deepin 15.5 elepnant
Kernel: x86_64 Linux 4.9.0-deepin9-amd64
```
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):
```
v3.0.10
```

**Expected Behavior**
`$ electron https://www.google.com` 
it will open a window and load `http://www.google.com` and  i expected the window can show me google.

**Actual behavior**

For v3.0.x, it open a window and show me an error window.
For v2.0.x, it open a window and show me google.
You can see the screenshots below

**To Reproduce**

1. Use `Deepin 15.5 elepnant` OS
2. `$ npm install -g electron`
3. `$ electron https://www.google.com`

**Screenshots**
![image](https://user-images.githubusercontent.com/19289258/48890066-be3ab100-ee72-11e8-8592-39a4342751e5.png)
![image](https://user-images.githubusercontent.com/19289258/48890072-c09d0b00-ee72-11e8-8607-63785638635b.png)

**Comment by daniel-nth** [comment]
Had the same problem, 3.0.11 fixed it for me.

**Comment by sofianguy** [comment]
I'm going to close this as it is reported as fixed in the comment above. Feel free to reach out if you are experiencing this issue on version 4.2.x or later.
