### ISSUE TITLE
Preserve BrowserWindowConstructorOptions on BrowserWindow

### ISSUE THREAD

**Issue by burtonator** [electron/electron#15802]
Ideally the BrowserWindowConstructorOptions would be preserved on the BrowserWindow and possibly returned via a getOptions() method or a options member.

This is necessary to make sure a Window can be re-used and that it has the right options.

For example, you can't load a webapp in a Window that requires node modules if nodeIntegration isn't enabled.

Additionally, there are security implications here. This way you could avoid loading a URL if the security on the Window isn't setup properly.

**Comment by miniak** [comment]
Sorry, closed by mistake

**Comment by miniak** [comment]
There was actually `webContents.browserWindowOptions`, which got removed by #28550

**Comment by nornagon** [comment]
I think this isn't a great idea; it's better if those options are GC-able, as they can in some circumstances retain somewhat significant resources (e.g. a reference to an icon).

It's also trivial for an app to implement themselves:

```js
const options = { ... options }
const bw = new BrowserWindow(options)
bw.constructorOptions = options
```
