### ISSUE TITLE
Remote debugging not working with Electron 4.x

### ISSUE THREAD

**Issue by gorunovanton** [electron/electron#15815]
* Output of `node_modules/.bin/electron --version`:  v4.0.0-beta.7
* Operating System (Platform and Version): Windows 7/10 x64, Linux
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 3.0.10

**Expected Behavior**
Remote debugging from Chromium is available for the render processes of applications started with _**--remote-debugging-port=<_port>**_ and Chromium Dev Tools are available and work correctly.

**Actual behavior**
The remote debugger is probably connected to the render process, but no debug tools are available. Chromium shows a blank page.

**To Reproduce**
Start Electron with the remote debuging option (**electron . --remote-debugging-port=<_port>**) and connect to it from Chromium by navigating to 127.0.0.1:<_port>.
With Electron 4.x you will see a blank page. With version 3.x you will see the Chromium Dev Tools UI.

**Additional Information**
Part of the remote debugging functionality still works, e.g. with JetBrains IDEs you can connect to the render process add get console output, variables, and set breakpoints (sometimes 🤣  ).

**Comment by nornagon** [comment]
I can reproduce this. Will look into it.
