### ISSUE TITLE
CommandOrControl+A accelerator does not work on Linux

### ISSUE THREAD

**Issue by nikku** [electron/electron#15810]
* Output of `node_modules/.bin/electron --version`: `v3.0.7`
* Operating System (Platform and Version): `Arch Linux (linux v4.17)`
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):
none.

**Expected Behavior**

I can bind the `CommandOrControl + A` accelerator.

**Actual behavior**

The `CommandOrControl + A` accelerator cannot be bound.

**To Reproduce**

```sh
$ git clone git@github.com:bpmn-io/electron-quick-start.git -b ctrl-a-not-working
$ npm install
$ npm start
```

This fork of the quick start applies https://github.com/bpmn-io/electron-quick-start/commit/7442617ab85bb97c4998137a57e050090e62838c to add a minimal menu + binding for `CmdOrCtrl + A`. Pressing the accelerator should output a message to the console, instead if selects all contents inside the opened browser window.

**Additional Information**

`CommandOrControl + A` and `Ctrl+A` don't not work either. Binding any other accelerator, i.e. `CmdOrCtrl+B` works as expected.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by nikku** [comment]
Thanks for the heads-up.
