### ISSUE TITLE
Add license badge

### ISSUE THREAD

**Issue by open-source-explorer** [electron/electron#15827]
Most of the repositories these days include a LICENSE badge within the `README` file. 
I think it would be great to have it.
Thoughts 🤔

**Comment by caesar** [comment]
There's a `LICENSE` file and a license entry in the GitHub header, isn't that enough?

**Comment by open-source-explorer** [comment]
Well, it's a common practice nowadays to have a `license` badge as well 😄

**Comment by nornagon** [comment]
I think the LICENSE and the GitHub header are sufficient :)
