### ISSUE TITLE
Bad behavior with ctrl+Z from CLI

### ISSUE THREAD

**Issue by Chococoin** [electron/electron#15828]
* Output of `node_modules/.bin/electron --version`:
 v3.0.9
* Operating System (Platform and Version):
Ubuntu 16.04 LTS
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):
3.0.9

**Expected Behavior**
After stopping the program from CLI with control+z I expect the close of the main window and all electron's window open at that moment. 

**Actual behavior**
The main window gets frozen and can't be closed either minimized from the bar icon. 

**To Reproduce**
https://github.com/Chococoin/CrystalChocolate

You can fork [electron-quick-start](https://github.com/electron/electron-quick-start) and include a link to the branch with your changes.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone https://github.com/Chococoin/CrystalChocolate
$ npm install
$ npm start || electron .
```
**Screenshots**

![giphy](https://user-images.githubusercontent.com/6132396/48980620-ca6d7b00-f0cb-11e8-8ec0-44b8e7a83a47.gif)

**Comment by MarshallOfSound** [comment]
@Chococoin `Control+Z` in a terminal does not actually terminate a program, specifically, it sends a `SIGTSTP` signal which actually tells the application to suspend, not terminate.

You can actually resume the program by sending it a `SIGCONT` signal.

If you want to terminate a program you need to send `SIGINT` (this is what `Control+C` sends or `SIGTERM`

**Comment by Chococoin** [comment]
Thank you Marshall.
