### ISSUE TITLE
Modifiers not consistently being reported on keydown event

### ISSUE THREAD

**Issue by westacotta** [electron/electron#15832]
* Output of `node_modules/.bin/electron --version`: v3.0.10
* Operating System (Platform and Version): Windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): Previous version I used which was working v2.0.0

**Expected Behavior**
all keyboard modifiers to be correctly reported on keydown event when pressed with any other alpha key when hooked with window.addEventListener('keydown') in a preload script against window

**Actual behavior**
ctrl + alt are correctly reported when pressed singularly or together but when pressed with another key they are reset to false UNLESS you keep holding them down to repeat then they are correctly set
i.e.
Here you can see me pressing ctrl + alt then U
{"ctrlKey":true,"keyCode":17,"shiftKey":false,"altKey":false}
{"ctrlKey":true,"keyCode":18,"shiftKey":false,"altKey":true}
**{"ctrlKey":false,"keyCode":85,"shiftKey":false,"altKey":false}**

When I continue to hold the 3 keys down I get the following repeat
{"ctrlKey":true,"keyCode":85,"shiftKey":false,"altKey":true}

**To Reproduce**
in a preload script
window.addEventListener('keydown', (event: KeyboardEvent) => {
    console.log( JSON.stringify({ ctrlKey: event.ctrlKey, keyCode: event.keyCode, shiftKey: event.shiftKey, altKey: event.altKey }));
});

```
**Screenshots**


**Additional Information**

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
