### ISSUE TITLE
protocol http OPTIONS returning GET

### ISSUE THREAD

**Issue by couturecraigj** [electron/electron#15849]
* Output of `node_modules/.bin/electron --version`: v3.0.10
* Operating System (Platform and Version): MacOS 10.14.1

* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

### Expected behavior

```javascript
protocol.interceptHttpProtocol(
    'https',
    (request, callback) => {
      if (request.method === 'OPTIONS') {
        return callback({
          ...request,
          // uploadData: request.uploadData[0],
          url: `http://localhost:3000/api/`
        });
      }
      ...
    },
    error => log.error(error)
  );
```

should return method "OPTIONS" from the designated endpoint but what I am receiving seems to align more with "GET".  For instance 'Access-Control-Allow-Headers' and 'Access-Control-Allow-Methods' are missing from the response.  Is there a reason for this to be done?

### Actual behavior

Returns a 'GET' and actually performs a GET as I have tested this on a local node server.

### How to reproduce

I will attach a repo shortly.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

We cannot move forward with fixing without a repro. Feel free to post steps to reproduce and we will gladly reopen this issue.
