### ISSUE TITLE
switch to no-user-gesture-required' - disables userGesture constrain

### ISSUE THREAD

**Issue by themihai** [electron/electron#15856]
**Is your feature request related to a problem? Please describe.**
In the browser window some HTML APIs like requestFullScreen can only be invoked by a gesture from the user.  I need to execute requestFullScreen(among other APIs) without a user interaction as my app is remotely controlled (via websockets).

**Describe the solution you'd like**
 I would like a switch such `app.commandLine.appendSwitch( 'no-user-gesture-required', 'true');` that should remove this requirement to have user interaction for restricted APIs.

**Describe alternatives you've considered**
I considered webFrame.executeJavaScript(code[, userGesture, callback]) but this is hard to impossible to use because I need to use it in various contexts (i.e. in a class method so I cannot execute 'this.Xmethod()'  in a webframe because the javascript I need to execute is local/scoped not global/at the webframe level .

**Comment by MarshallOfSound** [comment]
@themihai Chromium already has command line switches to disable / change certain gesture requirements / behaviors.

See this page for an incomplete list: https://peter.sh/experiments/chromium-command-line-switches/

It sounds like the flag you want is probably `--disable-gesture-requirement-for-presentation`

**Comment by riccardocagnasso** [comment]
--disable-gesture-requirement-for-presentation
Doesn't seem to be supported by electron, please reopen

**Comment by mihaiav** [comment]
@MarshallOfSound Chromium made it clear that flags temporary, experimental and should be used for testing only. No flag exist anymore to disable the gesture requirement.

**Comment by buptsky** [comment]
you may use the contents.executeJavaScript api and set userGesture with true

**Comment by mihaiav** [comment]
@buptsky contents.executeJavaScript with userGesture:true is not making the events trusted. For example if you fire a keyboard event as below you will find out that the event is set with attribute `isTrusted`: false. 


```
    sendKey(data){
        const jsContent = `
        try {
            var e = new KeyboardEvent("keydown", {
                isTrusted: true,
                bubbles: true,
                cancelable: true,
                keyCode:  '` + data.keyCode + `',
                code: '` + data.code + `',
                key: '` + data.key + `',
            });
            try {
                document.dispatchEvent(e);
                console.log('dispatched', e);
            } catch (errx) {
                console.log('event error', errx);
            }
        } catch (errx) {
            console.log(errx);
        }
       `;
        const userGesture = true;
        this.windowContents.executeJavaScript(jsContent, userGesture);
    }
```
