### ISSUE TITLE
Window not positioned correctly when using setPosition() with two displays

### ISSUE THREAD

**Issue by MathieuDebit** [electron/electron#15851]
* Output of `node_modules/.bin/electron --version`: `v3.0.5`
* Operating System (Platform and Version): Windows 10, Mac OSX Mojave
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
When using `window.setPosition(0, 0)`, window should be positioned at `0, 0`.

**Actual behavior**
Window is not always positioned correctly, depending on the current window position (if on other display, etc).

**To Reproduce**
https://github.com/MathieuDebit/electron-quick-start/pull/4/

```sh
$ git clone https://github.com/MathieuDebit/electron-quick-start.git -b bug/window-set-position
$ npm install
$ npm start || electron .
```

- Move window to second screen
- Click on `resetPosition` with position `0, 0`
→ Depending on the second screen virtual position, the window is not correctly positioned.

**Screenshots**

**Additional Information**
MacOS seems to handle off-screen window differently so the bug is not always present (see https://github.com/mawie81/electron-window-state/issues/44#issuecomment-438381017).

**Comment by Ali8668** [comment]
aliiio432111@gmail.com

**Comment by appurist** [comment]
You didn't indicate what the observed behavior actually was, e.g. was it only the `y` position which was incorrect, moved down a bit (+20 to +50?), or both `x` and `y` moving?  If it's just `y` this might be related to #10388 (which is closed but still a problem in Electron 4.1.3). 

But there's also #10862 which is causing quite a few reports depending on the DPI of the two monitors.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
