### ISSUE TITLE
Request with GET/HEAD method cannot have body on custom compiles

### ISSUE THREAD

**Issue by vulture** [electron/electron#15868]
Electron version: 3.0.10, Windows x64, compiling from source

This is essentially the same bug as https://github.com/electron/electron/issues/13618 etc that has been reported in the past. You guys seem to have "fixed" this by forcing an older version of visual studio in your appveyor settings. Our issue is that we need to compile with a newer version of visual studio -- would that ever be possible in the 3-0-x branch?

(We have custom code that requires newer language features which actually needs visual studio 15.9.x (15.8.x and below don't work). But this version seems to have the same issue as the prior issue when compiling in x64.)

Any idea if there's a real fix possible for the 3-0-x branch (we can't switch to Electron 4 yet in case that fixes it because tldr we essentially can't ship betas) ? Surely google must have fixed this in more recent versions by now, though I'm having a hard time matching up libcc's WebKit's Request.cpp with chromium's Request.cpp to look at recent patches that might have fixed this?

Or, does anyone have any additional information about what caused the issue so that it can be worked around/fixed, rather than just using an old compiler because that seemed to work for unknown reasons?

Thanks!

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR.
