### ISSUE TITLE
globalShortcut not very global in Wayland

### ISSUE THREAD

**Issue by Pajn** [electron/electron#15863]
* Output of `node_modules/.bin/electron --version`: v3.0.10
* Operating System (Platform and Version): Ubuntu 18.10, Wayland
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): N/A

**Expected Behavior**
After registering a global shortcut it should always be called when that combinations is pressed.
If the DE holds that shortcut it may be captured by the DE though. But a free combination should continue to work when new applications are opened though.

**Actual behavior**
Some applications, for example gnome-terminal capture the shortcut so that it is registered by the application instead of my global handler.

**To Reproduce**
Use gnome wayland session, Register a global shortcut and make sure it works, Open gnome-terminal and see that it does not work.

**Screenshots**
N/A

**Additional Information**
N/A

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!

**Comment by vbarbarosh** [comment]
I confirm, this happens to me on Ubuntu 20.04 with Electron 20.1.3. Each time I switch to a Gnome Terminal, globalShortcut's are not working. This makes them not so global.

**Comment by vbarbarosh** [comment]
In order to reproduce just open `gnome-terminal` and

```bash
mkdir a
cd a
echo {} > package.json
cat > app.js << 'EOF'
const electron = require('electron');

electron.app.whenReady().then(function () {
    const ret = electron.globalShortcut.register('Meta+I', function () {
        console.log('globalShortcut triggers!');
    });
});
EOF
npm install electron
node_modules/.bin/electron app.js
```

**Comment by Tbhesswebber** [comment]
Just want to call out that I stumbled across [this Reddit post](https://www.reddit.com/r/gnome/comments/qye01v/why_screen_sharing_and_keyboard_shortcuts_dont/) while attempting to debug https://github.com/Eugeny/tabby/issues/8957.  It sounds like Wayland potentially requires manually forwarding the keypress to Electron.

Is there a way to manually fire a keyboard event from the command line?

cc: @codebytere

**Comment by Nantris** [comment]
This is a total dealbreaker to not be addressed, and especially not even documented. Our entire application relies on `globalShortcut` and we target Linux for both development and end users and as far as I can tell there's no plan to support the promised feature set?

**Comment by egeres** [comment]
I bypassed the problem in a convoluted way that suits my use case. My electron app exposes an API endpoint on `localhost` that calls the function I would invoke with the global shortcut. Then, it's possible to register global shortcuts in python (if you have sudo) using the module "keyboard", a script like this pings the server:

```python
import contextlib, keyboard, requests

def foo():
    with contextlib.suppress(Exception):
        requests.get("http://localhost:18233/toggle_display")

keyboard.add_hotkey("ctrl+alt+e", foo)
keyboard.wait()
```
