### ISSUE TITLE
session-end doesn't fire on Electron 1.7.10

### ISSUE THREAD

**Issue by agjs** [electron/electron#15864]
Electron version: *1.7.10*
OS: *Windows 10 Pro, version: 1803*

```js
this._win = new BrowserWindow(options);
this._win.on('session-end', () => {
    log('session-end debug'); // store a log into a file
    // do something else
});
```

1. I run my Electron application
2. I restart my Windows 10 computer
3. I expect a log to be written in a file and also another function to be executed.

* Am I doing something wrong? 
* Is there another event that I could listen on if user decides to restart/shutdown while the application is running? 
* Is there any way I can test this event without physically restarting my computer?

Thanks in advance

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron < `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
