### ISSUE TITLE
webContents.debugger.sendCommand('Emulation.setTouchEmulationEnabled' .... not work

### ISSUE THREAD

**Issue by cyqresig** [electron/electron#15875]
Output of `node_modules/.bin/electron --version`: `v3.0.7`      (I tried almost all the versions above 3.0.0)
Operating System (Platform and Version): Mac OSX Sierra
Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
do webview.webContents.debugger sendCommand('Emulation.setTouchEmulationEnabled ...);
touch emulation should be valid for the webview.

**Actual behavior**
touch emulation does not valid for the webview.

**To Reproduce**

https://github.com/cyqresig/electron-quick-start/tree/bug/webview_setTouchEmulationEnabled_cyq_20181129

```sh
$ git clone https://github.com/cyqresig/electron-quick-start -b bug/webview_setTouchEmulationEnabled_cyq_20181129
$ npm install
$ npm start || electron .
```

**Comment by hdwong** [comment]
+1

**Comment by lishoulong** [comment]
+1, before version 3, the Emulation.setTouchEmulationEnabled is work. @MarshallOfSound

**Comment by jacklovepdf** [comment]
+1

**Comment by peihexing** [comment]
+1

**Comment by lishoulong** [comment]
hello，i fix this question.

Just add another event

           method: 'Emulation.setEmitTouchEventsForMouse',
            params: {
                enabled: enable
            }

**Comment by zcbenz** [comment]
It seems that Chromium has silently changed the devtools API to separate enabling touch from emulating it via mouse:
https://chromium-review.googlesource.com/c/chromium/src/+/609373/

So you have to add an extra call:

```js
browser.debugger.sendCommand('Emulation.setEmitTouchEventsForMouse', {
  enabled: true,
}, (...args) => console.log(args))
```
