### ISSUE TITLE
Emulation.setTouchEmulationEnabled to a webview, it works, but the mouse cursor does not return to "default" style when I move the mouse out of the range of the webview

### ISSUE THREAD

**Issue by cyqresig** [electron/electron#15876]
Output of `node_modules/.bin/electron --version`: `v2.0.9`     (I tried almost all the versions above 2.0.0, below 3.0.0)
Operating System (Platform and Version): Mac OSX Sierra
Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
when setTouchEmulationEnabled to a webview and then mouse move out of the range of the webview, the mouse cursor style should return to "default" 

**Actual behavior**
when setTouchEmulationEnabled to a webview and then mouse move out of the range of the webview, the mouse cursor style does not return to "default" , still keep the "touch emulation" style.

**To Reproduce**

https://github.com/cyqresig/electron-quick-start/tree/but/setTouchEmulation_mouse_cursor_style_cyq_20181129

```sh
$ git clone https://github.com/cyqresig/electron-quick-start -b but/setTouchEmulation_mouse_cursor_style_cyq_20181129
$ npm install
$ npm start || electron .
```

![image](https://user-images.githubusercontent.com/1388338/49198852-21c36200-f3d0-11e8-8eb4-03c965a50b35.png)

![image](https://user-images.githubusercontent.com/1388338/49198957-9f876d80-f3d0-11e8-9950-8b7ca649789a.png)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
