### ISSUE TITLE
Cannot display shadows in win7 system frameless mode

### ISSUE THREAD

**Issue by insub** [electron/electron#15879]
* Operating System (Platform and Version):
Windows 7
* Output of `node_modules/.bin/electron --version` 
Electron v3.0.4

**Expected Behavior**
On win7 system , set frameless: true and display shadows

**Actual behavior**
On win7 system , if set frameless: true,  not display shadows, mac os is ok.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by aje** [comment]
I still have this problem. I am sure it won't go with this electron starter as well.
