### ISSUE TITLE
enumerateDevices returns inconsistent results

### ISSUE THREAD

**Issue by Niladev** [electron/electron#15886]
* Output of `node_modules/.bin/electron --version`: v3.0.10
* Operating System (Platform and Version): MacOS Mojave 10.14 & MacOS High Sierra 10.13
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): Unknown

**Expected Behavior**
When plugging in or removing an external webcam with a built in microphone, navigator.mediaDevices.enumerateDevices() should return a complete list of the devices available.

**Actual behavior**
A clear and concise description of what actually happened.
When plugging in or removing an external webcam with a built in microphone, navigator.mediaDevices.enumerateDevices() will sometimes return an incomplete list containing a removed device or missing a device that has been plugged in.

**To Reproduce**
Branch: https://github.com/Niladev/electron-enumerate-devices

To reproduce this, clone and start the project.
Use a camera with a built in microphone and continuously plugin and remove your webcam while observing the numbers in the web client and the electron client.  

```sh
$ git clone https://github.com/Niladev/electron-enumerate-devices.git
$ yarn install
$ yarn start
```
This will start a web server at port `1234` and an Electron client showing the number of devices connected. Click start on both clients and then plug in and remove the webcam repeatedly and observe different numbers.

**Screenshots**
[screenshot](https://user-images.githubusercontent.com/2597934/49240875-9913e880-f406-11e8-9c20-5e3ff1a274f8.png)

**Comment by korob93** [comment]
Same issue on my side
**Electron version**: 4.0.5
**OS**: macOS 10.14.2, windows 10

At the same time, chrome detects all media devices as expected. BTW, sometimes chrome and electron emit different amount of devicechange events

**Comment by johnnyopao** [comment]
Running into the same issue when adding/removing a physical device. 

An unplugged device still persists in the returned device list

Plugging in a new device does not show up on the list. Sometimes the 'audioInput' is detected but not the 'videoInput' from the same device.

Restarting Electron picks up the correct device list

Able to consistently reproduce this with a 'Logitech Brio'

**Comment by Ajeey** [comment]
@sofianguy Any update on the above issue? We've hit this and its a blocker :(

**Comment by Ajeey** [comment]
Any possible workarounds for folks using electron version 3?

**Comment by vhmth** [comment]
@Ajeey were you able to get it working on version 4? Just wondering based on how you mentioned electron 3.

**Comment by Ajeey** [comment]
> @Ajeey were you able to get it working on version 4? Just wondering based on how you mentioned electron 3.

Edited the post, I actually meant version 4

**Comment by Ajeey** [comment]
Also note the same code works in standalone chromium version 69 (which is what electron 4 uses)

**Comment by acbuitrago** [comment]
For anyone interested, I've checked this on Electron 5.0.2 on MacOS 10.14.4 and in this version this issue is no longer happening :).

**Comment by sofianguy** [comment]
I'm going to close this as it is reported as [fixed](https://github.com/electron/electron/issues/15886#issuecomment-498300093). Feel free to reach out if you are experiencing this issue on version 4.2.x or later

**Comment by OferSisso1** [comment]
@sofianguy 
I experience this issue on version 4.2.9

**Comment by itbra** [comment]
Can somebody  please tell me how to find the changes to the code base that solved this issue? I tried `git log | 15886` in current branch but got no results. I have independent code to where this exact same issue occurs and can't seem to find a solution.

**Comment by yles9056** [comment]
> Running into the same issue when adding/removing a physical device.
> 
> An unplugged device still persists in the returned device list
> 
> Plugging in a new device does not show up on the list. Sometimes the 'audioInput' is detected but not the 'videoInput' from the same device.
> 
> Restarting Electron picks up the correct device list
> 
> Able to consistently reproduce this with a 'Logitech Brio'

I'm experiencing this issue with electron 17.1.0 on MacOS 12
While the browser is using a webcam, if another webcam with microphone is plugged in, only its audioInput will be detected. The videoInput will not show up in the list.

Chrome and Edge both have the same behavior on MacOS 12

**Comment by Romej** [comment]
> Chrome and Edge both have the same behavior on MacOS 12

Experiencing the same thing here.

Seems specific to MacOS as it works fine on Windows 10.

**Comment by hengshanMWC** [comment]
Electron 11.0.1 also appears. Mac m1 version 12.1, nodev16.15.0

**Comment by hengshanMWC** [comment]
[#34196](https://github.com/electron/electron/issues/34196)，The same question @sofianguy

**Comment by patchworkfish** [comment]
An unplugged device still persists in the returned device list.

Electron:19.0.10
Node:16.14.2
Windows 10
Chromium: 102.0.5005.167

Reproducable with a logitech webcam with integrated mic.
When unplugging, the mic (type:'audioinput') updates correctly, but the camera (type:'videoinput') does not.

Do we need to raise a new issue as this thread is marked as "closed"?
