### ISSUE TITLE
session-end doesn't fire at all

### ISSUE THREAD

**Issue by agjs** [electron/electron#15880]
Electron version: 3.0.3
OS: Windows 10 Pro, version: 1803

Yesterday I've opened [session-end doesn't fire on Electron 1.7.10](https://github.com/electron/electron/issues/15864) thinking that it's an issue with Electron 1.7.10. This now at least for us, turns to be the case with Electron in general, regardless of the version (we are currently on 3.0.3).

To minimize any side-effects when testing, I've used Electron Starter and here is the test code:

```js
const { app, BrowserWindow } = require('electron');
const path = require('path');
const fs = require('fs');

let mainWindow;

function createWindow() {
  mainWindow = new BrowserWindow({ width: 800, height: 600 });
  mainWindow.loadFile(path.join(__dirname, '../renderer/index.html'));
  mainWindow.on('closed', function() {
    mainWindow = null;
  });

  mainWindow.on('session-end', function() {
    fs.mkdirSync(path.join(app.getPath('downloads'), 'test123'));
  });
}

app.on('ready', createWindow);
app.on('window-all-closed', function() {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', function() {
  if (mainWindow === null) {
    createWindow();
  }
});
```
**Expectation:** 
1. Run the app
2. Restart your machine 
3. A new folder inside Downloads folder should be created

**Result** 
Folder is not created. It seams that the event is not fired at all.

Based on my research and very minimal understanding of Windows API's, this is how session-end should be invoked:

1. We restart the computer
2. System sends WM_QUERYENDSESSION messages
3. System sends WM_ENDSESSION to all the applications that returned TRUE.

By using [SendMessage](https://tools.stefankueng.com/SendMessage.html) I was able to play with this a bit. If I directly send WM_ENDSESSION to our app process with _WPARAM: endsession_, event fires.

This issue could also be very well related to [callbacks for hookWindowMessage should have their return value sent to OS](https://github.com/electron/electron/issues/8762).

If the context from above article is true and we indeed don't return anything on *WM_QUERYENDSESSION*, why do we then expect to get *WM_ENDSESSION*? Doesn't WM_ENDSESSION only fires for those applications that return TRUE to *WM_QUERYENDSESSION*?

Please, feel free to ask for any more information, I'm willing to help.

**Comment by agjs** [comment]
@juturu By reading the source code, I noticed you implemented this event. Any idea of what could be wrong?

**Comment by Fndroid** [comment]
Same issue!
Any idea for handling system reboot event?

**Comment by belak** [comment]
Looking at documentation around queryendsession, it sounds like it would be useful to also provide a "query-end-session" event because "session-end" means that the app will be force killed soon - only absolutely necessary cleanup should be done there (everything possible should be in query-session-end such as autosaving).

**Comment by belak** [comment]
Additionally, since returning 0 from queryendsession will let you stop shutdown (https://docs.microsoft.com/en-us/windows/desktop/shutdown/wm-queryendsession) this would be extra useful, as it would make it possible to stop shutdown if desired in your application.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by agjs** [comment]
> With only the information that is currently in the issue, we don't have enough information to take action. 

Are you freaking kidding me?

**Comment by Eugeny** [comment]
@agjs it's likely a template reply and they're closing it because nobody replied to their last comment.

I can confirm that this is still an issue at least with Electron 4.2.10 and will retest with the latest release

**Comment by calebbergman** [comment]
Still an issue with Electron 6.0.7.

**Comment by nornagon** [comment]
Yeah, looks like we don't respond with `true` to WM_QUERYENDSESSION.

https://github.com/electron/electron/blob/b61805b63a32b70a3d6d0bef4cc58c580ff8ea38/shell/browser/native_window_views_win.cc#L330-L334

Reopening this.

**Comment by MichaelSp** [comment]
Still a thing on `21.1.0`

**Comment by belak** [comment]
I haven't attempted to reproduce this lately but I'm pretty sure it's still an issue.

**Comment by savely-krasovsky** [comment]
This should be no longer and issue, see #44598.
