### ISSUE TITLE
Notification (main) with empty body are not shown

### ISSUE THREAD

**Issue by alexstrat** [electron/electron#15882]
* Output of `node_modules/.bin/electron --version`: v3.0.9
* Operating System (Platform and Version): MacOS
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v2.0.13

**Expected Behavior**
Notification with no or empty `body` to show.

**Actual behavior**
Notification with no or empty `body` are not shown.

**To Reproduce**
Starting from `electron-quick-start`, drop this in `main.js`
```js
  setTimeout(() => {
    const n = new Notification({
      title: 'empty body',
      body: ''
    })
    n.show()
  }, 5000)
```

You won't see any notification appear.

Same with no `body`.

**Additional Information**
It seems that dropping a notifcation with empty body has an impact on subsequent notifications and block them.

**Comment by codebytere** [comment]
I ran 
```
const {app, BrowserWindow, Notification} = require('electron')

let mainWindow

function createWindow () {
  mainWindow = new BrowserWindow({width: 800, height: 600})

  mainWindow.loadFile('index.html')

  setTimeout(() => {
    const n = new Notification({
      title: 'empty body',
      body: ''
    })
    n.show()
  }, 2000)
  
  mainWindow.on('closed', () => mainWindow = null)
}

app.on('ready', createWindow)

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit()
})

app.on('activate', () => {
  if (mainWindow === null) createWindow()
})
```
and it worked as expected both on `master` and on `v3.0.9` on my machine running MacOS 14.0 Mojave. Do you have any other config i might be missing?

**Comment by alexstrat** [comment]
Thanks for testing!

Actually I can’t reproduce now.. I suppose it was only temporary on my machine.

Sorry for that, thanks for your time!

**Comment by alexstrat** [comment]
Was very probably solved by https://github.com/electron/electron/pull/17469
