### ISSUE TITLE
Electron-AWS-SDK-error

### ISSUE THREAD

**Issue by Arattian** [electron/electron#15897]
* Output of `node_modules/.bin/electron --version`: 3.0.7
* Operating System (Platform and Version): Ubuntu 18.04

**Expected behavior**
Works correct when working with aws-sdk.

**Actual behavior**

Vue.js application served with electron runs an error on any AWS-SDK usage.
AWS-SDK package shows error when after util.isNode() condition it is trying access to its util.stream.Stream and util.stream is undefined. By going up in aws code, i saw this lines

```
  util.isBrowser: function isBrowser() { return process && process.browser; }
  util.isNode: function isNode() { return !util.isBrowser(); }
```

The main problem is that when electron serves application process.browser is undefined,which forces to util.isNode() return true and error happens. This problem does not exist in when serving vue in browser.
I think this problem more related to how the electron configures itself, and on which environment it runs
and use packages. To wrap application with electron i use vue-electron-builder plugin for vue CLI. Which creates background.ts file, when it holds electron configuration. Default configuration

```
'use strict';

import { app, protocol, BrowserWindow } from 'electron';
import {
  createProtocol,
  installVueDevtools,
} from 'vue-cli-plugin-electron-builder/lib';
const isDevelopment = process.env.NODE_ENV !== 'production';

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
let win: any;

// Standard scheme must be registered before the app is ready
protocol.registerStandardSchemes(['app'], { secure: true });
function createWindow() {
  // Create the browser window.
  win = new BrowserWindow({ width: 1200, height: 800 });

  if (isDevelopment) {
    // Load the url of the dev server if in development mode
    win.loadURL(process.env.WEBPACK_DEV_SERVER_URL as string);
    if (!process.env.IS_TEST) {
      win.webContents.openDevTools();
    }
  } else {
    createProtocol('app');
    // Load the index.html when not in development
    win.loadFile('index.html');
  }

  win.on('closed', () => {
    win = null;
  });
}

// Quit when all windows are closed.
app.on('window-all-closed', () => {
  // On macOS it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On macOS it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (win === null) {
    createWindow();
  }
});

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', async () => {
  if (isDevelopment && !process.env.IS_TEST) {
    // Install Vue Devtools
    await installVueDevtools();
  }
  createWindow();
});

// Exit cleanly on request from parent process in development mode.
if (isDevelopment) {
  if (process.platform === 'win32') {
    process.on('message', (data) => {
      if (data === 'graceful-exit') {
        app.quit();
      }
    });
  } else {
    process.on('SIGTERM', () => {
      app.quit();
    });
  }
}

```

**To Reproduce**
Github Repo [https://github.com/Arattian/DynamoDb-Vue-Electron](url)

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone https://github.com/Arattian/DynamoDb-Vue-Electron.git
$ cd Dynamodb-Vue-Electron
$ npm i
$ npm electron:serve
Click to Add Database
Input any text, click confirm
```
**Screenshots**
![screenshot from 2018-11-30 13-54-00](https://user-images.githubusercontent.com/36269636/49289614-c1125300-f4bd-11e8-8cd3-34d0cb207ae6.png)

**Comment by MarshallOfSound** [comment]
@Arattian `process.browser` is a made up concept, invented by tools like `webpack`  that gets automatically replaced in bundles to indicate a browser environment.  This is not an Electron issue rather this library is using a non-standard way to detect if it's running in a node environment.
