### ISSUE TITLE
When passing a Redux store from Render to Main using electron.remote store.getState() returns undefined. 

### ISSUE THREAD

**Issue by photopaul25** [electron/electron#15914]
* Output of `node_modules/.bin/electron --version`:
v3.0.9
* Operating System (Platform and Version):
OSX 10.14

**Expected Behavior**
I would have expected`store.getState()` to return the state object. 

**Actual behavior**
`store.getState()` returned undefined. 

**To Reproduce**

main.js
```js
const stateProcessor = require('./stateProcessor')

const createMainWindow = () => {
    global.stateProcessor = stateProcessor
}
```

render.js
```js
import { createStore } from 'redux'
import reducers from './reducers'
const remote = window.require('electron').remote
const stateProcessor = remote.getGlobal('stateProcessor')

const store = createStore(reducers)

stateProcessor.processStore(store)
```

stateProcessor.js 
```js
const processStore = (store) => {
    console.log(store.getState())
}

module.exports = { processStore }
```

**Additional Information**
Redux version: 4.0.1

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
