### ISSUE TITLE
Need to reinstall electron when I develop the vscode extention

### ISSUE THREAD

**Issue by chnliquan** [electron/electron#15915]
* Output of `node_modules/.bin/electron --version`: 3.0.10
* Operating System (Platform and Version): OS 10.3.3
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 3.0.10

**Expected Behavior**
I have developed a vscode extension which has a function when i execute, it will open an electron app. It works normally in the extension host. After development, I package it with the` vsce package` command (not uploaded to the store). When I install the packaged extension locally, This function is invalid, I need to re-install the electron in the extension's directory, restart the vscode and restart the function successfully.
**Actual behavior**
i should reinstall electron in my extension cwd，it works
```
**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional Information**
Add any other context about the problem here.

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
