### ISSUE TITLE
Tray icon bug in deepin

### ISSUE THREAD

**Issue by nashaofu** [electron/electron#15918]
* Output of `node_modules/.bin/electron --version`: 3.0.9
* Operating System (Platform and Version): Deepin 15.8(Linux)
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2.0.14

**Expected Behavior**
The tray icon should be displayed

**Actual behavior**
The tray icon is shown as an incorrect Icon

**To Reproduce**
repertory: https://github.com/nashaofu/dingtalk

```sh
$ git clone https://github.com/nashaofu/dingtalk.git
$ npm install
$ npm run build
$ npm start || electron .
```
**Screenshots**
Expected:
![image](https://user-images.githubusercontent.com/19303058/49340517-d3d28680-f67b-11e8-92c2-39bbcbb137ba.png)
Actual:
![image](https://user-images.githubusercontent.com/19303058/49340485-69b9e180-f67b-11e8-9b34-ef87adfa35bc.png)

**Additional Information**
[dingtalk issues](https://github.com/nashaofu/dingtalk/issues/154)
2.x does not have this bug. The bug appears after 3.x.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by nashaofu** [comment]
Thank you very much. There is no problem now.
