### ISSUE TITLE
html not rendering

### ISSUE THREAD

**Issue by rajkumarGosavi** [electron/electron#15910]
v3.0.7
Debian  x86_64 GNU/Linux

**Expected Behavior**
The application should open a window and render the index.html file available printing the contents inside the window.

**Actual behavior**
The application opened a window but was unable to render the index.html file instead it got crashed.
Showing the background in the window of the application

**To Reproduce**
Simply clone the repository git clone https://github.com/electron/electron-quick-start and follow the instructions listed over [here](https://electronjs.org/docs/tutorial/first-app#trying-this-example)

**Screenshot**
![selection_001](https://user-images.githubusercontent.com/13183033/49319261-f0f34200-f521-11e8-8b17-610e3d2d0cec.png)
ts**
I have sublime text and terminal open inn background and the electron application in foreground it does not show the index.html instead it shows the area it overlapped.

**Comment by daniel-nth** [comment]
Had the same problem, 3.0.11 fixed it for me.

**Comment by RAJKUMAR18** [comment]
Thank you, Will try it asap. Also, was the bug not accounted for in the previous releases? If so, then how could the tutorial available on the official site uses 3.0.7(earlier) or 3.0.10(now) and still works(it says that it works if you follow the steps)? Please fix the tutorial too as it is misleading.

**Comment by tomasdev** [comment]
Weird, I'm seeing something like this on v4.0.0

It's escaping the HTML instead of rendering it.

![screen shot 2019-01-02 at 10 37 51 pm](https://user-images.githubusercontent.com/364033/50622921-0c65ba00-0edf-11e9-825a-64795c8b9670.png)

**Comment by coolmagic** [comment]
> Weird, I'm seeing something like this on v4.0.0
> 
> It's escaping the HTML instead of rendering it.
> 
> ![screen shot 2019-01-02 at 10 37 51 pm](https://user-images.githubusercontent.com/364033/50622921-0c65ba00-0edf-11e9-825a-64795c8b9670.png)

Hi

Did you manage to find solution for this?

**Comment by rajkumarGosavi** [comment]
Well according to the team the issue was resolved 
https://github.com/electron/electron/issues/15910#issuecomment-446259315
but i have changed my development stack and I am now using something else.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
