### ISSUE TITLE
Please communicate the release goals for each major release.

### ISSUE THREAD

**Issue by burtonator** [electron/electron#15922]
Right now there are three new major releases.

3.1 and 4.0...

I have no idea what the goals of these releases are.  No idea what new features are present, etc.

It's hard enough being downstream of Electron and not knowing what to expect but I can't contribute if I don't know what's in the releases.

Is there a primary dev mailing list that I'm missing?

**Comment by PalmerAL** [comment]
I think this explains everything: https://electronjs.org/blog/electron-2-semantic-boogaloo

Each new major version is based on a new version of Chromium, typically with some additional features added. When a bug is fixed, it's included in the latest major version (which right now is 4.0), and sometimes backported to earlier versions as well.

Theres a list of new features and bug fixes in each version on the releases page: https://github.com/electron/electron/releases

**Comment by burtonator** [comment]
Right ... but for example 3.1.0 beta just says this:

"Note: This is a beta release. Please file new issues for any bugs you find in it.

This release is published to npm under the beta tag and can be installed via npm install electron@beta, or npm i electron@3.1.0-beta.1."

... so I have no idea what to expect with 3.1.0 beta.  

and I get that there's 'new versions' but WHICH ones?  

What's the rational for 3.1.0?  What are the release goals?

**Comment by BinaryMuse** [comment]
Here's a link to the tracking issue for the website bug I mentioned: https://github.com/electron/electronjs.org/issues/1582

I'm going to close this issue for tidiness' sake, but that doesn't mean that we can't do better with communicating plans going forward. If you have any specific ideas on things you'd like to see, please let us know!
