### ISSUE TITLE
DevTools console commands not working

### ISSUE THREAD

**Issue by albu77** [electron/electron#15926]
* Windows7 64 bits
* Electron 2.1

**Expected Behavior**
I would like to use some command in the devtools console:
As getEventListeners($('#gestionregions'));
Or monitorEvents($('#region-sortable'));
And they don't work

**Actual behavior**
monitorEvents doesn't log anything
getEventListeners return an Object with no Listeners
![image](https://user-images.githubusercontent.com/624802/49371936-53eb0180-f6f9-11e8-8e43-77068da8c6c3.png)

**To Reproduce**
Your best chance of getting this bug looked at quickly is to provide a REPOSITORY that can be cloned and run.

You can fork [electron-quick-start](https://github.com/electron/electron-quick-start) and include a link to the branch with your changes.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone $YOUR_URL -b $BRANCH
$ npm install
$ npm start || electron .
```
**Screenshots**

**Additional Information**

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

Thanks in advance! Your help is appreciated.

**Comment by albu77** [comment]
Nothing to do with Electron, I was tired !!:
 This is related to Chrome and Chromium, which syntax for this Api doesn't support quote. So  
`getEventListeners(gestionregions);` and `monitorEvents(region-sortable);`
Work perfectly.
