### ISSUE TITLE
clear cookies removes all session data

### ISSUE THREAD

**Issue by promosjotte** [electron/electron#15928]
* Output of `node_modules/.bin/electron --version`:
v3.0.10
* Operating System (Platform and Version):
Windows 10

I need to delete the cookies of a session, not more. I need to keep things like localStorage.
```javascript
session.defaultSession.clearStorageData({options : {origin: 'XXX', storages : ['cookies']}}, function(data) 
{
    resolve();
});
```

**Expected Behavior**
It should only delete the cookies.

**Actual behavior**
It deletes all session data

**To Reproduce**
Try this snipet (replace 'XXX')
```javascript
session.defaultSession.clearStorageData({options : {origin: 'XXX', storages : ['cookies']}}, function(data) 
{
    //resolve();
});
```
It is based on the electron docs: https://electronjs.org/docs/api/session#sessionclearstoragedata

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
