### ISSUE TITLE
The new-window event doesn't fire when calling window.open from a webview with nativeWindowOpen=yes

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#15936]
* Output of `node_modules/.bin/electron --version`: 2.0.0
* Operating System (Platform and Version): Windows 10

**Expected Behavior**
The [`window.open` docs](https://electronjs.org/docs/api/window-open) suggest that I can latch on to the `new-window` event to intercept window creation when calling `window.open` with `nativeWindowOpen` set to "yes":

>This option (`nativeWindowOpen`) can also be set on `<webview>` tags as well:
>`<webview webpreferences="nativeWindowOpen=yes"></webview>`
>The creation of the `BrowserWindow` is customizable via `WebContents`'s `new-window` event.

I expect that if my `webview` tag has `nativeWindowOpen` set to "yes" and I open a window from the webview process via `window.open`, the `new-window` event will fire.

**Actual behavior**
The `new-window` event doesn't fire. (The `app::browser-window-created` event does fire, however)

**To Reproduce**
checkout the electron-quickstart repo and make the following modifications:

In main.js' `createWindow` function, add:

	mainWindow.webContents.on("new-window", (event, url) => {
		console.log("\n\n!!!!!!!!!!!!!!: " + url);
	});

Replace everything in the `<body>` of index.html (except for `script` tag) with:

    <webview src="https://google.com" webpreferences="nativeWindowOpen=yes" allowpopups/>

In renderer.js, open the devtools:

    setTimeout(() => { // hack to ensure that this code runs after the webview is all set up
        document.getElementsByTagName("webview")[0].openDevTools();
    }, 2000);

Run `npm start`, and run `window.open("https://google.com")` inside of the devtools of the webview. Notice that the url doesn't get logged. When running in VSCode, you can verify that no breakpoint inside of the `new-window` handler gets hit.

---

Upon consulting the source, I've noticed the `new-window` isn't emitted if `nativeWindowOpen` is turned on. From [here](https://github.com/electron/electron/blob/176a76217c5f70d92bf21f6782a0c838a1e5058e/lib/renderer/window-setup.js#L117):

    if (!usesNativeWindowOpen) {
        // Make the browser window or guest view emit "new-window" event.
        window.open = function (url, frameName, features) {
            // ...
           const guestId = ipcRenderer.sendSync('ELECTRON_GUEST_WINDOW_MANAGER_WINDOW_OPEN', url, toString(frameName), toString(features))
        // ...
    }

Is this an error in the docs, then? Should they be updated?

---
As a side note, setting `nativeWindowOpen=no` doesn't affect anything; `new-window` doesn't fire. The only way I can get that event to fire is if I do `window.open` from the non-webview renderer process.

**Comment by Tim91084** [comment]
@pushkin- I notice it works for me if I do the following...  hope it helps.

```typescript
app.on('web-contents-created', onWebContentsCreated)

function onWebContentsCreated(
  _: Electron.Event,
  contents: Electron.webContents
) {
  const anyContents = contents as any
  anyContents.on('new-window', handleNewPopupWindow)
}
```

**Comment by pushkin-** [comment]
@Tim91084 Thanks, but that still doesn't fix my problem.

I've verified that the `'web-contents-created` event is firing, and we're adding the `new-window` handler, but it never fires when opening a window from the webview process.

**Comment by Tim91084** [comment]
@pushkin- did you put the [allowpopups](https://electronjs.org/docs/api/webview-tag#allowpopups) attribute on the webview?

**Comment by MarshallOfSound** [comment]
@pushkin- The webContents in the webview is a different webContents to your window.

E.g. `mainWindow.webContents` won't emit the new window event, you have to listen to the "did-attach-webview" event and attach your "new-window" event listener onto the webContents passed into that attach event.

**Comment by monhi** [comment]
Could you please share a "did-attach-webview" sample code to handle new-window event.

**Comment by arunnambissan** [comment]
I am using electron 20.3.8 and I was facing the same issue. I was able to fix it by below approach:

```
app.on('web-contents-created', (e, webContents) => {
    if (webContents.getType() === 'webview') {
        webContents.setWindowOpenHandler(({ url }) => {
            shell.openExternal(url);
            // deny => prevents electorn window open
            return { action: 'deny' };
        });
    }
});
```

`<webview allowpopups=""></webview>`

In my case empty string assigned to allowpopups was crucial. It was not working if I am not assigning the empty string.
`allowpopups=""`

**Comment by surya-teja444** [comment]
iam rendering an webview in a renderer.html page, i have set the src to the webview, Links with target="_blank" inside of <webview> tag do nothing, they should just navigate the webview to the page that was supposed to be opened in a new tab.
This is not happening , can anyone help me out.

**Comment by monhi** [comment]
@surya-teja444 
Try this one:

https://github.com/monhi/electron-webview

**Comment by surya-teja444** [comment]
> [@surya-teja444](https://github.com/surya-teja444) Try this one:
> 
> https://github.com/monhi/electron-webview

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>My Browser</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
    />
    <style>
      #controls {
        display: flex;
        align-items: center;
        position: fixed;
        top: 0;
        width: 100%;
        background-color: black;
        z-index: 1;
        padding-top: 10px;
        padding-bottom: 10px;
      }

      #back i,
      #forward i,
      #reload i {
        font-size: 16px;
      }

      body {
        overflow: hidden;
      }

      #controls button {
        margin-right: 10px;
        color: rgb(252, 253, 254);
        outline: none;
        border: none;
        background-color: black;
        font-size: 20px;
      }

      #back:hover,
      #forward:hover,
      #reload:hover,
      #new-tab:hover {
        background-color: rgb(248, 237, 237);
        border-radius: 50%;
        cursor: pointer;
      }

      #tab-bar {
        display: flex;
        width: 100%;
        background-color: #ddd;
        z-index: 1;
        padding: 5px;
        height: 50px;
        box-sizing: border-box;
        margin-top: 50px;
        overflow-x: auto;
        white-space: nowrap;
      }

      .tab {
        padding: 5px 10px;
        cursor: pointer;
        background-color: #bbb;
        margin-right: 5px;
        border-radius: 5px;
        display: flex;
        align-items: center;
      }

      .tab.active {
        background-color: #eee;
      }

      .tab .close {
        margin-left: 10px;
        color: black;
        cursor: pointer;
      }

      #webview-container {
        flex: 1;
        display: flex;
        flex-direction: column;
        height: 100vh;
      }

      webview {
        flex: 1;
        width: 100%;
        height: calc(100vh - 90px);
        display: none;
      }

      webview.active {
        display: flex;
      }
      #offlineDialog .content {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        padding: 20px;
        color: blue;
        background-color: white;
        border-radius: 10px;
        text-align: center;
      }

      #offlineDialog p {
        font-size: 20px;
        font-weight: bold;
        color: red;
      }
      button {
        background: aliceblue;
        border: 3px black solid;
        cursor: pointer;
        font-size: 20px;
        color: white;
        background-color: #8231d3;
        border-radius: 20px;
      }
      .modal-footer {
        margin-top: 20px;
        text-align: right;
      }
      .modal {
        display: none;
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        width: 450px;
        padding: 20px;
        background-color: white;
        border: 2px solid black;
        z-index: 1000;
        box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);
      }
    </style>
  </head>

  <body>

    
    <div id="networkModal" class="modal">
      <h3 style="display: flex; align-items: center; justify-content: center">
        Please Connect to network
      </h3>
      <div class="modal-footer">
        <button onclick="closeNetworkModal()">OK</button>
      </div>
    </div>

    
    <div id="alertmodal" class="modal">
      <h3 style="display: flex; align-items: center; justify-content: center">
        Connected to the predefined network
      </h3>
      <div class="modal-footer">
        <button onclick="closeAlertModal()">OK</button>
      </div>
    </div>

    
    <div id="controls">
      <button title="Home" id="home">
        <i class="fas fa-home home-icon"></i>
      </button>
      <button title="Backward" id="back">
        <i class="fas fa-arrow-left"></i>
      </button>
      <button title="Forward" id="forward">
        <i class="fas fa-arrow-right"></i>
      </button>
      <button title="Reload" id="reload">
        <i class="fas fa-redo-alt"></i>
      </button>
      <button title="New Tab" id="new-tab">
        <i class="fas fa-plus"></i>
      </button>
    </div>

    
    <div id="tab-bar">
      <div class="tab active" data-webview-id="webview-1">
        TESSERACT <span class="close">&times;</span>
      </div>
    </div>

    
    <div id="webview-container">
      <webview id="webview-1" class="active" allowpopups=""></webview>
    </div>

    <script>
      const activeWebview = document.querySelector("webview.active");
     
      var ReceivedCollege = "";

      document.addEventListener("DOMContentLoaded", () => {
        checkNetwork();
        setInterval(() => {
          checkNetwork();
        }, [60000]);
      });

      //function to call to check whether connected to same network or not
      async function checkNetwork() {
        await window.electron.ipcRenderer.send("check-network");
      }

      var URLReceived = "";
      //assigning the source to the webview
      window.electron.ipcRenderer.receive("url-response", (response) => {
        if (response.message) {
          URLReceived = response.message;
          const firstWebview = document.getElementById("webview-1");
          if (firstWebview) {
            firstWebview.src = URLReceived;
          }
        }
      });

      // Receive the network status whether offline or online
      window.electron.ipcRenderer.receive("network-status", (status) => {
        if (!status.connected) {
          alertmodal.style.display = "block";
        }
      });

      //connected to same network or diff network close modal
      function closeAlertModal() {
        alertmodal.style.display = "none";
      }

      var toBeLogout = false;
      window.electron.ipcRenderer.receive("usb-device-count", (count) => {
        if (count === true) {
          toBeLogout = true;
        } else {
          toBeLogout = false;
        }
      });

      (async function () {
        ReceivedCollege = await window.electron.ipcRenderer.invoke(
          "request-forwarded-data"
        );
        const URL = await window.electron.ipcRenderer.send(
          "get-url",
          ReceivedCollege
        );

        //setting default tab source
        document.querySelector(
          ".tab.active"
        ).innerHTML = `${ReceivedCollege.toUpperCase()}-TESSERACT <span class="close">&times;</span>`;
        var firstWebvieww = document.getElementById("webview-1");
        firstWebvieww.src = URLReceived;

        document.getElementById("new-tab").addEventListener("click", () => {
          openInNewTab("newtab"); // Pass the URLReceived variable to the function
        });

        //new tab
        document.getElementById("new-tab").addEventListener("click", () => {
          function openInNewTab(url) {
            console.log("url is:", url);
            const newWebview = document.createElement("webview");
            const tabCount = tabBar.children.length + 1;
            newWebview.id = `webview-${tabCount}`;
            newWebview.src = url === "newtab" ? URLReceived : url;
            newWebview.classList.add("webview");
            webviewContainer.appendChild(newWebview);

            const newTab = document.createElement("div");
            newTab.classList.add("tab");
            newTab.innerHTML = `${ReceivedCollege.toUpperCase()}-TESSERACT <span class="close">&times;</span>`;
            newTab.dataset.webviewId = newWebview.id;
            tabBar.appendChild(newTab);

            setActiveTab(newTab);
          }
        });
      })();

      //online or offline modal close
      function closeNetworkModal() {
        networkModal.style.display = "none";
      }

      //checking whether online or offline and any usb devices detected for every 10 seconds
      setInterval(() => {
        if (!navigator.onLine) {
          networkModal.style.display = "block";
        } else {
          if (toBeLogout === true) {
            applyToAllWebviews();
          }
        }
      }, [10000]);

      const webviewContainer = document.getElementById("webview-container");
      const tabBar = document.getElementById("tab-bar");

      let selectedSchool = "";
      const intervals = {};

      //back button
      document.getElementById("back").addEventListener("click", async () => {
        const activeWebview = document.querySelector("webview.active");
        if (activeWebview) {
          if (activeWebview.canGoBack()) {
            activeWebview.goBack();
          } else {
            await logoutFromWebview(activeWebview);
            window.electron.ipcRenderer.send("back-to-front-page", "goBack");
          }
        } else {
          window.electron.ipcRenderer.send("back-to-front-page", "goBack");
        }
      });

      //home button
      document.getElementById("home").addEventListener("click", async () => {
        applyToAllWebviews();
        window.electron.ipcRenderer.send("back-to-front-page", "goBack");
      });

      //forward button
      document.getElementById("forward").addEventListener("click", () => {
        const activeWebview = document.querySelector("webview.active");
        if (activeWebview) {
          activeWebview.goForward();
        }
      });

      //reload button
      document.getElementById("reload").addEventListener("click", () => {
        const activeWebview = document.querySelector("webview.active");
        if (activeWebview) {
          activeWebview.reload();
        }
      });

      //tab closing and tab activating
      tabBar.addEventListener("click", async (event) => {
        if (event.target.classList.contains("tab")) {
          setActiveTab(event.target);
        } else if (event.target.classList.contains("close")) {
          const tabToClose = event.target.parentElement;
          const webviewId = tabToClose.dataset.webviewId;
          const webviewToClose = document.getElementById(webviewId);
          const allTabs = document.querySelectorAll(".tab");
          if (allTabs.length === 1) {
            await logoutFromWebview(webviewToClose);
          }

          clearInterval(intervals[webviewId]);
          delete intervals[webviewId];

          tabToClose.remove();
          webviewToClose.remove();

          if (tabToClose.classList.contains("active")) {
            const allTabs = document.querySelectorAll(".tab");
            if (allTabs.length > 0) {
              setActiveTab(allTabs[allTabs.length - 1]);
            }
          }
        }
      });

      //function to set active tab
      function setActiveTab(tabElement) {
        document
          .querySelectorAll(".tab")
          .forEach((tab) => tab.classList.remove("active"));
        tabElement.classList.add("active");

        const webviewId = tabElement.dataset.webviewId;
        document
          .querySelectorAll("webview")
          .forEach((wv) => wv.classList.remove("active"));
        document.getElementById(webviewId).classList.add("active");
      }

      function openInNewTab(url) {
        console.log("url is:", url);
        const newWebview = document.createElement("webview");
        const tabCount = tabBar.children.length + 1;
        newWebview.id = `webview-${tabCount}`;
        newWebview.src = url === "newtab" ? URLReceived : url;
        newWebview.classList.add("webview");
        webviewContainer.appendChild(newWebview);

        const newTab = document.createElement("div");
        newTab.classList.add("tab");
        newTab.innerHTML = `${ReceivedCollege.toUpperCase()}-TESSERACT <span class="close">&times;</span>`;
        newTab.dataset.webviewId = newWebview.id;
        tabBar.appendChild(newTab);

        setActiveTab(newTab);
      }

      async function logoutFromWebview(webview) {
        try {
          const webviewId = webview.getAttribute("id");
          await window.electron.ipcRenderer.invoke(
            "clear-webview-cookies",
            webviewId
          );
        } catch (err) {}
      }

      //function to execute logout script for all webviews
      function applyToAllWebviews() {
        const webviews = document.querySelectorAll("webview");

        webviews.forEach((webview) => {
          if (!intervals[webview.id]) {
            webview.addEventListener("did-finish-load", () => {
              logoutFromWebview(webview);
            });

            if (webview.isLoading() === false) {
              logoutFromWebview(webview);
            }
          }
        });
      }
    </script>
  </body>
</html>

this is my index.html , when iam clicking some buttons in the webview which should be open in new tab are not opening

**Comment by monhi** [comment]
Please first check the following link:

https://github.com/monhi/electron-webview

If it works as you expect, please focus on the differences between your project and it.

In this way, you can find what is necessary to change.
