### ISSUE TITLE
Enable v8 embedded builtins feature on arm

### ISSUE THREAD

**Issue by deepak1556** [electron/electron#15933]
It was disabled in https://github.com/electron/electron/pull/15939, check the commit for details.

Upstream tracking bug: https://bugs.chromium.org/p/v8/issues/detail?id=6666
Desgin doc: http://goo.gl/Z2HUiM

/cc @jkleinsc

**Comment by nornagon** [comment]
We should also consider dropping support for running `mksnapshot` on arm hosts.

**Comment by jkleinsc** [comment]
Closing as #15939 did not ot disabled the feature, it actually enabled embedded builtins feature for arm.
