### ISSUE TITLE
window.Notification is sometimes invalid

### ISSUE THREAD

**Issue by joeyer** [electron/electron#15944]
Call the window.Notification method of the rendering process, sometimes there will be no notification display on the mac, but no error is reported.

var Notification = window.Notification;
let notiInstance = new Notification(title, {
                    // icon: 'assets/images/normal.png',
                    body: body,
                    vibrate: [200, 100, 200],
                });
                notiInstance.onshow = function (err) {
       
                    setTimeout(function () {
                        notiInstance.close();
                      
                    }, 3000);
                }
                notiInstance.onerror = (e) => {
                    Log.info("error", e);
                };
                notiInstance.onclick = () => {
                   。。。。。
                };

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
