### ISSUE TITLE
Transparency does not work on Linux (black background instead)

### ISSUE THREAD

**Issue by doom-fr** [electron/electron#15947]
* Output of `node_modules/.bin/electron --version`:
in first bad version : 1.5.0
in latest beta : v4.0.0-beta.8
in lastest nightly : v4.0.0-nightly.20181010

* Operating System (Platform and Version):
Linux Debian Jessie : Linux version 3.16.0-7-amd64 (debian-kernel@lists.debian.org) (gcc version 4.9.2 (Debian 4.9.2-10+deb8u1) ) #1 SMP Debian 3.16.59-1 (2018-10-03)
and also in
Linux Debian Buster : Linux version 4.18.0-2-amd64 (debian-kernel@lists.debian.org) (gcc version 7.3.0 (Debian 7.3.0-29)) #1 SMP Debian 4.18.10-2 (2018-10-07)

* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):
v1.4.16

**Expected Behavior**
having a transparent background for the window

**Actual behavior**
having a black background for the window

**To Reproduce**
see https://gitlab.com/doom-fr/electron-transparency-bug.git

**Screenshots**

1.4.16
![image](https://user-images.githubusercontent.com/7809481/49438959-1309f000-f7c0-11e8-8467-88b19284aedd.png)

1.5.0
![image](https://user-images.githubusercontent.com/7809481/49438968-18ffd100-f7c0-11e8-88c7-a71bf080c10e.png)

4.0.0.beta.8
![image](https://user-images.githubusercontent.com/7809481/49646103-6da08780-fa1e-11e8-8a67-9a982766cd73.png)

**Additional Information**
-

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron < `1.8.x`; does this occur on new versions?

**Comment by doom-fr** [comment]
Yes it does until the nightly one.

Le mar. 4 déc. 2018 à 17:51, Shelley Vohr <notifications@github.com> a
écrit :

**Comment by doom-fr** [comment]
Have also tried it on a Debian Buster machine.
The result is the same :
- there's a break between 1.4.16 and 1.5.0
- it doesn't work with latest electron version

Seems to [work under Ubuntu](https://stackoverflow.com/posts/comments/94117362?noredirect=1);

**Comment by doom-fr** [comment]
Has someone succeed in reproducing the problem (or not reproducing!) on a Debian machine ?

Debian is a main distribution. If it doesn't work with it, it is a big problem. No ?

**Comment by doom-fr** [comment]
Does `--enable-transparent-visuals --disable-gpu` still needed in last versions ?
If no, since which version.

**Comment by doom-fr** [comment]
Sorry for close re-open
Just click bad button

**Comment by doom-fr** [comment]
Just tested and it works in 2.0.16
But not in 3.1.0 nor in 4.0.1

**Comment by Astrych** [comment]
@doom-fr Setting 300ms delay and that's it? Do you have enabled hardware acceleration? If yes: does your machine support hardware acceleration? In my case delay is enough for virtual machine (without hardware acceleration but for normal machines I need to add:
```
app.disableHardwareAcceleration();
```

**Comment by doom-fr** [comment]
@Astrych, 

> setting 300ms and that's it ?

Not really. Rather, make a lot of tests, lost a lot of days, tried 10ms as said [here](https://github.com/electron/electron/issues/2170#issuecomment-361549395), tried 10 times what is needed (100 ms) but does not tried more, make a lot of tests, realizes that it works sometimes and make a lot of tests again to found just that !

I have now hardware acceleration enabled but it works with or without `--disable-gpu`.
I use it with paper.js and it needs hardware acceleration. If not, it is very slow.

So now I have this in my package.json : `"start": "electron --enable-transparent-visuals ."`

**Comment by Astrych** [comment]
@doom-fr That 300ms is not a constant. It changes depending on you machine, system, available resources etc. Higher you set it, higher probability of success ;)

Ok, so maybe `--enable-transparent-visuals` make a trick and allow for running it with GPU. I will try that. Thanks.

**Comment by doom-fr** [comment]
@Astrych effectively time to wait depends of the machine, etc.
It is why I have asked if it is possible to have an event on that.

**Comment by Astrych** [comment]
Tested with electron 4.0.3 and disabling gpu as well as --enable-transparent-visuals are not required any longer for that fix to work (nouveau drivers) so there is an improvement over old versions. I hope that sleep time in "ready" event will also become unnecessary.

**Comment by doom-fr** [comment]
@Astrych Effectively, it works without `--enable-transparent-visuals`

I have added [this issue](https://github.com/electron/electron/issues/16808) to change the doc.

**Comment by chap-wong** [comment]
Subscribe to this problem, since I have the same issue on Ubuntu 18.04.
Wait long enough could solve the problem. However, since the waiting time depends on the machine, it is impractical while trying to deploy the apps across different machines.
Hope the electron team will come up a better solution soon.

**Comment by doom-fr** [comment]
I have requested this to Electron Team.

https://github.com/electron/electron/issues/16809

**Comment by zenghongtu** [comment]
add `app.commandLine.appendSwitch('enable-transparent-visuals');` and `setTimeout` 500ms can solved it. (ubuntu 18 / electron 7.1.7) 👻👻

**Comment by cosoc** [comment]
我的 Debian 10 上也出现这个问题

**Comment by cosoc** [comment]
我在另一个问题中看到如下的解决方案,亲测可用:

```js
app.on('ready', () => setTimeout(your window create function, 400));
```

```js
function createWindow () {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    width: 500,
    height: 500,
    frame: false,
    transparent: true,
    alwaysOnTop: true,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js')
    }
  })

 // 设置延迟
app.on('ready', () => setTimeout(createWindow, 400));
```

**Comment by ckerr** [comment]
For what it's worth, the workaround mentioned by @doom-fr at https://github.com/electron/electron/issues/16809  works for me.

**Comment by zduronshawn** [comment]
if you're on win7, and the theme is windows basic theme, you should change your theme to  windows aero theme, then , transparent will work .but i wonder is there a better way to fix it

**Comment by Pevernow** [comment]
"--disable-gpu" and latency do make it work.

But I need to use webgl, which is not a good solution.

Is there any way to make transparency and webgl work on Linux at the same time?

**Comment by shubham-root** [comment]
```js
if(process.platform === "linux") {
  app.commandLine.appendSwitch('enable-transparent-visuals');
  app.disableHardwareAcceleration();
}```
before your
`app.on('ready`, () => {..})` 
seems to do the trick for me on Ubuntu 18.04/Electron 11.2.3

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by doom-fr** [comment]
Easy to wait more than two years without doing anything and tell that the version is not supported any more ...

In the last month users seems to encounter the problem.
@shubham-root & @Pevernow, can you confirm this is still an issue in the last release ?

Thanks.
