### ISSUE TITLE
BrowserWindow doesn't render when using webContents.send()

### ISSUE THREAD

**Issue by imolorhe** [electron/electron#15940]
**Expected Behavior**
I expect that the triggered DOM changes would be rendered when I send a message to a browser window from the main process using `webContents.send()`, without requiring an event be dispatched in the window.

**Actual behavior**
When I send an asynchronous message to the renderer process, the logs in the renderer process are shown in the devtools console (meaning that the renderer process receives the message) but the corresponding DOM updates aren't reflected in the window, that is until I dispatch another event in the window (like moving the mouse cursor within the window. Moving the mouse cursor outside the window has no effect either) after which the DOM updates accordingly.

**Additional Information**
I'm trying to understand what the possible reasons why the DOM might not have been promptly updated, maybe electron performs some tasks lazily for performance reasons which I am triggering in my app in some way.

The app with the issue is: https://github.com/imolorhe/altair/blob/staging/electron/window.js

**Comment by MarshallOfSound** [comment]
Can you provide a minimal repro preferably based off `electron-quick-start`.  We can't dive into a random app but if you can reproduce the problem in a minimal way we can look at it.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
