### ISSUE TITLE
Rename Atom.app Without Crash?

### ISSUE THREAD

**Issue by jjerome00** [electron/electron#15941]
I want to rename Atom.app to a different name, and have both copies work as a completely separate apps.  I use atom for both development and notes (and some other uses), so it would be useful to have my Mac treat them as separate apps.

I've read:
- https://github.com/electron/electron/issues/960
- https://github.com/electron/electron/issues/340 (which #960 refers to)
- https://electronjs.org/docs/tutorial/application-distribution#macos

I've followed all these suggestions, but nothing seems to work.  I get error messages similar to:
- `You can’t open the application “MyAppName.app” because it may be damaged or incomplete.`
- `MyAppName.app quit unexpectedly`

The issues I reference are from around 2015.  So I thought there was a possibility that the docs (https://electronjs.org/docs/tutorial/application-distribution#macos) were out of date.

Thanks for your time.

**Comment by MarshallOfSound** [comment]
Renaming will break code signitures, there is nothing we can do here
