### ISSUE TITLE
Minimizing window on X11 does not result in `visibilitychange` under non-EWMH-compliant window managers

### ISSUE THREAD

**Issue by futpib** [electron/electron#15956]
* Output of `node_modules/.bin/electron --version`: v6.0.1
* Operating System (Platform and Version): Linux 4.19.61-1-lts
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): n/a

**Expected Behavior**
When running under [xmonad](https://xmonad.org/) or [i3](https://i3wm.org/) (a window manager that does not set `_NET_WM_STATE` window property, that is, it does not completely conform to [freedesktop EWMH spec](https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html)) `visibilitychange` events, `document.hidden` and `document.visibilityState` should reflect the actual window state (minimized or normal).

**Actual behavior**
`visibilitychange` event never fires and `document.hidden` is always `true`

**To Reproduce**
The reproduction is a bit hairy.
The following binaries should be installed on your system:
* `Xephyr` - nested X server
* `xdotool` - to simulate user input
* `xprop` - to log window property changes
* `kwin_x11` - a compliant WM (I hope scripts are not hard to modify for a different WM)
* `xmonad` and/or `i3` - a non-compliant WM

Demo repo: https://github.com/futpib/electron-issue-x-ewmh-visibility-demo/

```sh
git clone https://github.com/futpib/electron-issue-x-ewmh-visibility-demo/
cd electron-issue-x-ewmh-visibility-demo
yarn

# Passing case:
bash ./test-kwin_x11.sh

# Failing cases:
bash ./test-xmonad.sh
bash ./test-i3.sh
```

Under `kwin_x11` you can see window minimization/maximization accompanied by `visibilitychange` event logs on the terminal (among other output) and notifications.

Under `xmonad` and `i3` you can see window minimization/maximization without any `visibilitychange` events fired (and thus no stdout or notifications).

Output should also contain colored `xprop -spy` logs, so that it's easy to see the difference between WMs.

**Additional Information**
Most mainstream window managers do implement [EWMH](https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html) and do set `_NET_WM_STATE(ATOM) = _NET_WM_STATE_HIDDEN` when window is hidden. This is the thing that `electron` currently monitors, and it works fine for said WMs:

https://github.com/electron/electron/blob/6f91af93433df4e9c0e7fb592e5b2dcb0b1c7888/atom/browser/ui/x/window_state_watcher.cc#L58-L62

Other more minimalistic WMs only change `WM_STATE(WM_STATE)` between `Normal` and `Withdrawn` or `Iconic` (or is it the X server itself that does that? I'm not sure). `electron` should observe `WM_STATE` changes as well as or instead of `_NET_WM_STATE`.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by futpib** [comment]
This is still how `IsWindowStateEvent` is implemented, so I'm sure the issue is still reproducible.

https://github.com/electron/electron/blob/34c4c8d5088fa183f56baea28809de6f2a427e02/shell/browser/ui/x/window_state_watcher.cc#L58-L62

**Comment by futpib** [comment]
I updated the issue description and the demo repo, this issue is still reproducible with electron v6.0.1

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
