### ISSUE TITLE
Large port number treated as invalid erroneously.

### ISSUE THREAD

**Issue by joshuef** [electron/electron#15959]
* Output of `node_modules/.bin/electron --version`: 2.0.8
* Operating System (Platform and Version): macOS 0.14.1

**Expected Behavior**
As per the [URL RFC](https://tools.ietf.org/html/rfc3986#section-3.2.3) there is no limit to the size of port numbers. So any url with a port number should be considered valid. eg `http://someurl:12345678` should be attempted to be resolved by a `webview`.

**Actual behavior**
Port numbers above `65535` are treated as invalid and a `webview` directly throws an error in `did-fail-load`. No attempt to resolve the request is made.

**To Reproduce**
Attempt to load a large port url (above `65535`, eg `http://someurl:12345678` ) in a `webview`. `did-fail-load` is immediately hit. No `webRequest` event is made,

**Additional Information**
We'd like to be using the port style syntax for a custom url handler (with these larger numbers), but there's currently no way to override URL validation, or capture the URL before it's deemed invalid.

https://github.com/maidsafe/safe_browser/issues/429

**Comment by MarshallOfSound** [comment]
@joshuef This standard is inherited from Chrome and is based upon [RFC 1340](https://tools.ietf.org/html/rfc1340#page-23) in particular the Registered Port range.

> The Registered Ports are in the range 1024-65535

I don't think we should be overriding this behavior.  The upper port limit is standard across most languages and environments.  The TCP spec actually only allows for 32bits to store both the source and destination port thus only allowing a 16bit number to store the destination port which has a maximum value of 2^16 (65536)
