### ISSUE TITLE
Documentation is not escaping HTML properly

### ISSUE THREAD

**Issue by eugirdor** [electron/electron#15965]
This is an issue with the documentation, not the framework.

**Expected Behavior**
HTML should be escaped properly in the generated documentation.

**Actual behavior**
HTML from Git Issues titles are being rendered in the documentation.

**To Reproduce**
Note the 3rd issue under macOS https://electronjs.org/releases#2.0.3.  An input field is being rendered for the description of #13277

**Screenshots**
<img width="832" alt="screen shot 2018-12-05 at 2 25 31 pm" src="https://user-images.githubusercontent.com/1062181/49548185-c4c91f80-f899-11e8-810c-2769d8c410ad.png">

**Additional Information**
Tested in Firefox 63 and Chrome 70 on macOS 10.14

**Comment by k3ithl1m** [comment]
May I help fix this issue and make a pull request?

**Comment by k3ithl1m** [comment]
Ok, Ill wait thn

**Comment by nornagon** [comment]
nobody's currently working on fixing the old documentation! Just that you might find that some part of this is already fixed :)

cc @zeke

**Comment by k3ithl1m** [comment]
I can't seem to find the documentation for releases. Would you be able to help me with locating that?

**Comment by MarshallOfSound** [comment]
Moving to https://github.com/electron/releases/issues/17
