### ISSUE TITLE
3.1 regression: crash when negotiate authenticating to a proxy for an https request 

### ISSUE THREAD

**Issue by bughit** [electron/electron#15963]
* Output of `node_modules/.bin/electron --version`: v3.1.0-beta.2 x86
* Operating System (Platform and Version): win7 sp1 x64
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 3.0.10

**Expected Behavior**
no crash

**Actual behavior**
crash before webContents.login event

**To Reproduce**
repro directions are the same as #14411

**Additional Information**
[stacktrace](https://github.com/electron/electron/issues/14411#issuecomment-444590623)

3.0.10 also crashes but on exit, not at the point of authentication, so possibly a different cause.

**Comment by MarshallOfSound** [comment]
These two issues are almost certainly related, can we keep them all in #14411 so that it's easier to follow this chain of issues
