### ISSUE TITLE
Error message:Module not found: Error: Can't resolve 'fs'

### ISSUE THREAD

**Issue by lpt9** [electron/electron#15968]
* Output of `node_modules/.bin/electron --version`:2.0.0
* Operating System (Platform and Version):win-64
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior:**
There were no errors when the module was introduced

**Actual behavior:**
I introduced ss in a file, but was prompted with the following error:
`Module not found: Error: Can't resolve 'fs' in 'D:\work\project\project_code\fincdevs\finc-dev\node_modules\electron'`

Whether I introduce it in the following two ways, there are errors:
1.`const {BrowserWindow, globalShortcut} = require('electron');`
2.`import { BrowserWindow, globalShortcut } from 'electron';`

After looking up information, someone try to add target: 'node' in webpack config section, like this :
 node: {
    fs: 'empty',
  }

But there will be new problems:
Uncaught TypeError: fs.existsSync is not a function

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
