### ISSUE TITLE
Allow logging to a file on Windows

### ISSUE THREAD

**Issue by nornagon** [electron/electron#15979]
With Chrome, `--enable-logging --log-file=log.txt` on Windows results in logs being written to `log.txt`. Electron, however, ignores the `--log-file` and always writes to the system debug log with `OutputDebugString`: https://github.com/electron/electron/blob/master/atom/app/atom_main_delegate.cc#L139

It's useful for telemetry to be able to redirect logs to a file, and there's presently no reliable way to do that on Windows.

**Comment by mrobrian** [comment]
Until there is better built-in support, I recommend [electron-log](https://www.npmjs.com/package/electron-log). We created a Windows app and use that package, and it has some nice features.

**Comment by nornagon** [comment]
It doesn't log Chromium's logs to that file though, which is important :)

**Comment by robatwilliams** [comment]
This would be very useful, especially given that piping electron output to a file does not work. When I try to do that, a new console window is opened for every process, and nothing ends up in the file.

**Comment by miniak** [comment]
Addressed by #25089
