### ISSUE TITLE
Cannot find libnode.so

### ISSUE THREAD

**Issue by RossComputerGuy** [electron/electron#15974]
* Output of `node_modules/.bin/electron --version`: `/home/osjs/.nvm/versions/node/v10.14.1/lib/node_modules/electron/dist/electron: error while loading shared libraries: libnode.so: cannot open shared object file: No such file or directory`
* Operating System (Platform and Version): `OS.js Linux Distro 1.0.0` (Based on Ubuntu Xenial)
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): `/home/osjs/.nvm/versions/node/v10.14.1/lib/node_modules/electron/dist/electron: error while loading shared libraries: libnode.so: cannot open shared object file: No such file or directory`

**Expected Behavior**
Electron to run.

**Actual behavior**
It cannot find `libnode.so`

**To Reproduce**
Setup a OS.js Linux build and run electron inside of it.

**Comment by nornagon** [comment]
What version of Electron are you using? In Electron 4.0.0 and newer, there shouldn't be any `libnode.so`. Seems like this could be an issue in OS.js.

**Comment by SpaceboyRoss01** [comment]
I installed the latest one from npm

**Comment by nornagon** [comment]
That would be 3.0.10 at the time of writing.

Can you provide the output of `tree node_modules/electron/dist`? `libnode.so` should be present in there if electron downloaded successfully.

**Comment by SpaceboyRoss01** [comment]
```
[spaceboyross@RX-178_Gundam_Mk-II lib]$ tree node_modules/electron/dist
bash: tree: command not found
```

**Comment by SpaceboyRoss01** [comment]
```
[spaceboyross@RX-178_Gundam_Mk-II lib]$ tree node_modules/electron/dist
node_modules/electron/dist [error opening dir]

0 directories, 0 files
```

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
