### ISSUE TITLE
Electron with boilerplate doesn't open but opens with quick start app in windows 10

### ISSUE THREAD

**Issue by MostafaSalama** [electron/electron#15981]
* Output of `node_modules/.bin/electron --version`:
* Operating System (Platform and Version):

* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

### Expected behavior

I am trying to run electron app in windows 10 with different boilerplate like 
https://github.com/electron-react-boilerplate/electron-react-boilerplate
https://github.com/SimulatedGREG/electron-vue
electron-forge 

but the app doesn't open and just runs in the background , I can see that via the task manger in windows , but I can't see the electron window 
### Actual behavior
but when I use electron-quick-start repo the app works perfect and it opens and I can see the actual window of the app 

I don't understand why this happens ? 
anyone can help ?

**Comment by BrayanIribe** [comment]
If the app works perfect with **electron-quick-start** then is a problem in your app. Is probably that you have misconfigured the main.js. Please provide your main.js code of your Electron app.

**Comment by MostafaSalama** [comment]
this is my main.js used by 
https://github.com/nklayman/vue-cli-plugin-electron-builder
`import { app, protocol, BrowserWindow } from 'electron'
import {
  createProtocol,
  installVueDevtools
} from 'vue-cli-plugin-electron-builder/lib'
const isDevelopment = process.env.NODE_ENV !== 'production'

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
let win

// Standard scheme must be registered before the app is ready
protocol.registerStandardSchemes(['app'], { secure: true })
function createWindow () {
  // Create the browser window.
  win = new BrowserWindow({ width: 800, height: 600 })

  if (isDevelopment || process.env.IS_TEST) {
    // Load the url of the dev server if in development mode
    win.loadURL(process.env.WEBPACK_DEV_SERVER_URL)
    if (!process.env.IS_TEST) win.webContents.openDevTools()
  } else {
    createProtocol('app')
    // Load the index.html when not in development
    win.loadURL('app://./index.html')
  }

  win.on('closed', () => {
    win = null
  })
}

// Quit when all windows are closed.
app.on('window-all-closed', () => {
  // On macOS it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  // On macOS it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (win === null) {
    createWindow()
  }
})

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', async () => {
  if (isDevelopment && !process.env.IS_TEST) {
    // Install Vue Devtools
    await installVueDevtools()
  }
  createWindow()
})

// Exit cleanly on request from parent process in development mode.
if (isDevelopment) {
  if (process.platform === 'win32') {
    process.on('message', data => {
      if (data === 'graceful-exit') {
        app.quit()
      }
    })
  } else {
    process.on('SIGTERM', () => {
      app.quit()
    })
  }
}`

**Comment by BrayanIribe** [comment]
Well, I don't know about Vue-cli, but probably the problem is in the statement `app.on('ready')`, I've tested your code and the problem is, that the function installVueDevtools() is not being resolved. Causing your problem. You can remove that statement or check why that function is not being resolved. I hope that is your problem.

**Comment by MostafaSalama** [comment]
I think the problem solved using ready-to-show event 
win.once('ready-to-show', () => {
  win.show()
})
this solved the problem

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
