### ISSUE TITLE
InputBar can't suppout all of emoji

### ISSUE THREAD

**Issue by boboxiaodd** [electron/electron#15989]
* Output of `node_modules/.bin/electron --version`: 3.0.10
* Operating System (Platform and Version): Mac
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):v3.0.10

**Expected Behavior**

show all of emoji when insert emoji

**Actual behavior**

some of emoji can't show : 🥶🥳🥵 etc..

**To Reproduce**

1. fouce input or textarea 
2. Control + Command + SPACE , and choose 🥶🥳🥰....etc.
3. it can't show

**Screenshots**

![image](https://user-images.githubusercontent.com/4714247/49730278-dacc4b00-fcb2-11e8-9936-3acb0bc07fc5.png)

**Comment by boboxiaodd** [comment]
i test other website ,it correct .

**Comment by boboxiaodd** [comment]
```javascript
mainWindow.loadURL('https://framework7.io/kitchen-sink/core/index.html?theme=ios')
```
use top search , it can't show 🥶🥳🥰....etc..

but in Chrome , it's correct!

**Comment by codebytere** [comment]
I suspect that this is the case with newer emoji; since support for them is added in newer chrome versions we'll support those once we've got those versions in `master`.
