### ISSUE TITLE
Microsoft Store In App Subscription API Required to submit to Microsoft Store yet not supported in Electron

### ISSUE THREAD

**Issue by sferoze** [electron/electron#15982]
I am trying to submit my app to the Microsoft Store but it just got rejected today with the comments that in order for my app to be approved I MUST use the Microsoft In App Purchase Subscription API. This is similar to submitting to the Mac App store where you must use their subscription API or else you will be denied. 

So with Electron Apps it is impossible to create a SAAS app that offers subscription and submit to Microsoft Store since Electron has no support for Microsoft Store Purchase API. 

I read here: https://electronjs.org/blog/in-app-purchases @AdrienFery that Microsoft Store API may be in the works so I wanted to check if there is any news regarding this. 

Is there an alternative method I can use to get my SAAS app into the Microsoft Store in the meantime?

Thanks!

**Comment by nornagon** [comment]
You might be able to use [NodeRT](/NodeRT/NodeRT) to call https://docs.microsoft.com/en-us/uwp/api/windows.services.store

/cc @felixrieseberg

**Comment by goldfire** [comment]
@sferoze @nornagon @felixrieseberg Has anyone actually gotten NodeRT working for this? We spent quite a bit of time trying to get it to work about a year ago and nothing we did worked. It doesn't seem like anything has changed with NodeRT in that time.

**Comment by vinidiktov** [comment]
I'd also like to know how to implement in-app purchases for WIndows Store.

Any suggestions?

Has anybody actually tried to use NodeRT for this?

**Comment by jimmy-tfp** [comment]
I tried NodeRT but it did not expose all the apis I believe you need to do purchases.

I did however see this:
https://github.com/Polarrco/windows-IAP-bridge

I have it working to the point of bringing up the correct purchasing dialogs, I will let this thread know if my app is actually accepted.

**Comment by vasyl-shumskyi** [comment]
@jimmy-tfp thanks for the info. was you app accepted by store?

**Comment by jimmy-tfp** [comment]
I dropped this project as Microsoft just kept putting obstacles up.

**Comment by adam-lynch** [comment]
@sferoze I see that your app (Memrey) was published on 13/12/2018 and that it includes a way to upgrade your subscription. What happened?

![image](https://user-images.githubusercontent.com/1427241/89034179-5a97a500-d330-11ea-953f-b1e82f576bfd.png)

---

Can anyone give an up to date summary of Electron in the Windows App Store? Is this still an issue?

Also in general, I'm not sure what is and isn't allowed regarding payments. It would be great if anyone could clarify. I know Apple are strict in that all payments must go through their system and you can't mention/link to your own billing/payments. The [Windows app store guidelines](https://docs.microsoft.com/en-us/windows/uwp/publish/store-policies#108-financial-transactions) are not clear to me. 10.8.1 seems to imply it is as strict as Apple, whereas 10.8.2 seems to say you can use a third party API.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
