### ISSUE TITLE
electron cant find fpm-linux-arm to build my deb package

### ISSUE THREAD

**Issue by Askmewho** [electron/electron#15984]
make electron-build RELEASE_TYPE=snapshot
./scripts/resin/electron/build.sh \
	-b /home/pi/etcher \
	-r armv7hf \
	-s linux \
	-v production \
	-n dist/.tmp/npm \
	-w dist/.tmp
Electron Builder Configuration:
{
  "npmRebuild": false,
  "nodeGypRebuild": true,
  "publish": null,
  "files": [
    "lib",
    "build/**/*.node",
    "assets/icon.png",
    "node_modules/**/*",
    "!lib/gui/app",
    "lib/gui/app/index.html",
    "generated"
  ],
  "mac": {
    "icon": "assets/icon.icns",
    "category": "public.app-category.developer-tools"
  },
  "dmg": {
    "background": "assets/dmg/background.tiff",
    "icon": "assets/icon.icns",
    "iconSize": 110,
    "contents": [
      {
        "x": 140,
        "y": 225
      },
      {
        "x": 415,
        "y": 225,
        "type": "link",
        "path": "/Applications"
      }
    ],
    "window": {
      "width": 540,
      "height": 405
    }
  },
  "win": {
    "icon": "assets/icon.ico"
  },
  "nsis": {
    "oneClick": true,
    "runAfterFinish": true,
    "installerIcon": "assets/icon.ico",
    "uninstallerIcon": "assets/icon.ico",
    "deleteAppDataOnUninstall": true,
    "license": "LICENSE",
    "artifactName": "${productName}-Setup-${version}-${env.TARGET_ARCH}.${ext}"
  },
  "portable": {
    "artifactName": "${productName}-Portable-${version}-${env.TARGET_ARCH}.${ext}",
    "requestExecutionLevel": "user"
  },
  "linux": {
    "icon": "assets/iconset",
    "category": "Utility",
    "packageCategory": "utils",
    "synopsis": "balenaEtcher is a powerful OS image flasher built with web technologies to ensure flashing an SDCard or USB drive is a pleasant and safe experience. It protects you from accidentally writing to your hard-drives, ensures every byte of data was written correctly and much more.",
    "executableName": "balena-etcher-electron"
  },
  "deb": {
    "depends": [
      "gconf2",
      "gconf-service",
      "libappindicator1",
      "libasound2",
      "libatk1.0-0",
      "libc6",
      "libcairo2",
      "libcups2",
      "libdbus-1-3",
      "libexpat1",
      "libfontconfig1",
      "libfreetype6",
      "libgcc1",
      "libgconf-2-4",
      "libgdk-pixbuf2.0-0",
      "libglib2.0-0",
      "libgtk2.0-0",
      "liblzma5",
      "libnotify4",
      "libnspr4",
      "libnss3",
      "libpango1.0-0",
      "libstdc++6",
      "libx11-6",
      "libxcomposite1",
      "libxcursor1",
      "libxdamage1",
      "libxext6",
      "libxfixes3",
      "libxi6",
      "libxrandr2",
      "libxrender1",
      "libxss1",
      "libxtst6",
      "polkit-1-auth-agent | policykit-1-gnome | polkit-kde-1"
    ],
    "priority": "optional"
  },
  "rpm": {
    "depends": [
      "lsb",
      "libXScrnSaver"
    ]
  },
  "appId": "io.balena.etcher",
  "copyright": "Copyright 2016-2018 Balena Ltd",
  "productName": "balenaEtcher"
}
WARNING: No Sentry token found (ANALYTICS_SENTRY_TOKEN is not set)
WARNING: No Mixpanel token found (ANALYTICS_MIXPANEL_TOKEN is not set)
~/etcher ~/etcher
electron-builder 19.40.0
Using /tmp/tmp.mNWYSAkhyE configuration file
Using /tmp/tmp.mNWYSAkhyE configuration file
Executing node-gyp rebuild for arch armv7l
Skip app dependencies rebuild because npmRebuild is set to false
Packaging for linux armv7l using electron 1.7.13 to dist/linux-armv7l-unpacked
Building deb
Error: Exit code: 1. Command failed: /home/pi/.cache/electron-builder/fpm/fpm-1.9.2-2.3.1-linux-x86_64/fpm -s dir -t deb --architecture armv7l --name balena-etcher-electron --force --after-install /tmp/temp-dir-mygF7X/1-after-install --after-remove /tmp/temp-dir-mygF7X/0-after-remove --description balenaEtcher is a powerful OS image flasher built with web technologies to ensure flashing an SDCard or USB drive is a pleasant and safe experience. It protects you from accidentally writing to your hard-drives, ensures every byte of data was written correctly and much more.
 Flash OS images to SD cards and USB drives, safely and easily. --maintainer Balena Inc. <hello@etcher.io> --vendor Balena Inc. <hello@etcher.io> --version 1.4.8+cf596a88 --package /home/pi/etcher/dist/balena-etcher-electron_1.4.8+cf596a88_armv7l.deb --url https://github.com/balena-io/etcher --category utils --deb-compression xz --deb-priority optional --depends gconf2 --depends gconf-service --depends libappindicator1 --depends libasound2 --depends libatk1.0-0 --depends libc6 --depends libcairo2 --depends libcups2 --depends libdbus-1-3 --depends libexpat1 --depends libfontconfig1 --depends libfreetype6 --depends libgcc1 --depends libgconf-2-4 --depends libgdk-pixbuf2.0-0 --depends libglib2.0-0 --depends libgtk2.0-0 --depends liblzma5 --depends libnotify4 --depends libnspr4 --depends libnss3 --depends libpango1.0-0 --depends libstdc++6 --depends libx11-6 --depends libxcomposite1 --depends libxcursor1 --depends libxdamage1 --depends libxext6 --depends libxfixes3 --depends libxi6 --depends libxrandr2 --depends libxrender1 --depends libxss1 --depends libxtst6 --depends polkit-1-auth-agent | policykit-1-gnome | polkit-kde-1 --license Apache-2.0 /home/pi/etcher/dist/linux-armv7l-unpacked/=/opt/balenaEtcher /home/pi/etcher/assets/iconset/128x128.png=/usr/share/icons/hicolor/128x128/apps/balena-etcher-electron.png /home/pi/etcher/assets/iconset/16x16.png=/usr/share/icons/hicolor/16x16/apps/balena-etcher-electron.png /home/pi/etcher/assets/iconset/256x256.png=/usr/share/icons/hicolor/256x256/apps/balena-etcher-electron.png /home/pi/etcher/assets/iconset/32x32.png=/usr/share/icons/hicolor/32x32/apps/balena-etcher-electron.png /home/pi/etcher/assets/iconset/48x48.png=/usr/share/icons/hicolor/48x48/apps/balena-etcher-electron.png /home/pi/etcher/assets/iconset/512x512.png=/usr/share/icons/hicolor/512x512/apps/balena-etcher-electron.png /tmp/temp-dir-mygF7X/2-balenaEtcher.desktop=/usr/share/applications/balena-etcher-electron.desktop
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/home/pi/.cache/electron-builder/fpm/fpm-1.9.2-2.3.1-linux-x86_64/lib/ruby/bin/ruby: line 6: /home/pi/.cache/electron-builder/fpm/fpm-1.9.2-2.3.1-linux-x86_64/lib/ruby/bin.real/ruby: cannot execute binary file: Exec format error
/home/pi/.cache/electron-builder/fpm/fpm-1.9.2-2.3.1-linux-x86_64/lib/ruby/bin/ruby: line 6: /home/pi/.cache/electron-builder/fpm/fpm-1.9.2-2.3.1-linux-x86_64/lib/ruby/bin.real/ruby: Success

/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/home/pi/.cache/electron-builder/fpm/fpm-1.9.2-2.3.1-linux-x86_64/lib/ruby/bin/ruby: line 6: /home/pi/.cache/electron-builder/fpm/fpm-1.9.2-2.3.1-linux-x86_64/lib/ruby/bin.real/ruby: cannot execute binary file: Exec format error
/home/pi/.cache/electron-builder/fpm/fpm-1.9.2-2.3.1-linux-x86_64/lib/ruby/bin/ruby: line 6: /home/pi/.cache/electron-builder/fpm/fpm-1.9.2-2.3.1-linux-x86_64/lib/ruby/bin.real/ruby: Success

    at /home/pi/etcher/node_modules/builder-util/src/util.ts:116:16
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
From previous event:
    at exec (/home/pi/etcher/node_modules/builder-util/src/util.ts:84:3)
    at /home/pi/etcher/node_modules/electron-builder/src/targets/fpm.ts:216:11
    at Generator.next (<anonymous>)
From previous event:
    at FpmTarget.build (/home/pi/etcher/node_modules/electron-builder/out/targets/fpm.js:268:11)
    at default.each.it (/home/pi/etcher/node_modules/electron-builder/src/platformPackager.ts:121:87)
From previous event:
    at taskManager.addTask.default.map.then (/home/pi/etcher/node_modules/electron-builder/src/platformPackager.ts:121:35)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/home/pi/etcher/node_modules/electron-builder/src/platformPackager.ts:121:8)
    at /home/pi/etcher/node_modules/electron-builder/src/platformPackager.ts:116:10
From previous event:
    at LinuxPackager.pack (/home/pi/etcher/node_modules/electron-builder/out/platformPackager.js:190:11)
    at /home/pi/etcher/node_modules/electron-builder/src/packager.ts:260:24
From previous event:
    at Packager.doBuild (/home/pi/etcher/node_modules/electron-builder/out/packager.js:332:11)
    at /home/pi/etcher/node_modules/electron-builder/src/packager.ts:186:52
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Packager.build (/home/pi/etcher/node_modules/electron-builder/out/packager.js:261:11)
    at /home/pi/etcher/node_modules/electron-builder/src/builder.ts:283:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/home/pi/etcher/node_modules/electron-builder/out/builder.js:63:21)
    at then (/home/pi/etcher/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Object.args [as handler] (/home/pi/etcher/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at Object.runCommand (/home/pi/etcher/node_modules/electron-builder/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/home/pi/etcher/node_modules/electron-builder/node_modules/yargs/yargs.js:1041:24)
    at Object.get [as argv] (/home/pi/etcher/node_modules/electron-builder/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/home/pi/etcher/node_modules/electron-builder/src/cli/cli.ts:43:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
Makefile:113: fallo en las instrucciones para el objetivo 'electron-build'
make: *** [electron-build] Error 255

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).

**Comment by mkurz** [comment]
This is a problem in `electron-builder`.
If someone wants to make fpm in `electron-builder` work for arm64/aarch64 I wrote a guide how to do so here: https://github.com/signalapp/Signal-Desktop/issues/6063#issuecomment-1307001166
Feel free to pick up that work, I don't have time to do so.
