### ISSUE TITLE
anti-virus software found Trojan horse "Win32/Trojan.541"

### ISSUE THREAD

**Issue by whaodu** [electron/electron#15986]
I use electron to built exe file, anti-virus software found Trojan horse "Win32/Trojan.541".how to solve?!

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
