### ISSUE TITLE
Webview long wait (ttfb) and download time

### ISSUE THREAD

**Issue by BrayanIribe** [electron/electron#15983]
* Output of `node_modules/.bin/electron --version`: v3.0.10.
* Operating System (Platform and Version): Windows 10 Pro x64.

**Expected Behavior**

Same Wait (TTFB) and Download as Chrome or Firefox, this is the network tab in Chrome

![image](https://user-images.githubusercontent.com/520683/49689913-11a53400-faee-11e8-97fb-3c0054b698ba.png)

**Actual behavior**

When using the webview, the Wait (TTFB) increases ~200ms more, same with Download time, even if the hosts file is empty and the application url is in localhost.

This is the network tab of the webview of Electron App

![image](https://user-images.githubusercontent.com/520683/49689941-719bda80-faee-11e8-98c3-9124ba724f0a.png)

**To Reproduce**

Just use the webview. This problem occurs with Web URLs or in localhost.
When you use Web URLs the TTFB increases ~50ms - 150ms, same with Download.
But, when you use localhost app, the TTFB increases ~200ms, same with Download.

I've a fork of the electron-quick-start with the [example](https://github.com/BrayanIribe/electron-webview-lag)

**Additional Information**
I've disabled all network adapters, used the workaround of `--no-proxy-server` and `auto-detect=false`, my hosts file is empty and I'm using Google DNS (8.8.8.8).

This problem affects in general, with all requests, even XHR.

**Edit:** I've created a blank file (test.php) in the app, with only a Reload button. this is the code that I'm using:

`<button onclick="window.location.reload();">Reload</button>`

The results are the same, Chrome is more faster than Electron.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
