### ISSUE TITLE
[macOS] click the cancel button to close the `openDialog` make the application hangs

### ISSUE THREAD

**Issue by tommyZZM** [electron/electron#15988]
* Output of `node_modules/.bin/electron --version`: v3.0.10
* Operating System (Platform and Version): macOS Mojave 10.14
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 

**Expected Behavior**
click the cancel button to close the `openDialog` won't make the application hangs.

**Actual behavior**
window freeze after click the cancel button to close the `openDialog`. but there will be no hangs if choose some file. And some times, no hangs would happen but log error(see below) in the terminal after `dialog.showOpenDialog`.

```
objc[88059]: Class FIFinderSyncExtensionHost is implemented in both \
/System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9ffcf1d0) and \
/System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaboration \
FileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride \
(0x11815bdc8). One of the two will be used. Which one is undefined.
```

**To Reproduce**
most simple code to reproduce
```javascript
Menu.buildFromTemplate([
    {
      label: 'Test',
      submenu: [
        {
          // application hangs if cancel the window
          label: 'Open Dialog and cancel it',
          click() {
            dialog.showOpenDialog(
              mainWindow,
              { properties: ['openFile'], filters:[{ name: 'All Files', extensions: ['*'] }] },
              function (filePaths, bookmarks) {
                console.log("you should cancel the dialog instead of select a file", filePaths, bookmarks);
              }
            );
          }
        },
      ]
    }
  ]);
```
**Screenshots**

**Additional Information**

**Comment by codebytere** [comment]
This is no longer present on latest supported versions of Electron.
