### ISSUE TITLE
Can Electron support Camera Access on MacOS Majave?

### ISSUE THREAD

**Issue by andrewleo** [electron/electron#15985]
Electron version: 2.0.7
MacOS: Mojave 10.14.1

### Description: 
I use ios-minicap,which will need the Access to Camera on MacOS Mojave(10.14.1),  but even though I accept the access to Camera on "Security and Privacy --- Camera", my application can not use the Camera.
I saw this commit: [add media access apis for mojave](https://github.com/electron/electron/pull/15948/commits/1d615b6740650ed871e523aa4436877171cd1c37), seems Camera Privacy can not be supported now?

**Comment by andrewleo** [comment]
May someone help me ? Much thanks!!

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).

**Comment by nornagon** [comment]
You'll need to upgrade to Electron 4, see https://github.com/electron/electron/pull/15948.

It's possible you could find or write a custom npm module to achieve the same effect.

**Comment by andrewleo** [comment]
Much thanks! 
I will have a try. BTW, When will Electron 4  release?

**Comment by nornagon** [comment]
When it's ready :) hopefully soon!

**Comment by andrewleo** [comment]
Greate! I am looking forward to it.

**Comment by gch1p** [comment]
I just wrote a native nodejs addon that can be used with older versions of electron: https://github.com/gch1p/mojave-permissions

**Comment by andrewleo** [comment]
Much thanks!
We will try this addon as soon as possible.
