### ISSUE TITLE
webview.executeJavaScript() not working.

### ISSUE THREAD

**Issue by updatesvc** [electron/electron#15990]
* Output of `node_modules/.bin/electron --version`:
v3.0.10
* Operating System (Platform and Version):
Windows 10 64bit

* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):
v2.0.6

**Expected Behavior**
Run JavaScript  (specifically Dom manipulation) code in the webview.
using 
```
webview.loadURL('https://unixpapa.com/js/testmouse.html")
webview.executeJavaScript('document.querySelector("body > table > tbody > tr > td:nth-child(1) > a:nth-child(1)").click()');
```
The  above code should show a click event.

**Actual behavior**
Does not do any DOM manipulation through execution scripts.
Unless you open the webview's console and type anything then press enter. After that the **.executeJavaScript** seems to work,

**To Reproduce**
On version 3.0.10
Create a webview and load the following url
`webview.loadURL('https://unixpapa.com/js/testmouse.html")`

after the page loads run this command
`webview.executeJavaScript('document.querySelector("body > table > tbody > tr > td:nth-child(1) > a:nth-child(1)").click()');`

it should show click events but it doesn't
then 
`webview.openDevTools()`
type anything then press enter. After that the **.executeJavaScript** seems to work,

**Comment by BrayanIribe** [comment]
This isn't a bug, unless you are using the dom-ready event of the webview. The function executeJavascript() will not work if the dom isn't ready (because is not ready). Please see webview events in the official documentation for further details.

**Comment by codebytere** [comment]
The above explanation is correct.
