### ISSUE TITLE
How to bring a window to the front of the screen without "switching" apps

### ISSUE THREAD

**Issue by outdoteth** [electron/electron#16007]
**Is your feature request related to a problem? Please describe.**
When I have chrome on full screen and do "window.show()" it switches the screen to the desktop with the app.

**Describe the solution you'd like**
It would be better if there was a feature which allowed me to bring the window to jut sit in front of the Chrome app while its on full screen rather than "switch" back to the desktop.

**Additional context**
here is an example;
<img width="1308" alt="screenshot 2018-12-10 at 08 44 36" src="https://user-images.githubusercontent.com/37438950/49770278-a456f600-fcdb-11e8-8274-aecf30f914bd.png">

**Comment by dbradleyfl** [comment]
[win.showInactive()](https://electronjs.org/docs/api/browser-window#winshowInactive)

**Comment by lurein** [comment]
I found a solution that seems to work for this! So this is assuming you've already figured out how to show a window above full screen apps in general. The issue I had with that is that when you try to bring a new window into view, it takes you out of fullscreen, even if that window is configured to show above fullscreen apps.

To deal with this the solution was simple:
```
mainWindow.hide()
mainWindow.show()

setTimeout(() => displayPopupWindow(data), 300)
```

In this case, your main window (which can be invisible) is given focus while still having the fullscreen app open, then opening the popup window *will not* close the fullscreen app.

**Comment by dhrn** [comment]
this one worked for me but it is for windows os

https://stackoverflow.com/questions/39421074/setting-focus-to-a-windows-application-from-node-js
