### ISSUE TITLE
An app crashes when `contentTracing.stopRecording` is called with an empty string as its first argument

### ISSUE THREAD

**Issue by ZacWalk** [electron/electron#16019]
* Electron 3 - all versions
* Windows 10
* Works in Electron 2 - all versions

**Expected Behavior**
ContentTracing example code from the Electron documentation should not crash.

**Actual behavior**
ContentTracing api crashes after startRecording is called. It looks like some issue with the callback.

```javascript
const { app, contentTracing } = require('electron')

app.on('ready', () => {
  const options = {
    categoryFilter: '*',
    traceOptions: 'record-until-full,enable-sampling'
  }

  contentTracing.startRecording(options, () => {
    console.log('Tracing started')

    setTimeout(() => {
      // *** Following line crashes ***
      contentTracing.stopRecording('', (path) => {
        console.log('Tracing data recorded to ' + path)
      })
    }, 5000)
  })
})
```

**Comment by ZacWalk** [comment]
This is the stack trace from the crash I see:

- electron.exe![thunk]:crash_reporter::CrashReporter::`vcall'{8,{flat}}' }'()	C++
- [Inline Frame] electron.exe!base::RepeatingCallback<bool __cdecl(base::trace_event::TraceConfig const &,base::RepeatingCallback<void __cdecl(void)> const &)>::Run(const base::trace_event::TraceConfig &) Line 124	C++
- [Inline Frame] electron.exe!mate::internal::Invoker<mate::internal::IndicesHolder<0,1>,base::trace_event::TraceConfig const &,base::RepeatingCallback<void __cdecl(void)> const &>::DispatchToCallback(base::RepeatingCallback<bool __cdecl(base::trace_event::TraceConfig const &,base::RepeatingCallback<void __cdecl(void)> const &)> callback) Line 196	C++
- electron.exe!mate::internal::Dispatcher<bool __cdecl(base::trace_event::TraceConfig const & __ptr64,base::RepeatingCallback<void __cdecl(void)> const & __ptr64)>::DispatchToCallback(const v8::FunctionCallbackInfo<v8::Value> & info) Line 239	C++
- node.dll!v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo * handler) Line 30	C++
- node.dll!v8::internal::`anonymous namespace'::HandleApiCallHelper<0>(v8::internal::Isolate * isolate, v8::internal::Handle<v8::internal::HeapObject> new_target, v8::internal::Handle<v8::internal::HeapObject> fun_data, v8::internal::Handle<v8::internal::FunctionTemplateInfo> receiver, v8::internal::Handle<v8::internal::Object> args, v8::internal::BuiltinArguments) Line 110	C++
- node.dll!v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments args, v8::internal::Isolate * isolate) Line 138	C++
- node.dll!v8::internal::Builtin_HandleApiCall(int args_length, v8::internal::Object * * args_object, v8::internal::Isolate * isolate) Line 126	C++

**Comment by alexeykuzmin** [comment]
Related to #13914.

**Comment by alexeykuzmin** [comment]
More stack traces: 
 - [linux](https://circleci.com/gh/electron/electron/106991)
 - [mac](https://github.visualstudio.com/electron/_build/results?buildId=25355)
 - [windows](https://windows-ci.electronjs.org/project/AppVeyor/electron-i8wjp/build/1.0.3901)

**Comment by nitsakh** [comment]
This does not seem to happen on electron 5.0.0-beta.2.
Please reopen the issue if you still see the issue.

**Comment by codebytere** [comment]
This is still happening on latest master @nitsakh

**Comment by nornagon** [comment]
Would be great to add a test (... and some documentation) for this!
