### ISSUE TITLE
BrowserWindow.webContents setZoomFactor and setZoomLevel carry over to other BrowserWindow instances showing URLs with the same domain

### ISSUE THREAD

**Issue by brettzook** [electron/electron#16018]
* Output of `node_modules/.bin/electron --version`: v3.0.11
* Operating System (Platform and Version):  Windows 10, Linux (raspbian)
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): N/A, problem also happened in 1.7.16 and 1.8.8

**Expected Behavior**
Separate instances of BrowserWindow will have independent zoomLevel or zoomFactor settings, even if they are loaded with URLs that have the same base domain

**Actual behavior**
If multiple BrowserWindow instances are loaded with different URLs that have the same domain, then calling win.setZoomLevel() on one of them causes the zoomLevel to be changed for all of them. Same behavior occurs with webContents.setZoomFactor().

If the URLs have different domains, the behavior doesn't happen (i.e. setZoomLevel() only affects the window it was called from).

**To Reproduce**
I've forked the electron-quick-start repo and made changes on [this branch](https://github.com/brettzook/electron-quick-start/tree/demo/ZoomIssue).

After cloning and navigating to the repo root, all that should be needed to run it is
```sh
$ npm install
$ npm start
```

Expected sequence of events when running the app:

1. A browser window showing the Chicago craiglist page will open, with zoomLevel 0.
2. 5 seconds later, a second browser window showing the Antiques section of Chicago craiglist page will open on top of the first, also with zoomLevel 0.
3. 3 seconds after that, the zoomLevel for the first window is set to 5. You'll see it enlarge in the background.
4. Almost immediately, you'll also see the Antiques window enlarge. This is the problem; expectation is that each BrowserWindow maintains an independent zoomLevel.

**NOTE** that the issue doesn't occur when using a URL other than Craigslist in the second window (such as https://google.com). My demo repo includes a couple lines that can be modified to demonstrate that as well.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
