### ISSUE TITLE
Does electon support Mac OS before Sierra

### ISSUE THREAD

**Issue by tzvetelin-vassilev** [electron/electron#16016]
Hi there,

this is just a question. Under El Capitan app is started but rendered content is not usable. I can provide and screenshot. Used electron is 3.0.10.

In supprorted platforms I found this:
Only 64bit binaries are provided for macOS, and the minimum macOS version supported is macOS 10.10 (Yosemite).

Is it still actual?

**Comment by nornagon** [comment]
Electron supports what Chrome supports, which for 3.0.10 = Chromium 66.0.3359.181 is macOS 10.9 (see https://chromium.googlesource.com/chromium/src/+/66.0.3359.181/build/config/mac/mac_sdk.gni#12). Also duplicated here: https://github.com/electron/electron/blob/3-0-x/atom/browser/resources/mac/Info.plist#L26
