### ISSUE TITLE
macOS: Window size is not respected

### ISSUE THREAD

**Issue by bpasero** [electron/electron#16015]
* Output of `node_modules/.bin/electron --version`: 3.0.11
* Operating System (Platform and Version): macOS 10.14.2
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2.0.x

**Expected Behavior**
The size of a window is applied.

**Actual behavior**
The size of the window is not applied.

**To Reproduce**
* Use a fiddle and simply configure the window like this: `new BrowserWindow({x: 0, y: 23, width: 1680, height: 1328})`
* 🐛 the window opens ~20px smaller than that (both in width and height)

This does not reproduce with 2.0.x
This does not reproduce when a `titlebarStyle:hidden`.
This does not reproduce with `useContentSize: true`

**Comment by bpasero** [comment]
This seems to be working OK when using Electron 4.

**Comment by bpasero** [comment]
I can reproduce actually without external monitor on macOS MBP.

**Comment by zcbenz** [comment]
I can reproduce on 3.x.

**Comment by zcbenz** [comment]
Closed with #16516.

**Comment by bpasero** [comment]
@zcbenz thanks!
