### ISSUE TITLE
API access to Mac "Show All Windows" action

### ISSUE THREAD

**Issue by dbradleyfl** [electron/electron#16025]
**Is your feature request related to a problem? Please describe.**
Ability to trigger the "Show All Windows" Mac functionality from Electron 

**Describe the solution you'd like**
BrowserWindow.showAllWindows() should do the same thing as right clicking the app icon in the dock and clicking "Show All Windows"

**Describe alternatives you've considered**
The alternative would be creating a custom interface for selecting a window to bring into focus, but it'd be rather difficult and time intensive to mimic the Mac functionality.

**Comment by codebytere** [comment]
@dbradleyfl Apple doesn't seem to expose a method to trigger this; if something changes i can look into it though!
