### ISSUE TITLE
page-title-updated not fired when document.title is changed during history navigation

### ISSUE THREAD

**Issue by alexstrat** [electron/electron#16032]
* Output of `node_modules/.bin/electron --version`: v3.0.10, v3.0.5
* Operating System (Platform and Version): MacOS 10.14.1
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): ❓

**Expected Behavior**
When `document.title` changes,  `page-title-updated` should be fired.

**Actual behavior**
I discovered a case where `document.title` is updated but `page-title-updated` is not fired.

**To Reproduce**
_⚠️I discovered the issue while working on [Notion.so](https://notion.so) (a document writing and organization software) and, I was not able to isolate the reason independently of Notion. Thus I can only provide reproduction step using Notion._

- Use https://github.com/alexstrat/electron-quick-start/tree/reproduction/page-title-updated-not-fired and `npm start`
- Navigate in the Notion workspace
- in the console, do `window.history.back()`
- => `document.title` has changed but `page-title-updated` was not fired

_see this recording: http://recordit.co/4jABBu2D1i_

**Additional Information**
- I tried to setup a repoduction case by changing the `document.title` on `popstate` event but was not able to reproduce. So, I doubt the history navigation is the root cause of the issue.
- Notion changes the document title using `document.title = '..'`
- In Chrome version 71.0.3578.80 the tab title is properly updated

**Comment by codebytere** [comment]
As we're only sending security fixes back to the 3x line at this juncture and this isn't reproduceable in newer versions of Electron, i'm going to go ahead and close this one out.
