### ISSUE TITLE
API calls is blocking

### ISSUE THREAD

**Issue by ArunaJithesh** [electron/electron#16039]
i am writing a electron wrapper over a c# dll having web api calls.We are writting this using native addon method.By creating addon file and refering that file to javascript library 

issue
------
For testing we create a electron window store app and calls to c# dll is working fine and we get the result in javascrpt file.But when we call functions having api calls(Post methods),its not working.
And one more thing,the same code is working in india(my team is there),i am working from USA.

Can please help me to sort out this issue

Following are steps we done to create windows app

1.      Prerequisites

        Node with version higher than 8.x.x

2.      Unzip ElectronApp. (ex: C:\Electron\ElectronApp)

3.      Copy the branch dll - branch_debug_0.0.6.dll to the location where node is installed (ex: C:\Program Files\nodejs)

4.      Change directory to addon in ElectronApp  and give command so as to rebuild the addon with electron-gyp.

        HOME=~/.electron-gyp node-gyp rebuild --target=3.0.10 --arch=x64 --dist-url=https://atom.io/download/electron

5.      For Packaging, go inside the project root folder,

a.      npm install -g electron-packager

b.      electron-packager . <name of electronApp as in package.json> --overwrite --platform=win32

c.      Copy the branch dll - branch_debug_0.0.6.dll to the newly created folder which contains the exe.

6.      For converting the app into a Windows Store App,

a.      npm install -g electron-windows-store

b.      Then, configure your PowerShell: Set-ExecutionPolicy -ExecutionPolicy RemoteSigned

c.      electron-windows-store --input-directory <path to the electron app package>  --output-directory <Any location> --package-version 1.0.0.0 --package-name <name of electronApp as in package.json>

        Note: When publisher name is asked, give something like CN=publisherName .  U

        Reference : https://github.com/felixrieseberg/electron-windows-store

**Comment by miniak** [comment]
Please use https://discuss.atom.io/c/electron, this does not seem to be an issue with Electron itself
