### ISSUE TITLE
Dialog docs don't match latest code

### ISSUE THREAD

**Issue by chmac** [electron/electron#16034]
https://github.com/electron/electron/blob/master/docs/api/dialog.md

Line 35:

  * `properties` String[] (optional) - Contains which features the dialog should

But this page shows just `String` instead of `String[]`:

https://electronjs.org/docs/api/dialog

I'm assuming those docs are built from that file, that might be wrong. I tried checking the history for the file and it looks like it's been `String[]` for some time.

**Comment by codebytere** [comment]
This should be opened as an issue on the website [itself](https://github.com/electron/electronjs.org).
