### ISSUE TITLE
Isolated Security Origin for App

### ISSUE THREAD

**Issue by dbkr** [electron/electron#16030]
**Is your feature request related to a problem? Please describe.**
Our app currently loads its page from a file:// URI. The problem with this is that pages from file:// URIs have access to any other file in the file system. Our app doesn't need this so I'd like to disable this so that if there were an XSS vulnerability, malicious code would not be able to access the local file system.

If we loaded our resources from an HTTPS URI, the page would be restricted to the origin it was loaded from and not have file system access, so this would achieve this, but for obvious reasons we don't want to hit the network to load the apps resources.

Is there already a recommended way of achieving this?

**Describe the solution you'd like**
Load a page in a WebView with a specific origin such that:
 * The page can load other resources from the same directory or subdirectories
 * The page does not have access to the local filesystem via file:// URIs
 * Resources come from disk, installed when the electron app is installed, rather than having to load resources over the network.

A potential solution would be something like setting up a fake, internal URL scheme that will serve the contents of an asar bundle, so the page can be loaded from this.

**Describe alternatives you've considered**
I've also considered somehow setting the CSP of the page to 'sandbox' to give it a unique origin, but this means the app can't load other files it needs (that would otherwise be loaded from the same origin).

**Additional context**
https://github.com/electron/electron/issues/14350 is a similar problem, although more specifically asking just to execute javascript.

**Comment by dbkr** [comment]
It looks like registering a custom protocol (https://electronjs.org/docs/api/protocol) might do the trick, except that I still can't set a CSP for the page other than as a meta tag in the HTML.

**Comment by MarshallOfSound** [comment]
> except that I still can't set a CSP for the page other than as a meta tag in the HTML.

You can set it through a header with the `webRequest` module

**Comment by MarshallOfSound** [comment]
Using a custom protocol is the solution you're looking for here

**Comment by dbkr** [comment]
Thanks, although I was trying this and was not getting callbacks for the custom protocol handler using `webRequest` (I was successfully getting callbacks for http/https requests the page was making). Should requests to custom protocols appear as callbacks in `webRequest`?

**Comment by dbkr** [comment]
Actually, I get `onBeforeRequest` and `onCompleted` for requests to the custom protocol but I would need `onHeadersReceived` to inject custom headers?

**Comment by dbkr** [comment]
Looking into this a little, it looks like this is because the HTTP equivalent makes an explicit call to the `network_delegate` to trigger `onHeadersReceived` (https://chromium.googlesource.com/chromium/src/+/master/net/url_request/url_request_http_job.cc#891) which `URLRequestAsarJob` just doesn't do, so it looks like the calls to the network_delegate would need adding to `URLRequestAsarJob`.

Irrespective or whether `URLRequestAsarJob` should make these callbacks, I'm thinking a better solution to this specific problem would be to allow the protocol handler to give response headers. Wdyt?
