### ISSUE TITLE
[Desktop Capture] Why use GetUserMedia with chromeMediaSource : 'desktop', focus on the window application?

### ISSUE THREAD

**Issue by jbeurel** [electron/electron#16031]
* Output of `node_modules/.bin/electron --version`: v3.0.2
* Operating System (Platform and Version): macOS Mojave

**Expected Behavior**
I use getUserMedia() with `chromeMediaSource: 'desktop'` and my Electron App stay foreground.

**Actual behavior**
I use getUserMedia() and the window source of the stream foreground over my Electron App.

```javascript
navigator.mediaDevices
      .getUserMedia({
        audio: false,
        video: {
          mandatory: {
            chromeMediaSource: 'desktop',
            chromeMediaSourceId: source.id,
            minWidth: 1920,
            maxWidth: 1920,
            minHeight: 1080,
            maxHeight: 1080,
            maxFrameRate: 25,
          },
        },
      })
      .then()
      .catch();
```

**To Reproduce**
Git clone this example and click to "Enable Capture"

https://github.com/hokein/electron-sample-apps/blob/master/desktop-capture/app.js#L71

**Screenshots**
![capture](https://user-images.githubusercontent.com/1665948/49876180-171eb900-fe23-11e8-9710-a147f833fecc.gif)

**Comment by aabuhijleh** [comment]
This issue is also on Windows as well. Electron v3.0.4

**Comment by jbeurel** [comment]
I upgraded my Electron to 4.1.3 and I still have the problem. Any ideas?

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by Darkstar87d** [comment]
Hey

**Comment by Benevole** [comment]
thank you
