### ISSUE TITLE
[Feature] Hide url bar (bottom)

### ISSUE THREAD

**Issue by Domvel** [electron/electron#16044]
Is there already an option to hide the url bar (bottom)?
![screen](https://user-images.githubusercontent.com/35452565/49930401-cfe90480-fec4-11e8-886b-2d06cbb29de6.gif)

**Comment by devyboy** [comment]
This is apparently caused by the href of your link, so you would need to remove the href and find a different way to route the user

**Comment by Domvel** [comment]
The URL bar is not electron's feature.
