### ISSUE TITLE
Remove QTKit dependency in Electron before OSX 10.15

### ISSUE THREAD

**Issue by renzil** [electron/electron#16045]
**Is your feature request related to a problem? Please describe.**
I work for a commercial software company, and we are building an OSX app using Electron. QuickTime framework support, and hence QTKit, will be dropped from Mac OSX 10.15 onwards (around September 2019). The Electron version we use (^2.0.0) has a dependency on QTKit framework, and hence will not launch on the new OSX. This appears to have been addressed for Mac App Store builds of Electron, where any app depending on QTKit is rejected. Has this been addressed with a newer version of Electron for apps not distributed via the App Store? If not, how can I get it added to the Electron backlog?

**Describe the solution you'd like**
A release of Electron that drops QTKit (and any other 32-bit) dependencies at the earliest, where the target platform is an independetly distributed OSX app and not a Mac App Store app.

**Describe alternatives you've considered**
None at the moment.

**Additional context**
None.

**Comment by nornagon** [comment]
Does this also affect Electron 3 or 4?

**Comment by vijayghaghre** [comment]
@nornagon I am also facing the same issue. My use case is similar as above, we are not planning to distribute our app via the App Store. I have tried latest version 4.0.0-nightly.20181010 and 4.0.0-beta.11 as well but it still has dependency on QTKit.

**Comment by nornagon** [comment]
It looks like QTKit is a dependency of Quartz, which is currently required in Electron for [Quick Look](https://electronjs.org/docs/all#winpreviewfilepath-displayname-macos) support via [QLPreviewPanel](https://developer.apple.com/documentation/quartz/qlpreviewpanel).

```
$ otool -L /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
[...]
/System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuartzComposer.framework/Versions/A/QuartzComposer (compatibility version 1.0.0, current version 168.0.0)
$ otool -L /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuartzComposer.framework/Versions/A/QuartzComposer
[...]
/System/Library/Frameworks/QTKit.framework/Versions/A/QTKit (compatibility version 1.0.0, current version 1.0.0)
```

I think we need to wait for Apple to release a version of Quartz that doesn't depend on QTKit.

**Comment by stephendwolff** [comment]
Just had a mac app store fail with the following issue: "ITMS-90300: Deprecated API Usage - Apple will stop accepting submissions of apps that use QuickTime or QTKit APIs .", so this has become live. 

Does anyone know how can i build my app to not have these dependencies on macos?

**Comment by belloyang** [comment]
I'm facing the same issue too. my electron dependency is `electron@^7.1.1`.  Is there any solution available for this issue?

**Comment by miniak** [comment]
Please create a new issue if this is still a problem with currently supported Electron versions.
