### ISSUE TITLE
 electron-angular app  in production don't play video mp4 in assets folder

### ISSUE THREAD

**Issue by DanieleRamacci** [electron/electron#16050]
* Output of `node_modules/.bin/electron --version`: 5.6.0
* Operating System (Platform and Version): windows 8

**Expected Behavior**
I wanted to create a simple angular app integrated with electron to loop a video mp4 in the background, the video is inside the assets folder

**Actual behavior**
I made a simple application angular that has a module to view a looped video in the background, my problem is that when I debug in the browser I see the video start and start again, even when I start electron in the window I see the video start and start again using `<ng build --prod && `electron.>`,` but when I make the package for distribution using the comdando `electron-packager --platform = win32` we only see a still image of the video without it starting to video is in assets folder

**main .js**
```
const { app, BrowserWindow } = require('electron')

let win;

function createWindow () {
  // Create the browser window.
  win = new BrowserWindow({
    width: 600, 
    height: 600,
    backgroundColor: '#ffffff',
    icon: `file://${__dirname}/dist/lasalute/assets/logo.png`
  })


  win.loadURL(`file://${__dirname}/dist/lasalute/index.html`)

  //// uncomment below to open the DevTools.
  // win.webContents.openDevTools()

  // Event when the window is closed.
  win.on('closed', function () {
    win = null
  })
}

// Create window on electron intialization
app.on('ready', createWindow)

// Quit when all windows are closed.
app.on('window-all-closed', function () {

  // On macOS specific close process
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', function () {
  // macOS specific close process
  if (win === null) {
    createWindow()
  }
})
```
**slider.component.html**
```
<div class="container">
  <div class="col-md 12">
         
          <video  autoplay  preload="metadata" loop   id="bgvid"   >
                  <!-- MP4 must be first for iPad! -->
                  **<source src="\assets\video\Superb_sunset.mp4"** type="video/mp4" /><!-- Safari / iOS video    -->
                  
                  
              </video>
              </div>
</div>
```
**folder organizzation **
```
-dist

  --lasalute(project name )

   --- assets

   --- index.html

   ---main

   ---style.css

   ---other

-lasalute_win32(in this folder there is a .exe )

-src

 --app

     ---slider.component.html

     ---slider.component.css

     ---slider.component.ts

 --assets

     ---img

     ---video

        ----superb_sunset.mp4

 --index.html

```

**Screenshots**

**Additional Information**
initially I had put the paths so `"/assets/video/Superb_sunset.mp4` but I had problems then I entered
`\ assets \ video \ Superb_sunset.mp4` as local path, I tried to write `src = "file: // absolute_path"`

**but still remains a fixed image in production**

**help me thanks**

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
