### ISSUE TITLE
app.requestSingleInstanceLock doesn't work if the main window launches second

### ISSUE THREAD

**Issue by kaansoral** [electron/electron#16057]
* Output of `node_modules/.bin/electron --version`: 3.0.11
* Operating System (Platform and Version): Macos 10.14.1

**Expected Behavior**
`app.requestSingleInstanceLock` should work even if you show one BrowserWindow (as a loader) - then destroy it and launch a new, main BrowserWindow

**Actual behavior**
`app.requestSingleInstanceLock` works as expected for the first launched BrowserWindow - but if you launch a secondary BrowserWindow, and destroy the first one, re-initiating the app launches a new instance

**To Reproduce**
https://stackoverflow.com/a/42294262/914546
Implement a "loader" BrowserWindow as in this example, it breaks the intended `app.requestSingleInstanceLock` functionality

**Solution - Without a Fix/Change**
Just instantiate the loader/temporary BrowserWindow, after the main BrowserWindow is created, re-structure events/operations accordingly

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR.
