### ISSUE TITLE
Instrumentation breakpoint "scriptFirstStatement" doesn't work correctly in Electron 3

### ISSUE THREAD

**Issue by roblourens** [electron/electron#16074]
Electron 3.0.10

* Operating System (Platform and Version): Windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2.0.12

- Download VS Code Insiders
- Open the developer tools
- Turn on the event listener breakpoint to pause on "Script First Statement":
![image](https://user-images.githubusercontent.com/323878/50023567-77813800-ff94-11e8-9d8a-58adbb3b7ce4.png)
- ctrl+shift+p to open the command palette. Execute the Reload Window command
- Devtools pauses on the Script First Statement bp
- Press continue
- Execution does not actually continue (but the 'continue' button has changed back to 'pause')
![image](https://user-images.githubusercontent.com/323878/50023640-aac3c700-ff94-11e8-8a4c-e036c8551539.png)

**Expected behavior**
When clicking 'continue', execution should actually continue and the program should reload.

I can see that the `Debugger.resume` message is being sent to Electron, but the runtime does not actually resume.

Let me know how I can help debug it...

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by roblourens** [comment]
This works fine in Electron 6
