### ISSUE TITLE
Custom copy accelerator doesn't trigger role on v4-beta.9

### ISSUE THREAD

**Issue by juancampa** [electron/electron#16088]
* Version: `v4.0.0-beta.9`
* OS: `Linux ix 4.19.4-arch1-1-ARCH`
* Last known working version: `v3.0.12`

**Expected Behavior**

The selected text is copied to the clipboard

**Actual behavior**

The empty string is copied to the clipboard

**To Reproduce**

Run these steps:
```sh
$ git clone https://github.com/juancampa/electron-bug-accelerator-not-firing.git -b master
$ npm install
$ npm start
```

This commit contains the changes made to `electron-quick-start`:

   https://github.com/juancampa/electron-bug-accelerator-not-firing/commit/7477142f84b014085551718e7b859c56a9e687bd

**Comment by nornagon** [comment]
cc @brenca, perhaps this has something to do with the accelerator fixes you've worked on recently?

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
