### ISSUE TITLE
[WINDOWS 10] BrowserWindow.setAppDetails(options) doesn't have an effect

### ISSUE THREAD

**Issue by dbradleyfl** [electron/electron#16087]
* Output of `node_modules/.bin/electron --version`: v3.0.10
* Operating System (Platform and Version): Windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): unknown

**Expected Behavior**
- [Example app repo](https://github.com/dbradleyfl/test-set-app-details-electron) 
- clone down that repo
- install node modules 
- then run `yarn dist` or `npm run dist`
- then open the `exe` in the dist folder
- an example app will open and a BrowserWindow is created
- pin the window to taskbar
- setAppDetails should set the relaunch command to have `arg1` and `arg2`
- close the window
- app should continue running in the background even though the window is closed
- open the window from the pin on the task bar
- the pin should run the relaunch command with args
- the app should detect a second instance and show a dialog box with the args set by window.setAppDetails

**Actual behavior**
On launch from pin the args are not passed by the relaunch command, the window just reopens without any data from the relaunch command.
**To Reproduce**
- [Example app repo](https://github.com/dbradleyfl/test-set-app-details-electron) 

**Screenshots**
![capture](https://user-images.githubusercontent.com/5935459/50047225-2e99b400-0066-11e9-9d84-627b7cab61f5.PNG)

**Additional Information**
None

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
