### ISSUE TITLE
Option to change the default sandbox behaviour of iframe

### ISSUE THREAD

**Issue by circleapps** [electron/electron#16084]
In Electron 2.x, I was able to call YouTube iframe API to create a YouTube player within a webview, then get the instance of player to play, seek or do other playback features.

In Electron 3.x, I found this behaviour changed. I can not access the player within the iframe through its js api from an outside html page (a local html page within my application).

I thought there is a default behaviour change for iframe, so that I'm not able to manipulate the youtube player within its iframe from a local html file (which is referenced by a webview) embedded in my Electron application.

If my assumption is true, is there an option to change it? An option to change the default iframe sandbox settings.

Following is the way I create the YouTube player by its iframe api.

```
      var tag = document.createElement('script');
      tag.src = "https://www.youtube.com/iframe_api";
      var firstScriptTag = document.getElementsByTagName('script')[0];
      firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
```

If the YouTube player created successfully. I will get a callback message from the iframe api, then I will
create a wrapper object to access its methods.

```
function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
          width: '100%',
          height: '100%',
          videoId: videoId,
          host: "https://www.youtube.com",
          playerVars : {
            cc_load_policy: 1,
            controls: 1,
            hl: "en",
            cc_lang_pref: "en",
            showinfo: 0,
            modestbranding: 1,
            enablejsapi: 1,
            autoplay: 1,
            rel: 0
          },
          events: {
            'onReady': onPlayerReady,
            'onStateChange': onPlayerStateChange
          }
        });
      }
```

Until here, everything looks ok. But when I try to play the video, the player js api just does not respond.

```
player.playVideo();  // not working
```

**Comment by miniak** [comment]
@circleapps are you still having this issue with Electron >= 4?

**Comment by miniak** [comment]
This seems more like a bug with `YT.Player` than Electron. Please re-open if you disagree

**Comment by circleapps** [comment]
I agree. I found a workaround to fix it, but I still don't know what was happened exactly.

**Comment by erwinyusrizal** [comment]
@circleapps whats the workaround? I'm having this issue too
