### ISSUE TITLE
[MacOS] Installing Electron globally results in error

### ISSUE THREAD

**Issue by GingkathFox** [electron/electron#16089]
* Output of `node_modules/.bin/electron --version`:  How do i do this? lastest version i have is ^3.0.12.
* Operating System (Platform and Version): MacOS Mojave 10.14.1
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
Electron successfully installed globally

**Actual behavior**
EACCES permission denied, Electron cant make directory `/usr/local/bin/node_modules/electron`
```css
gingkathfox$ sudo npm install electron -g
/usr/local/bin/electron -> /usr/local/lib/node_modules/electron/cli.js

> electron@3.0.12 postinstall /usr/local/lib/node_modules/electron
> node install.js

/usr/local/lib/node_modules/electron/install.js:49
  throw err
  ^

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/electron/.electron'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@3.0.12 postinstall: `node install.js`
npm ERR! Exit status 1
```
**To Reproduce**
Run `sudo npm install electron -g`
**Screenshots**
None needed

**Additional Information**
It seems the install script isnt using `sudo` at this point? i dont really know what else could cause this, and i dont know which file installs globally (if there is one). Unless someone could tell me how to make `npm` use the electron folder in `node_modules`, i need it installed globally.
EDIT: https://github.com/electron/electron/blob/master/npm/package.json seems to have the command that doesnt have `sudo`.

**Comment by GingkathFox** [comment]
Found a way to avoid usind global electron, closing now.

**Comment by Time-coding** [comment]
how to?
