### ISSUE TITLE
[macOS]NSWindowZoomButton is disabled in frameless window since 3.0.0

### ISSUE THREAD

**Issue by Gizeta** [electron/electron#16091]
* Output of `node_modules/.bin/electron --version`: 3.0.11 (since 3.0.0-beta.1)
* Operating System (Platform and Version): macOS Mojave 10.14.2
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2.0.14

**Actual behavior**
I create a frameless window and use `Accessibility Inspector` in `Xcode` to display the information properties of window's `ZoomButton`. I see that `ZoomButton` is disabled since `3.0.0-beta.1`. That breaks some window manager, such as [Magnet](http://magnet.crowdcafe.com/) which may use `Accessibility API`. If I downgrade to `2.0.14`, `Magnet` works well because `ZoomButton` is enabled.

**To Reproduce**
just create a frameless window

**Screenshots**
<img width="1680" alt="2.x" src="https://user-images.githubusercontent.com/1572561/50050527-c962c300-0138-11e9-942b-ce0f6379f0d0.png">
<img width="1680" alt="3.x" src="https://user-images.githubusercontent.com/1572561/50050797-5a896800-0140-11e9-823a-f5abbece2a37.png">

with Magnet's menu
<img width="1280" alt="2018-12-16 2 38 43" src="https://user-images.githubusercontent.com/1572561/50050802-6412d000-0140-11e9-85dd-b071638ca715.png">

**Additional Information**
`ZoomButton` will be enabled if I make the window full screen and restore it. And `Magnet` will works correctly.

**Comment by codebytere** [comment]
This can't currently be worked around, as macOS itself disallows NSViews with `NSWindowStyleMaskFullSizeContentView` from entering full screen. Should something change, we'll return to this and address it.
