### ISSUE TITLE
app.dock.hide() and app.hide() cannot be used together

### ISSUE THREAD

**Issue by cagdas001** [electron/electron#16093]
* Output of `node_modules/.bin/electron --version`: v3.0.8
 
* Operating System (Platform and Version): 

  * macOS High Sierra 10.12 (**no issue**)
  * macOS High Sierra 10.13.6 (**issue exists**)
  * macOS Mojave 10.14.1 (**issue exists**)

**Expected Behavior**
**app.hide()** should properly hide the app even if **app.dock.hide()** is being used.

**Actual behavior**
After hiding the dock icon with **app.dock.hide()**, **app.hide()** cannot hide the app itself. 

**To Reproduce**
You just need to use **app.hide()** after **app.dock.hide().** I prepared a minimal example for you to reproduce the issue.

1. Clone my repo.
```sh
git clone --single-branch -b master https://github.com/cagdas001/electron-quick-start.git
```

2. Go to the root directory of project and install dependencies/modules.
```sh
cd electron-quick-start/
npm install
```

3. Start the electron app.
```sh
npm start
```

4. Click on the **app.dock.hide** button and observe, it will work properly.
5. Click on the **app.hide** button and observe, it won't work.

You can show the app again by pressing CommandOrCtrl + X, if you need.

**P.S.** Reversing the order (calling **app.hide()** first, and then**app.dock.hide()**) will work only once. After showing/unhiding the app again, it won't work.

**Additional Information**

**What is wrong with BrowserWindow.hide?**
**BrowserWindow.hide** function can be used on Windows, the previously active window automatically regains  the focus after hiding the window. But this is not the case on macOS.

**Technical Investigation**

I have investigated this issue and it seems that, calling the **app.dock.hide()** sets **canHide** flag to NO. 

See

https://github.com/electron/electron/blob/master/atom/browser/browser_mac.mm#L326

```cpp
void Browser::DockHide() {
  for (auto* const& window : WindowList::GetWindows())
    [window->GetNativeWindow() setCanHide:NO];

  ProcessSerialNumber psn = {0, kCurrentProcess};
  TransformProcessType(&psn, kProcessTransformToUIElementApplication);
}
```

I guess this is the main reason. Is it necessary to set this flag?

This code wasn't enough for hiding dock icon?
```cpp
TransformProcessType(&psn, kProcessTransformToUIElementApplication);
```

I know, once the app is shown again, the dock icon will be shown automatically. So preventing user from hiding the app, seems a solution to this. I think, instead of this logic, we can listen activation/deactivation events, and if dock.icon needs to be hidden, we can hide again.

Please let me know your thoughts, if someone confirms this, I can work on this and open a PR.

**Comment by cagdas001** [comment]
Thanks for labels. I'd like to leave an update. I just checked the other versions, and it seems the other versions also use the same logic. So this issue should affect all listed versions. (have not tested with them)

* v2.0.x (and earlier)
* v2.1.x
* v3.1.x
* v4.x

https://github.com/electron/electron/blob/2-0-x/atom/browser/browser_mac.mm#L321
https://github.com/electron/electron/blob/2-1-x/atom/browser/browser_mac.mm#L262
https://github.com/electron/electron/blob/3-1-x/atom/browser/browser_mac.mm#L323
https://github.com/electron/electron/blob/4-0-x/atom/browser/browser_mac.mm#L324

**Comment by BickelLukas** [comment]
This is still an issue in version 6.0.4

It is actually a use case for us to simultaneously hide the dock and the application. We have an application that lives as a tray icon and therefore should not have a dock icon. But when you hit a hotkey a window pops up. At that moment we show the dock icon. When the window gets closed again the dock icon should disappear and the last focused window should regain focus so that the user can continue working on what he did before. 

We achieved regaining focus to the last application by using app.hide(). But if we combine it with app.dock.hide(). Only the dock icon gets hidden but the last window doesn't regain focus.

**Comment by jetlej** [comment]
Also looking for this solution!

**Comment by cagdas001** [comment]
During the time of opening this issue, we were decided to go with <b>BrowserWindow.hide</b>. The focus issue (mentioned before, see below) still remains, but it does the main job, hides both of dock icon and app.

> <b>What is wrong with BrowserWindow.hide?</b>
> BrowserWindow.hide function can be used on Windows, the previously active window automatically regains the focus after hiding the window. But this is not the case on macOS.

**Comment by codebytere** [comment]
Unfortunately calling `[window->GetNativeWindow() setCanHide:NO];` is a system-level requirement for dock hiding to work correctly. macOS makes it somewhat hard to control dock-level app behavior in a granular fashion, so we need to hack around it a bit with [TransformProcessType](https://developer.apple.com/documentation/applicationservices/1462420-transformprocesstype?language=objc). If we didn't use that, our only alternative would be to change the activation policy for the app, using [`NSApplicationActivationPolicyProhibited`](https://developer.apple.com/documentation/appkit/nsapplicationactivationpolicy/nsapplicationactivationpolicyprohibited?language=objc) and then flipping it back to `NSApplicationActivationPolicyRegular` when `app.dock.show()` was called. However, the former policy prevents windows from being created or activated while it's in place, so you wouldn't be able to interact with any of the windows until you'd called `app.dock.show()` again. As such we feel the approach we took to be the ultimately preferable one in terms of user experience, and this to not be something we're currently capable of changing.
