### ISSUE TITLE
Large numbers of .org.chromium.Chromium.xxxxxx files created under /tmp

### ISSUE THREAD

**Issue by akashnimare** [electron/electron#16097]
* Output of `node_modules/.bin/electron --version`:  v2.0.9
* Operating System (Platform and Version):  Linux
---
The Zulip Electron app creates large numbers of `.org.chromium.Chromium.xxxxxx` files and directories under `/tmp` , to the point where it can fill up a 1GB `/tmp` partition within a day. The files all seem to be the same size (6.4MB). Deleting the files/directories doesn't appear to have any effect on the app, even if they are removed while it's running.

- **Operating System**:
  - [x] Linux/Ubutnu
- **Clear steps to reproduce the issue**:
No specific steps, just [install](http://zulipchat.com/apps/linux) and use the Zulip Electron app.
Here are the detailed instructions.
https://zulipchat.com/help/desktop-app-install-guide

- **Relevant error messages and/or screenshots**:
An example of some of the files and directories under /tmp:

```
-rwxr-xr-x  1 user users  6.4M Nov 29 13:27  .org.chromium.Chromium.09Sbtp
-rwxr-xr-x  1 user users  6.4M Nov 29 13:49  .org.chromium.Chromium.0JzCtW
drwx------  2 user users    80 Nov 29 13:19  .org.chromium.Chromium.2EVNW6
-rwxr-xr-x  1 user users  6.4M Nov 29 13:53  .org.chromium.Chromium.3yn4zU
-rwxr-xr-x  1 user users  6.4M Nov 29 13:45  .org.chromium.Chromium.4sx4aL
-rwxr-xr-x  1 user users  6.4M Nov 29 13:26  .org.chromium.Chromium.555b7U
-rwxr-xr-x  1 user users  6.4M Nov 29 14:16  .org.chromium.Chromium.5BMprU
-rwxr-xr-x  1 user users  6.4M Nov 29 13:45  .org.chromium.Chromium.5sffWP
drwx------  2 user users    60 Nov 29 14:20  .org.chromium.Chromium.5ThFzW
-rwxr-xr-x  1 user users  6.4M Nov 29 13:53  .org.chromium.Chromium.69o5xJ
-rwxr-xr-x  1 user users  6.4M Nov 29 13:42  .org.chromium.Chromium.6m877C
-rwxr-xr-x  1 user users  6.4M Nov 29 13:30  .org.chromium.Chromium.7Qve23
-rwxr-xr-x  1 user users  6.4M Nov 29 13:53  .org.chromium.Chromium.8vCChR
-rwxr-xr-x  1 user users  6.4M Nov 29 13:40  .org.chromium.Chromium.8VjZ2d
-rwxr-xr-x  1 user users  6.4M Nov 29 13:42  .org.chromium.Chromium.8XsBvr
```

**Comment by nornagon** [comment]
Thanks for the report.

It would be helpful to know:
- Does this also happen in Electron 3.1 or 4.0?
- What distribution & version of Linux are you seeing this issue on?

Additionally, a small repro case would help us enormously.

**Comment by pspiller** [comment]
I'm seeing the issue on Ubuntu 18.04. I haven't been able to determine if particular actions in the Zulip Electron app trigger the creation of these files. If you delete them all, it seems to recreate a few of them (4-6) within a few minutes.

I'll need to let @akashnimare comment on how other versions of Electron affect this behaviour.

**Comment by Turcot-pony** [comment]
I do not have Zulip installed but today found a bunch of these files in my ~/.config/opera folder.  I use Opera v. 53.

The files were of varying sizes and go back months. All were browsing logs with URLs over months of browsing.  URLs fetched using Opera's proxy VPN were  tracked in these files. 

They appear be part of some hidden tracking/history mechanism. Clearing Opera's browser data does not remove them. I will monitor reoccurence of such files. One must assume that Opera's VPN is totally compromised, if one did not already think so.

**Comment by wells** [comment]
I found better luck with chrome over chromium regarding this tmp folder this issue on Ubuntu.

**Comment by akashnimare** [comment]
@nornagon can reproduce the same on v3 as well.

**Comment by logidelic** [comment]
I've seen this with Electron 6 as well, but haven't been able to repro in any obvious way. Could it be related to the process crashing?

**Comment by codebytere** [comment]
Without a way to reproduce this, it's unfortunately impossible for us to move forward or effectively triage this issue. I do see the attached zulip link at the top, but given that it's a fully-featured app it's not clear that this is an Electron-specific issue as opposed to one that could be mitigated by the app itself or by Chromium. As such, i'm going to close this issue, but am happy to re-open it should more information come to light.

**Comment by hhoffstaette** [comment]
@codebytere Please reopen this issue. It can be readily reproduced with the latest Element desktop app on Linux (1.7.1 as of this time), which AFAIK uses the latest Electron SDK. After finding over a GB of undeleted stuff in /tmp I had to write an absurd shell wrapper for the app to env-inject a per-instance unique TMPDIR and then delete it after termination. :disappointed:

**Comment by PF4Public** [comment]
I have a suspicion that this happens to Electron apps, which package native modules into `app.asar` instead of `app.asar.unpacked/node_modules/`, which results in Electron needing to unpack them upon every start. See also vector-im/element-web#17188 that I have filled.

**Comment by vanadis6677** [comment]
have a bunch of them in Opera/linux/Ubuntu 18.04 does mot delete upon exit.
