### ISSUE TITLE
Electron 3.0.x: loading of window script code has become slower

### ISSUE THREAD

**Issue by bpasero** [electron/electron#16099]
* Output of `node_modules/.bin/electron --version`: 3.0.x
* Operating System (Platform and Version): Windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2.0.x

**Expected Behavior**
Script loading is as fast as with previous versions or even faster.

**Actual behavior**
Script loading has become considerably slower. For applications with large scripts to load on startup (like VSCode) this results in a measurable delay on startup.

**To Reproduce**
See https://github.com/electron/electron/issues/16099#issuecomment-450355256

**Comment by bpasero** [comment]
Maybe related: https://v8.dev/blog/improved-code-caching

Would be good to get input from V8 folks if there is something Electron needs to do to get the old performance back or node.js. It looks like the node.js version Electron 3 is bundling does not yet contain the new APIs added for producing cached data: https://nodejs.org/docs/v10.6.0/api/vm.html#vm_script_createcacheddata

**Comment by bpasero** [comment]
I will do a bit more investigations to see if this reproduces with node.js. I also seem to have forgotten to execute the script (via `runInContext`). I think a lot of performance regression originates from executing the code and not just loading it.

**Comment by bpasero** [comment]
I have updated the sample repository with a more concrete sample that simulates what VSCode does on startup. My initial sample was not showing a regression in startup times when measured 500 times.

**To Reproduce**
The following example loads the minified code of VSCode (~5 MB of data).
* use macOS (the sample will not run on any other OS)
* `git clone https://github.com/bpasero/electron-cached-data.git`
* `npm install`
* `npm start`
* wait until `3.0.10/cache` folder is filled with ~23 files (this is the cached data which we need to produce the actual times on a second run)
* quit
* `npm start`
* open developer tools and check for the printed number (e.g. `500ms`)
* quit
* change the `package.json` to use Electron `2.0.12`
* `npm install`
* `npm start`
* wait until `2.0.12/cache` folder is filled with ~23 files (this is the cached data which we need to produce the actual times on a second run)
* quit
* `npm start`
* open developer tools and check for the printed number (e.g. `400ms`)

On my mac I see a diff of around `500ms` on `3.0.10` vs `400ms` on `2.0.12`.

**Comment by bpasero** [comment]
**Update 2:** I cannot reproduce a slowdown with a node.js sample that I added to the repository. By loading `vs/workbench/node/extensionHostProcess` instead of `vs/workbench/node/workbench.main` (a pure node.js code that will load in node.js environment)  in Electron `3.0.x` vs node.js `10.2.0` I get `~200ms` for Electron and `130ms` for node.js. 

This makes me wonder again if this could indeed be due to untrusted code mitigations (as reported against node.js before: https://github.com/nodejs/node-v8/issues/40)

@deepak1556 if you could craft a PR that properly disables the untrusted code mitigations in Electron's V8, I could try to build an Electron version with it to measure the difference. As I mentioned earlier, the runtime flag does not seem to have any impact. If I had to guess, we need to flip the flag in https://github.com/electron/node/blob/fcaf11a29c421b0e76c9f24f5b155a53eff14e7f/deps/v8/gypfiles/features.gypi#L97 ?

**Comment by deepak1556** [comment]
https://github.com/electron/electron/commits/disable_v8_untrusted_code_mitigations_4_X should have it disabled for 4.x branch

**Comment by bpasero** [comment]
@deepak1556 thanks. I am a little bit less optimistic now that I have locally build a version of node.js where the mitigations are enabled and my tests show similar code loading times as with the default node.js config. I was hoping to reproduce the slow loading times with a node.js build that uses the same flags.

While comparing the V8 flags of Electron vs node.js I found a few more differences that I cannot really explain:

* `--aggressive-lazy-inner-functions` : electron=true, node=false
* `--enable-experimental-builtins` : electron=false, node=true
* `--asm-wasm-lazy-compilation` : electron=true, node=false
* `--turbo-disable-switch-jump-table` : electron=true, node=false

The last one can be explained because it seems to be derived from the untrusted code mitigations flag. The first three I cannot explain though.

**Comment by bpasero** [comment]
**Update:** I just tried to load code using Electron 3.0.x and `ELECTRON_RUN_AS_NODE` and interestingly cannot reproduce the slowdown, I get pretty much the same times reported back as with a bare node.js version. This means that something in the renderer process slows down code loading considerably.

**Comment by bpasero** [comment]
**Update:** it looks like script loading time could be a red herring. Basically any computational task that happens right after window opening seems to be slower in 3.0.x. To reproduce, we can simply run some iterations of a expensive function and measure times, e.g. in the `renderer.js`:

```
function fibonacci(num) {
  if (num <= 1) return 1;

  return fibonacci(num - 1) + fibonacci(num - 2);
}

const now = Date.now();
fibonacci(40);
console.log(Date.now() - now);
```

I see a slowdown using 3.0.x vs 2.0.x easily with this sample.

**Comment by bpasero** [comment]
Actually the slowdown in this case is reproducible also when I try with `ELECTRON_RUN_AS_NODE=1`

**Comment by bpasero** [comment]
**Update:** the performance regression of fibonacci does not reproduce when V8 untrusted code mitigations are disabled. The change we use is: https://github.com/electron/libchromiumcontent/commit/58fb85dd25e02cc62dda64c6908bf73758a94690

**Comment by bpasero** [comment]
Update: it looks like not using `--nolazy` and the new [`script.createCachedData()`](https://nodejs.org/docs/v10.6.0/api/vm.html#vm_script_createcacheddata) API in node.js 10.6.0 improves the timing quite a bit. Since this new API is not available in Electron 3.0.x, we backported it on our custom build of 3.0.x.

**Comment by sofianguy** [comment]
@bpasero is this still happening in v4.2.x or later?

**Comment by bpasero** [comment]
I think we are OK given https://github.com/electron/electron/issues/16099#issuecomment-455508844

**Comment by sofianguy** [comment]
Ok, I will close this for now
