### ISSUE TITLE
How to install a mysql database software while installing electron application? Instead of installing separately.

### ISSUE THREAD

**Issue by bsikatti16** [electron/electron#16100]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lee-dohm** [comment]
Please see [the answer](https://github.com/electron-userland/electron-packager/issues/924#issuecomment-447888453).

-----

Please also note that spamming our organizations and repositories with the same question over and over is considered harassment under the [Electron Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md). If you continue to do this, you will be permanently blocked from these organizations.
