### ISSUE TITLE
Enhance setEnabled API to allow keeping the shell (X, minimize, maximize buttons) enabled

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#16103]
Is it feasible to introduce an optional `options` parameter to the `setEnabled` API to prevent disabling the shell (e.g. X button, minimize, maximize, whatever else comprises the "shell" - I guess the menu bar?)

**Is your feature request related to a problem? Please describe.**
I want to disable the window (specifically the contents of the webview), but I still want to be able to close out of the window while it's disabled.

**Describe the solution you'd like**
I want to enhance the `setEnabled` API such that it takes an extra optional parameter:

    declare function setEnabled(enabledState: boolean, opts?: SetEnabledOptions);

where `opts` looks something like:

    { disableShell: boolean }

And `disableShell` defaults to `true`.

**Describe alternatives you've considered**
I work around this in my app by adding an API to my guest page that's loaded in the webview that puts up a `div` over everything, effectively disabling the contents.

Another optional may be to add attributes onto the `webview` element to disable it.

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
