### ISSUE TITLE
(MacOS Mojave) - Video stream takes a long time to generate 

### ISSUE THREAD

**Issue by sai-gollamudi** [electron/electron#16105]
* Output of `node_modules/.bin/electron --version`: **v3.0.9**
* Operating System: **MacOS Mojave (10.14)**
* System Configuration: **MacBook Pro (15-inch, 2016), 2.7 GHz Intel Core i7, 16 GB 2133 MHz LPDDR3, Radeon Pro 460 with 4GB of GDDR5 memory**

**Expected Behavior**
Video stream should start instantaneously when `navigator.mediaDevices.getUserMedia` is called, and the camera light bulb indicator should start glowing immediately. 

**Actual behavior**
The video stream takes a while to start **on systems running MacOS Mojave**, and the camera light indicator too does not start glowing immediately. This causes a noticeable delay in the generation of a video preview. The delay is anything between 4s and 10s on the above mentioned system, and significantly more on lower specced systems (2014 Mac Minis with 8GB RAM) running on MacOS Mojave. But there is no delay on the same systems running MacOS High Sierra. There is also no delay at all in the browsers (tested on chrome, safari, chromium66 and chromium71), or when the app is run locally, the issue happens only in the generated installers in mojave.

**To Reproduce**
First, navigate to https://test.webrtc.org/ - to run a quick diagnostic test. Notice that the camera light indicator starts glowing immediately after the microphone test ends and the camera test starts.

Then, check this sample repository to reproduce this issue. You need to generate an installer and run the installed application to test the delay.
```
$ git clone https://github.com/sai-gollamudi/electron-media-test-app
$ npm install
$ npm run installer
```
I get a 5s delay from the time that the microphone test ends and the camera tests begin (or, if u will, a 5s delay from when the microphone test ends and the green faceTime camera bulb turns on). There is no delay at all in systems running on MacOS High Sierra

**Additional Information**
Tested on Chromium v66, which is the version of chromium that electron v3.0.9 uses (download link [here](https://sourceforge.net/p/osxportableapps/activity/?page=0&limit=100#5b20de03f0d34709bbb53b87)) - works fine without any delay

**Comment by virgilm** [comment]
Having the same issue, any progress on this?

**Comment by zmmbreeze** [comment]
I fixed this delay by adding code signature.

**Comment by sai-gollamudi** [comment]
@zmmbreeze - that worked for me as well! thanks a lot! I was signing the installer previously. Code signing seems to have done the trick! thanks a ton for the pointer!

**Comment by Xiaofuziod** [comment]
@sai-gollamudi  Another observation with electron on MacOS mojave - video devices show up in navigator.mediaDevices.enumerateDevices() even after the video device is unplugged.  How to deal with it？

**Comment by blaumeise20** [comment]
I have the same problem with macOS Catalina, but not via an installer, but in development mode. Is there a way to fix it when just executing it with `electron .` ?
