### ISSUE TITLE
Electron.remote need to be an object or not?

### ISSUE THREAD

**Issue by wgrhstf** [electron/electron#16102]
If I try to achieve two tasks with electron remote in one renderer process one needs the require as an Object, the other does not. 
So I have:
`const {app} = require('electron').remote;` for 
`let AppDataFolder = app.getPath('userData');`
and 
`const appNoObject = require('electron').remote;` for 
`let mainwindow = appNoObject.getCurrentWindow();`

If I only import remote one time the other function tells me getCurrentWindow() or getPath() is not a function. Is that deliberately and I'm missing something, or just a normal bug?

**Comment by MarshallOfSound** [comment]
That's how the remote API works.  The `getCurrentWindow` API is a method on the remote module itself and `getPath` is from the app module.
