### ISSUE TITLE
Errors and warnings are indicated but not shown in console

### ISSUE THREAD

**Issue by ohmmee** [electron/electron#16110]
* v3.0.10
* Windows 10

**Unusual behavior**
Warnings and Errors are indicated but not shown in console

**Screenshots**
![image](https://user-images.githubusercontent.com/23640077/50118141-e7ced880-0276-11e9-9c8e-f20beef390ee.png)
![image](https://user-images.githubusercontent.com/23640077/50118224-249acf80-0277-11e9-881d-1589b62dcb90.png)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

**Comment by ohmmee** [comment]
can't able to directly reproduce the same problem but found a solution to that
it occurred while working with simple variable objects too

was fixed after: Settings > Preferences > restore defaults and reload

it was also seen while working on chrome too maybe that's the problem with chromium build
