### ISSUE TITLE
Electron Native Menu Bar doesn't show

### ISSUE THREAD

**Issue by DProBoy** [electron/electron#16122]
Erm , the menu bar isn't visible in All of my electron applications (Atom , Vs Code ...etc ), i've also tried to create an electron app but it still isn't visible , All i see is a black-ish/Dark Grey (Ubuntu color) bar with no text or menu items , but when i click them they work !?
also VS Code-insiders' new custom menu bar works (the issue is with the native one)

* Output of `node_modules/.bin/electron --version`: v3.0.7
* Operating System (Platform and Version): Ubuntu 18.10 x64

### Expected behavior

The menu bar should appear visible

### Actual behavior

It is invisible

### How to reproduce

I really don't know

**Comment by codebytere** [comment]
@DProBoy as it stands, this issue is better raised with those applications and not Electron core. If something changes, happy to take another look!
