### ISSUE TITLE
4.0 regression: despite "--disable-gpu" or "app.disableHardwareAcceleration", 2 gpu proccess are started, 1st remains, 2nd exits

### ISSUE THREAD

**Issue by bughit** [electron/electron#16128]
* Output of `node_modules/.bin/electron --version`: v4.0.0-beta.10
* Operating System (Platform and Version): win7 sp1 x64
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v2.0.15

**Expected Behavior**
no gpu processes should be started

**Actual behavior**
1. 1st gpu process is started immediately and remains
2. 2nd gpu process is started after a 15secs and exits immediately

**To Reproduce**
- either run the default app `electron.exe --disable-gpu`
- or the following app
   ```js
   const { app, BrowserWindow } = require('electron');
   
   app.disableHardwareAcceleration();
   
   let win;
   
   app.once('ready', () => {
     win = new BrowserWindow();
     win.loadURL('about:blank');
   });
   ```

**Screenshots**
![image](https://user-images.githubusercontent.com/895588/50182583-b4736480-02dd-11e9-9920-e8d5613946bd.png)

**Additional Information**
- in 2.x no gpu processes are started
- in 3.x 1 gpu process is stated and exits immediately
- 4.x added a second gpu process that hangs around for the duration of the app

**Comment by nornagon** [comment]
Just to confirm, does Chromium exhibit the same behaviour?

**Comment by bughit** [comment]
I tried chrome 71, with --disable-gpu, seems to be doing the same thing.  Is this something electron can control or can it only be fixed upstream?  Seems rather wasteful to be launching 2 GPU processes and keeping one around when gpu acceleration is disabled.

**Comment by nornagon** [comment]
Yep, then the place for fixing this is [upstream](https://crbug.com).
