### ISSUE TITLE
In-memory Sessions cannot use clearCache

### ISSUE THREAD

**Issue by CGamesPlay** [electron/electron#16141]
* Output of `node_modules/.bin/electron --version`: v3.0.10
* Operating System (Platform and Version): macOS 10.14.2 (18C54)

**Expected Behavior**
When `session.fromPartition('foo').clearCache(callback)` or `session.fromPartition('foo').getCacheSize(callback)` is called, the callback will eventually be called.

**Actual behavior**
The callbacks are never called. Note that if we use `session.fromPartition('persist:foo').clearCache(callback)`, then the callback is called.

**Comment by BloodShura** [comment]
On `3.0.10` version it didn't happen; I migrated to `3.1.2` and it started happening. So it's a regression...

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
