### ISSUE TITLE
Image cause electron to crush

### ISSUE THREAD

**Issue by ejrcavenago** [electron/electron#16143]
* Output of `node_modules/.bin/electron --version`: v.3.0.7
* Operating System (Platform and Version): Win10 64bit
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): NA

**Expected Behavior**
The client embed the codepen section with a React component of an image tag without crashing.

**Actual behavior**
Every time the client tries to render the img with that source processed by a JS library (Angular/React/etc) it crashes

**To Reproduce**
[Link to forked repository](https://github.com/ejrcavenago/electron-quick-start/tree/img-crash)
```sh
$ git clone $YOUR_URL -b $BRANCH
$ npm install
$ npm start || electron .
```
**Screenshots**
![before](https://user-images.githubusercontent.com/4819495/50211729-3a8cbb00-0371-11e9-8dba-3533c32e267a.jpg)
![after](https://user-images.githubusercontent.com/4819495/50211728-39f42480-0371-11e9-8f93-4ddc5dae9cbc.jpg)

**Additional Information**
We had an issue with our client recently, one of our user uploaded a broken image as profile avatar and that caused the client itself to crash constantly. I noticed that the problem appeared when the image itself was managed through a JS library like Angular or React, but everything worked fine on Chrome, Chromium, Firefox, etc.
I've created a simple [codepen ](https://codepen.io/ejrcavenago/pen/XojrrG) with a react component that returns the broken image, as you can see in the attached screenshoots and running the given branch, the moment in which electron tries to render the image it crashes.

It seems to happen just with that image, but maybe you guys wants to dig deeper.

Thank you!

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
