### ISSUE TITLE
`shell.openExternal` doesn't work on Linux

### ISSUE THREAD

**Issue by jgierer12** [electron/electron#16149]
* Output of `node_modules/.bin/electron --version`: v3.0.13
* Operating System (Platform and Version): Manjaro Linux x86_64 (Kernel: 4.19.8-2-MANJARO)
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): N/A

**Expected Behavior**
Calling `shell.openExternal('https://google.com')` opens the default browser (Firefox).

**Actual behavior**
Nothing happens when calling the above code, but it returns `true`.
Executing `xdg-open https://google.com` works as expected.

**To Reproduce**
```sh
$ git clone https://github.com/jgierer12/electron-quick-start.git -b openexternal-bug-report
$ yarn
$ npm start || electron .
```
**Screenshots**
[![](https://thumbs.gfycat.com/NiceVigorousKingsnake-size_restricted.gif)](https://gfycat.com/nicevigorouskingsnake)

**Additional Information**
N/A

**Comment by phil294** [comment]
I can confirm this bug with 5.0.0-beta.1. While it seems to work with Chromium, Firefox cannot start.

This would seem like a critical issue to me..?

**Comment by codebytere** [comment]
This has been fixed in latest Electron releases. Verified on Ubuntu 16.06 and the following code:
```
const {app, BrowserWindow, shell} = require('electron')

let mainWindow

function createWindow () {
  // Create the browser window.
  mainWindow = new BrowserWindow() 

  mainWindow.loadFile('index.html')
 
  shell.openExternal('https://google.com').then(() => {
    console.log('hello')
  })

  mainWindow.on('closed', function () {
    mainWindow = null
  })
}

app.on('ready', createWindow)

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit()
})

app.on('activate', function () {
  if (mainWindow === null) createWindow()
})
```

**Comment by zkldi** [comment]
Hi, this issue appears to have popped up again. Firefox Dev Edition appears to load (it does the KDE bounce around my cursor), but then never actually opens into a window. This might be a firefox problem, or something else entirely, but I wouldn't know how to really check.

    Output of node_modules/.bin/electron --version: v15.1.1
    Operating System (Platform and Version): Linux zjaro 5.14.7-2-MANJARO #1 SMP PREEMPT Wed Sep 22 12:22:56 UTC 2021 x86_64 GNU/Linux
    Output of node_modules/.bin/electron --version on last known working Electron version (if applicable): N/A

Snippet:
```js
	shell.openExternal("https://google.com").then(() => {
		console.log("hello");
	});
```
Definitely tries to open something, but never seems to actually do anything. As mentioned above though, this might not be an electron problem.

**Comment by 320x200** [comment]
Could this issue be affecting https://github.com/logseq/logseq/issues/3965 and similar ones (searching online about electron apps and firefox and xdg-open and/or x-www-browser) leads to many struggling users of electron apps who can't open links when they have Firefox as default browser.
