### ISSUE TITLE
In Renderer process, data event and end event are not fired after the readable event is fired.

### ISSUE THREAD

**Issue by ClockGet** [electron/electron#16144]
* Electron version: 3.0.11
* Operating system: win10 x64
* Node version: 10.2.0

**Expected Behavior**
I use https module in renderer process, and I write some code like:
```
const https = require("https");
function get(url) {
    return new Promise((resolve, reject) => {
        const req = https.get(url, (res) => {
            let success = true;
            if (res.statusCode < 200 || res.statusCode >= 300) {
                success = false;
            }
            res.setEncoding("utf8");
            let html = "";
            res.once("readable", function () {
                console.log("readable");
            });
            res.on("data", function (data) {
                console.log("data");
                html += data.toString();
            });
            res.on("end", function () {
                console.log("end");
                if (success) {
                    resolve(html);
                }
                else {
                    reject(html);
                }
            });
            res.on('error', function (err) {
                reject(err);
            });
        });
        // Request events
        req.on('socket', (socket) => {
            socket.on('lookup', () => {
                console.log("lookup");
            });
            socket.on('connect', () => {
                console.log("connect");
            });
            socket.on('secureConnect', () => {
                console.log("secureConnect");
            });
            socket.on('timeout', () => {
                console.log("timeout");
            });
        });
        req.on('error', () => {
            console.log("error");
        });
    });
}
```
And this code will have the following log in the node environment.
```
lookup
connect
secureConnect
readable
data x N
end
```
**Actual behavior**
It has the following log in the electron renderer process environment.
```
lookup
connect
secureConnect
readable
```
**Additional Information**
If I modify the callback method of the readable event like that:
```
res.on("readable", function(){
    while(this.read()){
    }
});
```
Then in electron renderer process environement, it prints the data event and the end event.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by ClockGet** [comment]
I can't experience this issue in Electron v6.0.2 and v4.2.9.

**Comment by sofianguy** [comment]
Do you mean "can" or "cannot"? I want to make sure there isn't a typo.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
