### ISSUE TITLE
power-monitor does nothing on OSX 10.10.3

### ISSUE THREAD

**Issue by sebolio** [electron/electron#1615]
So I have a very simple code on a working app, but in no way does the event ever get trigged.

```
app.on('ready', function() {
  require('power-monitor').on('on-battery', function () {
    console.log('battery time');
  });
});
```

(The app itself is larger than that, ofc, I just cropped he useful part.

**Comment by zcbenz** [comment]
It seems that power state detection is broken.

**Comment by zcbenz** [comment]
From Chromium's source code is seems that they decided to only enable battery monitoring on Window:

```c++
#if defined(OS_WIN)
#include <windows.h>

// Windows HiRes timers drain the battery faster so we need to know the battery
// status.  This isn't true for other platforms.
#define ENABLE_BATTERY_MONITORING 1
#else
#undef ENABLE_BATTERY_MONITORING
#endif  // !OS_WIN
```

Anyway they implemented the battery monitoring by setting a 10s timer, so it is probably a good thing to not enable that.

**Comment by sebfindling** [comment]
@zcbenz good to know :)

**Comment by guatedude2** [comment]
Docs should be updated to reflect that ;)

**Comment by petr001** [comment]
for sure, quite missing this feature :-(

**Comment by dmfarcas** [comment]
I'll be using dbus events as a workaround, for example:

> destination=org.freedesktop.PowerManagement serial=352 path=/org/freedesktop/PowerManagement; interface=org.freedesktop.PowerManagement; member=Suspend

**Comment by bengotow** [comment]
For anyone stumbling across this - we should definitely get macOS support for powerMonitor into Electron (anyone want to submit a PR?) In the meantime though, you can get battery / AC charger status from macOS with this shell command:

```
pmset -g batt

Now drawing from 'Battery Power'
 -InternalBattery-0 (id=3080291)	66%; discharging; 4:20 remaining present: true
```
Unfortunately you'd need to poll, but doing it every 5 minutes or so probably isn't bad.

**Comment by KeitIG** [comment]
I have no Idea of the complexity if the thing, but Linux support would be great too!

**Comment by thechori** [comment]
Would also love to see this fixed for macOS. I know it's not *too* difficult to implement natively using Swift/Objective-C. What would we have to do in order to expedite the implementation of this?

**Comment by sindresorhus** [comment]
For reference, [here's](https://github.com/codler/Battery-Time-Remaining/blob/9fffe513a1932bddc198893ab29ed3451ca2978a/Battery%20Time%20Remaining/AppDelegate.m#L26-L32) how you implement the power source change callback.

**Comment by codebytere** [comment]
Closing as power monitor has now been enabled for mac.
