### ISSUE TITLE
Unable to enable Electron in Windows Firewall

### ISSUE THREAD

**Issue by ghost** [electron/electron#16150]
* Output of `node_modules/.bin/electron --version`: `4.0.0-nightly.20181010` (actually output is empty, got the version using `npm list electron`)
* Operating System: Windows 8.1 x64
* Output of`node_modules/.bin/electron --version`on last known working Electron version: not applicable

**Expected Behavior**
The following code should open Electron window and display content of github.com:

```js
const electron = require('electron');
electron.app.on('ready', () => {
  var win = new electron.BrowserWindow({
    width: 640,
    height: 480,
  });
  win.loadURL('https://github.com');
});
```

**Actual behavior**
Browser window appears, but it's empty. No content.

**To Reproduce**
Install electron using `npm i -D -g electron@nightly`
Save above code as `script.js`
Run `electron script.js`

**Screenshots**
Not applicable.

**Additional Information**
Our windows firewall blocks all programs by default. We need to explicitly whitelist all applications that need internet connection.
We whitelisted `%appdata%\npm\node_modules\electron\dist\electron.exe`, but we still observe that electron is unable to connect to the intenret.
Disabling firewall completelly makes electron work properly, but that is not an option.
We used Sysinternals NetMonitor to find out which applications need internet
The only application that performs requests is the above mentioned `electron.exe` file
However, enabling it in firewall doesn't work.
We suspect that electron performs some general checks regarding connectivity and if it finds out that network is disabled, it doesn't even perform requests.
Note: node.js is enabled in firewall and works properly (performs http requests as expected), but electron doesn't work.

**Comment by tempuser1233** [comment]
Finally solved the problem! Posting solution here for future users who may experience the same issue. The issue was that Windows Firewall doesn't work properly with environment variables in paths. Instead of

```
%appdata%\npm\node_modules\electron\dist\electron.exe
```

we had to specify

```
C:\Users\doublehelix\AppData\Roaming\npm\node_modules\electron\dist\electron.exe
```

Hope this helps someone.
