### ISSUE TITLE
Tray-menu loading is slow when there are multi-level menus

### ISSUE THREAD

**Issue by orangeChu** [electron/electron#16156]
* electron@3.0.12(It also happens in 4.0.0)
* win7 ultimate 64bit

Hi guys,
When I try to create multi-level menu for tray-menu,it worked,but loading speed is too slow.

Example code is below.
main.js
```
'use strict';
const app = require('electron').app;
const Tray = require('electron').Tray;
const Menu = require('electron').Menu;
const path = require('path');

let tray;
let contextMenu;

class Test {
    constructor() {

    }

    initApp() {
        app.on('ready', () => {
            this.createTray();
        });
    }

    createTray() {
        tray = new Tray(path.join(__dirname, 'icon.png'));
        tray.setToolTip('Test');

        let childMenu = [];
        let submenu = [];
        let lastLv = [];

        for (let index = 0; index < 5; index++) {
            lastLv.push({
                label: `lastLv${index}`
            });
        }

        for (let index = 0; index < 10; index++) {
            childMenu.push({
                label: `childMenu${index}`,
                type: 'submenu',
                submenu: lastLv
            });
        }

        for (let index = 0; index < 500; index++) {
            submenu.push({
                label: `menuItem${index}`,
                type: 'submenu',
                submenu: childMenu
            });
        }

        contextMenu = Menu.buildFromTemplate([{
            label: 'test',
            type: 'submenu',
            submenu
        }]);

        tray.on('right-click', () => {
            //It may be cost 2's or more
            tray.popUpContextMenu(contextMenu);
        });
    }
}

new Test().initApp();
```

**Comment by orangeChu** [comment]
When I was running on macOS, it worked very well.
Does anyone have this situation?Any help?

**Comment by VerteDinde** [comment]
@orangeChu We're seeing something a bit similar when using the buildFromTemplate method, but on both Mac and Windows. Your Mac build is working as expected? I'd be curious to see if buildFromTemplate is causing the slowdown.

**Comment by orangeChu** [comment]
@VerteDinde Sorry, I just saw your message.I test I tested the code in this [repository](https://github.com/orangeChu/multi-level-menu-for-tray.git) on macOS 10.14.2 and it worked quite well.But under Windows 7&10,it took almost a second to show up.My screenshot is below:

![screen](https://user-images.githubusercontent.com/25950247/51219452-f7bc0400-196b-11e9-866f-9d5e91b06bc1.gif)

**Comment by orangeChu** [comment]
> @orangeChu We're seeing something a bit similar when using the buildFromTemplate method, but on both Mac and Windows. Your Mac build is working as expected? I'd be curious to see if buildFromTemplate is causing the slowdown.

I spent some time testing to create a multi-level menu using `menu.append`. On Windows, the effect is the same as `buildFromTemplate`, and it takes about a second to display. Hope this will help you.

**Comment by codebytere** [comment]
This is more of a platform limitation than a function of how Electron implemented Menu apis, so sadly i don't think there's much we can do if you're at a place where you're creating hundreds of multi-layer nested menus.

**Comment by orangeChu** [comment]
@codebytere Thank you for your attention! When I use winform, I nest a multi-level tray menu, just like the multi-level menu in the example, and its display speed is consistent with the normal menu. So, I don't think this is a limitation on the Windows platform?

**Comment by orangeChu** [comment]
Is it possible to reopen the question? :smile:
