### ISSUE TITLE
Printing blank pages

### ISSUE THREAD

**Issue by adammeyer** [electron/electron#16151]
* Output of `node_modules/.bin/electron --version`: 3.0.13
* Operating System (Platform and Version): MacOS 10.14.2
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2.0.16

**Expected Behavior**
Print all content.

**Actual behavior**
Only printing first page's content, the reset of the pages are blank.  Electron 2 prints all pages.

**To Reproduce**
Print anything greater than one page on Electron 3 using `window.print()`.

**Screenshots**
![screen shot 2018-12-19 at 1 33 15 pm](https://user-images.githubusercontent.com/4603906/50240589-2ce82d00-0393-11e9-9f03-dd4a1241e649.jpg)

**Comment by adammeyer** [comment]
I have confirmed it is just a MacOS issue. Working fine on Windows.

**Comment by bengotow** [comment]
Hey! In my case I was using the `print` callback to close the BrowserWindow being printed. I discovered recently that if I do not close the window after printing is complete, it works fine. I suspect the callback is being fired early and the app is actually /not/ done spooling the pages to the printer. Does that match your use case as well?

**Comment by adammeyer** [comment]
Thanks, doesn't match my case.  I'm not closing the window.  Are you using Electron 3 or 4?

**Comment by codebytere** [comment]
This should be fixed in latest supported versions of Electron.
