### ISSUE TITLE
Linux symbols size has decreased significantly in Electron 3

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#16161]
* Output of `node_modules/.bin/electron --version`: 3.0.10
* Operating System (Platform and Version): Linux
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 2.0.16

It seems like Linux symbols' size has dropped significantly comparing to Electron 2, e.g. for Electron 2.0.16 [1] size of “electron-v2.0.16-linux-x64-symbols.zip” is *51.3* Mb, but for Electron 3.0.13 “electron-v3.0.13-linux-x64-symbols.zip” it’s only *9.84* Mb.
Native stacktraces are barely useful because of this.

[1] https://github.com/electron/electron/releases/tag/v2.0.16
[2] https://github.com/electron/electron/releases/tag/v3.0.13

**Comment by sofianguy** [comment]
@alexeykuzmin is this still a bug in 4.2.x or later?

**Comment by sofianguy** [comment]
closing for now but we'll reopen if this is still happening on later versions of electron
