### ISSUE TITLE
require screen module before app ready causes error

### ISSUE THREAD

**Issue by timfish** [electron/electron#16168]
Affects all supported Electron versions and platforms and has been reported and closed before [here](https://github.com/electron/electron/issues/5897) in 2016.

**Expected Behavior**
This should not have any side effects:
```typescript
const { screen } = require('electron');
```
**Actual behavior**
However it gives an error:
`Error: Cannot require "screen" module before app is ready`

As well as the undesired side effects, the error is pretty poor as we're not even requiring the screen module, we're simply accessing the property.

This also means the docs ask developers to do unnecessary complicated things like:
```
const electron = require('electron')
const { app, BrowserWindow } = require('electron')

app.on('ready', () => {
  let displays = electron.screen.getAllDisplays()
```

**Additional Information**
The session API cannot be used before app ready, but can be required without side effects:
```
// This doesn't result in an error
const { session } = require('electron');
```

The APIs that are unavailable before app ready should at least behave consistently.

**Comment by nornagon** [comment]
Seems reasonable to me. Looks like the right approach from the code side would be to lazily create an instance of `Screen` when it's first needed, rather than when the property is accessed. PR welcome!

**Comment by sandeep1995** [comment]
Using `electron-window-state` package throws the same error as above
