### ISSUE TITLE
OpenDialog allows folder selection unexpectedly in 'Recently Used' area of Linux file browser

### ISSUE THREAD

**Issue by ntpincus** [electron/electron#16163]
Same issue as [10197](https://github.com/electron/electron/issues/10197) but different electron version, and I did not receive a response.

* Output of `node_modules/.bin/electron --version`: v2.0.1 
* Operating System (Platform and Version): on CentOS Linux release 7.5.1804

**Expected Behavior**
Filtering the files by .jpg should allow the user to only select files of .jpg extensions, and not folders

**Actual behavior**
User can incorrectly select a folder in the Recently Used section, and electron appends the filtered extension to the file name. For example filtering by .jpg, and selecting the Folder MyPhotos in the recently used section outputs 'MyPhotos.jpg' (which is a file that doesn't exist).

**To Reproduce**
Install electron v2.0.1 on a Linux system, add an openDialog and filter by any extension type, select a folder from the recently used section. Observe resulting selection.

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
