### ISSUE TITLE
after win.hide the chromium  can't  render UI

### ISSUE THREAD

**Issue by citrusjunoss** [electron/electron#16169]
* Output of `node_modules/.bin/electron --version`: 3.0.12
* Operating System (Platform and Version):  win10

**Expected Behavior**

When the window is hidden `win.hide()`, I reset the data, the DOM with the data binding has been updated, and the UI should be rendered successfully. When I redisplay the window win.show(), the UI should have been rendered as empty data.

**Actual behavior**
When the window is hide `win.hide()`, I reset the data, the Dom has been updated, but the UI is not rendered. When I redisplay the window `win.show()`, the old data will be displayed briefly,  After that, the UI rendered as empty data。 It is obvious to see the UI. Re-rendering process

**To Reproduce**
When the window is hide `win.hide()`, I reset the data, the Dom has been updated, but the UI is not rendered. When I redisplay the window `win.show()`, the old data will be displayed briefly,  After that, the UI rendered as empty data。 It is obvious to see the UI. Re-rendering process

**Screenshots**
![test](https://user-images.githubusercontent.com/18432488/50324215-a4939480-0518-11e9-8b3b-6551e0ed5082.gif)
![image](https://user-images.githubusercontent.com/18432488/50324315-40250500-0519-11e9-93ea-3d6aa27b3cec.png)

**Additional Information**
Same as this issue #9720 , but this issue is not resolved, I also tried the requestIdleCallback method proposed by github , but it does not seem to take effect.
https://github.com/desktop/desktop/pull/1416,

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by fanchenio** [comment]
It's 2023, I use electron22, this problem is still not solved, I'm really speechless, I refresh the DOM before displaying the window, and then the page will flicker after displaying the window.

**Comment by silviawxy** [comment]
@citrusjunoss 大佬，想问下，这个问题有找到解决方案吗
