### ISSUE TITLE
gpio problem

### ISSUE THREAD

**Issue by hllhui** [electron/electron#16170]
i want to install electron into the pi and use it to control gpio

to reproduce it is enough to require the [pi-gpio lib](https://github.com/JamesBarwell/rpi-gpio.js).
```
const gpio = require('rpi-gpio')
```

run 'node main.js' is no problem,but i run 'election main.js' has an error like this:
```
/home/pi/safe-ui/node_modules/electron/dist/electron .
symbol lookup error:
/home/pi/safe-ui/node_modules/epoll/build/Release/epoll.node: undefined symbol:
_ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS
_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
```

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
