### ISSUE TITLE
`app.getAppMetrics()` and `ProcessMetric` - memory no longer available

### ISSUE THREAD

**Issue by jarrodek** [electron/electron#16179]
* Output of `node_modules/.bin/electron --version`: v4.0.0
* Operating System (Platform and Version): Ubuntu 18.04.1 LTS
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 3.x

**Expected Behavior**
The `ProcessMetric` contains `memory` entry.

**Actual behavior**
`memory` information is no longer available.

**To Reproduce**

```
let metrics = app.getAppMetrics();
console.log(metrics[0].memory);
```

**Additional Information**
I am using `app.getAppMetrics()` during development to check memory and CPU usage of my app. I have a task manager view as the one available in Chrome. After updated electron to v4 today I noticed that the `memory` property is no longer available. I saw other issues related to this: #13385, #13414, and #13383 but it's not clear whether you wanted to remove this metric or find the other way to present this information.
Will memory info be available?

**Comment by MarshallOfSound** [comment]
@jarrodek That property was deprecated in 3.0 and removed in 4.0.  The appropriate runtime warnings were giving in 3.x releases and it was mentioned in our [breaking changes document](https://github.com/electron/electron/blob/master/docs/api/breaking-changes.md#breaking-api-changes-30).

This was an intended API removal as a result of a Chromium API change

**Comment by jarrodek** [comment]
Are there any plans to introduce new API to get memory info? Just curious. :)

**Comment by MarshallOfSound** [comment]
@jarrodek See https://github.com/electron/electron/issues/13447

Also refs: https://github.com/electron/electron/pull/14847
