### ISSUE TITLE
webview.printToPdf() stopped working in 4.0

### ISSUE THREAD

**Issue by burningTyger** [electron/electron#16171]
* Output of `node_modules/.bin/electron --version`: v4.0.0

* Operating System (Platform and Version): Arch Linux 4.19
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v3.0.13

**Expected Behavior**
`webview.printToPdf()` returns some Buffer in its callback function.

**Actual behavior**
`webview.printToPdf()` returns `undefined`

**To Reproduce**

```sh
$ git clone https://github.com/burningTyger/electron-bug
$ npm install
$ npm start || electron .
```

The `console.log` will return undefined for `data` in the callback.

**Comment by burningTyger** [comment]
Workaround available from #16241 
Just use webContents:

        webview.getWebContents().printToPDF({}, (error, data) => {
          console.log(data, error)
          if (error) throw error
          fs.writeFile('output.pdf', data, error => {
            if (error) throw error
          })
        })

**Comment by miniak** [comment]
It's fixed in Electron 6

**Comment by bjbk** [comment]
And broken again in v7.0.0 https://github.com/electron/electron/issues/20634
