### ISSUE TITLE
Electron 3 and 4 package.json contains @types/node ^8.0.24 but release notes mention note 10.11

### ISSUE THREAD

**Issue by thomasLechaptois** [electron/electron#16173]
* Output of `node_modules/.bin/electron --version`: v4.0.0
* Operating System (Platform and Version): Windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):
v2
**Expected Behavior**
Unable to use the latest additions on node v10 using typescript

**Actual behavior**
We can only use note v8 features. 

Please update @types/node version in electron package.json

**Comment by shiftkey** [comment]
@thomasLechaptois want to give a shot at upgrading it to Node 10?

https://github.com/electron/electron/blob/6f91af93433df4e9c0e7fb592e5b2dcb0b1c7888/npm/package.json#L14
