### ISSUE TITLE
Is it possible to load PDF in an iFrame using electron browser?

### ISSUE THREAD

**Issue by Bahramudin** [electron/electron#16185]
* Output of `node_modules/.bin/electron --version`: 3.0.4
* Operating System (Platform and Version): Windows
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

I am able to open the PDF file in PDF viewer, which is using `<a>` tag

```
<a href="https://mmm.com/pdf/pdf_file.pdf" class="report-div-a" target="_blank"> 
    <div class="pull-left">View</div>
</a>
```
But this not working:
```
<iframe _ngcontent-c1="" allowfullscreen="" frameborder="0" mozallowfullscreen="" webkitallowfullscreen="" src="https://mmm.com/pdf/pdf_file.pdf">
</iframe>
```
**Expected Behavior**
I try to open the PDF file in iFrame, but it starts downloading (not viewing). I expect to preview the file instead of download, as the normal browsers can

**Actual behavior**
When I click the link for PDF file, in normal browsers it will open a window and preview the file. But in Electron browser it starts downloading instead previewing.

--
**Note:** All things works well on the normal browsers.

**Comment by burningTyger** [comment]
This is possibly related to issue #12337

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
