### ISSUE TITLE
Electron Tray Submenu not work on latest linux like Ubuntu 16.04

### ISSUE THREAD

**Issue by smartweber** [electron/electron#16189]
* Output of `node_modules/.bin/electron --version`:
v3.0.8
* Operating System (Platform and Version):
Ubuntu 16.04

**Expected Behavior**
The submenu should display properly as another  electron app menu.
This is screen on mac ,https://snag.gy/zMe5dg.jpg. You can see Demo Call's Default subment item.

**Actual behavior**
The submenu has a scroll bar for many items and submenu's items are not displayed.
On ubuntu 16.04, the submenu ui is different than mac and the Demo Call's Default item isn't shown.
https://snag.gy/lj6Aq8.jpg

**To Reproduce**
Step1:
Please download starter project from this link, https://github.com/maximegris/angular-electron.

Step2:
Please add as many submenu items as enough.

Step3:
Please run the project.

```sh
$ npm install
$ npm run electron:local
```

**Screenshots**
https://snag.gy/zMe5dg.jpg
https://snag.gy/lj6Aq8.jpg

**Additional Information**
The issue is occurred in the latest ubuntu os like 16.04 and 18.04

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
