### ISSUE TITLE
Electron still takes in Xbox controller input even when it's not in focus.

### ISSUE THREAD

**Issue by benlei** [electron/electron#16182]
* Looks like this will be a continuation of https://github.com/electron/electron/issues/9669
* Operating system: Windows 10
* I'm using Emby Theater, which currently uses the latest version of electron (4), but this issue seems to have existed since 1.4.16.

**Expected Behavior**
If I'm playing a game using an Xbox controller (and as a result, Electron isn't in focus), pressing any of my Xbox controller's buttons shouldn't affect Electron (unless Electron is focused).

**Actual behavior**
It looks like Electron still takes in Xbox controller input even if it's not in focus. For example, if you play a game or watch a movie while Electron isn't in focus and press any of your Xbox controller buttons, Electron still receives the input.

**To Reproduce**
Have an Xbox one controller while electron is open. Open up a game (while the game is in focus) press your Xbox one controller buttons.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
