### ISSUE TITLE
Allow more than one BrowserView per BrowserWindow

### ISSUE THREAD

**Issue by pr0gr8mm3r** [electron/electron#16181]
**Is your feature request related to a problem? Please describe.**
For the app I'm creating, I'd need to have the ability to add multiple BrowserViews to my BrowserWindow (I want to use the performance advantage of multiple threads).

**Describe the solution you'd like**
I'd like to be able to add multiple BrowserViews to a single BrowserView

**Describe alternatives you've considered**
- I tried to use individual hidden windows, as only one of the views has an UI that's visible to the user, and it worked fine. The thing is that it's harder to manage these windows then (close them all when ui closes, ...). Also, other developers might need multiple UIs in a single window
- webview doesn't allow me to have multiple threads

**Comment by kwonoj** [comment]
isn't this https://github.com/electron/electron/pull/16148 ?

**Comment by pr0gr8mm3r** [comment]
Yes, I'm sorry. Just searched through issues, not PRs...
