### ISSUE TITLE
TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by Maks1988** [electron/electron#16188]
Can anybody help me here  ???? 
Can't understand what i need to do to fix it ? 
`
const electron = require('electron');
const app = electron.app;
const BrowserWindow = electron.BrowserWindow;

function createWindow(){
    win = new BrowserWindow({width:800,height:600});
    win.loadFile('views/index.html');
}

app.on('ready',createWindow);
`

**Comment by temannin** [comment]
Use this instead

`const { app, BrowserWindow } = require('electron')`

**Comment by KHALED-LAKEHAL** [comment]
@Maks1988 
try run code with `electron file_name.js` not `node file_name.js`

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
