### ISSUE TITLE
Crash on large amounts of a particular Unicode character 

### ISSUE THREAD

**Issue by Snorkss** [electron/electron#16191]
Referencing report - #10332 from 8/22/17

Seems like this was never patched and still is an issue in many chat clients such as 'Slack' and 'Github's desktop editor' , not sure what version of electron they are running.

**Expected behavior:**
Client renders characters normally.

**Actual behavior:**
Client freezes sometime crashes.

**How to reproduce:**
Paste the contents of this anywhere in any of the effected applications - https://ghostbin.com/paste/3ubte 

Notes - U+09E3 is the Unicode symbol.

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
