### ISSUE TITLE
插件无法使用

### ISSUE THREAD

**Issue by lQei** [electron/electron#16194]
* Output of `node_modules/.bin/electron --version`: v10.2.0
* Operating System (Platform and Version):window10专业版  64位
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
能够使用VXG Media Player。

**Actual behavior**
加载插件
var player =BrowserWindow.addDevToolsExtension("E://soft/chromeFOR.COM_vxg-media-player_v1.8.47");
此处可打印出player为VXG Media Player。
但是无法使用此插件播放视频。

**To Reproduce**
https://www.videoexpertsgroup.com/vxg-chrome-plugin/

$ git clone $YOUR_URL -b $BRANCH
$ npm install
$ npm start || electron .
```
**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional Information**
Add any other context about the problem here.

**Comment by jettangs** [comment]
还不支持该扩展吧

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
