### ISSUE TITLE
a space is output to the console

### ISSUE THREAD

**Issue by h2oota** [electron/electron#16197]
* Output of `node_modules/.bin/electron --version`: 4.0.0
* Operating System (Platform and Version): Windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
```
c:\>electron hello.js
hello world!
hello world!
c:\> 
```
**Actual behavior**
```
c:\>electron hello.js
 hello world!
hello world!
c:\> 
```
**To Reproduce**
hello.js
```
console.log('hello world!');
console.log('hello world!');
require('electron').app.quit();
```

**Screenshots**

**Additional Information**

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
