### ISSUE TITLE
Why can electron app be published on MAC App Store? 

### ISSUE THREAD

**Issue by fengsiri** [electron/electron#16190]
According to this [guideline](https://electronjs.org/docs/tutorial/mac-app-store-submission-guide), electron app can be published to MAC App Store. Electron itself is based on chromium and node.js, and they are both based on v8 js engine which enables JIT. But JIT compiler is not allowed by MAC App Store as far as I know. So how can it bypass this limitation?

**Comment by PCGeekBrain** [comment]
What makes you think a JIT compiler is not allowed in the app store?

As far as I know apple has no problem with JavaScript based software on their platforms (e.g. react native apps for iOS)

If it helps I found this flag which seems to say that apple has no problem with JIT in xcode applications:

https://developer.apple.com/documentation/security/com_apple_security_cs_allow-jit

**Comment by PCGeekBrain** [comment]
I think you answered your own question.

React Native and other mobile JS based app frameworks use apple's WebKit framework to run the pages. As such they are allowed to pull scripts that do not fundamentally change the app's behavior without breaking the terms of service.

For MacOS apps (electron) they allow you to "install or run interpreted or executable code". This would allow for JIT and compiled app updates as long as they follow (a) and (b). (a) is basically apple's way of saying "we call it an update so it is an update" and (b) says that you have to keep the application within the scope in which you published it (e.g. don't turn your RSS reader into a Torrent client or something)

**Comment by fengsiri** [comment]
So theoretically if electron choose JSC instead of v8, then electron apps can pull scripts as the same as react native. That means we must make node.js run on JSC. I notice that there is a open source project [node-jsc](https://github.com/mceSystems/node-jsc) that try to implement a jscshim to adapt jsc interface to v8's like [node-chakracore](https://github.com/nodejs/node-chakracore). But as node-jsc itself indicates, it is a very early work in progress, and is far from being ready for production use.

**Comment by PCGeekBrain** [comment]
Not really, Electron is built as a way to build desktop apps and uses desktop paradigms in it's architecture.

For example, there is no menu bar, system tray or multi-window support on mobile devices...

Basically if it is a mobile app you want you should build it using a framework that understands the environment of the phone like react native and use something like electron or nw.js for the desktop. Since they are all javascript this should not really prevent you from sharing business logic code between them.

**Comment by fengsiri** [comment]
> Not really, Electron is built as a way to build desktop apps and uses desktop paradigms in it's architecture.
> 
> For example, there is no menu bar, system tray or multi-window support on mobile devices...
> 
> Basically if it is a mobile app you want you should build it using a framework that understands the environment of the phone like react native and use something like electron or nw.js for the desktop. Since they are all javascript this should not really prevent you from sharing business logic code between them.

I got it, thanks!
