### ISSUE TITLE
Electron 4.0.0  'unknown cipher' appears  in Crypto module

### ISSUE THREAD

**Issue by mazhorse** [electron/electron#16195]
* Output of `node_modules/.bin/electron --version`:  4.0.0
* Operating System (Platform and Version):  Windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):  v3.x.x

**Expected Behavior**
Generally , invoke ``crypto.createCipheriv ()`` that should return a Cipheriv Object.

**Actual behavior**
When I call  ``crypto.createCipheriv()`` , it will  response me a error that is **unknown cipher** .
But   If I run this program(**test code** ) alone by node cmd. (ex. node test.js ) that it work.
So I don't think it is a node10 problem.

**To Reproduce**
**sample code** 
in main.js
```
const crypto = require('crypto')
const methodName = 'aes-256-cfb'
const key =  'nMvTdb7VXMPudFWH'
const iv = crypto.randomBytes(16)
const cipher = crypto.createCipheriv(methodName, key, iv)
console.log(cipher)
```
**Response:**
in Electron 4  or  more newer
```
unknown cipher
```

in Electron 3.x , more older or  run alone by node cmd
```
 Cipheriv {
  _handle: {},
  _decoder: null,
  _options: undefined,
  writable: true,
  readable: true }  
```

**Comment by shiftkey** [comment]
@dessertboy which version of Node 10 are you testing on locally that works with your sample code? I ask because Electron 3 is based on Node 10.2 and Electron 4 is based on Node 10.11, so having more data points here about what works and what doesn't will help us troubleshoot the issue better...

**Comment by dessertboy** [comment]
> @dessertboy which version of Node 10 are you testing on locally that works with your sample code? I ask because Electron 3 is based on Node 10.2 and Electron 4 is based on Node 10.11, so having more data points here about what works and what doesn't will help us troubleshoot the issue better...

@shiftkey  I have tried v10.2.0 and v10.11.0 on locally with sample code in test.js ,  and execute the sample code  via node cmd.  As a result both versions can succeed
 If  I  run sample code in main.js via **Electron 4** that will fail.  but **Electron 3** is  ok.
 so  I don't think that is  Node10  version problem.

**Comment by shiftkey** [comment]
For reference, I checked the similar `crypto.getCiphers()` function on macOS (not Windows like the original reporter) in Electron `3.0.13` (135 listed):

<img width="814" src="https://user-images.githubusercontent.com/359239/50481989-d3978380-09ba-11e9-9a00-ae12ba78c230.png">

And then compared it to what's now in `4.0.0` (16 listed):

<img width="833" src="https://user-images.githubusercontent.com/359239/50481990-d3978380-09ba-11e9-90de-70a320efcc32.png">

**Comment by ca333** [comment]
confirm the above issue - seems the v4 incl. crypto module got "rid of" most hash funcs which breaks backwards compatiblity in our software.

**Comment by dessertboy** [comment]
@ca333  yes. That's it.

**Comment by shiftkey** [comment]
@dessertboy I'm not sure offhand. You'd have to look into how the Electron team are building and packaging Node into Electron - https://github.com/electron/node is the repository where that happens

**Comment by nornagon** [comment]
Also, as for the list of hashes, OpenSSL adds a lot of aliases to that list, so e.g. `RSA-SHA1`, `RSA-SHA1-2`, `sha1WithRSAEncryption` and `ssl3-sha1` are all aliases of `sha1`.

Digest algorithms present in OpenSSL that are not present in BoringSSL (decrepit or otherwise):
- mdc2 (aka RSA-MDC2, mdc2WithRSA)
- blake2 (its variants blake2b512, blake2s256)
- whirlpool

All the other elements in the list produced by `crypto.getHashes()` are just aliases.

**Comment by jasontlouro** [comment]
With Electron 3 (and OpenSSL rather than BoringSSL), 'aes256' was an alias for which cipher? In Electron 4, I have tried changing to aes-256-cbc, aes-256-ctr, aes-256-ecb, aes-256-ofb, and aes-256-xts. None of these have allowed me to achieve backwards compatibility with the version of my software that ran on Electron 3 (and used cipher aes256).

**Comment by jasontlouro** [comment]
Never mind. Was able to achieve compatibility using aes-256-cbc.

**Comment by nornagon** [comment]
Glad you found it! If you want to check the source, here's the list of aliases in the OpenSSL source: https://github.com/nodejs/node/blob/master/deps/openssl/openssl/crypto/evp/c_allc.c

**Comment by sirasistant** [comment]
Is it planned to add ripemd160 to electron from boringSSL? it is needed for some cryptocurrency-related libraries, like https://github.com/cryptocoinjs/hdkey/blob/master/lib/hdkey.js#L238

**Comment by pazaan** [comment]
Thanks @nornagon.

> That said, there is some precedent for BoringSSL adding support for less-commonly-used ciphers and cipher options via the `decrepit` module, for example [aes-128-cfb](https://boringssl.googlesource.com/boringssl/+/e64ef27cbe0b7bb06b748073f84eb83a2e5b505b).

Does this mean that these `decrepit` ciphers will be make available in a 4.x.y version of Electron? We use `crypto`'s `aes-128-cfb` cipher to communicate with a medical device.
So we'll either have to wait to upgrade to 4 until it's included, or include a `aes-128-cfb` module ourselves, which apparently gets really nasty in Windows.

**Comment by andreieftimie** [comment]
Can someone change the label? This doesn't only affect windows.

On macOS I see the same limited ciphers available as @pbca26 mentioned above:

```
> require('crypto').getHashes()
[ 'md4', 'md5', 'sha1', 'sha224', 'sha256', 'sha384', 'sha512' ]
```

**Comment by nornagon** [comment]
Closing this issue as all the ciphers/hashes mentioned here have been exposed (aes-{128,256}-cfb and ripemd160). If there are other ciphers or hashes you need, please open a new issue for the specific algorithm and we'll see what we can do.

**Comment by patwhite** [comment]
Are these ciphers going to be exposed in the 4 branch, or just 5? I'm on 4.0.8 and don't see RipeMD-160. Is there a way to patch to get it to work?

**Comment by nornagon** [comment]
ripemd160 is a digest, not a cipher. It's listed in `crypto.getHashes()` on versions >= 4.0.4.

**Comment by ontheroad1992** [comment]
Excuse me, will you support 'rmd160' in the follow-up?

> ripemd160是一个摘要，而不是一个密码。它列在`crypto.getHashes()`版本> = 4.0.4上。

Excuse me, will you support 'rmd160' in the follow-up?

**Comment by ontheroad1992** [comment]
> ripemd160是一个摘要，而不是一个密码。它列在`crypto.getHashes()`版本> = 4.0.4上。

Excuse me, will you support 'rmd160' in the follow-up?

**Comment by nornagon** [comment]
`rmd160` is an alias for `ripemd160`. We won't be adding additional aliases for ciphers that are already available.

**Comment by junderw** [comment]
@nornagon So every single app that uses rmd160 (keeping in mind that NodeJS crypto uses aliases) will have to dance around with try catches every time a user tries to use their library in Electron?

Just making sure.

```bash
$ node -e "console.log(require('crypto').getHashes().filter(v => v.indexOf('160') > -1))"
[ 'RSA-RIPEMD160', 'ripemd160', 'ripemd160WithRSA', 'rmd160' ]
```

**Comment by nornagon** [comment]
I'd recommend you just use `"ripemd160"` which is the canonical name and is supported on both Node.js and Electron. No need for a try/catch.

**Comment by junderw** [comment]
Ok, I'll use a try catch then.

Wouldn't want someone's app to break because of it, and bumping major version for a string change is silly.

**Comment by peterremote1980** [comment]
Is there any fix to this problem? thanks

**Comment by sschiessl-bcp** [comment]
> Is there any fix to this problem? thanks

Anything? We would also be very interested in a fix

**Comment by nornagon** [comment]
I've updated the title of this issue to refer to the initially-requested ciphers aes-256-cfb and aes-128-cfb. If you're having trouble with a different cipher, please open a new issue with the details of the problem you're experiencing.

**Comment by franzwilhelm** [comment]
@nornagon Thank you for some very clear answers in this thread! I'm in need of `aes-128-ccm`, not `cfb` for a project I'm currently working on. I don't really rely on having that installed into the electron binaries, if there's an easy way to polyfill the cipher into the crypto library included with the latest electron versions. How would I do such a thing? I'm currently relying on a package importing crypto through `require('crypto')`, and I need the cipher to be available through that import

**Comment by nornagon** [comment]
@franzwilhelm as requested in my previous comment, please open a new issue for new ciphers.

**Comment by PeterRao** [comment]
> Never mind. Was able to achieve compatibility using aes-256-cbc.

How did you solve it
