### ISSUE TITLE
After a page reload, goBack and goForward fire full reloads each time

### ISSUE THREAD

**Issue by lm-dp** [electron/electron#16204]
Tested from 3.x.x to 4.0.0

**Expected Behavior**
Triggering a reload after browsing should allow you to go back and go forward without having to reload the entire page. Should behave as it behave before reload.

**Actual behavior**
After browse and triggering a page reload, any time you go back or forward will trigger a full reload.

**To Reproduce**
Browse
Reload page
Use Back and Forward

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
