### ISSUE TITLE
About window.open in webview

### ISSUE THREAD

**Issue by xzycn** [electron/electron#16200]
The issue is #11471,yes,it's a long long time until now :)

In short: can't get window.opener in window/page opened with webview :(

I have found the muon that the fork version of electron with a description : 

> scriptable window.opener support

but, muon has some different api.
So, I want to know if the issue caused by **process model** could be solved :)
Merry Christmas!

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR.
