### ISSUE TITLE
error while loading shared libraries: libXss.so.1

### ISSUE THREAD

**Issue by joehonton** [electron/electron#16207]
* Output of `node_modules/.bin/electron --version`:
v4.0.0

* Operating System (Platform and Version):
Fedora Workstation 29

**Expected Behavior**
On a fresh installation of Fedora with Gnome Desktop, installation of Electron appears to install correctly with this command:
```
[root@fedora29 /]# npm install -g electron --unsafe-perm=true
```

**Actual behavior**
But attempting to start Electron fails:
```
 [root@fedora29 /]# electron
 /usr/lib/node_modules/electron/dist/electron: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
```
**Additional Information**
This closed issue from Atom provides the solution: https://github.com/atom/atom/issues/13176, which is to install libXScrnSaver.

```
[root@fedora29 /]# dnf install libXScrnSaver
```

**Comment by nornagon** [comment]
Electron depends on libXss to query idle time. Chrome has the same dependency. Installing libxscrnsaver is the right solution :)
