### ISSUE TITLE
Electron 4.0.0 slower in loading browser window

### ISSUE THREAD

**Issue by jrieken** [electron/electron#16210]
* Output of `node_modules/.bin/electron --version`: 4.0.0
* Operating System (Platform and Version): macOS 10.14.2

1. use Electron Fiddle
2. loading this gist https://gist.github.com/3d4909b7a1fc1664b962fb108de2d150
3. select version `3.0.13` and start/stop a few times. `pageLoad -> pageReady` takes around 250ms 🐎 
4. select version `4.0.0` and start/stop a few times. `pageLoad -> pageReady` takes around 430ms 🐌

**Comment by nornagon** [comment]
On my machine (macOS 10.13.6):

with `3.0.13`: pageLoad -> pageReady: 331ms (+221ms)
with `4.0.0`: pageLoad -> pageReady: 342ms (+255ms)

So still slower, but not nearly as much of a difference as you're observing.

It would really help if you could take a startup trace and add it to this issue! Run the app with `--trace-startup --trace-startup-file=/tmp/foo.json --trace-startup-duration=7` and upload the resulting trace here.

**Comment by jrieken** [comment]
@nornagon There you go:

[trace-3.0.13.json.txt](https://github.com/electron/electron/files/2723150/trace-3.0.13.json.txt)

[trace-4.0.0.json.txt](https://github.com/electron/electron/files/2723151/trace-4.0.0.json.txt)

**Comment by jrieken** [comment]
Also slower with `5.0.2`

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
