### ISSUE TITLE
c++ addon causes electron to freeze when using std::fstream in electron 4.0.0

### ISSUE THREAD

**Issue by DavidBurkett** [electron/electron#16228]
* Output of `node_modules/.bin/electron --version`: v4.0.0
* Operating System (Platform and Version): Windows 10 x86
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v2.0.2

**Expected Behavior**
std::fstream from within C++ native module (nodejs addon) would interact fine with the filesystem.

**Actual behavior**
Freezes when C++ native module (nodejs addon) attempts to use std::fstream. `_fsopen` works fine, but any usage of std::ifstream or std::ofstream will cause electron to whitescreen and freeze.

**Additional Information**
This was working before upgrading to electron v4.0.0

**Comment by felixrieseberg** [comment]
Hey @DavidBurkett! Thanks for the bug report – would you be able to add a simple repro (or even just a repro add-on)?

**Comment by DavidBurkett** [comment]
Sure, I'll try to get something together later this evening. It's 100% reproducible for me locally on multiple PCs though, and it's only when any call is made to std::fstream. Even simply declaring a std::ofstream, for example, without calling open() on it will still cause it to freeze. Also, running using node directly works perfectly (eg. `node test.js`), the issue only occurs when calling through electron.

**Comment by nornagon** [comment]
This might be related to #14617

**Comment by DavidBurkett** [comment]
Sorry I haven't created a repro yet, but I will. Under some tight deadlines, so I've just been using fopen as a workaround for now. atom-slack.herokuapp.com has been down for maintenance for a while now. Is there any other place I can chat with devs?

**Comment by nornagon** [comment]
Is your nodejs addon built with cmake-js (or any other non-`node-gyp` build system) by any chance?

**Comment by DavidBurkett** [comment]
Yes, cmake-js.

**Comment by nornagon** [comment]
Try adding this snippet to your CMakeLists.txt:

https://github.com/google/googletest/blob/01148677a937eae1c0fd1e488ca81445531ea368/googletest/cmake/internal_utils.cmake#L24-L38

```cmake
    foreach (flag_var
             CMAKE_C_FLAGS CMAKE_C_FLAGS_DEBUG CMAKE_C_FLAGS_RELEASE
             CMAKE_C_FLAGS_MINSIZEREL CMAKE_C_FLAGS_RELWITHDEBINFO
             CMAKE_CXX_FLAGS CMAKE_CXX_FLAGS_DEBUG CMAKE_CXX_FLAGS_RELEASE
             CMAKE_CXX_FLAGS_MINSIZEREL CMAKE_CXX_FLAGS_RELWITHDEBINFO)
      if (NOT BUILD_SHARED_LIBS AND NOT gtest_force_shared_crt)
        string(REPLACE "/MD" "-MT" ${flag_var} "${${flag_var}}")
      endif()
  endforeach()
```

**Comment by nthomas99** [comment]
Here's a pretty minimal repro built on top of electron quickstart:
https://github.com/nthomas99/electron-addon-fstream-repro

And this is with node-gyp, not cmake.

to build:
```console
cd fstream-addon
npm install
cd ../
npm install
npm start
``` 

Diff vs quickstart master:
https://github.com/nthomas99/electron-addon-fstream-repro/commit/c5f5668fa917b6c4ee9963c3034f130d1fa59ceb
 
@nornagon , I do think it is tied to https://github.com/electron/electron/issues/14617,  as changing:

 "RuntimeLibrary"  from 2 to 0 (i.e., /MD to /MT) makes it work just fine.

**Comment by nornagon** [comment]
yeah, the `RuntimeLibrary` setting there is causing the issue. It's not about cmake vs gyp per se, it's just that node-gyp links the static CRT by default while cmake-js links the dynamic CRT by default.

**Comment by codebytere** [comment]
@nornagon is there action we can take here or is the issue resolved insofar as the root issue doesn't lie with our code per se?

**Comment by nornagon** [comment]
I think we can close this out for now.
