### ISSUE TITLE
strange display when using electron with bootbox

### ISSUE THREAD

**Issue by dhanyn10** [electron/electron#16225]
* Output of `node_modules/.bin/electron --version`: 2.0.8
* Operating System (Platform and Version): Windows 10 Pro(not tested in other platform)

* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

### Expected behavior
there is no strange display when displaying modals with bootbox

### Actual behavior
there is a strange display when displaying modals with bootbox

### How to reproduce
```
  $ git clone https://github.com/dhanyn10/multiple-file-manager

  $ npm install
  $ npm start || electron .
```
- make a some duplicated file, just need around 20 file, you can copy and paste an empty documents in a same folder
- open this application
- browse to folder you've created that filled with duplicated file
- test with some features like a delete or other.
- press apply button
- on the modals that appear, try to scoll and hover over the list of your file
### Screenshots
![electron problem](https://user-images.githubusercontent.com/11478316/50572217-7140e780-0ded-11e9-817e-81b7d39ef9b7.png)

**Comment by dhanyn10** [comment]
update about how to reproduce:
```sh
$ git clone https://github.com/dhanyn10/multiple-file-manager
$ git checkout bootbox
$ npm install
$ npm start || electron .
```

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by dhanyn10** [comment]
the problem is gone, may i know which commit is fixed this issue?

**Comment by sofianguy** [comment]
reported as fixed
