### ISSUE TITLE
[macOS] Cycle through windows does not work until ~10s after application launch

### ISSUE THREAD

**Issue by tarngerine** [electron/electron#16226]
* electron v3.0.12
* macOS 10.12.6

**Expected Behavior**
Implementing what's shown on the [Menu documentation](https://electronjs.org/docs/api/menu), macOS default "Cycle through windows" behavior should be implemented and available immediately, allowing **"cmd + `"** and **"cmd + ~"** to cycle through available BrowserWindows.

**Actual behavior**
Default "Cycle through Windows" behavior is not available until ~10 seconds after application launch.
See video demo: https://www.dropbox.com/s/2shqlf8tulxdnur/Electron%20Cycle%20Windows%20Delay.mov?dl=0

**To Reproduce**
https://github.com/tarngerine/excelnotes/tree/cycle-bug
(Super barebones Electron app, just has a menu implemented.)
```sh
$ git clone https://github.com/tarngerine/excelnotes
$ git checkout cycle-bug
$ npm install
$ npm start
```
- Run app, starts with one window by default
- Create a new window with **"cmd + n"**, move it a little to see the two windows
- Press **"cmd + `"**

**Screenshots**
See video demo: https://www.dropbox.com/s/2shqlf8tulxdnur/Electron%20Cycle%20Windows%20Delay.mov?dl=0

**Additional Information**
I have not tested this on Windows.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
