### ISSUE TITLE
onBeforeSendHeaders: Can't add custom headers

### ISSUE THREAD

**Issue by divefox** [electron/electron#16233]
* Output of `node_modules/.bin/electron --version`: 1.6.7
* Operating System (Platform and Version): mac 10.13.4

I know there is a similar question [#4283](https://github.com/electron/electron/issues/4283).But it is not worked for me. Whether I write in the main process or render process. I can't set custom headers!

```javascript
const send=()=>{
    $.ajax({
        url: "http://localhost:9001/list",
        headers:{
            'myheader':'tst'
        }
    });
}
  
setInterval(() => {
    send()
}, 5000);


var electron = require('electron');

const filter = {
    urls: ['http://localhost:9001/*'],
};

const webcontent = electron.remote.getCurrentWebContents();

const ses = webcontent.session;
ses.webRequest.onBeforeSendHeaders(filter, (details, callback) => {
    details.requestHeaders['X-Test'] = 'test';
    
    // const requestHeaders = Object.assign(details.requestHeaders,{
    // ['X-Test']: 'test'
    // })

    console.log(requestHeaders)
    callback({ cancel: false, requestHeaders: details.requestHeaders });
});

```
the screen shot is below

![image](https://user-images.githubusercontent.com/2367779/50589473-b5052100-0ec1-11e9-8656-1bbb8c0d936a.png)

Could someone know how to fix it ?
Thank you very much!

**Comment by MarshallOfSound** [comment]
As mentioned in your linked issue, you can't do it like this from the renderer process.  You need to create a new object when calling back with `requestHeaders`, not mutate the original

**Comment by divefox** [comment]
> As mentioned in your linked issue, you can't do it like this from the renderer process. You need to create a new object when calling back with `requestHeaders`, not mutate the original

@MarshallOfSound Thank you for you reply!
I can't catch you. What do you mean of "You need to create a new object when calling back with requestHeaders"?  Is there have some example? Or where my code is wrong?

**Comment by divefox** [comment]
@MarshallOfSound Thank you! It's my fault. I confuse the render process and main process.What I do is always in the render process.So it is not work always.
