### ISSUE TITLE
New setSpellCheckProvider api

### ISSUE THREAD

**Issue by chrismohr** [electron/electron#16237]
I'm looking forward to using the api updates to `setSpellCheckProvider` that were added by @nitsakh in this pull request.
https://github.com/electron/electron/pull/14032

I see that they've been merged to master, but are not yet in a release.  What is the process by which they make it to a release?  Is there anything I might be able to do to help?

**Comment by nornagon** [comment]
We'll be cutting the first Electron 5 nightlies soon, nothing much you can do to make it go faster at this point :)
