### ISSUE TITLE
install a 3rd party driver with electron

### ISSUE THREAD

**Issue by shrimpairship** [electron/electron#16231]
Hi, guys. I am a new electron developer.
I am developing an app that controls robot with electron and node-serialport.
My question is: the robot's chip require a 3rd party driver. In order to communicate properly, this driver must be installed. 
So is there any way in my electron app to excute this driver installer? 
I can package this driver in my electron as a buildResources, but I don't konw how to excute it.

**Comment by felixrieseberg** [comment]
Generally speaking, Electron can execute whatever native code you need. In your rather unique case, you might want to make use of [Node's `child_process` capabilities](https://nodejs.org/api/child_process.html). 

Whatever manual steps you'd usually take to install your driver - if you can automate them in any language, Electron can probably run them for you.
