### ISSUE TITLE
Electron 4 native node_modules break apps on CentOS or RHEL 7.6 (CXXABI_1.3.9 not found)

### ISSUE THREAD

**Issue by bengotow** [electron/electron#16247]
* Output of `node_modules/.bin/electron --version`:4.0.0
* Operating System (Platform and Version): CentOS and Red Hat Enterprise Linux 7.6

In previous builds of Electron (2.0.14), Linux builds created on Travis CI (Ubuntu 14.04 Trusty) would work on CentOS and RHEL. When using Electron 4, requiring native node modules in the built/packaged application results in the following console error on these platforms:

```
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/share/mailspring/resources/app.asar.unpacked/node_modules/@paulcbetts/spellchecker/build/Release/spellchecker.node)
    at process.module.(/usr/share/mailspring/resources/app.asar/static/anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722)
    at Object.module.(/usr/share/mailspring/resources/app.asar/static/anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602)
    at tryModuleLoad (internal/modules/cjs/loader.js:541)
    at Function.Module._load (internal/modules/cjs/loader.js:533)
    at Module.require (internal/modules/cjs/loader.js:640)
    at require (internal/modules/cjs/helpers.js:20)
    ...
```

This is creating a good bit of support noise and I'm trying everything I can think of to narrow it down. Using the exact same Travis environment and changing ONLY the Electron version is enough to trigger the problem. It's not related to a particular native node module — Mailspring has several and this error is produced when requiring all of them. (In this diff, the left side works and the right side does not: https://github.com/Foundry376/Mailspring/compare/200b57d86bb...2bed8786b468)

I think the crux of the problem is that /something/ is using new C++ features that require `CXXABI_1.3.9`, and the modules are being compiled against(?) that C++ version. The distros only support older C++ ABI versions and are unable to dyload the libraries. 

After lots of Googling it seems the general consensus is that you can't just "install" a new CXXABI version on a host machine—it needs to be available for that distro? The oddest part of this is that Electron itself works on these platforms, it's just the native node modules that are broken.

Related: https://github.com/Foundry376/Mailspring/issues/1292

**Comment by bengotow** [comment]
Turns out this was my fault after all, but I'm still not entirely sure what changed with Electron 4.

My Travis CI configuration needed to compile some C++ unrelated to my native node modules, so I was installing `gcc++5` and setting `CC=gcc-5 CXX=g++-5`. I changed the build script so that it builds the native node modules and THEN upgrades gcc, changes the env vars, and builds the other project and now it runs fine on RHEL 7.6.

Still odd that this worked fine with Electron 2.x.

**Comment by nornagon** [comment]
Electron builds with custom sysroots (which feature it inherits from Chromium).

Electron 4 is built with libstdc++6 v8.2.0-7:
```
$ curl -sL http://s3.amazonaws.com/gh-contractor-zcbenz/toolchain/227023dae63c074376c4399a6039f93ae3dd426d/debian_sid_amd64_sysroot.tar.xz | tar xO debian/libstdc++6/DEBIAN/control
Source: gcc-8
Version: 8.2.0-7
[...]
```

Electron 2 is built with libstdc++6 v6.3.0-18:
```
$ curl -sL http://s3.amazonaws.com/gh-contractor-zcbenz/toolchain/02772eaba5440a79c6bd2d9cb7e42fa836950366/debian_stretch_amd64_sysroot.tgz | tar xO debian/libstdc++6/DEBIAN/control
Source: gcc-6
Version: 6.3.0-18
[...]
```

I suspect that's the root cause of the issue you saw :)

**Comment by slorenzo** [comment]
Hi @bengotow @nornagon.

I'm facing the same issue on my app. The build process is a bit different because I'm not using a CI environment. Instead of that, I'm using a Docker to recreate a Linux environment and avoid issues related to native modules.

I'm using this Docker Image: `https://github.com/electron-userland/electron-builder/blob/master/docker/base/Dockerfile` which uses `gcc-multilib` and `g++-multilib`. I think, both libraries are built to avoid this kind of issue.

For unknown reasons, the app shows the same error @bengotow had previously.

Is there any workaround? Thanks in advance.
