### ISSUE TITLE
system color API for macOS

### ISSUE THREAD

**Issue by jmarquis** [electron/electron#16246]
It would be great to add macOS support to the [`systemPreferences.getColor` method](https://github.com/electron/electron/blob/master/docs/api/system-preferences.md#systempreferencesgetcolorcolor-windows) to allow electron apps to fetch the [system colors](https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/color#system-colors) and [dynamic system colors](https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/color#dynamic-system-colors). This would be a pretty big deal for apps that are trying to fit in with the OS, especially since the colors change depending on several factors and Apple strongly discourages hardcoding them:

>**Don't hard code system color values in your app.** The color values provided below are intended for reference during your app design process. The actual color values will fluctuate from release to release, based on a variety of environmental variables. Always use the API to apply system colors.

>**Don't try to replicate dynamic system colors.** Dynamic system colors—some of which may be patterns—fluctuate from release to release, based on a variety of environmental variables. Instead of trying to create custom colors that match the dynamic system colors, use the dynamic system colors.

I am very unfamiliar with how most of this stuff works, but based on the docs I linked it seems like this could be a relatively simple interface to NSColor...?

**Comment by codebytere** [comment]
@jmarquis this is in flight now, and should be merged by the end of this week!

**Comment by jmarquis** [comment]
Amazing! Thanks for taking this on @codebytere — it means a lot for a project I'm working on and hopefully many others in the future. I looked at your PRs and the new APIs look great to me.

Random question that I just thought of: since these colors are subject to change based on user settings and other OS-level things, do you think there's a canonical way to detect when an app should re-query for new color values? I feel like listening for a few events via `systemPreferences.subscribeNotification` might do the trick, but I'm not sure which ones could indicate a change to a system color.
