### ISSUE TITLE
Electron 4.0.0 - webview.capturePage returns empty object.

### ISSUE THREAD

**Issue by wjhir** [electron/electron#16241]
* Output of `node_modules/.bin/electron --version`: 4.0.0
* Operating System (Platform and Version): Windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 3.0.13

**Expected Behavior**
[`webview.capturePage(callback)`](https://electronjs.org/docs/api/webview-tag#webviewcapturepagerect-callback) should invoke the callback with a NativeImage.

**Actual behavior**
`webview.capturePage(callback)` invokes the callback with an empty/plain object.

**To Reproduce**
See [this gist](https://gist.github.com/wjhir/c8cb4497c9c2ce2ec4d0262b285584eb#file-renderer-js).

**Additional Information**
`webview.getWebContents().capturePage(callback)` still works as expected.

**Comment by Tinysymphony** [comment]
+1

**Comment by zachbeasley** [comment]
+1

**Comment by michalzaq12** [comment]
+1

**Comment by thecorsair** [comment]
+1

**Comment by ksullivan91** [comment]
+1

**Comment by vsanse** [comment]
I have same issue but webview.getWebContents().capturePage(callback) also results in empty object for me.
