### ISSUE TITLE
[Windows][Backtrace] getLastCrashReport() returns a corrupt id

### ISSUE THREAD

**Issue by mzanfirescu** [electron/electron#16250]
* Output of `node_modules/.bin/electron --version`: v2.0.12
* Operating System (Platform and Version): win32 Microsoft Windows 10 Pro
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
Calling `require('electron').remote.crashReporter.getLastCrashReport().id` on windows I expect to get a similar response: `"{"response":"ok","_rxid":"77010000-73b5-d001-0000-000000000000"}
"`
**Actual behavior**
Calling  `require('electron').remote.crashReporter.getLastCrashReport().id` on windows returns `"{"response":"ok""`

**To Reproduce**
Run `require('electron').remote.crashReporter.getLastCrashReport().id` on windows

**Comment by konraddysput** [comment]
Hey @mzanfirescu. Can you please show us how you start your CrashReporter handler? 
Did you integrate your application with 3rd parties hosted solutions? 
Do you have the same behavior in main process?

**Comment by mzanfirescu** [comment]
@konraddysput 

1. This is how I start crashReporter.

`
const {crashReporter} = require('electron');

const options = {
  "companyName": "myCompany",
  "extra": {
    "buildType": "development",
    "version": "1.0.0"
  }
  "productName": "myProduct",
  "submitURL": "https://submit.backtrace.io/{{myCompany}}/{{token}}/minidump", // or 'https://mycompany.sp.backtrace.io:6098/post?format=minidump&token={{token}}',
  "uploadToServer": true
}

crashReporter.start(options);`

2. The application is integrated with Backtrace. (https://help.backtrace.io/integration-guides/application-frameworks/electron-integration-guide)
3. I have the same behavior also in the main process.

**Comment by konraddysput** [comment]
Can you please provide electron package version? This behavior works on your development  environment or in production?

**Comment by mzanfirescu** [comment]
@konraddysput  
Do you mean the electron-packager version? 
   ```
 "electron": "2.0.12",
    "electron-builder": "20.15.1",
    "electron-connect": "0.6.3",
    "electron-devtools-installer": "^2.2.4",
    "electron-installer-dmg": "^0.2.1",
    "electron-packager": "11.2.0",
    "electron-rebuild": "1.7.3",
    "electron-winstaller": "2.7.0",
```
It doesn't work nor development or production.

**Comment by sbahra** [comment]
@mzanfirescu This will be resolved shortly. The Electron reporter is expected the identifier returned in a different format in order for extracting last identifier to work.

We will keep you posted as the deployment of the update happens.

**Comment by eyardeni** [comment]
@sbahra any update on this fix please?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by konraddysput** [comment]
Hey. This issue is fixed on Backtrace side

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
