### ISSUE TITLE
No longer able to proxy wheel event out of webview using preload

### ISSUE THREAD

**Issue by buffet-time** [electron/electron#16255]
* Output of `node_modules/.bin/electron --version`: 4.0.0
* Operating System (Platform and Version): Windows 10 Enterprise x64 - 1709
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 3.0.9

**Expected Behavior**
The ability to proxy out wheel events from webview in a preload script. Example: 
```
document.addEventListener('wheel', event => {
  ipcRenderer.sendToHost(
    'wheel',
    event.deltaX,
    event.deltaY,
    event.altKey,
    event.ctrlKey,
    event.shiftKey
  )
})
```

**Actual behavior**
The event listener never is hit and thus can't proxy out the event from the webview. This was working in every version of 3.X.X that i had used before updating to 4.0.0

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
