### ISSUE TITLE
electron Build windows not getting full screen (workAreaSize,workArea,maximize) not working

### ISSUE THREAD

**Issue by ervijjusty** [electron/electron#16263]
* Operating System (Windows 10.1):
I'm using angular 6 with an electron. when I'm compiling the windows build the build not getting full screen. I'm changing the method in main.ts is a work area, WorkAreaSize etc not it's also not working

![screenshot 224](https://user-images.githubusercontent.com/17564766/50677926-67ec9080-1022-11e9-951f-e18ef5ea2508.png)

**const electronScreen = screen;
const size = electronScreen.getPrimaryDisplay().workAreaSize;
console.log(size);
win = new BrowserWindow({
x: 0,
y: 0,
width: size.width,
height: size.height,

icon: __dirname + '/icon.ico',
resizable:false,
webPreferences: {
 nodeIntegration:true,
 webSecurity: false,
 plugins: true
 },
});**

**Expected Behavior**
full screen for production build

**Actual behavior**
Not getting in the full work area

**Comment by doom-fr** [comment]
I have notice that if I do not use `resizable:false`, it works as expected, and surprisingly it is nevertheless unresizable.
I have tested it in electron 2.0.16, the last version that works well with transparency.
Try and let us know.

And maybe it is better to use `workArea` instead of `workAreaSize` to have the good position.

**Comment by ervijjusty** [comment]
@nornagon I'm     "electron": "3.0.8" using this version

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
