### ISSUE TITLE
Renderer process leaking in 3.x and 4.x on Windows 10 1803

### ISSUE THREAD

**Issue by ventsislav-georgiev** [electron/electron#16266]
The renderer process leaks sporadically from version 3.x onward. The most consistent reproduce I could manage is by using Karma to launch Electron and load a big in size javascript file. No tests are actually required, Karma just starts and quits and one Electron process is left running with busy looping.

### To Reproduce
https://github.com/ventsislav-georgiev/electron-quick-start
```sh
$ git clone https://github.com/ventsislav-georgiev/electron-quick-start.git
$ npm install
$ npm start
```
In case there are no leftover process from the first try, just run `npm start` again a couple of times.

Screencast of `npm start`: https://www.screencast.com/t/eNXFU5Q12f7F
Screencast of the leaking process: https://www.screencast.com/t/7ztiJxb4bz
**Note**: Karma is expected to throw an error as there are no tests configured.

### Screenshots
**v4.0.0** - Threads of the leaked process
![image](https://user-images.githubusercontent.com/5616486/50640554-e1767700-0f6d-11e9-81b9-004ca7756bdf.png)

**v3.0.13** - Threads of the leaked process
![image](https://user-images.githubusercontent.com/5616486/50640642-1a165080-0f6e-11e9-9e00-e807e93008de.png)

### Additional Information
The issue is not reproducible in Electron 2.x versions.
Also the issue is not reproducible on Linux and on MacOS.

**Comment by haroldiedema** [comment]
I think this is the same issue where you hit CTRL+C on the command line in windows (using git bash) to terminate an electron app that has one or more browser windows open.

A child process will be stuck there eating up one cpu core that you have to kill manually. I haven't found a consistent way to reproduce this, but AFAIK this issue doesn't seem to occur in 4.x, for as far as I've been using it.

**Comment by ventsislav-georgiev** [comment]
@haroldiedema My experience is that all versions leak a process in 3.x and 4.x. Could you try the repro I did with Karma and see if the process is leaked also in Electron 4.x?

**Comment by ventsislav-georgiev** [comment]
The issue seems to be fixed in Electron v5.
