### ISSUE TITLE
Custom inset amount for traffic light buttons 🚥 on MacOS

### ISSUE THREAD

**Issue by erusev** [electron/electron#16265]
Some MacOS apps, like Spark Mail, use custom positions for their traffic light buttons. Here's a screenshot from Spark Mail where traffic light buttons are further from the top left corner compared to most MacOS apps:

![image](https://user-images.githubusercontent.com/184170/50684883-ca905d00-101f-11e9-9c39-bd4c3cde44ad.png)

For comparison, here's Notes:

![image](https://user-images.githubusercontent.com/184170/50685238-11cb1d80-1021-11e9-8d5a-66b3c4589390.png)

It'd would be great if this could be achieved in Electron as it would allow for better aligned designs.

**Comment by MarshallOfSound** [comment]
Duplicate #8237
