### ISSUE TITLE
npm start run well, by launch by 'electron .' raise error "TypeError: win.loadFile is not a function"

### ISSUE THREAD

**Issue by code-brewer** [electron/electron#16289]
Hi, everybody.
   It is just a simple hello-world project. Is it wrong way to run 'electron .' command from project root?
  
   My electron version is 1.7.9 and on Mac OS X EI Capitan.

➜  my_helloworld electron -v
v1.7.9

And part of my package.json is:
```
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "test": "echo \"Error: no test specified\" && exit 1",
         ...
  },
```
and main.js like this:
```
const { app, BrowserWindow } = require('electron')
     ...
  win = new BrowserWindow({ width: 800, height: 600 })
  win.loadFile('src/index.html')
```

**Comment by MarshallOfSound** [comment]
> My electron version is 1.7.9

The loadFile method was not available in 1.7.x, update to latest (4.0.0) to get all APIs

**Comment by code-brewer** [comment]
Thank for your reply, i will upgrade my electron. What i don't understand is why run 'electron .'  failed while 'npm start' run well.

**Comment by code-brewer** [comment]
Thank for your reply. I find that there was a local installed electron of version 2.0.xx, that why 'npm start' work
