### ISSUE TITLE
Offscreen Rendering broken on Windows

### ISSUE THREAD

**Issue by stba42** [electron/electron#16288]
* Output of `node_modules/.bin/electron --version`:  v4.0.1
* Operating System (Platform and Version): Windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v3.0.14

**Expected Behavior**
The 'paint' event is fired several times when implementing the example from:
https://electronjs.org/docs/tutorial/offscreen-rendering

**Actual behavior**
The 'paint' event of webContents is never fired

**To Reproduce**
On Windows:
```
$ git clone https://github.com/stba42/electron-quick-start -b master
$ npm install
$ npm start
```

**Additional Information**
Btw. Quickstart is still using electron v3

**Comment by casabian** [comment]
I experience the same issue on Linux and for Electron v4.1.1.

Are there any info regarding a fix?

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
