### ISSUE TITLE
Accelerators not showing in popup menu for items with `role`

### ISSUE THREAD

**Issue by MayaWolf** [electron/electron#16291]
* Output of `node_modules/.bin/electron --version`:
Confirmed on both `v3.0.14` and `v4.0.1`.
* Operating System (Platform and Version):
Windows 10

### Expected behavior

Accelerators should be shown for items with a `role` when using `menu.popup({})`

### Actual behavior

Accelerators are shown for all menu items only when in the title bar.
When the menu is opened as a popup, only explicitly defined accelerators are shown, not ones defined by `role`.

### How to reproduce

The easiest way might be to check out [electron-quick-start](https://github.com/electron/electron-quick-start) and add `Menu.getApplicationMenu().popup({});` at the end of `createWindow`. Menu items that only have a defined `role` will not display their accelerators, but those with custom accelerators will.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by MayaWolf** [comment]
Still happens in Electron 8, just confirmed it.

**Comment by codebytere** [comment]
Unfortunately this is a byproduct of Chromium and not something we're currently capable of fixing, as it would entail assuming more maintenance burden for Menus than we feel comfortable assuming. As such, i'm going to close this as a `wontfix`, but should something change i'm happy to look further.
