### ISSUE TITLE
I have to add   target: 'node' in webpack.config.js to let ipcRender work

### ISSUE THREAD

**Issue by hugetiny** [electron/electron#16295]
after I import {ipcRenderer} from 'electron' in renderer
I have to add   
```
target: 'node' 
```
in webpack.config.js to let ipcRenderer work.
but there comes warning:
```
Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.
 
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.
```
How can i solve this?

node:10.13.0
os:MacOS 10.13.6

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
