### ISSUE TITLE
Cookies with same name are duplicated

### ISSUE THREAD

**Issue by antelle** [electron/electron#16292]
* Output of `node_modules/.bin/electron --version`: `v3.0.7`
* Operating System (Platform and Version): macOS Mojave 10.14.2, `Darwin 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64`
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): n/a

**Expected Behavior**
Imagine there are two cookies with the same name on the same domain and path:
1. manually set using Cookies object
2. set by server

I would expect the second cookie to replace the first one when it's received from server.

**Actual behavior**
Both cookies are sent in the same request.  
Request header:
```
Cookie: MyCookie=1; MyCookie=2
```
Cookies seen by electron (note the difference in `domain`):
```js
require('electron').remote.session.defaultSession.cookies.get({}, (e,c) => console.log(JSON.stringify(c, null, 2)))
[
  {
    "name": "MyCookie",
    "value": "1",
    "domain": ".localhost",
    "hostOnly": false,
    "path": "/",
    "secure": false,
    "httpOnly": true,
    "session": true
  },
  {
    "name": "MyCookie",
    "value": "2",
    "domain": "localhost",
    "hostOnly": true,
    "path": "/",
    "secure": false,
    "httpOnly": false,
    "session": true
  }
]
```

**To Reproduce**
1. set a cookie using `electron.remote.session.defaultSession.cookies.set`
2. go to a website which gives you the same cookie with another value in response
3. send another request to this website
4. check cookies in the last request

https://github.com/antelle/electron-quick-start

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone https://github.com/antelle/electron-quick-start
$ npm install
$ npm start || electron .
```

After this, wait for 2-3 seconds.
Please note: it will try to start a server on port `80` and then navigate to `http://localhost`. If it's not possible, most likely there will be an error.

**Screenshots**
`Cookie` header is displayed on this screenshot:
<img width="420" alt="screen shot 2019-01-06 at 22 21 07" src="https://user-images.githubusercontent.com/633557/50741717-63ca9980-1201-11e9-8448-964aa1284686.png">

**Additional Information**
Browsers should send one cookie, not two of them.  
In real life, it results in ["We've detected a problem with you cookie settings"](https://user-images.githubusercontent.com/20073334/49846238-50f6ad80-fd98-11e8-87f3-dd9f1cb295ff.png) screen returned by Google.

**Comment by cuixiping** [comment]
Two cookies with same name may be different when they have different domain, path,etc.
Check these fields of the two cookies.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
