### ISSUE TITLE
A JavaScript error occurred in the main process Uncaugth Exception: Error:spawn（There is an error in upgrading the app on the win10 system.）

### ISSUE THREAD

**Issue by Mrliu1102** [electron/electron#16294]
Our app has an error in the version upgrade，electron-- -v3.0.2

A JavaScript error occurred in the main process Uncaugth Exception:
Error:spawn
C:\Users\***\AppData\Roming\ISUPClient\installer-1.0.5.exe
EACCES
   at Process.ChildProcess._handle.onexit(internal/child_process.js:229:19)
  at onErrorNT(internal/child_process.js:406:16)
  at process._tickCallback(internal/process/next_tick.js:63:19)

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by Mrliu1102** [comment]
* Output of `node_modules/.bin/electron --version`:3.0.2
* Operating System (Platform and Version):win10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
A clear and concise description of what you expected to happen.
I expect to be able to install the upgrade package normally silently after the test download installation package is successful
**Actual behavior**
A clear and concise description of what actually happened.
When I click Upgrade Now, the error cartridge pops up, and the error description is as described as the problem
**To Reproduce**
Your best chance of getting this bug looked at quickly is to provide a REPOSITORY that can be cloned and run.

You can fork [electron-quick-start](https://github.com/electron/electron-quick-start) and include a link to the branch with your changes.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone $YOUR_URL -b $BRANCH
$ npm install
$ npm start || electron .
```
**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional Information**
Add any other context about the problem here.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
