### ISSUE TITLE
Feature: Allow getting userData path of another instance

### ISSUE THREAD

**Issue by t57ser** [electron/electron#16302]
**Is your feature request related to a problem? Please describe.**
Following use case: Imagine an app that allows various user profiles that can be set via a json file or some other way.
During start the profile will be read and userData folder is set to a specific path.
Now when a second instance is started I can only know whether or not I am the primary instance.
There is no way to get information of the primary instance if I am not it.
So assuming that the other instance is using another userData path, I do not want to close my secondary instance.

**Describe the solution you'd like**
It would be good to be able to get the userData path of the primary instance.

**Describe alternatives you've considered**
This could be solved by creating some kind of file and reading it during start and doing some handling..
but this is sort of dangerous/complicated and comes with various down sides. I.e if the app crashes or shuts down for some reason and doesn't clean the file properly etc...

**Comment by codebytere** [comment]
Given that this has been open for years, that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!
