### ISSUE TITLE
v4: MenuItems with roles default registerAccelerator to false, breaking all default shortcuts

### ISSUE THREAD

**Issue by pimterry** [electron/electron#16303]
* Output of `node_modules/.bin/electron --version`: v4.0.1
* Operating System (Platform and Version): Ubuntu 18.04

**Expected Behavior**
The default keyboard shortcuts for menu item roles should be registered (except in special cases where they're handled elsewhere - cut/copy/etc).

**Actual behavior**
As of v4, the keyboard shortcuts for any menu item with a role are not registered by default.

**To Reproduce**
In a v4 electron app, adding the below menu item will show a Ctrl/Cmd+R accelerator in the menu, but won't actually register it, so it won't work:

```
{
  role: 'reload'
}
```

this menu item does work:

```
{
  role: 'reload',
  registerAccelerator: true
}
```

I think this is caused by https://github.com/electron/electron/pull/15723, specifically https://github.com/electron/electron/blob/a1a431eb8735ed677b2ba980ef77549230c6363b/lib/browser/api/menu-item-roles.js#L256-L258

I.e. `registerAccelerator` defaults to `true` only if there's no role for the menu item. If there is a role set, it instead uses the `registerAccelerator` setting for that role, but for almost all roles this is `undefined`.

**Comment by codebytere** [comment]
Ah, thanks for pointing this out! i'll see what can be done about it 😀

**Comment by codebytere** [comment]
@pimterry a fix is in flight, it should go out with the next `4-0-x` patch release i would guess
