### ISSUE TITLE
Window.history.state not retained after browser refresh.

### ISSUE THREAD

**Issue by ccorcos** [electron/electron#16306]
* Output of `node_modules/.bin/electron --version`: v3.0.0, v2.0.16
* Operating System (Platform and Version): MacOS 10.13.6

When you add state to `window.history`, e.g. `window.history.replaceState({x:1}, undefined, window.location.href)`, then you should expect to see that state after you refresh `console.log(window.history.state)`.

If you open `index.html` inside chrome and press the next button a few times, you'll see the history state logged to the console. When you refresh, you should see the state continue counting where it left off. However if you use this file in the electron app using `npm start`, you'll notice that refreshing the page clears the history state.

**To Reproduce**

```sh
git clone git@github.com:ccorcos/electron-history-state-bug.git
cd electron-history-state-bug
npm install
npm start
```

**Additional Information**

I found an issue from 3 years ago but the problem is not solved and I've provided a minimal reproduction: https://github.com/electron/electron/issues/1249

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by geigerzaehler** [comment]
I’m still seeing this issue on v12.0.2.
