### ISSUE TITLE
Memory Leak when using Affinity

### ISSUE THREAD

**Issue by erik-ciq** [electron/electron#16319]
* Output of `node_modules/.bin/electron --version`: v4.0.1
* Operating System (Platform and Version): Windows 10 Home v1803

**Expected Behavior**
Not leak memory when using `affinity`

**Actual behavior**
Memory leak only when using `affinity`

**To Reproduce**
`git clone git@github.com:erik-ciq/electron-affinity-leak.git`
`cd electron-affinity-leak && npm install`
`npm run leak`

Repo readme has more details.

**Screenshots**
![image](https://user-images.githubusercontent.com/45185091/50848959-8a382400-132a-11e9-8ab7-8f70da46e8b0.png)

![image](https://user-images.githubusercontent.com/45185091/50814156-8de98d80-12cd-11e9-9598-e2a922a24657.png)

**Additional Information**
Only requires a single browser window, with affinity, and using location.reload to refresh. Leaks ~ 1.5Mb of memory in renderer process each time. You can run `npm start` to run the same code _without_ affinity prop set. You'll see that there is no leak. The leakage only occurs with affinity.

The repo provided also takes heap snapshots at each interval, and provides additional memory usage data if needed.

Probably the base case of https://github.com/electron/electron/issues/12027

There are many similar issues reported in chromium, but it _seems_ like they are related to context leaking from a child iframe into a parent window (causing a strong reference that prevents the iframe from being garbage collected). Here are some links around this for posterity:

https://bugs.chromium.org/p/chromium/issues/detail?id=529941
https://bugs.chromium.org/p/chromium/issues/detail?id=852408
https://bugs.chromium.org/p/chromium/issues/detail?id=270000
https://bugs.chromium.org/p/chromium/issues/detail?id=609137

I also tried to reproduce in chrome using iframes, but it seems like it's only electron:

https://www.bryntum.com/blog/debugging-memory-leaks-in-web-applications-using-iframes/

Using the gist below, you can cause the chromium leak by holding a reference from the child iframe in the parent window. You can "fix" the leak by removing this reference.
[Reproduce chromium iframe leak gist](https://gist.github.com/ilann/3939658)

Given that I was able to "remove" the iframe leak by removing the child reference in the parent (from the gist), and given running the repo I created for electron _without_ affinity does not seem to leak, it points towards this being an issue with the affinity implementation in electron. 

Diff from electron-quick-start: https://github.com/erik-ciq/electron-affinity-leak/pull/1/files#diff-7a9076d6d94e62c13d641aa71f19ae8eR63

@emmkimme any ideas on what might cause this? Not sure if this is a regression or has existed since https://github.com/electron/electron/pull/11501

**Comment by erik-ciq** [comment]
I was able to add the `process.getHeapStatistics` function into electron 2.0.0-beta.1 and confirm that this is not a regression, and has been there since affinity was added.

**Comment by erik-ciq** [comment]
Comes from: https://github.com/electron/electron/blob/master/atom/renderer/atom_renderer_client.cc#L154 . Will investigate.

**Comment by jaehayoo** [comment]
Is there any update?

This issue is same in 3.x 2.x

We are developing the application which have many game sub windows. This app's sub windows will be frequently closed and opened by users.
So, This issue is so so super important for us.
Please patch the memory leak issue about using affinity.

Thanks,

**Comment by jaehayoo** [comment]
So, Is there any update?

**Comment by erik-ciq** [comment]
@MarshallOfSound you mentioned some work on this issue related to a PR you were developing. Is there any status update on that PR?

**Comment by erik-ciq** [comment]
Tested on a build of `5-0-x` branch with `nodeIntegrationInSubFrames: true` in BrowserWindow `webPreferences`. Fixes the leak. Would be nice to have the leak fixed in code paths where `nodeIntegrationInSubFrames: false`.

![image](https://user-images.githubusercontent.com/45185091/57260056-e1b77980-7016-11e9-83a7-5d15f82f84b6.png)

**Comment by erik-ciq** [comment]
@MarshallOfSound are there plans to incorporate this todo into a release? https://github.com/electron/electron/commit/0890b0ca8e85f154cacefdc2e18229cd7491f76f#diff-0cdfa12fff513e022fac830c6af9c19aR160 will la

**Comment by MarshallOfSound** [comment]
@erik-ciq To be honest, my current personal thinking is `affinity` should be removed from the code base.  That TODO will eventually reach other code paths but it will take a long time.  I have a plan for this stuff that I'll be posting as a discussion issue some time this week.

**Comment by emmkimme** [comment]
@MarshallOfSound, Hi, this feature is used in our released flagship product. Our product is managing a hundred of pages, Be able to gather some of them in a single process, save memory and prevent to reach the limit of number of processes in Chromium, this is critical for us. We can add the 'Experimental' flag on this feature to mitigate the usage. Thanks

**Comment by MarshallOfSound** [comment]
@emmkimme Are those hundreds of pages on the same origin?  The goal here is to just enable the same process model as Chromium.  Maybe I'm missing your use case here, but at least in my mind there is no reason to change from Chromiums process model if we restore that (same origin will be in the same process).  It sounds like what you want is a clean way to use [Process Per Site](https://www.chromium.org/developers/design-documents/process-models)

See #18397 for the plans to restore Chromiums process model.

Please note that we haven't even discussed affinity or potentially removing it, what I mentioned above was entirely my opinion not a direction of the project 👍 It just so happens that removing the patches mentioned in that post would also remove the affinity patches.

**Comment by emmkimme** [comment]
we can not use the process-per-site option as all our pages have the same origin (domain of the company)

**Comment by MarshallOfSound** [comment]
@emmkimme Noted, but my opinion still stands.  I'll raise this at the next WG meeting

**Comment by thorsent** [comment]
Love affinity, but I think process-per-site for us would address the memory leak in our most common use case. I think the ability to set the process model with a command line switch would be useful.

I wonder if process-per-tab provides a path to affinity-like behavior for @emmkimme's situation?

**Comment by Xylobol** [comment]
> @MarshallOfSound, Please, this feature is used in our released flagship product. Our product is managing a hundred of pages, Be able to gather some of them in a single process, save memory and prevent to reach the limit of number of processes in Chromium, this is critical for us. We can add the 'Experimental' flag on this feature to mitigate the usage. Thanks

I'd like to second the `Experimental` flag. In a project I'm working on, we're also using affinity quite extensively. Removing it would almost definitely result in us completely forking Electron to keep the feature (we already have an in-house fork for simpler things).

**Comment by cynx** [comment]
> > @MarshallOfSound, Please, this feature is used in our released flagship product. Our product is managing a hundred of pages, Be able to gather some of them in a single process, save memory and prevent to reach the limit of number of processes in Chromium, this is critical for us. We can add the 'Experimental' flag on this feature to mitigate the usage. Thanks
> 
> I'd like to second the `Experimental` flag. In a project I'm working on, we're also using affinity quite extensively. Removing it would almost definitely result in us completely forking Electron to keep the feature (we already have an in-house fork for simpler things).

@MarshallOfSound  I second this as well. we have use-case to open multiple windows and using affinity is performant.

**Comment by erik-ciq** [comment]
![image](https://user-images.githubusercontent.com/45185091/63968044-8f7de680-ca53-11e9-8580-be0d4db5531c.png)

Worth noting that any objects defined in the context for a window with affinity will also leak. I updated the `leak` branch of `git@github.com:erik-ciq/electron-affinity-leak.git` to include a large string in the `renderer.js` file.

**Comment by erik-ciq** [comment]
I added some additional command line flags to `git@github.com:erik-ciq/electron-affinity-leak.git` to demonstrate leaking when you close and reopen windows with the same affinity.

Closing a window with affinity (terminating the process), and then opening a new window with that same affinity will produce a leak.

You can recover the memory by using process.crash in the render. Example here:

![image](https://user-images.githubusercontent.com/45185091/64040150-35435b00-cb11-11e9-9449-eb56e8ed3200.png)

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by Liting1** [comment]
The problem still exists
