### ISSUE TITLE
Orphaned process on Windows when starting Electron from `child_process.fork` with `{silent: true}`

### ISSUE THREAD

**Issue by mattyork** [electron/electron#16317]
* Output of `node_modules/.bin/electron --version`: v4.0.5
* Operating System (Platform and Version): Windows 10 Enterprise
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v2.0.16 does not leave any orphaned processes

**Expected Behavior**
When killing the process with ctrl-c from command line, I expect Electron to clean up all processes and not orphan any.

**Actual behavior**
When killing the process with ctrl-c from command line, Electron orphans child processes about 30% of the time

**To Reproduce**

1. Be on Windows
1. Clone repro https://github.com/mattyork/electron-quick-start
1. npm install
1. Run `node orphaned-process.js`
1. Once Electron has started, ctrl-c to kill the process
1. Check Task Manager or Process Explorer to see orphaned processes

**Screenshots**
![image](https://user-images.githubusercontent.com/666259/50806805-0c820300-12ad-11e9-887e-2ebe0ae7f159.png)

**Additional Information**

**Comment by mattyork** [comment]
This also repros on 4.0.5. It's not just 3.0.x

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
