### ISSUE TITLE
Orphaned async/await in 4.0.0

### ISSUE THREAD

**Issue by obsius** [electron/electron#16312]
* Output of `node_modules/.bin/electron --version`: v4.0.1
* Operating System (Platform and Version): PC, Win7
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v3.0.14

**Expected Behavior**
await fn() should resolve and execution should continue.

**Actual behavior**
await fn() never resolves.

**To Reproduce**
Issue occurs with async code. A seemingly innocuous await function call will never resolve.

This only occurs when I have:
mainWindow.loadURL();
mainWindow.webContents.openDevTools();

the reverse order does not have this issue:
mainWindow.webContents.openDevTools();
mainWindow.loadURL();

The actual line where this error occurs varies, but 100% of the time, on the initial load of Electron, using the loadUrl() then openDevTools() order, some startup line of code in my web app using await will hang indefinitely, left unresolved the containing async function never executes past this line.

The problem seems to manifest after an elapsed time post Electron startup, and only ever occurs once. Subsequent page reloads do not have this issue and all async code runs normally after a refresh.

I don't have the time to further diagnose the exact cause, and I understand that what I have provided may not be enough to reproduce, but I'd like for this issue to serve as one example that may help someone else who is experiencing this until someone is able to better isolate and diagnose this issue.

**Additional Information**
I did not have this issue with any of the 3.xx versions.  But in both 4.0.0 and 4.0.1 I see this issue.

Dev env is create-react-app running a webpack dev server. Electron is started after the server has come online, and the page is then requested in loadURL().

**Comment by MarshallOfSound** [comment]
My guess is you have something in your own code throwing an exception resulting in an unhandled rejection.  I'd suggest adding a `unhandledRejection` and `uncaughtException` handler on the `process` object to log those errors.

Without a valid repro we can't look into this or have it on our open backlog

**Comment by obsius** [comment]
@MarshallOfSound thanks for the response. I already have those handlers in the code, and no exception are being thrown. Even stranger, calling other async functions later on can "unstick" the unresolved call and processing continues.  Anyhow, the issue isn't present in any 3.xx version, and also I haven't seen it in >= 4 when openDevTools() is called either before loadURL() or not all.

I'll close this issue, but there's something amiss in Electron 4.xx versions when calling openDevTools() after loadURL().  I don't know how the async stuff works under the hood, but I'd suspect that this issue is a symptom of the JS engine choking in whatever queuing/callback mechanism that's responsible for the normal resolution of async functions. Somewhere in the code run during openDevTools(), or maybe in Chromium itself, this mechanism is being interrupted.
