### ISSUE TITLE
Consider using `@types` to publish typescript typings, to allow use in apps that don't directly install electron

### ISSUE THREAD

**Issue by G-Rath** [electron/electron#16327]
This is a sister issue to [this one](https://github.com/electron-userland/electron-compile/issues/95#issuecomment-452432563) over at `electron-compile`.

Currently `electron` has its typings paired with its package. This means that the typings can't be used without `electron` itself being installed.

This is a problem when using packages like `electron-compile` & `electron-prebuilt-compile`, as these packages require you to *not* install `electron`. 

As a result, the typescript cli has problems using the definition files by default (which in turn causes problems for ides like WebStorm, that use the typescript service for features such as error checking and autocompletion).

If the typings for `electron` were published to `@types` (as they were in the past), it'd mean they could be installed by developers independent of the main package, making it easier to develop with typescript + electron in more 'exotic' use-cases.

**Comment by felixrieseberg** [comment]
While the suggestion makes sense, `electron-prebuilt-compile` comes with typings (they're just copied over from `electron`).

**Comment by G-Rath** [comment]
@felixrieseberg the problem with that is that we import `electron`, not `electron-prebuilt-compile`; this means that typescript looks for typings for `electron`, *not* `electron-prebuilt-compile`. 

At least, that's my understanding. Eitherway, publishing them to `@types` would this a non-issue regardless of what you're doing.

**Comment by MarshallOfSound** [comment]
@G-Rath My understanding of `@types` is that we can't get publish access to it, those modules are only published from the DefinitelyTyped repository so can't be wired in to our automation and in fact we deliberately requested that the types on `@types/electron` were pulled down in accordance with [their policy](https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package).

> When a package bundles its own types, types should be removed from DefinitelyTyped to avoid confusion.

**Comment by G-Rath** [comment]
> we can't get publish access to it

I can't speak for that - that might be true. 

> When a package bundles its own types, types should be removed from DefinitelyTyped to avoid confusion.

That's the point of this issue: To remove the bundling of types from this package, and instead put them on `DefinitelyTyped`.

Their policy exists b/c it doesn't make sense to have the types in two places at once, which isn't what this issue wants.

--

I figured it might be a problem of being unable to automate. If the typings are updated manually on this repo, then it'd just be a case of instead updating them over at DefinitelyTyped. 

Sadly, I'm not sure what can be done about this 😢 if it can't be done, it can't be done. Thanks anyway

**Comment by MarshallOfSound** [comment]
> That's the point of this issue: To remove the bundling of types from this package, and instead put them on DefinitelyTyped.

This is just anecdotal evidence but the majority of people I've discussed this with greatly prefer types to be bundled.  It's one less dependency / thing to think about / install.

> I figured it might be a problem of being unable to automate. If the typings are updated manually on this repo, then it'd just be a case of instead updating them over at DefinitelyTyped.

We have tooling set up to automatically generate the type definitions from our documentation at publish type --> https://github.com/electron/electron-typescript-definitions.  It's not a case of just changing where we update the definitions, it's all automated.

**Comment by MarshallOfSound** [comment]
FWIW this problem is solvable through augmentation (assuming epc ships the correct `electron.d.ts` file)

```typescript
declare module 'electron' {
  import * as electron from 'electron-prebuild-compile';

  export = electron;
}
```

(Untested but used similar logic elsewhere before)

**Comment by deadcoder0904** [comment]
I want to use typings from Electron in a library I'm writing. And the alternative is I have to copy that particular interface again & again as Electron updates.

How do I solve that then @MarshallOfSound ?
