### ISSUE TITLE
frameless window in fullscreen.

### ISSUE THREAD

**Issue by MJB-Khorasani** [electron/electron#16323]
* Output of `node_modules/.bin/electron --version`: 4.0.1
* Operating System (Platform and Version): ubuntu 18.04.1 LTS

i want to show application in fullscreen mode at startup. so i try this:

`app.on("ready", () => {

    mainWindow = new BrowserWindow({
        "title": "main window",
        "fullscreen": true
    });
    let mainWindowURL = new URL(`file://${path.join(__dirname, "assets", "html", "index.html")}`);
    mainWindow.loadURL(mainWindowURL.toString());
});`

**Expected Behavior**
the app must be show frame for application. (show close, maximize, minimize and title in the frame)

**Actual behavior**
application fullscreened but don't show frame.

**Screenshots**
![issu](https://user-images.githubusercontent.com/46071328/50843532-1cb5e300-137e-11e9-8429-f0acaa1256ef.png)

**Comment by sebamarynissen** [comment]
This is the expected behavior for the fullscreen option. Try
```js
mainWindow.maximize();
```
See also https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winmaximize

**Comment by codebytere** [comment]
Closing in agreement with the above.

**Comment by MJB-Khorasani** [comment]
ok. i know that `win.maximize()` work. but i tell that fullscreen option don't work correctly.
i simulate fullscreen with this:
`app.on('ready-to-show', () => { win.maximize(); })`

**Comment by brenca** [comment]
`Fullscreen` mode is not `maximized` mode, those are different things. `Fullscreen` is when you watch a video for example, and the video takes up the entire screen. `Maximized` is when you click the maximize button and the window takes up all the available area of the desktop, minus the taskbar and the window controls.

**Comment by MJB-Khorasani** [comment]
ok. thanks.

**Comment by Moorviper** [comment]
![Bildschirmfoto 2022-11-02 um 20 35 26](https://user-images.githubusercontent.com/3305254/199586293-3c9bfb4c-f986-4948-a723-3d5d793f0083.png)
this works ...

**Comment by abdulkerimawad** [comment]
The real problem is the win.maximize() keeps a thin space in the screen's left and right sides, also once click the title bar twice the window will be minimized even if you set resizable to false
