### ISSUE TITLE
The shortcut to close (Ctrl + W) and minimize (Ctrl + M) does not work when it is triggered from the keyboard

### ISSUE THREAD

**Issue by vrbsm** [electron/electron#16338]
* Output of `node_modules/.bin/electron --version`: v4.0.0-beta.8
* Operating System (Platform and Version): Windows 10

**Expected Behavior**
When the user trigger Ctrl+W on the keyboard, the application should **close** and when the user trigger Ctrl+M, the application should **minimize**.

**Actual behavior**
When the user trigger Ctrl+W or Ctrl+M on the keyboard nothing happens.

Please see video below to understand better.

**To Reproduce**
```sh
$ git clone https://github.com/vrbsm/electron-quick-start.git -b shortcut-issue
$ npm install
$ npm start || electron .
```
**Screenshots**
![electron-1003](https://user-images.githubusercontent.com/9887288/50901954-bcb45080-1400-11e9-9456-49be58f443ba.gif)

**Additional Information**
This feature works in version v4.0.0-beta.7
This feature doesn't work in version v4.0.0 and above

**Comment by bpasero** [comment]
I saw the same on 4.0.x where my keybinding for toggling dev tools would no longer work on Windows from an Electron fiddle.

**Comment by mathieupothier** [comment]
Same here, I have F5 and Ctrl+F5 menu accelerators and they stopped working when updated to electron 4.0.0 and same goes for 4.0.1 on Windows

**Comment by VishwasShashidhar** [comment]
This is probably fixed as part of https://github.com/electron/electron/pull/16309

**Comment by vrbsm** [comment]
I am closing this issue because as mentioned above by @VishwasShashidhar, this probably was fixed on https://github.com/electron/electron/pull/16309 
Take a look in https://github.com/electron/electron/issues/16303
