### ISSUE TITLE
Not a valid 32 bit application

### ISSUE THREAD

**Issue by tzahush** [electron/electron#16345]
* Output of `node_modules/.bin/electron --version`: latest
* Operating System (Platform and Version): docker
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
Docker(electronuserland/builder:wine) with wine does not output 32 bit valid application for windows.

**Actual behavior**
When i launch my electronjs app in a 64 bit/ 32 bit windows i get an error saying that the .node is not a valid 32 bit application

**To Reproduce**
1. Get a plain electronjs app
2. npm install drivelist
3. require it, and use a function
4. RUN: npm install --arch=ia32 --platform=win32
5. RUN: npm run pack
6. excpect the error

Please note when i see the output i get these:

> [Container] 2019/01/10 09:48:41 Running command npm install --arch=ia32 --platform=win32
>  > drivelist@6.4.3 install /codebuild/output/src399106733/src/content/offline/exam/node_modules/drivelist
> > prebuild-install || node-gyp rebuild
>  prebuild-install WARN install No prebuilt binaries found (**target=4.0.0 runtime=electron arch=ia32 platform=win32**)
> make: Entering directory '/codebuild/output/src399106733/src/content/offline/exam/node_modules/drivelist/build'
>  CXX(target) Release/obj.target/drivelist/src/drivelist.o
>  CXX(target) Release/obj.target/drivelist/src/device-descriptor.o
>  CXX(target) Release/obj.target/drivelist/src/**linux**/list.o
>  SOLINK_MODULE(target) Release/obj.target/drivelist.node
>  COPY Release/drivelist.node
> make: Leaving directory '/codebuild/output/src399106733/src/content/offline/exam/node_modules/drivelist/build'

What should i do? thanks.

**Comment by felixrieseberg** [comment]
If you're having trouble building Windows apps without Windows, I suggest that you use Windows. Microsoft offers free VMs: https://modern.ie.

I would not consider this an Electron issue.

**Comment by jacobkim9881** [comment]
I have an issue like this while using a node module made of c++ for distributing windows version electron app too.
