### ISSUE TITLE
Electron 3.0.x Linux 32bits: libdbus-1.so.3: no version information available

### ISSUE THREAD

**Issue by bpasero** [electron/electron#16364]
* Output of `node_modules/.bin/electron --version`: 3.0.13
* Operating System (Platform and Version): Ubuntu 14 32bits
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
There should be no error printed when running Electron.

**Actual behavior**
An error is printed right on startup: 

```
bpasero@ubuntu:~/Downloads$ ./electron 
./electron: /lib/i386-linux-gnu/libdbus-1.so.3: no version information available (required by ./electron)
/home/bpasero/Downloads/electron: /lib/i386-linux-gnu/libdbus-1.so.3: no version information available (required by /home/bpasero/Downloads/electron)
```

**To Reproduce**
* download Electron 3.0.13 for Linux 32bit
* install a Ubuntu 14 32bit image into Parallels (I used: `ubuntu-14.04.5-desktop-i386.iso`)
* run `./electron` from the command line

**Comment by nornagon** [comment]
Looks related to https://crbug.com/783468

**Comment by nornagon** [comment]
also in case it's useful, this is what's printing the error: https://github.com/bminor/glibc/blob/master/elf/dl-version.c#L81

**Comment by Uprzejmy** [comment]
Same problem here

hostnamectl:
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
CPE OS Name: cpe:/o:redhat:enterprise_linux:7.3:GA:server
Kernel: Linux 3.10.0-514.26.2.el7.x86_64
Architecture: x86-64

**Comment by Uprzejmy** [comment]
workaround-ed this by downloading libdbus-1-3-1.12.2 from: https://opensuse.pkgs.org/15.0/opensuse-oss/libdbus-1-3-1.12.2-lp150.1.28.x86_64.rpm.html

extracted the package:
mkdir <path_to_extract>
cd <path_to_extract>
rpm2cpio <path_where_the_lib_was_downloaded>/libdbus-1-3-1.12.2-lp150.1.28.x86_64.rpm | cpio -idmv

then created an alias in my user bashrc:
alias code='LD_PRELOAD=<path_to_extract>/usr/lib64/libdbus-1.so.3 <path_to_vscode_binary>'

voila, no more annoying printout. Seems that this release of libdbus has met version requirements

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by adamlucia** [comment]
@sofianguy Let me know if I can offer any assistance, insight.

**Comment by Tobias-Keller** [comment]
have the same error on an raspberry with armv71 on Version 7.1.7.
and yes this does prevent electron from running

**Comment by abdoutech93** [comment]
Same problem on raspbian with armv71 on Version 7.1.7 and 6.0.12

**Comment by Tobias-Keller** [comment]
> npm config set arch armv7l

Fixed it for me

**Comment by AllanOricil** [comment]
Still have this error. I can't even run a --version command.

![image](https://user-images.githubusercontent.com/55927613/83287286-512b7880-a1d9-11ea-94b4-aa2e45f872b8.png)

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
