### ISSUE TITLE
Weview is always destroyed

### ISSUE THREAD

**Issue by VisualSJ** [electron/electron#16366]
**Is your feature request related to a problem? Please describe.**
I want to move a weview. But when I remove it of the document, it gets destroyed.

**Describe the solution you'd like**
I want to know how to keep webview from being destroyed, because I still need to use it.
Is there an opportunity to process the data before destruction.

**Describe alternatives you've considered**
Add an attribute to control whether the attribute is destroyed automatically.

**Comment by codebytere** [comment]
hi @VisualSJ this seems like a bug, not a feature request: we'll need you to fill out a bug report issue and then we can look at this.

**Comment by VisualSJ** [comment]
Thanks @codebytere
The bug has been submitted.
