### ISSUE TITLE
The webview is destroyed automatically

### ISSUE THREAD

**Issue by VisualSJ** [electron/electron#16372]
* Output of `node_modules/.bin/electron --version`: 3.0.9
* Operating System (Platform and Version): MacOS 10.13.6
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
1. Create a webview Insert into the document.body. And run a lot of js scripts in it.
2. Remove the webview from the body.
3. Put it back in the document.body.

I want the results of the previous run to continue in the webview.

**Actual behavior**
The webview is destroyed. All the data in there is lost. And there is no opportunity for us to store data.

**Comment by VisualSJ** [comment]
https://github.com/electron/electron/issues/16366

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by VisualSJ** [comment]
https://github.com/VisualSJ/electron-bug-1

Sorry, I'm late.

I wrote a simple demo.

Just click the buttons in order, the data in the webview will be forcibly destroyed.

@sofianguy

**Comment by VisualSJ** [comment]
@sofianguy Hello, how is the problem now? Do I need to add something?

**Comment by VisualSJ** [comment]
@sofianguy Now, how do we deal with this?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by VisualSJ** [comment]
I'm sorry.
The problem persists with the latest version.

I used 5.0.9 and 4.2.9.

When I try to move the webview to another HTML location, the webview content is forced to be destroyed.

@sofianguy

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
