### ISSUE TITLE
After I import {ipcRenderer} from 'electron' in renderer,I have to add  target: 'node' in webpack.config.js to let ipcRenderer work.

### ISSUE THREAD

**Issue by hugetiny** [electron/electron#16371]
after I import {ipcRenderer} from 'electron' in renderer

**reproduce:**
add target: 'node' in webpack.config.js or ipcRenderer will not work.
but there comes warning:
Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.
 
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.
is {target: 'node'} required for render when i package my app with webpack?

**Comment by miniak** [comment]
You need to add CSP to your page
