### ISSUE TITLE
TypeError: x is not a function

### ISSUE THREAD

**Issue by GingkathFox** [electron/electron#16377]
* Output of `node_modules/.bin/electron --version`: `-bash: electron: command not found`
* Operating System (Platform and Version): MacOS Mojave, 10.14.2
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): electron isn't installed globally

**Expected Behavior**
The game loads the first level.

**Actual behavior**
Electron throws a error: 
```css
Uncaught TypeError: Crafty.scene is not a function
    at Level1.js:6
```

**To Reproduce**
I dont have permission to put the code in a repo. Im sure you can reproduce using [this](https://github.com/starwed/craftyjs-npm-example).

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
installation instructions are in the repo above, just init the folder and save electron:
```sh
cd /PATH/TO/REPO
npm init
npm install --save electron
```
and then to set it up:
```css
"scripts": {
    "test": "electron .",
    "start": "beefy Level1.js --open"
  },
```
If you run using `npm start`, the example should appear on your browser on the port `http://127.0.0.1:9966`.
**Screenshots**
What electron outputs:
![what Electron outputs](https://user-images.githubusercontent.com/33764485/51074851-2e370d80-1652-11e9-8dc2-07d8e0f234dc.png)
What the game is supposed to look like:
![What the game is supposed to look like](https://user-images.githubusercontent.com/33764485/51074852-31ca9480-1652-11e9-93fa-11afb36fb82c.png)

**Additional Information**
Ive already asked on the Atom forums [here](https://discuss.atom.io/t/typeerror-crafty-scene-is-not-a-function/61273/18)

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community).
