### ISSUE TITLE
Failed to get crash dump id. after hanging for about 5-15 second.

### ISSUE THREAD

**Issue by RoyC1989** [electron/electron#16388]
Output of node_modules/.bin/electron : v3.0.13
Operating System (Platform and Version): Linux version 4.4.11 BuildRoot,

Expected behavior:
Crash reporter posts the dmp file to the mini break pad server as described in the CrashReporter documentation page.

Actual behavior:
On calling process.crash() the application just hangs for 5-15 seconds and shuts down. With the following output: 
Failed to get crash dump id.
Report Id:
Illegal instruction (core dumped)
might be related to #5434 althou wget 1.18 is installed on the system.

To reproduce:
I am unable to provide the build root build settings but other that the os I call the start methode of the crashreporter:
crashReporter.start({
  productName: " productName ",
  companyName: " companyName ",
  submitURL: "http://192.168.200.193:1127/post",
  uploadToServer: true
});

Additional information:

With crashreporter enabled and calling process.crash() the application hangs for a good while 5-15 seconds. And then the application just shuts down with no crash report posted to the server and no dmp file in the temp folder. We are running the application on a buildroot. Using deb-based libraries. But exept the crashreporting there are no issues so far. 

When running the application on windows and lubuntu it works as expected.
Any direction where the problem might reside (missing linux libraries or programs) would be helpful.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by mkermani144** [comment]
@sofianguy I have the same issue with Electron v7.0.0. Can you reopen this issue?
