### ISSUE TITLE
Image cache error in MacOS Mojave 

### ISSUE THREAD

**Issue by Ripple07** [electron/electron#16383]
* Output of `node_modules/.bin/electron --version`: 1.8.6

* Operating System (Platform and Version):
Mac Mojave 18.0.0、18.2.0

**Expected Behavior**
We expected to return the correct image when using the cache.

**Actual behavior**
But we found that the image returned by the same url is incorrect.
This phenomenon does not appear every time. But our app with electron received more than 20 feedbacks like this since November 2018.

**Screenshots**
The Right One
![image](https://user-images.githubusercontent.com/13217074/51095672-69bc0e00-17f1-11e9-9ba5-da60ff818164.png)

The Error One
![image](https://user-images.githubusercontent.com/13217074/51095131-6e7ec300-17ed-11e9-9f47-5ad75b74023a.png)

**Additional Information**
We have tried to shorten the cache time to one day. After that, we received only one feedback in one month. Please help us locate the reason. Thanks.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by Ripple07** [comment]
Thanks for your apply!
We tried to upgrade the electron version. But we still Found this issue as the picture below. 
Electron version is v2.0.9. 

The Error One
![fotojet 3](https://user-images.githubusercontent.com/13217074/51457373-1bc47e80-1d8c-11e9-95fb-5cd5eb33dbc6.jpg)
The Right One
![fotojet 4](https://user-images.githubusercontent.com/13217074/51457385-25e67d00-1d8c-11e9-8322-b0fed41c5059.jpg)

I hope that you can further find out the reasons and help us solve this problem.
Thank you very much!

**Comment by dengyaolong** [comment]
I meet this problem too , and really suffer from it.

**Comment by imqiang** [comment]
we meet this issue too

**Comment by nornagon** [comment]
This looks related: https://bugs.chromium.org/p/chromium/issues/detail?id=899874

does this still happen in Electron 6 for you?

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. 

Also, the version of Electron you reported this on has been superseded by newer releases. If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
