### ISSUE TITLE
ipcRenderer.removeAllListeners to remove multiple channels

### ISSUE THREAD

**Issue by gsongsong** [electron/electron#16386]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
- Option 1
```js
ipcRenderer.removeAllListeners('channel1', 'channel2', ..., 'channelN')
```
- Option 2
```js
ipcRenderer.removeAllListeners(['channel1', 'channel2', ..., 'channelN'])
```

**Describe alternatives you've considered**
Nothing

**Additional context**
I just wanted to remove all listeners of multiple channels with one line.

**Comment by MarshallOfSound** [comment]
This is the standard nodejs event emitter API.  If you want a single line you can do this.  Or you can make a helper method to do it for you.


```js
for (const channel of ['channel1', 'channel2']) ipcRenderer.removeAllListeners(channel)
```
