### ISSUE TITLE
if '://' key word in the middle of argument list, electron is not executed

### ISSUE THREAD

**Issue by MadfishDT** [electron/electron#16384]
* Output of `node_modules/.bin/electron --version`:
* after Electron v3.0.1
* Operating System (Platform and Version):
* window 10

**Expected Behavior**

I've run electron.exe with command line argument like this

```sh
$ electron.exe appdir url=https://test.com ws=wss://test.com
```
I've expected running electron with arguments

**Actual behavior**

electron.exe process quit. Event through main process do not work.
I wrote code in main process first line like this
```js
console.log('this is command lines: ' + JSON.stringify(process.args));
```
but I could not find this console message in console screen.

**To Reproduce**
1. download higher 3.0.1 version electron release from electron release official site
2. run electron.exe with arguments like this

**not wokrs example**
```
electron.exe appdir url=https://test.com ws=wss://test.com
electron.exe appdir url=https://test.com ABC
electron.exe appdir url=https://test.com test
electron.exe appdir thisisfirst://argument thisis://secondargument
electron.exe appdir thisisfirst://argument thisissecondargument

```

**wokrs example**
```
electron.exe appdir url=https://test.com
electron.exe appdir ABC url=https://test.com
electron.exe appdir test https://test.com test
```

if "://" keyword is in the middle of arguments array, electron quit immdeiately but if if "://" keyword is in the last of arguments array and only one, electron can be running

**Comment by MadfishDT** [comment]
I found somthing about command line parsing rules in atom/app/command_line_args.cc
in CheckCommandLineArguments function. 'url=http://xxxxxxx' type argument is accepted by IsBlacklistedArg function before 2.x version , but now, CheckCommandLineArguments function accept  '-url=http://xxxxxxx' or  '--url=http://xxxxxxx' type argument. however in main js '-xxx=xxxxx' pattern argument can not read with process.argv....

**Comment by MarshallOfSound** [comment]
This is expected behavior and is a security mitigation from a while ago.

Can you clarify your use case for having URLs in the arguments for your app?

**Comment by MadfishDT** [comment]
thanks for your help. 'all argument is ignored' is my fault. to run electron, i use 'npm start'. '--' command was consumed in npm process. so -- command can not pass to electron process. we develop window application. developer test html content that not packaged with console. sometimes we change server address by using command-line arguments. but it blocked in atom_main.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
