### ISSUE TITLE
autoHideMenuBar doesn't toggle menu if the focus set on the current BrowserView 

### ISSUE THREAD

**Issue by ChugunovRoman** [electron/electron#16381]
* Output of `node_modules/.bin/electron --version`: v3.1.0
* Operating System (Platform and Version): Fedora 28
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):
N/A
**Expected Behavior**
Toggling main menu by the Alt key when I work inside a BrowserView.

**Actual behavior**
I created a BrowserView and set it into BrowserWindow, and also set autoHideMenuBar: true.
When I work in a BrowserView, and I pressed on Alt key so the main menu doesn't toggle. BUT if I click on BrowserWindow outside BrowserView, then main menu will be toggle by the Alt key.  

How I create a BrowserView:
```typescript
const options: E.BrowserViewConstructorOptions = {
	webPreferences: {
	  nodeIntegration: false,
	  webSecurity: false,
	  webgl: true,
	  experimentalFeatures: true,
	  zoomFactor: 0.9
	}
};
```

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by gorn** [comment]
I can confirm this in Electron 15.1, please **reopen**.
