### ISSUE TITLE
2019 - Fork a .js file on a child_process still doesn't work because of ASAR.

### ISSUE THREAD

**Issue by vladejs** [electron/electron#16382]
* Output of `node_modules/.bin/electron --version`:
Electron `v4.0.1`

* Operating System (Platform and Version):
`Windows 10`

**Expected Behavior**

I've read nearly 10 issues related to forking a .js file on a child_process. 
The only way I have it worked is by using `extraResources: ["app/utils/discoverFiles.js"]` on the build configuration (on `package.json`) and using this code:

```
import { .fork } from 'child_process';

const childWorker =
      process.env.NODE_ENV === 'development'
        ? path.join(__dirname, 'discoverFiles.js')
        : path.join(process.resourcesPath, 'app/utils/discoverFiles.js');

    const discoverable = fork(childWorker);

    // work with discoverable
```

The problem is that  when building for Windows, and looking at the folder: `myapp/resources/`, I see the plain JavaScript file uncompressed: `myapp/resources/app/utils/discoverFiles.js`

I would like to not expose that file, and maintain it on the ASAR folder.

Haven't see a reliable and clean way to achieve it, so, please, help.

**Comment by sindresorhus** [comment]
Same with `childProcess.spawn()`... https://github.com/electron/electron/issues/9459

**Comment by vladejs** [comment]
mmm, disabling asar is not advised for Windows, since it make things go slower, among other things. 
`electron-builder` even throws a strong warning against not using asar.

Any other solution?

**Comment by meekaah** [comment]
as a workaround what i've done is spawn the main process with some specific args like --discoverFiles and at the top of my main.js i check if the process.argv contains --discoverFiles and require my discoverFiles.js and return as to not execute the rest of my main.js. it's hacky but it works

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by ishener** [comment]
forking a file inside ASAR doesn't work at all in electron 8

I tried the simplest possible fork, with and absolute path and it doesn't work:

`fork("c:\folder\app.asar\file.js")`

when pointing to a file not in asar works perfectly.
