### ISSUE TITLE
chrome.runtime.onmessage.addListener::sendResponse does not work

### ISSUE THREAD

**Issue by kwonoj** [electron/electron#16394]
* Output of `node_modules/.bin/electron --version`:
* Operating System (Platform and Version):
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
`chrome.runtime.onmessage.addListener` callback (`(message, sender, sendResponse) => void`)'s `sendResponse` callback fn should deliver response to caller.

**Actual behavior**
It does not.

**To Reproduce**
Clone `https://github.com/kwonoj/electron-quick-start/pull/4`

1. `npm start`
2. open `chrome://inspect` on chrome browser, inspect `chrome-extension://test-extension/_generated_background_page.html`

background script received initial message from content script, and content script does not receives response from it.

**Screenshots**

**Electron 4.0.1**

![image](https://user-images.githubusercontent.com/1210596/51131212-eb0ca400-17e3-11e9-88de-c22c9d69a8dd.png)

**Chrome**

![image](https://user-images.githubusercontent.com/1210596/51131459-a59ca680-17e4-11e9-87d5-2f5983683011.png)

**Additional Information**

This is technically dupe of https://github.com/electron/electron/issues/11341, while it is just closed even though it's electron specific. Feel free to close this one and reopen existing or either.

**Comment by jkleinsc** [comment]
Fixed via #16945

**Comment by CVertex** [comment]
@kwonoj Thanks for reporting this, I'm seeing a similar issue and keen to try out the fix.
How did you show the console window for the background page? I'd like to debug my background pages as I do in chrome, but i can't work out how to open the devTools for a background page/script.

**Comment by Padge91** [comment]
An old question, but responding for anyone else who ends up here trying to debug electron extensions. To debug a background script in Electron, you should open up a second window with the extension URL:
```
var name = session.defaultSession.loadExtension(path.join(__dirname, "./lib/extension")).then(function(extension){
                console.log("Extension loaded: "+extension.name+"@"+extension.version);

                var window = new BrowserWindow();
                window.loadURL(extension.url+"_generated_background_page.html")
                window.show();
                window.webContents.openDevTools({mode:"detach"});
            });

```
