### ISSUE TITLE
Vibrancy Support for Windows

### ISSUE THREAD

**Issue by Stilldabomb** [electron/electron#16391]
**Is your feature request related to a problem? Please describe.**
MacOS has support for the `vibrancy` field, there's been quite a few Windows versions, yet there's still no official support in Electron.

**Describe the solution you'd like**
An official Windows solution to vibrancy, using acrylic or any other background blurring method.

**Describe alternatives you've considered**
https://github.com/arkenthera/electron-vibrancy
https://github.com/23phy/electron-acrylic
https://github.com/sylveon/windows-blurbehind

All require a lower version of Electron than 4.0, and/or to be building on Windows.

**Comment by iamakulov** [comment]
Also previously discussed in https://github.com/electron/electron/issues/16391

**Comment by bogdan-calapod** [comment]
I guess this could be made possible using XAML Islands - https://blogs.windows.com/buildingapps/2018/11/02/xaml-islands-a-deep-dive-part-1/

**Comment by UXDart** [comment]
any news on this? TIA

**Comment by FearGannicus** [comment]
I have found a node module that works for electron 9.1.0. I know this isn't what we want, but i just thought I would update all of you; https://github.com/Seo-Rii/electron-acrylic-window

**Comment by EriKWDev** [comment]
It feels very strange that we have this feature built into electron but only for macOS now that "vibrancy"/acrylic is a thing on Windows too...

**Comment by bogdan-calapod** [comment]
> It feels very strange that we have this feature built into electron but only for macOS now that "vibrancy"/acrylic is a thing on Windows too...

Indeed - isn't Electron supposed to be fully cross-platform ?

**Comment by gpetrov** [comment]
Can we please add Windows support for Vibrancy? 
It is really 20 lines of code that is already given in the more recent fork of:

https://github.com/orhan/electron-vibrancy

It is also the default windows look now in Windows 11

Please @codebytere or @ckerr

**Comment by CoreyVidal** [comment]
Please, can we get this? Devs, have you seen @gpetrov's comments here?

**Comment by codebytere** [comment]
hey folks - put up a PR to get this added into Electron 🌟
