### ISSUE TITLE
Downloading base64 image  gives rise to the electron crashes

### ISSUE THREAD

**Issue by codertony** [electron/electron#16399]
* Output of `node_modules/.bin/electron --version`:  2.0.8
* Operating System (Platform and Version):window 10

**Expected Behavior**
*code in webcontent:
The Objective of this function is to download a image with a imageUrl.
```javascript
downloadImage(imgsrc, name) {//下载图片地址和图片名
        let image = new Image();
        // 解决跨域 Canvas 污染问题
        image.setAttribute("crossOrigin", "anonymous");
        image.onload = function() {
          let canvas = document.createElement("canvas");
          canvas.width = image.width;
          canvas.height = image.height;
          let context = canvas.getContext("2d");
          context.drawImage(image, 0, 0, image.width, image.height);
          let url = canvas.toDataURL("image/png"); //得到图片的base64编码数据
          let a = document.createElement("a"); // 生成一个a元素
          let event = new MouseEvent("click"); // 创建一个单击事件
          a.download = name || "photo"; // 设置图片名称
          a.href = url; // 将生成的URL设置为a.href属性
          a.dispatchEvent(event); // 触发a的单击事件
        };
        image.src = imgsrc;
      }
```

**Actual behavior**
When use the function to download the image at the bottom, the electron App crash.
![1547521957476328350](https://user-images.githubusercontent.com/16818275/51156492-d220f300-18b6-11e9-91b6-86dbdae3a8a6.png )

The crash state like this 
![20190115111455](https://user-images.githubusercontent.com/16818275/51156508-dc42f180-18b6-11e9-8338-d9bb7f0ea5f2.png)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
