### ISSUE TITLE
Hotkeys on electron-quick-start are not working

### ISSUE THREAD

**Issue by GitFlip** [electron/electron#16392]
* Output of `node_modules/.bin/electron --version`: v4.0.1
* Operating System (Platform and Version): Windows 7
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): N/A
 
**Expected Behavior**
Pressing hotkey like `Ctrl` + `Shift` + `I` should bring up developer tools in the electron-quick-start repo

**Actual behavior**
None of the hotkeys are working

**To Reproduce**

1. Clone the [electron-quick-start](https://github.com/electron/electron-quick-start) repo
2. Install dependencies
3. Run the application
4. Press `Ctrl` + `Shift` + `I` to bring up DevTools
5. No DevTools opening

**Additional Information**
This behavior is happening for all hotkeys, not just DevTools.

**Comment by codebytere** [comment]
Please open an issue on the `electron-quick-start` repo.
