### ISSUE TITLE
Electron can not select files and folders at the same time

### ISSUE THREAD

**Issue by DZiso** [electron/electron#16390]
* Output of `node_modules/.bin/electron --version`: 3.0.1 also tested on: 4.0.1
*System: Ubuntu 18.04.1 LTS/Windows 10 1809
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): -

**Expected Behavior**
After the documentation of the dialog component (https://github.com/electron/electron/blob/master/docs/api/dialog.md) i would assume calling showOpenDialog({ properties: ['openFile', 'openDirectory', 'multiSelections'] }) would open a file explorer where i can select multiple files and folders. 

**Actual behavior**
Ubuntu/Windows::
 You can only select folders.

**To Reproduce**
```sh
$ git clone https://github.com/DZiso/electron-multi-select-file-and-folder
$ cd electron-multi-select-file-and-folder
$ npm install
$ npm run start
```
Press the button "Click me to open File Explorer".

**Additional Information**
Started with no parameters you can select files & folders while browsing "latest Files" in the ubuntu explorer, but not if you change to any other folder.(Related: https://github.com/electron/electron/issues/16163)

Windows and Ubuntu are "plain" installation with no changes to the file explorer. IntelliJ/Git/node is installed on both. Windows is running as a virtual Machine under KVM.

**Comment by DZiso** [comment]
-> Made a mistake describing the bug. It exists in 3.0.1 and in 4.0.1.
I did edit my first post to reflect that.

**Comment by ntpincus** [comment]
Linux's recent files is just giving electron all sorts of trouble, huh? :1
Hope this gets fixed!

**Comment by Woofthecat** [comment]
Isn't this the same behavior the documentation mentions under `showOpenDialog`?

> **Note**: On Windows and Linux an open dialog can not be both a file selector and a directory selector, so if you set `properties` to `['openFile', 'openDirectory']` on these platforms, a directory selector will be shown.

**Comment by DZiso** [comment]
@Woofthecat you are right. Interesting as at least Windows supports the Feature natively

I would would still change the topmost Sample:
>An example of showing a dialog to select multiple files and directories

It is only valid on one(?) supported Platform.

**Comment by Woofthecat** [comment]
@DZiso Does it? I thought Windows had different dialogs for file/directory selection. Please correct me if I'm wrong.

But you have a point with the sample and I do agree. If the behavior cannot be changed then it would be nice to see a sample either applying to all platforms or to mention that it's only working on macOS.

**Comment by codebytere** [comment]
On Windows, files and folders can't be selected at the same time, sadly. It's a platform limitation.

**Comment by Nokel81** [comment]
I agree that this should be documented that those two options shouldn't be used together. It seems the the first one is used if multiple are provided.

**Comment by Morsmalleo** [comment]
what if you were to use two dialogs in the same controller? one for Selecting Files, and the other for selecting Directories??? would this be possible???

**Comment by Nokel81** [comment]
Yes that is possible, that is what we ended up doing for both Windows and Linux. macOS allows selecting both.

**Comment by Morsmalleo** [comment]
> Yes that is possible, that is what we ended up doing for both Windows and Linux. macOS allows selecting both.

Really?? so you can use two seperate dialogs in the same `AppCtrl.js` file, one for File Selection and one for Directory Selection? how would one integrate this??? I've looked everywhere and haven't found much which is why I am here to be honest, sorry for commenting on a closed issue, this was just driving me nuts.

**Comment by Nokel81** [comment]
Oh no sorry I misunderstood. We split out the dialogs depending on what the user wanted to do. I don't think windows supports Files+Directories being chosen at the same time via its APIs at all.

**Comment by Morsmalleo** [comment]
so its not possible to have seperate dialogs, one for a specific type of selection, in the same `AppCtrl.js` file on linux?

**Comment by Nokel81** [comment]
Yes of course you can have separate dialogs, same with on macOS. But on macOS you don't need to

**Comment by Morsmalleo** [comment]
Ok well I am working on Linux so if you don't mind my asking, how would one
setup seperate dialogs for specific selection??

**Comment by Nokel81** [comment]
You have one that includes `"openDirectory"` in `properties` and one that includes `"openFile"`. I would recommend reading the docs https://www.electronjs.org/docs/latest/api/dialog#dialogshowopendialogbrowserwindow-options

**Comment by Morsmalleo** [comment]
Thank you
