### ISSUE TITLE
Electron 4.0.x: does not run on Ubuntu 14/16 32bits anymore

### ISSUE THREAD

**Issue by bpasero** [electron/electron#16407]
* Output of `node_modules/.bin/electron --version`: 4.0.1
* Operating System (Platform and Version): Ubuntu 14 32bits
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 3.0.x

**Expected Behavior**
Electron 4.0.x starts on Ubuntu 14 32bits

**Actual behavior**
Electron does not start.

**To Reproduce**
Simply start Electron 4.0.x on a fresh Ubuntu 14 32bits and get as output:

```
ticino@ubuntu:~/Downloads$ ./electron 
./electron: /lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by ./electron)
./electron: /lib/i386-linux-gnu/libdbus-1.so.3: no version information available (required by ./electron)
ticino@ubuntu:~/Downloads$ 
```

**Comment by bengotow** [comment]
Hey gang! I filed a similar issue a while ago and I think @nornagon's comment there may be relevant to this: https://github.com/electron/electron/issues/16247#issuecomment-451261705

**Comment by heronhaye** [comment]
This occurs on Debian Stretch as well.

**Comment by bpasero** [comment]
Is there anything I can install on Ubuntu 14 32bit to get it to start? I would appreciate any pointers.

**Comment by bpasero** [comment]
Same on Ubuntu 16 actually.

**Comment by heronhaye** [comment]
Any update? Would be good to know if this is planning to be fixed or not.

**Comment by sgrayban** [comment]
Well crap... the same version ran in Debian Jessie(8) just fine. So what changed that it won't work in Stretch (9) ??

**Comment by sgrayban** [comment]
I just want to mention that without this working on 32bit we CANNOT use the secure chat feature.

**Comment by ckerr** [comment]
See https://electronjs.org/blog/linux-32bit-support for discussion on this. 

I see this decision in a similar light to the question of BSD support: The Electron maintainers don't have the resources to commit to supporting this themselves, but are open to PRs from community members encountering issues on platform X and who are able to work on these issues.

**Comment by tarruda** [comment]
Possible fix for this issue: https://github.com/electron/electron/issues/16205#issuecomment-515046860
