### ISSUE TITLE
Request for npm package of v5.0.0-nightly.20190111

### ISSUE THREAD

**Issue by RickyWong33** [electron/electron#16402]
**Is your feature request related to a problem? Please describe.**
v5.0.0-nightly.20190111 introduces Chromium 71.0.3578.98, which improves the performance of webassembly greatly, so we want to do some testing based on Electron

**Describe the solution you'd like**
release the npm package of v5.0.0-nightly.20190111

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by nornagon** [comment]
Releases are stalled for the moment due to an infrastructure issue, we will release once that issue has been resolved.

**Comment by MarshallOfSound** [comment]
The specific nightly you're requesting is available though in the `electron-nightly` package

**Comment by RickyWong33** [comment]
> The specific nightly you're requesting is available though in the `electron-nightly` package

the lastest package is only 5.0.0-nightly.20190107
