### ISSUE TITLE
[MacOS] Crash in nativeImage.createFromPath() with Template

### ISSUE THREAD

**Issue by CapOM** [electron/electron#16408]
I get some crashes with nativeImage.createFromPath when it has Template in its name after upgrading electron (see https://electronjs.org/docs/api/native-image#template-image) .

I think it is a regression that appeared back from electron 2.0 as it works in electron 1.7

[71273:0115/093130.192071:FATAL:image_skia.cc(482)] Check failed: g_supported_scales != NULL. 
0   libbase.dylib                       0x00000001064cc75e base::debug::StackTrace::StackTrace(unsigned long) + 174
1   libbase.dylib                       0x00000001064cc81d base::debug::StackTrace::StackTrace(unsigned long) + 29
2   libbase.dylib                       0x0000000106092c2c base::debug::StackTrace::StackTrace() + 28
3   libbase.dylib                       0x000000010613c20c logging::LogMessage::~LogMessage() + 460
4   libbase.dylib                       0x000000010612b675 logging::LogMessage::~LogMessage() + 21
5   libgfx.dylib                        0x000000010984eed7 gfx::ImageSkia::EnsureRepsForSupportedScales() const + 183
6   libgfx.dylib                        0x0000000109963c2b gfx::NSImageFromImageSkiaWithColorSpace(gfx::ImageSkia const&, CGColorSpace*) + 155
7   libgfx.dylib                        0x0000000109843469 gfx::Image::ToNSImage() const + 745
8   libgfx.dylib                        0x000000010984503c gfx::Image::AsNSImage() const + 60
9   Electron Framework                  0x000000010cdd5541 atom::api::NativeImage::SetTemplateImage(bool) + 33
10  Electron Framework                  0x000000010cdc22f2 atom::api::NativeImage::CreateFromPath(v8::Isolate*, base::FilePath const&) + 146

**Comment by CapOM** [comment]
Maybe related https://github.com/electron/electron/pull/1383/files

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
