### ISSUE TITLE
Spellchecker regression in v3.x

### ISSUE THREAD

**Issue by fxha** [electron/electron#16412]
* Output of `node_modules/.bin/electron --version`: v3.1.1 (maybe v4.0.x too)
* Operating System (Platform and Version): Linux 4.19.x
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v2.0.16

**Expected Behavior**

Spell checking should always work and highlight all misspelled words in a textarea and `contenteditable` block.

**Actual behavior**

Spell checking only works for short text lines. If you use longer lines or words, only the selected line is red highlighted.

**To Reproduce**

```sh
$ git clone https://github.com/fxha/electron-3-spellcheck
$ npm install
$ npm run start
```
**Screenshots**

![electron_spellchecking](https://user-images.githubusercontent.com/22716132/51214616-b18c8380-191e-11e9-9ca0-b7ca8a16ddd8.gif)

**Additional Information**

#13608 was a similar issue.

**Comment by nornagon** [comment]
This matches Chrome's behaviour and is working as expected.
