### ISSUE TITLE
Vibrancy should not default to active state

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#16417]
* Output of `node_modules/.bin/electron --version`: v4.0.1
* Operating System (Platform and Version): macOS 10.14.2

**Expected Behavior**

The default behavior of native macOS apps with vibrancy is to disable the vibrancy when the window is inactive. This makes it easier for the user to see the active app.

**Actual behavior**

Electron apps have the vibrancy forced to always be active since Electron manually sets the state to [`NSVisualEffectStateActive`](https://developer.apple.com/documentation/appkit/nsvisualeffectstate/nsvisualeffectstateactive?language=objc): https://github.com/electron/electron/blob/52fe92d02ef94712fc7b19b3f03d3363cfa71a4d/atom/browser/native_window_mac.mm#L1272

Electron should instead default to `NSVisualEffectStateFollowsWindowActiveState`, which is the default.

Electron could let the user optionally override this behavior through `BrowserWindow({vibrancyState: 'active'})` and `win.setVibrancy('sidebar', {state: 'active'})`.

**To Reproduce**

Nothing to reproduce. The docs are clear on this one.

**Additional Information**

More info here: https://github.com/sindresorhus/caprine/issues/701

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sindresorhus** [comment]
Still an issue in `master`: https://github.com/electron/electron/blob/fe5318d753637c3903e23fc1ed1b263025887b6a/shell/browser/native_window_mac.mm#L1440

**Comment by flawnn** [comment]
@codebytere I wasn't sure whether to open a new issue but this issue hasn't been implemented like described, there is still an option missing to change the vibrancyState over the runtime :)
