### ISSUE TITLE
Upstream webrtc69 already contains webrtc/disable-warning-win.patch

### ISSUE THREAD

**Issue by CapOM** [electron/electron#16424]
The file 
https://github.com/electron/electron/blob/4-0-x/patches/common/webrtc/disable-warning-win.patch should be removed as it is already in webrtc69 :

https://chromium.googlesource.com/external/webrtc/+/80d02ad93fa31e2ad507a24494106d6b950b522a

webrtc69 branch: https://chromium.googlesource.com/external/webrtc/+log/branch-heads/69

**Comment by nornagon** [comment]
Cool, wanna open a PR? All you need to do is delete that file and delete the line from `.patches` :)

**Comment by CapOM** [comment]
It is ok, please go ahead, thx!

**Comment by nornagon** [comment]
Oh, it turns out that patch wasn't being applied anyway, see patches/common/config.json which didn't include the webrtc directory.

**Comment by deepak1556** [comment]
Fixed by https://github.com/electron/electron/pull/16440
