### ISSUE TITLE
electron v4 webview h5 requestFullscreen not work

### ISSUE THREAD

**Issue by yangfan1018** [electron/electron#16428]
* Output of `node_modules/.bin/electron --version`: v4.0.1
* Operating System (Platform and Version): Mac OS 10.14.2
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v3.0.13

**Expected Behavior**
H5 requestFullscreen trigger this webview fullscreen.

**Actual behavior**
````
let webview = document.querySelectorAll('webview')[0]
webview.addEventListener('enter-html-full-screen', (e)=>{
    console.log(e)
})
````
'enter-html-full-screen' will triggered, but fullscreen not work

**To Reproduce**
I made a repository with multiple examples to the described behavior.

```sh
$ git clone https://github.com/yangfan1018/electron-webview-fullscreen-test.git
$ npm install
$ npm start || electron .
```
**Screenshots**
![image](https://user-images.githubusercontent.com/26080517/51304793-07267480-1a74-11e9-8f2e-9ce408d0b983.png)

**Additional Information**

**Comment by littlecold233** [comment]
+1

**Comment by littlecold233** [comment]
Any progress on this?

 In 4.x,  chrome upgraded to 69. Maybe this is the reason

**Comment by maxosprojects** [comment]
same problem in 4.0.6

**Comment by guilhermewaess** [comment]
Any news on this?

**Comment by zikosichi** [comment]
Any updates?

**Comment by miniak** [comment]
it reproduces on all platforms
