### ISSUE TITLE
Slow Canvas 2D drawImage

### ISSUE THREAD

**Issue by juancampa** [electron/electron#16439]
* Output of `node_modules/.bin/electron --version`: `v4.0.1`
* Operating System (Platform and Version): `Linux 4.20.0-arch1-1-ARCH #1 SMP PREEMPT`
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): `v3.1.1`

**Expected Behavior**

drawImage has consistent performance

**Actual behavior**

`drawImage` has good performance until a certain amount of big canvases with "2d" contexts are created (in my case 3x 3000x2000)

**Screenshots**

![2019-01-17_16-31](https://user-images.githubusercontent.com/1410520/51350670-c8de8480-1a76-11e9-9e4e-ee9b8a19d1a3.png)

**Additional Information**

Seems like it could be this bug in Chromium https://bugs.chromium.org/p/chromium/issues/detail?id=683994 (others are also reporting it on Chromium 69)

**Comment by nornagon** [comment]
I agree, this seems like a bug in Chromium. We'll pick up the fix if/when Chromium fixes it.
