### ISSUE TITLE
node-thermal-printer question

### ISSUE THREAD

**Issue by Dragonarka** [electron/electron#16432]
* electron --version`: v1.8.8
* Win x64

### Expected behavior
I am using the library node-thermal-printer for printing directly to Epson printers and its working ok in production.

## Actual behavior

my printer is not working in every PC in which I install a pre-release version. 
what i am trying to say is that every computer where i test the prerelease suddenly fail forever, even if y clear the %temp% or %appdata% of my app and literally nothing with the printer changed

### changes
I just add a new library called get-folder-size that works fine but it has nothing to do with printing, as i said, the behavior is the same in production but in pre-releases i think that is crashing the OS.

### experiments
i tried to print with a production version in my machine or testing machines ... Fails
i tried to print with a production version in another machine... works ok
i return version and use npm i and fail in the corrupted machines
i tried to reinstall electron, node, everything

###  error msg
_______________________________________________________
err: Error: UNKNOWN: unknown error, open '\\localhost\smile\'
code:"UNKNOWN"
errno:-4094
path:"\\localhost\smile\"
syscall:"open" 
message:"UNKNOWN: unknown error, open '\\localhost\smile\'"
stack:
"Error: UNKNOWN: unknown error, open '\\localhost\smile\'"
__________________________________________________________________
as you can see, smile is the name of my printer and works totally fine with pdfs in corrupted computers but  is cofingured in the same way in production for every user.

### my package
  "dependencies": {
    "bcryptjs": "^2.4.3",
    "bestzip": "^2.1.2",
    "electron-json-storage": "^4.0.2",
    "electron-log": "^1.3.0",
    "electron-updater": "^4.0.0",
    "express": "^4.16.3",
    "express-rate-limit": "^3.3.0",
    "fs-extra": "^7.0.0",
    "get-folder-size": "^2.0.0",
    "jquery": "^3.2.1",
    "ncp": "^2.0.0",
    "node-schedule": "^1.3.0",
    "node-thermal-printer": "github:SmileOffline/node-thermal-printer#master",
    "nodemailer": "^4.6.8",
    "npm": "^6.3.0",
    "simple-node-logger": "^0.93.37",
    "socket.io": "^2.1.1",
    "toastr": "git+https://github.com/SmileOffline/toastr.git"
  },
  "devDependencies": {
    "bestzip": "^2.1.2",
    "electron": "^1.8.8",
    "electron-builder": "^20.36.2"
  }

**Comment by nornagon** [comment]
Electron v1.8 is no longer supported.

Further, this seems like an issue with node-thermal-printer and you should file an issue on that repo.
