### ISSUE TITLE
Detect MacOS menu bar hidden

### ISSUE THREAD

**Issue by alexcroox** [electron/electron#16431]
Mac OS allows you to auto hide the menu bar 

![ss](https://cl.ly/1a4ca23a7e2b/Screenshot%202019-01-17%20at%2011.50.19.png)

Is there an event that can fire when it toggles between visible and hidden? Otherwise my menubar app position gets either covered or is left hovering when it hides.

![gif](https://cl.ly/46837a38abf4/Screen%20Recording%202019-01-17%20at%2011.54%20am.gif)

**Comment by orangeChu** [comment]
Maybe you can reset the location information when you click the icon.

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
