### ISSUE TITLE
Crash after a while with Tray.popUpContextMenu

### ISSUE THREAD

**Issue by tarruda** [electron/electron#16445]
* Output of `node_modules/.bin/electron --version`: v4.0.1 (also reproducible in versions 3.0.14 and 3.1.1)
* Operating System (Platform and Version): Windows 7 SP1 (also reproducible in Windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): v1.8.*

**Expected Behavior**
No application crash

**Actual behavior**
Application crash

**To Reproduce**
Copy and paste these shell commands to create a simple app to reproduce:

```sh
mkdir tray-crash
cd tray-crash
cat > package.json << "EOF"
{
  "name": "tray-context-menu-crash",
  "version": "1.0.0",
  "description": "reproduce crash when tray context menu is open",
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "electron": "^4.0.1"
  }
}
EOF
cat > main.js << "EOF"
const { app, Menu, Tray, nativeImage } = require("electron")
const path = require('path')

app.on("ready", main)
let tray
function main() {
  tray = new Tray(nativeImage.createEmpty())
  tray.popUpContextMenu(Menu.buildFromTemplate([
    { label: "Item 1" },
    { label: "Item 2" }
  ]))
  setInterval(() => {
    console.log('60 seconds passed')
  }, 60000)
}
EOF
npm install .
npm start
```

When the app starts, a menu will appear where your mouse cursor is. After approximately 60 seconds (probably the garbage collector run interval), move your mouse cursor and the app should crash. 

**Additional Information**
This probably happens because the menu object passed to `popUpContextMenu` is not referenced elsewhere and garbage collected while still used. A simple workaround is to save the menu object into a variable to keep it from being collected.

**Comment by jackple** [comment]
Also happened in electron@7.1.x, is there any workaround?

**Comment by codebytere** [comment]
Fixed by https://github.com/electron/electron/commit/50cc54e50b58f7b2a39119be4a92c2d300f28ab8.

@jackple yes, from above issue:

>  A simple workaround is to save the menu object into a variable to keep it from being collected.
