### ISSUE TITLE
Reuse //gin in codebase where possible

### ISSUE THREAD

**Issue by deepak1556** [electron/electron#16443]
This is an effort to refactor `//electron/native_mate`, it was originally created as a fork of `//gin` to add capabilities not supported by chromium https://github.com/electron/electron/pull/231. But moving forward we can extend `//gin` instead with ease, now that the codebase is unified.

- [x] [mate::Arguments](https://github.com/electron/electron/blob/master/native_mate/native_mate/arguments.h) => `gin::Arguments`
  - This has a dependency on the converters which must be transitioned first
  - Missing interfaces that should be extended
     - [ ] `mate::Arguments::GetThis`
- [ ] Remove [native_mate/constructor.h](https://github.com/electron/electron/blob/master/native_mate/native_mate/constructor.h)
   - It only contains dead code
- [x] [mate::Dictionary](https://github.com/electron/electron/blob/master/native_mate/native_mate/dictionary.h) => `gin::Dictionary`
   - This has a dependency on the converters which must be transitioned first
   - Missing interfaces that should be extended
      - [ ] `mate::Dictionary::SetReadOnly`
      - [ ] `mate::Dictionary::SetMethod`
      - [ ] `mate::Dictionary::Delete`
      - [ ] `mate::Dictionary::IsEmpty`
      - [ ] `mate::Dictionary::GetHandle`
- [ ] remove [native_mate/function_template.{cc|h}](https://github.com/electron/electron/blob/master/native_mate/native_mate/function_template.h) for `//gin/function_template.{cc|h}`
   - This has a dependency on `mate::Arguments`
   - Missing interfaces that should be added
      - [ ] `mate::internal::Destroyable` , which is necessary to check for c++ types destroyed by public `destroy()` api
- [x] [mate::Handle](https://github.com/electron/electron/blob/master/native_mate/native_mate/handle.h) => `gin::Handle`
- [ ] [mate::ObjectTemplateBuilder](https://github.com/electron/electron/blob/master/native_mate/native_mate/object_template_builder.h) => `gin::ObjectTemplateBuilder`
   - Missing interfaces that should be extended
      - [ ] `mate::ObjectTemplateBuilder::MakeDestroyable`
- [ ] [mate::WrappableBase](https://github.com/electron/electron/blob/master/native_mate/native_mate/wrappable_base.h) => `gin::WrappableBase`
   - Missing interfaces that should be extended
      - [ ] `mate::WrappableBase::AfterInit`
      - [ ] `mate::WrappableBase::InitWith`
- [ ] [mate::Wrappable](https://github.com/electron/electron/blob/master/native_mate/native_mate/wrappable.h) => `gin::Wrappable`
   -  Missing interfaces that should be extended
      - [ ] `mate::Wrappable::Init`
      - [ ] `mate::Wrappable::(Set/Get)Constructor`
- [x] remove [native_mate/converter.{cc|h}](https://github.com/electron/electron/blob/master/native_mate/native_mate/converter.h) for `//gin/converter.{cc|h}`
   - Add missing converters
- [x] Move `mate::PersistentDictionary`, `mate::Promise`, `mate::ScopedPersistent` under `gin` namespace

/cc @zcbenz

**Comment by zcbenz** [comment]
I think this task is hard because all native-mate classes relies on each other and it is extremely difficult to migrate all of them at once.

I'm going to try a different approach:
1. Create a new `Constructor` class in `gin` with features of `mate::Wrappable`, and only uses things from `gin`.
2. Gradually migrate users of `mate::Wrappable` to the new `Constructor` class.
3. (Kill the `Constructor` class and use `gin::Wrappable` if possible.)
4. Do the same approach for callback converters.
5. Everything else should be much easier to move now.
