### ISSUE TITLE
Moving a BrowserWindow to another display applies the "Scale" of the current

### ISSUE THREAD

**Issue by danailbd** [electron/electron#16444]
* Electron version: 3.1.0
* Operating System (Platform and Version): Windows 10 Enterprise, 1803
 
When having a setup of two (or more) displays with mismatching "scaling" factors, calling `BrowserWindow.setBounds()` with a position that is on the other display, results in both the new position and the size of the window being based on the "scaling" factor of the display where the window was at before invoking the method.
 
### Expected behavior
 
When a BrowserWindow is positioned on a **display, different from the primary display (regardless of the "scaling" factor)**, using `BrowserWindow.setPosition(0, 0)` would position the window at the *top left corner of the primary display*
 
Furthermore, for two sequential calls, e.g. of `BrowserWindow.setBounds({ x: 0, y: 0, width: 100, height: 100) })`, the latter call should affect neither the position nor the size of the window
 
### Actual behavior
 
Using `setPosition(0, 0)` doesn't position the window at the top left corner on the primary display but at some different place instead. It might even be the case that it is not positioned **on the primary display** at all but somewhere off screen instead, e.g. `{x: -222, y: -103}` (this was reported by the `getPosition()` method of the window after the window repositioning had took place).
 
Similar behaviour is observed for the `setBounds()` method as well:
- positioning behaves the same way;
- the size is based on the scale factor of the other display
 
Invoking `setBounds({ x: 0, y: 0, width: 100, height: 100) })` twice would:
* **with the first call**, the window is positioned somewhere on the primary display with some scaled size
* **with second call**, the window is both correctly positioned and resized
 
 
**In case both displays share the same scale , the positioning and resizing of BrowserWindow-s behave as expected.**
 
 
### To Reproduce
Steps:
1. Add a second display
2. Position the second display on the right side of the primary display
3. Change the display "Scale" factor (e.g. to 150%) so that it differs with the one for the primary display
4. Run the Electron the basic program:
```
const {app, BrowserWindow} = require('electron')
app.disableHardwareAcceleration();
 
let mainWindow
 
function createWindow () {
    // Create the browser window.
    mainWindow = new BrowserWindow({
        width: 300, height: 300,
        show: true
    })
    mainWindow.loadURL('http://github.com')
 
    mainWindow.setPosition(
        10000, // ensure the window is far enough to the right so that
               // it is relative to the second (non-primary) display
        0
    );
 
    setTimeout(function() {
        // bring the window back to the primary display
        mainWindow.setBounds({
            x: 0, y: 0,
            width: 300, height: 300 // same as the initial
        });
        console.log("Moved", mainWindow.getPosition());
    }, 4000);
}
 
app.on('ready', createWindow)
 
app.on('window-all-closed', function () {
    if (process.platform !== 'darwin') {
        app.quit()
    }
});
```
4. The BrowserWindow should be positioned at the top left corner of the primary display

**Comment by danailbd** [comment]
Sounds similar to https://github.com/electron/electron/issues/9560

**Comment by zona-ciq** [comment]
Also if you move the window to a different monitor when the scaling of the main display is not 100%, the window resizes itself and is no longer the size that you set it to be.

If you pass in:
```
mainWindow = new BrowserWindow({
    height: 1361,
    width: 2560,
    y: 0,
    x: -2560,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js')
    }
  })
```
The actually window's width and height become 2048 and 1113 respectively. (my scaling factor of the main display is 125%)

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by pushkin-** [comment]
This should really be merged with [this](https://github.com/electron/electron/issues/10862)

**Comment by nornagon** [comment]
Duplicate of #10862.
