### ISSUE TITLE
require(‘module-name’) in render process 

### ISSUE THREAD

**Issue by mrudangit** [electron/electron#16449]
When we do require module name in render process does is remotely open in main process and stuff goes back and for over ipc or it is opened in render process with out any ipc we can call methods ?
electron version 4.0.1

**Comment by MarshallOfSound** [comment]
No, if you have `nodeIntegration` enabled in the renderer without sandbox enabled then `require` in the renderer does all it's work in the renderer process, there is no back and forth.

**Comment by mrudangit** [comment]
in Later version i see we will have to do require.remote.require so it means everything will be in main process ?
