### ISSUE TITLE
backdrop-filter: blur() extending past window border

### ISSUE THREAD

**Issue by Stilldabomb** [electron/electron#16457]
* Output of `node_modules/.bin/electron --version`: v4.0.0-beta.11
* Operating System (Platform and Version): macOS 10.14.2
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
`backdrop-filter: blur()` should only blur the background contents, and not the outside of the visible area.

**Actual behavior**
If an element is placed near the edges of a window, and it has a `background-filter: blur()`, it will blur the background color (or behind the window if using `vibrancy`), instead of the contents behind the element.

It can easily be solved by putting a background color on the window, but that doesn't help with `vibrancy`, where I want some of the window to not have a background color.

I've tried extending the background element past the window, but that didn't do anything to help :(

**To Reproduce**
https://github.com/Stilldabomb/electron-quick-start/tree/backdrop-filter-blur-issue

**Screenshots**
<img width="912" alt="screen shot 2019-01-18 at 5 15 51 pm" src="https://user-images.githubusercontent.com/4196356/51420149-c0547f80-1b44-11e9-9b90-b29efa2984d7.png">

<img width="1687" alt="screen shot 2019-01-18 at 4 33 17 pm" src="https://user-images.githubusercontent.com/4196356/51419968-6bfcd000-1b43-11e9-905d-ff191d3fdafe.png">

**Additional Information**

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
