### ISSUE TITLE
Wrong color of inactive menu bar on Linux

### ISSUE THREAD

**Issue by Isolus** [electron/electron#16455]
* Electron version: 3.0.14
* Operating system: Manjaro (Arch based Linux with Xfce)

### Expected behavior
The color of an inactive menu bar should match the color of an inactive menu bar of other apps.

### Actual behavior
The color of an inactive menu bar is darkened.

### How to reproduce
You can see this if you compare a terminal window to an electron app (here the newest signal release).
If the electron app window is active, it looks ok.
![menu_bar_active](https://user-images.githubusercontent.com/3437355/51394686-410e7e00-1b3b-11e9-9f58-8b10e5ea0dcb.png)
However, if the window is not active, the menu text becomes darker (this doesn't happen in the terminal window below which is also inactive).
![menu_bar_inactive](https://user-images.githubusercontent.com/3437355/51394685-410e7e00-1b3b-11e9-9e5b-3009dd48e0f4.png)
It looks like this code [here](https://github.com/electron/electron/blob/master/atom/browser/ui/views/menu_bar.cc#L309) does that but I don't know why.
On my system this behaviour matches none of the included window manager themes.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

**Comment by codebytere** [comment]
This should be fixed in versions of Electron 4 and above.

**Comment by Isolus** [comment]
This isn't fixed in Electron 5.0.4.
