### ISSUE TITLE
Add a `BrowserWindows.getMediaSourceId()` method

### ISSUE THREAD

**Issue by nrdobie** [electron/electron#16460]
**Is your feature request related to a problem? Please describe.**
When using `navigator.mediaDevices.getUserMedia` to get a stream of a window you have to use the `desktopCapture.getSources` function. The issue I am having is that the only way to find your app's BrowserWindow is my checking the title of all visible windows which seems a little fragile to me.

**Describe the solution you'd like**
It would be nice to have a `BrowserWindow.getMediaSourceId()` function to quickly get a specific window's id. 

**Describe alternatives you've considered**
Right now I created a utility that will watch for an IPC request and will temporarily switch the title to a UUID for me to match against. Unless I missed something in the documentation, I didn't see a way to get the source id.

**Comment by CapOM** [comment]
Hi @nrdobie, do you to work on this ?

**Comment by nrdobie** [comment]
@CapOM I have not worked on this issue.

**Comment by CapOM** [comment]
Done. This can be closed.
