### ISSUE TITLE
4.0 regression: creating a window larger than primary physical display on linux

### ISSUE THREAD

**Issue by kwindla** [electron/electron#16465]
* Output of `node_modules/.bin/electron --version`: 4.0.1
* Operating System (Platform and Version): Ubuntu 16.04
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):
3.0.6

**Expected Behavior**
It seems that it is no longer possible to create a BrowserWindow that is larger than the primary physical xrandr monitor on Linux, even when running X with no window manager. This was possible up through 3.0.6.

For example, on an X configuration with two physical monitors that are each 1920x1080, configured as a single X screen that is 3840x1080 (with no window manager running), the following code should create a 3840x1080 window. This works as expected through 3.0.6
```
shellWindow = new BrowserWindow (
    { x: 0, y: 0,
      frame: false,
      width: 3840,
      height: 1080,
      show: false
    });
```

**Actual behavior**
In 4.0.0 and 4.0.1, the above code creates a 1920x1080 window.

Setting `enableLargerThanScreen` to true does not change the behavior.

This is not a window manager issue. We ship a hardware appliance and run X without a window manager.

**To Reproduce**
Start X with a very simple .xinitrc. For example:
```
xhost +
while true
do
  /bin/sleep 60
done
```
Then attempt to create a BrowserWindow that is larger than the primary xrandr "monitor".

**Additional Information**

Our hardware appliance can have either one or two HDMI outputs active. We always configure X as a single screen. So when two xrandr "monitors" are available, the X screen size is 3840x1080. We could create "full sized" electron windows that spanned both HDMI outputs until 4.0.0. I apologize for not finding this issue during the 4.0.x beta period.

It is possible in 4.0.x to `setSize()` the BrowserWindow instance to larger-than-primary-display size immediately after creating it (even before the ready-to-show event). This is a possible workaround for this regression. (In our case, however, some of our front-end code does layout calculations based on the initial size of the browser content area, however, so until we rewrite that code the workaround comes with potential timing-related bugs.)

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
