### ISSUE TITLE
tray left click linux open right click context menu

### ISSUE THREAD

**Issue by LogX7** [electron/electron#16462]
* Operating System (Platform and Version): LINUX MINT 19 - with Cinnamon 3.8.9

**Expected Behavior**
minimize and maximize window to tray

**Actual behavior**
right click context menu opens up

**To Reproduce**
You can run [CPARINE](https://github.com/sindresorhus/caprine)

**Comment by LogX7** [comment]
@sofianguy  what do i need to add ?

**Comment by mkermani144** [comment]
@sofianguy 
Why did you close this? Is the problem resolved for you? I have the same issue.

**Comment by brenca** [comment]
@mkermani144 The issue was closed by @LogX7, I suggest you ask him why he closed it.

**Comment by LogX7** [comment]
i closed it because nobody cared

**Comment by mkermani144** [comment]
Maybe we can reopen this issue.

**Comment by shenron** [comment]
I'm using Archlinux with i3wm I have the same problem. The context menu can only be opened only with right click.

**Comment by LogX7** [comment]
@sofianguy  what info do i need to add ?

**Comment by codebytere** [comment]
@LogX7 we need specific steps to reproduce this ("run Caprine" is not sufficient) as well as the specific version of Electron this occurred on.

**Comment by akontsevich** [comment]
Reproducible with libappindicator3 (libappindicator-gtk3) package installed with any electron version including latest. Reproducible with Riot for ex. Works fine if package is not installed. However icon looks weird, see: https://github.com/vector-im/riot-web/issues/7553

**Comment by gerroon** [comment]
THis can be reproduced with any App like Joplin, Riot, Trilium etc on Debian Buster Xfce, assumming libappindicator is the installed

**Comment by LogX7** [comment]
please reopen ?

**Comment by logxseven** [comment]
why is this issue closed ? just run any electron app with libappindicator3 (as @akontsevich mentioned) and you can see the issue ... i don't understand what kind of reproduction steps you need @codebytere

**Comment by jimmy213** [comment]
Any suggestions for this issue? It keeps happening with Caprine, Skype, Discord, etc.
