### ISSUE TITLE
Input in devtools console will not display completely

### ISSUE THREAD

**Issue by d1y** [electron/electron#16461]
**Platform**
- node:  '11.6.0'
- platform: `darwin`
**Screenshots**
![image](https://user-images.githubusercontent.com/45585937/51423161-598f9e80-1bf6-11e9-87c4-bb1e56e5c4fb.png)

So, what's going on here?👀

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
