### ISSUE TITLE
Electron crashes while running under nvidia-xrun

### ISSUE THREAD

**Issue by minecraft2048** [electron/electron#16471]
* Output of `node_modules/.bin/electron --version`:
```
 feanor  silmaril  ~  $  electron --version
v3.0.13
```

* Operating System (Platform and Version):

Arch Linux

**Expected Behavior**
All Electron apps can run

**Actual behavior**
Electron crashes with this:
```
feanor  silmaril  ~  $  atom --safe
/usr/bin/electron: symbol lookup error: /usr/bin/electron: undefined symbol: _ZN2v87Context3NewEPNS_7IsolateEPNS_22ExtensionConfigurationENS_10MaybeLocalINS_14ObjectTemplateEEENS5_INS_5ValueEEENS_33DeserializeInternalFieldsCallbackE
```
(using Atom as example, running Electron directly causes the same problem, see https://github.com/atom/atom/issues/18724)

**To Reproduce**

1. Run a DE under nvidia-xrun, in my case I'm using Xfce4 with startxfce4 as its launcher
2. Start any Electron app, either `electron` or Atom

**Comment by nornagon** [comment]
Is this reproducible with Electron 4?

**Comment by minecraft2048** [comment]
At least with Electron 4.0.2 installed using `npm install electron --save-dev` it doesn't crash:
```
 feanor  silmaril  ~  electron-test  node_modules  electron  dist  $  ./electron --version
v4.0.2
```

Unfortunately the system Electron package in Arch repos are outdated, so I can't check whether this will fixes all Electron apps that I have

**Comment by nornagon** [comment]
In that case this seems like an Arch issue, not an Electron issue. Closing for now but happy to work with Arch maintainers to find a solution.
