### ISSUE TITLE
Feature: HTTP preconnect

### ISSUE THREAD

**Issue by robatwilliams** [electron/electron#16476]
* Output of `node_modules/.bin/electron --version`: 4.01 (originally discovered using 2.0.13)
* Operating System (Platform and Version): Windows 10 64-bit
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): n/a

**Expected Behavior**
Should behave as standalone Chromium does when loading remote pages:
* When a page provides a `preconnect` resource hint via a response header or link tag, it should preemptively preconnect to the specified domain
* When loading a page that hasn't been seen before, it should preemptively open 2 connections to the origin
* When loading a page that has been seen before, it should use collected data from previous visits to preemptively open however many connections it believes are likely to be necessary

**Actual behavior**
No preconnects are made in any of the above scenarios. This is verified by the absence in the network log of any `HTTP_STREAM_JOB_CONTROLLER` events with `is_preconnect = true`. 

**To Reproduce**
~~I don't have a repo I can share, but...~~ See repo & instructions in immediately-following comments. Starting a window with `--log-net-log=C:\log.json` and causing the scenarios above, will reveal in the log that no preconnects are made. Do the same with a standalone Chromium (same v69), and preconnects are made.

**Screenshots**
n/a

**Additional Information**
⚠️ edited to add: feature not part of the content module? See [comment](https://github.com/electron/electron/issues/16476#issuecomment-456972406)

I've looked through the Chromium source code to find the expected behaviour described above - I believe the relevant parts are [loading_predictor.cc:PrepareForPageLoad](https://chromium.googlesource.com/chromium/src/+/69.0.3497.128/chrome/browser/predictors/loading_predictor.cc#70), [loading_predictor.cc:AddInitialUrlToPreconnectPrediction](https://chromium.googlesource.com/chromium/src/+/69.0.3497.128/chrome/browser/predictors/loading_predictor.cc#27), and [resource_prefetch_predictor.cc:PredictPreconnectOrigins](https://chromium.googlesource.com/chromium/src/+/69.0.3497.128/chrome/browser/predictors/resource_prefetch_predictor.cc#211). While I've been able to debug code found in the electron repo, I haven't been able to debug this because the symbols aren't in the PDB file.

This existing [question](https://stackoverflow.com/questions/50377941/preconnect-resource-hint-not-working-in-electron-but-works-fine-in-chrome) on StackOverflow appears to be having the same problem.

#5145 was closed due to resource hints not being supported in Chromium's webview tag. However, the MDN [compatibility table](https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content#Browser_compatibility) says they are supported from v50. Regardless, this issue I'm reporting isn't dependent on using webview or hints.

I have some suspicion that preconnect isn't enabled at all, as unlike standalone Chromium, no prediction data collection file is created in the user profile (`Network Action Predictor` SQLite). Possibly relevant: [loading_predictor_config.cc:IsLoadingPredictorEnabled](https://chromium.googlesource.com/chromium/src/+/69.0.3497.128/chrome/browser/predictors/loading_predictor_config.cc#83)

**Comment by robatwilliams** [comment]
Reproduction steps follow. The network log for equivalent page loads in Electron and Chromium are captured and then compared using the [netlog-viewer](https://netlog-viewer.appspot.com) tool.

## Preparation
```
git clone git@github.com:robatwilliams/electron-quick-start.git
npm install
```

Download the standalone Chromium of the same version (69.0.3497.106) that Electron 4.01 is using from [here](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/576753/). The base branch version was obtained by inputting the Chromium version into the Version Information tool at [OmahaProxy](https://omahaproxy.appspot.com).

## Resource hint case (via response header)
1. Chromium
   1. `chrome.exe --log-net-log=./net-log-chromium.json`
   1. Navigate to https://preconnect.herokuapp.com/
   1. Close the browser window
1. Electron
   1. `git checkout -b http-preconnect-16476-header-hint`
   1. `npm start -- --log-net-log=./net-log-electron.json`
   1. Close the electron window
1. Compare the network logs
   1. Import the two log files into separate instances of the netlog-viewer
   1. Open the `URL_REQUEST` event for the page in either log. Observe that the response includes the header `Link: <https://fonts.gstatic.com>; rel=preconnect; crossorigin;`
   1. Search for "is_preconnect = true" in both viewers
   1. Notice that in the Chromium log, there is at least one `HTTP_STREAM_JOB_CONTROLLER` event to https://fonts.gstatic.com. This will (see nearby events) connect a socket. Notice that in the Electron log, there is no such preconnecting controller.
   1. Search for `"type:HTTP_STREAM_JOB_CONTROLLER"` in the Electron net log. See that an equivalent job does exist, but it's only created in response to a later `URL_REQUEST` event.

**Comment by robatwilliams** [comment]
## Heuristic guessing case (preconnect to origin)
It's possible to observe this in the resource hint case too, but the following is provided for isolation purposes.

1. Chromium
   1. As above, but use https://dailyfx.com/gbp-usd (or any page that needs more than one connection)
1. Electron
   1. `git checkout -b http-preconnect-16476-default-guessing`
   1. Then, as above
1. Compare the network logs
   1. As above: notice in particular a preconnect to the origin domain that is done in Chromium, but which doesn't happen in Electron
   1. There are also various other preconnects done in Chromium; I presume these are heuristically guessed

**Comment by robatwilliams** [comment]
## Heuristic guessing case (learning from past visits)
Given that the basic preconnect to origin behaviour doesn't happen in Electron, it's no surprise that this doesn't happen either.

Comparing our original Electron 2.0.13 against the equivalent Chromium 61, it was noticed that Chromium would learn from previous visits to a site that needs/can make use of many connections. So the next time it was visited, e.g. 6 connections would be preconnected instead of 2. This is shown by a `HTTP_STREAM_JOB` with `SOCKET_POOL_CONNECTING_N_SOCKETS` `num_sockets = 6`.

This learning doesn't seem to happen in Chromium 69 (equivalent of Electron 4.01). Perhaps the learning process has changed. Doing a binary-ish search of the in-between and surrounding versions reveals that the change happened in Chromium 66.
* versions seen to learn to preconnect more connections on 2nd visit: 61, 65
* versions seen to continue preconnecting only two connections on 2nd visit: 66, 67, 69, 71

**Comment by robatwilliams** [comment]
Looking at the [changelog](https://chromium.googlesource.com/chromium/src/+log/65.0.3325.0..66.0.3359.0?&n=10000) between Chromium 65 and 66 and searching for "preconnect" reveals this commit

[Enable SpeculativePreconnect Field Trial Testing](https://chromium.googlesource.com/chromium/src/+/8442e044284223377ccd75e4f1b519c5656d4d8d) "This CL reenables SpeculativePreconnect field trial since the fix https://crrev.com/c/778899 addressing performance regressions was landed."

That linked bug "predictors: Preconnect to the main frame after navigation hints" mentions "Open minimum 2 sockets for the main page.", and touches some of the files I mentioned in the description. So it appears that either enabling the new behaviour or fixing that bug has affected the learning behaviour.

**Comment by robatwilliams** [comment]
I'm now able to share a reproduction of the heuristic/speculative preconnect case of this issue, that occurs on a public variant of our application.

Follow the steps as I described above in "Heuristic guessing case (preconnect to origin)", using the URL https://www.saxoinvestor.dk/sim/investor-demo/# for Chromium and the branch `http-preconnect-16476-saxoinvestor` for Electron.

* Electron 4.01 will not make any preconnects (no `is_preconnect = true` or `SOCKET_POOL_CONNECTING_N_SOCKETS`)
* Chromium 61
  * first visit: Two `HTTP_STREAM_JOB_CONTROLLER` events to https://www.saxoinvestor.dk with `is_preconnect = true` happen at the same timestamp. The `HTTP_STREAM_JOB` of the second one connects 2 sockets as seen by `SOCKET_POOL_CONNECTING_N_SOCKETS` `num_sockets = 2`
  * second visit: the second stream job connects 6 sockets
* Chromium 69
  * first visit: One job controller, whose stream job connects 2 sockets
  * second visit: same as for the first visit

So I think there are two questions:
1. Why does Electron not preconnect at all?
1. Why does Chromium 66 onwards not learn to do more preconnects, and is the change intentional?

It's the preconnecting behaviour in Electron that's most important to us, since our application in Electron is more demanding. This is especially visible when launching on high latency connections. For our use case, it would perhaps be preferrable to be able to explicitly request a given number of connections to a particular domain be made, via an option to the `BrowserWindow` constructor.

**Comment by nornagon** [comment]
Unfortunately, what is/isn't in `content` changes frequently, and isn't well documented in Chromium. It wouldn't be completely surprising to me if at some point in the future, preconnection moved into `content`. There's not really a bright line between the two.

I've updated the title of this PR to reflect your discoveries (thank you, by the way, for investigating and reporting back!)

**Comment by robatwilliams** [comment]
Thanks.

Aside: I've created an issue on Chromium, as home of the content module: [Document what is/isn't part of the content module](https://bugs.chromium.org/p/chromium/issues/detail?id=924737). Let's see if there's any feedback; it may be considered an internal architectural separation that isn't to be documented for external consumers.

**Comment by nornagon** [comment]
http preconnect is doable now since https://github.com/electron/electron/pull/18671.
