### ISSUE TITLE
window.devicePixelRatio  is wrong while register self protocol

### ISSUE THREAD

**Issue by yutent** [electron/electron#16491]
OS: MacOS 10.14.2
Display: 1920*1200 (origin: 2880 x 1800)  on macbook  pro 2017 15"
Electron: 4.0.0

Issue:  

my code: window.devicePixelRatio is wrong.
```
protocol.registerStandardSchemes(['app'], { secure: true })

app.once('ready', _ => {

  protocol.registerBufferProtocol('app', (req, cb) => {
     // todo....
  })

  let win = new BrowserWindow({
    width: 300,
    height: 200
  })
  win.loadURL('app://demo.html')
  win.openDevTools()
})

```
 Then, I print the `window.devicePixelRatio` on the devTools. It show  `2.190890312194824`(expect to 2).

If I use `win.loadURL('file:///path_of_demo.html')`. `window.devicePixelRatio` is now `2`.

**Comment by yutent** [comment]
I found that it only happens when `win.loadURL('app://sonist/index.html')`. I rename to another name  like `win.loadURL('app://demo/index.html')` it works well.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by yutent** [comment]
几百年了才回复, 黄花菜都凉了

**Comment by mirrorlink** [comment]
I have the very same issue. it seem it gets the wrong value after you mess up with zoomFactor, or settings deviceSize manually, or even the force-scale chromium settings option. One of these things. I cannot find another solution besides renaming the directory

**Comment by Rabbitzzc** [comment]
fuck

**Comment by pie6k** [comment]
I found out that changing zoom factor or zoom level on one window - somehow impacts device pixel ratio on all of them, even in the future, after app restart.

```ts

  mainWindow.webContents.setZoomLevel(1);
  mainWindow.webContents.setZoomFactor(1);
``` 

helped in my case. I left it there to be run on every app start.
