### ISSUE TITLE
print slient 参数无法正确使用

### ISSUE THREAD

**Issue by nikolamakin** [electron/electron#16499]
const printButton = document.getElementById('printButton');
    printButton.addEventListener('click',(event) => {
        const webview = document.querySelector('#printWebview')
        alert(webview)
        //webview.send('webview-print-render')
        webview.print({ silent: true, printBackground: true, deviceName: 'XP-80C' },
            (data) => {
                console.log("webview success", data);
            }
        )
    })

无论我 silent 是 true  还是 false 都会弹出打印机列表。是BUG吗？还是我哪里有问题？

**Comment by nornagon** [comment]
Duplicate of #14072
