### ISSUE TITLE
webcontents getType() method not documented or typed

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#16495]
* Output of `node_modules/.bin/electron --version`: Node 10.11
* Operating System (Platform and Version): Windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): Electron 4.0.1

Looks like WebContents has a `getType()` method on it, but this is not documented [here](https://electronjs.org/docs/api/web-contents), and the typings don't have that function, so I have to cast to `any`:

    app.on("web-contents-created", (e: Electron.Event, contents: Electron.WebContents) => {
        if ((contents as any).getType() === "webview") { }
    });

Can typings and documentation be added?

**Comment by emer7** [comment]
@codebytere Hi I am new in contributing to open source software. Can I try working on this issue?

**Comment by codebytere** [comment]
sure! you'll need to clone down electron, but for this specifically you won't need to build it from scratch. All you'll need to do is to add documentation for this method to https://github.com/electron/electron/blob/master/docs/api/web-contents.md, and then run `npm i && npm run create-typescript-definitions`.

Once that's done, you'll need to open `electron.d.ts (created by the previous command) to verify that the documentation was added and typed correctly. Only the changes to https://github.com/electron/electron/blob/master/docs/api/web-contents.md will need to be PR'd into master though!

Feel free to @ me in  a follow-up if i can provide further clarity!

**Comment by radupasparuga** [comment]
Where can I find the source code for the method?

**Comment by MarshallOfSound** [comment]
Documented in #16767

**Comment by pushkin-** [comment]
@MarshallOfSound I only see doc commits. Will typings be updated separately, or is there some automated process that updates typings from the docs? Thanks

**Comment by emer7** [comment]
> Where can I find the source code for the method?

@radupasparuga it's in atom\browser\api\atom_api_web_contents.cc

> I only see doc commits. Will typings be updated separately, or is there some automated process that updates typings from the docs? Thanks

@pushkin- afaik it should be automated. There is npm script `create-typescript-definitions` that is creating the typings.
