### ISSUE TITLE
cursor: can't display on contenteditable div when text is a lot 

### ISSUE THREAD

**Issue by xiaodoulala** [electron/electron#16498]
* Output of `node_modules/.bin/electron --version`: 4.0.1
* Operating System (Platform and Version):mac OS 10.14.2
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):3.1.1

**Expected Behavior**

**Actual behavior**
A clear and concise description of what actually happened.

**To Reproduce**
Your best chance of getting this bug looked at quickly is to provide a REPOSITORY that can be cloned and run.

You can fork [electron-quick-start](https://github.com/electron/electron-quick-start) and include a link to the branch with your changes.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone $YOUR_URL -b $BRANCH
$ npm install
$ npm start || electron .
```
**Screenshots**

**Additional Information**

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
