### ISSUE TITLE
A javascript error in the main process

### ISSUE THREAD

**Issue by reach2jeyan** [electron/electron#16503]
* Output of `node_modules/.bin/electron --version`: v3.0.7
* Operating System (Platform and Version): MacOS Mojave 10.14

**Expected Behavior**
On NPM start, the electron application launches in windows. Similar expected behaviour in MacOS.

**Actual behavior**
Javascript error in the Main process

<img width="416" alt="screenshot 2019-01-23 at 15 00 04" src="https://user-images.githubusercontent.com/20741047/51596701-9bcf1d80-1f1f-11e9-9b7f-6506d25aae9c.png">

**Comment by codebytere** [comment]
@reach2jeyan do you have a small standalone snippet you could give us to reproduce this error?

**Comment by reach2jeyan** [comment]
@codebytere This is the `main.js` I have. I have not changed anything which is present in the electron-quickstart repo. Just added a couple of things more but it works good with windows machine.

```

const {app, BrowserWindow, Menu} = require('electron')

function createWindow () {
  
  mainWindow = new BrowserWindow({width: 800, height: 250})

  
  mainWindow.loadFile('index.html')




  mainWindow.on('closed', function () {

    mainWindow = null
  })
}


app.on('ready', createWindow)

// Quit when all windows are closed.
app.on('window-all-closed', function () {
  // On macOS it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', function () {
  // On macOS it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (mainWindow === null) {
    createWindow()
  }
})
const template = [
  {
    label: 'Edit',
    submenu: [
      { role: 'undo' },
      { role: 'redo' },
      { type: 'separator' },
      { role: 'cut' },
      { role: 'copy' },
      { role: 'paste' },
      { role: 'pasteandmatchstyle' },
      { role: 'delete' },
      { role: 'selectall' }
    ]
  },
  {
    role: 'help',
    submenu: [
      {
        label: 'Learn More',
        version: '0.0.1',
        click () { require('electron').shell.openExternal('https://github.com/reach2jeyan/PasswordsCreator') }
      }
    ]
  }
]

if (process.platform === 'darwin') {
  template.unshift({
    label: app.getName(),
    submenu: [
      { role: 'about' },
      { type: 'separator' },
      { role: 'services' },
      { type: 'separator' },
      { role: 'hide' },
      { role: 'hideothers' },
      { role: 'unhide' },
      { type: 'separator' },
      { role: 'quit' }
    ]
  })

  // Edit menu
  template[1].submenu.push(
    { type: 'separator' },
    {
      label: 'Speech',
      submenu: [
        { role: 'startspeaking' },
        { role: 'stopspeaking' }
      ]
    }
  )

  // Window menu
  template[3].submenu = [
    { role: 'close' },
    { role: 'minimize' },
    { role: 'zoom' },
    { type: 'separator' },
    { role: 'front' }
  ]
}

const menu = Menu.buildFromTemplate(template)
Menu.setApplicationMenu(menu)
```

**Comment by vladimiry** [comment]
@reach2jeyan did you try calling `Menu.setApplicationMenu` after `ready` event called on the `app` as written in the [docs](https://electronjs.org/docs/api/menu#menusetapplicationmenumenu)?

```
Menu.setApplicationMenu(menu)

Sets menu as the application menu on macOS. On Windows and Linux, the menu will be set as each window's top menu.
```

**Comment by reach2jeyan** [comment]
@vladimiry Thanks! Ill try that out on app.ready but can you explain why the current code works in windows but not on mac? And is this change generic across platforms again?

**Comment by codebytere** [comment]
@reach2jeyan 
> Just added a couple of things more
is a wide range of potential issues, we'd need to see a standalone reproducible code snippet in order to best diagnose it.

**Comment by codebytere** [comment]
We haven't gotten a response to the question in the comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
