### ISSUE TITLE
getDisplayMedia with Chrome 72 throwing Not Allowed

### ISSUE THREAD

**Issue by iclems** [electron/electron#16513]
* Output of `node_modules/.bin/electron --version`: v5.0.0-nightly.20190107
* Operating System (Platform and Version): macOS Mojave 10.14.2 (18C54)
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): never

**Expected Behavior**
Using navigator.mediaDevices.getDisplayMedia({ video: true }), a native screen picker should appear.

**Actual behavior**
The following error is thrown: NotAllowedError: Permission denied

**Screenshots**
Expected dialog
![image](https://user-images.githubusercontent.com/1120050/51625551-71736500-1f0b-11e9-9a95-1406cad95046.png)

**Comment by codebytere** [comment]
@iclems this is probably: https://github.com/electron/electron/issues/16508

**Comment by MarshallOfSound** [comment]
> Using navigator.mediaDevices.getDisplayMedia({ video: true }), a native screen picker should appear.

This behavior isn't expected for Electron's case.  If we were to implement the plumbing required for this to work we would implement it similar to [`select-bluetooth-device`](http://electronjs.org/docs/api/web-contents#event-select-bluetooth-device) where we emit all possible options and then the app is responsible for the "choosing" part, whether that is through a UI or just choosing a specific device by default 🤷‍♂️

**Comment by iclems** [comment]
Interesting. I understand the previous perspective on this feature but it is now part of the WebRTC standards and no longer a Chrome-specific capability implemented through extensions. It sounds strange to have an official W3C "stable" API that needs to be rebuilt via private SDKs. Certainly makes sense in the short-term, but I would assume the long-term path should be: the official API works, but developers can build a custom UI instead if they like?

**Comment by aabuhijleh** [comment]
Unfortunately, Electron's desktopCapture is broken on Windows 10. All Chromium based windows including the electron window itself will have black thumbnails and cannot be shared via WebRTC correctly. I thought when Electron used chromium 72 we would be able to use Chrome's screen sharing picker which is working perfectly :(

**Comment by iclems** [comment]
FYI even with 5.0.0-beta.3 which includes the fix this is still not working throwing NotAllowedError: Permission denied.

**Comment by codebytere** [comment]
@brenca ☝️

**Comment by iclems** [comment]
@brenca @sofianguy @codebytere could you reopen and make sure this isn't marked as fixed in the release notes as I just tested again in beta 5 and it is still throwing NotAllowedError: Permission denied. I'm happy to help fix it but I'm not an expert in the native binding behind it

**Comment by MarshallOfSound** [comment]
Haven't confirmed but re-opening, @brenca can you double check this?  Feel free to close again if the fix has indeed been applied successfully

**Comment by connetcom** [comment]
Hi any update on this or is there an alternative place to track status? I am on Chrome 73.0.3683.90 on Android 8.0.0.

Thanks

**Comment by nornagon** [comment]
Hi @connetcom, Electron doesn't run on Android so we can't possibly be responsible for whatever issue you're running into. You might have better luck at crbug.com.

**Comment by connetcom** [comment]
Thanks for the link and sorry i had somehow shifted into the wrong thread as i was looking at a bunch of stuff at the same time and did not realize that i was on electron.

**Comment by juniiorlima** [comment]
> * Output of `node_modules/.bin/electron --version`: v5.0.0-nightly.20190107
> * Operating System (Platform and Version): macOS Mojave 10.14.2 (18C54)
> * Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): never
> 
> **Expected Behavior**
> Using navigator.mediaDevices.getDisplayMedia({ video: true }), a native screen picker should appear.
> 
> **Actual behavior**
> The following error is thrown: NotAllowedError: Permission denied
> 
> **Screenshots**
> Expected dialog
> ![image](https://user-images.githubusercontent.com/1120050/51625551-71736500-1f0b-11e9-9a95-1406cad95046.png)

Solution:

https://qiita.com/gtk2k/items/ac08ddeeaf74f3126f81

**Comment by iclems** [comment]
I agree the above mentioned link states a correct workaround but it uses the long supported DesktopCapture. The topic here is about supporting a now standard WebRTC API.

**Comment by angelohub** [comment]
Is there any update for this? Would be great to be able to use the new WebRTC API for screensharing.

**Comment by CapOM** [comment]
@iclems If getDisplayMedia was working in electron as expected, would the user still have the use the UI picker provided by chromium or is it possible to avoid that and still enumerate the sources ? So one can implement its own UI for the picker ?

**Comment by JerryFZhang** [comment]
Any updates on this? Thanks!

**Comment by ffflorian** [comment]
This is still the case for Electron 6.1.2 and 7.0.0.

**Comment by squalle0nhart** [comment]
Any update ? It's good if electron support standard WebRTC API.

**Comment by saghul** [comment]
There is no chance this is supported on Electron unless either of these is met:

1) Electron implements a picker UI (which they have refused to do so far)
2) Electron creates a non-standard constraint for `getDisplayMedia` so the source ID can be passed

Chrome has no intention to deprecate using `getUserMedia` for desktop capture (all you can do now on Electron) in the near future.

**Comment by zsinba** [comment]
and update for this?

**Comment by saghul** [comment]
Folks, stop asking. See https://github.com/electron/electron/issues/16513#issuecomment-557434953

**Comment by MurzNN** [comment]
So that https://github.com/electron/electron/pull/16763 PR not fix this issue?

**Comment by saghul** [comment]
No.

**Comment by WesselKroos** [comment]
I was able to polyfill getDisplayMedia using the desktopCapturer so that I can share the same code in Electron and the browsers. **I've only tested it in Windows 10.**
If need I can wrap it in a npm package with some options to make the implementation easier.

### Adding the polyfill to a BrowserWindow
If you want to add the polyfill to a BrowserWindow with an external website or file in it you need to preload it in the session to make it available to the website. Here is an example script that loads the polyfill in a BrowserWindow:

**main.js**
```javascript
const { BrowserWindow } = require('electron')

const win = new BrowserWindow({ width: 800, height: 600 })
win.webContents.session.setPreloads([path.join(__dirname, 'preload-get-display-media-polyfill.js')])
win.loadURL('https://example.com')
```

### The polyfill
The polyfill overrides the native mediaDevices.getDisplayMedia implementation. The getDisplayMedia override gets the sources from the desktopCapturer and displays them in a list in the body tag. (You can use the <style> tag at the bottom of this post to style it like an overlay.)
The user can click on a source and then the getDisplayMedia promise resolves the source.

**preload-get-display-media-polyfill.js**
```javascript 
const { desktopCapturer } = require('electron')
window.navigator.mediaDevices.getDisplayMedia = () => {
  return new Promise(async (resolve, reject) => {
    try {
      const sources = await desktopCapturer.getSources({ types: ['screen', 'window'] })

      const selectionElem = document.createElement('div')
      selectionElem.classList = 'desktop-capturer-selection'
      selectionElem.innerHTML = `
        <div class="desktop-capturer-selection__scroller">
          <ul class="desktop-capturer-selection__list">
            ${sources.map(({id, name, thumbnail, display_id, appIcon}) => `
              <li class="desktop-capturer-selection__item">
                <button class="desktop-capturer-selection__btn" data-id="${id}" title="${name}">
                  <img class="desktop-capturer-selection__thumbnail" src="${thumbnail.toDataURL()}" />
                  <span class="desktop-capturer-selection__name">${name}</span>
                </button>
              </li>
            `).join('')}
          </ul>
        </div>
      `
      document.body.appendChild(selectionElem)

      document.querySelectorAll('.desktop-capturer-selection__btn')
        .forEach(button => {
          button.addEventListener('click', async () => {
            try {
              const id = button.getAttribute('data-id')
              const source = sources.find(source => source.id === id)
              if(!source) {
                throw new Error(`Source with id ${id} does not exist`)
              }
              
              const stream = await window.navigator.mediaDevices.getUserMedia({
                audio: false,
                video: {
                  mandatory: {
                    chromeMediaSource: 'desktop',
                    chromeMediaSourceId: source.id
                  }
                }
              })
              resolve(stream)

              selectionElem.remove()
            } catch (err) {
              console.error('Error selecting desktop capture source:', err)
              reject(err)
            }
          })
        })
    } catch (err) {
      console.error('Error displaying desktop capture sources:', err)
      reject(err)
    }
  })
}
```

### Some basic styling for the source selection overlay
If you want to quickly test the polyfill here is some basic styling for the selection overlay. But of course you can customize this in any direction. You can add the style tag to the innerHTML of the selectionElem object in the polyfill.
```html
<style>
.desktop-capturer-selection {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100vh;
  background: rgba(30,30,30,.75);
  color: #fff;
  z-index: 10000000;
  display: flex;
  align-items: center;
  justify-content: center;
}
.desktop-capturer-selection__scroller {
  width: 100%;
  max-height: 100vh;
  overflow-y: auto;
}
.desktop-capturer-selection__list {
  max-width: calc(100% - 100px);
  margin: 50px;
  padding: 0;
  display: flex;
  flex-wrap: wrap;
  list-style: none;
  overflow: hidden;
  justify-content: center;
}
.desktop-capturer-selection__item {
  display: flex;
  margin: 4px;
}
.desktop-capturer-selection__btn {
  display: flex;
  flex-direction: column;
  align-items: stretch;
  width: 145px;
  margin: 0;
  border: 0;
  border-radius: 3px;
  padding: 4px;
  background: #252626;
  text-align: left;
  transition: background-color .15s, box-shadow .15s;
}
.desktop-capturer-selection__btn:hover,
.desktop-capturer-selection__btn:focus {
  background: rgba(98,100,167,.8);
}
.desktop-capturer-selection__thumbnail {
  width: 100%;
  height: 81px;
  object-fit: cover;
}
.desktop-capturer-selection__name {
  margin: 6px 0 6px;
  white-space: nowrap;
  text-overflow: ellipsis;
  overflow: hidden;
}
</style>
```

**Comment by codyherzog** [comment]
@WesselKroos 

Awesome! Thanks so much.

**Comment by MurzNN** [comment]
Also here https://github.com/hokein/electron-sample-apps/tree/master/desktop-capture is example of custom screen picker

**Comment by pawhtiobo** [comment]
For a noob like me, how do I make those changes that @WesselKroos sugests?

ty

**Comment by CapOM** [comment]
I think the issue is that the picker view (screenshot in this issue description) used in the standard w3c getDisplayMedia is implemented in chromium/src/chrome/browser/ui/views 
 (see https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/ui/views/desktop_capture/desktop_media_picker_views.h;l=20?q=desktopmediapickerviews&ss=chromium%2Fchromium%2Fsrc&originalUrl=https:%2F%2Fcs.chromium.org%2F ) and anything in chromium/src/chrome is not shipped into electron (except a view bits https://github.com/electron/electron/tree/master/chromium_src/chrome/browser )

**Comment by MeirionHughes** [comment]
@WesselKroos kudos. I had to butcher your code to inject it into 3rd party iframe... but I got it working. Cheers.

**Comment by mehulpangtey** [comment]
@WesselKroos I think you should wrap it in an npm package.

**Comment by tanphamanhh** [comment]
in electron 9.2.0, i'm using desktopCapture.getSource(..) to get desktop source, but when I'm using it on my video conferencing application, the other participent voice is recorded to screen sharing aiudio too (chrome 84 does not). I'm currently stuck with how can I remove that voices from screen audio stream.

**Comment by jsheffers** [comment]
Has anyone successfully used the polyfill mentioned above with `contextIsolation` enabled?

**Comment by ruolunhui** [comment]
需要将以下内容注释并替换
 // const mainWindow = new electron_1.BrowserWindow({
    //     frame: !options.hideWindowFrame,
    //     width: mainWindowState.width,
    //     height: mainWindowState.height,
    //     minWidth: options.minWidth,
    //     minHeight: options.minHeight,
    //     maxWidth: options.maxWidth,
    //     maxHeight: options.maxHeight,
    //     x: options.x,
    //     y: options.y,
    //     autoHideMenuBar: !options.showMenuBar,
    //     icon: helpers_1.getAppIcon(),
    //     fullscreen: options.fullScreen,
        
    //     // Whether the window should always stay on top of other windows. Default is false.
    //     alwaysOnTop: options.alwaysOnTop,
    //     titleBarStyle: (_a = options.titleBarStyle) !== null && _a !== void 0 ? _a : 'default',
    //     show: options.tray !== 'start-in-tray',
    //     backgroundColor: options.backgroundColor,
    //     ...windowHelpers_1.getDefaultWindowOptions(model_1.outputOptionsToWindowOptions(options)),
    //     webPreferences: {
    //       contextIsolation: false
    //     },
    // });


替换为以下内容，其余内容参考[韦塞尔克罗斯](https://github.com/WesselKroos)即可

   const optionsData = {...windowHelpers_1.getDefaultWindowOptions(model_1.outputOptionsToWindowOptions(options))};
   optionsData.webPreferences.contextIsolation = false;
   const mainWindow = new electron_1.BrowserWindow({
      frame: !options.hideWindowFrame,
      width: mainWindowState.width,
      height: mainWindowState.height,
      minWidth: options.minWidth,
      minHeight: options.minHeight,
      maxWidth: options.maxWidth,
      maxHeight: options.maxHeight,
      x: options.x,
      y: options.y,
      autoHideMenuBar: !options.showMenuBar,
      icon: helpers_1.getAppIcon(),
      fullscreen: options.fullScreen,
      titleBarStyle: (_a = options.titleBarStyle) !== null && _a !== void 0 ? _a : 'default',
      show: options.tray !== 'start-in-tray',
      backgroundColor: options.backgroundColor,
      ...optionsData,

    })

**Comment by diamond-darrell** [comment]
> Has anyone successfully used the polyfill mentioned above with `contextIsolation` enabled? I don't think this is possible because you have to pass it through the `contextBridge` which doesn't seem to be allowing the stream through. Does anyone have a workaround for this?

hey, regarding contextBridge and not allowing streams, is there any reference in the electron docs about it? I've run into the same problem upon upgrading my electron app and now trying to resolve it as well
