### ISSUE TITLE
Paste Short cut Key(Cmd+v) not working in Angular Save as popup (Mac OS)

### ISSUE THREAD

**Issue by lavanya-106** [electron/electron#16511]
Electron version: 3.0.7
Operating System: Mac OS
Angular Version:  Angular 2

**Expected Behavior**
Paste Shortcut Key(Cmd+v) should work in Save as Popup 

**Actual behavior**
Paste Short cut Key(Cmd+v) not working in Angular Save as popup

**To Reproduce**
1) Create save as dialog using below Code..
2) Now Click on save as options, Save as dialog opened
3) Copy some  foriegn characters like ö: from texteditor/browser
4) now using shout cut keys(Cmd+v) try to paste in save as dialogue box (save as dropdown)
5) cmd+v shortcut not working
Note: Right Click Properties-> Paste is Works well

**Save as popupcode:**
        this.dialog = this._electronService.remote.dialog;
            this.ChooseUrl = this.dialog.showSaveDialog(
                {
                    defaultPath: fileExtension,
                    filters: [
                        { name: this.cxfFiles, extensions: ['cxf'] },
                        { name: this.aseFiles, extensions: ['ase'] },
                        { name: this.allFiles, extensions: ['*'] }
                    ]
                },
                (filename) => {
                    if (filename === undefined) {
                        return;
                    } else {
                        this.fileOpenedFrom = filename;
                    }
                });
		
**Screenshots**
![image](https://user-images.githubusercontent.com/34025440/51739649-ff8c4e80-20b7-11e9-8d8a-0c84c6578fb2.png)

Please suggest me how to achieve this in Save as system dialog using Angular 2

**Comment by meekaah** [comment]
do you have a menu set for your application? if so you also need to have shortcuts for copy and paste to work. take a look at this for example https://github.com/onmyway133/blog/issues/67

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
