### ISSUE TITLE
After toggling fullscreen on frameless window, maximizing the window overflows onto second monitor.

### ISSUE THREAD

**Issue by sbatten** [electron/electron#16514]
The effect of this bug and repro steps are explained in this bug report to VS Code https://github.com/Microsoft/vscode/issues/66906

I can, however reproduce this with electron 4.0.2 and 5beta in Electron fiddle simply by making a window that is frameless and maximizes on startup. When running the fiddle, toggle fullscreen with F11 and see the overlap.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sbatten** [comment]
seems resolved
