### ISSUE TITLE
--ignore-connections-limit flag not having any effect

### ISSUE THREAD

**Issue by robatwilliams** [electron/electron#16527]
* Output of `node_modules/.bin/electron --version`: 4.01
* Operating System (Platform and Version): Windows 10 x64
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): n/a

**Expected Behavior**
* Socket pool for ignored domains does not stall
  * no instances of `SOCKET_POOL_STALLED_MAX_SOCKETS_PER_GROUP` in the network log
* `load_flags` in `URL_REQUEST` events include `IGNORE_LIMITS`, as set by the [network delegate](https://github.com/electron/electron/blob/master/atom/browser/net/atom_network_delegate.cc#L272)

**Actual behavior**
* Socket pool stalls for ignored domains
  * instances of `SOCKET_POOL_STALLED_MAX_SOCKETS_PER_GROUP` present in the network log
* `load_flags` in `URL_REQUEST` events do not include `IGNORE_LIMITS`

**To Reproduce**
1. Throttle network to encourage stalls, e.g. using win-shaper
1. Start with `--ignore-connections-limit=a.b.example.com --log-net-log=./net-log.json`
1. Open the net log using the [netlog-viewer](https://netlog-viewer.appspot.com)
1. See that `HTTP_STREAM_JOB` events exist containing `SOCKET_POOL_STALLED_MAX_SOCKETS_PER_GROUP` are present for jobs on the given domain
1. See that `URL_REQUEST` events only have the flags `load_flags = 0 (NORMAL)`

**Screenshots**
n/a

**Additional Information**
In Electron 2.0.13, the `IGNORE_LIMITS` flag was seen to be set, however only for requests made by the first BrowserWindow that was opened.

#4391 is also about this flag not working, but comments on that issue describe it having an effect on the network log. I'm not too familiar with the Electron source, but the code in the network delegate in this repo suggests a flag should be set on requests, and I'm not seeing that happen.

**Comment by nornagon** [comment]
This fiddle to test websocket connection limiting still works in v4.0.1: https://gist.github.com/89cb0c64983e02b2e519ec832d0b473b

To test:
1. Install [Electron Fiddle](/electron/fiddle)
2. Load the above fiddle
5. Click run

Observe that the connection count goes to 500. If you comment out line 5 of main.js, the connection count stops at 256.

**Comment by robatwilliams** [comment]
Thanks. My only observations are the presence of `SOCKET_POOL_STALLED_MAX_SOCKETS_PER_GROUP` and absence of `IGNORE_LIMITS`, which I found suspicious. If they are expected, then this isn't an issue.

**Comment by nornagon** [comment]
Closing this for now as there's no repro. If you run into issues, please comment and we'll reopen!
