### ISSUE TITLE
ipcMain

### ISSUE THREAD

**Issue by iahmedani** [electron/electron#16523]
Hi everyone!
I'm new to electron one thing is bothering me a lot or can be said unable to understand
is this necessary  to remove listener from both side (ipcRendere and ipcMain)  with same channel ?

Sorry for using this issue tracking area for answer, but I'm in great trouble as my app gets unstable

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
