### ISSUE TITLE
[macOS] PowerSaveBlocker does not prevent display turn off

### ISSUE THREAD

**Issue by szpasztor** [electron/electron#16529]
**Context**
* Output of `node_modules/.bin/electron --version`: v3.0.6
* Operating System (Platform and Version): macOS Mojave 10.14.2 (18C54)

**Expected Behavior**
Using [powerSaveBlocker](https://electronjs.org/docs/api/power-save-blocker) with `prevent-display-sleep` in the main process prevents the computer from sleeping and keeps the display on. 

**Actual behavior**
The computer's display is turned off but sleep mode is prevented (new logs from the app are shown after "waking up").

**To Reproduce**
1. `git clone https://github.com/decred/decrediton.git`
2. Follow setup instructions [here](https://github.com/decred/decrediton#basic-development-setup)
3. `git checkout 3828582361c4af1950a887de93411115cefb48a0`
4. `yarn install`
5. `yarn dev`

**Additional Information**

* See code [here](https://github.com/decred/decrediton/pull/1989/commits/3828582361c4af1950a887de93411115cefb48a0#diff-4fa54749a138460ad8f3583b662fafeaR314)
* `powerSaveBlocker.isStarted(id)` returned `true` in all cases

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
