### ISSUE TITLE
Webview.print() not working properly in 4.0.X

### ISSUE THREAD

**Issue by buffet-time** [electron/electron#16534]
* Output of `node_modules/.bin/electron --version`: 4.0.0
* Operating System (Platform and Version): Windows 10 Enterprise - x64 - 1709
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 3.0.9

**Expected Behavior**
Webview.print() to work as expected and fire and open prompt as expected

**Actual behavior**
Webview.print() works seemingly erratically 

**Additional Information**
Most likely related to https://github.com/electron/electron/issues/16219 however i have tried double calling and it ensures that the first attempt will always work but then subsequent attempts don't work correctly.

**Comment by burningTyger** [comment]
See workaround in #16241 to use `getWebContents()` which probably works here too.

**Comment by hablema** [comment]
Has the bug been fixed... I'm still having the issue in 4.0.4

**Comment by misbeliever** [comment]
+1

**Comment by pepijnverburg** [comment]
+1

**Comment by codebytere** [comment]
We can't properly triage this without a reliable reproducible example, and for now there does not appear to be one. I can't reproduce this locally, so unless we're able to verify this i'm going to go ahead and close this issue.

**Comment by buffet-time** [comment]
@codebytere 

In the Additional information i link to a similar issue. I forgot to close this but this was fixed at some point in Electron 5 beta phase, likely the same time when #16219 was fixed.

Closing
