### ISSUE TITLE
Cursor position is incorrect when typing in Arabic

### ISSUE THREAD

**Issue by nikolami** [electron/electron#16537]
* Output of `node_modules/.bin/electron --version`:
v4.0.2
* Operating System (Platform and Version):
win32-ia32; Win10 10.0.17763.253 English

**Expected Behavior**
Typing Arabic letters and numbers positions cursor next to each character per RTL rules
In example below, the cursor should be on the right of the number "4"
فثسف34

**Actual behavior**
Typing Arabic e.g. فثسف34 positions cursor on right of text

**To Reproduce**
1. Install Arabic keyboard in Windows English
2. Type the equivalent of "test34" in Arabic

**Screenshots**
![Notepad behavior (expected)](https://user-images.githubusercontent.com/18406914/51707487-32f6ac80-1fd6-11e9-818b-98aa5671cb5a.png)

**Additional Information**
None

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
