### ISSUE TITLE
About win.setSize()

### ISSUE THREAD

**Issue by MingWR** [electron/electron#16541]
I'm not sure whether this is a bug. In electron version 4.0.2, when I try to use win.setSize to resize a window to smaller size, it does not work, although it does work when resizing to a larger size. There is no problem in version 1.8.5, so I'm going back to the old version. Just curious what could cause this problem.

update:
It seems not electron's problem. The win.setSize works fine when running the app with electron directly. However, the problem happens after using electron-packager to pack the app into an .exe file.

**Comment by sofianguy** [comment]
Hi @MingWR please open up an issue with electron-packager.

**Comment by malept** [comment]
I can't imagine why this would be a bug in Electron Packager itself. If anything, there's an unexpected behavior that's occurring in a packaged Electron app that's not happening in development mode.
