### ISSUE TITLE
Can you provide a precompiled package for Electron4.0.1 mips64el?

### ISSUE THREAD

**Issue by JWTIAN1111** [electron/electron#16543]
**Is your feature request related to a problem? Please describe.**
I tried to precompile Electron4.0.1 on loongson mips64el, but the various dependencies are missing

**Describe alternatives you've considered**
Could the authorities provide a high version of Electron4.0.1 on mips64el

**Comment by nornagon** [comment]
We don't officially support mips at the moment, so unfortunately you're on your own here for now!
