### ISSUE TITLE
Update Node.js to the latest 8.10+ in 2-0-x branch

### ISSUE THREAD

**Issue by aminet** [electron/electron#16546]
As 2-0-x branch is actually (2.0.16)  is based on Node.js 8.9.3 which doesn't support OpenSSL 1.1.0+
an update of Node version to at least 8.10 would be great. It's the first version having support for building with OpenSSL 1.1.0 ( https://nodejs.org/en/blog/release/v8.10.0/ ).

**Comment by MarshallOfSound** [comment]
@aminet What is preventing you upgrading to Electron 3 or Electron 4?  Those releases have upgraded node versions and more recent versions of Chromium.

**Comment by aminet** [comment]
Hi @MarshallOfSound , I'm just an indirect user of Electron.
Currently Electron 2.0.x is a dependency. In my case it's Atom that needs it, upstream is working on upgrading to Electron 3:  https://github.com/atom/atom/pull/18603/  (but I doesn't expect a new version soon).

**Comment by MarshallOfSound** [comment]
Without direct reach out from Atom with a strong case for this we probably won't do this node version upgrade.  A minor bump in node requires a minor bump in Electron and we are already working on `5.x` so maintaining a new `2.1` release doesn't make a lot of sense for us.

**Comment by daviwil** [comment]
The Electron 3 upgrade will be included with Atom 1.36.0-beta0, to be released at the beginning of February.
