### ISSUE TITLE
systemPreferences.getAccentColor returns wrong color if automatic color is selected in windows 10

### ISSUE THREAD

**Issue by Ahriana** [electron/electron#16545]
* Output of `node_modules/.bin/electron --version`: v4.0.2
* Operating System `(Platform and Version): Windows 10: Version 1809 (Build: 17763.253)`

**Expected Behavior**
calling `systemPreferences.getAccentColor()` should return correct color no matter if automatic color is set in windows

**Actual behavior**
if using `systemPreferences.on('accent-color-changed')` when moving from manual color to automatic the event will fire twice, once with the correct color and immidiatly after with a diffrent color (which is diffrent depending on the pc not sure what causes the second color to be picked)

if  ``systemPreferences.getAccentColor()`` is also called after this event from now on it will return the incorrect value

**To Reproduce**
in main.js
```js
  mainWindow.webContents.once('dom-ready', () => {
    const color = systemPreferences.getAccentColor()
    console.log(color);
    systemPreferences.on('accent-color-changed', (event, color) => { console.log(color); })
  })
```

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone https://github.com/RosieCode95/electron-quick-start.git
$ npm install
$ npm start
```
**Screenshots**
http://mei.is-a-good-waifu.com/233eba.mp4
video showing the issue in action

**Additional Information**
note: starting the application with automatic already set still returns incorrect color values

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
