### ISSUE TITLE
Big leak in DesktopCapturer.getSources('screen') on MacOS

### ISSUE THREAD

**Issue by CapOM** [electron/electron#16542]
electron 4.0.2

Steps to reproduce:

git clone https://github.com/electron/electron-quick-start
and add the folllowing to renderer.js

```
const { desktopCapturer } = require('electron')

function findSources() {
  desktopCapturer.getSources({ types: ['screen'] }, (error, sources) => {
    if (error) throw error
    for (let i = 0; i < sources.length; ++i) {
      console.log('source: ' + sources[i].name); 
    }
  })
}

window.setInterval(findSources, 1000)
```

Does not happen with type "window" so I suspect an any in either webrtc::ScreenCapturerMac or the way it is started/stopped from chrome/browser/media/webrtc/native_desktop_media_list.cc

**Comment by CapOM** [comment]
Ah I actually just found and you guys are missing the following patch:

“ScreenCapturerMac: destroy the streams and remove the DisplayStreamManager” -  https://webrtc-review.googlesource.com/c/src/+/98227

Please back port it, thx!

**Comment by sofianguy** [comment]
fixed in https://github.com/electron/electron/pull/16555

**Comment by CapOM** [comment]
Thx!
