### ISSUE TITLE
Failed to import LevelDB

### ISSUE THREAD

**Issue by Alecyrus** [electron/electron#16551]
* Output of `node_modules/.bin/electron --version`: `4.0.1`
* Operating System (Platform and Version): `macOS Mojave 10.14.2`
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): `~3.0.13`

**Expected Behavior**
no error

**Actual behavior**
```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorE
  Referenced from: /Users/alecyrus/Documents/Code/RealWork/electron-demo/node_modules/leveldown/build/Release/leveldown.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorE
  Referenced from: /Users/alecyrus/Documents/Code/RealWork/electron-demo/node_modules/leveldown/build/Release/leveldown.node
  Expected in: flat namespace
```

**To Reproduce**
* `git clone https://github.com/Level/electron-demo`
*  change `  "electron": "~3.0.13",` to `  "electron": "4.0.1",`
* `yarn`
* `yarn start` 

**Screenshots**
![image](https://user-images.githubusercontent.com/13865581/51762320-5a4e9600-210a-11e9-8ce5-3954245337a7.png)

**Comment by nornagon** [comment]
Looks to me like leveldown isn't built against the right version of electron. can you confirm that you built the module for Electron 4? A module built for Node or for Electron 3 won't work.

**Comment by Alecyrus** [comment]
https://github.com/Level/level/issues/140#issuecomment-457662851

**Comment by MarshallOfSound** [comment]
I beleive this is an issue with Electron's ABI number being the same for 3 and 4 but not technically being ABI compatible.  We're following this upstream in node and `node-abi`.

🔗 https://github.com/nodejs/TSC/issues/651
🔗 https://github.com/lgeiger/node-abi/pull/55

**Comment by Alecyrus** [comment]
@Alecyrus In my test, it is not an issue with Electron. https://github.com/Level/level/issues/140#issuecomment-457662851,  No webpack, just level 5.0.0-0 with electron 4.0.2, that works, it use electron-rebuild to build leveldown for electron without any configuration. 

But in my project, I use electron-builder. I run `yarn add level`, it shows:
![image](https://user-images.githubusercontent.com/13865581/51781345-69593680-2152-11e9-9fd5-99254967c50d.png)

Seems like electron-builder has built native module `leveldown` for the project successfully.  But when I try starting the app, I get error:
```
 TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at dirname (path.js:1268:5)
    at Function.getRoot (webpack:///./node_modules/bindings/bindings.js?:154:13)
    at bindings (webpack:///./node_modules/bindings/bindings.js?:60:32)
    at eval (webpack:///./node_modules/leveldown/leveldown.js?:3:91)
    at Object../node_modules/leveldown/leveldown.js (/Users/alecyrus/Documents/Code/RealWork/Vaquita/dist_electron/index.js:1184:1)
    at __webpack_require__ (/Users/alecyrus/Documents/Code/RealWork/Vaquita/dist_electron/index.js:20:30)
    at eval (webpack:///./node_modules/level/level.js?:1:111)
    at Object../node_modules/level/level.js (/Users/alecyrus/Documents/Code/RealWork/Vaquita/dist_electron/index.js:1151:1)
    at __webpack_require__ (/Users/alecyrus/Documents/Code/RealWork/Vaquita/dist_electron/index.js:20:30)

```
I will  share a minimal repro soon.

**Comment by Alecyrus** [comment]
There is a minimal repro that help you guys to reproduce
https://github.com/Alecyrus/electron-level-minimal
```sh
$ git clone https://github.com/Alecyrus/electron-level-minimal.git
$ cd electron-level-minimal
$ yarn
$ yarn electron:service
```
You'll see the error in Chrome devtools console

**Comment by Alecyrus** [comment]
Solved. See https://github.com/Level/level/issues/140#issuecomment-457797963 for more details.
