### ISSUE TITLE
Cannot drag frameless window by touch, works via mouse or touchpad

### ISSUE THREAD

**Issue by soorajvnair** [electron/electron#16556]
* Output of `node_modules/.bin/electron --version`: 4.0.2
* Operating System (Platform and Version): Linux and Ubuntu 18.04. 
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): N.A

**Expected Behavior**

Create a frameless window, and to make it draggable, specify a rectangular area inside the window with the required CSS as mentioned in the documentation https://electronjs.org/docs/api/frameless-window#draggable-region. User should be able to click and drag the rectangular area to move the window, the same behavior should occur if he's using a touchscreen. i.e if he tried to touch and drag the rectangular area, he should be able to move the window.

**Actual behavior**

I am able to move the frameless window by clicking and dragging the rectangular area inside the window using a mouse or touchpad, however if i try the same using a touch interface i'm unable to do so. Nothing happens.

If i enable the frame of the window, then i am able to move the window using touch by touching on the titlebar or the chrome/frame of the window and move it around freely.

**To Reproduce**

Here's a demo repo. https://github.com/soorajvnair/electron-touch-and-drag-issue

```sh
$ git clone https://github.com/soorajvnair/electron-touch-and-drag-issue
$ npm install
$ npm start || electron .
```

**Additional Information**

I'm aware that vscode uses a custom titlebar on a frameless window and i am experiencing the same behavior there as well.

**Comment by svnc0der** [comment]
Can confirm this happening on my end as well. Electron 3.1.1 and Windows 10.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by soorajvnair** [comment]
I'm still experiencing this issue on Electron 6.x.y or later. 

I tested with v8.0.1, v7.1.13 and v9.0.0-beta.1 and issue still persists.

**Comment by zcbenz** [comment]
The Windows part should have been fixed by https://github.com/electron/electron/pull/24042.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
