### ISSUE TITLE
NOT ALLOWED TO LOAD LOCAL RESOURCES. 

### ISSUE THREAD

**Issue by Manish7972** [electron/electron#16563]
I am learning JS but having this issue in every code I run on chrome I got irritated so much by this error.Please help me with this.
(---Not allowed to load local resources----) even after running webserver extension same error appears.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
