### ISSUE TITLE
aes gcm missing from available ciphers list

### ISSUE THREAD

**Issue by angeal185** [electron/electron#16566]
* Output of `node_modules/.bin/electron --version`: **4x / 5x**
* Operating System (Platform and Version): Windows 10/ Windows 7/ Ubuntu 18.04.1

aes gcm mode is missing from the list of available ciphers. it works for on my end so is there any reason for this?

**To Reproduce**

```js
const crypto = require('crypto');

console.log(crypto.getCiphers())
// returns
[ 'aes-128-cbc','aes-128-ctr','aes-128-ecb','aes-128-ofb','aes-256-cbc',
  'aes-256-ctr','aes-256-ecb','aes-256-ofb','aes-256-xts','des-cbc',
  'des-ecb','des-ede','des-ede-cbc','des-ede3-cbc','rc2-cbc','rc4'
]

// encrypt with gcm
const encGcm = function(text, secret, salt){
  let obj = {},
  iv = crypto.randomBytes(32).toString('hex'),
  key = crypto.pbkdf2Sync(secret, salt, 10000, 32, 'sha512'),
  cipher = crypto.createCipheriv('aes-256-gcm', key, iv),
  encrypted = Buffer.concat([cipher.update(text, 'utf8'), cipher.final()]),
  tag = cipher.getAuthTag();
  obj.iv = iv
  obj.tag = tag.toString('hex');
  obj.encrypted = encrypted.toString('hex');
  return obj;
}

let i = encGcm('text', 'secret', 'salt')

// decrypt with gcm
const decGcm = function(encdata, secret, salt, iv, tag){
  let key = crypto.pbkdf2Sync(secret, salt , 10000, 32, 'sha512'),
  decipher = crypto.createDecipheriv('aes-256-gcm', key, iv);
  decipher.setAuthTag(Buffer.from(tag, 'hex'));
  let decrypted = decipher.update(Buffer.from(encdata, 'hex')) + decipher.final();
  return decrypted;
}

console.log(decGcm(i.encrypted, 'secret', 'salt', i.iv, i.tag))
// returns
text
```

**Comment by angeal185** [comment]
This is not a duplicate, that issue is about ciphers/hashes not included in boringssl. This issue is about the fact that you are MISSING aes-gcm from your list of available ciphers when it should be on there because it works. Im not saying it should be included, im saying it is included and you do not have it listed. understand?

**Comment by MarshallOfSound** [comment]
cc @nornagon Seems to be reverse symptons of the other issue, any ideas what's happening there?

**Comment by angeal185** [comment]
not sure as to why its not showing up. I do know that aes-gcm has to be included though. irrespective as to weather its listed for the above shown method of use, its still used as a cipher suite for securing tls connections and so forth.

for example

```js
console.log(tls.getCiphers())

//returns
[
"aes128-gcm-sha256", "aes128-sha", "aes256-gcm-sha384", "aes256-sha", "des-cbc3-sha",
 "ecdhe-ecdsa-aes128-gcm-sha256", "ecdhe-ecdsa-aes128-sha", "ecdhe-ecdsa-aes256-gcm-sha384",
 "ecdhe-ecdsa-aes256-sha", "ecdhe-ecdsa-chacha20-poly1305", "ecdhe-psk-aes128-cbc-sha",
 "ecdhe-psk-aes256-cbc-sha", "ecdhe-psk-chacha20-poly1305", "ecdhe-rsa-aes128-gcm-sha256",
 "ecdhe-rsa-aes128-sha", "ecdhe-rsa-aes256-gcm-sha384", "ecdhe-rsa-aes256-sha",
 "ecdhe-rsa-chacha20-poly1305", "psk-aes128-cbc-sha", "psk-aes256-cbc-sha"
]
```

**Comment by nornagon** [comment]
This is a bug in BoringSSL, see https://boringssl-review.googlesource.com/c/boringssl/+/33984 for an attempt to resolve it. We'll patch in the fix from upstream once it's landed.
