### ISSUE TITLE
electron.d.ts does not document all of the instance variables exposed by `Notification` class

### ISSUE THREAD

**Issue by pronebird** [electron/electron#16568]
* Output of `node_modules/.bin/electron --version`:
* Operating System (Platform and Version): macOS
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 3.x

**Expected Behavior**

`electron.d.ts` does document all of the instance variables exposed by `Notification` class.

**Actual behavior**

`electron.d.ts` _does not_ declare all of the available instance variables on the `Notification` instances.

Electron `Notifications` expose the `title` and `body` parameters along with a bunch of other params passed to constructor, however those are not documented for some reason. Please document the missing methods.

```
> var n = new require('electron').Notification({ body: "hello" })
undefined
> n.body
'hello'
``` 

**To Reproduce**
Your best chance of getting this bug looked at quickly is to provide a REPOSITORY that can be cloned and run.

You can fork [electron-quick-start](https://github.com/electron/electron-quick-start) and include a link to the branch with your changes.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone $YOUR_URL -b $BRANCH
$ npm install
$ npm start || electron .
```
**Screenshots**

**Additional Information**

**Comment by ckerr** [comment]
This issue hasn't been touched in quite awhile so I don't know when this issue got fixed, but the `title` and `body` properties mentioned here are now documented. Here is the entry from the electron.d.ts from the latest stable release:

```
    /**
     * A `String` property representing the title of the notification.
     */
    title: string;

    ...

    /**
     * A `String` property representing the body of the notification.
     */
    body: string;
```

So I'm going to close this issue as fixed.
