### ISSUE TITLE
webContents.debugger.attach() causes duplicate console.log output from the preload script

### ISSUE THREAD

**Issue by bughit** [electron/electron#16577]
* Output of `node_modules/.bin/electron --version`: v4.0.2 x86
* Operating System (Platform and Version): win7 sp1 x64

**Expected Behavior**
no duplication

**Actual behavior**
each console.log from the preload script produces 2 renderer devtools console entries 

**To Reproduce**
- run the following app
- in the renderer devtools settings (Console)
  - uncheck "group similar"
  - check "preserve log"
  - check "show timestamps"
- navigate via devtools console (`location = 'about:blank'`)
  ![image](https://user-images.githubusercontent.com/895588/51873190-3073ba00-232a-11e9-8c0d-24f75f5ab79e.png)

##### app.js
```js
'use strict';

const {app, BrowserWindow} = require('electron'),
      Path = require('path');

let win;

app.on('ready', async () => {

  win = new BrowserWindow({
    width: 1440,
    height: 900,
    useContentSize: true,
    webPreferences: {
      preload: Path.join(__dirname, 'preload.js'),
    },
  });

  win.webContents.debugger.attach();

  win.webContents.openDevTools({mode: 'right'});

  win.loadURL('about:blank');

});
```

##### preload.js
```js
console.log('preload log 1');
console.log('preload log 2');
```

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
