### ISSUE TITLE
Crash (EXC_BAD_ACCESS) on MacOS 10.14.2

### ISSUE THREAD

**Issue by jmeinke** [electron/electron#16588]
* Output of `node_modules/.bin/electron --version`: v3.0.14
* Operating Systems (Platform and Version):
* * macOS 10.13.6
* * macOS 10.14.2
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): Not Applicable

**Expected Behavior**
No crash.

**Actual behavior**
Crash.

**To Reproduce**
We do not know how to reproduce the error and we can not provide the source code.

**Additional Information**
EXC_BAD_ACCESS / KERN_INVALID_ADDRESS void* v8::internal::Internals::ReadEmbedderData
Sentry issue: https://sentry.io/share/issue/980bf53506df4d0181dbba8596b07a64/

**Comment by jmeinke** [comment]
Possibly related: https://github.com/nodejs/nan/issues/772

**Comment by aguynamedben** [comment]
This happened to one of our users too. It seems rare and no easily reproducable.

Here's the console logs from right before it happened:
![image](https://user-images.githubusercontent.com/107841/52314260-bd3ff880-2966-11e9-9d97-be949ceb0368.png)

Here's the minidump:
![image](https://user-images.githubusercontent.com/107841/52314286-dfd21180-2966-11e9-888b-6c36e2416316.png)

It happened in the main process.

Versions:
* macOS 10.13.6 (17G5019, 17.7.0)
* Electron 3.0.6

For SEO: the top of the stack trace was gpu::GpuWatchdogThread::DeliberatelyTerminateToRecoverFromHang()

**Comment by aguynamedben** [comment]
Hmm, thanks for the lead... we have chokidar from webpack-dev-server, but we don't package that with production.

It happened again yesterday... both times when electron-updater asks the app to quit.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by momakes** [comment]
I can confirm I'm getting this on 7.1.3 @sofianguy

**Comment by amitojsingh366** [comment]
Still occurs on `electron@11.2.3` and macOS 11.2.3

**Comment by nornagon** [comment]
There are a huge variety of things that can cause EXC_BAD_ACCESS. Please open a new issue and attach a crash dump, which you can obtain using the crashReporter module:

```
const { crashReporter, app } = require('electron')
console.log(app.getPath('crashDumps'))
crashReporter.start({ submitURL: '', uploadToServer: false })
```

Ideally, also include a small test case which reproduces the issue, for example using [Electron Fiddle](/electron/fiddle).

I'm locking this issue to limit further noise.
