### ISSUE TITLE
Can't show file list of Google Drive

### ISSUE THREAD

**Issue by KazuyaHayashi** [electron/electron#16587]
* Output of `node_modules/.bin/electron --version`: `v4.0.2`
* Operating System (Platform and Version): macOS Mojave Version 10.14.2

**Expected Behavior**
Users can show one's file list on Google Drive.

**Actual behavior**
`<webview>` can't render file list on Google Drive. Google Drive requires `chrome-extension://ghbmnnjooekpmoecnnnilnnbdlolhkhi/page_embed_script.js` to show file list but Electron raises `net:ERR_NOT_IMPLEMENTED` error on the page.

**To Reproduce**
```sh
$ git clone https://github.com/KazuyaHayashi/google_drive_sample.git
$ npm install
$ npm start || electron .
```
**Screenshots**
![screen shot](https://github.com/KazuyaHayashi/google_drive_sample/blob/master/images/screen_shot.png)

**Additional Information**
This issue has been happened since 28 Jan 2019.

**Comment by PalmerAL** [comment]
The error in the console is unrelated, Google Drive will work fine even if it can't read the extension script.

What's actually happening is that Google Drive expects that anything with a Chrome-like user agent has a `window.chrome` property that it can read from. As far as I can tell, not having this causes a JS error that prevents the page from completely loading; I'm guessing they have the code to do this wrapped in a try{}catch{} block that prevents the error from showing up in the console.

If you create a preload script and put this inside it, it should work:
```
electron.webFrame.executeJavaScript("window.chrome = {}");
```

**Comment by KazuyaHayashi** [comment]
Thank you @PalmerAL . Your advice works well.

**Comment by alexstrat** [comment]
@PalmerAL I tried your solution but it had no effect on my side:

```diff
diff --git a/src/index.html b/src/index.html
index 369d81b..fca9e13 100644
--- a/src/index.html
+++ b/src/index.html
@@ -6,7 +6,7 @@
     <link rel="stylesheet" type="text/css" href="style.css">
   </head>
   <body>
-    <webview src="https://drive.google.com/"></webview>
+    <webview src="https://drive.google.com/" preload='./preload.js'></webview>
     <script type="text/javascript" src="webview_handler.js"></script>
   </body>
 </html>
diff --git a/src/preload.js b/src/preload.js
new file mode 100644
index 0000000..7e8857e
--- /dev/null
+++ b/src/preload.js
@@ -0,0 +1,3 @@
+const electron = require('electron');
+console.log('I was preloaded');
+electron.webFrame.executeJavaScript("window.chrome = {}");
```

**Comment by alexstrat** [comment]
Completing the mock seems to have fixed the issue for me:
```js
window.chrome = {
  runtime: {
    connect: () => {
      return {
        onMessage: {
          addListener: () => {},
          removeListener: () => {},
        },
        postMessage: () => {},
        disconnect: () => {},
      }
    }
  }
}
```

**Comment by PalmerAL** [comment]
@alexstrat It looks like Google Drive has changed their code again, thanks for the workaround!
