### ISSUE TITLE
MacOS BrowserWindow with unsaved changes 

### ISSUE THREAD

**Issue by karaggeorge** [electron/electron#16589]
**Is your feature request related to a problem? Please describe.**
The Apple Interface Guidelines for Menu Anatomy suggest using the Bullet for windows with unsaved changes (https://developer.apple.com/design/human-interface-guidelines/macos/menus/menu-anatomy/)

![screen shot 2019-01-29 at 11 16 22 am](https://user-images.githubusercontent.com/8822835/51923057-31532d00-23b8-11e9-92df-0bdeebe248cc.png)

Currently the `role: window` menu takes care of the icons based on the window information, but there is no way to mark a window as "having unsaved changes"

**Describe the solution you'd like**
Some kind of instance method to set wether there are unsaved changes in a browser window

**Describe alternatives you've considered**
None. The `role: window` menu is controlled by the system, so I don't know how else I would tap into that logic

**Comment by MarshallOfSound** [comment]
There is an API for that :+1:

https://electronjs.org/docs/api/browser-window#winsetdocumenteditededited-macos

**Comment by karaggeorge** [comment]
Thank you!
