### ISSUE TITLE
Developer Tools Icon differs from all other windows in application

### ISSUE THREAD

**Issue by buffet-time** [electron/electron#16594]
* Output of `node_modules/.bin/electron --version`: 4.0.2
* Operating System (Platform and Version): Windows 10 Enterprise x64 1709 

**Expected Behavior**
Application icon standard across all windows including Dev Tools.

**Actual behavior**
Dev Tools stay as the default electron icon.

**Comment by RosieCode95** [comment]
this is mostly dependant on the way you package the application.

![image](https://user-images.githubusercontent.com/28003629/51984062-4603f380-2492-11e9-9f77-56f4829a38f6.png)

**Comment by buffet-time** [comment]
Hmm ya, so with Electron Packager seemingly using [the icon command line flag](https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#icon) will force the icon to be used across all instances i have seen.
