### ISSUE TITLE
Electron tag webview, properties such as autosize, width, height not working

### ISSUE THREAD

**Issue by mindgeek22** [electron/electron#16609]
* electron --version (4.0.3)
* Operating System: Windows 10 Enterprise

**Expected Behavior**
`webview` should resize according to width and height given in the properties

**Actual behavior**
`webview` is not resizing

**To Reproduce**
```
import '../assets/css/App.css'
import React, { Component } from 'react'

class App extends React.Component {
  render() {
    const iframeUrl = 'https://google.com';
    return (
      <div style={webViewStyle}>
        <webview
          id="iframe"
          name="iframe"
          src={iframeUrl}
          autosize="on"
          minwidth="1300"
          minheight="1300"
        />
      </div>
    )
  }
}

export default App
```
**Warning message**
If `autosize` property does not have a value, in the console you can find such warning:

> Warning: Received `true` for a non-boolean attribute `autosize`.
> If you want to write it to the DOM, pass a string instead: autosize="true" or autosize={value.toString()}.

**Comment by wjhir** [comment]
The webview autosize attribute was removed by #13869, but the feature wasn't removed from the docs until recently (#16884). Looks like the website still hasn't been updated to reflect that change.

Webviews are broken in a lot of ways. If you only use one webview per BrowserWindow, then you should probably use a [BrowserView](https://electronjs.org/docs/api/browser-view) instead. (More than one BrowserView per BrowserWindow is not yet supported. :/ )
