### ISSUE TITLE
Digest Auth 401

### ISSUE THREAD

**Issue by lekoaf** [electron/electron#16605]
* Output of `node_modules/.bin/electron --version`: **v4.0.2**
* Operating System (Platform and Version): **Linux Debian Stretch**

**Expected Behavior**
Dialog for digest auth opens

**Actual behavior**
When trying to use `window.open` in my Electron app to access a site that requires Digest authentication, I instantly get a 401 error. Opening the same website in a browser promts a digest auth login dialog.

**Additional Information**
`shell.openExternal()` does of course work, but I want to be able to use `window.open` in this case.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

**Comment by ClaudiaStefan** [comment]
@lekoaf  I think you need to implement : https://github.com/electron/electron/blob/v4.1.1/docs/api/app.md#event-login . Electron cancels basic auth popups by default. From the docs:
_The default behavior is to cancel all authentications, to override this you should prevent the default behavior with event.preventDefault() and call callback(username, password) with the credentials._

**Comment by codebytere** [comment]
Closing as the above is correct!
