### ISSUE TITLE
[Docs] RTL has some glitches

### ISSUE THREAD

**Issue by yarons** [electron/electron#16606]
The Hebrew/Arabic/Farsi/Urdu documentation is RTLed incorrectly.

![electrondocs](https://user-images.githubusercontent.com/406826/51977221-80b85c80-248f-11e9-9d4b-ae37584850b8.png)

1. The EN is overlapping the header.
2. The Copy button overlaps the code box.
3. The code box is right aligned although code is written only in English (Should be LTR by default).

I can help with CSS and testing if needed.

Thanks!

**Comment by HashimotoYT** [comment]
Website issue, moved to https://github.com/electron/electronjs.org/issues/2022
