### ISSUE TITLE
electron@5.0.0-beta.1 fails with error: No usable sandbox!

### ISSUE THREAD

**Issue by vladimiry** [electron/electron#16631]
electron: 5.0.0-beta.1
platform: linux x64

**Actual behavior**

https://github.com/electron/electron-quick-start app fails to start with the following error:
```
[3937:0131/003107.790938:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
```

**To Reproduce**

- `git clone https://github.com/electron/electron-quick-start.git`
- `cd electron-quick-start`
- `npm install`
- `npm add --only=dev electron@5.0.0-beta.1`
- any of the following commands fail:
  - `npm start`
  - `node_modules/.bin/electron --version`

**Additional Information**

Worth to mention that event just `node_modules/.bin/electron --version` execution fails with the same error.

CC @nornagon

**Comment by nornagon** [comment]
Are you running electron inside docker?

**Comment by vladimiry** [comment]
I'm not running it insider docker. But there will be a need to run it on Travis CI.

**Comment by MarshallOfSound** [comment]
@vladimiry What machine / environment are you currently running this on to get this error.

OS? Is it containerized? OS Version? User Permisions? Running as sudo?  Etc.

As much info as you can provide about your environment would be incredibly helpful

**Comment by vladimiry** [comment]
Linux manjaro 4.20.3-1-MANJARO. No sudo. Regular user. No containerization.

Running `sudo sysctl kernel.unprivileged_userns_clone=1` makes electron@5.0.0-beta.1 work. But I don't believe that stable electron@5 version will require users to modify the system settings in order to allow electron@v5 based apps starting.

I understand it's probably due to the sandboxing enabled by default without testing sandboxing support by the system. Besides, there might be needed a way to detect at the app level whether sandboxing supported by the system, method like `app.isSandboxingSupported()`. So there would be a way to inform app user with the respective message and recommendations.

**Comment by MarshallOfSound** [comment]
@vladimiry Can you confirm that chromium runs on that system with no extra configuration.

**Comment by vladimiry** [comment]
I'm able to start chromium-71.0.3578.98-3 on that system. Here is the console output:
```
[15156:15156:0131/095653.119829:ERROR:sandbox_linux.cc(364)] InitializeSandbox() called with multiple threads in process gpu-process.
[15126:15126:0131/095653.252765:ERROR:x11_input_method_context_impl_gtk.cc(144)] Not implemented reached in virtual void libgtkui::X11InputMethodContextImplGtk::SetSurroundingText(const base::string16 &, const gfx::Range &)
```

**Comment by nornagon** [comment]
Does your distro modify chromium? This seems like a distro kernel
misconfiguration issue.

**Comment by vladimiry** [comment]
> Does your distro modify chromium?

It seems to be including the following patches https://git.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/chromium

Manjaro Linux goes with `kernel.unprivileged_userns_clone` disabled by default. But even if a user has intentionally disabled that option having it enabled by default, I think that any electron app still should be able to start.

**Comment by vladimiry** [comment]
![sandbox](https://user-images.githubusercontent.com/1560781/52039930-e6b3eb00-2546-11e9-9ff1-d439a0782318.png)

**Comment by nornagon** [comment]
Interesting. The setuid sandbox has been deprecated for a long time in Chromium, see e.g. https://chromium.googlesource.com/chromium/src/+/HEAD/docs/linux_suid_sandbox.md, and hasn't ever been supported in Electron to my knowledge. But according to https://chromium.googlesource.com/chromium/src/+/HEAD/docs/linux_sandboxing.md#sandbox-types-summary it's still maintained. Perhaps we should consider supporting it in Electron.

**Comment by vladimiry** [comment]
Arch Linux and distributives based on it are quite popular on desktop and electron@5.0.0-beta.1 fails there since user namespaces sandboxing is forced. User namespaces sandboxing can only be enabled on those systems by manual `kernel.unprivileged_userns_clone` option tweaking (root access rights required). So I'd imagine electron to try user namespaces sandbox first and fallback to setuid sandbox if the primary option is unsupported by the system.

**Comment by sebakerckhof** [comment]
I'm seeing the same issue on Debian stretch

**Comment by vladimiry** [comment]
Just tried v5.0.0-beta.6 and I confirm that setuid sandbox works for me now.

For those who use [electron-builder](https://github.com/electron-userland/electron-builder) the simplest way to run `chmod 4755 ./dist/linux-unpacked/chrome-sandbox` before packaging is doing that in [after-pack](https://www.electron.build/configuration/configuration#afterpack) script, something to [this](https://github.com/vladimiry/ElectronMail/blob/d2a931771eaf2964829c07ed5587460f878f73eb/scripts/electron-builder/after-pack.ts).
