### ISSUE TITLE
Accept `MenuItem` instances in `buildFromTemplate`

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#16645]
**Is your feature request related to a problem? Please describe.**

I sometimes make `MenuItem` instances that I reuse in various parts of an app. Unfortunately, `Menu.buildFromTemplate` only accept plain objects (`MenuItemConstructorOptions` in the TS definition file) as menu items, so I can't reuse those `MenuItem` instances there directly. 

**Describe the solution you'd like**

I would like it to be possible to use `MenuItem` where currently `MenuItemConstructorOptions` is accepted.

The `submenu` property already accepts both an array of plain objects and a `Menu`. So it makes sense to also support `MenuItem` instances.

In TypeScript terms, it would mean:

```diff
-submenu?: (MenuItemConstructorOptions[]) | (Menu);
+submenu?: (Array<MenuItemConstructorOptions | MenuItem>) | (Menu);
```

```diff
-static buildFromTemplate(template: MenuItemConstructorOptions[]): Menu;
+static buildFromTemplate(template: Array<MenuItemConstructorOptions | MenuItem>): Menu;
```

**Describe alternatives you've considered**

None.

**Additional context**

No.

**Comment by codebytere** [comment]
I'll add this to my backlog :)
