### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by PwnFunction** [electron/electron#16651]
[here](https://github.com/electron/electron/blob/master/docs/api/browser-window.md) line 254
* `nodeIntegration Boolean (optional) - Whether node integration is enabled. Default is false`.
 
The default value of  `nodeIntegration` should be `true`.

**Comment by HashimotoYT** [comment]
Starts from Electron 5.0 and upper, `nodeIntegration` default value set to `false`. See [breaking changes](https://github.com/electron/electron/blob/master/docs/api/breaking-changes.md#new-browserwindow-webpreferences-) documentation.

**Comment by MarshallOfSound** [comment]
@HashimotoYT is correct :+1:
