### ISSUE TITLE
No entry for `process.platform` in the docs

### ISSUE THREAD

**Issue by DWAK-ATTK** [electron/electron#16666]
This is a documentation bug.

The `process.platform` property appears to be missing from the documentation.

**Comment by DWAK-ATTK** [comment]
This would be the documentation located at  

https://electronjs.org/docs/api/process

**Comment by MarshallOfSound** [comment]
Our `process` docs only document API's / properties that we add on top of the NodeJS Process API.

> Electron's process object is extended from the [Node.js process object](https://nodejs.org/api/process.html). It adds the following events, properties, and methods:

🔗 https://nodejs.org/api/process.html

**Comment by DWAK-ATTK** [comment]
Oh!  I missed that part.  I do apologize for having consumed your time.

Thank you for the correction.
