### ISSUE TITLE
securityScopedBookmarks do not work properly (showOpenDialog())

### ISSUE THREAD

**Issue by rr326** [electron/electron#16664]
* Output of `node_modules/.bin/electron --version`: v4.0.2
* Operating System (Platform and Version): OSX 10.14.1
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
```
dialog.showOpenDialog({
  ...
  securityScopedBookmarks: <true> or <false>
})
```
MAS build
  <ul>
    <li><code>securityScopedBookmarks: false ==> bookmarks === []</code> </li>
    <li><code>securityScopedBookmarks: true</code>  </li>
    <ul>
      <li>Success: <code>bookmarks === ["SLKDJFLKSDJLSJDLFJSLKJFLS..SJLD"]</code> </li>
      <li>Error: <code>bookmarks === ['']</code></li>
    </ul>
  </ul>
 
**Actual behavior**  
I get all sorts of unexpected behaviors. Note all of these are THE EXACT SAME CALLS.
* On my development machine
  * If I do a showOpenDialog() via a renderer window
    * At first, it returns `[]`
    * Then I try it via a main process
    * Then I try again, and I get bookmarks back
  * In main window
    * I always get `bookmarks === []`
      * For `securityScopedBookmarks: true` this is wrong! I should get `bookmarks === ['validbookmark']` or `bookmarks === [""]` (ie: empty / error)
  * In renderer, after trying it in main, I get valid bookmarks returned
    * EVEN IF I SET `securityScopedBookmarks: false`
* On a clean virtual machine, I always get `bookmarks === []`

Here is an example of the output of my test - I am getting a bookmark returned even when securityScopedBookmars is set to false!
```
ShowOpenDialog Results: 
securityScopedBookmarks setting: false 
isMas: true
filePaths: |/Users|
bookmarks: |Ym9va/wBAAAAAAQQMAAAADhIsl+6AwP9UEecjjev0G5JVbcbiOTvz+X/GU0cUJ3vHAEAAAQAAAADAwAAAAgAKAUAAAABAQAAVXNlcnMAAAAEAAAAAQYAABAAAAAIAAAABAMAACrJCQAAAAAABAAAAAEGAAAsAAAACAAAAAAEAABBvxq0KQAAABgAAAABAgAAAgAAAAAAAAAPAAAAAAAAAAAAAAAAAAAACAAAAAEJAABmaWxlOi8vLwwAAAABAQAATWFjaW50b3NoIEhECAAAAAQDAAAA4AHj6AAAAAgAAAAABAAAQb/byy9eqf0kAAAAAQEAADIwODk1QzIxLUVFRDItNEU3MS1BNzQ2LTBFMUVFMzgwMjFBQhgAAAABAgAAgQAAAAEAAADvEwAAAQAAAAAAAAAAAAAAAQAAAAEBAAAvAAAAAAAAAAEFAACoAAAA/v///wEAAAAAAAAADQAAAAQQAAAgAAAAAAAAAAUQAAA8AAAAAAAAABAQAABYAAAAAAAAAEAQAABIAAAAAAAAAAIgAAAIAQAAAAAAAAUgAAB4AAAAAAAAABAgAACIAAAAAAAAABEgAAC8AAAAAAAAABIgAACcAAAAAAAAABMgAACsAAAAAAAAACAgAADoAAAAAAAAADAgAAAUAQAAAAAAABDQAAAEAAAAAAAAAA==|
typeof bookmarks: object 
isArray: true
length: 1
bookmarks ==== [""]: false
```

And here it is in a main process call (same app with same entitlements, provisioning profile, etc.). This one SHOULD succeed.
```
ShowOpenDialog Results: 
securityScopedBookmarks setting: true 
isMas: true
filePaths: |/Users|
bookmarks: ||
typeof bookmarks: object 
isArray: true
length: 0
bookmarks ==== [""]: false
```

**To Reproduce**  
Repo: https://github.com/rr326/ElectronSecurityScopedBookmarkTest

Instructions on the README

**Additional Information**  
I have done EXTENSIVE testing to narrow this down. I assumed it was codesiging, or identities, or a provisioning profile, or even my virtual machine. It isn't. 

For someone with a Mac setup, [this repo](https://github.com/rr326/ElectronSecurityScopedBookmarkTest) will make it easy to test. 

Also, looking at the code, the results I am seeing should not happen. It shouldn't even be possible! But I don't know C++ and also can't get Electron to build, so I'm at a dead end. The only thing I can imagine is somehow the settings to `showOpenDialog()` are getting overwritten or changed somehow. 

See the code here:  
[atom/browser/ui/file_dialog_mac.mm](https://github.com/electron/electron/blob/c8c1be7ae546da4679a22b6872f023c9786df663/atom/browser/ui/file_dialog_mac.mm#L287-L313). Particularly [OpenDialogComplettion](https://github.com/electron/electron/blob/c8c1be7ae546da4679a22b6872f023c9786df663/atom/browser/ui/file_dialog_mac.mm#L287-L313) and [GetBookMarkDataFromNSURL](https://github.com/electron/electron/blob/c8c1be7ae546da4679a22b6872f023c9786df663/atom/browser/ui/file_dialog_mac.mm#L228-L251)

One strange thing - there are TWO `ShowOpenDialog()` in this file. Is that ok?

**Comment by jfuechsl** [comment]
@rr326 Yes, it's ok that file_dialog_mac.mm has two ShowOpenDialog functions - they have different signatures, one is used for when a callback to showOpenDialog was provided (and is the one which should get called in this case), and when no callback was set. Look at the ShowOpenDialog function in atom_api_dialog.cc, there it calls either one of those.

To me it seems that here https://github.com/electron/electron/blob/c8c1be7ae546da4679a22b6872f023c9786df663/atom/browser/ui/file_dialog_mac.mm#L302 the security_scoped_bookmarks flag is false and we proceed to call ReadDialogPaths. Looking at that implementation here https://github.com/electron/electron/blob/c8c1be7ae546da4679a22b6872f023c9786df663/atom/browser/ui/file_dialog_mac.mm#L264, it calls ReadDialogPathsWithBookmarks (which we want to call originally) but discards the returned bookmarks. This is in conformance with the observed behaviour of [] being returned in mas builds.
Why not just get rid of the `if (settings.security_scoped_bookmarks)` branch in OpenDialogCompletion and return the bookmarks in any case (which seem to be returned internally anyhow)?

**Comment by rr326** [comment]
@jfuechsl I'm happy to test that out to see if that works. It still steems strange to me - I seem to be getting behavior that shouldn't happen. Personally I'd put some logging code in to confirm that the parameters I set (settings.security_scoped_bookmarks) are in fact the same as what the function is getting. If not, then something else is amiss. 

But as  I said this is beyond my ability to debug so if someone wants to do a build I'd be happy to test it on my setup.

**Comment by jfuechsl** [comment]
@rr326 I'm currently trying create a mas build of electron with the effect of the flag neutralized. Just to check if this flag is the culprit, or it it happens further down the stack.
Do you know how to do logging in that part of the codebase?

**Comment by rr326** [comment]
I'm sorry - I really don't. I would imagine there is a way to push something to the Console.app which, if you don't know, is where MacOS gets its log messages. But just how is beyond me.

**Comment by jfuechsl** [comment]
I just finished the electron build and tested my app. I now get bookmarks back, so the flag is definitely not passed correctly to OpenDialogCompletion in file_dialog_mac.mm.
Next step is to figure out where the flag-passing goes wrong.

**Comment by jfuechsl** [comment]
Ok, I think I found the cause of the problem and fixed it. Right now it's a branch in my fork and I will now try to submit a PR. You can find it here https://github.com/jfuechsl/electron/commit/6a55a2b57dba36f4770262e67ab24901268a50d9.

What happens is: ShowOpenDialog is invoked with a `settings` object which holds the `security_scoped_bookmarks` flag. This object is then passed to the completion handler of the dialog where the flag is eventually accessed inside of `OpenDialogCompletion`. Since `settings` is passed as reference, the content of the object could (and in our case does) change before the completion handler is executed - this _somehow_ flips the `security_scoped_bookmarks` flag back to `false`.

My fix is to capture the flag in the calling environment (`ShowOpenDialog` and `ShowSaveDialog`) and then only pass the flag as value to the completion handler (we only access the flag there anyway).

It now works as documented in my examples. I hope to be able to submit the PR very soon and get it merged if it looks ok to others.

**Comment by rr326** [comment]
I will get to work testing this.

@jfuechsl  - Question - do you think while you are working on this code it would be worth changing the return  value? It seems to me in a non-MAS case, it would be best to return a `null`.   That way in non-MAS, you get `null` and in MAS you either get a `['VALIDBOOKMARKSTRING']` or `['']` (error). 

Or maybe that should be a separate PR?

Also, I'd be happy to document the return values of this feature since they don't exist except in the original PR, if you'd like.

**Comment by rr326** [comment]
@jfuechsl Do you have a MAS build? I haven't been able to get electron to build so I can't build from source. (Sorry if it's there somewhere - I can't find it.)

**Comment by jfuechsl** [comment]
@rr326 I think that should be a separate PR.
Just checked the documentation, yes it could be more detailed, would be great if you could do that.

I will build electron (based on 4.0.5, with the PR applied) with MAS tonight. Once done I can share it with you.

**Comment by rr326** [comment]
@jfuechsl [dialog.md](https://github.com/rr326/electron/blob/ea3033a4cb7737242ca491856dc817ba882a1aa9/docs/api/dialog.md) updated. Sorry - I couldn't figure out how to submit a PR to your repo. I'm new to this. 

Just let me know how else I can help.

**Comment by jfuechsl** [comment]
@rr326 Here's the (mas) build of electron 4.0.5 with the fix: https://mega.nz/#!UBFHXaJB!3lS2wnNPqU2MH08ovPSXjCF1kA43K_125tncPXGVBsg

**Comment by rr326** [comment]
@jfuechsl This works perfectly. Thank you!

Separately, what do you think about cleaning up the return value of the non-MAS or MAS with `security_scoped_bookmarks === false`.  Right this will return a `[]` (empty array). An error in a returned bookmarks will return a `['']` (Array with an empty string.) This seems confusing. 

To me, if its not a MAS build or the feature is turned off, it should return a `null`. Given that this feature hasn't actually worked until your fix, I can't imagine this breaking change would hurt many people. And it would clean it up for all future users. So I think it's worth fixing.

But I can't do it, so you'd have to like the idea and do it yourself.

(I will do a PR of my doc change separately.) 

In any case, thanks for fixing this.

**Comment by jfuechsl** [comment]
@rr326 I'm glad it works for you. I agree with you wanting to change the return value and make it more consistent. I would like to get some feedback from the electron team if they would accept such a change.

**Comment by MarshallOfSound** [comment]
> To me, if its not a MAS build or the feature is turned off, it should return a `null`.

That makes sense, but as indicated would be a breaking change.  I'd suggest getting this change in in-sync with the promisification that already changes the return type. See #17054

> Given that this feature hasn't actually worked until your fix, I can't imagine this breaking change would hurt many people

Just as a point this feature **has** worked in the past, it definitely worked when it was first added.

**Comment by rr326** [comment]
@MarshallOfSound Sorry for the negative implication. I had *assumed* that the out of scope reference made it work udependably, so that it might have looked like it worked but didn't regularly. My bad. I certainly appreciate all the work that's gone into this.
