### ISSUE TITLE
Geolocation error have no message

### ISSUE THREAD

**Issue by BusinessDuck** [electron/electron#16673]
* v4.0.3
* OSX

**Expected Behavior**
Geolocation Error handling should contain a error message

**Actual behavior**
Geolocation Error does not contain any error reason message

**To Reproduce**
run in Electron app based console:
```js
navigator.geolocation.getCurrentPosition(console.log.bind(console), console.log.bind(console))
```
you will see : 
``` PositionError {code: 2, message: ""} ```

**Comment by deepak1556** [comment]
Merging this to https://github.com/electron/electron/issues/16139 , please follow the issue for updates. Thanks!
