### ISSUE TITLE
Add shell method for browser default search

### ISSUE THREAD

**Issue by EpicEric** [electron/electron#16682]
**Is your feature request related to a problem? Please describe.**
Web search of text selection seems to be a relatively common feature in Electron applications. All implementations that I've found use `shell.openExternal(url[, options, callback])` whenever they want to implement text search, usually hard-coding the Google URL as the only search engine available. For example, [Franz](https://github.com/meetfranz/franz/blob/da92cd426cbf350313945e3459f96638a79bd44e/src/webview/contextMenu.js#L70-L76) and Discord are two programs that do just that.

This is bad for users that have a different default search engine (Bing, DuckDuckGo, StartPage...), because they have to manually copy-and-paste this text into their browsers if they do not want to use Google.

**Describe the solution you'd like**
A new method in the Electron API, such as `shell.search(query[, options, callback])`, with the same signature of `openExternal` except for the query instead of an URL. It would open a tab of a text search with the user's default search engine, instead of an application-specific one.

**Describe alternatives you've considered**
One option would be using `shell.openExternal` with a text instead of a URL, but at least on Linux this fails (`xdg-utils` cannot understand web searches as far as I've tried).

Another option would be detecting the default browser and calling the shell command corresponding to a search, but some browsers have different CLIs for this; for example, Firefox (`firefox -search "hello world"`) and Chrome (`chrome "? hello world"`).

**Additional context**
N/A

**Comment by MarshallOfSound** [comment]
@EpicEric None of the major OS's (macOS, Windows, Linux) have a standard OS API for opening a browser and searching in the "default" search engine.  Some browsers have CLI options for searching (E.g. you found firefox's and chrome's) but there is no robust way to do this cross-platform and cross-browser.

As such I'm going to tag this as a wontfix for now 👍
