### ISSUE TITLE
Touch ID support for macOS

### ISSUE THREAD

**Issue by idoodler** [electron/electron#16699]
**Is your feature request related to a problem? Please describe.**
I am building an Application that requires frequent password input. It would be awesome, to have native Touch ID support on macOS.

**Describe the solution you'd like**
An easy solution to show the Touch ID authentication dialog on macOS.

**Describe alternatives you've considered**
Writing my own Node.js add-on, but I couldn't wrap my head around it

**Additional context**
<img width="1085" alt="touch bar bild 2019-02-02 um 09 58 04" src="https://user-images.githubusercontent.com/6825153/52162266-71285600-26d1-11e9-80a7-5f85cc50bf90.png">

**Comment by codebytere** [comment]
Related: https://developer.apple.com/documentation/localauthentication?language=objc

**Comment by codebytere** [comment]
@idoodler I took a stab at this today, I think i can get it out in the next beta or two of 5.0 potentially!

**Comment by nornagon** [comment]
Is this functionality perhaps better suited to a 3rd-party native module?

**Comment by codebytere** [comment]
I considered that initially, but I think that we have a significant amount of macOS-specific code in `systemPreferences` as it stands, and that this feature would be more difficult to wrangle as a native node module subject to compilation difficulties against Node. It would also spread out maintenance responsibilities, where here we can support it more easily and better guarantee its functionality.

**Comment by emilbayes** [comment]
I made a module a while back that does that for my electron app (no real security, just checks that you have a valid identity as a boolean): https://www.npmjs.com/package/macos-touchid

**Comment by appinteractive** [comment]
You can use now the native electron feature: https://www.electronjs.org/docs/api/system-preferences#systempreferencesprompttouchidreason-macos
