### ISSUE TITLE
[Feature] Internal translation system

### ISSUE THREAD

**Issue by MyTheValentinus** [electron/electron#16693]
I think it would be nice to have an internal translation system in electron to translate the private texts of our applications.

For example i have some paragraphs of simple text and label, actually i make a json file for every lang, but it's not easy to use and maintain.

Thanks

**Comment by nornagon** [comment]
This seems like something that would make a great project for [electron-userland](https://github.com/electron-userland) since it would exist entirely outside of the core API.

**Comment by MarshallOfSound** [comment]
Agree with @nornagon that something like this shouldn't live in core 👍
