### ISSUE TITLE
Consider removing `contents.hasServiceWorker()`

### ISSUE THREAD

**Issue by ckerr** [electron/electron#16704]
Motivated by https://github.com/electron/electron/pull/16582. `contents.hasServiceWorker()` appears to have been so broken as to be unusable in earlier releases, but there are no issues filed for it. If this is correct, I think we should consider removing the function as it seems to have no users.

CC @codebytere who did the `hasServiceWorker()` testing and found it to be broken, and @paulcbetts, who [requested](https://github.com/electron/electron/issues/1331) the service worker API and so might be a good candidate to argue for keeping (a fixed version of) it :smiley:

**Comment by codebytere** [comment]
I'd be in favor of removing both this and `contents.unregisterServiceWorker()`, they're both finicky and weren't originally intended to be used in `webContents` anyways.

@deepak1556 do you think there's a reason to keep them? I'll pop open a PR to remove them otherwise.

**Comment by ckerr** [comment]
If the code was broken and nobody complained, IMO that says a lot for getting rid of this API.

However we should get public comment from the project long-timers before pulling the trigger
