### ISSUE TITLE
win.setSize is not working on windows Platform

### ISSUE THREAD

**Issue by hpatel4** [electron/electron#16711]
electron --version: 4.0.1
Operating System (Platform and Version): Windows 10

Expected browserwindow to resize on win.setSize(w, h) on winodws platform

Actual behavior  It's working as expected on MacOS and resizing with the given width and height but the same is failing on windows platform

To Reproduce:
1) Create browserWindow on windows platform
2) Call win.setSize(w, h, a)

**Comment by britt** [comment]
I have found the same issue. One additional piece of information, the bug only occurs if `resizable` is set to false.

**Comment by britt** [comment]
I found another issue that better describes the bug I saw #15560

**Comment by codebytere** [comment]
☝️closing as dup of https://github.com/electron/electron/issues/15560.

**Comment by BroJenuel** [comment]
if any having trouble with this... their are things that you should know.

if the browser window is in maximized or full screen set size will not work. so to do so you have to unmaximize it first.
sample code:

```js
     win.unmaximize();
     win.setSize(1180, 650, false);
```

**Comment by IAFEnvoy** [comment]
I meet the same problem and here is my solution:
``` javascript
currentWindow.setResizable(true);
currentWindow.setSize(width,height);
currentWindow.setResizable(false);
```
