### ISSUE TITLE
Close/Minimize buttons on macOS

### ISSUE THREAD

**Issue by antpaw** [electron/electron#16713]
* Output of `node_modules/.bin/electron --version`: 2.0.x (the one from VS Code 1.30.2)
* Operating System (Platform and Version): macOS 10.14.3

**Expected Behavior**
The button colour in the top application bar should be gray even if the window is in focus, like in all other native apps. This only happens if you are on a "standard" dpi monitor.

**Actual behavior**
The button colour in the top application bar is not gray, if you are on a "standard" dpi monitor.

**To Reproduce**
Set "Accent colour" to gray (on very right) in "Gerenal" macOS settings. The buttons in the top application bar are now gray in every application, except in VS Code if you are on a "standard" dpi monitor.

**Additional Information**
This is an issue from VS Code https://github.com/Microsoft/vscode/issues/67787

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by antpaw** [comment]
i was just asked by the vs-code projects maintainers to report this issue here, i don't use electron "directly" and can not verify this issue with the new version.

**Comment by sofianguy** [comment]
@antpaw thank you. Electron is no longer pushing bug fixes to v4.2.x or earlier. I'm going to close this issue for now but we'd be happy to reopen if this bug is still present in later versions
