### ISSUE TITLE
Add 2 more keys for globalshortcuts: capslock & fn

### ISSUE THREAD

**Issue by Karric** [electron/electron#16714]
**Is your feature request related to a problem? Please describe.**
The Caps Lock and Fn keys are useful to some, and not others. I would greatly enjoy being able to use these keys as modifiers for something more useful to me.

**Describe the solution you'd like**
Add global shortcuts support for the cap locks and fn keys. While these keys are not useless and are not proper modifier keys, I feel that the design choice should be left to the app developer.

**Describe alternatives you've considered**
The only alternative would be to use a keypress listener/sender to 'remap' the key to something Electron supports; or substitute electron's shortcut functionality completely.

**Additional context**
Using a 3rd party keypress listener does not feel safe.

**Comment by Karric** [comment]
@codebytere I appreciate the fast turn around, but what about the 'fn' key? Can it not be supported too?

**Comment by codebytere** [comment]
Sadly no, as it's not supported by Chrome :(

Sorry about that!

**Comment by Karric** [comment]
@codebytere No problem. I'm trying to understand your release cycle; when should I expect this to be available in the latest build?
