### ISSUE TITLE
Issues with process.getProcessMemoryInfo(): Return type is a Promise

### ISSUE THREAD

**Issue by bpasero** [electron/electron#16712]
* Output of `node_modules/.bin/electron --version`: 4.0.4
* Operating System (Platform and Version): macOS 10.14.1
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 3.0.x

**Expected Behavior**
`process.getProcessMemoryInfo()` should work as documented

**Actual Behavior**
`process.getProcessMemoryInfo()` seems to be returning a `Promise` (and not a type directly as documented in `electron.d.ts`).

Also, `residenSet` should be made optional as it does not seem to be implemented for macOS.

//cc @alexeykuzmin

**Comment by MarshallOfSound** [comment]
@bpasero --> https://github.com/electron/electron/pull/16593

**Comment by MarshallOfSound** [comment]
Fixed in #16593
