### ISSUE TITLE
Issue with new nodeIntegrationInSubFrames config

### ISSUE THREAD

**Issue by dansteen** [electron/electron#16733]
* Output of `node_modules/.bin/electron --version`:  v5.0.0-beta.1
* Operating System (Platform and Version):  Archlinux 4.20, windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): NA

**Expected Behavior**
The new config flag is intended to cause preload scripts to be loaded in subframes.

**Actual behavior**
It does seem  to load the preload scripts, however, clicking on any link in an iframe will result in a gray screen.   See the video below. 

As a note, this will also happen occasionally even without a click on a link though I am not able to reproduce it on demand.   

**To Reproduce**
1. git clone https://github.com/AbeSchor916/iframetest.git
2. npm install
3. npm start

Note that I am using nodejs 11.9.0 when running the above commands.

**Screenshots**
![iframe](https://user-images.githubusercontent.com/64940/52252070-5242e300-28ce-11e9-8d65-04ce95a95026.gif)

**Comment by ZackBoe** [comment]
I'm seeing this same issue with Electron v5.0.0-beta.2 on Windows 10. Enabling `nodeIntegrationInSubFrames` causes some iframes (noticeably YouTube embeds?) to have a quick flash of content and then a gray square immediately after load without user interaction. Their content is also no longer inspectable in devtools.
![electron_2019-02-05_16-13-16](https://user-images.githubusercontent.com/904055/52304750-684db380-2961-11e9-83ff-0193aa60f643.png)
![electron_2019-02-05_16-13-59](https://user-images.githubusercontent.com/904055/52304760-6be13a80-2961-11e9-8c2d-538b1ccea2b0.png)

**Comment by dansteen** [comment]
I see the devtools issue as well.

**Comment by dansteen** [comment]
Quick note @MarshallOfSound mentioned to us that this is related to the v8 GC process, and, when you use `sandbox: true` the issue is not present.   We have confirmed that this is true for the application above.   Obviously, this would be better off being fixed across the board, but at least there is a workaround.
