### ISSUE TITLE
Setting a MenuItem to visible: false also disables it

### ISSUE THREAD

**Issue by aaronraimist** [electron/electron#16747]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 4.0.4
* **Operating System** (Platform and Version):
  * macOS 10.14.3
* **Last known working Electron version** (if applicable):
  * unknown

### Expected Behavior
Setting a MenuItem to `visible: false` will hide it from the menu but **not** disable it.

See documentation https://electronjs.org/docs/api/menu-item

### Actual behavior
MenuItem is hidden AND disabled

### To Reproduce
https://github.com/aaronraimist/electron-quick-start/tree/visible-false

There should be one menu item visible (zoomin) and zoom out should also work but it doesn't.
(my issue is with zoomin but since that is kind of broken I did the demo with zoomout)

Menu code looks like
```
const template = [
  {
    label: 'View',
    submenu: [
	  { role: 'zoomin' },
      { role: 'zoomout', visible: false },
    ],
  }
]
```

```sh
# Clone this repository
git clone https://github.com/electron/electron-quick-start
# Go into the repository
cd electron-quick-start
# Checkout branch
git checkout visible-false
# Install dependencies
npm install
# Run the app
npm start
```

### Additional Information

I'm trying to work around https://github.com/electron/electron/issues/15496 by creating two menu items, one visible and one invisible but it doesn't work. See https://github.com/vector-im/riot-web/pull/8381

**Comment by codebytere** [comment]
@aaronraimist this is intended behavior, if a MenuItem is invisible it currently will not be functional. I can potentially look into changing this behavior, however, if you'd prefer!

**Comment by aaronraimist** [comment]
@codebytere Thanks for your answer. I can't speak to other platforms but at least in native macOS apps I would expect to be able to use a hidden menu item, or at least have the option to use hidden menu items.

Xcode gives you the option to allow the keyboard shortcut to continue working when the menu item is hidden
![screen shot 2019-02-08 at 12 43 40 pm](https://user-images.githubusercontent.com/5855073/52498723-2ad66980-2b9f-11e9-94c1-15e8d64e77e1.png)

**Comment by codebytere** [comment]
@aaronraimist i'll see what i can do!
