### ISSUE TITLE
TypeError: Cannot read property 'buildFromTemplate' of undefined

### ISSUE THREAD

**Issue by anton-marchenko** [electron/electron#16743]
* Electron version: 4.0.3
* Operating system: Windows 10

I try reproduce example from [doc](https://electronjs.org/docs/api/menu)
```
const { app, Menu } = require('electron')

const template = [
  { /* some code there*/}

const menu = Menu.buildFromTemplate(template)
Menu.setApplicationMenu(menu)
```

But I get error:
`Uncaught TypeError: Cannot read property 'buildFromTemplate' of undefined`

I was found [issue](https://github.com/electron/electron/issues/5862) when was similar problem. But it is not help me.
`const {app, Menu} = require('electron');` does not work any more.

After code research I was found solution:

`const {app, Menu} = require('electron').remote;`

Please, update your [doc](https://electronjs.org/docs/api/menu). Thank you.

**Comment by MarshallOfSound** [comment]
@anton-marchenko The `Menu` and `app` APIs are Main Proceess APIs.  They are only available in the main process, from the sounds of it you are running this code in the renderer process and therefore need to use the `remote` module.  This is expected behavior
