### ISSUE TITLE
webContents.executeJavascript not working when called from menu handler

### ISSUE THREAD

**Issue by tonioloewald** [electron/electron#16761]
Electron 4.0.4
macOS 10.14.1
Just started on this, so it's never worked.

### Expected Behavior
I've written a menu handler that looks like this:
```
let nav = true;
const toggleNav = {
  label: 'Toggle Nav',
  accelerator: '`',
  click() {
    nav = !nav
    const wins = BrowserWindow.getAllWindows()
    const js = `document.querySelector(".nav").classList.toggle("active", ${nav})`
    wins.forEach(win => {
      // win.webContents.openDevTools()
      win.webContents.executeJavaScript(js).then(result => console.log(result))
    })
  }
}
```

I expect using the menu item to toggle the class on the '.nav' element in every window.

### Actual behavior

When I hit the shortcut or select the menu item, nothing happens.
If I turn on devTools all the requests get played back.
If I uncomment out the openDevTools line, it works (but obviously devTools is open)
All of this takes place long after the window is spun up, so waiting for load events is beside the point.

### To Reproduce
Add the menu item to a menu (replace

`document.querySelector(".nav").classList.toggle("active", ${nav})`

with

`document.body.style.display = 'none'`

to make it even simpler

### Additional Information
I've been searching through issues to find a workaround, and find lots of similar issues that have been closed. I'm guessing that somehow opening dev tools finishes some spinup in the window, and it also masks flaws in fixes to the earlier problem since (for example) the way I initially wrote the code was in a console window…

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
