### ISSUE TITLE
BrowserWindow isVisible not returning accurate state

### ISSUE THREAD

**Issue by nickfujita** [electron/electron#16776]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 4.0.4
* **Operating System** (Platform and Version):
  * macOS 10.14.2
* **Last known working Electron version** (if applicable):
  * N/A also tested on 2.*.*

### Expected Behavior
According to the documentation, the isVisible method on a BrowserWindow instance should return, "Whether the window is visible to the user.". If the window is not visible to the user due to other application windows being in the foreground, the expected behavior is that `isVisible` will return false.

### Actual behavior
If the window is minimized, it correctly returns true.

If the window is not minimized, but occluded by other application windows, the value returns true. Based on the definition in the documentation, and a requirement for my application, this is not accurate.

### To Reproduce
Create any BrowserWindow instance, and execute a console log of the return value of `isVisible`, move the window behind other application windows, so that it is no longer visible on the user screen. The values returned will always return `true`, unless the window is minimized.

**Comment by nickfujita** [comment]
The original reason for wanting this behavior is that I would really like to return the app back to it's previous state before I called it into focus.

If it was previously visible, I would like it to remain visible, and return application focus back to the previous app.

If it was previously not visible, and not minimized, I would like to return application focus back to the previous app, and blur the electron app to the background (not minimized). I can already seem to achieve this using the BrowserWindow blur method.

**Comment by codebytere** [comment]
@nickfujita at present we only return this: https://developer.apple.com/documentation/appkit/nswindow/1419132-visible?language=objc, but i see there's an option to further include the window's `occlusionState.` Would adding a new API to determine whether or not a window is occluded solve this problem for you?
