### ISSUE TITLE
WebView docs should reference the "webviewTag" webPreferences option

### ISSUE THREAD

**Issue by jeremydelacasa** [electron/electron#16773]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  *  5.0.0-beta.2
* **Operating System** (Platform and Version):
  *  macOS 10.13.6 / Windows 10
* **Last known working Electron version** (if applicable):
  *  4.0.4

### Expected Behavior

Webview shows something.

### Actual behavior

Webview shows nothing and no error is thrown.

### To Reproduce

`<webview
      src="https://github.com/electron/electron"
      style="display:inline-flex; width:640px; height:480px"
    ></webview>`

**Comment by t57ser** [comment]
Since electron 5, the webview tag is disabled per default according to docs:
> webviewTag Boolean (optional) - Whether to enable the <webview> tag. Defaults to false.

You can enable it if you set "webviewTag: true" in the webPreferences

**Comment by jeremydelacasa** [comment]
@t57ser Thanks ! I will try it.

For less confusion, it would be nice to put the information in the "webview tag" page (https://github.com/electron/electron/blob/5-0-x/docs/api/webview-tag.md)

**Comment by MarshallOfSound** [comment]
@jeremydelacasa PR's are always welcome for documentation issues you find 👍 Would be good to have a reference to the `webviewTag` option in the `webview` docs to avoid people running into this situation 👍
