### ISSUE TITLE
Security doc contains a weak URL check

### ISSUE THREAD

**Issue by polict** [electron/electron#16774]
The security doc (https://github.com/electron/electron/blob/master/docs/tutorial/security.md#4-handle-session-permission-requests-from-remote-content) contains a weak check of URL:
```js
const { session } = require('electron')

session
  .fromPartition('some-partition')
  .setPermissionRequestHandler((webContents, permission, callback) => {
    const url = webContents.getURL()

    if (permission === 'notifications') {
      // Approves the permissions request
      callback(true)
    }
    
    if (!url.startsWith('https://my-website.com')) { // can be bypassed with 'https://my-website.com.attacker.com' 
      // Denies the permissions request
      return callback(false)
    }
  })
```

As noted in point 11 (https://github.com/electron/electron/blob/master/docs/tutorial/security.md#how-9) and point 12 (https://github.com/electron/electron/blob/master/docs/tutorial/security.md#how-10) such check can be bypassed.

Like any other security documentation this should be avoided in order to provide only solid code. I will provide a pull-request in a few minutes to add a '/' at the end of the url.

**Comment by MarshallOfSound** [comment]
Closed by #16775
