### ISSUE TITLE
Support new nodeIntegrationInSubFrames in webviews

### ISSUE THREAD

**Issue by dansteen** [electron/electron#16780]
PR https://github.com/electron/electron/pull/16425 add support for node integration in iFrames.  However this only added support for BrowserWindow (https://electronjs.org/docs/api/browser-window) objects.  It would be great if this could be added for webview (https://electronjs.org/docs/api/webview-tag)  objects as well!

**Comment by dansteen** [comment]
In case it helps,  we've posted a bounty for this issue:  https://www.bountysource.com/issues/70384098-support-new-nodeintegrationinsubframes-in-webviews

**Comment by denim2x** [comment]
@dansteen Hi - I'd like to get started on this project; can we discuss a small bounty increase?

**Comment by dansteen** [comment]
@denim2x I have no problem with the requested increase if you feel that that reflects the amount of effort involved. 

Looking at your account and commit history I don't see a lot of C/C++ work.   Do you have the experience needed to resolve this issue?

**Comment by brenca** [comment]
Hey @dansteen and @denim2x! If you haven't discussed starting on this, I'd like to take this as well, and I'm more than happy with the bounty.

**Comment by dansteen** [comment]
Hi @brenca! No problem at all.  I'd love to have you start on this.

**Comment by mul1sh** [comment]
Just seen this issue as well on bounty source, would love to give it a shot @dansteen  if it is still open 🙂, the bounty is fine with me and I believe I can turn it around in less than 3 days

**Comment by brenca** [comment]
@dansteen I posted a PR with a fix for this.

**Comment by dansteen** [comment]
@brenca nice - that's super fast work!   I see that it also fixed the other crash as well.  That's fantastic!

**Comment by dansteen** [comment]
hi @brenca Thanks so much for the work you have done on this so far.  It looks like things are coming along really nicely!

A quick question.  Does the work you have done on this support contextIsolation?  Thanks!

**Comment by brenca** [comment]
@dansteen I don't think partitions can cause problems with this, but the tests cover `contextIsolation`, `sandbox` and the combination of the two.

**Comment by dansteen** [comment]
Hi @brenca.  Thanks for the superfast turnaround on this  it looks great!  I'd like to wait to accept the solution until we get a 5x build so we can run a few quick tests.  is that ok with you?

**Comment by brenca** [comment]
@dansteen sure thing! If you want to test before the next `5-0-x` release that would contain this gets out, you could also test the `testing` builds that CI generates when running checks.

**Comment by dansteen** [comment]
Testing with the output of the CI runs would be just fine @brenca.  I see the artifact files for the appvayor builds, but can you point me to the artifacts for the linux builds?  Thanks!

**Comment by brenca** [comment]
Which architecture are you looking for? I can send you a link, I think you need to be an org member to see build artifacts for some reason (for `circleci` builds anyway)

**Comment by dansteen** [comment]
amd64 would be fine.  Thanks!

**Comment by brenca** [comment]
@dansteen this should be it then: https://155439-9384267-gh.circle-artifacts.com/0/dist.zip

**Comment by brenca** [comment]
@dansteen the latest beta should have the backport included
