### ISSUE TITLE
Make util::Promise a move-only type

### ISSUE THREAD

**Issue by zcbenz** [electron/electron#16799]
Passing `scoped_refptr` across threads is very dangerous as it would be very easy to accidentally increase/decrease on the wrong thread, currently we already have a couple issues caused by that:
https://github.com/electron/electron/pull/16788, https://github.com/electron/electron/pull/16738.

We should change the design of `util::Promise` to prevent this from happening from the first place, and the best way should be making `util::Promise` a move-only type.

**Comment by deepak1556** [comment]
Took a stab at it with a slight different approach https://github.com/electron/electron/commit/6450f3de4d6ffc223de6f146286c86fff5a9c75d that mimics task runner's traits implementation but its not ideal solution for developers to interact with promises natively.

But on a larger scale v8::promises are not meant to be dealt directly with chromium types, but this is a problem even chromium is trying to solve by introducing [base::Promise](https://docs.google.com/document/d/1l12PAJgEtlrqTXKiw6mk2cR2jP7FAfCCDr-DGIdiC9w/edit#).
