### ISSUE TITLE
[win] flaky tests on Windows, potential crash-on-exit

### ISSUE THREAD

**Issue by nornagon** [electron/electron#16796]
```text
not ok 49 app module app launch through uri launches successfully for multiple URIs following --
  AssertionError: expected 3221226505 to equal 123
      at ChildProcess.first.once.code (C:\projects\src\electron\spec\api-app-spec.js:822:25)
      at Object.onceWrapper (events.js:276:13)
      at ChildProcess.emit (events.js:188:13)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
```

https://windows-ci.electronjs.org/project/AppVeyor/electron-hew04/build/1.0.4231?fullLog=true

**Comment by MarshallOfSound** [comment]
`3221226505` normally means that the app is crashing, we've seen this caused before by a crash-on-exit

**Comment by MarshallOfSound** [comment]
Dropping this flake on this issue as I believe it's the same root cause: [AppVeyor Build](https://windows-ci.electronjs.org/project/AppVeyor/electron-67iac/build/1.0.5662?fullLog=true)

```
not ok 14 app module app.requestSingleInstanceLock prevents the second launch of app
  AssertionError: expected 3221225477 to equal 1
      at ChildProcess.second.once.code (C:\projects\src\electron\spec\api-app-spec.js:224:27)
      at Object.onceWrapper (events.js:276:13)
      at ChildProcess.emit (events.js:188:13)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
```

I believe we have a crash-on-exit in Windows

**Comment by MarshallOfSound** [comment]
Another example: https://windows-ci.electronjs.org/project/AppVeyor/electron-67iac/build/1.0.5730?fullLog=true

**Comment by Gvozd** [comment]
Same error
1. update electron to 5.0.0-beta.2 in electronquick-start
2. run
3. try open devtools - crash

**Comment by MarshallOfSound** [comment]
@Gvozd I'd be surprised if you saw the same error as this issue, as these logs come from our test suite (that electron-quick-start doesn't run).  If you are experiencing a reproducible crash on Electron 5.0.0-beta.2 can you please raise a new issue following the issue template and provide a way to reproduce the crash 👍

**Comment by Gvozd** [comment]
@MarshallOfSound , sorry I made a little mistake
In my case exit code is 3221225477, not 3221226505
Also js not worked in renderer process
#16883 #16885
