### ISSUE TITLE
Ready Event fires when Electron is not ready (transparency feature)

### ISSUE THREAD

**Issue by doom-fr** [electron/electron#16809]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 4.0.4
* **Operating System** (Platform and Version):
  * Debian Jessie
* **Last known working Electron version** (if applicable):
  * ?

### Expected Behavior
From [docs](https://electronjs.org/docs/all), Ready event is _'Emitted when Electron has finished initializing'_

### Actual behavior
When ready event is fired. Electron is not really ready has transparency does not work.
We should add delay to make app working :
`app.on('ready', () => setTimeout(onAppReady, 400));`

Ready event should be fixed.
Or another event should be fired when transparency is ready (prefered solution)

### To Reproduce
Play with [this repo](https://gitlab.com/doom-fr/electron-transparency-bug)  and change the delay.

### Screenshots
_

### Additional Information
You can check this [related issue](https://github.com/electron/electron/issues/15947)

**Comment by doom-fr** [comment]
Still present : 
https://stackoverflow.com/questions/54763647/transparent-windows-on-linux-electron

**Comment by Toooorch** [comment]
Can confirm, not only Debian but also Ubuntu

**Comment by Tal-telecomsante** [comment]
Still present on ubuntu, electron 5.0.4

**Comment by johannesjo** [comment]
Still an issue with electron 6.0.7.

**Comment by mifi** [comment]
Same problem on raspbian buster

**Comment by sam0x17** [comment]
This is likely the fix for the old mega-thread / issue going back to 2015 regarding transparency on linux #2170

**Comment by sencersoylu** [comment]
> Same problem on raspbian buster

have you find any solution ?

**Comment by mifi** [comment]
> > Same problem on raspbian buster
> 
> have you find any solution ?

Just using the settimeout hack

**Comment by sentialx** [comment]
Is the timeout consistent?

**Comment by zladuric** [comment]
Hello thread, from a year forward. Is the hack/workaround for window transparency supposed to work in December 2021? I'm trying to get the transparent window, but this does not seem to work, even if I increase the timeout on `app.whenReady` to like 5 seconds.

**Comment by skeddles** [comment]
bug still exists.
