### ISSUE TITLE
Unable to Disable vsync with argument on Electron 4.x.x

### ISSUE THREAD

**Issue by coreybruce** [electron/electron#16806]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 4.04
* **Operating System** (Platform and Version):
  * All
* **Last known working Electron version** (if applicable):
  * 3.x.x

### Expected Behavior
app.commandLine.appendSwitch('disable-gpu-vsync' is suppose to disable vsync

### Actual behavior
doesn't follow the set argument in my code not disabling vsync 

### To Reproduce
you can test this out with my application at https://gitlab.com/gamerworld/application or just add 
app.commandLine.appendSwitch('disable-gpu-vsync') to your own code and see that Electron 4.x.x does not disable vsync,

$ git clone https://gitlab.com/gamerworld/application
$ npm install electron@latest
$ edit main.js and remove // from app.commandLine.appendSwitch('show-fps-counter') and save
$ npm start from directory

now open the terminal in the directory and do 
$ npm install electron@3.1.3
$ npm start in the directory again

and you will see the disable vsync argument not in effect and a massive jump in game webgl performance instead of being capped at 60

### Screenshots
example with Electron 4.x.x
http://i.imgur.com/ulqV9hA.png

Same example with disabled vsync working on Electron 3.x.x
http://i.imgur.com/TQS4r0W.png

### Additional Information
For obvious performance reason I would really love the ability to disable vsync on my software.

**Comment by poiru** [comment]
@coreybruce The `disable-gpu-vsync` switch [no longer affects the frame rate](https://chromium.googlesource.com/chromium/src/+/2c951c8f6de48c558783859c611f3dd04a6f46a8%5E%21/components/viz/common/switches.cc). The new `--disable-frame-rate-limit` switch should do the trick, can you give it a shot?

**Comment by coreybruce** [comment]
Oh I see they have changed it, whats the app.commandLine.appendSwitch argument that I can replace in my code?

**Comment by poiru** [comment]
`app.commandLine.appendSwitch('disable-frame-rate-limit')` should work.

**Comment by coreybruce** [comment]
Thanks so much! I really wish they would stop changing the commands/arguments and notify users on changes, it's quite frustrating as a developer when you update your electron version and stuff stops working because of changes you knew nothing about. :P

**Comment by cramatt** [comment]
@poiru do you know if this commandLine switch still works: `app.commandLine.appendSwitch('disable-frame-rate-limit')`

I don't see it listed on the electron docs page here: https://www.electronjs.org/docs/api/command-line-switches#--ignore-connections-limitdomains

**Comment by daarong** [comment]
@cramatt it works on 9.2.1
I am curious why the docs are missing this
