### ISSUE TITLE
Global Shortcut for any key

### ISSUE THREAD

**Issue by woniesong92** [electron/electron#16803]
**Is your feature request related to a problem? Please describe.**
I want to create an app that listens to keyboard events (e.g. keylogger).

**Describe the solution you'd like**
I want to use a Global Shortcut to listen to keyboard events when my electron app is out of focus.

**Describe alternatives you've considered**
Write a native app without Electron

**Additional context**
I haven't found a way to listen to keyboard events when the app is not in focus. Is there already a way to do so?

**Comment by MarshallOfSound** [comment]
> (e.g. keylogger).

Yeah, we aren't going to help you make a keylogger 😄 The `globalShortcut` API is deliberately designed to absorb keypresses so that they are for shortcuts and don't pass-through to other applications.  This use case is not something we're planning on supporting

**Comment by woniesong92** [comment]
Thanks for the answer! I actually want to build a text macro tool where you can store text snippets under short strings (e.g. type "he" to output "hello world"). So to build something like this, Electron is out of question? Sorry if this is asking the same question.

**Comment by akoskm** [comment]
@MarshallOfSound I need this too but for a companion app for writers. Other apps do this as well:

![image](https://user-images.githubusercontent.com/3111627/182524713-c4f34196-62bc-4ab8-816a-d5c9a91d0d18.png)

I believe Discord is also an Electron app. Is this still not possible to do with Electron?
