### ISSUE TITLE
Ubuntu restore window

### ISSUE THREAD

**Issue by GitNomster** [electron/electron#16807]
* **Electron Version** (output of `node_modules/.bin/electron --version`): 4.0.3
* **Operating System** (Platform and Version): Ubuntu 16.04 x64

### Expected Behavior
Restoring minimized window.

### Actual behavior
When i minimize window and then try to restore it from tray icon - nothing happens.

### To Reproduce
[Link to repo](https://github.com/GitNomster/electron-quick-start)

```
$ git clone https://github.com/GitNomster/electron-quick-start
$ npm install
$ npm start || electron .
```

**Comment by mmoraga** [comment]
I have the same issue on Ubuntu 18.04
both with electron 3.1.10 and  5.0.0-beta.3 
Works correctly with electron 2.0.X

**Comment by mceachen** [comment]
Reproduced on electron 3.1.3 on Ubuntu 18.04.2 under default gnome desktop environment.

**Comment by Crazie-ash** [comment]
const createTray = () => {
  tray = new Tray(iconPath);
  const trayMenuT = [{ label: 'Show', click: function () { showWindow() } }, { label: 'Hide', click: function () { hideWindow() } }]
  let trayMenu = Menu.buildFromTemplate(trayMenuT);
  tray.setContextMenu(trayMenu);
};

const showWindow = () => {
  const positioner = new Positioner(win);
  if (process.platform === 'darwin') {
    let a = positioner.calculate('trayCenter', tray.getBounds());
    win.setPosition(a.x, a.y, false);
  }
  if (win.isMinimized()) {
    win.restore();
  }
  win.setVisibleOnAllWorkspaces(true); // put the window on all screens
  win.focus(); // focus the window up front on the active screen
  win.setVisibleOnAllWorkspaces(false); // disable all screen behavior
};

const hideWindow = () => {
    win.minimize();
};


Works fine with mac, windows but not with ubuntu 16.04, 18.04. Is this a bug or something????

**Comment by Ajeey** [comment]
Facing the same issue on 4x.
Workaround is to call minimize before restore
```
win.minimize();
win.restore();
win.focus();
```

**Comment by Crazie-ash** [comment]
try win.hide()... that works well for me

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
