### ISSUE TITLE
Adding support for bf-cfb cipher

### ISSUE THREAD

**Issue by Mic75** [electron/electron#16816]
Hello Electron Team,

As per https://github.com/electron/electron/issues/16195#issuecomment-460380616, it has been suggested to ask fro  missing cipher algo when needed and open an issue.

We're using the `bf-cfb` cipher in our product, with no alternative to change this method since it's used in other part of our system. 

This cipher not being exposed prevent us to upgrade to version 4+.
Could you please expose it?

**Comment by nornagon** [comment]
This cipher was [recently added to boringssl](https://github.com/google/boringssl/commit/6effbf24bc483b5f62add56129925ffe06b80b4a) and described as "the worst of 90's
crypto". We can expose it, but I'd highly recommend you move your app to a more modern cipher suite.

**Comment by Mic75** [comment]
Thanks for the answer @nornagon.
We will consider changing the cipher method used in our system according to this feedback!

This would require some work on our side, since several component are concerned.
In the meantime, could you please expose this cipher so we can move on with version 4?

**Comment by nornagon** [comment]
Closed by https://github.com/electron/electron/pull/32356
