### ISSUE TITLE
Expose cipher DES-EDE-CBC in Electron 4 crypto module

### ISSUE THREAD

**Issue by lonk** [electron/electron#16812]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * v4.0.0
* **Operating System** (Platform and Version):
  * archlinux
* **Last known working Electron version** (if applicable):
  * v3.1.3

Hi !

I just upgraded Electron from version 3 to version 4 and I noticed that the cipher DES-EDE-CBC is no longer exposed in the crypto module, which is breaking my app.

Is it possible to expose it again, as mentioned by @nornagon in #16195 ?

Thank you !

**Comment by nornagon** [comment]
It looks to me like `DES_EDE_CBC` is already exposed, see e.g. https://gist.github.com/e6db0acbf6b736c49c8bab4d86fff0dc which reports the following list in `crypto.getCiphers()` as of Electron 4.0.4:

```["aes-128-cbc","aes-128-cfb","aes-128-ctr","aes-128-ecb","aes-128-ofb","aes-256-cbc","aes-256-cfb","aes-256-ctr","aes-256-ecb","aes-256-ofb","aes-256-xts","des-cbc","des-ecb","des-ede","des-ede-cbc","des-ede3-cbc","rc2-cbc","rc4"]```

**Comment by nornagon** [comment]
Ah, actually it looks like it's listed in `getCiphers` but doesn't work when you try to actually use it. Reopening.

**Comment by patwhite** [comment]
Are these changes going to be available in the 4 branch, or just 5? I'm on 4.0.8 and still don't see RipeMD-160.
