### ISSUE TITLE
detachable <webview> element

### ISSUE THREAD

**Issue by gliheng** [electron/electron#1682]
Hi,

   It would be nice if <webview> element can be detached into separate window for rendering. I don't know if this can be done in electron atm.

**Comment by eric-nyq** [comment]
I need this feature too.

**Comment by zcbenz** [comment]
With current architecture of webview implementation, it is too hard to achieve that. If in future Chrome added the same thing we might try implement this, but for now it is nearly impossible.

**Comment by fsamuel** [comment]
zcbenz@: <webview> in Chrome is built on top of GuestView which supports ripping the content out of the container and attaching it elsewhere. BrowserPluginGuest and GuestViewBase (in Chromium) support Detach + Attach operations.

**Comment by paulcbetts** [comment]
If it's possible, this would be an amazing feature for us at Slack

**Comment by kevinsawicki** [comment]
Can this be closed now that #7157 has been merged and a web contents can be moved across webview and windows?

**Comment by zcbenz** [comment]
I'm good closing this, /cc @paulcbetts for more comments.

**Comment by paulcbetts** [comment]
Super awesome, close it
