### ISSUE TITLE
CPU throttling as command line argument

### ISSUE THREAD

**Issue by ToreJuloe** [electron/electron#16826]
**Is your feature request related to a problem? Please describe.**
Developer machines are often faster than average end user machines, which means that performance issues are not as obvious during development.
We want fast machines for builds and running our various tools, but we also want to see how the app we're building fares on a low-end machine or on a slow network connection.

**Describe the solution you'd like**
Since Chromium allows CPU and network throttling through the developer tools, it would be convenient to be able to set this as command line arguments, so that all windows in a multi-window application, and the main process if possible, would be automatically throttled.

**Describe alternatives you've considered**
Throttling processes on the system level, but this is tedious and error prone and does not play well with tooling in general.

**Comment by nornagon** [comment]
You should be able to do this with `ulimit`, [`cputhrottle`](http://www.willnolan.com/cputhrottle/cputhrottle.html) or similar OS features. I don't think this feature belongs in Electron core.
