### ISSUE TITLE
Not get all process.env in electron render process

### ISSUE THREAD

**Issue by 13banda** [electron/electron#16828]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * v4.0.2
* **Operating System** (Platform and Version):
  *  Ubuntu 18.04 x64 

### Expected Behavior
 Want to get all environment variable using `process.env` in electron render process
### Actual behavior
not get all env in electron render process in render process i use create-react-app to bundle code
```
     console.log(process.env)
     output===> {NODE_ENV: "development", PUBLIC_URL: ""}
```
but when i use 
`console.log(process)`
it have env property with all env (screen shot 3)

### To Reproduce
i also get main env by using `require('electron').remote.process.env` but 
due to nothing in process.env webpack not find any external modules from node_modules

![image](https://user-images.githubusercontent.com/31692610/52478856-b5818d80-2bcc-11e9-9085-2a14a21dcd23.png)
![image](https://user-images.githubusercontent.com/31692610/52478913-e8c41c80-2bcc-11e9-91df-2ab72b59b564.png)
![image](https://user-images.githubusercontent.com/31692610/52478961-101ae980-2bcd-11e9-90a8-3b85ae4bf478.png)

**Comment by MarshallOfSound** [comment]
@13banda 

> i use create-react-app to bundle code

That's your problem, `create-react-app` uses webpack behind the scenes to bundle your code and will replace all instances of `process.env` with a fake `env` that gets injected at build time.  This is expected behavior if you are using `create-react-app`

**Comment by 13banda** [comment]
thanks
