### ISSUE TITLE
TypeError: Cannot read property 'substr' of undefined

### ISSUE THREAD

**Issue by vaidelaplex** [electron/electron#16827]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
1.8.8

* **Operating System** (Platform and Version):
Ubuntu 18.04.1 LTS

### Expected Behavior
Instead of blank screen it should load the website

### Actual behavior
When we are tryng to open a website it is showing blank white screen. After checking in Toggle Developer Tool its showing javascript error in console like - TypeError: Cannot read property 'substr' of undefined

This issue not happening with all website but few website has been showing same issue.    

### To Reproduce

const Nightmare = require('nightmare');
const nightmare = Nightmare({show: true});

doLogin()

async function doLogin() {
	try {
		await nightmare
		 .goto('https://www.example.com') // actual url is different
		 
	} catch (e) {
	  throw (e)
	}
}

### Screenshots

![javascript-error-electron](https://user-images.githubusercontent.com/17119601/52476185-e7dabd00-2bc3-11e9-832b-9784124f3dc3.jpg)

**Comment by nornagon** [comment]
Thanks for the report. Unfortunately we no longer support Electron versions < 2.0.x.

Additionally, that stack trace appears to show an issue in your app's code, not in Electron.
