### ISSUE TITLE
printerInfo status not updated on Windows

### ISSUE THREAD

**Issue by rayonef** [electron/electron#16836]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 3.1.2
* **Operating System** (Platform and Version):
  * Windows 10 (1803)

### Expected Behavior
when calling webContents.getPrinters(), printer status should change when busy. Status stays at 0. Working correctly in macOS.

### Actual behavior
running an interval on getting printer info, printerInfo.status stays unchanged even if the printer is busy

### To Reproduce
run an interval with webContents.getPrinters() on a printer while it is printing

**Comment by ErvingZheng** [comment]
I've seen the issue in 4.0.7 on Windows 10

**Comment by fyousof** [comment]
Having similar issue - any alternative/solution to this?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by WillPoulson** [comment]
Hate to resurrect a very old bug report however I'm experiencing this on the latest version of Electron on Windows 10.

Status seems to be populated for macos, however on Windows for the same printer it's just reporting `0`

**Comment by YuHuaOu** [comment]
> Hate to resurrect a very old bug report however I'm experiencing this on the latest version of Electron on Windows 10.
> 
> Status seems to be populated for macos, however on Windows for the same printer it's just reporting `0`
same for me，dude，how to resolve this question

**Comment by YuHuaOu** [comment]
> 



> Hate to resurrect a very old bug report however I'm experiencing this on the latest version of Electron on Windows 10.
> 
> Status seems to be populated for macos, however on Windows for the same printer it's just reporting `0`

same for me，dude，how to resolve this question

**Comment by WillPoulson** [comment]
@YuHuaOu I've raised #39278 for this. I just need to add some repro steps first.
