### ISSUE TITLE
Chrome extensions: Content script css does not appear to be loaded

### ISSUE THREAD

**Issue by Amy-Lynn** [electron/electron#16831]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 4.0.0
* **Operating System** (Platform and Version):
  * Windows 7 (7601)
* **Last known working Electron version** (if applicable):
  * N/A

### Expected Behavior
Manifest.json content script css files to be loaded into browser window

### Actual behavior
Don't appear to be loaded

### To Reproduce

Manifest.json snippet:

```json
{
  "manifest_version": 2,
  "content_scripts": [
    {
      "matches": [
        "http://*/*",
        "https://*/*"
      ],
      "js": [
        "index.js"
      ],
      "css": ["style.css"]
    }
  ],
  "permissions": [
    "clipboardWrite",
    "activeTab",
    "background"
  ]
}

```

Code where I'm adding the browser extension:

```javascript
BrowserWindow.addExtension(extensionPath);

const childWindow = new BrowserWindow({
webPreferences: {
  nodeIntegration: false
}
});

childWindow.setMenu(null);
childWindow.show();
childWindow.openDevTools();
childWindow.loadURL(url);
```

### Additional Information
If I put at breakpoint at https://github.com/electron/electron/blob/master/lib/browser/chrome-extension.js#L262 , I can see that the CSS content is found and is being passed in

![image](https://user-images.githubusercontent.com/10166933/52480940-20a27400-2b7b-11e9-99c8-303dfddf8f8a.png)

Looking in devtools, I can see that my javascript is loaded, but the CSS isn't there (and isn't affecting the page):

![image](https://user-images.githubusercontent.com/10166933/52481051-71b26800-2b7b-11e9-83b2-415621ccace3.png)

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
