### ISSUE TITLE
dmg may be dangerous and blocked by Chrome

### ISSUE THREAD

**Issue by 4ban** [electron/electron#16856]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 4.0.3
* **Operating System** (Platform and Version):
  * macOS 10.14.3

### Additional Information
Hello, I've created binaries via electron-builder of my application and uploaded it to S3 on AWS. But I can't download the dmg file via chrome.
<img width="372" alt="screen shot 2019-02-07 at 5 43 24 pm" src="https://user-images.githubusercontent.com/2269864/52447812-e647c100-2aff-11e9-807e-db037ff60c72.png">

I **can** download the windows version from S3 via Chrome.
I **can't** download the mac version from S3 via Chrome
I **can** download mac and windows versions from S3 via Firefox.
I **can** download mac and windows versions from gdrive via Chrome
I **can** download mac and windows versions from github releases via Chrome.
I **can** download mac version even from unknown http file storage via Chrome.

The only issue I have is that I can't download the **DMG** file via **Chrome** from **S3**.

Has anyone come across a similar issue?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
