### ISSUE TITLE
Allow BrowserView below BrowserWindow

### ISSUE THREAD

**Issue by IceHacks** [electron/electron#16854]
**Is your feature request related to a problem? Please describe.**
Yeah. When I create a `BrowserView` it is placed above my `BrowserWindow`. Therefore I can not see my dropdown menus.

**Describe the solution you'd like**
I'd like to be able to set the z-index of a `BrowserView` or have an option to display below the `BrowserWindow`. My `BrowserWindow` is transparent and I set it up so you can click through it.

**Describe alternatives you've considered**
`WebView`'s are my choice if I can't get this to work because they are nested in the page.

**Additional context**
Here is my menu being cut-off:
![image](https://user-images.githubusercontent.com/38994479/52512588-b0f7ad80-2ba9-11e9-90cf-b25e4e51aad9.png)

**Comment by MarshallOfSound** [comment]
This is not currently possible with the architecture of `BrowserView`

**Comment by Kant1-0** [comment]
@IceHacks If you have a dropdown menu from your `BrowserWindow` that will overflow on `BrowserView`, the only way to display it is using [context menu](https://electronjs.org/docs/api/menu#menupopupoptions).
```js
const menu = Menu.buildFromTemplate(submenu);

parent.querySelector(children).onclick = (e) => {
  menu.popup({
    window: getCurrentWindow(),
    x: e.target.offsetLeft,
    y: e.target.offsetTop + e.target.offsetHeight,
  });
};
```
Unfortunately these context menus can't be customized with CSS. I guess you'll be able later to convert this dropdown menu into another `BrowserView` when a futur update will able us to use multiple browserView with z-ordering.

Some recent commit here added support for multiple browser views: https://github.com/electron/electron/blob/27bd47a3336ea176bb3f092fc428d7f1758e782f/docs/api/browser-window.md#winaddbrowserviewbrowserview-experimental
```markdown
## win.addBrowserView(browserView) Experimental

- browserView BrowserView

Replacement API for setBrowserView supporting work with multi browser views.
```

**Comment by IceHacks** [comment]
Ok thanks

**Comment by jerrybendy** [comment]
Hi,

I have a similar problem. Only one thing different from @IceHacks , I use `webview` to show my webpage, not `BrowserView`. 

I tried many methods, but my dropdown still behind `webview`.  I checked the code of `beaker` which also built by electron, `beaker` has no this problem. I copied codes of beaker to my project, but still not working. 

I don't know how to resolve this issue, could you give me some advice? Thanks

**Comment by iwiedenm** [comment]
@jerrybendy were you able to figure this out? I was also exploring Beaker for inspiration and I could not figure it out. Would love some guidance if you know the solution! :)

**Comment by jerrybendy** [comment]
@iwiedenm This issue is still in my bug list. I have no idea to figure this out.  😞

**Comment by Suraj-Bhandarkar-S** [comment]
Is this fix implemented? was not able to find it in any source!
