### ISSUE TITLE
Get window id using ipcMain

### ISSUE THREAD

**Issue by MertDalbudak** [electron/electron#16863]
I want to access the window ID when an ipcRenderer triggers an ipcMain.
When using:
```
ipcMain('getFile', (event, args)=>{
    let window_id = ?;
});
```
I am not able to tell from which window it is been triggered.
I am able to get the browserWindowOptions but not the BrowserWindow itself.

How can I tell which window has requested the window.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by MertDalbudak** [comment]
This is kind of a feature request. Because there is no way of getting the BrowserWindow to determine where the request comes from.

**Comment by MarshallOfSound** [comment]
@MertDalbudak `event.sender` is in our documentation for `ipcMain`.  --> https://electronjs.org/docs/api/ipc-main#eventsender ..

**Comment by MertDalbudak** [comment]
Ok. Indeed I was able to get the ID of the window from webContents.
I printed `webContents` and it didn't show anything on the console.
Sorry for any inconvenience caused by this thread.

**Comment by nous-** [comment]
The answer wasn't clear to me from the documentation. [event](https://www.electronjs.org/docs/latest/api/structures/ipc-main-event).sender.id is the same as [new BrowserWindow().id](https://www.electronjs.org/docs/latest/api/browser-window#winid-readonly). Ie.

```js
const { ipcMain } = require('electron')
ipcMain.on('asynchronous-message', (event, arg) => {
  event.sender.id;  // this is the id of the BrowserWindow that sent the message
})
```

**Comment by Tristan10** [comment]
> The answer wasn't clear to me from the documentation. To clarify, [event](https://www.electronjs.org/docs/latest/api/structures/ipc-main-event).sender.id is the same as [new BrowserWindow().id](https://www.electronjs.org/docs/latest/api/browser-window#winid-readonly). Ie.
> 
> ```js
> const { ipcMain } = require('electron')
> ipcMain.on('asynchronous-message', (event, arg) => {
>   event.sender.id;  // this is the id of the BrowserWindow that sent the message
> })
> ```

For me, `event.sender.id` does not match and BrowserWindow IDs from the results of `BrowserWindow.getAllWindows()`.

**Comment by ArsalImam** [comment]
@Tristan10 I have been also stuck into the same problem. After digging down to identify the root cause, I have figured out that the  `event.sender.id` is not the id of BrowserWindow but basically it is the id of the webContents inside the BrowserWindow. This means it should be compared something like mentioned below,

```
const { ipcMain } = require('electron')
const someWindow = new BrowserWindow(...);
ipcMain.on('asynchronous-message', (event, arg) => {
  //event.sender.id;  // this is the id of the BrowserWindow.webContents.id that sent the message
  if (event.sender.id == someWindow.webContents.id)
})

```

**Comment by natasweb** [comment]
how's this?
```
const windowId = BrowserWindow.getAllWindows().find((win) => win.webContents.id === event.sender.id).id
```

**Comment by ArnieGA** [comment]
@MertDalbudak 

### How about this alternative? (electron@19.0.4):
```
const { BrowserWindow, ipcMain } = require('electron');

ipcMain.on(<My Channel/Event>, (event) =>{
    const sendingBrowserWindow = BrowserWindow.fromWebContents(event.sender);
});
```

In my case, I was implementing a custom titlebar so I needed to implement the window controls functionality, and therefore the maximize/restore logic.  All this **while running without `nodeIntegration` and with `contextIsolation`**.  So this solution worked for me, and didn't have to go through the hustle of finding an id:

### Electron side
```
const { BrowserWindow, ipcMain } = require('electron');

ipcMain.on('window:maximize', (event) => {
    BrowserWindow.fromWebContents(event.sender).maximize();
    event.reply('window:maximized'); // Handle at sender window via contextBridge (preload)
});
ipcMain.on('window:unmaximize', (event) => {
    BrowserWindow.fromWebContents(event.sender).unmaximize();
    event.reply('window:unmaximized'); // Handle at sender window via contextBridge (preload)
});
```
Hope this helps, cheers! ;-)

**Comment by eXhumer** [comment]
```js
ipcMain.on('example-channel', (event, args) => {
  const senderWindow = BrowserWindow.fromWebContents(event.sender); // BrowserWindow or null
  console.log('BrowserWindow.fromWebContents', senderWindow);
})
```

`event.sender` is the `webContents` property from the associated BrowserWindow instance and the associated window can by retrieved using the [`BrowserWindow.fromWebContents`](https://www.electronjs.org/docs/latest/api/browser-window#browserwindowfromwebcontentswebcontents) method.

This seems to be the best way currently to retrieve the sender window from the IPC main event directly.
