### ISSUE TITLE
Exit status 4294967295 when passing arguments after a URL

### ISSUE THREAD

**Issue by raybooysen** [electron/electron#16889]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
4.0.4
* **Operating System** (Platform and Version):
Windows 10

### Expected Behavior
The application should start as normal

### Actual behavior
The application exits with an error code:
```
> electron-quick-start@1.0.0 start C:\source\electron-quick-start
> electron . "-U" "Superuser" "--env" "environment" "--manifest" "http://www.google.com/manifest.json" "--token" "dev"

npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! electron-quick-start@1.0.0 start: `electron . "-U" "Superuser" "--env" "environment" "--manifest" "http://www.google.com/manifest.json" "--token" "dev"`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\BooysenR\AppData\Roaming\npm-cache\_logs\2019-02-12T02_35_04_740Z-debug.log
```

### To Reproduce

```
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start
npm install
npm start -- -U Superuser --env environment --manifest "http://www.google.com/manifest.json" --token dev

```

**Comment by raybooysen** [comment]
If I remove `--token dev`, it works again.

**Comment by raybooysen** [comment]
Additionally, I can only reproduce this on Windows 10.  I've tried on Linux Mint and everything works fine.

**Comment by PiRXlv** [comment]
I played around with it a while and it seems that URI parsing in parameters is to blame. If you switch last two parameters 
`npm start -- -U Superuser --env environment --token dev --manifest "http://www.google.com/manifest.json"`

it starts to work again.

**Comment by raybooysen** [comment]
https://github.com/electron/electron/blob/master/atom/app/command_line_args.cc#L47

I think this is what we're seeing.  If we have a URL first, then `block_args` is set to true.  On the next iteration of the loop, block_args is checked, and false is returned, which causes electron to exit with -1

**Comment by raybooysen** [comment]
#13039 seems to discuss it, with a workaround

**Comment by raybooysen** [comment]
Unsure if I should leave this open.  I can clearly see that it's disabled by default, but I can't seem to find reasons, and because it dies quietly we don't know why it's failing.

**Comment by gannons** [comment]
@raybooysen thanks for reporting this. I spent a, **very** confused, hour trying to figure out what was going wrong when 2 new cmd args were added.

The work around for me was to change 

> --url https://my-service-url.com/api/v1 --location ~/Downloads/args/

to either

> --location ~/Downloads/args/ --url https://my-service-url.com/api/v1

or

> -- --url https://my-service-url.com/api/v1 --location ~/Downloads/args/

But it still feels like a programmer trap as the 1st approach is so standard and it'll work on Mac/Linux.

**Comment by fourpixels** [comment]
Any news? It's been a while, and now that vue-cli has updated electron version - it doesn't work anymore :)

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by pedro-surf** [comment]
Any idea about what this code means? 4294967295 
I have it when my app crashes after feeding a large data set, I'd like to have a clue. Thanks

**Comment by classmate-one** [comment]
/**
   * 监听页面崩溃
   */
  webCrashed = (event) => {
    const redirect = this.getWebContentURL(event);
    console.log(redirect)
    const filePath = require('path').join(__dirname, '../../public/404.html');
    debugger // error ↓
    this.loadFile(filePath, {
      query: {
        redirect,
        lang: require('../../store').get('lang'),
      }
    });
  }
