### ISSUE TITLE
[win] javascript not executed in renderer process

### ISSUE THREAD

**Issue by Gvozd** [electron/electron#16885]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 5.0.0-beta.2
* **Operating System** (Platform and Version):
  * Windows 7 Professional (SP1)

### Expected Behavior
Node/Chromium/Electron version at window, in electron-quick-start

### Actual behavior
No versions in main page
Cannot open devtools for view js errors - see #16883

### To Reproduce
https://github.com/Gvozd/electron-quick-start/tree/issue-16883
based on electron-quick-start. only updated electron to 5.0.0-beta.2
Just open

### Screenshots
![image](https://user-images.githubusercontent.com/1365584/52594130-cb58b200-2e5b-11e9-8531-d55cf989faa5.png)

**Comment by MarshallOfSound** [comment]
This is expected behavior, the default for `nodeIntegration` changed in V5.  `quick-start` needs to be updated
