### ISSUE TITLE
Running electron in docker

### ISSUE THREAD

**Issue by luxigo** [electron/electron#16892]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  4.0.4 
* **Operating System** (Platform and Version):
  Debian 9
* **Last known working Electron version** (if applicable):
  2.0.x

### Expected Behavior
Should display an error when the host system is using an incompatible video driver, or automatically disable gpu rendering (partially if possible) and display a warning message.

### Actual behavior
Nothing is displayed in the window, no error message in the console

### To Reproduce

```bash
# create Dockerfile
mkdir /tmp/electron-docker
cd /tmp/electron-docker
cat << 'EOF' > Dockerfile
FROM debian:stretch
ARG user=electron
ARG debian_mirror=deb.debian.org
RUN sed -r -i -e s/deb.debian.org/$debian_mirror/ /etc/apt/sources.list \
  && apt-get update \
  && apt-get install -y --force-yes \
      build-essential \
      bzip2 \
      ca-certificates \
      curl \
      git \
      wget \
      python \
      vim \
      screen \
      net-tools \
      xvfb \
      fakeroot \
      gconf2 \
      gconf-service \
      gvfs-bin \
      libasound2 \
      libcap2 \
      libgconf-2-4 \
      libgtk2.0-0 \
      libnotify4 \
      libnss3 \
      libxkbfile1 \
      libxss1 \
      libxtst6 \
      libgl1-mesa-glx \
      libgl1-mesa-dri \
      xdg-utils \
 && useradd --create-home --shell /bin/bash $user
USER $user
WORKDIR /home/$user
ARG nvm_version=v0.34.0
ARG node_version=v10
RUN wget -q -O /tmp/install.sh https://raw.githubusercontent.com/creationix/nvm/$nvm_version/install.sh \
 &&  . /tmp/install.sh \
 && export NVM_DIR="/home/$user/.nvm" \
 && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" \
 && nvm install $node_version \
 && npm install -g npm \
 && npm install -g \
      electron \
      q 
USER root
ARG app=app
COPY $app /home/$user/$app
RUN chown $user.$user /home/$user/app -R
USER $user
WORKDIR /home/$user/$app
RUN bash -l -c "\
npm install \
"
CMD bash -l -c "electron main.js"
EOF

# dummy app
mkdir app
test -f app/main.js || cat << 'EOF' > app/main.js
var electron=require('electron');
electron.app.on('ready', function() {
  var win = new electron.BrowserWindow({ width: 800, height: 600 });
  win.loadURL('https://github.com');
});
EOF

# build and run container
docker build \
  --build-arg debian_mirror=${DEBIAN_MIRROR:-deb.debian.org} \
  -t electron-docker \
  . \
&& docker run \
  --name=electron-docker \
  --rm=true \
  -v /tmp/.X11-unix:/tmp/.X11-unix/ \
  -v /dev/shm:/dev/shm \
  -v /mnt:/mnt \
  -e DISPLAY \
  -e DEBUG \
  -it \
  electron-docker
```

### Additional Information
At least it works when using the "--disable-gpu" option, (maybe there is a better solution ie: without totally disable gpu)
```bash
docker run \
  --name=electron-docker \
  --rm=true \
  -v /tmp/.X11-unix:/tmp/.X11-unix/ \
  -v /dev/shm:/dev/shm \
  -v /mnt:/mnt \
  -e DISPLAY \
  -e DEBUG \
  -it \
  electron-docker \
  bash -l -c "electron --disable-gpu main.js"
```

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by jbanayo** [comment]
I used the same solution as above however I received this errors

> electron . --no-sandbox
/app/node_modules/electron/dist/electron exited with signal SIGSEGV

How can I solve this? How to have an electron running in docker. 

docker file:
`# Use a Debian-based image as the base image
FROM debian:stretch

# Set the ARG variables for user and Debian mirror
ARG user=electron
ARG debian_mirror=deb.debian.org

# Update the apt sources.list to use the specified Debian mirror
RUN sed -r -i -e s/deb.debian.org/$debian_mirror/ /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y --force-yes \
        build-essential \
        bzip2 \
        ca-certificates \
        curl \
        git \
        wget \
        python \
        vim \
        screen \
        net-tools \
        xvfb \
        fakeroot \
        gconf2 \
        gconf-service \
        gvfs-bin \
        libasound2 \
        libcap2 \
        libgconf-2-4 \
        libgtk2.0-0 \
        libnotify4 \
        libnss3 \
        libxkbfile1 \
        libxss1 \
        libxtst6 \
        libgl1-mesa-glx \
        libgl1-mesa-dri \
        xdg-utils \
    && useradd --create-home --shell /bin/bash $user

# Switch to the user we created
USER $user

# Set the working directory to the user's home directory
WORKDIR /home/$user

# Set the NVM and Node.js versions as ARG variables
ARG nvm_version=v0.34.0
ARG node_version=v10

# Install NVM (Node Version Manager) and Node.js
RUN wget -q -O /tmp/install.sh https://raw.githubusercontent.com/creationix/nvm/$nvm_version/install.sh \
    && . /tmp/install.sh \
    && export NVM_DIR="/home/$user/.nvm" \
    && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" \
    && nvm install $node_version \
    && npm install -g npm

# Install Electron globally
RUN npm install -g electron

# Switch back to the root user to copy the application files
USER root

# Copy the application directory into the container
COPY app /home/$user/app

# Set ownership of the application directory to the user we created
RUN chown $user.$user /home/$user/app -R

# Switch back to the user we created
USER $user

# Set the working directory to the application directory
WORKDIR /home/$user/app

# Install application dependencies
RUN npm install

# Set the default command to start the Electron application
CMD ["npm", "start"]`
