### ISSUE TITLE
Mac: custom URL protocol scheme loses colon in url on open-url event

### ISSUE THREAD

**Issue by christophpre** [electron/electron#16896]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 4.0.4
* **Operating System** (Platform and Version):
  * macOS 10.13.6

### Expected Behavior
Passing an url to an electron application with a custom protocol handler, like described in https://electronjs.org/docs/api/app#event-open-url-macos, should preserve the colon in the url.

i.e. if the protocol was myelectronapp://, typing myelectronapp://https://www.google.com in another Browser should open the Electron application and pass https://www.google.com as the url argument in the **open-url** event.

```javascript

app.on('open-url', (event, url) => {
 url // 'https://www.google.com'
 });
```

### Actual behavior
```javascript
app.on('open-url', (event, url) => {
 url // 'https//www.google.com'
 });
```

### To Reproduce
Define an URL Scheme like described in https://electronjs.org/docs/api/app#event-open-url-macos and open the electron application with another like so: myelectronapp://https://www.google.com

### Additional Information
Works in process.argv that are passed to the main process, when opening an electron application with a url scheme on Windows.
Is it possible that macOS doesn't allow colons in arguments passed to url schemes?

**Comment by codebytere** [comment]
@christophpre i using the [following code](https://gist.github.com/codebytere/1f5d6c1b6af09aa420b336d0bd804db3) on macOS, I see this for `process.argv` in console:

```
Array(19)
0: "/Users/codebytere/Library/Application Support/Electron Fiddle/electron-bin/4.0.4/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper"
1: "--type=renderer"
2: "--no-sandbox"
3: "--enable-features=SharedArrayBuffer"
4: "--disable-features=MacV2Sandbox"
5: "--service-pipe-token=5122872547380339528"
6: "--lang=en-US"
7: "--app-path=/var/folders/8c/j47w04xs74v6zpr310q2l4mr0000gn/T/tmp-11815DYSVFgs3mfSR"
8: "--node-integration=true"
9: "--webview-tag=true"
10: "--no-sandbox"
11: "--background-color=#fff"
12: "--num-raster-threads=4"
13: "--enable-zero-copy"
14: "--enable-gpu-memory-buffer-compositor-resources"
15: "--enable-main-frame-before-activation"
16: "--service-request-channel-token=5122872547380339528"
17: "--renderer-client-id=4"
18: "https://www.google.com"
length: 19
```

`18: "https://www.google.com"` seems to correctly preserve the colon.

**Comment by christophpre** [comment]
Tried to reproduce this again. Apparently my error description is wrong. The colon is lost earlier, when retrieving an an url from **open-url** event from app (https://electronjs.org/docs/api/app#event-open-url-macos). I will edit the description.

**Comment by meekaah** [comment]
my thinking is that you should be urlencoding whatever you are passing in your custom protocol url
ie : myelectronapp://https%3A%2F%2Fwww.google.com

**Comment by codebytere** [comment]
The above is correct and also what I would recommend in this instance. Please let me know if the issuer persists!
