### ISSUE TITLE
Allow `MenuItem` options to be a function returning the options

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#16895]
**Is your feature request related to a problem? Please describe.**

It's currently very inconvenient to create (dynamic) MenuItem's that change based on some condition. Most apps need this, but it requires recreating and replacing the whole menu.

**Describe the solution you'd like**

If `MenuItem` accepted a function that returns the options, and called that function before showing the menu, it would solve most problems with creating dynamic `MenuItem`'s.

Example:

```js
new MenuItem(() => ({
	label: 'Foo',
	checked: someCondition === true
}));
```

**Describe alternatives you've considered**

This could be narrowed to just the `label`, `checked`, `enabled`, `visible` options, as that would cover most use-cases.

```js
new MenuItem({
	label: 'Foo',
	checked: () => someCondition === true
});
```

**Additional context**

This is a slight duplicate of https://github.com/electron/electron/issues/528, but that issue has gone unanswered for years and doesn't seem to be going anywhere. This issue includes a concrete proposal to solve the main use-cases.

**Comment by codebytere** [comment]
@sindresorhus i'll do my best to look into this!

**Comment by codebytere** [comment]
After some research, our Menu infrastructure at this time is not conducive to this and as such it wouldn't be possible in quite this way. I'll keep looking into how we might introduce some dynamism through other means though.
