### ISSUE TITLE
Maximized window with the transparency feature enabled

### ISSUE THREAD

**Issue by C4Grey** [electron/electron#1690]
On Windows 8.1 the transparency feature works fine until the moment when a window becomes maximized. After that it become to look like this(notice the frame style and also it looks like the additive blending mode is applied):
![transparency_issue](https://cloud.githubusercontent.com/assets/2578826/7640670/50a9d29c-fa8d-11e4-88e6-7d02cad4b534.png)
Is this bug related to the specific version of Windows(haven't checked it on earlier versions)? I've tried to look into the Electron sources but can't find entry points where it works with DWM...
P.S. 
I have just checked this on Windows 7, same behaviour.

**Comment by sapioit** [comment]
Oh, so I am working on [this project](https://github.com/sapioit/Colliderr) and I am trying to have the FullScreen working properly... but this is what I get...

If you do know a workaround, please do tell me about it!

## Normal (not maximized nor fullscreen)

![image](https://cloud.githubusercontent.com/assets/3173159/11228488/82aa8548-8d95-11e5-8cab-90678ae8950c.png)

## Maximized (space around the html of the BrowserWindow)

![image](https://cloud.githubusercontent.com/assets/3173159/11228503/9ee6d108-8d95-11e5-877d-dc16274f4db6.png)

## Full Screen (no transparency where it should be)

![image](https://cloud.githubusercontent.com/assets/3173159/11228508/a942b11c-8d95-11e5-9059-02bf7fb603a4.png)

**Comment by hackwaly** [comment]
Will this bug to be resolved officially?

**Comment by sapioit** [comment]
No idea. I haven't checked since then.
