### ISSUE TITLE
Upgrading from old version - webContents.getId() no longer works

### ISSUE THREAD

**Issue by Bizarrus** [electron/electron#16918]
I've tried to upgrade my old `electron` app. The old electron version was `1.6.2`.

Currently, when i receive an `IPC` message, the `sender.Id()` was checked with `webContents.getId()`:

```javascript
IPC.on('window:init', function(event, args) {
	if(typeof(_window) == 'undefined' || _window == null || typeof(_window.webContents) == 'undefined' || _window.webContents == null) {
		return;
	}
			
	if(!event.sender.isDestroyed() && _window.webContents.getId() === event.sender.getId()) {
	/* Other usage, but not excellent: */
	// if(_window == Window.getFocusedWindow()) {
		_callbacks.onLoad();
	}
}.bind(this));
```

But with the newest version, `webContents.getId()` will be `undefined`. How i can fix these issue without search the API changes on over 17 pages?

**Comment by MarshallOfSound** [comment]
@Bizarrus `getId` was never documented or official API.  There is a property `webContents.id` --> https://electronjs.org/docs/api/web-contents#contentsid that you should be using for this purpose.
