### ISSUE TITLE
webview and window.open don't auto-play youtube videos

### ISSUE THREAD

**Issue by vasyl-shumskyi** [electron/electron#16927]
Hi guys,

webview and [window.open](https://electronjs.org/docs/api/window-open#windowopenurl-framename-features) doesn't auto-play youtube videos in electron `4.0.4`.

I send `autoplay=1` as mentioned in [Youtube docs](https://developers.google.com/youtube/player_parameters?hl=en), but no luck. 

In the same time it auto-plays just fine in incognito Chrome window.

Here is the simple code of `webview`

```html
<webview id="youtube" src="https://www.youtube.com/embed/M7lc1UVf-VE?autoplay=1"></webview>
```
Or `window.open`

```javascript
window.open("https://www.youtube.com/embed/M7lc1UVf-VE?autoplay=1", "youtube")
```

Any help will be greatly appreciated!

**Comment by codebytere** [comment]
@vasyl-shumskyi using the [following code](https://gist.github.com/codebytere/1f5d6c1b6af09aa420b336d0bd804db3)

I see this for `process.argv` in console:

```
Array(19)
0: "/Users/codebytere/Library/Application Support/Electron Fiddle/electron-bin/4.0.4/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper"
1: "--type=renderer"
2: "--no-sandbox"
3: "--enable-features=SharedArrayBuffer"
4: "--disable-features=MacV2Sandbox"
5: "--service-pipe-token=5122872547380339528"
6: "--lang=en-US"
7: "--app-path=/var/folders/8c/j47w04xs74v6zpr310q2l4mr0000gn/T/tmp-11815DYSVFgs3mfSR"
8: "--node-integration=true"
9: "--webview-tag=true"
10: "--no-sandbox"
11: "--background-color=#fff"
12: "--num-raster-threads=4"
13: "--enable-zero-copy"
14: "--enable-gpu-memory-buffer-compositor-resources"
15: "--enable-main-frame-before-activation"
16: "--service-request-channel-token=5122872547380339528"
17: "--renderer-client-id=4"
18: "https://www.google.com"
length: 19
```

`18: "https://www.google.com"` seems to correctly preserve the colon.

**Comment by codebytere** [comment]
@vasyl-shumskyi please go back and fill out the template that you deleted with missing info including operating system before the maintainers can triage this issue.

**Comment by Unitech** [comment]
Adding `&mute=1` after `autoplay=1` did the trick
