### ISSUE TITLE
unstable behavior when creating a tabbed window

### ISSUE THREAD

**Issue by shin-kinoshita** [electron/electron#16925]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * v4.0.4
* **Operating System** (Platform and Version):
  * macOS 10.14.3
* **Last known working Electron version** (if applicable):
  * v3.1.3

### Expected Behavior
be created a tabbed window without any stress.

### Actual behavior
it actually works but takes few seconds till complete and the tabbed window would be much unstable, especially making it full screen state.

### To Reproduce
```
import { app, BrowserWindow } from 'electron';
app.on('ready', () => {
  const window = new BrowserWindow();
  window.addTabbedWindow(new BrowserWindow());
});
```

### Additional Information
I found that the code works well with electron v3.1.3.

**Comment by bpasero** [comment]
@sofianguy I can reproduce in VSCode and would consider this a blocker for us to update to 4.0.x.

**Comment by WSLUser** [comment]
ping

**Comment by codebytere** [comment]
Interestingly, this is only true in 4: it's back to normal in `v5.0.0` 🤔

**Comment by zcbenz** [comment]
Some observations: 
1. The `addTabbedWindow()` call takes usual time;
2. The CPU usage is normal even though window is lagging;
3. Using `TopLevelWindow` instead of `BrowserWindow` still has the problem.

**Comment by bpasero** [comment]
Confirmed fixed, thanks a lot for the fast turnaround.

**Comment by sofianguy** [comment]
fixed in https://github.com/electron/electron/pull/18314
