### ISSUE TITLE
chrome.tabs.executeScript callback doesn't provide return value

### ISSUE THREAD

**Issue by stewartlord** [electron/electron#16940]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 4.0.4
* **Operating System** (Platform and Version):
  * macOS 10.13.6
* **Last known working Electron version** (if applicable):
  * n/a

### Expected Behavior
`chrome.tabs.executeScript` callback should receive an array of return values from executed scripts.

### Actual behavior
Callback receives `[undefined]`

### To Reproduce
In your extension's background script:
```
chrome.tabs.executeScript(1, {code: `return true`}, 
  results => alert(JSON.stringify(results))
)
```

### Additional Information
PR to follow

**Comment by jkleinsc** [comment]
Fixed via #16941
