### ISSUE TITLE
App shows black screen when capturing with OBS. (Windows 10)

### ISSUE THREAD

**Issue by 3GOMESz** [electron/electron#16955]
I'm creating a kind of game with electron without using engine. But one thing has bothered me lately. When I try to capture the window with Open Broadcaster Software(One of the most commonly used programs for this purpose), the software shows a black screen.
I'm using Windows 10 and realized that if the application is in compatibility mode for Windows 7, the screen is displayed correctly.
If the GPU Acceleration is disable, the screen also is displayed correctly.
Is there any way to force an electron application to run in compatibility mode?

**Comment by nornagon** [comment]
I believe this is a limitation of OBS and not something Electron can fix. If you want to force your app to run without GPU acceleration, you can put this code in your main process JS:

```js
app.commandLine.appendSwitch("disable-gpu")
```

**Comment by 3GOMESz** [comment]
OK. Thank you for the attention. 👍 
I will try to contact the OBS developers.

**Comment by 3GOMESz** [comment]
Update: I contacted an OBS developer. Unfortunately he said me that is not an OBS, Electron or Chromium fault. It's just an operating system issue. 

In his words: 
"But there's unfortunately just nothing I can do about capturing browser-based applications due to that render technique they're all using which bypasses the windows GDI. I have to wait for Microsoft on it".

**Comment by 3GOMESz** [comment]
I hope this problem is solved someday. I believe that applications made in electron have a tendency to become more and more common. This limitation for capturing the application can be detrimental to some types of applications.

**Comment by framerate** [comment]
This is the exact issue we're having with our game. Compatibility mode is how we've fixed it. My current plan is to put an option in the config file `ENABLE_STREAMER_MODE` which turns off GPU with a warning to the user that it might limit performance and likely a link to this or another bug thread for transparency.

I wanted to post here to encourage others to do the same and maybe we can all direct to the same place once it's figured out. Feel free to reach out to me if you want to band together for information transparency

**Comment by kevinpeno** [comment]
@framerate which compatibility mode option for the executable was the one that made it work once GPU rendering was disabled? Was it a windows compatibility mode setting, an electron one?

**Comment by kevinpeno** [comment]
For reference: When @framerate said "Compatibility Mode" they mean to set the executable properties to "Run this program in compatibility mode for: Windows 8".

**Comment by framerate** [comment]
@kevinpeno I thought it was one or the other. Compatibility mode made it work, or as an alternative you could disable GPU?

**Comment by kevinpeno** [comment]
@framerate I tried just disabling gpu and compatibility mode was required anyway. I then went back to a build w/o gpu disabled and it worked with only compatibility mode set.

**Comment by framerate** [comment]
Has anyone had any updates to this from OBS perhaps? @3GOMESz ? :D

**Comment by framerate** [comment]
FYI we are experimenting with the following code and have had some success:

![image](https://user-images.githubusercontent.com/74291/66070429-241dad80-e506-11e9-8222-851e5814428c.png)

**Comment by 3GOMESz** [comment]
> Has anyone had any updates to this from OBS perhaps? @3GOMESz ? :D

I haven't had much success exactly but I'm working on testing to implement an electron injection in an SDL window with offscreen rendering.

**Comment by framerate** [comment]
We've had some luck recently, for better or for worse. We added a `streamMode` option and investigated how to get OBS to work with best performance. Seems like on win10 the troublesome one is `disable-gpu-compositing` which we flag with our streamerMode toggle (with a degraded performance warning)

```
let disableGpuCompositing = false
if (options.streamerMode) {
  switch (os.platform()) {
    case 'win32': {
      const osMajorVersion = parseInt(os.release().split('.')[0])
      if (osMajorVersion >= 10) {
        disableGpuCompositing = true
      }
      break
    }
    default:
      break
  }
}

if (options.disableGPU) {
  app.commandLine.appendSwitch('disable-gpu')
}

if (disableGpuCompositing) {
  app.commandLine.appendSwitch('disable-gpu-compositing')
}

if (options.disableGPU || disableGpuCompositing) {
  app.commandLine.appendSwitch('disable-accelerated-video-decode')
  app.commandLine.appendSwitch('disable-accelerated-video-encode')
}
```

**Comment by 3GOMESz** [comment]
Good news guys, apparently OBS recently implemented a system that detects chrome-based windows and uses a different method to capture the context without returning an empty black screen. I don't know about other capture programs in their way of handling the way windows 10 treats a certain capture mode but the obs seems to have solved that.
