### ISSUE TITLE
Error when running an electron app with native module ( node-rdkafka ) on MacOs.

### ISSUE THREAD

**Issue by chhaymenghong** [electron/electron#16951]
* **Electron Version** (output of `node_modules/.bin/electron --version`):4.0.0
  * 
* **Operating System** (Platform and Version):
  *  MacOs 10.12.6
* **Last known working Electron version** (if applicable):
  * 

### Expected Behavior

App launches without error.
### Actual behavior

App launches with the following error:
dlopen(/Applications/Plotter.app/Contents/Resources/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node, 1): Library not loaded: /Users/chhay/Desktop/Plotter/node_modules/node-rdkafka/build/deps/librdkafka.1.dylib
  Referenced from: /Applications/Plotter.app/Contents/Resources/app/node_modules/node-rdkafka/build/Release/node-librdkafka.node
  Reason: no suitable image found.  Did find:
	/Users/chhay/Desktop/Plotter/node_modules/node-rdkafka/build/deps/librdkafka.1.dylib: stat() failed with errno=13
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602)
    at tryModuleLoad (internal/modules/cjs/loader.js:541)
    at Function.Module._load (internal/modules/cjs/loader.js:533)
    at Module.require (internal/modules/cjs/loader.js:640)
    at require (internal/modules/cjs/helpers.js:20)
    at bindings (/Applications/Plotte…ngs/bindings.js:112)
    at Object.<anonymous> (/Applications/Plotte…ka/librdkafka.js:10)

Looks like it is looking for /Users/chhay/Desktop/Plotter/node_modules/node-rdkafka/build/deps/librdkafka.1.dylib which doesn't exist on the new Mac Box I was trying to run the app in. The path exists in the Mac Box I built the app in though.

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by nornagon** [comment]
https://electronjs.org/docs/tutorial/using-native-node-modules

**Comment by chhaymenghong** [comment]
I found a workaround for it and mentioned it in here: https://github.com/Blizzard/node-rdkafka/issues/570. In case someone run into the same issue and not sure what to do.
