### ISSUE TITLE
Webview only assume focused after delay

### ISSUE THREAD

**Issue by mjbvz** [electron/electron#16953]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 4.0.4
* **Operating System** (Platform and Version):
  *  macOS 10.14.2
* **Last known working Electron version** (if applicable):
  * 2.x 

### Expected Behavior
For code that calls `.focus()` on a webview and then `.focus()` on another element, the other element should end up focused:

```js
webview.focus();
textarea.focus();
```

### Actual behavior
The other element is focused first but then the webview steals back focus after a few milliseconds. Sometimes this is on the next tick and sometimes it is after a few ms delay.

### To Reproduce
1. Run code from this electron fiddle https://gist.github.com/22194dfac0d5ca3d29a340aab82cb9db Main logic is in `renderer.js`
1. Open developer tools console to see logs

### Screenshots
Console output.

<img width="557" alt="screen shot 2019-02-13 at 6 53 01 pm" src="https://user-images.githubusercontent.com/12821956/52759417-a598ed80-2fc0-11e9-804a-a44da7484f4b.png">

**Comment by ankurdengla1996** [comment]
Is this related to https://github.com/electron/electron/issues/14474?

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by mjbvz** [comment]
Fixed for me with Electron 8.0.1
