### ISSUE TITLE
electron doesn't work on redhat6.6

### ISSUE THREAD

**Issue by penghzhang** [electron/electron#16956]
Recently, I download the electron(v4.0.4) and run it on my linux(redhat6.6), it doesn't work, and output below message:
[root@localhost electron]# ./electron
./electron: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./electron)
./electron: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by ./electron)
./electron: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by ./electron)
./electron: /lib64/libdbus-1.so.3: no version information available (required by ./electron)
./electron: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/share/node-v10.15.1-linux-x64/lib/node_modules/electron/./libffmpeg.so)

I tried to upgrade the glibc, but I find it has been the latest version(v2.12) for the system. If I force to upgrade this library, it will cause system fault.

My linux inforamtion are as follows:
[root@localhost electron]# lsb_release  -a
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 6.6 (Santiago)
Release:        6.6
Codename:       Santiago

Could you give me any suggestion for this situation?

**Comment by MarshallOfSound** [comment]
Same cause as #16205 so merging into that.

Also worth noting that redhat 6.6 is ~4+ years old (released in 2014), you probably need to update to get to a version that supports a more recent glibc
