### ISSUE TITLE
Set default parameters through the configuration file

### ISSUE THREAD

**Issue by spitWind** [electron/electron#16965]
**Is your feature request related to a problem? Please describe.**
1. Set default parameters through the configuration file

**Describe the solution you'd like**
I have multiple operating systems, I want to modify the default parameters of vscode, such as the location where the user data files are stored, and expand the storage location;
Start command line
`Code.exe" --user-data-dir=../vscode/data --extensions-dir=../vscode/extensions`
But sometimes the program starts directly, such as restarting the program, the command line starts the program, which makes it impossible to set the configuration. I hope to have a configuration file to set some default parameters.

**Describe alternatives you've considered**

**Additional context**

**Comment by MarshallOfSound** [comment]
@spitWind This functionality is something that apps should provide, not Electron code 👍
