### ISSUE TITLE
showOpenDialog wrong Documentation and Typescript typings

### ISSUE THREAD

**Issue by patsimm** [electron/electron#16960]
The callback of [showOpenDialog](https://electronjs.org/docs/api/dialog#dialogshowopendialogbrowserwindow-options-callback) is defined to be called with the first argument being a `String[]`. When clicked 'Cancel' it is not called with an empty array - that was what I was expecting reading the docs - but was called with `undefined`.

Thus the docs are wrong. The first argument of the callback should be of type `String[] | undefined`.

**Comment by codebytere** [comment]
From the docs:
> If the dialog is cancelled this will be `undefined`.

We can potentially improve typings in the future but we've documented this for now, and other changes would require changes to underlying typescript infra.

**Comment by MarshallOfSound** [comment]
🎉 Turns out our ts generator supports this case 🤔 PR ☝️
