### ISSUE TITLE
Implementing offscreen rendering into External Textures

### ISSUE THREAD

**Issue by ronhab** [electron/electron#16961]
Current offscreen rendering approach requires to choose between two non-optimal options:
1. Disabling hardware acceleration - so grabbing frames from memory is fast (since they are being generated in system RAM) but the offscreen rendering itself is slower (since it is done by CPU) and some features are disabled (i.e. WebGL and 3D CSS).
2. Enabling hardware acceleration - grabbing frames from GPU memory is slow, but the offscreen rendering is fast (done by GPU) and all features available.

Would it be possible to implement a 3rd approach in Electron, which will allow to use hardware acceleration for rendering the frames, but instead of returning them as memory buffers (thus requiring a copy from GPU to system RAM) return a handle for the GPU texture (or render directly to a texture supplied externally by the user)?

This is similar to a recent change done in CEF:
see [here](https://bitbucket.org/chromiumembedded/cef/pull-requests/158/support-external-textures-in-osr-mode/diff) for the PR, and [here](https://bitbucket.org/chromiumembedded/cef/issues/1006/cef3-support-rendering-to-a-hardware-gl) for the long discussion.

Thanks!

**Comment by codebytere** [comment]
Given that that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR.

**Comment by luan007** [comment]
Allowing OSR with zero-copy texture sharing would be open up at least two possibilities:

1) To be used in Audio Visual industries & broadcasting industries: i.e sharing texture / mixing textures with external capturers at 60fps & higher, plays nice with tech like syphon / spout / NDI.. Allowing electron to be 'projection mapped' onto buildings.. or to be used in-par with tools like unreal, to provide better UI / UX for live compositions.. 
**Similar CEF use cases can be seen in VVVV & so on**
**Devs might even use this as a realtime graphics tool for after effect / blender to consume**

_https://github.com/daktronics/cef-mixer_
_http://www.thegrego.com/2016/05/16/webgl-in-cinder/_

2) To be used to implement complex 3D apps & professional VR applications, feeding rendered texture **back** as webgl texture for another window to consume. This opens up DOM -> VR overlay potential (discussed a lot in VR field & no standing standard to solve this for now, developers have to either use DOM as plain-overlays or draw everything in canvas2d & use as textures, introducing immense complexity for UI heavy apps like BIM & so on)

@ronhab Is there any chance we can start working on this?
@codebytere or may I ask if it is possible to provide a starting point for us to somehow start trying?

For realistic usage, feeding back into other-window within same electron app should be straight forward, 
i.e exchanging handles with ipc

In main process
```javascript
let hndl = offscreenBrowser.getTextureHandle();  //hndl works like nativeImage
```

In other render process
```javascript
//hndl is sent via ipc
let texture = channel.getTextureFromHandle(hndl);
texture.asImg(); 
```


_ref: https://magpcss.org/ceforum/viewtopic.php?f=6&t=14026_

**Comment by benoitlahoz** [comment]
Any news on this one?

**Comment by cnSchwarzer** [comment]
It is hard, because all electron views are rendered by CPU (like popups) when offscreen mode is on.
However if we are ok with render without popup and proxyviews, it is possible to copy the texture directly.

**Comment by nrkramer** [comment]
If anyone has any interest in opening a PR to address this, the rendering library used to manage the GPU buffer is [Skia](https://api.skia.org/), and a good place to start would be here: https://github.com/electron/electron/blob/6697042c0ab61ac55e91251427a131792de0358e/shell/browser/osr/osr_render_widget_host_view.cc#L683

**Comment by patacoding** [comment]
any news here?

**Comment by cnSchwarzer** [comment]
> any news here?

Yes, Indeed.

In fact I just finished the feature at CEF side few hours ago, see:

https://chromium-review.googlesource.com/c/chromium/src/+/5265077

https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=19404&start=20

https://bitbucket.org/chromiumembedded/cef/pull-requests/285/reimplement-shared-texture-support-for-viz

**Comment by cnSchwarzer** [comment]
Good news: All the patches are merged in M124(6367), so implementing it on electron should be easy.

**Comment by reitowo** [comment]
Started working on this. See https://github.com/electron/electron/issues/41972
