### ISSUE TITLE
Electron on Windows and wmic.exe

### ISSUE THREAD

**Issue by snene** [electron/electron#16979]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 1.7.9
* **Operating System** (Platform and Version):
  * Windows
* **Last known working Electron version** (if applicable):
  * 

Please help!!!

Why does Electron based Windows app, while launching, launch any executable named wmic if found in the same folder?

And how can I prevent it from happening?

Requesting urgent help!

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
