### ISSUE TITLE
Regression with native modules in 4.0.4

### ISSUE THREAD

**Issue by Jakst** [electron/electron#16996]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * v4.0.4
* **Operating System** (Platform and Version):
  * macOS 10.14.3
* **Last known working Electron version** (if applicable):
  * v4.0.3

### Expected Behavior
I do not know the underlying mechanisms that trigger this error, but I have a project in which I bundle all of `yarn.js` in order to install projects from within my Electron app.

In Electron v4.0.4, this no longer works for some native modules in node_modules, as their executables get left out.

### Actual behavior
The native executables should be included in node_modules just like when running `yarn install` from command line.

### To Reproduce
Clone this minimal reproduction repo: https://github.com/Jakst/electron-4.0.4-regression

To reproduce, do the following:
# Reproduction steps

```bash
# Go to "electron-4.0.3" folder
cd electron-4.0.3

# Install packages
yarn install

# Start project
yarn start

# Go to "electron-4.0.4" folder
cd ../electron-4.0.4

# Install packages
yarn install

# Start project
yarn start
```

**Observe that the expected and actual output match in electron 4.0.3 and differ in electron 4.0.4!**

**Comment by Jakst** [comment]
I can also not that the bug is still present in Electron 5.0.0-beta.3

**Comment by MarshallOfSound** [comment]
This is kind of expected, `sharp` uses some form of prebuilt native modules, they don't have any prebuilts for Electron 4.0.4's ABI number.  (Which is `69`)

https://github.com/lovell/sharp/releases

The ABI number changed from `4.0.3` to `4.0.4` as it was incorrect to begin with.  Sharp need to run a new release and generate new prebuilt for Electron `4.0.4` / `5.0.0`
