### ISSUE TITLE
Windows 10: appendSwitch 'use-winrt-midi-api' not working 

### ISSUE THREAD

**Issue by AndrejHronco** [electron/electron#16999]
* **Electron Version** :
4.0.4
* **Operating System** :
Windows 10 (1803)

### Expected Behavior
This flag allows the use of the Windows 10 RTMIDI API which allows multiple pieces of software to connect to a MIDI controller ( a feature available on macOS / very common but new to Windows 10). setting this flag to 'enabled' should allow an Electron app and another piece of software using Win RTMIDI to access a MIDI controller. Use Case: using a software synth and a Digital Audio Workstation simultaneously. 

### Actual behavior
setting this flag doesn't allow MIDI controller access via more than one piece of software

### To Reproduce
create a simple WebMIDI Electron app which listens for MIDI messages and log the messages to the console. open another MIDI capable program and try and access the MIDI device while the Electron app is active. Setting the 'use-winrt-midi-api' to 'enabled' should allow this.
```javascript
app.commandLine.appendSwitch('use-winrt-midi-api', 'enabled')
// also tried
app.commandLine.appendSwitch('--use-winrt-midi-api', 'enabled')
```

**Comment by nornagon** [comment]
Thanks for the report! It would be super helpful to have a small reproduction based on [electron-quick-start](https://github.com/electron/electron-quick-start).

**Comment by AndrejHronco** [comment]
This will be a bit complex to reproduce since it involves hardware. But can be reproduced with help from the browser. 
On a Windows 10 machine using Chrome:
1. connect your midi controller and visit this site: http://outputchannel.com/midi-logger/
2. play some notes and look at the Model of the controller you're using
3. go to chrome://flags and search 'midi', then enable winrt-midi, restart chrome
4. repeat steps 1-2 and take note of the Model of controller which should be using WinRT MIDI compatible names.

This depends on if your controller has multiple ports or not, but regardless, there should be a naming difference between the two OS MIDI APIs

I'll build out an Electron app to demonstrate this and log midi device names the console

**Comment by AndrejHronco** [comment]
Closing this issue since it's not a bug (Electron never supported this feature) and hoping to get this issue re-opened (add feature request):
https://github.com/electron/electron/issues/17060

**Comment by marcelblum** [comment]
Wondering what is the last/latest word on this matter 3 years later. Does anyone know if this flag is working in any more recent Electron version?
