### ISSUE TITLE
[KDE Plasma] tray can't actually destroy

### ISSUE THREAD

**Issue by rocka** [electron/electron#17000]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 3.1.3 and 4.0.4
* **Operating System** (Platform and Version):
  * Arch Linux 4.20.8-arch1-1-ARCH x86_64, KDE Plasma 5.15.0
* **Last known working Electron version** (if applicable):
  * unknown

### Expected Behavior

when a Tray is destroyed, it may disappear in notification area.

### Actual behavior

when a Tray is distroyed, it's hidden from the system tray but still visible in "hidden icons" area

### To Reproduce

- KDE Plasma 5.15.0

```console
git clone https://github.com/electron/electron-api-demos
npm install
npm start
```

- navigate to NATIVE USER INTERFACE -> Put your app int the __tray__

- click <kbd>View Demo</kbd> several times
 
### Screenshots

![image](https://user-images.githubusercontent.com/13914967/52895218-268afb80-31f2-11e9-90a3-ed6fd81cda83.png)

### Additional Information

this only happends when `libappindicator` is avaliable; it works fine when use `GtkStatusIcon` for tray impl.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by rocka** [comment]
This bug is still present on Electron@7.x, same behavior, same reproduce steps.

As of Electron@8, because appindicator was broken, this issue was gone. Not fixed, but gone. See #22207

**Comment by fds2610** [comment]
Same with Electron@6.x.x in Windows 10. tray.destroy just does not remove icon.

**Comment by rocka** [comment]
Since #23926 , this issue comes back again, on electron 9.0.3

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
