### ISSUE TITLE
event.sender async send multiple-exercise

### ISSUE THREAD

**Issue by githubyong** [electron/electron#17018]
it seems that event.sender.send() will exec multiple times as sender called.
```
// In main process.
const { ipcMain } = require('electron')
ipcMain.on('asynchronous-message', (event, arg) => {
  console.log(arg) // prints "ping"
  event.sender.send('asynchronous-reply', 'pong')
})
``` 

```
// In renderer process (web page).
const {ipcRenderer} = require('electron')
ipcRenderer.on('asynchronous-reply', (event, arg) => {
  console.log(arg) // prints "pong"
})
```
it will log 4 times at newSchedule  4th called,and 5 times at 5th called.
it seems previous events were stored at somewere and triggered again. 

electron version:4.0.1
os:windows 7

**Comment by effsoft** [comment]
any update?

**Comment by harryi3t** [comment]
@githubyong @effsoft 
Hey, I tried to reproduce this using "Electron Fiddle" on windows 10 but wasn't able to. Is this only happening on win 7? 
Also, your code doesn't include the part where renderer is sending the message to the main process.
Could you share the complete code to reproduce this or even better if you could share the gist file from Electron FIddle?

**Comment by tookbra** [comment]
This happens when I enter the page and quit and come in again.

**Comment by githubyong** [comment]
i tried pure electron without any integration,it works well. it seems it is not electron's bug.

**Comment by EdmarPereira** [comment]
Same problem here, I am using ipcRenderer to identify when an user click on menu event inside react and it is triggering more than one time.

**Comment by kongfanhe** [comment]
In my case,  change "ipcRenderer.on" to "ipcRenderer.once" solve the problem. "ipcRenderer.on" will create a listener and you have to clean it yourself

**Comment by lishenglll** [comment]
> 就我而言，将“ipcRenderer.on”更改为“ipcRenderer.once”即可解决问题。“ipcRenderer.on”将创建一个监听器，你必须自己清理它

good bro
