### ISSUE TITLE
crypto.scryptSync is not a function

### ISSUE THREAD

**Issue by Custardcs** [electron/electron#17015]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
V3.0.13
* **Operating System** (Platform and Version):
Windows 10
* **Last known working Electron version** (if applicable):
N/A

### Expected Behavior
should be able to use the function like in regular node.

### Actual behavior

I load up the app as soon as i request the function it crashes with the error
`crypto.scryptSync is not a function`
### To Reproduce
//crypt
const Node_Crypto = require('crypto');

function Encrypt_AES(data, pubkey) {

    const algorithm = 'aes-192-cbc';
    const key = Node_Crypto.scryptSync(pubkey, 'salt', 24);
    const iv = Buffer.alloc(16, 0); // Initialization vector.
    const cipher = Node_Crypto.createCipheriv(algorithm, key, iv);
    let encrypted = cipher.update(JSON.stringify(data), 'utf8', 'hex');
    encrypted += cipher.final('hex');
    return encrypted;

}

### Screenshots

![capture](https://user-images.githubusercontent.com/14811199/52920493-b1184b80-3315-11e9-838d-b3c6f07671a2.PNG)

**Comment by Custardcs** [comment]
Think i found the problem I was being a retard and didnt update my electron. Sorry Im working on so many projects thought I was on v4.

**Comment by zanethomas** [comment]
I'm confused. Looks to me as if electron is using node 8.something which does not include crypto.scrypt, which I *really* wish it did!

**Comment by nornagon** [comment]
`crypto.scryptSync` [was added in node 10.5.0](https://nodejs.org/api/crypto.html#crypto_crypto_scryptsync_password_salt_keylen_options). Electron 4 is the first version to include a node version with this function.
