### ISSUE TITLE
[Feature Request] Add ability to change hardware acceleration without a restart 

### ISSUE THREAD

**Issue by whitecrownclown** [electron/electron#17011]
**Is your feature request related to a problem? Please describe.**
In [Caprine](https://github.com/sindresorhus/caprine) we'd like to be able to disable hardware acceleration when `on-battery`, however we cannot do that without requiring the user to restart which leads to losing app state (user typing a message, etc).

**Describe the solution you'd like**
Implement possibility to change hardware acceleration without requiring app restart

**Additional context**
Related https://github.com/sindresorhus/caprine/issues/625

**Comment by nornagon** [comment]
Unfortunately I don't believe this is possible, due to Chromium's architecture. It _might_ be possible to do it with a renderer restart only, keeping the main process alive, but that wouldn't preserve e.g. a message being typed.

**Comment by codebytere** [comment]
Closing resultant of above comment.
