### ISSUE TITLE
apply setAspectRatio on Window os

### ISSUE THREAD

**Issue by MadfishDT** [electron/electron#17020]
**Is your feature request related to a problem? Please describe.**
setAspectRatio function not support on Windows OS.

**Describe the solution you'd like**
on Window OS, Window os native API not support Window Aspect ratio control differenct from MAC OS.
but I tried to make Width/Height ratio operation with WM_SIZE event handler. it was works.

I succeeded stay width - height ratio with aspect_ratio valuable in NativeWindowViews

**Describe alternatives you've considered**
None

**Additional context**

**Comment by MadfishDT** [comment]
https://github.com/electron/electron/pull/17245

**Comment by MadfishDT** [comment]
https://github.com/electron/electron/pull/18306

**Comment by ckerr** [comment]
Duplicate of https://github.com/electron/electron/issues/8036, fixed by #26941
