### ISSUE TITLE
CHECK failure cookies API

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#17037]
In the Electron 5 branch and master we have a CHECK failure in the cookies API

> `[401:0218/145432.207065:FATAL:ref_counted.h(63)] Check failed: CalledOnValidSequence(). `

Example: https://circleci.com/gh/electron/electron/138174

It doesn't happen 100% of the time, but shouldn't be too hard to repro on a Linux machine.  (Unsure if it fails on other OS's, haven't seen it personally but may have happened)

**Comment by nornagon** [comment]
related: https://github.com/electron/electron/pull/16788
