### ISSUE TITLE
Windows 10 - BrowserWindow setSize( ) working incorrectly in dual-display setup with different scaling

### ISSUE THREAD

**Issue by jffrn** [electron/electron#17033]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 4.0.5
* **Operating System** (Platform and Version):
  * Windows 10 Pro (1803)

Dual monitor setup, where main monitor (center) is 1920x1080 and scaled at 100% and other monitor (left) is 1920x1200 and scaled at 125%. Electron app tries to make window wider. If window is on main monitor, it works as expected. If window is on left monitor, the window not only gets wider but also taller. The issue does not happen if the left monitor is scaled down to 100%.

### Expected Behavior
Upon calling `window.setSize()`, window gets resized correctly in all monitors.
### Actual behavior
When window is sitting on top of monitor with 125% scaling, window gets resized incorrectly.
### To Reproduce
Create directory with following 3 files, then run `electron .` from command line:

1. package.json:
```javascript
{
  "name"    : "electron-bug",
  "version" : "0.1",
  "main"    : "main.js"
}
```
2. main.js:
```javascript
'use strict';

const electron = require('electron')
const app = electron.app
const BrowserWindow = electron.BrowserWindow
const ipcMain = electron.ipcMain
let win

app.on('ready', () => {
    win = new BrowserWindow({width: 500, height: 500, backgroundColor: '#fff'})
    win.loadURL(`file://${__dirname}/index.html`)
})
app.on('window-all-closed', () => {
    app.quit()
})
ipcMain.on('makeScreenWider', function() {
    console.log("NodeJS - Making screen wider")
    let currentSize = win.getSize()
    win.setSize(currentSize[0] + 5, currentSize[1])
})
```
3. index.html:
```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
</head>
<body>

<div style="padding: 20px">
    <button onclick="makeScreenWider()">Make screen wider by 5px</button>
</div>

<script>
    const electron = require('electron')
    const ipcRenderer = electron.ipcRenderer
    function makeScreenWider() {
        ipcRenderer.send("makeScreenWider")
    }
</script>

</body>
</html>
```

### Screenshots
What it looks like:
- Main monitor with 100% scale
![electron1](https://user-images.githubusercontent.com/6676638/52978056-672f7400-33ae-11e9-851e-2850c4f2b0b9.gif)
- Left monitor with 125% scale
![electron2](https://user-images.githubusercontent.com/6676638/52978057-672f7400-33ae-11e9-9e33-ea6e14c3d9e2.gif)

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by xpirt** [comment]
This issue is still present on latest version.

**Comment by ajsong** [comment]
This issue is still present on Electron 10.1.2 version.
