### ISSUE TITLE
Maximizing Electron apps cut-off bottom part on secondary monitor

### ISSUE THREAD

**Issue by joshsweaney** [electron/electron#17036]
* **Operating System** Windows 10 Enterprise (1709)

I'm assuming this is an Electron problem since two Electron apps at the latest versions are experiencing the same problem. See the screenshots below to quickly understand the issue. Essentially when maximizing a window on a secondary monitor, a part at the bottom of the window will be cut off and glitched.

This is happening on both Atom v1.34 and VSCode v1.31.1.

### Expected Behavior
The window fills the entire screen (minus the task bar)

### Actual behavior
A variable portion of the bottom half of the window is a mix of solid colors.

### To Reproduce
Open a window of an electron app, put it on a secondary monitor, and then maximise it.

### Screenshots
https://imgur.com/a/zhcLZ9X

**Comment by codebytere** [comment]
@joshsweaney we unfortunately can't proceed with this unless it's provably an Electron issue with a repro that's not application dependent. In this event, we ask that you open and issue upstream, and if more information arises we can take a look. Thank you!
