### ISSUE TITLE
Icon doesn't show up on Linux when package.json name contains an underscore

### ISSUE THREAD

**Issue by QuentinJanuel** [electron/electron#17035]
* **Electron Version**
4.0.1
* **Operating System**
Ubuntu 18.04.1 LTS x64

### Expected Behavior
See the app icon

### Actual behavior
No icon at all

### To Reproduce
As far as I can tell, the icon doesn't show up on Linux when your package.json name contains underscores. I managed to isolate this and just removed the underscores from my name but this doesn't feel right so I'm reporting it.

**Comment by QuentinJanuel** [comment]
Ok so I can't seem to have a process to reproduce it.
Weirdly enough, I have a (heavy) electron project that doesn't show the icon until I remove all the underscores in the package.json name. I can toggle the icon by just changing this name. But I've restarted an empty electron project to do experiments and I now always have the icon. I am comparing the two projects and I have no idea what I am missing.
Probably it is due to having underscores + something else still unknown. But since the glitchy project is huge I'm having a hard time isolating the error :/

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
