### ISSUE TITLE
[Bug] Linux Flash Plugin not loading

### ISSUE THREAD

**Issue by GhostlyDark** [electron/electron#17034]
* **Electron Version**: 
  * v5.0.x
* **Operating System** 
  * Linux (Ubuntu 18.10 x64)
* **Last known working Electron version**: 
  * v4.0.x

### Expected Behavior
Flash Plugin should load.

### Actual behavior
Flash Plugin does not load.

### Additional info
The Flash Player under Linux never worked in a mixed-sandbox or (full-)sandbox environment. As of v5.0.x, mixed-sandbox is forced. This prevents the plugin from loading.

### To Reproduce
[app.zip](https://github.com/electron/electron/files/2877526/app.zip)

**Comment by nornagon** [comment]
We should find an option that allows us to run Flash sandboxed. As an immediately applicable workaround, you can disable the sandbox with `--no-sandbox`.

**Comment by GhostlyDark** [comment]
Is there any workaround to disable the sandbox for production? Otherwise v5.0.x will be useless for anybody relying on the plugin, unless the issue is fixed by the time v5.0.x is declared as stable.

**Comment by nornagon** [comment]
You should be able to disable the sandbox in your packaged app with `app.commandLine.appendSwitch('no-sandbox')`.

**Comment by GhostlyDark** [comment]
Bad news. The appendSwitch method does work on Windows, but does not work with my Ubuntu installation. Disabling the sandbox via the command line works on both systems.

**Comment by nornagon** [comment]
ah... it must be because of the zygote pre-warming on linux. ok, we'll make sure to figure out a solution for stable.

**Comment by GhostlyDark** [comment]
I know this is a bit late but this issue wasn't truly fixed. While the sandbox can be deactivated on Linux to get the Flash Player working (thx for fixing this workaround btw), using the sandbox will still prevent the plugin from loading.
Using v6.1.x to test as v7 and above currently suffer from not being able to load the plugin at all.
