### ISSUE TITLE
DOMException: Could not start audio source on new soundcard

### ISSUE THREAD

**Issue by PurpleHorrorRus** [electron/electron#17045]
Hey. Not so long ago I bought a new sound card and after that Electron does not hear sounds from it through desktopCapturer. Throws a DOMException error: failed to start audio source.  What am I to do?

Electron version: 4.0.4
Sound card: ASUS Xonar DG (UniXonar drivers)

Code:
```javascript
desktopCapturer.getSources({types: ["window", "screen"]}, (error, sources) => {
    window.AudioContext = window.AudioContext || window.webkitAudioContext;
    navigator.mediaDevices.getUserMedia({
	audio: { mandatory: { chromeMediaSource: "desktop" } },
	video: { mandatory: { chromeMediaSource: "desktop" } }
   }).then((stream) => {
	audioContext = new AudioContext();
	so = audioContext.createMediaStreamSource(stream);
	analyser = audioContext.createAnalyser();
	so.connect(analyser);
	fbc_array = new Uint8Array(analyser.frequencyBinCount);
	clearInterval(interval);
	interval = setInterval(() => { console.log(true); io.emit("bit", { array: fbc_array, freqData: analyser.getByteFrequencyData(fbc_array) }); }, 1000 / 60); 
   }).catch((e) => console.log(e))
});
```

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
