### ISSUE TITLE
require from devtools can't find installed modules if electron started from specific folder

### ISSUE THREAD

**Issue by 3axap4eHko** [electron/electron#17040]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
v4.0.5
* **Operating System** (Platform and Version):
Windows 10 (1803)

### Expected Behavior
1. Install any module from npm ( example: `yarn add progress` )
2. Start electron app from specific folder `electron build`
3. Open Dev Tools
4. Execute `const progress = require('progress');`
5. You can use module `progress`

### Actual behavior
1. Install any module from npm ( example: `yarn add progress` )
2. Start electron app from specific folder `electron build`
3. Open Dev Tools
4. Execute `const progress = require('progress');`
5. module `progress` not found

### Additional Information
property `module.paths` does not contain the path to the project root `node_modules` folder. It has only:
``` js
'node_modules\electron\dist\resources\default_app.asar\node_modules',
`node_modules\electron\dist\resources\node_modules`
```
BTW project modules can't be found.

And it works fine with starting from the root `electron .`

**Comment by MarshallOfSound** [comment]
@3axap4eHko This is expected behavior, when you run `electron` targeting a directory we won't load a module from above that directory.  Your directory needs to have a `package.json` for it to be detected as an app correctly, hence why it works with `electron .`.

This issue will also never occur in a packaged state

**Comment by 3axap4eHko** [comment]
@MarshallOfSound that is not a directory above, that is the exact `current directory`. And what is the solution for projects with following structure if you need to run `build`
```sh
/build/index.js
/build/index.html
/node_modules/
/src/index.js
/src/index.html
package.json
```
