### ISSUE TITLE
Electron build output size 

### ISSUE THREAD

**Issue by sebakerckhof** [electron/electron#17051]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 4.0.5
* **Operating System** (Platform and Version):
  * Ubuntu 18.04.2 x64 

### Expected Behavior
I'm trying to build electron from source for Linux x64
When I follow the instructions from: https://electronjs.org/docs/development/build-instructions-gn

I would expect the output to be the same like the releases downloaded by electron-download or available here on github.

### Actual behavior
When I build electron 4.0.5 the electron binary turns out to be about 299.9 MB (Debug build, with all .so files counting up to 4GB). And 2.7GB for a Release build.

The 4.0.5 electron binary in the electron releases available on here is only 114.9 MB.

I don't know how to explain the massive difference in size and I assume the build instructions might be incomplete.

### To Reproduce
I just followed https://electronjs.org/docs/development/build-instructions-gn on Ubuntu 18.04.2 x64 for the 4-0-x branch of electron.

**Comment by nornagon** [comment]
How are you measuring the size of the Release build? `df out/Release` will count all the intermediate objects (`.o` files, generated sources, etc.) as well as the final product. The official release builds are generated with `ninja electron:electron_dist_zip`.

**Comment by sebakerckhof** [comment]
Just the size of the `electron` file in the `out/Release` directory.
The `ninja electron:electron_dist_zip` even fails for me because of it, since I get:
```
Traceback (most recent call last):
  File "../../electron/build/zip.py", line 67, in <module>
    sys.exit(main(sys.argv[1:]))
  File "../../electron/build/zip.py", line 64, in main
    z.write(dep)
  File "/usr/lib/python2.7/zipfile.py", line 1148, in write
    self._writecheck(zinfo)
  File "/usr/lib/python2.7/zipfile.py", line 1114, in _writecheck
    " would require ZIP64 extensions")
zipfile.LargeZipFile: Filesize would require ZIP64 extensions
ninja: build stopped: subcommand failed.
```

**Comment by rhys101** [comment]
It seems the Release build doesn't strip the electron binary for you. 
If you run `strip out/Release/electron` after the Release build, the binary will go from 2.7GB to 111MB allowing  `ninja -C out/Release electron_dist_zip` to run as expected.

**Comment by sebakerckhof** [comment]
@rhys101 thanks, it indeed looks like I need to call strip manually on the electron binary (and also the other shared object files).

Now that leaves the question whether this should have happened automatically when running `ninja electron:electron_dist_zip`. I just tested on a clean debian stretch system and it had the same behavior.
So is there another ninja command I need to run to get the stripped output?

**Comment by nornagon** [comment]
Ah, yeah it looks like our CI runs the strip step first: https://github.com/electron/electron/blob/83894dc5db46cdb9002fba7a6ab723ea939cebe1/.circleci/config.yml#L242-L249

The reason this isn't done automatically by the build is that GN doesn't like tools that modify files in-place, which `strip` does. There are ways around it but they're somewhat complicated and this was the simplest solution we came up with at the time, and it's similar to what Chrome does.
