### ISSUE TITLE
Error using stream protocol in webview:  this.listenerCount is not a function

### ISSUE THREAD

**Issue by mjbvz** [electron/electron#17059]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 4.0.4
* **Operating System** (Platform and Version):
  *  macOS 10.14.2
* **Last known working Electron version** (if applicable):
  * None

### Expected Behavior
In a webview that uses its own partition and registers a custom stream protocol in that partition, we should be able to use the protocol as expected. This works with buffer protocols:

```js
// in renderer

const webview = document.createElement('webview');
webview.setAttribute('partition', `webview${Date.now()}`);

webview.addEventListener('did-start-loading', () => {
    // register protocol in webview
    const contents = webview.getWebContents();
    contents.session.protocol.registerStreamProtocol('atom', (request, callback) => {
        http.get({ hostname: 'example.com', }, res => {
            callback({
                statusCode: 200,
                headers: {
                    'content-type': 'text/html'
                },
                data: res
            })
        })
    }, (error) => {
        if (error) console.error('Failed to register protocol')
    });
});

webview.src = `data:text/html;charset=utf-8;base64,${Buffer.from(`<!DOCTYPE html>
<html lang="en" style="width: 100%; height: 100%">
<head>
	<title>Virtual Document</title>
</head>
<body style="margin: 0; overflow: hidden; width: 100%; height: 100%">
    <iframe src="atom://bla"></iframe>
</body>
</html>`).toString('base64')}`

document.body.append(webview);
```

This works as expected if the protocol is registered in the main process and an iframe is created in the renderer process

### Actual behavior
This does not work. In the main developer console, see:

```
Uncaught TypeError: this.listenerCount is not a function
    at Readable.on (_stream_readable.js:805)
    at CallbacksRegistry.apply (/Users/matb/Library/Application Support/Electron Fiddle/electron-bin/4.0.5/Electron.app/Contents/Resources/electron.asar/renderer/callbacks-registry.js:47)
    at handleMessage (/Users/matb/Library/Application Support/Electron Fiddle/electron-bin/4.0.5/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:285)
    at EventEmitter.ipcRenderer.on.args (/Users/matb/Library/Application Support/Electron Fiddle/electron-bin/4.0.5/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:275)
    at EventEmitter.emit (events.js:182)
```

### To Reproduce
1. Run code from this electron fiddle https://gist.github.com/e1c5afa22b62b2c5c8267f188a74719a Main logic is in `renderer.js`
1. Open developer tools console to see error.

/cc @bpasero

**Comment by ianho** [comment]
Any fix plan for this issue？

**Comment by ianho** [comment]
Any plan to fix this issue？

**Comment by ianho** [comment]
Any plan to fix this issue?
I think this is about remoting (ipc) with stream is not handled well.
I have tried to fix the CallbacksRegistry.add and CallbacksRegistry.apply with correct this context. But it just fix the error "this.listenerCount is not a function", the stream still wasn't returned to the client.
Maybe the function remote.ts/wrapArgs should handle stream type？

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by mjbvz** [comment]
Confirmed with Electron 8.0.0

However the error is now:

```
Uncaught TypeError: Cannot read property 'endEmitted' of undefined
    at Readable.on (_stream_readable.js:879)
    at CallbacksRegistry.apply (callbacks-registry.ts:45)
    at remote.js:292
    at EventEmitter.<anonymous> (remote.js:272)
    at EventEmitter.emit (events.js:210)
    at Object.onMessage (init.ts:50)
```

**Comment by aabuelenin** [comment]
I've the same issue, @mjbvz have you'd any luck finding a workaround?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by deepak1556** [comment]
Remote module is deprecated in latest stable, the issue doesn't repro when loaded from main process.
