### ISSUE TITLE
[mac] The `close` MenuItem role is incorrect when tabbingIdentifier is present

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#17064]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 5.0.0-beta.3 and 4.0.5
* **Operating System** (Platform and Version):
  * macOS 10.14.3
* **Last known working Electron version** (if applicable):
  * None

### Expected Behavior

I expected the label for `{role: 'close'}` to be `Close   ⌘W` by default and `Close Window   ⌘W` if the active window has native tabs enabled (Meaning `tabbingIdentifier` set in BrowserWindow).

You can confirm this behavior in system apps. Notes.app has no tabs and it's `Close`, while Maps.app has tabs and it's `Close Window`.

### Actual behavior

The label is always `Close Window   ⌘W`.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sindresorhus** [comment]
I've confirmed it's still an issue with Electron 8.0.1

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by nornagon** [comment]
I can't reproduce this.

![image](https://user-images.githubusercontent.com/172800/157536982-d2d1c72e-d9c4-4455-bf2e-b98638aa0ee5.png)

Fiddle: https://gist.github.com/448aa5500f0db69f0241ebcbf76e53f9

**Comment by nornagon** [comment]
Since this issue is stale and doesn't appear to be reproducible in current versions of Electron, I'm going to close it out. If I've misunderstood the issue I'm happy to reopen.
