### ISSUE TITLE
Add Support of Windows 10 + 'WinRT MIDI API' via commandLine.appendSwitch

### ISSUE THREAD

**Issue by AndrejHronco** [electron/electron#17060]
**Is your feature request related to a problem? Please describe.**
Prior to Windows 10, it wasn't possible to use more than one piece of software simultaneously  connected to a MIDI device, for example a DAW and a MIDI device editor program. Windows 10 has a new MIDI API that developers can use which allows multiple pieces of software to simultaneously connect to a MIDI device, macOS has always allowed this...The only snag in this new Windows API is that all software needs to be using the new API for it to work, so both DAW and Editor need to use it.
This can be enabled in a browser, which supports the Web MIDI API, via chrome:flags

**Describe the solution you'd like**
Since this has been supported in Chrome for a few years now, it would be great to add support for this flag as well in Electron.

**Describe alternatives you've considered**
There doesn't appear to be an alternative solution using Electron

**Additional context**
The flag is: `use-winrt-midi-api`
set to enabled:
`app.commandLine.appendSwitch('use-winrt-midi-api', 'enabled')`

**Comment by MarshallOfSound** [comment]
This is a duplicate of your own issue #16999

**Comment by AndrejHronco** [comment]
Apologies for that.
I think this is more of a feature request vs. a bug report since I don't think Electron ever supported this flag. Would you re-open if I close the original issue out?
Thank You

**Comment by dopry** [comment]
@MarshallOfSound both of the issues related to 'use-winrt-midi-api' were closed, can you re-open this feature request.  It's an issue we encountered today in our product that is causing problems for our users. We need to enable the winrt midi apis to resolve them.

**Comment by lozjackson** [comment]
+1 please reopen this, this would be really useful

**Comment by dopry** [comment]
@ckerr anyone around who could re-open this?

**Comment by dopry** [comment]
This is still something that would be useful...  Is there a reason both related issues are closed?  This won't be the[ default in Chromium for at least another year](https://issues.chromium.org/issues/361126126). I develop an electron app that uses midi and we really need this to avoid winMM taking exclusive control of midi devices on windows.

**Comment by dopry** [comment]
re opened in https://github.com/electron/electron/issues/17073
