### ISSUE TITLE
Set url after window.open does not works with nativeWindowOpen in isolated context

### ISSUE THREAD

**Issue by hugomano** [electron/electron#17069]
* **Electron Version**:
4.0.4
* **Operating System**:
macOS 10.14.3
* **Last known working Electron version**:
3.1.4

### Expected Behavior

Setting an URL for the opened window in an isolated world context with `nativeWindowOpen` flag should trigger navigation to the given URL like in the top context.

<img width="559" alt="screenshot 2019-02-20 at 16 13 52" src="https://user-images.githubusercontent.com/823630/53101753-abe01a00-352a-11e9-91aa-cc49cdb87dfb.png">

### Actual behavior

Setting the URL trigger a type error.

<img width="548" alt="screenshot 2019-02-20 at 16 14 37" src="https://user-images.githubusercontent.com/823630/53101768-b0a4ce00-352a-11e9-8093-6a64f02eb940.png">

### To Reproduce

```sh
$ git clone https://github.com/getstation/electron-chrome-extension
$ npm install
$ npm start
```

Webview dev tool console in top context
```js
const newWin = window.open('')
newWin.location = 'https://google.com' // it works
```

Webview dev tool console in extension context
```js
const newWin = window.open('')
newWin.location = 'https://google.com' // it does not works
```

**Comment by nitsakh** [comment]
Can you please provide a minimal electron example? Preferable a fiddle which shows the issue.
The repo mentioned in the issue does bunch of other things also, which makes it hard to track.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and provide us with repro steps with [electron-quick-start](https://github.com/electron/electron-quick-start).

I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
