### ISSUE TITLE
webContents.print() not print as per the default printer settings when putting device name 

### ISSUE THREAD

**Issue by shabeer-mdy** [electron/electron#17077]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * v4.0.5
* **Operating System** (Platform and Version):
  *  Windows 10 

### Expected Behavior
using  webContents api to print an html file oriention  set to landscape in default printer settings and page size set to A5, 

mainWindow.webContents.print({ silent: true, printBackground: false, deviceName: 'HP LaserJet 1020' })

My issue is : it is not printing as defined in the default printer settings

but it currently printing is deviceName not set

and need to send mainWindow.webContents.print() api to silently and printer name 

### To Reproduce
If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone git@github.com:shabeer-mdy/electron-quick-start.git
$ npm install
$ npm start || electron .
```
and set any printer name to  mainWindow.webContents.print({ silent: true, printBackground: false, deviceName: 'HP LaserJet 1020' })

set any installed printer name

**Comment by rhys101** [comment]
It looks like it's related to https://github.com/electron/electron/issues/16792. The arguments aren't being passed through correctly inside webContents.print -  here's the pull request that should fix it: https://github.com/electron/electron/pull/17052

**Comment by popod** [comment]
@shabeer-mdy is your issue resolved by #17052 (electron 4.0.7) ? If yes, please close this issue ;)

**Comment by shabeer-mdy** [comment]
#17052 it is not working as I expected, printer option set silent is true it is not called the printer

**Comment by shabeer-mdy** [comment]
#17052 wouldn't solve my problem, In printer options when changing silent set to true then it's not calling any printer and silent is set to false then the print popup is getting. also same issue in device name property
