### ISSUE TITLE
Electron running on SLES 12, cannot display Japanese, Korean, Simplified Chinese and Traditional Chinese correctly.

### ISSUE THREAD

**Issue by skelly2015** [electron/electron#17079]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * Electron 4.0.0 linux x64 version
* **Operating System** (Platform and Version):
  * SLES 12 (tried on 12.0 and 12.4)
* **Last known working Electron version** (if applicable):
  * 

### Expected Behavior
It is expected that Electron can display those Characters correctly.

### Actual behavior
Electron cannot display Japanese, Korean, Simplified Chinese and Traditional Chinese Characters correctly.

### To Reproduce
1. Build a simple Electron app.
2. In the index.html, make some text area have Japanese, Korean, Simplified Chinese or Tranditional Chinese with UTF-8.
3. Launch the application on SLES 12.
4. In the main window, those Characters are not displayed correctly. ( displayed as garbled symbols, it looks like encoding and decoding issue )
5. In this OS ( SLES 12 ), open the index.html by Firefox.
6. In Firefox, those Characters can be displayed correctly.
7. Launch the application on SLES 15 or RHEL 7, those Characters are displayed correctly.

So I concluded that the issue only appears on SLES 12 with Electron.

I went through the issues here. Then I noticed that this is a font related issue. Someone suggests to use "monospace" as the font-family but this doesn't work for me.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
