### ISSUE TITLE
Can you guys add a doc that explains which electron version is compatible with which node version

### ISSUE THREAD

**Issue by goel-sunny** [electron/electron#17076]
Hi ,

I am getting this type of error most of time (in case of node native modules rebuild) when i update my electron version and not update my node version so most of time i get error like this

**NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 69**

I saw a lot of same time of version compatibility issues faced by other users . and this issue can be resolved by installing electron version which compatible to installed node version.

so if we have docs that contain the info that which electron version is compatible to the node version so it will be easy for the developer to get ride of this annoying error.

Thanks

**Comment by MarshallOfSound** [comment]
> I saw a lot of same time of version compatibility issues faced by other users . and this issue can be resolved by installing electron version which compatible to installed node version.

This is not 100% correct, Electron is not "compatibilt" with any specific node versions, you need to rebuild native modules for your version of Electron.

Please see our [Using Native Node Modules](https://electronjs.org/docs/tutorial/using-native-node-modules) guide.
