### ISSUE TITLE
fatal error: node_version.h: No such file or directory with Electron v4

### ISSUE THREAD

**Issue by anoadragon453** [electron/electron#17072]
* **Electron Version**
  * 4.0.4
* **Operating System** (Platform and Version):
  * Debian Linux testing
* **Last known working Electron version** (if applicable):
  * 3.x.x

### Description

Hello there. I'm trying to build a native node module within an electron project and am unable to do so using Electron v4.x.x. Building against v3.x.x has been fine, which leads me to believe this is some simple issue with versioning/linking but I and others cannot seem to figure out a solution.

The library I'm trying to build is https://github.com/wilix-team/iohook which has an issue for building on Electron v4: https://github.com/wilix-team/iohook/issues/144

### To Reproduce

Install build dependencies for your platform: https://wilix-team.github.io/iohook/manual-build.html

Build:

```sh
$ git clone https://github.com/anoadragon453/iohook # my electron v4 fork
$ npm install
$ npm run build
$ npm run deploy
```

Notice that one build finishes correctly (Electron v3.0.0) and the second does not (Electron v4.0.4)

The error that is produced is:

```
[ 87%] Building CXX object CMakeFiles/iohook.dir/src/iohook.cc.o
In file included from /home/user/code/iohook/src/iohook.h:3:0,
                 from /home/user/code/iohook/src/iohook.cc:1:
/home/user/code/iohook/node_modules/nan/nan.h:24:26: fatal error: node_version.h: No such file or directory
 #include <node_version.h>
                          ^
compilation terminated.
```

Seems something is up with the nodejs headers that are bundled with Electron? Really out of my depth with this issue but hope somebody here can help.

For reference, [an issue](https://github.com/nodejs/nan/issues/838) was created with the nan team but no resolution was found.

**Comment by nornagon** [comment]
The layout of electron's headers changed in v4 to match node's. node-gyp and latest cmake-js handle this correctly, but if you use a different build system you'll need to update it accordingly.

Closing because there's no action to be taken on Electron's side, this is an upstream issue with mishandling include paths.

**Comment by anoadragon453** [comment]
Hm ok, thanks for the insight. I'll try to see what we can do on our end :)

**Comment by alevchuk** [comment]
> The layout of electron's headers changed in v4 to match node's. node-gyp and latest cmake-js handle this correctly, but if you use a different build system you'll need to update it accordingly.
> 
> Closing because there's no action to be taken on Electron's side, this is an upstream issue with mishandling include paths.

This helps. In my case I had to run: `npm install -g yarn`
