### ISSUE TITLE
Menu Accelerator string display is incompleted

### ISSUE THREAD

**Issue by RandalTeng** [electron/electron#17075]
* **Electron Version** (output of `node_modules/.bin/electron --version`): 2.0.14
* **Operating System** (Platform and Version): macOS 10.14
* **Last known working Electron version** (if applicable): nope

### Expected Behavior
Set a menu item with shortcut, the shortcut string should display in the menu label right completed. But the keyboard trigger is allright. I guess it is just string split's problem.

### Actual behavior
When I set an open devtools menu and assignment a shortcut key of "F12", but the application's menu just display like "Open DevTools -------- F1".

### To Reproduce
Just begin an application and setup a menu.
This is a part of my menu setting code:
``` javascript
const topMenuTemplate = [
    {
      role: 'Help',
      submenu: [
        {
          label: 'Learn More',
          click: () => shell.openExternal('https://github.com')
        }
      ]
    }
]
const lastMenu = topMenuTemplate.pop()
lastMenu.submenu.push({
   label: 'Open DevTools',
   click: () => BrowserWindow.getFocusedWindow().openDevTools(),
   accelerator: 'F12'
})
topMenuTemplate.push(lastMenu)

Menu.setApplicationMenu(Menu.buildFromTemplate(topMenuTemplate))
```

### Screenshots
![image](https://user-images.githubusercontent.com/13815562/53140807-db456400-35c8-11e9-80cb-b79575c195e3.png)

### Additional Information
![image](https://user-images.githubusercontent.com/13815562/53140835-edbf9d80-35c8-11e9-8bdc-d72cd38edc07.png)
![image](https://user-images.githubusercontent.com/13815562/53140860-029c3100-35c9-11e9-986c-03ffbe35e058.png)

**Comment by codebytere** [comment]
@RandalTeng per our [versioning document](https://electronjs.org/docs/tutorial/electron-versioning), Electron v2.x only gets security fixes now. 

As such, in order to have this issue triaged by the maintainers you'll need to update to a more recent version. Please @ me in a follow-up comment once you've done so!

**Comment by RandalTeng** [comment]
@codebytere I'm sorry for it. I have upgrade my electron version to 4.0.5, and the menu shortcut display is completed. Thanks again.

**Comment by MarshallOfSound** [comment]
Closing as per the comment above indicating it's working on a newer Electron release
