### ISSUE TITLE
Spawning PyInstaller binaries on macOS spawns correctly but returns null

### ISSUE THREAD

**Issue by axfelix** [electron/electron#17074]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 1.8.8
* **Operating System** (Platform and Version):
  * macOS 10.14.3

### Expected Behavior
`require('child_process').spawn(script)`  returns a child_process object that has an associated PID and can be killed.

### Actual behavior
If I spawn a PyInstaller-created binary on macOS like

`let pythonChild = require('child_process').spawn(script)`

then pythonChild === null, even though it spawns correctly. This means I can't kill it effectively when the app closes. This works fine on Windows/Linux, and it works fine with regular Python scripts. This also works fine when run from `node -i` on macOS, suggesting it's Electron-related. (see https://github.com/nodejs/node/issues/26117)

### To Reproduce
Build a Python binary with PyInstaller (I can supply mine if you trust it) and try spawning it this way.

**Comment by nornagon** [comment]
We no longer support versions of Electron older than 2.0. Reopen if the issue still occurs on a modern version of Electron.

**Comment by axfelix** [comment]
Just verified it still occurs with 2.0.17.

**Comment by axfelix** [comment]
Is there any way for me to provide resources to prioritize getting this looked at? I have a feeling it's going to be very painful to troubleshoot as it seems specific to PyInstaller, to macOS, and to Electron.

**Comment by nornagon** [comment]
You could post a bounty on BountySource ([e.g.](https://www.bountysource.com/issues/70384098-support-new-nodeintegrationinsubframes-in-webviews)). Or debug it yourself :)

**Comment by axfelix** [comment]
all I can do is isolate it down to Electron since it doesn't occur in vanilla node and I don't know how Electron changes node's upstream pid handling or why it would be different on Mac. I'm not opposed to going the bountysource root, it just seems quite low-level.

**Comment by axfelix** [comment]
Would it help if I can duplicate this on 4.x? I suspect it's still unfixed given the specificity of it.

**Comment by nornagon** [comment]
In general, it's helpful to have a minimal repro case. As is this bug doesn't really have enough information for someone to reproduce the issue. Perhaps you could prepare a repo with a small shell script that shows the bug?

**Comment by axfelix** [comment]
Sure thing!

https://github.com/axfelix/electron-17074

**Comment by axfelix** [comment]
So I've isolated this and it had nothing to with PID handling -- I was accidentally declaring

`let pythonChild = require('child_process').spawn(script)`

after already declaring `let pythonChild = null` earlier in the script. Only macOS had a problem with the redundant variable declaration. Fixed after changing the line to `pythonChild = require('child_process').spawn(script)`.
