### ISSUE TITLE
transparency lost when writing png image to clipboard on Windows

### ISSUE THREAD

**Issue by bartcich** [electron/electron#17081]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 4.0.5
* **Operating System** (Platform and Version):
  * Windows 10 (1809)
* **Last known working Electron version** (if applicable):
  * n/a

### Expected Behavior
Copying and pasting images with transparency to/from other apps should preserve transparency.

### Actual behavior
When copying transparent png image with transparent background - pasting it to other apps (Gimp, PowerPoint) changes transparency to black color. Pasting the same image into electron app preserves transparency.
Similar thing with copying image from Gimp - it preservers transparency when pasting it to other apps, but changes transparency to black color when pasting to electron app

### To Reproduce
https://github.com/bartcich/electron-clipboard-transparent
```
git clone git@github.com:bartcich/electron-clipboard-transparent.git
yarn
yarn start
```
1. Click "Copy to clipboard"
2. Paste image to different app (like Gimp etc)

### Screenshots
Image being copied to clipboard:
![image](https://user-images.githubusercontent.com/3295025/53156502-da5c0480-35bf-11e9-8336-296da8bbf84e.png)

After pasting to Gimp:
![gimp-result](https://user-images.githubusercontent.com/3295025/53156546-efd12e80-35bf-11e9-804e-0c3e87ccffde.png)

### Additional Information
Raw clipboard read shows different formats being copied to to clipboard between gimp and electron app:
Gimp:
![gimp-clip](https://user-images.githubusercontent.com/3295025/53156742-52c2c580-35c0-11e9-8e92-65a0fb263544.png)
Electron:
![electron-clip](https://user-images.githubusercontent.com/3295025/53156754-55bdb600-35c0-11e9-9016-cac60a327300.png)

Here might be some informations about making sure to handle clipboard images with transparency: https://stackoverflow.com/a/52087880/6606805

**Comment by tinoji** [comment]
FYI
Same issue with Electron 5.0.6 :raised_hand:

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by bartcich** [comment]
Still happening for Electron 6.1.7

**Comment by gigadeplex** [comment]
update?

**Comment by AramAnd** [comment]
Still happening on Electron 8.2.5. Please help.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
