### ISSUE TITLE
Modal dialogs do not keep focus

### ISSUE THREAD

**Issue by Yanpas** [electron/electron#17087]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  *  3.1.3
* **Operating System** (Platform and Version):
  *  Ubuntu 18.10 x64
* **Last known working Electron version** (if applicable):
  *  ?

Original issue: https://github.com/Microsoft/vscode/issues/68645

### Expected Behavior

* modal window is poped up
* modal window is closed
* focused element is the same as before it has poped up

### Actual behavior
Focus is transferred to some other element

screencast:
![peek 2019-02-21 13-38](https://user-images.githubusercontent.com/7345761/53162884-01c1ca00-35de-11e9-995b-67ed4303aa7f.gif)

Here I middle-click on the pane of opened editors (middle click in linux is like Ctrl+V), it should close an editor. If I click it inside an editor it should paste the content of clipboard.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
