### ISSUE TITLE
new BrowserWindow is ignoring all the arguments (settings) randomly

### ISSUE THREAD

**Issue by allexzander** [electron/electron#17092]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 3.0.13
* **Operating System** (Platform and Version):
  * macOS, Windows, Ubuntu x64 all versions
* **Last known working Electron version** (if applicable):
  * ?

### Expected Behavior
  const childWindow = new BrowserWindow({
     x: 1680,
     y: 700, 
     width: 200,
     height: 194,
     frame: false,
     resizable: false,
     transparent: true,
     alwaysOnTop: true,
     focusable: false,
     minimizable: false,
     maximizable: false,
     toolbar: false,
  });
would always open a new BrowserWindow in a specified position (x: 1680, y: 700), with specified size (width: 200, height: 194), and no frame (frame: false).

### Actual behavior
It randomly happens for new BrowserWindow to be opened in such a way so it's ignoring all the arguments mentioned above (position, size, frame), so it's appearing in top left corner (0, 0), having a default size (about 800x600), having a frame (even though it was set to `false`). This happens about 1/100 to 1/1000, yet, it brings serious usability issues for our application users. There is no way for us to find out what exactly is happening. Having a `BrowserWindow::getBounds()` logged when `ready-to-show` event triggers, outputs the correct position and size (the one we've specified), yet the actual window looks huge (800x600) and has a frame.

### To Reproduce
1. Use the code from Expected Behavior in any Electron app with version starting from 3.0.13, and test it 
    multiple times (a lot), observe a random issue described in Actual Behavior.

### Screenshots
![issue_browser_window](https://user-images.githubusercontent.com/12224014/53221770-7871cc80-369d-11e9-949f-517102cb02b5.jpeg)

### Additional Information
We tried different Electron versions. Issue seem to be present in every version.

**Comment by allexzander** [comment]
Update: I was not able to find the reason of this issue, but, I guess, calling the `window.open` is randomly skipping the Electron's override of `new-window` event, and instead calling the Webkit(Chromium)'s implementation, hence the window appears on top left, having a border, not transparent, and having a default size - same as if we wouldn't use the `new-window` override. Just an assumption.
We had to implement a child window in a completely different way, because we need to deliver the feature soon, but, using the `window.open` along with `new-window` is our dream.

**Comment by MarshallOfSound** [comment]
Is window.open being called from an iframe in some cases?

**Comment by allexzander** [comment]
@MarshallOfSound No. We don't use iframe in our project. `window.open` is called from within React component's `componentDidMount` method. Here's the snippet:
`componentDidMount() {
    if (this.props.frameName && this.props.children) {
      this.portalWindow = window.open('', this.props.frameName, this.props.additionalFeatures);
   }
 }`

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
