### ISSUE TITLE
Top menu is visible by default on binary download

### ISSUE THREAD

**Issue by anuradhamudalige** [electron/electron#17093]
* **Electron Version**
  * 5.0.0-beta.3
* **Operating System** (Platform and Version): 
  * Windows 7 x64
* **Last known working Electron version** (if applicable): 
  * 4.0.5

### Expected Behavior
Top level menu should hid by default in binary download

### Actual behavior
Top level menu is visible on binary download

### To Reproduce
Use electron-packager or electron-builder with electron version mentioned and build your executable. Fire up the application.

**Comment by nornagon** [comment]
This is intended behavior, to match the menu behavior when in development mode. You can explicitly set a null menu if you want to disable the top menu.
