### ISSUE TITLE
A code conflict between Electron and ArcGIS JS API 4.x

### ISSUE THREAD

**Issue by Qio-fairy** [electron/electron#17108]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 4.0.5
* **Operating System** (Platform and Version):
  * macOS 10.14.2

### Actual behavior
We found a code conflict between Electron and ArcGIS JS API 4.8 and above versions. 

We use Electron + Vue 2.0 + ArcGIS JS API to do our project. In the beginning, we use  ArcGIS JS API 4.7 version, there is no problem. But when we change the 4.7 version to 4.8 and above versions, we found errors such as:  _windows.require.on is not a function_/_Ka is not a function_, and the map can't be loaded.

### To Reproduce
Please clone the code https://github.com/Qio-fairy/Electron-vue-arcgis.git
Then, run:
```sh
$ npm install
$ npm run dev
```
We can see the map loading is successful, this time the version of ArcGIS JS API is 4.6.0

To change the version of ArcGIS JS API, please open the _package.json_, and change `"esri-loader": "2.2.0"` to "esri-loader": "^2.6.0", the version of ArcGIS JS API will be changed to 4.10.0(latest)
P.S. You can also use options to change the version of ArcGIS JS API instead of esri-loader.
Then, run:
```sh
$ npm install
$ npm run dev
```
The error will accur.

### Screenshots
Please read https://github.com/Qio-fairy/Electron-vue-arcgis/blob/master/doc.docx

### Additional Information
We also try to contact with Esri, and they have already replied to us: "We did a simple 410 test and found the same problem you asked, possibly due to a variable boost. We submitted this issue to the US headquarters, but because it is a third-party product that is compatible with our products, it may not be resolved. I suggest you contact Electron to see if the problem can be solved."
And we have tried to send e-mail to info@electronjs.org, we still have not received any reply from Electron. Please help us, we will be very grateful.

**Comment by MarshallOfSound** [comment]
You will need to disable `nodeIntegration` in your window.

https://github.com/Qio-fairy/Electron-vue-arcgis/blob/efbed36e552faae737b004e91305cdf703cb0ae7/src/main/index.js#L20

> And we have tried to send e-mail to [info@electronjs.org](mailto:info@electronjs.org), we still have not received any reply from Electron. Please help us, we will be very grateful.

For future reference that is not the purpose of that email address
