### ISSUE TITLE
Dialog's defaultId Ineffective

### ISSUE THREAD

**Issue by twodee** [electron/electron#17101]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 4.0.5
* **Operating System** (Platform and Version):
  * macOS 10.12.6
* **Last known working Electron version** (if applicable):
  * 1.8.8

### Expected Behavior
A call to `dialog.showMessageBox` with the options

```js
{
   defaultId: 0,
   buttons: ['Wait', 'Discard'],
   message: 'You have unsaved changes. Discard them?',
}
```

will display a dialog whose Wait button is highlighted as the default.

### Actual behavior
The Wait button is not selected as the default. However, if I add a third button labeled No, or rename Discard to Cancel, then Wait is selected as the default.

### To Reproduce
I've placed a minimal working example at https://github.com/twodee/electron_defaultid_issue. All the code is in `main.js`:

```js
const { app, BrowserWindow, dialog } = require('electron');

function createWindow () {
  let win = new BrowserWindow({ width: 800, height: 600 });
  win.loadFile('index.html');
  win.on('close', e => {
    let options = {
      defaultId: 0,
      buttons: ['Wait', 'Discard'],
      message: 'You have unsaved changes. Discard them?',
    };
    let choice = dialog.showMessageBox(win, options);
    if (choice == 1) {
      win.destroy();
    }
  });
}

app.on('ready', createWindow);
```

```sh
$ git clone https://github.com/twodee/electron_defaultid_issue
$ npm install
$ npm start || electron .
```

### Screenshots

The Wait button is not selected as the default when the labels are Wait and Discard:
<img width="912" alt="screen shot 2019-02-24 at 6 18 27 am" src="https://user-images.githubusercontent.com/1939462/53289549-3b701c00-37fc-11e9-97b9-2fbcebbe85c4.png">

The Wait button is selected as the default when the labels are Wait and Cancel:
<img width="912" alt="screen shot 2019-02-24 at 6 17 56 am" src="https://user-images.githubusercontent.com/1939462/53289552-43c85700-37fc-11e9-8297-8391f7aa3cc5.png">

**Comment by codebytere** [comment]
@twodee i just ran your repro and it produced the correct results running v4.0.4. I was, however, using macOS 10.14 Mojave.

![Uploading Screen Shot 2019-02-25 at 2.00.19 PM.png…]()

**Comment by MarshallOfSound** [comment]
@codebytere I've successfully reproduced it on my master build and `4.0.5`, looks like some unexpected behavior when `defaultId` is set to `0` and no `no` or `cancel` button is present.  PR incoming.

**Comment by MarshallOfSound** [comment]
@twodee As a work-around for now you can set `cancelId: 1` in your code and the default will highlight correctly.  As an added bonus the cancel button will be mapped as well 😄

**Comment by twodee** [comment]
You people make submitting bug reports a delightful experience. The `cancelId` workaround does the job so well I will probably leave it in.

**Comment by codebytere** [comment]
@twodee appears i got thrown off by dark mode: what i thought was not a repro was in fact a repro 🙈 

thanks @MarshallOfSound!
