### ISSUE TITLE
Deeplink OSX Not Installed Handling

### ISSUE THREAD

**Issue by nickfujita** [electron/electron#17109]
The setAsDefaultProtocolClient method works as expected, but I was not able to find any documentation on how the usage of these deeplinks should be handled. Maybe this is out of the scope for Electron itself, but think it would be helpful for all those that are looking to implement deep-linking to their Electron desktop apps.

On Windows 10, deep-linking works as expected.
- Users navigate to the uri (eg. myapp://test), and the user will be prompted to open their application if it is installed.
- If the user does not have the application installed, if your app is in the Windows 10 store, and you have the proper keyword set, it will direct the user to the store.

On OSX, this is not the case.
- Users navigate to the uri (eg. myapp://test), and the user will be prompted to open their application if it is installed.
- If the user does not have the application installed, a couple things can happen depending on how the uri is being called.
  - If the uri is being called directly in the browser url, then for browsers like chrome, it will run a search for "myapp://test". This scenario is not so bad since you can pick a uri prefix that would result in relevant search results. This can be achieved from a web app by calling `window.open`, however in the case that the user has the app installed, and is prompted to open the app, it leaves the web browser with a blank tab open.
  - If the uri is called via JS, `window.location.replace("myapp://test")`, then nothing happens. This is the worst case, as the user has no indication that anything has happened or not, and the web application trying to call the deeplink has no idea if the app was opened successfully or not. Is there a way to detect if a deeplink has successfully prompted a user to open the app or not when using the `window.location.replace` method, or is there possibly another way that it can be called where the web app can detect this?

Is there possibly a configuration that can be set with the OSX app store that can search for the URI prefix when it's called from a web browser, but the app is not found to be installed?

**Comment by MarshallOfSound** [comment]
> Is there possibly a configuration that can be set with the OSX app store that can search for the URI prefix when it's called from a web browser, but the app is not found to be installed?

Unfortunately this is not supported at an OS level on macOS.  You would need to do some kind of app detection and show a page asking users to download your application if the URI launch fails.  A common trick for achieving this is outlined here.

https://github.com/electron/fiddle/issues/43#issuecomment-409032237
