### ISSUE TITLE
Can not view PDF

### ISSUE THREAD

**Issue by anuradhamudalige** [electron/electron#17110]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 

### Expected Behavior
PDF must be viewable

### Actual behavior
It says 'Couldn't load plugin'

### To Reproduce
I've set the plugins to true on BrowserWindows->webPreference but nothing works

**Comment by beig** [comment]
Take a look at this issue: https://github.com/electron/electron/issues/12337

**Comment by MarshallOfSound** [comment]
Duplicate of #12337

**Comment by anuradhamudalige** [comment]
Is this fixed?

On Feb 25, 2019, at 11:32 PM, Samuel Attard <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #17110<https://github.com/electron/electron/issues/17110>.

**Comment by anuradhamudalige** [comment]
Why is this issue closed? it's still there!

**Comment by ThomasMoutel** [comment]
> Why is this issue closed? it's still there!

It has been marked as a duplication of #12337 , see above.

**Comment by Nashorn** [comment]
Running Electron 6.0.0-beta.4
Still no pdf support 👎
