### ISSUE TITLE
WhatsApp works with Google Chrome 36+

### ISSUE THREAD

**Issue by has7eem** [electron/electron#17119]
* **Electron Version** 4.0.5
* **Operating System**  Windows 8.1

### Expected Behavior

Open WhatsApp web through Electron webView

### Actual behavior
WhatsApp works with Google Chrome 36+
To use WhatsApp, update Chrome or use Mozilla Firefox, Safari, Microsoft Edge or Opera.

### Screenshots

![img](https://c.top4top.net/p_1151f7l301.png)

**Comment by has7eem** [comment]
@codebytere

**Comment by MarshallOfSound** [comment]
@has7eem This is not an issue with Electron, WhatsApp must be doing some kind of UA sniffing or feature detection and it is mis-detecting Electron.

I'd recommend using the `setUserAgent` APIs to try hack around this, but this is not an Electron issue.

**Comment by has7eem** [comment]
I have tried many solutions, and that's just who worked with me.

```html
<webview 
src="https://web.whatsapp.com/" 
partition="persist:github" 
useragent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36">
</webview>
```
Do not forget to delete your storage first.
If you don't care about save your registration and don't need to clear storage every time.
read about `partition` in Electron Doc
