### ISSUE TITLE
event.preventDefault() doesn't work for window-all-closed

### ISSUE THREAD

**Issue by amargautam** [electron/electron#17125]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
4.0.5
* **Operating System** (Platform and Version):
macOS 10.14.3 & Win 10.0.17763
* **Last known working Electron version** (if applicable):
Not sure

### Expected Behavior
When I call `event.preventDefault()` at `window-all-closed`, I expect the app to not close and keep in focus.

### Actual behavior
App exits on windows and minimizes to dock on macOS without preventing default behavior.

### To Reproduce
[https://github.com/amargautam/electron-confirm-on-exit](https://github.com/amargautam/electron-confirm-on-exit)

### Screenshots
No applicable

### Additional Information
We are trying to show a dialog before the exit to confirm if the user really wants to quit.

**Comment by MarshallOfSound** [comment]
You're issue is you are calling [`e.preventDefault()`](https://github.com/amargautam/electron-confirm-on-exit/blob/master/main.js#L58) asynchronously.  i.e. By the time you are saying "don't quit", the app has already quit.

You'll need to call `e.preventDefault()` synchronously and then call `app.quit()` yourself in the dialog handler.  Something like the code below should work (untested).

```js
let allowQuit = false
function confirmAndQuit(e) {
  if (allowQuit) return;
  e.preventDefault();
  // dialog options
  const messageBoxOptions = {
    type: 'question',
    buttons: ['Cancel', 'Quit'],
    title: 'This will quit the app',
    message: 'Are you sure to quit?',
  };
  //show the dialog
  dialog.showMessageBox(null, messageBoxOptions, response => {
    // If user chooses to not exit
    if(response == 0) {
      // Do nothing, we've already prevented the exit and kept the window active
    } else {
      // If the user choses to quit, do nothing. 
      // will-quit event will trigger to be handled differently
      allowQuit = true;
      app.quit()
    }
  });
}

// Quit when all windows are closed.
app.on('window-all-closed', function (e) {
  // On macOS it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  confirmAndQuit(e)
})
```
