### ISSUE TITLE
In mine process console.log not working 

### ISSUE THREAD

**Issue by Maxmaxmaximus3** [electron/electron#17131]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * all
* **Operating System** (Platform and Version):
  * Windows 10 (1803)
* **Last known working Electron version** (if applicable):
  * none

### Expected Behavior
write this
```javascript
setInterval(function(){
  console.log(11)
}, 1000)
``` 
in mine.js, and when chrome remote debgger attached, must write 11,11,11,11 every second

### Actual behavior
in chrome remote debugger console is empty, but in command line where i write `electron . --inspect` console.log(11) outpus works correct

### To Reproduce
1) download this https://chrome.google.com/webstore/detail/nodejs-v8-inspector-manag/gnhhdgbaldcilmgcpfddgdbkhjohddkj

2) create `mine.js` like this
```javascript
setInterval(function(){
  console.log(11)
}, 1000)
``` 

3) run `electron . --inspect` from command line

4) in command line you see 11, 11, 11

5)  but in chrome dev tools you dont see none

### Screenshots
![image](https://user-images.githubusercontent.com/47686234/53376885-f5889480-3970-11e9-870f-abac9d7b92b2.png)

![image](https://user-images.githubusercontent.com/47686234/53376892-fe796600-3970-11e9-9e0d-0cc4accede3f.png)

**Comment by Maxmaxmaximus3** [comment]
Actually chrome plugin not required, it is just to simplify =)

![image](https://user-images.githubusercontent.com/47686234/53377324-a80d2700-3972-11e9-8bc2-ab15589059d7.png)

**Comment by ckerr** [comment]
Hi @Maxmaxmaximus3, thanks for filing this issue.

If I'm reading your issue correctly, I think [this stackoverflow answer](https://stackoverflow.com/a/31759944) has the answer you're looking for. `console.log()` works, but where it logs to depends on whether you call it from the main process or the renderer process.

I'm closing this issue as notabug. If this in error, please followup with more information. Thank you!

**Comment by Maxmaxmaximus3** [comment]
@ckerr how can i cee console output from main.js in chrome debugger? it is possible?

**Comment by zengdongbao** [comment]
I have the same confusion， and the dev-tool source tab not work too

**Comment by iMegaMaximus2** [comment]
bump
