### ISSUE TITLE
Using offscreen on some websites makes app to crash

### ISSUE THREAD

**Issue by btzsoft** [electron/electron#17140]
* **Electron Version:**
  `4.0.4`
* **Operating System:**
  `macOS 10.14.3`

### Actual Behavior
App crash when using `offscreen: true` on some websites.

### To Reproduce
```js
const win = new BrowserWindow({
  visible: true,
  webPreferences: {
    offscreen: true
  }
});
win.webContents.loadURL("http://www.4dreplay.com");
```

I don't have right now more websites to report, but I saw that this happens not only navigating to `http://www.4dreplay.com`

**Comment by btzsoft** [comment]
Hi @brenca, do you have any thoughts why this makes the app to crash?

**Comment by brenca** [comment]
Hey @btzsoft, I'm not sure yet, the crash log is not really helpful, so I'm going to have to investigate a bit further.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
