### ISSUE TITLE
Link chromiumdev-slack refers to some king of strange site

### ISSUE THREAD

**Issue by kindritskyiMax** [electron/electron#17154]
Did you see that link to chromiumdev-slack on https://electronjs.org/docs/development/chromium-development page refers to this site https://chromiumdev-slack.herokuapp.com/index.html which is not the slack related page?

**Comment by kindritskyiMax** [comment]
Actually there is a chromium slack https://chromium.slack.com/. Found it at https://groups.google.com/a/chromium.org/forum/?utm_medium=email&utm_source=footer#!topic/chromium-dev/Nr-SENBRPI0

**Comment by nornagon** [comment]
That slack is not public, and isn't a support slack (it's for developers to talk about developing Chromium). I don't think linking to it here would be appropriate.

**Comment by kindritskyiMax** [comment]
Oh, yes, now I see. Thanks for the clarification.
