### ISSUE TITLE
Windows 10: .getSources returns different number of displays from .getAllDisplays

### ISSUE THREAD

**Issue by paulius005** [electron/electron#17159]
* **Electron Version:**
  3.1.3
* **Operating System:**
Windows 10 (1803)
* **Last Known Working Electron version:**:
  N/A

### Expected Behavior
That `.getSources` returns the same length array as `.getAllDisplays`

### Actual Behavior
From `.getSources`:
```
[ { display_id: '2480450848',
    id: 'screen:3:0',
    name: 'Entire screen',
    thumbnail: {} } ]
```

From `.getAllDisplays`:
```
[ { id: 2480450848,
    bounds: { x: 1920, y: 0, width: 1920, height: 1080 },
    workArea: { x: 1920, y: 0, width: 1920, height: 1040 },
    size: { width: 1920, height: 1080 },
    workAreaSize: { width: 1920, height: 1040 },
    scaleFactor: 1,
    rotation: 0,
    touchSupport: 'unknown' },
  { id: 2528732444,
    bounds: { x: 0, y: 0, width: 1920, height: 1080 },
    workArea: { x: 0, y: 0, width: 1920, height: 1040 },
    size: { width: 1920, height: 1080 },
    workAreaSize: { width: 1920, height: 1040 },
    scaleFactor: 2,
    rotation: 0,
    touchSupport: 'unknown' } ]
```

### To Reproduce
To reproduce, take a Windows 10 laptop with 2 monitors and use this [Docking Station](https://smile.amazon.com/gp/product/B00ECDM78E/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1) to plug the two monitors in while operating the laptop in clamshell mode

In this case you will also notice that the id printed by `.getSources` is `screen:3:0` while traditionally if 1 display is available it would return `screen:1:0` which seems quite peculiar

You can see the issue being logged out in this custom built version of our Loom Application: https://www.dropbox.com/s/5oxcdww7euq8rbu/Loom%20Setup%200.59.0.exe?dl=0

### Additional Information
NOTE: While the issue exists in `getSources`, with the latest version of Chrome, `.chooseDesktopMedia` works as expected, showing both displays

I was able to replicate this reliably on a user's laptop and have order the piece of hardware (docking station) so I can try and debug as well. Please let me know if there is anything else I can do to provide more info to help with the issue.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
