### ISSUE TITLE
Scaling issues on all Electron based apps in Windows 10

### ISSUE THREAD

**Issue by selman92** [electron/electron#17157]
* **Operating System:**
  * Windows 10 (1803)

### Expected Behavior
Apps to work crystal clear with no blurry text.

### Actual Behavior
Texts are getting blurry when the app loses focus or being resized, and sometimes just randomly. The texts are not sharp, makes the app unusable.

### To Reproduce

This happens randomly, but also when I open the app and open another one on top if, so the previous app is in the background, and I resize the app that has the focus, the app in the background gets blurry.

And it also happens when the app has focus, but only the focused part works and other parts of the app gets blurry, like the menu or other grid panels etc.

### Screenshots
This is from [Atom](https://atom.io/) app: 

![atom](https://user-images.githubusercontent.com/17150333/53495962-16a4ce80-3ab2-11e9-95e8-951e52a3b608.png)

Visual Studio  Code:
![vs_code](https://user-images.githubusercontent.com/17150333/53496217-96cb3400-3ab2-11e9-9839-f6cde8f41cc8.png)

### Additional Information
My screen resolution is 2560x1440, DPI: %100 default

Tried different DPI settings, custom scaling, enabling "Let Windows try to fix apps so they are not blurry" option. Nothing worked so far.

I have this issue with every app that is written in Electron, other examples are: Postman, Slack

**Comment by luetm** [comment]
@selman92 which one of the many solutions is the one that helps?
