### ISSUE TITLE
The bubbling event on webview

### ISSUE THREAD

**Issue by wfeang** [electron/electron#17152]
electron --version`:5.5.1
(Platform and Version):window 10

I used the web page in the webview and added the ‘contextmenu event' on the web element. When I clicked the right click, the webview event was also triggered. How can I avoid it
![image](https://note.youdao.com/yws/public/resource/6da7561ca5dfc3eb39c00ed2b7013047/xmlnote/7A9BA974CA90417BA1EBD2311776EFEF/9585)
![image](https://note.youdao.com/yws/public/resource/6da7561ca5dfc3eb39c00ed2b7013047/xmlnote/BA575F1746D547F792C6BF960F511441/9586)

**Comment by wfeang** [comment]
![image](https://note.youdao.com/yws/public/resource/6da7561ca5dfc3eb39c00ed2b7013047/xmlnote/7A9BA974CA90417BA1EBD2311776EFEF/9585)
![image](https://note.youdao.com/yws/public/resource/6da7561ca5dfc3eb39c00ed2b7013047/xmlnote/BA575F1746D547F792C6BF960F511441/9586)

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
