### ISSUE TITLE
dev tools show nothing in webview

### ISSUE THREAD

**Issue by njleonzhang** [electron/electron#17168]
* **Electron Version:**
4.0.2
* **Operating System:**
mac 10.14

### Expected Behavior
[sample code](https://electronjs.org/docs/api/web-contents#contentssetdevtoolswebcontentsdevtoolswebcontents) doesn't work. the dev tool shows, but it's empty.

```
<html>
<head>
  <style type="text/css">
    * { margin: 0; }
    #browser { height: 70%; }
    #devtools { height: 30%; }
  </style>
</head>
<body>
  <webview id="browser" src="https://github.com"></webview>
  <webview id="devtools"></webview>
  <script>
    const browserView = document.getElementById('browser')
    const devtoolsView = document.getElementById('devtools')
    browserView.addEventListener('dom-ready', () => {
      const browser = browserView.getWebContents()
      browser.setDevToolsWebContents(devtoolsView.getWebContents())
      browser.openDevTools()
    })
  </script>
</body>
</html>
```

### Screenshots
the dev tools show nothing.

![image](https://user-images.githubusercontent.com/13174059/53564768-b8035180-3b92-11e9-815a-92160a730eef.png)

after remove this line `browser.setDevToolsWebContents(devtoolsView.getWebContents())`, the devtool can show correctly.

![image](https://user-images.githubusercontent.com/13174059/53565018-4d064a80-3b93-11e9-9d0e-6c56880bd775.png)

**Comment by MarshallOfSound** [comment]
@njleonzhang Doing this across `remote` means this is being done over multiple IPC / remote bridges.  Can you try this code / logic in the main process 👍

**Comment by njleonzhang** [comment]
@MarshallOfSound I think I haven't gotten your point. I try to make the process in main process in the following way, but issue persists:

```
// main.js, entry of main process
exports.openDevToolsForWebview = function(simulatorWebContents, devtoolsViewWebContents) {
  console.log('simulatorWebContents is:', simulatorWebContents, 'devtoolsViewWebContents is:', devtoolsViewWebContents)
  simulatorWebContents.setDevToolsWebContents(devtoolsViewWebContents)
  simulatorWebContents.debugger.attach()
  simulatorWebContents.openDevTools()
}
```

```
// render process
import electron from 'electron'
const { openDevToolsForWebview } = electron.remote.require('./index')

let simulatorView = document.getElementById('simulator')
let devtoolsView = document.getElementById('devtools')

simulatorView.addEventListener('dom-ready', () => {
  openDevToolsForWebview(simulatorView.getWebContents(), devtoolsView.getWebContents())
})
```

would you please give me a sample?

**Comment by njleonzhang** [comment]
The origin code in document can work on 2.0.17. The bug shows from 3.0.1 till now. Currently I roll back to 2.0.17.

**Comment by chatcan** [comment]
still don't work on electron 4.0.6

**Comment by njleonzhang** [comment]
@chatcan try to roll back to 2.0.17

**Comment by tedpenk** [comment]
any solution now?

**Comment by tedpenk** [comment]
Plesae don't forget the 3.x version doesn't work either，and We need 3.x.

**Comment by Mqleaf** [comment]
what is going on?
 I used 2.0.18, but couldn't click element in mobile mode. 
so I change to 3.x，can click element in mobile mode, work well. however, the devtools is empty......

**Comment by freedomelf** [comment]
sample code doesn't work in version 4.1.0, like this:
`<webview id="browser" src="https://github.com"></webview>
  <webview id="devtools"></webview>
  <script>
    const browserView = document.getElementById('browser')
    const devtoolsView = document.getElementById('devtools')
    browserView.addEventListener('dom-ready', () => {
      const browser = browserView.getWebContents()
      browser.setDevToolsWebContents(devtoolsView.getWebContents())
      browser.openDevTools()
    })
`
I replaced the webview with a BrowserView in main process, and set the same position. 
In main process, use webview#browser's setDevToolsWebContents argument to BrowserView instance, sample code：

`
//renderer process
//html
<webview id="container"></webview>

//js
const ipc = require('electron').ipcRenderer;
const app = document.getElementById('app');
app.addEventListener('dom-ready', () => {
    ipc.send('initialized');
});

//main process
mainWindow.webContents.loadURL(`file://${__dirname}/index.html`);
const devtools = new BrowserView({...});
mainWindow.setBrowserView(devtools);

devtools.setBounds({x: 475, y: 60, width: 920, height: 795});
ipcMain.on('initialized', () => {
        const container: webContents | undefined = webContents.getAllWebContents().find((item) => {
            return item.getURL().includes('resources/index.html');
        });
        if (container) {
            container.setDevToolsWebContents(devtools.webContents);
            container.debugger.attach();
            container.openDevTools();
        }
 });

`

@tedpenk @Mqleaf @njleonzhang

**Comment by kitze** [comment]
@freedomelf so the only way to solve this is using a BrowserView instead of a webview? :|

**Comment by matt-way** [comment]
Doesn't work in current beta either (v6.0.0-beta.15).

**Comment by kitze** [comment]
@matt-way yup looks like this is the issue:
https://github.com/electron/electron/issues/14095

**Comment by tedpenk** [comment]
Is there any plans to fix this problem in v3.x or v4.x？

**Comment by kunal01996** [comment]
Can't get it to work in v6.0.0

**Comment by kitze** [comment]
@codebytere said she'll take a look in this issue: https://github.com/electron/electron/issues/14095

**Comment by chemzqm** [comment]
Still not work on 6.0.11

**Comment by codebytere** [comment]
Duplicate of https://github.com/electron/electron/issues/14095

**Comment by schacker** [comment]
Still not work on 7.1.13

**Comment by huyifan** [comment]
hi guys who troubled with using devTools in webView. if you do want to use webView to load devTools and debug the page ,you can try this way.

*1
you can add those code in main process which can open a socket server that contains all devUrl you need

const { app } = require('electron');
……
app.commandLine.appendSwitch('remote-debugging-port', `${debugPort}`);
app.commandLine.appendSwitch('remote-debugging-address', 'http://127.0.0.1');


*2
in render process you can fetch the url '127.0.0.1:debugPort/json'  and it will resp all devUrls .

*3
if you set webView url such as 'http://github.com',And in step 2 you has got all devUrls ,  you just need  to get the devUrl  which .url.indexOf('http://github.com')

*4
devtoolsViewDom.setAttribute("src", `http://127.0.0.1:${debugPort}${devUrl}`)

above may not easy to understand ,I will give a demo soon.

**Comment by zhongkai** [comment]
> hi guys who troubled with using devTools in webView. if you do want to use webView to load devTools and debug the page ,you can try this way.
> 
> *1
> you can add those code in main process which can open a socket server that contains all devUrl you need
> 
> const { app } = require('electron');
> ……
> app.commandLine.appendSwitch('remote-debugging-port', `${debugPort}`);
> app.commandLine.appendSwitch('remote-debugging-address', 'http://127.0.0.1');
> 
> *2
> in render process you can fetch the url '127.0.0.1:debugPort/json' and it will resp all devUrls .
> 
> *3
> if you set webView url such as '[http://github.com',And](https://github.com',And) in step 2 you has got all devUrls , you just need to get the devUrl which .url.indexOf('[http://github.com](https://github.com)')
> 
> *4
> devtoolsViewDom.setAttribute("src", `http://127.0.0.1:${debugPort}${devUrl}`)
> 
> above may not easy to understand ,I will give a demo soon.

Great solution

**Comment by wyang0816** [comment]
I use the demo https://github.com/electron/electron/blob/00fc8066de5c6617769567ec0369f10a271426f8/docs/api/web-contents.md . And add a line 'devtools.webContents.executeJavaScript("window.location.reload()");' on the after with 'browser.openDevTools()', to fix on Electron@9.1.2

**Comment by Karine91** [comment]
> hi guys who troubled with using devTools in webView. if you do want to use webView to load devTools and debug the page ,you can try this way.
> 
> *1
> you can add those code in main process which can open a socket server that contains all devUrl you need
> 
> const { app } = require('electron');
> ……
> app.commandLine.appendSwitch('remote-debugging-port', `${debugPort}`);
> app.commandLine.appendSwitch('remote-debugging-address', 'http://127.0.0.1');
> 
> *2
> in render process you can fetch the url '127.0.0.1:debugPort/json' and it will resp all devUrls .
> 
> *3
> if you set webView url such as '[http://github.com',And](https://github.com',And) in step 2 you has got all devUrls , you just need to get the devUrl which .url.indexOf('[http://github.com](https://github.com)')
> 
> *4
> devtoolsViewDom.setAttribute("src", `http://127.0.0.1:${debugPort}${devUrl}`)
> 
> above may not easy to understand ,I will give a demo soon.

I tried to fetch by this url 127.0.0.1:debugPort/json but got CORS error, how you get it to work?

**Comment by Karine91** [comment]
@huyifan I used your solution but have problems with debugging.  When I set debugger breakpoint and reload the webview page, it stops on breakpoint but I can't interact with my devtools webview because of 'paused debugger overlay'. When I enable in devtools settings the option "Disable paused state overlay" everything works fine. Why this overlay cover my webview devtools if I'm debugging another webveiw? Any thoughts?

**Comment by christlee1989** [comment]
> @huyifan I used your solution but have problems with debugging. When I set debugger breakpoint and reload the webview page, it stops on breakpoint but I can't interact with my devtools webview because of 'paused debugger overlay'. When I enable in devtools settings the option "Disable paused state overlay" everything works fine. Why this overlay cover my webview devtools if I'm debugging another webveiw? Any thoughts?

I have the same problem. Have you solved?  @Karine91

**Comment by stevenlafl** [comment]
Interestingly, the exact example from the docs shows an empty devtools window. It doesn't work.

**Comment by princeomonu** [comment]
> I use the demo https://github.com/electron/electron/blob/00fc8066de5c6617769567ec0369f10a271426f8/docs/api/web-contents.md . And add a line 'devtools.webContents.executeJavaScript("window.location.reload()");' on the after with 'browser.openDevTools()', to fix on Electron@9.1.2

thanks! this solved my issues!!

**Comment by lxjts** [comment]
I tried the code below and succeed:
`
let win = new BrowserWindow();
let devWin = new BrowserWindow();
win.webContents.setDevToolsWebContents(devWin.webContents);
win.webContents.openDevTools();
// and then close it and reopen, then works
win.webContents.closeDevTools();
win.webContents.openDevTools();
`

**Comment by AliasT** [comment]
electron@30.0.0, still not working

**Comment by ArturGuedes** [comment]
The same problem on electron@31.0.2. Only works after `window.location.reload()`

**Comment by LINGyue-dot** [comment]
same issue in 26.6.10

**Comment by emmacramer** [comment]
has anyone else noticed that the `window.location.reload()` workaround no longer works? any other ideas?
