### ISSUE TITLE
electron.js

### ISSUE THREAD

**Issue by psdevu** [electron/electron#17166]
Hi All,
I am facing an issue.
I need my electron app always placed at the top with full-width and other windows should be placed under it.
How can I do this?
anyone can help me to solve this issue?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
