### ISSUE TITLE
building Electron error on windows

### ISSUE THREAD

**Issue by dijiang** [electron/electron#17179]
I am tring to building electron on windows.
after run the cmd gclient sync --with_branch_heads --with_tags for a long time, en error occured

![qq 20190301105126](https://user-images.githubusercontent.com/8736832/53613536-3999c480-3c11-11e9-8f47-ffc1c99c5767.png)

it seem that the code have be downloaded successfully .
how to resolve it? I need help

**Comment by nornagon** [comment]
Looks like the patch tool wasn't able to find `git`. Is `git` on your `%PATH%`?

**Comment by saxocellphone** [comment]
Try switching the order of the internal version of python and the depot_tools version of python. I remember having a similar problem with python versions.

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
