### ISSUE TITLE
getGPUInfo('complete') often never settles the returned promise

### ISSUE THREAD

**Issue by robatwilliams** [electron/electron#17187]
* **Electron Version:**
  * 4.0.4
* **Operating System:**
  * Windows 7, Windows 10
* **Last Known Working Electron version:**:
  * n/a - new API in v4

### Expected Behavior

The promise is always settled. Preferably resolved with the info, otherwise rejected with an error or a timeout.

### Actual Behavior

The promise often never settles. Not even after several minutes.

### To Reproduce

Call the method with `'complete'`. The issue doesn't happen with `'basic'`, [which is synchronous-like](https://github.com/electron/electron/pull/13486#issuecomment-403555502) but in a promise.

_When_ you call it seems to matter; it always works when called immediately in `main.js`, but often fails when called during other application activity.

Whether it settles or not seems to be persistent. If it settles, it's likely it will settle the next few times you run the app too. If it doesn't settle, chances are it won't settle next time you run the app either. So something seems to be getting stuck in a working/broken state.

### Additional Information

I suspect something deep down in Electron/Chromium is being called, that thing fails, leaving everything still waiting for it. If so, need fixing so it doesn't fail, and add some defence for async things failing.

Self-defence in application code: create a time limit by `Promise.race([])` ing the returned promise with another promise which rejects after a `setTimeout`.

**Comment by nornagon** [comment]
Is it possible that the gpu process is crashing on your machine?

**Comment by robatwilliams** [comment]
It doesn't appear so. I have a handler for `gpu-process-crashed`, which doesn't get called. Also, the GPU process in task manager has the same PID before and after.

I tried running with `--enable-logging --v=` with levels up to 6 and there didn't appear to be any related information from Chromium.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
