### ISSUE TITLE
app.disableHardwareAcceleration() doesn't disable GPU process creation

### ISSUE THREAD

**Issue by vladimiry** [electron/electron#17180]
* **Electron Version:** 4.0.6 and 5.0.0-beta.4 too
* **Operating System:** Linux x64
* **Last Known Working Electron version:** 3.1.4

### Expected Behavior
No GPU process created.

### Actual Behavior
GPU process created.

### To Reproduce
```javascript
const {app, BrowserWindow} = require("electron");

app.disableHardwareAcceleration();

app.on("ready", () => {
    const window = new BrowserWindow({
        width: 800,
        height: 600,
    });

    window.loadURL("about:blank");
});
```

**Comment by vladimiry** [comment]
@deepak1556 somehow similar to https://github.com/electron/electron/issues/14273?

**Comment by deepak1556** [comment]
Yup its the same issue, GPU process creation has been moved earlier in the startup cycle for sometime now. Its slightly difficult for user script to intervene. Although the process will be created, hw acceleration will be disabled when this api is called.

**Comment by vladimiry** [comment]
The difference is that it's working fine with v3.1.4 for me on Linux unlike in https://github.com/electron/electron/issues/14273 with v3.0.0-beta.7 on Windows. So at some point it stopped working with v4 and v5.

**Comment by deepak1556** [comment]
> But it would be great to drop the GPU process after that, so it doesn't eat a memory.

Yup 14273 is tracking that, also as a workaround if its possible for you to start the app from command line with `--disable-gpu` then this process won't be created.

**Comment by logidelic** [comment]
FWIW, passing `--disable-gpu` on the command-line doesn't work for me with electron 5

**Comment by vulture** [comment]
Same, --disable-gpu and app.disableHardwareRendering() still launch the gpu process for me

**Comment by RareScrap** [comment]
I was surprised but it still occurs in Electron 35
