### ISSUE TITLE
Recaptcha throws invalid domain for site key error, using custom protocol throws another error

### ISSUE THREAD

**Issue by AlekseyKost** [electron/electron#17182]
Using reCAPTCHA throws invalid domain for site key error if using not valid credentials. I tried to implement custom protocol as described here [#8414](https://github.com/electron/electron/issues/8414) but got error (see the screenshot)

* **Electron Version:**

- Electron version: 4.0.7
- Operating system: Windows 10, version 1809

### Expected Behavior
reCAPTCHA should work without errors

### Actual Behavior
My code in electron.prod.js file (which is responsible for the Main process) looks like this:
```ruby
protocol.registerStandardSchemes(['test']);

win = new BrowserWindow({
    width: size.width,
    height: size.height,
    x: 0,
    y: 0,
    icon: path.join(__dirname, 'favicon.ico'),
    webPreferences: {
      nodeIntegration: false
    }
  });

protocol.registerBufferProtocol('test', (request, callback) => {
    callback({mimeType: 'text/html', data: fs.readFileSync(path.join(__dirname, 'index.html'))})
  }, (error) => {
    if (error) console.error('Failed to register protocol');
  });

win.loadURL(url.format({
    pathname: path.resolve(__dirname, 'dist/frontend/index.html'),
    protocol: 'test:',
    slashes: true
  }));

```
After build was created, the app was installed and running error appears:

![electron_error](https://user-images.githubusercontent.com/48123353/53639711-abced100-3c32-11e9-807d-ac4418ce113e.png)

### Additional Information
I use electron-builder, domain validation was disabled in reCAPTCHA Admin Console

**Comment by sofianguy** [comment]
> Electron version: 5.6.0

5.6.0 is not one of Electron's versions. Can you please provide us with a correct version number?

**Comment by Aleksey-NFON** [comment]
@sofianguy I've adjusted the version number, it is 4.0.7. Thanks

**Comment by Aleksey-NFON** [comment]
@sofianguy Hi, are there any updates, thoughts regarding this issue?

**Comment by gtoroptsev** [comment]
@Aleksey-NFON Hi, try to specify full path to index.html

change this line

`callback({mimeType: 'text/html', data: fs.readFileSync(path.join(__dirname, 'index.html'))})`

to 

`callback({mimeType: 'text/html', data: fs.readFileSync(path.join(__dirname, 'dist/frontend/index.html'))})`

**Comment by Aleksey-NFON** [comment]
@gtoroptsev reCAPTCHA still throws invalid domain for site key error, doesn't help.

**Comment by Romain-P** [comment]
> @Aleksey-NFON Hi, try to specify full path to index.html
> 
> change this line
> 
> `callback({mimeType: 'text/html', data: fs.readFileSync(path.join(__dirname, 'index.html'))})`
> 
> to
> 
> `callback({mimeType: 'text/html', data: fs.readFileSync(path.join(__dirname, 'dist/frontend/index.html'))})`

It's `dist/index.html`

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
