### ISSUE TITLE
session.getCacheSize dose not work

### ISSUE THREAD

**Issue by rocka** [electron/electron#17189]
* **Electron Version:**
  * 3.1.4 and 4.0.6
* **Operating System:**
  * Arch Linux 4.20.13-arch1-1-ARCH x86_64
* **Last Known Working Electron version:**
  * 2.0.17

### Expected Behavior

get cache size using

```js
const {BrowserWindow} = require('electron')
const w = new BrowserWindow
w.loadURL('https://electronjs.org')
w.webContents.session.getCacheSize(size => {
  console.log(size) // -> output some random cache size, eg. 669451
})
```

### Actual Behavior

Can't get cache size, the callback never invoked.

### To Reproduce

make a temp test directory and do as follows:

```console
npm init -y
npm i electron@3 # or npm i electron@4
npx electron -i
> const {BrowserWindow} = require('electron')
undefined
> const w = new BrowserWindow
undefined
> w.loadURL('https://electronjs.org')
true
> w.webContents.session.getCacheSize(consloe.log)
undefined
# no cache size output here ...
```

### Additional Information

this problem may exist since 3.0

**Comment by codebytere** [comment]
Did a quick check on this and it looks like we get locked into a pending state which prevents the asynchrous operation from completing.

That is, we're here
https://github.com/electron/electron/blob/aa8b66aae175fa24ec097a9aae9657f9b609873e/atom/browser/api/atom_api_session.cc#L275

and `rv == net::ERR_IO_PENDING` so the callback doesn't run. i'll try to dig in some more soon.

**Comment by simongregory** [comment]
I'm getting this issue on the Mac with v5.0.4 (am noting because it's only labelled as an Linux problem).

**Comment by codebytere** [comment]
This was fixed in https://github.com/electron/electron/pull/17969.

i'll try to backport it soon.

**Comment by codebytere** [comment]
Closing as this has been backported to stable supported lines.
