### ISSUE TITLE
self signed certificate using axios rendrer side

### ISSUE THREAD

**Issue by larbijirari** [electron/electron#17186]
* **Electron Version:**
 4.0.5 -->
* **Operating System:**
  * Ubuntu 18.04 x64 -->
* **Last Known Working Electron version:**:
NUL

### Expected Behavior
call success 

### Actual Behavior
Failed to load resource: net::ERR_BAD_SSL_CLIENT_AUTH_CERT
### To Reproduce

const axios = Axios.create({
 baseURL: `${conf.get('sgbd.host')}:${conf.get('sgbd.port')}`,
 proxy: false,
 httpsAgent: new https.Agent({
    requestCert:false,
   rejectUnauthorized: false,
   ca: fs.readFileSync(conf.get('auth.ca')),
   cert: fs.readFileSync(conf.get('auth.cert')),
   key: fs.readFileSync(conf.get('auth.key'))
 })
});

axios.defaults.headers.Authorization = `CENTRI-USERNAME ${conf.get('auth.username')}, CENTRI-KEY ${conf.get('auth.apikey')}`;
axios.get('/vehicleType/10000').then((response) => {
          console.log(response);
        })

### Additional Information
this call works on main.js (ipc main)
but doesn't work on index.js (ipc rendrer)

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
