### ISSUE TITLE
[Mac] Top level windows are not excluded from the dock menu by default

### ISSUE THREAD

**Issue by CapOM** [electron/electron#17193]
* **Electron Version:**
  4.0.2
* **Operating System:**
  macOS 10.14.3
* **Last Known Working Electron version:**:
  1.7

### Expected Behavior
When creating a BrowserWindow it should not appear in the dock menu by defaults.

### Actual Behavior
It appears in the dock menu (example: `raven` in https://electronjs.org/docs/tutorial/macos-dock)

### To Reproduce
Just create new BrowserWindow, then right click on the app icon in the dock. (see https://electronjs.org/docs/tutorial/macos-dock)

At least it should be a way to control that, this can be achieve for top level window with:
`[window_ setExcludedFromWindowsMenu:YES];`, indeed [window isExcludedFromWindowsMenu] returns false by default, see

https://developer.apple.com/documentation/appkit/nsapplication/1428625-removewindowsitem
`Use the isExcludedFromWindowsMenu method of NSWindow if you want the item to remain excluded from the Window menu.`
https://developer.apple.com/documentation/appkit/nswindow/1419175-isexcludedfromwindowsmenu

**Comment by CapOM** [comment]
Actually it is not a regression, just setting the title as empty an it works. But maybe we can change this bug entry to a feature request to add a `BrowserWindow:setExcludedFromWindowsMenu`

**Comment by codebytere** [comment]
@CapOM i'll see what i can do!
