### ISSUE TITLE
Float64Array is converted to Uint8Array when sent over IPC

### ISSUE THREAD

**Issue by vshymanskyy** [electron/electron#17195]
* **Electron Version:**
v1.8.8, v3.1.4, v4.0.6
* **Operating System:**
  *  Windows 10 (1803)

### Expected Behavior
Float64Array and other Typed Arrays should preserve their type and correct values.

### Actual Behavior
Main process sends an object with multiple `Float64Array` instances, Renderer gets all of them converted byte-wise to `Uint8Array`.

P.S. With electron 1.7.16 it was converted to `Array` with correct values.

May be related to #13055 or #6572

**Comment by miniak** [comment]
@vshymanskyy what do you mean exactly by sent over IPC? Using `ipcRenderer.send()` / `ipcMain.on()` or the `remote` module?

**Comment by MrNovado** [comment]
@miniak having the same issue. It's `ipcRenderer.send()`. Also reproducible with `Float32Array `.

**Comment by miniak** [comment]
This is now natively supported in [Electron 8](https://github.com/electron/electron/releases/tag/v8.0.0-beta.1)
> IPC between main and renderer processes now uses the Structured Clone Algorithm. #20214

**Comment by miniak** [comment]
in older versions you can do this

main
```
const array = new Float64Array(10)
mainWindow.webContents.send('test', array, array.byteOffset, array.length)
```

renderer
```
ipcRenderer.on('test', (e, array, byteOffset, length) => {
  const array = new Float64Array(array.buffer, byteOffset, length)
  console.log('test', array)
})
```
