### ISSUE TITLE
Mac App Store rejects the build with 5.0.0-beta*

### ISSUE THREAD

**Issue by mulyk** [electron/electron#17197]
* **Electron Version:** 
  * 5.0.0-beta.4

### Rejection Email
Guideline 2.5.1 - Performance - Software Requirements

Your app uses or references the following non-public APIs:

Found private symbol usage.
Symbol: __LSSetApplicationLaunchServicesServerConnectionStatus
From framework: /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
Symbol: _SetApplicationIsDaemon
From framework: /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
Symbols: _pthread_chdir_np, _pthread_fchdir_np, _abort_report_np
From framework: /usr/lib/libSystem.B.dylib
In binary: Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework

The use of non-public APIs is not permitted on the App Store, because it can lead to a poor user experience should these APIs change.

We are constantly reevaluating and identifying non-public APIs that you may have been using for an extended period of time. You should always use public APIs and frameworks and ensure they are up-to-date to prevent this issue in the future

### Additional Information
Version 4 has no problems.

**Comment by MarshallOfSound** [comment]
These API calls appear to have been introduced in https://chromium-review.googlesource.com/c/chromium/src/+/1183624/

**Comment by nornagon** [comment]
@MarshallOfSound the `_LSSetApplicationLaunchServicesServerConnectionStatus` yes, but not:

- `_SetApplicationIsDaemon`
- `_pthread_chdir_np`
- `_pthread_fchdir_np`
- `_abort_report_np`

**Comment by MarshallOfSound** [comment]
Yeah mb, didn't see the others in the report, the others were all introduced recently as well.  E.g. `abort_report_np` --> https://chromium-review.googlesource.com/c/chromium/src/+/1270175

The solution here is probably just comment most of this out 🤔
