### ISSUE TITLE
Possibility to recompile electron with reduced feature set?

### ISSUE THREAD

**Issue by danielgindi** [electron/electron#17204]
### Problem Description
As everybody knows, electron comes with a bundle chromium, nodejs, and the core atom code. In most projects you can get along fine without having support for WebGL, PDFs, WebRTC, Audio apis, codecs and other huge parts of the code.

### Proposed Solution
Allow to specify a set of features (like `enable_pdf`) in `package.json` or a dedicated file (`.electronrc`...), and supply a script that we can run in `npm install` to rebuild electron with the specified flags, instead of take it from the prebuilt binaries.

### Alternatives Considered
Haven't found any except for using alternatives to electron, which we do not want.

**Comment by MarshallOfSound** [comment]
Although this is a nice idea, it's not currently technically feasible.  Everything inside chromium is heavily coupled and things like webgl and webrtc can't just be ripped out.  It also currently takes a number of hours to build Electron from scratch.

Gonna close this out as a won't fix for now.
