### ISSUE TITLE
Electron 5 doesn't have require available on window

### ISSUE THREAD

**Issue by natew** [electron/electron#17208]
* **Electron Version:** 5.0.0-beta.4
* **Operating System:** macOS 10.13.6
* **Last Known Working Electron version:**: 4.0.6

### Expected Behavior

`window.require` exists.

### Actual Behavior

`typeof window.require === 'undefined'`

### To Reproduce

```
git clone https://github.com/electron/simple-samples
cd activity-monitor
npm i electron@5.0.0-beta.4
npm start
```

### Screenshots

![image](https://user-images.githubusercontent.com/12100/53706112-83cfa100-3ddd-11e9-9167-5e217aea6f31.png)

**Comment by MarshallOfSound** [comment]
This is an intended change in behavior and is listed in our breaking changes document.  The default value for `nodeIntegration` changed.

https://github.com/electron/electron/blob/v5.0.0-beta.1/docs/api/breaking-changes.md#planned-breaking-api-changes-50

**Comment by natew** [comment]
Ah, looked all over blog and releases for that and didn't see the breaking changes document. Thank you.
