### ISSUE TITLE
Disable caching in webview

### ISSUE THREAD

**Issue by Rameshv** [electron/electron#1720]
Hi,
   As per this issue #891 **disable chrome BrowserWindow caching**, there is a new flag `--disable-http-cache` introduced to disable caching. But it still caches the content in webview.

I have a embedded http server running inside the electron app, which renders static html(from the directory ) into the webview. So the process is simple, when the user exits the presentation to open another one, it exits the server and open the http in another directory. But some presentation has the files with the same names & extensions. This led chrome to cache its content.

Another interesting issue i found with webview is, it aggressively caches even if i append a cachebuster string  to the url. But the same link with the cachebuster key works fine in the chrome browser(regular mode). So it's an issue in webview only.

So summarize, these are the 2 issues i have encountered regarding webview cache
   1. webview still caches even if there is a `--disable-http-cache` switch
   2. It  caches even with the cachebuster query string in the url

Hope i made this clear. Let me know if you need more info.

Cheers

**Comment by NoxHarmonium** [comment]
I am also having this issue. If there is anything you need to help debug this issue, let me know.

How I currently reproduce it:

1. I load up my electron app for the first time which requests images from an embedded web server.
2. I close my electron app.
3. I alter the image assets.
4. I open the electron app again and observe that the images shown are always the images that were loaded on the first load of the app.

The browser is actually making a request for each image and the web server is responding to the request for each image and sending the image to the browser but the image displayed never changes.

Like the original poster I am using cachebuster urls and the ```--disable-http-cache``` switch.

**Comment by rubenmoor** [comment]
same problem here

**Comment by swimyoung** [comment]
same problem..

**Comment by darrrk** [comment]
:+1:

**Comment by rubencodes** [comment]
Same issue...

**Comment by mzmousa** [comment]
+1

**Comment by dotdotcommadot** [comment]
+1

**Comment by Ascarbek** [comment]
+1
