### ISSUE TITLE
memory leak after a day running

### ISSUE THREAD

**Issue by vrbsm** [electron/electron#17213]
* **Electron Version:**
  * 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5
* **Operating System:**
  * Windows 10 x64
* **Last Known Working Electron version:**:
  * 3.1.4

### Expected Behavior
After a long time running my memory should not keep increasing

### Actual Behavior
After leaving the electron running for a day I realized that my PC was using around 2Gb.

### To Reproduce
$ git clone https://github.com/electron/electron-quick-start
$ npm install
$ npm start || electron .

### Screenshots
![download](https://user-images.githubusercontent.com/9887288/53735216-fcc60b80-3e64-11e9-9dcf-ea937f93ac33.png)

### Additional Information
The memory leak doesn't happen in version 3.x

**Comment by yarcub** [comment]
@vrbsm did you closed this because it was an invalid report?

**Comment by vrbsm** [comment]
this was fixed in version 4.0.6 and up
