### ISSUE TITLE
Load URL with replacement

### ISSUE THREAD

**Issue by PalmerAL** [electron/electron#17228]
### Problem Description

I'd like to be able to load a URL in a webContents without affecting the navigation history - basically, something equivalent to `window.location.replace`.

### Proposed Solution

An option on loadURL might work well, possibly something like this: `webContents.loadURL(url, {replace: true})`

### Alternatives Considered

I couldn't find any way to do this currently, but it's possible I'm missing something.

**Comment by MarshallOfSound** [comment]
@PalmerAL Would `contents.executeJavaScript('window.location.replace("x")')` solve this for you, I'd like to avoid making the API weight of things like `loadUrl` too heavy if it's easy enough to use actual browser APIs for this.

**Comment by PalmerAL** [comment]
@MarshallOfSound I think that would work; an actual API would be a bit nicer, but I can understand if that would add too much complexity to it.

**Comment by codebytere** [comment]
Closing this out in response to the conversation above; i think this may indeed add too much complexity but we can always revisit it if something else comes up!
