### ISSUE TITLE
NativeWindowOpen disables DevTools extension

### ISSUE THREAD

**Issue by orange4glace** [electron/electron#17232]
* **Electron Version:**
4.0.7
* **Operating System:**
Windows 10
* **Last Known Working Electron version:**:
4.0.7

### Actual Behavior
A popup window opened by BrowserWindow which enables __nativeWindowOpen__ and disables __nodeIntegration__ can't utilize DevTools extension like React with an error `Uncaught TypeError: ipcRenderer._sendInternalToAll is not a function,` yet extension tab itself is showing on Devtools.

### To Reproduce
[package.json](https://pastebin.com/wKrJV88v)
[app.js](https://pastebin.com/ZMC6ZZBM)
[index.html](https://pastebin.com/Bc0rCuqK)

### Screenshots
![2](https://user-images.githubusercontent.com/17820596/53806230-c042fe80-3f8f-11e9-89af-7bdcad6c0cd6.PNG)

**Comment by miniak** [comment]
Electron 4 is not supported anymore. Please file a new bug if you can still reproduce the issue with a recent version
