### ISSUE TITLE
How to implement top menu, similar to vscode？

### ISSUE THREAD

**Issue by TonyLiuYan** [electron/electron#17238]
How to implement top menu, similar to vscode,？
as shown in the screenshot below
![_20190306122804](https://user-images.githubusercontent.com/12442097/53856255-2a998480-400c-11e9-86ea-4afd8c9a13db.png)

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
