### ISSUE TITLE
Independent Windows

### ISSUE THREAD

**Issue by sanoopjose** [electron/electron#17230]
* **Electron Version:**
  * 3.0.10
* **Operating System:**
  * macOS 10.14 / Windows 10 (17134.590) / Ubuntu 18.04 x64
* **Last Known Working Electron version:**:
  * N/A

### Expected Behavior
There should be a way to keep the child windows alive even if we close the parent window.

### Actual Behavior
Closing all windows when I close the parent window.

### To Reproduce
Open electron application and shift click on any link. This will open the URL in a child window. Open any link from that window and close the parent window. 

The normal hehaviour is as soon as you cloase the parent window, all child windows aslo getting closed. How do I handle child windows independently?

**Comment by MarshallOfSound** [comment]
@sanoopjose You can intercept the `new-window` event and construct your own window and own that instead of letting Electrons default behavior play out.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
