### ISSUE TITLE
Changing the devtools theme buging the app Electron 4.0.7

### ISSUE THREAD

**Issue by ThiagoMartinsSaraiva** [electron/electron#17237]
* **Electron Version:**
4.0.7
* **Operating System:**
Windows 10 
* **Last Known Working Electron version:**
4.0.7

### Expected Behavior
The changes made at devtools preferences should be applied, and when applied, should apply only to devtools.

### Actual Behavior
Changing the devtools theme, doesn't reload the UI, it only worked when I closed and reopened the app. And when I opened the app again, the whole application were black themed.

### To Reproduce

$ git clone https://github.com/ThiagoMartinsSaraiva/testing-electron
$ electron . 

### Screenshots

This is what I saw when I ran the application just after changed the devtools theme:
![electron-issue1](https://user-images.githubusercontent.com/24665331/53853268-7ebc4e80-3fa3-11e9-8e89-0210eb43d64b.png)
When I change the devtools theme, nothing happens.
![electron-issue2](https://user-images.githubusercontent.com/24665331/53853271-82e86c00-3fa3-11e9-9698-b91f00e41c0e.png)

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
