### ISSUE TITLE
Electron Helper crashes if localStorage size is exceeded

### ISSUE THREAD

**Issue by duxthefux** [electron/electron#17240]
* **Electron Version:**
  * 4.0.6
* **Operating System:**
  * macOS 10.14
* **Last Known Working Electron version:**:
  * none

### Expected Behavior
Some proper error handling if size of sessionStorage or localStorage is exceeded like Chrome is usually telling you with an error that you've exceed the size.

### Actual Behavior
Electron Helper crashes and one has to reload to get webView up and running again

### To Reproduce
Open DevTools in electron and run
```
object = [];
for(i = 0; i < 10000000; i++){
var j = {a : "sssssoooooooooooooooooommmmmmmmmme sssssssssssssssstring sssssoooooooooooooooooommmmmmmmmme sssssssssssssssstring sssssoooooooooooooooooommmmmmmmmme sssssssssssssssstring sssssoooooooooooooooooommmmmmmmmme sssssssssssssssstring sssssoooooooooooooooooommmmmmmmmme sssssssssssssssstring"}

object.push(j)
}
try {
localStorage.setItem("a", JSON.stringify(object));
} catch(e){
}
```

### Screenshots
<img width="1461" alt="bildschirmfoto 2019-03-06 um 13 18 26" src="https://user-images.githubusercontent.com/6758162/53880992-c4643000-4012-11e9-9306-b07edf3f5ca2.png">

### Additional Information
If you checkout the running electron processes you'll see that one of the helper processes dies.

I tried running app with `export ELECTRON_ENABLE_STACK_DUMPING=true` and `export ELECTRON_ENABLE_LOGGING=true` but does not give more output than normal.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
