### ISSUE TITLE
Cannot write to stderr

### ISSUE THREAD

**Issue by remss** [electron/electron#17244]
* **Electron Version:**
  * 4.0.7
* **Operating System:**
  * Windows 10 (1803)
* **Last Known Working Electron version:**:
  * None

### Expected Behavior
A call to process.stderr.write("message") or console.error("message") from the main process should write "message" to stderr

### Actual Behavior
The "message" is written to stdout

### To Reproduce
```
// main.js
process.stderr.write('message from process.stderr.write')
console.error('message from console.error')
```

```
// testme.js
const { spawn } = require('child_process');

const cmd = spawn('node_modules\\.bin\\electron.cmd', ['.']);

cmd.stdout.on('data', (data) => {
  console.log(`stdout << ${data}`);
});
cmd.stderr.on('data', (data) => {
  console.log(`stderr << ${data}`);
});
```

Then run `node testme.js`

Output is
```
stdout << message from process.stderr.write
stdout << message from console.error
```

### Additional Information

The same issue occurs in the renderer process

**Comment by danielweck** [comment]
Same on Electron v5

**Comment by westhom** [comment]
Also experiencing this on Windows 10, Electron v7.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by remss** [comment]
The bug is still present in Electron 8.0.1 (Windows 10 1909)
Here is a repository to reproduce the issue => https://github.com/remss/electron-stderr-issue

**Comment by pitizzzle** [comment]
Would be nice to see this fixed :)

**Comment by remss** [comment]
@pitizzzle @dakeshi @westhom Give it a 👍, it may improve the visibility of this issue in triage...

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
