### ISSUE TITLE
Windows created with nativeWindowOpen do not have any on* event handlers defined

### ISSUE THREAD

**Issue by abettadapur** [electron/electron#17248]
* **Electron Version:**
4.0.3
* **Operating System:**
MacOS 10.4.2
* **Last Known Working Electron version:**:
N/A

### Expected Behavior
When calling `window.open` with the `nativeWindowOpen` flag enabled, I expect to be able to attach event handlers to the `onload` and `onbeforeunload/onclose` events.

### Actual Behavior
All of the event handlers except for `onerror` are null. Therefore, I cannot attach the necessary handlers.

### To Reproduce
1. Turn on `nativeWindowOpen`
2. `const newWindow = window.open("", "_blank", "");`
3. `newWindow.onload = () => {...} //onload is not defined`

![image](https://user-images.githubusercontent.com/2415669/53903157-d2588780-3ff7-11e9-8e1d-e0baf3bd4b16.png)

See https://github.com/abettadapur/electron-quick-start/tree/nativeWindowOpen for a quick example

**Comment by abettadapur** [comment]
Has anyone had a chance to take a look at this?

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
