### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by iKBAHT** [electron/electron#17241]
* **Electron Version:**
from 5.0.0-beta.5 to 5.0.0-beta.1
* **Operating System:**
macOS 10.14.3
* **Last Known Working Electron version:**:
4.0.7

### Problem
Build and pack passed well, but after run app, I see an error in console `Uncaught ReferenceError: require is not defined - at Object.electron - at __webpack_require__`.

### Screenshots
<img width="272" alt="screenshot 2019-03-06 at 15 20 05" src="https://user-images.githubusercontent.com/922404/53880942-69870480-4023-11e9-8591-d0e140675f23.png">

### Additional Information
We use Typescript, electron-builder, webpack.

**Comment by MarshallOfSound** [comment]
The default for nodeIntegration changed from true to false as per our breaking changes document.

**Comment by iKBAHT** [comment]
How can I find the breaking changes document?

**Comment by MarshallOfSound** [comment]
https://github.com/electron/electron/blob/master/docs/api/breaking-changes.md

**Comment by iKBAHT** [comment]
Ok, I found the [document](https://github.com/electron/electron/blob/master/docs/api/breaking-changes.md). @MarshallOfSound thank you.

**Comment by bokele** [comment]
https://github.com/electron/electron/blob/master/docs/api/breaking-changes.md

const w = new BrowserWindow({
  nodeIntegration: {
    webviewTag: true
  }
})

**Comment by bokele** [comment]
in your index.js 

const w = new BrowserWindow({
  webPreferences: {
    nodeIntegration: true
  }
})

**Comment by Sanjit1** [comment]
You could use Browserify to fix your issue, had it been a web page or a website. But since you are using Electron to render html, you just need to set node integration to true under web preference: like shown [here](https://github.com/Sanjit1/WizardMirror/blob/master/main.js#L16).

**Comment by tolbxela** [comment]
> in your index.js
> 
> const w = new BrowserWindow({
> webPreferences: {
> nodeIntegration: true
> }
> })

Thanks! Have solved my problem.

**Comment by smprime** [comment]
npm i @angular-devkit/build-angular -D

**Comment by 873261648** [comment]
Need to change webPreferences.nodeIntegration to true when new BrowserWindow
`mainWindow = new BrowserWindow({
        width: 1000,
        height: 600,
        webPreferences: {
            nodeIntegration: true
        }
    });`

**Comment by adnan00733** [comment]
Thanks @bokele You are a life saver. :)

**Comment by btargac** [comment]
setting `nodeIntegration` to true is the easy way, bu keeping it false is more secure as documentation tells, I ve found this https://stackoverflow.com/questions/52236641/electron-ipc-and-nodeintegration that may help future readers.

**Comment by mahdisalmanzade** [comment]
actually i added nodeIntergration  = true but dosent work still

**Comment by t1g3r01** [comment]
@tolbxela Thanks a lot mate

**Comment by the94air** [comment]
It didn't work for me because `webPreferences.contextIsolation` was set to true. Be careful when setting that option to false though https://www.electronjs.org/docs/tutorial/context-isolation#security-considerations.

**Comment by brntsllvn** [comment]
Assuming electron 12.0.0

set `contextIsolation: false`

Something like...
```
webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
      enableRemoteModule: true,
    }
```

reference: https://stackoverflow.com/a/66455544/4097181

**Comment by ruymon** [comment]
@brntsllvn  Adding 
```js
webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
      enableRemoteModule: true,
    }
```

Works like a charm!! Thing is, do these other properties affect your application in any way?


Regards,

**Comment by eric-burel** [comment]
Hi guys, any idea how to debug which package/piece of code is triggering this error? Proposed solutions are hacks, they lead to an insecure behaviour, the app needs an actual update to have a more secure behaviour. But the problem is that it's quite difficult to identify the faulty code.

**Comment by btargac** [comment]
where do you get this error ? I guess it is on runtime ? if you can open devtools on the running app then console error should contain the required information about the stack trace with the actual package causing it

**Comment by eric-burel** [comment]
I'll try to share a screen but it seems to be obsfuscated by webpack dev server, despite having source maps. I'll check in production if the error is clearer.
For instance this issue may appear with [electron-log (fix is documented hopefully)](https://github.com/megahertz/electron-log/blob/master/docs/node-integration.md)
