### ISSUE TITLE
Registering global shortcuts not working from v5.0.0-beta.3

### ISSUE THREAD

**Issue by ErnestoGarciaGenesys** [electron/electron#17246]
* **Electron Version:**
  * v5.0.0-beta.3 - v5.0.0-beta.5
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**:
  * v5.0.0-beta.2

### Expected Behavior
This should work, and registered must be assigned true:

    registered = globalShortcut.register("Super+Alt+Up", function () { console.log("hotkey!!")})

### Actual Behavior
Shortcut is not registered, for no key combinations as far as I can tell. Return value is always false.

### To Reproduce
Just run the code line above.

**Comment by brenca** [comment]
I can confirm that this is happening, there is an upstream partial fix for this, I'll post a followup fix upstream to make things work a 100%, and then I'll backport those fixes to master and `5-0-x`.
