### ISSUE TITLE
Provide API for accessing subframes from `webContents`

### ISSUE THREAD

**Issue by samuelmaddock** [electron/electron#17252]
### Problem Description

As a test author, I'd like to be able to interact with subframes of a renderer process in a remote `BrowserWindow` (i.e. execute JavaScript).

### Proposed Solution

Adding a `webFrame` proxy API to the `webContents` API could offer a complete solution to interacting with frames in the renderer process. The following type definitions would be an example of this.

```ts
/**
 * Proxy for `webFrame` renderer API.
 * Could partially implement `webFrame` API.
 */
interface WebFrameProxy {
  /** Provide mappings to methods for getting subframes. */
  findFrameByRoutingId(routingId: number): Promise<WebFrameProxy>

  /** Example method which would run in the appropriate frame. */
  executeJavaScript<T>(code: string, userGesture: boolean): Promise<T>
}

interface WebContents {
  /** Top-level `webFrame` instance of `WebContents` instance. */
  webFrame: WebFrameProxy
}

// Internally, webFrame-related methods could map to the top-level webFrame.
// See `asyncWebFrameMethods` in web-contents.js for other methods.
const webContents: WebContents
webContents.executeJavaScript =
  webContents.webFrame.executeJavaScript.bind(webContents.webFrame)
```
### Alternatives Considered

For a less complete solution, additional methods could be added as needed to the `webContents` API for interacting with subframes.
```ts
webContents.executeJavaScriptInFrame(frameRoutingId: number, code: string, userGesture: boolean): Promise<T>
```

### Additional Information

This could be a potential fix for #14350 if the `WebFrameProxy` were to implement a `executeJavaScriptInIsolatedWorld` proxy method.

**Comment by cumajkeee** [comment]
@samuelmaddock, is it possible to add in setSpellCheckProvider method in proposed proxy object? It would solve my issue where I'd like to have spellchecker works in nativeBrowserWindow.
