### ISSUE TITLE
webContents.print() callback always return false

### ISSUE THREAD

**Issue by popod** [electron/electron#17265]
* **Electron Version:**
  * 4.0.7
* **Operating System:**
  * macOS Mojave
* **Last Known Working Electron version:**:
  * 3.0.14

### Expected Behavior

When calling

```js
webContents.print({}, function (success) {
  console.log(success)
})
```

`success` always return `false`, even when the page is printing correctly !

### Actual Behavior

The `webContents.print({}, callback)`, should return `true` when the print is successful !

### To Reproduce

```sh
$ git clone https://github.com/popod/electron-quick-start.git
$ cd electron-quick-start
$ git checkout print-bug-1
$ npm install
$ npm start
```

When the application is run, the print window is displayed and pressing the print button launch the printer, but the callback always return `false` (this is displayed in the devTools console)

**Comment by popod** [comment]
Hi @codebytere !

Thanks for your PR about this issue, but why closing it ? The problem is still present in Electron 4.x.x and 5.x.x and even in 6.x.x.

**Comment by codebytere** [comment]
@popod the issue is closed, per typical PR convention, when the issue is solved in master. We plan to bckport this to 6/5/4 at some point soon, so please be patient just a bit longer and we'll have it fixed!

**Comment by popod** [comment]
Tested with Electron `5.0.5` and this seems to be fixed ! Thanks
