### ISSUE TITLE
Opened Flash context menu makes application unresponsive

### ISSUE THREAD

**Issue by christophpre** [electron/electron#17292]
* **Electron Version:**
  * 4.0.6 and 5.0.X
* **Operating System:**
  * macOS 10.13.6 **AND** Windows 10 (1809) (Linux not tested)

### Expected Behavior
If I right-click in a Flash application, the Flash contextmenu should stay open indefinitely and the Flash application should remain operable.

### Actual Behavior
If I right-click in a Flash application, the Flash contextmenu opens, but if you wait ~1 minute, the menu is closed and the Flash application becomes unresponsive.

### To Reproduce
1. Install current Flash Player for Chrome on your system (PPAPI - Flash Player 32.0.0.142)
2. Run the Electron Fiddle example from my gist https://gist.github.com/christophpre/f22145ced82b5ad1c54d0f5e0ff295ae
3. Right-click on the Flash content in the Flash about page, that is automatically loaded in the BrowserWindow, the Flash context menu should be open now
4. Wait ~1-2 minutes until the Flash context menu automatically closes
-> The Flash application is now unresponsive and the Flash context menu cannot be opened again

### Additional Information
Also tested this with current Google Chrome (Version  72.0.3626.119), the problem does not appear there. May be related to #13934, but I encountered this with current Electron Versions 4.0.6 und 5.0.X. I can consistently reproduce this with my gist.

**Comment by GhostlyDark** [comment]
Fixed by #21169 
Should land in v5.0.13 and v6.1.5.
(Already fixed in v7.1.2 and v8.0.0-beta.3, but one can't test this on the flash context menu because #20744)

**Comment by christophpre** [comment]
Tested in 5.0.13 and 6.1.7. Closing this issue.
