### ISSUE TITLE
Failing test on C74: devtools window can receive and handle menu events

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#17305]
https://windows-ci.electronjs.org/project/AppVeyor/electron-67iac/builds/55159
https://windows-ci.electronjs.org/project/AppVeyor/electron-i8wjp/builds/55161

```
not ok 908 webContents module devtools window can receive and handle menu events
  AssertionError: value should eventually become the pasted value: expected '' to equal 'test value'
      at Context.<anonymous> (C:\projects\src\electron\spec\api-web-contents-spec.js:422:22)
```

This only occurs on windows, we believes C74 has brought to light a previously flaky spec

**Comment by nornagon** [comment]
Going to guess this is no longer relevant.
