### ISSUE TITLE
Electron app with accessibility permissions hangs/freezes a few second on startup

### ISSUE THREAD

**Issue by ddavy** [electron/electron#17314]
* **Electron Version:**
  * 4.0.7
* **Operating System:**
  * macOS 10.14.2
* **Last Known Working Electron version:**:
  * Unknown

### Expected Behavior
Electron app with Accessibility permissions should start without hanging.

### Actual Behavior
Electron app with Accessibility permissions hangs or freezes macOS for a few seconds before opening

### To Reproduce
Package an electron app (eg. [electron-quick-start](https://github.com/electron/electron-quick-start) with electron-packager or [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate) with built-in electron-builder) and give the electron app accessibility permissions (on macOs: Security & Privacy > Privacy > Accessibility). Open the app and it will hang/freeze for a few seconds before opening. 

### Screenshots
/

### Additional Information
I need the accessibility permissions to simulate a keyboard event using [robotjs](https://github.com/octalmage/robotjs). Sometimes the app seems to have lost its accessibility permissions and I have to delete and add the app again to the accessibility list.
This bug does not seem to appear on other electron apps like vscode/slack/skype. Maybe it has something to do with signing?

Thanks!

**Comment by nornagon** [comment]
If you're up for it, could you try taking a sample of the app with Activity Monitor while it's frozen?

<img width="752" alt="Screen Shot 2019-03-11 at 4 27 48 PM" src="https://user-images.githubusercontent.com/172800/54164663-af284080-441a-11e9-9202-a9216dd24605.png">

**Comment by ddavy** [comment]
I found out that it had something to do with signing. After signing the application, it stopped freezing during startup when the accessibility features were enabled. Don't know why macOS behaves like this, but at least it can be easily fixed. This issue can be closed. Thanks!

**Comment by sourabhverificient** [comment]
This is occurring for Signed app as well , Do we have any fix on this ?
