### ISSUE TITLE
Windows: Frameless window focused shadow

### ISSUE THREAD

**Issue by vasiltabakov** [electron/electron#17329]
On Windows 10 when a window is focused it has a wider/darker shadow. 

In Electron this works fine with normal windows, but not when the window is frameless. 

Still in Windows 10 there are many applications which are 'frameless' yet have better shadow when focused. One example would be the 'Edge Browser'. Here's a quick test I did with MS Paint (starts with the window unfocused, notice how when focused the shadow (and border) changes):

![2019-03-11_14-08-39](https://user-images.githubusercontent.com/1178309/54123530-af1f4500-4408-11e9-8d45-68d0a1dd068c.gif)

Is there a way to "emulate" this with the current Electron APIs? Or maybe is there a way to hide the Windows title bar yet not "mark" the Window as 'frameless'?

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).

**Comment by vasiltabakov** [comment]
This is a feature request really. Please reopen. There's no way to achieve what native windows do with the current Electron API.

**Comment by hz0324** [comment]
@vasiltabakov Have you found a way to do so?

**Comment by vasiltabakov** [comment]
@hz0324 not really, I can think of workarounds, but can wait until this is resolved officially.. altho.. I don't really know why this was closed.

**Comment by hz0324** [comment]
@vasiltabakov I am working on a computer project, It is a eBook reader.

**Comment by Mercurial** [comment]
I have the same question

**Comment by vasiltabakov** [comment]
@sofianguy reopen this!
