### ISSUE TITLE
using node-windows my app

### ISSUE THREAD

**Issue by Firlfire** [electron/electron#17327]
Hi,

I want to build an installer with electron-builder to distribute my app.
This app have to use node-windows to create a Windows service from the electron Window or Tray Menu.

For the moment, my service juste run an express server on port 8080 (just to test it).

My problem is that it works in development (launch app, install service, go on Chrome/Firefox/...) on localhost:8080, uninstall my service) with _npm start_ .

When I build it with your electron-builder, the unpacked setup and the installer can install the service with the 'running' status, but my localhost:8080 don't works

You can find my whole code below and a part of my package.json

Can you help me please ?

**package.json**
`{
  // ommited
  "scripts": {
    "start": "electron ./src/electron.js",
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "build --win"
  },
  "build": {
    "asar": false,
    "files": [
      "!logs/",
      "!nbproject/"
    ],
    "win": {
      "target": [
        "nsis"
      ],
      "requestedExecutionLevel": "requireAdministrator"
    },
    "mac": {
      "target": [
        "dmg"
      ]
    },
    "linux": {
      "target": [
        "AppImage"
      ]
    },
    "nsis": {
      "oneClick": false,
      "perMachine": true,
      "allowElevation": true
    }
  },
  // omitted
}`

**src/electron.js**
```
'use strict';
const { app, BrowserWindow, Tray, Menu } = require('electron');
const { Service } = require('node-windows');
const path = require('path');

let appShell;
let appUrl = 'file://' + __dirname + '/index.html';
let service;

function createElectronShell() {
 appShell = new BrowserWindow({ width: 800, height: 600 });
 appShell.loadURL(appUrl);
 appShell.on('closed', () => { appShell = null; });

 const template = [
   {
      label: 'Service',
      submenu: [
      {
        label: 'Start service',
        click() {
          createService();
        }
      },
      {
        label: 'Stop service',
        click() {
          stopService();
        }
      },
      {
        label: 'Uninstall service',
        click() {
          uninstallService();
        }
      }
    ]
   }
 ];
 const menu = Menu.buildFromTemplate(template)
 Menu.setApplicationMenu(menu);
}

app.on('ready', createElectronShell);
app.on('window-all-closed', () => {
   if (process.platform !== 'darwin')
      app.quit();
   stopService();
});

app.on('activate', () => {
   if (appShell == null)
      createElectronShell();
});

function createService() {
 if (!service) {
   service = new Service({
      name: 'Test service',
      description: 'A simple node js listener',
      script: path.join(__dirname, 'listener.js'),
      env: {
        name: 'HOME',
        value: process.env['USERPROFILE']
      }
   });
    service.on('install', () => {
      service.start();
    });
    service.install();
  }
  else {
    service.start();
  }
}

function stopService() {
  if (service) {
    service.stop();
  }
}

function uninstallService() {
  if (service) {
    service.uninstall();
  }
}
```

**src/listener.js**
```
const express = require('express');
const app = express();

app.get('/', (req, res) => {
   res.send('<h1>Server is up and running on port 8080</h1>');
});

app.get('*', (req, res) => {
   res.send('<p>Server is running on port 8080</p>');
});

app.listen(8080, () => {
   console.log('The server is running in port 8080');
});
```

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
