### ISSUE TITLE
TouchBarSegmentedControl - mutating segments leaves previous icon or label

### ISSUE THREAD

**Issue by MarcusNoble** [electron/electron#17322]
* **Electron Version:**
  * 4.0.9
* **Operating System:**
  * macOS 10.13.6
* **Last Known Working Electron version:**:
  * N/A

### Expected Behavior
When replacing the `segments` array of a `TouchBarSegmentedControl` I expect the control to be completely replaced with the new values specified.

### Actual Behavior
When a `TouchBarSegmentedControl` is created with a control that just has an icon and the segments are replaced with one that just has a label both the initial icon and the new label are show. The same happens when going from label to icon.

### To Reproduce
Repo example: https://github.com/MarcusNoble/electron-TouchBarSegmentedControl-bug/blob/42a5b8f0226b80a4900f21bc69d21cf25dcd4df7/main.js#L49-L67

```sh
$ git clone https://github.com/MarcusNoble/electron-TouchBarSegmentedControl-bug.git
$ npm install
$ npm start
```

### Screenshots
1. Start with a control that just has an icon:
![image](https://user-images.githubusercontent.com/4919969/54088628-f00b5100-4357-11e9-8ea2-21e3f7f47b07.png)

2. Replace the control with one that just has a label. The icon remains (even if set to undefined or null):
![image](https://user-images.githubusercontent.com/4919969/54088630-f3064180-4357-11e9-84b6-8f83ddce163e.png)

3. Replace again with one that has a different icon. The label remains.
![image](https://user-images.githubusercontent.com/4919969/54088632-f8fc2280-4357-11e9-9820-1aaf5eaac476.png)

**Comment by MarshallOfSound** [comment]
@MarcusNoble Relatively straight forward fix --> https://github.com/electron/electron/pull/17323

We weren't accounting for this case (where `segments` gets replaced with a non-similar structure of segment)

**Comment by MarcusNoble** [comment]
Wow! That was fast! Thank you!

FYI: It's how VS Code does it as they pre-build several segmented groups to re-use.
