### ISSUE TITLE
Search doesn't work in case if page with webview component reloaded

### ISSUE THREAD

**Issue by mchusovlianov** [electron/electron#17333]
* **Electron Version:**
   * v4.0.8
* **Operating System:**
  * MacOS 10.14.3
* **Last Known Working Electron version:**:
  * v2.0.18

### Expected Behavior
findInPage works after reload page with webview component

### Actual Behavior
findInPage doesn't work after reload page. Found callback receive event with no matches

### To Reproduce

- go to page with findInPage functionality
- go to any other page
- go to page with findInPage functionality  again and try to search something

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
