### ISSUE TITLE
Provide API to open native OS emoji picker in ElectronJS

### ISSUE THREAD

**Issue by pashvin** [electron/electron#17358]
### Problem Description

Windows 10 and Mac both now offer native emoji picker
Windows 10 short cut is "Win key + ;"
Mac short cut is "Ctrl+Opt+space"
Most of web app uses own emoji implementation and can't keep up with latest emoji support and each implementation look non native.
But Electron is committed to bring native OS user experience so it will be nice if we provide API to bring native emoji picker on Mac and Windows 10.

### Proposed Solution

Provide API to bring native Mac and Windows 10 emoji picker.
Just for reference, adding following link of Chrome code. Chrome allows to right click and click "emoji" to open this keyboard. Electron does not offer right click menu and each developer may have diff requirement so this is not a proposal to add right click menu like Chrome but provide API and developer will use their own way. For example, I am working on chat application so I can put button(emoji) next to chat input text box and clicking on emoji button , I can put focus back to text box and ask Electron to open native emoji picker by calling API

Ref code: 
https://cs.chromium.org/chromium/src/ui/base/emoji/emoji_panel_helper_win.cc?dr=CSs&sq=package:chromium&g=0&l=20

https://cs.chromium.org/chromium/src/ui/base/emoji/emoji_panel_helper_mac.mm?dr=CSs&sq=package:chromium&g=0&l=17

**Comment by codebytere** [comment]
ooh this is a fun one...i'll try to spike on it soon!
