### ISSUE TITLE
electron v3.0.8 loadFile options not work

### ISSUE THREAD

**Issue by wanglk666** [electron/electron#17365]
i want to loadFile the html , and give some parameter to it , electron v3.0.8 loadFile options not work, but v4.0.3 can get it.

main process:
![image](https://user-images.githubusercontent.com/33086234/54264044-2c83ba80-45ad-11e9-942b-f0e19e5eab87.png)

![image](https://user-images.githubusercontent.com/33086234/54264081-3c9b9a00-45ad-11e9-9bc8-ccb180b05985.png)

renderer process:
![image](https://user-images.githubusercontent.com/33086234/54264133-5a68ff00-45ad-11e9-9307-3371893f0086.png)

console:
---> 
result is ''

**Comment by MarshallOfSound** [comment]
@wanglk666 The `options` object that you can pass to `loadFile` was only introduced in `4.0`

**Comment by wanglk666** [comment]
ok, thanks
