### ISSUE TITLE
Blocked `beforeunload` event but the window can not be closed

### ISSUE THREAD

**Issue by wslx520** [electron/electron#17364]
* **Electron Version:**
  * 3.0.9
* **Operating System:**
  * windows 10 x64

### Expected Behavior
Hope I can close the window

### Actual Behavior
Electron blocked the `beforeunload` messege and throw an error, but the window was still there

### To Reproduce
There is a webchat page, it has a `beforeunload` event listener:
```javascript
window.onbeforeunload = function() {
                return 'Do you want to leave this page?'
            }
```
it works well in browser, but in Electron, it got a error:
![image](https://user-images.githubusercontent.com/1026909/54259188-e07e4900-459f-11e9-9fc4-ab5072ade9b1.png)

**Blocked attempt to show a 'beforeunload' confirmation panel for a frame that never had a user gesture since its load.**

but the window still stay there and can not be closed anyway

I can not modify the web chat page, i have to solve it by Electron's way 😂

**Comment by joelrogo** [comment]
Same issue

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by laclance** [comment]
same issue with  "electron": "^9.1.1"

**Comment by bradisbell** [comment]
Same thing with Electron v25.  The blocked alert is fine... that's consistent with the browser itself.  But, some way to show an alert would be useful.
