### ISSUE TITLE
Electron spawns extra background processes when closed before loading finishes

### ISSUE THREAD

**Issue by casuaI** [electron/electron#17375]
* **Electron Version:**
  * 4.0.7
* **Operating System:**
  * Windows 10 (1803)
* **Last Known Working Electron version:**
  * None

### Expected Behavior
If Electron window had been closed before the main.js file (program) was loaded all started proccesses must be terminated.

### Actual Behavior
When Electron window is closed before the program was loaded an extra background proccess (probably renderer) will be started.

### To Reproduce
Run Electron app and close it immediately before the content was loaded.
Tested with the quick start example (https://github.com/electron/electron-quick-start) and an HTML5 website.

### Screenshots
![electronbug](https://user-images.githubusercontent.com/48362003/54291874-d4b27700-45df-11e9-86a7-6679b935301b.png)

### Additional Information
None

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
