### ISSUE TITLE
Menu role "recentDocuments" doesn't work

### ISSUE THREAD

**Issue by WarWithinMe** [electron/electron#17388]
* **Electron Version:**
  * 4.0.0 - 4.1.0
* **Operating System:**
  * macOS 10.14.2
* **Last Known Working Electron version:**:
  * 3.1.6

### Expected Behavior
The "Open Recent" menu should work just like any other application.

### Actual Behavior
The "Open Recent" menu is greyed out and unable to click.

### To Reproduce
Just add a `recentDocuments` menu item to the menu bar

### Screenshots
3.1.5:
![9AB36EF4-6274-4F61-9C29-82924F4BC513](https://user-images.githubusercontent.com/567110/54403492-27d51880-470b-11e9-9674-93c3bbd57686.jpg)

After 4.0:
![7FD96935-796F-4947-A0AC-8ED2243D3B75](https://user-images.githubusercontent.com/567110/54403504-31f71700-470b-11e9-89d5-93c37d2691a1.jpg)

### Additional Information
The `recentDocuments` menuItem simply fails to work after an upgrade to 4.0, without any code modification. 

The `Clear Menu` item shown in the v3.1.5 screenshot is a custom submenu of `recentDocuments`. The issue still exists even if I leave the submenu of `recentDocuments` empty.

**Comment by codebytere** [comment]
I'll check into this today!

**Comment by codebytere** [comment]
@WarWithinMe i can't reproduce this; it's not showing up grayed out for me and updated correctly with recent items once they exist.

I'm going to need a more specific repro in order to continue pursuing this issue, i think.

**Comment by WarWithinMe** [comment]
@codebytere I found the cause. In MacOSX, and electron >= 4.0, if I call `Menu.setApplicationMenu()` before app's `ready` event is fired, the `recentDocuments ` menu will fail to work as I described above.

I'm not sure if it's intend behaviour, but right now, I will just call `Menu.setApplicationMenu()` only after app is ready.

**Comment by codebytere** [comment]
Great! thanks for the follow-up. Yes, this is intended behavior [as documented](https://electronjs.org/docs/api/menu#menusetapplicationmenumenu):
> Note: This API has to be called after the ready event of app module.
