### ISSUE TITLE
The webview is destroyed automatically

### ISSUE THREAD

**Issue by VisualSJ** [electron/electron#17381]
* Output of `node_modules/.bin/electron --version`: 3.0.9
* Operating System (Platform and Version): MacOS 10.13.6
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Expected Behavior**
1. Create a webview Insert into the document.body. And run a lot of js scripts in it.
2. Remove the webview from the body.
3. Put it back in the document.body.

I want the results of the previous run to continue in the webview.

**Actual behavior**
The webview is destroyed. All the data in there is lost. And there is no opportunity for us to store data.

issue: https://github.com/electron/electron/issues/16372

demo: https://github.com/VisualSJ/electron-bug-1

What's the status of this issue now? Is there a plan?

**Comment by MarshallOfSound** [comment]
@VisualSJ Please do not raise duplicate issues, especially not duplicates of your own issue

**Comment by VisualSJ** [comment]
Sorry. I'm not sure if anyone is following that question. It seems to have gone unnoticed.

In fact, I just want to know the question: what is the current situation? Is there any plan.

**Comment by MarshallOfSound** [comment]
@VisualSJ We are not a support team, if the issue has no one assigned to it, it's unlikely anyone is working on it

**Comment by VisualSJ** [comment]
This problem is now seriously affecting the program I am developing. T.T
What do I need to do to get people's attention?

T.T When the webview was destroyed, it didn't give me any opportunity to deal with it
