### ISSUE TITLE
Electron Tutorial: Broken Image on Windows Taskbar Chapter

### ISSUE THREAD

**Issue by baltzyee** [electron/electron#17387]
Hi guys, I was reading the electron tutorial and on the [**Windows Taskbar** chapter](https://electronjs.org/docs/tutorial/windows-taskbar#windows-taskbar), and it appears that there is a **missing/broken** image:

![chrome_yChLFkYrTe](https://user-images.githubusercontent.com/48568695/54387634-959a2980-46a4-11e9-9b6d-5b3fea8457a8.png)

This is the broken link to the image that you use: http://i.msdn.microsoft.com/dynimg/IC420539.png
It does not load. The other 2 images in the tutorial load normally. It is annoying because the website will not stop loading, because of the broken image URL.

This is what the broken image URL shows if you click it:
![chrome_MW9tlHsNfj](https://user-images.githubusercontent.com/48568695/54387578-726f7a00-46a4-11e9-9317-79d50abceb3e.png)

It is a weird error. It happens on all my browsers Chrome, Firefox and Edge. 
Maybe you are use wrong URL link? because other 2 image URLs work.
Thanks for the tutorial! 
Chieers, Mikael

**Comment by baltzyee** [comment]
Show file history and @MarshallOfSound is last commit. Maybe you know more and are better than me to help my friend 😊

File: https://github.com/electron/electron/blob/master/docs/tutorial/windows-taskbar.md
History: https://github.com/electron/electron/commits/master/docs/tutorial/windows-taskbar.md

**Comment by baltzyee** [comment]
I search issue repository for *windows taskbar image* and i find this:

1. https://github.com/electron/electron/pull/15923
2. https://github.com/electron/electron/pull/6497

But https://github.com/electron/electron/pull/15923 fixes URL problem and image loads ok. But it closed. Why it was? Maybe should I make new one to fix it?

Correct image URL from https://github.com/electron/electron/pull/15923: https://i-msdn.sec.s-msft.com/dynimg/IC420539.png

This is what it shows:

![IC420539](https://user-images.githubusercontent.com/48568695/54390762-f5480300-46ab-11e9-9af7-030bbfacd725.png)

@MarshallOfSound and friends tell me if i can help you out 😊

**Comment by codebytere** [comment]
if you can find a correct image we'd gladly take a pull request!

**Comment by baltzyee** [comment]
@codebytere Thank you aswering me! This request uses the corect image https://github.com/electron/electron/pull/15923, maybe i should ask the request person @klaussinani how to do myselve or maybe he can do it himselve because I don't have much time because of work 😊

**Comment by baltzyee** [comment]
hmm i dont know how to use GitHub so well, so maybe @klaussinani can look at it. Thank you my friend!

**Comment by klaussinani** [comment]
Happy to help out : )
Should I create a new PR or update the existing one (#15923) to reference the current issue?

@baltzyee @codebytere

**Comment by baltzyee** [comment]
New one looks ok, but maybe @codebytere dissagrees, so should do what you guys think is the best option 😄
