### ISSUE TITLE
Electron fails to copy electron/spec/fixtures/asar/a.asar

### ISSUE THREAD

**Issue by topecongiro** [electron/electron#17389]
* **Electron Version:**
  * 4.1.0
* **Operating System:**
  * Tested on Windows 10 and macOS 10.14.3
* **Last Known Working Electron version:**:
  * None
### Expected Behavior
Copying a directory of electron succeeds.

### Actual Behavior
Electron fails to read a certain directory:
```
Error: Invalid package electron/spec/fixtures/asar/web.asar
    at createError (ELECTRON_ASAR.js:146:17)
    at Object.fs.lstat (ELECTRON_ASAR.js:265:23)
    at process.nextTick (ELECTRON_ASAR.js:300:33)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```
### To Reproduce

package.json:
```json
{
  "name": "copy-electron",
  "version": "1.0.0",
  "main": "index.js",
  "private": true,
  "dependencies": {
    "fs-extra": "^7.0.1",
  }
}
```

index.js:
```js
const fs = require('fs-extra');

// First download from https://github.com/electron/electron/archive/v4.1.0.zip and extract it
(async () => {
    try {
	await fs.copy('electron-4.1.0', 'electron');
    } catch (e) {
        console.log(e);
    }
})();
```

### Additional Information

Running the above script with Node.js succeeds without any problem, so this seems to be an issue related to Electron.
cc https://github.com/electron/electron/issues/10816.

**Comment by MarshallOfSound** [comment]
@topecongiro This is not a bug rather it is expected behavior, when Electron encounters an `asar` file it tries to read it as a folder/container instead of treating it as a "file".  If you want to disable this behavior you have to use `original-fs` or set `process.noAsar` to `true`

**Comment by topecongiro** [comment]
@MarshallOfSound Thank you for your response. I am fairly new to Electron and didn't know the behavior.

**Comment by topecongiro** [comment]
@MarshallOfSound Hi, I have tried setting `process.noArch = true` in macOS and running the above script. I expected the script to finish within a few seconds, but instead it hanged forever. It seems to me that `Electron` cannot properly handle `asar` file correctly in macOS when `process.noArch = true` and somehow gets stuck in an endless loop. Would you mind having a look when you have time?
