### ISSUE TITLE
getLastCrashReport doesn't return if uploadToServer false

### ISSUE THREAD

**Issue by issacgerges** [electron/electron#17399]
* **Electron Version:**
  * 4.0.0
* **Operating System:**
  * MacOS
* **Last Known Working Electron version:**:
  * n/a

### Expected Behavior
I would expect `getLastCrashReport` to return the latest crashReport, even if un-uploaded

### Actual Behavior
`getLastCrashReport` returns `null`, even though a crash was triggered with `process.crash()` and crash reports are present in the `crashDirectory`

### To Reproduce
The following can be loaded in electron fiddle to demonstrate the issue

https://gist.github.com/4f69a92b0d061a65eae07774fba73d68

### Additional Information
There is a possibility this is by design, if so we may want to rename the api method to make it clear, ie: `getLastUploadedCrashReport`

**Comment by issacgerges** [comment]
It looks like this may be as-designed, see https://github.com/electron/electron/blob/6d674eebb12123aa79c2e52701980568770743c1/lib/common/crash-reporter.js#L60

**Comment by codebytere** [comment]
hmm, per docs we should be doing:
```
Returns the date and ID of the last crash report. If no crash reports have been
sent or the crash reporter has not been started, `null` is returned.
```
i'll update this to return null, as i think we should be conforming to what's expected in docs.
