### ISSUE TITLE
Docs for image setting in appveyor.yml

### ISSUE THREAD

**Issue by RickyWong33** [electron/electron#17391]
### Problem Description

Any docs explained below appveyor setting ?
https://github.com/electron/electron/blob/961c9a88a8ec506474e8aa241d40e040a80f3a89/appveyor.yml#L28

### Proposed Solution

The hint how we can create this image

### Alternatives Considered

Maybe some steps? I guess a full repo is impossible because visual studio is a commercial software

**Comment by codebytere** [comment]
Hi @RickyWong33, this isn't an issue with the Electron framework itself, so i'm going to go ahead and close this. This portion of our appveyor CI configuration is just chooses the version of Visual Studio that's present in our Windows CI boxes.
