### ISSUE TITLE
用electron加载的swf，打包后，在部分win7机型上，打不开，需要设置win7的兼容性才行

### ISSUE THREAD

**Issue by luleiyu** [electron/electron#17390]
![image](https://user-images.githubusercontent.com/35429017/54416082-48b46280-4739-11e9-810f-016c92096809.png)
就是这个设置。请问有没有什么方法可以解决一下。

**Comment by miniak** [comment]
@luleiyu can you please use English for the issue?

**Comment by miniak** [comment]
Google translate didn't help much:
> Use swen loaded by electron, after packaging, on some win7 models, can not open, you need to set the compatibility of win7
