### ISSUE TITLE
Dot erased when drag and droping element with leading dot in name

### ISSUE THREAD

**Issue by isidorn** [electron/electron#17394]
Tried electron 3.10 and 5.0.0 and does not work in both. Both on mac and windows I can repro.
Here's my fiddle gist https://gist.github.com/isidorn/2a88c032113b2dcc6f8f2b773ed3b761 
Change the fiddle such that `renderer.js` line 6 points to a file on your machine which name starts with a `.`.

Start fiddling. Select some text, drag it and drop it the finder / explorer and notice that the dropped element does not have a leading `.`.

Related vscode bug https://github.com/Microsoft/vscode/issues/67176

![drop](https://user-images.githubusercontent.com/1926584/54440402-e5c3cb00-473a-11e9-851d-916e0c8e9c21.gif)

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by bpasero** [comment]
@codebytere reproduces in Electron 9, please reopen.

**Comment by deepak1556** [comment]
The issue repros in chrome as well, should open an issue in chromium.
