### ISSUE TITLE
getGPUInfo('basic') always reports softwareRendering false

### ISSUE THREAD

**Issue by robatwilliams** [electron/electron#17447]
* **Electron Version:**
  * 4.0.4, 4.0.7
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**:
  * n/a

### Expected Behavior
`auxAttributes.softwareRendering` returned by `getGPUInfo('basic')` correctly reflects whether or not software rendering is active, i.e. are we using hardware acceleration. It already does so in `complete` mode.

Alternatively if it cannot be determined in this mode, it should be omitted as is done with the other `auxAttributes`.

### Actual Behavior
`auxAttributes.softwareRendering` is reported as `false` despite software rendering being active.

### To Reproduce
1. download [electron-quick-start](https://github.com/electron/electron-quick-start)
2. add `app.getGPUInfo('basic').then(console.log);` in `main.js:createWindow`
3. `npm start -- --disable-gpu`
4. observe the output in the console

### Screenshots
n/a

### Additional Information
The same happens on a virtual machine where hardware acceleration is not available (no need to disable it via a flag).

**Comment by robatwilliams** [comment]
Similarly, it also always reports every `gpuDevice` as `active:false`. It should have an active Google SwiftShader.

**Comment by codebytere** [comment]
@robatwilliams we don't manipulate GPU info as we pull it from native Chromium implementations, so this might not be the best place to report this. If you could please verify you see the same issues when  checking `chrome://gpu` with the same flags passed, this issue should closed and opened on crbug.com instead. Thanks!

**Comment by robatwilliams** [comment]
It does report software rendering in various places, and an active Google SwiftShader.

This bug specifically concerns the `basic` mode. There is no such mode in chrome://gpu.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
