### ISSUE TITLE
Javascript hints in the webview are defined

### ISSUE THREAD

**Issue by StringKe** [electron/electron#17445]
> electron:v2.0.18
platform:macOS 10.14.3

Some external websites are loaded in the webview of electron. These external websites have their own javascript but cannot execute javascript.

![image](https://user-images.githubusercontent.com/31089228/54592052-85989600-4a66-11e9-8d0c-c7d551630c47.png)

I am using electron to create a browser, I have encountered some problems, such as javascript in the loaded website can not be executed.

![image](https://user-images.githubusercontent.com/31089228/54592242-efb13b00-4a66-11e9-843c-0726acfde3a2.png)

### These errors restart the electron, or wait for a while to disappear?

在webview中，引入其他页面，页面中的jquery无法执行。等待一会后错误消失

**Comment by MarshallOfSound** [comment]
> electron:v2.0.18

Can you upgrade your version of Electron to something more recent and try again?

**Comment by StringKe** [comment]
> > electron:v2.0.18
> 
> Can you upgrade your version of Electron to something more recent and try again?

When I upgraded electron, I didn’t encounter it. The error itself is not fixed.
