### ISSUE TITLE
getGPUInfo() reports mixed-up hardware gpuDevice when using software rendering

### ISSUE THREAD

**Issue by robatwilliams** [electron/electron#17448]
* **Electron Version:**
  * 4.0.4, 4.0.7
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**:
  * n/a

### Expected Behavior
When software rendering using Google SwiftShader (the CPU-based GPU implementation), it appears as the `gpuDevice`, and without information about other GPUs.

### Actual Behavior
In `basic` mode, the information is for the Intel hardware GPU - which is not the one doing the rendering:
```
{
    active: false,
    deviceId: 22802,
    driverDate: '12-10-2018',
    driverVendor: 'Intel Corporation',
    driverVersion: '25.20.100.6472',
    vendorId: 32902
}
```

In `complete` mode, the information is extended with `deviceString` and `vendorString` belonging to SwiftShader. It's also now reported as `active: true`:
```
{
    active: true,
    deviceId: 22802,
    deviceString: 'Google SwiftShader',
    driverDate: '12-10-2018',
    driverVendor: 'Intel Corporation',
    driverVersion: '25.20.100.6472',
    vendorId: 32902,
    vendorString: 'Google Inc.'
}
```

### To Reproduce
1. download [electron-quick-start](https://github.com/electron/electron-quick-start)
2. add `app.getGPUInfo(<mode>).then(console.log);` in `main.js:createWindow`
3. `npm start -- --disable-gpu`
4. observe the output in the console

### Screenshots
n/a

### Additional Information
None.

**Comment by codebytere** [comment]
@robatwilliams we don't manipulate GPU info as we pull it from native Chromium implementations, so this might not be the best place to report this. If you could please verify you see the same issues when  checking `chrome://gpu` with the same flags passed, this issue should closed and opened on crbug.com instead. Thanks!

**Comment by robatwilliams** [comment]
This issue does exist in Chromium:

```
GPU0 | VENDOR = 0x8086 [Google Inc.], DEVICE= 0x5912 [Google SwiftShader] *ACTIVE*
Driver vendor | Intel Corporation
Driver version | 25.20.100.6472
Driver date | 12-10-2018
```

**Comment by robatwilliams** [comment]
Reported root cause https://bugs.chromium.org/p/chromium/issues/detail?id=945308

This is still a bug in Electron, even though the root cause isn't in Electron. However I'll close this issue as requested given that's your process. Perhaps a label would be useful to track instances like this.
