### ISSUE TITLE
getGPUInfo() on Win7 does not report active SwiftShader GPU when using software rendering

### ISSUE THREAD

**Issue by robatwilliams** [electron/electron#17450]
* **Electron Version:**
  * 4.0.4, 4.0.7
* **Operating System:**
  * Windows 7
* **Last Known Working Electron version:**:
  * n/a

### Expected Behavior
Google SwiftShader (CPU-based implementation of GPU) is reported as the active GPU, as happens on Windows 10.

### Actual Behavior
The hardware GPU is the only one reported, and it has `active:false`.

### To Reproduce
1. download [electron-quick-start](https://github.com/electron/electron-quick-start)
2. add `app.getGPUInfo(<mode>).then(console.log);` in `main.js:createWindow`
3. `npm start -- --disable-gpu`
4. observe the output in the console

Output when using `basic` mode (it also happens using `complete`, but I've been unable to capture the output just now due to #17187):
```
[
  {
    "active": false,
    "deviceId": 1071,
    "driverDate": "2-3-2015",
    "driverVendor": "NVIDIA",
    "driverVersion": "9.18.13.4144",
    "vendorId": 4318
  },
  {
    "active": false,
    "deviceId": 1042,
    "driverDate": "8-16-2018",
    "driverVendor": "Intel Corporation",
    "driverVersion": "10.18.14.5057",
    "vendorId": 32902
  }
]
```

### Screenshots
n/a

### Additional Information
Observed on machine with dual-GPUs, although I don't think the issue is caused by that. This is the only Windows 7 machine I have available.

Possibly related: #17448, includes the output on Windows 10.

**Comment by codebytere** [comment]
@robatwilliams we don't manipulate GPU info as we pull it from native Chromium implementations, so this might not be the best place to report this. If you could please verify you see the same issues when  checking `chrome://gpu` with the same flags passed, this issue should closed and opened on crbug.com instead. Thanks!

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
