### ISSUE TITLE
Chrome Extension still exists without being added

### ISSUE THREAD

**Issue by dispix** [electron/electron#17455]
* **Electron Version:**
v3.1.4
* **Operating System:**
macOS 10.14.3

### Expected Behavior
When opening the devtools of a new Electron project, I shouldn't see the extensions I may have added in the same or another project if I don't add them.

### Actual Behavior
Even if I delete the whole project and clone it again, I have to explicitly use `BrowserWindow.removeExtension` otherwise the extensions are still available in the devtools.

### To Reproduce
Use [MarshallOfSound/electron-devtools-installer](https://github.com/MarshallOfSound/electron-devtools-installer) and use it to install any chrome devtools.
Then remove that code from your project. The extensions will still be available and only deleted by specifying `BrowserWindow.removeExtension`.

**Comment by miniak** [comment]
This is by design
