### ISSUE TITLE
build: "npm run check-tls" fails

### ISSUE THREAD

**Issue by Spongman** [electron/electron#17456]
the build instructions suggest "For a quick test, run the following script:
````
$ npm run check-tls
````

however, this fails for me on Ubuntu 18.04 with node v10.15.3:
````
$ npm run check-tls
npm ERR! path /home/user/electron-gn/src/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/home/user/electron-gn/src/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-03-19T16_52_49_321Z-debug.log
````

**Comment by codebytere** [comment]
@Spongman where did you run this from?

`/home/user/electron-gn/src/package.json` correctly doesn't exist; this needs to be run from 
`/home/user/electron-gn/src/electron` such that the correct path is:
`/home/user/electron-gn/src/electron/package.json`

**Comment by Spongman** [comment]
i was just following the instructions here: https://electronjs.org/docs/development/build-instructions-linux

it doesn't mention having to be in that directory. in fact, i don't think the sources are fetched until way later in the instructions (here: https://electronjs.org/docs/development/build-instructions-gn#getting-the-code)

**Comment by codebytere** [comment]
@Spongman yeah this is correct: our build system change resulted in this breaking. We'll try to get it fixed soon!

**Comment by codebytere** [comment]
This has been moved out of our main repo and updated in our main docs accordingly.
