### ISSUE TITLE
Ajax call causes crash when Electron is running from a network drive

### ISSUE THREAD

**Issue by angrymarker** [electron/electron#17460]
* **Electron Version:**
4.1.0
* **Operating System:**
Windows 7
* **Last Known Working Electron version:**:
3.1.5

### Expected Behavior
An simple ajax get call should return data.

### Actual Behavior
On local drive - ajax call successfully completes.
When transferred to a shared network drive for the company with a UNC path, the ajax call crashes Electron.

### To Reproduce
Clone:
https://github.com/angrymarker/EletronCrash.git
Install with 
$ npm install
Create build using electron packager
$ electron-packager "folder/to/project" ajaxtest --platform=win32 --overwrite --prune=true -
-arch=x64 --out=release-builds --electron-version=4.1.0

copy build to shared network drive

attempt ajax call with test button

### Screenshots

![image](https://user-images.githubusercontent.com/22374821/54634162-9db0eb00-4a4f-11e9-864b-89b87d912e7e.png)

### Additional Information
Build works fine locally, but not when on shared network drive.

**Comment by ckerr** [comment]
I believe this may be an issue with reading asar files on network drives which ISTR was fixed for 5.0. @angrymarker could you give this issue a try with one of the 5.0.0 betas to test this theory?

**Comment by angrymarker** [comment]
@ckerr 
tested with v5.0.0-beta.6, crashed as well.

**Comment by angrymarker** [comment]
Tested with v6.0.0, crashed as well.

**Comment by capc0** [comment]
any updates on this? @angrymarker

**Comment by nornagon** [comment]
Can you possibly provide a crash dump? That would help us to narrow down the issue.

**Comment by capc0** [comment]
how can i do that?
i can however confirm that upgrading to v7 and disabling ASAR build did seem to work. Will test tomorrow what of those 2 steps causes the app to not crash.

**Comment by capc0** [comment]
Electron 5.0.5 without ASAR does also crash.
Electron 7.1.0 with ASAR works.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
