### ISSUE TITLE
Electron crashes (or fail to load) when require node C++ addon

### ISSUE THREAD

**Issue by rogeriorc** [electron/electron#17462]
* **Electron Version:**
  * 4.1.0
  * 5.0.0-beta.5 
* **Operating System:**
  * Windows 10 (1803)
  * Windows 10 (1809)
* **Last Known Working Electron version:**:
  * 3.1.6

### Expected Behavior
The node addon to be loaded and exported methods avaliable in the required module. 

### Actual Behavior
 * The _hello_world_ example says thtat module did not self-register.
 * The _context_aware_ example crashes.

### To Reproduce
**Clone the repo:**

```bash
git clone https://github.com/rogeriorc/electron-node-addon.git
cd electron-node-addon
```

**To build the node addons use:**

```bash
npm install
npm run build
```

**To run the example requiring the addon on _src/node-addon/hello_world_**

```bash
npm run hello-world
```

**To run the example requiring the addon on _src/node-addon/context_aware**

```bash
npm run context-aware
```

**To configure**

Edit in the package.json:

```json
  "devDependencies": {
    ...
    "electron": "4.1.0"
  },
  "config": {
    "generator": {
      "win32": "Visual Studio 14 2015",
      "linux": "Unix Makefiles"
    },
    "runtime": {
      "target": "electron",
      "version": "4.1.0",
      "arch": "x64"
    }
  }

```
* devDependencies.electron: Electron version

* config.generator: The target generator CMake will use, per platform

* config.runtime.target: Electron runtime

* config.runtime.version: Electron version

* config.runtime.arch: Target architecture

After change the _devDependencies.electron_ and _config.runtime.version_, reinstall and rebuild:

```bash
npm install
npm run build
```

### Screenshots

![image](https://user-images.githubusercontent.com/2599798/54635115-423c2880-4a62-11e9-9919-51b4efaa5628.png)

**Comment by MarshallOfSound** [comment]
@rogeriorc It looks like that module is using `cmake-js` to build.  That build system does not automatically include some things that `node-gyp` does.  The thing that is missing in this scenario is the `DelayLoadHook` for `node.exe`.

Refs: https://github.com/electron/electron/issues/17326#issuecomment-471492666
Node Gyp Impl: https://github.com/nodejs/node-gyp/blob/master/src/win_delay_load_hook.cc

You'll need something similar from Electron 4 and higher
