### ISSUE TITLE
[Docs] incorrect url for Releasers in pull request document

### ISSUE THREAD

**Issue by dakeshi** [electron/electron#17478]
### Problem Description
Releasers link to incorrect url on Continuous Integration Testing section [in pull request doc](https://electronjs.org/docs/development/pull-requests)

### Proposed Solution
- fix link with correct one
- it needs to fix on crowdin string too

### Additional Information
Actually, I'd like to make pr to fix this issue but I don't know where can I find out this info.

**Comment by ryanomor** [comment]
Would the correct link perhaps be `https://github.com/orgs/electron/people`?

**Comment by erickzhao** [comment]
i dont think this exists anymore
