### ISSUE TITLE
  OptionParser.new do |parser|   parser.on("-n", "--noop", "Find the links, but don't update the content. \n\t\t\t\t\s\s\s\s\sPipe

### ISSUE THREAD

**Issue by afuerhoff420** [electron/electron#17473]
* Output of `node_modules/.bin/electron --version`:
* Operating System (Platform and Version):

* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Comment by MarshallOfSound** [comment]
The issue body is empty and the issue title does not appear to be Electron related.  I'm going to close this out, if you have an actual Electron issue please raise a new issue and strictly follow the issue template 👍
