### ISSUE TITLE
Can not able to login to udeler account 

### ISSUE THREAD

**Issue by prasaw35** [electron/electron#17498]
I can not able to login to udeler account please fix this bug
![Bug](https://user-images.githubusercontent.com/48667646/54749631-2f109080-4bfb-11e9-8587-5b6d8bc6615f.PNG)

**Comment by robatwilliams** [comment]
Stop reporting issues here. This is the wrong place.

#17449 #17430

**Comment by prasaw35** [comment]
so how can i login to udeler courses

**Comment by HashimotoYT** [comment]
@prasaw35 Report this issue to Udeler repository: https://github.com/FaisalUmair/udemy-downloader-gui/issues
