### ISSUE TITLE
devtools of webview, can't trigger event in mobile mode (on some computer).

### ISSUE THREAD

**Issue by Mqleaf** [electron/electron#17499]
* **Electron Version:**
  * 2.0.18
* **Operating System:**
  *  Windows10
* **Last Known Working Electron version:**:
  * 

### Description
I want to open the devtools of a webview in mobile mode, and open the devtools in another webview.
Therefore, I try the demo of `webContents.setDevToolsWebContents(xxx)`, but it couldn't work.
The problem is that I couldn't click element in mobile mode on a computer with Windows10. However,  another computer with Windows10 didn't occur, Mac not occur as well. 

### Expected Behavior

When the devtools loaded, switch to mobile mode, click on the button, can trigger click event.

### Actual Behavior

click the element, without any response.

### To Reproduce

```
<html>
<head>
  <style type="text/css">

    * { margin: 0; }
    #browser { height: 70%; }
    #devtools { height: 30%; }
  </style>
</head>
<body>
  <webview id="browser" src="https://github.com"></webview>
  <webview id="devtools"></webview>
  <script>
    const browserView = document.getElementById('browser')
    const devtoolsView = document.getElementById('devtools')
    browserView.addEventListener('dom-ready', () => {
      const browser = browserView.getWebContents()
      browser.setDevToolsWebContents(devtoolsView.getWebContents())
      browser.openDevTools({mode: 'right'})
    })
  </script>
</body>
</html>
```

### Additional Information

Update the version to 3.x.x, 4.x.x, can fire click event, but the elements panel is empty. What's more, the mode is not like mobile...
For example, load baidu.com :
![image](https://user-images.githubusercontent.com/22488004/54751338-9b988900-4c15-11e9-89ff-44d3faf3c77a.png)

**Comment by camilacanhete** [comment]
Possible related: can't trigger click/hover event when DevTools is open and win.reload() is called (the second time the window loads, button isn't clickable anymore.

Steps to reproduce: 
- Use the main window to open devTools and load a page with a button on it
- Make something reload the main window
- Check the button (isn't clickable anymore)

System: Mac OS Sierra version 10.12.6

**Comment by Mqleaf** [comment]
In my case, it happened at first load. Just one computer with Windows10 didn't work, another one works, may be compatibility error.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by Mqleaf** [comment]
I know the new version can resolve this issue, but new version has other problem: Element panel of devtools is empty. so I can't use the new version as well.
