### ISSUE TITLE
 MAS rejection - electron.asar file includes “autoupdater”

### ISSUE THREAD

**Issue by mariia-shumska** [electron/electron#17504]
* **Electron Version:** `4.0.7`

### Rejection Email

The app’s `electron.asar` file was found to include “autoupdater” code which at minimum directly imported updated executable files for other OSes, and appears capable of pulling in asar files as well.

___________

Guideline 2.5.2 - Performance - Software Requirements

Your app, extension, or linked framework appears to contain code designed explicitly with the capability to change your app’s behavior or functionality after App Review approval, which is not in compliance with App Store Review Guideline 2.5.2 and section 3.3.2 of the Apple Developer Program License Agreement.

This code, combined with a remote resource, can facilitate significant changes to your app’s behavior compared to when it was initially reviewed for the App Store. While you may not be using this functionality currently, it has the potential to load private frameworks, private methods, and enable future feature changes. This includes any code which passes arbitrary parameters to dynamic methods such as `dlopen()`, `dlsym()`, `respondsToSelector:`, `performSelector:`, `method_exchangeImplementations()`, and running remote scripts in order to change app behavior and/or call SPI, based on the contents of the downloaded script. Even if the remote resource is not intentionally malicious, it could easily be hijacked via a Man In The Middle (MiTM) attack, which can pose a serious security vulnerability to users of your app.

The next submission of this app may require a longer review time, and this app will not be eligible for an expedited review until this issue is resolved.

Next Steps

- Review the Software Requirements section of the App Store Review Guidelines.
- Ensure your app is compliant with all sections of the App Store Review Guidelines and the Terms & Conditions of the Apple Developer Program. 
- Once your app is fully compliant, resubmit your app for review.

Submitting apps designed to mislead or harm customers or evade the review process may result in the termination of your Apple Developer Program account. Review the Terms & Conditions of the Apple Developer Program to learn more about our policies regarding termination.

### Additional Information

```shell
$ grep  update ./Contents/Resources/electron.asar
Binary file ./Contents/Resources/electron.asar matches
```

Please, kindly assist.

**Comment by MarshallOfSound** [comment]
> The app’s electron.asar file was found to include “autoupdater” code which at minimum directly imported updated executable files for other OSes, and appears capable of pulling in asar files as well.

This is a new (and IMO very flawed) report from the MAS rejection folks 😢 I'll see if I can make it so the MAS build of Electron has no trace of update code in it at all, even if all those code paths are dead.

**Comment by Qiplex** [comment]
Thanks a lot, @MarshallOfSound for looking on it.

**Comment by mariia-shumska** [comment]
Thanks a lot, @MarshallOfSound for looking on it.

**Comment by MarshallOfSound** [comment]
> I'll see if I can make it so the MAS build of Electron has no trace of update code in it at all

So this isn't possible without some hefty breaking changes and I don't really want to make those around the `autoUpdater` module.  I'd suggest you reach back out to the MAS folks and ask them to manually review this.

Although there are files that are physically named "auto-updater" they are inoperative in our mac app store build.  The update framework itself `Squirrel.framework` is not present in MAS builds and the methods in that file are all set to be noops.

**Comment by circleapps** [comment]
Is this issue specific to 4.0.7 only or apply to all 4.0.x versions?  

I was planned to submit my app with Electron 4.0.0 to Mac App Store next week. 

Thanks.

**Comment by circleapps** [comment]
I saw 4.1.5 has been released, did it fix this issue? 

This issue is very critical to me, please, kindly assist, thanks.

**Comment by nornagon** [comment]
I think this is a Mac App Store policy failure, and I'm not sure there's anything we can do on our side without further information. I'd encourage you to ask for more details from the app store if possible and report back here with anything you find out.

**Comment by circleapps** [comment]
Thanks, I will submit my app next week with electron 4.0.0.
If I get any bad news (I really hope it will not happen), I will report back to you.

**Comment by circleapps** [comment]
My app got approved by Mac App Store last week. It looks like my reviewer has no problem with electron 4.0.0.
Don't know what will happen for 4.x, hope someone will tell me.

**Comment by nornagon** [comment]
Great to hear. I'm closing this because it looks like the issue has been resolved, feel free to reopen if this issue reappears.
