### ISSUE TITLE
Create and Closed Webview, Memory Increase

### ISSUE THREAD

**Issue by UoToGK** [electron/electron#17512]
* **Electron Version:**
  * Using Electron 1.3.1 on Windows 7. In my index.html I Create and Closed Webview, Memory Increase in electron.exe , i set  emitter.setMaxListeners() is 0. I wonder if the webview needs to have a destroyed method to free memory.

### Expected Behavior

Memory increases first and then decreases, in a dynamic equilibrium position

### Actual Behavior
 Memory Increase always,last out of memory

### To Reproduce
this is my script in my index.html;
		setInterval(() => {		
let webview = document.createElement("webview");	
		document.body.appendChild(webview);			
document.body.removeChild(webview);	 
webview=null;//it's no use doing that;
	}, 100);

so who can tell me what's the matter on here?

It should be that the memory of the main process keeps increasing.

Why can't this destroy WebView

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
