### ISSUE TITLE
Increase navigation speed of html pages

### ISSUE THREAD

**Issue by Harshad1995** [electron/electron#17510]
### Problem Description
I have a desktop application where user have short-cut keys for options like a. zzzz b. yyyyy c. www. Where a, b, c work as short-cut keys to avoid use of mouse. But it is 1000 slower than chrome browser and found not helpful as short-cut.

### Proposed Solution
Can you make it as fast as chrome browser?

### Alternatives Considered
I used sandbox: true, and it worked. Pages load faster as expected. But it do not allow require(), which is essential for database access, emailing and other stuff.

### Additional Information
I am new to programming and I avoided Java because it is now charging for commercial products. If do you have any other technology suggestion for desktop application which is as fast as javascript on chrome and free 
[index.txt](https://github.com/electron/electron/files/2995384/index.txt)

then it will be very helpful.

**Comment by MarshallOfSound** [comment]
If you want to use `require` we have to boot node each time the renderer navigates.  That's what is taking the extra time, there is no way around that

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
