### ISSUE TITLE
netlog properties are not properties

### ISSUE THREAD

**Issue by bitdisaster** [electron/electron#17519]
The properties `currentlyLogging` and `currentlyLoggingPath` do not return values when the netlog module is referenced via `electron.remote.netlog` or `electron.netlog`. Meanwhile `electron.session.currentSession.netlog` works as expected. 

* **Electron Version:**
 3.1.0  and later
* **Operating System:**
Observed on Windows 10, likely all platforms are affected
* **Last Known Working Electron version:**:
3.0.16

### Expected Behavior

`currentlyLogging` should return a boolean
`currentlyLoggingPath` should return a string
### Actual Behavior

`currentlyLogging` returns `(...args) => netLog[property](...args)`
`currentlyLoggingPath` returns `(...args) => netLog[property](...args)`

**Comment by codebytere** [comment]
It looks like this may have been intentional:
> // TODO(deepak1556): Deprecate and remove standalone netLog module,
> // it is now a property of session module.

cc @deepak1556

**Comment by deepak1556** [comment]
Yeah its a property on the session interface now, but the standalone module is meant to be working until this deprecated and removed. In that aspect, this is worth fixing.
