### ISSUE TITLE
loadURL / loadFile calls throw "ERR_ABORTED (-3) error" if location.hash or history.pushState called on the page before page loaded

### ISSUE THREAD

**Issue by vladimiry** [electron/electron#17526]
Electron v5.0.0-beta.6 will likely break every single page application / SPA that uses routing as it's uncommon to trigger the routing only after the page loading event has been fired. See workaround in additional Information section below.

### Issue Details

* **Electron Version:**
  *  5.0.0-beta.6 +
* **Operating System:**
  *  any (tested on linux)
* **Last Known Working Electron version:**
  *  4.1.1

### Expected Behavior
Page loading completes without errors even if that's a SPA.

### Actual Behavior

- `window.location.hash = '123'` called on page:
```
{ Error: ERR_ABORTED (-3) loading 'file:////dev/temp/electron-loadurl-issue/page.html#123'
    at rejectAndCleanup (//dev/temp/electron-loadurl-issue/node_modules/electron/dist/resources/electron.asar/browser/navigation-controller.js:72:21)
    at WebContents.navigationListener (//dev/temp/electron-loadurl-issue/node_modules/electron/dist/resources/electron.asar/browser/navigation-controller.js:93:20)
    at WebContents.emit (events.js:193:15)
  errno: -3,
  code: 'ERR_ABORTED',
  url:
   'file:////dev/temp/electron-loadurl-issue/page.html#123' }
```
- `history.pushState({}, "title", "url")` called on page:
```
{ Error: ERR_ABORTED (-3) loading 'file:////dev/temp/electron-loadurl-issue/url'
    at rejectAndCleanup (//dev/temp/electron-loadurl-issue/node_modules/electron/dist/resources/electron.asar/browser/navigation-controller.js:72:21)
    at WebContents.navigationListener (//dev/temp/electron-loadurl-issue/node_modules/electron/dist/resources/electron.asar/browser/navigation-controller.js:93:20)
    at WebContents.emit (events.js:193:15)
  errno: -3,
  code: 'ERR_ABORTED',
  url: 'file:////dev/temp/electron-loadurl-issue/url' }
```

### To Reproduce
-  main.js:
```javascript
const path = require("path");
const url = require("url");
const {app, BrowserWindow} = require("electron");

app.on("ready", async () => {
    const browserWindow = new BrowserWindow();

    browserWindow.webContents.on("did-start-navigation", (event, url) => {
        console.log("did-start-navigation", {url});
    });

    try {
        await browserWindow.loadURL(
            url.format({
                protocol: "file",
                slashes: true,
                pathname: path.join(__dirname, "page.html")
            })
        );
    } catch (e) {
        console.error(e);
    }

    // "loadFile" gives the same result
    // try {
    //     await browserWindow.loadFile(
    //         path.join(__dirname, "page.html"),
    //     );
    // } catch (e) {
    //     console.error(e);
    // }
});
```
- page.html:
```html
<!DOCTYPE html>
<html>
<body>
<script>
    window.location.hash = '123';
    // history.pushState({}, "title", "url"); // second case
</script>
</body>
</html>
```

### Screenshots
N/A

### Additional Information
The workaround is changing the hash / history state afte page got loaded:
```html
<!DOCTYPE html>
<html>
<script>
    function onload() {
        window.location.hash = '123';
        // history.pushState({}, "title", "url"); // second case
    }
</script>
<body onload="onload">
</body>
</html>
```

See relater PR https://github.com/electron/electron/pull/15855 and code line https://github.com/electron/electron/pull/15855/files#diff-fc5b6704bed639bfab5927de1eccbcc3R85

CC @nornagon

**Comment by MarshallOfSound** [comment]
Hey @vladimiry 

This is currently the expected behavior, the promise that `loadURL` returns will be rejected if the renderer for _whatever_ reason fails to completely load that URL.

If you navigate before the page has completed loading you have aborted that load, hence the `ERR_ABORTED` rejection.

**Comment by vladimiry** [comment]
@MarshallOfSound I still believe such logic is going to break a lot of SPA apps, but I got it that it's expected behavior. There are a few points I'd like you to consider:
- Changing the hash or push state is not really navigation, the new page loading process is not involved but only the url gets changed.
- The currently shown error is vague, I had to look into the sources in order to understand why exactly page loading got aborted.

**Comment by MarshallOfSound** [comment]
@vladimirkononov 

> I still believe such logic is going to break a lot of SPA apps

How can it break apps?  This feature was only just introduced in `5.0.0`, it didn't exist in any other state before that version.

**Comment by vladimiry** [comment]
@MarshallOfSound Single page applications often use routing based on either html5 history api (push state thing) or url hash. Normally SPA doesn't wait for the full page loading but starts working asap which means html5 hitstory or url hash might be changed before page got fully loaded and it doesn't mean that a new page starts loading as it's only the client side url change. This is actually how I noticed the problem in action. See applied workaround here
https://github.com/vladimiry/ElectronMail/blob/0fb48fa16fe4dcf0370a9004c4556f0716941377/src/web/src/environments/production/bootstrap-app.ts#L10 as an example.

**Comment by TheGoddessInari** [comment]
This still should've been clearly listed and documented as a Breaking API Change as loadURL returns the rejected promise and causes it to be 'uncaught' and printed, even when navigation is aborted intentionally by the user.

**Even if** `did-fail-load` is already handled!

The change to return type requires special handling at every call site to suppress a false-positive error that few people will ever care about. Instead of calling loadURL by itself on one line, you have to check if it returns anything, then add a catch only if it does, check if it's one of the bogus error codes, re-throw if it's a real error.

And still **prevents** the navigation, and it's not at all clear how to avoid **that**.

This does affect Single Page Applications that were working fine on v4, and this should've been left open and taken more seriously. In fact, I don't see a single online SPA out in the wild that's working with this change precisely because it is blocking navigation for no reason.

**Comment by cyphercodes** [comment]
This is also blocking loading dataURL like so:
```
browserWindow.webContents.loadURL('data:text/html;charset=utf-8,' + encodeURIComponent(html), {
      baseURLForDataURL: httpHost,
});
```

**Comment by vladimiry** [comment]
> If you navigate before the page has completed loading you have aborted that load, hence the ERR_ABORTED rejection.

I will just repeat. Calling `history.pushState` or changing the `location.hash` value does trigger reloading the page, so the loaded page remains the same. This is why `expected behavior` does not look good for me.

**Comment by cyphercodes** [comment]
> This is also blocking loading dataURL like so:
> 
> ```
> browserWindow.webContents.loadURL('data:text/html;charset=utf-8,' + encodeURIComponent(html), {
>       baseURLForDataURL: httpHost,
> });
> ```

This is still happening even after 5.0.2

**Comment by preslavsh** [comment]
Still happening in 6.0.9. I not sure what the proper behavior should be, but it causes pain when I want to load angular hash route from electron. My case is notification window should open hash route on the main window.

**Comment by vladimiry** [comment]
@preslavsh you could try bootstrapping the Angular app in `window.addEventListener("load"` handler.
