### ISSUE TITLE
Error: Oynamic Linking Error: Win32 error 126 at new OynamicLibrary

### ISSUE THREAD

**Issue by joeyer** [electron/electron#17536]
electron: 4.0.4
node:10.11.0

^ Error
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Oynamic Linking Error: Win32 error 126 at new OynamicLibrary
(C:\U5ers\Yeastar\AppOata\Local\Program5\Linku5\re50urces\app.asar\node at Object-Library
(C:\U5ers\Yeastar\AppOata\Local\Program5\Linku5\re50urces\app.asar\node at Object.<anonymous>
(C:\U5ers\Yeastar\AppOata\Local\Program5\Linku5\re50urces\app.asar\mai...:37675) at t
(C:\U5ers\Yeastar\AppOata\Local\Program5\Linku5\re50urces\app.asar\main\...:256) at Object.<anonymous>
(C:\U5ers\Yeastar\App0ata\Local\Programs\Linku5\re5〇urces\app.asar\mai...:91171) at t
(C:\U5ers\Yeastar\AppOata\Local\Program5\Linku5\re50urces\app.asar\main\...:256) at Object.<anonymous>
(C:\U5ers\Yeastar\AppOata\Local\Program5\Linku5\re50urces\app.asar\mai...:88987) at t
(C:\U5ers\Yeastar\AppOata\Local\Program5\Linku5\re50urces\app.asar\main\...:256) at Object.<anonymous>
(C:\U5ers\Yeastar\AppOata\Local\Program5\Linku5\re50urces\app.asar\mai...:88735) at t
(C:\U5ers\Yeastar\AppOata\Local\Program5\Linku5\re50urces\app.asar\main\...:256)
mm

When the package environment runs the installation package, there is no problem on other winodws computers. Except for the win10 professional version, this problem will be reported. Then I downgrade the electron version to 1.8.4, there will be no such problem.

**Comment by nornagon** [comment]
Hi, thanks for your report. Unfortunately we need some more information in order to diagnose this issue. Would it be possible to create a small example app that produces this crash based on [electron-quick-start](https://github.com/electron/electron-quick-start)?

Thanks!

**Comment by joeyer** [comment]
Using the ffi ^2.3.0 component to call our own dll dynamic library, then the electron version is directly upgraded from 1.8.4 to 4.0.4, packaged and run, it will be reported on windows10 professional version, then I downgrade the electron version to 1.8 .4 will not, no other special

**Comment by TanninOne** [comment]
Check if the system you have this on has the vc runtime (vc_redist) installed.
The 126 error loading dlls usually signals that a dependency can't be found, not the .dll/.node itself. Electron 4 stopped bundling the vc redistributable so users now have to install it themselves or you have to extend your installer to do it.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
