### ISSUE TITLE
CMD+R Event not captured

### ISSUE THREAD

**Issue by Stoyvo** [electron/electron#17530]
### Preflight Checklist

* [ x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.1.1
* **Operating System:**
  * MacOS 10.13.6

### Expected Behavior
User press CMD + R, browser window should receive the keypress/keydown/keyup events.

### Actual Behavior
Browser Window (JS) does not receive event.

### To Reproduce
Create a new Electron project using 4.1.1, disable dev tools on the browser window, provide null menu, add basic keydown listener.

**Comment by emilbayes** [comment]
This works without any issues:

`index.js`:
```js
const electron = require('electron')
const path = require('path')

const { BrowserWindow, app } = electron

app.on('ready', function () {
  let win = new BrowserWindow()
  win.loadURL('file://' + path.resolve('index.html'))

  win.webContents.on('did-finish-load', () => win.webContents.openDevTools({ mode: 'detach' }))
})
```

`index.html`
```html
<html>
  <script>
    document.addEventListener('keydown', (e) => {
      console.log(e)
      e.preventDefault()
    })
  </script>
</html>
```

**Comment by Stoyvo** [comment]
@emilbayes Thanks, unfortunately still doesn't work. My keypress event does not capture.

So far I have this workaround:
```
const electronLocalshortcut = require('electron-localshortcut');
electronLocalshortcut.register(win, 'CommandOrControl++R', () => {
        win.webContents.executeJavaScript("window.dispatchEvent(new KeyboardEvent('keydown',  {'key':'r', 'ctrlKey':true, 'char':'r', 'keyCode':82, 'code':82, 'which':82}))");
    });
```
However, my listener does not get the key code, regardless of which way I define it.

What I can't understand is why Electron prefers to hijack these shortcuts, and then only gives you two options:
1) Put it in a menu
2) Global shortcut and developers must add their own "is window focused" hacks.

Electron should give the browser every keyboard command except for OS level (eg: CMD+Q) and not depend on 3rd party modules to solve it.

**Comment by emilbayes** [comment]
Notice that `keyCode` is deprecated: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
