### ISSUE TITLE
registerHttpProtocol seems like that not present body of POST

### ISSUE THREAD

**Issue by Symous** [electron/electron#17531]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  *  4.1.0
* **Operating System:** 
  *  Windows 10 64 bit
* **Last Known Working Electron version:**: 
  *  None

### Expected Behavior

I developed a SPA  with React and use electron to make it a Desktop app. but I found that all my http:// request were transfer to file:// request, so I have to use protocol.registerHttpProtocol to transfer to original http:// request, **but all the POST request seems like that lost the body parameter.**
```js
// createWindow
win.loadURL(url.format({pathname : 'index.html', protocol : 'file', slashes : true}));
// onReady
protocol.registerHttpProtocol('file', (request, callback) => {
    // POST request body not present in request 
    // some logic to deal with request.url
   // .....
    callback({ url : 'myHttpApiUrl'+url , method : request.method});
})
```
### Actual Behavior

ll the POST request seems like that lost the body parameter.

**Comment by emilbayes** [comment]
@Symous did you check the uploadData property on the request?

**Comment by Symous** [comment]
@emilbayes  of course my friend, the uploadData is empty. All working well on my React SPA.

**Comment by malchowc** [comment]
@Symous , @emilbayes I seem to be seeing similar behavior when intercepting requests from my Angular front-end through the registerHttpProtocol method. The uploadData property appears to be "undefined" on the request object, which ultimately makes my back-end application fail to handle POST/PUT/PATCH requests correctly (since there's no uploadData to send to the callback). Any update on this issue?

Could it be related to the Angular/React mechanism used to send/format the request? 

Thanks!

**Comment by jianzhiyao** [comment]
My application is the same.
electron version:6.1.0
os: win10 x64

**Comment by anatoly314** [comment]
Any news on this issue? It seems that Electron v9+ still has the same problem.

**Comment by nornagon** [comment]
Unfortunately without any steps to reproduce this issue we can't debug further. Please provide a small example that reproduces the issue you're seeing, preferable using [Electron Fiddle](https://github.com/electron/fiddle).

Thanks!

**Comment by anatoly314** [comment]
@nornagon , will try to provide some example. It might take some time It's my first step with Electron.
But in general, no matter which protocol you register, `registerHttpProtocol`, `registerStringProtocol`, `registerBufferProtocol`. If you issue a POST request for example to `md-file://upload`, `request` object will be without a body in it. Actually, I doubt is it supposed to be present? In docs, I didn't find it: https://www.electronjs.org/docs/api/structures/protocol-request , `uploadData` not exists either. Maybe we doing it wrong?

**Comment by anatoly314** [comment]
@nornagon , fiddle as you asked :) 
https://gist.github.com/77f3e9ffd097439ee68fb1d94cd27a44

**Comment by nornagon** [comment]
@anatoly314 This is a fundamental limitation of XMLHttpRequest: it [only sends upload bodies to http/https](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/xmlhttprequest/xml_http_request.cc;l=800;drc=df1adb1e58a995deb240cdc86e2b2bd9d65cb433). (see [here](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/platform/weborigin/kurl.cc;l=820-828;drc=db82e0f37eb06d73ed1b62b6367555ee0e82005f) for the definition of `ProtocolIsInHTTPFamily`.)

`fetch()` does not have this problem, if you register your protocol as supporting Fetch. I've modified your example to show how: https://gist.github.com/e8f8f2322c5452d941a4fcc05f063942
