### ISSUE TITLE
base url with baseURLForDataURL changes when reloaded

### ISSUE THREAD

**Issue by emilbayes** [electron/electron#17537]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v4.1.1
* **Operating System:**
  * macOS 10.14.3
* **Last Known Working Electron version:**:
  * Unknown

### Expected Behavior

When using the `BrowserWindow` option `baseURLForDataURL` I expected consecutive reloads to have this base URL be constant.

### Actual Behavior

When using the `BrowserWindow` option `baseURLForDataURL` the first load works as expected, but performing a reload, either from the browser window itself or from the main process with `win.reload()`, the base URL is lost and replace with the data URL itself.

Before the reload `window.location.href === 'file://test'`, after the reload it is something like `window.location.href === "data:text/html;charset=UTF-8,%3Chtml%3E%3C%2Fhtml%3E"`

### To Reproduce

```js
const electron = require('electron')

const { BrowserWindow, app } = electron

app.on('ready', function () {
  let win = new BrowserWindow()
  win.loadURL('data:text/html;charset=UTF-8,' + encodeURIComponent(`<html></html>`), {
    baseURLForDataURL: 'file://test'
  })

  // test with timout for win.reload()
  // setTimeout(() => win.reload(), 5000)

  win.webContents.on('did-finish-load', () => win.webContents.openDevTools({ mode: 'detach' }))
})
```

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
