### ISSUE TITLE
webview ipc-message trigger double times

### ISSUE THREAD

**Issue by lishoulong** [electron/electron#17549]
### Issue Details

* **Electron Version:**
  * 3.0.10
* **Operating System:**
  *macOS 10.14.1
* **Last Known Working Electron version:**:
  *  2.0.10

### Expected Behavior
ipc-message callback should execute one time.

### Actual Behavior
ipc-message callback execute double times.

### To Reproduce
       // render process
       webview.addEventListener('ipc-message', (event) => {
               // this log double times
                console.log('eventevent',  event)
        })
       // webview preload
       ipcRender.sendToHost('ping')

**Comment by lishoulong** [comment]
@bkeepers please help me for this question.

**Comment by zcbenz** [comment]
Do you mind sharing a minimal app that can reproduce the problem?

I can't reproduce with a simple IPC ping-pong code and our ipc-message tests are passing, so I wonder if I missed something.

**Comment by lishoulong** [comment]
It is my fault, sorry to disturb you.
