### ISSUE TITLE
144Hz scrolling support on Linux

### ISSUE THREAD

**Issue by Lukypie** [electron/electron#17541]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an feature request that matches the one I want to file, without success.

### Problem Description
Hi, I have noticed that on all the Electron based apps on Linux, when a 144Hz monitor refresh rate is used, everything will be stuck at 60fps unlike on Windows, where here everything correctly follows the screen refresh rate

### Proposed Solution

Feature request: Support for 144Hz monitors on Linux

**Comment by MarshallOfSound** [comment]
@Lukypie Can you reproduce this in Chrome?

**Comment by Lukypie** [comment]
Chrome have the same issue as well https://bugs.chromium.org/p/chromium/issues/detail?id=535392

and firefox has a workaround

**Comment by nornagon** [comment]
We'll inherit Chromium's fix when it's fixed there, then.

Thanks for the report!

**Comment by fuzunspm** [comment]
I believe this issue still exists.

**Comment by foodornt** [comment]
it hasn't been fixed yet :D

**Comment by spearminttt** [comment]
Still experiencing this in apps like Discord and VS Code
