### ISSUE TITLE
safeDialogs option doesn't work

### ISSUE THREAD

**Issue by PalmerAL** [electron/electron#17543]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 5.0.0-beta.6
* **Operating System:** macOS 10.13.6
* **Last Known Working Electron version:**: unknown

### To Reproduce

```
git clone https://github.com/PalmerAL/electron-quick-start.git
cd electron-quick-start
git checkout safe-dialogs
electron .
```

When running the example app, the "prevent this app from creating additional dialogs" option will appear after the second popup, but checking it doesn't actually do anything. Instead, dialogs will continue to appear forever until you force-quit the app.

**Comment by jkleinsc** [comment]
This was fixed via #17579 and works correctly in 5.0.0-beta.7 and 5.0.0-beta.8
