### ISSUE TITLE
Using multiple webcams. Or providing an option to choose between webcams. (or any mediadevices)

### ISSUE THREAD

**Issue by ananya-g** [electron/electron#17553]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an feature request that matches the one I want to file, without success.

### Problem Description

Using multiple webcams simultaneously. Or any media devices of the same type. This was not possible in a browser for me. But if a provision to choose between webcams and showing its stream would be good workaround.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by ananya-g** [comment]
Issue Resolved
