### ISSUE TITLE
Module did not self-registe in web worker(robotjs)

### ISSUE THREAD

**Issue by Veiintc** [electron/electron#17550]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.1.0

* **Operating System:**
  * Windows 10 (1809) 
* **Last Known Working Electron version:**:
  * 1.8.7

### Expected Behavior

I hope use robotjs in web worker 
### Actual Behavior

but Uncaught Error: Module did not self-register. 
### Screenshots

![1](https://user-images.githubusercontent.com/32948063/54981563-86d83e80-4fe3-11e9-989b-953e68b18e4e.png)

![2](https://user-images.githubusercontent.com/32948063/54981442-3f51b280-4fe3-11e9-8baa-c350d75d4b1f.png)

### Additional Information

Except for robotjs, it works well

**Comment by MarshallOfSound** [comment]
@Veiintc Native node modules are not thread safe by design and as such loading them in worker threads can have undesired behavior such as this.

Check out our [multithreading](https://github.com/electron/electron/blob/master/docs/tutorial/multithreading.md#native-nodejs-modules) document for more information

**Comment by Veiintc** [comment]
> 上不是线程安全的，因此在工作线程中加载它们会产生不希

Thank you. I didn't even notice the rule
