### ISSUE TITLE
Electron does not work on touch screens

### ISSUE THREAD

**Issue by u4aew** [electron/electron#17552]
Electron version: 4.0.4
Operating system: Windows 10, linux

Hi, we are developing an application and have reached the final stage, but at the last stage we encountered a problem.
When intense touch to the screen with a webview, the application stops working

### Expected behavior
The application is left working

### Actual behavior
When you touch the screen, the click event stops running 
remain only 'touchstart' and 'touchend'

### How to reproduce

You need to run the application from the archive on the multi touch screen and intensively click on the webview or watch the video https://vimeo.com/326549419
[example.zip](https://github.com/electron/electron/files/3007840/example.zip)

### Additionally

Sometimes the application completely stops working and an error appears.

![photo_2019-03-26_18-36-55](https://user-images.githubusercontent.com/18558430/54994306-85fcd800-4ff6-11e9-827b-c46272aeb184.jpg)

Found a similar problem, but the electron version is very old there.https://github.com/electron/electron/issues/8725

Please pay attention to this trial. In our case, to complete the final stage you need to solve this problem.

**UPD:**
Crash dump
```
  r8: 00003ba01cc80ff0  r9: 0000000000000045 r10: 00003ba01cd2ce50 r11: 00003cb24ef551e9
 r12: 0000000000000000 r13: 00003ba01cd26000 r14: 00007ffeb093e7d8 r15: 00007ffeb093e7f0
  di: 00003ba01ce15ea0  si: 00003ba01cd26000  bp: 00007ffeb093e830  bx: 00007ffeb093e800
  dx: 0000000000000000  ax: 00003ba01cc44c80  cx: 00003ba01ce15ea0  sp: 00007ffeb093e7c8
  ip: 0000562dd5db4df0 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000006 msk: 0000000000000000 cr2: 0000000000000000
```

**Comment by imZEH** [comment]
On my end when user tries do multiple touches on the screen after a while the touch event won't work. like yeah, the onTouchstart event only recognizes when trying to tap on the screen.

**Comment by KonovalovaKV** [comment]
Hi guys! Is this question still not resolved?

**Comment by softlogic-dev** [comment]
Hello to all. Our project is highly dependent on this bug. Please raise the priority of this problem!

**Comment by gliss** [comment]
We have built a Point of Sale software using electron and get this issue often with our clients.

The devices we use with our PoS software are primarily touch devices and we have to remotely connect to the device to restart the PoS software to get our clients back up and running.

**Comment by Slauta** [comment]
Any news? This is very bad(

**Comment by KonovalovaKV** [comment]
Any news?

**Comment by miniak** [comment]
@u4aew Can you please share a crash dump? Or a simple repro?

**Comment by u4aew** [comment]
> @u4aew Can you please share a crash dump?

Hi, tell me what programs or methods to get the necessary dump ?

**Comment by u4aew** [comment]
I repeated the bug with the touch and did process.crash () in the console.
```
  r8: 00003ba01cc80ff0  r9: 0000000000000045 r10: 00003ba01cd2ce50 r11: 00003cb24ef551e9
 r12: 0000000000000000 r13: 00003ba01cd26000 r14: 00007ffeb093e7d8 r15: 00007ffeb093e7f0
  di: 00003ba01ce15ea0  si: 00003ba01cd26000  bp: 00007ffeb093e830  bx: 00007ffeb093e800
  dx: 0000000000000000  ax: 00003ba01cc44c80  cx: 00003ba01ce15ea0  sp: 00007ffeb093e7c8
  ip: 0000562dd5db4df0 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000006 msk: 0000000000000000 cr2: 0000000000000000
```

**Comment by u4aew** [comment]
Any news?

**Comment by vorobyev-aleksandr** [comment]
@miniak pay attention to the task! All hope is only on you :)

**Comment by vorobyev-aleksandr** [comment]
We can provide any data from the application or give access to the kiosk via remote desktop or ssh

**Comment by u4aew** [comment]
> We have built a Point of Sale software using electron and get this issue often with our clients.
> 
> The devices we use with our PoS software are primarily touch devices and we have to remotely connect to the device to restart the PoS software to get our clients back up and running as using a keyboard and mouse work fine.
> Edit: Even windows gestures stop working if the app is in fullscreen.


Did the problem persist on version 5.0.6 and higher?

**Comment by servappio** [comment]
> > We have built a Point of Sale software using electron and get this issue often with our clients.
> > The devices we use with our PoS software are primarily touch devices and we have to remotely connect to the device to restart the PoS software to get our clients back up and running as using a keyboard and mouse work fine.
> > Edit: Even windows gestures stop working if the app is in fullscreen.
> 
> Did the problem persist on version 5.0.6 and higher?

We are releasing a new version of our app running electron 6 so will know then. However we are using the script from #8725 which seems to have helped the issue. Bit hard to not include it.

**Comment by u4aew** [comment]
Hi everyone, starting from version 5.0.6 I have no problems
