### ISSUE TITLE
SVG is being cached even after deletion of all cached data?

### ISSUE THREAD

**Issue by buffet-time** [electron/electron#17556]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.1.0
* **Operating System:**
  * Windows 10 x64 Enterprise (1803)

### Expected Behavior
SVG definition file shouldn't be cached somewhere randomly?

### Additional Information
I've deleted the folder of my application inside AppData Local, i've deleted the build and package electron folders as well as removed node modules and reinstalled all of them, and have made the SVG file definition contain only 1 svg instead of dozens yet it still persists with the previous version of the SVG file somehow?

I'm completely baffled by this, and no one else on my team has any clue where the file is being cached? This is just a standard Electron 4.1.0 app using Vue.js and Webpack...

**Comment by MarshallOfSound** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by buffet-time** [comment]
hmmm, i can't seem to reproduce this issue anymore. I have no idea what resolved it, likely some weird caching issue on my machine.

Closing.
