### ISSUE TITLE
Cookie hostOnly property is not set to true when domain doesn't start with a leading '.'

### ISSUE THREAD

**Issue by YounixM** [electron/electron#17564]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
v4.1.1 , v2.0.8

* **Operating System:**
MacOS Mojave 10.14.4

### Expected Behavior
hostOnly property should be set to true when the domain doesn't start with a leading '.' 

### Actual Behavior
hostOnly property is set to false even when the domain doesn't start with a leading '.' 

### To Reproduce

Case 1 : Set cookie with domain starting without a leading '.'
Case 2 : Set cookie with domain starting with a leading '.'

Cooke hostOnly property should be set to true in case of Case 1.

        
        let electronSession = require('electron').remote.session.fromPartition("test");
        let cookiesStore = electronSession.cookies;

        cookiesStore.get({}, (err, cookie) => { console.log(cookie) });

        let cookie1 = { 
          url: 'http://www.godofwar.com',
          name: 'testCookie1',
          value: '\'cookie1\'',
          domain: 'godofwar.com',
          secure: false,
          httpOnly: false,
          expirationDate: 2147483647,
          path: '/' 
        }

        let cookie2 = { 
          url: 'http://godofwar.com',
          name: 'testCookie2',
          domain: '.godofwar.com',
          value: '\'cookie2\'',
          secure: false,
          httpOnly: false,
          expirationDate: 2147483647,
          path: '/' 
        }

        let cookie3 = { 
          url: 'http://godofwar.com',
          name: 'testCookie3',
          value: '\'cookie3\'',
          secure: false,
          httpOnly: false,
          expirationDate: 2147483647,
          path: '/' 
        }

        cookiesStore.set(cookie1, (err) => { 
          cookiesStore.set(cookie2, (err) => { 
            cookiesStore.set(cookie3, (err) => { 
              cookiesStore.get({}, (err, cookie) => { console.log(cookie) });
                });
            });
        });

Console log

      [
        {
          "name": "testCookie1",
          "value": "'cookie1'",
          "domain": ".godofwar.com",
          "hostOnly": false,
          "path": "/",
          "secure": false,
          "httpOnly": false,
          "session": false,
          "expirationDate": 2147483647
        },
        {
          "name": "testCookie2",
          "value": "'cookie2'",
          "domain": ".godofwar.com",
          "hostOnly": false,
          "path": "/",
          "secure": false,
          "httpOnly": false,
          "session": false,
          "expirationDate": 2147483647
        },
        {
          "name": "testCookie3",
          "value": "'cookie3'",
          "domain": "godofwar.com",
          "hostOnly": true,
          "path": "/",
          "secure": false,
          "httpOnly": false,
          "session": false,
          "expirationDate": 2147483647
        }
      ]

### Screenshots
![Screenshot 2019-03-27 at 3 18 13 PM](https://user-images.githubusercontent.com/3520897/55066874-b3a05a80-50a4-11e9-9130-61812a31f86d.png)
<img width="1440" alt="Screenshot 2019-03-27 at 3 23 38 PM" src="https://user-images.githubusercontent.com/3520897/55066914-c4e96700-50a4-11e9-90e7-a2e83f8b955a.png">

**Comment by deepak1556** [comment]
The behavior is expected and is similar to chrome, which basically follows https://tools.ietf.org/html/rfc6265#section-5.3 . I think the documentation can be made clearer on the `hostOnly` attribute.

For example in chrome try the following in this page:

`document.cookie="test=cookie1;domain=github.com"` - check devtools and you will see a domain cookie with domain as `.github.com`

`document.cookie="test=cookie2"` - check devtools and you will see a host cookie with domain as `github.com`

**Comment by harryi3t** [comment]
@deepak1556 Thank you for pointing out the RFC, but I am finding it difficult to find the place where this behavior is documented.
It says
```
6.   If the domain-attribute is non-empty:

           If the canonicalized request-host does not domain-match the
           domain-attribute:

              Ignore the cookie entirely and abort these steps.

           Otherwise:

              Set the cookie's host-only-flag to false.

              Set the cookie's domain to the domain-attribute.

        Otherwise:

           Set the cookie's host-only-flag to true.

           Set the cookie's domain to the canonicalized request-host
```

What am I missing here?

**Comment by codebytere** [comment]
If the domain-attribute is non-empty:
* Set the cookie's host-only-flag to false.
Otherwise:
*  Set the cookie's host-only-flag to true.

this describes the above behavior as far as i can see, does it not @harryi3t? in the first two the domain attr was non-empty, and `hostOnly` was false. In the last, you passed no domain and `hostOnly` was true.

**Comment by YounixM** [comment]
@codebytere : 

If the below logic is followed, all subdomains will have access to the cookies set for a domain. ie hostOnly cookie set for the domain example.com, will be accessible by foo.example.com / bar.example.com.


Logic: 
If the domain-attribute is non-empty:

- Set the cookie's host-only-flag to false.

Otherwise:

- Set the cookie's host-only-flag to true.




comment by zcbenz  on https://github.com/electron/electron/issues/5836: 

```
session and hostOnly are not meaningful when setting cookie, if you don't set expirationDate, the cookie will have session: true, and if you the domain doesn't start with a leading ., hostOnly will be true.
```
