### ISSUE TITLE
Preload scripts can run twice in the same process in different node environments

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#17576]
### Issue Details

* **Electron Version:**
  * 3.x, 4.x, 5.x, 6.x
* **Operating System:**
  * All
* **Last Known Working Electron version:**:
  * 2.x

### Expected Behavior
When navigations occur, a new process should be created for the navigation.

### Actual Behavior
When a navigation occurs _during_ a preloads scripts execution the same process is re-used as Chromium does not think the navigation has been committed yet.  This causes a memory leak and all native node modules to break.

### To Reproduce
Fiddle: https://gist.github.com/MarshallOfSound/c89aa0037c3da114d44aa3a2d1a0fc24

### Screenshots
![image](https://user-images.githubusercontent.com/6634592/55097842-eb45dd00-5079-11e9-99bf-d49c0d997bca.png)

As you can see here there are three navigation loads, the second and the third one actually have the same process ID (and are running in the same process)

**Comment by miniak** [comment]
@MarshallOfSound can you share more details? Why wasn't this an issue in Electron 2?

**Comment by MarshallOfSound** [comment]
Merging into #18397 as the long term solution to this 👍
