### ISSUE TITLE
BrowserWindow.getSize() returning wrong width and height when fullscreened

### ISSUE THREAD

**Issue by buffet-time** [electron/electron#17580]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 4.1.1
* **Operating System:** Windows 10 x64 Enterprise (1803)

### Expected Behavior
[browserWindow.getSize()](https://electronjs.org/docs/api/browser-window#wingetsize ) should return back the correct width and height always.

### Actual Behavior
[browserWindow.getSize()](https://electronjs.org/docs/api/browser-window#wingetsize ) when fullscreened reports a slightly taller height and wider width than it actually is.

So a div in my application is being placed incorrectly and has contents that are not being seen due to this.

### Screenshots
This screenshot is not fullscreened 
![Capture](https://user-images.githubusercontent.com/11199709/55110428-645f2780-50ae-11e9-8fec-200c71b0e1eb.PNG)
This screen shot is when it is fullscreened, as you can see the footer that says the copyright is lower than it should be becuase it's getting the wrong height.
![Capture2](https://user-images.githubusercontent.com/11199709/55110429-645f2780-50ae-11e9-99ea-53349f13b35e.PNG)

**Comment by pbrahmbhatt3** [comment]
can I work on this?

**Comment by sofianguy** [comment]
@pbrahmbhatt3 yes, we welcome PRs. Please follow our [contributing guide](https://github.com/electron/electron/blob/master/CONTRIBUTING.md)

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
