### ISSUE TITLE
electron version without devtools 'lite'

### ISSUE THREAD

**Issue by annymosse** [electron/electron#17599]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an feature request that matches the one I want to file, without success.

### Problem Description
i want to get Electron pre-built version without devtools ,that make electron small size,harder for reverse engineer ,less development for production environment  

### Alternatives Considered
exclude devtools files(c,h,cpp..) these make devtools ui

### Additional Information
if there is an ability to exclude/remove tabs and extensions support also that make electron supper smaller

**Comment by MarshallOfSound** [comment]
> i want to get Electron pre-built version without devtools ,that make electron small size

Not much smaller to be honest

> harder for reverse engineer

Your app is javascript, reverse engineering it is easy, independent of it containing devtools (you can easily attach an external set of devtools to the app)

This isn't something we can invest time in to so I'm going to close this as a `wontfix` for now 👍
