### ISSUE TITLE
Error loading ssh2/lib/buffer-helpers

### ISSUE THREAD

**Issue by caique0202** [electron/electron#17608]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
v4.0.8
* **Operating System:**
  * 
18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
Applicable to all
* **Last Known Working Electron version:**:
  * 

### Expected Behavior

Electron is not loading any page due to this error. PRODUCTION ONLY. Works in DEVELOPMENT.
### Actual Behavior

Error loading ssh2/lib/buffer-helpers
Uncaught Error: Cannot find module 'APP/Contents/Resources/app.asar/buffer-helpers'

**Comment by caique0202** [comment]
I found the fix for this.

**Comment by jadamsdb** [comment]
What was the fix?
