### ISSUE TITLE
Inconsistency between help and behaviour re: connecting to a URL

### ISSUE THREAD

**Issue by dorfsmay** [electron/electron#17609]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  v4.1.1
* **Operating System:**
  Ubuntu 16.04, Windows 10

### Expected Behavior
Electron help prints:

```
Usage: electron [options] [path]

A path to an Electron app may be specified. It must be one of the following:
  - index.js file.
  - Folder containing a package.json file.
  - Folder containing an index.js file.
  - .html/.htm file.
  - http://, https://, or file:// URL.
```

From this help, I expect using a URL instead of a directory to work the same way, but instead it just display the content of files. Expected behaviour:

* open electron window
* display "We are using Node.js 10.11.0, Chromium 69.0.3497.128, and Electron 4.1.1."

### Actual Behavior
* open electron window
* display "We are using Node.js , Chromium , and Electron ."

### To Reproduce
* npm -g install serve
* git clone https://github.com/electron/electron-quick-start
* `electron .` ==> Works as expected, display "We are using Node.js 10.11.0, Chromium 69.0.3497.128, and Electron 4.1.1."
* quit
* server -s .
* open another window and run
  * `electron http://localhost:5000` ==> Display the content of the index.html, but does not exectue the apps, displays: "We are using Node.js , Chromium , and Electron ."

### Additional Information
If electron is supposed to behave this way, not being able to load apps from a remote file structure served over http, then the help message should be change to reflect this. If it is supposed to run the same way as if the file were local, then there is a bug.

**Comment by MarshallOfSound** [comment]
@dorfsmay This is working as expected, when we load a remote URL (in this case an `http://` url) we disable `nodeIntegration` as per our [Security Guidelines](https://electronjs.org/docs/tutorial/security#2-disable-nodejs-integration-for-remote-content).  So we are loading the same HTML file but it doesn't have node enabled so it can't get the versions of node/chromium/electron

**Comment by dorfsmay** [comment]
To avoid confusion, could this be added to the "help" printed from electron?

**Comment by MarshallOfSound** [comment]
@dorfsmay That kind of information is no longer required on Electron 5.0 and higher as node is disabled by default for all windows.  You have to explicitly enable it

**Comment by dorfsmay** [comment]
Can it be enabled when loading a URL? How will it be enable in 5.0? Via code in the main.js or through a command line option?
