### ISSUE TITLE
video play only sound but no picture

### ISSUE THREAD

**Issue by jackple** [electron/electron#17607]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* x[ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.1.1
* **Operating System:**
  *  Windows 7/8/10
* **Last Known Working Electron version:**:
  * none

### Expected Behavior
every video always can be played

### Actual Behavior
![image](https://user-images.githubusercontent.com/6183232/55237946-40e2db00-526e-11e9-879a-3ee8e522aae0.png)

### Screenshots

![image](https://user-images.githubusercontent.com/6183232/55237973-56f09b80-526e-11e9-8353-efe94f1c5d49.png)

### Additional Information
When my electron is installed, it is ok, the mp4 file can be played perfectly. But after a while, 1 or 2 hours, the video tag get blank!

I have try 3.x and 4.x, and it has the same problem!

**Comment by 1024642475** [comment]
well

**Comment by Skittocomilla** [comment]
I lobe this app

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by sandeep1995** [comment]
I having a similar issue. Anyone?
