### ISSUE TITLE
20 second delay before main process REST server can receive message from renderer process

### ISSUE THREAD

**Issue by russfleming** [electron/electron#17600]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.1.1
* **Operating System:**
  * Windows 10 Enterprise 64 bit
* **Last Known Working Electron version:**:
  * 

### Expected Behavior
Not expecting there to be any extra delay in the main process' REST server to receive a message from the renderer process sending an HTTP GET to localhost when application first starts up.

### Actual Behavior
There is about a 20 second delay from application start up before the Express REST server that is started in the main process to be able to receive and process REST messages.  After about 20 seconds after app start up, the REST server responds normally.

### To Reproduce
A sample application based on the electron-quick-start repo has been created that demonstrates this.  

In the index.html, some code has been added that runs on web page instantiation that makes an HTTP GET call to the REST server running in the main process.  When the message is sent on start up, the 20 second delay is logged when the reply comes back from the server.

An Express server has been added to the end of main.js that provides a 'test' REST message API.  

A button has been added to the GUI to allow for the message to be sent.  The elapsed time is logged to the console.

The code is available at: https://github.com/russfleming/electron-rest-delay.git

```sh
$ git clone https://github.com/russfleming/electron-rest-delay.git
$ cd electron-rest-delay
$ npm install
$ npm start
```

**Main process REST server:**
```javascript
// === Add a REST Express server to this Electron main process to demonstrate the first message delay
const express = require("express");
const http = require("http");

let expressApp = express();

// --- setup REST server
expressApp.set("port", 8088);
let httpServer = http.createServer(expressApp);
httpServer.listen(8088);

// --- Test REST message
expressApp.get("/test", (req, res) => {
  console.log("REST server: Got test REST message");
  res.status(200).send({ "result": true });
});
```

**Renderer process REST server:**
```javascript
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
  </head>
  <body>
    <h1>Hello World!</h1>
    <!-- All of the Node.js APIs are available in this renderer process. -->
    We are using Node.js <script>document.write(process.versions.node)</script>,
    Chromium <script>document.write(process.versions.chrome)</script>,
    and Electron <script>document.write(process.versions.electron)</script>.

    <br><br><br>
    <button onclick="sendTestMsg()">Send REST message</button>

    <script>
      // You can also require other files to run in this process
      require('./renderer.js')

      // send the 'test' REST message to the main process, which isn't availble for 
      // about the first 20 seconds after application start-up
      function sendTestMsg() {
        const startTime = process.hrtime();
        const Http = new XMLHttpRequest();
        const url = 'http://localhost:8088/test';
        Http.open("GET", url);
        console.log("About to send REST test message");
        Http.send();
        Http.onreadystatechange = (e) => {
          if (Http.readyState == 4 && Http.status == 200) {
            const endTime = process.hrtime(startTime);
            const elapsed = "" + endTime[0] + "." + Math.trunc(endTime[1] / 1000000);
            console.log("Elapsed time: " + elapsed + " " + Http.responseText)
          }
        }
      }

      sendTestMsg();  // will result in about 20 second elapsed time

    </script>
  </body>
</html>
```
### Screenshots

**Sample output:**
<img width="740" alt="electron-rest-delay" src="https://user-images.githubusercontent.com/9358069/55198099-ee23f900-5171-11e9-8e95-728430a2ab24.png">

**Comment by harryi3t** [comment]
@russfleming I cloned your repo to reproduce this.
In my case, it opened within 0.2-0.4 ms
### OSX 10.14.4 (Mojave)
![image](https://user-images.githubusercontent.com/5207331/58471223-fa700680-8160-11e9-9e80-f9eff68dac72.png)

### Windows 10

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
