### ISSUE TITLE
Mock a http response seamlessly

### ISSUE THREAD

**Issue by cuixiping** [electron/electron#17618]
I want to mock a response seamlessly with local data, without redirect to another url, when render processes send http request.

Is it possible?

The following code explains my idea.

```
webRequest.filterRequest((req, res, passthrough) => {
    if (req.url == 'https://github.com/') {
        //res.status(200).sendFile('/path/to/hello.htm');
        res.status(200).sendText('hello');
    } else {
        passthrough();
    }
})
```

Looks like a proxy but is different.

`webRequest.onBeforeRequest` can redirect to another url. but cannot send a response directly without change the url.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
