### ISSUE TITLE
"pointer being freed was not allocated" when loading specific URLs over interceptStreamProtocol

### ISSUE THREAD

**Issue by pwnsdx** [electron/electron#17617]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.0-beta.7
* **Operating System:**
  * macOS Mojave 10.14.4
* **Last Known Working Electron version:**:
  * 4.X, bug is likely due to the PR of another bug that has been fixed: #17264

### Expected Behavior

It should load the video properly.

### Actual Behavior

The application crash with the following:

Electron(1492,0x700004426000) malloc: *** error for object 0x7fc38f8570a8: pointer being freed was not allocated
Electron(1492,0x700004426000) malloc: *** set a breakpoint in malloc_error_break to debug

### To Reproduce

Run the following Electron Fiddle: https://gist.github.com/639ca7f541ccd229483d8655c0c0f5a4

**Comment by pwnsdx** [comment]
cc @deepak1556 @codebytere

**Comment by codebytere** [comment]
@pwnsdx i just tested this on a local branch after reverting https://github.com/electron/electron/pull/17221 and the crash still occurs, so unfortunately it's not that. I'll keep digging and see what i can turn up!

**Comment by jkleinsc** [comment]
Fixed via #17752

**Comment by pwnsdx** [comment]
Amazing! Thank you so much!
