### ISSUE TITLE
Feature request: Response to a request directly

### ISSUE THREAD

**Issue by cuixiping** [electron/electron#17619]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an feature request that matches the one I want to file, without success.

### Problem Description

I need a way to give custom responses directly for some http requests from render process.

The page url should not be navigate to another url.

The virtual code explains what I want to do. (Electron has no this api.)

```
webRequest.filterRequest((req, res, passthrough) => {
    if (req.url == 'https://github.com/') {
        //res.status(200).sendFile('/path/to/hello.htm');
        res.status(200).sendText('HELLO');
    } else {
        passthrough();
    }
})
```

When electron run `mainWindow.loadURL('https://github.com/')`, user can see `HELLO` instead of github page. But the page's location is still `https://github.com/`

### Additional Information

Currently, `webRequest.onBeforeRequest` can redirect a request to another url. but cannot send a response directly without change the url.

**Comment by pwnsdx** [comment]
Hello,

You'll need to use `protocol.interceptStreamProtocol` to intercept the https protocol which does that for you. Note that due to #15434 not being in Electron yet, you'll have to replicate the whole behaviour of a browser. I was able to do that here: https://github.com/wireapp/wire-desktop-packages/blob/a835e311dbd664bfa966f3104974bf1d016dd017/packages/desktop-updater/src/main/Networking.ts#L188

Good luck

**Comment by Skittocomilla** [comment]
There is no one who can help me a little in this world of God. Please help me a little bit. Useful sending address. HOSEN PATUARY, MUTUAL TRUST BANK LTD BANGLADESH, A / C NO: 0520310026251 COMILLA BRUNCH

**Comment by pwnsdx** [comment]
I don't think that's the right place to ask for money. Maybe try gofundme.com

**Comment by MarshallOfSound** [comment]
Please do not raise duplicates of your own issues...

https://github.com/electron/electron/issues/17618
