### ISSUE TITLE
Provide instructions to build and debug libchromiumcontent on Mac OS X

### ISSUE THREAD

**Issue by bobpappas** [electron/electron#1762]
It is pretty hard to quickly figure out how to build libchromiumcontent for debug within Electron.

Can someone post the recipe for this? I'd like to debug some Chromium specific issues while using Electron.

**Comment by bobpappas** [comment]
Hi there, can I get a feel for how this issue is prioritized and when it will be addressed?

**Comment by bobpappas** [comment]
@zcbenz Is this something you can help me with?

**Comment by bobpappas** [comment]
@zcbenz ping

**Comment by zcbenz** [comment]
Building and debugging libchromiumcontent is basically the same with building and debugging Chromium, the dev website of Chromium has good documents for this:
http://dev.chromium.org/developers/how-tos/debugging-on-os-x
