### ISSUE TITLE
API  tray.destroy is not working 

### ISSUE THREAD

**Issue by rhythm-sharma** [electron/electron#17622]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  4.0.4
* **Operating System:** 
  *  Ubuntu 18.10 x64

### Expected Behavior

 Observed in Zulip desktop app
 1. ```tray.destroy()``` api should destroy tray icon in panel
 2.  ```show app tray icon``` option in general setting, it should destroy and create tray icon on toggle

### Actual Behavior

Previous tray icon are not destroy on toggle and new icon created i.e ```tray.destroy``` API is not working 

![Screenshot from 2019-03-30 18-57-58](https://user-images.githubusercontent.com/36422396/55276803-eacd7080-531d-11e9-842b-8d15bcfc09dd.png)

### To Reproduce

```
$ git clone https://github.com/zulip/zulip-electron
$ cd zulip-electron
$ npm install
$ npm start
```
you can find code in ``` zulip-electron/app/renderer/js/tray.js ```

```
function toggleTray() {
	let state;
	if (window.tray) {
		state = false;
		window.tray.destroy();
		if (window.tray.isDestroyed()) {
			window.tray = null;
		}
		ConfigUtil.setConfigItem('trayIcon', false);
	} else {
		state = true;
		createTray();
		if (process.platform === 'linux' || process.platform === 'win32') {
			renderNativeImage(unread).then(image => {
				window.tray.setImage(image);
				window.tray.setToolTip(unread + ' unread messages');
			});
		}
		ConfigUtil.setConfigItem('trayIcon', true);
	}
	const selector = 'webview:not([class*=disabled])';
	const webview = document.querySelector(selector);
	const webContents = webview.getWebContents();
	webContents.send('toggletray', state);
}
```

### Screenshots

![Image 2019-03-17 at 12 45 47 PM](https://user-images.githubusercontent.com/36422396/55276412-7395dd80-5319-11e9-9032-8da0050cd16c.jpeg)

**Comment by rrhythmsharma** [comment]
@MarshallOfSound  can you please review this ?

**Comment by chfanghr** [comment]
my work around:Spawn a new process to show tray

**Comment by chfanghr** [comment]
KDE and GNOME have the same ploblem that caused by the desktop itself,so the only thing we can do is to work around.

**Comment by rrhythmsharma** [comment]
@chfanghr can you guide me on this issue how to solve it, is thier another API should i try

**Comment by rrhythmsharma** [comment]
> KDE and GNOME have the same ploblem that caused by the desktop itself,so the only thing we can do is to work around.

i tried alt + f2 -> r, it solve this on temporary basis

**Comment by chfanghr** [comment]
will,brilliant,i will have a try

Rhythm Sharma <notifications@github.com> 于2019年3月30日周六 下午9:51写道：

**Comment by rrhythmsharma** [comment]
@chfanghr 
Though, I hit [this Gnome Shell bug](https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/1796607), and my Gnome crashed a couple of times, before I figured out what was happening!

**Comment by chfanghr** [comment]
you should try kde,at least it doesn't crash

**Comment by rrhythmsharma** [comment]
@chfanghr i read about ```GtkStatusIcon``` in Tray documentation [here](https://electronjs.org/docs/api/tray) under Platform limitations section, would you please tell me how to install in ubuntu

**Comment by chfanghr** [comment]
[Instructions here](https://linuxconfig.org/how-to-install-kde-plasma-desktop-on-ubuntu-18-04-bionic-beaver-linux).Also ,you can use kubuntu image directly.

**Comment by chfanghr** [comment]
And you may have to replace your login manager with sddm.

**Comment by rrhythmsharma** [comment]
I don't know much about GtkStatusicon, if you know something then tell me about it(how to install)

**Comment by chfanghr** [comment]
Oh sorry .GtkStatusion is a part of gnome so you don't have to install it Manually  . As for libappindicator1 ,you can install it with apt .But actually it doesn't solve this issue.

**Comment by rrhythmsharma** [comment]
Thanks, okay it cleared my concept

**Comment by chfanghr** [comment]
If you want a better Tray experience,you may want to try qt.But I wonder how they achieve it.

**Comment by rrhythmsharma** [comment]
Hmm, let try something out with qt

**Comment by chfanghr** [comment]
Using KDE's native API sovle this issue,but that's annoying....

**Comment by rrhythmsharma** [comment]
can provide a link for KDE native API

**Comment by chfanghr** [comment]
https://api.kde.org/pykde-4.4-api/kdeui/KSystemTrayIcon.html

**Comment by chfanghr** [comment]
But now I have to manage my codebase in five languages...GOD DAME

**Comment by rrhythmsharma** [comment]
that's really annoying :laughing:

**Comment by chfanghr** [comment]
Perhaps you can rewrite the application with PWA and wasm.Though you need chrome ,the  user experience will be better on every platforms.

**Comment by chfanghr** [comment]
check this : https://techbase.kde.org/Projects/Plasma/NewSystemTray

**Comment by rrhythmsharma** [comment]
@chfanghr  i has exams so sorry for late responding, I think it would be a bad option for me to dive deeper into the OS because I do not know much about them, I think we should see how other apps(like skype etc based on electron) are solving this issue because it is a problem with electron and linux

**Comment by chfanghr** [comment]
ok,did you make any progress?

**Comment by rrhythmsharma** [comment]
No progress

**Comment by chfanghr** [comment]
Update https://github.com/meetfranz/franz/issues/1377

**Comment by rrhythmsharma** [comment]
@sofianguy  It seems that @chfanghr  found a bug in tray implementation.

https://github.com/electron/electron/blob/e7c48922e77b0043f2d829b4e8c44c0d2b45d500/atom/browser/ui/tray_icon_gtk.cc#L20

When JavaScript api is called , the call will pass to this function to do the exact job , but as you can see, it just create a new tray without destroying the previous one , which may cause the issue.

@sofianguy please help us with solving this bug

**Comment by rrhythmsharma** [comment]
@codebytere  @miniak  
please help us with solving this bug

**Comment by codebytere** [comment]
@rrhythmsharma i've popped up a PR that i believe should ameliorate this!

**Comment by vsvipul** [comment]
@codebytere This doesn't fixed this issue. I think this needs to be reopened.

**Comment by aleksey-hoffman** [comment]
@codebytere could you please re-open this issue? It still occurs in Ubuntu 20.04 (electron: 10.1.3)

**Comment by EdvinM** [comment]
@codebytere the issue reappeared, electron 10.1.4, Ubuntu 18.

**Comment by RobinBobin** [comment]
> my work around:Spawn a new process to show tray

Could you explain how to do it, please?

**Comment by Simon-Laux** [comment]
still an issue in 12.0.1

**Comment by codebytere** [comment]
Looks like it may be this: https://bugs.launchpad.net/ubuntu/+source/libappindicator/+bug/1395229

i'll see if i can come up with a workaround

**Comment by Simon-Laux** [comment]
maybe related https://github.com/electron/electron/issues/27527

**Comment by Bilb** [comment]
Just bumped from electron
-    "electron": "8.2.0",
to
+    "electron": "^13.1.9",

and this bug started to appear. The destroy was working correctly before that.

**Comment by itsPG** [comment]
same on v17.4.11.

haven't tried the latest v21 though.

**Comment by itsPG** [comment]
Still reproducable on v17.4.11.

Hope someoe who encounters this issue could help us test the latest version.

I used a deprecated API and cannot upgrade right now.

**Comment by rak-phillip** [comment]
Not stale, able to repro on electron v20.3.8 in Ubuntu 22.04 Gnome. Would like to update to latest stable version of electron to confirm that this is still a problem.

**Comment by viktordw** [comment]
This was closed due to inactivity, but It seems this is still not resolved.
There is an [active issue](https://github.com/keeweb/keeweb/issues/1181) for keeweb project that is related to this.
