### ISSUE TITLE
I want to complete the action and load ready before the application is ready.

### ISSUE THREAD

**Issue by mtrucc** [electron/electron#17636]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an feature request that matches the one I want to file, without success.

### Problem Description
I want to complete the action and load ready before the application is ready.

### Proposed Solution
I want to be able to customize whether to load the proxy instead of locking it in the program.

```
const fs = require('fs');
const { app } = require('electron');
const PATH = app.getPath('userData');
const PROXY = "/proxy.db"

function readFile(path, callback) {
  fs.readFile(path, 'utf-8', function (err, data) {
    if (err) {
      console.error(err);
    } else {
      callback && callback(data);
    }
  })
}

function getProxyData(callback) {
  fs.stat(PATH + PROXY, function (err, stat) {
    if (stat && stat.isFile()) {
      readFile(PATH + PROXY, function (res) {
        let data = JSON.parse(res);
        if (data && data['no-proxy-server'] != undefined) {
          callback && callback(data);
        }
      })
    } else {
      readFile(path.join(__dirname, './data.json'), function (res) {
        let data = JSON.parse(res);
        if (data && data['no-proxy-server'] != undefined) {
          writeFile(PATH + PROXY, JSON.stringify(data), function () {
            callback && callback(data);
          })
        }
      })
    }
  });
}

function setBrowser() {
  getProxyData(data => {
    console.log("setBrowser()")
    for (let key in data) {
      if (data.hasOwnProperty(key)) {
        let value = data[key];
        value && app.commandLine.appendSwitch(key, value);
      }
    }
  })
}

function createWindow () {
  console.log("createWindow ()")
}

setBrowser()
app.on('ready', createWindow)

```
I need output:
```
setBrowser()
createWindow ()
```

but now output
```
createWindow ()
setBrowser()
```

Obviously fs is not finished reading and ready is loaded

I expect the fs to be read, then load "ready", or control "before the ready event"
https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md#supported-chrome-command-line-switches

Because I expect to be able to  use  "fs" read the user-defined settings file, then configure "Chrome Command Line Switches"

### Alternatives Considered
require("data.json") in Program directory
But if you don't have an administrator, you can't modify the file.

### Additional Information
none..

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
