### ISSUE TITLE
electron-pdf hangs indefinitevily on Lubuntu

### ISSUE THREAD

**Issue by MarcoSulla** [electron/electron#17631]
I tried to run `electron-pdf http://fraserxu.me test.pdf`, as suggested in the help, but it hangs indefinitively without any message. I tried gooogle.com too.

I also tried the solution [in this comment](https://github.com/fraserxu/electron-pdf/issues/233#issuecomment-461183337). It works for http://fraserxu.me but not for my html file, that is full of SVGs (maybe this is the problem)?

OS: Lubuntu 18.04.2 (Linux 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux)
Electron Version: 4.0.4

**Comment by codecounselor** [comment]
@MarcoSulla electron-pdf is a separate project.  You should close this issue and open one at https://github.com/fraserxu/electron-pdf
