### ISSUE TITLE
How to set cookie ?

### ISSUE THREAD

**Issue by HeiShanLaoYao889** [electron/electron#17637]
### How to set cookie?
When I entered my system, I needed to set the cookie. However, when I used the official method to set the cookie, the prompt failed all the time
```
const session = require('electron').remote.session;
const cookie = {url:'http://xxx.com' }
session.defaultSession.cookies.set(cookie,(error)=>{
        if (error) console.log(error)
    })
  session.defaultSession.cookies.flushStore(()=>{})

```
There is only one error message and no indication of the location of the error
![image](https://user-images.githubusercontent.com/24189898/55309855-90552100-5491-11e9-9873-8fd69588dc3b.png)

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
