### ISSUE TITLE
Menu role “windowMenu” incompletely renamed to “window”

### ISSUE THREAD

**Issue by k8stone** [electron/electron#17647]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * V5.0.0-beta.7
* **Operating System:**
  * macOS 10.13.6
* **Last Known Working Electron version:**:
  * 4.1.3

### Expected Behavior
My app used the “windowMenu” role for a menu template in Electron v4 which worked as expected.  In v5 my app failed to compile as TypeScript alerted me to a change in expected values.  I see the docs now reflect “window” as the correct value for this functionality so I changed and recompiled, expecting it to work...

### Actual Behavior
The “window” role is ignored and no menu appears as a result.  Changing my code to use (“windowMenu” as any) works as before.  It would seem the implementation is out of step with the TypeScript definitions and documentation.

**Comment by MarshallOfSound** [comment]
This appears to be a bug in our TS generator :thinking:

https://github.com/electron/electron/blob/5-0-x/docs/api/menu-item.md

**Comment by k8stone** [comment]
Curious.  The API documentation also references the form without “Menu”, at least at the moment:

https://electronjs.org/docs/api/menu#standard-menus

**Comment by MarshallOfSound** [comment]
@k8stone See the [`MenuItem`](https://electronjs.org/docs/api/menu-item) docs

> windowMenu - Whole default "Window" menu (Minimize, Close, etc.).

**Comment by k8stone** [comment]
Right.  Per my original report I'm using ("windowMenu" as any) to coerce TypeScript into accepting it.  I'm not blocked, just observing that this is clearly in something of an inconsistent state in the current beta.

**Comment by CvX** [comment]
These `role` values have been added to the docs in https://github.com/electron/electron/pull/16820/files#diff-27aca9003e7bfe3e2c635e67d04fc917L17, but that PR hasn't been merged to 5-0-x yet.
