### ISSUE TITLE
Disabling Eval doesn't

### ISSUE THREAD

**Issue by cawoodm** [electron/electron#17646]
### Issue Details
Trying to be real secure and deal with (i.e. prevent) this warning:
![image](https://user-images.githubusercontent.com/498834/55357254-dda2b400-54cc-11e9-9692-a76306d5c337.png)

* **Electron Version:**
  * 4.0.6
* **Operating System:**
  * Windows 10, Chrome Latest (73)

### Expected Behavior
Don't want a warning.

It seems electron tries to run JS code with `require('electron').executeJavaScript` and, if it succeeds, considers this unsafe:
![image](https://user-images.githubusercontent.com/498834/55357191-b0560600-54cc-11e9-8d15-46f1c6e59633.png)

I tried to disable `eval()` and get rid of the security warning using `allowEval: false` but the warning still appears and `require('electron').executeJavaScript()` functions as eval().

Interestingly, the [security checklist](https://electronjs.org/docs/tutorial/security) doesn't mention `allowEval` (which I googled) and it doesn't seem to have any effect - the warning still appears with this setup:

```
const win = new electron.BrowserWindow({
		webPreferences: {
			nodeIntegration: true,
			contextIsolation: true,
			allowEval: false
		}
	});
```

### Actual Behavior
The warning appears no matter what.

### To Reproduce
https://github.com/cawoodm/powowshell

`git clone` and then `electron .`

**Comment by MarshallOfSound** [comment]
@cawoodm The `allowEval` option does not exist --> https://github.com/electron/electron/blob/master/docs/api/browser-window.md

I don't know where you saw that option but as you noted it's not in our guides (because it doesn't exist).

I'm going to close this out but if I missed something here please @ mention me in a follow up below

**Comment by cawoodm** [comment]
Okaaay... so you have this warning which is checking whether arbitrary JS can be executed (which it can) and your checklist (linked to by the warning) doesn't explicitly address this issue nor does it mention any "unsafe-eval" which the warning does... what is a humble electron developer to do to appease the warning?

**Comment by aschultz** [comment]
@cawoodm You need to configure a Content Security Policy with a "script-src" value that does not contain "unsafe-eval". If you don't have a CSP or it has "unsafe-eval", you'll get the warning.

See the [security tutorial](https://github.com/electron/electron/blob/master/docs/tutorial/security.md) for how to configure a CSP. If you load your HTML pages via file://, make sure to use the meta tag.
