### ISSUE TITLE
Received signal 11 SEGV_MAPERR 000000000000 when using npm module rather than browserify

### ISSUE THREAD

**Issue by gannons** [electron/electron#17645]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v4.0.8
* **Operating System:**
  * macOS 10.14.3 
* **Last Known Working Electron version:**:
  * N/A / Using browserify

### Expected Behavior
Render Process does not crash.

### Actual Behavior
I've a project with a dependency on [spark-js-sdk](https://github.com/webex/spark-js-sdk). When I use a browserified version of the sdk (built from source) it works. When I switch over to using the officially npm module, ciscospark, it partially works but ultimately crashes. i.e. The App turns white and a RenderProcess dies. If I've the dev tools open after the crash they state

> DevTools was disconnected from the page.
> Once page is reloaded, DevTools will automatically reconnect.

When I 

    export ELECTRON_ENABLE_STACK_DUMPING=true

I see the following in the console

    Received signal 11 SEGV_MAPERR 000000000000
     [0x0001081624ec]
     [0x0001081623d1]
     [0x7fff7a1f4b3d]
     [0x7fed00000022]
     [0x00010b1c5b41]
     [0x000107415208]
     [0x0001073deb1d]
     [0x0001073de12a]
     [0x000107d25a8e]

### To Reproduce
Would love to strip the app down and provide a means of reproduction. But I've yet to identify what specific area causes the crash and I'm not entitled to release the overall project.

### Additional Information
Given the above limits I don't know if anyone will be able to, given the context, tell me what the solution is. But I'm hoping people with more experience can point out how to debug this issue. Ideally to identify what's causing the problem as currently I've little info to work with.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by gannons** [comment]
Documented this and the solution on StackOverflow

https://stackoverflow.com/questions/55032227/tips-on-solving-devtools-was-disconnected-from-the-page-and-electron-helper-di
