### ISSUE TITLE
Degraded UI performance from 2.x to 3.x/4.x (GPU not enabled?)

### ISSUE THREAD

**Issue by AoDev** [electron/electron#17641]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 3.x -> 4.1.3  (haven't tested all in between)
* **Operating System:**
  * OSX 10.11.6
* **Last Known Working Electron version:**:
  * 2.0.9

### Expected Behavior
When I update Electron from 2.0.9 to 4.1.3, I expect the UI performance to be the same (or better).

### Actual Behavior
UI performance is degraded. 
- eg1: in animated charts (using chart-js / react), animations are smooth in 2.0.9, choppy in 4.1.3.
- eg2:  navigating in the app is also lagging while some operations are being done, like having a submit button showing a loading animation.

### To Reproduce
- Simply switching from 2.0.9 to 4.1.3 in my app.
I'll create a repository if necessary, later.

### Additional Information
I have compared performance profiles from chrome developer tools.

What I noted is that:
- in v2.0.9, I have __1 GPU thread__ showing + __1 rasterizer thread__.
- in v4.1.3, I have __2 rasterizer threads__ but __no GPU__.

Profile screenshot:
![electron_2 0 9-4 1 3](https://user-images.githubusercontent.com/1526150/55321189-51b36c80-5479-11e9-8529-25aeacd72f91.png)

So I was wondering if this is the issue and something is disabling the GPU rendering. I don't know much about options nor how to interpret the lack of GPU row in the profile. I looked in docs, found gpuInfo in case it's useful, here is the output.

```json
{
  "auxAttributes": {
    "amdSwitchable": false,
    "canSupportThreadedTextureMailbox": false,
    "directRendering": true,
    "glExtensions": "GL_ARB_blend_func_extended GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_ES2_compatibility GL_ARB_explicit_attrib_location GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader5 GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_occlusion_query2 GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_subroutine GL_ARB_shading_language_include GL_ARB_tessellation_shader GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_texture_storage GL_ARB_texture_swizzle GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_vertex_attrib_64bit GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_EXT_texture_sRGB_decode GL_APPLE_client_storage GL_APPLE_container_object_shareable GL_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_texture_range GL_ATI_texture_mirror_once GL_NV_texture_barrier",
    "glRenderer": "Intel Iris OpenGL Engine",
    "glResetNotificationStrategy": 0,
    "glVendor": "Intel Inc.",
    "glVersion": "4.1 INTEL-10.14.74",
    "inProcessGpu": false,
    "initializationTime": 285,
    "jpegDecodeAcceleratorSupported": false,
    "maxMsaaSamples": "8",
    "oopRasterizationSupported": true,
    "optimus": false,
    "passthroughCmdDecoder": false,
    "pixelShaderVersion": "4.10",
    "sandboxed": false,
    "softwareRendering": false,
    "vertexShaderVersion": "4.10",
    "videoDecodeAcceleratorFlags": 0,
    "videoDecodeAcceleratorSupportedProfile": {
      "encrypted_only": false,
      "maxResolutionHeight": 2160,
      "maxResolutionWidth": 4096,
      "minResolutionHeight": 16,
      "minResolutionWidth": 16,
      "profile": 3
    },
    "videoEncodeAcceleratorSupportedProfile": {
      "maxFramerateDenominator": 1,
      "maxFramerateNumerator": 30,
      "maxResolutionHeight": 2160,
      "maxResolutionWidth": 4096,
      "profile": 3
    }
  },
  "gpuDevice": [
    {
      "active": true,
      "deviceId": 2606,
      "deviceString": "Intel Iris OpenGL Engine",
      "driverVendor": "INTEL",
      "driverVersion": "10.14.74",
      "vendorId": 32902,
      "vendorString": "Intel Inc."
    }
  ],
  "machineModelName": "MacBookPro",
  "machineModelVersion": "11.1"
}
```

**Comment by robatwilliams** [comment]
It appears from the `getGPUInfo()` output that hardware acceleration is in use (`glRenderer`, `softwareRendering`, `gpuDevice.active`).

I see you're using a 13-inch Retina MacBook from Late 2013 or Mid 2014. The device ID for your Intel Iris GPU from the output above (`0A2E` in hexadecimal) is not specifically on Chromium's [software rendering list](https://cs.chromium.org/codesearch/f/chromium/src/gpu/config/software_rendering_list.json).

I see you are using mac OS 10.11.6 (latest El Capitan (originally released 2015, .6 originally in July 2016)). You may be affected by the following rule from the software rendering list - all El Capitan runners with an Intel GPU (that's their vendor code):

```
{
      "id": 151,
      "description": "Rendering artifacts on older macOS releases and Intel GPUs",
      "cr_bugs": [794819],
      "os": {
        "type": "macosx",
        "version": {
          "op": "<=",
          "value": "10.11"
        }
      },
      "vendor_id": "0x8086",
      "multi_gpu_category": "any",
      "features": [
        "accelerated_2d_canvas",
        "gpu_rasterization"
      ]
    }
```

The rule exists due to (and references) this ["794819 [Mac] Canary Chrome 65 - Display appears broken/tearing/shearing like shattered glass, pixelated"](https://bugs.chromium.org/p/chromium/issues/detail?id=794819) Chromium bug. This may be a new rule added between Chromium 61 and Chromium 69 (which are [used by](https://github.com/electron/releases) Electron 2, 4 respectively), hence causing the regression in performance. Looking at the blame (top right > Layers menu > Blame) of the [software rendering list](https://cs.chromium.org/chromium/src/gpu/config/software_rendering_list.json?q=software_rendering_list&sq=package:chromium&g=0&l=1580), it shows it was added on 2017-12-20 as a resolution to the aforementioned bug. So that must be it.

You could verify this further:
1. What does `getGPUFeatureStatus()` output?
2. Using Google Chrome / Chromium (latest version will do for now; the list is probably unchanged), what does chrome://gpu output? (the entire page, not the partial info that the "copy" button gives you)

**Comment by AoDev** [comment]
@robatwilliams Wow, thanks for the reply. It seems you are totally correct. Wow.

Not sure what to do now, though.

## app.getGPUFeatureStatus()

  |         Property          |v2.0.9     | v4.3.1           |
  |---------------------------|-----------|------------------|
  |2d_canvas                  |  enabled  | disabled_software|
  |checker_imaging            |  disabled_off | |
  |flash_3d                   |  enabled  | disabled_software|
  |flash_stage3d              |  enabled  | disabled_software|
  |flash_stage3d_baseline     |  enabled  | disabled_software|
  |gpu_compositing            |  enabled  | disabled_software|
  |multiple_raster_threads    |  enabled_on | enabled_on|
  |native_gpu_memory_buffers  |  enabled  | enabled|
  |oop_rasterization          |           | disabled_off|
  |protected_video_decode     |           | disabled_off|
  |rasterization              |  disabled_software | disabled_software|
  |skia_deferred_display_list |           |disabled_off|
  |skia_renderer | |disabled_off|
  |surface_synchronization | |enabled_on|
  |video_decode               |  enabled | disabled_software|
  |video_encode               |  enabled | |
  | viz_display_compositor    |          | disabled_off|
  |webgl                      |  enabled | disabled_off|
  |webgl2                     |  enabled | disabled_off|

## This is chrome://gpu (on Chrome 73)
```
Graphics Feature Status
Canvas: Software only, hardware acceleration unavailable
Flash: Hardware accelerated
Flash Stage3D: Hardware accelerated
Flash Stage3D Baseline profile: Hardware accelerated
Compositing: Hardware accelerated
Multiple Raster Threads: Enabled
Native GpuMemoryBuffers: Hardware accelerated
Out-of-process Rasterization: Unavailable
Hardware Protected Video Decode: Unavailable
Rasterization: Unavailable
Skia Renderer: Disabled
Surface Control: Disabled
Surface Synchronization: Enabled
Video Decode: Hardware accelerated
Viz Service Display Compositor: Enabled
WebGL: Hardware accelerated
WebGL2: Hardware accelerated
Driver Bug Workarounds
add_and_true_to_loop_condition
adjust_src_dst_region_for_blitframebuffer
avoid_stencil_buffers
clamp_texture_base_level_and_max_level
decode_encode_srgb_for_generatemipmap
disable_2d_canvas_auto_flush
disable_av_sample_buffer_display_layer
disable_framebuffer_cmaa
disable_webgl_rgb_multisampling_usage
dont_use_loops_to_initialize_variables
emulate_abs_int_function
get_frag_data_info_bug
init_one_cube_map_level_before_copyteximage
max_msaa_sample_count_4
msaa_is_slow
pack_parameters_workaround_with_pack_buffer
rebind_transform_feedback_before_resume
regenerate_struct_names
remove_invariant_and_centroid_for_essl3
reset_base_mipmap_level_before_texstorage
rewrite_float_unary_minus_operator
rewrite_texelfetchoffset_to_texelfetch
scalarize_vec_and_mat_constructor_args
set_zero_level_before_generating_mipmap
unfold_short_circuit_as_ternary_operation
unpack_alignment_workaround_with_unpack_buffer
unpack_image_height_workaround_with_unpack_buffer
use_intermediary_for_copy_texture_image
use_unused_standard_shared_blocks
disabled_extension_GL_KHR_blend_equation_advanced
disabled_extension_GL_KHR_blend_equation_advanced_coherent
Problems Detected
Rendering artifacts on older macOS releases and Intel GPUs: 794819
Disabled Features: accelerated_2d_canvas, gpu_rasterization
Protected video decoding with swap chain is for Windows and Intel only
Disabled Features: protected_video_decode
Unfold short circuit on Mac OS X: 307751
Applied Workarounds: unfold_short_circuit_as_ternary_operation
Always rewrite vec/mat constructors to be consistent: 398694
Applied Workarounds: scalarize_vec_and_mat_constructor_args
Mac drivers handle struct scopes incorrectly: 403957
Applied Workarounds: regenerate_struct_names
On Intel GPUs MSAA performance is not acceptable for GPU rasterization: 527565
Applied Workarounds: msaa_is_slow
glGenerateMipmap fails if the zero texture level is not set on some Mac drivers: 560499
Applied Workarounds: set_zero_level_before_generating_mipmap
Pack parameters work incorrectly with pack buffer bound: 563714
Applied Workarounds: pack_parameters_workaround_with_pack_buffer
Alignment works incorrectly with unpack buffer bound: 563714
Applied Workarounds: unpack_alignment_workaround_with_unpack_buffer
copyTexImage2D fails when reading from IOSurface on multiple GPU types.: 581777
Applied Workarounds: use_intermediary_for_copy_texture_image
Multisample renderbuffers with format GL_RGB8 have performance issues on Intel GPUs.: 607130
Applied Workarounds: disable_webgl_rgb_multisampling_usage
Use GL_INTEL_framebuffer_CMAA on ChromeOS: 535198
Applied Workarounds: disable_framebuffer_cmaa
glGetFragData{Location|Index} works incorrectly on Max: 638340
Applied Workarounds: get_frag_data_info_bug
glResumeTransformFeedback works incorrectly on Intel GPUs: 638514
Applied Workarounds: rebind_transform_feedback_before_resume
glTexStorage* are buggy when base mipmap level is not 0: 640506
Applied Workarounds: reset_base_mipmap_level_before_texstorage
Result of abs(i) where i is an integer in vertex shader is wrong: 642227
Applied Workarounds: emulate_abs_int_function
Rewrite texelFetchOffset to texelFetch for Intel Mac: 642605
Applied Workarounds: rewrite_texelfetchoffset_to_texelfetch
Rewrite condition in for and while loops for Intel Mac: 644669
Applied Workarounds: add_and_true_to_loop_condition
Do TexImage2D first before CopyTexImage2D for cube map texture on Intel Mac 10.11: 648197
Applied Workarounds: init_one_cube_map_level_before_copyteximage
Decode and encode before generateMipmap for srgb format textures on macosx: 634519
Applied Workarounds: decode_encode_srgb_for_generatemipmap
Insert statements to reference all members in unused std140/shared blocks on Mac: 618464
Applied Workarounds: use_unused_standard_shared_blocks
Tex(Sub)Image3D performs incorrectly when uploading from unpack buffer with GL_UNPACK_IMAGE_HEIGHT greater than zero on Intel Macs: 654258
Applied Workarounds: unpack_image_height_workaround_with_unpack_buffer
adjust src/dst region if blitting pixels outside read framebuffer on Mac: 644740
Applied Workarounds: adjust_src_dst_region_for_blitframebuffer
Mac driver GL 4.1 requires invariant and centroid to match between shaders: 639760, 641129
Applied Workarounds: remove_invariant_and_centroid_for_essl3
Disable KHR_blend_equation_advanced until cc shaders are updated: 661715
Applied Workarounds: disable(GL_KHR_blend_equation_advanced), disable(GL_KHR_blend_equation_advanced_coherent)
Rewrite -float to 0.0 - float for Intel Mac: 672380
Applied Workarounds: rewrite_float_unary_minus_operator
Certain Apple devices leak stencil buffers: 713854
Applied Workarounds: avoid_stencil_buffers
Fullscreen video crashes macOS 10.11 WindowServer.: 806506
Applied Workarounds: disable_av_sample_buffer_display_layer
Shader variable initialization in a loop caused perf regression on Mac Intel.: 809422
Applied Workarounds: dont_use_loops_to_initialize_variables
8x MSAA is slow for alpha:false WebGL contexts on Mac Intel: 812071
Applied Workarounds: max_msaa_sample_count_4
glFlush error on Mac: 841755
Applied Workarounds: disable_2d_canvas_auto_flush
Clamp texture's BASE_LEVEL/MAX_LEVEL for GenerateMipmap: 913301
Applied Workarounds: clamp_texture_base_level_and_max_level
Skia renderer is not used by default.
Disabled Features: skia_renderer
```

##

**Comment by robatwilliams** [comment]
No problem. I'm currently fighting the "blacklisted GPU in Electron on Mac" fight myself, this case is a new one to me.

> what does chrome://gpu output? (**the entire page**, not the partial info that the "copy" button gives you)

That's enough to confirm it, regardless.

There is a command line flag `--ignore-gpu-blacklist`, which may be an option if it's just yourself or a few technically savvy users.

If not, it may be possible to append this at runtime using `app.commandLine.appendSwitch('ignore-gpu-blacklist')` (unless it's too late after the app has started). If it works, the hard part will be deciding when to append it and when not to. The blacklist has many important rules to deal with real problems (such as the aforementioned bug), but some of the Mac rules are simple there just-in-case because the GPU devices haven't been tested.

**Comment by AoDev** [comment]
Thank you for giving the options. I guess the decision on how to handle this is now on my side.

Regarding Electron itself, I wonder if there should be some note in the docs. I delayed Electron update because of this issue because I thought it was a problem for everyone. Had I not have this particular configuration, I would never have known about it.

**Comment by Slapbox** [comment]
Possibly related is this issue I just came to report that's plagued me on Electron 3 and 4 on Windows 10. A  newly created window that is not shown and has not been shown affects the display anyway on system startup. The 

![image](https://user-images.githubusercontent.com/6835891/55355815-55ee8280-5497-11e9-92b3-24d2bf65159c.png)

**Comment by robatwilliams** [comment]
@Slapbox that does look like it may be a GPU-related issue, but I think it's unlikely to be related to this specific one. I suggest you create a new issue (including all the requested details in the issue template), and possibly edit your comment above to link to it.

**Comment by miniak** [comment]
Since Electron 3, `app.getGPUFeatureStatus()` only seems to return correct values after the GPU process was started. When called in main (even after `app.isReady`) before any `BrowserWindow`s are created, it returns incorrect values.

**Comment by KomaGR** [comment]
Possibly related to this issue. Rendering artifacts in animations. (Discord bootup)
![2019-06-05_17-31](https://user-images.githubusercontent.com/22573447/58964670-f32ba700-87b7-11e9-8137-6dd9b737a6e9.png)

Also, local video (camera) playback from skype-for-linux-stable-bin is constantly stuttering. (Other end reports fine image)

**Comment by miniak** [comment]
Electron 4 is not supported anymore

**Comment by AoDev** [comment]
@miniak You could flag this as "won't fix" if you prefer but it does not matter that Electron 4 is not supported anymore. People can still face this in other versions.
