### ISSUE TITLE
<webview> won't fire click event while cover a pointer-events: none element

### ISSUE THREAD

**Issue by springhack** [electron/electron#17655]
### Issue Details

* **Electron Version:**
  * 3.0.10
* **Operating System:**
  * macOS 10.14.3

### Expected Behavior
Click event fire inside `<webview>`

### Actual Behavior
Nothing happend

### To Reproduce

1. Make container of `<webview>` have both `overflow: hidden` and `border-radius: 1px` (or any value);
2. Make a div cover on this container
3. Make cover div `pointer-events: none` and ensure it will be rendered (such as add `background: rgba(0, 0, 0, 0.01)`)

```
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv='Content-Type' content='text/html; charset=utf-8'>
        <title>Index</title>
        <style>
          .web {
            width: 500px;
            height: 500px;
            overflow: hidden;
            border-radius: 1px;
          }
          .web webview {
            width: 500px;
            height: 500px;
          }
          .fix {
            position: fixed;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            background: rgba(0, 0, 0, 0.01);
            pointer-events: none;
          }
        </style>
    </head>
    <body>
      <div class='web'>
        <webview src='https://www.dosk.win'></webview>
      </div>
      <div class='fix'></div>
    </body>
</html>
```

### Additional Information
Remove one of `overflow: hidden`, `border-radius: 1px` or `background: rgba(0, 0, 0, 0.01)` it work

**Comment by springhack** [comment]
Update:
Not only `border-radius+overflow`, every css property cause element clip will trigger this, like `clip-path` ...

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
