### ISSUE TITLE
Hardware acceleration blacklisted for many modern Mac computers

### ISSUE THREAD

**Issue by robatwilliams** [electron/electron#17653]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  4.0.4, all
* **Operating System:**
  *  macOS various versions
* **Last Known Working Electron version:**:
  *  n/a

### Expected Behavior

Hardware acceleration works on macOS, given reasonably recent hardware and OS version.

### Actual Behavior

Hardware acceleration blacklisted (via the Chromium [software rendering list](https://cs.chromium.org/chromium/src/gpu/config/software_rendering_list.json)) on recent hardware and OS versions.

Here is a table of the current rules affecting Macs:

Rule Id | Description
-- | --
1 | ATI Radeon X1900 is not compatible with WebGL on the Mac
10 | NVIDIA GeForce 7300 GT on Mac does not support WebGL
111 | Apple Software Renderer used under VMWare experiences synchronization issues with   GPU Raster
112 | Intel HD 3000 driver crashes frequently on Mac
113 | Some GPUs on Mac can perform poorly with GPU   rasterization. Disable all known Intel GPUs other than Intel 6th and 7th   Generation cards, which have been tested.
114 | Some GPUs on Mac can perform poorly with GPU rasterization. Disable all known   NVidia GPUs other than the Geforce 6xx and 7xx series, which have been   tested.
115 | Some GPUs on Mac can perform poorly with GPU rasterization. Disable all known AMD   GPUs other than the R200, R300, and D series, which have been tested.
116 | Some GPUs on Mac can perform poorly with GPU rasterization. Disable untested   Virtualbox GPU.
119 | There are display issues with GPU Raster on OSX 10.9
126 | Disallow use of OpenGL on Mac with core profile < 4.1
130 | Older NVIDIA GPUs on macOS render incorrectly
150 | Macs with NVidia GPUs experience rendering issues on High Sierra until 10.13.4
151 | Rendering artifacts on older macOS releases and Intel GPUs
159 | Disallow OpenGL use on Mac with old NVIDIA GPUs
160 | Disallow OpenGL use on Mac with old AMD GPUs

To call out some particular issues:
* Rules 113, 114, 115 - include various GPUs used as recent as 2015, not because of any known problem, but because they haven't been tested.
* Rule 151 (new for Electron 4 from Chromium 61) - all Intel GPUs disabled when using El Capitan (originally released 2015) or older. This is due to an [actual issue](https://bugs.chromium.org/p/chromium/issues/detail?id=794819). See #17641.

I've done some correlation work for some of these rules using the [PCI id database](https://pci-ids.ucw.cz/) and the "Identify your {iMac, MacBook Pro, Mac mini} pages on the Apple website:
* Rule 113 - Intel https://gist.github.com/robatwilliams/1690bd86b8a8d40649e1656420d18924
* Rule 114 - NVIDIA https://gist.github.com/robatwilliams/cbaaa660643c1a3026321113d3ffb309
* Rule 115 - AMD https://gist.github.com/robatwilliams/d726549aa794a9c1ddab578c4207eaad

These are some particular devices of concern (being quite modern) which appear to be blacklisted (see the gists for all):
1. MacBook Pro (15-inch, 2016) while using the switchable integrated graphics - rule 113
1. iMac (Retina 5K, 27-inch, Late 2015) - rule 115
1. iMac (Retina 5K, 27-inch, Late 2014) with Radeon R9 M295X option - rule 115
1. MacBook Pro (Retina, 15-inch, Early 2013) while using the switchable discrete graphics - rule 114
1. iMac (27-inch, Late 2012) with GeForce GTX 680MX option - rule 114
1. MacBook Pro (Retina, 15-inch, Mid 2012) while using the switchable discrete graphics - rule 114
1. iMac (21.5-inch, Late 2012) with GeForce GT 650M option - rule 114
1. Any device on El Capitan or earlier using integrated Intel (see #17641)
1. Many models from 2009-2011, especially iMacs.

Many of the above devices have retina screens, with up to 7.5x as many pixels as a single 1920x1800 screen. So they don't perform well at all without hardware acceleration, especially when going full screen - and it causes high CPU usage.

### To Reproduce
Run any electron-based application on affected hardware and OS version.

### Screenshots
n/a

### Additional Information

I'm reporting this issue here for visibility first, rather than on Chromium.

I think this is rather more of a concern for Electron apps:
* Unlike web apps, we don't have the option of asking our users to use Safari instead.
* More likely to be used for multi-window applications.

**Comment by robatwilliams** [comment]
Issue created on Chromium: [Issue 948676: Hardware acceleration blacklisted on some modern Mac computers](https://bugs.chromium.org/p/chromium/issues/detail?id=948676)

**Comment by MarshallOfSound** [comment]
@robatwilliams This issue should be tracked on Chromium's end, we'll inherit any fixes / changes they make 👍

**Comment by robatwilliams** [comment]
Changed "hardware acceleration" to "GPU rasterization" as per comment https://bugs.chromium.org/p/chromium/issues/detail?id=948676#c6

I was aware of the difference, and should have been more specific in reporting these issues.
