### ISSUE TITLE
(Crash) Electron crashes if setMenuBarVisibility to false and pressing Alt key

### ISSUE THREAD

**Issue by KiranNiranjan** [electron/electron#17652]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v5.0.0-beta.7
* **Operating System:**
  *  Windows 10

### Expected Behavior

Electron app should not crash when toggling `Alt` key when `setMenuBarVisibility(false)`

### Actual Behavior

Electron app crashes when `Alt` key is pressed

### To Reproduce
```sh
$ git clone  https://github.com/KiranNiranjan/electron-quick-start.git -b crash
$ npm install
$ npm start || electron .
```
When the app finishes loading press the `Alt` and the app crashes

### Screenshots

![2019-04-02 12 51 11](https://user-images.githubusercontent.com/13243259/55383546-1af75800-5546-11e9-873e-22be38ea6247.gif)

### Additional Information

Looks similary to the following issue -> https://github.com/electron/electron/pull/17474

**Comment by VishwasShashidhar** [comment]
@sofianguy Can you please take this up as part of the app-feedback-program?

**Comment by VishwasShashidhar** [comment]
https://github.com/electron/electron/commit/5994bf6745d36c3ffb278e2067803fe0ea009322 may have caused this issue. 

Calling @nitsakh for some help on this PR to check if the above commit may have caused this issue.
