### ISSUE TITLE
[Electron 5] crashes when webview is rendered inside browserview

### ISSUE THREAD

**Issue by t57ser** [electron/electron#17667]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.0-beta.7
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**:
  * unknown

### Expected Behavior
Electron shuts down

### Actual Behavior
When rendering a webview inside a browserView and calling app.quit then electron will crash.

### To Reproduce
https://github.com/t57ser/electron-crash-issue

The error code appears to change randomly:
![image](https://user-images.githubusercontent.com/10595986/55439457-f088b780-55a4-11e9-8a5f-331baa456513.png)
![image](https://user-images.githubusercontent.com/10595986/55439463-f7afc580-55a4-11e9-84d6-70d35f6e3a9e.png)

**Comment by t57ser** [comment]
I also tested for 5.0.1 and 6.0.0-beta.2 and it is still happening

**Comment by t57ser** [comment]
This is still happening for electron 10 and 11

**Comment by codebytere** [comment]
Bisected to https://github.com/electron/electron/compare/v14.0.0-nightly.20210305...v14.0.0-nightly.20210308 and narrowed to https://github.com/electron/electron/pull/27920.

Verifiable by running the provided repro in `v14.0.0-nightly.20210308` and beyond and observing that it no longer happens.
