### ISSUE TITLE
Right-click and mouse-drag input events from Wacom pen aren't working

### ISSUE THREAD

**Issue by themooserooster** [electron/electron#17660]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Operating System:**
  * Windows 10 (1803) 
  * Ubuntu 18.04 x64
* **Last Known Working Electron version:**:
  * Don't know, but it's gotten worse in the last 6 months or so on every Electron app I use

### Expected Behavior
The pen on a Wacom Tablet should work just like a mouse / track pad.

### Actual Behavior
Right-clicking and left-click-drag behaviors are either extremely slow (10 or more seconds to fire) or never fire at all. When touch is turned on, touch event work just fine, this issue only occurs in conjunction with pen use.

### To Reproduce
Use A Wacom Tablet with either GitKraken or Visual Studio Code

### Additional Information
This is a serious accessibilty issue for me. I first raised this issue with the Visual Studio Code team, who told me to report it to y'all. I have had chronic tendonitis for years, which makes mouse and trackpad usage extremely painful after no more than 5 minutes of usage, so it really isn't an option. I switched to a pen tablet years ago and never looked back. However, two of my most important apps, GitKraken and VS Code, have had increasing amounts of problems with my pen input. VS Code has become nearly unusable bc I can no longer drag scroll sliders with my pen. Right-click actions in GitKraken have become highly erratic, firing late or not at all, and apparently giving nonsensical position data, because the context menus such actions are supposed to summon appear in random locations nowhere near where the click event occurred.

**Comment by interpfister** [comment]
Experiencing the same issue. Happening in slack as well when attempting to draw on screen during calls.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
