### ISSUE TITLE
Can I create my own plugins for an electron?

### ISSUE THREAD

**Issue by miroshnichenkoYaroslav** [electron/electron#17677]
Electron offers many packages https://electronjs.org/userland/most_downloaded_packages but can I create my own package? If so, how to do it?

**Comment by MarshallOfSound** [comment]
@miroshnichenkoYaroslav Those packages are just `npm` packages, anyone can publish one 👍

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
