### ISSUE TITLE
Don't ask user for print settings.

### ISSUE THREAD

**Issue by Tzott** [electron/electron#17670]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *   4.1.0 or 4.1.3 or 5.0.0 -bata7 (x86)

* **Operating System:**
  * Windows 10 x64
   
* **Last Known Working Electron version:**:
  * none

### Expected Behavior

`webContents.print({
        silent: true
    }, function(error) {
        console.log(error)
    });`
Don't ask user for print settings, and send page to printer print
### Actual Behavior

First call:
No response, no callback, no results returned

Call again:
Callback returns error, console output: `false`

### Screenshots

![ezgif-4-5b8904ec32f4](https://user-images.githubusercontent.com/37071716/55451272-d1217700-5604-11e9-99af-ed0ec522859f.gif)

**Comment by nnde** [comment]
I also encountered the same problem, solving.

**Comment by Tzott** [comment]
> I also encountered the same problem, solving.

How did you solve it?

**Comment by baconbrad** [comment]
Related issue detailing various print issues with 4 and 5: https://github.com/electron/electron/issues/17523

8 hours ago it was given the bug tag so hopefully a fix is through the pipeline soon.

**Comment by codebytere** [comment]
Duplicate of https://github.com/electron/electron/issues/18858.
