### ISSUE TITLE
App Blur Method

### ISSUE THREAD

**Issue by nickfujita** [electron/electron#17671]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

When managing window states, I can not seem to find a way to return focus to the previous app without hiding all browser windows. The method `app.hide()` will hide all browser windows and return focus to the previous app. However I would like a way to do this without hiding all browser windows.

The use case for this is when the user has multiple windows open side by side. In this example, Chrome browser of the left hand part of the screen, and my Electron app on the right hand.

- OS level focus is on the Chrome browser
- An arbitrary action occurs, and the Electron fires an event such as `app.focus()`, and gains OS level focus.
- The user performs an action in the Electron app, and as the developer, I would like to return focus to the Chrome browser without hiding the Electron BrowserWindow on the righthand side of the screen. In this case the user must manually click the Chrome browser window on the left hand side in order to regain focus.

A second issue is currently if the app is managing two or more browser windows, in the example two (Window A and Window B).

- User has Electron app open, with one of the two the BrowserWindows visible, Window A.
- User navigates to Chrome browser, maximized over whole screen (not fullscreen). Window A is still visible in the background, behind the Chrome browser. Window B is not visible/ hidden.
- An arbitrary action occurs, and the Electron fires an event which gives the app OS level focus,  brings shows Window B in the foreground, but leaves Window A behind the Chrome browser window. This is currently working perfectly.
- The user performs an action in the Electron app, and as the developer, I would like to hide Window B, return focus to the Chrome browser without changing the state of Window A. Currently if you simply hide Window B, Window A will then be brought to the foreground. If you call `app.hide()`, focus is returned to the Chrome browser, but Window A is no longer in a visible state.

### Proposed Solution

The request is to add an `app.blur()` method which will perform the same action as calling `app.hide()`, with respect to returning OS level focus back to the previous application, but not altering the visibility of any open BrowserWindows.

**Comment by chuson1996** [comment]
Rooting for this one. This would be great

**Comment by blakewatson** [comment]
I need something like this in order to build an onscreen keyboard for accessibility. The idea being that one can click on the window (to type characters) without focusing the app.

**Comment by miniak** [comment]
I don't think there is an OS API to do this unfortunately

**Comment by blakewatson** [comment]
It’s been a little while but for my use case the answer was to set the `BrowserWindow.type` to `'panel'`. That way the window remains interactive but doesn’t steal focus when clicked on.
