### ISSUE TITLE
TypeError: clipboard.readBuffer is not a function

### ISSUE THREAD

**Issue by jazzwsr** [electron/electron#17672]
Electron Version:
1.4.13

Operating System:
Win 10

Last Known Working Electron version:
1.4.13

Expected Behavior:
expected clipboard.readBuffer('FileNameW') can work

Actual Behavior:
1、when i use
{ let filePath = 
 clipboard.read('FileNameW').toString('ucs2').replace(RegExp(String.fromCharCode(0), 'g'), '')
} 
got filePath has messy code

2、so i Instead of
{ let filePath = 
 clipboard.readBuffer('FileNameW').toString('ucs2').replace(RegExp(String.fromCharCode(0), 'g'), '')
} 
but got TypeError: clipboard.readBuffer is not a function

To Reproduce:
As mentioned above

Screenshots:
![image](https://user-images.githubusercontent.com/8381304/55466036-fcba5680-5630-11e9-97a3-21b742418592.png)

Additional Information:
As mentioned above

**Comment by MarshallOfSound** [comment]
@jazzwsr We no longer support `1.4.x`.  Please update to a recent and supported version like `4.1.x`

**Comment by jazzwsr** [comment]
thanks a lot! update 4.1.x clipboard.readBuffer() can work - -

i find only use mouse right copy file then CmdOrCtrl+V can get one last file not fileList on win system, 
more strange CmdOrCtrl+C copy file then CmdOrCtrl+V get nothing ~~!
