### ISSUE TITLE
Window jitter on mouse up

### ISSUE THREAD

**Issue by erik-ciq** [electron/electron#17682]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.0.7

* **Operating System:**
  * Windows 10 (1803)

### Expected Behavior
mouse up should not trigger a move event on a frameless window (which it will do if you send bounds across IPC and back)

### Actual Behavior
mouse up triggers a move event on a frameless window when sending bounds across IPC

### To Reproduce

```
git clone https://github.com/erik-ciq/jitter-test
npm install
npm start
```

#### Three cases:

**Case 1, extra move event thrown on mouse up (window will jitter on mouse up):**

![case1](https://user-images.githubusercontent.com/45185091/55501552-7df8f580-55ff-11e9-9331-1dd52dd92065.gif)

run the cloned repo to see case 1. Notice in the gif that the window moves on mouse up, and there are two extra `move` console logs on `mouseUp`.

**Case 2, no extra move event thrown on mouse up (no jitter):**

![case2](https://user-images.githubusercontent.com/45185091/55502405-573bbe80-5601-11e9-9dbf-664540486267.gif)

uncomment case 2 to see case 2 (https://github.com/erik-ciq/jitter-test/blob/master/events.js#L65)

Notice in the gif for case 2 that the window does not move on mouse up, and there are not two extra `move` console logs on `mouseUp`.

**Case 3, no extra move event thrown on mouse up (no jitter):**

![case3](https://user-images.githubusercontent.com/45185091/55502562-b1d51a80-5601-11e9-8d5f-d007ab8c3aa5.gif)

Notice in the gif for case 3 that the window does not move on mouse up, and there are not two extra `move` console logs on `mouseUp`.

uncomment case 3 to see case 3 (https://github.com/erik-ciq/jitter-test/blob/master/events.js#L69)

### Screenshots

**Diagram of issue:**

![image](https://user-images.githubusercontent.com/45185091/55500200-aa5f4280-55fc-11e9-9842-4f03e04291b8.png)

**Incorrect:**

![image](https://user-images.githubusercontent.com/45185091/55514098-1ac98c00-561c-11e9-869b-0db178319111.png)

**Correct:**

![image](https://user-images.githubusercontent.com/45185091/55514157-3d5ba500-561c-11e9-8e23-4f7bbdd1bc66.png)

### Additional Information
When the jitter occurs it appears to me as though a call to setBounds is being cached somewhere in the C++. That setBounds call is not being executed UNTIL mouseUp is fired. This only occurs if you send the bounds across the IPC from main -> renderer process, without actually setting the bounds in the main process. The jitter will always result in the window jumping to the position it was at in the 2nd to last call, which can be very clearly seen in this screenshot:

![image](https://user-images.githubusercontent.com/45185091/55502918-70913a80-5602-11e9-9c14-bfacb2ade15f.png)

(`move` logs are omitted in this screenshot to reduce noise)

[throttling, debouncing, and rate limiting](https://github.com/erik-ciq/jitter-test/blob/master/main.js#L48) bus events has no impact. Neither does using a unique name for the IPC channel for each event, or using [timestamps](https://github.com/erik-ciq/jitter-test/blob/master/events.js#L28) to ensure order of messages. I'm fairly stumped as to how / why this happens.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
