### ISSUE TITLE
Electron not lunching on Raspberry Pi Zero

### ISSUE THREAD

**Issue by MeddahAbdellah** [electron/electron#17683]
Electron Version: 3.0.13
  
  Operating System: Raspbian
  Raspberry Pi Zero armv64

### Expected Behavior
  I have this same code working on RPI3 no I am trying to run it on raspberry Pi zero but with no 
  success so far, it's supposed to just open a simple HTML page, I even tred the quick-start repo 
  but still no success. 

    const { app, BrowserWindow } = require('electron');
    let explorer=null;
    console.log("In the App");
    function createWindow () {
    explorer = new BrowserWindow({ width: 800, height: 600});
    explorer.loadFile('./views/index.html');
}
### Actual Behavior

  when runing:
     electron .
  nothing happens it doesn't eve print the console.log("In the App"); it just jumps the second like 
  after few seconds without throwing any error and without opening the app.

 Thanks.

**Comment by jkleinsc** [comment]
@MeddahAbdellah can you try setting the following environment variables and then run `electron .`

`export ELECTRON_ENABLE_LOGGING=true`
`export ELECTRON_ENABLE_STACK_DUMPING=true`

**Comment by codebytere** [comment]
Closing due to lack of follow-up.
