### ISSUE TITLE
Refused to execute inline script

### ISSUE THREAD

**Issue by mittalyashu** [electron/electron#17696]
### Preflight Checklist

* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.
* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.

### Issue Details

* **Electron Version:** 4.1.3
* **Operating System:** Windows 10

### Expected Behavior
It should not show this error in console `Refused to execute inline script`, whenever I make some changes to a page _(/welcome)_, generally the electron app should hot-reload but it is showing the error, then on the screen it also shows.

![image](https://user-images.githubusercontent.com/29014463/55562804-50e93780-5712-11e9-8ed2-acc80ceda7a6.png)

### To Reproduce
I have used [this boilerplate](https://github.com/SimulatedGREG/electron-vue) to get started with electron app.

1. Create few routes in `routes/index.js`
2. In the app change the view to that specific route
3. Make some changes of that file component
4. See the error in the app

### Screenshots

![electron_iSpe5ZamVa](https://user-images.githubusercontent.com/29014463/55562931-93127900-5712-11e9-8f97-912729b94d22.png)

**Comment by MarshallOfSound** [comment]
The scripts that are trying to execute violate your CSP as that error says, this isn't an Electron issue rather a configuration issue with your app.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
