### ISSUE TITLE
clipboard got nothing when copy local file when use control+c

### ISSUE THREAD

**Issue by jazzwsr** [electron/electron#17691]
Electron Version:
4.1.0

Operating System:
Win 10

Last Known Working Electron version:
4.1.0

Expected Behavior:
1、expected support get files from control+c
2、expected clipboard.read() can read file list

Actual Behavior:
i find only use mouse right copy multi file then CmdOrCtrl+V can get one last file not fileList on win system, more strange CmdOrCtrl+C copy file then CmdOrCtrl+V get nothing ~~!

To Reproduce:
As mentioned above

Screenshots:

Additional Information:
As mentioned above

**Comment by JohnTendik** [comment]
I'm in need of this same functionality but from my research I don't think its possible at the moment. 

clipboard.readBuffer('FileNameW').toString('ucs2').replace(RegExp(String.fromCharCode(0), 'g'), '')

or 

clipboard.read('FileNameW')

will give you the file location/name for you to do things with but it only works for 1 file at a time. So if you select multiple files, only the name/path for the last file in the clipbaord will be output. 

https://github.com/atom/tree-view/issues/569#issuecomment-361399684

:(

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by Rishgod** [comment]
:( i need this fam

**Comment by dirkteucher** [comment]
Still not able to do it. Would be great to re-open this in 2024 and see if there is a way to add support.
