### ISSUE TITLE
webview is broken in 5.0.0.beta.8 under Windows

### ISSUE THREAD

**Issue by webarchymeta** [electron/electron#17700]
### Issue Details

* Electron Version: 5.0.0.beta.8 and maybe earlier incremental versions 
* Operating System: most recent Windows 10 and maybe on other platforms
* Last Known Working Electron version: 4.1.1

### Expected Behavior
The webview should display web pages of corresponding urls

### Actual Behavior
The webview is empty

### To Reproduce

```sh
$ git clone https://github.com/hokein/electron-sample-apps
$ cd electron-sample-apps/webview/browser
$ electron .
```

**Comment by t57ser** [comment]
You need to enable the webviewTag, it is part of the windows webPreferences.
https://electronjs.org/docs/api/browser-window
Search for webviewTag.

**Comment by codebytere** [comment]
The above is correct!

**Comment by webarchymeta** [comment]
Well, the document said that the value of the `webviewTag` defaults to the one assigned to `nodeIntegration`, this is true for pre-5.0 electron versions, but not the current version (5.x).

There is at lease some inconsistency here, Please rectify it somehow ...

**Comment by MarshallOfSound** [comment]
@webarchymeta The docs for `5-0-x` note that the default for webviewTag is `false` --> https://github.com/electron/electron/blob/5-0-x/docs/api/browser-window.md
