### ISSUE TITLE
Notifications that shares the same tag won't trigger onclick on every second notification

### ISSUE THREAD

**Issue by r0stig** [electron/electron#17706]
### Issue Details

* **Electron Version:**
  * 4.1.4
* **Operating System:**
  * macOS 10.13.6
* **Last Known Working Electron version:**:

### Expected Behavior
The onclick-handler for a notification in the renderer process should always be fired upon click when the notification object shares the same tag.

### Actual Behavior
Only every second notification click fires the onclick handler when the notifications share the same tag.

### To Reproduce

https://github.com/r0stig/electron-quick-start

```sh
$ git clone git@github.com:r0stig/electron-quick-start.git
$ npm install
$ npm start
```
* Click on the button "send notification"
* Click on the notification and notice the log messages that indicate the click-handler fired
* Click on the button "send notification"
* Click on the notification and see that this time the onclick-handler did not fire

The same occur when you just wait for the notification to close from timeout:
* Click on the button "send notification"
* Wait for the notification to be closed automatically
* Click on the button "send notification"
* Click on the notification and notice that the onclick-handler did not fire

### Screenshots
![notification_electron](https://user-images.githubusercontent.com/1148042/55620492-5048b380-579b-11e9-885c-bc4081c6a01e.gif)
As shown in the gif, when I click on the notification a second time the onclick handler won't trigger.

**Comment by r0stig** [comment]
Letting you know that this is resolved in 5.0.0 but still present in 4.1.5.

**Comment by Ivorfason** [comment]
> Letting you know that this is resolved in 5.0.0 but still present in 4.1.5.

It still exist in 5.0.0

**Comment by r0stig** [comment]
> > Letting you know that this is resolved in 5.0.0 but still present in 4.1.5.
> 
> It still exist in 5.0.0

Are you able to reproduce with the above demo? If not how do you reproduce?

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by r0stig** [comment]
Please reopen this issue, I've managed to reproduce this bug again in electron version 10.1.2. But only in the case where I wait for the first notification to auto dismiss. To reproduce:
Clone https://github.com/r0stig/electron-quick-start

* Click "Send notification"
* Wait for notification to auto dismiss
* Cick "Send notification"
* Click on notification, notice that it will not log "onclick" which it should

See clip:
![onclick_fails](https://user-images.githubusercontent.com/1148042/93899920-18b62a00-fcf5-11ea-8bfb-7f0a5d8831ed.gif)
