### ISSUE TITLE
ipcRenderer.send being used to pass data from external classes to pass data to main.js

### ISSUE THREAD

**Issue by ConsultantsCombined** [electron/electron#17714]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
I have ipcMain in main.js and I have ipcRenderer that only seems to work in .html files. I want to write simple classes and be able to send some data to the main process via the ipcRenderer. I feel this is a bug but I am probably using it wrong. 

My example is I have a rclient.js file which contains a class and some global variables and i export this module and create it like so in main.js
```
rClient = 
    new RClient(
        '111.12.12.12',
        '23333',
        'Secret'
    );
```
, in this file I attempt to bring in the ipcRenderer with intentions of using ipcRenderer.send('console:output',consoleLogs); and then catching that send from rclient.js in the main.js via ipcMain.on('client:toconsole', (event, logs) =>{//send to html page here via webContents});

Why doesn't this work? What am I doing wrong? I can provide minimal code examples.

* **Electron Version:**
4.0.3 
* **Operating System:**
 Windows 10 (1803)
* **Last Known Working Electron version:**:

### Expected Behavior
Need to be able to use the ipcRenderer from JavaScript class files that are not main.js so I can send data to main.js from class files on a trigger. I am trying to populate a line of console data as it comes through a websocket.

The below code should work in both index.html and rclient.js but it doesn't I get an error in external javascript class files such as rclient: Error: Cannot read property of send of undefined
```
    const electron = require('electron');
    const {ipcRenderer} = electron;
```
    

### Actual Behavior
Boom. 
Error: Cannot read property of send of undefined
It is undefined in the JavaScript file rclient.js but works in my index.html inside the script tags as below when I manually send test data to below

**index.html**
```
 ipcRenderer.on('console:output', function(e, logs){
        console.log('Received data from mainjs, this will populate our console ' + logs);
        const consoleTextArea = document.querySelector('#console-output');
        consoleTextArea.value = consoleTextArea.value + logs + '\r\n';
        //How to get the data here ??? -- Basically an IPC needs to send from rclient class or from rclient class to main to webpage considering main contains the references for my html pages..
    });
```

### To Reproduce
Simple try to use ipcRenderer.send in a javascript file that is a class, and call it in some function and attempt to catch it in your main.js. 
Create a class file with 'use strict'; and module.exports = classname, create it on the app ready as a variable.

### Additional Information
That is all I have I hope this helps or you can help me.

**Comment by MarshallOfSound** [comment]
`ipcRenderer` is only available in the renderer process

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

If this is actually a bug and you can provide a minimal repro please @ mention me below
