### ISSUE TITLE
electron 4.1.4 - audio element not working

### ISSUE THREAD

**Issue by lab6net** [electron/electron#17710]
* **Electron Version:**
 4.1.4

* **Operating System:**
 Windows 10 x64

### Expected Behavior
audio element should appear and play sound

### Actual Behavior
prevents page from loading, disconnects webtools from page

### To Reproduce
Just make simple html file and put an audio element in it (&lt;audio&gt; &lt;/audio&gt; is enough).

### Additional Information
I'm using manual distribution for this. I'v just download 4.1.4 from https://github.com/electron/electron/releases

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
