### ISSUE TITLE
Hidden windows produce artifacts on Windows desktops

### ISSUE THREAD

**Issue by Slapbox** [electron/electron#17713]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 11.3.0 (and all versions 3.x and up)
* **Operating System:** Windows 7 x64 + Windows 10 x64
* **Last Known Working Electron version:**: 2.0.x

### Expected Behavior
Hidden windows should not affect desktop composition.

### Actual Behavior
A  newly created window that is not shown and has not been shown affects the display anyway on system startup. After showing the window, this doesn't occur again, even if you restart the app.

Restarting the machine produces the issue once again though. **[See figure 1 below]**

Allowing the display to turn off produces the issue too. This is a slightly different manifestation of the same issue; the window has shown before, then was hidden. After that the screen went to sleep and came back, leaving these artifacts. **[See figure 2 below]**

### To Reproduce
Create a hidden Browser Window and set the screen sleep timeout to 1 minute under Windows Power Options. Let the screen go to sleep and return. You should see artifacts. If this does not work, showing the window and hiding it again, and then allowing the screen to go to sleep should definitely produce the issue.

### Screenshots
**Figure 1**

![image](https://user-images.githubusercontent.com/6835891/55355815-55ee8280-5497-11e9-92b3-24d2bf65159c.png)

**Figure 2**

![image](https://user-images.githubusercontent.com/6835891/55357390-e084b100-549a-11e9-87e4-f1b4460d1aac.png)

### Additional Information

I'm seeing this on dedicated graphics, and in a virtual machine. I don't have a machine with integrated graphics to test on unfortunately.

I strongly suspect there's a relationship between the findings in https://github.com/electron/electron/issues/17641 and this issue.

**Comment by harryi3t** [comment]
Hi @Slapbox,
I tried reproducing this but couldn't. Here's my code from main.js
```js
// open a hidden window
 mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    show: false
  })

// show it after 2 sec
  setTimeout(function () {
    mainWindow.show()
  }, 2000);

// hide it again after 2 more sec
  setTimeout(function () {
    mainWindow.hide()
  }, 4000);
```

I tried this on Windows 10 Home, version: 1803, build: 17134.765

**Comment by Slapbox** [comment]
@harryi3t thanks for taking a shot at reproducing this. This issue may depend on you having a specific GPU configuration.  Could you post a gist of what `chrome://gpu` looks like on your machine? I know that's not a perfect parallel for Electron, but hopefully it gets us somewhere.

Here's what mine looks like on the problem machine:  https://gist.github.com/Slapbox/6625fa1f57209182220d3611de2eb922

I originally thought this was a development only issue, but this issue was reported to me by multiple users in the field, so it's definitely, beyond the shadow of a doubt,  a real issue that needs addressing. It's unfortunate that reproduction relies on the machine where the code is run.

**Comment by harryi3t** [comment]
@Slapbox I wasn't sure about should I open the above-mentioned URL in chrome browser or in a sample electron App (v4.1.1), so I did both (there were some differences).
Here's the link https://gist.github.com/harryi3t/d51232fb661d46b3b16a901d33d892b6

Also, I noticed that as you have expected mine is showing `Rasterization: Hardware accelerated`.

**Comment by Slapbox** [comment]
@harryi3t thanks a lot for taking the time to try to reproduce this and to help gather the info to pinpoint and fix the problem; I really appreciate it!

For the record my output is directly from Chrome since that seemed like the easiest way by far to collect the data, even if it's not 100% identical.

**Comment by Slapbox** [comment]
Just to update, I've got a sample size of at least 8 machines on this now. This issue DOES persist into `Electron@6` - at least with `frameless: true`

I feel absolutely 100% confident this is the cause and I feel pretty sure about a solution after some time collecting data.

I believe this is caused by `thick_frame` being left behind somehow. I'm guessing Electron emulates this effect for `frameless` windows and there's an edge case here where it's not cleaned up somehow? @codebytere would you happen to have any thoughts on whether this idea sounds plausible?

**Comment by Slapbox** [comment]
This issue persists in Electron 7. We've gotten complaints from users about this for at least a full year now, and we've done everything in our power to try to work around this, doing crazy window re-positioning to try to work around this.

I've even identified a probable cause of the issue.

Can anyone acknowledge this thread exists at least please?

**Comment by Slapbox** [comment]
Issue persists in `Electron@8.2.5`.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by Slapbox** [comment]
This issue is still relevant. Is it possible to get this re-opened rather than creating a new issue?

**Comment by nornagon** [comment]
@Slapbox what versions have you been able to reproduce the issue on? I can reopen with that info.

**Comment by Slapbox** [comment]
Hey @nornagon thanks very much for taking the time! We're continuing to see this in versions up to and including `11.3.0`.

**The cause:** I'm all but certain that the cause is that a hidden window's `WS_THICKFRAME` can be left behind. It seems to be related to hiding a child window in particular, and I thought maybe it was a race condition between hiding the child/parent, but no ordering or delaying of what we hide when works around it.

**Our temporary workaround:** For now we offer users an option now to disable the default `thickFrame: true` if they're experiencing this bug. This seems to fix every case we've heard of from users.

**Downsides:* By default users would expect windows to have `WS_THICKFRAME` (which enables both shadow and window animations.)

**Comment by Slapbox** [comment]
Not stale as of version 18. Haven't tested 19+ yet.

**Comment by Slapbox** [comment]
I believe this is still relevant.
