### ISSUE TITLE
Electron app opens windows twice

### ISSUE THREAD

**Issue by SudeshRani** [electron/electron#17724]
I have used electron for generating the build for Mac and windows, but when i open the exe or dmg file it opens two widows in which one is blank window,   i installed the electron-squirrel-startup library ,and calling its events but it quits the app and also events are not firing. Please help

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
