### ISSUE TITLE
don't run on raspberry pi!

### ISSUE THREAD

**Issue by nanzexu** [electron/electron#17721]
pi@raspberrypi:~/electron-quick-start $ npm start

electron-quick-start@1.0.0 start /home/pi/electron-quick-start
electron .

/home/pi/electron-quick-start/node_modules/electron/dist/electron: /lib/arm-linux-gnueabihf/libc.so.6: version GLIBC_2.27' not found (required by /home/pi/electron-quick-start/node_modules/electron/dist/electron) npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! electron-quick-start@1.0.0 start: electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /home/pi/.npm/_logs/2019-04-07T16_07_38_351Z-debug.log

**Comment by nanzexu** [comment]
strings libc.so.6  | grep GLIBC:
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_2.13
GLIBC_2.14
GLIBC_2.15
GLIBC_2.16
GLIBC_2.17
GLIBC_2.18
GLIBC_2.22
GLIBC_2.23
GLIBC_2.24
GLIBC_PRIVATE

**Comment by shiftkey** [comment]
@nanzexu please look at https://github.com/electron/electron/issues/16205 which is an earlier report on this issue, and has more information...

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
