### ISSUE TITLE
Shortcuts not working in Developer Tools

### ISSUE THREAD

**Issue by Stoyvo** [electron/electron#17725]
### Preflight Checklist

* [ x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v5.0.0-beta.8
* **Operating System:**
  * OSX 10.13.6

### Expected Behavior
Developer Tools keyboard shortcuts (Copy/Paste/Select All/etc) to work

### Actual Behavior
Developer Tools keyboard shortcuts are hijacked by Electron app

### To Reproduce
Here's the situation: I have custom keyboard shortcuts used in my app, not global shortcuts, but "local-global" shortcuts (related to: https://github.com/electron/electron/issues/17530)

Problem is that Developer Tools, for some reason, adheres to the same shortcut definitions as the main window :/

To recreate the issue, create a Menu template and remove Copy & Paste commands, assign the menu to the window, and open developer tools:
```
    const menu = Menu.buildFromTemplate(menuTemplate);
    Menu.setApplicationMenu(menu);

    // Create the browser window.
    win = new BrowserWindow(windowOptions);
    win.setMenu(null);
    win.webContents.openDevTools({ mode: 'detach' });
```

**Comment by sil3nthill** [comment]
hello can i work on this issue ?

**Comment by sofianguy** [comment]
@sil3nthill PRs are welcome! Please follow our [contributing guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md#pull-requests)

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
