### ISSUE TITLE
WebView ContextMenu

### ISSUE THREAD

**Issue by JGSangara** [electron/electron#17723]
Can someone assist me on a way to implement the `ContextMenu` in electron `webView `with functionalities like `copy link` and `open link in new tab`.

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
