### ISSUE TITLE
Ability to disable creation of logs directory

### ISSUE THREAD

**Issue by agjs** [electron/electron#17732]
Hey guys. We are keeping our logs in a different path (not using the electron's one) and we are wondering if there is some flag to disable creation of this folder.

Thanks in advance :)

**Comment by agjs** [comment]
Anyone? :-)

**Comment by codebytere** [comment]
@agjs yeah i can try to refactor this slightly so that users have more granular control over it.

**Comment by agjs** [comment]
Would really appreciate it and also honestly, it makes sense to make this optional. Thank you
