### ISSUE TITLE
mainwindow is focusing when closing other browserWindows

### ISSUE THREAD

**Issue by hpatel4** [electron/electron#17731]
Electron: 4.1.4
OS: MacOS

Expected Behavior: When closing the last open browser window, mainWindow shouldn't automatically come to focus. 

Actual Behavior: 
I am using browserwindows for push notifications. When the last notification browserwindow is dismissed, mainwindow is automatically coming to foreground with focus. It's working as expected in windows platform but not in macOS. 

To Reproduce: 
1) Create two browserwindows. One as a mainWindow and second as just a simple browserwindow. 
2) Hide the mainwindow
3) close the open browserWindow 
4) It would bring the mainWindow in focus.

**Comment by ismailkuraydli** [comment]
I am having the same issue using electron 3.0.10

**Comment by connormakh** [comment]
Have the same issue, electron 4.1.4

**Comment by hpatel4** [comment]
Is there any update on this ticket guys ?

**Comment by MaximeMarchand** [comment]
This is something we would like to fix for our app! Could it be scoped soon?

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by castroCrea** [comment]
Hello,
I have the same issue. @hpatel4 have you found out ?

You can reproduce it by creation a new window with a button that call .close() with ipcMain

```
    let win = new this.BrowserWindow({
      height: 40,
      width: 40,
      modal: true,
      frame: false,
      alwaysOnTop: true,
      opacity: 0.9,
      center: false,
      backgroundColor: "#fff",
      hasShadow: false,
      show: false,
      webPreferences: {
        nodeIntegration: true
      }
    });
    win.loadURL(`data:text/html;charset=UTF-8,
            <!DOCTYPE html>
            <html>
              <head>
              <title>topflowNotif${data.id}</title>
                
              </head>
              <body>
              <div class="main-content">
                <div id="close" class="close"><span>x</span></div>
                <script> 
              
                document.getElementById('close').addEventListener('click', (event) => {
                                        event.stopPropagation();
                    const {ipcRenderer} = window.require('electron')
                    ipcRenderer.send('call-close', 'ping') //eg placed in your 
                })
                </script>
              </body>
            </html>`);

    win.webContents.closeDevTools();
    // win.webContents.openDevTools({ mode: "detach" });
    let timeout;

    win.on("ready-to-show", () => {
      win.showInactive();
    });

    win.on("closed", () => {
      win = null;
    });

    win.on("blur", () => {
      win.close();
    });

    this.ipcMain.on("call-close", (event, arg) => {
      // if (win) win.close();
      if (win) {
        win.destroy();
      }
    });
  }
};
```
