### ISSUE TITLE
add frame for existing windows

### ISSUE THREAD

**Issue by johnzhu12** [electron/electron#17741]
I want to add frame for an existing window cause my login page is a frameless window.
but my logged-in pages needs to have a frame.
I've searched the issues.
https://github.com/electron/electron/issues/1145
and found it's not possible to set frame dynamically.
so there are two options for me :

1.  add a mocked web frame.

2. close the preview window, and  create a new one (I prefer this option),but how I share the login session between two separate  window?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
