### ISSUE TITLE
Suggesting that electron comes with built in embedded storage

### ISSUE THREAD

**Issue by wembomulumba** [electron/electron#17749]
I haven't starting to use electron yet but Suggesting that electron comes with built in database (embedded storage)

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Comment by MarshallOfSound** [comment]
Electron has all the storage APIs that the web has (idb, localstorage, etc.)

It also has access to all the node modules that provide storage strategies.  E.g. sqlite

**Comment by wembomulumba** [comment]
@MarshallOfSound
Okay , I try it only one time, it was cool ! just don't want to depend on http calls to pull data, since it does have locastorage. Do you have a doc to work electron with sqlite ?
