### ISSUE TITLE
ARM64 Native Compilation support

### ISSUE THREAD

**Issue by ossdev07** [electron/electron#17740]
Dear Team, 

### Problem Description
ARM64 native compilation support

### Proposed Solution
Steps followed to compile on arm64 platform:

- Compile gn and ninja tools and add repective paths in PATH variable.
- Install clang, lld, default-jdk packages.
- Run gclient sync --nohooks
- Modify DEPS file and build.gn as nacl and binutils are not supported in arm64 platform.
- gclient runhooks
- Execute gn command as mentioned in electron development docs and add target_cpu, clang path in args.gn.
- Execute ninja command to generate binary in out folder.

Approaches:
 1. Raise PR for above mentioned changes in Chromium package. This will create merge dependency over Chromium package

2. Create a patch and make a condition to apply that patch when package checks for ARM64. This will make Electron independent of Chromium based changes   

Please let me know, which approach should be best way to get the things done for Electron on ARM64

Regards,

**Comment by ossdev07** [comment]
Along with this, I am open to checking all the suggestions and experiments as I have a local ARM64 based machine at my end over which I can cross confirm the changes.

My intention is to see `ARM64` in the official supported list of `Electron`

Regards,

**Comment by nornagon** [comment]
Can you clarify which OS you're talking about? ARM64 on Linux is already supported and built by our CI. ARM on Windows is only just recently supported in upstream Chromium and we're beginning to experiment with building that.

**Comment by ossdev07** [comment]
@nornagon 
Thanks for the reply. 
We are using linux OS. I have been able to cross-compile for ARM64 platform with the provided electron development docs. But we require support for native compilation of electron package in ARM64 platform. 
You have mentioned in comment https://github.com/electron/electron/issues/17288#issuecomment-471018519 that only cross-compilation is supported currently.
So we have made updates in DEPS file and BUILD.gn file accordingly to support native compilation in ARM64 platform to generate binaries.

Thanks in advance.

Regards,

**Comment by ossdev07** [comment]
For better understanding, these are my environment details:
```
host_os = "linux"
target_os = "linux"
target_cpu = "arm64"
current_cpu = "arm64"
```
This will start **Native Compilation** of the packages over **ARM64** architecture.

Regards,

**Comment by jkleinsc** [comment]
In order for Electron to support native compilation on arm64, chromium would have to be updated to support native compilation on arm64.  If that is something you are interested in doing, I'd suggest taking it up with the Chromium project first.

**Comment by linqing2004** [comment]
> For better understanding, these are my environment details:
> 
> ```
> host_os = "linux"
> target_os = "linux"
> target_cpu = "arm64"
> current_cpu = "arm64"
> ```
> 
> This will start **Native Compilation** of the packages over **ARM64** architecture.
> 
> Regards,

Hi Ossdev07,

I have the same issue here to native build electron for aarch64. Have you built it successfully? Could you share the steps you take to build it? 

The prebuild electron doesn't work on aarch64 with 64k-pagesize kernel. Not sure if electron team has plan to release electron binary for  aarch64 with 64k-pagesize kernel.

Thanks,
Qing

**Comment by odidev** [comment]
@linqing2004 

I am working with @ossdev07. We had built electron binary using the below steps:

**Prerequisites:**

`apt-get update && apt-get install -y build-essential wget clang libdbus-1-dev libgtk-3-dev \                       libnotify-dev libgnome-keyring-dev libgconf2-dev \                       libasound2-dev libcap-dev libcups2-dev libxtst-dev \                       libxss1 libnss3-dev curl \                       gperf bison python-dbusmock lld default-jdk `

**Install depot_tools, gn and ninja**

**Depot_tools:**

git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git 

**gn:**

- git clone https://gn.googlesource.com/gn
 
- cd gn
 
- python build/gen.py
 
- ninja -C out
 
- cp out/gn /usr/sbin 
 

**ninja:**

- cd ~
 
- git clone https://github.com/ninja-build/ninja
 
- cd ninja
 
- ./configure.py --bootstrap 
 
- export PATH=$PATH:~/ninja:/path/to/depot_tools 
 

**Steps to generate electron binary:**

1) mkdir electron-gn && cd electron-gn

2) gclient config --name "src/electron" --unmanaged https://github.com/electron/electron

3) gclient sync  -v -j96 --nohooks

4) git config --global user.name "ossdev07"

5) git config --global user.email "ossdev@xxx.com"

6) Modify DEPS file with below mentioned changes:      

   a)    -  'checkout_nacl': True,                   

         +  'checkout_nacl': False,      

   b)     'name': 'binutils',            

             'pattern': 'src/third_party/binutils',                    

             -    'condition': 'host_os == "linux" and host_cpu != "mips64"',

             +    'condition': 'host_os == "linux" and host_cpu != "arm64"',

7) Modify build/config/compiler/BUILD.gn      

-  treat_warnings_as_errors = true      

+  treat_warnings_as_errors = false

8) gclient runhooks

9) cd src

10) export CHROMIUM_BUILDTOOLS_PATH=`pwd`/buildtools

11) gn gen out/Debug --args="import(\"//electron/build/args/debug.gn\") $GN_EXTRA_ARGS" 

12) Add these to out/Debug/args.gn      

    target_os = "linux"

    target_cpu = "arm64"

    current_cpu = "arm64"

    symbol_level = 1      

    enable_nacl = false      

    clang_base_path = "/usr"

13) ln -s llvm-ar llvm-ar-7

14) cd out/Debug

15) ninja -v -j96 electron

Electron binary was generated in **out/Debug** folder. As we need to support arm64 chromium first, we had made the changes and raised a [MR](https://chromium-review.googlesource.com/c/chromium/src/+/1592630) in chromium.

It has not been merged by the chromium team and they said they were not interested in support native compilation in arm64.

Please let us know if you have any more doubts about this.
