### ISSUE TITLE
PiP various mode.

### ISSUE THREAD

**Issue by meteorsnows** [electron/electron#17753]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

PiP mode for elements other than Video

### Proposed Solution

Anyway to change the blink's cpp code and fork another version of Electron to support it? Like in chromoium blink/renderer/modules/picture_in_picture/html_video_element_picture_in_picture.cc

```
ScriptPromise HTMLVideoElementPictureInPicture::requestPictureInPicture(
ScriptState* script_state,
--
  | HTMLVideoElement& element) {
  | Document& document = element.GetDocument();
  | PictureInPictureControllerImpl& controller =
  | PictureInPictureControllerImpl::From(document);

```

### Alternatives Considered
Could anyone guide roughly how to modifies blink cpp and so we can use customization of Electron, that we can manage and still update from upstream.

Electron support multiple OS, it is good to have following:
- Windows 10 have Compact Overlay
- Mac OSX have AVPictureInPictureController

### Additional Information
To Support more desktop usage.

**Comment by brenca** [comment]
I don't think it's trivial to extend `PiP` mode to other elements. The `PiP` mode in chromium uses a low level video layer to display the video, and the control elements are also done in `C++`, so there is no easy way to do this for other kinds of elements.
I suggest that you implement your own solution by spawning a new frameless window which is set to always-on-top, and use that to simulate `PiP` mode for other things. You have full control of what that window displays then, and you can implement whatever functionality you want - and there is no need to modify electron code.
