### ISSUE TITLE
MaxListenersExceededWarning but no proper stack of where

### ISSUE THREAD

**Issue by pocesar** [electron/electron#17750]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  4.1.4
* **Operating System:**
  *  Windows 10 x64 1809
* **Last Known Working Electron version:**:
  * 

### Expected Behavior

Be able to find where the `.on('error', () => {})` calls are happening

### Actual Behavior

Opaque warning with no stack trace

### To Reproduce

Really don't know, wish I knew

### Screenshots

![image](https://user-images.githubusercontent.com/461084/55915654-736ecb00-5bc0-11e9-9395-f9cc835e4958.png)

### Additional Information

Since the error is about adding "error" event listeners, makes it really hard to find where it's coming from (if it's from a module or my code). From my perspective, there are no "on" calls on my code, only "once", and they are removed if not triggered, at the end of component lifecycles. Tried setting ```process.traceProcessWarnings = true``` but didn't change anything. Also tried to apply a breakpoint on the line 18 o warning.js, but of course, I get the same stack

**Comment by miniak** [comment]
@pocesar do you see a different behavior in Electron compared to plain Node.js?

**Comment by miniak** [comment]
According to the implementation
https://github.com/nodejs/node/blob/a38e9c438ae872da37999c39d974facd4d524ea2/lib/internal/process/warning.js#L129

you can do this
```
process.on('warning', (e) => {
  console.log(e.stack)
})
```

**Comment by pocesar** [comment]
nope, already tried to  breakpoint there, there's no meaningful stack

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
