### ISSUE TITLE
File name not shown in save dialog in Electron 5

### ISSUE THREAD

**Issue by PalmerAL** [electron/electron#17754]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 5.0.0-beta.8
* **Operating System:** macOS 10.13.6
* **Last Known Working Electron version:**: 4.1.4

### Expected Behavior

The file name should be shown in the save dialog, as it is in Electron 4:

<img width="798" src="https://user-images.githubusercontent.com/10314059/55932619-0f63fb00-5bf0-11e9-852e-7c9ecf22ed70.png">

### Actual Behavior

No file name is shown:

<img width="797" src="https://user-images.githubusercontent.com/10314059/55932632-1985f980-5bf0-11e9-99f7-bb058a0a0134.png">

(Also, the dialog is attached to the window in Electron 5 but not 4, I'm not sure whether that's expected or not).

### To Reproduce

Create a link to a download in `index.html`:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
  </head>
  <body>
    <a href="https://github.com/electron/electron/releases/download/v5.0.0-beta.8/electron-v5.0.0-beta.8-win32-x64.zip">download link</a>
  </body>
</html>
```

**Comment by codebytere** [comment]
That was a result of changes in [this commit](https://github.com/electron/electron/commit/ca2d74e1185626f6c9179bf0cf7382e010a49bf0), i'll try to address this soon!
