### ISSUE TITLE
DPI change awareness on Windows

### ISSUE THREAD

**Issue by pronebird** [electron/electron#17756]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 4.1.4
* **Operating System:** Windows 10 (1803)
* **Last Known Working Electron version:**:
  *  N/A

### Expected Behavior

Browser windows should maintain its dimensions when DPI changes.

### Actual Behavior

When connecting to the Windows machine using RDP on macOS, the application receives scaleFactor, bounds and workArea display changes. However the browser windows don't seem to respect those changes and either scales up or down based on the new DPI, drawing UI entirely useless and broken.

### Similar issues

https://github.com/electron/electron/issues/11050

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
