### ISSUE TITLE
Electron-based apps freeze when playing sound on Linux

### ISSUE THREAD

**Issue by Booteille** [electron/electron#17768]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.1.3 (Riot) | IDK (Discord)
* **Operating System:**
  * Linux Mint 18.1

Both Discord and Riot freeze when they play sound (Discord from voice chat, Riot from notifications.)
It's maybe related to #14006.

**Comment by nornagon** [comment]
Without a minimized repro case there's not much we can do to work on this. Consider raising an issue with Riot or Discord and let them know to come back here if they're able to reduce the test case.
