### ISSUE TITLE
select tag issue in Webview?

### ISSUE THREAD

**Issue by buffet-time** [electron/electron#17765]
### Issue Details

* **Electron Version:** 4.1.4
* **Operating System:** Windows 10 x64 (1803) 
* **Last Known Working Electron version:** unsure

### Expected Behavior
Adding a select element without any changes should function like any browser

### Actual Behavior
The dropdown of the select element scrolls with the page instead of staying with the select element.

### Code snippets
The select element is taken [straight from W3S](https://www.w3schools.com/tags/tag_select.asp) 

      <select>
        <option value="volvo">Volvo</option>
        <option value="saab">Saab</option>
        <option value="mercedes">Mercedes</option>
        <option value="audi">Audi</option>
      </select>

and is inside a webview with these params: 
```
<webview tabindex="0"
      allowpopups
      plugins
      webpreferences="nodeIntegration=no,contextIsolation=no,webviewTag=no,webSecurity=yes,nativeWindowOpen=yes"
      preload="./preloads/content.js"
      partition="${this.partition}"
      src="${url || 'about:blank'}"></webview>
```

### Screenshots
Before Scroll
![beforeScroll](https://user-images.githubusercontent.com/11199709/55986708-0154bf80-5c6e-11e9-8e26-4e2434244757.PNG)

After Scrolled once
![afterScroll](https://user-images.githubusercontent.com/11199709/55986768-16315300-5c6e-11e9-9787-e85f3cd609cc.PNG)

**Comment by buffet-time** [comment]
Is this not reproducible for anyone else?

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by dube116** [comment]
This bug still exists.
Electron Version: 13.1.7
Operating System: Windows 10 x64 (1909)
