### ISSUE TITLE
FileList can't be sent from ipcRenderer to ipcMain

### ISSUE THREAD

**Issue by megancooper** [electron/electron#17763]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 4.0.3
  * 
* **Operating System:** macOS Mojave
  * 

### Expected Behavior

I am using `ipcRenderer` to send a FileList object from the renderer process to the main process so I can retrieve metadata from the files on the main process side. Here is the code on the renderer side that sends the files: (My app is made with react + redux)

```
export const importFiles = (files) => async(
  dispatch,
  getState
) => {
  ipcRenderer.send('import-files', files);
};
```

And the code on the main process side to service the event and grab the files:
```
ipcMain.on('import-files', async(event, files) => {
  console.log('import server side received ', await files);
  importFiles(files, dispatch);
});
```

I expect to receive a FileList object that looks something like this:
```
{
    0: {
       lastModified: 1554471086555,
       lastModifiedDate: "Fri Apr 05 2019 08:31:26 GMT-0500 (Central Daylight Time) {}"
       name: "test_upload",
       path: "/Users/megan/Desktop/test_upload",
       size: 1344,
       type: "",
       webkitRelativePath: ""
    }
}
```

### Actual Behavior
Instead of receiving the FileList object above, I get an empty object that looks like this on the main process side:
```
{ '0': {} }
```

Is there something preventing me from sending this FileList to ipcMain? Is there a way I can get around this? Thanks

**Comment by MarshallOfSound** [comment]
@megancooper the issue here is that the file objects inside a FileList aren't serializable.  You will have to extract the properties and data you need into a serialazable format like a normal object or a buffer before you send it over IPC

**Comment by nguyenbuithoi1997** [comment]
you should send the path instead of sending the file and at main.ts use fs.createReadStream (pat) to read it into the file

![image](https://user-images.githubusercontent.com/33334690/117583980-7a1bf380-b134-11eb-921b-b037cdf3d772.png)


and main.ts
![Uploading image.png…]()

**Comment by spencerwilson** [comment]
Thanks for the suggested workarounds! I wonder _why_ this doesn't work, though, given that

> Electron's IPC implementation uses the HTML standard [Structured Clone Algorithm](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) to serialize objects passed between processes

https://www.electronjs.org/docs/latest/tutorial/ipc#object-serialization

...and that `FileList` objects are structured-cloneable:
<img width="529" alt="image" src="https://github.com/user-attachments/assets/c5b71dba-3331-4d6f-9eee-23ad9302b014">
