### ISSUE TITLE
Ability to detect install from Apple store vs direct install

### ISSUE THREAD

**Issue by nickfujita** [electron/electron#17781]
Aside from having to create two separate builds, is there a way to detect whether an application has been installed by the user on OSX via the Apple app store or direct download.

There is currently the ability to detect the OS, using `process.platform`, but I can't seem to find a way to detect whether it was installed via app store or not. For bundling I am user `electron-builder`.

**Comment by MarshallOfSound** [comment]
> Aside from having to create two separate builds

You should be making two separate builds anyway using the `mas` platform for App Store distribution and `darwin` platform for non-App Store distribution.

Then you can use `process.mas` to detect whether or not you are running a `mas` build

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by nickfujita** [comment]
Thanks for the quick response.
