### ISSUE TITLE
nativeImage.createFromNamedImage returns nothing

### ISSUE THREAD

**Issue by erikjalevik** [electron/electron#17785]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.1.4
* **Operating System:**
  * MacOS 10.14.4
* **Last Known Working Electron version:**:
  * n/a

### Expected Behavior
`createFromNamedImage` to return the image name passed as a string, in this case "NSImageNameFolder".

### Actual Behavior
`createFromNamedImage` returns no image data.

### To Reproduce
Here is a repo showing the issue: 

https://github.com/erikjalevik/electron-retina-nativeimage-bugs

Instructions:
```
git clone git@github.com:erikjalevik/electron-retina-nativeimage-bugs.git
npm install
npm run start
```

The third section of the page shows the non-existent image under "nativeImage.createFromNamedImage".

### Screenshots

<img width="475" alt="Screenshot 2019-04-15 at 13 53 52" src="https://user-images.githubusercontent.com/8722592/56130703-ef349300-5f85-11e9-8c97-89e082cf1294.png">

**Comment by codebytere** [comment]
Strangely, this is localized: it doesn't repro if i use, for example, `NSActionTemplate`.
