### ISSUE TITLE
PPAPI process opening console windows when run from non-console

### ISSUE THREAD

**Issue by paulcbetts** [electron/electron#1779]
1. Create a Win32 Electron app that sets up Pepper Flash
2. Run the EXE from Explorer (you won't see this if you run Electron from a console)
3. Be very observant

You'll notice a DOS box flash open then immediately close. If we use Image File Execution Options to set a dummy EXE as our Debugger for "Cmd.exe" (I used Notepad), we can see what's happening:

![](http://cl.ly/image/2I3a022g1p3g/content#png)

PPAPI process is trying to echo "NOT SANDBOXED", but because we don't have an attached Console, it creates one

**Comment by cusr** [comment]
I'm facing the same problem. 
Is there any way to stop the console window from popping up?

**Comment by deepak1556** [comment]
Related https://code.google.com/p/chromium/issues/detail?id=508002

**Comment by ppoo24** [comment]
+1

**Comment by zcbenz** [comment]
The original Chromium issue has been closed as won't fix, and the console window is from the flash player so it is possible to fix it on our side.

**Comment by paulcbetts** [comment]
Can we run non-guest-view plugin processes in a sandbox? We shouldn't have to deal with node.js there

**Comment by zcbenz** [comment]
@paulcbetts It could be possible, I'll try to approach the developers of adobe flash player first.

**Comment by Gandii** [comment]
Was the "non-guest-view plugin processes in a sandbox" approach ever attempted to solve this? 

Been banging my head against this issue for a while now without success. Seems neither Chromium nor Adobe consider this a bug. Cef had some luck with hooking on to the process but issue seems to go unsolved for most. Even Modifying the dll seems not to work.

**Comment by TimvdEijnden** [comment]
Any update on this?

**Comment by StinsonZhao** [comment]
I have the same problem.
Any resolution now?

**Comment by SkiTiSu** [comment]
Still have this problem.

**Comment by hankbao** [comment]
However modifying a dll binary breaks its digital signature.

**Comment by upjersdave** [comment]
Very true, which is why I said you wouldn't like it 😄

**Comment by upjersdave** [comment]
Hello again,

We didn't really like the hex-editing solution either, however there is another solution to bypass the problem:

The DLL looks for the system variable `COMSPEC` when building the path to start the console window. `COMSPEC` usually contains: `C:\Windows\System32\cmd.exe`, which is what is opened when `NOT SANDBOXED` is printed to the console.

To avoid the terminal, it is possible within your `main.js` to overwrite `process.env.COMSPEC` with your own command interpreter path. e.g. `process.cwd() + "/bin/replacement-cmd.exe"`. This command interpreter inspects the command line requested and, only if it does not contain the string `NOT SANDBOXED`, forwards the command to the original system `cmd.exe`, effectively acting as a filtering proxy between electron and the original `cmd.exe`, bypassing the flickering terminal window completely.

`replacement-cmd.exe` can be written in C++ and only needs to inspect `lpCmdLine` and open the original `cmd.exe` using `ShellExecuteA()`, which uses the original `COMSPEC` value and not the one you overwrote. I am unfortunately unable to post the code for this here, but this should be enough information to do it yourselves if necessary.

**Comment by SamDelgado** [comment]
@upjersdave Thanks for sharing this awesome solution!

**Comment by IMcPwn** [comment]
This was quite annoying to write, but it works!

replacement-cmd.cpp
```
#include <windows.h>
#include <iostream>

char* concatptr(char* first, char* second) {
   size_t size = strlen(first) + strlen(second) + 1;
   char* result = new char[size];

   strcpy(result, first);
   strcat(result, second);

   return result;
}

int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow)
{
  if (std::string (lpCmdLine).find("NOT SANDBOXED") != std::string::npos) {
    // achoo
  } else {
	  ShellExecuteA(NULL, NULL, "C:\\Windows\\System32\\cmd.exe", concatptr(LPSTR("/c "), lpCmdLine), NULL, SW_HIDE);
  }
  return 0;
}
```

**Comment by SamDelgado** [comment]
Thanks for sharing your code @IMcPwn ! I am unfortunately still getting the flickering command prompt, but it appears that the NOT SANBOXED message is gone. I am compiling the file with `g++ -static replacement-cmd.cpp -o replacement-cmd.exe`. Any suggestions?

**Comment by IMcPwn** [comment]
@SamDelgado I think it has something to do with the ```/c``` parameter. I hadn't had a chance to package it up yet but a different one of these parameters or possibly no parameter might fix it: https://stackoverflow.com/a/515380

**Comment by SamDelgado** [comment]
@IMcPwn Thanks for the quick response! I am going to check this out now. I will report back if it works.

**Comment by IMcPwn** [comment]
@SamDelgado since we almost got the C++ part working, could you share how you got the Electron Path to update? These didn't work for me, COMSPEC stayed as C:\Windows\system32:

```process.env['COMSPEC'] = path.join(app.getAppPath(), path.join('lib', 'replacement-cmd.exe'))      process.COMSPEC = path.join(app.getAppPath(), path.join('lib', 'replacement-cmd.exe'));```

**Comment by IMcPwn** [comment]
@SamDelgado I updated my above comment to hide the command window.

**Comment by SamDelgado** [comment]
@IMcPwn Thanks for updating your original code! Everything works now!

Try changing the COMSPEC like this: `process.env.COMSPEC = path.resolve(app.getAppPath(), 'lib', 'replacement-cmd.exe');`

**Comment by IMcPwn** [comment]
@SamDelgado It worked! Thanks. Good luck to any future readers 😉

**Comment by alexanderturinske** [comment]
Worked for me! Thanks!

**Comment by codebytere** [comment]
Closing given the above workarounds and continued infeasibility of a fix from our side.

**Comment by denchik180283** [comment]
создайте пустой exe файл  , и укажите путь к нему в process.env.COMSPEC  --  проблема решена!!

**Comment by denchik180283** [comment]
create an empty exe file, and specify the path to it in process.env.COMSPEC - problem solved !!

**Comment by denchik180283** [comment]
я имею ввиду process.env.COMSPEC   в  mian.js

**Comment by aswzen** [comment]
So how to fix it ?
