### ISSUE TITLE
before-input-event is causing weird behaviours with webview when handled.

### ISSUE THREAD

**Issue by maxerbox** [electron/electron#17794]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.1.4
* **Operating System:**
  * Debian 9.8 Stretch Linux x64 gnome

### Expected Behavior

Webview should act normally.

### Actual Behavior

Listening to the event before-input-event on the webcontents of a webview is causing strange behaviours:
- Reloading the webview, with webview.loadURL(webview.src)  is no longer working.
- In webview's devtools, the inspector is no longer working (when you click on it, nothing works)

### To Reproduce

* `git clone https://github.com/maxerbox/community-edition`
* `git checkout fix-electron-issue-key-propragation`
* `sencha app watch` (see [CONTRIBUTING.md](https://github.com/maxerbox/community-edition/blob/fix-electron-issue-key-propragation/CONTRIBUTING.md) to see build requirements
In another terminal:
* npm start

### Screenshots

![1-notworking](https://user-images.githubusercontent.com/12765875/56144147-29139280-5fa2-11e9-9c8d-504647a4a12e.gif)
Here it is not working, the inspect tool and the webview is no longer responding (I try to load another url, it shows in the network tab that it loaded `google.com`, but unfortunately the webview hasn't changed).

![1-working](https://user-images.githubusercontent.com/12765875/56144113-15682c00-5fa2-11e9-90be-5efe2fdd7514.gif)
Here is a quick example where it's working (not using before-input-event)
The inspect tool is working, and also I load another url successfully.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
