### ISSUE TITLE
Open source the electron node.js implementation

### ISSUE THREAD

**Issue by mjmacleod** [electron/electron#17803]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Electron is advertised as and widely believed by those using and/or advocating it to be open source.
However it uses a custom node.js, the headers for this custom node.js are hard to track down but with a bit of effort (looking in the electron-rebuild) source code I was able to find tarballs of them here: https://atom.io/download/electron/v4.1.4/iojs-v4.1.4.tar.gz
These are however just the headers, I cannot find a source repository for these headers other than these tarballs that are not publicly advertised. I cannot find a repository (or tarball) or any kind of matching source code for the node.js fork/implementation that goes with these headers.

As the node.js implementation plays a very central/large role within any Electron app and as Electron is advertised as open source, the expectation is that the source code for the node.js portion should be available.

### Proposed Solution

There should be a publicly available repository for the electron node.js source code, if one exists it should be linked and documented more prominently so that it can be easily located, after much effort I've been unable to locate it so far.

### Alternatives Considered

There should be a publicly available repository for the electron node.js headers, which should explain at least why the source code is not available and gives a general breakdown of how the custom implementation differs from default node.js.
There should be prominent notices elsewhere explaining that only parts of electron are open source so that users are not given the wrong impression up front.

**Comment by mjmacleod** [comment]
Nevermind - I see the sources are here https://github.com/electron/node but in branches, because it is in branches it doesn't turn up in any searches github or google...

Closing as I managed to find it, still think this could be made a lot more clear.

**Comment by nornagon** [comment]
Do you have any suggestions for where we should put that link? The README of https://github.com/electron/node does link to the branches.

**Comment by mjmacleod** [comment]
I'm not sure really whats best to change. I can only explain from my perspective what happened and maybe you can draw some conclusions from that.

Sorry if the below is a bit long...

I'm a c++ developer with relatively broad experience dabbling in other technologies, I've worked with libcef before but never (up until now) electron directly - I do have a general understanding of how electron works etc. though.

A user of an existing framework I maintain, that already runs on several mobile platforms and desktop, was interested in being able to use it with electron for a basic prototype so I decided to assist him. However I set out first to support plain node.js, as others might find this useful too.

While I'm aware most node guides recommend using node-gyp to build etc. and I can understand why this is pushed for the average node user (who is usually writing new native code over at most a few cpp source files) - for a complex framework the easiest path to get something going was to modify our autotools based build system.

I managed to get a basic node.js module working relatively quickly and decided to then move on to trying it with electron. At this point I ran into issues with a clash in node.js versions, and realised I need to target a slightly different node for electron.

So I looked in the electron source directory, and found nothing. I tried to grep the source for references to it and found nothing. I did a google search for things like `"#define NODE_MODULE_VERSION 69" site:github.com` and found nothing.
I searched the "releases" of this repository thinking I might find something there, but nothing.
I trawled through various guides, and pages on the electron site to see if I could find any links to it and nothing, I searched the electron github but couldn't find anything.
The only hits I got for node.js and 69 talked about electron-rebuild, so I dug into that a bit and eventually found https://atom.io/download/electron/v4.1.4/iojs-v4.1.4.tar.gz which is confusingly named - it doesn't however contain a link to the repo it comes from...
It did have the contents I needed to build so at this point I had a working product and was "done"...

However I was still curious so I decided to search more. I ran into dead/archived repositories when searching for iojs, I decided to ask a few people who do use electron if they knew anything about where to find the electron node.js implementation and none of them knew anything etc.

At that point I filed this report, and then (murphies law) straight afterwards decided to click on electrons github profile, saw a "node" repo that looked empty, looked closer and noticed the text you mention about branches - at this point I realised this was it and posted my reply...

I'm sure at some point in all of the above I probably clicked on the node repo, saw it looked empty then closed it or similar, that would have been my mistake and I probably should have looked closer.
I realise that I'm not the average target user and that this is why the documentation is geared mostly towards pushing people to electron-rebuild, node-gyp etc. 

That said there are various points in the above process where some simple text might have saved me some time, possible places a change might have helped me (up to you to judge whether it would help others)
1) Uploading an appropriately named node header tarball with every release
2) Alternatively, placing a link to the right repo/branch of node.js in release notes of every release
3) Mentioning where the node repo (or headers tarballs) can be obtained somewhere on https://electronjs.org/docs/tutorial/using-native-node-modules or other similar parts of the website
4) Having the master branch of your node repo match the current LTS (or similar) branch instead of be empty - however I realise this is quite a big change.
5) Alternatively having the other branches is indexed by google - however not sure if this is possible
6) Briefly linking/mentioning the nodejs branch(es) somewhere in the electron README.md


Anyway I hope this has been of some use.
