### ISSUE TITLE
Print a photo in a 6x4 paper size in silent mode

### ISSUE THREAD

**Issue by rodrigocvb** [electron/electron#17811]
* **Electron Version:** 3.1.8
* **Operating System:** macOS 10.11.6

### Expected Behavior
Print out a 6x4 photo using a Hiti P510S printer. I would like my jpg imagem file to fill the entire paper. This photo is opened in a new BrowserWindows containing only its img tag.

### Actual Behavior
When I print it to a pdf file, it looks ok (it fills the entire document and 100% of the photo is shown), but when I send it to the printer, the photo seems to be centered in a bigger document, with white margins around it.  So I get as a result only part of the photo at the bottom right of the 6x4 paper and blank all over the rest.
If I set silent:true, the printing dialog pops up and I'm able to choose 6x4 paper size (an other options like fill the entire paper). This way, it works. But I'm not able to set paper size without showing this dialog (which is what I need).

### To Reproduce

The printing code:
`win.webContents.print({ silent:true, deviceName:'HiTi_P510S' }, (callback) => {
    if(callback)
      console.log('callback true')
    else
      console.log('callback false')
  })`

The style
```
@media print {
  @page {
    size: 6in 4in;
    margin-top: 0cm !important;
    margin-left: 0cm !important;
  }

  #printer-content {
    position: absolute;
    left: 0;
    top: 0;
  }
}

body {
  margin: 0px !important;
}

.photo {
  width: 6in;
  height: 4in;
}
```

**Comment by zlab** [comment]
### paper size

![image](https://user-images.githubusercontent.com/2288630/69718593-b8447380-1149-11ea-938a-d31f3befb0d9.png)

**Comment by codebytere** [comment]
Closed by https://github.com/electron/electron/pull/18984.

**Comment by cxiliao** [comment]
@rodrigocvb Have you already solve this problem? I'm using HiTi P322W printer, and also meet the same problem on printing a 6*4 image.

**Comment by vicckuo** [comment]
@rodrigocvb Have you already solve? I have same problem
