### ISSUE TITLE
shell.showItemInFolder in MAC OS opens Finder very slow

### ISSUE THREAD

**Issue by Dhananjay-Shetti** [electron/electron#17835]
shell.showItemInFolder in MAC OS opens Finder very slow or freezes for sometime.
As i am running this packaged app from external hard drive. So in shell.showItemInFolder filepath parameter is having filepath of external drive. Filepath folder contains more than 100 files in it. 
 As I am new to electron any help will be appreciated.
Thanks in Advance.

**Comment by JieJiSS** [comment]
Maybe you can try this as a workaround:

```js
const cp = require('child_process');
const { promisify } = require('util');
const exec = promisify(cp.exec);

async function showItemInFolder(path) {
  if(process.platform === 'darwin') {
    if(!path.endsWith('/'))
      path += '/';
    await exec(`open "${path}"`);  // use `open <path> to start a finder window
  } else {
    // use Electron.js' api
  }
}
```

**Comment by Dhananjay-Shetti** [comment]
> Maybe you can try this as a workaround:
> 
> ```js
> const cp = require('child_process');
> const { promisify } = require('util');
> const exec = promisify(cp.exec);
> 
> async function showItemInFolder(path) {
>   if(process.platform === 'darwin') {
>     if(!path.endsWith('/'))
>       path += '/';
>     await exec(`open "${path}"`);  // use `open path/to/dir to start a finder window
>   } else {
>     // use Electron.js' api
>   }
> }
> ```
> 
> on my MacOS 10.13.6 it takes about 500ms to show a finder window.
> 
> Or, you can also try `open /System/Library/CoreServices/Finder.app path/to/dir`, which has the same effect as method 1.

Thanks quick response. 
This does work for me. 
I tried with  await exec(`open "${path}"`); and await exec(`open /System/Library/CoreServices/Finder.app "${path}"`); and await exec(`open -R "${path}"`); 
But no luck. 
I am calling shell.showItemInFolder method from main.js file. I want to open specific folder and select the file. showItemInFolder works fast in windows but where in MAC its is very slow. I am using Mojave OS.

**Comment by codebytere** [comment]
@Dhananjay-Shetti we require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by jbis9051** [comment]
I am also having this issue. I don't want to execute commands. Is there a fix for the function?

**Comment by Dhananjay-Shetti** [comment]
> 
> 
> I am also having this issue. I don't want to execute commands. Is there a fix for the function?

After code signing in MAC. This issue got resolved.

**Comment by jbis9051** [comment]
@Dhananjay-Shetti  Odd that code signing would make a difference

**Comment by jbis9051** [comment]
I was able to solve by forwarding it the `ipcMain`.

component.js
```
const open = path => {
    _electron.ipcRenderer.send('show-file',path);
};
```

main.js
```
const {shell} = require('electron');
ipcMain.on('show-file', (e,path) =>{
	shell.showItemInFolder(path);
});
```

**Comment by popod** [comment]
@sofianguy please reopen this issue. The issue template is not filled, but I think they is enough informations now. Ans this issue a really problem, so it should not be closed. Thanks
