### ISSUE TITLE
webContents.capturePage take a screenshot of the complete webpage

### ISSUE THREAD

**Issue by dlamon** [electron/electron#17834]
*Electron version: 4.0.1*
*Operating system: MacOS 10.14*

### Problem Description
I use webContents.capturePage to get a full screenshot of the current page. If the height of page is larger than the BrowserWindow (or when there's a scroll bar), the overflow part is not included in the captured image. 

### Proposed Solution

Can you provide a solution to get a full screenshot of the page, like Puppeteer's full-page screenshot: `page.screenshot([fullPage: true])`

**Comment by codebytere** [comment]
Unfortunately this isn't something we think is in our best interest to pursue, as it's nontrivial and will create significant overhead and maintenance. Consider, for example, an infinite scrolling site like Reddit; how would one determine the full height of that page? 

I'm going to label this a `wontfix` and close it but am happy to revisit in the future should something change!
