### ISSUE TITLE
electron3.x and 4.x in win10 touch screen frequent multiple clicks program crash

### ISSUE THREAD

**Issue by FruitPineapple** [electron/electron#17836]
I use electron 4.x packaged a Vue application ,if I install the win10 64 touch screen and frequent multiple clicks, the program will crash.

If use electron 2.x every thing is ok ,no problem.

I need your help.

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by FruitPineapple** [comment]
Below is the template I created：

https://github.com/FruitPineapple/test-electron4.x.git

you can clone it and npm install , next build it .
If you  install the win10 64 touch screen and frequent multiple clicks ,you will find the question.

Thank you very much for your reply

//I am sorry that my English is not very  good. ^_^:smile:

**Comment by FruitPineapple** [comment]
> Thanks for reaching out!
> 
> We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.
> 
> Thanks for understanding and meeting us half way

Below is the template I created：

https://github.com/FruitPineapple/test-electron4.x.git

you can clone it and npm install , next build it .
If you install the win10 64 touch screen and frequent multiple clicks ,you will find the question.

Thank you very much for your reply

//I am sorry that my English is not very good. ^_^smile

**Comment by flausinoth** [comment]
I'm having the same issue, anyone solved  ?

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
