### ISSUE TITLE
failed to run "gn gen" when building electron on Windows

### ISSUE THREAD

**Issue by betterRunner** [electron/electron#17856]
- Operating System (Platform and Version):
Windows 10 and VS 2017

- electron version
^4.0.0

-  To reproduce

1. successfully got the code as https://electronjs/org/docs/development/build-instructions-gn
2. cd src
3. set CHROMIUM_BUILDTOOLS_PATH=%cd%\buildtools
4. gn gen out/Release--args="import("//electron/build/args/release.gn")"

```
Traceback (most recent call last):
  File "C:/git/electron-gn/src/build/vs_toolchain.py", line 471, in <module>
    sys.exit(main())
  File "C:/git/electron-gn/src/build/vs_toolchain.py", line 467, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "C:/git/electron-gn/src/build/vs_toolchain.py", line 293, in CopyDlls
    _CopyDebugger(target_dir, target_cpu)
  File "C:/git/electron-gn/src/build/vs_toolchain.py", line 326, in _CopyDebugger
    % (debug_file, full_path))
Exception: dbghelp.dll not found in "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\dbghelp.dll"
You must install the "Debugging Tools for Windows" feature from the Windows 10 SDK. You must use v10.0.17134.0. of the SDK
ERROR at //build/toolchain/win/BUILD.gn:50:3: Script returned non-zero exit code.
  exec_script("../../vs_toolchain.py",
  ^----------
Current dir: C:/git/electron-gn/src/out/Release/
Command: C:/Python27/python.exe -- C:/git/electron-gn/src/build/vs_toolchain.py copy_dlls C:/git/electron-gn/src/out/Release Release x64
Returned 1.
See //BUILD.gn:60:1: which caused the file to be included.
group("gn_all") {
^----------------
```

I did install the vs2017 with sdk10, so how can I fix this issue ?
Thanks.

**Comment by MarshallOfSound** [comment]
@betterRunner Uninstall the SDK through the Visual Studio Installer.  Then install the Windows 10 SDK manually from https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk and ensure that "Debugging Tools for Windows" is checked

**Comment by betterRunner** [comment]
@MarshallOfSound thanks for your help, it did solve the SDK problem but another issue raises:

SDK v10.0.17134.0 (which is the default one in microsoft website now) change the folder structure 
![tmp](https://user-images.githubusercontent.com/7123136/56350198-cd911100-61fc-11e9-9509-84055fbe840f.png)
so it will raise error in 'vs_toolchain.py'

I install the previous one (v0.0.14393.0) instead, then it raised the error:

`Command: C:/Python27/python.exe -- C:/git/electron-gn/src/build/toolchain/win/setup_toolchain.py "C:\Program Files (x86)/Microsoft Visual Studio/2017/Community" "C:\Program Files (x86)\Windows Kits\10" "C:\Windows\System32;C:\Windows/SysWOW64" win x64 environment.x64
Returned 1 and printed out:

vc_bin_dir = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64"
include_flags_I = "\"/I..\\..\\..\\..\\..\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\ATLMFC\\include\" \"/I..\\..\\..\\..\\..\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\include\" \"/I..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.14393.0\\ucrt\" \"/I..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17134.0\\shared\" \"/I..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17134.0\\um\" \"/I..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17134.0\\winrt\" \"/I..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17134.0\\cppwinrt\""
include_flags_imsvc = "\"-imsvc..\\..\\..\\..\\..\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\ATLMFC\\include\" \"-imsvc..\\..\\..\\..\\..\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\include\" \"-imsvc..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.14393.0\\ucrt\" \"-imsvc..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17134.0\\shared\" \"-imsvc..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17134.0\\um\" \"-imsvc..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17134.0\\winrt\" \"-imsvc..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.17134.0\\cppwinrt\""
vc_lib_path = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\lib\\x64"
vc_lib_atlmfc_path = "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\ATLMFC\\lib\\x64"

See //BUILD.gn:60:1: which caused the file to be included.
group("gn_all") {
^----------------
Traceback (most recent call last):
  File "C:/git/electron-gn/src/build/toolchain/win/setup_toolchain.py", line 292, in <module>
    main()
  File "C:/git/electron-gn/src/build/toolchain/win/setup_toolchain.py", line 284, in main
    assert vc_lib_um_path
AssertionError`

semms the vs2017 still point to version 10.0.17134.0, so which SDK version should I use and how to make vs2017 recognize it?
Thanks.
