### ISSUE TITLE
Win.setIcon is invalid after program installation(win.setIcon  在程序安装后使用无效)

### ISSUE THREAD

**Issue by qinzhongting** [electron/electron#17857]
Main process code:
`
//Modify icons after offline
    if(arg == 'windwIco_offline'){
      win.setTitle('offline');
      win.setIcon(nativeImage.createFromPath(path.join(__static, '/icon/iconx/128x128.png')));
    }
    //Modify the icon after going online
    if(arg == 'windwIco_online'){
      win.setTitle('online');
      win.setIcon(nativeImage.createFromPath(path.join(__static, '/icon/icons/128x128.png')));
    }
`
It is ok in a production environment.
It is also possible to start directly in the **win-unpacked** folder after packaging.
After installing with exe installation files, it will not work.

---------------------------------------------------------------------------------------------------------------
主进程代码：
`
//离线后修改图标
    if(arg == 'windwIco_offline'){
      win.setTitle('离线了');
      win.setIcon(nativeImage.createFromPath(path.join(__static, '/icon/iconx/128x128.png')));
    }
    //上线后修改图标
    if(arg == 'windwIco_online'){
      win.setTitle('在线');
      win.setIcon(nativeImage.createFromPath(path.join(__static, '/icon/icons/128x128.png')));
    }
`
生产环境下是可以的。
打包完毕后在**win-unpacked**文件夹下直接启动也是可以的。
使用exe安装文件安装后打开就不行了。

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
