### ISSUE TITLE
.exe Windows installer is not working on any other windows machine

### ISSUE THREAD

**Issue by vishakhag6** [electron/electron#17859]
### Issue Details

Trying to create a windows installer using electron. Although my project was in angular 7 but downgraded it to angular 6.0. 

Using `electron-packager` for creating windows installer. A folder is getting created with .exe and another folder as well. That .exe is opening for that windows machine but if I open that .exe on another windows machine it gives the **error of fmpeg.dll is not found**.  

To resolve fmpeg.dll I installed that externally and set the path too but still, the error persists. 

I am creating my windows installer by this following command:
`electron-packager . --platform=win32 --arch=x64`

My main.js file looks like this:
`const { app, BrowserWindow } = require('electron');
let win;
function createWindow() {

win = new BrowserWindow({ width: 800, height: 600 });

win.loadFile('../dist/app/index.html');

win.on('closed', () => {
win = null
})
};

app.on('ready', createWindow);
app.on('window-all-closed', () => {
if (process.platform !== 'darwin') { app.quit() }
});

app.on('activate', () => {
if (win === null) { createWindow() }
}); `

Any solution?

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
