### ISSUE TITLE
File download dialog is not modal

### ISSUE THREAD

**Issue by iamusenix** [electron/electron#17855]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 4.1.4
* **Operating System:** MacOS 10.14.2
* **Last Known Working Electron version:**: 4.0.1

### Expected Behavior

File download dialog should be modal, just like **Chrome** browser. When file dialog is open user should not be able to operate the active page.
### Actual Behavior

File download dialog is not modal. User can click the active page and go on operating. 
### To Reproduce
new a BrowserWindow and load url to any webpage which can download a file. When the file download dialog is open, it's not parented to current page which is not **modal**.

### Additional Information

I tried several versions (4.0.1, 4.1.4, 5.0.0-beta.1, 5.0.0-beta.8) on MacOS and Windows, and the file download dialog behaved differently for modal mode. Modal mode is working only on MacOS for version 4.0.1. None is working on Windows(win7, server 2012 tested).

Should the file download dialog(web download via BrowserWindow) be modal or not? I googled for a while and unfortunately didn't find any thing about this issue.

**Comment by codebytere** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by iamusenix** [comment]
I found a workaround for anyone who facing the same issue.  Just hook the "will-download" event and provide a self made dialog(Modal of course).  Prevent the default behavior if no file is selected. 

webContents.session.on("will-download",(event, item, webContents)=>{
    const fileName = item.getFilename()
    var path = dialog.showSaveDialog(winMain, {defaultPath:fileName})
    if(path){
      item.setSavePath(path)
    }else{
      event.preventDefault()
    }
    console.log(path)
  })

**Comment by codebytere** [comment]
This has been fixed in all versions of Electron v5 and later.

**Comment by alilang885** [comment]
Bump
