### ISSUE TITLE
maximize the window in render process with remote.getCurrentWindow().maximize() the animation isn't smooth as use ipcRenderer send a message to main process to window.maximize() on MaxOS.

### ISSUE THREAD

**Issue by Aura-zx** [electron/electron#17858]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.1.4
* **Operating System:**
  *  macOS 10.14.4
* **Last Known Working Electron version:**
  * 

### Expected Behavior
 the smooth of maximize window is the same when call maximize() 

### Actual Behavior
in render process the animation isn't smooth

### To Reproduce
https://github.com/Aura-zx/electron-quick-start

the animation of maximize window of two button 'max with window' and 'max with ipc' is different.

**Comment by MarshallOfSound** [comment]
@Aura-zx This is expected behavior, the `remote` module uses synchronous blocking IPC to communicate with the main process.  So when you call `maximize()` through remote the renderer process is blocked causing the animation to not be as smooth for a few `ms`.  This can be noticeable.  You should just use the async `ipc` messaging you set up 👍

**Comment by Aura-zx** [comment]
@MarshallOfSound thanks for your reply. Does it block also appears in `react`? In my project, I send a message to maximize, the I call `setState`, it also has a few `ms` block.
