### ISSUE TITLE
tray get wrong bounds when the system's notification area was hide

### ISSUE THREAD

**Issue by orangeChu** [electron/electron#17852]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 4.1.x
* **Operating System:** Windows 7 (64 bit) & Windows 10
* **Last Known Working Electron version:** It seems that this problem has always existed

### Expected Behavior
`tray.getBounds()` return correct bounds when the system's notification area was hide.

### Actual Behavior
`tray.getBounds()` got wrong bounds of tray.

### To Reproduce
Based on the Electron Fiddle test with below code.

``` javascript
const { app, BrowserWindow, nativeImage, Tray } = require('electron')

let mainWindow
let tray

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true
    }
  })

  mainWindow.loadFile('index.html')

  mainWindow.on('closed', function () {
    mainWindow = null
  })
}

function createTray() {
  tray = new Tray(nativeImage.createFromPath('D:\Electron\test\logo.ico'))

  console.log(tray.getBounds())

  tray.on('click', (event, bounds, position) => {
    console.log(bounds)
  })
}

app.on('ready', () => {
  createWindow()
  createTray()
})

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', function () {
  if (mainWindow === null) {
    createWindow()
  }
})
```

### Screenshots
![tray getbounds](https://user-images.githubusercontent.com/25950247/56328124-19699900-61b0-11e9-9f2e-e42262508d52.gif)

**Comment by benpolinsky** [comment]
Any workaround/way to determine if the system notification menu is active? I can replicate the same behavior.

**Comment by orangeChu** [comment]
> Any workaround/way to determine if the system notification menu is active? I can replicate the same behavior.

I am afraid there is no native way to achieve your goal.

**Comment by benpolinsky** [comment]
Just to follow up on anyone who may be interested a workaround/alternative approach:

[The Electron docs for `screen`](https://electronjs.org/docs/api/screen) provide methods that can assist with consistent width and height values for a particular display. Between those methods and the various `bounds` methods, I think there's enough to set a consistent window position relative to a screen corner.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
