### ISSUE TITLE
Electron BrowserWindow refreshes when you press F5 in Chrome

### ISSUE THREAD

**Issue by janakaonline** [electron/electron#17867]
I'm having this weird issue,
When I have my Chrome browser and the Electron app open, if I press F5 inside the Chrome browser, browser tab does not refresh. But the Electron app BrowserWindow refreshes even it is on the background. Does anyone has a solution for this?

**Steps to re create the bug**

- Open a BrowserWindow in a Electron app
- Open the Chrome browser
- Press F5 while on Chrome
- You will see Electron BrowserWindow refreshes even it is in the background

Thanks

**Comment by jdfwarrior** [comment]
I could be off but it sounds like you may have (in your electron app) registered a global hotkey that may be blocking the use of F5 elsewhere and always reloading your electron app. Just a thought

**Comment by janakaonline** [comment]
Thanks @jdfwarrior. That was the case. I thought those globalShortcuts are only when you are in the app. Missed the documentation explanation of it. 

Again thank you for pointing it out :)

Issue closed ;)
