### ISSUE TITLE
Branches 3.x.x and 4.x.x slower start

### ISSUE THREAD

**Issue by armandn** [electron/electron#17876]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.1.4
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**:
  * 2.0.14

### Expected Behavior
If I compile my app with Electron 2.0.0 - 2.0.14, startup is fast - the browser window is created almost instantly.

### Actual Behavior
Compiling the same app with 3.0.0, 4.0.0 and 4.14, there's a significant delay (5 seconds on a i7 @ 4GHz) before the browser window is created. The delay happens before the main.js starts executing.

Before trying to create an example, I want to know if it's a known issue.

**Comment by armandn** [comment]
I made a few more tests and it looks like the problem is related to the electron.exe being digitally signed (I signed it in my app). Not 100% sure yet. I will try to get a definitive answer. I don't know if I should close this issue for now or not.

**Comment by Qiplex** [comment]
`electron 5.0.6` - empty app ~11 seconds start on Windows 10 and Windows 7

**Comment by nornagon** [comment]
I can't reproduce this; all current electron versions start promptly (<1sec) on both Windows 10 and Windows 7 under my testing. @Qiplex is there something else on your system that might be interfering?

**Comment by Qiplex** [comment]
Hey @nornagon. Thanks for looking into this. I have resolved this in the following issue:
https://github.com/electron/electron/issues/19362
