### ISSUE TITLE
clipboard.readText('selection') doesn't work on MacOs.

### ISSUE THREAD

**Issue by CarlosEduR** [electron/electron#17881]
I've been working on an electron project which I need to get - when the user hits shortcut - selected text in any window's system (browser, notepad, etc). I've first tried in Linux (and it worked perfectly), but when I tried it in MacOs, the readText('selection') function only returns what there is in my clipboard. Does anybody know any other way to get this information with electron or nodejs?

**Comment by nornagon** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by CarlosEduR** [comment]
### Preflight Checklist


* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  "4.1.4"
* **Operating System:**
 macOS - Sierra 10.12 
* **Last Known Working Electron version:**:
  * 

### Expected Behavior
Getting selected text in Electron outside Electron window by hitting shortcut.

### Actual Behavior
When shortcut is typed the script returns what is in clipboard, the value from my last copy action.

### To Reproduce
I run this exactly code on my Linux machine and it returns what I need.

const {app, clipboard, globalShortcut} = require('electron');

app.on('ready', () => {
    globalShortcut.register('CTRL+ALT+K', () => {
        console.log('Shortcut pressed.');
        getSelectedText();
    })
})

function getSelectedText(){
    let text = clipboard.readText('selection');
    console.log(text);
}

(Electron app is running) - User highlights some text in (browser, notepad, wherever), type CTRL+ALT+K
and console.log text selected.

### Additional Information

**Comment by codebytere** [comment]
hey @CarlosEduR, unfortunately only platforms that use the X Window System support the selection buffer. This means that it won't work on macOS; i'll edit the docs to reflect this more clearly.

**Comment by arvinxx** [comment]
> hey @CarlosEduR, unfortunately only platforms that use the X Window System support the selection buffer. This means that it won't work on macOS; i'll edit the docs to reflect this more clearly.

Hi, I want to consult you that what other method can i use to achieve this function?That's mean a lot for me.Thanks
.

**Comment by linonetwo** [comment]
Seems `clipboard.readText()` always return `undefined` in Mac?

**Comment by arvinxx** [comment]
@CarlosEduR hi guy, do you solve the problem?
