### ISSUE TITLE
Google Sign-in Breaking in June 2019 for embedded frameworks

### ISSUE THREAD

**Issue by rosssketchup** [electron/electron#17887]
I read the post on the Google security blog: https://security.googleblog.com/2019/04/better-protection-against-man-in-middle.html which says that any embedded browsers will no longer be allowed to sign in to Google starting in June of 2019.

Does this mean that any Electron app that has not implemented Google authentication 'correctly' will break?

In other words, you should use your system browser to log the user in, and then you'll have to host a local web server to receive the code once the login flow is complete.

If anyone has more information about this, that would be great.

**Comment by MarshallOfSound** [comment]
@rosssketchup All I can say is to respectfully follow https://groups.google.com/a/chromium.org/d/msg/embedder-dev/STyM5ZNTHMM/POj1v_cqBgAJ.  Please note that both the Chromium team and the Electron team found out about this at the same time as everyone else and this wasn't a Chromium decision rather an internal Google Sign-In decision.

No one has more information other than what is in that blog post at this point.

I will leave this issue open as a discussion thread

**Comment by rosssketchup** [comment]
@MarshallOfSound Thanks for the information. Yikes, this seems like this is going to break a lot of people.

**Comment by stevenroussey-privicy** [comment]
And it is breaking....

**Comment by Nik720** [comment]
I am facing the same issue, Is there any workaround or different approach of google sign in with electron app?

**Comment by johannesjo** [comment]
@Nik720 there are possibly three slightly complicated workarounds possible:
1. Using some local loopback server to get the auth response (keep in might you  might run into problems with snaps and maybe even macos with this approach). The people of keypass seem to have successfully implemented that, though I wasn't able to find the relevant code in their repo yet.
2. Generating an access code in the system browser and require the user to manually copy it into the app to get an access token
3. Trying to convince google that you're in a regular browser (which is discouraged by google). 

This might be helpful:
https://developers.google.com/identity/protocols/oauth2/native-app

If you come up with a working solution, please let us know and share the code!! :)

**Comment by AwesomestCode** [comment]
Has anyone figured out how Google detects this?

**Comment by nornagon** [comment]
Closing this as it doesn't represent anything we can change about Electron. Feel free to continue discussion here, though.
