### ISSUE TITLE
Documentation is confusing/hard to navigate for new users

### ISSUE THREAD

**Issue by kevinschaich** [electron/electron#17884]
The [docs page](https://electronjs.org/docs) for Electron is seriously overwhelming and unhelpful if you're a new Electron user like myself.

If I have no prior knowledge of Electron, how would I know which page to start on between **About Electron**, **Writing Your First Electron App**, **Installation**, **Quick Start**, and others among the Guides section? I suggest we be intentional about what users see first.

I think many popular frameworks solve this problem with a hierarchy sidebar. It usually starts with a single **Getting Started** tutorial, works its way into more complex guides that most users will find themselves needing eventually, and then gets into the nitty gritty like  API docs.

I'd consider the following for some well-executed examples:

* https://reactjs.org/docs/getting-started.html
* https://vuejs.org/v2/guide/
* https://nextjs.org/docs
* https://code.visualstudio.com/docs

**Comment by jdfwarrior** [comment]
I'd agree on this but, @kevinschaich, this would probably be a good place for someone (maybe even you) to jump in and improve the docs and submit a pull request.

I personally wish each page had a side navigation that would jump to certain sections at bare minimum. By that I mean, if I go to a page, at bare minimum I wish there was a way to jump to "Instance Methods", "Events", "Static Methods", "Examples", etc. I just haven't had the time to work on it.

**Comment by eplank18** [comment]
https://github.com/electron/electron/pull/18023
Tried to write a cliff's notes file that explains what Electron is in more specific terms(since hi, new user, was incredibly confused too), and suggests a path of docs files to go through to write a first app and then get a good foundation of coding on Electron. Hopefully it's a start!

**Comment by nornagon** [comment]
This is an ongoing task that @electron/wg-ecosystem is working on through a variety of methods. I don't think this issue is usefully tracking that work, so I'm closing it.
