### ISSUE TITLE
It's impossible to blur a webview to focus embedder frame using js vanilla API

### ISSUE THREAD

**Issue by maxerbox** [electron/electron#17882]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.1.4
* **Operating System:**
  * Debian Stretch 9.8 x64 Gnome

### Expected Behavior
The javascript code executed in the embedder frame (and not in the webview):
```js 
require('electron').remote.getCurrentWebContents().focus()
``` 
 should focus the embedder frame

The javascript code executed in the embedder frame:
```js
webview.blur()
```
should blur the webview and focus the embedder frame

The javascript code executed in the embedder frame:
```js
window.focus()
```
should focus the embedder frame.

### Actual Behavior
When a webview is focused, it's impossible to focus back the embedder frame.

### To Reproduce

```sh
$ git clone https://github.com/maxerbox/electron-quick-start -b bug-focus-webview
$ npm install
$ npm start || electron .
```

### Screenshots

![image](https://user-images.githubusercontent.com/12765875/56441220-a9acf880-62ec-11e9-8159-da6142aa2ac8.png)
Output of the bug-focus-webview branch

```js
require('electron').remote.getCurrentWebContents().focus()
e.target.blur()
window.focus()
alert(document.hasFocus())
```
The code of the branch

**Comment by krisdages** [comment]
I've encountered the same issue. I did find a workaround for it that may help in the meantime.
```
//Focus the iframe inside the webview; Focusing the webview element itself does not work.
//The iframe is the last child of the shadow root as of Electron 4.0, but this could change.
const children = webview.shadowRoot.children;
for (let i = children.length - 1; i >= 0; i--) {
	const child = children[i];
	if (child.tagName === "IFRAME") {
		child.focus();
		return;
	}
}
```

**Comment by maxerbox** [comment]
By the way, it seems that https://github.com/electron/electron/commit/edf2e84895720cc4b6e0d39e01696b50df78e580 allowed to blur webview.
I renamed the issue

**Comment by maxerbox** [comment]
@sofianguy 

# Bug confirmed in: 
On debian:

Confirmed 5.0.0
![image](https://user-images.githubusercontent.com/12765875/57156453-4e93ff00-6dde-11e9-906e-ab3cac76a827.png)

Confirmed 6.0.0-beta1
![image](https://user-images.githubusercontent.com/12765875/57156827-3f618100-6ddf-11e9-8071-d866715ab2a2.png)

Confirmed 3.1.9
![image](https://user-images.githubusercontent.com/12765875/57156934-99fadd00-6ddf-11e9-9b7d-12b47ce29562.png)

# It was working in 2.X

![image](https://user-images.githubusercontent.com/12765875/57157132-1c839c80-6de0-11e9-9735-bf54276042f0.png)

**Comment by tassoevan** [comment]
Related to #14631?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
