### ISSUE TITLE
Ability to hide the OS's native cursor

### ISSUE THREAD

**Issue by mitrousis** [electron/electron#17889]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

We use Electron for digital signage applications that have no user interaction or mice attached. When these applications run, the mouse cursor will linger in the corner of the screen. While we can use css to hide the mouse cursor, it requires focus/interaction in the BrowserWindow to be effective (which is expected, given that it is browser-based).

### Proposed Solution

 I'd like a way to _natively_ show/hide the OS cursor, similar to the functionality in Unity and other full-screen content creation tools. The scope of the cursor visibility would be limited to the Electron app (not necessarily hiding the OS cursor everywhere).

### Alternatives Considered

Currently, we use 3rd party utilities to auto-hide the cursor, but it is quite clumsy.

**Comment by MarshallOfSound** [comment]
@mitrousis I believe you are looking for this --> 

https://developer.mozilla.org/en-US/docs/Web/API/Pointer_Lock_API

> It gives you access to raw mouse movement, locks the target of mouse events to a single element, eliminates limits on how far mouse movement can go in a single direction, and removes the cursor from view.

**Comment by mitrousis** [comment]
Thanks for the quick response! Will give your solution a test.
