### ISSUE TITLE
App freeze when iframe is deleted from a webview

### ISSUE THREAD

**Issue by pwnsdx** [electron/electron#17890]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.0-beta.9
* **Operating System:**
  * macOS Mojave
* **Last Known Working Electron version:**:
  * 4.1.4

### Expected Behavior

The iframe is removed without causing any issue

### Actual Behavior

The webview content will freeze (the gif will stop working) once the iframe is removed from it and in some cases, you will be unable to close the app.

### To Reproduce

Run the following Electron Fiddle: https://gist.github.com/ae270063bc98401e6f6cbfeb1fddfa5d

It will remove the iframe after 6 seconds. The gif should then freeze on the latest beta (9) and in some cases, closing the app is impossible unless force exiting.

### Additional Information

After further testing, I noticed that if the iframe is restored then the app start acting normally again.

**Comment by r0stig** [comment]
Able to reproduce in 5.0.1

**Comment by codebytere** [comment]
@r0stig @pwnsdx yeah, i'd imagine there's some issue where the OOPIF is not properly reconnected when the renderer process restarts. I'll try to poke at this soon.

**Comment by sofianguy** [comment]
fixed https://github.com/electron/electron/pull/18976
