### ISSUE TITLE
bug bug

### ISSUE THREAD

**Issue by UoToGK** [electron/electron#17910]
Electron Version:
Using Electron 1.3.1 on Windows 7. In my index.html I Create and Closed Webview, Memory Increase in electron.exe , i set emitter.setMaxListeners() is 0. I wonder if the webview needs to have a destroyed method to free memory.
Expected Behavior
Memory increases first and then decreases, in a dynamic equilibrium position

Actual Behavior
Memory Increase always,last out of memory

To Reproduce
this is my script in my index.html;
setInterval(() => {
let webview = document.createElement("webview");
document.body.appendChild(webview);
document.body.removeChild(webview);
webview=null;//it's no use doing that;
}, 100);

so who can tell me what's the matter on here?

It should be that the memory of the main process keeps increasing.

Why can't this destroy WebView

**Comment by MarshallOfSound** [comment]
> Using Electron 1.3.1

This version of Electron is no longer supported, please upgrade to the latest supported version of Electron (4 or 5)

**Comment by UoToGK** [comment]
But I still have the same problem with version 4.0.0.
