### ISSUE TITLE
ELectron Application crashes (shows whitescreen) when calling nativeImage.createFromPath API for .png file

### ISSUE THREAD

**Issue by mukeshthe93** [electron/electron#17912]
The Electron application crashes 

### Issue Details

* **Electron Version:**
  * ElectronVersion: 3.0.7  
  * NodeVersion-10.2.0   
  * ChromeVersion:66.0.3359.181
* **Operating System:**
  * Windows 10

### Actual Behavior
*When I am calling "nativeImage.createFromPath(**imagepath**)"  API and passing the below image path to reading the image and show on UI But It crashes on this API call and shows white screen. This is happening only with the attached image. If I am passing any other image (.png/jpeg) it is working. I am not able to figure it out what is special in this image.

![close_img](https://user-images.githubusercontent.com/14362375/56563119-88882880-65c8-11e9-82ff-97aff40b262c.png)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

**Comment by mukeshthe93** [comment]
I have forked [electron-quick-start](https://github.com/mukeshthe93/electron-quick-start) and modify the main.js file to reproduce this issue. I have done a small change to call "nativeImage.createFromPath(imagepath)" API. 

To reproduce the issue,you have yo call "npm start" command and check the console log. The application is crashing because of the "image1.toDataURL()" value is empty.

Could you suggest me why the "nativeImage.createFromPath()" returns null (ignoring the mimetype)?

**Comment by mukeshthe93** [comment]
Hi, 
Thanks for your reply. The Sample application is available at below location and to reproduce the issue follow the below steps.
[https://github.com/mukeshthe93/electron-quick-start]

# reproduction steps:

```
> Clone this repository
git clone https://github.com/electron/electron-quick-start
> Go into the repository
cd electron-quick-start
> Install dependencies
npm install
> Run the app
npm start
```

Check the console log, The Image1 dataurl is empty.
Kindly let me know if you need more information.

**Comment by codebytere** [comment]
It appears that this issue is resultant of the image being used in the repro and not a function of Electron or something that we're currently capable of fixing. If this occurs on other images, we're more than happy to investigate further!
