### ISSUE TITLE
Memory leak when creating and destroying <webview>s

### ISSUE THREAD

**Issue by UoToGK** [electron/electron#17911]
Electron Version:
Using Electron 4.0.0 on Windows 7. In my index.html I Create and Closed Webview, Memory Increase in electron.exe , i set emitter.setMaxListeners() is 0. I wonder if the webview needs to have a destroyed method to free memory.
Expected Behavior
Memory increases first and then decreases, in a dynamic equilibrium position

Actual Behavior
Memory Increase always,last out of memory

To Reproduce
this is my script in my index.html;
setInterval(() => {
let webview = document.createElement("webview");
document.body.appendChild(webview);
document.body.removeChild(webview);
webview=null;//it's no use doing that;
}, 100);

so who can tell me what's the matter on here?

It should be that the memory of the main process keeps increasing.

Why can't this destroy WebView

**Comment by codebytere** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by Nick-lab** [comment]
```
let webview = document.createElement("webview");
document.body.appendChild(webview);
document.body.removeChild(webview); // only removes webview from dom
webview=null; // does not destroy webview
```

**Comment by UoToGK** [comment]
why?That's what I did before, but memory is still increasing.

**Comment by UoToGK** [comment]
this is my script in index.html
```js
var srcArr = [
      "http://www.google.com/",
      "http://www.facebook.com/",
      "https://www.amazon.cn/"
    ];
    var id = new Date().valueOf();
    var div = document.createElement("div");
    document.body.appendChild(div);
    function createWebview(src) {
      var webview = document.createElement("webview");
      webview.id = id;
      webview.src = src || "about:blank";
      webview.classList.add("webview-test");
      div.appendChild(webview);
    }
    setInterval(() => {
      srcArr.forEach(src => {
        createWebview(src);
      });
    }, 5000);
    setInterval(clearWebview, 6000);
    function clearWebview() {
      var arr = document.querySelectorAll("webview");
      arr.forEach(el => {
        div.removeChild(el);
      });
    }
```
After a period of execution, you can find that the application process continues to increase in Windows Task Manager

**Comment by UoToGK** [comment]
![image](https://user-images.githubusercontent.com/32165193/56935988-4a8a8780-6b27-11e9-96c5-b0850b546993.png)

**Comment by UoToGK** [comment]
* Electron version: 5.0.0
* Operating system: windows server 2012R2

### Expected behavior
Memory increases first and then decreases, in a dynamic equilibrium position


### Actual behavior

After a period of execution, you can find that the application process continues to increase in Windows Task Manager

### How to reproduce
index.js
```js
const { app, BrowserWindow } = require("electron");
app.commandLine.appendSwitch("ignore-certificate-errors");
app.commandLine.appendSwitch("disable-http-cache");
app.commandLine.appendSwitch("disk-cache-size", 0);
app.commandLine.appendArgument("--disk-cache-size=0");

app.on("window-all-closed", function() {
  app.quit();
});

let NO_QUIT = false;

app.on("ready", createWindow);

function createWindow() {
  let window = new BrowserWindow({
    width: 1900,
    height: 1000,
    minWidth: 1000,
    minHeight: 600,

    frame: false,
    webPreferences: {
      plugins: true
    }
  });
  window.loadURL("file://" + __dirname + "/index.html");
  window.webContents.openDevTools();
  let session = window.webContents.session;

  session.on("will-download", function(event, downloadItem) {
    event.preventDefault();
  });

  window.on("closed", function() {
    if (!NO_QUIT) {
      window = null;
      app.quit();
    }
  });

  return window;
}

```
```index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>webview test</title>
  </head>
  <style>
    .webview-test {
      height: 500px;
      width: 500px;
      border: 1px solid red;
    }
  </style>
  <body>
    <h1>This is Webview Test !</h1>
  </body>
  <script>
    var srcArr = [
      "https://blog.csdn.net/chenzhigaoa/article/details/80782290",
      "https://www.cnblogs.com/zhuxinghan/p/6031678.html",
      "https://blog.csdn.net/qq_32451373/article/details/84023371",
      "https://echarts.baidu.com/tutorial.html#5%20%E5%88%86%E9%92%9F%E4%B8%8A%E6%89%8B%20ECharts",
      "https://cloud.tencent.com/developer/ask/78561",
      "https://segmentfault.com/p/1210000008832836/read",
      "https://blog.csdn.net/ywl570717586/article/details/78551319",
      "https://jbk.99.com.cn/keshi/neike.html",
      "https://jbk.99.com.cn/xiaochuan/bingfazheng.html"
    ];

    var id = new Date().valueOf();
    var div = document.createElement("div");
    document.body.appendChild(div);
    function createWebview(src) {
      var webview = document.createElement("webview");
      webview.id = id;
      webview.src = src || "about:blank";
      webview.classList.add("webview-test");
      div.appendChild(webview);
    }
    setInterval(() => {
      srcArr.forEach(src => {
        createWebview(src);
      });
    }, 5000);
    setInterval(clearWebview, 6000);
    function clearWebview() {
      var arr = document.querySelectorAll("webview");
      arr.forEach(el => {
        div.removeChild(el);
      });
    }
  </script>
</html>

```
(screenshot)[https://user-images.githubusercontent.com/32165193/56935988-4a8a8780-6b27-11e9-96c5-b0850b546993.png]

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by UoToGK** [comment]
The latest version also has this problem

**Comment by UoToGK** [comment]
webview没有被销毁，仅仅是从dom移除了

**Comment by UoToGK** [comment]
The webview is not destroyed, just removed from the dom

**Comment by UoToGK** [comment]
You can run my script on your computer and then view your task manager@ electron-triage@sofianguy
