### ISSUE TITLE
desktopCapturer.getSources with 'screen' causes binocular icon on lock screen

### ISSUE THREAD

**Issue by acbuitrago** [electron/electron#17937]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.1.3
* **Operating System:**
  * macOS 10.14.4
* **Last Known Working Electron version:**:
  * None.

### Expected Behavior
A call to `desktopCapturer.getSources( { types: [ 'screen'] })` should not cause the OS to show the binoculars icon when the user locks the screen, this icon should only be shown when the screen is being recorded. 

As far as I know this icon is used to show that the user is recording a screen. [Here](https://macreports.com/binoculars-icon-on-mac-what-does-that-mean/) is explained this icon.

### Actual Behavior
Calling `desktopCapturer.getSources( { types: [ 'screen'] })` causes the binoculars icon to be shown to the user when he locks the PC, even when the screen is not being recorded in any other way. The icon isn't shown when the PC is unlocked, only when the PC is locked, until the users closes the electron app that made the call.

This doesn't happen when `desktopCapturer.getSources({ types: 'window' })` is called. 

### To Reproduce
Clone this repository

```
git clone https://github.com/electron/electron-quick-start
npm install
npm start
```
Then, in the `renderer.js` file, put:
```
const { desktopCapturer } = require('electron');

desktopCapturer.getSources( { types: [ 'screen'] }, (error, sources) => {
    if (error) throw error
    for (let i = 0; i < sources.length; ++i) {
      console.log('source: ' + sources[i].name); 
    }
});
```
Finally, while keeping the app opened, lock your screen and you will notice on the login screen the binoculars icon, even though there aren't any apps recording the screen. This icon will be seen on your lock screen as long as you have the electron app opened.  

### Screenshots

<img width="1412" alt="Screen Shot 2019-04-23 at 18 01 18" src="https://user-images.githubusercontent.com/4340899/56621413-fac13300-65f1-11e9-8d8d-a27a53c3e8af.png">

**Comment by loc** [comment]
Can confirm that this regressed between 3.1.11 and 4.0.0-beta.1.

**Comment by nornagon** [comment]
Looks like this is also happening in 6.0.0-beta.6

**Comment by lingxf2002** [comment]
It is happening in 6.0.5 as well
