### ISSUE TITLE
OpenQA.Selenium.WebDriverException: 'DevToolsActivePort file doesn't exist'

### ISSUE THREAD

**Issue by rameshrc** [electron/electron#17936]
var options = new ChromeOptions();
            options.BinaryLocation = @"C:\XXX.exe";
            //options.AddArguments("--disable-background-networking --disable-client-side-phishing-detection --disable-default-apps --disable-dev-shm-usage --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --disable-web-resources --enable-automation --enable-logging --force-fieldtrials=SiteIsolationExtensions/Control --headless --ignore-certificate-errors --load-extension=/var/folders/zs/ppz21q1s40lb9xq14fgfqjgxk070r_/T/.org.chromium.Chromium.FnU5b9/internal --log-level=0 --metrics-recording-only --no-first-run --no-sandbox --password-store=basic --remote-debugging-port=0 --test-type=webdriver --use-mock-keychain --user-data-dir=/var/folders/zs/ppz21q1s40lb9xq14fgfqjgxk070r_/T/.org.chromium.Chromium.KR6kt");
            var service =  ChromeDriverService.CreateDefaultService();
            
            var driver = new ChromeDriver(service, options, TimeSpan.FromSeconds(100));

Selenium latest versions 3.14
Chrome driver from electron 5.09 beta release

**Comment by rameshrc** [comment]
OpenQA.Selenium.WebDriverException: 'Chrome failed to start: exited normally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Users\10135431\Downloads\ElectronAPIDemosSetup.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)'

**Comment by rameshrc** [comment]
OpenQA.Selenium.WebDriverException: 'Chrome failed to start: exited normally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Users\XXX\Downloads\ElectronAPIDemosSetup.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)'

**Comment by rameshrc** [comment]
code is pasted in the request

Faulting application name: ElectronAPIDemosSetup.exe, version: 2.0.2.0, time stamp: 0x5b988f2e
Faulting module name: ElectronAPIDemosSetup.exe, version: 2.0.2.0, time stamp: 0x5b988f2e
Exception code: 0xc0000409
Fault offset: 0x0000d59a
Faulting process id: 0x2c60
Faulting application start time: 0x01d4fa39a685c28e
Faulting application path: C:\Users\XXX\Downloads\ElectronAPIDemosSetup.exe
Faulting module path: C:\Users\XXX\Downloads\ElectronAPIDemosSetup.exe
Report Id: adaab51a-5c8d-4ba0-8b7a-089714659174
Faulting package full name: 
Faulting package-relative application ID:

I can launch manually that Electron demo exe and no issues, but issues with chrome driver
I use C# selenium bindings

**Comment by rameshrc** [comment]
Even with new packages
PACKAGES:

  <package id="Selenium.Support" version="4.0.0-alpha01" targetFramework="net472" />
  <package id="Selenium.WebDriver" version="4.0.0-alpha01" targetFramework="net472" />
  <package id="Selenium.WebDriver.ChromeDriver" version="74.0.3729.6-beta" targetFramework="net472" />

Even tried electron released 5.0.9 beta release with chrome driver, same issues.

**Comment by rameshrc** [comment]
PACKAGES:

  <package id="Selenium.Support" version="4.0.0-alpha01" targetFramework="net472" />
  <package id="Selenium.WebDriver" version="4.0.0-alpha01" targetFramework="net472" />
  <package id="Selenium.WebDriver.ChromeDriver" version="74.0.3729.6-beta" targetFramework="net472" />


Even tried electron released 5.0.9 beta release with chrome driver, same issues.

**Comment by rameshrc** [comment]
PACKAGES:

  < package id="Selenium.Support" version="4.0.0-alpha01" targetFramework="net472" />
  < package id="Selenium.WebDriver" version="4.0.0-alpha01" targetFramework="net472" />
  < package id="Selenium.WebDriver.ChromeDriver" version="74.0.3729.6-beta" targetFramework="net472" />


Even tried electron released 5.0.9 beta release with chrome driver, same issues.

**Comment by hunterchristian** [comment]
I'm experiencing the same issue. Would there happen to be any updates?

**Comment by helloCx** [comment]
problem solved? i'get the same one.

**Comment by bharathmuppa** [comment]
Hi Guys, Is there any solution to it ?

**Comment by PrathapKumar123** [comment]
@rameshrc Did you get solution for this? I am stuck at same point

**Comment by PrathapKumar123** [comment]
> problem solved? i'get the same one.

Got any solution?

**Comment by rameshrc** [comment]
no, i don't have solution. yet investigating it

**Comment by 734417902** [comment]
hey bros , is there any solutions now?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
