### ISSUE TITLE
Menu selection does always not count as user gesture

### ISSUE THREAD

**Issue by daumling** [electron/electron#17943]
### Preflight Checklist

* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  5.0.0-beta9
* **Operating System:** 
  * Mac OS 10.14.4
* **Last Known Working Electron version:**:
  * none  yet

### Expected Behavior
When selecting a menu item, this should always count as a user gesture.

### Actual Behavior
I am using Bluetooth.selectDevice() with Electron 5.0.0-beta9 and Mac OS 10.14.4 following a menu item selection, displaying a homebrew dialog. Sometimes, it works the first time, but subsequent selects always end up in an error saying that the action was not initiated by a user gesture. Not tested on other platforms.

The error message is: DOMException: Must be handling a user gesture to show a permission request

Tested with Electron 1.7.4: Even a confirm  box (a Bootstrap dialog) does not count as a user gesture. Works with Electron 5.0.0-beta9.

### To Reproduce
Difficult; I can provide an executable if needed.

**Comment by daumling** [comment]
Electron Version: 5.0.0-beta9 (does not work with Electron 1.8 either)
Operating System: Mac OS 10.14.4

**Comment by daumling** [comment]
Tried on both Mac OS and Windows with Electron 5.0.6 - same problem. I suspect this is because the click gesture goes to the main process, and the renderer process's MenuItem.click() handler is executed via a messaging interface.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by daumling** [comment]
Not worth the investigation.
