### ISSUE TITLE
Transparent macOS Windows has weird border on top side

### ISSUE THREAD

**Issue by 0neGuyDev** [electron/electron#17944]
I do not know why but when i tried to create transparent windows on macOS (Mojave) but it still had a top border, so is there a way to remove it?

**See the image as example!**
<img width="884" alt="Screenshot 2019-04-24 at 13 08 54" src="https://user-images.githubusercontent.com/33325154/56655175-58a55780-6692-11e9-91af-fac237128714.png">

*Thanks!*

**Comment by jdfwarrior** [comment]
@0neGuyDev Not sure this has to do with a transparent window. I've noticed the same thing on a frameless window on macOS. So, I think it has more to do with the titlebar or the lack of the window frame. I had a window with no frame and a custom titlebar and noticed that it had that line at the top as well. It doesn't show on Windows. I haven't tested this with the latest Electron (5+ beta) yet though. I know for certain that it's present in 4.0.1

**Comment by 0neGuyDev** [comment]
I expected it to be a thing that is there on normal windows and for some reason electron isn't removing it when making the window transparent...

**Comment by orangeChu** [comment]
@ckerr It seems to be associated with #13164.

**Comment by 0neGuyDev** [comment]
Yes It is the same thing :)
I couldn’t find anything similar when looking in issues to i thought nobody else had the problem and made a new issue...

Although I’ll close this off and #13164 figures it out or come with a good explanation!
