### ISSUE TITLE
v5.0.0: white flicker during Mission Control transitions and workspace transitions

### ISSUE THREAD

**Issue by zp1996** [electron/electron#17942]
### Issue Details

* **Electron Version:**
  * all beta versions in 5.0.x
* **Operating System:**
  * macOS 10.13 and 10.14
* **Last Known Working Electron version:**
  * 4.1.4

### Expected Behavior
During Mission Control transitions or workspace transitions, the window should not flicker. See the right window in the screenshot
### Actual Behavior
During Mission Control transitions or workspace transitions, the whole window flickers white. See the left window in the screenshot

### Screenshots
left version is 5.0.0-beta.9, right version is 4.1.4
![image](https://user-images.githubusercontent.com/14966444/56644236-e3e01680-66ad-11e9-8fff-813bfb1a708e.png)

see more in [this video](https://youtu.be/1ERkxTIKk6E)

**Comment by GhostlyDark** [comment]
I noticed a flashing issue with v5.x as well. 
When Electron is used like a browser, loading a different page has a chance of it flashing. This happens for extremely fast loading local pages as well.
Setting the background-color of the window to `#000` might make it easier to tolerate.

Electron v4.x never flashes.
Windows 10 x64

**Comment by zp1996** [comment]
Pelase cc@zcbenz, thx

**Comment by zp1996** [comment]
```
app.commandLine.appendSwitch('disable-backgrounding-occluded-windows', 'true')
```
this can resolve the problem

**Comment by PalmerAL** [comment]
I believe I'm having the same problem, @zp1996 thanks for the suggestion! I'll have to try that.

Another interesting thing about this is that the duration of the white flash seems to depend on how long the app was left in the background. If I switch away from the app and then immediately switch back, there's a barely noticable flicker, but if I leave it in the background for a few hours, it will freeze on the white screen for 10-15 seconds until the app appears again.

**Comment by jeremyspiegel** [comment]
I also see this when the machine wakes from sleep on macOS, and it is fixed by the `disable-backgrounding-occluded-windows` workaround.

**Comment by jeremyspiegel** [comment]
Unfortunately the workaround results in higher CPU usage and energy impact as reported by Activity Monitor when the app is minimized than when not using the workaround.

**Comment by PalmerAL** [comment]
@jeremyspiegel The CPU usage of a blank window doesn't seem to be too high (at least in my case), so if your app code is doing anything in the background, you could try using the browserwindow `blur` and `focus` events to pause background tasks. Or if you have CSS animations running, that could potentially be the source of CPU usage as well.

**Comment by jeremyspiegel** [comment]
Thanks @PalmerAL, I am seeing higher CPU usage since updating to Electron 5, though not on the blank electron-quick-start app, so will look closer into why that's happening in my app.
