### ISSUE TITLE
Breaking 5.0 change: `process` is undefined when using `browserWindow.loadURL(url)`

### ISSUE THREAD

**Issue by OiYouYeahYou** [electron/electron#17967]
### Issue Details

* **Electron Version:** 5.0.0
* **Operating System:** Ubuntu 18.10 (Cosmic Cuttlefish)
* **Last Known Working Electron version:**: ^3 and ^4

### Expected Behavior
`process` to be defined inside browser window

### Actual Behavior
`process` is undefined inside browser window

### To Reproduce
`app.html`
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <script>console.log(process)</script>
</body>

</html>
```

`main.js`
```js
const { app, BrowserWindow } = require('electron')

app.on('ready', () =>
    Promise.resolve().then(() => {
        let mainWindow = new BrowserWindow({
            contextIsolation: false,
            nodeIntegration: true,
            webviewTag: true,
        })

        mainWindow.loadURL(`file://${__dirname}/app.html`)

        mainWindow.on('closed', () => (mainWindow = null))
    })
)
```

`package.json`
```json
{
  "name": "elec-break-5",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "electron": "^5.0.0"
  }
}
```

### Screenshots

![image](https://user-images.githubusercontent.com/20130059/56754658-80291c80-6785-11e9-8a6e-666f0aa0c402.png)

### Additional Information
This is working in v^3 and v^4, but causes issues in v5. Nor have there been any depreciation warnings in v4 and nothing is referenced in [breaking changes](https://github.com/electron/electron/blob/master/docs/api/breaking-changes.md#planned-breaking-api-changes-50)

**Comment by kwonoj** [comment]
breaking changes explains `nodeIntegration` set to false which is for this case, isn't it?

**Comment by OiYouYeahYou** [comment]
@kwonoj I believe the webPreferences are to their pre-v5 defaults in the main.js?

```js
let mainWindow = new BrowserWindow({
  contextIsolation: false,
  nodeIntegration: true,
  webviewTag: true,
})
```

**Comment by kwonoj** [comment]
I'm on v4 currently and it is under `webPreferences`. which fits with v4's documentation as well. https://github.com/electron/electron/blob/v4.1.5/docs/api/browser-window.md

**Comment by OiYouYeahYou** [comment]
Ok, SO, the actual fix is as follows

```js
let mainWindow = new BrowserWindow({
	webPreferences: {
		nodeIntegration: true,
	},
})
```

Could the breaking docs be a little clearer? Like including code example like previous versions?
