### ISSUE TITLE
Cannot close popup windows (for certain websites)

### ISSUE THREAD

**Issue by ronny1982** [electron/electron#17962]
In some cases popup windows that are opened through a hyperlink in the render process cannot be closed. The following example link will produce such an popup that cannot be closed:

```html
<a href="https://bit.ly/2Gyxcdn" target="_blank">
    Popup Window cannot be closed
</a>
```

**Steps to reproduce:**
1. Make sure electron is installed (any version shall do)
2. Download and extract the [attached](https://github.com/electron/electron/files/3115687/app.zip) sample files into a directory 
3. Open a terminal and change into the directory
4. Run electron within the directory `electron .`
5. Click on the first link, wait until the new window is open and loaded, close the window
=> works as expected
6. Click on the second link, wait until the window is open and loaded, close the window
=> window cannot be closed

**Comment by MarshallOfSound** [comment]
This is currently expected behavior.

Refs: https://github.com/electron/electron/blob/master/docs/api/browser-window.md#event-close

> In Electron, returning any value other than undefined would cancel the close.

This is slightly different to common web behavior

**Comment by MarshallOfSound** [comment]
Refs: https://github.com/electron/electron/issues/8737
