### ISSUE TITLE
Problem with "will-download"

### ISSUE THREAD

**Issue by Atlass75** [electron/electron#17982]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.
---
### Issue Details

* **Electron Version:**
  * 5.0.0
* **Operating System:**
  * Windows 10 (17763)
---
### Expected Behavior
I would like to include a progress bar that indicates the progress of the file download
---
### Screenshots
> The progress bar does not move forward and does not display the percentage
![Progress bar](http://image.noelshack.com/fichiers/2019/18/1/1556513087-sans-titre.png)

>The error message says "The file is empty!"
![Error message](http://image.noelshack.com/fichiers/2019/18/1/1556513583-sans-titre.png)
---
### Actual Behavior

I retrieved this code from [this post](https://stackoverflow.com/questions/45979518/progress-bar-when-file-download-in-electron-application-using-node-js/46440590#46440590) but, when i use this code i have this error

`Attempting to call a function in a renderer window that has been closed or released.
Function provided here: :127:28`

At the line 127 : `session.defaultSession.on('will-download', function (event, downloadItem, webContents) {`

When the download starts it displays the error message that the file is empty but my file is not empty

And the progress bar shows 0% while the file is downloading

---
In EJS file

```javascript
function sendURL(URL, format) {
	let tile = "<%= title %>"
	tit = tile.replace(/[`~!@#$^&'",.<>\{\}\[\]\\\/]/gi, '')
	window.location.href = `/download?URL=${URL}&title=${tit}&format=${format}`
}

[... More code ...]

const {session} = require('electron').remote

session.defaultSession.on('will-download', function (event, downloadItem, webContents) {
	"use strict";

	if (downloadItem.getTotalBytes() === 0) {
		swal({
			position: 'center',
			type: 'error',
			title: 'Fichier vide !',
			showConfirmButton: true,
			icon: "warning"
		})
	}

	downloadItem.on('updated', function (event, state) {
	process.stdout.write(downloadItem.getTotalBytes())
		if (state === 'interrupted') {
			swal({
				position: 'center',
				type: 'error',
				title: 'Téléchargement interrompu',
				showConfirmButton: true,
				icon: "info",
			})
		} else if (state === 'progressing') {
			let jQueryprogress = $(".progress")
			let jQuerybar = $(".progress__bar")
			let jQuerytext = $(".progress__text")
			let percent = 0
			let update
			let resetColors
			let speed = 200
			let orange = 30
			let yellow = 55
			let green = 85
			let timer

			resetColors = function () {
				jQuerybar
					.removeClass("progress__bar--green")
					.removeClass("progress__bar--yellow")
					.removeClass("progress__bar--orange")
					.removeClass("progress__bar--blue")

				jQueryprogress
					.removeClass("progress--complete")

			}

			update = function () {
				timer = setTimeout(function () {
					try {
						let percentage = downloadItem.getReceivedBytes() / downloadItem.getTotalBytes()
						percent = percentage * 100
						percent = parseFloat(percent.toFixed(2))
						update()
					} catch (error) {
						clearTimeout(timer)
						percent = 100
						resetColors()
						jQueryprogress.addClass("progress--complete")
						jQuerybar.addClass("progress__bar--blue")
						jQuerytext.find("em").text("Complete")
						percent = 0
					}

					jQuerytext.find("em").text(percent + "%")

					if (downloadItem.isPaused()) jQuerytext.find("span").text('En pause')
					else jQuerytext.find("span").text(downloadItem.getFilename())

					if (percent >= green) {
						jQuerybar.addClass("progress__bar--green")
					}

					else if (percent >= yellow) {
						jQuerybar.addClass("progress__bar--yellow")
					}

					else if (percent >= orange) {
						jQuerybar.addClass("progress__bar--orange")
					}

					speed = Math.floor(Math.random() * 100)

					jQuerybar.css({ width: percent + " %" })

				}, speed)

			}

			$(".itemDL").addClass('bcenter')
			jQueryprogress.addClass("progress--active")
			update()
			resetColors()
		}

	})
	downloadItem.once('done', function (event, state) {

		console.log("Inside download done function " + event + state)

		if (state === 'completed') {
			setTimeout(function () {

				$(".itemDL").removeClass("bcenter")
				swal({
					position: 'center',
					type: 'success',
					title: 'Téléchargement terminé',
					showConfirmButton: true,
					icon: "success",
				})

			}, 50)

		} else if (state === 'cancelled' || state === "interrupted") {
			$(".itemDL").removeClass("bcenter")
			swal({
				position: 'center',
				type: 'error',
				title: 'Téléchargement annulé ou interrompu',
				showConfirmButton: true,
				icon: "error",
			})
		} else {
			$(".itemDL").removeClass("bcenter")
			swal({
				position: 'center',
				type: 'error',
				title: 'Téléchargement échoué',
				showConfirmButton: true,
				icon: "error"
			})

		}
	})

	session.defaultSession.clearStorageData([], function () { console.log(' cleared all storages after download ') })
	session.defaultSession.clearCache(function () { console.log('cleared all caches after download') })
})
```
---
In router.js

```javascript
expressApp.get('/download', async (req, res) => {
	let URL = req.query.URL
	let title = req.query.title
	let format = req.query.format

	res.header('Content-Disposition', `attachment; filename="${title}.${format}"`)

	await ytdl(URL, {
		format: format
	}).pipe(res)
})
```

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by Atlass75** [comment]
Where can I find the template ?

**Comment by MarshallOfSound** [comment]
@Atlass75 It's the thing you deleted when you made this issue (it's the prefilled template for all new issues) 😄 .

You can copy paste the original template here --> https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE/Bug_report.md

**Comment by Atlass75** [comment]
@MarshallOfSound Post edited

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
