### ISSUE TITLE
Electron 5 webview with no contextIsolation and nativeWindowOpen fails to load a preload in a popup window in the correct context

### ISSUE THREAD

**Issue by Tim91084** [electron/electron#17989]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.0
* **Operating System:**
  * Windows (didn't test anywhere else)
* **Last Known Working Electron version:**:
  * ? not sure.

### Expected Behavior
When opening a popup window from a webview with `contextIsolation=no,nativeWindowOpen=yes`, the preload script for that webview should load in the popup window in the correct context

### Actual Behavior
The preload script appears to fail to load in the correct context, causing things like fetch to fail with the following error: `TypeError: Failed to execute 'fetch' on 'Window': The global scope is shutting down.`

#### index.html
```html
<webview src="webview-test.html"
      style="height:100%; width: 100%"
      allowpopups
      preload="preload.js"
      webPreferences="contextIsolation=no,nativeWindowOpen=yes"></webview>
```
#### webview-test.html
```html
<html>
<body>
  <script>
    window.openGoogle = function () {
      window.open('https://www.google.com')
    }
  </script>
  <button onclick="openGoogle()" type="button">window.open('https://www.google.com')</button>
</body>
</html>
```

#### preload.js
```js
// window.location.href always reports about:blank in this situation for some reason
console.log('window.location.href', window.location.href)
fetch('https://www.google.com')
    .then(x => console.log('success', x.text()))
    .catch(x => console.log('error', x))
```

#### forked quick start repo with reproduction
https://github.com/Tim91084/electron-window-open-bug

### Screenshots
![image](https://user-images.githubusercontent.com/5086428/56830189-b1602600-6833-11e9-9ee5-d2440e6dd78c.png)

![image](https://user-images.githubusercontent.com/5086428/56830169-a3aaa080-6833-11e9-8cf1-7e88a4a1a6a9.png)

**Comment by hugomano** [comment]
Some exploration details: https://github.com/getstation/electron-chrome-extension/pull/47#issuecomment-487856527

**Comment by alexstrat** [comment]
Wouldn't this condition on `Opener()` be preventing the execution of renderer initialization scripts?
https://github.com/electron/electron/blob/53f6cbccbf388dd28bd8636cd452df4c1d0f4f13/atom/renderer/atom_renderer_client.cc#L76-L79

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
