### ISSUE TITLE
webview inner iframe doesn't fit

### ISSUE THREAD

**Issue by BenjaminHoegh** [electron/electron#17988]
when setting the <webview> tags width and height, the iframe it create inside itself doesn't fit the WebView size, how to change this?

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
