### ISSUE TITLE
Electron 5.0.0 - getting TS2322 error when using protocol.registerSchemesAsPrivileged()

### ISSUE THREAD

**Issue by mviens** [electron/electron#17998]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v5.0.0
* **Operating System:**
  * Windows 10 (1809)
* **Last Known Working Electron version:**:
  * 4.1.5

### Expected Behavior
The code to compile without errors.

### Actual Behavior
The code no longer compiles and has error TS2322.

### To Reproduce
According to this page ([https://github.com/electron/electron/blob/master/docs/api/protocol.md](https://github.com/electron/electron/blob/master/docs/api/protocol.md)) - search for the text `before (<= v4.x)` - the registering of schemes changed in Electron v5.  TypeScript has a compilation error while using the format shown on that page:

```
protocol.registerSchemesAsPrivileged([
  { scheme: 'scheme1', privileges: { standard: true, secure: true } },
  { scheme: 'scheme2', privileges: { standard: true, secure: true } }
])
```

### Screenshots

![image](https://user-images.githubusercontent.com/8459232/56847604-092d7a00-6892-11e9-808d-0bbac2675a9d.png)

**Comment by mviens** [comment]
After digging into the Electron code, I was able to resolve the error by doing this:
```
protocol.registerSchemesAsPrivileged([
	{scheme: 'app', privileges: {secure: true}},
])
```

**Comment by MarshallOfSound** [comment]
This is documented as a breaking change in Electron 5 in our breaking changes document

Refs: https://github.com/electron/electron/blob/master/docs/api/breaking-changes.md#privileged-schemes-registration

**Comment by mviens** [comment]
Documented, sure. Documented correctly? I do not believe it was. The solution provided at YOUR link, says to use:

```
protocol.registerSchemesAsPrivileged([
  { scheme: 'scheme1', privileges: { standard: true, secure: true } },
  { scheme: 'scheme2', privileges: { standard: true, secure: true } }
])
```
That is what does not work! Please re-read my original post, not just the title.

**Comment by MarshallOfSound** [comment]
@mviens The only way you would have gotten that TS (typescript) error is if our documentation was correct.  We auto-generate the TS definitions from our documentation which you can find here:

https://electronjs.org/docs/api/protocol#protocolregisterschemesasprivilegedcustomschemes

As far as I can see your screenshot with the TS error is not the example in our docs.  And when I run the example in our docs locally through `tsc` it compiles just fine.

```ts
protocol.registerSchemesAsPrivileged([
  { scheme: 'scheme1', privileges: { standard: true, secure: true } },
  { scheme: 'scheme2', privileges: { standard: true, secure: true } }
])
```

Your screenshot and the code you say doesn't work appear to be two different things.
