### ISSUE TITLE
SetLocale through app.commandLine.appendSwitch not working

### ISSUE THREAD

**Issue by itsUndefined** [electron/electron#17995]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.0
* **Operating System:**
  *  Windows 10 (1709)
* **Last Known Working Electron version:**
  * 4.1.5

### Expected Behavior
I expected calling `app.commandLine.appendSwitch('lang', 'el')` and then later at app ready event that calling `app.getLocale()` would return **"el"**

### Actual Behavior
Calling `app.getLocale()` returns **"en-US"** that is the system locale currently set on local machine.

### To Reproduce
Run this code in main process:

```js
var electron = require('electron');
var app = electron.app;
app.commandLine.appendSwitch('lang', 'el');

app.on('ready', function () {
  console.log(app.getLocale());
});
```

### Additional Information
Problem exists even if there is a browserWindow created before the console.log
Chromium window also uses the wrong locale.

**Comment by ivan-ensemble** [comment]
I don't know if this will help but I noticed when I do
```
app.commandLine.appendSwitch('lang', 'fr');

app.commandLine.getSwitchValue('lang');  // this will be equal to 'fr'
```

However, like @sofianguy , calling `app.getLocale()` will give me "en-US"

**Comment by lemontea888** [comment]
but connet www.google.com is
On electron 4.2.4 is normal

> I don't know if this will help but I noticed when I do
> 
> ```
> app.commandLine.appendSwitch('lang', 'fr');
> 
> app.commandLine.getSwitchValue('lang');  // this will be equal to 'fr'
> ```
> 
> So the switch is set, just the value for some reason isn't propagating to `app.getLocale()`. Like @sofianguy , calling `app.getLocale()` will give me "en-US"

But it doesn't work. When you connect to the google website (https://www.google.com/), the electron browser hangs up. When it is normal, it will display different language interfaces on electron 4.2.4.

D:\Programming\Electron4>npm ls -depth=0
electron4@0.8.8 D:\Programming\Electron4
+-- electron@4.2.4
+-- i18next@17.0.3
`-- i18next-sync-fs-backend@1.1.1

**Comment by DeerMichel** [comment]
So this is working in v4 and below, broken in v5+. I tracked it down to [this commit](https://github.com/electron/electron/pull/16334/commits/4089620729dbeba5a09e97d26c46ac35a75911a5) where the language initialization was moved to an earlier startup phase. Reverting it fixes the issue but i'm unaware of why it was done in the first place and possible side-effects.

Therefore cc'ing @deepak1556 & @nornagon on how to proceed?

**Comment by nornagon** [comment]
I don't remember the reasoning for that move, perhaps @deepak1556 does?

**Comment by deepak1556** [comment]
It was done because the service manager expected the resource bundle to be initialized early https://bugs.chromium.org/p/chromium/issues/detail?id=729596 , we were following suite of how chrome did its locale initialization https://chromium-review.googlesource.com/c/chromium/src/+/1292516.

**Comment by itsUndefined** [comment]
Any update on possible solutions? Maybe update the documentation that the feature of setting the locale through the main process is no longer existing?

**Comment by lemontea888** [comment]
Perhaps since the Chrome 74 version, i18n has to turn to Intl.locale?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Locale
electron 6.0.4
~~
main.js
console.log(Intl);
~~
is
~~{}~~

node 12 doc
https://nodejs.org/api/intl.html#intl_detecting_internationalization_support
~~
[Options for building Node.js]
--with-intl=none/--without-intl
--with-intl=system-icu
--with-intl=small-icu (default)
--with-intl=full-icu
~~
should use full-icu for compile electron and use Intl.locale to i18n?

**Comment by itsUndefined** [comment]
Any update on this? If it's not feasible to set locale maybe remove it from documentation?

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by DerpDays** [comment]
This issue still exists in electron v8.2.0

**Comment by Tianruo** [comment]
```
app.relaunch({ args: process.argv.slice(1).concat(['--lang=en-US']) })
app.quit()
```

but it only work when you want to relaunch you app😔

**Comment by iwiedenm** [comment]
This is not working in `8.3.0` can this be reopened?

**Comment by FrankWangZY** [comment]
This is not working in 9.1.1 as well, please reopen it and give some help

**Comment by FrankWangZY** [comment]
This is not working in 9.1.1 as well, please reopen it and give some help

**Comment by debelop13** [comment]
Same problem with 10.1.2

**Comment by Rajesh2015** [comment]
Any one find any way I see below code works but nnext time app launches it gets defaulted to locale How can I set to different locale when next time app starts is there any way I can maniplulate the process.argv 
app.relaunch({ args: process.argv.slice(1).concat(['--lang=en-US']) })
app.quit()

**Comment by pushkin-** [comment]
is this fixed by [this PR](https://github.com/electron/electron/pull/26185)?

**Comment by antoine-souesme-needone** [comment]
Still not working on 11.2.0

**Comment by RobotoSkunk** [comment]
Version 38.1.0 and still not working, or do someone has a workaround for this?
