### ISSUE TITLE
Quitting while attached (--inspect or --inspect-brk) causes crash

### ISSUE THREAD

**Issue by kpes** [electron/electron#17996]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.0
* **Operating System:**
  * macOS 10.14.4
* **Last Known Working Electron version:**:
  * 4.1.4

### Expected Behavior
Quitting while a debugger is attached to the process results in the application exiting without error.

### Actual Behavior
Qutting while a debugger is still attached results in the application crashing and macOS showing its crash report dialog.

### To Reproduce

1. Run electron with `--inspect=9229` or `--inspect-brk=9229`.
2. Attach with a debugger (such as Visual Studio Code).
3. Quit electron without detaching.

Below is a repo that reproduces the issue:
[Repo that reproduces the issue](https://github.com/kpes/electron5attachquitcrash)

```sh
$ git clone https://github.com/kpes/electron5attachquitcrash.git
$ npm install
```

**Comment by btzsoft** [comment]
I have the same situation, it took me a lot of time and didn't found any solutions.
