### ISSUE TITLE
SVG as background-image not rendered anymore in v5.0.0

### ISSUE THREAD

**Issue by chrilith** [electron/electron#17997]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  5.0.0 (all betas and initial release)
* **Operating System:**
MacOS 10.14.3 (not tested under Windows or Linux)
* **Last Known Working Electron version:**:
4.1.5

### Expected Behavior
Inline CSS SVG image should render when used as `background-image`.

### Actual Behavior
SVG doesn't show.

### To Reproduce
Using https://github.com/chrilith/electron-quick-start/tree/svg-rendering-problem:
SVG in `background-image` doesn't render anymore with electron v5. In this exemple the grid doesn't show in the red square. Changing to v4.1.5 will show the expected SVG grid.

### Screenshots

<img width="405" alt="image" src="https://user-images.githubusercontent.com/1277891/56847048-b1653200-68d6-11e9-9b9b-05b2620747b6.png">

### Additional Information
None.

**Comment by chrilith** [comment]
OK, some more info. If I use a smaller code like this one, it works:
```css
background-image: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="8" height="8"><rect x="0" y="0" width="4" height="4" style="fill:rgba(0,0,0,.1)" /><rect x="4" y="4" width="4" height="4" style="fill:rgba(0,0,0,.1)" /></svg>');
```

This is unrelated to escaped double quote, because using this code (same SVG as in forked), it will also fail:
```css
background-image: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><rect x="0" y="0" width="100%" height="100%" fill="url(#grid)"/><pattern id="grid" patternUnits="userSpaceOnUse" width="16" height="16"><line x1="16" y1="0" x2="16" y2="16" style="stroke:rgba(130,130,130,0.95); stroke-width:2" /><line x1="0" y1="16" x2="16" y2="16" style="stroke:rgba(130,130,130,0.95); stroke-width:2" /><line x1="0" y1="7.5" x2="16" y2="7.5" style="stroke:rgba(195,195,195,0.75); stroke-width:1;" stroke-dasharray="1, 2" /><line x1="7.5" y1="0" x2="7.5" y2="16" style="stroke:rgba(195,195,195,0.75); stroke-width:1" stroke-dasharray="1, 2" /></pattern></svg>');
```

Now, if I set this previous SVG code in JS as base64, the grid shows:
```javascript
var svg = btoa('<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><rect x="0" y="0" width="100%" height="100%" fill="url(#grid)"/><pattern id="grid" patternUnits="userSpaceOnUse" width="16" height="16"><line x1="16" y1="0" x2="16" y2="16" style="stroke:rgba(130,130,130,0.95); stroke-width:2" /><line x1="0" y1="16" x2="16" y2="16" style="stroke:rgba(130,130,130,0.95); stroke-width:2" /><line x1="0" y1="7.5" x2="16" y2="7.5" style="stroke:rgba(195,195,195,0.75); stroke-width:1;" stroke-dasharray="1, 2" /><line x1="7.5" y1="0" x2="7.5" y2="16" style="stroke:rgba(195,195,195,0.75); stroke-width:1" stroke-dasharray="1, 2" /></pattern></svg>');
document.querySelector(".bg").style.backgroundImage = `url('data:image/svg+xml;base64,${svg}')`;
```

Thanks!

**Comment by Catlinz** [comment]
I had a similar issue with Electron v5, and the problem for me was that the version of chromium used in Electron v5 treats '#'s in URLs differently, and it was breaking the inline SVG background image in the CSS because I had some hex colors.  For me, changing all the '#'s to the URL encoded version, %23, allowed the inline SVG to work again.  Could be a similar issue here?

**Comment by nornagon** [comment]
Can you check whether this works in Chrome 73?

**Comment by Catlinz** [comment]
Using Chrome 73.0.3683.103, both the issue and the solution that I ran into seem to be the same, '#' in SVG data URL breaks it, but changing it to %23 fixes it.

**Comment by nornagon** [comment]
In that case, this isn't an issue with Electron, but rather behaviour we inherit from Chromium. Closing this for now, but feel free to continue discussion if needed.
