### ISSUE TITLE
xxxsetup.exe recognised as trojan by antivirus

### ISSUE THREAD

**Issue by GG-A** [electron/electron#18024]
I download **electron-quick-start**,  I use  **electron-builder** to build **electron-quick-start** to `setup.exe`. when I run this `setup.exe`, the antivirus alter warning: this program will change `d3dcompiler_47.dll`, it's maybe a trojan. 
how to resolve it?

**Comment by MarshallOfSound** [comment]
@GG-A `setup.exe` is not generated by any project in `electron/electron`.  It sounds like the output of [`electron-builder`](https://github.com/electron-userland/electron-builder) is being detected as a false-positive.
