### ISSUE TITLE
Question: Is it possible to get all ipcRenderer listeners for all windows from renderer or through remote?

### ISSUE THREAD

**Issue by Aligatro** [electron/electron#18020]
Hello, i try to find answer for question in subject. Spent already more than couple of hours, but don't get succeed. Hope the questions are allowed. Thanks for the help.

**Comment by Nick-lab** [comment]
not too sure what the question is here. each window will have access to its own listeners and you cant transfer listeners to other windows. can you give an example of use case?

**Comment by Aligatro** [comment]
I'am mean get registered ipcRenderer EE events list of renderer. For example we can get it for main from renderer like this - `remote.ipcMain._events`. But how to get the same for all renderer windows from one of it (if renderer windows are more than one)? Is it possible at all?

**Comment by MarshallOfSound** [comment]
> Is it possible at all?

No, there is no current API to get what listeners are registered on `ipcRenderer` instances from the main process.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by Aligatro** [comment]
Got it, thank you.
