### ISSUE TITLE
Cannot pass ES6 proxy into electron remote function

### ISSUE THREAD

**Issue by iyobo** [electron/electron#18025]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
```
//Renderer

//Load remote functions
const { find,  upsert, remove } = electon.remote.require('filepouch');

// Create a proxy (e.g an object from MobX 5)
const esProxy = ...

await upsert(esProxy)

```

filepouch.js :
``` 
exports.upsert = async (obj)=>{
   // This is always an empty object
   console.log(obj);

}
```

* **Electron Version:**
  * 4.1.0
* **Operating System:**
  * OSX 10.14.4
* **Last Known Working Electron version:**:
  * N/A

### Expected Behavior
obj param in filepouch.js should be an object with contents

### Actual Behavior
obj param in filepouch.js is an empty object

**Comment by vladimiry** [comment]
As a quick guess, try requesting the dependency like: electron.**remote**.require('filepouch');

**Comment by iyobo** [comment]
@vladimiry sorry typo. I was already using electron.remote.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
