### ISSUE TITLE
Problem with file drag & drop

### ISSUE THREAD

**Issue by congk** [electron/electron#18027]
* Electron version: 4.1.5
* Platform: Windows 7(SP1) & Windows 10

Drag & drop any file to <textarea> from File Selection Dialog opened by [input type='file'] tag。
* Step 1. Click the [input type='file'] tag, open file selection dialog
* Step 2. drag & drop any file to <textarea> from the dialog
* See the task manager in Windows.

In my case, electron consume large amounts of CPU resources, and there is no downward trend.

Computer Information:
![image](https://user-images.githubusercontent.com/5109665/56877224-05127f80-6a7f-11e9-9f03-c052b772458a.png)

App capture:
![image](https://user-images.githubusercontent.com/5109665/56877362-01cbc380-6a80-11e9-9bbb-fabfed0d6b23.png)

**Comment by Nick-lab** [comment]
Not really sure what your issue is, my two guesses would be either having an issue with non stock file explorer or issue with html/css and not setting up your file drag and drop region correctly.

**Comment by qwerchuan** [comment]
测试代码
[electron-quick-start.zip](https://github.com/electron/electron/files/3190548/electron-quick-start.zip)
操作步骤与现象
![test](https://user-images.githubusercontent.com/16553355/57913330-fae5e300-78be-11e9-84d9-3075667cf882.gif)

**Comment by congk** [comment]
> 测试代码
> [electron-quick-start.zip](https://github.com/electron/electron/files/3190548/electron-quick-start.zip)
> 操作步骤与现象
> ![test](https://user-images.githubusercontent.com/16553355/57913330-fae5e300-78be-11e9-84d9-3075667cf882.gif)

@Nick-lab Sorry for my english. Here is our test case. We just create an project by electron-quick-start, and made very few changes.

**Comment by Nick-lab** [comment]
you have to work with the drag and drop api not against it my friend. do you know how labels work and how they can be combined with inputs to expand upon their functionality? check this tutorial out https://css-tricks.com/drag-and-drop-file-uploading/

**Comment by congk** [comment]
yes, we know how labels wok.
my real question is "app crashed when user did as shown in gif, i don't know how it happened?".
we cannot control user's behavior.

i really don't know if i made myself clear ...

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
