### ISSUE TITLE
window.opener opened from webview is null after cross site navigation

### ISSUE THREAD

**Issue by hugomano** [electron/electron#18032]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
`5.0.0`
* **Operating System:**
` macOS 10.14.4`
* **Last Known Working Electron version:**:
`4.0.4`

### Expected Behavior

Open a Window with domain A via `window.open` et navigate to domain B in the opened window should keep the `window.opener` reference.

At the business logic level, sign-in with Google Auth from a web frame doesn't work. The callback on final application domain can't post a message to the window opener. 

### Actual Behavior

The `window.opener` is null after cross-site navigation.

### To Reproduce

```js
// main.js

const { app, BrowserWindow } = require('electron')

function createWindow() {
  const mainWindow = new BrowserWindow({
        webPreferences: {
          nodeIntegration: true,
          webviewTag: true,
          contextIsolation: false,
        }
  });

  mainWindow.loadFile('index.html')
}

app.on('ready', createWindow)
app.on('window-all-closed', app.quit);
```

```html
  <webview src="https://mail.google.com" allowpopups></webview>
```

- Call `window.open('https://google.com')` from the web view dev tools
- The `window.opener` is not null
- Go to Github with `window.location  = 'https://github.com'`; the `window.opener` is null

### Additional Information

Similar issues have been reported: https://github.com/electron/electron/issues/17869,
https://github.com/electron/electron/pull/15821, https://github.com/electron/electron/issues/8100

Also preloads doesn't load in the same origin context for the opened window.
Seems linked to https://github.com/electron/electron/issues/17989:

- Web view (`myapp.com`) open `auth.google.com`, `window.opener` is null and preloads are loaded
- Web view (`myapp.com`) open `auth.myapp.com`, `window.opener` is set but preloads are not loaded

More details [here](https://github.com/getstation/electron-chrome-extension/pull/47#issuecomment-487856527)
History: https://github.com/electron/electron/issues/11471#issuecomment-352627083

**Comment by alexstrat** [comment]
Relates to #15821 IMO

**Comment by alexstrat** [comment]
Reproduction repository https://github.com/alexstrat/electron-bug-repro-cross-origin-opener

**Comment by ppontes** [comment]
#15821 fixed this bug for sandboxed renderers. For non-sandboxed renderers, Node is enabled and the approach Electron uses to force it to be properly restarted upon navigation causes this problem.
While this is worked on, you can consider either sandboxing your renderer if at all possible or not using native window open to open the popup.
