### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by ujjwalmaity** [electron/electron#18037]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Electron Version:**
  - 5.0.0
- **Operating System:**
  - Windows 10 (1903)
- **Last Known Working Electron version:**:
  - 4.1.5

### Expected Behavior

    In the lower version of 5.0.0, the app run properly means version 4.1.5 and below it works fine.
    But in the version 5.0.0 it gets an error.
    When I create a second js file and write 'require("electron")' it gets the error.

### Actual Behavior

    Uncaught ReferenceError: require is not defined

### To Reproduce

[GitHub](https://github.com/ujjwalmaity/electronjs-bug "ujjwalmaity")

### Screenshots

![win1](https://user-images.githubusercontent.com/48418596/56921122-936c1d00-6ae2-11e9-8904-ed6d062c5caa.PNG)

**Comment by vladimiry** [comment]
This is expected behavior since `nodeIntegration` is enabled by default since version 5.

So you have 2 options:
- Stopping requiring nodejs dependencies from the rendering process and using IPC communication instead. This is a preferred option in terms of security.
- Explicitly enabling `nodeIntegration` flag (window creating options).

**Comment by MarshallOfSound** [comment]
@vladimiry There is a third (and easier) option.

Move all the things that use node/require into a preload script.  Even when `nodeIntegration` is disabled you still have access to `require` and friends in your preload script.

**Comment by vladimiry** [comment]
@MarshallOfSound missed mentioning preload scripts, yes the simplest option indeed. `electron.remote.require` way of importing nodejs dependencies will work in preload script of the renderer process (`enableRemoteModule` should not be disabled).

**Comment by TheJedinator** [comment]
@vladimiry To avoid creating another issue, I'm commenting here. I current have nodeIntegration false in my previous versions using either electron 3.1.11 or 4.0.9 however any version > 5 causes the same issue for me. I have tried flipping the flag to true and rebuilding and it still does not work. Any assistance would be greatly appreciated. 

`Uncaught ReferenceError: require is not defined
    at (index):1
(index):1 Uncaught ReferenceError: process is not defined
    at (index):1
renderer.js:1 Uncaught ReferenceError: module is not defined
    at renderer.js:1`

first line it fails on `            require('module').globalPaths.push('/home/eigen/repos/eigen-hmi/debuild/node_modules')
`

**Comment by vladimiry** [comment]
As a quick guess, try replacing `require('module')` with `electron.remote.require('module')`. But In general, the stuff you do looks somehow fishy (extending `globalPaths`).

**Comment by TheJedinator** [comment]
Attempted that and get electron not defined instead. this is an index.ejs file. I agree it's hacky but it's only for running on a dev machine. Removing that just leads to errors further down the chain with module/process not being defined.

**Comment by vladimiry** [comment]
This way: `require("electron").remote.require('module')` and prefereably in a preload script.

**Comment by TheJedinator** [comment]
I decided to not rely on the boiler plate we were using that was doing some sketchy things and doesn't seem to be maintained any more. using vue cli and electron-builder now. Thanks for your response.

**Comment by NirmanSonawane** [comment]
in electron v5 and above, node integration is false by default, which is why you might be getting these error:
try:
webPreferences: {
      nodeIntegration: true
    }
when creating a new window

**Comment by mahdisalmanzade** [comment]
![image](https://user-images.githubusercontent.com/55497711/72441051-3d015480-37bf-11ea-925c-4a5a40089f75.png)

![image](https://user-images.githubusercontent.com/55497711/72441078-4d193400-37bf-11ea-9d10-07ea5e43212f.png)

can you guys help to fix my this error?

**Comment by mahdisalmanzade** [comment]
![image](https://user-images.githubusercontent.com/55497711/72441144-6ae69900-37bf-11ea-9daf-5fad0d21b5a9.png)

this is my issue when i run my program

**Comment by mahdisalmanzade** [comment]
@vladimiry please help me if you can

**Comment by vladimiry** [comment]
@mahdisalmanzade you could clone the https://github.com/electron/electron-quick-start and move the custom code that you put to HTML file into the preload.js file.

**Comment by mahdisalmanzade** [comment]
@vladimiry actually im getting this error when im trying to do this

![image](https://user-images.githubusercontent.com/55497711/72442376-9b2f3700-37c1-11ea-9ede-d15a24a6107f.png)

**Comment by vladimiry** [comment]
There is no `require` in https://github.com/electron/electron-quick-start/blob/master/index.html So you certainly do something else.

**Comment by Damercy** [comment]
In case the above suggestions didn't work, you can try the following.

In the main.js file (the main renderer process), where you've created the browser window, set the nodeIntegration to true as follows:

```Javascript
winOne= new BrowserWindow({       
       /* other options like width,height*/
        webPreferences: {
            nodeIntegration: true
}
    });
```

Worked for me. Electron version: ^9.0.4

**Comment by iNerdStack** [comment]
> 
> 
> In case the above suggestions didn't work, you can try the following.
> 
> In the main.js file (the main renderer process), where you've created the browser window, set the nodeIntegration to true as follows:
> 
> ```js
> winOne= new BrowserWindow({       
>        /* other options like width,height*/
>         webPreferences: {
>             nodeIntegration: true
> }
>     });
> ```
> 
> Worked for me. Electron version: ^9.0.4

Worked for me. Thanks

**Comment by alexawake** [comment]
> This is expected behavior since `nodeIntegration` is enabled by default since version 5.
> 
> So you have 2 options:
> 
> * Stopping requiring nodejs dependencies from the rendering process and using IPC communication instead. This is a preferred option in terms of security.
> * Explicitly enabling `nodeIntegration` flag (window creating options).

And how to use IPC if we cannot require ipcRenderer ? in doc [https://www.electronjs.org/docs/api/ipc-renderer ](url) ipcRenderer is used directly but it does not work for me (^10.1.2)

**Comment by raphael10-collab** [comment]
@MarshallOfSound would you be so kind in explaining me how to concretely move all things that need 'require' in preload.js and how to concretely use this? (https://github.com/electron/electron/issues/18037#issuecomment-487728401 )
I'm struggling to understand this in concrete and practical terms.

This is my preload.ts :  

    const {
      contextBridge,
      ipcRenderer
    } = require("electron")

    const url = require('url');

    const fromPathToUrl = (path: string) => {
      return url.pathToFileURL(path);
    }

    contextBridge.exposeInMainWorld(
      "api", {
          //send: (channel, data) => {
              //ipcRenderer.invoke(channel, data).catch(e => console.log(e))
          //},
          //receive: (channel, func) => {
            //ipcRenderer.on(channel, (event, ...args) => func(...args)).catch(e => console.log(e))
          //}
        // https://github.com/frederiksen/angular-electron-boilerplate/blob/master/src/preload/preload.ts
        electronIpcSend: (channel: string, ...arg: any) => {
          ipcRenderer.send(channel, arg);
        },
        electronIpcSendSync: (channel: string, ...arg: any) => {
          return ipcRenderer.sendSync(channel, arg);
        },
        electronIpcOn: (channel: string, listener: (event: any, ...arg: any) => void) => {
          ipcRenderer.on(channel, listener);
        },
        electronIpcOnce: (channel: string, listener: (event: any, ...arg: any) => void) => {
          ipcRenderer.once(channel, listener);
        },
        electronIpcRemoveListener:  (channel: string, listener: (event: any, ...arg: any) => void) => {
          ipcRenderer.removeListener(channel, listener);
        },
        electronIpcRemoveAllListeners: (channel: string) => {
          ipcRenderer.removeAllListeners(channel);
        }
      }
    )

In index.d.ts I declared interface Window:


    declare interface Window {
      //electron: {
        //doThing(): void;
      // https://github.com/frederiksen/angular-electron-boilerplate/blob/master/src/window-interface/ind$
        api: {
          /** Electron ipcRenderer wrapper of send method */
          electronIpcSend: (channel: string, ...arg: any) => void;
          /** Electron ipcRenderer wrapper of sendSync method */
          electronIpcSendSync: (channel: string, ...arg: any) => any;
          /** Electron ipcRenderer wrapper of on method */
          electronIpcOn: (channel: string, listener: (event: any, ...arg: any) => void) => void;
          /** Electron ipcRenderer wrapper of onOnce method */
          electronIpcOnce: (channel: string, listener: (event: any, ...arg: any) => void) => void;
          /** Electron ipcRenderer wrapper of removeListener method */
          electronIpcRemoveListener: (channel: string, listener: (event: any, arg: any) => void) => void;
          /** Electron ipcRenderer wrapper of removeAllListeners method */
          electronIpcRemoveAllListeners: (channel: string) => void;
        }
    }

In main.ts I defined and ipcMain.handle :  

    ipcMain.handle("path-to-url", (IpcMainEvent, path) => {
      if (mainWindow) {
        mainWindow.webContents.send("path-to-url", path);
      }
    });

I need to call the function fromPathToUrl defined in preload.ts in a viewerDemo.tsx file.
How to do properly do it?

I did this, but it's not correct: 

    let path = './images/natural-scene.jpeg';
    window.api.electronIpcOn("path-to-url", fromPathToUrl (path));

Error message : `Uncaught ReferenceError: fromPathToUrl is not defined in viewerDemo.tsx`

**Comment by falah-M** [comment]
> In case the above suggestions didn't work, you can try the following.
> 
> In the main.js file (the main renderer process), where you've created the browser window, set the nodeIntegration to true as follows:
> 
> ```js
> winOne= new BrowserWindow({       
>        /* other options like width,height*/
>         webPreferences: {
>             nodeIntegration: true
> }
>     });
> ```
> 
> Worked for me. Electron version: ^9.0.4
Good!

**Comment by Zeeshan-2k1** [comment]
```
const createWindow = () => {
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true,
    },
  });
}
```

` node  15.11.0`

`npm 7.6.1`

`electron 12.0.1`

Even after adding nodeIntegration: true. I am getting error `require not defined.`

Please Help.

**Comment by zastrowm** [comment]
I was having the same problem - `require not defined` even with `nodeIntegration: true`.  However, I came across https://stackoverflow.com/questions/59523682/nodeintegration-true-ignored which suggested `contextIsolation: false` as well - if I enabled that, then it worked.
