### ISSUE TITLE
--in-process-gpu strange behavior

### ISSUE THREAD

**Issue by hackteck** [electron/electron#18048]
### Electron 5.0.0 @ Windows 10 LTSB x64
`app.commandLine.appendSwitch("--in-process-gpu");` only shows a white screen and nothing else, although everything works in version _4.1.5_

**main.js**
```
const { app, BrowserWindow } = require('electron');
app.commandLine.appendSwitch("--in-process-gpu");
app.commandLine.appendSwitch("--autoplay-policy", "no-user-gesture-required");
let mainWindow;

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    minHeight: 450,
    minWidth: 480,
    show: false
  });
  mainWindow.loadFile('./index.html');
  mainWindow.setMenu(null);
  //mainWindow.setFullScreen(true);
  mainWindow.maximize();
  mainWindow.webContents.openDevTools();
  mainWindow.once('ready-to-show', mainWindow.show);
  mainWindow.on('closed', () => mainWindow = null);
  //mainWindow.webContents.on('devtools-opened', mainWindow.webContents.closeDevTools);
}

//APP EVENTS
app.on('ready', () => {
  createWindow();
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
})
app.on('activate', function () {
  if (mainWindow === null) createWindow();
})
```

**Comment by miniak** [comment]
@hackteck Why do you want to use in-proc GPU?

**Comment by hackteck** [comment]
@miniak because this is the only way I know to enable Steam overlay.

**Comment by Cleod9** [comment]
Same issue here, was fine in 4.1.5 and was needed for Steam overlay

**Comment by Spacetech** [comment]
I'm also having this issue. Running `electron.exe --in-process-gpu` gives me a white screen on v6.0.0-beta.13-win32-x64. Could someone add a v6 label to this?

Like others said, for Steam games that use Electron, the "--in-process-gpu" flag is required to get the Steam overlay working. There are [a](https://github.com/greenheartgames/greenworks/issues/16) [few](https://github.com/greenheartgames/greenworks/issues/50) [issues](https://github.com/greenheartgames/greenworks/issues/40) and [a pull request](https://github.com/electron/electron/pull/8628) that has some more information about this particular problem.

From my testing, electron v4 works with `--in-process-gpu` if you directly launch the electron.exe with that argument. We previously used `app.commandLine.appendSwitch("in-process-gpu");`, but this no longer works. See #14273 for discussion about that.

Something to note about the white screen is that the game still "functions". I can hear sounds and click on stuff, I can't just see it. I would attach an image, but it would just be a blank white image 😄 

I'm guessing the chromium upgrade between electron v4 and electron v5 caused this problem, and it continued on from v5 into v6. Anyone have ideas on how to debug this or get it working again?

**Comment by nornagon** [comment]
Does Chrome work for you with `--in-process-gpu`?

**Comment by Spacetech** [comment]
@nornagon It does not work. No window opens. In task manager, I see two chrome.exe processes running and neither of them are the renderer process. The processes exit about 25 seconds later.
Tested on version 75.0.3770.142. I'm running on windows 10 w/ an amd gpu (vega 56).

**Comment by vaughnroyko** [comment]
Same for me in Chrome 77.0.3854.0 (Windows 10, GeForce RTX 2070). The #use-angle flag also has no effect on this.

**Comment by nornagon** [comment]
Unfortunately in general we can't support behaviour that Chromium doesn't support. Please file a bug against Chromium: https://crbug.com/new

Leaving this open as a tracking issue.

**Comment by Spacetech** [comment]
Yea makes sense. I've [filed a bug](https://bugs.chromium.org/p/chromium/issues/detail?id=985653) against Chromium for it. Thanks.

**Comment by leozzyzheng** [comment]
I think it is also reasonable to provide a way get the GPU process id which could be used by overlay program.

**Comment by nornagon** [comment]
@leozzyzheng is that possible with Steam's APIs? If so, I think that would be a preferable solution. As you've discovered, Chrome's in-process GPU mode is not well-supported upstream :\

**Comment by leozzyzheng** [comment]
> @leozzyzheng is that possible with Steam's APIs? If so, I think that would be a preferable solution. As you've discovered, Chrome's in-process GPU mode is not well-supported upstream :\

No, I'm a developer from another game platform and we also have a game overlay need this feature. But currently we just found this command line switch is useful.
Another problem is that we found the electron-quick-start demo crashes in Chromium even if I only add the command line switch on v4.2.8, so overlay may also have problem on v4.x.x electron. I'm just checking the v3.1.12, hope it won't crash again.

**Comment by leozzyzheng** [comment]
Seems v3.1.12 is stable for me.

**Comment by goldfire** [comment]
Has anyone figured anything out with this? We've been trying to get our Steam games updated to Electron 6 from 3 so that we can get the benefits from a much newer version of Chromium, but we can't seem to get past the white screen issue.

**Comment by MikalDev** [comment]
@goldfire I don't how usable this is, but I just got Steam overlay to work with Win 10, Electron 6.0.6 and using append-switch in-process-gpu. The 'fix': change the Electron exe to run in Windows 8 compat mode (set properties->compatability->win 8). What else does this break, I don't know, but the basics of my game and Steam Overlay and Steam API work in very light testing. Can you try and share your experience, if it works - does it hit perf or other functionality w/ your game? Also I doing a little bit of googling, it looks like a decent installer could add the reg key to make the Electron run in win8 compat mode on install also.

**Comment by kylechar** [comment]
Does adding the --disable-direct-composition flag, in addition to --in-process-gpu, fix the white screen issue?

**Comment by tishion** [comment]
@kylechar 

I tried your suggestion and it works now. Thanks.

BTW, I tried it in my own application based on CEF lib.

**Comment by codebytere** [comment]
Closing as we have no control over this and there exist workarounds. If issues persist, we recommend you bring the flag issues to crbug.com

**Comment by Flashwalker** [comment]
I found that some electron based apps, packaged in appimage, fails to start with error:
```
...
FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
...
```
And the only way they starts is with: `--in-process-gpu`
