### ISSUE TITLE
Window.confirm is not modal anymore

### ISSUE THREAD

**Issue by robsonhermes** [electron/electron#18055]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.1.5
* **Operating System:**
  * Windows 10 (1809)
  * Ubuntu 18.04.2 LTS
* **Last Known Working Electron version:**
  * 1.8.7 (Sorry about the big jump, but we moved directly from Electron 1.8.7 to 4.1.5. So I am not quite sure where down the road this was broken)

### Expected Behavior
`window.confirm` should be modal. Users should not be able to click elsewhere in the main window sending the dialog to the background.

### Actual Behavior
`window.confirm` is not modal. Users can accidentally click elsewhere in the main window, sending the  dialog to the background. Consequently some of them don't realize that and seems application is frozen/stuck.

### To Reproduce

$ git clone https://github.com/robsonhermes/electron-quick-start.git
$ cd electron-quick-start
$ npm install
$ npm start

**Comment by robsonhermes** [comment]
@sofianguy it also happens on Linux, just tested =(

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
