### ISSUE TITLE
Electron build failed due to warning C5054 under "/std:c++latest"(C++20) + "/W4" on MSVC

### ISSUE THREAD

**Issue by QuellaZhang** [electron/electron#18053]
Electron build failed due to warning C5054 under /std:c++latest(C++20) + /W4 in the development version of Visual C++. Could you help look at this? Thanks in advance! Noted that this issue only found when compiles with unreleased vctoolset, that next release of MSVC will have this behavior.

**Repro steps:**

1. git clone https://github.com/electron/electron.git D:\Electron\src
2. open a clean VS x86 command prompt and browse to D:\Electron\src
3. set _CL_=/Zc:noexceptTypes- /std:c++latest 
4. python script\bootstrap.py -v --target_arch=ia32
5. cd ..
6. vendor\depot_tools\ninja.exe -C out\R electron -v -d keeprsp

**Failures:**
D:\Electron\src\vendor\download\libchromiumcontent\src\third_party\skia\include\private\SkSafe32.h(12): error C2220: warning treated as error - no 'object' file generated
D:\Electron\src\vendor\download\libchromiumcontent\src\third_party\skia\include\core\SkMatrix.h(1811): warning C5054: operator '&': deprecated between enumerations of different types
D:\Electron\src\vendor\download\libchromiumcontent\src\third_party\skia\include\core\SkMatrix.h(1811): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
D:\Electron\src\vendor\download\libchromiumcontent\src\third_party\skia\include\core\SkMatrix.h(1823): warning C5054: operator '&': deprecated between enumerations of different types
D:\Electron\src\vendor\download\libchromiumcontent\src\third_party\skia\include\core\SkMatrix.h(1823): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings

**Comment by nornagon** [comment]
We don't support building with MSVC. See https://github.com/electron/electron/blob/master/docs/development/build-instructions-gn.md.

**Comment by cdacamar** [comment]
@nornagon From the build instructions:

> Note: Even though Visual Studio is not used for building, it's still required because we need the build toolchains it provides.

Doesn't this imply MSVC is used for building Electron?

**Comment by nornagon** [comment]
Electron is built with Clang.

**Comment by MichaelGoulding** [comment]
This will eventually happen on Clang as well when they implement http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p1120r0.html

**Comment by nornagon** [comment]
@MichaelGoulding if such an implementation eventually comes to clang, this build error will be fixed upstream before it reaches us.
