### ISSUE TITLE
-webkit-app-region:drag does not work in iframe

### ISSUE THREAD

**Issue by chenjiangshuo** [electron/electron#18057]
I found that setting ‘-webkit-app-region:drag’ in the iframe doesn't work. What should I do

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
