### ISSUE TITLE
How to pull a stripped version of Electron from proprietary dependencies?

### ISSUE THREAD

**Issue by marechal-p** [electron/electron#18063]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
Working on [Theia](https://github.com/theia-ide/theia), we are trying to offer support for Electron applications. Even though we are technically a framework, we do publish and hence distribute code, such as `electron` which itself pulls the Electron binaries, along with the dreaded `libffmpeg.so` library which contains proprietary codecs. I've seen in the releases that a different `libffmpeg.so` is distributed, so I have two questions:
- Is this safe to rely on the releases to contain a stripped `libffmpeg.so`?
- What would be a recommend way of pulling a proprietary-free electron version?

### Proposed Solution
Either there already is a somewhat standard way of pulling the stripped binaries, or see at making it configurable in the `install.js` script, or maybe at the `electron-download` package level?

### Alternative solution
We could always fallback to making our own package downloading a given Electron binaries and then trying to replace the `libffmpeg.so` file, just not sure if that's the best way, and if you guys will keep releasing a stripped version in the long run :)

---

cc @marcdumais-work

**Comment by marechal-p** [comment]
Updated the issue to correctly refer to problematic proprietary codecs, but the issue is the same:
- Is it reliable to rely on the github release for the stripped shared library?
- Is there a common way to use that library, or should we come up with our own download-and-replace?

**Comment by malept** [comment]
> * Is there a common way to use that library, or should we come up with our own download and replace script/package?

This Node module exists to do just that: https://www.npmjs.com/package/electron-packager-plugin-non-proprietary-codecs-ffmpeg

**Comment by MarshallOfSound** [comment]
Quite a few folks depend on that `ffmpeg` version so although we can't make any guarantees that it will stay around (we're somewhat dependent on Chromium + ffmpeg supporting that).  We're not going to deliberately remove it.

As @malept mentioned there is a userland module that folks use to swap in that version of `ffmpeg`

**Comment by marechal-p** [comment]
@MarshallOfSound @malept that answers my question, thanks :)
