### ISSUE TITLE
Preload script not run with nativeWindowOpen=true and window.open('')

### ISSUE THREAD

**Issue by jeremyspiegel** [electron/electron#18070]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.0
* **Operating System:**
  * macOS 10.14.4
* **Last Known Working Electron version:**:
  * 4.1.5

### Expected Behavior
I would like to open a new child window and render content into it from script running in my `mainWindow`, rather than perform a navigation in the new child window. This works when setting `nativeWindowOpen: true` for the main window and using `window.open('')` to open a window with location `about:blank`.

I would also like to load a preload script in the new window, so that I can configure the `webFrame`. In 4.1.5, setting a preload script on the main window caused the preload script to also be loaded for child windows. In 5.0.0, the preload script stopped loading for the child window.

I would actually expect that providing a preload script in the `new-window` event would work, as described [here](https://electronjs.org/docs/api/window-open#using-chromes-windowopen-implementation) and pointed out [here](https://github.com/electron/electron/issues/16224#issuecomment-451108352) by @MarshallOfSound, but it doesn't. I've tried various ways of using the options that are passed into the event, but none have worked:
```
mainWindow.webContents.on('new-window', (event, url, frameName, disposition, options) => {
  event.preventDefault();
  Object.assign(options, {
    webPreferences: {
      preload: `${__dirname}/preload.js`
    }
  });
  event.newGuest = new BrowserWindow(options);
});
```
and
```
mainWindow.webContents.on('new-window', (event, url, frameName, disposition, options) => {
  event.preventDefault();
  Object.assign(options.webPreferences, {
    preload: `${__dirname}/preload.js`
  });
  event.newGuest = new BrowserWindow(options);
});
```
and
```
mainWindow.webContents.on('new-window', (event, url, frameName, disposition, options) => {
  event.preventDefault();
  event.newGuest = new BrowserWindow({
    webPreferences: {
      preload: `${__dirname}/preload.js`
    }
  });
});
```

### Actual Behavior
There doesn't seem to be a way to load a preload script into a window opened via `window.open('')` in electron 5.0.0. I'd like some way to get that to work, whether that is by setting the preload script on the main window as worked in previous versions, or making it work when setting it in the `new-window` event.

### To Reproduce
[Here](https://github.com/jeremyspiegel/electron-quick-start/commit/b0d0fafa54ad130c1784bd558baff36501b2cdee) is a commit that demonstrates the preload script loaded properly when run with electron 4.1.5, but not loaded when run with electron 5.0.0, and here is the branch:
```sh
$ git clone git@github.com:jeremyspiegel/electron-quick-start.git -b preload-not-run-on-window-open
$ npm install
$ npm start || electron .
```

### Additional Information
I think this might be related to https://github.com/electron/electron/issues/17989 or https://github.com/electron/electron/issues/16224, but those issues actually involve a `window.open` with a navigation, while my issue doesn't (if I open a window that performs a navigation, the preload script does still run for me in 5.0.0).

I tried removing the early exit from https://github.com/electron/electron/blob/53f6cbccbf388dd28bd8636cd452df4c1d0f4f13/atom/renderer/atom_renderer_client.cc#L76-L79 as suggested in https://github.com/electron/electron/issues/17989#issuecomment-488033529 but that didn't fix the issue either.

**Comment by alexstrat** [comment]
@jeremyspiegel I was able to have preload scripts running with the suggestion https://github.com/electron/electron/issues/17989#issuecomment-488033529. If you have a chance to try #18152 to verify that.

**Comment by alexstrat** [comment]
After some digging, I realized it is an intended behavior after #15213 but that you can get over it by using `nodeIntegrationInSubFrames`:

```diff
--- a/main.js
+++ b/main.js
@@ -12,6 +12,7 @@ function createWindow () {
     height: 600,
     webPreferences: {
       nativeWindowOpen: true,
+      nodeIntegrationInSubFrames: true,
       nodeIntegration: true,
       preload: `${__dirname}/preload.js`
     }
```

See #18156

**Comment by jeremyspiegel** [comment]
@alexstrat thanks for the clarification, that worked for me!

Is it known what caused the crashes when releasing node environments that required the change to disable nodeIntegration by default (#15076)? I'm wondering if there will be a way to have preload scripts run in new windows without having the memory leak.

**Comment by alexstrat** [comment]
🤷‍♂️I don't know exactly.

I think at the time of #15076 no one had figured out how to have several node environments in 1 render process, but, later, I think MarshallOfSound figured it out in #16425.

_Reminder to close the issue._

**Comment by jeremyspiegel** [comment]
OK sounds good, thanks!
