### ISSUE TITLE
IndexedDB silently fails after refresh

### ISSUE THREAD

**Issue by hnry** [electron/electron#18082]
* **Electron Version:**
  *  5.0.0
* **Operating System:**
  *  OSX Mojave

Whenever I refresh my app while developing, all my code with IndexedDB stops working. I mean it silently stops working, no errors thrown. Works fine on first launch or restart, but a refresh is what I mean.

Maybe related to https://github.com/electron/electron/issues/10792 but again I don’t get any errors; things just stop working. And I’m not running multiple instances.

Is this normal?

**Comment by hnry** [comment]
Oh WOWOWOWOWOWOWOWOWOWoWOwooWOowoWOwooWOwoWWW !!!
I wasted 2 hrsssssss especially since it was a silent bug. 

But yea, dropped to electron 4.1.5 and it fixed.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
