### ISSUE TITLE
frameName instance property missing from BrowserWindow docs

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#18106]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 4.0.4
* **Operating System:** Windows 10
* **Last Known Working Electron version:**: n/a

the [docs](https://electronjs.org/docs/api/browser-window#instance-properties) don't list `frameName` as a property on `BrowserWindow`, but it apparently is.

At least when `nativeWindowOpen` is set, `win.frameName` returns the second argument to `window.open` / the `frameName` parameter in the `new-window` handler.

**Comment by MarshallOfSound** [comment]
@pushkin- This property is deliberately not documented as it is not API.  It was originally added for some internal memoization logic that is no longer required.  It can (and probably will) be removed at any time.

**Comment by pushkin-** [comment]
@MarshallOfSound So is there now way to retrieve a window's frame name?

I can get the frameName from the `new-window` handler, but how can I then associate it with the actual created-window in `browser-window-created`?

**Comment by pushkin-** [comment]
@MarshallOfSound Any suggestions for me? Are you thinking about removing `frameName` from the properties just because it's not used, or because you don't want to expose it to consumers for some other reason? Thank you

It's important for my situation to be able to figure out what `windowName` was passed into `window.open` (with `nativeWindowOpen` set) and be able to get that information from the `BrowserWindow`.

**Comment by MarshallOfSound** [comment]
@pushkin- I'd reccomend for your use case using a `WeakMap<WebContents, string>` that maps a window to the frame name it was given in the `new-window` event.

E.g.

```js
const myMap = new WeakMap();
w.on('new-window', (e, url, frameName, disposition, options) => {
  myMap.set(options.webContents, frameName);
});

app.on('browser-window-created', (e, window) => {
  const frameName = myMap.get(window.webContents);
});
```

**Comment by pushkin-** [comment]
@MarshallOfSound  Oh! well that's a pleasant surprise. I had my `options` typed as `BrowserWindowConstructorOptions`, but indeed looks like there's a webcontents on it. Maybe this issue should be repurposed into one about adding typings for the `options` parameter of `new-window` since it's currently set to `any`

**Comment by MarshallOfSound** [comment]
@pushkin- `BrowserWindowConstructorOptions` is actually correct, it's just that that options object has an undocumneted `webContents` property.  That property probably won't go anywhere though as it's key to how we construct windows for webContents that already exist.

That `options` object in `new-window` should definitely be documented as `BrowserWindowConstructorOptions` though 😄

**Comment by pushkin-** [comment]
@MarshallOfSound Resurrecting this. There's a situation where we cancel the initial window creation, do some async check, and then decide to continue with it by creating a new `BrowserWindow` and passing in the old options.

In this case, we've created a new `webContents` (the old `options.webContents.id` throws something like "Object has been destroyed"), and the `browser-window-created` handler is executed the moment we call the `BrowserWindow` constructor, so we don't have a chance to add the new `webContents` into the map.

Is there any way to accomplish this (saving off the window name passed to `window.open` when we cancel and recreate the window)?

One thought I had was to save the window name into options.title temporarily and get the title in the browser window created handler, but if there's a cleaner way, I'm all ears.

I guess another way is save the current window name that's being opened in a local var and assume that the next `browser-window-created` handler call will be for that same window.

**Comment by schontz** [comment]
> @pushkin- I'd reccomend for your use case using a `WeakMap<WebContents, string>` that maps a window to the frame name it was given in the `new-window` event.
> 
> E.g.
> 
> ```js
> const myMap = new WeakMap();
> w.on('new-window', (e, url, frameName, disposition, options) => {
>   myMap.set(options.webContents, frameName);
> });
> 
> app.on('browser-window-created', (e, window) => {
>   const frameName = myMap.get(window.webContents);
> });
> ```

Now that `new-window` has been deprecated in favor of `setWindowOpenHandler`, how would I go about implementing WeakMap solution?

**Comment by pushkin-** [comment]
@schontz The [`did-create-window`](https://www.electronjs.org/docs/api/web-contents#event-did-create-window) handler apparently gets passed the frame name, so you should be able to just reference it directly from there. Is that what you want?

**Comment by schontz** [comment]
I tried it, but somehow things get real wonky for me. See the following code with comments...

```js
const frameNameMap = new WeakMap();

app.on('browser-window-created', async (event, win) => {
  const { webContents } = win;

  // both IDs = 2
  console.log('ids', { webContents: webContents.id, win: win.id, url: webContents.getURL() });

  const readyToShow = new Promise(r => win.once('ready-to-show', () => r()));

  let frameName = frameNameMap.get(webContents);

  if (!frameName) {
    // running this causes webContents.getURL() to return the URL of window.opener
    // if we don't run this line, then webContent.getURL() returns the URL of the opened window
    frameName = await new Promise(r => 
      webContents.once('did-create-window', (_, { frameName }) => r(frameName))
    );
  }

  // both IDs now = 1
  console.log('ids', { webContents: webContents.id, win: win.id, url: webContents.getURL() });

  await readyToShow;

  const url = webContents.getURL();

  console.log('output:', { frameName, url });
})
```

Somehow the `win` and `webContents` references are changed if I await `did-create-window`. I feel like I'm missing something obvious.

---

On a side note, it would be nice to be able to make promise-safe utils around some events, e.g. is there a reliable property to look at on `browserWindow` or `webContents` that would let me know that `'ready-to-show'` has already been fired?

**Comment by pushkin-** [comment]
@schontz huh, so you're adding the `did-create-window` handler *after* `browser-window-created` fired? Is that not too late? Second, `did-create-window` only fires if `setWindowOpenOverrideHandler` is hooked up and allowed the window creation. Are you doing that?

Do you want both handlers, or can you turn your `browser-window-created` into `did-create-window`?
