### ISSUE TITLE
Windows chrome and context menu should be aware of dark mode setting

### ISSUE THREAD

**Issue by shiftkey** [electron/electron#18119]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Recent builds of Windows 10 support a "dark mode" that changes the chrome and context menus to fit better with the rest of the OS. https://www.digitaltrends.com/computing/how-to-enable-dark-mode-in-windows-10/ has a write up of how to enable this.

Here's a side-by-side of Explorer and the Quick Start app on Windows `10.0.17763.437`:

![](https://user-images.githubusercontent.com/359239/57080976-2b782b00-6cca-11e9-8c41-5097e39526d1.png)

This is complementary to #15316 but not the whole solution:

 - it'd be great if the defaults "just worked" based on this setting, so app developers and users would get this benefit without needing to manage configuration themselves
 - some apps choose to roll their own themes, but they don't have control over the main menu or context menu without also rolling their own implementations of those and hiding the default chrome

To go into more detail, here's what a context menu looks like that respects the dark mode setting:

![](https://user-images.githubusercontent.com/359239/57081074-5ebaba00-6cca-11e9-97f7-d30fc030c759.png)

And here's the equivalent main menu and context menu in the Electron Quick Start when using Electron 5:

![](https://user-images.githubusercontent.com/359239/57081076-5ebaba00-6cca-11e9-926b-9a18be540bef.png)
![](https://user-images.githubusercontent.com/359239/57081077-5ebaba00-6cca-11e9-8f3e-d3b0d61d3e72.png)

### Proposed Solution

I'm not familiar with how this works under the hood, but happy to go spelunking if this is something that interests the maintainers to gather more information.

### Alternatives Considered

As mentioned above, app developers can roll their own dark theme for menus and switch to use a chromeless `BrowserWindow`. That's fine for people who want to invest in that, but if there's lots of interest in the default chrome working better then maybe this is worth diving into?

**Comment by codebytere** [comment]
cc @MarshallOfSound ☝️

**Comment by MarshallOfSound** [comment]
I believe we have a hard dependency on Chromium enabling dark mode in these views.  This is happening _right nowish_ in C76/77 based on the work that is still happening in their codebase.

E.g. 
https://chromium-review.googlesource.com/c/chromium/src/+/1588766

Once that lands this should happen automagically

**Comment by shiftkey** [comment]
@MarshallOfSound awesome - I'm happy to keep an eye on this as the 6.0 betas evolve in case it makes it in by time that ships.

Feel free to close this out if there's no Electron-specific work to enable this on your side.

**Comment by shiftkey** [comment]
This change look like it's worth following: https://chromium-review.googlesource.com/c/chromium/src/+/1597930

**Comment by ChrisHSandN** [comment]
Is there any progress on this?

Since this bug was opened Electron 6+ started supporting a dark mode menu bar but the window chrome is still stuck as white.

Electron v9.0.0-beta.3 looks like this:
![image](https://user-images.githubusercontent.com/13466620/75464490-2da92580-597f-11ea-9d8c-6fc7bc1f0e99.png)

C76/77 is mentioned above but v9 is now on C83 is this still a Chromium blocker or an Electron issue?

**Comment by x4080** [comment]
Is there progress for this white window chrome ?

**Comment by ChrisHSandN** [comment]
Electron v10.0.0-beta.1 looks like this:
![image](https://user-images.githubusercontent.com/13466620/82687185-e1ecdc00-9c4e-11ea-88c1-47fc6e1d204e.png)

I guess that rules out C84 fixing it

**Comment by x4080** [comment]
Is it windows api that dont have dark windows chrome ? But windows explorer can have dark windows chrome

**Comment by ChrisHSandN** [comment]
The latest Electron v11.0.0-beta7 (C86) still doesn't have any improvement so I have posted this as a bug on the Chromium tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=1127795

I am no expert... but I *think* what is happening is that Electron is showing the native Windows 10 titlebar (which Chrome never shows anymore as it renders its own "custom-titlebar"). Hence Chromium has never had any need to respect dark mode on the native titlebar.

Luckily there was still an obscure flag for Chrome `disable-windows10-custom-titlebar` so they could replicate the issue natively and has at least got the bug report to `Status: Untriaged`.
