### ISSUE TITLE
Offscreen rendering - sticky mouse in <select> combo box

### ISSUE THREAD

**Issue by rivkab** [electron/electron#18118]
* Electron version: 4.1.4. Also reproduced on 4.0.0 and 1.8.6
* Operating system: Windows 10

### Expected behavior

Clicking on an option in a combo box ('select' html tag with set size) displayed using offscreen rendering should select that option and "release" the mouse. Mousing over another option without clicking should not select it

### Actual behavior

When a combo box ('select' html tag with set size) is displayed using Electron offscreen rendering, selecting an option leaves the mouse "stuck" on the box. Mousing over other options selects them, despite not clicking

### How to reproduce
    
    $ git clone https://github.com/rivkab/stickyMouseComboBox
    $ cd stickyMouseComboBox
    $ npm i electron@4.1.4
    $ node_modules\electron\dist\electron.exe stickyMouseBug.js

Click on a single option in the combo box and move the mouse up and down without clicking again

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
