### ISSUE TITLE
NODE_MODULE_VERSION problem with Electron 5.0.0

### ISSUE THREAD

**Issue by informaticienzero** [electron/electron#18128]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.0
* **Operating System:**
  * Docker image node:12.0.0, but I think the problem is common on all platforms.
* **Last Known Working Electron version:**:
  * N/A but the plugin `edge-js` works without any manuel recompilation with Node 10.x.

### Expected Behavior
Compiling the `edge-js` native module with Node 12.0.0 works and produce a module usable with Electron 5.0.0.

### Actual Behavior
The compilation works perfectly but Electron throws error, saying that the NODE_MODULE_VERSION used for plugin is 72 but the NODE_MODULE_VERSION of Electron is 70. 

A [StackOverflow](https://stackoverflow.com/questions/46384591/node-was-compiled-against-a-different-node-js-version-using-node-module-versio) is related to this problem.

### To Reproduce

I should provide tomorrow a repo showing the problem.

### Additional Information

The problem does not come from the plugin, but seems to come from the NODE_MODULE_VERSION. Shouldn't it be 72, as specified [here](https://nodejs.org/en/download/releases/)?

**Comment by informaticienzero** [comment]
I made some researches and found issues [here](https://github.com/electron-userland/electron-builder/issues/3660), [here](https://github.com/nodejs/TSC/issues/651), or [here](https://github.com/nodejs/node/pull/24114). So, how am I suppose to compile the native module ? Should I remove all those `#if NODE_MODULE_VERSION <= NODE_11_0_MODULE_VERSION` as suggested [here](https://github.com/nodejs/nan/issues/839#issuecomment-472913184)?

**Comment by nornagon** [comment]
Electron and Node have separate NODE_MODULE_VERSIONs. See https://github.com/nodejs/node/blob/master/doc/abi_version_registry.json. Compiling a module against Node _will not_ produce a module that is usable with Electron. The ABIs are not explicitly compatible (you might get lucky sometimes, but in general the two are not compatible).

If you're trying to build a module against a stable ABI, consider [n-api](https://nodejs.org/api/n-api.html).

**Comment by MarshallOfSound** [comment]
You'll have to build the native module against Electron's headers rather than Node.JS's headers.  As @nornagon mentioned the ABI is 99% of the time incompatible.

See https://electronjs.org/docs/tutorial/using-native-node-modules for more info on how to build your native module for use with Electron

**Comment by informaticienzero** [comment]
Thanks for your quick answers, it helps me. I read this page before opening the issue, and I made a `npm install` with setting the environment variables, as precised.

To be certain, I'll redo everything today with a clean install. Is the following line correct? 

```
# Electron's version.
export npm_config_target=5
```

Thanks a lot for quick answers and help you provide.

**Comment by MarshallOfSound** [comment]
@informaticienzero You need the entire block (all the variables)

```bash
# Electron's version.
export npm_config_target=5.0.0
export npm_config_arch=x64
export npm_config_target_arch=x64
export npm_config_disturl=https://atom.io/download/electron
export npm_config_runtime=electron
export npm_config_build_from_source=true
HOME=~/.electron-gyp npm install
```

**Comment by informaticienzero** [comment]
Thanks. I'll post later today all the informations and commands I use, like the Dockerfile, the Node installation, etc.

I'm pretty sure I wrote all as required in the linked page, but I maybe mixed up something.

**Comment by informaticienzero** [comment]
Yes, the command you gave me was right. I certainly had mix up something while compiling, causing the error. Sorry for raising a non-issue. And thanks again for the nice job on Electron. :)

**Comment by ldm0** [comment]
It solves my problem!
