### ISSUE TITLE
Crash when passing an array for header value in registerFileProtocol handler

### ISSUE THREAD

**Issue by nornagon** [electron/electron#18126]
Here's an example [fiddle](https://github.com/electron/fiddle) that triggers the crash: https://gist.github.com/0cbf622b1b46ea55811f56df9b32df37.

It looks like we're just assuming that this value is a string, and we crash hard if anything other than a string is passed. It would be better for us to throw a JS error in this situation.

```
base::Value::GetString() const (in Electron Framework) (values.cc:319)
atom::URLRequestAsyncAsarJob::StartAsync(std::__1::unique_ptr<base::Value, std::__1::default_delete<base::Value> >, int) (in Electron Framework) (url_request_async_asar_job.cc:88)
base::internal::Invoker<base::internal::BindState<void (atom::URLRequestAsyncAsarJob::*)(std::__1::unique_ptr<base::Value, std::__1::default_delete<base::Value> >, int), base::WeakPtr<atom::URLRequestAsyncAsarJob>, std::__1::unique_ptr<base::Value, std::__1::default_delete<base::Value> >, int>, void ()>::RunOnce(base::internal::BindStateBase*) (in Electron Framework) (bind_internal.h:641)
base::TaskAnnotator::RunTask(char const*, base::PendingTask*) (in Electron Framework) (task_annotator.cc:114)
base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::sequence_manager::LazyNow*, bool*) (in Electron Framework) (heap_profiler.h:93)
base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoSomeWork() (in Electron Framework) (thread_controller_with_message_pump_impl.cc:214)
base::MessagePumpKqueue::Run(base::MessagePump::Delegate*) (in Electron Framework) (message_pump_kqueue.cc:155)
non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) (in Electron Framework) (thread_controller_with_message_pump_impl.cc:0)
base::RunLoop::RunWithTimeout(base::TimeDelta) (in Electron Framework) (run_loop.cc:167)
content::BrowserProcessSubThread::IOThreadRun(base::RunLoop*) (in Electron Framework) (browser_process_sub_thread.cc:0)
base::Thread::ThreadMain() (in Electron Framework) (thread.cc:315)
base::(anonymous namespace)::ThreadFunc(void*) (in Electron Framework) (platform_thread_posix.cc:83)
```

NB. this is probably only a good first issue if you have some C++ experience :)

**Comment by allstaralok** [comment]
Hi, I want to contribute. How should I start, Please help as this is my first time.

**Comment by nornagon** [comment]
@allstaralok The first step would be to get a checkout of Electron building on your machine by following the instructions here: https://github.com/electron/electron/blob/master/docs/development/build-instructions-gn.md

**Comment by nmohnblatt** [comment]
Hey, first-timer here too. I'm trying to build the project locally by following the instructions linked above. I seem to get stick at the "Getting the code section". When I run the following lines from the instructions:

 ```
$ mkdir electron-gn && cd electron-gn
$ gclient config --name "src/electron" --unmanaged https://github.com/electron/electron
$ gclient sync --with_branch_heads --with_tags
# This will take a while, go get a coffee.
```

Terminal has been running for over 2 hours now, outputting timestamps like these:

    [1:55:43] Still working on:
    [1:55:43]   src

and sometimes a warning that goes along the lines of:

    WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone"
    "--no-checkout" "--progress" "https://chromium.googlesource.com/chromium/src.git"
    "User/electron/electron-gn/_gclient_src_MbWcoF"' in User/electron/electron-gn failed; will
    retry after a short nap...

I'm working on the latest version of macOS and made sure to meet all requirements. Any ideas what the issue is and how to fix?

**Comment by 0x24D** [comment]
Hi @allstaralok, are you still looking at this issue or can I take a look at it?

**Comment by tharun208** [comment]
Hi , I like to work on this issue

**Comment by RnkC** [comment]
Hi! I would like to contribute to this issue.
