### ISSUE TITLE
Electron desktopCapturer.getSources().then is not a function

### ISSUE THREAD

**Issue by islalobo** [electron/electron#18120]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.14
* **Operating System:**
  * Windows 10 Pro

### Expected Behavior
Capture user audio input using desktopCapturer and MediaDevices getUserMedia

### Actual Behavior
Getting error: desktopCapturer.getSources().then is not a function

### To Reproduce / Additional Information
Developing an electron application on Windows 10 Pro version 1809. Our application has a browser window the renders when the user hits a hotkey combination. The browser window calls 'renderer.js'

    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="UTF-8">
        <title>Audio Visualizer</title>
      </head>
      <body>
    
        
    
        <script>
          require('./renderer.js')
        </script>
      </body>
    </html>

The `renderer.js` file handles interactions from the user within that browser window and attempts to capture user's audio using `desktopCapturer` using the screen (entire screen) as the source. 

I followed the documentation on electron docs, but we're getting an error `desktopCapturer.getSources().then is not a function`

This is the `renderer.js` file
```
desktopCapturer.getSources({ types: ['window', 'screen'] }).then(async sources => {
  for (const source of sources) {
    if (source.name === 'Entire screen') {
      try {
        const stream = await navigator.mediaDevices.getUserMedia({
          audio: {
            mandatory: {
             chromeMediaSource: 'desktop',
             chromeMediaSourceId: source.id 
            }
          },
          video: false
        })
        handleStream(stream)
      } catch (e) {
        handleError(e)
      }
      return
    }
  }
})

function handleStream (stream) {
  // create audio context and show audio visulaizaio
}

function handleError (e) {
  console.log(e)
}
```

Our code is basically a direct copy/paste from the example included in the electron docs. What are we missing that we are getting this error? 

I know there is a limitation on macOS that you have to create a stream in a different what (rather than navigator.mediaDevices.getUserMedia), but I don't think that limitation has anything to do with this error we're facing.

**Comment by codebytere** [comment]
@islalobo the documentation you followed appears to be the _latest_ documentation, not the documentation for the version at hand. If you check the documentation for the 4 line, you'll see that method takes a callback and does not return a Promise.

**Comment by islalobo** [comment]
Thank you! Over looked that detail. I have it working with a callback.

**Comment by efatsi** [comment]
In case someone else lands on this thread, this is the implementation that worked for me as of 12-3-2019. The callback you pass to `getSources` needs to ignore the first argument since the source code throws null in there for whatever reason.
```js
desktopCapturer.getSources({ types: ['window', 'screen'] }, (_ignore, sources) => {
  for (const source of sources) {
    if (source.name === 'Entire screen') {
      navigator.mediaDevices.getUserMedia({
        audio: false,
        video: {
          mandatory: {
            chromeMediaSource: 'desktop',
            chromeMediaSourceId: source.id,
            minWidth: 1280,
            maxWidth: 1280,
            minHeight: 720,
            maxHeight: 720
          }
        }
      }).then((stream) => {
        webRTC.initPeer(stream)
      }).catch((e) {
        console.log(e)
      })

      return
    }
  }
})
```

**Comment by paramsiddharth** [comment]
> In case someone else lands on this thread, this is the implementation that worked for me as of 12-3-2019. The callback you pass to `getSources` needs to ignore the first argument since the source code throws null in there for whatever reason.
> 
> ```js
> desktopCapturer.getSources({ types: ['window', 'screen'] }, (_ignore, sources) => {
>   for (const source of sources) {
>     if (source.name === 'Entire screen') {
>       navigator.mediaDevices.getUserMedia({
>         audio: false,
>         video: {
>           mandatory: {
>             chromeMediaSource: 'desktop',
>             chromeMediaSourceId: source.id,
>             minWidth: 1280,
>             maxWidth: 1280,
>             minHeight: 720,
>             maxHeight: 720
>           }
>         }
>       }).then((stream) => {
>         handleStream(stream)
>       }).catch((e) => {
>         handleError(e)
>       })
> 
>       return
>     }
>   }
> })
> ```

The first argument to the callback is most probably the error, which if `null`, means everything is working fine.
