### ISSUE TITLE
registerStringProtocol doesn't support custom headers

### ISSUE THREAD

**Issue by nornagon** [electron/electron#18125]
### Issue Details

* **Electron Version:**
  * 6.0.0-beta.1
* **Operating System:**
  * macOS 10.14.4
* **Last Known Working Electron version:**:
  * None

### Expected Behavior
Setting the `headers` key in the response callback for a `registerStringProtocol` handler should cause headers to be set in the response.

### Actual Behavior
The `headers` data is ignored.

### To Reproduce
https://gist.github.com/555971b5d659617d3bfabed2469bef60

### Additional Information
It looks like we just never set this data. We probably should.

**Comment by DeerMichel** [comment]
The docs also doesnt state that setting custom headers is possible for a string protocol. I wonder if theres a use case for them? The desired behavior of the gist can be achieved by using `mimeType`:

![image](https://user-images.githubusercontent.com/8472721/59637746-6b289400-910b-11e9-87be-c4e7502f6ecd.png)

Anyway, custom headers can be injected [here](https://github.com/electron/electron/blob/4dc38d39e98c5703a62790d1ba6ed4d4fb52fb81/atom/browser/net/url_request_string_job.cc#L95).

**Comment by nornagon** [comment]
String protocols are particularly handy during testing, and there are plenty of other headers than `Content-Type` that could be useful to set. We permit setting arbitrary headers for `registerStreamProtocol`, and it seems like an omission to disallow that for string protocols (since a string protocol is just a simpler version of stream protocols).

In fact, I don't see any particular reason we shouldn't implement string protocols on top of stream protocols, entirely in JS, rather than having separate C++ bindings for them. maybe cc @zcbenz for his thoughts?

**Comment by zcbenz** [comment]
The NetworkService-based protocol APIs have custom headers (and other options) implemented for all APIs, thanks to the new architecture, the new API implementations are both simpler and more powerful.

I'll have a PR for documenting all changes and goodies for NetworkService-based protocol API.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
