### ISSUE TITLE
'silent: true' for printing not working in version 5.

### ISSUE THREAD

**Issue by PWC-Michael** [electron/electron#18123]
Hey there

I have upgraded an app to version 5 as in the list of fixes was the silent printing bug, but the issue is still the same.

My code:
`printWindow.webContents.print({silent: true});`

Results in nothing happening at all. No errors thrown or anything. Changing it back to false, brings up the window to select the printer and then it prints perfectly fine. It's just the silent mode that doesn't work.

I am running this on Windows 10, with Node version 10.15.3. I can not try with a different OS as the printer only has drivers for Windows.

Many thanks,
Michael

**Comment by Naowut** [comment]
Same problem on Ubuntu with Electron 5.0.1
I would really like to see this issue fixed.

**Comment by flaticols** [comment]
Same on macOS Mojave

**Comment by gclooi** [comment]
Hi, I discover something interesting with this bug. I am running electron with window 10.

printWindow.webContents.print({ silent: false, printBackground: false}); -> Print Dialog Appeared

printWindow.webContents.print({ silent: false, printBackground: false, deviceName: 'PRINTER_NAME'}); -> Print Dialog NOT Appear

printWindow.webContents.print({ silent: true, printBackground: false}); ->Print Dialog NOT Appear & No Print Activity

printWindow.webContents.print({ silent: true, printBackground: false, deviceName: 'PRINTER_NAME'}); -> Print Dialog NOT Appear & No Print Activity

@sofianguy, is this issue possible relate to the "deviceName" that is not correct? 

Thanks for help and hope this issue can be fix soon.

**Comment by StijnVanBergen** [comment]
I struggled with this issue for hours before realising it might be Electron, not me. I've noticed the same behaviour. Downgraded to 4.*, still an issue. Upgraded to 6 beta, still an issue. After some more testing I've notices the same as @gclooi , I can only get any print activity when !silent and deviceName is not specified. (Tried on Mojave and Win10)

**Comment by hiteshambaliya** [comment]
I have also tested yesterday, exactly as @gclooi  written test cases, and same result.
My system Linux Debian (buster).
I was using electron 4.0.1 then upgraded to 4.2.2 but no result then upgraded to 5.0.0 & 5.0.1 but no success found.
Is there any way to do it.

**Comment by StvBB8** [comment]
@hiteshambaliya The only way I've found it to work for now is downgrading to Electron 3.

**Comment by hiteshambaliya** [comment]
Ok than you @StvBB8 . I will check it today and reply here whats happen on Linux Debian buster.

**Comment by cxyao** [comment]
I have the same problem. I tested under electron 4.2.2 and electron 5.0.2.  Only work for electron3, but under electron3, svg doesn't print correctly

**Comment by nornagon** [comment]
We would love some help in this area. None of the core Electron maintainers have significant experience with printing. If you're interested in tackling this bug (and/or any of the related printing issues), your help would be very welcome. I'd be happy to help you get set up with a development environment (start [here](/electron/electron/blob/master/docs/development/build-instructions-gn.md)).

**Comment by popod** [comment]
I've no skills for this.. sorry. But it seems that @brenca had some experiences with printing ?! He begin some works under the brenca/printing-fixes branch in the electron/electron repo.

**Comment by hiteshambaliya** [comment]
Cheers...
I have downgraded to Electron V3.1.10, and now its print() function working fine, if we set printer name in argument to print function then that printer get selected by default.

Thank a lot all.

**Comment by popod** [comment]
@codebytere For informations, it seems that @brenca had done some works to fix this issue in brenca/printing-fixes commit b9dcdcde255beacd246e000e98f45e0332d3819b.

**Comment by codebytere** [comment]
@popod ah ok, it looks like that's been stalled so i can try to see where it's at or pick it up from him! thanks for the bump :)

**Comment by agomezb** [comment]
hi, wich release will include this fix?

**Comment by popod** [comment]
@agomezb The backport which fix the "silent printing" issue is here #19038. Follow this PR to get notified when it will be merged into 5.x.x.

**Comment by EmadFani** [comment]
waiting for new here same problem

**Comment by misbeliever** [comment]
Still not working on 6.0.0-beta.13 where this PR is merged

**Comment by ArturoRis** [comment]
I tried 6.0.0-beta.13 and it's still not working for me too.

Actually, the callback it's called with `true` but the print doesn't start

**Comment by codebytere** [comment]
What platform? This is working for me on `v6.0.0-beta.13` on `macOS` as tested by https://github.com/popod/electron-quick-start/tree/print-bug-1

**Comment by vgribdev** [comment]
the silent printing works well form me in v6.0.0-beta, but it doesn't work if deviceName is provided

**Comment by misbeliever** [comment]
@vgribdev I found the same, that if deviceName is specified it will not work and callback never called, without deviceName it works and pints on default devioce

**Comment by maikonmatheus** [comment]
Tested v5.0.7 on Windows 10 and callback is never called with deviceName and, if I remove the deviceName the callback is called, but nothing is sent to the printer...

**Comment by ArturoRis** [comment]
@codebytere 
I tested `v6.0.0-beta.13` and `v5.0.7` on `Linux Mint 19.1`: on both the callback is called with `true` but nothing is sent to the printer, either I pass `deviceName` or not.  
I'll test with the repo you linked and I'll give you updates

**Comment by ibalaji777** [comment]
> the silent printing works well for me in v6.0.0-beta, but it doesn't work if deviceName is provided
same problem here, i downgraded 3.1.10,it works well.

**Comment by maikonmatheus** [comment]
> > the silent printing works well for me in v6.0.0-beta, but it doesn't work if deviceName is provided
> > same problem here, i downgraded 3.1.10,it works well.

No need to downgrade. Update to 8.2.0. It's working now.

**Comment by ibalaji777** [comment]
> > > the silent printing works well for me in v6.0.0-beta, but it doesn't work if deviceName is provided
> > > same problem here, i downgraded 3.1.10,it works well.
> 
> No need to downgrade. Update to 8.2.0. It's working now.

i will check,guys don't use 3.1.10  printer missing lot of content while print huge bug there.

**Comment by ibalaji777** [comment]
> What platform? This is working for me on `v6.0.0-beta.13` _and_ `v5.0.7` on `macOS` as tested by https://github.com/popod/electron-quick-start/tree/print-bug-1

These versions v6.0.0-beta.13 and v5.0.7 not responding with  deviceName.

**Comment by CoWayger** [comment]
Electron 13.1.9 also bugged. Prints ok when silent: false, no success with silent: true. Any workaround or fix?

**Comment by elAgala** [comment]
> Electron 13.1.9 also bugged. Prints ok when silent: false, no success with silent: true. Any workaround or fix?

Exactly the same here using Pop_OS! 21.04

**Comment by LucasHang** [comment]
Got silent: true working at Electron 13.2.1 with printBackground: false, although deviceName doesn't work and the default printer gets selected.

**Comment by i5o** [comment]
No luck on 13.1.6, 
```js
{
  silent: true,
  printBackground: false
 }

**Comment by ufocruz** [comment]
I make it work in linux putting the pageSize implicit.
The size values needs to be in micron.

This example is for a label of 5cm x 9,6cm:

`var options = {
    silent: true,
    margins: {
      marginType: 'none'
    },
    deviceName: impressora,
    pageSize: {
      height: 50000,
      width: 96000
    }
};`

**Comment by EcotechBrad** [comment]
"electron": "^13.0.0",
print({
    silent:true,
    margins: { marginType: 'none' },
    pageSize: { height: 60000, width: 40000 },
    dpi:200,copies:1,landscape:false,color:false,
  },
    printer receives a command when printing silent, but nothing is actually printed, setting device doesn't change behavior
