### ISSUE TITLE
How can I handle plist file to prepare submit App store

### ISSUE THREAD

**Issue by Younghun-Jung** [electron/electron#18137]
Electron version: ^3.0.8
Using Framework: Quasar v0.17

I finished my development work and then submit to App store but rejected.
I read tutorial from electron doc below again and in more detail.
[mac-app-store-submission-guide](https://electronjs.org/docs/tutorial/mac-app-store-submission-guide)

I got already provisioning profile and finished signing using electron-osx-sign plugin.

**Q1. Is it necessary to sign for native module when I use electron-osx-sign plugin?**
When I use electron-osx-sign plugin to sign app, I just use below command.
```
electron-osx-sign myApp.app
```
However, From electron docs said that native module used in App needs signature by using below command.
```
electron-osx-sign YourApp.app YourApp.app/Contents/Resources/app/node_modules/nativemodule/build/release/nativemodule
```

**Q2. How can I handle some .plist file?**
Electron Docs describes that I need to prepare child.plist, parent.plist and loginhelper.plist file with Info.plist.
I can find Info.plist in my app (by open package and content directory) after build.
Where are child, parent, loginhelper.plist files?? Do I create these files(where, when)?
Additionally, as I know, In order for the app to connect to the server or open socket, I need to add some authorizations into parent.plist like below. Is it right?
```
<key>com.apple.security.network.client</key>
<true/>
<key>com.apple.security.network.server</key>
<true/>
```
App store reviewers said that they cannot log in my app and it did not fetch next content.
(I'm using axios package to request authorization)
This problem seems to have occurred because I did not prepare .plist files.

**Q3. Signature app using script**
Electron Docs said that I need to sign app with below script.
I cannot understand How I can sign using below script to sign app.
Where can I execute below script in terminal?(which path?)
```
#!/bin/bash

# Name of your app.
APP="YourApp"
# The path of your app to sign.
APP_PATH="/path/to/YourApp.app"
# The path to the location you want to put the signed package.
RESULT_PATH="~/Desktop/$APP.pkg"
# The name of certificates you requested.
APP_KEY="3rd Party Mac Developer Application: Company Name (APPIDENTITY)"
INSTALLER_KEY="3rd Party Mac Developer Installer: Company Name (APPIDENTITY)"
# The path of your plist files.
CHILD_PLIST="/path/to/child.plist"
PARENT_PLIST="/path/to/parent.plist"
LOGINHELPER_PLIST="/path/to/loginhelper.plist"

FRAMEWORKS_PATH="$APP_PATH/Contents/Frameworks"

codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Electron Framework"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Libraries/libnode.dylib"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper.app/Contents/MacOS/$APP Helper"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper.app/"
codesign -s "$APP_KEY" -f --entitlements "$LOGINHELPER_PLIST" "$APP_PATH/Contents/Library/LoginItems/$APP Login Helper.app/Contents/MacOS/$APP Login Helper"
codesign -s "$APP_KEY" -f --entitlements "$LOGINHELPER_PLIST" "$APP_PATH/Contents/Library/LoginItems/$APP Login Helper.app/"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$APP_PATH/Contents/MacOS/$APP"
codesign -s "$APP_KEY" -f --entitlements "$PARENT_PLIST" "$APP_PATH"

productbuild --component "$APP_PATH" /Applications --sign "$INSTALLER_KEY" "$RESULT_PATH"
```
I'm sorry that I'm not familiar with English.
Thanks.

**Comment by codebytere** [comment]
cc @sethlu

**Comment by sethlu** [comment]
Q1: When using `electron-osx-sign`, you'll only need to provide paths to native modules if there happen to be any undetected ones during code signing.

Q2: The child, parent and loginhelper plists are entitlement files. We use them to enable app sandbox and other security things. They are not copied to the app bundle so you can only find `Info.plist`.

Q3: You can run that script from anywhere, but need to make sure that the paths are pointing to the correct app bundle.

---

Alternatively, you can try out `electron-osx-sign` to automate code signing. And here's a short tutorial for you to get started: https://mintkit.net/electron-userland/electron-osx-sign/guide/

**Comment by codebytere** [comment]
Closing as this has been addressed!
