### ISSUE TITLE
Allow to retrieve window tabbingIdentifier at runtime

### ISSUE THREAD

**Issue by bpasero** [electron/electron#18138]
Electron supports macOS sierra native tabs when creating windows, however in order to properly restore an arrangement of multiple groups of tabs, we would need to get this information at runtime before closing the application.

**Comment by bpasero** [comment]
@codebytere thanks for the change, but I am not able to restore windows into the same tab group. See https://github.com/electron/electron/issues/40529

**Comment by Jennjenn88** [comment]
extensions.showRecommendationsOnlyOnDemand
