### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by msudgh** [electron/electron#18139]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 5.0.0
* **Operating System:** Arch Linux

### Expected Behavior

I'd expect to access `process` object in my renderer process

### Actual Behavior

Chrome dev tools throw `ReferenceError` while accessing to `process` object.
```js
Uncaught ReferenceError: process is not defined
```

**Comment by codebytere** [comment]
@msudgh `nodeIntegration` is turned off by default in `5`, so you'll need to enable it via:
```
const { BrowserWindow } = require('electron')
let win = new BrowserWindow({
  webPreferences: {
    nodeIntegration: false
  }
})
```
which we caution against, or enable it via preload script.

**Comment by msudgh** [comment]
@codebytere Thanks. it'd be better to update docs. this functionality existed in previous versions.

**Comment by codebytere** [comment]
@msudgh this information was presented both in release notes and in breaking change documentation leading up to and including the stable release :)

**Comment by Raghav9o9** [comment]
Hello I am also getting this error and still it is not fixed for me pls help me.

**Comment by Raghav9o9** [comment]
Thanks it worked for me, you don't that how happy now I am thank you very very much...

**Comment by phamkimtho** [comment]
Thank you very much. Now I can solved my problem!

const { BrowserWindow } = require('electron')
let win = new BrowserWindow({
  webPreferences: {
    nodeIntegration: true
  }
})

**Comment by swapnilvaidankar** [comment]
> @msudgh `nodeIntegration` is turned off by default in `5`, so you'll need to enable it via:
> 
> ```js
> const { BrowserWindow } = require('electron')
> let win = new BrowserWindow({
>   webPreferences: {
>     nodeIntegration: true
>   }
> })
> ```
> 
> which we caution against, or add it via preload script.

Where to add this above code?

**Comment by schmorrison** [comment]
> > @msudgh `nodeIntegration` is turned off by default in `5`, so you'll need to enable it via:
> > ```js
> > const { BrowserWindow } = require('electron')
> > let win = new BrowserWindow({
> >   webPreferences: {
> >     nodeIntegration: true
> >   }
> > })
> > ```
> > 
> > 
> > which we caution against, or add it via preload script.
> 
> Where to add this above code?

In your electron apps `main.js` file, check the project `package.json` file -- the `"main"` parameter shows the files path

**Comment by cawoodm** [comment]
Note `contextIsolation: false` now replaces `nodeIntegration: true`.

**Comment by raphael10-collab** [comment]
@codebytere While keeping nodeIntegration to false how to still access process object?

**Comment by eXhumer** [comment]
> Note `contextIsolation: false` now replaces `nodeIntegration: true`.

I needed to use both, using only `contextIsolation: false` / `nodeIntegration: true` doesn't fix the issue. This affects the [quick start guide](https://www.electronjs.org/docs/tutorial/quick-start#create-the-main-script-file) as only `nodeIntegration: true` was mentioned there.

**Comment by fortypercenttitanium** [comment]
> > Note `contextIsolation: false` now replaces `nodeIntegration: true`.
> 
> I needed to use both, using only `contextIsolation: false` / `nodeIntegration: true` doesn't fix the issue. This affects the [quick start guide](https://www.electronjs.org/docs/tutorial/quick-start#create-the-main-script-file) as only `nodeIntegration: true` was mentioned there.

THANK YOU SO MUCH! I've been spinning my wheels all day trying to figure out why not even following electron's own quick start guide was working for me!

**Comment by ohmygod481999** [comment]
Me too, quick start doesn't work. Uncaught ReferenceError: process is not defined x 3

**Comment by hbieler** [comment]
I found same problem - just by doing the beginners samples.

**Comment by rhllor** [comment]
mee too, i follow quickstart but i got "Uncaught ReferenceError: process is not defined". 

![image](https://user-images.githubusercontent.com/1021565/110780980-9b13b580-8265-11eb-8ccb-e2499995271d.png)

node v14.16.0
npm v6.14.11

I missing some requirement?

**Comment by ghasseminia** [comment]
update your main.js as follows:
`function createWindow () {
  const win = new BrowserWindow({
    width: 600,
    height: 600,
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false
    }
  })`

**Comment by hbieler** [comment]
Thanks for quick help :-)

**Comment by ghasseminia** [comment]
> Thanks for quick help :-)
> this solved the issue in the simple sample ;-)
No problem!

**Comment by nilslindemann** [comment]
@codebytere 

> @msudgh this information was presented both in release notes and in breaking change documentation leading up to and including the stable release :)

But it was not, and the latest breaking change ( `contextIsolation: false` ) is not in the [official docs](https://www.electronjs.org/docs/tutorial/quick-start#create-the-main-script-file).

**Comment by soymikey** [comment]
> > Note `contextIsolation: false` now replaces `nodeIntegration: true`.
> 
> I needed to use both, using only `contextIsolation: false` / `nodeIntegration: true` doesn't fix the issue. This affects the [quick start guide](https://www.electronjs.org/docs/tutorial/quick-start#create-the-main-script-file) as only `nodeIntegration: true` was mentioned there.

thank you so much , i have created so many new project from scratch until i have seen you answer. cheers mate~~

**Comment by CoderNinja123** [comment]
Wow. Works like a charm. I would request ElectronJS Team to please update the docs and add this, or totally remove the need to use `contextIsolation` **with** `nodeIntegration` (*Just keep one of them!!*).

**Comment by visionari-labs** [comment]
I thought for security purposes, we should disable nodeIntegration and enable contextIsolation... I ran into this issue when I tried to run a packaged Electron app on my other Macbook. Is this safe to run on the main window?

**Comment by arnoldmartinez** [comment]
I did resolve putting contextIsolation to false.

// 1. import electron objects
const { app, BrowserWindow } = require('electron');

// 2. reserve a reference to window object
let window;

// 3. wait till application started
app.on('ready', () => {
    // 4. create a new window
    window = new BrowserWindow({
        width: 800,
        height: 600,
        webPreferences: {
            nodeIntegration: true,
            contextIsolation: false
        }
    });
    // 5. load window content
    window.loadFile('index.html');
});

**Comment by m4xlmum** [comment]
> I did resolve it putting contextIsolation to false.
> 
> // 1. import electron objects const { app, BrowserWindow } = require('electron');
> 
> // 2. reserve a reference to window object let window;
> 
> // 3. wait till application started app.on('ready', () => { // 4. create a new window window = new BrowserWindow({ width: 800, height: 600, webPreferences: { nodeIntegration: true, contextIsolation: false } }); // 5. load window content window.loadFile('index.html'); });

It done, Thanks.  From Electron v18.0.1
