### ISSUE TITLE
electron 5.0.0 can not load webview

### ISSUE THREAD

**Issue by 758915145** [electron/electron#18145]
### Issue Details
相同的代码，我使用 5.0.0 版本时无法加载 webview，但是我换成 4.1.4 版本就正常了。
With the same code, I couldn't load WebView when I used version 5.0.0, but it was normal for me to switch to version 4.1.4.

#### main.js
``` javascript
const { app, BrowserWindow, session } = require('electron')
function createWindow () {
  let win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true
    }
  })
  win.webContents.openDevTools()
  win.loadFile('index.html')
}
app.on('ready', createWindow)
```
#### index.html
``` html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Webview</title>
  <style>
    webview{
      display:inline-flex;
      width:300px;
      height:200px;
      background-color:#DDD;
    }
  </style>
</head>
<body>
<h1>Hello World!</h1>
We are using Node.js <script>document.write(process.versions.node)</script>,
Chromium <script>document.write(process.versions.chrome)</script>,
and Electron <script>document.write(process.versions.electron)</script>.
  <webview src="webview.html" id="myWebview"></webview>
</body>
</html>
```

#### webview.html
``` html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Webview</title>
  </head>
<body>
  <h1>我就看看webview能不能用</h1>
</body>
</html>
```

#### 5.0.0
![5 0 0](https://user-images.githubusercontent.com/17400918/57174006-4386b080-6e6a-11e9-8a49-1c340f56cff8.png)

### 4.1.4
![4 1 4](https://user-images.githubusercontent.com/17400918/57174041-cf004180-6e6a-11e9-94e0-37799498caf6.png)

### 5.0.0 with file:// prefix
![5 0 0-with](https://user-images.githubusercontent.com/17400918/57174052-08d14800-6e6b-11e9-9677-e3b57fb9fde2.png)

**Comment by alongsea2** [comment]
和我遇到的一样,是 bug 吗?

**Comment by MarshallOfSound** [comment]
You now need to explicitly enable `webviewTag` in your `webPreferences` object.

See https://github.com/electron/electron/blob/master/docs/api/breaking-changes.md#new-browserwindow-webpreferences-

**Comment by Haemp** [comment]
@MarshallOfSound Can we please get this into the webview docs?
