### ISSUE TITLE
Focus of the window lost after selection with Alt keyword pressed

### ISSUE THREAD

**Issue by ficristo** [electron/electron#18151]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  5.0.1
* **Operating System:**
  * Windows 10 
* **Last Known Working Electron version:**
  * Before electron 5 the Alt keyword didn't focus the menu bar, so it worked

### Expected Behavior

When you use mouse to select something with Alt key pressed the focus should remain in the window.

### Actual Behavior

The focus goes to the menubar.

### To Reproduce

Just start the electron-quick-start app and try to select something with the Alt button pressed. And then release the Alt button.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by ficristo** [comment]
I'm still able to reproduce with electron 8.0.1

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
