### ISSUE TITLE
Attach proxies with user:pass authentication to webview

### ISSUE THREAD

**Issue by Johnnycus** [electron/electron#18157]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
How can I attach a proxy with auth (user:password) on webview element? I was able to attach proxies that don't require authentication with session.setProxy() method, but can I use proxies with login and password too? .setProxy({proxyRules: 'https://user:password@ip:port' }) doesn't work.

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
