### ISSUE TITLE
How Can I hide some script from devtools

### ISSUE THREAD

**Issue by wuzhiming** [electron/electron#18163]
Hello,
I want to hide some scripts to show from devtools, let the devtools not return the contents of this script,I build a new version of electron, but I can find where to control this.
can anyone help?
![image](https://user-images.githubusercontent.com/6093737/57188215-7ba2f780-6f2d-11e9-9314-c20c4c5b40d8.png)

**Comment by nornagon** [comment]
We don't support hiding scripts from devtools.

**Comment by wuzhiming** [comment]
@nornagon could you tell me where the code is,  I can modify it by myself?☺
