### ISSUE TITLE
electron.screen doesn't exist in render process in electron 6.0.0-beta.1

### ISSUE THREAD

**Issue by KochiyaOcean** [electron/electron#18168]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.0-beta.1
* **Operating System:**
  * Windows
* **Last Known Working Electron version:**:
  * 5.0.1

### Expected Behavior
electron.screen should exist in render process 

### Actual Behavior
electron.screen doesn't exist in render process 

### To Reproduce
run `require('electron').screen` and will return undefined

### Screenshots
![image](https://user-images.githubusercontent.com/8194131/57197902-800bf680-6fa7-11e9-9a3b-488b4932b2e3.png)

**Comment by shiftkey** [comment]
This is a planned breaking change for v6:

https://github.com/electron/electron/blob/82bb6d4ccf2a6609b116a8a7df9ea7db796aa55d/docs/api/breaking-changes.md#electronscreen-in-renderer-process

```
// Deprecated
require('electron').screen
// Replace with
require('electron').remote.screen
```

**Comment by KochiyaOcean** [comment]
@shiftkey Thank you for explanation
