### ISSUE TITLE
Exiting Fullscreen mode for Embedded Content does not work.

### ISSUE THREAD

**Issue by smithalan92** [electron/electron#18188]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
5.0.0
* **Operating System:**
MacOS 10.13.6 / Windows 10
* **Last Known Working Electron version:**:
Electron v2.0.8

### Expected Behavior
Exiting fullscreen content ( ie. A Youtube Video displayed in a iframe ) should return the to app.
### Actual Behavior
Video size shrinks, but screen stays black , see https://cl.ly/f7af08d44619

### To Reproduce
main.js

```
const {app, BrowserWindow} = require('electron')
const path = require('path')
const url = require('url')

let window = null

// Wait until the app is ready
app.once('ready', () => {
  // Create a new window
  window = new BrowserWindow({
    // Set the initial width to 500px
    width: 600,
    // Set the initial height to 400px
    height: 600,
    // Don't show the window until it's ready, this prevents any white flickering
    show: false,
    webPreferences: {
      webSecurity: false,
      nodeIntegration: true,
      allowRunningInsecureContent: true,
    },
  })

  window.loadURL(url.format({
    pathname: path.join(__dirname, 'index.html'),
    protocol: 'file:',
    slashes: true
  }))

  window.once('ready-to-show', () => {
    window.show()
  })
})

```

index.html

```
<!DOCTYPE html>
<html>
</head>
<body>
  <div>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/eBpxovL0zng" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
    </iframe>
  </div>
  </body>
</html>
```

### Screenshots
Screen recording https://cl.ly/f7af08d44619

**Comment by adill** [comment]
We're having this issue as well on 5-0-x and 6-0-x. I have not investigated deeply but it appears that the BrowserWindow resizes to fullscreen and simply refuses to resize back after you exit fullscreen.

**Comment by btzr-io** [comment]
Similar issue, probably related to this, when I press `F11` the `browserWindow` leaves the full-screen mode but the embedded content (video-player) is still displayed on the full screen (electron 4.1.0 ).

Not sure if this is fixed already on `5-0-x` or `6-0-x`.

Looks like electron ignores the `html5-exit-fullscreen` event, so the work around is to force this event when the `browserWindow` leaves the fullscreen mode:

```JS
// Force exit mode for html5 fullscreen api
remote.getCurrentWindow().on('leave-full-screen', event => {
  document.webkitExitFullscreen();
});
```
