### ISSUE TITLE
Is it safe to use webview tag in Electron?

### ISSUE THREAD

**Issue by Qrysto** [electron/electron#18187]
Sorry I know that this is not the ideal place to ask questions, but I have tried to post on stackoverflow, Atom's discuss forum, also sent an email to info@electronjs.org, all have been a few weeks already and I've received absolutely no answers. So I'm posting this question here hoping someone can help me answer and then quickly close the issue. My question was:

In [Electron's `webview` documentation](https://electronjs.org/docs/api/webview-tag), there is a warning:

> Electron's webview tag is based on Chromium's webview, which
> is undergoing dramatic architectural changes. This impacts the
> stability of webviews, including rendering, navigation, and event
> routing. We currently recommend to not use the webview tag and to
> consider alternatives, like iframe, Electron's BrowserView, or an
> architecture that avoids embedded content altogether.

It recommends not to use `webview`, however none of the alternative such as `iframe` or `BrowserView` can fit my use case as well as `webview` does. So I wonder if the warning above recommends not to use `webview` **only** because the API and architecture can change in the future or is there any known security issues with `webview` right now? And in general, what I care the most is: Is it **safe** to use `webview` (in term of security) right now?

**Comment by nornagon** [comment]
Thanks for reaching out!

I'm closing this issue as it does not represent a task that can be completed, but please feel free to discuss the topic here.

**Comment by PalmerAL** [comment]
@Qrysto Webviews run in a separate process and have node integration disabled by default, so there shouldn't be any major reason why they're less secure than the alternatives. You'll definitely want to use the `webPreferences` option to enable sandboxing, disable the remote module, enable context isolation, etc. ([example for BrowserView](https://github.com/minbrowser/min/blob/1d45be37e06ffef2d520a012c6cfd0eb56e86297/js/webviews.js#L167-L174)).

However, there's a fair number of bugs in webviews right now, some recent examples:
https://github.com/electron/electron/issues/17890
https://github.com/electron/electron/issues/18019
https://github.com/electron/electron/issues/18177

Most of these aren't present in BrowserView, so you definitely want to use that instead if it's at all possible to do so.

**Comment by Qrysto** [comment]
Thanks for your answer! Security is my primary concern so it's good to get a confirmation that the warning was not related to security.

**Comment by littlecold233** [comment]
> @Qrysto Webviews run in a separate process and have node integration disabled by default, so there shouldn't be any major reason why they're less secure than the alternatives. You'll definitely want to use the `webPreferences` option to enable sandboxing, disable the remote module, enable context isolation, etc. ([example for BrowserView](https://github.com/minbrowser/min/blob/1d45be37e06ffef2d520a012c6cfd0eb56e86297/js/webviews.js#L167-L174)).
> 
> However, there's a fair number of bugs in webviews right now, some recent examples:
> #17890
> #18019
> #18177
> 
> Most of these aren't present in BrowserView, so you definitely want to use that instead if it's at all possible to do so.

Is there a plan to fix the bugs in webview? I want to know because webview is important in my project. 

And  it's too hard to migrate all webviews to BrowserView

**Comment by raphael10-collab** [comment]
Are all the already known `webviews bugs` solved?

**Comment by raphael10-collab** [comment]
@nornagon 

May be I reached a wrong webpage, but it looks like that `chome.webviewTag` is already a `deprecated API` for `Google Chrome` : https://developer.chrome.com/docs/extensions/reference/webviewTag/   . 

If this is the case,  why `webviewTag` is still deployed in Electron ?
