### ISSUE TITLE
cannot open link in external default os browser when using electron 5.0.1

### ISSUE THREAD

**Issue by dhanyn10** [electron/electron#18186]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.1
* **Operating System:**
  * macOS 10.13 High Sierra (64-bit)
  * Windows 10 Home
  * Linux Mint 19 Cinnamon
* **Last Known Working Electron version:**:
  * 4.1.4

### Expected Behavior
when i click a link it will open in a new tab in default os browser.

### Actual Behavior
when i click a link, it just process visit the link inside application.

### To Reproduce
you can test it in my own testing repository here:
```
https://github.com/dhanyn10/electron-example
```
clone above repository. the navigate to folder `open-all-link-to-default-browser`
```sh
$ cd open-all-link-to-default-browser
$ npm i
$ npm start
``` 
then click to any link you want to test.
Try with two version of electron, Change electron version in `package.json` with version `4.1.4` and `5.0.1`

### Screenshots

![electron-problem](https://user-images.githubusercontent.com/11478316/57268625-b7b19600-70ae-11e9-88a6-f6f3e7d5d906.PNG)

**Comment by vladimiry** [comment]
You can't access stuff from main process with disabled node integration (disabled by default since electron@5) but you can do that in preload script. So try changing:
```
mainWindow = new BrowserWindow({width: 800, height: 600})
```
to:
```
mainWindow = new BrowserWindow({width: 800, height: 600, webPreferences: {preload: path.join(__dirname, 'renderer.js')}})
```

**Comment by dhanyn10** [comment]
nice, thank you for your solution @vladimiry

**Comment by dhanyn10** [comment]
@vladimiry i've tested your solution, it worked. But in my other project it cause another problem. try visit my repository here [multiple file manager](https://github.com/dhanyn10/multiple-file-manager)

**Comment by vladimiry** [comment]
@sofianguy, in my opinion, there is no bug here but a question for a resource like StackOverflow.

**Comment by dhanyn10** [comment]
solved by enabling node integration in electron 5
```js
mainWindow = new BrowserWindow({
//.....
        webPreferences:
        {
            nodeIntegration: true
        }
    })
```
