### ISSUE TITLE
Stop falling back sans-serif to SimSun and (P)MingLiu

### ISSUE THREAD

**Issue by be5invis** [electron/electron#18193]
SimSun and PMingLiu are **serif fonts**, they should not be used as the fallback font for sans-serif families.

![image](https://user-images.githubusercontent.com/240091/57309869-6390cb00-711b-11e9-82cc-92a942007a07.png)

ref. https://www.zhihu.com/question/323244457/answer/675834621

**Comment by nornagon** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by ShikiSuen** [comment]
It is meaningless to ask more detailed information about this issue. In this case you can assume that this issue happens with the latest public build of Electron. I personally know @be5invis and he surely has his reason not to fill out your sophistic template which is too stupid to this issue.

**Comment by ShikiSuen** [comment]
Additionally, @be5invis works in Microsoft and is making efforts to improve the CJK font experience of Microsoft products. He surely knows that the CJK font fallback behavior of popular softwares on Microsoft Windows can directly affect the user experience of Microsoft products in Simplified Chinese / Traditional Chinese / Japanese / Korean languages.

Behaviors of misusing types of UI font for a language is making trouble to the users who use this language. Chromium currently does this stupidly by prioritizing PMingLiU & SimSun (serif Chinese fonts) above Micrsoft YaHei and JhengHei (sans-serif Chinese fonts) [1]. To be frank, using "sans-serif" is enough in current Windows 10 builds. Is Electron still gonna do the same stupid thing?

[1] See: https://cs.chromium.org/chromium/src/third_party/blink/renderer/platform/fonts/win/font_fallback_win.cc

```
  static const UChar* const kSimplifiedHanFonts[] = {L"simsun",
                                                     L"Microsoft YaHei", 0};
  static const UChar* const kTraditionalHanFonts[] = {L"pmingliu",
                                                      L"Microsoft JhengHei", 0};
```

**Comment by nornagon** [comment]
This issue was re-opened as #18197, please continue discussion there.
