### ISSUE TITLE
Requiring node modules electron (5.0.0) 

### ISSUE THREAD

**Issue by EbramTawfik** [electron/electron#18204]
I'm building a desktop application using Angular and electron.

I started using electron v4.1.3 and I was able to require node modules in the Angular of the application, for example in the home.ts file by using:
```
import { Component } from '@angular/core';
import * as Fs from 'fs';


@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage {

    ngOnInit () {
        console.log ((<any> window).require ("fs"));
        //   or like this 
        //  const fs: typeof Fs = window['require']('fs');
    }
}
```
and this is what i get:

![image](https://user-images.githubusercontent.com/12788360/57342002-72fb1e80-70f1-11e9-869c-748751e86a08.png)

As you can see I can access all fs methods, so I can read, write, copy files and whatever else.

Now I have installed electron v5.0.0, I created the same application but I get an error when I try to require fs module in the ngOnInit method:

![image](https://user-images.githubusercontent.com/12788360/57342017-84442b00-70f1-11e9-965c-cf1ca67b9321.png)
How can I fix this?  thank you!

**Comment by MarshallOfSound** [comment]
`nodeIntegration` is now disabled by default in `5.0.0` as per our breaking changes document.

https://github.com/electron/electron/blob/master/docs/api/breaking-changes.md#planned-breaking-api-changes-50

and the release notes

https://github.com/electron/electron/releases/tag/v5.0.0
