### ISSUE TITLE
Bug: Kiosk mode still allows Cmd+Tab

### ISSUE THREAD

**Issue by pjebs** [electron/electron#18207]
OS: MacOSX 10.13.6 (High Sierra)
Electron Version: v5.0.1

When a window is in kiosk mode, currently it disables Cmd+Space (spotlight), Cmd+W (Close window) etc.

With a global accelerator, I can block off Cmd+Q (quit application).

A true kiosk mode should also prevent Cmd+Tab. Currently it doesn't do that so a user can easily switch to another application. Therefore it's not a kiosk mode.

**Comment by pjebs** [comment]
These are the features of kiosk mode:

```
func KioskMode(){  
        let presOptions: NSApplication.PresentationOptions = [  
             .hideDock  
           // .autoHideMenuBar,           // Menu Bar appears when moused to.  
           // .disableAppleMenu,          // All Apple menu items are disabled.  
           // .disableProcessSwitching,      // Cmd+Tab UI is disabled. All Exposé functionality is also disabled.  
           // .disableForceQuit,             // Cmd+Opt+Esc panel is disabled.  
           // .disableSessionTermination,    // PowerKey panel and Restart/Shut Down/Log Out are disabled.  
           // .disableHideApplication,       // Application "Hide" menu item is disabled.  
          //  .autoHideToolbar,  
          //  .fullScreen  
        ]  
        let optionsDictionary = [NSView.FullScreenModeOptionKey.fullScreenModeApplicationPresentationOptions: presOptions]  
        ExamFullPage.contentView?.enterFullScreenMode(NSScreen.main!, withOptions: optionsDictionary)  
    }  
      
    @IBAction func EnterKioskByBtn(_ sender: Any) {  
        KioskMode()  
    }  
```

From: https://forums.developer.apple.com/thread/111064

**Comment by miniak** [comment]
@pjebs We are setting the [NSApplicationPresentationDisableProcessSwitching](https://developer.apple.com/documentation/appkit/nsapplicationpresentationoptions/nsapplicationpresentationdisableprocessswitching?language=objc) flag. It works for me on macOS 10.14.4.

**Comment by pjebs** [comment]
@miniak I don't know what to say. I have a slightly earlier OS and it doesn't work for me.

**Comment by pjebs** [comment]
I'll try and test it on someone elses computer.

**Comment by pjebs** [comment]
This should be added to docs for Windows (Kiosk mode for Windows only works on Win 10 Enterprise Ed):

https://www.microsoft.com/developerblog/2018/04/17/packaging-electron-app-managed-distribution-across-devices/

https://github.com/syedhassaanahmed/kiosk-demo-electron

**Comment by pjebs** [comment]
This should be added to docs for Windows (Kiosk mode for Windows only works on Win 10 Enterprise Ed):

https://www.microsoft.com/developerblog/2018/04/17/packaging-electron-app-managed-distribution-across-devices/

https://github.com/syedhassaanahmed/kiosk-demo-electron

**Comment by pjebs** [comment]
I set `win.setVisibleOnAllWorkspaces(true)` and `alwaysOnTop: true`  (in fact I made it `alwaysOnTopScreensaver) and it still doesn't work. I can still Cmd+Tab to transfer the electron window to it's own workspace.

**Comment by pjebs** [comment]
@miniak Can you send me your code snippet where you claim it is working. It'd be interesting to find out if it's my OS.

**Comment by maxhewett** [comment]
@pjebs do you call 
  `app.dock.hide()`
anywhere? I removed that and it was no longer an issue.

**Comment by pjebs** [comment]
@maxhewett Thank you. You solved the issue for me.

@miniak On MacOS, kiosk mode does not work when `app.dock.hide()` is applied.

I don't know if this is a macOS limitation or a electron issue. Its should be at least documented.

**Comment by pjebs** [comment]
As a temp fix, when I need to show the kiosk screen, I temporarily enable the dock and then disable it again when it's time to hide the screen.

**Comment by maxime-guyot** [comment]
It's possible to quit kiosk mode with Command+Option+Space (Open a Finder window with the search field selected)
https://support.apple.com/sq-al/guide/mac-help/mh26783/10.14/mac/10.14

**Comment by pjebs** [comment]
@maxime-guyot I see that. :-(

**Comment by pjebs** [comment]
Just when your kiosk mode Full screen window is about to pop up, of you click Cmd+Tab, you can also bypass it.

**Comment by maxime-guyot** [comment]
I found a partial solution to prevent quit kiosk mode :
```javascript
win.on("blur", function() {
  this.show();
});
```

**Comment by pjebs** [comment]
Good workaround!

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by pjebs** [comment]
Still applies V8.01

**Comment by maxime-guyot** [comment]
v6.1.7 in my case (mas compatibility)

reproduce :
https://github.com/electron/electron/issues/18207#issuecomment-573463010

**Comment by RoderickQiu** [comment]
still applies now, v7.1.1 in my case

**Comment by RoderickQiu** [comment]
> It's possible to quit kiosk mode with Command+Option+Space (Open a Finder window with the search field selected)
> https://support.apple.com/sq-al/guide/mac-help/mh26783/10.14/mac/10.14

```
    win.on('blur', () => {
                win.hide();
                win.setKiosk(false);
                win.moveTop();
                win.focus();
                win.setKiosk(true);
                win.show();
                win.focus();
    });
```
This works for me in the case.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
