### ISSUE TITLE
Electron windows causing repaint issues when DWM composition disabled

### ISSUE THREAD

**Issue by CharlieHess** [electron/electron#1821]
- Log on to a Windows 7 machine
- Switch your theme to Windows Basic or Windows Classic (this has the side-effect of disabling Aero's DWM composition)
- Launch an Electron app
- Switch to another app window
- The other window fails to repaint:

![window repaint issue](https://cloud.githubusercontent.com/assets/1865957/7892783/3bd6c34a-060c-11e5-8746-3815d26d6590.PNG)

This occurs with almost every app that I've tried, so it seems like something funky with the Electron window. It may or may not require the presence of a `webview` tag; I haven't isolated that yet. Until now we've been advising users to switch to an Aero theme (this fixes the problem, but is undesirable for many).

**Comment by CharlieHess** [comment]
Also an issue with any remote desktop session, since that typically disables DWM composition.

**Comment by jakebauer** [comment]
This is horrendous on a window sitting above outlook. The only real fix is to maximize and minimize slack, since there's so many panes in outlook you have to swirl your mouse pointer around in to clear the screen of repaint artifacts. Disabling gpu in both outlook and slack doesn't change anything either.

Sorry for the obfuscation in the images, I've provided extra to show the detail just in case.

![2015-05-16 00_45_46](https://cloud.githubusercontent.com/assets/12820558/8070076/9fd852d2-0eb3-11e5-81c9-fef652f013f2.png)
![2015-06-09 14_32_40-2015-05-17 22_01_40](https://cloud.githubusercontent.com/assets/12820558/8070214/a58e30f6-0eb4-11e5-94aa-7a50a44f3082.png)
![2015-06-09 14_30_06-2015-05-22 10_27_52](https://cloud.githubusercontent.com/assets/12820558/8070215/a5911546-0eb4-11e5-86e7-4f020c397427.png)
![2015-06-09 14_34_43-2015-05-22 11_31_11](https://cloud.githubusercontent.com/assets/12820558/8070246/d28ec9c6-0eb4-11e5-8169-7db70b430d0f.png)

**Comment by jakebauer** [comment]
replaced with https://github.com/rfgamaral/SlackUI - works flawlessly

**Comment by zcbenz** [comment]
@CharlieHess Does this happen for the default app? I tried with v0.29.1 on a fresh Window 7 image with basic theme, and the default app seems to work well.

**Comment by CharlieHess** [comment]
@zcbenz I think it's exclusive to the `webview` tag.

**Comment by fxpoet** [comment]
+1 same issue when css animation used.

**Comment by LuisPeregrina** [comment]
+1 Same problem with Slack.

**Comment by myself248** [comment]
+1, I just reported this to Slack and they said it's a bug in Electron. Switching to an Aero theme to work around this would suck. Thanks in advance to whoever's working on this!

**Comment by paulcbetts** [comment]
@myself248 If you upgrade to any OS newer than Windows 7, you can enable Classic Theme and still not hit this bug. Highly encouraged!

**Comment by myself248** [comment]
![slackatomwindowimprint](https://cloud.githubusercontent.com/assets/4481636/13720511/cfa35cba-e7d8-11e5-9b0a-fab1a90e859b.png)

Imprinting issue is reproducible here too, clicking (in the screenshot shown) on the cmd window, then slack, then drobo dashboard. Happens about 1 time in 4. Win7, non-Aero theme, Nvidia NVS 5400M driver version 345.35. 

Just as soon as any OS newer than 7 (I note that you don't say "better than") gets the thumbs-up from corporate IT, I'll have a workaround! :)

**Comment by myself248** [comment]
![slackatomwindowrepaintbordlerless](https://cloud.githubusercontent.com/assets/4481636/13732440/3822eb8a-e959-11e5-8137-52bc445e6f02.png)

Got a new and hilarious manifestation: sometimes when switching back to the window, it's drawn without borders. I can just alt-tab back and forth between Spotify and Slack a dozen times, and 1 or 2 of those times, Slack is drawn without a title bar or window borders, as seen here.

Interestingly enough, if I click where the title bar should be, I can move the window. And if I hover over where borders and corners should be, I get the resize cursor, and I can drag to resize the window. After that operation, the window is redrawn completely, 100% of the time.

**Comment by Joshua-Smith** [comment]
I'm seeing an issue on Windows 7 where updating the title bar doesn't cause a repaint of the title bar. (I think it's the same problem this person is seeing: https://discuss.atom.io/t/title-bar-doesnt-update-when-switching-tabs/16429) The correct title is shown if I hover over the icon in the taskbar, and resizing the window makes it repaint. Two questions:
1. Is this the same issue being described here, or should I create a new issue?
2. Is there a workaround I can use to force a title bar repaint?

**Comment by Ben3eeE** [comment]
1. Yes it should be the same issue. If you want you can verify this by changing to the default Windows 7 theme and testing the repaint of the title bar.

**Comment by Joshua-Smith** [comment]
Confirmed: When I changed the theme, it solved the problem. Unfortunately, I can't tell my users to change their theme, so is there any other workaround I could implement in my code?

**Comment by paulcbetts** [comment]
None of the Electron developers are working on this, but will accept a PR for it

**Comment by TimvdEijnden** [comment]
We need to use transparent BrowserWindows in our application. This doesn't work with certain Windows settings. But we're able to detect these settings and show a warning to the user with instructions to fix it. We detect it by checking the Registry for certain values:

```
HKEY_CURRENT_USER\Software\Microsoft\Windows\CompositionPolicy should be 2
HKEY_CURRENT_USER\Software\Microsoft\Windows\Composition should be 1
```

**Comment by embeddedemily** [comment]
I'm having same issue with title-bar text not update until you click off app and back on or refresh or close window etc. Unless I change the theme, then it works fine but that's not a practical solution because i can't tell customers to change their theme

**Comment by tohagan** [comment]
Considering using Electron for a new project but this issue would be the **show stopper** as a significant number of our users will have Windows 7.

**Comment by bgrimm** [comment]
Experiencing this issue with current 1.14.0 beta 0 still. (Win7x64, AMD)
Re-enabled Aero and problem goes away, but that is not a solution/fix.

**Comment by DovAmir** [comment]
waiting for a fix

**Comment by paulcbetts** [comment]
This is unlikely to be fixed tbh, users should either enable Aero or upgrade to an operating system not old enough to be in grade school

**Comment by AnatoliiAPFM** [comment]
seen the same issue on Windows 7 with basic theme, affected: Slack, Postman, 
workaround: switched to an Aero theme for now, probably best to upgrade to Windows 10 later anyway.

**Comment by sonofachuck** [comment]
It's odd to get such a glib response as "upgrade to an operating system not old enough to be in grade school" for a product such as this.

I work for a charity and a few banks in the US who still have entirely Windows 7-based infrastructures. Was hoping to use this as an inexpensive dev platform, but will have to reconsider if this response is indicative of the platform support.

BTW, Windows 7 is still huge: http://netmarketshare.com/operating-system-market-share.aspx?qprid=10&qpcustomd=0

Really, I want to work with Electron, but downplaying a major segment of the desktop market, your main objective, seems so frivolous.

**Comment by zanderz** [comment]
Thanks for the research. Tracking internally with DESKTOP-4179 - though it seems to be inherent to Electron.

**Comment by dsteegen** [comment]
I also stumbled on this issue while testing the Electron app we created for our client. As a workaround for the problem, I implemented a function that resizes the window 1 pixel and afterwards setting it back to it's original dimensions (this can not be seen with the naked eye). Each feature that should repaint the window will also call this function. It's not the most elegant solution but in the end, it was good enough for us.

Luckily, we only open an existing web application within Electron so we only had to use this hack when changing the title of the window. If you do a lot of native BrowserWindow calls, this may not be the solution for you.

`this.resizeWindowToFixRepaint = function (windowToResize) {
			var browserWindow = windowToResize || NodeRequire.remoteBrowserWindow().getFocusedWindow();

			var wasMaximized = browserWindow.isMaximized();
			var bounds = browserWindow.getBounds();

			browserWindow.setSize(bounds.width - 1, bounds.height - 1);

			if (wasMaximized) {
				browserWindow.maximize();
			} else {
				browserWindow.setSize(bounds.width, bounds.height);
			}
		};`

**Comment by thauk-copperleaf** [comment]
This is a serious UX issue and I'm disheartened to see such a glib answer from a contributor. Really wish it would get fixed. :disappointed:

**Comment by arnaudbud** [comment]
+1

**Comment by rbarros-daitan** [comment]
+1

**Comment by izll** [comment]
+1

**Comment by kpedro88** [comment]
+1
(for Slack, Mattermost, Skype...)

**Comment by pmadhur** [comment]
If you are not using Menu, as a workaround, create BrowserWindow without frame:
`new BrowserWindow({frame: false})`
And implement the titlebar yourself or use [electron-titlebar](https://www.npmjs.com/package/electron-titlebar) package.
This worked for me on Windows 7 basic theme.

**Comment by ab320012** [comment]
I would love to help with this sort of lost as to how to start though. So far I am starting to look through the following file, let me know if i am on the right track:
https://github.com/electron/electron/blob/master/atom/browser/ui/views/autofill_popup_view.cc
