### ISSUE TITLE
Document webContents page-title-updated event

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#18210]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

(Actually a duplicate of [this closed issue](https://github.com/electron/electron/issues/10040))

### Issue Details

* **Electron Version:** 4.0.4
* **Operating System:** Windows 10
* **Last Known Working Electron version:**: n/a

`WebContents` apparently has a `page-title-updated` event that isn't documented. We were latching the handler onto the [`webview`](https://electronjs.org/docs/api/webview-tag#event-page-title-updated), but we're in the process of transitioning from a `webview` to a `BrowserView` which doesn't have that event.

I haven't tested this, but I was told that we can latch onto the event on the webcontents ([source](https://github.com/electron/electron/blob/0755857a0c1c76453391659c6d5ac6218dc9286f/atom/browser/api/atom_api_web_contents.cc#L1049)), but it's not documented.

Can it be?

**Comment by miniak** [comment]
Fixed in master

**Comment by miniak** [comment]
Pending backports to release branches
