### ISSUE TITLE
cookies.get({}) Typescript definition is incorrect

### ISSUE THREAD

**Issue by danawoodman** [electron/electron#18219]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 5.0.1
* **Operating System:** Mac OSX Mojave

### Expected Behavior

The type for `cookies.get` method should be `Promise<Cookie[]>` (an array of cookies)

### Actual Behavior

The type for `cookies.get` method is `Promise<Cookie>` (a single cookie)

### To Reproduce

1. Use Typescript
2. Try to do `session.defaultSession.cookies.get({}).map(c => c.name)`
3. See an error in Typescript saying the method returns a single cookie when in fact it returns an array of cookies

**Comment by MarshallOfSound** [comment]
This is fixed in the latest parser and on master, it may take a while for it to get into a release

**Comment by jasonxia23** [comment]
Still not resolved in 5.0.11
