### ISSUE TITLE
WebContents no longer emits `cursor-changed`

### ISSUE THREAD

**Issue by adill** [electron/electron#18213]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.0-beta.2
* **Operating System:**
  * Windows 10 (1809)
* **Last Known Working Electron version:**:
  * 4.2.0

### Expected Behavior
When hovering over text, links, etc. WebContents should be emitting `cursor-changed` events.

### Actual Behavior
`cursor-changed` are not emitted.

### To Reproduce
```sh
$ git clone https://github.com/adill/electron-quick-start -b no-cursor-changed
$ npm install
$ npm start || electron .
```

**Comment by ckerr** [comment]
This doesn't appear to be a Windows-specific bug. @adill's repro wfm on Ubuntu 19.04 as well.

**Comment by codebytere** [comment]
repros on macOS too

**Comment by codebytere** [comment]
Fixed in https://github.com/electron/electron/pull/23379/commits/2f3a23afb776220c0b0f9734d260466d4f9a1ad1
