### ISSUE TITLE
dev tools: iFrame in webview with a different origin from the the top frame is not inspectable

### ISSUE THREAD

**Issue by hugomano** [electron/electron#18224]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.1
* **Operating System:**
  * macOS 10.14.4 (18E226)
* **Last Known Working Electron version:**:
  * 4.1

### Expected Behavior

In a webview, we should be able to expand the iFrame DOM and inspect loaded iFrame's scripts in the dev tool whatever is the src origin. `nodeintegration` and `nodeintegrationinsubframes` attributes don't change anything.

### Actual Behavior

The iFrame tree is inspectable only if the source origin is the same that the top frame origin.

### To Reproduce

```sh
$ git clone https://github.com/getstation/electron-iframe-devtools
$ npm install
$ npm start
```

Expand the last 2 iFrames in the devtools:
- iFrame with `google.com` origin is inspectable 
- iFrame with `atlassian.com` origin is not inspectable 

### Screenshots

<img width="724" alt="Screenshot 2019-05-09 at 11 30 59" src="https://user-images.githubusercontent.com/823630/57443276-f893e100-724d-11e9-8177-9fe13a9152d4.png">

**Comment by lesleyandreza** [comment]
I have the some problem @hugomano, did you discovery any solution for this?
It also happens in later versions (6 and 7)

**Comment by lesleyandreza** [comment]
@hugomano, this command solved the issue for me:
```javascript
app.commandLine.appendSwitch('disable-site-isolation-trials')
```
I hope it helps too.

**Comment by Veiintc** [comment]
I have the same problem
I try this in 4.2.12 5.0.13 6.1.4 6.1.12 7.2.4 7.3.1 8.3.1 9.0.3
It work in 4.2.12
so I think 4.2.12 to 5.0.0 happened something

**Comment by Veiintc** [comment]
I try this command , @lesleyandreza  ,It work !!
you save me!thank you

**Comment by hugomano** [comment]
Stale issue and I'm not focus on it
