### ISSUE TITLE
drag DOM event not fired when element is above a webview

### ISSUE THREAD

**Issue by MathieuDebit** [electron/electron#18226]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  5.0.1, 6.0.0-beta.2
* **Operating System:**
  *  MacOS 10.14.3
* **Last Known Working Electron version:**
  *  4.2.0

### Expected Behavior

When dragging a DOM item, DOM events should always fire as expected, even if the drag element is above a webview.

### Actual Behavior

When dragging a DOM element who is above a webview, [`dragstart` event](https://developer.mozilla.org/en-US/docs/Web/API/Document/dragstart_event) is fired but not [`drag` event](https://developer.mozilla.org/en-US/docs/Web/API/Document/drag_event).

This breaks libraries like [`react-dnd`](https://github.com/react-dnd/react-dnd/).

### To Reproduce

Gist to test with Fiddle: https://gist.github.com/MathieuDebit/fb2841d67c7b9b30831c154686f7183a.
- Drag element in the list outside the webview: `drag` event is fired
- Drag element in the list inside the webview: `drag` event is not fired

Works with Electron 4.

### Additional Information

Issues that might be related:
- https://github.com/electron/electron/issues/17635
- https://github.com/electron/electron/issues/14258#issuecomment-416794070

**Comment by MathieuDebit** [comment]
Here is a Fiddle that fixes the issue:
- https://gist.github.com/9f860240ce97b300a1414092c3ad3317

Dragging over a webview is working as expected when the webview has the `pointer-events` CSS property to `none` during the drag.
This issue is similar with `iframe` and [seems to be known](https://stackoverflow.com/search?q=iframe+drag+and+drop).

This solution also fixes the issue when we drag an item from outside the webview to a drop target above a webview (bug present in electron@4.x.x).

Do you know what has changed exactly since 5.0.0? Is there a way to fix it?

Anyhow when dragging an item, there is no need to have pointer events for the webview.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
