### ISSUE TITLE
Tray icon behaving weird on Mac on light theme

### ISSUE THREAD

**Issue by vkolova** [electron/electron#18230]
### Preflight Checklist

* [X ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  5.0.1
* **Operating System:**
  macOS 10.14.3
* **Last Known Working Electron version:**:
  none

### Expected Behavior
All parts of the icon should keep their opacity when switching light and dark mode.

### Actual Behavior
The parts of the icon that are colored in white disappear in light mode, and the other colors lose some of their opacity.

### To Reproduce
[Demo](https://github.com/vkolova/electron-mac-os-tray-icons)

```sh
$ git clone https://github.com/vkolova/electron-mac-os-tray-icons
$ npm install
$ npm start || electron .
```

### Screenshots
This is the icon (note the white in the middle).
![icon](https://raw.githubusercontent.com/vkolova/electron-mac-os-tray-icons/master/icon%404x.png)

It looks correct in dark mode.
![dark mode](https://raw.githubusercontent.com/vkolova/electron-mac-os-tray-icons/master/screenshots/Screen%20Shot%202019-05-09%20at%203.36.16%20PM.png)

Looks like it lost some opacity in light mode.
![light mode](https://raw.githubusercontent.com/vkolova/electron-mac-os-tray-icons/master/screenshots/Screen%20Shot%202019-05-09%20at%203.36.31%20PM.png)

**Comment by codebytere** [comment]
Dug a bit into this this morning: this happens at the macOS level in that the level of opacity assigned by default makes it _appear_ as though the middle white section has been lost but in fact it's just that the default opacity assigned to tray items in Light mode is close enough to the background of the tray itself that it appears lost.

You can see on highlight in Light mode that it remains correct, and as such unfortunately this isn't something that's addressable on our end.

**Comment by donkooijman** [comment]
Hi @codebytere 

I noticed my white icons also getting transparent. I am unable to achieve full white in the menu bar. Only when clicked (highlighted) does my white parts become actually white.

Any idea how other apps are achieving this? For example iStats menu (white battery part): 
![image](https://user-images.githubusercontent.com/19776108/73030638-5e56e600-3e3a-11ea-9a49-35f8566402e2.png)
