### ISSUE TITLE
Documentation missing for `frame` option of BrowserWindow

### ISSUE THREAD

**Issue by upupming** [electron/electron#18232]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  5.0.1
* **Operating System:**
  Windows 10 but should seen on Any
* **Last Known Working Electron version:**:
  Any

### Expected Behavior

Show the whole sentence documentation of `frame` option as https://github.com/electron/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions.

### Actual Behavior

When typing, I got this:

![20190509224623-2019-5-9.png](https://i.loli.net/2019/05/09/5cd43d42ab0a5.png)

Following the source, I went to `electron.d.ts`:

![20190509224805-2019-5-9.png](https://i.loli.net/2019/05/09/5cd43daa69c0b.png)

It seems the new line breaks the interpretation of the documentation.

### To Reproduce

See above.

### Screenshots

See above.

### Additional Information

None.

**Comment by MarshallOfSound** [comment]
This is fixed with the new docs parser, unfortunately that docs parser probably can't be backported to Electron 5
