### ISSUE TITLE
showMessageBox BrowserWindow is not optional

### ISSUE THREAD

**Issue by adill** [electron/electron#18236]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.0-beta.2
* **Operating System:**
  * Windows 10 (1809)
* **Last Known Working Electron version:**:
  * 5.0.0

### Expected Behavior
`dialog.showMessageBox({options...})` should display a message box matching the options passed in

### Actual Behavior
A message box complaining about parsing argument at index 11 displays

### To Reproduce
```sh
$ git clone https://github.com/adill/electron-quick-start -b show-message-box
$ npm install
$ npm start || electron .
```

**Comment by codebytere** [comment]
Fairly certain i know what's behind this, i'll try to get a fix out imminently!
