### ISSUE TITLE
Per window audio capture from getUserMedia

### ISSUE THREAD

**Issue by supertiger1234** [electron/electron#18231]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
v4.1.4
Windows 10 x64
v4.1.4
### Expected Behavior
I was expecting to get a window capture and audio capture of a window.

### Actual Behavior
I got the window capture but the audio capture is from the whole PC and not specific to the program. I only want to capture the audio thats coming from a window (Just like discords screenshare)

### To Reproduce
```
chrome.desktopCapture.chooseDesktopMedia(['screen', 'window', 'audio'], callback)


  const stream = await navigator.mediaDevices.getUserMedia({
    audio: {
      mandatory: {
        chromeMediaSource: "desktop",
        chromeMediaSourceId: id,
      }
    },
    video: {
      mandatory: {
        chromeMediaSource: "desktop",
        chromeMediaSourceId: id,
        maxFrameRate: 60
      }
    }
  });
```

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by tanphamanhh** [comment]
I'm facing with the same problem. Do you have any solution?
In my researches, may be I must hook Window Core Audio APIs for capture audio from single application, but hook is difficult.

**Comment by supertiger1234** [comment]
Yup, thats what i was told aswell but i dont know hooks. I just gave up on my project :/
