### ISSUE TITLE
Tray stops working on Linux and disappears on Windows

### ISSUE THREAD

**Issue by stoically** [electron/electron#18241]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.1
* **Operating System:**
  * Ubuntu 18.04 and Windows 10 Build 15063

### Expected Behavior

Tray context menu should always work.

### Actual Behavior

Tray context menu stops working after a few context menu clicks (3-6).

### To Reproduce

Forked `electron-quick-start` and included a

<details>
<summary>minimal example</summary>

```js
const {app, Menu, Tray} = require('electron')
const path = require('path');

app.on('ready', () => {
  const contextMenu = Menu.buildFromTemplate([
    {label: 'Test', click: () => console.log('test')}
  ]);

  const tray = new Tray(path.join(__dirname, 'test.png'))
  tray.setToolTip('Test')
  tray.setContextMenu(contextMenu)
})
```
</details>

```
git clone https://github.com/stoically/electron-quick-start.git
npm install
npm start
```

Right-click the tray icon (white rectangle) and click the `Test` context menu. Observe the command-line and see `test` printed. Repeat the click on the `Test` context menu a few times.
* On Linux it eventually stops printing `test`
* On Windows the Tray icon disappears after a few clicks

### Additional Information

Since I have some applications that use Electron and whose Tray doesn't stop working, it seems absolutely possible to make the Tray reliable. In fact, I've cloned [Rambox](https://github.com/ramboxapp/community-edition), ran `npm install` and `npm start` and the Tray keeps working on the same systems I've reproduced my issue on. So I'm not sure what's wrong here - maybe I'm missing something.

**Comment by DeerMichel** [comment]
Hey, thanks for reaching out. That shouldn't be an Electron issue indeed. Since you're declaring `tray` within function scope, it will eventually go out-of-scope and therefore disappears. When you keep the `tray` reference in global scope (to prevent it from being GC'ed) like shown in the [docs](https://electronjs.org/docs/api/tray#class-tray), it should resolve your issue. Otherwise, feel free to reopen.

**Comment by stoically** [comment]
Makes perfect sense and works, thanks!

**Comment by Ryanaztec** [comment]
Please check the Electron FAQ on here[https://www.electronjs.org/docs/faq#my-apps-tray-disappeared-after-a-few-minutes](url)
