### ISSUE TITLE
Unintended escape of quotation mark in args of `relaunch`

### ISSUE THREAD

**Issue by ipy** [electron/electron#18247]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.1
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**:
  * 

### Expected Behavior

```js
const { app } = require('electron');
app.relaunch({
    execPath: 'C:\\WINDOWS\\system32\\cmd.EXE',
    args: ['/c', 'echo "'],
});
app.quit();
```
Expected output:
"

### Actual Behavior

Actual output:
\\"

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and provide us with steps to reproduce this issue using [electron-quick-start](https://github.com/electron/electron-quick-start).

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
