### ISSUE TITLE
feature: allow an empty whitelist for Session.allowNTLMCredentialsForDomains to fully disable windows integrated auth

### ISSUE THREAD

**Issue by bughit** [electron/electron#18245]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Without specifying any whitelist electron's default behavior on windows is to follow IE security zone settings. This is indicated [in chromium docs](https://www.chromium.org/developers/design-documents/http-authentication),

> In Windows only, if the AuthServerWhitelist setting is not specified, the permitted list consists of those servers in the Local Machine or Local Intranet security zone (for example, when the host in the URL includes a "." character it is outside the Local Intranet security zone), which is the behavior present in IE. Treating servers that bypass proxies as being in the intranet zone is not currently supported.

and I've confirmed experimentally that it precisely obeys the IE security zone settings.

So given that by default integrated auth will be on for whatever urls IE settings and group policies dictate, it would be useful to be able to completely disable integrated windows auth in electron.

### Proposed Solution

specifying an empty whitelist `.allowNTLMCredentialsForDomains('')` would disable windows integrated auth IE fallback

currently (5.0.1) this is a noop

### Alternatives Considered

a workaround is to specify a bogus whitelist  `.allowNTLMCredentialsForDomains('invalid.invalid')`

**Comment by nornagon** [comment]
I think you can accomplish this with any non-empty string, e.g. `allowNTLMCredentialsForDomains(' ')`, per https://source.chromium.org/chromium/chromium/src/+/main:net/http/http_auth_preferences.cc;l=80-81;drc=359c4471ef9ffdf94d1080815d51f28ce0302b94.
