### ISSUE TITLE
Network Error Logging is disabled by default

### ISSUE THREAD

**Issue by kwonoj** [electron/electron#18252]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4, 5, 6 
* **Operating System:**
  * not related

* **Last Known Working Electron version:**:
  * doesn't work at all

### Expected Behavior

Electron's network request honor NEL header and make NEL request.

### Actual Behavior

Does not happens

### To Reproduce

Navigate known NEL-enabled endpoint (i.e https://dcreager.net/nel/intro/), collect netlog and check `Reporting` section.

### Additional Information

NEL (https://www.w3.org/TR/network-error-logging/) is enabled by default from M69 (https://www.chromestatus.com/features/5391249376804864), but in our desktop client based on v4 (and v5, 6 for verification purpose) doesn't honor NEL header so we are not able to collect users using desktop client.

In chromium visiting NEL configured endpoint will make proper NEL request to specified endpoint, and client side behavior can be verified via netlog like below:

![image](https://user-images.githubusercontent.com/1210596/57558111-5ea56480-7331-11e9-99ba-e0d89703b5bd.png)

In Electron, some version simply doesn't have `Reporting` section at all, or if exists it says it's disabled:

![image](https://user-images.githubusercontent.com/1210596/57558135-7381f800-7331-11e9-9ab4-7d463038246a.png)

**Comment by nornagon** [comment]
I recorded this on Electron master:

<img width="851" alt="Mozilla_Firefox" src="https://user-images.githubusercontent.com/172800/57562073-9a95f500-7344-11e9-9185-a564cea56cf7.png">


I think this is actually an issue with `--log-net-log`, which does not record additional information such as NEL data.

That said, I think we still haven't hooked up the reporting service properly. /cc @deepak1556
