### ISSUE TITLE
uncaughtException  Invalid

### ISSUE THREAD

**Issue by hxkuc** [electron/electron#18256]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 1.0---5.0
* **Operating System:**
  * Windows 7
* **Last Known Working Electron version:**:
  * 
### Expected Behavior

i have three files

main.js
```
process.on('uncaughtException', function (err) {
  console.log(err)
})
const Bugs = require('./bugs.js')
Bugs.on('bug', fun)
function fun () {
  console.log(123)
  aaaaa
  console.log(456)
}
```

bug.js
```
const EventEmitter = new (require('events'));
module.exports = EventEmitter;

```

index.html
```
<!DOCTYPE html>
<html>
<head>
</head>
<body>
    <script>
        const {remote, ipcRenderer} = require('electron');
        const Bugs = remote.require('./bugs.js');
        Bugs.emit("bug"); 
    </script>
</body>
</html>
```
'uncaughtException' should get work when i emit 'bug' in renderer process , but it not 

### Actual Behavior

uncaughtException should get work

**Comment by miniak** [comment]
You will get an exception in the renderer process
```
Uncaught Error: Could not call remote function 'emit'. Check that the function signature is correct. Underlying error: aaaaa is not defined
```
