### ISSUE TITLE
Support chrome 'flags' and all command line options?

### ISSUE THREAD

**Issue by burtonator** [electron/electron#18253]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

I'd like to have more control over the chrome renderer including flags and command line options.

There are experimental features of chrome I would like to play with.

These can be accessed in a browser as chrome://flags but this URL doesn't work with Electron.

Additionally there are command line arguments I'd like to specify like '--disable-site-isolation-trials' which would allow me to work around a bug that impact Electron right now.

**Comment by burtonator** [comment]
Looks like it 'might' be able to do this now with --enable-feature= but I don't have a list of features to test it out with.

**Comment by MarshallOfSound** [comment]
Chrome features that are flagged can be enabled / disabled with `--enable-features` and `--disable-features`.

Other cli flags can also be provided.  You do both of these through the command line API

https://github.com/electron/electron/blob/master/docs/api/command-line.md

**Comment by mingjun97** [comment]
I'm trying to manupilate these two flags inside Chrome, but it seems that these flags don't have corresponding cli flags. The flags I've encontered are `enable-media-session-service` and `hardware-media-key-handling`. They can be changed by chrome://flags//#enable-media-session-service and chrome://flags//#hardware-media-key-handling How can I disable it? 

 I've searched it a lot but didn't find solution or workaround.

Thanks

**Comment by Pabloitto** [comment]
Any solution for this ?

**Comment by rocka** [comment]
@mingjun97 in case you are still wandering, and someone searching for this issue, I found a workaround:

Open some task manager, you should be able to see many renderer processes of chrome, and their command lines, take a screenshot or copy one of those, especially `enable-features` and `disable-features`.

![image](https://user-images.githubusercontent.com/13914967/75015426-85e5b080-54c3-11ea-9c9f-263a7618d44b.png)

Then disable/enable desired flags in chrome, restart chrome, and copy those command line again:

![image](https://user-images.githubusercontent.com/13914967/75014751-fd1a4500-54c1-11ea-89f0-5068aa24248e.png)

In my case, It is `HardwareMediaKeyHandling,MediaSessionService` in `disable-features`.

Add them using

```js
app.commandLine.appendSwitch('disable-features', 'HardwareMediaKeyHandling,MediaSessionService');
```

 before `app`'s `ready` event triggered. Works fine with electron 7.x and 8.x on Linux, which disable chromium's poor MPRIS implementation.

**Comment by Timmmm** [comment]
You don't need to use the task manager - just go to `chrome://version`.

**Comment by aminya** [comment]
How can I enable experimental web assembly features?

**Comment by parkerlreed** [comment]
Is there a way to pass this on the command line itself rather than in the source code?

**Comment by oalfroukh** [comment]
> Chrome features that are flagged can be enabled / disabled with `--enable-features` and `--disable-features`.
> 
> Other cli flags can also be provided. You do both of these through the command line API
> 
> https://github.com/electron/electron/blob/master/docs/api/command-line.md

Hi @MarshallOfSound 
Hope you're doing well!

Any idea how we can enable Chrome policy via the command line, for example, enable [CloudAPAuthEnabled](https://chromeenterprise.google/policies/?policy=CloudAPAuthEnabled), or needs to request that as a feature to support it by `electron` itself?

Thanks in advance!
