### ISSUE TITLE
add android support

### ISSUE THREAD

**Issue by mccoysc** [electron/electron#18257]
now i know that nodejs can be build into android os and can be work well.
like the url:
https://github.com/dna2github/dna2oslab

**Comment by chfanghr** [comment]
Chromium kernel doesn't behave like it does on desktop so electron app
won't be correctly rendered , I think.

mccoysc <notifications@github.com> 于 2019年5月11日星期六 12:47写道：

**Comment by miniak** [comment]
Duplicate of https://github.com/electron/electron/issues/15749
