### ISSUE TITLE
Error applying patches during gclient sync on windows

### ISSUE THREAD

**Issue by jphw** [electron/electron#18269]
Hi
I'm trying to clone Electron on Windows as per build guide (https://electronjs.org/docs/development/build-instructions-gn) using **gclient sync**, but it fails with an error every time:

```
Syncing projects: 100% (95/95), done.

________ running 'D:\Python27\python.exe src/electron/script/apply_all_patches.py src/electron/patches/common/config.json' in 'F:\Code\Tst'
Traceback (most recent call last):
  File "src/electron/script/apply_all_patches.py", line 32, in <module>
    main()
  File "src/electron/script/apply_all_patches.py", line 28, in main
    apply_patches(json.load(config_json))
  File "src/electron/script/apply_all_patches.py", line 14, in apply_patches
    committer_name="Electron Scripts", committer_email="scripts@electron")
  File "F:\Code\Tst\src\electron\script\lib\git.py", line 95, in import_patches
    newvalue='HEAD'
  File "F:\Code\Tst\src\electron\script\lib\git.py", line 119, in update_ref
    return subprocess.check_call(args)
  File "D:\Python27\lib\subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "D:\Python27\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "D:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "D:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2]
Error: Command 'D:\\Python27\\python.exe src/electron/script/apply_all_patches.py src/electron/patches/common/config.json' returned non-zero exit status 1 in F:\Code\Tst
```

It fails to execute "git -C update-ref" for some reason that I don't really understand.

Python 2.7.10
GClient 0.7

**Comment by jphw** [comment]
An addition: when I add "shell=True" argument to `subprocess.check_call` call in electron/script/lib/git.py - then it seems to be working and this particular error goes away, but others show up (also related to subprocess calls if I get it right)

**Comment by MarshallOfSound** [comment]
This appears to be because the patch script can't find `git` on your path. Please ensure that `git`and `node` are available on your system level PATH variable and restart your computer to be sure 👍

**Comment by jphw** [comment]
> 
> 
> This appears to be because the patch script can't find `git` on your path. Please ensure that `git`and `node` are available on your system level PATH variable and restart your computer to be sure 👍

they are available, here is what "where" command shows on my system:

```
F:\Code\Tst>where git
D:\depot_tools\git.bat

F:\Code\Tst>where node
D:\nodejs\node.exe
```

**Comment by MarshallOfSound** [comment]
Which python are you using? The python you installed or the python that is packaged with `depot_tools`?

**Comment by jphw** [comment]
Locally installed python 2.7.10 as suggested by https://electronjs.org/docs/development/build-instructions-windows#prerequisites

**Comment by jphw** [comment]
@MarshallOfSound  any update?

**Comment by trippleflux** [comment]
I am also getting this issue

**Comment by samkuhn** [comment]
I've just run into the same issue today with a fresh clone on a brand new pc.. did anyone solve it yet?

**Comment by samkuhn** [comment]
Managed to solve this through some combination of moving my local python / git paths above depot_tools and not trying to sync on wifi.. had about 8 other issues as well but mostly from not reading the prerequisites properly ;)

**Comment by tuxianchao** [comment]
i have this problem,too. did you solve it？
