### ISSUE TITLE
Crash on macOS with Electron v3.1.6

### ISSUE THREAD

**Issue by Coder-256** [electron/electron#18262]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success. ***This might be a duplicate of #17617 but I have no idea how to check.***

### Issue Details

* **Electron Version:**
  *  3.1.6 (Visual Studio Code 1.33.1)
* **Operating System:**
  *  macOS 10.14.4
* **Last Known Working Electron version:**:
  *  N/A

### Expected Behavior

No crash.

### Actual Behavior

The app crashes.

### To Reproduce

Not quite sure how to reproduce, but the crash is from [Visual Studio Code](https://code.visualstudio.com/).

### Screenshots

N/A

### Additional Information

Crash report: [Electron.crash](https://gist.github.com/Coder-256/d6f7c628335e3fe96547e55aa7f6802a)

I've narrowed it down to somewhere in this function:
https://github.com/electron/electron/blob/73158a6419a3e2da9e4d523e1131052abd28fbbb/atom/browser/window_list.cc#L82-L90

Sorry if I haven't provided enough information, if I'm missing anything please let me know.

**Comment by Coder-256** [comment]
To me, this looks the crash happens when calling `window->IsClosed()`, but I have no clue how that happens. Also I could be entirely wrong. This is just based on the disassembly from Hopper (I was bored):

<img width="600" alt="Screen Shot 2019-05-11 at 5 13 53 PM" src="https://user-images.githubusercontent.com/10134823/57574996-42c4c000-7410-11e9-887a-f39f1e2eaba8.png">

**Comment by codebytere** [comment]
At present, there is no way for us to reproduce this in a minimal standalone Electron app. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
