### ISSUE TITLE
Need a way to run with --no-sandbox by default

### ISSUE THREAD

**Issue by burtonator** [electron/electron#18265]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

5.0 implemented sandbox by default but a ton of our users are reporting issues.

See: 

https://github.com/burtonator/polar-bookshelf/issues/947
https://github.com/burtonator/polar-bookshelf/issues/891

For a stack traces and other errors.

It looks like --no-sandbox fixes it but if I construct the browser window with sandbox: false that doesn't fix the problem.

### Proposed Solution

Some way to disable the sandbox by default and/or restore the old behavior.

**Comment by MarshallOfSound** [comment]
This is not something that would be easy to support, or something that is good for the security of the Electron ecosystem as a whole.  The decision was made and discussed in https://github.com/electron/electron/issues/15760.

Any issues users are having with the SUID sandbox on linux can be fixed by either correctly configuring the OS or ensuring the permissions of the `chrome_sandbox` binary are correct at install time.

I'd recommend reading through https://github.com/electron/electron/issues/17972

For snapcraft issues, this PR to the snapcraft maker should handle those: https://github.com/electron-userland/electron-installer-snap/pull/22

The stack trace in https://github.com/burtonator/polar-bookshelf/issues/947 looks like it might be a separate issue though, so raising that as a new issue would be helpful.  In particular any information about any PPAPI plugins in use, or things like trying to use the chrome PDF viewer.

**Comment by burtonator** [comment]
They're probably on an Electron version < 5.0...

**Comment by jarek-foksa** [comment]
@MarshallOfSound Since there is already `--no-sandbox` command line argument, why not expose  corresponding programmatic option? You could deprecate both of them after all critical bugs are fixed. Note that sandbox is also causing crashes on macOS: https://github.com/electron/electron/issues/19626.

**Comment by MarshallOfSound** [comment]
> why not expose corresponding programmatic option?

Because that's not possible, the choice on what and how to sandbox is done way before a users app code ever runs.  A programatic option to disable sandbox is useless

**Comment by adomyaty55foundry** [comment]
This is rediculous, I'm forced to downgrade from Electron 5.0 because of no solutions when on WSL > Cypress 3.5 which forces Electron use 5.0. Have to downgrade to 3.4 to get the odler 2.0 electron just to make my tests to work

`[12264:1029/152011.865024:FATAL:gpu_data_manager_impl_private.cc(892)] The display compositor is frequently crashing. Goodbye.`

**Comment by vn971** [comment]
Is it also possible to have an environment variable override, in situations where directly plugging into CLI is not possible?

**Comment by vn971** [comment]
It might be useful if the electron app itself is run in another jail that disables `root` user (and thus SUID), and also gives access control on user-specific directories (something that is not possible to do for the app itself).

**Comment by tarruda** [comment]
> Since there is already --no-sandbox command line argument, why not expose corresponding programmatic option?

The following seems to work for me:

```js
// run this at early startup, before app.on('ready')
app.commandLine.appendSwitch('--no-sandbox')
```

**Comment by rwwagner90** [comment]
I've been searching for a solution to the snapcraft sandbox issues for many hours now. I see that https://github.com/electron-userland/electron-installer-snap/pull/22 was implemented, but I don't understand how it fixes the issue. My snap builds still all get rejected during automatic review with 

```
human review required due to 'deny-connection' constraint (interface attributes). If using a chromium webview, you can disable the internal sandbox (eg, use --no-sandbox) and remove the 'allow-sandbox' attribute instead. For QtWebEngine webviews, export QTWEBENGINE_DISABLE_SANDBOX=1 to disable its internal sandbox. declaration-snap-v2_plugs_connection (browser-sandbox, browser-support)
```

How are we supposed to fix this issue?

**Comment by probonopd** [comment]
There should be an environment variable in addition to the `--no-sandbox` argument, doing the same thing. This would greatly simplify it to disable the sandbox globally on a system for all applications.

**Comment by rap2hpoutre** [comment]
@tarruda Is there a way to add this option only for Linux (and not for other builds ?)

**Comment by nQssss** [comment]
> @tarruda Is there a way to add this option only for Linux (and not for other builds ?)

`if (process.platform === "linux") app.commandLine.appendSwitch("no-sandbox");`

**Comment by jespertheend** [comment]
I want to publish an electron app to Steam, and when launched through the Steam Linux Runtime, it takes a good minute or two before either closes or shows a blank screen. The only fix I've found is to set the `--no-sandbox` flag.

I tried both `app.commandLine.appendSwitch("no-sandbox");` and `app.commandLine.appendSwitch('--no-sandbox')` but neither of these seem to work.
My guess is that this switch only disables the sandbox for the render process. Whereas actually providing it on startup disables it it for everything.

If this is true, afaik you can already achieve this using `sandbox: false` in your `webPreferences`, no need to use `commandLine.appendSwitch()` then:
```js
const win = new BrowserWindow({
  webPreferences: {
    sandbox: false,
  },
})
```

On another note, [this comment mentions](https://github.com/camunda/camunda-modeler/issues/4695#issuecomment-2478248024):
> appending the switch within the app no longer works

So it's also possible that `commandLine.appendSwitch()` used to work at some point, but now it no longer does.

**Comment by jbool24** [comment]
Why are we un-sandboxing in the first place? That's not good security unless I'm missing something? We have tons of Electron apps distributed to millions users with open attack vectors and this feels really really bad. Whats up folks?? 🤔

**Comment by vn971** [comment]
@jbool24 [there](https://github.com/electron/electron/issues/18265#issuecomment-573331892) [are](https://github.com/electron/electron/issues/18265#issuecomment-547656143) [reasons](https://github.com/electron/electron/issues/18265#issuecomment-1418288118). Also, please really do read the thread before posting a reply. I hope both of our comments would be hidden as offtopic and/or deleted to not pollute the thread.

**Comment by probonopd** [comment]
The sandboxing is not compatible with Snap and AppImage. These are running from squashfs files mounted by non-root users, so no setuid is available.

**Comment by overbyte** [comment]
> const win = new BrowserWindow({
>   webPreferences: {
>     sandbox: false,
>   },
> })

This didn't work for me - the only thing that works is using the `--no-sandbox` flag on the .appImage or double-clicking the file in nautilus 🤷

**Comment by Chetan11-dev** [comment]
I tested with following 
```
app.commandLine.appendSwitch('--no-sandbox');
```

```

    webPreferences: {
      sandbox:false, 
    }
```
none works,
Can electron team give us a solution as to how to add '--no-sandbox' in newer electron version's?

**Comment by rathboma** [comment]
Hey all, here's how we do this with Electron Builder and Beekeeper Studio:

We use a linux-specific launcher script - https://github.com/beekeeper-studio/beekeeper-studio/blob/master/apps/studio/build/launcher-script.sh, as a way to run our app with --no-sandbox by default.

Here's the configuration we use to do that with electron builder:

- Include the file: https://github.com/beekeeper-studio/beekeeper-studio/blob/master/apps/studio/electron-builder-config.js#L45
- afterpack script to make it the executable: https://github.com/beekeeper-studio/beekeeper-studio/blob/master/apps/studio/build/afterPack.js

Hope that helps! Works great for Beekeeper Studio

**Comment by Chetan11-dev** [comment]
@rathboma 

I followed your way, and When try to launch app, it shows this error, 
```
-bash: /usr/bin/googlemapsextractor: Permission denied
```

Any idea why?
