### ISSUE TITLE
Electron apps have no icon in systray settings of KDE Plasma desktop environment

### ISSUE THREAD

**Issue by glaubersm** [electron/electron#18261]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
electron 4.1.4
* **Operating System:**
  * 
Arch Linux, KDE Plasma 5.15.5 desktop environment.
* **Last Known Working Electron version:**:
  * 

### Expected Behavior

Electron apps should show their icon in systray settings of KDE Plasma desktop environment, like non-electron apps.
### Actual Behavior

Electron apps have no icon in systray settings of KDE Plasma desktop environment.
### To Reproduce

install and run any electron app with systray icon on a linux distribution running KDE Plasma desktop environment.
open systray settings of KDE Plasma:
right click on up arrow aside the clock/date, select "Configure system tray..."
click 'Entries" section in the left side
Observe the entry of your electron app: it has no icon.
The screenshot below shows several electron apps without icon in systray settings window.

### Screenshots

![electron](https://user-images.githubusercontent.com/15967631/57571231-ae436900-73e1-11e9-96a0-a82301ef9607.png)

**Comment by eskildak** [comment]
In my case I have neither icon nor title.
**Electron version:** Both 5.0.1 and 4.2.1
**Operating System:** Debian 10, KDE Plasma 5.14.5.1
![2019-05-15_16-36](https://user-images.githubusercontent.com/48755050/57785134-65691880-7731-11e9-84d0-2b5b35b95640.png)

**Comment by codebytere** [comment]
This can be solved with the following: 

1. In "Edit applications" KDE menu, change path from "/usr/bin/YOUR_APP_NAME" to "XDG_CURRENT_DESKTOP=Unity /usr/bin/YOUR_APP NAME"
2. Edit the `.desktop` file.

**Comment by glaubersm** [comment]
Will there be no definitive solution to this problem?

**Comment by glaubersm** [comment]
Your "solution" does not work with apps installed via flatpak or Snap.
Install Discord and Skype, for example,

https://snapcraft.io/discord
https://flathub.org/apps/details/com.skype.Client

and edit their .desktop files as you said.
Their icons are still missing in system tray settings.
Reopen this issue please, we need a proper solution.

**Comment by glaubersm** [comment]
Reopen this issue please.
