### ISSUE TITLE
WebGL [20966:0512/185825.695311:ERROR:gles2_cmd_decoder.cc(10887)] [.WebGL-0x12e76e150

### ISSUE THREAD

**Issue by coreybruce** [electron/electron#18266]
Hey guys I wanted a report an issue with Electron 5.0.1
fullscreening WebGL will freeze/lock up the whole application and spam this error in the terminal

`00]RENDER WARNING: Render count or primcount is 0.
[21512:0512/185925.766166:ERROR:gles2_cmd_decoder.cc(10887)] [.WebGL-0x6bd9b054000]RENDER WARNING: Render count or primcount is 0.
[21512:0512/185925.768287:ERROR:gles2_cmd_decoder.cc(10887)] [.WebGL-0x6bd9b054000]RENDER WARNING: Render count or primcount is 0.
[21512:0512/185925.769983:ERROR:gles2_cmd_decoder.cc(10887)] [.WebGL-0x6bd9b054000]RENDER WARNING: Render count or primcount is 0.
...`

I have tested it but I have no issues with Electron 4.1.1 for example and doesn't cause these issues

**Comment by miniak** [comment]
@coreybruce This is not actionable without more details, such as a simple repro (preferably using https://github.com/electron/fiddle)

**Comment by coreybruce** [comment]
what extra details do I need?

**Comment by MarshallOfSound** [comment]
@coreybruce The entire template is missing (we require the template filled out).  As you deleted it you can find the original template here --> https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE/Bug_report.md

As @miniak mentioned the key thing is a simple way for us to repro, preferably an Electron Fiddle gist.

**Comment by coreybruce** [comment]
---
name: WebGL issues and fullscreen issues
about: Create a report to help us improve Electron

---



### Preflight Checklist


* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
  Electron 5.0.1
* **Operating System:**
  * 
 Manjaro XFCE 18.04 stable
* **Last Known Working Electron version:**
  * 
   Electron 4.1.1
### Expected Behavior

open properly without OpenGL issues and fullscreen
### Actual Behavior

sometimes will not open properly spamming OpenGL errors and breaks when fullscreening on games
### To Reproduce

https://gitlab.com/gamerworld/application




### Screenshots

https://imgur.com/9agqbRE.png
https://imgur.com/mq0oPip.png
### Additional Information


seems to be having issues when maximizing the window or even setting to auto maximize on launch on top of the fullscreen issue than spamming WebGL errors.

**Comment by coreybruce** [comment]
Any reports on any fixes to Electron 5.x.x

**Comment by coreybruce** [comment]
Any update? I tried Electron 7.0.0-nightly.20190606 and it was also having stability issues when fullscreening

**Comment by coreybruce** [comment]
Bug also Affects Windows, tested with electron 5.0.5

**Comment by coreybruce** [comment]
@sofianguy @miniak @MarshallOfSound

**Comment by MarshallOfSound** [comment]
@coreybruce We understand that this bug exists and that it affects you, there is nothing more to do here other than wait for someone to pick it up.  This project is open source and maintained by a small group of core maintainers, this bug is currently not an immediate priority for us.  If you wish to attempt to fix it we're more than happy to accept pull requests though

**Comment by coreybruce** [comment]
I found that a work around is having to re-program Gamer World as my other software using Electron 5.x.x is not affected by this bug but I haven't done that yet and only seems to be a issue for when my application maximises or content inside it goes in full screen but again only with the way Gamer world is coded.

**Comment by bluesaxman** [comment]
It looks like the command line option "disable-frame-rate-limit" is causing rendering issues. Both when the window resizes and when it tries to paint anything (such as electrons main menu) over top of the rendering surface. This occurs on all platforms.

**Comment by coreybruce** [comment]
Can confirm that there is a issue with the frame limiter being turned off and will need to be fixed.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
