### ISSUE TITLE
how to generate node.lib for native c++ addon when build electron from source code

### ISSUE THREAD

**Issue by epicylq** [electron/electron#18278]
i want to know how can i generate node.lib (that use for native c++ addon when you use node-gyp ) when build electron from source code, i cant find the step from document, anyone know it

**Comment by MarshallOfSound** [comment]
@epicylq It is just `electron.lib` renamed to `node.lib`

E.g. https://github.com/electron/electron/blob/master/appveyor.yml#L108

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by epicylq** [comment]
> @epicylq It is just `electron.lib` renamed to `node.lib`
> 
> E.g. https://github.com/electron/electron/blob/master/appveyor.yml#L108

thanks for your help, and i find if you want to generate  a usable electron.lib in debug, you must  set is_component_build to true in debug.gn

**Comment by MarshallOfSound** [comment]
@epicylq Yes, if you want to build native modules against a custom Electron build you can't use debug.   You should use `testing` or `release` for that.
