### ISSUE TITLE
Spellchecker doesn't work

### ISSUE THREAD

**Issue by cumajkeee** [electron/electron#18294]
### Issue Details

* **Electron Version:**
  * 5.0.1
* **Operating System:**
  * macOS 10.14.4 
* **Last Known Working Electron version:**:
  * 4.0.8

### Expected Behavior
When I setup node-spellchecker module as provider, expect it work (highlight misspelt words)

### Actual Behavior
Spellchecker didn't work (misspelt words not highlighted)
[spellchecker.zip](https://github.com/electron/electron/files/3177527/spellchecker.zip)

**Comment by MarshallOfSound** [comment]
Electron 5's spellchecker is now a different API as of Electron 5

See https://electronjs.org/blog/electron-5-0#spellchecker-now-asynchronous
