### ISSUE TITLE
getFileIcon index

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [electron/electron#18292]
https://electronjs.org/docs/api/app#appgetfileiconpath-options-callback

Some Windows files can contain several icons, we can get iconIndex with https://electronjs.org/docs/api/structures/shortcut-details.

I need it beacause I am trying to display icons of shortcuts, so how are we supposed to use getFileIcon to get the nth icon ?

**Comment by MarshallOfSound** [comment]
This is something that the underlying Chromium API does not support and I don't think is the intended usecase for the method.

This API is designed to fetch the _one_ icon a file would have / display in a file explorer.  i.e. Imagine you found the file in Windows Explorer, the icon this API returns is the icon it would display to you.

Although you are correct that on windows a `dll` or `exe` can contain multiple icons, only one is the primary / default used for this API.

I'd suggest using a native module if you want to get the icon at a different index for your specific use case
