### ISSUE TITLE
shell.openExternal with Firefox as default browser not always getting focus

### ISSUE THREAD

**Issue by linonetwo** [electron/electron#18293]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

Electron version: v5.0.1
Operating system: MaxOS 10.14.4

### Expected Behavior

As doc https://electronjs.org/docs/api/shell#shellopenexternalurl-options

### Actual Behavior

Link opened in the browser, but the browser is not brought to the foreground.

### To Reproduce

Upgrade electron to v5.0.1 in https://github.com/electron/electron-api-demos

And try "open external links" demo

**Comment by MarshallOfSound** [comment]
@linonetwo In order to activate a the opened application you have to set `activate: true`

```js
shell.openExternal('https://google.com', {
  activate: true,
})
```

**Comment by linonetwo** [comment]
But as doc https://electronjs.org/docs/api/shell#shellopenexternalurl-options
The default of `activate` is true on Mac.

**Comment by linonetwo** [comment]
Actually `shell.openExternal(url, { activate: true })` don't work, please reopen this, might be v5 regression.

**Comment by linonetwo** [comment]
@MarshallOfSound Please reopen this.

**Comment by MarshallOfSound** [comment]
@linonetwo Closed issues take a bit longer to filter to the top of my queue, please be patient and do not raise duplicate issues

**Comment by jeremyspiegel** [comment]
I am seeing the same problem with Safari as well as with Firefox. The problem does not exist when Chrome is the default browser. I am able to reproduce the issue with Electron 5.0.2, but not with 4.2.3. I also reproduced it with v5.0.0-beta.1.

**Comment by jeremyspiegel** [comment]
I think the problem is in this [change](https://github.com/electron/electron/pull/15065/files#diff-3931a5874dc372d4b3db289b762c23c9R151). A reference to an `OpenExternalOptions` structure is being captured by an Objective-C block that outlives the object that's being referenced.
