### ISSUE TITLE
BrowserWindow.setShape(rects)  titlebar

### ISSUE THREAD

**Issue by xuhuan123** [electron/electron#18304]
### Issue Details
BrowserWindow. setShape was used in the project, 
but on windwo10, the title bar of the screen became Win95. 
Is there any solution?

### Expected Behavior
the title bar of the screen became windwo10 (OS). 

### To Reproduce

$ git clone https://github.com/xuhuan123/setShape
$ npm install
$ npm start

### Screenshots

see image：
![キャプチャ](https://user-images.githubusercontent.com/20894625/57762010-42d6ff80-7731-11e9-971e-bf94909fd1c6.JPG)

sourceCode：

`mainWindow.setShape([
  {x:0, y:0, width: 1080, height: 100},
  {x:0, y:0, width: 500, height: 840}
])
`

![キャプチャ1](https://user-images.githubusercontent.com/20894625/57755904-a149b100-7724-11e9-9087-dfac9acae629.JPG)

**Comment by xuhuan123** [comment]
mainWindow.setShape([
      {x:0, y:0, width: 1080, height: 100},
      {x:0, y:0, width: 500, height: 840}
    ])

**Comment by xuhuan123** [comment]
> BrowserWindow. setShape was used in the project,
> but on windwo10, the title bar of the screen became Win95.
> Is there any solution?
> 
> see image：
> ![image](https://user-images.githubusercontent.com/20894625/57755796-5def4280-7724-11e9-840a-e6d3fc497c48.png)
> 
> sourceCode：
> `mainWindow.setShape([ {x:0, y:0, width: 1080, height: 100}, {x:0, y:0, width: 500, height: 840} ]) `
> ![キャプチャ1](https://user-images.githubusercontent.com/20894625/57755904-a149b100-7724-11e9-9087-dfac9acae629.JPG)

**Comment by xuhuan123** [comment]
> BrowserWindow. setShape was used in the project,
> but on windwo10, the title bar of the screen became Win95.
> Is there any solution?
> 
> see image：
> ![image](https://user-images.githubusercontent.com/20894625/57755796-5def4280-7724-11e9-840a-e6d3fc497c48.png)
> 
> sourceCode：
> 
> `mainWindow.setShape([ {x:0, y:0, width: 1080, height: 100}, {x:0, y:0, width: 500, height: 840} ]) `
> 
> ![キャプチャ1](https://user-images.githubusercontent.com/20894625/57755904-a149b100-7724-11e9-9087-dfac9acae629.JPG)

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by xuhuan123** [comment]
@sofianguy Updated. 更新しました。

**Comment by miniak** [comment]
@xuhuan123 what is your use case for this API? This might be a limitation of Windows, the underlying [SetWindowRgn](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-setwindowrgn) API is legacy. You should use a frameless window instead.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment [above](https://github.com/electron/electron/issues/18304#issuecomment-493467152). With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
