### ISSUE TITLE
Electron should have a built-in way to persist user preferences and other data.

### ISSUE THREAD

**Issue by AJ-Creations** [electron/electron#18303]
**Electron doesn't have a built-in way to persist user preferences and other data. This module handles that for you, so you can focus on building your app** - I have seen this paragraph in many webpages like electron-store documentations and others. While making something powerful, you should have gave it basic, must have features also. Not everybody is an SQL fan. So sqlite3 might not always be a valid answer. Neither electron-store has a good documentation on setting collections and documents. We need something like MongoDB to be locally running inside the application (embedded). And the answer is **No, you can't**.
For the next major update, We request you to add a NoSQL database in electron.

**Comment by MarshallOfSound** [comment]
@AJ-Creations In Electron you have access to _all_ the APIs for data storage both the node ecosystem and the web ecosystem have to offer.

#### Web Based

* `localStorage`
* `IndexedDB`
* `sessionStorage`

#### Node Based

There are way too many to list here

* `levelup`
* `sqlite3`
* `lowdb`
* `lokijs`

Electron isn't responsible for re-inventing all the wheels, there are countless solutions and abstractions  out there for persisting data.  You should find the one that works best for you and use it.

**Comment by elrDevelopment** [comment]
Hey @MarshallOfSound can you point me to the electron docs that show the quota eviction criteria for electron?
