### ISSUE TITLE
Crash when clicking <input type="file">

### ISSUE THREAD

**Issue by habanero123** [electron/electron#18313]
I have executed the following code with Electron v6.0.0-beta.3.
And when I clicked the button on the form it crashed.

Apparently, there is a problem with the execution of <INPUT type = "file">.

Do you have any one who knows the solution?

Regards.

    <html>
      <body>
        <form action="cgi-bin/abc.cgi" method="post" enctype="multipart/form-data">
          <p>
            <input type="file" name="datafile">
          </p>
          <p>
            <input type="submit" value="send">
          </p>
        </form>
      </body>
    </html>

### Issue Details

* **Electron Version:**
  * v6.0.0-beta.3
* **Operating System:**
  * Windows 10 Enterprise (1803)
* **Last Known Working Electron version:**:
  * v5.0.1

**Comment by MarshallOfSound** [comment]
Duplicate https://github.com/electron/electron/issues/18254
