### ISSUE TITLE
desktopCapture Crash with 10bit

### ISSUE THREAD

**Issue by datstarkey** [electron/electron#18312]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
6.0.0-beta3 & 5.0.1
* **Operating System:**
 Windows 10 (1803) 
* **Last Known Working Electron version:**:
 N/A

### Expected Behavior
When I have a a HDR WCG enabled monitor attached and use desktopCapture, I try to capture a chrome browser with webRTC, or any application on the monitor and it should display a stream.

### Actual Behavior
When doing this in electron it crashes immediatly with:
 [20968:0515/234318.408:ERROR:dxgi_output_duplicator.cc(116)] IDXGIDuplicateOutput does not use RGBA (8 bit) format, which is required by downstream components, format is 10
[20968:0515/234318.449:ERROR:dxgi_output_duplicator.cc(116)] IDXGIDuplicateOutput does not use RGBA (8 bit) format, which is required by downstream components, format is 10

I assume this is due to the monitor being a YUV 4:4:4 10bit color ouput, disabling HDR & WCG fixes the issue however its not ideal as this feature works in a chrome browser.

### To Reproduce
Try to run a webRTC video of a chrome browser with a HDR & WCG monitor attached.
```
  navigator.mediaDevices
    .getUserMedia({
      audio: false,
      video: {
        mandatory: {
          chromeMediaSource: "desktop",
          chromeMediaSourceId: selectedScreen
        }
      }
    })
    .then(stream => {
      handleStream(stream);
    })
    .catch(e => {
      console.log(e);
    });
```

### Additional Information
Note it stream other non HDR monitors fine and some applications (file explorer) if they're NOT on the HDR screen(Chrome browser always crashes it when selected).

If I uncheck the HDR from the monitor everything works as intended.

Crash also happens if I don't try to do anything with the returned result.

I can use firefox and chrome webRTC without any crashing and it works fine with the HDR monitor enabled:

**Comment by Simran-B** [comment]
The web content itself will still be in 8-bit colors though, right? All web technologies seem to be standardized around sRGB.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by samuelmaddock** [comment]
In case others run into the same or similar issues, I've reported it upstream to Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=1247730

**Comment by harismuha123** [comment]
Has there been any kind of fix for this with a new electron version or is it still broken? I'm able to reproduce this bug with Electron 25.
