### ISSUE TITLE
docs: where to acquire appveyor setting of build_cloud and image

### ISSUE THREAD

**Issue by RickyWong33** [electron/electron#18315]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

I've noticed Electron has complete automatic build system where windows building is powered by appveyor. However, forking Electron and putting into my own appveyor does not work at all. It requires accurate setting of `build_cloud` and `image`

How could I get that? Are they only access to the maintainers?

### Proposed Solution

Docs about appveyor

**Comment by MarshallOfSound** [comment]
build_cloud and custom images are appveyor Enterprise features that we use to support our build process. 

You can find docs on how we generate our images here: https://github.com/electron/electron/blob/master/docs/development/azure-vm-setup.md

If you want more info on those features I'd suggest reading through appveyors documentation.
