### ISSUE TITLE
Docs: Please change link in nativeImage.createFromNamedImage() documentation

### ISSUE THREAD

**Issue by chris-scheurle** [electron/electron#18311]
The documentation for `nativeImage.createFromNamedImage()` links to a [long list of possible image names](https://developer.apple.com/documentation/appkit/nsimagename?language=objc), which isn't helpful at all, because the list only contains names, no image previews.

Unlike [Apple Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/system-icons/), which gives a good overview of the options available.

**Comment by miniak** [comment]
@chris-scheurle you're welcome to create a PR fixing the documentation.

**Comment by miniak** [comment]
@chris-scheurle please check the linked PR
