### ISSUE TITLE
App name not used

### ISSUE THREAD

**Issue by leegee** [electron/electron#18317]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
 v5.0.1
* **Operating System:**
Windows 10 
`MINGW64_NT-10.0 studio 2.8.2(0.313/5/3) 2017-07-12 15:35 x86_64 Msys`

* **Last Known Working Electron version:**:
N/A

### Expected Behavior
According to [the docs](https://electronjs.org/docs/api/app#appgetname):

> `app.getPath(name)`

> userData The directory for storing your app's configuration files, which by default it is the appData directory appended with your app's name

> `app.getName()`

> Usually the name field of package.json is a short lowercased name, according to the npm modules spec. You should usually also specify a productName field, which is your application's full capitalized name, and which will be preferred over name by Electron.

After setting both `name` and `productName` in `package.json`, I expected the following to output the `name` or `productName` fields.

```javascript
const electron = require('electron');
const remote = electron.remote;
console.log(
   remote ? remote.app.getName() :
      electron.app ? electron.app.getName() : '/DEFAULT/');
```

### Actual Behavior
`Electron` is returned instead of the value of the `productName` or `name` fields of `package.json`.

### To Reproduce

As above.

**Comment by miniak** [comment]
@leegee are you sure you're putting those entries into the correct package.json? Can you share a simple repro app?

**Comment by leegee** [comment]
I wasn't aware there was to be more than one `package.json`....

I was reading the [API docs](https://electronjs.org/docs/api/app#appgetname), which refer to 'the application's `package.json`` ?

**Comment by miniak** [comment]
Some Electron boilerplates use two package.json, one for the build itself with build dependencies (such as TypeScript, webpack, ...) and another one for the app itself with runtime dependencies (React, jQuery, ...)

**Comment by leegee** [comment]
I see! 

I just have the one `package.json`, haven't used any boilerplate.

**Comment by codebytere** [comment]
@leegee do you have a repro for the issue?

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. 

Additionally, the version of Electron you reported this on has been superseded by newer releases. If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
