### ISSUE TITLE
isFullscreenable set to false when fullscreen set to false

### ISSUE THREAD

**Issue by devinfoley** [electron/electron#18325]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.1 (and earlier)
* **Operating System:**
  * macOS 10.14.4
* **Last Known Working Electron version:**:
  * N/A

### Expected Behavior
When I create a new BrowserWindow with `fullscreen: false`, I don't expect `isFullscreenable` to also be `false`.

### Actual Behavior
When creating a new BrowserWindow with `fullscreen: false`, the window ends up with `isFullscreenable` also being false.

### To Reproduce
I've created a fiddle here: https://gist.github.com/devinfoley/d09d14146aa0f1d161779c628fb8272e

You can see that I set `fullscreen: false`, and then output `isFullscreen` in `console.log`. The output is `false`.

**Comment by pushkin-** [comment]
That behavior is documented [here](https://electronjs.org/docs/api/browser-window#new-browserwindowoptions):

>When explicitly set to false the fullscreen button will be hidden or disabled on macOS. Default is false.

Just remove `fullscreen: false` to stop explicitly setting it.

**Comment by MarshallOfSound** [comment]
Hey @devinfoley as @pushkin- correctly noted this is currently the expected behavior.  Explicitly setting `fullscreen: false` on macOS removes the fullscreen button and therefore the ability to make the window fullscreen.  Hence `isFullscreenable()` is `false`.

If you leave `fullscreen:` undefined the `isFullscreenable` API will operate as you currently expect
