### ISSUE TITLE
crashReporter freezes the application

### ISSUE THREAD

**Issue by cristiammercado** [electron/electron#18329]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v6.0.0-beta.3
* **Operating System:**
  * Windows 10.0.17763 (17763)
* **Last Known Working Electron version:**
  * v5.0.1

### Expected Behavior
Start `crashReporter` process and continue the execution of the application.

### Actual Behavior
The `crashReporter` process is started (according to the Windows task manager) but the application doesn't continue running, like if call the `crashReporter.start` method blocked the main execution thread (after call `crashReporter.start` method, the crashReporter process continues running and the main electron process too).

### To Reproduce
* Create base electron app.
* Call `crashReporter.start` method.
* Put a `console.log` with any message after method call (or a window, too). This `console.log` never prints the message (or the window created open).

[EDIT] Repository: https://github.com/cristiammercado/test-electron-quickstar

### Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/4806666/57901323-2cf93580-782a-11e9-81ec-5f945746cb30.png)

![Screenshot_2](https://user-images.githubusercontent.com/4806666/57901324-2cf93580-782a-11e9-8e60-3a70839cd5f1.png)

**Comment by miniak** [comment]
@cristiammercado in which process are you calling `crashReporter.start()`, main or renderer?

**Comment by cristiammercado** [comment]
@miniak Main process

**Comment by cristiammercado** [comment]
Researching a little more, I realized that the problem is between versions 6.0.0-beta.1 and 6.0.0-beta.2, checking the history of changes between these two versions (https://github.com/electron/electron/compare/v6.0.0-beta.1...v6.0.0-beta.2) The PR that catches me is this has to do with crashpad: https://github.com/electron/electron/pull/18198. I'm not sure if this has to do with the bug that is being presented.

**Comment by cristiammercado** [comment]
Hi @miniak , Have you had the opportunity to check this issue? I updated the issue with a repository test.

**Comment by felixrieseberg** [comment]
I can confirm - happens in all current versions of Electron v6. If it helps, I've also made a [fiddle](https://gist.github.com/b9ecefaa0bc2af499872d3567ec1b8fa).

**Comment by nornagon** [comment]
I believe @nitsakh is working on this

**Comment by sofianguy** [comment]
fixed https://github.com/electron/electron/pull/18483
