### ISSUE TITLE
require is not defined when using inspect to attach debugger

### ISSUE THREAD

**Issue by TomasHubelbauer** [electron/electron#18334]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 5.0.1
* **Operating System:** Windows 10
* **Last Known Working Electron version:**: N/A

When running `electron index.js --inspect` where Electron is an NPM global, the debugger gets attached and I can use the Chrome DevTools to inspect the JavaScript context. `require` is defined in there.

When using the provided prebuilt binaries (4.2.2 - win32-x64) and placing my files to `resources/app`, then starting the executable using `electron.exe --inspect`, the inspector is still able to connect to the app, but in the DevTools console, `require` is not defined.

That means I can't do `require('electron')` and get access to the main context API.

This may be a deliberate design choice that I do not understand.

### Expected Behavior

`require` is defined

### Actual Behavior

`require` is undefined

### To Reproduce

```sh
# This WORKS
touch index.js
npx electron index.js --inspect
```

Chrome inspector can be attached and `require` exists in the DevTools console.

```sh
# This DOES NOT WORK
# Download prebuilt Electron binary for Windows and cd to its directory
cd resources
mkdir app
cd app
touch index.js
cd ../..
electron --inspect
```

Chrome inspector can be attached, but `require` is not defined in the DevTools console.

**Comment by miniak** [comment]
The `nodeIntegration` option in webPreferences is now `false` by default to increases security, making the `require` method only available in the preload script. There are 2 options:
- re-enable `nodeIntegration` explicitly when creating the `BrowserWindow`
- use a preload script to expose the `require` method as global

**Comment by TomasHubelbauer** [comment]
A since-deleted comment here got me thinking about `nodeIntegration`. I am assuming, when I attach the debugger to the Electron process, the JavaScript context I am attached to is the main process, not the renderer process, correct? Because my understanding is that `nodeIntegration` applies to the renderer process only?

**Comment by MarshallOfSound** [comment]
@TomasHubelbauer I believe this is currently expected behavior, there is a trick to getting `require` though by using `process.mainModule.require`.

**Comment by TomasHubelbauer** [comment]
This worked just perfectly, thank you!
