### ISSUE TITLE
[MacOS] shell.openExternal with Firefox as default browser can't get focus

### ISSUE THREAD

**Issue by linonetwo** [electron/electron#18332]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

Electron version: v5.0.1
Operating system: MaxOS 10.14.4

### Expected Behavior

As doc https://electronjs.org/docs/api/shell#shellopenexternalurl-options

### Actual Behavior

Link opened in the browser, but the browser is not brought to the foreground.

### To Reproduce

Upgrade electron to v5.0.1 in https://github.com/electron/electron-api-demos

And try "open external links" demo

**Comment by MarshallOfSound** [comment]
Duplicate of #18293
