### ISSUE TITLE
Suggested Security Recommendation

### ISSUE THREAD

**Issue by ryazo** [electron/electron#18335]
I suggest disabling jit as a security recommendation, as the project self-admittedly is behind on security updates. It seems irresponsible otherwise.

--js-flags="--jitless" would disable jit.

https://github.com/electron/electron/blob/master/docs/tutorial/security.md

**Comment by nornagon** [comment]
FWIW, `--js-flags` only affects code in the main process, which shouldn't be running anything untrusted anyway.

**Comment by nornagon** [comment]
Er, the above comment is actually incorrect—`--js-flags` does in fact affect the renderer process. However, I don't think `--jitless` by itself is a useful security hardening measure. Can you expand on why you think this would be a good recommendation?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Comment by mckravchyk** [comment]
@nornagon @codebytere 

There has been a recent article on this topic by Microsoft devs.

https://microsoftedge.github.io/edgevr/posts/Super-Duper-Secure-Mode/

> ... what if we simply disabled the JIT? This reduction of attack surface has potential to significantly improve user security; it would remove roughly half of the V8 bugs that must be fixed.

**Comment by mckravchyk** [comment]
It can decrease performance a bit so it would be really useful if it was possible to apply js-flags per renderer - or if it's too complex - apply flags for Node.js V8 and Chromium V8 separately, so it does not unnecessarily degrade performance on the main process (and UI renderer if possible).

Also it seems like WebAssembly is currently not supported in jitless mode. 

https://v8.dev/blog/jitless (2019)
> WebAssembly is currently unsupported, but interpretation is also in the realm of possibility 

but I think Microsoft Edge team will be working on it for their "super duper secure mode":

https://microsoftedge.github.io/edgevr/posts/Super-Duper-Secure-Mode/
> At the moment, Web Assembly is not supported in this mode. We hope to slowly enable new mitigations and add Web Assembly support over the next few months as we continue testing and experimentation
