### ISSUE TITLE
BrowserView: allow linking size and position to an Element

### ISSUE THREAD

**Issue by krisdages** [electron/electron#18342]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

I want to be able to position a BrowserView using CSS the same way that one can currently position a WebView, e.g. with flexbox, grid layout, inside a resizable div, etc.

I have tried styling a positioning element and using ResizeObserver to move the BrowserView on changes, but there is a noticeable lag between the element paint and the BrowserView moving, especially in the case of resizable.  

Also, (and this may be outdated), but the last time I tried, the BrowserView position required integer pixels, which caused problems with fractional pixel units and DPI.

### Proposed Solution

Provide a means to link the size, position, and visibility of a BrowserView to an Element on the page such that synchronizing them would be more responsive and accurate than the current methods. 

In a perfect world, zIndex would also be supported but I'm sure the implementation would have to be very different and that is a separate issue.

Something like this would go a long way toward being able to replace WebView.

### Alternatives Considered

ResizeObserver, manual placement

**Comment by choryfang** [comment]
I need it, especially zIndex.

**Comment by Xylobol** [comment]
I think is a good idea. I'm working on a project that pretty extensively embeds WebViews, and it'd be lovely to make positioning much easier. It'd also be nice to use CSS transforms on BrowserViews, but that's probably not going to happen.

**Comment by vikiCoder** [comment]
I need this feature too. I want to load a webpage inside another page which is loaded in a `webview`. Since nesting `webview` inside other `webview` is not supported, I thought to use `BrowserView` instead to load a nested page. But then I came across this issue and had to leave that idea too.

**Comment by miniak** [comment]
This is out of scope of the `BrowserView`
