### ISSUE TITLE
Support Taptic Engine

### ISSUE THREAD

**Issue by zhenshuaiwws** [electron/electron#18345]
In this way, touchbar can provide vibration feedback, such as _haptic touchbar_.

**Comment by miniak** [comment]
is there a public macOS API exposing this functionality?

**Comment by MarshallOfSound** [comment]
The touchbar itself does not have haptic feedback support and the haptic feedback APIs for the trackpad are entirely private so we can't use / expose them 👍 

If this changes in the future and apple releases new hardware / APIs we can reconsider this

**Comment by zhenshuaiwws** [comment]
> The touchbar itself does not have haptic feedback support and the haptic feedback APIs for the trackpad are entirely private so we can't use / expose them 👍
> 
> If this changes in the future and apple releases new hardware / APIs we can reconsider this

https://www.haptictouchbar.com/
Why can touch bar touch vibration feedback be achieved in this application?

**Comment by zhenshuaiwws** [comment]
> is there a public macOS API exposing this functionality?

@miniak Refer to this application ( https://www.haptictouchbar.com/ )
