### ISSUE TITLE
Electron apps going horribly blurry

### ISSUE THREAD

**Issue by martmists** [electron/electron#18344]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * Unknown
* **Operating System:**
  * Windows Home N 64-bit
* **Last Known Working Electron version:**:
  * Unknown

### Expected Behavior
Text and images in electron should be clear.

### Actual Behavior
Text looks horrible (see screenshots)

### To Reproduce

- Install StreamlabsOBS/Discord
- Wait
- Text goes blurry

### Screenshots

![image](https://user-images.githubusercontent.com/16361449/57960218-e417ae80-7907-11e9-8ab4-9db6037342a0.png)

### Additional Information
This does NOT happen on Linux versions.

**Comment by wirmachenbunt** [comment]
same here
![KKNluvxbVkXjMUQMzVnYiCmk](https://user-images.githubusercontent.com/1138673/70710774-396e3f80-1ce0-11ea-8172-12d38c1e8c31.png)

**Comment by GabrielBln** [comment]
I have the same issue. It can be reproduced by connecting a MacBook Air with a retina display to a non-retina display in clamshell mode. In my case it's an Apple Thunderbolt Display (which is QHD, not Retina) connecting via a Thunderbolt-to-USB-C-Adapter. I run Electron apps on the Thunderbolt Display perfectly fine and once I disconnect the MacBook, the apps become blurry on the laptop's screen.

**Comment by divmgl** [comment]
This is happening to me on Windows. It's infuriating. So many apps use Electron now and I have to disable hardware acceleration on all of these apps. Have we figured out what is causing this?

**Comment by codebytere** [comment]
Given that this is a consumer behavior and we have at no point received a reproducible example in Electron.js (by any end-user) we recommend that you instead open this issue on the apps where you're seeing this. We understand your frustration with this obviously bothersome behavior, but without any recourse for investigation it'll be doubtless more effective to being this to the apps themselves.

**Comment by martmists** [comment]
When this issue was initially created I was referred here from issues on those applications

**Comment by Cthululz** [comment]
Still happens to this day

**Comment by Gitoo22** [comment]
The issue is still valid. I use a laptop Lenovo Ideapad Y700 since 2017, and this issue occurs with several Electron apps : Joplin, Microsoft Teams, Wargaming Game Center. Each and every time I use then, after some seconds only, text blurrs. I can temporarily fix (only for few seconds) by displaying the app window full-screen, then not-full-screen again, or by moving the app window. It is a major issue, I love Joplin App...

**Comment by Gitoo22** [comment]
Update to my previous post this morning : There are workarounds !

Using this thread => [Electron 2.0.x : extreme blur around the entire application (Windows 10) #51789](https://github.com/microsoft/vscode/issues/51789) there are at least to workarounds : 
1. Force Microsoft Vista compatibility execution on the executable (but may affect performance)
2. Disable Nvidia FXAA anti-aliasing : On Nvida card Control panel, Manage 3D settings ,Adding your faulty application : Turning FXAA Off for this application.

I do have problem with the Nvidia panel which explodes (crashes) when I execute it, after some seconds. 😲 (but this is another issue - not related to Electron, I guess).

The thing is : I don't feel Electron is fixed at this day for this problem.  😢
