### ISSUE TITLE
Electron exits process without waiting for node.js event loop

### ISSUE THREAD

**Issue by mscdex** [electron/electron#18358]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.1, 6.0.0-beta.3, master
* **Operating System:**
  * Ubuntu 19.04 x64
* **Last Known Working Electron version:**
  * Unknown

### Expected Behavior
Node event loop allowed to complete after destroying/closing a BrowserWindow

### Actual Behavior
Process exits destroying/closing a BrowserWindow. Even delaying the destroying/closing of the window does not affect behavior.

### To Reproduce
```js
const { app, BrowserWindow } = require('electron');

app.on('ready', () => {
  const win = new BrowserWindow();
  win.destroy();

  setTimeout(() => {
    // Execution never reaches here
    console.log('here');
  }, 500);
});
```

**Comment by miniak** [comment]
There is a default handler for [`event-window-all-closed`](https://electronjs.org/docs/api/app#event-window-all-closed), which quits the app unless the event is handled:
> Emitted when all windows have been closed.

> If you do not subscribe to this event and all windows are closed, the default behavior is to quit the app; however, if you subscribe, you control whether the app quits or not. If the user pressed Cmd + Q, or the developer called app.quit(), Electron will first try to close all the windows and then emit the will-quit event, and in this case the window-all-closed event would not be emitted.

**Comment by miniak** [comment]
this should work
```
const { app, BrowserWindow } = require('electron');

app.on('window-all-closed', () => {
  // keep running
})

app.on('ready', () => {
  const win = new BrowserWindow();
  win.destroy();

  setTimeout(() => {
    // Execution never reaches here
    console.log('here');
  }, 500);
});
```

**Comment by mscdex** [comment]
I'm curious as to why this would be the default behavior? Couldn't `BrowserWindow` and other such functionality simply increase the reference counter for the node event loop and decrease when closed/destroyed? This way the process will exit naturally when there is nothing left to wait on and people already familiar with node.js won't be in for a surprise?

**Comment by MarshallOfSound** [comment]
@mscdex Electron has never and will never exit when the event loop is empty.  If you don't open a window, electron will keep running forever as you could be waiting for OS level events / user interaction.

That default behavior was introduced a long time ago as it is the expected behavior of most apps.  Once all the windows are closed, quit the app.

As @miniak pointed out, you can change this default behavior by adding a listener
