### ISSUE TITLE
Electron doesn't work on ARM64 when running as root

### ISSUE THREAD

**Issue by gamelaster** [electron/electron#18350]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.0
* **Operating System:**
  * Ubuntu Bionic, aarch64 (SOPine A64, Allwinner A64), Kernel 5.1.0
* **Last Known Working Electron version:**:
  * 4.2.2

### Expected Behavior
Should start an app or print the actual version

### Actual Behavior
2 seconds after executing, app just stop (gdb not showing any issue or crash). Even if I just execute `electron --version`, same behavior

### To Reproduce
Just run electron-quick-start

### Screenshots
![Running Electron v5.0.0 with gdb](https://user-images.githubusercontent.com/1665373/57975466-b430df80-79c9-11e9-97e0-c97d049b64f6.png)
![Electron v4.2.2 works just fine](https://user-images.githubusercontent.com/1665373/57975511-813b1b80-79ca-11e9-8929-d6c57513665f.png)

### Additional Information

Because there isn't any verbosity, error or crash, I'm really clueless why it's not working. Since the older version works fine, I don't expect that it's OS issue, but I can be wrong.
EDIT: Also tested @6.0.0-beta.3 , same issue

**Comment by eatmyvenom** [comment]
Do you by chance have electron installed globally. Maybe it's requiring from some other folder for some reason.

**Comment by gamelaster** [comment]
Hi @eatmyvenom . I tested global and also local (npm_modules) installation, I don't think it's environment problem, I think it would act differently (showing some error, at least in GDB). Maybe, I can try also Raspberry Pi (armhf), I think it will be same

**Comment by jkleinsc** [comment]
@gamelaster can you set the following environment variables and then retry launching electron-quick-start:
```sh
export ELECTRON_ENABLE_LOGGING=true
export ELECTRON_ENABLE_STACK_DUMPING=true
```

This should provide better insight into why it is crashing.

**Comment by gamelaster** [comment]
```
[3355:0531/001053.631114:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
```
When tested on non-root user, it worked finely. I think this should be handled and checked by electron and write error if user is root?

**Comment by jkleinsc** [comment]
@gamelaster I agree that we should handle it more gracefully and opened an issue here to track this: #18547
