### ISSUE TITLE
Updating existing application error in "require"

### ISSUE THREAD

**Issue by dariomadeira** [electron/electron#18356]
I have an app in electron, it works fine !.
I always update it with the command "npm install --save-dev electron@latest" and I've never had problems. In this latest version the update works... but the app no ​​longer runs! indicating an error of "require" is not defined. Excuse my English.

**Comment by miniak** [comment]
in Electron 5, the `noteIntegration` option in `webPreferences` is set to `false` by default for security reasons. You need to explicitly set it to `true`.

**Comment by miniak** [comment]
```
  mainWindow = new BrowserWindow({
    webPreferences: {
      nodeIntegration: true
    }
  })
```

**Comment by dariomadeira** [comment]
Oh Thanks! i Will Try!
