### ISSUE TITLE
child_process requires sudo outside of main process

### ISSUE THREAD

**Issue by cawoodm** [electron/electron#18357]
Ubuntu Linux Latest - Latest Electron 4.2.2.

I have an electron app which works wonderfully in windows and has a whole lotta problems in Linux*.

This issue is about a child_process "pwsh" which runs fine in the main process but not in the renderer process (my browser window). I've added the code below.

**Main Process Output**:
```
OK
STDOUT Sunday, May 19, 2019 7:39:58 PM
```

**Renderer Process Output**:
```
OK
STDOUT need to run as root or suid
```

```javascript
const PowerShell = require("powershell");
let ps = new PowerShell("Get-Date", {PSCore:"pwsh",debug:true}, (err, stdout, stderr) => {
    if (err === null) {
        // We trim because of extra trailing newline
        if (stdout) console.log("STDOUT", stdout.trim());
        if (stderr) console.log("STDOUT", stderr.trim());
    }
    else {
        console.log("ERROR", err);
    }
});
ps.on("error", (err) => {
    console.log("ERROR", err);
});
console.log("OK")
``` 

* Other issues include `electron .` not starting my app (popping up some default app telling me to supply the path) even though I have a package.json pointing `"main": "app.js"` whereas `electron app.js` works fine.

**Comment by nornagon** [comment]
Hi, thanks for reaching out! In order to better diagnose the issue here, we need a way to reproduce it. Please provide either a [fiddle](https://github.com/electron/fiddle) or fork [electron-quick-start](https://github.com/electron/electron-quick-start) and make the smallest change you can to cause the issue to occur.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
