### ISSUE TITLE
App crashing after file upload window appears

### ISSUE THREAD

**Issue by JB1905** [electron/electron#18353]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
App crashing after file upload window appears

* **Electron Version:**
  * 6.0.0 beta 3
* **Operating System:**
  * macOS 10.14.5 / 10.14.6 beta 1
* **Last Known Working Electron version:**
  * 5.0.1

### Expected Behavior
Electron does not crash

### Actual Behavior
App crashing after file upload window appears

### To Reproduce
Install Electron v6.0.0 beta 3
Add input type file
Click on upload file input

**Repo fork:**
https://github.com/JB1905/electron-quick-start

![demo](https://user-images.githubusercontent.com/28870390/57982166-057cb580-7a42-11e9-816e-00596f6a33f7.gif)

**Comment by MarshallOfSound** [comment]
Duplicate https://github.com/electron/electron/issues/18347
