### ISSUE TITLE
Copy/Paste text with CMD+C/CMD+V 

### ISSUE THREAD

**Issue by MatthewB19** [electron/electron#18365]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
Lots of users would like to be able to copy/paste text using CMD+C/CMD+V without having to manually set up a "menu" in the main process.

### Proposed Solution
Add native CMD+C and CMD+V copy/pasting without needing to manually implement a menu.

### Alternatives Considered
The alternative is having the user implement a menu in the main process. However, this is inconvenient and far from ideal.

### Additional Information
The issue has been mentioned before in other threads, such as: #1902

**Comment by miniak** [comment]
@MatthewB19 please use the appropriate template for either a bug report or feature request.

**Comment by miniak** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by miniak** [comment]
@MatthewB19 are we talking about macOS or all platforms?

**Comment by MatthewB19** [comment]
Correct. It's just for MacOS.
I have already done some research and it's definitely a known issue.

**Comment by vladimiry** [comment]
Enabling CMD+C/CMD+V without context menu is already feasible but it requires custom implementation (custom event listening and then triggering the copy/cut action on `webContents`).

**Comment by codebytere** [comment]
The maintainers agree with @vladimiry above: this isn't something we think is something we'd want to add as maintenance overhead when it's already possible by means of event listening and accelerators.
