### ISSUE TITLE
BrowserWindow should be capable of targeting dedicated monitors

### ISSUE THREAD

**Issue by queequac** [electron/electron#1836]
In case of multiple monitors it would be great if it would be possible to target a dedicated monitor a BrowserWindow shall be displayed on.

The current API provides the same limited possibilities a browser does. Fullscreen works only on the primary monitor and placing windows on different monitors requires knowledge about the user's actual setup to do this by coordinates only.

Would it be possible to add an additional option for BrowserWindows that allows specifying the target monitor?

**Comment by paulcbetts** [comment]
Have you seen the Screen API? You should be able to pretty easily target specific monitors by getting their working area

**Comment by frankhale** [comment]
As an aside, if a browser window is on a second screen, dialogs are popped up on the first screen. I've noticed this with Atom and specifically with the dialog that pops up if you check for an update and there are none. This may need to be made into a separate issue if there is interest in it.

**Comment by queequac** [comment]
@paulcbetts You are right... but targeting a dedicated display would be much more easy if done by the BrowserWindow itself instead of writing such ugly glue code to manipulate the coordinates. I'd still vote for adding an additional BrowserWindow option.

@frankhale I am undecided. On the one hand you are right, this might be a separate issue. On the other hand, if the BrowserWindow would know the display it belongs to, a dialog that got handed over the BrowserWindow as optional parameter could simply be shown on that same display. But good point, these things are definitely linked to each other and strenghens my feeling that a BrowserWindow should explicitely know about the display it belongs to.

**Comment by rjmunro** [comment]
+1 to making this simpler. I'm making software for presentations, so I the ability to open a "display" window full screen on the "other" monitor when the user presses "go"

**Comment by sboekhoff** [comment]
I'm working on a Laptop with an additional display. That display is set `primary` in the system-settings of Linux Mint. Unless I turn it off, my app always shows up on the display of the laptop. So I always have to move it over to my "working display". :angry:

It would be great to detect the active display and add it as a parameter to the constructor of BrowserWindow.

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR.

**Comment by mix3d** [comment]
That's too bad it's a wont-fix, since that basically will prevent us from being able to adopt Electron for the desktop replacement app we were about to start on. In our use-case, multimonitor and monitor specific window targeting was 100% the critical feature.

**Comment by vidartf** [comment]
Maybe a "status/contribute" would help indicate that this is something that would be acceptable in core, but isn't a priority, just from a communication standpoint. That might help communicate that core isn't *opposed* to the idea, but won't initiate the effort either 😄

**Comment by vidartf** [comment]
OTOH, if somebody knows of good userland implementations of such functionality, that would be much appreciated 🥇

**Comment by mix3d** [comment]
Here's the general solution we settled on, even though it runs into a different bug I've identified

```JS
function openWindowOnMonitor(monitorId){
    const monitor = (monitorId && screen.getAllDisplays().find(monitor => monitor.id === monitorId)) || screen.getPrimaryDisplay()
    const { x, y } = monitor.bounds
    const {width, height} = monitor.size
    const newWindow = new BrowserWindow({
        show: false,
        x,
        y,
        width,
        height,
        webPreferences: { ... etc},
    })

    // MacOS can handle maximizing ahead of time without showing, which is technically a bug
    // https://github.com/electron/electron/issues/24375
    if (process.platform === 'darwin') newWindow.maximize()
    return newWindow
}
