### ISSUE TITLE
how to get dom when i use  mainWindow

### ISSUE THREAD

**Issue by tianxia0079** [electron/electron#18379]
how to get dom when i use 
`
mainWindow = new BrowserWindow({..
mainWindow.loadURL('http://abc.cn/index.jsp');

`

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
