### ISSUE TITLE
webFrame.findFrameByRoutingId and webFrame.firstChild returns frames only if they belong to the same domain.

### ISSUE THREAD

**Issue by Lukich** [electron/electron#18371]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
5.0.1
* **Operating System:**
OSX 10.13.1
* **Last Known Working Electron version:**:
4.1.4

### Expected Behavior
When calling webFrame.findFrameByRoutingId and webFrame.firstChild in the preload script for a page with iframes I should be able to get a reference to the frame and perform executeJavaScript call on it regardless of the domain it belongs to.

### Actual Behavior
For all frames belonging to a domain different from the top domain of the page these two commands return null.

### To Reproduce

https://github.com/Lukich/webFrame-bug-report.git

```sh
$ git clone https://github.com/Lukich/webFrame-bug-report.git
$ electron .
```

**Comment by bughit** [comment]
The WebFrame docs mention that only frames in the same renderer process can be returned. I'm guessing the iframe isolation model has changed to put different domains in different processes. Don't know if there's any control over that.

**Comment by bughit** [comment]
Access to the the full frame hierarchy would have to be exposed in the browser (main process), #17252

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
