### ISSUE TITLE
Dose electron support activeX control?

### ISSUE THREAD

**Issue by LitchGZ** [electron/electron#18375]
I have an ActiveX control mstscax.dll is RDP Client Controller. 
And now I want to use electron create a application to invoke this activex control to do RDP connection.
Dose electron support activeX control?

My environment is as below:
Nodejs version: v10.15.3
npm version: 6.4.1
electron version: v5.0.1
OS version: Windows 10
mstscax.dll: version 9

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by hbb520** [comment]
同求
