### ISSUE TITLE
"require" not working in a seperate file  ?

### ISSUE THREAD

**Issue by alexs7** [electron/electron#18388]
I have a straightforward `main.js` file as below:

```
const {app, BrowserWindow} = require('electron')
const path = require('path')
const url = require('url')

let win

function createWindow () {
  // Create the browser window.
  win = new BrowserWindow({ width: 1280, 
                            height: 720, 
                            nodeIntegration: true, 
                            resizable: false,
                            maximizable: false })

  // and load the index.html of the app.
  win.loadFile('index.html')

  // Open the DevTools.
  win.webContents.openDevTools()

  // Emitted when the window is closed.
  win.on('closed', () => {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    win = null
  })
}

app.on('ready', createWindow)

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  if (win === null) {
    createWindow()
  }
})
```

I also have an _init.js_ file that I only have 1 line of code in it.

`const fs = require('fs');`

Now I have tried and searched online for multiple solutions but nothing works so I am raising an issue here.

I tried this aswell: [https://stackoverflow.com/a/44394999](https://stackoverflow.com/a/44394999) - with no success.

I keep getting `Uncaught ReferenceError: require is not defined`

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by alexs7** [comment]
I finally got it sorted `nodeIntegration: true` should have been in `webPreferences` block.

**Comment by alexs7** [comment]
I finally got it sorted `nodeIntegration: true` should have been in `webPreferences` block!

**Comment by sgehrman** [comment]
I also starting seeing problems with require this morning.  Not sure how it's been working fine for years now.

I also didn't have nodeIntegration: true set.  I set it and it now works.
