### ISSUE TITLE
fs.readFileSync behaviour changed

### ISSUE THREAD

**Issue by phil-ide** [electron/electron#18387]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.1
* **Operating System:**
  * Windows 10 (1803)
* **Last Known Working Electron version:**
  * 4.2.2

### Expected Behavior

Under electron 4.2.2 I can do this:
buildFile = path.join( __dirname, 'build.jz');
build = fs.readFileSync(buildFile);

Result: 'build' is the contents of the file. This works both in development mode and after building the package.

### Actual Behavior

Under electron 5.0.1 the contents are not read. No error is raised.

The file build.jz is the first file in the asar.

I'm fairly new to electron, so I'm not sure which version of electron has the correct behaviour, but according to the docs fs.readFileSync should handle files in the asar transparently.

I saw a previous report which seemed similar (from a few years back), and the solution was to set the filename to './resources/app.asar/'+filename. I tried that, and still got nothing back.

### Additional Information

I can, of course, continue to use electron 4.2.2, however it means my application is stuck in limbo, unable to upgrade to newer versions of electron  which may introduce features I want to use.

The file 'build.jz' simply contains a number, being the number of times the application was run during development. In development mode, this number is incremented and written back to the file each time the application is launched. In non-development mode, I simply read the file.

**Comment by MarshallOfSound** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
