### ISSUE TITLE
Debugger attach make Network requests never finish

### ISSUE THREAD

**Issue by 4eveRS** [electron/electron#18394]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.1
* **Operating System:**
  * MacOS Mojave 10.14.4
* **Last Known Working Electron version:**
  * ???

### Expected Behavior
Debugger attach should not interfere in network requests life cycle.

### Actual Behavior

If you attach a debugger, enable Network protocol, and start listening to network events, it never finish requests that return a status 304. (Keep the request pending, which lead to many network events to not fire)

If you don't attach a debugger and inspect the requests in the devtools, you will notice that the request still return a status 304, but it actually finishes.

### To Reproduce
https://gist.github.com/9063af3c26448ece4d7f776a887246c7

### Additional Information

Before questioning why I'm using the debugger to analyse the requests instead of using webRequest or even the webview / webContent events, it's because it returns all headers, detailed timing and many other data.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
