### ISSUE TITLE
showOpenDialog returns parent directory if selected directory is in iCloud only

### ISSUE THREAD

**Issue by justinjdickow** [electron/electron#18404]
### Preflight Checklist
I didn't actually read these so I can't check them (at least I'm honest?)

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v5.0.1
* **Operating System:**
  * macOS 10.14.5
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
I'm not really sure

### Actual Behavior
If the user selects a directory via showOpenDialog that is remote (i.e in iCloud) and not downloaded locally to their computer, then showOpenDialog returns the parent directory instead of the selected one

### To Reproduce
Go into finder and locate a directory that is in iCloud and not downloaded locally, as indicated by the cloud symbol

![Screen Shot 2019-05-22 at 7 34 38 AM](https://user-images.githubusercontent.com/3627664/58171481-1d338400-7c64-11e9-8860-25843dc68162.png)

Then use showOpenDialog in Electron and select that directory

```
electron.dialog.showOpenDialog({
    properties: ['openDirectory', 'createDirectory']
  }, (filePaths) => {
    console.log(filePaths)
  })
```

And filePaths[0] will contain the parent directory instead of the selected directory

**Comment by MarshallOfSound** [comment]
@justinjdickow Can you confirm what the behavior here is in Chrome?

**Comment by justinjdickow** [comment]
@MarshallOfSound 
If you try to open a file that's in iCloud in Chrome the open button is disabled in the dialog

If you open a location that's in iCloud by typing the absolute path directly into the browser it shows the directory listing with `.icloud` appended to every file

**Comment by codebytere** [comment]
This unfortunately is a long-standing Apple bug that's not fixable on our side: see http://www.openradar.me/27966701 for more details.
