### ISSUE TITLE
electron.d.ts — Protocol handler callbacks should allow error responses

### ISSUE THREAD

**Issue by mjbvz** [electron/electron#18407]
### Issue Details

* **Electron Version:**
  * 6.0 beta 4
* **Operating System:**
  * NA
* **Last Known Working Electron version:**
  * Unknown. I believe it's been broken since at least 2.x

### Expected Behavior
For the [protocol apis](https://electronjs.org/docs/api/protocol), the handler callbacks allow you to surface errors:

> When callback is called with nothing, a number, or an object that has an error property, the request will fail with the error number you specified.

The typings for this would look something like:

```ts
registerBufferProtocol(
    scheme: string,
    handler: (request: RegisterBufferProtocolRequest, callback: (buffer?: (Buffer) | (MimeTypedBuffer) | number | { error: number }) => void) => void,
    completion?: (error: Error) => void): void;
```

### Actual Behavior
The current d.ts typings for these do not support returning errors:

```ts
registerBufferProtocol(
    scheme: string,
    handler: (request: RegisterBufferProtocolRequest, callback: (buffer?: (Buffer) | (MimeTypedBuffer)) => void) => void,
    completion?: (error: Error) => void): void;
```

### To Reproduce
Try using the typescript:

```ts
import { app, protocol }  from 'electron'

app.on('ready', () => {
  protocol. registerBufferProtocol('atom', (request, callback) => {
      callback({ error: -10 }); // This call should be valid
  })
})
```

**Comment by nornagon** [comment]
I believe this is fixed now, let me know if that's not the case and we can reopen.
