### ISSUE TITLE
Accented character picker produces two letters instead of one

### ISSUE THREAD

**Issue by mfilej** [electron/electron#18405]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
3.1.6 ([according to package.json](https://github.com/desktop/desktop/blob/release-1.6.6/package.json#L167))
* **Operating System:**
macOS 10.14.4 (18E226)
* **Last Known Working Electron version:**
n/a

### Expected Behavior
Typing a word using the macOS accented character picker, I would expect each typed letter to appear once.

### Actual Behavior
When typing a letter with the accented character picker, if the letter that follows the accented character is typed too soon, both the accented and unaccented version of the letter will appear.

### To Reproduce
Press-and-hold a key to trigger the accented character picker (for example `a`). When the picker appears, choose a number (for example `1`), then type any letter immediately afterwards (for example `q`). The result will be `aàq` instead of `àq`. Waiting for some amount of time before pressing `q` will avoid the issue.

This can be reproduced in any electron app. Examples include Slack 3.4.2-beta4 HEAD/79ae6a5, GitHub Desktop 1.6.6, and Discord 0.0.255. It does not happen in non-electron apps.

### Screenshots

Demo:
![accent_demo_fast 2019-05-22 16_35_33](https://user-images.githubusercontent.com/3621/58184591-b0df7180-7cb1-11e9-9bde-3681f85630f1.gif)

Avoiding issue by waiting before the last keystroke:
![accent_demo_slow 2019-05-22 16_34_52](https://user-images.githubusercontent.com/3621/58184607-b76de900-7cb1-11e9-9253-f981c6f6a7c2.gif)

### Similar issues

I found this fixed issue, but it looks like there wasn't a timing component involved.
https://github.com/electron/electron/issues/3379

**Comment by shiftkey** [comment]
@mfilej if you were to test this with a later version of Electron (using the https://github.com/electron/electron-quick-start test project and rendering a plain `input` or `textarea`) do you still see the issue?

**Comment by mfilej** [comment]
@shiftkey I was able to reproduce the issue with both `input` and `textarea`.

**Comment by shiftkey** [comment]
@mfilej could you publish that up somewhere the maintainers can access and run themselves? That will help with speeding up the process of better understanding this bug and why it's happening.

**Comment by mfilej** [comment]
@shiftkey Done: https://github.com/mfilej/electron-quick-start
Let me know if there is anything else I can do to speed up the process.

**Comment by mfilej** [comment]
I forgot to mention that I reported this issue here because similar issues (like the one [I linked to][issue]) have been fixed in the past. However the behaviour seems to originate from chromium (I can reproduce it in all chrome browsers). I reported the issue here as well: https://bugs.chromium.org/p/chromium/issues/detail?id=966007

[issue]: https://github.com/electron/electron/issues/3379

**Comment by shiftkey** [comment]
@mfilej if this is reproducible in Chromium then it's probably not something that the apps can address easily. Let's see what the maintainers there and here suggest.

**Comment by codebytere** [comment]
Closing as this is an upstream issue and not one that can be addressed by Electron. They've closed the upstream issue, but should something change we can assuredly reopen.
