### ISSUE TITLE
electron crashed

### ISSUE THREAD

**Issue by wuwei2150** [electron/electron#18414]
* **Electron Version:*3.1.1*
* **Operating System:*windows10,x64*
* **Last Known Working Electron version:*no version*

FAULTING_IP: 
qzk_wk!ui::Compositor::SetScaleAndSize+d [c:\projects\libchromiumcontent-wqq1s\src\ui\compositor\compositor.cc @ 352]
015ab53f f30f1086bc000000 movss   xmm0,dword ptr [esi+0BCh]

EXCEPTION_RECORD:  ffffffff -- (.exr 0xffffffffffffffff)
ExceptionAddress: 015ab53f (qzk_wk!ui::Compositor::SetScaleAndSize+0x0000000d)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 00000000
   Parameter[1]: 000000bc
Attempt to read from address 000000bc

PROCESS_NAME:  qzk.wk.exe

ADDITIONAL_DEBUG_TEXT:  
Use '!findthebuild' command to search for the target build information.
If the build information is available, run '!findthebuild -s ; .reload' to set symbol path and load symbols.

MODULE_NAME: qzk_wk

FAULTING_MODULE: 77330000 ntdll

DEBUG_FLR_IMAGE_TIMESTAMP:  5c3d1523

ERROR_CODE: (NTSTATUS) 0xc0000005 - 0x%p

EXCEPTION_CODE: (NTSTATUS) 0xc0000005 - 0x%p

EXCEPTION_PARAMETER1:  00000000

EXCEPTION_PARAMETER2:  000000bc

READ_ADDRESS:  000000bc 

FOLLOWUP_IP: 
qzk_wk!ui::Compositor::SetScaleAndSize+d [c:\projects\libchromiumcontent-wqq1s\src\ui\compositor\compositor.cc @ 352]
015ab53f f30f1086bc000000 movss   xmm0,dword ptr [esi+0BCh]

MOD_LIST: <ANALYSIS/>

FAULTING_THREAD:  000024d0

BUGCHECK_STR:  APPLICATION_FAULT_STRING_DEREFERENCE_NULL_CLASS_PTR_DEREFERENCE_INVALID_POINTER_READ_WRONG_SYMBOLS

PRIMARY_PROBLEM_CLASS:  STRING_DEREFERENCE

DEFAULT_BUCKET_ID:  STRING_DEREFERENCE

LAST_CONTROL_TRANSFER:  from 01526ba7 to 015ab53f

STACK_TEXT:  
075ae30c 01526ba7 3f800000 075ae350 1f5abe58 qzk_wk!ui::Compositor::SetScaleAndSize+0xd [c:\projects\libchromiumcontent-wqq1s\src\ui\compositor\compositor.cc @ 352]
075ae358 015fec25 075ae388 1f76bbf8 075ae390 qzk_wk!aura::WindowTreeHost::OnHostResizedInPixels+0x53 [c:\projects\libchromiumcontent-wqq1s\src\ui\aura\window_tree_host.cc @ 357]
075ae368 015fb2b9 075ae388 1f76bbf8 00000000 qzk_wk!views::DesktopWindowTreeHostWin::HandleClientSizeChanged+0x25 [c:\projects\libchromiumcontent-wqq1s\src\ui\views\widget\desktop_aura\desktop_window_tree_host_win.cc @ 842]
075ae390 0160487d 00000047 1f76bbf8 075ae3c8 qzk_wk!views::HWNDMessageHandler::ClientAreaSizeChanged+0x3f [c:\projects\libchromiumcontent-wqq1s\src\ui\views\win\hwnd_message_handler.cc @ 1217]
075ae3a0 01609744 075ae664 00000000 1f76bbf8 qzk_wk!views::HWNDMessageHandler::OnWindowPosChanged+0x18 [c:\projects\libchromiumcontent-wqq1s\src\ui\views\win\hwnd_message_handler.cc @ 2548]
075ae3c8 01604eca 000721e2 00000047 00000000 qzk_wk!views::HWNDMessageHandler::_ProcessWindowMessage+0x6a3 [c:\projects\libchromiumcontent-wqq1s\src\ui\views\win\hwnd_message_handler.h @ 455]
075ae408 0153dfac 00000001 00000000 075ae664 qzk_wk!views::HWNDMessageHandler::OnWndProc+0x6a [c:\projects\libchromiumcontent-wqq1s\src\ui\views\win\hwnd_message_handler.cc @ 950]
075ae424 0152d7c5 000721e2 00000047 00000000 qzk_wk!gfx::WindowImpl::WndProc+0x53 [c:\projects\libchromiumcontent-wqq1s\src\ui\gfx\win\window_impl.cc @ 304]
075ae468 7516e0bb 000721e2 00000047 00000000 qzk_wk!base::win::WrappedWindowProc<&gfx::WindowImpl::WndProc>+0x25 [c:\projects\libchromiumcontent-wqq1s\src\base\win\wrapped_window_proc.h @ 76]
WARNING: Stack unwind information not available. Following frames may be wrong.
075ae494 75178849 0152d7a0 000721e2 00000047 user32+0x1e0bb
075ae4b8 7517b145 00000047 00000000 075ae664 user32+0x28849
075ae588 75168503 0152d7a0 00000000 00000047 user32+0x2b145
075ae5f0 75160328 0a4f1450 00000000 00000047 user32+0x18503
075ae638 773a0bad 075ae654 00000038 075af77c user32+0x10328
075ae6c0 002ad24f 0e3d6afc 002ad0e0 00000000 ntdll+0x70bad
075ae70c 075ae748 0028ff13 1f7d4550 1f7d4568 qzk_wk!atom::api::BrowserWindow::OnCloseContents+0x16f [c:\projects\electron-39ng6\atom\browser\api\atom_api_browser_window.cc @ 205]
075ae710 0028ff13 1f7d4550 1f7d4568 0e3d6af4 0x75ae748
075ae744 075ae75c 0125e265 1f7d4550 029bc838 qzk_wk!atom::api::WebContents::CloseContents+0xd3 [c:\projects\electron-39ng6\atom\browser\api\atom_api_web_contents.cc @ 604]
075ae74c 1f7d4550 029bc838 1f7d4568 075ae784 0x75ae75c
075ae750 029bc838 1f7d4568 075ae784 0125e282 0x1f7d4550
075ae754 1f7d4568 075ae784 0125e282 1f7e62d8 qzk_wk!content::WebContentsImpl::`vftable'
075ae758 075ae784 0125e282 1f7e62d8 1f7d4550 0x1f7d4568
075ae75c 0125e282 1f7e62d8 1f7d4550 0125e270 0x75ae784
075ae768 0125e26f 002ad3a9 0e3d6aa4 002ad320 qzk_wk!content::WebContentsImpl::Close+0x12 [c:\projects\libchromiumcontent-wqq1s\src\content\browser\web_contents\web_contents_impl.cc @ 3431]
075ae784 00329f7a 075ae7a3 1f653ad8 1f653ad8 qzk_wk!content::WebContentsImpl::Close+0x2f
075ae7c8 a84174e2 00000001 075ae804 0032d72b qzk_wk!atom::NativeWindow::NotifyWindowCloseButtonClicked+0x16a [c:\projects\electron-39ng6\atom\browser\native_window.cc @ 393]
075ae7cc 00000000 075ae804 0032d72b 0154306f 0xa84174e2

STACK_COMMAND:  ~0s; .ecxr ; kb

SYMBOL_STACK_INDEX:  0

SYMBOL_NAME:  qzk_wk!ui::Compositor::SetScaleAndSize+d

FOLLOWUP_NAME:  MachineOwner

IMAGE_NAME:  qzk.wk.exe

BUCKET_ID:  WRONG_SYMBOLS

FAILURE_BUCKET_ID:  STRING_DEREFERENCE_c0000005_qzk.wk.exe!ui::Compositor::SetScaleAndSize

Followup: MachineOwner
---------

**Comment by codebytere** [comment]
@wuwei we can't triage this without more information about the code you were running to cause this and a minimal repro that we can use to locally test it.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
