### ISSUE TITLE
When app starts during auto-updating, error occurs for "require" statement

### ISSUE THREAD

**Issue by ervinewell** [electron/electron#18418]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.1.0/ 1.8.6
* **Operating System:**
  * macOS 10.14

### Expected Behavior
When I received an available update, I quit the app, and restart it in a second.
At this time, update isn't done, so app will restart with the old version.
When update is done, executing "require('./xxx')" should run well

### Actual Behavior
When update is done, application will be replaced to new version.
At this time, when executing "require('./xxx')",  the dependency cannot  found as it has been deleted in the new version.

### To Reproduce
Prepare a ready-to-update app,  restart in a second

**Comment by MarshallOfSound** [comment]
@ervinewell This is expected behavior, if you restart the app after the update has been downloaded but before it has finished being applied when you restart the app it will be in a broken state.  You need to ensure you don't call `app.quitAndInstall()` until `update-downloaded` is emitted.
