### ISSUE TITLE
Main window flickers with maximizing and fullscreen

### ISSUE THREAD

**Issue by katiamoklokova** [electron/electron#18410]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  Electron 4.1.3, 4.2.1, 5.0.0-beta6 and 6.0.0-beta2
* **Operating System:**
  *  macOS 10.14.4
* **Last Known Working Electron version:**
  *  3.1.7

### Expected Behavior

Maximizing/restoring and toggling/exiting fullscreen shouldn't cause the main window to flicker.

### Actual Behavior

Main window flickers when the app is maximized/restored or if fullscreen is toggled/exited.

### To Reproduce

1. Launch an Electron app
2. Maximize and restore the main window
3. Toggle and exit fullscreen

### Screenshots

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/20443967/58202821-6ba94880-7c8d-11e9-8950-fd7491feee57.gif)

**Comment by codebytere** [comment]
@katiamoklokova do you by chance have a more minimal repro? I would hedge at first glance that this is resultant of a specific combination of `titleBar` and `BrowserWindow` options, so it would definitely help if we had a better idea of which ones are in play here!

**Comment by MarshallOfSound** [comment]
@codebytere I can repro on the default app.  The flash happens whenever you transition between fullscreen and normal

**Comment by MarshallOfSound** [comment]
Fixed in #18661
