### ISSUE TITLE
desktopCapturer.getSources() doesn't obtain all windows

### ISSUE THREAD

**Issue by Inviles** [electron/electron#18417]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v5.0.0 & v4.0.1
* **Operating System:**
  * Windows 10 (1809) & MacOS 10.14.4
* **Last Known Working Electron version:**
  *  N/A

### Expected Behavior
The expected behavior is desktopCapturer.getSources() to return all opened windows.

### Actual Behavior
The actual behavior is:
- On Windows the method doesn't obtain and return standard windows (like Settings) as well as minimized windows
- On MacOS the method doesn't return windows that are placed on another desktop (spaces). For example, fullscreen windows 

### To Reproduce
```bash
# Clone this repository
$ git clone https://github.com/Inviles/electron-getsources-example.git
# Go into the repository
$ cd electron-getsources-example
# Install dependencies
$ npm install
# Run the app
$ npm start

// If npm start does not work (for some reason it was not on my virtual Windows machine) you could use: npm run build:win
```

### Screenshots
https://monosnap.com/file/SxF3KlL5sV7TSgS4dbxCRMZ123gFm8

**Comment by codebytere** [comment]
Merging into https://github.com/electron/electron/issues/17767

**Comment by codebytere** [comment]
@Inviles re the second issue
> On MacOS the method doesn't return windows that are placed on another desktop (spaces). For example, fullscreen windows

it does actually, but the issue is that it does _sometimes_ meaning there's nondeterminism happening here likely resultant of some kind of race. I'm planning on digging into this more soon.
