### ISSUE TITLE
[BUG] Windows 10 ANOMALY: use of REX.w is meaningless (default operand size is 64)

### ISSUE THREAD

**Issue by iMegaMaximus2** [electron/electron#18415]
Windows 10 x64 last update

I run electron-quick-start app and have `ANOMALY: use of REX.w is meaningless (default operand size is 64)` in console

![image](https://user-images.githubusercontent.com/49617181/58224249-a78fec80-7d25-11e9-9817-6a815825a78c.png)

**Comment by eatmyvenom** [comment]
Just to make sure, this is the latest version of the electron-quick-start right? If you don't know then just try updating anyway. Otherwise try npm install again. If that does not work then maybe it's an or a weird error message with chromium.

**Comment by iMegaMaximus2** [comment]
@eatmyvenom is v5.0.1
Now I will try to install beta and alpha, and check

**Comment by iMegaMaximus2** [comment]
@eatmyvenom  electron@6.0.0-beta.4 has no errors =) thank. Apparently this is some kind of internal chrome error.
