### ISSUE TITLE
nodeIntegrationInSubFrames webview attribute causes preload script to run multiple times

### ISSUE THREAD

**Issue by Tim91084** [electron/electron#18429]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  5.0.1
* **Operating System:**
  windows
* **Last Known Working Electron version:**
  n/a

### Expected Behavior
A preload script should run only 1 time for each webContents / iframe

### Actual Behavior
The preload script appears to run multiple times

### To Reproduce
https://github.com/Tim91084/electron-node-subframe-issue/tree/node-in-subframe-runs-too-often

```sh
$ git clone https://github.com/Tim91084/electron-node-subframe-issue.git -b node-in-subframe-runs-too-often
$ npm install
$ npm start || electron .
```

### Screenshots
![image](https://user-images.githubusercontent.com/5086428/58273769-63b9d900-7d5f-11e9-8d30-1525dea34ce3.png)

**Comment by codebytere** [comment]
cc @brenca

**Comment by miniak** [comment]
@Tim91084 does it reproduce in Electron 6?

**Comment by miniak** [comment]
This issue not platform dependent, I have a repro on Mac as well.
