### ISSUE TITLE
Accelerator string in menu item always greyed out on Windows even if menu item is enabled

### ISSUE THREAD

**Issue by Mi6a** [electron/electron#18424]
* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 5.0.0
* **Operating System:** Windows 10 (1809) 
* **Last Known Working Electron version:** Unknown (tested 4.*)

### Expected Behavior
Accelerator string in menu item is shown in the same color as menu string itself.

### Actual Behavior
Accelerator string in menu item is always shown as disabled (light grey), ev

### To Reproduce
https://github.com/electron/electron-api-demos
$ git clone https://github.com/electron/electron-api-demos
$ cd electron-api-demos
$ npm install
$ npm start
Look at any menu item with accelerator - like "Copy"

### Additional Information
!!! Same is not reproduced in https://github.com/electron/electron-quick-start
![electron-api-demos_BUG](https://user-images.githubusercontent.com/13664434/58266044-924ca980-7d89-11e9-9c0d-87a3865d839c.PNG)
![electron-quick-start_OK](https://user-images.githubusercontent.com/13664434/58266061-9b3d7b00-7d89-11e9-8a3e-8cef01253bcc.PNG)

**Comment by Mi6a** [comment]
Apparently electron-quick-start using just default electron menu.
While electron-api-demos uses :
  const menu = Menu.buildFromTemplate(template)
  Menu.setApplicationMenu(menu)
In our app for windows we call win.setMenu(menu), but result is the same.

**Comment by DeerMichel** [comment]
Hey, thanks for reaching out. I tried to reproduce your issue under Windows 10 (1809). The accelerators are displayed properly for v5.x and newer. For v4.x the accelerators are greyed out as you said. So this seems to be the opposite behavior of what you described (see Electron Version vs. Last Known Working), right?

**Comment by electron-triage** [comment]
@Mi6a Please upgrade to a later version of Electron as we are no longer supporting versions older than 6.x.y per our [supported versions policy](https://www.electronjs.org/docs/tutorial/support#supported-versions). Feel free to reach out if you are experiencing this on a later version of Electron and we can reopen.
