### ISSUE TITLE
In electron v5.0.2, I can not find process.

### ISSUE THREAD

**Issue by swzwqtxdy** [electron/electron#18437]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  5.0.2
* **Operating System:**
  Windows 10
* **Last Known Working Electron version:**
  4.2.1

### Expected Behavior
I can find and use "process" from nodejs.

### Actual Behavior
I can not find process from nodejs. From console in dev tools, when I tried to access "process", it reported "process is not defined"

### Screenshots

<img width="279" alt="screenshot" src="https://user-images.githubusercontent.com/50982291/58311884-a00f3700-7e3c-11e9-9b17-8f94ddba3b09.PNG">

**Comment by vladimiry** [comment]
You can't access `process` from the renderer process with disabled `nodeIntegration` flag.
`nodeIntegration` is disabled by default since electron v5, so:
- you can access it like `remote.process` from the `preload` script
- alternatively you will need to explicitly enable `nodeIntegration` flag

**Comment by codebytere** [comment]
The above is correct.
