### ISSUE TITLE
Enabling touch emulation on webview also affects the BrowserWindow host

### ISSUE THREAD

**Issue by AglaiaWang** [electron/electron#18438]
Using `webContents.debugger.sendCommand` to enable touch emulation on webview would also affect the BrowserWindow that hosts it.

```js
webContents.debugger.sendCommand('Emulation.setEmitTouchEventsForMouse', { enabled: true });
webContents.debugger.sendCommand('Emulation.setTouchEmulationEnabled', {
  enabled: true,
  configuration: 'mobile',
});
```

### Issue Details

* Electron Version: 4.x and later
* Operating System:macOS 10.14
* Last Known Working Electron version:3.1.9

### Expected Behavior

When `sendCommand` is executed, touch emulation should be enabled for webview, while the host page stays in desktop mode.

### Actual Behavior

BrowserWindow's cursor also becomes the touch version.

### To Reproduce

Clone https://github.com/AglaiaWang/electron-quick-start and click the "click" button.

**Comment by jacklovepdf** [comment]
I met the same problem.

**Comment by iwiedenm** [comment]
I can confirm this issue is still present in 6.0.x. Is there an update on a fix or a workaround?

**Comment by flashyu** [comment]
I met the same problem，and this issue is still present in 7.1.1. Is there an update on a fix or a workaround?

**Comment by LeoMartinDev** [comment]
Any news on this issue ?

**Comment by christlee1989** [comment]
still in 9.1.2
Any news on this issue ? @zcbenz

**Comment by christlee1989** [comment]
> still in 9.1.2
> Any news on this issue ? @zcbenz

I try 3.x.y - 4.0.0 and found this issue starting from 4.0.0  @zcbenz  need help

**Comment by JenniferSui** [comment]
Also in Electron 10, @zcbenz need help

**Comment by gpetrov** [comment]
Any progress on this @zcbenz - it is stil present in Electron 12 - and quite essential

**Comment by oluul** [comment]
Any news on this issue ? @zcbenz

**Comment by billypon** [comment]
still in 13.1.7

**Comment by Chryseis** [comment]
so bad, still in, i'm going to use BroswerView to solve it
