### ISSUE TITLE
Feature Request: powerMonitor support for on-ac/on-battery for mac

### ISSUE THREAD

**Issue by pjebs** [electron/electron#18457]
Currently `on-ac` and `on-battery` support is only available on Windows: https://electronjs.org/docs/api/power-monitor#event-on-ac-windows

It would be good if it can be implemented on macOS. Here is code on how to do it: 

https://github.com/codler/Battery-Time-Remaining/blob/master/Battery%20Time%20Remaining/AppDelegate.m#L284

https://github.com/codler/Battery-Time-Remaining/blob/master/Battery%20Time%20Remaining/AppDelegate.m#L27

https://github.com/codler/Battery-Time-Remaining/blob/master/Battery%20Time%20Remaining/AppDelegate.m#L231

**Comment by pjebs** [comment]
On a related note, the `on-ac` and `on-battery` events are triggered when the state changes.
It would be good to have a function that actually queries whether the laptop is on-ac or on-battery at the moment.

**Comment by nornagon** [comment]
We inherit this API from Chromium, see https://chromium.googlesource.com/chromium/src/+/master/base/power_monitor

If Chromium adds this functionality (or if [you add it to Chromium](https://chromium.googlesource.com/chromium/src/+/master/docs/contributing.md)!) then we'll inherit it.

**Comment by pjebs** [comment]
what about external to chromium?

**Comment by pjebs** [comment]
chromium code is C++. The snipper above is obj-c. I see electron code for mac is obj-c
