### ISSUE TITLE
Hide from Add and remove program list

### ISSUE THREAD

**Issue by immohdali** [electron/electron#18458]
Hi...

I am made application but I want to hide that application from uninstall list at Add & features list and also from task Manager service running list after install.....is any body help me 

Thanks in Advance

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
