### ISSUE TITLE
Background color ignored on scriptable BrowserWindow

### ISSUE THREAD

**Issue by zarubond** [electron/electron#18466]
`BrowserWindow` parameter `backgroundColor` is ignored (the background stays white) if it is created with native chrome `window.open`.

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
3.1.6
* **Operating System:**
Windows 
* **Last Known Working Electron version:**
Never

### Expected Behavior
The window should start-up with defined color

### Actual Behavior
The window start with white color

### To Reproduce
Create a child window with native Chrome window.open (scriptable window) as shown here https://electronjs.org/docs/api/window-open , then set backgroundColor constructor property of BrowserWindow to some color. The result is that it is ignored. The color is set just fine if I do not use the window.open.

**Comment by miniak** [comment]
@zarubond the reason is that the scriptable popup shares the render process with the parent window. The background color is passed via the command-line, which is therefore shared.

**Comment by zarubond** [comment]
Unfortunately there is a bug in passing color from parent too. If I add the backgroundColor to the constructor parameter of parent BrowserWindow, then the color is passed to the script-able window. But if I set the color to parent with setBackgroundColor and then open up the script-able window, the color is not passed to it. So I can not change background color during lifetime of application which is very inconvenient for users who want to switch themes.

**Comment by iMoses** [comment]
> @zarubond the reason is that the scriptable popup shares the render process with the parent window. The background color is passed via the command-line, which is therefore shared.

I tried setting the parent `backgroundColor` hoping it will effect it's children, but instead the parent itself simply flushes that color for a second before resetting it to white, and then both the children and the parent background color is white.

**Comment by miniak** [comment]
Should be fixed by #24517, which landed in Electron 12
