### ISSUE TITLE
Disabled submenus' MenuItems can still be accessed via shortcuts

### ISSUE THREAD

**Issue by Woofthecat** [electron/electron#18461]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.0, 5.0.1, 5.0.2
* **Operating System:**
  * Windows 10 (1809) / Ubuntu 18.10 x64
* **Last Known Working Electron version:**
  * -

### Expected Behavior
macOS produces the expected behavior, as it won't allow triggering any code that is assigned to the click event of the MenuItem. After all if someone can't click it, why would one be able to use the shortcut for it.

### Actual Behavior
When a shortcut is pressed for a MenuItem that belongs to a disabled submenu, the code get's executed, but only in Windows and Linux.

### To Reproduce
```sh
$ git clone https://github.com/Woofthecat/electron-disabled-menus
$ cd electron-disabled-menus
$ npm install
$ npm start
```

The menu bar has a 'Test' menu which contains a disabled submenu. The disabled submenu has 2 other (enabled) MenuItems, with the Shift+H and Shift+J accelerators assigned. Inspect the terminal for console logs when the shortcuts are pressed. On macOS nothing will happen while there will be console logging for Windows and Linux.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
