### ISSUE TITLE
Missing additionalFeatures in new-window

### ISSUE THREAD

**Issue by zarubond** [electron/electron#18460]
Callback 'new-window' of BrowserWindow.webContents should pass additionalFeatures parameter as array of string which normally work until you enable on on parent window nativeWindowOpen feature, after that they parameter becomes always undefined. Native windows open is required for script-able child windows and not having additionalFeatures is bad because there is no other way how to pass window parameters from render to main process.

### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  3.0.0 and higher (probably older ones too)
* **Operating System:**
All platforms 
* **Last Known Working Electron version:**
None

### Expected Behavior
new-window callback should pass additionalFeatures as array of strings even if nativeWindowOpen is enabled.

### Actual Behavior
additionalFeatures is returned as undefiend if nativeWindowOpen is enabled.

### To Reproduce
Open up a BrowserWindow with nativeWindowOpen enabled and listening on 'new-window'. Then open up child window from render process with window.open('', 'child', 'testing=true');. The callback in 'new-window' will pass additionalFeatures as undefined instead of array of strings.

**Comment by codebytere** [comment]
Looks like this is happening [here](https://github.com/electron/electron//blob/e81afed66d9e49fcca3679b663bd7c0319067c31/lib/browser/api/web-contents.js#L378-L399): the IPC message is being sent when the internal `'-add-new-contents'` event is emitted and it doesn't have a concept of `additionalFeatures` so it's undefined. 

I'll try to see what can be done about this.

**Comment by lucasyvas** [comment]
It would be great if this could be made to work.
