### ISSUE TITLE
Is it safe to set the global variable from renderer process directly via getGlobal()?

### ISSUE THREAD

**Issue by arsenykruglikov** [electron/electron#18465]
Electron: 5.0.2
Node: v10.15.3
All supported OS

In main.js I'v got this code:
`global.sharedVariable = { prop: value };`
In renderer.js I'v got this code:
`remote.getGlobal('sharedVariable').prop = newValue;`

Is it safe to set global variables like so or maybe I should set it asynchronously via ipcMain?

**Comment by MarshallOfSound** [comment]
Safe, maybe, depends on your usage 🤷‍♂ 

Performant, no, you should use `ipcMain` to do this async

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
