### ISSUE TITLE
`ignore-certificate-errors` not working for Auto Update on Mac

### ISSUE THREAD

**Issue by thibaultdelor** [electron/electron#18468]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v3.1.8
* **Operating System:**
  * macOS 10.12.6
* **Last Known Working Electron version:**
  * ???

### Expected Behavior
When using VsCode behind a company MITM proxy and using the flag `--ignore-certificate-errors`, I should be able to auto update VSCode

### Actual Behavior
Auto Updating fails with "An SSL error has occurred and a secure connection to the server cannot be made."

### To Reproduce
Download VSCode and try to update behind a MITM proxy.

### Additional Information
See related issue https://github.com/microsoft/vscode/issues/73806

**Comment by MarshallOfSound** [comment]
@thibaultdelor This is expected behavior.  The `--ignore-certifcate-errors` flag only affects Chromiums network stack.  The updates in Electron are downloaded through Squirrel.Mac and do not pass through the Chromium network stack.
