### ISSUE TITLE
Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document. 

### ISSUE THREAD

**Issue by Yuezi32** [electron/electron#18470]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
5.0.2
* **Operating System:**
  * 
windows 10 (1809)
* **Last Known Working Electron version:**
  * 
5.0.2
### Expected Behavior

can running on build version.
### Actual Behavior

update Electron 4.0 to 5.0.2, when running the build version, got "Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document. ".
But it's OK when running in "npm run electron:serve".
### Screenshots

![1](https://user-images.githubusercontent.com/12807041/58444390-9599b980-812a-11e9-9f2e-4b0d2184ce75.png)

**Comment by MarshallOfSound** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
