### ISSUE TITLE
Electron 6.0.0-beta.4 -- Error: Could not call remote method 'savePage'

### ISSUE THREAD

**Issue by Nashorn** [electron/electron#18475]
I was previously on Electron 5.0.1, and have used the getWebContents().savePage() callback-style syntax fine.

Today i upgraded to 6.0.0-beta.4 and see in release notes that it relies on promises but no matter how i try to call it, i keep getting this error:

Error: Could not call remote method 'savePage'. Check that the method signature is correct. Underlying error: Error processing argument at index 0, conversion failure from #<Object>
Underlying stack: TypeError: Error processing argument at index 0, conversion failure from #<Object>
    at WebContents.savePage (/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/api/deprecate.js:102:32)
    at /usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:372:67
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:251:27)
    at EventEmitter.emit (events.js:194:13)
    at WebContents.<anonymous> (/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:342:29)
    at WebContents.emit (events.js:194:13)

    at /usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:375:21
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:251:27)
    at EventEmitter.emit (events.js:194:13)
    at WebContents.<anonymous> (/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:342:29)
    at WebContents.emit (events.js:194:13)
(anonymous) @ browser.js:188
apply @ /usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/callbacks-registry.js:41
(anonymous) @ /usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:281
(anonymous) @ /usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:271
emit @ events.js:194
onMessage @ /usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/init.js:43

I've tried the following:
async () => {
var success = await webview.getWebContents().savePage(fileName, 'HTMLComplete');
}

AND:
webview.getWebContents().savePage(fileName, 'HTMLComplete').then(async (error) => { ... })

Both styles give the error above. Any help getting my code migrated to work with 6.0.0-beta.4 please?

thanks

**Comment by codebytere** [comment]
@Nashorn do you think you could attach a simple reproducible app (for example, with [`fiddle`](https://github.com/electron/fiddle)) that replicates the crash you're seeing?

**Comment by Nashorn** [comment]
Hey there,
so i realized the 1st param to savePage(path, 'HTMLComplete') in 6.0.0-beta.4 is not the same as what previous versions expected.

in 6.0.0 - just a string path is needed, not an object{} as in 5.0.* so this works now:

dialog.showSaveDialog({}, async function (fileName) {
    getWebView().getWebContents().savePage(fileName.filePath, 'HTMLComplete').then(async () => {

**Comment by Nashorn** [comment]
btw - any way to save the page of an iframe inside of a webview?

**Comment by codebytere** [comment]
Glad this is sorted! As for the latter question: check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
