### ISSUE TITLE
Using baseURLForDataURL option in window.loadURL throws error

### ISSUE THREAD

**Issue by lynxtaa** [electron/electron#18472]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.2
* **Operating System:**
  * Windows 10 (1903)
* **Last Known Working Electron version:**
  * 4.*

### Expected Behavior

Using `baseURLForDataURL` option in `window.loadURL` should open new window using provided base url.
### Actual Behavior

Window doesn't open, throws error to console (screenshot provided).

### To Reproduce

```jsx
const win = new remote.BrowserWindow()
win.current.loadURL(
  `data:text/html;charset=UTF-8,${encodeURIComponent('<!DOCTYPE html>')}`,
  { baseURLForDataURL: 'http://...' },
)
```

### Screenshots

<img width="721" alt="Screenshot 2019-05-28 13 07 32" src="https://user-images.githubusercontent.com/22496946/58470075-9857d700-8149-11e9-9137-97c3e27e9755.png">

**Comment by vladimiry** [comment]
See here https://github.com/electron/electron/blob/00964b98b90ab69803da09b5af9e5500e4c2bce1/lib/browser/navigation-controller.js#L113

**Comment by lynxtaa** [comment]
> 
> 
> See here
> 
> https://github.com/electron/electron/blob/00964b98b90ab69803da09b5af9e5500e4c2bce1/lib/browser/navigation-controller.js#L104-L113

Well it does work without `baseURLForDataURL`. And it worked in 4.*

**Comment by vladimiry** [comment]
Still works for me with specified `baseURLForDataURL` https://github.com/vladimiry/ElectronMail/blob/da780bcecc1b8f7c10afc94a0a4dfc6646c2957e/src/electron-main/window/about.ts#L93

**Comment by lynxtaa** [comment]
Thanks! I resolved my issues with base-url by using `<base .. />` tag inside html instead of `baseURLForDataURL`.

But i'm still not sure if current behaviour (window crash) is desirable. Here is example:

main.js
```js
const { app, BrowserWindow } = require('electron')

function createWindow() {
  let win = new BrowserWindow({ webPreferences: { nodeIntegration: true } })

  const html = `
    <!DOCTYPE html>
    <html>
      <body>
        <h1>TEST</h1>
      </body>
    </html>
  `

  win.loadURL(`data:text/html,${encodeURIComponent(html)}`, {
    baseURLForDataURL: 'http://github.com'
  })
}

app.on('ready', createWindow)
```

package.json
```js
{
	"name": "base-url-for-data-url",
	"version": "1.0.0",
	"description": "",
	"main": "main.js",
	"scripts": {
		"start": "electron ."
	},
	"devDependencies": {
		"electron": "^5.0.2"
	}
}
```

**Comment by cyphercodes** [comment]
I'm having the same issue:

```
 window.webContents.loadURL('data:text/html,<html><head><title>test</title></head><body><h1>Hi</h1></body></html>', {
      baseURLForDataURL: httpHost,
    }).then((e) => {
    }).catch((e) => {
      console.log(e);
    });
```

**Comment by vladimiry** [comment]
Can confirm the issue. It was working for me because I was using `file://` protocol for which it's working fine. But when I tried using `http://` for another case it failed.

**Comment by incizzle** [comment]
+1

**Comment by cyphercodes96** [comment]
Verified bug on latest electro V `6.0.4` @sofianguy ??

Progress on this?

```    browserWin.webContents.loadURL('data:text/html;charset=utf-8,' + html, {
      'extraHeaders': 'pragma: no-cache\n',
      baseURLForDataURL: hostBaseUrl,
    });```

When will a push be worked on?

**Comment by vladimiry** [comment]
Referencing similar issue #20700

**Comment by joehonton** [comment]
I followed the solution that @lynxtaa came up with, that is inject a `<base href='...' \>` tag into the html contents beforehand, and simply bypass the broken `baseURLForDataURL` option.

Electron 8.0.0

Cross referencing https://github.com/electron/electron/issues/20700 which is a duplicate

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by dominic2013** [comment]
> Thanks! I resolved my issues with base-url by using `<base .. />` tag inside html instead of `baseURLForDataURL`.
> 
> But i'm still not sure if current behaviour (window crash) is desirable. Here is example:
> 
> main.js
> 
> ```js
> const { app, BrowserWindow } = require('electron')
> 
> function createWindow() {
>   let win = new BrowserWindow({ webPreferences: { nodeIntegration: true } })
> 
>   const html = `
>     <!DOCTYPE html>
>     <html>
>       <body>
>         <h1>TEST</h1>
>       </body>
>     </html>
>   `
> 
>   win.loadURL(`data:text/html,${encodeURIComponent(html)}`, {
>     baseURLForDataURL: 'http://github.com'
>   })
> }
> 
> app.on('ready', createWindow)
> ```
> 
> package.json
> 
> ```js
> {
> 	"name": "base-url-for-data-url",
> 	"version": "1.0.0",
> 	"description": "",
> 	"main": "main.js",
> 	"scripts": {
> 		"start": "electron ."
> 	},
> 	"devDependencies": {
> 		"electron": "^5.0.2"
> 	}
> }
> ```

hi,when i use style in the htmlcontent it doesn't works, how to use style css  within is,thanks!
