### ISSUE TITLE
Underlined letters on menu items are shown without pressing Alt

### ISSUE THREAD

**Issue by katiamoklokova** [electron/electron#18482]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  5.0.0-beta 6, 6.0.0-beta4
* **Operating System:**
  *  Ubuntu 18.04 x64, Windows 7 
* **Last Known Working Electron version:**
  *  4.2.1

### Expected Behavior
 Accelerators should only appear with Alt key being held.

### Actual Behavior
 Accelerators are reveled when clicking on any menu in the menu bar and away without Alt being held.The letters stay underlined after interacting with the menu bar.

### To Reproduce

1. Launch an Electron app with menu bar on Ubuntu 18.04 or Windows 7
2. Click on any menu in the menu bar
3. Click away, navigate around the app and observe that accelerators stay visible

### Screenshots

<img width="398" alt="Screen Shot 2019-05-28 at 12 10 06 PM" src="https://user-images.githubusercontent.com/20443967/58506178-92f78e00-8143-11e9-82a5-870de7faa27f.png">

**Comment by otake84** [comment]
Hello, any updates on this..? using alt key for switching languages (ja/en) and this has been quite a problem ..

**Comment by adamulrich** [comment]
It appears that the basic cases of underscores are handled. You press alt F and the top level menu lights up for 'File' for example. If you press another accelerator to invoke a sub-menu, it works, and the expected state of the menu is correct.

But get off the simple path case, and the problems around this are significant. It's the change in state when the app loses focus (Like menu is open, you navigate away, or using Alt-Tab to navigate to another app, and the Alt key is respected, and the menu state is underscored, and when you return to the app, the underscores persist, despite the menu no longer being invoked.

You can also get into this state too easily by clicking on a top level menu, then clicking on it again. Underscores are now your default state. 

The fixes that VS Code did for electron menus should be ported to fix all these corner cases. Without them, it is really unusable, and leaves accessibility poor.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
