### ISSUE TITLE
How to apply original-fs for fs-extra

### ISSUE THREAD

**Issue by Leaking** [electron/electron#18493]
I fork a process, and that process use fs-extra to handle IO-work, and when I fail to handle asar file.
how can I apply original-fs for fs-extra

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
