### ISSUE TITLE
Electron crashes with display-added emitting infinitely 

### ISSUE THREAD

**Issue by deanihansen** [electron/electron#18507]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.2.2
* **Operating System:**
  * Windows 10, 1803
* **Last Known Working Electron version:**
  * Unclear

### Expected Behavior
Creating BrowserWindows should work without crashing Electron

### Actual Behavior
Creating BrowerWindow crashes Electron if done wrong. 
Can be worked around with wrapping everything in a `setTimeout`

### To Reproduce
Requires 2 Windows machines. 
Machine A: 
Desktop, 16gb memory, full HD monitor, nvidia GTX 970

Machine B
Razor Blade, 2017, 16 gb of memory, 4K touch monitor, GTX 1060

*Repro steps*
_Machine A_
1. Enable RDP
2. Start fiddle with gist

_Machine B_
3. RDP to Machine A
4. Quit RDP session
5. Start new RDP session
6. Observe display added loop

Electron fiddle for repro: https://gist.github.com/56c70211215f01410e893d0f33f38528

### Screenshots
Video of crash: https://slack-files.com/T12KS1G65-FK1CXUR1T-a811ee02f8

### Additional Information
* This issue impacts Slack. 
* Only happens if the following option is set: ` skipTaskbar: true` when creating the second BrowserWindow

**Comment by MarshallOfSound** [comment]
Fixed by https://github.com/electron/electron/pull/19016
