### ISSUE TITLE
content not rendering when packaged in .app distributable

### ISSUE THREAD

**Issue by trusktr** [electron/electron#18510]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.2
* **Operating System:**
  * macOS
* **Last Known Working Electron version:**
  * n/a

### Expected Behavior

The app works fine when I run it locally, f.e. `./node_modules/.bin/electron src/index.js`. I see my `<webview>` render content as expected.

### Actual Behavior

When I package it with electron-forge, everything in the app works, except the one `<webview>` that I have simply doesn't load content, just a white rectangle, and opening devtools on it shows that nothing in the webview is even loaded. Running anything in console simply doesn't work (disappears) because the context isn't even loaded.

The only styling that the webview has is `width: 100%; height: 100%;`

### To Reproduce

unfortunately, not sure how to reproduce yet. Maybe I can take the private repo, and clip all the code except for the webview, and try reproducing that.

I think I may have better luck refactoring not to use a webview.

I really hope webviews will be un-deprecated, now that OOPIF's will be a thing.

### Screenshots

The first screenshot shows, that in local mode (`electron src/index.js`), the webview works fine. The devtools on top is for the main window, and the devtools on the bottom is for the webview:

<img width="1680" alt="Screen Shot 2019-05-29 at 12 42 15 PM" src="https://user-images.githubusercontent.com/297678/58586145-46798480-820f-11e9-8640-61cdf1aa4190.png">

The second screenshot shows the same setup, but running from an `.app` distribution build, and the bottom devtools shows that the same webview, with the same file URL, is blank and not loading anything:

<img width="1680" alt="Screen Shot 2019-05-29 at 12 40 38 PM" src="https://user-images.githubusercontent.com/297678/58586230-72950580-820f-11e9-92bd-43f64f710c63.png">

**Comment by MarshallOfSound** [comment]
@trusktr The thing that stands out to me their is the `@` symbol in the path.  If you are not loading that file correctly that `@` symbol will be URI encoded and the filesystem won't know where to find it.

E.g. `encodeURIComponent('@') === '%40'`

I assume you are doing something like `mainWindow.loadURL(path.resolve(__dirname, 'path/to/index.html))` you should instead be doing.

```js
mainWindow.loadURL(url.format({
  pathname: path.resolve(__dirname, 'path/to/index.html'),
  protocol: 'file',
  slashes: true
})
```

**Comment by trusktr** [comment]
Yes, but it works fine when I run `electron src/index.js`, just not when I run the electron-forge-packaged `.app`, so the `@` path works fine.

But I made a new discovery. The wrapper window that contains the webview, also has `@` in its path. However, if I try to load the webview content into the window, instead of a webview, then the window is blank when I try to run the `.app`!

So it's not a problem with the webview, but something is making the context that loads that particular HTML file not load so much as a JavaScript context (i.e. console doesn't even work, there's no window, there's nothing, devtools is completely inert).

**Comment by trusktr** [comment]
Here's a screenshot of the context, in a window pointing to my HTML file:

<img width="1366" alt="Screen Shot 2019-05-29 at 2 31 39 PM" src="https://user-images.githubusercontent.com/297678/58592939-86943380-821e-11e9-9a97-2b46f16a05da.png">

Its very weird, but unfortunately I have no idea how to reproduce it with non-private code yet.

**Comment by MarshallOfSound** [comment]
@trusktr Did you try the code for `loadURL` provided.  The only noticeable difference is that `@` symbol.  I can see the paths in both your screenshots, the first has no `@` the second one does

**Comment by trusktr** [comment]
Thanks for looking @MarshallOfSound! 🙏 I was hoping that was the issue, so I tried removing the `@`, but no luck:

<img width="1009" alt="Screen Shot 2019-05-29 at 4 45 19 PM" src="https://user-images.githubusercontent.com/297678/58598485-75a0ed80-8231-11e9-9dd8-5b71a3d0b965.png">

**Comment by MarshallOfSound** [comment]
@trusktr Try launching the app from terminal with `ELECTRON_ENABLE_LOGGING=true` and `ELECTRON_ENABLE_STACK_DUMPING=true` set

**Comment by trusktr** [comment]
@MarshallOfSound  I discovered something very peculiar!

If I run the app as

```sh
open /path/to/foo.app
```

then it always fails, the `<webview>` doesn't work. Every time!

However, if I run the app using the executable inside the `.app`,

```sh
/path/to/foo.app/Contents/MacOS/foo
```

then it works perfect, every time!

What could be different about opening the `.app` the regular way compared to the executable?

I'm currently on Electron 5.0.6.

**Comment by trusktr** [comment]
I tried to make a small reproduction, but unfortunately it works perfectly both ways (using `open` and running the executable directly). Without changing my main process code, the renderer code is just:

```tsx
import * as React from 'react'
import * as ReactDOM from 'react-dom'

// <h1>Hello Webview!!!!!!</h1>
const url = 'data:text/html;charset=utf-8;base64,PGgxPkhlbGxvIFdlYnZpZXchISEhISE8L2gxPg=='

ReactDOM.render(<webview style={{width: '100%', height: '100%'}} src={url} />, document.querySelector('#app'))
```

My actual example is a lot bigger, proprietary code base. I wish I could share it. Any ideas what could possibly be different between running with `open` vs directly?

**Comment by trusktr** [comment]
How do I pass the `ELECTRON_ENABLE_LOGGING=true` and  `ELECTRON_ENABLE_STACK_DUMPING=true` to the app when using `open`?

I tried

```sh
ELECTRON_ENABLE_LOGGING=true ELECTRON_ENABLE_STACK_DUMPING=true open ./dist/mac/mapper-saffron.app
```

but the app opens and disconnects from the console, and I don't see any output. This is the case in which it doesn't work. Otherwise I could easily prepend the env vars to the direct executable.

**Comment by trusktr** [comment]
I re-factored my code so that the stuff running in the `<webview>` does not rely on Node or Electron APIs, only Web APIs, then I switched to using an `<iframe>`, and now it works great.

So there's a problem with `<webview>`.

**Comment by codebytere** [comment]
@trusktr there are, unfortunately, many problems with webview haha.

We generally recommend using alternatives when possible, so given that the initial issue is no longer prescient i'm going to go ahead and close this out.

**Comment by trusktr** [comment]
@codebytere Ah, I realize now from this issue that I recognized you at WebAssembly Summit, but didn't know until now.

I found other issues that seem almost identical to this one, in that the application gets a blank screen in production:


- https://github.com/nstudio/xplat/issues/155 which seem identical to:
- https://github.com/electron-userland/electron-builder/issues/2662
- https://github.com/ionic-team/ionic/issues/19246

Additionally search for "electron blank screen" or similar searches and you'll find more issues, like https://github.com/ionic-team/capacitor/issues/1688 and https://github.com/electron/electron/issues/22289.

Seems there are some rendering glitches to be solved, but I don't think a single soul knows what the issue is.
