### ISSUE TITLE
hiddenInset + BrowserView = window drag canceled if cursor leaves drag region

### ISSUE THREAD

**Issue by jeremyspiegel** [electron/electron#18514]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.2.2/5.0.2
* **Operating System:**
  * macOS 10.14.4
* **Last Known Working Electron version:**
  * unknown

### Expected Behavior
I'm creating a BrowserWindow with *titleBarStyle: 'hiddenInset'*, and loading it with html having a div at the top with *height: 25px* and *-webkit-app-region: drag* where the title bar would normally be. I'm then adding a BrowserView into the window. I expect to be able to drag the window by clicking in the top area.

### Actual Behavior
I am able to drag the window, but if I drag quickly enough for the cursor to leave the drag region, the drag seems to be canceled until the cursor goes back into the drag region, resulting in a choppy drag experience (see the gif below). This doesn't happen when using other values for titleBarStyle or when not using a BrowserView.

### To Reproduce
Here is the minimal code that reproduces the issue: https://github.com/electron/electron-quick-start/compare/master...jeremyspiegel:hiddeninset-browserview-drag-issue?expand=1

Here are the commands required to clone/setup/run the repo
```sh
$ git clone https://github.com/jeremyspiegel/electron-quick-start.git -b hiddeninset-browserview-drag-issue
$ cd electron-quick-start
$ npm install
$ npm start
```

### Screenshots
![Kapture 2019-05-29 at 17 02 16](https://user-images.githubusercontent.com/776117/58599145-c7e30e00-8233-11e9-968d-07a97666ca33.gif)

**Comment by jeremyspiegel** [comment]
I tried using [electron-drag](https://www.npmjs.com/package/electron-drag) instead of -webkit-app-region, and when I couldn't get it to receive mouse events because of this [osx-mouse issue](https://github.com/kapetan/osx-mouse/issues/8), I tried switching electron-drag to use [osx-mouse-cocoa](https://www.npmjs.com/package/osx-mouse-cocoa), but it also didn't receive any mouse events (I added logging to the [NSEvents handler](https://github.com/poiru/osx-mouse-cocoa/blob/master/source/mouse.mm#L43) and it was never called, I don't know why though).

**Comment by jeremyspiegel** [comment]
I think I've figured out the issue — if I add a colon to selector name in the `[self.window respondsToSelector:@selector(performWindowDragWithEvent)]` checks in [native_browser_view_mac.mm](https://github.com/electron/electron/blob/master/shell/browser/native_browser_view_mac.mm#L47), that allows the check to succeed so that we use `performWindowDragWithEvent:`, and that fixes the issue. It looks like it had the colon at some point but was [removed](https://github.com/electron/electron/commit/cd5cd25f74108d5b4c602f9b7145235f4485602a). The [public API for performWindowDragWithEvent](https://developer.apple.com/documentation/appkit/nswindow/1419386-performwindowdragwithevent?language=objc) takes an argument so I think we should be using the colon.

Even with the fix above, the issue still exists with the pre-10.11 compatibility code. It looks like we just stop getting `mouseDragged` calls if the cursor quickly leaves the window, if the window has a toolbar. But I don't know why this is.

cc @felixrieseberg

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
