### ISSUE TITLE
Edit menu is useless cause app lose focus

### ISSUE THREAD

**Issue by cumajkeee** [electron/electron#18518]
### Issue Details

* **Electron Version:**
  * 5.0.x
* **Operating System:**
  * Win 7, Win 10
* **Last Known Working Electron version:**
  * 4.0.8

While I type some text in input/textarea, I'd like to use Edit menu to cut/copy/paste/select text.

### Expected Behavior
I'd like to able perform all actions on the text I placed in input/textarea.

### Actual Behavior
When click Edit menu is application lose focus and click on any menu item didn't lead to some interaction with text.

### To Reproduce

https://github.com/cumajkeee/electron-quick-start/tree/edit-menu-issue
OR
Just add textarea to index.html :)

**Comment by nicodorn** [comment]
Same issue on platform/linux.

This affects all items in the menubar, not only the text tools. I'd expect that the WebView gains focus after clicking any menubar item. Instead the menubar retains the focus. 4.x.x had the correct (IMHO) behaviour.

Workaround: If you have defined a special click event for a menubar item you can call `win.focusOnWebView()` afterwards, where `win` is the related BrowserWindow object.

Workaround 2: Stick to 4.x.x. ;-)

**Comment by ffflorian** [comment]
This was fixed in https://github.com/electron/electron/pull/20019 and works for me with Electron 5.0.11.

**Comment by electron-triage** [comment]
Closing this as it is reported as fixed in the above comment. Please upgrade to a later version of Electron. We will be happy to reopen this if you are experiencing this issue on later versions of Electron.
