### ISSUE TITLE
Window can enter kiosk mode when dragged to the top of screen in Windows 7

### ISSUE THREAD

**Issue by Slapbox** [electron/electron#18511]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 4.1.5
  * 
* **Operating System:** Windows 7
  * 
* **Last Known Working Electron version:** Unknown
  * 

### Expected Behavior
Window should maximize when dragged to top of screen, but not enter kiosk mode.

### Actual Behavior
Twice in the past few weeks I have seen the window get stuck in kiosk mode, and it cannot be exited. 

This is a bigger issue than it might seem despite the low occurrence rate. Because my application saves the position of the window when it's closed, when the user re-opens the application it's still stuck like this unless they go digging into their file system for where this information is saved and delete it.

### To Reproduce
Drag an frameless (not sure this matters) Electron window to the top of the screen until it occurs, probably a couple hundred times... Unfortunately I have no idea how to consistently reproduce this.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
