### ISSUE TITLE
Sandbox inside ppapi don't inherit sanbox property from BrowserWindow

### ISSUE THREAD

**Issue by Feverqwe** [electron/electron#18516]
Hello. I run BrowserWindow with sandbox false and when run ppapi plugin inside, it runing inside sandbox.

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.2
* **Operating System:**
  * Windows 10 (1903)
* **Last Known Working Electron version:**
  * 4.2.2

### Expected Behavior
ppapi process must inheret --no-sandbox switch

### Actual Behavior
ppapi process don't inheret --no-sandbox switch when BrowserWindow have sandbox: false property.

### To Reproduce
Create window and run any ppapi plugin inside
```
new BrowserWindow({
      ...
      webPreferences: {
         sandbox: false
      }
    });
```

### Additional Information
I can fix it with this switch, but is disable sandbox globally.
```
      electron.app.commandLine.appendSwitch('no-sandbox');
```

**Comment by miniak** [comment]
@Feverqwe Why is that a problem?

**Comment by Feverqwe** [comment]
@miniak cause ppapi plugins don't works.

**Comment by miniak** [comment]
@Feverqwe which plugin?

**Comment by Feverqwe** [comment]
I use mpv.js from here https://github.com/Kagami/mpv.js 
if I don't use no-sandbox swith I see black block.

**Comment by miniak** [comment]
@Feverqwe the proper solution IMO in this case is to add a new API to opt-out of sandboxing for a particular plugin. See PR #18939

**Comment by miniak** [comment]
code example would be
```
const {PLUGIN_MIME_TYPE} = require("mpv.js");
app.disablePluginSandbox(PLUGIN_MIME_TYPE);
```

**Comment by Feverqwe** [comment]
Its looks great! Thx!

**Comment by miniak** [comment]
@Feverqwe the only problem is that this is semver minor and we'll be only able to add this to Electron 6, which is still in beta. For Electron 5, we would have to bump 5.0 to 5.1 in order to add a new API there.

**Comment by Feverqwe** [comment]
@miniak its not a problem for me. I resolve this problem via switch, after release I will use this api method.

**Comment by electron-triage** [comment]
Closing this issue as it is reported to be fixed. Feel free to reach out if you are still experiencing this issue in later versions of Electron and we can reopen.
