### ISSUE TITLE
Docs missing MenuItem.submenu

### ISSUE THREAD

**Issue by Paxa** [electron/electron#18522]
Actual object has it, but docs don't reflect https://electronjs.org/docs/api/menu-item

> Each Menu consists of multiple MenuItems and each MenuItem can have a submenu.

If we not suppose to use `menuItem.submenu`, then is recommended way to do it?

I use it to dynamically enable and disable menu items

**Comment by MarshallOfSound** [comment]
This is fixed in the master / 6-0-x docs and will be included in those typescript defs 👍 

https://github.com/electron/electron/blob/master/docs/api/menu-item.md#menuitemsubmenu
