### ISSUE TITLE
"-webkit-app-region: drag" elements are always above BrowserView elements

### ISSUE THREAD

**Issue by jeremyspiegel** [electron/electron#18529]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.2.2/5.0.2/6.0.0-beta.5
* **Operating System:**
  * 10.14.4
* **Last Known Working Electron version:**
  * unknown

I created a frameless window and included a 25px-height div across the top with "-webkit-app-region: drag". I then added a BrowserView that has a "-webkit-app-region: no-drag" button that overlaps with that div, and want to be able to click on the button. However, the "drag" div in the window seems to always be above the button in the BrowserView, so that the button isn't clickable.

I tried putting the "-webkit-app-region: drag" div in the BrowserView, but that doesn't seem to work (the window isn't draggable).

### To Reproduce
Here is [code](https://github.com/electron/electron-quick-start/compare/master...jeremyspiegel:browserview-webkit-app-region-no-clicks?expand=1) the creates two windows: the left window has a drag region and an overlapping no-drag button that is clickable. The right window has a drag region and a BrowserView containing a button that isn't clickable (but should be).
```sh
$ git clone https://github.com/jeremyspiegel/electron-quick-start.git -b browserview-webkit-app-region-no-clicks
$ cd electron-quick-start
$ npm install
$ npm start
```

### Screenshots
![Kapture 2019-05-30 at 14 56 39](https://user-images.githubusercontent.com/776117/58667583-3e8f1280-82eb-11e9-9ca0-823d4a94f851.gif)

**Comment by ruihanzhao** [comment]
I have this same exact issue. I have an app that is frameless and has a 30px drag region on top but there is a browserview on top of part of the app that I want to have buttons marked as no-drag, but no matter what the drag element is on top so the entire browserview is draggable, including the buttons. Is there any fix for this?

**Comment by codebytere** [comment]
Closed by https://github.com/electron/electron/pull/26145
