### ISSUE TITLE
Electron Webview element does not focus correctly on the text area

### ISSUE THREAD

**Issue by mailtokartik1** [electron/electron#18539]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * >=3.0.0
* **Operating System:**
  * Mac OS
* **Last Known Working Electron version:**
  * v2.0.18

### Actual Behavior

The webpage should focus properly in the placeholder text box.

### To Reproduce

- Click left ‘ファイナンス’ menu after `npm start`
- Click Text box <-does not work
Change Electron version to v2.0.16
- Click left ‘ファイナンス’ menu
- Click Text box <-works

`git clone https://github.com/mailtokartik1/sampleElectron`
`cd sampleElectron`
`npm install`
`npm start`
### Screenshots

<img width="797" alt="Screen Shot 2019-05-31 at 4 05 23 PM" src="https://user-images.githubusercontent.com/29715398/58688328-1a9d0100-83bf-11e9-97c1-ed7dd0e0c8ec.png">
<img width="799" alt="Screen Shot 2019-05-31 at 4 06 01 PM" src="https://user-images.githubusercontent.com/29715398/58688358-27b9f000-83bf-11e9-9c22-cab63e698c2d.png">
<img width="790" alt="Screen Shot 2019-05-31 at 4 07 03 PM" src="https://user-images.githubusercontent.com/29715398/58688363-2b4d7700-83bf-11e9-868e-0e47dbf39b3c.png">

### Additional Information

Our product has recently upgraded the Electron version to v2.0.16 to v3.0.0 and we use the Electron webview component to render our views. Using BrowserView does not show this bug and we are able to correctly focus in the text box.

**Comment by mailtokartik1** [comment]
@sofianguy this also occurs for v4.x and 5.x as well. I last checked for v5.0.2 and still encountered it.

**Comment by KazuyaHayashi** [comment]
@mailtokartik1 
See https://github.com/electron/electron/issues/14474
Maybe same issue happens on your case.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
