### ISSUE TITLE
LoadURL method in child window does not load angular route

### ISSUE THREAD

**Issue by chandrakanthi07** [electron/electron#18541]
### Issue Details

* **Electron Version:**
  * 5.0.2
* **Operating System:**
  * Windows 7
* **Last Known Working Electron version:**
  * 4.2

### Expected Behavior
LoadURL function should load the html file mentioned in the angular route

### Actual Behavior
The index.html is loaded instead of the actual routed file

### To Reproduce
Unable to share the repository because code is private

### Additional Information

I am using angular path to load content for childwindow. However the path is not loaded in the child window.
Below is the code 
child.loadURL('file://' + __dirname + '/index.html#/about');

Please fix this or let me know a workaround, so that i can upgrade the electron version in our app.

**Comment by BorysTyminski** [comment]
It looks more like usage error not electron bug. Can you create and share demo repository?

**Comment by MarshallOfSound** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by EmmanuelNocks** [comment]
question is, are you able to load  mainWindow.loadURL('file://' + __dirname + '/angular_app/index.html') ?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Comment by chandrakanthi07** [comment]
Yes it does load the index.html file.
Thank you

**Comment by chandrakanthi07** [comment]
How to reopen this issue?
