### ISSUE TITLE
webviews are not anti-aliased

### ISSUE THREAD

**Issue by burtonator** [electron/electron#18559]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.1 
* **Operating System:**
  * Ubuntu 19.04
* **Last Known Working Electron version:**
  * None

### Expected Behavior

Fonts within <webview> should be treated just like they are outside webviews and that includes font anti-aliasing.

https://github.com/electron/electron/issues/10025

### To Reproduce

Just load the following HTML in Electron on Linux.  Behold.. blurry fonts :-P

```
<html>
<body>

<p>

    This is some test that is probably anti-aliased properly.
</p>

<webview src="http://www.example.com"></webview>


</body>
</html>
```

### Screenshots

The text at the top is AA (notice the red blurring on the edges?) everything else is not.

![image](https://user-images.githubusercontent.com/45447/58751060-811d3000-844e-11e9-8cc1-512fb86819a5.png)

### Additional Information

It might be related to this bug:

https://github.com/electron/electron/issues/10025

If we can set the default to #FFF then I think this will be fixed everywhere.

If someone will point me in the right direction I can send a PR.   I just don't know where to set the defaults.

**Comment by slawekmuniak** [comment]
This issue occurs also on Windows machines

**Comment by GiovanH** [comment]
This seems like a serious issue that hasn't been addressed.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
