### ISSUE TITLE
How to listen 'open-url' on win10

### ISSUE THREAD

**Issue by lhp--** [electron/electron#18586]
NEED HELP!!! I want open app via url ( xxx://name=xx), i need the parameter on WIN10 system.
"electron@4.1.4"

**Comment by codebytere** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by lhp--** [comment]
```
app.on('will-finish-launching', () => {
    // for mac
    app.on('open-url', (event, url) => {
       ...
    })
    // for win
    process.argv.forEach((url) => {
        if (/yourprotocol:/.test(url)) {
            ...
        }
    }
})
```
