### ISSUE TITLE
Windows Dark Mode

### ISSUE THREAD

**Issue by oonqt** [electron/electron#18584]
With the release of the May 2019 update for windows, it introduced a way to set a dark mode for applications if they support it. However, I do not see this functionality in windows, I see it for Mojave [as seen here](http://electronjs.org/docs/tutorial/mojave-dark-mode-guide), is this undocumented or has the functionality not been added yet?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

See #18119 and #15316
