### ISSUE TITLE
Transparent Windows not working in Windows 7

### ISSUE THREAD

**Issue by Polcar13** [electron/electron#18587]
### Issue Details

* **Electron Version:**
  * 6.9.0
* **Operating System:**
  * Windows 7

### Expected Behavior
See a transparent window when start the app in Windows 7

### Actual Behavior
A white background apear instead

### Screenshots

![image](https://user-images.githubusercontent.com/18739826/58790579-f45ea780-85f0-11e9-99c5-9c80dcafa205.png)

### Additional Information
Is there an option for use transparent windows on Windows 7?

**Comment by EnderDev** [comment]
What does it say in your Dev Tools console?

**Comment by Polcar13** [comment]
> What does it say in your Dev Tools console?

hi! well, the console don't say nothing, the app works too,  like on windows 10, but whit this white background

**Comment by miniak** [comment]
https://electronjs.org/docs/api/frameless-window#limitations
