### ISSUE TITLE
Response Headers with period corrupted in onHeadersReceived

### ISSUE THREAD

**Issue by richbern** [electron/electron#18593]
If a web server responds to a request with a header that contains a period, having an onHeadersReceived handler can corrupt the headers before they're received by the browserWindow hosted within. 

Starting with the QuickStartApp, I made the following changes: 

```
  // and load the index.html of the app.
  //mainWindow.loadFile('index.html')
  mainWindow.loadURL("<someUrl>");

  mainWindow.webContents.once("did-finish-load", async() => {
    mainWindow.webContents.session.webRequest.onHeadersReceived((details, callback) => {
      console.log(details.responseHeaders);
      callback({cancel: false, responseHeaders: details.responseHeaders});
    });    
  });
```

I then used Fiddler to manipulate the response by sending back a static file for all requests on that URL loaded above with the following contents: 

```
HTTP/1.1 200 OK
Date: Mon, 03 Jun 2019 17:03:54 GMT
Content-Type: text/html
My.Value: 1
Content-Length: 196

<script>var x=new XMLHttpRequest();x.open("POST", ".", true);x.addEventListener("readystatechange",function(e){if(x.readyState === 4){alert(x.getAllResponseHeaders());}}, false);x.send();</script> 
```

In the "onHeadersReceived", details.responseHeaders looks like this:
```
{ 'Content-Length': [ '196' ],
  'Content-Type': [ 'text/html' ],
  Date: [ 'Mon, 03 Jun 2019 17:03:54 GMT' ],
  My: { Value: [ '1' ] } }
```

However, the containing page cannot see that header, as it alerts:
```
date: Mon, 03 Jun 2019 17:03:54 GMT
content-length: 196
content-type: text/html
```

Commenting out the onHeadersReceived handler, the web page alerts this:
```
date: Mon, 03 Jun 2019 17:03:54 GMT
my.value: 1
content-length: 196
content-type: text/html
```

I'm not sure if I prefer the current state where Electron is translating the header into an object, and then return it to a string, or if it would be better to keep it as a string all the way through.

For example, the current state allows me to look at the header like `details.responseHeaders.My.Value`, which may be convenient. However, if that stays, I think when the headers are given to the page, the properties under `responseHeaders` need to be translated back into string headers (so `My.Value` is one header and not lost). 

Alternatively, if the header names were kept as strings, one would have to access them via `details.responseHeaders["My.Value"]`. Which feels more cumbersome but also potentially makes iterating easier.

**Comment by pushkin-** [comment]
I can no longer reproduce this with Electron 8.1.1.

**Comment by richbern** [comment]
I agree, I can't reproduce this any longer. Not sure what fixed this or when it was fixed, but I'll mark this as Closed.
