### ISSUE TITLE
Create a Guide for app notarization

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#18609]
As of macOS Catalina Apple will be [requiring that apps are notarized](https://appleinsider.com/articles/19/06/03/apples-macos-catalina-is-first-to-require-app-notarization-by-default), we all saw this day coming and are slightly prepared.  The tooling exists, we just need to document how everyone can use it.

Refs: https://github.com/electron-userland/electron-notarize
Refs: https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#osxnotarize

**Comment by Kilian** [comment]
Ref for `electron-builder`/general "other stuff Apple wants you to do when notarizing": https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/

I'd be happy to get an in-detail guide started (or if anyone feels like it, they're welcome to ~~plagiarize~~ use any part of the article.)

**Comment by arvidkahl** [comment]
Thank you Kilian for the walkthrough. This is one of those rare blogposts that are immediately comprehensive, instructive and (almost) error-free (there is a `}` to many in the `afterSign` script you provide IIRC). 

An in-depth guide would certainly be helpful, but the post is already sufficient to implement this in 15 minutes. And then, of course, wait another 15 minutes for the Apple API to grace you with a working ticket.

**Comment by Kilian** [comment]
> (there is a } to many in the afterSign script you provide IIRC).

Cheers, fixed!

**Comment by lukeapage** [comment]
We're trying to reproduce getting a security warning with a signed app - either in mojave or the catalina beta - and even though the app is signed after 1st June and **not** notarized, we are **not** getting blocked or seeing additional warnings other than the (you downloaded this from the internet). we are using a dmg.

Has anyone seen this affect an electron app or have more info about how to reproduce the blocking?

**Comment by Kilian** [comment]
The notarization requirement is not yet in effect for developer id’s generated before april 8th 2019, so that’s probably why.

**Comment by lukeapage** [comment]
We eventually reproduced by allowing the beta to update itself to the latest beta. Our developer account fits that criteria and our app is blocked. Thanks for the suggestion.

**Comment by Mizzick** [comment]
With two last Catalina betas we started to have some notarization or signing problems here
https://github.com/AdguardTeam/AdGuardForSafari/issues/172
 and as it mentioned in the issue, there are same problems even with Whatsapp.

So I guess, the notarization requirement is in full effect already.

**Comment by MehediH** [comment]
@Kilian @MarshallOfSound I would like to write the documentation/guide for app notarization. Shall I go ahead and contribute one under here https://github.com/electron/electron/tree/master/docs/tutorial 

There are some problems with notarization at the moment, especially when notarizing .zip distributions. Please let me know if I can go ahead and write up a guide for the docs :)
