### ISSUE TITLE
API for OS X appearance settings

### ISSUE THREAD

**Issue by max** [electron/electron#1861]
It would be nice to have an API to access the OS X appearance settings. Then you can:

- Hook your theme into the appearance settings
- Draw custom traffic lights when opting for a frameless window (we can already gray them out when the window is blurred)

![image](https://cloud.githubusercontent.com/assets/111631/7976661/df97c6f8-0a32-11e5-83cd-f1303906dddb.png)

![image](https://cloud.githubusercontent.com/assets/111631/7976659/d95f0738-0a32-11e5-9b81-180bc08c9d88.png)

**Comment by paulcbetts** [comment]
It'd be cool to inject this as a CSS class - I'm not sure that this information is Generally Available on OS X though, or if it's something that only the OS can see

**Comment by max** [comment]
@paulcbetts Yes, injecting that as a CSS class would be neat although in a React/Ember world I'd much rather deal with the classes myself instead of having to observe the class list on an element like `html`.

**Comment by Tribex** [comment]
Don't forget about Linux (GTK+QT) at least. I keep wanting to toy with the idea of porting GTK themes to the browser. Haven't found time yet.

**Comment by max** [comment]
@Tribex I think there may be [a property for GTK already](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions): `dark-theme`.

**Comment by max** [comment]
@paulcbetts Looks like `[NSColor colorForControlTint:NSDefaultControlTint]` could work. [See this thread](http://www.cocoabuilder.com/archive/cocoa/13836-notification-of-aqua-graphite-preference-changed.html). There are also notifications that fire which could be forwarded as events to the browser window.

**Comment by tommoor** [comment]
Try this in the command line:

```
defaults read -g AppleInterfaceStyle
```

You can read it when your app starts using exec, the only thing is I don't know of a why to get notified if it changes whilst the app is running

**Comment by max** [comment]
Ah, brilliant. I'd still love to get notified but this will do as a workaround. Thanks, @tommoor.

**Comment by ricodang** [comment]
I temporary solved this issue by watching the ».GlobalPreferences.plist« in »~/Library/Preferences/« with simple-plist (look for »AppleAquaColorVariant«). 
I use one function to get the appearance setting and another to watch it (fs.watchFile), if it changes I use the get-function to callback the result and change the CSS class from blue to grey for example. 

Unfortunately it does not take effect immediately, not all the time, but as a workaround it is fine for me at the moment.
But of course I'd love to have a »native« way for this.
Hope this helps.

**Comment by max** [comment]
@ricodang Is `fs.watchFile` expensive? Otherwise this is a really neat workaround.

**Comment by ricodang** [comment]
I haven't really checked on this as I am in a very deep development stage. I guess if you just watch one file it's rather less expensive than watching whole directory trees, especially if the file doesn't change so often.
If you have the chance to figure something out about the performance of your app, I'd love to hear it.

**Comment by paulcbetts** [comment]
@Tribex Agree - is there a way to get the theme values from GTK+?

**Comment by Tribex** [comment]
@max Ah, neat, hadn't seen that.
@paulcbetts Getting the entire theme from GTK+ would probably be best left to a library. That said, GTK+3 themes are just CSS (Closer to LESS, actually.) So getting the values would probably be pretty easy.

**Comment by dkfiresky** [comment]
Hey, there is a repo with example of how to switch from light theme to dark: https://github.com/weAreYeah/WAYTheDarkSide

**Comment by davej** [comment]
There are also [CSS System Colors](http://webdesign.about.com/od/colorcharts/l/blsystemcolors.htm). On OS X it only seems to be useful for getting the highlight color though.

**Comment by dkfiresky** [comment]
I think we could simply develop (if there are none) a node module for getting/setting the values from NSUserDefaults. It would solve not only getting appearance information issues, but even more things like if our application require to store some data in NSUserDefaults (plist files).

**Comment by joshaber** [comment]
Looks like #4646 addressed this, right?

**Comment by max** [comment]
@joshaber As far as I know dark mode is not the same as blue/graphite appearance settings. So while awesome that Electron can now render dark apps it seems unrelated.

**Comment by joshaber** [comment]
Ah, right :+1:

**Comment by miniak** [comment]
https://github.com/electron/electron/pull/5262
