### ISSUE TITLE
Check whether the mouse or keyboard has been scrambled

### ISSUE THREAD

**Issue by tiagocaus** [electron/electron#18632]
How to check if the mouse or keyboard was triggered within 1 minute? 
If you have not done anything, run a command

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by tiagocaus** [comment]
The channels reported do not work!
