### ISSUE TITLE
Setting new src in webview is slow in v6

### ISSUE THREAD

**Issue by steverandy** [electron/electron#18638]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.0-beta.6
* **Operating System:**
  * macOS 10.14.5
* **Last Known Working Electron version:**
  * 5.0.2

### Expected Behavior
Setting new src in previous version of electron would take only 1–2ms.

### Actual Behavior
Setting new src in electron v6 takes ~600–700ms.

### To Reproduce
1. Clone this repo: https://github.com/steverandy/electron-quick-start/
2. Checkout branch `slow-webview`
3. Run `npm install` and `npm start`
4. Open devtool to see the time took to set new src

### Screenshots

<img width="1136" alt="Screenshot 2019-06-05 at 10 23 12 AM" src="https://user-images.githubusercontent.com/525332/58925938-f1dc8900-877b-11e9-84ee-5ae555936117.png">

**Comment by zcbenz** [comment]
Electron is very slow when handling webview related sync IPC messages, other sync IPC message seem to work fine.

**Comment by zcbenz** [comment]
So for APIs that return Promise (for example `loadURL`), the `guest-view-manager` would wait until the Promise is resolved.
