### ISSUE TITLE
Is webview.findInPage broken?

### ISSUE THREAD

**Issue by madprops** [electron/electron#18633]
I'm not sure if I'm doing something wrong or if search is broken right now.

When creating the webview I do:

    webview.addEventListener('found-in-page', function(e)
    {
        webview.stopFindInPage('keepSelection')
    })

And I call it manually like:

```webview.findInPage('word')```

The word exists in the current document, yet e.result always shows 0 matches, and no word is highlighted (though I'm not sure if I should do this manually).

This is on Electron 5.0.2

https://electronjs.org/docs/api/webview-tag

**Comment by codebytere** [comment]
@madprops do you have a minimum viable repro I could use to replicate the conditions of your error, by chance? It'll be easier for me to investigate this if I know under what conditions you experienced it!

**Comment by madprops** [comment]
Thank you for pushing me to make the demo. After trying hard making it fail (it wasn't failing) I found the culprit:

```    
    contextMenu(
    {
        window: wv2,
        showCopyImageAddress: true,
        showSaveImageAs: true,
        showInspectElement: true
    })```

Which is provided by the electron-context-menu package. So nothing wrong with Electron.
You can close this, unless you want more information.

**Comment by codebytere** [comment]
Awesome! Thanks for investigating, and glad it's solved!
