### ISSUE TITLE
Windows Mixed Reality support

### ISSUE THREAD

**Issue by waptak** [electron/electron#18637]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

In Chrome Canary（74.0.3710.0) have the flag "Windows Mixed Reality support" 
![image](https://user-images.githubusercontent.com/2579658/58923314-b472fe00-8771-11e9-9f66-8cf7eff686ac.png)
I have tried to update Electron version to `6.0.0-beta.5` which Chromium version is 76.0.3805.4
, I see the [List of Chromium Command Line Switches](https://peter.sh/experiments/chromium-command-line-switches/),  this version don't have the Command Line Switch `--enable-windows-mixed-reality-support'`, Is it another Command Line Switch?
### Proposed Solution

* #### Electron 6.0.0-beta.5
* #### Windows 10 version 1809

```javascript
mainWindow = new BrowserWindow({    
    webPreferences: {
      nodeIntegration: true,
      plugins: true
    }
  })
app.commandLine.appendSwitch('--enable-webvr');
app.commandLine.appendSwitch('--enable-windows-mixed-reality-support');
```
![image](https://user-images.githubusercontent.com/2579658/58923683-3a437900-8773-11e9-9f42-a8e45096e73b.png)

**Comment by erickzhao** [comment]
Hey there,

Based on your screenshot from `chrome://flags`, wouldn't the switch be `--windows-mixed-reality`?

**Comment by djmisterjon** [comment]
On my side i succeed to make it work with nwjs, but infinite loop ! 
Any suggest ? nwjs or electron ?
i made a video to show the result
https://youtu.be/JtJhQI_fTwM

**Comment by MarshallOfSound** [comment]
This should be fully enabled in //content by default nowadays
