### ISSUE TITLE
Chrome Devtools failing to load plugins consistently

### ISSUE THREAD

**Issue by jonathantizard** [electron/electron#18649]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
v5.0.2
* **Operating System:**
Mac OSX 10.14.5
* **Last Known Working Electron version:**
V3.0 - Other VUE Electron plugins that use older versions of Electron - do consistently work. Which suggests Electron is the issue

### Expected Behavior
When launching the electron app, open the dev tools and got to VUE JS plugin

<img width="801" alt="Screenshot 2019-05-08 at 11 22 44" src="https://user-images.githubusercontent.com/590023/58959223-87881080-879c-11e9-84a6-929e248342e7.png">

### Actual Behavior
VUE JS Devtools cannot detect the DOM. This is intermittent and reloading the dev tools over and over will cause the tools to work / then cease to work. Random.

<img width="989" alt="Screenshot 2019-05-08 at 11 13 14" src="https://user-images.githubusercontent.com/590023/58959245-9373d280-879c-11e9-9233-44bf98f2788a.png">

### To Reproduce
yarn electron:serve / refresh the dev tools

### Additional Information
This bug has been raised on VUE JS and Electron VUE - all seem to keep pointing back to electron as being the cause.

Other issue linked here:
https://github.com/vuejs/vue-devtools/issues/1001

**Comment by GitNomster** [comment]
Same problem in electron v. 4.2.4. OS: Windows 10 x64

**Comment by GitNomster** [comment]
I noticed that if you press f5 while on the network tab - devtools does not hang.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by jonathantizard** [comment]
Same issue for electron 6/7/8 same steps to replicate.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
