### ISSUE TITLE
why Electron open multiple instance when it's open only one window ( see inside task manager) 

### ISSUE THREAD

**Issue by ervijjusty** [electron/electron#18640]
I'm using the electron version 4.1.4 with angular 7, but the problem that I'm facing is the app is take high usage of CPU, Memory and It's only one windows is open and if we see inside the task manager there is 3 Instance is open every instance take own memory and CPU,

I'm attached the screenshot have a look
![Screenshot (14)](https://user-images.githubusercontent.com/17564766/58933168-04f35700-8784-11e9-8962-dcaa7acd83b8.png)

**Comment by ervijjusty** [comment]
Here you can see there is four instance of electron and the CPU is 32% and Memory Around 1 GB

![Screenshot (16)](https://user-images.githubusercontent.com/17564766/58933320-76cba080-8784-11e9-80fb-a4b61365b7db.png)

**Comment by MarshallOfSound** [comment]
Electron (just like Chromium) runs across multiple processes.  You have the `main` process (where your core app logic runs), `renderer` processes (these are you BrowserWindow's), then their is an additional `gpu-process` which does all the, well, GPU things 👍

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
