### ISSUE TITLE
After popping up an message, all input who's type is text is broken.

### ISSUE THREAD

**Issue by swzwqtxdy** [electron/electron#18646]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.2
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 4.2.1

### Expected Behavior
input who's type is text is always normal

### Actual Behavior
After popping up an message, all input text control is broken. After clicking, I can't see the cursor flickering. I can only delete the characters that have been written on it, and I can't enter new characters. If make the window lose focus and regain focus, input text control belong to this window can return to normal.

### Screenshots
<img width="193" alt="Screenshots" src="https://user-images.githubusercontent.com/50982291/58948788-861b1000-87bd-11e9-9fb4-15e8dbefcb7a.PNG">

**Comment by baconbrad** [comment]
Can you clarify "popping up a message". Is this a custom dialog in your program, an Electron dialog, or a Chromium alert/confirm dialog?

**Comment by swzwqtxdy** [comment]
It's a alert/confirm dialog.

**Comment by krausekai** [comment]
Can confirm this occurs when using ``window.alert()`` dialog under Windows 10 1809, Electron 5.0.3. When clicking a field, it appears to focus in and out twice, made apparent by field highlight CSS. To restore typing functionality in a field, the window needs to be re-focused by alt-tabbing out and back in.

**Comment by zadam** [comment]
Can confirm exact same behavior as @krausekai and @swzwqtxdy described, in my case with window.confirm(), windows 10, electron 6.0.0-beta.11. This happens on windows only, linux is not affected.

**Comment by popod** [comment]
Exactly the same as @zadam. I can confirm that this issue only appears on Windows ! I'm on macOS and all works fine.

**Comment by jtenner** [comment]
Yep! A confirm box causes this behavior. It can be reset by opening up devtools or refreshing the page.  Any advice on how to fix this?

**Comment by swzwqtxdy** [comment]
Is this issus fixing?

**Comment by jackiepluto** [comment]
Met the same issue. When will it be fixed? Any schedule?

**Comment by jackiepluto** [comment]
Any update on this issue? It has been opened for nearly 3 months.

**Comment by mobitar** [comment]
I've posted a workaround here: https://github.com/electron/electron/issues/20400#issuecomment-539586029

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by pushkin-** [comment]
this is a dupe of [this](https://github.com/electron/electron/issues/19977) anyway
