### ISSUE TITLE
how can i get electron browserwindow physical id,not win.id

### ISSUE THREAD

**Issue by whitemiaool** [electron/electron#18642]
RT

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
