### ISSUE TITLE
specifying the default path for dialog to be "~/Desktop" does not work

### ISSUE THREAD

**Issue by dnory0** [electron/electron#18641]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v5.0.2
* **Operating System:**
  * Pop!_OS 19.04 x64 (Ubuntu 19.04 based)
* **Last Known Working Electron version:**
  * I did not try that on previous versions

### Expected Behavior
I expected the dialog box to open up by default on "home/{my-username}/Desktop".

### Actual Behavior
that differ, because I tried 2 options:
  1. defaultPath: "~/Desktop": it behaves as the path is invalid. 
  2. defaultPath: "/home/$USER/Desktop" it opens up at "/home", which to my understanding the dialog stopped at "/home/" because it couldn't neutralize the meaning of "$USER".

However I need to mention that both ways works on my terminal. and I'm not sure if the path specified for windows, which is "C:\\Users\\%username%\\Desktop"
### To Reproduce

```sh
$ git clone https://github.com/dnory0/xampp-htdocs-manager -b master
$ npm install
$ npm start || electron .
```

**Comment by MarshallOfSound** [comment]
@dnory0 Both `~` and `$USER` are not valid components in an absolute path.  You should construct this path manually using the [`app.getPath()`](https://electronjs.org/docs/api/app#appgetpathname) API.  E.g.

```js
const homeDir = app.getPath('home');
const desktopDir = path.resolve(homeDir, 'Desktop');
```

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

**Comment by dnory0** [comment]
my bad, so it's misperspecitveness of me since it's trickier than I thought, and thanks for your solution and time.
