### ISSUE TITLE
Window is not rendered if it is shown with .minimize method

### ISSUE THREAD

**Issue by clusterberries** [electron/electron#18651]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.2
* **Operating System:**
  * Windows 10 (1809)
* **Last Known Working Electron version:**
  * 4.2.3

### Expected Behavior
Window is rendered correctly and 'Lorem ipsum' is displayed

### Actual Behavior
Window is not rendered correctly, it is displayed blank

### To Reproduce
1. Create a window with `display: false` and call `win.minimize()` when `dom-ready` event is fired.
Or clone the repository and run sample app:
```sh
$ git clone https://github.com/clusterberries/electron-sample.git -b launch-minimized
$ npm install
$ npm start
```
2. Wait till window is displayed in the taskbar and click on it to open.

### Additional Information
If window is resized manually, it is re-rendered and text is displayed.
The issue is not reproduced on MacOS.
Also it is not reproduced with 6.0.0-beta.6

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
