### ISSUE TITLE
Tray icon becomes invisible when selecting "Auto" appearance in System Preferences on macOS 10.15 beta1

### ISSUE THREAD

**Issue by yeahdongcn** [electron/electron#18663]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 2.0.7
* **Operating System:**
  * macOS 10.15 beta1
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior

The tray icon can display clearly when selecting "Auto" appearance in System Preferences on macOS 10.15 beta1

### Actual Behavior

The tray icon is invisible when selecting "Auto" appearance in System Preferences on macOS 10.15 beta1

### To Reproduce

1. Install WD Discovery or VMware Fusion
2. Switch macOS 10.15 beta1 Appearance setting to "Auto"
3. Check the tray icon in the system menu bar
4. The tray icon is invisible

### Additional Information

Click on the tray icon, if you specify highlight/selected tray image, it displays well

**Comment by yeahdongcn** [comment]
This only reproduces when switching system appearance from "Dark" to "Auto" in daylight time.

**Comment by MarshallOfSound** [comment]
Thanks for the good report @yeahdongcn .  Catalina is still pretty new so we're going to see a few things like this, keep the reports coming 💯 

A PR to fix this one is referenced above.

**Comment by yeahdongcn** [comment]
Cool! But I'm still using electron 2.x, which release will contain your fix?

**Comment by MarshallOfSound** [comment]
Electron 2 is end of life it will not be receiving this fix

**Comment by yeahdongcn** [comment]
I notice there are a couple of versions, which version is recommended to migrate to? Thanks.

**Comment by MarshallOfSound** [comment]
The latest stable is Electron 5.  Electron 2 is quite old so I'd suggest upgrading to 5 but jumping 1 major at a time.  I.e. upgrade to 3, test fix and update your code.  Then jump to 4 then 5

**Comment by yeahdongcn** [comment]
Sounds good, thanks. Is there any document about how to migrate between these major versions?

**Comment by MarshallOfSound** [comment]
Most of the time it's as easy as changing the version number.  You may need to update some dependencies or update your code due to any breaking changes that impact you.  See this doc for breaking change info --> https://electronjs.org/docs/api/breaking-changes#breaking-api-changes-20
