### ISSUE TITLE
Circular loop 

### ISSUE THREAD

**Issue by BotellaA** [electron/electron#18667]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.2
* **Operating System:**
  *  Ubuntu 18.04 x64

### Expected Behavior

No crash

### Actual Behavior

Crash with this stack
```
../../third_party/tcmalloc/gperftools-2.0/chromium/src/free_list.h:72] Circular loop in list detected:  0x155976511c60 
Received signal 11 SEGV_MAPERR 000000000039
#0 0x556f0486fcbc (/home/camaud/programming/Geode/node_modules/electron/dist/electron+0x39adcbb)
#1 0x556f0486f811 (/home/camaud/programming/Geode/node_modules/electron/dist/electron+0x39ad810)
#2 0x7f85ce7fe890 (/lib/x86_64-linux-gnu/libpthread-2.27.so+0x1288f)
#3 0x556f02c902a0 (/home/camaud/programming/Geode/node_modules/electron/dist/electron+0x1dce29f)
#4 0x556f02c9425e (/home/camaud/programming/Geode/node_modules/electron/dist/electron+0x1dd225d)
#5 0x556f07883f14 (/home/camaud/programming/Geode/node_modules/electron/dist/electron+0x69c1f13)
#6 0x7f85b74d1440 <unknown>
#7 0x7f85b7125c9a <unknown>
#8 0x7f85b7124522 <unknown>
#9 0x7f85b751fd80 <unknown>
#10 0x7f85b74e24d9 <unknown>
#11 0x7f85b77be462 <unknown>
#12 0x556f0759b4b7 (/home/camaud/programming/Geode/node_modules/electron/dist/electron+0x66d94b6)
#13 0x556f03e71f27 (/home/camaud/programming/Geode/node_modules/electron/dist/electron+0x2faff26)
#14 0x556f03e722bd (/home/camaud/programming/Geode/node_modules/electron/dist/electron+0x2fb02bc)
#15 0x556f042bbead (/home/camaud/programming/Geode/node_modules/electron/dist/electron+0x33f9eac)
#16 0x556f042ba1c1 (/home/camaud/programming/Geode/node_modules/electron/dist/electron+0x33f81c0)
#17 0x556f042b90b1 (/home/camaud/programming/Geode/node_modules/electron/dist/electron+0x33f70b0)
#18 0x556f03e59031 (/home/camaud/programming/Geode/node_modules/electron/dist/electron+0x2f97030)
#19 0x556f04070346 (/home/camaud/programming/Geode/node_modules/electron/dist/electron+0x31ae345)
#20 0x556f0447edce (/home/camaud/programming/Geode/node_modules/electron/dist/electron+0x35bcdcd)
  r8: 0000000000000000  r9: cccccccccccccccd r10: 0000556f01aef9f0 r11: 0000000000000000
 r12: 00007ffc24983901 r13: 00007ffc249839b0 r14: 00007ffc24983888 r15: 0000000000000001
  di: 0000000000000000  si: 00007ffc24983888  bp: 00007ffc249839a0  bx: 0000000000000078
  dx: 0000000000000078  ax: 0000000000000001  cx: 00007f85ce7fd2b7  sp: 00007ffc24983858
  ip: 0000556f02c902a0 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000006
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000039
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

### To Reproduce

I am not sure how to reproduce this. There is nothing going on and this happen.

### Additional Information

Is there any way to have a more informative stack?

**Comment by codebytere** [comment]
Unfortunately, without a repro we're unable to triage or take action against this issue. Please provide one or we'll need to close this issue until one can be determined.

**Comment by nornagon** [comment]
Sadly symbolicating stacks on Linux isn't currently supported (though https://github.com/electron/electron/pull/18676 is looking promising!), so the only way to get a better stack would be to run the app under a version of Electron with debugging symbols. Either build Electron yourself or use one of our CI builds, e.g. dist.zip from here: https://circleci.com/gh/electron/electron/222323#artifacts/containers/0

**Comment by BotellaA** [comment]
Thanks for the advises. I will look into it to have a better stack.
