### ISSUE TITLE
Replace StatusItemView implementation with [NSStatusItem button]

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#18664]
Now that we have a supported platform list of >= 10.10 we can use the `[NSStatusItem button]` instead of the hacks and tricks we use currently.

**Comment by DeerMichel** [comment]
# Tray Migration for macOS Catalina

Docs: https://electronjs.org/docs/api/tray  

`statusItem: NSStatusItem`

## Instance Methods

- `destroy`
  * not tested, but shouldnt be a problem
- `setImage`
  * works via `[[statusItem button] setImage]`
- `setPressedImage`
  * works via `[[statusItem button] setAlternateImage]`
- `setToolTip`
  * works via `[[statusItem button] setToolTip]`
- `setTitle`
  * works via `[[statusItem button] setTitle]`
  * icon & text position needs to be set using `[[statusItem button] setImagePosition]`
- `getTitle`
  * works via `[[statusItem button] title]`
- `setHighlightMode`
  * i have no idea... 
  * there is no custom draw function anymore, maybe drop support for this func? or worth finding a custom solution which might break again in future macOS versions?
  * however there is `[NSButton setHighlighted]` which will be reset on click - maybe a custom click handler can uphold the highlighting state?
  * https://stackoverflow.com/questions/26004684/nsstatusbarbutton-keep-highlighted
- `setIgnoreDoubleClickEvents`
  * no idea about this one... my guess is a custom click handler
- `getIgnoreDoubleClickEvents`
  * correlates with setter
- `popUpContextMenu`
  * maybe?
- `setContextMenu`
  * works somehow via `[[statusItem button] setMenu]`
  * needs further investigation, e.g. radios, buttons not enabled (see #random channel)
  * `[statusItem popUpStatusItemMenu]` but did work.. but is deprecated yay
- `getBounds`
  * works via `[[statusItem button] frame]`
- `isDestroyed`
  * not tested, but shouldnt be a problem

## Events

- `click`
  * defaults to open assigned `[[statusItem button] menu]`
  * not sure if can be overriden
  * custom view needed for that, workaround?
- `right-click`, `double-click`
  * custom view needed for that, workaround?
- `drop`, `drop-files`, `drop-text`
  * custom view needed for that, workaround?
- `drag-enter`, `drag-leave`, `drag-end`
  * custom view needed for that, workaround?
- `mouse-enter`, `mouse-leave`, `mouse-move`
  * detected using a `NSTrackingArea`
  * attaching tracking area to `[statusItem button]` might work

Especially the events are problematic (at least from my point of knowledge). Also, theres no setter for `[statusItem button]`. Is there a workaround to change it to a custom `NSStatusBarButton` - and if so, would that help?

cc @codebytere @miniak @erickzhao

**Comment by sindresorhus** [comment]
> right-click

You can set what events triggers the `.action` on a button with [`sendActionOn:`](https://developer.apple.com/documentation/appkit/nscontrol/1428972-sendactionon?language=objc).

> double-click

You can just check the `.clickCount`: https://stackoverflow.com/a/16806632/64949
