### ISSUE TITLE
Auto update size reduction - updating only those files that have changed

### ISSUE THREAD

**Issue by Puritanic** [electron/electron#18673]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Hello everyone!

I have a question about delta (differential?) updates (if that means updating only the application files that have changed, instead of downloading the whole installer on update). I've done a small research about this feature, and discovered a lot of discussions about it and that it is somehow possible, but no one mentioned how :|

So, is there a way to update the application by updating only those files that have changed since the last version?

The application I’m working on right now has a requirement that updates should be as smallest as possible as the most of the devices will be on cellular data (paid per Mb) and possibly with poor network conditions.

So far Electron turned out to be a perfect solution for all our needs, but this auto-update issue might be a deal breaker.

Application is Windows only, and we’re using the latest version of Electron and `electron-builder` (which packages NSIS).

### Proposed Solution

Implement a way to update only those part of the application that has changed, maybe separate node/chromium build from the rest of the application so that those are not downloaded again when an update occurs.

Thanks in advance!

**Comment by MarshallOfSound** [comment]
@Puritanic The official `electron.autoUpdater` module in Electron uses [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows) which has built in support for delta updates.  If you use `electron-winstaller` these deltas will be generated for you

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

**Comment by Puritanic** [comment]
@MarshallOfSound Sorry but I've asked the exact same question on Discuss community and r/electron before opening an issue here but no one replied. 

I'll check out `electron-winstaller`, thank you!
