### ISSUE TITLE
Native node modules binaries targeting Electron 4+ are bloated

### ISSUE THREAD

**Issue by miniak** [electron/electron#18670]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
* **Electron Version:**
  * 4.2.x, 5.0.x, 6.0.0 beta
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 3.1.x

### Expected Behavior
Native node modules are built in release mode with node-gyp (via npm install) and the binary size is similar to modules built for Electron 3.

### Actual Behavior
Native node modules are not built with correct build settings, leading to bloated binaries

### To Reproduce
Create `.npmrc` with the following content
```
disturl = https://atom.io/download/atom-shell
runtime = electron
target = 4.2.0
arch = x64
```
`npm install diskusage` for example

### Screenshots
**Electron 3**
![size-e3](https://user-images.githubusercontent.com/1281234/59039543-54fe1680-8875-11e9-93fe-b6fc654a2060.png)

**Electron 4**
![size-e4](https://user-images.githubusercontent.com/1281234/59039547-56c7da00-8875-11e9-90e2-b460a0c150f4.png)

**Electron 5**
![size-e5](https://user-images.githubusercontent.com/1281234/59039552-58919d80-8875-11e9-98ba-fe9e41099b24.png)

**Electron 6**
![size-e6](https://user-images.githubusercontent.com/1281234/59039562-5a5b6100-8875-11e9-8c32-c2d9ea4044d4.png)

### Additional Information
At least with Electron 4, the issue is caused by `node_with_ltcg` not being set in `include/node/common.gypi`
```
['node_with_ltcg=="true"', {
'msvs_settings': {
    'VCCLCompilerTool': {
    'WholeProgramOptimization': 'true' # /GL, whole program optimization, needed for LTCG
    },
    'VCLibrarianTool': {
    'AdditionalOptions': [
        '/LTCG:INCREMENTAL', # link time code generation
    ]
    },
    'VCLinkerTool': {
    'OptimizeReferences': 2, # /OPT:REF
    'EnableCOMDATFolding': 2, # /OPT:ICF
    'LinkIncremental': 1, # disable incremental linking
    'AdditionalOptions': [
        '/LTCG:INCREMENTAL', # incremental link-time code generation
    ]
    }
}
}, {
'msvs_settings': {
    'VCCLCompilerTool': {
    'WholeProgramOptimization': 'false'
    },
    'VCLinkerTool': {
    'LinkIncremental': 2 # enable incremental linking
    }
}
}]
```

**Comment by nornagon** [comment]
See electron/node#104. I'll backport that to other node branches shortly.

**Comment by ckerr** [comment]
@nornagon did this fix the issue on Electron 6 / did this get backported?

**Comment by nornagon** [comment]
@miniak reported that the fix did not work.

**Comment by miniak** [comment]
@nornagon This is the PR, which caused `node_with_ltcg ` to not work anymore in `common.gypi` https://github.com/nodejs/node/pull/25931

**Comment by mastergberry** [comment]
Reporting that I am having this same issue. The output files have doubled in size and it seems to be linking a bunch of unused code.
