### ISSUE TITLE
Windows 10 S Mode  Code Integrity Issue

### ISSUE THREAD

**Issue by gaodeng** [electron/electron#18680]
### Issue Details

* **Electron Version:**
  * 4.x
* **Operating System:**
  *  Windows 10 (1809)
* **Last Known Working Electron version:**

### Actual Behavior
Code Integrity determined that a process (\Device\HarddiskVolume4\Program Files\WindowsApps\27425IcyArrow.MoonFM-PremiumPodcastApp_1.0.10.0_x64__z9kheaq1rx32y\app\Moon FM.exe) attempted to load \Device\HarddiskVolume4\Users\gaodeng\AppData\Local\Temp\1eadcc0e-a37f-49da-bd6c-2f3f59aa535f.tmp.node that did not meet the Enterprise signing level requirements or violated code integrity policy. However, due to code integrity auditing policy, the image was allowed to load.

### To Reproduce
https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-test-windows-s

### Additional Information
https://blogs.msdn.microsoft.com/appconsult/2017/06/15/porting-and-testing-your-classic-desktop-applications-on-windows-10-s-with-the-desktop-bridge/

**Comment by MarshallOfSound** [comment]
@gaodeng Just through a combination of experience and guess work you haven't configured your `app.asar` file correctly.  You need to have all your native node modules in `app.asar.unpacked` (see the `unpacked` options for the asar tool).

Any native modules in your `app.asar` (not in unpacked) will be extracted to the temporary directory and loaded from there.  This is the warning you are seeing here.  If you configure your asar with unpacked native node modules this error will not occur 👍
