### ISSUE TITLE
Better update cycle

### ISSUE THREAD

**Issue by AlexSHoffman** [electron/electron#18683]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Guys, wouldn't it make more sense to follow the traditional update cycle:

- Develop `v1.x.y` (where `x`-minor features; `y`-bug fixes) until there's a major feature that requires the 1st digit increment
- Release `v2.x.y beta` & stop updating `v1.x.y`
- Release `v2.x.y stable`
- Keep updating `v2.x.y` until there's a major feature, at which point you increment the 1st digit again (to `v3.x.y beta`) and stop updating `v2.x.y`
- ...

Right now you have to waste your time updating v3.x, that no one really cares about, instead of concentrating on v6.x.

### Proposed Solution

Follow a more logical traditional update cycle

**Comment by MarshallOfSound** [comment]
Hey @AlexSHoffman 

A lot of thought has gone into how we version, what we work on and how releases operate.  You can read more about how Electron Releases work at the links included below.

* [Releases Working Group](https://github.com/electron/electron/blob/master/docs/tutorial/electron-versioning.md)
* [Releases Working Group](https://github.com/electron/governance/tree/master/wg-releases)
* [Release Cadence](https://electronjs.org/blog/12-week-cadence)
* [Proposed Release Timeline](https://electronjs.org/docs/tutorial/electron-timelines)
