### ISSUE TITLE
Windows build fails

### ISSUE THREAD

**Issue by tindl88** [electron/electron#18693]
### Issue Details
  _• packaging       platform=win32 arch=x64 electron=**3.1.11** appOutDir=release\win-unpacked_

Why Electron version is 3.1.11? A few days ago it was version 4.x.x. (I'm using Electron version 5)

* **Electron Version:** 5.0.2
* **Operating System:** Windows 10

### Screenshots
![image](https://user-images.githubusercontent.com/4578761/59141619-b68bc580-89da-11e9-9258-0b7115ed597a.png)

**Comment by MarshallOfSound** [comment]
@tindl88 The `Latest release` flag on github is given to the release that is quite literally the "latest" (done by time).  The last release we published was `3.1.11`.

If `electron-builder` is using that version by default that is a flaw in builder, not electron itself
