### ISSUE TITLE
Add method for getting Windows 10 Shell Color

### ISSUE THREAD

**Issue by EnderDev** [electron/electron#18696]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
I need a way of checking if the user is in https://i.imgur.com/yvZYfsG.png
Windows Dark mode or light mode

### Proposed Solution
systemPreferences.getShellColorType()

### Alternatives Considered
n/a

### Additional Information
Because my app icon is white, I want it to invert if using the Windows 10 light mode.
https://i.imgur.com/dzsLQTs.png
You can barely see it in light mode.

**Comment by Jarodshow** [comment]
[`IsDarkMode()` already exists](https://github.com/electron/electron/blob/a0b1f4fe0b0341a4933fdfeb288dffc5601232fa/atom/browser/api/atom_api_system_preferences.cc#L32) so we could probably just update that function?

**Comment by vankop** [comment]
@codebytere Could I take it? It will be great to implement macOS dark mode too(It is possible since macOS Mojave update)

**Comment by vankop** [comment]
Looks like `NSAppearance` usage already exists https://github.com/electron/electron/blob/af108764c74880533a42da2a309b8728561a172e/atom/browser/api/atom_api_system_preferences_mac.mm#L48
https://github.com/electron/electron/blob/abab90f563c054c7b12319b87fb9f1130708f58c/atom/browser/mac/atom_application.h#L15

**Comment by EnderDev** [comment]
Yeah, just improving IsDarkMode() would be excellent.

**Comment by MarshallOfSound** [comment]
@vankop You're more than welcome to take a swing at this, the `isDarkMode` and `getAppLevelAppearance()` APIs have existed on macOS for a while now, an equivalent for Windows is what's missing here 👍

**Comment by caesar** [comment]
For Windows support for the `systemPreferences.isDarkMode()` API, see #15316.

However Windows now has two "dark mode" settings, one for apps and one for the taskbar.
If I understand correctly, this issue is for the setting which affects the taskbar?
Whereas `isDarkMode` would be for the setting which affects apps.

**Comment by EnderDev** [comment]
For shell (taskbar) we could use `systemPreferences.isShellDarkMode()`.

Then, just update the existing [`isDarkMode()`](https://github.com/electron/electron/blob/a0b1f4fe0b0341a4933fdfeb288dffc5601232fa/atom/browser/api/atom_api_system_preferences.cc#L32) for apps in Windows.

**Comment by EnderDev** [comment]
Any updates?

**Comment by vankop** [comment]
My apologies, could someone take this please.

**Comment by vedhasp** [comment]
Can I take it?

**Comment by erickzhao** [comment]
@vedhasp always open to PRs :)
