### ISSUE TITLE
Symbols are not accessible across processes

### ISSUE THREAD

**Issue by b4rd** [electron/electron#18707]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.2
* **Operating System:**
  * Windows 10 x64 (1903)

### Expected Behavior
Symbols can be accessed via ipc.

### Actual Behavior
Symbols are not accessible via ipc.

### To Reproduce
In a main script:
```
global.mySymbol = Symbol('test')
```

In a renderer script:
```
const { remote } = require('electron')
console.log('symbol from main', remote.getGlobal('mySymbol')) //undefined
```

#### An electron-quickstart branch with the example above:
```sh
$ git clone https://github.com/b4rd/electron-quick-start.git -b symbols-test
$ npm install
$ npm start
```

**Comment by MarshallOfSound** [comment]
@b4rd IPC (and `remote`) works through serialization.  Symbols can't be serialized so they can't be shared between processes.

**Comment by b4rd** [comment]
Makes sense. Would be nice to have something about this in the documentation though.

**Comment by zyead** [comment]
‏‫من الـ iPhone الخاص بي‬
