### ISSUE TITLE
Can't load external/native modules using webpack 4 dev server

### ISSUE THREAD

**Issue by ir-fuel** [electron/electron#18703]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.3
* **Operating System:**
  * macOS 10.14.4
* **Last Known Working Electron version:**
  * 1.7.8

### Expected Behavior
When `require`'ing a moduled declared as external in my Webpack config, it should load

### Actual Behavior

I get an error:
```
Uncaught Error: Cannot find module XXX
```

### To Reproduce

Clone this repo `https://github.com/ir-fuel/electron-problem`

```
git clone https://github.com/ir-fuel/electron-problem
npm install
cd app
npm install
cd ..
npm run development
```

### Additional Information

I need to update an app I wrote over 2 years ago. At that point in time I was using Electron 1.7 and Webpack 1. I tried upgrading this to Electron 5 and Webpack 4 and that is where the problems started. So I have no idea where this started to break, nor can I report this in the Webpack repo as using require in code that runs on a client is something specific for Electron.

Everything is supposed to run in the `app` subfolder (and that's how it is configured in my Webpack config). There you can also find a second `package.json` containing only the modules needed at runtime (used by `electron-builder`). I don't know if this is still the way to do things today, but there was so much to change I spent a pretty horrible evening tbh. It's a full time job to keep up with all dependency updates of a project it seems :D 

Any idea?

**Comment by MarshallOfSound** [comment]
@ir-fuel Electron 5 changed the default value of `nodeIntegration` from `true` to `false` as per our breaking changes [document](https://github.com/electron/electron/blob/master/docs/api/breaking-changes.md#planned-breaking-api-changes-50).  Native modules depend on that setting

**Comment by ir-fuel** [comment]
But that value is set to `true` in my code?
```
  win = new BrowserWindow({
    width: 1280, height: 800,
    minWidth: 1280, minHeight: 800,
    center: true,
    autoHideMenuBar: true,
    webPreferences: {
      nodeIntegration: true,
      experimentalFeatures: true
    }
  })
```
