### ISSUE TITLE
Is it possible to create an instance of an electron app inside of another electron app?

### ISSUE THREAD

**Issue by Avivhdr** [electron/electron#18702]
Hi React-Electron community,

It's my first week with electron and i was wondering if the following thing possible to do with a React-Electron app?
I've tried making it work and stumbled on some issues with it.

I need to create 3 separate apps:
1. App A - React-Electron app.
2. App B - React-Electron app.
3. Dashboard App - React-Electron app that can show instances of App A & App B.
I attached an image to make it clearer.

Because it's with react, i can easily import the app.js files of App A & App B to the Dashboard App but that doesn't solve the problem of loading\starting the Electron process of App A & App B.

So the question is:
Can i import an existing Elecron-React app to another one **and by doing that making the electron process of the imported app runs (parallel to the process of the main app - dashboard app)**?

![image](https://user-images.githubusercontent.com/23265867/59162080-a287b700-8af3-11e9-9ff5-a700bcc59140.png)

Thank You very much

**Comment by vladimiry** [comment]
Something you might want to check out https://github.com/sentialx/multrin.

**Comment by codebytere** [comment]
> Can i import an existing Electron-React app to another one and by doing that making the electron process of the imported app runs (parallel to the process of the main app - dashboard app)

Unfortunately the most straightforward answer to this is no: the above (multrin) is the closest it's currently possible to get.
