### ISSUE TITLE
The BrowserView.id does not match event.sender.id

### ISSUE THREAD

**Issue by krausekai** [electron/electron#18712]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  * 5.0.3
* **Operating System:**
  * Windows 10 (1809)
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior

``BrowserView.id`` returns an ID of "1", and this should be the same ID as the ``event.sender.id`` from a fired event when caught by ``BrowserView.webContents.on``.

### Actual Behavior

When creating a ``BrowserView`` with ``addBrowserView``, during creation the ``BrowserView`` has an ID of "1", and it can be accessed correctly via ``BrowserView.fromId(id)``. Events fired from the ``BrowserView`` have two forms of id, the ``event.sender.id`` and the ``event.sender.webContents.id``. In this fired event, both ``event.sender.id`` and ``event.sender.webContents.id`` are the same value of "3", when it is expected that ``event.sender.id`` should be the same id as ``BrowserView.id`` with a value of "1".

### To Reproduce

From a render process, using the console:

```
var { BrowserView, BrowserWindow } = require('electron').remote;
var view = new BrowserView();
BrowserWindow.getAllWindows()[0].addBrowserView(view); // alternatively: .getFocusedWindow()
view.setBounds({ x: 0, y: 0, width: 480, height: 480 });
view.webContents.loadURL('https://electronjs.org/');

console.log("View ID at creation is: " + view.id);
console.log("View webContents ID at creation is: " + view.webContents.id);

view.webContents.on("dom-ready", (e) => {
	console.log("Response ID is: " + e.sender.id); // does not match creation ID
	console.log("Response webContents ID is: " + e.sender.webContents.id);
});
```

Output:

> VM885:7 View ID at creation is: 1
> VM885:8 View webContents ID at creation is: 3
> VM885:11 Response ID is: 3
> VM885:12 Response webContents ID is: 3

### Screenshots

N/A

### Additional Information

N/A

**Comment by MarshallOfSound** [comment]
This is expected behavior. `e.sender` is the webContents, not the browser view.
