### ISSUE TITLE
How to move webview between BrowserWindows

### ISSUE THREAD

**Issue by steelbrain** [electron/electron#1871]
Just like how we move tabs between windows in chrome, How does one move webviews between BrowserWindows?

**Comment by jwu** [comment]
Is this possible? I'm also curious of this.

**Comment by zcbenz** [comment]
Currently there is no way to do that.

**Comment by lukeapage** [comment]
Any idea how difficult a feature this would be?

**Comment by xywz** [comment]
@lukeapage see #3347.

**Comment by Mossop** [comment]
I have a patch that does this, would it be accepted?

**Comment by lukeapage** [comment]
@Mossop #3347 was a patch but it didn't get merged because there was no documentation for it. I assume that @zcbenz would merge it if a similiar updated patch was created with documentation.

**Comment by telmo2015** [comment]
Good Afternoon, people, My name is Telmo A.M. I would like to know, repositories of Api Saxo Bank, so I can begin to understand, and log in and consult the candles through the exchanges. and everything there. Could someone help me there? Thank you.
