### ISSUE TITLE
Dialog does not block main process on Windows 10

### ISSUE THREAD

**Issue by ruihanzhao** [electron/electron#18719]
The functionality of this message box/dialog is to pop up before the application opens (before the main window/browserwindow is initialized) and show the user a warning. On OSX, this works perfectly fine (the app will jump in the doc, upon clicking, you see the modal message and AFTER clicking ok, are taken to the app). However, on windows, the message box does not block the main process and the modal and main window are opened at the same time, with the main window actually being usable and responsive even if the modal is not closed. 

I am using `dialog.showMessageBox()` without passing in a BrowserWindow since one has not yet been initialized at the point that the modal appears. 

Any help on why this is behaving differently on Windows and OSX would be greatly appreciated!

### Expected behavior:
On Windows the message box will block execution of the process until the message box is closed, just like on OSX.

### Actual behavior: 
The message box appears and the process continues (main app is usable). Main app foregrounds and message box goes behind it so it is easy to miss. This is only the case on Windows.

Electron version: 3.1.6

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by codebytere** [comment]
With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
