### ISSUE TITLE
The clipboard api can not read the title of link

### ISSUE THREAD

**Issue by myaisv** [electron/electron#18711]
When I copy a note link in Evernote Desktop application, the link have both title information  and url information, like follows:

copy a note link in evernote app:
<img width="1196" alt="copy_a_link" src="https://user-images.githubusercontent.com/10362876/59194135-99ade880-8bba-11e9-8b62-bab26f37ec19.png">

we can get the title information if paste it back to Evernote:
<img width="1195" alt="link_has_title_info" src="https://user-images.githubusercontent.com/10362876/59194141-a3375080-8bba-11e9-8043-9fc49d26c604.png">

the link title is "TestNoteOne" and the url is "https://app.yinxiang.com/shard/s57/nl/2147483647/0deb97d5-c275-4621-bcd7-33ae6fb4b9b0/"

but I can't get the title using current clipboard api, the api result as follows:
<img width="770" alt="result" src="https://user-images.githubusercontent.com/10362876/59194228-ef829080-8bba-11e9-9225-edeaa4488954.png">

I can read  the title info by using Xcode and swift language, thus the information is in the clipboard, but  is there a way to read the title in Electron :) ?

**Comment by miniak** [comment]
@myaisv which macOS API do you use in Xcode to read the title?

**Comment by myaisv** [comment]
Sorry, I figure it out. This  can be done with the clipboard.read('xxx') api in Electron.

macOS API:
`

 let pasteboard = NSPasteboard.general
        guard let pasteboardItems =  pasteboard.pasteboardItems else{
            return
        }
        Swift.print("pasteboardItems count:\(pasteboardItems.count)")
        
        for element in pasteboardItems{
            if let str = element.string(forType: NSPasteboard.PasteboardType(rawValue: "public.utf8-plain-text")) {
                Swift.print("public.utf8-plain-text:")
                Swift.print(str)
            }
            
            if let str = element.string(forType: NSPasteboard.PasteboardType(rawValue: "com.evernote.notelink.html")) {
                Swift.print("com.evernote.notelink.html:")
                Swift.print(str)
            }
            
            
        }

`

![clipboard](https://user-images.githubusercontent.com/10362876/59248490-23aa8f80-8c55-11e9-816e-8376bd06b88c.png)

In electron:
I can get the information by using:
clipboard.read("com.evernote.notelink.html");
