### ISSUE TITLE
Electron crash when call indexeddb getAll() api

### ISSUE THREAD

**Issue by kasnihuang** [electron/electron#18725]
When I using Indexeddb getAll() in Electron(5.0.2), macOSX 10.13.6, the electron exit immediately. Could you help to take a look.

`Application Specific Information:
Fatal Error: EXC_BREAKPOINT / EXC_I386_BPT

Thread 2328252 Crashed:
0 Electron Framework 0x111389f67
1 Electron Framework 0x11138e116
2 Electron Framework 0x11138e5c7
3 Electron Framework 0x113d1018b
4 Electron Framework 0x113d10000
5 Electron Framework 0x11138ce31
6 Electron Framework 0x111388584
7 Electron Framework 0x11137e2ef
8 Electron Framework 0x112586203
9 Electron Framework 0x11099eea5
10 Electron Framework 0x110fee3a0
11 Electron Framework 0x11102d222
12 Electron Framework 0x11259c933
13 Electron Framework 0x1125b73af
14 Electron Framework 0x1125b7913
15 Electron Framework 0x112657c24
16 Electron Framework 0x1125d62d8
17 Electron Framework 0x110e31c24
18 Electron Framework 0x11261b3ca
19 Electron Framework 0x112658047
20 libsystem_pthread.dylib 0x7fff7f064661
21 libsystem_pthread.dylib 0x7fff7f06450d
22 libsystem_pthread.dylib 0x7fff7f063bf9

Thread 2328175
0 libsystem_kernel.dylib 0x7fff7ee9320a
1 CoreFoundation 0x7fff56e3d785
2 CoreFoundation 0x7fff56e3cad7
3 CoreFoundation 0x7fff56e3c153
4 HIToolbox 0x7fff56126d96
5 HIToolbox 0x7fff56126b06
6 HIToolbox 0x7fff56126884
7 AppKit 0x7fff543d7a73
8 AppKit 0x7fff54b6de34
9 AppKit 0x7fff543cc885
10 Electron Framework 0x11265e97c
11 Electron Framework 0x11265d4bf
12 Electron Framework 0x1125d62d8
13 Electron Framework 0x110e2a1f3
14 Electron Framework 0x110e2a030
15 Electron Framework 0x110e2c052
16 Electron Framework 0x110e26f04
17 Electron Framework 0x1121eb51e
18 Electron Framework 0x1121eb191
19 Electron Framework 0x113d9524f
20 Electron Framework 0x1121ea5e4
21 Electron Framework 0x1102d2513 AtomMain
23 libdyld.dylib 0x7fff7ed4c015 [inlined]
24 libdyld.dylib 0x7fff7ed4c015

Thread 2328207
0 libsystem_kernel.dylib 0x7fff7ee9d28a
1 libsystem_pthread.dylib 0x7fff7f063be9
2 libdispatch.dylib 0x7fff7ed146f0

Thread 2328236
0 libsystem_kernel.dylib 0x7fff7ee9d28a
1 libsystem_pthread.dylib 0x7fff7f063be9

Thread 2328237
0 libsystem_kernel.dylib 0x7fff7ee9d28a
1 libsystem_pthread.dylib 0x7fff7f063be9
2 libsystem_malloc.dylib 0x7fff7eef6c7c
3 libdispatch.dylib 0x7fff7ed302de
4 libobjc.A.dylib 0x7fff7e13b653
5 libsystem_platform.dylib 0x7fff7f05d7ad
6 libsystem_malloc.dylib 0x7fff7eef6679
7 libdispatch.dylib 0x7fff7ed13d3c
8 libdispatch.dylib 0x7fff7ed15aea
9 QuartzCore 0x7fff621be361
10 libdispatch.dylib 0x7fff7ed12db8
11 libdispatch.dylib 0x7fff7ed1fcc5
12 libdispatch.dylib 0x7fff7ed224d1
13 libdispatch.dylib 0x7fff7ed14cc2
14 libdispatch.dylib 0x7fff7ed14755
15 libsystem_pthread.dylib 0x7fff7f06420e
16 libsystem_pthread.dylib 0x7fff7f063be9
17 libdispatch.dylib 0x7fff7ed2b9b1

Thread 2328247
0 libsystem_kernel.dylib 0x7fff7ee9dbea
1 Electron Framework 0x11266203d
2 Electron Framework 0x112657cde
3 Electron Framework 0x1125d62d8
4 Electron Framework 0x11260acd7
5 Electron Framework 0x11261b3ca
6 Electron Framework 0x112658047
7 libsystem_pthread.dylib 0x7fff7f064661
8 libsystem_pthread.dylib 0x7fff7f06450d
9 libsystem_pthread.dylib 0x7fff7f063bf9

Thread 2328248
0 libsystem_kernel.dylib 0x7fff7ee9320a
1 Electron Framework 0x1125eada0
2 Electron Framework 0x1125eaeb1
3 Electron Framework 0x1126067d8
4 Electron Framework 0x112606b42
5 Electron Framework 0x112606a54
6 Electron Framework 0x112658047
7 libsystem_pthread.dylib 0x7fff7f064661
8 libsystem_pthread.dylib 0x7fff7f06450d
9 libsystem_pthread.dylib 0x7fff7f063bf9

Thread 2328253
0 libsystem_kernel.dylib 0x7fff7ee9dbea
1 Electron Framework 0x1158e6560 uv_run
2 Electron Framework 0x115864536
3 libsystem_pthread.dylib 0x7fff7f064661
4 libsystem_pthread.dylib 0x7fff7f06450d
5 libsystem_pthread.dylib 0x7fff7f063bf9

Thread 2328255
0 libsystem_kernel.dylib 0x7fff7ee9ca16
1 Electron Framework 0x1158f1778 uv_cond_wait
2 Electron Framework 0x115864638
3 Electron Framework 0x1158623b8
4 libsystem_pthread.dylib 0x7fff7f064661
5 libsystem_pthread.dylib 0x7fff7f06450d
6 libsystem_pthread.dylib 0x7fff7f063bf9

Thread 2328257
0 libsystem_kernel.dylib 0x7fff7ee93246
1 Electron Framework 0x1158accf1 node::inspector::Agent::GetWorkerManager
2 libsystem_pthread.dylib 0x7fff7f064661
3 libsystem_pthread.dylib 0x7fff7f06450d
4 libsystem_pthread.dylib 0x7fff7f063bf9
5 Electron Framework 0x1158accdf node::inspector::Agent::GetWorkerManager`

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
