### ISSUE TITLE
-webkit-app-region: drag force an element to show contextmenu.

### ISSUE THREAD

**Issue by Sombian** [electron/electron#18729]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.3
* **Operating System:**
  * windows 10 x64
* **Last Known Working Electron version:**
  * none

### Expected Behavior

let us adjusted draggable area.
### Actual Behavior

`-webkit-app-region: drag` force an element to show contextmenu when right-clicked and cant be ignored with javascript. wont even fire any functions bounded to it also. is this intended behavior?
### To Reproduce

put css tag `-webkit-app-region: drag` and rightclick or bound any event then try fire it.

### Screenshots

![image](https://user-images.githubusercontent.com/23397550/59273896-2a0c2c00-8c94-11e9-9015-08c51667296c.png)

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.1.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
