### ISSUE TITLE
Add getBounds for BrowserView like BrowserWindow

### ISSUE THREAD

**Issue by krausekai** [electron/electron#18734]
### Feature Request

The only current way to get the parameters set by ``setBounds`` of a ``BrowserView`` seems to be to store it as a global variable at creation, and to reference that variable. Ideally, there should be a way to get this information from the created ``BrowserView`` directly with ``getBounds``, like the ``BrowserWindow``. This is particularly important if the bounds of the ``BrowserView`` has been changed by ``setAutoResize`` after creation, because the bounds no longer match a stored global variable.

**Comment by payitforwardnow** [comment]
Electron version 7.0.0 and getBounds is still undefined for BrowserView. If getBounds is not supported for BrowserView PLEASE remove it from the documentation.

**Comment by rlingineni** [comment]
@payitforwardnow - I has a similar problem, didn't update my electron version to something greater than 7. Hence the error for me.
