### ISSUE TITLE
<input type="date"> does not show Japanese calendar as date chooser

### ISSUE THREAD

**Issue by agata** [electron/electron#18737]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.0-beata.7
* **Operating System:**
  * Mac OS 10.14.5
* **Last Known Working Electron version:**
  * 5.0.3

### Expected Behavior
1. Change system language to Japanese. Then clicking lower triangular arrow on <input type="date">, show Japanese calendar as date chooser.

2. Change system language to English. Then clicking lower triangular arrow on <input type="date">, show English calendar as date chooser.

### Actual Behavior
1. Change system language to Japanese. Clicking lower triangular arrow on <input type="date">, nothing happens.

2. Change system language to English. Then clicking lower triangular arrow on <input type="date">, show English calendar as date chooser.

### To Reproduce

1. Change system language to Japanese

2. Clone and run
```sh
$ https://github.com/agata/electron-reproduce-calendar-bug.git
$ cd electron-reproduce-calendar-bug
$ npm install
$ npm start
```

3. Clicking lower triangular arrow
This app shows <input type="date"> element. Clicking lower triangular arrow on <input type="date">, nothing happens.

#### 5.0.3
<img width="802" alt="5 0 3" src="https://user-images.githubusercontent.com/40473/59315955-0af2b600-8cf7-11e9-9ea2-462395143376.png">

#### 6.0.0-beta.7
<img width="802" alt="6 0 0-beta 7" src="https://user-images.githubusercontent.com/40473/59315957-0cbc7980-8cf7-11e9-90f9-0381c401eb13.png">

**Comment by nornagon** [comment]
This also appears to be broken in Chrome (I tested current Canary, which is 77.0.3830.0).

Can you confirm whether you're also seeing this issue in Chrome? I looked around for relevant issues on the bug tracker and found https://bugs.chromium.org/p/chromium/issues/detail?id=919712 but I don't think that's describing this issue (just Reiwa-related backports). I think it would make sense to file a new issue in Chromium: https://crbug.com/new. We'll keep this issue open to track upstream work.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
