### ISSUE TITLE
Files that have not been downloaded will be deleted when exiting the app.

### ISSUE THREAD

**Issue by ZhangZheng-GIS** [electron/electron#18739]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.3
* **Operating System:**
  * Windows 10  x64 
* **Last Known Working Electron version:**
  * none

### Expected Behavior

Pause/interrupt the downloading file and keep the unfinished file when exiting the electron app.
### Actual Behavior

Files that have not been downloaded will be deleted when exiting the electron app.
### To Reproduce

I use the `contents.downloadURL(url)` method to download the file and `downloadItem.pause()` to pause it and `app.exit()` to exit the app.
### Screenshots

<img src=http://chuantu.xyz/t6/702/1560331740x1709417261.gif />

**Comment by MarshallOfSound** [comment]
@ZhangZheng-GIS This is expected behavior, there is no way to resume the download if we left the temp files lying around.  This is the same behavior as Chrome, download a file, pause it, relaunch chrome, the temporary file was removed.
