### ISSUE TITLE
Add support for writing Electron apps in Swift

### ISSUE THREAD

**Issue by albert-tomanek** [electron/electron#18731]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Electron apps tend to be substantially slower than native apps due to all app logic being written in JavaScript.

### Proposed Solution

Adding support for a compiled language such as Swift to replace the JS/Node app logic. This would involve exposing the Electron API to it, as well as enabling it to communicate with the HTML UI (respond to events, modify the DOM, etc.).

Implementing this would combine the efficiency and versatility of HTML with the power and speed of Swift, a language that offers many of the features of modern JS but without the slowdown of an interpreted language.

Swift is available for all of the three platforms that Electron supports, being officially supported on macOS and Linux and having unofficial builds for Windows as well.

### Additional Information

The Electron APIs are exposed to JavaScript via `native_mate`, which registers all classes and methods at runtime. Although this is sub-optimal for interfacing with a compiled language, it would be the easiest option, and would be possible as Swift supports [dynamic member lookup](https://www.hackingwithswift.com/articles/55/how-to-use-dynamic-member-lookup-in-swift); so exposing the API to swift would simply require creating a copy of `native_mate` that would add methods to Swift classes on the fly. The only thing that would then remain to be done would be enabling Swift to communicate with the HTML DOM, by creating a DOM API for Swift that would talk to Chromium under the hood.

### Alternatives Considered

None

**Comment by nornagon** [comment]
> Electron apps tend to be substantially slower than native apps due to all app logic being written in JavaScript.

I'm curious how you came to this conclusion—in my experience, the speed of execution of JavaScript is not really a performance bottleneck in most Electron apps. For apps that do CPU-bound work, Node native modules are a good way of optimizing performance-sensitive code where necessary.

I'm closing this for now as it's not something we'd consider doing in the near term, but I'm happy to continue conversation in the issue.
