### ISSUE TITLE
Support for BigBuffer in IPC broken in 6.x and nightly

### ISSUE THREAD

**Issue by issacgerges** [electron/electron#18758]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
7.0.0-nightly.20190611
* **Operating System:**
MacOS 10.14.5
* **Last Known Working Electron version:**
v5.0.3

### Expected Behavior
With the merge of https://chromium.googlesource.com/chromium/src/+/4c5bd80e, legacy `ipc` internally uses BigBuffer and should support large messages.

### Actual Behavior
Electron crashes when `ipc.send` is called with a large arg (~134mb)

### To Reproduce
The following can be opened in electron-fiddle to reproduce the issue

https://gist.github.com/issacgerges/370a76335fd699930c43bde5cbeb41b7

**Comment by issacgerges** [comment]
Using lldb it looks like the 6.x error was introduced with this change https://chromium.googlesource.com/chromium/src/+/66.0.3359.158/mojo/edk/system/node_channel.cc#900

The 7.x-nightly error appears to be unrelated, due to porting away from legacy ipc

**Comment by coreh** [comment]
<img width="1847" alt="image" src="https://user-images.githubusercontent.com/418473/59391947-4ff50780-8d4c-11e9-9993-a2aa380d9f92.png">

Yeah, perhaps there is a way we can set `max_message_num_bytes`?

I tried using something like

```javascript
app.commandLine.appendSwitch('max_message_num_bytes', '4096000000');
```

But it doesn't seem to be recognized

**Comment by nornagon** [comment]
@issacgerges hm.. i'm not sure how that change could result in an error in 6.x since it was introduced in Chrome 66?

I think the right way to handle this would be to add something like `ipcRenderer.sendBuffer('channel', args, buf)` that uses the `mojo_base.mojom.BigBuffer` data type under the hood, rather than trying to make `send` support arbitrarily large data. @issacgerges I'd be happy to help you out getting a PR up for that :)

**Comment by nornagon** [comment]
I don't have time to work on this at the moment, but I'm happy to help someone else who wants to tackle it.

**Comment by codebytere** [comment]
Resolved by https://github.com/electron/electron/pull/20214.
