### ISSUE TITLE
shell.openExternal API does not bring the opened application to the foreground

### ISSUE THREAD

**Issue by ecarriou** [electron/electron#18754]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.3
* **Operating System:**
  * macOS 10.14.5
* **Last Known Working Electron version:**
  * 4.0.8

### Expected Behavior

Calling `shell.openExternal` API opens by default the url in the default browser and brings the opened application to the foreground.

### Actual Behavior

Calling `shell.openExternal` API opens by default the url in the default browser and the opened application is behind the electron application.

**Comment by codebytere** [comment]
Fixed by https://github.com/electron/electron/pull/18721.
