### ISSUE TITLE
About the shadow under the window

### ISSUE THREAD

**Issue by GlodenBoy** [electron/electron#18765]
When I set transparent :false , a transparent window with a shaded border is displayed first, and then the normal window is displayed.

I don't want to enable ready-to-show, which will make the loading feel slower.

Normal when transparent : true is set, but the program has no shadow borders.

Is there any way to remove the shadow window at startup, after the window is displayed, the shadow frame is loaded?

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
