### ISSUE TITLE
Adding a feature that can hot update application while starting it

### ISSUE THREAD

**Issue by TongDaDa** [electron/electron#18767]
Hi.

As far as I found the practical method of `update application` in electron is the way of reinstalling the application.  Ideally, I want to make my app only to update inner-page, that means it just needs to change some resources (i.e HTML, CSS, js, and image), it without any `native-code`, and starts the electron-app to detect the `patch-version`  for each time, if it needs to update the `patch-version`, I give it an `update-page` for waiting it updates the local resources until It has done, and then entering the `main-page` that is original page without any type of update.

Could you give me a direction of what library can resolve the above problem?

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Proposed Solution

We can write a custom directory that contains some resources(ie. HTML, CSS...), updating it when I found it has a newer version, and then it replaces the downloaded resources to the local `resources-directory`.

**Comment by codebytere** [comment]
This is something that would be an effective userland tool, and so we would happily welcome it being added there, but at this time this isn't functionality the maintainers feel should be intrinsic to Electron itself.

**Comment by TongDaDa** [comment]
@codebytere Do you know any thing about that tools?
