### ISSUE TITLE
Missing headers file for building native code for ElectronJS v3.0.16

### ISSUE THREAD

**Issue by lissyx** [electron/electron#18787]
### Issue Details

* **Electron Version:**
  * 3.0.16
* **Operating System:**
  * Linux, macOS, Windows
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
File at https://atom.io/download/electron/v3.0.16/node-v3.0.16-headers.tar.gz is downloadable

### Actual Behavior
`node-gyp` / `node-pre-gyp` build fails with 404 on https://atom.io/download/electron/v3.0.16/node-v3.0.16-headers.tar.gz

**Comment by lissyx** [comment]
I could successfully access 4.0.3, 4.1.4, 5.0.0, but anything earlier seems to have disappeared ? I could understand older releases to be cleaned up, but according to https://electronjs.org/releases/stable?version=3&page=3#3.0.16 this one is just three months old.

**Comment by lissyx** [comment]
For context, we do call `node-pre-gyp` with `--target=3.0.16 --disturl=https://atom.io/download/electron --runtime=electron` and it was working flawlessly over the past weeks.

**Comment by lissyx** [comment]
https://github.com/electron/electron/commit/e73a0e6cc66665d83242e263bc8718c42ffd7c7e

**Comment by lissyx** [comment]
@MarshallOfSound Looks like the URL we were using is deprecated, but even on the new one, I can't find those files: https://electronjs.org/headers/v3.0.16/node-v3.0.16-headers.tar.gz Do you know if that is on-purpose ?

**Comment by MarshallOfSound** [comment]
@lissyx Drop back to `node-gyp` 4.x for now, looks like the latest release of node-gyp (went out today) broke support for Electron < 4.

https://github.com/nodejs/node-gyp/issues/1778

Gonna leave this open just so folks coming to our tracker can find it while node-gyp is fixed.

**Comment by lissyx** [comment]
@MarshallOfSound Sent a PR with new URL and forcing `node-gyp@4.x`, and it is indeed starting to turn green, thanks for the workaround !

**Comment by codebytere** [comment]
Closing as this has been addressed and fixed on the `node-gyp` end.
