### ISSUE TITLE
http2 code in Electron 5/6 suffers from a known memory leak

### ISSUE THREAD

**Issue by mrfelton** [electron/electron#18817]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
The current version of node (12.0.0) that is embedded in Electron suffers from a memory leak in the http2 code that makes it impossible to use grpc without fatal memory overflow errors.

See https://github.com/nodejs/node/issues/27416

The issues has been resolved in https://github.com/nodejs/node/pull/27914 and the fix is included in [node v12.4.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.4.0)

### Proposed Solution
Update node to 12.4.0

### Alternatives Considered
Without this upgrade, the only way to use grpc is to downgrade Electron to v4.

**Comment by MarshallOfSound** [comment]
As per our versioning policy a minor bump in node would be a minor bump in Electron.  It would be easier / make more sense for us to float the individual patch commit onto our node branch.

Refs: https://github.com/nodejs/node/commit/b84b4d8c7dc957dd630a66ee372c6f29e173e98d

**Comment by mrfelton** [comment]
Hi. Thanks for the info. Can you give any pointers as to where these change needs to be made? We're currently unable to release until this issues is resolved (or face the prospect of having to downgrade to electron v4). Any thoughts as to when it's likely that this could get fixed and released into 5.x?
