### ISSUE TITLE
Overlay div over browserwindow

### ISSUE THREAD

**Issue by EnderDev** [electron/electron#18816]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
I am trying to overlay a div over the BrowserWindow like a little snackbar which says "Update available" for example. Or even a custom ContextMenu.

### Proposed Solution
Not sure

### Alternatives Considered
Maybe apply a property in the webPreferences

### Additional Information
N/A

**Comment by EnderDev** [comment]
I believe this was possible in the past with webview, just wondering if it's possible in BrowserView

**Comment by MarshallOfSound** [comment]
A BrowserView will render above the content being rendered in the BrowserWindow itself

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
