### ISSUE TITLE
process.versions should include boringssl

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#18827]
On a similar vein to https://github.com/electron/electron/issues/18826 the `process.versions` object should include the `boringssl` version to allow people to do version checks 👍

**Comment by DeerMichel** [comment]
See #18826.

**Comment by jkleinsc** [comment]
@DeerMichel this shouldn't be closed until a PR addressing this is merged in.

**Comment by nornagon** [comment]
Closing this as a duplicate of #18826.
