### ISSUE TITLE
Choosing appropriate fallback font list by system locale (especially on Windows)

### ISSUE THREAD

**Issue by sorah** [electron/electron#18829]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Under a Windows machine using English as a display language, Japanese kanji texts are rendered with Chinese font `SimSum`. This behavior matches with Chrome's one if the machine doesn't list Japanese as an alternative preferred locale, and HTML content language is set to `en-US`.
But if the machine lists Japanese as an alternative, Electron should render the text with Japanese fonts.

AFAIK, Chrome renders kanji texts (Han script) with Japanese fonts when the accept-language configuration includes Japanese, as reading Chromium (blink)'s [font_fallback_win.cc](https://cs.chromium.org/chromium/src/third_party/blink/renderer/platform/fonts/win/font_fallback_win.cc). This behavior is done by considering the system locales including secondary/alternative locales. Because of this, I don't encounter the same problem in Chrome.

Looks like Electron currently honors only primary system locale and content locale (HTML `lang`), but not secondary/alternative locales. Thus I think Electron's current behavior is not following Chrome's one.

As I'm not familiar with the Electron codebase, I'm still not sure why the current implementation doesn't make this problem on Mac. I'm listing Japanese as an alternative locale both on my Mac and Windows machine, but this problem happens only on Windows; as looking into font related codes in Chromium, I guess macOS' CoreText is doing good for choosing a font.

Related to #15486 #18197.

In real life, for Slack workspace/Discord servers where its primary language is Japanese, this problem forces people using English as a primary system language to read Japanese with an unmatched font, which is rendered ugly as a Japanese text. I don't think letting app developers using Electron to implement font configuration is happy, just for this problem. Electron should provide a good default to devs.

### Proposed Solution

Get _all_ preferred locales from OS and set them to Chromium engine. I'm guessing https://github.com/electron/electron/pull/15532 fixes this problem.

#### Japanese text shown on Slack app (Windows)

![Japanese text](https://img.sorah.jp/x/20190616_130936_PbjXWPa70A.png)

If I manually change `<html>` lang to `ja-JP`, kanji text starts rendered with Japanese font, Meiryo.

#### Windows Language Preference

![English, Japanese](https://img.sorah.jp/x/20190616_130723_KbBw6nUXLK.png)

#### Mac Language Preference

![English, Japanese](https://img.sorah.jp/x/20190616_131026_DagQq3fgNc.png)

**Comment by nurse** [comment]
Kanji is used in China, Taiwan, Japan, and Korea. Since Kanji is widely used in those countries more than a thousand years, their glyphs are slightly different. This issue is described like below:

> <img width="631" alt="ScreenShot 2020-04-18 18 09 30" src="https://user-images.githubusercontent.com/13423/79633345-cc901800-819f-11ea-92b4-e71be92e2c80.png">
> https://developers.googleblog.com/2017/04/noto-serif-cjk-is-here.html

**Comment by sorah** [comment]
PR fixed this issue is ongoing at https://github.com/electron/electron/pull/23247
