### ISSUE TITLE
Webview - Fullscreen Embedded Content freezes the entire app

### ISSUE THREAD

**Issue by smithalan92** [electron/electron#18842]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.4
* **Operating System:**
  * macOS 10.13.6
* **Last Known Working Electron version:**
  * 2.0.8

### Expected Behavior
Fullscreening embedded content within a webview should open the content in full screen. Exiting the content should restore/

### Actual Behavior
Fullscreening Embedded content makes the Browser Window go fullscreen, the Embedded content stays the same size and the whole app freezes.

### To Reproduce
**main.js**
```js
const {app, BrowserWindow} = require('electron')
const path = require('path')
const url = require('url')

let window = null

// Wait until the app is ready
app.once('ready', () => {
  // Create a new window
  window = new BrowserWindow({
    // Set the initial width to 500px
    width: 600,
    // Set the initial height to 400px
    height: 600,
    // Don't show the window until it's ready, this prevents any white flickering
    show: false,
    webPreferences: {
      webSecurity: false,
      nodeIntegration: true,
      allowRunningInsecureContent: true,
      webviewTag: true,
    },
  })

  window.loadURL(url.format({
    pathname: path.join(__dirname, 'index.html'),
    protocol: 'file:',
    slashes: true
  }))

  window.once('ready-to-show', () => {
    window.show()
  })
})

```

**index.html**
```html
<!DOCTYPE html>
<html>
  <body>
    Electron Webview Example
    <webview id="foo" src="http://mralansmith.com/misc/electron.html" style="display:inline-flex; width:640px; height:480px"></webview>
  </body>
</html>
```

**webview.html** - Will be loaded remotely using index.html
```html
<!DOCTYPE html>
<html>
  <body>
    <h2>Webview</h2>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/fnlJw9H0xAM" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></iframe>
  </body>
</html>
```

### Screenshots
https://cl.ly/6708fa317fc3

**Comment by MarshallOfSound** [comment]
Relaated https://github.com/electron/electron/pull/18781

**Comment by robertzxz** [comment]
Having same issue on windows with iframe not going all the way fullscreen just moving to top left corner, and the screen stops responding to the clicks, only when I press escape it goes back to normal. Any help?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
