### ISSUE TITLE
Small / mangled / squished font in context menu

### ISSUE THREAD

**Issue by felixrieseberg** [electron/electron#18850]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  * 4.x
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 3.x

### Expected Behavior
Individual items inside the context menu should be clearly readable and take up enough space to display all text.

### Actual Behavior
We have received one (but so far only one) report from a user for whom Slack's context menu looks "too small".

We asked for display and High-DPI details and found nothing but default stuff: It's a 1920 x 1080 display at 100% scaling, no advanced scaling settings have been found.

### To Reproduce
Unclear, just filing in case someone else has similar issues.

### Screenshots
![image](https://user-images.githubusercontent.com/1426799/59636189-c2c50080-9107-11e9-9470-6825691bbe60.png)

**Comment by electron-triage** [comment]
@felixrieseberg is this still happening on electron 6.x.y or later?

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
