### ISSUE TITLE
Add a defocus method to BrowserView

### ISSUE THREAD

**Issue by krausekai** [electron/electron#18859]
When a ``BrowserView`` from a ``BrowserWindow`` is focused, there seems to be no way to re-focus the main ``BrowserWindow``. All input events will continue to be captured by the ``BrowserView``, even when calling ``BrowserWindow.focus()``, and that ``BrowserWindow.isFocused()`` returns true. Additionally, this cannot be side-stepped with keyboard input, as the ``BrowserView.webContents`` event ``before-input-event`` does not seem to have a way to ``preventDefault`` on the ``BrowserView`` either. 

I propose that there should be a way to defocus a focused ``BrowserView`` in a ``BrowserWindow``.

**Comment by MarshallOfSound** [comment]
https://electronjs.org/docs/api/browser-window#winblur

**Comment by krausekai** [comment]
@MarshallOfSound  ``BrowserWindow.blur()`` does not apply to ``BrowserView``, as far as I'm aware?

**Comment by krausekai** [comment]
@MarshallOfSound Sorry to bother again, but I think you misunderstood my proposal.

``BrowserView`` nor ``webContents`` has a ``blur`` property.

**Comment by MarshallOfSound** [comment]
@krausekai Blurring a `webContents` / `BrowserView` doesn't make much sense, what should get focused instead.  If you want to stop focusing X, you should call `focus` on something else

**Comment by krausekai** [comment]
@MarshallOfSound Even when the main ``BrowserWindow`` has focus (confirmed by ``BrowserWindow.isFocused()``), the previously focused ``BrowserView`` does not lose focus, and retains complete key input. An eventListener in ``BrowserWindow`` fails to register key events due to this.

**Comment by krausekai** [comment]
@MarshallOfSound Below is a reproducible example.

Using the Electron quickstart repo:

> git clone https://github.com/electron/electron-quick-start

Edit the quickstart ``main.js`` file to enable ``nodeIntegration``:

```
  // Create the browser window.
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
	  nodeIntegration: true
    }
  })
```

Once started, open the Developer tools, and enter into the console:

```
window.addEventListener('keydown', () => {
	console.log("main window is receiving keydown");
}, true);

var { BrowserView, BrowserWindow } = require('electron').remote;
var view = new BrowserView();
BrowserWindow.getAllWindows()[0].addBrowserView(view); // alternatively: .getFocusedWindow()
view.setBounds({ x: 0, y: 0, width: 480, height: 480 });
view.webContents.loadURL('https://electronjs.org/');

// if the view is focused programmatically or clicked, then the
// main window cannot receive keydown events, even if the
// focused element is an input element, rather than just window
setInterval(() => {
	window.focus();
}, 10);
```

As can be shown, there is no way to programmatically call ``focus`` on another element once ``BrowserView`` has focus.

**Comment by krausekai** [comment]
@sofianguy @codebytere Sorry to disturb you both, but I would like to receive another opinion on this matter. In addition to my main post, my last post contains reproducible steps and reasoning as to why this is a problem that should be addressed within Electron. Thank you.
