### ISSUE TITLE
shell.openExternal not opening browser with query

### ISSUE THREAD

**Issue by TobiahZ** [electron/electron#18851]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
Electron: 3.1.8
* **Operating System:**
OS: Windows_NT x64 10.0.17134

See issue with VSCode here: https://github.com/microsoft/vscode/issues/75356

VSCode maintainers told me this is an electron issue, so raising the same issue here.

I have an extension that lets you search the documentation by opening a web browser with the user's selection as a search query. I would like to add the feature to open from the web or from a local folder.

### Expected Behavior

Using `await vscode.env.openExternal(vscode.Uri.parse(s as string));` works as expected. Which uses electrons https://electronjs.org/docs/api/shell#shellopenexternalurl-options

**However**, it doesn't work as expected when using a local path with a query "C:/Program Files/Folder/search.html?q=SearchForThis"

### Actual Behavior
Nothing happens when using a local path to html file with ?q=SomeQuery at the end.

If I remove the query from the uri string, it will load the web page correctly. However, the point of what I am trying to achieve is to have the search term automatically filled in.

### To Reproduce

From VSCode

```Javascript
	var uri = vscode.Uri.file("C:/Program Files/Folder/search.html?q=SearchForThis" as string);
	// url is confirmed to have a query value of ""
	await vscode.env.openExternal(uri); //Will not load anything/nothing happens.

	var fixed_uri = uri.with({ query: 'q=SearchForThis' }); 
	//fixed_uri has correct query value now
	await vscode.env.openExternal(uri); //Will also not load anything/nothing happens.

	var blank_uri = vscode.Uri.file("C:/Program Files/Folder/search.html" as string);
	await vscode.env.openExternal(blank_uri); //Will load local webpage in browser as expected.

	var query_uri = blank_uri.with({ query: 'q=SearchForThis' }); 
	//query_uri has correct query value now
	await vscode.env.openExternal(query_uri ); //Will load webpage with uri, however "q=SearchForThis" will be missing
```

In VSCode, vscode.env.openExternal maps onto https://electronjs.org/docs/api/shell#shellopenexternalurl-options

@jrieken commented that there is "Little we can do" and that I should forward this issue to electron.

**Comment by MarshallOfSound** [comment]
@TobiahZ This is 100% expected behavior, file paths are not URLs.  Just because some browsers allow you to load files does not mean they are URLs.  For instance `test.html?` is a perfectly valid filename on windows, launching a local file with query parameters thus makes no sense.
