### ISSUE TITLE
repl.start Causes Crash in Renderer

### ISSUE THREAD

**Issue by dsanders11** [electron/electron#18872]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.4
  * 6.0.0-beta.9
* **Operating System:** 
  * macOS 10.14.5
* **Last Known Working Electron version:**
  * 4.1.4
  * 5.0.0-beta.8

### Expected Behavior

`repl.start` should create a new `repl.REPLServer` in the renderer process

### Actual Behavior

A crash happens

### To Reproduce

* Branch with crash: https://github.com/dsanders11/electron-quick-start/tree/repl-renderer-crash
* Branch without crash (v4.1.4): https://github.com/dsanders11/electron-quick-start/tree/repl-renderer-crash-v4

### Additional Information

Does not crash in the main process. I ran through the individual v5 betas and see that the crash began happening with **5.0.0-beta.9**. It does not crash if you test on 5.0.0-beta.8.

Crash stacks are slightly different depending on which version of Electron you run, but all seem to go through `node::inspector::Agent::GetWorkerManager` in one of the frames.

I realize it doesn't make sense to start a `REPLServer` in this manner in the renderer process since it will default to `stdin`/`stdout`, but the crash also happens even if you provide your own stream for `input` and `output`. It's just a more concise reproduce case to let it use the default.

**Comment by codebytere** [comment]
I've narrowed this to `NodeInspectorClient` being null at the time `node::inspector::Agent::Connect` is called, so it dies at `CHECK_NOT_NULL(client_);`.

I highly suspect it's the result of [this Node.js PR](https://github.com/nodejs/node/pull/21182)

**Comment by ak239** [comment]
I believe that I can reproduce similar crash by following steps:
1. clone [`electron-quick-start`](https://github.com/electron/electron-quick-start)
2. enable node integration in Node.js by adding `nodeIntegration: true` in `webPreferences`.
3. add `require('inspector').open(9229, undefined, false)` to `renderer.js`

cc @eugeneo , who is an author of https://github.com/nodejs/node/pull/21182

**Comment by eugeneo** [comment]
This seems to be the result of `node::inspector::StartIoThread` being called without prior call to `node::inspector::Start`. Note that `node::inspector::Start` needs to be called as early as possible so the V8Inspector has more complete data.

**Comment by ak239** [comment]
I am not familiar with `electron` code base (I am going to fetch and build it tomorrow) but by looking on code, it looks like [atom_renderer_client](https://github.com/electron/electron/blob/34c4c8d5088fa183f56baea28809de6f2a427e02/shell/renderer/atom_renderer_client.cc#L97) creates `NodeBindings` but does not do something like `NodeDebugger(bindings->env()).Start()` with bindings' node environment. As @eugeneo mentioned - without this call `client_` is not initialized.

**Comment by dsanders11** [comment]
@ak239, any progress here? Would be nice if a fix could make it in time for 6.0.0.

**Comment by ak239** [comment]
@dsanders11 I built electron last week and confirmed my theory - `NodeDebugger` call is missing but when I am adding it - it fights with `V8Inspector` from blink. I will continue my research this week. What is deadline for 6.0.0?

**Comment by dsanders11** [comment]
@ak239, thanks for the update. I'm not sure about a deadline for 6.0.0, it's currently on beta 11, seems like it's still a couple weeks away. If it's a small fix it could likely be put into a minor release. Don't rush on my account, just thought it would be nice since it's been broken since 5.0.0.

**Comment by bobjunga** [comment]
I was about to create an issue for this too. I am hoping that it gets fixed soon.  I could revive my c/c++ skills to take a look if encouraged to do so.

I would like to add that it is useful to create a repl in the render process. I pass the tty device of the launching terminal to the renderer in a flag and then optionally start the repl with streams to/from that tty. This is very handy when experimenting and debugging.  Its demonstrated in  https://github.com/junga-com/elelectron-inspectorInRenderCrashes

FYI, electron-v4.7.2 that atom uses does not have this problem -- it probably predates that node patch. Its weird that Atom uses such an old electron. Is Arom on life support? Maybe I should have given VSCode a closer look before hitching my wagon to the atom.

--BobG

**Comment by bobjunga** [comment]
I forgot to mention the work-a-round that I am using.

The actual issue is using inspector in a render process so the work-a-round uses repl in a way that avoids it using inspector. 

1) When useGlobal is false (the default) repl.start will synchronously use inspector to create a new context to eval commands that does not have access to the lexical scoped variable so we have to pass useGlobal:true.

2) Next, when useGlobal is true, repl uses inspector in the completer function  to get a list of lexically scoped variable names to complete. repl allows providing your own completer function but I did not want to write all the features from scratch so I let it install its private completer function and then hack in an override after the repl is started.

```
// start the repl
window.repl = require('repl').start({
	prompt: 'winProc> ',
	input:  ttyRead,
	output: ttyWrite,
	useGlobal: true,
	ignoreUndefined: true
});

// work-a-round for electron issue [#18872](https://github.com/electron/electron/issues/18872)
// we dont use the completer: ... function option because we dont want to reimplement the whole thing
let myGlobals = ['global','window','console','electron','mainProcess','mainWindow','consoleWin','consoleMain'];
let builtinCompleter = repl.completer;
repl.completer = (line, callback)=>{
	if (/^[^ .]*$/.test(line))
		callback(null, [myGlobals.filter((word)=>{return word.indexOf(line)==0}), line]);
	else {
		builtinCompleter(line, callback)
	}
};

```

**Comment by codebytere** [comment]
hey all - i finally found some time to poke into this and got a basic working version. @ak239 if you're willing i'd love to hear your thoughts on my stopgap solution and if you think it's the best we can do for now!

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
