### ISSUE TITLE
Unable to find electron app

### ISSUE THREAD

**Issue by Yangfan2016** [electron/electron#18878]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
4.2.4
  * 
* **Operating System:**
macOS 10.14.4 (18E226)
  * 
* **Last Known Working Electron version:**
4.1.3 
 * 

### Expected Behavior
It works

### Actual Behavior
It doesn't work 

### Screenshots

![image](https://user-images.githubusercontent.com/17830872/59776297-28baaf00-92e5-11e9-9c14-b05a741eb3f3.png)
![image](https://user-images.githubusercontent.com/17830872/59776322-31ab8080-92e5-11e9-8521-651990fcc3f3.png)

### Additional Information

package.json

```json
{
 "scripts": {
    "electron-start": "nodemon --watch ./main.js --exec 'electron .'"
 },
 "devDependencies": {
    "electron": "^4.1.3",
    "electron-builder": "^20.40.2",
    "nodemon": "^1.18.10"
 },
 "dependencies":{
   "electron-store": "^3.2.0",
 }
}
```

 main.js

```js
const { app, BrowserWindow } = require('electron')

class AppWindow extends BrowserWindow {
  constructor(config, fileLocation) {
    const basicConfig = {
      width: 800,
      height: 600,
      webPreferences: {
        nodeIntegration: true
      }
    }
    const finalConfig = { ...basicConfig, ...config }
    super(finalConfig)
    this.loadFile(fileLocation)
    this.once('ready-to-show', () => {
      this.show()
    })
  }
}
app.on('ready', () => {
  new AppWindow({}, './public/index.html')
})


```

**Comment by erickzhao** [comment]
Did you try adding your `main.js` as your `main` file in` package.json`?

See documentation here: https://electronjs.org/docs/tutorial/first-app
> npm will guide you through creating a basic package.json file. The script specified by the main field is the startup script of your app, which will run the main process. An example of your package.json might look like this:
> ```
> {
>   "name": "your-app",
>   "version": "0.1.0",
>   "main": "main.js"
> }
> ```

**Comment by codebytere** [comment]
Closing in agreement with the above.

**Comment by Yangfan2016** [comment]
@erickzhao  thx 😄

**Comment by kateric** [comment]
That is fine and good but what if your package.json already has the above "main": "main.js" entry and it still doesn't work?

**Comment by ethauber** [comment]
It's likely that you may have **start** after electron as part of the value for the start key.
```
  "main": "main.js",
  "scripts": {
    "start": "electron start ."
  },
```
should be 
```
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  },
```

**Comment by Adam-UW** [comment]
Can someone help pleaseeee??
![11097627-9B4B-4E17-BEF6-42E719F2F312](https://user-images.githubusercontent.com/29112412/90367243-6ddb8d80-e01d-11ea-850d-f55b8a88c7f8.png)

**Comment by erickzhao** [comment]
Hey @Adam-UW, this is beyond the scope of the issue, but you need to specify a path in your start script (e.g. `electron .`) so that Electron knows where your app resides. You can see a hint for this in the Terminal output included in your screenshot.

See in electron-quick-start: https://github.com/electron/electron-quick-start/blob/e0d251aaffb5b3cedcf3043f880088ea26a0e201/package.json#L6-L8

**Comment by damoncp** [comment]
Please ensure you have
`"main": "main.js",`
in your `package.json` file

**Comment by StupidRepo** [comment]
> Can someone help pleaseeee?? I am not able to run my app, once I say `npm start`
> ![11097627-9B4B-4E17-BEF6-42E719F2F312](https://user-images.githubusercontent.com/29112412/90367243-6ddb8d80-e01d-11ea-850d-f55b8a88c7f8.png)

@Adam-UW 

```
"scripts": {
"start": "electron ."
}
```
Then run `npm start` to run it.
