### ISSUE TITLE
Just wanted to know is code protection available in electron yet and how i would go about using it in electron?

### ISSUE THREAD

**Issue by L2L2L** [electron/electron#18875]
Just wanted to know is code protection available in electron yet and how i would go about using it in electron... On another note, I'm trying to figure out should I use electron or nwjs.. so far what i learnt is that electron have well know products in production; visual studio code, discord, streamlabs obs, whatsapp, skype, twitch, shopify, Github desktop, GroupMe, phonegap, atom, and many more well known desktop app! I mean i was shock to find all of this out... nwjs does not seem to have popular apps.. they have a list page of apps made in nwjs which one had to dig to find since it wasn't on the site and a long list but no apps that stick out to me, unlike electron which caught me by surprise of how many well known app is written with it. the only thing i can think of that nwjs has on it side is secure source code protection and entry point of html plus share context across multiple windows which easy communication between windows... could any of those app had been made with nwjs? I have a app i built on firefox browser which i'm looking to carry over to either electron or nwjs and right now i'm feel nwjs but even know nwjs is older electron has so much already made with it. Which one would be easy for me to carry over my project that ownly work in firefox? which one would easy development? Any comments or suggestions are welcome. 

Thank you for reading.

**Comment by MarshallOfSound** [comment]
Heya @L2L2L , GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
