### ISSUE TITLE
BrowserWindow becomes invisible without any trace or apparent reason

### ISSUE THREAD

**Issue by geraldoramos** [electron/electron#18877]
### Issue Details

* **Electron Version:**
  * v5.0.2
* **Operating System:**
  * MacOS 10.14.5 (18F132)

### Expected Behavior
BrowserWindow to be shown reliably.

### Actual Behavior
My app is a menu-bar app that uses a tray icon and triggers a `browserWindow` instance when clicked. Here is the `browserWindow` setup:

  ```javascript
  mainWindow = new BrowserWindow({
    width: 300,
    height: 450,
    show: true,
    frame: false,
    title: "Nikola",
    fullscreenable: false,
    resizable: false,
    transparent: true,
    titleBarStyle: 'customButtonsOnHover',
    webPreferences: {
      // Prevents renderer process code from not running when window is
      // hidden
      backgroundThrottling: false,
      nodeIntegration: true,
    }
```
The window is positioned using `electron-positioner` package and everything works seamlessly most of the time. After running the app for some time, something makes the window become invisible. When checking the logs, no error is presented and everything seems to be working normally, but the window itself becomes invisible. By removing `titleBarStyle: 'customButtonsOnHover',` I can see that the window is still present (thanks to a small edge caused by the titlebar style, visible on the gif images below). When the problem occurs, I can still right click on it and trigger the context menu (see screenshots section). 

I've been trying to identify the root cause of this for over a week. Any help is appreciated.

### To Reproduce
I can't find a pattern to reproduce the issue, it just happens suddenly and without any apparent reason. I've been able to catch the issue on multiple occasions and received reports from customers. Please check screenshots.

### Screenshots
**This is the expected behavior. Happens most of the time**

![work](https://user-images.githubusercontent.com/5693297/59774851-64b22d80-926d-11e9-8fad-3468fc702816.gif)

**This is the faulty behavior, happens suddenly**

![error](https://user-images.githubusercontent.com/5693297/59774864-68de4b00-926d-11e9-83b9-058708d6ee0e.gif)

### Additional Information
The project is open source and the `main.js` code, and everything else is available [here](https://github.com/geraldoramos/nikola). Any tips or help is greatly appreciated.

Thanks!

**Comment by geraldoramos** [comment]
This was related to an error in the renderer.

**Comment by cathykc** [comment]
What error was it?!

**Comment by ahallicks** [comment]
Same as above and since the same version. My app will randomly 'hide' itself, but it is still there and I can still interact with it. If I use devtools to send a message to the main process to show the window it does show again. This has been plaguing me for ages so any resolution would be really helpful.

It also seems to occur more often when running the app in development. I've only seen it a couple of times in the packaged version, oddly.
