### ISSUE TITLE
I need to save images in jpeg format to the clipboard.

### ISSUE THREAD

**Issue by sanghoTW** [electron/electron#18876]
"electron": "2.0.2",
"electron-builder": "19.31.1",
"electron-prebuilt": "^1.4.13",
"electron-rebuild": "^1.5.11",

Operating System (Platform and Version): [ window10 ]

Expected behavior
[ jpeg type images must be saved to the clipboard.]

Actual behavior
[ An image of type png is saved to the clipboard. ]

---------------------------------------------------------------------------------------------
```
getDataURI(imageUrl){
        return new Promise( (resolve, reject) => {
            request.get(imageUrl, function (error, response, body) {
                const type = response.headers["content-type"];
                const prefix = "data:" + type + ";base64,";
                const base64 = new Buffer(body).toString('base64');
                const dataURI = prefix + base64;

                if (!error && response.statusCode == 200) {
                    resolve(dataURI);
                } else{
                    reject('fileIOMoel getDataURI() request fail');
                }
            });
        });
    }
```

```
copyClipboard(){
        if (!this.isClipboardCopy) {
            this.isClipboardCopy = true;

            const fileName = this.state.selectedAlbumPicture.file_name;
            const fileLastDot = fileName.lastIndexOf('.');
            const fileExtention = fileName.substring(fileLastDot + 1, fileName.length).toLowerCase();
            const imgDataURI = this.fileIOModel.getDataURI(this.state.selectedAlbumPicture.imgUrl);

            imgDataURI.then(dataURI => {
                this.isClipboardCopy = false;
                console.log('AlbumHome.js copyClipboard success : ', dataURI);
                const image = nativeImage.createFromDataURL(dataURI);
                if (fileExtention === 'png' || fileExtention === 'gif') {
                    clipboard.writeImage(image, 'png');
                } else if (fileExtention === 'jpg' || fileExtention === 'jpeg') {


                   [[[[[[[[[ **clipboard.writeImage(image, 'jpeg');**]]]]]]]]


                }
            }).catch(err => {
                this.isClipboardCopy = false;
                console.log('AlbumHome.js copyClipboard err : ', err);
            });
        }
    }
```

clipboard.writeImage (image, 'jpeg'); This is the code that runs normally. 
However, jpeg was copied as a PNG file.

**Comment by sofianguy** [comment]
We are no longer pushing bug fixes to versions older than 2.0.x. Does this occur on later versions of Electron?

**Comment by sanghoTW** [comment]
> We are no longer pushing bug fixes to versions older than 2.0.x. Does this occur on later versions of Electron?

```
  getImageData = () => {
    var options = {
      url: "http://image-cloudfront.moigo.io/79YW4nxqo_S-A3OKe9jds-Klbtk=/x/group/82715512794464/chat/41FBC5635A53.jpg",
      method: "get",
      encoding: null
    };
    return new Promise( (resolve, reject) => {
        request(options, function (error, response, body) {
            if (!error && response.statusCode == 200) {
                resolve(body);
            } else{
                reject('fileIOMoel getImageData() request fail');
            }
        });
    });
  }

  copyClipboard = () => {
          const { clipboard, nativeImage } = electron.remote;
          const imageBase64 = this.getImageData();
          imageBase64.then( base64 => {    
                 const image = nativeImage.createFromBuffer(base64).toJPEG(10);
                 clipboard.writeImage(nativeImage.createFromBuffer(image));
          }).catch( err => {
              console.log(err);
          });
  }
```


The same is true for electron 3.0.

**Comment by miniak** [comment]
@sanghoTW why do you need to write the image to the clipboard in JPEG format?

**Comment by miniak** [comment]
Images are always copied as bitmaps to the clipboard, the type argument of the API does not specify the image format https://github.com/electron/electron/blob/master/docs/api/clipboard.md#clipboardwriteimageimage-type

**Comment by miniak** [comment]
Try https://github.com/electron/electron/blob/master/docs/api/clipboard.md#clipboardwritebufferformat-buffer-type-experimental

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
