### ISSUE TITLE
Can't install electron@5.0.4

### ISSUE THREAD

**Issue by ezetojo** [electron/electron#18893]
### Preflight Checklist
[x] I have read the [Contributing Guidelines]
[x] I agree to follow the [Code of Conduct]
[x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
Electron Version: 5.0.4
Operating System: Win10 Pro (1809) x64
Visual Studio Code: 1.35.1
Node: 10.16.0 (updated now, same on 10.15) / npm 6.9.0

```
> electron@5.0.4 postinstall F:\proyectos\2019\bbt\node_modules\electron
> node install.js


... and 1 more
F:\proyectos\2019\bbt\node_modules\electron\install.js:49
  throw err
  ^

Error: Could not parse checksum file at line 1:
npm WARN bbt@1.0.0 No description
npm WARN bbt@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@5.0.4 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@5.0.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### Expected Behavior
to install

### Actual Behavior
won't install

### To Reproduce
npm i electron
npm i electron --save
npm i electron --save-dev
npm install electron
npm install electron -g

### Additional Information
forced 5.0.3, works like a charm

**Comment by cpboyd** [comment]
I'm having this same issue with 5.0.5

**Comment by pushkin-** [comment]
I believe you're supposed to use node 12.0.0 with Electron 5.x. Try that. That being said, I'm having a bunch of issues with @types when I try building, but probably unrelated to your issue

**Comment by rishabhdeepsingh** [comment]
I have the same issue on Mac OS

**Comment by DeerMichel** [comment]
Do you still have this issue? For me, electron v5.0.4(/5) does install under Windows & Mac with node v10 and node v12. I guess it's the same issue as in #18915.

**Comment by rishabhdeepsingh** [comment]
Yeah, It is resolved I think. Worked fine for me now after uninstalling and re-installing.

**Comment by DeerMichel** [comment]
Aight, otherwise feel free to reopen 👍
