### ISSUE TITLE
why no memory cache

### ISSUE THREAD

**Issue by hxkuc** [electron/electron#18900]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
5.0.0
* **Operating System:**
  * 
Windows 7
* **Last Known Working Electron version:**
  * 
why electron not have memory cache most time
look at this 

in chrome 
![image](https://user-images.githubusercontent.com/17510186/59845428-f9ad4780-938f-11e9-89c9-4e31f85148e4.png)

in electron
![image](https://user-images.githubusercontent.com/17510186/59845459-0b8eea80-9390-11e9-94ce-25660477d4c8.png)

how could i do 

### Expected Behavior

use memory cache
### Actual Behavior

use disk cache

**Comment by codebytere** [comment]
Thanks for reaching out!

We close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by ikreymer** [comment]
I wanted to open a similar issue, but then found this one, which asks the core question (but can open a separate one with more details if that'd be preferred).

It seems the cacheing behavior in Electron is very different from Chrome, and it is unclear if this is a bug or intended behavior.

My use case is as follows:
1) Set up a session for a <webview> with a persistent session configured to run with a proxy server.
2) Add `Cache-Control` headers as needed to induce cacheing.

I've observed the following differences with Electron 6.0:

1) When proxy mode settings are set, the in disk cache is not populated. If a resource is cached without proxy mode, and proxy settings are later set to the same session, the resource will remain cached. 

2) The Blink in-memory cache is never used, neither for persistent or non-persistent sessions.
In Chrome, the in-memory cache is used with or without proxy mode.

Is it possible to have the cacheing work the same as in Chrome, with both in-memory cache and proxy settings support, or is this as designed?

Using a `persist:` or regular session seems to have no affect: only disk cache is ever used and only when not using a proxy server.

Presumably, the `webFrame` apis have access to `blink::WebCache` so the in-memory blink cache is expected to be working?
What about proxy settings and cacheing?
Will the transition to the new Network Service help solve these issues and make Electron work similar, or is this not something that could be fixed.

Any clarifications would be appreciated as I try to figure out what is possible with cacheing and Electron!
