### ISSUE TITLE
Cannot install Electron 5.0.5 from NPM

### ISSUE THREAD

**Issue by popod** [electron/electron#18915]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 5.0.5
* **Operating System:** macOS / Win
* **Last Known Working Electron version:** 5.0.4

### Expected Behavior

Electron 5.0.5 should be push to NPM and should be installed with `npm i electron`

### Actual Behavior

Only Electron 5.0.4 is published to NPM and running `npm i electron` install it

**Comment by codebytere** [comment]
Yep! We're aware of this, we had a hiccup at the npm publish step (it's not as simple as `npm publish` for us given the complex nature of our release process) and we should be able to address and correct this by the end of today.

**Comment by codebytere** [comment]
Build has now been successfully published.

**Comment by popod** [comment]
Nice, thanks ;)
