### ISSUE TITLE
print blurring 

### ISSUE THREAD

**Issue by hinnncom** [electron/electron#18917]
### Issue Details

* **Electron Version:**
  * 3.1.11
* **Operating System:**
  * Windows Server 2012 R2
* **Last Known Working Electron version:**
  * None

### Expected Behavior
webContents.print(option, callback) print  blurring use virtual pdf printer when deviceName have value .
virtual pdf printer have setting option for print Dpi  ,70Dpi  96Dpi 4000Dpi. 
![image](https://user-images.githubusercontent.com/48546169/60571693-aa5f1200-9da6-11e9-8696-286937b49f4c.png)

### Actual Behavior
webContents.print({ silent: true, printBackground:true,deviceName: data.deviceName }

print  blurring when deviceName have value print blurring
![image](https://user-images.githubusercontent.com/48546169/59989222-c9f08f00-9670-11e9-89a6-4f46b487f018.png)

but if deviceName have no value , print is defined

I'm not sure if this is a BUG, and I still want to find a solution. Thank!!!

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by hinnncom** [comment]
@codebytere  I  I know what happened. my print driver  can set dpi . electron silent print  will use the first option 72dpi  replace default settings when   deviceName have value   ,so it is  print blurring , but how solve the problem?

**Comment by codebytere** [comment]
@hinnncom it's not clear what the issue is here; please see https://github.com/electron/electron/issues/18917#issuecomment-504492969

**Comment by hinnncom** [comment]
@codebytere  now the issue is clear?

**Comment by codebytere** [comment]
@hinnncom unfortunately we can't fix this on our end in the existing silent printing infrastructure, but https://github.com/electron/electron/pull/18984 will solve this problem but allowing users to set custom dpi.

**Comment by dominic-simplan** [comment]
Not specifying a dpi explicitly seems to print with the lowest available dpi.
As a workaround, setting a dpi value not supported by the printer (e.g. dpi: {horizontal: 0, vertical: 0}) seems to use the default dpi instead.

**Comment by Chengma999** [comment]
> Not specifying a dpi explicitly seems to print with the lowest available dpi. As a workaround, setting a dpi value not supported by the printer (e.g. dpi: {horizontal: 0, vertical: 0}) seems to use the default dpi instead.

Setting a dpi seem not work for me.  I have a epson receipt printer. This prints clearly. I have alse a POS-80 receipt printer and a Aclas receipt printer. They both support max 203 dpi. But now they print not clearly. Setting dpi doen't work.

**Comment by Chengma999** [comment]
> @hinnncom unfortunately we can't fix this on our end in the existing silent printing infrastructure, but #18984 will solve this problem but allowing users to set custom dpi.

dpi:{vertical:number,horizontal:number} doesn't work well. I have tried with different printers already. This issue need to be reopened.

**Comment by Hedwig188** [comment]
Do we have any plan to address this? We tried the workaround to pass 0 dpi, but not sure if this causes any other side effects.
