### ISSUE TITLE
Add a `BrowserWindows.moveAbove(mediaSourceId)` method

### ISSUE THREAD

**Issue by CapOM** [electron/electron#18922]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
BrowserWindow.{focus,blur,moveTop}() are not enough in some situations. For example when implementing an overlay that follows another window that can lose focus. In that case it is useful to move the overlay above the tracked window.

### Proposed Solution
Implement a new method `BrowserWindows.moveAbove(mediaSourceId)` where mediaSourceId is an id in the format of DesktopCapturerSource's id, see https://electronjs.org/docs/api/structures/desktop-capturer-source#desktopcapturersource-object

### Alternatives Considered
No other alternatives but I considered making a new separate object for mediaSourceId instead of a string but then we would have to change type of DesktopCapturerSource's id. In the end it is just a string so I opted for a string.

### Additional Information
Someone else requested to implement `BrowserWindows.getMediaSourceId()` https://github.com/electron/electron/issues/16460 so this is related in the sense that moveAbove would take a mediaSourceId in parameter whereas  getMediaSourceId would return a mediaSourceId. In any case it seems there are some interest around that.

**Comment by miniak** [comment]
@CapOM please use the checklist (`[ ]` and `[x]`) properly

**Comment by CapOM** [comment]
Sorry can you clarify ? I am sure I am missing something but I do not see it. Thx!
