### ISSUE TITLE
Windows 7 shutdown while Electron app is open causes a breakpoint error

### ISSUE THREAD

**Issue by j-ochs** [electron/electron#18935]
* Electron: 5.0.0
* OS: Windows 7
* Distribution: electron-builder ^20.38.4

### Expected Behavior: 
On Windows 7, if I have a packaged Electron app running and I shutdown the machine, the machine should quit the app and shutdown without error.

### Actual Behavior:
If I have a packaged Electron app running and I shutdown the machine, I see a breakpoint error that prevents the machine from shutting down.

### To Reproduce:
1. On Windows 7, create a packaged Electron build and run it.
2. Go to shutdown the machine as you would normally (click Windows icon -> Shutdown).
3. A Breakpoint Error will pop up which hangs the shutdown of the machine until the user clicks "OK".

This only occurs while running a packaged Electron build, locally running apps quit as expected. Tested with older versions of Electron (v4.2.4 and below) and the issue does not happen, it first appears in v5.0.0. Tested with 5.x.x patch versions and the issue still appears.

![win-7-breakpoint-error](https://user-images.githubusercontent.com/11338019/59952750-2dd94480-9432-11e9-8ebe-5b0634f887ad.png)

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.1.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
