### ISSUE TITLE
'level' param of setAlwaysOnTop is not implemented on Windows

### ISSUE THREAD

**Issue by CapOM** [electron/electron#18933]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
Currently it is not possible to make a BrowserWindow always on top but still behind the task bar on Windows. Whereas It is implemented on MacOS with levels "floating", ... ",
"status" (then "pop-up-menu" and "screen-saver" will make it above the dock)

### Proposed Solution
Win32 api allows to do that, I have a local patch that I will submit next week if interested.
In my patch I re-use the same level names as for MacOS to make it easier for the user.

### Alternatives Considered
Choose different level names on Windows.

**Comment by codebytere** [comment]
@CapOM that'd be awesome and appreciated 🙇‍♀

**Comment by codebytere** [comment]
Closed by https://github.com/electron/electron/pull/18982.
