### ISSUE TITLE
Node_modules version error when using child_process

### ISSUE THREAD

**Issue by manashathparia** [electron/electron#18941]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v5.0.0-beta.9
* **Operating System:**
  * Windows 10 1903
* **Last Known Working Electron version:**
  * none

### Expected Behavior
Use [xxhash](https://www.npmjs.com/package/xxhash) successfully from child_process

### Actual Behavior
Error while executing child_process: 
```
'node_modules\xxhash\build\Release\hash.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 70. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`)
```

### To Reproduce
Run [xxhash](https://www.npmjs.com/package/xxhash) using child_process from electron

### Additional Information

I am using [xxhash](https://www.npmjs.com/package/xxhash) from renderer process successfully but when the child_process is executed it throws node_modules version error.
If I compile the binary using node_modules version 72 (nodejs version 12.4.0), then electron throws error that it requires version 70 then after rebuilding with electron-rebuild i get the child_process error

I also tried the latest electron beta but again it throws error that it requires node_modules version 73 and the latest version of nodejs has version 72

**Comment by MarshallOfSound** [comment]
@manashathparia Sounds like you are spawning `node` as a child process.  You should instead use `process.execPath` and set the environment variable `ELECTRON_RUN_AS_NODE`.  This will spawn your binary but it will run just like nodejs would (no electron apis)

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
