### ISSUE TITLE
Webview crashes with certain libraries

### ISSUE THREAD

**Issue by burningTyger** [electron/electron#18943]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.4, 6 beta 7
* **Operating System:**
  * Current Arch 64
* **Last Known Working Electron version:**
  * 4.2.5

### Expected Behavior
The webview renders whatever is thrown at it.

### Actual Behavior
some libraries crash the webview so that the background of the webview turns grey and on next interaction with it it crashes the whole app. Only a reload of the webview saves the app from crahsing.

### To Reproduce
This is tricky. I really have tried to get a working sample but can't reproduce it since it involves multiple steps. Loading the libraries directly into a webview seems to be ok. However, my app compiles svelte templates inside electron and then renders the created bundle. I'm having difficulties getting the bundle to run on its own.

You can find the bundle here: https://gist.github.com/burningTyger/ac5bf6eca2e7dcd2651ab2f6a03bef4a

The culprit seems to be on line https://gist.github.com/burningTyger/ac5bf6eca2e7dcd2651ab2f6a03bef4a#file-bundle-js-L1334
where I required xlsx-populate.
I had the same issue with some other libraries, e.g. schild and possibly knex.

### Additional Information
Please close the issue if it's lacking information. It might help others to find the issue and add more substantial bug reports though.

**Comment by burningTyger** [comment]
this is #20750 if that helps.

**Comment by burningTyger** [comment]
This issue has been resolved in 8.0.0 Thank you very much to whoever has fixed this. Highly appreciated. Feel free to close the issue.

**Comment by magicdawn** [comment]
temporary fix: copy the buffer

https://nodejs.org/dist/latest-v12.x/docs/api/buffer.html#buffer_static_method_buffer_from_buffer

```
const newbuf = Buffer.from(buf)
```
