### ISSUE TITLE
[5.0.4] Preload.js in  <webview> tag not executed

### ISSUE THREAD

**Issue by nghiepit** [electron/electron#18950]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.4
  * 5.0.5
* **Operating System:**
  * macOS 10.14.5
* **Last Known Working Electron version:**
  * 5.0.3

### Expected Behavior
Anytime `<webview>` tag reload/refresh `preload` executed.

### Actual Behavior
When I updated ` e.target.webview.loadURL('newSrc')` on `new-window` event.
Ever since then `preload` not execute.

### Additional Information
I have using `webpreferences="nativeWindowOpen"`

**Comment by philmenow** [comment]
Can you please root my phone thanks

**Comment by nghiepit** [comment]
The issue has resolved `6.0`.
