### ISSUE TITLE
NaCL deprecated in Electron?

### ISSUE THREAD

**Issue by TRPB** [electron/electron#18954]
I recently discovered this great project: https://github.com/Kagami/mpv.js which allows embedding mpv in Electron and benefiting from the additional codec support and hardware video acceleration on linux which is currently not possible in many cases.

As of Electron 5.0, this plugin no longer loads correctly. It may be an issue with the plugin ( bug report here: https://github.com/Kagami/mpv.js/issues/51 ) but I believe it's because Chromium has deprecated/removed NaCL support: https://developer.chrome.com/native-client/migration

> Given the momentum of cross-browser WebAssembly support, we plan to focus our native code efforts on WebAssembly going forward and plan to remove support for PNaCl in Q2 2019 (except for Chrome Apps). We believe that the vibrant ecosystem around WebAssembly makes it a better fit for new and existing high-performance web apps and that usage of PNaCl is sufficiently low to warrant deprecation.

> We also recently announced the deprecation Q1 2018 of Chrome Apps outside of ChromeOS.

The mpv.js plugin aside, what is Electron's plan going forward? Clearly Chromium is keeping support in the browser as it's used with ChromeOS. Will Electron be compiled with support? At the moment it looks like it's not.

It doesn't look like Electron made a choice to drop support, but Electron stopped supporting it because Chromium stopped enabling support be default.

**Comment by nornagon** [comment]
We don't generally support features that Chromium doesn't support, and NaCl is no exception. NaCl has been deprecated and disused for some time now. I imagine support will be going away even for ChromeOS in the relatively near future.

I recommend exploring WebAssembly if possible for your project.
