### ISSUE TITLE
sent by error BSV to an account of electron cash

### ISSUE THREAD

**Issue by JL258** [electron/electron#18963]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
* **Operating System:**
  * 
* **Last Known Working Electron version:**
  *

**Comment by JL258** [comment]
I sent by error some BSV to electron cash and dont appear in my account, could you please help me? 

Thanks

**Comment by nornagon** [comment]
I think you're confusing us with a cryptocurrency. We're an app development framework.

**Comment by JL258** [comment]
upsss, sorry… and thanks
