### ISSUE TITLE
Window always triggers resize on move

### ISSUE THREAD

**Issue by HaulinOats** [electron/electron#18978]
### Issue Details

* **Electron Version: v3.1.11**
* **Operating System: Windows 10**

### Expected Behavior
Moving window, should not trigger a resize event

### Actual Behavior
Move window triggers resize event

### Additional Information
I have found threads that lead to supposed duplicates but none of them address this issue directly.

Is there any way to allow the window to be moved without triggering the resize event?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

**Comment by HaulinOats** [comment]
https://github.com/HaulinOats/electron-event-overlap

I'm simply outputting the events to the command line console so you can see how moving the BrowserWindow also triggers a resize.

**Comment by erickzhao** [comment]
It seems like the `resize` event is triggered because the Chromium internals actually change the window size by 0 or 1 every time you move the window.

For instance, a 800x600 window might subtly resize to 800x601 or 801x600 during moving. Not sure what the best solution to this would be.

**Comment by pushkin-** [comment]
I am unable to reproduce this using Electron 8.0.0 on Windows 10.

**Comment by lonestarx1** [comment]
@erickzhao Is right, just faced this issue too. A quick workaround I used was to save the window size before performing a move, and then once the window has been moved, force it back to its original size.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by pushkin-** [comment]
Follow the [new issue](https://github.com/electron/electron/issues/28134) for updates
