### ISSUE TITLE
Electron Build size 2.1GB

### ISSUE THREAD

**Issue by hariomdebut** [electron/electron#18970]
Here are the dev dependencies which i am using
"dependencies": {
"@angular/animations": "^6.1.0",
"@angular/common": "^6.1.0",
"@angular/compiler": "^6.1.0",
"@angular/core": "^6.1.10",
"@angular/forms": "^6.1.0",
"@angular/http": "^6.1.0",
"@angular/platform-browser": "^6.1.0",
"@angular/platform-browser-dynamic": "^6.1.0",
"@angular/router": "^6.1.10",
"@ng-bootstrap/ng-bootstrap": "^4.2.1",
"axios": "^0.19.0",
"bootstrap": "^4.3.1",
"core-js": "^2.5.4",
"electron-installer-dmg": "^3.0.0",
"electron-installer-windows": "^1.1.1",
"font-awesome": "^4.7.0",
"i": "^0.3.6",
"jquery": "^3.3.1",
"ngx-spinner": "^7.0.0",
"ngx-toastr": "^10.0.0",
"npm": "^6.9.0",
"popper.js": "^1.14.7",
"rxjs": "6.3.3",
"rxjs-compat": "6.3.3",
"zone.js": "~0.8.26"
},
"devDependencies": {
"@angular-devkit/build-angular": "~0.8.0",
"@angular/cli": "~6.2.3",
"@angular/compiler-cli": "^6.1.0",
"@angular/language-service": "^6.1.0",
"@types/jasmine": "~2.8.8",
"@types/jasminewd2": "~2.0.3",
"@types/jquery": "^3.3.29",
"@types/node": "^8.9.5",
"codelyzer": "~4.3.0",
"electron": "^4.1.3",
"electron-packager": "^13.1.1",
"jasmine-core": "~2.99.1",
"jasmine-spec-reporter": "~4.2.1",
"karma": "~3.0.0",
"karma-chrome-launcher": "~2.2.0",
"karma-coverage-istanbul-reporter": "~2.0.1",
"karma-jasmine": "~1.1.2",
"karma-jasmine-html-reporter": "^0.2.2",
"protractor": "~5.4.0",
"ts-node": "~7.0.0",
"tslint": "~5.11.0",
"typescript": "~2.9.2"
},
here is the main.js
const electron = require('electron');
const { app, Menu, MenuItem } = require('electron');
const { ipcMain } = require('electron');
var path = require('path')
const url = require("url");
const axios = require('axios');
var fs = require('fs');
const BrowserWindow = electron.BrowserWindow
let win;

function createWindow() {
win = new BrowserWindow({
width: 1024,
height: 768,
icon: path.join(__dirname, '/dist/assets/icons/png/64x64.png')
});

win.loadURL(
    url.format({
        pathname: path.join(__dirname, `/dist/index.html`),
        protocol: "file:",
        slashes: true
    })
);

win.on("closed", () => {
    win = null;
});

var template = [{
    label: "Application",
    submenu: [
        { label: "About Application", selector: "orderFrontStandardAboutPanel:" },
        { type: "separator" },
        { label: "Quit", accelerator: "Command+Q", click: function() { app.quit(); } }
    ]
}, {
    label: "Edit",
    submenu: [
        { label: "Undo", accelerator: "CmdOrCtrl+Z", selector: "undo:" },
        { label: "Redo", accelerator: "Shift+CmdOrCtrl+Z", selector: "redo:" },
        { type: "separator" },
        { label: "Cut", accelerator: "CmdOrCtrl+X", selector: "cut:" },
        { label: "Copy", accelerator: "CmdOrCtrl+C", selector: "copy:" },
        { label: "Paste", accelerator: "CmdOrCtrl+V", selector: "paste:" },
        { label: "Select All", accelerator: "CmdOrCtrl+A", selector: "selectAll:" }
    ]
}];

Menu.setApplicationMenu(Menu.buildFromTemplate(template));
const menu = new Menu();
menu.append(new MenuItem({ label: 'Copy', role: 'copy' }));
menu.append(new MenuItem({ type: 'separator' }));
menu.append(new MenuItem({ label: 'Paste', role: 'paste' }));

win.webContents.on('context-menu', function(e, params) {
    menu.popup(win, params.x, params.y);
});
}

app.on("ready", createWindow);
app.on("window-all-closed", () => {
if (process.platform !== "darwin") {
app.quit();
}
});
app.on("activate", () => {
if (win === null) {
createWindow();
}
});

ipcMain.on('getFiles', async(event, arg) => {
const filepath = '/var/www/html/filepath.dat';
if (fs.existsSync(filepath)) {
const fileData = fs.readFileSync(filepath);
win.webContents.send("getFilesResponse", JSON.parse(fileData.toString()));
} else {
try {
const address = await makeaddress(37, 'random');
const user = await makeaddress(5, 'user');
const response = await axios.post('http://localhost:3000/users/create-user', {
address: address,
user: user
});

        fs.writeFile(filepath, JSON.stringify(response.data.data), (err) => {
            if (err) {
                console.log("An error ocurred creating the file " + err.message);
                return false;
            }
        });
        win.webContents.send("getFilesResponse", response.data.data);
    } catch (err) {}

}
});

function makeaddress(length, type = 'random') {
let result = '';
const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
const charactersLength = characters.length;
for (let i = 0; i < length; i++) {
result += characters.charAt(Math.floor(Math.random() * charactersLength));
}
if (type === 'user') {
return result;
}
return 'A' + result;
}
I am building a simple app using elctron. Please help, what is wrong with this configuration.

**Comment by DeerMichel** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. In this particular case, a minimal working repo would be helpful.

Thanks for understanding and meeting us half way 😀.

**Comment by ngudbhav** [comment]
I also encountered this issue while using electron-builder. If you are building multiple times or multiple outputs, make sure you get the release build out of the project folder. Sometimes, the build is also put into the archive.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our [comment](https://github.com/electron/electron/issues/18970#issuecomment-505654124). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
