### ISSUE TITLE
Player is not playing video inside Microsoft teams application

### ISSUE THREAD

**Issue by alon1980** [electron/electron#18973]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 3.1.8
* **Operating System:**
  * macOS 10.14.4 (18E226)
* **Last Known Working Electron version:**
  * None

### Expected Behavior
After recording a video clip with our video recorder inside of Microsoft Teams application, when trying to play the video the video is playing correctly.

### Actual Behavior
When launching our video player in order to play a recorded video the player crashes with an error message "Something went wrong" with a session ID.

### Additional Information
this is a copy of the media internals failing player:
render_id: 9
player_id: 8
origin_url: https://teams.qakmstest.dev.kaltura.com/
frame_url: https://teams.qakmstest.dev.kaltura.com/recorder/index/record
frame_title: IbeenthereCorp
url: blob:https://teams.qakmstest.dev.kaltura.com/34e0a9df-f54b-45af-8307-8048e7621489
total_bytes: 248586
streaming: false
single_origin: true
passed_cors_access_check: false
range_header_supported: true
pipeline_state: kStopped
info: Selected FFmpegAudioDecoder for audio decoding, config: codec: opus bytes_per_channel: 2 channel_layout: 2 channels: 1 samples_per_second: 48000 sample_format: 2 bytes_per_frame: 2 seek_preroll: 0ms codec_delay: 0 has extra data? true encrypted? false discard decoder delay? true
audio_channels_count: 1
audio_codec_name: opus
audio_sample_format: Signed 16-bit
audio_samples_per_second: 48000
bitrate: 0
found_audio_stream: true
found_video_stream: true
height: 540
max_duration: kInfiniteDuration
start_time: 0
time_base: 1/1000
video_codec_name: vp9
video_format: PIXEL_FORMAT_I420A
video_is_encrypted: false
width: 960
audio_dds: false
audio_decoder: FFmpegAudioDecoder
error: video decoder initialization failed
pipeline_error: DECODER_ERROR_NOT_SUPPORTED
duration: unknown

**Comment by MarshallOfSound** [comment]
This is not an Electron issue, it sounds like you are experiencing an issue with Microsoft Teams.  If this is an Electron issue please provide a minimal repro based off of `electron-quick-start` rather than an existing Electron app.

**Comment by miniak** [comment]
@alon1980 Teams uses a build of ffmpeg, which has VP8/9 codecs disabled.
