### ISSUE TITLE
Backport fix for access violation

### ISSUE THREAD

**Issue by TanninOne** [electron/electron#18988]
Could this patch please be backported to electron 4:
https://github.com/electron/electron/commit/b97d7e7ecd6ed403cea700ab4aab0d0d20624f7f
?

It's a pretty simple fix that should apply without problem to the v4 branch.

**Comment by codebytere** [comment]
@TanninOne done, when it's merged it'll go out with the next patch release.

**Comment by MarshallOfSound** [comment]
Fixed in #18992
