### ISSUE TITLE
Better callback value for webContents.print()

### ISSUE THREAD

**Issue by popod** [electron/electron#18980]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 5.0.5
* **Operating System:** macOS Mojave 10.14.5 / Windows too ?
* **Last Known Working Electron version:** not known

### Expected Behavior

When using `webContents.print()`, if the user click the **cancel button** on the print dialog (or on the **"PDF" button**) this should: return a callback value of "false" (error) or "true" (success), but with more details that only "true" or "false". Something like an error/success message that tell that the cancel button has been clicked..

This could be:

- `success` when the document is sent to the printer
- `cancelled` when the cancel button is clicked
- `pdf` / `other-action`? when the PDF button is clicked
- `failed` when an error occurs

### Actual Behavior

In my application, I only want to display a success notification to the user when the print process is successfully launched and an error message when they is an error. For now, false-positive notifications are display when :

- the cancel button is clicked on the print dialog (return is `false`), we do not know if it is an `error` or a `cancel` event and when an error occurs (return is `false` too), we do not know if it is an `error` or a `cancel` event.
- the "PDF" button (only on macOS?) is clicked (return is `true`) and we would know if this is a print `success` or something else to display a "successfully print" notification to the user.

Not tested, but Windows should have the same problem !

---

Perhaps linked with #15568 but more specific ?
@codebytere perhaps something that is linked with #17400

**Comment by codebytere** [comment]
@popod what are you testing this with? If I run the original repro you sent in, i see `false` in the console for manual cancellation, like i expect.

However, i think we should potentially be able to callback a string of either `failed`, `success` or `cancelled` depending on the outcome of the print; i'll add that to my backlog.

**Comment by popod** [comment]
@codebytere I do not provide any repo for this issue.. I think you use the repo for the bug where the callback only return `false` (#17265) which use electron `4.x.x` and this is why you get a `false` value. If you want to use this repo, you should update the electron version to `5.0.5`.

> However, i think we should potentially be able to callback a string of either `failed`, `success` or `cancelled` depending on the outcome of the print; i'll add that to my backlog.

Yes, this would be very useful !

**Comment by codebytere** [comment]
That's what i was referencing: it correctly prints `success` as `false` in that repro when i cancel it while running master.

**Comment by popod** [comment]
Aie, sorry my bad ! I've update the issue description with your proposition. I think that return "customs" callback value as string will resolve the issue.

**Comment by codebytere** [comment]
@popod PR is up 🚀
