### ISSUE TITLE
Type for DesktopCapturer's `getSources` Promise version incorrect

### ISSUE THREAD

**Issue by embiem** [electron/electron#18983]
### Issue Details

* **Electron Version:** 5.0.5

### Expected Behavior
Calling `Electron.DesktopCapturer.getSources()` with it's Promise variant should return an array of `Electron.DesktopCapturerSource`.

### Actual Behavior
Types are setup to return a single `Electron.DesktopCapturerSource`, even though the implementation correctly returns an array.

### To Reproduce
Using Typescript setup, write:

```
const { desktopCapturer } = require("electron");

const sources = await desktopCapturer.getSources({
	types: ["screen"]
});

const chosenSource = sources[0];
```

TS will detect this error at the last line: "Element implicitly has an 'any' type because expression of type '0' can't be used to index type 'DesktopCapturerSource'.
  Property '0' does not exist on type 'DesktopCapturerSource'."

### Additional Information

I'd fix it myself, but after a quick look at the source code can't figure out how the types are created. They seem to be auto generated somehow and not manually defined in the code base.

**Comment by codebytere** [comment]
cc @MarshallOfSound i think this is an inner type parsing issue 🤔 

Looks correct here `Returns `Promise<DesktopCapturerSource[]>` so the parser must be clobbering it

**Comment by MarshallOfSound** [comment]
```
getSources(options: SourcesOptions): Promise<Electron.DesktopCapturerSource[]>;
```

This is fixed with the new docs parser, unfortunately, this was a massive rewrite and not something we can look to backport at this time.  It's fixed in the currently nightly FWIW.
