### ISSUE TITLE
Minimal HTML Reader using C++ to support electron with/like a preloader

### ISSUE THREAD

**Issue by ngudbhav** [electron/electron#18996]
### Preflight Checklist

* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Electron app takes good time to start probably because of chromium. On a low-end PC's viz., i3 or below, time can be considerably high. 

### Proposed Solution

A bare minimal headless HTML Reader on C++ which will render preloader code and automatically close as soon as the app is loaded. A progress event may be exposed which will help create interactive loaders. As soon as the app is launched (via shortcut or exe), the preloader comes up, plays some animation for a second or two and as soon as the BrowserWindow is loaded, the loader will close, thereby providing a good experience for user

### Additional Information

https://github.com/ultralight-ux/ultralight

Libraries like these may help achieve this objective.

**Comment by MarshallOfSound** [comment]
This is something that has been discussed before and is not something we feel is appropriate for Electron Core.
