### ISSUE TITLE
window.open always return null, if node integration is off and nativeWindowOpen is false

### ISSUE THREAD

**Issue by DerivcoHK** [electron/electron#19003]
as Title

**Comment by MarshallOfSound** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.
