### ISSUE TITLE
Using dialog.showOpenDialog with property `promptToCreate` results in two modals asking for file creation, when file is not existing.

### ISSUE THREAD

**Issue by ghanashyam-c-k** [electron/electron#19001]
### Preflight Checklist

* [ x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.2.0
* **Angular Version:**
  * 7.2.0
* **Operating System:**
  * Win10 Enterprise
* **Node Version:**
  * 10.15.3
### Expected Behavior
Expects a modal asking for file creation when clicking the open button when required file is not present to be selected

### Actual Behavior
The modal window prompting to create the file comes twice

### Screenshots
![modal](https://user-images.githubusercontent.com/50394182/60243983-189f6280-98d7-11e9-8c64-95d5f78f8195.png)
![results](https://user-images.githubusercontent.com/50394182/60244091-4e444b80-98d7-11e9-8823-b45de20f20e1.png)

**Comment by MarshallOfSound** [comment]
I can not reproduce this on Windows 10, we hand this off entirely to the OS with [`FOS_CREATEPROMPT`](https://docs.microsoft.com/en-us/windows/desktop/api/shobjidl_core/ne-shobjidl_core-_fileopendialogoptions).  My guess is you've found a Windows bug 🤷‍♂ 

Closing out as not an Electron issue based on the above, if it happens consistently I'd suggest reporting to WIndows Feedback 👍

**Comment by ghanashyam-c-k** [comment]
I have created a simple application here: [https://github.com/ghanashyam-c-k/RnD-job/tree/dev/sampleApp](url)

Can you verify its not a coding mistake??
