### ISSUE TITLE
官方文档有点卡

### ISSUE THREAD

**Issue by xiaowang1314** [electron/electron#19002]
https://electronjs.org/docs/tutorial/development-environment#setting-up-macos

**Comment by malept** [comment]
> 官方文档有点卡 [machine translated: the official documentation is a bit {hard?}]

Can you explain what you're having difficulty with regarding the section of the tutorial that you linked? It will make it easier to figure out what could be changed.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
