### ISSUE TITLE
http post requests and google fonts crash app when packaged for windows

### ISSUE THREAD

**Issue by dottodot** [electron/electron#19007]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.6
* **Operating System:**
  * macOS 10.14.5
* **Last Known Working Electron version:**
  * n/a

### Expected Behavior

App to load without crashing
### Actual Behavior

Firstly I don't have the issue when I package for osx and I have tried electron-packager and electron-builder and get the same result.

If I add google fonts to my index file i.e
```
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
```
and use those fonts anywhere in my app it crashes straight away with a blank white screen.

Also if I make a http POST request the same thing happens so I assume it's related, http GET works OK

### To Reproduce

https://github.com/dottodot/electron-test
```sh
$ git clone https://github.com/dottodot/electron-test
$ npm install
$ npm run package:win
```
then open on windows and you'll see it crashes straight away.
then in `src/index.html' remove then following
```
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
```
then re-package and it will work.

Similarly the see the http requests issue these can be uncommented in `src/app/app.component.ts`

**Comment by dottodot** [comment]
Any suggestions as to how I can get this fixed, trying to finish a project but completely stuck on this issue.

**Comment by MarshallOfSound** [comment]
This appears to be resolved in v7 and higher
