### ISSUE TITLE
Wrong behavior after canceling the printer dialog box

### ISSUE THREAD

**Issue by brunto** [electron/electron#19008]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.6
* **Operating System:**
  * macOS 10.14.5
* **Last Known Working Electron version:**
  * 4.2.5

### Expected Behavior
When I click on a **button** who uses the `print()` method
The print dialog opens
Then I click on "Cancel" button
I must be able to go to another page by clicking on a link

### Actual Behavior
When I click on a **button** who uses the `print()` method
The print dialog opens
Then I click on "Cancel" button
I can not click on another link, I have to quit the application and open it again

### To Reproduce
You can download the PIA 2.1.0 version at this URL https://github.com/LINCnil/pia-app/releases/tag/2.1.0 then:
* Create a new PIA
* Click on the **Preview** icon
* Click on the **Printer** icon (Wait for the printer dialog box)
* Click on the **Cancel** button
* Try to go on another page of the application

**Comment by fxha** [comment]
@codebytere FYI, this issue also affect the button click event and links (`href="javascript:foo();"`). I also noticed that URLs which were opened in the default browser are loaded by Electron after cancelling the print dialog ([details](https://github.com/electron/electron/issues/16085#issuecomment-506869309)).

**Comment by popod** [comment]
I think I've had something similar (only on Windows) by using `window.confirm()`. In this case, using [`dialog.showMessageBox()`](https://electronjs.org/docs/api/dialog#dialogshowmessageboxbrowserwindow-options-callback) will get around this problem.

**Comment by fxha** [comment]
> Have you the same problem if you replace the print dialog by a `window.confirm()` ?

No, I haven't.

**Comment by zadam** [comment]
@popod I have very similar issue - after calling confirm() I can't set focus to the text input - specifically the cursor does not appear after clicking the input, I can't write into input, but backspace will remove characters (which is pretty weird).

Opening dev tools fixes the problem, also switching to another window and then back fixes the problem as well.

This happens only on windows (linux works fine, I did not test mac). I'm using latest 6.0.0-beta.11

**Comment by 314r** [comment]
Hi,

Same problem here.

- **Electron Version** : 6.0.2
- **OS** : Windows 10, MacOS (Linux not tested)

**Comment by lmparppei** [comment]
Same problem, but opening / closing dev tools or switching to another window does not help either. Print callback works, everything typed into the console works, but no buttons or text fields respond anymore. I am calling the webContents.print() through remote.

- Electron version: 6.0.1
- OS: MacOS 10.14.6

**Comment by brunto** [comment]
@popod For me it works with the version 5.0.4 but not with versions upper.

**Comment by welintonhaas** [comment]
I solved the issue by upgrading to version 7.0 beta

**Comment by JonathasNascimento** [comment]
Still happens with v6.0.12 on Windows 10

**Comment by bjbk** [comment]
Issue still happens v6.0.12 macOS as well

**Comment by JonathasNascimento** [comment]
I upgrade to version v7.0.0 and it is now working

**Comment by codebytere** [comment]
Fixed more efficiently in https://github.com/electron/electron/pull/21026
