### ISSUE TITLE
Content of app isn't loaded: "Uncaught Error: Cannot convert name to ASCII"

### ISSUE THREAD

**Issue by cumajkeee** [electron/electron#19005]
### Issue Details

* **Electron Version:**
  * 5.0.2
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 4.0.8

### Expected Behavior
App works correctly

### Actual Behavior
Renderer failed, main process works

### To Reproduce
End-user case, reproduced only locally.

### Additional Information
App renderer process is failed and didn't rendered anything, when open devtools it's gone is same second and didn't open until I restart app.
When launch app with the --enable-logging, I got following error:

[5304:0627/095437.564:INFO:CONSOLE(222)] "Uncaught Error: Cannot convert name to ASCII", source: C:\Users\User\AppData\Local\Programs\App\resources\electron.asar\renderer\api\remote.js (222)

**Comment by MarshallOfSound** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by cumajkeee** [comment]
@MarshallOfSound as I said before, one specific PC with error. Sample will not help to reproduce the issue. But it doesn't mean that nobody else will caught same and I would really appreciate if electron team will take a look.

**Comment by MarshallOfSound** [comment]
@cumajkeee If we can't reproduce it we can't look into it.  If it's truly un-reproducable then there's not much we can do here

**Comment by cumajkeee** [comment]
@MarshallOfSound, even error name can't help to point somewhere?

**Comment by MarshallOfSound** [comment]
@cumajkeee I'm not a search engine nor a support team, all I'm going to do is drop the error message into google, if you search for that error it will tell you exactly where it comes from

* https://github.com/request/request/issues/2422
* https://github.com/nodejs/node-gyp/issues/1199
* https://github.com/nodejs/node/issues/13043
* https://github.com/unicode-org/full-icu-npm/issues/8

This error is not coming from Electron, it's coming from giving an invalid thing to `url.parse`
