### ISSUE TITLE
nativeImage.createFromURL(url)

### ISSUE THREAD

**Issue by whitecrownclown** [electron/electron#19031]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

I would like to be able to implement a `Copy Image` feature in my app.

Right now, i cannot do this without first downloading the image and doing 
`nativeImage.createFromBuffer(buffer)` or doing `nativeImage.createFromPath(path)` if the image is on the filesystem. Ideally this would also work with the file protocol.

Adding support for `webp` would be great since right now you'd have to convert the downloaded image into a format supported by `nativeImage` in order to copy it to the clipboard.

### Proposed Solution

Add a new `nativeImage` method, `nativeImage.createFromURL(url)` that downloads the image from the provided url and returns a `NativeImage`.

### Alternatives Considered

None.

### Additional Information

This can be done in app code, however having it in electron would greatly simplify this process.
More details: https://github.com/sindresorhus/electron-context-menu/pull/79

Thank you!

**Comment by MarshallOfSound** [comment]
For context menus you definitely don't need to download the image and create a nativeImage.

Just use https://electronjs.org/docs/api/web-contents#contentscopyimageatx-y to copy the image where the context menu was triggered

**Comment by xadamxk** [comment]
Running into a scenario where I could use this.
Instead I have to download an image, convert to buffer, and load the native image that way...

**Comment by redspider926** [comment]
MarshallOfSound, I am interested in your suggestion.
Can I use the webcontent for touchbar button icon?
