### ISSUE TITLE
Electron and Travis CI (chrome-error://chromewebdata/)

### ISSUE THREAD

**Issue by rgetValue** [electron/electron#19034]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.5
* **Operating System:**
  * Window 10 / Xubuntu / MacOS Mojave

### Expected Behavior
When i try to build app (using electron-builder) on my Windows PC (or Linux/MacOS Virtual Machine) – all works like expected.

### Actual Behavior
When i use Travis CI to build my app, every time i get blank page (chrome-error://chromewebdata/).

### Screenshots
![error](https://user-images.githubusercontent.com/5750897/60359630-402f2180-99e2-11e9-838c-39a0959e1825.png)

### Additional Information
I think, problem is with loading `index.html` file into app.
Electron.js file:
```
mainWindow.loadURL(url.format({ pathname: path.join(__dirname, "/frontend/index.html"), protocol: "file:", slashes: true }));
```
I try to build my app with `asar: false` option - same issue.
I try to load internet page (https://github.com/) - all works fine (like expected).

**Comment by codebytere** [comment]
This is not demonstrably an issue with Electron - it seems to be an issue with Travis.

I would recommend you perhaps try to use `mainWindow.loadFile('index.html')` instead.
