### ISSUE TITLE
How to send sync message from IpcMain to IpcRenderer

### ISSUE THREAD

**Issue by TongDaDa** [electron/electron#19049]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 

Latest

* **Operating System:**
  * 

macOS 10.13.6 

* **Last Known Working Electron version:**
  * 

### Expected Behavior

I want an asynchronous way to send messages from IpcMain to IpcRenderer, just one-way communication.

### Actual Behavior

After I have referred the document of electron and any issue of `StackOverflow`.  It looks like to communicate `rendererProcess` only way is to use `send` function to send messages to it. But the send function is asynchronous form, however, I need the order of invoking.

So I need a kind of `ipcMain.sendSync` function. what do you think?

**Comment by Zarma13** [comment]
Hello @TongDaDa, how did you solved your problem ?
