### ISSUE TITLE
openItem doesn't open apps with parameters

### ISSUE THREAD

**Issue by icaspi** [electron/electron#19047]
### Issue Details

* **Electron Version:**
 v5.0.6
* **Operating System:**
OSX Mojave 10.14.5

### Expected Behavior
When calling `(shell.openItem("/usr/bin/open -na unity")` The unity app should be loaded (I picked unity as a general case)

### Actual Behavior
The app isn't loaded and `openItem` return false

I could be wrong but it could the spaces that are the source of the issue.

**Comment by codebytere** [comment]
@icaspi this is expected behavior per [documentation](https://github.com/electron/electron/blob/1a6a16e3469af88712f8e6514ca133b296345024/docs/api/shell.md#L27). The `fullPath` argument is intended only to provide a path and then the function will

> Open the given file in the desktop's default manner.
