### ISSUE TITLE
Add an option to choose the paper format (size) on webContents.print()

### ISSUE THREAD

**Issue by popod** [electron/electron#19056]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

They is no way to choose the paper format (A4, A3, Letter, ...) when printing with `webContents.print()`.

### Proposed Solution

Add something like the `pageSize` option which is available in [`webContents.printToPDF()`](https://electronjs.org/docs/api/web-contents#contentsprinttopdfoptions-callback).

**Comment by tomnielsen** [comment]
A possible workaround is to create multiple "virtual" print devices on the machine, each with different setting having unique names (like `foobar_a4`, `foobar_letter`). Then (when it's working), use a different the printer device name when printing.

Can't test this right now because https://github.com/electron/electron/issues/17260

**Comment by zlab** [comment]
sales goods label cards has many page sizes, such as 50mm*40mm, 80mm* 50mm...

**Comment by zlab** [comment]
@codebytere 
## why contents.print() dont has pageSize option?
```
contents.printToPDF(options)
pageSize String | Size (optional) - Specify page size of the generated PDF. 
Can be A3, A4, A5, Legal, Letter, Tabloid or an Object containing height and width in microns.
```

**Comment by codebytere** [comment]
@zlab `printToPDF` and `print` are completely different functions with different underlying implementations, so this would not be as simple as porting over the existing code from `printToPDF`. That said, i'm still happy to consider this and may do so in the future.

**Comment by codebytere** [comment]
@zlab I found some time for this - hopefully should be added in the next version of Electron.
