### ISSUE TITLE
To send sync messages from mainProcess to renderer process

### ISSUE THREAD

**Issue by TongDaDa** [electron/electron#19051]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 

Latest

* **Operating System:**
  * 

macOS 10.13.6 

* **Last Known Working Electron version:**
  * 

### Expected Behavior

I want an asynchronous way to send messages from IpcMain to IpcRenderer, just one-way communication.

After I have referred the document of electron and any issue of `StackOverflow`.  It looks like to communicate `rendererProcess` only way is to use `send` function to send messages to it. But the send function is asynchronous form, however, I need the order of invoking.

So it needs a kind of `ipcMain.sendSync` function. what do you think?

**Comment by nornagon** [comment]
Blocking the browser process is disallowed. The browser process is responsible for performing many tasks on behalf of all renderers, and if it were blocked then all renderers would block. You should architect your app to use asynchronous communication instead.
