### ISSUE TITLE
Please update the readme example to something that has the expected behavior on every os.

### ISSUE THREAD

**Issue by aranmohyeddin** [electron/electron#19050]
The first line in the Readme is a sample usage. One that only works as expected in OS X. One needs to go down a couple of paragraphs to realize that it's not supposed to work on their system, which in my case is on Archlinux. Please have some empathy for most of the population of the world who happen to not use a macbook like you guys. If you don't, at least move the warning up there so people can see it while trying out the example!

**Comment by MarshallOfSound** [comment]
@aranmohyeddin Which specific part of the README are you referring to --> https://github.com/electron/electron/blob/master/README.md

I did a quick scan and every bit of sample code or suggested command isn't specific to any OS?

**Comment by aranmohyeddin** [comment]
@Marshall I'm so sorry:)) 
https://github.com/electron/electron/blob/master/docs/api/dialog.md
I just knew I was seeing a markdown I thought it was the readme:)) I clicked on issues and posted this didn't notice it wasn't the actual readme of the repo.

**Comment by MarshallOfSound** [comment]
@aranmohyeddin I've double checked the first example in that readme.  It doesn't include any platform specific logic or code.  All options used are cross-platform.

Without more specifics on what exactly doesn't work or is macOS specific I'm going to close this out.  If I missed something please @ mention me in a follow up below

**Comment by aranmohyeddin** [comment]
A couple of lines below you can see:

> Note: On Windows and Linux an open dialog can not be both a file selector and a directory selector, so if you set properties to ['openFile', 'openDirectory'] on these platforms, a directory selector will be shown.

I'm on Linux and I was using the first example and was unable to select files and it was so frustrating I wasted some time searching to no avail finally I came back to the readme and read on to see the warning.

**Comment by MarshallOfSound** [comment]
Fixed in #19055

**Comment by aranmohyeddin** [comment]
What about https://electronjs.org/docs/api/dialog#dialog?
