### ISSUE TITLE
Unknown cipher : MineflayerJS

### ISSUE THREAD

**Issue by 360noscope** [electron/electron#19053]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  5.0.6
* **Operating System:**
  Windows 10 x64 V1903
* **Last Known Working Electron version:**
  ~None~ => **Electron 3.1.11** (Just testing with help from PrismarineJS's dev)

### Expected Behavior
I using mineflayer to running some bot management and according to mineflayer team they said
the need cipher  ~aes-128-cfb~ -> **aes-128-cfb8** to let authentication working and i already see aes-128-cfb listed in 
getCiphers() 

### Actual Behavior
Unknown cipher error thrown out

### More Investigation

when i run `getCiphers()` comparing from two locations this is result
from electron
https://imgur.com/GECe8CF

from node
https://imgur.com/GodfLIA

**Comment by nornagon** [comment]
Hi there, thanks for the report. Electron does support aes-128-cfb, as you discovered. I'm not sure why your app is throwing an error and without a clear repro we can't debug further.

If you can figure out what cipher name the app is attempting to use then perhaps we can get some more info.

**Comment by 360noscope** [comment]
my bad its **aes-128-cfb8** cipher

**Comment by codebytere** [comment]
While it would be possible for us to patch this, BoringSSL has stated that since it's a relatively obscure cipher they are unwilling to expose it for binary size considerations. As such, at this time this is not in our best interest to maintain against their wishes. Should something change, i'll be sure to let you know.

**Comment by GisliNielsen** [comment]
I would love `aes-128-cfb8` to be added to electron. It's supported in nodeJS and should also be supported in Electron. This cipher is used for Minecraft servers and would allow us to make better applications

**Comment by 1by** [comment]
Are there any updates on this? this being added would help a lot of us out.

**Comment by nornagon** [comment]
Would something like https://www.npmjs.com/package/aes-js work for you?

**Comment by rom1504** [comment]
fyi we indeed did end up using aes js https://github.com/PrismarineJS/node-minecraft-protocol/pull/750
