### ISSUE TITLE
BrowserWindow.setWindowButtonVisibility() crashes on Windows/Linux

### ISSUE THREAD

**Issue by bpasero** [electron/electron#19052]
**Electron version:** 4.x

This method does not seem to exist on Windows/Linux: `BrowserWindow.setWindowButtonVisibility()`

Result:
![image](https://user-images.githubusercontent.com/900690/60395230-d8d3b780-9b30-11e9-85c9-ffee1b6befa0.png)

**Comment by MarshallOfSound** [comment]
According to our docs the method is macOS only.  Although unusual for us not to provide a noop shim in this case at least the documentation is there.

**Comment by codebytere** [comment]
Closing in agreement with the above; it's documented as a macOS only method and only exposed to that OS.
