### ISSUE TITLE
Can't fork child inside ASAR with portable

### ISSUE THREAD

**Issue by Cefold** [electron/electron#19067]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.2.4
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 

### Expected Behavior

JS file inside ASAR could be forked.
### Actual Behavior

Everything works with the app under win-unpacked folder, but portable app won't fork the child.
### To Reproduce

I know that `asar` is kind of different, so I used this, and it worked under `win-unpacked` folder, but with portable app, it won't work.
```
    const cp_path = 'app.asar/server/server.js';
    const rootFolder = path.join(__dirname, '..');
    child = fork( cp_path,[], {  cwd: rootFolder  } );
```
I tried
```
   const childPath = path.join(__dirname, '../app.asar/server/server.js');
   child = fork( childPath,[],  { } );
```
The result stays the same.

### Additional Information

With unpacked and portable app:
`fs.existsSync(path.join(rootFolder, 'app.asar/server/server.js')` will both return true, and 
` fs.existsSync(path.join(__dirname, '../app.asar/server/server.js'))` will both return true

**Comment by addlistener** [comment]
@Cefold Have you made it work?
