### ISSUE TITLE
New “inspector” folder in Electron 5 package that doesn't do anything?

### ISSUE THREAD

**Issue by aabuhijleh** [electron/electron#19075]
* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

* **Electron Package Version:**
  5.0.6 for 32-bit Windows
* **Operating System:**
  Windows 10
* **Last Known Electron Package Version Without This Folder:**
  4.2.5

After updating Electron from **v4** to **v5** I found a new **~9MB** folder `inspector` containing **188 files**  in the Electron package install path at **`node_modules/electron/dist/resources/inspector`** or **`${packagedApp}/resources/inspector`** after packaging with `electron-builder`. What is this for?

There seems to be no consequences for deleting this folder. I can still use Electron and chrome devtools perfectly fine after removing it.

**Can it be safely deleted/excluded from my packaged app?**

Any help is appreciated!

**Comment by sofianguy** [comment]
fixed https://github.com/electron/electron/pull/19193
