### ISSUE TITLE
Color set using setBackgroundColor ignored when loading file or URL

### ISSUE THREAD

**Issue by sylveon** [electron/electron#19091]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.6
* **Operating System:**
  * Windows 10 1903

### Expected Behavior
The page is loaded with the background color specified by the last call to setBackgroundColor.

### Actual Behavior
The page is loaded with the background color specified by the color set in the initial creation options. If no page is loaded, the color from the last call to setBackgroundColor is correctly displayed.

### To Reproduce
https://github.com/electron/electron-quick-start/compare/master...sylveon:master

### Screenshots
![image](https://user-images.githubusercontent.com/6440374/60552536-39afeb00-9cfd-11e9-8e7a-036b57fbd4b0.png)

**Comment by kiavashp** [comment]
Also seeing this exact behavior in v7.1.x

**Comment by mikeyyyzhao** [comment]
I'm still seeing this issue in 9.1.1

**Comment by codebytere** [comment]
This is expected behavior of calling `mainWindow.setBackgroundColor('#00FF00')` _after_ calling ` mainWindow.loadFile('index.html')`. The background color of the webcontents takes precedence. If you just call `mainWindow.setBackgroundColor('#00FF00')` before calling `loadFile` it will work as intended.

**Comment by sylveon** [comment]
@codebytere Except in my repro I call setBackgroundColor **before** doing loadFile and it *didn't* work as intended
