### ISSUE TITLE
Electron crashed after print

### ISSUE THREAD

**Issue by YiiGuxing** [electron/electron#19108]
Version: v5.0.5, v5.0.6
JavaScript code: `document.querySelector('iframe').contentWindow.print()`

**Comment by MarshallOfSound** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by YiiGuxing** [comment]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.5
  * 5.0.6
* **Operating System:**
  * Windows 10 1903 x64
* **Last Known Working Electron version:**
  * 5.0.4

### Expected Behavior
1. Electron does not crash.
2. Electron responds to UI events.

### Actual Behavior
1. Electron crashed.
2. Electron does not respond to UI events.

### To Reproduce
1. `$ git clone https://github.com/electron/electron-api-demos.git`
2. Modify `package.json`: `"electron": "^5.0.1"` -> `"electron": "^5.0.6"`
3. `$ npm install`
4. Add a button to `index.html`: `<button onclick="window.print()">Print</button>`
5. `$ npm run dev`
6. Click the print button
    - Click the print buuton  on the dialog: *Electron crashed after print.*
    - Click the cancel buuton  on the dialog: *Electron does not respond to UI events after the dialog closes.*

### Screenshots
![screenshot1](https://user-images.githubusercontent.com/10737066/60693675-c3360780-9f0d-11e9-9a6d-033a63e25b15.gif)
![screenshot2](https://user-images.githubusercontent.com/10737066/60693678-c7622500-9f0d-11e9-8265-1c3db1a9a14c.gif)

**Comment by lesleyandreza** [comment]
I have the same problem in MacOS Mojave 10.14.5.
With me the error happens in versions 5 and 6.
And when I tested in version **7.0.0-nightly.20190704** the print feature worked correctly.

Already corrected and missing to release in stable version?

**Comment by christophpre** [comment]
I can confirm this bug as well. Seems to have been introduced with **5.0.5** (maybe #18804). Print works for me with Version **5.0.4** and doesn't with **5.0.5** / **5.0.6**.

**Comment by HaNdTriX** [comment]
I can confirm this bug also on 

**OS:** MacOS 10.x.x
**Electron:** 6.0.x
**Error:**

```log
objc[69614]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9df513d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x10de91f50). One of the two will be used. Which one is undefined.
```
