### ISSUE TITLE
Sandbox - UserAgent is not the same as main window when sandbox is enabled with 3.x version

### ISSUE THREAD

**Issue by KiranNiranjan** [electron/electron#19113]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  3.1.11
* **Operating System:**
  *  macOS 10.14.5 / Windows 10

* **Last Known Working Electron version:**
  *  5.0.6

### Expected Behavior

the user agent in any window created using `window.open` should match with the main window's user agent

#### Main window userAgent
```Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) electron-quick-start/1.0.0 Chrome/66.0.3359.181 Electron/3.1.11 Safari/537.36```

#### Child window userAgent
```Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) electron-quick-start/1.0.0 Chrome/66.0.3359.181 Electron/3.1.11 Safari/537.36```

### Actual Behavior

Application name and version is missing in the child window created with sandbox set to `true`

#### Child window userAgent
```Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Electron/3.1.11 Safari/537.36```

Note: in the above `electron-quick-start/1.0.0` is missing in the userAgent string

### To Reproduce

```sh
$ git clone https://github.com/KiranNiranjan/electron-quick-start -b user-agent
$ npm install
$ npm start || electron .
```
Check the devtools console for the userAgent

### Screenshots

N/A

### Additional Information

N/A

**Comment by MarshallOfSound** [comment]
@KiranNiranjan `3-1-x` is very near end of life and as you've indicated that this works on `5.0.6` I'm going to close this out with the suggestion that you upgrade Electron versions 👍
