### ISSUE TITLE
[Question] Why we clear the notifications automatically from mac NC

### ISSUE THREAD

**Issue by linuxjuggler** [electron/electron#19114]
Hey,

I was wondering why the app will auto-clear the notifications from mac NC? I searched the issues but didn't get any clear answer about the topic tbh

ref: 
1. https://github.com/electron/electron/issues/6475#issuecomment-232824352
2. https://github.com/electron/electron/blob/2a3793485f71b8ec102a324ab61804c8c093a21e/shell/browser/notifications/mac/cocoa_notification.mm#L23-L27

And sorry to ask this, but what is the best way to close the app without clearing NC notifications on mac? as in my case having the notifications on the NC is important even after closing the app.

Thanks

PS: Also, I have found this question https://discuss.atom.io/t/notifications-are-removed-from-macos-notification-center-when-application-quits/48434 from 2017 which was the base for my second reference above.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

**Comment by linuxjuggler** [comment]
hey @MarshallOfSound can't we think of this as a feature like for example provide a flag to keep the notifications inside the NC and not clear them? if that's okay am happy to open a feature request for that

plus as I mentioned this question was asked in 2017 in one of the community channels but didn't get any answer.

**Comment by MarshallOfSound** [comment]
@linuxjuggler Leaving the notifications hanging around is what the majority (based on past tickets) wants, adding a flag to not dismiss them on GC is pretty bad and even if they were left around they wouldn't be actionable, E.g. click, reply events would not function.

**Comment by linuxjuggler** [comment]
Thanks @MarshallOfSound 

So basically we can't fully emulate the native apps functionality here. I was wondering about this, as for example, with TweetDeck if you clicked on the notification it will open the app, and I think this is what the majority of the people will want at most from the notification.

Thanks again for your note and really sorry for bothering you here.
