### ISSUE TITLE
bug: `systemPreferences.isDarkMode()` has non-deterministic behavior

### ISSUE THREAD

**Issue by deermichel** [electron/electron#19125]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** v7.0.0-nightly.20190705
* **Operating System:** macOS Mojave 10.14.5 (also on Catalina)
* **Last Known Working Electron version:** v6-beta.12

### Expected Behavior
When handling `AppleInterfaceThemeChangedNotification` events, `systemPreferences.isDarkMode` should reflect the current appearance theme.

### Actual Behavior
Sometimes it reflects the appearance theme _before_ the change, sometimes the theme _after_ the change. This behavior is consistent during one app instance. When you restart the app, behavior might toggle non-deterministically. However, after a short time (e.g. 1s) `isDarkMode` always returns the correct value.

### To Reproduce
```js
const {app, systemPreferences} = require('electron')

app.on('ready', () => {
  systemPreferences.subscribeNotification('AppleInterfaceThemeChangedNotification', () => {
    console.log(`Dark mode: ${systemPreferences.isDarkMode()}`)
    setTimeout(() => {
      console.log(`Dark mode after 1s: ${systemPreferences.isDarkMode()}`)
    }, 1000)
  })
})
```
Keep restarting the app to see the different behaviors.

### Screenshots
Correct:
![image](https://user-images.githubusercontent.com/8472721/60736927-9da8fe00-9f0d-11e9-84fe-9030bb3419f1.png)

Wrong:
![image](https://user-images.githubusercontent.com/8472721/60736963-cc26d900-9f0d-11e9-90de-74c20379c95e.png)

**Comment by DeerMichel** [comment]
Oh right and when building against 10.13 SDK, it always returns `false` under v7. v6 works fine... Apple 🙈

**Comment by eycorsican** [comment]
Also encounter on macOS 10.15 with Electron 6.0.0, here's a workaround:
```javascript
function isDarkMode() {
  return (systemPreferences.getUserDefault('AppleInterfaceStyle', 'string') == 'Dark')
}
```

**Comment by ossim** [comment]
Just ran into this issue. @eycorsican 's  workaround works for now, but it would be great to get the regression addressed.

**Comment by MarshallOfSound** [comment]
This is fixed by the `nativeTheme` module which landed in `v7`.  Folks should use that 👍

**Comment by tommoor** [comment]
@MarshallOfSound based on your knowledge of the issue do you think hat @eycorsican's workaround is reasonable for those of us that can't upgrade to v7 yet?
