### ISSUE TITLE
Electron how to achieve the main window flattening and dynamic adjustment of the main window size and position

### ISSUE THREAD

**Issue by JackMing0** [electron/electron#19121]
Want to use Electron for embedded application! Remove unnecessary options! Electron can realize the main window flattening and dynamic adjustment of the main window size and position? If possible! Please tell me thank you!
![8777](https://user-images.githubusercontent.com/37831370/60690519-8e6c8500-9efa-11e9-9192-7efceb3809c3.png)

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
