### ISSUE TITLE
BrowserWindow.on('swipe') broken since Electron 3

### ISSUE THREAD

**Issue by bpasero** [electron/electron#19131]
### Issue Details

* **Electron Version:**
  * 3.0.x, 4.0.x, 5.0.x, 6.0.x
* **Operating System:**
  * macOS 10.14.5
* **Last Known Working Electron version:**
  * 2.0.x

### Expected Behavior
`BrowserWindow.on('swipe')` fires when doing a 3-finger swipe gesture.

### Actual Behavior
`BrowserWindow.on('swipe')` does not fire.

**Comment by bpasero** [comment]
@codebytere @deepak1556 this seems to have caused a regression in VSCode where our window size is assumed to be larger than it is when macOS native tabs are enabled. See https://github.com/microsoft/vscode/issues/79176

**Comment by bpasero** [comment]
![grid-tw](https://user-images.githubusercontent.com/900690/63094369-76136f80-bf68-11e9-9763-6b078dcfc0f8.gif)

**Comment by KASOGIT** [comment]
Swipe event still isn't triggered with electron 7, news ?

**Comment by sdnyco** [comment]
In addition to 'rotate-gesture'. Still not working in 8.1.1

**Comment by codebytere** [comment]
@sdnyco `rotate-gesture` is working just fine for me, see [this fiddle](https://gist.github.com/4535eedab0fe411b1f20ac184f5099d0).

**Comment by codebytere** [comment]
@KASOGIT it does work: it's your system settings that make it appear not to.

`-swipeWithEvent:` is used to implement 10.6-style trackpad swiping, where the content on the screen doesn't move with the swipe. Most Mac trackpads are not configured to allow this kind of swiping anymore; the "Swipe between pages" preference in Trackpad pref pane has to be set to "swipe with two or three fingers" for it to be available.

<img width="780" alt="Screen Shot 2020-04-14 at 5 40 47 PM" src="https://user-images.githubusercontent.com/2036040/79286977-2b3f5400-7e77-11ea-9a70-4f1df7132a71.png">

**Comment by sourabhverificient** [comment]
i wanted to prevent **three figure swipe gesture** i tried

`win.on("swipe", (e, d) => {
    log.info("Swipe")
    // e.preventDefault()

  })
  win.on("rotate-gesture", (e, r) => {
    log.info("rotate-gesture")
    // e.preventDefault()
  })`
  
but i am not even getting logs. it seems **both event  not working**.
please let me know if anyone have any solution.

**Comment by seivan** [comment]
> [@KASOGIT](https://github.com/KASOGIT) it does work: it's your system settings that make it appear not to.
> 
> `-swipeWithEvent:` is used to implement 10.6-style trackpad swiping, where the content on the screen doesn't move with the swipe. Most macOS trackpads are not configured to allow this kind of swiping anymore; the "Swipe between pages" preference in Trackpad pref pane has to be set to "swipe with two or three fingers" for it to be available.
> 
> <img alt="Screen Shot 2020-04-14 at 5 40 47 PM" width="780" src="https://user-images.githubusercontent.com/2036040/79286977-2b3f5400-7e77-11ea-9a70-4f1df7132a71.png">

God I wish I saw this earlier, they removed swipe to navigate from vscode because they couldn't understand how it works, lol. Never dawned on me that it wasn't broken.
