### ISSUE TITLE
 How does it show up in full screen Mac OS applications！

### ISSUE THREAD

**Issue by JackMing0** [electron/electron#19138]
<! As an open source project, we have a small dedicated maintenance team that sometimes takes a long time to fix problems, so please be patient and we will get back to you as soon as possible.
-->

Check list before take-off
<! -- replace [] with [x] -- > to make sure you complete the following steps

* [] I have read the project guidelines (https://github.com/electron/electron/blob/master/CONTRIBUTING.md).
* [] I agree to abide by the project comply with the code of conduct (https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md).
*[] I searched the problem tracker for a feature request that matched the one I wanted to submit, but was unsuccessful.

Problem description for # # #
<! Is your feature request related to a problem? Please give a clear and concise description of the problem. -->

System: Mac OS 10.13
Electronic version: 5.0.6
Problem description:
I'm trying to use nested electrons on an application! But! In the process of implementation encountered problems! When you launch a full screen application on your Mac! Electrons will not be displayed on this startup application! I looked at the electronic creation window API and found no solution!

I took a closer look at the Mac desktop! Discovered! Launch an application full screen on Mac! Created another desktop on the Mac to store the app that is currently running full screen. All electronics can only be displayed on desktop 1! Unable to display in full screen desktop 2!

Suggestion: if you can solve this problem! Electrons will have a wide range of USES...

If there is already a solution! Please help @me! Thank you very much!

![666](https://user-images.githubusercontent.com/37831370/60764013-480e5600-a0b3-11e9-9e0b-a3617a40feec.png)
![111](https://user-images.githubusercontent.com/37831370/60764014-4a70b000-a0b3-11e9-9c40-3cc8ee11dfd8.png)

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by JackMing0** [comment]
Thank you for your advice
