### ISSUE TITLE
Session expired?

### ISSUE THREAD

**Issue by silardg** [electron/electron#19140]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
 5.0.6
* **Operating System:**
  macOS 10.13.6

### Expected Behavior
Keep the login credentials after restart

### Actual Behavior
Deletes the login and asks for it again on restart

### Additional Information
Trying to open github.com, login and keep the login next time I open the app.

**Comment by daltonmenezes** [comment]
Same here.

**Comment by silardg** [comment]
@daltonmenezes  I have found a perm. solution:

Created file cookies.js
`
const electron = require('electron')
const {app} = electron

var cookies = electron.session.defaultSession.cookies;

cookies.on('changed', function(event, cookie, cause, removed) {
  if (cookie.session && !removed) {
    var url = `${cookie.secure ? 'https' : 'http'}://${cookie.domain}${cookie.path}`
    cookies.set({
      url: url,
      name: cookie.name,
      value: cookie.value,
      domain: cookie.domain,
      path: cookie.path,
      secure: cookie.secure,
      httpOnly: cookie.httpOnly,
      expirationDate: Math.floor(new Date().getTime()/1000)+1209600
    }, function(err) {
      if (err) {
        log.error('Error trying to persist cookie', err, cookie);
      }
    });
  }
});
`

Then in `function main()` add `require('./src/cookies')`

It works okay for now, but not sure if there is an official electron.

Hope it helps!

**Comment by daltonmenezes** [comment]
@silardg Unfortunately, it didn't work for me. But I just tested **v6.0.0-beta.13** and the problem was solved.
