### ISSUE TITLE
When keyboard closes, a white rectangle remains in it's place

### ISSUE THREAD

**Issue by madalinsurdu** [electron/electron#19148]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.6
* **Operating System:**
  * Windows 10 (1803) 
* **Last Known Working Electron version:**
  * -

### Expected Behavior
Closing the keyboard should not affect the app.

### Actual Behavior
When the keyboard is closed, a white bar remains instead of the keyboard.

### To Reproduce
The code is available here: https://github.com/harrvester/electron-quick-start
```sh
# Clone this repository
git clone https://github.com/harrvester/electron-quick-start
# Go into the repository
cd electron-quick-start
# Install dependencies
npm install
# Run the app
npm start
```
OR 
You can fork electron-quick-start (https://github.com/electron/electron-quick-start)
-> Add an input or something that will open the keyboard (Windows 10 OSK);
-> Change the background.

#### First method
-> Click the input to open the keyboard (make sure it will open on top of your app);
-> Click outside app (ex: on the desktop)
#### Second method
-> Click the input to open the keyboard (make sure it will open on top of your app);
-> Lock the tablet
-> Unlock the tablet

### Screenshots
<img src="https://raw.githubusercontent.com/harrvester/electron-quick-start/master/Screenshot_1.png"/>
<img src="https://raw.githubusercontent.com/harrvester/electron-quick-start/master/Screenshot_2.png"/>
<img src="https://raw.githubusercontent.com/harrvester/electron-quick-start/master/Screenshot_3.png"/>

### Additional Information
This test was made on a Microsoft Surface Pro tablet.

Any ideas?

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.1.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
