### ISSUE TITLE
Many events triggered with undocumented Event arg

### ISSUE THREAD

**Issue by cmeeren** [electron/electron#19156]
I'm confused about events, specifically runtime vs. documented listener signatures. Many events are documented without an `Event` parameter, for example many of the BrowserWindow events such as [`closed`](https://github.com/electron/electron/blob/v6.0.0-beta.12/docs/api/browser-window.md#event-closed), [`blur`](https://github.com/electron/electron/blob/v6.0.0-beta.12/docs/api/browser-window.md#event-blur) etc. But at runtime, these events are called with an `Event` parameter.

This made me think that maybe all events have `Event` as the first parameter, but some events, such as the `autoUpdater` [`error`](https://github.com/electron/electron/blob/v6.0.0-beta.12/docs/api/auto-updater.md#event-error) event is only called with `Error`, not `Event` (and is correctly documented).

Is this just a matter of incomplete documentation, or is there a logic to this? (I'm new to the JS world, so please bear with me if this is evident to everyone but me.)

(If anyone is wondering; I'm creating Electron bindings for Fable, an F# to JS compiler, and since F# is strongly typed I should get this right in the bindings.)

**Comment by codebytere** [comment]
If that's the case, we would welcome PRs to correct said documentation! I can also potentially dedicate some time to auditing and addressing this gap time permitting.

**Comment by cmeeren** [comment]
So what you're saying is that the runtime behaviour is correct, and that if an event is called with `Event` even though no args are documented, then it's a bug in the documentation and I can count on the event always returning `Event`?

**Comment by cmeeren** [comment]
In any case: While I can write down the events I come across and can test, I don't have the infrastructure (e.g. for auto-update) or devices (e.g. for macOS-only events) to test all events, so ideally I'd like to get some official answers and not have to guess.
