### ISSUE TITLE
Add tooltip in bottom left when loading page or hovering link

### ISSUE THREAD

**Issue by EnderDev** [electron/electron#19154]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
I think there should be an option in webPreferences where you can enable the tooltips https://i.imgur.com/f4JZW4A.png

### Proposed Solution
^^

### Alternatives Considered
Using a context menu with disabled text

### Additional Information
N/A

**Comment by EnderDev** [comment]
Made it with a simple browserwindow seperate

**Comment by matthme** [comment]
Can I ask how you solved this? And can we re-open this issue? It seems to me quite basic browser functionality that seems to be built into chromium so I'm wondering why it's not there in electron...
