### ISSUE TITLE
Why does the About menu role do nothing on Windows

### ISSUE THREAD

**Issue by sregger** [electron/electron#19153]
The about menu role seems to do nothing on Windows.

https://github.com/electron/electron/blob/master/lib/browser/api/menu-item-roles.js#L176 

On Mac it pops up an About box. Why is that?

**Comment by sindresorhus** [comment]
Windows doesn't provide a system "About" dialog, see https://github.com/electron/electron/issues/15591

**Comment by codebytere** [comment]
Closing in agreement with the above. It's documented as being windows and linux-only.

**Comment by gannons** [comment]
That's unintuitive. Thanks for the info @sindresorhus.

Agree with closing the issue.
