### ISSUE TITLE
Cannot access Webview methods via webview element

### ISSUE THREAD

**Issue by Qrysto** [electron/electron#19164]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
v5.0.6
* **Operating System:**
Windows 10
* **Last Known Working Electron version:**
v4.2.6

### Expected Behavior
Previously, it was possible to call Electron's webview methods (e.g. `webview.isDevToolsOpened()`) from the `webview` element (`const webview = document.querySelector('webview')`)

### Actual Behavior
After upgrading to electron v5, `webview` element only has the native HTMLElement methods, without Electron methods.

### To Reproduce
https://github.com/Qrysto/electron-quick-start/tree/webview-bug

**Comment by miniak** [comment]
@Qrysto `nodeIntegration` and `webviewTag` options are now disabled by default for security reasons.
