### ISSUE TITLE
desktopCapturer and getUserMedia screenshot get black screenshot over electron 3.1.11

### ISSUE THREAD

**Issue by chanble** [electron/electron#19177]
### Issue Details

* **Electron Version:**
  * 4.0.0 or later
* **Operating System:**
  * Windows 10 (1803) / deepin 15.10.1
* **Last Known Working Electron version:**
  * 3.1.11

### Expected Behavior
can capture screenshot

### Actual Behavior
cpature screenshot is black

### To Reproduce
```sh
$ git clone https://github.com/chanble/electorn-capture-screen.git -b ttt
$ npm install
$ npm start 
```

### Screenshots
![DeepinScreenshot_Desktop_20190710012345](https://user-images.githubusercontent.com/3293670/60909949-157e7c00-a2b2-11e9-8e4a-0207a7b2d69b.png)

![DeepinScreenshot_Desktop_20190710012408](https://user-images.githubusercontent.com/3293670/60909982-2e872d00-a2b2-11e9-9b5e-2cbd85a44cb2.png)

**Comment by chanble** [comment]
I get it. I should play video and pause it in `video.onloadedmetadata` callback.

**Comment by chanble** [comment]
please close it

**Comment by xudeming208** [comment]
请参考＃21063
