### ISSUE TITLE
docs parser not generating types for BrowserWindow properties

### ISSUE THREAD

**Issue by nornagon** [electron/electron#19185]
e.g. `BrowserWindow.minimizable` is not present in `electron.d.ts`. Unsure if this is a docs parser issue or a type generator issue. cc @codebytere @MarshallOfSound

> [...] error TS2551: Property 'minimizable' does not exist on type 'BrowserWindow'. Did you mean 'isMinimizable'?

**Comment by codebytere** [comment]
@nornagon i _think_ this may be a docs parser issue; it seems to be dependent on the indentation of the markdown file headers (it works when i change each property from `####` to `###`) so i'll pop up a PR to address that now but i think a more robust solution might just be to make the docs-parser less brittle about that.
