### ISSUE TITLE
Deleting custom element methods could break Electron on future Chrome release?

### ISSUE THREAD

**Issue by trusktr** [electron/electron#19181]
This isn't a bug, but discussion of existing code:

https://github.com/electron/electron/blob/f36f90b60f4633a6911672b86f04ad346ad92afa/lib/renderer/web-view/web-view-element.ts#L90-L94

Based on the fact that those methods are being `delete`ed, I gather that Chrome's engine is internally using something like `.call` or `.apply` to call those methods on the element instance, after it has already gotten references to those methods.

How do we know that Chrome won't, in the future, change to doing something more like `element.connectedCallback()` instead? That may cause Electron to break, because the methods will be undefined. It seems like the above code is relying on private internals of Chrome engine.

**Comment by MarshallOfSound** [comment]
This code is internal only and Chrome does not call those methods.  If breakages occur CI will pick up on them
