### ISSUE TITLE
<webview> Preload IPC with Context Isolation

### ISSUE THREAD

**Issue by oyed** [electron/electron#19186]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 5.0.6
* **Operating System:** Arch Linux
* **Last Known Working Electron version:** N/A

### Expected Behavior
Using `ipcRenderer` to send IPC events to the host via `sendToHost` should work as intended and include all event data (Such as the `channel` attribute) in the event.

### Actual Behavior
When sending an IPC message _to_ the `<webview>`, things work as expected and the `preload` for the `<webview>` receives the event. However, when sending an event to the `<webview>` on the host (**With** context isolation enabled on the parent window) via `sendToHost`, the Event is empty (A generic JavaScript event) and has none of the usual attributes like `channel` or `args`.

### To Reproduce
Reproduced in repo: [https://github.com/oyed/context-issue](https://github.com/oyed/context-issue)

I'm not sure if this is the intended behavior with context isolation enabled.

**Comment by miniak** [comment]
Related to #9340

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.1.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by alisoncamilleri** [comment]
I am currently experiencing the same issue on macOS, using the latest version of Electron (8.0.1).

**Comment by mystster** [comment]
I have the same issue on Linux(WSL2) and Windows10. I use Electron 9.0.5.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
