### ISSUE TITLE
big delay compiling some javascript on a second running instance of Electron

### ISSUE THREAD

**Issue by ericmandel** [electron/electron#19197]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.6, 6.0.2
* **Operating System:**
  * macOS 10.14.5, 10.14.6
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
I expect a second running instance of an Electron app to compile the socket.io client file socket.io.js as quickly as the first running instance.

### Actual Behavior
There is a 4 second delay compiling socket.io.js in a second running instance of Electron if the first instance is still running.

### To Reproduce
1. install MacOS version of Electron 5.0.6

2. clone and enter the demo repository
````
$ git clone https://github.com/ericmandel/electrondelay
$ cd electrondelay
````

3. run the first instance and note the displayed times:
````
$ /Applications/Electron.app/Contents/MacOS/Electron test.js &
# my times on a MacBook Pro:
# start test: 10:36:18 AM
# start eval: 10:36:18 AM
# end eval: 10:36:18 AM
````
4. without exiting, run the second instance and note the displayed times:
````
$ /Applications/Electron.app/Contents/MacOS/Electron test.js &
# my times on a MacBook Pro:
start test: 10:37:29 AM
start eval: 10:37:29 AM
end eval: 10:37:33 AM
````
### Additional Information
Possibly related to #13163

Note that this delay does not happen if you edit test.html and load socket.io.slim.js instead. I assume this means that Chromium is making an unfortunate choice regarding how to compile these two files, but I have no idea how to proceed ...

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
