### ISSUE TITLE
Major electron start issue on mac

### ISSUE THREAD

**Issue by rebal15** [electron/electron#19208]
Hi all, I have been having a major issue with using electron as follows:
I get the following error:

sh: electron: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @ start: `electron ./app`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

Electron version: 1.4.13
OS: macOS 10.15

I have been searching the web for a while now, with no luck found, and so I have asked here. I have reinstalled npm, node_modules, electron, nodejs, electron-packager, electron-builder, yet nothing seems to work. 

**Any help would be useful!**

Thanks!

**Comment by DeerMichel** [comment]
Hi, thanks for reaching out. Have you tried a newer (supported) version of Electron - e.g. v5 or v6-beta? And please provide a short description (or repo) to reproduce the problem.

**Comment by nornagon** [comment]
We don't support Electron versions older than v3 currently. See https://electronjs.org/docs/tutorial/support#currently-supported-versions
