### ISSUE TITLE
issue in running electron on Debian environment 

### ISSUE THREAD

**Issue by abhishekvirtual** [electron/electron#19205]
HI There,
     I am facing the following issue while trying to run my electron application in Debian 7.11

/var/www/qipster/404/560/token_nest/finalTest/node_modules/electron/dist/electron: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory

I already tried to "install libX11-xcb.so.1" on the server but facing the following issue 

Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libX11-xcb.so.1
E: Couldn't find any package by regex 'libX11-xcb.so.1'

can you please help me to resolve the same.

**Comment by DeerMichel** [comment]
Looks to me as if [deps](https://chromium.googlesource.com/chromium/src/+/master/build/install-build-deps.sh#233) of Chromium are missing on your headless setup. Take a look at https://github.com/Googlechrome/puppeteer/issues/290 for possible solutions. I'll close this issue as it is not a problem of Electron itself.
