### ISSUE TITLE
tests: Meiryo is not installed by default on Windows 10

### ISSUE THREAD

**Issue by richard-townsend-arm** [electron/electron#19201]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  6.0.0-beta.12
* **Operating System:**
  *  Windows 10 (1903).
* **Last Known Working Electron version:**
  * n/a

### Expected Behavior

All font fallback tests pass.

### Actual Behavior

Font fall back tests fail with this in the log:

    not ok 1191 font fallback should fall back to Japanese font for sans-serif Japanese script",
       AssertionError: expected 'Yu Gothic' to equal 'Meiryo'",
           at Context.<anonymous> (C:\\ci\\electron\\spec\\chromium-spec.js:1555:36)",

The Meiryo font does not appear to be installed on any of the Windows 10 machine that I have access to, and [Microsoft's typography page indicates that it's no longer shipped.](https://docs.microsoft.com/en-us/typography/font-list/meiryo)

### To Reproduce

Run the tests with `-g "font fallback"` or similar on a Windows 10 system.

### Screenshots

n/a

### Additional Information

n/a

**Comment by jkleinsc** [comment]
@richard-townsend-arm where exactly are you seeing this test failure?  If I look at our 6-0-x branch builds in CI, that test passes, eg: https://ci.appveyor.com/project/electron-bot/electron-ljo26/builds/25961931

**Comment by richard-townsend-arm** [comment]
OK, so I think I've found something useful: https://docs.microsoft.com/en-us/windows/deployment/windows-10-missing-fonts

So Meiryo was removed, but it can be added back by installing Japanese supplemental fonts.

**Comment by jkleinsc** [comment]
Ah ok.  So it's just a matter of making sure the right fonts are installed for the test then.  If that is the case @richard-townsend-arm, do you mind closing this issue?

**Comment by richard-townsend-arm** [comment]
I guess probably what I need to poll is: is it worth adding Yu Gothic [(which is installed by default)](https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list) to the list of acceptable fallback fonts?
