### ISSUE TITLE
net module: doesn't emit 'end' event unless 'data' handler is registered

### ISSUE THREAD

**Issue by nornagon** [electron/electron#19214]
Observed in Electron 4, 5, 6 and master. Fiddle: https://gist.github.com/72b277f3e5ba69dd636f195c370c77f6

doesn't work ("done" never printed):

```js
      const req = net.request("https://example.com")
      req.on('response', (response) => {
        response.on('end', () => console.log('done'))
      })
      req.end()
```

works:
```js
      const req = net.request("https://example.com")
      req.on('response', (response) => {
        response.on('data', () => {})
        response.on('end', () => console.log('done'))
      })
      req.end()
```

**Comment by arantes555** [comment]
This does not seem like a bug to me. `response` is a Stream, and like all streams it has to be consumed before it can end, either by attaching and event handler to `'data'`, or by piping it.

**Comment by nornagon** [comment]
Ah, right you are. `fs.createReadStream()` behaves the same way.
