### ISSUE TITLE
about a problem of z-index of browserview

### ISSUE THREAD

**Issue by spcBackToLife** [electron/electron#19222]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

Electron Version: 5.0.6
Platform: macOs 10.14

Actual Behavior:
when a browserwindow use `setBrowserview()` to set a browserview ,and also use `loadURL()` to show a page. the content of browserview will always coverd the `loadURL page` content. 

Expected Behavior:
I can set z-index of them ,to show the `loadURL` page on the top of browserview content.

**Comment by MarshallOfSound** [comment]
A BrowserView is an entirely different renderer it is not possible to position content in the main window above a BrowserView

**Comment by headfire94** [comment]
Does it mean that you will not support #15899 @MarshallOfSound ?

**Comment by iwiedenm** [comment]
Sorry to revive this but I noticed that Beaker uses BrowserView and it is able to get a context menu to display above the BrowserView (click the icon to the right of the nav bar in Beaker to see). I have been exploring the source but I cannot really figure out how they are doing this, as the code is a little advanced for me. If anyone wants to explore it there might be a solution living somewhere in there. I believe it's in this file but, again, I'm not sure: https://github.com/beakerbrowser/beaker/blob/master/app/shell-menus.js

**Comment by wslp12** [comment]
@iwiedenm 404 ... :(

Have you got the answer to this question?

**Comment by iwiedenm** [comment]
@wslp12 Ah yes they must have refactored the project. The solution is definitely there somewhere I just cannot pinpoint where in the code it is happening :(

**Comment by fermion-boson** [comment]
> @wslp12啊，是的，他们一定是重构了这个项目。解决方案肯定是有的地方，我只是不能确定在代码中，它正在发生:(
> 
> 这些相关问题可能会帮助您
> [：#15899（评论](https://github.com/electron/electron/issues/15899#issuecomment-573554326)
> [）#16854（评论）](https://github.com/electron/electron/issues/16854#issuecomment-573405044)

The Wexond project is the same way, I don't know how they did it

**Comment by kankanai** [comment]
any news about this?

**Comment by tanhh326** [comment]
> I have implemented simple support for zIndex through `browserWindow.setTopBrowserView`. See [electron-browserView-zIndex](https://github.com/Maxwell-Jay/electron-browserView-zIndex).我已经通过 `browserWindow.setTopBrowserView` 实现了对 zIndex 的简单支持。参见 [electron-browserView-zIndex](https://github.com/Maxwell-Jay/electron-browserView-zIndex)。

Your feature is supported by electron, and what is required is that the elements of the host page can be displayed on the 'browser', such as the 'bootstrap alert' element.
