### ISSUE TITLE
webGL works in Electron 4.2.6 but not in 5.0.x

### ISSUE THREAD

**Issue by JohnMLarkin** [electron/electron#19234]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.6
* **Operating System:**
  * Windows 7
* **Last Known Working Electron version:**
  * 4.2.6

### Expected Behavior
Draw a simple map using a tutorial that works fine in a stand-alone browser (tried both HERE and MapBox versions) and under Electron 4.2.6.

### Actual Behavior
Fails to load map under 5.0.0-5.0.6.  Error message is "Failed to initialize WebGL"

### To Reproduce
```sh
$ git clone https://github.com/JohnMLarkin/MapBox_Electron_Demo
$ npm install
$ npm start || electron .
```
You will need to update the _secrets.js file with a valid MapBox token.

**Comment by spcBackToLife** [comment]
I have the same problem.

**Comment by TongDaDa** [comment]
You can add an argument of chromium in your application, for example  `--disable-GPU` or `enable-GPU`, `ignore-GPU-blacklist`. 

So what difference between them?

The first argument(disable-GPU) is to block the processing GPU of your computer and then it will use CPU to load the work of GPU. This solution is appropriated to an old graphics card.

The second argument(enable-GPU or ignore-GPU-blacklist) is to enable your graphics card to work with WebGL and other requirements of what WebGL work on your computer.

**Comment by JohnMLarkin** [comment]
I've tried all three as command line options when starting Electron and also in the main.js using app.commandLine.appendSwitch(...).  None fix the issue (or else I'm doing something wrong). WebGL still won't work under Electron 5.0.x.

> You can add an argument of chromium in your application, for example `--disable-gpu` or `--enable-gpu`, `--ignore-gpu-blacklist`.
> 
> So what difference between them?
> 
> The first argument(disable-GPU) is to block the processing GPU of your computer and then it will use CPU to load the work of GPU. This solution is appropriated to an old graphics card.
> 
> The second arguments(enable-GPU or ignore-GPU-blacklist) is to enable your graphics card to work with WebGL and other requirements of what WebGL work on your computer.

**Comment by Stefano1990** [comment]
Same problem here.

**Comment by miniak** [comment]
Please try `mainWindow.loadURL('chrome://gpu/')` and include the output here

**Comment by nornagon** [comment]
I can't reproduce this on macOS or Windows 10 on any current Electron version. Possibly this is Windows 7-specific or specific to your GPU?

**Comment by Stefano1990** [comment]
I'm on a ThinkPad yoga on Windows 10.

**Comment by nornagon** [comment]
@Stefano1990 please grab the contents of `chrome://gpu`, thanks!

**Comment by JohnMLarkin** [comment]
Here are the reports from chrome://gpu for Electron 4.2.6 and 5.0.7 (again, running under Windows 7).
[chrome_gpu_report_electron_4_2_6.txt](https://github.com/electron/electron/files/3423309/chrome_gpu_report_electron_4_2_6.txt)
[chrome_gpu_report_electron_5_0_7.txt](https://github.com/electron/electron/files/3423310/chrome_gpu_report_electron_5_0_7.txt)

I also just tested my code on Windows 10 (MS Surface Pro) and it works fine there.

**Comment by nornagon** [comment]
> GPU process was unable to boot: GPU process crashed too many times with SwiftShader.

that seems like the problem!

Can you try running your test app with `--enable-logging` to see if any information is printed about why the GPU process crashed?

**Comment by JohnMLarkin** [comment]
The chromium log reports:
[5204:0723/111019.768:ERROR:browser_gpu_channel_host_factory.cc(139)] Failed to launch GPU process.
[5204:0723/111022.662:VERBOSE1:CONSOLE(7965)] "Main._createAppUI: 79.357177734375ms", source: chrome-devtools://devtools/bundled/shell.js (7965)
[5204:0723/111022.702:VERBOSE1:CONSOLE(7965)] "Main._showAppUI: 39.214111328125ms", source: chrome-devtools://devtools/bundled/shell.js (7965)
[5204:0723/111022.817:VERBOSE1:CONSOLE(7965)] "Main._initializeTarget: 11.44189453125ms", source: chrome-devtools://devtools/bundled/shell.js (7965)
[5204:0723/111022.818:WARNING:CONSOLE(170)] "%cElectron Security Warning (Insecure Content-Security-Policy)", source: H:\Research\Balloon\MapBox_Electron_Demo\node_modules\electron\dist\resources\electron.asar\renderer\security-warnings.js (170)
[5204:0723/111022.819:WARNING:CONSOLE(170)] "%cElectron Security Warning (Insecure Content-Security-Policy)", source: H:\Research\Balloon\MapBox_Electron_Demo\node_modules\electron\dist\resources\electron.asar\renderer\security-warnings.js (170)
[5204:0723/111022.985:VERBOSE1:CONSOLE(7965)] "Main._lateInitialization: 0.988037109375ms", source: chrome-devtools://devtools/bundled/shell.js (7965)

**Comment by nornagon** [comment]
Unfortunately the only relevant error message there is
> Failed to launch GPU process.

which isn't terribly helpful :/

**Comment by JohnMLarkin** [comment]
Thanks for the attempt. Looks like the simple solution is to ditch Windows 7.

**Comment by Stefano1990** [comment]
I have the same problem on Windows 10. I will try to get a screenshot some
time when I'm in the office.

**Comment by spcBackToLife** [comment]
I have the same problem in Electron6 with win7

**Comment by romanhaa** [comment]
Same problem here, Windows 10 running in VM.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
