### ISSUE TITLE
protocol.interceptHttpProtocol is invalid

### ISSUE THREAD

**Issue by hxkuc** [electron/electron#19240]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
5.0.6
* **Operating System:**
  * 
* **Last Known Working Electron version:**
  * 
win7
### Expected Behavior

i use interceptHttpProtocol to intercept https request, follow code 
```
protocol.interceptHttpProtocol(
    'https',
    (request, callback) => {
      callback(Object.assign({}, request, {session: null}))
    },
    error => {
        if (error) console.error('Failed to intercept protocol')
    }
  )
mainWindow.loadURL(`https://www.baidu.com`);
```

it do not work in version 5.0.6, but it worked in version 1.8.8

### Actual Behavior

it shoult show the 'https://www.baidu.com' page

**Comment by codebytere** [comment]
As it stands, there is not enough information provided for us to triage this. 

> it do not work in version 5.0.6,

what does this mean? "not work" in what way? crash? different behavior?

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment. If no response is provided within 10 days, this issue will be closed.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
