### ISSUE TITLE
Cannot read property 'send' of undefined in electron

### ISSUE THREAD

**Issue by vigneshbabu801** [electron/electron#19253]
main.js--

    restoreWindowSave =	win.getBounds();
    console.log("Restore",restoreWindowSave);
    ipcMain.on('custom-restore', (event) => {
		console.log(win.setSize(restoreWindowSave.width, restoreWindowSave.height));
        win.setPosition(restoreWindowSave.x, restoreWindowSave.y);
    });

custom.js

    const { remote, screen, ipcRenderer } = require('electron').remote.screen;
    function customRestore()
    {
        ipcRenderer.send('custom-restore');   
    }

            $('#max_remove').click(function (e) {
                e.preventDefault();
                customRestore();
            });

**Comment by vigneshbabu801** [comment]
I want to restore my window size back to normal after maximize.

**Comment by tborychowski** [comment]
I have a similar issue:
```sh
ipcMain.on('channel', (ev, arg) => {
        ^
TypeError: Cannot read property 'on' of undefined
```

**Comment by MarshallOfSound** [comment]
```js
const { remote, screen, ipcRenderer } = require('electron').remote.screen;
```

I'm not sure what you want this code to do but it's definitely not going to work.  I'm guessing you want something like

```js
const { remote, ipcRenderer } = require('electron');
const { screen } = remote;
```

**Comment by tborychowski** [comment]
@MarshallOfSound 
this is exactly what I have and it doesn't work.
However, TBH, that might not be an issue with electron itself.
I think that this started happening when I upgraded to MacOS Catalina :-)

**Comment by nazamov** [comment]
const appWindow = new BrowserWindow({
    width: 1150,
    height: 600,
    webPreferences: {
      webSecurity: false,
      nodeIntegration: true,
      contextIsolation: false,
      enableRemoteModule: true,
    },
  });
  
  you need to enableRemoteModule when creating window. Try this
