### ISSUE TITLE
Electron apps slow on amdgpu

### ISSUE THREAD

**Issue by Redsandro** [electron/electron#19269]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue

I'm unsure if I'm allowed to post this vague issue here, because I'm not sure what's to blame. But here goes:

As a developer, I'm a big fan of Atom (IDE) and Boostnote (notes). They are both Electron apps. Usually I'm working on 2 Intel machines. One with nVidia graphics, and one with onboard Intel HD graphics.

I recently bought an **AMD Ryzen 5 3400G** with onboard **Radeon Vega Graphics** (APU) on an ASRock A300 Mini-STX board to replace an outdated desktop computer. I'm really pleased with this small machine. Everything is going snappy. Everything seems faster than my old machine at a fraction of the power usage.

However, Electron apps seem to go way slower. Everything moves with a lag or latency of 100ms, from scrolling to selecting text. And the Window seems to update at ~10 FPS while the rest of my machine updates at 60 FPS. In stead of tabs with code being visible instantly, I see them being constructed. First the panel, then grey text appears, then a syntax highlighting pass. This only takes a couple of frames, but it's annoying enough, especially since it works fluently on older machines.

### Issue Details

* **Electron Version:**
  * 2.x and 3.x
* **Operating System:**
  * Linux Mint 19.1 Cinnamon 4.0.10 x64
* **Graphics Hardware:**
  * Advanced Micro Devices, Inc. [AMD/ATI] Picasso
* **APU:**
  * [Ryzen 5 3400G](https://www.amd.com/en/products/apu/amd-ryzen-5-3400g#product-specs)

### Expected Behavior
Snappy and fluent interface

### Actual Behavior
Laggy and stuttering interface

### Additional Information
Google Chrome itself is going super fluent.

**Comment by miniak** [comment]
Electron 2 is not supported anymore, removing label

**Comment by miniak** [comment]
Can you please try https://electronjs.org/fiddle, which is based on Electron 5 if it still reproduces?

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by Redsandro** [comment]
I was traveling the last month.

@miniak I don't know how to create a fiddle, but if you have any example apps, I can try them.

* Atom 1.40.1 freezes my system within a minute of opening a file. No ssh, tty or sysrq possible.
* Boostnote 0.11.17 [freezes my system](https://github.com/BoostIO/Boostnote/issues/3122) within a minute of opening Interface Settings.

**Comment by Redsandro** [comment]
@miniak I've installed every version of Boostnote to find out exactly what commit caused the crash, and it is the one that upgraded Electron from 3.0.3 to 3.0.8: https://github.com/BoostIO/Boostnote/commit/1388e7d7f478102fc98dce303cbed883b06ff9bd

Here's something interesting: The apps don't crash immediately. It's usually after some scrolling or clicking a dropdown.

I notice that the Electron app that will crash is fast and smooth again. If it's slow and laggy, it will not crash.

**Comment by Redsandro** [comment]
Since Atom 1.40 crashes too, and Atom 1.40 uses Electron 3.1.10, I suspect At least Electron >= 3.0.8 <= 3.1.10 crashes AMD Picasso computers.

**Comment by Redsandro** [comment]
> don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

So, 3.x crashes. 4.x works. Something needs to be backported to 3.x in order to fix all the crashing Electron apps out there that are not ready to upgrade the major version.

Could you reopen this issue @sofianguy ?

**Comment by miniak** [comment]
Electron 3 and 4 are not supported anymore, so there is nothing to back-port.

**Comment by Redsandro** [comment]
@miniak Ok gotcha.

Is there any overlap between the Atom team and the Electron team (because they are both projects by GitHub)? Because Atom just released 1.41 _last week_, where they moved from Electron 2 to Electron 4 even though 5, 6, and 7 were already out. Why would a skilled team choose to move to an unsupported Electron version and skip the three supported versions? Are there known critical issues?

The reason I bring this up is that team Electron can choose to not support certain versions anymore based on reasons, but reality is that many smaller, bigger, and popular apps (like "your own" Atom) are using Electron 2, 3 and 4.
