### ISSUE TITLE
Failed to get 'download' path

### ISSUE THREAD

**Issue by chenshuipeng** [electron/electron#19273]
### Issue Details

* **Electron Version:2.0.7
  * 
* **Operating System:WIN7
  * 
* **Last Known Working Electron version:2.0.7
  * 

### Actual Behavior

![image](https://user-images.githubusercontent.com/22186574/61273410-0af54280-a7dc-11e9-967f-37a1873fff90.png)

### Additional Information

ipcMain.on('find-download-path', function(event, arg) {
    event.returnValue = app.getPath('downloads');
});

ipcMain.on('getAutoStartValue', () => {
    startOnBoot.getAutoStartValue(exeName, (error, result) => {
        dialog.showMessageBox(mainWindow, {
            message: error + ' '+ result
        });
        if (error) {
            mainWindow.webContents.send('getAutoStartValue', false)
        } else {
            mainWindow.webContents.send('getAutoStartValue', true)
        }
    })
});

this Line/Column in main.js points ‘getAutoStartValue’, but i cant find anything about 'downloads'

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron < `3.1.x`. In order for the maintainers to continue triaging this issue, please demonstrate that it is present on a [supported version](https://electronjs.org/docs/tutorial/support).

At present, it also appears that your local machine is simply failing to find the `downloads` folder you are querying for in `app.getPath('downloads')`, which is likely not an Electron issue.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by asd281533890** [comment]
Still facing the issue using electron22.3.24. But this error can't be reproed all the time.
