### ISSUE TITLE
preventDefault on webContents before-input-event also prevents menu accelerators

### ISSUE THREAD

**Issue by alexstrat** [electron/electron#19279]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 4.1.4 , 5.0.6
* **Operating System:** macOS
* **Last Known Working Electron version:** ?

### Expected Behavior

When preventing a keyboard event with `before-input-event`, I would have expected that menu accelerators are triggered anyway.

Example:
- with `before-input-event`, using `preventDefault` I'm preventing keyboards events with `key='t'` and `meta=true` from being sent to a `webContents`
-  I'm adding a menu `'Command T'` with accelerator `CmdOrCtrl+T`
- => when pressing `Cmd+T`, `'Command T'` menu is not triggered, I expected it would

### To Reproduce
Use this Fiddle: https://gist.github.com/717833a552807afd427847de8346fcac

### Additional Information
I'm trying to match Chrome behavior: when a menu keyboard shortcut is pressed (for instance Cmd+T), the menu is triggered but no DOM's `InputEvent` is dispatched in the focused page.

**Comment by MarshallOfSound** [comment]
> When preventing a keyboard event with before-input-event, I would have expected that menu accelerators are triggered anyway.

This is how `before-input-event` works (expected behavior).  The menu accelerator handler is processed after that event gets emitted by Chromium

**Comment by alexstrat** [comment]
Ok thanks! Indeed the doc is actually clear about it:

>Calling `event.preventDefault` will prevent the page `keydown`/`keyup` events **and the menu shortcuts.**

As far as I can tell, I guess there is no way today of achieving this: prevent the page `keydown`/`keyup` events but *not* the menu shortcuts.
(There is this workaround: call the `MenuItem` click handler from the `before-input-event` event handler after preventing the events.)

So this falls into a feature request.

**Comment by alexstrat** [comment]
Note the future implementation: it seems that Chromium has the concept of [reserved commands](https://cs.chromium.org/chromium/src/chrome/browser/ui/browser_command_controller.h?l=44) to block sending events to the renderer when matching a shortcut.
