### ISSUE TITLE
Electron command not working

### ISSUE THREAD

**Issue by MD-AZMAL** [electron/electron#19271]
I have installed electron but it doesn't seem to work. When i try using electron command it doesn't do anything or give any errors. Attached terminal output below.

```
root@loopaz:~# npm install electron -g --unsafe-perm=true --allow-root
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
/usr/local/bin/electron -> /usr/local/lib/node_modules/electron/cli.js

> electron@5.0.6 postinstall /usr/local/lib/node_modules/electron
> node install.js

Downloading tmp-3748-1-SHASUMS256.txt-5.0.6
[============================================>] 100.0% of 4.74 kB (4.74 kB/s)
+ electron@5.0.6
added 146 packages from 141 contributors in 350.609s
root@loopaz:~# el
electron  elfedit   elif      else      
root@loopaz:~# electron -h
root@loopaz:~# electron
root@loopaz:~# electron -v
root@loopaz:~# 

```

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by DeerMichel** [comment]
You try to run electron as root. This requires the `--no-sandbox` parameter as described in https://github.com/electron/electron/issues/18547. A non-silent warning message is on its way... https://github.com/electron/electron/pull/19216. If the issue persists, feel free to reopen.

**Comment by MD-AZMAL** [comment]
@DeerMichel  That wasn't the issue it wasn't detecting electron so i had to completely wipe out both npm, node and electron. After reinstalling it worked... yes i used --no-sandbox for running it as root.
