### ISSUE TITLE
docs: unclear sccache related build directions for windows

### ISSUE THREAD

**Issue by bughit** [electron/electron#19289]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

https://github.com/electron/electron/blob/master/docs/development/build-instructions-gn.md

1. The first mention of sccache states:
   > You can avoid much of the wait by reusing Electron CI's build output via sccache.

   **Which seems to say that pre-built binaries will be downloaded somehow. Is that the case? On windows too?**
2. The linux initial `gn gen` section mentions an optional `cc_wrapper=\"${PWD}/electron/external_binaries/sccache\"`, **but the windows one does not, why? it doesn't work on windows?**
3. Then it says
   > To speed up subsequent builds, you can use sccache. Add the GN arg cc_wrapper = "sccache"

   But the linux cc_wrapper is already set as shown in 2. **What's the difference between the two shown cc_wrapper values?**

   It seems to contradict 1. **Is sccache intended for using pre-built binaries or your own first build output or either?**

**Comment by bughit** [comment]
@MarshallOfSound When I was looking for similar issues, I found your comment

> [I did actually get sccache working on windows](15090#issuecomment-429129022)

Could you please clarify the docs?

**Comment by MarshallOfSound** [comment]
`sccache` still doesn't work on windows and although I made it work~ish / build at some point it's not running on our CI and therefore isn't worth the hassle over plain `ccache` (the S is only helpful when you can let CI do the work for you).

`sccache` does work on Linux and macOS and can make your local linux build take as short as ~3 minutes if you have a fast network connection.

1. sccache binaries are downloaded on supported platforms (not windows) by electron during `gclient sync`
2. It doesn't work on windows, that's why it's only mentioned on linux/macOS
3. The first one uses the sccache binary that Electron bundles with our buildtools, the second one assumes you have sccache available on your path.  tbh the second one should probably go

> It seems to contradict 1. Is sccache intended for using pre-built binaries or your own first build output or either?

Either

`sccache` works by using instead of compiling locally using pre-compiled intermediate artifacts from our CI machines or your local machine (it's a two step cache).

`Compile Request --> Local Cache --> Remote Cache (S3) --> Compile Locally`

If it hits anywhere along that chain it won't proceed to the next cache lookup.  If it misses it will fall back to compiling locally like normal

**Comment by bughit** [comment]
@MarshallOfSound 

So should cc_wrapper be set on windows, in order to use the local cache?

And should it be set from the start or only after the first build?

**Comment by MarshallOfSound** [comment]
@bughit `sccache` does not function on windows, you shouldn't set `cc_wrapper` on windows

**Comment by bughit** [comment]
@MarshallOfSound 

There are two sections in the doc that refer to setting cc_wrapper

1. before the first build
   ```   
   # this next line is needed only if building with sccache
   $ export GN_EXTRA_ARGS="${GN_EXTRA_ARGS} cc_wrapper=\"${PWD}/electron/external_binaries/sccache\""
   ```
2. after the first build
   > To speed up subsequent builds, you can use sccache. Add the GN arg cc_wrapper = "sccache" by running gn args out/Debug to bring up an editor and adding a line to the end of the file.

I still don't understand the purpose of the second section. Why is it trying to speed subsequent builds, when the first section already sped up the first build?

About the local cache, are saying is that the local cache is used automatically on windows, cc_wrapper does not need to be set for it. Or there is no local cache on windows either?

**Comment by MarshallOfSound** [comment]
> Or there is no local cache on windows either?

`sccache` does not work on windows, therefore there is no remote cache, no local cache, no nothing, it simply doesn't work.

> I still don't understand the purpose of the second section. Why is it trying to speed subsequent builds, when the first section already sped up the first build?

It's probably just two bits of documentation that were written at different times and could be cleaned up, the word "subsequent" appears to be the word in question here.  Removing that one word makes everything make sense

**Comment by bughit** [comment]
Beyond "subsequent builds" it's also referring to modifying the args `gn args out/Debug`, which implies the first build from the initial `gn gen` was done without it. So it sounds the whole second section should be removed.

**Comment by bughit** [comment]
> the word "subsequent" appears to be the word in question here. Removing that one word makes everything make sense

@MarshallOfSound 

I am trying a linux=>win cross compile build, and would like to confirm the cc_wrapper directions.

The doc says to use
- `cc_wrapper=\"${PWD}/electron/external_binaries/sccache\"` on the initial build
- `cc_wrapper = "sccache"` "To speed up subsequent builds"

So it's still not clear, what is the correct value of the cc_wrapper arg? Does it need to change from initial to subsequent builds?

**Comment by bughit** [comment]
@MarshallOfSound 

Also for cross-compiling the docs don't mention how to make the VS and WINSDK headers and libs and whatever else, available.

**Comment by MarshallOfSound** [comment]
> So it's still not clear, what is the correct value of the cc_wrapper arg? Does it need to change from initial to subsequent builds?

`cc_wrapper` is just a path to the sccache binary, you don't need to change it, just set it to a valid path.  If `sccache` is on your `PATH` then you can just put "sccache" there.  If not then you'll need the absolute path.

> Also for cross-compiling the docs don't mention how to make the VS and WINSDK headers and libs and whatever else, available.

Electron does not support cross-compilation.  If you want to try figure it out, that's up to you 👍

**Comment by bughit** [comment]
> Electron does not support cross-compilation.

@MarshallOfSound 

In that case I'd like to provide some feedback on the regression (without workaround) of the windows build experience since 4.x. I am sure you know all this, but it needs to be underscored how significantly it impedes working on electron on windows.

The old build was managebly fast for two reasons, downloadable chromium and node artifacts and component builds. Both of which are currently broken on windows. As a result the full static testing build on my 5 year old hardware now takes almost the whole workday, during which time my win vm is not really usable for anything else.

Both sccache and component builds are desperately needed on windows to get back to where we were before.

**Comment by MarshallOfSound** [comment]
@bughit We are aware of the long built times, as are the Chromium build team.  There isn't a whole lot we can do to improve it on our end.

**Comment by bughit** [comment]
> We are aware of the long built times, as are the Chromium build team. 

The goal here is not to build chromium faster but to not build it all. Isn't that what sccache is supposed to provide? And then further to avoid long link times with the component build.

So if the project can devote any resources to getting windows sccache and component builds working, it would be very beneficial, as the current windows build situation undoubtedly creates a significant barrier to contributing.
