### ISSUE TITLE
feat: implement `will-resize` event for Linux

### ISSUE THREAD

**Issue by alitaheri** [electron/electron#19301]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
The `will-resize` event that is emitted by the `BrowserWindow` is a crucial component of any window management system (snapping windows, specific layouts, etc).

The `will-move` event is also important, but there are workarounds for that one for now.

### Proposed Solution
According to https://github.com/electron/electron/pull/13649#issuecomment-407854603, it should be possible to get this working for linux as well.

### Alternatives Considered
I've tried `setBounds` on `resize` but it flickers so badly.

**Comment by pmkary** [comment]
@DeerMichel &mdash; So we made an issue for it.

**Comment by pmkary** [comment]
Issues across other projects that must be closed for this issue to be implementable:

- https://bugs.chromium.org/p/chromium/issues/detail?id=985481
- https://gitlab.freedesktop.org/xorg/lib/libxrandr/issues/8

**Comment by pmkary** [comment]
X's team came back to me with this So it seems impossible I guess:

<img width="685" alt="Screen Shot 2019-07-23 at 4 45 44 PM" src="https://user-images.githubusercontent.com/2157285/61711460-5d4cdb00-ad69-11e9-830f-ebd135e17f7f.png">

**Comment by DeerMichel** [comment]
X11 stuff is abstracted away from us through Chromium. My experiments over there didn't succeed but feel free to try it - [here](https://cs.chromium.org/chromium/src/ui/base/x/) should be a good place to start. Reach out to me via dm if you need help setting up the env 😉.

**Comment by codebytere** [comment]
The Chromium issue has been closed as wontfix and the upstream one has been deleted so i'm going to close this out. We can revisit and open should something change :)

**Comment by pouyakary** [comment]
Sad ☹️
