### ISSUE TITLE
Setting maximizable to false still shows the maximize icon on the frame

### ISSUE THREAD

**Issue by kkumar4** [electron/electron#19306]
Here is my sample code to create the window:

```
let aboutWindow = new BrowserWindow({
    width: 300,
    height: 300,
    backgroundColor: '#222',
    show: true,
    maximizable: false,
    minimizable: false,
    alwaysOnTop: true,
    title: 'About'
})
```

And here is the screenshot of the output window on Mac(Mojave 10.14.4). Have't tested on other platform yet.

<img width="297" alt="Screen Shot 2019-07-17 at 9 36 57 PM" src="https://user-images.githubusercontent.com/6407135/61392526-a79f0980-a8dc-11e9-87f3-c722d41b32bc.png">

Electron version: 4.2.0

As you can see the maximize icon is still there on the frame even after setting maximizable to false while creating the window. I can click that icon and the window goes full screen.

**Comment by DeerMichel** [comment]
This is somehow related to the `alwaysOnTop` property. Bc it works when this property is set to `false`. Further investigating...
