### ISSUE TITLE
Build the node code cache through GN

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#19311]
Currently we use the stub node code cache, we should support the `mkcodecache` binary in our build system.

Refs: https://github.com/nodejs/node/blob/master/node.gyp#L429-L449

**Comment by nornagon** [comment]
does that conflict with mksnapshot?

**Comment by MarshallOfSound** [comment]
They're two different things afaik.

**Comment by MarshallOfSound** [comment]
So quick update, made it build, then everything crashes, so that's fun 🤷‍♂ I'll get back to this at some point but not going to invest to much time rn
