### ISSUE TITLE
Electron 5.x's node v12.0.0 has openSSl v1.1.0 but vanilla node v12.0.0 has openSSL v1.1.1b

### ISSUE THREAD

**Issue by troppoli** [electron/electron#19327]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

**Electron Version:**
  *v5.0.1* 
**Operating System:**
  *Windows !o Pro 1803* 
**Last Known Working Electron version:**
  
### Expected Behavior
Expected that for node v12.0.0 running electron to have the same version of openssl as node v12.0.0 running on the desktop.
```
console.log(process.versions.node,process.versions.openssl);
12.0.0 1.1.1b
```
### Actual Behavior
```
console.log(process.versions.node,process.versions.openssl);
12.0.0 1.1.0
```
### To Reproduce
```
run node v12.0.0 in a command shell
console.log(process.versions.node,process.versions.openssl);
```
```
run electron 5.x break into devtools
console.log(process.versions.node,process.versions.openssl);
```
The practical impact of this is that the different hash algorithms are available in the different versions making code fail that runs in v12.0.0 of node, just in electron.

**Comment by MarshallOfSound** [comment]
@troppoli Electron does not actually include `openssl`, we bind node to chromiums `boringssl` library which exposes openssl compatible APIs.

The difference in algorithms is because boringssl does not ship algorithms deemed obsolete or insecure.  Which algorithm, in particular, are you trying to use and is not available?

**Comment by troppoli** [comment]
Thanks for the info. I was looking for shake128.

It's unfortunate to have different run-time behavior like that, makes it tough to have unit tests. 

So why report a version for openSSL that isn't used and no version for boring that is?

Is there doc that notes the differences between node and the node that's in electron? 

FWIW electron node, with boring, reports these hashes:
["md4", "md5", "ripemd160", "sha1", "sha224", "sha256", "sha384", "sha512"]

openSSL v1.1.1b has these:
['RSA-MD4','RSA-MD5','RSA-MDC2','RSA-RIPEMD160','RSA-SHA1','RSA-SHA1-2','RSA-SHA224','RSA-SHA256','RSA-SHA3-224','RSA-SHA3-256','RSA-SHA3-384','RSA-SHA3-512','RSA-SHA384','RSA-SHA512','RSA-SHA512/224','RSA-SHA512/256','RSA-SM3','blake2b512','blake2s256','id-rsassa-pkcs1-v1_5-with-sha3-224','id-rsassa-pkcs1-v1_5-with-sha3-256','id-rsassa-pkcs1-v1_5-with-sha3-384','id-rsassa-pkcs1-v1_5-with-sha3-512','md4','md4WithRSAEncryption','md5','md5-sha1','md5WithRSAEncryption','mdc2','mdc2WithRSA','ripemd','ripemd160','ripemd160WithRSA','rmd160','sha1','sha1WithRSAEncryption','sha224','sha224WithRSAEncryption','sha256','sha256WithRSAEncryption','sha3-224','sha3-256','sha3-384','sha3-512','sha384','sha384WithRSAEncryption','sha512','sha512-224','sha512-224WithRSAEncryption','sha512-256','sha512-256WithRSAEncryption','sha512WithRSAEncryption','shake128','shake256','sm3','sm3WithRSAEncryption','ssl3-md5','ssl3-sha1','whirlpool']

**Comment by nornagon** [comment]
i suppose this is a vote for #18826. It's a little tricky though because boringssl doesn't have version numbers.

BoringSSL doesn't support shake128 ([here](https://www.imperialviolet.org/2017/05/31/skipsha3.html)'s a relevant post by one of boringssl's developers) so unfortunately we can't support it either. Perhaps try https://www.npmjs.com/package/js-sha3 or similar.

**Comment by troppoli** [comment]
After some research I can fulfill the need at the moment by truncating the result of sha256. 

I do think that reporting the version of ssl that's not being used isn't helping many people and will at times lead them on wild goose chases. ;)

FWIW, I opened a [related question](https://github.com/nodejs/node/issues/28757#issuecomment-513827498) because the node API would need to be extended to support variable hash output sizes.

**Comment by igor-lemon** [comment]
What about ed25519 support? 1.1.1b supports this but I can't run SSH2 lib because of `boringssl ` or doesn't support ed25519 or has incompatible API. Under native NodeJS v12+ all work correctly.

**Comment by vjau** [comment]
This is very confusing, i have just wasted two hours trying to get sha3 to work with my electron app, only to find in closed bug comments that open-ssl  included in electron is in fact not included despite what `process.versions` is advertising.
