### ISSUE TITLE
`page-title-updated` not working properly

### ISSUE THREAD

**Issue by sentialx** [electron/electron#19323]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  6.0.0-beta.14
* **Operating System:**
  * Windows 10 1903
* **Last Known Working Electron version:**
  * 5.0.7

### Expected Behavior
The title should be updated.

### Actual Behavior
The title is not updating.

### To Reproduce

* Create a `BrowserView`.
* Add a `page-title-updated` listener.
* Go to any website.
* Observe the `title` parameter behavior.

### Screenshots
The selected tab should display `Google` instead of `New tab`.
![image](https://user-images.githubusercontent.com/11065386/61445869-7e1ec600-a94e-11e9-9eb7-8f27560db2f8.png)

### Additional Information
The problem also occurs when using `webContents.getTitle()` in `setInterval`.

**Comment by Devhercule** [comment]
Which project are you using to handle tabs in your electron app?

**Comment by Devhercule** [comment]
@sentialx are you using [_Webview_](https://electronjs.org/docs/api/webview-tag) or [_BrowserView_](https://electronjs.org/docs/api/browser-view)?

**Comment by sentialx** [comment]
@Devhercule `BrowserView`

**Comment by sentialx** [comment]
My bad, everything works correctly. I had to do slight modifications in my code after update to get this to work.

**Comment by markosii** [comment]
@sentialx  would it be possible to share only the part of code that manages the tabs in your browser using the browserView. Wexond is a big project.

**Comment by sentialx** [comment]
@markosii https://github.com/wexond/desktop/blob/master/src/main/view-manager.ts

**Comment by sentialx** [comment]
I'm reopening this issue, because `page-title-updated` is not being fired when going back and forward (i.e on github.com).
