### ISSUE TITLE
simple quote encoding in HTTP vs HTTPS requests

### ISSUE THREAD

**Issue by Devhercule** [electron/electron#19322]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  * v4.2.6
* **Operating System:** 
  * windows 7
* **Last Known Working Electron version:** 
  * IDK

Electron does not encode urls in the same way when it's http or https :
- http request : Electron encode the simple quote and replace it with %27
- https request : Electron does not encode the simple quote. The server receive the request with the simple quote '

### Expected Behavior

Either encode in the two cases (regardless of the protocol of the request) or never encode the request.

### Actual Behavior

Electon (or chromium) does not encode simple quote in https requests and encodes it in http requests.

### To Reproduce

Launch a HTTP request with simple quote inside the url.
Check the url received server side -> quote is encoded and replaced by %27.
Launch a HTTPS request with simple quote inside the url.
Check the url received server side -> quote is not encoded and it appears in the url.

**Comment by codebytere** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by Devhercule** [comment]
Thank you @codebytere for your response.

To produce this issue, you should have a server to be able to see incoming requests from electron client.

I used the quick start example, I added this code at the end of the function `createWindow()` in "main.js" (create a session instance and set the proxy params with your own proxy).

  ```
const tabSession = session.fromPartition("test");
tabSession.setProxy({ proxyRules: 'YourProxyAdress:port' }, () => {
});
```

I created a webview in "main.html"
  
1st case: **https** request :

  `<webview id="foo" src="https://www.example.org/abc'.jpeg" style="display:inline-flex; width:100%; height:800px" partition="test"></webview>`

  url received by my proxy :
  https://www.example.org/abc'.jpeg
  
  
  2nd case: **http** request :
  
  `<webview id="foo" src="http://www.example.org/abc'.jpeg" style="display:inline-flex; width:100%; height:800px" partition="test"></webview>`
  
  url received by my proxy :
  http://www.example.org/abc%27.jpeg

**Comment by Devhercule** [comment]
@codebytere 

I resolved the issue, It was not an electron issue.

It is my proxy module that posed problem. this module encodes http and https requests differently (it was a node parse problem).

I close this issue.

Thank you again
