### ISSUE TITLE
how to remote debug webview in electron 

### ISSUE THREAD

**Issue by abnerCrack** [electron/electron#19328]
First, Thank you for such a great program.

But I have a little problem。

I want to inspect remote webview , with remotedebug-ios-webkit-adapter in electron

in chrome we can open chrome://inspect/#devices click the item to inspect the webview.

Is it possible to call it that way in an electron？

**Comment by MarshallOfSound** [comment]
@abnerCrack Launch Electron with `--remote-debugging-port=9229` and then go to `chrome://inspect` in your browser

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
