### ISSUE TITLE
Electron disable auto reload

### ISSUE THREAD

**Issue by major697** [electron/electron#19320]
I install Electron with Vue using this [tutorial](https://alligator.io/vuejs/vue-electron/).

I looking for answer how I can disable auto reload ? I start my application using npm run dev, when I change somethink in code Electron run auto reload (refreshes and compiles the application again ). I would like to refresh the application myself after writing a part of the code. I don't use Webpack.

Yes, I know I can disable auto save in Visual Studio Code, but this is not a solution.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

**Comment by MarshallOfSound** [comment]
Side note, auto-reload is not an Electron feature.  It'll be provided by whatever tooling vue is using
