### ISSUE TITLE
Electron build failed due to error C2059: syntax error: 'requires' under /std:c++latest(C++20) 

### ISSUE THREAD

**Issue by QuellaZhang** [electron/electron#19335]
Electron build failed due to error C2059: syntax error: 'requires' under /std:c++latest(C++20) on MSVC, 'requires' is a keyword in C++20. Could you help look at this? Thanks in advance!

**Repro steps:**

1. git clone https://github.com/electron/electron.git D:\Electron\src
2. open a clean VS x86 command prompt and browse to D:\Electron\src
3. set CL=/Zc:noexceptTypes- /std:c++latest
4. python script\bootstrap.py -v --target_arch=ia32
5. cd ..
6. vendor\depot_tools\ninja.exe -C out\R electron -v -d keeprsp

**Failures:**
D:\Electron\src\vendor\download\libchromiumcontent\static_library\gen\services\service_manager\public\mojom\interface_provider_spec.mojom-shared-internal.h(202): error C2059: syntax error: 'requires'
D:\Electron\src\vendor\download\libchromiumcontent\static_library\gen\services\service_manager\public\mojom\interface_provider_spec.mojom-shared-internal.h(202): error C2238: unexpected token(s) preceding ';'
D:\Electron\src\vendor\download\libchromiumcontent\static_library\gen\services\service_manager\public\mojom\interface_provider_spec.mojom-shared-internal.h(208): error C2338: Bad sizeof(InterfaceProviderSpec_Data)
D:\Electron\src\vendor\download\libchromiumcontent\static_library\gen\services\service_manager\public\mojom\interface_provider_spec.mojom-shared.h(348): error C2059: syntax error: 'requires'
D:\Electron\src\vendor\download\libchromiumcontent\static_library\gen\services\service_manager\public\mojom\interface_provider_spec.mojom-shared.h(349): error C2039: 'output': is not a member of 'service_manager::mojom::internal::InterfaceProviderSpec_Data'

**Comment by MarshallOfSound** [comment]
@QuellaZhang We have very strictly documented MSVC requirements for building Electron that come from Chromium.  Electron >= 4 does not even use MSVC and Electron 3 is a few weeks away from being End Of Lifed.

This isn't something we can / should be fixing 👍

**Comment by cdacamar** [comment]
Does Electron intend to use any C++20 features or is the project going to lock on C++17?  The error we observed here is mandated by the introduction of concepts in C++20 so clang will also produce the same failure at some point.

We are maybe giving you a head start here :smile:.

**Comment by MarshallOfSound** [comment]
@cdacamar I'm sure we'll get to ++20 but we're restricted but our dependencies.  In this case this failure isn't our code rather in chromium.
