### ISSUE TITLE
Text is extra bold in Electron 3.1.9 - 3.1.12 [Mac Only]

### ISSUE THREAD

**Issue by harryi3t** [electron/electron#19340]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Affected Electron Versions:**  3.1.9 - 3.1.12
* **Operating System:** MacOS 10.14.4 (Working fine on Windows and Linux)
* **Last Known Working Electron version:** <= 3.1.8 and >= 4.0.0

### Expected Behavior
The text should render normally as it was rendering in version <= 3.1.8 and is rendering in version >= 4.0.0

### Actual Behavior
The text is looking extra bold

### To Reproduce
Just open any Electron app on the affected versions. I think the difference is *more* noticeable when having a coloured text.

![image](https://user-images.githubusercontent.com/5207331/61531508-a12ba180-aa44-11e9-8efc-f9e3db2697d6.png)

For the above screenshot, I have used Electron fiddle and the following code in the renderer.js
```html
<style>
      .sample {
        font-size: 20px;
        color: orange;
      }
</style>
<div class="sample">Sample Text</div>
```

**Comment by codebytere** [comment]
Electron `v3-1-x` is receiving security fixes only at this time in accordance with our [release line support documentation](https://electronjs.org/docs/tutorial/support#supported-versions). If this recurs on a more recent supported major line, we can revisit this issue and begin triage.
