### ISSUE TITLE
White videos on Windows 10

### ISSUE THREAD

**Issue by adammeyer** [electron/electron#19344]
### Preflight Checklist

* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**  4.2.4
* **Operating System:** Windows 10
* **Last Known Working Electron version:** n/a

### Expected Behavior
Videos to play without issue.

### Actual Behavior
We have one Windows machine that will not play mp4 videos.  The videos show as a patchy white square (see screenshot).  This only happens on this one Windows machine and I'm at a loss for ways to diagnose or resolve.

- Video card drivers are up to date
- Video files are local
- Videos play fine in Windows Media Player and Google Chrome on the same machine.
- The exact same file videos play without issue on other Windows 10 machines running Electron 4.2.4.

### Screenshots
<img width="770" alt="Screen Shot 2019-07-19 at 9 09 59 AM" src="https://user-images.githubusercontent.com/4603906/61537674-b46b4c80-aa05-11e9-80bb-4c41d9761e20.png">

**Comment by adammeyer** [comment]
This can be fixed with `app.disableHardwareAcceleration`.  https://electronjs.org/docs/api/app#appdisablehardwareacceleration

**Comment by miniak** [comment]
I wouldn't call it a fix, rather a workaround.
