### ISSUE TITLE
Catalina notarization issue

### ISSUE THREAD

**Issue by Mizzick** [electron/electron#19342]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
We start having these issues with last two releases of Catalina. 
I want to mention that only sandboxed version of application experience this issue.

```
A JavaScript error occurred in the main process

Uncaught Exception:

Error: dlopen(/var/folders/xj/d3lz5pss4gqfkfqghngc48qm0000gn/T/com.adguard.safari.AdGuard/.TC3Q7MAJXF.com.adguard.safari.AdGuard.4C1JbH, 1): no suitable image found. Did find:
/var/folders/xj/d3lz5pss4gqfkfqghngc48qm0000gn/T/com.adguard.safari.AdGuard/.TC3Q7MAJXF.com.adguard.safari.AdGuard.4C1JbH: code signature in (/var/folders/xj/d3lz5pss4gqfkfqghngc48qm0000gn/T/com.adguard.safari.AdGuard/.TC3Q7MAJXF.com.adguard.safari.AdGuard.4C1JbH) not valid for use in process using Library Validation: Library load disallowed by System Policy
/var/folders/xj/d3lz5pss4gqfkfqghngc48qm0000gn/T/com.adguard.safari.AdGuard/.TC3Q7MAJXF.com.adguard.safari.AdGuard.4C1JbH: stat() failed with errno=17

at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
at Object.Module._extensions..node (module.js:671:18)
at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
at Module.load (module.js:561:32)
at tryModuleLoad (module.js:504:12)
at Function.Module._load (module.js:496:3)
at Module.require (module.js:586:17)
at require (internal/module.js:11:18)
at bindings (/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/node_modules/safari-ext/node_modules/bindings/bindings.js:112:48)
at Object.<anonymous> (/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/node_modules/safari-ext/index.js:1:189)
```

This file `index.js` belongs to native node module, which is compiled with node-gyp and signed with:
```
codesign --verbose --force --deep -o runtime --timestamp --sign "${CODE_SIGN_IDENTITY}" --entitlements "${ELECTRON_CHILD_ENT}" "${SRC}/node_modules/safari-ext/build/Release/safari_ext_addon.node"
```

The javascript error above mostly looks like that something is wrong with this module signature, but codesign check is ok.
```
codesign -vvv --deep --strict [path]/node_modules/safari-ext/build/Release/safari_ext_addon.node: valid on disk
[path]/node_modules/safari-ext/build/Release/safari_ext_addon.node: satisfies its Designated Requirement
```

We are still not sure about proper notarization scheme for MAS builds, but it seems like we should not notarize anything before uploading to app store.

Any help would be really appreciated.

* **Electron Version:**
  * 5.0.6
* **Operating System:**
  * 10.15.x

### To Reproduce
Get v1.4.1 from MAS https://apps.apple.com/us/app/adguard-for-safari/id1440147259
Launch the app.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

![image](https://user-images.githubusercontent.com/8577533/58959145-1ac94200-87ad-11e9-89ff-b672a67bd370.png)
</details>

<details>
  <summary>Screenshot 2</summary>

![image](https://user-images.githubusercontent.com/8577533/58959165-21f05000-87ad-11e9-9a7d-6c0b26e21b35.png)
</details>

### Additional Information
Original issue:
https://github.com/AdguardTeam/AdGuardForSafari/issues/172

**Comment by semireg** [comment]
I'm also seeing this issue in our current MAS builds. I've commented on a similar issue https://github.com/electron/electron-osx-sign/issues/188, but I only have a solution for sandbox-only, or hardened-only. Not both at the same time.

This looks like the MAS app is quarantined, leading to being run in a hardened runtime. However, it's missing the entitlements to allow binaries within the ASAR to be used ("not valid for use in process using Library Validation").

It's possible that this is a Catalina bug and may be resolved in the next beta. However, I'm taking a conservative stance and aggressively trying to find a solution that lets me package with both sandbox and hardened runtime support.

**Comment by arlenyan** [comment]
@Mizzick The issue with your app might be that the `safari_ext_addon.node` binary contained in its its asar bundle is signed with `Developer ID Application: Adguard Software Limited (TC3Q7MAJXF)`.

Apple's upload process doesn't seem to traverse an asar bundle to sign any binaries it might contain. So when submitting to the Mac App Store, binaries need to be specified within the `--unpack-dir` option. This enables Apple to sign all the binaries with the proper `Apple Mac OS Application Signing` identity.

Catalina must have changed the way it validates the code signature of dlopen'd binaries of sandboxed apps.

**Comment by Mizzick** [comment]
Thanks a lot @arlenyan!
Passing `--asar.unpack=*.node` to electron-packager solved the problem.
