### ISSUE TITLE
HTTP headers are not available anymore in DevTools Network tab

### ISSUE THREAD

**Issue by paul321** [electron/electron#19359]
Hi,
We have a problem with version 4 and 5 of Electron, for ajax requests there are no headers available for requests, we want to see what headers are sent to remote server but it's not working anymore, the error we get is: Provisional headers are shown

Here is a screen shot with a fresh electron download, same thing happens with our app, this happens on Windows and Mac, Electron version 5.0.7 and tested even with 4.x

![image](https://user-images.githubusercontent.com/555502/61575803-0f21a880-aad9-11e9-8b63-bb047fc0dd4a.png)

**Comment by JLueke** [comment]
I had the same problem, but after updating electron to 6.0.10, I can see the headers now.

**Comment by electron-triage** [comment]
@paul321 Please use Electron 6.0.10 as reported in the above comment. We are no longer supporting versions older than Electron 6, per our [supported versions policy](https://www.electronjs.org/docs/tutorial/support#supported-versions)
