### ISSUE TITLE
Packaged App Starts 12 seconds on Windows 10/7 - electron 5.0.6

### ISSUE THREAD

**Issue by Qiplex** [electron/electron#19362]
Hello,

Packaged app starts insanely slow on Windows platforms with recent electron `5.0.6` and takes **12 seconds**.

I did a quick test and packaged with [electron-builder](https://github.com/electron-userland/electron-builder) [**electron-quick-start**](https://github.com/electron/electron-quick-start) app (which basically is an empty one) 

And the issue is still here. 

I was able to reproduce the issue on Windows 10 (64 bit) and Windows 7 (32 bit)

Please, kindly assist.

**Comment by Qiplex** [comment]
It seems to be related to `portable` apps. `nsis` working fine. 

/cc @develar

**Comment by develar** [comment]
1. Use electron 5.0.7 — inspector dir is not included anymore.
2. Use latest electron-builder where updated 7zip is used.

So, this issue is obsolete, for further investigation please file issue to
electron-builder issue tracker.

**Comment by MarshallOfSound** [comment]
Closing out as it's a builder issue rather than electron core and doesn't belong on this tracker

**Comment by Qiplex** [comment]
Thanks @develar! It helped. 

Info for future readers: 

Updating electron minor version from `5.0.6` > `5.0.7` helped to decrease startup time almost twice - from 12 seconds to 6 seconds of portrable version on Windows platform. 

I have used the latest version of electron-builder `21.1.1`  in previous setup so it wasn't an issue. 

Longer startup of `portable` version most likely is the default behavior of this package (?) 

So I will just use `nsis` since it starts immediately.

**Comment by develar** [comment]
> Updating electron minor version from 5.0.6 > 5.0.7 helped to decrease startup time almost twice - from 12 seconds to 6 seconds of portrable build on Windows platform.

Yes, due to Electron bug, `inspector` dir was bundled by mistake. Since IO is very slow on Windows (only Linux has excellent IO implementation), unpacking a lot of small files takes enormous time. Also, please ensure that asar is not disabled. Another way to speed-up — https://github.com/electron-userland/electron-builder/issues/3972#issuecomment-502129243

**Comment by Qiplex** [comment]
Thanks for the valuable info, @develar . I really appreciate your help with this.
