### ISSUE TITLE
Native c++ addon crashes when c++ std::filesystem used

### ISSUE THREAD

**Issue by AtiqGauri** [electron/electron#19378]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * ~~5.0.6~~ => 7.1.10
* **Operating System:** 
  *  Windows 10 (1903)
* **Last Known Working Electron version:**
  *  unknown

### Expected Behavior

my native addon perfectly works as standalone (include c++17 std::filesystem) and it should do the same when called in electron app

### Actual Behavior

When I import addon into electron app everything works fine until the statement of std:filesystem.function() arrives. After which electron gets crashed ( Blank white screen) with developer tools option disconnected. 

### To Reproduce
**EDIT:** Check this repository 
https://github.com/AtiqGauri/Electron-CPP17-filesytem-native-addon

~~https://gist.github.com/AtiqGauri/c130b0a700fd30b2a2cb4e184af327cb~~

~~`there you will find a link for native addon.`~~

~~https://gist.github.com/AtiqGauri/c130b0a700fd30b2a2cb4e184af327cb~~

~~link for native addon used with electron app
https://drive.google.com/drive/folders/1cnnoz91iY2oaD16D0tC28ey_Pp6q15Hl?usp=sharing~~
<!--
If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
~~```sh
$ git clone $YOUR_URL -b $BRANCH
$ npm install
$ npm start || electron .
```~~
-->
~~nothing special just call above native addon in basic electron app
go to fiddle link~~



### Screenshots
<!-- If applicable, add screenshots to help explain your problem. -->
![Screenshot (110)](https://user-images.githubusercontent.com/37737221/61699116-e9560700-ad57-11e9-8287-da9a9a7ed738.png)

![Screenshot (111)](https://user-images.githubusercontent.com/37737221/61699125-f115ab80-ad57-11e9-8e05-2ef26b6628cd.png)

![Screenshot (112)](https://user-images.githubusercontent.com/37737221/61699420-80bb5a00-ad58-11e9-8a7c-a0ad38dbe8ad.png)


### Additional Information
<!-- Add any other context about the problem here. -->
I have created a basic Node.js native Addon which list names of all the files in a directory through c++ 17 (std::filesystem). Their are other normal c++ function too. Everything works fine as standalone Addon/module but when I require() same Addon in electron app. The gets crashed ( Blank white screen ).  
I have enabled `nodeIntegration`
If I don't use std::filesystem function Addon than module works fine in electron.

**Comment by nornagon** [comment]
We've previously had issues with native modules built with cmake-js (though I thought those were fixed in recent versions of cmake-js). Would you mind trying to create a simple repro case using node-gyp to see if the same issue arises?

**Comment by miniak** [comment]
Also if you are reporting a crash, it would be nice to include a crash dump or call stack

**Comment by AtiqGauri** [comment]
> 
> 
> We've previously had issues with native modules built with cmake-js (though I thought those were fixed in recent versions of cmake-js). Would you mind trying to create a simple repro case using node-gyp to see if the same issue arises?

Reproduce it - https://github.com/AtiqGauri/Electron-CPP17-filesytem-native-addon
Here it is. But I am not using node-gyp as It was a mess for me to setup that thing on windows and using c++11 above version in it. That's why I had switched to cmake-js. There is source code in this repo for native addon if you want you can create node-gyp version through it. 

By they way I should mention that this native addon created by cmake-js works perfectly fine as a standalone nodejs addon. You can try it by yourself. The error only comes up when we use same addon in electron.
If we remove c++ std::filesystem function from native addon and recompile it. then we can use it normally in electron app and it works fine.

**Comment by AtiqGauri** [comment]
> 
> 
> Also if you are reporting a crash, it would be useful to include a crash dump or call stack if possible

@miniak
I am sorry, I don't know how to find it. May above git repo link will be usefull for that.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.1.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by AtiqGauri** [comment]
I tried it with ```"electron": "^7.1.10"```  but things are still same...
getting same devtools was disconnected error.

here is updated repository to reproduce bug
https://github.com/AtiqGauri/Electron-CPP17-filesytem-native-addon

**Comment by AtiqGauri** [comment]
I tried it with updated electron version 7.1.10 and things are still same...
it is showing same "devtools was disconnected" errors...

here is updated repository to reproduce bug
https://github.com/AtiqGauri/Electron-CPP17-filesytem-native-addon

**Comment by AtiqGauri** [comment]
the native addon which is not working electron app is working file when used as standalone addon
you can try by running 
```
cd Electron-CPP17-filesytem-native-addon/electron-quick-start/t-addon
npm install
node index
```

it should showing ```this is c++ filesystem function 7```
as output on command line 

but the same is not happening in electron app

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
