### ISSUE TITLE
Cannot install applications based on electron on Windows 10

### ISSUE THREAD

**Issue by rowboater** [electron/electron#19373]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
unknown
  * 
* **Operating System:**
  Windows 10 (1803)
* **Last Known Working Electron version:**
None

### Expected Behavior
Electron based apps to install on my machine correctly

### Actual Behavior
So when I try to install GitHub for Windows I get an error

This laptop does have some funny security settings on it.

Does anyone know a way around this?

I also get this issue with:
Atom, Slack & Gitkraken

### To Reproduce
Install an electron based application

### Screenshots
![image](https://user-images.githubusercontent.com/2257238/61667304-8a4daf00-acd1-11e9-8b93-ea7e25756faa.png)

**Comment by MarshallOfSound** [comment]
> I get an error

That isn't very helpful, can you share the error. 😆 

That said, closing this out as a non-electron issue until this has been triaged by the apps you mentioned and determined to be an Electron issue or you can reproduce this with the standalone electron binary.

**Comment by rowboater** [comment]
Wow ok that’s unfriendly. The error is in the screenshot. 
It’s always the same across all three apps. They all pointed me at you.

**Comment by MarshallOfSound** [comment]
@rowboater You edited in that image after my comment 😄 GitHub has an edit history

![image](https://user-images.githubusercontent.com/6634592/61667905-22c33f80-ac90-11e9-9b0d-82b22b8d55bb.png)

Regardless, can you link the GitHub Desktop issue you raised where they pointed you over here for additional context?

**Comment by shiftkey** [comment]
@MarshallOfSound @rowboater https://github.com/desktop/desktop/issues/7976

**Comment by MarshallOfSound** [comment]
Thanks @shiftkey 🙇 

That issue appears to have traced it to a Group Policy blocking the application doing _something_.  Without knowing the policy causing the issue we won't be able to do anything, I'd suggest checking the windows event log, it may have more information around which policy blocked the application.

It's probably blocking access to a certain directory or something 🤔

**Comment by 0xced** [comment]
I'm in the same situation with *funny security settings* and I'm having trouble installing GitKraken with the same error: `The application was unable to start correctly (0xc0000364)`. I monitored the GitKraken installation with [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) and discovered that the installer successfully extracted the app into `%LocalAppData%\gitkraken\app-6.3.0`. From there I was able to copy the `app-6.3.0` directory into `C:\Program Files\GitKraken` with administrator privilege and GitKraken launched successfully. 🎉

**Comment by Neustradamus** [comment]
There is a problem in several installers, there is no possibility to select the installation folder.
By default it is in %LOCALAPPDATA%, it must be replaced by %PROGRAMFILES%.

32-bit and 64-bit:
- "Program Files" on 32-bit or 64-bit OS: %ProgramFiles%
- "Program Files (x86)" for 32-bit applications on 64-bit OS: %ProgramFiles(x86)%

Important:
- The user profile must be in %APPDATA%
- The cache must be in %LOCALAPPDATA%

For example, Mozilla Firefox has:
- Install folder: %PROGRAMFILES%\Mozilla Firefox
- Profile folder: %APPDATA%\Mozilla\Firefox
- Cache folder: %LOCALAPPDATA%\Mozilla\Firefox

More informations about folders in Microsoft Windows:

1/ %PROGRAMFILES% is a folder first found in Microsoft Windows 95 and included in all later versions of Microsoft Windows that stores the software programs installed on the computer.

2/ %USERNAME%\AppData
- Local: This folder stores device-specific settings and temporary files. There is a separate %LOCALAPPDATA% environment variable for this folder that you can use in your batch files and scripts.
- LocalLow: Here, Windows mainly stores buffer data generated by various applications (Internet Explorer, Java, Adobe, etc.). It is also used by low-level access systems, for example, for your browser's temporary files when working in Protected View. This directory also cannot be moved to another computer.
- Roaming: You can transfer files from this folder to another computer. The Roaming folder stores browser data, bookmarks, etc. This directory allows users to always work with a familiar environment on any server in the Remote Desktop Services farm when using roaming profiles or user profile disks. The environment variable for this directory is %APPDATA%.
