### ISSUE TITLE
-webkit-app-region: drag have highest priority regardless the z-index.

### ISSUE THREAD

**Issue by Sombian** [electron/electron#19379]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
5.0.7
* **Operating System:**
Windows 10 (17763.615)
* **Last Known Working Electron version:**
unknown

### Expected Behavior
-webkit-app-region field should have priority property.

### Actual Behavior
-webkit-app-region: no-drag is not triggered if -webkit-app-region: drag is set although its under the element.

### To Reproduce
```html
<template>
  <div id="app-content"
    <div class="resize-handle top"/>
    <div class="resize-handle bottom"/>
    <div class="resize-handle left"/>
    <div class="resize-handle right"/>
    <div id="titlebar" class="draggable"/>
  </div>
</template>

<style>
.draggable {
  -webkit-app-region: drag;
}
.resize-handle {
  background: blue;
  width: 2.0px;
  height: 2.0px;
  position: fixed;
  -webkit-app-region: no-drag;
}
.resize-handle.top {
  width: 100%;
}
.resize-handle.bottom {
  bottom: 0px;
  width: 100%;
}
.resize-handle.left {
  height: 100%;
}
.resize-handle.right {
  right: 0px;
  height: 100%;
}
</style>
```

### Additional Information
-webkit-app-region: drag block all events hooked to it will ever goin' to get fixed?

**Comment by nornagon** [comment]
This is an OS limitation and isn't something we plan to fix.

**Comment by Sombian** [comment]
> This is an OS limitation and isn't something we plan to fix.

this is the one of most important feature to frameless app where html and css's fancy visual work can outshine others. if not planned it should by now.
