### ISSUE TITLE
6.0.0-beta.14 - Windows 10 - Window.setImmediate never run passed callback

### ISSUE THREAD

**Issue by amuzacz** [electron/electron#19384]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v6.0.0-beta.14
* **Operating System:**
  * Windows 10 Pro
* **Last Known Working Electron version:**
  * v5.0.1

### Expected Behavior
After invoking setImmediate(callback) we expect that callback will be called.

SIDE NOTE: We get this on chrome browser which dose not implement this function natively . This function is rather IE/Edge specific (https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate).

### Actual Behavior
Passed callback is never called. There is no error, Immediate object is created.

### To Reproduce
Create BrowserWindow open dev tools console and run:
```javascript
setImmediate(() => console.log('Never gets logged'))
```
### Additional Information
When we reload window location.reload() function starts to work.

**Comment by codebytere** [comment]
Not reproducible on macOS.

**Comment by codebytere** [comment]
@amuzacz this is directly resultant of the change in `nodeIntegration` to off by default in 5. 
`setImmediate` is implemented in Node.js, so it's available when Node is available in the renderer process. 

To fix this, you'll need to set:
```
    webPreferences: {
      nodeIntegration: true
    }
```
in your BrowserWindow parameters.

**Comment by amuzacz** [comment]
I have this option enabled, and yes on darvin/linux every thing is fine. Only on windows this function is dead.

**Comment by erickzhao** [comment]
![Capture](https://user-images.githubusercontent.com/16010076/61750443-45ba2600-ad5a-11e9-9a7c-47de21003067.PNG)

Unable to reproduce on Windows 10 Pro with a minimal Hello World Fiddle example on my end.

cc @amuzacz @codebytere

**Comment by amuzacz** [comment]
Sorry, I mislead you.

I didn't test this on "empty" content page. I have Ext.js in it which polyfills this function if it isn't available. I didn't tough that will have impact as source of setImmediate didn't change. So I confirm this is not a problem in electron framework, something bad is happening in loaded app.

**Comment by amuzacz** [comment]
I check this bug today, and here is the snippet that can break node event loop:
```javascript
// main.js
const {app, BrowserWindow} = require('electron');
const path = require('path');


let bootstrap = () => {
	let w = new BrowserWindow({
		show: true,
		userContentSize: true,
		width: 600,
		height: 400,
		webPreferences: {
			nodeIntegration: true
		}
	});

	w.loadURL('file://' + path.join(__dirname, 'index.html'));
       // This will break event loop
	w.webContents.send('event', {});
};

app.on('ready', bootstrap);
```
```html
<html>
<title>Electron Simple</title>
<head>
	<script type="text/javascript">
		let immediateLog = () => {
			setImmediate(() => console.log('Log only once'));
		}
	</script>
</head>
<body>
	<div>Hello world</div>
</body>
</html>
```

Then when we open dev console and type; immediateLog(); immediateLog(); we see that message is logged only once. I solved it by wrapping `webContents.send` in `setTimeout` with some delay.

But I think it would be better to get some exception if event loop is down.

**Comment by MarshallOfSound** [comment]
@amuzacz Even with that example I'm struggling to reproduce 🤔

**Comment by amuzacz** [comment]
Yes, I tried this also on Windows 10 Home (node 12.7) and it works ok. I will try to reinstall environment on Windows Pro maybe it will fix the problem.

**Comment by amuzacz** [comment]
Error still occurs. I've tested electron 6.0.1 release on windows 2008 Server and windows 10 Pro. Fork from electron-quick-start with bug replication in attachment [electron-quick-start-windows-bug.tar.gz](https://github.com/electron/electron/files/3496541/electron-quick-start-windows-bug.tar.gz)
