### ISSUE TITLE
BrowserWindow not accessible for Sharing when it has a parent or always on top

### ISSUE THREAD

**Issue by bynho** [electron/electron#19385]
* Electron version: 5.0.0
* Operating system: Windows 10

### Expected behavior

I should be able to access the BrowserView from the available windows given by the OS.  I.e. when trying to DesktopCapture, even when the BrowserView is a child of another BrowserView or when the BrowserView is set to always show on top

### Actual behavior

If the BrowserView has a parent or is set to always show on top, the BrowserView window is no longer available and does not show when querying for available windows / screens.

### How to reproduce

From your renderer process, query for available desktop capture sources:
`
desktopCapturer.getSources({ types: ['window', 'screen'] }).then(async sources => {
      console.dir(sources);
    });
`

From your main process, create a browser window with an assigned parent or with alwaysOnTop set to true

`
const browser = new BrowserWindow({
    title: "my-browser",
    parent: mainWindow,
    frame: false,
    width: 800, height: 600,
    x: 0, y: 0,
    alwaysOnTop: true 
  });
`

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.1.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
