### ISSUE TITLE
docs: distinction between setPermissionRequestHandler and setPermissionCheckHandler is unclear

### ISSUE THREAD

**Issue by bughit** [electron/electron#19405]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

https://electronjs.org/docs/api/session#sessetpermissioncheckhandlerhandler

From the documented minor differences, it's not clear why both are needed and when one should use which.

@MarshallOfSound I found that you added setPermissionCheckHandler in #13925, could you please clarify?

**Comment by MarshallOfSound** [comment]
@bughit `setPermissionRequestHandler` handles permissions requests that can be responded to asynchronously (hence the callback).  `setPermissionCheckHandler` handles permission checks that **must** be responded to synchronously.

**Comment by bughit** [comment]
I was logging both, just to understand them better in a page that wants audio and video and I was seeing media audio requests on both, PermissionRequestHandler and PermissionCheckHandler. Evidently requests for same perm type can be both sync and async. So if it's not the perm type, what differentiates async and sync requests?

**Comment by MarshallOfSound** [comment]
@bughit It's where it comes from in Chromium.  E.g. When a page calls `xxx.requestPermission()` it will fire a permission request.  If they then do `xxx.doTheThing()` it may fire a synchronous permission check to validate.

**Comment by pushkin-** [comment]
@MarshallOfSound just to double check, would you then recommend using both methods for added security? [this page](https://github.com/doyensec/electronegativity/wiki/PERMISSION_REQUEST_HANDLER_JS_CHECK) and [this page](https://www.electronjs.org/docs/tutorial/security#11-verify-webview-options-before-creation) only call out `setPermissionRequestHandler`. Or is having both redundant?
