### ISSUE TITLE
Electron 6, maximize/restore not working correctly

### ISSUE THREAD

**Issue by t57ser** [electron/electron#19423]
### Preflight Checklist
* [X ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.0-beta.15
* **Operating System:**
  * Windows 10 64bit
* **Last Known Working Electron version:**
  * 5.0.8

### Expected Behavior
The window restores its size to what it used to be

### Actual Behavior
The window is shown in the smallest size

### To Reproduce
1) Maximize Window
2) Minimize Window
3) Restore Window (click on the icon in the taskbar)
4) Unmaximize Window

### Screenshots
![grafik](https://user-images.githubusercontent.com/10595986/61781949-84f18100-ae05-11e9-8983-17edb536427f.png)

**Comment by pushkin-** [comment]
Confirmed that this is an issue in Electron 6 (stable)

**Comment by TomaszMa** [comment]
This issue is regression after cbb5164cc83ae14c16e72b199c10168fbc95240a

Potential solution for it is:

```
diff --git a/atom/browser/native_window_views_win.cc b/atom/browser/native_window_views_win.cc
index d6fd2ae58..a6033a0f9 100644
--- a/atom/browser/native_window_views_win.cc
+++ b/atom/browser/native_window_views_win.cc
@@ -419,7 +419,8 @@ bool NativeWindowViews::PreHandleMSG(UINT message,
       if (last_window_state_ == ui::SHOW_STATE_NORMAL) {
         if (consecutive_moves_)
           last_normal_bounds_ = last_normal_bounds_candidate_;
-        last_normal_bounds_candidate_ = GetBounds();
+        last_normal_bounds_candidate_ = IsMaximized() ?
+            widget()->GetRestoredBounds() : GetBounds();
         consecutive_moves_ = true;
       }
       return false;
@@ -498,6 +499,7 @@ void NativeWindowViews::HandleSizeEvent(WPARAM w_param, LPARAM l_param) {
           case ui::SHOW_STATE_MAXIMIZED:
             last_window_state_ = ui::SHOW_STATE_NORMAL;
             root_view_->SetInsets(gfx::Insets(0));
+            SetBounds(last_normal_bounds_candidate_, false);
             NotifyWindowUnmaximize();
             break;
           case ui::SHOW_STATE_MINIMIZED:


```

**Comment by whyboris** [comment]
Confirming can reproduce error within my app on current `master` after upgrading from Electron 5 to Electron 6 -- https://github.com/whyboris/Video-Hub-App

I opened a related issue #19816 -- simply minimizing and restoring a window causes the size to be (momentarily) set to the _minWidth_ and _minHeight_ specified in _new BrowserWindow_ object. 

I suspect in your case you do not have a minimum set, hence it collapses to the smallest OS-permitted-minimum (?) as shown in your screenshot.
