### ISSUE TITLE
process.uptime() returns unexpected result

### ISSUE THREAD

**Issue by MareikeTaeubner** [electron/electron#19425]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  v5.0.8
* **Operating System:**
 Microsoft Windows 10 Pro (Version: 10.0.18362 Build 18362)
* **Last Known Working Electron version:**
  unknown

### Expected Behavior
The same result node.js produces: the time the process is already running.
Output Node.js 12.7.0
```
node foo.js
2.1028718
4.1022395
6.1052112
8.1049451
```
### Actual Behavior
Electron returns some other numbers. 
Output Electron 5.0.8
```
electron foo.js 

 585175.0756366
585177.0780253
585179.0767907
585181.0769859
```

### To Reproduce
foo.js
```
function uptime() {
  console.log(process.uptime());
}

setTimeout(uptime, 2000);
setTimeout(uptime, 4000);
setTimeout(uptime, 6000);
setTimeout(uptime, 8000);
```

**Comment by DeerMichel** [comment]
Broke between v5-beta.8 and v5-beta.9. Most likely the node upgrade https://github.com/electron/electron/pull/17752 - investigating further there...
