### ISSUE TITLE
Menu visibility changes after leaving fullscreen mode on linux

### ISSUE THREAD

**Issue by yafp** [electron/electron#19426]
### Issue Details

* **Electron Version:**
  * 5.0.7
* **Operating System:**
  * Ubuntu 18.04 x64
* **Last Known Working Electron version:**
  * unknown

### Expected Behavior
Activating and then de-activating fullscreen mode should not change the visibility of the menu

### Actual Behavior
Deaktivating fullscreen mode results in a visible menu

### To Reproduce

* hide the menu
* trigger fullscreen mode
* leave fullscreen-mode

### Additional Information
Tested only on linux so far

**Comment by codebytere** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test via [fiddle](https://github.com/electron/fiddle) that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
