### ISSUE TITLE
Unhandled exception in WorkerScriptFetchInitiator::CreateScriptLoaderOnIO

### ISSUE THREAD

**Issue by michtsu** [electron/electron#19459]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
v7.0.0-nightly.20190722

* **Operating System:**
Windows 10 1903

* **Last Known Working Electron version:**
Unknown

### Expected Behavior
When starting a shared worker, the shared worker should run without encountering any unhandled exception

### Actual Behavior
Starting a simple shared worker results in an unhandled exception. This exception is thrown from WorkerScriptFetchInitiator::CreateScriptLoaderOnIO() on line 324:

```cpp
  auto resource_type =
      static_cast<ResourceType>(resource_request->resource_type);
```

The exception details:

Unhandled exception at 0x00007FF7AF887D23 in electron.exe: 0xC0000005: Access violation reading location 0x00000000000002BC.

### To Reproduce
1. Clone this fork: https://github.com/michtsu/electron
2. Enable [this](https://github.com/michtsu/electron/blob/eb6660f5341d6d7e2143be31eefec558fd866c84/spec/chromium-spec.js#L863) test
3. Run the test

**Comment by deepak1556** [comment]
This is fixed in master
