### ISSUE TITLE
Why so many renderer processes for single BrowserWindow?

### ISSUE THREAD

**Issue by dmitry-zakablukov** [electron/electron#19452]
Good day.

I'm migrating our application from Electron 1.8.2 to 5.0.7. In Electron 1.8.2 there was a single renderer process corresponding to a BrowserWindow. After migration I see seven (!) renderer processes in the task manager and only one of them is corresponding to a BrowserWindow we are creating in our application.
How can I control the number of renderer processes? What are they supposed for?

![image](https://user-images.githubusercontent.com/2607265/61876559-d416df00-aef5-11e9-9991-55190afa53be.png)

**Comment by codebytere** [comment]
@dmitry-zakablukov the logs there indicate at least two main processes, and then if you add the renderer processes and have, say, devtools open that should account for all of them.

**Comment by miniak** [comment]
site isolation?
