### ISSUE TITLE
electron-quick-start on debian _ --no-sandbox is not supported

### ISSUE THREAD

**Issue by fabien11** [electron/electron#19454]
### Issue Details
* **Electron Version:**
 "devDependencies": {
    "electron": "^5.0.8"
  }

* **git --version**
git version 2.11.0
* **node --version**
   v10.16.0
* **npm --version**
   6.9.0

* **Operating System:**
  linux debian (antiX) 

### Actual Behavior
I followed all the steps described there https://electronjs.org/docs/tutorial/first-app
and when I run 'npm start' I have the following message :
[5054:0725/163732.268279:FATAL:atom_main_delegate.cc(194)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

Thanks for help

**Comment by codebytere** [comment]
You need to run `electron --no-sandbox .`

**Comment by fapcdms** [comment]
### I have the same problem.
#### My app uses electron and vuejs.

I made the following change in the package.json file

***original***
``` json
"electron:serve": "vue-cli-service electron:serve",
```
***with changes***
``` json
"electron:serve": "vue-cli-service electron:serve --no-sandbox",
```

**Comment by cypher3107** [comment]
from where did you change these
"electron:serve": "vue-cli-service electron:serve --no-sandbox",
