### ISSUE TITLE
Silent printing not working in combination with deviceName (in v5.0.7 +)

### ISSUE THREAD

**Issue by ibra038** [electron/electron#19474]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success. 
  * #17260 Not relevant: addresses the same issue, but for a version before the pull request that supposedly fixed silent printing. is already closed.
  * #17077 Not relevant: addresses the same issue, but for an older version before pull request #19038 that should fix silent printing. 
  * #18123 Not relevant: doesn't address the same issue. Is already closed
  * #17523 A list of issues related to printing. 

### Issue Details

* **Electron Version:**
  * 5.0.7 and 6.0.0-beta.15 
* **Operating System:**
  * MacOS Mojave v10.14.4
* **Last Known Working Electron version:**
  * 3.1.11

### Expected Behaviors
According to the pull request #19038 which was merged in v.5.0.7, silent printing should work. 

&#35; | Code | Expected Behavior
------ | ----- | -------------------
1 | `webContents.print()` | Opens the print preview
2 | `webContents.print({ silent: true })` | Prints silently to default printer
3 | `webContents.print({ silent: true, printBackground: true })` | Prints silently with background to default printer
4 | `webContents.print({ silent: true, deviceName: 'Canon_MF633C_635C' })` | Prints silently to my Canon printer
5 | `webContents.print({ silent: true, deviceName: printBackground: true, deviceName: 'Canon_MF633C_635C' })` | Prints silently with background to my Canon printer

Original documentation of WebContents.print() can be found [here](https://electronjs.org/docs/api/web-contents#contentsprintoptions-callback).

### Actual Behaviors
&#35; | Actual Behavior
------ |  ---------------
1 | :white_check_mark: As expected
2 | :white_check_mark: As expected
3 | :white_check_mark: As expected
4 | :x: Nothing will happen, callback is never called
5 | :x: Nothing will happen, callback is never called

Unfortunately when providing a deviceName, nothing is send to the printer and the callback will never be called (see image of terminal logs below).

### To Reproduce

1. Clone this fork: https://github.com/ibra038/electron-quick-start
2. Run `yarn install` and `yarn start` 
3. Follow the steps on your screen

![Schermafbeelding 2019-07-26 om 12 26 15](https://user-images.githubusercontent.com/10993141/61945586-a63aa480-afa0-11e9-91a5-d9db5c93a93e.png)
![Schermafbeelding 2019-07-26 om 13 19 08](https://user-images.githubusercontent.com/10993141/61948525-53fd8180-afa8-11e9-98ee-de03aac35eee.png)

### Additional Information
For other developers that need to print silently to a predefined printer, the last known version I found to work is v3.1.11.

**Comment by misbeliever** [comment]
yeah, struggling with this issue from v3.1.11

**Comment by sarathjasrin** [comment]
This issue is not fixed yet. V6.0.0

**Comment by codebytere** [comment]
@sarathjasrin yes, i'm aware! If it had been fixed, this issue would be closed. I plan to work it on it very soon.

**Comment by codebytere** [comment]
Hey folks, got a PR up targeting master that should ensure it's fixed in v7. I won't be able to port it in its current state back to v6 and v5 owing to some intermediary changes Chromium made but i'll do my best.

**Comment by gozzoo** [comment]
Thanks @codebytere, that's very good news. Unfortunately the release of v7 is 3 months away. Lets keep our fingers crossed that we can get some fixes in any of the stable releases sooner because v3 is already getting old in the tooth.

**Comment by gozzoo** [comment]
Has this been backported to 5-0-x or 6-0-x?

**Comment by cstsortan** [comment]
Any news on fixes for cases 4 and 5 being shipped before v7?

**Comment by gozzoo** [comment]
It's trange that this issue has been closed but the fix is not avalable in any stable release.

**Comment by sarathjasrin** [comment]
@gozzoo It will available from V7. she mentioned above.

> Hey folks, got a PR up targeting master that should ensure it's fixed in v7. I won't be able to port it in its current state back to v6 and v5 owing to some intermediary changes Chromium made but i'll do my best and should hopefully be able to get it fixed in those lines too.

**Comment by gozzoo** [comment]
@sarathjasrin well, but v7 is not available yet.

My point is that this issue has been closed, but the issue actually has not been fixed, because its not available in *any* stable release. It's good to know that it will be fixed in the future version, but it is not production ready yet. And it will take quite some time for v7 to get adoption, which will come with its own set of issues, so I don't expect to be able  to use this fix before the start of next year, possible much latter. People are still strugling to upgrade to v6, which is supposed to be stable. (see https://github.com/microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Aelectron-6.0.x-update+)

Not many (if any) of the big adopters of electron use printing in their apps and there is no strong push to make printing in electron work properly. As a result it has been neglected.

I hope you see now why i'm distrubed by the promise: din't worry, it will be fixed in next version

**Comment by sarathjasrin** [comment]
@gozzoo I can understand. I'm also struggled with this issue ended up creating console application for printing in C#.
