### ISSUE TITLE
Menubar text invisible in Win10 dark mode in 6.0.0 betas

### ISSUE THREAD

**Issue by caesar** [electron/electron#19476]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.0-beta.15
* **Operating System:**
  * Windows 10 (1903)
* **Last Known Working Electron version:**
  * 5.0.8

### Expected Behaviour
The menu bar text should be legible.

Ideally, the window chrome and menu bar should be dark with light text in Dark Mode – see #18119.
Otherwise, if the menubar background is light, the text should be dark, as on previous versions of Electron.

Screenshot from Electron 5.0.8 (working):
<img width="559" alt="Screenshot 2019-07-26 at 15 47 51" src="https://user-images.githubusercontent.com/1566516/61960108-cb3d1080-afbc-11e9-8345-5a11600c91ae.png">

### Actual Behaviour
In dark mode, the menu bar stays light but the text colour changes to a light grey too, making it all but invisible.

Screenshot from Electron 6.0.0-beta.15 (invisible text):
<img width="574" alt="Screenshot 2019-07-26 at 15 34 00" src="https://user-images.githubusercontent.com/1566516/61960136-d98b2c80-afbc-11e9-9b4e-6c1ff8825c6e.png">

### To Reproduce
Open Electron in Windows 10 with dark mode enabled.

**Comment by DeerMichel** [comment]
Addressed in https://github.com/electron/electron/pull/19469.

**Comment by caesar** [comment]
Ah, great. I'd searched for issues but not PRs.

Feel free to close this if you like, or maybe best to leave until that PR is merged.

**Comment by caesar** [comment]
Closing as the above PR was merged.
