### ISSUE TITLE
cannot open new tab url in current window

### ISSUE THREAD

**Issue by goldalworming** [electron/electron#19484]
### Issue Details

* **Electron Version:**
  * 3.x
  * 4.x
  * 5.x
* **Operating System:**
  * OSX and Win32

* **Last Known Working Electron version:**
  * 2.0.18

### Expected Behavior
when user open in new tab, current webview change url to redirected url

### Actual Behavior
webview not change to redirected url, and stop in latest preview althought src attribute already changed

### To Reproduce
use my code below in any version >=3

### Additional Information
this is my code

        webview.addEventListener('new-window', (e) => {
          const protocol = require('url').parse(e.url).protocol
          if (protocol === 'http:' || protocol === 'https:') {
            this.navigateWebview(e.url,key)
          }
        })

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.1.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
