### ISSUE TITLE
electron-quick-start on debian- bug with the menu

### ISSUE THREAD

**Issue by fabien11** [electron/electron#19485]
### Issue Details

* **Electron Version:**
  "devDependencies": {
"electron": "^5.0.8"
}
* **Operating System:**
 linux debian (antiX)

* **git --version:**
git version 2.11.0

* **node --version:**
v10.16.0

* **npm --version:**
6.9.0

### Actual Behavior
I followed all the steps described at the end of this page : https://electronjs.org/docs/tutorial/first-app

the app laucnh correctly but when I click on the Menu, View or Edit for exemple, the sub menu appears and when the cursor leave this area define by the Item menu + the correspondig submenu the app quit.
For exemple If I click on Edit, the sub menu appears and if I move the cursor to View, the app quit.

I precise I launch with 'electron --no-sandbox .' otherwise it wont launch
Thanks for help

**Comment by MarshallOfSound** [comment]
This sounds like the app is crashing, can you run with the following environment variables set and post the output. 

* `ELECTRON_ENABLE_LOGGING=1`
* `ELECTRON_ENABLE_STACK_DUMPING=1`

Can you also provide more details around your OS (version, flavor, etc.)

**Comment by fabien11** [comment]
More about my os :

* **cat /proc/version**
Linux version 4.9.87-antix.1-486-smp (root@antix1) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) ) #1 SMP Tue Mar 13 12:29:54 EDT 2018
* **cat /etc/debian_version**
9.4
* **lsb_release -a**
No LSB modules are available.
Distributor ID:	antiX
Description:	antiX 17.1
Release:	17.1
Codename:	stretch
* **cat /etc/os-release**
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"


Ok with theses 2 new environnement variables, ths Behavior is the same, it crashed.
I have the following logs :

root@antix1:/home/antixh/Documents/dossier PERSO/DEV/TestElectron1/electron-quick-start# npm start

electron-quick-start@1.0.0 start /home/antixh/Documents/dossier PERSO/DEV/TestElectron1/electron-quick-start
electron --no-sandbox .

Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
[7096:0727/152443.813185:ERROR:bus.cc(396)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[7096:0727/152444.403504:INFO:CONSOLE(170)] "%cElectron Security Warning (Insecure Content-Security-Policy)", source: /home/antixh/Documents/dossier PERSO/DEV/TestElectron1/electron-quick-start/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js (170)
Received signal 11 SEGV_MAPERR 0000fffffffc
#0 0x00000297664f (/home/antixh/Documents/dossier PERSO/DEV/TestElectron1/electron-quick-start/node_modules/electron/dist/electron+0x251564e)
#1 0x0000028e0a12 (/home/antixh/Documents/dossier PERSO/DEV/TestElectron1/electron-quick-start/node_modules/electron/dist/electron+0x247fa11)

[...]

#47 0x0000b5b7d286 (/lib/i386-linux-gnu/libc-2.24.so+0x18285)
#48 0x0000009f1ab3 (/home/antixh/Documents/dossier PERSO/DEV/TestElectron1/electron-quick-start/node_modules/electron/dist/electron+0x590ab2)
  gs: 00000033  fs: 00000000  es: 0000007b  ds: 0000007b
 edi: 00000000 esi: 09b6d378 ebp: bfe0eec8 esp: bfe0eeb0
 ebx: 072ec83c edx: 09b6d4f0 ecx: 071dd248 eax: 071dcfbc
 trp: 0000000e err: 00000005  ip: 03a2dd80  cs: 00000073
 efl: 00210297 usp: bfe0eeb0  ss: 0000007b
[end of stack trace]
Calling _exit(1). Core file will not be generated.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 start: `electron --no-sandbox .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-quick-start@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-27T13_24_46_232Z-debug.log


Here it is! Now I don't have access to the root folder to see the log file

**Comment by erickzhao** [comment]
Same symptom as: https://github.com/electron/electron/issues/18436

**Comment by jkleinsc** [comment]
Fixed via #19257
