### ISSUE TITLE
Web Bluetooth: `navigator.bluetooth.requestDevice` returns immediately if user cancels dialog early

### ISSUE THREAD

**Issue by daumling** [electron/electron#19489]
### Preflight Checklist

*  I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
*  I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
*  I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.8
* **Operating System:**
  * Mac OS Mojave and WIndows 10
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
`navigator.bluetooth.requestDevice` should scan for devices if called repeatedly.

### Actual Behavior
`navigator.bluetooth.requestDevice` returns immediately if called repeatedly and no `select-bluetooth-device` events have been emitted during a previous call. Error: User cancelled.

### Additional Information
Not sure if this is a feature request. It is certainly undesired behavior.

I have implemented a BT selection dialog (https://www.npmjs.com/package/electron-webbt-dialog). If the user cancels the dialog before a device has been detected, `navigator.bluetooth.requestDevice` thinks that the user canceled, and never leaves that state; any further attempt to call `navigator.bluetooth.requestDevice` returns immediately with the same error.

I suspect this is because the callback supplied with `select-bluetooth-device` is never called, because that event was never fired. The UI cannot tell `navigator.bluetooth.requestDevice` that it cancelled properly.

I would suggest that `navigator.bluetooth.requestDevice` emits a `select-bluetooth-device` event immediately with an empty device list so the main process knows the callback, and can inform `navigator.bluetooth.requestDevice` appropriately if the user canceled the dialog before a BT device has been detected.

**Comment by daumling** [comment]
It would be even better to have an additonal event `select-bluetooth-start` with a callback to call to end the selection process.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.1.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by TerrapinSoftware** [comment]
Still present in 8.0.1

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by bierzorutas** [comment]
Problem is still present ! you can not cancel a bluetooth request and ask for a second device .
