### ISSUE TITLE
Hermes Javascript Engine

### ISSUE THREAD

**Issue by jeremistadler** [electron/electron#19486]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
The v8 engine is big in terms of disk size and that makes electron apps big to download and store.

### Proposed Solution
The Hermes javascript engine might be a better fit for most electron apps as for its much smaller disk footprint and precompiled at build time javascript bundles for fast app start.

What would it need to bring Hermes to the desktop? I think its only built for android right now.

### Additional Information
https://facebook.github.io/react-native/blog/2019/07/17/hermes
https://code.fb.com/android/hermes/

**Comment by MarshallOfSound** [comment]
So firstly this would be basically impossible, node.js and chromium are heavily tied to V8 as is the module ecosystem of node.js.  But if that impossibility wasn't enough of a reason here are some actual numbers.

https://bellard.org/quickjs/bench.html

Hermes is a whole **1mb** smaller V8 (with rounding it could be less).  That, and hermes is anywhere between 10x and 30x **slower** than V8 depending on the benchmark being run.  This would be catastrophic for app performance.
