### ISSUE TITLE
BrowserView (sandbox enabled) webContents 'new-window' event preventDefault don't stop Electron from create popup

### ISSUE THREAD

**Issue by khoaakt** [electron/electron#19499]
### Preflight Checklist

* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.

### Issue Details

* **Electron Version:**
  *  5.0.8 / 6.0.0-beta.15 
* **Operating System:**
  *  Windows 10 (1809) / macOS 10.14.6
* **Last Known Working Electron version:**
  *  Unknown

### Expected Behavior

Electron shouldn't create new window when event.preventDefault().
### Actual Behavior

As mentioned here [https://electronjs.org/docs/api/web-contents#event-new-window](url), Electron shouldn't create new window when event.preventDefault() but it isn't when set sandbox=true in webPreferences.
### To Reproduce

Gist: [https://gist.github.com/khoaakt/0d5dabad991de4d14dc09beb63c35325](url)
Load it in Electron Fiddle.

### Screenshots

![f](https://user-images.githubusercontent.com/6000592/62024722-3591c300-b200-11e9-978e-df74c5a423ae.gif)

### Additional Information

Nope.

**Comment by MarshallOfSound** [comment]
You are using `remote` to do this which means the event is firing asynchronously over IPC.  `event.preventDefault()` has to be called synchronously inline with the event being emitted in the main process so this example will never work.  Move the handler to the main process and it will work just fine 👍
