### ISSUE TITLE
Unable to open 'web-contents.js'

### ISSUE THREAD

**Issue by chenfengyanyu** [electron/electron#19496]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.6
* **Operating System:**
  * macOS 10.14
* **Last Known Working Electron version:**
  * none

### Expected Behavior
ipcMain and ipcRenderer can communication with each other

### Actual Behavior
Unable to open 'web-contents.js' 

### To Reproduce
Renderer.js:
```
ipcRenderer.send('asynchronous-message', 'ping');
ipcRenderer.on('asynchronous-reply', (event, arg) => {
      console.log(arg) // prints "pong"
})
```
main.js
```
const { ipcMain } = require('electron');
const speedTest = require('speedtest-net');
const test = speedTest({maxTime: 5000, log: true});

ipcMain.on('asynchronous-message', (event, arg) => {
  console.log(arg) // prints "ping"
  if(arg === 'ping') {
    test.on('data', data => {
      event.reply('asynchronous-reply', 'pong');
      // event.reply('asynchronous-reply', data);
    })
    test.on('error', err => {
        event.reply('asynchronous-reply', err);
    });
  }
})
```

### Additional Information
Unable to open 'web-contents.js': A system error occurred (ENOTDIR: not a directory, stat '/Users/jartto/Documents/project/kael/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js').

please help me，this drive me crazy，thanks～

**Comment by codebytere** [comment]
This fiddle works without incident: https://gist.github.com/18d636e4aa8affb0872c2081113a76fb.

I recommend you double check the way that your app is packaged, as this isn't an issue with Electron itself.
