### ISSUE TITLE
Is it possible to download an application and install it on user's system? 

### ISSUE THREAD

**Issue by alirezavlz** [electron/electron#19491]
Hi There,
I have an issue, I developed an application based on electron for Mac and Windows platforms, The problem is at the first it was a basic app but now we have more features, so i decided to use Squirrel target for Windows, but now I decided to migrate to NSIS target because of the features like removing appData/myApp on uninstalling and ..., I searched about auto updaters in different versions and noticed that Squirrel version is not supporting other auto updaters, So I got and idea maybe it is possible to download new version with NSIS and then install it on user's system on the current app, it's kind of a trick because we have a lot of live users so we don't want to say or inform them to go and download our app again!
Thanks

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
