### ISSUE TITLE
window.open unable to set title

### ISSUE THREAD

**Issue by guanyong1993** [electron/electron#19497]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.8
* **Operating System:**
  * Windows 10 (1803)
* **Last Known Working Electron version:**
  * none

### Expected Behavior
The title can be changed.

### Actual Behavior
The title appears blank.

### To Reproduce
main process

```javascript
mainWindow = new BrowserWindow({
    show: true,
    webPreferences: {
        nativeWindowOpen: true
    }
});
```

render process

```javascript
var child= window.open('', '', 'height=480,width=320');
child.document.title = 'my title';
```

### Additional Information
- `nativeWindowOpen` attributes are important.
- At first I thought it was a chrome problem, but then I found that chrome was normal.
- For version 4.0 of electron, You can only set the title after the onload event. But 5.0.8 onload event not work.
- I'm trying to speed up the window rendering of electron, window.open URL param set to empty, Opening window is fast, so I have to do it.

**Comment by erickzhao** [comment]
Able to reproduce on macOS Mojave on my machine. To me, the issue seems to be tied with the event listeners not triggering. None of the `console.log` calls are being logged on my dev console as soon as `v5.0.0-beta-1`, but were working just fine in `v4.2.8`.

Snippet:
```
// renderer.js
const child = window.open('', '', 'height=480,width=320');

child.addEventListener('load', () => {
    console.log('This should log in the dev console');
    console.log(child.document.title);
    child.document.title = 'Testing';
    console.log(child.document.title);
});
```

**Comment by zarubond** [comment]
The problem is still persistent event on latest Electron 6.0.7

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
