### ISSUE TITLE
When using a worker: nw_path_close_fd Failed to close guarded necp fd 55 [9: Bad file descriptor] crash

### ISSUE THREAD

**Issue by alexzielenski** [electron/electron#19519]
I am working on a visual studio code language server. And I'm running into continuous crashes when I try to use web workers.  There error in my system log is `nw_path_close_fd Failed to close guarded necp fd 55 [9: Bad file descriptor] crash`. I am reporting here because the stack trace on my crash log points to electron.framework.

### Issue Details

* **Electron Version:**
  * 4.2.7
* **Operating System:**
  * OS X 10.4.5

### Expected Behavior
I simply run the following to experience predictable crashes:

```
let worker = new Worker(require.resolve(...), {
	workerData: 0
});
```

I was able to reproduce on a fresh project. 

```
$ git clone https://github.com/microsoft/vscode-extension-samples
$ cd vscode-extension-samples/lsp-sample
$ yarn install
```

I then edited `extension.ts` to add `---experimental-worker` to the launch flags, and modified `ValidateTextDocument` in `server.ts` to have the line from above:

```
let worker = new Worker(require.resolve('x.js'), {
	workerData: 0
});
```

I don't think it matters what the content of 'x.js' is, for my purposes it contained:

```
const {
  Worker, isMainThread, parentPort, workerData
} = require('worker_threads');
console.log('doodly')

if (isMainThread) {
	console.log('mainthread')
  function dosomething(script) {
    return new Promise((resolve, reject) => {
      const worker = new Worker(__filename, {
        workerData: script
      });
      worker.on('message', () => {
		  console.log('hallo')
	  });
      worker.on('error', () => {
		  console.log('GOODBYTE')
	  })
      worker.on('exit', (code) => {
        if (code !== 0)
          reject(new Error(`Worker stopped with exit code ${code}`));
      });
    });
  };
  dosomething("hello")
  module.exports =  dosomething


} else {
	console.log('worker1')
  const script = workerData;
  parentPort.postMessage("message");
}
```

Now that this is set up `yarn compile` and use the built into `launch.json` configs to run the extension in vscode. Viewing the `Output` pane of the language server extension shows that the node process is exiting immediately.

### Actual Behavior
Immediate crash on a call to some C++ code on invocation to `WorkerImpl`.

### Additional Information
I've attached a crash log with a stack trace

[Code Helper_2019-07-29-144659_Alexanders-iMac.crash.txt](https://github.com/electron/electron/files/3444452/Code.Helper_2019-07-29-144659_Alexanders-iMac.crash.txt)

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by alexzielenski** [comment]
I’m not using this in a project anymore so I have no interest in it getting fixed. However there definitely is enough information in the ticket for a salaried individual to see if the problem reproduces still, assuming you  guys at all had an interest in publishing a stable product.
