### ISSUE TITLE
My app is crashing on start-up when packaged on Electron v6

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#19511]
In Electron v6 two new Helper applications were added to the macOS application bundle.  These helpers live alongside `Electron Helper.app` as `Electron Helper (Renderer).app` and `Electron Helper (Plugin).app`.  These helpers **must** be shipped with your packaged application if they are not your application will crash on startup.

In order to support these new helpers, you need to be on the latest version of whatever packaging system you use.  Information for the major packaging systems is included below.

### Electron Packager

`electron-packager@14.0.4` includes the changes required to make Electron v6 work correctly.  You should upgrade to this version or higher.

### Electron Forge

`electron-forge` depends on `electron-packager` internally to just ensure you have the latest version of `electron-packager` and you'll be fine.

### Electron Builder

`electron-builder` does not currently support these new helpers, please follow [this isue](https://github.com/electron-userland/electron-builder/issues/4104) to track support for these helpers

#### My app still crashes though?

If your application bundle includes these helpers applications and your app **still** crashes you are almost certainly running into a different issue, please raise a new issue for your crash instead of piling onto this one 👍

**Comment by zlab** [comment]
the same question on mac 10.13

**Comment by AbbetWang** [comment]
i upgrade Electron Packager to 14.0.3, but still exit

**Comment by HaNdTriX** [comment]
### 🆕 Electron Builder (v21.2.0)

Electron Builder now supports  these new helpers:

* https://github.com/electron-userland/electron-builder/releases/tag/v21.2.0
* https://github.com/electron-userland/electron-builder/pull/4111

```bash
$ npm update electron-builder@latest --save-dev
```

**Comment by caesar** [comment]
Worth noting that if your app crashes on start up *only in dark mode on Windows*, you're probably running into #19468.

**Comment by gaodeng** [comment]
these new helper apps are using invalid bundle identifier.

**Comment by caesar** [comment]
They all seem to share a bundle identifier, which seems strange, but I don't know if it's actually invalid?

**Comment by gaodeng** [comment]
@caesar  When submitted via the Application Loader, it gives these error:
```
ERROR ITMS-90277: "Invalid Bundle Identifier. The application bundle contains a tool or framework Electron Helper (GPU) [fm.moon.apps.desktop.player.pkg/Payload/Moon FM.app/Contents/Frameworks/Moon FM Helper (GPU).app] using the bundle identifier 'fm.moon.apps.desktop.player.helper.(GPU)', which is not a valid bundle identifier." 

ERROR ITMS-90277: "Invalid Bundle Identifier. The application bundle contains a tool or framework Electron Helper (Plugin) [fm.moon.apps.desktop.player.pkg/Payload/Moon FM.app/Contents/Frameworks/Moon FM Helper (Plugin).app] using the bundle identifier 'fm.moon.apps.desktop.player.helper.(Plugin)', which is not a valid bundle identifier."

ERROR ITMS-90277: "Invalid Bundle Identifier. The application bundle contains a tool or framework Electron Helper (Renderer) [fm.moon.apps.desktop.player.pkg/Payload/Moon FM.app/Contents/Frameworks/Moon FM Helper (Renderer).app] using the bundle identifier 'fm.moon.apps.desktop.player.helper.(Renderer)', which is not a valid bundle identifier."

```

**Comment by danielweck** [comment]
I upgraded from Electron5 to 6 (electron-builder to the latest version), and my app DMG which is code-signed and notarized seems to continue to function normally ... (no problems with bundle identifier).

**Comment by MarshallOfSound** [comment]
@gaodeng that bundle identifier is being generated by _something_ in your own build system, it is not the bundle ID these helpers normally ship with

**Comment by gaodeng** [comment]
@MarshallOfSound  Thank you for pointing me the direction of the issue. I am using the latest electron-builder. I will create an issue there.

**Comment by gaodeng** [comment]
@danielweck My app works fine too, but when I upload it to the Mac App Store with the application loader, I get these errors.

**Comment by danielweck** [comment]
Thanks @gaodeng I now understand that the error is specific to Application Loader, which I do not need at the moment (the DMG / App is not distributed via the Mac App Store).

**Comment by mabbotts9797** [comment]
I seem to be encountering this same issue with both .zip & DMG on Mac.

The app works and runs correctly with `electron-forge start` but will crash when attempting to start the produced/packaged app.

I am running `electron@6.0.1`, and the latest`electron-builder` and `electron-packager`. If it helps, I am on Mac OS Mojave v10.14.4.

**Comment by NikFranki** [comment]
@gaodeng you can try this
Enter the fm.moon.app and view contents

Find Moon FM Helper (GPU).app, Moon FM Helper (Plugin).app, Moon FM Helper (Renderer).app

To view the contents, open the info.plist file and point the Bundle identifier to fm.moon.apps.desktop.player.helper

Then submit and try again

Hope useful

**Comment by Aarbel** [comment]
same issue here. I'm also using `afterSign` with `electron-builder` which doesn't work with v6, so downgraded to v5

**Comment by gaodeng** [comment]
@Aarbel check out this  https://github.com/electron-userland/electron-builder/issues/4151#issuecomment-520663362  for the workaroud

**Comment by danielweck** [comment]
> I'm also using `afterSign` with `electron-builder` which doesn't work with v6

I do not think this statement is correct. Please let me know if I am wrong, but: my Electron6 DMG is signed and notarized (via `afterSign`) successfully by `electron-builder` (latest version), and the app runs without issues. 

However, there seems to be a problem when using the Application Loader to upload the app to the Apple Mac Store (I haven't tried that myself).

**Comment by Aarbel** [comment]
> @Aarbel check out this [electron-userland/electron-builder#4151 (comment)](https://github.com/electron-userland/electron-builder/issues/4151#issuecomment-520663362) for the workaroud

@gaodeng thanks a lot ! I'm looking for stable workaround, i don't have the time to raw edit files each time i build

**Comment by danielweck** [comment]
@Aarbel
This fix:
`helper.CFBundleIdentifier = `${helperBundleIdentifier}.${postfix.replace(/[^a-z0-9]/gim,"")}`;`
...can be implemented in your `package.json` as a `sed` shell command, specifically for your MacOS `electron-builder` script, for example, a `pre**` task in your build workflow, like `preelectron-builder-macos` or `prepackage-app-macos` (whatever your existing script name is).
Any taker to write the `sed` command? ;)

**Comment by Aarbel** [comment]
hate that but you're true ;) thanks a lot

**Comment by ash67** [comment]
I am having a similar issue. My electron app build successfully but it crashes right I lunch it. I m using the below versions:

electron: 6.0.10
electron-builder: 21.2.0
Mac version: 10.14.6
app notarized: no

I checked logs in console.app. Here are some of the errors 

```Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Volumes/myapp/myapp.app/Contents/, NSFilePath=/Volumes/my app/my app.app/Contents/PlugIns, NSUnderlyingError=0x7fd4f2c57660 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}```

```
CODE SIGNING: process 7544[My App]: rejecting invalid page at address 0xce885fc2000 from offset 0x0 in file "<nil>" (cs_mtime:0.0 == mtime:0.0) (signed:0 validated:0 tainted:0 nx:0 wpmapped:1 dirty:0 depth:0)
```

```
Unable to load Info.plist exceptions (eGPUOverrides)
```

@gaodeng I tried to apply your below fix, but I had no luck. so if you please guide me, that would be highly appreciated.

https://github.com/electron-userland/electron-builder/issues/4151#issuecomment-520663362

**Comment by Aarbel** [comment]
I think i solved the issue by bringing right entitlement files (electron-builder was also reading package.json build, not electron-builder custom config file)

**Comment by stephendwolff** [comment]
I've a related issue: #20405, where the .app bundle works ok until the helper apps are signed (and entitlements applied). Then the .app bundle crashes on startup. Without signing (and entitlements applied), Application Loader complains that the helper apps do not have the sandbox entitlement, but the .app bundle does run at least!

**Comment by ash67** [comment]
@Aarbel thanks for your suggestion. 
@stephendwolff : I think you will need to notarize your app. I had a similar issue where I was able to build and sign. However, it would crash right after you open it. It fixed after notarized my app. The below guides help me a lot:

https://help.apple.com/xcode/mac/current/#/dev033e997ca

https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/

https://medium.com/@TwitterArchiveEraser/notarize-electron-apps-7a5f988406db

**Comment by stephendwolff** [comment]
@ash67 re notarizing - i've read some of those guides, but as far as i am aware notarizing is *only* for apps which are distributed using disc images (ie dmg) rather than the MacAppStore (mas), which is what i'm having a problem with. Also, I'm developing an app for a 3rd party (ie a client), and we both have Apple Developer accounts (as companies). I'm an 'admin' on their account, but cannot create the 'Developer ID' certificates on that account necessary for notarizing. So it looks like notarizing is for developers who distribute their own apps and not those of clients! It's impossible to get the correct Developer ID 'team', ie that which matches your client otherwise.

**Comment by lincolnthree** [comment]
For me, this is still happening on Windows and Mac when bundling with Electron builder 21.2.0. It works fine when running unpackaged via electron-webpack (dev mode).

**Comment by stephendwolff** [comment]
I gave up on Electron tbh, and ended up re-writing it in Swift as it is mac only for now

**Comment by lincolnthree** [comment]
@stephendwolff I wish I had another option :) Unfortunately I don't have the human-power to do native development. Electron has worked very well so far, and the fact that VSCode and other major apps are built with it gives me hope, but some issues like this really take the wind out of my sails.

**Comment by stephendwolff** [comment]
@lincolnthree, yes, i didn't want to give up on Electron, but having gone round this a number of ways, i ended up with the Swift route. 

Have you tried building your app with Electron v5?

**Comment by lincolnthree** [comment]
I have. Transparency is broken in that version so I can't use it, but it did seem to run fine.

**Comment by perryy** [comment]
> I've a related issue: #20405, where the .app bundle works ok until the helper apps are signed (and entitlements applied). Then the .app bundle crashes on startup. Without signing (and entitlements applied), Application Loader complains that the helper apps do not have the sandbox entitlement, but the .app bundle does run at least!
> 
> Also - there is another helper app - (GPU) - now. Not sure if that is relevant or not.

I have exactly the same issue. Is there any chance, that it will be fixed? Or any workaround?

**Comment by lincolnthree** [comment]
I have not found a workaround at this time.

**Comment by JCBsystem** [comment]
this i how i do it 

make sure you have done the fix mentioned above
`helper.CFBundleIdentifier = ${helperBundleIdentifier}.${postfix.replace(/[^a-z0-9]/gim,"")};`

then i build it with electron-builder (only one output)
and re sign it with 
this script

--------------------
`
APP="XXX"
COMPANY_DEVELOPER_ID="XXX"
CURRENT_PATH='.'
 FOLDER="mas"
APP_PATH="$CURRENT_PATH/$FOLDER/$APP.app"
 RESULT_PATH="$CURRENT_PATH/$FOLDER/$APP-Publish-Ready.pkg"

 APP_KEY="3rd Party Mac Developer Application: $COMPANY_DEVELOPER_ID"
INSTALLER_KEY="3rd Party Mac Developer Installer: $COMPANY_DEVELOPER_ID"
 CHILD_PLIST="$CURRENT_PATH/entitlements.mas.inherit.plist"
PARENT_PLIST="$CURRENT_PATH/entitlements.mas.plist"
LOGINHELPER_PLIST="$CURRENT_PATH/entitlements.mas.loginhelper.plist"

FRAMEWORKS_PATH="$APP_PATH/Contents/Frameworks"

codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Electron Framework"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Libraries/libnode.dylib"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper.app/Contents/MacOS/$APP Helper"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper.app/"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (GPU).app/Contents/MacOS/$APP Helper (GPU)"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (GPU).app/"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (Plugin).app/Contents/MacOS/$APP Helper (Plugin)"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (Plugin).app/"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (Renderer).app/Contents/MacOS/$APP Helper (Renderer)"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (Renderer).app/"

codesign -s "$APP_KEY" -f --entitlements "$LOGINHELPER_PLIST" "$APP_PATH/Contents/Library/LoginItems/$APP Login Helper.app/Contents/MacOS/$APP Login Helper"
codesign -s "$APP_KEY" -f --entitlements "$LOGINHELPER_PLIST" "$APP_PATH/Contents/Library/LoginItems/$APP Login Helper.app/"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$APP_PATH/Contents/MacOS/$APP"
codesign -s "$APP_KEY" -f --entitlements "$PARENT_PLIST" "$APP_PATH"

productbuild --component "$APP_PATH" /Applications --sign "$INSTALLER_KEY" "$RESULT_PATH"
`



save the script as sign.sh 
then 
`sudo sh sign.sh` 
to run it 

this is not my script i just modified it
hope it helps someone

this is for the MAS but you can still use the .app or remove productbuild

**Comment by DominikLevitsky** [comment]
For some unknown reasons I was able to build, sign and notarize a .dmg with the latest electron-builder 22.1.0, and the setting **"hardenedRuntime": false**, yes **false**. Before this, we were not able to launch our app att all, getting the EXC_BAD_ACCESS error, though it was successfully notarized, too. Maybe this info will help someone.

**Comment by MarshallOfSound** [comment]
Closing out, this issue has served it's purpose :+1:

**Comment by belloyang** [comment]
I was able to solve this SIGTRAP error crash issue by forcing electron-forge to use electron-packager@14.2.1 for packaging. however, the packaged app failed to load resource with error:  net::ERR_NOT_IMPLEMENTED and failed to load a module. has anyone encountered the same issue?
