### ISSUE TITLE
display add "name" attribute

### ISSUE THREAD

**Issue by dengyaolong** [electron/electron#19524]
I found that display structure not support display.name , and sometimes needs to know display brand like "SAMSUNG" or "SONY" ...etc, so it's there any way to get the display name?

**Comment by codebytere** [comment]
Unfortunately no: we inherit from Chromium's [display](https://cs.chromium.org/chromium/src/ui/display/display.h?q=display&sq=package:chromium&l=17) which has no concept of that at all.
