### ISSUE TITLE
App Crashes with $APP Helper.app

### ISSUE THREAD

**Issue by Wilsonilo** [electron/electron#19520]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.8
* **Operating System:**
  * macOS 10.14.6

### Expected Behavior
App should be able to run after codesign

### Actual Behavior
After running electron-packager the app works, if i codesign everything EXCEPT $APP Helper.app and/or $APP Helper.app/Contents/MacOS/$APP Helper app still works, if i codesign any of those two app crashes.
Also app launcher asks me to codesign other files like Frameworks or it rejects me.

### To Reproduce
Created a repo to be able to reproduce.
https://github.com/Wilsonilo/TraycoinMXLite
Just use npm install to get everything you need, then you can try package-mac to get the app (it should run)
Then you can check my bash file inside /release-builds/app-build.sh there are several ways i've tried to codesign to see where are my errors, you can also see the entitlements in the same folder.
Again, apps works until i run:

codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper.app"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper.app/Contents/MacOS/$APP Helper"

Here is the log from Console:
Process:               TrayCoinMXLite Helper [28278]
Path:                  /Users/USER/*/TrayCoinMXLite.app/Contents/Frameworks/TrayCoinMXLite Helper.app/Contents/MacOS/TrayCoinMXLite Helper
Identifier:            TrayCoinMXLite Helper
Responsible:           TrayCoinMXLite Helper [28278]
5   traycoinmxlite.net.wilsonmunoz	0x000000010b743905 0x10b742000 + 6405
       0x10b742000 -        0x10b77aff7 +traycoinmxlite.net.wilsonmunoz (0) <D387E90A-06A5-3CCE-8D3F-CE48526FACB3> /Users/USER/*/TrayCoinMXLite.app/Contents/Frameworks/TrayCoinMXLite Helper.app/Contents/MacOS/TrayCoinMXLite Helper
       0x10b788000 -        0x10b7a3fff +com.github.Squirrel (1.0 - 1) <E4398068-33D3-3A00-9DBE-5ACC9B022501> /Users/USER/*/TrayCoinMXLite.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel
       0x10b7ca000 -        0x10b82dff7 +org.reactivecocoa.ReactiveCocoa (1.0 - 1) <701B20DE-3ADD-3643-B52A-E05744C30DB3> /Users/USER/*/TrayCoinMXLite.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/A/ReactiveCocoa
       0x10b8a7000 -        0x10b8bbfff +org.mantle.Mantle (1.0 - ???) <31915DD6-48E6-3706-A076-C9D4CE17F4F6> /Users/USER/*/TrayCoinMXLite.app/Contents/Frameworks/Mantle.framework/Versions/A/Mantle
       0x10bc31000 -        0x111de4f07 +com.github.Electron.framework (5.0.8) <507C902D-03BA-3195-A32A-C325628424F3> /Users/USER/*/TrayCoinMXLite.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
       0x112589000 -        0x11280afe7 +libffmpeg.dylib (0) <5AB84A10-1627-3C9C-8671-065B476B33F2> /Users/USER/*/TrayCoinMXLite.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib

**Comment by MarshallOfSound** [comment]
If the app is only crashing it after you codesigned it with custom entitlements you are missing entitlements or you provided an invalid set of entitlements.  I recommend using `electron-osx-sign` to codesign your app.

This is not an issue with Electron rather a user-side build configuration issue so I'm going to close this out

**Comment by Wilsonilo** [comment]
Entitlements are fine, i've used the one on Documentation, but thanks i'll give it a shot on electron-osx-sign:

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.app-sandbox</key>
    <true/>
    <key>com.apple.security.inherit</key>
    <true/>
  </dict>
</plist>`
