### ISSUE TITLE
app.dock.bounce no longer has a default bounce type

### ISSUE THREAD

**Issue by nghiepit** [electron/electron#19522]
Hi all,

I just upgraded to `6.0` and `TypeError: Insufficient number of arguments.`

**Comment by MarshallOfSound** [comment]
Looks like a refactor caused the `bounce` implementation to lose its old default value --> https://github.com/electron/electron/blob/4ccd6d59002e46cecee0237c4ef58323ad6b4017/lib/browser/api/app.js#L63-L65

We should provide a default value in the native `DockBounce` impl
