### ISSUE TITLE
Printing: add support for automatic height detection / single page PDFs

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#19532]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Under some scenarios, especially where there's some side-by-side content, having the printed PDF split up into multiple pages can mess up the content a bit, so it would be better to have an option for printing everything into a single page having automatic height, basically removing any page breaks.

### Proposed Solution

[`printToPDF`](https://electronjs.org/docs/api/web-contents#contentsprinttopdfoptions-callback) already supports a `pageSize` option, but both dimensions must be provided as numbers. It'd be great if `height` could also be set to `'auto'` and calculated automatically to fit in a single page.

Alternatively a new, more explicit, `singlePage` option or something could be added.

### Alternatives Considered

I'm not sure what alternatives I could adopt, perhaps I could print to PDF, count how many pages have been outputted and print to PDF again this time calculating manually the required height of the document. If this even works it would be a performance issue (printing twice), and it probably won't be very reliable (one has to precisely compute the height, which when considering margins may be tricky to do correctly).

### Additional Information

Screenshot of a PDF where this is a problem:

<img width="527" alt="Screen Shot 2019-07-30 at 15 04 00" src="https://user-images.githubusercontent.com/1812093/62131421-77436c00-b2db-11e9-8469-0ae6a0a9e42e.png">

**Comment by codebytere** [comment]
Closing as we adhere to https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF - please look to the options defined therein and if you have a suggestion for more options to add, that can be surfaced upstream to the DevTools protocol team within Chromium.
