### ISSUE TITLE
BrowserView.setBounds blocks subsequent setBounds when using current Bounds' values

### ISSUE THREAD

**Issue by krausekai** [electron/electron#19536]
### Issue Details

* **Electron Version:**
  * 6.0.0
* **Operating System:**
  * Windows 10 (1809)
* **Last Known Working Electron version:**
  * 5.0.8

### Expected Behavior

Applying ``BrowserView.setBounds`` should always take affect, even if the bounds are the same as the current values of the ``BrowserView``'s bounds, and not block subsequent ``setBounds``.

### Actual Behavior

As of Electron 6.0 (compared to 5.0.8), setting the bounds of a ``BrowserView`` to its current ``x``, ``y``, ``width``, and ``height`` prevents the ``BrowserView`` from changing its bounds on a subsequent call.

### To Reproduce

Using the Electron quickstart repo:

> git clone https://github.com/electron/electron-quick-start

Edit the quickstart ``main.js`` file to enable ``nodeIntegration``:

```
// Create the browser window.
mainWindow = new BrowserWindow({
	width: 800,
	height: 600,
	webPreferences: {
	  preload: path.join(__dirname, 'preload.js'),
	  nodeIntegration: true
	}
})
```

Once started, open the Developer tools, and enter into the console:

```
var bounds = { x: 0, y: 0, width: 480, height: 480 }
var boundsXChange = { x: 240, y: 0, width: 480, height: 480 }
var boundsHeightChange = { x: 0, y: 0, width: 480, height: 482 }

var { BrowserView, BrowserWindow } = require('electron').remote;
var view = new BrowserView();
BrowserWindow.getAllWindows()[0].addBrowserView(view); // alternatively: .getFocusedWindow()
view.setBounds(bounds);
view.webContents.loadURL('https://electronjs.org/');
```

Create the above view multiple times with the following combinations, to see the bug:

```
// BUG: VIEW DOES NOT UPDATE X POSITION
view.setBounds(bounds);
view.setBounds(boundsXChange); // subsequent call blocked

// BUG: VIEW DOES NOT UPDATE X POSITION UNTIL CALLED TWICE
view.setBounds(bounds);
view.setBounds(boundsXChange); // subsequent call blocked
view.setBounds(boundsXChange);

// CORRECT BEHAVIOR: VIEW DOES UPDATE X POSITION
view.setBounds(boundsXChange);

// CORRECT BEHAVIOR: VIEW DOES UPDATE X POSITION
view.setBounds(boundsHeightChange);
view.setBounds(boundsXChange);
```

**Comment by erickzhao** [comment]
Can confirm that this occurred as early as `6.0.0-beta` for both Linux and Windows.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
