### ISSUE TITLE
electron 6: app.getPath('logs') throws error on Windows

### ISSUE THREAD

**Issue by MareikeTaeubner** [electron/electron#19543]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.0
* **Operating System:**
  * Microsoft Windows 10 Pro (10.0.18362 Build 18362)
* **Last Known Working Electron version:**
  * 5.0.8

### Expected Behavior
Function returns the path to the logs directory like electron 5.0.8 does:
```
C:\Users\taeubnerm\AppData\Roaming\Electron\logs
```

### Actual Behavior
Function throws an error:
```
Error: Failed to get 'logs' path
    at App.<anonymous> (D:\workspace-js\scribble\index.js:10:26)
    at App.emit (events.js:205:15)
```

### To Reproduce
```
const { app } = require("electron");

app.on("ready", () => {
  try {
    const logsPath = app.getPath("logs");
    console.log(logsPath);
  } catch (e) {
    console.error(e);
  }
});
```
`app.getPath('userData')` worked fine so it does seem like a logs specific problem.

### Additional Information

May be related to #15877 but I'm not sure, since this is on Windows.

**Comment by DragDay7** [comment]
You should call `app.setAppLogsPath()` as https://github.com/electron/electron/pull/17841 stated I believe.

**Comment by codebytere** [comment]
@MareikeTaeubner if you read our breaking changes notes you'll see that that's the case: no default log path is set becuase that created issues with portability so you need to call `app.setAppLogsPath()` first. I'll be backporting a fix shortly so that a more descriptive error is throw.

**Comment by MareikeTaeubner** [comment]
@DragDay7 @codebytere Ah, I see. Thank you very much for explaining. I seem to have misunderstood this in the release notes and the documentation (sorry about that). Thank you for adding a more descriptive error message for people like me ^^"

**Comment by LefterisJP** [comment]
@codebytere Hey guys, I also came across this issue.

When reading the docs one can be lead to assume that it's sage to call `app.getPath("logs")` due to the following entry in the [documentation](https://electronjs.org/docs/all#appgetpathname):

> If app.getPath('logs') is called without called app.setAppLogsPath() being called first, a default log directory will be created equivalent to calling app.setAppLogsPath() without a path parameter.
