### ISSUE TITLE
Menu roles "zoomin" and "zoomout" do nothing

### ISSUE THREAD

**Issue by Joelman111** [electron/electron#19559]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version: 5.0.8**
* **Operating System: Windows 10 (17763) **

### Expected Behavior
For the default menu options "Zoom in", "Zoom out", and "Actual Size" (which have the roles "zoomin", "zoomout", and "resetzoom", respectively), I expect them to zoom my app.

### Actual Behavior
They take no action whatsoever. No zooming in or out. However, zoom is still properly affected by manually running webFrame.setZoomFactor(x).

### To Reproduce
Just created a most basic electron app (just loads a single page that says "Tab" in h1 tags).
Zoom does not work. Check out my Electron Fiddle to see what I mean:

https://gist.github.com/bf259939ce78c089f21294de95844b95

**Comment by javan** [comment]
See also https://github.com/electron/electron/issues/18745#issuecomment-517307966

**Comment by EricGeigerQ** [comment]
Confirmed this behavior in Electron 6.0.2. Menu roles "zoomin", "zoomout", and "resetZoom" do not work.

However, in Windows 7 and Windows 10, the default keys "Ctrl + Shift + =" will work to execute a Zoom In. The other default key combinations do not work, though.

**Comment by EricGeigerQ** [comment]
I re-tested this issue against Electron 6.0.10 and the zoom-related Menu roles, and their keyboard combinations, all appear to be working again!

**Comment by RICKROSSWIFEINGRIDE** [comment]
ELECTRONIC COCK ROACH

**Comment by electron-triage** [comment]
@Joelman111 
Closing this as it is reported as fixed in v6.0.10 in the above comment. Please upgrade to Electron 6 or higher as we are no longer supporting versions older than Electron 6. See our [supported versions policy](https://www.electronjs.org/docs/tutorial/support#supported-versions)
