### ISSUE TITLE
Degrade to unsandboxed mode in unpackaged apps on Linux

### ISSUE THREAD

**Issue by nornagon** [electron/electron#19550]
Electron v5 enabled mixed-sandbox mode by default, which means that on some Linux distributions, the `chrome-sandbox` helper must be setuid root in order for Electron to launch successfully. We don't set this permission automatically during `npm install` because doing so would require root access. While we do not wish to automatically degrade to non-sandboxed mode in production when this situation is detected, it would be expedient to do so during development, preferably with a big hard-to-ignore warning printed to the console warning that the app will fail to boot when packaged, and instructions on how to set the correct permissions.

Ref #17972

**Comment by nornagon** [comment]
@p3x-robot Please file an issue against whatever you're using to create AppImages.

**Comment by vladimiry** [comment]
@p3x-robot electron itself works but there is a matter of proper package preparing, ie electron-builder at the moment doesn't support the case out of the box (but can be done with custom scripts, repackaging stuff). There are also at least 2 workarounds, see the previous messages for details.

**Comment by nornagon** [comment]
This issue is for a specific task (automatic degradation in unpackaged mode), please continue to use #17972 to discuss the core issue.

**Comment by pronebird** [comment]
There is no point in doing this, because when developing it's easy to pass a `--no-sandbox` flag. Degrading the sandbox under certain conditions sounds like creating even more confusion for developers that would likely stumble upon inconsistent behaviour when in development and production.

**Comment by nornagon** [comment]
People seem to be managing just fine without this, so I'm going to close the issue.
