### ISSUE TITLE
crashed  EXCEPTION_ACCESS_VIOLATION_READ

### ISSUE THREAD

**Issue by yssmile** [electron/electron#19565]
### Issue Details

* **Electron Version:**
  * 5.0.6 

* **Operating System:**
  * Windows 6.1.7601 x64 

* **Last Known Working Electron version:**
  * Not Sure

### Expected Behavior

Not Crash
### Actual Behavior

Crash
### To Reproduce
I do not know why my App not crash on my computer, but some of my user crashed.

### Screenshots

this is the crash detail
![image](https://user-images.githubusercontent.com/7445891/62294658-0a2c0400-b49e-11e9-9875-b3be37b02a10.png)
![image](https://user-images.githubusercontent.com/7445891/62297053-064eb080-b4a3-11e9-9df5-a4052bcfbe86.png)

**Comment by codebytere** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment. If there is no follow-up within 10 days, this issue will be closed.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
Closing as dup of https://github.com/electron/electron/issues/19592.

**Comment by skourismanolis** [comment]
@yssmile I'm also experiencing the same problem. It's happening randomly (and scarcely) for over a year now. Did you somehow find a way to fix, or reduce the issue?

**Comment by jontonsoup** [comment]
I have a symbol dump of this error: 

[ca072907b566448f970946ca66cc3a1c-symbolicated.crash.zip](https://github.com/electron/electron/files/4624025/ca072907b566448f970946ca66cc3a1c-symbolicated.crash.zip)

**Comment by sonamgupta-kiwi** [comment]
@yssmile @skourismanolis  I m also experiencing the same problem. Did you people fix it?

**Comment by skourismanolis** [comment]
@sonamgupta-kiwi It hasn't happened since, we've upgraded to various electron versions (currently on 7.x) so I suppose some update must have fixed it...

**Comment by SentoxAIO** [comment]
Getting the same error on the newest version of Electron (12.0.7)

**Comment by yssmile** [comment]
![image](https://user-images.githubusercontent.com/7445891/123192717-0e1fff80-d4d6-11eb-92d5-6f87a5c6e100.png)
try this，set resizable like this.It seems worked for me and did not see bug report in Sentry!

**Comment by yssmile** [comment]
![image](https://user-images.githubusercontent.com/7445891/123192932-71119680-d4d6-11eb-91c3-6ad95c944a35.png)

try this，set resizable like this.It seems worked for me and did not see bug report in Sentry!

**Comment by jurkog** [comment]
@yssmile Did that actually fix it?

**Comment by joanx** [comment]
@yssmile , bumping - we are also experiencing this issue, wondering how you identified the `resizable` param as the culprit.
