### ISSUE TITLE
Unable to open the electron app(v5.0.8) in linux by double clicking.

### ISSUE THREAD

**Issue by shubhamyelekar** [electron/electron#19563]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.8
* **Operating System:**
  * Ubuntu 18
* **Last Known Working Electron version:**
  * 3.1.0

### Expected Behavior
App should open in linux by double clicking

### Actual Behavior
Not opening on double click

### To Reproduce
Double click on the app in linux . It works from terminal, but not from file manager.

### Additional Information
There is an existing bug for 4.x version. (#15406) . I know it is issue with file manager not able to identify the file as executable, but with 6.0.0 getting released, just wanted to know if there is any plan to fix this issue from electron side. Wanted to know this information to plan for our future releases. Any update on this issue will be helpful.

**Comment by MarshallOfSound** [comment]
@shubhamyelekar As per https://github.com/electron/electron/issues/15406#issuecomment-435582734 this is a bug in the `file` tool when identifying `PIE` executables.  There is nothing for us to fix, we won't be removing or disabling `PIE` as it is a security feature
