### ISSUE TITLE
Windows 10 - Failed at the electron@6.0.0 postinstall script

### ISSUE THREAD

**Issue by iskyd** [electron/electron#19562]
I'm trying to install electron@5.0.8 on my windows 10 machine.

`npm install electron --save-dev`

this is the error:

> npm ERR! file C:\windows\system32\cmd.exe;
> npm ERR! path C:\windows\system32\cmd.exe;
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn C:\windows\system32\cmd.exe;
> npm ERR! electron@5.0.8 postinstall: `node install.js`
> npm ERR! spawn C:\windows\system32\cmd.exe; ENOENT
> npm ERR!
> npm ERR! Failed at the electron@5.0.8 postinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\matti\AppData\Roaming\npm-cache\_logs\2019-08-01T08_02_07_143Z-debug.log

No additional information is provided in the log file.

Also tried to delete node_modules and:
```
npm cache clean --force
npm install electron
```

but the same error is thrown.

**Comment by MarshallOfSound** [comment]
`ENOENT` means it couldn't find or execute the binary it's trying to run.  In this case `node install.js` (the binary there is `node`).

Is `node` available on your system PATH?

**Comment by MarshallOfSound** [comment]
Also FWIW I just double checked and all my windows machines can install it fine so this is something specific to your set up

**Comment by iskyd** [comment]
@MarshallOfSound it seems node is available in my system PATH.
```
node --version
v10.16.0
```

**Comment by mUtterberg** [comment]
I'm able to install Electron 6.0.0 on my Windows 10 machine, as well. Could it be a permissions issue? https://stackoverflow.com/questions/38458118/nodejs-error-spawn-c-windows-system32-cmd-exe-enoent

**Comment by iskyd** [comment]
@mUtterberg thanks for the suggestion it was the semicolon after C:\Windows\System32\cmd.exe environment variable. Holy crap.

**Comment by dimaslanjaka** [comment]
Disabling UAC before install electron, worked for me
