### ISSUE TITLE
Error popups when apps would normally call app.makeSingleInstance() events

### ISSUE THREAD

**Issue by axfelix** [electron/electron#19571]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 2.0.18
* **Operating System:**
  * Windows 7 and 10

### Expected Behavior
No error; `app.makeSingleInstance()` handler fires as normal.

### Actual Behavior
Electron applications throw what looks like a bootstrap error when a user double-clicks on their desktop shortcut when they're already running.

### To Reproduce
Include the usual trimmings in main.js:

```
if(require('electron-squirrel-startup')) return;
require('update-electron-app')();
...
```

Also handle checking if the app is already running:

```
var shouldQuit = app.makeSingleInstance(function(commandLine, workingDirectory) {
  notifier.notify({"title" : "Radiam", "message" : "Radiam is already running."});
});
```

Package with https://github.com/electron-userland/electron-installer-windows, and install, then try clicking on the app's desktop shortcut after it's already running. The `app.makeSingleInstance()` event is handled, but there is also an Electron error popup.

### Screenshots
https://user-images.githubusercontent.com/252047/61984911-52898480-afbb-11e9-85ff-372abe90b3c9.png

### Additional Information
The Squirrel folks seem to think this is not specific to them: https://github.com/Squirrel/Squirrel.Windows/issues/1517

**Comment by MarshallOfSound** [comment]
> 2.0.18

Electron 2 and 3 are EOL, please upgrade to a newer version of Electron (the latest stable is 6.0.0) and this issue will probably have been fixed.  Closing out as it was raised on an EOL version of Electron
