### ISSUE TITLE
Devtools don't open when project located in network mapped folder on Windows (6.0.0)

### ISSUE THREAD

**Issue by zloybest** [electron/electron#19589]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
v6.0.0
* **Operating System:**
  Windows 10
* **Last Known Working Electron version:**
5.0.6

### Actual Behavior

When project sources located in the network mapped folder DevTols don't open (nor from code, nor from menu).

### To Reproduce
Install electron@6.0.0 in the network mapped folder, start electron, try to open DevTools.

**Comment by nehbit** [comment]
I'm having the same problem, but on Mac, and it's not loaded from a network mapped folder. I cannot open devtools in any way whatsoever. I just upgraded from 5.0.8.

**Comment by jjustin3** [comment]
I, too, am having an issue where DevTools will not open on Win10. Using Electron Fiddle, I can successfully open DevTools for v6 but once exporting that project (or using electron-quick-start), DevTools fails to open. I tried deleting all userData folders related to the application, clearing the cached Electron zips, and even copied the v6 Electron files from Electron Fiddle to my app's node modules. Nothing worked. Oddly enough, this occurs for all beta 7 versions but v5 works just fine. Had someone else test this out on their computer and it worked fine on v6 for them. This leads me to believe that something changed with my setup that causes v6 to not kick off DevTools correctly. Possibly the Chrome version bump?

@nehbit - did you end up getting this working on your end?

**Comment by nehbit** [comment]
No, likewise I've downgraded to Electron 5.x.x, where we'll likely remain for the foreseeable future.

**Comment by jjustin3** [comment]
I'm going to continue investigating on my end. Packaging the app up produces working DevTools, so I believe some configuration on my computer is causing the issue. My fear is pruning everything and, possibly, re-imaging for something trivial.

Last question for you - are you able to get DevTools working by setting the DevTools webContents? E.g. [docs example](https://electronjs.org/docs/api/web-contents#contentssetdevtoolswebcontentsdevtoolswebcontents)

This seems to work for me although it feels hacky considering the problem is isolated to me.

**Comment by nehbit** [comment]
We haven't tried that. No devtools is a hard show-stopper, so once we confirmed that is happening, we just rolled back our whole update process.

**Comment by jjustin3** [comment]
So, it turns out my issue was the terminal I was using. Was running into this problem when using hyper.js as my terminal but everything works fine when switching over to Git Bash. Very, very odd issue. I doubt this is y'all's issue but maybe this will help someone.

**Comment by Paerhati** [comment]
Wow I was having the worst problems and could not open the devtools no matter what I did.
It seems that running **npm start** from an administrator level CMD or Powershell prompt results in not being able to open the developer tools on my Window build.

**Comment by jjustin3** [comment]
@Paerhati - I think you are correct. I discussed my findings here if you haven't seen it: https://github.com/electron/electron/issues/20069

@nehbit - you may find use in this comment if the user was able to figure things out (could be similar to what you are doing): https://github.com/electron/electron/issues/20069#issuecomment-563202815

**Comment by Qazzian** [comment]
I've found the same problem.
My normal dev environment is Linux and I have a win 10 VM for testing.
I've setup a network share to point to my linux dev directory and have been running electron app fine from there.
We recently upgraded electron from version 4.x to 7.x and I that's when the dev tools problem started. Copying the files into my home directory fixes it.

**Comment by tomsaunders-code** [comment]
Same issue. Devtools will not open in the following scenario.

Windows 10 1703
Called from mainWindow.webContents.openDevTools() or Menu within electron or hotkeys
electron 7.1.10 | 7.1.11 | 7.1.12 | 8.0.0
running electron in development. ie. npm run electron -> electron .
**Source files are located on network storage over SMB**
When source files are moved to C: drive. Works as expected, popping the devtools.

**Comment by vvildcard** [comment]
Same issue with Node.js 12.13.0, Chromium 80.0.3987.158, Electron 8.2.0, Windows 10 1909. 

Reproduced by mapping source files (located on local disk) to X:\ drive via \\localhost\C$\path\

## Workaround:
### Replace: 
app.whenReady().then(createWindow)

### With: 
let win = null
let devtools = null
app.once('ready', () => {
  win = new BrowserWindow()
  devtools = new BrowserWindow()
  win.loadFile('index.html')
  win.webContents.setDevToolsWebContents(devtools.webContents)
  win.webContents.openDevTools({ mode: 'detach' })
})

**Comment by starpit** [comment]
we also see this: in electron 7.3.3 in the windows 10 enterprise test VM.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
