### ISSUE TITLE
webContents.savePage is not saving the html file provided in the path

### ISSUE THREAD

**Issue by KannanPSomeswaran** [electron/electron#19587]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
when using webContents.savePage the html file is not getting created instead filename_files folder is created and no files are displayed under the folder

* **Electron Version:** 6.0.0
  * 
* **Operating System:** windows 10
  * 
* **Last Known Working Electron version:**
  * 

### Expected Behavior

Expected to save the browser page i opened in the provided path.

### Actual Behavior

only folder is getting created without any files in it.
Getting "Page was saved successfully." log in console.

### To Reproduce

const {app, BrowserWindow} = require('electron')
const path = require('path')
let win

function createWindow () {
  // Create the browser window.
  win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js')
    }
  })

win.loadURL('https://github.com')

win.webContents.on('did-finish-load', async () => {
    win.webContents.savePage('c:/electron/tmp/test.html', 'HTMLComplete').then(() => {
      console.log('Page was saved successfully.')
    }).catch(err => {
      console.log(err)
    })
  })
win.on('closed', function () {
    win = null
  })
}

### Additional Information
I am trying electron for first time, I have not used it before. They code i used is almost replicated from electron documentation.

**Comment by holem** [comment]
Facing the same on MacOS. Got
`(node:45972) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Insufficient number of arguments.`

But this works just fine (without `async`):
```
win.loadURL('https://github.com');
win.webContents.on('did-finish-load', function() {
  win.webContents.savePage('/tmp/test.html', 'HTMLComplete', function(error) {
    if (!error)
      console.log("Save page successfully");
  });
});
```

**Comment by rebootcode** [comment]
@holem 

Try below, it should work on "Mac", but this won't work on Windows:

```
window.loadURL('https://github.com');
window.webContents.on('did-finish-load', async () => { 
        window.webContents.savePage("savePage.html", 'HTMLOnly').then(() => { 
            console.log('Page was saved successfully.') 
        }).catch(err => { 
            console.log(err) 
        }); 
    }); 
```

**Comment by rebootcode** [comment]
@codebytere - bug exists even for electron 9.x for windows platform.

**Comment by jacopomazzoni** [comment]
facing the same problem on win 10, attached is the relevant code to reproduce:

`const { BrowserWindow, app } = require('electron')

app.whenReady().then( _ =>{
  const win = new BrowserWindow({ width: 800, height: 600 })

  win.loadURL('https://github.com');
  let contents = win.webContents;

  contents.on('did-finish-load', _=> {
      
      let pathF = './out/test.html';

      contents.savePage(pathF, 'HTMLOnly').then(() => {
        console.log('Page was saved successfully at ' + pathF)
      }).catch(err => {
        console.log(err)
      })

  });

  contents.on('did-fail-load',_=>{
    console.log('fail');
  });

});`

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
