### ISSUE TITLE
Win: app.clearRecentDocuments does not work

### ISSUE THREAD

**Issue by dospolov** [electron/electron#19588]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
app.clearRecentDocuments does not work on Windows.

* **Electron Version:**
  * 5.0.8
* **Operating System:**
  * Windows 10 pro; build 1903
* **Last Known Working Electron version:**
  * 

### Expected Behavior
List of recent documents should be cleared

### Actual Behavior
List of recent documents continues to accumulate

### To Reproduce
Try `app.clearRecentDocuments();` on Windows

### Screenshots
![image](https://user-images.githubusercontent.com/670682/62343120-307b8f00-b4f2-11e9-853e-a8aac23b8ecd.png)
![image](https://user-images.githubusercontent.com/670682/62343111-20fc4600-b4f2-11e9-8277-189fe6f0a69b.png)

**Comment by codebytere** [comment]
@dospolov when was the last time this worked?

**Comment by dospolov** [comment]
@codebytere I'm new to electron, so I don't know ¯\_(ツ)_/¯

**Comment by dospolov** [comment]
Issue is not fixed :(
electron version: 6.0.3

**Comment by codebytere** [comment]
@dospolov i think this may be an issue with your app packaging or the way it's interfacing with roles and recent documents - this was tested to work on Windows 10 🤔

**Comment by dospolov** [comment]
@codebytere I've checked source code of Electron Builder, and I haven't found any interactions with roles
