### ISSUE TITLE
Transparent window will not work when manually open the devtool

### ISSUE THREAD

**Issue by legolaserea** [electron/electron#19591]
I set a window as transparent window in the BrowserWindow options by
`      frame: false,
     transparent: true,`
But it will not work when i manually open the devTools.
I don't want to disable the devTools in the webPreferences options, how can i solve it?

**OS: Windows 10
      Electron ✌️ 6.0.0**

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).

**Comment by miniak** [comment]
Check https://github.com/electron/electron/blob/master/docs/api/web-contents.md#contentsopendevtoolsoptions, you can pass `mode` in `options` to make it detached
