### ISSUE TITLE
network serviceification followup

### ISSUE THREAD

**Issue by nornagon** [electron/electron#19602]
Since #19488, the network service is enabled and the old path has been deleted. Some features are broken as a result and will need to be fixed before 8.0.0. This is a tracking issue for those features.

- [x] webRequest API (zcbenz)
- [x] service workers on file protocol (#20132)
- [x] session.clearAuthCache - tests (#20015)
- [x] session.getBlobData (#20041)
- [x] session.setUserAgent (#20014)
- [x] custom standard schemes / registerSchemesAsPrivileged
- [x] Rewire Login Handler from NetworkDelegate into ProxyingURLLoaderFactory
- [x] fix 'login' event not firing on net requests

cc @deepak1556 @jkleinsc @zcbenz

**Comment by zcbenz** [comment]
I'm putting my name on the tasks that I'm working on, in case of any duplicate work.
