### ISSUE TITLE
ipcRenderer undefined on renderer process.

### ISSUE THREAD

**Issue by Sombian** [electron/electron#19607]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.8
* **Operating System:**
  * windows 10 latest
* **Last Known Working Electron version:**
  * unknown

### Expected Behavior
can be emitted.

### Actual Behavior
as title, ipcRenderer is undefined on renderer process.

### To Reproduce
background.js
```js
const { ..., ipcMain } = require("electron");
...
window.webContents.send("event"); //this works.
...
ipcMain.on("event", () => { //this works.
 console.log("zero");
});
...
```
try.js
```js
import { ipcRenderer } from "electron";

export default class example {
   constructor() {
      ipcRenderer.on("event", () => { //TypeError, can not read property "on" of undefined.
         console.log("1st");
      });
   }
}
ipcRenderer.on("event", () => { //TypeError, can not read property "on" of undefined.
   console.log("2nd");
});
```

### Additional Information
ive found [this](https://forum.safedev.org/t/problem-using-nodejs-tutorial-code-in-other-electron-apps/1675) also, assume mine isnt the first case.

**Comment by MarshallOfSound** [comment]
Please provide a clonable example based on `electron-quick-start` that reproduces this issue

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by Sombian** [comment]
Not enough information? Ive provided all codes that are necessary to cause this issue. I dont get it sir.

**Comment by miniak** [comment]
@Sombian you haven't provided all the information, such as how you are creating the `BrowserWindow` instance. `nodeIntegration` it disabled by default in Electron 5+, therefore you cannot use `require` outside of the preload script unless you enable it explicitly.
