### ISSUE TITLE
Can't build older Electron versions

### ISSUE THREAD

**Issue by char** [electron/electron#19616]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 3.0.2
* **Operating System:**
  * macOS 10.14.5
* **Last Known Working Electron version:**
  *  5.0.8

### Expected Behavior
After running `gclient sync --with_branch_heads --with_tags` I expect it to complete successfully so that I'm able to run the `gn gen` command as described in the [documentation for 3.0.2
](https://github.com/electron/electron/blob/v3.0.2/docs/development/build-instructions-gn.md)
### Actual Behavior
After running `gclient sync --with_branch_heads --with_tags` I get this in the terminal:
```
2>Syncing projects:   1% ( 1/51)
[2:06:09] Still working on:
[2:06:09]   src
Syncing projects: 100% (79/79), done.

________ running 'src/libchromiumcontent/script/apply-patches' in '/Users/veritas/election'
error: patch failed: src/v8/src/inspector/BUILD.gn:79
error: src/v8/src/inspector/BUILD.gn: patch does not apply
build_gn.patch failed to apply
Error: Command 'src/libchromiumcontent/script/apply-patches' returned non-zero exit status 1 in /Users/veritas/election
```

### To Reproduce
Run the commands provided in the [documentation for building 3.0.2](https://github.com/electron/electron/blob/v3.0.2/docs/development/build-instructions-gn.md). I replaced the url with my fork of the electron 3.0.2 branch
```sh
mkdir electron-gn && cd electron-gn
cat > .gclient <<-GCLIENT
solutions = [
  {
    "url": "https://github.com/char/electron3",
    "managed": False,
    "name": "src/electron",
  },
]
GCLIENT
gclient sync --with_branch_heads --with_tags
```
### Additional Information
Building the latest electron works fine. I'd like to build older versions.

**Comment by MarshallOfSound** [comment]
Electron 3 is EOL and not supported.

It also doesn't use gclient or GN to build, the documentation for building electron varies between Electron 3 and Electron 4, check the docs for the version you're trying to build

**Comment by char** [comment]
I understand that Electron 3 is no longer supported but it'd be nice to know how to build this version for something I'm experimenting with.

The build instructions I followed (and linked) are for 3.0.2
