### ISSUE TITLE
Preload Script Cannot Access non-Electron Dependancies

### ISSUE THREAD

**Issue by moloch--** [electron/electron#19614]
### Issue Details

* **Electron Version:**
  * v6.0.0
* **Operating System:**
  * MacOS 10.14
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior

Per documentation window preload scripts should be able to access `node_modules` even when `nodeIntegration` is disabled.

### Actual Behavior

Modules other than `electron` cannot be included/required

##### preload.js
```javascript
const { ipcRenderer } = require('electron');
const rxjs = require('rxjs');
```

##### console output
```
VM11 sandbox_bundle.js:2885 Unable to load preload script: src/preload/script.js
(anonymous) @ VM11 sandbox_bundle.js:2885
VM11 sandbox_bundle.js:2886 Error: module not found: rxjs
```

**Comment by MarshallOfSound** [comment]
You are running that preload script in a sandboxed renderer which will not load from node_modules.

It isn't actually nodejs, sandboxed preloads are just normal JS scripts run during the preload phase.

You should use a tool like webpack to bundle your preload script and it's dependencies into a single file to use as your sandboxed preload script
