### ISSUE TITLE
Reading from ASAR sub dir fails

### ISSUE THREAD

**Issue by Askill** [electron/electron#19617]
It seems fs.readdir() only ever reads from the base of the asar dir, ignoring the provided path:

    const directoryPath = path.join(__dirname, '/backgrounds/');
    console.log(directoryPath);
    fs.readdir(directoryPath, function (err, files) {
        //handling error
        if (err) {
            return console.log('Unable to scan directory: ' + err);
        } 
        console.log(files);
        mainWindow.webContents.send('addBackground', files);
    });
![image](https://user-images.githubusercontent.com/16598120/62422403-8434d680-b6b2-11e9-92b0-62a3a9d4290c.png)

![image](https://user-images.githubusercontent.com/16598120/62422409-a0387800-b6b2-11e9-86f9-7190c04ee861.png)

**Comment by miniak** [comment]
@Askill which versions of Electron are affected?

**Comment by codebytere** [comment]
Closing due to no response.
