### ISSUE TITLE
browserview on mac

### ISSUE THREAD

**Issue by itayit** [electron/electron#19618]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
 6.0.0
* **Operating System:**
 mac os 10.13
* **Last Known Working Electron version:**

### Expected Behavior
 1. create a browser view that is out of bounds of the window (i.e. window is 20 width, 20 height, view is 500 width, 500 height), then resize the window to contain the view. the view should be visible and responsive

### Actual Behavior
 2. the browser view portion that was initially out of the window cannot receive keyboard/mouse inputs. this happens only on mac, not on ubuntu/windows

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
