### ISSUE TITLE
Electron app with accessibility permissions freeze macOS (v.4.2.5)

### ISSUE THREAD

**Issue by AirFusion45** [electron/electron#19621]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v4.2.5
* **Operating System:**
  *  macOS 10.15 Beta (Build: 19A512f)
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior

Electron application is supposed to mute speakers when it detects an AD playing in Spotify.

### Actual Behavior

Electron application mutes speakers, however, it also freezes macOS for about a minute.

### To Reproduce

1. Clone the code on Github https://github.com/AirFusion45/Spotify-Muter. (Sorry the code is a bit messy)
2. Allow the app accessibility permissions 
3. Sign in with Spotify when launched. 
4. Play a song until an ad comes up. Then the app should try to mute the speakers, however, it just freezes the whole macOS system.

### Screenshots
 /

### Additional Information

Referenced issues: https://github.com/electron/electron/issues/17314, this should not happen even if the app is not signed... Is there a way to prevent freezing without paying Apple $100/yr?

**Comment by MarshallOfSound** [comment]
If this is only occurring for an unsigned app it's probably gatekeeper doing additional validation of your app on first launch.

Not much else we can do here, if you comment on the issue you linked with the trace that @nornagon requested we might be able to point you in a direction but if this is code signing / gatekeeper related theirs nothing we can do.

This conversation should continue on the linked issue

**Comment by sourabhverificient** [comment]
This is occurring for Signed app as well , Do we have any fix on this ?
