### ISSUE TITLE
macOS screen capture thumbnail drag and drop

### ISSUE THREAD

**Issue by seulgi0711** [electron/electron#19624]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Is there an event handler for dragging and dropping macOS screen capture thumbnail.

![image](https://user-images.githubusercontent.com/7961148/62468379-e552cc00-b7d0-11e9-8182-a08a898e0f0d.png)

### Proposed Solution

Some applications already have the event handler. So please implement the event handler.

**After screen capture**
![image](https://user-images.githubusercontent.com/7961148/62468806-e46e6a00-b7d1-11e9-8b5c-3037ab45cc3f.png)

**Drag the thumbnail to application**
![image](https://user-images.githubusercontent.com/7961148/62468878-0ff15480-b7d2-11e9-903f-b28496c5613f.png)

**Comment by MarshallOfSound** [comment]
Please track http://crbug.com/978484 upstream 👍
