### ISSUE TITLE
Does not send https referrer to http sites

### ISSUE THREAD

**Issue by VladimirMerk** [electron/electron#19622]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.8, 6.0.0
* **Operating System:**
  * Windows 10 (1803)

### Expected Behavior
The https referrer is sent to http sites, and is available in the variables document.referrer and $ _SERVER ['HTTP_REFERER']

### Actual Behavior
When sending a https referrer to any http site, the referrer is empty

Referrer is empty [Bad]
   urlOptions = {
       httpReferrer: "https://somesome.com"
   }
   win.loadURL ('http://www.whatismyreferer.com/', urlOptions) // HTTP URL`

Referrer is https://somesome.com [Good]
   urlOptions = {
       httpReferrer: "https://somesome.com"
   }
   win.loadURL ('https://www.whatismyreferer.com/', urlOptions) // HTTPS URL

Referrer is http://somesome.com [Good]
   urlOptions = {
       httpReferrer: "http://somesome.com"
   }
   win.loadURL ('http://www.whatismyreferer.com/', urlOptions) // HTTP URL

### To Reproduce

```sh
$ git clone https://github.com/VladimirMerk/electron-https-referrer && cd electron-https-referrer
$ npm install
$ npm start
```

**Comment by nornagon** [comment]
This is [expected behavior](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy).

**Comment by VladimirMerk** [comment]
But this does not work with the heading Referrer-Policy: unsafe-url
It also does not work with the meta tag <meta name = "referrer" content = "unsafe-url"> or <meta name = "referrer" content = "always">
[https://yadi.sk/i/RzLiHsYxxMtvFA](url)
