### ISSUE TITLE
Is it possible to use custom protocols on Linux?

### ISSUE THREAD

**Issue by nehbit** [electron/electron#19643]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
Hey there,

I maintain a cross platform Electron app. I've done a couple hours of search across the internet on whether this is functional or not, to no avail. The issue is that custom protocol linking works on Mac OS, and on Windows, however there is no information on whether it does on Linux.

- In Mac, ```open-url``` event is raised, which allows me to take it from there.
- In Windows, the OS tries to spawn a second instance, and the ```second-instance``` event is raised. I look at the args of that second instance, which contains the URL that I need to process, and I take it from there.
- In Linux, the OS tries to spawn a second instance, however the URL is not in the args provided to that second instance. ```Open-url``` event doesn't fire either (since it's Mac-only). 

So, how do you get the URL that I need to use in Linux? I have no problem with the protocol links working, and hitting the app. So the association of the link to the app is just fine, it's just that I cannot seem to get the link itself so that I can do something with it. 

The code handles Mac OS and Windows just fine, so I'm specifically asking about how to get Linux to work, or if this is a supported feature.

This app is running as a Snap package, packaged by Electron-builder.

Thanks a lot!

### Proposed Solution
- Clarification on whether Electron supports custom protocols on Linux
- [If so,] Documentation on how to get the URL from protocol links in Linux environments

**Comment by Kilian** [comment]
Hi Nehbit, Indeed,`open-url` is only for mac and linux and windows need to read the args on the `second-instance` call (or first instance, if the app's not open)

On Linux (Ubuntu, in my case), my app correctly gets the `args` on a second instance when instantiated from a custom protocol call, with the information in the args I expect so I can confirm that works.

**Comment by nehbit** [comment]
Thanks a lot! It appears that on Ubuntu, I do not get the deep link path as the arg, but on Windows, it does work. 

I'll try to narrow this down, I'll circle back once I try the app as unpacked runtime and/or as deb. As you suspected, this might be about Snap and its sandbox.

**Comment by MikeJerred** [comment]
@nehbit This was a while ago but did you get this working in the end?
