### ISSUE TITLE
ERROR in ./node_modules/electron/index.js Module not found: Error: Can't resolve 'fs'  in 'x:\\xxxxx\node_modules\electron'

### ISSUE THREAD

**Issue by saurabBajgain** [electron/electron#19659]
trying to use ipcRender in app.compponent.ts 
import { remote, ipcRenderer } from 'electron';

but it shows error on **ng serve** as mention in title...

Angular CLI: 6.0.8
Node: 10.15.0
OS: win32 x64
Angular: 5.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.12.2
@angular-devkit/build-optimizer   0.12.2
@angular-devkit/build-webpack     0.12.2
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      5.0.0-rc.1
@angular/cli                      6.0.8
@angular/material                 5.0.0-rc.1
@ngtools/webpack                  7.2.2
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              5.5.2
typescript                        2.4.2
webpack                           4.28.4

tried to implement suggested mention in below issue chain but nothing help.... 
https://github.com/angular/angular-cli/issues/10681

**Comment by vladimiry** [comment]
Accessing the `electron` module in a preload script and exposing only needed stuff to the web/angular bundle will solve the issue.

**Comment by saurabBajgain** [comment]
> Accessing the `electron` module in a preload script and exposing only needed stuff to the web/angular bundle will solve the issue.

Thank you for your response ,will please explain a bit more or may be with example...!

**Comment by vladimiry** [comment]
Here is the example https://github.com/electron/electron-quick-start. In preload script, you can attach things to `window` object and then access them in web/angular bundle.

The core problem here is that by default Angular CLI is trying to pack the `electron` module into the web bundle by it should just keeping the dynamic `require("electron")`-like code in the resulting bundle. So another solution would be in tweaking the webpack config by specifying proper (externals)[https://webpack.js.org/configuration/externals/] property value.

**Comment by MarshallOfSound** [comment]
This sounds like an upstream toolchain / bundling issue, closing out 👍

**Comment by saurabBajgain** [comment]
> This sounds like an upstream toolchain / bundling issue, closing out 👍

but still cannot figure out issue with ipcRender using electron, beside this electron was doing good, actually i want to add open component in new tab within electron window,where i found ipcRender features in electron for inter process communicate, after i add these settings (https://github.com/electron/electron/issues/19659#issue-477683549) this issue came out....

**Comment by mavrick** [comment]
you need to set your webpack target to "electron-renderer"

**Comment by lonelam** [comment]
> you need to set your webpack target to "electron-renderer"
To set webpack target as electron-renderer, I use @angular-builders/custom-webpack.
Is there an option in angular to do this?

**Comment by lonelam** [comment]
> you need to set your webpack target to "electron-renderer"

To set webpack target as electron-renderer, I use @angular-builders/custom-webpack.
Is there an option in angular to do this?

**Comment by kalpeshims** [comment]
problem with reactjs and electron, updated as per suggestion but still issues is not resolved..
![image](https://user-images.githubusercontent.com/53003080/94390875-92c13580-0171-11eb-8439-6d1d58667a34.png)

**Comment by Slapbox** [comment]
For anyone else who hits this, the issue probably is that Electron's first line is `fs = require('fs')`. If you're seeing this issue after turning `nodeIntegration` off it means you're still requiring/importing something directly from `electron` in your non-node capable renderer script. It could be an import of any piece of `electron` (eg, `clipboard`, `remote`, `ipcRenderer`, etc.)
