### ISSUE TITLE
using crashReporter api can't get all params

### ISSUE THREAD

**Issue by beautycss** [electron/electron#19662]
I'm using crashReporter in my electron project and only got three params.
I've tried in both `main.js` in main process and React Page in render process, the  results are the same.

### Expected Behavior
Get all params in my server.
![image](https://user-images.githubusercontent.com/16473160/62600937-c3695e80-b922-11e9-9d78-1052d53dceaf.png)

### Actual Behavior
Got only three params.
![image](https://user-images.githubusercontent.com/16473160/62601203-64f0b000-b923-11e9-9102-82fa0dec13d3.png)

### What I tried

in render process 
```jsx
componentWillMount() {
    remote.crashReporter.start({
      productName: 'productName',
      companyName: 'companyName',
      submitURL: 'http://127.0.0.1:7001/api/crash/create',
    });
    setImmediate(() => {
      if (platform !== 'linux') {
        remote.crashReporter.addExtraParameter('userId', '2');
      } else {
        remote.crashReporter.start({
          productName: 'productName',
          companyName: 'productName',
          submitURL: 'http://127.0.0.1:7001/api/crash/create',
          uploadToServer: true,
          ignoreSystemCrashHandler: true,
          extra: {
            userId: 2,
          }
        });
      }
      setImmediate(() => {
        remote.process.crash();
      });
    });
  }
```

or in main process

```js
    crashReporter.start({
      productName: 'productName',
      companyName: 'companyName',
      submitURL: 'http://127.0.0.1:7001/api/crash/create',
      uploadToServer: true,
      ignoreSystemCrashHandler: true,
    });

    setImmediate(() => {
      console.log(crashReporter.getParameters());
      process.crash();
    });
```

https://github.com/electron/electron/blob/master/spec/fixtures/api/crash-restart.html
https://github.com/electron/electron/blob/master/spec/fixtures/api/crash.html

I saw the two examples and tried them, still don't work.

### Issue Details

* **Electron Version:**
  * 4.0.3
* **Operating System:**
  * macOS 10.14.6

**Comment by MarshallOfSound** [comment]
@beautycss Your `body` object is empty in your screenshot which means you probably don't have a `multipart/form-data` body parser on your server.

If you're using `express` you should use this middleware to parse the body --> https://github.com/expressjs/multer

**Comment by beautycss** [comment]
still not working, but thanks.
I use eggjs, the core is koa2.
