### ISSUE TITLE
could not get code signature for running application

### ISSUE THREAD

**Issue by trae-op** [electron/electron#19666]
Hello! I hope someone helps me.
I can't solve autoUpdate for Mac OS platform.
There are some events for autoUpdate:

**1) checking-for-update
2) update-available
3) download-progress
4) update-downloaded**

For win-10, everything works. For Mac-OS, the 4th item does not work and the error message "**could not get code signature for running application**" is displayed.
The problem is with this https://electronjs.org/docs/tutorial/code-signing
I tried for example from here to use http://flummox-engineering.blogspot.com/2018/12/electron-builder-codesign-specified-item-could-not-be-found-in-the-keychain.html but does not help.

**Comment by linuxjuggler** [comment]
Have you notarized your app?

**Comment by trae-op** [comment]
> Have you notarized your app?
> 
> Also, in mac, if you didn't sign your app, the update will not work. As Signing your code is a requirement.

And if you use the solution from here http://flummox-engineering.blogspot.com/2018/12/electron-builder-codesign-specified-item-could-not-be-found-in-the-keychain.html will not fix the problem?

**Comment by MarshallOfSound** [comment]
On macOS your application must be codesigned with a valid developer ID certificate in order for the auto updater to work

**Comment by linuxjuggler** [comment]
No, as mentioned in https://www.electron.build/auto-update.html

![Screen Shot 2019-08-07 at 10 01 51 PM](https://user-images.githubusercontent.com/27624/62650216-03e6cd80-b95f-11e9-96d5-e29af155491c.png)

and in https://electronjs.org/docs/api/auto-updater#macos

![Screen Shot 2019-08-07 at 10 03 06 PM](https://user-images.githubusercontent.com/27624/62650284-2ed12180-b95f-11e9-97b1-16479ea1124d.png)

You need to sign & notarize your application for the auto-updater to work.

**Comment by trae-op** [comment]
> No, as mentioned in https://www.electron.build/auto-update.html
> 
> ![Screen Shot 2019-08-07 at 10 01 51 PM](https://user-images.githubusercontent.com/27624/62650216-03e6cd80-b95f-11e9-96d5-e29af155491c.png)
> 
> and in https://electronjs.org/docs/api/auto-updater#macos
> 
> ![Screen Shot 2019-08-07 at 10 03 06 PM](https://user-images.githubusercontent.com/27624/62650284-2ed12180-b95f-11e9-97b1-16479ea1124d.png)
> 
> You need to sign & notarize your application for the auto-updater to work.

I was a little confused that for win-10 works, but for win-10 need to certificate too. And now I understand everything. Thanks!
