### ISSUE TITLE
Printing causes process to crash

### ISSUE THREAD

**Issue by abentele** [electron/electron#19664]
### Issue Details

* Electron 5.0.5 - 6.0.1 (see list below)
* macOS 10.14.6

Similar to issues #15188/#15143 (which are already closed/merged).

### Expected Behavior

Basic printing (Browser API window.print()) works.

### Actual Behavior

Application process crashes when printing.

### To Reproduce

Electron Fiddle repro here (same as for issue #15188):
https://gist.github.com/bf55ecc157b5e4d4a69a0a07e0ac0610

To reproduce:
* open the Fiddle with Electron Fiddle (version 0.9.0), select the Electron version and start the app with "Run"
* click on the main page; the print dialog is opened
* in the print dialog, click "Print"

Reproducible (versions), related to the Fiddle and to my private real-world application:
* Electron 4.2.6 => not reproducible with Fiddle / not reproducible with my real-world app
* Electron 4.2.9 => not reproducible with Fiddle / not reproducible with my real-world app
* Electron 5.0.0 => not reproducible with Fiddle / reproducible with my real-world app
* Electron 5.0.4 => not reproducible with Fiddle / reproducible with my real-world app
* Electron 5.0.5 => reproducible with Fiddle
* Electron 5.0.6 => reproducible with Fiddle
* Electron 5.0.7 => reproducible with Fiddle
* Electron 5.0.8 => reproducible with Fiddle
* Electron 5.0.9 => reproducible with Fiddle
* Electron 6.0.0 => reproducible with Fiddle
* Electron 6.0.1 => reproducible with Fiddle / reproducible with my real-world app
* Electron 7.0.0-beta.1 => not reproducible with Fiddle

macOS crash report (crash of Electron 6.0.1):
[crash-report.txt](https://github.com/electron/electron/files/3477048/crash-report.txt)

**Comment by codebytere** [comment]
This will be fixed in the next release of 6.
