### ISSUE TITLE
Error launching app

### ISSUE THREAD

**Issue by Cypaubr** [electron/electron#19670]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.1
* **Operating System:**
  * Windows 10 1903
* **Last Known Working Electron version:**
  * 

### Expected Behavior
Launch the app in a Windows window.

### Actual Behavior
A dialog opens with the message:  
```
**Error launching app**  
Unable to find Electron app at E:\NodeProjects\Fidzee-Monitor  
Cannot find module 'E:\NodeProjects\Fidzee-Monitor'  
Require stack:  
-  
E:\NodeProjects\Fidzee-Monitor\node_modules\electron\dist\resources\default_app.asar\main.js  
-
```

### To Reproduce
It's a fresh project with Angular.

**Comment by MarshallOfSound** [comment]
If a valid app does not exist in `E:\NodeProjects\Fidzee-Monitor` or` E:\NodeProjects\Fidzee-Monitor/package.json` or `E:\NodeProjects\Fidzee-Monitor/index.js` this is the error you see

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

**Comment by Cypaubr** [comment]
An app exists, I have a main.js loading a BrowserWindow etc. registered in my package.json
