### ISSUE TITLE
visibleOnFullScreen param of BrowserWindow.setVisibleOnAllWorkspaces not working

### ISSUE THREAD

**Issue by loc** [electron/electron#19674]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.0.0, 5.0.0, 6.0.1, 7.0.0-beta.1
* **Operating System:**
  * macOS 10.14.3
* **Last Known Working Electron version:**
  * n/a

### Expected Behavior

When the `visibleOnFullScreen` param is set to true for [`BrowserWindow.setVisibleOnAllWorkspaces`](https://electronjs.org/docs/api/browser-window#winsetvisibleonallworkspacesvisible-options), the BrowserWindow instance appears atop every workspace, including full-screened apps.

### Actual Behavior

The BrowserWindow appears atop every workspace except full-screened apps.

### To Reproduce

- Full screen an app, like Finder, via the green traffic button
- Load and run the fiddle: https://gist.github.com/6d38792799a65f3e7d1a81ae1fceb61b
- Four-fingered swipe or ctrl+arrow key to switch between workspaces
- Observe that the window appears on all workspaces except full-screened apps

### Additional Information

`visibleOnFullScreen` was originally implemented here: https://github.com/electron/electron/pull/14122

**Comment by DeerMichel** [comment]
cc'ing original author @paulius005 for his ideas on why this doesn't work

**Comment by loc** [comment]
After some tinkering, it looks like I misunderstood the abilities of the macOS API. `NSWindowCollectionBehaviorFullScreenAuxiliary` only allows you to overlay atop windows set with `NSWindowCollectionBehaviorFullScreenPrimary` _of your own app_. So the repro steps as described are working as designed.

**Comment by arvinxx** [comment]
hi, @loc can you know how to resolve this problem?My setting is  same but doesn't work.
