### ISSUE TITLE
Screen readers do not recognize modal windows as dialogs

### ISSUE THREAD

**Issue by craxal** [electron/electron#19676]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.2.5
* **Operating System:**
  * Windows
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
When a browser window is opened as a modal to the primary renderer window, I would expect screen readers, such as NVDA, to say something like "Title dialog First or top level elements Focus button".

For example, if I click the All Categories... menu item in Microsoft Outlook, screen readers will announce "Color Categories dialog To assign... Important checkbox not checked ". Here, "Color Categories" is the title bar, "To assign..." is the first descriptive element, and "Important checkbox not checked" is the element that receives focus first.

Another example: if I select "Define New Bullet..." in Microsoft Word, screen readers will announce "Define New Bullet dialog Bullet character Preview OK button". Here, "Define New Bullet" is the title bar, "Bullet character" and "Preview" are top-level elements, and "OK" is the default dialog dismissal button.

### Actual Behavior
When a browser window is opened as a modal to the primary renderer window, a screen reader, such as NVDA, says something like "Title" with no other context or indication of the window's content. First focus is unknown (maybe the window itself?).

### To Reproduce

In the main process:
```ts
let mainWindow;
...
// Assume some sort of action from `mainWindow`, such as a button press, raises this event.
ipcMain.on("open-dialog", () => {
    let dialogWindow = new BrowserWindow({
        frame: true,
        modal: true,
        parent: mainWindow,
        skipTaskbar: true
    });
    dialogWindow.loadURL(...);
});
```

### Additional Information
The Electron application I work on implements custom dialogs by using browser windows and HTML pages. We've tried many times to get screen readers to announce these dialog windows the same way it does for native dialogs, but we've had no success.

On Mac systems, it's a little different: `parent` is set to `undefined`. Not sure why this is done, but it suggests that whatever can be done to get the right screen reader context for modals, it should only depend on the `modal` option.

**Comment by craxal** [comment]
Does anyone have an update on this?

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by craxal** [comment]
5 days is a little fast to auto-close an issue. Devs have a lot on their plates...

I just tested this on 7.1.1, and it's...a little better. My screen reader says "pane" instead of "document", but it should still say "dialog".

**Comment by craxal** [comment]
@electron-triage Please reopen this bug. I've tested against 7.1.1, and it still has issues.
