### ISSUE TITLE
`window.print()` not working in electron 7.0.0-beta.2

### ISSUE THREAD

**Issue by lesleyandreza** [electron/electron#19687]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.0.0-beta-2
* **Operating System:**
  * MacOs Mojave 10.14.6
* **Last Known Working Electron version:**
  * 7.0.0-beta.1

### Expected Behavior
Show system print dialog.

### Actual Behavior
Nothing happens.

### To Reproduce
Add `<script>window.print();</script>` into `index.html` in [*Electron Fiddle*](https://electronjs.org/fiddle).

**Comment by codebytere** [comment]
I know what did this, PR incoming.
