### ISSUE TITLE
README.md: some emojis are not displayed properly on some Android devices sold in mainland China.

### ISSUE THREAD

**Issue by zaoqi** [electron/electron#19686]
🇹🇼was banned by some Android devices sold in mainland China

on those devices:
`🇹🇼` become
somethings like `T W` or `☐☐`

Solution: Replace it with 🇭🇰 or 🇲🇴?

**Comment by codebytere** [comment]
@zaoqi unfortunately we inherit all these emoji customizations from Chromium, so this isn't really within our purview to change. I think it might be more effective for you to open a bug on chromium here: http://crbug.com

**Comment by zaoqi** [comment]
@codebytere 
This issue is about readme.md

https://github.com/electron/electron/commit/a3cdf46fb637f79b639839cf4c6655066f8b06d3#diff-04c6e90faac2675aa89e2176d2eec7d8R10
