### ISSUE TITLE
Net core console errors everywhere

### ISSUE THREAD

**Issue by Porkechebure** [electron/electron#19695]
This bullshit doens't work anywhere. Either line up with net core or fix your crap.

Everywhere I follow your crap readme.dm I get errors at the first basic steps.

Example following your readme.md

On the first machine I started a new 2.2 net core web project
Added electron.net
added electron.CLI

Got some weird error in console like "

> Electron.cli dotnettool is not compatible or not found' or something like that.

 No way to go forward

After 30 minutes of hair pulling I've decided to change machine

Here I follow your crap guide

> npm install electron --save-dev 

[--save-exact]

and got

> npm : npm ERR! code EINVALIDTAGNAME
> At line:1 char:1
> + npm install electron --save-dev [--save-exact]
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (npm ERR! code EINVALIDTAGNAME:String) [], RemoteException
>     + FullyQualifiedErrorId : NativeCommandError
>  
> npm
>  
> ERR!
>  Invalid tag name "[--save-exact]": Tags may not have any characters that encodeURIComponent encodes.
> 
> 
> 
> npm
>  
> ERR!
>  A complete log of this run can be found in:
> 
> npm
>  
> ERR!

Ok it says it doesnt like save-exact, nice that electron devs put it and crashes.
Well I remove it

> npm install electron --save-dev

Errors on errors.
First NPM console says

> Queue overflowed
then installs something and then

pm : npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\xxx\Documents\Visual Studio 2017\Projects\WebApplication2\package.json'
At line:1 char:1
+ npm install electron --save-dev
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (npm WARN saveEr...2\package.json':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
npm
 
notice
 created a lockfile as package-lock.json. You should commit this file.

npm
 
WARN
 
enoent
 ENOENT: no such file or directory, open 'C:\Users\xxx\Documents\Visual Studio 2017\Projects\WebApplication2\package.json'

npm
 WARN
 WebApplication2 No description

npm
 
WARN
 WebApplication2 No repository field.

npm
 
WARN
 WebApplication2 No README data

npm
 
WARN
 WebApplication2 No license field.

Fucking failure
fix it

**Comment by codebytere** [comment]
@Porkechebure your comment is a violation of [the Electron Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md). You may consider this an official warning.

It also seems you may have opened this issue in error, as this project is not a .NET project unlike [Electron.NET](https://github.com/ElectronNET/Electron.NET).
