### ISSUE TITLE
Add a method to modify folder / directory icons

### ISSUE THREAD

**Issue by SaifurRahmanMohsin** [electron/electron#19715]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
The folder icons can be modified using different processes in different operating systems. For example, in Windows a Desktop.ini file can be used to specify a custom folder icon whereas in macOS [the process is different](https://support.apple.com/en-gb/guide/mac-help/mchlp2313/mac) and also the format maybe different (it uses icns if I'm not mistaken).

### Proposed Solution
Create a simple function in the File module to apply a NativeImage as a folder icon and that function should perform different processes specific to the OS to set the icon.

### Alternatives Considered
Couldn't find any good ones.

**Comment by MarshallOfSound** [comment]
IMO this is not something that should live in Electron Core.  There is no Chromium API to help with this functionality and it is not specific to Electron, nor would it be used by the majority of Electron applications.

You should probably build this as a native node module rather than getting it implemented in Electron itself

**Comment by SaifurRahmanMohsin** [comment]
@MarshallOfSound Wait, what? In that case why is there a file module or process module in Electron? These aren’t specific to Electron either nor are there Chromium APIs as these are OS-level filesystem-based concepts yet they exist in electron. I thought Electron was something that would bridge the gap and make it easier to develop cross platform desktop apps so ideally this particular feature goes right in line with what Electron is supposed to achieve.

**Comment by MarshallOfSound** [comment]
@SaifurRahmanMohsin The file module (I assume you are referring to `fs`) comes from Node.JS as does the `process` object, not implemented nor maintained in Electron core, it comes from the embedded node.js instance.

**Comment by SaifurRahmanMohsin** [comment]
Ohk. Thanks
