### ISSUE TITLE
Electron > 6.0  current working directory is not correct

### ISSUE THREAD

**Issue by gaodeng** [electron/electron#19717]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.1
* **Operating System:**
  * macOS 10.14.3 (18D42)
* **Last Known Working Electron version:**
  * 4.x, 5.x

### Expected Behavior
renderer.js should working without error

### Actual Behavior
Message: Uncaught TypeError: Error processing argument at index 0, conversion failure from  ...

### To Reproduce

https://github.com/gaodeng/electron-quick-start

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
 git clone https://github.com/gaodeng/electron-quick-start.git
 cd electron-quick-start
 npm install
 npm start 

```

### Additional Information
This issue only occurs when
 * [x] create window with webSecurity: false
 * [x] call mainWindow.webContents.send after window created
 * [x] Electron version > 6.0

**Comment by MarshallOfSound** [comment]
Fixed in #19719
