### ISSUE TITLE
not allow load local resource when use service worker 

### ISSUE THREAD

**Issue by mengzhidiguo** [electron/electron#19716]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Details

* **Electron Version:**
  * 5.0.0
* **Operating System:**
  * Windows 10 (1903)
* **Last Known Working Electron version:**
  * 6.0.0

### Expected Behavior
In the case of a service worker, I want to be able to load local resources.

### Actual Behavior
But actually, it can't load

**Comment by electron-triage** [comment]
@mengzhidiguo You've reported that it was working on Electron 6. Please use Electron version 6 or later as we are no longer supporting versions older than Electron 6. See our [supported versions policy](https://www.electronjs.org/docs/tutorial/support#supported-versions)
