### ISSUE TITLE
The message after run app (would like to control this computer using accessibility features)

### ISSUE THREAD

**Issue by trae-op** [electron/electron#19733]
Hi! I have a problem. After each run my app, display a message ("MyApp" would like to control this computer using accessibility features). What can I do for this change?
As I understand it, need to run only once after click "Deny" but it run everytime. Electron version 6.0.1
![image](https://user-images.githubusercontent.com/12648541/62958335-29605500-bdff-11e9-9516-f8b71fa3e4f6.png)

**Comment by codebytere** [comment]
Thanks for reaching out!

@trae-op this would occur resultant of a codepath Electron/Chromium is traveling that requires these permissions.

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by trae-op** [comment]
> Thanks for reaching out!
> 
> @trae-op this would occur resultant of a codepath Electron/Chromium is traveling that requires these permissions.
> 
> We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

I do not quite understand what I need to do for consider my problem. Maybe available some methods from docs for fix this problem, but I can't find it.

**Comment by codebytere** [comment]
@trae-op what we mean here is that with the information you've provided, we don't know what code you've written that would cause this error, which prevents us from being able to properly investigate and potentially solve this issue. If you could provide us with a reproducible [fiddle](https://github.com/electron/fiddle) we could look into this more :)

**Comment by trae-op** [comment]
> @trae-op what we mean here is that with the information you've provided, we don't know what code you've written that would cause this error, which prevents us from being able to properly investigate and potentially solve this issue. If you could provide us with a reproducible [fiddle](https://github.com/electron/fiddle) we could look into this more :)

I found the reason of displaying the message (**"MyApp" would like to control this computer using accessibility features**). It's **iohook module** starts the message. https://wilix-team.github.io/iohook/

**Comment by codebytere** [comment]
Right, but that's still not quite enough; for example, you didn't give us an operating system. Can you please go back and fill out the template we provided in the issue to begin with? Specifically - we need a **reproducible piece of code**.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Comment by ovo4096** [comment]
electron 13.6.9

I have this problem when playing audio files.
