### ISSUE TITLE
Can't install globaly on Ubuntu 18.04

### ISSUE THREAD

**Issue by zeroidentidad** [electron/electron#19741]
### Issue Details
* **Electron Version:**
  electron@6.0.2 

* **Operating System:**
  Ubuntu 18.04 x64

* **Screen Shot:**
![captura](https://user-images.githubusercontent.com/2924638/62996101-06e33180-be29-11e9-97f9-d87e82199981.png)

* **Log file:**
[2019-08-14T05_03_13_009Z-debug.log](https://github.com/electron/electron/files/3499890/2019-08-14T05_03_13_009Z-debug.log)

**Note:** I try with root user getting same error on post install

![captura](https://user-images.githubusercontent.com/2924638/62996866-f5e7ef80-be2b-11e9-8f3d-9db4817dcd5d.png)

**Comment by MarshallOfSound** [comment]
See https://electronjs.org/docs/tutorial/installation#troubleshooting

Though I would point out that using `sudo` to install globally is generally a **bad idea**

**Comment by zeroidentidad** [comment]
Thanks, I get it. reading npm info linked useful too
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
https://docs.npmjs.com/misc/config#unsafe-perm
