### ISSUE TITLE
globalShortcut.unregister is not removing global shortcut for accelerator registered through Menu.setApplicationMenu

### ISSUE THREAD

**Issue by inDigiNeous** [electron/electron#19749]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

Registering menu accelerator via menu template, eg:
```
	const menu_template: Electron.MenuItemConstructorOptions[] = [
		{
			label: 'Layer',
			submenu: [
				{
					id: "new",
					label: "Add New",
					accelerator: 'n',
					click: on_menu_item_click
				}
                       ]
                }
        ]

	const menu = Menu.buildFromTemplate(menu_template)
	Menu.setApplicationMenu(menu)

	globalShortcut.unregister('n')
```

The accelerator for key N is still active and is not unregistered. I would wish to just register the keyboard shortcuts, display them in the menu and handle the actual keystroke on the renderer side with 'keyup'.

* **Electron Version:**
  * v4.2.9
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron version:**
  * Unknown

### Expected Behavior

The accelerator for key N should not be handled via a global shortcut.

### Actual Behavior
The accelerator for key N is still handled by global shortcut handlers.

### To Reproduce
Create a menu with accelerators, buildFromTemplate and Menu.setApplicationMenu()
After this, call globalShortcut.unregister().

Test out application and see that keyboard shortcut is still handled globally.

**Comment by codebytere** [comment]
@inDigiNeous that's not the way that `globalShortcut()` works; you can only unregister shortcuts that you registered _with `globalShortcut()` _. 

See [documentation](https://github.com/electron/electron/blob/319c2853dfdd3fcec42e763ef820a28028fae6bb/docs/api/global-shortcut.md#L96-L100) 

> Unregisters the global shortcut of `accelerator`.

This accelerator in your repro was not registered as a globalShortcut and cannot be unregistered with the same.

**Comment by inDigiNeous** [comment]
Allright, thank you for the clarification. The use of accelerators in the Menu documentation confused me, that it would be registered using the same system. Also the option registerAccelerator for menu options hints that it uses the same system, but seems this is indeed not the case.

I wish there was a way to disable the menu item accelerators though, but doesn't seem to be currently possible on macOS.
