### ISSUE TITLE
Secure Websocket using self sign cert

### ISSUE THREAD

**Issue by jt-helsinki** [electron/electron#19748]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
5.0.6
* **Operating System:**
Mac 10.14
* **Last Known Working Electron version:**
n/a

### Expected Behavior
From the render process, `new WebSocket('wss://some_ip')` to a server/device that uses a self signed cert should connect without an error.

### Actual Behavior
Even when trying to catch errors using the `certificate-error` events, the web socket is unable to connect. 

Without putting any `certificate-error` event handlers on the `BrowserWindow` or on the `app` I receive the following error in the console output:

> WebSocket connection to 'wss://some_ip:some_port/' failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID

If I add the `certificate-error` event handlers I receive:

> WebSocket connection to 'wss://some_ip:some_port/' failed: WebSocket opening handshake was canceled

### To Reproduce
From the render process, try to connect to any secure web socket which uses a self signed cert. 

**Main process**
```
process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;

const win = new BrowserWindow({
        webPreferences: {
            nodeIntegration: true,
            webSecurity: false,
            allowRunningInsecureContent: true
        }
    });

win.webContents.on('certificate-error', (event, url, error, certificate, callback) => {
    event.preventDefault();
    callback(true);
});
```

**Render process**
```
const connection = new WebSocket(`wss://some_ip:some_port/`);

connection.onopen = (event): void => {
    console.log('* User is opening socket connection....', event);
};

connection.onclose = (event): void => {
    console.log('* User is closing socket connection....', event);
};
```

### Additional Information
For now, I have started connecting inside the main process. This feels like a hack and I don't think that is the intention of the Electron team.... or is it?

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.1.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
