### ISSUE TITLE
Clicks not being detected with addEventListener or .on('click')

### ISSUE THREAD

**Issue by source1471** [electron/electron#19757]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
v6.0.2
* **Operating System:**
 Windows 10 (1803)
* **Last Known Working Electron version:**
Unknown

### Expected Behavior
When button is pressed should open a new window  with the same layout but with text as test as it is a test but i cant go past until the button works

### Actual Behavior
Button is pressed and highlights with an orange border but it doesn't process that it is clicked so the new window doesn't open

### To Reproduce

index.html:

`<!DOCTYPE html>`
`<html>`
`  <head>`
`    <meta charset="UTF-8">`
   ` <title>Hello World!</title>`
`    <link rel="stylesheet" href="../assets/css/main.css">`
`  </head>`
`  <body>`
    
  `  <div class="row">`
`      <div id="price-container">`
`        <p class="subtext">Market-Monitor</p>`
     `   <h1 id="About">By SourcE</h1>`
    `  </div>`
   `   <div id="goal-container">`
  `      <p><span id="targetPrice">Monitor The Prices of items on the market</span></p>`
   `   </div>`
`      <div id="right-container">`
  `      <button id="launch">Launch</button>`
      `</div>`
   ` </div>`

   ` <script src="index.js"></script>`
`  </body>`
`  <main>`
    `<div id="live-prices">`
      `<p class="subtext"></p>
  `  </div>`
 ` </main>`
`  </html>`

index.js:

`const {BrowserWindow} = require('electron').remote`
`const path = require('path')`
`const {shell} = require('electron')`
`const launchbtn = document.getElementById('launch')`

`launchbtn.addEventListener('click', (event) => {`
`  const modalPath = path.join('file://', __dirname, 'launch.html')`
 ` let win = new BrowserWindow({ width: 400, height: 320 })`
 ` win.on('close', () => { win = null })`
`  win.loadURL(modalPath)`
 ` win.show()`
`})`

launch.html:

`<!DOCTYPE html>`
`<html>`
`  <head>`
  `  <meta charset="UTF-8">`
   ` <title>Hello World!</title>`
 `   <link rel="stylesheet" href="../assets/css/main.css">`
`  </head>`
`  <body>`
    
    `<div class="row">`
    `  <div id="price-container">`
     `   <p class="subtext">test</p>`
    `    <h1 id="About">test</h1>`
    `  </div>`
    `  <div id="goal-container">`
    `    <p><span id="targetPrice">test</span></p>`
   `   </div>`
   `   <div id="right-container">`
   `     <button id="launch">test</button>`
  `    </div>`
  `  </div>`

`    <script src="launch.js"></script>`
`  </body>`
`</html>`

### Screenshots
![Capture](https://user-images.githubusercontent.com/51530905/63047387-41ea7100-becc-11e9-91e4-c271d96a2e07.PNG)

### Additional Information
This is my first time using Electron so i might well be wrong in the code any help is usefull

**Comment by rit9163882** [comment]
I want to fix this issue but unable to locate it in source code, can u help me getting a way to clone this on my pc and work on it?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by naivebayesrust** [comment]
> I want to fix this issue but unable to locate it in source code, can u help me getting a way to clone this on my pc and work on it?





https://frivolous-spring-portlet.github.io/HhS1kEWEeovW-MAGQMG1X1kKtP0lONu0GSNVWztX10aVTXg/
