### ISSUE TITLE
The electron v6.0.2 build app can't run on ubuntu v18.04

### ISSUE THREAD

**Issue by zhangshuaidan** [electron/electron#19750]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:
  * v6.0.2
* **Operating System:**
  * mac os
* **Last Known Working Electron version:**
  * 5.0.8

### Expected Behavior
I package a linux app ,it run normal on unbutun;

### Actual Behavior
I use electron v6.0.2 and  electron-builder package an linux app,but it can't run, but when I use electron v5.0.8, run the same shell it run normal
I use this shell to package `electron-builder build --linux`

### To Reproduce
```
git clone https://github.com/electron/electron-quick-start.git
cd electron-quick-start
npm install
npm install electron-builder --save-dev
npm run electron-builder build --linux
```

### Screenshots

![image](https://user-images.githubusercontent.com/27200655/63019854-1cab3200-becf-11e9-83b6-aa93d69b2a87.png)

this is worong, when it open ,it's noting.

**Comment by ckerr** [comment]
I _think_ this is an electron-builder bug report rather than an Electron one?

If so, please report this to https://github.com/electron-userland/electron-builder/issues instead. Thank you!
