### ISSUE TITLE
Closing a BrowserWindow with set affinity and electron.remote usage from a preload script will freeze similar BrowserWindows.

### ISSUE THREAD

**Issue by markleutloff** [electron/electron#19753]
* Electron Version: >= 6.0.0-beta.13, 6.0.0, 6.0.1, 6.0.2, 7.0.0-beta.1, 7.0.0-beta.2
* Operating System (Platform and Version): Windows 10
* Last known working Electron version: 5.0.9, <= 6.0.0-beta.12

**Expected Behavior**
Closing the BrowserWindow should not freeze other BrowserWindows.

**Actual behavior**
Similar BrowserWindows will freeze.

**To Reproduce**
Create a two BrowserWindows with identical webPreferences set to:
preload: some preload script
affinity: some affinity

**index.js:**

> const {app, BrowserWindow} = require('electron')
> 
> function createWindow () {
>     const browserWindow = new BrowserWindow({
>         width: 800,
>         height: 600,
>         webPreferences: {
>             preload: "PATH_TO_PRELOAD.js",
>             affinity: "Test"
>         }
>     })
> 
>     browserWindow.loadFile('index.html')
> }
> 
> app.on('ready', () => {
>     createWindow();
>     createWindow();
> })
> 
> app.on('window-all-closed', function () {
>     app.quit()
> })

**preload.js:**

> // Thats all what is needed to make it break
> const { remote } = require("electron");

**Additional Information**
Just by using **electron.remote** this issue occours. To test the freeze effect, just try to select some text in the remaining window.

**Comment by MarshallOfSound** [comment]
This is why the `affinity` API is flagged as experimental, what you are seeing here is a deadlock between two renderers with synchronous IPC.

The end game is for `affinity` to be removed along with all of our other patches to the Chromium process model to avoid scenarios like this.  See https://github.com/electron/electron/issues/18397
