### ISSUE TITLE
Dom frozen after cancel close window.print dialog.

### ISSUE THREAD

**Issue by purocean** [electron/electron#19768]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.2
* **Operating System:**
  * Windows 10.0.18362.267

---------------------------------------------------------------------------------------------------
[Version 6.0.2](https://github.com/electron/electron/releases/tag/v6.0.2) solved print crash problem. But is still trouble when I cancel print dialog.

There is a closed same issue.
https://github.com/electron/electron/issues/14705

**Comment by CaseyLeeMurphy** [comment]
I don't believe this is a windows only issue. I'm observing this behavior on mac in version 7.0.2

**Comment by vladimiry** [comment]
This is a quite severe issue. Besides, Linux is also affected.

**Comment by jngbng** [comment]
I'm observing it on Mac (Mojave 10.14.5) in version 6.0.10, too.

**Comment by HaNdTriX** [comment]
This issue also effects the window.opener api:

```js
const opener = window.open('/')
opener.print() // -> freezes current webview
```

**Comment by jarek-foksa** [comment]
I can reproduce this issue with Electron 5.0.11 on macOS Mojave.

**Comment by HaNdTriX** [comment]
Fyi: This issue seems to be resolved in version `v7.0.0-beta.6`

**Comment by TristonJ** [comment]
This issue seems to be fixed in `v7.0.0-beta.6` and `v7.0.0-beta7`, but in those versions I am experiencing a different issue (appears to be the same as https://github.com/electron/electron/issues/14705). The print dialog only works once (Ubuntu 19.04).

**Comment by codebytere** [comment]
@vladimiry this should be fixed in 8

**Comment by codebytere** [comment]
Closing as this has been fixed - however the "only works once" issue is valid and will now be tracked in https://github.com/electron/electron/issues/21397.
