### ISSUE TITLE
set the x of BrowserWindow to 1021-1079,the width of the win will increase 2

### ISSUE THREAD

**Issue by KinoriN** [electron/electron#19769]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * Electron v6.0.2
* **Operating System:**
  * Windows 10 1903
* **Last Known Working Electron version:**
  * just had used v6.0.2

### Expected Behavior
set bound.x of browserWin to a new number (1021-1079)

### Actual Behavior
the bound.width increase 2

### To Reproduce
`setInterval(()=>{
        win.setBounds({
            x:1079,
        })
        console.log(win.getBounds().width)
    },100);`

### Screenshots

![image](https://user-images.githubusercontent.com/45453624/63081311-e07edc80-bf75-11e9-930a-3d903006207a.png)

**Comment by KinoriN** [comment]
* **Electron Version:**
  * Electron v6.0.2
* **Operating System:**
  * Windows 10 (1903)

**Comment by brenca** [comment]
Could you please make a repro app for this? (I suggest electron fiddle) We'd need to know more than just this to verify and fix this. (I'm specifically interested in whether you have a frameless window or not)

**Comment by KinoriN** [comment]
> Could you please make a repro app for this? (I suggest electron fiddle) We'd need to know more than just this to verify and fix this. (I'm specifically interested in whether you have a frameless window or not)

I have try it on another computer, I find that if want to repro it , need to set the scale of wondows display to 125%
just need to create a default browserWindow and set the bounds.x to 1079, need not any more setting
`const electron = require('electron');
const app = electron.app;
const {BrowserWindow} = electron;
let win = null;
app.on('ready',()=>{
    win = new BrowserWindow({
    });
    console.log(win.getBounds().width);
    setInterval(()=>{
        win.setBounds({
            x:1075
        });
        console.log(win.getBounds().width);
    },1000);
});`
![image](https://user-images.githubusercontent.com/45453624/63219362-f2919280-c1a2-11e9-9e20-2a62cf0f458f.png)

**Comment by brenca** [comment]
I can confirm that this happens, will look into it next week.

**Comment by brenca** [comment]
I have added a larger scale patch that addresses this. BTW this bug repros in chrome as well, I'm going to open a bug report there and link it here when I do.

**Comment by Garbee** [comment]
Has any bug report been filed with Chromium about this?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
