### ISSUE TITLE
WebView not showing

### ISSUE THREAD

**Issue by JonasAlpha** [electron/electron#19761]
I'm fairly new to Developing with Electron and wanted to try making a simple web browser like application for testing. For that, I wanted to add a webview but it's not showing up. I don't really know why it's not showing.

index.js (main electron file)
```js
const electron = require('electron')

const { app, BrowserWindow } = require('electron')

function createWindow () {
  // Erstelle das Browser-Fenster.
  let win = new BrowserWindow({
    width: 1000,
    height: 600,
    center: true,
    webPreferences: {
      nodeIntegration: true,
      webViewTag: true
    }
  })

  // and load the index.html of the app.
  win.loadFile('index.html')
}

app.on('ready', createWindow)
```

index.html
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Some title</title>
  </head>

  <body>
    <h1> HTML is fancy! </h1>

    <webview src="http://www.google.com/" style="width:1280; height:720"></webview>


  </body>
</html>
```

**Comment by codebytere** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by Kilian** [comment]
Hi @JonasAlpha make sure you add a unit in your webviews style attribute or it'll have a height of 0 by 0. Like so:

```
// what you have
<webview src="http://www.google.com/" style="width:1280; height:720"></webview>
// what works
<webview src="http://www.google.com/" style="width:1280px; height:720px"></webview>
```

In the future, you can use the developer tools and check the elements panel. Select the webview tag there and you can see what CSS is applied, if it's applied correctly and if you look at the "computed" tab that shows up, you also get a visual overview of the dimensions of the element.

**Comment by JonasAlpha** [comment]
That helped but it's still not showing anything :(

**Comment by jikaibo** [comment]
hi，Have you solved this problem？

**Comment by tannerkozlowski** [comment]
> That helped but it's still not showing anything :(

@JNSAPH, have you solve this problem?

**Comment by chusieme14** [comment]
what is the solution

**Comment by Lanson2232** [comment]
I solved my problem by adding `webPreferences:{
    webviewTag:true
  }` this to my `BrowserWindow` **options**

**Comment by lavahasif** [comment]
**Before**
![adsd](https://user-images.githubusercontent.com/22430922/152732816-89041e81-a578-40a3-9734-94dca9b0a1a6.gif)
**After**
![adsd sdf](https://user-images.githubusercontent.com/22430922/152732983-4ca72deb-178f-4c76-b153-2f8435d47ff6.gif)

So you must add
`webPreferences:{ webviewTag:true }`

```
function createWindow() {
    win = new BrowserWindow({width: 800, height: 600, webPreferences: {webviewTag: true}})
    win.loadURL(url.format({
        pathname: path.join(__dirname, 'index.html'),
        protocol: 'file:',
        slashes: true
    }))
}
```

**Comment by admin007r** [comment]
ok working
