### ISSUE TITLE
Error when trying to add certain src url to my image tag

### ISSUE THREAD

**Issue by dr-nyt** [electron/electron#19766]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
* **Electron Version:**
  * 6.0.2
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
I added a src link to an img tag and expected it to display that image

### Actual Behavior
Instead of displaying the src image, it gives me the following error: Failed to load resource: the server responded with a status of 503 ()

### To Reproduce
- Add the following img tag to reproduce:
< img
        id="chapter"
        class="novelCover"
        src="https://novelplanet.com/Uploads/I-Might-Be-A-Fake-Cultivator848.jpg"
        border="0"
        alt=""
/>

- CSS just in case
.novelCover {
       width: 240px;
       height: 300px;
       border-radius: 5% 5% 0 0;
}

### Additional Information
Trying to run the same img tag in a browser results in the correct display of the src image.

**Comment by MarshallOfSound** [comment]
The image appears to be behind cloudflare ddos protection which return 503 when the request is blocked.

This is not an issue with electron itself, the server legitimately returned a 503
