### ISSUE TITLE
How to make a signed kernel extension when my app access the system's audio on macOS?

### ISSUE THREAD

**Issue by xiaoping6688** [electron/electron#19767]
Access information about media sources that can be used to capture audio and video from the desktop using the navigator.mediaDevices.getUserMedia API in Electron. But it does not work on macOS for audio capture. 
So, i need to request a Developer ID Certificate for Signing Kexts, but I don't know how to do it, please help me.

![image](https://user-images.githubusercontent.com/16394201/63072504-c1248700-bf56-11e9-98ef-9e9c044419f0.png)

The Official response:
![image](https://user-images.githubusercontent.com/16394201/63072877-a0f5c780-bf58-11e9-8e1b-e24c294f7781.png)

**Comment by MarshallOfSound** [comment]
You do not need a kernel extension to use that API

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
