### ISSUE TITLE
bug: open file dialog doesn't allow selecting files

### ISSUE THREAD

**Issue by DeerMichel** [electron/electron#19779]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.0.0-nightly.20190814, master
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron version:**
  * v8.0.0-nightly.20190813

### Expected Behavior
Should be able to select files or folders.

### Actual Behavior
Selecting is disabled (greyed out).

### To Reproduce
```js
const { app, dialog } = require('electron')

app.on('ready', () => {
  dialog.showOpenDialogSync({
    title: 'Hello!',
    properties: ['openFile'],
  })
})
```

### Screenshots
![image](https://user-images.githubusercontent.com/8472721/63111062-b6abc280-bf41-11e9-8e68-992792390014.png)

**Comment by DeerMichel** [comment]
cc @codebytere 

ref https://github.com/electron/electron/compare/v8.0.0-nightly.20190813...v8.0.0-nightly.20190814

maybe https://github.com/electron/electron/commit/28466a39d81e8adbade67ff150b7037be4993db2?

**Comment by codebytere** [comment]
yeah i think i know what this is!
