### ISSUE TITLE
Electron native extensions?

### ISSUE THREAD

**Issue by cfv1984** [electron/electron#19777]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

It is as of today (aug 15, 2019) not possible to extend Electron in an organized, native way to add functionality that is not covered by the mainline project. 

This hinders adaptability and precludes using Electron in any way that was not previously thought of by the Electron team, and leaving easily modifiable plain javascript in charge of orchestrating the application.

### Proposed Solution

Ideally we could have Electron have the ability to load natively compiled shared objects for several points of the application lifecycle, much like Cordova or Ionic or Capacitor apps do. 

This would let individual implementors fill the gaps in their roadmap by themselves, with the most obvious security aspect coming to mind, enabling anti tampering measures and proper data safeguarding, as well as enabling all kinds of spectacularly positive means of interacting with the host OS.

### Alternatives Considered

A plugin architecture for calling shared libraries like the ones implemented by Cordova, Capacitor, and even React Native comes to mind. 

### Additional Information

At the moment this is precluding me from building an Electron app that deals with patient records due to the IMMENSE potential for abuse it presents. HIPAA mandates at the very least basic privacy protecting measures are put in place, that if built with Electron can be sidestepped to inject random  code which then can totally pass as part of my own application with little to no ability to contain the damage done. Having a native module check for tampering would ensure this is made at least somewhat more onerous on the attacker's part.

**Comment by MarshallOfSound** [comment]
@cfv1984 Electron embeds Node.JS which has had built-in support for native addons for a long time.

Refs: https://nodejs.org/api/addons.html

**Comment by cfv1984** [comment]
Please explain how native modules can be used to implement boot time hooks that cannot be disassembled by simply unpacking the asar and removing them instead of closing this ticket
