### ISSUE TITLE
Blocked a frame with origin "file://" from accessing a cross-origin frame

### ISSUE THREAD

**Issue by SimanovichSiarhei** [electron/electron#19789]
### Issue Details
* **Electron Version:**
  * 5.0.4+, 6.0.0+
* **Operating System:**
  * MacOS 10.14.6, Win 7, Win 10
* **Last Known Working Electron version:**
  * 5.0.3

### Expected Behavior

When I use native chrome window.open function, I'd like to have windows communication way using window.opener.

### Actual Behavior

When I try to access data stored in parent window, I got security error:
```
Uncaught DOMException: Blocked a frame with origin "file://" from accessing a cross-origin frame.
```
No matter both windows origin is 'file:'.

### To Reproduce
Sample in attachments
To reproduce:
```
npm i
npm start
```
Reload document (cmd+R)
Click "New child window"
Observe child window console

[electron-quick-start.zip](https://github.com/electron/electron/files/3509563/electron-quick-start.zip)

**Comment by alper-teke** [comment]
Can we get a feedback about this please? It's blocking us to use latest versions of electron. Thanks a lot

**Comment by rpastro** [comment]
Any feedback on this issue?

**Comment by rpastro** [comment]
I haven't looked in detail, but it seems that the problem could have been introduced by https://github.com/electron/electron/pull/18614.

**Comment by MarshallOfSound** [comment]
Unique `file://` URLs are all considered on different origins for security reasons, this is the same behavior as a browser

**Comment by rpastro** [comment]
This is a scenario where the electron app is opening a second window using window.open function.  The origin is the same on both windows. This is a false match for for a cross origin issue.

Please take a look at the attached sample application to see the problem.

**Comment by MarshallOfSound** [comment]
@rpastro This is not a false match.  As I explained different `file://` URLs are considered on different origins for security reasons.  If you want to do this you should use a custom protocol as that follows traditional `protocol://[domain]/[path]` rules that the `file://` protocol does not follow

**Comment by rpastro** [comment]
@MarshallOfSound  Regarding the comparison with the browser. This would be equivalent to a web application opening another window for a different page in the same domain, which is allowed and we are actually using in our web application.

**Comment by rpastro** [comment]
@MarshallOfSound  How can I use a different protocol than file to load a page that is packaged together with the electron app itself?  Again, this has always been allowed in electron and it was broken in v5.0.4.  The rules for file:// protocol should follow the same rules as other protocols and should consider the 'domain' itself. For an electron app the domain would be all files packaged as part of the app.

**Comment by MarshallOfSound** [comment]
> This would be equivalent to a web application opening another window for a different page in the same domain, which is allowed and we are actually using in our web application.

No it's not the same, it's on the `file://` protocol.  That changes everything.

> The rules for file:// protocol should follow the same rules as other protocols and should consider the 'domain' itself.

No... They shouldn't.  I'm sorry but the `file://` protocol is an exception to all normal rules, you can use the `electron.protocol` module to register your own custom protocol that will follow the normal rules.

**Comment by rpastro** [comment]
Why should file://<__dirname>/... be an exception to the rule when this is the only alternative to load the files that are part of my own app?  Please explain how could this ever be used for a cross site attack because I truly don't understand.

Please understand that we have an entire app that is based on this functionality and that has worked without issues since before Electron v1.

You are suggesting that I should register my own protocol. How can I use that to reliably load other files which are packaged with the app itself?  For instance, how would I load the window in the attached example?

window.open('file://' + __dirname + '/childWin/child.html', '', 'width=200, height=200');

**Comment by rpastro** [comment]
@MarshallOfSound  regarding your suggestion. Are you saying that I would not have the CORS . issue if I create a custom protocol that has the same effect as the file:// protocol, similar to the example in https://electronjs.org/docs/api/protocol?

I'm assuming this also means that I would have to load all my windows using this custom protocol.

**Comment by jon-heard** [comment]
I am also struggling with cross-origin issues.  Am I right in thinking that if you want different windows of your application to work together you have to be running a webserver alongside electron?

**Comment by jon-heard** [comment]
I've come to realize that if you have multiple windows, the proper way to communicate between them is by using the main process as a liason.  This can be done through IPC.  This would mean that you'd also have to initiate each window through the main process (again, can be done through IPC).

My particulars are a bit different as I have a parent window and an iframe, so there _is_ no main process between them.  However, I have found a solution that allows for cross-origin communication. 
 I've provided an explanation [here](at https://stackoverflow.com/questions/58156367/electronjs-avoiding-cross-origin-issues).

**Comment by mobitar** [comment]
Related: https://github.com/electron/electron/issues/18214

**Comment by SimanovichSiarhei** [comment]
@MarshallOfSound, in any case, if it relates to security, there is an security issue in electron. Without main window reload, my desired behavior is working (each even reload change result). So you need pay attention to it.

But honestly I didn't understand how behavior of chromium is changed within electron version change from 5.0.3 to 5.0.4. I hope that this could become like feature that is disabled by default. 

I guess load files stored in same asar archive has nothing common with tab isolation solving Spectre vulnerability and could be treated as same origin. There is no way now to have simple communication layer parent-child to grab some classes/methods/data.

**Comment by mobitar** [comment]
@MarshallOfSound should different file:// paths be able to share localStorage? I'm seeing that they are indeed able to read each other's values: https://github.com/electron/electron/issues/21260

**Comment by clusterberries** [comment]
Hello @MarshallOfSound ! 
I have the same problem and I'm trying to find some workaround. Using custom protocol is a bad variant for me, because I have a lot of issues with http requests. 
So I try to use file protocol, but even if I have a page "file:///C:/project/index.html" and then try to open the same page using window.open, it throws an error "Blocked a frame with origin "file://" from accessing a cross-origin frame.". It doesn't make sense at all, because urls are identical.
Why does it work in such way? What urls with file protocol are interpreted as the same origin?
Thank you in advance for any help!

**Comment by clusterberries** [comment]
If somebody is looking for workaround, I found a solution: `protocol.interceptFileProtocol` allows to intercept `file://` as well. So if you have a window /project/index.html and you need to load /project/child.html using `window.open`, do the following: 

- load /project/index.html#child, so it will be interpreted as the same origin

- replace index.html#child with child.html in main process:

```
   protocol.interceptFileProtocol('file', (request, cb) => {
        let url = request.url.replace(/file:[/\\]*/, '');
        url = decodeURIComponent(url);
        url = url.replace(/\/index\.html#child.*$/, '/child.html');
        cb(url);
    }, err => console.log(err));
```

**Comment by SuperKirik** [comment]
@chenweihan thanks a lot ! this solution worked for me 😺
