### ISSUE TITLE
How to allow CORS requests with webSecurity: true

### ISSUE THREAD

**Issue by ChugunovRoman** [electron/electron#19788]
Hi.
Im developing a desktop app for figma.com.
Figma make requests on s3-alpha-sig.figma.com and static.figma.com
and all this requests fails with error in my app:
```
Access to Script at 'https://static.figma.com/***********' from origin 'https://www.figma.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.figma.com' is therefore not allowed access.
```
The official desktop app base on Electron and creates BrowserView with "webSecurity: true" too.
BUT in official app the CORS requests successful passes! How?? I don't understand
<details>
  <summary>I created BrowserView with next options:</summary>

```javascript
{
  webPreferences: {
    nodeIntegration: false,
    contextIsolation: true,
    webSecurity: true,
    webgl: true,
    experimentalFeatures: false,
  }
}
```

</details>

Can you halp me find to answer on: "How do make a CORS request with setted 'webSecurity' property in the true?"
P.S. I cannot set  'webSecurity' property in the false, because it need for correct work of Figma plugins I think...
There is a diffirent problem:
Figma check web security each time before run any user plugin.
In script which check web security have next line which should throw exception:
```javascript
window.parent.document.body
```
The script execute in iframe node, it catch and ignore error on this line `window.parent.document.body` in any browser and official app - it is normal behavior. But in my app this line passes and function return a error: "Failed DOM access check"
<details>
  <summary>On this pice of code:</summary>

```javascript
  try {
    window.parent.document.body
    return "Failed DOM access check"
  } catch (ex) {}
```

</details>
<details>
  <summary>Full security check function:</summary>

```javascript
function doIframeSecurityChecks() {
  // Edge seems to change the URL and origin of the page when you document.write()
  // a whole new page. The new URL looks something like http://{abc123.abcd-1234-5678-0123}/
  // with the {} escaped using percent encoding.
  if (document.location.origin !== "null" &&
    !/^https?:\/\/\%7b[a-f0-9.-]+\%7d$/.test(document.location.origin)) {
    return "Failed origin check: " + document.location.origin
  }

  // This doesn't ensure that we're sandboxed. But we want this to be true
  if (!document.location.href.startsWith('data:text/html,') &&
    !document.location.href.startsWith('data:text/html;base64,') &&
    !/^https?:\/\/\%7b[a-f0-9.-]+\%7d\/$/.test(document.location.href)) {
    return "Failed location.href check: " + document.location.href
  }

  try {
    if (localStorage && localStorage["figma-extension-guard"] !== undefined) {
      return "Failed localStorage check"
    }
  } catch (ex) {}

  try {
    window.parent.document.body
    return "Failed DOM access check"
  } catch (ex) {}

  try {
    window.parent.someRandomProperty
    return "Failed JS heap access check"
  } catch (ex) {}

  return "ok"
}

let result
try {
  result = doIframeSecurityChecks()
} catch (ex) {
  result = ex + ''
}
parent.postMessage({
  pluginMessage: result
}, '*')
```

</details>

I think if I set 'webSecurity' property in the true this security check pass successful. But after that, I got error with CORS requests. :cry: :disappointed: 
Figma doesn't work if CORS requests is fails.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

**Comment by checkin001** [comment]
Did you figure out how to fix it? i have the same problem when load figma in my Electron BrowserWindow
