### ISSUE TITLE
"Update check failed. The server sent an invalid response." when trying to update my app

### ISSUE THREAD

**Issue by mr-newell** [electron/electron#19805]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.1.4
* **Operating System:**
  * macOS 10.14.5 (Mojave)

### Expected Behavior
After following the instructions in the [tutorial](https://electronjs.org/docs/tutorial/updates), I can update my Electron app.

### Actual Behavior
I get the error `Error: Update check failed. The server sent an invalid response. Try again later.`

### Additional Information
I opened the [same ticket](https://github.com/Squirrel/Squirrel.Mac/issues/240) a few days ago in the Squirrel.Mac repo since that seems to be where the error is coming from, but I'm opening it here too since this repo is more active and it seems likelier someone has run into my issue.

Basically, I have a code-signed Mac app to which I'm trying to add auto-update functionality.

I have set up a Lambda function at `https://api.staging.my-domain.com/updater/checkUpdates/products/product-name/platforms/darwin?v=1.0.0` which I use in `setFeedUrl()` to check whether an update is available; if one is, a 200-status JSON response is returned that looks like this:

```json
{
  "upgradeStatus": "minor",
  "url": "https://s3.amazonaws.com/my-bucket/staging/installers/latest/My%20Product%20Name.zip"
}
```

I can paste that S3 URL into my browser and it will download the file without a problem; I've set it to be publicly accessible.

Despite this, I get the error `Error: Update check failed. The server sent an invalid response. Try again later.` which is coming from [SQRLUpdater.m](https://github.com/Squirrel/Squirrel.Mac/blob/cb838776ce22bcbf41def7b9a1352f24120bab29/Squirrel/SQRLUpdater.m). Objective-C is looks quite foreign to me though so it's hard to understand what is causing the error to be thrown.

I have gone through the docs and many blog posts and as far as I can tell, I am doing everything I should be to get updates working. Is there something else I need to be doing? Anything I may have overlooked?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

FWIW that error is due to one of the following
* An invalid HTTP response code
* Invalid JSON being returned
* Missing information in the JSON object (try adding the `name` field)
