### ISSUE TITLE
Electron 6 - restore after minimize has wrong window size

### ISSUE THREAD

**Issue by whyboris** [electron/electron#19816]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * `6.0.2`
* **Operating System:**
  * Windows 10 (1903)
* **Last Known Working Electron version:**
  * `5.0.7`

### Expected Behavior
1. App is not maximized 
2. click minimize 
3. click on taskbar icon
4. **app restores to original size**

### Actual Behavior
1. App is not maximized 
2. click minimize 
3. click on taskbar icon
4. **screen flickers as the app returns from _minimum allowed window size_ to the original (not maximized) size.**

### To Reproduce
I logged the behavior:
```ts
  win.on('minimize', (e) => {
    console.log('minimizing');
    const bounds: any = win.getBounds();
    console.log(bounds);
  });

  win.on('restore', (e) => {
    console.log('restoring');
    const bounds: any = win.getBounds();
    console.log(bounds);
  });
```

Result:
```
minimizing
{ x: 100, y: 200, width: 1400, height: 800 }
restoring
{ x: 100, y: 200, width: 420, height: 250 }
```

The dimensions come from 
```ts
  win = new BrowserWindow({
    ...
    minWidth: 420,
    minHeight: 250,
    frame: false // this line might be relevant for the current issue
```

I have the problem happening in my app, in `master` - tracking with https://github.com/whyboris/Video-Hub-App/issues/260

Can be reproduced by cloning the repository, running `npm install`, having _Angular CLI_ installed (`npm i -g @angular/cli`), and running the app `npm start`. Needless to say the error occurs in the built version of the app (`npm run electron:windows`).

_Note:_ the error does _not_ occur when the window is _maximized_, minimized, and restored.

Error might not occur on Mac -- can't be sure because the Mac has a stupid minimize/maximize animation 🤷‍♂ 

Thank you _Electron Team_ for your amazing work 🙇 my app would be impossible without you ❤️ 

### Possibly related tickets:
https://github.com/electron/electron/issues/19423
https://github.com/electron/electron/issues/13043
https://github.com/electron/electron/issues/16900

### Possible solution:
https://github.com/electron/electron/issues/19423#issuecomment-521621266

**Comment by whyboris** [comment]
@zcbenz -- I'm sorry but this bug is not yet closed as of `6.0.5`

Thank you to @brenca for working on it, but it seems that he tried to close 3 different bugs and this one might have slipped through.

```
minimizing
{ x: 409, y: 945, width: 1990, height: 937 }
restoring
{ x: 409, y: 945, width: 420, height: 250 }
```

I have a branch `remove-flicker` for anyone to try. Just clone [my repository](vhttps://github.com/whyboris/Video-Hub-App), `npm install`, switch to branch, and run; minimze/maximize to see the logging show the problem.

Relevant testig code: https://github.com/whyboris/Video-Hub-App/blob/remove-flicker/main.ts#L122

**Comment by zcbenz** [comment]
@whyboris The fix will be included in next 6.x release, 6.0.5 does not have it yet.

**Comment by whyboris** [comment]
@zcbenz thank you so much for the quick response 🙇 
I'm looking forward to it ❤️
