### ISSUE TITLE
webPreferences.webviewTag option takes no effect on BrowserWindow opened by nativeWindowOpen option

### ISSUE THREAD

**Issue by KochiyaOcean** [electron/electron#19829]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  5.0.9 and 6.0.2
* **Operating System:**
  *  All platforms
* **Last Known Working Electron version:**
  *  4.2.9

### Expected Behavior

A BrowserWindow opened by `window.open()` with `nativeWindowOpen` option should enable `<webview>` support if `webPreferences.webviewTag` is true
### Actual Behavior

`<webview>` support is not enabled
### To Reproduce

clone reproduce repo and start with electron@5 or electron@6
```bash
git clone https://github.com/KochiyaOcean/electron-bugs.git -b nativeWindowOpen
cd electron-bugs
electron .
```

In the subwindow, the webview isn't rendered. In the devtool of subwindow, a error `Uncaught TypeError: Cannot read property 'loadURL' of null` occours.

### Screenshots

In electron@5.0.9 (Not working)
The webviewTag option is true in webPerferences
![image](https://user-images.githubusercontent.com/8194131/63288204-182fb080-c2f7-11e9-8f01-f221dffe4c31.png)

In electron@4.2.9 (Working)
![image](https://user-images.githubusercontent.com/8194131/63288080-d1da5180-c2f6-11e9-9a98-c8b02c00e553.png)

### Additional Information
Update: if `nodeIntegrationInSubFrames` is true (which enables node integration in subwindow), `<webview>` will be enabled.
So is node integration a must for webview in subwindow (webview in main browserwindow didn't require node integration through)?

**Comment by KochiyaOcean** [comment]
Still occurs on electron@7

**Comment by miniak** [comment]
Yes, you need to enable `nodeIntegrationInSubFrames`.

**Comment by KochiyaOcean** [comment]
@miniak  So if a window wants to able to open subwindow with `<webview>` support, it has to enable `nodeIntegrationInSubFrames` which causes [memory leak issue](https://github.com/electron/electron/issues/12634)?
