### ISSUE TITLE
Delete user data in windows and mac on uninstall

### ISSUE THREAD

**Issue by hawx1993** [electron/electron#19838]
Hi,

I need to remove user data on uninstall on both windows and mac.

As in Mac there is no uninstall feature when we move to trash how will the user data get deleted.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
