### ISSUE TITLE
webSecurity: false ignored in new-window event

### ISSUE THREAD

**Issue by martin31821** [electron/electron#19846]
### Issue Details

* **Electron Version:** 6.0.3/5.0.8
* **Operating System:** Arch Linux, Windows 10, seems to be platform independent
* **Last Known Working Electron version:** Couldn't determine

### Expected Behavior
When using `nativeWindowOpen: true` and `webSecurity: false`, I expect opened windows to also have webSecurity disabled.

### Actual Behavior

I'm using `webSecurity: false` in development to allow loading plugin scripts from the filesystem when running within webpack-dev-server. 
At the same time, I need to use `nativeWindowOpen: true`, as a library I'm using requires a working window.open. 
So I'm handling the `new-window` event in `main.js`, and try to override the `webPreferences` to the `new BrowserWindow` and set `event.newGuest`, but the setting isn't honored and I'm not allowed to load file:// urls in the opened window, event though I'm allowed to load them in the parent window.

### To Reproduce
```ts
const serve = true; // serve is set to true when running in dev-server

win.webContents.on('new-window', (
    event: any,
    uri: string,
    frameName: string,
    disposition: string,
    options: BrowserWindowConstructorOptions,
    additionalFeatures: any) => {
    console.log(event, url, frameName, options, additionalFeatures, event.newGuest);
    if (uri.indexOf('foobar') >= 0) {
    // open window as modal
      event.preventDefault();
      options = {
        ...options,
        webPreferences: {
          ...options.webPreferences,
          webSecurity: !serve,
          allowRunningInsecureContent: serve,
        }
      };
      event.newGuest = new BrowserWindow(options);
      console.log('Done creating window');
      return event.newGuest;
    }
  });
```

### Screenshots
![Screenshot from 2019-08-20 21-50-46](https://user-images.githubusercontent.com/5557633/63379439-9d1cd780-c394-11e9-9c9d-2b1283139c1b.png)
![Screenshot from 2019-08-20 21-50-18](https://user-images.githubusercontent.com/5557633/63379440-9d1cd780-c394-11e9-9d41-7f0b5689da72.png)
![Screenshot from 2019-08-20 21-50-15](https://user-images.githubusercontent.com/5557633/63379441-9db56e00-c394-11e9-9602-dea67bd5ed8e.png)

### Additional Information

The problem is occuring when using golden-layout and the ngx-golden-layout angular binding within an electron app.
XRef: 
https://github.com/golden-layout/golden-layout
https://github.com/EmbeddedEnterprises/ng6-golden-layout

**Comment by martin31821** [comment]
Minor follow up: 
After reading #19829, which seems to be related, I get the content warnings in my child window, but still get the 'Not allowed to load local resource' error.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
