### ISSUE TITLE
Notification cannot be displayed

### ISSUE THREAD

**Issue by y489436672** [electron/electron#19859]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**v
  v5.0.2 - v6.0.2
* **Operating System:**
   win10   x64   17134
* **Last Known Working Electron version:**
  v5.0.9

### Expected Behavior
  let msgNotification = new Notification({title: 'aaaaa', subtitle: 'bbbbb', body: 'ccccc', silent: true})
  msgNotification.on('click', () => {
    msgNotification.close()
  })
Notification normal display
### Actual Behavior
The code executed successfully. But nothing shows up.
The main process notification will not be displayed. The html5 notification will not be displayed. I tested that all version notifications in this section have disappeared. Recently my win10 has been updated. Is this related to the system? Before this it was normal.
### To Reproduce
 in the main
 import { Notification } from 'electron'
 let msgNotification = new Notification({title: 'aaaaa', subtitle: 'bbbbb', body: 'ccccc', silent: true})
  msgNotification.on('click', () => {
    msgNotification.close()
  })
 in the renderer
 let msgNotification = new Notification( ‘aaa’,  {body: 'ccccc'})
 msgNotification.onclick = () => {
         msgNotification.close()
  })

**Comment by ckerr** [comment]
It doesn't look like `show()` is being called on either of these notifications?

Does the demo at https://github.com/electron/fiddle/tree/master/static/show-me/notification work for you?

**Comment by y489436672** [comment]
Thank you for your reply.
 I will reply you tomorrow because of the time difference.
It was normal in previous use.
In my home win10  17134.885, it is normal.
I found that my app did not appear in the win10 notification settings.
Under normal conditions it is in the presence notification settings and can be set.
I will reply you in detail tomorrow.

**Comment by y489436672** [comment]
I use the same code to run on my computer.
The code executed successfully but there is no display.
I can't see any notifications.
![code1](https://user-images.githubusercontent.com/19664101/63566573-497ed980-c5a0-11e9-843e-7841a5b47bc1.png)
![code2](https://user-images.githubusercontent.com/19664101/63566574-497ed980-c5a0-11e9-9469-6e6284f1ba03.png)
![code3](https://user-images.githubusercontent.com/19664101/63566575-4a177000-c5a0-11e9-95bb-2880473a3f12.png)
![code4](https://user-images.githubusercontent.com/19664101/63566576-4ab00680-c5a0-11e9-9153-5171f43ad1b5.png)

**Comment by y489436672** [comment]
It runs on win10 Professional 17134.950.

**Comment by y489436672** [comment]
I reinstalled my application on my computer and it showed normally. And I saw my application in the notification settings. I don't know why it didn't work when I first installed it. If I don't think it's a problem, I'll close it.

**Comment by y489436672** [comment]
It's normal in my debugging state.
