### ISSUE TITLE
 White screen appears quickly when the app focus from background.

### ISSUE THREAD

**Issue by BelinChung** [electron/electron#19858]
### Preflight Checklist
*  [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
*  [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
*  [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v6.0.3
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron version:**
  * v1.8.3

### Expected Behavior
The same behavior as other APPs

### Actual Behavior
White screen appears quickly when the app focus from background, Ensure that the app is in the background for a while.

### To Reproduce
https://github.com/electron/electron-quick-start
Put the app in the background for a while and focus main window, the issue will be reproduced.

### Screenshots
Screen recording: https://s0.static.lunkr.cn/cab/publish/electron_bug_report.mov

### Additional Information
none

**Comment by MarshallOfSound** [comment]
I can't assign them but @loc has been working on this
