### ISSUE TITLE
electoron v4.1.4 , Font rendering becomes thicker

### ISSUE THREAD

**Issue by steady-join** [electron/electron#19861]
I can't know the recurring path of this bug. The application packaged by electron is occasionally present. The font with font-weight of 500 is bold, similar to 600. Can you help me? Thank you！
version:4.1.1
platform:mac

**Comment by ckerr** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unneccessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-info` label for this reason. After you've responded, please link to the test case and @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by steady-join** [comment]
@ckerr   hi，I can't provide you with an application, because this can't be a bug,But I can give you a difference comparison。
<img width="791" alt="屏幕快照 2019-08-21 下午10 41 05" src="https://user-images.githubusercontent.com/29935583/63442337-84c8bd80-c465-11e9-8577-5f3334d5ab9d.png">
<img width="630" alt="屏幕快照 2019-08-21 下午10 44 23" src="https://user-images.githubusercontent.com/29935583/63442350-8b573500-c465-11e9-9084-e54debd046c7.png">

**Comment by miniak** [comment]
Electron 4 is not supported anymore.
https://electronjs.org/blog/electron-7-0#end-of-support-for-4xy

Please create a new issue if the bug still exists in a supported version of Electron.
