### ISSUE TITLE
AddExtensions function in WebView

### ISSUE THREAD

**Issue by IceHacks** [electron/electron#19877]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
The WebView element does not have an `addExtension` method anywhere.

### Proposed Solution
Add it to the WebView

### Alternatives Considered
I considered third party scripts but they didn't work.

**Comment by miniak** [comment]
@IceHacks Did you try using `BrowserWindow.addExtension()`? It's a static method, which adds a Chrome extension to all windows / webviews.

**Comment by IceHacks** [comment]
No. I did not.
