### ISSUE TITLE
Side bar menu with two action, either open in same window or on new window.

### ISSUE THREAD

**Issue by saurabBajgain** [electron/electron#19879]
Angular CLI: 6.0.8
Node: 12.8.0
OS: win32 x64
Angular: 5.0.3

electron: 2.0.17
![photo_electron](https://user-images.githubusercontent.com/14971466/63484042-e8d49b80-c4d0-11e9-9f20-76ca3ac19b49.jpg)

(as pointed in picture i dint mean to open same content in different window, i just want to show action type which we can relate same for other sub menu. and of-course i want different sub menu opened in different windows but may be sometime same content in different windows and performing same action with different settings/variables.)

as shown in picture above... i tried a simple method to open in new window but that time both window opens same content but i want to have different content in different windows run/performs intended action in same time. for example i want to load Perform action in one window and Testing in another windows, their outcome doesn't have any relation. 

these side menu are defined in src/app/app.component and on click of each side menu, content will loaded from src/app/component/xyz.component . if we have to load content from https:// url its fine we can have different content loaded in different windows as per url provided, but here i am trying to load different component in different windows and perform intended actions in same time. 
and as we know electron browser is defined in outside src folder in menu.js file and for single window its working fine as we can see in picture above.

here i want somebody to help me with ideas to get this features.
i did some research but couldn't get as per i explain above, if there is any  i will appreciate if somebody provide me some links ...
Thankyou

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
