### ISSUE TITLE
Electron 6 causes DLL init error when using NAPI native modules

### ISSUE THREAD

**Issue by Superlokkus** [electron/electron#19884]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version: 6.0.3**
  * 
* **Operating System: Windows 10 1903**
  * 
* **Last Known Working Electron version: 3.1.13**
  * 
* **Build System: Microsoft (R) C/C++ Optimizing Compiler Version 19.22.27905 for x64 aka Visual Studio 2019**

### Expected Behavior
Native node module still works in new electron version

### Actual Behavior
DLL initialization error at runtime

### To Reproduce

Yarn install and yarn dist of https://github.com/Superlokkus/electron-native-node-demo/tree/actual_napi_use_with_electron_update 
Then run the executable: DLL error

Yarn install and yarn dist https://github.com/Superlokkus/electron-native-node-demo/tree/actual_napi_use
Then run the executable: Works as intended

Only difference (assumed) between the branches: New electron version.

### Error

> Uncaught Error: A dynamic link library (DLL) initialization routine failed.
> \\?\C:\Users\marku\AppData\Local\Programs\electron_native_node_demo\resources\app.asar.unpacked\node_modules\spielwiese\build\Release\spielwiese.node
>     at process.func (electron/js2c/asar.js:155)
>     at process.func [as dlopen] (electron/js2c/asar.js:155)
>     at Object.Module._extensions..node (internal/modules/cjs/loader.js:828)
>     at Object.func (electron/js2c/asar.js:155)
>     at Object.func [as .node] (electron/js2c/asar.js:164)
>     at Module.load (internal/modules/cjs/loader.js:645)
>     at Function.Module._load (internal/modules/cjs/loader.js:560)
>     at Module.require (internal/modules/cjs/loader.js:685)
>     at require (internal/modules/cjs/helpers.js:16)
>     at index.html:10

**Comment by one-thunder** [comment]
Yeah same problem I've bump into yesterday. The fun fact that the stack trace is fun as hell', I tried to debug but I believe devs from electron have a better knowledge how to do it well.
Hopefully it will be fixed soon, thanks gl hf!

**Comment by greg9504** [comment]
FWIW I have built an add on that used n-api and it works with Electron 6.  I took a quick look and built your distribution.  However you are using CMake-js to build your plugin and I can't really see the magic it is doing.  My guess is the problem lies there, not with Electron.  Try building it with node-gyp and then use electron-builder to rebuild your plugin targeting Electron via the install-app-deps command.  I have these scripts setup to do that:

"postinstall": "npm run postinstall:electron && npx electron-builder install-app-deps",
"postinstall:electron": "node postinstall",

**Comment by xhcoding** [comment]
If you use CMake-js build addon for electron > 4,  you should add `${CMAKE_JS_SRC}` to your source files. Look #17462  and https://github.com/cmake-js/cmake-js#general

**Comment by xhcoding** [comment]
If you use CMake-js to build addon for electron > 4, you shoule add `${CMAKE_JS_SRC}` to you sources.Look #17462 and https://github.com/cmake-js/cmake-js#general

**Comment by Superlokkus** [comment]
> If you use CMake-js to build addon for electron > 4, you shoule add `${CMAKE_JS_SRC}` to you sources.Look #17462 and https://github.com/cmake-js/cmake-js#general

Yes that solved the problem, sorry did not saw that update in the cmake-js documentation.
