### ISSUE TITLE
Configure electron to handle forward slash in SRC tags "/"?

### ISSUE THREAD

**Issue by mattjankowski** [electron/electron#19899]
I am converting a website to an electron app for windows 10. Things are going smoothly except the entire application has paths to resources written like this: 

`@font-face {
  font-family: 'SymphonieGrotesque';
  src: url('/assets/fonts/37AAB8_48_0.eot');
  src: url('/assets/fonts/37AAB8_48_0.eot?#iefix') format('embedded-opentype'), url('/assets/fonts/37AAB8_48_0.woff2') format('woff2'), url('/assets/fonts/37AAB8_48_0.woff') format('woff'), url('/assets/fonts/37AAB8_48_0.ttf') format('truetype');
  font-weight: 500;
  font-style: normal;
}`

Which results in a "FILE NOT FOUND" error.

The error goes away (and the application can use the font) when I remove the first slash from the path:
`@font-face {
  font-family: 'SymphonieGrotesque';
  src: url('assets/fonts/37AAB8_48_0.eot');
  src: url('assets/fonts/37AAB8_48_0.eot?#iefix') format('embedded-opentype'), url('assets/fonts/37AAB8_48_0.woff2') format('woff2'), url('assets/fonts/37AAB8_48_0.woff') format('woff'), url('assets/fonts/37AAB8_48_0.ttf') format('truetype');
  font-weight: 500;
  font-style: normal;
}`

If it were 10 or even 20 instances I could make the changes pretty easily. There are many more than that. Is there something I can configure for electron to utilize the slash?  

Thanks!
Matt

**Comment by MarshallOfSound** [comment]
@mattjankowski This is how `file://` works, when loaded from disk the `/` means "root of my disk" when loaded on `http` it means "root of the web server".

You should update all these URLs

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
