### ISSUE TITLE
app.setName(name) not working in macOS Mojave

### ISSUE THREAD

**Issue by davej** [electron/electron#19892]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.3
* **Operating System:**
  * macOS Mojave 10.14.5 (18F132)
* **Last Known Working Electron version:**
  * Not sure. Also broken in Electron 5.0.9

### Expected Behavior
`app.setName('foo')` should change the application name

### Actual Behavior
`app.setName('foo')` has no effect on application name.
I tested this running in dev mode and a pre-packaged signed app.

### To Reproduce

```js
app.setName('foo')
```

Gist: https://gist.github.com/c434c7cd7d940ba25ba6707a0a743dd1

**Comment by MarshallOfSound** [comment]
@davej macOS enforces certain things out of our control.  Namely certain places where your application name appears it reads it straight from your `Info.plist` file and you **can not** override it.  This is why in development no matter what your app appears as "Electron" in the top menu bar.

Unfortunately there is nothing that can be done here

**Comment by davej** [comment]
@MarshallOfSound Thanks, understood. Can I suggest that you add the Windows and Linux tags to the method in the API docs? I did a quick PR here: #19893
