### ISSUE TITLE
app.dock.hide() crash on OS X Catalina when running as root

### ISSUE THREAD

**Issue by nicko2n** [electron/electron#19896]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
6.0.3. Also observed on 4.2.9
* **Operating System:**
OSX Catalina 10.15 Beta (19A536g)
* **Last Known Working Electron version:**
Can't reproduce on non-Catalina variants of OSX - at least Yosemite and High Sierra
### Expected Behavior
App icon not shown in Dock
### Actual Behavior
Error message followed by Electron app crash

2019-08-22 13:18:37.765 Electron[73668:2759878] -[__NSCFConstantString objectAtIndex:]: 
unrecognized selector sent to instance 0x7fff9812d5c0

### To Reproduce

App crashes when calling app.dock.hide() but only when running as root, e.g. started as a service by launchd.

package.json:
{
  "name": "electron-dock",
  "version": "1.0.0",
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  },
  "devDependencies": {
    "electron": "^6.0.3"
  }
}

main.js:
const {app, BrowserWindow} = require('electron')
app.dock.hide()
console.log('reached')
process.exit(0)

As non-privileged user:
$ npm start

> electron-dock@1.0.0 start /path/to/app
> electron .
reached

As root, via sudo
$ sudo npm start

> electron-dock@1.0.0 start path/to/app
> electron .
reached

As root, via su - (or via launchd)

$ sudo su -
root# npm start

> electron-dock@1.0.0 start /path/to/app
> electron .

2019-08-22 13:23:11.096 Electron[73780:2762770] -[__NSCFConstantString objectAtIndex:]: unrecognized selector sent to instance 0x7fff9812d5c0

### Additional Information
My app crashes with "Illegal instruction: 4" after printing the error message but the example above doesn't; not sure what the difference is.

Unsure why it runs ok via "sudo npm start", but not after "sudo su -" . It doesn't appear to be related to differenced in environment variables.

Reproduced on two OS X laptops, but on Catalina only (latest beta as of submission).

**Comment by nicko2n** [comment]
Issue still present after upgrading to the new beta (#7) of Catalina.

The instance in the error message changed:
2019-08-29 09:18:12.058 Electron[2596:29096] -[__NSCFConstantString objectAtIndex:]: unrecognized selector sent to instance 0x7fff92fed090

**Comment by nicko2n** [comment]
Reproduced in MacOS build 19A558d.

2019-09-17 10:50:09.630 Electron[1498:12005] -[__NSCFConstantString objectAtIndex:]: unrecognized selector sent to instance 0x7fff91c2f340

**Comment by nicko2n** [comment]
Reproduced with beta 9 (build 19A573a)

2019-09-25 09:49:15.316 Electron[1812:21458] -[__NSCFConstantString objectAtIndex:]: unrecognized selector sent to instance 0x7fff90409c60

**Comment by nicko2n** [comment]
Reproduced in the launch release of Catalina
2019-10-08 20:57:34.071 Electron[1855:17634] -[__NSCFConstantString objectAtIndex:]: unrecognized selector sent to instance 0x7fff96e26040

**Comment by codebytere** [comment]
Unfortunately this is a `wontFix` on our end - not because we don't wish to but because for consumer apps, Apple as a company allows very little control over the Dock, and the way that an app exists on it. Apps can only set, by normal means, one of a few activation policies:
```
// The application is an ordinary app that appears in the Dock and may
// have a user interface.
[NSApp setActivationPolicy: NSApplicationActivationPolicyRegular];

// The application does not appear in the Dock and does not have a menu
// bar, but it may be activated programmatically or by clicking on one
// of its windows.
[NSApp setActivationPolicy: NSApplicationActivationPolicyAccessory];

// The application does not appear in the Dock and may not create
// windows or be activated.
[NSApp setActivationPolicy: NSApplicationActivationPolicyProhibited];
```
but we in Electron want to provide you more granular access, so we hook into slightly [lower level components](https://github.com/electron/electron/blob/9b01bb00d2337283d5a1d0eb9d867ced1211d3ea/shell/browser/browser_mac.mm#L332-L363). Unfortunately, the above is a side effect of us allowing you to have more control at all. As such, i'm going to label this a `wont-fix` and close it out.

**Comment by MauricioPellizzon** [comment]
@codebytere 
Thanks a lot for this info, just came across this issue on our tests in Catalina.
My code in main.js just has this:

`app.dock.hide()`

The app I'm working on does not have a menu and t should not show it the Dock, it is very basic and must be called from root.
How could apply the this bit in the app code, please?
// The application does not appear in the Dock and does not have a menu
// bar, but it may be activated programmatically or by clicking on one
// of its windows.
[NSApp setActivationPolicy: NSApplicationActivationPolicyAccessory]; 

Sorry for the newly question, just learning about this great way to create macOS apps.

Thank you for any input.
Regards,
Mauricio

**Comment by codebytere** [comment]
@mauriciofauth that's a great question - it's definitely possible and i'm open to considering it! Could you please open a new issue as a feature request? Specifically, a request for the ability to control app activation policy on macOS?

**Comment by MauricioPellizzon** [comment]
@codebytere Thank you very much for considering this. Let me know if you need further information and, as a newbie, if I did something wrong.
Kind regards
Mauricio

**Comment by threatstop** [comment]
Thank you for the update.

With the info you provided, I was able to workaround the issue by adding
"mac": {
      "extendInfo": {
        "LSUIElement": 1
      }
}
to my electron-builder config. Now the electron-based app launched via launchd doesn't pop-up in the dock when it's run.

I second the request to be able to do this using the electron API instead of enforcing it via the app's plist.
