### ISSUE TITLE
Electron's Main Process is unable to spawn the child Process

### ISSUE THREAD

**Issue by Praveer1981** [electron/electron#19905]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  5.0.7
* **Operating System:**
  Windows 10
* **Last Known Working Electron version:**
  5.0.0

### Expected Behavior
 I am Expecting to run my exe in the background

### Actual Behavior
 It does not do any thing, 

### Additional Information
I have create a Backgroundtask.exe(UWP), I want this exe to be spawned when I launch my electron app.
below is my sample code.
```
main.js [Main Process]

const spawn = require('child_process').spawn

  // Spawn the background task here
  const backgroundTask = path.join(__dirname,  "uwpBackgroundTask", "BackgroundTaskTriggerer.exe")
  //console.log(`Path = ${backgroundTask}`);
  ipcMain.on("message-from-main-process", () => {
    ipcMain.send(backgroundTask)
  });
  
  const runningBackgroundTask = spawn(backgroundTask);

  runningBackgroundTask.stdout.on('data', (data) => {
    //console.log(`stdout: ${data}`)
    ipcMain.on("message-from-main-process", () => {
      ipcMain.send(`stdout: ${data}`)
    });
  })

  runningBackgroundTask.stderr.on('data', (data) => {
    //console.log(`stderr: ${data}`)
    ipcMain.on("message-from-main-process", () => {
      ipcMain.send(`stderr: ${data}`)
    });
  })

  runningBackgroundTask.on('close', (code) => {
    //console.log(`child process exited with code ${code}`)
    ipcMain.on("message-from-main-process", () => {
      ipcMain.send(`child process exited with code ${code}`)
    });

  })
```
The above code snippet I have added just after creating the window.
Is it possible to spawn an exe from the main process ? It does not even capture any error.
Note:
When I Spawn from the renderer process. It does throw an error
**child process exited with code 3221226505**

**Comment by fohristiwhirl** [comment]
I don't think the use of ipcMain here makes sense, that's for communication with the renderer process, unless I'm mistaken. (Also, even if it was correct, I don't think anything is generating the "message-from-main-process" events you're waiting for.)

A minimal program that does *something* with child process output could look like this:

```javascript
const path = require("path");
const readline = require("readline");
const spawn = require("child_process").spawn;

const backgroundTask = path.join(__dirname, "whatever.exe");
const runningBackgroundTask = spawn(backgroundTask);

const scanner = readline.createInterface({
	input: runningBackgroundTask.stdout,
	output: undefined,
	terminal: false
});

scanner.on("line", (line) => {
	console.log(line);
});
```

**Comment by Praveer1981** [comment]
Ohh, I was to intend to have 
`ipcMain.on("message-from-main-process", () => {
      ipcMain.send(`stderr: ${data}`)
    });
` sorry to post the misleading information. But, Yes, I wanted to check whether the background task spawn or not .so  I  have ` runningBackgroundTask.stderr.on('data', (data) => { ... }`

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.1.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
