### ISSUE TITLE
设置-webkit-app-region：drag后，点击右键会出现默认菜单栏

### ISSUE THREAD

**Issue by CY-Blink** [electron/electron#19919]
有方法把默认菜单栏稳藏吗？
![1566615363(1)](https://user-images.githubusercontent.com/18389584/63631812-bd7fb700-c65e-11e9-995b-21063590b0cf.jpg)

**Comment by jkleinsc** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).

**Comment by jkleinsc** [comment]
GitHub问题适用于功能请求和错误报告，有关使用Electron或代码帮助请求的问题应该直接发送到 [社区](https://github.com/electron/electron#community)
