### ISSUE TITLE
Cloning existing electron desktop app

### ISSUE THREAD

**Issue by AlexAtCodeForage** [electron/electron#19933]
### Preflight Checklist

* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
When cloning my electron project that works on two different computers, npm start fails on my third which is a windows 10 tablet device after the clone.

I tried cloning the example for electron on my windows 10 tablet / laptop device and it worked fine when using npm start.

Using latest nodejs and electron. All windows 10 devices.

### Expected Behavior
Should run on all devices that can support visual studio code and git bash

### Actual Behavior
Spawn error. Application never starts.

### To Reproduce
Can only reproduce on my specific repository, cannot provide access at this time. 

### Screenshots
Need to collect

### Additional Information
Need to come back to this thread on the target PC with the issues and will update this.

**Comment by MarshallOfSound** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
