### ISSUE TITLE
Certain MenuItem roles are non-functional

### ISSUE THREAD

**Issue by alexdhill** [electron/electron#19931]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  ^6.0.0
* **Operating System:**
  macOS 10.14.1
* **Last Known Working Electron version:**
 NA

### Expected Behavior
Menu bar should display the App Name, Test, File, Edit, View, and Window menus.

### Actual Behavior
Both the File and View Menus do not display and the App-name menu is empty

### To Reproduce
In a new electron project and add 
`const appMenu = [
  // //List of main tabs with submenu lists
  {role: 'appMenu'},
  {
    label: 'Test',
    submenu: [
      {
        label: 'Open Webpage',
        click: async () => {
          const { shell } = require('electron');
          await shell.openExternal('https://electronjs.org');
        }
      },
    ]
  },
  {role: 'fileMenu'},
  {role: 'editMenu'},
  {role: 'viewMenu'},
  {role: 'windowMenu'}
];
`
to the main.js to open during the createWindow() function.

### Screenshots
<img width="349" alt="Screen Shot 2019-08-24 at 4 13 26 PM" src="https://user-images.githubusercontent.com/46797990/63643655-1f094b00-c68a-11e9-846d-612f2427ef09.png">
**The 'Quantification' tab is the same as the 'Test' tab

**Comment by codebytere** [comment]
I think you may not be fully initializing this menu somehow:

```js
  const appMenu = [
    { role: 'appMenu' },
    { label: 'Test', submenu: [
      { 
        label: 'Open Webpage',
        click: async () => {
          const { shell } = require('electron')
          await shell.openExternal('https://electronjs.org')
        }
      }
    ]},
    {role: 'fileMenu'},
    {role: 'editMenu'},
    {role: 'viewMenu'},
    {role: 'windowMenu'}
  ]

  const menu = Menu.buildFromTemplate(appMenu)
  Menu.setApplicationMenu(menu)
```
running the following with latest supported versions on macOS shows me both purportedly menu items correctly:

<img width="492" alt="Screen Shot 2019-08-30 at 1 16 12 PM" src="https://user-images.githubusercontent.com/2036040/64049101-975b8a80-cb28-11e9-84dc-bed2945bfbb9.png">

<img width="222" alt="Screen Shot 2019-08-30 at 1 16 27 PM" src="https://user-images.githubusercontent.com/2036040/64049105-99bde480-cb28-11e9-889b-a220753e279c.png">
