### ISSUE TITLE
Font rendering on macOS 10.14 is still too thin on Electron v4.x

### ISSUE THREAD

**Issue by lexi-lambda** [electron/electron#19970]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v4.2.9
* **Operating System:**
  * macOS 10.14.5
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior

Versions of Electron other than 4.x include a fix for font rendering on macOS 10.14. Here’s what things are supposed to look like, rendered using Electron v6.0.4:

<img width="912" alt="Screen Shot 2019-08-26 at 20 25 06" src="https://user-images.githubusercontent.com/759911/63734140-badcb780-c840-11e9-86e9-8aa3e1ab9852.png">

Electron v3.1.13 is not quite as good, but it still looks fine:

<img width="912" alt="Screen Shot 2019-08-26 at 20 25 54" src="https://user-images.githubusercontent.com/759911/63734150-caf49700-c840-11e9-99e7-55d3ff2ff799.png">

### Actual Behavior

On Electron v4.2.9, however, font rendering is much too thin:

<img width="912" alt="Screen Shot 2019-08-26 at 20 24 10" src="https://user-images.githubusercontent.com/759911/63734174-d9db4980-c840-11e9-93ec-3be1a7367bba.png">

Yikes!

### To Reproduce

I’ve set up [a repository](https://github.com/lexi-lambda/electron-4.x-font-smoothing-repro) with the above minimal example. To reproduce the issue, run the following commands on a machine running macOS 10.14:

```sh
$ git clone git@github.com:lexi-lambda/electron-4.x-font-smoothing-repro.git
$ cd electron-4.x-font-smoothing-repro
$ npm install
$ npm start
```

### Additional Information

The original issue for this bug was #14948, and supposedly it was backported to 4.x in #17737. However, as various people have reported in https://github.com/microsoft/vscode/issues/59887#issuecomment-508186862 and https://github.com/electron/electron/pull/17737#issuecomment-486582861, the issue is still present as of Electron v4.2.9.

**Comment by miniak** [comment]
Electron 4 is not supported anymore: https://electronjs.org/blog/electron-7-0#end-of-support-for-4xy

**Comment by miniak** [comment]
The problem is that https://skia-review.googlesource.com/c/skia/+/157566 wasn't back-ported properly. This part of the patch got lost
```
+                if (noSmoothBitmap[x][y] != smoothPixel) {
+                    smoothBehavior = SmoothBehavior::some;
                 }
```
