### ISSUE TITLE
Application hung-up when call BrowserWindow.addDevToolsExtension(..) after upgrade to 6.0.4

### ISSUE THREAD

**Issue by dave3068** [electron/electron#19978]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.4
* **Operating System:**
  * Windows 10 (1803)
* **Last Known Working Electron version:**
  * 5.0.10

### Expected Behavior
Application can startup normally, and the extensions works fine.

### Actual Behavior
Application hung-up at BrowserWindow.addDevToolsExtension(..), when loading any chrome extensions.

### To Reproduce
```
app.on('ready', ()=>{
    console.log('ready')

    if (options.debug) {
        let exts = BrowserWindow.getDevToolsExtensions();
        console.log(exts);
        // react 调试工具目录
        let reactDevToolDir = path.join(os.homedir(),
            'AppData/Local/Google/Chrome/User Data/Default/Extensions/fmkadmapgofadopljbjfkapdkoienihi'
            // 'AppData/Local/Google/Chrome/User Data/Default/Extensions/ckkdlimhmcjmikdlpkmbgfkaikojcbjk'
            // 'AppData/Local/Google/Chrome/User Data/Default/Extensions/dnhjfclbfhcbcdfpjaeacomhbdfjbebi'
        );
        // 当本地Chrome有安装 React插件 时，加载到壳程序中
        if (fs.existsSync(reactDevToolDir)) {
            // 找到具体的插件版本目录，如：".../fmkadmapgofadopljbjfkapdkoienihi/3.6.0_0"
            let versionDir: string = null;
            let versionDirs = fs.readdirSync(reactDevToolDir);
            if (versionDirs && versionDirs.length) {
                versionDir = versionDirs[versionDirs.length - 1];
            }
            console.log('prepare react debug tool');
            // 启用 react 调试工具
            BrowserWindow.addDevToolsExtension(         // <---------- hung-up here....
                path.join(reactDevToolDir, versionDir)
            );
            console.log('react debug tool enabled');
        }
        exts = BrowserWindow.getDevToolsExtensions();
        console.log(exts);
    }

    new MainWindow().show();
});
```

### Screenshots
![image](https://user-images.githubusercontent.com/2647956/63755243-d4d1d500-c8e8-11e9-9c7d-27a777e107c3.png)

![image](https://user-images.githubusercontent.com/2647956/63755965-229b0d00-c8ea-11e9-92db-0cdf9b2a590d.png)

**Comment by rob10e** [comment]
I have also run into this problem.

I have tried it with the react and redux extensions, both manually as per the documentation and using the extension loader. Deleting the electron cache directory for the app: C:\Users<USER>\AppData\Roaming<APPNAME> fixes it for one more run, then I have to delete it again to run it again.

I have found that Electron 5.0.11 not have this problem.

**Comment by kyle-mcknight** [comment]
> I have also run into this problem.
> 
> I have tried it with the react and redux extensions, both manually as per the documentation and using the extension loader. Deleting the electron cache directory for the app: C:\Users\AppData\Roaming fixes it for one more run, then I have to delete it again to run it again.
> 
> I have found that Electron 5.0.11 not have this problem.

I am using 6.010 and have the issue still all the time.

**Comment by zarubond** [comment]
For me it works if I add the extension only after I create a BrowserWindow.

**Comment by ivancuric** [comment]
> For me it works if I add the extension only after I create a BrowserWindow.
Doesn't work here, using Electron 7.11 on Windows 10.

There are a lot of changes to the extension system in https://github.com/electron/electron/releases/tag/v6.0.0. This is probably a regression.

**Comment by omar-caraveo** [comment]
This seems to be the reason why my dev electron window will not render/show, when following the simple "getting started" guide for `electron-react-boilerplate` (https://electron-react-boilerplate.js.org/).

Two workarounds that work for me:
1. Edit `your-project-name\app\main.dev.ts`;
change `const extensions = ['REACT_DEVELOPER_TOOLS', 'REDUX_DEVTOOLS']`
to `const extensions = []`
2.  Set Windows Color setting to "Light" (Settings > Personalization > Colors)

🍻

**Comment by dave3068** [comment]
Finally, I'v upgrade to 9.1.x and using `session.defaultSession.loadExtension(..)`  instead.
