### ISSUE TITLE
Child window maximizes parent window on click when always on top enabled

### ISSUE THREAD

**Issue by Zyles** [electron/electron#19995]
### Issue Details

* **Electron Version:**
  * 5.0.10
* **Operating System:**
  * Win 10

### Expected Behavior

Parent window should not maximize when clicking around in child window

### Actual Behavior

Parent window is maximizing from the windows program bar instead of staying minimized

### To Reproduce

```
ipcMain.on('showChildWindow', function (e, data) {
  const modalPath = process.env.NODE_ENV === 'development'
    ? process.env.WEBPACK_DEV_SERVER_URL + '#/rapid'
    : `app://${__dirname}/index.html#/rapid`
  let childWin= new BrowserWindow(
    {
      parent: mainWindow,
      modal: false,
      show: true,
      width: 800,
      height: 320,
      webPreferences: {
        nodeIntegration: true,
        webSecurity: false
      }
    })

  childWin.setAlwaysOnTop(true)

  childWin.on('ready-to-show', () => {
    childWin.show()
  })

  childWin.on('close', function () { rapidWin = null })
  childWin.loadURL(modalPath)
})
```

### Additional Information

When I create a child window that I want to open and interact with outside of the main window it will not let me without the main window (which is minimized) opening itself up behind my AlwaysOnTop child window.

It should stay minimized until I actually click on it in the windows program bar.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
