### ISSUE TITLE
loadURL() test for DNS not resolved fails on WOA

### ISSUE THREAD

**Issue by jkleinsc** [electron/electron#20008]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * master, 6-0-x
* **Operating System:**
  * Windows on Arm (64 bit)
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
The test `webContents module loadURL() promise API rejects when loading fails due to DNS not resolved` passes on Windows on Arm.

### Actual Behavior
On Windows on Arm, the test `webContents module loadURL() promise API rejects when loading fails due to DNS not resolved` fails with:
```not ok 256 webContents module loadURL() promise API rejects when loading fails due to DNS not resolved
  AssertionError: expected [Error: ERR_NAME_RESOLUTION_FAILED (-137) loading 'https://err.name.not.resolved/'] to have property 'code' of 'ERR_NAME_NOT_RESOLVED', but got 'ERR_NAME_RESOLUTION_FAILED'
      at C:\vsts-agent-win-x86-2.148.2\_work\1\s\src\electron\spec\node_modules\chai-as-promised\lib\chai-as-promised.js:302:22
      at async Context.<anonymous> (C:\vsts-agent-win-x86-2.148.2\_work\1\s\src\electron\spec\api-web-contents-spec.js:58:7)
```
Above error from test on WOA hardware here: https://github.visualstudio.com/electron/_build/results?buildId=48711&view=logs&jobId=12f1170f-54f2-53f3-20dd-22fc7dff55f9&taskId=5caf77c8-9b10-50ef-b5c7-ca89c63e1c86&lineStart=447&lineEnd=448&colStart=1&colEnd=1

### To Reproduce
Run the test suite on a WOA build on WOA hardware, specifically the command:
`npm run test -- --ci -g "due to DNS not resolved"`

### Screenshots
N/A

### Additional Information
It looks like the issue is that the test on WOA is returning `ERR_NAME_RESOLUTION_FAILED` instead of `ERR_NAME_NOT_RESOLVED` because the error is something other than `WSAHOST_NOT_FOUND` or `WSANO_DATA`: https://cs.chromium.org/chromium/src/net/dns/host_resolver_proc.cc?rcl=89bbc693aa8910f53c914b2b99074b21dfc1bac2&l=241

**Comment by tdusnoki** [comment]
I ran tests on Windows on Arm (64 bit) system and enabled this one as well to check if the issue still exists. This test seems to pass on the current version of 6-0-x branch.
Could you test this on your WoA hardware to verify if it works?
