### ISSUE TITLE
Let users change language for the native spellcheck (as native text inputs in MacOS)

### ISSUE THREAD

**Issue by andresazp** [electron/electron#20016]
I find very aggravating that many if no tall apps will not allow users to change the language for the spell check in text inputs, even though they use the native MacOS spellcheck. **Users should have access to the native spellcheck controls (including alguange) on all text inputs that will enable that feature.**

**This is a problems for users how have the system language set in one language but need to write write in other languages – imagine chat and social media apps, and everything you write now is highlighted, or worse: autocorrected because you can't change the native spellcheck language on the fly**

This will probably be less practical for text editors that I hope already have a solution, but any app that has paragraph text inputs would benefit from this.

**Comment by MarshallOfSound** [comment]
Electron does not use the native spellchecker on macOS.  We use Chromium's spell check which users control with `setSpellCheckProvider` --> https://github.com/electron/electron/blob/master/docs/api/web-frame.md#webframesetspellcheckproviderlanguage-provider

This is on apps to implement, the backing APIs are already in Electron
