### ISSUE TITLE
Calling showOpenDialogSync/showSaveDialogSync the second time will trigger a popup in Linux

### ISSUE THREAD

**Issue by Woofthecat** [electron/electron#20025]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.x
* **Operating System:**
  * Ubuntu 18.10 x64
* **Last Known Working Electron version:**
  * 5.0.x

### Expected Behavior
Opening the open or save dialog does not show a popup.

### Actual Behavior
The problem happens when the dialog is opened the second time. It will show a popup, that "dialog.title" is ready and the dialog will be placed behind the main window.

### To Reproduce
https://gist.github.com/978281d6e52064a7f1b6f54e75571883

### Screenshots
![popup](https://i.imgur.com/9sVPqVP.png)

**Comment by ckerr** [comment]
I can't repeat it consistently, but it happened for me once each in 6.0.6 and 7.0.0-beta.3 when testing on Ubuntu 19.04. The dialogs behaved correctly in ~10 more 6.0.6 test runs so I'm not sure what triggers this.

**Comment by chinenual** [comment]
I can reproduce this with 7.1.10, 7.2.4 and 8.2.5.

Does anyone have a workaround?

**Comment by dvalter** [comment]
@ckerr I've tested [a slightly updated repro](https://gist.github.com/dvalter/9d69b292b50bc938a92b7d4d4ac13060) on Arch Linux with a different WMs. 
I could reproduce it with electron v11.1.1 and:
* GNOME 3.38 (Mutter)
* KDE 5.20 (KWin)
* Deepin (Deepin WM)
* MATE 1.24.1 (Marco)

But I could not reproduce it with electron v11.1.1 and:
* XFCE 4.16 (XFWM4)
* Openbox 3.6.1

Popup itself is specific for GNOME/Mutter, but for the rest of repros a file dialog window appears not in focus.
I believe it's still an issue for a number of Linux users. Could you please give it another try?

**Comment by jes** [comment]
I'm having the same problem. Not only is the second-and-subsequent save dialog opened in the background, but it seems like it's not even a modal. I can close the main window while the save dialog is still open. It seems like it's ignoring the BrowserWindow argument. I'm on Electron 18.0.3.

**Comment by DmitryAstafyev** [comment]
Any movement with this issue? I have same bug
```
- os: archlinux
- electron: 18.0.4
```

**Comment by DmitryAstafyev** [comment]
VSCode also effected - https://github.com/microsoft/vscode/issues/150159

**Comment by EmiM** [comment]
Same happens for me.
Ubuntu 21.10
electron@18.3.1

**Comment by pwespi** [comment]
Still affecting us.
```
Ubuntu 22.04
Electron 20.1.4
```

**Comment by lxt-ing** [comment]
I find a temporary solution from the same issues [#32857](https://github.com/electron/electron/issues/32857),  after install the extension , it works fine. however I find another problem affect me is that the native dialog in Linux can be blur and it will be hidden behine the main windows.
