### ISSUE TITLE
Mac App Store rejects app with non-public API usage

### ISSUE THREAD

**Issue by lesleyandreza** [electron/electron#20026]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.

### Issue Details

* **Electron Version:** 
 * 6.0.5

### Rejection Email
Dear Developer,

We identified one or more issues with a recent delivery for your app, "ProDoctor Cloud Consultórios" 1.0.5 (867). Please correct the following issues, then upload again.

**ITMS-90338: Non-public API usage** - The app references non-public symbols in Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework: _fileport_makefd, _fileport_makeport. If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed. For further information, visit the Technical Support Information at [http://developer.apple.com/support/technical/](http://developer.apple.com/support/technical/)

Best regards,

The App Store Team

**Comment by lubo08** [comment]
I can confirm. I have the same issue here. Any advice about workaround?

**Comment by MarshallOfSound** [comment]
Duplicate #20027

It looks like Apple it trialing some new private API detection stuff.  We're aware and investigating
