### ISSUE TITLE
generating latest-linux.yml, latest-mac.yml

### ISSUE THREAD

**Issue by trae-op** [electron/electron#20022]
For **latest-linux.yml** format of file **.AppImage** default. And for **latest-mac.yml** format of file **.zip**. 
Can I change this? 
For example **latest-mac.yml** change to **.dmg** format, and **latest-linux.yml** change to **.deb**
![image](https://user-images.githubusercontent.com/12648541/63926137-00bd9980-ca54-11e9-80af-ce075348d28c.png)
![image](https://user-images.githubusercontent.com/12648541/63926230-277bd000-ca54-11e9-9dd8-5703b922da66.png)

**Comment by MarshallOfSound** [comment]
These yaml files are not part of `electron` core.  I'm guessing you are using some kind of third party build tool which is generating these for some kind of update flow?  Regardless, these files are not generated or consumed by Electron directly, you should raise this with whichever project generates these
