### ISSUE TITLE
Electron 7 beta fails to install

### ISSUE THREAD

**Issue by mubaidr** [electron/electron#20039]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * electron@7.0.0-beta.3
* **Operating System:**
  * Windows 10, 18950
* **Last Known Working Electron version:**
  * electron@6.0.2

### Expected Behavior
electron@7.0.0-beta.3 should install fine. 

### Actual Behavior
electron@7.0.0-beta.3 fails to install

### To Reproduce
Try installing electron@7.0.0-beta.3 on Windows. 

### Additional Information
```bash
npm i -D electron@beta

> electron@7.0.0-beta.3 postinstall D:\Current\temp\node_modules\electron
> node install.js

(node:12560) UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted, lstat 'C:\Users\username\AppData\Local\Temp\electron-download-fVvnDg\electron-v7.0.0-beta.3-win32-x64.zip'
(node:12560) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12560) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ electron@7.0.0-beta.3
```

**Comment by vladimiry** [comment]
EPERM error on Window is known to happen when there is concurrent and frequent access to the files, even if just access to read operation, see some details [here](https://github.com/isaacs/node-graceful-fs/pull/119). Means it could be an issue of `npm` itself doesn't handle properly the EPERM errors on Windows. So try running the command multiple times.

**Comment by ckerr** [comment]
This doesn't appear to be an Electron issue -- several other packages have also hit this when being installed by npm on Windows. 

https://github.com/nodejs/node/issues/17080 is an upstream Node issue reported on this, which points to how one user got things working by following the steps described in https://stackoverflow.com/questions/20711240/how-to-completely-remove-node-js-from-windows

I'm going to close this ticket since it doesn't appear to be an Electron issue, but I hope the links above help you in getting things working again!

**Comment by mubaidr** [comment]
Since the electron v6 was installing fine on my system, this made think that electron v7 beta installer had issue. But now I beleive installation script has been updated for beta which somehow is effected by the outstanding nodejs issue.

Thanks for the info.

**Comment by xielehe** [comment]
I have the same issue.

**Comment by MontyZhao** [comment]
Gays, if you are using "cnpm" instead of "npm" to install the electron, this question is alway appear in version 6.1 - 7.0 .   

So, it's easy to resulve the issue. USE "npm". 

This mistake had taked off six hours of my life! 

/(ㄒoㄒ)/~~
