### ISSUE TITLE
tray icon don't close for ubuntu 18.04.3

### ISSUE THREAD

**Issue by trae-op** [electron/electron#20043]
I used the code
`
app.on('before-quit', function (evt) {
    tray.destroy();
});
`
The app closes but icon stay tray. 
Also when minimizing the app closes and I try open does not displayed.
For other OS like (mac-os, win-10), everything is OK.
electron: v6.0.1

**Comment by ckerr** [comment]
I tried making a quick `electron-quick-start` clone with a tray and added the `app.on('before-quit')` code listed above:

https://gist.github.com/d797a5fec00f142f7153aec8ebaa1a83

This gist works for me on Ubuntu 19.04 using the default gnome desktop -- the tray disappears when the application exits.

@trae-op, could you test this gist on your system?

**Comment by trae-op** [comment]
> I cloned `electron-quick-start`, added a tray, added the `app.on('before-quit'` code listed above, and pinned the Electron version in package.json to 6.0.1:
> 
> https://gist.github.com/d797a5fec00f142f7153aec8ebaa1a83
> 
> This gist works for me on Ubuntu 19.04 using the default gnome desktop -- the tray disappears when the application exits.
> 
> @trae-op, could you test this gist on your system?
I tried your version on Ubuntu 18.04.3 and it's OK, it's work. My app contained Incorrect code for event `minimize` and `close` for mainWindow
