### ISSUE TITLE
"affinity" have a bug

### ISSUE THREAD

**Issue by wuwei2150** [electron/electron#20047]
repro steps：
1.git pull "electron-quick-start" 
2.modify source:
main.js:
function createWindow () {
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      affinity: "main", //add
      nodeIntegration :true
    }
  })

renderer.js
const ffi = require('ffi')
ffi.ffiType

3."electron ." run app
4.refresh page
5.have a error：
.D:\Project\electron-quick-start\node_modules\bindings\bindings.js:121 Uncaught Error: Module did not self-register.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (internal/modules/cjs/loader.js:620)
    at tryModuleLoad (internal/modules/cjs/loader.js:559)
    at Function.Module._load (internal/modules/cjs/loader.js:551)
    at Module.require (internal/modules/cjs/loader.js:658)
    at require (internal/modules/cjs/helpers.js:20)
    at bindings (D:\Project\electron-quick-start\node_modules\bindings\bindings.js:112)
    at Object.<anonymous> (D:\Project\electron-quick-start\node_modules\ref\lib\ref.js:5)

6. i test version 3.1.13   4.2.10   5.0.10   6.0.6,all have this bug

7. #https://github.com/kapetan/electron-drag/issues/10#issue-339231007

**Comment by MarshallOfSound** [comment]
You're loading a native module twice in the same process, this is why affinity is experimental and will be removed at some point in the future.  You need to either stop using that native module or stop using affinity

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

**Comment by ThomasMoutel** [comment]
> You're loading a native module twice in the same process, this is why affinity is experimental and will be removed at some point in the future. You need to either stop using that native module or stop using affinity
Sorry, but I'm having difficulties to see the direct link between having an experimental feature and having to remove it in the future. I sincerely hope that affinity is not the new PDF, in terms of feature deprecation.

**Comment by MarshallOfSound** [comment]
@ThomasMoutel Please see https://github.com/electron/electron/issues/18397.  The intention is to remove Affiny

**Comment by kirilpopov** [comment]
> @ThomasMoutel Please see #18397. The intention is to remove Affiny

How about all the apps that depend on affinity (try opening 100 windows without affinity) and don't use page navigation and native modules - this is basically a game over for some apps.

**Comment by jaehayoo** [comment]
Our application is opening 25~50 game windows. 
This would not be possible without affinity.
Please consider keeping the affinity option with patching the bug.
Thx.
