### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by changesunline** [electron/electron#20058]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* Electron Version: 6.07
* Operating System: Windows 10

### Expected Behavior
I'd expect to access process object in my renderer process
[https://electronjs.org/docs/tutorial/first-app](url)

### Actual Behavior
`webPreference: {
      nodeIntergration: true
    }`
It's useless, Chrome dev tools throw ReferenceError while accessing to process object

> `Uncaught ReferenceError: process is not defined`

**Comment by MarshallOfSound** [comment]
`webPreference` is a typo, it should be `webPreferences`

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
