### ISSUE TITLE
openDevTools() not working since version 6.0.0

### ISSUE THREAD

**Issue by f0zi** [electron/electron#20069]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * Tried versions 6.0.0, 6.0.6 and 6.0.7
* **Operating System:**
  * Windows 7 x64
* **Last Known Working Electron version:**
  * 5.0.10

### Expected Behavior
I'm trying to open the dev console.

### Actual Behavior
Dev console does not open.

### To Reproduce
- Clone the Electron quick start from here: https://github.com/electron/electron-quick-start It's currently using electron 6.0.6.
- `npm install`
- `npm start`
- Press Ctrl+Shift+I or select from the menu to toggle the dev tools
- nothing happens

Uncommenting line 23 in main.js (`mainWindow.webContents.openDevTools()`) does not help either.

Older version:
- in package.json, set devDependencies/electron to 5.0.10
- `npm install`
- `npm start`
- Dev tools open just fine.

### Additional Information

_Edit:_ Just updated my Google Chrome to 76 (from 75) and the dev tools open just fine (in both).

**Comment by uasabi-rober** [comment]
Anyone having this issue? Im reproducing exactly this steps with electron-quick-start and dev tools never opens.

Node.js 12.4.0, 
Chromium 76.0.3809.146
Electron 6.0.9.

**Comment by charmer1989** [comment]
I have the same issue!

**Comment by sarajbosna2012** [comment]
same here

**Comment by grozdanovgg** [comment]
Same issue here.
Up to Electron 5.0.12 openDevTools() works fine. 
After update to 6.0.0 or up - openDevTools() does not work. I wrapped the call in a try/catch, and logged the result. The method is passing successfully, no errors are thrown, but the dev tools are just not opening. Neither on the renderer nor for the main process.

**Comment by oumad** [comment]
I'm having exact same issue here.
Using both `mainWindow.webContents.openDevTools()` through a menu item or `require('electron').remote.getCurrentWindow().toggleDevTools()` in the renderer, both don't work.
I'm on electron 6.1.5
electron-packager 14.1.0

**Comment by jjustin3** [comment]
Had this problem recently and found something that worked for me...
I assume y'all are on Windows, so try running your terminal/command prompt/powershell in a non-admin mode. This eliminated the issue of devtools not opening up for me.

**Comment by sarajbosna2012** [comment]
> Had this problem recently and found something that worked for me...
> I assume y'all are on Windows, so try running your terminal/command prompt/powershell in a non-admin mode. This eliminated the issue of devtools not opening up for me.
> 
> **Edit:** It is worth noting that I also had this problem on an older version and thought it was the terminal I was using that was causing the issue. This belief was due to the me switching from the old terminal to git-bash, which alleviated the problem.
> However, looking back I now realize that the old terminal I was using was running in admin and git-bash wasn't until I started running it in admin a week ago. When I changed this a week ago, the problem started again. Therefore, this problem isn't specific to a particular Electron version (could be the past few perhaps?). I hope this background info will help someone out in the future until the underlying issue is determined.

i solved the issue the same way. I was running cmd prompt in admin mode.

**Comment by oumad** [comment]
Digging a bit more I realized for my users it works fine if they open the app locally, cause normally we use a remote directory for the app, that way I can update it in real time for all my team. So this could be linked to the admin access mentioned by @jjustin3 I hope there is a workaround for this use-case.

**Comment by krolson** [comment]
This is more than just an annoyance since my electron app needs to run elevated in order to function properly - now I just can't use dev tools. So the "workaround" of using a non-admin console doesn't work for me. Any other options?

I have also repro'd where the exact same app code either shows or does not show the developer tools depending on if I run "yarn dev" from an admin/non-admin console (Windows 10 OS).

**Comment by pauloricardofagundesjr** [comment]
I have the same issue and open prompt with admin doesn't work for me too.
does anyone have other ideia?

**Comment by guhuangjin** [comment]
I ran into the same problem on some Windows 7 computers, but on others I had no problem with either Windows 7 or Windows 10.

**Comment by Paosder** [comment]
Same issue is here! Is there any other workaround to overcome this?!

**Comment by warrenseine** [comment]
I ran into the problem running Windows in a VM under macOS, files shared from the host through a mapped network drive. I found out that `setDevToolsWebContents` (documented [here](https://www.electronjs.org/docs/api/web-contents#contentssetdevtoolswebcontentsdevtoolswebcontents)) make DevTools appear.

Copying the example for simplicity:

```js
const { app, BrowserWindow } = require('electron')

let win = null
let devtools = null

app.once('ready', () => {
  win = new BrowserWindow()
  devtools = new BrowserWindow()
  win.loadURL('https://github.com')
  win.webContents.setDevToolsWebContents(devtools.webContents)
  win.webContents.openDevTools({ mode: 'detach' })
})
```

Tested with Electron 7.1.4.

**Comment by f0zi** [comment]
I can confirm that the issue only appears when the project is running from a network drive. If I move it to a local drive the devtools open just fine.

Also, I tested version 8.0.0, same issue.

**Comment by juliuswigo** [comment]
> ```js
> let devtools = null
> ```



> I ran into the problem running Windows in a VM under macOS, files shared from the host through a mapped network drive. I found out that `setDevToolsWebContents` (documented [here](https://www.electronjs.org/docs/api/web-contents#contentssetdevtoolswebcontentsdevtoolswebcontents)) make DevTools appear.
> 
> Copying the example for simplicity:
> 
> ```js
> const { app, BrowserWindow } = require('electron')
> 
> let win = null
> let devtools = null
> 
> app.once('ready', () => {
>   win = new BrowserWindow()
>   devtools = new BrowserWindow()
>   win.loadURL('https://github.com')
>   win.webContents.setDevToolsWebContents(devtools.webContents)
>   win.webContents.openDevTools({ mode: 'detach' })
> })
> ```
> 
> Tested with Electron 7.1.4.

Works also on Electron v8. Thanks! _This guy needs a price_

**Comment by abettadapur** [comment]
I have this same issue on Electron 8.0.2, and can confirm that running the application from a non-elevated shell makes the devtools appear

Does anyone know why this is the case?

**Comment by sbowler** [comment]
I ran into this issue trying to run from a network drive as well. Would be interested to know why this has problems and if there's something I can do to prevent it.

**Comment by Tobias-Keller** [comment]
in 9.0.0-beta.7 the dev tools also not appear if app is running as admin

**Comment by wuzhong233** [comment]
I had the same problem today. I was using vscode to debug when this occurred, but when I ran the program as' NPM start ', I was able to open the developer tools normally

**Comment by j253wang** [comment]
> I have this same issue on Electron 8.0.2, and can confirm that running the application from a non-elevated shell makes the devtools appear
> 
> Does anyone know why this is the case?

I'm seeing the same issue as well on Electron 8.0.2. and 8.2.1 when running from an admin comand prompt or VSCode. The dev tools aren't opening from the menu either. It works fine if running with non-elevated privileges. Would also want to know why this is.

**Comment by emusgrave** [comment]
I was having an issue with this after upgrading to Electron 8. I could only get devtools opened if I hit ctrl-shit-i twice in fast succession, but things still didn't seem to be running correctly after that.

I tracked the problem down to a previous 'fix' that I had put in, where I was not calling loadURL() until I had received the 'devtools-opened' event. Once I removed that fix and just called loadURL normally, my problem went away.

Here's the original issue which led me down the 'devtools-opened' path. I'm linking to my latest comment which describes how I reverted my fix.
https://github.com/electron/electron/issues/2379#issuecomment-612303700

**Comment by 21mehran** [comment]
hey I am using electron version 10.
 I too have the same issue but I managed to access the devtools in the browser following these steps.
~right click the index.html and open it in the browser
~ctrl+shift+I and there you are.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by Codindy** [comment]
Hi, 
I also have the problem of devtools that don't load, so I add 

`mainWindow.webContents.openDevTools({ mode: 'detach' })` 
after
`mainWindow.loadFile('index.html')` 

and it works for me

**Comment by v-dawg** [comment]
Happened to me when I updated to 18.0.3 from 16

**Comment by devqazi** [comment]
This is happening on 18.x.x. Had to downgrade to 16 (from above comment) to make it work.

**Comment by kumavis** [comment]
i had an issue opening the dev tools when using electron via `npx electron file.js`. i resolved it by installing `electron` and running it via `yarn electron file.js`

**Comment by asger-finding** [comment]
This is my implementation of a fix for those stuck on low electron versions or having issues in recent releases. It is by no means perfect (you can open two DevTools instances on linux but `webContents.isDevtoolsOpen` doesn't return true if `setDevToolsWebContents` is reassigned)

```typescript
const openDevtools = (window: Electron.BrowserWindow, mode: Electron.OpenDevToolsOptions['mode'] = 'right'): void => {
    // Fixes https://github.com/electron/electron/issues/20069 for electron < 13.5.0
    if (process.platform === 'linux') {
        const devtoolsWindow = new BrowserWindow();
        devtoolsWindow.setMenuBarVisibility(false);
        window.webContents.setDevToolsWebContents(devtoolsWindow.webContents);
        mode = 'detach';

        // Ensure that devtools closes when the parent is closed.
        window.once('closed', () => devtoolsWindow.destroy());
    }

    window.webContents.openDevTools({ mode });
};
```

**Comment by cbossi** [comment]
In my case the problem was that before executing `openDevTools()` the *open state* of devtools was already `true`, even though it was not visible. In this case, `openDevTools()` does nothing (at least on Windows).

Solution 1: always execute `closeDevTools()` before executing `openDevTools()`:
```
window.webContents.closeDevTools();
window.webContents.openDevTools();
```

Solution 2: implement a toggle functionality:
```
if (window.webContents.isDevToolsOpened()) {
  window.webContents.closeDevTools();
} else {
  window.webContents.openDevTools();
}
```

**Comment by todesking** [comment]
I have the same problem with `electron@25.1.0`. Neither `setDevToolsWebContents` solution nor "close-and-open" solution worked for me.

However,  I discovered that the "wait-and-open" solution works for some reason.

```
    setTimeout(() => {
      mainWindow.webContents.openDevTools();
    }, 1000) // wait long enough
```

**Comment by poWERmaXray** [comment]
Same issue with 32.0.2, I resolve by enable menu bar then force realod
