### ISSUE TITLE
Minimum window sizes not respected after updating to v6.0.7

### ISSUE THREAD

**Issue by AssetKid** [electron/electron#20068]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  6.0.7
* **Operating System:**
  *  Windows 10 (1903)
* **Last Known Working Electron version:**
  *  6.0.5

### Expected Behavior

Minimum and maximum window sizes should be respected.

### Actual Behavior

Minimum and maximum window sizes do not apply.

### To Reproduce

Create a simple project using v6.0.5 (Last known working version) then upgrade electron to v6.0.7

### Additional Information

```js
  win = new BrowserWindow({
    title: 'App Name',
    width: 625,
    height: 600,
    minWidth: 625,
    minHeight: 600,
    autoHideMenuBar: true,
    backgroundColor: '#FFFFFF',
    webPreferences: {
      nodeIntegration: true,
      webSecurity: false
    }
  })
```

**Comment by AssetKid** [comment]
`v6.0.6` is also affected.

This issue might have originated from this commit - https://github.com/electron/electron/commit/fb82bfa7071bb5cb3da277879c0c87be1e636064

**Comment by codebytere** [comment]
cc @brenca ☝️

**Comment by arantes555** [comment]
I can confirm we also see a similar issue on electron@6.0.9, the size of electron windows on Windows does not respect the values passes upon creation. Rollback to 6.0.5 seems to fix the problem for us.

**Comment by roaringUnicorn** [comment]
Same here with electron@6.0.9. All my windows are smaller than expected...

**Comment by BENLKAMLENourdine** [comment]
same problem encountered using electron@6.0.9

**Comment by tex0l** [comment]
Same here with `electron@6.0.9`

**Comment by Hubz-m** [comment]
Same problem here ☝️

**Comment by viclafouch** [comment]
Same problem here !

**Comment by Celebes** [comment]
Same problem on version 7.1.1:
* window starts with wrong resolution (611x593 instead of 625x600)
* window can be resized even further from starting point far beyond min values, down to 595x554
* trying to offset errors by setting minWidth to 625 + (625-595) and minHeight to 600 + (600-554) which is 655x646 and leaving width and height as 625x600 partially fixes the problem: starting window resolution is correct (625x600) and can't be resized down, but at the same time resize cursor is not showing or only showing for a moment (flickering)

**Comment by arantes555** [comment]
I confirm the same problem still happens with electron@7.

It is very annoying, I am still stuck on 6.0.5 to avoid this.

**Comment by Celebes** [comment]
Same problem using electron@8.0.2

**Comment by NunoCuradoFuze** [comment]
Still happens with Electron@11.2.3. minHeight is not being respected on Windows OS, even using `useContentSize: true` flag. On Mac OS it works fine.

**Comment by pushkin-** [comment]
Repros with Electron 12. Calling `setMinimumSize(...)` directly seems to work around this

**Comment by pushkin-** [comment]
I believe this is still an issue in v21
