### ISSUE TITLE
app.commandline.appendSwitch doesn't

### ISSUE THREAD

**Issue by sdetweil** [electron/electron#20063]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
3.1.10
* **Operating System:**
Ubuntu 18.04.3 LTS  armv7l odroid
??

### Expected Behavior
want to setup external debugger
need to pass either or both 
	app.commandLine.appendSwitch("inspect", "5858");	
        app.commandLine.appendSwitch("remote-debugging-port", "8315")		
	app.commandLine.appendSwitch("autoplay-policy", "no-user-gesture-required");

the  autoplay-policy flag is appended (shown in process list), the others are not, and the ports are not in use

### Actual Behavior
debug options not passed 

### To Reproduce
pass those three lines to java script app start , before BrowserWindow 

### Additional Information

process list after window open 
```
odroid   11133 11132  0 09:50 pts/1    00:00:01 node /home/odroid/MagicMirror/node_modules/.bin/electron js/electron.js dev
odroid   11139 11133 25 09:50 pts/1    00:04:07 /home/odroid/MagicMirror/node_modules/electron/dist/electron js/electron.js dev
odroid   11141 11139  0 09:50 pts/1    00:00:00 /home/odroid/MagicMirror/node_modules/electron/dist/electron --type=zygote --no-sandbox
odroid   11175 11139  0 09:50 pts/1    00:00:01 /home/odroid/MagicMirror/node_modules/electron/dist/electron --type=gpu-process --no-sandbox --gpu-preferences=KAAAAAAAAACAAACAAQAAAAAAAAAAAGAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAA --service-request-channel-token=4202EF29FA404675B3429FC3336ECA06
odroid   11178 11141 13 09:50 pts/1    00:02:12 /home/odroid/MagicMirror/node_modules/electron/dist/electron --type=renderer **--autoplay-policy=no-user-gesture-required** --no-sandbox --service-pipe-token=EA2CACC8DF317954766BCDF511452848 --lang=en-US --app-path=/home/odroid/MagicMirror/node_modules/electron/dist/resources/default_app.asar --node-integration=false --webview-tag=false --no-sandbox --background-color=#000000 --num-raster-threads=4 --enable-main-frame-before-activation --enable-compositor-image-animations --service-request-channel-token=EA2CACC8DF317954766BCDF511452848 --renderer-client-id=4 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
odroid   11185 11141 13 09:50 pts/1    00:02:12 /home/odroid/MagicMirror/node_modules/electron/dist/electron --type=renderer --autoplay-policy=no-user-gesture-required --no-sandbox --service-pipe-token=7CB4C85A696FD6ADC29406410E708056 --lang=en-US --app-path=/home/odroid/MagicMirror/node_modules/electron/dist/resources/default_app.asar --num-raster-threads=4 --enable-main-frame-before-activation --enable-compositor-image-animations --service-request-channel-token=7CB4C85A696FD6ADC29406410E708056 --renderer-client-id=6 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
```

**Comment by codebytere** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on, v3, is no longer supported. In order for us to triage this issue, it must be present in a [supported version](https://electronjs.org/docs/tutorial/support).

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
