### ISSUE TITLE
No native build was found 

### ISSUE THREAD

**Issue by EnderDev** [electron/electron#20075]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.3 
**Operating System:**
  * Windows 10 (1903)
* **Last Known Working Electron version:**
  * Unknown

### Expected Behavior
The app should launch.

### Actual Behavior
App doesn't run and aborts with this error
``` App threw an error during load
Error: No native build was found for platform=win32 arch=x64 runtime=electron abi=73 uv=1 libc=glibc
    at Function.load.path (C:\Users\ender\Desktop\Dot Browser\dot-desktop\dist\main\6b4091b_app.js:118703:9)
    at load (C:\Users\ender\Desktop\Dot Browser\dot-desktop\dist\main\6b4091b_app.js:118683:30)
    at Object.<anonymous> (C:\Users\ender\Desktop\Dot Browser\dot-desktop\dist\main\6b4091b_app.js:37119:43)
    at $import (C:\Users\ender\Desktop\Dot Browser\dot-desktop\dist\main\6b4091b_app.js:428:11)
    at locals.require (C:\Users\ender\Desktop\Dot Browser\dot-desktop\dist\main\6b4091b_app.js:411:18)
    at Object.<anonymous> (C:\Users\ender\Desktop\Dot Browser\dot-desktop\dist\main\6b4091b_app.js:37015:17)
    at $import (C:\Users\ender\Desktop\Dot Browser\dot-desktop\dist\main\6b4091b_app.js:428:11)
    at locals.require (C:\Users\ender\Desktop\Dot Browser\dot-desktop\dist\main\6b4091b_app.js:411:18)
    at Object.<anonymous> (C:\Users\ender\Desktop\Dot Browser\dot-desktop\dist\main\6b4091b_app.js:3557:21)
    at $import (C:\Users\ender\Desktop\Dot Browser\dot-desktop\dist\main\6b4091b_app.js:428:11)
```

### To Reproduce
```sh
$ git clone https://github.com/dot-browser/desktop -b master
$ npm install
$ npm run dev
```

### Screenshots
N/A

### Additional Information
I recently updated to the latest beta version of https://github.com/fuse-box/fuse-box

**Comment by MarshallOfSound** [comment]
This is an issue with the build of glibc.  It looks like it's searching for a prebuilt binary for Electron 6 but one doesn't exist.  This isn't an issue with Electron

**Comment by EnderDev** [comment]
So should I be reporting this to the glibc authors?

**Comment by lizwxup** [comment]
> glibc

Can you solve it? i meet the same questions now ,Look forward to your reply.

**Comment by EnderDev** [comment]
No I didn't, I could never find out the issue

**Comment by vaultec81** [comment]
I have a similar error with leveldown. Is there any solution to this? I am not sure whether this is an issue with leveldown or electron specifically.

**Comment by vaultec81** [comment]
@EnderDev Since you are using webpack in the repository you provided. I've been doing research into this issue, it appears that webpack can cause problems with `__dirname`. Some native node modules require `__dirname` to work properly inorder for them to use the native code. (In my case leveldown is module in question). I am actively looking into a fix on the webpack side of things. I will post the results to my findings once completed.

information about webpack and `__dirname` https://github.com/webpack/webpack/issues/1599

**Comment by vaultec81** [comment]
Fix found [here](https://github.com/quepas/electron-leveldown-pouchdb-webpack) with webpack

**Comment by DmitryKRTV** [comment]
I had the same issue with the serial and USB port packages.
Previous answers didn’t solve the issue for me completely.
Node.js v22.14.0
"webpack": "^5.88.2"

This helped me (add lines to webpack.config.ts):
```
externals: {
    usb: 'commonjs usb',
    '@serialport/bindings-cpp': 'commonjs @serialport/bindings-cpp',
},
```

Also works: 
```
 plugins: [new webpack.ExternalsPlugin('commonjs', ['usb'])]
```
But I assume it's basically the same as the previous method
