### ISSUE TITLE
CLI: Don't show window when move "main.js" file to folder

### ISSUE THREAD

**Issue by eAmin** [electron/electron#20077]
Hello

Clone 'electron-quick-start' and try to put main.js and index.html into custom folder, then change the package.json start script like this:
```
"scripts": {
  "start": "electron ./main/main.js"
}
```
After that, electron process is in background, but we can't see any window.
You can't even do this too:
```
"scripts": {
  "start": "electron main.js"
}
```

The bug is showed up from version 6 and It is OK on all version prior to 6. you can change electron version to 5 and Test it again, and all it's going to be normal.

Windows 10 v1903, Electron 6.0.7, Node 12.9.1

**Comment by codebytere** [comment]
This issue does not appear to be one with Electron, rather it seems to be one with how you've organized your files relative to one another.

If you'd like for us to continue to triage this issue, we'll need a standalone repro a maintainer could run to demonstrate the issue.This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by eAmin** [comment]
@codebytere I forked 'electron-quick-start' repo and created new branch. Here is and example app: https://github.com/eAmin/electron-quick-start/tree/cli60x_organizedfiles

Then run the following command for test the app:
```
npm run start:ok // electron .
npm run start:a-fail // electron main.js
npm run start:b-fail // electron ./main/main.js
npm run start:c-fail // electron ./main/main
npm run start:d-fail // electron ./main/
npm run start:e-fail // electron ./main/.
npm run start:f-fail // electron main
```
As you can see, none of them work properly, except the first one.
Thanks.

**Comment by eAmin** [comment]
@codebytere Any progress?

**Comment by eAmin** [comment]
Looks like it's my Windows problem, I've tested on another computer and works like a charm.

**Comment by eAmin** [comment]
@codebytere After spent 1 hr and debugging, in this screenshot you'll see when the program cause crash ("electron . > chrome-inspector-left and electron main.js chrome-inspector-right): 

![Untitled](https://user-images.githubusercontent.com/309560/64991034-52847180-d8e6-11e9-94ea-c7b0f69a0170.jpg)

In that for loop the electron main.js crashed but in electron . program keep running and debugging correctly.

I'm just curios why in just crashed in my OS?

**Comment by codebytere** [comment]
If this is a new issue, you should file a new issue and fill the template there.

**Comment by eAmin** [comment]
@codebytere OK BYE!!!
