### ISSUE TITLE
CORS (webSecurity) doesn't work

### ISSUE THREAD

**Issue by sentialx** [electron/electron#20074]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.5
* **Operating System:**
  * Windows 10 1903
* **Last Known Working Electron version:**
  * unknown

### Expected Behavior
CORS should block requested resource when `webSecurity` option is enabled. On Chrome it works fine.

### Actual Behavior
CORS doesn't work.

### To Reproduce
https://gist.github.com/dc71a808fe8687ba6e0253f9a690f68d

**Comment by MarshallOfSound** [comment]
You are accessing `https://` from `file://`.  This is allowed from Electron as the `file://` protocol has slightly more permissions.  Standard cors when loading `http`/`https` sites works as expected.

Closing as expected behavior

**Comment by sentialx** [comment]
@MarshallOfSound So how can I enable CORS in the `file://` protocol?

**Comment by MarshallOfSound** [comment]
@sentialx What's your use case here?  Using a custom protocol will enable CORS afaik.  E.g. `my-app://`, you can register that using the `protocol` module

**Comment by sentialx** [comment]
@MarshallOfSound I mean, I want my app to be secure and the issue has been reported here https://github.com/wexond/desktop/issues/317

**Comment by lawrencenull** [comment]
I believe electron does use CORS by default for http and https requests, using the file:// protocol to load a page most other browsers sandbox it and don't allow it to make web requests. For example you open a file:// page and it requests jQuery from a CDN it simply doesn't load jQuery in chrome or Mozilla (also think script execution is off). You could implement the same behavior using a sandboxed iframe with everything turned off. You'd have to test it but I think it could be a work around.

**Comment by hbrls** [comment]
Where is the detailed documents for this feature?
