### ISSUE TITLE
Double click the element with style “-webkit-app-region: drag;” to maximize the window leads to an error

### ISSUE THREAD

**Issue by ooyyloo** [electron/electron#20070]
I'm using electron to develop a software. I have a frameless window. I create a titlebar myself using css code "-webkit-app-region: drag;", and I have a "maximize"/"unmaximize" button. The question is that, when I double click the title-bar, the window maximizes, but the "maximize"/"unmaximize" button does not change. I've tried to use ipc to communicate, but there's still a problem. The problem is that after I click the 'maximize' button, the window maximizes, but when I double click the "drag region", it triggers 'maximize' signal of the window. As we know, a normal software should trigger 'unmaximize' when I double click the "drag region".

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

**Comment by omkarbhad** [comment]
> function createWindow() {
>   // Create the browser window.
>   mainWindow = new BrowserWindow({
>    width: 900,
>     height: 745,
>     resizable: false,
>     frame: false,
>     center: true,
>     transparent: true,
>     maximizable: false,     
> 
> > 
> 
>     webPreferences: {
>       preload: path.join(__dirname, 'preload.js'),
> 
>       nodeIntegration: true,
>     },
>   })
> 



use maximize = false in the main window 


use this for buttons 👍 

> 
> const remote = require('electron').remote;
> 
> document.getElementById("mini").addEventListener("click", function (e) {
>      var window = remote.getCurrentWindow();
>      window.minimize();
> });
> 
> document.getElementById("max-btn").addEventListener("click", function (e) {
>      var window = remote.getCurrentWindow();
>      if (!window.isMaximized()) {
>          window.maximize();
>      } else {
>          window.unmaximize();
>      }
> });
> 
> document.getElementById("close").addEventListener("click", function (e) {
>      var window = remote.getCurrentWindow();
>      window.close();
> });



It worked for me !
