### ISSUE TITLE
Build Electron source code error by the command  “ninja -C out/Debug electron”

### ISSUE THREAD

**Issue by Rex-Lliu** [electron/electron#20079]
Hi everyone:
   When I try to build the source code of Electron by the command "ninja -C out/Debug electron"
   I got the error description:
![1](https://user-images.githubusercontent.com/12455127/64150123-25ea4780-ce5a-11e9-9bb9-247cd557f1f4.png)

----------------------------------------------------------------------------------------------------------"../../electron/shell/browser/api/atom_api_web_request_ns.cc(110,17): error: member reference base type '
const content::ResourceType' is not a structure or union
  if (info->type.has_value())
      ~~~~~~~~~~^~~~~~~~~~
../../electron/shell/browser/api/atom_api_web_request_ns.cc(111,44): error: member reference base type '
const content::ResourceType' is not a structure or union
    details->Set("resourceType", info->type.value());"
----------------------------------------------------------------------------------------------------------
I have no idea about this, I just follow this [guide book](https://github.com/electron/electron/blob/v7.0.0-beta.3/docs/development/build-instructions-gn.md) step by step,It went smoothly until the last step.So, anyone helped me solve this problem? Thanks a lot.

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
