### ISSUE TITLE
Electron desktopCapturer capture sources from all desktops/workspaces

### ISSUE THREAD

**Issue by aditya2337** [electron/electron#20073]
So I am trying to create a screen recorder using electron and react, I am trying to create a picker where the user has the option to select a source to record.

I am using electron's desktopCapturer to capture the sources and then display it on the picker, but the problem I am facing here is that it only captures the windows open on the current screen/workspace.

What I mean by this is suppose in mac OS, you open an app in fullscreen mode, this app goes into a virtual workspace. Now, these applications are not listed by desktopCapturer.getSources().

How do I get the application sources that are opened in different workspaces/desktops?

**Comment by codebytere** [comment]
This is unfortunately not possible in Electron right now; it's a fundamental limitation of Chromium as can be seen in the following Chromium repro steps:

```
Steps to reproduce the problem:
1. Run this app: https://chrome.google.com/webstore/detail/desktop-capture-sample/mhkidniocjdaiddjckopkigjmjbadfji/related
2. See that windows in the Application Window view reflect only what is currently on-screen
3. Move into a full-screen app view, and see that what's in the Application Window changes to reflect that specific window.
```

I've filed a bug upstream and will be sure to let you know if something changes.

**Comment by aditya2337** [comment]
Oh okay, so is there any workaround for this @codebytere ?
