### ISSUE TITLE
Cannot Preview Local File

### ISSUE THREAD

**Issue by Ivorfason** [electron/electron#20071]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
4.1.5
* **Operating System:**
MacOS

### Expected Behavior
Preview Loacl or Online File Normally as the Chrome Browser Behaviour

### Actual Behavior
Blank Page.
Get a prompt to download the file.

I have tried some file type as .pdf .doc .xlsx...
I have tried `<iframe src=""/>` & `<webview src="" plugins/>` and it didn't work...

**Comment by codebytere** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
