### ISSUE TITLE
Run JS on a window

### ISSUE THREAD

**Issue by MarcoD1337** [electron/electron#20076]
How Do I run JS code on a window opened with window.open() without using the developer console

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
