### ISSUE TITLE
Closing child window hangs main window

### ISSUE THREAD

**Issue by zarubond** [electron/electron#20086]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

I have enabled nativeWindowOpen and nodeIntegrationInSubFrames for main window, and I have a preload script which required a remote from electron. Which this configuration I open a child window and then I close it. The main window render process hangs for ever so I have to restart whole app. Here is and example app https://github.com/zarubond/electron-quick-start/tree/child_hang

* **Electron Version:**
6.0.7, 7.0.0-beta3
* **Operating System:**
Windows, Linux, MacOS
* **Last Known Working Electron version:**
5.0.10

### Expected Behavior
Closing child window should not hang main window for ever

### Actual Behavior
Main window hangs after closing child window. 

### To Reproduce
Open child window and then close it

**Comment by VishwasShashidhar** [comment]
@sofianguy This is actually a blocker for stable (for some of us at least) as pop-outs (child windows) are common use cases.

**Comment by NikolayMakhonin** [comment]
Details of this error:

For reproduce use this code:
```js
win = new BrowserWindow({
	width: 1200,
	height: 700,
	webPreferences: {
		nodeIntegration: false,
		preload: require.resolve('./preload'), // required for reproduce the error
	},
	frame: false,
})

win.webContents.openDevTools({
	mode    : 'undocked',
	activate: true,
})
```

**preload.js**
```js
// may only contain this line for reproduce the error
const {remote} = require('electron')
```

Run the app and run in the console:
```js
var win = window.open('about:blank', '', 'width=600,height=400')
win.document.write('Some text')

win.close()

// after this main window will hung, and dev tools will partly not work (you cannot run another console command)
```

Temporary solution (hack):
```js
var win = window.open('about:blank', '', 'width=600,height=400')

// fix electron bug with close about:blank windows
const winClose = win.close.bind(window)
win.close = () => {
	if (window.minimize) {
		window.minimize()
	}
	this.attachComponent()
	window.location.href = 'http://0.0.0.0/' // if you change window url and wait, you can close window without error
	setTimeout(() => winClose(), 2000)
}
```

**Comment by NikolayMakhonin** [comment]
Improved solution of bypass the error:

```
win = new BrowserWindow({
	...
	webPreferences: {
		...
		preload: require.resolve('./preload'),
	},
})
```

**preload.js**
```
function delay(timeMilliseconds) {
	return new Promise(resolve => setTimeout(resolve, timeMilliseconds))
}

const open = window.open.bind(window)
window.open = function (...args) {
	const childWindow = open(...args)

	const allWindows = remote.BrowserWindow.getAllWindows()
	const remoteChildWindow = allWindows[allWindows.length - 1]

	childWindow.close = async () => {
		const href = childWindow.location.href
		childWindow.location.href = 'http://0.0.0.0/'
		remoteChildWindow.hide()
		try {
			while (href === childWindow.location.href) {
				await delay(50)
			}
		} catch {
		}
		remoteChildWindow.close()
	}

	return childWindow
}
```

**Comment by miniak** [comment]
This bug is platform independent.

**Comment by loc** [comment]
@miniak what version are you testing with? I have a fix for 6-0-x in #20547. When I implement a similar fix in 7-0-x/master, I hit a V8 error that I haven't been able to track down yet. Ultimately, the problem is that we allow Chrome to create a WebContents and immediately kill it — the long term fix is an API change. But I'm still hoping to get a short term fix up this week, if possible.

**Comment by miniak** [comment]
This is a repro on master. But we need to fix it in 6 and 7 as well

**Comment by miniak** [comment]
@loc when I tried using an async IPC instead, I am not getting it on the other side. Even if we fix the sync version, another problem would be that the rpc-server in main won't get a notification that the context is released and memory would leak

**Comment by miniak** [comment]
@loc which should be ok since:
https://github.com/electron/electron/blob/825e67140e9e1a2318883e6c3887fe8ffe427fc7/lib/renderer/api/remote.js#L16-L23

**Comment by cynx** [comment]
Curious how this is not a blocker for stable build? Unable to upgrade from v5 due to prevalence of this issue v6 onwards

**Comment by ckerr** [comment]
https://github.com/zarubond/electron-quick-start/tree/child_hang does not reproduce the error in the currently-supported versions of  Electron. Tested with 

* 7.3.2
* 8.4.0
* 9.1.0 
* 10.0.0-beta.11

Unless there's a critical security issue that would merit patching an unsupported version, this won't be fixed in 6. In any case, the better solution would be for all applications still running on Electron 6 to upgrade.

**Comment by UstymUkhman** [comment]
It does reproduce with version `13.6.9`. Maybe even with latest ones too, unfortunately, that's the highest one I can use in my project so I haven't tested above that. But I tested with versions:

- 12.2.3
- 11.5.0
- 10.4.7
- 9.4.4

and the only one where closing a child window works smoothly is the `9.4.4`.
