### ISSUE TITLE
Problem in select printer deviceName

### ISSUE THREAD

**Issue by pedrohosoares** [electron/electron#20096]
###Electronjs ^6.0.4

When 'im select deviceName for printer the document, my app dont print, but, if put deviceName = '' (selecting the pattern printer), the app printer with success.

My code doesnt work:

 janelaPrint.loadURL(url_balcao);
            janelaPrint.webContents.once('did-finish-load', function() {
                janelaPrint.webContents.print(
                    {
                        silent:true,
                        printBackground:false,
                        deviceName:'MP4200TH'
                    },
                    function(err){
                        console.log(err);
                        if(err){
                        }
                    }
                );

**Comment by codebytere** [comment]
This has been fixed in v7, and needs to be backported to 6 if possible but it may be too difficult. See https://github.com/electron/electron/issues/17523 for more.
