### ISSUE TITLE
"shell.openExternal() opens an external link" is flaky on WoA

### ISSUE THREAD

**Issue by richard-townsend-arm** [electron/electron#20097]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  *  6-0-x, 7-0-x, master
* **Operating System:**
  *  Windows on Arm (64 bit)
* **Last Known Working Electron version:**
  *  N/A

### Expected Behavior

The test `shell module shell.openExternal() opens an external link asynchronously` passes on Windows on Arm.

### Actual Behavior

The test `shell module shell.openExternal() opens an external link asynchronously` fails with
```
Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\vsts-agent-win-x86-2.148.2\_work\1\s\src\electron\spec\api-shell-spec.js)
```

### To Reproduce

`npm run test -- --ci -g "shell.openExternal()"

### Screenshots
N/A

### Additional Information
It's possible that the issue arises from the device's default web browser (WoA can only be tested on physical hardware) crashing on startup after trying to reload a large number of tabs left over from previous runs.

**Comment by jkleinsc** [comment]
Resolved via #20091
