### ISSUE TITLE
BrowserWindow.moveTop() test fails on WOA in 6-0-x

### ISSUE THREAD

**Issue by jkleinsc** [electron/electron#20110]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  6-0-x
* **Operating System:**
  * Windows on Arm (64 bit)
* **Last Known Working Electron version:**
  * master, 7-0-x

### Expected Behavior

The test `BrowserWindow module BrowserWindow.moveTop() should not steal focus` passes  on Windows on Arm.
### Actual Behavior

On Windows on Arm, the test `BrowserWindow module BrowserWindow.moveTop() should not steal focus` fails with:
```
not ok 91 BrowserWindow module BrowserWindow.moveTop() should not steal focus
  AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
  
    assert(w.isFocused())
  
      at Context.<anonymous> (C:\vsts-agent-win-x86-2.148.2\_work\1\s\src\electron\spec\api-browser-window-spec.js:551:7)
not ok 92 BrowserWindow module "after each" hook: closeTheWindow for "should not steal focus"
  Error: Object has been destroyed
      at C:\vsts-agent-win-x86-2.148.2\_work\1\s\src\out\Default\resources\electron.asar\browser\rpc-server.js:392:52
      at EventEmitter.<anonymous> (C:\vsts-agent-win-x86-2.148.2\_work\1\s\src\out\Default\resources\electron.asar\browser\rpc-server.js:249:27)
      at EventEmitter.emit (events.js:200:13)
      at WebContents.<anonymous> (C:\vsts-agent-win-x86-2.148.2\_work\1\s\src\out\Default\resources\electron.asar\browser\api\web-contents.js:342:29)
      at WebContents.emit (events.js:200:13)
```
Above error from test on WOA hardware here: 
https://github.visualstudio.com/electron/_build/results?buildId=49301&view=logs&jobId=12f1170f-54f2-53f3-20dd-22fc7dff55f9&taskId=5caf77c8-9b10-50ef-b5c7-ca89c63e1c86&lineStart=542&lineEnd=543&colStart=1&colEnd=1
### To Reproduce

Run the test suite on a 6-0-x WOA build on WOA hardware, specifically the command:
npm run test -- --ci -g "BrowserWindow.moveTop()"

### Screenshots

N/A

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
