### ISSUE TITLE
Current page flashing while navigating to page with relative path and will-navigate event handler

### ISSUE THREAD

**Issue by AleshaOleg** [electron/electron#20127]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v6.0.7
* **Operating System:**
  * macOS 10.13.6
* **Last Known Working Electron version:**
  * v6.0.3

### Expected Behavior
Navigating to a page with a relative path and `will-navigate` event handler without any flashed.

### Actual Behavior
Current page flashing while navigating to another page with relative path in `href` when `will-navigate` event handler exists.

### To Reproduce
I made repository with reproducing - https://github.com/AleshaOleg/electron-flashing-page-reproduce

Please run it, and when you'll see GitHub home page, please click any link with relative path. For example, it's a green "Sign up" button.

### Screenshots
https://www.dropbox.com/s/uhrmxzvzswjmqz2/Reproducing.mov?dl=0

### Additional Information
Probably related to those fixes in `6.0.4`:
* Fixed web page displayed with offset when using native tab on macOS. [#19888](https://github.com/electron/electron/pull/19888)
* Fixed white flash after restoring an app from the background. [#19900](https://github.com/electron/electron/pull/19900)

**Comment by MarshallOfSound** [comment]
This issue is known and comes from upstream.  Basically the renderer restarts on navigations and this causes the compositor to flash white.  For instance I can see the white flash on `6.0.3` (in fact every version of Electron).

See https://github.com/electron/electron/issues/6104

You can mitigate this for same-site navigations by using `app.allowRendererProcessReuse = true` but you should read through what that property does before using it.

**Comment by JanDevDE** [comment]
Hey, sorry for asking here, but I crawled to many issues and couldn't find an answer. Is there any way to redirect between pages without having a "flash", except using allowRendererProcessReuse?
