### ISSUE TITLE
Window border shadow disappears

### ISSUE THREAD

**Issue by y489436672** [electron/electron#20125]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  v7.0.0-beta.4
* **Operating System:**
Windows 10
* **Last Known Working Electron version:**
  v6.0.7
### Expected Behavior
Window border shadow exists

### Actual Behavior
No shadows

### Screenshots
![QQ截图20190905120202](https://user-images.githubusercontent.com/19664101/64311006-09bee580-cfd5-11e9-9b6e-ddde3ecbb461.png)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
