### ISSUE TITLE
Electron Support for FIPS

### ISSUE THREAD

**Issue by gannons** [electron/electron#20120]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
[FIPS](https://en.wikipedia.org/wiki/FIPS_140-2) is a common security standard products need to meet to qualify for contracts offered by US and Canadian Governments. Electron has no support for FIPS. i.e. It notably lacks support for a FIPS compliant version of OpenSSL. This limits the projects for which it is a suitable.

### Proposed Solution
Support a FIPS compliant version of OpenSSL.

### Alternatives Considered
Detail / highlight why FIPS support is not possible.

**Comment by nornagon** [comment]
We don't ship OpenSSL.

**Comment by MarshallOfSound** [comment]
@gannons We don't ship OpenSSL as of Electron 4.0 and higher (all supported versions of Electron)

**Comment by codebytere** [comment]
Closing in agreement with the above; this is not currently a possibility.

**Comment by alejandroclaro** [comment]
I'm agreed with @nornagon, it is possible to build BoringSSL in FIPS mode by using the BORINGSSL_FIPS definition during the compilation. Also, BoringSSL has gone successfully through the CMVP in an accredited CMVP lab.

I think is a matter of adding a build flag to build Electron with support to FIPS mode (BORINGSSL_FIPS), and perform some test.
