### ISSUE TITLE
[Question] Creating broken symlinks on Linux

### ISSUE THREAD

**Issue by michalSolarz** [electron/electron#20126]
I don't know if its an issue but a lot of electron apps (for example teams-for-linux) creates symlinks in the app configuration file. I've described it more detailed in this issue: https://github.com/IsmaelMartinez/teams-for-linux/issues/273
And my question is if it is a proper behavior? Should these symlinks point to the existing files?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
