### ISSUE TITLE
setSimpleFullScreen will show the traffic lights

### ISSUE THREAD

**Issue by joeyer** [electron/electron#20124]
electron: 4.2.2

config:    
const mainWindow = new BrowserWindow({
            x: frame.x,
            y: frame.y,
            minWidth: frame.width,
            minHeight: frame.height,
            width:frame.width,
            height:frame.height,
            vibrancy: 'medium-light',
            acceptFirstMouse: true,
            show: false,
            backgroundColor: 'none',
            resizable: true,
            webPreferences: {
                scrollBounce: true
            },
            autoHideMenuBar: true,
            icon: '../src/assets/images/icon.png',
            frame: false,
        });

zoom：setSimpleFullScreen(true);
minify：setSimpleFullScreen(false);

![image](https://user-images.githubusercontent.com/11498128/64310239-f4948780-cfd1-11e9-9c02-5c417891b4f6.png)

After shrinking, there is a problem
![image](https://user-images.githubusercontent.com/11498128/64310322-39202300-cfd2-11e9-95f7-1f7f3715f9eb.png)

The traffic light showing the original window

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Comment by miniak** [comment]
you should never render your own traffic light buttons on macOS, which seems to be the case looking at the screenshot: https://electronjs.org/docs/api/frameless-window#alternatives-on-macos
