### ISSUE TITLE
electron.desktopCapturer is not cutting off some part from right

### ISSUE THREAD

**Issue by bit-warrior** [electron/electron#20123]
OS:-Linux mint 19.1
"electron": "^6.0.7"

i am trying to take whole screen capture, it works fine except , it chopping off some pixel from the right side along the height of screen.

````
 electron.desktopCapturer.getSources({ types: ['screen'] }).then(async sources => {
      console.log(sources);
      
      for (const source of sources) {
          // Filter: main screen
          if (source.name === "Entire screen" ) {
              try{
                  const stream = await navigator.mediaDevices.getUserMedia({
                      audio: false,
                      video: {
                          mandatory: {
                              chromeMediaSource: 'desktop',
                              chromeMediaSourceId: source.id,
                              minWidth: 1280,
                              maxWidth: 4000,
                              minHeight: 720,
                              maxHeight: 4000
                          }
                      }
                  });

                  _this.handleStream(stream);
              } catch (e) {
                  _this.handleError(e);
              }
          }
      }
  });
````

**Comment by CapOM** [comment]
Try with Chromium Browser or Google Chrome on the page https://www.webrtc-experiment.com/getDisplayMedia/ and check if it is happening there too.

**Comment by bit-warrior** [comment]
it works through the link you sent without cutting off any pixel.

**Comment by loc** [comment]
@bit-warrior do you mind checking if the problem still repros in electron 8? Easiest way to check is by [making a fiddle](https://github.com/electron/fiddle).

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
