### ISSUE TITLE
API request: find out if a window is visible on a display

### ISSUE THREAD

**Issue by bpasero** [electron/electron#20145]
I know there is the [Page Visibility API](https://github.com/electron/electron/blob/4-0-x/docs/api/browser-window.md#page-visibility) but it does not solve this use case: Find out if the browser window in Electron is visible to the user, that is:
* window is not minimized
* window is not fully covered by another window
* window is not Alt+Tabbed to the background (thus overlapped by another application)
* window is not hidden (programmatically)
* window is not off-screen

The use case for VSCode is to decide wether a notification toast is to be purged after a certain timeout or not. If the window is not visible to the user we would like to not purge, assuming that the user cannot see the notification. 

Today we rely on `Window.isFocused()` to make this decision, but this is obviously wrong for the case where the window is fully shown on the monitor, but simply another window has focus.

**Comment by MarshallOfSound** [comment]
Fixed in https://github.com/electron/electron/pull/19988

**Comment by MarshallOfSound** [comment]
document.visibilityState is now correct and matches the list of conditions you mentioned

**Comment by zerofront** [comment]
@MarshallOfSound How can I detect the  Visibility in version 4.x??
