### ISSUE TITLE
globalShortcut Issue when using "Control" key.

### ISSUE THREAD

**Issue by adamthecro** [electron/electron#20147]
I've been trying globalShortcut and had a problem:
when using: 
globalShortcut.register('CommandOrControl+Y', () => {
    //Code to execute
})

When pressing Ctrl+Y the first time nothing happens but after that first time it works. If I don't press it for some seconds then happens the same thing. But when using another keys like Alt+Y it works. Am I doing something wrong or it's a bug? 

Thank you!

Context code:

const { app, globalShortcut } = require('electron')

app.on('ready', () => {
  globalShortcut.register('CommandOrControl+Y', () => {
    // Code not executing at first press.
  })
})

-------------------------------------------------------

const { app, globalShortcut } = require('electron')

app.on('ready', () => {
  globalShortcut.register('Alt+Y', () => {
    // Code executing at first press.
  })
})

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by adamthecro** [comment]
Hi, I'm sorry.
Video:
https://vimeo.com/user102602516/review/358369627/8bb49a6a7a

Code:
const {app, globalShortcut, BrowserWindow} = require('electron')
const path = require('path')

let mainWindow

function createWindow () {
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js')
    }
  })

  mainWindow.loadFile('index.html')
  mainWindow.on('closed', function () {
    mainWindow = null
  })
}

app.on('ready', function(){
  createWindow();
  globalShortcut.register('CommandOrControl+T', function(){
    console.log("CommandOrControl+T");
  });
  globalShortcut.register('CommandOrControl+N', function(){
    console.log("CommandOrControl+N");
  });
})

// Quit when all windows are closed.
app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})

app.on('activate', function () {
  if (mainWindow === null) createWindow()
})

**Comment by codebytere** [comment]
@adamthecro the template asks for the following:
### Issue Details

* **Electron Version:**
  * 
* **Operating System:**
  * 
* **Last Known Working Electron version:**
  * 

Without these, a reproducible sample is helpful but unfortunately insufficient. It would be great if you could, instead, delete and reformat your original issue to match the requested template.
