### ISSUE TITLE
session, ipcrenderer undefined outside of mainprocess.

### ISSUE THREAD

**Issue by Sombian** [electron/electron#20148]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * latest
* **Operating System:**
  * windows latest
* **Last Known Working Electron version:**
  * unknown

### Expected Behavior
as title, these two are undefined.

### Actual Behavior
define 'em..?

### To Reproduce
https://github.com/Sombian/example

**Comment by codebytere** [comment]
From `session.md`:

> Process: [Main](../glossary.md#main-process)

This is a main process module only, as specified in docs. This is not an issue with Electron.

**Comment by Sombian** [comment]
> From `session.md`:
> 
> > Process: [Main](../glossary.md#main-process)
> 
> This is a main process module only, as specified in docs. This is not an issue with Electron.

whats the actual problem? can you provide further details?

**Comment by reZach** [comment]
@Sombian You have to pass these variables through the preload script to your renderer processes for this to work. 

**preload.js**
```
const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld(
    "electron",
    {
        ipcRenderer: ipcRenderer
    }
);
```

**renderer file**
```
window.electron.ipcRenderer; // use as wanted
```
