### ISSUE TITLE
Windows: Issues with BrowserWindow.maximize() when 'resizable' is false

### ISSUE THREAD

**Issue by CodeSmith32** [electron/electron#20151]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.x (confirmed with 6.0.0 / 6.0.7)
* **Operating System:**
  * Windows 10 (1903)
* **Last Known Working Electron version:**
  * ?

### Expected Behavior
- Create a BrowserWindow, setting `{resizable: false, maximizable: true}`
- The maximize button on the window *should* be enabled
- When clicking maximize / programmatically calling `browserwindow.maximize()`:
  - The window *should* fully maximize
  - The `'maximize'` event *should* trigger
- After being maximized, calling `browserwindow.isMaximized()` *should* return `true`

### Actual Behavior
- Create a BrowserWindow, setting `{resizable: false, maximizable: true}`
- The maximize button on the window is *disabled*
- When programmatically calling `browserwindow.maximize()`:
  - The window becomes almost as big as the screen but *does not* become maximized; i.e., it is not fixed in place, and can still be dragged around
  - The `'maximize'` event *does not* trigger
- After being maximized, calling `browserwindow.isMaximized()` returns `false`

### To Reproduce
Putting the following two files in a folder on Windows 10 and running `electron .` in the directory with electron 6.0.x globally installed should demonstrate the issue:

**package.json:**
```
{
	"name": "bug",
	"main": "index.js",
	"dependencies": {},
	"devDependencies": {}
}
```

**index.js**
```
const {app, BrowserWindow} = require('electron');

app.once('ready',async ()=>{
	var win = new BrowserWindow({
		closeable: true,
		minimizable: true,
		maximizable: true,
		resizable: false,
	});
	win.on('maximize',()=>{
		console.log('maximized!');
	});
	win.maximize();
	console.log(win.isMaximized());
});
```

### Screenshots
Unmaximizable, despite `{maximizable: true}`
![Unmaximizable](https://user-images.githubusercontent.com/21373557/64445959-a0f36e00-d0a5-11e9-86fb-37d466471341.png)

### Additional Information
Perhaps some of this is intended behavior (maybe the button being disabled). However, when nonetheless programmatically maximizing it, I would definitely expect:
- The `'maximize'` event to fire
- `browserwindow.isMaximized()` to return `true`

This is especially odd since the window cannot be resized (via `browserwindow.setSize(...)`) when in this *partially* maximized state. It also *can* be unmaximized (via `browserwindow.unmaximize()`) which does successfully restore it, and from there `setSize()` does work.

**Comment by legolaserea** [comment]
i have the same problem with  electron v6.02.

'browserwindow.maximize() 'can not set  'browserwindow.isMaximized()' as true

**Comment by eamodio** [comment]
FYI, this looks like the same issue as: https://github.com/electron/electron/issues/19934

**Comment by kaysonwu** [comment]
@zcbenz  Do you have a plan to solve this problem?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
