### ISSUE TITLE
session not working on product but dev.

### ISSUE THREAD

**Issue by Sombian** [electron/electron#20163]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * latest
* **Operating System:**
  * windows latest
* **Last Known Working Electron version:**
  * unknown

### Expected Behavior
on dev environment session does work but product however dont even fire and no console error or what so ever.

### Actual Behavior
let session fired on product

### To Reproduce
https://github.com/Sombian/example/
(check https://github.com/Sombian/example/blob/master/src/App.vue out)

**Comment by codebytere** [comment]
Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue. The repo you've provided contains a lot of app-specific code, and as such it's not demonstrable that this is an issue with Electron.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by Sombian** [comment]
@codebytere woah u can just copy repo, install then build product. Open dev panel watch the mesaage print out. Such a lazyness infao. I even linked the where issue occured.

**Comment by jkleinsc** [comment]
@Sombian  your comment was deleted as a violation of the Electron Code of Conduct. You may consider this an official warning.

Please do not interact with the project for 24 hours. After that, please look through your open issues and edit them to ensure they're entirely on-topic, and we can continue the discussion here about the best way to go forward.

**Comment by Sombian** [comment]
Im no longer use electron but nwjs. Thus ill close this by now.
