### ISSUE TITLE
Mac OSApplication crash on start when in app product request

### ISSUE THREAD

**Issue by lubo08** [electron/electron#20161]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 3.1.12
* **Operating System:**
  * Mac OS X 10.11.6
* **Last Known Working Electron version:**
  * 

### Expected Behavior
Application do not crash on startup.

### Actual Behavior
Application crash.

### To Reproduce
See the crash log.

### Additional Information
I have implemented MAC in-app purchases. But sometimes on older MAC os el Capitan happen to users that are not able to start application, it crashes. See log:
Full log here: https://pastebin.com/2GFx3cVr?fbclid=IwAR2Zab62J7_bkHuxAA-jH4mR6u6rCsWO6sSwnzsXbMQZn2py1rt4QLlzIXs

Any advice about what could be, problem?

OS Version:            Mac OS X 10.11.6 (15G22010)
Report Version:        11
Anonymous UUID:        1AD46B5F-E138-C159-57B5-1562050ACB7A
 
 
Time Awake Since Boot: 1800 seconds
 
System Integrity Protection: enabled
 
Crashed Thread:        32  Dispatch queue: SKProductsRequest reply queue
 
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000018
Exception Note:        EXC_CORPSE_NOTIFY
 
VM Regions Near 0x18:
-->
    __TEXT                 000000010ebc7000-000000010ebc8000 [    4K] r-x/rwx SM=COW  /Applications/sInvoices.app/Contents/MacOS/sInvoices
 
Application Specific Information:
objc_msgSend() selector name: respondsToSelector:
 
 
Thread 0:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   libnode.dylib                   0x0000000113c56071 v8::Object::CreationContext() + 1
1   com.github.electron.framework   0x000000010ec061da mate::internal::V8FunctionInvoker<void (std::__1::vector<in_app_purchase::Product, std::__1::allocator<in_app_purchase::Product> > const&)>::Go(v8::Isolate*, mate::internal::SafeV8Function const&, std::__1::vector<in_app_purchase::Product, std::__1::allocator<in_app_purchase::Product> > const&) + 122

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by lubo08** [comment]
@codebytere Hello, I update the issue. Thank you.

**Comment by sofianguy** [comment]
@lubo08 is this happening on version 4.2.x or later? We are no longer supporting versions earlier than 4.2.x, per our supported versions [policy](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#supported-versions)

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
