### ISSUE TITLE
Dragging a frameless window with -webkit-app-region: drag; does not work

### ISSUE THREAD

**Issue by dschuessler** [electron/electron#20168]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.7
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron version:**
  * I am a first time Electron user

### Expected Behavior
A frameless window with its body styled with `-webkit-app-region: drag;` is draggable according to https://github.com/electron/electron/blob/master/docs/api/frameless-window.md#draggable-region

### Actual Behavior
A frameless window with its body styled with `-webkit-app-region: drag;` is not draggable.

### To Reproduce
1. `git clone https://github.com/dschuessler/electron-drag-bug`
2. `cd electron-drag-bug`
3. `npm install && npm run start`
4. Try to drag the window.

### Screenshots
![electron-bug](https://user-images.githubusercontent.com/5774545/64487722-1b56f600-d23e-11e9-8401-f3577d0709bc.gif)

### Additional Information
It might be a regression of https://github.com/electron/electron/issues/13358

**Comment by HaNdTriX** [comment]
> Note: -webkit-app-region: drag is known to have problems while the developer tools are open. See [this GitHub](https://github.com/electron/electron/issues/3647) issue for more information including a workaround.

**Comment by CodeSmith32** [comment]
Hey, @dschuessler, are you sure it's not just because the default height of the 'body' element is 0px? I know this has thrown me off many times.
Try adding "margin: 0; width: 100vw; height: 100vh;" to the body style, and report if you're still having the issue.

**Comment by codebytere** [comment]
This is indeed working correctly (as verified with [this gist](https://gist.github.com/d6569e7c766f23cccf7e552d1ff95237), and i believe your issue lies with conflicting [text selection](https://github.com/electron/electron/blob/master/docs/api/frameless-window.md#text-selection)/

Working in 6.0.7:

![draggable](https://user-images.githubusercontent.com/2036040/64574770-d797e580-d33e-11e9-9c25-435ba2057fd2.gif)

**Comment by dschuessler** [comment]
Disabling text selection did not change the described behavior, but @CodeSmith32 's proposal did the trick. Thank you!
