### ISSUE TITLE
[Angular][Electron]dialog.showOpenDialogSync not defined

### ISSUE THREAD

**Issue by geyuqiu** [electron/electron#20167]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

```ts
const remote: any = window.electron.remote;
const files: string[] = remote.dialog.showOpenDialog(remote.getCurrentWindow(), {
      properties: ['openFile', 'openDirectory']
});
```
I don't know if this repo is the right place to raise this issue. 
Maybe [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)?
The above code works in a Angular Project inside a electron-boilerplate-project for file selection

### Proposed Solution

but calling `remote.dialog.showOpenDialogSync` gives a `showOpenDialogSync not defined error`
(Electron-version: 5.0.2)
inside `electron.d.ts` I can find `showOpenDialog(browserWindow: BrowserWindow, options: OpenDialogOptions, callback?: (filePaths?: string[], bookmarks?: string[]) => void): (string[]) | (undefined);`

but no `showOpenDialogSync` for interface `dialog`

**Comment by codebytere** [comment]
[`dialog.showOpenDialogSync `](https://github.com/electron/electron/blob/56d10aeef7d5b20b84d87722008c977bba65a69b/docs/api/dialog.md#L26) was not introduced until Electron v6.
