### ISSUE TITLE
electron crash-reporter

### ISSUE THREAD

**Issue by trae-op** [electron/electron#20174]
Can I get access Cross-Origin Resource Sharing (CORS) ? Maybe exist option for this? I can send for localhost but another url not work
`
crashReporter.start({
  productName: 'YourName',
  companyName: 'YourCompany',
  submitURL: 'https://domen.com/api/,
  uploadToServer: true
})
`

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. We will be able to more closely look at your issue once you do so.

**Comment by trae-op** [comment]
> filled out

I don't know how to filled out. Show this question to the developer and he will understand.

**Comment by codebytere** [comment]
@trae-op I am the developer. When you open a new issue, there is a full template that you had to delete in order to paste your own sentence. We require that it is filled out regardless of the type of issue you are having and the intended audience of your issue.

**Comment by trae-op** [comment]
> @trae-op I am the developer. When you opened this new issue, there was a full markdown template that you had to delete in order to paste your own sentence.
> 
> That I understand your issue is immaterial - we require that it is filled out regardless of the type of issue you are having and the intended audience of your issue.

I can not send data from electron.crashReporter to back-end. Back-End PHP. Also I do not see the request in the tab "Network" Chrome

**Comment by jkleinsc** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community).
