### ISSUE TITLE
BrowserWindow loadURL size too small

### ISSUE THREAD

**Issue by pjebs** [electron/electron#20176]
```
let html = `
<html></html>
`
browserWindow.loadURL("data:text/html;charset=utf-8," + encodeURI(html));
```

It appears that `loadURL` had some kind of maximum size limit for strings. I think this is a bug that should be fixed. it certainly doesn't allow a 66 kilobyte string

**Comment by vladimiry** [comment]
See `Length limitations` paragraph here https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs
