### ISSUE TITLE
App store audit application failed

### ISSUE THREAD

**Issue by huangbiyong** [electron/electron#20177]
Dear,
I re-signed the .app file. After the signature is successful, I submit it to the app store market, but the apple responds to me with a failed signature.

> ITMS-90238: Invalid Signature - The nested app bundle Electron Framework at path RoWrite.app/Contents/Frameworks/Electron Framework.framework has following signing error(s): a sealed resource is missing or invalid . Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information.

How should I solve it?

thanks!!!!

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
