### ISSUE TITLE
The pdf "Widow/Orphan control" setting in electron-printer

### ISSUE THREAD

**Issue by iamcaam** [electron/electron#20180]
Hello everyone,

Does the Electron module, electron-printer, has the relative pdf setting like "**Widow/Orphan control**" in Microsoft Word ?

![pdf_electron](https://user-images.githubusercontent.com/12681645/64595417-7de9f680-d3e4-11e9-87d5-598600aa5e60.png)

**Comment by codebytere** [comment]
Please post this issue on the [electron-printer](https://github.com/marcopiraccini/electron-printer) repo.
