### ISSUE TITLE
An unbordered window cannot be set to a width less than a certain value

### ISSUE THREAD

**Issue by coderooo** [electron/electron#20183]
### Preflight Checklist

*  I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
*  I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
*  I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.7
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 

### Expected Behavior
Set the window width to 10px

### Actual Behavior
The minimum window width is 48px

### To Reproduce
`mainWindow = new BrowserWindow({
    width: 10,
    height: 200,
    frame: false
  })`

### Screenshots
![record](https://user-images.githubusercontent.com/24584714/64606992-26568580-d3fa-11e9-8d14-9390f3b5f8c5.gif)

**Comment by reduckted** [comment]
It looks like this can be worked around by setting `thickFrame` to false. I've tried in both 6.1.0 and 7.1.0 and it solves the issue.

> `thickFrame` Boolean (optional) - Use `WS_THICKFRAME` style for frameless windows on Windows, which adds standard window frame. Setting it to false will remove window shadow and window animations. Default is true.

**`thickFrame: true`**
![thickFrame-true](https://user-images.githubusercontent.com/10321525/68377319-db58b480-0195-11ea-8d86-36107df979ba.gif)

**`thickFrame: false`**
![thickFrame-false](https://user-images.githubusercontent.com/10321525/68377381-ff1bfa80-0195-11ea-828d-da7765cee277.gif)

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
