### ISSUE TITLE
6.0.8 node.lib linking issues

### ISSUE THREAD

**Issue by Eugeny** [electron/electron#20185]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.8
* **Operating System:**
  * Windows Server 2016 and 2019
* **Last Known Working Electron version:**
  * 6.0.7

With the 6.0.8 binaries, native module builds are now failing with:

```
node.lib(node.exe) : fatal error LNK1223: invalid or corrupt file: file contains invalid .pdata contributions 
```

**Comment by richard-townsend-arm** [comment]
I've just noticed this too. It appears that the node.lib in AppData\Local\node-gyp\Cache\6.0.8\x64 is actually ARM64, but I'm not sure which download is responsible for these artefacts. @jkleinsc, do you know more about what could be going on here?

**Comment by jkleinsc** [comment]
6.0.9 has been released with the correct headers.  Additionally, the incorrect header files for 6.0.8 have been updated on https://atom.io/download/electron

**Comment by deepak1556** [comment]
@jkleinsc 6.0.8 still fails, there are checksum failures with the updated headers, 

```
Error: win-x64/node.lib local checksum 43f611616154f667fe1101315834923cd06699bb7b4cb273bf780142ed6f0b44 not match remote d5a48e83d9c112a2db16ccf08406b381ea9e86f86b44a2d13712afd84842834d
```

**Comment by jkleinsc** [comment]
Ahh I forgot about the checksums.  Probably better to use 6.0.9 instead

**Comment by malept** [comment]
Perhaps 6.0.8 should be marked as deprecated in NPM?
