### ISSUE TITLE
Build with chromium libc++ on windows

### ISSUE THREAD

**Issue by deepak1556** [electron/electron#20195]
Tracking bug to identify the problems with using libc++ on windows. (ex: Distribution size, native node modules)

Chromium has been building with their fork of libc++ on windows, macOS and linux ever since the clang move had been made.

At the moment we only use it on macOS and linux. And chromium disabled their build bots using MSSTL, so if there are any compilation issues we have been patching and upstreaming, this is unnecessary churn in the upgrade workflow.

Another pain point of this difference is that we are deviating from compilation flags between upstream, at the moment there is one [/Zc:twoPhase](https://github.com/electron/electron/blob/master/patches/chromium/build_win_disable_zc_twophase.patch), but this difference might increase in future.

Upstream bug: https://bugs.chromium.org/p/chromium/issues/detail?id=801780

/cc @electron/wg-upgrades

**Comment by LifeIsStrange** [comment]
Optionally: would be nice to benchmarck to see if there's a performance improvement or regression

**Comment by deepak1556** [comment]
This is completed.
