### ISSUE TITLE
Unable to register serviceworker

### ISSUE THREAD

**Issue by Praveer1981** [electron/electron#20197]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.7
* **Operating System:**
  *  Windows 10(10.0.17763.0)
* **Last Known Working Electron version:**
  * 5.0.7

### Expected Behavior
It should be able to download the service worker and able to register it

### Actual Behavior
Its not able to download the serviceworker

### source code to register the SW
below is the sample code to create `mainWindow`
`mainWindow =  
       new BrowserWindow({
       'x': mainWindowState.x,
       'y': mainWindowState.y,
       'width': mainWindowState.width,
       'height': mainWindowState.height,
        title: appName,
        show: false,
        autoHideMenuBar: true,
        webPreferences: {
        webSecurity: !devMode,
         nodeIntegration: true, 
          nodeIntegrationInWorker: true,
    //  devTools: devMode,
         enableRemoteModule: true //only enable for spectron
        },
       renderProcessReady: false,
       canQuitWithoutChecking: false,
      contextIsolation: true
      });`
I read https://electronjs.org/docs/all#2-do-not-enable-nodejs-integration-for-remote-content
I realized, problem might be due to `nodeIntegrationInWorker:true` . When I set this flag to `false `, it is able to download my application's service worker . but It fails when I try to open a file from the `Box`.

Any help would be highly appreciated !

**Comment by codebytere** [comment]
We close issues that are questions since they don't represent a task needing to be completed. This is not demonstrably a bug, more a request for assistance. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
