### ISSUE TITLE
Attempt to write outside buffer bounds

### ISSUE THREAD

**Issue by crisan-catalin** [electron/electron#20208]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.0.3
* **Operating System:**
  * Windows 10 (1803) 
* **Last Known Working Electron version:**
  * 4.0.3

### Expected Behavior

I want to extract an asar file using `asar extract app.asar` command. 
### Actual Behavior
I get the following error: 
`RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds`

### To Reproduce
Run  `asar extract app.asar` command on asar file.

### Screenshots

https://i.imgur.com/zmNOSqq.png

**Comment by Eglet27** [comment]
am also facing same problem

**Comment by MarshallOfSound** [comment]
Bugs with `asar` should be raised on electron/asar
