### ISSUE TITLE
.showSaveDialog() - callback that hands you fileName is inconsistent between 6.0.2 and 6.0.8

### ISSUE THREAD

**Issue by Nashorn** [electron/electron#20201]
.showSaveDialog() - in 6.0.2 fires our callback with the chosen file path as an object that had to be accessed:

dialog.showSaveDialog({ filters: [] }, function (obj) { 
     alert(obj.filePath)
})

But, when i upgraded to 6.0.8, it breaks because an object is not handed back, only the string path:

dialog.showSaveDialog({ filters: [] }, function (filePathStr) { 
     alert(filePathStr)
})

**Comment by codebytere** [comment]
I just ran [this fiddle](https://gist.github.com/3f07a6fc76ccdd2d790351581f179b2f) and saw identical behavior in both.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
