### ISSUE TITLE
Checkbox/radio doesn't update on macOS Mojave accent color change, unless restarted.

### ISSUE THREAD

**Issue by jsynowiec** [electron/electron#20202]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.10, 6.0.8
* **Operating System:**
  * macOS 10.14.6

### Expected Behavior
Form elements like checkbox or radio button updates their "active" color when the system accent color changes.

### Actual Behavior
Checkbox and radio "active" (checked) color is set on first render according to the system accent color. When the accent color is later changed in the system preferences, the checkbox/radio button active color is not updated.

### To Reproduce
JSFiddle to test in web browser: https://jsfiddle.net/x7dftgrb/

Electron Fiddle that reproduces the issue: https://gist.github.com/b013465c400bb583d7fb8ad4ae4a130a

### Screenshots
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/1029142/64701671-7dfffa00-d4a9-11e9-9834-286e83a2295b.png">

and after restarting the fiddle:
<img width="912" alt="image" src="https://user-images.githubusercontent.com/1029142/64701717-9a039b80-d4a9-11e9-8843-0769e0d04f78.png">

**Comment by jsynowiec** [comment]
@codebytere it definitely works in Safari. Sorry, I didn't check in Chrome. My bad. This needs to be elevated as a Webkit problem then, not Electron. Any pointers where I should report it?

**Comment by codebytere** [comment]
No worries! I'd say open a [crbug](https://bugs.chromium.org/p/chromium/issues/list) :)

In the meantime i'm going to close this out, since we'll get that fix most likely for free when Chromium handles it and we upgrade to a version containing that fix.
