### ISSUE TITLE
setTimeout function call does not keep time when minimized or on a hidden desktop space

### ISSUE THREAD

**Issue by truecastdesign** [electron/electron#20212]
I created a simple stopwatch timer that uses setTimeout function call but it does not keep time when minimized or on a hidden desktop space.

const timerStart = function() {
     t = setTimeout(add, 1000);
}

### Issue Details

Electron Version: v1.4.13
Operating System: macOS 10.13.6

The timer keeps time if the window is on the current desktop or visible but it slows to about half speed when minimized or I put it on another desktop space and then switch back to my main space. It is like macOS is slowing JS down. Might there be a work around for this?

Thanks

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by miniak** [comment]
Check `backgroundThrottling ` in https://electronjs.org/docs/api/browser-window
