### ISSUE TITLE
Enable widevine support

### ISSUE THREAD

**Issue by deepak1556** [electron/electron#20211]
It has been disabled in https://github.com/electron/electron/pull/19923/commits/c388f79620e763482d532eedc147d9c03c5e3488 

Upstream CL: https://chromium-review.googlesource.com/c/chromium/src/+/1767596

Upstream now also supports linux, we should fix this and look into enabling on all 3 platforms. Although complete support can't be provided because of proprietary components, just enough support to load the plugin via our command line api.

/cc @electron/wg-upgrades

**Comment by panther7** [comment]
Please, update docs, because this doesn't work: https://www.electronjs.org/docs/tutorial/testing-widevine-cdm#using-the-library
