### ISSUE TITLE
Verify building without use_jumbo_build

### ISSUE THREAD

**Issue by deepak1556** [electron/electron#20213]
PR: https://github.com/electron/electron/pull/19817

Google forum Thread: https://groups.google.com/a/chromium.org/d/msg/chromium-dev/DP9TQszzQLI/pZ7aC8GbDAAJ

Upstream removal bug: https://bugs.chromium.org/p/chromium/issues/detail?id=994387

Not necessary for immediate action, just a tracking bug.

/cc @electron/wg-upgrades

**Comment by miniak** [comment]
Jumbo build was dropped in #20824
