### ISSUE TITLE
Renderer-Process XHR-Request withCredentials

### ISSUE THREAD

**Issue by MetalCar** [electron/electron#20226]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v2.0.13
* **Operating System:**
  * Ubuntu 18.04 x64
* **Last Known Working Electron version:**
  * don't know

### Expected Behavior
When I'm trying to send a XHR-Request with `withCredentials: false` I would expect, that no Cookies will be send. 

### Actual Behavior
When I send a XHR-Request with `withCredentials: false` all Cookies will be send. It's looking that it is the opposite of https://github.com/electron/electron/issues/9356.

### To Reproduce
Just try to do a XHR-Request in the Renderer-Process

### Additional Information

We are using `cross-fetch` for fetching data. In `cross-fetch` the above named property `withCredentials` is set to `false` when. But I also tried a XHR-Request with the normal XMLHttpRequest object

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by MetalCar** [comment]
@sofianguy I tested it also with Electron 6.0.9. Also in this version the behavior above happens.

**Comment by alexvetter** [comment]
@sofianguy We are still experiencing this issue with the latest `8.2.0`. Regarding the SameSite changes in Chromium 80 this issue came up again.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
