### ISSUE TITLE
4.x regression: webContents.capturePage callback is not called in offscreen mode

### ISSUE THREAD

**Issue by bughit** [electron/electron#20229]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.2.10 x86
* **Operating System:**
  * win7 sp1 x64
* **Last Known Working Electron version:**
  * 3.1.13 x86

### Expected Behavior
capturePage callback to called in offscreen mode

### Actual Behavior
capturePage callback not called in offscreen mode

### To Reproduce
run the following app
```js
'use strict';

const {app, BrowserWindow} = require('electron'),
      Path = require('path'),
      fs = require('fs'),
      OFFSCREEN = true;

let win;

if (OFFSCREEN) {
  app.disableHardwareAcceleration();
  //app.commandLine.appendSwitch('disable-software-rasterizer');
  //app.commandLine.appendSwitch('in-process-gpu');
}

app.on('ready', () => {

  win = new BrowserWindow({
    width: 1440,
    height: 900,
    useContentSize: true,
    show: true,
    webPreferences: {
      offscreen: OFFSCREEN,
      nodeIntegration: false,
      //contextIsolation: true,
      //preload: Path.join(__dirname, 'preload.js'),
    },
  });

  win.webContents.on('did-stop-loading', event => {
    console.log('did-stop-loading');
    setTimeout(capturePage, 500);
  });

  //win.webContents.openDevTools({mode: 'right'});

  win.loadURL('https://example.org/');

});

function capturePage() {
  console.log('capturePage start');
  win.webContents.capturePage(image => {
    console.log('capturePage callback');
    fs.writeFileSync('capturePage.png', image.toPNG());
    app.exit();
  });
}
```

### Additional Information
versions tested:

- works in 3.1.13
- fails in 4.0.0 and 4.2.10
- works in 5.0.0 and 6.0.9

**Comment by bughit** [comment]
likely related to #16288

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
