### ISSUE TITLE
two cursor ？

### ISSUE THREAD

**Issue by runnerSnail** [electron/electron#20225]
example 1:

![image](https://user-images.githubusercontent.com/40654631/64834804-0dc2b700-d616-11e9-956d-8ed076f46eb7.png)

example 2:
![image](https://user-images.githubusercontent.com/40654631/64835188-8fffab00-d617-11e9-862e-4c557c9dbc8d.png)

The input box wakes up the electron application, with two cursors present
1. The first one is in another program
2. The second one is in electron app
3. Electron returns the first cursor after running the result

How do you have two cursors at the same time

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
