### ISSUE TITLE
Mimicking chromium's "install PWA to desktop" 

### ISSUE THREAD

**Issue by greasematic** [electron/electron#20235]
Hi fellow electron devs -

I'm trying to build something that mimics chromium's "install PWA to desktop" feature inside an electron app. I've tried looking at the source to figure how this could work for the 3 desktop platforms (windows, mac, linux), but haven't had much luck. 

Specifically, I want to create a desktop-apps per website (chosen by a user), without bundling electron with each of those apps (just one electron instance to run any number of such installed apps).

Could someone point me in the right direction regarding this? 

Thanks,
Girish

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
