### ISSUE TITLE
menubar reappears after going out of fullscreen 

### ISSUE THREAD

**Issue by coreybruce** [electron/electron#20237]
Menubar bug that I have seen present since Electron 5.x.x, if you use mainWindow.setMenuBarVisibility(false) to hide the menu the menu will reappear if you go into fullscreen than out of fullscreen from a web video for example instead of staying forcefully hidden.

Electron 6.0.7 
Manjaro XFCE
Was working on Electron 4.x.x and never re showed the menubar

If you use this code for example and go into a youtube video and fullescreen the video than go out you will see the menubar reappear.

```
var app = require('electron').app
var BrowserWindow = require('electron').BrowserWindow
var mainWindow

app.on('window-all-closed', function() {
  if (process.platform != 'darwin')
  app.quit()
})

//app.disableHardwareAcceleration()
app.on('ready', function() {
  mainWindow = new BrowserWindow({width: 1300, height: 900,icon: __dirname + '/icon.png'})
  mainWindow.setMenuBarVisibility(false)
  mainWindow.loadURL('file://' + __dirname + '/index.html') // Load splash screen
  mainWindow.maximize() // start maximized
  setTimeout(function () {
    mainWindow.loadURL('https://youtube.com/')
  }, 3000) // Load store page after 3 secs

  // Emitted when the window is closed.
  mainWindow.on('closed', function() {
    mainWindow = null;
  })

  mainWindow.webContents.on('new-window', (event, url) => {
    event.preventDefault()
    let pSize = mainWindow.getSize()
    const win = new BrowserWindow({ width: pSize[0], height: pSize[1]})
    win.loadURL(url)
    event.newGuest = win
  })
})
```

**Comment by James-Livesey** [comment]
Tested on both Windows 10 and Linux (Debian using Chrome OS Crostini), can confirm it appears to only happen in Linux.

**Comment by coreybruce** [comment]
Seems to be a issue with the code

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by krassowski** [comment]
I am still seeing this issue on Linux (Ubuntu) with Electron 10.x. I guess it is not a supported version any longer, but just to put the records straight it does not seem to be fixed on 7.x for me; for a simple workaround see https://github.com/jupyterlab/jupyterlab_app/pull/255/commits/12819f95f7ebd8f0f155fdb618896f1cc353ef01.

**Comment by coreybruce** [comment]
> I am still seeing this issue on Linux (Ubuntu) with Electron 10.x. I guess 10.x it is not a supported version any longer, but just to put the records straight it does not seem to be fixed on 7.x for me; for a simple workaround see [jupyterlab/jupyterlab_app@12819f9](https://github.com/jupyterlab/jupyterlab_app/commit/12819f95f7ebd8f0f155fdb618896f1cc353ef01).
> 
> Edit: this was also reported in #19426.

Move to the newer version of Electron, you should always stick to the newest version for security, patches and fixes.
