### ISSUE TITLE
child_process methods are slow on detached Electron (macOS)

### ISSUE THREAD

**Issue by aicioara** [electron/electron#20249]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.9
* **Operating System:**
  * macOS 10.14

I built an Electron application using `electron-packager` on macOS. In its simplest form, the app consists of one button which, upon press, opens an external program.

```
child_process.execFile('open', ['-a', 'Terminal', path])
```

I am observing a 50x slowdown of the function call above when running the application detached from a terminal (for example started using Spotlight or Finder) compared to running it from the terminal

```
hello.app/Contents/MacOS/hello
```

Started from Terminal + press button => External app opens in 100 ms

Started from Finder + press button => External app opens in 5 seconds

Any hints of what could be the issue?

```
| Package           | Version  | 
| ----------------- | -------- |
| npm               | 6.4.1    |
| node              | v10.15.2 |
| electron          | 6.0.9    |
| electron-packager | 14.0.5   |
```

**Comment by aicioara** [comment]
Is there something that I can provide to help you reproduce? 

Is there a recommended way for me to profile the detached electron app?

**Comment by BeardScript** [comment]
I am experiencing the same issue. I find myself forced to open my packaged app with the terminal if I don't want to have a delay of up to 5 seconds to open an external app in a super PC. I'll start digging into why this is happening, but in the meantime I'm considering alternatives. Is there a way to distribute the app in a way that it opens attached to a terminal without the user having to do it manually?

**Comment by aicioara** [comment]
I am also still stuck because of this. @sofianguy, do you have any pointers for us, so we can begin an investigation?

**Comment by BeardScript** [comment]
@aicioara do you know of any alternatives? I tried this: https://www.npmjs.com/package/electron-terminal-open but don't seem to be able to make it work. I'm trying to look for some tool to pack the app in a way that it runs from the command line but I'm not finding anything. How are you packaging your app?

**Comment by aicioara** [comment]
I did not try other 3rd party apps. I assume they just wrap around existing Node APIs. 

About starting from terminal, I guess you can make a starting script that opens a terminal and executes the app, then closes the terminal, but that sounds really hacky and will add significant overhead to your start time. 

Below is my packaging script.

```
ELECTRON_IS_DEV=1 electron-packager . --out ../dist --extraResource '../main/build' --overwrite
```

**Comment by BeardScript** [comment]
@aicioara and @sofianguy I don't know if you tried this on Windows 10 yet but at least on my end, it works as expected there. I've already made my peace with the fact that I'll have to ask my macOS users to open the program with the terminal until I have time to create a launcher. @sofianguy I'll have time to look into this after I release my alpha. Can you point me in the right direction? Thanks!

**Comment by felixfaire** [comment]
I am also experiencing this issue. Was there any progress on why this happens or how to mitigate it? Is this related to apple firewalls checking each call to a terminal command?

**Comment by aicioara** [comment]
Could be. I experience this on macOS

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
