### ISSUE TITLE
Cannot use service worker in html document served from custom protocol: The document is in an invalid state.

### ISSUE THREAD

**Issue by mjbvz** [electron/electron#20248]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  * 7.0.0-beta.4
* **Operating System:** 
  * macOS 10.14.6
* **Last Known Working Electron version:** 
  * NA

### Expected Behavior
Serve up a simple html page inside an iframe using a custom protocol (`test-scheme` in this example). The html page should be able to register a service worker to handle requests

Here's the example main process code:

```js
protocol.registerSchemesAsPrivileged([
  { scheme: 'test-scheme', privileges: { allowServiceWorkers: true, standard: true, secure: true } }
]);
```

```js
 protocol.registerStringProtocol('test-scheme, (request, cb) => {
    cb({
      mimeType: 'text/html',
      charset: 'utf-8',
      data: `<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Heey World!</title>
  </head>
  <body>
    Hello iframe!
    <script>
      window.navigator.serviceWorker.register('service-worker.js', {scope: './'}).then(function(registration) {
        console.log('All good')
      })
    </script>
  </body>
</html>`
    })
  });
```

### Actual Behavior
The service worker cannot be registered. In the dev tools console, I see the error: 

```
DOMException: Failed to register a ServiceWorker: The document is in an invalid state.
```

### To Reproduce
Use the electron fiddle: https://gist.github.com/98ead2337cf17febffa64f731a8cc3e8

Look at the devtools output to see the errors

### Additional Information

/cc @deepak1556 - This is blocks migrating VS Code to use normal iframes for its webviews

**Comment by cawa-93** [comment]
I encountered the same problem

* **Electron Version:**
  * 8.0.0-beta.5
* **Operating System:**
  * macOS 10.15.1
* **Last Known Working Electron version:**
  * N/A

I use custom protocol:
```js
protocol.registerSchemesAsPrivileged([
  {
    scheme: 'app',
    privileges: {
      secure: true,
      standard: true,
      allowServiceWorkers: true,
      supportFetchAPI: true
    }
  },
]);
```

And got error when try register service worker

```js
navigator.serviceWorker.register('/path/to/service-worker.js')
```
```
DOMException: Failed to register a ServiceWorker: The document is in an invalid state
```

**Comment by cawa-93** [comment]
In electron 8.0.0-beta.6 i got same problem with another text:
```
TypeError: Failed to register a ServiceWorker: The URL protocol of the current origin ('app://.') is not supported
```

**Comment by cawa-93** [comment]
Same in 8.0.0

**Comment by vladimiry** [comment]
Facing this issue in v10.1.5.

**Comment by vladimiry** [comment]
@cawa-93, see my previous message (you have to set `allowServiceWorkers: true` flag, etc). But still you will likely face the `The document is in an invalid state` then.

**Comment by deepak1556** [comment]
Updated gist https://gist.github.com/deepak1556/7caeef7c8d63cf7d537bcfd0c9406bae
