### ISSUE TITLE
Property 'canceled' does not exist on type 'OpenDialogReturnValue'

### ISSUE THREAD

**Issue by Akumzy** [electron/electron#20243]
I noticed that `OpenDialogReturnValue` has a property called canceled and it's even documented but it has no type definition in ` OpenDialogReturnValue` interface 

`canceled - Boolean - whether or not the dialog was canceled.`

I can define it if I know where to get the types definition files.

**Comment by Olybear9** [comment]
Try "cancelled" it might be an error in the documentation.

**Comment by Akumzy** [comment]
I checked `OpenDialogReturnValue` interface it has no such property

**Comment by MarshallOfSound** [comment]
Just a small typo in the docs --> https://github.com/electron/electron/pull/20246

**Comment by Akumzy** [comment]
@MarshallOfSound  I don't think my issue was understood 
`Electron.OpenDialogReturnValue` has no property called `canceled` in it's Typescript interface definition and it's causing linting error `Property 'canceled' does not exist on type 'OpenDialogReturnValue'`
```js
  interface OpenDialogReturnValue {
    /**
     * An array of file paths chosen by the user. If the dialog is cancelled this will
     * be an empty array.
     */
    filePaths?: string[];
    /**
     * An array matching the filePaths array of base64 encoded strings which contains
     * security scoped bookmark data. securityScopedBookmarks must be enabled for this
     * to be populated.
     */
    bookmarks?: string[];
  }
```

**Comment by MarshallOfSound** [comment]
>  I don't think my issue was understood

Nope, perfectly understood.  Electrons typescript definitions are generated from the markdown documentation.  See https://github.com/electron/electron/pull/20246/checks?check_run_id=224444328 for the changes that that PR caused.

**Comment by Akumzy** [comment]
Ooh great I didn't know and that explained why I couldn't find the electron.d.ts file

**Comment by sofianguy** [comment]
fixed https://github.com/electron/electron/pull/20246
