### ISSUE TITLE
macOS Catalina 10.15 beta 

### ISSUE THREAD

**Issue by roy2651** [electron/electron#20242]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

I have updated my mac os to Catalina 10.15 beta , and test my electron app.
I share screen via eletron, as webrtc but  it does not work，and remote is black

### Proposed Solution

mac os Catalina 10.15 beta is new os featrue such as screen recorder authority，when I give authority to my electron app is ok。

### Alternatives Considered

is anybody has update mac os to beta，testing electron is ok，and if any soultion work this。

**Comment by varisbhalala** [comment]
navigator.geolocation.getcurrentposition not working in electron mac os catalina

**Comment by dwilson6** [comment]
I am seeing issues too with the desktopCapturer and screen capture on macOS Catalina. I've tried electron 5.0.8 and electron 7 beta 6. I know Catalina added a permission request for screen capture/recording and [the webrtc stack in Chromium had to be updated](https://groups.google.com/forum/#!msg/discuss-webrtc/C1T2wGEaakQ/agrPP_wMBQAJ) to account for it. 

The behavior I see in electron is that `desktopCapturer.getSources` and `navigator.mediaDevices.getUserMedia({ video: { mandatory: { chromeMediaSource: 'desktop' } } })` both resolve before the permission is granted or denied. If permission is denied (or not explicitly granted), the media stream captures the background and top bar and you can see the cursor moving. If permission is granted, the next stream you capture will capture correctly. Denying permission while a stream is active doesn't seem to affect the stream. Only subsequent requests for streams.

Here's a guide that shows what the UX for the permission request is like: https://dropshare.zendesk.com/hc/en-us/articles/360033453434-Enabling-Screen-Recording-Permission-on-macOS-Catalina-10-15-

Also, I haven't been able to find any reference to the actual api Apple added to wait for the permission request other than [this discussion](https://stackoverflow.com/questions/56597221/detecting-screen-recording-settings-on-macos-catalina). I guess there's also probably something in the webrtc source code.

**Comment by dwilson6** [comment]
> One potential workarround meanwhile the fix come is to check if desktopCapturer.getSources list the current running app at startup time and if it isn't you know that the user didn't gave the authorisation. It's dirty but should work for hurry peoples.

I tried that on electron 5.0.8 but my app shows in the window list whether or not permissions are granted

**Comment by tannerlinsley** [comment]
I'll just drop by with my experience here: I wasn't able to even manually grant permissions to the Electron app during development because the electron process was hiding in my permissions list as my terminal application (which I did not give permissions to). Only after resetting all of my camera permissions via `tccutil reset ScreenCapture`, did I realize this and then granted permissions to my terminal to do screen capture. 🤷‍♂️

**Comment by radespy** [comment]
I'm running Catalina 10.15.6 and have reset screen permissions using: npm [mac-screen-capture-permissions](https://www.npmjs.com/package/mac-screen-capture-permissions).

Within my renderer.js file, I get :-

systemPreferences.getMediaAccessStatus("screen") // true

but get the following on using desktopCapturer:

`const {
  remote,
  desktopCapturer,
  systemPreferences,
  BrowserWindow,
} = require("electron").remote;

desktopCapturer
    .getSources({
      types: ["screen"],
    })
    .then((source) => console.log(source));
};`

Returns : Uncaught TypeError: Cannot read property 'getSources' of undefined.

Has any one experienced this ? What am I missing here ? tnx

**Comment by dwilson6** [comment]
Looks like your require might be the problem. It is expecting desktopCapturer to be under electron.remote when it is directly on the electron object. I think it should work if you take the `.remote` off at the end of your require statement.

**Comment by radespy** [comment]
It works. Thanks a lot !!!
