### ISSUE TITLE
关于electron v2.0.4版本拖拽的问题

### ISSUE THREAD

**Issue by 18241893068** [electron/electron#20252]
我在开发中遇到的，在electron v2.0.4版本开发中，将电脑的分辨率放大到125%以上的时候，用setPosition自定义的拖拽事件，拖拽时，electron窗口自动变大。在下是萌新的原因，可能会写的有问题。不过没找到原因，所以请指点一二

**Comment by jkleinsc** [comment]
Electron v2.0.4  is no longer supported.  Please try a newer version (v4.2.9 or greater) to see if the problem you see is still there.
不再支持Electron v2.0.4。请尝试更新的版本（v4.2.9或更高版本），看看你看到的问题是否仍然存在。

**Comment by jianghaiqun** [comment]
@jkleinsc electron 升级到v6.0.9 问题依然在。

**Comment by jkleinsc** [comment]
好的，如果Electron v6.0.9中仍然存在问题，请提交一个新问题，详细说明问题以及如何重现

**Comment by jkleinsc** [comment]
Ok if there is still a problem in Electron v6.0.9 please file a new issue with exact details of the problem and how to reproduce it
