### ISSUE TITLE
CrashReport not work in Mac

### ISSUE THREAD

**Issue by Leaking** [electron/electron#20253]
electron: 5.0.8
Platform: Darwin QUINNHZCHEN-MB0 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64

i have set CrashReporter for both my render process and main process,

```javascript
crashReporter.start({
    productName: 'WeDrive',
    companyName: 'tencent',
    submitURL: 'http://localhost:3000/api/app-crashes',
    uploadToServer: true
  })
```

And i use express to start a local server listening port 3000

When I invoke a crash by 'process.crash', and the CrashReport not work, i just see the following log after crash

```xml

┏ Electron -------------------

  [0917/172044.867442:ERROR:http_transport_mac.mm(297)] HTTP status 404
  
┗ ----------------------------
```

**Comment by tmm1** [comment]
What was the solution?
