### ISSUE TITLE
No audio channel exists

### ISSUE THREAD

**Issue by Jokershaoc** [electron/electron#20251]
在electron上开发电话app中，第二次铃声出现错误提示：
[41151:0917/165851.453658:ERROR:rtpreceiver.cc(59)] AudioRtpReceiver::OnSetVolume: No audio channel exists.

**Comment by jkleinsc** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community).

GitHub问题适用于功能请求和错误报告，有关使用Electron或代码帮助请求的问题应该直接发送到[社区] https://github.com/electron/electron#community
