### ISSUE TITLE
Task View animation bug

### ISSUE THREAD

**Issue by carlosgolivas** [electron/electron#20265]
https://imgur.com/a/k9Nxuet

Hey, I noticed this problem quite some time ago but didn't realize until now that it's happening in a lot of Electron Apps (Spotify, Discord, WhatsApp, VS Code etc.) when you open it from the task viewer and the app is minimized.

**Comment by codebytere** [comment]
@carlosgolivas at present it's not demonstrably clear that this originates in Electron - we recommend that this first be reported to consumers whose apps you're experiencing this on. If this becomes reproducable in a standalone app, they can then file an issue with us :)
