### ISSUE TITLE
Black screen on window close in fullscreen mode

### ISSUE THREAD

**Issue by alxmiron** [electron/electron#20263]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.9
* **Operating System:**
  * MacOS 10.14.6

### To Reproduce
1. Open electron window with control buttons by `new BrowserWindow({ frame: true })`
1. Change close logic to default mac behavior - hide app on close, not quit. Can be done by 
```
mainWindow.on('close', event => {
     event.preventDefault();
     mainWindow.hide();
});
```
3. Set fullscreen mode
4. Click close button

### Expected Behavior
Window is hidden

### Actual Behavior
Full screen gets black 

### Screenshots

![Sep-17-2019 22-04-46](https://user-images.githubusercontent.com/10484318/65071969-93d55980-d998-11e9-9c25-5c6300f4cc8e.gif)

### Notes

Bug is not actual if mainWindow was cloed from normal mode (not fullscreen)

**Comment by HaNdTriX** [comment]
The same bug applies to Electron-Version 7 as well:

- `electron@7.0.0-beta.3`
- `electron@7.0.0-beta.4`
- `electron@7.0.0-beta.5`

**Comment by alxmiron** [comment]
Not yet. Yes, you can exit fullscreen or exit entire app instead of hiding, but it's not an expected behavior

**Comment by jackple** [comment]
@HaNdTriX You can use `setTimeout`, like:
```ts
if (is.macos && mainWindow.isFullScreen()) {
  mainWindow.setFullScreen(false)
  await wait(750)
}
mainWindow.hide()
```

**Comment by holmberd** [comment]
@jackple instead of a timeout you can use the callback from the `leave-full-screen` window event.

**Comment by agalwood** [comment]
I also encountered this problem, thanks to the `leave-full-screen` event mentioned by @holmberd , this is my code :

```javascript
window.on('close', (event) => {
  if (window.isFullScreen()) {
    window.once('leave-full-screen', () => window.hide())

    window.setFullScreen(false)
  } else {
    window.hide()
  }
})
```

**Comment by whitemiaool** [comment]
+1

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by Safa-gh** [comment]
Reproduced on 13.6.1, please fix

**Comment by pushkin-** [comment]
reopened the issue [here](https://github.com/electron/electron/issues/39572)
