### ISSUE TITLE
Ability to force ELECTRON_NO_ATTACH_CONSOLE in production Electron app

### ISSUE THREAD

**Issue by cheynewallace** [electron/electron#20266]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
Im about to launch an Electron app, although i've just discovered that when you run the app from the command line in Windows the terminal session attaches to the log output from the Electron app. You can't quit the terminal session because it will kill the app.

I need my app to be launched on startup of Windows, without having the ugly terminal screen there. I would also like people to be able to script it's start without needing the terminal to stay alive.

I know I can do this with the `ELECTRON_NO_ATTACH_CONSOLE` env var, but there doesn't seem to be a way to force this to be always on. I don't want to tell people they need to set `ELECTRON_NO_ATTACH_CONSOLE=true` before running the app, thats ugly.  

Using Electron builder to build the production app.  Have tried forcing `env.ELECTRON_NO_ATTACH_CONSOLE=true` at the top of my `electron.js` main file, before anything else loads, but that seems to do nothing. 

As far as I can tell, its not possible right now (really happy if someone can prove me wrong).  

### Proposed Solution
Have the ability to configure these options without the need for environment variables.  

### Alternatives Considered
Asked the question here: https://stackoverflow.com/questions/57841304/how-to-force-electron-no-attach-console-in-production-electron-app  with no luck

### Additional Information
Just need to ability to start this app automatically (on Windows) without having make my users specify a bunch of env vars.  They should just be able to run the .exe like any other .exe.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

**Comment by FrankenApps** [comment]
This clearly sound like a feature request to me, is it not?
