### ISSUE TITLE
Renderer process leaked/orphaned when page that uses SharedWorker and remote module is closed

### ISSUE THREAD

**Issue by devmonkey22** [electron/electron#20277]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** (reproduces on all of these):
  * Electron v6.0.0  Chromium v76.0.3809.88  Node v12.4.0  v8 v7.6.303.27-electron.0
  * Electron v6.0.9  Chromium v76.0.3809.146  Node v12.4.0  v8 v7.6.303.31-electron.0
  * Electron v7.0.0-beta.4  Chromium v78.0.3896.6  Node v12.8.1  v8 v7.8.212.1-electron.0

* **Operating System:**
  * Windows 10.0.17763 Build 17763
  * (Ubuntu 18 does not appear to be affected)

* **Last Known Working Electron version:**
   * Electron v5.0.10  Chromium v73.0.3683.121  Node v12.0.0  v8 v7.3.492.27-electron.0

### Expected Behavior
After loading a page with a `SharedWorker` and a preload script that requires the `remote` module, when electron closes, all electron and chromium renderer processes exit cleanly.

### Actual Behavior
After loading a page with a `SharedWorker` and a preload script that requires the `remote` module, when electron closes, it leaves a leaked/orphaned chromium renderer process running after all other electron processes exit.

### To Reproduce
This issue is readily reproducible for me with the following steps:

1. Run: `git clone https://github.com/devmonkey22/electron-renderer-leak.git`
2. Run: `npm install`
3. Run: `npm start`
4. Observe your process list with a tool like Process Explorer (tree view is best) or Task Manager. Notice the single renderer process and PID, along with other electron processes.
5. Close Electron
6. Observe that the `electron --type=renderer` process remains after all other processes exit.

The orphaned process doesn't use much CPU, but holds quite a bit of RAM until its forced terminated.

### Screenshots

While running:
<img width="1528" alt="renderer-leak-while-running" src="https://user-images.githubusercontent.com/5084545/65179170-40125100-da28-11e9-9017-dd013f260c57.png">

After closing Electron:
<img width="1535" alt="renderer-leak-orphaned" src="https://user-images.githubusercontent.com/5084545/65179187-46083200-da28-11e9-9466-f6c085468280.png">

### Additional Information
I'm not sure why, but this requires the combination of SharedWorker and require of `remote` module in preload to trigger the issue.  If either feature is commented out, the leak does not occur.

Originally my issue was occurring within a `webview` that used a SharedWorker (who is supposed to close the port during the `beforeunload` event, but that doesn't fire consistently (at all?) with Electron/Chromium.  However, I was able to isolate it that to occur in the main renderer, not just a webview now through the sample given.  Even when I close the port to the SharedWorker manually (via setTimeout after X seconds for example), the process still leaks.

When I downgraded my sample to 5.0.10, the issue did not occur.

**Comment by originalmoose** [comment]
I'm seeing a similar issue with the orphaned process, I commented on the forums about it to try and get some debugging help https://discuss.atom.io/t/after-upgrade-to-6-0-x-renderer-process-not-closing-on-app-quit-on-windows/67926 we are using the pendo io library to track user actions. When I comment out the pendo initialization call the process is correctly terminated. I checked the source for the library and it is not using a SharedWorker so it may be a separate issue (we are using remote calls from the browser window). I verified the issue still occurs with electron 7.0.0

**Comment by amirebrahimi** [comment]
For those coming here please take a look at: https://github.com/lutzroeder/netron/issues/322#issuecomment-739090316

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
