### ISSUE TITLE
Electron 5: crashed in MenuModelAdapter and MenuModel

### ISSUE THREAD

**Issue by aabuhijleh** [electron/electron#20284]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  5.0.6 (32-bit)
* **Operating System:**
  *  Windows 7 Version 7601 (Service Pack 1)

Our crash data shows a crash related to menus (At `MenuModel::GetModelAndIndexForCommandId`). Not sure how to reproduce.

### Crash

<details>
  <summary>Details</summary>
  Windows 7 Version 7601 (Service Pack 1) MP (4 procs) Free x86 compatible
Product: WinNt, suite: SingleUserTS
kernel32.dll version: 6.1.7601.24499 (win7sp1_ldr.190612-0600)
Machine Name:
Debug session time: Thu Sep 19 09:31:13.000 2019 (UTC + 0:00)
System Uptime: not available
Process Uptime: 3 days 14:16:45.000
  Kernel time: 0 days 0:18:25.000
  User time: 0 days 0:39:45.000

Effective machine: x86 compatible (x86)

THREAD ID: 0

(Crashed here) 002fefdc 03903dbe 00003121 002feff4 002feff0 ui::MenuModel::GetModelAndIndexForCommandId+0x1d [C:\projects\src\ui\base\models\menu_model.cc @ 17]
002ff000 04876843 00003121 002ff010 00000000 views::MenuModelAdapter::GetAccelerator+0x2e [C:\projects\src\ui\views\controls\menu\menu_model_adapter.cc @ 161]
002ff060 03900f49 13040dc0 002ff070 01220000 views::MenuConfig::ShouldShowAcceleratorText+0x63 [C:\projects\src\ui\views\controls\menu\menu_config.cc @ 93]
002ff098 03900c7e 002ff0a4 00bf27a8 ffff0000 views::MenuItemView::GetMinorText+0x57 [C:\projects\src\ui\views\controls\menu\menu_item_view.cc @ 1350]
002ff174 048666e5 13061f5c 00000000 00000000 views::MenuItemView::GetAccessibleNodeData+0x10e [C:\projects\src\ui\views\controls\menu\menu_item_view.cc @ 184]
002ff1c4 04864b67 13061f5c 13061ea0 e60be934 views::ViewAccessibility::GetAccessibleNodeData+0x65 [C:\projects\src\ui\views\accessibility\view_accessibility.cc @ 142]
002ff1e4 02f8f53d 13725c18 13725c68 002ff23c views::ViewAXPlatformNodeDelegate::GetData+0x47 [C:\projects\src\ui\views\accessibility\view_ax_platform_node_delegate.cc @ 206]
002ff1f4 02f85064 13725e38 002ff218 02f95836 ui::AXPlatformNodeWin::IsWebAreaForPresentationalIframe+0x11 [C:\projects\src\ui\accessibility\platform\ax_platform_node_win.cc @ 3979]
002ff23c 02f84fa8 001a19e6 13725de8 13725de8 ui::AXPlatformNodeWin::MSAARole+0x1a [C:\projects\src\ui\accessibility\platform\ax_platform_node_win.cc @ 3455]
002ff26c 048647f9 0000002d 13040dc0 002ff294 ui::AXPlatformNodeWin::NotifyAccessibilityEvent+0x68 [C:\projects\src\ui\accessibility\platform\ax_platform_node_win.cc @ 481]
002ff2b0 038e82a2 0000002d 13040dc0 0ae42448 views::ViewAXPlatformNodeDelegate::NotifyAccessibilityEvent+0x59 [C:\projects\src\ui\views\accessibility\view_ax_platform_node_delegate.cc @ 140]
002ff2c8 04877143 0000002d 00000001 0ae42448 views::View::NotifyAccessibilityEvent+0x3a [C:\projects\src\ui\views\view.cc @ 1385]
002ff324 04878802 13040dc0 00000000 00000001 views::MenuController::SetSelection+0x1dd [C:\projects\src\ui\views\controls\menu\menu_controller.cc @ 1275]
002ff358 0487872a 130e45b0 002ff378 0a104068 views::MenuController::HandleMouseLocation+0xc0 [C:\projects\src\ui\views\controls\menu\menu_controller.cc @ 0]
002ff464 039003f8 130e45b0 002ff748 002ff748 views::MenuController::OnMouseMoved+0x14a [C:\projects\src\ui\views\controls\menu\menu_controller.cc @ 791]
002ff47c 038f1137 002ff748 e60bec70 0000009b views::MenuHostRootView::OnMouseMoved+0x28 [C:\projects\src\ui\views\controls\menu\menu_host_root_view.cc @ 34]
002ff4b4 02d47288 002ff748 002ff514 002ff748 views::Widget::OnMouseEvent+0x227 [C:\projects\src\ui\views\widget\widget.cc @ 1294]
002ff4c8 02d470ee 002ff748 002ff514 13089420 ui::EventHandler::OnEvent+0x48 [C:\projects\src\ui\events\event_handler.cc @ 42]
002ff4e0 02d46dc1 13376b7c 002ff748 002ff520 ui::EventDispatcher::DispatchEvent+0x2c [C:\projects\src\ui\events\event_dispatcher.cc @ 194]
002ff500 02d46c82 13089420 002ff748 00000000 ui::EventDispatcher::ProcessEvent+0xb1 [C:\projects\src\ui\events\event_dispatcher.cc @ 143]
002ff53c 02d46be0 002ff554 13089420 002ff748 ui::EventDispatcherDelegate::DispatchEventToTarget+0x46 [C:\projects\src\ui\events\event_dispatcher.cc @ 87]
002ff568 02d47465 002ff58c 13089420 002ff748 ui::EventDispatcherDelegate::DispatchEvent+0x62 [C:\projects\src\ui\events\event_dispatcher.cc @ 58]
002ff5a8 02d4786b 002ff5e0 002ff748 002ff5e0 ui::EventProcessor::OnEventFromSource+0x115 [C:\projects\src\ui\events\event_processor.cc @ 21]
002ff5bc 02d476cd 002ff5e0 002ff748 0a1d9df4 ui::EventSource::DeliverEventToSink+0x1b [C:\projects\src\ui\events\event_source.cc @ 50]
002ff5f8 02d47846 002ff620 002ff748 00000000 ui::EventSource::SendEventToSinkFromRewriter+0x19d [C:\projects\src\ui\events\event_source.cc @ 93]
002ff610 04864190 002ff620 002ff748 1332ad28 ui::EventSource::SendEventToSink+0x12 [C:\projects\src\ui\events\event_source.cc @ 43]
002ff634 038f8e91 002ff748 131d7a48 00000200 views::DesktopWindowTreeHostWin::HandleMouseEvent+0x60 [C:\projects\src\ui\views\widget\desktop_aura\desktop_window_tree_host_win.cc @ 910]
002ff838 038f7b37 00000200 00000000 0072009b views::HWNDMessageHandler::HandleMouseEventInternal+0x2f1 [C:\projects\src\ui\views\win\hwnd_message_handler.cc @ 2919]
002ff87c 038f79c9 001a19e6 00000200 00000000 views::HWNDMessageHandler::_ProcessWindowMessage+0x7f [C:\projects\src\ui\views\win\hwnd_message_handler.h @ 330]
002ff8c0 02c92915 00000200 00000000 0072009b views::HWNDMessageHandler::OnWndProc+0x79 [C:\projects\src\ui\views\win\hwnd_message_handler.cc @ 987]
002ff8e0 02c927b0 001a19e6 00000200 00000000 gfx::WindowImpl::WndProc+0x53 [C:\projects\src\ui\gfx\win\window_impl.cc @ 303]
DBGHELP: user32 - public symbols  
        z:\ossymbols\wuser32.pdb\2989D28D81D042579DB67AD418C0AF682\wuser32.pdb
002ff920 767c62fa 001a19e6 00000200 00000000 base::win::WrappedWindowProc<&gfx::WindowImpl::WndProc>+0x50 [C:\projects\src\base\win\wrapped_window_proc.h @ 79]
002ff94c 767c6d3a 02c92760 001a19e6 00000200 user32!InternalCallWinProc+0x23
002ff9c4 767c77c4 00000000 02c92760 001a19e6 user32!UserCallWinProcCheckWow+0x109
002ffa24 767c788a 02c92760 00000000 002ffa9c user32!DispatchMessageWorker+0x3b5
002ffa34 02a461f3 002ffaac 002ffaac 00000000 user32!DispatchMessageW+0xf
002ffa9c 02a45dc9 002ffaac 01003f60 001a19e6 base::MessagePumpForUI::ProcessMessageHelper+0x213 [C:\projects\src\base\message_loop\message_pump_win.cc @ 380]
002ffad8 02a457f1 01008f8c 00bc0000 00000001 base::MessagePumpForUI::DoRunLoop+0x59 [C:\projects\src\base\message_loop\message_pump_win.cc @ 176]
002ffaf8 02a44a0f 01008f8c 002ffb64 002ffb50 base::MessagePumpWin::Run+0x41 [C:\projects\src\base\message_loop\message_pump_win.cc @ 54]
002ffb08 02a60943 00000001 002ffb3c 002ffb34 base::MessageLoopImpl::Run+0x1f [C:\projects\src\base\message_loop\message_loop_impl.cc @ 305]
002ffb50 01a69a0a e60be3b0 002ffb58 002ffb54 base::RunLoop::Run+0x1a3 [C:\projects\src\base\run_loop.cc @ 156]
002ffb90 01a69894 002ffba8 02a94b03 e60be364 content::BrowserMainLoop::MainMessageLoopRun+0xf2 [C:\projects\src\content\browser\browser_main_loop.cc @ 1554]
002ffbb4 01a6b7de 002ffbc8 002ffbf8 01a66c34 content::BrowserMainLoop::RunMainMessageLoopParts+0x40 [C:\projects\src\content\browser\browser_main_loop.cc @ 1005]
002ffbc0 01a66c34 01006db0 00726573 012244cf content::BrowserMainRunnerImpl::Run+0xe [C:\projects\src\content\browser\browser_main_runner_impl.cc @ 166]
002ffbf8 028b2b0c 002ffc74 002ffc00 02ada5d6 content::BrowserMain+0x95 [C:\projects\src\content\browser\browser_main.cc @ 47]
002ffc2c 028b340b 002ffc74 002ffdf0 00bf0660 content::RunBrowserProcessMain+0x54 [C:\projects\src\content\app\content_main_runner_impl.cc @ 545]
002ffc5c 028b3157 002ffc74 00000000 00befc98 content::ContentMainRunnerImpl::RunServiceManager+0x293 [C:\projects\src\content\app\content_main_runner_impl.cc @ 954]
002ffcb0 028b2883 00000000 002ffd8c 002ffd7c content::ContentMainRunnerImpl::Run+0xd7 [C:\projects\src\content\app\content_main_runner_impl.cc @ 0]
002ffcc0 0319064d 002ffd90 00000000 00000000 content::ContentServiceManagerMainDelegate::RunEmbedderProcess+0x13 [C:\projects\src\content\app\content_service_manager_main_delegate.cc @ 53]
002ffd7c 028b2a8f 002ffd88 002ffd8c 053f47f0 service_manager::Main+0x159 [C:\projects\src\services\service_manager\embedder\main.cc @ 461]
002ffdbc 0122132c 002ffdcc 002ffde4 002ffdf0 content::ContentMain+0x33 [C:\projects\src\content\app\content_main.cc @ 19]
002ffe20 0520156a 01220000 00000000 00741d1a wWinMain+0x222 [C:\projects\src\electron\atom\app\atom_main.cc @ 181]
DBGHELP: kernel32 - public symbols  
        z:\ossymbols\wkernel32.pdb\8DAD93F4ACB8492EBCB1F76FB9BE79162\wkernel32.pdb
002ffe6c 760e343d fffde000 002ffeb8 77109802 __scrt_common_main_seh+0xf8 [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl @ 283]
002ffe78 77109802 fffde000 77378ad3 00000000 kernel32!BaseThreadInitThunk+0xe
002ffeb8 771097d5 052015f0 fffde000 00000000 ntdll!__RtlUserThreadStart+0x70
002ffed0 00000000 052015f0 fffde000 00000000 ntdll!_RtlUserThreadStart+0x1b
</details>

**Comment by codebytere** [comment]
While we appreciate this crash report, unfortunately this isn't actionable for us right now without a repro. In order for this issue to remain open, we'd appreciate if you could determine and demonstrate a way for us to reproduce this, or we'll be unable to triage this. 

I'm setting the `blocked` label for the above reasons, and as such we'll close this issue in 10 days should a repro not be determined.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
