### ISSUE TITLE
How do I open a new subrouting window

### ISSUE THREAD

**Issue by Staryixing** [electron/electron#20294]
### Problem Description

How do I open a new subrouting window

'./build/index.htm/#/home'

  winRemote = new BrowserWindow({ 
      width: 450, 
      height: 800
  })
  winRemote.loadFile('./build/index.html',{
    hash: 'home'
  })

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
