### ISSUE TITLE
[Windows] window stick on a side moves back to previous position on reload

### ISSUE THREAD

**Issue by CptMaumau** [electron/electron#20296]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.7
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 

### Expected Behavior
window reloads without moving

### Actual Behavior
Window moves to previous position after reload

### To Reproduce
Stick window on a side then trigger reload.

### Additional Information
In my case reload is triggered on a browserView inside the browserWindow.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
