### ISSUE TITLE
patch failure during build of electron on 6-0-x branch

### ISSUE THREAD

**Issue by willward** [electron/electron#20299]
steps to reproduce : 
```
$ mkdir electron-gn && cd electron-gn
$ gclient config --name "src/electron" --unmanaged https://github.com/electron/electron
$ mkdir -p src/electron
$ cd src/electron
$ git clone https://github.com/electron/electron .
$ git checkout 6-0-x
$ cd ../../
$ gclient sync --with_branch_heads --with_tags
```

patch error : 

```
Applying: patch the ensure_gn_version.py script to work on mac CI
Applying: build: add electron tracing category
Applying: Add ContentGpuClient::PreCreateMessageLoop() callback
Applying: Disable custom libcxx on windows
Applying: fix breakpad symbol generation on linux arm
Applying: build: pull in a fixed compiler for Windows on Arm
Applying: cross_site_document_resource_handler.patch
Applying: frame_host_manager.patch
Applying: crashpad_pid_check.patch
Applying: fix: use WeakPtr to detect deletion
Applying: fix: disabling compositor recycling
Applying: allow new privileges in unsandboxed child processes
error: patch failed: DEPS:172
error: DEPS: patch does not apply
Patch failed at 0085 allow new privileges in unsandboxed child processes
The copy of the patch that failed is found in: .git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
Traceback (most recent call last):
  File "src/electron/script/apply_all_patches.py", line 32, in <module>
    main()
  File "src/electron/script/apply_all_patches.py", line 28, in main
    apply_patches(json.load(config_json))
  File "src/electron/script/apply_all_patches.py", line 14, in apply_patches
    committer_name="Electron Scripts", committer_email="scripts@electron")
  File "/home/build/dev/electron-gn/src/electron/script/lib/git.py", line 67, in am
    proc.returncode))
RuntimeError: Command ['git', '-C', u'src', '-c', 'user.name=Electron Scripts', '-c', 'user.email=scripts@electron', '-c', 'commit.gpgsign=false', 'am'] returned 128
Error: Command '/usr/bin/python src/electron/script/apply_all_patches.py src/electron/patches/common/config.json' returned non-zero exit status 1 in /home/build/dev/electron-gn
Hook '/usr/bin/python src/electron/script/apply_all_patches.py src/electron/patches/common/config.json' took 152.44 secs

```

**Comment by isangmeng** [comment]
I also encountered the same problem, how can I solve it？

**Comment by hinoryu** [comment]
> steps to reproduce : 
> 
> ```
> 
> $ mkdir electron-gn && cd electron-gn
> 
> $ gclient config --name "src/electron" --unmanaged https://github.com/electron/electron
> 
> $ mkdir -p src/electron
> 
> $ cd src/electron
> 
> $ git clone https://github.com/electron/electron .
> 
> $ git checkout 6-0-x
> 
> $ cd ../../
> 
> $ gclient sync --with_branch_heads --with_tags
> 
> ```
> 
> 
> 
> patch error : 
> 
> 
> 
> ```
> 
> Applying: patch the ensure_gn_version.py script to work on mac CI
> 
> Applying: build: add electron tracing category
> 
> Applying: Add ContentGpuClient::PreCreateMessageLoop() callback
> 
> Applying: Disable custom libcxx on windows
> 
> Applying: fix breakpad symbol generation on linux arm
> 
> Applying: build: pull in a fixed compiler for Windows on Arm
> 
> Applying: cross_site_document_resource_handler.patch
> 
> Applying: frame_host_manager.patch
> 
> Applying: crashpad_pid_check.patch
> 
> Applying: fix: use WeakPtr to detect deletion
> 
> Applying: fix: disabling compositor recycling
> 
> Applying: allow new privileges in unsandboxed child processes
> 
> error: patch failed: DEPS:172
> 
> error: DEPS: patch does not apply
> 
> Patch failed at 0085 allow new privileges in unsandboxed child processes
> 
> The copy of the patch that failed is found in: .git/rebase-apply/patch
> 
> When you have resolved this problem, run "git am --continue".
> 
> If you prefer to skip this patch, run "git am --skip" instead.
> 
> To restore the original branch and stop patching, run "git am --abort".
> 
> Traceback (most recent call last):
> 
>   File "src/electron/script/apply_all_patches.py", line 32, in <module>
> 
>     main()
> 
>   File "src/electron/script/apply_all_patches.py", line 28, in main
> 
>     apply_patches(json.load(config_json))
> 
>   File "src/electron/script/apply_all_patches.py", line 14, in apply_patches
> 
>     committer_name="Electron Scripts", committer_email="scripts@electron")
> 
>   File "/home/build/dev/electron-gn/src/electron/script/lib/git.py", line 67, in am
> 
>     proc.returncode))
> 
> RuntimeError: Command ['git', '-C', u'src', '-c', 'user.name=Electron Scripts', '-c', 'user.email=scripts@electron', '-c', 'commit.gpgsign=false', 'am'] returned 128
> 
> Error: Command '/usr/bin/python src/electron/script/apply_all_patches.py src/electron/patches/common/config.json' returned non-zero exit status 1 in /home/build/dev/electron-gn
> 
> Hook '/usr/bin/python src/electron/script/apply_all_patches.py src/electron/patches/common/config.json' took 152.44 secs
> 
> 
> 
> ```

**Comment by hinoryu** [comment]
> I also encountered the same problem, how can I solve it？

**Comment by hinoryu** [comment]
> steps to reproduce : 
> 
> ```
> 
> $ mkdir electron-gn && cd electron-gn
> 
> $ gclient config --name "src/electron" --unmanaged https://github.com/electron/electron
> 
> $ mkdir -p src/electron
> 
> $ cd src/electron
> 
> $ git clone https://github.com/electron/electron .
> 
> $ git checkout 6-0-x
> 
> $ cd ../../
> 
> $ gclient sync --with_branch_heads --with_tags
> 
> ```
> 
> 
> 
> patch error : 
> 
> 
> 
> ```
> 
> Applying: patch the ensure_gn_version.py script to work on mac CI
> 
> Applying: build: add electron tracing category
> 
> Applying: Add ContentGpuClient::PreCreateMessageLoop() callback
> 
> Applying: Disable custom libcxx on windows
> 
> Applying: fix breakpad symbol generation on linux arm
> 
> Applying: build: pull in a fixed compiler for Windows on Arm
> 
> Applying: cross_site_document_resource_handler.patch
> 
> Applying: frame_host_manager.patch
> 
> Applying: crashpad_pid_check.patch
> 
> Applying: fix: use WeakPtr to detect deletion
> 
> Applying: fix: disabling compositor recycling
> 
> Applying: allow new privileges in unsandboxed child processes
> 
> error: patch failed: DEPS:172
> 
> error: DEPS: patch does not apply
> 
> Patch failed at 0085 allow new privileges in unsandboxed child processes
> 
> The copy of the patch that failed is found in: .git/rebase-apply/patch
> 
> When you have resolved this problem, run "git am --continue".
> 
> If you prefer to skip this patch, run "git am --skip" instead.
> 
> To restore the original branch and stop patching, run "git am --abort".
> 
> Traceback (most recent call last):
> 
>   File "src/electron/script/apply_all_patches.py", line 32, in <module>
> 
>     main()
> 
>   File "src/electron/script/apply_all_patches.py", line 28, in main
> 
>     apply_patches(json.load(config_json))
> 
>   File "src/electron/script/apply_all_patches.py", line 14, in apply_patches
> 
>     committer_name="Electron Scripts", committer_email="scripts@electron")
> 
>   File "/home/build/dev/electron-gn/src/electron/script/lib/git.py", line 67, in am
> 
>     proc.returncode))
> 
> RuntimeError: Command ['git', '-C', u'src', '-c', 'user.name=Electron Scripts', '-c', 'user.email=scripts@electron', '-c', 'commit.gpgsign=false', 'am'] returned 128
> 
> Error: Command '/usr/bin/python src/electron/script/apply_all_patches.py src/electron/patches/common/config.json' returned non-zero exit status 1 in /home/build/dev/electron-gn
> 
> Hook '/usr/bin/python src/electron/script/apply_all_patches.py src/electron/patches/common/config.json' took 152.44 secs
> 
> 
> 
> ```
