### ISSUE TITLE
Flash is not working (webview + pepperflash)

### ISSUE THREAD

**Issue by aquaspy** [electron/electron#20309]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.10
* **Operating System:**
  *Solus 4.0 with kernel 5.2

### Expected Behavior
Game should actually load

### Actual Behavior
Game doesn't load. If you open the dev tools and in console type "navigator.plugins" you will be able to see the flash, but for some reason game isn't working.

### Additional Information
Can anyone help me? Thanks!

**Comment by coreybruce** [comment]
Flash has been a issue since Electron 5.x.x, I have been trying ot get a follow up and fix but so far nothing..

**Comment by aquaspy** [comment]
Got it. I will try with an older version. Thanks

**Comment by coreybruce** [comment]
The last version of electron that flash works on is Electron 4.2.6

**Comment by aquaspy** [comment]
Thank you so much! It worked!

So yeah, the fix to this is use the version 4.2.6

Btw, do you think they will support flash again in the future?

**Comment by coreybruce** [comment]
Yes I'm sure they will, it's a bug that is making it not work not electron support itself.

**Comment by aquaspy** [comment]
In windows latest electron works with flash player. The bug is linux only

**Comment by coreybruce** [comment]
Yes and previously in electron 5.x.x both Windows and Linux had broken flash so the electron team will need to fix the flash support on the Linux version.

**Comment by aquaspy** [comment]
Got it. I was testing right now, and latest electron that works with flash in linux is 4.2.11 haha

Thanks for all the help man

**Comment by aquaspy** [comment]
Btw, I couldn't get the cookies working in electron 4.2.11. 

const {session} = require('electron')
  win.loadURL('https://laf.world/?game');
session.defaultSession.cookies.get({}, (error, cookies) => {
    console.log(error, cookies)
  })

The cookies always return "NULL" Do you know what is causing this?

**Comment by vsellen** [comment]
Just ran into this myself. Apparently there is an issue with sandboxing. See #17034 

> The Flash Player under Linux never worked in a mixed-sandbox or (full-)sandbox environment. As of v5.0.x, mixed-sandbox is forced. This prevents the plugin from loading.

The work around is to add `app.commandLine.appendSwitch('no-sandbox')`

Worked for me v8.0.x custom build. Now to look into the associated risks of running 'no-sandbox'.

**Comment by coreybruce** [comment]
Aha! that works but not quite as while it will load flash it won't run flash and gives this error.

`ERR_INVALID_ARGUMENT`

**Comment by miniak** [comment]
@nornagon this is caused by sandboxed ppapi host process, that I had a PR for, but didn’t have time to land #18939

**Comment by amdbaz** [comment]
same problem happening to me electron v7.1.7 on windows 
flash does not work
any one still have this issue on 7+ version of electron?

**Comment by fp07** [comment]
https://github.com/electron/electron/issues/20744#issuecomment-569126188

Any workaround @miniak?

**Comment by fp07** [comment]
Fix?

**Comment by LukeTowers** [comment]
@fp07 @amdbaz @coreybruce did https://github.com/electron/electron/issues/20744#issuecomment-583061958 solve the issue for you in the latest version of Electron?

**Comment by ROBERT-MCDOWELL** [comment]
is it fixed?

**Comment by coreybruce** [comment]
Nope hasn't been fixed since the issue has existed but again I don't know if they will bother since Flash is dead and no longer supported, it wouldn't be a good idea to use flash anyways.

**Comment by ROBERT-MCDOWELL** [comment]
I need to run my old projects in flash, that's why I ask thanks.

**Comment by ROBERT-MCDOWELL** [comment]
btw it seems to be fixed since february 10th 2020
https://github.com/electron/electron/pull/22111/commits/a66156b8acdbf5cc80c92e140f67dc72db7e22e6

**Comment by coreybruce** [comment]
Oh well that's good if they did, I'd have to test it if I can even get a old of Flash to try lol

**Comment by EddieOne** [comment]
What was the fix?

**Comment by ROBERT-MCDOWELL** [comment]
sorry I still didn't fully test it, I just reported what said on the git issue.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
