### ISSUE TITLE
Use localstorage as a persistent storage mechanism

### ISSUE THREAD

**Issue by imolorhe** [electron/electron#20313]
Hello, I currently have an app built on electron that uses localStorage as the primary mechanism for storing persistent data. However I have gotten reports from some users about losing data after installing a new version of the app. I haven't been able to reproduce this however, as it is reported to happen at random sometimes, not always.

My question is, is it safe to use localStorage as a persistent storage mechanism in electron apps? Are there best practices to ensure the persistence of the data stored in localStorage across app builds?

**Comment by 0neGuyDev** [comment]
Personally I'd say in most cases it is fine, but I'd recommend making a file either text, json or something similar with all your settings and so on...

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
