### ISSUE TITLE
How to use other main.js in main process

### ISSUE THREAD

**Issue by aov2005** [electron/electron#20315]
- Electron version: 6.0.10
- Operating system: macOS 10.14.6

I have a app , it has a function to crawler, I use `spawn` to create a child process, and puppeteer control it

```javascript
spawn(app.getPath("exe"), [
    childMainJsPath,
    "--remote-debugging-port=4321"
  ])
```
and

```javascript
puppeteer.connect({
   browserURL: "http://localhost:4321"
})
```

That is works in `electron .`, but I run it when I use electron-builder build an app,  It spawn the parent process by parent's main.js. Is there a configuration item to change main.js?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
