### ISSUE TITLE
Can't seem to disable auxclick

### ISSUE THREAD

**Issue by freddy-daniel** [electron/electron#20318]
Re-opening [10315](https://github.com/electron/electron/issues/10315)

Electron version: 1.6.11
Operating system: Windows 10
Expected behavior
I create a window with these options: webPreferences: { disableBlinkFeatures: "Auxclick" }.
I point the window to an html page that has a link: <a href="http://www.google.com">GOOGLE</a>, and I expect middle clicking to not open up a new window.

Actual behavior
Middle clicking opens a new window.

Am I just not understanding what disabling auxclick does? Does disabling it also disable middle click in the hosted webapp? I couldn't confirm that either - see more details here.

It's Monday, 23 September 2019 still there's no feasible solution
tried with electron v6.0.9 too . same result, is there any solution

**Comment by MarshallOfSound** [comment]
That issue has extensive discussion, ways to disable auxclick and ways to prevent new windows popping up.  I just verified the information in https://github.com/electron/electron/issues/10315#issuecomment-392940023 on both v6 and v7 beta and can confirm that everything there is accurate.

Please don't "re-open" old issues (we can do that if the discussion leads to that) 😄 

Closing out as the original solution to the linked issue is still valid (preventing the `new-window` event)
