### ISSUE TITLE
Why webContents.print() in V7.0@beta is more slower than V6.0/V5.0 ?

### ISSUE THREAD

**Issue by zjee** [electron/electron#20316]
OS: windows 10 x64
ELECTRON VISION: v6.0.10  vs v7.0.0-beta.4 

the v7.0 Added a selection of new printing customization options [#18984 ](https://github.com/electron/electron/pull/18984) 

but in my tests  webContents.print() in V7.0@beta is more slower than V6.0

the part of code  

 `let printWindow = new BrowserWindow({ show: false });
  printWindow.loadURL("https://www.google.com");
  printWindow.webContents.on("did-finish-load", function() {
    printWindow.webContents.print(
      {
        deviceName: "Microsoft Print to PDF",
        silent: true,
        printBackground: false,
        copies: 1
      },
      success => {
        if (success) {
          console.log("Print job was succesfull!");
        } else {
          console.log("Print job was not succesfull )-;");
        }
        printWindow.destroy();
        console.log("Printing finished.");
      }
    );`
 
[](url)

![20190923122904](https://user-images.githubusercontent.com/43081961/65401984-22fdc980-ddfe-11e9-881b-4e57d2c76baa.png)

**Comment by codebytere** [comment]
This is a corollary of Chromium's changing print implementation. There's not much to be done on the Electron side, unfortunately.

**Comment by chenyungcs** [comment]
electron 9.0.0 is normal
