### ISSUE TITLE
Electron v6.0.10 with webpack-dev-server redirects after a few seconds to file:// protocol.

### ISSUE THREAD

**Issue by carlblock** [electron/electron#20321]
### Issue Details

* **Electron Version: **
  * v6.0.10
* **Operating System:**
  * macOS 10.14.5
* **Last Known Working Electron version:**
  * 

### Expected Behavior

Expected behaviour is that electron stays on the http protocol and doesn't initiate a request for the file protocol.

### Actual Behavior
To speed up development I'm running a webpack-dev-server at `http://0.0.0.0:8000`, it all works fine in the browser. However when running in electron with `mainWindow.loadURL('http://0.0.0.0:8000')` the page loads fine and displays for about 4 seconds. Then something initiates a load to `/app/index.html` with the file protocol instead of http. I have inspected the sockjs requests and payloads of webpack-dev-server but nothing states a reload or redirect of the page.

```js
devServer: {
    index: 'http://0.0.0.0:8000/index.html',
    compress: true,
    historyApiFallback: true,
    hot: false,
    headers: { 'Access-Control-Allow-Origin': '*' },
    open: true,
    overlay: false,
    host: '0.0.0.0',
    port: 8000,
    inline: true,
    clientLogLevel: 'debug',
    disableHostCheck: true,
    watchOptions: {
      aggregateTimeout: 300,
      ignored: /node_modules/,
      poll: 100
    },
    stats: {
      normal: true
    }
  }
```

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>MyApp</title>
</head>
<body>
<div id="app"></div> <!-- bootstrapped by vuejs -->
</body>
</html>
```

### To Reproduce

I'm running a minimal app compiled by webpack. Only the frontend is compiled by webpack, the renderer(index.js) is untouched. If necessary I'll upload an example later.

### Screenshots

![Screenshot 2019-09-23 at 12 35 44](https://user-images.githubusercontent.com/5603121/65419382-cfd84680-ddfe-11e9-8d50-3d765c5b5cf0.png)

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

This seems to squarely fit in the "webpack-dev-server is doing a thing I don't expect" rather than an Electron bug

**Comment by carlblock** [comment]
Hey @MarshallOfSound you were right it's not electron causing this issue. I nailed it down to being capacitor splash screen from ionic causing this redirect after 4500ms. I'm attaching a link to the opened issue in their repo in case somebody has the same issue in the future.

https://github.com/ionic-team/capacitor/issues/2011
