### ISSUE TITLE
setPosition() has a bug!

### ISSUE THREAD

**Issue by jianghaiqun** [electron/electron#20320]
### Issue Details

* **Electron Version:**
  * 6.0.9

* **Operating System:**
  * windowns 10(1809)
* **Last Known Working Electron version:**
  * 

### Expected Behavior

问题描述见这里下面
Ref:#20252
Ref: #10862
### Actual Behavior

在放大的窗口中调用setPosition()，窗口会变大
### To Reproduce

checkout: https://github.com/jianghaiqun/electron-api-demos/commit/34b5cb87b6c0485ff205588a0b2ed16f8865f82b

### Screenshots
bug截图：

![image](https://user-images.githubusercontent.com/32890262/65418647-79373080-de2f-11e9-8e8d-bd2212276c0c.png)
window 10 显示配置：
![image](https://user-images.githubusercontent.com/32890262/65419071-70932a00-de30-11e9-959b-bafbf67e07dd.png)

### Additional Information

@jkleinsc , 您好，我大概修改了一下示例工程。您检出，在15寸1080p分辨率的笔记本电脑上运行，就能重现问题。如果不能重现，请检查显示配置.window10会默认设置 125% 缩放布局。

**Comment by sofianguy** [comment]
Please follow #10862 for updates
