### ISSUE TITLE
macOS transparent window flickers on mousemove or position change

### ISSUE THREAD

**Issue by floating** [electron/electron#20325]
### Issue Details

* Electron Version
  *  `5.x.x`, `6.x.x`, `7.0.0-beta.x`
* Operating System
  * `macOS 10.14.2`
* Last Known Working Electron version
  * `4.2.10`

### Expected Behavior
Window should not flicker when resized and repositioned.

### Actual Behavior
Window flickers when resized and repositioned, seems to be related to mouse move events.

### To Reproduce

**`git clone https://github.com/floating/electron-flicker`**
**`npm run v6`** -> Will install Electron v6 and start app

Move mouse around the black sidebar as the window is resized and repositioned, see window flicker.  This flicker also exists on Electron v5 **`npm run v5`** and Electron v7 **`npm run v7`**.

#### To see it working correctly:

**`npm run v4`** -> Will install Electron v4 and start app

Move mouse around the black sidebar as the window is resized and repositioned, see window no longer flickers.

### Related
https://github.com/electron/electron/issues/8127#issuecomment-518208027

**Comment by floating** [comment]
Likely related: https://github.com/electron/electron/issues/8127#issuecomment-518208027

**Comment by floating** [comment]
Hi everyone! We understand if this is lower priority than other bugs but would like communicate it is a blocking issue for us and likely any other app that needs to resize/reposition often. We'd love to upgrade to Electron v6 to fix other issues we have. Any updates to plan our development cycle around would be much appreciated. Thanks for your hard work!

**Comment by floating** [comment]
This flicker also seems to exist on all platforms, not just macOS

**Comment by itsthisjustin** [comment]
@sofianguy noticed some movement here. Any eta on a fix? Definitely a major issue for us.

**Comment by neekai** [comment]
we're experiencing this issue as well on version 4.1.1. Any update on the issue?
[electron-flicker.mov.zip](https://github.com/electron/electron/files/4037221/electron-flicker.mov.zip)

**Comment by nornagon** [comment]
Collected this into a fiddle for easy repro: https://gist.github.com/b9668056eacfe87ca50f4d2b8e82e19f

**Comment by itsthisjustin** [comment]
@nornagon Who do I have to pay to fast track a fix for this haha

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by bpasero** [comment]
I still see flickering running the https://gist.github.com/b9668056eacfe87ca50f4d2b8e82e19f with Electron 11.
