### ISSUE TITLE
Notification unresponsive after ~40s of inactivity

### ISSUE THREAD

**Issue by alexanderturinske** [electron/electron#20323]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.
Relates to: #20153, #11690, #12458, [eb#1604](https://github.com/electron-userland/electron-builder/issues/1604)
Documentation: https://electronjs.org/docs/api/notification#new-notificationoptions-experimental, which conflicts with https://electronjs.org/docs/tutorial/notifications a little

### Issue Details

* **Electron Version:**
  * v6.0.8
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
1. Open app
2. Click `Check for update` menu item
3. Update is found and starts downloading
4. On download Notification pops up giving option to restart and install new version
5. User waits ~40s because they were in the middle of something or whatever. Notification continues to show
6. User clicks on notification to restart app
    - EXPECTED: App restarts and installs the new version OR the notification disappears when it no longer will register actions
    - ACTUAL: Notification disappears and the app remains

### To Reproduce
```
// Pulled from Issue #1604
function ensureSafeQuitAndInstall() {
    app.removeAllListeners('window-all-closed');
    const browserWindows = BrowserWindow.getAllWindows();
    browserWindows.forEach(browserWindow => {
        browserWindow.removeAllListeners('close');
    });
    dialog.showErrorBox('Error', `no error, just closing`);
    autoUpdater.quitAndInstall();
}

/**
 * Shows the update available notification and restarts the app on acceptance
 * @returns {void} void
 */
autoUpdater.on('update-downloaded', () => {
    const notif = new Notification({
        title: 'Update Downloaded',
        body: 'Click to reload the application',
    });

    // Reload the app if clicked on
    notif.on('click', ev => {
        dialog.showErrorBox('Error', `no error, just clicked ${ev}`);
        try {
            ensureSafeQuitAndInstall();
        } catch (e) {
            dialog.showErrorBox('Error', `error: ${e}`);
        }
    });

    // Never called
    notif.on('close', ev => {
        dialog.showErrorBox('Error', `no error, closing action ${ev}`);
    });

    // Never called
    notif.on('error', err => {
        dialog.showErrorBox('Error', `error ${err}`);
    });

    notif.show();
});
```

### Workaround
Create a `setTimeout` that automatically closes the Notification after ~30s

**Comment by MarshallOfSound** [comment]
@alexanderturinske This is expected behavior, your `notif` object has been garbage collected (there is nothing retaining it?).  You can easily work around this by doing `global.notif = ` or otherwise holding a reference to the notification object till you are done with it

**Comment by alexanderturinske** [comment]
🤦‍♂ Ah, thank you. That is not a problem I encounter very often.

**Comment by Crazie-ash** [comment]
@alexanderturinske Have u found a way to set timeout for notifications? Guide me if u found one pls!

**Comment by alexanderturinske** [comment]
As discussed above, my issue was that my variable was being garbage collected, so I created a top-level variable to retain it as suggested.

```
// THIS IS THE CHANGE
// MAKE notif A TOP-LEVEL VARIABLE
let notif; 

// Pulled from Issue #1604
function ensureSafeQuitAndInstall() {
    app.removeAllListeners('window-all-closed');
    const browserWindows = BrowserWindow.getAllWindows();
    browserWindows.forEach(browserWindow => {
        browserWindow.removeAllListeners('close');
    });
    dialog.showErrorBox('Error', `no error, just closing`);
    autoUpdater.quitAndInstall();
}

/**
 * Shows the update available notification and restarts the app on acceptance
 * @returns {void} void
 */
autoUpdater.on('update-downloaded', () => {
    notif = new Notification({
        title: 'Update Downloaded',
        body: 'Click to reload the application',
    });

    // Reload the app if clicked on
    notif.on('click', ev => {
        dialog.showErrorBox('Error', `no error, just clicked ${ev}`);
        try {
            ensureSafeQuitAndInstall();
        } catch (e) {
            dialog.showErrorBox('Error', `error: ${e}`);
        }
    });

    // Never called
    notif.on('close', ev => {
        dialog.showErrorBox('Error', `no error, closing action ${ev}`);
    });

    // Never called
    notif.on('error', err => {
        dialog.showErrorBox('Error', `error ${err}`);
    });

    notif.show();
});
```
