### ISSUE TITLE
Renderer process can write file to disk using 'fs'? 

### ISSUE THREAD

**Issue by brucebrit** [electron/electron#20332]
Electron version 6 + angular 8

I have encountered a weird thing. I develop the GUI using angular 8 framework. Inside the angular component, I have import * as fs from 'fs' and  able to use it to write to my disk using fs.writeFileSync("D:/Meeting/a.txt","testing"), inside my angular component.

I thought render process (which run the angular component) should not be able to use the fs to write to file, and should be done by the main process.  Then why is that possible then?

**Comment by amn** [comment]
Do you use Node.js integration by setting `nodeIntegration` to `true` among the options when creating a `BrowserWindow`, for example? Renderer process *does* have access to the `fs` namespace, among other things, if Node.js integration is enabled.

**Comment by brucebrit** [comment]
> Do you use Node.js integration by setting `nodeIntegration` to `true` among the options when creating a `BrowserWindow`, for example? Renderer process _does_ have access to the `fs` API that Node.js defines, among other things, if Node.js integration is enabled. That's the point of integration.

Hi. Thanks for your reply.
I build my application on top of the framework downloaded from https://github.com/maximegris/angular-electron.   I observe that it did set nodeIntegration to true. Wau...something new I learn. Thanks for mentioning nodeIntegration, will read up on this for more detail

I originally use the 
ipcRenderer.on("blablabla", ...) method to trigger method on Main Process from the Renderer Process, which i find it very verbose. Look like with nodeIntegeration, there is no reason for me to use this original method.
