### ISSUE TITLE
It is not possible to cancel a Bluetooth.requestDevice if there are no available devices

### ISSUE THREAD

**Issue by emilwikstrom** [electron/electron#20331]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

Electron Version: 6.0.7
Operating System: macOS 10.13.6
(also verified on Windows 10)

### Expected Behavior
I expect to be able to abort Bluetooth scanning (initiated by calling requestDevice()) even if there are no scan results.

### Actual Behavior
Currently it is only possible to abort a scan by calling the callback provided by the webContents event 'select-bluetooth-device' (in the main process). However, if there are no scan results the callback is never called and there is no callback to use.

### To Reproduce
Start scanning by calling requestDevice() in an environment with no BLE devices (or with a filter that does not match any devices).

### Additional Information
One solution would be to trigger 'select-bluetooth-device' with an empty list immediately when requestDevice is called. This would be backwards compatible and have the least impact on the current API.

Personally, I would prefer if the callback was provided in some other way. It does not make sense of providing the callback repeatedly in the 'select-bluetooth-device' event as the callback usage is not related to an individual scan result but rather to the ongoing scanning process.

**Comment by codebytere** [comment]
Duplicate underlying issue as https://github.com/electron/electron/issues/19489
