### ISSUE TITLE
Calling hang() or crash() in browser window does not trigger unresponsive or crashed events

### ISSUE THREAD

**Issue by jocodev1** [electron/electron#20345]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.10 _(same result in 5.0.10)_
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior

I need to listen to when the window goes unresponsive or crashes, then restart the app. However, when I manually call `process.hang()` or `process.crash()` to test the events, I expect the event listeners I setup in `main.js` to be triggered.

### Actual Behavior

When I manually call `process.hang()` or `process.crash()`, the app goes unresponsive or crashes, but the events are not triggered.

### To Reproduce

_See forked repo:_  [jocodev1/electron-quick-start](https://github.com/jocodev1/electron-quick-start/tree/bug/notFiringCrashEvents)

```sh
$ git clone https://github.com/jocodev1/electron-quick-start.git -b bug/notFiringCrashEvents
$ npm i --no-optional
$ npm start
```

In window, run `process.hang()` or `process.crash()` from console. You should see console messages when each event should get triggered, but there are none.

### Screenshots

![browserwindow](https://user-images.githubusercontent.com/10883716/65631994-aa863c80-dfa6-11e9-8f48-53db79dc6d91.png)

![console](https://user-images.githubusercontent.com/10883716/65631999-ad812d00-dfa6-11e9-8eeb-1589e9c09063.png)

**Comment by fabiospampinato** [comment]
I can reproduce in v9.1.0 that the `unresponsive` event is never fired when calling `process.hang`. 

`renderer-process-crashed` is fired for me though.

**Comment by codebytere** [comment]
@fabiospampinato @jocodev1 this is actually somewhat intended behavior. More specifically, the `unresponsive` event is _not_ triggered in the event that a devtools window is open. If you run:

https://gist.github.com/af6dc1bbbcfe9b2f78f7e1e31f1afae2

run `process.hang()` in console, and click out of the console window, and wait ~20-30 secs, you'll see the listener fired as expected.

**Comment by fabiospampinato** [comment]
@codebytere that kind of works, but I have to wait for like 2 minutes and 30 seconds for the "unresponsive" event to be triggered, that sounds too high a timeout to me, if things are unresponsive for 2 minutes straight I might just cut the power out 😅 is there any way to customize this?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by Slapbox** [comment]
@codebytere is this still expected to work in v20.3.x with `contextIsolation` enabled? I've been waiting several minutes but the `'unresponsive'` listener doesn't fire.

**Comment by Slapbox** [comment]
I tried attaching to `win` and `win.webContents`, but neither seems to work.

**Comment by Slapbox** [comment]
@codebytere could you provide any guidance here? I've run into times when an app window becomes unresponsive in production and even then the `unresponsive` event doesn't seem to fire. I had the `main` process set to log to a file when that window became unresponsive, but nothing was logged.

Before that, in development, I'd tried all manner of methods to provoke it.

**Comment by Slapbox** [comment]
@MarshallOfSound could you comment on this? 

We have an intermittent bug related to a renderer going unresponsive or crashing but the built-in events to detect that don't seem to work at all in any version of Electron I've tried which makes debugging even harder.

Neither `unresponsive` nor `render-process-gone` ever fire in my testing on Ubuntu and on Windows 11 and it's quite troublesome.

**Comment by Slapbox** [comment]
This appears to finally be resolved in `25.x`.
