### ISSUE TITLE
Port within URL Pattern for onBeforeSendHeaders fails

### ISSUE THREAD

**Issue by donmahallem** [electron/electron#20347]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.10
* **Operating System:**
  * Windows
* **Last Known Working Electron version:**
  * Haven't tried any other version before

### Expected Behavior
 Should accept URL Pattern with a port inside it when using a Filter for session.webRequest.onBeforeSendHeaders(*,*). Valid patterns are listed on https://electronjs.org/docs/api/web-request and it mentions even wildcard as port as possible.

### Actual Behavior
Crashed with "Error: Invalid URL Pattern  \*://localhost:88/\* :Invalid Port.

### To Reproduce
```
const filter = {
            urls: [
                '*://localhost:88/*',
            ]
        }
        session.webRequest
            .onBeforeSendHeaders(filter, (details, callback) => {
                details.requestHeaders['Authorization'] = 'Bearer ' + this.secureToken
                callback({ requestHeaders: details.requestHeaders })
            })
```

### Additional Information

I am not entirly sure if this is an Electron or Chromium Issue as Electron does seem to use an URL Matcher from Chromium

**Comment by morteza-binary** [comment]
I have faced this issue after upgrading to `6.0.12`. Is there any plan to fix this issue?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
