### ISSUE TITLE
Building with Visual Studio 2019 fails (angle dependency)

### ISSUE THREAD

**Issue by jaimecbernardo** [electron/electron#20346]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.0.0-nightly.20190924
* **Operating System:**
  * Windows 10 (1803)

### Expected Behavior
Successful build of Electron on Visual Studio 2019.

### Actual Behavior
Fails with :
```
CXX obj/third_party/angle/libGLESv2/global_state.obj
FAILED: obj/third_party/angle/libGLESv2/global_state.obj

...

../../third_party/angle/src/libGLESv2/global_state.cpp(39,1): error: static_assert failed due to requirement 'std::is_trivially_constructible<std::atomic<std::mutex *>>::value' "global mutex is not trivially constructible"
static_assert(std::is_trivially_constructible<decltype(g_Mutex)>::value,
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

### To Reproduce

Follow the build instructions from: https://electronjs.org/docs/development/build-instructions-windows to build with Visual Studio Community Edition 2019. Fails for both the Debug and Release builds.

### Additional Information

Upstream bug report in angle: https://bugs.chromium.org/p/angleproject/issues/detail?id=3936
This doesn't affect upstream Chromium since it doesn't use MS STL (`use_custom_libcxx` = `true` for Chromium).
Reported the issue in order to track it.

**Comment by bviswanathan** [comment]
I am seeing the same problem too on Win 10 with VS 2019 Community Edition
