### ISSUE TITLE
systemPreferences.isDarkMode()  returns wrong value on macOS 10.15 Catalina

### ISSUE THREAD

**Issue by gaodeng** [electron/electron#20353]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v6.0.10
* **Operating System:**
  * macOS 10.15 Beta (19A546d)
* **Last Known Working Electron version:**
  * 

### Expected Behavior
systemPreferences.isDarkMode on macOS 10.15 Catalina should report whether it's in dark mode or not, even when set to Auto Mode (based on time of day).

### Actual Behavior
systemPreferences.isDarkMode() report  the macOS appearance setting that is currently applied to the application.

### To Reproduce
```js
systemPreferences.setAppLevelAppearance('dark')
systemPreferences.isDarkMode()
// always reporting to be true.
```

```js
systemPreferences.setAppLevelAppearance('light')
systemPreferences.isDarkMode()
// always reporting to be false.
```

**Comment by MarshallOfSound** [comment]
This is expected behavior and there is nothing we can do about it.  Catalina changed how dark mode is stored and now the only way to detect it is by checking the dark mode setting of your app.  If you force a dark mode setting for your app it will match that one.

Closing out as expected and unchangeable behavior
