### ISSUE TITLE
Terminating workers when `nodeIntegrationInWorker: true` leads to crash

### ISSUE THREAD

**Issue by marbemac** [electron/electron#20368]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.10
* **Operating System:**
  * macOS 10.14.4
* **Last Known Working Electron version:**
  * Unknown

### Expected Behavior

Terminating workers when `nodeIntegrationInWorker` is true should not result in a crash.

### Actual Behavior

Terminating workers when `nodeIntegrationInWorker` is true eventually results in a crash (happens randomly - sometimes after a single termination, sometimes after 20).

### To Reproduce

Reproduction: https://github.com/marbemac/electron-worker-crash

1. `git clone https://github.com/marbemac/electron-worker-crash`
2. `yarn`
3. `yarn start.crash`
4. Wait 1-10 seconds for the crash.

All the example does is create and terminate an empty worker on an interval.

`yarn start` starts the app with `nodeIntegrationInWorker: false`, demonstrating that things work fine when it is false.

**Comment by marbemac** [comment]
Quick update - checked with `8.0.0-beta.3` and the issue persists.

**Comment by daeteck** [comment]
In version 7.1.13 this issue persists. Is when the terminate function of the worker is called and is totally random.

**Comment by murrayju** [comment]
I'm seeing the same with electron `8.0.5` on linux, but only when the chrome developer tools are attached.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
