### ISSUE TITLE
Regression of recentDocuments Menu role on macOS

### ISSUE THREAD

**Issue by bigtimebuddy** [electron/electron#20364]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

Defining a menu item like this no longer works in v6 where prior versions worked correctly. In v6, the menu item shows up in the menu disabled and does not have a submenu.

```js
{
    label: 'Open Recent',
    role: 'recentDocuments',
    submenu: [
        { role: 'clearRecentDocuments' }
    ]
}
```

* **Electron Version:**
  * 6.0.10
* **Operating System:**
  * macOS 10.14.5 
* **Last Known Working Electron version:**
  * 5.0.11

### Expected Behavior

`Open Recent` menu item should be enabled and contain a submenu that is expandable.

### Actual Behavior

`Open Recent` menu item is disabled without a submenu.

### To Reproduce

Example, see `main.js` for the menu setup.

```sh
$ git clone git@github.com:bigtimebuddy/electron-recent-docs-bug.git -b master
$ npm install
$ npm start || electron .
```

### Screenshots

v6.x
![Screen Shot 2019-09-27 at 5 24 51 PM](https://user-images.githubusercontent.com/864393/65808808-ce36b780-e14b-11e9-9a51-b1877f66c9d1.png)

v5.x
![Screen Shot 2019-09-27 at 5 25 19 PM](https://user-images.githubusercontent.com/864393/65808811-d2fb6b80-e14b-11e9-9d71-3f37fe6b8fc3.png)

**Comment by codebytere** [comment]
Caused by https://github.com/electron/electron/pull/18626; looking into a fix now.

**Comment by bigtimebuddy** [comment]
Yeah! Thanks so much @codebytere for looking into this.

**Comment by bigtimebuddy** [comment]
cc @codebytere 

Could we reopen this @zcbenz? `recentDocuments` seems like it is still broken in 6.0.12. The menu items work (are now enabled) but the `recentDocuments` menu does not populate with files. I have updated the repo I provided above:

https://github.com/bigtimebuddy/electron-recent-docs-bug/commit/50f8adeb0b4b01240f56fc0ef5448c2260eec8b1

Here are some screenshots:

**v6.0.12**
![Screen Shot 2019-10-08 at 4 27 44 PM](https://user-images.githubusercontent.com/864393/66440652-9996eb80-e9e8-11e9-9517-b3651677b207.png)

**v5.0.11**
![Screen Shot 2019-10-08 at 4 27 19 PM](https://user-images.githubusercontent.com/864393/66440648-969bfb00-e9e8-11e9-8d3d-7422cfdf08b5.png)

**Comment by codebytere** [comment]
Could you open a new issue? i'll assign myself and look into it!
