### ISSUE TITLE
Out-of-the-box feature to set application level default font by user

### ISSUE THREAD

**Issue by pavangayakwad** [electron/electron#20365]
### Problem Description
Not many applications  built using Electron are offering font-selections as part of their standard user preference and this is a huge problem when the application development team choose the font that does not render properly on screen (specially on Windows machines). Currently user has application level zoom-in and zoom-out feature coming out-of-the box from electron. Similarly, it would be a great addition if font selection preference is also included in the same way. 

### Proposed Solution
Allow user to select font-name (NOT font size, font color), only the font name.

### Additional Information
This problem persist largely for Windows operating systems.

As you may notice in the below screenshot, the fonts are improperly anti-aliased and the display is not clean to the eyes specially for the applications that we use for long hours and there seems to be no proper way of handling this in electron till date.

![image](https://user-images.githubusercontent.com/1834890/65813093-0db5e000-e1ee-11e9-8843-d0fbabf36cce.png)

However, there are some fonts like "Arial", "Verdana" (on Windows 10) that can solve the above mentioned anti-aliasing problem and let user have control over setting their preferred font for better visibility.

**Comment by nornagon** [comment]
I don't think we'd consider add a user-facing UI for this. It seems like the correct approach would be to fix the text rendering bug.

Does this text rendering issue also happen with Chrome?

**Comment by pavangayakwad** [comment]
yes, the issue exist with Chrome too!

Electron is heavily dependent on chromium it seems and no one right approach have been successful in solving this problem till date (https://github.com/electron/electron/issues/6344). Time for electron to take some out-of-the-box or workaround steps now util the actual bug is fixed?
