### ISSUE TITLE
error and unhandledrejection events subscribed via the preload script EIC window do not fire

### ISSUE THREAD

**Issue by bughit** [electron/electron#20361]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.2.11 x86
  * 6.0.10 x86
* **Operating System:**
  * win7 sp1 x64

### Expected Behavior
all events subscribed via the preload EIC window should fire

### Actual Behavior
- in 4.2.11 the error event fires but unhandledrejection does not
- in 6.0.10 neither do

### To Reproduce
run the following app in 4.2.11 and 6.0.10

##### `index.js`
```js
'use strict';

const {app, BrowserWindow} = require('electron'),
      path = require('path');

let win;

app.on('ready', async () => {

  win = new BrowserWindow({
    width: 1440,
    height: 900,
    useContentSize: true,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      preload: path.join(__dirname, 'preload.js'),
    },
  });

  win.loadFile('index.html');

  win.webContents.on('console-message', (event, level, message, line, sourceId) => {
    console.log('renderer console.%s: %s', ['debug', 'info', 'warn', 'error'][level + 1], message);
  });

});
```

##### `preload.js`
```js
'use strict';

addEventListener('error', event => {
  console.log('preload eic_window.on_error');
});

addEventListener('unhandledrejection', event => {
  console.log('preload eic_window.on_unhandledrejection');
});
```

##### `index.html`
```html
<script>

  addEventListener('unhandledrejection', event => {
    console.log('content content_window.on_unhandledrejection');
    event.preventDefault();
  });

  addEventListener('error', event => {
    console.log('content content_window.on_error');
    event.preventDefault();
  });

</script>

<button onclick="throw new Error('synthetic unhandled error');">unhandled error</button><br>
<button onclick="Promise.reject(new Error('synthetic unhandled rejection'));">unhandled rejection</button>
```

**Comment by bughit** [comment]
trying some variations

adding listeners via the content window, works in 4.2.11 (both error and unhandledrejection fire) but not in 6.0.10 (neither does) 
```js
webFrame.executeJavaScript('window', contentWin => {

  contentWin.addEventListener('error', event => {
    console.log('preload content_window.on_error');
  });

  contentWin.addEventListener('unhandledrejection', event => {
    console.log('preload content_window.on_unhandledrejection');
  });

});
```

**Comment by bughit** [comment]
In 6.0 the code attaching the listeners has to run in the content js

```js
webFrame.executeJavaScript(
  `(${function() {
    
    addEventListener('error', event => {
      console.log('preload content_window.on_error');
    });

    addEventListener('unhandledrejection', event => {
      console.log('preload content_window.on_unhandledrejection');
    });

  }})`,
  fn => fn()
);
```

I suppose it can be argued since these events are specific to the js env, attaching via the eic window should not be expected to work. But why shouldn't it work via the content window `webFrame.executeJavaScript('window')`:

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
