### ISSUE TITLE
Screenshot/Capture whole webpage in BrowerView

### ISSUE THREAD

**Issue by virajkini** [electron/electron#20376]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
- 4.1.1
* **Operating System:**
- macOS 10.13.6

Currently, I have used electron BrowserView to render a webpage. Now to capture the screenshot of my webpage, I have done something like this : 

`electron.remote.BrowserView.fromId(1).webContents.capturePage(this.determineScreenShot(), function (image) {  })`

From above, I get the native image of current visible screen view. And not the entire scroll view of the webpage. Is there way to accomplish that ? The entire scroll view of the webpage as an image.

**Comment by virajkini** [comment]
or else can we do anything in desktopCapturer to capture whole webpage ?

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).

**Comment by miniak** [comment]
also you should use `electron.remote.getCurrentWebContents()`, hardcoding `BrowserView` id is a bad idea
