### ISSUE TITLE
mismatched node module

### ISSUE THREAD

**Issue by bruceauyeung** [electron/electron#20372]
electron v6.0.10 ships with node 12.4.0 and node module version is 73(which i think should be 72),  but according to https://nodejs.org/en/download/releases/,   node module version should be 72 while nodejs version is 12.x. mismatched mode module versions lead a problem: nodejs native modules compiled against nodejs 12.x installed in host machine are not compatible with electron v6.0.10

* **Electron Version:**
  * v6.0.10
* **Operating System:**
  * centos 7 x64 
* **Last Known Working Electron version:**
  * IIRC electron 3.x which ships node version 10.x and node module version is 64

### Expected Behavior
electron v6.0.10 ships with node 12.4.0 and node module version is 72

### Actual Behavior
electron v6.0.10 ships with node 12.4.0 and node module version is 73

~~~
process.versions
{
  node: '12.4.0',
  v8: '7.6.303.31-electron.0',
  uv: '1.29.1',
  zlib: '1.2.11',
  brotli: '1.0.7',
  ares: '1.15.0',
  modules: '73',
  nghttp2: '1.38.0',
  napi: '4',
  llhttp: '1.1.3',
  http_parser: '2.8.0',
  openssl: '1.1.0',
  icu: '64.2',
  unicode: '12.1',
  electron: '6.0.10',
  chrome: '76.0.3809.146'
}

~~~

**Comment by MarshallOfSound** [comment]
Nowdays electron is ABI incompatible with the matching node version.  As such we have our own node module versions.

See this registry for the values: https://github.com/nodejs/node/blob/master/doc/abi_version_registry.json

73 is the correct number

You have to build native modules specifically for electron: https://electronjs.org/docs/tutorial/using-native-node-modules
