### ISSUE TITLE
electron App doesn't work at startup windows 7

### ISSUE THREAD

**Issue by tijo123** [electron/electron#20375]
I have developed a desktop app with electron.
I have put setLoginItemSettings on  windows  startup windows , my app should start at start on windows. Some of my functionality is not working properly(Only login is working).

**Comment by Slapbox** [comment]
Works for me. It's not at all clear what the full issue you're facing is from what you've written.

**Comment by sofianguy** [comment]
@tijo123 please follow https://github.com/electron/electron/issues/20374 for updates. This is a duplicate issue.
