### ISSUE TITLE
CSS is wrong in "package" version

### ISSUE THREAD

**Issue by PCMACHero** [electron/electron#20373]
### Issue Details

* **Electron Version:**
  4.2.10
* **Operating System:**
 MacOS Mojave 10.14.6  
>
* **Last Known Working Electron version:**
  NA

### Expected Behavior
I expect the app to look the same after it has been packaged into an app

### Actual Behavior
Something is wrong CSS wise on packaged version. Some elements are squashed as if having zero height.

<!--

### Additional Information

The elements are all Material UI Sliders. Everything else appears correctly. To clarify, only in the packaged app version does the issue occur. It works fine whilst in yarn start mode

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
