### ISSUE TITLE
Electron crash when using `electron .` in macOS 10.14.6

### ISSUE THREAD

**Issue by YikaJ** [electron/electron#20371]
### Preflight Checklist

* [ x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v4.2.1
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron version:**
  * v4.2.1

### Expected Behavior
Execute `electron . ` can launch electron app.

### Actual Behavior
App crash without any manipulate. If I restart the mac system, it will be ok for a moment, but 
 the crash will still happen after that. 

### Screenshots
![image](https://user-images.githubusercontent.com/8725110/65830382-92355b00-e2e1-11e9-9cd5-ce54d8125325.png)

### Additional Information
It will happen both my macbook and my teammate's macbook, we all update the mac version to 10.14.6 . And the following message in the console maybe is the key of this problem.

```bash
[0929/173534.539582:WARNING:system_snapshot_mac.cc(42)] sysctlbyname kern.nx: No such file or directory (2)
```

**Comment by codebytere** [comment]
Unfortunately, without a repro we're unable to triage this. In running this version of Electron on this version of macOS, i've never seen a similar issue.

Please provide a standalone test that a tester could run to reproduce the issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by fabiospampinato** [comment]
I think I'm experiencing this issue on Electron 8.2.2 as well as 8.2.1, I'm running macOS 10.14.6.

Here there are a bunch of crash dumps: https://drive.google.com/file/d/1ckpywln8BYLH_P2o69AqV61l2OT3UT2H/view?usp=sharing

It happens sort of randomly whenever I deal with the file system, which is being watched by chokidar, sometimes I remove a watched file and the whole thing crashes.

**Comment by fabiospampinato** [comment]
My issue was actually this: https://github.com/electron/electron/issues/18397#issuecomment-613754729
