### ISSUE TITLE
silent print is not working in Linux machine 

### ISSUE THREAD

**Issue by pmansoorktr** [electron/electron#20379]
, tried to use stable version 6.0.10 and bet version 7.0.0-beta.5, but still not working ,the same code is working fine in windows
On further investigation it has also find that ,the same printing without any code change is working in version 3.1.10

**Comment by pmansoorktr** [comment]
My 
Code
const win = electron.remote.getGlobal('_BrowserWindow')
            const BrowserWindow = electron.remote.BrowserWindow;
            var child = new BrowserWindow({ parent: win, width: 200, height: 300, show: false })
let printer = printersInfo.filter(printer => printer.isDefault === true)[0];                
                child.webContents.print({ silent: true, printBackground: true ,deviceName: ''}, () => {//child.close();                    
                });
Thanks in advance

**Comment by stilettk** [comment]
Try to specify `deviceName` from your `printer` variable. We had this issue on linux, and explicitly setting `deviceName` did solve the issue.

**Comment by pmansoorktr** [comment]
The issue has been resolved with 11+ versions 
Thanks For electron
