### ISSUE TITLE
Electron 6 BrowserWindow Debugger freezes indefinitely, without apparent pattern

### ISSUE THREAD

**Issue by Slapbox** [electron/electron#20383]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

# Issue Details

* **Electron Version:** `6.0.10`
* **Operating System:** `Windows 7`
* **Last Known Working Electron version:** `4.1.5`

### Expected Behavior
Debugger does not bug out and freeze/eat CPU indefinitely

### Actual Behavior
Debugging innocuous and functional code that was debuggable in Electron 4 can lead to freezes that require destroying the BrowserWindow or restarting Electron entirely.

### To Reproduce
No idea :(

### Screenshots

![image](https://user-images.githubusercontent.com/6835891/65904339-4390cb00-e38c-11e9-8a70-9d0231dfb57c.png)

### Additional Information

I upgraded and setting breakpoints in working code that was previously debuggable in Electron 4 there are issues. There's been no changes to that code and the debugger worked fine in Electron 4. I've been working on new code and figured that the issue was caused by a bug in my newly written code until just now.

It will stop properly at the breakpoints (in a number of places in my code), and then CPU usage spikes and stays high, taking up 40-45% CPU on my dual core machine. It appears to respond, but if you resume or step ahead nothing happens. If you press Pause script execution, similarly nothing seems to happen except the UI updates. CPU usage remains the same throughout. This code also runs properly when not debugging and last time I ran it in React Native and debugged with React Native Debugger (based on Electron 1.8 I think?)

Hitting Ctrl+P, the quick nav feature comes up as expected, but there's no files there except the HTML file loaded. Any additional files no longer appear.

Electron 6 is based on Chromium 76, and on some machines Chrome 76 (and 77) shoots to using a full CPU core and doesn't stop until the process is ended. I wonder if perhaps I'm seeing the same thing here.

**Comment by Slapbox** [comment]
This is an increasingly serious issue for me. I'm having to restart browser windows 50 times a day now that I'm debugging some tough code and I've had to resort mostly to logging because the debugger freezes indefinitely when used in some areas, seemingly without any pattern.

**Comment by Slapbox** [comment]
In at least one case I've discovered that defining a function using `_.debounce` in a class constructor can create this issue. In my circumstance in React, moving it to `componentDidMount` resolved this issue, but as far as I'm aware this was never an issue in `Electron@4` and earlier.

Any thoughts? Is there something obvious here I'm unaware of?

**Comment by Slapbox** [comment]
I'm increasingly certain that the issue occurs when inspecting a function that handles a mouse/keyboard event. We're using `React`, which could be somehow implicated, but the issue began after upgrading Electron with no changes to `React` (version `16.9.0` and also with `16.10.0`)

**Comment by ruoxijiang** [comment]
I am also facing similar issue after upgrading from 3.x to 6.x
At certain part of the code, at seemingly random times, when the execution hits a breakpoint, the execution will not resume when you hit the "resume" button. 
Also, while the execution is halted, any of the "debugging feature", like inspecting scope variables will not work. 
I think the two screen shot best summarize the issue at hand.

Issue reproducible on:
Electron : 6.1.1 and 6.1.4
OS: Mac 10.15.1

![image](https://user-images.githubusercontent.com/9947688/69219930-dbea4580-0bae-11ea-9401-851908634371.png)
![image](https://user-images.githubusercontent.com/9947688/69219941-e1e02680-0bae-11ea-8bd6-9eb9b604b75f.png)

**Comment by Slapbox** [comment]
The worst part is the lack of a pattern to create a repro. I was just working on a version of our app that uses Electron 4 yesterday and had forgotten what debugging it supposed to be like until then. I'm constantly hesitant to actually set breakpoints in my project at this point. This issue _**absolutely did not exist**_ in Electron 4 and below.

The only real patterns I've found are that trying to debug things that happen in event handlers is an almost guarantee'd freeze. Debouncing with `lodash` seems to increase the likelihood a function will cause the issue, but this might be placebo. React lifecycle methods besides `render()` are also basically impossible to debug. `componentDidUpdate` seems to be a near 100% guaranteed freeze in my experience.

**Comment by Slapbox** [comment]
Wrapping an otherwise working function with a `setTimeout` provoked the issue in one issue I saw today. Still trying to nail down specifics of recreating.

**Comment by SSJ9899TDylan** [comment]
I don’t get this!

**Comment by m-brantheim** [comment]
I can confirm, I seem to get this problem only when I am debugging with Chrome and I pause on a breakpoint in code that is wrapped in a setTimeOut function.
Moving the code out of the SetTimeOut fixes the problem.

**Electron Version**: 6.0.3
**Operating System**: Windows 1

**Comment by m-brantheim** [comment]
On second thought, I do seem to get it as well outside of setTimeOut functions but it happens less often.

**Comment by Slapbox** [comment]
I've noticed basically any function that's an event handler freezes, and absolutely any and all code invoked via `ipc` freezes the application if inspected. ie, `WindowOne` sends to `main` which sends to `WindowTwo` - inspecting the function that runs in `WindowTwo` seems to be a 100% reliable way to create this bug, but I've not had time to make a stripped down repo to prove this.

@m-brantheim - would you happen to be using a preload script?

**Comment by Slapbox** [comment]
Inspecting a method invoked via `electron-redux` seems to cause the issue too, in line with my previous findings on `ipc` calls in general. `electron-redux` uses synchronous `IPC`.

**Comment by Slapbox** [comment]
This seems to be fixed in `7.1.8` and `7.1.9`

**Comment by m-brantheim** [comment]
> @m-brantheim - would you happen to be using a preload script?

Yes I have a preload script that is requiring a native node module and adding a variable to the window object to allow calls to me made into native code.

I have found a way to reproduce this error 100% of the time is this:

`import { useDrop } from "react-dnd"`

...
`const [{ canDrop, isOver }, drop] = useDrop({
    accept: [NativeTypes.FILE],
    drop(item) {
      folderBrowserStore.onIngestAsset(currentId, item.files)
    },
    collect: monitor => ({
      isOver: monitor.isOver(),
      canDrop: monitor.canDrop()
    })
  })`

If you set a breakpoint inside of the drop function and you drag and drop a file from the OS file system then it will always freeze.

This is using Electron version 8.1.1 this time, I tried changing versions but still get the same problem.

**Comment by m-brantheim** [comment]
I tried to remove the use of the preload script but I still get the same problem.

**Comment by Slapbox** [comment]
> I tried changing versions but still get the same problem.

@m-brantheim what was lowest version number you tried, if you know? I don't recall this being an issue in Electron 4, or at least, not on the same scale as now. Previously it was exceptionally rare.

**Comment by Slapbox** [comment]
This issue is a killer. I'd have to guess I've lost an entire week or more of productivity to it issue. I have no idea what information I could provide to assist with debugging. I really wish I did. If anyone has _any_ ideas, I'd appreciate them more than you could ever know.

**Comment by Slapbox** [comment]
I still can't repro this, but I can confirm it continues at least up to Electron@9.x.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
