### ISSUE TITLE
showOpenDialog: Selecting a folder crashes the app (Ubuntu 19.04)

### ISSUE THREAD

**Issue by ebuehrle** [electron/electron#20380]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v6.0.10
* **Operating System:**
  * Ubuntu 19.04 x64
* **Last Known Working Electron version:**
  * n.a.

### Expected Behavior
The app starts up and shows a file open dialog, allowing me to pick a file.

### Actual Behavior
The file open dialog shows up, but the app crashes as soon as I click on one of the directories in the left side bar, or when I right-click inside the window. Sometimes, the app crashes immediately upon opening the dialog.

### To Reproduce
$ git clone https://github.com/ebuehrle/electron-quick-start.git
$ cd electron-quick-start
$ npm install
$ npm start

### Screenshots
![Screenshot from 2019-09-30 17-59-50](https://user-images.githubusercontent.com/43623224/65895728-35eb3d80-e3ac-11e9-86aa-169c484d36fd.png)

### Additional Information
It works as expected on OSX El Capitan and macOS High Sierra.

**Comment by williamluke4** [comment]
@sofianguy I'm experiencing the same issue on **Ubuntu 19.04** using **Electron 7.1.5**

**Comment by Hitesh-bigscal** [comment]
@sofianguy  I also having the same issue in Ubuntu 19.04 as well as in Ubuntu 19.10

**Comment by Mpho-Kgosisejo** [comment]
Hello... did y'all get help on this or found a solution?

**Comment by mukulvaidya** [comment]
n

**Comment by ahmtcn123** [comment]
I have the same problem in 19.10

**Comment by victoralvesf** [comment]
I was having the same issue, but then i decided to make a test and run the script on the Ubuntu terminal (not inside VSCode) and surprisely works. It appears that the problem is with VSCode Terminal.

**Comment by bugzbrown** [comment]
> I was having the same issue, but then i decided to make a test and run the script on the Ubuntu terminal (not inside VSCode) and surprisely works. It appears that the problem is with VSCode Terminal.
> 
> **Electron:** 5.0.8
> **Ubuntu:** 19.10

Amazingly it's true... if you run your "npm run electron:serve"  from a normal terminal window, it works OK

**Comment by fabcotech** [comment]
I am on ubuntu 19.10, I can confirm that I have the same problem. I can also confirm that it comes from VS Code, @victoralvesf 's solution (outside VS Code) works.

**Comment by djweaver-dev** [comment]
Can confirm this is still an issue.  I'm on an arch linux build and I'm getting the `dialog.showOpenDialog` crash when running/debugging from vscode too.  Running directly from my own terminal works.  Could this be some kind of sandbox issue where the apps executed from within vscode dont have permissions?

**Comment by juanreynolds** [comment]
Just rolled back Ubuntu 20.04 to 18.04. Works perfect on 18.04 but crashes app on 20.04 during debug. If you can't debug you can't develop.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
