### ISSUE TITLE
Cannot load NAPI addons in Nightly Debug build

### ISSUE THREAD

**Issue by maierfelix** [electron/electron#20387]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
8.0.0-nightly.20190928
* **Operating System:**
Windows 10 Home 10.0.17763
* **Last Known Working Electron version:**
Unknown, though in Release build everything works fine

### Expected Behavior
The Napi module should get loaded correctly

### Actual Behavior
Requiring the addon gives: `Uncaught Error: A dynamic link library (DLL) initialization routine failed.` I have tried with different addons, none of them work.

### To Reproduce
Just following the build instructions:
````
gn gen out/Debug --args="import(\"//electron/build/args/debug.gn\")
ninja -C out/Debug electron
````

**Comment by MarshallOfSound** [comment]
Native modules do not work in debug/component builds.  Use a testing build or a release build
