### ISSUE TITLE
Support WM_URGENT notifications on Linux

### ISSUE THREAD

**Issue by kenpowers-signal** [electron/electron#20393]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Some window managers on Linux use the `WM_URGENT` hint to highlight which desktop the app triggering a notification is on.

### Proposed Solution

Support `WM_URGENT` and other notification hints, though I don't see this functionality clearly exposed in libnotify.

### Additional Information

https://github.com/signalapp/Signal-Desktop/issues/3643

**Comment by codebytere** [comment]
Hi, while we appreciate this enhancement request it's not something that our team will be able to implement in the near future.  it's not something that Chromium has implemented or that is reasonably implementable with any supported utility.

If you'd like to make a PR for this request we would welcome that but in the meantime I'm going to go ahead and close this.
