### ISSUE TITLE
Filter cookies by domain is not working in 7.0.0

### ISSUE THREAD

**Issue by btzsoft** [electron/electron#20392]
### Issue Details

* **Electron Version:**
  * 7.0.0-beta.5
* **Operating System:**
  * Windows
* **Last Known Working Electron version:**
  * 6

### Expected Behavior
```js
const filter = {
  domain: 'facebook.com'
}
const cookies = await webContents.session.cookies.get(filter) // will resolve with actual cookies
```

### Actual Behavior
```js
const filter = {
  domain: 'facebook.com',
  // url: 'https://facebook.com' - NOTE: filtering by url is working
}
const cookies = await webContents.session.cookies.get(filter) // is returning empty array
```

### To Reproduce
```js
const filter = {
  domain: 'facebook.com'
}
const cookies = await webContents.session.cookies.get(filter)
```

Filter by `domain` is returning empty array, but if I try to filter using `url` is returning the actual cookies.

Tested on all `7` beta versions.
On `6` filtering by domain was worked.

**Comment by codebytere** [comment]
cc @nornagon/@zcbenz this seems like a nw13n issue?

**Comment by btzsoft** [comment]
@codebytere when it's expected to have a new build which will include the fix? thx.
