### ISSUE TITLE
Electron 6 lag when adding to system accessibility on macos 10.14

### ISSUE THREAD

**Issue by Suertzz** [electron/electron#20394]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v6.0.10
* **Operating System:**
  * macOs Mojave 10.14.6

### Expected Behavior
A smooth application, like before adding to accessibility

### Actual Behavior
The application becomes very slow when I add it in System Preferences -> Security & Privacy -> Accessibility

### To Reproduce

$ git clone https://github.com/Suertzz/electron-lag && cd electron-lag
$ npm install electron-packager -g
#### Lets build the App  
$ electron-packager . --overwrite
#### Go to System Preferences -> Security & Privacy -> Accessibility -> Click on '+' add the .app (electron-lag/electron-lag-darwin-x64/electron-lag.app)

![Screenshot 2019-10-01 at 17 51 33](https://user-images.githubusercontent.com/10809975/65978580-3d761980-e474-11e9-9e2c-e0dd4becc1ca.png)

$ open electron-lag-darwin-x64/electron-lag.app

If you uncheck the application (in the system settings) and restart the App it becomes fluid again (u can click on "notification" on the tray menu to test)

### Additional screen
<img width="203" alt="Screenshot 2019-10-01 at 18 17 04" src="https://user-images.githubusercontent.com/10809975/65980625-d9555480-e477-11e9-9ad6-f6d9cff14202.png">

**Comment by codebytere** [comment]
This is not reproducible for myself or anyone else on the team, and as such i'm inclined to this this a  function of your machine or macOS and not a function of Electron itself. Should something change, we're potentially happy to revisit this.

**Comment by Suertzz** [comment]
> Same issue with Electron 9.2.1 on two different Macs. @Suertzz Did you find a solution ? MacOS Upgrade ?

I did not find a solution, I gave up, sorry :/

**Comment by gilsdav** [comment]
So sad 😢 
@Suertzz thank's for your answer.
