### ISSUE TITLE
Using mac-app-store-submission-guide with new macos Helper apps fails on store upload

### ISSUE THREAD

**Issue by stephendwolff** [electron/electron#20405]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.11
* **Operating System:**
  * macOS 10.14.6

### Expected Behavior

After creating an MAS build using electron-packager

```
$ electron-packager . --app-bundle-id=com.weareamplify.disconnect --app-category-type=public.app-category.lifestyle --overwrite --platform=mas --arch=x64 --icon=Icon.icns --prune=true --out=mas-builds
```

I can run the .app file created.

I produce an MAS installable package using the following guidelines:

 - https://github.com/electron/electron/blob/master/docs/tutorial/mac-app-store-submission-guide.md

and expect to be able to upload the package using 'Application Loader' (version bundled with XCode 9 - latest Application Loader available to me - no longer with XCode11). I have uploaded successfully a package produced with electron-packager and signed this way previously.

My entire script:

```
#!/bin/bash

# Name of your app.
APP="disconnect"
APP_FOLDER="/Users/stephen/Documents/Development/amplify/disconnected/mas-builds/disconnect-mas-x64"
# The path of your app to sign.
APP_PATH="$APP_FOLDER/disconnect.app"
# The path to the location you want to put the signed package.
RESULT_PATH="$APP_FOLDER/$APP.pkg"
# The name of certificates you requested.
APP_KEY="3rd Party Mac Developer Application: Louder Productions Limited (HKH4LU2D76)"
INSTALLER_KEY="3rd Party Mac Developer Installer: Louder Productions Limited (HKH4LU2D76)"
# The path of your plist files.
CHILD_PLIST="/Users/stephen/Documents/Development/amplify/disconnected/child.plist"
PARENT_PLIST="/Users/stephen/Documents/Development/amplify/disconnected/parent.plist"
LOGINHELPER_PLIST="/Users/stephen/Documents/Development/amplify/disconnected/loginhelper.plist"

FRAMEWORKS_PATH="$APP_PATH/Contents/Frameworks"

codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Electron Framework"
#codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Libraries/libEGL.dylib"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib"
#codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib"
#codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Libraries/libswiftshader_libEGL.dylib"
#codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Libraries/libswiftshader_libGLESv2.dylib"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper.app/Contents/MacOS/$APP Helper"
#codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (GPU).app/Contents/MacOS/$APP Helper (GPU)"
#codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (Plugin).app/Contents/MacOS/$APP Helper (Plugin)"
#codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (Renderer).app/Contents/MacOS/$APP Helper (Renderer)"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper.app/"
codesign -s "$APP_KEY" -f --entitlements "$LOGINHELPER_PLIST" "$APP_PATH/Contents/Library/LoginItems/$APP Login Helper.app/Contents/MacOS/$APP Login Helper"
codesign -s "$APP_KEY" -f --entitlements "$LOGINHELPER_PLIST" "$APP_PATH/Contents/Library/LoginItems/$APP Login Helper.app/"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$APP_PATH/Contents/MacOS/$APP"
codesign -s "$APP_KEY" -f --entitlements "$PARENT_PLIST" "$APP_PATH"

productbuild --component "$APP_PATH" /Applications --sign "$INSTALLER_KEY" "$RESULT_PATH"
```

### Actual Behavior

Uploading to Application Loader results in an error:

1 package(s) were not uploaded because they had problems:
	/var/folders/65/k0nskmxs255dms193m1zy95c0000gn/T/00AD8BF7-C2EE-4CF3-97E7-A4235DA86FD7/1480709017.itmsp - Error Messages:
		ERROR ITMS-90296: "App sandbox not enabled. The following executables must include the "com.apple.security.app-sandbox" entitlement with a Boolean value of true in the entitlements property list: [( "com.weareamplify.disconnect.pkg/Payload/disconnect.app/Contents/Frameworks/disconnect Helper (GPU).app/Contents/MacOS/disconnect Helper (GPU)", "com.weareamplify.disconnect.pkg/Payload/disconnect.app/Contents/Frameworks/disconnect Helper (Plugin).app/Contents/MacOS/disconnect Helper (Plugin)", "com.weareamplify.disconnect.pkg/Payload/disconnect.app/Contents/Frameworks/disconnect Helper (Renderer).app/Contents/MacOS/disconnect Helper (Renderer)", "com.weareamplify.disconnect.pkg/Payload/disconnect.app/Contents/MacOS/disconnect" )] Refer to App Sandbox page at https://developer.apple.com/devcenter/mac/app-sandbox/ for more information on sandboxing your app."

If i uncomment the codesign lines for the new Helper apps (GPU) (Plugin) and (Renderer), the app no longer runs, and instead errors

How can i ensure these new helper apps have the entitlements? is there something i can add to my script or files to my build?

### To Reproduce

Upload an electron mas application signed with the documented scripts (which previously worked where nothing else did for me!)

### Additional Information
I can see the new helper apps have been an issue for other packaging tools such as electron-osx-sign and electron-builder, but cannot see how it has been fixed by them

**Comment by codebytere** [comment]
cc @sethlu, you may have better answers to this?

**Comment by stephendwolff** [comment]
FYI I installed the last 5.x release of Electron, built my app and then signed as per the documentation. The app ran without crashing, and also the app didn't contain the Helper apps (probably obvious!)

**Comment by stephendwolff** [comment]
So, i found which entitlements Chrome gives to the helper apps, via:

https://chromium-review.googlesource.com/c/chromium/src/+/1627456
https://chromium-review.googlesource.com/c/chromium/src/+/1664834
https://chromium-review.googlesource.com/c/chromium/src/+/1664834/2/chrome/app/helper-plugin-entitlements.plist
https://chromium-review.googlesource.com/c/chromium/src/+/1664834/2/chrome/app/helper-renderer-entitlements.plist#1

I made a helper-gpu-entitlements.plist as well - with a sandbox entitlement (ie roughly same as documented child.plist, without the inherit).

The signed app then ran without crashing after being built with electron 6.0.11, however the screen remained white. I tried specifying a colour in the ``` new BrowserWindow({ backgroundColour: '#ff0000', ```etc, and the background colour showed up, but none of the rest of the app, so something else missing. I'll try file entitlements or see if there are any other likely required by one of these helper apps in order to render (ie network etc for CSS files)

**Comment by sethlu** [comment]
@codebytere @stephendwolff I'll take a look at this issue... 🤔
I think it may be something to do with the packaging toolchain & the signing set up. I just hacked an `electron@6.0.11` to run on Catalina (unsure if it will pass the app loader). Details to follow.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
