### ISSUE TITLE
Main process Notification doesn't show in the Action Center

### ISSUE THREAD

**Issue by nblthree** [electron/electron#20415]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
 6.0.10
* **Operating System:**
  Windows 10 

### Expected Behavior
After the notification show and hide (close) you should be able to find it inside the Action Center

### Actual Behavior
Action Center is empty

### To Reproduce

a simple 
```
if (Notification.isSupported()) {
     const notification = new Notification({
         title: 'The title',
         body: 'The body'
      });
      notification.show();
}
```

**Comment by mattschlosser** [comment]
Keep a global reference to your notification to prevent it from being garbage collected
```
let notificaton
if (Notification.isSupported()) {
     notification = new Notification({
         title: 'The title',
         body: 'The body'
      });
      notification.show();
}
```

**Comment by MarchWorks** [comment]
@mattschlosser doesn't work

**Comment by MarchWorks** [comment]
I would like to work on this. Can someone tell me which file should I look into?

**Comment by MarchWorks** [comment]
Maybe this is what is missing https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast-desktop-cpp-wrl#step-4-implement-the-activator

**Comment by fds2610** [comment]
tray.displayBalloon leaves unclicked notifications in the action-center in Windows 10. notification.show does not. 
just a hint.

**Comment by raksooo** [comment]
Can confirm that this is still an issue with Electron 9.0.5.

**Comment by dragonDScript** [comment]
Can confirm that this is till an issue with Electron 11.1.1 and 12.0.0 beta 12

**Comment by raksooo** [comment]
As far as I can tell this has been working since Electron 12. Could someone please verify this? I've tested it on Windows 11.
