### ISSUE TITLE
After app.quit() main process keeps running: sleeping thread in native module

### ISSUE THREAD

**Issue by o2genum** [electron/electron#20425]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.11
* **Operating System:**
  * Windows 10 1809 (Build 17763.737)
* **Last Known Working Electron version:**
  * None

### Expected Behavior
I'm coding a `WaitForProcessToExit(pid)` function in my native [node-winapi](https://github.com/o2genum/node-winapi/blob/master/src/addon.cc) module. In an `Napi::AsyncWorker` I call `WaitForSingleObject(process, INFINITE)`. That is, I wait for a process with a certain PID to terminate.

### Actual Behavior
The problem: if `app.quit()` gets called while `WaitForSingleObject()` is still waiting inside the native module, main electron process keeps running.

Similar stuff when I try `Sleep()` inside `Napi::AsyncWorker`

### To Reproduce
My demo repo https://github.com/o2genum/electron-native-sleep-hang-demo

1. Start e.g. notepad.exe
2. Paste its PID into `main.js`
3. `npm run start`
4. Close Electron Window - main process doesn't exit until you kill notepad.exe

### Additional Information
I suspect this might not be a actual bug.

Anyway,
- How to make Electron terminate the native module with a waiting thread?
- What does `app.quit()` do to the main process, apparently it doesn't just kill it?

**Comment by o2genum** [comment]
Not really a bug, but a behavior that is hard to avoid.

https://github.com/nodejs/help/issues/2218

**Comment by whudson** [comment]
This is definitely a bug. It still occurs in v14 and can cause hanged threads with high CPU usage.
