### ISSUE TITLE
 BrowserWindow dimensions and monitor with different DPI and > 100%

### ISSUE THREAD

**Issue by iconarocco** [electron/electron#20423]
electron: 5.0.11
 
  - if you move a BrowserWindow on a monitor with DPI > 100% you receive events resize because the width or the height of the browser change by 1 px

 - if you move a BrowserWindow to a monitor with different DPI and you check dimension during the move, you can see that, when getDisplayMatching detect the scaleFactor changed, it return a dimension scaled. Soon after, when Windows scale the browser the dimension are correct.

	For example:
	1296 x 779 DPI 1 on first monitor
	1038 x 624 DPI 1.25 when the BrowserWindow is between the 2 monitor but not scaled
	1297 x 780 DPI 1.25 when the BrowserWindow ha been scaled by Windows

**Comment by pushkin-** [comment]
this should probably be added to [this](https://github.com/electron/electron/issues/10862) issue, and may already be on it.

**Comment by sofianguy** [comment]
@iconarocco please follow https://github.com/electron/electron/issues/10862 for updates
