### ISSUE TITLE
Error in windows 7 start up (Electron setLoginItemSettings)

### ISSUE THREAD

**Issue by tijo123** [electron/electron#20434]
I have added setLoginItemSettings (main.js page) for loading on windows 7 start up.
But show pop up with errors message:

const appFolder = path.dirname(process.execPath)
//const updateExe = path.resolve(appFolder, '..', 'Update.exe')
const exeName = path.basename(process.execPath)

app.setLoginItemSettings({
openAtLogin: true,
//path: updateExe,
args: [
'--processStart', "${exeName}",
'--process-start-args', "--hidden"
]
})

* I have read the [Contributing Guidelines]
https://electronjs.org/docs/api/app#appsetloginitemsettingssettings-macos-windows
.

### Issue Details

* **Electron Version:**
  6.0.0
* **Operating System:**
   Windows 7

### Expected Behavior
Windows start up with load our electron application.

### Actual Behavior
Loading app with error message.

### Screenshots
![doc](https://user-images.githubusercontent.com/53806091/66249357-903f2200-e74f-11e9-88c0-50c548c02086.png)

**Comment by codebytere** [comment]
This is not an issue with Electron; it seems you've passed in your executable paths incorrectly. I would suggest verifying the location of said executable, since this does not seem to be login-item specific either.

**Comment by tijo123** [comment]
Hi 
I have used the below code for getting executable paths

 const exeName = path.basename(process.execPath)

**Then call**

app.setLoginItemSettings({
openAtLogin: true,
//path: updateExe,
args: [
'--processStart', "${exeName}",
'--process-start-args', "--hidden"
]
})

**Please guide me to clear the problem.**

**Comment by tijo123** [comment]
> This is not an issue with Electron; it seems you've passed in your executable paths incorrectly. I would suggest verifying the location of said executable, since this does not seem to be login-item specific either.

Hi
I have used the below code for getting executable paths

const exeName = path.basename(process.execPath)

Then call

app.setLoginItemSettings({
openAtLogin: true,
//path: updateExe,
args: [
'--processStart', "${exeName}",
'--process-start-args', "--hidden"
]
})

Please guide me to clear the problem.
