### ISSUE TITLE
getUserMedia throwing Not readable error for video stream from installed app

### ISSUE THREAD

**Issue by nagendraK6** [electron/electron#20449]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
I am trying to access camera with getUserMedia from electron bundled installed (dmg). Access the videostream with the following code is throwing DOM exception: NotReadable. Can't start the source.

navigator.getUserMedia = navigator.getUserMedia ||
                           navigator.webkitGetUserMedia ||
                           navigator.mozGetUserMedia;

  if (navigator.getUserMedia) {
     navigator.getUserMedia({ audio: true, video: true },
        function(stream) {
          console.log(stream);
        },
        function(err) {
           console.log("The following error occurred: " + err.name);
        }
     );
  } else {
     console.log("getUserMedia not supported");
  }

The above is throwing an exception when the video is true. It works fine if I set audio true and video false.

**The above code works fine when I put in my web browser console or running electron in dev mode (with localhost url)**

* **Electron Version:**
    "electron": "6.0.11",

  * 
* **Operating System:**
  Mac OS - Mojave - 10.14.6
* **Last Known Working Electron version:**
  * 

### Expected Behavior

getUserMedia with video = true should return the media stream
### Actual Behavior

Mediastream throws exception if video = true
### To Reproduce
Run this command in js console of installed electron app.

`navigator.getUserMedia = navigator.getUserMedia ||
                           navigator.webkitGetUserMedia ||
                           navigator.mozGetUserMedia;

  if (navigator.getUserMedia) {
     navigator.getUserMedia({ audio: true, video: true },
        function(stream) {
          console.log(stream);
        },
        function(err) {
           console.log("The following error occurred: " + err.name);
        }
     );
  } else {
     console.log("getUserMedia not supported");
  }`

Code links

$ git clone https://github.com/nagendraK6/electronwebstream
$ npm install
$ yarn build

then install the dmg from the dist/
open the install app and check the console log

the problem in this area
https://github.com/nagendraK6/electronwebstream/blob/master/src/App.js#L14

**Comment by nagendraK6** [comment]
Found the fix.
We need to add entitlement for the mac. As we are going to access camera.

I used following entitlement

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
    
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>

    
    <key>com.apple.security.device.camera</key>
    <true/>
    <key>com.apple.security.device.audio-input</key>
    <true/>
</dict>
</plist>

**Comment by ljbelenzo** [comment]
i have run the exact problem but i cant find any solution on windows,

**Comment by Ende93** [comment]
for develop, you can just use `terminal.app` to run start.
