### ISSUE TITLE
Difference between process.defaultApp and app.isPackaged

### ISSUE THREAD

**Issue by xmedeko** [electron/electron#20448]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
I've spent some time figuring out what's the difference between [`process.defaultApp`](https://electronjs.org/docs/api/process#processdefaultapp) and [`app.isPackaged`](https://electronjs.org/docs/api/app#appispackaged) see also my [SO question].(https://stackoverflow.com/questions/58179379/electron-difference-between-process-defaultapp-and-app-ispackaged/58180776#58180776). I know that `process.defaultApp` is accessible from the main thread only, and that it has values `undefined/true`, while the `app.isPackaged` is accessible always and has values `false/true`. And that `Boolean(process.defaultApp) == !app.isPackaged` usually.

1. Are there any cases, when both are thruthy or both are falsy?
2. But why is the implementation differ? If both flags are considered similar,  then I would expect `app.isPackaged` to be initialized from `process.defaultApp` or vice versa.

### Proposed Solution
Please, document the differences or similarities in `process.defaultApp` and `app.isPackaged`. E.g. a simple sentence like "this flag supersedes the other flag" or "this flag is equal to other flag" is enough to clarify a confusion. Thanks.

### Alternatives Considered
Change `app.isPackaged` - initialize it from `process.defaultApp` or vice versa.

### Additional Information
Also related to #12656 and #7714.

**Comment by codebytere** [comment]
`process.defaultApp` specifically only applies to apps which are opened via the default app, aka just running the `electron` executable. `app.isPackaged` has nothing to do with the default app, and is a per-app indication of whether or not the app is a packaged app. They don't directly relate to one another.

**Comment by xmedeko** [comment]
@codebytere thanks for the answer. You can see, from the discussion in #12656 and #7714 and from the [SO question](https://stackoverflow.com/questions/58179379/electron-difference-between-process-defaultapp-and-app-ispackaged/58180776#58180776) that many (maybe most) of users consider use these flags to distinguish dev and production (packaged) code and they (we) think these flags are interchangeable - the only differences are technical.

**So, this is "document please" request. Please, make the doc more clear. Thanks.**

Also, I do not know electron so in depth to see the differences from your answer. I.e. am not able to decide, which of them to use as a "dev code flag" for our app. I.e. what might be (practical) cases, when both are thruthy or both are falsy? Or at least, which of these flags do you recommend as "dev code" flag? Thank you.
