### ISSUE TITLE
Unable to install Electron version >=7: EPERM: operation not permitted

### ISSUE THREAD

**Issue by mubaidr** [electron/electron#20455]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * electron@7.0.0 (any version > 6)
* **Operating System:**
  * Windows 10 May 2019 Update
* **Last Known Working Electron version:**
  * electron@6.0.8 (in fact any version <= 6)

### Expected Behavior
Should download and install fine.

### Actual Behavior
Download fails with permission denied error. 

### To Reproduce
`npm install electron` on windows

### Screenshots
![Capture](https://user-images.githubusercontent.com/2222702/66298992-83cddd00-e8a7-11e9-8761-ae7abcecd089.PNG)
![Capture1](https://user-images.githubusercontent.com/2222702/66298993-84667380-e8a7-11e9-8b57-1d62e7b93f2e.PNG)

### Additional Information
I don't know. :( Looks like the download method changed in the newer version which somehow does not work for me. 

So far I have tried these options: 

- Disabled Windows defender
- Tried recreating temp folder
- Tried changing path of temp folder (even changed drive)
- Adding `everyone` to the security of the `temp` folder
- Updating npm
- Running CMD as Administrator
- Making sure that run `nodejs` always run as administrator

**Comment by mubaidr** [comment]
Update: 
- Uninstalled nodejs completely (remove all node and npm directories)
- Create & Login to a new Administrator account on windows
- Install latest nodejs

This error is still there. :(

**Comment by mahonecode** [comment]
Same problem here.

**Comment by PYGC** [comment]
Same problem here.

**Comment by PYGC** [comment]
```
PS D:\liuyunqing\project\JavaScript\WebStorm\6> npm i -D electron@latest

> electron@7.0.0 postinstall D:\liuyunqing\project\JavaScript\WebStorm\6\node_modules\electron
> node install.js

(node:18680) UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted, lstat 'C:\Users\liuyu\AppData\Local\Temp\electron-download-ZCtMMr\electron-v7.0.0-win32-x64.zip'
(node:18680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18680) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mubaidr** [comment]
BTW Besides `electron` package, other things like `chrome-driver`, `winCodeSign`, `nsis-resources` are downloading fine.

**Comment by daizhx** [comment]
same problem here,

**Comment by daizhx** [comment]
yes,now i have to install electron@6.1.3 instead

**Comment by mubaidr** [comment]
Update: during build, `electron-builder` is able to download (and use) `electron` package in the %appdata% directory but still not able to launch electron application. Should not electron install script use the cached download from this directory ?

**Comment by vortii** [comment]
Workaround:
1. start installer normally with `npm install electron`, installation fails with EPERM error, but creates `node_modules` folder
2. create folder `\dist` in `node_modules\electron`
3. download release package directly from https://github.com/electron/electron/releases
4. unzip release package to `node_modules\electron\dist`
5. create `path.txt` in `node_modules\electron` directory, add text: `electron.exe`

From this point it should work. If you re-run the installer the dist folder and path.txt will be deleted.

**Comment by dejirutek** [comment]
I had same problem,  but 
on my environment,
Remove line below from .npmrc
ELECTRON_MIRROR=https://npm.taobao.org/mirrors/electron/
will solve this problem.

**Comment by mubaidr** [comment]
^ There is no `ELECTRON_MIRROR` variable set in npm config. :(

**Comment by taoabc** [comment]
Same issue
But use v6, I can't add args --no-sandbox, which will cause the whole window become black, at some machine, not every time.
Now I can only use v5, 😭

**Comment by seppu** [comment]
> Workaround:
> 
> 1. start installer normally with `npm install electron`, installation fails with EPERM error, but creates `node_modules` folder
> 2. create folder `\dist` in `node_modules\electron`
> 3. download release package directly from https://github.com/electron/electron/releases
> 4. unzip release package to `node_modules\electron\dist`
> 5. create `path.txt` in `node_modules\electron` directory, add text: `electron.exe`
> 
> From this point it should work. If you re-run the installer the dist folder and path.txt will be deleted.

This worked for running the application but when I do `npm run make` it tries to access the Appdata\Local\Temp location again and throws the error. 

So any resolution for this issue??

**Comment by yunmin97** [comment]
same error like this:
(node:21640) UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted, lstat 'C:\Users\ADMINI~1\AppData\Local\Temp\electron-download-tfppVA\electron-v7.1.1-win32-x64.zip'

**Comment by hornpecom** [comment]
Same problem here.

**Comment by jiaodoushi13** [comment]
Same problem here.

**Comment by cp9ev** [comment]
Same problem here.

**Comment by AndreasWebdev** [comment]
Same problem here.

**Comment by thomasLechaptois** [comment]
what is your npm version? for electron 7.1 it should be nodejs 12.8.1 so npm 6.10.2

**Comment by youyinnn** [comment]
same here

**Comment by iloseall** [comment]
Same problem on my machine. (windows 10 , npm -v=>6.13.1 )
electron 6.1.4 is ok.

**Comment by Lyoko-Jeremie** [comment]
same here

**Comment by schroederen** [comment]
Had the same problem and did some debugging. @electron/get handles electron downloads starting from electron 7.

Turns out you need to set ELECTRON_GET_USE_PROXY. Then @electron/get uses global-agent as proxy lib. global-agent in turn uses the env variable GLOBAL_AGENT_HTTP_PROXY to determine the proxy address.

Setting both resolved the issue for me!

**Comment by mubaidr** [comment]
Going to try this! 👍

**Comment by qq5050595531** [comment]
Colleague fixed it by edit .\node_modules\@electron\get\dist\cjs\artifact-utils.js
line 38 :
```
function getArtifactRemoteURL(details) {
    var opts = details.mirrorOptions || {};
    var base = mirrorVar('mirror', opts, BASE_URL);
    if (details.version.includes('nightly')) {
        base = mirrorVar('nightly_mirror', opts, NIGHTLY_BASE_URL);
    }
    var path = mirrorVar('customDir', opts, details.version);
   // add this line	
   path = path.substr(1);
    var file = mirrorVar('customFilename', opts, getArtifactFileName(details));
    return "" + base + path + "/" + file;
}
```

**Comment by ganyanchuan1989** [comment]
> PS D:\liuyunqing\project\JavaScript\WebStorm\6> npm i -D electron@latest
> 
> > electron@7.0.0 postinstall D:\liuyunqing\project\JavaScript\WebStorm\6\node_modules\electron
> > node install.js
> 
> (node:18680) UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted, lstat 'C:\Users\liuyu\AppData\Local\Temp\electron-download-ZCtMMr\electron-v7.0.0-win32-x64.zip'
> (node:18680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:18680) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

fix for me : electron_mirror=https://cdn.npm.taobao.org/dist/electron/

**Comment by al123xiaaaa** [comment]
> Colleague fixed it by edit .\node_modules@electron\get\dist\cjs\artifact-utils.js
> line 38 :
> 
> ```
> function getArtifactRemoteURL(details) {
>     var opts = details.mirrorOptions || {};
>     var base = mirrorVar('mirror', opts, BASE_URL);
>     if (details.version.includes('nightly')) {
>         base = mirrorVar('nightly_mirror', opts, NIGHTLY_BASE_URL);
>     }
>     var path = mirrorVar('customDir', opts, details.version);
>    // add this line	
>    path = path.substr(1);
>     var file = mirrorVar('customFilename', opts, getArtifactFileName(details));
>     return "" + base + path + "/" + file;
> }
> ```

fixed for me

**Comment by hansmaad** [comment]
Was a coporate proxy problem here...
To fully configure the proxy do:
```
export ELECTRON_GET_USE_PROXY=1
export GLOBAL_AGENT_HTTP_PROXY=http://our.proxy.com/
export GLOBAL_AGENT_HTTPS_PROXY=http://our.proxy.com/
npm i -D electron
```
