### ISSUE TITLE
desktopCapture goes failed in case of "lock-screen".Throwing "sources.map is not a function at Desktopcapture.handlEmitOnCapture"

### ISSUE THREAD

**Issue by DhavalSinor** [electron/electron#20459]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
The screen capture event is calling in every 5 minutes by using the `setInterval` method and its working good in case of "unlock-screen" in window 10, however, when the window screen is locked(Window+L), the below exception has generated.

> sources.map is not a function at Desktopcapture.handlEmitOnCapture

* **Electron Version:**
  * v6.0.7
* **Operating System:**
  * 
Windows 10 Pro(1803)
* **Last Known Working Electron version:**
  * 

### Actual Behavior
`Desktopcapture.getSources(optinal,callback)` does not handle "lock-screen" nor handlling uncaughtException. Below exception is generating.
![image](https://user-images.githubusercontent.com/11939820/66304685-6b97a580-e91b-11e9-842a-c95ee67ba6fe.png)

### Expected Behavior 

`Desktopcapture.getSources(optinal,callback)` should handle "lock-screen" / handles uncaughtException. 

### To Reproduce
Step 1: Copy below code

const electron = require('electron');

const desktopCapturer = electron.desktopCapturer;
const remote = electron.remote;
const electronScreen = remote.screen;

const fs = require('fs');
const path = require('path');
const os = require('os');

var screenShotPath = '';

let getScreenCapture = function () {

    const timeoutScheduled = Date.now();
    const thumbSize = determineScreenshot();
    console.log(thumbSize.height);
    console.log(thumbSize.width);
    let options = { types: ['screen'], thumbnailSize: thumbSize };

    desktopCapturer.getSources(options, function (error, sources) {
        if (error) {
            console.log(error.message);
            return; 
        }
        sources.forEach(function (source) {
            screenShotPath = path.join(os.tmpdir, 'screenshot_' + timeoutScheduled + '.jpeg');
            console.log(screenShotPath);
            fs.writeFile(screenShotPath, source.thumbnail.toPNG(), function (err) {
                if (err) return console.log(err.message);

            });

        });

    });
}
setInterval(function () {
      getScreenCapture();
    console.log('Captured');
}, 5000);

function determineScreenshot() {
    const screensize = electronScreen.getPrimaryDisplay().workAreaSize;

    const maxDimension = Math.max(screensize.width, screensize.height);
    console.log(maxDimension);

    return {
        width: maxDimension * window.devicePixelRatio,
        height: maxDimension * window.devicePixelRatio
    };
}

Step 2: Install npm & run this code.

Step 3: Lock your window screen (Window + L). Lock your screen at least 10 minutes.

Step 4: Unlock your widow screen and see the Dialog box popups with the below error message.
  
![error](https://user-images.githubusercontent.com/11939820/66305518-18265700-e91d-11e9-8336-8dc91cca7136.jpg)

### Additional Information
Also other errors logs in the terminal 

 [19164:1007/163453.079:ERROR:dxgi_output_duplicator.cc(170)] Failed to capture frame, error 000001EB5A7F5380, code -2005270490
[19164:1007/163453.095:ERROR:screen_capturer_win_directx.cc(140)] DxgiDuplicatorController failed to capture desktop, error code Duplication failed
[19164:1007/163528.058:ERROR:dxgi_output_duplicator.cc(170)] Failed to capture frame, error 000001EB5A871850, code -2005270490
[19164:1007/163528.552:ERROR:screen_capturer_win_directx.cc(140)] DxgiDuplicatorController failed to capture desktop, error code Duplication failed
[19164:1007/163538.072:ERROR:dxgi_output_duplicator.cc(170)] Failed to capture frame, error 000001EB5A878A70, code -2005270490
[19164:1007/163538.077:ERROR:screen_capturer_win_directx.cc(140)] DxgiDuplicatorController failed to capture desktop, error code Duplication failed
[19164:1007/163543.058:ERROR:dxgi_output_duplicator.cc(170)] Failed to capture frame, error 000001EB5A878A70, code -2005270490
[19164:1007/163543.061:ERROR:screen_capturer_win_directx.cc(140)] DxgiDuplicatorController failed to capture desktop, error code Duplication failed
There was an uncaught error TypeError: sources.map is not a function
    at DesktopCapturer.handlEmitOnCapturer (~\node_modules\electron\dist\resources\electron.asar\browser\desktop-capturer.js:72:32)

**Comment by DhavalSinor** [comment]
Guys any idea on this?

**Comment by loc** [comment]
@DhavalSinor what is the expected behavior? Obviously it shouldn't throw an exception, but is it okay if the sources list comes back empty?

**Comment by DhavalSinor** [comment]
hi @loc  I have updated the expected behavior in outlined description.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
