### ISSUE TITLE
Update bandwidth limitation for webrtc streaming

### ISSUE THREAD

**Issue by masudhossain** [electron/electron#20467]
i want to update the SDP to change the bandwidth limitation on ElectronJS so we can get better performance on our webrtc app. I can't seem to find any docs that'll let me do this for electron. 

Example of how to update it on chrome/firefox: https://github.com/webrtc/samples/blob/gh-pages/src/content/peerconnection/bandwidth/js/main.js#L219

**Comment by MarshallOfSound** [comment]
In general, whatever technique works in Chromium should work in Electron too 👍

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
