### ISSUE TITLE
 webContents Event: 'crashed'

### ISSUE THREAD

**Issue by xiaoqufengdi** [electron/electron#20474]
I set a listener at Main process,  then execu process.crash()  on the console to simulated rendering process crash。But it doesn't work

`let mainWindow = null;
app.on("ready", ()=>{
    mainWindow = new BrowserWindow({
        width: 800, height: 500,
        webPreferences: {
            nodeIntegration: true
        }
    });
    mainWindow.webContents.openDevTools();
    mainWindow.loadURL(path.join("file:", __dirname, "index.html"));
   
    mainWindow.webContents.on('crashed', (event, killed) => {
        console.log("killed: "+killed);
        console.log("-----------");
        console.log(mainWindow.isDestroyed());
        const options = {
            type: 'error',
            title: '进程崩溃了',
            message: '这个进程已经崩溃.',
            buttons: ['重载', '退出'],
        };

        dialog.showMessageBox(options, (index) => {
            if (index === 0)
                reloadWindow(mainWindow);
            else
                app.quit();
        });

    });

    mainWindow.on("closed", ()=>{
        mainWindow = null;
    });
});`

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
