### ISSUE TITLE
How can i know that the mouse has entered window?

### ISSUE THREAD

**Issue by OctupleSakura** [electron/electron#20470]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
What do i want to do when the mouse entered the window with **“-webkit-app-region: drag”** attribute , then i find if i try to add the **“-webkit-app-region: drag”** attribute，the element invalidates all mouse event，include **mouseenter** and **mouseleave**

I understand that the click event related to dragging, but why are events other same also failed

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
