### ISSUE TITLE
v7 install faile 

### ISSUE THREAD

**Issue by qiuyanlong** [electron/electron#20479]
**Issue Details**

**Electron Version:**
electron@7.0.0-beta.3

**Operating System:**
macos 10.14.6 (18G87)

**Last Known Working Electron version:**
electron@6.0.5 is success
Expected Behavior
electron@7.0.0-beta.3 should install fine.

**Actual Behavior**
electron@7.0.0-beta.3 fails to install

**To Reproduce**
Try installing electron@7.0.0-beta.3 on macos.

**Additional Information**
`> electron@7.0.0-beta.5 postinstall /Users/tal/WorkSpace/electron-quick-start/node_modules/electron
> node install.js

(node:96828) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
    at EventEmitter.emitter.on.response (/Users/tal/WorkSpace/electron-quick-start/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (events.js:198:13)
    at module.exports (/Users/tal/WorkSpace/electron-quick-start/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/Users/tal/WorkSpace/electron-quick-start/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:203:15)
    at ClientRequest.origin.emit.args [as emit] (/Users/tal/WorkSpace/electron-quick-start/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
(node:96828) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:96828) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
added 878 packages from 413 contributors and audited 10351 packages in 26.245s
found 0 vulnerabilities`

**Comment by qiuyanlong** [comment]
@bkeepers @probablycorey ^_^

**Comment by qiuyanlong** [comment]
__* ^ * _ omg

**Comment by qiuyanlong** [comment]
oop~~

**Comment by qiuyanlong** [comment]
~~

**Comment by MarshallOfSound** [comment]
@qiuyanlong I've tested on a few machines and can't repro this, my guess is you're using a download mirror and v7 is not on that mirror yet

**Comment by MeteorKL** [comment]
@qiuyanlong same error with you.

Here is my configuration for npm.

```
$ npm config list
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.9.0 node/v10.16.3 darwin x64"

; node bin location = /Users/xuliang/.nvm/versions/node/v10.16.3/bin/node
; cwd = /Users/xuliang/repos/repos_nes/nes-emulator-desktop
; HOME = /Users/xuliang
; "npm config ls -l" to show all defaults.
```

**Comment by echosalik** [comment]
I am having this same error. On Windows.

**Comment by aretw0** [comment]
I'm having this same error. On Raspberry Pi 3+.

**Comment by neauoire** [comment]
[Same error](https://github.com/hundredrabbits/Orca/issues/158) on the pi.

**Comment by algakzru** [comment]
Same error on macOS Mojave 10.14.6

**Comment by qiuyanlong** [comment]
you can re-npm install until success!!!   i madeit

**Comment by fytriht** [comment]
Same error on v7.1.7

**Comment by BobCromwell** [comment]
I met the same error on Mac.  as @MarshallOfSound suggested, I  remove the [registery] setting in my .npmrc and restart terminal get it works.

**Comment by schmorrison** [comment]
Check this, haven't checked this across machines yet:

https://github.com/electron/electron/issues/21353
