### ISSUE TITLE
systemPreferences.askForMediaAccess leads to app crash

### ISSUE THREAD

**Issue by Nodarii** [electron/electron#20498]
### Issue Details

* **Electron Version:**
  * 6.0.12
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron version:**
  *  unknown

### Expected Behavior
User should be prompted to grant microphone access.

### Actual Behavior
Application crashes

### To Reproduce
electron-forge scaffold with minimal changes to reproduce this issue - 
https://github.com/Nodarii/not-working-media-access

**To see crash:**
- git clone git@github.com:Nodarii/not-working-media-access.git
- npm i
- npm start

**To see working build:**
- git clone git@github.com:Nodarii/not-working-media-access.git
- npm i
- npm make
- run application from `out` folder

### Additional Information
related issue: 
https://github.com/electron/electron/issues/19307
related stackoverflow question: 
https://stackoverflow.com/questions/58290668/electron-osx-systempreferences-askformediaaccess-crashes-app

**Comment by Nodarii** [comment]
Ok so I found root cause. 
I was running application from webstorm terminal.
It works just as expected if I run it from regular terminal.

Looks like permissions were granted to webstorm instead of electron helper app

**Comment by Nodarii** [comment]
Not sure if this issue is related to electron itself. I guess this one might be closed. 
But it might be helpful for other people who might face the same issue

**Comment by APshenkin** [comment]
Face the same issue for electron 7.x on macOS Catalina. running in any terminal doesn't fix an issue.

**Comment by codebytere** [comment]
The app has crashed because it has a hardened runtime and attempted to access privacy-sensitive data without an entitlement indicating its intent to access this data.

The app must have the 'com.apple.security.device.audio-input' entitlement. Once you add this to your plist, the error will stop happening.

**Comment by 2xAA** [comment]
This still seems to be an issue.

Even with the correct entitlements I can't run an Electron app which calls `systemPreferences.askForMediaAcess` in development mode from VSCode's integrated terminal, though it will launch fine through iTerm or Terminal.
