### ISSUE TITLE
Please document the limiation of weview tag

### ISSUE THREAD

**Issue by chemzqm** [electron/electron#20492]
It takes lots of time to fight with buggy webview in electron, I suppose to document the issues with webview.

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

There're many issues with current webview tag in electron, including:

* Not possible to serve devtools web contents.
* Not possible to enable touch events, although it's possible to enable touch events by use command line switch, still not possible to trigger touch events.

### Proposed Solution

Document them in docs until they're fixed.

### Alternatives Considered

`BrowserView` can work as expected for display devtools contents and enable touch events, but has it's own issues, including:

* They always rendered above current window, which could make popups hard to use.
* You can't use z-index to control order of them like webview.
* You can't use css for position the window, but have to use `setBounds`.
* You have to manually remove them on window refresh.

### Additional Information

https://github.com/electron/electron/issues/14095

**Comment by MarshallOfSound** [comment]
The first thing in our docs is a warning to consider not using webviews

https://electronjs.org/docs/api/webview-tag#warning

This PR https://github.com/electron/electron/pull/20478 also adds some more information around different ways to embed content in electron

**Comment by chemzqm** [comment]
Ok, I've found some other issues with `BrowserView` on electron 6.0.11, it's not possible to inject script like webview, `setBackgroundColor` method doesn't work at all.  It sucks.

**Comment by chemzqm** [comment]
@MarshallOfSound but `BrowserView` still have lots of issues.
