### ISSUE TITLE
AutoUpdater not updating

### ISSUE THREAD

**Issue by stevenroussey-desiclabs** [electron/electron#20491]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  * v6.0.11
* **Operating System:**
  * macOS 10.14.6

### Expected Behavior
App gets updated. 

### Actual Behavior
No update and no error

### Area of Need
I am having a hard time debugging the issue, since it is on a packaged app, and it takes a while to sign and notarize. Looking at the code, it seems like there is a logger, but looking at the typescript definitions, it looks like there is no api to set it. Even skipping TS and trying to set logger directly, it seems to do nothing. 

So, how does one debug the autoUpdater?

### Related Issue
https://github.com/electron-userland/electron-builder/issues/4300

**Comment by stevenroussey-desiclabs** [comment]
This does not work, and I don't see any docs for it.

```
import {autoUpdater } from 'electron';
autoUpdater.logger = logger;
```

I do see in the code things like `this._logger.info(`Install on explicit quitAndInstall`);` But I never see those messages (even when bypassing the setter and setting _logger explicitly

**Comment by MarshallOfSound** [comment]
Electron builder's auto updater is not Electron's built in one.  It is home spun custom logic that we can not support 👍 You should raise issues on Electron Builders issue tracker

**Comment by stevenroussey-desiclabs** [comment]
Well, for most that is true but then it hands off to the native one and that’s where the issue is.

**Comment by stevenroussey-desiclabs** [comment]
https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/MacUpdater.ts : 

```
export class MacUpdater extends AppUpdater {
  private readonly nativeUpdater: AutoUpdater = require("electron").autoUpdater
...
quitAndInstall(): void {
    this.nativeUpdater.quitAndInstall()
  }
}
```

My issue is in quitAndInstall which simply links to Electron's quitAndInstall, and thus I am here trying to find a way to debug the issue I am having.

**Comment by stevenroussey-desiclabs** [comment]
https://github.com/electron/electron/blob/master/shell/browser/auto_updater_mac.mm#L165 it looks like `relaunchToInstallUpdate` which leads to https://github.com/Squirrel/Squirrel.Mac/blob/b5ce589c4ca5d61388f555a8fd4a7705a114e427/Squirrel/SQRLUpdater.m#L737

**Comment by stevenroussey-desiclabs** [comment]
I installed XCode, attached to my process, and created a symbolic breakpoint for `relaunchToInstallUpdate`. Indeed it stops, but it is all assembly. :(
