### ISSUE TITLE
angular-electron webview not loading all functionalities of website

### ISSUE THREAD

**Issue by vamsideepak** [electron/electron#20499]
I am trying to use webview element in my angular 7 in electron desktop application. For the first time website was loaded successfully but after login into the website remaining functionalities are not working. Website is developed using thymeleaf.

I tried like below:
`
<webview id="mainwebview" nodeintegration='on' src="https://tarc-uat.gfcp.io/"
  style=" width:100%; height:calc(100vh - 11vw)"  partition="persist:sitesession" disablewebsecurity="on" webpreferences="allowRunningInsecureContent" >
</webview>`

and Script:
**onload = () => {
    const webv = document.getElementById('mainwebview')
    window.addEventListener('load', () => {
      webv.addEventListener('dom-ready', () => {
      });
    })
  }**

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
