### ISSUE TITLE
Devtools: Source-mapped React Typescript files lose coloring 

### ISSUE THREAD

**Issue by deepakanand** [electron/electron#20504]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.12 
* **Operating System:**
  * Windows 10 Pro (1903)
* **Last Known Working Electron version:**
  * 3.1.8

### Expected Behavior
React Typescript component source code is  displayed with the similar coloring as other TypeScript and JavaScript sources

### Actual Behavior
React Typescript component source code is  displayed without any coloring

### To Reproduce
1. Implement a simple React component in TypeScript
2. Name the file with the extension *.tsx
3. Build it with webpack source-map and open Electron devtools. It looks similar to the screenshot below

### Screenshots
![image](https://user-images.githubusercontent.com/4721866/66494701-17f59b00-ea86-11e9-96db-78aff0ccfba0.png)

**Comment by MarshallOfSound** [comment]
I've seen the same thing happen in Chrome, the syntax highlighting in devtools is quite flaky sometimes and in this case, apparently just doesn't work 🤷‍♂ 

This code is outside of Electrons scope though, if you can repro in Chrome consistently I'd raise upstream

**Comment by deepakanand** [comment]
Thanks for looking at this. But its not flaky at all for me (and i checked with some of my team-mates), we consistently see this in Electron `6.x` and not at all in `3.x`
I hoped this would be investigated a little before closing it

**Comment by aprilandjan** [comment]
@demopark after bump electron version from `v4.x` into `v7.x` and then `v8.4.1` at last, the syntax highlighting is finally correct
