### ISSUE TITLE
Regression of recentDocuments file list on macOS

### ISSUE THREAD

**Issue by bigtimebuddy** [electron/electron#20503]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.12
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron version:**
  * 5.0.11

### Expected Behavior

Using `app.addRecentDocument`, should add files to the `recentDocuments` menu.

### Actual Behavior

The files are missing from the `recentDocuments` menu (the files, however, show up correctly when right-clicking on the dock icon--assuming that `addRecentDocument` works fine).

* `recentDocuments` seems like it is still broken in 6.0.12. The menu items work (are now enabled) but the `recentDocuments` menu does not populate with files.

### To Reproduce

```sh
$ git clone git@github.com:bigtimebuddy/electron-recent-docs-bug.git -b master
$ npm install
$ npm start || electron .
```

### Screenshots

**v6.0.12**
![Screen Shot 2019-10-08 at 4 27 44 PM](https://user-images.githubusercontent.com/864393/66440652-9996eb80-e9e8-11e9-9517-b3651677b207.png)

**v5.0.11**
![Screen Shot 2019-10-08 at 4 27 19 PM](https://user-images.githubusercontent.com/864393/66440648-969bfb00-e9e8-11e9-8d3d-7422cfdf08b5.png)

### Additional Information

Follow up to #20364 & #20398

cc @codebytere

**Comment by bigtimebuddy** [comment]
I'm currently still being blocked by this regression.

**Comment by codebytere** [comment]
It's on my backlog, but it's a fairly complex issue. We used to use a xib file but then removed it unaware that it would cause this. Chromium has removed their use of xib files so we can't trivially add it back and will now need to manually implement the backing logic. I'll do my best in the next few weeks :)

**Comment by bigtimebuddy** [comment]
Thank you for the update, makes sense. I appreciate your help.

**Comment by codebytere** [comment]
@bigtimebuddy heyo, i carved out an hour today and actually pulled together a PR for this. I've verified it's working as intended and said PR should be up shortly. Thanks for being patient and sticking with me on this!

**Comment by bigtimebuddy** [comment]
@codebytere AMAZING & THANK YOU!

**Comment by bigtimebuddy** [comment]
@codebytere I'm not sure if the manual merging of your fix (3176e323e41f097fedc2bb7110a10bf48482dbe8) to 6.1.x got messed up, but this is still an issue with 6.1.3. However, it works as expected with 7.0.1.

**Comment by codebytere** [comment]
@bigtimebuddy nope, it's that the actual backport is still in the works unfortunately! i'm on it and should have it sorted soon though.

Backport: https://github.com/electron/electron/pull/20885

**Comment by bigtimebuddy** [comment]
Oh, my bad! Thanks for handling this.
