### ISSUE TITLE
Screenshot prevention similar to confide windows app?

### ISSUE THREAD

**Issue by NvVijayakumara** [electron/electron#20501]
Hi, 

how do I prevent taking screenshot of my app by other screen recording / capturing tools?
I came to know one application [confide](https://getconfide.com/) which is built with electron js, is able to prevent screen capture.

Thanks..

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

**Comment by miniak** [comment]
https://electronjs.org/docs/api/browser-window#winsetcontentprotectionenable-macos-windows
