### ISSUE TITLE
Flashing menus on linux

### ISSUE THREAD

**Issue by user414** [electron/electron#20520]
### Preflight Checklist

* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v7.0.0-beta.6
* **Operating System:**
  *  Ubuntu 18.04 LTS x64 
* **Last Known Working Electron version:**
Would have to dig in deeper as this started in one of the version of VS Code but unknown at this time exactly which and to which version of electron it maps. 

### Expected Behavior
Menu not flashing when switching

### Actual Behavior
Menu flashes when switching between menus

### To Reproduce

As described in this VS Code issue https://github.com/microsoft/vscode/issues/76850

**Comment by codeforcesmeme** [comment]
@sofianguy  I'm facing this issue when I installed the latest vscode-insiders 1.43-insider (Electron 7.1.11) but not in the stable 1.42.1 (Electron 6.1.7)
I'm also facing the problem with Slack "Production 4.3.2 64-bit" not sure what's their Electron version

**Comment by GitFiend** [comment]
This is fixed for me in GitFiend after updating it to use electron 8.1.1. Still had the issue in 8.0. Tested on Ubuntu 18.04 with a dark theme and dark menus.

**Comment by codeforcesmeme** [comment]
This is fixed in all electron apps for me slack, vscode and discord on Linux

**Comment by user414** [comment]
@codeforcesmeme Can you share your vscode version? Was trying it with the latest publicly available release to see if it was fixed and still the problem is there for me on vscode

Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:44:48.716Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0

**Comment by user414** [comment]
Just read the original thread in the vscode forum and people are saying it is fixed in the insider build 1.51, so tried that one as well and it is still there for me on Ubuntu 18.04.5 LTS 

Version: 1.51.0-insider
Commit: 49696e87c64f478f97909a91d41ff2913df9bf71
Date: 2020-10-31T00:11:14.623Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
