### ISSUE TITLE
BrowserWindow: minHeight/minWidth broken on mixed DPI monitors on Windows in Electron 6.0.6

### ISSUE THREAD

**Issue by ToadKing** [electron/electron#20527]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.6, 6.0.12
* **Operating System:**
  * Microsoft Windows [Version 10.0.18362.418]
* **Last Known Working Electron version:**
  * 6.0.5

### Expected Behavior
minHeight/minWidth is the same value on all monitors

### Actual Behavior
minHeight/minWidth are much larger in size on lower DPI monitors

### To Reproduce
Sample app: https://github.com/ToadKing/dpi-bug

To reproduce, you must have multiple monitors on Windows with different DPI levels. The primary monitor on your desktop should be a high DPI one, while a secondary monitor should be lower DPI.

### Screenshots
High DPI primary monitor:
![image](https://user-images.githubusercontent.com/1023440/66600023-3765f400-eb6a-11e9-9af8-565ad652012f.png)

Lower DPI secondary monitor (stretches off the monitor):
![image](https://user-images.githubusercontent.com/1023440/66600069-4e0c4b00-eb6a-11e9-97f6-c4fc13c57e7b.png)

### Additional Information
The behavior works in 6.0.5, but is broken in 6.0.6. Might be #19928/#20001 or the Chromium upgrade?

**Comment by smildlzj** [comment]
+1

**Comment by sgd2z** [comment]
This might be related: https://github.com/electron/electron/issues/20683
