### ISSUE TITLE
how to play sound in electron

### ISSUE THREAD

**Issue by M956588010** [electron/electron#20541]
well,this is a little question.I had found the answer all day.
I don't know how to play sound in electron app.I tried use new Audio() to play sound,but the error is Audio() is not defined.
I search it in Google,some of the answers is to do it in render process with Web Audio API,my colleague don't allow me to do it.
So I want to know how to play sound in main process.(I have tried to use other node package,but it doesn't work)
Please help me.I am just a rookie.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
