### ISSUE TITLE
shell.openItem no longer lets you choose from a list of applications on Windows 10 1903

### ISSUE THREAD

**Issue by MRayermannMSFT** [electron/electron#20543]
# Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
When using `shell.OpenItem` to open a file whose extension does not have a default app, a list of programs should appear that allow the user to choose what program to use. Starting with Windows 10 1903 this is no longer the case. Instead, an error appears:
![image](https://user-images.githubusercontent.com/21112697/66675395-1957cc80-ec1a-11e9-9000-b51b1fab95c3.png)

* **Electron Version:**
4.2.5 and 6.0.12
* **Operating System:**
Windows 10 1903
* **Last Known Working Electron version:**
4.2.5 on Windows 10 1809

### Expected Behavior
A list of programs should appear:
![image](https://user-images.githubusercontent.com/21112697/66675491-486e3e00-ec1a-11e9-8b91-d37d8ea81ab9.png)

### Actual Behavior
An error appeared (see above screenshot).

### To Reproduce

1. Be on Windows 10 1903
2. Clone my electron quick start: https://github.com/MRayermannMSFT/electron-quick-start
3. Switch to the openItemIssue branch
4. `npm install`
5. `npm start`
6. Click the button

### Screenshots
See above.

### Additional Information
I understand that this might be a Windows or Chromium specific issue, so no worries on that. Just wanted to get the conversation going somewhere and this felt like as good a place as any. 😄

**Comment by MarshallOfSound** [comment]
Being a windows bug I suggest you raise this with the Windows Feedback tool and let them deal with it.  We're using the right API so this is on Windows to fix afaics
