### ISSUE TITLE
Thumbnail Toolbar button object does not execute click() function

### ISSUE THREAD

**Issue by timburgess** [electron/electron#20556]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.0.0-beta.6
* **Operating System:**
  * Windows 10 (1903)
* **Last Known Working Electron version:**
  * unknown

### Expected Behavior
An example for the use of Thumbnail Toolbar button(s) is at https://github.com/electron/electron/blob/master/docs/tutorial/windows-taskbar.md#thumbnail-toolbars. The API at https://electronjs.org/docs/api/structures/thumbar-button is consistent with the example code. 

`setThumbarButtons` is being used as below:
```
  if (platform === 'win32') {
    const addedBtn = mainWindow.setThumbarButtons([
      {
        tooltip: 'Mario',
        icon: path.join(__dirname, 'img/mario.jpg'),
        click() {
          console.log('mario clicked')
        },
      },
    ])
    console.log('added thumbar btn', addedBtn)
  }
```

`Added thumbar btn` should appear in the terminal. It does and the thumbnail is visible when hovering over the icon. On hovering over the app icon in the toolbar, the button is shown. On clicking the button, the button object's click() function should be called and a console.log output visible.
### Actual Behavior
Clicking on the button, there is no apparent execution of the button objects click() function, so no console.log output in the example code

### To Reproduce
```
git clone https://github.com/timburgess/electron-todos
yarn
yarn run electron
```

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
