### ISSUE TITLE
Web Workers Bug ( Not worker_threads )

### ISSUE THREAD

**Issue by Inomezi** [electron/electron#20555]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
6.0.11
6.0.12
v7.0.0-beta.6
* **Operating System:**
 MacOs Mojave Version 10.14.5

### Expected Behavior
Hi, I need to create a multi-threaded application. I using web workers, but them don't work correctly https://electronjs.org/docs/tutorial/multithreading

### Actual Behavior
When i used `web workers` I ran into a threads creation limit. I can create max 240-243 threads, but when i add 1 more thread - it crash. I have free 7 GB RAM, but it crush anyway. Btw, in activity monitor it'll show x2 threads count, than i created. If i created 240 threads - it'll show 480+ threads in activity monitor

### To Reproduce
For reproduce `web workers` error:
`
for( let i = 0 ; i < 250 ; i ++ ) {
  new Worker("./src/workers/profile.js") // need provide a path to file
} // 240 = no crush, 250 will crush
`

### Screenshots
`Web workers`

This screenshot shows that were created x2 threads, than I actually create (as I described above).  Were created 240 threads, but in fact 486 is displayed
![image](https://user-images.githubusercontent.com/24946599/66699513-378ffc00-ecf0-11e9-8c63-4760b39160c1.png)

This screenshot shows what happens when I add one thread, after creating 240 web workers
![image](https://user-images.githubusercontent.com/24946599/66699533-6b6b2180-ecf0-11e9-9b93-5e505664cf66.png)

### Additional Information
If i can provide more info for you - tell me please !

**Comment by Inomezi** [comment]
Hi again, it my first issue sorry, but will you it fix ? My project frozen for 1 week because of this errors, and idk wait or no. Thank you.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
