### ISSUE TITLE
Display text when hovering over the tray icon (windows)

### ISSUE THREAD

**Issue by MarchWorks** [electron/electron#20552]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

I would like to display some dynamic app data when hovering over the tray icon
### Proposed Solution

N/A
### Alternatives Considered

N/A
### Additional Information

![Sans titre](https://user-images.githubusercontent.com/40798653/66705259-3674c400-ed1c-11e9-90bd-85f41114bdd1.jpg)

**Comment by MarshallOfSound** [comment]
https://electronjs.org/docs/api/tray#traysettooltiptooltip

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
