### ISSUE TITLE
Problem trying to swap the Iotex to IotexE tokens

### ISSUE THREAD

**Issue by MicaelG** [electron/electron#20554]
I had a problem trying to swap the Iotex to IotexE tokens. I tried a few times and none was successful, then I looked at the Txid and realized that the contract for which this exchange is configured is incorrect and tried to do the iopay wallet manually and got it, and due to unsuccessful attempts using the iotex geeks wallet My funds are pending txid and I am unable to trade my currencies.
![iotex issue](https://user-images.githubusercontent.com/51017035/66714890-20561a80-ed93-11e9-9995-9960443688a4.JPG)
![iotex issue 2](https://user-images.githubusercontent.com/51017035/66714891-20561a80-ed93-11e9-9313-5aabc92177f4.JPG)
![iotex issue 3](https://user-images.githubusercontent.com/51017035/66714892-20561a80-ed93-11e9-9bdd-97b4fcb8cc18.JPG)
![iotex issue 4](https://user-images.githubusercontent.com/51017035/66714893-20561a80-ed93-11e9-8291-b846d57f9614.JPG)

**Comment by codebytere** [comment]
This is not an issue with Electron; please report this to the app itself.
