### ISSUE TITLE
Return value of function provided from renderer thread to main thread via the remote object is not transferred as function result when called

### ISSUE THREAD

**Issue by christian-judt** [electron/electron#20562]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.12 (and probably all previous versions starting with the creation of the remote object)
* **Operating System:**
  * Windows 7 (and probably all other operation systems since this is verly likely an internal electron problem)
* **Last Known Working Electron version:**
  * none I guess

### Expected Behavior
Any reference to a result returning function existing at a renderer thread provided to the main thread via the remote object of this renderer thread results in a promise returning function at the main thread which synchronously returns promises that resolve with the corresponding result of the corresponding function call at the corresponding renderer thread independently of whether the renderer thread function returns this promise synchronously as a return value or asynchronously as a promise.

### Actual Behavior
Any reference to a result returning function existing at a renderer thread provided to the main thread via the remote object of this renderer thread results in a function at the main thread which always returns the value "undefined". (Which would be ok for a "remote-to-main" RPC function callback argument, but certainly not ok for "main-to-remote" RPC function transferred from the renderer thread to the main thread via the arguments of a "remote-to-main" RPC function)

### To Reproduce
```
git clone -b functions-provided-from-renderer-to-main-fail-to-deliver-result-bug https://github.com/christian-judt/electron-quick-start.git
cd electron-quick-start
npm install
npm start
```

### Additional Information
* The "undefined" returning function generated at the main thread for the corresponding function at the renderer thread is the one created into the variable "callIntoRenderer" around line 222 in the file "/lib/browser/rpc-server.js". (Electron Branch "7-0-x")
* The communication of result values of this kind of "main-to-renderer" RPC function basically works, but only when providing an explicit callback argument at the main thread, which then is explicitly called with the result as argument at the renderer thread instead of simply returning the result as the return value of the RPC function. (this workaround is implemented in the "To Reproduce" example above as well)

**Comment by MarshallOfSound** [comment]
This is expected behavior and a limitation of both the remote module and sync IPC in Electron.  It's impossible to make a blocking call from main->renderer therefore it's impossible to get that return value

**Comment by christian-judt** [comment]
> 
> 
> This is expected behavior and a limitation of both the remote module and sync IPC in Electron. It's impossible to make a blocking call from main->renderer therefore it's impossible to get that return value

What about async IPC? Like using callbacks like I was doing to get a result from the renderer thread to the main thread in the example. Just a standard solution inside the remote module instead of some workaround outside. Then "main-to-renderer" RPCs would always return a pending promise (since no blocking is possible in this direction) that would later resolve with the result of the renderer function independent of whether the renderer function later provides this result via returning the result itself or a promise that will eventually resolve with the result.
