### ISSUE TITLE
Want the data traffic generated by web pages to be transmitted through the render process

### ISSUE THREAD

**Issue by KinoriN** [electron/electron#20579]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

I try to open many players by create a browserWindow and loadURL, but I find that all of the data traffic are  transmitted throught the  main process and it could produce some problem on load videos.
### Proposed Solution

the data traffic could transer throught the render process

**Comment by MarshallOfSound** [comment]
This is fundamentally how Chromium is designed.  It is out of the scope of this project to manipulate that
