### ISSUE TITLE
Ubuntu and smart cards authentication - Windows and Mac working perfectly

### ISSUE THREAD

**Issue by avvRobertoAlma** [electron/electron#20575]
### Preflight Checklist

* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.3.0
* **Operating System:**
  * Ubuntu 18.04
* **Last Known Working Electron version:**
  * 

### Expected Behavior
I need authentication using smart-card certificates.
On windows i have no problem, certificates are loaded into windows store
On mac i have no problem, certificates are visible in the keychain (system certificate store of Apple Mac os)

On ubuntu, i executed this command:
`modutil -dbdir sql:.pki/nssdb/ -add "OpenSC" -libfile /usr/lib/$(uname -i)-*/opensc-pkcs11.so`
chrome and chromium can access to certificates and i can log in to reserved areas.
The electron app, however, does not access to these certificates.

The event `select-client-certificate` is never fired on ubuntu.

**Comment by sofianguy** [comment]
@avvRobertoAlma after [Oct 22](https://electronjs.org/docs/tutorial/electron-timelines), when we release electron v7, we will no longer supporting versions older than v5. Does this bug happen on a later version of electron?

**Comment by avvRobertoAlma** [comment]
I'll try tonight with electron v5 and v6 and i will return to you. Anyway, on ubuntu version electron app should use certificates stored in nssdb or there should be something different ?

**Comment by avvRobertoAlma** [comment]
Hi @sofianguy i updated electron to 6.0.12. 
The situation hasn't improved:
- on Mac Os X and Windows, i am able to fetch regularly data from the public API;
- on Ubuntu, i still get a 401 (as you can see in developer tools' image
![401Electron](https://user-images.githubusercontent.com/25185257/66958057-b4f89b00-f067-11e9-8505-00f324ec2fd0.png)
)

Anyway on the same system i am able to access with Chrome/Chromium to a similar website (which also require strong authentication with smartcard), as you can see in the attached screenshot i am requested for the PIN and to select a certificate
![requestPinChrome](https://user-images.githubusercontent.com/25185257/66958164-e6716680-f067-11e9-8fe5-bdf8982b2296.png)
![selectCertificateChrome](https://user-images.githubusercontent.com/25185257/66958173-ea9d8400-f067-11e9-9693-b76cefb4e3b8.png)

I don't know how to solve this issue. Can you provide me with some advice ?
Given the fact that on Win/Mac OS everything works fine, maybe I did not make any mistake, but on linux i have no idea in order solve this issue.

**Comment by avvRobertoAlma** [comment]
Update. This issue still occurs with last electron version (8.3.0)

**Comment by Ramanujam1983** [comment]
Hi,

We are also facing the same problem with electron based browser for smart card authentication by executing the following command:
modutil -dbdir sql:$HOME/.pki/nssdb/ -add "OpenSC PKCS#11 Module" -libfile /usr/lib/$(uname -i)-linux-gnu/opensc-pkcs11.so

We have called modutil -dbdir sql:$HOME/.pki/nssdb/ -list to list the modules and it is listing "OpenSC PKCS#11 Module" along with the opensc-pkcs11.so correctly.

We have refereed the following links:
https://wiki.archlinux.org/index.php/Electronic_identification
https://wiki.ubuntu-it.org/Hardware/Periferiche/CartaNazionaleServizi

Also there is a stackoverflow issue https://stackoverflow.com/questions/58396067/electron-app-and-https-ssl-authentication-with-smart-cards-pcks11

Kindly help us to use the smart card based authentication with electron browser.

We are using electron browser to authenticate the AD FS and SAML with Microsoft Azure. In the same environment, Chrome and FireFox works.

Regards,
Ramanujam

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by cgagner** [comment]
I believe this issue is still valid in the latest version(s) of Electron. Additionally, I believe other Linux distributions are affected. I've created a new issue https://github.com/electron/electron/issues/32668 since this issue has been closed.
