### ISSUE TITLE
Download links from Windchill don't work (Probably not just a Windchill related issue)

### ISSUE THREAD

**Issue by coldspark29** [electron/electron#20582]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version: v5.0.10**

* **Operating System: Windows 10 (17134)**

* **Last Known Working Electron version:**

### Expected Behavior

I expected the file to be downloaded, as it does when I click the link in Chrome.

### Actual Behavior

Nothing happened.

### To Reproduce

Get access to a Windchill account and try to download a document via Electron.

### Additional Information

The download link is from an application called Windchill, which is a production environment management system. It provides download links for documents, which are not a direct link to the document. In the browser you get redirected a few times until the download dialog occurs. The Windchill account is connected to the Windows user account. It is possible to navigate through Windchill within Electron, but as soon as you try to download a document nothing happens.

**Comment by HaNdTriX** [comment]
No Bug afaik. 

fyi: https://www.npmjs.com/package/electron-dl

**Comment by codebytere** [comment]
This is not a bug in Electron itself - in agreement with the above you should be using a download handler to accomplish your goal.
