### ISSUE TITLE
DesktopCapturer returns stream with black background and mouse cursor alone when requesting stream for entire screen in fedora

### ISSUE THREAD

**Issue by soundar78** [electron/electron#20580]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.11
* **Operating System:**
  * Fedora 30
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
The "window" and "screen" stream must return proper video stream of the selected entity.

### Actual Behavior
The "screen" stream is black with only the cursor but the "window" stream seems to provide proper video of the selected window.

### To Reproduce
main.js
```
const { app, BrowserWindow } = require('electron')

function createWindow () {
// Create the browser window.
let win = new BrowserWindow({
width: 800,
height: 600,
webPreferences: {
nodeIntegration: true
}
})

// and load the index.html of the app.
win.loadURL('http://localhost:8000/index.html')
}

app.on('ready', createWindow);
```

index.html
```
<style>

div {
	margin-right: 5px; 
}
</style>
<div id="parent">
	
</div>
<script>
var electron = require('electron');
var desktopCapturer = electron.desktopCapturer;
var parent = document.getElementById('parent');
desktopCapturer.getSources({ types: ['window', 'screen'] } , function(error, sources)
    {
    if(error)
    {
    throw error
    }
    
   for(const source of sources )
   {
   		const stream =  navigator.mediaDevices.getUserMedia({
          audio: false,
          video: {
            mandatory: {
              chromeMediaSource: 'desktop',
              chromeMediaSourceId: source.id,
              minWidth: 500,
              maxWidth: 500,
              minHeight: 500,
              maxHeight: 500
            }
          }
        })
	stream.then( function(a) { 
		
		var container = document.createElement('div');
		var vidElem = document.createElement('video');
		var divElem = document.createElement('div');
		divElem.innerText = source.id;
		vidElem.id = source.id;
		container.append( vidElem );
		container.append( divElem );
		container.style = "display:inline-block;"
		parent.append(container);
		vidElem.srcObject = a; 
		vidElem.play();
	}).catch( function(err) {
		console.log(err);
	});
   }
	
});

</script>
```

### Screenshots
![ssimage](https://user-images.githubusercontent.com/40226633/66802032-c98a4580-ef38-11e9-835b-99ae9157c368.png)

### Additional Information
Tried with Electron 1.8.8, 2.0.18 , 3.1.13 and 4.2.11 and issues seems to exist in those versions.
Same Issue present in Chromium ( 77.0.3865.90 ) too, sharing entire screen is black while individual windows are visible.
Works fine in Firefox Quantum 69.0.3

**Comment by MarshallOfSound** [comment]
> Same Issue present in Chromium ( 77.0.3865.90 ) too, sharing entire screen is black while individual windows are visible.

You should report this upstream to Chromium 👍

**Comment by xudeming208** [comment]
请参考https://github.com/electron/electron/issues/21063

**Comment by NoelDavies** [comment]
Has anybody managed to fix this for streaming to a video element?

**Comment by soundar78** [comment]
Bug's being tracked here
https://bugs.chromium.org/p/chromium/issues/detail?id=682122
