### ISSUE TITLE
node.js fs.mkdir/mkdirSync hang with {recursive: true} if name is invalid

### ISSUE THREAD

**Issue by bpasero** [electron/electron#20588]
### Issue Details

* **Electron Version:**
  * 6.0.11
* **Operating System:**
  * Windows 10

### Expected Behavior
`fs.mkdirSync` never hangs

### Actual Behavior
Run this in renderer:

```js
const fs = require('fs')

/*console.log("1")
fs.mkdir('invalid1:', {recursive: true}, (err) => {
  console.log("is not called")
  if (err) throw err
})*/

console.log("before")
fs.mkdirSync('C:\\Users\\<name>\\Desktop\\invalid2:', {recursive: true})
console.log("after is not reached")
```

This is fixed in later versions of node.js: https://github.com/nodejs/node/issues/28599

//cc @deepak1556

**Comment by deepak1556** [comment]
Fixed with https://github.com/electron/electron/pull/20629
