### ISSUE TITLE
Cordova needs help

### ISSUE THREAD

**Issue by LifeIsStrange** [electron/electron#20595]
Apache Cordova is the electron of mobile.
It is a foundational technology that allows developers to write hybrid web apps and to share most of the code with electron and the web, thus having critically high public utility.

Cordova has currently zero paid developper and a lack of maintenance. 
Cordova needs contributions to get android 10 support.

I believe Cordova and Electron projects share a common goal of pushing the open web forward.

Electron has quickly got a huge success on the desktop and I expect it's only a matter of a few years until cordova get really popular.
The Electron project has gotten many sponsors, especially Microsoft.

I'm asking for the electron project to sponsor cordova as a friend project, and for electron sponsors, especially Microsoft (which is involved in chromium too with Edge) to give help and funding to this foundational technology.

Details:
https://github.com/apache/cordova/issues/163

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. We wish you good luck, but this isn't the most appropriate forum for this question.

**Comment by LifeIsStrange** [comment]
What is the best place to reach electron executives?
