### ISSUE TITLE
Does Electron support 4K USB Video resolution?

### ISSUE THREAD

**Issue by reddysravan014** [electron/electron#20603]
We are developing a windows application using Electron framework. This application intends to show video streaming from USB Camera. We are using "navigator.mediaDevices" apis to access USB video streams. Problem is Electron application unable work for 4K USB video resolution and throws error.

We are able to see the video stream into Electron application but it works only for lower resolution e.g. 480p and hence the quality is not up to mark. The USB camera can support till 4K resolution. However, when we supply higher resolution it works till 720p but beyond that it gives "OverconstrainedError". (code snippet below for refn)

           navigator.mediaDevices.getUserMedia({
                    video:
                        {
                                width: {
                                    exact: usbWidth
                                },
                                height: {
                                    exact: usbHeight

                                },
                                deviceId: {
                                exact: deviceid
                            },
                        }
                }).then(function (stream) {
                    stream.getTracks().forEach(function(track) {
                        console.log(track.getSettings());
                })

My question is:- 1. Does Electron,which is built on top of Chromium, has any limitations with respect to USB Video resolution ? 2. Can 4K USB Video resolution support exist in Electron app ? 3. Is there any reference code which exist to point us in the right direction ?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by miniak** [comment]
@reddysravan014 you didn't even mention which Electron version you've tried.

**Comment by Thejaswini-senthilkumar** [comment]
I'm having the same issue and I'm using the latest electron version can someone help me with this issue
