### ISSUE TITLE
Setting cookie is not working in v7.0.0

### ISSUE THREAD

**Issue by btzsoft** [electron/electron#20607]
### Issue Details

* **Electron Version:**
  * 7.0.0-beta.7
* **Operating System:**
  * Windows
* **Last Known Working Electron version:**
  * 6

### Actual Behavior
```js
await webContents.session.cookies.set({
  domain: '.facebook.com', 
  name: 'my cookie', 
  value: 'my value'
})
```

Here I receive `Failed to get cookies domain` error.

When I try with url the promise is resolved but no any cookies is set in any way.
In generally I wasn't be able to set cookies with v7.0.0

**Comment by codebytere** [comment]
This was fixed in the latest beta by https://github.com/electron/electron/pull/20496.
