### ISSUE TITLE
findInPage can freeze the whole app

### ISSUE THREAD

**Issue by magne4000** [electron/electron#20602]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
* **Electron Version:**
  * `6.x`
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron version:**
  * unknown

### Expected Behavior
When one use `webContents::findInPage` method, it should not freeze the app.

### Actual Behavior
On some verify specific conditions, it happens that calling `webContents::findInPage` can freeze the whole app.
We are yet unsuccessful to reproduce the issue in Electron Fiddle. We haven't found all the parameters that triggers the issues.
**I created this issue mainly to help us debug and be able to provide more information afterwards** 
Additionnal information:
- `found-in-page` event is not received when it crashes
- ~**The crash only happens in the first ~2seconds after the webContents in created**. After that, no more freeze~ It can crash after those 2 seconds, but it's not 100% of the time
- It can crash after the first `findInPage` call or subsequent ones (with or without `findNext: true`)
- We reproduce the issue with any webviews in our application 100% of the time
- We have multiple webviews behind each others
- We have multiple BrowserWindow (the visible one that crashes, and an invisible one)
- We tried to unplug all custom configuration on our webviews (no preload, all default webviews props), and we still have the crash
- As we only reproduce in our app, it is difficult to test with other Electron version than 6.x for now

### To Reproduce
_See comment above_

### Additional Information
_See comment above_

**Comment by adlerfaulkner** [comment]
+1 on electron 6.0.9 on macOS. However I get the crash at any time, not only in the first 2 seconds after webContents creation.

I also have:

* `found-in-page` event is not received when it crashes
* It can crash after the first findInPage call or subsequent ones (with or without findNext: true)
* Multiple webviews behind others
* Multiple BrowserWindows (the visible one that crashes, and an invisible one)

**Comment by praneetrohida** [comment]
+1 on Electron 6.1.4, Windows 10

**Comment by d4kris** [comment]
Just want to add that we have seen this issue on macOs 10.15.3 and electron 7.1.14 and  8.0.3. 
We also have multiple webviews and found-in-page is not triggered.
This page seems extra easy to trigger it on by searching for "overview": https://www.livingston.org/domain/1577, but has been spotted on other pages aswell.

**Comment by Purendra1** [comment]
+1 
Using Electron version 7.1.1 on MacOS Mojave 10.14.6 
The freezes and stops responding when trying to search anything within Webview by using findInPage( )

**Comment by grgvineet** [comment]
+1
Using Electron version 8.3.0 on MacOS Mojave 10.14.6.
On profiling, figured out that electron is stuck in an infinite while loop in [find_request_manager.cc](https://chromium.googlesource.com/chromium/src/+/master/content/browser/find_request_manager.cc#688).
The issue is reproducible when using webview and iframe in same browser window and triggering findInPage in webview. The issue can be reproduced in Electron Fiddle using this [gist](https://gist.github.com/grgvineet/ac5a57de394782539b17ba18959ef3ea).

**Comment by praneetrohida** [comment]
The issue is still present in Electron 9 when the window has both iframes and webviews

**Comment by Sryther** [comment]
+1
Using Electron 9.3.3 on Neon KDE (Ubuntu 20.04), happened on Ubuntu 20.04 and Windows 10 too.
Same environment: running findInPage inside a webview.

**Comment by pnegahdar** [comment]
Also happening on Electron 10+

**Comment by CliffReimers** [comment]
Still seeing this on Electron 16

**Comment by nornagon** [comment]
Would it be possible to get a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by d4kris** [comment]
Still seeing this in electron 19.0.8, I have updated the gist provided by @grgvineet, hope that is enough to debug. Second find call always hangs. 
Does not seem to matter if iframe is allowed to load its content or if nodeIntegration and/or contextIsolation is enabled on the webview.
Remove the iframe and I am unable to repro.

**Comment by d4kris** [comment]
still an issue, is the gist enough to repro?
