### ISSUE TITLE
shell.openItem returns always true on Linux

### ISSUE THREAD

**Issue by xmedeko** [electron/electron#20606]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
```js
let ret = shell.openItem('file:///noexistent');
console.log(ret);
```
`ret` is always `true` on Linux even if opening fails, e.g.
```sh
xdg-open 'file:///noexistent'
echo $?
```
Shows nonzero error code.

* **Electron Version:**
  * v6.0.11
* **Operating System:**
  *Linux / Ubuntu 16.04 x64

### Expected Behavior
`ret` should be `false`, if `xdg-open` returns non-zero code.

Optional: It would be very nice if the `xdg-open` error (catch stderr) would be displayed in `dialog.showErrorBox` if it returns non-zero code. Just take care that `xdg-open` may write some warnings to stderr even if it returns 0.

**Comment by codebytere** [comment]
@xmedeko hey! you're right - the way we've implemented this it just returns true when the command spawns successfully but doesn't wait for the exit code. I'll look into improving this soon!
