### ISSUE TITLE
setMinimumSize does not refresh the BrowserWindow

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#20613]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 5.0.7
* **Operating System:** Windows 10

### Expected Behavior
I set a window's minimum size to be greater than the current size. I expect the BrowserWindow to increase in size to match the new minimums.

### Actual Behavior
The window size doesn't increase until you move the window.

### To Reproduce
```
const { app, BrowserWindow } = require('electron')

async function createWindow() {
	const mainWindow = new BrowserWindow({ width: 500, height: 500 });
	mainWindow.setMinimumSize(700, 700); // size only increases to this after moving the window
}

app.on('ready', createWindow)
```

**Comment by pushkin-** [comment]
This is also an issue in Electron 7.1.2

**Comment by gtkpr** [comment]
> This is also an issue in Electron 7.1.2

7.1.8 too.

**Comment by pushkin-** [comment]
can't reproduce this with 8.0. for some reason, I can't reproduce this with 7.1.2 either anymore. not sure what changed. I am using a different Windows version than before, so maybe that's the difference.

**Comment by pushkin-** [comment]
Actually, I can reproduce with Electron 8.0.1 on Windows 10.0.16299. Can't repro on Windows 10.0.18362

**Comment by pushkin-** [comment]
With Electron 8.2.2 and Windows 10 1909 (OS Build 18363.720), it does resize now, but I see a black frame around the old size for a bit, which goes away after a couple seconds.

Below, original size was 300x300, and I set minimum size to 700x700.

![image](https://user-images.githubusercontent.com/6374473/79237075-5acc6d00-7e33-11ea-8c8e-8f9b64fd070f.png)

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by pushkin-** [comment]
reposted issue to [here](https://github.com/electron/electron/issues/28084)
