### ISSUE TITLE
DevTools disappear on unmaximize/un-full screen.

### ISSUE THREAD

**Issue by wjharney** [electron/electron#20623]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.0+
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 5.0.11

### Expected Behavior
DevTools docked to right or bottom should not disappear when changing from maximized or full screen to normal state.

### Actual Behavior
DevTools docked to right or bottom disappear when changing from maximized or full screen to normal state.

The DevTools are not closed, they are simply not visible. The DevTools reappear when closed/re-opened or the window is enlarged, but not when it is shrunk. DevTools docked to left or undocked do not disappear. Focus is also not necessarily lost when the DevTools disappear. To demonstrate, run the fiddle linked below. Open the JS console, enter something (`alert(1)`). Trigger the disappearance using keyboard commands. Hit enter.

### To Reproduce
Run [this gist](https://gist.github.com/wjharney/7f2ce41becec2902d3f658050aa60465) in Electron Fiddle. Click some buttons.

**Comment by pushkin-** [comment]
Since the gist is deleted, here's a minimal example. I can repro this with Electron 11.

1. start main.js
2. click open window
3. maximize window
4. restore window
5. observe that the devtools disappears until you make the window larger

main.js:
```
const {app, BrowserWindow} = require('electron')

function createWindow () {
  const mainWindow = new BrowserWindow({
    webPreferences: {
      nativeWindowOpen: true
    }
  })

  mainWindow.loadFile('index.html')

  app.on("browser-window-created", (e, win) => {
    win.webContents.openDevTools({mode: "bottom"});
  });
}

app.whenReady().then(() => {
  createWindow()
})

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})
```

index.html:
```
<!DOCTYPE html>
<html>
  <body>
    <button id="b" onclick="window.open('https://google.com')">Open Window</button>
  </body>
</html>
```

**Comment by wjharney** [comment]
> Since the gist is deleted, here's a minimal example.

Not deleted, the link just didn't survive a name change. 😉

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by pushkin-** [comment]
This doesn't repro with Electron 12.0.1
