### ISSUE TITLE
打包后启动无显示，不是显示空白，而是根本没显示

### ISSUE THREAD

**Issue by GuoSirius** [electron/electron#20630]
electron 4.2.12
node 10.16.2
npm 6.9

Windows 10 64位 如下：

![image](https://user-images.githubusercontent.com/48358523/67068525-ea5ad100-f1ac-11e9-934a-a2d0cf02ca4e.png)

部分 window7 64位 机器打开后如下

这是异常的， 如下：

![}A1BM8H%`DLG753 ZL3ORI9](https://user-images.githubusercontent.com/48358523/67068568-12e2cb00-f1ad-11e9-8c09-08fcbd1b8990.jpg)

这是正常的， 如下：

![NK{(9E6KB3}%0K$V1O8AVFJ](https://user-images.githubusercontent.com/48358523/67068574-15ddbb80-f1ad-11e9-8f3d-15971e53ca9b.jpg)

双击应用打开后，可以看到有3个进程，一秒钟左右，其中一个就删除了，只剩两个，导致根本就没有应用窗口

有的win7 64位可以，有的不行，都是新采购的台式机

**Comment by markgitHub2016** [comment]
之前遇到同样的问题，使用右键兼容方式就可以打开，或者升级到5版本就好了，

**Comment by sofianguy** [comment]
We are no longer pushing bug fixes to versions 4.x.y or older, see our [supported versions doc](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#currently-supported-versions). Please upgrade to version 5 or newer.

Closing this as it is reported by @markgitHub2016 as fixed.

**Comment by GuoSirius** [comment]
> 之前遇到同样的问题，使用右键兼容方式就可以打开，或者升级到5版本就好了，

@markgitHub2016 Thank You!
