### ISSUE TITLE
Window renders incorrectly on multi-monitor setup

### ISSUE THREAD

**Issue by drk-mtr** [electron/electron#20633]
### Potential Duplicate

This may overlap with https://github.com/electron/electron/issues/20067 but I'm not sure, as that issue does not contain screenshots. Please feel free to delete if this is already tracked elsewhere.

### Issue Details

* **Electron Version:** 4.2.10
* **Operating System:** Windows 10 18362
* **Last Known Working Electron version:** N/A

### Description
Window renders incorrectly. Generally shows a blank space at the top of the screen that results in being unable to see the top menu bar and the area just below it.

Screenshot:
![image](https://user-images.githubusercontent.com/40315783/67099140-4a557580-f1b5-11e9-9702-5dcd0db5d23f.png)

Same issue, but using a different theme so that it's clearer to see what's going on:
![image](https://user-images.githubusercontent.com/40315783/67099212-6ce78e80-f1b5-11e9-8710-3a582a7acd66.png)

### To Reproduce

- Open an Electron app (occurs in the latest versions of Slack and VSCode)
- Move it to the other monitor by dragging with the mouse and let it snap to fullscreen OR move to other monitor with `Windows + Left` key and then `Windows + Up`

### Workaround

Press the `Windows + Left` or `Windows + Right` key to display the app in only half of the screen
OR
Keep the app windowed and drag it to an "almost fullscreen" size

**Comment by sofianguy** [comment]
We are no longer pushing bug fixes to version 4.x.y or earlier, see our [supported versions doc](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#currently-supported-versions). Please upgrade to version 5 or newer and let us know if this is still a problem in later versions.

**Comment by drk-mtr** [comment]
Tell slack to update ha
