### ISSUE TITLE
Electron 7, request using net module never contains cookies in response

### ISSUE THREAD

**Issue by t57ser** [electron/electron#20631]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.0.0-beta.7
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 6

### Expected Behavior
Cookies are received

### Actual Behavior
response.headers["set-cookie"] never contains cookies

### To Reproduce
Do a request using the net module as described here: https://electronjs.org/docs/api/net
to any site that will return cookies.

**Comment by codebytere** [comment]
cc @zcbenz, this seems like a nws13n issue?

**Comment by zcbenz** [comment]
Yeah it looks like a regression from nws13n.

**Comment by t57ser** [comment]
Also not working in: 8.0.0-beta.2

**Comment by t57ser** [comment]
I have found a workaround:
```
const session = electron.session.fromPartition("AUTH" + Math.random());
const request = electron.net.request({
	url: "http://localhost:3000/logon",
	method: "GET",
	session,
});
request.on("login", function (_, callback) {
	callback("credentials.username", "credentials.password");
});
request.on("response", (response) => {
	response.on("error", (e) => {
		console.error(e);
	});
	session.cookies.get({}).then((c) => {console.log("cookies in session", c);});
});
request.on("error", (e) => {
	console.error(e);
});
request.end();
```
Passing a session will put the cookies into the session.
Note: This does not work when passing "partition" instead of "session"
This workaround also does not work if:
`app.commandLine.appendSwitch("enable-experimental-web-platform-features");` was set.

**Comment by arantes555** [comment]
Author of [electron-fetch](https://www.npmjs.com/package/electron-fetch) here. Seeing the same problem (plus many others...) in the net module in electron7.

**Comment by arantes555** [comment]
(it seems somewhat linked to https://github.com/electron/electron/issues/8891 , but it is not the same issue)
