### ISSUE TITLE
Unable to use zeromq, module was compiled against a different Node.js version using NODE_MODULE_VERSION 48. This version of Node.js requires NODE_MODULE_VERSION 73.

### ISSUE THREAD

**Issue by trusktr** [electron/electron#20641]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.12
* **Operating System:**
  * macOS 10.14.6 (18G87)
* **Last Known Working Electron version:**
  * not sure

### Expected Behavior

`npx electron-rebuild` and everything should work.

### Actual Behavior

```
Uncaught Error: The module '/Users/trusktr/src/tracker/node_modules/zeromq/build/Release/zmq.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 73. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

This is what I've tried so far:

- First I tried  `npm rebuild`, ran Electron, and got the above `72` vs `73` error.
- Then I ran `npx electron-rebuild`, ran Electron, and got same `72` vs `73` error.
- Then I removed `node_modules` and `npm install`ed, ran Electron, and the error became `48` vs `73`.
- Then I downgraded `electron` to `^5`, re-installed node_modules, ran Electron, and the error became `47` vs `70`.
- Then I ran `electron-rebuild`, ran Electron, no change. Still `47` vs `70`.
- Then I ran `npm rebuild`, ran Electron, and the error changed to `72` vs `70` (seems to make sense, my node version is 12, and Electron v5 expects a lower ABI version than that).

The `electron-rebuild` process completes very fast. It doesn't seem like anything can rebuild that fast. Is there a cache I can clear to try rebuild?

### To Reproduce

- Install `electron` v5 or v6.
- Install `zeromq` 5.1.0
- Try to import and use `zeromq` in the electron application

I have no reproduction I can share yet.

### Additional Information

No matter what I try, I can't get rid of this error. As described above, `npm rebuild` won't work because it isn't a version of Node.js with an Electron ABI version.

When I run `electron-rebuild`, it completes quickly, and doesn't fix the error.

Anything else I should try?

**Comment by trusktr** [comment]
If I go back to Electron v3.x.x, the problem goes away.

**Comment by bet4it** [comment]
Try this:
```
rm -rf ~/.cache/node-gyp
rm -rf ~/.electron-gyp
```
Then rebuild.

This could solve `47 vs 70` or `48 vs 73`.

If it still doesn't work, try to remove all the custom settings of `npm` and `yarn` environment variable (For example, `electron_mirror`).

**Comment by miniak** [comment]
This seems like an issue with `electron-rebuild`, which needs to be reported there.

**Comment by trusktr** [comment]
Might be a bug in ZeroMQ (haven't tested yet): https://github.com/zeromq/zeromq.js/issues/338
