### ISSUE TITLE
Add an API to enumerate system/installed fonts.

### ISSUE THREAD

**Issue by tdbender** [electron/electron#20642]
This would be useful for an app to be able to present to the user a list of fonts already installed on their system and available for use.  Users may have installed additional fonts but Electron apps have no way to know they are installed.

**Comment by codebytere** [comment]
I honestly think this might live better as a native node module - i actually have already started playing with this here: https://github.com/codebytere/electron-font-manager

**Comment by issacgerges** [comment]
We've used https://github.com/foliojs/font-manager in the past but have noticed some discrepancy between how Chromium parses font files and how other libraries do

@codebytere I noticed that https://www.chromium.org/developers/design-documents/directwrite-font-proxy exists (at least partially) to expose font APIs to the renderer to power `chrome.fontSettings`. I wonder if this could be exposed via an electron API?

https://cs.chromium.org/chromium/src/content/child/dwrite_font_proxy/dwrite_font_proxy_win.h?g=0

**Comment by ArcherWong** [comment]
'electron-font-manager@latest' is not in the npm registry. @codebytere how can I install it.

**Comment by codebytere** [comment]
Published: https://www.npmjs.com/package/electron-font-manager

I'm also going to close this now as a wontfix, as this is not something we will be implementing into core in the near future.

**Comment by tdbender** [comment]
Published for MacOS.  How do we do this for Windows and Linux?

**Comment by ThaUnknown** [comment]
we can now get this via [FontAccessAPI](https://wicg.github.io/local-font-access/), but it seems like the latest version of electron doesn't support this. @codebytere is this going to change anytime soon?
![image](https://user-images.githubusercontent.com/6506529/177363046-67606fd4-36d7-4531-adcb-a1fa47ce3331.png)

**Comment by 2xAA** [comment]
@ThaUnknown The FontAccessAPI is definitely available in Electron 22.0.0. It was added in Chromium 103.

**Comment by ThaUnknown** [comment]
> @ThaUnknown The FontAccessAPI is definitely available in Electron 22.0.0 (current). It was added in Chromium 103.

that comment was posted before FontAccessAPI was implemented in electron :^) but yes it works fine now
