### ISSUE TITLE
Addon rebuilding - wierd (DLL) initialization error

### ISSUE THREAD

**Issue by thehorseisbrown** [electron/electron#20653]
### Issue Details

I was getting the same errors on any **working** node.js addon I tried to rebuild so it works with electron:
Javascript error in the main process: **Uncaught exception, A dynamic link library (DLL) initialization routine failed.**

### Expected Behaviour
I expect that I don't get exceptions when trying to add addons

### Actual Behavior

I tried to follow any steps I could find but nothing worked.
Then I suddenly managed to get it working by downgrading to electron3!
I borrowed example projects at https://github.com/nodejs/node-addon-examples and this worked on my machine:

`npm install`
`npm install electron@3`
`npm install --save-dev electron-rebuild`
`.\node_modules\.bin\electron-rebuild.cmd`

So I took the example addon (hello world, N-API) and cycled through the electron versions to find which ones are the faulty ones:

I cycled through the versions like this:
`npm install electron@version`
`.\node_modules\.bin\electron-rebuild.cmd`
`electron .`

I thought I would get determinate answers but as I was trying to identify the border of where the versions stopped working ( 2-didnt rebuild, 3 good, 4+ bad.. ) but I noticed that the same version would sometimes work and sometimes not. I hope this information is valuable to you... My layman guess is that its something to do with npm and updating of files, rather than electron versions..

### My machine
My system is Windows 10 x64, node 10.13.0 x64

**Comment by miniak** [comment]
This issue needs to be reported to electron-rebuild
