### ISSUE TITLE
remote.getGlobal should return value without getter/setter

### ISSUE THREAD

**Issue by dreamerblue** [electron/electron#20650]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

When I access the main process `global` in renderer process by `remote.getGlobal('someProperty')`, it returns the value with getter/setter (to lazily get/set value through IPC?). Such as object, array and function returns are always be with getter/setter.

It's so inconvenient for some use like logging and some other libraries. So in many times I need to delete the getters and setters by cloning the object after function return.

Relative issues and discussions:
- [View does not update after `$store.state.array[i].attr = ‘value’`](https://forum.vuejs.org/t/view-does-not-update-after-store-state-array-i-attr-value/5226)
- [Getting “simple” remote objects in electron](https://stackoverflow.com/questions/35976638/getting-simple-remote-objects-in-electron)

### Proposed Solution

Maybe add an additional param in remote.getGlobal to configure it returns the whole object (array, function...) without getter/setter.

**Comment by miniak** [comment]
https://medium.com/@nornagon/electrons-remote-module-considered-harmful-70d69500f31

**Comment by miniak** [comment]
This is by design
