### ISSUE TITLE
Spellecheckerprovider does not forward composited unicode charpoint as-is

### ISSUE THREAD

**Issue by kwonoj** [electron/electron#20654]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  6.0.12, master
* **Operating System:**
  *  Confirmed on windows 10, not sure other platforms
* **Last Known Working Electron version:**
  *  unknown

### Expected Behavior

unicode charpoint preserved when `spellcheck: (words...)` callback delivers words

### Actual Behavior

charpoint does not honor composition, forwards splitted charpoint string

### To Reproduce

- clone https://github.com/kwonoj/char-codepoint-repro
- npm install && npm start
- as instructed, copy char in screen (`한글`) and paste into input to trigger spellcheck (if necessary, press space key to trigger)
- check console output compare between input's value to spellchecker forwarded

### Screenshots

![image](https://user-images.githubusercontent.com/1210596/67176635-bb488900-f37f-11e9-8166-af9a7478fa74.png)

### Additional Information

While spellchecker provider seems to deliver same string, it's lookalike string which is different string. In result, compare original input string to received words in callback shows those two are different. 

It's due to forwarded string in callback does not honor composited unicode charpoint - in repro example single char `한` is `\uD55C` (https://mothereff.in/js-escapes#1%ED%95%9C) and spellchecker callback will deliver `한` as `\u1112\u1161\u11AB` (https://mothereff.in/js-escapes#1%E1%84%92%E1%85%A1%E1%86%AB) which is 3 separate unicode charpoint in composited (`ㅎ`, `ㅏ`,`ㄴ`) 

This isn't limited to KR, any other unicode charpoint can have a composition (i.e `mañana`, `mañana`) will show same results.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
