### ISSUE TITLE
Slow POS printing when using certain printers

### ISSUE THREAD

**Issue by francescodicaprio** [electron/electron#20651]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.0.0-beta.7
* **Operating System:**
  * Window 7 Pro 32-bit

Hi everyone,
I have given a lot of thoughts before to open the issue, as I didn't think that it was actually an electron issue. I'm a beginner in terms of developing with Electron. After a lot of tests I have tried to isolate the issue as best as I could. Basically, I have an electron application (packed and built with electron-builder as a single .exe portable application) which loads a web app. This web app has a print button and when it gets clicked, ipcRenderer sends a message to ipcMain with the url of the web page I want to print. The webpage is a simple HTML/CSS page with a 80mm template (POS receipt). The main process receives the message, opens the webpage as an invisible browserWindow, it prints it when it's ready-to-show using a pre-defined printer, and then destroys the window.

### Expected Behavior
Well, I expect the web page to be printed at the same speed with which it gets printed using Chrome, Chromium, Firefox, etc. 

### Actual Behavior
Indeed the document gets printed, but very slowly. The print job gets fired in time, and printing begins almost immediately, but it takes a long time to print the document. Approximately 4-5 seconds. 
Quick fact: I have been using electron 3.x for months, because silent printing when specifying a printer was constantly getting fixed and then broken version by version. I thought that the slowness was due to electron 3.x using a very old version of Chromium, so I thought about solving the issue upgrading to 7.0.0-beta7 (after following all the PRs and open issues in terms of silent printing). After upgrading, the slowness is still there.
The same document gets printed at the printer's normal speed (less than 1 second), on the same machine, with the same printer:
- using Chrome 77 (latest)
- using the same version of Chromium that electron is using (I have got it by console logging process.versions, 78.0)
- using Firefox (latest)
- using Microsoft Edge (latest)

### To Reproduce
Get a standard 80mm or 72mm wide HTML/CSS POS receipt. No images, no complex elements, just texts and lines generated by table borders. This is how I print it within the application.
```
ipcMain.on("print", (event, arg) => {
        let printWindow = new BrowserWindow({show: false});
        printWindow.loadURL(arg);
        printWindow.on("ready-to-show", () => {
            printWindow.webContents.print({silent: true, deviceName: device.config.printerName});
            printWindow = null;
        });
    });
```

### Additional Information
Additionally, it doesn't happen with all the printers. If I use an Epson TM-T20II, for example, the speed is normal even within electron. The issue is currently happening with a Star TSP100 ECO FuturePRNT and with a Citizen CT-E351. Tricking the printer configuration using Windows or the printer's utility doesn't solve the issue, I'm pretty sure I have tried all the possible combinations.

Thanks in advance.

**Comment by baconbrad** [comment]
I can confirm this issue with Star TSP100 printers as early as version 3.0.X. Doing text only documents the printer goes at normal speed. When printing documents with a graphic such as a logo or barcode the print speed is significantly slower. The whole document is printed slow and not just the section with the graphics. Printing the same document in any web browser does not have this issue. We have found no work around.

**Comment by rafaelvaloto** [comment]
I'm having the same problem with the epson TM-T20 printer, I'm using the v9.1 version of electron, when printing is done with silent: false it is very fast, but when it is done with silent: true it is slow

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by baconbrad** [comment]
I went to make another issue since it still exists in the latest versions of Electron. But in testing through the latest Chromium I noticed it has the same issue opposed to if I print the same thing directly through my file manager. This leads me to believe it is an upstream issue. I will research it a little more and will report any future findings here.
