### ISSUE TITLE
cant select webview tag with "inspect" tool from devtools

### ISSUE THREAD

**Issue by BasitCode** [electron/electron#20658]
inspect tool cant select webview tag 

![image](https://user-images.githubusercontent.com/53387349/67210849-36b74280-f433-11e9-9b2d-4ca36e9dac4f.png)

also i noticed mouse events not working correctly in webview, draging something from outside renderer (splitter). draging element stops moving when it reaches webview panel

it happened when im updated to 6.0.12 from 2.0.18

sorry for my bad english

**Machine**
electron version: 6.0.12
os: windows 7 64bit

**Comment by HaNdTriX** [comment]
This is because an WebView is not an iframe.
As a workaround try the following code:

```js
// select webview tag -> openDevTools
document.querySelector('webview').openDevTools()
```

**Comment by Kilian** [comment]
Hi Basit, this is correct behaviour.

Webviews are inplemented as out of process iframes and are not part of the same process of the surrounding page/webContents. Like @HaNdTriX said, you can use the devtools of a specific webview to inspect it, and you can use IPC to communicate with the content inside a webview: https://electronjs.org/docs/api/webview-tag#webviewsendchannel-arg1-arg2-

**Comment by BasitCode** [comment]
in my opinion I explained incorrectly

im just need to inspect <webview></webview> tag (not inside)

![image](https://user-images.githubusercontent.com/53387349/67403432-56816e80-f5cb-11e9-9554-b8d812607e66.png)

this not appears when hovering in webview, but it worked in previous version (2.0.18)

**Comment by Kilian** [comment]
Because the Webview is a different process, your regular browserWindow can't actually detect that the mouse is over it. This is by design. You can use the elements to select the webview instead.
