### ISSUE TITLE
How to keep authentication after app.quit()

### ISSUE THREAD

**Issue by faradoxuz** [electron/electron#20659]
How to keep localstorage items after quitting the app

**Comment by HaNdTriX** [comment]
https://electronjs.org/docs/api/browser-window

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
