### ISSUE TITLE
release notes script does a bad job of weeding out fixes that have already landed in previous branches

### ISSUE THREAD

**Issue by ckerr** [electron/electron#20660]
The release notes script generates a _lot_ of entries in the 7.0.0 notes that should be omitted because they include fixes that were already included in previous releases.

For example, https://github.com/electron/electron/pull/19941 was included. Its description reads:

```
Backport of #19912

See that PR for details.

Notes: Fixed command-line scheme arguments from spilling over into each other.
```

And #19912 has a `merged/6-0-x` label. The 6-0-x backport was PR #19940 which was merged in https://github.com/electron/electron/commit/6b77e2ee14a23ce73185c290ce43256c3b232969, so this should not have been included in the 7.0.0 release notes.

Invocation was

```sh
$ ./release/notes/index.js origin/6-0-x..origin/7-0-x --version v7.0.0 --explicit-links
```

**Comment by nornagon** [comment]
I think we do a lot better on this now!
