### ISSUE TITLE
Menu zoomin and zoomout doesn't work with webviews

### ISSUE THREAD

**Issue by HaNdTriX** [electron/electron#20667]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.x.x
  * 6.x.x
  * 7.0.0-beta.7
* **Operating System:**
  * MacOS: 10.14.6
* **Last Known Working Electron version:**
  * none

### Expected Behavior

When using Menu role `zoomin` `zoomout` or `resetzoom` together with WebViews it should always target the currently selected browser context or WebView.

### Actual Behavior

When using Menu role `zoomin` `zoomout` or `resetzoom` together with WebViews it aways targets the last created webview.

### To Reproduce

[Example Repository](https://github.com/HaNdTriX/electron-focusedWindow-bug)

```sh
$ git clone git@github.com:HaNdTriX/electron-focusedWindow-bug.git
$ npm install
$ npm start
```

...and follow the instructions.

### Screenshots

![Oct-21-2019 22-11-33](https://user-images.githubusercontent.com/1265681/67239718-1e095580-f450-11e9-8394-35bf76cf0ba1.gif)

### Additional Information

I believe this bug may affect many issues regarding menu items. 

### Related issues

#19559 #15496 #15896

**Comment by abhigyank** [comment]
We can replicate this on [Zulip Desktop App](https://github.com/zulip/zulip-desktop/) as well. For us the zoom in behavior works correctly, but the zoom out and reset zoom works only on last created webview as reported in this issue. We are using v8.1.1.

**Comment by akashnimare** [comment]
@sofianguy still getting this on v8. Any plans to fix this in v9/v10?

**Comment by akashnimare** [comment]
Currently using accelerators instead of `Roles` as a temporary fix.

**Comment by andersk** [comment]
https://github.com/electron/electron/blob/805e442ff873e10735a1ea18021f491597afa885/lib/browser/api/web-contents.ts#L680-L690

`getFocusedWebContents` uses `WebContents#isFocused` to check whether each webview is focused, but empirically, `WebContents#isFocused` returns `true` as long as the *window* is focused regardless of how many webviews are in the window. So `getFocusedWebContents` will always return the first webview it finds, not the focused webview.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
