### ISSUE TITLE
Prevent closing of window

### ISSUE THREAD

**Issue by AndiLeni** [electron/electron#20668]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

* Electron Version: latest
* Operating System: Windows 10 1903

Hello,

I know this topic was already adressed several times, but I struggle to archive this with a newer electron version.

What I tried: using the code sample from https://electronjs.org/docs/api/browser-window both with and without the ``e.preventDefault()`` function.
````
window.onbeforeunload = (e) => {
  console.log('I do not want to be closed')
  e.returnValue = false // equivalent to `return false` but not recommended
}
````
I've put this funtion inside my ``main.js`` file. 
The windows object is created with 
````
win = new BrowserWindow({
        width: 1000,
        height: 500,
        resizable: true,
        minimizable: true,
        maximizable: true,
        closable: true,
        webPreferences: {
            nodeIntegration: true
        }
    })
````

Unfortunately the window still closes whan I press the window-close button. 
Is this an issue with electron or do I face a problem on my side?

Regards
Andi

**Comment by itsananderson** [comment]
I just wrote up a basic Electron Fiddle demo and this seems to work. https://gist.github.com/eac11940e1660fca3a9dc6875ac338a4

Based on your description, what might be happening is that you're trying to define `onbeforeunload` in your `main.js` by adding it to the `BrowserWindow` object. What you actually want to do is define `window.onbeforeunload` inside the JS on your webpage, as in the example I linked to above.

Alternatively, if you want to prevent the window from closing from `main.js` you would listen to the "close" event and cancel that event like so:

```
win.on('close', e => {
  e.preventDefault();
});
```

The advantage of the `onbeforeunload` method is that you can check any state you might have inside the web page to see if there are unsaved changes or other things that should prevent the page from unloading.

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
