### ISSUE TITLE
The new audioMuted property should work on WebViews

### ISSUE THREAD

**Issue by HaNdTriX** [electron/electron#20679]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.0.0
  * 8.0.0
  * 8.0.1
  * 9.0.0-beta.1
  * 9.0.0-beta.2
* **Operating System:**
  * MacOS: 10.14.06

### Expected Behavior

`webview.audioMuted = true` should mute the webview. 
`webview.audioMuted = false` should unmute the webview. 

### Actual Behavior

`webview.audioMuted = true` does nothing but triggers the following warning:

```log
(electron) 'setAudioMuted function' is deprecated and will be removed. Please use 'audioMuted property' instead.
```

### To Reproduce

Check out the following electron fiddle

https://gist.github.com/e80bbbc93d80be9889d8aceb4b8c20a2

**Comment by codebytere** [comment]
@HaNdTriX welp, this does not work in 6, 5, or 4, so it's at least not an issue with the property migration. I'll try to poke at this more.

**Comment by HaNdTriX** [comment]
@codebytere thanks for having a look at this 🙏! For my understanding all "old" setter and getter methods will be deprecated in in the next versions of electron. 

Currently I moved back to `setAudioMuted` as a temporary fix. Nevertheless I can't turn of that misleading deprecating warning electron is triggering:

```
(electron) 'setAudioMuted function' is deprecated and will be removed. Please use 'audioMuted property' instead.
```

**Comment by codebytere** [comment]
@HaNdTriX wait, does the non-property version work? Neither worked when i tested your repro.

**Comment by HaNdTriX** [comment]
`webview.setAudioMuted(true)` works fine but this one triggers a deprecation warning. Tested on `macOS` via 
[Electron Fiddle](https://electronjs.org/fiddle).

**Comment by KochiyaOcean** [comment]
I've noticed that if webview is set as muted, sometimes when a iframe inside webview reloads, it will still play sounds.
It's hard to create a stable reproduce. If I find a way to make it, I'll make a demo and publish it here.

**Comment by HaNdTriX** [comment]
@sofianguy I could reproduced this bug in the latest versions of electron as well and updated the description above to reflect these changes.
