### ISSUE TITLE
get code failed

### ISSUE THREAD

**Issue by panguclick** [electron/electron#20676]
system:windows 10

PS **E:\electron-gn> gclient sync --with_branch_heads --with_tags**
Syncing projects: 100% (95/95), done.

________ running 'vpython.bat src/electron/script/apply_all_patches.py src/electron/patches/config.json' in 'E:\electron-gn'
Applying: Make Module.globalPaths a reference.
Applying: fix: don't create console window when creating process
Applying: refactor: alter child_process.fork to use execute script with Electron
Applying: feat: add uv_loop watcher_queue code
Applying: feat: initialize asar support
Applying: Expose `get_builtin_module` function
Applying: fix: build and expose inspector agent
Applying: fix: expose InternalCallbackScope
Applying: build: add GN build files
Applying: fix: export DebugOptions
Applying: fix: add default values for 'enable_lto' and 'build_v8_with_gn' in common.gypi
Applying: feat: add new built_with_electron variable to config.gypi
Applying: feat: add flags for low-level hooks and exceptions
Applying: export Environment::kNodeContextTagPtr
Applying: fix: expose tracing::Agent and use tracing::TracingController instead of v8::TracingController
Applying: fix: use bssl BN_bn2bin_padded for ossl's BN_bn2binpad
Applying: Pass all globals through "require"
Applying: Call process.log from fallback stream on Windows
Applying: FIXME: use redefined version of internalModuleStat
Applying: FIXME: remove async_id assertion check
Applying: fixme: Comment trace event macro
Applying: fix: Export node::Abort and Assert
Applying: fix: key gen APIs are not available in BoringSSL
Applying: fix: do not define DebugOptions's constructors in header
Applying: src: Disable NODE_USE_V8_PLATFORM in node_options
Applying: build: modify js2c.py to allow injection of original-fs and custom embedder JS
Applying: refactor: allow embedder overriding of internal FS calls
Applying: chore: prevent / warn non context-aware native modules being loaded
Applying: Inherit ELECTRON_CRASHPAD_PIPE_NAME in child process
Applying: fixme: Revert "crypto: add support for RSA-PSS keys"
Applying: chore: re-add CompileAndCall, this should be added as a helper in electron
Applying: fix: extern the NativeModuleEnv and options parser for debug builds
Applying: chore: read _noBrowserGlobals from global not config
Applying: chore: split CreateEnvironment into CreateEnvironment and BootstrapEnvironment
Applying: chore: handle default_configuration not being set in the electron env
Applying: Revert "crypto: add outputLength option to crypto.createHash"
Applying: fsevents: stop using fsevents to watch files
Applying: fsevents: regression in watching /
Applying: build: bring back node_with_ltcg configuration
Applying: Revert "tls: add option to override signature algorithms"
Applying: Revert "crypto: fix OpenSSL return code handling"
Applying: Revert "crypto: add oaepLabel option"
Applying: fix: windows compilation on libuv setsockopt
Applying: fix: don't use node-controlled prepareStackTrace
Applying: fix: remove uses of NODE_USE_V8_PLATFORM
Applying: add_realloc.patch
Applying: build_gn.patch
Applying: dcheck.patch
Applying: accelerator.patch
Applying: blink_file_path.patch
Applying: blink_local_frame.patch
Applying: blink_world_context.patch
Applying: can_create_window.patch
Applying: disable_hidden.patch
Applying: dom_storage_limits.patch
Applying: out_of_process_instance.patch
Applying: render_widget_host_view_base.patch
Applying: render_widget_host_view_mac.patch
Applying: thread_capabilities.patch
Applying: web_contents.patch
Applying: webview_cross_drag.patch
Applying: disable_user_gesture_requirement_for_beforeunload_dialogs.patch
Applying: gin_enable_disable_v8_platform.patch
Applying: gin_with_namespace.patch
Applying: blink-worker-enable-csp-in-file-scheme.patch
Applying: disable-redraw-lock.patch
Applying: v8_context_snapshot_generator.patch
Applying: boringssl BUILD.gn
Applying: pepper_flash.patch
Applying: no_cache_storage_check.patch
Applying: blink_fix_prototype_assert.patch
Applying: libgtkui_export.patch
Applying: gtk_visibility.patch
Applying: sysroot.patch
Applying: mas_blink_no_private_api.patch
Applying: mas_no_private_api.patch
Applying: resource_file_conflict.patch
Applying: scroll_bounce_flag.patch
Applying: mas-cfisobjc.patch
Applying: mas-cgdisplayusesforcetogray.patch
Applying: mas-audiodeviceduck.patch
Applying: mas-lssetapplicationlaunchservicesserverconnectionstatus.patch
Applying: ignore_rc_check.patch
Applying: chrome_key_systems.patch
Applying: allow_nested_error_trackers.patch
Applying: blink_initialization_order.patch
Applying: ssl_security_state_tab_helper.patch
Applying: exclude-a-few-test-files-from-build.patch
Applying: desktop_media_list.patch
Applying: proxy_config_monitor.patch
Applying: gritsettings_resource_ids.patch
Applying: isolate_holder.patch
Applying: notification_provenance.patch
Applying: content_browser_main_loop.patch
Applying: dump_syms.patch
Applying: command-ismediakey.patch
Applying: tts.patch
Applying: printing.patch
Applying: verbose_generate_breakpad_symbols.patch
Applying: support_mixed_sandbox_with_zygote.patch
Applying: autofill_size_calculation.patch
Applying: fix_disable_usage_of_abort_report_np_in_mas_builds.patch
Applying: fix_disable_usage_of_pthread_fchdir_np_and_pthread_chdir_np_in_MAS.patch
Applying: fix_disable_usage_of_setapplicationisdaemon_and.patch
Applying: unsandboxed_ppapi_processes_skip_zygote.patch
Applying: patch_the_ensure_gn_version_py_script_to_work_on_mac_ci.patch
Applying: build_add_electron_tracing_category.patch
Applying: disable_custom_libcxx_on_windows.patch
Applying: worker_context_will_destroy.patch
Applying: fix_breakpad_symbol_generation_on_linux_arm.patch
Applying: frame_host_manager.patch
Applying: crashpad_pid_check.patch
Applying: remove references to Profile from PreconnectManager
Applying: network_service_allow_remote_certificate_verification_logic.patch
Applying: put_back_deleted_colors_for_autofill.patch
Applying: build_win_disable_zc_twophase.patch
Applying: disable_color_correct_rendering.patch
Applying: add_contentgpuclient_precreatemessageloop_callback.patch
Applying: feat: enable picture in picture mode for video players
Applying: fix: disabling compositor recycling
Applying: allow new privileges in unsandboxed child processes
Applying: expose SetUserAgent on NetworkContext
Applying: feat: add set_theme_source to allow apps to override chromiums internal theme choice
Applying: Revert "Cleanup: Remove Menu Subtitles/Sublabels"
Applying: ui/views: fix namespace qualification with jumbo_build
Applying: export FetchAPI mojo traits to fix component build
Applying: build: fix when building with enable_plugins=false
Applying: add zoom limit setters to webcontents
.git/rebase-apply/patch:9: trailing whitespace.
    // Results Table
warning: 1 line adds whitespace errors.
Applying: expose ripemd160
Applying: expose aes-{128,256}-cfb
Applying: add_realloc.patch
Applying: build_gn.patch
Applying: expose_mksnapshot.patch
Applying: deps: provide more V8 backwards compatibility
Applying: dcheck.patch
Applying: Export symbols needed for Windows build
Applying: Workaround an undefined symbol error
Applying: Do not export private V8 symbols on Windows
Applying: Revert "[cleanup] Switch {OFFSET_OF} to {offsetof} where possible."
Applying: Temporarily disable 31 bit Smis on 64-bit architectures
Applying: Include ostream in quic_ip_address.h
Hook 'vpython.bat src/electron/script/apply_all_patches.py src/electron/patches/config.json' took 48.96 secs
**Running hooks:   3% ( 3/84) electron_npm_deps
________ running 'vpython.bat -c import os, subprocess; os.chdir(os.path.join("src", "electron")); subprocess.check_call(["python", "script/lib/npx.py", "yarn@1.15.2", "install", "--frozen-lockfile"]);' in 'E:\electron-gn'
Traceback (most recent call last):
  File "script/lib/npx.py", line 18, in <module>
    npx(*sys.argv[1:])
  File "script/lib/npx.py", line 7, in npx
    subprocess.check_call(call_args)
  File "C:\Python27\Lib\subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Python27\Lib\subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\Lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Python27\Lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\Lib\subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', 'script/lib/npx.py', 'yarn@1.15.2', 'install', '--frozen-lockfile']' returned non-zero exit status 1
Error: Command 'vpython.bat -c import os, subprocess; os.chdir(os.path.join("src", "electron")); subprocess.check_call(["python", "script/lib/npx.py", "yarn@1.15.2", "install", "--frozen-lockfile"]);' returned non-zero exit status 1 in E:\electron-gn**

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

**Comment by miniak** [comment]
@panguclick seems like you don't have `npx` installed

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our [comment](https://github.com/electron/electron/issues/20676#issuecomment-545616347). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
