### ISSUE TITLE
Execute typescript file in child process within Electron

### ISSUE THREAD

**Issue by JayenLee** [electron/electron#20674]
How to excute typescrit file in child process within Electron?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
