### ISSUE TITLE
Confirm dialog before closing

### ISSUE THREAD

**Issue by AndiLeni** [electron/electron#20689]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

* Electron Version: 6.1.0
* Operating System: win 10

Hello,

I would like to show a confirm dialog when the user tries to close the window and there are unsaved changes.

I tried using the ``confirm()`` method when the ``onbeforeunload`` event fires, but chrome gives me ``Blocked confirm('TEST') during beforeunload`` as an error.
Is there a way to accomplish what I want with electron or do I need to look for a third-party plugin?

Regrads
Andi

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
