### ISSUE TITLE
session.cookies.set is broken in 7.0

### ISSUE THREAD

**Issue by sgd2z** [electron/electron#20688]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.0.0
* **Operating System:**
  * Windows 10 (1903)
* **Last Known Working Electron version:**
  * 6.0.12

### Expected Behavior
session.defaultSession.cookies.set(cookie) should set a cookie that can be then retrieved using session.defaultSession.cookies.get(filter)

### Actual Behavior
session.defaultSession.cookies.set doesnt seem to be doing anything.

### To Reproduce
Gist:
This gist logs an empty array in 7.0.0, In 6.0.12, it logs the cookie object that was set:
https://gist.github.com/sgd2z/af6abf3cea4bddb1cd62a3e8265c359f

**Comment by nornagon** [comment]
I believe the the issue here is with cookie expiry time. Can you try adding an expiry time to the cookie?

**Comment by sgd2z** [comment]
Thanks, adding an expirationDate made it work. The docs say the parameter is optional though.

**Comment by binux** [comment]
I noticed the same issue, per document
> If omitted then the cookie becomes a session cookie

With some test, seems I have to set `expirationDate` to 0 to set a session cookie, which is a breaking changing.

**Comment by Treverix** [comment]
Thanks for that ticket, saved my day! I was caching and restoring cookies and suddenly lost all session cookies because of that.

**Comment by a1q123456** [comment]
adding expirationDate: 0 to detail object sovled the problem, thx

**Comment by ChrisHSandN** [comment]
`session.cookies.set()` also fails with a blank `name`:

According to the documentation: https://electronjs.org/docs/api/cookies#cookiessetdetails
> name String (optional) - The name of the cookie. Empty by default if omitted.

```js
session.cookie.set({
  url: 'https://example.com',
});
// ❌ Error: Failed to parse cookie
```

```js
session.cookie.set({
  url: 'https://example.com',
  name: '',
});
// ❌ Error: Failed to parse cookie
```

```js
session.cookie.set({
  url: 'https://example.com',
  name: 'foo',
});
// ✔ success
```

According to the RFC6265 5.2: https://tools.ietf.org/html/rfc6265#section-5.2
>   5.  If the name string is empty, ignore the set-cookie-string entirely.

So I think the behavior (that a blank name is invalid) is correct and electron needs to make `name` a required field.

### Issue Details:

**Electron Version:**
7.1.1
**Operating System:**
Windows 10 (1903)
**Last Known Working Electron version:**
6

**Comment by sgd2z** [comment]
Th fix to this now causes cookies not to be set when expirationDate is 0. I have removed the expirationDate setting to 0 in our project but this might break other projects out there.
