### ISSUE TITLE
Cannot download headers & got dns network error for native modules

### ISSUE THREAD

**Issue by MatthD** [electron/electron#20687]
### Preflight Checklist
* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
6.0.0
* **Operating System:**
  *macOS 10.14.6*

try things that was [explain here](https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v6.0.0/node-v6.0.0-headers.tar.gz), the disturl seems ko 

### Actual Behavior
Error when installing native module, network error, cannot contact the domain 
Redirected to [this url](https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v6.0.0/node-v6.0.0-headers.tar.gz) which is not reachable

### To Reproduce

config in my zshrc:

```
export npm_config_target=6.0.0
export npm_config_arch=x64
export npm_config_target_arch=x64
# # # Télécharge les en-têtes pour Electron.
export npm_config_disturl=https://atom.io/download/atom-shell
# # # Indique à node-pre-gyp que l'on compile pour Electron.
export npm_config_runtime=electron
```

### Screenshots
![error](https://image.noelshack.com/fichiers/2019/43/2/1571776697-capture-d-ecran-2019-10-22-a-22-34-42.png)

### more info
I am not behind any proxy at all

**Comment by MarshallOfSound** [comment]
S3 is currently experiencing a DDOS attack on its DNS infrastructure

https://status.aws.amazon.com/
