### ISSUE TITLE
callback of webRequest.onHeadersReceived() has wrong type definition

### ISSUE THREAD

**Issue by chrisguttandin** [electron/electron#20701]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  v7.0.0
* **Operating System:**
  *  macOS 10.14.6
* **Last Known Working Electron version:**
  *  v6.x.x

### Expected Behavior

The type definitions of the `callback` function passed to the `listener` of [`webRequest.onHeadersReceived([filter, ]listener)`](https://electronjs.org/docs/api/web-request#webrequestonheadersreceivedfilter-listener) should match the docs.

### Actual Behavior

For some reason the `callback` is expecting the same argument as the callback of [`webRequest.onBeforeSendHeaders([filter, ]listener)`](https://electronjs.org/docs/api/web-request#webrequestonbeforesendheadersfilter-listener)

### To Reproduce

The following snippet is of course nonsense as it is doing nothing. But it doesn't compile when using TypeScript.
```typescript
session.defaultSession.webRequest.onHeadersReceived(({ responseHeaders }, callback) => callback({
    responseHeaders: {
        ...responseHeaders
    }
}));
```

```txt
error TS2345: Argument of type '{ responseHeaders: {} | { [x: string]: string; }; }' is not assignable to parameter of type 'CallbackResponse'. Object literal may only specify known properties, and 'responseHeaders' does not exist in type 'CallbackResponse'.
```

### Additional Information

I initially thought that this could be a naming collision. But as far as I can tell each callback has a distinct name in the [relevant doc file](https://github.com/electron/electron/blob/master/docs/api/web-request.md). 

Please let me know if this is something that can be fixed easily. I'm happy to provide a pull request for it.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
