### ISSUE TITLE
<webview> stopped working (in macOS Catalina?)

### ISSUE THREAD

**Issue by corwin-of-amber** [electron/electron#20704]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.1.0 / 7.0.0
* **Operating System:**
  * macOS 10.15 Catalina

### Expected Behavior
A `<webview>` tag should load a Web page using a separate renderer process, embedded in the current page. The element should have the methods described in https://electronjs.org/docs/api/webview-tag#methods.

### Actual Behavior
Nothing is shown, and the element does not have `loadURL`, `openDevTools` etc.

### To Reproduce
I tried:
 * The code in https://github.com/hokein/electron-sample-apps (webview/browser)
```sh
git clone https://github.com/hokein/electron-sample-apps
cd electron-sample-apps/webview/browser
electron .
```
[sample-app.zip](https://github.com/electron/electron/files/3762713/sample-app.zip)

 * The tutorial from https://www.tutorialspoint.com/electron/electron_webview.htm
```sh
unzip tutorial.zip
electron ./test.js
```
[tutorial.zip](https://github.com/electron/electron/files/3762715/tutorial.zip)

### Screenshots
<img width="912" alt="Screen Shot 2019-10-23 at 16 58 59" src="https://user-images.githubusercontent.com/704372/67400515-6b9fd280-f5b6-11e9-9104-b0d9f2041a84.png">

**Comment by MarshallOfSound** [comment]
According to https://electronjs.org/docs/api/webview-tag#enabling `webviewTag` is disabled by default, you need to opt in to use a webview

**Comment by corwin-of-amber** [comment]
It is indeed written there. A code snippet would go a long way though.
