### ISSUE TITLE
Electron 7, disable-gpu flag no longer working

### ISSUE THREAD

**Issue by t57ser** [electron/electron#20702]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.0.0
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 6

### Expected Behavior
GPU should be disabled and the chrome window should have no "Intermediate D3D Window" child

### Actual Behavior
GPU is enabled

### To Reproduce
app.commandLine.appendSwitch("disable-gpu");

### Additional Information
It works when using app.disableHardwareAcceleration() but that has a different effect. See:
### Electron 7 with app.disableHardwareAcceleration():
![electron7](https://user-images.githubusercontent.com/10595986/67386085-9bd67980-f594-11e9-8889-9b4b6d17bcf1.PNG)
### Electron 6 with disable-gpu:
![electron 6](https://user-images.githubusercontent.com/10595986/67386140-b3adfd80-f594-11e9-84da-05155625665f.PNG)

**Comment by pushkin-** [comment]
I believe that something like this broke in Electron 5 and I had to do the following to work around this (not tested in Electron 7):

    app.disableHardwareAcceleration();
    app.commandLine.appendSwitch("disable-software-rasterizer");

**Comment by pushkin-** [comment]
Related issue [here](https://github.com/electron/electron/issues/14273#issuecomment-468755011).

Suggests adding the "in-process-gpu" switch. This does prevent the GPU process from starting, but the chrome://gpu page is a lot greener than I expected with all three options (`in-process-gpu`, `disable-software-rasterizer`, `app.disableHardwareAcceleration`)

This is also a problem in Electron 8.

**Comment by pushkin-** [comment]
Actually the green stuff makes sense, I just didn't understand what `in-process-gpu` actually does. I'm guessing that's not suitable for you.

**Comment by pushkin-** [comment]
Did some more investigation.

Passing the `--disable-gpu` and `--disable-software-rasterizer` switches to Chrome 80 prevents the GPU process from starting.

Passing these switches via `app.commandLine.appendSwitch` in addition to calling `app.disableHardwareAcceleration()` prevents the GPU process from starting in Electron 6.1.9 (latest Electron 6 patch), but stopped working in Electron 7.0.0-beta.1 (earliest Electron 7).

The Chromium version between the two Electron versions changed from 76.0.3809.146 to 78.0.3866.0. Maybe something in Chromium broke this.

When loading chrome://gpu in Electron 6 vs 7beta:
"Metal" disabled in 6; not present in 7
"Multiple Raster Threads" disabled in 6; enabled in 7
"Surface Control" disabled in 6; not present in 7
"Surface Synchronization" enabled in 6; not present in 7
"WebGL/GL2" disabled in 6; "software only, hardware acceleration unavailable" in 7

**Comment by pushkin-** [comment]
It looks like as of Electron 9:
```
app.disableHardwareAcceleration();
app.commandLine.appendSwitch("disable-software-rasterizer");
```

successfully prevent the GPU process from spawning. Could someone double check this?

The `disable-gpu` switch still doesn't do that, so I guess the main issue remains.

**Comment by t57ser** [comment]
The flag seems to be working again,
latest 8: not working
latest 9, 10, 11: working

**Comment by pushkin-** [comment]
@t57ser For me, it that switch still doesn't turn off the GPU process in Electron 11.

**Comment by t57ser** [comment]
@pushkin- That's weird, this is the code I tried:
```
const electron = require("electron");
const path = require("path");

const init = () => {
	let browserWindow2 = new electron.BrowserWindow({
		show: true,
		x: 500,
	});

	browserWindow2.webContents.loadURL("http://www.google.com").then(() => {
	});
};
electron.app.commandLine.appendSwitch("disable-gpu");
electron.app.on("ready", () => {
	init();
});
```
I see that no gpu process spawned.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by pushkin-** [comment]
follow [here](https://github.com/electron/electron/issues/28164) for updates
