### ISSUE TITLE
Electron 7 webSecurity setting not working

### ISSUE THREAD

**Issue by Annihil** [electron/electron#20710]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
 7.0.0
* **Operating System:**
  macOS Mojave 10.14.6
* **Last Known Working Electron version:**
6.X

### Expected Behavior
webSecurity set to false should allow CORS

### Actual Behavior
Chrome still enforces CORS with webSecurity set to false

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

**Comment by natearmagost** [comment]
@sofianguy 

[Fork](https://github.com/natearmagost/electron-quick-start-v7-api-failures)

An express API at port 8000.

`webSecurity: false` seems to fail. If I leave off webSecurity completely, it seems to work.

There is also a v6 branch, but you have to remove and reinstall node_modules.

**Comment by AhadCove** [comment]
I just ran into this issue as well after updating to electron 7.0.0

**Comment by hacdias** [comment]
Same issue here!

**Comment by alitaheri** [comment]
We noticed this after upgrading electron v7-beta from beta-3 to beta-7. and it still happens on the released version (v7.0.0).

**Comment by dragonpiper** [comment]
7.0.1 seems to have fixed it for me

**Comment by hacdias** [comment]
Fixed for me too!

**Comment by sofianguy** [comment]
closing as this is reported as fixed

**Comment by ishowshao** [comment]
v9.0.1 not working

**Comment by bobmoff** [comment]
Same here but with v9.0.2

**Comment by VitruxPT** [comment]
Same issue here with v9.0.2

**Comment by Quentin-Lamotte** [comment]
Same here with v9.0.4.

Using `app.commandLine.appendSwitch('disable-web-security');` as a workaround works for now.
