### ISSUE TITLE
localstorage size limit

### ISSUE THREAD

**Issue by Inomezi** [electron/electron#20725]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  2.0.18
* **Operating System:**
  macOS 10.13.6
* **Last Known Working Electron version:**
  7.0.0

### Actual Behavior
When set big item to localstorage getting error VM893:1 Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'data' exceeded the quota.
    at <anonymous>:1:14

### To Reproduce
localStorage.setItem('data', (new Array(11*1024*1000)).join("x"))

### Additional Information

Please fix it on this version (2.0.18), because I can’t work on the versions above, there are a lot of bugs on them, for example, cannot open the browser, can not specify the path to the folder, cannot open the context menu, etc. And when I update the version to fix the localstorage limit, I get new bugs that disable my functionality

or tell me how can I fix it myself, thanks

**Comment by MarshallOfSound** [comment]
Electron `2.0.18` is EOL and is no longer supported.

If you have specific bugs on Electron 7 please raise them on this repository, please be aware that there are API changes between Electron 2 and 7 that may impact you during the upgrade process.

**Comment by miniak** [comment]
https://github.com/electron/electron/blob/master/docs/api/breaking-changes.md
