### ISSUE TITLE
Error installing on RPi4

### ISSUE THREAD

**Issue by DevinKott-KA** [electron/electron#20723]
### Update 2
@xiaoshan5733 has found a solution for the time being (located below in the comments). For visibility, I'll post it here:

> I solved the problem, you should config like this in your ~/.npmrc file:
```
arch=armv7l
```
> You can get arch from `uname -m`

I've tested this and can confirm that I'm able to proceed past the error and run the quick start application. However, I'm keeping this issue open until a developer responds to indicate whether this issue is still relevant to development and if it's intended behavior.

### Update
Just tested on a fresh SD-card install of the latest Raspbian. Made sure to run `sudo apt update && sudo apt full-upgrade`, downloaded the latest version of node (`v13.0.1`) and then tried installing via `npm install --save-dev electron`. Still have the same problem. Raspberry Pi 4, 16 GB MicroSD, fresh install

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  Cannot install
* **Operating System:**
  Raspbian, latest sept. build
* **Last Known Working Electron version:**
 None

### Expected Behavior
I expect to be able to install electron.

### Actual Behavior
I receive a HTTPError -- Response code 404 (Not Found).

### To Reproduce

1. Run `git clone https://github.com/electron/electron-quick-start`
2. CD into the directory: `cd electron-quick-start`
3. Run npm install: `npm install`

### Screenshots
[Screenshot of output](https://gyazo.com/cb7b3905b3ce24eddf0dc2626cbfdd13)

### Additional Information

- `node -v`: `v10.17.0`
- `npm -v`: `6.11.3`
- I've tried deleting `node_modules/` and rerunning `npm install`.
- Install seems to go through while using `yarn` but when starting the program it spits out: `Your install of electron is incorrect. Please delete 'node_modules/electron' and run 'npm install' again.` (or something of that nature).
- I've run `sudo apt update && sudo apt upgrade -y`, didn't help
- I'm on a hardwire connection which is working fine. The internet works fine on my Pi (I can go into chromium and browse as well as `ping` sites)

**Comment by wonderlandpark** [comment]
I works find on Ubuntu Mate in Raspi. I think it is issue for raspbian

**Comment by DevinKott-KA** [comment]
@wonderlandpark Interesting. Thanks for the comment.

**Comment by zhonggithub** [comment]
same issue  in my mac book pro. os is 10.15 .   node version: 12.13.0
![image](https://user-images.githubusercontent.com/17545551/67821242-48fe4400-faf7-11e9-87ad-120c41e3c65e.png)

**Comment by Bijzorg-Tim** [comment]
Having the same issue. Any solutions?

**Comment by Hypsie** [comment]
Having the same issue on raspbian :'(

**Comment by DevinKott-KA** [comment]
@Bijzorg-Tim @Hypsie Have not found anything yet. Still waiting for a response here from one of the devs.

**Comment by xiaoshan5733** [comment]
Same issue toooooo~

**Comment by xiaoshan5733** [comment]
I solved the problem, you should config like this in your ~/.npmrc file:

```
arch=armv7l
```

You can get arch from `uname -m`

**Comment by DevinKott-KA** [comment]
@xiaoshan5733 Updated OP with your response. Thanks!

**Comment by AstroGD** [comment]
I had the exact same error today. Thank you very much for the solution :) This helped a lot after hours of searching and trying to resolve the issue

**Comment by DevinKott-KA** [comment]
> 
> 
> I had the exact same error today. Thank you very much for the solution :) This helped a lot after hours of searching and trying to resolve the issue

Lets hope one of the dev's picks up the task soon!

**Comment by kokufu** [comment]
I got the same error on RPi3 and found the cause.

In `install.js`, `process.arch` is used.
Its value is `arm` on RPi, so it tries to download 
https://github.com/electron/electron/releases/download/v7.1.2/electron-v7.1.2-linux-arm.zip instead of 
https://github.com/electron/electron/releases/download/v7.1.2/electron-v7.1.2-linux-armv7l.zip

electron/install.js L.31
```js
downloadArtifact({
  version,
  artifactName: 'electron',
  force: process.env.force_no_cache === 'true',
  cacheRoot: process.env.electron_config_cache,
  platform: process.env.npm_config_platform || process.platform,
  arch: process.env.npm_config_arch || process.arch
}).then((zipPath) => extractFile(zipPath)).catch((err) => onerror(err))
```

Before electron v6, just `process.env.npm_config_arch` was used.
```js
  arch: process.env.npm_config_arch,
```

If it's `undefined`, `getNodeArch()` has been called in the download function, then we get the correct architecture name `armv7l`.

electron/get/dist/cjs/utils.js
```js
function getNodeArch(arch) {
    if (arch === 'arm') {
        switch (process.config.variables.arm_version) {
            case '6':
                return uname();
            case '7':
                return 'armv7l';
            default:
                break;
        }
    }
    return arch;
}
```

So to set  `process.env.npm_config_arch` is the only way to avoid this problem currently for us user. You can set it as command line option instead of modifying `~/.npmrc`.
```bash
npm install --arch=armv7l electron
```
