### ISSUE TITLE
Cannot provide path to directory

### ISSUE THREAD

**Issue by Inomezi** [electron/electron#20724]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  7.0.0
* **Operating System:**
  macOS 10.13.6
* **Last Known Working Electron version:**
  2.0.9

### Expected Behavior
Need select path to directory 

### Actual Behavior
Getting error: Uncaught (in promise) TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type object

### To Reproduce
remote.dialog.showOpenDialog({properties: ['openDirectory']})[0]

**Comment by codebytere** [comment]
@Inomezi this function returns a Promise in v7 per documentation - your syntax is not correct and should instead be:
```js
const { remote } = require('electron')

remote.dialog.showOpenDialog({
  properties: ['openDirectory']
}).then(ret => {
  console.log(ret.filePaths)
})
```
