### ISSUE TITLE
electron always "Electron failed to install correctly, please delete node_modules/electron and try installing again"

### ISSUE THREAD

**Issue by WingDust** [electron/electron#20731]
![image](https://user-images.githubusercontent.com/45911286/67533959-82514100-f6fe-11e9-95c4-275e1cbefeb0.png)

![image](https://user-images.githubusercontent.com/45911286/67533980-9d23b580-f6fe-11e9-9183-c4b668db73d3.png)

![image](https://user-images.githubusercontent.com/45911286/67533994-af9def00-f6fe-11e9-8e51-2b5fe43b3d06.png)

![image](https://user-images.githubusercontent.com/45911286/67534099-25a25600-f6ff-11e9-9a6c-8cfe60a85a0a.png)

![image](https://user-images.githubusercontent.com/45911286/67534124-394dbc80-f6ff-11e9-9cca-1c92ab1e5058.png)

**Comment by istriver** [comment]
I have the same problem,but electron 6 works well in my computer

**Comment by PeachT** [comment]
It happened to me, too.

**Comment by leon-o** [comment]
The path.txt is missing.
Try to run  `node node_modules/electron/install.js`. It should be run automaticlly after you installed electron.

I have the same problem and I run the install.js many times. It seems that function 'downloadArtifact' took so much time that it failed to create path.txt.

**Comment by istriver** [comment]
> The path.txt is missing.
> Try to run `node node_modules/electron/install.js`. It should be run automaticlly after you installed electron.
> 
> I have the same problem and I run the install.js many times. It seems that function 'downloadArtifact' took so much time that it failed to create path.txt.
> 
> https://github.com/electron/electron/blob/master/npm/install.js#L31


Yes,It causes this problem,but  I failed to download `electron-v7.0.0-win32-x64.zip` through `install.js`. Eventually,  I download `electron-v7.0.0-win32-x64.zip` from https://npm.taobao.org/mirrors/electron/7.0.0/ ,and unzip it into `node_modules\electron\`, then create `path.txt` file with text `electron.exe` in that directory.Finally,I launched electron@7.0.0. It is the network that causes the problem(electron6 has a different function to download,and it might could download from a mirror).I also find the incomplete cache file in  my computer。Is it possible to set a mirror ?

**Comment by szhielelp** [comment]
> > The path.txt is missing.
> > Try to run `node node_modules/electron/install.js`. It should be run automaticlly after you installed electron.
> > I have the same problem and I run the install.js many times. It seems that function 'downloadArtifact' took so much time that it failed to create path.txt.
> > https://github.com/electron/electron/blob/master/npm/install.js#L31
> 
> Yes,It causes this problem,but I failed to download `electron-v7.0.0-win32-x64.zip` through `install.js`. Eventually, I download `electron-v7.0.0-win32-x64.zip` from https://npm.taobao.org/mirrors/electron/7.0.0/ ,and unzip it into `node_modules\electron\`, then create `path.txt` file with text `electron.exe` in that directory.Finally,I launched electron@7.0.0. It is the network that causes the problem(electron6 has a different function to download,and it might could download from a mirror).I also find the incomplete cache file in my computer。Is it possible to set a mirror ?

Got totally same error.....

**Comment by lutianxiong** [comment]
i made it!

1. npm install electron -g
2. get error EPERM: operation not permitted, lstat 'C:\Users\XXXX\AppData\Local\Temp\electron-download-eQhWL8\electron-v7.1.1-win32-x64.zip
3. download the package from this link https://github.com/electron/electron/releases/download/v7.1.1/electron-v7.1.1-linux-x64.zip
4. move to C:\Users\XXXX\AppData\Roaming\npm\node_modules\electron
5. edit install.js, comment downloadArtifact and add extractFile('./electron-v7.1.1-win32-x64.zip');
![微信图片_20191114171001](https://user-images.githubusercontent.com/42662202/68842633-a1416280-0701-11ea-9018-4e63e5c4cc94.png)
6. node install.js
7. run electron in the terminal

**Comment by ifreann** [comment]
@lutianxiong thank you, that actually worked. To clarify for anyone else following your instructions, add a step "3.5" where you add the downloaded Electron .zip to C:\Users\XXXX\AppData\Roaming\npm\node_modules\electron

**Comment by binojvr** [comment]
> * de install.js
> * run electron in the terminal
Step 3: download the package from this link https://github.com/electron/electron/releases/download/v7.1.1/electron-v7.1.1-linux-x64.zip

Why its linux version? is it a typo?

**Comment by SGissubel** [comment]
Is an actual fix for this in the pipeline? It would be nice for the actual issue to be resolved - instead of just work-arounds.

**Comment by Keith-CY** [comment]
Actually the `install.js` didn't run as expected, then I manually add the dist file from https://npm.taobao.org/mirrors/electron/7.1.11/ into the `node_modules/electron/dist` and change launch method `getElectronPath` in the `node_modules/electron/index.js` to return the `./dist/Electron.app/Contents/MacOS/Electron`.

**Comment by appurist** [comment]
I have this problem with the 8.0.0 release, after upgrading electron from 6.1.

I have two government projects in strict automated environments where packages referenced just need to work.  The approach of issuing commands, manually copying files around from older versions etc just isn't a practical solution of any kind for me.

Is the only official supported workaround for this problem to revert to an older 7.x version? Or is there an 8.0.1 update coming that addresses this, and if so, what is the timeline on that?

**Comment by c690554125** [comment]
I download the zip from the taobao mirror, and move the zip to `node_modules/electron`, then modify the logic that exec the zip instead of download the zip, it's ok, but some minitues later, the error is happend again. And I check the `node_modules/electron/install.js`, what I modified logic is disappeard. 😢

**Comment by MGYH** [comment]
> I download the zip from the taobao mirror, and move the zip to `node_modules/electron`, then modify the logic that exec the zip instead of download the zip, it's ok, but some minitues later, the error is happend again. And I check the `node_modules/electron/install.js`, what I modified logic is disappeard. 😢 It's version is 8.0.0.
I solved it. I used yarn, and I find this file in the "C:\Users\local\AppData\Local\Yarn\Data\global\node_modules\electron". 
1. If your network is slow yarn global add install --verbose electron, The terminal will display the download progress. But  I download failed  “HTTPError: Response code 404 (Not Found) for https://npm.taobao.org/mirrors/electron/v8.0.1/electron-v8.0.1-win32-x64.zip"
2. I found it on 'https://github.com/electron/electron/releases/v8.0.1/'，you can change the version
"https://github.com/electron/electron/releases/v8.0.0/"
3. According to @lutianxiong, move to C:\Users\local\AppData\Local\Yarn\Data\global\node_modules\electron
edit install.js, comment downloadArtifact and add extractFile('./electron-v7.1.1-win32-x64.zip');
微信图片_20191114171001
4.node install.js
5.run electron in the terminal
6.If you install electron in your project before you finish the above, you can use 3,4,5 to solve it, of reinstall.

My english is poor, hope i can help you

**Comment by MGYH** [comment]
> I download the zip from the taobao mirror, and move the zip to `node_modules/electron`, then modify the logic that exec the zip instead of download the zip, it's ok, but some minitues later, the error is happend again. And I check the `node_modules/electron/install.js`, what I modified logic is disappeard. 😢 It's version is 8.0.0.
I solved it. I used yarn, and I find this file in the "C:\Users\local\AppData\Local\Yarn\Data\global\node_modules\electron". 
1. If your network is slow yarn global add install --verbose electron, The terminal will display the download progress. But  I download failed  “HTTPError: Response code 404 (Not Found) for https://npm.taobao.org/mirrors/electron/v8.0.1/electron-v8.0.1-win32-x64.zip"
2. I found it on 'https://github.com/electron/electron/releases/v8.0.1/'，you can change the version
"https://github.com/electron/electron/releases/v8.0.0/"
3. According to @lutianxiong, move to C:\Users\local\AppData\Local\Yarn\Data\global\node_modules\electron
edit install.js, comment downloadArtifact and add extractFile('./electron-v7.1.1-win32-x64.zip');
微信图片_20191114171001
4.node install.js
5.run electron in the terminal
6.If you installed electron in your project before you finish the above, you can use 3,4,5 to solve it, of  reinstall.

My english is poor, hope i can help you

**Comment by surlykke** [comment]
This is probably not relevant for anyone on this thread, but just in case:

I was getting 'Electron failed to install correctly, please...', and tried downgrading/upgrading electron, removing node_modules, removing ~/.cache/electron, running electron-fix, ... nothing worked. 

Turned out the issue was that I had
 
`target: "node"`

in webpack.config.js. Changing that to 

`target: "electron-renderer"` 

fixed my issue. 

Not the most enlightning error message I've come across.

**Comment by JackWCollins** [comment]
I was on `node v12.13.0` and seeing this error. I upgraded node to version `13.8.0` and that fixed the error for me. I hope this can help someone else!

**Comment by MGYH** [comment]
> I was on `node v12.13.0` and seeing this error. I upgraded node to version `13.8.0` and that fixed the error for me. I hope this can help someone else!

Thank you for your reply，I am using 12.16.1. Last week, I found a new project and everything worked. Now I am already using the project.

**Comment by MGYH** [comment]
> This is probably not relevant for anyone on this thread, but just in case:
> 
> I was getting 'Electron failed to install correctly, please...', and tried downgrading/upgrading electron, removing node_modules, removing ~/.cache/electron, running electron-fix, ... nothing worked.
> 
> Turned out the issue was that I had

I found a project last week and it worked. I don't know much about webpack, I will try your method later. thank you very much.

**Comment by AxelRothe** [comment]
> This is probably not relevant for anyone on this thread, but just in case:
> 
> I was getting 'Electron failed to install correctly, please...', and tried downgrading/upgrading electron, removing node_modules, removing ~/.cache/electron, running electron-fix, ... nothing worked.
> 
> Turned out the issue was that I had
> 
> `target: "node"`
> 
> in webpack.config.js. Changing that to
> 
> `target: "electron-renderer"`
> 
> fixed it.
> 
> Not the most enlightning error message I've come across.

This worked for me! Thanks!

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by egorzekov** [comment]
I faced this isssue on the project with `pnpm` package manager.

The best solution I've managed to find (besides replacing `pnpm`) is:
1. Create `npmrc` and add `node-linker=hoisted` (as stated in the official docs)
2. Add `"postinstall": "node ./node_modules/electron/install.js"` script to my `package.json`

**Comment by piotrgodycki** [comment]
@egorzekov thanks dude that one worked really well

**Comment by piotrgodycki** [comment]
> I faced this isssue on the project with `pnpm` package manager.
> 
> The root cause is explained here: [deltachat/deltachat-desktop#4490 (comment)](https://github.com/deltachat/deltachat-desktop/issues/4490#issuecomment-2597807847).
> 
> To solve it add the following config to your `package.json`:
> 
> ```
> "pnpm": {
>     "onlyBuiltDependencies": ["electron"]
> },
> ```

Thanks dude, this one worked really well!!!!

**Comment by LarryZhu-dev** [comment]
> 我在使用包管理器的项目中遇到了这个问题`pnpm`。
> 
> 根本原因解释如下：[deltachat/deltachat-desktop#4490 (评论)](https://github.com/deltachat/deltachat-desktop/issues/4490#issuecomment-2597807847)。
> 
> 要解决此问题，请将以下配置添加到您的`package.json`：
> 
> ```
> "pnpm": {
>     "onlyBuiltDependencies": ["electron"]
> },
> ```

it works , thank you very much

**Comment by abdullah-khanji** [comment]
1. pnpm approve-builds electron
2. pnpm rebuild electron
3. pnpm exec electron --version

**Comment by maxssilva** [comment]
> "pnpm": {
>     "onlyBuiltDependencies": ["electron"]
> },

um mês quebrando a cabeça com esse problema e a solução estava aqui debaixo do meu nariz...

**Comment by libertea1986** [comment]
> > > The path.txt is missing.
> > > Try to run `node node_modules/electron/install.js`. It should be run automaticlly after you installed electron.
> > > I have the same problem and I run the install.js many times. It seems that function 'downloadArtifact' took so much time that it failed to create path.txt.
> > > https://github.com/electron/electron/blob/master/npm/install.js#L31
> > 
> > 
> > Yes,It causes this problem,but I failed to download `electron-v7.0.0-win32-x64.zip` through `install.js`. Eventually, I download `electron-v7.0.0-win32-x64.zip` from https://npm.taobao.org/mirrors/electron/7.0.0/ ,and unzip it into `node_modules\electron\`, then create `path.txt` file with text `electron.exe` in that directory.Finally,I launched electron@7.0.0. It is the network that causes the problem(electron6 has a different function to download,and it might could download from a mirror).I also find the incomplete cache file in my computer。Is it possible to set a mirror ?
> 
> Got totally same error.....



create `path.txt` file with text just `electron.exe` in that file (not directory)!

**Comment by sulenchy** [comment]
I have this issue with Electron v38.1.2 in 2026. It happens only on Mac but worksnon Windows. Running `node node_modules/electron/install.js` works for me. Thanks

**Comment by appurist** [comment]
FYI: Tauri has matured now and leapfrogged Electron in terms of being a dependable solution, and thus a workaround to these weird Electron quirks like this one, along with the Window sizing bug that has plagued me for a decade now. Took me about 30 minutes to get Claude to port my Electron apps to Tauri and my DX is considerably better now.

**Comment by sulenchy** [comment]
Thanks @appurist. I will look it up.

**Comment by timomono** [comment]
> I faced this isssue on the project with `pnpm` package manager.
> 
> The root cause is explained here: [deltachat/deltachat-desktop#4490 (comment)](https://github.com/deltachat/deltachat-desktop/issues/4490#issuecomment-2597807847).
> 
> To solve it add the following config to your `package.json`:
> 
> ```
> "pnpm": {
>     "onlyBuiltDependencies": ["electron"]
> },
> ```

Thanks, it works for me!
This should be written in docs

**Comment by jacknkandy** [comment]
> i made it!
> 
> 1. npm install electron -g
> 2. get error EPERM: operation not permitted, lstat 'C:\Users\XXXX\AppData\Local\Temp\electron-download-eQhWL8\electron-v7.1.1-win32-x64.zip
> 3. download the package from this link https://github.com/electron/electron/releases/download/v7.1.1/electron-v7.1.1-linux-x64.zip
> 4. move to C:\Users\XXXX\AppData\Roaming\npm\node_modules\electron
> 5. edit install.js, comment downloadArtifact and add extractFile('./electron-v7.1.1-win32-x64.zip');
>    ![微信图片_20191114171001](https://user-images.githubusercontent.com/42662202/68842633-a1416280-0701-11ea-9018-4e63e5c4cc94.png)
> 6. node install.js
> 7. run electron in the terminal

For some reason the `extractFile` command was not working for me either (silently fails). So I manually extracted the files in the zip into the `dist` subfolder.

The last part I needed was to add a `path.txt` file (with `electron.exe` inside) into the electron node module folder. And got it working!

**Comment by MichaelHillcox** [comment]
I've experiences the same thing. I've used changed my node version from `24` to `22`, then `rm -rf node_modules`, `npm i` and now it's working just fine so I think it could be something to do with `extract-zip` and upon digging, I'd be pretty confident this is the root caused seeing as `extract-zip` hasn't updated in 6 years https://github.com/max-mapper/extract-zip/issues/154#issuecomment-4528735702

**Comment by AMIRALI-SAFARZADE** [comment]
Electron Binary Installation Fails on Windows with pnpm - Resolved
Summary: This guide addresses a previously encountered technical challenge with installing the Electron binary on Windows using pnpm. The issue, marked by errors such as Electron failed to install correctly and ENOENT: spawn ...\dist\electron.exe, has now been successfully resolved.

Problem Description:

The core issue was the failure of the Electron postinstall script within pnpm’s isolated installation environment. This prevented the necessary electron.exe binary from being downloaded and placed correctly, resulting in an incomplete node_modules.pnpm\electron@<VERSION>\node_modules\electron\dist directory.

Resolution Steps Taken:

The installation issue was overcome by performing the following steps manually:

Manual Binary Download: Download the specific Electron binary zip archive required for the project’s version and platform. For example, for Electron v31.7.7 on Windows 64-bit, you would download:
https://npmmirror.com/mirrors/electron/v31.7.7/electron-v31.7.7-win32-x64.zip

(Note: Replace v31.7.7 and electron-v31.7.7-win32-x64.zip with the correct version and platform if different).

Direct Extraction of Contents: Extract all files and folders from the downloaded zip archive directly into the Electron package’s dist folder. The correct path is typically:
<ProjectRoot>\node_modules\.pnpm\electron@<VERSION>\node_modules\electron\dist

(Example: C:\YourProject\node_modules\.pnpm\electron@31.7.7\node_modules\electron\dist).

It is crucial that electron.exe and other binary files reside directly within this dist directory.

Correct path.txt Creation: To fix the ENOENT error, create the path.txt file in the main Electron package directory (not inside dist). The content of this file must be exactly electron.exe without any extra characters. Use the following command in the Windows Command Prompt (cmd.exe):
<nul set /p ="electron.exe" > <PathToElectron>\path.txt

(Here, <PathToElectron> should be replaced with the full path to the Electron package’s root directory, e.g., C:\YourProject\node_modules\.pnpm\electron@31.7.7\node_modules\electron).

Outcome:

Following these manual steps, the Electron binary was correctly installed. The command pnpm exec electron --version then executed successfully, confirming the resolution of the installation failure.

Key Learnings:

When encountering ENOENT errors with Electron installations, always prioritize checking the dist directory for the electron.exe binary and validating the integrity of the path.txt file.
Utilizing the <nul set /p ="..." > command in cmd.exe is a reliable method for creating text files with precise content, free from unintended newline characters, which is critical for configuration files like path.txt.

<img width="1059" height="930" alt="Image" src="https://github.com/user-attachments/assets/86a22b1e-e1db-4578-8df9-678586380c4e" />
