### ISSUE TITLE
Electron Pacakging error - Operation not permitted, lstat

### ISSUE THREAD

**Issue by aruntech89** [electron/electron#20738]
Hi All,

Requirement:
We are building a desktop application using Electron & Python as business service to provide productivity tools to support our users.

### Issue Details

* **Electron Version:**
  * 
* **Operating System:**
    Windows 10 (1803) 
* **Last Known Working Electron version:**
  "electron": "^6.0.7"

### Expected Behavior

Our productivity tool desktop application in Win32 x64 as executable file.

### Actual Behavior

1) Using Electron-download we have downloaded the required binary in user\local\electron\cache

2) we have set electron_cache @ environment   variable to user\local\electron\cache

Electron packager creates random temp files in user\local\temp\electron-download which is not pointing to user\local\electron\cache.

### To Reproduce

**when we run the following command**
_electron-packager ./ --appname=UtilityTool --build-version=1.0.0 --download.cacheRoot=C:/Users/arun/AppData/Local/electron/Cache --no-asar --no-prune --platform=win32 --arch=x64 --icon=./images/UtilityTool.png --out ./dist/elenpm --overwrite_

**We are getting an issue**
PERM: operation not permitted, lstat 'C:\Users\arun\AppData**\Local\Temp\electron-download-wlbgwx\**electron-v6.0.7-win32-x64.zip'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 build-win32: electron-packager ./ --appname=UtilityTool --build-version=1.0.0 --download.cacheRoot=C:/Users/arun/AppData/Local/electron/Cache --no-asar --no-prune --platform=win32 --arch=x64 --icon=./images/UtilityTool.png --out ./dist/elenpm --overwrite
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 build-win32 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\arun\AppData\Roaming\npm-cache_logs\2019-10-24T06_17_59_536Z-debug.log

### Additional Information

**Part of dependency from package.json**

"devDependencies": {
    "electron": "^6.0.7",
    "electron-packager": "^14.0.6"
  },
  "dependencies": {
    "@electron/get": "^1.5.0",
    "debug": "^4.1.1",
    "python-shell": "^1.0.8",
    "rcedit": "^2.0.0",
    "requirejs": "^2.3.6",
    "sweetalert": "^2.1.2",
    "username": "^5.1.0"
  }

**Comment by codebytere** [comment]
This is probably not the right place to open this issue - please open this on [`electron-packager'](https://github.com/electron/electron-packager) instead. Thanks and good luck!
