### ISSUE TITLE
`setZoomFactor` is deprecated but documentation offers no explanation / is out of date

### ISSUE THREAD

**Issue by neopostmodern** [electron/electron#20741]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  * 7.0.0
* **Operating System:** 
  * Ubuntu 19.04 x64
* **Last Known Working Electron version:** 
  * 6.x

### Expected Behavior

Documentation should explain how to deal with / replace the deprecated call.

### Actual Behavior

Documentation suggests wrong usage.

### To Reproduce

I call 
```js
webContents.setZoomFactor(1.0);
```
and get 
```txt
(electron) 'setZoomFactor function' is deprecated and will be removed. Please use 'zoomFactor property' instead.
```
in the log.

### Additional Information

"Normal" people would search for ["electron zoomfactor"](https://www.startpage.com/do/dsearch?query=electron+zoomfactor&cat=web&pl=opensearch&language=english) and find [the webFrame documentation](https://electronjs.org/docs/api/web-frame) or maybe [the BrowserWindow documentation](https://electronjs.org/docs/api/browser-window#new-browserwindowoptions). (The latter not being useful for this scenario, the first suggesting the deprecated call.)

**Comment by miniak** [comment]
I think it's quite clear that you're supposed to use the `webContents.zoomFactor` property, which is documented here: https://electronjs.org/docs/api/web-contents#contentszoomfactor
