### ISSUE TITLE
Mouse events not working anywhere within Frameless window in Electron 7

### ISSUE THREAD

**Issue by StanHR** [electron/electron#20754]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.0.0

* **Operating System:**
  * Windows 10

I've used frame:false because I want to add a custom title-bar. Because of this, none of the mouse-events are being captured anywhere on the app UI.
Removing frame:false makes it work just fine.

### Expected Behavior
When I hover mouse over any element on the UI, the defined CSS properties must be applied.

### Actual Behavior
Apparently, the mouse events are not being captured. Nether the mouse hover, nor the click works.

**Comment by nelroid** [comment]
Hi, I got the same issue on Windows server 2012.
@rai-harshit  this issue set to closed. Is it solved?
