### ISSUE TITLE
webContents.login event not triggered in 7.0.0

### ISSUE THREAD

**Issue by binux** [electron/electron#20752]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.0.0
* **Operating System:**
  * macOS
* **Last Known Working Electron version:**
  * 6.1.2

### Expected Behavior
https://github.com/electron/electron/blob/v7.0.0/docs/api/web-contents.md#event-login triggered

### Actual Behavior
login event not triggered

### To Reproduce
run following code

```js
const {app, BrowserWindow} = require('electron')
app.once('ready', async () => {
  win = new BrowserWindow()
  app.on('login', console.log)
  win.webContents.on('login', console.log)
  win.webContents.once('did-finish-load', async () => {
    const html = await win.webContents.executeJavaScript('document.documentElement.innerHTML')
    console.log(html)
    app.quit()
  })
  await win.webContents.loadURL('https://httpbin.org/basic-auth/user/passwd')
})
```

**Comment by nornagon** [comment]
Yeah, unfortunately the 'login' event was a casualty of us refactoring on top of Chromium's new 'network service' code. It's currently just ... not attached at all. Whoops. https://github.com/electron/electron/blob/7-0-x/shell/browser/login_handler.cc#L37-L39

**Comment by sowelie** [comment]
Any thoughts on when this will be implemented? This is holding me back from updating to 7.x. Is there anything I can do to help with the fix?

**Comment by gavinkalika** [comment]
any movement on this getting fixed?
