### ISSUE TITLE
Support for double tap modifiers in globalShortcuts

### ISSUE THREAD

**Issue by danielravina** [electron/electron#20753]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

I'm trying to do something like this:
```
globalShortcut.register("Command+Command", callback);
```
But I'm getting this errors:
<img width="532" alt="Screen Shot 2019-10-25 at 10 36 39 PM" src="https://user-images.githubusercontent.com/3150871/67614903-a69e3380-f779-11e9-834f-00d3120f03c0.png">

### Proposed Solution

Not sure if WebKit can support that kind of abilities, but it would be great if this would be supported in Electron.

### Alternatives Considered

N/A

### Additional Information

I'm using Alfred app (not electron to my knowledge) and it does support a double-tap as a "hot key"
<img width="565" alt="Screen Shot 2019-10-25 at 10 39 57 PM" src="https://user-images.githubusercontent.com/3150871/67614928-ebc26580-f779-11e9-9398-df163bf8ce9e.png">

**Comment by miniak** [comment]
https://cs.chromium.org/chromium/src/ui/base/accelerators/accelerator.h?type=cs&sq=package:chromium&g=0&l=87

**Comment by danielravina** [comment]
thanks @miniak looks like a point in the right direction. would you know how to use the method in JS?

**Comment by miniak** [comment]
@danielravina it's not exposed to JS, this is just the Chromium API.

**Comment by LuRenJiasWorld** [comment]
Maybe you can try this package: https://github.com/wilix-team/iohook @danielravina

**Comment by danielravina** [comment]
Wow, you came from the heavens! Thank you it does the job with a few lines of code:

```js
let firstClick = null;

const onCmdPress = () => {
  if (firstClick && Date.now() - firstClick < 200)) {
      console.log('Cmd Double Pressed!')
      firstClick = null;
   } else {
      firstClick = Date.now();
   }
};

ioHook.registerShortcut([3675], onCmdPress);
ioHook.registerShortcut([3676], onCmdPress);
 ioHook.start();
```
