### ISSUE TITLE
Set cookie return undefined

### ISSUE THREAD

**Issue by Inomezi** [electron/electron#20755]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  7.0.0
* **Operating System:**
  macOS 10.13.6
* **Last Known Working Electron version:**
  2.0.18

### Expected Behavior
Loading web page with cookies
### Actual Behavior
Set cookies return undefined , and don't load web page

### To Reproduce
window.webContents.session.cookies.set({ url, name, value, domain, path: "/" }, error => {
//
})
window.webContents.session.cookies.set({ url, name, value, domain, path: "/" }).then( c => {
         console.log(c) // undefined
      }, (error) => {
         console.error(error)
})
Both variant don't working on version 7.0.0 , but first variant worked on version 2.0.18

**Comment by binux** [comment]
1. `cookies.set` is returning Promise<void> since 6.0.0 https://electronjs.org/releases/stable?version=6&page=4#release-notes-for-600
2. expirationDate is no longer optional in 7.0.0, which is reported https://github.com/electron/electron/issues/20688

**Comment by Inomezi** [comment]
> 1. `cookies.set` is returning Promise since 6.0.0 https://electronjs.org/releases/stable?version=6&page=4#release-notes-for-600
> 2. expirationDate is no longer optional in 7.0.0, which is reported #20688

Thank you, expirationDate helped me
