### ISSUE TITLE
Slow start up time

### ISSUE THREAD

**Issue by melker-github** [electron/electron#20765]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

Electron version: 7.0.0
Platform: Windows 10 32bit
I created an electron app. I followed a tutorial where the starup time for the app was instant. 

### Expected Behavior
I expected the app to open, ready to use, within seconds.

### Actual Behavior
When I start my app, it takes a good 30 second for the app to even show up. It then takes another 20 seconds for the content of the app to show up.

### Additional Information

Here is my code (only the main.js file):
const electron = require('electron');
const url = require('url');
const path = require('path');

const app = electron.app;
const BrowserWindow = electron.BrowserWindow;
const Menu = electron.Menu;
const ipcMain = electron.ipcMain;

// Set ENV
process.env.NODE_ENV = 'production';

// Windows
let mainWindow;
let addWindow;

// Listen for the app to be ready
app.on('ready', () => {

  // Create new window
  mainWindow = new BrowserWindow({
    title: 'Shopping List',
    webPreferences: {nodeIntegration: true}
});
  // Load the html file into window
  mainWindow.loadURL(url.format({
    // 'file://dirname/mainWindow.html'
    pathname: path.join(__dirname, 'mainWindow.html'),
    protocol: 'file:',
    slashes: true
  }));

  // Quit app when closed
  mainWindow.on('closed', () => {
    app.quit();
  })

  // Build menu from mainMenuTemplate (Cretaed below)
  const mainMenu = Menu.buildFromTemplate(mainMenuTemplate)
  // Insert menu
  Menu.setApplicationMenu(mainMenu)
});

// Handle create add window
function createAddWindow() {
  // Create new window
  addWindow = new BrowserWindow({
    width: 300,
    height: 200,
    title: 'Add Item',
    webPreferences: {nodeIntegration: true}

});
  // Load the html file into window
  addWindow.loadURL(url.format({
    // 'file://dirname/mainWindow.html'
    pathname: path.join(__dirname, 'addWindow.html'),
    protocol: 'file:',
    slashes: true
  }));

  // Garbage collection handle
  addWindow.on('close', () => {
    addWindow = null;
  })
}

// Catch item add
ipcMain.on('item:add', (e, item) => {
  mainWindow.webContents.send('item:add', item)
  addWindow.close();
});

// Create menu template
const mainMenuTemplate = [

  {
    label: 'File',
    submenu: [
      {
        label: 'Add Item',
        click() {
          createAddWindow();
        }
      },
      {
        label: 'Clear Items',
        click() {
          mainWindow.webContents.send('item:clear')
        }
      },
      {
        label: 'Quit',
        // If on mac: use command + Q, else use Ctrl + Q to quit
        accelerator: process.platform == 'darwin' ? 'Command+Q' : 'Ctrl+Q',
        click() {
          app.quit();
        }
      }
    ]
  }
];

// If mac, add empty object to menu
if (process.platform == 'darwin') {
  // Adding empty object to the beginning of array
  mainMenuTemplate.unshift({});
}

// Add developer tools if not in production
if (process.env.NODE_ENV !== 'production') {
  mainMenuTemplate.push({
    label: 'Developer Tools',
    submenu: [
      {
        label: 'Toggle DevTools',
        accelerator: process.platform == 'darwin' ? 'Command+I' : 'Ctrl+I',
        click(item, focusedWindow) {
          focusedWindow.toggleDevTools();
        }
      },
      {
        role: 'reload'
      }
    ]
  })
}

**Comment by Inomezi** [comment]
I have the same problem. When i don't include my js file it shows faster, but still load slower than before, and if include main.js file - it takes 5-10 second

**Comment by melker-github** [comment]
What do you mean by not including the js file?

**Comment by Inomezi** [comment]
> What do you mean by not including the js file?

You have js file that you including from html, if you will not include it - program will start faster. Maybe troubles in code, or smth else, but versions older 7.0 haven't this problem

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
