### ISSUE TITLE
WebGL Performance Issues with WebView (Electron 7.0)

### ISSUE THREAD

**Issue by nwittwer** [electron/electron#20766]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.0.0
* **Operating System:**
  * macOS 10.15 Catalina (19A602)
* **Last Known Working Electron version:**
  * ~6.0.4~ 6.1.2

### Expected Behavior
Smooth scrolling/panning/zooming with multiple `WebView` tags loaded.

### Actual Behavior
Delayed, choppy rendering to the point where the shape of the `WebView` content ghosts the actual content that's rendered (see GIF below). Multiple WebGL errors appear in the logs about texture and invalid mailbox name? Also occasionally saw an error like "Unable to create WebGL, using native GL instead. This will be slow." 

Note: I'm not directly interacting with WebGL or `Canvas`, but rather manipulating the scale/position of a `div` containing multiple `WebView` elements with CSS Transforms.

### To Reproduce
```sh
$ git clone https://github.com/nwittwer/reflex.git -b bug/webgl-electron7
$ npm install
$ npm start
```

### Screenshots

Example of the content ghosting that occurs when moving around quickly. Tried with Electron 6.1.2 on Catalina and had no issues, so seems like something changed between 6.1.2 and 7.0 that affects this.
![example](https://user-images.githubusercontent.com/6360459/67635527-bf692f00-f8c8-11e9-945c-357c9664e9d5.gif)

<img width="672" alt="Screen Shot 2019-10-27 at 2 26 26 PM" src="https://user-images.githubusercontent.com/6360459/67635462-dc513280-f8c7-11e9-923f-fa180a9b660a.png">

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
