### ISSUE TITLE
Enable desktop capturer specs disabled in master

### ISSUE THREAD

**Issue by deepak1556** [electron/electron#20771]
https://github.com/electron/electron/pull/20649/commits/ccf65f279dc22015921794bdf9938a7ef22c423e

https://github.com/electron/electron/pull/20314/commits/7c589aea808971bc6273ae7372fffa17a60fb6a9

https://github.com/electron/electron/pull/20314/commits/fee13e102c14418c6eaa88a5ca056d874302c251

/cc @electron/wg-upgrades

**Comment by nornagon** [comment]
NB these are still disabled:

https://github.com/electron/electron/blob/e589e9b259ecad5a2f2f47f0b8d40618d1c54601/spec-main/api-desktop-capturer-spec.ts#L159-L160

https://github.com/electron/electron/blob/e589e9b259ecad5a2f2f47f0b8d40618d1c54601/spec-main/api-desktop-capturer-spec.ts#L25-L26

https://github.com/electron/electron/blob/e589e9b259ecad5a2f2f47f0b8d40618d1c54601/spec-main/api-desktop-capturer-spec.ts#L36-L37

https://github.com/electron/electron/blob/e589e9b259ecad5a2f2f47f0b8d40618d1c54601/spec-main/api-desktop-capturer-spec.ts#L45
