### ISSUE TITLE
Enable OSR in master and 8-x-y

### ISSUE THREAD

**Issue by deepak1556** [electron/electron#20772]
https://github.com/electron/electron/blob/master/build/args/all.gn#L29

/cc @electron/wg-upgrades

**Comment by mceIdo** [comment]
initiation crash investigation in this fork https://github.com/mceSystems/electron/tree/electron-8-osr-fix
We'll submit a PR if and when we fix this

**Comment by jkleinsc** [comment]
Resolved via #22160.
