### ISSUE TITLE
install error on mac

### ISSUE THREAD

**Issue by yunyanU** [electron/electron#20776]
sudo npm install -g electron
Password:
/Users/yan/npm-global/bin/electron -> /Users/yan/npm-global/lib/node_modules/electron/cli.js

> core-js@3.3.4 postinstall /Users/yan/npm-global/lib/node_modules/electron/node_modules/core-js
> node postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> electron@7.0.0 postinstall /Users/yan/npm-global/lib/node_modules/electron
> node install.js

(node:27529) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdtemp '/Users/yan/npm-global/lib/node_modules/electron/electron-download-bqEadZ'
(node:27529) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27529) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
+ electron@7.0.0
added 86 packages from 89 contributors in 14.224s

**Comment by 1by** [comment]
Try just
npm i —save-dev electron
https://electronjs.org/docs/tutorial/installation

**Comment by popsapple** [comment]
How to fixed it? I have same problem.
