### ISSUE TITLE
Windows 10 / VS 2019 build error: Perfetto patches not applied

### ISSUE THREAD

**Issue by samkuhn** [electron/electron#20777]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
8.0.0-nightly.20191026 (Building from source)
* **Operating System:**
Windows 10 (1809)

### Expected Behavior
Perfetto patches in src/electron/patches/perfetto to be applied by apply_all_patches.py during the post hook phase of gclient sync.

### Actual Behavior
The patch "metatrace_remove_memset_and_trivial_ctor_assumption.patch" is not applied and the subsequent build fails.

### To Reproduce
Install and build electron from source on Windows 10 / VS 2019 using instructions provided.

### Additional Information
The Perfetto patch added in [this PR](https://github.com/electron/electron/pull/20465) is not applied leading to this build error (VS 2019 Community Edition):

`
FAILED: obj/third_party/perfetto/src/base/base/metatrace.obj
..\..\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe /nologo /showIncludes "-imsvc..\..\..\..\..\..\..\..\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\ATLMFC\include" "-imsvc..\..\..\..\..\..\..\..\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include" "-imsvc..\..\..\..\..\..\..\..\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-imsvc..\..\..\..\..\..\..\..\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-imsvc..\..\..\..\..\..\..\..\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-imsvc..\..\..\..\..\..\..\..\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-imsvc..\..\..\..\..\..\..\..\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-imsvc..\..\..\..\..\..\..\..\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -DUSE_AURA=1 "-DCR_CLANG_REVISION=\"372314-13bdae85-2\"" -D_HAS_NODISCARD -D_HAS_EXCEPTIONS=0 -DCOMPONENT_BUILD -D__STD_C -D_CRT_RAND_S -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_ATL_NO_OPENGL -D_WINDOWS -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -DPSAPI_VERSION=2 -DWIN32 -D_SECURE_ATL -D_USING_V110_SDK71_ -DWINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP -DWIN32_LEAN_AND_MEAN -DNOMINMAX -D_UNICODE -DUNICODE -DNTDDI_VERSION=NTDDI_WIN10_RS2 -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00 -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -D_HAS_ITERATOR_DEBUGGING=0 -DPERFETTO_IMPLEMENTATION -I../.. -Igen -I../../third_party/perfetto -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -Xclang -mllvm -Xclang -instcombine-lower-dbg-declare=0 -fcomplete-member-pointers /Gy /FS /bigobj /utf-8 /Zc:sizedDealloc- /X -fmsc-version=1916 /guard:cf,nochecks /Zc:dllexportInlines- -m64 /Brepro -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes /W4 -Wimplicit-fallthrough -Wthread-safety -Wextra-semi /WX /wd4091 /wd4127 /wd4251 /wd4275 /wd4312 /wd4324 /wd4351 /wd4355 /wd4503 /wd4589 /wd4611 /wd4100 /wd4121 /wd4244 /wd4505 /wd4510 /wd4512 /wd4610 /wd4838 /wd4995 /wd4996 /wd4456 /wd4457 /wd4458 /wd4459 /wd4200 /wd4201 /wd4204 /wd4221 /wd4245 /wd4267 /wd4305 /wd4389 /wd4702 /wd4701 /wd4703 /wd4661 /wd4706 /wd4715 -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-xor-used-as-pow -Wno-c99-designator -Wno-reorder-init-list -Wno-final-dtor-non-final-class -Wno-sizeof-array-div /Od /Ob0 /GF /Z7 -gcodeview-ghash -fno-standalone-debug /MDd -Xclang -add-plugin -Xclang find-bad-constructs -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wno-undefined-bool-conversion -Wno-tautological-undefined-compare /TP /wd4577 /GR- /c ../../third_party/perfetto/src/base/metatrace.cc /Foobj/third_party/perfetto/src/base/base/metatrace.obj /Fd"obj/third_party/perfetto/src/base/base_cc.pdb"
../../third_party/perfetto/src/base/metatrace.cc(87,3): error: static_assert failed due to requirement 'std::is_trivially_constructible<perfetto::metatrace::Record>::value' "Record must be trivial"
  static_assert(PERFETTO_IS_TRIVIALLY_CONSTRUCTIBLE(Record) &&
  ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
` 

Presumably because the perfetto folder is missing from src/electron/patches/config.json?

```json
{
  "src/electron/patches/chromium": "src",

  "src/electron/patches/quiche": "src/net/third_party/quiche/src",

  "src/electron/patches/boringssl": "src/third_party/boringssl/src",

  "src/electron/patches/v8":  "src/v8",

  "src/electron/patches/node": "src/third_party/electron_node"
}
```

**Comment by samkuhn** [comment]
I can confirm that manually applying "metatrace_remove_memset_and_trivial_ctor_assumption.patch" to Perfetto fixes the build error.

**Comment by deepak1556** [comment]
Yup noticed this while https://github.com/electron/electron/pull/20649, it should be fixed when that PR is merged today. Thanks!
