### ISSUE TITLE
Electron delivers identical screen ID in dual screen setup

### ISSUE THREAD

**Issue by berkon** [electron/electron#20779]
### Issue Details

* **Electron Version:**
  * 5.0.1
* **Operating System:**
  * Debian 9 (Linux)
* **Last Known Working Electron version:**
  * Unknown

### Expected Behavior
**screen.getAllDisplays()** should deliver a unique ID for each attached display.

### Actual Behavior
**screen.getAllDisplays()** delivers an identical ID (21442169663798852) for display model Samsung DM55. We have this model in different meeting rooms and I'm always getting the same ID. This post: https://github.com/electron/electron/issues/6899#issuecomment-241296007 states that the ID is derived from the model name an is just a hash. But I don't know whether that's still correct (the post is quite old) because we also have other display types (two identical models) which deliver different IDs). So there must be another factor which influences the hash creation.

So the question is how this ID is calculated, and whether this can somehow be improved to make sure that the IDs are distinct in any case.

### To Reproduce
Unfortunately these screen model is required for reproducing the issue. Thus it makes no sense to add code here. In case somebody indeed has such devices, it is just required to call:

**screen.getAllDisplays()**

and look at the returned ID in the JSON structure.

**Comment by adammeyer** [comment]
I'm seeing this as well with Electron 6, Manjaro 18.1.

**Comment by adammeyer** [comment]
Here's a hack I wrote to remove duplicate ids.

```js
let displays = screen.getAllDisplays().map((display, index, allDisplays) => {
  const displaysWithThisId = allDisplays.filter(d => d.id === display.id).length;
  if(displaysWithThisId > 1){
    display.id = index;
  }

  return display;
});

**Comment by cheynewallace** [comment]
Any update on this one? Iv just hit this issue too with a customer.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
