### ISSUE TITLE
Fail to install Electron 7

### ISSUE THREAD

**Issue by duanhx** [electron/electron#20774]
I cannot intall electron 7. But version 6 is good.

C:\Users\Administrator>electron -v

C:\Users\Administrator>"node"  "G:\nodejs\node_global\\node_modules\electron\cli.js" -v
G:\nodejs\node_global\node_modules\electron\index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (G:\nodejs\node_global\node_modules\[4melectron[24m\index.js:14:11)
    at Object.<anonymous> (G:\nodejs\node_global\node_modules\[4melectron[24m\index.js:18:18)
[90m    at Module._compile (internal/modules/cjs/loader.js:956:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:812:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:724:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:849:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:74:18)[39m
    at Object.<anonymous> (G:\nodejs\node_global\node_modules\[4melectron[24m\cli.js:3:16)
[90m    at Module._compile (internal/modules/cjs/loader.js:956:30)[39m

**Comment by SunChaoran** [comment]
same error

**Comment by hayatesa** [comment]
Just delete node_modules and try again. Perhaps you need VPN or cnpm in China.

**Comment by DevinKott-KA** [comment]
Architecture and other system information would be helpful, especially with helping someone else replicate the error.

**Comment by duanhx** [comment]
I tried cnpm at first, but not working as well.
My OS is Windows 10 in zh_CN.

**Comment by hayatesa** [comment]
> I tried cnpm at first, but not working as well.
> My OS is Windows 10 in zh_CN.

I tried several times and finally installed 7.0.0 perfectly in win10 64bit. The version of my Node is 12.x(32bit) and npm is 6.x. If you need help, you can contact me by hayatesa@live.cn.

**Comment by zhonggithub** [comment]
same error in my mac os 10.15. but electron@6 is success

**Comment by Auxxxxlx** [comment]
Download electron manually, then modify `install.js`.

```javascript
// // downloads if not cached
// downloadArtifact({
//   version,
//   artifactName: "electron",
//   force: process.env.force_no_cache === "true",
//   cacheRoot: process.env.electron_config_cache,
//   platform: process.env.npm_config_platform || process.platform,
//   mirror: "https://npm.taobao.org/mirrors/electron/", // 多了这句
//   arch: process.env.npm_config_arch || process.arch
// })
//   .then(zipPath => extractFile(zipPath))
//   .catch(err => onerror(err));

extractFile("<electron_zip_path>");
// unzips and makes path.txt point at the correct executable
function extractFile(zipPath) {
  extract(zipPath, { dir: path.join(__dirname, "dist") }, function(err) {
    if (err) return onerror(err);
    fs.writeFile(path.join(__dirname, "path.txt"), platformPath, function(err) {
      if (err) return onerror(err);
    });
  });
}


```

**Comment by duanhx** [comment]
The download part is ok. Just cannot get electron 7 to run. So I had to rollback to version 6.

**Comment by duanhx** [comment]
> Download electron manually, then modify `install.js`.
> 
> ```js
> // // downloads if not cached
> // downloadArtifact({
> //   version,
> //   artifactName: "electron",
> //   force: process.env.force_no_cache === "true",
> //   cacheRoot: process.env.electron_config_cache,
> //   platform: process.env.npm_config_platform || process.platform,
> //   mirror: "https://npm.taobao.org/mirrors/electron/", // 多了这句
> //   arch: process.env.npm_config_arch || process.arch
> // })
> //   .then(zipPath => extractFile(zipPath))
> //   .catch(err => onerror(err));
> 
> extractFile("<electron_zip_path>");
> // unzips and makes path.txt point at the correct executable
> function extractFile(zipPath) {
>   extract(zipPath, { dir: path.join(__dirname, "dist") }, function(err) {
>     if (err) return onerror(err);
>     fs.writeFile(path.join(__dirname, "path.txt"), platformPath, function(err) {
>       if (err) return onerror(err);
>     });
>   });
> }
> ```

I finally get version 7 worked. Thanks a lot!!! Something wrong with download?

**Comment by Ziv-Barber** [comment]
Same problem in Windows 10 and version 7.0.1
I tried 6.1.3 and it's working fine.
I'll stay with 6.1.3 for now until that it'll be fixed.

**Comment by g1eny0ung** [comment]
Same error for me in MacOS 10.15 and version 7.

**Comment by Ziv-Barber** [comment]
> 
> 
> Same error for me in MacOS 10.15 and version 7.

It worked for me after setting ELECTRON_CUSTOM_DIR to '7.1.0' (or whatever version you are using) and then do yarn install

**Comment by kanjieater** [comment]
This is still broken and doesn't work behind a proxy: https://github.com/electron/electron/issues/20739

Back to 6...
