### ISSUE TITLE
2nd call to systemPreferences.isTrustedAccessibilityClient(true) does not open prompt

### ISSUE THREAD

**Issue by salomvary** [electron/electron#20787]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.0.0-beta.1, 7.x, 6.x, nightly is also affected
* **Operating System:**
  * macOS 10.14.6 (18G103)
* **Last Known Working Electron version:**
  * 5.0.11

### Expected Behavior

If an Electron application is *not* a trusted accessibility client:

- Calling `systemPreferences.isTrustedAccessibilityClient(false)` first should return `false`
- Calling `systemPreferences.isTrustedAccessibilityClient(true)` second should show a system prompt

### Actual Behavior
- Calling `systemPreferences.isTrustedAccessibilityClient(false)` first returns `false` ✅
- Calling `systemPreferences.isTrustedAccessibilityClient(true)` second does not show a prompt ❌

### To Reproduce

Use the following snippet in `main.js`:

```js
app.on("ready", () => {
  const isTrusted = systemPreferences.isTrustedAccessibilityClient(false);
  console.log("isTrustedAccessibilityClient", isTrusted);
  if (!isTrusted) {
    const clickedButton = dialog.showMessageBox(null, {
      type: 'warning',
      message: 'Turn on accessibility',
      detail: 'Turn on Media Keys?',
      defaultId: 1,
      cancelId: 0,
      buttons: ['Not Now', 'Turn On Accessibility']
    })
    if (clickedButton === 1) {
      // Calling isTrustedAccessibilityClient with prompt=true has the side effect
      // of showing the native dialog that either denies access or opens System
      // Preferences.
      systemPreferences.isTrustedAccessibilityClient(true)
    }

  }
```

Or use this example repo:

```sh
$ git clone https://github.com/salomvary/electron-media-keys-bug
$ cd electron-media-keys-bug
$ npm install
$ npm start
```

### Use case:

Show this "explanatory prompt" before showing the real one:

<img width="532" alt="Screenshot 2019-10-28 at 21 23 34" src="https://user-images.githubusercontent.com/193923/67714952-3ab20a00-f9c9-11e9-9428-4530d91c45e7.png">

**Comment by codebytere** [comment]
hey @salomvary - this is in fact working as designed by Apple itself. The way that system permissions work is that Apple will only show you the system prompt the the first time access is requested. After the user has made an initial decision, the only way to change that decision is via System Preferences, in the following screen:

<img width="780" alt="Screen Shot 2019-12-05 at 11 00 10 AM" src="https://user-images.githubusercontent.com/2036040/70265056-78374f00-174e-11ea-9099-6b2d5ed5560e.png">

**Comment by salomvary** [comment]
@codebytere thanks for the response! I disagree with you on this not being a bug in Electron for two reasons:

1. It works as expected on an older version of Electron (5.0.11) on the same macOS version where recent Electron has this issue
2.
 - The first call to `systemPreferences.isTrustedAccessibilityClient(false)` correctly *does not show the prompt*
 - The second `systemPreferences.isTrustedAccessibilityClient(true)` call *is* the first ever call that should show the prompt, but it incorrectly *does not*. "The way that system permissions work is that Apple will only show you the system prompt the the first time" does not sound like an argument supporting this behavior.

What do you think? Am I missing something? (I know close to nothing about native macOS development therefore I might be....)
