### ISSUE TITLE
Windows 10 / VS 2019 link error (Component Build)

### ISSUE THREAD

**Issue by samkuhn** [electron/electron#20784]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
8.0.0-nightly.20191026 (Building from source)
* **Operating System:**
Windows 10 (1809)

### Expected Behavior
Electron to link successfully.

### Actual Behavior
I am receiving the following link error:

`
FAILED: electron.exe electron.exe.pdb
ninja -t msvc -e environment.x64 -- ../../third_party/llvm-build/Release+Asserts/bin/lld-link.exe /nologo "-libpath:..\..\..\..\..\..\..\..\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\ATLMFC\lib\x64" "-libpath:..\..\..\..\..\..\..\..\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\lib\x64" "-libpath:..\..\..\..\..\..\..\..\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "-libpath:..\..\..\..\..\..\..\..\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "-libpath:..\..\..\..\..\..\..\..\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" /OUT:./electron.exe /PDB:./electron.exe.pdb @./electron.exe.rsp
lld-link: error: duplicate symbol: public: __cdecl blink::mojom::BlobProxy::BlobProxy(class mojo::MessageReceiverWithResponder *) in obj/third_party/blink/public/mojom/android_mojo_bindings/android_mojo_bindings_jumbo_1.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: __cdecl blink::mojom::FileChooserFileInfo::FileChooserFileInfo(void) in obj/third_party/blink/public/mojom/mojom_platform/mojom_platform_jumbo_1.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: __cdecl blink::mojom::FindOptions::FindOptions(void) in obj/third_party/blink/public/mojom/mojom_platform/mojom_platform_jumbo_2.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: __cdecl blink::mojom::FindOptions::FindOptions(bool, bool, bool, bool, bool) in obj/third_party/blink/public/mojom/mojom_platform/mojom_platform_jumbo_2.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: __cdecl blink::mojom::NativeFileInfo::NativeFileInfo(class base::FilePath const &, class std::basic_string<wchar_t, struct std::char_traits<wchar_t>, class std::allocator<wchar_t>> const &) in obj/third_party/blink/public/mojom/mojom_platform/mojom_platform_jumbo_1.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: __cdecl blink::mojom::ServiceWorkerRegistrationOptions::ServiceWorkerRegistrationOptions(void) in obj/third_party/blink/public/mojom/mojom_core/mojom_core_jumbo_1.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: __cdecl blink::mojom::FileChooserFileInfo::~FileChooserFileInfo(void) in obj/third_party/blink/public/mojom/mojom_platform/mojom_platform_jumbo_1.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: __cdecl blink::mojom::FindOptions::~FindOptions(void) in obj/third_party/blink/public/mojom/mojom_platform/mojom_platform_jumbo_2.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: __cdecl blink::mojom::NativeFileInfo::~NativeFileInfo(void) in obj/third_party/blink/public/mojom/mojom_platform/mojom_platform_jumbo_1.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: __cdecl blink::mojom::ServiceWorkerRegistrationOptions::~ServiceWorkerRegistrationOptions(void) in obj/third_party/blink/public/mojom/mojom_core/mojom_core_jumbo_1.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: __cdecl blink::mojom::WindowFeatures::~WindowFeatures(void) in obj/third_party/blink/public/mojom/mojom_platform/mojom_platform_jumbo_6.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: static bool __cdecl blink::mojom::BlobReaderClientStubDispatch::Accept(class blink::mojom::BlobReaderClient *, class mojo::Message *) in obj/third_party/blink/public/mojom/android_mojo_bindings/android_mojo_bindings_jumbo_1.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: static bool __cdecl blink::mojom::BlobReaderClientStubDispatch::AcceptWithResponder(class blink::mojom::BlobReaderClient *, class mojo::Message *, class std::unique_ptr<class mojo::MessageReceiverWithStatus, struct std::default_delete<class mojo::MessageReceiverWithStatus>>) in obj/third_party/blink/public/mojom/android_mojo_bindings/android_mojo_bindings_jumbo_1.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: static bool __cdecl mojo::StructTraits<class blink::mojom::WindowFeaturesDataView, class mojo::StructPtr<class blink::mojom::WindowFeatures>>::Read(class blink::mojom::WindowFeaturesDataView, class mojo::StructPtr<class blink::mojom::WindowFeatures> *) in obj/third_party/blink/public/mojom/mojom_platform/mojom_platform_jumbo_6.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: virtual void __cdecl blink::mojom::BlobProxy::ReadAll(class mojo::ScopedHandleBase<class mojo::DataPipeProducerHandle>, class mojo::PendingRemote<class blink::mojom::BlobReaderClient>) in obj/third_party/blink/public/mojom/android_mojo_bindings/android_mojo_bindings_jumbo_1.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: virtual void __cdecl blink::mojom::BlobProxy::ReadRange(unsigned __int64, unsigned __int64, class mojo::ScopedHandleBase<class mojo::DataPipeProducerHandle>, class mojo::PendingRemote<class blink::mojom::BlobReaderClient>) in obj/third_party/blink/public/mojom/android_mojo_bindings/android_mojo_bindings_jumbo_1.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: void __cdecl blink::mojom::FileChooserFileInfo::set_native_file(class mojo::StructPtr<class blink::mojom::NativeFileInfo>) in obj/third_party/blink/public/mojom/mojom_platform/mojom_platform_jumbo_1.obj and in blink_common.dll
ninja: build stopped: subcommand failed.
`
### Additional Information

Since I'm unable to find anything in the chromium bug tracker or here relating to this error I'm kinda assuming its something silly I've done on my end.. (run the post hooks multiple times maybe?) 

Any pointers of how to fix it would be welcome.. so close to finally building! Thanks.

**Comment by deepak1556** [comment]
@samkuhn can you pull in latest master and try again, also make sure your toolchain meets the requirements mentioned here https://chromium.googlesource.com/chromium/src/+/lkgr/docs/windows_build_instructions.md#visual-studio

**Comment by samkuhn** [comment]
Thanks will leave latest master syncing overnight and report back.
I'll also double check the minimum requirements again.

FYI get_toolchain_dir returned:

`
vs_path = "C:\\Program Files (x86)/Microsoft Visual Studio/2019/Community"
sdk_path = "C:\\Program Files (x86)\\Windows Kits\\10"
vs_version = "2019"
wdk_dir = ""
runtime_dirs = "C:\\Windows\\System32;C:\\Windows\\SysWOW64;Arm64Unused"
`

**Comment by samkuhn** [comment]
Hmm re-fetched latest master and rebuilt from scratch but still hitting the same link error. 
I believe all requirements posted above are present and correct. 

I'm a bit out of my depth here but I'm guessing blink_common.dll is generated as part of the component build? So just wondering why lld-link is attempting to link to the .obj files as well as the dll's. Or is that just how it works?

**Comment by deepak1556** [comment]
Thanks for testing it, from your log the toolchain is correct. I missed the fact that you are making a component build, I only verified the testing and release builds. Will look into this today.

**Comment by samkuhn** [comment]
I just tried a release build instead as a test.. and it failed with a different error (build this time not link):

`
[19200/19708] CXX obj/third_party/blink/renderer/core/svg/svg/svg_jumbo_1.obj
FAILED: obj/third_party/blink/renderer/core/svg/svg/svg_jumbo_1.obj
..\..\third_party\llvm-build\Release+Asserts\bin\clang-cl.exe /nologo /showIncludes "-imsvc..\..\..\..\..\..\..\..\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\ATLMFC\include" "-imsvc..\..\..\..\..\..\..\..\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include" "-imsvc..\..\..\..\..\..\..\..\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-imsvc..\..\..\..\..\..\..\..\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-imsvc..\..\..\..\..\..\..\..\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-imsvc..\..\..\..\..\..\..\..\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-imsvc..\..\..\..\..\..\..\..\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-imsvc..\..\..\..\..\..\..\..\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -DUSE_AURA=1 -DOFFICIAL_BUILD "-DCR_CLANG_REVISION=\"373424-64a362e7-1\"" -D_HAS_NODISCARD -D_HAS_EXCEPTIONS=0 -D__STD_C -D_CRT_RAND_S -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_ATL_NO_OPENGL -D_WINDOWS -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -DPSAPI_VERSION=2 -DWIN32 -D_SECURE_ATL -D_USING_V110_SDK71_ -DWINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP -DWIN32_LEAN_AND_MEAN -DNOMINMAX -D_UNICODE -DUNICODE -DNTDDI_VERSION=NTDDI_WIN10_RS2 -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DBLINK_CORE_IMPLEMENTATION=1 -DWEBP_EXTERN=extern -DUSE_EGL -D_WTL_NO_AUTOMATIC_NAMESPACE -DBLINK_IMPLEMENTATION=1 -DINSIDE_BLINK -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=0 -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_WIN -DABSL_ALLOCATOR_NOTHROW=1 -DNO_MAIN_THREAD_WRAPPING -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DUSE_CHROMIUM_ICU=1 -DU_STATIC_IMPLEMENTATION -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DUCHAR_TYPE=wchar_t -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DSK_GL -DSK_HAS_PNG_LIBRARY -DSK_HAS_WEBP_LIBRARY "-DSK_USER_CONFIG_HEADER=\"../../skia/config/SkUserConfig.h\"" -DSK_HAS_JPEG_LIBRARY -DSK_SUPPORT_GPU=1 "-DSK_GPU_WORKAROUNDS_HEADER=\"gpu/config/gpu_driver_bug_workaround_autogen.h\"" -DGR_GL_FUNCTION_TYPE=__stdcall -DV8_DEPRECATION_WARNINGS -DLEVELDB_PLATFORM_CHROMIUM=1 -DLEVELDB_PLATFORM_CHROMIUM=1 -DSUPPORT_WEBGL2_COMPUTE_CONTEXT=1 -DWTF_USE_WEBAUDIO_PFFFT=1 -DUSE_LIBJPEG_TURBO=1 -DV8_DEPRECATION_WARNINGS -DLIBXSLT_STATIC -I. -I../.. -Igen -I../../third_party/libyuv/include -I../../third_party/libwebp/src -I../../third_party/wtl/include -I../../third_party/khronos -I../../gpu -Igen/third_party/dawn/src/include -I../../third_party/dawn/src/include -I../../third_party/boringssl/src/include -I../../third_party/webrtc_overrides -I../../third_party/webrtc -Igen/third_party/webrtc -I../../third_party/abseil-cpp -I../../third_party/ced/src -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../third_party/protobuf/src -I../../third_party/protobuf/src -Igen/protoc_out -I../../third_party/skia -I../../third_party/angle/include -I../../third_party/angle/src/common/third_party/base -Igen/angle -I../../third_party/angle/include -I../../v8/include -Igen/v8/include -I../../third_party/libwebm/source -I../../third_party/leveldatabase -I../../third_party/leveldatabase/src -I../../third_party/leveldatabase/src/include -I../../third_party/libjpeg_turbo -I../../third_party/iccjpeg -I../../third_party/libpng -I../../third_party/zlib -I../../third_party/ots/include -I../../v8/include -Igen/v8/include -I../../third_party/libxml/src/include -I../../third_party/libxml/win32/include -I../../third_party/libxslt/src -I../../third_party/snappy/src -I../../third_party/snappy/win32 -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -Xclang -mllvm -Xclang -instcombine-lower-dbg-declare=0 -fcomplete-member-pointers /Gy /FS /bigobj /utf-8 /Zc:sizedDealloc- /X -fmsc-version=1916 /guard:cf,nochecks -m64 /Brepro -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes /W4 -Wimplicit-fallthrough -Wthread-safety -Wextra-semi /WX /wd4091 /wd4127 /wd4251 /wd4275 /wd4312 /wd4324 /wd4351 /wd4355 /wd4503 /wd4589 /wd4611 /wd4100 /wd4121 /wd4244 /wd4505 /wd4510 /wd4512 /wd4610 /wd4838 /wd4995 /wd4996 /wd4456 /wd4457 /wd4458 /wd4459 /wd4200 /wd4201 /wd4204 /wd4221 /wd4245 /wd4267 /wd4305 /wd4389 /wd4702 /wd4701 /wd4703 /wd4661 /wd4706 /wd4715 -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-final-dtor-non-final-class -Wno-sizeof-array-div /MT -Xclang -add-plugin -Xclang find-bad-constructs -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wexit-time-destructors /wd4305 /wd4324 /wd4714 /wd4800 /wd4996 -Xclang -add-plugin -Xclang blink-gc-plugin -Xclang -plugin-arg-blink-gc-plugin -Xclang no-gc-finalized -Wglobal-constructors /O2 /Ob2 /Oy- /Zc:inline /Gw /Z7 -gcodeview-ghash -fno-standalone-debug -Wconversion -Wno-float-conversion -Wno-sign-conversion -Wno-implicit-float-conversion -Wno-implicit-int-conversion -Wno-shorten-64-to-32 /wd4344 -DLIBXML_STATIC= /TP /wd4577 /GR- /c gen/third_party/blink/renderer/core/svg/svg_jumbo_1.cc /Foobj/third_party/blink/renderer/core/svg/svg/svg_jumbo_1.obj /Fd"obj/third_party/blink/renderer/core/svg/svg_cc.pdb"
In file included from gen/third_party/blink/renderer/core/svg/svg_jumbo_1.cc:5:
In file included from .\../../third_party/blink/renderer/core/svg/animation/smil_animation_sandwich.cc:26:
In file included from ../..\third_party/blink/renderer/core/svg/animation/smil_animation_sandwich.h:29:
../..\third_party/blink/renderer/core/svg/animation/smil_time.h(73,17): error: no member named 'min' in namespace 'std'
    return std::min(SMILTime(base::TimeDelta::FromSecondsD(seconds)), Latest());
           ~~~~~^
../..\third_party/blink/renderer/core/svg/animation/smil_time.h(72,29): error: no return statement in constexpr function
  static constexpr SMILTime FromSecondsD(double seconds) {
                            ^
../..\third_party/blink/renderer/core/svg/animation/smil_time.h(76,17): error: no member named 'min' in namespace 'std'
    return std::min(SMILTime(base::TimeDelta::FromMicroseconds(us)), Latest());
           ~~~~~^
../..\third_party/blink/renderer/core/svg/animation/smil_time.h(75,29): error: no return statement in constexpr function
  static constexpr SMILTime FromMicroseconds(int64_t us) {
                            ^
4 errors generated.
[19209/19708] CXX obj/third_party/blink/renderer/core/timing/timing/timing_jumbo_1.obj
ninja: build stopped: subcommand failed.
`

So starting to think there must be something a bit wrong with my setup here..

**Comment by samkuhn** [comment]
Mind you there have been quite a [lot of changes](https://bugs.chromium.org/p/chromium/issues/detail?id=998526&can=1&q=smil_time.h&sort=-modified&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified) to those files recently.

**Comment by samkuhn** [comment]
I added:

`#include <algorithm>'

To:

Line 30 of third_party/blink/renderer/core/svg/animation/smil_time.h

Since that's where std:min is defined and now my release build succeeds! (do we report that?)
Would still like to get the component build working at some point if we can resolve that link error.

**Comment by deepak1556** [comment]
Looked further into the component build issue, the symbol export defines `BLINK_COMMON_EXPORT` are declared irrespective of the component target `blink_common` which causes duplicate exported symbols https://cs.chromium.org/chromium/src/third_party/blink/public/mojom/BUILD.gn . This should be boken in upstream as well, might take sometime for me to get a proper fix.

**Comment by samkuhn** [comment]
Ah ok good to know. I'm actually doing alright with my release build for the time being. 
Thanks for the help.

**Comment by deepak1556** [comment]
Testing build should be fixed by https://github.com/electron/electron/pull/20859

**Comment by deepak1556** [comment]
The component builds should now be fixed by https://bugs.chromium.org/p/chromium/issues/detail?id=1019970

**Comment by bughit** [comment]
@deepak1556 

> The component builds should now be fixed by https://bugs.chromium.org/p/chromium/issues/detail?id=1019970

I just got this on master (a7c2f79a94f2dfd87baeefab402b18e1eef28290). Is it the same issue?

```
[32883/32884] LINK electron.exe electron.exe.pdb
FAILED: electron.exe electron.exe.pdb
ninja -t msvc -e environment.x86 -- ../../third_party/llvm-build/Release+Asserts/bin/lld-link.exe /nologo "-libpath:..\..\..\..\..\Program Files (x86)\Microsoft
 Visual Studio\2019\Professional\VC\Tools\MSVC\14.23.28105\ATLMFC\lib\x86" "-libpath:..\..\..\..\..\Program Files (x86)\Microsoft Visual Studio\2019\Professiona
l\VC\Tools\MSVC\14.23.28105\lib\x86" "-libpath:..\..\..\..\..\Program Files (x86)\Windows Kits\NETFXSDK\4.6\lib\um\x86" "-libpath:..\..\..\..\..\Program Files (
x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x86" "-libpath:..\..\..\..\..\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x86" /OUT:./electron.exe /PDB:.
/electron.exe.pdb @./electron.exe.rsp
lld-link: error: duplicate symbol: public: __thiscall blink::mojom::BlobProxy::BlobProxy(class mojo::MessageReceiverWithResponder *) in obj/third_party/blink/pu
blic/mojom/android_mojo_bindings/blob.mojom.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: __thiscall blink::mojom::FileChooserFileInfo::FileChooserFileInfo(void) in obj/third_party/blink/public/mojom/mojom_p
latform/file_chooser.mojom.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: __thiscall blink::mojom::FindOptions::FindOptions(void) in obj/third_party/blink/public/mojom/mojom_platform/find_in_
page.mojom.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: __thiscall blink::mojom::FindOptions::FindOptions(bool, bool, bool, bool, bool) in obj/third_party/blink/public/mojom
/mojom_platform/find_in_page.mojom.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: __thiscall blink::mojom::NativeFileInfo::NativeFileInfo(class base::FilePath const &, class std::basic_string<wchar_t
, struct std::char_traits<wchar_t>, class std::allocator<wchar_t>> const &) in obj/third_party/blink/public/mojom/mojom_platform/file_chooser.mojom.obj and in b
link_common.dll
lld-link: error: duplicate symbol: public: __thiscall blink::mojom::ServiceWorkerRegistrationOptions::ServiceWorkerRegistrationOptions(void) in obj/third_party/
blink/public/mojom/mojom_core/service_worker_registration.mojom.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: __thiscall blink::mojom::FileChooserFileInfo::~FileChooserFileInfo(void) in obj/third_party/blink/public/mojom/mojom_
platform/file_chooser.mojom.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: __thiscall blink::mojom::FindOptions::~FindOptions(void) in obj/third_party/blink/public/mojom/mojom_platform/find_in
_page.mojom.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: __thiscall blink::mojom::FullscreenOptions::~FullscreenOptions(void) in obj/third_party/blink/public/mojom/mojom_plat
form/fullscreen.mojom.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: __thiscall blink::mojom::NativeFileInfo::~NativeFileInfo(void) in obj/third_party/blink/public/mojom/mojom_platform/f
ile_chooser.mojom.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: __thiscall blink::mojom::ServiceWorkerRegistrationOptions::~ServiceWorkerRegistrationOptions(void) in obj/third_party
/blink/public/mojom/mojom_core/service_worker_registration.mojom.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: __thiscall blink::mojom::WindowFeatures::~WindowFeatures(void) in obj/third_party/blink/public/mojom/mojom_platform/w
indow_features.mojom.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: static bool __cdecl blink::mojom::BlobReaderClientStubDispatch::Accept(class blink::mojom::BlobReaderClient *, class
mojo::Message *) in obj/third_party/blink/public/mojom/android_mojo_bindings/blob.mojom.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: static bool __cdecl blink::mojom::BlobReaderClientStubDispatch::AcceptWithResponder(class blink::mojom::BlobReaderCli
ent *, class mojo::Message *, class std::unique_ptr<class mojo::MessageReceiverWithStatus, struct std::default_delete<class mojo::MessageReceiverWithStatus>>) i
n obj/third_party/blink/public/mojom/android_mojo_bindings/blob.mojom.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: static bool __cdecl mojo::StructTraits<class blink::mojom::WindowFeaturesDataView, class mojo::StructPtr<class blink:
:mojom::WindowFeatures>>::Read(class blink::mojom::WindowFeaturesDataView, class mojo::StructPtr<class blink::mojom::WindowFeatures> *) in obj/third_party/blink
/public/mojom/mojom_platform/window_features.mojom.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: virtual void __thiscall blink::mojom::BlobProxy::ReadAll(class mojo::ScopedHandleBase<class mojo::DataPipeProducerHan
dle>, class mojo::PendingRemote<class blink::mojom::BlobReaderClient>) in obj/third_party/blink/public/mojom/android_mojo_bindings/blob.mojom.obj and in blink_c
ommon.dll
lld-link: error: duplicate symbol: public: virtual void __thiscall blink::mojom::BlobProxy::ReadRange(unsigned __int64, unsigned __int64, class mojo::ScopedHand
leBase<class mojo::DataPipeProducerHandle>, class mojo::PendingRemote<class blink::mojom::BlobReaderClient>) in obj/third_party/blink/public/mojom/android_mojo_
bindings/blob.mojom.obj and in blink_common.dll
lld-link: error: duplicate symbol: public: void __thiscall blink::mojom::FileChooserFileInfo::set_native_file(class mojo::StructPtr<class blink::mojom::NativeFi
leInfo>) in obj/third_party/blink/public/mojom/mojom_platform/file_chooser.mojom.obj and in blink_common.dll
ninja: build stopped: subcommand failed.
```

**Comment by deepak1556** [comment]
@bughit yup its the same issue, I would suggest you to use testing build since electron no longer officially supports debug builds. I haven't looked into fixing this for a while.

**Comment by bughit** [comment]
@deepak1556 This is a testing build with the following args:

`gn gen out/Testing-x86 --args="import(\"//electron/build/args/testing.gn\") target_cpu=\"x86\" is_component_build=true enable_nacl=false blink_symbol_level=0 is_debug=true"`

The args used were suggested in the docs for a faster build.

**Comment by deepak1556** [comment]
By testing build we usually refer to static build with debug symbols on contrary to release build which has more compiler optimizations and minimal debug symbols. `is
_component_build=true` are usually referred to as debug builds.

Please use the testing config from https://github.com/electron/electron/blob/master/build/args/testing.gn

**Comment by bughit** [comment]
What does `is_debug = true` do? Is there any reason to want it on when debugging?

**Comment by deepak1556** [comment]
It enables all the checks behind `DEBUG` macro like `//base` DCHECKS, v8 debugging checks etc.

**Comment by bughit** [comment]
Thanks, one more thing. I may try linux cross compilation with sccache. Will the component build work there? Is it recommended? for additional build speed? or any other reason?

**Comment by deepak1556** [comment]
Yes you can definitely use the component build, but there may be build errors that you would have to fix on your own. I don't have actual numbers to say which config would be better.

**Comment by bughit** [comment]
> but there may be build errors that you would have to fix on your own

It seems you're saying the combination I asked about (linux, win-cross-compile, sccache, component) is unsupported. Which part makes it unsupported, just component?

**Comment by deepak1556** [comment]
Yes just component, because our ci hasn't been running component builds for sometime now and thats why I said there might be compile errors when you build master in component build.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
