### ISSUE TITLE
Communication using ipcRenderer.sendToHost seems broken since electron 6.0.0 and above

### ISSUE THREAD

**Issue by yafp** [electron/electron#20817]
### Preflight Checklist
* [ x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 6.0.0 or higher
* **Operating System:** Ubuntu 18.04 x64
* **Last Known Working Electron version:** 5.0.11

### Expected Behavior
Communication between renderer and injected code in webview using `ipcRenderer.sendToHost() ` should work in electron 6.0.0 and above (like it did using electron 5.x)

### Actual Behavior
`ipcRenderer.sendToHost() ` seems not to work, code after this line is not executed.
Sending back to renderer fails.

### To Reproduce
I got the following code in my renderer

```
webview.addEventListener("ipc-message", (event) => {
    // update the badge
    if(event.channel != null)
    {
        updateServiceBadge(serviceId, event.channel);
    }
});
```

and the following code is injected in my webview.
```
const {ipcRenderer} = require("electron");

function serviceGetUnreadMessageCount()
{
    const elements = document.querySelectorAll("#pane-side .P6z4j, .unread");
    console.log(elements);

    let count = 0;
    for (let i = 0; i < elements.length; i++)
    {
        if (elements[i].parentNode.parentNode.querySelectorAll("#pane-side *[data-icon='muted']").length === 0) 
        {
            count += 1;
        }
    }

    // Report back the unread count
    ipcRenderer.sendToHost(count);
    console.log("POST_SENDTOHOST_1");
}

ipcRenderer.on("request", function()
{
    ipcRenderer.sendToHost(serviceGetUnreadMessageCount());
    console.log("POST_SENDTOHOST_2");
});
```

Both console.log("POST...) are executed using Electron 5.0.11 and below, but after updating to 6.0..0 or above not any longer. The `count` variable is not send back to the renderer.

I've checked https://github.com/electron/electron/blob/master/docs/api/breaking-changes.md#planned-breaking-api-changes-60 to see breaking changes from electron 5 to 6 - but haven't found something explaining this behaviour change.

Maybe i am misinterpreting something here, but so far i just don't understand why the code which worked without issues on v5 series is broken since electron v6.

Any ideas?

**Comment by yafp** [comment]
@vladimiry 
Thanks for the feedback.
Seems like i have to continue digging then .... but to be honest i don't see any light in the dark so far.
Any idea what might cause my problems considering the code above?

Greetings

**Comment by vladimiry** [comment]
`serviceGetUnreadMessageCount()` function call doesn't return any value, so you send `undefined` executing such code: `ipcRenderer.sendToHost(serviceGetUnreadMessageCount());`

I could look into the code but you will need to provide an isolated minimal repro repository.

**Comment by yafp** [comment]
Thanks - that already helped.

Sorry for creating the issue.
