### ISSUE TITLE
macOS Mojave, a weird border around every window.

### ISSUE THREAD

**Issue by MaxyeeMoo** [electron/electron#20820]
I installed macOS Mojave on my Mid 2009 MacBook Pro.
Everything runs smoothly, no errors where found while booting, but I stumbled upon a tiny discomfort.
Every window, every option bubble has a weird black border,  I don't know how to explain it.
The system runs from an SSD if that's important
![Screenshot 2019-10-29 at 1 27 23 pm](https://user-images.githubusercontent.com/55453203/67764117-df782a00-fa51-11e9-9144-ce91e72bb8a9.png)

**Comment by MaxyeeMoo** [comment]
I installed macOS Mojave on my Mid 2009 MacBook Pro.
Everything runs smoothly, no errors where found while booting, but I stumbled upon a tiny discomfort.
Every window, every option bubble has a weird black border,  I don't know how to explain it.
The system runs from an SSD if that's important
![Screenshot 2019-10-29 at 1 27 23 pm](https://user-images.githubusercontent.com/55453203/67764117-df782a00-fa51-11e9-9144-ce91e72bb8a9.png)

**Comment by bernatfortet** [comment]
@MaxyeeMoo did you figure what was causing the issue? Could you share it with us?

**Comment by MaxyeeMoo** [comment]
@bernatfortet 
I kinda found the solution for this problem but it doesn't solve everything.
I'm still getting the borders on some windows.
Nevertheless, the windows in the screenshot mentioned above is now without the borders and the white mode which was grey, is now back to normal as it was supposed to be.
https://github.com/SpiraMira/HybridMode-Public
All thanks to this link, keep in mind that the borders aren't fully fixed and will make their appearance known on some windows.

**Comment by bernatfortet** [comment]
Thanks!
