### ISSUE TITLE
There is no way to set `--max-http-header-size` in Electron 5.x

### ISSUE THREAD

**Issue by flotwig** [electron/electron#20831]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.10
* **Operating System:**
  * all
* **Last Known Working Electron version:**
  * n/a

### Issue Summary

* Node 11.11.0 introduced a `--max-http-header-size` config option, to change `http.maxHeaderSize` (default 80kb)
* In Electron 5, Node 12.0.0 was introduced, which made the default `http.maxHeaderSize` only 8kb
* This made some of our users' tests fail with Electron 5, since the header size changed:
	* cypress-io/cypress#5431
* We want to increase the header size by doing `--max-http-header-size={1 MB}` at Electron startup time
	* However, Electron does not accept this command line argument. If you try passing it to an unpackaged app or a packaged app, the result is the same, `http.maxHeaderSize` is still 8kb.
	* You can pass it as a `NODE_OPTIONS`, and this works great. We updated our Electron launcher to pass this because we thought this was the solution: 
		* cypress-io/cypress#5452, cypress-io/cypress#5492
	* However, this only works in development. As the docs note:
		> https://electronjs.org/docs/all#node_options
		> NODE_OPTIONS are explicitly disallowed in packaged apps.
* So, it appears there is no real way to set `--max-http-header-size` in Electron. Not sure if this counts as a bug, or as a feature request, but either way, a working method to set this flag would be much appreciated!

P.S. thanks for all the work you do on Electron, the fact that this is the first issue I've had to open after 10 months of working with your product is a testament to its quality.

### Related

* #13402 - "Electron ignores NODE_OPTIONS"

**Comment by codebytere** [comment]
Closing this as i've added it, but per our API policies it will only be available in newer versions of Electron.

**Comment by flotwig** [comment]
@codebytere Awesome, thanks! Do you know when this will be released? I don't see it in the changelog for any of the versions since it was merged on October 30th.

**Comment by flotwig** [comment]
@codebytere Looking at the docs on electronjs.org, it doesn't seem like this has been released yet. Sorry to bug, but do you have an idea of when it might be released?

**Comment by flotwig** [comment]
Looks like the changelog appeared in the Electron 9.x release notes, I'm guessing that means it will not be in 8.x: https://www.electronjs.org/releases/beta?version=9

**Comment by sssandp** [comment]
If it means anything, I am eagerly anticipating this issue being fixed in Electron so I can use the latest version of Cypress.
