### ISSUE TITLE
electron7 install error  in mac os 10.15

### ISSUE THREAD

**Issue by zhonggithub** [electron/electron#20841]
when i install electron  with npm i -D electron@latest
when node install.js the error happen: 
(node:64243) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (/Users/zz/workspace/zBase/electron-quick-start/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (events.js:210:5)
    at module.exports (/Users/zz/workspace/zBase/electron-quick-start/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/Users/zz/workspace/zBase/electron-quick-start/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (events.js:300:26)
    at ClientRequest.emit (events.js:215:7)
    at ClientRequest.origin.emit (/Users/zz/workspace/zBase/electron-quick-start/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
    at Socket.socketOnData (_http_client.js:456:22)
![image](https://user-images.githubusercontent.com/17545551/67821681-ca0a0b00-faf8-11e9-9142-f0317374a388.png)

mac os: 10.15
node： 12.13.0
npm:  6.12.0

**Comment by zhonggithub** [comment]
when i install electron@6  is successs.  electron@7 is error
![image](https://user-images.githubusercontent.com/17545551/67825210-8537a180-fb03-11e9-9ce0-4dcf19ca62e0.png)

**Comment by zhonggithub** [comment]
i think mac os 10.15 not support electron 7

**Comment by Auxxxxlx** [comment]
#20774

**Comment by xiaoshan5733** [comment]
Maybe the problem is `@eletron/get`

**Comment by DevinKott-KA** [comment]
I already addressed this problem 8 days ago (from now) in issue #20723

**Comment by xiaoshan5733** [comment]
@zhonggithub 
I solved the problem, if you're using taobao mirror, you should config like this in your `~/.npmrc` file:

```
electron_mirror=https://npm.taobao.org/mirrors/electron/
electron_custom_dir=7.0.0
```




====================================================

Here's the problem

https://github.com/electron/get/blob/master/src/utils.ts#L27
![image](https://user-images.githubusercontent.com/854370/68025729-95f53c80-fce8-11e9-8f0f-5bbe345516b4.png)

✅: https://npm.taobao.org/mirrors/electron/7.0.0/electron-v7.0.0-darwin-x64.zip
❌: https://npm.taobao.org/mirrors/electron/v7.0.0/electron-v7.0.0-darwin-x64.zip

**Comment by Alecyrus** [comment]
@xiaoshan5733  Could you report a PR for this issue ?

**Comment by xiaoshan5733** [comment]
@Alecyrus 

Sorry,  I'm afraid i can't, because i don't know why the dirname is different.
```
# github
https://github.com/electron/electron/releases/download/   v7.0.0/    electron-v7.0.0-darwin-x64.zip
# taobao
https://npm.taobao.org/mirrors/electron/   7.0.0/     electron-v7.0.0-darwin-x64.zip
```

**Comment by Auxxxxlx** [comment]
@zcbenz

**Comment by zhonggithub** [comment]
> @zhonggithub
> I solved the problem, if you're using taobao mirror, you should config like this in your `~/.npmrc` file:
> 
> ```
> electron_mirror=https://npm.taobao.org/mirrors/electron/
> electron_custom_dir=7.0.0
> ```
> 
> ====================================================
> 
> Here's the problem
> 
> https://github.com/electron/get/blob/master/src/utils.ts#L27
> ![image](https://user-images.githubusercontent.com/854370/68025729-95f53c80-fce8-11e9-8f0f-5bbe345516b4.png)
> 
> ✅: https://npm.taobao.org/mirrors/electron/7.0.0/electron-v7.0.0-darwin-x64.zip
> ❌: https://npm.taobao.org/mirrors/electron/v7.0.0/electron-v7.0.0-darwin-x64.zip

i try but not work

**Comment by xiaoshan5733** [comment]
@zhonggithub  
Because electron version was changed, now it's `7.0.1`, you can get version from `electron-quick-start/node_modules/electron/package.json`.

And you should remove `./node_modules` before `npm install`

**Comment by globules-io** [comment]
What version works with MacOS 10.15.x ?
I've tried 6, 7 and even 8 nightly but it won't install?

**Comment by tiancihe** [comment]
Same issue on macOS Mojave 10.14.6

**Comment by tiancihe** [comment]
> @zhonggithub
> I solved the problem, if you're using taobao mirror, you should config like this in your `~/.npmrc` file:
> 
> ```
> electron_mirror=https://npm.taobao.org/mirrors/electron/
> electron_custom_dir=7.0.0
> ```
> 
> ====================================================
> 
> Here's the problem
> 
> https://github.com/electron/get/blob/master/src/utils.ts#L27
> ![image](https://user-images.githubusercontent.com/854370/68025729-95f53c80-fce8-11e9-8f0f-5bbe345516b4.png)
> 
> ✅: https://npm.taobao.org/mirrors/electron/7.0.0/electron-v7.0.0-darwin-x64.zip
> ❌: https://npm.taobao.org/mirrors/electron/v7.0.0/electron-v7.0.0-darwin-x64.zip

Works for me.

**Comment by fengmk2** [comment]
Please set mirror to `https://cdn.npm.taobao.org/dist/electron/`, I add a rewrite rule on CDN.

```bash
electron_mirror=https://cdn.npm.taobao.org/dist/electron/
```

**Comment by zhonggithub** [comment]
> Please set mirror to `https://cdn.npm.taobao.org/dist/electron/`, I add a rewrite rule on CDN.
> 
> ```shell
> electron_mirror=https://cdn.npm.taobao.org/dist/electron/
> ```

it work for me  tks!

**Comment by arleyGuoLei** [comment]
work for me ~ ↓

code ~/.npmrc

add these:

```
electron_mirror=https://cdn.npm.taobao.org/dist/electron/
electron_custom_dir=7.1.9
```

**Comment by orangezyx** [comment]
that is the correct anwser while using the taobao mirror.
just edit the npmrc file
```
electron_mirror=https://cdn.npm.taobao.org/dist/electron/
electron_custom_dir=7.1.9
```

**Comment by czqasngit** [comment]
It works for me
