### ISSUE TITLE
dialog.showMessageBoxSync options noLink not work under windows 10, electron v7

### ISSUE THREAD

**Issue by tangjfn** [electron/electron#20855]
dialog.showMessageBoxSync(getCurrentWindow(), {
        type: "question",
        title: "test title",
        message: "test message",
        buttons: ["OK", "Cancel"],
        defaultId: 0,
        cancelId: 1,
        noLink: true
    })

**Comment by alex8088** [comment]
the same, too

**Comment by JannisX11** [comment]
I third that.

**Comment by patrickeller** [comment]
Same... And because of noLink issn't working anymore, I don't get a respone wich button i clicked.
btw. same result with async message box.

**Comment by popod** [comment]
Hi @codebytere any chance to have a fix for this issue ? Thanks a lot ;)
