### ISSUE TITLE
Cannot read property getType of null

### ISSUE THREAD

**Issue by IhorVimmi** [electron/electron#20853]
Stack: Angular 8  + Electron 7.0

when i call 
import {session, ipcMain} from 'electron';
also im using electron-dl

`session.defaultSession.createInterruptedDownload({
eTag: item.getETag(),
lastModified: item.getLastModifiedTime(),
length: item.getTotalBytes(),
offset: item.getReceivedBytes(),
mimeType: item.getMimeType(),
path: item.savePath,
urlChain: item.getURLChain()
});`

where item - DownloadItem

I got the next error:  http://joxi.ru/Y2L6EdMh7Gbo5r 
Help me please, what wrong?

The idea: before closing application, it can download some files, and after the restart, I need to resume downloading.
I create interrupted download when downloading started (that is wrong?)

Full code of the function

`private downloadFiles(event, files, id) {
    for (const file of files) {
      const properties = {
        directory: path.join(__dirname + '/../../downloads/test'),
        onProgress: (status) => {
          // progress logic
        },
        onStarted: (item) => {
          session.defaultSession.createInterruptedDownload({
            eTag: item.getETag(),
            lastModified: item.getLastModifiedTime(),
            length: item.getTotalBytes(),
            offset: item.getReceivedBytes(),
            mimeType: item.getMimeType(),
            path: item.savePath,
            urlChain: item.getURLChain()
          });
        }
      };

      electronDl.download(this.window, file.url, properties).then(result => {
        return this.window.webContents.send('download-complete', {
          event: 'onComplete',
          id,
          data: {
            path: result.getSavePath(),
          }
        });
      });
    }
  }`

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
