### ISSUE TITLE
Wrong area painted with `backdrop-filter` set in macOS 10.15

### ISSUE THREAD

**Issue by jasonxia23** [electron/electron#20872]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.11
* **Operating System:** 
  * macOS 10.15
* **Last Known Working Electron version:**
  * 

### Expected Behavior

`backdrop-filter` has effect on the whole page.

### Actual Behavior

`backdrop-filter` only has effect on certain area.

### To Reproduce

```bash
git clone https://github.com/jasonxia23/electron-quick-start
cd electron-quick-start
npm install
npm start
```

**Comment by miniak** [comment]
@jasonxia23 did you try with Electron 6 or 7?

**Comment by jasonxia23** [comment]
@miniak Yeah, Electron 6/7 is fine.

**Comment by electron-triage** [comment]
@jasonxia23 Please upgrade to Electron 6 or 7. We are no longer supporting versions older than Electron 6, per our [supported versions policy](https://www.electronjs.org/docs/tutorial/support#supported-versions)
