### ISSUE TITLE
Webview cookies doesn't persist

### ISSUE THREAD

**Issue by lincolnaleixo** [electron/electron#20891]
* [X ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
7.0.0
* **Operating System:**
MacOS 10.5.1

### Expected Behavior
Persist cookies from webview

### Actual Behavior
Not persisting cookies from webview after reloading the app

### To Reproduce
Github.com
Login
Restart the app
Not logged anymore

### Additional Information
Already searched issues and found some relevant information but none seems to work
https://github.com/electron/electron/issues/15365
https://github.com/electron/electron/issues/13200
https://github.com/electron/electron/issues/9807
https://github.com/electron/electron/issues/4304

The only solution that worked was from this issue, but I don't know if this is the "official way". Also it's related to a different version (5.0.6):
https://github.com/electron/electron/issues/19140

**Comment by MarshallOfSound** [comment]
Based on #19140 you are running into expected behaviour.  The GitHub session cookie is set to `Session` expiry.  I.e. when you restart the app it is supposed to start a new session and not have that cookie any more.

The workaround in that issue simply takes all session only cookies and sets them to have a date-based expiry time.
