### ISSUE TITLE
Cannot get WebGL to work on linux ARMv7

### ISSUE THREAD

**Issue by dland512** [electron/electron#20890]
I am running electron on an ARMv7 processor running Ubuntu 16.04.2 LTS. WebGL isn't working. Chromium says that's it's disabled:
```
console.log(app.getGPUFeatureStatus());
{
  '2d_canvas': 'disabled_software',
  flash_3d: 'disabled_software',
  flash_stage3d: 'disabled_software',
  flash_stage3d_baseline: 'disabled_software',
  gpu_compositing: 'disabled_software',
  metal: 'disabled_off',
  multiple_raster_threads: 'disabled_off',
  oop_rasterization: 'disabled_off',
  protected_video_decode: 'disabled_off',
  rasterization: 'disabled_software',
  skia_renderer: 'disabled_off',
  surface_control: 'disabled_off',
  surface_synchronization: 'enabled_on',
  video_decode: 'disabled_software',
  viz_display_compositor: 'enabled_on',
  viz_hit_test_surface_layer: 'disabled_off',
  webgl: 'disabled_off',
  webgl2: 'disabled_off'
}
```

I have tried several things to get it working including using the following flags on the command line:

    ./node_modules/.bin/electron main.js --no-sandbox --enable-webgl --ignore-gpu-blacklist

and the following settings in the main process code:

```
app.commandLine.appendSwitch('--enable-webgl', 'true');
app.commandLine.appendSwitch('--ignore-gpu-blacklist', 'true');
app.commandLine.appendSwitch('--no-sandbox', 'true');
```

I also tried turning on webgl and experimental features like this:

```
mainWindow = new BrowserWindow({
    width: 400,
    height: 640,
    frame: true,
    webPreferences: {
        webgl: true,
        experimentalFeatures: true,
        experimentalCanvasFeatures: true
    }
});
```
Nothing seems to work. I've read [this issue](https://github.com/electron/electron/issues/1277) with no luck.

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v6.1.1
* **Operating System:**
  * Ubuntu 16.04.2 LTS
* **Last Known Working Electron version:**
  * 

### Expected Behavior

WebGL should work

### Actual Behavior

WebGL is disabled. When I pull up a page such as https://get.webgl.org I get the message

> Hmm. While your browser seems to support WebGL, it's disabled or unavailable. If possible, please ensure that you are running the latest drivers for your video card.

Also when I open `chrome://gpu` I see 

> WebGL: Disabled
> WebGL2: Disabled

### Additional Information

As best I can tell, the GPU is made by Vintante and appears to be using their driver.

**Comment by freezen** [comment]
@dland512 , I'm trying to use GPU acceleration feature in electron as well. I find that you use browserWindow to open a new chrome window and use GPU acceleration in it, but do you know if I want to use GPU acceleration in NodeJS child_process or cluster process, is that possible? Or I have to use it in a real browser window. Thx

**Comment by freezen** [comment]
@dland512 , I find that if you log the GPU status in main.js(electron root portal), it says disabled, but if you log it after initialize, it says yes, enabled.

**Comment by dland512** [comment]
@freezen, that doesn't seem to be the case for me. When I call `window.loadURL('https://get.webgl.org')` it says that WebGL is disabled. I would think all the initialization would be finished by that point.

What you say initialize, what do you mean? After calling a particular method?

**Comment by aperkaz** [comment]
@freezen @dland512 I am facing the same issue. Did you managed to solve it?

**Comment by maurocristy87** [comment]
I'm developing an application for raspberry pi 4, building for armv7l and I had the same problem tring to get the  webgl2 context, it returns null and in console I get the following error message "GL_INVALID_ENUM: Invalid pname".  Then I tried using the old webgl context (canvasElement.getContext("webgl"), and with some little modifications in the shaders it worked. Finally I tried 2d context, and it worked too. So as long as webgl2 still doesn't work, you can try the old webgl API (or context 2d)

**Comment by maurocristy87** [comment]
I'm developing an app for raspberry pi 4 (armv7l arch) and I had thee same issue trying to get the webgl2 context. it always returned null and in the console I got the follow error message "GL_INVALID_ENUM: Invalid pname". Then I tried using 2d context, and it workd fine, and finally I tried using the old webgl api, and with some modifications in my shaders, it worked fine too.
So as long as webgl2 still doesn't work, you can try the old webgl API (or context 2d).

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
