### ISSUE TITLE
Application crash

### ISSUE THREAD

**Issue by Inomezi** [electron/electron#20909]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *7.0.0
* **Operating System:**
 Windows 10, Mac Os

### Actual Behavior
In different projects, with a heavy load, the program stops working and a white screen appears.
Errors in console:
[66857:1101/121345.746686:ERROR:CONSOLE(4712)] "Connection is closed, can't dispatch pending call", source: devtools://devtools/bundled/shell.js (4712)

### To Reproduce
This problem is not only when using multithreading, but it is easiest to reproduce it like this
for( let i = 0 ; i < 5000 ; i ++ ) {
	new Worker("js file path")
}

### Screenshots

![image](https://user-images.githubusercontent.com/24946599/68018375-a59d6280-fca1-11e9-9304-a5af3a3c1d8a.png)

**Comment by codebytere** [comment]
In the main process or renderer? Workers aren't supported in renderer processes right now.

**Comment by Inomezi** [comment]
> In the main process or renderer? Workers aren't supported in renderer processes right now.

I told you, this problem not only with workers,  but it easy way for reproduce it.
It web workers, not workers_thread, i provided this example for easy reproduce, i have project without workers with this problem

**Comment by Inomezi** [comment]
> In the main process or renderer? Workers aren't supported in renderer processes right now.

How can i handle crash ? 
process.on('uncaughtException', e => {}); and process.on('unhandledRejection', e => {}); not saving.
Second project got this error: `async hook stack has become corrupted` then white screen.  Can I prevent the application from reloading with such errors?

**Comment by codebytere** [comment]
I'm not fully sure what the issue is here - i ran your repro with Workers and saw no crash on macOS.

**Comment by Inomezi** [comment]
> I'm not fully sure what the issue is here - i ran your repro with Workers and saw no crash on macOS.

Electron version 7.0.0 ?

**Comment by KochiyaOcean** [comment]
I wrote an example for reproduce.
Run following command

```bash
git clone git@github.com:KochiyaOcean/electron-bugs.git -b 7.x.x-heavyload
cd electron-bugs
electron .
```

The render process will have a chance to crash after about 20 seconds.

![image](https://user-images.githubusercontent.com/8194131/68701965-355cde00-05cb-11ea-978b-907ab7bb827b.png)

Reproduced on my PC with windows 10 build 1903, with core i9 9900k & 32G RAM.

Seems PC with higher performance will have a lower chance to meet an crash.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
