### ISSUE TITLE
I want to do some code little change on Devtools ，the local file also change I used to work on Devtools's workspace but I try on electron Devtools  I don't how to achieve it again , Please somebody just tell me a way  Thank your help

### ISSUE THREAD

**Issue by WingDust** [electron/electron#20908]
I want to do some code little change on Devtools ，the local file also change I used to work on Devtools's workspace 
but I try on electron Devtools  I don't how to achieve it again 
, Please somebody just tell me a way  Thank your help.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
