### ISSUE TITLE
iframe not show

### ISSUE THREAD

**Issue by GuoSirius** [electron/electron#20907]
### Issue Details

* **Electron Version:**
  * 6.1.12
* **Operating System:**
  * Windows 10 x64 -->
* **Last Known Working Electron version:**
  * 4.2.12

![image](https://user-images.githubusercontent.com/48358523/68008061-865dff80-fcb8-11e9-95a1-cb262816418e.png)

The left is webview Tag,  it is normal in 4.x OR 6.x

The right is ifram Tag, it is normal in 4.x , but not Shown in 6.1.12

**Comment by junwalldo1** [comment]
this problem is very serious,application: Lector,the Electron version used is 5.0.4,there is no such problem

**Comment by junwalldo1** [comment]
I found the problem,you need to set up nodeIntegrationInSubFrames to true

**Comment by MarshallOfSound** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by GuoSirius** [comment]
> Thank you for taking the time to report this issue and helping to make Electron better.
> 
> Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.
> 
> I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.
> 
> Thanks in advance! Your help is appreciated.

**Comment by GuoSirius** [comment]
> Thank you for taking the time to report this issue and helping to make Electron better.
> 
> Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.
> 
> I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.
> 
> Thanks in advance! Your help is appreciated.

https://github.com/GuoSirius/webview-vs-iframe.git

@MarshallOfSound  this is the demo!

**Comment by t57ser** [comment]
I could reproduce this

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
