### ISSUE TITLE
Cannot access nativeTheme via electron.remote

### ISSUE THREAD

**Issue by sachinrekhi** [electron/electron#20900]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.0.0
* **Operating System:**
  * macOS 10.14.6

### Expected Behavior
I tried the following to access the new nativeTheme module from my renderer process:

```
let electron = window.require('electron')
let { nativeTheme } = electron.remote
console.log(nativeTheme.shouldUseDarkColors)
```

I expected this to print true to the console since dark mode is enabled on my Mac.

### Actual Behavior
Instead I got an error saying cannot read shouldUseDarkColors property of undefined. I also tried console.log(electron.remote) and nativeTheme was not listed. It appears nativeTheme is not accessible from the renderer process via electron.remote. I have no problem accessing things like systemPreferences from electron.remote so I expected this to work.

**Comment by sachinrekhi** [comment]
@MarshallOfSound saw that you have been working on nativeTheme, so wanted to see if you could help!

**Comment by miniak** [comment]
@sachinrekhi you can use this workaround before we release the fix:
`const { nativeTheme } = require('electron').remote.require('electron')`
