### ISSUE TITLE
Electron 7 missing directories in sources in chrome dev tools

### ISSUE THREAD

**Issue by Tekk-Know** [electron/electron#20917]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.0.0
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 6.1.2

### Expected Behavior
When building my angular project and running electron I expect have the following path visible in the sources tab in Chrome developer tools (webpack:// > . > src). 

### Actual Behavior
When building my angular project and running electron I am missing the path mentioned above and instead have paths to "./lib" and "webpack" which does not contain the angular app .ts files.  This prevents me from being about to debug the app using the developer tools.

### To Reproduce
1. Install Angular cli (npm install @angular/cli -g)
2. Generate new Angular app (ng new electron-angular-app)
3. Install electron in app (npm install electron@latest --save-dev)
4. Configure electron and start
5. Open dev tools and navigate to sources tab
6. Notice available directories under webpack://

### Screenshots
Bad:
![v7.0.0 Sources](https://i.stack.imgur.com/zsXCl.png)

Good:
![v6.1.2 Sources](https://user-images.githubusercontent.com/15911092/68036593-03c34900-fc94-11e9-9387-c7f2dfb23d6b.png)

### Additional Information
Downgrading my project to version 6.1.2 fixes the issue.

**Comment by amirburbea** [comment]
I'm having the same issue in Electron 7.1.0 with React so this is not limited to Angular

**Comment by amirburbea** [comment]
Still broken in 7.1.2 - please increase the priority of this issue (or explain a workaround if there's a different way to build our applications that gets around this issue)

**Comment by amirburbea** [comment]
@sofianguy Is there any update here? Or are you guys having trouble reproducing? This is a serious issue and I (and @Tekk-Know I'm sure as well) would be happy to provide information to help you guys track this down.

**Comment by amirburbea** [comment]
Ugh. Still broken in 7.1.3

**Comment by amirburbea** [comment]
Still broken in 7.1.4

**Comment by amirburbea** [comment]
Fixed in 7.1.6!

**Comment by srikanthonl** [comment]
Yes works in 7.1.6

**Comment by amirburbea** [comment]
@Tekk-Know you can close this issue now.

**Comment by srikanthonl** [comment]
Sorry, today I saw the issue coming back again in electron@7.1.7. Cant see the webpack/. folder. So, cant debug using dev tools.

**Comment by srikanthonl** [comment]
OK. This somehow started working again. I just removed node_modules and reinstalled them. And the webpack/. folder is back. I can now debug in chrome dev tools.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
