### ISSUE TITLE
Electron Fiddle Never Stops Downloading...

### ISSUE THREAD

**Issue by oshea00** [electron/electron#20914]
### Issue Details
Install Electron Fiddle. (Windows 10 in a VM behind firewall)
electron-fiddle-0.11.0-x64-setup.exe
Run.

### Expected Behavior
Background Download of electron API should complete.

### Actual Behavior
It doesn't.
I suspect some sort of firewall issue, however, there is no feedback, nor are there settings, no way to determine what is happening from the user's point-of-view. 

### To Reproduce
See Issue Details.

**Comment by miniak** [comment]
https://github.com/electron/fiddle/issues
