### ISSUE TITLE
question: how to get keydown event inside a webview

### ISSUE THREAD

**Issue by muscaiu** [electron/electron#20911]
I'm loading a game into an electron webview and having some focus issues when i try to exit fullscreen.
A solution to the focus issue would be to listen to key events when the webview is in focus.
I tried this and nothing is happening.
Any idea how to do it?
```
  const keyPressed = e => {
    console.log('key pressed', e);
  };

const webviewTag = document.querySelector('webview');
webviewTag.focus();
webviewTag.addEventListener('keydown', keyPressed);
```

**Comment by codebytere** [comment]
This is not currently possible, sadly - see https://github.com/electron/electron/issues/14258#issuecomment-416794070
