### ISSUE TITLE
React DevTools: Profiler "Reload and start profiling" doesn't work due to XMLHttpRequest 'null' origin

### ISSUE THREAD

**Issue by joltmode** [electron/electron#20915]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.1.2
* **Operating System:**
  * macOS 10.15 (19A602)
* **Last Known Working Electron version:**
  * I do not know

This might be a problem how React DevTools is built - that it's maybe incompatible with Electron ways.

Though, I'm asking here because, hey, the profiler works in standard Chrome, so it's not really the extension's issue. Also, maybe there is a workaround?

### Expected Behavior

- Open React DevTools Profiler
- Click "Reload and start profiling"
- Await reload
- Do actions
- Click "Stop profiling"
- See profiler results

### Actual Behavior

- Open React DevTools Profiler
- Click "Reload and start profiling"
- Await reload
- Do actions
- Click "Stop profling" - does not work
- Because there are errors in console (actually thrown immediately after reload):
  ```
  Access to XMLHttpRequest at 'chrome-extension://react-developer-tools/build/renderer.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, https.
  ```
  ```
  Uncaught DOMException: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'chrome-extension://react-developer-tools/build/renderer.js'.
  ```

### To Reproduce
Electron Fiddle Gist: https://gist.github.com/joltmode/82574cab4970def210dac0c68d4c34b8

### Screenshots
![Errors after triggering profiler](https://user-images.githubusercontent.com/1030080/68028419-81e81580-fcbd-11e9-85ae-58b8437df6d8.png)

![The respective code in React DevTools](https://user-images.githubusercontent.com/1030080/68028680-1ce0ef80-fcbe-11e9-9b63-4fa0494af0dd.png)

### Additional Information
**Relevant code from React DevTools codebase**

https://github.com/facebook/react/blob/a1ff9fd7bb919cfe8d18ce9c8b9315d74d0e3405/packages/react-devtools-extensions/src/injectGlobalHook.js#L71-L87

**Comment by codebytere** [comment]
hey! given that this is a bug present in a consumer of Electron, it'd probably be a better choice to open that there first; once that's done, if they determine that this is a bug with us and not them, we'll be happy to reopen and investigate this :)
