### ISSUE TITLE
Electron 8 exports __esModule = true, breaking Webpack bundles

### ISSUE THREAD

**Issue by LuminescentMoon** [electron/electron#20910]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.0-beta.1 & 8.0.0-beta.2
* **Operating System:**
  * Windows 10 1909 build 18363.449
* **Last Known Working Electron version:**
  * 7.0.0

### Expected Behavior
`require('electron').__esModule === undefined`

### Actual Behavior
`require('electron').__esModule === true`

### To Reproduce
- `npm init -y`
- `npm i electron@8`
- `echo "console.log(require('electron').__esModule === true)" > index.js`
- `npm run electron .`

Terminal will have `true` written.

### Additional Information
This breaks Webpack bundles because Webpack's require will check this property and return exports.default which obviously doesn't exist on Electron's exports object. Electron 7 doesn't have __esModule defined on its exports at all.

**Comment by codebytere** [comment]
cc @miniak, looks like this was added here: https://github.com/electron/electron/commit/7825d043f2765ddab5c1b05e49d2eb5782c8421b
