### ISSUE TITLE
-webkit-app-region: drag stops working when BrowserView is changed

### ISSUE THREAD

**Issue by quanglam2807** [electron/electron#20926]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  7.0.0/7.0.1
* **Operating System:**
  *  macOS 10.14.6 / macOS 10.15.1
* **Last Known Working Electron version:** 
  *  6.0.12

### Expected Behavior

User should be able to drag HTML component with `-webkit-app-region: drag` to move window around. 

### Actual Behavior

When the React app is first loaded, it works. When BrowserView is changed, HTML parts with `-webkit-app-region: drag` are no longer draggable. Clicking the components won't fix the problem but try to perform dragging operation on these components would then fix it.

### To Reproduce

```sh
$ git clone https://github.com/quanglam2807/webcatalog -b v17.1.2
$ cd webcatalog/template
$ yarn
$ yarn electron-dev
```
Electron will run. The sidebar includes `-webkit-app-region: drag` and can be dragged. Add multiple workspaces, then try to switch workspace. The `BrowserView` will be changed. Then, you would no longer be able to drag the side.

Hole a workspace icon on the sidebar and try to drag it, the app would let you rearrange workspaces. Then sidebar is now draggable again.

`v16.1.2` is the last version of the app using `electron@6.0.12` and it still works ok. The commit following it: https://github.com/quanglam2807/webcatalog/commit/ecf3513a62eade5cb046f38de2f17f1506d1cde3 causes the issue.

Reported by user: https://github.com/quanglam2807/webcatalog/issues/354.

### Screenshots

<img width="1062" alt="Screen Shot 2019-11-01 at 10 27 09 PM" src="https://user-images.githubusercontent.com/1548835/68065419-02773800-fcf7-11e9-9f9e-9f7e795be482.png">

### Additional Information

None

**Comment by quanglam2807** [comment]
Update: Reloading `webContents` of `BrowserWindow` after `setBrowserView` would make dragging works again.

**Comment by sentialx** [comment]
I can confirm that on macOS after changing the `BrowserView` using either `setBrowserView` or `addBrowserView` breaks dragging in a frameless window. After reloading the `BrowserWindow`, it starts working. I'm using Electron 8.0.0-beta.2.

**Comment by ivanalejandro0** [comment]
I've had a similar problem after upgrading from electron 4 to 7.

To me, the problem appears when I vertically resize the window, and gets "fixed" if I resize the window horizontally or minimize/restore it.

I found a workaround for this problem here: https://github.com/nwjs/nw.js/issues/2375#issuecomment-87499741

I just added an extra node to my app:

```html
<body>
  <!-- app content here -->
  <div style="-webkit-app-region: no-drag;"></div>
</body>
```

I still haven't investigated why this fixes the problem, but with this I no longer see the issue.

I hope this helps.

**Comment by xuchaoqian** [comment]
Have the same issue here.

**Comment by sentialx** [comment]
@ivanalejandro0 Despite it fixes the issue with vertical resizing, it still doesn't fix the issue with changing BrowserViews.

**Comment by sentialx** [comment]
I found a workaround for this issue. You can try increasing window's width (or height, if you've applied @ivanalejandro0's fix) by 1 and then restoring it to the original size. Example code:

```js
const { width } = win.getBounds();
win.setBounds({ width: width + 1 });
win.setBounds({ width });
```

**Comment by quanglam2807** [comment]
Fixed with https://github.com/electron/electron/pull/21723

**Comment by pejman1** [comment]
same issue in electron 10.1.5 in windows 10, browser view is not draggable after removing and adding
