### ISSUE TITLE
The response of the CORS POST request is empty when using webRequest

### ISSUE THREAD

**Issue by vladimiry** [electron/electron#20923]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

The response of the CORS POST request is empty.

* **Electron Version:** 7.x, 8.x
* **Operating System:** Linux (at least)
* **Last Known Working Electron version:** 6.1.3

### Expected Behavior

The response of the CORS POST request is not empty.

### Actual Behavior

The response of the CORS POST request is empty.

### To Reproduce

https://github.com/vladimiry-playground/electron-quick-start-custom-prtocol-cors-issue

### Screenshots

![v7 0 1 (response is empty)](https://user-images.githubusercontent.com/1560781/68053943-415cbc00-fcfe-11e9-9ba2-913fda4d0a84.gif)

![v6 3 1 (response is filled)](https://user-images.githubusercontent.com/1560781/68053948-43bf1600-fcfe-11e9-8722-620645f5c375.gif)

### Additional Information

In v7 and v8, the `access-control-allow-origin` and `origin` headers are not shown as modified in the dev console. It shows `https://mail.protonmail.com` value but should be showing `scheme123://index.html` as v6 does.

**Comment by vladimiry** [comment]
Just tried electron@7.1.0, the problem is still there.

**Comment by nornagon** [comment]
@vladimiry it looks like you're issuing the request from a page served on a custom domain, and additionally modifying the request with `webRequest`. Are you also seeing the issue for CORS requests when not using those features? If not, please update the issue title and details to reflect your findings.

**Comment by vladimiry** [comment]
@nornagon that's correct, in the original repro repository a custom protocol is used but the problem is also reproducible for the regular/https scheme, the respective repro repo is here https://github.com/vladimiry-playground/electron-quick-start-cors-issue

<details><summary>See some visual description below</summary><p>

![6 1 4](https://user-images.githubusercontent.com/1560781/68283879-6ef28e00-008d-11ea-99a4-2a4c78674ae7.gif)

![7 1 0](https://user-images.githubusercontent.com/1560781/68283980-a3664a00-008d-11ea-895c-a9edcf9ffc46.gif)

</p></details>

<details><summary>Notice that "access-control-allow-origin" header is shown defferently on dev console for 6.x and 7.x (it's related to the `Additional Information` section of the original message)</summary><p>

![6 1 4](https://user-images.githubusercontent.com/1560781/68283888-74e86f00-008d-11ea-9203-378fde5211d6.png)

![7 1 0](https://user-images.githubusercontent.com/1560781/68283889-74e86f00-008d-11ea-8351-a093160765c4.png)

</p></details>

**Comment by nornagon** [comment]
Your new repro also uses webRequest, so it seems like that's critical to this issue, yes? cc @zcbenz who worked on migrating webRequest to the network service.

**Comment by vladimiry** [comment]
> Your new repro also uses webRequest, so it seems like that's critical to this issue, yes?

Correct, it's all about the onBeforeSendHeaders/onHeadersReceived webRequest handlers.

**Comment by deepak1556** [comment]
@zcbenz it might be related to the OOR-CORS feature that was enabled https://groups.google.com/a/chromium.org/d/msg/network-service-dev/zph9qQsu91I/yE2-Pw8BAQAJ

**Comment by zcbenz** [comment]
Currently webRequest in Electron uses the `extraHeaders: false` code path in Chromium, we should use the `extraHeaders: true` code path to keep compatibility with old versions. It is on my TODO list but I thought no app would be hit by the behavior, I'll have a fix for this.

**Comment by vladimiry** [comment]
Can confirm the issue got resolved with 7.1.2 release.

**Comment by jalanga** [comment]
For me is not working on electron 7.1.2, on OSX

**Comment by vladimiry** [comment]
@jalanga did you try running the https://github.com/vladimiry-playground/electron-quick-start-cors-issue repo (initially provided here https://github.com/electron/electron/issues/20923#issuecomment-550217015)? If it works for you on OSX then the issue is probably in your code (1.7.12 => 7.1.2 is a major update that might require restructuring the exisitng code).

**Comment by jalanga** [comment]
@vladimiry Thank you for your time, your example is working, the headers are set, de single difference is that I do ```initSession``` after ```createWindow```, if I do it before it, is stuck at spalsh screen. I will figure it out.

**Comment by jalanga** [comment]
Fir parameter `filter` for `onBeforeSendHeaders` it was `http://localhost:8000` which was bad, because, now needs to be `http://localhost:8000/*`
