### ISSUE TITLE
electron打包的桌面客户端启动白屏问题

### ISSUE THREAD

**Issue by Zhongxiangyun** [electron/electron#20928]
请教一个问题，就是用户那边安装了这个包后，我们服务器发布了新的代码，但是用户那边打开客户端会白屏（目前解决的办法是删除用户的缓存目录，然后重新启动就好了，不过mac下就不好解决），这种白屏的问题需要怎么解决呢？

项目采用的技术：angular4.x+ts
打包技术：Electron-builder，目前实现的是一个简单的包装应用，在打包里面引入了一个项目地址，用户打开这个应用（相当于打开了一个网页），但是会出现加载白屏的问题。

**Comment by Zhongxiangyun** [comment]
发行细节
electron -v  v1.4.13
操作系统：
windows10
Nodejs版本：
node -v  v10.14.2

**Comment by sofianguy** [comment]
@Zhongxiangyun Can you try a later version of electron? We are no longer supporting versions older than version 5.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by Heyh520** [comment]
My version is 28.3.3, and there will be a white screen when running on win10 after packaging, and there is no way to view the debugging tools, pure white screen
