### ISSUE TITLE
printToPDF Not Respecting CSS print media rules

### ISSUE THREAD

**Issue by payitforwardnow** [electron/electron#20927]
OSX 10.13.6
Electron v7.0.0
Node 12.13.0

I'm expecting the printToPDF function to respect the css media print rules. For example, if I want to protect sensitive information from being printed I setup css media print to hide the information from printing. Unfortunately, even content marked to not be printed is printed. printToPDF follows some css like pagination but not the most important which is the ability to protect sensitive data from being printed. 

I'll be happy to provide more information if needed. Below is a sample of the css which I use all the time.

@media print
{    
    .no-print, .no-print *
    {
        display: none !important;
    }
}

and then in my html document I use

<div class="no-print">This is sensitive information</div>

It would be nice if respecting media print css is the default but allow an option to override (or vice-versa).

Thank you for your time and consideration.

David

I put a line at the top of the HTML that says "Don't print this...". This div has the no-print class on it. Here is a screen shot of what it looks like in Chrome

![image](https://user-images.githubusercontent.com/30054747/68066856-f477e600-fcfb-11e9-967f-90b4016c1a80.png)

Here is an screen shot on a Mac when printing to PDF. The line I protected is not printed.

![image](https://user-images.githubusercontent.com/30054747/68066847-c2668400-fcfb-11e9-903b-69488da68b33.png)

However, it is printed when using the printToPDF in a BrowserView.

![image](https://user-images.githubusercontent.com/30054747/68066873-33a63700-fcfc-11e9-8e88-7078f5936c2c.png)

I'll be happy to provide more info.

**Comment by burningTyger** [comment]
please provide a repo with the bug so that it can be tested.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
