### ISSUE TITLE
Regression in 6.0+ releases: app.on.ready event isn't called

### ISSUE THREAD

**Issue by alex-klimov** [electron/electron#20931]
### Preflight Checklist

* [ x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.0.1, works correctly on 5.0.11
* **Operating System:**
  * Windows 10 (Version 10.0.18362 Build 18362)
* **Last Known Working Electron version:**
  * 5.0.11

### Expected Behavior
app.on.ready event is called.

### Actual Behavior
app.on.ready event is not called.

### To Reproduce
The line `Starting app.on.ready event...` is never printed for this `main.js` file, since app.on.ready event is never called.

`main.js`
```javascript
const app = require("electron").app;
console.log("Starting main process...");
app.on("ready", () => {
    console.log("Starting app.on.ready event...");
});
console.log("Main process started.");
```

[Updated] That is important to start electron by passing `main.js` as the starting script to electron instead of referencing it in package.json:
```cmd
node_modules/.bin/electron.cmd main.js
```
`package.json`
```json
package.json

{
    "name": "electron-app.ready-repro",
    "version": "1.0.0",
    "description": "",
    "scripts": {
    },
    "main": "",
    "devDependencies": {
    },
    "dependencies": {
        "electron": "7.1.0"
    }
}
```

### Additional Information
I got a clue, that some major regression is introduced in recent 6.0+ releases, after reading this issue:
https://github.com/electron/electron/issues/19978

Sticking with the older 5.0.11 version until new releases stabilize.

**Comment by MarshallOfSound** [comment]
@alex-klimov Your code does not appear to reproduce this issue.  Using this fiddle --> https://gist.github.com/11988a04937ae45bbfa4dc74e1ff76ef

I get this output: 
![image](https://user-images.githubusercontent.com/6634592/68078190-410c0180-fd8e-11e9-8b43-627a6e2462f0.png)

As you can see that event definitely fires.

**Comment by alex-klimov** [comment]
It does reproduce on my dev machine =) I can help debug the problem on my machine, cannot help with the fiddle.

**Comment by alex-klimov** [comment]
I have updated Windows 10 with the specific version I got from System Information, just in case if that is important for getting the repro. Another piece of the information: I have an ultra-wide monitor.

**Comment by t57ser** [comment]
Have you checked if the app is already in the ready state?
Try the following:
```
if (app.isReady()) {
	console.log("App is ready");
} else {
	app.on("ready", () => {
		console.log("App ready event");
	});
}
```

**Comment by alex-klimov** [comment]
Done, please find below.

Also updated repro steps in the original issue with the way how electron should be started: `main.js` should be passed as the script to electron itself, instead of being referenced in package.json.

```cmd
node_modules/.bin/electron.cmd main.js
```

`main.js`
```javascript
const app = require("electron").app;
console.log("Starting main process...");
app.on("ready", () => {
    console.log("app.on.ready event.");
});
console.log("app is " + (app.isReady() ? "ready" : "not ready"));
console.log("Main process started.");
```

`package.json`
```json
{
    "name": "electron-app.ready-repro",
    "version": "1.0.0",
    "description": "",
    "scripts": {
    },
    "main": "",
    "devDependencies": {
    },
    "dependencies": {
        "electron": "7.1.0"
    }
}
```

Such setup produces the following output:
```cmd
D:\src\electron-app.ready-repro/node_modules/.bin/electron.cmd main.js 

Starting main process...
app is not ready
Main process started.
```

**Comment by o2genum** [comment]
Got this bug! My app stopped working on both development machines, very cool.

It has to do with #19978, indeed. `vue-devtools` extension was once installed and has been stored in the `%AppData%\AppName` Electron cache directory. I deleted the entire directory, this fixes the hangup.

@zxffan The bug is related to the dev extensions installed into Electron. That's why deleting `%AppData%\AppName` or changing `AppName` itself helps.

**Comment by miniak** [comment]
Closing in favor of #19978
