### ISSUE TITLE
"BrowserWindow.loadFile" is not a function

### ISSUE THREAD

**Issue by HelloAny** [electron/electron#20937]
# Issue Details

* **Electron Version:**
  * 7.0.1
* **Operating System:**
  * Mac OS 10.15
* **Last Known Working Electron version:**
  * none

### Expected Behavior
`Mainwindow.loadFile` will open the file
### Actual Behavior
An error is prompted `mainwindow.loadFile is not function
`

### To Reproduce
You can reproduce using a small utility repo here: https://github.com/HelloAny/crossover.
```
$ https://github.com/HelloAny/crossover.git
$ npm install
$ electron .
```
### Additional Information
 This is my first attempt to implement electron according to the official website tutorial, but I found this problem.

**Comment by JCBsystem** [comment]
your code works fine for me 
try to delete node_modules and get it again

**Comment by HelloAny** [comment]
> your code works fine for me
> try to delete node_modules and get it again

I have tried several times, but the system still reports an error

**Comment by HelloAny** [comment]
> > your code works fine for me
> > try to delete node_modules and get it again
> 
> I have tried several times, but the system still reports an error

I can use the` loadURL` to run normally

**Comment by MarshallOfSound** [comment]
`electron .` uses your global electron.  If you run `electron --version` you will see that it is not a recent version of Electron.

**Comment by HelloAny** [comment]
> `electron .` uses your global electron. If you run `electron --version` you will see that it is not a recent version of Electron.
> 
> You should use `npm start` or `node_modules/.bin/electron .`

Thanks. In the end, I found that the problem of installing `install.js` on `MAC 10.15`may be a bit troublesome in China, but I have found a solution in other issues
