### ISSUE TITLE
Random JS parsing errors in custom HTTP protocols

### ISSUE THREAD

**Issue by sentialx** [electron/electron#20932]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.0.1
* **Operating System:**
  * Windows 10 1903
* **Last Known Working Electron version:**
  * 6.1.3

### Expected Behavior
Websites should load from a custom http protocol normally.

### Actual Behavior
Electron when trying to load js bundles generated by `webpack-dev-server` from a custom http protocol, throws weird and completely random errors in devtools like:
```
ReferenceError: Invalid left-hand side in assignment
```
However it worked normally in previous Electron versions. Perhaps the migration to `NetworkService` has to do something with it?

Notice, if you uncomment [this line](https://github.com/sentialx/electron-quick-start/blob/master/src/main/index.ts#L69) and comment above, it loads normally. 

### To Reproduce
https://github.com/sentialx/electron-quick-start
(Instructions are in the README file)
(the example website can load normally on first startup, so please reload it using `Ctrl+R`)

**Comment by lodicolo** [comment]
I am able to reproduce the same with Electron 7.1.0 on macOS 10.14.6, loading via URL (instead of custom protocols) works fine.

**Comment by sentialx** [comment]
Is there a workaround for this? It's blocking my development...

**Comment by qazbnm456** [comment]
I'm experiencing the same situation 😞 and think that the `NetworkService` is the culprit as @sentialx said. I did some tests among different versions and found out that the problems occurred from v7.0.0-beta.4., which included the [changes](https://github.com/electron/electron/compare/v7.0.0-beta.3...v7.0.0-beta.4).

Hope there are any workarounds or even a fix. Thanks!

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
