### ISSUE TITLE
OpenGL on MacOS Catalina

### ISSUE THREAD

**Issue by GrzegorzZajac000** [electron/electron#20944]
### Issue Details

* **Electron Version:**
7.0.1
* **Operating System:**
macOS Catalina 10.15.1

### Expected Behavior
OpenGL is deprecated on macOS Catalina. Can I use Metal API in Electron?

### Actual Behavior
I get this error in console:
```
Unable to create basic Accelerated OpenGL renderer.
Unable to create basic Accelerated OpenGL renderer.
Core Image is now using the software OpenGL renderer. This will be slow.
```

**Comment by MarshallOfSound** [comment]
@GrzegorzZajac000 Can you reproduce this error with Chrome?

**Comment by GrzegorzZajac000** [comment]
This is only thing i can get in `about:gpu`
![Screenshot 2019-11-04 20 01 50](https://user-images.githubusercontent.com/12233796/68149351-0fd23380-ff3e-11e9-98a0-3622d33bb6e8.png)

![Screenshot 2019-11-04 20 01 35](https://user-images.githubusercontent.com/12233796/68149352-0fd23380-ff3e-11e9-9214-6bbb3635f931.png)

Mac Mini 2018 here

**Comment by cryptoPickle** [comment]
Here is the same issue, 

```
[1] Unable to create basic Accelerated OpenGL renderer.
[1] Unable to create basic Accelerated OpenGL renderer.
[1] Core Image is now using the software OpenGL renderer. This will be slow.
```
![image](https://user-images.githubusercontent.com/27652549/68173248-50e43b00-ff72-11e9-840a-f43b76c38a2f.png)

**Comment by GrzegorzZajac000** [comment]
Any news on this issue?

**Comment by nornagon** [comment]
Still waiting to hear if this issue is also present in Chrome.

**Comment by Auxxxxlx** [comment]
Same issue too.
<img width="899" alt="截屏2019-11-2614 21 19" src="https://user-images.githubusercontent.com/55738135/69604320-05e0b380-1058-11ea-8f73-5aa621f5bebf.png">

**Comment by Alecyrus** [comment]
https://forums.macrumors.com/threads/core-image-is-now-using-the-software-opengl-renderer-this-will-be-slow.2109425/

**Comment by rawbin-** [comment]
same in electron 6.x with macOS Catalina 10.15.1

**Comment by OVBondHUB** [comment]
the same problem macOS Catalina 10.15.1

**Comment by nornagon** [comment]
More comments reporting the same issue aren't helpful. This is still marked blocked/need-info because we have not yet heard if anyone has tried the same code in Chrome to see if the behavior is the same there. If Chrome behaves fine, but Electron doesn't, then there's maybe something we can do. Otherwise, it's out of our hands.

If you're experiencing this issue, please try to reproduce it in Chrome and let us know how that goes.

**Comment by GrzegorzZajac000** [comment]
Today I saw new errors, maybe they will be useful for something

`[72438:1207/223755.550044:ERROR:gles2_cmd_decoder.cc(18526)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoCreateAndTexStorage2DSharedImageINTERNAL: invalid mailbox name
[72438:1207/223755.550147:ERROR:gles2_cmd_decoder.cc(18547)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoBeginSharedImageAccessCHROMIUM: bound texture is not a shared image
[72438:1207/223755.550161:ERROR:gles2_cmd_decoder.cc(13532)] [.DisplayCompositor]GL ERROR :GL_INVALID_VALUE : glScheduleCALayerCHROMIUM: unsupported texture format
[72438:1207/223755.550308:ERROR:gles2_cmd_decoder.cc(13532)] [.DisplayCompositor]GL ERROR :GL_INVALID_VALUE : glScheduleCALayerCHROMIUM: unsupported texture format
[72438:1207/223755.571869:ERROR:gles2_cmd_decoder.cc(18576)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoEndSharedImageAccessCHROMIUM: bound texture is not a shared image`

**Comment by niedfelj** [comment]
@nornagon I am seeing this on latest Catalina(10.15.2) and latest Chrome (79.0.3945.79 (Versão oficial) 64 bits if I do the following:

Launch Chrome from terminal:

/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome

Go to a site that presumably uses GPU: https://animejs.com

Inspect the site and go into device mode (I'm doing a 4K display mode)

You'll then see at some point (not always right away), this output in the Terminal:

Unable to create basic Accelerated OpenGL renderer.
Unable to create basic Accelerated OpenGL renderer.
Core Image is now using the software OpenGL renderer. This will be slow.

**Comment by nornagon** [comment]
OK. If this issue is also present in Chrome then unfortunately there's nothing we can do about it. Feel free to file an issue on Chromium's bug tracker: https://crbug.com/new

**Comment by pastelsky** [comment]
Chrome already has a flag (chrome://flags) that allows you to enable metal rendering. Can the same be done in Electron though @nornagon ?

**Comment by nornagon** [comment]
You can try enabling the feature for yourself with `--enable-features=Metal`.

**Comment by appleparan** [comment]
1. `--enable-features=Metal` seems doesn't work.
2. Not only Catalina, Mojave also has same problem.

**Comment by nofacer** [comment]
Use `app.commandLine.appendSwitch('Metal');`
@appleparan

**Comment by tboulis** [comment]
Any update on this one?

**Comment by appleparan** [comment]
@tboulis After updating to Electron 8, I'm not getting those messages, even Catalina

**Comment by GrzegorzZajac000** [comment]
I still have them.
MacOS Catalina 10.15.3
Electron 8

**Comment by tboulis** [comment]
Me as well @appleparan

**Comment by kalbert312** [comment]
I'm using Electron 8.0.1 macOS 10.15.3. Still getting them too.

**Comment by stevenroussey-privicy** [comment]
Chrome 80 itself does use OpenGL on MacOS Catalina.
 ![image](https://user-images.githubusercontent.com/42726156/75592239-a5865700-5a36-11ea-9c9b-f87da91a60b5.png)

In Chromium, often things are disabled by default (or enabled!) and the setting is reversed in Chrome. Might this be one of those cases?

On MacOS Catalina, having a backdrop div using blur causes all sorts of white screen / or missing layers for a microsecond, making the screen flash. Nothing is actually running, but the compositor freaks out.

**Comment by nathansobo** [comment]
I saw the error message a few times in an app I was hacking on last night, but it was unclear what was triggering it. Small sample size so far, but I didn't see any logging after adding the following to the initialization of my app.

```
import {app} from "electron";
app.commandLine.appendArgument("--enable-features=Metal");
```

Hopefully I'm not just fooled by randomness here.

**Comment by hydrosquall** [comment]
Able to reproduce this issue on a clean install of the electron boilerplate ( https://github.com/sindresorhus/electron-boilerplate ), running Catalina and Electron 7.

**Comment by whxleemdddd** [comment]
Electron：8.1.1；catalina：10.15.3
Unable to create basic Accelerated OpenGL renderer.
Unable to create basic Accelerated OpenGL renderer.
Core Image is now using the software OpenGL renderer. This will be slow.

**Comment by manishb2s** [comment]
Guys, I came with good news and i fix electron app and running locally and .PKg and .DMG all packages are running on @MAC  - CATALINA OS.

MY ELECTRON APP IS WORKING SMOOTHLY ON MAC CATALINA EVEN I DO HAVE MAC ON CLOUD. WHICH IS EVEN BETTER TO SERVE THE SOFTWARE.

Thanks Everyone

**Comment by agashish** [comment]
Guys, I came with good news and i fix electron app and running locally and .PKg and .DMG all packages are running on @MAC - CATALINA OS.

MY ELECTRON APP IS WORKING SMOOTHLY ON MAC CATALINA EVEN I DO HAVE MAC ON CLOUD. WHICH IS EVEN BETTER TO SERVE THE SOFTWARE.

Thanks Everyone

**Comment by athenawisdoms** [comment]
Has a solution been found?  @agashish @nathansobo

Experiencing the same error sometimes. Running on Catalina 10.15.3 and Electron 8.2.5

**Comment by dractw** [comment]
Hi, everybody. I recently faced the same issue and resolves it mysterious way. 
Render-process entry was have: 
```
const app = new Vue({ ... params })
app.$mount('#app')
```
And after aprox. 2-3 minutes mentioned error appears, and the whole app freezes and became unresponsive.

So the trick was to create new Vue instance inside global electron object `top`, like this:
```
top.vue = new Vue({ ... params}).$mount('#app')
```

Cheers, hope this might help.

**Comment by tommoor** [comment]
Any chance we could re-open this ticket? It's still an issue in Electron v8, working my way up to testing on v9 – Chrome on left / Electron logs on right.

![image](https://user-images.githubusercontent.com/380914/86187181-0d85a080-baf0-11ea-81e4-26ff301b3e6c.png)

**Comment by karimhossenbux** [comment]
Yep, it appears to only happen when the devtools is opened.

Found the area where it triggers for me, in the Styles tab:
![Screenshot 2020-07-03 at 10 36 24 PM](https://user-images.githubusercontent.com/584224/86496495-fd82f080-bd7d-11ea-9903-fba140423edc.png)


Video in action: https://imgur.com/a/9wrnv3r
