### ISSUE TITLE
require('fs').promises.mkdir hangs with existing directory

### ISSUE THREAD

**Issue by NaridaL** [electron/electron#20951]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success. *Yes, I've seen #20588, but here the name _is_ valid and I already have the version where it is fixed*

### Issue Details
`await require('fs').promises.mkdir(existingDir, {recursive: true})` hangs forever with existing directory

* **Electron Version:**
  * 

    $ node_modules/.bin/electron --version
    
     v7.0.1

* **Operating System:**
  * 
![image](https://user-images.githubusercontent.com/10828874/68158526-18cc0080-ff50-11e9-863b-b8f7cd9d4c9e.png)

* **Last Known Working Electron version:**
  * 
N/A
### Expected Behavior

`await require('fs').promises.mkdir(existingDir, {recursive: true})`  should return within milliseconds
### Actual Behavior

it never does
### To Reproduce

```sh
git clone https://github.com/NaridaL/electron-mkdir-hang
npm install
npm start
# C:\foo should have been created
# CTRL+C to to quit electron
npm start
# mkdir never returns, "Hello there" is never logged to console.
```

### Screenshots

![image](https://user-images.githubusercontent.com/10828874/68158858-ce974f00-ff50-11e9-82ee-9dc2fd385266.png)

**Comment by codebytere** [comment]
@NaridaL do you have a repro for this that does not involve Webpack? I wasn't able to reproduce it outside the Webpack context, and so i'm inclined to say this issue should be opened there instead.

**Comment by NaridaL** [comment]
@codebytere Good point. I wasn't able to reproduce it without webpack either. I'm using electron-forge, which always also includes the hot module reloading code in the bundle. I'm going to try to reproduce it with a manual webpack bundle.

In any case, it seems to me that webpack shouldn't be able to "break" the `fs` module. If I add 

```ts
  await new Promise(resolve => {
    setTimeout(resolve, 200);
  });

  console.log("slept");
```

that works as expected, so it's clearly not blocking the rendering process.

**Comment by NaridaL** [comment]
It seems to happen when loading over a server.

@codebytere , can you reproduce it with https://github.com/NaridaL/electron-mkdir-hang/tree/no-webpack2 ?

**Comment by NaridaL** [comment]
Do you need more info here, or can we remove the block/need-info tag?

**Comment by codebytere** [comment]
Still cannot reproduce, sadly :(

**Comment by NaridaL** [comment]
Not getting this with 8.0.0 anymore. I assume it has to do with one of the fixed bugs.

**Comment by NaridaL** [comment]
Also, this seems to be the same issue. https://github.com/electron/electron/issues/19554

**Comment by undergroundwires** [comment]
I had the same issue. `setTimeOut` trick in #19554 has fixed it for me.

**Comment by undergroundwires** [comment]
I had the same issue with Electron 12. `setTimeOut` trick in #19554 has fixed it for me.

**Comment by undergroundwires** [comment]
I had the same issue after migrating from Electron 11 to Electron 12. `setTimeOut` trick in #19554 has fixed it for me.
