### ISSUE TITLE
isMaximised() and isFullScreen() always return false if transparent window

### ISSUE THREAD

**Issue by AntaresFR** [electron/electron#20969]
### Issue Details

* **Electron Version:**
  * 7.0.0
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 

### Expected Behavior
isMaximised() and isFullScreen() should return true if the window is maximised or in fullscreen

### Actual Behavior
isMaximised() and isFullScreen() return false if BrowserWindow transparent mode is set to true.

### To Reproduce
```javascript
electron.app.on("ready", function () {
    var win = new BrowserWindow({
        show: true,
        frame: false,
        fullscreen: true,
        transparent: true
    });
    setInterval(() => { 
        console.log('Fullscreen: ' + win.isFullScreen()); 
    }, 3000);
    setInterval(() => { 
        console.log('Maximised: ' + win.isMaximised()); 
    }, 3000);
});
```
Check the console after toggle fullscreen or maximise. It always return false.
If BrowserWindow transparent is set to false, behavior is correct and it returns the good value.

**Comment by Liupeng8** [comment]
have the same problem too！

**Comment by skyslide22** [comment]
same for me,
more infos:

- window docking on win10 not working if {transparent: true} (grab/move window to any screenedge)
- win.isMaximized() returns undefined
- working: double click on a div with -webkit-app-region: drag; maximize/unmaximize the window
- win.unmaximize() returns undefined, win.restore() works properly

**Comment by emiyalee1005** [comment]
I can confirm this issue on 9.0.0 beta3

**Comment by Samkhyey** [comment]
I thought and solved this problem manually:
`(screen.availHeight <= document.body.clientHeight) && (screen.availWidth <= document.body.clientWidth)`
It works the same as isMaximised()

**Comment by AntaresFR** [comment]
Any update on this ?

**Comment by JasonXiaoSpace** [comment]
is there update on this ?

**Comment by gzx-miller** [comment]
How to fix this problem?

**Comment by Luci404** [comment]
Still an issue on 11.0.3.

**Comment by smartguy1196** [comment]
I'm also getting this problem with frameless windows

**Comment by smartguy1196** [comment]
> How to fix this problem? process like this.
> ```
> if(win) {
>   if (win.isMax) {
>     win.unmaximize();
>   } else {
>     win.maximize();
>   }
>   win.isMax = !win.isMax;
> }
> ```
Works

**Comment by purocean** [comment]
```
win.on('enter-full-screen', handleFullscreenEnter)
win.on('leave-full-screen', handleFullscreenLeave)
```

https://github.com/purocean/yn/commit/0b5a4c25cc17b42a5c19e57e4a751ed1db9e0944#diff-91b423f87c23cf65742f51623b76e6fe52d42231eeb6092f43435b09ea1003ebR123

**Comment by Rabbitzzc** [comment]
The bug still exists...

**Comment by Rabbitzzc** [comment]
> The bug still exists on Windows...

use `isMaximized` on Windows

**Comment by Eleg-i** [comment]
It's already 2025, and this issue still exists on Windows 11.

**Comment by bmsuseluda** [comment]
Sadly this issue still exists in 2026 on Windows 11. Please reopen this issue.
