### ISSUE TITLE
 the webview init time will become very long after change icon 

### ISSUE THREAD

**Issue by zhengjiaqi** [electron/electron#20968]
electron:3.1.13
windows7
I have a very strange problem. the webview init time will become very long in render process if i change icon on exe using packager or builder.This problem has been bothering me for more than a week.help me please.thanks

**Comment by sofianguy** [comment]
@zhengjiaqi few questions:
1) Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?
2) Does this happen on version 5 or later? We are no longer supporting versions older than Electron 5.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
