### ISSUE TITLE
Brasilia summer time saving 

### ISSUE THREAD

**Issue by zarubond** [electron/electron#20998]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
The Brazil has recently stopped using summer time. But Electron still works with it!

* **Electron Version:**
  6.1.4 and probably any Electron 6 and lower
* **Operating System:**
 Window 10
* **Last Known Working Electron version:**
7 and up works

### Expected Behavior
The Electron should use system time.

### Actual Behavior
The time is one hour ahead since it still counts the Brasilia Summer time.

### To Reproduce
Go to time settings on your Windows computer, Change timezone to "(UTC -03:00) Brasilia". Open dev tools and paste "new Date().toTimeString()" to console. The resulting time will be one hour ahead.

### Screenshots

![image](https://user-images.githubusercontent.com/6961047/68296594-bcfa9800-0073-11ea-9b22-ba95a586eb68.png)

**Comment by miniak** [comment]
@deepak1556 could this be an issue with old ICU?

**Comment by MarshallOfSound** [comment]
When countries update their timezone or whether they follow DST or not it takes a while to propagate to all the ICU implementations.  As you discovered the correct information is in Electron 7.

Updating the ICU is complicated and risky, the best move here is updating your Electron app to electron 7.

**Comment by alexeykuzmin** [comment]
> could this be an issue with ICU timezone data?

@miniak Yes, it's an ICU issue.

**Comment by miniak** [comment]
Skype says it’s P1 for them

**Comment by miniak** [comment]
Let’s investigate at least how complicated it would be

**Comment by deepak1556** [comment]
@miniak I think this is fixed in upstream by https://bugs.chromium.org/p/chromium/issues/detail?id=1009000

**Comment by MarshallOfSound** [comment]
Sorry if I wasn't clear, updating the ICU outside of chrome doing it last time was (a) scary and (b) caused noticeably inflated ICU related crashes.

I am strongly against any kind of ICU patch landing in Electron

**Comment by deepak1556** [comment]
@MarshallOfSound agree that ICU changes are scary but we already did it for the Japanese era name change, I didn't see any issue from that change. Also the above ICU change is minimal and only needed for 6-1-x branch, any reason to not push it forward as long as the ICU tests pass ?

**Comment by codebytere** [comment]
Related: https://github.com/nodejs/node/pull/30232

**Comment by deepak1556** [comment]
@codebytere fortunately for this case we don't have to bump the ICU version , just backport the above minimal patch :)

**Comment by MarshallOfSound** [comment]
> I didn't see any issue from that change.

We did, after that patch we saw spikes in ICU related crashes.  They went away after we bumped to Electron 6.

**Comment by zarubond** [comment]
@JorgeALeitao Every other program except Electron works fine, event new versions of Chrome. The problem is not in Windows. Identical problem is also present on GNU/Linux.

**Comment by ckerr** [comment]
Solved by upgrading to a newer (supported) version of Electron
