### ISSUE TITLE
Content-Type change to 'text/plain' when build the app in windows

### ISSUE THREAD

**Issue by vts3497** [electron/electron#20990]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  6.0.11
* **Operating System:**
  Windows 10 (1803)

### Expected Behavior

I wrote an application that send post request with **FormData** or **Json** to **Flask python** server. When in developer mode, the request is always successful with header : _"multipart/formdata"_ or _"application/json"._

### Actual Behavior

But when I build the app with **electron-builder** , **yarn dist**, the request fails because the header is only "text/plain" that the Flask server couldn't parse the data. 

### To Reproduce

My application was written with Reactjs and I first try **fetch** in React but it failed. I aslo used ipcRenderer, ipcMan to handle the request but it only ran correctly on dev mode. 

Is it a problem about CORs or something like that which happens when  packing app ?

**Comment by RahZero0** [comment]
How did you solve this I am also facing the same issue . Any help??
