### ISSUE TITLE
win32 electron-builder --win --ia32

### ISSUE THREAD

**Issue by Zhongxiangyun** [electron/electron#20995]
打包命令：
electron-builder --win --ia32

把32位的对应的安装包，安装在win32位的电脑上，报错如下：

无法启动此程序因为计算机中丢失ffmpeg.dll 

我用electron-builder直接打包后的安装包，在win64的电脑上运行安装时可以成功。

希望帮忙解决一下，是不是配置问题呢？

配置文件如下：

{
  "name": "snailpet_dev32",
  "version": "2.0.0",
  "description": "A minimal Electron application",
  "main": "index.js",
  "scripts": {
    "start": "electron .",
    "pack": "electron-builder --dir",
    "dist": "electron-builder --win --ia32"
  },
  "repository": "https://github.com/electron/electron-quick-start",
  "keywords": [
    "Electron",
    "quick",
    "start",
    "tutorial",
    "demo"
  ],
  "publish": [
    {
      "provider": "generic",
      "url": "https://www.jianshu.com/u/1699a0673cfe"
    }
  ],
  "win": {
    "target": [
      {
        "target": "nsis",
        "arch": [
          "ia32"
        ]
      }
    ]
  },
  "nsis": {
    "oneClick": false,
    "allowToChangeInstallationDirectory": true,
    "installerIcon": "./build/icon.ico",
    "shortcutName": "AAA",
    "perMachine": true
  },
  "author": "GitHub",
  "license": "CC0-1.0",
  "devDependencies": {
    "electron": "^6.0.7"
  }
}

**Comment by nornagon** [comment]
This seems like an issue with electron-builder, not Electron itself. Please file an issue on that project: https://github.com/electron-userland/electron-builder

**Comment by xmsz-stu** [comment]
any update?
