### ISSUE TITLE
how to enalbe "Press ESC to exit full screen mode" message

### ISSUE THREAD

**Issue by muscaiu** [electron/electron#20997]
How can i enable the "Press ESC to exit full screen mode message" in electron?

![2019-11-06_13-01-16](https://user-images.githubusercontent.com/11426309/68292993-b4b35480-0095-11ea-957b-4d7150b2309e.png)

Observation: Same iframe with same options in Chrome shows the message, but electron doesn't.

**Comment by nornagon** [comment]
That UI is part of Chrome, which we don't support. You can construct it yourself if you need to.
