### ISSUE TITLE
MenuItem labels are getting truncated

### ISSUE THREAD

**Issue by aabuhijleh** [electron/electron#21001]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.1.3 & 7.1.0 (32-bit)
* **Operating System:**
  * Windows 10 Build 18362 (64-bit) 
* **Last Known Working Electron version:**
  * 5.0.6 (32-bit) 

### Expected Behavior

Tray context menu text to not be truncated

### Actual Behavior

Text is truncated with ellipsis

### To Reproduce

You can use this [repo](https://github.com/aabuhijleh/electron-21001).

I use `tray.setContextMenu(menu)` to set the tray's context menu.

You can build a menu similar to the one shown in the screenshots below and the submenu text will always be truncated.

### Screenshots

6.1.3 context menu (You can also see that it's dark because it's now aware of the OS's theme)
![electron_6 1 3_tray_context_menu](https://user-images.githubusercontent.com/42934634/68300338-3b702d80-00a6-11ea-8988-1222bd299f71.png)

5.0.6 context menu
![electron_5 0 6_tray_context_menu](https://user-images.githubusercontent.com/42934634/68300377-53e04800-00a6-11ea-8c23-9d1024979957.png)

No changes were made to the menu building code.

**Comment by aabuhijleh** [comment]
@sofianguy this issue is also occurring on 7.1.x

I've created this [repo](https://github.com/aabuhijleh/electron-21001) to help reproduce the issue

It appears to happen when both a MenuItem icon is defined & type is set to "checkbox"

It also affects all application menus, not just the tray context menu.

**Tray context menu**
![chrome_0nd0uimuGu](https://user-images.githubusercontent.com/42934634/68389472-b5b6b580-016b-11ea-970f-551509599e4c.png)

**App menu**
![electron_ch1dwkJvnd](https://user-images.githubusercontent.com/42934634/68389461-afc0d480-016b-11ea-9a66-4813aaa9cbdd.png)

**Comment by codebytere** [comment]
@aabuhijleh unfortunately this is an issue upstream in Chromium and not with Electron - there's not a lot we can do about it on our end. When Chromium fixes it, we'll ensure that it gets rolled out as fast as possible!
