### ISSUE TITLE
electron 7.1.0 powerSaveBlocker module is useless on win10

### ISSUE THREAD

**Issue by xland** [electron/electron#21017]
My code is here:
```javascript
const { powerMonitor, powerSaveBlocker } = require("electron").remote;
const id = powerSaveBlocker.start("prevent-display-sleep");
powerSaveBlocker.stop(id);
powerMonitor.on("lock-screen", () => {
  powerSaveBlocker.stop(id);
  console.log("The system is lock screen");
});
powerMonitor.on("unlock-screen", () => {
  console.log("The system is unlock screen");
});
```
When I press Win+L key,
My screen is locked.
This code can not prevent  the lock-screen event.

**Comment by MarshallOfSound** [comment]
`prevent-display-sleep` will not prevent the user manually locking their machine.  It is designed to prevent natural display sleep like timeouts.  The use case is for things like full screen videos and keeping the display on while watching those.

Blocking the computer from being locked is not a supported use case

**Comment by xland** [comment]
@MarshallOfSound 

When I set the screen close timeout to 1 minute.
That code will not work too.

My setting:
![image](https://user-images.githubusercontent.com/2980915/68817053-6a485e00-06bb-11ea-8688-96b1c775bbc9.png)

**Comment by DouglasMarq** [comment]
@xland i just tested powerSaveBlocker and it is working on Electron 7.1.1

Example code: 
```javascript
const { app, BrowserWindow, Menu, powerSaveBlocker } = require('electron');

{...creating a window without menu there...}

app.on('ready', () => {
  createWindow();
  powerSaveBlocker.start('prevent-display-sleep');
});
```
In your code you are starting powerSaveBlocker and immediately stopping it, also, you are stopping the powerSaveBlocker on event "lock-screen". 

The powerMonitor event "lock-screen" only fires if the system is about to lock the screen, it does not prevent it.

If you want to stop the display from sleeping, you must start it and leave it running. Can you start it, and leave it running and test if it is indeed not working?

![energy-settings](https://user-images.githubusercontent.com/11037395/68858740-771d7f80-06c4-11ea-9664-0f370179e9ea.png)

**Comment by xland** [comment]
Yes，I see.

I thought  `powerSaveBlocker.stop` is stop the `display sleep` event

Sorry to bother you.
