### ISSUE TITLE
Electron 7.1.0 form fields render not as intended

### ISSUE THREAD

**Issue by ameerahm** [electron/electron#21010]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v7.1.0
* **Operating System:**
  * macOS 10.15
* **Last Known Working Electron version:**
  * v6.1.4

### Expected Behavior
Form fields should render as intended

### Actual Behavior
Form fields render differently in v7.1.0

### To Reproduce
Gist for electron fiddle
https://gist.github.com/daeb3a9bbc5d7b40efea41a9c55042da

Previous version 

### Screenshots

v6.1.4 (expected render)
<img width="798" alt="Screen Shot 2019-11-06 at 3 49 39 PM" src="https://user-images.githubusercontent.com/26329051/68337063-b5f07b80-00ad-11ea-9040-c08018d0517b.png">

v7.1.0 (messed up render)
<img width="802" alt="Screen Shot 2019-11-06 at 3 49 26 PM" src="https://user-images.githubusercontent.com/26329051/68337083-c0ab1080-00ad-11ea-9cd1-305f1c909679.png">

### Additional Information

Thank you for your help. If you can point me in the right direction, I'd be happy to submit a PR to help out.

**Comment by nornagon** [comment]
Can you provide a repro case that's fully self-contained? Ideally using [Electron Fiddle](https://github.com/electron/fiddle). Without knowing what you're running on `localhost:4000` there's no way for us to reproduce what you're seeing.

**Comment by ameerahm** [comment]
Thanks for your immediate response. Sure, will revert with fiddle.

**Comment by ameerahm** [comment]
couldn't exactly reproduce but there is a significant difference in rendering in the two versions below

here is the gist:
https://gist.github.com/daeb3a9bbc5d7b40efea41a9c55042da

v6.1.4 (expected render)
<img width="798" alt="Screen Shot 2019-11-06 at 3 49 39 PM" src="https://user-images.githubusercontent.com/26329051/68337063-b5f07b80-00ad-11ea-9040-c08018d0517b.png">

v7.1.0 (messed up render)
<img width="802" alt="Screen Shot 2019-11-06 at 3 49 26 PM" src="https://user-images.githubusercontent.com/26329051/68337083-c0ab1080-00ad-11ea-9cd1-305f1c909679.png">

**Comment by t57ser** [comment]
Opening the file in chrome (78) has the same result as in electron v7. Pretty sure this is not an electron issue
![Capture](https://user-images.githubusercontent.com/10595986/68385801-dcb8bb80-015a-11ea-87cf-5ce2a1857475.PNG)

**Comment by ameerahm** [comment]
Thanks @t57ser for checking it in chrome. I have posted the bug in chromium here:

https://bugs.chromium.org/p/chromium/issues/detail?id=1022471
