### ISSUE TITLE
window.URL.createObjectURL crashes when running from a network share drive (e.g. '\\')

### ISSUE THREAD

**Issue by capc0** [electron/electron#21029]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  7.1.0
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**

### Expected Behavior

The function should be callabe the same as if the electron app runs from a local drive (e.g. C:\)

### Actual Behavior

The renderer crashes

### To Reproduce

Try to set the src tag of an image with
```
source = this.domSanitizer.bypassSecurityTrustUrl(window.URL.createObjectURL(fileObjectOrBlob));
```

### Additional Information

maybe related to https://github.com/electron/electron/issues/17460

**Comment by capc0** [comment]
a workaround is to convert the blob to a base64 data url.
I guess the browser does not perform a "network" request in that case

```
const reader = new FileReader();
reader.onloadend = () => {
    source = this.domSanitizer.bypassSecurityTrustUrl(reader.result as string);
};
reader.readAsDataURL(fileObjectOrBlob);
```

**Comment by burningTyger** [comment]
maybe also #20750

**Comment by wokeyi** [comment]
In my case, set `true` for app.allowRendererProcessReuse and then run `URL.createObjectURL(new Blob())` in webview will crash the electron app
my electron version is 8.2.2

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
