### ISSUE TITLE
Electron Apps no longer working on Mac Catalina?

### ISSUE THREAD

**Issue by omarel1** [electron/electron#21023]
Has anyone noticed that Electron Apps can no longer be opened on the latest Mac Catalina os? A Mac dialog box just says Mac can no longer open this app, whereas on Mojave it opens with no issues. Are there any reports and solutions regarding this?

**Comment by poiru** [comment]
You need to notarize your app. See https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/

**Comment by omarel1** [comment]
I'm not sure if that's the case, because you mention all MAC versions 10.14.5 and higher. However, a computer with 10.14.6 on Mojave has no issues opening the app. 

The message also doesn't say anything about malicious content. It just says "The application xxxx can't be opened"

**Comment by stevenroussey-privicy** [comment]
Notarization has different rules for 10.14.x and 10.15.x. Also has different rules per developer account. New account must notarize now, and older accounts have different dates to comply.

**Comment by codebytere** [comment]
Closing in agreement with the above.
