### ISSUE TITLE
Galaxy note 9 issue, i have a bug but not sure where to start

### ISSUE THREAD

**Issue by daverose1241** [electron/electron#21027]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
* **Operating System:**
  * 
* **Last Known Working Electron version:**
  *

**Comment by MarshallOfSound** [comment]
This appears to have been opened by mistake.  The Galaxy Note 9 is an android device and Electron does not run on Android
