### ISSUE TITLE
Double click not working in macOS open file dialog

### ISSUE THREAD

**Issue by lutzroeder** [electron/electron#21032]
### Issue Details

* **Electron Version:** 7.1.0
* **Operating System:** macOS 10.15.1

### Expected Behavior
Can double click in open file dialog.

### Actual Behavior
Double click not working.

### To Reproduce
1. Unzip [electron-21032.zip](https://github.com/electron/electron/files/3819246/electron-21032.zip)
2. `npm install`
3. `npx electron .`
4. Press `Cmd-O`
5. Double click file

Works when the dialog is opened by clicking on the menu item and not using the shortcut.

**Comment by codebytere** [comment]
@lutzroeder is this issue specific to Catalina? i can't reproduce this on Mojave with that version.

**Comment by popod** [comment]
@codebytere I think no.. I sometimes have the same problem with 10.14.6 (Mojave).

**Comment by lutzroeder** [comment]
@codebytere I does not repro on latest Catalina anymore either.
