### ISSUE TITLE
An error ocurred creating the file EROFS: read-only file system, open '/tmp/.mount_Test WaamJmVl/resources/{filename}'

### ISSUE THREAD

**Issue by sakshidebut** [electron/electron#21031]
* **Electron Version**:   4.2.5

* **Target**: Linux Ubuntu 16.04 LTS

I am getting following error when opening the Linux build. 
An error ocurred creating the file EROFS: read-only file system, open '/tmp/.mount_Test WaamJmVl/resources/{filename}'

For Windows and MAC, it is working fine. When desktop application is opened then i am creating a file at app path from electron. File is getting created at my application folder (/var/www/html/{filename}) when run the build by using this command (npm run electron) but it is not getting created when opening the binary file.

Command which i have used to create build/binary is **npx electron-builder**. I am using electron to package my Angular application. 

**Path where file is created.**
path.join(app.getAppPath(), '..', name) -> name is the variable for filename.

**package.json**
{
    "name": "test",
    "version": "0.0.2",
    "description": "Test App",
    "homepage": "http://test.com/",
    "author": {
        "name": "Test Team",
        "email": "info@test.com"
    },
    "main": "main.js",
    "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "build": "ng build",
        "test": "ng test",
        "lint": "ng lint",
        "e2e": "ng e2e",
        "electron": "ng build --prod && electron .",
        "win": "node installers\\windows\\createinstaller.js",
        "pack": "node_modules\\.bin\\electron-packager . Wallet-app --overwrite  --icon=src/assets/icons/win/icon.ico --asar=true --platform=win32 --arch=ia32 --prune=true --out=release-build --version-string.CompanyName=\"Test\" --version-string.FileDescription=\"Test\" --version-string.ProductName=\"Test\""
    },
    "private": true,
    "dependencies": {
        "@angular/animations": "^6.1.0",
        "@angular/common": "^6.1.0",
        "@angular/compiler": "^6.1.0",
        "@angular/core": "^6.1.10",
        "@angular/forms": "^6.1.0",
        "@angular/http": "^6.1.0",
        "@angular/platform-browser": "^6.1.0",
        "@angular/platform-browser-dynamic": "^6.1.0",
        "@angular/router": "^6.1.10",
        "@ng-bootstrap/ng-bootstrap": "^4.2.1",
        "axios": "^0.19.0",
        "bootstrap": "^4.3.1",
        "core-js": "^2.5.4",
        "cryptr": "^4.0.2",
        "electron-installer-dmg": "^3.0.0",
        "electron-installer-windows": "^1.1.1",
        "electron-json-storage": "^4.1.6",
        "font-awesome": "^4.7.0",
        "i": "^0.3.6",
        "jquery": "^3.3.1",
        "ngx-spinner": "^7.0.0",
        "ngx-toastr": "^10.0.0",
        "node-forge": "^0.9.1",
        "npm": "^6.9.0",
        "popper.js": "^1.14.7",
        "rxjs": "6.3.3",
        "rxjs-compat": "6.3.3",
        "zone.js": "~0.8.26"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "~0.8.0",
        "@angular/cli": "~6.2.3",
        "@angular/compiler-cli": "^6.1.0",
        "@angular/language-service": "^6.1.0",
        "@types/jasmine": "~2.8.8",
        "@types/jasminewd2": "~2.0.3",
        "@types/jquery": "^3.3.29",
        "@types/node": "^8.9.5",
        "codelyzer": "~4.3.0",
        "electron": "^4.1.3",
        "electron-packager": "^13.1.1",
        "electron-winstaller": "^3.0.4",
        "jasmine-core": "~2.99.1",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~3.0.0",
        "karma-chrome-launcher": "~2.2.0",
        "karma-coverage-istanbul-reporter": "~2.0.1",
        "karma-jasmine": "~1.1.2",
        "karma-jasmine-html-reporter": "^0.2.2",
        "protractor": "~5.4.0",
        "ts-node": "~7.0.0",
        "tslint": "~5.11.0",
        "typescript": "~2.9.2"
    },
    "build": {
        "productName": "Test",
        "win": {
            "icon": "dist/assets/icons/win/1024x1024.ico",
            "target": [
                {
                    "target": "nsis",
                    "arch": [
                        "x64",
                        "ia32"
                    ]
                }
            ]
        },
        "mac": {
            "icon": "dist/assets/icons/mac/1024x1024.icns",
            "target": [
                {
                    "target": "dmg"
                }
            ]
        },
        "linux": {
            "artifactName": "Test",
            "executableName": "Test",
            "icon": "dist/assets/icons/png/1024x1024.png",
            "target": [
                {
                    "target": "AppImage"
                }
            ]
        },
        "directories": {
            "output": "release/"
        }
    }
}

Any help would be greatly appreciated!

**Comment by ttomaszewski** [comment]
+1 @sakshidebut did you ever find a solution to this?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!

**Comment by andirsun** [comment]
https://stackoverflow.com/questions/60881343/electron-problem-creating-file-error-erofs-read-only-file-system
