### ISSUE TITLE
clientRequest leaks net::ERR_HTTP_RESPONSE_CODE_FAILURE as unhandled exception

### ISSUE THREAD

**Issue by kwonoj** [electron/electron#21046]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.1
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * Unknown

### Expected Behavior
do not raise subsequent unhandled exception after response event received

### Actual Behavior
Unhandled exception raised:

```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: net::ERR_HTTP_RESPONSE_CODE_FAILURE

[OK]
```

### To Reproduce

```
git clone https://github.com/kwonoj/clientrequest-response-code-failure
npm install && npm start
```

### Screenshots

![image](https://user-images.githubusercontent.com/1210596/68459094-410a6800-01b9-11ea-969b-3851c6b9b356.png)

### Additional Information

Setting up `response` eventhandler correctly forwards 404 response, but right after unhandled exception is thrown. This is not caught by `error` eventhandler - regardless of setting up eventhandler or not, unhandled exception is always thrown.

**Comment by nornagon** [comment]
https://github.com/kwonoj/clientrequest-response-code-failure/pull/1

**Comment by nornagon** [comment]
after discussion with @kwonoj, the issue here is that you can't read the response body for non-2xx responses currently.

**Comment by brianathere** [comment]
Thanks!

**Comment by electronart** [comment]
Is there a workaround for this? Or a previous version where this works? Encountering this issue w/ IIS Server using NTLM

**Comment by true-zero** [comment]
This is still an issue and was never actually fixed.

**Comment by nornagon** [comment]
@true-zero what version of Electron are you using? I tried the repro in the OP here on Electron 7.1.3 and it seemed to me to be working correctly.

**Comment by danielehrhardt** [comment]
> @true-zero what version of Electron are you using? I tried the repro in the OP here on Electron 7.1.3 and it seemed to me to be working correctly.

My Problem is if i delete all Files on the Server like the latest.yml and check for Updates i get this Error. How could we fix this?

**Comment by joshuef** [comment]
I'm seeing this error when receiving a 404 response in webview, using electron 7.1.5 and 7.1.6.

404 response body is not loaded and a `did-fail-load` error is seen.

**Comment by anjalichhabra29** [comment]
I'm still facing same issue in Electron version 80. 
Test case is working fine when running on Chrome but not on Electron(Headless or UI both). Its the case to catch 400 response of API using XMLHTTPRequest. Please suggest
