### ISSUE TITLE
On Windows , can't resize app using bottom or right edge if I specify min height and width

### ISSUE THREAD

**Issue by pashvin** [electron/electron#21057]
### Preflight Checklist

* [ x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:
7.1.1
* **Operating System:**
Windows
* **Last Known Working Electron version:**
6.x

### Expected Behavior
App resize behaviour should not change due to min height and width

### Actual Behavior
When min height and width provided you can't resize using bottom and right edge of app

### To Reproduce
take sample form https://github.com/electron/electron-quick-start
change code of main.js. 
In create browser window pass minHeight: 650,  minWidth: 850,
start app and see there is no way to resize top bottom or right
Top and left edge work fine.

**Comment by pashvin** [comment]
Looks like once it reach min , then bottom / right resize stop working which may be how it is coded but that is bad behavior. it should stop from reducing size but should not stop increasing it

**Comment by mlaurencin** [comment]
I tested this in the currently supported versions (10.0.0, 9.2.1, 8.5.0) and was not able to reproduce it. Is this still an issue for you?

![window-resize](https://user-images.githubusercontent.com/35157522/91500269-b6633880-e8b2-11ea-86b4-b4c43c2dd463.gif)

Electron Fiddle Gist Used: https://gist.github.com/c4783c10bfa28d4a2b3c01a04f58d4ed

**Comment by pashvin** [comment]
Yes it is working in latest version. I tried 10.x
