### ISSUE TITLE
Setting a proxy in a Session with `session.setProxy` does nothing on electron >= 5

### ISSUE THREAD

**Issue by arantes555** [electron/electron#21050]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.12, 6.1.4, 7.1.1
* **Operating System:**
  * macOS 10.14.6 / Ubuntu 19.04 x64
* **Last Known Working Electron version:**
  * 4.2.12

### Expected Behavior
When using `session.setProxy`, subesquent requests done with the `net` API with the specified session should use the proxy configured.

### Actual Behavior
Requests ignore the proxy set with `session.setProxy`

### To Reproduce

```sh
$ git clone https://github.com/arantes555/electron-bug-net-proxy.git
$ npm install
$ npm start
```

In this repo, we test this by launching a simple HTTP server and 2 proxies, and running a simple script against them using multiple versions of electron.

When running this, we can see that in electron@4, the requests correctly go through the proxy. However, starting with electron@5, the requests do not follow the proxy at all. Requests that should go through the simple unauthenticated succeed anyway, but there is no log from the proxy, and those that should go through the authenticated proxy fail when setting the proxy works (because credentials are not provided), but succeed on electron@5 and greater.

**Comment by nornagon** [comment]
Requests to `localhost` bypass proxies by default. Add `<-loopback>` to your proxy rules if you want to proxy requests to localhost, as described here: https://chromium.googlesource.com/chromium/src/+/master/net/docs/proxy.md#bypass-rule_subtract-implicit-rules
