### ISSUE TITLE
The printerinfo status does not determine whether the printer is online or offline

### ISSUE THREAD

**Issue by shaonianla1997** [electron/electron#21058]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

when calling webContents.getPrinters(), printer status does not determine whether the printer is online or offline.

**Comment by codebytere** [comment]
We are only able to plumb through the data that's available to use through Chromium, and as you can [see here](https://cs.chromium.org/chromium/src/printing/backend/print_backend.h?sq=package:chromium&dr=CSs&g=0&l=40-44) we don't have the ability to access printer online status. Should something on their end change, we're more than happy to revisit this in the future.
