### ISSUE TITLE
DNS over HTTPS Support

### ISSUE THREAD

**Issue by SpikeRaxstone** [electron/electron#21064]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

My suggestion isn't solving any problems that require fixing but it would be a major boost with privacy and security for Electron applications.

### Proposed Solution

I'm a big fan of the very new and growingly popular DoH system or DNS over HTTPS. Is there a way for developers to enable this for their electron applications?

### Alternatives Considered

If I can't enable DNS over HTTPS directly, how would I set a custom DNS provider for all requests made in an electron application?

### Additional Information

N/A

**Comment by MarshallOfSound** [comment]
The `dns-over-https` feature flag is available from chromium 78 and up (Electron 7 and up).  It will follow Chromium's policy of automatically using DNS over HTTPS as well if the users current DNS settings support it.

If you want the ability to set the DNS servers to use for a give `session` in Electron I'd suggest raising a feature request specific to that as that is a more generic request than DNS over HTTPS

**Comment by SpikeRaxstone** [comment]
Thanks for your help. The `dns-over-https` feature flag was of no help to me unfortunately and appeared to do nothing so I have taken your advice and opened a more specific feature request at #21068 to allow DNS over HTTPS toggling for specific `session`s.
