### ISSUE TITLE
DNS over HTTPS Session Toggling

### ISSUE THREAD

**Issue by spikecodes** [electron/electron#21068]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

The `dns-over-https` feature flag seems to do nothing for me when I use it on my Electron (v8.0.0-beta.2) application and as suggested by @MarshallOfSound in #21064, I'm opening a more specific feature request to directly add DNS over HTTPS toggling for certain sessions.

### Proposed Solution

I would imagine this feature looking like `session.defaultSession.enableDoH()` and `session.defaultSession.disableDoH()` respectively. Hopefully this is achievable and thank you in advance for reviewing my feature request.

### Alternatives Considered

N/A

### Additional Information

N/A

**Comment by SpikeRaxstone** [comment]
I just saw [a great article](https://www.zdnet.com/article/how-to-enable-dns-over-https-doh-in-google-chrome/) by ZDNet talking about how to enable DoH on Chrome 79 using the full feature flag:

```--enable-features="dns-over-https<DoHTrial" --force-fieldtrials="DoHTrial/Group1" --force-fieldtrial-params="DoHTrial.Group1:server/https%3A%2F%2F1.1.1.1%2Fdns-query/method/POST```

So when I get the chance, I'll try that out with Electron 8 and see if it works to how I'd like it to, I doubt it would be session specific but it could definitely be a start.

**Comment by SpikeRaxstone** [comment]
Nevermind, unfortunately no luck at all with those feature flags.

**Comment by Buminta** [comment]
I want using custom DNS in webview tag. Anyone know it please help me!
Thanks!

**Comment by nornagon** [comment]
It's worth trying those feature flags again after https://github.com/electron/electron/pull/28305.

**Comment by nornagon** [comment]
NB, see https://github.com/electron/electron/pull/30576. I'm not sure this is configurable in Chrome at a per-session level.
