### ISSUE TITLE
desktopCapturer shows black screen with mouse on Fullscreen games. 

### ISSUE THREAD

**Issue by masudhossain** [electron/electron#21063]
Building a webrtc app using desktopCapturer, but it shows a black screen on Fullscreen games (using League of Legends), but shows the mouse cursor from in game. Switching to windowed mode instantly fixes the issue. 

Code is typical desktopCapturer api from electron docs. 

Electron version: 6.0.12

example code: 
```
desktopCapturer.getSources({ types: ['window', 'screen'], thumbnailSize: {width:0, height: 0} }).then(sources => {
  console.log('sources:', sources)
  for (const source of sources) {

// Check if in array of gameArray
  navigator.mediaDevices.getUserMedia({
    audio: false,
    video: {
      mandatory: {
        chromeMediaSource: 'desktop',
        chromeMediaSourceId: source.id,
        minFrameRate: Math.round(60),
        maxFrameRate: Math.round(60)
      }
    }
  }).then(stream => {
    console.log("stream found. but will show black screen.")
  });
	}
})
```

**Comment by xudeming208** [comment]
我也遇到了这个问题，通过navigator.mediaDevices.getUserMedia获取到的stream写入到video，然后利用canvas将video写入到image的src，得到的image也是黑屏。我试了electron的1.8.8和3.1.13都没有问题，可以得到全屏的截图

**Comment by xudeming208** [comment]
I also encountered this problem, through the navigator. MediaDevices. GetUserMedia access to write to the video stream, and then use canvas will write to the video image SRC, the image is also a black screen. I tried 1.8.8 and 3.1.13 of electron without any problem, and the screenshot of full screen can be obtained

**Comment by xudeming208** [comment]
主要代码如下：
`// handleStream
function handleStream(stream) {
	let video = document.createElement('video');

	video.addEventListener('loadedmetadata', () => {
		// 创建canvas
		let canvas = document.createElement('canvas');
		canvas.width = currentWidth * ratio;
		canvas.height = currentHeight * ratio;
		let ctx = canvas.getContext('2d');
		ctx.drawImage(video, 0, 0, currentWidth * ratio, currentHeight * ratio);
		video.remove();

		// 操作img
		imgDom.src = canvas.toDataURL();
	}, false);

	video.srcObject = stream;
	document.body.appendChild(video);
}


// 创建蒙版窗口
function getUserMedia(id) {
	navigator.mediaDevices.getUserMedia({
		audio: false,
		video: {
			mandatory: {
				chromeMediaSource: 'desktop',
				chromeMediaSourceId: id,
				minWidth: currentWidth,
				maxWidth: currentWidth * ratio,
				minHeight: currentHeight,
				maxHeight: currentHeight * ratio
			}
		}
	}).then(stream => {
		handleStream(stream);
	}).catch(error => {
		handleError(error);
	});
}

desktopCapturer.getSources({
	types: ['screen']
}).then(soruces => {
	getUserMedia(soruces[0].id);
})`

**Comment by xudeming208** [comment]
主要代码如下：
```javascript
// handleStream
function handleStream(stream) {
	let video = document.createElement('video');

	video.addEventListener('loadedmetadata', () => {
		// 创建canvas
		let canvas = document.createElement('canvas');
		canvas.width = currentWidth * ratio;
		canvas.height = currentHeight * ratio;
		let ctx = canvas.getContext('2d');
		ctx.drawImage(video, 0, 0, currentWidth * ratio, currentHeight * ratio);
		video.remove();

		// 操作img
		imgDom.src = canvas.toDataURL();
	}, false);

	video.srcObject = stream;
	document.body.appendChild(video);
}


// 创建蒙版窗口
function getUserMedia(id) {
	navigator.mediaDevices.getUserMedia({
		audio: false,
		video: {
			mandatory: {
				chromeMediaSource: 'desktop',
				chromeMediaSourceId: id,
				minWidth: currentWidth,
				maxWidth: currentWidth * ratio,
				minHeight: currentHeight,
				maxHeight: currentHeight * ratio
			}
		}
	}).then(stream => {
		handleStream(stream);
	}).catch(error => {
		handleError(error);
	});
}

desktopCapturer.getSources({
	types: ['screen']
}).then(soruces => {
	getUserMedia(soruces[0].id);
})

```

**Comment by xudeming208** [comment]
electron 4.2.8版本之前可以正常显示屏幕全屏，4.2.8就显示黑屏了。
```javascript
v4.2.8发行说明
修正
修复了使用Javascript从DOM中删除HTML5视频元素时的内存泄漏。＃19347
```

**Comment by zxch3n** [comment]
I solved this based on #19177

i.e.

```javascript
// handleStream
function handleStream(stream) {
	let video = document.createElement('video');

	video.addEventListener('loadedmetadata', () => {
		video.pause();
		// 创建canvas
		let canvas = document.createElement('canvas');
		canvas.width = currentWidth * ratio;
		canvas.height = currentHeight * ratio;
		let ctx = canvas.getContext('2d');
		ctx.drawImage(video, 0, 0, currentWidth * ratio, currentHeight * ratio);
		video.remove();

		// 操作img。此处得到的图片是黑屏
		imgDom.src = canvas.toDataURL();
	}, false);

	video.srcObject = stream;
	video.play();
	document.body.appendChild(video);
}
```

**Comment by NoelDavies** [comment]
anybody fixed this for video? I need a video stream :(

**Comment by masudhossain** [comment]
> 主要代码如下：
> 
> ```js
> // handleStream
> function handleStream(stream) {
> 	let video = document.createElement('video');
> 
> 	video.addEventListener('loadedmetadata', () => {
> 		// 创建canvas
> 		let canvas = document.createElement('canvas');
> 		canvas.width = currentWidth * ratio;
> 		canvas.height = currentHeight * ratio;
> 		let ctx = canvas.getContext('2d');
> 		ctx.drawImage(video, 0, 0, currentWidth * ratio, currentHeight * ratio);
> 		video.remove();
> 
> 		// 操作img。此处得到的图片是黑屏
> 		imgDom.src = canvas.toDataURL();
> 	}, false);
> 
> 	video.srcObject = stream;
> 	document.body.appendChild(video);
> }
> 
> 
> // 创建蒙版窗口
> function getUserMedia(id) {
> 	navigator.mediaDevices.getUserMedia({
> 		audio: false,
> 		video: {
> 			mandatory: {
> 				chromeMediaSource: 'desktop',
> 				chromeMediaSourceId: id,
> 				minWidth: currentWidth,
> 				maxWidth: currentWidth * ratio,
> 				minHeight: currentHeight,
> 				maxHeight: currentHeight * ratio
> 			}
> 		}
> 	}).then(stream => {
> 		handleStream(stream);
> 	}).catch(error => {
> 		handleError(error);
> 	});
> }
> 
> desktopCapturer.getSources({
> 	types: ['screen']
> }).then(soruces => {
> 	getUserMedia(soruces[0].id);
> })
> ```

Does this fix the stream showing black or just the appending of the video element?

**Comment by EmptyCrown** [comment]
Was this resolved? Facing this issue where I'm simply writing the stream to a video file in memory and it just has black frames (with a mouse).

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by giuliohome** [comment]
I've tried on Fedora 34 with Gnome Wayland. I had a black screen when I selected "Entire Desktop".
I tried `app.disableHardwareAcceleration();` but the screen for "Entire Desktop" was still black.
Finally I configured the login with Gnome X11 instead of Wayland and I could see "Screen 1" instead of "Entire Desktop" and the recording stream was working fine - not black - and I found also a few other sources (Firefox, Nautilus) that were not present in Wayland (there I could see only Electron applications like Studio Code, the running app and a not working Entire Desktop)

**Comment by sajeebchandan** [comment]
So, what I found is that 3 issues.

1. Make sure that on Linux you're sending 
`chromeMediaSource: process.platform == 'win32' ? 'desktop' : 'screen'`

2. Make sure that **you're not doing this.**
`videoElement.srcObject = null;`

3. Make sure that you're passing actual type of screen id
`chromeMediaSourceId: source.id`

That's it. Everything will be cool.

**Comment by KongYy1** [comment]
`async loadDesktopProcess() {
        const sources = await desktopCapturer.getSources({
            types: ['window','screen'],
            fetchWindowIcons: true
        })
        const selectContainer = document.getElementById('share-list');
        for (const obj of sources) {
            const videoElement = document.createElement('video');
            const stream = await navigator.mediaDevices.getUserMedia({
            audio: false,
            video: {
                mandatory: {
                    chromeMediaSource: 'desktop',
                    chromeMediaSourceId: obj.id
                }
            }
          })


        
            videoElement.addEventListener('loadedmetadata', (event) => {
                videoElement.play()
            }, false);
            videoElement.srcObject = stream
            selectContainer.appendChild(videoElement)
        
        }
    }`

**Comment by KongYy1** [comment]
```javascript
async function loadDesktopProcess() {
    const sources = await desktopCapturer.getSources({
        types: ['window','screen'],
        fetchWindowIcons: true
    })
    const selectContainer = document.getElementById('share-list');
    for (const obj of sources) {
        const videoElement = document.createElement('video');
        const stream = await navigator.mediaDevices.getUserMedia({
            audio: false,
            video: {
                mandatory: {
                    chromeMediaSource: 'desktop',
                    chromeMediaSourceId: obj.id
                }
            }
        })
        videoElement.addEventListener('loadedmetadata', (event) => {
            videoElement.play()
        }, false);
        videoElement.srcObject = stream
        selectContainer.appendChild(videoElement)
    }
}
```  
May I ask if there is any problem with my code? Some of the captured video sources are black, but the mouse (such as Vscore) can be seen. Electron version: 6.1.7
