### ISSUE TITLE
Postinstall stuck

### ISSUE THREAD

**Issue by kostia** [electron/electron#21069]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.1
* **Operating System:**
  * macOS 10.13.6
* **Last Known Working Electron version:**
  * None

### Expected Behavior
Can install electron, i.e. postinstall hook finishes eventually

### Actual Behavior
Cannot install electron: The postinstall hook hangs forever

### To Reproduce
`npm install electron`

### Screenshots
<img width="876" alt="Bildschirmfoto 2019-11-10 um 18 17 53" src="https://user-images.githubusercontent.com/9946/68547819-7051ec80-03e6-11ea-9f72-b51719abc703.png">

### Additional Information
Waited for it to finish for 30 minutes.
Restarted the OS, then tried to install again and waited again for 30 minutes.

**Comment by LoveSponge** [comment]
I was facing the same issue, haven't looked at the cause but any dev's or anyone else who comes across this note the following:

I know it's not ideal but removing electron and re-installing 7.1.0 worked for me:

`npm r electron`

`npm i electron@7.1.0 --save`

after that, everything became zen and i remembered the meaning of life <3

**Comment by Sestowner** [comment]
I have the same issue on Linux Mint 19.1. I use `node v13.1.0` and `npm 6.12.1`

**Comment by ElegyD** [comment]
It may seem stuck, but it is actually downloading the release zip of Electron from GitHub.
But GitHub's downloads are currently slow (~40KB/s for me) so just give it a while.
The zip is around 60 MB. You can see the progress in the Network tab of the Activity Monitor in macOS.

**Comment by kostia** [comment]
> It may seem stuck, but it is actually downloading the release zip of Electron from GitHub.
> But GitHub's downloads are currently slow (~40KB/s for me) so just give it a while.
> The zip is around 60 MB. You can see the progress in the Network tab of the Activity Monitor in macOS.

Yes, that's probably the download. Waiting for it to finish is the way to go.

But: People usually do not have the Activity Monitor open all the time. Also people usually do not expect a software download to take 20 minutes. And if a software download takes 20 minutes, then they usually expect it to be somehow indicated (progress bar for example).

Waiting for 20 minutes without any hint about what's going on and when it's done, asks for troubles.

**Comment by locomoco28** [comment]
I've had this issue in November 2019 and it took 35min to install.
Now I'm trying to install it again and after 2h it still didn't finish ;_;

**Comment by sushihangover** [comment]
5 hours and counting... Can not find a github connection via netstat (but do not know if there is an ip pool they are using).

Any way to manually finish the setup?

**Comment by flopes89** [comment]
Same issue here on Win10 right now, tried several times. Also, even with `--verbose` no download progress is showing up.

**Comment by devsnek** [comment]
When downloading it will show a progress bar, I'm seeing it just hang before it gets that far.

**Comment by kolyasya** [comment]
The same problem

**Comment by jkher** [comment]
+1 Same problem

**Comment by dcatteeu** [comment]
This seems like a recurring issue. It's an obstacle preventing people to get started with electron. Are there any mirrors with the latest stable version?

**Comment by marc2332** [comment]
I just tried again, it now works

**Comment by lattejed** [comment]
FYI this still seems to be happening. I've been unable to install the demo app and the npm package. Not a network issue on my end. macOS 10.14, nvm / node 13.x

**Comment by bumprat** [comment]
My solution :
1、Find electron module folder at .\node_modules\electron
2、In install.js, Find `downloadArtifact({ ... })` , then add `mirrorOptions`
3、use a mirror like taobao (https://npm.taobao.org/mirrors/electron/)
Example:
```
downloadArtifact({
  version,
  artifactName: 'electron',
  force: process.env.force_no_cache === 'true',
  cacheRoot: process.env.electron_config_cache,
  platform: process.env.npm_config_platform || process.platform,
  arch: process.env.npm_config_arch || process.arch,
  mirrorOptions: {
    mirror: 'https://npm.taobao.org/mirrors/electron/',
  }
}).then(extractFile).catch(err => {
  console.error(err.stack)
  process.exit(1)
})
```

Hope it work for you 💌

**Comment by bumprat** [comment]
> https://www.npmjs.com/package/electron-download
> 
> 
> in .npmrc :
> 
> electron_mirror="https://npm.taobao.org/mirrors/electron/

**Comment by erikwatson** [comment]
This is so frustrating.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by moeinrahimi1** [comment]
i remember back in 2019 facing this issue was the main reason not using electron. we are in 2025 and the issue still exists. is there a way to download zip file manually and place it where it belongs?
