### ISSUE TITLE
Crash on startup because of Windows Script Host error

### ISSUE THREAD

**Issue by PragmaticBeaver** [electron/electron#21067]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
"electron": "^7.1.1"

* **Operating System:**
Windows 10 Pro (1809) x64

* **Last Known Working Electron version:**
 "electron": "^6.1.4"

### Expected Behavior
Normal startup / working app.

### Actual Behavior
As soon as the main electron file gets read, the following error occurs and the application won't start:
![image](https://user-images.githubusercontent.com/8586904/68547335-82c92780-03e0-11ea-8760-da858d3a6639.png)

### To Reproduce
- download the official electron-quick-start repo at https://github.com/electron/electron-quick-start
- in the package.json, change "main": "main.js" into "main": "electron.js"
- rename main.js into electron.js
- run start-script (npm run start)
- crash with error

### Additional Information
The problem also exists in production code, in a Vue project which gets bundled and then run using electron. This problem was not present in prior Versions (6.1.4 and below).

I couldn't reproduce this behavior on my Linux mint system but on all three Windows machines in my household. All systems are running the same Windows and Node versions.

**Comment by EnderDev** [comment]
You cannot directly run `electron.js`. You need to provide the `electron` prefix for it to run. Similar to how you run node applications using `node`. Change 

```
"main": "electron.js"
```
to...
```
"main": "electron electron.js"
```

**Comment by PragmaticBeaver** [comment]
Thank you, that fixed the Problem.

**Comment by xinaesthete** [comment]
I just had a similar error even though my npm script was indeed calling electron.  I finally realised it was because the file itself was called `electron.js`.

Not sure if this should be filed as a separate issue, there may well be documentation warning against this somewhere, but hopefully at least if someone else has a similar problem in future they might find this comment.

**Comment by ChocolateLoverRaj** [comment]
I think this is what @xinaesthete  said but the docs should mention
> Do not name your main file `electron.js`.

**Comment by the-noob** [comment]
Following some tutorials I ended up with the same problem, pop-up with `Windows Script Host Error ` ... changing the `public/electron.js` to `public/elect.js` (probably any other name except `electron`) sorted it
