### ISSUE TITLE
With silent printing, the printed content is horizontally centered, I hope to start from the upper left corner

### ISSUE THREAD

**Issue by 1134506391** [electron/electron#21075]
If you don't use it, you can start printing from the upper left corner.
The only place to change is `silent: true`,
I hope that when using silent printing, the printed content is horizontally centered, starting from the upper left corner.

surroundings:
node:12.0.0
electron:7.1.1
```
        webview.print(
          {
            silent: true,
            printBackground: true,
            deviceName: this.printDeviceName,
            landscape: true
         }
}
```

**Comment by shaonianla1997** [comment]
你是用vue和electron 7.1.1搭建的项目吗  怎么搭建的

**Comment by sofianguy** [comment]
duplicate https://github.com/electron/electron/issues/21074
