### ISSUE TITLE
Unable to install Electron 7.1.1 on Raspberry PI 3 (32 bit ARM)

### ISSUE THREAD

**Issue by richardebrock** [electron/electron#21070]
* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

Unable to install Electron 7.1.1 on Raspberry PI 3 (32 bit ARM).

* **Electron Version:**
  * 7.1.1
* **Operating System:**
  * Raspbian 10

### Expected Behavior
`npm install electron --save-dev --save-exact` should successfully install Electron.

### Actual Behavior
npm install fails with:

_(node:5627) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)_

### To Reproduce

Run this command:

`npm install electron --save-dev --save-exact --verbose`

### Additional Information
Debugging the install script shows that install.js is attempting to download the following URL:

`https://github.com/electron/electron/releases/download/v7.1.1/electron-v7.1.1-linux-arm.zip`

This results in HTTP response code 404. The correct URL is:

`https://github.com/electron/electron/releases/download/v7.1.1/electron-v7.1.1-linux-armv7l.zip`

**Comment by rudam** [comment]
Hi.
I have got the same problem on RPi2 with BalenaOS. The Electron is a part of ([Balena Dashboards](https://github.com/willswire/balena-dashboards)). Here is the log...

```
[electron]    > electron@7.1.1 postinstall /usr/src/app/node_modules/electron
[electron]    > node install.js
[electron]    (node:38) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
[electron]        at EventEmitter.<anonymous> (/usr/src/app/node_modules/got/source/as-stream.js:35:24)
[electron]        at EventEmitter.emit (events.js:210:5)
[electron]        at module.exports (/usr/src/app/node_modules/got/source/get-response.js:22:10)
[electron]        at ClientRequest.handleResponse (/usr/src/app/node_modules/got/source/request-as-event-emitter.js:155:5)
[electron]        at Object.onceWrapper (events.js:300:26)
[electron]        at ClientRequest.emit (events.js:215:7)
[electron]        at ClientRequest.origin.emit (/usr/src/app/node_modules/@szmarczak/http-timer/source/index.js:37:11)
[electron]        at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:585:27)
[electron]        at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
[electron]        at TLSSocket.socketOnData (_http_client.js:454:22)
[electron]    (node:38) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[electron]    (node:38) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by metadataengine** [comment]
Same for v8.0.0-beta.2

```
> electron@8.0.0-beta.2 postinstall /usr/src/app/node_modules/electron
> node install.js

(node:8027) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (/usr/src/app/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (events.js:210:5)
    at module.exports (/usr/src/app/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/usr/src/app/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (events.js:300:26)
    at ClientRequest.emit (events.js:215:7)
    at ClientRequest.origin.emit (/usr/src/app/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:585:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
    at TLSSocket.socketOnData (_http_client.js:454:22)
(node:8027) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8027) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
+ electron@8.0.0-beta.2
```

**Comment by rudam** [comment]
Same for v8.0.0-beta.2

```
> electron@8.0.0-beta.2 postinstall /usr/src/app/node_modules/electron
> node install.js

(node:8027) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (/usr/src/app/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (events.js:210:5)
    at module.exports (/usr/src/app/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/usr/src/app/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (events.js:300:26)
    at ClientRequest.emit (events.js:215:7)
    at ClientRequest.origin.emit (/usr/src/app/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:585:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
    at TLSSocket.socketOnData (_http_client.js:454:22)
(node:8027) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8027) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
+ electron@8.0.0-beta.2
```

**Comment by jkleinsc** [comment]
@richardebrock @rudam what version(s) of Node are you using?

**Comment by flyxlee** [comment]
I meet the same problem,Do you solve this problem?

**Comment by jkleinsc** [comment]
This issue was resolved via electron/get#128

**Comment by flyxlee** [comment]
> I meet the same problem,Do you solve this problem?

I run command "npm config set arch armv71" to solve this problem

**Comment by dsanders11** [comment]
@jkleinsc, this wasn't fixed by your PR.

The install script for Electron is [providing an arch to `downloadArtifacts`](https://github.com/electron/electron/blob/a6d142a112ccc0cecd33c83ff59479f4485614ba/npm/install.js#L31-L38) which will [override the value](https://github.com/electron/get/blob/2e22564d2fd28a3a867dbdc7e277e16a3deec9f4/src/index.ts#L60-L68). As such, the value of `getNodeArch` is discarded, so it can't resolve this issue, since it isn't used.

It looks like the npm install script shouldn't be providing `process.arch` as a fallback for arch since that will short-circuit the work of `getNodeArch`, and `downloadArtifact` needs better logic for merging the options, it should probably read:

```
    {
        ..._artifactDetails,
        platform: _artifactDetails.platform || process.platform,
        arch: _artifactDetails.arch || getHostArch(),
      };
```

**Comment by jkleinsc** [comment]
@dsanders11 you are correct.  I missed the fact that the install script passes the arch.

As @flyxlee mentioned, running `npm config set arch armv7l` or `export npm_config_arch=armv7l` before running npm install will fix this issue.

**Comment by dsanders11** [comment]
> As @flyxlee mentioned, running npm config set arch armv7l or export npm_config_arch=armv7l before running npm install will fix this issue.

@jkleinsc, is this the long-term fix, or just until it's fixed in the code? Would be nice to have it work out-of-the-box.

**Comment by jkleinsc** [comment]
@dsanders11 in my testing on my Raspberry PI it works fine even without setting the arch.  I'm guessing certain versions of node and/or OSes set `process.env.npm_config_arch` or `process.arch` to `arm` which then causes this failure.

In regards to fixing it, sure if someone wants to fix it that would be great.  I don't have time to look into it right now.

**Comment by richardebrock** [comment]
Excellent, `npm config set arch armv7l` works for me, thanks @flyxlee and @jkleinsc
