### ISSUE TITLE
使用静默打印，打印出来的内容是水平居中的，希望从左上角开始

### ISSUE THREAD

**Issue by 1134506391** [electron/electron#21074]
不使用则是从左上角开始打印，
唯一改变的地方`silent: true,`
希望在使用静默打印的时候，打印出来的内容是不是水平居中的，是从左上角开始

环境:
node:12.0.0
electron:7.1.1

```
        webview.print(
          {
            silent: true,
            printBackground: true,
            deviceName: this.printDeviceName,
            landscape: true
         }
}
```

**Comment by shaonianla1997** [comment]
你说中文是没有用滴

**Comment by xland** [comment]
@1134506391 
我来理你，嘿嘿

我试了一下，没任何问题，代码和截图如下：

```js
let { remote } = require("electron");
let webContents = remote.getCurrentWebContents();
webContents.print({
  silent: true,
  printBackground: true,
  deviceName: this.printDeviceName,
  landscape: true
});
```
左侧PDF是生成的打印文件
![image](https://user-images.githubusercontent.com/2980915/68817825-e93e9600-06bd-11ea-81a6-2ac6deacc51a.png)

**Comment by sofianguy** [comment]
Hello @1134506391, it looks like @xland has a solution. Please try that and report back if you are still having issues.
