### ISSUE TITLE
Electron Back Button/gesture

### ISSUE THREAD

**Issue by Piflyer** [electron/electron#21085]
Hi, I'm trying to create a smart display via a web app. I have decided to include different pages that serve as "apps" like video calling and smart home control. I was wondering if it is possible to incorporate a touchscreen gesture like sliding your finger from left to right or showing just a back button on Electron. Thanks!

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
