### ISSUE TITLE
should doc contents.id with more details

### ISSUE THREAD

**Issue by bruceauyeung** [electron/electron#21087]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

this issue is actually about document enhancement.
quoted from https://electronjs.org/docs/api/web-contents#contentsid-readonly   

> A Integer representing the unique ID of this WebContents.

this description is too simple, i think the following information should be documented here:
1. in what scope is this `id` unique ? within entire electron app or owner `BrowserWindow` ?
2. what algorithm is used to generate this unique `id` ?

**Comment by MarshallOfSound** [comment]
> in what scope is this id unique ? within entire electron app or owner BrowserWindow ?

The entire electron app

> what algorithm is used to generate this unique id ?

There is no specific algorithm we should define or document so as to avoid lock in.  All we can document is that the at any one time the ID of an active webContents is unique to that webContents.   i.e. A Integer repsenting the unique ID of this webContents.

The implementation details should not be documented in case we ever need to change the implementation.  All that matters is that it is a number unique to that `webContents`.  If you want to raise a PR adding clarification in that area.  Go for it 👍

**Comment by bruceauyeung** [comment]
@MarshallOfSound ok, i will do it later.
thanks for clarification!
