### ISSUE TITLE
Second Instance not getting Called

### ISSUE THREAD

**Issue by EtashGuha** [electron/electron#21083]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.2.12
* **Operating System:**
  * MacOS 10.14.6
* **Last Known Working Electron version:**
  * None

### Expected Behavior

I open an app. Then, I open the app a second time. The part with
```javascript
app.on('second-instance', (event, commandLine, workingDirectory) => {
        // Someone tried to run a second instance, we should focus our window.
        console.log("HERERERER")
        console.log(event)

})
```
should catch it. It should print out recognizing that the electron app was told to open a second time.
### Actual Behavior

I open the app the first time. When I open it a second time, it does not create a new instance. The previous instance does not print out anything recognizing a second instance was told to be created.
### To Reproduce

Here is the code I used for the electron app.
```javascript
app.requestSingleInstanceLock()

app.on('second-instance', (event, commandLine, workingDirectory) => {
        // Someone tried to run a second instance, we should focus our window.
        console.log("HERERERER")
        console.log(event)

})

app.on('ready', function() {
    createWindow()
});
```

### Additional Information

I am creating a PDF reader. When a user clicks on a PDF, it automatically opens with my app. However, when they open a different PDF the second time, it does not open nor does the original instance say anything about an attempt to open a second thing.

**Comment by arantes555** [comment]
@EtashGuha Your code does not appear to quit when `requestSingleInstanceLock` returns `false`, which it should ( https://github.com/electron/electron/blob/v4.2.12/docs/api/app.md#apprequestsingleinstancelock )

Also, I believe this is very linked to the build-process you are using, as this depends on the AppID that is set by the build system.

**Comment by EtashGuha** [comment]
I am using electron-builder. 
```json
"build": {
    "afterSign": "scripts/notarize.js",
    "appId": "com.github.EtashGuha.Etude",
```
This is how I set the appID in my package.json.
Also, I really don't want a singleInstanceLock. I want multiple instances of the application to be able to be opened at one time. Any idea?

**Comment by arantes555** [comment]
@EtashGuha On macOS you cannot have multiple instances running : the system already enforces a single instance lock. What is happening to you right now is only that you are not seeing the `second-instance` event, because macOs prevents it from being run at all.

This is actually explained in detail in the `requestSingleInstanceLock` doc : 
> On macOS the system enforces single instance automatically when users try to open a second instance of your app in Finder, and the open-file and open-url events will be emitted for that. However when users start your app in command line the system's single instance mechanism will be bypassed and you have to use this method to ensure single instance.

Also, I should add that when the app is already opened and you try to re-open the app itself, not a file, it's the `activate` event that is sent (this bit seems to be missing from this part of the doc)
