### ISSUE TITLE
autoUpdater error event when first checking update

### ISSUE THREAD

**Issue by trae-op** [electron/electron#21080]
I have checking update when start first app. After adding a new version to the server and when first start app 2 events **(checking-for-update, update-available**) are successful, then **error** and text message _ENOENT: no such file or directory, rename 'C:\Users\QA\AppData\Local\rmclient-updater\pending\my-app.exe'_. After second open app, update is successful

const { autoUpdater } = require('electron-updater');

autoUpdater.on('checking-for-update', (event) => mainWindow.webContents.send('Checking for update...'));
autoUpdater.on('update-available', (ev, info) =>mainWindow.webContents.send('Update available.'));
autoUpdater.on('update-not-available', (ev, info) =>mainWindow.webContents.send('Update not available.'));
**// activated error event**
autoUpdater.on('error', (ev, err) =>mainWindow.webContents.send('Error in auto-updater: ${err ? err.toString() : ev.toString()}'));
autoUpdater.on('download-progress', (progressObj) =>mainWindow.webContents.send('Download progress: ${progressObj.percent}'));
autoUpdater.on('update-downloaded', (progressObj) =>mainWindow.webContents.send('A new version has been downloaded. Restart the application to apply the updates'));

**Comment by MarshallOfSound** [comment]
`electron-updater` is not the official Electron `autoUpdater` module.  It is a third party community module.  You should raise this issue with them.
