### ISSUE TITLE
TouchBar Api is broken above v4.2.12

### ISSUE THREAD

**Issue by hah** [electron/electron#21094]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.0 and above 
* **Operating System:**
  * macOS 10.15 
* **Last Known Working Electron version:**
  * 4.2.12

Hey, I was trying to get the touchbar api work as per this example:
https://electronjs.org/docs/api/touch-bar#examples

### Expected Behavior
The "spin" button from the example should show up

### Actual Behavior
It does nothing with the touchbar

**Comment by codebytere** [comment]
Do you also experience this issue on macOS 10.14? I am unable to replicate this - it works perfectly for me on all supported versions.

**Comment by hah** [comment]
sorry, probably my computer is messing with me, it works perfectly for me as well 🤦‍♂️
