### ISSUE TITLE
Draggable transparent frameless window background glitch (windowas

### ISSUE THREAD

**Issue by eladmeidar** [electron/electron#21102]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
6.0.9
* **Operating System:**
Windows 10 pro (1903)
* **Last Known Working Electron version:**
Unknown

### Expected Behavior
When dragging a frameless, transparent window (using `-webkit-app-region: drag;`) out of screen bounds (when part of the window is outside the desktop viewable area), it should remain transparent when dragged back to the viewport.

### Actual Behavior
When a frameless, transparent window is being dragged out of the screen, the out-of-bounds transparent background turns to black when coming back to the viewport. Worth mentioning that it does not happen EVERY time. but rather occasionally.

### To Reproduce
Hard, only happens sometimes.

**Comment by sofianguy** [comment]
We cannot debug further without repro steps (preferably with [Electron fiddle](https://github.com/electron/fiddle) or [electron-quick-start](https://github.com/electron/electron-quick-start)). Please reach out if this is happening consistently and can provide us with repro steps.
