### ISSUE TITLE
Please provide "disable more private api" patch for Electron 4.x

### ISSUE THREAD

**Issue by circleapps** [electron/electron#21111]
I know Electron is not supporting Electron 4.x since Oct 22, 2019.

But after Electron 5.0, NaCL is dropped, which is the way my app used to play local video files. I have to stick to Electron 4.x for now.

If Electron don't provide this patch, I will not be able to submit any new updates to Mac App Store.

PLEASE consider providing a patch for Electron 4.x, thanks.

**Comment by nornagon** [comment]
Sorry, we don't release new versions for the 4.x series. We have limited resources and we can't afford to spread them further than we already do.

**Comment by circleapps** [comment]
I understand, but I believe I'm not the only one.

Consider the difficulty I'm facing right now, I will not start any new project with Electron, it is too risky.

**Comment by circleapps** [comment]
Anyway, thanks for letting me it is not possible.
I will try to find a reasonable solution for this issue, the worst case is that I have to move to some other app store to publish my app.
