### ISSUE TITLE
TypeError: sender.emit is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by tommoor** [electron/electron#21112]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.0.0-beta.2
* **Operating System:**
  * macOS 10.14.5
* **Last Known Working Electron version:**
  * v6.1.X 

### Expected Behavior
No warnings

### Actual Behavior
The warning

```
[28455:1113/114404.211707:ERROR:CONSOLE(3361)] "Uncaught TypeError: sender.emit is not iterable (cannot read property Symbol(Symbol.iterator))", source: electron/js2c/sandbox_bundle.js (3361)
```

is printed in the console constantly.

### Screenshots

![image](https://user-images.githubusercontent.com/380914/68798485-5cd39b00-060b-11ea-80d9-1f62cbb97e52.png)

**Comment by nornagon** [comment]
Unfortunately without any steps to reproduce this issue we can't debug further. Please provide a small example that reproduces the issue you're seeing, preferable using [Electron Fiddle](https://github.com/electron/fiddle).

Thanks!

**Comment by chenxsan** [comment]
I have same warning in the console when I open electron devtools under electron v8.0.0-beta.3, and the React DevTools extension won't work at all. No such problem if downgraded electron to v7.1.2.

Here's a repo you can clone to reproduce it https://github.com/chenxsan/electron-quick-start, and the warning could be React.js related.

**Comment by gnemtsov** [comment]
We are still seeing this in Electron 8.0.3. I don't know how it can be reproduced, but we are receiving a lot of these exceptions from many users. We use Sentry for capturing exceptions in our application. Any help or advice appreciated!

`TypeError: sender.emit is not iterable (cannot read property Symbol(Symbol.iterator))
  at ? (electron/js2c/renderer_init.js:2181:16)`

**Comment by folkvir** [comment]
Getting this in electron 8.2.5, `Uncaught TypeError: sender.emit is not iterable (cannot read property Symbol(Symbol.iterator))`

And it appears to be for me a problem when sending data from the main process to the renderer process with `window.webContents.send(...)`.

Maybe the error is related to this (the description of the .send method): 

> Arguments will be serialized with the Structured Clone Algorithm, just like postMessage, so prototype chains will not be included. Sending Functions, Promises, Symbols, WeakMaps, or WeakSets will throw an exception.
NOTE: Sending non-standard JavaScript types such as DOM objects or special Electron objects is deprecated, and will begin throwing an exception starting with Electron 9.

**Comment by zquancai** [comment]
I encounter this issue on Electron@8.2.0 randomly. But don't know how to reproduce it.
