### ISSUE TITLE
deleteAppDataOnUninstall for MAC

### ISSUE THREAD

**Issue by BTARPAR** [electron/electron#21121]
HELP !!!
I am not able to find a solution to delete my appData from the ~/Library/Application Support/MyApp when I uninstall my app

Currently Using below npm module for my application:
```
"electron": "^4.1.1",
"electron-builder": "^21.2.0",
"electron-reloader": "^0.2.0",
"electron-store": "^3.1.0",
"react": "^16.8.6",
"react-dom": "^16.8.4"
```

**Comment by MarshallOfSound** [comment]
There is no such thing as "uninstalling" a macOS app.  No events, no hooks, nothing.  Uninstalling an app on macOS is "dragging the app to the trash can".

This is a fundamental limitation of the OS
