### ISSUE TITLE
How to shared data between renderer window and another window

### ISSUE THREAD

**Issue by lech-code-monkey** [electron/electron#21127]
I want to create a child window extends main window，and I can use main window's data in the child window. Have some Solution I can shared data between two windows?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
