### ISSUE TITLE
Electron app crashing on windows with ntdll.dll error

### ISSUE THREAD

**Issue by Sai1919** [electron/electron#21125]
electron version: 3.1.0
Operating System: windows server 2019 standard

Expected Behavior: Should continuously run without crashing and autoupdate itself when updates available
Actual Behavior: Crashing after running fine for sometime and also crashing on autoupdates once the new version of app is downloaded.

Attaching the system event log of the crash:
![agent error PNG](https://user-images.githubusercontent.com/11816115/68836224-dfc62580-06df-11ea-9c58-a70a4e624958.png)

Please let me know if anymore info is needed.

**Comment by sofianguy** [comment]
We are no longer supporting versions older than Electron 5.x per our [supported versions doc](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#supported-versions). Please test with a later version of Electron and let us know if this is still an issue with repro steps.
