### ISSUE TITLE
Linux UI freezes if user presses mouse button while modal window is opening

### ISSUE THREAD

**Issue by wp777** [electron/electron#21128]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v7.1.1, v6.1.4, v4.2.11
* **Operating System:**
  * Manjaro 18.1.0 x64 (KDE Plasma 5.16.5), Ubuntu 18.04 x64 (Gnome)
* **Last Known Working Electron version:**
  * unknown

### Expected Behavior
Everything except parent of the modal window should be clickable.

### Actual Behavior
Nothing can be clicked, including system widgets (taskbar etc.) and the modal window. There is no excessive CPU usage and processes appear to be working - opening start menu or console using keyboard works. Closing the modal using escape key helps.

### To Reproduce
Create an Electron app with following code:
```js
const { app, BrowserWindow, dialog } = require("electron");
function createMainWindow() {
    let win = new BrowserWindow();
    win.loadURL("data:text/html;charset=utf-8,test");
    setTimeout(() => {
        dialog.showOpenDialog(win);
    }, 2500);
    return win;
}
app.on("ready", createMainWindow);
```
Start the app, put cursor over the window and press left mouse button. Hold it down until modal window appears. At this point UI is frozen. The key to reproduce this bug is to have mouse pressed (inside an Electron window) while modal is opening - this can happen even when user is just clicking. Another example is Visual Code (Electron 4.2.11) - use ctrl+o while holding down left mouse button. I could not reproduce this bug on Windows/Mac.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
