### ISSUE TITLE
setProxy doesn't work with pacScript

### ISSUE THREAD

**Issue by betavebow** [electron/electron#21130]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.1
* **Operating System:**
  * Windows 10 (1909)
* **Last Known Working Electron version:**
  * 6.1.4

### Expected Behavior
Setting a proxy with setProxy and a pac file works.

### Actual Behavior
So i'm trying to set a proxy using setProxy with a pac file. I added a partition to my webview and use the same one when using setProxy. It's not catching an error but when I use resolveProxy the promise is empty. If i check the ip it's my normal one not the proxy one.

### Additional Information
If i use proxyRules everything works as intended.
My pacFile should be fine:
```function FindProxyForURL(url, host) { return "PROXY proxy.example.com:8080"; }```

**Comment by betavebow** [comment]
So I tried setting the proxy with the electron-quick-start project to minimize factors that could play a role.
If i follow the official docs: https://electronjs.org/docs/api/session, i get an error saying: ```ERR_MANDATORY_PROXY_CONFIGURATION_FAILED (-131)```.

**Comment by ymschaap** [comment]
Can you add the snippet that shows your session.setProxy(config) and your config object. Are you sure the path is correct to your pacfile? (e.g. console.log the file, or try to read it with `const pacFileString = await fs.readFile(pacFile, "utf8");`

**Comment by betavebow** [comment]
This is my usage in the quick-start:
```
const pacPath = "C:/proxy.pac";
const ses = mainWindow.webContents.session;

const pacFileString = await fs.readFile(pacPath, "utf8", (err, data) => {
  if (err) {
    console.log(err);
  }
  console.log("data read: " + data);
});

ses.setProxy({pacScript: pacPath}).then(() => {
  console.log("proxy successfully set");
  ses.resolveProxy("https://google.com").then(r => {
    console.log("resolved proxy: " + r)
  }).catch(r => {
    console.log(r)
  })
}).catch(r => {
  console.log(r)
});

mainWindow.loadURL("https://google.com").then(() => {
  console.log("loaded url successfully")
}).catch(r => {
  console.log("reason: " + r)
});
```
When i read the file like you proposed the output is equal to my file.

The console output looks like this:
```
proxy successfully set
data read: function FindProxyForURL(url, host) { return "PROXY proxy.example.com:8080"; }
resolved proxy: 
Error: ERR_MANDATORY_PROXY_CONFIGURATION_FAILED (-131)
```
As you can see i can set the proxy without catching an error, but when trying to resolve the promise is empty. When i use loadURL afterwards it returns the chromium error.

The latest version of electron I've tried is 6.1.4. This works. I don't know if this is helpful information though. setProxy since changed from using callbacks to promises.

**Comment by ymschaap** [comment]
Seems to make sense (I presume the proxy.example:8080 is a dummy value here).

Two ideas:
What if your return "DIRECT" in  FindProxyForURL? Does that also fail?
Do you need a pacscript? Can you not try what you want with the proxyRules object?

**Comment by betavebow** [comment]
Direct doesn't seem to make a difference.
I have decided that I'll be sticking with 6.1.4 until this is resolved.

Thank you very much for your help!

**Comment by cuixiping** [comment]
Same issue.  
Electron v7.1.14

I tested a simplest pac file.

```
function FindProxyForURL(url, host) {
    return 'DIRECT';
}
```

The error message is:

```
Error: ERR_MANDATORY_PROXY_CONFIGURATION_FAILED (-131) loading 'https://google.com/'
    at rejectAndCleanup (electron/js2c/browser_init.js:5906:21)
    at WebContents.failListener (electron/js2c/browser_init.js:5916:11)
    at WebContents.emit (events.js:203:13) {
  errno: -131,
  code: 'ERR_MANDATORY_PROXY_CONFIGURATION_FAILED',
  url: 'https://google.com/'
}
```

**Comment by cuixiping** [comment]
I am sure that pacScript value should not be `file:` url under electron v7.1.x or higher.
My solution is using `data:` url or `http:` url instead.

For example:

```
let content = `function FindProxyForURL(url, host) {
    return 'DIRECT';
}`;
session.defaultSession.setProxy({
    pacScript: 'data:text/plain;base64,' + Buffer.from(content, 'utf8').toString('base64')
}).then(_=>{ console.log('done'); });
```

**Comment by iwind** [comment]
> I am sure that the `pacScript` value should not be `file:` url with electron v7.x.x or higher.
> My solution is using `data:` url or `http:` url instead.
> 
> For example:
> 
> ```
> let content = `function FindProxyForURL(url, host) {
>     return 'DIRECT';
> }`;
> session.defaultSession.setProxy({
>     pacScript: 'data:text/plain;base64,' + Buffer.from(content, 'utf8').toString('base64')
> }).then(_=>{ console.log('done'); });
> ```

This fixed my issue.

**Comment by iwind** [comment]
> I am sure that the `pacScript` value should not be `file:` url with electron v7.x.x or higher.
> My solution is using `data:` url or `http:` url instead.
> 
> For example:
> 
> ```
> let content = `function FindProxyForURL(url, host) {
>     return 'DIRECT';
> }`;
> session.defaultSession.setProxy({
>     pacScript: 'data:text/plain;base64,' + Buffer.from(content, 'utf8').toString('base64')
> }).then(_=>{ console.log('done'); });
> ```

this works well, and 'text/plain' should be replaced with 'application/x-ns-proxy-autoconfig' as perfect.

**Comment by wong1993** [comment]
I found that:

**Comment by wong1993** [comment]
I found that
`session.defaultSession.setProxy({}).then(() => {});`
worked fine for bypass proxy

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
