### ISSUE TITLE
Rendering process dialog.showOpenDialog  return a empty object like this

### ISSUE THREAD

**Issue by dirkhe1051931999** [electron/electron#21146]
code
![20191115230422.png](https://i.loli.net/2019/11/15/v91jrpeUZgnfmdE.png)
result
![20191115230458.png](https://i.loli.net/2019/11/15/I3G7L8ebNvQSucJ.png)

----------------
electron 7.1.1

**Comment by dirkhe1051931999** [comment]
Print directly res.fullPaths is undefined

**Comment by MarshallOfSound** [comment]
That is not an empty object, you are using the `remote` module which proxies things across processes.  The `(...)` implies "getter", if you click it devtools will activate the getter.

If you `console.log(res.filePaths)` you will see an array of file paths.

**Comment by Cosen95** [comment]
> That is not an empty object, you are using the `remote` module which proxies things across processes. The `(...)` implies "getter", if you click it devtools will activate the getter.
> 
> If you `console.log(res.filePaths)` you will see an array of file paths.

I searched a lot of places and couldn’t find the answer. Why is it designed like this?
