### ISSUE TITLE
`net` in electron7: impossible to set a `Host` header in requests

### ISSUE THREAD

**Issue by arantes555** [electron/electron#21148]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.1
* **Operating System:**
  * All
* **Last Known Working Electron version:**
  * 6.1.4

### Expected Behavior
When creating a request with `net`, it should be possible to set the `Host` header arbitrarily.

### Actual Behavior
On electron >= 7, trying to set the `Host` header throws an `net::ERR_INVALID_ARGUMENT` error.

### To Reproduce

```sh
$ git clone https://github.com/arantes555/electron-bug-net-host-header.git
$ npm install
$ npm start
```

### Additional Information
When running this, we can see that in electron@6 all requests succeed. On electron@7 however, all requests that set a
`Host` header fail with said error. 

This problem makes it impossible to explicitly set the `Host`, which is normal in a web context, but does not make sense
in this case since requests are not done by a webpage.

I feel I have to point out that this one is in not at all a critical issue. It's just that it's a breaking change and that it is a restriction that does not really make sense.

**Comment by vladimiry** [comment]
Probably related issues #20923 / #20730 and a fix #21099.

**Comment by christarnowski** [comment]
I can confirm this issue is present in Electron 8.0. It prevents `electron-builder`'s (latest version `22.3.2`) auto updater from working with private S3 bucket used as release storage. In particular, this code should work:
```js
autoUpdater.on("checking-for-update", () => {
  let opts = {
    service: "s3",
    region: AWS_REGION,
    method: "GET",
    host: AWS_HOST,
    path: `${AWS_RELEASES_PATH}/${UPDATE_CHANNEL}-${UPDATE_PLATFORM}.yml`,
  };

  aws4.sign(opts, {
    accessKeyId: AWS_ACCESS_KEY_ID,
    secretAccessKey: AWS_SECRET_ACCESS_KEY
  });

  autoUpdater.requestHeaders = opts.headers;
});
```
but fails with `net::ERR_INVALID_ARGUMENT`.

The result of `aws4.sign` are headers (passed in `opts.headers`): `Host` (<= the problematic, but required, one), `X-Amz-Content-Sha256`, `X-Amz-Date` and `Authorization`.

**Comment by VerteDinde** [comment]
@arantes555 Thanks for reporting this issue! We did a bit of digging here to see what the issue was - it looks like this would require a patch to Chromium directly, since this was introduced upstream, but we've added more information to the docs on what headers are restricted and why. If this is a blocker for you, let us know and we can reopen this issue.

**Comment by arantes555** [comment]
@VerteDinde thanks for your answer !

No, as I said in my original report, I do not consider this to be a critical issue, it is not a blocker for me.

It was just a seemingly random breaking change that I couldn't understand when upgrading to electron@7. It's OK to just close it.

However, you did mention adding it to the docs, and I cannot seem to find it on the docs for `net` ( https://github.com/electron/electron/blob/master/docs/api/client-request.md ). Could you please point me to where it is documented ?

**Comment by VerteDinde** [comment]
@arantes555 Sure thing! I added it to the `setHeader`part of the docs specifically, here: https://github.com/electron/electron/blob/master/docs/api/client-request.md#requestsetheadername-value

If you think it would be more helpful somewhere else, though, just let me know, happy to make the change so it's easier to find.

**Comment by arantes555** [comment]
@VerteDinde Sorry, looks like I missed it yesterday 🤦 It looks like the logical place for that information ! Thanks

**Comment by blacksmithHub** [comment]
Hi @VerteDinde I would also be happy if we can add `Host` to our headers. Cheers!
