### ISSUE TITLE
The coordinates returned by ContextMenuParams don't account for the zoom level

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#21145]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.1
* **Operating System:**
  * macOS Mojave
* **Last Known Working Electron version:**
  * None, AFIAK 

### Expected Behavior

The `x` and `y` coordinates returned in the `ContextMenuParams` object should account for the current zoom level.

### Actual Behavior

They don't.

### To Reproduce

- Have a listener for the `context-menu` event.
- Right click on the top-right corner of the app and log the `x` coordinate returned in the `ContextMenuParams` object.
- Zoom out/in some.
- Right click on the same spot.
- The same coordinates are returned, even though the app's size effectively changed.

**Comment by MarshallOfSound** [comment]
@fabiospampinato The `x` and `y` coordinates of the `context-menu` event are for the entire screen's coordinates system.  Not just your app.  Your individual app zoom has no impact on the x/y coordinates on the screen.

This is expected behavior.  Calling `menu.popup({ x, y })` will pop it up at the correct location

**Comment by fabiospampinato** [comment]
I see, the issue I stumbled on was that I have to detect what elements the user is clicking on via `document.elementsFromPoint`, and that method requires scaled coordinates.
