### ISSUE TITLE
shell.openExternal support chrome:// URIs

### ISSUE THREAD

**Issue by Slapbox** [electron/electron#21149]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
`shell.openExternal()` can't open URIs like `chrome://gpu`

### Proposed Solution
Unknown. Totally guessing, I suspect that Electron leverages features of the operating system to pass these links to the default handler. If that's the case this may be harder to achieve than I'd initially believed.

### Alternatives Considered
I can't think of any alternative besides resorting to native modules

**Comment by MarshallOfSound** [comment]
There is no URI handler on the OS for `chrome://`, it's an internal protocol to Chrome, they don't register an OS level handler.  You would have to spawn Chrome manually with that URL as the argument

**Comment by Slapbox** [comment]
Thanks @MarshallOfSound, that's about what I figured. That's a great suggestion for an alternative implementation though. Thank you even more for that.
