### ISSUE TITLE
Can't install electron - install hangs

### ISSUE THREAD

**Issue by Legends** [electron/electron#21144]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
I can install Electron no matter which version
* **Operating System:**
Win 10 - 1803
* **Last Known Working Electron version:**
not applicable

node -v v12.13.0

### Expected Behavior

Successfull install

### Actual Behavior

Won't install electron, it hangs  ♾️ 

```
Electron version: any version I try to install gets stuck here:

```

![image](https://user-images.githubusercontent.com/966368/68550591-70f97b80-0404-11ea-87d7-bf334b9afba7.png)

 
### To Reproduce

yarn add electron

**Comment by MarshallOfSound** [comment]
It doesn't hang, it's downloading Electron.  Depending on your internet speed it might take a while and depending on your network configuration your proxy may be blocking the download.  This is a network issue on your side of things 👍
