### ISSUE TITLE
checkbox in dialog not working 

### ISSUE THREAD

**Issue by otsybulsky** [electron/electron#21159]
### Issue Details

* **Electron Version:**
  * 7.1.1
* **Operating System:**
  *  Windows 10 (1803) 
* **Last Known Working Electron version:**
  * 6.1.3

### Expected Behavior
dialog.showMessageBox
https://electronjs.org/docs/api/dialog#dialogshowmessageboxbrowserwindow-options
Returns Promise<Object> - resolves with a promise containing the following properties:
- response Number - The index of the clicked button.
- **checkboxChecked** Boolean - The checked state of the checkbox if checkboxLabel was set. Otherwise false.

### Actual Behavior
checkboxChecked do not change

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

**Comment by xland** [comment]
@sofianguy 

Yes. This is a bug.
I test it on my computer.


```js
let { remote } = require("electron");
let result = await remote.dialog.showMessageBox({
  checkboxLabel: "test",
  checkboxChecked: false,
  title: "test",
  message: "test,test,test"
});
console.log(result.checkboxChecked);
```

Whether you check the CheckBox or not, It will all print `false`

**Comment by codebytere** [comment]
@otsybulsky thanks for the report, i just put up a PR that should fix the issue!

**Comment by xland** [comment]
@codebytere 

^_^

**Comment by otsybulsky** [comment]
Thank you very much for your help!

**Comment by jrdiard** [comment]
How do I get this fix? My app exhibits the checkbox not working using 7.1.7. I've tried Electron Fiddle with 6.1.5, 7.1.4, 7.1.7, and V8.0.0.-beta.5 and 6.1.5 is the only one that works.  Note this is on Windows 10. I have not had any issues on Mac OS.   Here is the fiddle test (this is main.js):

/ Display native system dialogs for opening and saving files, alerting, etc.
//
// For more info, see:
// https://electronjs.org/docs/api/dialog

const { app, BrowserWindow, dialog } = require('electron')

let mainWindow = null

app.on('ready', () => {
  mainWindow = new BrowserWindow({ height: 600, width: 600 })

var ret = dialog.showMessageBox(mainWindow, {type: "question",      buttons:["Yes", "No"],
    message: "Do you want to run the demonstration scenes?", 
    cancelId: 1,
    checkboxLabel: "Save images for each scene",checkboxChecked: false, noLink: false});
        ret.then((val) => {
            console.log("Run Demo: " + val.response + " Save scenes: " + val.checkboxChecked);
        });

})
