### ISSUE TITLE
electron, ipc doesn't give error or output

### ISSUE THREAD

**Issue by sweepychild** [electron/electron#21156]
I'm new to js and electron, i keep getting no outputs or errors when running this code. Any help would be appreciated. 

```
//Main.js
const ipcMain = require('electron').ipcMain;

ipcMain.on('x', function(event, arg) {
    console.log(arg);
});

// index.html
const { ipcRenderer } = require('electron').ipcRenderer;
ipc.send('x', "Hello");
```

![Unt2eaqitled](https://user-images.githubusercontent.com/52845359/69004377-2ed9b800-0977-11ea-893c-edae6cefa5fc.jpg)

**Comment by vladimiry** [comment]
- There is no issue but a question for the StackOverflow-like resource.
- Transform `const { ipcRenderer } = require('electron').ipcRenderer;` to `const { ipcRenderer } = require('electron');`
- Move stuff from index.html to the preload script, see https://electronjs.org/docs/api/browser-window.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
