### ISSUE TITLE
Black <select> Boxes like #7289 with 7.1.1 and WINDOWS

### ISSUE THREAD

**Issue by coolsurfer** [electron/electron#21152]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v7.1.x
* **Operating System:**
  * Windows 10.0.18362.476
* **Last Known Working Electron version:**
  * v6.1.5, v8.0.0-beta.3

with 7.1.x i'm experiencing the same issue, that "select"-"option"-list are rendered black in html "webview" content even without <audio> or <video> tag and much to high like mentioned here https://github.com/electron/electron/issues/7289 with windows. Adding the switches "--disable-gpu" oder any other hardware deacceleration switch that i found did not help. Electron v8 does NOT show this behavior; everything is fine there...

Screenshot: [https://prnt.sc/q0xwk5](https://prnt.sc/q0xwk5)

Windows: Version 10.0.18362.476
AMD/ATI RX 480 - Software 19.9.2

**Comment by craxal** [comment]
I'm experiencing this with 7.1.1 specifically. Sometimes the drop down doesn't render at all. When it does, it's completely black.

**Comment by tassoevan** [comment]
I'm seeing it in 7.1.3 too.

**Comment by sofianguy** [comment]
fixed: https://github.com/electron/electron/pull/21526
