### ISSUE TITLE
dialog.showOpenDialog({properties: ['openFile']}) allows opening directories as well.

### ISSUE THREAD

**Issue by polofgrs** [electron/electron#21155]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.1
* **Operating System:**
  * Ubuntu 18.04 x86_64
* **Last Known Working Electron version:**
  * /

### Expected Behavior
```javascript
dialog.showOpenDialog({properties: ['openFile']}).then((result) => {
    console.log(result);
  });
```
should not allow the user to select a directory and open it, without the `openDirectory` property.   
At worst, if opened, the `result.filePaths` should be an empty list (or `result.canceled` should be set to `true`).

### Actual Behavior
The dialog opens in the `Recent` tab of Ubuntu file explorer, and any folder can then be opened from there, by clicking on `open` (top-right corner) after selecting the folder.
When printing `result` (see above), we get :
```javascript
{ canceled: false, filePaths: [ '/path/to/dir' ] }
```

### To Reproduce
[Forked electron-quick-start](https://github.com/polofgrs/electron-quick-start):
```sh
git clone https://github.com/polofgrs/electron-quick-start
cd electron-quick-start
npm install
npm start
```
Then, when you find yourself in the `Recent` tab, select any directory, and click on `open`.

### Screenshots
![Screenshot from 2019-11-16 16-01-15_2](https://user-images.githubusercontent.com/19371211/68995212-58b5b080-088b-11ea-94e8-69805dbda9fc.png)

![Screenshot from 2019-11-16 16-18-18_2](https://user-images.githubusercontent.com/19371211/68995356-2c9b2f00-088d-11ea-805f-2eb0076c74e5.png)

### Additional Information
If you select an other location than `Recent` in your file explorer, you can select any folder, and `Open` button will only let you navigate inside the folder, not send it to electron (expected behaviour).

**Comment by MarshallOfSound** [comment]
> If you select an other location than Recent in your file explorer, you can select any folder, and Open button will only let you navigate inside the folder, not send it to electron (expected behaviour

This sounds like a bug in this specific file picker implementation on Ubuntu.  You should probably raise this upstream with Ubuntu.  We set the action to `GTK_FILE_CHOOSER_ACTION_OPEN` which is documented as.

> Indicates open mode. The file chooser will only let the user pick an existing file.

So it would seem that Ubuntu mis-implemented this.

**Comment by JMD110** [comment]
Is there any way to solve this problem？

**Comment by JMD110** [comment]
> 

Is there any way to disabled the recent option, thx.
