### ISSUE TITLE
failed to create tray icon: error processing argument at index 0, conversion failure

### ISSUE THREAD

**Issue by vladimiry** [electron/electron#21154]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 8.0.0-beta2
* **Operating System:** Linux, Windows (have not tested on macOS)
* **Last Known Working Electron version:** 7.1.1

### Expected Behavior
Tray icon with the specified image created.

### Actual Behavior
Unhandled `error processing argument at index 0, conversion failure error` error is occurring. No tray icon created.

### To Reproduce
https://github.com/vladimiry-playground/electron-quick-start-tray-issue

### Screenshots

![8 0 0-beta 2](https://user-images.githubusercontent.com/1560781/68995118-33c93980-089b-11ea-86a9-7c66b8b35ea5.png)

![8 0 0-beta 2-win](https://user-images.githubusercontent.com/1560781/68995119-33c93980-089b-11ea-8962-af4ecdc5f7a3.png)

Tray icon with the specified image created if used v7.1.1 and below:

![7 1 1](https://user-images.githubusercontent.com/1560781/68995117-33c93980-089b-11ea-8ecb-83ba86a87b0c.png)

### Additional Information

If used 8.0.0-beta2 there is no error if I construct the tray using the native image module like `new Tray(nativeImage.createFromPath("image path"))` but there is no visible tray icon either, but works for v7.1.1 and below.

**Comment by momakes** [comment]
To add more info, I just upgraded from `7.1.1` to `8.0.0-beta.3` and I got this error:
```
Error processing argument at index 0, conversion failure from /Users/mo/dev/there3/desktop/main/static/tray/iconTemplate.png
```
I'm on **macOS**, and this was working on 6 and 7 version lines.

**Comment by vladimiry** [comment]
Ok, so as I expected macOS is also affected.

**Comment by codebytere** [comment]
It's an issue with underlying type marshalling between c++ and js - it's platform agnostic.

I'll hopefully have a fix up soon.

**Comment by vladimiry** [comment]
@codebytere I can confirm the issue got resolved with 8-beta4 release when running on Windows. On Linux, there is no error anymore but no tray icon created either. So the expected behavior has not been met.

> Expected Behavior
> Tray icon with the specified image created.

**Comment by vladimiry** [comment]
@codebytere should I place a new issue or this one is fine for tracking the absence of tray icon when running @electron@^8 on Linux?

**Comment by sofianguy** [comment]
fixed https://github.com/electron/electron/pull/21241

**Comment by vladimiry** [comment]
@sofianguy, I wrote above that I tested 8-beta4 release with #21241 fix included and the issue has not been completely handled:

> Expected Behavior
> Tray icon with the specified image created.

So I'm placing a new issue, #21445.

@momakes can you confirm the issue is completely fixed for you when running macOS?

**Comment by vladimiry** [comment]
@momakes, the fix has been already verified on macOS by @codebytere as noted here https://github.com/electron/electron/issues/21445#issuecomment-563430173 so I'm withdrawing my question to you.

**Comment by FI-GGG** [comment]
"devDependencies": {
		"electron": "^7.1.8",
		"electron-packager": "^14.2.1"
	}

win10 1909  我使用electron-packager打包后运行exe就会产生这个错误，但如果直接运行elecrtron main.js就正常了,这是为什么?

**Comment by FI-GGG** [comment]
win10 1909 I run the exe after packaging with electron-packager will produce this error, but if you run elecrtron main.js directly, it is normal, why is this?

**Comment by betamos** [comment]
I'm getting this error message when using a path to an icon on OS X Catalina with Electron 8.0.2 and 8.1.1, both with pdf and icns.

Using a png works, but there are other issues instead: if I use a 16x16px icon, its resolution is poor (due to retina display). Supplying another 32x32 icon suffixed with @2.png makes it too large - i.e. not adapting to retina.

**Comment by dsteinman** [comment]
Please re-open this issue.

This still occurring in Electron v8.2.3 on MacOSX, this is the latest version installed by Electron Forge.

**Comment by nornagon** [comment]
@dsteinman I can't reproduce this with v8.2.3 on macOS 10.14. I tried @vladimiry's repository linked in the issue, https://github.com/vladimiry-playground/electron-quick-start-tray-issue, and it seems to work fine with no error messages.

**Comment by vladimiry** [comment]
The thing is that, in my experience, the `error processing argument at index 0, conversion failure error` message is not very informative, it's used for different cases. For example if you pass the `*.ico` file naming it as `*.png`.

**Comment by nornagon** [comment]
Agreed, it's not a great error message.

**Comment by dsteinman** [comment]
> @dsteinman I can't reproduce this with v8.2.3 on macOS 10.14. I tried @vladimiry's repository linked in the issue, https://github.com/vladimiry-playground/electron-quick-start-tray-issue, and it seems to work fine with no error messages.

I just tried this as well, and it DOES work so it's probably a configuration error on my end.

I suppose the problem could be simply the file is not found.  I'm electron forge / webpack which mucks with the paths of the files.

**Comment by dsteinman** [comment]
Okay, I figured it out.  This will be useful for any Electron Forge users.

My tray path is coded as:
```
tray = new Tray(path.join(__dirname, 'assets', 'logoTemplate.png'));
```

The actual image is located in `src/assets/logoTemplate.png`

I had to modify `webpage.main.config.js` using the 'copy-webpack-plugin' npm  module to copy `src/assets` into the webpack build directory.

contents of `webpage.main.config.js`;

```
const path = require('path');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const assets = [ 'assets','simulator' ]; // src/asset directory

module.exports = {
	entry: './public/electron.js',
	module: {
		rules: require('./webpack.rules'),
	},
	devServer: {
		contentBase: './dist',
		hot: true,
	},
	plugins: assets.map(asset => {
		return new CopyWebpackPlugin([
			{
				from: path.resolve(__dirname, 'src', asset),
				to: path.resolve(__dirname, '.webpack/main', asset)
			}
		]);
	})
};
```
