### ISSUE TITLE
enableDeviceEmulation has no effect

### ISSUE THREAD

**Issue by JohnHardy** [electron/electron#21153]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** `v7.1.1`
* **Operating System:**  Windows 10: 10.0.18362 N/A Build 18362
* **Last Known Working Electron version:** NA

### Expected Behavior

Calling `enableDeviceEmulation({screenSize: { width: 1000, height: 1000}})` should render the window in device emulation mode, with an emulated screen size of `1000px` x `1000px` when viewed through devtools.

### Actual Behavior

The applications behaves the same regardless of if the call is made or not.  I can open devtools manually and set the device mode, but this is quickly lost when the application next restarts.

I've tried calling the function after different events, putting it on a timer for 2s. This did seem to change what was rendered (it seemed to disable device emulation? 👀) but it went back to normal as soon the window was resized.

### To Reproduce

https://electronjs.org/docs/api/web-contents#webcontents-enabledeviceemulation-parameters

```
let mainWindow = new electron.BrowserWindow({});
mainWindow.webContents.once('dom-ready', () => {
   mainWindow.openDevTools({ mode: 'bottom' });
   mainWindow.webContents.enableDeviceEmulation({
                screenPosition: 'desktop',
                screenSize: { width: 1000, height: 1000 },
                viewSize: { width: 1024, height: 768 },
                fitToView: true,
                deviceScaleFactor: 1,
    });
});
mainWindow.loadURL(somepage); 
```

You can see the relevant electron fiddle GIST here:

https://gist.github.com/112c81c1c2249a46e858b51ea40e5ff1

**Comment by lqygo123** [comment]
have the same issue

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
