### ISSUE TITLE
Electron Menu.popup() sometimes closes unexpectedly

### ISSUE THREAD

**Issue by crazytoucan** [electron/electron#21163]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.1
* **Operating System:**
  * macOS 10.14.6

### Expected Behavior

A visual menu summoned via `Menu.popup()` stays open until dismissed by the end user.

### Actual Behavior

Under certain circumstances, the summoned Menu may disappear, even though there was no user interaction, explicit programmer dismissal, or other noteworthy event. (Furthermore, the menu's `callback` is not called, and `menu-will-close` is not triggered.)

### To Reproduce

The following main program elicits the faulty behavior on my Macbook Pro:

```js
// main.js
var app = require("electron").app;
var BrowserWindow = require("electron").BrowserWindow;
var Menu = require("electron").Menu;
var MenuItem = require("electron").MenuItem;

/** 1 */
function run() {
  const bw = new BrowserWindow();
  bw.webContents.addListener("context-menu", (_evt, params) => {
    /** 2 */
    const menu = new Menu();
    menu.append(new MenuItem({ label: "Experiment" }));
    menu.popup({
      x: params.x,
      y: params.y,
    });
  });

  bw.loadURL("about:blank");
  bw.show();
}

app.on("ready", run);
```

If the `Menu` is created with local scope at location `/** 2 */` as above, it dismisses itself between 8 seconds and 1 minute. If the `Menu` is instead created at location `/** 1 */` (and still summoned at `/** 2 */`), it correctly stays open until dismissed by the user (e.g. `Escape` key or clicking an item).

### Additional Information

**If I were to speculate,** this bug is caused by interplay between some memory management code and the OSX bindings, where the `Menu` object is being GC'ed by chromium even though the native menu visual is open, and then some polling job recognizes the `Menu` object is no longer alive, and then bails out of the visual.

**Comment by MarshallOfSound** [comment]
This appears to be fixed in `8.0.0-beta.X`.  (Tested with manual GC) . I can repro on v7 but can't isolate what exactly caused it to be fixed in 8.0

To workaround in 7.1 you can do this.

```js
let menu = makeMenu();
menu.on('menu-will-close', () => {
  menu = null;
});

This will retain a reference to `menu` until it is closed preventing GC closing the menu
```
