### ISSUE TITLE
Uncaught TypeError: setInterval(...).unref is not a function in node enabled renderer or web worker

### ISSUE THREAD

**Issue by mrfelton** [electron/electron#21162]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
6.1.4
* **Operating System:**
Mac
* **Last Known Working Electron version:**
None

### Expected Behavior
Calling `unref()` on a timer as returned by `setInterval` should work.

### Actual Behavior
Results in error `Uncaught TypeError: setInterval(...).unref`

### To Reproduce
In my case I'm trying to run this from a node enable web worker, but you can also trigger the error just from a node enabled renderer process.

Try running this code in the renderer process.

`setInterval(() => ({}), 0).unref()`

Here is a gist that highlights the issue.

https://gist.github.com/f3dac90388644653d0be469215a584d2

### Additional Information

It seems that the `setTimer` and `setInterval` versions used in a node enabled renderer process does not not match the one in nodejs, and as a result code that works in node is unusable in electron.

The actual issue I'm trying to address is this one: https://github.com/grpc/grpc-node/issues/1077

**Comment by MarshallOfSound** [comment]
This is expected behavior.  If you want to use the node versions of these methods instead of the blink versions you can import them from "timers"

`const { setTimeout } = require('timers')`

**Comment by murgatroid99** [comment]
That doesn't effectively address the case where timers are used indirectly by another module that is written to work with the Node API.
