### ISSUE TITLE
IPCMainEvent.reply throws odd expection according to the doc

### ISSUE THREAD

**Issue by rawbin-** [electron/electron#21168]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  * 7.1.1  
* **Operating System:** 
  * macOS Catalina 
* **Last Known Working Electron version:**
  * 

### Expected Behavior

no exception throws
### Actual Behavior

throws odd exception
Error: Missing required channel argument
    at WebContents../lib/browser/api/web-contents.js.WebContents.sendToFrame (electron/js2c/browser_init.js:3589:11)
    at Object.event.reply (electron/js2c/browser_init.js:3730:18)
    at eval (webpack:///./src/common/api/MainAPI.js?:295:15)
    at fs.js:1186:7
    at FSReqCallback.oncomplete (fs.js:153:23
### To Reproduce

The docs says: with any args
![image](https://user-images.githubusercontent.com/8169783/69045271-7fade700-0a31-11ea-95c3-e3869b5c4d10.png)

and in the source code requires an string value as the forced channel argument:
```
const addReplyToEvent = (event) => {
  event.reply = (...args) => {
    event.sender.sendToFrame(event.frameId, ...args)
  }
}

WebContents.prototype.sendToFrame = function (frameId, channel, ...args) {
  if (typeof channel !== 'string') {
    throw new Error('Missing required channel argument')
  } else if (typeof frameId !== 'number') {
    throw new Error('Missing required frameId argument')
  }

  const internal = false
  const sendToAll = false

  return this._sendToFrame(internal, sendToAll, frameId, channel, args)
}

```
so if we call `event.reply({})` it throws Uncaught Exception: Error: Missing required channel argument

**Comment by vladimiry** [comment]
The error message actually gives you a hint: ` Error: Missing required channel argument`. See the example code here https://electronjs.org/docs/api/ipc-main#sending-messages

**Comment by rawbin-** [comment]
@vladimiry  thank you very much,  I mean that is there any way to reply to any sender without the channel arguments, just reply to the sender, so we can use it as a common listener for many emitter

**Comment by MarshallOfSound** [comment]
@rawbin- You can't just "reply", you need to give it a channel to reply on.

**Comment by rawbin-** [comment]
@MarshallOfSound  thanks, I passed the channel from renderer to main, and reply to them.
