### ISSUE TITLE
Setup window proxy

### ISSUE THREAD

**Issue by Linch1** [electron/electron#21161]
### Issue Details

* **Electron Version: 7.1.1**
* **Operating System:**
  * Ubuntu 19.10

### Expected Behavior
I'm trying to setup a proxy for electron windows, i saw that for to this there is the function `session.setProxy({params}, () => {});` i wrote this

```
const remote        = require('electron'),
      app           = remote.app,
      BrowserWindow = remote.BrowserWindow,
      ejse          = require('ejs-electron');
let win;

function createWindow () {
  // Create the browser window.
   win = new BrowserWindow({
    width: 1200,
    height: 750,
    icon: 'public/img/icona.png',
    webPreferences: {
      nodeIntegration: true,
    },
  })

  win.setMenuBarVisibility(false)
  //win.webContents.openDevTools();
  win.loadFile('views/index/test.ejs') // test.js per le finestre con sessioni diversahome-placeholder.ejs
  win.resizable = false;
  win.on('closed', () => {
    win = null;
  });
  return win
}

app.on('ready', () => {
  let window_ = createWindow()
  window_.webContents.session.setProxy({ proxyRules: 'https=193.124.183.25:8888'}, function() {
      console.log('done')
      window_.loadURL('https://google.com');
  });
});
app.on('window-all-closed', () => {
  if(process.platform !== 'darwin'){
    app.quit();
  }
});
```

as proxy i used a free one from  [this site](https://free-proxy-list.net/)

### Actual Behavior
The problem is that when i start the script it never reach the callback function of the `setProxy()` method and never console log the 'done` and load `google.com` url

**Comment by xland** [comment]
@Linch1 

session.setProxy  return a Promise object.
You can not send a callback method to this method.

My code:
```js
let { remote } = require("electron");
let webContents = remote.getCurrentWebContents();
await webContents.session.setProxy({
  proxyRules: "https=127.0.0.1:1080"
});
console.log("done");
webContents.loadURL("https://google.com");
```
Write these codes in a async method.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
