### ISSUE TITLE
Shadows on variable content inside frameless transparent windows on MacOs

### ISSUE THREAD

**Issue by thiagorova** [electron/electron#21173]
Hi again! 
I've discovered today what seems to be a fairly minor bug. I am building a timer using a frameless transparent window using electron on MacOs and, interestingly enough, if I change the workbench, there is a shadow under the timer. This seems to correspond exactly to the time when I changed my workbench.

I looked around the issues, but didn't find anything similar. I am terribly sorry if this is a known issue.

### Preflight Checklist
* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
 Electron 7.0.0
* **Operating System:**
macOS Catalina 
* **Last Known Working Electron version:**
Haven't checked, to be honest.

### Expected Behavior
I expected no text artefact to stay when changing workbenches.

### Actual Behavior
When returning from another workbench, the shadow of the previous text continues as a shadow

### To Reproduce
Here is my code:

```

// main.js

function setTimerWindow () {
  const windowState = db.get('timer-window-state', {})
  if (windowState.bounds == null) {
    windowState.bounds = {}
  }
  timerWin = new BrowserWindow({
    width: 200,
    height: 80,
    resizable: false,
    show: false,
    frame: false,
    setSkipTaskbar: true,
    alwaysOnTop: true,
    transparent: true,
    titleBarStyle: 'customButtonsOnHover',
    webPreferences: {
      nodeIntegration: true
    },
    contextIsolation: true
  })
  ;['resize', 'move', 'close'].forEach(e =>
    timerWin.on(e, storeTimerWindowState)
  )
  timerWin.setAlwaysOnTop(true, 'floating')
  timerWin.setVisibleOnAllWorkspaces(true)
  timerWin.fullScreenable = false
}

// timer renderer index

ipcRend.on('set-window', (e, data) => {
  document.getElementById('active-task-time').textContent = data.time
})

ipcMain.on('set-timer', (e, data) => {
  if (timerWin != null) {
    timerWin.webContents.send('set-window', data)
    timerWin.showInactive()
  }
})
```

'set-window' Is called from my application's main window, which also sends the time to be displayed

![electron-shadow](https://user-images.githubusercontent.com/11561119/69071233-5462d200-0a08-11ea-9ae5-84b2a4903b7e.gif)

On this image, you can see the shadow (artifact or whatever is the correct term) appearing and then "updating" when I change the workbench again.
I hope this is enough, but if you need anything else, I'm here to help

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by CodeOcenS** [comment]
I have the same proplem

**Comment by xiajingren** [comment]
Any progress?

**Comment by fatemehmarzoughi** [comment]
Any news on this?

**Comment by ruslankonev** [comment]
Still the same bug
