### ISSUE TITLE
Electron 7: ses.clearAuthCache() does not reset the selected client certificate

### ISSUE THREAD

**Issue by sa-MatteoHausner** [electron/electron#21172]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.1 (issue first appeared in 7.0-nightly)
* **Operating System:**
  * Windows 10, macOS 10.14.6
* **Last Known Working Electron version:**
  * 6.1.4

### Expected Behavior
In our application we use `app.on('select-client-certificate', (...) => ...)` to select a client certificate for client authentication.  
When the session is finished `webContents.session.clearAuthCache({ type: 'clientCertificate', origin: '...' })` is called to remove the auth credentials.

When an other session starts we expect the `app.on('select-client-certificate', (...) => ...)` callback to be called again so we can potentially select a different certificate for logging in.  

### Actual Behavior
When a second web-session begins, after having called `webContents.session.clearAuthCache()`, we don't get the `app.on('select-client-certificate', (...) => ...)` callback but the previously selected certificate gets simply reused, just as if there was no call to `session.clearAuthCache()` at all.  
This has not been the case with Electron 6 and prior.

### To Reproduce

1. Clone and launch nodejs-based sample server, that accepts client certificate based authentications:
```sh
$ git clone https://github.com/sa-MatteoHausner/electron-cert-auth-issue-server.git
$ cd electron-cert-auth-issue-server
$ npm install 
$ node cert_server.js
```

2. Open second terminal and clone electron-based sample client:
```sh
$ git clone https://github.com/sa-MatteoHausner/electron-cert-auth-issue-client.git
```

3. Import the included client certificate `client_no_password.p12` to your operating-system's certificate store - no password is required. On macOS you can simply double click the file.

4. Run electron-based sample client - after launch it will automatically sign-in with the server:
```sh
$ cd electron-cert-auth-issue-client
$ npm install && npm start
```

5. In the client's UI click on **Clear Auth**, the console output should be:
```
Event: clear-auth
 -> clearAuthCache() done
```

6. In the client's UI click on **Refresh**, this will reload the server page, with Electron > 7 there should be no console output.

7. Modify `package.json` of the client as follows:
`"electron": "7.1.1"` -> `"electron": "6.1.4"`

8. Redo steps 4 through 6 - this time after hitting **Refresh** the console output should look as follows:
```
Event: select-client-certificate
 -> Available ClientCerts for localhost:8443: client1;
 -> Using certificate: client1

Event: clear-auth
(electron) The 'options' argument to 'clearAuthCache' is deprecated. Beginning with Electron 7, clearAuthCache will clear the entire auth cache unconditionally.
 -> clearAuthCache() done

Event: select-client-certificate
 -> Available ClientCerts for localhost:8443: client1;
 -> Using certificate: client1
```

**Comment by sa-MatteoHausner** [comment]
Quick Update: this issue still exists in `Electron 9.0.0-beta.2` and `Electron 10.0.0-nightly.20200221`

**Comment by a-shabanov** [comment]
Do you have any updates for this issue?
@sa-MatteoHausner how you solve your problem? I still can't clear the auth certificate cache

**Comment by bwRavencl** [comment]
> Do you have any updates for this issue?
> @sa-MatteoHausner how you solve your problem? I still can't clear the auth certificate cache

Unfortunately so far we didn't have the time to dig into this issue any deeper by ourselves.  
Consequently this issue is still blocking us from switching to the more current releases and we are still stuck on Electron 6 (which fortunately still receives security updates at this point).  
@a-shabanov Out of curiosity - since I haven't checked for a while - could you reproduce the issue with a current Beta of Electron 9 or nightly build of Electron 10?

**Comment by a-shabanov** [comment]
> @a-shabanov Out of curiosity - since I haven't checked for a while - could you reproduce the issue with a current Beta of Electron 9 or nightly build of Electron 10?

This error is still relevant in version 9.0.0

**Comment by sa-MatteoHausner** [comment]
I did some deeper digging on where this issue originated and how it could potentially be solved:

In **Electron 6**  `clearAuthCache()` did the following:
- If the option `type: password` is set, it removed the `HttpAuthCache` entries for the provided host.
- If the option `type: clientCertificate ` is set it instead removed the cached entries of the previously selected client certificates for the supplied host from `client_auth_cache`.

This was done [here](https://github.com/electron/electron/blob/v6.1.12/atom/browser/api/atom_api_session.cc#L250):
```
    } else if (options.type == "clientCertificate") {
      auto* client_auth_cache = network_session->ssl_client_auth_cache();
      client_auth_cache->Remove(net::HostPortPair::FromURL(options.origin));
    }
```

Starting with **Electron 7** the cached client certificate selections get no longer cleared, instead **only the HttpAuthCache** gets cleared. In fact the `options.type` parameter simply got removed from the API.
For reference please check out the implementation of [ClearAuthCache()](https://github.com/electron/electron/blob/v11.0.0-nightly.20200807/shell/browser/api/electron_api_session.cc#L565).

As it stands this leaves us with no way to clear the client certificate auth cache, which essentially makes M-TLS authentication unusable for all applications that allow signing in with more than one client certificate / account. 👎 

Around the same time these changes were made for Electron 7, in Chromium the following commit was done: [Move client auth handling into SSLClientContext
](https://github.com/chromium/chromium/commit/bac8dffa5dddb9729111321d153c03aa2a569893)
With this commit the `ssl_client_auth_cache_` is no longer residing directly inside `HttpNetworkSession`, instead it now resides within the class `SSLClientContext` - see [here](https://github.com/chromium/chromium/commit/bac8dffa5dddb9729111321d153c03aa2a569893#diff-8606c05c6ddcaa1c643aca8f6fade6a7L198).

The client certificate cache can still be accessed via the newly introduced class `SSLClientContext`, which itself can be accessed by calling `HttpNetworkSession::ssl_client_context()`.
Consequently if we would simply conduct the following change to the previously removed code of Electron 6 it should still work fine with the current versions of Chromium:
```
    } else if (options.type == "clientCertificate") {
      auto* ssl_client_context = network_session->ssl_client_context();
      ssl_client_context-> ClearClientCertificate(net::HostPortPair::FromURL(options.origin));
    }
```

However with Electron 7 the API of `clearAuthCache()` was also changed: we can no longer provide a host, instead the call always applies to all cache entries, i.e. all hosts. Consequently all client certificate cache entries must be removed.
This could be done by adding the following call to `Session::ClearAuthCache()` instead:
```
network_session->ssl_client_context()-> OnCertDBChanged();
```

For reference see [here](https://github.com/chromium/chromium/blob/86.0.4226.1/net/socket/ssl_client_socket.cc#L144) Implementation of `SSLClientContext::OnCertDBChanged()`
vs
the implementation of `SSLClientContext::ClearClientCertificate()` [here](https://github.com/chromium/chromium/blob/86.0.4226.1/net/socket/ssl_client_socket.cc#L113).

Both calls do essentially the same `SSLClientContext::OnCertDBChanged()` clears all cache entries - `SSLClientContext::ClearClientCertificate()` clears only the ones for the provided host.

**Comment by nornagon** [comment]
@sa-MatteoHausner in Electron 7 we switched to using the network service, instead of accessing the network internals directly, since the latter is deprecated in Chromium and is no longer possible, as the networking internals are in a separate process. This is the API we now use: https://chromium.googlesource.com/chromium/src/+/30bb2ed98e65683566669089196e080a7d94993a/services/network/public/mojom/network_context.mojom#978

Unfortunately, I don't see any way to call `ClearClientCertificate` through the available APIs.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
