### ISSUE TITLE
white flash when focusing the app after occlusion (regression)

### ISSUE THREAD

**Issue by loc** [electron/electron#21189]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7, 8
* **Operating System:**
  * macOS
* **Last Known Working Electron version:**
  * 6.1.x

### To Reproduce
Fiddle: https://gist.github.com/6b61ba6976b93de0d7260308f750ad10

### Additional Information

Regressed https://github.com/electron/electron/issues/19858

**Comment by orangeChu** [comment]
I had the same situation on the Windows platform on electron v7.1.5.
