### ISSUE TITLE
H.264 video started playing with electron (v 6.0.0) onwards even with patent-free ffmpeg is used

### ISSUE THREAD

**Issue by ssrakesh** [electron/electron#21194]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  6.0.0 onwards
* **Operating System:**
  * Windows 10 (1803)
* **Last Known Working Electron version:**
  * 5.0.12

### Expected Behavior
video h.264 video (http://www.tev-dem.com/wp-content/uploads/2015/01/big_buck_bunny.mp4) must not play

### Actual Behavior
h264 video plays without any issues

### To Reproduce
Set electron version as 6.0.0 for local app in package.json
build with "electron-packager-plugin-non-proprietary-codecs-ffmpeg" so that corresponding "patent-free" FFMPEG is downloaded

play video from http://www.tev-dem.com/wp-content/uploads/2015/01/big_buck_bunny.mp4 in electron browser window and it plays.

now switch to older 5.0.12 electron. build with same plugin
try to play the video again, it will not play.

This indicates video support added in 6.0.0 is it intentional or bug?

**Comment by ssrakesh** [comment]
I tried another approach
created a simple browser app with browser opening above video
1. use current version of electron (v7.1.1) and browser plays the video
2. use ffmpeg download from v5.0.12 (ffmpeg-v5.0.12-win32-x64.zip) and overwrite ffmpeg in node_modules\electron\dist folder
video still plays.
So is the issue related to CEF rather than electron?

**Comment by ssrakesh** [comment]
Code for browser page is used from Verify ffmpeg support section in 
https://docs.w3cub.com/electron/development/upgrading-chromium/

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
