### ISSUE TITLE
DesktopCapturer doesn't call callback function for getSources method

### ISSUE THREAD

**Issue by chiyusen** [electron/electron#21218]
Electron version: 7.1.1
Operating system: Win 10
HI!
DesktopCapturer API,getSources method,can not enter callback functin. I tried Electron version: 6.0.0,it's OK,wish your reponse,thanks

**Comment by ramaralo** [comment]
It looks like `desktopCapturer.getSources` is promised based now.

**Comment by MarshallOfSound** [comment]
@ramaralo is correct, `getSources` now returns a promise

**Comment by wx1993** [comment]
getSources now returns a promise，you can write the capture function like this:
`handleCapture = async () => {
    const options = { types: ['window', 'screen'] }
    const screenShots = await desktopCapturer.getSources(options);
    // ...
}`

**Comment by wx1993** [comment]
getSources now returns a promise，you can write the capture function like this:
`handleCapture = async () => {
     const options = { types: ['window', 'screen'] }
     const screenShots = await desktopCapturer.getSources(options); 
     // ... 
}`

**Comment by lmcarreiro** [comment]
This still happens with promise... https://github.com/electron/electron/issues/25595

Maybe the source of both issues are the same.
