### ISSUE TITLE
Context menu not working on build macos

### ISSUE THREAD

**Issue by sebassdc** [electron/electron#21217]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.
### Issue Details

* **Electron Version:**
  v8.0.0-beta.2
* **Operating System:**
  macOS 10.15
* **Electron Builder**
21.2.0

### Expected Behavior
Im creating a context menu to fix misspelled words with the new v8 beta 2 feature.
When i test this in electron dev mode it works perfectly.
I should be able to handle the context-menu event and do a `menu.popup()`

### Actual Behavior
When i make a build with electron-builder the context menu doesn't work

**Comment by codebytere** [comment]
I recommend opening this issue on Electron builder itself, as that is not an official Electron package: https://github.com/electron-userland/electron-builder
