### ISSUE TITLE
Bundled FFmpeg does not contain copyright and version metadata

### ISSUE THREAD

**Issue by alexsharoff** [electron/electron#21222]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.12, 7.1.2
* **Operating System:**
  * Windows 10 (1809)
* **Last Known Working Electron version:**
  * None

### Expected Behavior
When right-clicking on provided ffmpeg.dll and selecting Properties -> Details, "Product name", "Product version", "Copyright" properties should have a value.

### Actual Behavior
All ffmpeg.dll properties are empty.

### To Reproduce
Check ffmpeg.dll bundled in any Electron release package for Windows.

### Screenshots

![Untitled](https://user-images.githubusercontent.com/707030/69232008-be23dd00-0bbc-11ea-9e67-ff6c2917741d.jpg)

**Comment by MarshallOfSound** [comment]
No other `ffmpeg.dll` on my system has this information either.  You should raise this request upstream with Chromium if you want that information put in the DLL that they generate when `is_component_ffmpeg` is `true`
