### ISSUE TITLE
Blurry rendering on Mac OS X after switching from non-retina display to retina display

### ISSUE THREAD

**Issue by aterenin** [electron/electron#21229]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
7
* **Operating System:**
Mac OS X
* **Last Known Working Electron version:**
N/A

### To Reproduce
1. Connect MacBook to a non-retina display - in my case, a 40" 4k display connected via DisplayPort with standard scaling (i.e. full resolution, not retina-like 1080p scaled up to 4k).
2. Close the MacBook lid.
3. Open an Electron app.
4. Unplug the display.
5. Open the MacBook lid. Electron app is blurry.

**Comment by sofianguy** [comment]
I tried reproducing this issue with your steps and did not see any issues with blurriness.

**Comment by nielsvandepas** [comment]
I have the same issue, at least with WhatsApp Desktop and Visual Studio Code. After restarting the affected app, everything is nice and sharp again. Rinse and repeat for the other app(s).
I connected my MacBook Pro via HDMI to an LG Signature 1080p display.
