### ISSUE TITLE
Return of webContents.getPrinters() has wrong type definition 

### ISSUE THREAD

**Issue by hicaro** [electron/electron#21231]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.2
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron version:**
  * 2.0.18

### Expected Behavior
The type definitions of the function return should be `PrinterInfo[]`, thus matching [`webRequest.getPrinters()`](https://electronjs.org/docs/api/web-contents#contentsgetprinters) documentation.

### Actual Behavior
`electron.d.ts` declares `getPrinters` as

```js
getPrinters(): void
``` 

### To Reproduce
A snippet to get printers

```js
const printers: PrinterInfo[] = mainWindow.webContents.getPrinters();
```

```sh
error TS2322: Type 'void' is not assignable to type 'PrinterInfo[]'.
```
### Screenshots

![Screen Shot 2019-11-20 at 8 18 29 AM](https://user-images.githubusercontent.com/1482851/69252878-f0a7e880-0b70-11ea-8bf7-2e38a8b7d213.png)

### Additional Information
One thing that I also noticed in the [implementation](https://github.com/electron/electron/blob/034f4d5734bb87ec28b21fd76decb162e8f45c8a/lib/browser/api/web-contents.js#L271) of the function is that there is no returned value when the printing is not enabled.

The current implementation is:

```js
WebContents.prototype.getPrinters = function () {
  if (features.isPrintingEnabled()) {
    return this._getPrinters()
  } else {
    console.error('Error: Printing feature is disabled.')
  }
}
```

Maybe it should return an empty array when printing is disabled:

```js
WebContents.prototype.getPrinters = function () {
  if (features.isPrintingEnabled()) {
    return this._getPrinters()
  } else {
    console.error('Error: Printing feature is disabled.')
    return [];
  }
}
```

or update the function's return definition to be:

```js
getPrinters(): PrinterInfo[] | void
```

Please, let me know if this is something I can be of any assistance. I'm happy to provide a pull request to address it.

**Comment by xland** [comment]
On `Electron 7.1.1`  `Win10` is ok.

```js
let { remote } = require("electron");
let webContents = remote.getCurrentWebContents();
let printers = webContents.getPrinters();
console.log(printers);  //my printers
console.log(process.versions.electron);  //7.1.1
```

**Comment by hicaro** [comment]
@xland thank you for running this! The function implementation is correct. What is wrong is the type definition for typescript. It declares that `getPrinters()` returns `void` instead of `PrinterInfo[]`, which is blocking the build process.

What I found that worked to circumvent the issue was casting the return to `any` and then assigning the value to a variable with the correct type:

```js
const printers: PrinterInfo[] = <any>mainWindow.webContents.getPrinters();
```

**Comment by xland** [comment]
OOOOOOOK~~
Sorry to bother you.

TypeScript is ugly.
run away.....

**Comment by hicaro** [comment]
@xland not a bother at all! I appreciate you taking the time and checking this issue with me. It is always good to have a second pair of eyes 👁 on it.
