### ISSUE TITLE
electron 7.1.2 app is segfaulting on startup on Ubuntu 18.04 after it worked for a while (after setup)

### ISSUE THREAD

**Issue by yafp** [electron/electron#21240]
### Preflight Checklist
* [ x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
7.1.2
* **Operating System:**
Ubuntu 18.04 x64
* **Last Known Working Electron version:**
6.1.2

### Expected Behavior
App should not segfault on start

### Actual Behavior
App is segfaulting - after it worked for several launches without issues.

### To Reproduce
I can't offer a reproduceable minimal demo so far.

I am working on a Linux Ubuntu machine on my project.
Recently i upgraded from electron 5 over 6 to 7.

Since some days i am realizing an issue where i am starting my app by `npm run start` and it instantly quits without feedback. After jumping back and forth between electron6 and electron7 it seems like that to me:

* using electron 6.1.2 -> app starts as expected
* upgrading to electron 7.1.2 -> app starts as expected BUT

After several launches the app is not starting properly anymore.

This means:
* i do start running: `npm run start`
* app quits without error output

**According to /var/log/syslog:**

`Nov 21 15:10:15 localhost kernel: [273917.152073] electron[26171]: segfault at 0 ip 0000562cace03824 sp 00007ffe614b7c00 error 4 in electron[562caac18000+53a6000]`

**According to sentry:**

`Fatal Error: SIGSEGV /SEGV_MAPERR`

**At this point i have to:**

- downgrade to electron 6.1.2 -> starts as expected
- remove folder `node_modules`
- execute `npm install`
- update to electron 7.1.2 -> starts for some launches
- app runs for several times, then crashes while using it.  From that point on i can't start anymore and the loop jumps back to the beginning.

Any idea how to troubleshoot this segfault?
Should i add additional information from sentry? if so - what?

Some aspects reminds me to 
* https://github.com/electron/electron/issues/19468 (but my dev environment is a linux machine)
* https://github.com/electron/electron/issues/19511 (not packaged here)

**Comment by matheo** [comment]
Wow, I'm getting a SIGILL but on Mac, on my Ubuntu 18.10 my Electron 7.1.2 works correctly.
I'm not sure which system logs you should check to get a better idea of the exception :(

**Comment by momakes** [comment]
FWIW I had to update some dependencies. It was `@sentry/electron` for me

**Comment by yafp** [comment]
@momakes:
i am using sentry 1.0.0. 

`"@sentry/electron": "^1.0.0",`

And you?

**Comment by momakes** [comment]
@yafp Yes, it's exactly that. I upgraded to beta version and it solved it: https://github.com/getsentry/sentry-electron/issues/192

There has been an issue affecting all platforms. I spent 2 days debugging!!

**Comment by yafp** [comment]
@momakes 
so far it looks like the sentry beta is solving my issue as well. Thanks for this hint , i was messing around as well for 2 days already.

I'll keep this issue open for 2 more days to be sure it's solved.

**Comment by momakes** [comment]
Glad it helped!

**Comment by yafp** [comment]
seems like using 1.1.0-beta.0 really solved this issue.

Thanks once again.
