### ISSUE TITLE
BrowserWindow won't go fullscreen on instantiation on Ubuntu

### ISSUE THREAD

**Issue by benfrancis** [electron/electron#21259]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.2
* **Operating System:**
  * Ubuntu 18.04.3 LTS
* **Last Known Working Electron version:**
  * 6.0.6

### Expected Behavior
`BrowserWindow` created in fullscreen mode

### Actual Behavior
Can see toolbar with File, Edit, View etc. menus

### To Reproduce
```
$ git clone https://github.com/webianproject/shell-kiosk.git
$ cd shell-kiosk
$ npm install
$ npm start
```

`BrowserView` is instantiated here https://github.com/webianproject/shell-kiosk/blob/master/chrome.js#L17

```
    this.mainWindow = new BrowserWindow({
      fullscreen: true,
      webPreferences: {
        nodeIntegration: true,
        webviewTag: true
      }
    });
```

### Additional Information
Used to work on Electron 6.0.6. First noticed the problem after upgrading to Electron 7.1.2. 
Still works on Mac OS.

**Comment by benfrancis** [comment]
Likely related to or a duplicate of #21268

**Comment by benfrancis** [comment]
**Note:** Bug also reproduces on Ubuntu Core.

**Comment by benfrancis** [comment]
As per https://github.com/electron/electron/issues/21088#issuecomment-553486818, `Menu.setApplicationMenu(null)` makes the offending menu disappear and the application takes up the whole screen.

So on reflection, the issue may not be that the BrowserWindow isn't going fullscreen, but that the menu is displayed when it shouldn't be.

**Comment by lkostrowski** [comment]
I have the same problem on Ubuntu 20.x, kiosk doesnt hide icons tray :< 
I used hack with setting app size using display bounds for now

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by benfrancis** [comment]
I can verify that this bug no longer reproduces in Electron 9.4.3 when running under Ubuntu Desktop.
