### ISSUE TITLE
webContents's session can not enableNetworkEmulation

### ISSUE THREAD

**Issue by xland** [electron/electron#21250]
`Win10`
`Electron 7.1.0`  and `Electron6.1.4`

```js
let { remote } = require("electron");
let ses = remote.getCurrentWebContents().session;
await ses.clearCache();
await ses.clearStorageData();
ses.enableNetworkEmulation({
  offline: true
});
let xhr = new XMLHttpRequest();
xhr.open("GET", "https://www.cnblogs.com/aggsite/AggStats");
xhr.onload = () => console.log(xhr.responseText);
xhr.send();
```

When I emulate the network outage,
the xhr gets the web source  correctly.

**Comment by xland** [comment]
And Electron 6.1.5 has this issue,too.

**Comment by xland** [comment]
And Electron 5.0.12 has this issue,too.

**Comment by xland** [comment]
And Electron 8.0.0-beta.3 has this issue,too

**Comment by xland** [comment]
@sofianguy 

Would you check this for me？Thanks

**Comment by nornagon** [comment]
I can reproduce this.

A little analysis: at least in the post-network-service code (7.x+), it looks like when we set the network conditions, we pass `network_emulation_token_`, which is never anywhere set as the `throttling_profile_id` of any request, so the network conditions are never applied.

As a workaround for now, you might try using the [Network.emulateNetworkConditions](https://chromedevtools.github.io/devtools-protocol/tot/Network#method-emulateNetworkConditions) method in the debugger API, e.g.

```js
const dbg = myWebContents.debugger
dbg.attach()
await dbg.sendCommand('Network.enable')
await dbg.sendCommand('Network.emulateNetworkConditions', {offline: true, latency: 0, downloadThroughput: -1, uploadThroughput: -1})
```

NB. with this workaround, the network condition emulation will only last as long as the debugger is attached.

**Comment by xland** [comment]
@nornagon

Thanks!

**Comment by cawa-93** [comment]
I also get this problem in 8.0.0-beta.4

**Comment by megahertz** [comment]
`net.request` has the same issue. It affects all versions since Electron 4, including Electron 9.

**Comment by nimfadora2** [comment]
I have some trouble with workaround for this problem. Can it be fixed soon?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by killpowa** [comment]
This issue is still relevant, could you please reopen?

**Comment by nornagon** [comment]
Here's a Fiddle which reproduces the issue: https://gist.github.com/7b6b11c8f57465aa2545e508f0e6d0f1

If it loads the webpage successfully, then this feature is broken.

**Comment by duzda** [comment]
Importantly to add, the workaround doesn't seem to have any effect on workers.

**Comment by dyongerwen42** [comment]
still affecting me

**Comment by kevinlinv** [comment]
It would be nice if this worked so we can emulate the entire session rather than per web contents 🙏

**Comment by oopses** [comment]
still affecting me

**Comment by oopses** [comment]
Does this method work for DownloadItem?

> 仍然影响着我
