### ISSUE TITLE
EventSource request always return net::ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by manodupont** [electron/electron#21253]
EventSource request doesn't connect and always return this : 
```
net::ERR_EMPTY_RESPONSE
```
on this line 
```
this.eventSource = new EventSource('http://localhost:3003/api/events');
```

This line works good in Chrome, in electron-dev too. I am not sure where and how to start debugging that.

I am using the default native EventSource (https://github.com/EventSource/eventsource). I tried also with a github project polyfill  that I found which i thought could fix the problem, but it didnt help. I still have the same issue. Any idea on this one ?!

Thanks

package.json
```
"electron-dev": "^1.0.1",
"electron": "^7.0.0",
"electron-builder": "^21.2.0",
```

**Comment by vladimiry** [comment]
I'd suggest trying electron v6 as since v7 the network-related stuff got significantly changed/broken and the progecc of fixing it is still in progress.

**Comment by elsandosgrande** [comment]
This has hit me as well.

**Comment by nornagon** [comment]
I can't reproduce this. https://gist.github.com/8291aa01700906c38ffb759a4e5af386 seems to work fine in Electron 6, 7, and 8.

Can you perhaps provide an example using [Electron Fiddle](https://github.com/electron/fiddle)? Thanks!

**Comment by elsandosgrande** [comment]
I am wondering if the original reporter even remembers this ticket, given that it has been a few months. Maybe somebody should mention him?

**Comment by manodupont** [comment]
Can definitely close this.
