### ISSUE TITLE
"--ignore-connections-limit" commandLine switch stopped working in Electron@7

### ISSUE THREAD

**Issue by Kilian** [electron/electron#21255]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 7.1.2
* **Operating System:** Ubuntu 18.04 x64 
* **Last Known Working Electron version:** 6.x

### Expected Behavior
Setting the "ignore-connections-limit" commandLine switch for localhost should allow more than 4 connections to e.g. the gatsby development server, which limits it to that number. This is the behaviour in Electron@6

### Actual Behavior
The "ignore-connections-limit" seems to have no effect anymore in electron@7.

### To Reproduce

1. Run a gatsby local server, like https://github.com/gatsbyjs/gatsby-starter-hello-world
2. Launch this fiddle with electron@6, and see that all 6 iframes load the site: https://gist.github.com/Kilian/d35badc28200c3229b1028243433cf54
3. Launch the fiddle with electron@7, see that none of the iframes load anymore
4. Remove two iframes, launch with electron@7, see that the iframes now do load

### Note
Note that our documentation still mentions the flag as working: https://electronjs.org/docs/api/chrome-command-line-switches#--ignore-connections-limitdomains

**Comment by nornagon** [comment]
I don't think `ignore-connections-limit` was ever a Chrome switch. Looks like it got inadvertently removed here: #19644

**Comment by deepak1556** [comment]
Yeah its not a chrome switch, and yup its accidentally removed there.

**Comment by Kilian** [comment]
ref: https://github.com/electron/electron/pull/19644/files#diff-8c1eed0d78f8872226e8dd910fccb551L245

Can it be re-introduced in the new classes?
