### ISSUE TITLE
Global Keyboard Shortcuts not working in build.

### ISSUE THREAD

**Issue by Stanlyhalo** [electron/electron#21258]
I have a global keyboard shortcut that is ctrl+q, and inside it is an if then, it states that if window is focused then, and it sends an event to the browser window, and the browser window changes an element when they click ctrl+q. I tested this and it works, but when I build the application and install it, it does not work. Why won't it work.

**Comment by Stanlyhalo** [comment]
BTW, I'm currently elsewhere, and I believe I have electron in dev dependencies, and I am using electron-builder, their is another error with file-system not working in the build version, but works in the command "npm start", also file-system is in dependencies I believe.

**Comment by xland** [comment]
First，You should check global keyboard shortcut in your system. 
If there is a `ctrl+q` shortcut in your system,
your app will not register the same shortcut  successfully，
And no errors will be triggered.

Second, According to your needs, you should not use  global keyboard shortcut.
I think just use window.onkeydown is ok.
```js
window.onkeydown = function() {
  if ((event.ctrlKey || event.metaKey) && event.keyCode == 81) { 
     //Q's keycode is 81
     //do what you want here.
  }
};
```

**Comment by ckerr** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
