### ISSUE TITLE
"Unable to load preload.js" error when adding any ui library

### ISSUE THREAD

**Issue by lewixlabs** [electron/electron#21254]
### Preflight Checklist

* [X ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v7.1.1
* **Operating System:**
  * macOS Catalina v10.15.1

Hi,
I have a full working project with Electorn, Typescript & React
Link of my project is here:
https://github.com/lewixlabs/charta

My preload.tsx source is here:
https://github.com/lewixlabs/charta/blob/master/src/preload.tsx

```
// All of the Node.js APIs are available in the preload process.
// It has the same sandbox as a Chrome extension.

import React = require("react");
import ReactDOM = require("react-dom");
import { Charta } from "./react-engine/Charta";

window.addEventListener("DOMContentLoaded", () => {
  const replaceText = (selector: string, text: string) => {
    const element = document.getElementById(selector);
    if (element) {
      element.innerText = text;
    }
  };

  for (const type of ["chrome", "node", "electron"]) {
    replaceText(`${type}-version`, (process.versions as any)[type]);
  }

  ReactDOM.render(<Charta/>, document.getElementById("idReactMain"));
});

```
When I try to add any react library, like https://react-bootstrap.github.io, like this way

```
// All of the Node.js APIs are available in the preload process.
// It has the same sandbox as a Chrome extension.

import React = require("react");
import ReactDOM = require("react-dom");
import { Charta } from "./react-engine/Charta";
import { Button } from 'react-bootstrap';

window.addEventListener("DOMContentLoaded", () => {
  const replaceText = (selector: string, text: string) => {
    const element = document.getElementById(selector);
    if (element) {
      element.innerText = text;
    }
  };

  for (const type of ["chrome", "node", "electron"]) {
    replaceText(`${type}-version`, (process.versions as any)[type]);
  }

  ReactDOM.render(<Button>BUTTON</Button>, document.getElementById("idReactMain"));
});
```

I get this error:

> Unable to load preload script: /Users/l.detogni/Codex/chartacopia/dist/preload.js

but this module exists in dist output folder.

This is my electorn window:
![image](https://user-images.githubusercontent.com/7371215/69434568-3239be80-0d3e-11ea-91f8-f3e659da23b9.png)

Can somebody help me or suggest me where I'm wrong?
Thanks!
Lewix

**Comment by lewixlabs** [comment]
I noticed my issue was marked "bug".
Do you confirm?
Does a workaround exist?

Thanks for any help.

Lewix

**Comment by MarshallOfSound** [comment]
This issue is in your own code.  Something in your code is trying to do `document.body.appendChild` but during the preload script `document.body` is not defined yet.  You should wait for the `load` event in your preload script before doing any DOM work

**Comment by lewixlabs** [comment]
Thank you!
I will verify, eventually I will update this post, maybe could be usefull for anyone encountered same issue.

**Comment by lewixlabs** [comment]
I'm inspecting my issue, but I tried to instantiate my react app inside DOMContentLoaded or load (on electorn preload module) but without success. Same issue
```
window.addEventListener("DOMContentLoaded", () => {


  // ReactDOM.render(<Charta/>, document.getElementById("idReactMain"));
});

window.addEventListener("load", () => {


  // ReactDOM.render(<Charta/>, document.getElementById("idReactMain"));
});
```

**Comment by TheKonka** [comment]
I have the same problem. I want to render a react component when I send a event from main process. I don't know how to achieve it.
