### ISSUE TITLE
Different file:// paths are not treated as different origins

### ISSUE THREAD

**Issue by mobitar** [electron/electron#21260]
### Issue Details

**Electron Version:** 7.1.2 (but also same behavior on 5.x and 6.x)
**Operating System:** macOS 10.14.6

### Expected Behavior
Different file:// paths should be treated as different origins, according to @MarshallOfSound's post [here](https://github.com/electron/electron/issues/19789#issuecomment-534739289):

> Unique file:// URLs are all considered on different origins for security reasons, this is the same behavior as a browser

However, different files appear to be able to share localStorage. I've attached a simple demo project.

index.html:

```
localStorage.setItem("foo", "bar");
console.log("Read value from index.html:", localStorage.getItem("foo"));
// Outputs "bar"
```

child.html (as iframe):
```
console.log("Read value from child.html:", localStorage.getItem("foo"));
// Outputs "bar", but should be null.
```

We expect child.html, which has a different file:// location, to not be able to read index.html's localStorage values.

### Actual Behavior
child.html iframe is able to read the localStorage values that index.html set.

### To Reproduce

Run this project: 
[electron-same-origin.zip](https://github.com/electron/electron/files/3880609/electron-same-origin.zip)

<img width="769" alt="Screen Shot 2019-11-22 at 11 05 56 AM" src="https://user-images.githubusercontent.com/3277844/69445514-128f9f80-0d18-11ea-9604-bae7ea52def2.png">

**Comment by mobitar** [comment]
For the record, both the latest versions of Chrome and Safari behave similarly. They treat all files as having same origin. However, Firefox handles this correctly and gives a unique localStorage context to each unique file path.

Chrome:
<img width="677" alt="Screen Shot 2019-11-22 at 1 40 05 PM" src="https://user-images.githubusercontent.com/3277844/69455608-60170700-0d2e-11ea-9f72-2a747e94dad4.png">

Firefox:
<img width="318" alt="Screen Shot 2019-11-22 at 1 43 27 PM" src="https://user-images.githubusercontent.com/3277844/69455618-660ce800-0d2e-11ea-9776-a0583a0e379a.png">

**Comment by nornagon** [comment]
Unfortunately it's beyond the scope of the Electron project to change this behavior in Chromium. Please raise a bug upstream: https://crbug.com/new

**Comment by mobitar** [comment]
Related threads:

https://bugs.chromium.org/p/chromium/issues/detail?id=794098

https://bugzilla.mozilla.org/show_bug.cgi?id=1500453

Looks like this issue is being actively discussed on the Chromium side.
