### ISSUE TITLE
SetProxy - Using proxies that require authentication does not work.

### ISSUE THREAD

**Issue by true-zero** [electron/electron#21269]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.2
* **Operating System:**
 Windows 10 (18362)
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
If a proxy is set electron is expected to handle the **407 Proxy Authentication Required** from the server by raising the `login` event and if that event does not have a handler then to throw an error that a proxy authentication is required.

### Actual Behavior
Electron instead sees that the response is not a 2xx response from the server and instead throws a `net::ERR_HTTP_RESPONSE_CODE_FAILURE` which is most likely due to there not being a specific exception for the 407 Proxy Authentication header.

### To Reproduce
```JS

const { app, net, BrowserWindow } = require('electron');

app.on('ready', async () =>
{
	/*
	 * Switch between a proxy with and without authentication required
	 * to see the described behaviour.
	*/

	let proxy = '127.0.0.1:8888';
	//let proxy = '127.0.0.1.:8888:user:pass';
	
	
	let window = new BrowserWindow({ width: 800, height: 800, show: false});
	let session = window.webContents.session;
	
	await session.setProxy({proxyRules: proxy});
	
	const request = net.request({session: session, url: 'http://canihazip.com/s'});
	
	if(proxy.split(':').length === 4)
	{
		request.on('login', (_, callback) => callback(proxy.split(':')[2], proxy.split(':')[3]));
	}

	request.on('response', (response) =>
	{
		let body = '';
		response.on('data', (chunk) => { body += chunk; });
		response.on('end', () => console.log(body));
	});
	
	request.end();
});
```

**Comment by nornagon** [comment]
Fixed by https://github.com/electron/electron/pull/21135

**Comment by dataich** [comment]
When is this release for 7.1.x?

**Comment by kunokdev** [comment]
I had issues with suggested method in my context where I run separate browser views.

Instead of setting proxy on `BrowserWindow` I set proxy on the view:

```
view.webContents.session
      .setProxy({
        proxyRules: proxyString,
      })
```

then using `app.on('login')` handler to authorize proxy.

**Comment by razr001** [comment]
hi，@kunokdev I have the same problem,  I referred to your code, it does not work
```javascript
const mainWindow = new BrowserWindow({
  width: 800,
  height: 600,
});

mainWindow.webContents.session.setProxy({ proxyRules: "192.168.0.1:8899" }).then(() => {
  mainWindow.loadURL("https://www.google.com");
});

app.on("login", function (event, webContents, request, authInfo, callback) {
  if (authInfo.isProxy) { 
	callback("username", "password"); 
  } 
});
```

**Comment by future-mine** [comment]
@kunokdev 
Could you explain in more detail?
