### ISSUE TITLE
err_file_not_found

### ISSUE THREAD

**Issue by chenguang1994** [electron/electron#21273]
![err](https://user-images.githubusercontent.com/31501915/69490244-c5e6c880-0ebf-11ea-967c-dac84fdacc69.png)
I try to Upload files(20G),each chunks 3M,it occured this problem occasionally。
Version is 6.0.0

**Comment by xland** [comment]
It seems like an error of your server side.
You should post more details about your error.

**Comment by chenguang1994** [comment]
> It seems like an error of your server side.
> You should post more details about your error.

 test1()
  
  
  test1(){
      for (let index = 0; index <3; index++) { 
          this.test2()
      }
    },
   async test2() {


      for (let index = 0; index < 7000; index++) {
             
        let a =  await   this.test3();
      }
   },
    test3() {
	
		 return new Promise((resolve,reject)=>{
			let arr = []
			//this file is 3M
			let readStream=fs.createReadStream('test.dll');
			readStream.on('data', data => {
				arr.push(data)
			})
			 readStream.on('end', () => {
			 
				      var file = new File(arr,"test.dll"); 
                       var ft= new FormData()
                       ft.append("file",file)

                      axios.post("url",ft).then(res=>{
                          resolve()
                     }) 
			 
			 })
		 })
	
	}

**Comment by chenguang1994** [comment]
About half of the upload errors

**Comment by xland** [comment]
Although you posted the same file 21000 times to your server，
But it doesn't look like anything's wrong.
So I think it is your server side error.

**Comment by chenguang1994** [comment]
> Although you posted the same file 21000 times to your server，
> But it doesn't look like anything's wrong.
> So I think it is your server side error.

thanks，Which version do you use

**Comment by chenguang1994** [comment]
> > Although you posted the same file 21000 times to your server，
> > But it doesn't look like anything's wrong.
> > So I think it is your server side error.
> 
> thanks，Which version do you use

My problems have been coming up，The server is as follows  
![QQ图片20191125194125](https://user-images.githubusercontent.com/31501915/69537947-222f1280-0fbc-11ea-90ef-e46ebf121e0f.png)
![Uploading QQ图片20191125194130.png…]()

**Comment by chenguang1994** [comment]
![QQ图片20191125194134](https://user-images.githubusercontent.com/31501915/69537963-28bd8a00-0fbc-11ea-8178-230ea0e5950a.png)

**Comment by chenguang1994** [comment]
> Although you posted the same file 21000 times to your server，
> But it doesn't look like anything's wrong.
> So I think it is your server side error.
> 
> thanks，Which version do you use
> 
> My problems have been coming up，The server is as follows
![123](https://user-images.githubusercontent.com/31501915/69538099-83ef7c80-0fbc-11ea-8f78-42941beeca82.png)

**Comment by xland** [comment]
Electron 6.x.x & 7.x.x

Change your code to one that runs in the browser,
then test it in your browser

**Comment by chenguang1994** [comment]
in the browser has  no problems ， Electron 5.x.x & 6.x.x & 7.x.x all exist this problem

**Comment by chenguang1994** [comment]
electro

> Electron 6.x.x & 7.x.x
> 
> Change your code to one that runs in the browser,
> then test it in your browser

run successful in 8.0.0-beat3

**Comment by xland** [comment]
AHA，It's weird.

**Comment by ckerr** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unneccessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you've responded, please link to the test case and @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
