### ISSUE TITLE
Native File Drag & Drop with "WebP" image will cause JavaScript error.

### ISSUE THREAD

**Issue by taku-o** [electron/electron#21275]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
Native File Drag & Drop with "WebP" image will cause JavaScript error dialog.  
("PNG" image will display correctly draging icon.)

```
// OK
ipcMain.on('ondragstartpng', (event, filePath) => {
  const imgPath = path.join(__dirname, '/images/ic_music_video_black_24dp_1x.png');
  event.sender.startDrag({
    file: filePath,
    icon: imgPath,
  });
});

// NG
ipcMain.on('ondragstartwebp', (event, filePath) => {
  const imgPath = path.join(__dirname, '/images/ic_music_video_black_24dp_1x.webp');
  event.sender.startDrag({
    file: filePath,
    icon: imgPath,
  });
});
```

* **Electron Version:**
  * v6.1.5
* **Operating System:**
  * macOS 10.13.6
* **Last Known Working Electron version:**
  * 

### Expected Behavior
WebP image icon will be displayed in draging.

### Actual Behavior
JavaScript Error dialog will be displayed.  
dialog message is

```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: Must specify non-empty 'icon' option
    at EventEmitter.<anonymous> (/Users/taku-o/Desktop/electron-crash-on-drap-webp/main.js:35:18)
    at EventEmitter.emit (events.js:200:13)
    at WebContents.<anonymous> (/Users/taku-o/Desktop/electron-crash-on-drap-webp/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:334:21)
    at WebContents.emit (events.js:200:13)
```

### To Reproduce
a minimal sample code.  
https://github.com/taku-o/electron-crash-on-drap-webp

```sh
$ git clone git@github.com:taku-o/electron-crash-on-drap-webp.git
$ cd electron-crash-on-drap-webp
$ npm install
$ npm run start
```

### Screenshots
![](https://raw.githubusercontent.com/taku-o/electron-crash-on-drap-webp/master/js_error_dialog.png)

**Comment by nornagon** [comment]
Unfortunately we only support PNG and JPEG in the `nativeImage` API. See https://electronjs.org/docs/api/native-image#supported-formats
