### ISSUE TITLE
Support .mjs file in electron

### ISSUE THREAD

**Issue by xiaoxiangmoe** [electron/electron#21271]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Electron doesn't support mjs now.

### Proposed Solution

support `.mjs` and `.cjs`.

### Additional Information

* node 13.2 has been released with .mjs support without flag: https://github.com/nodejs/node/releases/tag/v13.2.0
* https://github.com/electron/electron/issues/6127

**Comment by MarshallOfSound** [comment]
Once this feature makes its way to an LTD version of node Electron will get it.

**Comment by Alhadis** [comment]
@MarshallOfSound [Node v14.0.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#14.0.0) was released the other day, which finally got rid of the annoying `ESM support is experimental` warning.

How long do you think it'll be before this lands in Electron?
