### ISSUE TITLE
Bad translation, wrong code...

### ISSUE THREAD

**Issue by abelardolg** [electron/electron#21272]
### Preflight Checklist

* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  DC
* **Operating System:**
  *  DC
* **Last Known Working Electron version:**
  *  DC

### Expected Behavior

This [page](https://electronjs.org/docs/tutorial/first-app) is bad formatted, mixing English Spanish words and so on...
### Screenshots

![image](https://user-images.githubusercontent.com/22522883/69483465-fda23180-0e27-11ea-8b0e-720fc41b1555.png)

**Comment by MarshallOfSound** [comment]
Can you raise this over at [electron/electronjs.org](github.com/electron/electronjs.org)
