### ISSUE TITLE
The animation performance

### ISSUE THREAD

**Issue by Alecyrus** [electron/electron#21289]
### Issue Details

* **Electron Version:**
  * v7.1.2
* **Operating System:**
  * macOS 10.15
* **Hardware:**
  *  Macbook Pro 13

### Expected Behavior
The animation in fullscreen mode should be smooth as it does in window mode (800x600)

### Actual Behavior
I have write some code for animation, and I noticed that the larger the size of window is , the slower the animation FPS. I made a performance profile as follows. 

It seems like window size will affect render performance a lot. In my case, there is  half performance loss. I could feel ui interaction is very laggy. And I really don't know the reason, hope anybody could help me out. 

As you can see, it takes more than 40ms to render a single frame, which is not caused by heavy javascript tasks.
<img width="1291" alt="截屏2019-11-2616 21 20" src="https://user-images.githubusercontent.com/55738135/69611483-cff7fb00-1068-11ea-9472-e07a0116b6d6.png">

![截屏2019-11-2616 24 26](https://user-images.githubusercontent.com/55738135/69611997-ddfa4b80-1069-11ea-8f57-c1f188808a48.png)
<img width="474" alt="截屏2019-11-2616 23 19" src="https://user-images.githubusercontent.com/55738135/69612010-e0f53c00-1069-11ea-8fd8-47c9541c5f6b.png">

**Comment by Alecyrus** [comment]
Is it related to #20944 ？？

I didn't notice this issue on Window platform.

**Comment by nornagon** [comment]
Is this issue also present in Chrome?

**Comment by Alecyrus** [comment]
For now, I have no more details about this, because I have no experience to debug electron itself. The output in the above screenshot didn't tell more specific information. So I do not know whether it is printed by chromium or electron. 

I will try my best to figure it our these days.

**Comment by xland** [comment]
You should provide the miniest workable codes.
So that somebody can test and give some suggests for you.

**Comment by Auxxxxlx** [comment]
Update:  I upgrade macOS from 10.15 beta  to 10.15.1
