### ISSUE TITLE
MenuItem type:radio won’t allow 0 checked items

### ISSUE THREAD

**Issue by ChrisHSandN** [electron/electron#21292]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.1
* **Operating System:**
  *  Windows 10
* **Last Known Working Electron version:**
  * None

Create a series of radio MenuItems which are all checked:false

```
  Menu.setApplicationMenu(Menu.buildFromTemplate([{
    label: 'foobar',
    submenu: [{
      label: 'item 1',
      type: 'radio',
      checked: false,
    }],
  }]));
```

### Expected Behavior
No radio button should be checked.

Note: while radio buttons are mutually exclusive once one is checked there are definite use cases for having none selected to start with and this behavior is allowed in:
1. HTML `<input type=radio>`
2. Windows UX Guide https://docs.microsoft.com/en-us/windows/win32/uxguide/ctrl-radio-buttons#default-values

### Actual Behavior
The first radio option is automatically checked (ignoring the checked:false property)

### To Reproduce
https://gist.github.com/e97deedf4d919809cafc65fe3ce22d15

### Screenshots
![image](https://user-images.githubusercontent.com/13466620/69656188-01c09000-1070-11ea-904c-0b6ff0f58c38.png)

**Comment by AlexSHoffman** [comment]
@ChrisHSandN try something like this, without specifying `checked: false`
```JS
Menu.buildFromTemplate([
  { label: 'Item1', type: 'radio' },
  { label: 'Item2', type: 'radio' },
])
```

**Comment by codebytere** [comment]
This is a fundamental behavior of Chromium's menu modeling across platforms; it does not allow you to set all radio buttons to false in an initial menu state. I suggest you open a bug to Chromium itself if you would like to see this behavior changed - we [consume Chromium's menu model](https://github.com/electron/electron/blob/50f2d2b5abfa1124dd49f41de8251952bc946307/shell/browser/api/atom_api_menu.cc#L134) and as such as subject to the decisions they have made around this behavior.

You can open a bug to Chromium [here](https://bugs.chromium.org/p/chromium/issues/list).
