### ISSUE TITLE
electron-api.json main/renderer process fields always true

### ISSUE THREAD

**Issue by tong** [electron/electron#21290]
* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.*
* **Last Known Working Electron version:**
  * 6.*

Since electron v7.* electron-api.json defines all `process` fields as true.
Therefore (any) generators are unable to distinguish which types are only available in `main` or `renderer` process. 

```json
"process": {
  "main": true,
  "renderer": true
},
```
This breaks the package generation for haxe types definitions: #tong/hxelectron/issues/46.

**Comment by MarshallOfSound** [comment]
This is piece of work that hasn't been done yet in the `docs-parser` project.

https://github.com/electron/docs-parser/blob/d4d62e1ac0c32f732d0bde55e2ca06116490875b/src/DocsParser.ts#L164-L168

This issue should be raised on the `docs-parser` (or even better a Pull Request 😄 )
