### ISSUE TITLE
DevTools's Add to workspace not working (again)

### ISSUE THREAD

**Issue by dfoverdx** [electron/electron#21300]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

I found an [issue](https://github.com/electron/electron/issues/4798) that matches this exactly, but it was fixed in 2016.  This seems like a regression.

### Issue Details

* **Electron Version:**
  * 7.1.1
* **Operating System:**
  * Windows 10

### Expected Behavior
When adding a folder to the workspace in the Sources/Filesystem tabs, the folder is added to workspace, same as it is in Chrome.

### Actual Behavior
After clicking the button and selecting a folder, nothing happens.  (Fails silently.)

### To Reproduce
* Open DevTools
* Click Sources Tab
* Click Filesystem Tab
* Click `+ Add folder to workspace` button, select folder, click Select Folder

### Screenshots
![workspace](https://user-images.githubusercontent.com/3087358/69678625-f2831780-105a-11ea-98f0-eeb64c0e7dec.gif)

**Comment by IgorFomenko** [comment]
I have the same (node 12.13.0, Chrome 80.0.3987.163, Electron 8.2.1).

**Comment by richarddwelsh** [comment]
I have the same problem (Node.js 12.13.0, Chromium 80.0.3987.165, and Electron 8.2.5).

**Comment by j0hnwhyte** [comment]
Same. Maybe it's trying to request the permission but it has no space where to show it?

**Comment by IgorFomenko** [comment]
workaround is here [https://forum.vivaldi.net/topic/18031/unable-to-add-folder-to-workspace-in-dev-tools/3](url)

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron < `8.x.y`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
