### ISSUE TITLE
If i want to achieve Edge of the adsorption and Edge stitching by Multiple forms ,That's possible?

### ISSUE THREAD

**Issue by WingDust** [electron/electron#21302]
- If i want to achieve Edge of the adsorption and Edge stitching by Multiple forms ,That's possible?
- Use what?
- 如果我想对多窗体进行窗体的边缘吸附、边缘拼接 它能实现吗？

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
