### ISSUE TITLE
Crash due to SUID sandbox helper binary in paths with spaces

### ISSUE THREAD

**Issue by fxha** [electron/electron#21309]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v7.1.2
* **Operating System:**
  * Debain 10 VM image from Debian - no configuration done
* **Last Known Working Electron version:**
  * ???

Electron's fallback sandbox crashes on a Linux system with user namespaces disabled like Debian 10 and located in a path that contains spaces. I guess that this is an Electron issue because the issue is not reproducible with a path without spaces.

NOTE: The issue is only reproducible on a Linux system with user namspaces disabled, so the fallback sandbox is used!

### Expected Behavior

Electron should successfully launch when the binaries are located in a path with spaces like `/opt/electron with spaces/`.

### Actual Behavior

Electron crashes (due to fallback sandbox) without any error message at application startup, the main process is not executed.

### To Reproduce

1. Download Electron binary, move it to `/opt/electron`, change directory owner to `root ` recursively and `chmod 4755 /opt/electron/chrome-sandbox` on a Linux system with user namspaces disabled like Debian 10.
1. Launch Electron -> Electron should start successfully
1. `sudo mv /opt/electron "/opt/electron withspace"`
1.  Launch Electron from directory with spaces ->Application crash: `Trace/breakpoint trap`

**Comment by nornagon** [comment]
Reproduced this with a testing build. Here's the stack trace:


```
[25831:1127/095859.962188:FATAL:zygote_host_impl_linux.cc(187)] Check failed: ReceiveFixedMessage(fds[0], kZygoteBootMessage, sizeof(kZygoteBootMessage), &boot_pid). 
#0 0x5585e5b73679 base::debug::CollectStackTrace()
#1 0x5585e5aa1943 base::debug::StackTrace::StackTrace()
#2 0x5585e5abb315 logging::LogMessage::~LogMessage()
#3 0x5585e759cd2c service_manager::ZygoteHostImpl::LaunchZygote()
#4 0x5585e4fe075d content::(anonymous namespace)::LaunchZygoteHelper()
#5 0x5585e759bc5a service_manager::ZygoteCommunication::Init()
#6 0x5585e75a3203 service_manager::CreateGenericZygote()
#7 0x5585e4fdfb84 content::ContentMainRunnerImpl::Initialize()
#8 0x5585e75a3a86 service_manager::Main()
#9 0x5585e3930641 content::ContentMain()
#10 0x5585e2ace01e main
#11 0x7f88075e8b97 __libc_start_main
#12 0x5585e2acdd2a _start

Received signal 6
#0 0x5585e5b73679 base::debug::CollectStackTrace()
#1 0x5585e5aa1943 base::debug::StackTrace::StackTrace()
#2 0x5585e5b73131 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7f880d659890 <unknown>
#4 0x7f8807605e97 gsignal
#5 0x7f8807607801 abort
#6 0x5585e5b71f05 base::debug::BreakDebugger()
#7 0x5585e5abb800 logging::LogMessage::~LogMessage()
#8 0x5585e759cd2c service_manager::ZygoteHostImpl::LaunchZygote()
#9 0x5585e4fe075d content::(anonymous namespace)::LaunchZygoteHelper()
#10 0x5585e759bc5a service_manager::ZygoteCommunication::Init()
#11 0x5585e75a3203 service_manager::CreateGenericZygote()
#12 0x5585e4fdfb84 content::ContentMainRunnerImpl::Initialize()
#13 0x5585e75a3a86 service_manager::Main()
#14 0x5585e3930641 content::ContentMain()
#15 0x5585e2ace01e main
#16 0x7f88075e8b97 __libc_start_main
#17 0x5585e2acdd2a _start
  r8: 0000000000000000  r9: 00007ffd893d96d0 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007ffd893daa80 r13: 00007ffd893d9930 r14: 00007ffd893daa88 r15: aaaaaaaaaaaaaaaa
  di: 0000000000000002  si: 00007ffd893d96d0  bp: 00007ffd893d9920  bx: 00007ffd893da164
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007f8807605e97  sp: 00007ffd893d96d0
  ip: 00007f8807605e97 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

**Comment by nornagon** [comment]
Running with strace, this seems like the problem:

```
[pid 26211] execve("/home/nornagon/work/electron-gn/src/out/testing", ["/home/nornagon/work/electron-gn/"..., "space/chrome-sandbox", "/home/nornagon/work/electron-gn/"..., "--type=zygote"], 0x34a1eae0a800 /* 72 vars */) = -1 ENOENT (No such file or directory)
```

**Comment by nornagon** [comment]
I think this is an issue in Chromium as well. The code at [//sandbox/linux/suid/client/setuid_sandbox_host.cc](https://cs.chromium.org/chromium/src/sandbox/linux/suid/client/setuid_sandbox_host.cc?l=163&rcl=e9b380c67c085baaa2c81ba67e89b00a2e30ce35) calls `base::CommandLine::PrependWrapper`, which [splits on whitespace](https://cs.chromium.org/chromium/src/base/command_line.cc?l=461&rcl=e9b380c67c085baaa2c81ba67e89b00a2e30ce35).

I also observe this issue to be present when installing Chrome itself into a directory containing a space.

I'd recommend [filing this issue on the Chromium bug tracker](https://crbug.com/new).

**Comment by fxha** [comment]
@nornagon Thanks for your fast reply, you mean I should open a bug report at Chromium for this, so the Electron team can fetch the fix later, or you want to open one?

**Comment by nornagon** [comment]
Yes, please go ahead and report this upstream to Chromium.

**Comment by fxha** [comment]
FYI, https://bugs.chromium.org/p/chromium/issues/detail?id=1029290.

**Comment by johnsmith0209** [comment]
@nornagon 
Hi, I'm sorry to interrupt and address an irrelevant problem, but I do encounter an another issue which causes electron@7.1.x crashing in CentOS:7. And I can get two coredump files per crash. Since I'm quite lame at debugging these kind of things, tried to use `gdb` to inspect coredump file but failed. 
I want to know how to inspect coredump files in CentOS and how to find the stack trace as you did up there.
Really appreciated.

**Comment by johnsmith0209** [comment]
And also sometimes the running program can receive `render-process-crashed` event, but without  generating any coredump files.
