### ISSUE TITLE
should raise an error in dev console if the resource designated by webview tag's src is unreachable/inexistent

### ISSUE THREAD

**Issue by bruceauyeung** [electron/electron#21305]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.1.4
* **Operating System:**
  * Centos 7.4 64bit
* **Last Known Working Electron version:**
  * unknown

### Expected Behavior
should raise an error in dev console or have a related failed request in dev network tab if the resource designated by webview tag's src is unreachable/inexistent, for example 1:
~~~
<img src="http://local.zte.com.cn/inexistent.jpg" />
~~~
will raise an error:
>GET http://local.zte.com.cn/inexistent.jpg net::ERR_CONNECTION_REFUSED

and in dev network tab there is a related failed request for `inexistent.jpg`

 for example 2:
~~~
<iframe src="http://local.zte.com.cn/inexistent.jpg" />
~~~
will not raise an error in dev console tab but there is a related failed request for `inexistent.jpg`  in dev network tab

### Actual Behavior

nothing and this makes me confused.

**Comment by MarshallOfSound** [comment]
A WebView is a a completely separate webContents and therefore has its own devtools.  Network errors and the like will go to its own devtools not the hosts devtools.  There is an API on the WebView element to open the devtools
