### ISSUE TITLE
VS2019 fails to open the gn generated electron_lib.vcxproj

### ISSUE THREAD

**Issue by bughit** [electron/electron#21301]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * master
* **Operating System:**
  * win7 sp1 x64

- projects generated by `gn gen out/Testing-x86 --ide=vs2019`
- opening `all.sln`
- error: `error  : Cannot load project with duplicated project items: ../../../../electron/shell/common/api/constructor.h is included as 'None' and as 'None' item types. `
- removing the duplicate `constructor.h` entry in the project file resolves the problem

**Comment by MarshallOfSound** [comment]
@bughit That generator comes from `gn` not from Electron.  If there is a bug in the generator you should isolate and report upstream to the `gn` folks in the chromium repo.
