### ISSUE TITLE
Reload/redirect of remote app randomly causes blank screen

### ISSUE THREAD

**Issue by francescodicaprio** [electron/electron#21314]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.1
* **Operating System:**
  * Windows 10 Pro x64
* **Last Known Working Electron version:**
  * Unknown

### Expected Behavior
Reload or redirect should show the refreshed content of the remote webpage.

### Actual Behavior
Remote application goes to blank screen.

### To Reproduce
- Create two BrowserWindow, kiosk mode, fullscreen, one on a screen, one on another screen
- Load two different remote URLs, one for each BrowserWindow
- Set an interval that refreshes those two pages every 30 seconds
- After a random number of reloads, both BrowserWindow(s) go to a blank screen

### Additional Information
It doesn't matter which Javascript instruction you use to change page: location.href, location.reload, location.replace generate the same outcome. Remote web server doesn't show any weird error log, when location.reload() fires, Electron loads a white page that is local and belongs to Chromium itself, it's not an error while loading the remote page.

**Comment by AnandK1100** [comment]
I'm also facing same issue, on same electron version.
In my case when I reload app or open it by clicking on the app icon then it shows a white screen

**Comment by mozgenn** [comment]
@AnandK1100  @francescodicaprio  any solution to this one guys?

When I Reload my app through `Cmd + R`, it shows the blank screen. When I inspect it, it had an empty body in DOM.

My reload configs are:
```await mainWindow.reload();```

**Comment by namrouche993** [comment]
any solution please ?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
