### ISSUE TITLE
Electron slow loading of many dynamically added images in html webpage

### ISSUE THREAD

**Issue by brandonlam777** [electron/electron#21310]
* Electron version: 6.1.5
* Operating system: Windows 10 1807

Background: The app runs Electron to display medium to high complexity webpages.

### Expected behavior
On Electron version 1.8.8, all images are loaded from local cache quickly. 
![image](https://user-images.githubusercontent.com/37786499/69740974-dab19f00-10ff-11ea-8326-3a89ede55104.png)

### Actual behavior
After upgrading the Electron verison to 6.1.5, images take much longer to be loaded from local cache, sometimes taking minutes to fully load all images.
![image](https://user-images.githubusercontent.com/37786499/69741349-835ffe80-1100-11ea-91da-572198e326c0.png)

The same images on the same webpage take much longer to be loaded.

### How to reproduce

Load a webpage within electron 6.1.5 or greater.
The webpage used for testing is as followed, the array is an array of images to be dynamically loaded.
![image](https://user-images.githubusercontent.com/37786499/69741941-8dcec800-1101-11ea-985b-e377edb75e79.png)

**Comment by nornagon** [comment]
Do you see the same behavior when loading that page with Chromium?

**Comment by brandonlam777** [comment]
I do not see the same slow loading loading the page within the latest version of Chromium.
Here are the graphs from loading the same webpage on the latest version of Chromium.
![image](https://user-images.githubusercontent.com/37786499/69748646-734f1b80-110e-11ea-8ac5-1f19bd340338.png)

**Comment by nornagon** [comment]
Hm, okay then, that is concerning. Would it be possible for you to create an example which shows the issue, possibly based on [electron-quick-start](https://github.com/electron/electron-quick-start)?

**Comment by brandonlam777** [comment]
I was not able to replicate the issue in an app based on electron-quick-start. We are going to try to change our electron build tools to resolve the problem.

**Comment by brandonlam777** [comment]
We have discovered this issue is due to the chromium version, looking like this issue was introduced in chrome 60+.
