### ISSUE TITLE
WebHID API support

### ISSUE THREAD

**Issue by brockoli** [electron/electron#21311]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Need access to the new experimental WebHID API for communicating with HID devices such as Jabra headsets.

### Proposed Solution

WebHID API is an experimental api in chromium 78.  It solves this issue.

### Alternatives Considered

node-hid can be used in Electron to communicate with HID devices, but it doesn't give us the report descriptors so we can't support many HID devices as we need to hard code the usages to their location in the bit stream.

### Additional Information

Chome 78+ allows access to the WebHID API by enabling experimental feature flag.  Electron lets us set this flag, but we still don't have access to WebHID API even in the latest Electron builds on chromium 78.

Chome also implements a device picker for granting HID device permissions.  I understand that Electron isn't likely going to implement a UI for picking HID devices (similar to WebUSB and bluetooth).  We would need a way to blanket authorize all connected HID devices so that we can retrieve them with the `getDevices()` function in the WebHID API.  Normally the returned array is empty until the user has explicitly granted device permissions.

**Comment by aabuhijleh** [comment]
In Electron 9.3.0, we have access to `navigator.hid`

**Comment by jimb456** [comment]
I am using 10.1.5 which is Chrome 85.  I have experimentalFeatures = true.  Yes, navigator.hid is present but when we use navigator.hid.requestDevice() we would normally get a consent popup from Chrome.  I am unable to get this to happen in Electron where it does occur in a standalone web page in Chrome.  See example consent screen.
![Screen Shot 2020-10-26 at 3 06 25 PM](https://user-images.githubusercontent.com/36517966/97233842-e63c9880-179c-11eb-8bce-ab6b12794f07.png)

**Comment by aabuhijleh** [comment]
@jimb456 I think some work still need to be done on Electron's side like #22478 to make the WebHID API usable. I think Electron will provide this data but you will have to design the UI yourself like [`navigator.bluetooth`](https://www.electronjs.org/docs/api/web-contents#event-select-bluetooth-device).

@jkleinsc can you please let us know if there's an update on this topic and in which version can we expect to use the WebHID API in Electron?

**Comment by aabuhijleh** [comment]
Any update on this?

**Comment by jjeff** [comment]
I'd love to see this get in. Ping me if you need any testers or feedback.
