### ISSUE TITLE
`app.setAsDefaultProtocolClient` not working for sandboxed Mac apps

### ISSUE THREAD

**Issue by jack-arms** [electron/electron#21319]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.8
* **Operating System:**
  * macOS 10.14.6

### Expected Behavior
`app.setAsDefaultProtocolClient` (https://electronjs.org/docs/api/app#appsetasdefaultprotocolclientprotocol-path-args) is consistently returning `false` for any Mac app that is sandboxed.

### Actual Behavior
`app.setAsDefaultProtocolClient` should not fail in a sandbox environment, or if there are other considerations to make protocol activation work in a sandboxed environment extra documentation would be helpful.

### To Reproduce

Pretty involved to reproduce, but basically having this in the app's entitlements file:
```
<key>com.apple.security.app-sandbox</key>
<true/>
```

and this in the `Info.plist`:
```
<key>CFBundleURLTypes</key>
<array>
  <dict>
     <key>CFBundleURLName</key>
     <string>Launch</string>
     <key>CFBundleTypeRole</key>
     <string>Editor</string>
     <key>CFBundleURLSchemes</key>
     <array>
       <string>foo</string>
     </array>
  </dict>
</array>
```

and building with this configuration according to [electron-builder](https://www.electron.build/configuration/mac#MacConfiguration-target), then calling `app.setAsDefaultProtocolClient('foo')` returns false wherever it's called, e.g. before app ready and after.

Additionally, not sandboxing the app *and* not having `CFBundleURLTypes` does not cause any problems with `app.setAsDefaultProtocolClient`, despite the documentation saying that the schemes need to listed in the `Info.plist`, so I'm wondering if there's something going on with this in general.

**Comment by ckerr** [comment]
Thank you for taking the time to report this issue and helping to make Electron better. The version of Electron you reported this on has been superseded by newer releases -- the latest in that series is 5.0.12. In addition, there are newer releases of Electron 6 and 7 (and, in beta, 8) branches that supersede that series.

If you're still experiencing this issue in the latest version of Electron, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the blocked/need-info label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by koussaimb** [comment]
i had same problem 
for example app.setAsDefaultProtocolClient('tel') worked fine with electron without enable sandbox 
with sandbox option do not take into consideration the protocol

OS : MAC
using electron 12.0.6
