### ISSUE TITLE
SetProxy - Using proxies that require authentication does not work.

### ISSUE THREAD

**Issue by true-zero** [electron/electron#21323]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.0.0-beta.3
* **Operating System:**
 Windows 10 (18362)
* **Last Known Working Electron version:**
  * v6.0.0

### Expected Behavior
If a proxy is set electron is expected to handle the **407 Proxy Authentication Required** from the server by raising the `login` event and if that event does not have a handler then to throw an error that a proxy authentication is required.

### Actual Behavior
Electron instead sees that the response is not a 2xx response from the server and instead throws a `net::ERR_HTTP_RESPONSE_CODE_FAILURE` which is most likely due to there not being a specific exception for the 407 Proxy Authentication header.

### To Reproduce
```JS

const {app, session, net} = require('electron');

app.on('login', (event, webContents, details, authInfo, callback) =>
{
    console.log('login event fired');

    if(authInfo.isProxy)
    {
        event.preventDefault();
        callback('username', 'password');
    }
});

app.on('ready', () =>
{
    console.log('the app is ready');

    let sess = session.fromPartition('name');
    sess.setProxy({proxyRules: 'ip:port'});

    let req = net.request({url: 'https://canihazip.com/s', session: sess});


    req.on('response', (response) =>
    {
        let body = '';
        response.on('data', (chunk) => { body += chunk; });
        response.on('end', () =>
        {
            console.log(body);
        });
    });
    req.end();
});
```

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
