### ISSUE TITLE
Electron is grabbing the ` key, which breaks my app

### ISSUE THREAD

**Issue by scripting** [electron/electron#21326]
Update: I think I found the workaround on [this page](https://electronjs.org/docs/tutorial/keyboard-shortcuts#shortcuts-within-a-browserwindow). 

Good morning and Happy Thanksgiving. ;-) 

I have an Electron app that I've been running since 2017, and recently had to rebuild it under Electron 6.1.5. Almost everything works, but I find that now the environment is grabbing Cmd-` -- the keystroke my app uses to toggle between visible and invisible HTML code. This editor has been around since the very early days of the web and that's the key it has always used.

I'm looking for a way to disable this, to grab the keystroke before the shell gets it. 

Mac OS 10.13.6.

Any advice much appreciated.

**Comment by MarshallOfSound** [comment]
The page you linked has all the information you need to correctly obtain shortcuts
