### ISSUE TITLE
desktopCapturer.getSources() always returns a single screen combining all the screens in linux even there are multiple screens.

### ISSUE THREAD

**Issue by shafayet2368** [electron/electron#21321]
Electron Version: 6.0.0
Operating System: Ubuntu 18.04 x64 

### Expected Behavior
`desktopCapturer.getSources()` 
should return an array of length equal to the number of screens/displays with all the information about each screen.

### Actual Behavior
`desktopCapturer.getSources()` 
always returns an array of length 1 combining all the screens/displays.

it returns a single screen with `id: "screen:0:0"`

### To Reproduce

`const electron = require('electron');
const desktopCapturer = electron.desktopCapturer;
desktopCapturer.getSources({ types: ['screen']}, sources => {
    console.log(sources);
  });`

@codebytere @nornagon   can you please address the issue?

**Comment by loc** [comment]
There is an active upstream bug that addresses this issue: https://bugs.chromium.org/p/chromium/issues/detail?id=396091

It looks like it hasn't landed yet, but whenever it does, it'll start working in the subsequent major Electron release.

**Comment by xudeming208** [comment]
> There is an active upstream bug that addresses this issue: https://bugs.chromium.org/p/chromium/issues/detail?id=396091
> 
> It looks like it hasn't landed yet, but whenever it does, it'll start working in the subsequent major Electron release.

Has the latest version of this problem been solved?
