### ISSUE TITLE
How to use Other Window's method

### ISSUE THREAD

**Issue by sonjaerock** [electron/electron#21322]
### Problem Description

For several days, I've been thinking about how to write methods on other window objects using ipcMain and ipcRenderer and remote and webContents.

Main process - Renderer process (by ipcMain and ipcRenderer)
`send` method doesn't send method.
By official document 'send' method is Event Emiiter(by nodeJS) ... 
`send` method in nodeJS can send method,
but `send` method in Electron can not! send method.

So I decided to choose that just method's return value send using `invoke` and `handle` 
Renderer => Main has `invoke/handle` but Main => Renderer communicate don't have any way to synchronize communication..

I want to .. communicate with other windows More perfectly..

My example 
Core renderer process has core object(very heavy and locally)
Sub renderer process must not have core object(core objects are affected by creation time and only exist once)

Sub renderer process have to use core renderer process's method(or return value)

somebody help me..

**Comment by xland** [comment]
看你头像，感觉你应该是中国人。
懒的写英文了，反正官方也不管，我提了一大堆issue也没人回复我。

首先，
进程间发消息，消息对象是肯定不能带方法的，
因为Electron会给你序列化和反序列化这个消息对象
消息对象原型链上的东西同样也不会传递。

其次，
你这个需求有点变态，进程间通信应该尽量异步，要不然搞不好会卡死你的渲染进程的。

不过，
还是有办法的，你可以尝试`ipcRenderer.sendSync`方法，
这个方法将以同步的形式发送消息给主进程，主进程处理完后，可以为此方法设置返回值。

祝你早日开发出牛逼的应用，哈哈！

**Comment by ckerr** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community).
