### ISSUE TITLE
getPrimaryDisplay().workAreaSize 

### ISSUE THREAD

**Issue by sunjiaqing** [electron/electron#21332]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v7.1.2
* **Operating System:**
  * Windows 10 (1809)
* **Last Known Working Electron version:**
  * v7.1.2

### Expected Behavior
width:1920
height :1200
### Actual Behavior
width:1920
height :1160

### To Reproduce
```javascript
function createWin(str) {
    let tempWin = new BrowserWindow({width: 1920, height: 1200, show: false,webPreferences:{nodeIntegration:true,webviewTag:true}});
    let promise = tempWin.loadFile(str);
    tempWin.once("ready-to-show", () => {
        tempWin.show();
    })
    tempWin.on("closed", () => {
        tempWin = null
    })
    return tempWin;
}

function createMainWin() {
    mainWin = createWin("index.html");
    mainWin.webContents.openDevTools();
    let { width, height } = screen.getPrimaryDisplay().workAreaSize
    mainWin.setSize(width,height)
}
```

### Additional Information

**Comment by momakes** [comment]
What you're looking for is `screen.getPrimaryDisplay().bounds`.
