### ISSUE TITLE
gclient sync fail

### ISSUE THREAD

**Issue by Drecc** [electron/electron#21333]
I am building electron on windows system.I found a problem when I use "gclient sync --with_branch_heads --with_tags",please help me to resolve it
![image](https://user-images.githubusercontent.com/12831867/69860407-29faf980-12d1-11ea-9511-a39b603cc437.png)

**Comment by MarshallOfSound** [comment]
@Drecc I literally just hit this, update your clone of `depot_tools` to the latest 👍
