### ISSUE TITLE
The capturePage() function does not work after packaging

### ISSUE THREAD

**Issue by erdenerkilic** [electron/electron#21336]
I don't speak English very well, I apologize.
When we package our application using the electron-packager, I notice that after Electron v5.0.12, the capturePage () function does not work. It does not give any errors. Has anyone experienced it? Is there a solution?

Plugins I use
   "dependencies": {
     "bootstrap": "^ 4.3.1",
     "electron": "^ 5.0.12", (after this version I couldn't run it in another version)
     "electron-debug": "^ 3.0.1",
     "electron-settings": "^ 3.2.0",
     "font-awesome": "^ 4.7.0",
     "jquery": "^ 3.4.1",
     "sweetalert2": "^ 9.3.11",
     "toastr": "^ 2.1.4"
   },
   "devDependencies": {
     "electron-packager": "^ 14.1.1"
   }

win32 x64 as the package

**Comment by ckerr** [comment]
@erdenerkilic, to be clear, are you saying it only fails when using electron-packager + Electron > 5.0.12?

What other versions / combos did you try with? E.g. when you're running locally without electron-packager, does it work?

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
