### ISSUE TITLE
Failed to load custom devtools

### ISSUE THREAD

**Issue by javaxiu** [electron/electron#21347]
I have read the [docs](https://electronjs.org/docs/tutorial/devtools-extension)
- I can add react dev tools extension to my electron app by `BrowserWindow.addDevToolsExtension('xxx')` too. 
- I wrote an extension myself, it works on chrome
- but it doest'n work on electron app, it says `Uncaught (in promise) Error: Connect to unknown extension ipcwork`.  `ipcwork` is the name of my selfmake extention.

I didn't use too much chrome api, no more then just these `window.postMessage`, `chrome.runtime.sendMessage`,  `window.chrome.runtime.onMessage.addListener`
should i upload my extension for test ?

**Comment by miniak** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by javaxiu** [comment]
sorry for reply too late,  i figure out that was my fault,  writing a devtools should completely follow [this guiding](https://developer.chrome.com/extensions/devtools),  which means it should contains content_script.js / background.js / devtool_pane.html.  
i missed background.js, it works fine on chrome but not electron. content_script.js can't conmmunicate with devtools_pane directly.  don't know why but maybe api permissions stuff i guess.
so this issue was closed for sure.
