### ISSUE TITLE
Electron download failed

### ISSUE THREAD

**Issue by HeiShanLaoYao889** [electron/electron#21353]
### Error detail
```
> electron@7.1.2 postinstall 
.../node_modules/electron
> node install.js

(node:99449) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
    at EventEmitter.emitter.on.response (.../node_modules/@electron/get/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (events.js:182:13)
    at module.exports (.../node_modules/@electron/get/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (.../node_modules/@electron/get/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:187:15)
    at ClientRequest.origin.emit.args [as emit] (.../node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient (_http_client.js:546:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:432:20)
(node:99449) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:99449) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### npm configuration

```
npm config get registry                           

```
https://registry.npmjs.org/

The same error occurred when I used taobao(https://registry.npm.taobao.org/) mirror source

**Comment by TAlcantara** [comment]
I also can’t download, but the console does not report an error. Just stopped there for a whole day.

**Comment by jacobq** [comment]
Could you please try again (sounds like a transient network/registry problem) and post more information (e.g. how to reproduce)? When I run the following (connecting to the Internet from the USA):

```
$ npm install electron@7.1.2

> core-js@3.4.7 postinstall /home/user/tmp/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> electron@7.1.2 postinstall /home/user/tmp/node_modules/electron
> node install.js

npm WARN saveError ENOENT: no such file or directory, open '/home/user/tmp/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/user/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

+ electron@7.1.2
added 86 packages from 92 contributors and audited 104 packages in 3.956s
found 0 vulnerabilities
```

**Comment by ckerr** [comment]
I'm seeing more-or-less the same output as @jacobq reported in the previous comment and agree this looks like a temporary networking issue.

Marking as blocked/needinfo, @HeiShanLaoYao889 please lmk if this problem persists for you.

**Comment by HeiShanLaoYao889** [comment]
What is your mirror source

**Comment by dsanders11** [comment]
@ckerr, a temporary networking issue wouldn't result in a 404.

@HeiShanLaoYao889, which platform are you using? There's currently a bug where ARM platforms may not be able to install and will see this 404 instead.

**Comment by chanble** [comment]
add _path.txt_ to _node_modules/elelctron_ directory, and write `electron` or `electron.exe` into the file, Then, manually download electron, unzip to _node_modules/electron/dist_. 
------------------------------------------
建个path.txt放到node_modules/electron文件夹下， electron或electron.exe写进去。 手动去下载对应版本的electron解压到electron/dist文件夹下。

**Comment by arleyGuoLei** [comment]
work for me ~ ↓

code ~/.npmrc

add these:

```
electron_mirror=https://cdn.npm.taobao.org/dist/electron/
electron_custom_dir=7.1.9
```

**Comment by ishowshao** [comment]
same issue
i use https://registry.npmjs.org/

**Comment by ishowshao** [comment]
same issue @8.0.0

**Comment by ishowshao** [comment]
I also can’t download, but the console does not report an error. Just stopped there for a whole day.

**Comment by ishowshao** [comment]
when i use a system global proxy, it downloaded

**Comment by kanjieater** [comment]
I'm getting this failing silently as well. It's a proxy issue it would seem.

**Comment by schmorrison** [comment]
Ok I got my post install to work on 8.0.0 and 7.1.7 by running like so:

```npm i --save-dev --arch=armv7l --platform=linux electron@7.1.7```

Problem was I was using ```--arch=arm```. I am not sure what the default behaviour is because the debug message doesn't show the download URL construction, but head over to the [releases page](https://github.com/electron/electron/releases) and find the version you want to download. Then using the --arch and --platform flags in the save command the download URL will look like this: ```https://github.com/electron/electron/releases/download/v{version}/electron-v{version}-{platform}-{arch}.zip```

**Comment by atmanikumar** [comment]
Facing same issue `npm i electron@8.0.0`. Attaching logs below

`npm install electron@8.0.0 --loglevel verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'install',
npm verb cli   'electron@8.0.0',
npm verb cli   '--loglevel',
npm verb cli   'verbose' ]
npm info using npm@6.9.0
npm info using node@v10.16.3
npm verb npm-session 9c01b3535ce8d62f
npm http fetch GET 304 http://registry.npmjs.org/electron 176ms (from cache)
npm timing stage:loadCurrentTree Completed in 2258ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 21ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 1109ms
npm http fetch GET 304 http://registry.npmjs.org/@electron%2fget 71ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/@types%2fnode 108ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/env-paths 66ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/global-agent 67ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/sumchecker 89ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/fs-extra 95ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/global-tunnel-ng 101ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/got 126ms (from cache)
npm http fetch GET 200 http://registry.npmjs.org/es6-error 15ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/matcher 66ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/boolean 79ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/roarr 80ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/serialize-error 81ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/semver 84ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/core-js 98ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/escape-string-regexp 52ms (from cache)
npm http fetch GET 200 http://registry.npmjs.org/globalthis 6ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/sprintf-js 51ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/type-fest 51ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/tunnel 54ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/npm-conf 58ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/config-chain 60ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/pify 61ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/proto-list 49ms (from cache)
npm http fetch GET 200 http://registry.npmjs.org/mimic-response 25ms (from cache)
npm http fetch GET 200 http://registry.npmjs.org/duplexer3 26ms (from cache)
npm http fetch GET 200 http://registry.npmjs.org/decompress-response 28ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/url-parse-lax 76ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/p-cancelable 80ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/lowercase-keys 88ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/cacheable-request 93ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/@szmarczak%2fhttp-timer 95ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/@sindresorhus%2fis 99ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/to-readable-stream 116ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/defer-to-connect 49ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/clone-response 64ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/http-cache-semantics 73ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/get-stream 78ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/keyv 88ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/responselike 90ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/normalize-url 91ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/json-buffer 47ms (from cache)
npm http fetch GET 304 http://registry.npmjs.org/prepend-http 45ms (from cache)
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 2693ms
npm timing stage:loadIdealTree Completed in 4285ms
npm timing stage:generateActionsToTake Completed in 102ms
npm verb correctMkdir /Users/user_name/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /Users/user_name/.npm/_locks/staging-b57551577d11cdc3.lock for /Users/user_name/Documents/digital/project_name/node_modules/.staging
npm timing action:extract Completed in 29ms
npm info lifecycle electron@8.0.0~preuninstall: electron@8.0.0
npm info lifecycle electron@8.0.0~uninstall: electron@8.0.0
npm verb unbuild rmStuff electron@8.0.0 from /Users/user_name/Documents/digital/project_name/node_modules
npm info lifecycle electron@8.0.0~postuninstall: electron@8.0.0
npm timing action:unbuild Completed in 8ms
npm timing action:remove Completed in 8ms
npm timing action:finalize Completed in 4ms
npm timing action:refresh-package-json Completed in 7ms
npm info lifecycle electron@8.0.0~preinstall: electron@8.0.0
npm timing action:preinstall Completed in 0ms
npm info linkStuff electron@8.0.0
npm verb linkBins [ { electron: 'cli.js' },
npm verb linkBins   '/Users/user_name/Documents/digital/project_name/node_modules/.bin',
npm verb linkBins   false ]
npm timing action:build Completed in 6ms
npm info lifecycle electron@8.0.0~install: electron@8.0.0
npm timing action:install Completed in 1ms
npm info lifecycle electron@8.0.0~postinstall: electron@8.0.0

> electron@8.0.0 postinstall /Users/user_name/Documents/digital/project_name/node_modules/electron
> node install.js

`

It stuck at `node install.js`

Please help getting this fixed.

**Comment by qiujinyuan** [comment]
> work for me ~ ↓
> 
> code ~/.npmrc
> 
> add these:
> 
> ```
> electron_mirror=https://cdn.npm.taobao.org/dist/electron/
> electron_custom_dir=7.1.9
> ```

thinks, work for me

**Comment by ryanaltair** [comment]
> work for me ~ ↓
> 
> code ~/.npmrc
> 
> add these:
> 
> ```
> electron_mirror=https://cdn.npm.taobao.org/dist/electron/
> electron_custom_dir=7.1.9
> ```
this trick works 

seems like when run install.js , 
the binary files download stuck at 
`(node:26298) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found) for https://npm.taobao.org/mirrors/electron/v8.1.1/electron-v8.1.1-darwin-x64.zip`

when `https://npm.taobao.org/mirrors/electron/v8.1.1 `is not exist but `https://npm.taobao.org/mirrors/electron/8.1.1 `exist,
>compare v8.1.1 with 8.1.1
 so that's why `electron_custom_dir=7.1.9`  works

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
