### ISSUE TITLE
nativeTheme is undefined

### ISSUE THREAD

**Issue by xland** [electron/electron#21350]
Win10  Electron6.1.4

Code in main process
```js
const { nativeTheme } = require('electron');
console.log(nativeTheme.shouldUseDarkColors)
```
Console log info
> UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'shouldUseDarkColors' of undefined

These codes run correctly,but They are `Deprecated`
```js
const { systemPreferences } = require('electron')
console.log(systemPreferences.isDarkMode())
```

**Comment by MarshallOfSound** [comment]
`nativeTheme` was released in Electron 7.  It is not present in Electron 6

**Comment by xland** [comment]
Thanks
