### ISSUE TITLE
Unable to load Dynamic Images when using with vue js 

### ISSUE THREAD

**Issue by viatenaw** [electron/electron#21368]
OS - Ubuntu 18.04
Electron - 6.1.5
vue-cli-plugin-electron-builder - 1.4.2
Vue - 2.6.10
vuetify - 2.1.12
Node - 10.13.0

I have an app that allows the users to upload images and show them in a gallery view through viewer js `https://github.com/fengyuanchen/viewerjs`. 
After the upload I write the images locally through the main process of electron (I write to reduce the memory 
constrain). As soon as the image is written, I send an event with a unique id to the renderer process when write is complete.
I use a unique id as the filename to store the image so that I can retrive it through this id for intergrating it in the gallery.
When I receive the event and id from the the main process in the renderer, I push the id into a 'docsAdded' array.
To populate the images in the viewer canvas, I iterate over the 'docsAdded' array and try to create a canvas like this :

`<ul ref="images" class="showImage">`
    `<li v-for="(image, index) in docsAdded" :key="index">`
        `<img :src="getLocation(image._id)">`
      `</li>`
`</ul>`
`methods:{`
    `getLocation(id){`
       ` const userDataPath = remote.app.getPath("userData");`
        `const filename = id + '.png'`
       ` let imagesLoc = require.context(userDataPath, true, /\.png$/);`
        `return imagesLoc("./" + filename);`
   ` }`
`}`

This is not helping me as it loads the image but because of some reason it keeps recompiling again and again.
It works perfectly when I tested it with a static filename like:

`methods:{`
`    getLocation(id){`
`        const userDataPath = remote.app.getPath("userData");`
  `      let imagesLoc = require.context(userDataPath, true, /\.png$/);`
`        return imagesLoc("./" + "ck3ofcy4499904a5q2asg1xq0.png");`
`    }`
`}`

To me the issue seems to be triggered because of Dynamic filename.

Any help would be very much appreciated as I'm stuck on this since a very long time.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
