### ISSUE TITLE
Can't open Muti-window after build

### ISSUE THREAD

**Issue by hanjt** [electron/electron#21364]
I open muti-window code like this. 

```
if (isDev) {
    newWindow.loadURL('http://localhost:9080/#' + routerPath)
  } else {
    newWindow.loadFile(`${__dirname}/index.html/#` + routerPath)
    // @ts-ignore
    global.__static = require('path')
      .join(__dirname, '/static')
      .replace(/\\/g, '\\\\')
  }
```

Run `yarn build` and launch the app. When open new window, the debug tools show `chrome-error://chromewebdata`.

**Comment by MarshallOfSound** [comment]
@hanjt You can't provide a `#` to a file path.  It will treat it as part of the file path rather than a hash on a URL.  You should construct the `file://` URL yourself if you want to have a `#` there.
