### ISSUE TITLE
Electron taking too long to load main renderer html file.

### ISSUE THREAD

**Issue by Stanlyhalo** [electron/electron#21369]
I have a custom button that is suppose to launch a new window and load html it sends, it works all good but when I build it and test the build version, it takes a bit to load the html, like about 1-2 seconds. Should I instead launch the child window inside the renderer.js, or the main.js?

The reason I need to do this and it has to be fast, is because the windows are my own custom menu buttons, and menu columns. I used to have these as divs, and it loaded immediately but I wanted them just in case to stick out of the window.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
