### ISSUE TITLE
input box not clickable 

### ISSUE THREAD

**Issue by rajwant** [electron/electron#21362]
The input field not  clickable when I click another window tab then it clickable 

 I need to click outside the electron window.

**Comment by DeepRobin** [comment]
Can you provide a gif or a video?

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by rajwant** [comment]
<div class="wrapper">
    <div class="container absol">
        <div class="row">
            <div class="col-lg-12">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-3"></div>

                        <div class="col-lg-6 bg-white" id="login-block">

                            <div class="m-auto w-lg-75 w-xl-75">
                                <div class="row">
                                    <div class="col-md-12 text-center mt-2">
                                        <a class="text-info font-weight-light m-4 heading log">Login</a>
                                    </div>
                                </div>
                                <div *ngIf="eMsg" class="alert alert-danger">ERROR:--{{eMsg}}</div>
                                <form id="loginform" method="post" role="form" class="frm-wth mt-4" #ff="ngForm">

                                    <div class="form-group"><label class="text-secondary">RetailerId</label>
                                        <input type="text" maxlength="7" required [(ngModel)]="loginform.rid" name="rid" #adminUsername="ngModel" (keypress)="numberOnly($event)" pattern="[0-9]{6,7}" class="form-control" />

                                        
                                        <div *ngIf="adminUsername.invalid && adminUsername.touched" class="alert alert-danger">
                                            <div *ngIf="adminUsername.errors.required">{{common.RetailerIdisrequired}}</div>
                                            <div *ngIf="adminUsername.errors.pattern">{{common.RetailerIdshouldbe60r7digitsandonlynumbersareallowed}} </div>
                                        </div>

                                    </div>

                                    <div class="form-group"><label class="text-secondary">Pin</label>

                                        <input type="password" required [(ngModel)]="loginform.pin" (keypress)="numberOnly($event)" #adminpin="ngModel" maxlength="4" name="pin" class="form-control" pattern="[0-9]{4,4}" />

                                        <div *ngIf="adminpin.invalid && adminpin.touched" class="alert alert-danger">
                                            <div *ngIf="adminpin.errors.required">{{common.PINisrequired}}</div>
                                            <div *ngIf="adminpin.errors.pattern">{{common.PINshouldbe4digitsandOnlynumbersallow}} </div>
                                        </div>

                                    </div>


                                    <div class="form-group" *ngIf="isFetch==false">
                                        <div class="container">
                                            <div class="row">
                                                <div class="col-md-12 text-center">
                                                    <button mat-raised-button (click)="fetchuser()"> <i class="material-icons"> touch_app </i>FetchActiveUsers</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-group" *ngIf="isFetch==true">
                                        <mat-form-field class="example-full-width">
                                            <mat-select matNativeControl name="sampleType" id="sampleType" placeholder={{common.SelectUser}} [(value)]="selected" required>
                                                <mat-option *ngFor="let sample of User.listUsers" [value]="sample.aadharUserId" (click)="user(sample)" required> {{sample.shopUserName}} ({{ sample.aadharNo }}) </mat-option>
                                            </mat-select>
                                        </mat-form-field>
                                    </div>


                                    
                                    <div class="container">
                                        <div class="row">
                                            <div class="col-lg-12 text-center mb-3">
                                                <div class="row">
                                                    <div class="col-md-12">
                                                        <button class="w-100 btn btn-info mt-2  buttonNext buttonc-mob mb-2" mat-button name="login-submit" id="login-submit" data-target="#myModal" data-toggle="modal" value="Log In" [disabled]="loginform.invalid">
                                                            {{common.Login}} <mat-icon class="mob-hide">account_circle</mat-icon>
                                                        </button>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-md-12" *ngIf="isFetch==true">
                                                        <button class="w-100 btn btn-danger mt-2 buttonBack buttonc-mob" mat-button name="login-submit" id="login-submit" (click)="home()" value="Log In">
																<mat-icon class="mob-hide" >keyboard_arrow_left</mat-icon> Back
															</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    

                                </form>

                            </div>
                        </div>

                        <div class="col-lg-3"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="modal" id="myModal">
    <div class="modal-dialog modal-lg">
        <div class="modal-content ">

            <div class="modal-header text-center" id="notpritarea">
                <h1 class="modal-title text-center" id="pritarea" *ngIf="lan=='eng'"><strong>{{common.ConsentofAadhaarHolder}}</strong></h1>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <div class="modal-body" id="pritarea1" *ngIf="lan=='eng'"> {{common.consentDetails}} </div>

            <div class="imgCenter">
                <img src="http://img.jetbitts.com/screensavers/down/misc/thumbprint_zkh6r47f.gif" />
            </div>

            <div class="text-center mb-3" id="notpritarea" *ngIf="lan=='eng'">

                <button mat-raised-button class="back text-center" data-dismiss="modal">{{common.Decline}}</button> &nbsp;&nbsp;
                <button mat-raised-button class="mat-success text-center" data-dismiss="modal" (click)="capture(deviceinfo)">{{common.Accept}}</button> <br>
            </div>

        </div>
    </div>
</div>



this is the template of that page which is stuck

**Comment by rajwant** [comment]
> Can you provide a gif or a video?


[Microsoft Game DVR - DBT IN FERTILIZER - VLC media player 2019-12-04 09-45-16.zip](https://github.com/electron/electron/files/3919951/Microsoft.Game.DVR.-.DBT.IN.FERTILIZER.-.VLC.media.player.2019-12-04.09-45-16.zip)
