### ISSUE TITLE
The stable version of electron and chromium.

### ISSUE THREAD

**Issue by zhangyuliangzyl** [electron/electron#21363]
Hi, electron
  As the document saying, electron 8.0.0-beta.3 will update chromium to the version 80.
![image](https://user-images.githubusercontent.com/14748450/70028698-50c27400-15e0-11ea-8d20-56bb2ec16110.png)

  But I found the chrome team's schedule showing, the stable chromium 80 will release in Feb 4, 2020.
![image](https://user-images.githubusercontent.com/14748450/70028878-b9a9ec00-15e0-11ea-83f1-3f403c38cbb5.png)

  So could you please tell me what kind of plan about you release electron 8.0.0 stable  version?
  And please show me some advice to choose the version if I want get an absolute stable electron during Dec 2019. It will be very helpful.
  Thanks!

**Comment by MarshallOfSound** [comment]
Our release timelines are [in our docs](https://electronjs.org/docs/tutorial/electron-timelines)
