### ISSUE TITLE
Screen dimensions are off by one pixel in offscreen mode

### ISSUE THREAD

**Issue by x-yuri** [electron/electron#21379]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v7.1.3
* **Operating System:**
  * Arch Linux

### Expected Behavior

Given that
```sh
real_screen_width=$(xdpyinfo | grep dimensions: | awk '{print $2}' | sed -E 's/x.*//')
real_screen_height=$(xdpyinfo | grep dimensions: | awk '{print $2}' | sed -E 's/.*x//')
```
When
```js
new BrowserWindow({
    width: $real_screen_width,
    height: $real_screen_height,
    show: false,
    webPreferences: {offscreen: true}})
```
Then
```js
screen.width == $real_screen_width
screen.height == $real_screen_height
```

### Actual Behavior

```js
screen.width == $real_screen_width - 1
screen.height == $real_screen_height - 1
```

### To Reproduce

`index.js`:

```js
const { app, BrowserWindow } = require('electron');

function createWindow () {
    let win = new BrowserWindow({
        width: 1920,
        height: 1080,
        show: false,
        webPreferences: {
            offscreen: true,
        }
    });

    win.loadFile('index.html');
}

app.on('ready', createWindow);
```

`index.html`:

```html
<!doctype html>
<html>
<body>

<script>
    console.log(screen.width, screen.height);
</script>

</body>
</html>
```

```
$ xdpyinfo | grep dimensions: | awk '{print $2}'
1920x1080

$ npm i -D electron@7.1.3

$ ELECTRON_ENABLE_LOGGING=1 npx electron .
...
[4121886:1204/101853.969957:INFO:CONSOLE(6)] "1919 1079", source: ...
```

### Additional Information

It [breaks running `cypress` tests][1] because the screenshots are feeded to `ffmpeg`, and the latter [doesn't always tolerate][2] odd dimensions.

[1]: https://github.com/cypress-io/cypress/issues/3491
[2]: https://trac.ffmpeg.org/ticket/309#comment:3

**Comment by AndreVirtimo** [comment]
I have the same issue on my build server (Ubuntu 18.04). I have applied a fix in the xvfb lib.

https://github.com/cypress-io/cypress/issues/2102#issuecomment-544412048
