### ISSUE TITLE
Cannot be set request header `referer` in webRequest.onBeforeSendHeaders in version 7.1.3 but works fine in version 6.x and 5.x.

### ISSUE THREAD

**Issue by leoding86** [electron/electron#21374]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.3
* **Operating System:**
  * Windows 10 (1903)
* **Last Known Working Electron version:**
  * 6.1.5

### Expected Behavior
Request header 'referer' can be set in webRequest.onBeforeSendHeaders

### Actual Behavior
Request header 'referer' cannot be set in webRequest.onBeforeSendHeaders

### To Reproduce
I use local server to recieve the request come from electron's net module. I use [electron/electron-quick-start](https://github.com/electron/electron-quick-start) as a template to reproduce this. Add these lines below to the beginning of the function 'createWindow' which in the file 'main.js':
```js
  session.defaultSession.webRequest.onBeforeSendHeaders(function (details, callback) {
    details.requestHeaders['referer'] = 'https://www.github.com' // cannot not be set in electron version 7.1.3
    details.requestHeaders['x-electron-version'] = process.versions['electron']

    callback({
        requestHeaders: details.requestHeaders
    })
  })

  let request = net.request('http://127.0.0.1/headers.php');

  request.on('response', response => {
    let body = '';

    response.on('data', data => {
      body += data;
    });

    response.on('end', () => {
      console.log(JSON.parse(body));
    });
  });

  request.end();
```

### Screenshots
Request header referer can be set in v6.1.5:
![referer can be set](https://raw.githubusercontent.com/leoding86/image-storage/master/electron-issue-7.x-002.png)

Request header referer can't be set in v7.1.3:
![referer can't be set](https://raw.githubusercontent.com/leoding86/image-storage/master/electron-issue-7.x-001.png)

### Additional Information
In version 7.x, the request headers referer can’t been set in webRequest.onBeforeSendHeaders. I find some information in the issue #20923 and I think this is caused by the same reason too which is the webRequest in electron uses the extraHeaders: false code path in Chromium. Then I find some code comments in the merge #21099 which explain the request created by net module can’t handle by Chromium(But it can be set in onBeforeSendHeaders  in version 5.x and 6.x). Both setHeader and onBeforeSendHeaders can’t set referer header. Is there any way to set referer header by using built-in modules? Or is it a bug need to be fixed?

**Comment by walmat** [comment]
Related #23102

**Comment by nornagon** [comment]
Is this still an issue in 8.x+?

**Comment by walmat** [comment]
I believe this is resolved for me in 8.x.y, however I am setting them directly in the request headers before sending the request itself and not utilizing the hook like OP.

**Comment by true-zero** [comment]
Still broken, the pull request to "fix" this uses the correct spelling of the word (referrer) even though the misspelling as `Referer` is now codified as standard.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
