### ISSUE TITLE
Provide a way to postpone electron initialization

### ISSUE THREAD

**Issue by JasonYeMSFT** [electron/electron#21370]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
According to #1726, electron starts initializing and at some point emits 'ready' event once the main process starts. The process is asynchronous to the user's main process script. However, there are functions that can only run before app is ready. For example, https://electronjs.org/docs/api/app#appdisablehardwareacceleration
https://electronjs.org/docs/api/app#appdisabledomainblockingfor3dapis

With the current architecture, the programmer has no way to guarantee that such function can be called before app is ready, even if he puts these function calls at the beginning of his main process script.

### Proposed Solution
Have a user defined trigger function to initiate the electron initialization process. For example, `app.beginInitialize()` which triggers the initialization process. Then the programmer can call whatever function that has to be called before app is ready, invoke this function to start initialization process, listen to 'ready' event and then run code after the app is ready.

If the user doesn't need any of these functions, he can just call `app.beginInitialize()` at the first line of his main script.

### Alternatives Considered
Create command line arguments for these function and embed them into the initialization process. This can also guarantee that the program can run as expected.

**Comment by MarshallOfSound** [comment]
> With the current architecture, the programmer has no way to guarantee that such function can be called before app is ready, even if he puts these function calls at the beginning of his main process script.

This is incorrect.  The synchronous execution of your main process script is guaranteed to happen before the app is ready.  i.e. As long as you call these methods syncronously when your main file is called you'll be fine.  It shouldn't be possible for the app to be ready before your script runs.

**Comment by MarshallOfSound** [comment]
Sorry didn't mean to close this, if you have an example of an app that is "ready" before your code runs please provide a repro.

**Comment by JasonYeMSFT** [comment]
> With the current architecture, the programmer has no way to guarantee that such function can be called before app is ready, even if he puts these function calls at the beginning of his main process script.
> 
> This is incorrect.  The synchronous execution of your main process script is guaranteed to happen before the app is ready.  i.e. As long as you call these methods syncronously when your main file is called you'll be fine.  It shouldn't be possible for the app to be ready before your script runs.

This actually addresses our current concerns because we are not calling any async function. However, some program may need to make async calls to determine what function to call.

The following code will cause the function being called after "ready" event.

```JavaScript
new Promise((resolve, reject) => {
  // simulate an async call which resolves after some time
  setTimeout(resolve, 3000);
}).then(() => {
  // calling app.disableHardwareAcceleration
  console.log("disable gpu");
});
...

app.on("ready", function () { console.log("ready"); });
```

I don't see a way to force the promise to resolve before app is ready.

**Comment by jhudson8** [comment]
Hello, are there any updates here?  I have a real world use case.  I need to be able to set "userData" path base on an application name I retrieve asynchronously.

Since the app.setPath ('userData', ...) function can only be called before the "ready" event is fired, the success of the logic is non-deterministic.

Is there a workaround available?  Thanks for the help.

**Comment by nornagon** [comment]
This is architecturally unviable in Electron, so I'm going to close this as wontfix.

@jhudson8 I recommend reading your configuration files synchronously if they need to be read before app start, e.g. using `fs.readFileSync`.

**Comment by Iku-turso** [comment]
@nornagon how can this be architecturally unviable? The requirement for async stuff before the electron app starts is clear as day. Mere technical challenges are no reason to wontfix this.

**Comment by sschultze** [comment]
From the [documentation about Electron 28's ESM support](https://www.electronjs.org/docs/latest/tutorial/esm#you-must-use-await-generously-before-the-apps-ready-event), it can be inferred that with top-level `await` available in ES modules, it is now indeed possible to do asynchronous stuff before the `ready` event, as long as you use ESM and `await` the asynchronous calls it in the main ES module.

This indeed seems to work - tested with the following code (`.mjs` file):

```js
import { app } from 'electron';

console.log('Hi.');

app.on('ready', () => {
    console.log('Ready event emitted.');
});

console.log('Waiting five seconds.');
await new Promise(resolve => setTimeout(resolve, 5000));
console.log('Finished waiting five seconds.');
```

Output:
```
Hi.
Waiting five seconds.
Finished waiting five seconds.
2023-12-23 10:36:54.513 Electron[1782:27223] WARNING: [...]
Ready event emitted.
```
