### ISSUE TITLE
Lastpass icon shows in text fields

### ISSUE THREAD

**Issue by miguel-a-calles-mba** [electron/electron#21389]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v2.0.18
  * macOS 10.15.1
* **Last Known Working Electron version:**
  * 

### Expected Behavior

Login input fields should not show the LastPass Chrome extension icon.

### Actual Behavior

I see the LastPass icon in the login fields.

### To Reproduce

Create a login form using Bootstrap and install the LastPass Chrome extension in the Chrome app.

### Screenshots

![image](https://user-images.githubusercontent.com/44813512/70196176-c13ec300-16bc-11ea-9c35-15f707b30701.png)

**Comment by ckerr** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron reported in this issue (2.0.18) has reached end-of-life is no longer supported. If you still experience this in the latest supported versions of Electron and would like this issue to remain open, please add a comment specifying the version you're testing with and any other information that a maintainer needs to know to reproduce the issue.

In addition, if the issue persists, would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by miguel-a-calles-mba** [comment]
Hi @ckerr, I upgraded to electron@4.0.0 and still seeing the same issue.

**Comment by miguel-a-calles-mba** [comment]
I forked electron-quick-start and added my logging page HTML code. I still see the same behavior.

![image](https://user-images.githubusercontent.com/44813512/70287448-c6b31080-1783-11ea-8712-af9796ca74e0.png)

**Comment by miguel-a-calles-mba** [comment]
Thanks for the tip! Some rogue inline styles that somehow made it into the HTML code. I removed it and all is good now.

![image](https://user-images.githubusercontent.com/44813512/70287558-2c9f9800-1784-11ea-955c-9b116920b253.png)
