### ISSUE TITLE
`ClientRequest` doesn't report upload progress in 7.1.3

### ISSUE THREAD

**Issue by romansp** [electron/electron#21385]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.3
* **Operating System:**
  * macOS 10.15.1
* **Last Known Working Electron version:**
  * 6.1.5

### Expected Behavior
`request.getUploadProgress()` returns correct information about upload progress after request has started.

### Actual Behavior
`request.getUploadProgress()` always comes as `{}`.

### Additional Information
I did some debugging, and it's very much likely that it got broken in https://github.com/electron/electron/pull/21244 refactoring. From what I see now is that `this._urlLoader` in net.js doesn't emit `upload-progress` event at all, thus `this._uploadProgress` always remains empty.
Setting `chunkedEncoding` to `false/true` doesn't help either. 

I don't have minimal reproduction available right now, but will try to provide one ASAP.

**Comment by nornagon** [comment]
Thanks for the report! #21388 should solve this.

**Comment by romansp** [comment]
Is it supposed to report progress when `chunkedEncoding` is enabled? Because I don't see that happening.

Fiddle link: https://gist.github.com/romansp/cba4c03f92e92b9d857b2bf300039677
Try toggling between `chunkedEncoding=true/false`. When it's `false`, it will show consequent alerts with progress, but when it's set `true` you only get final "upload done" alert.

**Comment by nornagon** [comment]
I think that's correct behavior... there's no way for Chrome to know how big a chunked upload is, so it can't really meaningfully provide a 'progress' event. Chunked encoding is meant for streaming data like video or audio, which doesn't really have "upload progress" per se.

**Comment by nornagon** [comment]
Here's the code in Chromium responsible: https://cs.chromium.org/chromium/src/services/network/upload_progress_tracker.cc?l=61-62&rcl=0ad497d62a56e2b59c3923d37406d3c82150a60b

Note the comment about chunked upload.

```cpp
  if (!progress.size())
    return;  // Nothing to upload, or in the chunked upload mode.
```

**Comment by dkorobeinikov** [comment]
Hi @nornagon . Is it possible to somehow patch Chromium's `net` module to return at least `current` uploaded value?
According to the code Chromiums [code](https://source.chromium.org/chromium/chromium/src/+/master:services/network/upload_progress_tracker.cc;bpv=0;bpt=1?originalUrl=https:%2F%2Fcs.chromium.org%2F), it uses some [threshold](https://source.chromium.org/chromium/chromium/src/+/master:services/network/upload_progress_tracker.cc;l=77;bpv=0;bpt=1?originalUrl=https:%2F%2Fcs.chromium.org%2F)  to decide whether to emit `upload-progress` event. 

```
  bool enough_new_progress =
      (amt_since_last > (progress.size() / kHalfPercentIncrements));
```

I think in case we don't have `progress.size()` we could use some threshold in bytes (let's say 200b), for that. 
So, for `chunkedEncoding=true` request, we could just return `{active: true, started: true, total: undefined, current: ${uploaded-bytes}}`. This would allow the developers to ensure that uploading is in progress, show at least the uploaded size and make the applications more responsive.

Also, I believe, in most cases Electron apps send large local files using `chunkedEncoding=true`. So, the developer could get the file size via `fs.statSync(fileName).size` and using the `current` property show the percentage as well.

**Comment by nornagon** [comment]
I'm not sure I understand your use case; if you're using chunked encoding then you're providing the streaming data to the net module. You can just count the bytes you've sent so far, no?

**Comment by dkorobeinikov** [comment]
I thought so too. But an actual read data is not  equal to those, that already uploaded. for ~1500MB file I got it read as `ReadableStream` and written to `request` object by ~3 seconds, but it gets uploaded to the server after 1-2 minutes
