### ISSUE TITLE
Cursor scales incorrectly

### ISSUE THREAD

**Issue by jacobq** [electron/electron#21409]
* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.0.0-beta.3 (also exists on v8.0.0-beta.4 & 9.0.0-nightly.20191204)
* **Operating System:**
  * Debian (bullseye/sid) Linux (5.3.0-2-amd64)
* **Last Known Working Electron version:**
  * v8.0.0-beta.2

### Expected Behavior
Moving the cursor onto the electron application's window from outside should not cause it to change size.

### Actual Behavior
When the cursor moves within the frame of the window it shrinks.
Screen recording of behavior is here: https://imgur.com/a/oL6Nf8V
Using `--force-device-scale-factor=2` does not help (cursor remains the same, small size).

### To Reproduce

1. Run electron-quick-start application with v8.0.0-beta.3
2. Move (mouse) cursor in and out of window

Might be platform/system dependent. In my case I was using a high DPI display on 4K monitors in Linux.

### Screenshots
Refer to link in "Actual Behavior" section above.

### Additional information

I suspect that this could be related to the upgrade to Chromium 80.

**Comment by jacobq** [comment]
I just confirmed that this same behavior occurs in the latest Chromium, so this is an upstream problem. Demo video here: https://imgur.com/a/QN1eSni

I believe this is the same problem described here: https://bugs.chromium.org/p/chromium/issues/detail?id=1021819

**Comment by MarshallOfSound** [comment]
Closing out as it is tracked upstream at https://bugs.chromium.org/p/chromium/issues/detail?id=1021819
