### ISSUE TITLE
Electron app window rendering broken on Linux with 10 Bit per color (30 Bit) Desktop rendering with Nvidia GPU

### ISSUE THREAD

**Issue by irieger** [electron/electron#21414]
### Preflight Checklist
* [X ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.1.5 (At least in VS Codium, don't know what Slack uses)
* **Operating System:**
  * Xubuntu 18.04 / Xubuntu 19.10
* **Last Known Working Electron version:**
  * Don't know if it ever worked

### Expected Behavior
Correct rendering of colors, icons and text. I use Chromium in the screenshots as I didn't want to publish my active Slack chats or code windows from Codium.

![chromium-render-bug-10bit_expected](https://user-images.githubusercontent.com/142033/70326000-b195ba80-1833-11ea-9769-5e40fbbf3a7a.png)
(Created with regular Nvidia driver settings)

### Actual Behavior
The actual behavior is wrong colors, being rendered, strange shadows/outlines around text and icons etc.  Effect shown is exactly the same for Codium or Slack, maybe a bit less readable than the rendering in Chrome, maybe related to font sizes.

![chromium-render-bug-10bit](https://user-images.githubusercontent.com/142033/70309993-fd823880-180e-11ea-88c1-f53bb8775d8d.png)
(Created with Nvidia driver set to 10 bits per color, see below)

### To Reproduce
Switch the Nvidia driver to 10 bits per color (1.1 Billion colors) mode for X screen 0:
![nvidia-settings-30bit](https://user-images.githubusercontent.com/142033/70328124-9a0d0080-1838-11ea-8b73-c071db933856.png)

This needs a driver newer than 431.70 which is the first version they allow consumer hardware to output 10 bpc. Nvidia says in a document that at least one monitor connected needs to have 10 bit for this, but maybe it works also with none. If 10 bps mode is activated they just dither and output 8 bit for every monitor not supporting 10 bits.

### Additional Information
I can reproduce this issue with every Electron/Chromium based application I tried. Tried with Slack, VS Codium and Chromium itself. All other software works fine with 10 bits per color rendering in the Nvidia driver activated. For image processing 10 bits per color really makes a difference so it is really nice Nvidia opened it up for the consumer hardware so it would be cool to see all software work as expected.

Hope the electron project is the right place to report but to me as a user it seems directly related to electrons rendering so I thought I'd directly report here. If I need to try something or can supply any more information I'm happy to setup a build environment to try stuff myself. While I don't use Chromium that often defect Slack and Codium is bad for my daily use.

Tested with Nivida drivers 435.21 and 440.33, Chromium from the Ubuntu repository (package chromium-browser), Slack from "Ubuntu Software Store" and VS Codium from the repo on https://vscodium.com/ . All systems with the newest updates tested over the last several weeks.
GPUs are all Nivida GeForce GPUs with Pascal chips (1050 Ti, 1070 and 1080 Ti)

**Comment by MarshallOfSound** [comment]
> Tried with Slack, VS Codium and Chromium itself

This should be reported directly to Chromium.  https://crbug.com
