### ISSUE TITLE
App crashes when BrowserView tries to both resize and destroy itself (almost) simultaneously

### ISSUE THREAD

**Issue by jiwonchang** [electron/electron#21410]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
I'm currently using BrowerView to act as a makeshift tab (so that I may have multiple "tabs" of my application open). When I create 20+ processes and shut them down (shutting them down calls view.destroy()) very quickly and _then_ right afterwards try to resize the window, the app crashes with Error 3221226525.

When I disable the call to view.destroy(), I no longer get this issue. This works, since Javascript garbage collection will collect the processes after a minute or two, but this solution seems a bit suboptimal and unreliable in the case where we may have weak references left over.

I tried to work around this by disabling resizing for those BrowserViews (via view.setAutoResize()) and _then_ calling view.destroy(), but this does not fix the issue.

* **Electron Version:**
  *  7.1.2
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior

Close many BrowserViews quickly and then Resize right afterwards --> Window should resize without crashing.

### Actual Behavior

Close many BrowserViews quickly and then Resize right afterwards --> App crashes (if I don't resize, no crash).

### To Reproduce

As mentioned above, we need to create 20+ processes and shut them down (shutting them down calls view.destroy()) very quickly and _then_ right afterwards try to resize the window. The app should crash with Error 3221226525.

### Screenshots

![IceT Nova BrowserView Crash Error](https://user-images.githubusercontent.com/20053828/70284635-7fc01d80-1779-11ea-9147-d3480d7b5bfd.PNG)

### Additional Information

This problem exists in both Electron v5.0.0 and v7.1.2.

Question: Let's say I take the "don't destroy, let processes get garbage collected" route. Is it possible that the app will also crash during garbage collection if the user happens to resize just as a process is being destroyed?

Thank you for your time, and I look forward to hearing from you!

**Comment by jiwonchang** [comment]
Hello @sofianguy ,

Are there any updates to this? I'm hoping that this issue can be resolved soon as I find the garbage collection process to be unreliable (as it does not successfully collect all garbage and leave a few hanging around).

Please let me know. Thank you!

**Comment by pushkin-** [comment]
@jiwonchang destroying the browserview appears to be for force-close types of scenarios. I wonder if you can just do `browserWindow.removeBrowserView(browserView)` for all of the views. Are you doing this workflow when shutting down the entire app, or just the browser view processes?

**Comment by codebytere** [comment]
Closed in https://github.com/electron/electron/pull/25411
