### ISSUE TITLE
Flash player not working in multiple versions of electron for MacOS

### ISSUE THREAD

**Issue by kkannan-carecloud** [electron/electron#21426]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**

* **Operating System:**
 7.1.2
6.1.5
3.1.13
* **Last Known Working Electron version:**
None

### Expected Behavior
Run Flash movie

### Actual Behavior
Movie does not load

### To Reproduce

1. To make sure the website supports flash, go to "https://helpx.adobe.com/flash-player.html" 
<img width="343" alt="Screen Shot 2019-12-06 at 5 47 59 PM" src="https://user-images.githubusercontent.com/5374592/70362945-a2733480-1854-11ea-9093-aaccef6f9751.png">

If it doesn't work in the 1st try, change the settings to `Allow` in chrome. 

Notice that a Flash movie renders at the bottom of the page. 
<img width="455" alt="Screen Shot 2019-12-06 at 5 46 27 PM" src="https://user-images.githubusercontent.com/5374592/70363028-e108ef00-1854-11ea-8be7-99670cfdde08.png">

Now run the following code below in a test app, with the latest version of electron.
```
const {app, BrowserWindow} = require('electron');
const path = require('path');
let mainWindow;

app.on('window-all-closed', function() {
  if (process.platform != 'darwin')
    app.quit();
});


let ppapi_flash_path;

// Specify flash path.
// On Windows, it might be /path/to/pepflashplayer.dll
// On OS X, /path/to/PepperFlashPlayer.plugin
// On Linux, /path/to/libpepflashplayer.so
if(process.platform  == 'win32'){
  ppapi_flash_path = path.join(__dirname, 'pepflashplayer.dll');
} else if (process.platform == 'linux') {
  ppapi_flash_path = path.join(__dirname, 'libpepflashplayer.so');
} else if (process.platform == 'darwin') {
  ppapi_flash_path = path.join(__dirname, 'PepperFlashPlayer.plugin');
}

app.commandLine.appendSwitch('ppapi-flash-path', ppapi_flash_path);
console.log(ppapi_flash_path);
// Specify flash version, for example, v18.0.0.203
app.commandLine.appendSwitch("ppapi-flash-version", "32.0.0.293");


app.on('ready', function() {

                             mainWindow = new BrowserWindow({
                               width: 1600,
                               height: 800,
                               webPreferences: { plugins: true },
                               useContentSize: true,
                               webSecurity: false,
                               allowRunningInsecureContent: true,
                               fullscreenWindowTitle: false
                             });
                             mainWindow.webContents.openDevTools();
                             
                             mainWindow.loadURL(
                               "https://helpx.adobe.com/flash-player.html"
                             );
                           });
```

I have made sure the plugin is enabled in the app by running the navigator.plugins
### Screenshots
![Flash Not working](https://user-images.githubusercontent.com/5374592/70362836-558f5e00-1854-11ea-89be-0a7a08e05610.png)

The Flash player is not working within the electron app.

**Comment by Rosslington** [comment]
Most likely related to #20744 

Would recommend setting "webviewTag" to true in your web preferences, and downgrading to Electron v6.1.2 (the latest version that still has remote Flash sources working correctly as far as a I know).

**Comment by kkannan-carecloud** [comment]
@Rosslington Thank you very much for your support. It worked without the `webviewTag: true` and just by downgrading the version to v6.1.2.
