### ISSUE TITLE
Electron's Web App

### ISSUE THREAD

**Issue by eaedk** [electron/electron#21429]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

There is no automatic way to use an application made with Electron as a website that can be deployed.

### Proposed Solution

Make a builder so that an Electron's app can be deployable online or locally like Flask or Django apps.

**Comment by superheri** [comment]
The way to convert an existing nodejs web app into an electron app could be cool too.

**Comment by eaedk** [comment]
ok

**Comment by loc** [comment]
While this is out of scope for what core Electron would support, something like this could certainly exist in https://github.com/electron-userland/, if you'd like to contribute. The technical challenge will be in the narrowing surface area; Electron has a wider API surface area than the web, so many of the things that make Electron apps useful wouldn't work. PWA's are becoming more and more popular as an alternative to a full app — maybe those would be more feasible to adapt back and forth. Thanks for the feedback.
