### ISSUE TITLE
App "freezes" after modal window with print options is closed/cancelled

### ISSUE THREAD

**Issue by clusterberries** [electron/electron#21439]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.12, 6.1.4
* **Operating System:**
  *  Windows 10
* **Last Known Working Electron version:**
  * 5.0.2

### Expected Behavior
Application responses to user actions after print is cancelled. (log statements are in the console)

### Actual Behavior
Application doesn't handle events (e.g. click) after print is cancelled. (no log statements in the console)

### To Reproduce
Precondition: clone this repository to reproduce the issue:
https://github.com/clusterberries/electron-sample/tree/print-page
```sh
$ git clone https://github.com/clusterberries/electron-sample.git -b print-page
$ npm install
$ npm start
```
1. Click 'print me' button, so modal window appears
2. Close or cancel modal window
3. Click 'print me' and/or 'test' buttons
4. Observe the console in dev tools.

### Additional Information
The issue is not reproduced with Electon 7.1.3.

**Comment by codebytere** [comment]
This is unfortunately known, and can't be fixed in 5-0-x given some changes that were made in Chromium at the time. 5-0-x is also only receiving security fixes at this time, so sadly, your best bet at this time is to upgrade to a version of Electron where this issue is not present.

**Comment by vladimiry** [comment]
Simply referencing the original and still open issue #19768.
