### ISSUE TITLE
Official compilation guidance not working on macOS 10.14.6

### ISSUE THREAD

**Issue by xiao2013** [electron/electron#21433]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
I am trying to follow the developer's official guide to build the electron from scratch. https://electronjs.org/docs/development/build-instructions-macos#prerequisites

My macOS is 10.14.6. I followed the instruction to use xcode 9.4.1 with sdk version 10.13 to build. 
However I got following error saying that they need 10.14+. Is the documentation out dated?

=======================================================
ERROR at the command-line "--args":1:1: Unable to load "/Users/dd/electron-gn/src/electron/build/args/debug.gn".
import("//electron/build/args/debug.gn")  cc_wrapper="/Users/dd/electron-gn/src/electron/external_binaries/sccache"
^--------------------------------------
~/electron-gn/src @ dd-MacBook-Pro(dd): gn gen out/Release --args="import(\"//electron/build/args/release.gn\") $GN_EXTRA_ARGS"
ERROR at //build/config/mac/mac_sdk.gni:80:5: Script returned non-zero exit code.
    exec_script("//build/mac/find_sdk.py", find_sdk_args, "list lines")
    ^----------
Current dir: /Users/dd/electron-gn/src/out/Release/
Command: python /Users/dd/electron-gn/src/build/mac/find_sdk.py --print_sdk_path --print_bin_path 10.14
Returned 1.
stderr:

Traceback (most recent call last):
  File "/Users/user/electron-gn/src/build/mac/find_sdk.py", line 127, in <module>
    print(main())
  File "/Users/dd/electron-gn/src/build/mac/find_sdk.py", line 96, in main
    raise Exception('No %s+ SDK found' % min_sdk_version)
Exception: No 10.14+ SDK found

See //build/config/sysroot.gni:64:3: whence it was imported.
  import("//build/config/mac/mac_sdk.gni")
  ^--------------------------------------
See //base/BUILD.gn:31:1: whence it was imported.
import("//build/config/sysroot.gni")
^----------------------------------
See //BUILD.gn:67:5: which caused the file to be included.
    "//base:base_perftests",
    ^----------------------
 
=======================================================
 I have tried to use higher version of xcode( equipped with sdk 10.14 and sdk 10.15) to build electron, however, both of them failed. For sdk 10.14, I have problems with connection time out. For 10.15, I have same problem with user reported on stackover flow https://stackoverflow.com/questions/58794301/errors-when-building-electron-from-source-with-gn-and-ninja-on-mac-os-10-15

Could someone help me to provide a working guide? It is really hard to uninstall and install the electron and changing xcode version everyday due to slow compilation.

**Comment by codebytere** [comment]
@xiao2013 i recommend you use https://github.com/electron/build-tools.

**Comment by MarshallOfSound** [comment]
☝️ It has a handy tool `e load-macos-sdks`

**Comment by xiao2013** [comment]
@codebytere @MarshallOfSound  Thank you. Currently when I use build tool I can only access to the newest version of the electron which is 9.0.0 nightly. If I want to access 7.1.2 or 6.0.0 how I can compile them locally?

**Comment by codebytere** [comment]
@xiao2013 not quite - you're looking at what's in the version file, which is just `master`, not the nightly itself. You need to check out the release branch, which would be `8-x-y`, `7-1-x` or similar.

**Comment by xiao2013** [comment]
@codebytere Thank you, another stupid question...when I use `build-tools` I run `e build electron`, I always end up produce the `electron.app` in `out/testing` folder. But I also notice that you should be able to build for release right? Whats the difference between the testing and release version? Also, if I build with `e build electron:dist`. I will get a `dist.zip` file, which contains electron. If I replace the folder to my personal electron module in `node_modules` folder. Does that means that the electron is modified to the version that I modified by myself?
