### ISSUE TITLE
showmessagebox - callback not working

### ISSUE THREAD

**Issue by jabelcs** [electron/electron#21432]
Hello all.

I've been working in a project for some time and recently I just noticed that showmessagebox callback stopped working.

I use it in the update process, here is my code:

dialog.showMessageBox({
		 type: 'question',
		buttons: ['Reiniciar', 'Mais tarde'],
		defaultId: 0,
		message: 'Estão disponíveis novas actualizações.\nPor favor, reinicie a aplicação para aplicar as actualizações.',
		title: 'Impulsive CRM',
		detail: `A aplicação será atualizada para a versão ${updateInfo.version} de ${dt}.`
	}, response => {
		if (response === 0) {
			autoUpdater.quitAndInstall();
		}
	});

The code autoUpdater.quitAndInstall(); is never fired.

I even tried this code in Electron Fiddle for Mac and it doesn't work. The message window is shown but when you click a button the callback is not fired.

System details:
Electron: 7.1.3
Npm: 6.13.1
Node: 13.1.0

Thanks in advance.

**Comment by popod** [comment]
This is a [breaking change of 6.0.0](https://electronjs.org/releases/stable?version=6&page=4#release-notes-for-600). See [the doc here](https://electronjs.org/docs/api/dialog#dialogshowmessageboxbrowserwindow-options).

**Comment by MarshallOfSound** [comment]
Closing out as per above, this was a breaking change as part of the promisification project.  The old API was appropriately deprecated and then removed.
