### ISSUE TITLE
Running iframe/webview in vm

### ISSUE THREAD

**Issue by danbulant** [electron/electron#21430]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

I need to run webview in vm2 to restrict path. The code that's to be run is untrusted, thus I want to restrict the path FS can access. The code needs access to nodeintegration.

### Proposed Solution

Either allow running iframe in vm (vm2) or add an option in webview to restrict path FS can access.

**Comment by MarshallOfSound** [comment]
Implementing policy based node API restrictions is out of scope for the Electron project.

Node has experimental support for permissions / policy systems nowadays too: https://nodejs.org/api/permissions.html#policies
