### ISSUE TITLE
WebXR Support

### ISSUE THREAD

**Issue by Dmarcoux111** [electron/electron#21446]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

When Chrome 79 becomes stable (December 10th), support for webxr ( replacement for webvr ) will be included by default.

### Proposed Solution

Will Electron versions bundled with 79 also include webxr support? I know this has been discussed extensively, but I couldn't find a straight answer.

**Comment by MarshallOfSound** [comment]
Electron 8 will ship with Chromium 80.  Any feature enabled by default in Chromium 80 will also be enabled in Electron.  Please note that Chrome feature set and Chromium's feature set may not be the same thing.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

**Comment by Dmarcoux111** [comment]
Darn, tried with the nightly build and no dice, something special probably has to be done on the bundling side. Can I still request this feature? I know you guys would rather push any feature stuff off to Native Modules, but (totally speculating) I feel like the work involved with wrapping openVR/whatever else for Oculus etc. would be more work than just getting it to work on the Electron side of things with whatever flags / src need to be added/built.

**Comment by Dmarcoux111** [comment]
@MarshallOfSound Yup, chrome 79 has webxr enabled by default, its in the chromium blog too. I was able to get it working in chrome bydisabling the xr-sandbox flag. Would be sweet if electron allowed us to append other flags than the supported ones to get this working like it did in older versions.

**Comment by wangzhongliang** [comment]
> @MarshallOfSound Yup, chrome 79 has webxr enabled by default, its in the chromium blog too. I was able to get it working in chrome bydisabling the xr-sandbox flag. Would be sweet if electron allowed us to append other flags than the supported ones to get this working like it did in older versions.

Hi, Dmarcoux111
Did you make webxr work in Electron now? I also went into this issue.

**Comment by RangerMauve** [comment]
Haven't done much testing, but the `navigator.xr` variable is there inside BrowserWindow, but not inside `<webview>`.

**Comment by cmumme** [comment]
Looks like somebody got this working! https://bai.dev/projects/webxr-electron-apr2021

**Comment by bedney** [comment]
That article details that you have to flip the `checkout_openxr` flag to `True` in the `DEPS`. @MarshallOfSound - can we have OpenXR compiled in by default? Deploying customized versions of Electron is not going to work for us. Thanks!

**Comment by YoshikawaMasashi** [comment]
I hope this `WebXR support`.
I want to develop VR applications more easily.
@MarshallOfSound I'm also expecting OpenXR enabled compilation of Electron will be the default.
