### ISSUE TITLE
Cannot resize/maximize/restore/drag or close the window using pen on touchscreen devices

### ISSUE THREAD

**Issue by sachetsharma1** [electron/electron#21440]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  7.1.0
* **Operating System:**
  Windows 10 pro
* **Last Known Working Electron version:**
  n/a

### Expected Behavior
Window should respond to pen taps on the screen.

### Actual Behavior
Window does not respond.

### To Reproduce
Download or clone electron-quick-start project on a touchscreen laptop(surface book in my case) and try using pen to resize/maximize/restore/drag or close the window.

 #### Clone the repository
git clone https://github.com/electron/electron-quick-start
##### Go into the repository
cd electron-quick-start
##### Install dependencies
npm install
##### Run the app
npm start

### Additional Information
I tried the latest vs code which is based on electron v6 and it works properly. All other apps on the machine also responds normally to pen taps.

**Comment by kenpowers-signal** [comment]
We've received this as a bug report for Signal: https://github.com/signalapp/Signal-Desktop/issues/4318
