### ISSUE TITLE
Redistributable DLLs not covered by license files

### ISSUE THREAD

**Issue by andrew-mclachlan** [electron/electron#21456]
Hi there -

I'm trying to trace back to the origin and license of many of the re-distributable DLLs in an Electron installation, such as d3compiler_47.DLL.

Please can someone point me at the license file/link or how those files are pulled in to the electron build, so that I may trace back.

Thanks in advance,

Andrew

### Preflight Checklist
* [X ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v4.2.2
* **Operating System:**
  * Windows 10, but also macOS Mojave and Ubuntu 18.04

### Expected Behavior

A note in the LICENSE.txt or Appendix file covering the DLLs.

### Actual Behavior

I cannot find a mention of the DLLs in the LICENSE.txt or Appendix.

### To Reproduce

Create an Electron installation and try and find the source of d3dcompiler_47.dll

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v5.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by andrew-mclachlan** [comment]
Thanks. Can you tell me where in your source the license for the mentioned DLL is listed. The most recent version will do nicely. I could not find a mention of its origin or software license.
Thanks!

**Comment by andrew-mclachlan** [comment]
I think you can close this one now.
