### ISSUE TITLE
Protocols not working in windows 7

### ISSUE THREAD

**Issue by omidnikrah** [electron/electron#21458]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**  v3.0.11
* **Operating System:** Windows7

I'm trying to use custom protocols in electron in windows7 but it's not working.

**Comment by nornagon** [comment]
Unfortunately without any steps to reproduce this issue we can't debug further. Please provide a small example that reproduces the issue you're seeing, preferable using [Electron Fiddle](https://github.com/electron/fiddle).

In addition, Electron v3 is no longer supported. See https://electronjs.org/docs/tutorial/support#currently-supported-versions
