### ISSUE TITLE
Dialog In v7 windows

### ISSUE THREAD

**Issue by Puneetkumarpal** [electron/electron#21463]
save dialog or open dialog are not returning the path.

i am using windows 10 and electron v7.

this is my randerer.js code 
`
const { dialog } = require('electron').remote;
const path = require('path');

dialog.showOpenDialog({
        title: "Select a folder",
        properties: ["openDirectory"]
    }, (folderPaths) => {
        if (folderPaths === undefined) {
            console.log("No destination folder selected");
            return;
        } else {
            console.log(folderPaths);
        }
    });
`

it prints nothing.

**Comment by popod** [comment]
This is a breaking change of Electron 6.0.0. Read the doc [here](https://electronjs.org/docs/api/dialog#dialogshowopendialogbrowserwindow-options).

```
dialog.showOpenDialog({
  title: "Select a folder",
  properties: ["openDirectory"]
}).then(result => {
  console.log(result.canceled)
  console.log(result.filePaths)
}).catch(err => {
  console.log(err)
})
```

**Comment by Puneetkumarpal** [comment]
Thank you. its working now
