### ISSUE TITLE
Electron typescript definitions prevent process usage properly

### ISSUE THREAD

**Issue by bpasero** [electron/electron#21475]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.1.5
* **Operating System:**
  * macOS

### Expected Behavior
I can use `process.removeListener('exit')` in my code.

### Actual Behavior
I get a compile error.

### To Reproduce
* clone and setup https://github.com/electron/electron-quick-start-typescript
* type `process.removeListener('exit');`

**Comment by MarshallOfSound** [comment]
I'm relatively sure this is fixed in Electron 7 with our new docs parser.  Previously we were making a strange fake EventEmitter.  Now we correctly declare an extension on the NodeJS event emitter.

This isn't a thing we can backport easily to Electron 6 though.

**Comment by codebytere** [comment]
Closing in agreement with the above.
