### ISSUE TITLE
Since v6.0.0, window titles are no longer visible to macOS

### ISSUE THREAD

**Issue by AutoScreencast** [electron/electron#21479]
* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.3-->
* **Operating System:**
  * macOS Mojave
* **Last Known Working Electron version:**
  * 5.0.12

### Expected Behavior
The windows of Electron app should be accessible via their title to macOS System Events and other apps that rely on the window title for their operation (e.g. Hammerspoon)

### Actual Behavior
Since Electron v6.0.0, windows no longer show titles to macOS.

### To Reproduce
For example, in Terminal, run the following command:

```osascript -e 'tell application "System Events" to get the title of every window of every process'```

The resulting list no longer shows the window title(s) of open windows of the Electron app.

For people who use Hammerspoon (https://www.hammerspoon.org/), you can verify the same result by running...

```hs.application.find('Electron'):visibleWindows()[1]:title()```

In the Hammerspoon console; the result is an empty string.

The window titles were last accessible in Electron version 5.0.12

**Comment by bpasero** [comment]
This is https://github.com/electron/electron/pull/21462

**Comment by codebytere** [comment]
Fixed already - see @bpasero link above.
