### ISSUE TITLE
如何在electron中使用 Google文档、表格及幻灯片的Office编辑扩展程序

### ISSUE THREAD

**Issue by Tim2011** [electron/electron#21472]
我有试过将chrome安装好的插件复制到项目下，然后用
```
BrowserWindow.addExtension(path)
```
加载插件，但是没有任何效果。
或者是我用得不对，有没大佬可以请教一下？

扩展程序 ID: gbkeegbaiigmenfmjfclcdgdpimamgkj

**Comment by xland** [comment]
addExtension不能在 app 模块的 ready 事件之前调用.

path不能是crx文件的路径，把crx解压出来，path指向这个解压后的文件夹

**Comment by Tim2011** [comment]
我是指向的一个里面含有manifest.json文件的文件夹的，addExtension也是ready后面调用的
现在就是不知道 通过什么方法打开一个 office文件，window.open会直接闪白 然后跳转到初始路由，直接拖入文件是不响应的

**Comment by xland** [comment]
并不是所有的谷歌浏览器插件都可以安装在Electron中的，
有些谷歌浏览器插件会涉及到原生C/C++代码或与原生本地程序通信的机制，
比如迅雷的谷歌浏览器插件

你可以先试着装一下纯JavaScript语言撰写的谷歌浏览器插件试试

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
