### ISSUE TITLE
ipcRenderer.sendToHost can not work

### ISSUE THREAD

**Issue by yiidot** [electron/electron#21478]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.4
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  

### Expected Behavior
after ipcRenderer.sendToHost is called, ipcMain should receive message.

### Actual Behavior
after ipcRenderer.sendToHost is called, ipcMain can not receive message.

**Comment by xland** [comment]
The document said:
> ipcRenderer.sendToHost Like ipcRenderer.send but the event will be sent to the <webview> element in the host page instead of the main process.

**Comment by MarshallOfSound** [comment]
`ipcRenderer.sendToHost` is used for webviews to send messages to their parent.  The message will be received on `ipcRenderer.on`.  `ipcMain` never sees that event
