### ISSUE TITLE
Electron should provide electron.d.ts as separate module

### ISSUE THREAD

**Issue by bpasero** [electron/electron#21476]
VSCode currently keeps a copy of `electron.d.ts` in the source folder and wants to get rid of it. We now are forced to depend on the `electron` module as dev dependency, only to get the types. Would it be possible to provide a NPM package (similar to @types/electron maybe) where we could simply pull in the types and not the binary? VSCode has its own setup for pulling in Electron that is not going through the Electron NPM module.

**Comment by bpasero** [comment]
Hm, I will revisit this in VSCode, we should probably leverage the Electron binary from the module itself.

**Comment by nornagon** [comment]
Closing this as it's been a while and unclear if this is still relevant.
