### ISSUE TITLE
Alerts are not closed when remotely controlled by Selenium WebDriver

### ISSUE THREAD

**Issue by AZ567** [electron/electron#21483]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  7.1.2
* **Operating System:**
  *  Windows 10
* **Last Known Working Electron version:**
  *  never worked in my tests

### Expected Behavior
My bug is reported in this StackOverflow-Post: https://stackoverflow.com/questions/58628689/why-arent-alerts-modal-and-closed-in-my-electron-application-when-tested-with-s

When I use Selenium WebDriver, I want a modal alert in my Electron application to be closed, as soon as I accept or dismiss that alert. The application should not be interactable when the modal alert is open.

### Actual Behavior

The alert does not close, but stays open. It is also possible to trigger another alert, even though the previously not closed alert is still open and modal. Very strange. Chrome behaves as expected (-> The alerts are closed. I didn't test if the application is programmatically interactable when a modal alert is displayed though.).

### To Reproduce

The code used for creating the alert is:
elemental2.dom.DomGlobal.window.confirm("Alert text here") (this code is then transpiled to JavaScript).
Please have a look at the stackoverflow-article for the rest of the details.

### Additional Information

The application is closed source and not accessable from the outside. I therefore can't provide screenshots or a link to the application. Is this a bug in the electron-implementation of WebDriver?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
