### ISSUE TITLE
Issue when loading netflix.com and reddit.com in a browserview

### ISSUE THREAD

**Issue by EnderDev** [electron/electron#21486]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v6.1.2
* **Operating System:**
  * Windows 10 1903
* **Last Known Working Electron version:**
  * n/a

### Expected Behavior
The page should load fine without any renderer freezes.

### Actual Behavior
The renderer freezes while loading either netflix.com or reddit.com. The renderer hangs for a while, and it finally crashes after some "interaction" with the renderer.

```
Received fatal exception EXCEPTION_BREAKPOINT
Backtrace:
        uv_loadavg [0x00007FF66B6B42FB+846443]
        std::vector<v8::CpuProfileDeoptInfo,std::allocator<v8::CpuProfileDeoptInfo> >::_Xrange [0x00007FF66A3C50BF+306271]
        std::vector<v8::CpuProfileDeoptInfo,std::allocator<v8::CpuProfileDeoptInfo> >::_Xrange [0x00007FF66A3C523F+306655]
        uv_udp_get_send_queue_count [0x00007FF66A6C1F86+619926]
        uv_udp_get_send_queue_count [0x00007FF66A6F31F0+821248]
        uv_translate_sys_error [0x00007FF66D8DE966+28742]
        uv_translate_sys_error [0x00007FF66D8E11F0+39120]
        uv_udp_set_multicast_loop [0x00007FF66D945D36+198102]
        uv_udp_set_multicast_loop [0x00007FF66D94EA20+234176]
        uv_translate_sys_error [0x00007FF66D9051DE+186558]
        v8::String::Value::operator* [0x00007FF66A330791+1307473]
        v8::String::Value::operator* [0x00007FF66A331E33+1313267]
        v8::String::Value::operator* [0x00007FF66A32D968+1295656]
        v8::String::Value::operator* [0x00007FF66A2419E6+329126]
        v8::String::Value::operator* [0x00007FF66A24215E+331038]
        IsSandboxedProcess [0x00007FF66BEC2D8A+204666]
        v8::String::Value::operator* [0x00007FF66A241956+328982]
        Ordinal0 [0x00007FF669A613BF+5055]
        node::AsyncResource::CallbackScope::CallbackScope [0x00007FF66E6D31B2+4041154]
        BaseThreadInitThunk [0x00007FFF0DFA6FD4+20]
        RtlUserThreadStart [0x00007FFF0E0FB1F1+33]
```

The NPM log: https://pastebin.com/qUHJcDw1

### To Reproduce
```sh
$ git clone https://github.com/dot-browser/desktop
$ npm install
$ npm run dev
$ npm start (in seperate terminal)
```

### Screenshots
https://www.youtube.com/watch?v=snZ3wqdhEic

### Additional Information
N/A

**Comment by loc** [comment]
Hi @EnderDev. The best way to get someone to look at this quickly is to create a [minimal, complete, and verifiable example](https://stackoverflow.com/help/minimal-reproducible-example) and post that here. I would recommend using [Electron Fiddle](https://github.com/electron/fiddle), though spinning up a new repro using [electron-quick-start](https://github.com/electron/electron-quick-start) works too. Once we have that, it'll be a lot easier to dig into.

**Comment by EnderDev** [comment]
How am I supposed to reproduce this?

**Comment by loc** [comment]
Does the renderer freeze when loading netflix.com from a fiddle?

Yes: cool, that's a minimal repro, you're done.
No: figure out what's different in your application and apply the differences to the fiddle bit by bit until it breaks.

**Comment by EnderDev** [comment]
It's an issue in my application. However, how would I go about finding something like this? I've tried using the Performance tab in my renderer app's dev tools, but the whole app crashes before I can even read the results.

**Comment by loc** [comment]
Because there are a lot of issues in Electron and the maintainers have limited time, we are forced to require a basic repro that cuts down our time spent investigating. If you can produce a minimal example, we'll keep this issue open and look into it — otherwise I'll have to close it in 10 days, since there isn't proof that it's a problem with Electron and not your application. Good luck!

**Comment by EnderDev** [comment]
@loc Hello. Fixed the issue. Realized `.on` should be `.once`. I think the renderer was just updated too much causing the freezing.

Before:
```js
this.webContents.on('media-started-playing', (listener: any) => {
      appWindow.webContents.send(`audio-playing-${this.tabId}`);
});
```

After:
```js
this.webContents.once('media-started-playing', (listener: any) => {
      appWindow.webContents.send(`audio-playing-${this.tabId}`);
});
```
