### ISSUE TITLE
App Starts and Stops Immediately Without Launching Window or Error

### ISSUE THREAD

**Issue by gtkpr** [electron/electron#21503]
### Issue Details

* Electron Version: **7.1.4, 7.1.7**
* Operating System: **Windows 10 Home 1903, 1909**
* Last Known Working Electron version: **Can't remember.**
* Node Version: **12.8.1, 12.13.0, 12.14.0**
* NPM Version: **6.13.4**
* **More info can be found [here](https://stackoverflow.com/q/59316390/7543162).**

### Expected Behavior

I expect the app and its corresponding window to launch...

### Actual Behavior

No window is launched. No errors are thrown in Command Prompt. The app supposedly starts and then ends immediately. A screenshot of Command Prompt can be seen [**here**](https://stackoverflow.com/q/59316390/7543162) or at the bottom of this post.

### To Reproduce

1. _**mkdir test**_
2. _**cd test**_
3. _**npm init**_
4. _**enter, enter, enter...**_
5. _**create index.js**_
```
const { app, BrowserWindow } = require('electron')

function createWindow () {
  // Create the browser window.
  let win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true
    }
  })

  // and load the index.html of the app.
  win.loadFile('index.html')
}

app.on('ready', createWindow)
```
6. _**npm install electron --save-dev**_
7. _**edit package.json to add the start script**_
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "electron .",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "electron": "^7.1.4"
  }
}

```
8. _**create index.html**_
```
<!doctype html>
<html>
  <head></head>
  <body>
    blahblahblah
  </body>
</html>
```
9. _**npm start**_

App starts and ends immediately and basically nothing happens.

### Screenshots

![Command Prompt](https://i.stack.imgur.com/jec0j.png "Command Prompt")

### Additional Information

All of my projects that were working fine the last time I worked on them about a month ago suddenly stopped working, which is how I discovered this issue. But even new projects are not working...

**Comment by vladimiry** [comment]
Try starting the app in console with ELECTRON_ENABLE_LOGGING=true environment variable and see the console output. https://electronjs.org/docs/api/environment-variables

**Comment by gtkpr** [comment]
> Try starting the app in console with ELECTRON_ENABLE_LOGGING=true environment variable and see the console output. https://electronjs.org/docs/api/environment-variables

Ok, I just tried it, but it didn't work, although I'm not sure if I did it properly. Here's what I did:

1. Navigated to the main directory of my project via command line.
2. set ELECTRON_ENABLE_LOGGING=true
3. npm start

Same result as before. Did I not do it right?

**Comment by vladimiry** [comment]
> Same result as before. Did I not do it right?

Adding ELECTRON ENABLE LOGGING=true doesn't change the app behavior but simply increasing chances for more info gets printed to console which might help with issue debugging as the information you provided in the original post doesn't look sufficient for the issue gets a bug status.

**Comment by gtkpr** [comment]
> > Same result as before. Did I not do it right?
> 
> Adding ELECTRON ENABLE LOGGING=true doesn't change the app behavior but simply increasing chances for more info gets printed to console which might help with issue debugging as the information you provided in the original post doesn't look sufficient for the issue gets a bug status.

How is it not some sort of bug if the instructions on Electron's website don't work?

I've given pretty clear steps on how to reproduce the problem. Has anybody tried reproducing it?

**Comment by vladimiry** [comment]
> Has anybody tried reproducing it?

I have, no described issue noticed. I'd suggest trying https://github.com/electron/electron-quick-start first using 7.1.4 and then if it still doesn't work with other electron versions so it's clear that at least some electron versions work for you.

**Comment by gtkpr** [comment]
> > Has anybody tried reproducing it?
> 
> I have, no described issue noticed. I'd suggest trying https://github.com/electron/electron-quick-start first using 7.1.4 and then if it still doesn't work with other electron versions so it's clear that at least some electron versions work for you.

The issue persists for me, even with the Electron Quick Start demo, using Electron version **^7.1.5**. 

How exactly do I install older versions of Electron in order to test those?

**Comment by vladimiry** [comment]
If you are new to @electron development may be the preferred option to try things will be using https://github.com/electron/fiddle It has built-in @electron version switch.

**Comment by gtkpr** [comment]
> If you are new to @electron development may be the preferred option to try things will be using https://github.com/electron/fiddle It has built-in @electron version switch.

But would that help me troubleshoot the issues with running Electron locally?

The issue is running Electron locally. All of my Electron projects went from working fine to being broken while the files and scripts remain unchanged...

**Comment by vladimiry** [comment]
> But would that help me troubleshoot the issues with running Electron locally?

I think you could start from narrowing down the issue scope by detecting an Electron version starting from which it stopped working for you, https://github.com/electron/fiddle could be helpful here. Also, make sure it's not your system that causes the issues (try running on another computer).

**Comment by gtkpr** [comment]
> I think you could start from narrowing down the issue scope by detecting an Electron version starting from which it stopped working for you, https://github.com/electron/fiddle could be helpful here. Also, make sure it's not your system that causes the issues (try running on another computer).

Then I will try that as soon as I get enough free time to do so. Thanks for your input.

**Comment by hopejr** [comment]
I've had this problem too, on two different Windows 10 machines. Both were running 1903, and it's after I moved from Electron 4 to Electron 7. Running electron.exe directly from node_modules\electron\dist doesn't work either.

**Comment by gtkpr** [comment]
> I've had this problem too, on two different Windows 10 machines. Both were running 1903, and it's after I moved from Electron 4 to Electron 7. Running electron.exe directly from node_modules\electron\dist doesn't work either.
> 
> Edit: it even happens on a fresh project that started with Electron 7.

Are you still experiencing the problem too?

**Comment by hopejr** [comment]
I was, but managed to fix it by removing the %appdata%\electron directory. It may be a caching issue.

**Comment by hopejr** [comment]
Ok, having to delete that directory each time gets annoying. I went in and deleted files in their one-by-one until I found the offending file. It's in the extensions directory. For me, it's to do with the Vue.js dev tools extension. I know that your example project doesn't use Vue.js, but do any of your other projects use it? If so, that could be the issue (so, not actually an Electron issue). Check the extensions folder and a file called "IDMap.json". If it lists "Vue.js devtools", then there's your problem. Otherwise, I have no idea what's causing it.

**Comment by gtkpr** [comment]
> Ok, having to delete that directory each time gets annoying. I went in and deleted files in their one-by-one until I found the offending file. It's in the extensions directory. For me, it's to do with the Vue.js dev tools extension. I know that your example project doesn't use Vue.js, but do any of your other projects use it? If so, that could be the issue (so, not actually an Electron issue). Check the extensions folder and a file called "IDMap.json". If it lists "Vue.js devtools", then there's your problem. Otherwise, I have no idea what's causing it.
> This seems to be the issue I'm having:
> [SimulatedGREG/electron-vue#958](https://github.com/SimulatedGREG/electron-vue/issues/958)

I have never installed anything Vue or anything related to it, but maybe the same file exists in another dependency?

Local/Electorn?

**Comment by gtkpr** [comment]
> > But would that help me troubleshoot the issues with running Electron locally?
> 
> I think you could start from narrowing down the issue scope by detecting an Electron version starting from which it stopped working for you, https://github.com/electron/fiddle could be helpful here. Also, make sure it's not your system that causes the issues (try running on another computer).

Weird. So I just installed the Electron Fiddle. Tried launching the same version that is otherwise failing to launch, and this version works with Electron Fiddle. Might it be that something with Node or Electron was removed from Windows Environment Variables or whatever?

**Comment by gtkpr** [comment]
> > But would that help me troubleshoot the issues with running Electron locally?
> 
> I think you could start from narrowing down the issue scope by detecting an Electron version starting from which it stopped working for you, https://github.com/electron/fiddle could be helpful here. Also, make sure it's not your system that causes the issues (try running on another computer).

Weird.

Electron Fiddle is able to launch Electron, but new and old projects won't.

In addition to that, uninstalling and reinstalling does not fix the problem.

Any ideas?

**Comment by gtkpr** [comment]
@vladimiry @hopejr 

Finally figured it out. NPM's configuration key `ignore-scripts` had somehow been set to `true`... :/

**Comment by vladimiry** [comment]
> How do I close the issue?

Locate the respective button at the page bottom.

**Comment by m4heshd** [comment]
Unbelievable. No error from both main and renderer, no warnings. Async stuff just hangs. It was all because Vue devtools and it was completely random. Started working again in just a few minutes. So bizarre.

**Comment by Infinite-3D** [comment]
I'm having the same problem. I'm using the latest version of electron quick start, and `ignore-scripts` is set to false. I don't have Vue devtools, and I've never even used Vue at all. By adding console.log statements, `main.js` is run, but `app.on("ready")` is never called. No windows open and the program ends right after it starts.

**Comment by Infinite-3D** [comment]
Update: it worked when I downgraded all the way to electron 13.6.9. Shame I have to use such an old version, but it works. 
I installed it like this if it matters: `npm install electron@13.6.9 --save-dev`

**Comment by Visual-Dawg** [comment]
I had the same problem. Suddenly Electron just closed down shortly after starting, without an error or a window opening. 
Removing the local files in `%appdata%/YOUR_APP_NAME` fixed it.

**Comment by Murilobdo** [comment]
Eu estava com o mesmo problema, desinstalei o instalei o electron novamente como desenvolvimento e foi
