### ISSUE TITLE
Maximizing window on Ubuntu 18.04.3 does not respect maxWidth/maxHeight

### ISSUE THREAD

**Issue by mfigl** [electron/electron#21508]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v7.1.5
  * v6.1.6
* **Operating System:**
  * Ubuntu 18.04.3 x64
* **Last Known Working Electron version:**

### Expected Behavior
If the BrowserWindow has maxWidth or maxHeight values set, maximizing should respect those values and do not exceed size of the window over those values.

### Actual Behavior
After pushing maximize button the window is full screen size.

### To Reproduce
Run Election with app
```
const { app, BrowserWindow } = require('electron')

app.on('ready', function () {
	let win = new BrowserWindow({ width: 800, maxWidth:800, height: 600, maxHeight: 800 })
	win.on('closed', () => {
	  win = null
	})

	// Load a remote URL
	win.loadURL('https://github.com')
})
```

and push maximize button (top right corner).

### Additional Information
The issue is not reproducible on such operating systems: Ubuntu 16.04, Windows 10, MacOs Sierra.

**Comment by reduckted** [comment]
I'm seeing the same problem.

* **Electron Version:**
  * v7.1.7
* **Operating System:**
  * Ubuntu 19.04

This also occurs when you drag the window to the top, left or right of the screen. When you drag the window to the left or right of the screen, the window is "snapped" (not sure if that's the official term) to that side of the screen with full height. When you drag it to the top of the screen, the window is maximized.

Windows has a similar "snapping" feature, but the window's maximum size is respected.

Here's a screenshot of snapping the window to the right side:

![image](https://user-images.githubusercontent.com/10321525/71307015-0c363580-2434-11ea-911a-ef7990949b1b.png)

In fact, in that screenshot you can see that I also have `maximizable` set to false.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
