### ISSUE TITLE
MenuItem.label does not dynamically changed

### ISSUE THREAD

**Issue by ChinaLiuxiaosong** [electron/electron#21504]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.4
* **Operating System:**
  * Windows 10 (1909)
* **Last Known Working Electron version:**
  * 

### Expected Behavior

Works as described in the [document](https://electronjs.org/docs/api/menu-item#menuitemlabel).

> menuItem.label
A String indicating the item's visible label, this property can be dynamically changed.

### Actual Behavior

It does not dynamically changed
### To Reproduce

https://gist.github.com/9050c852b4e5318028bf77384dfd94b5

**Comment by codebytere** [comment]
This is mistaken documentation - these labels are unfortunately not dynamic. See https://github.com/electron/electron/issues/12633.
