### ISSUE TITLE
Add support for setting the TLS min version --tls-min-v1.0 

### ISSUE THREAD

**Issue by gdavidkov** [electron/electron#21511]
### Preflight Checklist
* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
After Node 12 the default min TLS version is set to 1.2. There are CLI options to change the default value:
* --tls-min-v1.0
* --tls-min-v1.1
* --tls-min-v1.3
* --tls-max-v1.0
* --tls-max-v1.1
* --tls-max-v1.3

Here more information can be found: https://nodejs.org/api/tls.html#tls_tls_default_min_version

### Proposed Solution
It would be wonderful if  Electron can add support for these CLI options.

**Comment by MarshallOfSound** [comment]
The node TSL version does not impact Chromium's network stack and I do not think we should allow (or if it's possible to allow) reducing Chromium's minimum TLS version.  This flag should already work in `NODE_OPTIONS` but it won't impact the Chromium network stack

**Comment by rathboma** [comment]
I build [Beekeeper Studio](https://github.com/beekeeper-studio/beekeeper-studio) and we're having an issue with users trying to connect to a MySQL database using TLS < v1.2. I tried setting NODE_OPTIONS before running the app, but those changes don't seem to be picked up.

Reading the docs, looks like only two options are supported for 'packaged' apps (which I assume means my production binaries?) - https://www.electronjs.org/docs/api/environment-variables#node_options

Is that right, or am I doing it wrong?

I'm running

```
$ export NODE_OPTINS="--tls-min-v1.0"
$ beekeeper-studio

```
