### ISSUE TITLE
remote.getCurrentWindow().capturePage(...) does not return image to function

### ISSUE THREAD

**Issue by wolfiex** [electron/electron#21516]
This works on older versions of electron (e.g. 3.1.4) but at some point, a change was introduced _ meaning that for the latest versions (e.g. 7.xx ) it is no longer the case. 

```
remote.getCurrentWindow().capturePage(
    function handleCapture (img) {
       console.log(img,'img')
    }
)
```

**Comment by codebytere** [comment]
As specified [in the docs](https://electronjs.org/docs/api/browser-window#wincapturepagerect), `win.capturePage` returns a Promise.

```js
remote.getCurrentWindow().capturePage().then(img => {
  console.log(img)
})
```
