### ISSUE TITLE
Electron v6 get wrong value with systemPreferences.isDarkMode()

### ISSUE THREAD

**Issue by orangeChu** [electron/electron#21532]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.1.4
* **Operating System:** 
  * macOS 10.15.2
* **Last Known Working Electron version:** 
  * 4.2.x

### Expected Behavior

`systemPreferences.isDarkMode()` returns the correct value under macOS.

### Actual Behavior

`systemPreferences.isDarkMode()`  returns the opposite value under macOS.

### To Reproduce

Have `NSRequiresAquaSystemAppearance=false` in your `Info.plist`, then test the code
```js
systemPreferences.subscribeNotification('AppleInterfaceThemeChangedNotification', () => {
    console.log('dark mode:' + systemPreferences.isDarkMode());
  }
});
```

### Screenshots

![Kapture 2019-12-16 at 11 19 16](https://user-images.githubusercontent.com/25950247/70877187-72b3f180-1ff7-11ea-8586-e23ae4bbdc22.gif)

**Comment by MarshallOfSound** [comment]
This is unfortunately expected as a result of several changes Apple made in Catalina.

Update to v7 and use `electron.nativeTheme` instead

**Comment by orangeChu** [comment]
Thank you for your reply.
But in v4, it can return the correct value without setting `NSRequiresAquaSystemAppearance` in Catalina.
