### ISSUE TITLE
Different UI of MessageBox with localized buttons

### ISSUE THREAD

**Issue by AnnaHotsa** [electron/electron#21537]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.12
* **Operating System:**
  *  Windows 10  Pro(1909) 

### Expected Behavior
Same view of MessageBox regardless of button labels.

### Actual Behavior
I'm working on localization electron app and had faced a problem with UI of localized MessageBox. The thing is that when I pass `buttons: ["Cancel", "Yes"]` property into `showMessageBoxSync` options, the dialog looks like at the 1st screenshot and the buttons are translated automatically depending on the current language of OS. However, when I pass the translated values into the `buttons` property, the view of the dialog is different, which may be confusing for the users.

### To Reproduce
Create dialog with customized button labels.
let dialog1 = dialog.showMessageBoxSync(BrowserWindow.getFocusedWindow(), {
            type: "question",
            title: "Dialog 1",
            message: "Message",
            buttons: ["Відміна", "Так"]
        });

### Screenshots
Dialog with `buttons: ["Cancel", "Yes"]` property
![image](https://user-images.githubusercontent.com/51370811/70904087-35585f80-2009-11ea-97ad-97c22ee895c4.png)

Dialog with `buttons: ["Відміна", "Так"]` property
![image](https://user-images.githubusercontent.com/51370811/70904147-4d2fe380-2009-11ea-9115-4906ca6a4035.png)

**Comment by popod** [comment]
Use the `noLink` param. See [the doc](https://electronjs.org/docs/all#dialogshowmessageboxsyncbrowserwindow-options).

**Comment by AnnaHotsa** [comment]
Hi @popod !
This helped, thank you!
