### ISSUE TITLE
乱码导致看不到key值

### ISSUE THREAD

**Issue by qq771026828** [electron/electron#21531]
![image](https://user-images.githubusercontent.com/21036501/70877181-70519780-1ff7-11ea-956f-b477a23697bc.png)
![image](https://user-images.githubusercontent.com/21036501/70877195-7b0c2c80-1ff7-11ea-8391-78f40b4e779f.png)

**Comment by qq771026828** [comment]
![image](https://user-images.githubusercontent.com/21036501/70877279-cc1c2080-1ff7-11ea-998c-087402168a33.png)
这个是其他软件的，显示没有问题

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
