### ISSUE TITLE
'mousemove' event has invisible margin in BrowserWindow

### ISSUE THREAD

**Issue by lonkaars** [electron/electron#21538]
### Preflight Checklist

* [*] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [*] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [*] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.2.12
* **Operating System:**
  * Windows 10 1909 (build 18363.535)

### Expected Behavior
mousemove event firing on the entire body, without a margin

### Actual Behavior
The mousemove event doesn't fire outside an invisible margin, see [this](https://youtu.be/2XEBVWyelqM) video.

### To Reproduce
Create an electron app on electron 4.2.x with a BrowserWindow, and add the following code to the renderer javascript:

```js
document.body.addEventListener('mousemove', (e) => {
    console.log(e.clientX, e.clientY)
})
```

### Additional Information
I haven't checked if it works on electron 5 or newer, but I have to use 4.2.x, because that's the latest electron version that doesn't run node 12. Building native modules is sort of broken on node 12 and later, and my app requires robotjs.

**Comment by loc** [comment]
I assume you're removing the default `<body>` margin with css? Can you provide a complete example (easiest way is with [Electron fiddle](https://github.com/electron/fiddle))?

**Comment by lonkaars** [comment]
[Here's](https://gist.github.com/f28858d946284e2d678c374a363747be) the fiddle,

While creating the fiddle, I noticed it only seems to happen on a frameless window, and only on the window edges. It fires the mouse events on the right edge when DevTools is open.

This might have something to do with being able to resize the window? but making the window non-resizable changes nothing so I don't know what's going on here

**Comment by miniak** [comment]
Electron 4 is not supported anymore. Even if there is a bug in Electron and it gets fixed, you won’t be able to get it fixed unless you update to a supported version.

**Comment by lonkaars** [comment]
The same bug seems to occur on electon 7.1.7 as well. I've updated my app to use electron 7, but the bug still persists.

**Comment by lonkaars** [comment]
Any updates on this?

**Comment by onikienko** [comment]
This bug occurs in 9.0.0 on Windows too :disappointed:  So Electron versions from 4 to 9.0.0 are affected. Do not know about older versions.

Each frameless window has a small invisible "dead" border (4-7px). You can't catch mouse events in this area and can't change the cursor.   

There  is a small complete example to demonstrate this bug - [Electron Frameless Window Bug](https://github.com/onikienko/electron-frameless-bug-demo)

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
