### ISSUE TITLE
IndexedDb gets corrupted on Electron 7

### ISSUE THREAD

**Issue by anteburazer** [electron/electron#21558]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.3
* **Operating System:**
  * macOS 10.15.1 / Windows 10 (1809)
* **Last Known Working Electron version:**
  * 6.1.2

### Expected Behavior
The app stores a lot of data into IndexedDb table (~50 000 - 100 000 items). After processing the items it deletes them from the DB. Accessing the table after deleting the items should be very quick.

### Actual Behavior
In the process of inserting or deleting the items, the table becomes somehow corrupted and it takes minutes to pull the data from it, although it's empty.
After tables becomes "corrupted" the repro rate of the issue is 100%. App can't start because it's accessing the table for couple of minutes and all other transactions are blocked.
If I copy the DB and use it with the same app but with Electron 6.1.2 build the problem disappears.

**Question**: Has something changed in Electron or Chromium (from v6 to v7), related to IndexedDB, which could cause this behaviour? Thank you.

### To Reproduce
I created Electron Fiddle demo but couldn't repro the bug unfortunately. The only thing I've noticed is that the exception is thrown if I'm trying to fetch over ~75 000 items from the DB, but it doesn't work with Electron 6 either so I think it's not related.
**Gist**: https://gist.github.com/anteburazer/2fd2c80b2f89b506b77a9f5e317ae7e3

**Comment by nornagon** [comment]
Unfortunately without a repro case it's not going to be possible to determine anything further about this bug. Electron doesn't interfere with IndexedDB, so this is likely due to a Chromium change between v6 and v7 (Chromium v76 and Chromium v78).

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
