### ISSUE TITLE
Electron hangs after calling app.exit() when run on GitLab CI on Windows

### ISSUE THREAD

**Issue by richardfritsch** [electron/electron#21556]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
When Electron is run on GitLab CI on Windows, calling `close()` on the main window or calling `app.exit()` makes Electron hang instead of exiting. The command executed by CI is `.\node_modules\.bin\electron main.js`, where main.js is the same as in the ["Writing Your First Electron App" tutorial](https://github.com/electron/electron/blob/v5.0.12/docs/tutorial/first-app.md#electron-development-in-a-nutshell). The loaded index.html is also taken from there except it calls `window.close()` in the script tag in `<body>`.

Calling `remote.app.exit()` or triggering main process exit from renderer by `ipcRenderer.send` leads to the same hang. None of 'closed', 'window-all-closed' or 'uncaughtException' event handlers are called on `win`, `app` or `process` respectively in the main process; `win.destroy()` has no effect either.

The hang only occurs when run by GitLab CI runner, I can't trigger it in any way when running it myself. Updating GitLab or the runner to latest stable version didn't help. 

Using `--inspect-brk` in the CI command and then attaching a "dedicated DevTools for Node" debugger didn't help as no uncaught exception is thrown. Pausing script execution by hitting F8 during the hang has no effect besides disabling the pause button.

* **Electron Version:**
  * 5.0.12
* **Operating System:**
  * Windows 10 (1909)

### Expected Behavior
Calling `app.exit()` or `app.quit()` should just work, irrespective of the environment. Closing the window either in renderer or main process should trigger the 'closed', 'window-all-closed' events in the main process. If there's a problem with any of these, an exception should be thrown and/or a message printed to stderr.

### Actual Behavior
Calling `app.exit()` or `app.quit()` causes a hang; 'closed' and 'window-all-closed' events don't fire. No uncaught exception is thrown.

### To Reproduce
* Clone and check out [electron-quick-start](https://github.com/electron/electron-quick-start), perhaps the latest 5.x commit 03c1b938
* add `window.close()` to renderer.js file
* Trigger a GitLab CI job on Windows with .gitlab-ci.yml:
   ```
   - npm ci
   - .\node_modules\.bin\electron main.js
   ```
  it will hang

### Additional Information
The reason I need the app to exit normally on CI is to run unit tests and exit with a success/fail exit code. Of course I could kill the app instead, but that's not a solution. Calling Node's `process.abort()` is the only way I found that makes it exit, but then I can't get a meaningful exit code.

Thank you for looking into this, I very much appreciate it.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
