### ISSUE TITLE
desktopCapturer.getSources memory leaks

### ISSUE THREAD

**Issue by Senasiko** [electron/electron#21555]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.1.6
* **Operating System:**
  * macOs 10.14.6

### Expected Behavior

The Resident set size of the Main process when using desktopCapturer.getSources not growing.
### Actual Behavior

Memory leak in the Main process (rss memory growing) when using the desktopCapturer.getSources method in the Rendering process.
### To Reproduce

I just run the code that same with [#19908](https://github.com/electron/electron/issues/19908) in v6.1.6 , and it's well in v4.2.10
#### log in v6.1.6
```
rss=44.941312MB, heapTotal=8.82688MB, heapUsed=4.591224MB, external=1.092509MB
rss=118.259712MB, heapTotal=6.20544MB, heapUsed=4.078576MB, external=1.032391MB
rss=128.548864MB, heapTotal=6.47168MB, heapUsed=4.555952MB, external=1.032391MB
rss=138.698752MB, heapTotal=6.47168MB, heapUsed=4.76792MB, external=1.032391MB
rss=158.441472MB, heapTotal=6.47168MB, heapUsed=4.97628MB, external=1.032391MB
rss=169.381888MB, heapTotal=7.258112MB, heapUsed=5.267584MB, external=1.032391MB
rss=189.546496MB, heapTotal=7.258112MB, heapUsed=5.69024MB, external=1.032391MB
rss=199.540736MB, heapTotal=7.7824MB, heapUsed=5.799064MB, external=1.032391MB
rss=219.68896MB, heapTotal=7.7824MB, heapUsed=6.22848MB, external=1.032391MB
```
#### log in v4.2.10
```
rss=45.207552MB, heapTotal=12.324864MB, heapUsed=6.852656MB, external=0.161429MB
rss=150.91712MB, heapTotal=12.849152MB, heapUsed=6.633424MB, external=1.22608MB
rss=150.892544MB, heapTotal=12.849152MB, heapUsed=6.641872MB, external=1.22608MB
rss=150.859776MB, heapTotal=12.849152MB, heapUsed=6.64536MB, external=1.22608MB
```
> main.js
```js
const {
    app,
    BrowserWindow
} = require('electron');
const url = require('url');
const path = require('path');

let win;

const logBytes = x => `${x[0]}=${x[1] / (1000.0 * 1000)}MB`;

const logMemory = () => {
    console.log(
        Object.entries(process.memoryUsage())
        .map(logBytes)
        .join(', ')
    );
};

const createWindow = () => {
    win = new BrowserWindow();
    win.loadURL(url.format({
        pathname: path.join(__dirname, 'index.html'),
        protocol: 'file:',
        slashes: true
    }));
};

try {
    app.on('ready', createWindow);
} catch (e) {
    console.err(e);
}

logMemory();
setInterval(logMemory, 10000);
```
> index.html
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
  </head>
  <body>
    <h1>Hello World!</h1>
    We are using Node.js <span id="node-version"></span>,
    Chromium <span id="chrome-version"></span>,
    and Electron <span id="electron-version"></span>.

    <!-- You can also require other files to run in this process -->
    <script src="./renderer.js"></script>
  </body>
```
> renderer.js
```js
const electron = require('electron');
const desktopCapturer = electron.desktopCapturer;

const getSourcesLoop = () => {
    console.log('getSources() call');
    desktopCapturer.getSources({
        types: ['screen', 'window']
    }).then(sources => {
        console.log('getSources() success', sources);
        setTimeout(getSourcesLoop, 5000);
    });
};
getSourcesLoop();
```

**Comment by AtriLahiji** [comment]
Just to add to this, I noticed the exact same issue in 6.1.5. Not sure if there is a 6.x version that does not contain this issue.

**Comment by maxfurgala** [comment]
i have exactly the same problem for Windows.
In v.7.x.x this issue still actual

**Comment by AtriLahiji** [comment]
@maxfurgala I could not replicate on 7.1.2 so this is either an issue that appeared again in later 7.x.x releases or the issue you are encountering may have a different cause.

**Comment by maxfurgala** [comment]
> @maxfurgala I could not replicate on 7.1.2 so this is either an issue that appeared again in later 7.x.x releases or the issue you are encountering may have a different cause.
@AtriLahiji Thank you very much. it helped me alot :+1:

**Comment by KyzaGitHub** [comment]
The problem persists in Electron 8.1.0 on Windows 10 as well.

**Comment by KASOGIT** [comment]
Same for me, calling desktopCapturer multiples times using electron >= 8.0.0 lead to crash. Any updates on this ?

**Comment by KASOGIT** [comment]
@Senasiko Could you update the issue title to follow the current electron version, cause the leak is still present ? It'll maybe get more attention.

**Comment by Senasiko** [comment]
> @Senasiko Could you update the issue title to follow the current electron version, cause the leak is still present ? It'll maybe get more attention.

Sorry, because the issue has `6-1-x` label and my log is in v6.1.6，so I think that I can not change the issue title. Maybe you can create a new issue with version that you use.

**Comment by denys-potomkin** [comment]
still reproducing in v11.0.2, windows 10

**Comment by gkarmas** [comment]
Same issue in v11.1
