### ISSUE TITLE
Electron 7: wrong type for preloadURL vs preload

### ISSUE THREAD

**Issue by bpasero** [electron/electron#21553]
The documentation of `preload` reads: `This option will appear as preloadURL (not preload) in the webPreferences specified to the will-attach-webview event.`

However the type is not present anywhere in `electron.d.ts`

//cc @MarshallOfSound

**Comment by nornagon** [comment]
This is a bit awkward because even though it's technically allowable to specify a `file://` URL to WebPreferences anywhere via `preloadURL`, it's a bit useless to do so, since `preload` is right there and loads a path. #33228 to solve this a different way.
