### ISSUE TITLE
Refused to load the script

### ISSUE THREAD

**Issue by kns-devel** [electron/electron#21551]
Refused to load the script 'https://www.gstatic.com/firebasejs/7.6.0/firebase-app.js' because it violates the following Content Security Policy directive: "script-src 'self' ".

index.html:1 Refused to load the script 'https://www.gstatic.com/firebasejs/7.6.0/firebase-analytics.js' because it violates the following Content Security Policy directive: "script-src 'self' ".

index.html:1 Refused to load the script 'https://www.gstatic.com/firebasejs/7.6.0/firebase.js' because it violates the following Content Security Policy directive: "script-src 'self' ".

index.html:1 Refused to load the script 'https://www.gstatic.com/firebasejs/7.6.0/firebase-auth.js' because it violates the following Content Security Policy directive: "script-src 'self' ".

index.html:1 Refused to load the script 'https://www.gstatic.com/firebasejs/7.6.0/firebase-firestore.js' because it violates the following Content Security Policy directive: "script-src 'self' ".

**Comment by kns-devel** [comment]
What I must be a config file?

**Comment by gui-gu-zi** [comment]
I'd like to ask, how did you solve this problem?
