### ISSUE TITLE
SimpleURLLoaderWrapper broken with redirects in > 7.1.2

### ISSUE THREAD

**Issue by burtonator** [electron/electron#21566]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
 v7.1.4
* **Operating System:**
 Ubuntu + MacOS
* **Last Known Working Electron version:**
 7.1.2

### Expected Behavior

electron and electron-updater should follow redirect URLs

### Actual Behavior

electron-updater / electron-builder breaks with Electron > 7.1.2 

```
Redirect was cancelled at SimpleURLLoaderWrapper. (electron/js2c/browser_init.js:2561:23) at SimpleURLLoaderWrapper.emit (events.js:203:13)
```

This NUKED my app update system and I think it's a really critical bug that needs to be fixed.

### To Reproduce

I don't have an easy way to reproduce.

You could TRY to fetch this URL:

```
https://github.com/burtonator/polar-bookshelf/releases/download/v1.80.3/Polar-Bookshelf-1.80.3-mac.zip
```

which is what the auto-updater is fetching and then breaks on.

PS ... Electron rocks!  Except for this issue of course.

**Comment by sentialx** [comment]
Yeah, I probably lost most of my app users, because I didn't notice this bug before...

**Comment by nornagon** [comment]
Yikes, that seems bad! It looks like that error is related to the redirect mode "manual". Do you have any snippets of code that set the redirect mode to manual and/or register `'redirect'` handlers? That might helpful in tracking down what's going wrong here.

**Comment by nornagon** [comment]
Looks like this is where electron-updater sets `redirect` to `"manual"`: https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/electronHttpExecutor.ts#L27

**Comment by nornagon** [comment]
cc @develar @vladimiry who work on electron-updater

**Comment by vladimiry** [comment]
@nornagon thanks for pinging, but I don't work on `electron-updater` and don't use it anymore.

**Comment by burtonator** [comment]
> Looks like this is where electron-updater sets `redirect` to `"manual"`: https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/electronHttpExecutor.ts#L27

ouch.. sure enough.  What's frustrating is that with Github all the URLs are manual so I don't even of if there's a workaround for this.

**Comment by nornagon** [comment]
Yeah... this seems like a bug in electron-updater if it doesn't always call `request.followRedirect()` when the redirect mode is set to "manual" and it wants to follow a redirect. However, looking at the code for the previous version of the network service pre-7.1.3, it seems like the behavior would have been the same, so maybe something else is going on?

Unfortunately it's hard to say without more info from the electron-updater side of things :/

**Comment by lyswhut** [comment]
Get this error when electron> 7.1.2
electron-update stopped working: https://github.com/electron-userland/electron-builder/issues/4505

**Comment by burtonator** [comment]
@lyswhut I'm narrowing it down to it being a bug / conflict with > 7.1.2 too.  I'm reverting to 7.1.2 now to hopefully fix this.

**Comment by lutzroeder** [comment]
@nornagon Doesn't look like anyone is actively working on `electron-updater` but lots of apps are using it and your change 0476eb67 broke update for those apps. Would be great if you can help investigating and revert your change until this bug is understood and fixed?

**Comment by lutzroeder** [comment]
@nornagon The code is in https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/electronHttpExecutor.ts. `createRequest` is called with `redirect: "manual"`. The handler is added in `addRedirectHandlers`, calls `request.abort()` and starts another download.

```
  addRedirectHandlers(request, options, reject, redirectCount, handler) {
    request.on("redirect", (statusCode, method, redirectUrl) => {

      // no way to modify request options, abort old and make a new one
      // https://github.com/electron/electron/issues/11505
      request.abort();

      if (redirectCount > this.maxRedirects) {
        reject(this.createMaxRedirectError());
      } else {
        handler(_builderUtilRuntime().HttpExecutor.prepareRedirectUrlOptions(redirectUrl, options));
      }
    });
  }
```

```
Error: Error: Redirect was cancelled
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2561:23)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
(node:59127) UnhandledPromiseRejectionWarning: Error: Redirect was cancelled
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2561:23)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
(node:59127) UnhandledPromiseRejectionWarning: Error: Redirect was cancelled
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2561:23)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
(node:59127) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:59127) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:59127) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:59127) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by nornagon** [comment]
Electron v7.1.8 should have the fix to this issue.

**Comment by agata** [comment]
I've checked it on macOS, Windows and Linux. It works fine.

- Electron v7.1.8
- electron-builder v22.2.0
- electron-updator v4.2.0

**Comment by CatalanCabbage** [comment]
![image](https://user-images.githubusercontent.com/45961072/82247083-701d4580-9963-11ea-8ac4-6b24a725e55b.png)

I'm getting a similar error after I check for updates with electron-updater and there's an update; I'm on Electron-updater 4.3.1 and Electron 7.1.11. ☹️ 
This is the project if it helps: https://gitlab.com/cataxcab/the-wall
Any ideas?

**Comment by lukehaas** [comment]
@CatalanCabbage did you find a solution for this?

**Comment by paulojrab321** [comment]
Vou olhar!

Em seg, 2 de ago de 2021 06:33, Luke Haas ***@***.***>
escreveu:

**Comment by CatalanCabbage** [comment]
@lukehaas, yes!  
Take a look at this issue, it has a commit reference too. :)  
https://github.com/electron-userland/electron-builder/issues/4987#issuecomment-647039914

**Comment by CatalanCabbage** [comment]
@lukehaas did it work?

**Comment by lukehaas** [comment]
@CatalanCabbage I haven't tried it. It's not clear to me how that solution solves that problem and I'm concerned about it creating new problems.
