### ISSUE TITLE
append iframe element endlessly  when the webcontents debugger is attached

### ISSUE THREAD

**Issue by guox191** [electron/electron#21578]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.6
* **Operating System:**
  * macos
* **Last Known Working Electron version:**
  * none

Create an iframe element and append it into one webview's document, if the webview's webcontents debugger was attached, there will be lots of iframe created and appended into the document until the debugger be detached.

### Expected Behavior

Only one iframe element was appended into the document.

### Actual Behavior

Iframe was appended endlessly until the debugger be detached.

### To Reproduce

1. attach any webcontents' debugger.(mainframe or subframe, such as a webview).
```
const webview = document.createElement('webview');
webview.src = 'about:blank';
document.body.append(webview);
webview.addEventListener('did-finish-load', () => {
  const webContent = webview.getWebContents();
  webContent.debugger.attach();
});
```
2. create and append a new iframe element.
```
const element = document.createElement('iframe');
element.src = 'about:blank';
document.body.append(element)
```

3. Many iframe was created and endlessly, if we detach the debugge, these will be stoped.

### Screenshots

![image](https://user-images.githubusercontent.com/9742995/71160222-1e707200-2282-11ea-9ef5-a34409684bb9.png)

**Comment by azproduction** [comment]
I can confirm that this problem still exists in 8.x and 9.x . 
@sofianguy I prepared a minimal reproduction case which could help you investigate this problem. 
[electron-fails-to-create-iframe-using-debugger.zip](https://github.com/electron/electron/files/4609858/electron-fails-to-create-iframe-using-debugger.zip)

How this issue can be helped from out of electron team side?

I also noticed that if function creator of iframe is wrapped into setTimeout it works and creates only one iframe.

@guox191 did you manage to find a workaround?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
