### ISSUE TITLE
Some tray mouse click handlers not processed and tray menu displayed at the same time

### ISSUE THREAD

**Issue by vladimiry** [electron/electron#21576]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 8.0.0-beta.5
* **Operating System:** Linux (so far the issue detected only on Ubuntu, tested on version 19.10, Gnome Shell)
* **Last Known Working Electron version:** unclear since primary/left tray mouse click processing stopped working since something like version 3, see https://github.com/electron/electron/issues/14941

### Expected Behavior
- App window visibility gets toggled by the **every** primary/left mouse click on the tray icon.
- No tray menu displayed if the primary/left mouse clicked on the tray icon.

### Actual Behavior
- **Some** primary/left mouse clicks are not processed, especially the first 1-3 clicks.
- Tray menu displayed along with the primary/left mouse click processing. So both primary/left and secondary/right mouse click actions are being processed.

### To Reproduce
https://github.com/vladimiry-playground/electron-quick-start-tray-issue-menu-gnome

### Screenshots

<details><summary>Click to uncollapse the animated image</summary>

![demo](https://user-images.githubusercontent.com/1560781/71147833-0d504280-223b-11ea-98f8-5835140220cc.gif)

</details>

### Additional Information

Doesn't matter whether `libappindicator3-1` is installed or not.

Possibly related issue:
- https://github.com/electron/electron/issues/21445
- https://github.com/electron/electron/issues/21445
- https://github.com/electron/electron/issues/14941

**Comment by vladimiry** [comment]
Just tried the recent v8.0.0-beta.9 release and the problem is still there. Some tray clicks not being processed, they just skipped. Very annoying issue introduced in v8-betas. @ckerr any chance issue gets resolved in final v8 release?

**Comment by Bobo1239** [comment]
Hm, I believe this may actually be a GNOME issue. Looking at the output of `dbus-monitor` shows that only a double-click on the tray icon (which also briefly shows the menu) will send a `org.kde.StatusNotifierItem.Activate` method call to the application. Single clicks only cause a query of the menu items via the `com.canonical.dbusmenu` interface.

To test this you can manually send the method call with `dbus-send --dest=:1.414 --type=method_call /StatusNotifierItem org.kde.StatusNotifierItem.Activate`  (replace `dest` with your one from `dbus-monitor`). The window visibility then switches immediately as one would expect.

I've also tested your test application in [sway](https://github.com/swaywm/sway) and it works without issues. So the remaining question is whether this is a bug in GNOME or intended behavior...

**Comment by vladimiry** [comment]
> I believe this may actually be a GNOME issue

I agree that it appears to be the Gnome issue since I've tested the case on KDE and Xfce and there is no such issue. The thing is that many user use Gnome-based systems, like Ubuntu and upgrading the Electron v8 will break the UX of users interacting with tray icon.

**Comment by Bobo1239** [comment]
Digged a bit deeper and am pretty sure now that this is unfortunately the intended behavior from GNOME's side. Tray icons in GNOME are nowadays (AFAIKT) actually implemented by the [appindicator shell extension ](https://github.com/ubuntu/gnome-shell-extension-appindicator) which states in its README:

> - Reveal indicator menus upon click.
> - Double clicking an icon will activate the application window (if implemented by the indicator).

This was also confirmed by the author in https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/25. (way back in 2013)

Not sure how this should be handled by electron...

btw: As a sway user myself, electron 8 is ironically enabling me to finally click tray icons at all now.

**Comment by vladimiry** [comment]
> btw: As a sway user myself, electron 8 is ironically enabling me to finally click tray icons at all now.

In general, I tend to think the tray icon clicks handling support on Linux got improved in Electron v8 (the change seems to be coming with Chromium update, see https://github.com/electron/electron/issues/21445#issuecomment-564488600) since now the right and left clicks are treated as a separate actions (see #14941). I like how it works now if Xfce DE is used. But unfortunately, the change affects the Ubuntu/Gnome users in a bad way.

**Comment by vladimiry** [comment]
To whom it may concern. It turned out Electron is getting rid of DBus related tray icon implementation rolled out with @chromium update in Electron v8 in favor of previously used / `GTK/appindicator` approach, see electron/electron#23674.

**Comment by vladimiry** [comment]
Going to test #23674 soon and close the issue then as resolved.

**Comment by vladimiry** [comment]
Closing the issue since it doesn't make sense anymore since 9.0.3 because of #23674. So tray `click` even stopped to be processed on Linux since 9.0.3. See the respective / long-standing #14941 issue.
