### ISSUE TITLE
Error: net::ERR_INVALID_ARGUMENT electron7.1.5

### ISSUE THREAD

**Issue by zacard-orc** [electron/electron#21577]
### Preflight Checklist
None

### Issue Details
Electron: 7.1.5
Operating System: win10 x64
Last Known Working Electron version: ^6.X.X

### Expected Behavior
Running No Error

### Actual Behavior
when I run on electron 7+，the logs tell me below:
2019-12-19 13:21:32:873 [error] Error: Error: net::ERR_INVALID_ARGUMENT
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2536:21)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:476:20)
    at SimpleURLLoaderWrapper.topLevelDomainCallback (domain.js:131:23)
Though it dosen't matter with running normally , I also want to find out the reason.
And I can't find where is the browser_init.js

Thx~

**Comment by codebytere** [comment]
@zacard-orc with just the imformation you've provided us, it's not possible for us to know what you're running in order for this error to occur. Please attach a repro so we can effectively triage this.

**Comment by VerteDinde** [comment]
Hey @zacard-orc, I was having similar issues. If you're using electron-fetch, try updating your version of Electron to 7.1.7 and your version of electron-fetch to latest (1.4.0). There were multiple changes to the net module in Electron 7.1.x that electron-fetch addresses in 1.4.0 - without knowing more about your issue, this may help. Let me know if this doesn't work.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
