### ISSUE TITLE
setPosition Bug

### ISSUE THREAD

**Issue by spcBackToLife** [electron/electron#21588]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
Electron Version: 6.0.9
Operating System: macOS Mojave 版本：10.14.6

### Expected Behavior
I want to set Position to max width of window in order to hide the browserWindow, for Example,
```code
win.setPosition(1680,  0, true );
```
i expect it equals 1680 when I getPosition().x

### Actual Behavior
i got `getPosition().x` doesn't equal 1680

### To Reproduce
here is the demo: "git@github.com:spcBackToLife/electron-sprout.git#feature/doc-tool-demo"
you just need to :
  ```code
     yarn install
     yarn dev
  ```
code file is : "src/main-process/main-window.ts"

you "CommandOrControl+Left", the window will come out from right , and "CommandOrControl+Right" will hide the window, but it always can't be the right positon x of 1680

**Comment by codebytere** [comment]
This specific number, 1680, is the cause of the issues you're experiencing. For example, on my device, i have a resolution of `1680 x 1050`, as confirmed here:

<img width="669" alt="Screen Shot 2019-12-19 at 7 48 12 PM" src="https://user-images.githubusercontent.com/2036040/71229026-f7716a80-2298-11ea-98ab-f7f58f4674fb.png">

If i call `win.setPosition(0,  0, true)`, followed by `win.getPosition()`, i see `[ 0, 23 ]` in console. `23` might seem like a bug, but it is in fact not. `0` would place it over the top tray:

<img width="695" alt="Screen Shot 2019-12-19 at 7 53 54 PM" src="https://user-images.githubusercontent.com/2036040/71229160-677ff080-2299-11ea-9330-c84933d38746.png">

which is disallowed by the macOS operating system, and which is precisely 23 pixels high. The same applies to the width; if i set it anywhere from `0` to `1680`, `win.getPosition()` returns the correct x-axis position. Any greater or less, and it will not be properly handled (this is a Chromium-level design decision, not one handled by Electron). 

You should instead look to handle window hiding with the APIs we have intentionally crafted for that purpose, like `win.hide()`.

**Comment by spcBackToLife** [comment]
Thanks for your help~ @codebytere
