### ISSUE TITLE
[RTL][Mac] Window buttons do not respect system default

### ISSUE THREAD

**Issue by seshrs** [electron/electron#21583]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * Electron 9.0.0-nightly.20191217
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron version:**
  * _Uncertain_

### Expected Behavior

On a Mac with primary language set to an RTL language (say, Arabic), the window buttons (the "traffic lights") _should_ appear on the right side of the window.

### Actual Behavior

It seems that Electron-based apps still show the window buttons on the left, just like in LTR languages like English.

See below for a screenshot indicating the issue.

### To Reproduce

1. Change the MacOS system language to Arabic. (https://support.apple.com/guide/mac-help/change-the-language-your-mac-uses-mh26684/mac)
2. Restart your computer. (Notice how native windows now have window buttons on the right side.)
3. Open an Electron app. The window buttons appear on the left side.

### Screenshots

Here is a screenshot of my Mac in Arabic (with a native window open for reference), along with a test build of the Electron app. Notice that the position of the window buttons is different.

![image](https://user-images.githubusercontent.com/12139762/71199876-c61e7d80-224b-11ea-94f4-658088a611dd.png)

### Additional Information

I was also able to reproduce this issue on various Electron-based apps including VS Code, Skype, WhatsApp, Slack.

**Comment by TonyWuu** [comment]
cc @zcbenz @MarshallOfSound 
@seshrs and I are trying to figure this out at the moment, but not sure what's wrong. Any pointers or hints as to where this might be broken and what might be causing it?

**Comment by MarshallOfSound** [comment]
https://chromium-review.googlesource.com/c/chromium/src/+/562603/10/chrome/browser/ui/cocoa/tabbed_browser_window.mm#82

☝️
