### ISSUE TITLE
Lighthouse Audit not working in electron 7.1.2

### ISSUE THREAD

**Issue by Mqleaf** [electron/electron#21594]
### Preflight Checklist
* [x]  I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x]  I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x]  I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.2
* **Operating System:**
  * macOS 10.13.4
* **Last Known Working Electron version:**
  * not sure, but there is a similar issue for 2.x version, https://github.com/electron/electron/issues/13382#issue-334824134 

### Expected Behavior

lighthouse can work

### Actual Behavior

lighthouse cann't work

### To Reproduce

- webview show a webpage:
```
<webview id="browser" src="https://www.iconfont.cn/" nodeintegration nodeintegrationinsubframes enableremotemodule="true" disablewebsecurity></webview>
```
- set the devtools of the webview to a browserview
```
// app.js

let view;

function main() {
    browserView = document.getElementById("browser");
    createView();
    browserView.addEventListener("dom-ready", () => {
        browser = browserView.getWebContents();
        setDevtools(browser);
    });
}

function createView() {
    const win = electron.remote.getCurrentWindow();
    view = new BrowserView({
        webPreferences: {
            webviewTag: true,
            nodeIntegration: true,
            preload: './webview-pre.js'
        }
    });
    win.setBrowserView(view);
    view.setBounds({ x: 10, y: 750, width: 1200, height: 550 })
    view.on('closed', () => { view = null; });
    view.webContents.on('dom-ready', () => { devtoolsReady();})
}

function setDevtools(browser) {
    browser.setDevToolsWebContents(view.webContents);
    browser.openDevTools({mode: 'right'});
}

function devtoolsReady() {
    view.webContents.openDevTools({mode: 'detach'}); // open the devtools of the devtools
}
```
- click the audit btn, and it is not working...
![image](https://user-images.githubusercontent.com/22488004/71305231-78507380-240b-11ea-9197-3596d786f14e.png)

- can see the error: "AuditsService is not defined"
![image](https://user-images.githubusercontent.com/22488004/71305127-117e8a80-240a-11ea-96a0-16e15111dc6e.png)

**Comment by Mqleaf** [comment]
As it might be the issue of chromium, I verified the chromium behavior.
For electron 7.1.2, the chromium version is 78.0.3904.113. But I just found 78.0.3904.108 (https://sourceforge.net/projects/osxportableapps/files/Chromium/).

Chromium 78.0.3904.108 works for lighthouse audit:
![image](https://user-images.githubusercontent.com/22488004/71306150-e7cc6000-2417-11ea-99ae-f0f74ff45e12.png)

I think maybe the chromium is ok, I am not sure for the version 78.0.3904.113.

**Comment by Mqleaf** [comment]
electron 6.1.4 has the same bug, also with error "AuditsService is not defined". The close chromium version 76.0.3809.132 still works.

**Comment by praneetrohida** [comment]
Still an issue in v10.1.3

**Comment by wangliax** [comment]
Any update, Thanks

**Comment by ShyneTurtle** [comment]
now it says "Can only audit HTTP/HTTPS pages and Chrome extensions. Navigate to a different page to start an audit."

**Comment by nornagon** [comment]
Lighthouse works in 12.x+. It doesn't work on file:// pages, either in Electron or Chromium, which is beyond our scope to fix.
