### ISSUE TITLE
Crash when going to http://google.com with any `webRequest` listener

### ISSUE THREAD

**Issue by sentialx** [electron/electron#21597]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.0-beta.5
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 8.0.0-beta,4

### Expected Behavior
http://google.com should load without any crash

### Actual Behavior
Going to http://google.com works for the first time. However, when going to the same URL after the cache has been saved in `userData`, it crashes with `3221225477` exit code. The strange thing is that when going to https://google.com, it works perfectly.

### To Reproduce
(I couldn't use Fiddle, since it saves the `userData` temporarily)
https://github.com/sentialx/electron-quick-start/tree/google-crash
Branch `google-crash`

**Comment by sentialx** [comment]
It seems that it also crashes on http://detectadblock.com.

**Comment by zcbenz** [comment]
Can you share more about how to reproduce the crash? I have tried with following steps but could not reproduce:
1. Open the app, click random links
2. Close the app
3. Reopen the app

**Comment by sentialx** [comment]
@zcbenz Ah sorry. I forgot to replace the line
```
mainWindow.loadURL('https://google.com');
```
with
```
mainWindow.loadURL('http://google.com');
```

**Comment by zcbenz** [comment]
I can reproduce this on Windows but not macOS. This seems to be a Windows-only bug.
