### ISSUE TITLE
youtube.com not loading on 8.0.0-beta.5

### ISSUE THREAD

**Issue by sentialx** [electron/electron#21596]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.0-beta.5
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 8.0.0-beta.4

### Expected Behavior
https://youtube.com should load.

### Actual Behavior
https://youtube.com is not loading.

### To Reproduce
https://gist.github.com/e9ea437d3562b951a6619540aaf3da15

### Screenshots
![image](https://user-images.githubusercontent.com/11065386/71311012-519a3900-241b-11ea-90b5-2eb959bc74ea.png)

### Additional information

This may be related to #21242

**Comment by nornagon** [comment]
Bisected on master, the issue was introduced on master within in this range: https://github.com/electron/electron/compare/113b47d871bf97cb901ed5eef5074959c2eef14b...7161b2f57c8a0da87d8e2d54f240c16f5b2afe4b

**Comment by nornagon** [comment]
looks like `--enable-features="WebComponentsV0Enabled"` fixes the issue as a workaround. I suspect that in Chrome, youtube has this enabled as an origin trial or similar, which Electron does not support.

**Comment by nornagon** [comment]
Specifying `enableBlinkFeatures: 'ShadowDOMV0,CustomElementsV0,HTMLImports'` in the WebPreferences also works around the issue.
