### ISSUE TITLE
Support the ability to override the app.getVersion() via environment variable.

### ISSUE THREAD

**Issue by burtonator** [electron/electron#21593]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

There was recently a bad regression in electron and electron-builder which is breaking auto-updates.

https://github.com/electron-userland/electron-builder/issues/4550
https://github.com/electron/electron/issues/21566

I'm trying to mitigate this moving forward by testing the codes self-update mechanism moving forward.

I'd like the ability to do:

```
export APP_VERSION=1.0.0
```

to have electron report a different ```app.getVersion()```

this would force electron-builder to upgrade itself from N to N to exercise its own update code.

### Proposed Solution

Just add a test for process.env.APP_VERSION in app.getVersion()

If there's no objection I might send a PR for this

**Comment by MarshallOfSound** [comment]
This isn't something that should be supported in electron, I can easily see people setting this on their system and breaking _every_ electron app in one go because they would all read the environment variable.

If you want your app to be able to do this, implementing it in your app is relatively straight forward.

```js
if (process.env.MY_APP_VERSION_OVERRIDE) {
  app.setVersion(process.env.MY_APP_VERSION_OVERRIDE)
}
```

**Comment by MarshallOfSound** [comment]
Also worth noting on macOS that environment variables aren't even read in from your shell when you launch a GUI app.
