### ISSUE TITLE
maximizable = false is ignored on Linux

### ISSUE THREAD

**Issue by reduckted** [electron/electron#21595]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.7
* **Operating System:**
  * Ubuntu 19.04 x64
* **Last Known Working Electron version:**
  * ?

### Expected Behavior
Setting `maximizable` to false when creating a `BrowserWindow` should prevent the window from being maximized.

### Actual Behavior
The window can be maximized.

### To Reproduce
Using the `electron-quick-start` repository, add `maximizable: false` to the options when creating the `BrowserWindow`.

Fiddle: https://gist.github.com/reduckted/009f336d9cc181e3acb1e39df4c845d4

### Screenshots
![image](https://user-images.githubusercontent.com/10321525/71307151-ef9afd00-2435-11ea-9e5d-f54c964db949.png)

### Additional Information
Could be related to #21508

**Comment by OriginalEXE** [comment]
Hi, it mentions in the docs that it is not implemented for Linux:
> maximizable Boolean (optional) - Whether window is maximizable. This is not implemented on Linux. Default is true

**Comment by reduckted** [comment]
🤦‍♂ D'oh! I just assumed it would be supported on all platforms.

I've created #21631 as a feature request for this.
