### ISSUE TITLE
MacOS 'Traffic Lights' displaying on Fullscreen

### ISSUE THREAD

**Issue by Vidsify** [electron/electron#21604]
I’m building a desktop app using React and Electron. I wanting to show the Mac Control Buttons (‘Traffic Lights’) at the top left when the application is made full screen.

I have tried setting fullscreenWindowTitle: true in my start.js file and have played around with frame & titleBarStyle but nothing seems to be allowing me to show the control buttons.

Any help would be much appreciated

**Comment by Alecyrus** [comment]
you can implement the traffic lights on your own.

**Comment by Alecyrus** [comment]
you can implement the traffic lights on your own.

**Comment by Vidsify** [comment]
> you can implement the traffic lights on your own.

How would I do that?

**Comment by Alecyrus** [comment]
Try [this](https://github.com/kapetan/titlebar)
