### ISSUE TITLE
crashReporter.getLastCrashReport always throw error

### ISSUE THREAD

**Issue by Leaking** [electron/electron#21619]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

```
crashReporter.getLastCrashReport()
```
it always throw this error

```
 'Error processing argument at index 0, conversion failure from undefined'
```

* **Electron Version:**
  * 7.1.2
* **Operating System:**
  * Windows 10 (10.0.17134)

**Comment by codebytere** [comment]
@Leaking this happens if no `crashesDirectory` has been set, which requires initializing the `crashReporter`:

No Crash:
```js
const { crashReporter } = require('electron')

crashReporter.start({
  productName: 'YourName',
  companyName: 'YourCompany',
  submitURL: 'https://your-domain.com/url-to-submit',
  uploadToServer: false
})

crashReporter.getLastCrashReport()
```

Crash:
```js
const { crashReporter } = require('electron')

crashReporter.getLastCrashReport()
```
