### ISSUE TITLE
Crash when opening an external link after calling app.removeAllListeners()

### ISSUE THREAD

**Issue by rhysd** [electron/electron#21616]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v7.1.7
* **Operating System:**
  * macOS 10.14
* **Last Known Working Electron version:**
  * v6.1.7

### Expected Behavior

Electron can open an external link successfully with browser window

### Actual Behavior

Process crashes. Below is a dump when I tried `ELECTRON_ENABLE_LOGGING=true ELECTRON_ENABLE_STACK_DUMPING=true ./node_modules/.bin/electron .`:

```
Received signal 11 SEGV_MAPERR 000000000058
 [0x0001155eca59]
 [0x000115545163]
 [0x0001155ec971]
 [0x7fffa43d5b3a]
 [0x0001155a31ff]
 [0x000113311ac9]
 [0x00011345acb9]
 [0x0001158af7d9]
 [0x0001158b46de]
 [0x0001158b3f64]
 [0x0001158ac943]
 [0x0001158ad1ba]
 [0x0001158c358e]
 [0x0001155985b2]
 [0x0001155a8544]
 [0x0001155a8a17]
 [0x000115605053]
 [0x000115540bfa]
 [0x0001156049bf]
 [0x7fff8e9e16d1]
 [0x7fff8e9c25cd]
 [0x7fff8e9c1ac6]
 [0x7fff8e9c14c4]
 [0x7fff8df21ebc]
 [0x7fff8df21cf1]
 [0x7fff8df21b26]
 [0x7fff8c4b6a54]
 [0x7fff8cc327ee]
 [0x7fff8c4ab3db]
 [0x00011560585c]
 [0x000115604388]
 [0x0001155a8ef8]
 [0x00011557cf77]
 [0x000114d82bb3]
 [0x000114d84112]
 [0x000114d7fe66]
 [0x000114c3e372]
 [0x000114c3df8e]
 [0x000116d53339]
 [0x000113de7654]
 [0x000113237154]
 [0x00010caba9e0]
 [0x7fffa41c6235]
 [0x000000000002]
[end of stack trace]
```

### To Reproduce

Run following code on main process:

```javascript
const { app, BrowserWindow } = require('electron');

async function go() {
    await app.whenReady();
    app.removeAllListeners();

    const win = new BrowserWindow();
    win.loadURL('https://example.com');
}

go().catch(console.error);
```

It does not crash when commenting out `app.removeAllListeners()`. And I also confirmed this does not occur with Electron v6.

### Screenshots

Crashes with following dialog:

![スクリーンショット 2019-12-25 12 45 53](https://user-images.githubusercontent.com/823277/71431375-c79ce980-2714-11ea-9d10-179aca8297ac.png)

Though it is localized, it says 'Application exited due to unexpected reason. When you want to reopen the application, please click "reopen". When you want to send a crash report to Apple, please click "report"'.

### Additional Information
Might be related to #21597, but in this case `webRequest` listener is not involved.

**Comment by loc** [comment]
I've traced the crash to [this change](https://github.com/electron/electron/pull/19979/files#diff-8a19e7f384ba27f625eb0e55641ee5feL1016-L1017). I think it was broken before, that change just revealed it. Chatting with @zcbenz, we think the direction forward is to ensure that the protocol module is initialized before consumers have the opportunity to unbind necessary listeners for its setup. I should have time to finish this up next week.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
