### ISSUE TITLE
 Need to click twice to switch cursor between outter page and webview when webview in mobile mode

### ISSUE THREAD

**Issue by Mqleaf** [electron/electron#21624]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.7 & 6.1.4
* **Operating System:**
  * macOS 10.13.4
* **Last Known Working Electron version:**
  * not sure, but 2.0.9 works well.

### Expected Behavior

1. Electron page(html) contains a webview which in mobile mode, just click once can switch the mouse cursor. 
2. Other text element ( like element p ) in the html is selectable.

### Actual Behavior

1. I click the button in the page(html), then click item in the webview, the webview has no response. I need to click item in the webview one more time to make it work.
2. I cannot use mouse to select the text of other element in the html.

### To Reproduce

index.html
```
<html>
  <head>
    <title>Hello World</title>
    <style>
      body {
        text-align: center;
        background-image: linear-gradient(45deg, rgb(144, 201, 234) 0%, rgb(83, 151, 239) 100%);
      }

      button {
        background: rgba(0,0,0,0.40);
        box-shadow: 0px 0px 4px 0px rgba(0,0,0,0.50);
        border-radius: 8px;
        color: white;
        padding: 1em 2em;
        border: none;
        font-family: 'Roboto', sans-serif;
        font-weight: 300;
        font-size: 14pt;
        position: relative;
        top: 40%;
        cursor: pointer;
        outline: none;
      }

      button:hover {
        background: rgba(0,0,0,0.30);
      }

      webview{
        height: 600px;
        margin-bottom: 10px;
        /* background: #ffffff; */
      }
      #browser{
        width: 360px;
        height: 640px;
      }
    </style>
    <link href='https://fonts.googleapis.com/css?family=Roboto:300' rel='stylesheet' type='text/css' />
  </head>
  <body>
    <p>electron - 7.1.7</p>
    <button id="refresh">refresh</button>
    <webview id="browser" src="https://www.iconfont.cn/" nodeintegration nodeintegrationinsubframes enableremotemodule="true" disablewebsecurity preload="./webview-pre.js"></webview>
    <webview id="devtools"></webview>
  </body>
  <script src="app.js"></script>
</html>
```
app.js
```
let pageView 
let devtoolsView
let browser
let view

const electron = require('electron')
const { BrowserView } = require('electron').remote;
const win = electron.remote.getCurrentWindow();

window.onload = main;

function main() {
    pageView = document.getElementById("browser");
    devtoolsView = document.getElementById("devtools");
    refreshBtn = document.getElementById('refresh');
    createView();
    pageView.addEventListener("dom-ready", () => {
        browser = pageView.getWebContents();
        setDevtools(browser);
    });
    refreshBtn.addEventListener('click', ()=> {
        console.log('refresh')
        pageView.reload();
    })
}

// create browserview
function createView() {
    view = new BrowserView({
        webPreferences: {
            webviewTag: true,
            nodeIntegration: true,
            preload: './webview-pre.js'
        }
    });
    win.setBrowserView(view);
    view.setBounds({ x: 10, y: 750, width: 1200, height: 550 })
    view.on('closed', () => { view = null; });
}

// devtools set to browserview
function setDevtools(browser) {
    browser.setDevToolsWebContents(view.webContents);
    browser.openDevTools({mode: 'right'});
    // browser.setDevToolsWebContents(devtoolsView.getWebContents());
    // browser.openDevTools({ mode: "right" });
}
```
1. In the html, there is a webview for webpage, a browserView for devtools of the webpage.
![image](https://user-images.githubusercontent.com/22488004/71506051-66167f80-28ba-11ea-9993-6bc23edd5151.png)

2. Click the mobile button switch the webview to mobile mode.
![image](https://user-images.githubusercontent.com/22488004/71506106-92ca9700-28ba-11ea-8bcc-bbe752a14e35.png)

3. Click item in webview, no response, need to click twice.
![image](https://user-images.githubusercontent.com/22488004/71506167-c60d2600-28ba-11ea-9aa6-4a7d032e51b7.png)

4. After webview responsed, click refresh button in the html, no response, need to click twice as well.
![image](https://user-images.githubusercontent.com/22488004/71506226-0bc9ee80-28bb-11ea-86ec-039d3aea7377.png)

5. tag p in html is not selectable.
![image](https://user-images.githubusercontent.com/22488004/71507484-aaf0e500-28bf-11ea-9c7c-206e68105bc9.png)

### Additional Information

1. This issue not occurs in Electron 2.0.9, just use the same code.
2. Put the devtools in a Webview or BrowserWindow, also has this issue.
3. If the webview not in mobile mode, this issue not occurs.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
