### ISSUE TITLE
Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by jega-ms** [electron/electron#21626]
I've integrated  RxDx with electron-forge based project.  I'm getting the  below error. 

```
browser.js:2 Uncaught ReferenceError: global is not defined
    at Object../node_modules/immediate/lib/browser.js (browser.js:2)
    at __webpack_require__ (bootstrap:726)
    at fn (bootstrap:100)
    at Module../node_modules/pouchdb-utils/lib/index-browser.es.js (index-browser.es.js:1)
    at __webpack_require__ (bootstrap:726)
    at fn (bootstrap:100)
    at Module../node_modules/pouchdb-selector-core/lib/index.es.js (index.es.js:1)
    at __webpack_require__ (bootstrap:726)
    at fn (bootstrap:100)
    at Module../node_modules/rxdb/dist/es/query-change-detector.js (query-change-detector.js:1)
```

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by xgkobe** [comment]
> I've integrated RxDx with electron-forge based project. I'm getting the below error.
> 
> ```
> browser.js:2 Uncaught ReferenceError: global is not defined
>     at Object../node_modules/immediate/lib/browser.js (browser.js:2)
>     at __webpack_require__ (bootstrap:726)
>     at fn (bootstrap:100)
>     at Module../node_modules/pouchdb-utils/lib/index-browser.es.js (index-browser.es.js:1)
>     at __webpack_require__ (bootstrap:726)
>     at fn (bootstrap:100)
>     at Module../node_modules/pouchdb-selector-core/lib/index.es.js (index.es.js:1)
>     at __webpack_require__ (bootstrap:726)
>     at fn (bootstrap:100)
>     at Module../node_modules/rxdb/dist/es/query-change-detector.js (query-change-detector.js:1)
> ```

are you re

> I've integrated RxDx with electron-forge based project. I'm getting the below error.
> 
> ```
> browser.js:2 Uncaught ReferenceError: global is not defined
>     at Object../node_modules/immediate/lib/browser.js (browser.js:2)
>     at __webpack_require__ (bootstrap:726)
>     at fn (bootstrap:100)
>     at Module../node_modules/pouchdb-utils/lib/index-browser.es.js (index-browser.es.js:1)
>     at __webpack_require__ (bootstrap:726)
>     at fn (bootstrap:100)
>     at Module../node_modules/pouchdb-selector-core/lib/index.es.js (index.es.js:1)
>     at __webpack_require__ (bootstrap:726)
>     at fn (bootstrap:100)
>     at Module../node_modules/rxdb/dist/es/query-change-detector.js (query-change-detector.js:1)
> ```

I have the same problem. Have you solved it？

**Comment by xgkobe** [comment]
> I've integrated RxDx with electron-forge based project. I'm getting the below error.
> 
> ```
> browser.js:2 Uncaught ReferenceError: global is not defined
>     at Object../node_modules/immediate/lib/browser.js (browser.js:2)
>     at __webpack_require__ (bootstrap:726)
>     at fn (bootstrap:100)
>     at Module../node_modules/pouchdb-utils/lib/index-browser.es.js (index-browser.es.js:1)
>     at __webpack_require__ (bootstrap:726)
>     at fn (bootstrap:100)
>     at Module../node_modules/pouchdb-selector-core/lib/index.es.js (index.es.js:1)
>     at __webpack_require__ (bootstrap:726)
>     at fn (bootstrap:100)
>     at Module../node_modules/rxdb/dist/es/query-change-detector.js (query-change-detector.js:1)
> ```

I have the same problem. Have you solved it
