### ISSUE TITLE
Wrong shell.openPath() result

### ISSUE THREAD

**Issue by vladimiry** [electron/electron#21623]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 9.0.0-nightly.20191225
* **Operating System:** Linux
* **Last Known Working Electron version:** new method introduced since v9

### Expected Behavior
- `object { result: {success: true, errorMessage: ""} }` printed to console.
- `app.getPath("userData")` opened

### Actual Behavior
- `string { result: '' }` printed to console.
- `app.getPath("userData")` opened

### To Reproduce
```
git clone git@github.com:vladimiry-playground/electron-quick-start-openpath-issue.git
cd electron-quick-start-openpath-issue
npm ci
npm start
```

### Additional Information

Ref #20682, CC @codebytere

**Comment by codebytere** [comment]
Incorrect documentation; should be
```
### `shell.openPath(path)`

* `path` String

Returns `Promise<String>` - Resolve with an object containing the following:

* `errorMessage` String - The error message corresponding to the failure if a failure occurred, otherwise "".

Open the given file in the desktop's default manner.
```

will fix.
