### ISSUE TITLE
Support Mobile Apps (Android and IOS)

### ISSUE THREAD

**Issue by AhmetTR7771** [electron/electron#21620]
Can you support mobile? Please, add make mobile apps like desktop apps.

**Comment by Alecyrus** [comment]
It is impossible and impractical.  React Native and Flutter should be better choices.

**Comment by RealAlphabet** [comment]
> It is impossible and impractical. React Native and Flutter should be better choices.

First, please forgive me for reviving this old issue.

The answer to this question is not enough for me. Saying "Impossible, use another alternative" is not constructive at all. It will neither help the Electron project to evolve, nor give an informed answer to the question. Maybe it seems impossible for you but that doesn't mean it is.

I would be interested in contributing to the development of an Android-compatible Electron version. At the moment I have only just started to study the Electron codebase. If other contributors or people interested in developing an Android-compatible version come by, feel free to mention me or contact me on LinkedIn.
