### ISSUE TITLE
check-python-tls tries to use Python3 when `python` is pointed to python3 instead of 2

### ISSUE THREAD

**Issue by ChadBailey** [electron/electron#21627]
> This is a bug report, but if you have come here in search of help on this error see the bottom of this post "Fix for MacOS"

### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v7.1.7
* **Operating System:**
  * Mac OS X ProductVersion: 10.14.6 BuildVersion:   18G1012
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
Given that python2 is installed, and accessible via `python2` or `python2.7`, running the command `$ npx @electron/check-python-tls` should use python2 and not attempt to use python3.

Additionally, the version of python in use should be checked to provide a less cryptic error message in the unlikely event the code was executed using python3 in error.

### Actual Behavior
```
$ npx @electron/check-python-tls
npx: installed 1 in 0.653s
  File "/Users/user/.npm/_npx/77158/lib/node_modules/@electron/check-python-tls/tls.py", line 41
    print "Your system/python combination is using an outdated security " \
                                                                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Your system/python combination is using an outdated security " \)?
```

### To Reproduce
1. Validate `python` is pointed to `python3` rather than `python2`, and `python2` is properly set up
```
$ which python
/usr/local/bin/python
$ ls -al /usr/local/bin/python
lrwxr-xr-x  1 username  admin  42 Dec 27 16:51 /usr/local/bin/python -> /usr/local/Cellar/python/3.7.5/bin/python3
$ python -V
Python 3.7.5
$ python2 -V
Python 2.7.17
$ python3 -V
Python 3.7.5
```

2. Run `npx @electron/check-python-tls` to see attempt to use python3 for python2 code
```
$ npx @electron/check-python-tls
npx: installed 1 in 1.124s
  File "/Users/username/.npm/_npx/81322/lib/node_modules/@electron/check-python-tls/tls.py", line 41
    print "Your system/python combination is using an outdated security " \
                                                                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Your system/python combination is using an outdated security " \)?
```

3. Validate this is root cause via linking `python` to `python2` and trying again

```
$ ln -s /usr/local/bin/python2 /usr/local/bin/python
$ python -V
Python 2.7.17
$ npx @electron/check-python-tls
npx: installed 1 in 0.851s
Your Python is using TLSv1.3, which is sufficient for building Electron.
```

### Additional Information

I'm sure you're aware python 2 is officially end of life in 4 days. If dependencies require that python2 continue to be used past EOL, at least give the user the freedom to be able to symlink `python` to python3.

Also, `python` has been traditionally symlinked to `python2` to maintain backwards compatibility with Linux system utilities, however, It is very possible that as Linux distros update to python3 `python` may begin pointing to python3 with system utilities depending upon it. If this does happen, it will become impossible to run/build electron on these systems for the same reason that you [can't remove python2 from some older distros](https://askubuntu.com/questions/187227/i-run-sudo-apt-get-remove-python2-7-can-i-restore-my-ubuntu-now)

### Fix for MacOS
If you've found this thread due to the above error and don't understand the above details, here is how you should fix.

1. Use homebrew to install python2 `brew install python@2`
> If you don't have homebrew/that command didn't work, visit the [homebrew website](https://docs.brew.sh/Installation) for instructions on installing homebrew then redo step 1
2. Ensure you haven't explicitly added python to your path via some other means `echo $PATH |grep python` - this should return to the next line without showing anything
  a. If you find that the prior command does return a result, search for modifying your path. Likely, you will end up editing `~/.bashrc` or `~/.bash_profile` to remove python specific path
3. Force brew to relink python2 via `$ brew unlink python@2 && brew link python@2 --overwrite`
4. Ensure `python -V` returns `Python 2.7.x` (where .x is probably .14 but might be higher) and you should be all set

**Comment by malept** [comment]
`@electron/check-python-tls` can be found in a GitHub repository at: https://github.com/MarshallOfSound/check-python-tls

I've filed a PR to do a basic 2 vs. 3 version check (no idea when it's going to be merged/released as it's the holidays): https://github.com/MarshallOfSound/check-python-tls/pull/1

Since this isn't specifically a bug with Electron (but rather a bug with a build dependency), I'm closing this issue.

**Comment by ChadBailey** [comment]
Sorry, I'm new to the npm ecosystem and didn't realize that was a dependency. Thanks for the quick response!
