### ISSUE TITLE
default button in dialog not working on macOS

### ISSUE THREAD

**Issue by tessus** [electron/electron#21633]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v7.1.5 (also tried 7.1.7)
* **Operating System:**
  * macOS 10.14.6 (but I think it doesn't matter. I think it happens on all macOS versions)
* **Last Known Working Electron version:**
  * none that I know of

### Expected Behavior
When I set `defaultId` for `showMessageBox*`, the button set should be active by default.

### Actual Behavior

No button is selected at all:

<img width="217" alt="image" src="https://user-images.githubusercontent.com/223439/71554617-97449c00-29ef-11ea-960d-7a7558120531.png">

### To Reproduce
Minimal example:

`test.js`

```
const {app, BrowserWindow, dialog} = require('electron');

let mainWindow;

app.on('ready', () => {
	mainWindow = new BrowserWindow({
		height: 200,
		width: 440
	});

	mainWindow.loadURL('file://' + __dirname + '/index.html');

	const ok = dialog.showMessageBoxSync(mainWindow, {
		type: 'question',
		message: 'message here',
		buttons: ['Ok', 'Cancel'],
		defaultId: 1,
		cancelId: 1,
	});
});
```

`node_modules/electron/dist/Electron.app/Contents/MacOS/Electron test.js`

<img width="552" alt="image" src="https://user-images.githubusercontent.com/223439/71555100-db3a9f80-29f5-11ea-86f0-0c0e31c91809.png">

---

Context:

An application that uses Electron and experiences this problem is Joplin. Joplin can be built as follows:

```
git clone https://github.com/laurent22/joplin.git
cd joplin
npm install && cd Tools && npm install && cd ..
cd ElectronClient/app
npm install
cd ..
./run.sh
```

To get to such a dialog, create a notebook and a note. Right-click on a note an choose `Delete`.
Or try to delete one of the welcome notes.

### Additional Information
I've seen this problem since Electron 4.x. I can't recall an Electron version where this ever worked on macOS.

**Comment by codebytere** [comment]
@sami-azzam  i see this and am happy to investigate but yes for bookkeeping reasons it'd be super helpful if you could make a new issue! feel free to mention me.
