### ISSUE TITLE
Uncaught TypeError: require(...) is not a function

### ISSUE THREAD

**Issue by MelerEcckmanLawler** [electron/electron#21636]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v7.1.7
* **Operating System:**
  * Windows 10 64bit

### Expected Behavior
`require()` should work in `.html` file as it does in `main.js`

### Actual Behavior
Console logs `Uncaught TypeError: require(...) is not a function`

### To Reproduce
Use the `require()` function inside a local `.html` file loaded by Electron.

### Additional Information
The problem isn't related to `nodeIntegration` being `false` because I have this in `main.js`:

    mainWindow = new BrowserWindow({
        webPreferences: {
          nodeIntegration: true,

**Comment by lizeze** [comment]
I want to see how your `main.js` is written

**Comment by MelerEcckmanLawler** [comment]
`use strict`
    const { app, BrowserWindow, Menu } = require(`electron`)
    const electron = require(`electron`)
    const path = require(`path`)
    let mainWindow
    function createWindow() {
      mainWindow = new BrowserWindow({
        resizable: false,
        backgroundColor: `#fff`,
        width: 1100,
        height: 700,
        skipTaskbar: true,
        webPreferences: {
          webSecurity: false,
          nodeIntegration: true,
          preload: path.join(__dirname, `preload.js`)
        }
      })
      mainWindow.loadURL(`file:///${__dirname}/index.html`)
      Menu.setApplicationMenu(null)
      mainWindow.webContents.openDevTools()
      mainWindow.on(`closed`, function () { mainWindow = null })
    }
    app.on(`ready`, createWindow)
    app.on(`window-all-closed`, function () { if (process.platform !== `darwin`) app.quit() })
    app.on(`activate`, function () { if (mainWindow === null) createWindow() })

**Comment by reZach** [comment]
@MelerEcckmanLawler do you have a sample repo we can run to test this for you?

**Comment by FI-GGG** [comment]
我也遇到了同样的问题! 我升级到electron8后才这样,之前是7.0,但7.0有 tray的bug。
I encountered the same problem!This is the case after I upgraded to electron8. Before 7.0 everything was normal because 7.0 has a tray bug.



Electron Version:
v8.0.2
Operating System:
Windows 10 64bit

**Comment by codebytere** [comment]
Given that no repro has been provided for this specific issue, and i'm unable to recreate it myself, i'm going to go ahead and close this. Happy to open again should more information come to light.
