### ISSUE TITLE
hiddenInset breaks mouse interactions in the first 38px of the window

### ISSUE THREAD

**Issue by astoilkov** [electron/electron#21632]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.1.5
* **Operating System:**
  * macOS Mojave 10.14.6
* **Last Known Working Electron version:**
  * We have observed the bug for the last few years. Most probably this has never worked.

### Expected Behavior

- Start a mouse drag operation from the first 38px of the window and while dragging move the mouse below the 38px. `mousemove` and `mouseup` events should continue to fire.
- Setting `cursor` CSS property on elements that show in the first 38px of the window should show cursor type which was set in CSS

### Actual Behavior

- Start a mouse drag operation from the first 38px of the window and while dragging move the mouse below the 38px. `mousemove` and `mouseup` events stop being fired and continue to get fired after the user performs a mouse up operation.
- Setting `cursor` CSS property on elements that are rendered in the first 38px of the window should the default cursor regardless of what was set in CSS.

### To Reproduce

The only thing needed is setting `titleBarStyle: 'hiddenInset'` when creating a new `BrowserWindow` instance. Subscribing to `mousemove` and `mouseup` events will show the first problem. Setting `cursor: pointer` to the entire page will show the second problem.

### Additional Information

The 38px described above match the height of the title bar in applications with inset buttons.

There are already two open issues that look connected to the problems described in this issue:
- [hiddenInset + BrowserView = window drag canceled if cursor leaves drag region](https://github.com/electron/electron/issues/18514)
- [macOS Mojave: Unclickable region in windows with "hiddenInset" title bar](https://github.com/electron/electron/issues/14529)

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by MiguelMike** [comment]
Still an issue on version 33.2.0.
