### ISSUE TITLE
Electron with firebase dependency crashes

### ISSUE THREAD

**Issue by navratill** [electron/electron#21634]
Hello, 

when I am adding firebase dependency to my electron project and importing to main.js as:
`import firebase from 'firebase';`

It is replicable in electron-quick-start project as well, just add firebase dependency and import the firebase module.

It crashes during the application load with the error: 
> App threw an error during load
> Error: Failed to load gRPC binary module because it was not installed for the current system
> Expected directory: electron-v7.1-darwin-x64-unknown
> Found: [node-v64-darwin-x64-unknown]
> This problem can often be fixed by running "npm rebuild" on the current system

npm rebuild doesn't help...

Any ideas how to solve this? I am using last version of electron and the last version of firebase:
"electron": "^7.1.7"
"firebase": "^7.6.1"

**Comment by codebytere** [comment]
Closing as duplicate underlying issue of https://github.com/electron/electron/issues/21638
