### ISSUE TITLE
webContents.printToPDF in electron7.x ,it's do not work

### ISSUE THREAD

**Issue by terry-zi** [electron/electron#21639]
in renderer.js , i used fn webContents.printToPDF in electron7.x ,it's do not work , but in 6.1.5 it'ok .
I think it's a bug.

const fs = require('fs')
const os = require('os')
const path = require('path')
const pdfPath = path.join(os.tmpdir(), 'test.pdf')
const remote = require('electron').remote
let mainWindow = remote.getCurrentWindow();

mainWindow.webContents.on('did-finish-load', () => {
    mainWindow.webContents.printToPDF({}, (errror, data) => {
        fs.writeFile(pdfPath, data,(err)=>{
          remote.shell.openExternal('file://' + pdfPath)
        });
      })
});

**Comment by markleutloff** [comment]
printToPDF returns a Promise<Buffer> now.
The callback you provide when calling printToPDF will no longer be used.

See: https://github.com/electron/electron/blob/v7.0.0/docs/api/web-contents.md#contentsprinttopdfoptions

**Comment by codebytere** [comment]
@markleutloff is correct, as per our documentation. Closing this in that event.
