### ISSUE TITLE
setFullScreen can't work properly in electron 6.1.5

### ISSUE THREAD

**Issue by 623841176** [electron/electron#21649]
I used electron 6.1.5. While an app used setResizable(false), setFullScreen(true) can't work properly. So I must use things like below:
`const { remote } = window.require('electron');
const win = remote.getCurrentWindow();
win.setResizable(true);
win.setFullScreen(true);
win.setResizable(true);`

Then I can see this worked. Is this a bug?

**Comment by codebytere** [comment]
No; resizability takes fullscreenability into account at present. I'm going to close this in that event, but if more information comes to light i'm happy to take a second look.
