### ISSUE TITLE
Documentation to include understanding of folder structure

### ISSUE THREAD

**Issue by pjebs** [electron/electron#21656]
Can there be more information provided to understand the source code folder structure of this repo.

That is so:

1. We may want to issue a PR for a bug fix but we don't know where to find where the feature is implemented

2. We may want to inspect the code to increase general understanding of what's going on under the hood for the various OS

**Comment by codebytere** [comment]
@pjebs more than what's already [here](https://electronjs.org/docs/development/source-code-directory-structure)?

**Comment by pjebs** [comment]
The page you linked to said there is an `atom/app/` directory. Is that meant to be in this repo/master branch or some other branch? I don't see it anywhere? I see some of the other directories on the linked page such as `chromium_src`, `default_app ` and  `docs`. I don't see `atom`.

**Comment by codebytere** [comment]
`atom` got renamed to `shell`; i'll update that.
