### ISSUE TITLE
installer error: sorry,we could not configure system to connect to outline.

### ISSUE THREAD

**Issue by superior68** [electron/electron#21650]
os: windows v 32bit
outline-client version: 1.3.1

error:
sorry,we could not configure system to connect to outline.please try running the installer again.
if you still cannot install outline,please get in touch with us and let us know that the TAP device could not be installed

also i reinstall this version with 1.2.34 and it be installed but cannot connect to my server.
version 1.3.1 has working well on another PCs that run windows 8.1 64 bit
help me please.

**Comment by codebytere** [comment]
This is not an issue with Electron: I suggest you file an issue on the [outline-client](https://github.com/Jigsaw-Code/outline-client) repo.
