### ISSUE TITLE
build electron on MacOS, getting the code steps, "gclient sync" command fail.

### ISSUE THREAD

**Issue by tapir-dream** [electron/electron#21669]
I am build electron on MacOS.
While getting the code steps,
I found a problem using the command "gclient sync --with_branch_heads --with_tags",
Please help me out.

System: MacOS 10.14.6

```sh
$ gclient sync --with_branch_heads --with_tags
```
### Screenshots
![image](https://user-images.githubusercontent.com/1677226/71711743-60caaf00-2e3d-11ea-9e45-e00a7aa8e751.png)

**Comment by codebytere** [comment]
@tapir-dream what steps did you take after seeing this error?

<img width="774" alt="Screen Shot 2020-01-03 at 11 14 39 AM" src="https://user-images.githubusercontent.com/2036040/71734607-4b905900-2e1a-11ea-849d-e350bd4f7deb.png">

seems like the next logical place to go. I also recommend you use our [`build-tools`](https://github.com/electron/build-tools) repository to build the project and open further issues there.

**Comment by tapir-dream** [comment]
```
git clone https://github.com/electron/build-tools.git
cd build-tools
yarn install
export PATH="$PATH:$PWD/src"
e load-macos-sdks
e init --root=/path/to/new/electron/directory --bootstrap testing
```
![image](https://user-images.githubusercontent.com/1677226/71777491-ade48780-2fdb-11ea-807f-5815017fefa5.png)

**Comment by codebytere** [comment]
@tapir-dream `/path/to/new/electron/directory` is a placeholder, meaning that it should be replaced with a new directory in the location of your choice. It is saying that there is no directory at that location because there is none; you need to create one (mine, for example, is `/Users/codebytere/Developer/electron-gn` and pass that path to it:

`e init --root=/Users/codebytere/Developer/electron-gn --bootstrap testing`

**Comment by tapir-dream** [comment]
sorry,paste error, using new directory.
``
e init --root=Users/showopt/worker/project/electron/ --bootstrap testing
``

**Comment by codebytere** [comment]
@tapir-dream please open this issue on the build-tools repo; i also suggest you check that `/Users/showopt/worker/project/electron/` exists. The path needs to be exactly correspondent to the new directory and have a preceding slash.
