### ISSUE TITLE
Electron Helper(GPU) process still require high perf GPU when all BrowserWindow which needs webGL were closed

### ISSUE THREAD

**Issue by boluobanana** [electron/electron#21664]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
5.0.0, 6.0.0, 7.0.0
* **Operating System:**
macOS 10.13.6
* **Last Known Working Electron version:**
not sure

### Expected Behavior
When I close all browserWindow which used webGL context.
In Activity Monitor Electron Helper(GPU) will not require high perf GPU.

### Actual Behavior
When I close all browserWindow which used webGL context.
In Activity Monitor Electron Helper(GPU) still require high perf GPU.

### To Reproduce
```
git clone git@github.com:boluobanana/electron-quick-start.git
npm i
npm run start

// click the btn openThreeJsDoc
// when the new page onload and In Activity Monitor Electron Helper(GPU) has requires high perf GPU. Close this page
// The helper still required high perf GPU
```

### Screenshots

![image](https://user-images.githubusercontent.com/5364199/71677496-f32b6e00-2dbd-11ea-9d0d-0bee80aeb459.png)

After close the webgl page
![image](https://user-images.githubusercontent.com/5364199/71677588-2a018400-2dbe-11ea-91d0-06938aa9dc08.png)

### Additional Information
And I do the same things at Chrome 79.0.3945.88. When I close the website which created webGL Context , After 5s later, the Chrome Helper(GPU) not requires high perf GPU any more.

Is there some way can close the GPU process manually or stop require high perf GPU?

**Comment by nornagon** [comment]
Possibly related: https://github.com/electron/electron/issues/13303

Can you paste the contents of `about:gpu` from Chrome? Thanks!

**Comment by boluobanana** [comment]
I try same thing in Electron 8.0.0 beta. It not require high perf GPU any more.
