### ISSUE TITLE
app.on('ready', callback) causes TypeScript compilation errors when callback has a specified type.

### ISSUE THREAD

**Issue by K4rakara** [electron/electron#21678]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.7
* **Operating System:**
  * Manjaro Linux, 64 bit.
* **Last Known Working Electron version:**
  * Unknown

### Expected Behavior
A value with the type of "`Function`" will compile when used as callback for an `app.on` listener.

### Actual Behavior
Refuses to compile unless the type `Function` is removed.

### To Reproduce
```ts
const electronCreateWindow:Function = ():void => {
	// code here
};

app.on('ready', electronCreateWindow);
```
... Results in the following error ...
```
main.ts:99:8 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '"ready"' is not assignable to parameter of type '"window-all-closed"'.

99 app.on('ready', electronCreateWindow);
          ~~~~~~~

  node_modules/electron/electron.d.ts:830:5
    830     on(event: 'window-all-closed', listener: Function): this;
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The last overload is declared here.
```
... Whereas this does not.
```ts
const electronCreateWindow = ():void => {
	// code here
};

app.on('ready', electronCreateWindow);
```

### Additional Information
Looking at the file that is marked as problematic, these lines seem to be improperly typed? Possibly adding `|Function` to the type would fix it.
```ts
on(event: 'ready', listener: (launchInfo: unknown) => void): this;
once(event: 'ready', listener: (launchInfo: unknown) => void): this;
addListener(event: 'ready', listener: (launchInfo: unknown) => void): this;
removeListener(event: 'ready', listener: (launchInfo: unknown) => void): this;
```
Also, its worth noting that (at least when using yarn, I'm not sure if this will occur with NPM as well) electron causes 18 compile errors when running `yarn tsc`. Every single error is almost identical to this:
```
node_modules/electron/electron.d.ts:1655:31 - error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?

1655   class BrowserWindow extends NodeJS.EventEmitter {
                                   ~~~~~~
```

**Comment by MarshallOfSound** [comment]
You have an incorrect dependency on `@types/node@^13` somewhere in your deps tree.  You should remove that dependency on depend on `@types/node@^12`

Refs: #21612

**Comment by K4rakara** [comment]
Thanks for the tip, that got rid of the compile errors related to extends NodeJS.
However, using type `function` still causes a compile error.

**Comment by psulek** [comment]
I have same problem as described above with this code:

```ts
  app.on('child-process-gone', (event: Event, details: Electron.Details) => {});
```

Turns out easy fix for me was to fully specify `Event` -> `Electron.Event` , because it gets confused nodejs `Event` type with electron type.

Working code:
```ts
  app.on('child-process-gone', (event: Electron.Event, details: Electron.Details) => {});
```
