### ISSUE TITLE
Skipping extension with invalid URL

### ISSUE THREAD

**Issue by rangerscience** [electron/electron#21673]
### Preflight Checklist
* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

There is an existing issue that was closed because it didn't provide info such as how to reproduce. (https://github.com/electron/electron/issues/14779). LMK if I should do something different than opening this issue.

### Issue Details

* **Electron Version:**
  * 7.1.7
* **Operating System:**
  * MacOS Mojave 10.14.5
* **Last Known Working Electron version:**
  * Unknown

### Expected Behavior
Extension should load without reporting errors

### Actual Behavior

Main process logs error:
`[30712:0102/163027.980187:ERROR:CONSOLE(8007)] "Skipping extension with invalid URL: chrome-extension://my-cool-extension", source: devtools://devtools/bundled/shell.js (8007)`

Extension does appear to run properly, although it's perhaps too simple to see other effects of this error.

### To Reproduce
$ git clone https://github.com/rangerscience/electron-extensions
$ npm install
$ npm start

### Additional Information
This looks relevant: https://github.com/electron/electron/blob/master/lib/browser/chrome-extension.js#L405

I have no idea where to even begin finding `devtools://devtools/bundled/shell.js (8007)`. Any help there would be appreciated.

### Additional Questions
These are other things I'm trying to figure out with regards to extensions, but that are outside the immediate scope of this issue.

- Is there any way to go from the docs (say, [`webContents.loadURL`](https://electronjs.org/docs/api/web-contents#contentsloadurlurl-options) to the implementing code?
- Where would the logs from the background script show up?
- Is there any way to invoke an extension's browser action button? (I'm not seeing any in the doc)

**Comment by johannesjo** [comment]
Still occurs for me with v7.1.12

**Comment by danutzcodrescu** [comment]
Same problem on `v8.1.1` and `8.2.1`.
