### ISSUE TITLE
registerFileProtocol results into window.location.origin is null

### ISSUE THREAD

**Issue by user321321** [electron/electron#21675]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.7
* **Operating System:**
  * Windows 10

### My Goal:
The goal is to restrict the file access of electron renderer. So win.loadFile() cannot be used, because with file:// i have access to all files on the computer. Therefore I have to register an own custom protocol.

### Expected Behavior
window.location.origin should be set

### Actual Behavior
With the custom file protocol window.location.origin is null. Therefore Content-Security-Policy is not work correctly, i.e. contents cannot be loaded per Javascript.
> Access to XMLHttpRequest at 'app://cms/test.html' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, https.

### To Reproduce
main.js

> const { app, protocol, BrowserWindow } = require('electron')
const path = require('path')
function createWindow () {
  // Create the browser window.
  let win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
		contextIsolation: true,
		sandbox: true,
		nodeIntegration: false,
		allowRunningInsecureContent: false,
		webSecurity: true,
		enableRemoteModule: false
    }
  })
  protocol.registerFileProtocol('app', (request, callback) => {
    url = request.url.substr(10);
	if (url === '') {
		url = '/index.html';
	}
    callback({ path: path.normalize(`${__dirname}/${url}`) })
	}, (error) => {})
  //win.loadFile('index.html'); //window.location.origin is file://.
  win.loadURL('app://cms'); //window.location.origin is null
}
app.on('ready', createWindow)

index.html
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Security-Policy" content="script-src 'self' 'unsafe-inline';" />
  </head>
  <body>
    window.location.origin is <script>document.write(window.location.origin)</script>.
  </body>
</html>
```

**Comment by vladimiry** [comment]
@deepak1556 is this by design?

@user321321 You might want to try `registerBufferProtocol` instead. It works there as you need. By the way, did you also register the protocol by calling `protocol.registerSchemesAsPrivileged(["your-scheme", {privileges: {corsEnabled: true, standard: true}}])` (needs to be called before app read even fired, and called only once)?

**Comment by user321321** [comment]
@vladimiry 
Thank you for your answer.
When I replace the protocol.registerFileProtocol function in main.js with registerBufferProtocol, window.location.origin is still null.

> 	protocol.registerBufferProtocol('app', (request, callback) => {
> 	  callback({ mimeType: 'text/html', data: Buffer.from('<!DOCTYPE html><html>  <head>    <meta charset="UTF-8">    <meta http-equiv="Content-Security-Policy" content="script-src \'self\' \'unsafe-inline\';" />  </head>  <body>    window.location.origin is <script>document.write(window.location.origin)</script>.  </body></html>') })
> 	}, (error) => {})

**Comment by user321321** [comment]
@vladimiry 
Thank you very much. When I add `protocol.registerSchemesAsPrivileged(["your-scheme", {privileges: {corsEnabled: true, standard: true}}])` the window.location.origin will be set, also with protocol.registerFileProtocol :)

**Comment by deepak1556** [comment]
@vladimiry yes this is by design, custom schemes registered with `standard: true` property will have origin set.
