### ISSUE TITLE
Insecure CORS Always Enabled for Buffer Protocols

### ISSUE THREAD

**Issue by moloch--** [electron/electron#21676]
### Issue Details

* **Electron Version:**
  * 7.1.7
* **Operating System:**
  * Darwin
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior

`corsEnabled` flag should disable CORS response headers, alternatively add an option to control the CORS response.

### Actual Behavior

Regardless of the `corsEnabled` flag `Access-Control-Allow-Origin: *` is always returned.

### To Reproduce

```
  protocol.registerSchemesAsPrivileged([{
    scheme: 'app',
    privileges: { 
      standard: true,
      secure: true,
      corsEnabled: false,
    }
  }
```

### Screenshots

<img width="371" alt="Screen Shot 2020-01-04 at 11 46 22 AM" src="https://user-images.githubusercontent.com/875022/71769567-a1333700-2ee8-11ea-96cd-42f7dfe7ce2a.png">

**Comment by vladimiry** [comment]
Can you add a link to a minimal repository with the issue to be reproducible (preferably based on https://github.com/electron/electron-quick-start)?

**Comment by moloch--** [comment]
https://github.com/moloch--/electric-scan

**Comment by vladimiry** [comment]
First of all, to verify CORS headers you need to run XHR / Fetch request triggered by JS code, not a regular GET like iframes do.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

> For security reasons, browsers restrict cross-origin HTTP requests initiated from scripts. For example, XMLHttpRequest and the Fetch API follow the same-origin policy. This means that a web application using those APIs can only request resources from the same origin the application was loaded from, unless the response from other origins includes the right CORS headers.

Then even if you perform XHR/Fetch request from the `file://` protocol there still will be no cross-domain error (probably by design). But if you load the browser window page from custom protocol, like `app1` and then perform XHR/Fetch request to another protocol like `app2` or `https` or same protocol but different host you will get the expected cross-domain error.

> alternatively add an option to control the CORS response.

You already have such capability (see https://electronjs.org/docs/api/web-request):

```javascript
session.defaultSession.webRequest.onHeadersReceived(
    (
      responseDetails,
      callback,
    ) => {
      const {responseHeaders} = responseDetails;
      delete responseHeaders["Access-Control-Allow-Origin"]
      callback({responseHeaders});
    },
  );
```

**Comment by moloch--** [comment]
TIL: Same-origin Policy just isn't a thing in Electron when running in the context of a `file://` origin.

**Comment by moloch--** [comment]
Wait, so what does the `corsEnabled` flag do? I updated my example to use XHR and the response header is still there. While hooking `session.defaultSession.webRequest` to modify the response header is a neat trick this is documented no where, nor is mentioned in any of the `corsEnabled` details.

**Comment by moloch--** [comment]
Figured it out, Electron's DevTools does not accurately report response headers. The CORS response headers don't actually exist, and cross-origin access is indeed blocked between `app://` and `app2://` --and `file://` can simply access anything, Electron does not enforce SOP in a `file://` origin.

**Comment by zuoxiaofeng** [comment]
> Figured it out, Electron's DevTools does not accurately report response headers. The CORS response headers don't actually exist, and cross-origin access is indeed blocked between `app://` and `app2://` --and `file://` can simply access anything, Electron does not enforce SOP in a `file://` origin.

Does this description was in any docs of electron，the SOP in electron is opposed to SOP in a browser，I was confused about it but cannot found any offical doc for it.
By the way, is there a way to enforce SOP in a file:// origin.

Thanks
