### ISSUE TITLE
Microsoft Store Rejection: Electron 6.x and 7.x

### ISSUE THREAD

**Issue by buu700** [electron/electron#21677]
Using Electron 4.x (4.2.12) worked as expected, but since updating to 6.x (6.1.7), as well as testing with 7.x (7.1.7), submitting our package to the Microsoft app store fails with the following message:

> Package acceptance validation error: The package file format for cyph.appx is invalid: Exception from HRESULT: 0x8051100F. Update the package and try again.

**Comment by codebytere** [comment]
@buu700 in order to properly triage this, we'll need to know how you configured the package in a reproducible manner. It may be that you're incorrectly packaging the app.

**Comment by buu700** [comment]
Got it. I'll look a bit more into this soon, but if it isn't something with an obvious root cause then it's possible that it's related to my use of [cordova-electron](https://github.com/apache/cordova-electron).

**Comment by codebytere** [comment]
Closing as there's been no more information for us to go on.

**Comment by buu700** [comment]
Whoops, sorry about the lack of follow-up @codebytere. Looks like we eventually got this sorted somehow in March. Upgrading to Electron 8 might have fixed it.
