### ISSUE TITLE
webview inside scaled div gets cropped

### ISSUE THREAD

**Issue by pakastin** [electron/electron#2168]
This is what's happening:
http://github.com/pakastin/electron-bug

**Comment by zcbenz** [comment]
This is a confirmed bug of Chromium:
https://code.google.com/p/chromium/issues/detail?id=492182

**Comment by pakastin** [comment]
Oh, thank you for the info - hope they'll fix it soon.. :/

**Comment by zcbenz** [comment]
Fixed with #6128.
