### ISSUE TITLE
Some processes remain alive in the background after main process crash

### ISSUE THREAD

**Issue by aabuhijleh** [electron/electron#21681]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  7.1.7
* **Operating System:**
  *  Windows 10 18362
* **Last Known Working Electron version:**
  *  6.1.7

### Expected Behavior

All processes should be killed if main process crashes.

### Actual Behavior

Some processes (`Renderer` and `crashReporter` processes to be exact) remain alive in the background eating up resources and can only be killed manually.

#### Repo
A crash will happen instantly and two processes will remain alive after it happens.
```sh
$ git clone https://github.com/aabuhijleh/electron-quick-start -b processes-alive-after-crash
$ npm install
$ npm start
```

#### Code
This sequence in the `preload` script somehow causes a crash in the main process. `Renderer` and `crashReporter` processes remain alive after it happens.
```js
mainWindow.minimize()
mainWindow.hide()
mainWindow.show()
```

### Screenshots

![Taskmgr_WwXMIsEmWG](https://user-images.githubusercontent.com/42934634/71802082-6f93aa80-3065-11ea-90a1-a29bf5005a3b.png)

### Additional information
If multiple crashes occur, you will see lots and lots of Electron processes running in the background and they never die.

This issue might seem related to #21614 but I can reproduce this behavior in my app by using `process.crash()` in the main process. My app is very complicated and this was the only way I could get this behavior to be reproduced in the simple quick-start repo.

The common thing between this simple repo and my app is that both use the `remote` module so that might be what's causing this.

**Comment by KarthikeyanKanniappan** [comment]
@aabuhijleh A Big Hello from India, Did you solved the issue which is happened to you !
