### ISSUE TITLE
Failed to clone submodule 'vendor/boto'

### ISSUE THREAD

**Issue by 215020267** [electron/electron#21691]
we failed to clone submodule 'vendor/boto'.  Could you please help take a look at this? Thanks in advance!

**Reproduce steps:**
1. git clone --recursive https://github.com/electron/electron D:\Electron\src
2. cd D:\Electron\src
3. set PATH=C:\Python\Python27;%PATH%
4. python script\bootstrap.py -v --target_arch=ia32 2>&1
  
**ErrorMessage:**
Running in verbose mode
Your Python is using TLSv1.2, which is sufficient for building Electron.
git submodule sync --recursive
Synchronizing submodule url for 'vendor/boto'
Synchronizing submodule url for 'vendor/breakpad'
Synchronizing submodule url for 'vendor/crashpad'
Synchronizing submodule url for 'vendor/depot_tools'
Synchronizing submodule url for 'vendor/gyp'
Synchronizing submodule url for 'vendor/libchromiumcontent'
Synchronizing submodule url for 'vendor/libchromiumcontent/vendor/boto'
Synchronizing submodule url for 'vendor/libchromiumcontent/vendor/depot_tools'
Synchronizing submodule url for 'vendor/libchromiumcontent/vendor/pyyaml'
Synchronizing submodule url for 'vendor/node'
Synchronizing submodule url for 'vendor/pdf_viewer'
Synchronizing submodule url for 'vendor/pdf_viewer/vendor/grit'
Synchronizing submodule url for 'vendor/requests'
git submodule update --init --recursive
Cloning into 'F:/gitP/electron/electron/vendor/libchromiumcontent/vendor/boto'...
remote: Repository not found.
fatal: repository 'https://github.com/piotrbulinski/boto.git/' not found
fatal: clone of 'https://github.com/piotrbulinski/boto.git' into submodule path 'F:/gitP/electron/electron/vendor/libchromiumcontent/vendor/boto' failed
Failed to clone 'vendor/boto'. Retry scheduled
Cloning into 'F:/gitP/electron/electron/vendor/libchromiumcontent/vendor/boto'...
remote: Repository not found.
fatal: repository 'https://github.com/piotrbulinski/boto.git/' not found
fatal: clone of 'https://github.com/piotrbulinski/boto.git' into submodule path 'F:/gitP/electron/electron/vendor/libchromiumcontent/vendor/boto' failed
Failed to clone 'vendor/boto' a second time, aborting
Failed to recurse into submodule path 'vendor/libchromiumcontent'
None
Traceback (most recent call last):
  File "script\bootstrap.py", line 300, in <module>
    sys.exit(main())
  File "script\bootstrap.py", line 36, in main
    update_submodules()
  File "script\bootstrap.py", line 145, in update_submodules
    execute_stdout(['git', 'submodule', 'update', '--init', '--recursive'])
  File "F:\gitP\electron\electron\script\lib\util.py", line 187, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['git', 'submodule', 'update', '--init', '--recursive']' returned non-zero exit status 1

**Comment by MarshallOfSound** [comment]
You appear to be trying to build a GYP version of Electron that is no longer supported.  Unfortunately we have no intention of supporting or fixing issues with the build system of those old release lines.

Try checking out and building master instead

**Comment by 215020267** [comment]
@MarshallOfSound  Thank you for your information. I use latest version 349da6af7f20a1199765508a454e941e616b9ad3 source code on master branch to build Electron on MSVC, but got the following error. Could you provide the new build steps or document for MSVC? The old one can not be used. Thanks in advance.

D:\Electron\src>python script\bootstrap.py -v --target_arch=ia32 2>&1
python: can't open file 'script\bootstrap.py': [Errno 2] No such file or directory

**Comment by MarshallOfSound** [comment]
https://github.com/electron/electron/blob/master/docs/development/build-instructions-gn.md
