### ISSUE TITLE
dev tools: unable to load source maps over custom protocol

### ISSUE THREAD

**Issue by bendemboski** [electron/electron#21699]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.7
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron version:**
  * 6.1.7

### Expected Behavior
When loading a Javascript file using a custom protocol, opening the dev tools should load the source maps.

### Actual Behavior
It does not load the source maps, and produces no error message other than an `ERR_UNKNOWN_URL_SCHEME` in the net log if net logging is enabled.

### To Reproduce
To see it work properly on Electron 6.1.7:
1. Run [this fiddle](https://gist.github.com/d0cb93e9c7d6ad198fe38db77038495a) on Electron 6.1.7
2. Open the dev tools
3. Note that `source map requested!` was logged to the main process console, and the source map for `test.js` (including `test.ts`) was loaded into the dev tools

To see it fail on Electron 7.1.7:
1. Run [this fiddle](https://gist.github.com/d0cb93e9c7d6ad198fe38db77038495a) on Electron 7.1.7
2. Open the dev tools
3. Note that `source map requested!` was not logged to the main process console, and neither `test.js.map` nor `test.ts` were loaded

### Additional Information
This is probably more fallout from Chromium's network service. When I enable net logging (`app.commandLine.appendSwitch('log-net-log', 'netlog.json')`), I see the following when opening the dev tools:

```
{"params":{"priority":"IDLE","traffic_annotation":129652775,"url":"serve://dist/assets/test.js.map"},"phase":1,"source":{"id":27,"type":1},"time":"20404995","type":2},
{"phase":1,"source":{"id":27,"type":1},"time":"20404995","type":103},
{"phase":2,"source":{"id":27,"type":1},"time":"20404995","type":103},
{"params":{"load_flags":0,"method":"GET","privacy_mode":0,"url":"serve://dist/assets/test.js.map"},"phase":1,"source":{"id":27,"type":1},"time":"20404995","type":99},
{"params":{"net_error":-302},"phase":2,"source":{"id":27,"type":1},"time":"20404995","type":99},
{"phase":1,"source":{"id":27,"type":1},"time":"20404995","type":107},
{"phase":2,"source":{"id":27,"type":1},"time":"20404995","type":107},
{"params":{"net_error":-302},"phase":2,"source":{"id":27,"type":1},"time":"20404995","type":2},
```

Note the `"net_error":-302` -- `-302` is `ERR_UNKNOWN_URL_SCHEME`, so somehow the network service(?) isn't aware of the standard scheme that was registered when trying to load `test.js.map`, even though `test.js` was successfully loaded using that same scheme.

This is currently preventing `ember-electron` apps from loading source maps on 7.x since `ember-electron` relies on a custom protocol to load the Ember app from the filesystem while still allowing Ember's web-based tooling (route recognition, web-style absolute asset URLs, etc.) to function.

**Comment by jean343** [comment]
I confirm that it works for 6.1.8 and does not work for 8.0.2.
It would be really nice to get this fixed. The protocol is amazing, but source maps are required.

Thanks,

**Comment by rhys-e** [comment]
Have the same problem, have worked around it in my case by configuring inline source maps. 

In weback:

`devtool: "inline-source-map"`

**Comment by MGraefe** [comment]
This is still broken in 2021, using Electron 11.2.0.

Error message is now: `DevTools failed to load SourceMap: Could not parse content for app://-/179.b2cf9c584eb328c35257.worker.js.map: Unexpected end of JSON input`

I'm serving the "website build" of our app using `electron-serve`.

network log shows still HTTP -302 (ERR_UNKNOWN_URL_SCHEME)

Inlining the source maps works but it's a rather ugly workaround.

**Comment by Simon-Laux** [comment]
+1

**Comment by bpasero** [comment]
Same issue for VSCode. We are about to change to a custom protocol and sourcemaps stop working.
