### ISSUE TITLE
There is no way to set the `--http-parser` NODE_OPTION in a packaged app

### ISSUE THREAD

**Issue by flotwig** [electron/electron#21693]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Problem Description

In a similar vein to #20831, some `NODE_OPTIONS` should be passable to packaged Electron apps. I think this list should include `--http-parser`.

`--http-parser` is not whitelisted for `NODE_OPTIONS` in packaged apps, but it should be, because Node 11.5.0 changed the default HTTP parser to one that breaks some use cases. See comment here for an explanation: https://github.com/cypress-io/cypress/issues/5602#issuecomment-571685626

### Proposed Solution

Whitelist `--http-parser=parser`.

### Alternatives Considered

- Don't know of any other potential alternatives besides writing a slow HTTP parser in Node.js and giving up the many conveniences that Node's HTTP parsing brings.

**Comment by codebytere** [comment]
Given the explanation above i'm happy to introduce this; i'll open a PR soon.
