### ISSUE TITLE
webContents.printToPDF rejects in v8.0.0-beta.5

### ISSUE THREAD

**Issue by jacobq** [electron/electron#21708]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

Note: related but different issues:

* #21603 -- that one was using the older (callback) API, but this is using the latest (promise) API (and #21639 appears to be a duplicate of that)
* #18093 -- in that case some output is produced, but here a rejection occurs (and the affected electron versions are different).
* #20634 -- that one never ends, but this one rejects shortly after the call occurs

### Issue Details

* **Electron Version:**
  * v8.0.0-beta.5 (also happens in 9.0.0-nightly.20191220 & 9.0.0-nightly.20200108)
* **Operating System:**
  * Debian (bullseye/sid) x64, 5.3.0 kernel
* **Last Known Working Electron version:**
  * 7.1.8, 8.0.0-beta.4, See [bisect](https://github.com/electron/electron/issues/21708#issuecomment-573079603)

### Expected Behavior
Calling `someBrowserWindow.webContents.printToPDF` should not throw exception / generate promise rejection.

### Actual Behavior
Calling `someBrowserWindow.webContents.printToPDF` rejects with `[Error: Failed to generate PDF]`.

### To Reproduce
Fiddle: https://gist.github.com/jacobq/cc5e5e1736b88cb32604f55369afd1c7
Repo: https://github.com/jacobq/electron-quick-start/tree/bug/print-to-pdf

```js
mainWindow.webContents.once('did-finish-load', async function() {
  try {
    const pdfData = await mainWindow.webContents.printToPDF({})
    console.log('Got PDF data -->', pdfData) // never gets here
  } catch(e) {
    // output --> Call to printToPDF threw exception [Error: Failed to generate PDF]
    console.error('Call to printToPDF threw exception', e)
  }
});
```

**Comment by jacobq** [comment]
FWIW I've started bisecting and 2ab56802cb9ea7549c9020731bdc69618e201f0c appears OK.

**Comment by jacobq** [comment]
@deepak1556 It looks like #21061 [skips the `printToPDF` test](https://github.com/electron/electron/pull/21061/commits/0c807679d73d7bde8f54270770873be185ba4fe6#diff-eef00a0036ba5095cf00426903a89251R1415
) and this is [still present](https://github.com/electron/electron/blob/2858471151cdf8627595bf006355fa3fe89280da/spec-main/api-web-contents-spec.ts#L1416-L1438) [in `master`](https://github.com/electron/electron/blob/master/spec-main/api-web-contents-spec.ts#L1416-L1438). Was this an oversight that was supposed to be taken care of before the PR landed?

**Comment by codebytere** [comment]
@jacobq i've tracked it down to https://chromium-review.googlesource.com/c/chromium/src/+/1917685 as the culprit; should hopefully have some more progress & answers soon!

**Comment by jacobq** [comment]
> @jacobq i've tracked it down...

Thanks for digging into this. When I discovered that it broke after a Chromium update I threw up my hands and didn't know what to do next (have not yet had to peel back that layer).

**Comment by codebytere** [comment]
@jacobq tracked it down - PR is up and it should be fixed in the next beta. Chromium is a complicated terror zone so it's not just you 😅
