### ISSUE TITLE
Electron 7.1.7 webContents.reloadIgnoringCache() & webContents.reload() Not working

### ISSUE THREAD

**Issue by orbitfum** [electron/electron#21701]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines]
* [x] I agree to follow the [Code of Conduct]
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
v7.1.7
* **Operating System:**
Windows 10, 1909
* **Last Known Working Electron version:**
v7.1.0 (upgraded from 7.1.0 to 7.1.7)

### Issue 
Trying to reload render nothing happens. 
This issue causes issue in "electron-reloader" package.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
