### ISSUE TITLE
window.flashFrame(true) and App.dock.bounce("critical") not working after a while.

### ISSUE THREAD

**Issue by indrolie** [electron/electron#21714]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * ^7.0.0
* **Operating System:**
  * macOS 10.15.1 & Windows 10 (1803)
* **Last Known Working Electron version:**
  * -

### Expected Behavior
For macOS, using App.dock.bounce("critical") should result in app bouncing constantly on the dock.
For windows, using windows.flashFrame(true) should result in app flashing orange constantly on the taskbar.

### Actual Behavior
For macOS, bouncing stops after a few seconds.
For windows, flashing stucks and only shows orange colour after a few seconds.

### To Reproduce
Run electron with below codes,  and after electron opened, switch/move to other app (so blur event will be triggered).
```
const electron = require('electron')
const App = electron.app
const Browser = electron.BrowserWindow

App.on('ready', () => {
    let win = new Browser({
        width: 1280,
        height: 720,
    })

    win.loadURL('https://google.com')
})

App.on('browser-window-blur', () => {
    console.log('blur..')

    setTimeout(() => {
        if (App && App.dock) App.dock.bounce("critical")

        Browser.getAllWindows().forEach(w => {
            w.once('focus', () => {
                w.flashFrame(false)
            })
    
            w.flashFrame(true)
        })
    }, 2000)
})
```

### Screenshots
How it looks like on windows. Flashing stucks at orange colour after a few seconds.
![image](https://user-images.githubusercontent.com/41278410/72061459-80177f80-3308-11ea-86ae-ac21f6f8455d.png)

**Comment by HirokiDaido** [comment]
we met the same problem with using ```w.flashFrame(false)```.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
