### ISSUE TITLE
dialog.showSaveDialog doesn't return anything

### ISSUE THREAD

**Issue by ShubhamKushwah** [electron/electron#21717]
So, I'm trying to create a simple Save Dialog, where the user can select a location and filename, and it will create a file at that specified location.

I've followed the docs, and also checked out some tutorials, the code is exact same, but apparently in my case when I open the dialog, select a location and click Save, I don't get any response back in the callback of dialog.showSaveDialog method.

Sorry if this is a noob mistake, I'm just starting into Electron.

Here's my code:
```
const { dialog } = require('electron').remote

const createBtn = document.getElementById('create_btn')

createBtn.addEventListener('click', async () => {
  console.log('First Response: ', await dialog.showSaveDialog())

  dialog.showSaveDialog(path => {
    console.log('Second Response: ', path)
  })
})
```

And here is the complete console log:
```
First Response:  {}
```

**Comment by jacobq** [comment]
* Issues here are for bug reports, not support requests. Please check out the electron community forum or Slack channel for help
* Please use the issue template -- you didn't even mention what version of electron you're using
* You appear to be attempting to pass a callback to `showSaveDialog`, but (assuming you're using the current version) that is not what [the docs specify](https://electronjs.org/docs/api/dialog#dialogshowsavedialogbrowserwindow-options).
* You appear to be not using the `Promise` returned by the call to `showSaveDialog`

Try something like:

```js
dialog.showSaveDialog({}).then((result) => {
  console.log('Second Response: ', result) // you probably want result.filePath
}).catch((...args) => {
  console.warn('failed/rejected with', args)
})
```

**Comment by ShubhamKushwah** [comment]
Thanks @jacobq. Sorry my bad.

But this is what I'm getting in response:
```
Second Response:  {}
```

I'm closing this issue, please help me here:
https://stackoverflow.com/questions/59668749/dialog-showsavedialog-doesnt-return-anything

**Comment by jacobq** [comment]
> I'm closing this issue, please help me here:

I posted an answer with a working example for you there. Good luck
