### ISSUE TITLE
Electron based apps are all suffering from rendering issues

### ISSUE THREAD

**Issue by ishirley34** [electron/electron#21712]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
* **Operating System:**
  * 
Windows 10 Home x64
* **Last Known Working Electron version:**
  * 

### Expected Behavior
The apps should render correctly

### Actual Behavior
If I leave the app alone, white pixels start appearing everywhere and it gets worse and worse

### To Reproduce

I have no idea how to reproduce the bug, it has just started happening out of nowhere and nothing seems to fix the issue. This is happening the twitch desktop app, Discord, and Slack apps. 

### Screenshots

![image](https://user-images.githubusercontent.com/20825005/72026786-61e74c00-3242-11ea-86f0-996ffd21248f.png)

![image](https://user-images.githubusercontent.com/20825005/72026796-6875c380-3242-11ea-846e-65ade8ef4278.png)

### Additional Information

Windows 10 Home x64
Z390 DESIGNARE
Intel Core i7-9700K
Nvidia GeForce RTX 2070

**Comment by jacobq** [comment]
I have seen this problem in the past (or something similar where the apps become "all black"), especially on Windows and especially with nvidia GPUs (e.g. #4380 #10239 #10863). See if you can run the apps with the `--disable-gpu` option. If so, does it resolve that problem? (Obviously this is not a "solution" as performance may be severely impacted)

**Comment by ishirley34** [comment]
Disabling hardware acceleration works on most apps. I believe the issue is related to the Nvidia drivers. I have been updating every time they come out but I still have this issue.

**Comment by codebytere** [comment]
Closing as this isn't something whose resolution lies with Electron, but rather in Chromium. If this continues to recur we suggest you instead open a crbug.com

**Comment by mrk3767** [comment]
I wanted to add some input here in case others run into it. As was mentioned above, this seems to be happening with NVIDIA GPUs. I ran into some similar issues with the FFXIV Teamcraft app. Going into the NVIDIA control panel, adding Teamcraft to the 3D customization settings panel, and disabling a bunch of features fixed everything. I didn't do a deep-dive into which one fixed it all.

**Comment by LielYeg** [comment]
Having the same problem,
Has anyone found a solution except disabling the gpu?
