### ISSUE TITLE
Electron 6/7: devtools console often keeps output from previous session after reload

### ISSUE THREAD

**Issue by bpasero** [electron/electron#21725]
### Issue Details

* **Electron Version:**
  * 6 and 7
* **Operating System:**
  * macOS, Linux
* **Last Known Working Electron version:**
  * 4.x

### Expected Behavior
Reloading the window should clear the devtools console.

### Actual Behavior
Sometimes devtools console keeps the output from the previous session.

### To Reproduce
* install latest Electron Fiddle
* Toggle Developer Tools
* Enable "Break on error" from the sources tab
* Add a breakpoint into `node_modules/@babel/runtime/helpers/interopRequireWildcard.js#17`
* hit Ctrl/Cmd+R
* => console does not clear anymore

Video proof:

![Peek 2020-01-10 11-28](https://user-images.githubusercontent.com/900690/72146325-7e979700-339c-11ea-95ff-7dd2495a606d.gif)

//cc @deepak1556

**Comment by bpasero** [comment]
It may be related: in VSCode development we often notice how we end up what seems to be a VM script instead of the actual file. Similar to this in the video:

![image](https://user-images.githubusercontent.com/900690/72146444-bbfc2480-339c-11ea-93cb-9f86c1c9bf83.png)

I think the two issues are connected.

**Comment by Kilian** [comment]
I think I have this issue too, in 8 and 9, where a page refresh will "detach" the devtools, and I need to close and re-open them before e.g. the correct element three is shown.

**Comment by bpasero** [comment]
One thing I learned is that this is related to the files I have opened in the "Sources" tab. Closing them all and then reloading gets me out of this issue.

**Comment by bpasero** [comment]
Not seeing this anymore since E9.
