### ISSUE TITLE
Cannot I/O

### ISSUE THREAD

**Issue by NKnife** [electron/electron#21726]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.8
* **Operating System:**
  * macOS 10.15

usually no problem, sometime connot i/o after a while. use `location.reload` can normalize
一般情况下能正常使用，偶尔会在过了一段时间后无法 i/o。只有使用 `location.reload` 才能正常

### Expected Behavior
![image](https://user-images.githubusercontent.com/18021554/72147427-73169100-33d9-11ea-87bc-f3a44d3cc7d3.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/18021554/72147187-f4b9ef00-33d8-11ea-9a2b-0dbecbf06156.png)

### Additional Information
i have `setTimeout` to polling i/o
有使用`setTimeout`去轮询读操作

**Comment by codebytere** [comment]
Unfortunately without a repro we can't triage this - please provide one so that we can begin to take a closer look.
