### ISSUE TITLE
EXC_BAD_ACCESS After closing child window

### ISSUE THREAD

**Issue by APshenkin** [electron/electron#21727]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 7.1.8
  * 
* **Operating System:** Mac OS X 10.15.2
  * 
* **Last Known Working Electron version:** 3.1.7
  * 

### Expected Behavior

Electron app don't crash after closing child window

### Actual Behavior

Sometimes Electron app crash after closing child window created using `nativeWindowOpen`. Looks like it could be because child window get focus after sending `.close()` (e.g. user click on this window)

### To Reproduce

```sh
$ git clone git@github.com:APshenkin/electron-crash-on-close.git
$ yarn
$ yarn develop
```
Usual this app creates child window, where user should save file. After choosing filepath, dummy file will be saved and child window should be closed automatically

Then in app:
1. There are 3 buttons. Each button will open child window.
2. Click any button, child window will appear
3. Click "Save key" button
4. Save dialog will be opened
5. Press "Enter" or "save" and then immedeately click on child window
6. Main window will crash 

### Additional Information

Crash Report https://gist.github.com/APshenkin/bf812f94d3ff1a1059d043091500c64f

**Comment by codebytere** [comment]
Closing as this no longer reproducible on latest supported versions.
