### ISSUE TITLE
Mac win.isVisible() returns different results between versions 4.1 & 6/7

### ISSUE THREAD

**Issue by Slapbox** [electron/electron#21737]
### Issue Details

* **Electron Version:**
  * `6.1.7` & `7.1.8`
* **Operating System:**
  * `macOS 10.13.6`
* **Last Known Working Electron version:**
  * `4.1.x`

### Expected Behavior
When the window is occluded `win.isVisible()` should return `false` as was the case in `electron@6`

### Actual Behavior
When the window is occluded `win.isVisible()` will return `true`. A window must be `minimized` or `hidden` to return `false`

### To Reproduce
Simply give `win.isVisible()` a try on an occluded window on macOS (at least on 10.13.6)

### Additional Information
Possible regression related to #17463 (?)

**Comment by Slapbox** [comment]
@sofianguy I updated some mistaken version info, this also affects `6.1.x`, not only `7`

I'm now guessing that #17463 is actually the cause.

On Mac, windows that were occluded used to return `false` but now return `true`, which seems backwards. Code that used to work cross-platform fails on Mac (and only Mac) in versions later than `electron@4.1.x` and the result of `isVisible` seems counter-intuitive.

**Comment by codebytere** [comment]
@Slapbox this is not a bug - the definition of visibility is visibility _on screen_ and not _full_ visibility, which is, by definition, true when it's occluded. The behavioral change i made in my old PR now means that it's returning visibility status correctly. However - i see what you're saying, and i understand why it might be important for you to take different pathways depending on a window's occlusion status. Would it help if i exposed an API method on BrowserWindows like `isOccluded` that returned this informatoin?

**Comment by Slapbox** [comment]
@codebytere thank you for your reply.

My individual use case was easy enough to work around since it was very old code where I really should have been using different logic anyway, but the discrepancy in behavior across OS's surprised me.

I think your suggestion sounds good though. Adding `win.isOccluded()` seems sufficient to avoid any confusion about the intended behavior.
