### ISSUE TITLE
Login event does not emit

### ISSUE THREAD

**Issue by gavinkalika** [electron/electron#21734]
I have an image tag with a camera ip ad get a HTTP 401. Before upgrading to version 7 the login event would be invoke and authentication would happen occur.

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  7.1.7
* **Operating System:**
  *  macOS 10.13.6
* **Last Known Working Electron version:**
  * 6.7

### To Reproduce

// html file
Add image tag "img  href="http://1.1.1.1/cameraFeed" to render in view

// main js
    app.on('login', (event, webContents, request, authInfo, callback) => {
        // perform auth - but never gets called
          callback(user,  password);
    });

**Comment by nornagon** [comment]
This looks like a duplicate of #20752. Can you try with v7.1.8?

**Comment by gavinkalika** [comment]
@sofianguy I tried again and get a error connection timeout.

I will check my local set up again.

Is there anymore info I can give you to make this info helpful?

**Comment by gavinkalika** [comment]
Actually this did not fix the issue. I still get the 401. 

Is there any helpful info that I can give you to reproduce this issue?

**Comment by gavinkalika** [comment]
turns out this was the answer:

https://electronjs.org/docs/api/protocol

I will close the ticket.
