### ISSUE TITLE
Promise not resolved for showMessageBox in 7.x

### ISSUE THREAD

**Issue by tessus** [electron/electron#21746]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v7.1.8
* **Operating System:**
  * macOS 10.14.6 (but I think it doesn't matter. I think it happens on all macOS versions)
* **Last Known Working Electron version:**
  * v6.1.7

### Expected Behavior
After the promise is resolved, the info should be printed to console.

For the code below, the output should be as follows (when clicking `cancel`):

```
1
false
```

### Actual Behavior
No output.

### To Reproduce

electron-fiddle: https://gist.github.com/29052c5b05035da099f64aabacb12374

Minimal example:

`test.js`

```
const {app, BrowserWindow, dialog} = require('electron');

let mainWindow;

app.on('ready', () => {
	mainWindow = new BrowserWindow({
		height: 200,
		width: 440
	});

	mainWindow.loadURL('file://' + __dirname + '/index.html');

  let options = {
    type: 'question',
		message: '-',
		buttons: ['Ok', 'Cancel'],
		defaultId: 1,
		cancelId: 1
  }

  options.message = 'message here (async)';
  dialog.showMessageBox(mainWindow, options, (response, checkboxChecked) => {
    console.log(response);        // not working
    console.log(checkboxChecked); // not working
  });
});
```

`node_modules/electron/dist/Electron.app/Contents/MacOS/Electron test.js`

**Comment by popod** [comment]
Use the promise version and not a callback : https://electronjs.org/docs/api/dialog#dialogshowmessageboxbrowserwindow-options which is depreciated since v7.x.x.

**Comment by tessus** [comment]
Oh, I only found examples in the form of:

```
  options.message = 'message here (async)';
  dialog.showMessageBox(mainWindow, options, (response, checkboxChecked) => {
    console.log(response);
    console.log(checkboxChecked);
  });
```

It would be nice to have at least one example in the docs which is not deprecated. Anyway, sorry for the noise.
