### ISSUE TITLE
Vue.js extension does not loaded if app.userAgentFallback is present

### ISSUE THREAD

**Issue by AssetKid** [electron/electron#21747]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.8
* **Operating System:**
  * Windows 10 (1909)
* **Last Known Working Electron version:**
  * 

### Expected Behavior

Vue.js extension should load.

### Actual Behavior

If `app.userAgentFallback` is assigned at the start of the application, the Vue.js extension does not load.

### To Reproduce

https://github.com/AssetKid/electron-quick-start

```sh
$ git clone https://github.com/AssetKid/electron-quick-start.git
$ npm install
$ npm start || electron .
```

### userAgentFallback not set
![image](https://user-images.githubusercontent.com/40426812/72228112-e1fc1180-35b4-11ea-8e18-5a5002b29f6b.png)

### userAgentFallback set

![image](https://user-images.githubusercontent.com/40426812/72228107-c2fd7f80-35b4-11ea-8691-3d1834060fa8.png)

### Additional Information

The React extension works just fine. This might be an issue with the Vue devtools extension.

**Comment by miniak** [comment]
This seems to be Vue.js extension issue, not Electron. Closing.
