### ISSUE TITLE
Auto Update Fail over 

### ISSUE THREAD

**Issue by HXavS** [electron/electron#21745]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

On a failed automatic updates, the electron app can crash and be in a non running state. See Issues from existing electron projects. This issue just occurred for me 1/12/2020. 

https://discuss.atom.io/t/unable-to-find-a-valid-app-error-windows-10/43318
https://github.com/desktop/desktop/issues/6486

### Proposed Solution

One Manual solution to this was to go to appData/Local/{application}/ and launch exe from previous version. The Auto Update ran again, but this time succeeded. My Proposed Solution is to automate this. On "unable to find app" error check for a launch previous version.

**Comment by MarshallOfSound** [comment]
This change should go into either of the Squirrel's not into Electron core and my understanding is on Windows at least this logic already exists nowadays

**Comment by q837477816** [comment]
Hi @MarshallOfSound , we also encountered the same issue when migrating from electron-updater to squirrel.windows-based auto-updater. If the app is exited before the "updater-downloaded" event is triggered, clicking the desktop icon will result in the app being unable to open. As @HXavS mentioned above, we have to go to appData/Local/{application}/ and launch exe from the previous version. Can you share some insights on this? Thanks in advanced
