### ISSUE TITLE
Electron 6 / 7: BrowserWindow is freeze on Window after hide and show again

### ISSUE THREAD

**Issue by thomasdao** [electron/electron#21753]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
BrowserWindow is freeze on Windows when we call `browserWindow.hide()` and then `browserWindow.show()`. After the window shows up again, user is unable to interact with it. This only happens for Electron 6 and 7. Electron 5 is ok - after calling `show()`, user can interact with it.

* **Electron Version:**
Electron 6.1.7 and 7.1.7
* **Operating System:**
Windows. Mac OS is ok.
* **Last Known Working Electron version:**
Electron 5

### Expected Behavior

After calling `show()`, the window is not freeze, user can interact with it

### Actual Behavior

The window is freeze.

### To Reproduce

Simply hide the browser window and show it again. This happens only on Windows.

**Comment by AssetKid** [comment]
Working just fine here in 6.x and 7.x on Windows 10 (1909).

Maybe add a fiddle or repo?

> For bugs that can be encapsulated in a small experiment, you can use Electron Fiddle (https://github.com/electron/fiddle) to publish your example to a GitHub Gist and link it your bug report.

> If Fiddle is insufficient to produce an example, please provide an example REPOSITORY that can be cloned and run. You can fork electron-quick-start (https://github.com/electron/electron-quick-start) and include a link to the branch with your changes.

**Comment by Slapbox** [comment]
@thomasdao please include the version numbers for the operating systems you're testing on. Not mentioning what version of Windows (including build number for Windows 10) is just asking for your issue to be ignored.

**Comment by thomasdao** [comment]
I think there are probably some issues upgrading from Electron 5 to 6/7 in my app. I still haven't figured it out what caused this freeze but I'm unable to reproduce with a fiddle so I'm closing this issue. Thanks all for your comments :)

**Comment by thomasdao** [comment]
I found out the freeze is not from electron but from `electron-devtools-installer`. Sorry for the false alarm.

https://github.com/MarshallOfSound/electron-devtools-installer/issues/122
