### ISSUE TITLE
Tray icon lose gradient and turns completely white/black when screen got blurred

### ISSUE THREAD

**Issue by Toinane** [electron/electron#21767]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  7.1.7
* **Operating System:**
  *  macOS 10.15.2

   

### Additional Information

I don't really know if its a bug or not, so I've come to ask for help on this.

I need to create an animated tray icon for my App. To do this, I create the icon beforehand with a canvas to use the Buffer api then to display the icon as a tray. It all works great for now. In my case, I display a whole grey circle with the progression in white on top (as you can see in the Expected picture).
The problem is that once I change screens, the icon is correctly visible on the second screen, but on the first screen, the traybar gets blurred and makes the icons a bit transparent. And in my case, I lose my gray effect and it turns my icon completely white.

When I remove the gray circle, I don't have any more issues and I get the result I'm looking for. But I'm losing the readability of the icon. See the next screenshot : 
<img width="203" alt="Screenshot 2020-01-14 at 17 18 58" src="https://user-images.githubusercontent.com/7584391/72361571-fd206b80-36f1-11ea-9d49-8c9337379594.png">

### Expected Behavior

<img width="225" alt="Screenshot 2020-01-14 at 16 38 29" src="https://user-images.githubusercontent.com/7584391/72359854-56d36680-36ef-11ea-8bd4-7033f6ea166a.png">
<img width="198" alt="Screenshot 2020-01-14 at 17 06 17" src="https://user-images.githubusercontent.com/7584391/72360444-4079da80-36f0-11ea-96c8-6507ab1f4d33.png">

Like the normal icon when I'm on the focused screen, my icon have a gray circle and a white.

### Actual Behavior

<img width="220" alt="Screenshot 2020-01-14 at 16 38 37" src="https://user-images.githubusercontent.com/7584391/72359862-59ce5700-36ef-11ea-87e8-466d3cb676e4.png">
<img width="196" alt="Screenshot 2020-01-14 at 17 06 30" src="https://user-images.githubusercontent.com/7584391/72360461-45d72500-36f0-11ea-96a3-03d8ecefdd49.png">

My icon, the first left one with "16 min" title, is completely white on dark theme and dark on light mode. I see the same problem with the Deepl icon on the right of mine. However, the Onedrive icon doesn't have this problem, it's keep the gray gradient. So I suppose it's not a mac issue.

### To Reproduce

Create a gradient nativeImage with a canvas and use it for a tray icon.
Switch screen on macOS to see.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
