### ISSUE TITLE
WebContents.print(): Print window is not modal (anymore)

### ISSUE THREAD

**Issue by dominic-simplan** [electron/electron#21768]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.9
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 2.0.12

### Expected Behavior
Print dialog should be modal, i.e. it should not be possible to focus the main electron window when the print dialog is open

### Actual Behavior
Print dialog is not modal, the main electron window can get the focus.

### To Reproduce
See this Electron fiddle: https://gist.github.com/dominic-simplan/b06df46006f921dcf9a8c44c5c14eab2

**Comment by codebytere** [comment]
This is unfortunately a function of Chromium's print code, as we simply plumb through information and invoke their existing trigger logic for creating per-platform native dialogs. If you'd like to see this changes, please open a crbug.com.

**Comment by dominic-simplan** [comment]
Hi @codebytere, thanks for looking at this issue and your explanation.
I am wondering how I should report this at the Chromium bugtracker, as I checked Chromium version 78.0.3904.0 (which is very close to the Electron V7 version) and the print dialog is modal and looks completely different from the print dialog I see in Electron. 
Are there two ways to call a print dialog in Chromium?

**Comment by CherryDT** [comment]
Yes there are - the other dialog is Ctrl+Shift+P in Chromium.

However, even this dialog is modal in Chromium! So, it's unclear how this should be requested from Chromium if apparently there it already works!
