### ISSUE TITLE
React Developer Tools devtools extension not working

### ISSUE THREAD

**Issue by andre-aktivconsultancy** [electron/electron#21766]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.7
* **Operating System:**
  * Ubuntu 19.10 x64

### Expected Behavior
When installing React Developer Tools extension I expect a "Components" and "Profiler tab to be present in the devtools.
### Actual Behavior
The extension is reported as installed by `BrowserWindow.getDevToolsExtensions()` but the tabs do not appear in the devtools. Version 4.2.0 was working correctly, but version 4.4.0 is having this issue.

### To Reproduce
https://github.com/andre-aktivconsultancy/electron-quick-start/tree/react-dev-tools-not-shown

```sh
$ git clone https://github.com/andre-aktivconsultancy/electron-quick-start.git -b react-dev-tools-not-shown
$ rm ~/.config/electron-quick-start/extensions -rf # force download of latest extension
$ npm install
$ npm start
```

**Comment by MarshallOfSound** [comment]
More recent versions of react devtools require react to actually be on the page in order for them to appear in devtools.

E.g. if you load https://ahfarmer.github.io/calculator/ it will show you the react "Components" tab

**Comment by lucasbaze** [comment]
> More recent versions of react devtools require react to actually be on the page in order for them to appear in devtools.
> 
> E.g. if you load https://ahfarmer.github.io/calculator/ it will show you the react "Components" tab

@MarshallOfSound Can you explain "actually be on the page" further? I'm on ReactDevTools version 4.10.1 and electron 9.0.5 and when I Inspect element within our electron app, I'm not seeing the components or profiler options. Can confirm successful load following: https://www.electronjs.org/docs/tutorial/devtools-extension
