### ISSUE TITLE
Electron symbol server is missing executable files

### ISSUE THREAD

**Issue by daveplunkett** [electron/electron#21778]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.9
* **Operating System:**
  * Windows 10 (1803)
* **Last Known Working Electron version:**
  * Unknown

### Expected Behavior
Using a Microsoft debugger to analyze an electron minidump file should result in a symbolic call stack. 

### Actual Behavior
The debugger fails to resolve symbols if the required electron executables are not available on the local system.  The debugger attempts to download the executable file from the symbol store, but none are available.  This can be fixed by adding executable files to the symbol store.  Each .pdb in the symbol store should have an associated .exe or .dll file added too.

### To Reproduce
1. Use Visual Studio to open an electron minidump file.  Make sure the executable that caused this crash is not on the local system.

2. Add https://electron-symbols.githubapp.com to the debugger symbol paths

3. Debug the crash, note that symbols are not resolved. 

### Screenshots
![image](https://user-images.githubusercontent.com/7943453/72389404-88dfcb00-36e5-11ea-80b5-769d48ceda1b.png)

**Comment by MarshallOfSound** [comment]
Can you provide more information on which symbol and the id of that symbol.  I know for a fact that `7.1.6` and `7.1.8` have working symbols on the symbol server as I was using VS2015 to analyze a dump file a few days ago.  This is probably a misconfiguration in your Visual Studio set up but without more information on what symbol it can't resolve we can't help

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by M956588010** [comment]
@MarshallOfSound 
Excuse me,my question is like as this.
But my dump file was generated by Ubuntu 16.04.6,I want to  analyze it by Visual Studio on Windows.
It doesn't work,the infomation is like the screenshots in the question.
So I want to know how to resolve it.
My Electron is 8.0.3.
Please help me ...
