### ISSUE TITLE
Visual studio 2013 community with update 4 doesn't exist. 

### ISSUE THREAD

**Issue by JoyDaheeCha** [electron/electron#21786]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 0.36.12
* **Operating System:**
  * WSL (linux2)
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior

According to the document(https://github.com/electron/electron/blob/v0.36.12/docs/development/build-instructions-windows.md) the prerequisite is visual studio 2013 with update 4. And it has to be community edition. 

### Actual Behavior

Download page of MSVS doesn't show Visual studio 2013 community with update 4. Instead it has vs 2013 community with update 4, vs express 2013 for desktop. 

I'm not sure if it is OK to use vs express 2013 for desktop, as I'm using it for building electron which is desktop app. 

Thank you for your help. 

### To Reproduce

The link to check available vs version is 
https://my.visualstudio.com/Downloads?q=visual%20studio%202013&wt.mc_id=o~msft~vscom~older-downloads

**Comment by MarshallOfSound** [comment]
> 0.36.12

That Electron version is beyond unsupported, my guess is msft have removed the download link for the required version of visual studio from their website

**Comment by JoyDaheeCha** [comment]
@MarshallOfSound Thank you for your reply. 
By the way, I must use electron 0.36.12 as it is used to build certain project made by other programmer.
Would it be OK to use VS express 2013 for desktop with update 4? Or can I use VS 2013 community with update 5?

Thank you for your help.
