### ISSUE TITLE
Cannot activate electron app in case it been on disconnected display

### ISSUE THREAD

**Issue by PaulTveritinov** [electron/electron#21787]
### Issue Details

* **Electron Version:**
  * 5.0.12
* **Operating System:**
  *  Windows 10 (1903)

### Preconditions:
Run an app and move to second (not primary) display.
Disconnect second display.

### Expected Behavior
Application moved to primary display

### Actual Behavior
- It's moved to primary display w/o title and border in case it was not minimized or maximized. Title and border restored after minimize and restore.
- User unable to activate app because of bounds are still on removed display and cannot be changed even from the app.

### To Reproduce
See Actual Behavior section.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
