### ISSUE TITLE
In a production environment, ctrl + shift + i can open the devtools.

### ISSUE THREAD

**Issue by y489436672** [electron/electron#21785]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * V7.1.7
* **Operating System:**
  * windows10 X64
* **Last Known Working Electron version:**
  * V7.1.7
### Expected Behavior
In a production environment, ctrl + shift + i cannot open the devtools.

### Actual Behavior
In a production environment, ctrl + shift + i can open the devtools. Is this an exception? How can I prevent it from opening, the previous version is normal, this problem will occur in versions after 7.1.X.

**Comment by pushkin-** [comment]
can you just set `webPreferences.devTools` to `false` in prod on the BrowserWindow?

**Comment by y489436672** [comment]
> 您`webPreferences.devTools`可以`false`在BrowserWindow上设置为prod吗？
yes. devTools: false
![image](https://user-images.githubusercontent.com/19664101/72494663-902ae400-385f-11ea-9eea-82e463f66a0e.png)

**Comment by MarshallOfSound** [comment]
`devTools: false`.  Note the capital "T"

**Comment by AdrianMrn** [comment]
Sorry for the necro, I didn't want to open a new issue for this. Is there any reason that I wouldn't want users to be able to open the developer tools? Our app is a paid one, so I suppose this could make it easier for malicious users to try and circumvent the trial mode without paying?
