### ISSUE TITLE
electron master gn build error

### ISSUE THREAD

**Issue by zimengle** [electron/electron#21782]
### Issue Details
```
../../electron/shell/browser/mac/atom_application_delegate.mm:36:60: error: too many arguments to function call, expected 0, have 5
  g_swizzle_imk_input_session->GetOriginalImplementation()(self, _cmd, range,
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~
1 error generated.
```
* **Electron Version:**
master
* **Operating System:**
 macOS 10.14.6 xcode 11.3

**Comment by zcbenz** [comment]
Can you try running `gclient sync --force`? The master branch builds fine on my machine and CI machines, I think your `src/` is synced to the commit used by Electron.

**Comment by codebytere** [comment]
@zimengle you should use https://github.com/electron/build-tools, and open any subsequent issues there.

**Comment by muraliran** [comment]
@zimengle -- did you resolve it? I am having exact same issue.
