### ISSUE TITLE
Part of screen “missing” when on-screen keyboard is hidden

### ISSUE THREAD

**Issue by jahrralf** [electron/electron#21780]
Electron version: 4.2.12
Operating system: Window 10
Device: MS-Surface 4 Pro 

**Expected behaviour**
The app resizes to full size after closing the on-screen keyboard

**Actual behaviour**
After hiding the on-screen keybord a white area is left below the html area of the app.

We have an electron app which is executed full-screen on Microsoft Surface Pro (W10). Most of the time when the on-screen keyboard is hidden everything works well, the electron app takes again 100% of the height. However, sometimes a white area is left when the keyboard is hidden.

We were able to get this also in dev mode with the development tools open, see linked image. The html area is not full height, a white area is left below it. Can you help us to get rid of this white area, please?

https://i.stack.imgur.com/Pixuz.png

**Comment by zeitlerquintet** [comment]
+1

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by jahrralf** [comment]
Short update, please excuse the delay. We updated to Electron 6 and did not have the issue any more, however, there was another but minor scrolling issue.

**Comment by y489436672** [comment]
@sofianguy @jahrralf 
This problem still exists in electron v10.4.3.  When the on-screen keyboard is turned on. The page moves up, but the window does not.

**Comment by y489436672** [comment]
![image](https://user-images.githubusercontent.com/19664101/117262673-18356280-ae84-11eb-8fa8-20a0265a5d58.png)

**Comment by MaxTt90** [comment]
This issue still remains in electron v8.5.5, running on Windows Surface tablet. Any ideas or workaround ?
