### ISSUE TITLE
Parent property on BrowserWindow doesn't seem to work properly

### ISSUE THREAD

**Issue by jjtfsalgado** [electron/electron#21799]
### Issue Details

* **Electron Version:**
  * 7.1.9
* **Operating System:**
  * Windows 10 Pro - 1809
* **Last Known Working Electron version:**
  * Not sure but it [was working at some point ](https://www.youtube.com/watch?v=l75UxvoRyI4) 

### Expected Behavior
As described on this [video](https://www.youtube.com/watch?v=l75UxvoRyI4) 

### Actual Behavior
The child window seems to be completely independent. The `parent` property on the `BrowserWindow ` doesn't seem to work at all.
 
[Video 1](https://jose-iplicit.tinytake.com/tt/NDAwMDg2Ml8xMjMwNjA5Nw)

Using multiple screens the child window opens on the main screen and ignores parent window position.

[Video 2 ](https://jose-iplicit.tinytake.com/tt/NDAwMDg1Nl8xMjMwNjA5MQ)

### To Reproduce
I've created a [repo](https://github.com/jjtfsalgado/electron-parent-issue) to demonstrate this issue (the repo that I've used for the videos)

**Comment by pushkin-** [comment]
The behavior you see in the video is specific to macs. See the note [here](https://www.electronjs.org/docs/api/browser-window#platform-notices).

Also, I don't think the window is guaranteed to appear on the same monitor as the parent. Is your second monitor the primary monitor by chance?

**Comment by jjtfsalgado** [comment]
thanks @pushkin-! yes, the second screen is my main screen. So the parent window is only meant to work on the mac? On windows doesn't seem to make any difference specifying it or not

**Comment by pushkin-** [comment]
@jjtfsalgado No, the `parent` property certainly works, but its behavior I guess in OS-dependent. On Windows, it will make the child window always on top of the parent window. Second, minimizing the parent window, will minimize the child window. I believe restoring the main window will also restore the child window.

Also, the child window doesn't get its own taskbar icon. It's considered part of the same application and uses the same icon as the parent window.

There's probably other differences.

As for the second issue, I'm guessing the window just launches on the primary monitor by default. If you need to launch on the same monitor as the main window, you'd probably have to add logic to do that (configure the child window bounds to match the main window, or something like that)

**Comment by jjtfsalgado** [comment]
Cheers @pushkin-! I will give it a go then 👍
