### ISSUE TITLE
Spellchecker is not working on Windows and Linux (Electron 8.0.0-beta.6)

### ISSUE THREAD

**Issue by dziudek** [electron/electron#21798]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.0-beta.6
* **Operating System:**
  * Windows 10 (1909), Ubuntu 19.04 x64 
* **Last Known Working Electron version:**
  * 8.0.0-beta.4

### Expected Behavior
If the `spellcheck` param is set to `true` in the `webPreferences` object for the BrowserWindow instance, the misspelled words should have visual indicator (dotted red bottom border). 

### Actual Behavior
The expected behavior occurs only on macOS 10.15, on Windows 10 and Ubuntu 19.04 the spellcheck feature is not working.

### To Reproduce
I have prepared a simple example of the non-working spellchecker Electron instance.

```sh
$ git clone https://github.com/dziudek/electron-8-spellchecker-test.git -b master
$ cd electron-8-spellchecker-test
$ npm install
$ npm start
```

### Screenshots
On Windows 10:

![72467988-709ea780-37dc-11ea-984f-5f966b124dff](https://user-images.githubusercontent.com/22004/72508764-906ab580-3846-11ea-923a-670a7e1782be.png)

On Ubuntu 19.04:

![Screenshot 2020-01-16 at 10 16 29](https://user-images.githubusercontent.com/22004/72510258-66ff5900-3849-11ea-8f64-7319b525970b.png)

On macOS 10.15:
![Screenshot 2020-01-16 at 10 09 22](https://user-images.githubusercontent.com/22004/72509690-5a2e3580-3848-11ea-9878-a141074817ba.png)

### Additional Information
I suppose that the issue is related to the hunspell-based platforms, as macOS has native spellchecker.

**Comment by dziudek** [comment]
Good news - I have checked the issue deeper and it seems that the problem exists only in beta 5 and beta 6 releases. In beta 2/3/4 versions spellchecking is working on my Windows 10.

I have updated the issue description with this fact. 

Maybe it is caused by Chrome version change? beta 4 uses Chrome 80.0.3955.0, beta 5 uses Chrome 80.0.3987.14 and beta 6 uses 80.0.3987.51.

**Comment by dziudek** [comment]
Another observation, but seems to be related to this issue so I am not creating a separate issue - even on macOS 10.15 on Electron v.8.0.0-beta.6 the `dictionarySuggestions` field from `params` in the `context-menu` event of `WebView` is always empty. On Electron v.8.0.0-beta.4 the issue not occurs and the array with dictionary suggestions is properly populated.

**Comment by dziudek** [comment]
Spellchecker in stable Electron v.8.0 is working fine in my example app for Windows 10 and Ubuntu linux, so I am closing this issue.

Thank you for your amazing work and bringing this feature as native API of Electron - I have spent a lot of time trying to implement it with use of 3rd party libraries and to be honest - it was a nightmare, and now it is easy to use :)

**Comment by sergeyd63** [comment]
any ideas why mine is not working?
we had third party spellcheck (electron-spellchecker), i removed it
now i have:
webPreferences: {
            spellcheck: true,

const ses = window.webContents.session
ses.setSpellCheckerLanguages(['en-US'])

using electron 8.0.0 stable on win10

thanks

**Comment by sergeyd63** [comment]
also, didn't work in your demo

**Comment by sergeyd63** [comment]
another thing i noticed is that moving to electron 8.0.0 from 6.1.7 the default os context menu stopped working

**Comment by steverandy** [comment]
I can't get the builtin spellcheck to work on Windows with v8.0.0 and v.8.1.0.
I'm using `<webview>` with webpreferences attribute `spellcheck=1`.
Is there any guide to set up the builtin spellcheck?
