### ISSUE TITLE
Windows communicating with each other

### ISSUE THREAD

**Issue by kevinsawicki** [electron/electron#218]
Is there an API for a window to emit an event on another window?

I'm looking to support dragging tabs from one window to another so I was going to emit an event to tell the window where the drag started to close the item when the drop happens on the other window.

Thanks!

**Comment by hackjutsu** [comment]
It looks like `processId = require('remote').getCurrentWindow().getProcessId()` is no longer valid in recent Electron release(1.7.x).

Is there any other way to get the renderer process's pid?

**Comment by kevinsawicki** [comment]
It looks like processId = require('remote').getCurrentWindow().getProcessId() is no longer valid in recent Electron release(1.7.x).

It is now `processId = require('remote').getCurrentWindow().webContents.getProcessId()` post Electron 1.0

**Comment by hackjutsu** [comment]
@kevinsawicki 

I got a pretty small number like 4 or 3, which looks more like an internal windows routing id other than an OS pid.

- Electron: 1.4.15
- MacOS: 10.12.5
