### ISSUE TITLE
Support for toolbar windows in windows

### ISSUE THREAD

**Issue by WebFreak001** [electron/electron#2180]
Right now `type: toolbar` is only supported on Linux, but Windows can have toolbars too. It would be nice to have because when a window is not a toolbar and is framed, there is some minimum width. This would enable toolbar windows like this:

![](http://i.webfreak.org/5C4FC1)

**Comment by hankbao** [comment]
+1 for this. Currently I found no way to set WS_EX_TOOLWINDOW to a BrowserWindow's window style in Windows.

**Comment by Mind-Reader** [comment]
Can anyone elaborate on what exactly type: toolbar does? documentation is very short.
