### ISSUE TITLE
Problem with child_process.exec(), start tabtip.exe is not shown

### ISSUE THREAD

**Issue by Cookie923** [electron/electron#21816]
* **Electron Version:**
  * 6.0.11
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 

### Expected Behavior
`exec("start tabtip.exe")` should open touch keyboard.

### Actual Behavior
 the TabTip.exe process is running,  but the keyboard is not shown and without any error. Before execate `exec()`, I have set this registry key.
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\TabletTip\1.7\EnableDesktopModeAutoInvoke=1
```
By the way, on node, exec("start tabtip.exe") is working...

### To Reproduce
1.open any Electron app
2.use 
```
const { exec } = require('child_process');
exec("start tabtip.exe");
```

3. start it

**Comment by niunaruto** [comment]
Have you solved your problem? Now I have to open the soft keyboard on win10, but I can't open it. Have you solved it?

**Comment by Cookie923** [comment]
> Have you solved your problem? Now I have to open the soft keyboard on win10, but I can't open it. Have you solved it?

Yep. I wrote a batch.

**Comment by Cookie923** [comment]
> Have you solved your problem? Now I have to open the soft keyboard on win10, but I can't open it. Have you solved it?

And you also need to make sure that the current window is out of focus.

**Comment by niunaruto** [comment]
May I see your code?

**Comment by Aveolela** [comment]
May I see your code?

**Comment by nohhhon** [comment]
> May I see your code?

a6dbc0b2ff918799c404fd92f172047c5b662d01

**Comment by nohhhon** [comment]
> May I see your code?

a6dbc0b2ff918799c404fd92f172047c5b662d01
