### ISSUE TITLE
Remove package-lock.json from .gitignore

### ISSUE THREAD

**Issue by Sti2nd** [electron/electron#21818]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

Hi, chiming by with a friendly reminder that package-lock.json is supposed to be committed to source control. Source: https://docs.npmjs.com/configuring-npm/package-lock-json.html

Just discovered that package-lock.json is ignored when I copied the root level gitignore at [electron/.gitignore](https://github.com/electron/electron/blob/master/.gitignore) to use it in my own electron project.

**Comment by codebytere** [comment]
This was done intentionally: https://github.com/electron/electron/commit/98c51dd6608a66bd35ca0db696824c8e31e985a4.
