### ISSUE TITLE
app.dock.hide() && app.dock.show() called in quick succession can duplicate icons

### ISSUE THREAD

**Issue by Slapbox** [electron/electron#21810]
**Edit: I'm guessing this is known and just unavoidable without some extra working around using the resolution of the promise returned from `dock.show()`?**

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** `7.1.9`
* **Operating System:** `macOS 10.13.6`
* **Last Known Working Electron version:** `Unk

### Expected Behavior
Duplicate app icons shouldn't be possible.

### Actual Behavior
Duplicate icons can accumulate. After quitting the application the extra icons remain and cannot be quit or force quit to get rid of them. Oddly, simply left-clicking them does get them to go away.

### To Reproduce
```js
  remote.app.dock.show();
  setTimeout(remote.app.dock.hide, 50);
  setTimeout(remote.app.dock.show, 100);
  setTimeout(remote.app.dock.hide, 150);
  setTimeout(remote.app.dock.show, 200);
  setTimeout(remote.app.dock.hide, 250);
```
> Note: `remote` not required, just easier

### Additional Information

If a user tries to force quit a zombie icon, macOS will prevent re-opening the app without the user acknowledging that it crashed last time, as it would if you actually force quit the app.

This should be easy enough for users to workaround, but I assume this isn't the intended behavior.

Edit: Simply checking for `!dock.isVisible()` before calling `dock.show()` is insufficient to prevent this behavior. The bug persists

The real world situation for this is an application that hides/shows with a global hotkey - a user may hit the hotkey by accident and then again to hide it, but they may end up with duplicated dock icons because of this quick action. I toggle back and forth 3x in the repro code above to ensure reproduction, but it can be reproduced with less.

![image](https://user-images.githubusercontent.com/6835891/72575960-398fcb00-389c-11ea-8a16-9f06309965b3.png)

**Comment by codebytere** [comment]
Unfortunately this is a `wontFix` on our end - not because we don't wish to but because for consumer apps, Apple as a company allows very little control over the Dock, and the way that an app exists on it. Apps can only set, by normal means, one of a few activation policies:
```
// The application is an ordinary app that appears in the Dock and may
// have a user interface.
[NSApp setActivationPolicy: NSApplicationActivationPolicyRegular];

// The application does not appear in the Dock and does not have a menu
// bar, but it may be activated programmatically or by clicking on one
// of its windows.
[NSApp setActivationPolicy: NSApplicationActivationPolicyAccessory];

// The application does not appear in the Dock and may not create
// windows or be activated.
[NSApp setActivationPolicy: NSApplicationActivationPolicyProhibited];
```
but we in Electron want to provide you more granular access, so we hook into slightly [lower level components](https://github.com/electron/electron/blob/9b01bb00d2337283d5a1d0eb9d867ced1211d3ea/shell/browser/browser_mac.mm#L317-L323). Unfortunately, the above is a side effect of us allowing you to have more control at all. As such, i'm going to label this a `wont-fix` and close it out.

**Comment by Slapbox** [comment]
Totally understand and I appreciate your thorough explanation @codebytere. Thank you for taking the time.

**Comment by rtharston** [comment]
There is a [Medium post](https://medium.com/@jackymelb/show-hide-dock-icon-on-macos-app-3a59f7df282d) with a solution to this problem from 2017 that has a workaround for the many icons issue.
