### ISSUE TITLE
can't run

### ISSUE THREAD

**Issue by wyxhh** [electron/electron#21824]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
* **Operating System:**
  * 
* **Last Known Working Electron version:**
  * 

### Screenshots

<img width="417" alt="image" src="https://user-images.githubusercontent.com/51747865/72661397-55b67800-3a14-11ea-8b98-5afbffb838e5.png">
![V(@QY`UGSO}E8FSG RTZ 3T](https://user-images.githubusercontent.com/51747865/72661405-7aaaeb00-3a14-11ea-8db9-fa03c316ef01.png)

**Comment by pushkin-** [comment]
um, this is not enough info to be able to diagnose the issue. Also, the crash is happening in an opencv python script, so why do you suspect that Electron is the culprit?

**Comment by codebytere** [comment]
I'm closing this as the template has not been filled (which would not normally lead to closure) but the error attached above is in python only, with no clear link to Electron at all. Should something change, we'll be happy to revisit this issue.
