### ISSUE TITLE
Javascript Require function

### ISSUE THREAD

**Issue by HorseGlass** [electron/electron#21836]
**Hi!**
I tried to use **`require('electron')`** on renderer side but it returns an error:
**`Uncaught ReferenceError: require is not defined`**
But on other projects I looked at it had no problem with only using Electron.
For example there is [Electron samples](https://github.com/electron/simple-samples) and I tried it my self and it worked. But in my own project i've got the error.
Any ideas? What could be the problem?

**Comment by circutrider21** [comment]
I have encountered the same problem a few weeks ago. The problem is that the electron doesn't scan files except for the main file that invokes and creates a instance of electron. if i am wrong, feel free to correct me.

**Comment by HorseGlass** [comment]
I managed to do it. I've just had to create a preload file and load ipcRenderer front there

**Comment by circutrider21** [comment]
**Your Solution Works!!!**. Thanks by the way
