### ISSUE TITLE
checkboxChecked still not working in 7.1.9

### ISSUE THREAD

**Issue by RoderickQiu** [electron/electron#21831]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, **only found a [closed issue](https://github.com/electron/electron/issues/21159) that doesn't works**.

### Issue Details

* **Electron Version:**
  * 7.1.9
* **Operating System:**
  * Windows 10, 1809

### Expected Behavior
The `checkboxChecked` property of dialog boxes should works in the promise.

### Actual Behavior
It doens't work when the `checkboxChecked` is set to be false, it works when `checkboxChecked` is set to be true.
This problem is said to be solved, but it hasn't been...

### To Reproduce
@jrdiard gave a example in the old and closed 21159 issue,
with the fiddle code in main.js:
```
const { app, BrowserWindow, dialog } = require('electron')

let mainWindow = null

app.on('ready', () => {
  mainWindow = new BrowserWindow({ height: 600, width: 600 })

  var ret = dialog.showMessageBox(mainWindow, {
    type: "question", buttons: ["Yes", "No"],
    message: "Do you want to run the demonstration scenes?",
    cancelId: 1,
    checkboxLabel: "Save images for each scene", checkboxChecked: true, noLink: false
  });
  ret.then((val) => {
    console.log("Run Demo: " + val.response + " Save scenes: " + val.checkboxChecked);
  });

})
```

**Comment by RoderickQiu** [comment]
I'll try to solve it first...

**Comment by RoderickQiu** [comment]
In the [pull request 21248](https://github.com/electron/electron/pull/21248/files), the file they edited is the `shell/browser/ui/message_box_win.cc`, and for the line 186, the code is:
```
BOOL verificationFlagChecked = FALSE;
  TaskDialogIndirect(&config, &id, nullptr, &verificationFlagChecked);

  if (id_map.find(id) != id_map.end())  // common button.
    button_id = id_map[id];
  else if (id >= kIDStart)  // custom button.
    button_id = id - kIDStart;
  else
    button_id = cancel_id;

  return std::make_pair(button_id,
                        checkbox_checked ? verificationFlagChecked : false);
```
So when checkbox_checked is true, it returns verificationFlagChecked, or it'll return false.
I didn't really find how the checkbox_checked and verificationFlagChecked properties are changing, but I'm guessing that this could be the thing which is wrong?

**Comment by RoderickQiu** [comment]
Hey anyone here

**Comment by codebytere** [comment]
@RoderickQiu as you can see, we have about 1250 issues, and so we would appreciate if you would exercise some patience as we work to triage and address your issue. We will work to address it as soon as we are able.
