### ISSUE TITLE
How to debug "DevTools was disconnected from the page" + white screen?

### ISSUE THREAD

**Issue by MaxYari** [electron/electron#21834]
As per subject, I have electron react app which on my first machine works just fine through `electron app.js` as well as from .exe after being built. Yet on the second PC (win 10 as well, but AMD cpu instead of intel) while running build app (haven't tried raw version) after a bit of runtime (5-20sec) chromium just goes white and dev tools show "DevTools was disconnected from the page ... " message. There are no errors neither in chrome devtools as well as main electron process console (was running app's exe through cmd to see electron console output).
So the question is - using what tools and how I can get specific report of what happened to which part of electron and why?

On a side note: I saw multiple speculations on the net regarding why this could happen, including the possibility that performance heavy code somehow can cause this, the mere idea of which sounds quite strange to me honestly, I think it's quite reasonable to expect app to run fine no matter the load, assuming no exceptions were caused by faulty code. And yes my app does run some "heavy" calculations "threaded" using 4 workers, but again, this wasn't an issue on the first machine.

**Comment by MaxYari** [comment]
> crashreporter

A link? An extended explanation? Or at least a few work about what is it at all and how it's applicable to debugging electron's chromium process white screen?

**Comment by MaxYari** [comment]
Do you mean this thing: https://electronjs.org/docs/api/crash-reporter ?

**Comment by hxkuc** [comment]
it can used in renderer process，but it not very useful

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by xiajingren** [comment]
Is there any progress on this issue? I'm also troubled by this issue

**Comment by YQOpenSource** [comment]
You can see all logs of electron by run electron as following:
```bash
export  ELECTRON_ENABLE_LOGGING=1  electron .
```
