### ISSUE TITLE
registering "Capslock" as globalShortcut does not work on mac

### ISSUE THREAD

**Issue by jsphweid** [electron/electron#21830]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
v5.0.13
v6.1.7
v7.1.9

* **Operating System:**
macOS 10.15.2

### Expected Behavior
putting this in `app.on("ready", () => ` should print out `is registered true` on boot up in the terminal and `hello WRLD` every time Capslock is pressed.
```javascript
  globalShortcut.register("Capslock", () => {
    console.log('hello WRLD' )
  });

  console.log("is registered", globalShortcut.isRegistered("Capslock"));
```

### Actual Behavior
`is registered true` prints out when it boots, but `hello WRLD` never prints out, i.e. the callback is never seemingly executed.

### To Reproduce

1. clone https://github.com/szwacz/electron-boilerplate
2. `npm install`
3. `npm install -D electron@5` (or 6 or 7)
4. add above code chunk to the `app.on("ready", () => ` 
5. `npm start`
6. observe terminal and compare with "Actual Behavior" section above.

### Additional Information
Other hotkeys DO work just fine.

I used to use Seil/Karabiner (programs that can manipulate the behavior ofcapslock) on this machine but both have been uninstalled.

Mac allows you to change Capslock in the System Preferences, experimenting with the Capslock behavior a bit. However, I've noticed that it doesn't seem to make a difference whether it's on the default or "No Action"

**Comment by erickzhao** [comment]
Just tested on 5.0.0-beta-3 (first version that #16725 landed) and can also reproduce this issue.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
