### ISSUE TITLE
Symbols & Emojis not displayed properly after build and install

### ISSUE THREAD

**Issue by robbylucia** [electron/electron#21833]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * "5.0.10"
"electron-builder": "22.2.0",
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * ?

### Expected Behavior
ℹ️ is displayed

### Actual Behavior
â„¹ï¸ is displayed

### To Reproduce
Put ℹ️ or other emoji or symbol on a page displayed with your electron app. Build it, run the .EXE file to install and run it, and you will see weird text instead of the actual symbol.

### Additional Information
If this is not an electron bug please close and redirect me to where I should create an issue or how to fix. Thank you!

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.
