### ISSUE TITLE
no-sandbox argument conflicts with  stdio ipc when electron process is spawned from regular node process

### ISSUE THREAD

**Issue by bruceauyeung** [electron/electron#21845]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.1.4
* **Node Version:**
  * v12.13.1
* **Operating System:**
  * centos 7.4
* **Last Known Working Electron version:**
  * don't know

### Expected Behavior
 devtools in `electron` window is opened by default, and it can  be opened via pressing  `CTRL+SHIFT+I`
 or clicking menu item `view -> Toggle Developer Tools`.

### Actual Behavior
 devtools in `electron` window is NOT opened by default, and it can not be opened neither via pressing  `CTRL+SHIFT+I`
 nor via clicking menu item `view -> Toggle Developer Tools`.

### To Reproduce
demo repo:  https://github.com/bruceauyeung/electron-issue-0
~~~
# run the following commands as non-root user
git clone https://github.com/bruceauyeung/electron-issue-0.git
cd electron-issue-0
yarn install
node start-electron.js
~~~

quick explanations:
in file `start-electron.js`  i try to spawn an electron process 
~~~
var path = require('path');
var child_process = require('child_process');
var electron = require('electron');

var entry = path.join(__dirname, './start-electron-index');
var args = ['--no-sandbox', entry];
var proc = child_process.spawn(electron, args, { stdio: ['ipc'],});
~~~

1. if i remove '--no-sandbox' and leave `stdio: ['ipc']` untouched , devtools can be opened as expected.
2. if remove ` { stdio: ['ipc'],}` and leave `'--no-sandbox'` untouched,  devtools can also be opened as expected.

### Additional Information
1. also tested on windows 7 64bit with node 12.4.0,  and worked as expected.
2. i tried to test this bug with electron 7.1.9, but when i run `node start-electron.js`, there is an error thrown out:
>\# node start-electron.js
>/root/electron-issue-0/node_modules/electron/index.js:14
>    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
>    ^
>
>Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
>    at getElectronPath (/root/electron-issue-0/node_modules/electron/index.js:14:11)
>    at Object.<anonymous> (/root/electron-issue-0/node_modules/electron/index.js:18:18)
>    at Module._compile (internal/modules/cjs/loader.js:959:30)
>    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
>    at Module.load (internal/modules/cjs/loader.js:815:32)
>    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
>    at Module.require (internal/modules/cjs/loader.js:852:19)
>    at require (internal/modules/cjs/helpers.js:74:18)
>    at Object.<anonymous> (/root/electron-issue-0/start-electron.js:5:16)

**Comment by bruceauyeung** [comment]
@MarshallOfSound would you mind take a look ?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
