### ISSUE TITLE
Electron 7: restoring minimised windows shows blank for a brief moment

### ISSUE THREAD

**Issue by bpasero** [electron/electron#21844]
### Issue Details

* **Electron Version:**
  * 7.x
* **Operating System:**
  * macOS 10.15.2
* **Last Known Working Electron version:**
  * 6.x

### Expected Behavior
Restoring a window that was minimized should show the contents instantly. 

### Actual Behavior
Restoring a minimized window shows its contents blank for a brief moment.

### To Reproduce
* install Electron fiddle
* open it
* minimize via `Cmd+M`
* click the dock icon

**Comment by MarshallOfSound** [comment]
I believe this was fixed in https://github.com/electron/electron/pull/21750 can you try the most recent 7.x release, I can't repro it on my machine

**Comment by bpasero** [comment]
@MarshallOfSound great to hear, will report back asap when I can verify this.

**Comment by bpasero** [comment]
Yes, confirmed.
