### ISSUE TITLE
" cmd+` " does not switch windows when using the French keyboard layout

### ISSUE THREAD

**Issue by alexdima** [electron/electron#21847]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.8
* **Operating System:**
  * macOS 10.15.2
* **Last Known Working Electron version:**
  * ?

### Expected Behavior
* When using the French keyboard layout on a mac with ISO keyboard, `` cmd + ` `` should switch application windows, as it does in TextEdit or in Chrome or as it does when using the US or the US Intl keyboard layout.

### Actual Behavior
* Pressing `` cmd + ` `` has no effect: 
![Kapture 2020-01-21 at 11 29 39](https://user-images.githubusercontent.com/5047891/72797673-d73f1d80-3c41-11ea-8f8f-086b2c328198.gif)

### To Reproduce

* In Electron Fiddle, use the following snippet which creates two windows instead of one:
```js
const {app, BrowserWindow} = require('electron')

let firstWindow, secondWindow;

function createWindow () {
  firstWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: { nodeIntegration: true }
  });
  firstWindow.loadFile('index.html');
  firstWindow.on('closed', function () {
    firstWindow = null
  })

  secondWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: { nodeIntegration: true }
  });
  secondWindow.loadFile('index.html');
  secondWindow.on('closed', function () {
    secondWindow = null
  })
}

app.on('ready', createWindow)
app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', function () {
  if (firstWindow === null) {
    createWindow()
  }
})
```

**Comment by clavin** [comment]
It seems this bug was fixed with #27701! I tested this in #17287 with the "French" keyboard layout.
