### ISSUE TITLE
Windows 10 on ARM issues

### ISSUE THREAD

**Issue by MehediH** [electron/electron#21877]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  7.1.10
* **Operating System:**
  * Windows 10 (1903)
* **Last Known Working Electron version:**
  * N/A

### Issue

The documentation for Electron on Windows on ARM is slightly broken. On the "Linking against the  correct node.lib" [section](https://github.com/electron/electron/blob/master/docs/tutorial/windows-arm.md#linking-against-the-correct-nodelib), the download link for the arm64 version of `node.lib` leads to a 404. And without linking against the correct `node.lib`, I am unable to compile my app for ARM64. It works just fine for x64, as expected.
 
Also, and this is possibly a separate problem from this, but I don’t have a node-gyp  folder in `%AppData%/Local` at all. Any ideas?

Thank you.

**Comment by codebytere** [comment]
cc @jkleinsc ☝️

**Comment by jkleinsc** [comment]
The 404 error has been resolved in the latest documentation.
