### ISSUE TITLE
Electron Slack channel

### ISSUE THREAD

**Issue by Nitingadhiya** [electron/electron#21884]
Hello Everyone,

I'm recently started working on electron application project. so i wish can join electron community in Slack channel. 
so we Gain / Share knowledge with community. 
Thanks.

**Comment by codebytere** [comment]
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
