### ISSUE TITLE
Cannot access `electron.remote.app` in Electron application via DevTools?

### ISSUE THREAD

**Issue by deadcoder0904** [electron/electron#21885]
I want to access

```js
var app = require(‘electron’).remote.app
```

via DevTools in an Electron Application.

Right now, when I open up DevTools & type in

```js
var app = require(‘electron’).remote.app
```

I get an error:

> Uncaught Error: Blocked remote.getBuiltin(‘app’)

I also checked out https://github.com/electron/electron/issues/20900#issuecomment-549281149 but I guess the use-case is different.

I want to access it from the DevTools.

For example, I opened VSCode then opened its DevTools and typed

```js
var { app } = require(‘electron’).remote.require(‘electron’)
```

& it gave me the error:

> Uncaught Error: Blocked remote.require(‘electron’)

How do I access the `app` variable via DevTools? I don’t want to access it via code. Is it even possible?

**Comment by pronebird** [comment]
Sounds like a really bad idea. Why not set up IPC and send a signal to the app to do something?

**Comment by deadcoder0904** [comment]
@pronebird why is it a bad idea? really curious?

> Why not set up the IPC handler and send a message to the main process to do something?

Like I said I’m not trying to write code. I want to access already installed apps like VSCode.

On further thinking, I do think it’s not possible with packaged apps in production but it’s possible to do in development.

**Comment by codebytere** [comment]
@deadcoder0904 this isn't an issue with Electron - this is the app itself blocking you from doing that for clear security reasons.

**Comment by deadcoder0904** [comment]
Thought so too. Thank you @codebytere for clearing it up :)
