### ISSUE TITLE
Proposal: Enable `contextIsolation` by default in Electron 9

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#21887]
We now have the [`contextBridge`](https://www.electronjs.org/docs/api/context-bridge) module that makes the barrier of entry for `contextIsolation` dramatically smaller.

Let's turn on `contextIsolation` by default in Electron 9

cc @electron/gov

**Comment by malept** [comment]
* The [security docs](https://www.electronjs.org/docs/tutorial/security#3-enable-context-isolation-for-remote-content) will need to be updated.
* Should those docs also link to the `contextBridge` docs as well?

**Comment by MarshallOfSound** [comment]
Plan of action in #23506
