### ISSUE TITLE
Protocol handlers no longer working when registered from render process

### ISSUE THREAD

**Issue by ronny1982** [electron/electron#21896]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.x.x
* **Operating System:**
  * any
* **Last Known Working Electron version:**
  * 6.1.7

### Expected Behavior
Protocol handlers registered from the render process are expected to work exactly as in the previous version, or if deprecated/removed this should be listed in [breaking changes](https://www.electronjs.org/docs/api/breaking-changes#planned-breaking-api-changes-70)

### Actual Behavior
After registering a protocol handler from the renderer process, requests using the handler will fail with the following message:

> Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME

### To Reproduce

```sh
git clone https://github.com/ronny1982/electron-21896.git .
npm run v6
# See output and close window
npm run v7
# See output and close window
```

### Screenshots

<details>
<summary>Migration Same Code (6.1.7 => 7.1.10)</summary>

----

Electron v6.1.7
![image](https://user-images.githubusercontent.com/27136773/73120688-ad536700-3f71-11ea-9f3f-21b94bcb7a3a.png)

Electron v7.1.10
![image](https://user-images.githubusercontent.com/27136773/73120677-7ed58c00-3f71-11ea-8dc4-5fe456f1de11.png)

</details>

### Additional Information

-

**Comment by nornagon** [comment]
custom protocols must be registered before the `ready` event is emitted.

https://www.electronjs.org/docs/api/breaking-changes#privileged-schemes-registration

**Comment by ronny1982** [comment]
> custom protocols must be registered before the `ready` event is emitted.
> 
> https://www.electronjs.org/docs/api/breaking-changes#privileged-schemes-registration

The linked breaking changes are for version 5, but the example code still worked in 6.1.7
Furthermore the breaking changes for version 5 are only referring to registering standard schemes and not to the [registration of the buffer protocol handler](https://www.electronjs.org/docs/api/protocol#protocolregisterbufferprotocolscheme-handler-completion).

The given example registers the standard schemes correctly before the ready event. There are no documented restrictions when to register the protocol buffer handler.

**Comment by nornagon** [comment]
ah sorry, i misread the issue. in general we recommend avoiding the remote module (it's [soon to be deprecated](https://github.com/electron/electron/issues/21408), but the behavior you're describing does sound odd.

**Comment by ronny1982** [comment]
Teardown sample repository, use [electron-21896-master.zip](https://github.com/electron/electron/files/4880992/electron-21896-master.zip) for reproduction

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
