### ISSUE TITLE
Electron menu vertically extends past application window

### ISSUE THREAD

**Issue by reZach** [electron/electron#21903]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.9
* **Operating System:**
  * Windows
* **Last Known Working Electron version:**
  * Unknown

### Expected Behavior
I expect the menu to not extend past the application window.

### Actual Behavior
The menu extends past the application window if the number of menu items is larger than the window.

### To Reproduce
Create a menu with a large number of menu items.

### Screenshots
![image](https://user-images.githubusercontent.com/4740370/73145259-305be680-4072-11ea-939c-31995cc994a2.png)

**Comment by codebytere** [comment]
We delegate to Chromium for this functionality, so i suggest that you open a crbug.com about it. Until they handle it, there's unfortunately nothing we can do to mitigate it without patching into Chromium in a way that isn't feasible for us to maintain.

**Comment by reZach** [comment]
Thanks @codebytere, I've [logged a bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1047506).
