### ISSUE TITLE
Electron freezes on Linux if app tries to send a notification and no notification daemon is running.

### ISSUE THREAD

**Issue by zenhack** [electron/electron#21912]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.9
* **Operating System:**
  * Arch Linux (current as of Jan 2020)
* **Last Known Working Electron version:**
  * Unknown

In #7831, @ckerr suggested opening a new issue to track the problem Linux users were having. I was unable to find an issue so I'm opening one.

In summary: On Linux, if an app tries to send a notification and there is no notification daemon running, electron will lock up, and it becomes necessary to kill the process.

In my case I'm seeing this on the riot.im app, but if you look at the old issue there are numerous bugs from other projects that point to it, so it is clear that this affects many other applications.

### Expected Behavior

Most likely in this case the notification should just not appear (since there is no way to deliver it) but the app should continue operating. From a developer perspective it may make sense to report the error to the caller, but I'm a user in this case and unfamiliar with the APIs.

### Actual Behavior

The app locks up entirely, and must be killed.

### To Reproduce

On a Linux system, make sure there is no notification daemon running and trigger a notification. In my case I am using the sway compositor for wayland, which does not launch a daemon by default.

**Comment by NickEckardt** [comment]
This issue causes problems in Signal-Desktop: https://github.com/signalapp/Signal-Desktop/issues/2567

**Comment by vladimiry** [comment]
@NickEckardt also see https://github.com/electron/electron/issues/21415.

**Comment by NickEckardt** [comment]
@vladimiry The issue completely resolved itself when I turned off notifications in signal-desktop. I was only experiencing the freezes on moments when I should have been getting notifications. I'm pretty sure that is a different issue which I'm not experiencing.

**Comment by Kellegram** [comment]
> @vladimiry The issue completely resolved itself when I turned off notifications in signal-desktop. I was only experiencing the freezes on moments when I should have been getting notifications. I'm pretty sure that is a different issue which I'm not experiencing.

Same for me. Disabling notifications completely prevents ANY freezes.

**Comment by TheEvilSkeleton** [comment]
Any update?

**Comment by Kellegram** [comment]
This seems to date back 3 years? I guess this is never getting fixed?

**Comment by leifmadsen** [comment]
Work around: run `dunst` or another notification system to work around the issue. Disabling notifications didn't seem to totally solve it for me.

```
dunst -config ~/.config/dunst/dunstrc &
```

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by EvanCarroll** [comment]
This problem still exists on Debian trixie with the latest versions of `signal-desktop` and Discord

**Comment by Vendicated** [comment]
I created a new issue since this is still an issue today, see ^

**Comment by R8bert** [comment]
Confirm that is still an issue on Fedora 43
