### ISSUE TITLE
Session.cookies.set throws Setting cookie failed error

### ISSUE THREAD

**Issue by jarrodek** [electron/electron#21919]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v7.1.10
* **Operating System:**
  * macOS 10.14.6 (18G2022)
* **Last Known Working Electron version:**
  * not sure, but it was working before

### Expected Behavior
Cookie is set.

### Actual Behavior
When trying to set a cookie I am getting the following error: `Error: Setting cookie failed`. 
Unfortunately there's nothing else. I was trying to debug it myself but the function is a `native code` so I can't take a look of what is happening.

### To Reproduce
This is tricky. I have a separate module that handles cookies. It uses the same version of Electron. In this module tests are passed and cookies are set. However, when I use the same module in the final application then it starts behaving unexpectedly. Whatever the cookie configuration is it always throws an error.

I even try to use the example from the documentation and it fails as well:

```javascript
const sis = session.fromPartition('persist:web-session');
const cookie = { url: 'http://www.github.com', name: 'dummy_name', value: 'dummy' };
sis.cookies.set(cookie)
.catch((e) => {
  console.error('ERROR SETTING COOKIE');
  console.error(e);
});
```

I use different partition as this cookies should not be mixed with the application cookies. The application is API testing tool so it's important to me to keep them separated.

Because it works in a separate module but it does not in the application it means that I have some configuration that prevents setting a cookie. So the ask to you is to describe cases when this error can occur. Maybe I'll be able to figure it out.

**Comment by jarrodek** [comment]
This seems to be working in electron@8.0.0-beta.7.

**Comment by sofianguy** [comment]
@jarrodek I'm going to close this for now, but feel free to reach out if you are experiencing this issue again
