### ISSUE TITLE
Frameless browser window has resize area on edges when resizable option is false

### ISSUE THREAD

**Issue by shark-o** [electron/electron#21929]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v7.1.10
* **Operating System:**
  * Windows 10 (1903)
* **Last Known Working Electron version:**
  * 

### Expected Behavior
When creating BrowserWindow with options:

```
{
    x: 0,
    y: 0,
    width: 800,
    height: 600,
    show: true,
    frame: false,
    resizable: false
}
```
Would expect that BrowserWindow doesn't have resize area on window edges where mouse events are not working.
 
### Actual Behavior
BrowserWindow has about 5px wide area on window edges where mouse events are not working.

### To Reproduce
```sh
$ git clone https://github.com/shark-o/electron-resize-area-bug.git
$ npm install
$ npm start || electron .
```

### Screenshots
![Electron window resize area](https://raw.githubusercontent.com/shark-o/electron-resize-area-bug/master/resize-area.gif "Electron window resize area")

**Comment by kartofelek007** [comment]
I confirm this. This hapend even when you set window to fullscreen.

chrome fullscreen:
![chrome-fullscreen](https://user-images.githubusercontent.com/2007669/78909245-85a97080-7a83-11ea-9887-93e98c10f0aa.gif)

electron frameless fullscreen
![electron-fullscreen](https://user-images.githubusercontent.com/2007669/78909275-8fcb6f00-7a83-11ea-8c98-bd439ac61f46.gif)

This is code for electron window:
```transparent: true,
frame: false,  
alwaysOnTop: true,  
fullscreen: true,  
resizable: false,
```

**Comment by jameshfisher** [comment]
Can confirm this issue still present in `^12.0.0-nightly.20200910`.

The border is `5px` on each side. I found this using:

```html
<!DOCTYPE html>
<html>
  <body>
    <p>
      Move the mouse around until the values below settle.
      The border size is inferred from min/max mouse positions.
    </p>
    <span id="log"></span>
    <script>
      const logEl = document.getElementById("log");
      let minClientX = Infinity;
      let minClientY = Infinity;
      let maxClientX = 0;
      let maxClientY = 0;
      document.onmousemove = (ev) => {
        minClientX = Math.min(minClientX, ev.clientX);
        minClientY = Math.min(minClientY, ev.clientY);
        maxClientX = Math.max(maxClientX, ev.clientX);
        maxClientY = Math.max(maxClientY, ev.clientY);
        logEl.innerText = JSON.stringify({ 
          leftBorder: minClientX, 
          topBorder: minClientY, 
          rightBorder: 799-maxClientX, 
          bottomBorder: 599-maxClientY,
        });
      };
    </script>
  </body>
</html>
```

**Comment by jameshfisher** [comment]
Workaround: add an additional transparent 5px on each side of your `BrowserWindow`. Fairly horrible, but seems to work.

**Comment by Thiedent** [comment]
> 
> 
> Workaround: add an additional transparent 5px on each side of your `BrowserWindow`. Fairly horrible, but seems to work.

Hi, i am trying to deal with the same issue, if you could, could you please explain a bit more what you mean in your workaround? Thanks

**Comment by Thiedent** [comment]
@jameshfisher 
> 
> 
> Workaround: add an additional transparent 5px on each side of your `BrowserWindow`. Fairly horrible, but seems to work.

Hi, i am trying to deal with the same issue, if you could, could you please explain a bit more what you mean in your workaround? Thanks

**Comment by jameshfisher** [comment]
@Thiedent I mean:

* On your BrowserWindow:
  * Set `transparent: true`
  * Set `width` to be 10px more than you actually need
  * Set `height` to be 10px more than you actually need
* In your HTML:
  * Set `body { margin: 5px }`, or equivalent, so that the page has a 5px unused border

**Comment by Thiedent** [comment]
> 
> 
> @Thiedent I mean:
> 
>     * On your BrowserWindow:
>       
>       * Set `transparent: true`
>       * Set `width` to be 10px more than you actually need
>       * Set `height` to be 10px more than you actually need
> 
>     * In your HTML:
>       
>       * Set `body { margin: 5px }`, or equivalent, so that the page has a 5px unused border

Thanks for replying, looks like that works, you are right not a nice workaround but it works, thanks

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
