### ISSUE TITLE
Docs: broken link to contributing document on Electron Support tutorial page

### ISSUE THREAD

**Issue by ig3** [electron/electron#21943]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * n/a
* **Operating System:**
  * n/a
* **Last Known Working Electron version:**
  * n/a

### Expected Behavior
When I click on the link  [contributing document](https://www.electronjs.org/CONTRIBUTING) towards the bottom of the [Finding Support](https://www.electronjs.org/docs/tutorial/support#finding-support) section of tutorial page [Electron Support](https://www.electronjs.org/docs/tutorial/support), a page describing how to contribute should appear.

### Actual Behavior
A 404 page not found error page appears.

### To Reproduce
Visit page [Electron Support](https://www.electronjs.org/docs/tutorial/support), scroll down towards the bottom of section [Finding Support](https://www.electronjs.org/docs/tutorial/support#finding-support) and click on the link  [contributing document](https://www.electronjs.org/CONTRIBUTING).

### Screenshots
n/a

### Additional Information
n/a

**Comment by ig3** [comment]
Perhaps that link should be to [Contributing to Electron](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) which I found from a link on [About Electron](https://www.electronjs.org/docs/tutorial/about), or maybe there is an equivalent page on https://www.electronjs.org/docs somewhere.

**Comment by erickzhao** [comment]
The fix was just merged in today: https://github.com/electron/electron/pull/21921

Hopefully should be up on the website soon!
