### ISSUE TITLE
Drastic Performance Decrease in SharedWorker from v5 to v6 and onwards

### ISSUE THREAD

**Issue by d4hines** [electron/electron#21944]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  6.0.0
* **Operating System:**
  * Windows 10 (18362)
* **Last Known Working Electron version:**
  *  5.0.13
### Expected Behavior

In v5, SharedWorker message posting was very fast (close 100K messages/second).
### Actual Behavior

In v6 and v7, SharedWorker message posting is an order of magnitude slower.

### To Reproduce

Here's the fiddle: https://gist.github.com/023c745f1f4faf24ee6a1c9e7fdb6819.

Press the button to start the test.
On v5, I get 90K messages/sec. On v6, I get 3K.

### Additional Information

Thank you all for your dedicated work on the project!

**Comment by masterkidan** [comment]
@d4hines : This issue is fixed in E9. The underlying bug fix in chromium is: 
https://chromium.googlesource.com/chromium/src/+/80cdb9f67d5aa482b4d118ab27164349fc8f2c69
