### ISSUE TITLE
win.blur() returns focus to the previous window on the OS level, but this does not occur if the previously focused window was a sibling window.

### ISSUE THREAD

**Issue by Slapbox** [electron/electron#21963]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** `7.1.10`
* **Operating System:** `Windows 7 & Windows 10 (Build 1803)` (Confirmed working macOS 10.13.6 / Mint 19)
* **Last Known Working Electron version:** Unknown, but I think this has never worked on Windows after encountering several related issues (see below) and examining my code - I had implemented a workaround for this since at least `Electron@3`.

### Expected Behavior
Calling `win.blur()` will return focus to the previously focused window

### Actual Behavior
If the previously focused window is part of the same Electron application, upon `win.blur()` the user will have no window focused.

### To Reproduce
1. Create two `BrowserWindow`s (allow `remote` module for simplicity)
  - `WinA` can be empty
  - In `WinB` include `<button onclick="remote.getCurrentWindow().blur()>Blur</button>`
2. Focus `WinA`
3. Click `Blur` in `WinB`

Press some OS level hotkey to affect the window, either closing, minimizing, etc - it will fail. Of course `webContents` is also not focused, but for simplicity's sake.

### Additional Information
Seems very likely related to #20464 and #19977

**Comment by dpilarsk** [comment]
Did you test on macOS ? Because I seem to have the same problem on Electron 7.1.10 too

**Comment by Slapbox** [comment]
I did test macOS and Linux with that version of Electron and had no issues. What version of macOS?

**Comment by dpilarsk** [comment]
With macOS Catalina

**Comment by Slapbox** [comment]
Interesting. Please do mention the exact version if you can (as per the issue template, which I know you can't see just leaving a comment.)

In any event, it doesn't look like this issue is going to get any attention.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by Slapbox** [comment]
Still an issue in 11.3.0.

**Comment by Slapbox** [comment]
Still an issue in 11.4.3.

**Comment by Profnird** [comment]
To make easy me I did make use of node-notifier to take care of my alerts and notifications. Using alert seems to bring problems at data entry points!. So I will advise for now one should make use of a third-party notifier like (node-notifier) which makes use of the native windows notification system at least thats a lot nicer. you just have to send your notification msg to the ipc main from your ipc renderer then boom there you go !!

**Comment by Slapbox** [comment]
Still an issue on Windows in 13.6.0. Works fine on Linux.

**Comment by Slapbox** [comment]
Not fixed to my knowledge, but I don't have an updated repro available right now.

**Comment by Slapbox** [comment]
I don't believe this is fixed but I don't have a repro. I somehow missed the stale notification.
