### ISSUE TITLE
registerURLSchemeAsPrivileged stopped working in electron 6, and still fails in 7

### ISSUE THREAD

**Issue by suedama1756** [electron/electron#22009]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v7.1.11
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * Electron 5

### Expected Behavior
When using the registerURLSchemaAsPrivileged API I expect to be able to use the fetch API from a renderer process  for that custom scheme 

### Actual Behavior
Browser renderer process emits: URL schema must be "http" or "https" for a CORS request

### To Reproduce
Create an electron main.js, register the schema as first line of code. 

```js
const { protocol } = require('electron');
protocol. registerURLSchemeAsPrivileged([{ schema: 'test', privileges: { bypassCSP: true }}]);
``` 

attempt to fetch from renderer:

fetch('test://some/path');

This code used to work in electron 5, was broken in 6 and seems to be still broken in 7. I've tried various combinations of privileges with no success.

**Update**:

I have managed to get the code working in the rendered process, however, it doesn't not appear to be available when running in a shared worker which is critical for our application and definitely worked in version 5

**Comment by nornagon** [comment]
@suedama1756 can you provide a repro that shows the issue you're encountering? Preferably through [Fiddle](https://github.com/electron/fiddle) or built on top of [electron-quick-start](https://github.com/electron/electron-quick-start)

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
