### ISSUE TITLE
ARM64 download file should also be named AARCH64

### ISSUE THREAD

**Issue by monitorelx** [electron/electron#22022]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * All versions, for this example just pick one and call it $VERSION
* **Operating System:**
  * GNU/Linux ARMv8 (ARM64 == AARCH64)
* **Last Known Working Electron version:**
  * NONE

### Expected Behavior
The file https://github.com/electron/electron/releases/download/v$VERSION/electron-v$VERSION-linux-aarch64.zip should also be available

### Actual Behavior
Only the file https://github.com/electron/electron/releases/download/v$VERSION/electron-v$VERSION-linux-arm64.zip is available

### To Reproduce
Try to download https://github.com/electron/electron/releases/download/v$VERSION/electron-v$VERSION-linux-aarch64.zip

### Screenshots
[Not Found]

### Additional Information
Achitectures ARM64 and AARCH64 are the same, so we need an alias because there are scripts that only use one of them. E.g. https://discuss.atom.io/t/error-electron-v5-0-11-linux-aarch64-zip-for-x-core-not-found/71595

**Comment by nornagon** [comment]
What system is expecting the architecture to be `aarch64`?

**Comment by monitorelx** [comment]
In may case it is Raspbian on Raspberry Pi 4B with official 64 bit kernel, trying to install X-Core with `npm install` (see example above).

**Comment by malept** [comment]
What is the output when you run the following on your Raspberry Pi 4B:

```
uname -m
node --eval='console.log(os.platform()); console.log(os.arch()); console.log(process.config.variables.arm_version)'

**Comment by monitorelx** [comment]
pi@rpi4b:~ $ `uname -m`
aarch64
pi@rpi4b:~ $ `node --eval='console.log(os.platform()); console.log(os.arch()); console.log(process.config.variables.arm_version)'`
linux
arm
6
pi@rpi4b:~ $

**Comment by malept** [comment]
That is bizarre that `arm_version` would be 6. Is Node coming from `nodejs.org`, the NodeSource repository, the official Debian repository, or somewhere else?

**Comment by monitorelx** [comment]
It is coming from official Raspbian repo, which are based on Debian:
pi@rpi4b:~ $ `apt show nodejs`
Package: nodejs
Version: 10.15.2~dfsg-2+rpi1
Priority: optional
Section: javascript
Maintainer: Debian Javascript Maintainers <pkg-javascript-devel@lists.alioth.debian.org>
Installed-Size: 153 kB
Depends: libatomic1 (>= 4.8), libc-ares2 (>= 1.7.0), libc6 (>= 2.4), libgcc1 (>= 1:3.0), libicu63 (>= 63.1-1~), libnghttp2-14 (>= 1.3.0), libnode64 (= 10.15.2~dfsg-2+rpi1), libssl1.1 (>= 1.1.0), libstdc++6 (>= 4.1.1), libuv1 (>= 1.20.0~), zlib1g (>= 1:1.1.4)
Recommends: ca-certificates, nodejs-doc
Suggests: npm
Conflicts: nodejs-legacy
Replaces: nodejs-legacy
Homepage: http://nodejs.org/
Download-Size: 86.5 kB
APT-Manual-Installed: no
APT-Sources: http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages
Description: evented I/O for V8 javascript - runtime executable
 Node.js is a platform built on Chrome's JavaScript runtime for easily
 building fast, scalable network applications. Node.js uses an
 event-driven, non-blocking I/O model that makes it lightweight and
 efficient, perfect for data-intensive real-time applications that run
 across distributed devices.
 .
 Node.js is bundled with several useful libraries to handle server
 tasks:
 .
 System, Events, Standard I/O, Modules, Timers, Child Processes, POSIX,
 HTTP, Multipart Parsing, TCP, DNS, Assert, Path, URL, Query Strings.

**Comment by malept** [comment]
Do the node arch/arm_version values change if you use the Node.js package from NodeSource, or the one from nodejs.org?

**Comment by monitorelx** [comment]
The problem is that Raspbian only has 32bit packages, just the kernel is 64bit. I will try again in a chrooted environment with Debian Testing 64bit and make you know. Thanks for your interest malept!

**Comment by monitorelx** [comment]
root@rpi4bCHROOT:/ # `node --eval='console.log(os.platform()); console.log(os.arch()); console.log(process.config.variables.arm_version)'`
linux
arm64
undefined

**Comment by monitorelx** [comment]
Closing the issue because in the chroot it is working well, so it will in a pure 64bit system.
...
> electron@5.0.11 postinstall /root/x-core/node_modules/electron
> node install.js

Downloading tmp-27797-1-SHASUMS256.txt-5.0.11
[============================================>] 100.0% of 4.79 kB (4.79 kB/s)
...
