### ISSUE TITLE
Not being able to install electron with npm on Ubuntu 19.10

### ISSUE THREAD

**Issue by GustavoPeredo** [electron/electron#22028]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.0
* **Operating System:**
  * Ubuntu 19.10 64x
* **Last Known Working Electron version:**
  * 

### Expected Behavior
Expected my first electron app to work / electron to install correctly

### Actual Behavior
When installing electron with npm install --save-dev electron, the following warning messages were printed: 

> core-js@3.6.4 postinstall /home/gustavo/Programming/First Electron App/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> electron@8.0.0 postinstall /home/gustavo/Programming/First Electron App/node_modules/electron
> node install.js

(node:26601) UnhandledPromiseRejectionWarning: RequestError: write EPROTO 140008315103104:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

    at ClientRequest.<anonymous> (/home/gustavo/Programming/First Electron App/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:428:26)
    at ClientRequest.emit (events.js:333:22)
    at ClientRequest.origin.emit (/home/gustavo/Programming/First Electron App/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:424:9)
    at TLSSocket.emit (events.js:321:20)
    at errorOrDestroy (internal/streams/destroy.js:128:12)
    at onwriteError (_stream_writable.js:463:3)
    at onwrite (_stream_writable.js:484:7)
    at internal/streams/destroy.js:60:7
(node:26601) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:26601) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm notice save electron is being moved from dependencies to devDependencies
npm WARN first-electron@1.0.0 No description
npm WARN first-electron@1.0.0 No repository field.

+ electron@8.0.0
added 85 packages from 91 contributors and audited 102 packages in 14.285s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

But since they appeared to be just warning I ignored them and ran npm install and npm start, the output was this:
> first-electron@1.0.0 start /home/gustavo/Programming/First Electron App
> electron .

/home/gustavo/Programming/First Electron App/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/home/gustavo/Programming/First Electron App/node_modules/electron/index.js:14:11)
    at Object.<anonymous> (/home/gustavo/Programming/First Electron App/node_modules/electron/index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/gustavo/Programming/First Electron App/node_modules/electron/cli.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! first-electron@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the first-electron@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gustavo/.npm/_logs/2020-02-04T15_39_49_539Z-debug.log

### To Reproduce
running the commands mentioned above

### Additional Information
I hope I'm not doing a dumb mistake...

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
