### ISSUE TITLE
Cannot resize maximized window on Windows

### ISSUE THREAD

**Issue by getupp** [electron/electron#22027]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version: 7.1.11 && 8.0.0
* **Operating System: Windows 10 (1607)
* **Last Known Working Electron version:6.*

### Expected Behavior
The window will be resized.

### Actual Behavior
The window stays maximized.

### To Reproduce
await this.app.browserWindow.maximize();
await this.app.browserWindow.setBounds({
      x: 0,
      y: 0,
      width: 1920,
      height: 900,
 });

### Additional Information
If I call unmaximzed after maximized, it can resize it. I can use that as a workaround. On Mac OS it works correctly.

**Comment by getupp** [comment]
I tried it with electron 8, this issue still exists in that version too.

**Comment by pushkin-** [comment]
Confirmed this behavior in Electron 8.0.1. By the way, why are you `await`ing `setBounds` and `maximize`?

**Comment by pushkin-** [comment]
this is also an issue in electron 9

**Comment by somebeaver** [comment]
Same problem, Electron 7.3.2.

**Comment by zilti** [comment]
Well duhh, it is a *maximized* window, the whole point of it is to take up the entire viewport and not even show the resize handlers.

**Comment by pushkin-** [comment]
@zilti This is a breaking change that used to work, which is why people are reporting it. It seems like a window being maximized shouldn't preclude you from programmatically resizing it.

**Comment by mlaurencin** [comment]
I am having a bit of trouble recreating your specific issue. Can you try running this Fiddle gist and confirm whether or not you are experiencing the same thing here?: [Gist](https://gist.github.com/mlaurencin/ea0ba05f61ac14d920c468b47d507904)
If not, if you could create and link your own gist of the issue, that would be very helpful.

**Comment by zilti** [comment]
> @zilti This is a breaking change that used to work, which is why people are reporting it. It seems like a window being maximized shouldn't preclude you from programmatically resizing it.

Yea, that is known in developer circles as a "bug fix". A maximized window has a fixed size, that's the entire point of it.

**Comment by groundwater** [comment]
Hey @zilti. I'm only going to say this once. _Be nice to our maintainers_. Please consider this repository a workplace, and you can leave the attitude at the door. We understand that broken software is frustrating. That doesn't change the matter.

We are all going to take a _cooling off moment_, so please **nobody comment here for 3 days**. After that, everyone including @zilti is welcome to engage again. We all want the same thing.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!

**Comment by pushkin-** [comment]
follow [here](https://github.com/electron/electron/issues/28170) for updates. FYI @mlaurencin
