### ISSUE TITLE
Tray for linux with click event : ignore appindicator ?

### ISSUE THREAD

**Issue by squalou** [electron/electron#22037]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

I'm using a Tray icon in my app for ages. Works fine.
With linux there is a limitaion : 

> When app indicator is used on Linux, the click event is ignored.

So far it didn't bother me, but ... I now have appindicator installed as a dependency of another software. And as a result ... my electron Tray click does not work anymore.

Would there be a way to somehow  'ignore appindicator' if present at runtime ?

### Proposed Solution

No idea, really :)

**Comment by vladimiry** [comment]
You should try Electron v8 which comes with changed tray icon clicking behavior, like switching to DBus KStatusNotifierItem thing, see #21445.

**Comment by squalou** [comment]
great news! will give it a try

**Comment by squalou** [comment]
great!
