### ISSUE TITLE
Documentation: Breaking Change in showOpenDialog() and possible other APIs

### ISSUE THREAD

**Issue by manngo** [electron/electron#22038]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

showOpenDialog now returns a promise, not a string. The change appears to have occurred since Electron 6. That’s OK, but I think that the change should be mentioned in the documentation for both older and newer versions.

Due to another issue I have had to revert to an older Electron, and have had to revisit the incompatibility.

### Proposed Solution

Update the documentation to mention above.

**Comment by MarshallOfSound** [comment]
We document all of our breaking changes in one place --> https://www.electronjs.org/docs/breaking-changes

**Comment by manngo** [comment]
> We document all of our breaking changes in one place --> https://www.electronjs.org/docs/breaking-changes

Surely you’re not expecting everybody who reads the documentation to switch over to that site just in case? It would make more sense to mention it in the documentation itself.

In any case, I can’t find any mention of this particular breaking change on that site, so it wouldn’t have helped.
