### ISSUE TITLE
LocalStorage does not persist after killing process (CTRL + C)

### ISSUE THREAD

**Issue by rodrigoramos** [electron/electron#22048]
* Electron version: 8.0.0
* Operating system: Linux - Fedora 31 - Kernel 5.4.13-201.fc31.x86_64

### Expected behavior
The local store should persist items even though the app is terminated as soon as the item was added.

### Actual behavior
If the app is terminated in less than 2 seconds after an item is added to local storage, the value is not available after the app is reopened.

### How to reproduce
1. Create a new electron app 
(I used the quick start from the website git clone https://github.com/electron/electron-quick-start)

0. Run the app using `npm start`

0. Run a JavaScript code that adds a new key/value pair to localStorage
````
localStorage.setItem("my-key", "my-value")
````

0. Within 3 seconds, terminate the app (killing the process or pressing Ctrl + C)
NOTE: If the app is closed properly (pressing Alt + F4 or click on the "X"), this issue does not occur.

0. Run the app again

0. Check for the localStorage items
````
localStorage.getItem("my-key")
````
Or in the Application tab from Developer Tools.

Both cases are not available neither the key nor the value

**Comment by mahnunchik** [comment]
Any news?

**Comment by johannesjo** [comment]
Did anybody find a good work around? For me the error occurs no matter how I close the window. I tried:
* `BrowserWindow.close()`
* the x
* Alt+F4
* cmd + c

Workaround approaches I see are:
* save localStorage entries completely on close of the main window and restore it if the window is recreated
* use indexeddb instead

I dislike both of them :/

**Comment by rodrigoramos** [comment]
@johannesjo: My work around was keep the data in a file inside of SO's temporary folder. I was not pleased with this solution but it worked well.

**Comment by tripower** [comment]
I have the same problems
local storage worked with Electron 7
but now with Electron 9 after close of the client oder site / domain change the data will be cleared??

**Comment by jcnmsg** [comment]
I'm having the same problem on Electron 11.0.2 running on Debian 10/11.

**Comment by subatomicglue** [comment]
same

**Comment by nornagon** [comment]
Please open a new issue with steps to reproduce on a [currently-supported version of Electron](https://www.electronjs.org/docs/latest/tutorial/electron-timelines).

**Comment by marcjulianfleck** [comment]
Issue still occurs. 
However it seemed to work for me the last two months even with hard shutting down a RaspberryPi. Out of nowhere it stopped working though and the local storage gets reseted after each restart.
Is there really no one how knows anything about that bug?

**Comment by ArsalImam** [comment]
We are using IndexedDB with as a workaround of it and it is serving the purpose with electron
