### ISSUE TITLE
Not updated dependencies in electron project; is there a cache to delete?

### ISSUE THREAD

**Issue by marcoautiero** [electron/electron#22051]
I'm working on an electron project where I'm having an issue that requires me to explore the code of some dependencies, too. In order to debug the app and find a solution to my issue I'm simply editing the code of a couple of dependencies, inserting some console.log(); but when I launch the electron app with `electron . --debug --disable-http-cache` I have not signs of any of my console.log(); I tried (as an extreme check) to completely delete the code of a dependency, but running the app it works while I expected to crash; furthermore, exploring the sources from the developer tool, I find the code of the dependencies, including the ones that I have edited, but with no signs of edits (so, with the original code).

I'm pretty new with electron, but to me it seems like there's a cache for dependencies and any edit made on them is not revealed. If it's so, how can I delete, update or disable this cache?

**Comment by MarshallOfSound** [comment]
There is no cache for your `node_modules` you probably aren't editing the right file.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
