### ISSUE TITLE
Not compatible with Yarn PnP

### ISSUE THREAD

**Issue by fketchakeu** [electron/electron#22053]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

Electron is not compatible with Yarn.

* **Electron Version:** 8.0.0
  * 
* **Operating System:** macOS 10.15.2
  * 
* **Last Known Working Electron version:** N/A
  * 

### Expected Behavior

Successful app start.

### Actual Behavior

Error message shown in a dialog box:
> A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'electron-is-dev'
> Require stack:
> - /Path/to/Project/electron-quick-start/main.js
> - /Path/to/Project/electron-quick-start/.yarn/unplugged/electron-npm-8.0.0-7c6435c2f3/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js

### To Reproduce

**Install Yarn (2)**

```
npm install yarn@berry -g
```

**Clone quick start repository**

```
git clone https://github.com/electron/electron-quick-start
```

**Go into the repository**

```
cd electron-quick-start
```

**Install dependencies using yarn**

```
yarn install
```

**Add a package dependency**

```
yarn add electron-is-dev
```

**Require the package dependency in main.js**

```
echo "require('electron-is-dev');" | cat - main.js | tee main.js > /dev/null
```

**Run the app**

```
yarn run start
```

**Comment by miniak** [comment]
Please report this to `electron-quick-start` instead

**Comment by fketchakeu** [comment]
Per your request, I created https://github.com/electron/electron-quick-start/issues/359
But this issue seems to be core to electron. I just used electron-quick-start as a way to illustrate and isolate the issue.

Thanks.
