### ISSUE TITLE
Notification.show() does not show the notification message

### ISSUE THREAD

**Issue by Praveer1981** [electron/electron#22061]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
I have upgraded the electron version from `6.0.12` to `7.1.1`. And I found that Notification feature stopped working.

* **Electron Version:**
7.1.1
* **Operating System:**
Windows 10 Enterprise
* **Last Known Working Electron version:**
6.1.12

### Expected Behavior
It should be able to shoe the Notification message at the bottom right corner of the screen.

### Actual Behavior
Its not showing the notification message.

### Additional Information
I was showing the notification message when my app download the file successfully.
Below code was working earlier:
**app.setAppUserModelId(<app Name>);**  What is the significance of <app Name>, Generally where do we get it from ?
Below is the code We have in the main process[Note: It works well with electron:6.1.12, but does not work with electron 7.1.1]
```
    const {Notification} = require("electron");
    item.once("done", (_event, state) => {
      downloadItems.delete(item)
      if (!mainWindow.isDestroyed() && downloadItems.size == 0) {
        setTimeout(() => {
          // Starts flashing the window to attract user's attention.
          mainWindow.flashFrame(true)
          mainWindow.setProgressBar(0, {
            mode: "none"
          })
        }, 2000)
      }

      if (state === "completed") {
        let notification = new Notification({
          title: appName,
          body: suggestPath
        });

        // handle on click event of notification
        notification.on("click", () => {
          shell.showItemInFolder(suggestPath);
        });
        notification.show();
      } else {
        console.log(`Download failed: ${state}`)
      }
    })
```

**Comment by Praveer1981** [comment]
@roelpaulo @m4heshd  It seems in my above code `notification.show();` is not working. Do you guys have any idea about it ?

**Comment by Praveer1981** [comment]
@roelpaulo @m4heshd  I want to use the `Notification` class as mentioned here 
https://www.electronjs.org/docs/api/notification#class-notification

**Comment by MarshallOfSound** [comment]
Please see the requirements for [showing a notification on windows](https://www.electronjs.org/docs/tutorial/notifications#windows)

**Comment by xlzhou1** [comment]
> @roelpaulo @m4heshd I want to use the `Notification` class as mentioned here
> https://www.electronjs.org/docs/api/notification#class-notification

Dose your app notification works for you? Same issue for me.

**Comment by mqliutie** [comment]
In my case, I used Notification Web API.
onshow callback is triggered but the message box can not be shown on macOS...
Performance>Notification>MyApp is enabled...

**Comment by AursorDev** [comment]
it doesn't work in 2024
