### ISSUE TITLE
MacOS: Child window is not focused if it is minimized

### ISSUE THREAD

**Issue by clusterberries** [electron/electron#22062]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  * 4.2.12
  *  5.0.12
  * 6.1.7
  * 7.1.11
* **Operating System:** 
  * macOS 10.14.6
* **Last Known Working Electron version:**
  * unknown

### Expected Behavior
Child window is focused

### Actual Behavior
Child window is still minimized and not focused 

### To Reproduce

1. Clone the repo (focus-child branch), install modules and start the project:

```sh
$ git clone https://github.com/clusterberries/electron-sample.git -b focus-child
$ npm install
$ npm start
```

2. Minimize child window
3. Click on "Focus child window" button

### Additional Information
Issue is also was reproduced on old Electron versions on Windows (4.2.12, 5.0.12). But it is not reproduced any more on v6 and v7, only macOS is affected.

Child window in the example is open using `window.open()` method. The same code can be used in Chrome. Issue is not reproduced with Chrome v80.

**Comment by habbes** [comment]
@clusterberries  it appears that this behaviour was introduced intentionally in [this commit](https://github.com/electron/electron/commit/bbb9c37), probably to address [this issue](https://github.com/electron/electron/issues/106).

**Comment by clusterberries** [comment]
@habbes that you for information!
@zcbenz could you please take a look? Thanks in advance

**Comment by whxleemdddd** [comment]
win.show();
no win.focus();

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
