### ISSUE TITLE
Default context menu stopped working after moving from electron 6.1.7 to 8.0.0

### ISSUE THREAD

**Issue by sergeyd63** [electron/electron#22068]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.0 stable
* **Operating System:**
  * Windows 10 64-bit
* **Last Known Working Electron version:**
  * 6.1.7

### Actual Behavior
Right click on any input field opens default context menu

### Additional Information
this might also affects the built-in spellcheck, since i noticed this issue when trying to make spellcheck work (although, might be non related)

**Comment by MarshallOfSound** [comment]
Electron has never had a default context menu, you always need to make it yourself in the `context-menu` event.  Your logic to do so has probably stopped working, or a module you use is doing it for you and has stopped working

**Comment by sergeyd63** [comment]
I meant in the input field, without implementing a custom context menu, you were getting default Windows context menu.
After upgrading to Electron 8 the menu does not appear any more.
My thoughts, also, that it might be related to builtin spellchecker not working, because that menu shows you word suggestions in case of misspelling 

To summarize, it's not an Electron feature, it's an Win OS feature, that somehow was disabled in Electron 8

![Clipboard01](https://user-images.githubusercontent.com/4738739/74445197-ffd2c580-4e43-11ea-8029-470d3288b466.jpg)
