### ISSUE TITLE
showMessageBox: unable to set icon in render process

### ISSUE THREAD

**Issue by roypardi** [electron/electron#22067]
### Preflight Checklist

* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
v8.0.0
  * 
* **Operating System:**
macOS 10.14.5
  * 
* **Last Known Working Electron version:**
  * 

### Expected Behavior

Using the code below I am trying to set the icon of a messageBox from within a `renderer` process

```   const iconPath = upath.toUnix(upath.join(__dirname, "assets", "icon_64x64.png"));

   // debug: does file exist?
    var fileExists = fs.existsSync(iconPath)
    console.log('fileExists', fileExists);
    
    const dialogIcon = nativeImage.createFromPath(iconPath);
    // debug did nativeImage get created?
    console.log('dialogIcon', dialogIcon);
    
    var options = {
        type: 'question',
        buttons: ['&Yes', '&No'],
        title: 'Delete Event',
        icon: dialogIcon,
        normalizeAccessKeys: true,
        message: 'Permanently delete event?'
    };

    const win = BrowserWindow.getFocusedWindow();
    dialog.showMessageBox(win, options)
        .then((choice) => {
            if (choice.response === 0) {
                // action code deleted for clarity
            }
        }).catch(err => {
            console.log('ERROR', err);
        });
}
```
### Actual Behavior

In the authoring environment (Visual Studio Code) and in the compiled app,  the custom Icon is not created:

<img width="250" alt="Screen Shot 2020-02-06 at 11 02 12 AM" src="https://user-images.githubusercontent.com/9053196/73954792-57b37e80-48d0-11ea-8aff-aed8a82e827f.png">

Console output showing that the source png exists and that the `nativeImage` was created

![Screen Shot 2020-02-06 at 11 02 29 AM](https://user-images.githubusercontent.com/9053196/73954828-600bb980-48d0-11ea-9456-f9c3552eb46e.png)

Using the same code from the `main` process, with the source path adjusted , the icon displays correctly
```const iconPath = upath.toUnix(upath.join(__dirname, "app", "assets", "win_icon_64x64.png"));```

<img width="250" alt="Screen Shot 2020-02-06 at 11 01 52 AM" src="https://user-images.githubusercontent.com/9053196/73954852-68fc8b00-48d0-11ea-9a09-55d3c4260f6a.png">

### To Reproduce
See the example code above

**Comment by miniak** [comment]
@roypardi the `dialog` module is not directly accessible in the renderer process. You must be using the `remote` module, which your code sample does not show. In that case the `nativeImage` also has to be used via `remote`.

**Comment by roypardi** [comment]
@miniak  – thanks for the reply. At the top of my `renderer` I am accessing the `dialog` and `nativeImage` modules as shown below. Maybe I am doing it wrong?

```
const { ipcRenderer, remote, nativeImage } = require('electron');
const { BrowserWindow, dialog } = require('electron').remote;
```

**Comment by MarshallOfSound** [comment]
```
const { ipcRenderer, remote } = require('electron');
const { BrowserWindow, dialog, nativeImage } = require('electron').remote;
```

As @miniak said you need to use `nativeImage` over `remote` for it to correctly work with a remote version of `dialog`

**Comment by roypardi** [comment]
Am I not doing that with this line: accessing both `dialog` and `nativeImage` via `remote`?

```const { BrowserWindow, dialog, nativeImage } = require('electron').remote;```
