### ISSUE TITLE
Printing on Windows 10 / 8 / 7 : paper size from default printer is always used

### ISSUE THREAD

**Issue by itechoverdose** [electron/electron#22066]
Hi! We found a strange issue.

User prints from our electron application, BrowserWindow.print() is executed and standard system printing dialog is shown
User selects printer other then default from printing dialog
The paper size setting from default printer is used, printed pages are numerous and have large empty spaces and small rectangles with dense printing in them.
The issue was easy to find because we had thermal printer set as default and it has small paper size. The printer used to print browserwindow content was some model of HP LaserJet.

Everything is ok only when default printer matches the selected from dialog printer.
But we couldn't produce issue with PDF virtual printer, only physical had an issue.

Electron version: 8.0.0
Operating system: Windows 7 x64

**Comment by codebytere** [comment]
@itechoverdose https://github.com/electron/electron/pull/22014 should help i think.

**Comment by zlab** [comment]
@codebytere 8.0.0 or later ?

**Comment by itechoverdose** [comment]
@codebytere Thank you so much for the amazingly fast reply ; i'll try ur solution soon and i also found a work around the problem and i thought i should mention it as it might be of help to u or anyone who needs it :
change the default printer when the user chooses a printer and since there is no way in electron to get what printer was chosen from the printer dialog (which i think should be added) u have to make ur own custom dialog and get printer name then run this command in main.js using child process exec function
Command : RUNDLL32 PRINTUI.DLL,PrintUIEntry /y /n "PRINTER_NAME_HERE"
then reset default printer to the original default printer after printing job is done to avoid causing problems to the user

**Comment by tangyue0924** [comment]
Same question. I need your help.THX

**Comment by eternalharvest** [comment]
I have same issue!

@codebytere
Thank you for your improvement in PR #22014.

But It seems the `pageSize` option is not work on windows environment.
This problem is not happen when I run same code on MacOS X.

My environment is below.
* Windows10 Pro x64
* Electron 11.2.3

**Comment by eternalharvest** [comment]
I wrote a simple script to diagnose this issue as follows.

```javascript
const { app, protocol, BrowserWindow } = require('electron');

var mainWindow = null;
app.on('window-all-closed', () => {
  if (process.platform != 'darwin') {
    app.quit();
  }
});

app.on('ready', () => {
  mainWindow = new BrowserWindow({
      width: 960,
      height: 640,
      center: true,
      show: false,
      webPreferences: {
        contextIsolation: true
      }
  });

  mainWindow.loadURL('https://www.google.com/');
  mainWindow.on('ready-to-show', () => {
    let opts = {
      pageSize: 'A5',
    };

    mainWindow.show();
    mainWindow.webContents.print(opts, (success, failureReason) => {
      console.log(opts);
    });
  });
  mainWindow.on('closed', () => {
    mainWindow = null;
  });
});
```

And the result is below.
```javascript
{
  pageSize: 'A5',
  mediaSize: {
    custom_display_name: 'A5',
    height_microns: 210000,
    name: 'ISO_A5',
    width_microns: 148000
  }
}
```

As you can see, it seems javascript level setting logic is fine.
I think this issue is related with windows implementation written in c++ in chromium code base.
But I'm not sure where to patch the code...

**Comment by m4heshd** [comment]
Printing seems to be broken on Electron v13 too. All the page related configs like `pageSize` , `landscape` and `margins` are being totally ignored and falls back to particular printer's defaults.

What I was able to discover is Chrome exhibits the exact same behavior if printed using the system dialog. Prints fine if browser's dialog is used. Since Electron uses the system interface it's probably originated from chromium.

So @codebytere, @nornagon, has there been any internal discussions about this? Any findings or possible solutions/workarounds? Fixing this would eliminate the need for using massive extra dependencies that hardly even gets the job done. Since Chromium already got perfect printing support could we possibly get this working? 🥺

**Comment by m4heshd** [comment]
Bump. Stale because there's no attention from the devs.

**Comment by andredealmei** [comment]
Is there a plan to fix this issue?

**Comment by odysahe** [comment]
> Hi! We found a strange issue.
> 
> User prints from our electron application, BrowserWindow.print() is executed and standard system printing dialog is shown User selects printer other then default from printing dialog The paper size setting from default printer is used, printed pages are numerous and have large empty spaces and small rectangles with dense printing in them. The issue was easy to find because we had thermal printer set as default and it has small paper size. The printer used to print browserwindow content was some model of HP LaserJet.
> 
> Everything is ok only when default printer matches the selected from dialog printer. But we couldn't produce issue with PDF virtual printer, only physical had an issue.
> 
> Electron version: 8.0.0 Operating system: Windows 7 x64

How about this?
i tried it on `printToPdf` and it worked.
```
  //paper F4
  pageSize: {
    height: 13,//inch
    width: 8.5,//inch
  },
```

**Comment by m4heshd** [comment]
> i tried it on `printToPdf` and it worked.

As discussed in #31705, the issue only applies to physical devices.

**Comment by qingyanbaby** [comment]
Bump.This problem still exists. This has had a profound impact on the user experience.

**Comment by m4heshd** [comment]
@qingyanbaby They won't pay attention to this issue anymore. The best option would be to open a new issue so the devs are aware that the issue still exists. Make sure to mention that you have tested on the latest version.

**Comment by bagonterman** [comment]
Bump. Having the same issue it will not change paper size. Even if set in microns. Electron 25.5 Node 18.15.0

**Comment by stefanbolba93** [comment]
For anyone who still has issues with this downgrade to version 24.8.3..
Create a new html file and load it in a new window. You will do all the resizing in that file using css.
Example:

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Print</title>
    <style>
      body {
        display: flex;
        justify-content: center;
        align-items: center;
        margin: 0;
        padding: 0;
        border: 1px solid black;
      }

      .container {
        border: 1px solid black;
        height: 470px;
        width: 384px;
      }
      #image {
        height: 100%;
        width: 100%;
        object-fit: fill;
        margin: 0;
      }

      @page {
        margin-top: 0cm;
        margin-left: 0cm;
        margin-right: 0cm;
        margin-bottom: 0cm;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <img src="" alt="print" id="image" />
    </div>
  </body>
</html>

const newWin = new BrowserWindow({
    width: 384,
    height: 576,
    show: false,
  });

  newWin.loadFile("./print.html");

  const printOptions = {
    silent: true,
    printBackground: false,
    color: false,
    landscape: false,
    collate: false,
    pagesPerSheet: 1,
    copies: 1,
    deviceName: data.printerName,
    // pageSize: {
    //   height: 127000, // 5 inch
    //   width: 101600, // 4 inch
    // },
  };

  newWin.webContents.once("did-finish-load", () => {
    newWin.webContents
      .executeJavaScript(
        `const image = document.querySelector("#image")
        image.src="data:image/png;base64, ${data.label}"
    `
      )
      .then(() => {
        newWin.webContents.print(printOptions, (success, errorType) => {
          if (success) {
            console.log("Print successful");
          } else {
            console.log(errorType);
          }
          newWin.close();
        });
      });
  });

**Comment by cah-eric-waight01** [comment]
Bump

**Comment by RichelleReyes** [comment]
Bump
