### ISSUE TITLE
Scrollbar is always visible on macOS

### ISSUE THREAD

**Issue by alxmiron** [electron/electron#22087]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  * v8.0.0 (also actual for v7.1.11)
* **Operating System:**
  * macOS 10.15.3
* **Last Known Working Electron version:**
  * maybe v6. not sure

### Expected Behavior
If macOS preference "Show scrollbars automatically on mouse trackpad" is set, scrollbar should disappear when not scrolling. Example from Chrome v80.0.3987.87:

![Feb-07-2020 17-41-08](https://user-images.githubusercontent.com/10484318/74043497-2327eb80-49d2-11ea-8e82-f3da389e1e1b.gif)

### Actual Behavior
If macOS preference "Show scrollbars automatically on mouse trackpad" is set, scrollbar is always visible, even when it's not scrolling. Example from Electron v8.0.0 (Chrome 80.0.3987.86 inside):

![Feb-07-2020 17-40-58](https://user-images.githubusercontent.com/10484318/74043507-2ae79000-49d2-11ea-8a4a-8d52ef42770c.gif)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
