### ISSUE TITLE
macOS: document entitlements when using Electron with node.js in renderer

### ISSUE THREAD

**Issue by bpasero** [electron/electron#22082]
It seems to me that the documentation in https://www.electronjs.org/docs/tutorial/mac-app-store-submission-guide refers to a sandboxed renderer. It would be valuable if Electron could document the minimal set of entitlements needed for a renderer that is not sandboxed, e.g. has access to node.js.

My naive assumption is that the following is needed:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.security.cs.allow-jit</key>
    <true/>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>
</dict>
</plist>
```

//cc @deepak1556 @MarshallOfSound

**Comment by nornagon** [comment]
If your app is in the MAS then technically there's no sandbox, because sandboxing is disabled under MAS due to unavailability of the APIs used to sandbox. (Plus MAS gives you its own sandbox.)

Is this still relevant?

**Comment by deepak1556** [comment]
VSCode is not published through the app store, but this issue is no longer relevant for VSCode, due to ongoing sandbox effort, entitlements are aligned with a chromium renderer for a while now  https://github.com/microsoft/vscode/tree/main/build/azure-pipelines/darwin , issue can be closed.
