### ISSUE TITLE
Delay for macros and sounds.

### ISSUE THREAD

**Issue by Frensiow** [electron/electron#22096]
I use an elgato to capture my games and another one for my camera. They both add delay to my stream so everything else need to be delayed by 1300ms. Since my deckboard is not delayed, my sound effects and my scenes changes are too soon! I would LOVE to see the implimatention of a delay for, well pretty much everythig. Maybe one delay per button and maybe an option to add a delay for the whole board?

Thanks, this app is great!

**Comment by nornagon** [comment]
I think you've found the wrong repository. This is Electron, a framework for building desktop apps.
