### ISSUE TITLE
fs.readFile is not calling the callback function on first run

### ISSUE THREAD

**Issue by Ziv-Barber** [electron/electron#22102]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
Electron version: any version (7.0.0, 7.1.9, 8.0.0).
  * 
* **Operating System:**
Windows 10.
  * 
* **Last Known Working Electron version:**
Never worked.
  * 

### Expected Behavior

On my render code:

import fs from 'fs'

fs.readFile(path, 'utf8', cb)

The cb must be called ALWAYS

### Actual Behavior

The cb function never been called on first run. I must select 'view - reload' from the app's menu and then it's working (or force compiling when debugging live).

### To Reproduce

To see this bug, just create an electron app and put this code in your render:

import fs from 'fs'

fs.readFile('someFile.txt', (err, data) => { console.log('bug! this message never been shown!') })

**Comment by xland** [comment]
@Ziv-Barber 
I think this is not an issue of Electron.
I try these codes in my render process.
```js
let fs = require('fs');
fs.readFile(`E:\net.log`, (err, data) => { console.log('bug! this message never been shown!') })
```
And I can see the console log message
`bug! this message never been shown!`

So if you can not see this console line.
Try use `require('fs')`
And check your Babel plugin

**Comment by xland** [comment]
This is a bug?

**Comment by gruen1988** [comment]
i got the same problem.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by alexanderkasten** [comment]
I got the same issue with Electron 13.x.x, but only on Windows. macOS works as expected. 
Has anyone fixed the problem?
