### ISSUE TITLE
Opening windows to bad URLs doesn't indicate errors like it does in Chrome; blank window

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#22100]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 7.1.2
* **Operating System:** Windows 10

### Expected Behavior
When I open a window to a non-existent page, I expect the window to indicate an error like Chrome.

### Actual Behavior
I just see a blank window.

### To Reproduce
If you download the electron-quick-start app and replace main.js with:
```
const { app, BrowserWindow } = require('electron')

async function createWindow() {
  var mainWindow = new BrowserWindow({
    webPreferences: {
      nativeWindowOpen: true
    }
  });
  await mainWindow.loadURL("https://google.com");
  mainWindow.webContents.openDevTools();
}

app.on('ready', createWindow);
```

Run `npm start` and open a window to a bad page in devtools: `window.open("https://googleaaaaa.com")`.

You end up with a blank window whose `location.href` is `chrome-error://chromewebdata/`.

If you do the same thing in Chrome, you end up with a window that points to the same URL and actually has content:
![google_error](https://user-images.githubusercontent.com/6374473/74074790-5ddf5300-49d5-11ea-9336-6059d9ae3fdf.png)

Is it possible to get the same page displayed for errors like this?

I guess this is somewhat related to [this](https://github.com/electron/electron/issues/9085).

**Comment by MarshallOfSound** [comment]
@pushkin- You can detect that error page inside a preload script and render whatever UI you want.  Also if you call `window.location.reload()` it will attempt to load the original URL again.

As a general rule Electron won't implement Chromium's UI features like this page
