### ISSUE TITLE
[Linux] Global shortcuts for keysyms associated with multiple keycodes

### ISSUE THREAD

**Issue by kempniu** [electron/electron#2210]
The way global shortcuts are [currently implemented](https://github.com/atom/electron/blob/master/chromium_src/chrome/browser/extensions/global_shortcut_listener_x11.cc#L105) prevents some `MediaPlayPause` events from being passed to the registered callback.

When registering a callback for `MediaPlayPause`, Electron only calls `XGrabKey()` for keycode 172 (generated by a `KEY_PLAYPAUSE` event). Meanwhile, other keycodes (208 and 215) are also associated with keysym `XF86AudioPlay`, not to mention there's yet another keysym, `XF86AudioPause`, which should also cause the callback for `MediaPlayPause` to be called.

Using an AVRCP-enabled Bluetooth headset, when the _Play/Pause_ button is pressed, a `KEY_PLAYCD` or `KEY_PAUSECD` event is generated, not a `KEY_PLAYPAUSE` one. These events are not passed to the callback registered for `MediaPlayPause`, while other button presses (_Next_ and _Previous_) are processed fine (which is not surprising, as `XF86AudioNext` and `XF86AudioPrev` keysyms are only associated with a single keycode each).

Unfortunately, my knowledge of X11, Chromium and Electron itself is too limited for suggesting a solution.

I'm observing the above behavior in version 0.26.1, yet the code in question hasn't changed for a year, so I'm not sure this is relevant.

**Comment by codebytere** [comment]
We are no longer implementing bugfixes/improvements for versions of Electron < `1.6.x`, so i'm going to close this issue.
