### ISSUE TITLE
windows7 black screen

### ISSUE THREAD

**Issue by javaxiu** [electron/electron#22118]
did electron support windows7 ?

i've try to find the lowest version which supports this os,  i've download electron bin file and double click to start(didn't load any code of mine),  and  it turns out electron@v5.0.9 is the lowest works fine.

and the higher version show a black screen,  electron.exe process keeps crashing  as i saw in  Process Explorer

**Comment by erickzhao** [comment]
I don't have access to a Windows 7 machine, but your issue seems pretty similar to: https://github.com/electron/electron/issues/19569#issuecomment-522231083

Can you check to see if your .NET Framework is outdated? Apparently v4.7.1 is needed at a minimum for Electron >=6.

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by gengshenghong** [comment]
@erickzhao I also got the black screen issue on Windows 7, and I search all the information, which points to #19569. The question is, it seems like .net framework 4.7.1 does NOT support Windows 7, and only support Windows 7 **SP1**, which means "system upgrade" for users. Does it mean Electron officially stop supporting for Windows 7 (without SPI1) from Electron v6.x? Please confirm my understanding, it is a blocking issue for my case (some other features require v6.x but I need to support Windows 7).

Thanks,
Shenghong

**Comment by javaxiu** [comment]
but i don't think this issue was cause by .net framework not installed
i've try to install it myself, but it black screen when start up still. and also,  keep crashing all the time.

so could i take it as STOP SUPPRORTING FOR WINDOWS7 OFFICAL , not since Electron 6 ?

**Comment by SilurianYang** [comment]
@javaxiu Hello! How do you solve this problem? I found that version 5.0.0 can run on win7! However, other bugs were found, and you need to upgrade to the higher version

**Comment by javaxiu** [comment]
> @javaxiu Hello! How do you solve this problem? I found that version 5.0.0 can run on win7! However, other bugs were found, and you need to upgrade to the higher version

yep, IT IS NOT SUPPORTING WINDOWS7 any longer (though that wasn't annouced offically), so if you want to use it, give up windows7, or use cef or other as a backup if u think windows7 is important

**Comment by bonniss** [comment]
Had the same problem, have digged almost entire the internet, I summarize people's solutions:
- install .NET Framework on client's machine
- install .NET Framework on developer's machine, then rebuild
- downgrade Electron version
Did all of these, same black screen. Then I moved the portable app folder from `D:` to `C:` and re-ran the `.exe`, it strangely worked!
When it comes to building on specific platform, Electron kills me every time.
