### ISSUE TITLE
Media internals broken in electron 8

### ISSUE THREAD

**Issue by sebakerckhof** [electron/electron#22120]
### Preflight Checklist
* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.0
* **Operating System:**
  * Ubuntu 18.04 x64 
* **Last Known Working Electron version:**
  * 7.1.11

### Expected Behavior
Loading chrome://media-internals should load the chrome media internals page

### Actual Behavior
Blank page. In chrome 80 there's also the option to show it in the devtools. If I set the correct flags I can see the 'Media' tab option, but it also gives me a blank page. So neither way works.

### To Reproduce
Load `chrome://media-internals`

**Comment by erickzhao** [comment]
Did some digging, seems like it broke sometime between the 2019.10.12 and 2019.10.17 nightly build for Electron 8.

**Comment by jdwalker** [comment]
This happens in Windows as well for chrome://flags #22209

**Comment by sarumjanuch** [comment]
Just faced same issue, on 9.0.0-beta5, for chrome://webrtc-intrnals.

**Comment by sarumjanuch** [comment]
This is the error i get in rejected .loadURL promise:
```
Error: ERR_FAILED (-2) loading 'chrome://webrtc-internals/'
    at rejectAndCleanup (electron/js2c/browser_init.js:5996)
    at WebContents.failListener (electron/js2c/browser_init.js:6006)
    at WebContents.emit (events.js:210)
```

**Comment by sarumjanuch** [comment]
This is not platform dependent, as i faced this on win and mac.

**Comment by kubaau** [comment]
Has anybody found a workaround for this?

**Comment by eengoron** [comment]
Is there any update on this?

**Comment by mashafomasha** [comment]
> Has anybody found a workaround for this?

I know just one workaround such as use `peerConnection.getStats()` method to gather all information by your own

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!

**Comment by jesse-gibson-dd** [comment]
For anyone subscribed to this issue, give it another shot. This seems to be fixed in newer versions of Electron. (Tested on `v27.3.2` and latest `v30.0.1`). I'm able to successfully load `chrome://webrtc-internals` and `chrome://gpu` via `loadURL(...)`.

**Comment by code-small-white** [comment]
@codebytere Can only the URL below be opened? Why are others, like chrome://flags, not working?
```
// electron/spec/chromium-spec.ts
  describe('chrome:// pages', () => {
    const urls = [
      'chrome://accessibility',
      'chrome://gpu',
      'chrome://media-internals',
      'chrome://tracing',
      'chrome://webrtc-internals',
      'chrome://process-internals'
    ];
```

**Comment by ThaUnknown** [comment]
for anyone wanting to enable arbirtary flags they test on other browsers, open `about://version/` in your browser of choice, there inside `Command Line` you'll find for example: `--flag-switches-begin --enable-experimental-web-platform-features --enable-features=FileSystemAccessAPI,FluentOverlayScrollbar,WindowsScrollingPersonality --flag-switches-end` as I have enabled: ![Image](https://github.com/user-attachments/assets/e8fb8593-1fda-4591-9e89-8c404a382b23)
in my browser

some switches are part of `--enable-features`, some arent such as experimental web platform features, safest bet to enable these is:
```js
import { app } from 'electron'
app.commandLine.appendSwitch(flag, value)
```
but
```js
new BrowserWindow({
    webPreferences: {
      enableBlinkFeatures: 'FluentOverlayScrollbar, WindowsScrollingPersonality'
    }
  })
```
seems to work as well?

enjoy

this is in relation to [#22209](https://github.com/electron/electron/issues/22209)
