### ISSUE TITLE
Widevine plugin not working

### ISSUE THREAD

**Issue by iwiedenm** [electron/electron#22136]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.0 but also present in 7.x.x at least
* **Operating System:**
  * all
* **Last Known Working Electron version:**
  * none

### Expected Behavior
Follow Official docs https://www.electronjs.org/docs/tutorial/testing-widevine-cdm and be able to load the DRM protected video on https://shaka-player-demo.appspot.com

### Actual Behavior
Widevine does not load into `navigator` and the DRM video on https://shaka-player-demo.appspot.com does not play

### To Reproduce
0. Set up electron quick start 8.0.0 https://github.com/electron/electron-quick-start
1. Get the latest version of Widevine from here: https://dl.google.com/widevine-cdm/current.txt (currently 1.4.9.1088)
2. Download that version from here https://dl.google.com/widevine-cdm/1.4.9.1088-mac-x64.zip and extract it to electron-quick-start/widevine
3. add commandLine switches to main.js, enable plugins, and load test site
```
app.commandLine.appendSwitch('widevine-cdm-path', './widevine')
app.commandLine.appendSwitch('widevine-cdm-version', '1.4.9.1088')
// ...
const mainWindow = new BrowserWindow({
  width: 800,
  height: 600,
  webPreferences: {
    preload: path.join(__dirname, 'preload.js'),
    plugins: true
  }
})
mainWindow.loadURL('https://shaka-player-demo.appspot.com/')
```
4. Observe that the DRM video does not play!

I understand that the docs say it might not work on some versions but I would like an official answer as to whether this is still the case because it is a little misleading if it doesn't work at all, which seems to be the case in my research. If anyone has a solution I would greatly appreciate it!

**Comment by simongregory** [comment]
Does the [Note on VMP](https://www.electronjs.org/docs/tutorial/testing-widevine-cdm#note-on-vmp) section in the docs help? The [fork](https://github.com/castlabs/electron-releases) mentioned is probably your easiest option.

Checking this [endpoint](https://redirector.gvt1.com/edgedl/widevine-cdm/versions.txt) the latest Widevine CDM is 4.10.1582.2 and the oldest version is 1.4.9.1088. Using the newer version might alter your findings but you are most likely to experience trouble from the enhanced security added with VMP, a lot can depend on the robustness levels required by the license server.

**Comment by iwiedenm** [comment]
Yeah that's helpful although it seems the docs should specify that it will absolutely not work unless you use that fork because that seems to be the case

**Comment by MarshallOfSound** [comment]
Unfortunately widevine get's harder to use constantly and we do not have the resources to actively support it, we will gladly accept any PRs to improve the situation whether that is documentation or code fixes but for now I'm closing this out as it's not something we're going to be able to address any time soon
