### ISSUE TITLE
dsym archive contains breakpad symbols on mac

### ISSUE THREAD

**Issue by torycl** [electron/electron#22139]
The distribution archive for macOS with native dSYM symbols contains also breakapd_symbols directory. This directory has the same contents as archive with breapad symbols.

*For example*:
`electron-v9.0.0-beta.1-darwin-x64-dsym.zip`
also contains directory `breakpad_symbols` which is in
`electron-v9.0.0-beta.1-darwin-x64-symbols.zip`

To fix, please remove breapad_symbols from -dsym archive and leave it only in -symbols archive.

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.0.0 - latest
  * macOS, all versions
* **Last Known Working Electron version:**
  * I don't know

### Expected Behavior
`electron-vX.Y.Z-darwin-x64-dsym.zip` contains just dSYM symbols.

### Actual Behavior
`electron-vX.Y.Z-darwin-x64-dsym.zip` contains dSYM symbols and breakpad_symbols.

### To Reproduce
Download `electron-vX.Y.Z-darwin-x64-dsym.zip` from any version released in last years.

### Screenshots
![Screenshot 2020-02-11 at 09 54 48](https://user-images.githubusercontent.com/3928694/74223129-501c1d00-4cb6-11ea-8b5a-7f6b05ed46f9.png)

**Comment by alexeykuzmin** [comment]
cc @jkleinsc
