### ISSUE TITLE
No way to support "Check Spelling While Typing" setting by toggling spellchecker webpreference

### ISSUE THREAD

**Issue by jwheare** [electron/electron#22143]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.0.0
* **Operating System:**
  * macOS 10.15.3

With the built in spellchecker landed in 8.0.0, there is no way to toggle spellchecking behaviour without recreating a BrowserWindow, since it's only exposed as a boolean on webPreferences.

This makes it impossible to implement the standard "Check Spelling While Typing" menu item on macOS.

Please provide a runtime toggle for this.

**Comment by thomasdao** [comment]
I can work around this issue by setting `spellcheck="false"` to the DOM element that doesn't require spellcheck.

**Comment by MarshallOfSound** [comment]
As @thomasdao suggested, with the new Spellchecker Electron is aligning more with how Chromium works and there is already a webstandard way for disabling the spellchecker on DOM elements.  You should be using that 👍
