### ISSUE TITLE
TS definitions of NativeImage static methods are incorrect

### ISSUE THREAD

**Issue by dperetti** [electron/electron#22167]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.0
* **Operating System:**
  * any
* **Last Known Working Electron version:**
  * (not sure)

### Expected Behavior
```js
import { NativeImage } from 'electron'
const nativeImage = NativeImage.createFromPath(imagePath)
```
**Type checking should warn that NativeImage in undefined.**

### Discussion
In `electron.d.ts`, `createFromPath` and other methods are defined as static methods of `NativeImage`, but the exported module is `nativeImage`, not `NativeImage`. 

Typescript is probably confused with this:
<img width="297" alt="image" src="https://user-images.githubusercontent.com/845612/74332226-95fbe280-4d95-11ea-8226-de65f454a11f.png">

The workaround is currently to:
```js
import { nativeImage as NativeImage } from 'electron'
```

If I'm understanding right, `electron.d.ts` is generated with https://github.com/electron/typescript-definitions from the json api documentation, so the issue might live there.

**Comment by codebytere** [comment]
> but the exported module is `nativeImage`
@dperetti the above is correct; this isn't a typing issue, the static methods _should_ be called from `nativeImage`. 

```
import { nativeImage } from 'electron'
const image = nativeImage.createFromPath(imagePath)
```

is what you want.

**Comment by dperetti** [comment]
1. My point was: the typing is unable to detect the issue when you do this:
```js
import { NativeImage } from 'electron'
const nativeImage = NativeImage.createFromPath(imagePath)  // NativeImage is undefined but no error is detected
```
This is because  the definition file incorrectly states that `createFromPath` is a static method of the `NativeImage` class:

<img width="644" alt="image" src="https://user-images.githubusercontent.com/845612/74385900-f110f200-4df4-11ea-93dc-d074d077e9a4.png">
2. This is all the more confusing that using the the lower case  `nativeImage` is not consistent with the way other imports work (BrowserWindow, Menu, etc):

<img width="256" alt="image" src="https://user-images.githubusercontent.com/845612/74386073-5f55b480-4df5-11ea-8440-1522fe9b5ff8.png">

This is not intuitive to:

```js
const browserWindow = BrowserWindow.fromId(...)
// but
const _nativeImage = nativeImage.createFromPath(...)
```

Would you mind re-opening?

**Comment by Omnidon** [comment]
The original poster is correct.

Typescript code hinting is still showing that createFromPath exists on NativePath, but it gets:
`Can not read from property 'createFromPath' of undefined`

nativeImage must be used instead, but the typescript definitions clearly need to be updated.

**Comment by moritzruth** [comment]
@codebytere This should be reopened.

**Comment by AmirSavand** [comment]
Getting the same error. Why is this closed @codebytere?

**Comment by MBurchard** [comment]
I'm working with Electron 18.2.3 and it's still confusing:

```typescript
import {
  nativeImage,
  NativeImage,
} from 'electron';
declare const __static: string;

function getImageFromStatic(filename: string): NativeImage {
  return nativeImage.createFromPath(path.join(__static, filename));
}
```

If one use `NativeImage.createFromPath` the following error message is shown in IntelliJ:

TS2693: 'NativeImage' only refers to a type, but is being used as a value here.

**Comment by BlackHole1** [comment]
@MBurchard Sorry I wasn't clear on this before, maybe you wanted to @codebytere? 😄 But just now I tried to understand the whole context  I have just based my code on yours and don't get the same error. Can you provide a repo address where I can reproduce the problem? 👀

<img width="793" alt="image" src="https://user-images.githubusercontent.com/8198408/169491544-87625742-ee42-4c94-889d-b604346074ef.png">

**Comment by MBurchard** [comment]
@BlackHole1 as said... `NativeImage.createFromPath` instead of `nativeImage.createFromPath` leads to that error...

for me it is not obvious and clear why one has to import two things... `NativeImage` and `nativeImage`

**Comment by BlackHole1** [comment]
`NativeImage` is TypeScript Type, not JavaScript Object.
`nativeImage` is JavaScript Object, not TypeScript Type.

I thought the following example would be more intuitive.
```
import { nativeImage } from "electron";
import type { NativeImage } from "electron";
```

**Comment by BlackHole1** [comment]
In the latest version of electron, I see that the type is correct.
<img width="611" alt="image" src="https://user-images.githubusercontent.com/8198408/169504586-f72a033d-2a1c-4b1e-bdb9-fe6c73925d84.png">

**Comment by MBurchard** [comment]
Thank you very much for clarification. I have added the correct rule in the `.eslintrc.js`
```javascript
  rules: {
    '@typescript-eslint/consistent-type-imports': 'error',
```
and the Imports are much clearer now.

I still find it a bit unfortunate that there are `nativeImage` and `NativeImage`, but it is perfectly clear that there is a need for this difference. One is a Type, the other a JavaScript Object.

> Return Type is not necessary.

Here I do not agree. At the latest, when you export a method, it should have a return type. So the developers should not be lazy and specify in right away 😉

**Comment by BlackHole1** [comment]
Great! Glad to have solved your problem. 😄
