### ISSUE TITLE
Print from PDF

### ISSUE THREAD

**Issue by nornagon** [electron/electron#22179]
In Chrome's PDF viewer, there's a "print" button which allows the user to print a PDF. We've disabled this because it doesn't work currently. We should fix it and re-enable it.

https://github.com/electron/electron/blob/d590f2e/shell/browser/extensions/api/resources_private/resources_private_api.cc#L73-L74

**Comment by bakaa99** [comment]
I would like to help with this, Can you lead me in the right way on how can i go around fixing it.

**Comment by JuliadsonS** [comment]
Forecast for correction?

**Comment by codebytere** [comment]
Fixed in https://github.com/electron/electron/pull/22760
