### ISSUE TITLE
PDF download button doesn't do anything

### ISSUE THREAD

**Issue by nornagon** [electron/electron#22178]
When viewing a PDF, clicking the "download" button has no effect. It should trigger a download (including the `"will-download"` event and associated machinery).

**Comment by aaronsarnat** [comment]
Not sure if this is possible, but it would also be cool if the download button could be optionally hidden or disabled if, say for instance, user is reading a PDF from the local file system (e.g. user manual).

**Comment by agata** [comment]
This is very useful. Now, if the user is using BrowserWindow or WebView, the PDF The files are automatically previewed (really great). However, I think it's getting harder to download the PDF files.

**Comment by vishnu0320** [comment]
"dom- ready" console is working but "will-download" is not working ???

```
win.webContents.on('dom-ready', () => {
        console.log("dom ready")
      })
win.webContents.on('will-download', () => {
        console.log("download")
      })
```
