### ISSUE TITLE
Some incrementally-loaded PDFs only load the first page

### ISSUE THREAD

**Issue by nornagon** [electron/electron#22180]
e.g. https://www.hq.nasa.gov/alsj/a17/A17_FlightPlan.pdf

See also https://crbug.com/1051548 for a DCHECK that triggers when attempting to load this PDF in Chromium with DCHECKs enabled.

**Comment by aaronsarnat** [comment]
I've been experiencing this bug as well. Here's a screenshot:

![image](https://user-images.githubusercontent.com/8367927/80914505-dc137300-8d00-11ea-8ffe-64417d98d1e3.png)

I see the second page flash for a split second and then all pages except first turn into blurry dots. Here's the PDF I'm trying to load in an `<embed>` tag:
https://www.fabfilter.com/help/ffproq3-manual.pdf

The app I'm building can run either in a browser or as a standalone app via Electron. This PDF bug appears to be specific to the Electron build.

Currently building against `10.0.0-nightly.20200221` in `package.json`. I tried the latest nightly just now and there was no change.

**Comment by thomasLechaptois** [comment]
The issue seems to be fixed in electron 9.3.4 and 10.1.6, can anyone else confirm? Linked chromium issue could be https://bugs.chromium.org/p/chromium/issues/detail?id=1051548

**Comment by electron-triage** [comment]
see https://github.com/electron/electron/issues/22180#issuecomment-733553388
