### ISSUE TITLE
did-start-loading event fired when an iframe is loaded in the window

### ISSUE THREAD

**Issue by ghost** [electron/electron#22182]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.x.x , 6.x.x , 7.x.x 
* **Operating System:**
  * MacOS 
* **Last Known Working Electron version:**
  * N/A 

### Expected Behavior

webContents `did-start-loading` event should fire only page in the browser window starts loading and not an iframe is added to the 

### Actual Behavior

did-start-loading event fires when the window starts to load and when a new iframe is added and the page in the iframe starts loading instead of firing only when the window starts to load.

### To Reproduce

main.js
```
const {app,BrowserWindow } = require('electron');
const path = require('path');
var win;
function createWindow() {
win = new BrowserWindow({width: 800, height: 600});
win.loadURL("file://" + path.join( app.getAppPath() , 'index.html') );
win.webContents.on('did-start-loading',()=>{
    console.log('did start loading called');
   });
}
app.on('ready', createWindow);
```

index.html
```
<!DOCTYPE html> 
<html>
    <head>
        <meta charset="UTF-8">
        <title>Hello World!</title>
    </head>
    
    <body>
        <h1>Hello World!</h1>
        <button onclick="setIframe()">set iframe</button>
    </body>
    <script>
function setIframe()
            {
              var frame = document.createElement('iframe');
              frame.src = "https://www.github.com";
              document.body.appendChild(frame);
            }
    </script>
</html> 
```

### Additional Information

the console msg is printed every time a new iframe is added

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
