### ISSUE TITLE
Double-clicking while window.confirm dialog is open causes window to maximize

### ISSUE THREAD

**Issue by begriffs** [electron/electron#2218]
If a `window.confirm` dialog is open then double-clicking anywhere not on the dialog itself acts like a double-click of the window titlebar and causes the window to maximize.

**Comment by hokein** [comment]
Also confirmed on OS X: with a `window.confirm dialog`, user can still maximize/minimize the BrowserWindow.

**Comment by zcbenz** [comment]
On Windows this has been fixed with #2152.

**Comment by zcbenz** [comment]
This is actually an expected behavior when using native message box, I'm closing as won't fix.
