### ISSUE TITLE
Notification timeoutType='never' doesn't work

### ISSUE THREAD

**Issue by p-fusi** [electron/electron#22192]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.0
* **Operating System:**
  * Windows 10 Pro (1709)

### Expected Behavior
Using Notification API in main process with `timeoutType: 'never` I expected that the notification disappears only when the user clicks on it.  

### Actual Behavior
After few seconds the notification disappers.

### To Reproduce

```
  const newNotification = new Notification({title: 'I am a main process Notification!', timeoutType: 'never'})
  newNotification.show()
```

```sh
$ git clone https://github.com/p-fusi/electron-quick-start -b master
$ npm install
$ npm run start
```

**Comment by p-fusi** [comment]
Sorry, any update for this problem?

**Comment by jp185318** [comment]
any one got the solution for above listed problem

**Comment by mbuchner** [comment]
notifications are a pretty important thing when deciding for electron -> nobody could find a fix?

**Comment by LaserYGD** [comment]
This issue is still ongoing, just tested today on the latest stable release. like mbu mentioned it's really important, sometimes you want to make sure the user sees the notification -- if not set to never, he could be AFK and by the time he's back it's gone

**Comment by codebytere** [comment]
This is being worked on.

**Comment by JohansenJunias20** [comment]
i fixed my problem. I putted title inside the object option instead parameter.
**Before :** 
`new Notification("hi there!",{ body: "helloworld", timeoutType: "never" })`
**After :**
`new Notification({ title:"hi there!",body: "helloworld", timeoutType: "never" })`
