### ISSUE TITLE
Tray icon blurry on HiDPI Linux desktop

### ISSUE THREAD

**Issue by rocka** [electron/electron#22207]
### Issue Details

* **Electron Version:**
  * 8.0.0
* **Operating System:** 
  * KDE Plasma 5.18, Arch Linux
* **Last Known Working Electron version:** 
  * 7.1.10

### Expected Behavior
Tray icon should be clear and sharp on HiDPI displays

### Actual Behavior
Tray icon got blurry

### To Reproduce

1. create `index.js`

```js
const {app, Tray} = require('electron')
let t;
app.on('ready', () => {
    t = new Tray('icon.png')
    t.setToolTip('test tray')
})
```

and `icon.png` with this image: ![icon](https://user-images.githubusercontent.com/13914967/74583657-2d666d00-5004-11ea-9a6c-fdca6ff974dc.png) (or any 44x44 png image)

2. run with electron@7

```console
$ npm i electron@7.1.10
$ npx electron .
```

tray icon is sharp and clear

![image](https://user-images.githubusercontent.com/13914967/74583684-8b935000-5004-11ea-9e6a-1cf32a34d575.png)

3. run with electron@8

```console
$ npm i electron@8.0.0
$ npx electron .
```

tray icon is blurry

![image](https://user-images.githubusercontent.com/13914967/74583671-6a326400-5004-11ea-95a9-6bb6ad785bce.png)

### Additional Information

This may caused by https://github.com/electron/electron/pull/21904 , as it downscales every image to 22x22.

**Comment by vladimiry** [comment]
I guess this change https://github.com/electron/electron/pull/21904 might have something to do with the issue.

**Comment by Slapbox** [comment]
Seeing the same issue with `11.4.x`. I'm surprised no one else is reporting this. I figured it must be some mistake in our implementation at first, but by the third day of trying to resolve this, I have to conclude it's Electron.

**Comment by Slapbox** [comment]
@rocka did you ever resolve this? Things just don't look right in KDE.

**Comment by Slapbox** [comment]
Top: Our 22x22px image
Bottom: Our 22x22px image in the KDE tray

![image](https://user-images.githubusercontent.com/6835891/154386449-9813b402-0078-4da8-ae03-72c304b6cb00.png)

If anyone has any ideas, I'd be very appreciative. This is how it looks even with the latest version of KDE - 5.24.1

**Comment by Slapbox** [comment]
Looks like this isn't an issue with `snap` packages, so I'm guessing there's nothing that can be fixed on Electron's side.

**Comment by Slapbox** [comment]
Looks possibly fixable via installing [`libappindicator-gtk3`](https://www.reddit.com/r/discordapp/comments/hyivy9/discord_tray_indicator_is_blurry_on_linux/fzfex13/), so really nothing to be done on Electron's side I guess - but it's a shame because for users not running Arch, it's pretty tedious to get up and running.

**Comment by Slapbox** [comment]
Hmmm that's very curious. Thanks for sharing @ArchangeGabriel!

**Comment by Slapbox** [comment]
Fixed this by accident on KDE by installing `libappindicator3-1`.
