### ISSUE TITLE
Need Documentation on how use built-in Spellchecker for WebViews

### ISSUE THREAD

**Issue by Syed-Umair** [electron/electron#22216]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

I am not able to use the built-in spellchecker feature in Electron 8.x for Webviews.

### Proposed Solution

It would be great if additional documentation is provided on the Spellchecker functionality and how to use it in webviews.

**Comment by Syed-Umair** [comment]
Hi Team, 
Any updates on this one are appreciated

**Comment by zeevl** [comment]
https://github.com/electron/electron/commit/4323b6d618d41376c7fcef85752ebff48602651d helps. 

In your main process, call `setSpellCheckerLanguages` with your default language(s):
```
session.defaultSession.setSpellCheckerLanguages(['en-US']);
```


Then watch for the `context-menu` event:
```
    browserWindow.webContents.on('context-menu', (event, props) => {
      // when triggered on a misspelled word:
      // props.misspelledWord will have the word
      // props.dictionarySuggestions will be an array of suggestions
    });
```

You can use this to build the context menu in your UI. 

call `session.defaultSession.addWordToSpellCheckerDictionary(word);` to add a word to your dictionary.

**Comment by Syed-Umair** [comment]
@zeevl 

> [4323b6d](https://github.com/electron/electron/commit/4323b6d618d41376c7fcef85752ebff48602651d) helps.
> 
> In your main process, call `setSpellCheckerLanguages` with your default language(s):
> 
> ```
> session.defaultSession.setSpellCheckerLanguages(['en-US']);
> ```
> 
> Then watch for the `context-menu` event:
> 
> ```
>     browserWindow.webContents.on('context-menu', (event, props) => {
>       // when triggered on a misspelled word:
>       // props.misspelledWord will have the word
>       // props.dictionarySuggestions will be an array of suggestions
>     });
> ```
> 
> You can use this to build the context menu in your UI.
> 
> call `session.defaultSession.addWordToSpellCheckerDictionary(word);` to add a word to your dictionary.

This works when you are trying to use the spellcheck for BrowserWindow. But I would like to integrate the spellcheck for the Webview inside the browserwindow.

**Comment by ahallicks** [comment]
See https://github.com/electron/electron/issues/23363#issuecomment-622290317 for the apparent working example.

**Comment by MehediH** [comment]
Is there any update on this? I could not find any working sample where the built-in spellchecker works for webview.

**Comment by ccorcos** [comment]
I have a minimal reproduction here: https://github.com/ccorcos/electron-spellchecker-bug

![image](https://user-images.githubusercontent.com/1794527/94482861-cb233c80-018e-11eb-9974-71fb78809bdf.png)

Spellchecker works inside the main webview, but not inside an inner webview.

**Comment by Syed-Umair** [comment]
I found that spellcheck is working by default in webviews and iframes in electron 10.1.3. Closing the issue for now.
