### ISSUE TITLE
The "prefers-color-scheme" media query gets stuck after manually setting the appearance

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#22211]
### Issue Details

* **Electron Version:**
  * 7.1.12
* **Operating System:**
  * macOS 10.14
* **Last Known Working Electron version:**
  * Never worked

### Expected Behavior

This is my use case:

1. Listen for system-level appearance preferences changes via this: `matchMedia ( '(prefers-color-scheme: dark)' )`.
2. If the theme of my app is dark, or if the system-level appearance is dark, then set the app's appearance to dark, otherwise set it to light.
3. Refresh the app's appearance when needed.
4. I'd rather use web standards for doing this rather then listening for system-level appearance changes via the SystemPreferences module, which works.

It's a pretty reasonable use case right?

### Actual Behavior

1. Either because the system-level appearance or the theme changed at some point I'll have to set the appearance of the app accordingly.
2. Once I do that `matchMedia ( '(prefers-color-scheme: dark)' )` becomes totally useless and just always tells me back the value I have set.

What's the point of `prefers-color-scheme` telling me back what I already know rather than **always** listening for system-level changes?

### To Reproduce

```js
// renderer.js

let THEME = 'light';

setInterval ( () => {
  const prefersDark = matchMedia ( '(prefers-color-scheme: dark)' ).matches;
  console.log ( 'dark mode detected:', prefersDark );
  const correctAppearance = ( prefersDark || THEME === 'dark' ) ? 'dark' : 'light';
  require ( 'electron' ).remote.systemPreferences.setAppLevelAppearance ( correctAppearance );
  console.log ( 'setted appearance:', correctAppearance );
}, 1000 );

setTimeout ( () => {
  THEME = 'dark';
}, 30000 );
```

The fiddle works like this:

1. As I explained when explaining my use case, if the theme is dark or the preferred color scheme is dark then the appearance should be set to dark, otherwise it should be set to light.
2. The app starts with a light theme (at least for me that I don't have dark mode enabled at the system level), and it will switch to the dark theme in 30 seconds, triggering the dark appearance to be set.
3. In theory it should refresh the appearance every second.
4. Change the system-level appearance on your machine and notice how che media query isn't detecting further changes after that.

### Additional information

This has been broken at least since last August: https://github.com/electron/electron/issues/15540#issuecomment-523690718.

It'd be very nice if this got fixed so that we won't have to rely on Electron-only APIs for detecting system-level dark mode changes. Plus I guess relying on Electron's SystemPreferences causes an IPC call and those are kinda slow?

**Comment by fabiospampinato** [comment]
Actually in hindsight if that media query always listened for system-level changes I wouldn't be able to use it in my CSS if I'm overriding the app-level appearance, as the app-level appearance would be ignored 🤔 

I guess that actually makes sense then.

**Comment by fabiospampinato** [comment]
Actually I'm reopening this because there should be a way to listen to system-level changes somehow, and as far as I can tell I can only listen to macOS system-level changes by subscribing to the `AppleInterfaceThemeChangedNotification` notification.

But `prefers-color-scheme` supposedly detects a dark theme preference under Windows (and Linux?) too, how am I supposed to do that without `prefers-color-scheme`?

**Comment by MarshallOfSound** [comment]
> It just feels inconsistent that on the browser I can use it for detecting system-level changes and in Electron I basically can't if I'm overriding the app-level appearance.

It's not inconsistent at all, it works **the exact same way** just in Electron you can override the value it uses.

The scenario you want "force everything to be dark but listen for changes" is not possible because "force everything to be dark" means the OS will never report a change.

The three state switch that most apps implement is

* Follow System
* Force Dark
* Force Light

These settings line up perfectly with

* `nativeTheme.themeSource = 'system'`
* `nativeTheme.themeSource = 'dark'`
* `nativeTheme.themeSource = 'light'`

**Comment by MarshallOfSound** [comment]
Also to be clear, this is not broken, `nativeTheme` and that three state switch is **exactly** what apps in the wild use right now to do this.

**Comment by fabiospampinato** [comment]
> Also to be clear, this is not broken, nativeTheme and that three state switch is exactly what apps in the wild use right now to do this.

Well if I can't listen to system-level changes I'd argue there's something broken here, it doesn't matter what other apps do.

> The scenario you want "force everything to be dark but listen for changes" is not possible because "force everything to be dark" means the OS will never report a change.

I this an OS-level limitation then? 🤔 Which OS' have this limitation? Because at least under macOS I think I can listen to system-level appearance changes even when setting an appearance myself.

**Comment by MarshallOfSound** [comment]
> Well if I can't listen to system-level changes I'd argue there's something broken here, it doesn't matter what other apps do.

Just to make this super clear, this is an **OS limitation** there is nothing we can do about it.  File a `rdar` with apple and ask them to fix it...

> Because at least under macOS I think I can listen to system-level appearance changes even when setting an appearance myself.

No you can't, as soon as you override `appearance` on your app you will not be able to observe system theme changes correctly as of Catalina.

On Windows you can observe but certain bits of UI won't update depending on your configuration and on Linux it's basically a free-for-all.

I've spent a fair amount time looking at this and the current set up is the best of all worlds.

**Comment by fabiospampinato** [comment]
I see, thanks for the detailed explanation 👍
