### ISSUE TITLE
Python file not found

### ISSUE THREAD

**Issue by shafique18** [electron/electron#22222]
Hi,
I used a electron-packager to package a electron js application with --asar=true option, but when Im trying to run my application it gives me error as ;

Uncaught PythonShellError: C:\Users\ASUS X510\Anaconda3\envs\Shafique\python.exe: can't open file '"Project Directory"\resources\app.asar\engine\main_cleanup.py': [Errno 2] No such file or directory

Command I used for Packaging is
electron-packager . --overwrite --icon=F:\shafique\geo_icon.png --extra-resource=./engine/

Other details
OS - Windows 10 home
System - 64 bit

Folder which I mentioned in extra resource is visible to outer world and anyone can see the code easily, but I want to use hide the python code too from application which is not possible after asar packaging,
Please any one available for help to complete my process so I can make application with all hidden and working code.

Thanks, waiting for valuable and working responses.

**Comment by codebytere** [comment]
This should be opened as an issue on the [`electron-packager`](https://github.com/electron/electron-packager) repository.
