### ISSUE TITLE
v8_context_snapshot_generator is not stripped in the linux-x64 mksnapshot archive

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#22224]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  - v8.0.1
  https://github.com/electron/electron/releases/download/v8.0.1/mksnapshot-v8.0.1-linux-x64.zip
  - v7.1.12
  https://github.com/electron/electron/releases/download/v7.1.12/mksnapshot-v7.1.12-linux-x64.zip
  - v6.0.12
  https://github.com/electron/electron/releases/download/v6.0.12/mksnapshot-v6.0.12-linux-x64.zip

* **Operating System:**
  * N/A 

* **Last Known Working Electron version:**
N/A
v9.0.0-beta.2 is fine though.

### Expected Behavior

All binaries should be stripped.

### Actual Behavior

`v8_context_snapshot_generator` is not stripped in published archives.

### To Reproduce

> $ file mksnapshot-v8.0.1-linux-x64/v8_context_snapshot_generator
mksnapshot-v8.0.1-linux-x64/v8_context_snapshot_generator: ELF 64-bit LSB pie executable x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.2.0, BuildID[sha1]=38a6ad837b3b84fc2ecef0a50e6f7c4188a9376e, **with debug_info, not stripped**

### Additional Information

cc @MarshallOfSound , @jkleinsc

**Comment by jkleinsc** [comment]
#22094 should resolve this issue

**Comment by jkleinsc** [comment]
Resolved via #22257
