### ISSUE TITLE
Is systemPreferences.canPromptTouchID() actually deprecated?

### ISSUE THREAD

**Issue by dpeukert** [electron/electron#22238]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
Although it is marked as deprecated on the [website](https://www.electronjs.org/docs/api/system-preferences#systempreferencescanprompttouchid-macos), it has no deprecation notice or a replacement to use instead. I suspect it was accidentaly marked as deprecated in [this unrelated commit](https://github.com/electron/electron/pull/18477/files#diff-8330cc91b59f45f220fe480486215c97R385).

**Comment by codebytere** [comment]
You are very correct - i'll get that fixed up asap tomorrow. Thanks for surfacing it!
