### ISSUE TITLE
Transparent window with border radius shows white background.

### ISSUE THREAD

**Issue by IsmaeelAkram** [electron/electron#22243]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  v7.1.7
* **Operating System:**
  Windows 10 1903
* **Last Known Working Electron version:**
  v7.1.7

### Expected Behavior
Border gap should be transparent.

### Actual Behavior
Border gap shows white, not transparent.

### To Reproduce
```javascript
---main.js---
mainWindow = new BrowserWindow({
    width: 900,
    height: 685,
    frame: false,
    transparent: true,
    webPreferences: {
      nodeIntegration: true
    }
  });
---main.css---
html,
body {
  height: 100%;
  overflow: hidden;
}

body {
  margin: 0;
  padding: 0;
  font-family: sans-serif;
  transform: scale(0.998);
  border-radius: 15px;
}
```

### Screenshots
https://i.imgur.com/T7Uyz4H.png

**Comment by alizahid** [comment]
Same issue with Electron `^8.0.2` https://imgur.com/a/Cmgj4Ii

**Comment by ahallicks** [comment]
I am also setting the `backgroundColor` property on the window settings object to a transparent colour:

```backgroundColor: '#00FFFFFF'```

This seems to work fine and means there is no flash of a background colour as the app is loading. See more [here](https://www.electronjs.org/docs/api/browser-window#setting-backgroundcolor).

**Comment by ismaeelakram** [comment]
@ahallicks That worked, thanks!

**Comment by ismaeelakram** [comment]
@ahallicks Worked at first, but doesn't seem to now?? Still getting the same error even after it was fixed.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
