### ISSUE TITLE
webRequest onBeforeSendHeaders + onHeadersReceived CORS net::ERR_FAILED error

### ISSUE THREAD

**Issue by vladimiry** [electron/electron#22242]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** v9.0.0-beta.2, 10.0.0-nightly.20200216
* **Operating System:** Linux
* **Last Known Working Electron version:** 8.0.1

### Expected Behavior
The following text gets printed on screen on "Send cross-domain XHR request" button click:
```
{"status":422,"statusText":"Unprocessable Entity","responseText":"{\"Code\":10080,\"Error\":\"some-user-name@protonmail.ch does not exist. Did you mean SomeUsername@protonmail.com?\",\"ErrorDescription\":\"\",\"Details\":{}}"}
```
![ok](https://user-images.githubusercontent.com/1560781/74688785-cdc9b680-51e9-11ea-9c43-3f06fadee40b.png)

### Actual Behavior
The following text gets printed on screen on "Send cross-domain XHR request" button click:
```
{"status":0,"statusText":"","responseText":"EMPTY"}
XMLHttpRequest error
```
![error](https://user-images.githubusercontent.com/1560781/74688794-d1f5d400-51e9-11ea-93c3-b8a4e427572f.png)

### To Reproduce

https://github.com/vladimiry-playground/electron-quick-start-cors-issue2

**Comment by samuelmaddock** [comment]
There's a good chance this is related to this work ongoing in #19447. Chrome extensions now use their native implementation and could still need work to fully support some `chrome.*` extension APIs.

**Comment by vladimiry** [comment]
Can confirm issue resolving, thanks @zcbenz.

**Comment by airking05** [comment]
I repro in 8.1.1-9.0.0-beta.13 that responseHeaders cannot be changed by "onHeadersReceived".
I cannot add responseHeaders to "Access-Control-Allow-Origin" attribute at all...

**Comment by vladimiry** [comment]
@airking05 I think you need to open a new issue then, regression like.

**Comment by airking05** [comment]
@vladimiry thank you for reply.
I'll open a new issue :)

**Comment by vladimiry** [comment]
Great, since otherwise the issue won't be properly triaged and so won't be fixed.

**Comment by vladimiry** [comment]
@airking05 I have just tried to run repo from the first message using 9.0.0-beta.13 and 9.0.0-beta.14 and didn't notice the issue you listed. Also tried 9.0.0-beta.14 in https://github.com/vladimiry/ElectronMail and it work well there too (there is `onHeadersReceived` handler).
