### ISSUE TITLE
App crashed on win.webContents.print() while calling multiple times

### ISSUE THREAD

**Issue by aitldeveloper** [electron/electron#22252]
I build electron app for windows 32bit architecture and running webview in it. There is print bill functionality while order registered.  So when i register order multiple times then order receipts are printing and application crashed. Print bill function called from renderer process. So how to prevent from application crashing. Is my code is right way to print order receipt from renderer process?
Please help me out. Its urgent.

function printBill(orderId,printer) {
    let BillprintWindow = new BrowserWindow({ show: false });
    BillprintWindow.webContents.loadURL(location.origin + "/pos/printbill/" + orderId);
    BillprintWindow.once('ready-to-show', () => {
        console.log('in bill')
        setTimeout(function(){
            //BillprintWindow.show();
            if (printer != '') {
                BillprintWindow.webContents.print({ silent: true, deviceName: printer }, (e) => {
                    console.log(e);
                    BillprintWindow.close();
                    BillprintWindow=null;
                });
            } else {
                BillprintWindow.webContents.print({ silent: true }, (e) => {
                    console.log(e)
                    BillprintWindow.close();
                     BillprintWindow=null;
                });
            }
        },500)
    });
}

**Comment by amirwaild** [comment]
I have the same situation

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by lonelyWalkor** [comment]
me too

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our [comment above](https://github.com/electron/electron/issues/22252#issuecomment-591244587). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
