### ISSUE TITLE
Windows mouse back button causes renderer page reload

### ISSUE THREAD

**Issue by lishid** [electron/electron#22269]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

After using `history.pushState` to push a new browser history, use the mouse "back" navigation button commonly found on many mouses to navigate backwards. In all previous versions of Electron (7.1.12 and below), the page does not reload, and javascript event `popstate` is fired. Since 8.0.0, the page is reloaded.  `popstate` event is not fired, and `window.onbeforeunload` is skipped and ignored as well. Interestingly the forward button does not reload the page.

* **Electron Version:**
  * 8.0.0 and 8.0.1
* **Operating System:**
  * Windows 10 (1809)
* **Last Known Working Electron version:**
  * 7.1.12

### Expected Behavior
Expecting the page to not reload, and the `popstate` event to be fired.

### Actual Behavior
Page reloads and `popstate` event is fired.

### To Reproduce

Clone https://github.com/electron/electron-quick-start

renderer.js
```
history.pushState({}, '', location.href);

console.log('pushed history state');

window.addEventListener('popstate', (event) => {
	console.log(event);
});
```

#### 7.1.12
We see the event is logged.
![image](https://user-images.githubusercontent.com/609710/74784034-04004800-5275-11ea-8e8f-a3a712acec88.png)

#### 8.0.1
The page reloads and no event shows up.
![image](https://user-images.githubusercontent.com/609710/74784118-38740400-5275-11ea-927a-a55a04fd6e92.png)

**Comment by nornagon** [comment]
I believe this is fixed by #22202 and should be addressed in the next release. Reopen if this persists in 8.0.2.
