### ISSUE TITLE
Launching Electron Boilerplate in WSL

### ISSUE THREAD

**Issue by williamsalex** [electron/electron#22268]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
node_modules/.bin/electron --version returns same error as npm start
* **Operating System:**
Ubuntu 18.04.4 LTS running in WSL2 on Windows 10
* **Last Known Working Electron version:**
None
### Expected Behavior
Launch Electron App Boilerplate

### Actual Behavior
Returned error: 

[14306:0218/171510.423507:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/alex/final-project/electron-quick-start/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.

**Comment by MarshallOfSound** [comment]
The error message tells you how to fix this.

Please note that launching Electron in WSL will not work very well as WSL is headless and Electron is a GUI application, it won't show an actual window on your machine if you launch it through WSL

**Comment by williamsalex** [comment]
> The error message tells you how to fix this.
> 
> Please note that launching Electron in WSL will not work very well as WSL is headless and Electron is a GUI application, it won't show an actual window on your machine if you launch it through WSL

This is incorrect. Electron can be launched using MobaXterm's X server - or another remote client - by altering the display variables in WSL. My issue was with the sudoers file, which was not mentioned in the error message.
