### ISSUE TITLE
Uncaught Error: Invalid package when use fs.statSync in electron

### ISSUE THREAD

**Issue by hushiyun1994** [electron/electron#22279]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:6.0.7
  * 
* **Operating System:windows7
  * 
* **Last Known Working Electron version:**
  * 

### Expected Behavior
I want to use fs.statSync to a .asar file in electron.

### Actual Behavior
The asar.js throw err Uncaught Error: Invalid package D://1.asar;

### To Reproduce
open devtools in electron and entering the code.
`
const fs = require("fs");
fs.statSync("D://1.asar");
`

I checked the source code of asar.js.The cause of this bug may be that asar.js detected that the extension of this file is asar and intercepted it.

**Comment by codebytere** [comment]
This will work if you use [`original-fs`](https://www.npmjs.com/package/original-fs) instead - Electron overrides the `fs` module for asar purposes.
