### ISSUE TITLE
Allow developers to add new APIs to native Chrome extensions

### ISSUE THREAD

**Issue by samuelmaddock** [electron/electron#22285]
### Problem Description
As a user, I'd like to be able to use browser extensions found in web stores (ie. Chrome web store) within Electron applications.

As a developer, I'd like to provide this affordance by extending native Chrome extension APIs (`chrome.*`).

Currently there's no mechanism which allows developers to inject scripts into newly created isolated world script contexts. Preload scripts offer the ability to inject scripts into either
1. the main world of the top-level frame 
2. an isolated world of the top-level frame (via [`contextIsolation`](https://www.electronjs.org/docs/api/browser-window#new-browserwindowoptions))
3. either (1) or (2) in all frames (via [`nodeIntegrationInSubFrames`](https://www.electronjs.org/docs/api/browser-window#new-browserwindowoptions))

[Chrome extension content scripts](https://developer.chrome.com/extensions/content_scripts) are injected into isolated worlds starting at IDs defined by [`ElectronExtensionsRendererClient::GetLowestIsolatedWorldId()`](https://github.com/electron/electron/blob/master/shell/renderer/extensions/electron_extensions_renderer_client.cc#L26). These world IDs are inaccessible from preload scripts.

### Proposed Solution

One possible solution which can reuse existing concepts would be to redesign the preload scripts API. Instead of setting global preferences for preload script injection using the [`webPreferences` option](https://www.electronjs.org/docs/api/browser-window#new-browserwindowoptions), script injection options could be defined per-preload script. This would take heavy inspiration from Chrome extension content scripts.

```ts
interface PreloadScript {
  /** Path to preload script. */
  script: string

  /** Whether this preload script requires node integration. */
  nodeIntegration: boolean

  /** Whether to inject into all frames. */
  allFrames: boolean

  /** Which script contextes should the preload script be injected into. */
  context:
    | 'main'        // main world (0)
    | 'isolated'    // isolated world (999) - default
    | 'extensions'  // extension isolated worlds ([1 << 20]+)
    | 'any'         // any newly created script context
}

const preloadScripts: PreloadScript[] = [
  {
    script: 'preload.js',
    nodeIntegration: true,
    context: 'isolated'
  },
  {
    script: 'custom-chrome-apis.js',
    allFrames: true,
    context: 'extensions'
  }
]

session.defaultSession.setPreloads(preloadScripts)
```

#### 1. Chrome extension JS bindings system

Native Chrome extensions provide an API for binding [features](https://chromium.googlesource.com/chromium/src/+/master/chrome/common/extensions/api/_features.md) to extension script contexts. The [Extension Bindings documentation](https://chromium.googlesource.com/chromium/src.git/+/master/extensions/renderer/bindings.md) provides more details.

Initially, Chrome API features were implemented using JavaScript. This binding mechanism is now only used for [legacy APIs and will eventually be replaced](https://chromium.googlesource.com/chromium/src.git/+/master/extensions/renderer/bindings.md#legacy-javascript-implementations). Using inspiration from this API, a new JS binding mechanism could be provided by Electron to fully extend Chrome extensions.

#### 2. 'created-script-context' event for renderer webFrame

When extensions are injected into the renderer, they need to create a new script context first. There's a handy method on the `RendererClientBase` class which could be modified to accept the world ID.

```diff
# shell\renderer\renderer_client_base.h
-virtual void DidCreateScriptContext(v8::Handle<v8::Context> context,
-                                    content::RenderFrame* render_frame);
+virtual void DidCreateScriptContext(v8::Handle<v8::Context> context,
+                                    content::RenderFrame* render_frame,
+                                    int32_t world_id);
```

By forwarding this information to the `webFrame` API, we could emit it as an event. Preload scripts could listen for this event to know when extension script contexts are created.

Additionally, [`extensions::ScriptContextSet::GetContextByV8Context`](https://source.chromium.org/chromium/chromium/src/+/master:extensions/renderer/script_context_set.h;bpv=1;bpt=1;l=76?originalUrl=https:%2F%2Fcs.chromium.org%2F) would allow us to know whether it's used to manage an extension. Metadata about the extension could be passed to the event as well.

```ts
// preload.js
webFrame.on('created-script-context', (worldId: number) => {
  if (isExtensionWorld(worldId)) {
    webFrame.executeJavaScriptInIsolatedWorld(worldId, [
      { url: 'custom-chrome-apis.js' }
    ])
  }
})
```

```ts
// custom-chrome-apis.js
window.chrome = {
  browserAction: {
    setTitle(details, cb) {
      // ...
    }
  }
}
```

##### `chrome.ipcRenderer`

The last piece to this solution would be to provide the `ipcRenderer` API to Chrome extensions. That way the custom APIs like `browserAction` can talk to the browser process.

This would be potentially dangerous as trusting all extensions with the `ipcRenderer` API is not great. Chrome's extension system has a permissions system where some APIs are only injected based on the context of the script (see [`Feature::Context`](https://source.chromium.org/chromium/chromium/src/+/master:extensions/common/features/feature.h;l=33-42;drc=1c6c6f193ffb7aba1266864125463375e5b7d836;bpv=1;bpt=1?q=BLESSED&ss=chromium%2Fchromium%2Fsrc&originalUrl=https:%2F%2Fcs.chromium.org%2F) enum).

Creating a new native extension feature only allowed for special Electron extension contexts might be a way to do this. After adding new `chrome.*` APIs, the injected script could then call `delete chrome.ipcRenderer` to prevent the extension from using it.

### Additional Information
ref #19447

**Comment by sentialx** [comment]
Alternatively, if you prefered avoiding introducing this kind of breaking changes, there could be an API in `webFrame` called `injectChromeAPI` taking as an argument an object of user defined `chrome` APIs to merge with the existing native implementation. This method would check whether the current `webContents` are an extension background page and inject the specified `chrome` APIs into the corresponding world without bothering the user which world they should inject to.

**Comment by samuelmaddock** [comment]
I've added another alternative which involves adding a new event to `webFrame` to know when extension scripts contexts are created. I'm not sure how to solve IPC yet though.

@sentialx ^ this idea is somewhat similar to yours

**Comment by sentialx** [comment]
@samuelmaddock Wouldn't importing the ipcRenderer in the preload and using it in the setTitle method work?

**Comment by samuelmaddock** [comment]
> 
> 
> @samuelmaddock Wouldn't importing the ipcRenderer in the preload and using it in the setTitle method work?

In the example I wrote, the preload script and the script injected into the isolated world would be in different files. The important point is that these are run in different script contexts.

The preload script's context will have access to the `ipcRenderer` API.
The extension's isolated world script context will not.

It might be possible to add the APIs into the isolated world script context though. I'll have to look into that more.

**Comment by sentialx** [comment]
@samuelmaddock It's possible to do something like this:
```typescript
const { webFrame, ipcRenderer } = require('electron');

(async () => {
  const w = await webFrame.executeJavaScriptInIsolatedWorld(2, [
    {
      code: 'window',
    }
  ]);

  w.ipcRenderer = ipcRenderer;

  await webFrame.executeJavaScriptInIsolatedWorld(2, [
    {
      code: 'console.log(window.ipcRenderer)', // outputs: EventEmitter
    }
  ]);
})();
```

**Comment by sentialx** [comment]
It's possible to do that:
```typescript
const { webFrame, ipcRenderer } = require('electron');

(async () => {
  const w = await webFrame.executeJavaScriptInIsolatedWorld(worldId, [
    {
      code: 'window',
    }
  ]);

  w.ipcRenderer = ipcRenderer;

  await webFrame.executeJavaScriptInIsolatedWorld(worldId, [
    {
      code: 'console.log(window.ipcRenderer)',
    }
  ]);
})();
```
But developers will need to remember calling `delete window.ipcRenderer` in the end. And this is not good.

**Comment by euglv** [comment]
Now with recent versions of electron it possible to add new API to chrome extension manifest v2 background pages.
Preload script added to `BrowserWindows` using `webPreferences` or `<webview preload="...">` do not work for background pages.
But preload scripts added to [session](https://www.electronjs.org/docs/latest/api/session#sessetpreloadspreloads) work for extension background pages:
```
const { session } = require('electron')

session.defaultSession.setPreloads(...)
// or
session.fromPartition(...).setPreloads(...)
```
If there are extensions loaded then session preload script will execute several times after loading new URL, for the main web page and for each extension background page. 
Inside `preload.js` you can check if preload script is loaded into background page context this way:
```
if (location.href.startsWith('chrome-extension://')) {
...
}
```

But extension manifest v3 background scripts are service workers, and the above methods do not work. There is no way to add preload scripts to service workers. 
May be something like this https://github.com/electron/electron/pull/28923 may help to implement new API in manifest v3 extension background scripts.

**Comment by samuelmaddock** [comment]
A subset of the requests in this issue will be addressed by https://github.com/electron/rfcs/pull/8
