### ISSUE TITLE
[bug?] [linux] Resizing electron window causes previous window to go blank

### ISSUE THREAD

**Issue by trusktr** [electron/electron#22289]
I'm not entirely sure this is an Electron issue instead of a VS Code issue.

Some times switching to another Electron window (VS Code window) and then _resize_ that window, the previous window stops rendering properly and shows only the window background.

I can switch back to the previous window and resize it to make it render again, but then the new-previous window goes blank.

After some time, some windows get stuck not rendering and resizing does not bring them back.

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**

```json
{
  "node": "12.4.0",
  "v8": "7.6.303.31-electron.0",
  "uv": "1.29.1",
  "zlib": "1.2.11",
  "brotli": "1.0.7",
  "ares": "1.15.0",
  "modules": "73",
  "nghttp2": "1.39.2",
  "napi": "4",
  "llhttp": "1.1.3",
  "http_parser": "2.9.2",
  "openssl": "1.1.0",
  "icu": "65.1",
  "unicode": "12.1",
  "electron": "6.1.7",
  "chrome": "76.0.3809.146"
}
```

in Manjaro Linux rolling release, kernel 5.4.

### Expected Behavior

I expect the UI of all windows to keep rendering properly even if the window is not in focus.

### Actual Behavior

Here's a video showing how switching windows and resizing them causes them to start rendering while the unfocused windows goes blank:

![render-glitch](https://user-images.githubusercontent.com/297678/74870901-60b04100-530f-11ea-8d97-fe7d83051535.gif)

Here's a video showing when I open devtools, the rendering of window stops appearing even when resizing:

![render-glitch-2](https://user-images.githubusercontent.com/297678/74871107-c3a1d800-530f-11ea-9a81-d10de69cde38.gif)

But it isn't necessarily triggered by dev tools. Sometimes, one window simply never renders again.

As long as I have any electron (VS Code) windows open, the problem persists on some window, and the only way to fix it is to completely quit out of VS Code (close all windows), and restart.

It seems to have to do with switching active Chrome contexts.

Here's a video showing that when I open devtools, the rendering of the main content is frozen, although the underlying UI still seems to be active:

![glitch3](https://user-images.githubusercontent.com/297678/74871581-8f7ae700-5310-11ea-9e82-e34ee9b8290b.gif)

### To Reproduce

I've no idea how to trigger it. It might have to do with when I switch from an external display to my laptop display, or vice-versa, but I'm not sure yet.

**Comment by trusktr** [comment]
Similar issues:

- https://github.com/nstudio/xplat/issues/155 which seem identical to:
  - https://github.com/electron/electron/issues/18510
  - https://github.com/electron-userland/electron-builder/issues/2662
  - https://github.com/ionic-team/ionic/issues/19246

Additionally search for "electron blank screen" or similar searches and you'll find more issues, like https://github.com/ionic-team/capacitor/issues/1688.

**Comment by ChALkeR** [comment]
Do you perhaps have glibc 2.31 installed?
