### ISSUE TITLE
Document `BrowserWindow#removeAllListeners`

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#22290]
### Issue Details

* **Electron Version:**
  * 7.10

Apparently `BrowserWindow` instances have a `removeAllListeners` method, but this isn't mentioned in the docs and the typescript types don't report it.

**Comment by siddharth25pandey** [comment]
I want to work on this issue. Kindly help me out how to resolve this issue.
Thanks!

**Comment by benrbray** [comment]
I suspect this issue can probably be closed, since `removeAllListeners` was included in the typings since at least Electron 9, and removed again in Electron 12.  The electron docs have a [warning](https://www.electronjs.org/docs/api/remote) against using `removeAllListeners` on a `BrowserWindow`.

**Comment by dsanders11** [comment]
Closing this as it's documented that `BrowserWindow` extends `EventEmitter`, and `removeAllListeners` is one of the methods on `EventEmitter`. The typings should pick it up.

@fabiospampinato, if you think this is still an issue, please ping me and I'll reopen the issue. 🙂
