### ISSUE TITLE
Pass a function from main to renderer process

### ISSUE THREAD

**Issue by kitattyor** [electron/electron#22296]
### Issue Details

* **Electron Version:**
  * Electron 8.0.0
* **Operating System:**
  * Win10

I cannot pass a function to a renderer process from the main process

I would like to send a function from my main to renderer process

I have an function which I export from the ```db.services.js``` module

    // db.services.js
    const MongoClient = require('mongodb').MongoClient;
    const assert = require('assert')
    
    var DatabaseService = (function () {
        "use strict";
        var instance; //prevent modification of "instance" variable
        function Singleton() {
            if (instance) {
                return instance;
            }
            instance = this;
        }
    
        Singleton.create = function (db_uri) {
            //Singleton initialization code
            this.db_uri = db_uri
            this.db = undefined
            this.a = 0 // debugging async behavior
        }
    
        //instance accessor
        Singleton.getInstance = function () {
            return instance || new Singleton();
        };
    
        Singleton.getDB = function () {
            return this.db.db('xFilterDB') // directly return the used DB
        }
    
        Singleton.establishConnection = function (callback) {
            ... 
        }
    
        return Singleton;
    }());
    
    // exporting a "singleton" object to use with all views
    DatabaseService.getInstance();
    
    module.exports = DatabaseService;

I 'import' the function into my main electron process ```app.js```

    // app.js
    
    const {
        app,
        BrowserWindow,
        ipcMain
    } = require('electron');
    
    const isDev = require('electron-is-dev');
    const DatabaseService = require('./services/db.services'); 
    app.on('ready', function () {
        DatabaseService.getInstance();
        DatabaseService.create("mongodb://localhost:27017");
        
        mainWindow = new BrowserWindow({
            width: 1024,
            height: 768,
            webPreferences: {
                nodeIntegration: true
            }
        })
        let url = 'file://' + __dirname + '/views/main.html'
        mainWindow.loadURL(url)
        mainWindow.webContents.on('did-finish-load', () => {
            console.log(DatabaseService);

            // 
            // [Function: Singleton] {
            //   create: [Function],
            //   getInstance: [Function],
            //   getDB: [Function],
            //   establishConnection: [Function],
            //   db_uri: 'mongodb://localhost:27017',
            //   db: undefined,
            //   a: 0
            // }

            mainWindow.webContents.send('database-service', 
                DatabaseService);  // <-- I am sending the function here
        });
        windows.push(mainWindow)
    }

In main.html I do 

    <script>
            require('./main.js')
    </script>

And in main.js

    //main.js
    
    ipcRenderer.on('database-service', (event, args) => {
        // ----- mongo connection ESTABLISH REGION START----
        // implicit async
        console.log(args); // <-- args is null here 
        ...
    }

Any idea what is going wrong here?

Also, apparently this ```webContents.send('database-service', DatabaseService)``` is deprecated. So a better solution will be doubly appreciated.

### Expected Behavior
`args` should not be null, it should be an array with the only element being the function that's sent 

### Actual Behavior
`args` is null

### To Reproduce

Code is provided.

**Comment by kitattyor** [comment]
The exports can be simplified

```
module.exports = function() {
    return "Hello";
}
```

But this doesn't work too.

**Comment by MarshallOfSound** [comment]
IPC serializes all content, this means complex things like functions, prototypes and promises can't be sent over IPC.  You'll need to use message passing and some combination of `ipcMain.handle` and `ipcRenderer.invoke` to "call" your method from the renderer process

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
