### ISSUE TITLE
-webkit-app-region: drag is disabled by -webkit-app-regon: no-drag in an iframe (on windows)

### ISSUE THREAD

**Issue by jonathon-love** [electron/electron#22297]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.1
* **Operating System:**
  * Windows (many different versions)
* **Last Known Working Electron version:**
  * 1.8

if you load the following in a frameless window on windows, the blue app-drag region will not work. if you remove the `-webkit-app-region: no-drag` from the div in the iframe, it works (or if you resize the window). this bug was introduced in version 2.0.

```
<!DOCTYPE html>
<html>
  <body>
    <div style="height: 50px ; -webkit-app-region: drag ; background-color: blue ;"></div>
    <h1>Hello World!</h1>
    <iframe srcdoc="<!DOCTYPE html><html><body><div style='width: 30px ; height: 30px ; background-color: red ; -webkit-app-region: no-drag ;'>fred</div></body></html>"></iframe>
  </body>
</html>
```

possibly related to #21621

**Comment by xland** [comment]
Electron 10.1.1 has this issue too.

How about this issue's progress?

**Comment by xland** [comment]
How about this issue's progress?

**Comment by janwendt** [comment]
Any Progress here?
I can confirm this bug is still in Electron 13.

**Comment by yuhengshen** [comment]
mac also. iframe `-webkit-app-regon: drag/no-drag`  will  all prevent dragging.

v17 work around:

```js
dragElement.style.appRegion = "no-drag";
setTimeout(() => {
  dragElement.style.appRegion = "drag";
}, 10);
```

**Comment by hulong-prong** [comment]
> Electron 10.1.1 has this issue too.Electron 10.1.1 也有这个问题。 How about this issue's progress?这个问题的进展如何？ Is there a way to get around this issue?有没有办法解决这个问题？ @sofianguy

请问有解决这个问题吗
