### ISSUE TITLE
Entire Application Is Crashing On File Dialog

### ISSUE THREAD

**Issue by bekalshenoy** [electron/electron#22301]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.
### Issue
when calling `<input type="file">` the entire application crashes. Also using `remote.dialog` is also causing crashing of application. I Am using 9.0.0-beta.2 and ubuntu 20.04

**Comment by bekalshenoy** [comment]
### Update
file dialog works in windows

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

**Comment by bekalshenoy** [comment]
I forked electron-quick-start and installed 9.0.0 and added `<input type="file">` after that what happened see [here](https://youtu.be/UTj5HUa_ias)

**Comment by bekalshenoy** [comment]
I have tried above to ^8 and ^7 and the result is same.when running ^7 it shows error `[6492:0228/082510.036243:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command`. Is it a problem of electron or my version of ubuntu

**Comment by bekalshenoy** [comment]
when i build my package in ^8 it worked. It also worked when i build on ^7. But it will not work in development. When i build ^9 it has a new issue when i open my build it crashes and never opens
