### ISSUE TITLE
Electron ignores Win32 SetWindowPlacement API calls

### ISSUE THREAD

**Issue by nlundquist** [electron/electron#22306]
### Preflight Checklist
- [x] I have read the Contributing Guidelines for this project.
- [x] I agree to follow the Code of Conduct that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.1+
* **Operating System:**
  * Windows
* **Last Known Working Electron version:**
  * < 6.1

### Expected Behavior
Electron-based applications should obey the SetWindowPlacement API call like any other native Windows application.

### Actual Behavior
Electron-based applications ignore SetWindowPlacement API calls and do not change placement or size. 

### To Reproduce
I first noticed this issue when using the Windows interface enhancement tool AquaSnap with the Electron-based app Discord, so that's how I'll be describing reproduction. However, this issue is reproducible with any recent Electron-based app & any incoming SetWindowPlacement call.

When using AquaSnap in Windows, DBLCLICK'ing the draggable "resize handle" on the border of a window results in that window being resized in that direction automatically, snapping to the nearest neighbor. This is done via the SetWindowPlacement Windows API call. When attempting this with Discord, or another Electron app, the call is ignored. This is just one simple instance of the functionality that's broken due to the ignored SetWindowPlacement.

I've never AquaSnap fail with any resizable app up until very recent versions of Discord. Even X11 apps running in the WSL work. I don't think this is acceptable behavior to have across all Electron apps.

**Comment by nlundquist** [comment]
I believe this issue was introduced with this change: https://github.com/electron/electron/pull/21813/commits

**Comment by nlundquist** [comment]
Interestingly this issue doesn't effect the most recent version of Slack. Would imply that this is a rather recent bug.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
