### ISSUE TITLE
BrowserWindow.webContents.focus doesn't work on mac

### ISSUE THREAD

**Issue by CezaryKulakowski** [electron/electron#22305]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
10.0.0-nightly.20200220
* **Operating System:**
macOS 10.15.1
* **Last Known Working Electron version:**
I don't know (judging by implementation it never worked)

### Expected Behavior:
Call to BrowserWindow.webContents.focus focuses proper window

### Actual Behavior:
Call  to BrowserWindow.webContents.focus does nothing

### To Reproduce:

Run following simple app:
```
const { app, BrowserWindow } = require('electron')

function createWindow () {
  let win1 = new BrowserWindow({ x:100, y: 300, width: 300, height: 200 })
  win1.on('closed', () => {
    win1 = null
  })
  win1.loadURL('https://github.com')

  let win2 = new BrowserWindow({ x:300, y: 300, width: 300, height: 200 })
  win2.on('closed', () => {
    win1 = null
  })
  win2.loadURL('http://www.example.com')

  setTimeout(() => {
    win1.webContents.focus();
  }, 3000);
}

app.on('ready', createWindow)
```

It works as expected on Windows: it creates two windows and after three seconds it focuses the first one. On mac it doesn't work and call to `webContents.focus` doesn't change the focus (it stays on the second window).

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by CezaryKulakowski** [comment]
I've create pr for the issue: https://github.com/electron/electron/pull/22323
