### ISSUE TITLE
版本号多加了v

### ISSUE THREAD

**Issue by devmings** [electron/electron#22316]
ELECTRON_CUSTOM_DIR默认值是 版本号前面加了V

**Comment by chanble** [comment]
https://github.com/electron/get/issues/123 这个项目的问题，自己下载对应版本文件吧

**Comment by chanble** [comment]
估计electron以后路径都要同一加v了

**Comment by chanble** [comment]
https://github.com/cnpm/cnpmjs.org/issues/1551 这里有办法

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
