### ISSUE TITLE
Can't proxy my primus connection

### ISSUE THREAD

**Issue by Bojack92160** [electron/electron#22311]
I'm using engine.io client in primus with electron, because I make a websocket connection to a server. I want to use a proxy, therefore I use a custom agent (https-proxy-agent), but it keep connecting directly instead of through the proxy. Here is what I have done:

```
let module = {
      transport: { //in primus, options for the specific transformer are put here
        agent: new HttpsProxyAgent(url.parse('http://Username:Pswd@IP:Port')),
        forceNode: true //because I use electron so I force him to use nodeJs environment 
      },
      strategy: "disconnect,timeout",
      reconnect: {
        max: 5000,
        min: 500,
        retries: 10
      }
    }

primus = new Primus(Myurl, module);
```
I do not get any error/warning message or anything. 

I can use https-proxy-agent for simple http request, and it work (the request is well proxified). At this point I think the problem is from electron because we can use custom agent only in a nodeJs environment (but electron is hybrid nodejs/chromium right? and the forceNode option is set to True so what the shit?) ...

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
