### ISSUE TITLE
shell.openItem does not exist in electron 10 nightly builds

### ISSUE THREAD

**Issue by godza** [electron/electron#22312]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v10.0.0-nightly.20200218
* **Operating System:**
  * macOS 10.15.3
* **Last Known Working Electron version:**
  * i used really old version before (2.x)

### Expected Behavior
I expected to open my log file when opening it with shell.openItem

### Actual Behavior
Got an error that openItem function does not exist

### To Reproduce
Just try to reproduce in v10.

### Screenshots
![Screenshot](https://i.imgur.com/xCf8aOr.png"Screenshot")

### Additional Information
Other shell functions like showItemInFolder and openExternal are working as expected

**Comment by codebytere** [comment]
That's correct, that change was intentionally made. See https://github.com/electron/governance/blob/master/wg-api/spec-documents/shell-openitem.md.

**Comment by godza** [comment]
Thanks, i've searched the documentation to see if there was an announcement regarding this method, but obviously i missed this page.

Thanks for helping out
