### ISSUE TITLE
Docs / question regarding require() vs remote.require() with node APIs (such as fs)

### ISSUE THREAD

**Issue by johot** [electron/electron#22319]
One thing I would like help understanding and also perhaps helping out with documenting better is the difference between the following code (in the render process):

```
const fs = require("fs");
const remote = require('electron').remote
const fs = remote.require("fs");
```

So the question is, when we require a node module (such as fs) vs doing it via `remote.require` are we actually doing the same thing? I know that `remote.require` acts as a proxy layer between the node / main process and the browser window, is the same thing true when just doing a "regular" require (`const fs = require("fs")`) from the render process to use a node API?

Thank you!

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
