### ISSUE TITLE
Not able to login to youtube account within webview or BrowserWindow

### ISSUE THREAD

**Issue by circleapps** [electron/electron#22346]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.13
* **Operating System:**
  * macOS 10.15.3

### Expected Behavior
All google accounts should be able to login youtube account within webview or BrowserWindow

### Actual Behavior
Only old google account  can login youtube account successfully within webview or BrowserWindow.
If you use a newly created google account (or create it recently), you can NOT login to youtube.

### To Reproduce
1. Create a BrowserWindow
2.  mainWindow.loadURL('https://youtube.com')
3. Login with your google account created recently
 
In the Browser Window, Youtube display this error: This browser or app may not be secure. 

![image](https://user-images.githubusercontent.com/44904628/75106797-1f939600-565b-11ea-8e03-6bed8bc78d5e.png)

To reproduce it,

```sh
$ git clone https://github.com/circleapps/electron-quick-start.git
$ npm install
$ npm start
```

### Additional Information
I tried to use electron 6, 7 and 8, got the same result.

**Comment by codebytere** [comment]
What other settings do you have on your computer? I just created a new account and was able to log in no problem with your repro.

**Comment by MarshallOfSound** [comment]
This is account specific and Google is applying this protection based on useragent to random accounts.  It's out of our control.

If you don't like it, take it up with Google https://security.googleblog.com/2019/04/better-protection-against-man-in-middle.html

**Comment by circleapps** [comment]
Thanks, I accept this resolution, since there is nothing we could do about it.

**Comment by paulkoeckdev** [comment]
`<webview useragent="Mozilla/5.0 (Windows NT 10.0; rv:74.0) Gecko/20100101 Firefox/74.0"></webview>`

Works perfectly for me!
