### ISSUE TITLE
Cookies aren't retrieved when cookie has sameSite=strict, secure and http only

### ISSUE THREAD

**Issue by pavloldev6** [electron/electron#22345]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.0
* **Operating System:**
  * macOS 10.13.6
* **Last Known Working Electron version:**
  * 5.0.13

### Expected Behavior

When using session.cookies.get({}) expect cookies which are secure, httpOnly, have sameSite=strict to be retrieved, which works fine in version 5.0.13.

### Actual Behavior

Certain cookies can be retrieved. Can still retrieve cookies which are not secure, not httpOnly. But cookies which are secure, httpOnly, have sameSite=strict aren't retrieved starting with version 6.0.0. 
### To Reproduce

```sh
$ git clone https://github.com/pavloldev6/electron-quick-start.git -b secure-cookies-get-problem
$ npm install
$ npm run http-server (in one terminal)
$ npm run start (in another terminal)
```
Simple server runs on port 3000 and accepts requests on endpoint called /hello which would set a sessionId cookie on response

Simple electron app makes a request to /hello endpoint and upon request completion retrieves the cookie that was set (this is version 5.0.13)

Observe the cookie is retrieved, it should be logged with "Cookies retrieved:"

Then:
```sh
$ npm install electron@6.0.0
```
Close and reopen the Electron app with _npm run start_ and request will be reissued. Observe the cookies aren't retrieved after request completes.

### Additional Information

I would like to help with what I can to resolve this issue.

**Comment by pavloldev6** [comment]
@sofianguy it is labelled for version 6 only, however it affects all versions after

**Comment by johnli611** [comment]
+1 this is keeping our users from staying logged in as the cookies aren't being saved. Any workaround?

**Comment by lehetap** [comment]
This behaviour may be due to a fact that Chrome has changed default value for SameSite attribute from None to Lax. So if a cookie does not have SameSite explicitly set it won't be None anymore but which makes some restrictions and can possibly prevent certain cookies from being retrieved.

**Comment by patchworkfish** [comment]
Does this thread continue for a supported version? I have the same issue and would like to know more. Setting cookies from my server to sameSite = "strict" or sameSite = "lax"  means the cookies are not picked up by my electron client. Only if sameSite = "none". Does this mean that I need to use "none" if using cookies (for example a jwt) with electon?
Electron version: 13.1.2

**Comment by ivictbor** [comment]
Related issues might be usefull:

if you are using webSecurity=false then you should know that at some point it stopped working https://github.com/electron/electron/issues/23664

Also if SameSite is not specified, at some point all Chromes started deafult it to Lax (It was none before) https://github.com/electron/electron/issues/21509

**Comment by AntonDemarczyk** [comment]
a little bit hacky, but it works for me:

```	
session.defaultSession.webRequest.onHeadersReceived(
	{ urls: ['https://my.trusted.url/*/*'] },
	(details, callback) => {
		if (
			details.responseHeaders &&
			details.responseHeaders['Set-Cookie'] &&
			details.responseHeaders['Set-Cookie'].length &&
			!details.responseHeaders['Set-Cookie'][0].includes('SameSite=none')
		) {
			details.responseHeaders['Set-Cookie'][0] = details.responseHeaders['Set-Cookie'][0] + '; SameSite=none';
		}
			callback({ cancel: false, responseHeaders: details.responseHeaders });
	},
);
```

**Comment by demchuk-alex** [comment]
@AntonDemarczyk it did help me either! I've made it concise though, only difference I had it empty so it's been by default `SameSite=Lax`

```javascript
appSession.webRequest.onHeadersReceived({ urls: [cookieFilter] }, (details, callback) => {
        const cookies = details.responseHeaders['Set-Cookie'];
        if(cookies) {
            const newCookie = Array.from(cookies)
                .map(cookie => cookie.concat('; SameSite=None'));
            details.responseHeaders['Set-Cookie'] = [...newCookie];
            callback({
                responseHeaders: details.responseHeaders,
            });
        } else {
            callback({ cancel: false });
        }
    });
```

**Comment by ZOUYIQAQ** [comment]
> 有点老套，但它对我有用：
> 
> ```
> session.defaultSession.webRequest.onHeadersReceived(
> 	{ urls: ['https://my.trusted.url/*/*'] },
> 	(details, callback) => {
> 		if (
> 			details.responseHeaders &&
> 			details.responseHeaders['Set-Cookie'] &&
> 			details.responseHeaders['Set-Cookie'].length &&
> 			!details.responseHeaders['Set-Cookie'][0].includes('SameSite=none')
> 		) {
> 			details.responseHeaders['Set-Cookie'][0] = details.responseHeaders['Set-Cookie'][0] + '; SameSite=none';
> 		}
> 			callback({ cancel: false, responseHeaders: details.responseHeaders });
> 	},
> );
> ```
This does work, but there are a few things that need to be changed, change "Set-Cookie" to "set-cookie" and change the "; SameSite=none" add "; Secure" become "; SameSite=none;  Secure".
Because the "SameSite=none" parameter requires "Secure" to enable.
