### ISSUE TITLE
devtool don‘t response to any mouse event 

### ISSUE THREAD

**Issue by tsxuehu** [electron/electron#22340]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.1
  * 8.0.0
  * 7.1.8
  * 6.1.6
* **Operating System:**
  * mac 10.15.3
* **Last Known Working Electron version:**
  * 4.2.12
  * 5.0.9

### Expected Behavior
devtool of a webview works normal

### Actual Behavior
devtool of a webview do not response to mouse event

### To Reproduce
Example: https://github.com/tsxuehu/devtool-not-work-example
Run Example:
```sh
$ git clone git@github.com:tsxuehu/devtool-not-work-example.git -b master
$ npm install
$ npm start
```
 when run `npm start`, it will start electron with option --remote-debugging-port=8899
 page has two webview tag. webview 1 open a url, webview 2 open the devtool of webview 1.
1. set a debugger on test.js line 2 in webview 2
2. click the refresh button on the top
3. then the debugger point is triggered，now webview don‘t response to any mouse event 

### Screenshots
![page](https://b.yzcdn.cn/public_files/51c2de80e6a3f356615b7d7dc82bb32f.png)

**Comment by ccckblaze** [comment]
any updates?

**Comment by cz2013** [comment]
We have same problem. electron seems not support <webview> very well. Is there any way except use BrowserWindow?

**Comment by ccckblaze** [comment]
it turns out the "pause state overlay" option caused this issues, but why this will effect the whole devtools still remains a mistery, i have recompile the devTools from the source code, and hard coded this settings to be off.
sadly, still no properly solution

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
