### ISSUE TITLE
Document how App icons need to be assembled for light and dark mode

### ISSUE THREAD

**Issue by guw** [electron/electron#22348]
### Problem Description

I'd like to provide an app icons on Mac OS which supports regular as well as dark mode. 
I have two different versions of my icon for that purpose.

### Proposed Solution

Documentation how such icons can be packages and included in Electron.

**Comment by MarshallOfSound** [comment]
macOS has no built in declarative way of doing this (unlike iOS).  You can use `app.dock.setIcon` to achieve this yourself however at runtime

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

**Comment by guw** [comment]
@MarshallOfSound Thanks for looking into the issue. I found [this article](https://developer.apple.com/documentation/uikit/uiimage/providing_images_for_different_appearances) and it shows that Xcode has a way to combine multiple appearances of an image for presentation. I opened the issue because I think this might be either lack of documentation in Electron or lack of support.

**Comment by MarshallOfSound** [comment]
@guw If you check that article is in the "UIKit" category which is just for iOS and tvOS apps, there is no macOS support for this from apple (as per my original comment)

**Comment by guw** [comment]
Wow, that's confusing. It says macOS further below in the text. That's why I assumed it's applicable to macOS too.
