### ISSUE TITLE
Enhancement: Electron version with FIPS 140-2 support

### ISSUE THREAD

**Issue by alejandroclaro** [electron/electron#22359]
**Preflight Checklist**

- [x] I have read the Contributing Guidelines for this project.
- [x] I agree to follow the Code of Conduct that this project adheres to.
- [x] I have searched the issue tracker for a feature request that matches the one I want to file.

**Problem Description**

Electron has no support for FIPS 140-2 in underlying `crypto` and `https` packages (core NodeJS packages), nor in the Chromium layer.

FIPS 140-2/3 is a common security standard products need to meet to qualify for contracts offered by many Governments. 

I found a similar _issue_ [(#20120)](https://github.com/electron/electron/issues/20120), but it was discarded and closed because was related to OpenSSL. However, BoringSSL also has a FIPS compliant mode.

**Proposed Solution**

Provide a compilation flag to enable FIPS 140-2 complaint mode (BORINGSSL_FIPS), and release two flavors of Electron (one non-complaint, and another complaint).

**Comment by codebytere** [comment]
Given that this is not currently on a roadmap for the core team and has been open for years, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR.

**Comment by alejandroclaro** [comment]
I understand what you mean, but for many working for government-related projects, this is a must. Also, I think it could be very important as an electron security feature. 

I think there could be another option to allow using FIPS 140-2 compliant libraries like OpenSSL, and also solve problems with some NodeJS packages that depend directly on OpenSSL.

BoringSSL allows adding a namespace or a prefix to it symbols, and maybe chromium also supports it. If that is the case, if Electron is compiled with this option, the symbols will not clash with the symbols in OpenSSL library or any other fork of it; and it will be possible to use a Nodejs module to perform cryptographic operations using another library without problems.

Another similar option is that both chromium and NodeJS versions in electron are compiled hidden the BoringSSL symbols.

@codebytere, @sofianguy What do you think about these options?

**Comment by sregger** [comment]
@alejandroclaro did this issue ever make any headway?

**Comment by alejandroclaro** [comment]
> @alejandroclaro did this issue ever make any headway?

Hi @sregger. Not advances here. We decided to use a FIPS 140-3 validated commercial third-party library for cryptographic operations and create a native Nodejs module to wrap the operations that we need.

**Comment by gannons** [comment]
That's an interesting item @nornagon. I'm hesitant to believe it can be that easy. But it's worth investigating.

**Comment by sregger** [comment]
That's an interesting note @nornagon. I'm hesitant to believe it will be that easy. But it's worth investigating.

**Comment by sregger** [comment]
It seems we explicitly require client-side FIPS as well. Interesting point though.

**Comment by nornagon** [comment]
@sregger good luck! There are no plans to support FIPS in Electron.

**Comment by alejandroclaro** [comment]
@nornagon that is true in some cases only when the only cryptographic operations are part of client and server communication, but if you are performing any other cryptographic operation besides the client and server communication, then the cryptographic module must be FIPS validated. 

For example, if you are signing a file, then the cryptographic module MUST be FIPS validated.

**Comment by alija-qsd** [comment]
> > @alejandroclaro did this issue ever make any headway?
> 
> Hi @sregger. Not advances here. We decided to use a FIPS 140-3 validated commercial third-party library for cryptographic operations and create a native Nodejs module to wrap the operations that we need.\
> 
> It's terrible the state of the NodeJS and Electron ecosystems. Full of bad decisions that make any development very complicated.

What third-party library you used?

**Comment by alejandroclaro** [comment]
> > > @alejandroclaro did this issue ever make any headway?
> > 
> > 
> > Hi @sregger. Not advances here. We decided to use a FIPS 140-3 validated commercial third-party library for cryptographic operations and create a native Nodejs module to wrap the operations that we need.\
> > It's terrible the state of the NodeJS and Electron ecosystems. Full of bad decisions that make any development very complicated.
> 
> What third-party library you used?

We ended up implementing a native module making wrappers for the functionalities we need from OpenSSL 3.

There is a difficulty with duplicate symbols and how to isolate the problem, but it is possible to solve it by creating a native library that works as a firewall for the problem.

Not very happy with the solution, but given the conditions of the NodeJs and Electron runtime it was our only option.

This should probably be solved with NodeJs 18 depending on OpenSSL 3 if it doesn't break anything in the pluggable module in the new architecture of OpenSSL 3, but it seems that is not the case with Electron.
