### ISSUE TITLE
Paint event is not triggered

### ISSUE THREAD

**Issue by EspaguetiMagic** [electron/electron#22357]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.1
* **Operating System:**
  * Windows 10 (1803)
* **Last Known Working Electron version:**
  * -

### Expected Behavior
While navigation on a loaded web page, I expect the 'paint' to be triggered (to see the console log message 'paint event').

### Actual Behavior
The event is never triggered.

### To Reproduce
const { app, BrowserWindow } = require('electron');

app.disableHardwareAcceleration();

app.whenReady().then(() => {
  let win = new BrowserWindow({
    width: 1920,
    height: 1080,
    enableLargerThanScreen: true,
    resizable: false,
    skipTaskbar: true,
    webPreferences: {
      offscreen: true,
    }
  });

  win.loadURL('http://github.com');

  win.webContents.on('paint', (event, dirty, image) => {
    console.log("paint event");
  });

  win.webContents.frameRate = 30;
});

**Comment by flotwig** [comment]
I'm also running in to this issue with Electron 8.0.0 and above on Debian 10 and Ubuntu 19.10, the 'paint' event no longer fires, even with `webPreferences.offscreen = false`.

**Comment by flotwig** [comment]
I'm also running in to this issue with Electron 8.0.0 and above on Debian 10 and Ubuntu 19.10, the `paint` event no longer fires, even with `webPreferences.offscreen = false`. Works fine with 7.1.13.

**Comment by flotwig** [comment]
To avoid this, we're going to switch to recording video using the Chrome DevTools Protocol instead. You can send a `Page.startScreencast` command and listen for `Page.screencastFrame` messages via https://www.electronjs.org/docs/all#class-debugger, which is pretty similar in functionality to this `paint` event.

https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-startScreencast

**Comment by Ajeey** [comment]
@sofianguy 404 on https://www.electronjs.org/docs/all#class-debugger
