### ISSUE TITLE
Electron Hangs frequently when web page using ajax request

### ISSUE THREAD

**Issue by junchu25** [electron/electron#22360]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.9
* **Operating System:**
  * Windows 10 (1909)
* **Last Known Working Electron version:**
  * none

### Expected Behavior

Page load correctly, app not hang.

### Actual Behavior
Click the menu quickly, app hang. 

### To Reproduce
It's a little bit complicated.

### Screenshots
![windbg](https://raw.githubusercontent.com/junchu25/error-report/master/electron/dmp/2020-2-24/screenshoot.png)

### Additional Information
I am using Vue.js in our web page and use BrowserWindow load it. 
I am captured Electron running process dump file and use WinDbg analyzed. I found many threads wait signal, like dead lock? 
Here is dump file: https://github.com/junchu25/error-report/tree/master/electron/dmp/2020-2-24

**Comment by codingforme** [comment]
@junchu25 Are you find out what's problem with this now ?  I face the same question like you. 
After not using the application for a long time, the entire rendering process hangs after the page is requested.

**Comment by nornagon** [comment]
Electron 7 is no longer supported, please open a new issue if you are still facing this problem on the current stable version of Electron (v10).
