### ISSUE TITLE
Ignore spelling in electron 8

### ISSUE THREAD

**Issue by nautatva** [electron/electron#22362]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

With the release of electron 8, I was implementing the newly released `spell check` API's on my electron app. I was able to implement `learn spelling` using [ses.addWordToSpellCheckerDictionary](https://www.electronjs.org/docs/all#sesaddwordtospellcheckerdictionaryword) API given in docs, however I am stuck trying to implement the `ignore spelling` part.

The context menu i am trying to implement looks like this:
[![Conext menu for electron app][1]][1]

### Proposed Solution

I would like a API call which can be called for `ignoring the given misspelled word`.

### Alternatives Considered

I can implement it such a way that the dictionary suggestions are not shown for a specific set of words stored in array, but that will still leave a red squiggly line below the word. Besides, there has to be a native API call implemented given spell check has been officially announced.

### Additional Information

The difference between `Ignore spelling` and `Learn Spelling` according to google is:

**Ignore spelling**
> The word is ignored if it occurs again in the document (it will be highlighted in other documents)

**Learn Spelling** 
> The word won't be flagged as misspelled in any document.

  [1]: https://i.stack.imgur.com/9FWkQ.png

**Comment by MarshallOfSound** [comment]
The concept of "ignore" is macOS only and doesn't work in Chromium, that context menu is from some other application.  Unfortunately it's not a thing we can implement
