### ISSUE TITLE
webContents.print not working with deviceName provided

### ISSUE THREAD

**Issue by xuehaoze** [electron/electron#22365]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version: 4.x, 5.x and 6.x. More specific, reproduced in 4.2.12, 5.0.13 and 6.1.8
  * 
* **Operating System: Windows 10 (1809)
  * 
* **Last Known Working Electron version: 3.1.13, 7.x and 8.x. 
  *  
### Expected Behavior

// isSucceed should be either true or false
printingWin.webContents.print({ deviceName: device_name }, (isSucceed) => {
     console.log('123');     // 123 should be printed
}

### Actual Behavior

 // Nothing happens. completion handler not been called.
printingWin.webContents.print({ deviceName: device_name }, (isSucceed) => {
    console.log('123');     // 123 not been printed
}

### To Reproduce
// printingWin is initialized as:
let printingWin = new BrowserWindow({
    show: false,
    width: 500,
    height: 500,
}); 
printingWin.loadURL(`file://${__dirname}/test.html`);
printingWin.webContents.once('did-finish-load', () => {
  printingWin.webContents.print({ deviceName: device_name }, (isSucceed) => {
     // isSucceed should be either true or false
  }
});

// Whereas test.html is simply a hello world html:
`
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
   Hello!!!!
</body>
</html>

**Comment by codebytere** [comment]
Yes - this is known and unfortunately cannot be fixed on those versions. We recommend you use v7 and beyond.
