### ISSUE TITLE
Redux DevTools No Store Found after removing iFrame

### ISSUE THREAD

**Issue by gcraftyg** [electron/electron#22369]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
When using Redux DevTools via [redux-devtools-extension](https://github.com/zalmoxisus/redux-devtools-extension) the extension fails to recognize the redux store when an iframe is removed from the document. Prior to the iframe being removed, the extension functions as expected. Also, even after the iframe is removed, the application continues to function correctly, only the developer tool fails to function as expected.

* **Electron Version:**
  * v7.1.7
* **Operating System:**
  * macOS 10.15.3
* **Last Known Working Electron version:**
  * Unknown

### Expected Behavior
After an iFrame is removed from the document, Redux DevTools should continue to identify the store and remain working without interruption.

### Actual Behavior
Redux DevTools displays "No Store Found" and never reconnects to the store once iFrame is removed.

### To Reproduce
Below is a package with a simple react/redux to do app demonstrating the behavior of adding/removing an iframe from the document.

[redux-devtools-test-electron.zip](https://github.com/electron/electron/files/4247957/redux-devtools-test-electron.zip)

```sh
$ npm install
$ npm start
```

1. Using the Electron version of the app
1. Have the redux devtools tabs open
1. Add one or two items on the To Do list and acknowledge redux devtools are behaving correctly
1. Press the "Toggle iFrame" button once to see the iFrame being added to the page and acknowledge redux devtools continue to function properly
1. Press the "Toggle iFrame" button once more, after ~3 seconds, redux devtools displays an error of "No Store Found"

These same steps can be followed in the web version below, but the error will not occur. Only in the electron version will you see the "No Store Found" error.

[redux-devtools-test.zip](https://github.com/electron/electron/files/4247961/redux-devtools-test.zip)

The library does appear to still be maintained and I am posting here per the Electron website [regarding devtools extensions is not working](https://www.electronjs.org/docs/tutorial/devtools-extension#what-should-i-do-if-a-devtools-extension-is-not-working).

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
