### ISSUE TITLE
Allow monospaced fonts for tray text on macOS

### ISSUE THREAD

**Issue by karaggeorge** [electron/electron#22363]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

When setting the tray text on macOS, the text can jump around a lot if it's not using a monospaced font. In our use-case, we are showing time elapsed in a recording, and the number keeps moving slightly, but since we update the text every second, it gets pretty distracting.

### Proposed Solution

Use the `NSFont.monospacedDigitSystemFont` for the tray when desired through an API.

Could be an option like `tray.monospacedDigits = true`. Or maybe it could be more flexible. `tray.font = {size: 10, weight: 'bold', monospacedDigits: true};`, in cases where people want to control the size and weight as well.

### Alternatives Considered

Implementing a native module to control the tray text instead

**Comment by RaisinTen** [comment]
@karaggeorge @erickzhao I think this can be closed, now that https://github.com/electron/electron/pull/25059 has landed.
