### ISSUE TITLE
webRequest API stopped working with file:// urls since 7.0.0 (and up to 9.0.0-beta.3 at least)

### ISSUE THREAD

**Issue by ChALkeR** [electron/electron#22370]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.0.0
  * 7.1.13
  * 8.0.1
  * 8.0.2
  * 9.0.0-beta.2
  * 9.0.0-beta.3
* **Operating System:**
  * `Linux xps 5.5.4-arch1-1 #1 SMP PREEMPT Sat, 15 Feb 2020 00:36:29 +0000 x86_64 GNU/Linux`, Arch Linux current
* **Last Known Working Electron version:**
  * 6.1.8

### Expected Behavior
E.g. how 6.x behaves: `onBeforeRequest` callback gets fired before requests are made.

Note: `touch /tmp/1.html` to get `onCompleted`, otherwise check `onErrorOccured`.

```
Electron 6.1.8
onBeforeRequest: file:///tmp/1.html
onCompleted: file:///tmp/1.html
Load finished!
```

See code to reproduce below.

#### With `file:///tmp/1.html` (does not work):

```
Electron 7.0.0
Load finished!
```

```
Electron 7.1.13
Load finished!
```

```
Electron 8.0.2
Load finished!
```

```
Electron 9.0.0-beta.3
Load finished!
```

#### With `https://example.com/` (works):

```
Electron 9.0.0-beta.3
onBeforeRequest: https://example.com/
onCompleted: https://example.com/
Load finished!
```

```
Electron 8.0.2
onBeforeRequest: https://example.com/
onCompleted: https://example.com/
Load finished!
```

```
Electron 7.0.0
onBeforeRequest: https://example.com/
onCompleted: https://example.com/
Load finished!
```

### To Reproduce

```js
const { BrowserWindow, app } = require('electron')

app.on('ready', () => {
  const window = new BrowserWindow({})
  console.log(`Electron ${process.versions.electron}`)
  window.webContents.session.webRequest.onBeforeRequest((details, callback) => {
    console.log(`onBeforeRequest: ${details.url}`)
    callback({})
  })
  window.webContents.session.webRequest.onCompleted((details) => {
    console.log(`onCompleted: ${details.url}`)
  })
  window.webContents.session.webRequest.onErrorOccurred((details) => {
    console.log(`onErrorOccured: ${details.url}`)
  })
  window.webContents.loadURL('file:///tmp/1.html') // compare with https://example.com/
  window.webContents.on('did-finish-load', () => {
    console.log('Load finished!')
  })
  window.show()
})
```

### Additional Information
* Documented to work with `file:` urls: https://www.electronjs.org/docs/api/web-request#webrequestonbeforerequestfilter-listener
* Specifying filters manually doesn't seem to help
* https://github.com/electron/electron/issues/21308 might be related
* Looks like a regression to me.

**Comment by ChALkeR** [comment]
@sofianguy this can also be reproduced on macOS 10.15.2 Catalina (checked only Electron 7.1.12 there), with the exact same symptoms.

**Comment by pascalkania** [comment]
it is also reproducable on Windows 10 with electron 7.1.13

**Comment by ChALkeR** [comment]
The breakage happened between `v7.0.0-beta.2` and `v7.0.0-beta.3`.
```
v7.0.0              bad
v7.0.0-beta.6       bad
v7.0.0-beta.4       bad
v7.0.0-beta.3       bad
v7.0.0-beta.2       good
v7.0.0-beta.1       good
v6.1.9              good
```

**Comment by ChALkeR** [comment]
Fist bad commi on `7-0-x` branch is c7a3142babdc26c6d9cc99ea98d8d98a4b6c8e97.
