### ISSUE TITLE
Mouse select event hides is considered like a click event

### ISSUE THREAD

**Issue by DhouhaBchir** [electron/electron#22372]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  * since 5.0.13 
* **Operating System:** 
  * MacOS 10.14.6 
* **Last Known Working Electron version:** 
  * 4.1.5 

### Expected Behavior

The mouse event when selecting the text on the input doesn't close the modal. (see attached video with electron 4.1.

### Actual Behavior

The mouse event when selecting the text on the input, is considered like a click event, when the cursor passes over the dimmer (the black zone around the modal). (see attached video with electron 7.1.7).

### Screenrecords

[with Electron 4.1.5.zip](https://github.com/electron/electron/files/4249074/with.Electron.4.1.5.zip)
[with Electron 7.1.7.zip](https://github.com/electron/electron/files/4249075/with.Electron.7.1.7.zip)

Any ideas how to fix that ?
Thanks.

**Comment by MarshallOfSound** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by smildlzj** [comment]
same problem
