### ISSUE TITLE
Clipboard tests are failing on arm64 Windows 

### ISSUE THREAD

**Issue by zcbenz** [electron/electron#22371]
According to CI history, the clipboard tests started to fail since Feb 16, 2020, the only change is a version bump https://github.com/electron/electron/commit/647f086286e8c71b1dee39948dd84c163f5d0893.

The Windows CI machine has already been restarted, and I have tried to move the tests into the main process, but none works. I doubt it is caused by a Windows update.

**Comment by deepak1556** [comment]
Un-assigning myself as I was unable to repro the issue locally when testing https://github.com/electron/electron/pull/29980
