### ISSUE TITLE
Unable to get setSpellCheckerDictionaryDownloadURL to download dictionary

### ISSUE THREAD

**Issue by heronhaye** [electron/electron#22381]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.0.1
* **Operating System:**
  * Arch Linux
* **Last Known Working Electron version:**
  * N/A (new feature)

### Expected Behavior
I expect that when I use `win.webContents.session.setSpellCheckerDictionaryDownloadURL`, Electron downloads `hunspell_dictionaries.zip` and spell checks input boxes. 

### Actual Behavior
Dictionary file is not downloaded to `~/.config/Electron/Dictionaries` and no spellchecking is done. 

### To Reproduce
See demo repo at https://github.com/heronhaye/electron-8-spellchecker-test. Relevant excerpt below.

```js
function createWindow () {
  win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true,
      spellcheck: true
    }
  })

  win.webContents.session.setSpellCheckerDictionaryDownloadURL(
    'https://modalduality.keybase.pub/hunspell801.zip'
  )

  win.loadFile('index.html')

  win.webContents.openDevTools()

  win.on('closed', () => {
    win = null
  })
}
```

When I comment out the call to setSpellCheckerDictionaryDownloadURL, everything works as expected.

I verified that the sha256 hash of the zip file at the URL (`bc64c413308f6582df625833e4d9f35871ca438ba93d72afc3a1cf84779e2d50`) is the same as the hash of the file that was released in Electron 8.0.1.

```sh
$ git clone https://github.com/heronhaye/electron-8-spellchecker-test.git
$ npm install
$ npm start
```

### Additional Information
Let me know if I can help by doing other tests, thanks!

**Comment by MarshallOfSound** [comment]
So I was writing a whole thing about how to do this because your code snippet is wrong, then realized that the method doesn't work at the moment 😢 

PR is up to fix it https://github.com/electron/electron/pull/22382

Once that PR is landed the below will be correct:

You need to host the **contents** of that zip file at a given URL and provide that base URL to that API.  i.e. if the contents of the zip file are found at `https://modalduality.keybase.pub/dictionaries/mydict.bdic` then you need to use `https://modalduality.keybase.pub/dictionaries/` as the URL in this API.

**Comment by heronhaye** [comment]
Great, thank you for the quick response!

**Comment by heronhaye** [comment]
One more question: is it possible to specify a local filepath here? I tried with 8.0.2 but it doesn't seem to work. We'd ideally like to ship these resources as part of the package so the user does not need to make any network calls. Or perhaps Electron could read the files out of the standard hunspell download location (`/usr/share/hunspell/` on Linux)?

**Comment by MarshallOfSound** [comment]
No you cant provide a file path to this API is has to be an actual URL.

Also the hunspell dictionaries that some Linux distros come with are less complete and are in a different format to the ones chromiums spellchecker uses

**Comment by heronhaye** [comment]
Sorry I think I'm still doing this incorrectly. I updated the code to point to a base URL:

https://github.com/heronhaye/electron-8-spellchecker-test

```
  win.webContents.session.setSpellCheckerDictionaryDownloadURL(
    'https://modalduality.keybase.pub/dictionaries/'
  )
```

And 
```
curl -O https://modalduality.keybase.pub/dictionaries/en-US-8-0.bdic 
```
for example, works as expected. But I still can't get Electron 8.0.2 to download the files.
