### ISSUE TITLE
Differences in Electron vs getUserMedia docs

### ISSUE THREAD

**Issue by EmptyCrown** [electron/electron#22380]
### Issue Details

* **Electron Version:**
  8.0.0
* **Operating System:**
  Windows 10
* **Last Known Working Electron version:**
  * 

### Expected Behavior

I would expect the `getUserMedia` docs (https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) could just be ported over to the Electron desktopCapturer template defined here (https://www.electronjs.org/docs/api/desktop-capturer).

### Actual Behavior

However, it seems like Electron uses a modified version of `getUserMedia` that includes a `mandatory` field with things like `minWidth`, `maxWidth`, etc that aren't in the official `getUserMedia` docs. How do I use all the other parameters in the `MediaTrackConstraints` object in the context of Electron's desktopCapturer?

For instance, I'd like to specify `cursor: 'never'` to hide the mouse in the recording, but I seem to ffigure out how to do that with desktopCapturer. Thanks!

**Comment by MarshallOfSound** [comment]
> I would expect the getUserMedia docs (https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) could just be ported over to the Electron desktopCapturer template defined here

`desktopCapturer` is a completely different API from `getUserMedia` with different parameters and options.  Both should work, just choose which one best fits your use case.  They are not intended to be API interopable however.

**Comment by tasercake** [comment]
@MarshallOfSound where might one find an API reference for the `getUserMedia` function as displayed in the `desktopCapturer` docs? The Mozilla Web API docs make no mention of properties `mandatory`, `chromeMediaSource`, etc. that appear in the `desktopCapturer` docs.

**Comment by MartinListwan** [comment]
@tasercake's question is still not answered. @MarshallOfSound do you know?

**Comment by deepanshushukla** [comment]
Documentation of getUserMedia for electron  is missing from the web @MarshallOfSound any answer for this.
