### ISSUE TITLE
HTML canvas rendering performance is worse on faster iMac

### ISSUE THREAD

**Issue by wfischer42** [electron/electron#22398]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.0, 8.0.1, 8.0.2
* **Operating System:**
  * macOS 10.15.3
* **Last Known Working Electron version:**
  * 7.1.13

I'm using the Cytoscape.js graph library to render a smooth interactive graph in an HTML canvas. I have 2 computers: an iMac (Retina 5K, 27-inch, 2019): 3 GHz 6-Core Intel Core i5, 24GB Ram, Radeon Pro 570X 4 GB graphics card; and a Macbook Pro (13-inch, 2017), 2.4 GHz Dual-Core Intel i5, 8GB Ram. 

### Expected Behavior
Cytoscape will smoothly render graph interactions in the Electron application.

### Actual Behavior
The graph loads quickly and renders smoothly on the slower Macbook Pro, but takes 7 seconds to load and has choppy rendering on the faster iMac. It seems the rest of the user interface on the iMac is also choppy and unresponsive, but only when the cytoscape graph is being rendered. When I remove the graph, it works fine. 

The graph rendering works fine in chrome v80+ on both machines, so it probably isn't chromium, and it works if I downgrade to Electron v7, so the bug seems to have been introduced in Electron v8.0.0. I'm not certain it's related to HTML canvas interactions, but it seems likely. I only use canvas via Cytoscape.js, so it would take a long time for me to test it without Cytoscape.js. 

### Steps to Reproduce
It'll take a while to set up steps to reproduce, but I'll work on it and update the issue when I have something.

**Comment by codebytere** [comment]
Closing as there's been no more information provided for us to go on.
