### ISSUE TITLE
Frameless minimum sized window is not restored to previous size after minimize and restore

### ISSUE THREAD

**Issue by christian-judt** [electron/electron#22393]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.10 - 9.0.0-beta.3 (and presumably later versions until this bug is fixed)
* **Operating System:**
  * Windows 10 pro (1909)
* **Last Known Working Electron version:**
  * 7.1.9

### Preconditions

* Window is frameless
* Window has minimum size
* Window size is minimum size

### Expected behavior

* Window is minimized
* Window is restored
* Window has the same size as before the minimization

### Actual behavior

* Window is minimized
* Window is restored
* Window is slightly higher and wider than before the minimization

### To Reproduce

```
git clone -b frameless-minsize-minimize-restore-bug https://github.com/christian-judt/electron-quick-start.git
cd electron-quick-start
npm install
npm start
```

### Additional Information

* A similar problem with "maximize-unmaximize" instead of "minimize-restore" has appeared in Electron Version 7.1.2. (see #22440)

### Maybe related issues

* Windows: Restore (after minimize) to wrong window size #7951
* Frameless minimum sized window is not restored to previous size after maximize and unmaximize #13533
* maximize, minimize, restore incorrect size #15702
* Electron 6 - restore after minimize has wrong window size #19816

**Comment by tallev266** [comment]
Glad to see this issue is reported.
Any plans on fixing this for version 8?
If not, are there any workarounds we can implement other than saving the bounds on minimize and resetting them on restore?

**Comment by orangeChu** [comment]
> Glad to see this issue is reported.
> Any plans on fixing this for version 8?
> If not, are there any workarounds we can implement other than saving the bounds on minimize and resetting them on restore?

Maybe possible to temporarily solve this problem by resetting the size of the window when the window's `restore` event is activated.

**Comment by pejman1** [comment]
Does anybody know, how long does it take to fix ?
