### ISSUE TITLE
[showSaveDialog] Mismatch between source, documentation and type definitions

### ISSUE THREAD

**Issue by lekoaf** [electron/electron#22396]
I've found a mismatch between the source documentation, the website and the type definitions.

According to source documentation, `dialog.showSaveDialogSync` and `dialog.showSaveDialog` takes an options object. That object can have `properties` which is an array of strings.
https://github.com/electron/electron/blob/master/docs/api/dialog.md#dialogshowopendialogsyncbrowserwindow-options

But when you go to the website, it can only be a string. Not an array of strings.
https://www.electronjs.org/docs/api/dialog#dialogshowsavedialogsyncbrowserwindow-options

And in `electron.d.ts`, the `properties` property doesn't even exist at all, so I can't use them with typescript.

```typescript
interface SaveDialogOptions {
    title?: string;
    defaultPath?: string;
    buttonLabel?: string;
    filters?: FileFilter[];
    message?: string;
    nameFieldLabel?: string;
    showsTagField?: boolean;
    securityScopedBookmarks?: boolean;
  }

interface SaveDialogSyncOptions {
    title?: string;
    defaultPath?: string;
    buttonLabel?: string;
    filters?: FileFilter[];
    message?: string;
    nameFieldLabel?: string;
    showsTagField?: boolean;
    securityScopedBookmarks?: boolean;
  }
```
Removed type comments for brevity.

Electron version 7.1.7.

Sadly it's too convoluted to find how to update the stuff, otherwise I'd send in a PR instead.

**Comment by codebytere** [comment]
@lekoaf thanks for surfacing this, but this isn't actually a bug. The new properties were added in v8.0.0, in this commit: [28466a39d81e8adbade67ff150b7037be4993db2](https://github.com/electron/electron/commit/28466a39d81e8adbade67ff150b7037be4993db2). The source files always reflect the latest master, and the website reflects the latest stable version, which is why you're seeing the perceived mismatch.

**Comment by lekoaf** [comment]
That's strange. When I was on the Github page, I even switched branches between 7.x and 8.x and it was still there as a string array. Oh well. Thanks.
