### ISSUE TITLE
desktop capture does not work on version 8.0.1 !!!

### ISSUE THREAD

**Issue by sr9999999** [electron/electron#22391]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.1
* **Operating System:**
  * macOS 10.14, windows 10
* **Last Known Working Electron version:**
  * 5.0.10

### Actual Behavior

 desktopCapturer.getSources(
        { types: ["window", "screen"] },
        (error, sources) => {
          console.log('<<<<<<<<<<<<<')
          if (error) {
            ipcRenderer.send("getScreen-error");
            console.log(error);
          } else {
            for (const item of sources) {
              item.thumbnail = item.thumbnail.toDataURL();
            }
            console.log('>>>>>>>>>>>>>>>>>>..')
            ipcRenderer.send("getScreen-success", sources);
          }
        }
      );

The code above works good on version 5.0.10. However once I upgrade to 8.0.1, the callback function was not called and no error exposed
### Screenshots

![image](https://user-images.githubusercontent.com/61491566/75320631-13e9de80-58aa-11ea-8a34-0ac6e14db856.png)
![image](https://user-images.githubusercontent.com/61491566/75320678-2fed8000-58aa-11ea-980e-fe34ff27b9ad.png)
![image](https://user-images.githubusercontent.com/61491566/75320735-4d224e80-58aa-11ea-9952-9e5d93a5e904.png)

**Comment by sebakerckhof** [comment]
This now returns a promise: https://www.electronjs.org/docs/api/modernization/promisification

**Comment by MarshallOfSound** [comment]
Closing as per @sebakerckhof 's comment above, this method now returns a promise and it went through a deprecation cycle.  We strongly recommend you keep up to date with Electron versions and only jump one version at a time in order to minimize changes and catch these deprecations while the warnings are still present
