### ISSUE TITLE
app crashed when rename itself while running

### ISSUE THREAD

**Issue by malin1988** [electron/electron#22392]
### Preflight Checklist

* [ yes] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [yes ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ yes] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  6.0.0
* **Operating System:**
  macOS 10.14.5

### Expected Behavior
 the app will not crash

### Actual Behavior
  I rename the application as code bellow, and then the app crashed.
 ```
    const defaultInstallDir = path.join(os.homedir(), '../../', 'Applications')
    fs.renameSync(`${defaultInstallDir}/${oldName}.app`, `${defaultInstallDir}/${newName}.app`)
 ```
### To Reproduce
 ```
    const defaultInstallDir = path.join(os.homedir(), '../../', 'Applications')
    fs.renameSync(`${defaultInstallDir}/${oldName}.app`, `${defaultInstallDir}/${newName}.app`)
 ```

### Additional Information
Is there any way can I rename my  Electron app by code?

**Comment by MarshallOfSound** [comment]
> Is there any way can I rename my Electron app by code?

Not while it's running, it's incredibly unsafe.  You're better off copying the application to the new name, launching it, quitting the current app and then deleting the old app from the new named one.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
