### ISSUE TITLE
Modals are not rendered correctly in Electron 9.x

### ISSUE THREAD

**Issue by Arjan-Zuidema** [electron/electron#22394]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.0-beta.3
* **Operating System:**
  * macOS 10.15.3
* **Last Known Working Electron version:**
  * 8.x

### Expected Behavior

Modals should not have rounded corners like in the screenshot below and look like they are attached to the parent window

<img width="912" alt="Schermafbeelding 2020-02-26 om 12 05 14" src="https://user-images.githubusercontent.com/30040390/75340076-0d4f6d00-5892-11ea-8c39-ffe538dc435f.png">

### Actual Behavior

Modals look weird and are not attached to the parent

<img width="912" alt="Schermafbeelding 2020-02-26 om 12 04 18" src="https://user-images.githubusercontent.com/30040390/75340010-ebee8100-5891-11ea-85d3-e1b5dad308d2.png">

### To Reproduce

My Example code below:

```js
const modal = new BrowserWindow({
	width: 450,
	height: 250,
	useContentSize: true,
	vibrancy: process.platform === "darwin" ? "popover" : undefined,
	resizable: false,
	parent: parentWindow,
	skipTaskbar: false,
	modal: (!parentWindow) ? false : true,
	show: false,
	acceptFirstMouse: true,
	titleBarStyle: 'hidden',
	minimizable: false,
	maximizable: false,
	webPreferences: {
		nodeIntegration: true,
		enableRemoteModule: true
	}
});
```

### Screenshots
See above

### Additional Information
`dialog.showMessageBox` works as expected.

**Comment by codebytere** [comment]
@Arjan-Zuidema it appears this is specific to the `popover` vibrancy type - you'll notice the issue goes away if it's removed. I'll try to look into this soon.

**Comment by codebytere** [comment]
Confirmed, this is a macOS SDK change out of our control.
