### ISSUE TITLE
electron version:8.0.1, can't resolve 'fs' in'node_modules/electron'

### ISSUE THREAD

**Issue by LycheeHe** [electron/electron#22390]
### Issue Details
I type: ng serve in command line, and show this finally
![image](https://user-images.githubusercontent.com/30425557/75309363-d0807780-588b-11ea-8a2d-575961ab00b7.png)
and this is my browser's information when I load: [localhost:4200](url)
![image](https://user-images.githubusercontent.com/30425557/75309679-a7141b80-588c-11ea-948e-5f4f7dc93f75.png)

and here is my browser's information when I load: [http://localhost:8100/webpack-dev-server/](url) after I run the project by 'ionic serve' command
![image](https://user-images.githubusercontent.com/30425557/75309464-163d4000-588c-11ea-8956-d3f55e199631.png)

* **Electron Version:**

  * 
* **Operating System:**
  * 
* **Last Known Working Electron version:**
  * 

### Additional Information

and more information show here
![image](https://user-images.githubusercontent.com/30425557/75309867-31f51600-588d-11ea-8e07-7c5ec9d36758.png)
tsconfig.json
![image](https://user-images.githubusercontent.com/30425557/75309889-46d1a980-588d-11ea-9c14-89e8ec6914d2.png)
package.json
![image](https://user-images.githubusercontent.com/30425557/75309913-62d54b00-588d-11ea-9509-6b71b8524dfa.png)
![image](https://user-images.githubusercontent.com/30425557/75309932-6f59a380-588d-11ea-99d5-f4b0b7866196.png)

**Comment by LycheeHe** [comment]
I this it is the problem that electron can not resolve 'fs' module after the version upgrade. what do u think?

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
