### ISSUE TITLE
Print crash in Electron 8.0.2, Mac OS Catalina 10.15.3

### ISSUE THREAD

**Issue by thomasdao** [electron/electron#22409]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
App crashes when call `webContents.print()`
* **Electron Version:**
8.0.2
* **Operating System:**
Mac OS Catalina 10.15.3 (19D76)
* **Last Known Working Electron version:**
Electron 6 did not crash when print but has other bugs with printing

### Expected Behavior

App should not crash
### Actual Behavior

App crashes
### To Reproduce

Can be reproduced with this Fiddle
https://gist.github.com/1aced5931b191c07adb6a111f937a4e1

**Comment by codebytere** [comment]
Do you have a crash dump @thomasdao? I ran this fiddle and experienced no issues.

**Comment by thomasdao** [comment]
@codebytere please check this crash dump, thanks https://drive.google.com/file/d/1pJn0XTqiQoIzR69thIA3DIgWwrY5H7qz/view?usp=sharing

**Comment by thomasdao** [comment]
By the way the app crashes immediately when I clicked "Print" button, and it did not show any print dialog. My Mac doesn't have any printer connected. However in Electron 6, I can see the print dialog. Please let me know if you need any other info, thanks!

**Comment by codebytere** [comment]
@thomasdao ah, this was the crucial piece:
> My Mac doesn't have any printer connected.

I nuked local printers from my mac and could repro. Looks like this edge case is specific only to when no local printers are connected to your mac, which is annoying, but also makes triage a little easier 😛 I'll get on this but in the meantime if you connect literally any printer to your mac (doesn't matter if it's connected to your current network or not) this should stop happening.
