### ISSUE TITLE
Failed to use WebDriverJs and Electron-Chromedriver  to start Electron in Windows10

### ISSUE THREAD

**Issue by yujingmu** [electron/electron#22408]
### Issue Details

* **Electron Version:**
  *  v8.0.2
* **Operating System:**
  *  Windows 10 (1909)
* **Last Known Working Electron version:**
  * None

### Expected Behavior
 should start the Electron

### Actual Behavior
(node:26644) UnhandledPromiseRejectionWarning: SessionNotCreatedError: session not created: No matching capabilities found

### To Reproduce
https://www.electronjs.org/docs/tutorial/using-selenium-and-webdriver

  follow the instruction of Install Electron-chromedriver and WebdriverJS

### Screenshots
![image](https://user-images.githubusercontent.com/41482825/75408186-fcfdc780-594f-11ea-86ba-0c698f49e701.png)

![image](https://user-images.githubusercontent.com/41482825/75408057-a3959880-594f-11ea-9d6b-8f03bd34a3b3.png)

### Additional Information
sample code:
```
const webdriver = require('selenium-webdriver')

const driver = new webdriver.Builder()
  // The "9515" is the port opened by chrome driver.
  .usingServer('http://localhost:9515')
  .withCapabilities({
    chromeOptions: {
      // Here is the path to your Electron binary.
      binary: '\\Users\\qf\\tmp\\node_modules\\electron\\dist\\electron.exe'
    }
  })
  .forBrowser('electron')
  .build()

driver.get('http://www.google.com')
driver.findElement(webdriver.By.name('q')).sendKeys('webdriver')
driver.findElement(webdriver.By.name('btnG')).click()
driver.wait(() => {
  return driver.getTitle().then((title) => {
    return title === 'webdriver - Google Search'
  })
}, 1000)

driver.quit()
```

````
C:\Users\qf\tmp>node a.js
(node:26644) UnhandledPromiseRejectionWarning: SessionNotCreatedError: session not created: No matching capabilities found
    at Object.throwDecodedError (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\error.js:550:15)
    at parseHttpResponse (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\http.js:563:13)
    at Executor.execute (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\http.js:489:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:26644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:26644) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:26644) UnhandledPromiseRejectionWarning: SessionNotCreatedError: session not created: No matching capabilities found
    at Object.throwDecodedError (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\error.js:550:15)
    at parseHttpResponse (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\http.js:563:13)
    at Executor.execute (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\http.js:489:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:26644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:26644) UnhandledPromiseRejectionWarning: SessionNotCreatedError: session not created: No matching capabilities found
    at Object.throwDecodedError (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\error.js:550:15)
    at parseHttpResponse (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\http.js:563:13)
    at Executor.execute (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\http.js:489:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:26644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:26644) UnhandledPromiseRejectionWarning: SessionNotCreatedError: session not created: No matching capabilities found
    at Object.throwDecodedError (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\error.js:550:15)
    at parseHttpResponse (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\http.js:563:13)
    at Executor.execute (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\http.js:489:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:26644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:26644) UnhandledPromiseRejectionWarning: SessionNotCreatedError: session not created: No matching capabilities found
    at Object.throwDecodedError (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\error.js:550:15)
    at parseHttpResponse (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\http.js:563:13)
    at Executor.execute (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\http.js:489:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:26644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:26644) UnhandledPromiseRejectionWarning: SessionNotCreatedError: session not created: No matching capabilities found
    at Object.throwDecodedError (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\error.js:550:15)
    at parseHttpResponse (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\http.js:563:13)
    at Executor.execute (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\http.js:489:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:26644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
```

**Comment by qifeiLiu** [comment]
The same issue I also encountered.

**Comment by chenbosns** [comment]
The same issue I also encountered!!

**Comment by Daniel-McCarthy** [comment]
Have any of you managed to find a solution or a workaround to this?
I am experiencing this issue, and see that this issue has been occurring for a while. Thanks for your time.

**Comment by fahadsaleemfd** [comment]
i have also same issue

**Comment by 95borgfu** [comment]
Anyone found some solutions? I met this issue too in my MAC.

**Comment by vcgupta** [comment]
I am also facing same issue on MAC, any solution please?

**Comment by Rdavid1991** [comment]
selenium-webdriver 4.0.0-alpha is incompatible, you use the version  3.6.0

**Comment by Rdavid1991** [comment]
> ### Issue Details
> * **Electron Version:**
>   
>   * v8.0.2
> * **Operating System:**
>   
>   * Windows 10 (1909)
> * **Last Known Working Electron version:**
>   
>   * None
> 
> ### Expected Behavior
> should start the Electron
> 
> ### Actual Behavior
> (node:26644) UnhandledPromiseRejectionWarning: SessionNotCreatedError: session not created: No matching capabilities found
> 
> ### To Reproduce
> https://www.electronjs.org/docs/tutorial/using-selenium-and-webdriver
> 
> follow the instruction of Install Electron-chromedriver and WebdriverJS
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/41482825/75408186-fcfdc780-594f-11ea-86ba-0c698f49e701.png)
> 
> ![image](https://user-images.githubusercontent.com/41482825/75408057-a3959880-594f-11ea-9d6b-8f03bd34a3b3.png)
> 
> ### Additional Information
> sample code:
> 
> ```
> const webdriver = require('selenium-webdriver')
> 
> const driver = new webdriver.Builder()
>   // The "9515" is the port opened by chrome driver.
>   .usingServer('http://localhost:9515')
>   .withCapabilities({
>     chromeOptions: {
>       // Here is the path to your Electron binary.
>       binary: '\\Users\\qf\\tmp\\node_modules\\electron\\dist\\electron.exe'
>     }
>   })
>   .forBrowser('electron')
>   .build()
> 
> driver.get('http://www.google.com')
> driver.findElement(webdriver.By.name('q')).sendKeys('webdriver')
> driver.findElement(webdriver.By.name('btnG')).click()
> driver.wait(() => {
>   return driver.getTitle().then((title) => {
>     return title === 'webdriver - Google Search'
>   })
> }, 1000)
> 
> driver.quit()
> ```
> 
> ```
> C:\Users\qf\tmp>node a.js
> (node:26644) UnhandledPromiseRejectionWarning: SessionNotCreatedError: session not created: No matching capabilities found
>     at Object.throwDecodedError (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\error.js:550:15)
>     at parseHttpResponse (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\http.js:563:13)
>     at Executor.execute (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\http.js:489:26)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> (node:26644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:26644) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> (node:26644) UnhandledPromiseRejectionWarning: SessionNotCreatedError: session not created: No matching capabilities found
>     at Object.throwDecodedError (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\error.js:550:15)
>     at parseHttpResponse (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\http.js:563:13)
>     at Executor.execute (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\http.js:489:26)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> (node:26644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> (node:26644) UnhandledPromiseRejectionWarning: SessionNotCreatedError: session not created: No matching capabilities found
>     at Object.throwDecodedError (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\error.js:550:15)
>     at parseHttpResponse (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\http.js:563:13)
>     at Executor.execute (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\http.js:489:26)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> (node:26644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
> (node:26644) UnhandledPromiseRejectionWarning: SessionNotCreatedError: session not created: No matching capabilities found
>     at Object.throwDecodedError (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\error.js:550:15)
>     at parseHttpResponse (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\http.js:563:13)
>     at Executor.execute (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\http.js:489:26)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> (node:26644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
> (node:26644) UnhandledPromiseRejectionWarning: SessionNotCreatedError: session not created: No matching capabilities found
>     at Object.throwDecodedError (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\error.js:550:15)
>     at parseHttpResponse (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\http.js:563:13)
>     at Executor.execute (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\http.js:489:26)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> (node:26644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
> (node:26644) UnhandledPromiseRejectionWarning: SessionNotCreatedError: session not created: No matching capabilities found
>     at Object.throwDecodedError (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\error.js:550:15)
>     at parseHttpResponse (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\http.js:563:13)
>     at Executor.execute (C:\Users\qf\tmp\node_modules\selenium-webdriver\lib\http.js:489:26)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> (node:26644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
> ```
> ```

selenium-webdriver 4.0.0-alpha is incompatible, you use the version 3.6.0

**Comment by Rdavid1991** [comment]
selenium-webdriver 4.0.0-alpha is incompatible, you use the version 3.6.0

**Comment by coco-1998-2** [comment]
same issue I encountered.

**Comment by coco-1998-2** [comment]
> selenium-webdriver 4.0.0-alpha is incompatible, you use the version 3.6.0

this solution worked for me.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
