### ISSUE TITLE
Media Keys Not Working on MacOS (again)

### ISSUE THREAD

**Issue by csetera** [electron/electron#22405]
* [X ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
╰─➤  node_modules/.bin/electron --version
v8.0.2

* **Operating System:**
MacOS 10.15.3

* **Last Known Working Electron version:**
Electron 5.0.13

### Expected Behavior
Media keys registered via globalShortcut should function

### Actual Behavior
Media keys do not appear to be registered properly.  iTunes opens on play/pause.  This is true with my application as well as with the original test application from https://github.com/electron/electron/issues/20788

### To Reproduce
The original test application at https://github.com/electron/electron/issues/20788 with a change to 8.0.2 does not function properly.

**Comment by csetera** [comment]
Doing a bit more testing, it appears that 7.1.13 with the backported fixes works (for me), but nothing in the 8.x series appears to work.  This is all being done with the original test application and pegging the electron version.

**Comment by MarshallOfSound** [comment]
I tested the original repro on `8.2.0` and it appears to work fine, I believe you tested this before the secondary fix had landed in the `8-x-y` branch.  Please note that you do need to grant accessibility permissions to receive these key events.

If you are actually playing music and don't want to ask for accessibility permissions you can use the `MPRemoteCommandCenter` APIs through this module instead --> https://github.com/MarshallOfSound/electron-media-service

**Comment by salomvary** [comment]
@MarshallOfSound The fix does not seem to be working for me, tried `8.2.0` and `8.2.1`. Even though `isTrustedAccessibilityClient` returns true, only iTunes is started and no events are sent to Electron. I am on macOS 10.14.6.

If I go back to `electron@5` everything works a expected.

**Comment by csetera** [comment]
FWIW... I updated to latest 8.3.x yesterday and things now seem to work correctly.  I see that this issue is already closed, but for those that were seeing the same issues, you may want to try the latest 8.x release.
