### ISSUE TITLE
Reload crash after version change from 7.1.13 to 8.0.0 and back to 7.1.13 

### ISSUE THREAD

**Issue by wfischer42** [electron/electron#22406]
For anyone else experiencing this problem, you can recover by deleting the app's folder in ApplicationSupport (on Mac) and re-running.

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

Electron Version:
7.1.13 & 8.0.0
Operating System:
macOS 10.15.3
Last Known Working Electron version:
7.1.13
* **Electron Version:**
  * 7.1.13 after downgrade
* **Operating System:**
  * 
* **Last Known Working Electron version:**
  * 7.1.13 before upgrade, then downgrade

### Expected Behavior
The app will work after downgrading to 7.1.13 as it did before upgrading from 7.1.13

### Actual Behavior
After an upgrade from 7.1.13 to ^8.0.0 and subsequent downgrade back to 7.1.13, the app goes blank after a page reload. Reload works as expected before the upgrade. 

### To Reproduce
Upgrade to Electron version 8.0.2 (latest attempted)
Serve the app and close (refresh should work)
Downgrade to Electron version 7.1.13

It also seems to be an issue when downgrading further.

**Comment by GhostlyDark** [comment]
Encountered this on Windows 10 as well.
Clearing the folder **Code Cache** solves this.

**Comment by codebytere** [comment]
This kind of idempotence is not a guarantee we provide nor have historically provided; it's expected that you clear the user cache between installations of versions.
