### ISSUE TITLE
something about install bug at electron@8*

### ISSUE THREAD

**Issue by chunmingdeng** [electron/electron#22437]
when I run npm install 
![image](https://user-images.githubusercontent.com/23050110/75506605-7ca39900-5a19-11ea-9d99-8ae9d9c11fc8.png)
by I found help in internet, we found path in this picture not found; when I try it, i found 'v8.0.2' is not a file, 'v' is superfluous,  please help me check it, thank you!

**Comment by malept** [comment]
Where are you finding documentation that says to use the `npm.taobao.org` domain for a mirror?

**Comment by chunmingdeng** [comment]
sorry，I in China，so I can't get GitHub resource in good network speed, we need to visit
a mirror registry, the `npm.taobao.org` is a mirror registry.
if I change the electron_mirror to origin, can I fixed this problems?

**Comment by malept** [comment]
The [installation instructions](https://www.electronjs.org/docs/tutorial/installation#mirror) has the correct URL to use as the mirror for China.

**Comment by AtarisMio** [comment]
@malept 
the mirror URL of this doc `ELECTRON_MIRROR="https://cdn.npm.taobao.org/dist/electron/"` cannot use for me.

```
(node:28463) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found) for https://npm.taobao.org/mirrors/electron/v8.0.2/electron-v8.0.2-darwin-x64.zip
```

the correct URL is `https://npm.taobao.org/mirrors/electron/8.0.2/electron-v8.0.2-darwin-x64.zip`

**Comment by malept** [comment]
It seems that the CDN lags behind in terms of Electron versions, you should file a bug with them.
