### ISSUE TITLE
Slow startup for multiple instances and localStorage is not synchronized

### ISSUE THREAD

**Issue by MJomaa** [electron/electron#22438]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.0
* **Operating System:**
  * Windows 10

### Expected Behavior
Fast startup for multiple application instances and `localStorage` is synchronized.

### Actual Behavior
Slow startup for multiple application instances and `localStorage` is not synchronized.

### To Reproduce
Save something into `localStorage` that will be retrieved on application startup.
Now open a second instance of the application.

### Additional Information
⚠️ The issue can be closed. This is just an information for everyone stumbling across the same problem. Hopefully it will appear in search engines.

The problem is that the application locks the config files associated with `localStorage`. When an additional instance starts it will eventually timeout requesting the same lock. The timeout will slow down the application startup by quite a bit.

A workaround is not to use `localStorage`.  For my application I'm using https://github.com/nathanbuchar/electron-settings. This library works great and as far as I can tell there are no locks on the config files. To synchronize settings use a file watcher (also in that library) that notifies file changes.

**Comment by Raynos** [comment]
I also ran into this issue today.

I tried many things to figure out why my startup was slow and eventually noticed that apps using `localStorage` were slow to startup & apps not using `localStorage` were fast to startup

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!

**Comment by sunjinbo321** [comment]
async function createWindow() {
  const config = {
   ...
    webPreferences: {
  ...
    }
  }
const gotTheLock = app.requestSingleInstanceLock()
 if (!gotTheLock) {
    config.webPreferences['partition'] = `persist_${process.pid}`
 }

We can set the partition attribute to isolate sessions, which can solve the problem of slow startup and ensure that the first Electron instance can access the LocalStorage cache, but the second instance or more still cannot be resolved

**Comment by Skywalker13** [comment]
> config.webPreferences['partition'] = `persist_${process.pid}` }

That's strange but this hack breaks Electron custom protocols and generates CORS errors.
