### ISSUE TITLE
How can i access to file data that copy from finder in clipboard?

### ISSUE THREAD

**Issue by teamrun** [electron/electron#2244]
i want to get image file from clipboard.

when right-click an image on a web page and copy it, i can get the image file from both browser's `onpaste` event and `clipboard` module that electron provided. 

when it came to **files(images) in finder**, `cmd+c` copy it, browser's `onpaste` event can only give you a preview icon of this file.

like this: 
![image](https://cloud.githubusercontent.com/assets/2055081/8722431/48302d14-2bf7-11e5-9ec2-e465279aa6db.png)

i hope electron can give me more power to access clipboard data. but after i look through the api doc of clipboard and native-image, tryed in devtool of electron, the result still the same, i can only get the preview icon of the image.

![image](https://cloud.githubusercontent.com/assets/2055081/8722485/b69c1c18-2bf7-11e5-85f3-e61a59cf4c46.png)

how can i access to image data copyed from finder, not from web page?

here is some code, paste those code to devtool of electron, copy an image file in finder, back to devtool, press enter.

```
var clipboard = require('clipboard');
var img = clipboard.readImage('png');
document.body.innerHTML += '<img src="' +img.toDataUrl()+ '">';
```

**Comment by teamrun** [comment]
Can not change application's icon via copy-paste after cmd-i. i guess it's the same reason.

[How can I change an application icon in Mac OS X](http://superuser.com/questions/37811/how-can-i-change-an-application-icon-in-mac-os-x)

**Comment by CxRes** [comment]
To further the above request, It would be really cool if electron could handle file pointers natively.

For example if I cut/copy a file in explorer or finder and then use the paste method to tell me which file was on the clipboard. 

Similarily, if I have loaded the metadata of a bunch of files using the fs module in node and then use the cut/copy to inform the clipboard of their selection, then it should be possible to paste it in explorer/finder.

My use case is developing a node based explorer/finder app that is cross platform which should appear native to the user.

Thanks a ton if you consider my request and I would be happy to make a separate ticket if you so desire.

**Comment by bpasero** [comment]
+1!

**Comment by gaohailang** [comment]
+1
i want to achieve a function when user drags a gif in electron work like in MacOS's finder drag, not browser which only capture only one frame of gif.

**Comment by luan007** [comment]
Also +1 on this issue.. 

My 2cents on OSX though:

first do `npm install nodobjc` <-- this seems failing for a while, you may try cloning the nodobjc repo and do `npm install` in base directory... 


then in your app:

``` javascript

var $ = require('nodobjc')

$.framework('Foundation')
$.framework('AppKit')

var pb = $.NSPasteboard('generalPasteboard');
var pool = $.NSAutoreleasePool('alloc')('init')

function fetch(t){
	var dt = pb('dataForType', t);
	var str = $.NSString('alloc')('initWithData', dt, 'encoding', $.NSUTF8StringEncoding);
	console.log(t, ":");
	console.log(str);
}

var prev = pb('changeCount');
setInterval(function () {
	if (pb('changeCount') == prev) {
		return;
	}
	prev = pb('changeCount');
	console.log(pb('types'));
	fetch($.NSFilenamesPboardType);
	fetch($.NSStringPboardType);
	fetch($('public.html'));
	fetch($('public.rtf'));
	fetch($('WebURLsWithTitlesPboardType'));
	// fetch($('com.apple.icns'));
	// fetch($('public.png'));
	// fetch($('public.tiff'));
}, 1000);

```

Code above wraps around obj-c's NSPasteboard instance to get new data with setInterval, 
(http://stackoverflow.com/questions/3610600/get-notified-when-something-is-added-to-nspasteboard)
and basic 'Types' are shown in the snippet. 

As for @teamrun 's need, NSFilenamesPboardType would suffice as what you might want is the 'real path' of the file (multi-select should work, too)


Would love to see official implementations :bulb:  keep hacking

**Comment by fuermosi777** [comment]
+1 

All my images in the clipboard from Finder are previews, too. I also notice that in Slack app (which is using Electron), if you paste image, it also shows the preview image instead of the real image. It looks more like a bug to me...

![image](https://cloud.githubusercontent.com/assets/7303373/15795796/f2312a38-29a9-11e6-9bb0-823838d4230b.png)

**Comment by MrSnappingTurtle** [comment]
+1.

 I'm writing a clipboard manager and it would be awesome if I could have actual files work with it.

**Comment by f111fei** [comment]
+10086
Adobe Air had supported this feature.

**Comment by bertofer** [comment]
+1

Working on a file manager, this would be ideal to have. I will look for alternatives while this gets some progress, will post here if I find something. Thanks @luan007 I will have a look at your solution! Looks good for OS X!

**Comment by redhotbeani** [comment]
+1 
Would be nice if I could select an image in Windows Explorer and copy it into our Electron app. As mentioned before, Adobe Air supported this feature. But we've switched to Electron because Air has an outdated webkit browser.

**Comment by Augus** [comment]
+1

**Comment by Augus** [comment]
Thank You @luan007 

`var $ = require('nodobjc')

var paths = ['/file-path-1', '/file-path-2']
copyFilesToClipboard(paths);

function copyFilesToClipboard (paths) {

	$.framework('Foundation')
	$.framework('AppKit')

	var pasteboard = $.NSPasteboard('generalPasteboard');
	var changeCount = pasteboard('clearContents');
	var filesToCopy = $.NSMutableArray('alloc')('init');

	paths.forEach(function (image) {
		var string = $.NSString('stringWithUTF8String', image);
		filesToCopy('addObject', $.NSURL('alloc')('initFileURLWithPath', string));
	});

	pasteboard('writeObjects', filesToCopy);

};


`

**Comment by s-a** [comment]
Any news about this topic?

**Comment by hokein** [comment]
The issue has been fixed in chrome 48 (https://bugs.chromium.org/p/chromium/issues/detail?id=553686). It should work in the latest electron.

**Comment by s-a** [comment]
Mentioned method ```copyFilesToClipboard``` does not work on windows 10.

    var $ = require('nodobjc')
    
    var paths = ['c:\\git\\sulu\\clipboard.js', 'c:\\git\\sulu\\Gruntfile.js']
    
    function copyFilesToClipboard (paths) {
    
    	$.framework('Foundation')
    	$.framework('AppKit')
    
    	var pasteboard = $.NSPasteboard('generalPasteboard');
    	var changeCount = pasteboard('clearContents');
    	var filesToCopy = $.NSMutableArray('alloc')('init');
    
    	paths.forEach(function (image) {
    		var string = $.NSString('stringWithUTF8String', image);
    		filesToCopy('addObject', $.NSURL('alloc')('initFileURLWithPath', string));
    	});
    
    	pasteboard('writeObjects', filesToCopy);
    };
    
    copyFilesToClipboard(paths);

When I execute this script i get...
```shell
C:\git\test>node clipboard.js
C:\git\test\node_modules\ffi\lib\dynamic_library.js:74
    throw new Error('Dynamic Linking Error: ' + err)
    ^

Error: Dynamic Linking Error: Win32 error 126
    at new DynamicLibrary (C:\git\test\node_modules\ffi\lib\dynamic_library.js:74:11)
    at new Library (C:\git\test\node_modules\ffi\lib\library.js:45:12)
    at C:\git\test\node_modules\nodobjc\lib\core.js:20:14
    at Object.<anonymous> (C:\git\test\node_modules\nodobjc\lib\core.js:410:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)

```

**Comment by bravekingzhang** [comment]
I found a solution:

```javascript
const clipboardWatcher = require('electron-clipboard-watcher')

	clipboardWatcher({
		// (optional) delay in ms between polls
		watchDelay: 1000,

		// handler for when image data is copied into the clipboard
		onImageChange: function (nativeImage) {
			//console.log(nativeImage.toDataURL())
			mainWindow.webContents.send('onImageChange', nativeImage.toDataURL())
		},

		// handler for when text data is copied into the clipboard
		//		onTextChange: function (text) {
		//			mainWindow.webContents.send('onTextChange', text)
		//		}
	})
```

the idea is

watch clipboard onImageChange in main process `can get nativeImage` ,then , send to the`DataURL` to  render process

the demo can be show here 

https://github.com/bravekingzhang/httpImage

![image](https://cloud.githubusercontent.com/assets/4476322/21676417/7c4ed808-d370-11e6-9510-5191a79c9332.png)
