### ISSUE TITLE
Unable to use files from app.asar in worker_threads

### ISSUE THREAD

**Issue by APshenkin** [electron/electron#22446]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 7.x, 8.x, 9.x
  * 
* **Operating System:** macOS 10.15.3
  * 
* **Last Known Working Electron version:**
  * 

### Expected Behavior
Ability to require files and modules from asar.pack

### Actual Behavior

By default you can't search in app.asar at all. But you can run in worker
```process._linkedBinding('atom_common_asar'). initAsarSupport(require)```

Then it will start check, but when find asar and try to create Archive here https://github.com/electron/electron/blob/602913cb4c98d102548e082c97401415849fe082/shell/common/api/electron_api_asar.cc#L22

With EXC_BAD_ACCESS error
Full log availible here https://gist.github.com/APshenkin/c7e94d40dcb6784db42f573da55c2102

### To Reproduce
1. Create worker by worker_threads in main process that will require app.asar file

**Comment by Ramkumar92** [comment]
Any solution to this issue?

**Comment by APshenkin** [comment]
Found workaround for this so that you shouldn't unpack the whole app.asar

1. Add `asar-node` to your dependencies

```
"dependencies": {
    "asar-node": "^2.1.3",
}
```

2. in you electron-builder config add asarUnpack with all your worker scripts and with `asar-node` package
asarUnpack:

```
  - node_modules/asar-node
  - build/myWorker.js
```

3. In place when you run worker check that you run in production mode and change path to app.asar.unpacked

```
 const scriptPath = isDevelopment ?
        path.join(__dirname, './myWorker.js') :
        path.join(process.resourcesPath, 'app.asar.unpacked/build/myWorker.js');
```

4. In your worker scripts add check that you run in production mode, and then require `asar-node` package and required files from asar

```
const { workerData } = require('worker_threads');

const {
  isDevelopment
} = workerData;

let myFile

if (isDevelopment) {
  myFile = require('./myFile')
} else {
  const { register, addAsarToLookupPaths } = require('asar-node')

  register()
  addAsarToLookupPaths()
  myFile = require('../../../../app.asar/build/myFile')
}
```

This code looks a little bit ugly, but it works (not 100% sure that will work with native modules)

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
