### ISSUE TITLE
difference in performance when opening page in electron vs in chromium. suggest optimization

### ISSUE THREAD

**Issue by nenadlazovic** [electron/electron#22454]
Hi,
I have a simple web page playing famous big_buck_bunny_1080p_h264.mov (see below).
Environment: Node 12.13.0, Electron 8.0.1, Chrome 80.0.3987.86 on Raspberry PI 4 2 GB

When I open that page in chrome standalone, I am getting avg CPU usage approx 25% and avg load approx 1.6
When I open same page in simple electron project , I am getting avg CPU usage approx 50% and avg load approx 2.4 

1. Is it reasonable to expect that same page should consume approx same CPU when run standalone and in electron ?
2. If yes, can somebody suggest changes to get it to standalone chrome performance ?

**Chromium standalone case**
Chromium, when run standalone, has following command line options
`/usr/lib/chromium-browser/chromium-browser-v7 --disable-quic --enable-tcp-fast-open --ppapi-flash-path=/usr/lib/chromium-browser/libpepflashplayer.so --ppapi-flash-args=enable_stagevideo_auto=0 --ppapi-flash-version=32.0.0.330 --enable-pinch --flag-switches-begin --disable-accelerated-2d-canvas --force-gpu-rasterization --ignore-gpu-blacklist --flag-switches-end 
`

**Page in Electron case**
When running in electron, I tried running electron without / with all various command line options, to ensure GPU is used , like  
`--disable-accelerated-2d-canvas --force-gpu-rasterization --ignore-gpu-blacklist --enable-native-gpu-memory-buffers 
`

**Page with one video in it**
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Security-Policy" content="script-src 'self' 'unsafe-inline';" />
</head>
<body>

<video width="1280" height="720px" controls autoplay style="top: 110px; left: 320px; position: absolute;">
    <source src="big_buck_bunny_1080p_h264.mov" type="video/mp4">
</video>

</body>
</html>

```

**Comment by nenadlazovic** [comment]
Not being experienced in electron, I just realized that difference is likely due to fact that electron uses its own version of chromium (in this case 80.0.3987.86), not chromium that comes as part of Raspbian Buster with desktop (78.0.3904.108).

Is there a way to get Electron to use chromium that is part of Raspbian Buster with desktop ?

**Comment by SilurianYang** [comment]
I happen to have the same problem as you. I have a static page that has nothing to do with it and no excessive calculations. CPU can reach 8-10% on average

**Comment by ferment-it** [comment]
I am encountering the same issue on Electron 10.1.3 My RPi has the same Chromium- 78.0.3904.108 (Official Build) Built on Raspbian , running on Raspbian 10 (32-bit), though it's 4GB ram

I'm trying to play a 3GB h264 file - native Chromium browser shows 15% CPU consumption max for the busiest process (without launching with any GPU acceleration flags). Electron shows ~275% CPU, even with the GPU flags. And playback is very choppy.

Any ideas? Thanks

**Comment by KiaraGrouwstra** [comment]
Running video calls in Discord desktop (Electron) vs. their web app (in Chrome), I'm experiencing the exact same performance differences. I'm running Arch Linux, if that matters.

**Comment by nornagon** [comment]
Thanks for the reports. It's reasonable to expect that the performance should be similar between Electron and the version of Chromium on which that version of Electron is based (which you can see [here](https://github.com/electron/releases#releases).

Some followup questions:
- Does this only happen on Raspberry Pi?
- Is this still happening on current versions of Electron (v13+)?

**Comment by KiaraGrouwstra** [comment]
For me this happened on my laptop (not ARM like RPi).
That said Discord still seems to be on Electron 12, so from them I cannot tell if this is solved with v13.

**Comment by joperator** [comment]
> It's reasonable to expect that the performance should be similar between Electron and the version of Chromium on which that version of Electron is based

I also expected this, but tested several versions of Electron and Chrome on Windows 10 (version 22H2) with the following small application:

package.json
-

```json
{
  "name": "performance-test",
  "version": "1.0.0",
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  }
}
```

main.js
-

```js
const { app, BrowserWindow } = require("electron");

app.on(
    "ready",
    () => {
        const win = new BrowserWindow({
            fullscreen: true,
            kiosk: true
        });

        win.removeMenu();
        win.loadURL("https://testdrive-archive.azurewebsites.net/performance/fishbowl/");
    }
);

```

This application loads [Fish Bowl HTML5 Graphics Benchmark](https://testdrive-archive.azurewebsites.net/performance/fishbowl/) in fullscreen mode. If I select `Fish -> Auto`, the number of fish is automatically increased as long as 60 FPS are supported. Depending on the system hardware (CPU, GPU, RAM, ...) the number of fish settles around a certain value. However, on the same system, it makes a difference whether the URL is loaded in Electron or Chrome: In Electron, the number of fish increases slower than in Chrome and settles around a value that is 10% to 50% lower than in Chrome. Even when using the latest Electron release with a Chromium version that is newer than the installed version of Chrome, Chrome has better performance than Electron.

So to finally answer your questions, @nornagon:

> - Does this only happen on Raspberry Pi?

No, this also happens on Windows.

> - Is this still happening on current versions of Electron (v13+)?

Yes, it's still happening: Tested with the latest stable [electron v24.3.1](https://github.com/electron/electron/releases/tag/v24.3.1) and pre-release [electron v25.0.0-beta.8](https://github.com/electron/electron/releases/tag/v25.0.0-beta.8) against the current Google Chrome version 113.0.5672.127.

Does anyone have an idea why?
Maybe there's a patch or some compile flag that makes Chromium for Electron slower than Chrome?
Any hint would be greatly appreciated.

**Comment by acnebs** [comment]
[Our users are seeing similar issues.](https://community.supernotes.app/t/degraded-desktop-app-performance-on-late-2015-imac/853)

@nornagon Can we re-open this issue? I think it is worth continuing to investigate this and @joperator repro seems like a good start.

**Comment by GrabbenD** [comment]
Bump @nornagon

**Comment by DrewImm** [comment]
Why's this closed? I just installed latest Electron today and I'm also seeing noticeably worse performance in Electron.

Electron Version: ^28.0.0
Chrome Version: Version 120.0.6099.71 (Official Build) (64-bit)


threejs scene with 1000 cubes and 100 point lights (randomly spread over 100 units in all directions). Around 30fps in chrome, around 15 in electron

**Comment by negative0** [comment]
I am also facing the same issue. Please re-open this ticket.

**Comment by iojanis** [comment]
This should really be addressed. A game of mine sees 50 % worse performance on a packed electron app compared to the browser version.

**Comment by Komdosh** [comment]
Same here
