### ISSUE TITLE
Anything based on electron lags a lot on Linux compared to Windows

### ISSUE THREAD

**Issue by Joe23232** [electron/electron#22458]
So with anything that uses electron, whether it would be chromium-based browsers, the atom text editor etc, when scrolling or doing anything else, the program is pretty laggy. From what I have determined when using a Chromium-based browsers (lets take the `brave` browser as an example) they all unnecessarily taking up too much CPU processing power. I pressed `shift`+`esc` on both Windows and Linux within the browsers and I found that Brave was taking up way too much CPU processing power compared to Windows (Atom does not have its own built in task manager afaik but I am assuming this is the same issue for Atom as well). So I compared two websites [Benchmark Your Graphics Card On Linux](https://linuxconfig.org/benchmark-your-graphics-card-on-linux) and [WhatsApp Web](https://web.whatsapp.com/)

# CPU use for Brave for Windows

## Benchmark Your Graphics Card On Linux
Idle:		1-4
Scrolling:	30-40

## WhatsApp Web
Idle:		0
Scrolling:	30-60

## GPU Process (for Benchmark Your Graphics Card On Linux website)
Idle:		0-3
Scrolling:	18-48

---

# CPU use for Brave for EndeavourOS (Arch Linux-based distro)

## Benchmark Your Graphics Card On Linux
Idle:		17
Scrolling:	140-160

## WhatsApp Web
Idle:		0
Scrolling:	153

## GPU Process (for Benchmark Your Graphics Card On Linux website)
Idle:		2-5
Scrolling:	110

---

So I am not too sure why on Linux electron-based programs are taking up more CPU processing power compared to Windows, if anyone knows what is going on I would love to know. Thanks :)

**Comment by MarshallOfSound** [comment]
Brave is not electron based.  It sounds like your OS has perf issues with chromium itself so you should raise with brave / chromium directly if you can consistently repro

**Comment by Joe23232** [comment]
Hey man, this is an issue with Atom as well as I mentioned above. I beleive this is all to do with electron. I thought chromium is based on electron? And for sure I know that Brave is based on Chromium.

**Comment by codebytere** [comment]
@Joe23232 Electron is based on Chromium, not the other way around. And no, Brave is not based on Electron. It is based on pure Chromium: https://www.computerworld.com/article/3328781/brave-browser-goes-full-chromium-by-adopting-google-ui.html

We suggest you report this issue to Chromium directly, as @MarshallOfSound indicated above.
