### ISSUE TITLE
Menu item: custom accelerator string

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#22462]
It'd be useful to be able to write a custom string in menu items where accelerators usually are displayed.

The main reason behind this for me is that Electron doesn't support shortcut sequences, so apps that implement them, like VSCode, have to resort to the following, which IMHO looks pretty ugly:

![image](https://user-images.githubusercontent.com/1812093/75625476-6121c500-5bb6-11ea-808d-ab5f505cb073.png)

**Comment by codebytere** [comment]
@fabiospampinato thanks for the feature request! We'd love to be able to provide this kind of UI customization, but unfortunately this is a [macOS-level](https://developer.apple.com/documentation/appkit/nsmenuitem/1514815-keyequivalentmodifiermask?language=objc) restriction. Should something change in the future on Apple's end, i'll give this a try!
