### ISSUE TITLE
Enabling Metal support in Chromium.

### ISSUE THREAD

**Issue by wdanilo** [electron/electron#22466]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.1
* **Operating System:**
  * MacOs Catalina

### Expected Behavior
We should be able to set up arbitrary flags in Chromium.

### Actual Behavior
According to the documentation: https://github.com/electron/electron/blob/master/docs/api/command-line-switches.md we can use the `app.commandLine.appendSwitch` to control a few predefined options. The list is very short in comparison to the Chromium flags that we can find when entering `chrome://flags/` from the browser. In particular, I want to enable `Metal` support in my Electron app on MacOS. Is there any way to do it currently? If not, then I believe this is a pretty serious limitation which should be considered a bug. In case there is this possibility, the docs do not tell a word about it and it should also be considered a bug.

**Comment by MarshallOfSound** [comment]
That documentation page is a list of all the chromium flags that we know work, not all the ones that could work.

Using the `appendSwitch` API with any chromium flags might work but there's so way we can test all of them.

The only way to know if it works is to try it, so find the flag you want and give it a shot.  If it doesn't work we can take it from there but it's worth pointing out that sometimes there's nothing we can do about a flag not working.

**Comment by wdanilo** [comment]
@MarshallOfSound Thank you so much for the help. I think it would be beneficial to add this explanation to the docs, as there is no place explaining that other flags might work using this method.
