### ISSUE TITLE
Serial API support

### ISSUE THREAD

**Issue by reillyeon** [electron/electron#22478]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
The [Serial API](https://wicg.github.io/serial/) is a draft specification from the Web Incubator Community Group. There is a prototype implementation [being developed](https://bugs.chromium.org/p/chromium/issues/detail?id=884928) inside the Chromium project (by me). Developers have asked whether this API will be supported in Electron in addition to being available in regular web browsers. As this API requires the user to grant permissions there is some work required on the Electron side before it will be supported.

### Proposed Solution
[A pattern](https://www.electronjs.org/docs/api/web-contents#event-select-bluetooth-device) for this already seems to exist for the Web Bluetooth API. When `navigator.serial.requestPort()` is called a `select-serial-port` could be fired with a list of available serial ports and a callback. Applications would have the option of presenting their own UI to the user or automatically selecting a particular port. Example,

```js
const { app, BrowserWindow } = require('electron');

let win = null;

app.on('ready', () => {
  win = new BrowserWindow({ width: 800, height: 600 });
  win.webContents.on('select-serial-port', (event, portList, callback) => {
    event.preventDefault()
    let result = portList.find((device) => {
      return port.portName === 'COM1'
    })
    if (!result) {
      callback('')
    } else {
      callback(result.portId)
    }
  })
})
```

In addition an application could choose to bypass the permission-based flow altogether and configure Electron to return all available ports in response to a call to `navigator.serial.getPorts()`.

The Chromium content layer API for this is [`SerialDelegate`](https://source.chromium.org/chromium/chromium/src/+/master:content/public/browser/serial_delegate.h).

### Alternatives Considered
There are existing NodeJS modules for communicating with serial ports, such as [node-serialport](https://serialport.io/). The advantage of supporting the Serial API is the ability for applications to share code between their Electron and web versions without the need for a polyfill layer. I am considering adding one to [the Serial API polyfill](https://github.com/google/web-serial-polyfill) anyways but that is likely more work than hooking up the API to work in Electron using Chromium's built-in implementation.

### Additional Information
[Chrome status entry](https://chromestatus.com/feature/6577673212002304) for the Serial API.

Whatever code is added for this API should be directly applicable for resolving #21311 to allow access to the WebHID API as well.

**Comment by nornagon** [comment]
Handling serial permissions similarly to bluetooth / HID seems reasonable to me. Is this API present in Chromium already?

**Comment by reillyeon** [comment]
It is present but still behind the experimental web platform features flag because the implementation is incomplete.

**Comment by nornagon** [comment]
Great, sounds like we should be able to start work on providing these events today, then.

Any interest in working up a PR? :)

**Comment by reillyeon** [comment]
I'll think about it. :)

**Comment by gniezen** [comment]
Any chance this API will be applicable to resolving https://github.com/electron/electron/issues/14545 as well, or would that still need a refactoring of WebUSB in Chromium?

**Comment by reillyeon** [comment]
Once the WebUSB implementation is refactored to have a content layer API similar to what WebHID and the Serial API do, it will be applicable.

**Comment by gniezen** [comment]
@nornagon Hi there! Has there been any movement on adding serial/HID permissions? I would love to be able to use the Chromium APIs in Electron!

**Comment by nornagon** [comment]
@gniezen nope, still happy to review a PR though :)

**Comment by jkleinsc** [comment]
@gniezen with our nightly build you should be able to use the chromium apis documented here: https://bugs.chromium.org/p/chromium/issues/detail?id=884928.

You will need to pass the flag ` --enable-experimental-web-platform-features` when running Electron because the web serial stuff is behind that flag.

**Comment by gniezen** [comment]
Hi @jkleinsc ! As @reillyeon explained above, permissions for the Web Serial API will have to be handled by Electron in a similar fashion to how it's currently handling Web Bluetooth permissions. At the moment, a call to `navigator.serial.requestPort` always results in `DOMException: No port selected by the user`, even with the latest nightly build.

**Comment by jkleinsc** [comment]
@gniezen ah ok I missed the bit about permissions.

**Comment by gniezen** [comment]
This is pretty exciting, thanks @jkleinsc !

> Whatever code is added for this API should be directly applicable for resolving #21311 to allow access to the WebHID API as well.

Does this mean the same will be done for the WebHID API?

**Comment by sepehr500** [comment]
"Applications would have the option of presenting their own UI to the user or automatically selecting a particular port." 

I'm struggling to get the list of ports exposed in the render process. How do I set the permissions so navigator.serial.requestPorts() works correctly?

**Comment by gniezen** [comment]
@sepehr500 Have a look at this Web Serial tutorial: https://web.dev/serial/#use . `navigator.serial.getPorts()` only returns a list of serial ports the user has previously granted access to. `navigator.serial.requestPort()` will return a list of all ports.

**Comment by reillyeon** [comment]
> `navigator.serial.requestPort()` will return a list of all ports.

This is not correct. `requestPort()` will only return a single port, but the `select-serial-port` event that Electron fires contains the list of all ports and one of them can be selected as the return value of `requestPort()`. This is because in the web version of the API the `requestPort()` method triggers UI which only allows the user to select one of a list of ports that are available.

**Comment by sepehr500** [comment]
My goal is to allow the user to pick from a list of serial ports. How do I get the list of ports to the UI so the user can make the selection?

**Comment by jkleinsc** [comment]
@sepehr500 in Electron, you will need to listen for the [select-serial-port](https://www.electronjs.org/docs/latest/api/session/#event-select-serial-port-experimental) event on the session in order to get a list of ports to display to the user so that the user can make a selection.  Also, as the [documentation](https://www.electronjs.org/docs/latest/api/session/#event-select-serial-port-experimental) states, 
>Because this is an experimental feature it is disabled by default. To enable this feature, you will need to use the --enable-features=ElectronSerialChooser command line switch. Additionally because this is an experimental Chromium feature you will need to set enableBlinkFeatures: 'Serial' on the webPreferences property when opening a BrowserWindow.
The experimental flags will not be needed for 15.x and higher but currently released versions of Electron require these flags to be set.

Also, here is an example Electron app demonstrating how to work with the Serial API in Electron: https://gist.github.com/284893c7f01d3cb4559508ca06919481

**Comment by sepehr500** [comment]
Thanks for the reply. Every example I have seen selects a port from `portList` and passes that port id into the callback. This isn't really what I want. I'm new to electron, so i'm not sure how I pass `portList` to the UI so I can display the options to the user and the user can make the selection. I don't think passing `portList` into the callback works correctly.

**Comment by jkleinsc** [comment]
@sepehr500 Electron doesn't provide a UI to display the list of ports, its up to the developer to create a UI to allow a user to pick a serial port, eg https://gist.github.com/jkleinsc/284893c7f01d3cb4559508ca06919481#file-main-js-L21 is where you would put in a call to display a UI to allow a user to pick a serial port.  This is different from Chromium based browsers where a UI is automatically displayed when `navigator.serial.requestPort()` is called.

**Comment by sepehr500** [comment]
@jkleinsc I appreciate the response. I looked at the docs for `showMessageBoxSync` and i'm not sure how you would use it to select from a potentially long list of options. I think an array of buttons would look strange for anything more than a couple ports. Any for what options you would use?

**Comment by jkleinsc** [comment]
@sepehr500 I'd recommend asking over at [the Electron Discord server](https://discord.com/invite/electron).
