### ISSUE TITLE
Uncaught Exception: Error: EEXIST: file already exists, mkdir

### ISSUE THREAD

**Issue by AlexWayfer** [electron/electron#22497]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * `8.0.3`
* **Operating System:**
  * Arch Linux
* **Last Known Working Electron version:**
  * `8.0.2`

### Expected Behavior

[KeeWeb](https://keeweb.info/) opens without errors.

### Actual Behavior

There is error from Electron at the second start and remaining process.

### To Reproduce

1. Install [KeeWeb](https://aur.archlinux.org/packages/keeweb/) (`1.12.3`, the latest for now) on Arch Linux.
2. Install Electron `8.0.3` (the latest for now) on Arch Linux.
3. Start KeeWeb.
4. Close KeeWeb (there are no remaining processes).
5. Start KeeWeb again.

### Screenshots

![image](https://user-images.githubusercontent.com/6510020/75759894-5a768780-5d47-11ea-8772-5772d0db7991.png)

### Additional Information

Remaining process:

```
alex       13109  0.2  0.3 636992 118028 ?       Sl   12:07   0:00 /usr/lib/electron/electron --disable-updater /usr/lib/keeweb/app.asar
```

**Comment by codebytere** [comment]
@AlexWayfer this seems to be an issue with KeeWeb's temporary file cleanup, and not with Electron itself. You should open an issue there - if they determine that it occurs in a way whose cause provably lies with Electron, we'll be happy to re-open and take a look at this.

**Comment by AlexWayfer** [comment]
OK, it's only with specific Electron version, so I've come here, but I've opened the issue for KeeWeb.
