### ISSUE TITLE
Temporary .ico files created by NativeImage should be cleaned

### ISSUE THREAD

**Issue by raksooo** [electron/electron#22500]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.10
* **Operating System:**
  * Windows 10 (1909)

### Expected Behavior

Temporary .tmp.ico files created by NativeImage in \Users\\\<user>\AppData\Local\Temp\ should be cleaned after NativeImage is destroyed or when application exits.

### Actual Behavior

The .tmp.ico file is left in \Users\\\<user>\AppData\Local\Temp\. If the application is opened multiple times there are multiple temporary icons.

### To Reproduce

1. Create a NativeImage with an .ico file archived in an asar-archive
2. Start the application
  2a. Check that a .tmp.ico file was created in \Users\\\<user>\AppData\Local\Temp\
3. Quit the application
  3a. Notice that the file wasn't deleted

### Additional Information

This is related to https://github.com/electron/electron/issues/10796 with the difference that #10796 answered whether or not the files could be deleted and didn't address that they should be deleted automatically.

The code doing the copying:
https://github.com/electron/electron/blob/v1.8.1/atom/common/api/atom_api_native_image.cc#L168-L184

**Comment by pronebird** [comment]
Would it be possible to load icon directly from ASAR instead of dumping it to disk first? Seems like WINAPI supports that via `CreateIconFromResourceEx`.

**Comment by MarshallOfSound** [comment]
Because these files are created in `Temp` they can (and will) be cleaned by the OS whenever it wants to.  Them being left behind is ok as the OS will clean this folder up.

**Comment by pronebird** [comment]
@MarshallOfSound there is absolutely no way this can be addressed in the future by reading the ICO directly from memory (asar) vs. extracting it to filesystem? Seems like you dismiss the case without consideration. I realise you guys have plenty of work to do besides dealing with this, but sounds like a good improvement.

**Comment by Gitoffthelawn** [comment]
Can this be re-opened please?  It's still an issue.  Windows does not automatically empty the system temp folder when third-party apps leave orphaned files in that folder.  It relies on apps to clean up their own mess.
