### ISSUE TITLE
Expose DOM elements to VR/WebGL

### ISSUE THREAD

**Issue by greggman** [electron/electron#22526]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Would love to use HTML to build VR 

### Proposed Solution

Add options to make this possible in Electron. Possible and complementary solutions

1. Allow copying HTML to a texture

Chromium currently prevents this since it is a security risk but Electron is for making native apps so that security risk is less (similar to other Electron security issues)

This solution has multiple issues but can still be useful. One issue is actually getting Chromium to render a bunch of HTML to a texture. You'd need some API that you specify a texture and its size, followed by the size of the HTML or sub dom tree you want to render, the width of the virutal page and the sub portion of that page you want drawn into the texture. Another is that it would not be live. It's a *snapshot* of the current state of some subtree of the DOM. Some of this already exists since the extension API has APIs for taking screenshots.

Another issue is the HTML being just an image is interactive. You can't click on elements.

2. Allow referencing the compositor's textures from JavaScript.

[Firefox actually had an experiement to allow this](https://developer.mozilla.org/en-US/docs/Tools/3D_View). Could add a similar API into Electron. Plus: is it might not be *too* hard, the compositor already makes all these textures you just have to provide a list of them and where they go. Plus: Easy it integrate with WebGL, you pass these textures into your own shaders, do whatever you want with them. Plus: Updated automatically as HTML updates. Minus: Not interactive. The browser would not handle mouse events, etc....

3. Render the browser itself in VR using 3D CSS

In this case the browser would render a sub tree of the DOM elements in VR (meaning it would render the DOM elements twice, once for each eye). The easiest solution would probably be to piggy back off the fullscreen API since it already lets you choose only a subtree of the DOM to show.  Plus: 3D CSS already works for specifying 3D positions and the browser handles mouse events. Minus: Harder to itegrate with WebGL

4. Provide a way to make the canvas a background so you can mix WebGL content with 3D CSS (share the depth buffer). Solution 3 would only let you have a canvas as a 2D plane in 3D css. Ideally you'd like to be able to mix HTML elements in a 3D scene. 1 and 2 might let you show the textures in a 3D scene but they won't let interact. So, provide some way to designate a canvas to share a depth buffer with the solution from 3 above.

Note: thought needs to be given for example should you be able to renderer the HTML to a render target so that you can then post process vs only being able to render to a canvas which you can't

### Alternatives Considered

?

### Additional Information

Whether I personally have time to try this I don't know but Electron seems a great place to experiment in that it could actually ship the features where as many things are making it difficult to expose such functionality to the web. It seemed like a good place to post this as a place to coordinate with others that might want to help pursue these features.

**Comment by nornagon** [comment]
This is a cool idea but it is outside of the scope of the Electron project to support such functionality.
