### ISSUE TITLE
Invalid media type: 'screen'

### ISSUE THREAD

**Issue by le0zh** [electron/electron#22530]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
7.1.13
  * 
* **Operating System:**
macOS 10.15.3
  * 
* **Last Known Working Electron version:**
  * 

### Expected Behavior
According to the [docs](https://www.electronjs.org/docs/api/system-preferences#systempreferencesgetmediaaccessstatusmediatype-macos) about `getMediaAccessStatus`. `screen` should be a valid media type. 

And `systemPreferences.getMediaAccessStatus("screen")` should work as expected.

### Actual Behavior
Got `Invalid media type` error in main process.

### Screenshots

![image](https://user-images.githubusercontent.com/3633972/75887107-3d83a680-5e64-11ea-9d16-24fdd729e23e.png)

**Comment by erickzhao** [comment]
It seems like the "screen" type was added in Electron 8 and works fine in that version.

If you look at the docs from v7.1.13, you can see that it doesn't yet exist: https://github.com/electron/electron/blob/v7.1.13/docs/api/system-preferences.md#systempreferencesgetmediaaccessstatusmediatype-macos
