### ISSUE TITLE
Possibility to control window corner radius

### ISSUE THREAD

**Issue by wdanilo** [electron/electron#22542]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
Would it be possible to have an option to set rounded corner radius of windows? I know I can use transparent windows and div inside, but then vibrancy does not work. 

### Proposed Solution
I think the patch (at least for MacOS) would be simple, as here is just a code which explicitly sets the radius but it is just not configurable: https://github.com/electron/electron/blob/master/shell/browser/native_window_mac.mm#L217

**Comment by MarshallOfSound** [comment]
@wdanilo That code does not set the radius of the window, it sets the radius of the rendered progress bar.  Configuring the border radius on macOS is not directly supported by apple let alone other platforms which have no concept of rounded corners for the windows.

This isn't something we can implement at this time
