### ISSUE TITLE
Net request replaces cookie header with session cookies

### ISSUE THREAD

**Issue by ilias-t** [electron/electron#22541]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * From v7.1.14 to v9.0.0-beta.5
* **Operating System:**
  * macOS 10.15.3
* **Last Known Working Electron version:**
  * v6.1.9

### Expected Behavior
A `net` request that sets a cookie using `request.setHeader` should include the specified header.

### Actual Behavior
Instead, when cookies from the session cookie jar are present, they are sent instead and the specified header is ignored.

### To Reproduce
Run this code:
```js
const electron = require('electron');
electron.app.on('ready', async () => {
  await makeRequest();
  // A long timeout is required for it to be reproducible when running this script on the first try, in a clean session
  setTimeout(async () => {
    console.log(await electron.session.defaultSession.cookies.get({}));
    await makeRequest();
  }, 10000);
});

function makeRequest() {
  return new Promise(resolve => {
    const request = electron.net.request({ url: 'https://www.twitter.com' });
    request.setHeader('cookie', 'foo=bar');
    request.on('close', resolve);
    request.end();
  });
}
```

### Screenshots
When running the above code, all requests after the initial one shows a cookie header with this value, which reflects the value that is present in the session's cookies.
<img width="795" alt="image" src="https://user-images.githubusercontent.com/4505008/75946161-2be4d380-5e51-11ea-81ad-bb2769de8fe0.png">

### Additional Information
* To see the incorrect headers, you must inspect the network request in a proxy such as Fiddler.
* This was previously reported in #8223, fixed in #8258, but now seems to have been regressed.
* Also #8891 seems to be possibly implemented by accident now?

**Comment by NilSet** [comment]
Seems the flag added in #8258 was deleted in a chromium upgrade https://github.com/electron/electron/pull/19488/files#diff-b0d406e17d88850bd84bfabe2fedd5b8L127
