### ISSUE TITLE
Getting Error: Invalid Provisioning Profile. The provisioning profile included in the bundle is invalid [Missing code-signing certificate]

### ISSUE THREAD

**Issue by ssondhi123** [electron/electron#22547]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by ssondhi123** [comment]
i am getting this error to upload the .pkg file to mac store using transporter app
Error:-  Invalid provisioning profile. The provisioning profile included in the bundle is invalid




Following are the details: -
"electron": "^6.1.4",
"electron-builder": "^22.0.0",

package.json:-

"build": {
"productName": "Fantom Wallet",
"appId": "********** appId********",
"mac": {
"category": "public.app-category.productivity",
"target": [
"pkg",
"dmg",
"zip",
"mas"
],
"provisioningProfile": "embedded.provisionprofile",
"entitlements": "build/entitlements.mac.plist",
"type": "distribution",
"icon": "build/icon.icns"
},
"mas": {
"type": "distribution",
"category": "public.app-category.productivity",
"entitlements": "build/entitlements.mas.plist",
"icon": "build/icon.icns"
},
"directories": {
"buildResources": "build",
"output": "dist"
},
"files": [
"build/static",
"build",
{
"from": "build/static",
"to": "static"
}
],
"extraResources": [
{
"from": "build/static",
"to": "static"
}
]
}

Kindly provide the steps to upload the app on iTunes or is there any update in packages please give me the solutions.
 
Thank you..
![Screen Shot 2020-03-06 at 4 27 08 PM](https://user-images.githubusercontent.com/51946575/76187200-bbe09f80-61fa-11ea-88ed-53d25209a3c3.png)

**Comment by codebytere** [comment]
@ssondhi123 we recommend you open this issue on `electron-builder` instead - we are not directly responsible for ecosystem packaging tools.
