### ISSUE TITLE
`backgroundThrottling: false` with HTML select causes white screen on Windows

### ISSUE THREAD

**Issue by chetbox** [electron/electron#22551]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.1.9
* **Operating System:**
  * Windows 10
  * Not reproducible on macOS
* **Last Known Working Electron version:**
  * Fixed in 7.+

### Expected Behavior
Clicking HTML select shows options

### Actual Behavior
Clicking HTML select shows options, but then the entire renderer window goes white

### To Reproduce
On Windows 10:
- Create a new Electron project with Electron Forge: `yarn create electron-app my-app`
- Set the Electron version to `6.1.9` in `package.json`
- Run `yarn`
- Set `webPreferences: {  backgroundThrottling: false }` on the `BrowserWindow` in `index.js`
- Add a `<select>` to `index.html`. 
- Optional: Set a background color on `<body>` so it's easier to see the bug.
- Run `yarn start`
- Click the HTML `<select>` element you added and move the mouse around.

As long as devTools is open (which is the default behaviour in this project template) *or* you open a second `BrowserWindow` (this is important to use because it affects production environment) after a second or so the entire window will go white.

A minimal repro using dev tools is in this repo: https://github.com/clockwork-dog/electron-render-bug-repro

On Windows 10, using Git Bash:

```sh
$ git clone https://github.com/clockwork-dog/electron-render-bug-repro.git repro
$ cd repro
$ yarn
$ yarn start
```

Then click the `Hello` dropdown.

### Screenshots

When the window shows I see this:
![Capturebefore](https://user-images.githubusercontent.com/292958/76006673-c05c3e00-5f04-11ea-80ba-8989b343fb2f.PNG)

Then I click "Hello" and see this:
![Capture](https://user-images.githubusercontent.com/292958/76006688-c5b98880-5f04-11ea-9ac6-df65da2e31c2.PNG)

### Additional Information

We have found this problem in our production application that is using multiple `BrowserWindow`s.

**Comment by madhukudala** [comment]
@chetbox I am facing the same issue.

We have multiple browser windows with backgroungTrottling as false. When user clicks on select dropdown entire screen turns to white .

Can you please suggest us how to fix this issue.

**Comment by chetbox** [comment]
We worked around the problem by creating our own dropdown component which allows us to style the component to our liking. You could also try upgrading your Electron version. Sorry I'm not able to help any more than that, @madhukudala.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
