### ISSUE TITLE
Crash Reporter: crashes are neither persisted nor uploaded in forked process

### ISSUE THREAD

**Issue by bpasero** [electron/electron#22552]
* **Electron Version:**
  * 7.x
* **Operating System:**
  * macOS 10.15.x

Steps (without server):
* `git clone https://github.com/bpasero/electron-crashreporter`
* `yarn`
* open `constants.js` and configure:
  * `enableCrashReporter: true`
  * `crashChildProcess`: `true`
  * `tmpDir`: some location that exists that you can check on
* `yarn start`

=> 🐛there is no crash report generated on disk. I see crash report if I configure `crashMain: true` but not in the case of renderer nor child process.

Steps (with server):
* `git clone https://github.com/bpasero/electron-crashreporter`
* `yarn`
* open `constants.js` and configure:
  * `enableCrashReporter: true`
  * `crashChildProcess`: `true`
  * `tmpDir`: some location that exists
* `uploadToServer: true`
* `submitURL: 'http://localhost:1127/post'` (from https://github.com/electron/mini-breakpad-server)
* `yarn start`

=> 🐛 no crash is uploaded. it works fine when crashing main

**Comment by Colengms** [comment]
With (some changes to) the `electron-crashreporter` repo referrenced above, I'm seeing that a crash of a native child process IS NOT intercepted by Electron, with crash reporter enabled, if exec'ed from code loaded via index.html (i.e. renderer.js).  However, it IS intercepted by Electron if launched from code invoked from main ("main" in package.json).  In fact, if there is a chain of process exec's, the last process in that chain will get crashes collected, despite the intermediate process in the chain not starting createReporter.

I'm trying to diagnose another issue, in which a native process exec'ed by our extension to VS Code (an Electron app) is not triggering OS crash reports on macOS, despite generating them when run outside of VSCode/Electron.  They appear to be intercepted by crashReporter.

Is there a way to explicitly exec a process without crashReporter, from our extension that does not have direct access to Electron APIs?

**Comment by vyunikov** [comment]
Is there any progress on this?
On Electron 10.1.3 it doesn't work either. I start crash reporter on the main process and expect it to monitor crashes in my child forked process, but in fact dump doesn't get saved to a disk nor uploaded.

**Comment by vyunikov** [comment]
Managed to make it work with Electron 10: #24779#issuecomment-716420456

**Comment by VishwasShashidhar** [comment]
I see this issue with `9-x-y` as well unfortunately.

**Comment by deepak1556** [comment]
The repro is no longer valid, child process on mac and windows will be monitored automatically once crashpad is started in main process. It is working fine in vscode, if the issue is still perceived by other apps, please open a new issue with a minimal repro. Thanks!
