### ISSUE TITLE
app.focus() not working

### ISSUE THREAD

**Issue by devinfoley** [electron/electron#22554]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

It would appear that `app.focus()` stopped working in Electron 6, and remains broken in Electron 8.

* **Electron Version:**
  * 8.0.3
* **Operating System:**
  * macOS
* **Last Known Working Electron version:**
  * 5.0.13

### Expected Behavior
`app.focus()` should bring the application to the foreground.

### Actual Behavior
`app.focus()` does nothing.

### To Reproduce

Fiddle: https://gist.github.com/a772265b312329e3f3bc1feb7b6aff7d

1) Start this fiddle.
2) As soon as the window pops up, select another application so that Electron is in the background.
3) Within 5 seconds, the app will attempt to focus itself to no avail.

**Comment by codebytere** [comment]
@devinfoley this appears to have been intentional: https://github.com/electron/electron/pull/16400

**Comment by MarshallOfSound** [comment]
The use case here is for things like dragging files from app A to app B.  App B needs to be able to focus itself after receiving a file, currently it cant.

**Comment by mifi** [comment]
Will this make it into 8.x version?
