### ISSUE TITLE
Request: Add documentation describing differences between process.memoryUsage and performance.memory

### ISSUE THREAD

**Issue by gkjohnson** [electron/electron#22561]
Hello! I tried posting this issue on the [forum](https://discuss.atom.io/t/why-are-node-process-memoryusage-and-chrome-performance-memory-values-different-in-electron/72265) but I've gotten no responses so I figured I'd ask for it to be formally documented to avoid confusion in the future.

I’m doing some memory profiling in my electron app and running with the `--enable-precise-memory-info` flag and I see there are two ways to get information on current memory allocation: Nodes `process.memoryUsage()` and Chromes `performance.memory`. Here are the values returned from each call:

```js
// process.memoryUsage()
{
  "rss": 631332864,                  // ~ 602.09 MB
  "heapTotal": 97619968,             // ~ 93.10 MB
  "heapUsed": 91908280,              // ~ 87.65 MB
  "external": 83524574               // ~ 79.66 MB
}

// performance.memory
{
  "totalJSHeapSize": 177817582,      // ~ 169.58 MB
  "jsHeapSizeLimit": 1107296256,     // 1056 MB
  "usedJSHeapSize": 175333878        // ~ 167.21 MB
}
```

As you can see the values vary pretty significantly but I would at least expect both `totalJSHeapSize` and `usedJSHeapSize` from `performance.memory` to be the same as `heapTotal` and `heapUsed`. Why are they different? Is one considered more accurate? Do they mean something different from each other?

For some more context I’m running both commands in the dev tools of the electron browser window and opening the browser window with the following options:

```
{
  // ...
  webPreferences: {
    nodeIntegration: true,
    backgroundThrottling: false,
  }
}
```

Thank you!

**Comment by nornagon** [comment]
The `performance.memory` values only include V8 heap size, whereas `process.memoryUsage()` includes all memory usage.

**Comment by gkjohnson** [comment]
@nornagon Is this in the documentation anywhere, now? I'd searched for awhile when I originally needed this info and had never found an answer.

**Comment by nornagon** [comment]
Not sure, but `process.memoryUsage` is a Node.js function and `performance.memory` is a Web API so Electron's docs aren't really the right place for a comparison.
