### ISSUE TITLE
app.setAsDefaultProtocolClient failing for tel protocol on Windows 10

### ISSUE THREAD

**Issue by jmvallejo** [electron/electron#22565]
### Preflight Checklist

* [ x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.11, 8.0.3 (tried the newer one to verify if it worked there)
* **Operating System:**
  * Windows 10 (1803)
* **Last Known Working Electron version:**
  * I think this used to work well on previous versions of Windows 10, regardless of Electron version

### Expected Behavior
`app.setAsDefaultProtocolClient('tel')` should set the current app as the default handler for tel:// protocol, which can be seen in Windows' Default Apps (by protocol):
![image](https://user-images.githubusercontent.com/14879937/76033828-3bc0ee00-5f0b-11ea-8df1-eb425dc70eeb.png)
(I think this works for other protocols, but not for tel)

### Actual Behavior
`app.setAsDefaultProtocolClient('tel')` returns `true` but Default app is not set.

### To Reproduce
Start a new electron project, call `app.setAsDefaultProtocolClient('tel')` making sure it returns `true`, then check Default app by going to Settings -> Default Apps in Windows.

### Screenshots
![image](https://user-images.githubusercontent.com/14879937/76033828-3bc0ee00-5f0b-11ea-8df1-eb425dc70eeb.png)

### Additional Information
I have found other tickets from people saying the app doesn't show up as an app that can handle the specified protocol, which I know is fixed by setting the appropriate values in the registry (already took care of that), this is specifically related to being able to set the app as the Default handler via `app.setAsDefaultProtocolClient('tel')`

**Comment by xoancosmed** [comment]
Any update on this issue? I'm experiencing the same problem in Electron 11 with Windows 10 (20H2).

**Comment by gr33k** [comment]
Any update/ETA on this please?

**Comment by ghenry** [comment]
Watching :-)

**Comment by gr33k** [comment]
2022 - and zero activity on this ticket :( 
Are we still working to resolve this issue for Windows? Any definitive fix/work-around would be appreciated. Thank you
