### ISSUE TITLE
Make Spellcheck Offline

### ISSUE THREAD

**Issue by bekalshenoy** [electron/electron#22573]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
Electron Mostly Use To Develop Offline Applications. But Spellcheck is using internet to fetch Binaries It Is Not A Good Approach.

### Proposed Solution
Make Spellcheck Offline

### Alternatives Considered
Add An Toggle Option To Make Spellcheck Offline

### Additional Information
Also Do not Want To Forcefully Add Spellcheck Binaries In Build Application If Spellcheck Is Set To False

**Comment by MarshallOfSound** [comment]
@bekalshenoy What you are asking for is not technically feasible on some platforms without dramatic sacrifices in other areas (build size, spellcheck performance / accuracy, etc.)

The spellchecker in it's current form is "offline" (if that's how you want to describe it) on macOS as it uses the native spellchecker.  On Windows 10 soon Chromium will use the native spellchecker there as well.  On linux there is no "native" spellchecker and no desire from upstream to support the multitude of different spellcheckers that could in theory be on a linux machine.

If you want offline spellcheck, your app will have to distribute the dictionaries **with** the application and manually position them in the correct directory yourself.  This is not a thing that Electron will first-party support as it is not how the spellchecker is designed to work in Chromium.  That said, it should currently be technically possible if you are prepared to pay the cost of shipping all dictionaries with your application.

Some points of clarification in your issue for future reference:

> Electron Mostly Use To Develop Offline Applications

This is incorrect at least given the apps we have / know about in our apps registry.
