### ISSUE TITLE
Relative popup windows are closed when the main window is closed

### ISSUE THREAD

**Issue by cuixiping** [electron/electron#22581]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.3
* **Operating System:**
  * Win 7
* **Last Known Working Electron version:**
  * unknown

### Expected Behavior
Relative windows should not been closed when main window is closed.

### Actual Behavior
Relative windows will be closed when main window is closed.

### To Reproduce
1. Load a page in main window.
2. Click a link or use js window.open to open a new window.
3. Close the main window. The new popup window will be closed immediately.

**Comment by t57ser** [comment]
See: https://github.com/electron/electron/issues/11128

**Comment by cuixiping** [comment]
Duplicated with #11128
