### ISSUE TITLE
Extra type=utility process in Electron 7+

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#22587]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 7, 8.0, 8.1
* **Operating System:** Windows 10
* **Last Known Working Electron version:** Electron 6

### Expected Behavior
When I launch an Electron app, I expect there to be the following processes:
main
GPU (if enabled)
renderer (for each window/browserview/webview)

### Actual Behavior
There is an extra process of type utility. Chromium documents this type [here](https://developer.chrome.com/extensions/processes), but has no explanation as to what it is.

### To Reproduce
With an example like (Electron 8.1.0):

```
const { app, BrowserWindow } = require('electron')

async function createWindow() {
  const mainWindow = new BrowserWindow();
  mainWindow.loadFile('index.html');
}

app.on('ready', createWindow)

app.on('window-all-closed', function () {
  app.quit()
})
```

When I open up Task Manager, I see 4 Electron processes:
main
GPU
Renderer
And Utility (`"...\electron.exe" --type=utility --field-trial-handle=... --service-sandbox-type=network --mojo-platform-channel-handle=1900 /prefetch:8`)

Chromium increased from 76 to 78 between Electron 6 and 7. Maybe something in the new Chromium brought this over, but could this be an electron issue?

**Comment by MarshallOfSound** [comment]
Chromium uses utility processes to run certain services.  In this case what you are seeing is the network service.
