### ISSUE TITLE
Need help finding out why there is macOS segfault on exit on my Electron app

### ISSUE THREAD

**Issue by AxelTerizaki** [electron/electron#22585]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 8.0.2

* **Operating System:** macOS Catalina 10.15.3

* **Last Known Working Electron version:** N/A
  * 

### Expected Behavior

Quit properly

### Actual Behavior

When closing the app's window or using Cmd+Q, the app quits but causes a segfault and macOS segfault report window.

### To Reproduce

I sadly can't reproduce this at home on my Mac as it only happens on a user's mac so far. I don't have enough mac users to test it out either. 

I realize this is probably an issue on my app's end, but I'd like some help in deciphering the segfault report (attached below) to see if I can get a clue as to what might be causing this. If I can find out what causes this, then I can probably fix it.

### Screenshots

None

### Additional Information

[Segfault dump](https://github.com/electron/electron/files/4300251/kmsegfault.txt)

[DMG file for a packed version](https://mugen.karaokes.moe/downloads/KaraokeMugen-next.dmg)

[App's git](https://lab.shelter.moe/karaokemugen/karaokemugen-app/-/tree/next/src) : this is on the next branch, but it might take time to setup and run properly to reproduce, so I'm just showing the repo for your info, as I believe only the segfault dump is really valuable there.

**Comment by codebytere** [comment]
As first steps go, you should use this: https://www.npmjs.com/package/@electron/symbolicate-mac to symbolicate the crash. As a very lean maintainer team, we don't have the bandwidth to investigate app-specific issues with no repros, so if you can give us a clear crash dump that is at least a better starting point.

I'm setting the blocked label for now, but as more information comes to light we may be able to remove it and triage this.

**Comment by AxelTerizaki** [comment]
Here's the version ran through electron-symbolicate :

[kmsegfault_symbolicated.txt](https://github.com/electron/electron/files/4303069/kmsegfault_symbolicated.txt)

Thank you for considering looking at it; I know most projects have a small team of developers and little time to spare.

**Comment by codebytere** [comment]
@AxelTerizaki ah that was helpful! It's this: https://lab.shelter.moe/karaokemugen/karaokemugen-app/-/blob/next/src/services/medias.ts#L9. We don't really support worker threads in Electron right now, owing to some underlying incompatibilities with V8. You should use Web Workers for now.

**Comment by AxelTerizaki** [comment]
Thank you for the precise reply!

I'll have to look into this, as it only happens on macOS and on my user's computer too (it doesn't on my Mac). It also doesn't happen on Windows versions of the same app for some obscure reason, and I made sure to close the worker threads properly on exit. But I suppose I'll have to triple-check that and look into web workers.
