### ISSUE TITLE
correct way for preload: ipc vs attaching globals

### ISSUE THREAD

**Issue by Sparkenstein** [electron/electron#22591]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.1.0
* **Operating System:**
  * Xubuntu 18.04 x64

So in latest version I read that `nodeIntegration` should not be used and official boilerplate has removed it from code. it was replaced with `preload`. I don't know much electron, so I'd like to know the correct way of using preload scripts.

to use node specific stuff like `require` etc. I simple attached
```js
global.require = require
```
in preload.js and it works. you can use CJS in renderer scripts now. But in [this](https://stackoverflow.com/questions/57807459/how-to-use-preload-js-properly-in-electron) SO post the author has stated that ipc is the correct way to use any node specific stuff.

Does that mean ALL my node specific logic will reside in preload.js ?
If I want to open a file etc I will write it in preload and communicate with ipc? (won't that affect main thread?)
 
Or is using globals fine?
```js
global.fs = require('fs')
```

**Comment by Sparkenstein** [comment]
In the [official docs](https://www.electronjs.org/docs/api/process#event-loaded) it is suggested to use globals.

**Comment by reZach** [comment]
@Sparkenstein I could be wrong, but I would guess that globals were recommended before [contextBridge](https://www.electronjs.org/docs/api/context-bridge) was a thing. 

I'd be interested to hear from one of the team members on their input of this.

**Comment by MarshallOfSound** [comment]
This is a relatively complex topic that I don't want to waste the effort of writing up in a github comment.  I'll probably write it up in a blog post or Source Of Truth document but here is the TLDR.

**Desired Web Preference**

You want to construct you window with

```
new BrowserWindow({
  webPreferences: {
    nodeIntegration: false,
    contextIsolation: true,
    sandbox: true,
  }
})
```

Communication is then done over a combination of `contextBrige` and `ipc`.

```
|-------------|  contextBridge   |-------------|   IPC   |--------------|
|   Renderer  | ---------------> |   Preload   | ------> | Main Process |
|-------------|                  |-------------|         |--------------|
```

You want to expose the minimal possible API surface.  Turning off node and then just exposing the `require` method is pointless (It's like putting up a giant protective wall and then bunching a hole right through it).

**Comment by Sparkenstein** [comment]
Thanks, I'll wait for the blog post :D 
Just for the clarification, require was just an example (It's better to resolve modules with Babel or something). My question was regarding is it okay for preload to be huge since all node specific logic is going to reside in a single place? Or am I missing something?
Surely a descriptive video tutorial or post might help since it's a new and important topic that not many people know
