### ISSUE TITLE
The navigator.connection 'onchange' event should be triggered in a renderer process

### ISSUE THREAD

**Issue by monohandle** [electron/electron#22597]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 8.1.0, 9.0.0-beta.6
* **Operating System:** macOS 10.15.3

### Expected Behavior
The `navigator.connection` API should trigger the `onchange` event.

### Actual Behavior
When accessing the `navigator.connection` object from within a renderer, the 'onchange' event is never called. This is available and working in Chromium version 80.0.3987.137.

### Additional Information
Other related issues / PR's:
https://github.com/electron/electron/issues/13074
https://github.com/electron/electron/issues/11875
https://github.com/electron/electron/pull/21004

**Comment by DariusNorv** [comment]
JFI it's not working in electron 7 as well.

**Comment by zcbenz** [comment]
There are several types of web connection changes but none of them are enabled by default in Electron. They should also be disabled by default in Chromium too but I don't know how Chrome browser have them enabled.

Anyway as a workaround, passing `--enable-network-information-downlink-max` to command line can make the event work.

**Comment by ahallicks** [comment]
@zcbenz This fix that was working has all of a sudden stopped working again in ^10.1.4 😞

**Comment by ahallicks** [comment]
@zcbenz I've been doing a bit of testing and things are even weirder now. I can't get it to work with any version of 10 (it did before).

It does work, but only if I switch off the wifi (so, disconnect the internet, for example). If I connect and disconnect to a VPN the change event never fires. It definitely used to a few weeks ago. I think there have been two releases of Electron (10.1.4 and 10.1.5) since then, but as I said, no version of 10 seems to work when connecting and disconnecting to/from a VPN.

**Comment by nornagon** [comment]
@ahallicks can you compare with the behavior of the same API in Chrome? I'm unsure whether this is an issue with Electron or an issue with the underlying code in Chrome. If the latter, we should report it upstream at crbug.com.

**Comment by ahallicks** [comment]
@nornagon So, I've done some testing this morning and the event never fires for VPN connection/disconnection in Electron, Chrome stable (86.0.4240.111 (Official Build) (64-bit)), and Chrome Canary (88.0.4307.2 (Official Build) canary (64-bit)).

All work fine when switching the connection from, e.g. wifi to ethernet, or disconnecting completely.

**Comment by nornagon** [comment]
Ok. It sounds like this is an issue upstream then. I'll close this for now as the responsibility for this functionality rests with the Chrome team.
