### ISSUE TITLE
use cluster fork worker process, it doesn't work when require electron module

### ISSUE THREAD

**Issue by redabc** [electron/electron#22602]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version: 5.0.14
  * 
* **Operating System: Windows 10
  * 
* **Last Known Working Electron version:**
  * 

### Expected Behavior

 I want to use net module of electron in worker process;

### Actual Behavior

But it doesn't work when I require net module of electron , it return undefined;
### To Reproduce

//main process
const cluster = require('cluster');
cluster.setupMaster({
    exec: `${global.$backend}/subprocess/${scriptType}.js`
});
let worker = cluster.fork();

// worker process
let {net} = require('electron');
// return undefined

**Comment by redabc** [comment]
is there anyone can help me？

**Comment by MarshallOfSound** [comment]
Forking your Electron process results in a `node` process rather than Electron / your app again.  It therefore does not have access to the `electron` module.

You should use `cp.spawn(process.execPath)` if you want to "fork" your process and still have access to Electron

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
