### ISSUE TITLE
webContents.getPrinters not working

### ISSUE THREAD

**Issue by ysun** [electron/electron#22605]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v7.1.7
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * I don't know

### Expected Behavior

List available printers.

### Actual Behavior

```
const remote = electron.remote;
const webContents = remote.getCurrentWebContents();
const printers = webContents.getPrinters();
console.log(printers);  //Actually I have plugged in a printer currenttly.

log:
(10) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
0: {}
1: {}
2: {}
3: {}
4: {}
5: {}
6: {}
7: {}
8: {}
9: {}
length: 10
__proto__: Array(0)

```

**Comment by codebytere** [comment]
Are your drivers and everything hooked into it? A printer being plugged in doesn't necessarily mean they'll show up here. They need to be printers in the system printer list specifically.

**Comment by ysun** [comment]
> Are your drivers and everything hooked into it? A printer being plugged in doesn't necessarily mean they'll show up here. They need to be printers in the system printer list specifically.

Yes, I'm sure the printer works well on my system. I can use printer normally in any other application if it's needed. I'm working on this issue for a while.

**Comment by ysun** [comment]
Any update, or could you reproduce this issue ?

**Comment by codebytere** [comment]
I still can't repro but i'll keep working on it for a bit as best i can.

**Comment by codebytere** [comment]
Closing as no one on the core team could reproduce.
