### ISSUE TITLE
Adding any Object prototype throws an error

### ISSUE THREAD

**Issue by somebeaver** [electron/electron#22615]
* **Electron Version:**
  v8.1.0
* **Operating System:**
  macOS 10.15.3
* **Last Known Working Electron version:**
  N/A

### Expected Behavior
I expect to be able to add an Object prototype without Electron throwing an error.

### Actual Behavior
Electron throws an error on startup, then otherwise seems to work fine.

### To Reproduce
Electron fiddle: https://gist.github.com/d3238b39f2b33493e0d7dbfc4c3b6afe

### Screenshots
A screenshot by another user already exists here (different code than in the Fiddle, though) on this old Stackoverflow Question: https://stackoverflow.com/questions/54179169/object-prototype-break-electron

**Comment by MarshallOfSound** [comment]
ty for the easy repro and well raised issue.  Makes it super easy for us to debug this kind of stuff, fix PR is already up 👍
