### ISSUE TITLE
desktop_capturer screen image quality

### ISSUE THREAD

**Issue by pureZjr** [electron/electron#22627]
hello， i don`t know why i use desktop_capturer get screen image quality is lower than i use the key "print screen" on the keybrord ?

my  display is 3840 x 2160 ，but i get size with getBounds() ，i get the size is 2560 x 1440

my electron version is 7.1.13

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
