### ISSUE TITLE
Is there any way to print the third-party libs that c++ addon dependent backtrack when it crash? 

### ISSUE THREAD

**Issue by oldmtn** [electron/electron#22637]
I have a c++ addon which dependent a thiry-party dll (libtest.a).
When I call the interface of libtest.a, there would have a crash.

Does anyone encought this issue before?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
