### ISSUE TITLE
standard set to true in registerSchemesAsPrivileged breaks navigation

### ISSUE THREAD

**Issue by sentialx** [electron/electron#22634]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.0-beta.6
* **Operating System:**
  * Windows 10, Linux
* **Last Known Working Electron version:**
  * 9.0.0-beta.5

### Expected Behavior
Navigating to google.com after visiting `xd://index/` should work.

### Actual Behavior
Navigating to google.com after visiting `xd://index/` fails with `ERR_FAILED`.

### To Reproduce
https://gist.github.com/sentialx/6c5639751304b2437ce7188413137133

### Additional information
Definitely blocks stable

**Comment by vladimiry** [comment]
@sentialx, you might also want to track the progress of https://github.com/electron/electron/issues/22584 issue (also custom schemes + `registerSchemesAsPrivileged` related issue).

**Comment by vladimiry** [comment]
> Operating System:
    Windows 10

Reproducible on Linux too.

**Comment by sentialx** [comment]
Could also be an issue with Chromium upgrade

**Comment by erickzhao** [comment]
was able to repro on macOS as well

**Comment by sentialx** [comment]
@erickzhao It seems to be working on 9.0.0-beta.14, probably #22867 fixed this.

**Comment by erickzhao** [comment]
Yep, seems to be working again. Will close!
