### ISSUE TITLE
can't set max-http-header-size for js-flags

### ISSUE THREAD

**Issue by liximomo** [electron/electron#22632]
![image](https://user-images.githubusercontent.com/9816225/76307778-6e505980-6304-11ea-9ff7-dbf3199e1140.png)

As the document says, we can get a list of available flags from `node --help`, but this does not work for `--max-http-header-size`.

**Comment by codebytere** [comment]
@liximomo you can use `NODE_OPTIONS` for this: https://github.com/electron/electron/blob/83124889e5dabbc5c67c41d43c5dc9d5b38f921e/docs/api/environment-variables.md#L50

**Comment by liximomo** [comment]
@codebytere The `NODE_OPTIONS` does work, but the doc about `--js-flag` is clearly wrong.
