### ISSUE TITLE
Printing a flash based application inside Electront does not work

### ISSUE THREAD

**Issue by cln650** [electron/electron#22636]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.3
* **Operating System:**
  * Windows 10 (1803)

### Expected Behavior
Printing a page using `win.webContents..print(..)` will print successfully the current page.  

### Actual Behavior
The after selecting the printer the printing process is stuck (Status = Spooling). (See screenshots)

If I load an url directly in the `BrowserWindow` it works fine. 
### To Reproduce
1. Load an `index.html` file that contains an `webview` tag:

```
<body>
<webview id="appView" src="..." plugins nodeintegration></webview>
</body>
```

2. In main process :

```
  globalShortcut.register('CommandOrControl+P', () => {
    win.webContents.print({
      // empty options
    },((success, failureReason) => {
      if (!success) {
        console.log(failureReason);
      }
    }));
  });
```

### Screenshots
![Capture](https://user-images.githubusercontent.com/30065915/76317142-5537b080-62e4-11ea-866e-ba202f7588cf.PNG)

### Additional Information
In `index.html` between `<script>` tags:

```
onload = () => {
      const {shell, ipcRenderer} = require('electron');
      const webview = document.querySelector('webview');

      ipcRenderer.invoke('getConfigUrl', {}).then(url => {
        webview.src = url;
      });

      
 }
```

I also tried `<webview>.print()` and `window.print()` from the renderer process but it doesn't work.
The webview contains a flash-based web app. I'm using Pepper Flash plugin.

**Comment by calinchiper** [comment]
I found that only some content is printable in a flash based application (maybe a flash app developer can help with more information) embedded in electron. I've tested the same app in chrome and I found that there is a similar behavior. Ctrl+P does not invoke the print window in Chrome if the flash content is not "printable". If I click print from the menu it will print a blank page.

**Comment by codebytere** [comment]
Closing as this is an upstream bug - i suggest filing this at crbug.com if you feel strongly about it. When they fix it, it'll roll into us.
