### ISSUE TITLE
macOS code signing broken: crash, outdated documentation, and broken with `com.apple.security.app-sandbox=yes`

### ISSUE THREAD

**Issue by marcj** [electron/electron#22656]
If you setup the repo at https://github.com/electron/electron-quick-start and 

1. `npm install electron-packager --dev`
2. `./node_modules/.bin/electron-packager . MyApp --overwrite`
3. Follow steps at https://www.electronjs.org/docs/tutorial/mac-app-store-submission-guide

you get a lot of error/warnings in the signing script:

```
./MyApp-darwin-x64/MyApp.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework: replacing existing signature
./MyApp-darwin-x64/MyApp.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib: replacing existing signature
./MyApp-darwin-x64/MyApp.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib: No such file or directory
./MyApp-darwin-x64/MyApp.app/Contents/Frameworks/Electron Framework.framework: replacing existing signature
./MyApp-darwin-x64/MyApp.app/Contents/Frameworks/Squirrel.framework/MacOS/Squirrel: No such file or directory
./MyApp-darwin-x64/MyApp.app/Contents/Frameworks/Squirrel.framework/Squirrel: replacing existing signature
./MyApp-darwin-x64/MyApp.app/Contents/Frameworks/ReactiveCocoa.framework/ReactiveCocoa: replacing existing signature
./MyApp-darwin-x64/MyApp.app/Contents/Frameworks/Mantle.framework/Mantle: replacing existing signature
./MyApp-darwin-x64/MyApp.app/Contents/Frameworks/MyApp Helper.app/Contents/MacOS/MyApp Helper: replacing existing signature
./MyApp-darwin-x64/MyApp.app/Contents/Frameworks/MyApp Helper.app/: replacing existing signature
./MyApp-darwin-x64/MyApp.app/Contents/Library/LoginItems/MyApp Login Helper.app/Contents/MacOS/MyApp Login Helper: No such file or directory
./MyApp-darwin-x64/MyApp.app/Contents/Library/LoginItems/MyApp Login Helper.app/: No such file or directory
./MyApp-darwin-x64/MyApp.app/Contents/MacOS/MyApp: code object is not signed at all
In subcomponent: /Users/marc/bude/electron-quick-start/MyApp-darwin-x64/MyApp.app/Contents/Frameworks/MyApp Helper (GPU).app
./MyApp-darwin-x64/MyApp.app: code object is not signed at all
In subcomponent: /Users/marc/bude/electron-quick-start/MyApp-darwin-x64/MyApp.app/Contents/Frameworks/MyApp Helper (GPU).app
```

Those error result in an app not being signed. If you fix them manually by updating the sign script to

```
ARGS="-f "

codesign -s "$APP_KEY" $ARGS --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Electron Framework"
codesign -s "$APP_KEY" $ARGS --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib"
#codesign -s "$APP_KEY" $ARGS --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Libraries/libnode.dylib"
codesign -s "$APP_KEY" $ARGS --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework"

codesign -s "$APP_KEY" $ARGS --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Squirrel.framework/Versions/A/Squirrel"
codesign -s "$APP_KEY" $ARGS --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Squirrel.framework/Squirrel"

codesign -s "$APP_KEY" $ARGS --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/ReactiveCocoa.framework/ReactiveCocoa"
codesign -s "$APP_KEY" $ARGS --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Mantle.framework/Mantle"

codesign -s "$APP_KEY" $ARGS --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper.app/Contents/MacOS/$APP Helper"
codesign -s "$APP_KEY" $ARGS --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper.app/"

codesign -s "$APP_KEY" $ARGS --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (GPU).app/Contents/MacOS/$APP Helper (GPU)"
codesign -s "$APP_KEY" $ARGS --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (GPU).app/"

codesign -s "$APP_KEY" $ARGS --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (Renderer).app/Contents/MacOS/$APP Helper (Renderer)"
codesign -s "$APP_KEY" $ARGS --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (Renderer).app/"

codesign -s "$APP_KEY" $ARGS --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (Plugin).app/Contents/MacOS/$APP Helper (Plugin)"
codesign -s "$APP_KEY" $ARGS --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (Plugin).app/"

#codesign -s "$APP_KEY" $ARGS --entitlements "$LOGINHELPER_PLIST" "$APP_PATH/Contents/Library/LoginItems/$APP Login Helper.app/Contents/MacOS/$APP Login Helper"
#codesign -s "$APP_KEY" $ARGS --entitlements "$LOGINHELPER_PLIST" "$APP_PATH/Contents/Library/LoginItems/$APP Login Helper.app/"

codesign -s "$APP_KEY" $ARGS --entitlements "$CHILD_PLIST" "$APP_PATH/Contents/MacOS/$APP"
codesign -s "$APP_KEY" $ARGS --entitlements "$PARENT_PLIST" "$APP_PATH"
```

 so that the app is actually signed, you get crashes like:

```
$ MyApp-darwin-x64/MyApp.app/Contents/MacOS/MyApp
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
[61656:0312/004144.475423:FATAL:gpu_data_manager_impl_private.cc(1034)] The display compositor is frequently crashing. Goodbye.
[1]    61656 trace trap  
```

If you use additionally now `MyApp.app/Contents/MacOS/MyApp --no-sandbox` then it works, but you don't have the sandbox anymore.

---

Apple requires you meanwhile to use the [hardened runtime](https://developer.apple.com/documentation/security/hardened_runtime) to publish your app in the App Store. To do this, you need `codesign --timestamp -o runtime`. When I add to my script above 

```
ARGS="-f --timestamp -o runtime"
```

sign again and starting, it shows a new crash:

```
MyApp-darwin-x64/MyApp.app/Contents/MacOS/MyApp                           
[1]    63379 killed
```

That's fine but undocumented, since the hardened runtime requires a couple of additional entitlements. So I add following entitlements to the `parent.plist`:

```
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.app-sandbox</key><true/>

    <key>com.apple.security.cs.disable-library-validation</key><true/>

    <key>com.apple.security.cs.allow-jit</key><true/>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key><true/>
    <key>com.apple.security.cs.disable-executable-page-protection</key><true/>
    <key>com.apple.security.cs.disable-library-validation</key><true/>
  </dict>
</plist>
```

after singing and starting again I see the electron window for a second after 5s boot time, then crash:

```
MyApp-darwin-x64/MyApp.app/Contents/MacOS/MyApp
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397

#
# Fatal process OOM in CodeRange setup: allocate virtual memory
#


#
# Fatal process OOM in CodeRange setup: allocate virtual memory
#

[64724:0312/005709.516968:FATAL:gpu_data_manager_impl_private.cc(1034)] The display compositor is frequently crashing. Goodbye.
[1]    64724 trace trap
```

So I add `--no-sandbox` again:

```
MyApp-darwin-x64/MyApp.app/Contents/MacOS/MyApp --no-sandbox
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397

#
# Fatal process OOM in CodeRange setup: allocate virtual memory
#


#
# Fatal process OOM in CodeRange setup: allocate virtual memory
#
```

Same output, but without crash and instead just an empty window:

![Screenshot 2020-03-12 at 00 58 12](https://user-images.githubusercontent.com/450980/76474620-8d321700-63fc-11ea-9167-f5d4f8f6d441.png)

I tried with electron-builder as well. I used

```
    "mac": {
      "category": "public.app-category.developer-tools",
      "hardenedRuntime": true,
      "gatekeeperAssess": false,
      "entitlements": "parent.plist"
    },
```

Everything works fine until I add `<key>com.apple.security.app-sandbox</key><true/>` in the `parent.plist`, like so:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.app-sandbox</key><true/>

    <key>com.apple.security.cs.allow-jit</key><true/>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key><true/>
    <key>com.apple.security.cs.disable-executable-page-protection</key><true/>
    <key>com.apple.security.cs.disable-library-validation</key><true/>
  </dict>
</plist>
```

```
$ ./node_modules/.bin/electron-builder --dir
  • electron-builder  version=22.4.1 os=19.2.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=darwin arch=x64 electron=8.1.1 appOutDir=dist/mac
  • do not use "your.id" as appId, "com.electron.electron-quick-start" will be used instead
  • default Electron icon is used  reason=application icon is not set
  • do not use "your.id" as appId, "com.electron.electron-quick-start" will be used instead
  • signing         file=dist/mac/electron-quick-start.app identityName=Developer ID Application: asdasas identityHash=asdadasd provisioningProfile=none


```

```
$ dist/mac/MyApp.app/Contents/MacOS/MyApp
[1]    73109 killed 
```

--- 

My system:

```
macOS catalina: 10.15.2
node: v12.14.1
electron: 8.1.1
```

So to summary: As soon as I use `com.apple.security.app-sandbox` + hardening signation the app crashes, no matter what I do. The important part is here that Apple requires you to have both hardened runtime and app-sandbox activated to distribute an app through the Mac App Store. So it's currently not possible to distribute electron apps via the Mac App Store, at least not in the way its documented. //edit, the last sentence is probably not true, since you don't need yet a hardened runtime for the App Store, only for notarization. However, that means you can't have apps that are notarized + sandboxed at the same time.

**Comment by marcj** [comment]
I tried removing `<key>com.apple.security.cs.allow-unsigned-executable-memory</key><true/>` in the electron-build variant and was able to get a short window to see instead of instant `killed`. However, still an error.

```
dist/mac/electron-quick-start.app/Contents/MacOS/electron-quick-start
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
[80474:0312/021330.650520:FATAL:gpu_data_manager_impl_private.cc(1034)] The display compositor is frequently crashing. Goodbye.
[1]    80474 trace trap
```

**Comment by marcj** [comment]
Related to https://github.com/electron/electron-osx-sign/issues/200.

My crash report:
```
Process:               electron-quick-start [7347]
Path:                  /Users/USER/*/electron-quick-start.app/Contents/MacOS/electron-quick-start
Identifier:            com.electron.electron-quick-start
Version:               1.0.0 (1.0.0)
Code Type:             X86-64 (Native)
Parent Process:        zsh [4519]
Responsible:           iTerm2 [3354]
User ID:               501

Date/Time:             2020-03-12 03:08:20.266 +0100
OS Version:            Mac OS X 10.15.3 (19D76)
Report Version:        12
Bridge OS Version:     4.2 (17P3050)
Anonymous UUID:        4C4249CD-A3A1-1305-2E40-0B5604DDCD2C


Time Awake Since Boot: 1000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (Code Signature Invalid)
Exception Codes:       0x0000000000000032, 0x000009936e9c2040
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x2
```

**Comment by semireg** [comment]
The sad thing about this whole complex situation is that, even though I have a sandboxed app published on MAS, and I have the same app, non-sandboxed w/ hardened runtime being distributed via my app's website... I still don't feel I quality as an expert because I can't explain the intricacies of all the dependencies, both technical, logical and ever-changing. What I write today might not be correct a month from now. But I will offer these small pieces of advice:

MAS:
• hardened runtime is not required.
• sandboxing is required

DIY Distribution:
• notarization is (for all intent and purpose) required
• notarization requires hardened runtime
• sandboxing is not required

**Comment by ronghester** [comment]
I am able to generate a notarized DMG without "app-sandboxed security" flag. We are also able to distribute it to other users and it works! Now we wants to upload the app to mac store. We tried everything but the moment we add "app-sandboxed security" flag into the entitlement and turn on the signing the application crashes on start. If we specify MAS setting and disable CSC_IDENTITY_AUTO_DISCOVERY then codesigning required for uploading the app to mac store does not work (error: code object is not signed at all).   Anyways after struggling for few days; when i saw this open issue; i could not be more convinced that this is certainly a issue with electron.

**Comment by marcj** [comment]
Yeah, it only works either 

1. app-sandbox disable with notarization (required hardened-runtime)
2. app-sandbox enabled and mapp app store (no hardened-runtime and no notarization required)

So, it works to get stuff in the app store and to distribute apps. But hardened-runtime + app-sandbox at the same time doesn't work, and also not (yet) required by Apple.

**Comment by MarshallOfSound** [comment]
Hardened runtime and app sandbox are mutually exclusive, you can't and shouldn't use them both at the same time.  From the sound of your latest comment you have this working for both MAS distribution and DDL distribution.

To be clear to anyone finding this issue, do not notarize/harden your MAS build, it will not work

Closing this out as the previous comment indicates everything is fine

**Comment by marcj** [comment]
To be clear:

> you can't and shouldn't use them both at the same time

This is a personal statement by @MarshallOfSound and does not reflect any information or recommendation by Apple. It seems an issue with Electron only, as using sandbox + hardened  runtime works for xcode projects fine.

Still, the documentation about that fact is far from optimal. A lot of people seem to have issues getting their app deployed because of that inconsistency and outdated documentation.

**Comment by MarshallOfSound** [comment]
Where does apple recomend you notarize and sandbox a Mac app store application?

**Comment by marcj** [comment]
You said it like its official and well known fact that both shouldn't be used at the same time in general. Which is not true and you don't find any information about that from Apple. Quite the contrary: Each on its own is recommended by Apple. If they wouldn't work together, you would find an information about that in the official documentation. And you wouldn't be able to use both in XCode. You can indeed use both at the same time just fine for anything not Electron related. Only in Electron does it not work.

Requiring an official statement from Apple that should exactly say that both at the same time is recommended is an odd way to justify claims that it's mutually exclusive and "can not" and "should not" be used. That mutually exclusive thing is plain wrong, considering the fact that its works perfectly fine outside of the electron world. At the very best you could say that your claims are only related to electron.

**Comment by ronghester** [comment]
> Yeah, it only works either
> 
> 1. app-sandbox disabled with notarization (required hardened-runtime)
> 2. app-sandbox enabled and mac app store (no hardened-runtime and no notarization required)
> 
> So, it works to get stuff in the app store and to distribute apps. But hardened-runtime + app-sandbox at the same time doesn't work, and also not (yet) required by Apple.

I agree with #1 it works. But #2 does not work. Once you enabled the app-sandbox then app crashes; If app-sandbox is enabled & signing is disabled (CSC_IDENTITY_AUTO_DISCOVERY = false) then only app works but then you can submit it to app store since the app is not signed. I also tried a manual alternative that is generate *.app without code signing and then using the signing script (attached below) but that also fails since it requires some portion of *.app to be signed already.  So currently we can't submit apps to mac app store. 

[scriptforgit.txt](https://github.com/electron/electron/files/4368392/scriptforgit.txt)

**Comment by ahmadwaliesipick** [comment]
> > Yeah, it only works either
> > 
> > 1. app-sandbox disabled with notarization (required hardened-runtime)
> > 2. app-sandbox enabled and mac app store (no hardened-runtime and no notarization required)
> > 
> > So, it works to get stuff in the app store and to distribute apps. But hardened-runtime + app-sandbox at the same time doesn't work, and also not (yet) required by Apple.
> 
> I agree with #1 it works. But #2 does not work and yes "hardenedRuntime" is false. Once you enabled the app-sandbox the app crashes; If app-sandbox is enabled & signing is disabled (CSC_IDENTITY_AUTO_DISCOVERY = false) then only app works but then you can't submit it to app store since the app is not signed. I also tried a manual alternative that is generate *.app without code signing and then using the signing script (attached below) to sign *.app and generating package but that also fails since it requires some portion of *.app to be signed already. So currently we can't submit apps to mac app store.
> 
> [scriptforgit.txt](https://github.com/electron/electron/files/4368392/scriptforgit.txt)

i am also using same script (https://www.electronjs.org/docs/tutorial/mac-app-store-submission-guide) after signing app once i open the app became crash the reason is;
`[30627:0413/134622.560420:FATAL:gpu_data_manager_impl_private.cc(892)] The display compositor is frequently crashing. Goodbye.`

@ronghester  do you have any solution?

**Comment by salomvary** [comment]
I came here to figure out why an app built for App Store distribution is crashing with "The display compositor is frequently crashing." Following the advice here, I tried going the "app-sandbox enabled and mac app store (no hardened-runtime and no notarization required)" path, which would meet my needs.

Sadly, even with hardened runtime disabled, I am getting the same error on Catalina 10.15.3:

```
% electron-hello-world.app/Contents/MacOS/electron-hello-world
Operating system platform:  darwin
Operating system version:  19.3.0
Electron version:  8.2.5
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
[84651:0514/124608.298301:FATAL:gpu_data_manager_impl_private.cc(1034)] The display compositor is frequently crashing. Goodbye.

% codesign -d -vvv electron-hello-world.app                
Executable=electron-hello-world.app/Contents/MacOS/electron-hello-world
Identifier=com.electron.bug
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=1712 flags=0x0(none) hashes=46+5 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha1=5e73326fb25e1ee93e965a2e38a7d1160a529d42
CandidateCDHashFull sha1=5e73326fb25e1ee93e965a2e38a7d1160a529d42
CandidateCDHash sha256=c97db4bed8ae9105cdf20f703a57ef829c9c0ee7
CandidateCDHashFull sha256=c97db4bed8ae9105cdf20f703a57ef829c9c0ee721b53e7e460b0e4b1f259744
Hash choices=sha1,sha256
CMSDigest=af0839f862db3d684f6d3f8a61c67f8013df75b524a35cebbcffa21eb58e301a
CMSDigestType=2
CDHash=c97db4bed8ae9105cdf20f703a57ef829c9c0ee7
Signature size=9091
Authority=Mac Developer: Marton Salomvary (<removed>)
Authority=Apple Worldwide Developer Relations Certification Authority
Authority=Apple Root CA
Timestamp=14. May 2020 at 12:43:56
Info.plist entries=28
TeamIdentifier=<removed>
Sealed Resources version=2 rules=13 files=8
Internal requirements count=1 size=176
```

Using latest Electron, build using latest Electron Builder. The [app source is available here](https://github.com/salomvary/electron-bugs/tree/catalina-build).

**Comment by zenghongtu** [comment]
@salomvary  

I fix it by remove this:

```
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
```

**Comment by TonyWuu** [comment]
Thanks @zenghongtu, removing that entitlement fixed the `The display compositor is frequently crashing` issue for me on High Sierra, but now on Catalina I run into `# Fatal process OOM in CodeRange setup: allocate virtual memory`. Did anyone else run into the same issue? Adding the entitlement back removes the OOM error, but of course brings back the crashing compositor issue...

**Comment by luotyzl** [comment]
Hey I got this error after code sign for distribution MAS, 
```
Application Specific Information:
dyld: launch, running initializers
/usr/lib/libSystem.B.dylib
Process is not in an inherited sandbox.

Application Specific Signatures:
Process is not in an inherited sandbox.
```
Anyone has same issue?
