### ISSUE TITLE
How to intercept the request  and modify the uploadData

### ISSUE THREAD

**Issue by xgj1988** [electron/electron#22654]
I wan't to modfify some  post requests . How can I do it ,I use the webRequest.onBeforeRequest AND  protocal.interceptBufferProtocol .But They doesn't take effect .I see the api docs .but the docs doesn't exists example about the question. 
anybody can help me .thanks a lot.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
