### ISSUE TITLE
getCursorScreenPoint bug

### ISSUE THREAD

**Issue by pureZjr** [electron/electron#22659]
My mac monitor size is 1440 x 900
My External monitor size is 2560 x 1440

when i have no External monitor，i use screen.getCursorScreenPoint() get my mouse point is 
{ x:  30 , y: 47 }

when i have External monitor，i get my mouse point is {x: 1470 , y: -330 }

i think that the point X can use 1470 - 1440 = 30, but the point Y  i have no idea how to calculate。

**Comment by MarshallOfSound** [comment]
@pureZjr The `x` and `y` coords are based on a coordinates system who's origin depends on the layout and configuration of your monitors.  You shouldn't be trying to translate these coordinates like this, they are already in the correct coordinates system.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
