### ISSUE TITLE
Main window has frame when app starting 

### ISSUE THREAD

**Issue by JMorillasGreen** [electron/electron#22650]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
8.1.1
* **Operating System:**
Windows 10 1909 (18363.719)
* **Last Known Working Electron version:**
I haven't tested nor worked with older versions of electron.

### Expected Behavior
The app should never show the native frame.
### Actual Behavior
The app shows the frame for a second or two, when starting app, then disappears leaving the window design as expected, without native frame.

### To Reproduce
```
const { app, BrowserWindow } = require('electron');

function createWindow () {
  let win = new BrowserWindow({
    width: 1000,
    height: 800,
    frame: false,
    resizable: false,
    hasShadow: false,
    webPreferences: {
      nodeIntegration: true
    }
  });
  win.setMenuBarVisibility(null);
  win.loadFile('./public/views/index.html');
};

app.whenReady().then(createWindow);
```

I will add a repository soon, but the code should work perfectly to show what I mean.

### Screenshots
When starting the app:
https://imgur.com/a/tb5P5tJ

When the app is already finished starting:
https://i.imgur.com/CCyWEcO.png

### Additional Information
This happens every single time I start the app. It's not just the first time and then always loads correctly. And this is not packaged, so it will probably happen in packaged version too.

**Comment by MarshallOfSound** [comment]
Is this windows 10 or windows server?

**Comment by JMorillasGreen** [comment]
Ups, I thought I wrote it correctly, but it's **Windows 10 1909 (18363.719)** updated with the latest Windows update as of today.

**Comment by MarshallOfSound** [comment]
@JMorillasGreen Can you set `show: false` on the window and then do

```
win.on('ready-to-show', () => win.show())
```

**Comment by JMorillasGreen** [comment]
> @JMorillasGreen Can you set `show: false` on the window and then do
> 
> ```
> win.on('ready-to-show', () => win.show())
> ```

Okay, that did solve the problem! Thank you very much for your help.

**Comment by MarshallOfSound** [comment]
Closing out as the feature designed for this kind of issue worked 👍
