### ISSUE TITLE
How to make license file to electron app setup

### ISSUE THREAD

**Issue by velnandha27** [electron/electron#22662]
where it placed a license file and how to call that file in  my package.json

and how to build electron app securely

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
