### ISSUE TITLE
When the app is updated while running

### ISSUE THREAD

**Issue by seunghwanbae** [electron/electron#22663]
**Electron Version: 8.0.1**

If the MAS app is updated in the background with the app running, or if the pkg is installed.
The app has not been restarted and has not been bringing updated files.

Can I detect when I install pkg or update MAS automatically?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
