### ISSUE TITLE
gclient electron@6.1.5 failed with error Not a valid object name 76.0.3809.146

### ISSUE THREAD

**Issue by hxkuc** [electron/electron#22660]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * electron6.1.5

* **Operating System:**
  * windows7

* **Last Known Working Electron version:**
  * no

### Expected Behavior

build success
### Actual Behavior

I used the following code to build electron
1. download depot_tools
2. `gclient`
![image](https://user-images.githubusercontent.com/17510186/76483254-7bc72a00-6451-11ea-9a20-6697230ad684.png)
![image](https://user-images.githubusercontent.com/17510186/76483301-a0230680-6451-11ea-8d4b-1401df72107b.png)
![image](https://user-images.githubusercontent.com/17510186/76483333-b5983080-6451-11ea-9d0a-32faefa58de2.png)
3. `set GIT_CACHE_PATH=E:\electron-cache\.git_cache`
4. 
```
`mkdir electron-gn && cd electron-gn `
`mkdir code && cd code `
gclient config --name "src/electron" --unmanaged https://github.com/electron/electron@v6.1.5
gclient sync --with_branch_heads --with_tags
```
5. 
Tried many times `gclient sync --with_branch_heads --with_tags`

![image](https://user-images.githubusercontent.com/17510186/76483690-a06fd180-6452-11ea-8ba8-c55edbc23456.png)
![image](https://user-images.githubusercontent.com/17510186/76483722-b8475580-6452-11ea-9dc4-78e4ab681e4f.png)
![image](https://user-images.githubusercontent.com/17510186/76484871-ebd7af00-6455-11ea-8d1d-cdfbaf4029c8.png)
![image](https://user-images.githubusercontent.com/17510186/76484953-0f9af500-6456-11ea-8120-83ca02b4ea28.png)

and the folder size
![image](https://user-images.githubusercontent.com/17510186/76483892-31df4380-6453-11ea-8f4a-8abbdfb620f3.png)

I want to know which step is wrong
how can i download the code

**Comment by hxkuc** [comment]
now
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by codebytere** [comment]
Please use https://github.com/electron/build-tools - that should sort the issue.
