### ISSUE TITLE
How do i hide the tooltip after calling win.setSize ?

### ISSUE THREAD

**Issue by 26903651** [electron/electron#22687]
![image](https://user-images.githubusercontent.com/16937789/76674511-422a2680-65eb-11ea-9056-83343c486c02.png)
![image](https://user-images.githubusercontent.com/16937789/76674521-51a96f80-65eb-11ea-85a8-c77e1dfb63db.png)

**Comment by 26903651** [comment]
how do i hide the "432px * 432px" on the top right?

**Comment by ahallicks** [comment]
This is part of devtools. If you don't have devtools open and resize the app this won't show:

https://stackoverflow.com/questions/35931064/how-do-i-get-the-screen-size-to-show-when-chrome-console-is-open

**Comment by 26903651** [comment]
thanks
