### ISSUE TITLE
top full screen display

### ISSUE THREAD

**Issue by ashitamo** [electron/electron#22685]
we know discord have a "game activity"and,
it can display on fullscreen game(like rainbow6).
i known discord made of Electron,
how do window display on fullscreen program

(i know my english so bad)

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
