### ISSUE TITLE
 display no full screen

### ISSUE THREAD

**Issue by lichaomeng** [electron/electron#22699]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.
 display no full screen

### Issue Details

centos7:  Linux localhost.localdomain 3.10.0-1062.9.1.el7.x86_64
	     CentOS Linux release 7.7.1908

Electron version: 7.1.9

### Actual Behavior

display no full screen

### To Reproduce

![76609290-1b6be180-6552-11ea-8a19-7d488749161c](https://user-images.githubusercontent.com/25163978/76722081-23f43000-677d-11ea-871e-323671424ade.png)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

**Comment by codebytere** [comment]
Closing due to no response.
