### ISSUE TITLE
How to hide the Windows menu?

### ISSUE THREAD

**Issue by dragonmenorka** [electron/electron#22693]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

My problem is I want to hide this menu:
![Captura](https://user-images.githubusercontent.com/46191980/76701411-3741c580-66c1-11ea-9ce2-5d09d225debd.PNG)

### Proposed Solution

????

**Comment by ahallicks** [comment]
See https://www.electronjs.org/docs/api/frameless-window. You need to create a frameless window.

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
