### ISSUE TITLE
top display on full screen program 2

### ISSUE THREAD

**Issue by ashitamo** [electron/electron#22690]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

we know discord have a "game activity"and,
it can display on fullscreen game(like rainbow6).
i known discord made of Electron,

(i know my english so bad)
### Proposed Solution

how do window display on fullscreen program

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
