### ISSUE TITLE
ZoomFactor does not work for Child Windows

### ISSUE THREAD

**Issue by abettadapur** [electron/electron#22711]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version: 8.0.2**
* **Operating System: Windows 10 and MacOS, multiple versions**

The `zoomFactor` property seems to have zero effect on child windows opened with `window.open`

I have tried this in two ways, that both do not work

1. Setting `zoomFactor` in the `webPreferences` of the BrowserWindow constructor that is called on the `new-window` event
2. Calling `window.webContents.setZoomFactor`

Both of these methods work on the parent window

### Expected Behavior
`setZoomFactor` should set the zoom factor of a child window

### Actual Behavior
The child window is locked at a zoom factor of 1

### Gist
This electron-fiddle reproduces the problem
https://gist.github.com/fa561a1b2aac2c1a97d383b368c0ad35
![zoom-factor](https://user-images.githubusercontent.com/2415669/76810828-a9db9f80-67ac-11ea-8f8a-9f2f7412c6a3.gif)

**Comment by codebytere** [comment]
@abettadapur - this is not in fact a bug; you're loading an empty string and not an actual url, so Chrome doesn't know what to do. If you go to Chrome itself and replicate this you'll see the same behavior. Once that's fixed you'll see that the child and parent windows _both_ zoom when you zoom the parent, which is also expected, because they have the same origin.

**Comment by abettadapur** [comment]
@codebytere Thanks for your response

I am loading an empty URL because I then write content from the main window to the child window synchronously. Is there any way to still accomplish that? Loading a URL overwrites whatever content I write to the child DOM

**Comment by abettadapur** [comment]
![image](https://user-images.githubusercontent.com/2415669/77004640-a8c98000-691c-11ea-8d10-412cedb63dbe.png)
This still seems like a bug, maybe in the Chrome engine? Should the child window not inherit the zoom, because it exists in the parent browsing context?

**Comment by abettadapur** [comment]
Using `about:blank` instead of '' fixes the issue

Thanks for your reply!
