### ISSUE TITLE
badgeCount doesn't trigger notification permission

### ISSUE THREAD

**Issue by tidg** [electron/electron#22715]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.3
* **Operating System:**
  * macOS Catalina 10.15.3

### Expected Behavior
I would like to see the notification authorization popup appear when the badge counter is used and no permission has been set.

### Actual Behavior
When I use the badgeCount property, the badge does not appear because no permission requests on notifications are displayed.
I need to do a new Notification in order to allow notifications and see the badge.

### To Reproduce
Just use the badgeCount property before authorizing notifications.

**Comment by MarshallOfSound** [comment]
This notification is a one-off thing that is **automatically** done by Catalina.  Unfortunately if you miss it the first time there is no way for the app to show it again, you have to go into System Preferences and manually enable it for the app.

**Comment by codebytere** [comment]
Closing in agreement with the above.

**Comment by tidg** [comment]
Thank you for your feedback,
I understand that this point is mostly related to Mac OSX.
However, could you maybe run a notification request when the badgeCount property is used?
For your information, I have not declined any notification request because no request has been proposed to me.

**Comment by knubie** [comment]
@MarshallOfSound @codebytere I think you've missed the point of the OP. Setting the badgeCount should request notification permissions (in the same way that creating a new notification does). Currently it fails silently, even if the permission is still "default" (ie. notification permissions were never requested, consequently the user can't enable them in system preferences).

I think it would also be helpful to document this requirement in the `setBadgeCount` docs, as well as adding a way to request notification permissions from the main process without creating a new notification (in the case we don't want `setBadgeCount` to automatically request notification permission).
