### ISSUE TITLE
webview's DOM operations do not happen when the webview is out of the viewport

### ISSUE THREAD

**Issue by praneetrohida** [electron/electron#22720]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.1.1 / 7.x.x
* **Operating System:**
  * macOS  / Windows 10  

### Expected Behavior
Whenever a webview is loaded but not inside the viewport, DOM operations triggered inside the webview should work as expected.
We have a list of webviews in a scrollable container. The DOM operation we are performing is `window.scrollTo()`. The operation is triggered using IPC set up in the preload script.

### Actual Behavior
The IPC event is received immediately by all the webivews, but DOM operations performed in the handler do not get executed for the webviews that are out of the viewport. They all are executed together when those webviews are brought into the viewport.

### Additional Information
I noticed the same thing happening with `webview.capturePage()`
The promise returned by the `capturePage()` function does not resolve until the webview is brought into the viewport by scrolling down.

**Comment by codebytere** [comment]
@praneetrohida do you know in what version this last worked as you expected? In addition, could you please provide a small self-contained example of the issue, ideally via [fiddle](https://www.electronjs.org/fiddle)?

**Comment by praneetrohida** [comment]
@codebytere The last version that is worked for me as expected was 5.0.13
Here is a minimal reproduction of the issue https://github.com/praneetrohida/electron-webview-dom-events-issue

Notice that when clicked on the Scroll to end button, only the first webview scrolls initially. The rest of the webviews scroll when the viewport is scrolled and they are brought into the viewport

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by kitze** [comment]
@praneetrohida I think that it's still reproducible, so let's report it again

**Comment by praneetrohida** [comment]
@kitze yes, I'll update the example repo with the latest version of Electron and report it again
