### ISSUE TITLE
Native OS file drag and drop causes crash

### ISSUE THREAD

**Issue by capc0** [electron/electron#22721]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  v8.1.1

* **Operating System:**
  *  Win 10

* **Last Known Working Electron version:**
  * ^7.1.3

### Expected Behavior

file drag and drop out of electron into windows file explorer should work

### Actual Behavior

the app crashes instantly, with no error message displayed (Exit status 3221225477)

### To Reproduce

https://www.electronjs.org/docs/tutorial/native-file-drag-drop

**Comment by capc0** [comment]
edit: only seems to happen when the icon property is set to 'null'

**Comment by codebytere** [comment]
@capc0 can you please provide a more specific repro? I ran the following [repro](https://gist.github.com/bcd19399c6533f7de691c601936ed10e) and saw the expected error when `icon` was null:

<img width="532" alt="Screen Shot 2020-03-17 at 5 35 30 PM" src="https://user-images.githubusercontent.com/2036040/76913940-bc6ddb80-6875-11ea-80f4-3d0fd95afc65.png">

**Comment by capc0** [comment]
@codebytere I am pretty sure it only crashes on Windows. The docs always said that the icon must be non null on mac systems (https://www.electronjs.org/docs/api/web-contents#contentsstartdragitem). 

I just ran your fiddle and it crashes as i was dragging the item into my file explorer.


`$ electron main.js                                                                                                                                                (electron) The default value of app.allowRendererProcessReuse is deprecated, it  is currently "false".  It will change to be "true" in Electron 9.  For more info rmation please check https://github.com/electron/electron/issues/18397           /c/Users/Simon/AppData/Roaming/npm/electron: line 14:  9556 Segmentation fault       node "$basedir/node_modules/electron/cli.js" "$@"`

thank you

**Comment by capc0** [comment]
can someone remove the ```blocked/need-repo``` label please?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by jan-nick** [comment]
I was trying to implement this feature and it always crashed when dropping the file and was already doubting major life decisions that led me to become a developer and then noticed that I didn't add event.preventDefault() 😢 🤣
