### ISSUE TITLE
Undo/Redo has no effect inside <webview>

### ISSUE THREAD

**Issue by adityamudgil2505** [electron/electron#22744]
Calling Cmd+Z (webContents.undo()) and Shift+Cmd+Z (webContents.redo()) have no effect inside a <webview> tag

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * Electron v8.1.1
* **Operating System:**
  * macOS 10.15

### Expected Behavior
Calling Cmd+Z (webContents.undo()) and Shift+Cmd+Z (webContents.redo()) inside a <webview> tag will do the functionality that are defined for them i.e, undo and redo. Also by calling them from menu bar inside edit.

### Actual Behavior
Calling undo and redo inside <webview> has no effect. It gives no response. I remains unchanged after calling undo/redo it.

### To Reproduce
I use Electron fiddler to reproduce this issue and the gist link is https://gist.github.com/958fea4350204faf6778121b97af90f7
(no effect of undo and redo inside google search bar)

### Screenshots
![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/25535045/76966288-bea26980-694b-11ea-84ed-215097205276.gif)

**Comment by andersk** [comment]
This Gist has working undo/redo for me on both Windows and Linux (via both menu entry and keyboard shortcut), so this must be a macOS specific bug.

**Comment by codebytere** [comment]
@andersk some preliminary digging tells me the functionality isn't totally broken: if you run [this gist](https://gist.github.com/a28818a2355047854908e7f6c87529d2) you'll see that undo and redo work correctly on button click. I thus suspect it's a menu or shortcut issue; i'll look a bit more.

**Comment by pyrocto** [comment]
This makes editing comments very annoying in the mac Zulip desktop app, so those of us who use it are very interested in getting this fixed.
