### ISSUE TITLE
Allow for global configuration support on macOS

### ISSUE THREAD

**Issue by grahampugh** [electron/electron#22769]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

When managing a fleet of computers, it is important to be able to apply settings that apply to every user on a computer. However, Electron apps do not have this ability (see https://www.electronjs.org/docs/api/app#appgetpathname), meaning that hit-and-miss engineering has to be carried out by any Mac administrator attempting to make their users' lives easier. The example I'm currently working on is applying the company URL as the default connection in the Riot.im application.

### Proposed Solution

Settings should be able to be supplied in `/Library/Application Support/Riot/config.json`. These should override any settings in `~/Library/Application Support/Riot/config.json`.

### Alternatives Considered

Any alternative requires local engineering by administrators so is not scalable.

### Additional Information

Most Mac apps have the ability to set configurations in a Configuration Profile. This should be considered as the next step beyond may suggestion, if developers want Electron apps to be properly managed in the enterprise.

**Comment by MarshallOfSound** [comment]
This is a per-app decision on how to handle this kind of use case.  `config.json` is specific to Riot in this case.

**Comment by grahampugh** [comment]
Are you saying that it is possible to set global settings? I ask because when I raised an issue with Riot, they said that it was not. They quoted https://www.electronjs.org/docs/api/app#appgetpathname when saying this.
