### ISSUE TITLE
Error when command line arguments include colons and options

### ISSUE THREAD

**Issue by noteon** [electron/electron#22781]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  8.1.1
* **Operating System:**
  *  Windows 10 (1809)
* **Last Known Working Electron version:**
  * 

### Expected Behavior

Be able to print out process.argv successfully

### Actual Behavior

The electron program exited directly, neither printing out the process.argv, nor reporting any errors.

### To Reproduce

Clone the following repo and run.

```sh
$ git clone https://github.com/noteon/electron-quick-start -b master
$ npm install
$ electron . localhost:8000 --db=test || npm run cli
```

**Comment by codebytere** [comment]
@noteon this is because we reject anything that looks like a URI in the argv - this will work if you encode or escape `localhost:8000`.

**Comment by noteon** [comment]
@codebytere  Thank you for your feedback.

-  "electron . -- localhost:8000" can print process. argv correctly, but "electron . -- localhost:8000  --db" failed. The latter has only one more option switch.
-  Is there any intercept point that allows me to deal with the process.argv before rejecting it?
- The command-line argument is entered by the end-user, encode or escape is not appropriate
