### ISSUE TITLE
Cursor blocked after setBounds on frameless window

### ISSUE THREAD

**Issue by johnryan** [electron/electron#22780]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.1.1
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron version:**
  * n/a

### Background
It seems that when resizing a frameless window *with* a BrowserView inside it to a sufficiently narrow width there is an area created at the top of the window that blocks all touches and makes the window draggable (even if the window has movable = false)

### Expected Behavior
- Calling setBounds should allow the window to resize without disrupting the functionality of the BrowserView

### Actual Behavior
Approximately 25% of the window at the top stops accepting input and becomes a drag region

### To Reproduce
**Electron Fiddle:** https://gist.github.com/f80bfd413b7211c31e2feeb0608cafc8

### Screenshots
![ezgif-7-09195467100b](https://user-images.githubusercontent.com/416564/77129173-62157c00-6a29-11ea-9ca4-9bcf79cd3fab.gif)

**Comment by praneetrohida** [comment]
Same thing happens for me on 9.1.0. I have a BrowserView inside a non-frameless window. The bounds of the BrowserView are calculated dynamically and at a certain point the BrowserView stops accepting the mouse input and becomes a drag region
