### ISSUE TITLE
DesktopCapturer hide specific items and applications while screen sharing

### ISSUE THREAD

**Issue by masudhossain** [electron/electron#22795]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

When screen sharing, it shows everything. Even the window from the electron app when starting the share. 

### Proposed Solution

When sharing a screen, include a way to hide specific applications, elements, or items. Similar to how zoom does it for their screen sharing. 

### Alternatives Considered

Sharing only application is okay, but there's many bugs that happens when you do this. And it'll require users to redo their screensharing application if they decide to switch between apps.

**Comment by wangfpp** [comment]
how to hide local applocation

**Comment by MarshallOfSound** [comment]
This is possible now per: https://github.com/electron/electron/issues/19880#issuecomment-1139115348

Ref: https://github.com/electron/electron/pull/34362
