### ISSUE TITLE
Open source lib for Node.js bindings to Apple notification libraries

### ISSUE THREAD

**Issue by ORESoftware** [electron/electron#22794]
I realize that Electron might only do in-app notifications (not system notifications on Mac machines). But I am looking for Node.js bindings to the C / objective-C libraries that Apple uses to display notifications on a Macbook Pro etc.

https://developer.apple.com/documentation/usernotifications/

the above link shows how to use Objective C or Swift to display notifications, but am looking to either call that from a child process or from Node.js.

**Comment by MarshallOfSound** [comment]
@ORESoftware Electrons `Notification` API is literally system notifications for every platform.  Backed by `NSUserNotification` on macOS.

https://www.electronjs.org/docs/api/notification

**Comment by ORESoftware** [comment]
is that library open-sourced, because I want to use it
