### ISSUE TITLE
Zenerdiode

### ISSUE THREAD

**Issue by GentleRV** [electron/electron#22793]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 12.0.2 64Bit
* **Operating System:**
  * Windos 8.1 x64
* **Last Known Working Electron version:**
  *  Can't find in the menue structure but is latest version

### Expected Behavior
I select to place a part called Zenerdiode

### Actual Behavior
I see the zenerdiode as well defined object being placed.
Then can select only zenerdiode-default without any value to fill-in
Or standard (Schottky) diodes, which are not Zenerdiodes

### To Reproduce
Just select the zener diode with the small letter z. Then look at the properties. For the default-zener diode a voltage value has to be set on which treshold this diode will start to work
This threshold is not present

**Comment by nornagon** [comment]
I think you have the wrong project. This is [Electron](https://electronjs.org), a framework for building desktop apps with web technologies.
