### ISSUE TITLE
Electron failed to load c++ symbols when using node addon with napi and cmake

### ISSUE THREAD

**Issue by forif** [electron/electron#22799]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  
  * tested on latest v10.0.0-nightly.20200317 / v9.0.0-beta.9 / v8.1.1
* **Operating System:**
  
  * Windows 10 (1909)
* **Last Known Working Electron version:**
  
  * not known.
* **Node version the c++ addon(N-api) build against:**
  * v12.16.1
* **MSVC version to build the addon:**
  * Visual Studio 2019 with v140 compiler(VS 2015). Tried v142, too.

### Expected Behavior

The C++ addon(using N-api) loaded by electron should work properly.

### Actual Behavior

Crash when c++ addon using some c++ std objects(e.g. std::stringstream). VS debugger shows it is crashed on the RaiseException line in MSVC's delayhlp.cpp since the c++ symbols cannot be found(the pfnRet remains NULL after the last resort in __delayLoadHelper2 function).
BTW. using node.exe instead of electron.exe works just fine.

### To Reproduce

(forgiving me for not pushed to a github repo.)
a minimal c++ addon project using cmake-js and N-api which cause the electron to crash(built with `cmake-js -t v140 -a x64`, also tried with just `cmake-js` which is using default v142):

```cmake
# CMakeLists.txt
cmake_minimum_required(VERSION 2.8.2)

project(sstream_failure)

include_directories(${CMAKE_JS_INC})
add_library(${PROJECT_NAME} SHARED
  sstream_test.cc
  ${CMAKE_JS_SRC})
  # win_delay_load_hook.cc)  # I found a temporary fix later by adding an extra hook.
set_target_properties(${PROJECT_NAME} PROPERTIES PREFIX "" SUFFIX ".node")
target_compile_definitions(${PROJECT_NAME} PRIVATE NAPI_CPP_EXCEPTIONS NODE_ADDON_API_DISABLE_DEPRECATED)
target_link_libraries(${PROJECT_NAME} ${CMAKE_JS_LIB})

# Include N-API wrappers
execute_process(
  COMMAND node -p "require('node-addon-api').include"
  WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
  OUTPUT_VARIABLE NODE_ADDON_API_DIR)
string(REPLACE "\n" "" NODE_ADDON_API_DIR ${NODE_ADDON_API_DIR})
string(REPLACE "\"" "" NODE_ADDON_API_DIR ${NODE_ADDON_API_DIR})
target_include_directories(${PROJECT_NAME} PRIVATE ${NODE_ADDON_API_DIR})

message("NODE_RUNTIME:" ${NODE_RUNTIME})
message("NODE_RUNTIMEVERSION:" ${NODE_RUNTIMEVERSION})
message("NODE_ARCH:" ${NODE_ARCH})
```

```c++
// sstream_test.cc
#include <sstream>
#include "napi.h"

Napi::Number TestSStream(const Napi::CallbackInfo& info) {
  std::string name = info[0].As<Napi::String>();
  Napi::Function config_cb = info[1].As<Napi::Function>();
  Napi::Env env = info.Env();
  try {
    Napi::Object json = env.Global().Get("JSON").As<Napi::Object>();
    Napi::Function parse = json.Get("parse").As<Napi::Function>();
    std::stringstream ss;  // crashes on here.
    ss << "{\"" << name << "\": \"sstream initialized\"}";
    Napi::Object result = parse.Call(json, { Napi::String::New(env, ss.str()) }).As<Napi::Object>();
    config_cb.Call(env.Global(), { result });
    return Napi::Number::New(env, 0);
  } catch(const std::exception& e) {
    Napi::TypeError::New(env, std::string("cli error: ") + e.what()).ThrowAsJavaScriptException();
    return Napi::Number::New(env, (double) 1);
  }
}

Napi::Object Init(Napi::Env env, Napi::Object exports) {
  exports.Set(Napi::String::New(env, "testSStream"), Napi::Function::New(env, TestSStream));
  return exports;
}

NODE_API_MODULE(sstream_failure, Init)
```

and the main.js to call the addon:
```js
var addon = require('/path/to/sstream_failure.node');
addon.testSStream("Test", (config_json_str) => { console.log(config_json_str); });
```

### Additional Information

Via VS debugger I found that it is because the c++ symbols(std::basic_io, std::streambuf, etc) in my addon could not be found during std::stringstream object initialization(since load_exe_hook replaces the node.exe with electron.exe). Then go through the __delayLoadHelper2 function in delayhlp.cpp(which called the load_exe_hook), I found that in the last effort, it would try load_failure_hook() to get the symbol address, so the temporary solution I found here is as follows:
I copied the default win_delay_load_hook.cc and add following hook:
```c++
// load_exe_hook stuff ...

static FARPROC WINAPI load_failure_hook(unsigned int event, DelayLoadInfo* info) {
	if (event == dliFailGetProc) {
#ifdef DEBUG
		HMODULE m = GetModuleHandle("msvcp140d.dll");
#else
		HMODULE m = GetModuleHandle("msvcp140.dll");
#endif // DEBUG
		return m != NULL ? GetProcAddress(m, info->dlp.szProcName) : NULL;
	}
}

decltype(__pfnDliFailureHook2) __pfnDliFailureHook2 = load_failure_hook;
```
Then replace the original ${CMAKE_JS_SRC} by the new win_delay_load_hook.cc file in CMakeLists.txt, and it is now runs well as expected.

I also found this issue may relate to #14617 ?

**Comment by MarshallOfSound** [comment]
cc @deepak1556 Could this be libc++ being incompat here?

**Comment by galenelias** [comment]
I am new to Node.js native addons, but am also hitting this.  Trying to understand what's going on, I'm seeing that node.lib appears to be 'exporting' all the VC runtime symbols, but electron.exe isn't, so when you build a native module it decides to use node for it's VC runtime dependency, but when it goes to load those symbols from electron it then can't and raises an exception.

**Comment by zcbenz** [comment]
@forif I'm trying to reproduce this problem but did not reproduce, I assume it is because there were some details missing. Can you try to compile https://gist.github.com/zcbenz/4e979f11d65ad6d1a39560e71dc0424c and see if Electron can loads it on your machine?

(Note that in order to minimize the factors that may cause the problem, I used node-gyp to build the native module. Using cmake-js does not made a difference on my machine though.)

**Comment by forif** [comment]
@zcbenz I tried your code(node-gyp) and it indeed works fine. but when I using cmake-js to compile the same problem reproduced. see https://gist.github.com/forif/5d89b4affb7b50581ce693cd3ae0b24e

**Comment by zcbenz** [comment]
I believe this is a build configuration problem. Electron is built with libc++, while modules built by cmake-js are linked with the std library of visual studio dynamically, so the modules would try to search the std symbols from Electron and failed.

But I don't know how node-gyp does not have this problem, we have to compare the generated build configurations between node-gyp and cmake-js to find out why.

**Comment by mastergberry** [comment]
This is my quick adjustment to my test application with adding support for node-gyp: https://github.com/mastergberry/SimpleNativeAddon 

Please note, this test was done on macOS.

Node-GYP:

```
  c++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/Users/user/Library/Caches/node-gyp/12.16.2/include/node -I/Users/user/Library/Caches/node-gyp/12.16.2/src -I/Users/user/Library/Caches/node-gyp/12.16.2/deps/openssl/config -I/Users/user/Library/Caches/node-gyp/12.16.2/deps/openssl/openssl/include -I/Users/user/Library/Caches/node-gyp/12.16.2/deps/uv/include -I/Users/user/Library/Caches/node-gyp/12.16.2/deps/zlib -I/Users/user/Library/Caches/node-gyp/12.16.2/deps/v8/include -I../node_modules/nan  -Os -gdwarf-2 -mmacosx-version-min=10.10 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++1y -stdlib=libc++ -fno-rtti -fno-exceptions -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/binding/library.o.d.raw   -c -o Release/obj.target/binding/library.o ../library.cpp
  c++ -bundle -undefined dynamic_lookup -Wl,-no_pie -Wl,-search_paths_first -mmacosx-version-min=10.10 -arch x86_64 -L./Release -stdlib=libc++  -o Release/binding.node Release/obj.target/binding/library.o 
```

```
/usr/local/Cellar/cmake/3.13.2/bin/cmake -S/Users/user/Development/electron_9_native_add_on_bug/SimpleNativeAddon -B/Users/user/Development/electron_9_native_add_on_bug/SimpleNativeAddon/cmake-build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.13.2/bin/cmake -E cmake_progress_start /Users/user/Development/electron_9_native_add_on_bug/SimpleNativeAddon/cmake-build/CMakeFiles /Users/user/Development/electron_9_native_add_on_bug/SimpleNativeAddon/cmake-build/CMakeFiles/progress.marks
/Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/Makefile2 all
/Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/SimpleNativeAddon.dir/build.make CMakeFiles/SimpleNativeAddon.dir/depend
cd /Users/user/Development/electron_9_native_add_on_bug/SimpleNativeAddon/cmake-build && /usr/local/Cellar/cmake/3.13.2/bin/cmake -E cmake_depends "Unix Makefiles" /Users/user/Development/electron_9_native_add_on_bug/SimpleNativeAddon /Users/user/Development/electron_9_native_add_on_bug/SimpleNativeAddon /Users/user/Development/electron_9_native_add_on_bug/SimpleNativeAddon/cmake-build /Users/user/Development/electron_9_native_add_on_bug/SimpleNativeAddon/cmake-build /Users/user/Development/electron_9_native_add_on_bug/SimpleNativeAddon/cmake-build/CMakeFiles/SimpleNativeAddon.dir/DependInfo.cmake --color=
Dependee "/Users/user/Development/electron_9_native_add_on_bug/SimpleNativeAddon/cmake-build/CMakeFiles/SimpleNativeAddon.dir/DependInfo.cmake" is newer than depender "/Users/user/Development/electron_9_native_add_on_bug/SimpleNativeAddon/cmake-build/CMakeFiles/SimpleNativeAddon.dir/depend.internal".
Dependee "/Users/user/Development/electron_9_native_add_on_bug/SimpleNativeAddon/cmake-build/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/Users/user/Development/electron_9_native_add_on_bug/SimpleNativeAddon/cmake-build/CMakeFiles/SimpleNativeAddon.dir/depend.internal".
Scanning dependencies of target SimpleNativeAddon
/Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/SimpleNativeAddon.dir/build.make CMakeFiles/SimpleNativeAddon.dir/build
[ 50%] Building CXX object CMakeFiles/SimpleNativeAddon.dir/library.cpp.o
/Library/Developer/CommandLineTools/usr/bin/c++  -DSimpleNativeAddon_EXPORTS -I/Users/user/.cmake-js/electron-x64/v9.2.1/include/node -I/Users/user/Development/electron_9_native_add_on_bug/SimpleNativeAddon/node_modules/nan  -D_DARWIN_USE_64_BIT_INODE=1 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DBUILDING_NODE_EXTENSION -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -fPIC   -std=gnu++14 -o CMakeFiles/SimpleNativeAddon.dir/library.cpp.o -c /Users/user/Development/electron_9_native_add_on_bug/SimpleNativeAddon/library.cpp
[100%] Linking CXX shared module Release/SimpleNativeAddon.node
/usr/local/Cellar/cmake/3.13.2/bin/cmake -E cmake_link_script CMakeFiles/SimpleNativeAddon.dir/link.txt --verbose=1
/Library/Developer/CommandLineTools/usr/bin/c++ -D_DARWIN_USE_64_BIT_INODE=1 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DBUILDING_NODE_EXTENSION -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -bundle -Wl,-headerpad_max_install_names -undefined dynamic_lookup -o Release/SimpleNativeAddon.node CMakeFiles/SimpleNativeAddon.dir/library.cpp.o 
[100%] Built target SimpleNativeAddon
```

After this I did try to add this to the CMakeLists.txt file, but it did not seem to help:

`set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -stdlib=libc++")`

**Comment by lilong7676** [comment]
electron/electron#27205

**Comment by ohanar** [comment]
We ran into this issue as well. It seems like the issue is that electron is exporting various libc++ symbols in their lib stub on Windows. The way we worked around this was by explicitly linking the msvc runtime lib stubs before node. e.g. with cmake-js
```cmake
target_link_libraries ( ourModule
  PRIVATE
    msvcprt.lib
    msvcrt.lib
    vcruntime.lib
    ucrt.lib
    ${CMAKE_JS_LIB}
)
```
