### ISSUE TITLE
ubuntu npm install electron error when use taobao mirrors

### ISSUE THREAD

**Issue by a630140621** [electron/electron#22790]
![image](https://user-images.githubusercontent.com/26158889/77221213-a23c4200-6b82-11ea-8667-2bbf72b36003.png)

the correct taobao mirrors url is https://npm.taobao.org/mirrors/electron/8.1.1/electron-v8.1.1-linux-x64.zip

**Comment by malept** [comment]
What documentation are you using to set the mirror?

**Comment by a630140621** [comment]
`
npm config set registry https://registry.npm.taobao.org/
npm install electron                                                  
`

**Comment by malept** [comment]
Please see https://www.electronjs.org/docs/tutorial/installation#mirror for mirror instructions.

**Comment by a630140621** [comment]
thanks, i use next command to fix this
![image](https://user-images.githubusercontent.com/26158889/77222103-30b4c180-6b8b-11ea-80a3-187ba4cafd2c.png)

**Comment by malept** [comment]
You want either

```
ELECTRON_MIRROR="https://cdn.npm.taobao.org/dist/electron/"
```

or

```
ELECTRON_MIRROR="https://npm.taobao.org/mirrors/electron/"
ELECTRON_CUSTOM_DIR="{{ version }}"
```
