### ISSUE TITLE
Allow intercepting contentWindow.print in Electron to print iframes at the Electron layer

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#22796]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
I want to silent print an iframe.

Grabbing the frame from my sandboxed web app and doing `frame.contentWindow.print()` won't work since it's not silent.

Electron has an API on `webContents` that will let me silent print, but that will print the entire page, and I'm not able to have it just print a specific iframe.

### Proposed Solution
Can we get an `print` event that we can intercept at the Electron layer that will allow us to configure the print job? Like what `WebContents::print` does, but for an arbitrary `window` reference.

This will be similar to how we can intercept `window.open` with the `new-window` event.

### Alternatives Considered
We're playing around with shoving the iframe into its own (hidden) window and printing that.

**Comment by codebytere** [comment]
@pushkin- unfortunately we essentially just plumb through Chromium's printing architecture, which doesn't really allow for this kind of granularity at the moment. In theory it is possible, but not without us taking on significant maintenance burden and increasing friction with changes that Chromium makes to its own architecture. For now i'm going to close this as a wontfix, but if something changes and the aforementioned burden becomes less large i would be happy to look at and try my hand at this.

**Comment by chetanclozio** [comment]
@codebytere Is there any way to capture System level printer event in electron js? E.g if someone press Ctrl+P Or Print option on file then i want to capture that event inside my application.

**Comment by deniskak** [comment]
@chetanclozio have you found anything about being able to intercept the event?
