### ISSUE TITLE
HTTPError: Response code 404 (Not Found) for https://npm.taobao.org/mirrors/electron/v7.1.14/electron-v7.1.14-darwin-x64.zip

### ISSUE THREAD

**Issue by Garlic** [electron/electron#22792]
`➜  ~ npm config set electron_mirror https://npm.taobao.org/mirrors/electron/`

But I got this error:
`HTTPError: Response code 404 (Not Found) for https://npm.taobao.org/mirrors/electron/v7.1.14/electron-v7.1.14-darwin-x64.zip`
After electron@7.xxx , install.js 
`
const fs = require('fs')
const os = require('os')
const path = require('path')
const extract = require('extract-zip')
const { downloadArtifact } = require('@electron/get')`

and @electron/get will auto add 'v'Version
get/src/utils.ts
`export function normalizeVersion(version: string) {
  if (!version.startsWith('v')) {
    return `v${version}`;
  }
  return version;
}`

BUT the real download url is 
`https://npm.taobao.org/mirrors/electron/7.1.9/electron-v7.1.9-darwin-x64.zip`

So i can't download the lastest version.

**Comment by Garlic** [comment]
`registry=http://registry.npmjs.org
registry=https://registry.npm.taobao.org/
electron_mirror=https://cdn.npm.taobao.org/dist/electron/
electron_custom_dir=8.1.1`

**Comment by cyberpwnn** [comment]
That doesnt fix anything.
