### ISSUE TITLE
Support universal link on Electron

### ISSUE THREAD

**Issue by gujinku** [electron/electron#22802]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

As you may know, Apple is supporting universal link on MacOS 10.15+.  It looks like we need to provide some new APIs.
https://developer.apple.com/documentation/appkit/nsworkspace/3172702-open

### Proposed Solution

Implement the feature according to Apple's introduction

**Comment by nornagon** [comment]
It looks like this should be handleable through the [continue-activity](https://www.electronjs.org/docs/latest/api/app#event-continue-activity-macos) event, right? According to https://developer.apple.com/documentation/xcode/supporting-universal-links-in-your-app, you'll get an event with type [NSUserActivityTypeBrowsingWeb](https://developer.apple.com/documentation/foundation/nsuseractivitytypebrowsingweb), which you should be able to handle from the `continue-activity` event in JavaScript.

I'm closing this as I don't think there's any action for us to take here, but let me know if I've missed something 🙇🏻

**Comment by btjones** [comment]
@gujinku did you ever get this working? I believe I have everything setup correctly with applink entitlements but the `continue-activity` event doesn't fire for me.
