### ISSUE TITLE
Add Clipboard change event to clipboard API

### ISSUE THREAD

**Issue by gratmann** [electron/electron#2280]
I'd like to write a clipboard manager that monitors the systems' clipboard. Searching for an event in the clipboard I didn't found one.

I know there exists the HTML5 clipboard API, but my application needs to monitor the clipboard when it does not have focus.

I mean like `QClipboard`'s `void selectionChanged()` and `void dataChanged()` or like GTK's `owner-changed`.

Currently I'm retrieving the contents of the clipboard and look manually whether the content has changed every 20ms, which should not be the preferred way. It works but I really shouldn't resort to a busy polling loop...

**Comment by afc163** [comment]
Need that too

**Comment by destan** [comment]
:+1:

**Comment by mikesurowiec** [comment]
:+1: would be useful for me too

**Comment by alejandroSuch** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by blan4** [comment]
:+1:

**Comment by johnRivs** [comment]
+1

**Comment by edokeh** [comment]
+1
I need this!

**Comment by paulcbetts** [comment]
This isn't possible on OS X, you have to poll. It works on Windows, and miiiight work on Linux?

**Comment by destan** [comment]
@paulcbetts what do you mean by _isn't possible_? Did you take a look into how Qt implements this functionality?

**Comment by destan** [comment]
@zcbenz any plans in roadmap to implement this?

**Comment by paulcbetts** [comment]
@destan As far as I can see from https://github.com/qtproject/qtbase/blob/dev/src/plugins/platforms/cocoa/qmacclipboard.mm, it doesn't implement it at all, the event just doesn't fire.

**Comment by destan** [comment]
@paulcbetts I don't know about mac but it works on windows and linux (currently I am using it). Moreover you may be misinterpreting the source code because if it wasn't available on mac it would have been stated here http://doc.qt.io/qt-5/qclipboard.html#changed

**Comment by nwestbury** [comment]
+1, I could use this

**Comment by joelrobichaud** [comment]
+1

**Comment by zcbenz** [comment]
Chromium is going to add this feature, we will be able to use it Electron after it gets finished:
https://bugs.chromium.org/p/chromium/issues/detail?id=460610

**Comment by paulcbetts** [comment]
I'm not so sure, it looks like only X11 and ChromeOS get it

**Comment by wangxiexe** [comment]
want it badly! thx.

**Comment by destan** [comment]
@zcbenz https://bugs.chromium.org/p/chromium/issues/detail?id=460610 seems fixed, do you have time to check it out?

**Comment by iDaN5x** [comment]
@zcbenz any updates?

**Comment by jeffreysteo** [comment]
+1

**Comment by paulcbetts** [comment]
@destan Still only implemented for X11 and ChromeOS

**Comment by zh99998** [comment]
+1 for this request

**Comment by kevinsawicki** [comment]
@twang2218 this is still only implemented on Linux in Chromium

**Comment by LewdEwe-ErikWallace** [comment]
I'm also wishing Electron had clipboard events. :+1:

**Comment by twang2218** [comment]
Oh, that's unfortunately. For my case, I got performance hit of keep checking for new clipboard on Linux, which is 10-20 times slower than macOS. It would be great even if only implemented this feature on Linux.

**Comment by LewdEwe-ErikWallace** [comment]
For now I've simply used some preload code in a frameless hidden window as a kind of clipboard manager utility.  I'm using an interval timer of 250ms to read the clipboard and compare it to the last value; if it has changed I send an IPC message to the main Node Electron process. It suits my needs and is very responsive, as soon as I copy text in another application it immediately appears in my Electron app.

**Comment by JonasGroeger** [comment]
@LewdEwe-ErikWallace Do you have that code somewhere?

**Comment by iDaN5x** [comment]
Correct me if I'm wrong, but it should be possible to write a native node add-on to support this.

Native add-ons are written in C/C++ and compiled by node-gyp.
Using conditional preprocessor directives, we can support cross-platform support.

The add-on would subscribe to the system's native clipboard events & call stored callback JS functions when en event rises.

**Comment by LewdEwe-ErikWallace** [comment]
@JonasGroeger

Sorry I didn't see your comment sooner. Here is an example extracted from my project:

https://gist.github.com/LewdEwe-ErikWallace/d6e36f899a77a4f05e46388c254d014f

**Comment by LewdEwe-ErikWallace** [comment]
@dsantratlock
Feel free to copy anything in the gist if it helps you.

**Comment by codebytere** [comment]
As this is still only implemented in Chromium for Linux, I also believe this is better as a native addon rather then implemented in such a platform-specific capacity. As such, i'm labeling this a `wontfix`, but should something change on the Chromium side we can revisit this!

**Comment by PovarovDenis** [comment]
Hey folks, any updates?

**Comment by sudhakar3697** [comment]
Hey folks, check my npm module ([node-clipboard-event](https://www.npmjs.com/package/clipboard-event)) out.
Thank you.

**Comment by 318097** [comment]
I need this tooo

**Comment by akash07k** [comment]
I too need this badly. any update on this?
@hokein
@zcbenz

**Comment by akash07k** [comment]
Hey bro, your module is awesome, is there any way to get the data/text which has been changed?

> Hey folks, check my npm module ([node-clipboard-event](https://www.npmjs.com/package/clipboard-event)) out.
> Thank you.

**Comment by felipecrs** [comment]
For anyone interested in this feature, I suggest you star this crbug: https://bugs.chromium.org/p/chromium/issues/detail?id=933608

**Comment by akash07k** [comment]
starred.
> For anyone interested in this feature, I suggest you star this crbug: https://bugs.chromium.org/p/chromium/issues/detail?id=933608

**Comment by felipecrs** [comment]
Now that `clipboard-changed` was implemented in Chromium, can this issue be reopened for having it supported in Electron?

(I suppose some additional changes in Electron will be necessary)
