### ISSUE TITLE
Word, Excel and PowerPoint content does not update , when sharing using electron.desktopcapturer

### ISSUE THREAD

**Issue by k9winheit** [electron/electron#22804]
Electron version : 4.0.4
Operating system : Window 10 

Expected Behavior
When sharing some application (**Word,Excel and PowerPoint**) media stream should show that the app is updating when editing content and scrolling

Actual behavior
When sharing some application (**Word,Excel and PowerPoint**) UI is not updating (I can only see mouse moving but not showing editing and scrolling content on live feed), UI get updated only when I move office package to the other screen or resize the word or excel window it seems to update again). For this I am using **electron.desktopcapturer**

To Reproduce
This happened only when you are sharing application not screen. 

Screenshots
Some screen shots are attached

Please  it is really helpful If we can get solution ASAP
![Editi content](https://user-images.githubusercontent.com/11206974/77309356-853e7500-6d22-11ea-9056-41817e55a05f.PNG)
![Scroll Issue](https://user-images.githubusercontent.com/11206974/77309361-866fa200-6d22-11ea-9d60-120dd60335be.PNG)

**Comment by codebytere** [comment]
@k9winheit we don't support Electron v4 (it's past EOL), and in addition to that, this is an issue which seems to be app and/or platform-specific and not a function of Electron. As such, i'm going to close this out, but can re-open it if you can demonstrate that it occurs on a supported version or one that is not app-specific (i.e a bug in Electron itself).
