### ISSUE TITLE
JQuery Not Loaded when nodeIntegration enabled

### ISSUE THREAD

**Issue by Mugesh-Rajaram** [electron/electron#22801]
Hi Team,

I have created an Electron + Angular 8 application and enabled nodIntegration, while running the electron app JQuery is not loaded so other JQuery dependent files are also not getting loaded. Can any please help me in resolving this issue.

**Angular Package.json**
{
  "name": "application",
  "version": "0.0.0",
  "main": "electron-index.js",
  "scripts": {
    "ng": "ng",
    "start": "npm-run-all -p angular-start electron-start",
    "angular-start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "electron-start": "wait-on http-get://localhost:4200/ && electron . --serve",
    "start:electron": "ng build --base-href ./ && electron .",
    "package-win": "electron-packager . MyBuss --out=../executer/win --platform=win32 --arch=x64 --icon=electron_assets/icons/icon.ico --asar --overwrite"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "jquery": "^3.4.1",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.25",
    "@angular/cli": "~8.3.25",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "electron": "^8.1.1",
    "electron-packager": "^14.2.1",
    "electron-reload": "^1.5.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "npm-run-all": "^4.1.5",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3",
    "wait-on": "^4.0.1"
  }
}

**Inside angular.json**
 "styles": [
     "src/styles.scss",
     "src/assets/styles/bootstrap-4.4.1.css"
 ],
 "scripts": [
     "node_modules/jquery/dist/jquery.min.js",
     "src/assets/script/scripts.js",
     "src/assets/script/font-all.js",
     "src/assets/script/bootstrap.bundle.js"
]

**main.js**

// Modules to control application life and create native browser window
const electron = require('electron')
const { ipcMain, app, BrowserWindow, screen, remote } = electron;
const path = require('path')
const url = require('url');
let mainWindow;

const args = process.argv.slice(1),
  serve = args.some(val => val === '--serve');

function createWindow() {
  const size = screen.getPrimaryDisplay().workAreaSize;

  // Create the browser window.
  mainWindow = new BrowserWindow({
    x: 0,
    y: 0,
    width: size.width,
    height: size.height,
    frame: false,
    webPreferences: {
      allowRunningInsecureContent: (serve) ? true : false,
      **nodeIntegration: true**
    }
  })

  if (serve) {
    require('electron-reload')(__dirname, {
      electron: require(`${__dirname}/node_modules/electron`)
    });
    mainWindow.loadURL('http://localhost:4200');
  } else {
    mainWindow.loadURL(url.format({
      pathname: path.join(__dirname, 'dist/index.html'),
      protocol: 'file:',
      slashes: true
    }));
  }

  // Open the DevTools.
  if (serve) {
    mainWindow.webContents.openDevTools();
  }
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow)

// Quit when all windows are closed.
app.on('window-all-closed', function () {
  // On macOS it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') app.quit()
})

app.on('activate', function () {
  // On macOS it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) createWindow()
})

ipcMain.on('minimizeApp', (event, arg) => {
  mainWindow.minimize();
  mainWindow.webContents.send('minimizeAppResponse', "Success");
})

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.

![image](https://user-images.githubusercontent.com/16976667/77260063-a3b55980-6cab-11ea-8770-03fd773bfdb5.png)

**Comment by MarshallOfSound** [comment]
With nodeIntegration enabled you have to `require('jquery')` it's normal loader will not worker.  Either disable nodeIntegration or load it as a node module
