### ISSUE TITLE
Self-builded electron 4.2.12 reproduce black screen on windows 7 64bit

### ISSUE THREAD

**Issue by rvo337** [electron/electron#22800]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * self-builded 4.2.12 with changes in webrtc
* **Operating System:**
  * Windows 7 64-bit
* **Last Known Working Electron version:**
  * original release 4.2.12

### Expected Behavior
Black screen problem is not reproduced

### Actual Behavior
Back screen on application start

### To Reproduce
I have self-builded electron 4.2.12 with changes in webrtc code. If i build electron app from self-builded electron, then app have black screen problem.
But if i build electron app use original electron release 4.2.12, then app start success.

### Additional Information
If i use --disable-gpu flag, then problem is solved, but this solution reproduce many other problems

**Comment by nornagon** [comment]
Electron 4 is not a supported release line.
