### ISSUE TITLE
I found a very dangerous thing in electron

### ISSUE THREAD

**Issue by lnsane** [electron/electron#22818]
Excuse me for not being good at english

I used electron for abnormal development today. I mainly use tags <webview>, <BrowserView> to load third-party websites, because I found that some websites have some functions that are not what I want, so I looked for a long time online And found several APIs
**contents.executeJavaScript (code [, userGesture])**
**contents.insertCSS (css [, options]),**
I found out that this API can wait for the web page to load and embed the web page with js or css. Oh, is this a phishing script?

For example, I simulate a scene:
If there is a payment or entering a password or scanning code on a third page, I can embed js code, make changes, and even add an API to transfer data to me. Almost like this, you can easily implement man-in-the-middle attacks.

So, is there any document telling me that my page does not support such nesting, or is it forbidden to embed js, css in my website in electron?

**Comment by ckerr** [comment]
You're correct; extreme care must be taken when receiving code from an untrusted source.

See https://www.electronjs.org/docs/tutorial/security#isolation-for-untrusted-content and https://www.electronjs.org/docs/tutorial/security#checklist-security-recommendations for more information.

Thanks!
