### ISSUE TITLE
Fatal Error: EXC_BAD_ACCESS / KERN_INVALID_ADDRESS in atom::GetUploadData

### ISSUE THREAD

**Issue by le0zh** [electron/electron#22813]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
6.1.3

* **Operating System:**
macOS 10.12.6

* **Last Known Working Electron version:**
not sure

### Expected Behavior
No crash.

### Actual Behavior
Crashed.

### Screenshots
![image](https://user-images.githubusercontent.com/3633972/77384679-f7659700-6dc0-11ea-86ce-46923ee06c5d.png)

![image](https://user-images.githubusercontent.com/3633972/77384813-4f040280-6dc1-11ea-94ba-100dd304ec48.png)

### Additional Information

https://github.com/electron/electron/blob/v6.1.3/atom/common/native_mate_converters/net_converter.cc#L240

**Comment by ckerr** [comment]
@le0zh, 6-1-x is fast approaching end of life. Does this issue persist in newer versions of Electron, e.g. the 9.0.0 betas?

**Comment by koenoe** [comment]
I see the same issue in our Sentry project in latest Electron 8 (8.2.5).

**Comment by kamalbennani** [comment]
We see the same problem here too :/

**Comment by nornagon** [comment]
@kamalbennani @koenoe @jontonsoup can you confirm that you're seeing the same stack trace as shown in the top bug? The functions it mentions no longer exist in Electron 9.

If you're seeing a different stack trace, can you please post the details here?

**Comment by jontonsoup** [comment]
I think i might be confused on where this error is happening. It might be different. 

This is the error I'm getting: Fatal Error: EXC_BAD_ACCESS / KERN_INVALID_ADDRESS. Please let me know if there is a better issue to attach this to. 

Here is the crash. 
[5563fd3db9a84bd8abd27ff71ed88102-symbolicated.crash.zip](https://github.com/electron/electron/files/5170899/5563fd3db9a84bd8abd27ff71ed88102-symbolicated.crash.zip)


Thanks!

**Comment by nornagon** [comment]
@jontonsoup that error appears to be unrelated to the top post in this issue. It looks like that crash may be related to https://github.com/electron/electron/issues/22069. If you're still experiencing it in Electron 8.x, please open a new issue.

**Comment by jontonsoup** [comment]
Thanks! Apologies for the false alarm. I'm just getting better at reading crash dumps :)

**Comment by nornagon** [comment]
Closing this as the initial issue doesn't appear to be present any more. Will reopen if it resurfaces.
