### ISSUE TITLE
DownloadItem returns zero bytes on 'updated' event

### ISSUE THREAD

**Issue by siucht** [electron/electron#22819]
**Description**
Since upgrading to Electron 7.x.x and up, download stop working, the `downloadItem.getReceivedBytes()` on 'updated' event always returns 0, and downloaded file is zero size.

The download worked on Electron 6.x.x. 
Our code hasn't been changed. 
Is there any changes in Electron 7 for handling download?

**Code snippet**
```
dWindow.webContents.session.on('will-download', (event, downloadItem, downloadWebContents) => {  
      downloadItem.setSavePath(savePath);

      // Download in progress
      // eslint-disable-next-line consistent-return
      downloadItem.on('updated', (updatedEvent, state) => {
        // Download is interrupted but can be resumed
        if (state === 'interrupted') {
            logger.error('Received INTERRUPTED on download');
        }
        if (state === 'progressing') {
          logger.debug('Downloading addons-config...');
          logger.debug(`Received bytes: ${downloadItem.getReceivedBytes()}`);
        }
      });

      // Download completed/interrrupted
      downloadItem.once('done', (doneEvent, state) => {
        if (state === 'completed') {
          logger.debug('Download completed');
        } else if (state === 'interrupted') {
          logger.error(`Download is INTERRUPTED.`);
        }  
         // close window here
      });
    });
```

**Output**
```
[DEBUG] download-install-util - Downloading addons-config...
[DEBUG] download-install-util - Received bytes: 0
[DEBUG] download-install-util - Downloading addons-config...
[DEBUG] download-install-util - Received bytes: 0
[DEBUG] download-install-util - Downloading addons-config...
[DEBUG] download-install-util - Received bytes: 0
[DEBUG] download-install-util - Downloading addons-config...
[DEBUG] download-install-util - Received bytes: 0
[DEBUG] download-install-util - Downloading addons-config...
[DEBUG] download-install-util - Received bytes: 0
[DEBUG] download-install-util - Download completed for addons-config.json
[DEBUG] download-install-util - Closing addons-config download window
```

**Environment**
 OS: Mac OS v18.7.0
Electron: 7.0.0 and up

**Comment by joselrodrigues** [comment]
Hi any update to this issue?

**Comment by ckerr** [comment]
@joselrodrigues looks like this issue got lost. Would it be possible for you to make a standalone testcase out of the snippet above? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use. That way, anyone on the team doing triage can just download-and-run your testcase inside Fiddle.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by zepp-pp** [comment]
Still getting this error on version 31.3.0
