### ISSUE TITLE
Expose `spellcheck_platform::CheckSpelling` API

### ISSUE THREAD

**Issue by craftzdog** [electron/electron#22829]
Hi, thank you for creating such a great framework!
I have a feature request which I think I can contribute, but let me check if you are interested in supporting it.

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
The builtin spellchecker has been supported in https://github.com/electron/electron/pull/20692.
But it does not allow us to check spells programmatically, like [node-spellchecker](https://github.com/felixrieseberg/node-spellchecker)'s `isMisspelled` method.
Chrome's spellcheck_platform provides [CheckSpelling](https://chromium.googlesource.com/chromium/src/+/46ee392970e491fb9ee2523348e23222b40d5119/components/spellcheck/browser/spellcheck_platform.h#60) to do that exactly.

### Proposed Solution
Add a method to call `spellcheck_platform::CheckSpelling` like so:

```cc
#if BUILDFLAG(USE_BROWSER_SPELLCHECKER)
bool Session::CheckSpelling(const std::string& word) {
  if (spellcheck::UseBrowserSpellChecker()) {
    return spellcheck_platform::CheckSpelling(base::UTF8ToUTF16(word), 0);
  }
  return true;
}
#endif
```

in `shell/browser/api/atom_api_session.cc`.

It's simple and won't affect other features.

### Alternatives Considered
I don't know.

### Additional Information
None

Thanks!

**Comment by MarshallOfSound** [comment]
@craftzdog That method is not cross platform, can you clarify your usecase for this method?

**Comment by craftzdog** [comment]
@MarshallOfSound Thanks for the reply.

My usecase is that I'm building a Markdown editor based on [CodeMirror](https://codemirror.net/) which browser's spellchecker doesn't work.
So, we have to use a plugin like [codemirror-spell-checker](https://github.com/sparksuite/codemirror-spell-checker) which checks spellings in JS.

I found [`SpellCheck::SpellCheckWord`](https://chromium.googlesource.com/chromium/src/+/46ee392970e491fb9ee2523348e23222b40d5119/components/spellcheck/renderer/spellcheck.cc#268) which looks cross platform.
Would it be possible to invoke from `Session`?

**Comment by astoilkov** [comment]
@MarshallOfSound On what operating system is the `spellcheck_platform::CheckSpelling` available? What about `SpellCheck::SpellCheckWord`?

Exposing the API will benefit a lot of applications using a custom editor. The electron site shows [65 applications that contain "editor" in their description](https://www.electronjs.org/apps?q=editor).

We have the same problem at https://caret.io/.

**Comment by lishid** [comment]
I have the same setup with CodeMirror. After digging around for a few hours, I did not find any undocumented spellcheck access 😂

The current alternative is to use typo.js and self-manage hunspell libraries downloading from the renderer. Other than having to do all that repeated work, it also doesn't support multiple languages (https://github.com/cfinke/Typo.js/issues/37)

A second alternative is to bring in electron-spellchecker (or a variant of it) which is what we were trying to move away from in the first place with native spellchecker support.

Hoping we can make this a reality. Thanks again for all the hard work!

**Comment by abnerlee** [comment]
Maybe also expose `spellcheck_platform::FillSuggestionList` to get suggestions for words that are "misspelled"

**Comment by lishid** [comment]
@MarshallOfSound I've put down a few hours into exploring the codebase and hooking up a working prototype. Currently having some trouble with how to properly expose the API. Would really appreciate if you have some tips.

As for use case, adding to the others here, I'm working on https://obsidian.md which is also based on CodeMirror.

@craftzdog @astoilkov @abnerlee Also wanted to say hi, big fan of all your work! 😃

**Comment by craftzdog** [comment]
@lishid hi 👋 Great to know you made a PR for the issue!
