### ISSUE TITLE
app.setVersion is not present in api.json

### ISSUE THREAD

**Issue by neilrees** [electron/electron#22849]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.0
* **Operating System:**
  * n/a

### Expected Behavior
The `setVersion` method on `App` should be included in the `api.json` artifact so that it can be called from typescript.

For an example, as this code sample is suggesting: https://github.com/electron/electron/issues/21593#issuecomment-568117257

### Actual Behavior
The `setVersion` method is missing from `api.json`.

To invoke from typescript you must cast to any first: `(<any>app).setVersion("1.2.3");`

### Screenshots

![image](https://user-images.githubusercontent.com/282424/77662902-53bce800-6f74-11ea-8c1f-66d8df7cfe1f.png)

**Comment by codebytere** [comment]
This is intentional - it's not a documented API, and our TypeScript typings only reflect our consumer-facing code.
