### ISSUE TITLE
Windows can be lost when spawned or moved onto a differently scaled monitor

### ISSUE THREAD

**Issue by meredith-ciq** [electron/electron#22840]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.0, 7.1.3
* **Operating System:**
  * Windows 10

### Expected Behavior
Windows should not be missing after being spawned or moved.

### Actual Behavior
Windows can be lost when running under a specific monitor configuration with different scaling. Under this monitor configuration windows were lost in two ways:
* Spawning a window on the bottom right corner of the secondary monitor
* Spawning a window on the primary monitor and moving it with setbounds to the bottom right corner of the secondary monitor.

When the window is spawned on the primary monitor and moved to a position closer to the top of the secondary, the window is not lost, but has doubled bounds. In the cases where the window is lost the reported bounds from getBounds match were I tried to position the window, so there is no way to key off those values to determine that the window was lost.

### To Reproduce
Two monitors, with the primary on the right:
![image](https://user-images.githubusercontent.com/46169395/77590805-fe75cd80-6ec4-11ea-95e7-d88a5c91ba01.png)

Primary: scaling 200%, resolution 2560x1440
Secondary: scaling 100%, resolution 1920x1080

```sh
$ git clone https://github.com/meredith-ciq/electron-quick-start/ -b scaling_lost_windows
$ npm install
$ npm start
```
A window will open with buttons for four cases. Click each button to run the scenario. Information about the bounds of the window and monitor info will log to the main process in each case.
* Case 1: Window is lost when directly spawned on bottom right corner of secondary.
* Case 2: Window is lost when spawned on the primary and moved to the bottom right corner of the secondary
* Case 3: Window ends up in the wrong location when spawned on the primary and moved the the middle right of the secondary (bounds are doubled)
* Case 4: Window is not lost and ends up in the correct position when it is spawned on the secondary and moved to the bottom right corner of the secondary

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
