### ISSUE TITLE
The webContents 'new-window' event has an empty frameName if the link target starts with a '_'

### ISSUE THREAD

**Issue by Kilian** [electron/electron#22848]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
* **Electron Version:** 8.2.0

### Expected Behavior
When I click a link that triggers a new-window event, such as one with `target="_blank"`, I expect that target name to end up in the frameName argument. However, this only works for targets without a _ prefixed. If there is a _ prefix, the frameName is empty.

### To Reproduce

Fiddle: https://gist.github.com/3af1fff2d9e8203c2cdf2736144dc70e

instructions:

* Click first link: check console to see that frameName is empty
* Click second like: check console to see a filled-in frameName

I would expect for the first link that the frameName in the console is "_blank".

**Comment by nornagon** [comment]
Does this happen for all `_` prefixes or just the [special ones](https://html.spec.whatwg.org/multipage/browsers.html#valid-browsing-context-name-or-keyword) ?

**Comment by Kilian** [comment]
It seems just the special ones (i.e. the target `_foobar` comes through). Of the special ones, `_blank` is the only one that triggers `new-window`.

**Comment by nornagon** [comment]
Then this is expected behavior. Blink intercepts the frame name ahead of when it arrives at `new-window` and interprets it appropriately.
