### ISSUE TITLE
Unable to login to google drive :(

### ISSUE THREAD

**Issue by Praveer1981** [electron/electron#22857]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  8.0.2
* **Operating System:**
  Windows 10 Enterprise  N
* **Last Known Working Electron version:**
 7.0.0

### Expected Behavior
I should be able to login to the google drive through my electron app

### Actual Behavior
It is not allowing me to `login` to the google drive via the electron based application. Attached the snapshot.

### Screenshots
![image](https://user-images.githubusercontent.com/24364597/77716259-af40b180-7018-11ea-832f-a68b754f5cf0.png)

### Additional Information
I could resolve this problem by removing `Electron` from the user Agent also I had to Modify `Chrome` in the user agent in order to make it work.
`app.on("ready", () => {
  **app.userAgentFallback = app.userAgentFallback.replace("Electron/" + process.versions.electron, "");
  app.userAgentFallback = app.userAgentFallback.replace("Chrome/" + process.versions.chrome, "Chrome");**
  createWindow ();

  Menu.setApplicationMenu(null);

});`

This is the temporary solution so that our customer will not get impacted.Also We knew that google is going to deprecate user-agent very soon.

**What would be the alternative solution to make it work ?**

**Comment by codebytere** [comment]
This is unfortunately out of Electron's control, as it is something whose functionality lies with Chromium - we recommend you continue to override the userAgent on the consumer end and, if you would like, direct your feedback to http://crbug.com/.
