### ISSUE TITLE
desktopCapturer.getSources cannot detect unplug/replug monitor

### ISSUE THREAD

**Issue by darthzeran** [electron/electron#22856]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
4.2.8
* **Operating System:**
Windows 10

### Expected Behavior
When I unplug an HDMI or USB connection to another monitor, I expect `desktopCapturer.getSources({ types: ['screen'] }` to return the number of screens connected.
It returns 3 when I have a usb and HDMI connection in (Main screen (laptop), and 2 monitors = 3 screens).  WHen i unplug and replug, i still expect 3.

### Actual Behavior
At start, the computer finds 3 screens.  When i unplug, it finds 2 screens, but when I replug, it only finds the previous 2.

### To Reproduce
1-Have a laptop with a usb-> monitor plugged in, and a normal HDMI plugged into a monitor.
2- Use electron code
```
desktopCapturer.getSources({ types: ['screen'] }, async (error, sources) => {
		if (error) {
			throw error
		}
console.log(sources)
	})
```
Try with 3 screens, unplug, try again, replug, try again.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
