### ISSUE TITLE
MediaRecorder.ondataavailable not firing after computer is locked

### ISSUE THREAD

**Issue by liubo113** [electron/electron#22860]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** v8.1.1
* **Operating System:** macOS 10.15.4
* **Last Known Working Electron version:**

### Expected Behavior

Continuing record the window when coming back.
### Actual Behavior

MediaRecorder.ondataavailable not firing after computer is locked or sleeping, it also not work when i comeback to it again.

MediaRecorder.state is still "recording", but ondataavailable not fire.

### Additional Information

```javaScript
const { desktopCapturer } = require('electron')

class WindowRecorder {
  bufferCache
  _mediaRecorder

  constructor(bufferCache) {
    this.bufferCache = bufferCache
    this._handleDataAvailable = this._handleDataAvailable.bind(this)
    this._handleStart = this._handleStart.bind(this)
    this._handleStop = this._handleStop.bind(this)
    return (async () => {
      await this._init()
      return this
    })()
  }

  start(ms) {
    this._mediaRecorder.start(ms)
  }

  stop() {
    this._mediaRecorder.stop()
  }

  async _init() {
    const source = await this._getCaptureSource()
    const mediaStream = await this._getMediaStream(source)
    let recorder = new MediaRecorder(mediaStream, {
      mimeType: 'video/webm; codec=vp9',
    })
    recorder.ondataavailable = this._handleDataAvailable
    recorder.onstart = this._handleStart
    recorder.onstop = this._handleStop
    this._mediaRecorder = recorder
  }

  async _getCaptureSource() {
    let sources
    try {
      sources = await desktopCapturer.getSources({ types: ['window'] })
    } catch (err) {
      throw new Error(`failed to get sources ${err}`)
    }
    return sources.find(s => s.name === process.env.npm_package_name)
  }

  async _getMediaStream(source) {
    const constraints = {
      audio: false,
      video: {
        mandatory: {
          chromeMediaSource: 'desktop',
          chromeMediaSourceId: source.id,
        }
      }
    }
    let stream
    try {
      stream = await navigator.mediaDevices.getUserMedia(constraints)
    } catch (err) {
      throw new Error(`failed to get media stream ${err}`)
    }
    return stream
  }

  // it doesn't fire when computer is locked
  async _handleDataAvailable(evt) {
    const chunk = new Blob([evt.data], { type: 'video/webm; codecs=vp9' })
    const buffer = Buffer.from(await chunk.arrayBuffer())
    this.bufferCache.push(buffer)
  }

  _handleStart() {
    console.log('start recording')
  }

  _handleStop() {
    console.log(`stop recording`)
  }
}
```

**Comment by liubo113** [comment]
Is there a known issue about this problem on windows platform? @sofianguy

**Comment by liubo113** [comment]
It will trigger onstop event after upgrading electron to v9.1.0, the state also change to `inactive`.

**Comment by gitdust** [comment]
> It will trigger onstop event after upgrading electron to v9.1.0, the state also change to `inactive`.

I'm use electron v6.0.0 and have some issue on windows plantform.
do I need to update electron to v9.1.0?
