### ISSUE TITLE
Mac: "activate" not sent when application is made active by custom URL scheme

### ISSUE THREAD

**Issue by stevebaxter** [electron/electron#22874]
### Preflight Checklist
* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.0.1
* **Operating System:**
  * macOS 10.15.3
* **Last Known Working Electron version:**
  * n/a

### Expected Behavior
When our application receives a custom URL via "open-url" it should be activated and should receive the "activate" event.

### Actual Behavior
Our application becomes activated but the "activate" event is not sent.

### To Reproduce
Run this fiddle:

https://gist.github.com/1ffcea98bac898c05fcff1371a1ba447

From a terminal window, do: `open com.test.event:hello`

The Electron app should be made active and we should see "activate" and "Received open-url com.test.event:hello". This doesn't happen, we just see "Received open-url com.test.event:hello"

### Additional Information
A workaround is to emit "activate" explicitly in the code that handles URL. This may lead to an application activating more than once, however this is harmless in our particular case.

**Comment by miniak** [comment]
This is expected
