### ISSUE TITLE
Cannot drag window with -webkit-app-region: drag;

### ISSUE THREAD

**Issue by jhuckaby** [electron/electron#22872]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.1.1
* **Operating System:**
  * macOS 10.15.3
* **Last Known Working Electron version:**
  * 1.8.4

### Expected Behavior

The window should be draggable by clicking on elements styled with `-webkit-app-region: drag;`.

### Actual Behavior

The window does not move when clicking and dragging on elements styled with `-webkit-app-region: drag;`.

### To Reproduce

This bug can be reproduced very easily using the most minimal of examples.  See code below:

**index.js**

```js
var {app, BrowserWindow} = require('electron');
var mainWindow = null;

app.whenReady().then( function() {
	mainWindow = new BrowserWindow({
		width: 800,
		height: 600
	});
	mainWindow.loadFile('index.html');
} );
```

**index.html**

```html
<!DOCTYPE HTML>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>Hello World!</title>
		<meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'">
	</head>
	<body style="-webkit-app-region: drag; -webkit-user-select: none;">
		<h1>Hello World!</h1>
	</body>
</html>
```

Run this example and you will see the window cannot be dragged by clicking inside the content, even though the entire body is styled with `-webkit-app-region: drag;`.

### Screenshots

None needed.

### Additional Information

This bug is related to, but not a duplicate of, the following:

- #21621 (talking about BrowserView specifically)
- #22474 (says "cannot resize" but I think they mean move / drag)

**Comment by jhuckaby** [comment]
Works after adding `titleBarStyle: 'hidden'`.  I did not know that was required for `-webkit-app-region: drag` to activate.  Closing this bug.  Sorry!

**Comment by Slapbox** [comment]
@jhuckaby glad you got it working! I'd encourage you to remove your comment here for completeness: https://github.com/electron/electron/issues/21621#issuecomment-605394949

**Comment by jhuckaby** [comment]
@Slapbox Done, thank you -- I had forgotten that.
