### ISSUE TITLE
Unable to display local photos that contain whitespace in name (windows)

### ISSUE THREAD

**Issue by gnesher** [electron/electron#22879]
### Preflight Checklist
* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

I've created a simple application that requests a user to select a photo using electron.remote.dialog.showOpenDialog after which I simply try to show a preview of the selected photo.

It works fine except for when it comes to files/paths with spaces on windows.
things like :
C:\Users\path name\Downloads\image name.jpeg

The image is not displayed at all (fails to load the file) and solutions like encodeURI don't seem to help.

* **Electron Version:**
Electron v7.1.2

* **Operating System:**
Windows 10 (18363)

* **Last Known Working Electron version:**
N/A

### Expected Behavior
Photos should be displayed in the browser even when they (or the folder they are in) include whitespace 

### Actual Behavior
Photos do not display, console error saying browser was unable to locate file

### To Reproduce

Simply use electron.remote.dialog.showOpenDialog to choose an image file that contains whitespace / lives within a folder that contains whitespace (on a window machine) and try to display the result.

Something along these lines:

```
        let options = {
          title: 'Select photos',
          buttonLabel: 'Done',
          filters: [{ name: 'Images', extensions: ['jpeg'] }],
          properties: ['openFile', 'multiSelections'],
        };
        let selectedPhoto = await electron.remote.dialog.showOpenDialog(
          options
        );
        photosList = [encodeURI(selectedPhoto.filePaths[0])];

```

### Screenshots
N/A

### Additional Information
N/A

**Comment by Hicham95** [comment]
Typically, if an image is named with a space, ie, “my image.jpg”, the browser will add a character code to represent the space. It would then look like this: “my%20image.jpg”. So what’s this mean? It means that images and files using spaces between multiple names more than likely will break at some point. 
You would use Node's path.relative for that.

**Comment by gnesher** [comment]
@Hicham95 doing something like 
`path.relative(electron.remote.app.getAppPath(), selectedPhoto.filePaths[0])`
will result with '..\..\..\Downloads\passport (2).jpeg' and the path will still contain spaces/won't be displayed.

It's worth noting that the browser window does not automatically replace whitespace with %20  - I need to use encodeURI for that.

**Comment by MarshallOfSound** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by gnesher** [comment]
I've created a test app only to realize the problem seems to be with sanitizer.bypassSecurityTrustStyle handling of spaces in some edge cases. Closing this
