### ISSUE TITLE
Limit FPS and/or stop updating page entirely

### ISSUE THREAD

**Issue by danbulant** [electron/electron#22873]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
I am developing an app that should be always running animation. It's aesthetically pleasing, while some performance might be lost due to rendering it. There should be a way to pause rendering entirely, or at least lower the FPS limit. (For the FPS limits, I tried searching and found chrome *had* a flag limiting FPS, but it was removed since)

### Proposed Solution
Having some kind of function to pause rendering
```js
win.webContents.pauseRender();
```

### Alternatives Considered
Or at least limit FPS to less than 60:
```js
app.FPSLimit = 25;
```

### Additional Information
App is always running. Also tried using the FPS limit on offscreen rendering, but it didn't work.

I don't need any node integration (and running it in sandbox), so solutions can depend on not using node (or using, doesn't matter as of now).

**Comment by codebytere** [comment]
This is generally, from a performance perspective, indicative of something that should be changed or altered in that app itself as opposed to band-aided in core itself. 

Given that this isn't currently on our roadmap, and in the interest of the scope of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR.
