### ISSUE TITLE
Need Help - How can i install any service during electron app installation

### ISSUE THREAD

**Issue by ShrinathGupta** [electron/electron#22886]
I just wanted to know, how i can package windows service and client code inside electron final package for windows and Linux - NSIS and Linux.

Any help will be really appreciated.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
