### ISSUE TITLE
Some data is missing when requested via custom HTTP Protocol

### ISSUE THREAD

**Issue by archiecodes** [electron/electron#22883]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
TL;DR: Electron's http protocols lose data

When I register a http protocol (`session.fromPartition("tabs").protocol.registerHttpProtocol`) and try to use it, the data is different from the original source. I'm trying to have a react application at hydrogen://home, but data is lost, so I get bad JavaScript.
![image](https://user-images.githubusercontent.com/42045366/77894794-b44a6e80-726d-11ea-88d1-39317a3b17e5.png)
This is very strange. JavaScript is being corrupted.

It works fine when accessing it via http://localhost:5165/home, from both Electron and Firefox. I suspect that this is only happening with large files, but I'm not sure. I have confirmed this is not react's fault by also trying to make hydrogen://home go to [easylist](https://easylist.to/easylist/easylist.txt), and the data is clearly not the same length. (See screenshots)

* **Electron Version:**
  * v8.1.1
* **Operating System:**
  * Ubuntu 19.04 x64
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior

hydrogen://home returns the exact data at http://localhost:5165/... or https://easylist.to/easylist/easylist.txt

### Actual Behavior

hydrogen://home returns *most* of the data, but some (seemingly random) parts are lost. *The data returned changes every time I make a request, despite the fact that the specific files that are requested are static.*

### To Reproduce
Clone my [WIP browser](https://github.com/alleshq/hydrogen/tree/ca5e4e385e0e72e38dd5569249138e6fc298d7ee) (from commit `ca5e4e385e0e72e38dd5569249138e6fc298d7ee`), and in one terminal, start the UI react application with:
```sh
$ cd ./app
$ npm i
$ npm start
```
and start electron in `.` with:
```
npm i
npm start
```
Once the browser is running, enter `!!hydrogen://home` in the url bar (`!!` bypasses the api). Currently `hydrogen://` is a http protocol for easylist, so you can open the dev tools by entering `h:dev` in the url bar and then check the length of the list returned; it should be a lot less than when you go to it via https://easylist.to/easylist/easylist.txt.

### Screenshots

![image](https://user-images.githubusercontent.com/42045366/77895365-8f0a3000-726e-11ea-8b8f-d9cffd95ce90.png)

### Additional Information

None.

**Comment by NilSet** [comment]
I am seeing a similar response corruption in registerHttpProtocol. When calling the callback with a `file:` url of a large file, I am seeing chunks of code from further into the file being spliced in earlier.

**Comment by NilSet** [comment]
Here is a gist with both the original file and one corrupted version fetched over the custom httpscheme https://gist.github.com/NilSet/2bfd80f5fa4bad6cccefa08996f50bb9

**Comment by NilSet** [comment]
And here is an electron fiddle which seems to reliably reproduce the problem. Every time it runs it gets a different hash result because the response has been corrupted randomly
https://gist.github.com/NilSet/3271505191e377b605735314c286d8f0

**Comment by NilSet** [comment]
This is also reproducible on macos by the way. Have not tested on windows yet.

**Comment by klwfwdk** [comment]
when I use axios to post request via custom HTTP Protocol, all data was lost. May be the same problem

**Comment by sentialx** [comment]
Similar to #20932

**Comment by archiebaer** [comment]
I'm no longer working on the project that had this issue, but Electron didn't throw any errors. I would just receive a response with a lot of data missing. It would work fine for small stuff, but I was using react (CRA) and it would mean that the code was malformed.

**Comment by archiebaer** [comment]
Oh, but when I tried it on my windows device, it worked fine, and my friend, who was using arch, had no issues, but I think some other people testing it did.

**Comment by chichiangho** [comment]
got the same problem,a large file will missing some data,use registerBufferProtocol worked
