### ISSUE TITLE
With integrated spellchecker and multi language, context-menu is slow, app freezing and sluggish

### ISSUE THREAD

**Issue by eugene-pr** [electron/electron#22881]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.0-beta.10
* **Operating System:**
  * Windows 10 18362
* **Last Known Working Electron version:**
  * -

### Expected Behavior
Integrated Spellchecker misspelled word suggestion should be fast enough independently of a text size, so the application won't look freezing and sluggish

### Actual Behavior
After enabling the integrated spellchecker, and pasting a large text to the textarea, the application start freezing on scroll, and becomes sluggish. Also, it takes to much time before context-menu is triggered (sometimes 5-10sec.). Tested with electron-quick-start app

### To Reproduce

* Set spellcheck:true in BrowserWindow
* let languages = session.defaultSession.availableSpellCheckerLanguages;
* session.defaultSession.setSpellCheckerLanguages(languages);
* Paste large text into a text area
* See context-menu trigger time, or overall application behavior on scroll etc.

### Screenshots

![electron-spellchecker](https://user-images.githubusercontent.com/9944915/77896558-27111500-7281-11ea-81d8-8d2a61baf075.gif)

**Comment by MarshallOfSound** [comment]
```
let languages = session.defaultSession.availableSpellCheckerLanguages;
session.defaultSession.setSpellCheckerLanguages(languages);
```

Yeah this is going to be slow, you're asking the spellchecker to check **50** languages.  That's unreasonable and it will be unusable for most users.  At most you should be checking 2 or 3 languages, not 50.

Closing this out as expected behaviour for unreasonable API usage

**Comment by eugene-pr** [comment]
I also checked it with two languages and it had the same behaviour.
