### ISSUE TITLE
Open multiple child windows, webContents new-window listener will crash

### ISSUE THREAD

**Issue by tym3515** [electron/electron#22888]
win.webContents.on(
    'new-window',
    (event, newUrl, frameName, disposition, options) => {
      console.log('new-window=>options', options)
      event.preventDefault()

      handleNewWindow({ event, newUrl, options, frameName, url })
    }

**Comment by MarshallOfSound** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
