### ISSUE TITLE
Error invoking remote method 'ELECTRON_GUEST_WINDOW_MANAGER_WINDOW_METHOD' when trying to use google drive api

### ISSUE THREAD

**Issue by godza** [electron/electron#22898]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v9.0.0-beta.12
* **Operating System:**
  * 10.15.3
* **Last Known Working Electron version:**
  * I don't really know, i've jumped from 2.x version to 9 beta. In version 2 it worked without any hickups

### Expected Behavior
To use google drive api to select a file that i can pass trough to my app.

### Actual Behavior
When the google authentication popup appears and when i authenticate with google, google drive api process crashes with error i've provided in the bug report title and is seen in provided screenshots

### To Reproduce
I use WebView to load my app inside of a electron browser window. WebView has allowpopups option turned on. In my app i initiate google api file picker by clicking on a button and when i authenticate, authentication popup freezes. When trying to do these steps again, message "Error invoking remote method 'ELECTRON_GUEST_WINDOW_MANAGER_WINDOW_METHOD'" appears as shown in the screenshot

### Screenshots
https://imgur.com/0l6y7eA
https://imgur.com/ftMbEWa

**Comment by MarshallOfSound** [comment]
@godza Please enable `nativeWindowOpen: true` in your webpreferences

**Comment by godza** [comment]
Thanks @MarshallOfSound,
That did the trick.

**Comment by alishahlakhani** [comment]
@MarshallOfSound you are lifesaver my man :D

**Comment by cesarvarela** [comment]
Any explanation of why?
