### ISSUE TITLE
AutoUpdater::quitAndInstall doesn't work anymore

### ISSUE THREAD

**Issue by probablycorey** [electron/electron#229]
When AutoUpdater::quitAndInstall is called it never terminates the app.

How to reproduce:
- Wait for an update to be downloaded
- Open the dev tools and run `require('remote').require('auto-updater').quitAndInstall()`
- All windows close but Atom stays open and won't close.
- When I force quit Atom it will relaunch and is updated to the correct version

This error appears (in Console.app) after Atom is download:

```
4/11/14 10:22:44.087 AM com.apple.launchd.peruser.501[129]: (com.github.atom.ShipIt[41127]) assertion failed: 13C64: launchd + 105965 [425516B6-9F3E-342F-87B3-EC461EBA6A1A]: 0xd
```

But I don't think that log message is related to this.

**Comment by bitomule** [comment]
I'm still having this issue. Update is installed but app is never closed. Any idea?

**Comment by Kamahl19** [comment]
I also have this problem on latest electron. I call quitAndInstall, it installs update but does not relaunch the app. It opens new app after manual relaunch
