### ISSUE TITLE
Can selectedTextRange be whitelisted for MAS builds?

### ISSUE THREAD

**Issue by dbalatero** [electron/electron#22908]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
When I use Electron apps such as Slack or Discord on OSX, I'm unable to retrieve the `AXSelectedTextRange` accessibility attribute from input fields, and as a result cannot access cursor position/selection. I have some system-wide plugins that rely on being able to get the cursor position.

I think it's due to this patch, and those apps probably being built for the Mac App Store:

https://github.com/electron/electron/blob/d8737734bff17bccbfc7291f948b705d4c490d74/patches/chromium/mas_no_private_api.patch#L37-L41

### Proposed Solution

Could we turn these selection range attributes back on?

I'm not too clear on why certain APIs would need to be turned off to avoid rejection in the app store, so this might be off base.

Other native, non-Electron apps I've installed seem to provide these accessibility attributes when queried, so I'm wondering if this is something we could relax?

### Alternatives Considered

It's either on/off I think in this case.

### Additional Information

None

**Comment by codebytere** [comment]
@dbalatero unfortunately no - the APIs referenced there are APIs that are patched out because they're private. Any private API usage by Electron apps results in automatic rejection by the App Store, so we aren't able to relax that at this time.

**Comment by FelixKratz** [comment]
This is very sad news for svim in electron apps https://github.com/FelixKratz/SketchyVim/issues/12.

**Comment by dbalatero** [comment]
@FelixKratz Funny, I was asking for my similar Vim project as well! https://github.com/dbalatero/VimMode.spoon
