### ISSUE TITLE
File downloads broken when using a url that redirects to the actual file.

### ISSUE THREAD

**Issue by smithalan92** [electron/electron#22906]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.0
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron version:**
  * Electron 6.1.0

### Expected Behavior
Downloading a file using `window.webContents.downloadURL(url)` should correctly download the file that results from the Http request, even if `url` redirects to the file.

Eg. https://sample.com/file/1 -> Redirects to https://bucket.s3.amazonaws.com/files/file.zip , which Electron correctly downloads.

### Actual Behavior
Triggering a file download using a url that redirects to a file results in an incorrect file mime type being calculated which results in the file not being able to be downloaded. Eg. in the above example it seems the following happens.

1. Trigger download using https://sample.com/file/1
2. File mime type is calculated using the above url
3. Redirect is followed to https://bucket.s3.amazonaws.com/files/file.zip, but nothing happens. Using the save dialog, the incorrect file extension is suggested.

### To Reproduce
Trigger a download using a url which redirects to a file. 

Sample Electron Fiddle https://gist.github.com/smithalan92/de6eead97e9009fe2b9e39ed250bf90c.

`electron-fd.mralansmith.com/file/:id` is a simpel API as follows

```
const express = require('express')
const app = express()
const port = xxx

app.get('/file/:id', (req, res) => {
    res.redirect(301, 'https://tw-open.s3.amazonaws.com/electron/pdf_sample.pdf')
});

app.listen(port, () => console.log(`Example app listening at http://localhost:${port}`))
```

**Comment by codebytere** [comment]
Please provide a standalone [fiddle] that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue. It's not clear, for example, what "trigger a download" means, and we may look at the wrong codepaths as a result.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by smithalan92** [comment]
Sorry @codebytere , I meant to come back and add one but forgot. I've updated the issue details with a Gist link for a fiddle.

**Comment by codebytere** [comment]
Hmm - I ran your repro fiddle and experienced correct behavior for both:

![redirect](https://user-images.githubusercontent.com/2036040/78743013-51fb0900-7912-11ea-9f93-59a3fc612131.gif)

**Comment by smithalan92** [comment]
Madness, Its also working for me now in the Fiddle, and I checked the actual app where we spotted this issue, and it is also fine there now. It must have been something to do with AWS/S3 I'm guessing, since nothing changed in either the fiddle or our production app in the last 24 hours.

Thanks for checking it out @codebytere and sorry for wasting your time on it, I'll close this off now.
