### ISSUE TITLE
Electron v8.2.0 Bluetooth broken on Mac

### ISSUE THREAD

**Issue by zbot473** [electron/electron#22909]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
This was a thing in earlier electron versions, but I started to get this now. Possibly due to some things I did to this laptop but I'm not too sure. 

* **Electron Version:**
 v8.2.0
* **Operating System:**
macOS 10.13.6 

### Expected Behavior
Example: Google auth works using web bluetooth API. Also, Google Bluetooth samples don't work.

### Actual Behavior
The auth window hangs and the process throws an `NSInvalidArgumentException `. (Not an actual process hang — it's just stuck)

### To Reproduce

Fiddle:
https://gist.github.com/9ec38a297101c951d2ab397e29db1155

**Comment by codebytere** [comment]
@zbot473 it's not clear what we need to do in order to repro this - running the fiddle brings up a page but there are many myriad actions one might take once on that page, and so we cannot proceed. Can you please explain the repro steps in more detail?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!

**Comment by zbot473** [comment]
@codebytere 
Hi, sorry for not responding. 

I made a new fiddle here: https://gist.github.com/2660dc8ff7c7479989d5e0e4cb33c64e.

Steps: 
1. Run the 
2.  Make sure that the all devices button is selected
3. Press the Get Bluetooth Device info button, and check the fiddle console, it should give the NSInvalidArgumentException. 

If you use Google 2fa with a security key as your phone, and try to sign in through an electron app, the Google auth window refuses to proceed after entering your password, because it is stuck on generating a challenge for bluetooth. This is the reason why I had opened the issue.

Let me know if you need any more information.
