### ISSUE TITLE
Windows Taskbar "flash" when the BrowserWindow switch with another

### ISSUE THREAD

**Issue by caminin** [electron/electron#22907]
### Preflight Checklist

* [ X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.3
* **Operating System:**
  * Windows 10 1903

### Expected Behavior
When, in kiosk mode or fullscreen, I change the current Window with any of these : 
- Show a new BrowserWindow
- Hide the current BrowserWindow
- Move an old BrowserWindow to the top
The Windows taskbar stays hidden and doesn't "flash".

### Actual Behavior
On Windows,when you do any of the step before, the taskbar "flash".
Even with options that should disable this behaviour.

It's working fine on Linux

### To Reproduce
I've put a little project I made to demonstrate this behaviour. It swaps between two window that should be on top

  I've tested : 
- Using kiosk or fullscreen
- show the browserwindow immediatly or wait a little bit
- use the type 'toolbar' for the browserWindow
- setAlwaysOnTop("true","screen-saver",1);
- remove the icon from the taskbar
- use the focus
- modal and/or child window

### Screenshots
Here is a little gif to demonstrate. It's done with the code below
https://gifyu.com/image/drjc

### Additional Information
I want to use it for a Kiosk App, with a main window with my app, and the possiblity to open new link on another webpage.

If I can, I don't want to use just one Window because I lost the navigation from my app when I exit the webpage (I know how to restore the navigation it but it's complicated, I don't want to enter into details).

So I would like two BrowserWindow, One for my App and another for the navigation.

Is this behaviour a bug or is it Windows fault (again...)
Again, it's working fine on Linux.

```
const { app, BrowserWindow}= require('electron');


//******VARIABLES***********

let mainWindow,tab;

//******OPTIONS WINDOWS***********
const optionsMain= {
	frame:false,
	width:1920,//pour le mode dev
	height:1080,
	kiosk:true,
	type:'toolbar',
	show: false
};
const optionsMain2= {
	frame:false,
	width:1920,//pour le mode dev
	height:1080,
	fullscreen:true,
	show: false
};


//******INIT***********
app.on('ready', createWindow);
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') { app.quit(); }
})
app.on('activate', () => {
	createWindow();
});

//******FUNCTIONS***********
async function createWindow() {
	mainWindow = new BrowserWindow(optionsMain);
	mainWindow.setAlwaysOnTop("true","screen-saver",1);
	mainWindow.loadURL("https://github.com");

	tab = new BrowserWindow(optionsMain2);
	tab.loadURL("https://google.fr");

	mainWindow.moveTop();
	mainWindow.show();

	setInterval(mySwitch,9000,tab,mainWindow,"off");
	setTimeout((tab,mainWindow)=>{setInterval(mySwitch,9000,tab,mainWindow,"on")},3000,tab,mainWindow);

}

function mySwitch(tab,mainWindow,myType){
	switch(myType){
		case "on":
			mainWindow.show(); 
			tab.hide(); 
		break;
		default:
			mainWindow.hide(); 
			tab.show(); 
	}
}
```

**Comment by caminin** [comment]
The issue seems to be with the focus (when a window in fullscreen get the focus when another window had it, it show the windows taskbar).
Anyway, the option **thickFrame** seems to be a workaround. 

_Maybe it should be in the documentation ?_

When the option is **false**, the "taskbar flash" doesn't show.
When it is **true** (and it is by default), it appears.
Here is a project to test it, just press Ctrl+D to switch between the two BrowserWindows.
It has been tested on both Linux and Windows, but the issue was on windows only.

```
const { app, BrowserWindow, session,dialog, globalShortcut,protocol }= require('electron');
//******VARIABLES***********

var mainWindow,tab,tab2;
var myType="on";

//******OPTIONS WINDOWS***********
const optionsMain= {
	frame:false,
	width:1920,//pour le mode dev
	height:1080,
	kiosk:true,
	skipTaskbar:false,
	show: false,
	thickFrame:false,
};

//******INIT***********
app.on('ready', createWindow);
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') { app.quit(); }
})

//******FUNCTIONS***********
async function createWindow() {
	registerShortcuts()

	tab = new BrowserWindow(optionsMain);
	tab.loadURL("https://google.com");

	tab2 = new BrowserWindow(optionsMain);
	tab2.loadURL("https://github.com");

	tab.show(); 
	tab2.show(); 
}

function mySwitch(){
	switch(myType){
		case "on":
		myType="off";
			showWindow(tab2);
		break;
		default:
			myType="on";
			showWindow(tab);
	}
}

function showWindow(mywindow){
	mywindow.focus();
}

function registerShortcuts(){
  // Enregistrer un écouteur de raccourci 'CommandOrControl+X'.
  const ret = globalShortcut.register('CommandOrControl+D', () => {
    mySwitch();
  })
  const ret2 = globalShortcut.register('CommandOrControl+F', () => {
  	app.quit();
  })
}
```

**Comment by sircharlo** [comment]
Thank you so much for this. `thickFrame` was in fasct the source of my woes with `alwaysOnTop` vs taskbar flashing and focus; I never would have found it if not for this post.
