### ISSUE TITLE
Uncaught TypeError: Object.entries is not a function

### ISSUE THREAD

**Issue by haohan007008** [electron/electron#22904]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
v8.2.0
* **Operating System:**
  Windows 10 64bit

electron load local file 
Console logs Uncaught TypeError: Object.entries\Object.values is not a function

load http server can work

delete my code  ` v-decorator`   can work .code is 

` <a-form-item>
            <a-input
              size="large"
              type="text"
              placeholder="账户: admin"
              v-decorator="[
                'username',
                {rules: [{ required: true, message: '请输入帐户名或邮箱地址' }, { validator: handleUsernameOrEmail }], validateTrigger: 'change'}
              ]"
            >` 

my configuration error ？

**Comment by nornagon** [comment]
Unfortunately without any steps to reproduce this issue we can't debug further. Please provide a small example that reproduces the issue you're seeing, preferable using [Electron Fiddle](https://github.com/electron/fiddle).

Thanks!

**Comment by codebytere** [comment]
We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.
