### ISSUE TITLE
trafficLightPosition sets the y position incorrectly

### ISSUE THREAD

**Issue by ttrepka** [electron/electron#22926]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.0
* **Operating System:**
  * macOS 10.14.6 
* **Last Known Working Electron version:**
  * None

### Expected Behavior
When creating a `BrowserWindow` with `trafficLightPosition: { x: 100, y: 100 }`, traffic lights should show `100px` from the left and `100px` from the top of the window.
![Screenshot 2020-04-02 at 17 38 25](https://user-images.githubusercontent.com/6588668/78211195-c7c53600-7508-11ea-99ec-3cda535902bc.png)

### Actual Behavior
Traffic lights are only 50px from the top.
![Screenshot 2020-04-02 at 17 35 11](https://user-images.githubusercontent.com/6588668/78211007-57b6b000-7508-11ea-922f-9607d2d6da90.png)

### To Reproduce
[Electron fiddle](https://gist.github.com/ttrepka/ad1964299b8cb36af9d116a3f594bec8)

### Additional Information
It seems multiplying the `y` value twice (i.e. making it `200` in my example) leads to the desired offset.

If that's of any help, I'm using a standard external monitor with my Mac Mini (not retina).

**Comment by MarshallOfSound** [comment]
Can you provide details of your display scaling and monitor resolution.  It's possible this should be documented but the coordinates system used to position the traffic lights is different to the coordinates system your renderer has.  They are position based on the OS coordinates system not the scaled coordinates system of your actual renderer.

**Comment by ttrepka** [comment]
The display is `1920x1080`, scale factor `1`. Here's the full Display object for reference:
```
{
  "id": 458675522,
  "bounds": {
    "x": 0,
    "y": 0,
    "width": 1920,
    "height": 1080
  },
  "workArea": {
    "x": 0,
    "y": 23,
    "width": 1920,
    "height": 984
  },
  "accelerometerSupport": "unknown",
  "monochrome": false,
  "colorDepth": 24,
  "colorSpace": "{primaries_d50_referred: [[0.6512, 0.3349],  [0.3236, 0.6214],  [0.1534, 0.0527]], transfer:BT709_APPLE, matrix:RGB, range:FULL}",
  "depthPerComponent": 8,
  "size": {
    "width": 1920,
    "height": 1080
  },
  "workAreaSize": {
    "width": 1920,
    "height": 984
  },
  "scaleFactor": 1,
  "rotation": 0,
  "internal": false,
  "touchSupport": "unknown"
}
```
> They are position based on the OS coordinates system not the scaled coordinates system of your actual renderer.

Does this mean the position will be different, dependent on used monitor? Is there any way (e.g. using the `scaleFactor`) to convert the pixel position to the OS coordinates system?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
