### ISSUE TITLE
setTimeout is broken in ELECTRON_RUN_AS_NODE

### ISSUE THREAD

**Issue by arantes555** [electron/electron#22935]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

When `ELECTRON_RUN_AS_NODE` is enabled, `setTimeout` is basically broken. It works the first time it's used, not the second time.

* **Electron Version:**
  * Every version between 6.0.0 & 9.0.0-beta12
* **Operating System:**
  * macOS 10.14.6 & Ubuntu 18.04
* **Last Known Working Electron version:**
  * None

### Expected Behavior
setTimeout should work consistently

### Actual Behavior
When `ELECTRON_RUN_AS_NODE` is enabled, `setTimeout` is basically broken. It works the first time it's used, not the second time.

### To Reproduce

```sh
$ git clone https://github.com/arantes555/electron-bug-settimeout.git
$ npm install
$ npm start
```

This runs multiple times, with the current node & with versions of electron from 6 to 9.
For a given run, it prints `IT WORKED!` when `setTimeout` works normally, and nothing otherwise.

### Additional Information
Somehow, when wrapping the `setTimeout` in a `process.nextTick`, or a `setImmediate`, it works.

This makes me thing that it's linked to https://github.com/electron/electron/issues/7079 and to the activation of the uv loop in lib/common/init.ts .

**Comment by codebytere** [comment]
Closing as duplicate underlying issue for https://github.com/electron/electron/issues/21515.

**Comment by codebytere** [comment]
cc @ckerr

**Comment by arantes555** [comment]
@codebytere thanks, I didn't find the other issue. I hadn't realized that it was related to using `async/await` *at the same time* as using `setTimeout` ...
