### ISSUE TITLE
App turns into blank white window after signing in macOS

### ISSUE THREAD

**Issue by DTLTAKE** [electron/electron#22938]
Hi all,

As a follow-up of #22884 , I signed my app with `--hardened-runtime` enabled. However, by doing so, I get a blank window.

I have checked other similar posts but could not find an answer which solves my issue. Any help please?

I am using the following command to sign my app: 
`./node_modules/.bin/electron-osx-sign dist/MyApp.app --no-gatekeeper-assess --identity="Developer ID Application: COMPANY (#######)" --entitlements=dist/entitlements.mac.plist --entitlementsInherit=dist/entitlements.mac.plist --hardened-runtime`
And I'm using the following entitlements:

```
<?xml version="1.0" encoding="UTF-8"?>  
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">  
<plist version="1.0">  
<dict>  
    <key>com.apple.security.cs.allow-jit</key><true/>  
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key><true/>  
    <key>com.apple.security.cs.disable-library-validation</key><true/>  
    <key>com.apple.security.automation.apple-events</key><true/>  
    <key>com.apple.security.cs.disable-executable-page-protection</key><true/>
    <key>com.apple.security.temporary-exception.files.absolute-path.read-only</key><true/>  
    <key>com.apple.security.temporary-exception.files.absolute-path.read-write</key><true/>  
    <key>com.apple.security.network.client</key><true/>  
    <key>com.apple.security.network.server</key><true/>  
    <key>com.apple.security.assets.movies.read-write</key><true/>  
    <key>com.apple.security.assets.music.read-write</key><true/>  
    <key>com.apple.security.assets.pictures.read-write</key><true/>  
    <key>com.apple.security.files.downloads.read-write</key><true/>  
    <key>com.apple.security.files.user-selected.read-write</key><true/>  
    <key>com.apple.security.device.usb</key><true/>  
    <key>com.apple.security.device.bluetooth</key><true/>  
    <key>com.apple.security.personal-information.location</key><true/>  
</dict>  
</plist>  
```
I am using:
```
electron: 4.0.6
electron-packager: 13.1.1
electron-osx-sign: 0.4.1
```

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by DTLTAKE** [comment]
Thank you for your reply @sofianguy 

After updating Electron, the issue still stands. Now I have the following versions:
```
electron: 8.2.0
electron-packager: ^14.2.1
electron-osx-sign: ^0.4.15
```

**Comment by MaddHatters** [comment]
I am also been experiencing this issue but with submission to the app store. I do not have issues when signing and running locally.

https://github.com/electron/electron/issues/22135#issuecomment-659671793

**Comment by lmick002** [comment]
@DTLTAKE & @MaddHatters I just had this problem. I signed the MAC with hardenedRuntime: true and the MAS build with hardenedRuntime: false and the Apple team were able to review the app (after having the blank screen issue with prior builds)

**Comment by DevonPeroutky** [comment]
@MaddHatters @DTLTAKE I'm getting this problem as well. Were either of you able to figure this out? I've been at this for hours and I'm pulling my hair out.

**Comment by MaddHatters** [comment]
Hey Devon, are you doing a MAC or MAS build?

**Comment by DevonPeroutky** [comment]
I'm just doing a simply build for Mac (Not a Mac App Store App). I'm using `electron-forge` and my config (the packager portion) looks like:
```    
...
packagerConfig: {
    "protocols": [{"name": "Peak", "schemes": ["peak-dev-app", "peak-app"]}],
    "name": "Peak",
    "executableName": "Peak",
    "dmg": {
        "sign": false,
    },
    "osxSign": {
        identity: process.env.APPLE_DEVELOPER_IDENTITY,
        hardenedRuntime: true,
        'gatekeeper-assess': false,
        entitlements: 'entitlements.mac.plist',
        'entitlementsInherits': 'entitlements.mac.plist',
        'signature-flags': 'library'
    },
    "osxNotarize": {
        "appleId": process.env.APPLE_ID,
        "appleIdPassword": process.env.APPLE_ID_PASSWORD
    },
    "icon": "./src/assets/logos/electron-icons/mac/icon.icns",
    packageManager: 'yarn'
},
```

And in the interest of getting something working, I enabled all the entitlements listed on the [hardenedRuntime](https://developer.apple.com/documentation/security/hardened_runtime) page
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.cs.allow-jit</key>
    <true/>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
    <key>com.apple.security.cs.allow-dyld-environment-variables</key>
    <true/>
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>
    <key>com.apple.security.cs.disable-executable-page-protection</key>
    <true/>
    <key>com.apple.security.cs.debugger</key>
    <true/>
  </dict>
</plist>
```

Building & Signing the app works with `hardenedRuntime: false`, but as soon as I set it to true, the app will sign successfully but only show white on startup with no logs or errors.

**Comment by SowmiyaGovindharaj** [comment]
The same issue I am facing with windows while trying to automate electron application. Is this resolved and if yes can anyone tell the solutions
