### ISSUE TITLE
Support Mouse Buttons as Accelerators

### ISSUE THREAD

**Issue by Kyusung4698** [electron/electron#22939]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

I'm building a app which uses the `Ctrl + Mousewheel` as a default shortcut because it's convenient for the user to switch to my app. Unfortunately this is not possible with the default accelerators available so i'm using the native npm module [iohook](https://github.com/wilix-team/iohook).

### Proposed Solution

I'd like to have all available mouse buttons as accelerators. Like MouseWheelUp, MouseWheelDown, Left, Right, Middle, X1 and X2. 

### Alternatives Considered

I'm currently using the native npm module [iohook](https://github.com/wilix-team/iohook) which is sadly not as stable as i like it to be. Also it's only available as passive listener so the mouse input still get's through.

**Comment by codebytere** [comment]
At present, we only support accelerators which are compatible with Chrome's accelerator framework, and non-key accelerators are currently not compatible. The only way for us to potentially support this would be to take on the significant maintenance burden of patching Chromium's accelerator infrastructure, which we're not at this point prepared to do. Should something change upstream we're happy to reconsider this, but for now i'm going to close and mark `wontfix`.
