### ISSUE TITLE
Mac OS - HTTP authentication - NTLMv2 authentication not working

### ISSUE THREAD

**Issue by christophpre** [electron/electron#22951]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.1.9, 7.2.1, 8.2.0, 9.0.X
* **Operating System:**
  * macOS 10.15.4
* **Last Known Working Electron version:**
  * Never

### Expected Behavior
1. When authenticating via HTTP authentication and Proxy/Server only allows NTLMv2, authentication should work.
2. When authenticating via HTTP authentication and Proxy/Server negotiates protocol and allows NTLMv1 and NTLMv2, Electron should always use NTLMv2.

### Actual Behavior
1. When authenticating via HTTP and the Proxy/Server only allows NTLMv2 and 'login' event is triggered in Electron and **Password/Username is entered correctly**, authentication does not work. Windows Event Log Error Code 0xc000006d / Substatus 0xc000006a (https://docs.microsoft.com/en-us/windows/security/threat-protection/auditing/event-4625)
2. When authenticating via HTTP authentication and Proxy/Server negotiates protocol, Electron always uses NTLMv1.

### To Reproduce
1. Configure all Domain Controllers for Windows server to only allow NTLMv2
2. Try to authenticate with correct credentials via Electron 'login'-Event
-> 'login'-Event in Electron is triggered again and the described Error Codes can be seen in Windows Event Log

### Screenshots
![image](https://user-images.githubusercontent.com/6893212/78341915-be83aa00-7598-11ea-929b-836cca0097a5.png)
![image](https://user-images.githubusercontent.com/6893212/78341931-c4798b00-7598-11ea-8c8e-c44d85b41ff6.png)

### Additional Information
* This issue #17111 states, that Chrome should use NTLMv2 per default since Chromium 65
* NTLMv2 in Electron works on Windows 10 Version 1903 (OS Build 18362.476)
* NTLMv2 is used and works per default on Chromium Browser Version 80.0.3987.158, which is used in current stable Electron Version 8.2.0, where it does not work

**Comment by christophpre** [comment]
Any news on this?

**Comment by deepak1556** [comment]
Sorry I couldn't get time to PR this yet, but the cause is simple NTLMv2 was only enabled in chrome https://source.chromium.org/chromium/chromium/src/+/master:chrome/common/chrome_features.cc;l=517 

The default value for embedders on posix platform is disabled https://source.chromium.org/chromium/chromium/src/+/master:services/network/public/mojom/network_service.mojom;l=155

Hence this never worked on any electron versions before, I will have to enable this on older versions behind a flag. Will try to do this sometime later this week.

**Comment by rizi** [comment]
@deepak1556  any update on this? I also suffer from this bug.
thx in advance

**Comment by christophpre** [comment]
@deepak1556 Sry to ask again. Do you have any timeline, when this bug can be addressed?

**Comment by deepak1556** [comment]
Working on a PR now.
