### ISSUE TITLE
Video tearing on armv7l with Electron, no video tearing on included Chromium

### ISSUE THREAD

**Issue by snblackout** [electron/electron#22956]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v7.1.1
  * v7.1.9
* **Operating System:**
  * Built-on: Ubuntu 18.04 x64
  * Target-arch: armv7l
  * Run-on: Raspbian Buster on Raspberry Pi 4
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior

When you open a new Electron window to YouTube (https://youtu.be/KVYup3Qwh8Q) music video that has a lot of movement, video should be smooth and playback great.  No tearing.

### Actual Behavior

Open an Electron built application to the same YouTube URL.
Play the video full-screen.
Video plays, but has considerable amount of horizontal tearing.

### To Reproduce

  * Using `electron-quick-start` on startup of main, open a new child window to the YouTube video:

```
var child = new BrowserWindow({parent: mainWindow});
  child.loadURL('https://youtu.be/KVYup3Qwh8Q')
  child.once('ready-to-show', () => {
    child.show()
  })
```
  * Build an Electron app targeting armv7l using script `electron-builder --linux deb --armv7l`
  * Copy .deb package to Raspberry Pi 4 running latest Raspbian
  * Install .deb package `sudo dpkg -i ./Documents/app-name_armv7l.deb`
  * You may need some dependencies for install so run `sudo apt --fix-broken install`
  * Run the newly installed Electron app
  * Maximize the new child window
  * Play the music video full-screen
  * Notice random horizontal tearing when on high-movement within video

To reproduce with no video tearing with included Chromium build on Raspbian Buster

  * Open Chromium and navigate to the YouTube URL above
  * Maximize the window
  * Play the music video full-screen
  * Notice no (or very minimal to notice) video tearing in the same video

### Screenshots

Not applicable as this is video related and cannot easily get screenshots of issue.

### Additional Information

I have created a question on the Raspberry Pi Stack Exchange here: https://raspberrypi.stackexchange.com/questions/109717/video-tearing-in-custom-electron-app-but-not-with-included-chromium-app

I have compared GPU reports for both included Chromium and Electron and the Electron build has a couple driver bug workarounds applied that the Chromium version does NOT.

```
>> decode_encode_srgb_for_generatemipmap
>> disable_post_sub_buffers_for_onscreen_surfaces

>> Disable partial swaps on Mesa drivers (detected with GL_VERSION): 339493
Applied Workarounds: disable_post_sub_buffers_for_onscreen_surfaces

>> Decode and encode before generateMipmap for srgb format textures on os except macosx: 634519
Applied Workarounds: decode_encode_srgb_for_generatemipmap
```

The included Chromium for Raspbian Buster may include some additional patches for armv7l that Electron is not applying for that particular architecture.

I would love some assistance in narrowing this down and coming up with a fix.

Thanks in advance.

**Comment by jeffrson** [comment]
For me it seems this is also present in 8.2.1 - with local videos, though.

I wonder if Electron uses hardware accelerated video decoding on a Raspberry. Any insights?

**Comment by snblackout** [comment]
> Does it use libffmpeg.so for decoding?

I believe so, yes.  I've got confirmation from an anonymous source on Pi SE question that the included Chromium is using ffmpeg for decoding, so I would assume so would Electron+Chromium.

> Has it hardware decoding support?

I don't believe so as of yet.  I believe the Mesa driver team is hard at work to make that happen.  I've tried some command line switches to ignore GPU features which one of them toggled the "Hardware decoding" to enabled from the GPU report, but it didn't make a difference in tearing.

I'd really like to know who or which repository was used to compile Chromium for the Raspbian Buster release that is being used.  We could see exactly how they're compiling Chromium for the ARM platform and it may be that Electron needs to do those patches or config as well for its ARM implementation.

**Comment by snblackout** [comment]
> Does it use libffmpeg.so for decoding

After more testing with the application I'm developing, the tearing isn't just when video is playing in Electron.  I've seen it happen with any high movement on the page like a slideshow that slides images in and out quickly.

So now I'm leaning more towards just a rendering issue for anything on the webpage that requires quick movement/painting on screen, not just video playback related.

**Comment by skyler1253** [comment]
@snblackout I've run into the same issue.  Were you able to come up with a workaround to get electron apps to render better?

**Comment by snblackout** [comment]
@skyler1253 I haven't with electron.  Our project is a dedicated device, and wasn't really in the need for strictly Electron support, so we have background services running for typical stuff, and any webpage for visuals we used Apache server running locally and then started up Chromium in kiosk mode pointing to the localhost address.  Chromium does not tear the high movement, but is much more unstable.  For an example, running the same exact webpage in Electron and also in Chromium off of a local instance of Apache, the Electron app runs for over a week no issues, the Chromium implementation can crash one or a few time per day.  I believe Chromium is using hardware acceleration, but using that method is not as stable right now.  I'm hoping for updated drivers to make Chromium method more stable.  Also, once that happens I believe Electron app built for ARM could implement the same patches Chromium is built with to get that hardware acceleration.

**Comment by juanadamuzsimj** [comment]
I have a simple video tag in my electron app and I can see tearing on all videos. I open that videos in pi chromium or VLC and I can't see tearing....

**Comment by thunderkerrigan** [comment]
has anyone come up with a solution/workaround yet?

**Comment by juanadamuzsimj** [comment]
> has anyone come up with a solution/workaround yet?

Yes, I ended up using omxplayer (An external video processing package that uses native video rendering instead of browser render):

https://www.npmjs.com/package/node-omxplayer

**Comment by snblackout** [comment]
Be aware that omxplayer is being deprecated.

From: https://github.com/popcornmix/omxplayer

> Note: omxplayer is being deprecated and resources are directed at improving vlc.
> 
> This is due to: omxplayer uses openvg for OSD and subtitles which isn't supported on Pi4. omxplayer uses openmax which has been deprecated for a long time and isn't supported with 64-bit kernels. omxplayer does not support software decode omxplayer does not support advanced subtitles omxplayer does not support playback from ISO files. omxplayer does not integrate with the X desktop
> 
> Please try using vlc. If there are features of omxplayer that vlc does not handle then try reporting here.

**Comment by MartinPavlik** [comment]
I'm hitting multiple issues with playing videos via omxplayer / vlc on Pi 4 (after playing videos for more than few days the omx processes start to not exit cleanly and are not possible to be killed etc.).

Any idea how to make the video playback possible directly in Electron? In Chromium everything seems to work fine, can someone explain why it is a problem in Electron? Thanks :pray:

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
