### ISSUE TITLE
Extend/patch native Platform Code

### ISSUE THREAD

**Issue by Sachanski** [electron/electron#22961]
### Preflight Checklist

* [ x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description - _Extending platform specific native code_
I was wondering if there is a way to patch/interact with the native platform code/APIs. For example, if I needed to register for push notifications on a native MacOS app:
- I would call `registerForRemoteNotifications(matching types: NSApplication.RemoteNotificationType)` or `registerForRemoteNotifications()`, since the former is deprecated I believe. 
- I would recieve the device token inside the `application(_ application: NSApplication, 
didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data)` funciton, which is a member of the `NSApplicationDelegate` protocol (for those unfamiliar - the device token is then used so an application can receive push notifications).

As far as I know Electron does not provide access to those parts of the app architecture.

### Proposed Solution
I am not extremely familiar with how the native apps that embed the browser for each platform (windows, Mac) are built, however I saw that there is an [electron_application_delegate.mm](https://github.com/electron/electron/blob/d9321f4df751fa32813fab1b6387bbd61bd681d0/shell/browser/mac/electron_application_delegate.mm) file, which I assume is the entry point for the MacOS apps (there is probably something similar for Windows). Could there be a way to add some mechanism, so developers can add custom code there, or maybe another solution with a similar effect?

### Alternatives Considered
I have checked some solitions that basically utilize [PushAPI](https://developer.mozilla.org/en-US/docs/Web/API/Push_API), but that way the application does not receive notifications if it is not launched.

### Additional Information
Something similar is done by the Cordova plugins - write a couple of native files (Kotlin/Java for Android; Swift/Objective-C for iOS) + 1 javascript file and the platform provides a mechanism to communicate with the native code. In particular - one can check how Push Notifications for iOS are implemented [here](https://github.com/phonegap/phonegap-plugin-push/blob/master/src/ios/AppDelegate%2Bnotification.m).

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
