### ISSUE TITLE
Electron Installation Errors 

### ISSUE THREAD

**Issue by carbondigitalus** [electron/electron#22960]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
* **NPM Version:** 6.14.4
* **Node Version:** v12.14.1
* **Electron Version:** 8.2.0
* **Operating System:** Mac OS Catalina Version 10.15.3
* **Last Known Working Electron version:** This is my first time using Electron.

### Expected Behavior

Expected the install to work without errors. 
### Actual Behavior

When installing Electron with `npm install electron -g` the "part 1" errors are received. When I run `electron` in the terminal the "part 2" errors are received. 

ERROR PART 1: 
```
/usr/local/bin/electron -> /usr/local/lib/node_modules/electron/cli.js

> electron@8.2.0 postinstall /usr/local/lib/node_modules/electron
> node install.js

(node:8505) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdtemp '/usr/local/lib/node_modules/electron/electron-download-3ptJO8'
(node:8505) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8505) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
+ electron@8.2.0
updated 1 package in 1.811s
```

ERROR PART 2: 
```
/usr/local/lib/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/usr/local/lib/node_modules/electron/index.js:14:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron/index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron/cli.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
```

### To Reproduce

Part 1: run the following in the terminal "npm install electron -g".
Part 2: run the following in the terminal "electron".

GitHub Repo: https://github.com/stackacademytv/master-electron
I'm using this repo in a Udemy course, but it's irrelevant to this issue because I'm discussing a global install error. 

### Additional Information

I've tried multiple times to delete the node modules folder like error part 2 states, and trying again to install but nothing has worked. 

Now, I have no issues going into the project referenced above, and also the Electron Demo App, and running the start script to open the app. It works fine. The only problem is here in the global install and use.

**Comment by codebytere** [comment]
@carbondigitalus it looks like your system permissions are causing the issue:
```
 EACCES: permission denied, mkdtemp '/usr/local/lib/node_modules/electron/electron-download-3ptJO8'
```

the second error is caused by the first. I recommend you switch to root or something to resolve it, or update your system permissions to allow creation of such temporary directories.
