### ISSUE TITLE
app.moveToApplicationsFolder() throwing error 

### ISSUE THREAD

**Issue by twitharshil** [electron/electron#22971]
Electron Version: 7.1.13
Operating System: macOS Catalina 10.15.3
Last Known Working Electron version: 3.1.8

**Expected Behavior**
Above function should be able to 
- Close application 
- Move application to ApplicationFolder
- Launch application 

**Actual Behavior**
All of the expected behaviour is working, but during the app close inside the `moveToApplicationsFolder()` an error is thrown. Able to re-produce this error file we package electron-fiddle for version 7.1.13

Screenshots
<img width="1238" alt="Screenshot 2020-04-06 at 5 23 26 PM" src="https://user-images.githubusercontent.com/25850676/78555885-8fd13200-782b-11ea-837a-922a2892a391.png">

**Comment by codebytere** [comment]
@twitharshil could you please provide a more specific repro? I followed the above steps and did not experience an error.

**Comment by twitharshil** [comment]
@codebytere There are no specific reproduce steps for this I have used `app.moveToapplicationfolder()` inside the application, this seems like an issue on a specific MAC platform. I could able to reproduce this issue on my system using the Electron distributed binaries for version 5.0, 6.0 and 7.0. I could also reproduce this issue on other applications which are using electron v7.1.11. (Skype)

**Comment by codebytere** [comment]
@twitharshil the screenshot does not include the actual crash info, which we would need at minimum to try and look into this.

**Comment by twitharshil** [comment]
@codebytere 
[Crash_Dump_electron.zip](https://github.com/electron/electron/files/4490904/Electron_2020-04-17-095842_Harshils-MacBook-Pro.crash.zip)

**Comment by appinteractive** [comment]
Some problem here!

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.

**Comment by cyrus2281** [comment]
I had the same issue with electron version `22.0.0`. 
Fixed it by manually closing and reopening the app.
```javascript
app.moveToApplicationsFolder()
app.relaunch()
app.exit()
```
