### ISSUE TITLE
It's possible for window.open to never resolve, hanging the window that called window.open

### ISSUE THREAD

**Issue by carterbs** [electron/electron#22972]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.2
* **Operating System:**
  * Windows 10 (1903). Saw it on windows 7 as well. 
* **Last Known Working Electron version:**
  * Unsure

### Expected Behavior
window.open should always resolve.

### Actual Behavior
Ocassionally, window.open will not resolve. It hangs the parent window and child windows.

### To Reproduce
https://gist.github.com/carterbs/43adfc4796358fb1e17f32e529896ebd

### Screenshots
Logs. Note that Window opened 40 is not logged.
![image](https://user-images.githubusercontent.com/16466430/78576318-7f549380-77fa-11ea-917b-035d65a12cbd.png)
Here's another screenshot where it failed at window 11.
![image](https://user-images.githubusercontent.com/16466430/78576402-9c896200-77fa-11ea-879a-c273f160c494.png)

### Additional Information
1. The failure may take a while. Here are a sample of failures.
* After 54 windows
* After 49 windows
* After 11 windows
* After 63 windows
* After 190 windows
* After 459 windows
2. I had to use a VM with 4GB of RAM and 2 cores to get the bug to produce. 
3. I had to have a large preload to get the bug to reproduce.

The gist above is contrived, but we had this happen with a user just playing around with react portals, which uses window.open. 

I'm wondering if this bug is related to this one: https://github.com/electron/electron/issues/20086

**Comment by carterbs** [comment]
@sofianguy Does this getting put into unsorted issues mean "We aren't going to fix it"? Or does it mean "It will be sorted and looked at and may or may not get fixed"? If I knew more, I'd go in and try to fix it. But I don't even know where to start.

**Comment by nornagon** [comment]
@carterbs can you try on a more recent version of Electron? 7.1.x is an older release line and hasn't been getting updates in a while. Try 7.2.x or 8.x ideally!
