### ISSUE TITLE
DevTools failed to parse SourceMap: http://aaa.server.com/javascripts/touch.min.js.map

### ISSUE THREAD

**Issue by liangzhuang327** [electron/electron#22996]
in electron，load the server page 
`mainWindow.loadURL(`http://aaa.server.com/login`);`
in devtools:
DevTools failed to parse SourceMap:http://aaa.server.com/javascripts/touch.min.js.map;

I access http://aaa.server.com/javascripts/touch.min.js.map without a problem, but i'm warned when the browser loads this file: DevTools failed to parse SourceMap: http://aaa.server.com/javascripts/touch.min.map;
So, I can't use the sourcemap feature.

Is my configuration wrong?

Electron: 4.0.4 ;
electron-builder: 20.15.1;

**Comment by Strangerxxx** [comment]
The same is for me with Electron 8.2.1, electron-builder 22.4.1 and electron-packager 14.2.1

**Comment by liangzhuang327** [comment]
> in electron，load the server page
> `mainWindow.loadURL(`[http://aaa.server.com/login`);`](http://aaa.server.com/login%60);%60)
> in devtools:
> DevTools failed to parse SourceMap:http://aaa.server.com/javascripts/touch.min.js.map;
> 
> I access http://aaa.server.com/javascripts/touch.min.js.map without a problem, but i'm warned when the browser loads this file: DevTools failed to parse SourceMap: http://aaa.server.com/javascripts/touch.min.map;
> So, I can't use the sourcemap feature.
> 
> Is my configuration wrong?

Electron: 4.0.4 ;
electron-builder: 20.15.1;

**Comment by Strangerxxx** [comment]
It could be also connected to in which order you've called BrowserWindow.webContents.loadURL() and BrowserWindow.webContents.openDevTools()
Seems like if you're initializing openDevTools after complete of loadURL it could not render sourceMaps
Could you please check if you have any entities at Network tab of devtools or not? It may also be related

**Comment by liangzhuang327** [comment]
I try 
`if (isDevelopment) {
    mainWindow.webContents.on('devtools-opened', () => {
        mainWindow.loadURL(...)
    }
} else {
    mainWindow.loadURL(...)
}`  and other ways in [2379](https://github.com/electron/electron/issues/2379). it's not work

**Comment by lekoaf** [comment]
Same issue here.

Get spammed by a couple of hundred `DevTools failed to parse SourceMap`.

Electron 8.2.0.

Started after we upgraded to 8+.

**Comment by wilkerlucio** [comment]
Having same issue here, trie electron `8.3.1` and `9.0.1`

**Comment by robsonkades** [comment]
same problem with electron ^9.0.4

`DevTools failed to load SourceMap: Could not load content for file:///C:/Users/robson.kades/Downloads/electron-background-processing/src/abstract.js.map: `

`    "electron": "^9.0.4",
    "electron-builder": "^22.7.0",
    "electron-rebuild": "^1.11.0",`
`

**Comment by kidsonfilms-python-rules** [comment]
@robsonkades  Same with electron ^9.0.5
```
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/robson.kades/Downloads/electron-background-processing/src/abstract.js.map:

electron": "^9.0.5", "electron-builder": "^22.7.0", "electron-rebuild": "^1.11.0",

**Comment by kidsonfilms-python-rules** [comment]
I think I may have a workable solution (it worked in my case but maybe different to you). Follow the following steps.

**WARNING: This will not work if the URL in the error message is not in your local machine e.g. file:///... will work but not** **example.co/... **

1. **Check your Error Message:** Your error message tells you which package is missing. So in my case, my error was:
```
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/username/Desktop/StockX/underscore.js.map:
```
The error says it can't find **underscore.js.map** which then you find the missing package on npm

2. **Install the Missing Package:** Now you find your package on [npmjs.com](npmjs.com) (mine was [Underscore](https://www.npmjs.com/package/underscore), @liangzhuang327 's missing package is [touch](https://www.npmjs.com/package/touch)) and you run `npm install {PACKAGE}`

3. **Find and Copy the File to its Final Location:** Now go to the `node_modules` folder and go to the package's (the one you just installed) corresponding folder. Your final operating path should be
```
{PROJECT_ROOT}
| node_modules
| | {PACKAGE}
```
You should now find the missing file in your error (mine is underscore.js.map, @liangzhuang327 's is touch.min.js.map) and copy it over to where the error is trying to find it (if it's trying to find it somewhere other than your local computer, this fix won't work) which in my case is the project root folder.

4. **Rinse and repeat for every error of this kind you have** (my case 2 separate errors)

and you're done!

**Comment by lekoaf** [comment]
@kidsonfilms-python-rules this may be a workable solution for you. I have, what seems to be, hundreds of files missing. And it's not a "physical" location.

DevTools failed to parse SourceMap: webpack:///<path>/node_modules/apollo-cache/lib/bundle.esm.js.map

**Comment by lekoaf** [comment]
I "solve" it for now by writing `-DevTools` in the console filter input to remove them.

**Comment by kidsonfilms-python-rules** [comment]
@lekoaf well my solution worked for me but, it might not work for all so your solution is a great backup until github fixes this issue

**Comment by lekoaf** [comment]
This may be a Chrome bug, introduced in Chrome 80.
https://bugs.chromium.org/p/chromium/issues/detail?id=1052872

**Comment by chm-dev** [comment]
You can disable sourcemaps for JS in DevTools from the command palette:

Ctrl+Shift+P  -> Disable JavaScript source maps.
![image](https://user-images.githubusercontent.com/11930016/90323565-2bee1100-df63-11ea-8db8-ab01353a35c9.png)

Not ideal but worked best for me.

**Comment by bdurrer** [comment]
> You can disable sourcemaps for JS in DevTools from the command palette:

The message really isn't the problem. Without sourcemaps you can't really debug, tools like react inspector and redux dev tools won't work. We are back in the days of IE thanks to this issue

**Comment by shrinktofit** [comment]
I have the same problem when load source map from renderer process.

As a result I found that electron incorrectly resolve the `sourceMappingURL` **based on the web page origin**(where the `<script>` is attached) if you `require()` the script instead of using `document.createElement`.

**Comment by parliament718** [comment]
This is still a problem with latest versions of everything :( 
Node: v12.18.3   Chrome: 88.0.4324.96  Electron 11.2.2

**Comment by geigerzaehler** [comment]
I was able to work around this issue by [disabling asar](https://www.electron.build/configuration/configuration#overridable-per-platform-options) in the electron-builder configuration. After this my source maps were properly loaded.

**Comment by dhanyn10** [comment]
not solved yet?

**Comment by GiancarlosIO** [comment]
😭

**Comment by arthurpankiewicz** [comment]
bump

**Comment by jacobkim9881** [comment]
@kidsonfilms-python-rules For me it worked. Thanks!

**Comment by Awendel** [comment]
can confirm this is still an issue in the latest release.
when using ts modules & preload it seems to search for sourcemap in directory relative to html file root, instead of the importet script

**Comment by pcafstockf** [comment]
@Awendel does your comment about "preload" and source maps indicate that you are able to use a debugger on the preload script itself?
If so, I would very much appreciate you adding some detail to this issue #30470 which is attempting to collect information as to how (or even if) preload scripts can be debugged.

**Comment by Awendel** [comment]
@pcafstockf 
Not sure what you mean by debugger, but console.log used in my scripts point to the correct line in my original typescript file. But that's about as much debugging as I do. Since I only use ES6 Modules, I don't really do any global debuggin of variables or anything like that.
It does indeed work though with inline sourcemaps & preload script. Happy to post my tsconfig / webPreferences if that helps.

**Comment by pcafstockf** [comment]
@Awendel 
I was hoping you had found a way to use Electron's DevTools to actually set breakpoints and step through code in the preload script.  
However, thank you for the fast response.
I can also confirm that console.log does indeed report the correct line if you have inline source maps properly configured in a preload script.

**Comment by gpetrov** [comment]
bump, this still happens

**Comment by dominic-simplan** [comment]
bump

**Comment by slugb0t** [comment]
Was this ever resolved?

**Comment by lucassilvas1** [comment]
> Was this ever resolved?

Nope.

**Comment by gpetrov** [comment]
Still a problem

**Comment by dhanyn10** [comment]
bump

**Comment by i-lq** [comment]
Is there really no solution yet? My app is not working because of this bug

**Comment by TravisBumgarner** [comment]
Bump

**Comment by stephane-segning** [comment]
Bump

**Comment by aprilandjan** [comment]
Still a problem. Quite annoying indeed.

**Comment by Kallenju** [comment]
Bump
