### ISSUE TITLE
Non Paged Printing and PDF Generation

### ISSUE THREAD

**Issue by francoislaberge** [electron/electron#2300]
hi,

I've been curious to see what kind of design tools you could make using electron. Think vector graphics editing with easy printing support. I'd love to be able to print large posters and such using visuals generated using dom/svg/canvas elements. It seems that printing can only be paged. Is there something I'm missing?

/cc @hokein 

Thanks in advance,
Francois

**Comment by hokein** [comment]
Chromium doesn't support this right now. The print feature is borrowed from Chromium, so Electron won't support it unless Chromium does.

**Comment by francoislaberge** [comment]
That's what I figured. Thanks for confirming. Would be so cool if we could use HTML for large data visualization posters, flow charts, etc. It is what it is.

**Comment by Godisemo** [comment]
This is related to the pull request #2338.

**Comment by zcbenz** [comment]
I'm closing this since it is actually a feature request for Chromium, and we are not able to fix it on Electron's side alone, plus we now support setting arbitrary page size.
