### ISSUE TITLE
Menu bar is shown while `setMenuBarVisibility(false)`

### ISSUE THREAD

**Issue by cln650** [electron/electron#23026]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  9.0.0-beta.14
* **Operating System:**
 Windows 10
* **Last Known Working Electron version:**
  8.2.1

### Expected Behavior
Setting `win.setMenuBarVisibility(false)` will hide the menu bar. 

### Actual Behavior
Menu bar is shown

### To Reproduce
```
    let win = new BrowserWindow({
        width: 800,
        height: 600,
        webPreferences: {
            preload: path.resolve(__dirname, '../renderer/renderer-preload.js'),
            plugins: true,
            webviewTag: true,
            devTools: debugMode,
        },
    });
    win.setMenuBarVisibility(false); // or     win.removeMenu();
```

### Additional Information
* If I set ` autoHideMenuBar: true` it disappears but it appears when you pres `alt` key.
* If I set `frame: false` it disappears

**Comment by vladimiry** [comment]
This issue was placed in the tracker many times before. Got fixed, and then appeared again, and again. Just a note.
