### ISSUE TITLE
mac set window full-screen ,  content area zooming in is not smooth

### ISSUE THREAD

**Issue by Gaitin** [electron/electron#23028]
### Issue Details

* **Electron Version: 5.0 6.0 7.0 8.0**
* **Operating System: mac**
* **Last Known Working Electron version: 4.2.12**

### Expected Behavior

Mac set window full-screen  smooth
### Actual Behavior
mac set window full-screen, content area zooming in is not smooth

### [Screenshots]
[![gifhome-635x349-1.gif](https://i.postimg.cc/6QDfp4bk/gifhome-635x349-1.gif)](https://postimg.cc/5HSCPyVg)

### Additional Information

The html content area is only in the upper left corner, and suddenly becomes larger after zooming, triggering only one resize

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

**Comment by Gaitin** [comment]
> Thank you for taking the time to report this issue and helping to make Electron better.
> 
> Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?
> 
> Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
@sofianguy 
I've tried it in an empty project, and it's a must-see, you can try adding a border to the html and trying to zoom in on the window. try to use win.setFullScreen (flag)

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
