### ISSUE TITLE
Click-through frameless and transparent window not supported on versions > 6.1.9

### ISSUE THREAD

**Issue by glawson** [electron/electron#23042]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.1
* **Operating System:**
  * macOS 10.15.3
* **Last Known Working Electron version:**
  * 6.1.9

### Expected Behavior
Note: this is related to #1335.  However, that issue offers many solutions and workarounds.  This distorts the central issue, frameless transparent windows no longer allow click through.

Up to version 6.1.9, a window could be set with the options, frame: false, transparent: true.  If you set the bounds of the window to the full width / height of the display, and set the body background color to transparent of the renderer page and set the window on top, you could click-though to any OS window behind it.  Our application uses an element within the frameless transparent window that the end user interacts with.  This is possible up to version 6.1.9.

Illustrated in the Electron Fiddle gist - https://gist.github.com/glawson/63bfdbca42e2b482a3385ad101a8e1d3.

### Actual Behavior
You can no longer click-though frameless transparent windows unless you set setIgnoreMouseEvents, but that applies to the whole window.  If you need to interact with a part of the window, you have to change setIgnoreMouseEvents false over that element.  There is the 'forwarding' option, but it is only available on Windows OS - https://www.electronjs.org/docs/api/frameless-window#forwarding.  If run on macOS, there is no way to toggle setIgnoreMouseEvents when over the element you need user interaction. 

### To Reproduce
Electron Fiddle gist - https://gist.github.com/glawson/63bfdbca42e2b482a3385ad101a8e1d3.  run with version 6.1.9 to show expected click-through, change to 8.2.1 to show break. 

### Screenshots
https://www.loom.com/share/581466825f924c68863ca06e9996293b

**Comment by sofianguy** [comment]
@glawson tried on E9 and it's also broken there

**Comment by zcbenz** [comment]
I have looked into this and I realized that we do not actually support click-through transparent window. The old behavior was accidentally supported by Chromium from some version, and then accidentally dropped by Chromium later.

So unless someone is willing to find out exactly how to make it work, we are unable to "fix" this issue.

**Comment by glawson** [comment]
@zcbenz - do you have any suggestions on who might be interested in looking into this further?

**Comment by zcbenz** [comment]
I don't know anyone who is interested in working on this feature, and since we never officially supported it before, I prefer to close this as won't fix.

**Comment by toonvanvr** [comment]
@glawson Can you check out whether [this demo](https://github.com/toonvanvr/electron-transparency-demo) supports the functionality you want?

I'm trying to figure out which bugs still exist cross-platform to update my outdated electron-transparency-mouse-fix npm package. Feel free to open an issue per bug on the demo repository.

**Comment by glawson** [comment]
@toonvanvr - I tested on macOS 10.15 and Windows 10.  At first glance it looks very promising 🎉.  I did have some 'issues' related to dragging on Windows where the cursor took on the behavior of the app/window it was over.  I'll create an issue for that on your demo repo.  I'll also do some more testing in the next few days with different macOS versions.

**Comment by sapkra** [comment]
@glawson What is your final solution? Are you still stuck with 6.x or have you been able to fix this cursor problem? I have currently the same problem.

**Comment by glawson** [comment]
> @glawson What is your final solution? Are you still stuck with 6.x or have you been able to fix this cursor problem? I have currently the same problem.

@sapkra - sorry for the late response.  I'm not longer with the company that this issue originated from so I'm not sure of the status.  @paulius005 might be able to update you with any other details.

**Comment by paulius005** [comment]
@sapkra We are about to be more actively looking into what the best paths forward here are and will update this thread accordingly

**Comment by sapkra** [comment]
I'm glad to hear that. I am looking forward to a solution, also because this is the third most requested feature for electron.

**Comment by paulius005** [comment]
Updated example repo here: https://github.com/loomhq/electron-quick-start

And demo of the issue here: https://www.loom.com/share/78d2ae36da7e4ad38308d03ae001d27b

**Comment by sapkra** [comment]
I think it's more likely a change in chromium instead of electron itself. There were some commits which are applying backported chromium fixes. The problem must be within one of the commits between electron 7.0.0-beta.4 and 7.0.0-beta.5 which includes #20062.

https://github.com/electron/electron/commits/v7.0.0-beta.5

v7.0.0-beta.4 is the last version which is working fine.

**Comment by paulius005** [comment]
Update! We've found a workaround by creating a native module and changing some of the native window properties within the operating system. 

One issue remains for us is that once there is a video element on the screen the functionality goes away again

Video demo: https://www.loom.com/share/8f5cc5a0328244a9a5fd7c44833ea43b

sample repo coming soon :)

**Comment by sapkra** [comment]
Interesting! We are using a video element in our overlay too - I'm very interested in looking into it but at the end it still is a workaround and it has to be fixed properly.

**Comment by sapkra** [comment]
@paulatbipsync Do you have any updates on this? Can you share the sample repo please?

**Comment by paulius005** [comment]
We should be publishing a repo soon :)

**Comment by gchilds** [comment]
@sapkra @paulius005 here's our repo that fixes mac transparent click through for us on post electron-6 versions:

https://github.com/loomhq/ElectronMacOSClickThrough

**Comment by sapkra** [comment]
Great job! It even works with an video element now.

**Comment by gchilds** [comment]
> Great job! It even works with an video element now.

Woohoo! Sorry about the weird API, it just grew that way. I hope to fix it at some point.

**Comment by sapkra** [comment]
Are you going to publish it on npm?

**Comment by gchilds** [comment]
> Are you going to publish it on npm?

That sounds like a good idea! This is my first package / add-on.

**Comment by gchilds** [comment]
@sapkra Here it is on npm: https://www.npmjs.com/package/@loomhq/electron-click-through-workaround

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!

**Comment by OwnageBanana** [comment]
> @sapkra Here it is on npm: https://www.npmjs.com/package/@loomhq/electron-click-through-workaround

This is great of you putting this together! Though I'm getting an exception on load that the module did not self register. I'm not well versed in how this could be happening.

that given, I'm on:

electron "12.0.3" 

I followed what steps I expected:

npm i @loomhq/electron-click-through-workaround

and in initializing my window :
```
const patch = require('@loomhq/electron-click-through-workaround');
patch.InstallClickThroughPatch()
const win = new BrowserWindow({  ....  });
patch.MakeWindowIgnoreMouseEvents(win.getNativeWindowHandle())
```

and the expected did not happen 😄 and I recieved this following error

```
Apr 16 2021 10:50:51 GMT-0300 ERROR: Error: Module did not self-register: '\\?\C:\Users\Adam\repos\desktop\node_modules\@loomhq\electron-click-through-workaround\build\Release\electronClickThroughWorkAround.node'.
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at bindings (C:\Users\Adam\repos\desktop\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\Users\Adam\repos\desktop\node_modules\@loomhq\electron-click-through-workaround\main.js:1:37)
    ```
    
    Any help in this regard is much appreicated!

**Comment by gchilds** [comment]
This is a Mac only add on. If you know how to conditionalise it a PR would be appreciated.

**Comment by sapkra** [comment]
I already create a PR which improves the docs including a platform condition.

https://github.com/loomhq/ElectronMacOSClickThrough/pull/1

**Comment by gchilds** [comment]
Thank you @sapkra!
