### ISSUE TITLE
Cannot use emojis (even in unicode) with webContents.sendInputEvent

### ISSUE THREAD

**Issue by iwiedenm** [electron/electron#23052]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.1 (present in earlier versions as well)
* **Operating System:**
  * all
* **Last Known Working Electron version:**
  * n/a

### Expected Behavior
The following code should type 3 🐶in the input box

### Actual Behavior
The following gets typed: ``

### To Reproduce
Fiddle: https://gist.github.com/iwiedenm/a4826d0241c9f4e082f3e42f93b962aa
```
// Navigate to google or any other site with an input/textarea
webContents.loadURL('https://google.com')
.then(() => {
  // An array of characters that all become 🐶
  let charArray = ['🐶', '\u{1F436}', '\uD83D\uDC36']

  for (var i = 0; i < charArray.length; i++) {
    console.log('charArray[i]', charArray[i]);
    webContents.sendInputEvent({
      type: 'keyDown',
      keyCode: charArray[i],
    }, true);
    webContents.sendInputEvent({
      type: 'char',
      keyCode: charArray[i],
    }, true);
    webContents.sendInputEvent({
      type: 'keyUp',
      keyCode: charArray[i],
    }, true);
  }
})
```

**Comment by codebytere** [comment]
@iwiedenm the reason this is happening is that this method parses the `keyCode` into an [accelerator](https://github.com/electron/electron/blob/33ef0d23a66a6f9dd4b7bece071bfe0363bbf558/docs/api/accelerator.md#L1), which doesn't accept emojis at this point in time. I'll look into it a bit but it's likely that this isn't something we can fix or handle on our end, as it'd require significant code shift in accelerator logic.
