### ISSUE TITLE
The electron app cannot be awakened through the web

### ISSUE THREAD

**Issue by yaoyuanrong** [electron/electron#23051]
![d5761d9b92f2dbdcc11c7ba7eaaa649](https://user-images.githubusercontent.com/46862208/78859116-fbe8ab80-7a60-11ea-8e88-dbe6c6400a25.png)
![623748f246dde00e20636e4ed90c0c0](https://user-images.githubusercontent.com/46862208/78859119-fee39c00-7a60-11ea-9989-4466ff2f84b0.png)
Click the link on the web to report the appeal error

**Comment by codebytere** [comment]
Please add this to https://github.com/electron/electron/issues/23055.
