### ISSUE TITLE
通过web协议的方式打开electron应用报错

### ISSUE THREAD

**Issue by yaoyuanrong** [electron/electron#23056]
**Preflight Checklist**
[x ] I have read the Contributing Guidelines for this project.
[ x] I agree to follow the Code of Conduct that this project adheres to.
**Issue Details**
- Electron Version:
  8.2.1
- Operating System:
   window 10
- Last Known Working Electron version:
   Dont know.
**预期行为**
没有崩溃
**实际行为**
通过web唤醒electron的时候，electron应用报错：
Invalid package C:\Program Files (x86)\Google\Chrome\Application\81.0.4044.92\resources\app.asar
正常的情况下打包安装双击能够打开。

**Comment by codebytere** [comment]
duplicate https://github.com/electron/electron/issues/23055
