### ISSUE TITLE
CodeJudge Unknown issue

### ISSUE THREAD

**Issue by niteshkumardutt** [electron/electron#23072]
![Untitled](https://user-images.githubusercontent.com/25803530/78989883-7d6c3680-7b52-11ea-98f7-1d7157c091bd.png)

I am not able to use this tool. I have attached the screenshot of the issue.
After filling the fields once i click on start button it gives unknown error.
That error message is not specific like exactly what is the issue?.Is it a system
side issue or this tool is having problem?

please check the issue.

**Comment by MarshallOfSound** [comment]
This appears to be an issue with codejudge not with Electron itself, please report this to codejudge not to us
