### ISSUE TITLE
The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /nix/store/lzblq49adyvx6j25ynh2ajjs5ixc4yii-electron-8.1.1/lib/electron/chrome-sandbox is owned by root and has mode 4755

### ISSUE THREAD

**Issue by disassembler** [electron/electron#23074]
The sandbox check should ensure permissions are at least a certain security level. In this case it's failing because chrome-sandbox isn't writable by owner, but all my binaries in the nix store have no write permission.

### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
* **Operating System:**
  * 
* **Last Known Working Electron version:**
  *

**Comment by disassembler** [comment]
After discussing with a colleague, this won't work anyways. Is there a way to make electron never run in a sandbox? In our use case we're already running the application in a kernel user namespace, so a sandbox inside a user namespace doesn't add any additional security.

**Comment by vladimiry** [comment]
> Is there a way to make electron never run in a sandbox

Add `--no-sandbox` CLI arg.
