### ISSUE TITLE
worker_thread works in development with Electron command but failed in production when it published

### ISSUE THREAD

**Issue by yl1215** [electron/electron#23078]
OS: macos 10.13.6
electron version: 7.1.10

Expect: 
thread_worker run himself and then exit
Actually：
thread triggered 'exit' event quickly and run nothing actually.

but it run successful in development with Electron ./path,  i spend a lot of time to find the answer, but failed. Maybe we just do not support that in production?

**Comment by MarshallOfSound** [comment]
You are probably running into issues with path resolution to your worker script.  Log it out and ensure you are correctly pointing at your packaged worker script.  Also ensure it is not in an ASAR file as `worker_threads` is not compatible with ASAR

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

**Comment by kaatt** [comment]
This behavior should be noted in the docs. I read about worker_threads on https://www.electronjs.org/docs/tutorial/performance and wasted a few hours debugging this. 

cc @22446
