### ISSUE TITLE
When AppData does not have write permission, the installation cannot be completed on windows.

### ISSUE THREAD

**Issue by plusor** [electron/electron#23086]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.2.1
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 8.1.1

### Expected Behavior
Throw an exception.

### Actual Behavior
The installation proces always pending.

### Screenshots
<img width="628" alt="截屏2020-04-13下午2 52 52" src="https://user-images.githubusercontent.com/659346/79099341-79305b00-7d96-11ea-894a-261f887f2ca0.png">

**Comment by codebytere** [comment]
While you have technically filled out the template, the steps provided here are very unclear and as such we cannot proceed. Please provide us with more information about circumstances surrounding the issue as well as a way to reproduce it.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by plusor** [comment]
@codebytere Can you try again by setting the AppData directory to read-only permission?  I don't know why the user has no permission to write to the AppData directory, maybe the current user is not in the admin role.

**Comment by codebytere** [comment]
@plusor this does not address my requests in my above comment, please address them in order to for us to triage this issue.

**Comment by plusor** [comment]
https://github.com/electron-userland/electron-builder/issues/4092
