### ISSUE TITLE
Error "Unable to deserialize cloned data due to invalid or unsupported version" when call remote objects

### ISSUE THREAD

**Issue by abnerlee** [electron/electron#23080]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.1 (also in 8.1.1)
* **Operating System:**
  * macOS 10.15.3 and Windows 10
* **Last Known Working Electron version:**
  * 6.x.x

When I call any object in `remote`, for example `require("electron").remote.app` or `require("electron").remote.getCurrentWindow()` in render process, it will throw error
```
// require("electron").remote.app
ipc-renderer-internal.ts:13 Uncaught Error: Unable to deserialize cloned data due to invalid or unsupported version.
    at EventEmitter../lib/renderer/ipc-renderer-internal.ts.exports.ipcRendererInternal.sendSync (ipc-renderer-internal.ts:13)
    at Object../lib/renderer/api/remote.js.exports.getBuiltin (remote.js:309)
    at Object.get (remote.js:354)
    at <anonymous>:1:27

// require("electron").remote.getCurrentWindow()
ipc-renderer-internal.ts:13 Uncaught Error: Unable to deserialize cloned data due to invalid or unsupported version.
    at EventEmitter../lib/renderer/ipc-renderer-internal.ts.exports.ipcRendererInternal.sendSync (ipc-renderer-internal.ts:13)
    at Object../lib/renderer/api/remote.js.exports.getCurrentWindow (remote.js:315)
    at <anonymous>:1:28
```

### Additional Information
I already set enableRemoteModule to `true`, also, when this error throws, I won't get promise callback when calling `ipcRender.invoke`.

This error does not always happen, so any help / suggestions about how to fix it?

https://stackoverflow.com/questions/60683076/electron-error-unable-to-deserialize-cloned-data-due-to-invalid-or-unsupported seems also related.

**Comment by vladimiry** [comment]
See https://www.electronjs.org/docs/breaking-changes. Structured clone algorithm is also used in the remote module despite not being mentioned in breaking changes, see https://github.com/electron/electron/pull/20427.

**Comment by abnerlee** [comment]
@vladimiry Thanks.

I'm facing the error when I call electron's build-in objects for functions from `require("electron").remote`, they should not cover doms or functions

**Comment by pushkin-** [comment]
I also get this error sometimes when opening windows (via window.open)

**Comment by nornagon** [comment]
@vladimiry i don't think this issue is related to the breaking change, it seems like a separate bug.

**Comment by DigitalCyan** [comment]
For some reason sending back return data from the main process fixed it for me.

For example in main.js I did:
`ipcMain.on("foo", (e) => {
  console.log("bar");
  e.returnValue = 0;
});`

**Comment by nornagon** [comment]
I'm not able to reproduce this. Here's the code I was trying: https://gist.github.com/fb61b12864247fe8163f42c4b22891c8

@abnerlee if you can manage to reproduce this with a Fiddle or small repo based on [electron-quick-start](https://github.com/electron/electron-quick-start), that would be helpful in diagnosing the issue!

**Comment by abnerlee** [comment]
@nornagon I reproduced this on a "invoke" a function that returns `Promise` but won't resolve it.

```
// main
ipc.handle("test", () => {
  return new Promise((resolve) => {
   console.log("test");
  });
});
```

```
// render
ipc.invoke("test").then((res) => {
  console.log(res);
});
```

Some seconds after `ipc.invoke("test")`,  is called, the `remote.xxx` is not available.

**Comment by jackple** [comment]
I found that after changing hash history, this bug will always appear.

![image](https://user-images.githubusercontent.com/6183232/91551620-0b5b8900-e95d-11ea-900a-7bb27b6dec9e.png)
![image](https://user-images.githubusercontent.com/6183232/91551572-f67ef580-e95c-11ea-948a-e9abb6d7a4b0.png)
![image](https://user-images.githubusercontent.com/6183232/91551590-fda60380-e95c-11ea-912e-4c5e9ae97a31.png)

**Comment by a7madgamal** [comment]
so how can I debug this when I have it in my console?

**Comment by ckerr** [comment]
If I'm reading the comments correctly, this issue has been diagnosed as app code that's doing unsupported behavior. As such, this isn't an Electron bug so much as it is something that needs to be changed in app code and discussion on how best to do that.

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
