### ISSUE TITLE
File Dialog Crashing Electron with Segfault - Ubuntu 18.04

### ISSUE THREAD

**Issue by richlanc** [electron/electron#23105]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
```
10.0.0-nightly.20200327 < GTK dialog does open, crashes after dialog closes
10.0.0-nightly.20200326 < GTK dialog doesn't open, crashes after multiple button clicks
10.0.0-nightly.20200325 < GTK dialog doesn't open, crashes after multiple button clicks
10.0.0-nightly.20200324 < GTK dialog doesn't open, crashes after multiple button clicks
10.0.0-nightly.20200323 < GTK dialog doesn't open, crashes after multiple button clicks
10.0.0-nightly.20200320 < GTK dialog doesn't open, crashes after multiple button clicks
10.0.0-nightly.20200317 < GTK dialog doesn't open, crashes after multiple button clicks
10.0.0-nightly.20200310 < Working as expected
```
* **Operating System:**
Ubuntu 18.04 x64
* **Last Known Working Electron version:**

### Expected Behavior

I expect to be able to use the GTK FileChooser to upload/download files.

### Actual Behavior

From nightly version `10.0.0-nightly.20200317` the electron window closes without showing the file GTK FileChooser and reports a SEGFAULT in the terminal window. 

From nightly version `10.0.0-nightly.20200327` the GTK FileChooser opens, but after opening a file or cancelling, the electron window exits and reports a SEGFAULT in the terminal window.

### To Reproduce

`electron  http://jsfiddle.net/lovlka/N4Jxk/`

**Comment by nornagon** [comment]
I suspect #22531 might be the cause of this one.
