### ISSUE TITLE
Can't set Referer header

### ISSUE THREAD

**Issue by sd-soleaio** [electron/electron#23102]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.1
* **Operating System:**
  * macOS 10.14.6

### Expected Behavior
The Referer header should be able to be set on ClientRequest objects via request.setHeader(name, value).

### Actual Behavior
Referer header isn't being set at all (headers can be viewed by using a proxy like Charles or Fiddler).

### To Reproduce
```const { app } = require('electron')
app.on('ready', () => {
  const { net } = require('electron')
  const request = net.request('https://github.com')
  request.on('response', (response) => {
    console.log(response.statusCode})
    console.log(JSON.stringify(response.headers))
    response.on('data', (chunk) => {
      console.log(chunk)
    })
    response.on('end', () => {
      console.log('No more data in response.')
    })
  })

  # this referer header should be set
  request.setHeader('referer', 'https://github.com')

  request.end()
})
```

### Additional Information
There does seem to be a Referrer property on the request that can be seen when using webRequest.onBeforeRequest but as far as I can see it's always empty and cannot be modified.

Being able to set the referer header is a basic and fundamental requirement for working with some websites, would be great if this issue could be fixed.

Massively appreciate all the developers taking the time working and updating this project.

**Comment by theyezzyman** [comment]
Electron team fix this sh*t so bots can eat

We need that referer header to cook :(

**Comment by LuoJinghua** [comment]
We got this problem too which is blocking our product from working.

**Comment by LuoJinghua** [comment]
The referer of details is blank, is there any way to set this property for the request?

**Comment by jjason685** [comment]
+1

**Comment by mitchdavies** [comment]
+1

**Comment by walmat** [comment]
Seems to be fixed in v8.x.x and up. v7 broke a lot of functionality with `net` that this was more than likely related to.

**Comment by nornagon** [comment]
Closing as this is fixed in 8.x. v7 is receiving security fixes only.
