### ISSUE TITLE
Maximize and unmaximize do not truly do the process how normal applications do it.

### ISSUE THREAD

**Issue by Stanlyhalo** [electron/electron#23113]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.2
* **Operating System:**
  * Windows 10 (build 18362)
* **Last Known Working Electron version:**
  * 7.1.12

### Expected Behavior
My code is suppose to close, maximize (and unmaximize), and minimize.

### Actual Behavior
Both close and minimize works, but maximize button maximizes it, but at the same time, sets the new width, height, x, and y to the new maximize, so when I unmaximize, it just stays where it is until I use the drag bar. Also when in maximize, I can drag it as if it wasn't maximized and was just sized up to be the size of the screen.

### To Reproduce
1) Install electron.
2) Setup basic electron with HTML.
3) Make 3 buttons with the following code
```javascript
var { remote } = require('electron');

btnClose.addEventListener("click", function(e) {        
    var win = remote.getCurrentWindow();
    win.close();
});
btnMax.addEventListener("click", function(e) {
    var win = remote.getCurrentWindow();
    if(win.isMaximized()){
        win.unmaximize();
    }else{
        win.maximize();
    }
});
btnMin.addEventListener("click", function(e) {
    var win = remote.getCurrentWindow();
    win.minimize();
});
```

**Comment by Stanlyhalo** [comment]
I did some debugging, and it appears that win.isMaximized() always returns false.

**Comment by codebytere** [comment]
@Stanlyhalo could you please provide a more thorough repro? for example, transparent window is not specified in yours above, so we might be able to replicate your error conditions properly.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
