### ISSUE TITLE
Selecting a folder from an input element selects files recursively instead

### ISSUE THREAD

**Issue by Keagel** [electron/electron#23123]
# Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v7.0.0 to v9.0.0-beta.16
* **Operating System:**
  * Windows 10 (1903)
* **Last Known Working Electron version:**
  * v6.1.10

I have added an `<input type="file" webkitdirectory>` element in order to be able to select a folder.

### Expected Behavior

Folder gets selected.

### Actual Behavior

Instead of the folder being selected, it selects every single file recursively starting from the selected folder. If there are too many files, the app hangs and crashes.

#### Electron Fiddle gists

v9.0.0-beta.16 - https://gist.github.com/cd6be0d11dcbb5053a7dba42b29abc6d
v7.0.0 - https://gist.github.com/e4968d390c6a8fa83cbe3c67a4da6431
v6.1.10 - https://gist.github.com/b9f404b3b2050afd4425abd5716acc83

### Screenshots

What should happen:

![electron_2020-04-15_19-21-44](https://user-images.githubusercontent.com/18720666/79367895-df5fde00-7f4e-11ea-84db-8d174f1714c6.png)

What happens:

![electron_2020-04-15_19-22-45](https://user-images.githubusercontent.com/18720666/79367931-ec7ccd00-7f4e-11ea-8386-98b487250cf7.png)

### Additional Information

This might be linked to #20380 but this is happening even running from the command line. Not using VS code. I haven't tested every single version but I have tested around 15 from v7.0.0 to v9.0.0-beta.16. This is present in all v8 versions too.

**Comment by nornagon** [comment]
This is listed in the breaking changes for v7: https://www.electronjs.org/docs/breaking-changes#behavior-changed-webkitdirectory-attribute-for-input-typefile-now-lists-directory-contents

**Comment by Keagel** [comment]
You're right, I assumed the correct behavior was selecting the folder and not its content since it's been working this way for so long.
