### ISSUE TITLE
Crash reporting on Linux is incompatible with sandbox

### ISSUE THREAD

**Issue by nornagon** [electron/electron#23124]
On Linux, Electron uses breakpad, as opposed to crashpad which is the crash reporting tool on macOS and Windows. Breakpad requires manually initializing the crash reporter in every process to be monitored, including renderers. Initializing the crash reporter in the renderer currently requires calling `crashReporter.start` from within the renderer, which can only be done from JavaScript. Initializing the crash reporter requires performing privileged operations, such as installing signal handlers and writing to the filesystem. Thus, when the crash reporter is initialized on Linux in the renderer process, if the sandbox is enabled, the renderer process crashes.

Chromium works around this by [enabling the crash reporter before the sandbox is initialized](https://source.chromium.org/chromium/chromium/src/+/master:chrome/app/chrome_main_delegate.cc;l=1067;drc=da6ef73266f6110abc5e788457f0e8f9257dd5b6). We'll need to do the same, which means the crash reporter will need to be initialized before JavaScript has the chance to run.

IMO, this is also a good thing for the API, because it would reduce the differences between the crash reporter API on Linux vs. macOS/Windows, and it would mean that `crashReporter` could become a main-process-only module. It is, however, a breaking change.

**Comment by deepak1556** [comment]
> that crashReporter could become a main-process-only module. It is, however, a breaking change.

💯 

This would also eliminate another subtle bug users can run into on windows, if you start the crash reporter in the render process before the crash reporter on browser process , you can mess up the connection pipe to crashpad client https://github.com/electron/electron/blob/master/shell/common/crash_reporter/crash_reporter_win.cc#L91
