### ISSUE TITLE
Iframe print to pdf.

### ISSUE THREAD

**Issue by suoc** [electron/electron#23120]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

Thanks all contributors for Electorn;

### Problem Description

I had a application that do print in an iframe, I want to implemanent a print preview by pdf, hope to add a method to print iframe to pdf.

**Comment by codebytere** [comment]
Given that there exist workarounds (printing from a `WebContents`), that this isn't currently on our roadmap, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR
