### ISSUE TITLE
Wrong types for `BrowserWindow#webContents#devToolsWebContents`

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#23132]
As of v8.2.2 the typescript types Electron ships with tell me that `BrowserWindow#webContents#devToolsWebContents` always exists, while in fact it  will be `null` if the devtools is not open, these sorts of type-level bugs can lead to hard to discover bugs.

**Comment by vladimiry** [comment]
> lead to hard to discover bugs

In other words it leads you down to the pure JavaScript world from the TS heaven :joy:
