### ISSUE TITLE
Local update location instead of an update server

### ISSUE THREAD

**Issue by ottogutierrez** [electron/electron#23131]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

It would be nice if there was support for having a local update location for apps that need to be distributed only locally with people within the same network (network disk location)

**Comment by MarshallOfSound** [comment]
The autoUpdater API supports receiving `file://` protocol "URLs"
