### ISSUE TITLE
trafficLightPosition causes traffic lights to disappear when starting app in fullscreen 

### ISSUE THREAD

**Issue by duriandummy** [electron/electron#23142]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.1.1
* **Operating System:**
  * macOS 10.15.3

### Expected Behavior
When starting the app in fullscreen, traffic lights should appear normally

### Actual Behavior
Traffic lights are not visible

### To Reproduce
Start app in full screen

**Comment by MarshallOfSound** [comment]
I tried to repro this with

```js
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    fullscreen: true,
    frame: false,
    titleBarStyle: 'hidden',
    trafficLightPosition: {
      x: 40,
      y: 40,
    },
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: true,
      preload: __dirname + '/renderer.js'
    }
  })
```

and everything looked normal to me.

When in full screen the custom traffic light position will not be applied as the "frame" is moved out of the window.  To view the traffic lights you need to move your mouse to the top of the screen like any other macOS application.
