### ISSUE TITLE
Cannot Inject CSS into multiple Webviews

### ISSUE THREAD

**Issue by KorbsStudio** [electron/electron#23158]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.4.3 >
* **Operating System:**
  * Windows and Linux(Debian)

### Expected Behavior
When setting up scripts to inject CSS to a webview, CSS in the webview is expected to change.
Along with other scripts that aim for their targeted webview element by ID.

### Actual Behavior
Only on webview gets CSS injected

### To Reproduce
The script I use is something I pulled off of [Stackoverflow](https://stackoverflow.com/questions/42930572/inject-css-into-webview-chrome-electron-html-css-js/42931151#42931151). 

So this would work:
```
<webview id="wv1" src="https://www.github.com/" style="display:inline-flex; width:100%; height:140px" nodeintegration></webview>

<script>
    var webview = document.getElementById('wv1');
    webview.addEventListener('dom-ready', function () {
        webview.insertCSS('html,body{ background-color: #FF0000 !important;}')
    });

</script>
```
But this won't work:
```
<webview id="wv1" src="https://www.github.com/" style="display:inline-flex; width:100%; height:140px" nodeintegration></webview>

<script>
    var webview = document.getElementById('wv1');
    webview.addEventListener('dom-ready', function () {
        webview.insertCSS('html,body{ background-color: #FF0000 !important;}')
    });

</script>

<webview id="wv2" src="https://www.korbsstudio.com/" style="display:inline-flex; width:100%; height:140px" nodeintegration></webview>

<script>
    var webview = document.getElementById('wv2');
    webview.addEventListener('dom-ready', function () {
        webview.insertCSS('html,body{ background-color: black !important;}')
    });

</script>
```

### Screenshots
![image](https://i.imgur.com/WG441N8.png)

**Comment by KorbsStudio** [comment]
oh god it happened again, working on another project, like...I really need this

**Comment by KorbsStudio** [comment]
This is a issue on all supported versions.

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by KorbsStudio** [comment]
Gist/Fiddle:
https://gist.github.com/c20fc0082aee0fec52e87fb0f14a9803

**Comment by nornagon** [comment]
@KorbsStudio Ah, sorry for the late reply, but it seems that gist link is 404 for me now. Would you mind re-uploading it?

**Comment by KorbsStudio** [comment]
No, you took long to look back.

**Comment by KorbsStudio** [comment]
I finally learned basics of `var` with `webview`:
```
webview = document.querySelector('webview')
var webview_1 = document.getElementById('webview_1');
var webview_2 = document.getElementById('webview_2');

function webview_1DV(){webview_1.openDevTools()}
function webview_2DV(){webview_2.openDevTools()}
```
So that's that
