### ISSUE TITLE
Restoring window from minimize will break keyboard accessibility

### ISSUE THREAD

**Issue by torycl** [electron/electron#23157]
When using keyboard navigation and screen readers in the Electron app, minimizing the window (win-m), and restoring (alt-tab) causes screen readers like NVDA or JAWS stop reading items in the window.

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * Reproduced in 4.2.12, 7.1.11, 8.0.2
* **Operating System:**
  * Windows 10 (1909)
* **Last Known Working Electron version:**
  * 3.1.13

### Expected Behavior
Screen readers continue reading the content when restoring the window from minimize.

### Actual Behavior
Screen readers stop reading the contents when using keyboard navigation after restoring.
Screen readers still read items under mouse or keystrokes. But do not read focused items when using tab key for navigation.

### To Reproduce
1. Have some rich app with many items and keyboard navigation support (tab keys, cursor keys). 
2. Use NVDA or JAWS screen reader.
3. Check it reads items properly as you walk over them using keyboard navigation.
4. Win-m to minimize items (do not use mouse).
5. Alt-tab to refocus the window (do not use mouse)
6. Try to tab over items again and listen to the screen reader if it still reads items properly
7. Not 100% percent reproducible. Try to minimize-restore several times

### Additional Information
* Bug can be workaround by forcibly repainting the window when restoring from minimize
* Related to https://chromium-review.googlesource.com/c/chromium/src/%2B/2088293 Using Chromium with this patch (82+) can fix the issue. This needs to be tested, I am not sure.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
