### ISSUE TITLE
Electron Notification API shows electron.app.<productName>

### ISSUE THREAD

**Issue by futurelucas4502** [electron/electron#23160]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  8.2.1
* **Operating System:**
  *  Windows 10 1909
* **Last Known Working Electron version:**
  *  Unknown

### Expected Behavior

For the Notification API to show the notification source as the "productName"

### Actual Behavior

The [experimental notification API](https://www.electronjs.org/docs/api/notification) displays notifications source as "electron.app.productName" instead of just "productName"
![image](https://user-images.githubusercontent.com/48055553/79692302-3e2d9c00-825c-11ea-87e8-ab8736448a1c.png)

### To Reproduce

```
const { Notification } = require('electron')
notification = new Notification({title: "Message from: Steve",body: messagebody,icon: "./icon.png"})
notification.show()
```
Simply any notification.show() (has to have an image or no source appears at all)

**Comment by nornagon** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

In particular, it's important for us to know in what version of Electron you've observed this behavior.

Thanks for understanding and meeting us half way :grinning:

**Comment by futurelucas4502** [comment]
Sorry I had pressed feature request instead of bug report I have filled out all additional info now :)

**Comment by MarshallOfSound** [comment]
That is your app user model ID.  In order for Windows to be able to translate that into an application name a shortcut to your application with your app user model ID in that shortcut's metadata needs to exist in the Start Menu of that machine.

See the [Windows](https://www.electronjs.org/docs/tutorial/notifications#windows) section of our notification tutorial

**Comment by futurelucas4502** [comment]
That's the notification module for notifications in the renderer not the [experimental notification API](https://www.electronjs.org/docs/api/notification) that runs in the main process which is what I'm having the problem with

**Comment by MarshallOfSound** [comment]
@futurelucas4502 It's the same requirement and same information, even the same code behind the scenes

**Comment by futurelucas4502** [comment]
@MarshallOfSound Ah okay could this then be added to the documentation for the notification API in the main process so this is more clear? 👍
