### ISSUE TITLE
SCCache race condition hampers *.debug file correctness

### ISSUE THREAD

**Issue by thypon** [electron/electron#23168]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * Tested on v10.0.0-nightly.20200408
* **Operating System:**
  * Linux any
* **Last Known Working Electron version:**
  * None

### Expected Behavior

Compile object output should be correct.
![Screen Shot 2020-04-19 at 22 51 23](https://user-images.githubusercontent.com/581115/79743804-86ed5f80-8305-11ea-8413-dc3583d7f4b4.jpg)

### Actual Behavior

While testing for Linux reproducibility I ran into an issue where build-id and debug link production section of Linux x64 binaries where randomic at each build.
![Screen Shot 2020-04-15 at 15 53 38](https://user-images.githubusercontent.com/581115/79743988-e3507f00-8305-11ea-97ec-a0255ef6cbb1.jpg)

Checking at the relative debug file I noted that `.strtab` and `.debug_str` sections where of different size. Checking inside it was clear some symbol was messed up, expecially the mojom ones. 
![Screen Shot 2020-04-16 at 13 49 41](https://user-images.githubusercontent.com/581115/79743678-4392f100-8305-11ea-871c-7b185df895d3.jpg)

Since it was not clear why this was happening I run `diffoscope` on the `out` directory. This revealed that some `.cc` object output where going in wrong `.o`.
![Screen Shot 2020-04-18 at 12 27 52](https://user-images.githubusercontent.com/581115/79743836-98366c00-8305-11ea-8a7b-3726823df4eb.jpg) . 
For example some `A.cc` was finishing in `B.cc` output `B.o`. So `B.o` was present twice, while `A.o` was never present in the final binary.

Since I did not know what was causing these files output to be messed up I runned multiple tests on filesystem/linker/sccache. I finally triaged the problem and it seems to be related to a newly discovered race condition in `sccache` on Linux platform.

This can be verified running a multiple builds with sccache disabled. In these case the output is not only deterministic, but it also have correct objects in correct locations. ![Screen Shot 2020-04-19 at 22 51 23](https://user-images.githubusercontent.com/581115/79743804-86ed5f80-8305-11ea-8413-dc3583d7f4b4.jpg)

Cc: @nornagon @ikkisoft @jkleinsc 

### To Reproduce

- Download https://github.com/electron/electron/blob/34a8e388fedc492d68ce00fcefd281871065f87c/script/reproducible/verify.sh
- create the directory `/home/builduser/project`
- run verify.sh script with `./verify.sh -b /home/builduser/project v10.0.0-nightly.20200408`
- run diffoscope with `--exclude-directory-metadata --text out.txt --html out.html` the directories /home/builduser/project/src/out/Default{,2}

Some files will have wrong `.o` output.

### Additional Information

This is the last issue we have on Linux platform to obtain reproducibility on all major platforms on electron (macOS, Windows, Linux). While this issue is affecting the reproducibility, incorrect sccache behaviour may affect strongly electron stability and hamper the ability use the crash reports the users are sending.

**Comment by nornagon** [comment]
Is there a bug on sccache we can track?

**Comment by thypon** [comment]
> Is there a bug on sccache we can track?

I searched this morning in the sccache bug tracker, but did not found anything.
The issue seems to be mostly with directories with super small files, in particular mojom generated apis. I could not even obtain a single build with correct object with sccache enabled.

**Comment by nornagon** [comment]
Given we don't use sccache in CI on current branches (we use goma instead), is this still relevant?

**Comment by thypon** [comment]
By current you mean master and nightlies, while release are using sccache insted right?

**Comment by jkleinsc** [comment]
@thypon yes that is correct.  sccache is used for releases; goma is used for development/testing builds.

**Comment by thypon** [comment]
So, yes @nornagon this is especially relevant for release builds.

**Comment by jkleinsc** [comment]
I'm testing using a newer version of sccache in #23202 to see if that resolves the issue.

**Comment by jkleinsc** [comment]
@thypon I have good news and bad news.  The bad news is that we can't use a newer version of sccache with Electron as it errors out with an error message such as:
```UnknownFlag arguments with -Xclang   26168```

The good news is that I think I have a workaround.  You can get read-only access to the release sccache S3 bucket for use with sccache via:
```export SCCACHE_BUCKET=electronjs-sccache-release```.  Doing so should ensure consistent results across the two builds as they will both read from the same populated cache.

When I add that environment variable to verify.sh and then run `./verify.sh -b /home/builduser/project v10.0.0-nightly.20200408`, it works for the most part, but it does find some differences in mksnapshot.zip that I think are unrelated to the sccache issue:

```
Epoch: bf 79 a0 5e
brotli                            : None
bytecode_builtins_list_generator  : None
character_data_generator          : None
chrome_sandbox                    : None
chromedriver                      : None
chromedriver.zip                  : None
cppgen_plugin                     : None
crashpad_handler                  : None
dist.zip                          : None
electron                          : None
flatc                             : None
gen-regexp-special-case           : None
genmacro                          : None
genmodule                         : None
genperf                           : None
genstring                         : None
genversion                        : None
hunspell_dictionaries.zip         : None
ipc_plugin                        : None
libEGL.so                         : None
libGLESv2.so                      : None
libVkICD_mock_icd.so              : None
libffmpeg.so                      : None
libvk_swiftshader.so              : None
libvulkan.so                      : None
mksnapshot                        : None
mksnapshot.zip                    : DIFFERENT (unexpected): 40 out of 830926159 bytes are different (0.00%)
  0x2a26c920: 4b03041400000008008288965031059b2a626111006813330018000000737769 'K...........P1..*ba..h.3.....swi'
              4b0304140000000800f385965031059b2a626111006813330018000000737769 'K...........P1..*ba..h.3.....swi'
                                ++ ^
  0x2a7d1b00: c2115bb5459729df61ff0b504b030414000000080082889650652ceaf1106601 '..[.E.).a..PK...........Pe,...f.'
              c2115bb5459729df61ff0b504b0304140000000800f3859650652ceaf1106601 '..[.E.).a..PK...........Pe,...f.'
                                                        ++ ^
  0x2a7e8140: ff07504b03041400000008008288965090143ef86e9501000833040015000000 '..PK...........P..>.n....3......'
              ff07504b0304140000000800f385965090143ef86e9501000833040015000000 '..PK...........P..>.n....3......'
                                      ++ ^
  0x2a8016e0: fcff03504b0304140000000800828896506b7ac9790c112b0030a48a000c0000 '...PK...........Pkz.y..+.0......'
              fcff03504b0304140000000800f38596506b7ac9790c112b0030a48a000c0000 '...PK...........Pkz.y..+.0......'
                                        ++ ^
  0x2aab2820: 00080024889650793d13f6adc9b00600d9821c0a0000006d6b736e617073686f '...$..Py=..............mksnapsho'
              00080098859650793d13f6adc9b00600d9821c0a0000006d6b736e617073686f '......Py=..............mksnapsho'
                    ^  +                                                           ^
  0x315bf1e0: 68e1df7d98f36f2fc10e00f3ff07504b03041400000008009986965070613f06 'h..}..o/......PK...........Ppa?.'
              68e1df7d98f36f2fc10e00f3ff07504b03041400000008009284965070613f06 'h..}..o/......PK...........Ppa?.'
                                                               ^ ^
  0x315bf280: 1400000008008288965004e62508e9471700688d4400140000006c6962766b5f '.........P..%..G..h.D.....libvk_'
              140000000800f385965004e62508e9471700688d4400140000006c6962766b5f '.........P..%..G..h.D.....libvk_'
                          ++ ^
  0x31733aa0: 0082889650c77571e3fcae130000b530000c0000006c696266666d7065672e73 '....P.uq.......0.....libffmpeg.s'
              00f3859650c77571e3fcae130000b530000c0000006c696266666d7065672e73 '....P.uq.......0.....libffmpeg.s'
                ++ ^
  0x3186e9c0: 02140314000000080073869650da4005c06ad41d00b8a87f000c000000000000 '.........s..P.@..j..............'
              02140314000000080067849650da4005c06ad41d00b8a87f000c000000000000 '.........g..P.@..j..............'
                                +  ^                                                     ^
  0x3186ea00: 0008005d8696504a588012448f09002e854900160000000000000000000000a4 '...]..PJX..D.....I..............'
              000800508496504a588012448f09002e854900160000000000000000000000a4 '...P..PJX..D.....I..............'
                     ^ ^                                                           ^
  libvulkan.so: Timestamps differ
  LICENSES.chromium.html: Timestamps differ
  snapshot_blob.bin: Timestamps differ
  v8_context_snapshot_generator: Timestamps differ
  swiftshader/libGLESv2.so: Timestamps differ
   ...
nasm                              : None
protoc                            : None
protozero_plugin                  : None
re2c                              : None
snapshot_blob.bin                 : None
top_domain_generator              : None
torque                            : None
transport_security_state_generator: None
v8_context_snapshot.bin           : None
v8_context_snapshot_generator     : None
yasm                              : None
Equals:           37
Expected diffs:   0
Unexpected diffs: 1
Unexpected files with diffs:

  mksnapshot.zip
Checking mksnapshot.zip difference: (18777 deps)
```

**Comment by nornagon** [comment]
@jkleinsc i think using the same cached object files somewhat defeats the purpose of _reproducing_ the build?

**Comment by thypon** [comment]
@jkleinsc there is still an unmerged patch at python-stripzip that renders mksnapshot.zip not reproducible. I am working with the maintainer to merge the Zip64 fix on their side.
@nornagon is right, using the same binaries defeats the purpose of reproducibility.

Unluckily at the moment I don't see any solution to this sccache bug if not disabling it temporarily. Have you ever considered using ccache on circleci instead?

**Comment by jkleinsc** [comment]
@thypon follow up question - why does the verify script use sccache at all?  wouldn't building without sccache work?  I think the way the script is written the second build will get cached results from the first build which as @nornagon mentioned kind of defeats the purpose.

**Comment by thypon** [comment]
That's a good question. At the beginning I wanted to replicate the exact setup of the builder.
Given this bug with `sccache` it has been both a bad and a good idea. Bad because it clearly defeat the local reproducibility test for some object. Good because we caught this bug.

Theoretically speaking the second build should not even be done, if I am guaranteed local reproducibility is working, it is there only to verify if there is some trivial local non reproducibility issues, that can be caught even with caching in between.

Within chromium since they do a double build I have this warranty and verify.sh can perform only one build. Since I have not this warranty in `electron` at the moment, I wanted to avoid people coming in the issue tracker saying release X is not remote reproducible, when the issue was that the build was not even local reproducible.

Short answer, tradeoff between doing two 8 hours builds and having perfect local reproducibility test or 8 hours+less than an hour to perform limited local reproducibility test.

**Comment by jkleinsc** [comment]
@thypon, I've been thinking about this - what if we did double builds on a nightly basis?  We already run release builds against our test suite on a nightly basis and I think with a little bit of work we could make the verification of releases use that same cron structure to run a verification build if/when a release has been released that day.

**Comment by jkleinsc** [comment]
Also, I was able to update to the latest version of sccache and the issue persists if the second build uses the local disk cache from the first build, but again this isn't really testing reproducibility because it relies on a cache.  I'm trying now to run the verify script with sccache but deleting the cache between builds.

**Comment by thypon** [comment]
Based on my tests the problem is always present when sccache is enabled. The problem is symbols finishing in wrong files due to a race condition with generated files from mojom.

**Comment by thypon** [comment]
> @thypon, I've been thinking about this - what if we did double builds on a nightly basis? We already run release builds against our test suite on a nightly basis and I think with a little bit of work we could make the verification of releases use that same cron structure to run a verification build if/when a release has been released that day.

Real problem is that releases won't be reproducible, if using sccache on Linux.
While on macOs it does not seem to have this bug. Local or Remote reproducibility, or even correctness of output is not guaranteed at the moment when sccache is enabled. So it does not really change anything if we know that local reproducibility is guaranteed in nightlies.

**Comment by jkleinsc** [comment]
@thypon I feel like I'm missing something here.  If we can reproduce a sccache produced release with a build that doesn't use sccache, wouldn't that prove reproducibility?

**Comment by thypon** [comment]
Yes, it should. If it doesn't use any caching mechanism. Basically what we want to reach is build equivalence, wrt the same toolchain. So If it somehow reuse the same output object it kinda defeats the purpose. The idea, for security purpose, is that we can know, only by compiling and verifying the hash, if somebody included malicious objects inside the compiled electron. From a software engineering point of view the purpose is catching compiler/caching mechanism bugs, such as the one we found in sccache. From a operational perspective instead is the ability to safely scale the infrastructure and perform parallel build without the terror of one of the node being compromised.

For example, if build with goma are reproducible wrt local builds without, the user can be guaranteed of having the same output, while the developer can have way faster compilations.

**Comment by thypon** [comment]
Just to add a bit more context, I always find this article very precise in the definitions and explanations.

http://blog.llvm.org/2019/11/deterministic-builds-with-clang-and-lld.html

**Comment by jkleinsc** [comment]
@thypon what if we ran release verification (without sccache) in CI after a release is published?  It wouldn't hold up the release process but would allow us to have confidence that a release was reproducible?

**Comment by jkleinsc** [comment]
To kind of further winnow this down - At this point for us to turn off sccache on our actual releases is going to be really horrible so I'm just trying to figure out how we can make this work.  ccache isn't a great option because our CI machines are ephemeral and wouldn't work great with a disk based cache.

**Comment by nornagon** [comment]
> @thypon what if we ran release verification (without sccache) in CI after a release is published? It wouldn't hold up the release process but would allow us to have confidence that a release was reproducible?

I don't love this as it's unclear what we would do if the result was "no", that we'd released something non-reproducible. Additionally, it reduces the frequency of checking this to weekly, which means we'll have 30–50 commits to check through to find which one broke it, vs. if we built nightly we'd have about 5.

**Comment by thypon** [comment]
I would prefer to maintain sccache as it is if we can fix the race condition issue somehow. In the meantime, is it possible to disable only for x86_64 which I guess is the most used architecture?
