### ISSUE TITLE
Use BrowserView create window, but -webkit-app-region can not work normally

### ISSUE THREAD

**Issue by blacklisten** [electron/electron#23193]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.2
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 8.2.2

### Expected Behavior

I used BrowserView to build a window with a fixed height of 35px. This window always exists. The main function of this window is to switch other windows, similar to the Google tab. Use addBrowserView to add to BrowserWindow. 
Set the Frame of BrowserWindow to false, when I add "-webkit-app-region: drag" to the tabs, I hope it can be dragged but fails
### Actual Behavior
-webkit-app-region can not work normally

### To Reproduce
[This is repository demo](https://github.com/blacklisten/electron-tabs)

### Additional Information
I tried to use this issue to solve the problem but failed

[https://github.com/electron/electron/issues/20926](https://github.com/electron/electron/issues/20926)

**Comment by xland** [comment]
How about this issue's progress?
@sofianguy @quanglam2807

**Comment by codebytere** [comment]
Closed in https://github.com/electron/electron/pull/26145
