### ISSUE TITLE
CustomScheme needs documentation

### ISSUE THREAD

**Issue by bpasero** [electron/electron#23195]
I am referring to https://github.com/electron/electron/blob/master/docs/api/structures/custom-scheme.md

It is currently very unclear what the implications are for each of the properties. 

//cc @deepak1556 who gave me a very good explanation yesterday

**Comment by siddharth25pandey** [comment]
I want to work on this issue. Kindly help me what changes are needed in this customscheme.md file.
Thanks!

**Comment by b18050** [comment]
@MarshallOfSound  Where can I find more about this to add info to documentation.

**Comment by 16sweetyjain** [comment]
I want to work on this. Please suggest me resource so i can get started. I am new to Open source community.

**Comment by faraz16iqbal** [comment]
I would love to work on this issue!

**Comment by 1111mp** [comment]
So where can I find the corresponding documentation?
