### ISSUE TITLE
Ubuntu: closing an Electron app with an open alert() causes a zombie window in the application bar

### ISSUE THREAD

**Issue by Prinzhorn** [electron/electron#23196]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** v9.0.0-beta.13, v8.2.3, v7.2.3, v6.1.10 (I didn't go back any further)
* **Operating System:** Ubuntu 19.10

### Expected Behavior

Closing an Electron application should close the Electron application.

### Actual Behavior

When an `alert()` is displayed and I close the application a zombie window remains in the task bar (or whatever it is called) on Ubuntu. The screenshot shows the zombies after I did the thing multiple times.

### To Reproduce

Essentially just a preload script with a `alert(1);`

1. https://gist.github.com/Prinzhorn/dfe34f7b9e6e90fbde99f5f20e402747
2. Close the main window but leave the alert inside open
3. The application closes (`ps ax | grep electron` doesn't yield any results) but it still shows in the application bar on the left (clicking it doesn't do a thing, right click -> quit neither)

### Screenshots
![Selection_614](https://user-images.githubusercontent.com/679144/79838025-ad1d0900-83b2-11ea-90cf-127e0ee90c6a.png)

**Comment by Prinzhorn** [comment]
Fwiw I upgraded to Ubuntu 20.04 and it seems to not happen any longer. Since it is the latest LTS this might be solved?

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
