### ISSUE TITLE
Desktop app to control a connected device using electron

### ISSUE THREAD

**Issue by meghajayakumar** [electron/electron#23197]
New to electron and planning on building a desktop application that would detect and work on a device connected using RJ45 (device) to USB (PC). Have already developed a mobile application that is used to control the device using bluetooth. Planning to use the same characteristics data to develop a desktop application that can be used to control the device. 

The device is a height adjustable desk that has move up, move down, saving heights to 4 memory positions, reset and displaying current height functionalities. Can I achieve these functionalities using electron? What would the packages you would recommend to detect and work with the characteristics of the connected device?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
