### ISSUE TITLE
Please re-open #21154 - Tray Icon is broken

### ISSUE THREAD

**Issue by dsteinman** [electron/electron#23203]
This problem is back, and makes using a tray icon impossible, It affects the latest version v8.2.3 on  both MacOS and Windows.

https://github.com/electron/electron/issues/21154

The only temporary workaround I've found is to use this, which creates a 'blank' tray icon that is usable, but hidden.

```
const trayIcon = electron.nativeImage.createFromPath(path.join(__dirname, 'img', 'logoTemplate.png'));
tray = new Tray(trayIcon);
```

**Comment by nornagon** [comment]
Thanks for the report, but please don't open new issues as well as commenting on old ones. We do see comments on closed issues.

**Comment by vladimiry** [comment]
@dsteinman make sure `logoTemplate.png` is acutally a PNG image but not renamed to PNG from other image format.
