### ISSUE TITLE
Javascript error when running electron

### ISSUE THREAD

**Issue by caradoct** [electron/electron#23243]
I am trying to get .png plot files created from plotly and get the error in the attached images.
Any help would be appreciated. 
This is a repost as I didn't fill out the template correctly.

### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * <-- 6.1.4 -->
* **Operating System:**
  * <--  macOS 10.14.6  -->
* **Last Known Working Electron version:**
  * <--  First time trying to get this to work -->

### Expected Behavior
Trying to get the plotly plot I can see in my jupyter notebook written to file.

### Actual Behavior
.png files are written but the surface has been corrupted. There are some markers but they look weird (sometimes numbers and letters show up).

### To Reproduce
I can send some test data and my plotly code but others can get .png files using this fine so I suspect it is an issue with my electron/orca installation on my mac.

### Screenshots
The error in Electron:
<img width="416" alt="Screen Shot 2020-04-23 at 10 19 40 am" src="https://user-images.githubusercontent.com/53884127/80046020-a3c7a400-854c-11ea-9639-9b6268447914.png">

What the plot looks like in my jupyter notebook:
<img width="583" alt="Screen Shot 2020-04-23 at 10 25 05 am" src="https://user-images.githubusercontent.com/53884127/80046058-c5289000-854c-11ea-94c2-02eb758ea011.png">

What the .png file looks like:
![newplot (14)](https://user-images.githubusercontent.com/53884127/80046109-f43f0180-854c-11ea-8bec-e275c4773aef.png)

### Additional Information
I am using jupyter notebook 5.7.4
Orca 1.3.1

**Comment by nornagon** [comment]
Seems like a problem with Orca, you should file a bug there.

**Comment by nornagon** [comment]
This is where to do that I think! https://github.com/plotly/orca/issues/new

**Comment by caradoct** [comment]
Really?

The orca problem is causing electron to throw a runtime error?
OK, I’ll try the orca folks.
Thanks for getting back to me so quickly.

Cheers,

Tom
