### ISSUE TITLE
Prints images with loss of quality (strongly compressing)

### ISSUE THREAD

**Issue by lyucean** [electron/electron#23245]
### Issue Details
* **Electron Version:**
electron: 8.2.3,
* **Operating System:**
Windows 10 (1903)

### Expected Behavior
I need to print marking with a picture, unfortunately, I have only PNG / GIF / JPEG

``` const {app, BrowserWindow} = require('electron');
let win = null;

app.on('ready', () => {

  win = new BrowserWindow({width: 320, height: 427, show: false });

  win.once('ready-to-show', () => win.hide())

  win.loadURL(`file://directory/to/pdf/test.png`);

  win.webContents.on('did-finish-load', () => {
    win.webContents.print({silent: true});
    win = null;
  });
});
```

### Actual Behavior
The images are printed with a strong loss of quality, it can be seen in the screenshot that I have attached.

### To Reproduce
Just try to print an image (PNG / GIF / JPEG), even if you insert it into an HTML document, the result will be the same.

### Screenshots
![image](https://user-images.githubusercontent.com/955310/80050563-a27f8280-851e-11ea-8c0c-71bbd066b530.png)
For clarity, I printed through a PDF printer, but it looks the same on real paper as well.

### Additional Information
At the same time, if I print through a chrom browser, I get a great image.
![image](https://user-images.githubusercontent.com/955310/80050576-b0cd9e80-851e-11ea-9e97-a3a3ec7ce742.png)
Same image I'd like to get.

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Comment by lyucean** [comment]
lol, while I found only such a solution: first you need to save the picture as PDF, then print PDF. Everything prints without loss of quality.

**Comment by codebytere** [comment]
@lyucean we don't really alter any of Chromium's printing functionality: we simply pipe it through and enable you to have programmatic access to it. In that event we recommend you open a bug with Chromium itself should this continue to be an issue.

**Comment by lyucean** [comment]
> @lyucean we don't really alter any of Chromium's printing functionality: we simply pipe it through and enable you to have programmatic access to it. In that event we recommend you open a bug with Chromium itself should this continue to be an issue.

Thank you for your attention, I knew the trouble was in Chromium. Eventually I found a solution to my problem and it suits me. You have a great product, thank you for what you have!
