### ISSUE TITLE
setAlwaysOnTop(true, "floating", 1) - Unexpected Behavior MacOS Catalina

### ISSUE THREAD

**Issue by ddamico125** [electron/electron#23246]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
v8.2.3
* **Operating System:**
Mac OS Catalina (10.15.4)
* **Last Known Working Electron version:**
Unsure
### Expected Behavior
`setAlwaysOnTop(true, "floating", 1)` should create a window that will be hidden when mission control is launched and in other ways act similarly to Spotlight Search.
### Actual Behavior
The window will not hide on mission control launch 

### To Reproduce
create a new BrowserWindow and call the method setAlwaysOnTop(true, "floating", 1)

**Comment by vanejung** [comment]
+1
Also experiencing the same issue in the same details.

**Comment by codebytere** [comment]
@ddamico125 this is not in fact the case -  we simply map this to `NSFloatingWindowLevel` [here](https://developer.apple.com/documentation/appkit/nswindowlevel?language=objc) and make no other changes to it. If you would like to change that, it would need to be done at the apple level - that would be reporting [here](https://developer.apple.com/bug-reporting/).

**Comment by zquancai** [comment]
> @ddamico125 tWe simply map this to `NSFloatingWindowLevel` [here](https://developer.apple.com/documentation/appkit/nswindowlevel?language=objc) and make no other changes to it.
> 
> If you would like to change that, it would need to be done at the native macOS level - that would be reporting [here](https://developer.apple.com/bug-reporting/).

Operating System:
Mac OS Catalina (10.15.4)

But it is normal when I use electron@5.x or 6.x or 7.x.
5.x video:
https://www.loom.com/share/fc93d7b4477f4f62814b31dd67b518f0

8.x video:
https://www.loom.com/share/8b7c63ec7d3e4830ae631d00aba8361f

it seems an electron bug.

**Comment by arantes555** [comment]
I can confim the behaviour is as expected on old version of electron, so it does seem to be an electron bug in recent versions, not a macos bug.
