### ISSUE TITLE
Mac App Store Private API Rejection

### ISSUE THREAD

**Issue by mobileguru121** [electron/electron#23248]
Mac App Store Rejection
The automated review process is rejecting the apps on the Mac App Store because of their use of private API calls.

The detected private API symbols include:

CAContext CALayerHost NSAccessibilityRemoteUIElement NSNextStepFrame NSThemeFrame NSURLFileTypeMappings

How to exclude those private api from electron framework (version 2.0.4) and approve to Apple?

Thanks in advance.

**Comment by MarshallOfSound** [comment]
> How to exclude those private api from electron framework (version 2.0.4)

Upgrade to a supported version of Electron, version `2.0.4` is far too old.  Current stable is `8.x.y`
