### ISSUE TITLE
WebRTC Insertable Streams support

### ISSUE THREAD

**Issue by sergeyd63** [electron/electron#23255]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
Is there a support for WebRTC Insertable Streams or is it coming? I tried beta and nightly version seems like RTCRtpSender does not include createEncodedVideoStreams. This was added starting Chromium 83.
The experimentalFeatures flag is enabled but i still can't see it

Thank you

**Comment by MarshallOfSound** [comment]
This is enabled by default (and working) from Chromium 86 onwards and therefore is enabled and working in all supported versions of Electron (as of today)
