### ISSUE TITLE
Crash when quit app on macOS Dock

### ISSUE THREAD

**Issue by rocka** [electron/electron#23253]
### Issue Details

* **Electron Version:**
  * 8.2.3
* **Operating System:**
  * Mac OS X 10.15.4 (19E287)
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
App should quit without crash

### Actual Behavior
App crashes when click "Quit" on macOS Dock

### To Reproduce
Quit App from macOS Dock (unsure, see additional information below)

### Additional Information

Crash report generated by @electron/symbolicate-mac: [crash-report.txt](https://github.com/electron/electron/files/4521388/crash-report.txt)

Since I'm not a macOS user, this bug report was forwarded from https://github.com/Rocket1184/electron-netease-cloud-music/issues/52#issuecomment-618149943

This issue should be present since electron@5, according to https://github.com/Rocket1184/electron-netease-cloud-music/issues/52#issuecomment-520143943

The 'will-quit' event was not handled, and on 'before-quit' event, I tried to destroy some BrowserWindow and a Tray, would it matter?

https://github.com/Rocket1184/electron-netease-cloud-music/blob/89f3d6fd37f30787eea476922e096c0507b7773e/src/main/index.js#L102-L128

**Comment by codebytere** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment. This issue will be closed in 7 days if the above cannot be provided.

Thanks in advance! Your help is appreciated.
