### ISSUE TITLE
autoUpdater doesn't work

### ISSUE THREAD

**Issue by klen** [electron/electron#23251]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  8.2.2
* **Operating System:**
  * macOS 10.15.4 Catalina

### Expected Behavior
I'm trying to set up auto-update and using [autoUpdater](https://www.electronjs.org/docs/api/auto-updater)

### Actual Behavior
The `autoUpdater` doesn't make any request to web server.
I see in console `Check updates:` from my code bellow and feed URL is correct, but in the server logs I don't see any requests from autoUpdater. Also, there are no events from autoUpdater. My server is working well, the application using it for other requests and everything is working except the autoUpdater.

### To Reproduce
```coffee
{ app, autoUpdater, dialog } = require('electron')

env = require('utils/env')

module.exports = ->
    feed = "#{ env.baseURL }/dev/electron/update/#{ process.platform }/#{ app.getVersion() }"

    try
        autoUpdater.setFeedURL(url: feed)

        autoUpdater.on 'error', (err) ->
            console.log('AutoUpdater - Error')
            console.error(err)

        autoUpdater.on 'checking-for-update', ->
            console.log('AutoUpdater - Checking for update')

        autoUpdater.on 'update-available', ->
            console.log('AutoUpdater - update available')

        autoUpdater.on 'update-not-available', ->
            console.log('AutoUpdater - update not available')
            setTimeout checkUpdate, 300e3

        autoUpdater.on 'update-downloaded', (event, releaseNotes, releaseName) ->
            dialogOpts =
                type: 'info',
                buttons: ['Restart', 'Later']
                title: 'Application Update'
                message: process.platform == 'win32' ? releaseNotes : releaseName
                detail: 'A new version has been downloaded. Restart the application to apply the updates.'

            dialog.showMessageBox(dialogOpts).then (returnValue) ->
                if returnValue.response == 0
                    autoUpdater.quitAndInstall()

        checkUpdate = ->
            console.log 'Check updates:', feed
            autoUpdater.checkForUpdates()

        checkUpdate()

    catch exc
        console.log 'Failed to setup auto update', exc

```

### Additional Information
The application is signed well. I even upload it into AppStore and passed a review. And the version from AppStore (which one absolutely signed and verified) also doesn't make autoUpdater requests.

How to make it work?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
