### ISSUE TITLE
feat: Allow exotic objects to be configurable, or make them normal objects

### ISSUE THREAD

**Issue by cberescu** [electron/electron#23278]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

I would love to have total control other the objects in the render process, that means also to be able to change immutable prototype objects (like Object,prototype, Function.prototype.. ). 

While the reason for immutable prototype objects is right for browsers, in electron this should be a editable option. 

### Additional Information

https://github.com/tc39/ecma262/issues/272

**Comment by codebytere** [comment]
The processes we use to serialize items across processes do not make this possible, unfortunately. Should something change, we'll let you know.
