### ISSUE TITLE
Dialog buttons in the wrong order

### ISSUE THREAD

**Issue by somebeaver** [electron/electron#23276]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version: 8.2.3

### Expected Behavior
The buttons in the dialog box that appears when running the Electron Fiddle should be in the order "Yes" then "No".

### Actual Behavior
They are in reverse order. The index of the clicked button is also reversed.

If this is the normal behavior then I think the docs should mention it [here](https://www.electronjs.org/docs/api/dialog#dialogshowmessageboxbrowserwindow-options)

Gist:

https://gist.github.com/6df3a3d77104aae9e0155bb4945b1d0b

**Comment by codebytere** [comment]
@somebeaver can you please include the operating system?

**Comment by somebeaver** [comment]
Sorry, yes; macOS 10.15.4

Screenshot: https://i.imgur.com/fk5Odjw.png

**Comment by sindresorhus** [comment]
This is working as intended. macOS orders the buttons from right to left, with the first button being the main and rightmost one. This should definitely be better documented though.

https://developer.apple.com/design/human-interface-guidelines/macos/windows-and-views/alerts/

**Comment by codebytere** [comment]
That was my understanding too @sindresorhus, thanks for confirming! I'll pop up a docs PR soon.

**Comment by somebeaver** [comment]
Ok thank you for the clarification. I haven't been using macOS for very long and I didn't know they went from right to left.
