### ISSUE TITLE
Does electron have an API to open the remote desktop of the window

### ISSUE THREAD

**Issue by 1006569910** [electron/electron#23289]
![1587967359(1)](https://user-images.githubusercontent.com/41898623/80338801-d72d6a00-888f-11ea-99b9-421dd3ce0702.png)

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
