### ISSUE TITLE
Desktop Capture API - Can we create a border/ring around shared application window ?

### ISSUE THREAD

**Issue by poojas2288** [electron/electron#23288]
I am using desktop capture API for screen/application sharing. I need to create a border/highlighted ring around the shared application/window so that it becomes prominent to the user what is being shared, like it is with most of the screen sharing applications.

Is it possible with desktop Capture API or some other API of Electron ?

Thanks for the help.

**Comment by MarshallOfSound** [comment]
This is not directly supported by Electron or Chromium and probably isn't an API we're going to implement due to it's specificity in nature, I recommend you look into writing a native module for this 👍

**Comment by parikshit-dp** [comment]
@MetaiR @poojas2288 did you come across anything that would be helpful here? I know we can do a fullscreen border around screen but I'm also facing issues in drawing around individual application.

**Comment by yangwooseong** [comment]
Maybe https://github.com/SnosMe/electron-overlay-window can help. I will try it out, too
