### ISSUE TITLE
>electron@5.0.8 does not support Windows 7

### ISSUE THREAD

**Issue by SilurianYang** [electron/electron#23284]
### Preflight Checklist

* [  ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:*8.2.3*
* **Operating System:*Windows 7 32bit*
* **Last Known Working Electron version:*5.0.8*

### Expected Behavior
can be started on win7

### Actual Behavior
unable to start

### To Reproduce
1. create a brand new project
2. npm install electron@8.2.3
3. The packaged project runs on win7

### Screenshots
![QQ图片20200426192829](https://user-images.githubusercontent.com/31280665/80306162-245bfe00-87f4-11ea-9290-0db0b9ac2cbf.jpg)
![QQ图片20200426192836](https://user-images.githubusercontent.com/31280665/80306169-27ef8500-87f4-11ea-975b-7242fd46b095.jpg)

### Additional Information
I tried the solution of [#19569](https://github.com/electron/electron/issues/19569), and installed the .net Framework 4.7.1 with the package when installing the package through nsis! Win7 prompts that this system does not support .net Framework 4.7.1 and it can be run on win7 if it is restored to electron@5.0.8 and below Dear friends, how to solve this problem. Of course, check compatibility mode on win7 can be run!

**Comment by lvzhao1995** [comment]
Replacing the installed file d3dcompiler_47.dll with version 10.0.17134.12 works. This file is in the low version of electron.

**Comment by roy2651** [comment]
@lvzhao1995 electron怎么看匹配的dll，你知道嘛

**Comment by lvzhao1995** [comment]
> @lvzhao1995 electron怎么看匹配的dll，你知道嘛

如果是为了解决win7黑屏问题，使用10.0.17134.12版本的d3dcomplier_47.dll替换electron自带的就可以。

**Comment by SilurianYang** [comment]
> > @lvzhao1995 electron怎么看匹配的dll，你知道嘛
> 
> 如果是为了解决win7黑屏问题，使用10.0.17134.12版本的�d3dcompiler_47.dll替换electron自带的就可以。

这个尝试下 兄弟有联系方式么

**Comment by roy2651** [comment]
> > @lvzhao1995 electron怎么看匹配的dll，你知道嘛
> 
> 如果是为了解决win7黑屏问题，使用10.0.17134.12版本的�d3dcompiler_47.dll替换electron自带的就可以。

你有遇到在windows10的机器上，打开electron的程序需要右击兼容性打开这类的问题嘛

**Comment by lvzhao1995** [comment]
> > > @lvzhao1995 electron怎么看匹配的dll，你知道嘛
> > 
> > 
> > 如果是为了解决win7黑屏问题，使用10.0.17134.12版本的�d3dcompiler_47.dll替换electron自带的就可以。
> 
> 你有遇到在windows10的机器上，打开electron的程序需要右击兼容性打开这类的问题嘛

没遇到过，是不是Windows10版本比较低，没有.net framework 4.7.1

**Comment by codebytere** [comment]
Chromium no longer supports 32 bit apps doesn't run on 64 bit windows. There's nothing we can do about this unfortunately.
