### ISSUE TITLE
Newline ignored in tray menu label on MacOS and Windows. Works on Linux

### ISSUE THREAD

**Issue by hovancik** [electron/electron#23295]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  ^8.2.3
* **Operating System:**
  *  macOS 10.15.4
* **Last Known Working Electron version:**
  *  Linux any

### Expected Behavior

When adding newline in tray menu label (`\n` or `\r\n`) it is being separated in 2 lines.
```
"A\r\nB"
```
A
B

### Actual Behavior

When adding newline in tray menu label (`\n` or `\r\n`) it is being ignore and string is one line

```
"A\r\nB"
```
AB

### To Reproduce
create label in tray menu with new line

### Additional Information

Works as expected in Linux.

**Comment by codebytere** [comment]
@hovancik unfortunately these are system-level limitations: neither macOS nor Windows allow for newline breaks in menu items in the way you desire. Should something change, i'm happy to take another look at this.
