### ISSUE TITLE
Electron loadFile cannot load html with anchor #

### ISSUE THREAD

**Issue by qianfeii** [electron/electron#23290]
### Preflight Checklist

*  I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
*  I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
*  I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
    "electron": "^8.1.1",
    "electron-builder": "^22.4.1"
* **Operating System:**
   Windows 10 (1803)

### Expected Behavior
I want to load a html file with anchor ,like './a.html#/cock/pit'

### Actual Behavior
load failed, just white page 

I can load file successfully `win.loadFile('./app/dist/index.html')`，
but when i use `win.loadFile('./app/dist/index.html#/cockpit/citrecord')`, it just white page
btw,
I want to control new-window url ,
```
win.webContents.on('new-window', (event, url, framename, disposition, options) => {
    event.preventDefault()
    const hash = url.split('#')[1]
    const loadFilePath = `./app/dist/index.html#${hash}`
    const win = new BrowserWindow(options)
    win.once('ready-to-show', () => win.show())
    if (!options.webContents) {
      console.log(1212)
      // win.loadFile(loadFilePath)
      win.loadFile('./app/dist/index.html/#/cockpit/cit/history/second?year=2018') // failed
      // win.loadURL('http://10.119.169.117:9920') // it worked
    }
    event.newGuest = win
  })
```
still failed

**Comment by MarshallOfSound** [comment]
This is expected behavior, a file path has no concept of an "anchor" `loadFile` explicitly loads a file path so it tries to treat the `#` as part of the path.  There are special API params for hash / query with `loadFile`.

```js
win.loadFile('./path/to/thing', { hash: 'my-hash' });
```

As per the API docs: https://www.electronjs.org/docs/api/web-contents#contentsloadfilefilepath-options

**Comment by grafanauser** [comment]
@MarshallOfSound:
do you know if something similiar exists for shell.openExternal() to open a file with a hash at the end in the default browser?
