### ISSUE TITLE
autoUpdater: Make popular private API public i.e. document API

### ISSUE THREAD

**Issue by Superlokkus** [electron/electron#23294]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

I and as far as I can tell many other users are using the non documented API of autoUpdater, for example 

1. `autoUpdater.downloadUpdate`
2. `autoUpdater.autoDownload`
3. `autoUpdater.autoInstallOnAppQuit`
4.  event `download-progress`

. Right now the only "Documentation" is the typescript source of AppUpdater. The mentioned API is not documented in https://www.electronjs.org/docs/api/auto-updater.

### Proposed Solution

Make the mentioned API official i.e. public.

### Alternatives Considered

Implement ways to issue an update of the application, where the steps download, and installation can be triggered by the programmer/user.

**Comment by MarshallOfSound** [comment]
@Superlokkus That API is not Electron's API.  As you can see [in this search](https://github.com/electron/electron/search?q=autoInstallOnAppQuit&unscoped_q=autoInstallOnAppQuit) those methods do not exist anywhere in Electron's codebase.

I think you are using an unsupported third-party updating solution (which I strongly recommend you avoid)

**Comment by Superlokkus** [comment]
@MarshallOfSound My apologies you are right, I messed up.
