### ISSUE TITLE
When Ajax requests to customize the protocol, post cannot carry the body parameter

### ISSUE THREAD

**Issue by mapleby** [electron/electron#23306]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.2.3
* **Operating System:**
  * windows10(1909)
* **Last Known Working Electron version:**
  * 

### Expected Behavior

Ajax requests post and can carry the body parameter
### Actual Behavior

When Ajax requests a custom protocol, post cannot carry the body parameter, and HTTP or HTTPS can carry the body parameter.
### To Reproduce

 const xmlhttp = new XMLHttpRequest();
            console.log(xmlhttp)
            xmlhttp.open("POST", "atom://test.sy", true);
            xmlhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
            xmlhttp.send("fname=Henry&lname=Ford");

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If you're still experiencing this issue in Electron 8.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
