### ISSUE TITLE
Allow backgroundThrottling and introduce hide/show APIs for BrowserView

### ISSUE THREAD

**Issue by mmmkkaaayy** [electron/electron#23313]
### Problem Description
I'm working on implementing a split-view web browser in electron. The idea is that a user can have any number of open browser tabs, but only a subset of them are visible on the 'main' BrowserWindow at any point in time.

I currently do this by creating a frameless BrowserWindow for each tab the user has open. I chose BrowserWindow over BrowserView because I noticed that BrowserWindow supports backgroundThrottling when hidden. So I believed it would be more performant than having BrowserViews that I move offscreen (since there is no API to hide them).

So far this has worked ok, but it definitely feels like the wrong tool for the job. There is one particular bug that I don't know how to solve: even if I set `movable` to false, I'm able to move the frameless BrowserWindows with win+shift+left/right. That will move the focused BrowserWindow to adjacent displays.

I believe BrowserView is much more appropriate for what I'm trying to achieve. 

Note that I didn't actually test the performance of BrowserView before going with BrowserWindow; it was premature optimization on my end. Please let me know if my reasoning/assumptions were incorrect!

### Proposed Solution
BrowserView should support backgroundThrottling. And I should be able to toggle a BrowerView's visibility with `hide()` and `show()`

**Comment by mmmkkaaayy** [comment]
Does anyone familiar with the BrowserView implementation know what sort of source code changes this would entail?

**Comment by miniak** [comment]
@mmmkkaaayy you can do it via `webContents` https://github.com/electron/electron/blob/master/docs/api/web-contents.md#contentssetbackgroundthrottlingallowed

**Comment by zcbenz** [comment]
I'm closing this issue since there is an API for the requested feature.
