### ISSUE TITLE
Async method `dialog.showMessageBox` is blocking

### ISSUE THREAD

**Issue by karaggeorge** [electron/electron#23319]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.0

### Expected Behavior

- Having a way to show a message dialog that does not block main process
- Async method `dialog.showMessageBox` should not be blocking

### Actual Behavior

After https://github.com/electron/electron/pull/17298,

There's no way to show a non-blocking dialog. There used to be an option to pass a callback to make the dialog non-blocking for the main process. But now even the `showMessageBox` method which is async returning a promise, is blocking the main process, which defeats the purpose of it being async.

### To Reproduce

```
  console.log('1');
  dialog.showMessageBox({
    type: 'error',
    message: 'Some message',
  }).then(() => {
    console.log('3');
  });
  console.log('2');
```

I would expect that to print:
```
1
2
3
```

But it actually prints:
```
1
3
2
```

So, the `showMessageBox` method is not really async and there's no value using it over `showMessageBoxSync`

**Comment by codebytere** [comment]
@karaggeorge please provide an operating system: i ran this on macOS and correctly saw:

```
1
[66246:0428/105754.863937:WARNING:ca_layer_tree_coordinator.mm(54)] Blank frame: No overlays or CALayers
[66246:0428/105754.927565:WARNING:ca_layer_tree_coordinator.mm(54)] Blank frame: No overlays or CALayers
2
3
```

**Comment by karaggeorge** [comment]
Sorry, I guess the console statements happen in the right oder. But as you can see from the recording below, the code stops executing until I click `OK`. So the log `2` doesn't happen immediately after `1` but only after the dialog has stopped. So it appears that it is indeed blocking the main process.

![Kapture 2020-04-28 at 14 24 18](https://user-images.githubusercontent.com/8822835/80523400-090c0280-895c-11ea-9c5b-07adede719e1.gif)

To clarify, this is documented correctly for both `showMessageBox` and `showMessageBoxSync`. My problem is that there no longer seems to be a way to have a non-blocking dialog

**Comment by codebytere** [comment]
@karaggeorge the message box must be attached to a window to be asynchronous - this has historically been the case as well. If you run:

```
  console.log('1');
  dialog.showMessageBox(mainWindow, {
    type: 'error',
    message: 'Some message',
  }).then(() => {
    console.log('3');
  });
  console.log('2');
```

you'll see this to be the case - `2` gets printed before any action is taken on the dialog.

**Comment by karaggeorge** [comment]
@codebytere thank you for the workaround. Is there a reason for that behavior? Or is it a limitation of the implementation?

**Comment by sindresorhus** [comment]
This is unfortunately how `NSAlert` works. There's no good way to run an app-modal alert asynchronously. The best you can do is to create your own window that looks like an alert.

There are ways to give the process some time to operate while the alert is open: https://stackoverflow.com/questions/7246153/cocoa-how-to-run-a-modal-window-while-performing-a-background-task But I don't think that would work well for Electron.

However, I don't think the `browserWindow` argument should be optional in the async version. It is surprising to users that when they forget/don't pass the argument, suddenly it's blocking. At minimum this behavior should clearly be documented, but I would strongly prefer to fix it instead.

**Comment by boburxon** [comment]
I did workaround just passing an argument like this:
`dialog.showMessageBox(remote.getCurrentWindow(), {
                    title: 'Success.',
                    message: 'Some text goes here.'
                });`
If I pass current window it works as expected, asynchronously, if I don't pass current window or pass a null value it works, but in a synchronous way.
