### ISSUE TITLE
First XHR request (Axios) takes (very) long time to achieve, why ?

### ISSUE THREAD

**Issue by Octavelscx** [electron/electron#23314]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Operating System:**
MacOS 10.15.3

### Expected Behavior
My app request on open (and every 5sec) .json file (on server) with **Axios** and parse it to get some data.

### Actual Behavior
On opening the app, the first **Axios** request takes between 5 and 7sec to achieve and after takes only 50 or 100ms, I'm wondering why ?

<img width="578" alt="Capture d’écran 2020-04-28 à 15 01 11" src="https://user-images.githubusercontent.com/62465485/80490186-4626c380-8961-11ea-98ec-acb942623f1b.png">

I read that a long time Queuing can be explained by theses raisons :

>      1. The request was postponed by the rendering engine because it's considered lower priority than critical resources (such as scripts/styles). This often happens with images.
>      2. The request was put on hold to wait for an unavailable TCP socket that's about to free up.
>      3. The request was put on hold because the browser only allows six TCP connections per origin on HTTP 1.
>      4. Time spent making disk cache entries (typically very quick.)

I think it's the 1. the reason of my issue here, but I don't find what scripts or styles are making time to load on open because it's a little app with no big scripts to load, just one css3 animation, so I may think it's just the electronjs time to load ? If anyone has an idea I would be very grateful.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
