### ISSUE TITLE
Override parent window

### ISSUE THREAD

**Issue by l222p** [electron/electron#23322]
### Issue Details

* **Electron Version:**
  * 6.0.10
* **Operating System:**
  * Windows 10 (1803)

### Expected Behavior
I want to override a parent window's window. Like this: 

`screenWindow.setParentWindow(new BrowserWindow());`

Of course screenWindow has a previous parent, and I want to override it. 
```
    modal: true,
    show: false,
    fullscreen: true,
    frame: false,
    resizable: false,
```

### Actual Behavior
Got this erros
`Error: Can not be called for modal window`

### To Reproduce
```
 let win = new BrowserWindow();
 let screenWindow = screenDetectorWindow(win);
 screenWindow.loadFile(path.join('page.html'));
 screenWindow.setParentWindow(new BrowserWindow());

```

**Comment by Venancio-Machaiela** [comment]
Thankiu🖤

**Comment by codebytere** [comment]
Given that  that this isn't currently on our roadmap or a use case affecting a substantial subset of users, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR.
