### ISSUE TITLE
Weird behaviour of electron.ipcMain

### ISSUE THREAD

**Issue by marco-a** [electron/electron#23329]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  v8.2.4
* **Operating System:**
  *  macOS 10.14.6
* **Last Known Working Electron version:**
  *  n/a

### Expected Behavior

That a handler gets installed for the specified channel.

### Actual Behavior

An error is thrown:

	(node:7235) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_events' of undefined
	    at _addListener (events.js:228:19)
	    at addListener (events.js:284:10)
	    at registerTestHandler (/Users/marco/Desktop/electron-ipc-test/index.js:4:3)
	    at /Users/marco/Desktop/electron-ipc-test/index.js:9:3
	(node:7235) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_events' of undefined
	    at _addListener (events.js:228:19)
	    at addListener (events.js:284:10)
	    at registerTestHandler (/Users/marco/Desktop/electron-ipc-test/index.js:4:3)
	    at /Users/marco/Desktop/electron-ipc-test/index.js:9:3
	(node:7235) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
	(node:7235) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
	(node:7235) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
	(node:7235) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### To Reproduce

```javascript
var electron = require("electron")

var registerTestHandler = function(onFunction) {
	onFunction("test", console.log)
}

electron.app.whenReady()
.then(function() {
	registerTestHandler(electron.ipcMain.on)
})
```

```sh
$ git clone git@github.com:marco-a/electron-ipc-test.git
$ npm install
$ npm run run
```

### Additional Information

It works when the code is changed to the following:

```javascript
var electron = require("electron")

var registerTestHandler = function(ipcInstance) {
	ipcInstance.on("test", console.log)
}

electron.app.whenReady()
.then(function() {
	registerTestHandler(electron.ipcMain)
})
```

**Comment by MarshallOfSound** [comment]
This is just the way javascript works, when you rip the `on` method off of ipcMain you are removing the `this` scope when you call that method in the future.  i.e. if you explicitly bind it to `ipcMain` it will work

```
var electron = require("electron")

var registerTestHandler = function(onFunction) {
	onFunction("test", console.log)
}

electron.app.whenReady()
.then(function() {
	registerTestHandler(electron.ipcMain.on.bind(electron.ipcMain))
})
```

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
