### ISSUE TITLE
PDF printing of some unicode characters fails

### ISSUE THREAD

**Issue by burningTyger** [electron/electron#23344]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  8.2.4

* **Operating System:**
  *  macOS 15.4

### Expected Behavior
Displaying characters and printing to PDF should result in identical display of all characters

### Actual Behavior
Printing some characters fails. See image attached:
This is the electron window: 
<img width="741" alt="image" src="https://user-images.githubusercontent.com/263378/80697166-e3583800-8ad8-11ea-8f41-3ff3b4ce18c4.png">

This is the generated PDF via `webContents.printToPDF()`
<img width="771" alt="image" src="https://user-images.githubusercontent.com/263378/80697242-fe2aac80-8ad8-11ea-9e77-a7427b9ed540.png">

### To Reproduce
use my repo to create the output.pdf file inside the same dir:

```
git clone https://github.com/burningTyger/electron-pdf-bug.git
npm i
npm start

# If on a mac:
open output.pdf
```

**Comment by codebytere** [comment]
@burningTyger i'm a little confused - the repo you provided has no [custom commits](https://github.com/burningTyger/electron-pdf-bug/commits/master). No pdf is generated as none is ever even opened.

**Comment by burningTyger** [comment]
@codebytere this is so embarrassing, I forgot to commit 🤦 I pushed it now.

**Comment by codebytere** [comment]
No worries :) I pulled it down and verified, but unfortunately this isn't a bug Electron can fix - it's an issue with Chromium's own unicode rendering. If you open `index.html` in Chrome, print, and then save it as a PDF, you'll see the same weirdly-rendered characters. I recommend you open a bug [here](crbug.com) and then as soon as it's fixed we'll pick it up in Electron itself!
