### ISSUE TITLE
Glichty Lines on electron based apps on Windows 10 with Nvidia GPU

### ISSUE THREAD

**Issue by Nikit-Singh** [electron/electron#23350]
### Issue Details

* **Operating System:**
  * Windows 10 (1909) with Nvidia 1050Ti and Nvidia 445.75 Drivers

### Actual Behavior
Glitchy lines on the electron based apps while using them.

### To Reproduce
Randomly Appears while using the app. Like while scrolling or typing.

### Screenshots
![Error](https://user-images.githubusercontent.com/31632952/80728021-15db5280-8b24-11ea-881a-2c27bf77450e.png)

**Comment by codebytere** [comment]
Unfortunately this is not something we control and is nondeterministic as a result of Chrome interactions. Should something change, we'll reopen this.

**Comment by spartanatreyu** [comment]
> Unfortunately this is not something we control and is nondeterministic as a result of Chrome interactions. Should something change, we'll reopen this.

Is there a link to a relevant chromium (or skia?) issue that tracks this?
