### ISSUE TITLE
SIGABRT when calling `process.exit` with `worker_threads` active

### ISSUE THREAD

**Issue by flotwig** [electron/electron#23366]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.4
* **Operating System:**
  * Pop_OS 19.10
* **Last Known Working Electron version:**
  * `worker_threads` were first available in 5.x
  * In 5.x, this is still broken, but it causes a SIGSEGV, not a SIGABRT
  * From 6.x+ the SIGABRT issue is present

### Expected Behavior

`process.exit` aborts all running worker_threads without erroring, like in vanilla Node.js.

### Actual Behavior

SIGABRT (or SIGSEGV in 5.x) is thrown when calling `process.exit` with worker_threads running.

### To Reproduce

I've created a repo here that demonstrates the issue: https://github.com/flotwig/electron-worker-threads-sigabrt

Run `npm install` to install Electron 8.2.4.

Try running it with Node 12.13.0 and then with Electron 8.2.4:

With `node index.js` (Node 12.13.0):

```
[parent]        calling process.exit
[parent]        worker exited
[wrapper]       process exited with code: 2 signal: null
```

With `electron index.js` (Electron 8.2.4, bundles Node 12.13.0)

```
[parent]        calling process.exit
.../dist/electron ./parent.js[13467]: ../../third_party/electron_node/src/node_worker.cc:384:virtual node::worker::Worker::~Worker(): Assertion `stopped_' failed.
[wrapper]       process exited with code: null signal: SIGABRT
```

### Additional Information

A workaround is to call `worker.terminate()` and wait for it to resolve before calling `process.exit`, but this should not be necessary, Node does not require it.

`worker.unref()` does not change the outcome.

Note - I have also seen this issue cause a SIGSEGV segfault in Electron 8.2.4, but I was unable to reproduce this minimally, only the SIGABRT.

**Comment by flotwig** [comment]
This is fairly difficult to work around in an existing codebase, because there are many ways (planned and unplanned) that the process may exit, and it's impossible to verify that we can *always* terminate all workers before the process exits, especially since `process.on('exit')` will not run asynchronous handlers.

**Comment by flotwig** [comment]
It seems to be some kind of race condition when the `Worker` destructor is called while the process is shutting down:

https://github.com/nodejs/node/blob/42cce5a9d0fd905bf4ad7a2528c36572dfb8b5ad/src/node_worker.cc#L381-L389

I've seen it fail at `CHECK(stopped_)` as well as at `CHECK(thread_joined_)`.

**Comment by codebytere** [comment]
Folding into https://github.com/electron/electron/issues/23315 as they have the same underlying cause.
