### ISSUE TITLE
Contextmenu inside webview

### ISSUE THREAD

**Issue by AndiLeni** [electron/electron#23363]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
v8.2.4
* **Operating System:**
Windows 10 (1909)

### Expected Behavior
I want to display a contextmenu inside a webview when the user right-clicks there.

### Actual Behavior
This does not seem to be possible since the webviews dont offer the "context-menu" event.

### Additional Information
I also tried using the `electron-context-menu` package, but their menu does not open inside webviews as well.

**Comment by vladimiry** [comment]
```javascript
app.on("web-contents-created", (...[/* event */, webContents]) => {
  webContents.on("context-menu", () => {
     // trigger menu showing
  });
});
```

**Comment by MarshallOfSound** [comment]
Solution provided above

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

**Comment by abnerlee** [comment]
Possible to allow developers to use custom dom-based context menu?

The `context-menu` only triggers when native context menu are used.
