### ISSUE TITLE
Electron executable when running by itself and ffmpeg.dll

### ISSUE THREAD

**Issue by Amosss** [electron/electron#23377]
* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  electron 7.2.4 and electron devtools installer 2.24
* **Operating System:**
  Windows 10

### Expected Behavior
When running an electron executable by itself, it should work with no problem.

### Actual Behavior
When running the executable in a dedicated folder, I get an error and the app is not running (see screenshot below). 

### To Reproduce
I'm using quasar framework and the electron build is done "behind the scenes".

### Screenshots
![image](https://user-images.githubusercontent.com/17168621/80802346-b6c71d80-8bb7-11ea-8ad1-a6ab4505eab2.png)

**Comment by Amosss** [comment]
builder and target portable did the trick

**Comment by javenwang** [comment]
Hi @Amosss , I have the same problem. Could you show your solution to me? Thank you!

**Comment by Amosss** [comment]
Sure, in electron settings I did the following

```
    electron: {
      bundler: "builder", // 'packager' or 'builder'

      packager: {
      },

      builder: {
        appId: "...",
        productName: "...",
        win: {
          target: "portable"
        }
      },

```

**Comment by jivansupe** [comment]
Hello @javenwang, Can you please point me out where to make the changes mentioned in the last comment?
My electron version is: **15.3.0**


Let me know. Thanks.

**Comment by javenwang** [comment]
hi @jivansupe you may check `package.json`

**Comment by kingisaac95** [comment]
Setting target: "portable" worked for me. Thanks

**Comment by leonielovesya** [comment]
@kingisaac95 it didn't fix it for me, is there anything else I could try?

**Comment by peterbriers-pvs** [comment]
Did not work for me either. When executing the same portable multiple times in succession, this errors comes up. (Win11)
