### ISSUE TITLE
Infer print title

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#23380]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.2 
* **Operating System:**
  * macos 10.14
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior

When calling `window.print ()` the resulting PDF will take its name from the webpage's title.

When calling `webContents.print ()` the same thing should happen.

### Actual Behavior

The resulting PDF is always called "Untitled.pdf".

### To Reproduce

Just call `webContents.print ({ silent: false })`.

**Comment by codebytere** [comment]
Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue. For example, are you calling this in the renderer process? main? Lack if information forces us to make assumptions which might be incorrect.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment. This issue will be closed in 7 days if not addressed.

**Comment by fabiospampinato** [comment]
@codebytere I think a test for this requires interacting with the native print dialog across platforms, I don't know how to write a test for that.

I'm calling that from the main process, in a BrowserWindow created just for printing with these options:

```ts
  new BrowserWindow ({
    backgroundColor: '#FFFFFF',
    enableLargerThanScreen: true,
    show: false,
    useContentSize: true,
    webPreferences: {
      devTools: false,
      nodeIntegration: false,
      javascript: false,
      sandbox: true,
      webSecurity: true
    }
  });
```

The title is defined using the `<title>` tag and the loaded HTML is loaded as a data URL string.

---

BTW wouldn't it be a separate problem if even just calling `BrowserWindow#webContents#print` from the renderer process rather than from the main process could have an effect on the title of the printed PDF? Like doesn't the renderer process just forward the command to the main process anyway?

**Comment by codebytere** [comment]
We essentially just leverage Chromium's printing infrastructure, which doesn't allow for customization outside of a header and footer at present. Yes, but you can also just set the name of the PDF itself, so as a fix to this would likely require a nontrivial patch to Chromium at this time this isn't something we feel is in the best interest of the project to fix as it makes maintenance of our patch surface more difficult for something which is still achievable through manual setting.
