### ISSUE TITLE
TypeError: Cannot read property 'appendSwitch' of undefined

### ISSUE THREAD

**Issue by cacheiforindicium** [electron/electron#23389]
I'm trying to initilize widevine as is described in the electron documentation by doing the following:
```
const { electron_1 } = require("electron");
electron_1.commandLine.appendSwitch('widevine-cdm-path', 'libwidevinecdm.so')
electron_1.commandLine.appendSwitch('widevine-cdm-version', '1.4.8.866')
```

However, in the console this returns ` Cannot read property 'appendSwitch' of undefined`
I can't see what I am doing wrong here.

**Comment by vladimiry** [comment]
https://www.electronjs.org/docs/api/command-line

electron_1 => app

**Comment by codebytere** [comment]
Closing in agreement with the above.
