### ISSUE TITLE
crashReporter module failures on Windows on Arm

### ISSUE THREAD

**Issue by richard-townsend-arm** [electron/electron#23399]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

On the Azure pipelines analytics, the following tests are reporting failures since 23/04/2020:
* crashReporter module getLastCrashReport returns the last uploaded report
* crashReporter module should not send a minidump when uploadToServer is false

* **Electron Version:**
  *  master
* **Operating System:**
  *  Windows on Arm
* **Last Known Working Electron version:** 
  *  `6fa05dd` is the first version affected 

### Expected Behavior

* crashReporter module tests pass

### Actual Behavior

* crashReporter module tests fail with these errors
```
not ok 529 crashReporter module should not send a minidump when uploadToServer is false
  Error: ENOENT: no such file or directory, scandir 'C:\Users\klein\AppData\Local\Temp\Zombies Crashes\completed'
      at Object.readdirSync (fs.js:872:3)
      at Object.fs.readdirSync (electron/js2c/asar.js:605:39)
      at waitForNewFileInDir (electron\spec-main\api-crash-reporter-spec.ts:161:27)
      at Context.<anonymous> (electron\spec-main\api-crash-reporter-spec.ts:232:27)
not ok 535 crashReporter module getLastCrashReport returns the last uploaded report
  Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\vsts-agent-win-x86-2.148.2\_work\1\s\src\electron\spec-main\api-crash-reporter-spec.ts)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
```

### To Reproduce
`npm run test -- --ci -g "crashReporter"`

**Comment by richard-townsend-arm** [comment]
Related discussion in #23242, the tests were disabled on Windows on Arm, but I should find the root cause.

**Comment by nornagon** [comment]
FYI there's an ongoing refactor of crashReporter here: https://github.com/electron/electron/pull/23265

**Comment by richard-townsend-arm** [comment]
Re-enabled the tests on top of 54b6c0606226f6df806dc6bc458295ac50b1f792 and everything passed successfully (Windows 1909, build 18363.836, Microsoft Surface Pro X).

**Comment by richard-townsend-arm** [comment]
Full test run on that system configuration indicated 4 failures:

````
not ok 332 BrowserWindow module "webPreferences" option "sandbox" option exposes ipcRenderer to preload script (path has special chars)
  Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\ci\electron\src\electron\spec-main\api-browser-window-spec.ts)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

not ok 1425 chrome extensions chrome.i18n getAcceptLanguages()
  AssertionError: expected [ 'en-GB' ] to deeply equal [ 'en-US' ]
      at Context.<anonymous> (electron\spec-main\extensions-spec.ts:122:49)

not ok 1537 version-bumper nextVersion bumps to beta from beta
  AssertionError: expected '2.0.0-beta.1' to equal '2.0.0-beta.9'
      at Context.<anonymous> (electron\spec-main\version-bump-spec.ts:81:36)

not ok 1538 version-bumper nextVersion bumps to beta from beta if the previous beta is at least beta.10
  AssertionError: expected '6.0.0-beta.1' to equal '6.0.0-beta.16'
      at Context.<anonymous> (electron\spec-main\version-bump-spec.ts:88:36)
```

332 looks legitimate. 1425 is probably because I'm based in the UK (and therefore my system's language / keyboard layout etc are set to en-GB), 1537 is probably because I didn't pull down all the tags for my test build, 1538 is similar. 

@jkleinsc : could we sync up at some point and try to figure out what's going wrong in the WoA test environment?

**Comment by jkleinsc** [comment]
@richard-townsend-arm we are not seeing those above failures in CI now. 
#23707 should resolve the flakiness we have been seeing recently on WOA.

**Comment by codebytere** [comment]
Closed in https://github.com/electron/electron/pull/23707.
