### ISSUE TITLE
Help: There was an error building with is_component_build at Mac OS

### ISSUE THREAD

**Issue by yanite** [electron/electron#23391]
ninjia -C out/Testing electron
src/electron/build/args/testing.gn --------------------------
import("all.gn")
is_debug = true  // my modify
is_component_build = true  // my modify
is_component_ffmpeg = true
is_official_build = false
dcheck_always_on = true
symbol_level = 2 // my modify
enable_desktop_capturer = false

blink_symbol_level = 2  // my add
target_cpu = "x64"   // my add
x64_arch = "haswell"   // my add

rtc_use_h264 = proprietary_codecs

---------------------------------------------------------------------
ninja build to [10041/10228] say
Undefined symbols for architecture x86_64:
  "chrome_browser_ssl::LegacyTLSExperimentConfig::LegacyTLSExperimentConfig()", referenced from:
      std::__1::__unique_if<chrome_browser_ssl::LegacyTLSExperimentConfig>::__unique_single std::__1::make_unique<chrome_browser_ssl::LegacyTLSExperimentConfig>() in libchrome.a(tls_deprecation_config.o)
  "mojo::StructTraits<blink::mojom::FetchAPIDataElementDataView, network::DataElement>::Read(blink::mojom::FetchAPIDataElementDataView, network::DataElement*)", referenced from:
      mojo::internal::Serializer<blink::mojom::FetchAPIDataElementDataView, network::DataElement>::Deserialize(blink::mojom::internal::FetchAPIDataElement_Data*, network::DataElement*, mojo::internal::SerializationContext*) in fetch_api_request.mojom.o
  "mojo::StructTraits<blink::mojom::FetchAPIRequestBodyDataView, scoped_refptr<network::ResourceRequestBody> >::Read(blink::mojom::FetchAPIRequestBodyDataView, scoped_refptr<network::ResourceRequestBody>*)", referenced from:
      mojo::internal::Serializer<blink::mojom::FetchAPIRequestBodyDataView, scoped_refptr<network::ResourceRequestBody> >::Deserialize(blink::mojom::internal::FetchAPIRequestBody_Data*, scoped_refptr<network::ResourceRequestBody>*, mojo::internal::SerializationContext*) in fetch_api_request.mojom.o
  "node::ResetStdio()", referenced from:
      electron::NodeMain(int, char**) in node_main.o
  "node::Environment::RunCleanup()", referenced from:
      electron::NodeMain(int, char**) in node_main.o
  "node::Environment::kNodeContextTagPtr", referenced from:
      node::Environment::GetCurrent(v8::Local<v8::Context>) in electron_api_protocol.o
      node::Environment::GetCurrent(v8::Local<v8::Context>) in electron_api_session.o
      node::Environment::GetCurrent(v8::Local<v8::Context>) in electron_api_system_preferences_mac.o
      node::Environment::GetCurrent(v8::Local<v8::Context>) in electron_api_url_loader.o
      node::Environment::GetCurrent(v8::Local<v8::Context>) in native_window_mac.o
      node::Environment::GetCurrent(v8::Local<v8::Context>) in electron_bindings.o
      node::Environment::GetCurrent(v8::Local<v8::Context>) in node_bindings.o
      ...
  "node::Environment::InitializeDiagnostics()", referenced from:
      electron::NodeBindings::CreateEnvironment(v8::Local<v8::Context>, node::MultiIsolatePlatform*) in node_bindings.o
      electron::NodeMain(int, char**) in node_main.o
  "node::Environment::stop_sub_worker_contexts()", referenced from:
      electron::NodeMain(int, char**) in node_main.o
  "node::native_module::NativeModuleEnv::LookupAndCompile(v8::Local<v8::Context>, char const*, std::__1::vector<v8::Local<v8::String>, std::__1::allocator<v8::Local<v8::String> > >*, node::Environment*)", referenced from:
      electron::util::CompileAndCall(v8::Local<v8::Context>, char const*, std::__1::vector<v8::Local<v8::String>, std::__1::allocator<v8::Local<v8::String> > >*, std::__1::vector<v8::Local<v8::Value>, std::__1::allocator<v8::Local<v8::Value> > >*, node::Environment*) in node_util.o
  "node::Assert(node::AssertionInfo const&)", referenced from:
      node::tracing::Agent::GetTracingController() in javascript_environment.o
      node::MutexBase<node::LibuvMutexTraits>::MutexBase() in node_debugger.o
  "webrtc::GetWindowOwnerPid(unsigned int)", referenced from:
      electron::NativeWindowMac::MoveAbove(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in native_window_mac.o
  "vtable for node::DebugOptions", referenced from:
      node::DebugOptions::DebugOptions(node::DebugOptions const&) in node_debugger.o
      node::DebugOptions::~DebugOptions() in node_debugger.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):
  File "../../build/toolchain/mac/linker_driver.py", line 287, in <module>
    Main(sys.argv)
  File "../../build/toolchain/mac/linker_driver.py", line 97, in Main
    subprocess.check_call(compiler_driver_args, env=env)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
-----------------------------------------------------------------------------------------

Which dylib are these symbols 
chrome_browser_ssl::LegacyTLSExperimentConfig::LegacyTLSExperimentConfig()
mojo::StructTraits
node::ResetStdio
"node::Environment::RunCleanup()"
"node::Environment::kNodeContextTagPtr"
"node::Environment::InitializeDiagnostics()"
"node::Environment::stop_sub_worker_contexts()"
"node::native_module::NativeModuleEnv::LookupAndCompile"
"node::Assert(node::AssertionInfo const&)"
"webrtc::GetWindowOwnerPid"

-----------------------------------------------------------------------------------------

**Comment by MarshallOfSound** [comment]
We do not support building Electron with `is_component_build`
