### ISSUE TITLE
Can't link python source to Electron

### ISSUE THREAD

**Issue by lvntky** [electron/electron#23390]
### Preflight Checklist

* [.] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [.] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [.] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details,
Hi, I have a python code that scrapes images by keyword, i want to make a GUI with electron but I can't connect my python script to my Electron GUI

* **Electron Version:**
  * v8.2.4
* **Operating System:**
  * Arch Linux x86_64
* **Last Known Working Electron version:**
  * v8.2.4

### Expected Behavior
When I click the scrap button, Electron needs to run my python script and scrap selected keywords.

### Actual Behavior
Nothing happen when I click the scrap button.

### Screenshots

![aaa](https://user-images.githubusercontent.com/42411502/80894641-4a8a0e00-8ccc-11ea-8367-29c19e17c3e3.png)

#### main.js function to call python
```
function get_scrap(){
  var python = require("python-shell")
  var path = require("path")

  var key1 = document.getElementById("key1").value
  document.getElementById("key1") = "";

  var key1 = document.getElementById("key2").value
  document.getElementById("key2") = "";

  var options = {
      scriptPath : path.join(__dirname, '/../engine/'),
      args : [key1, key2]
  }

  var scrap = new python('scraper.py', options);
  scrap.on('message', function(message){
      swal("scraping!")
  })
}
```
#### index.html file
```
<!DOCTYPE html>
<html>
  <head>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet"> 
  <link rel="stylesheet" type="text/css" href="styles.css">
  <script src="main.js"></script>
  
    
  </head>
  <body>
    <center>
    
  </center>
    
  
    <form>
      
    <div class="input-container">
      <input id="key1" type="text" required=""/>
      <label>First Keywod</label>		
    </div><br><br><br><br>
    <div class="input-container">
      <input type="text" required=""/>
      <label>Second Keywod</label>		
    </div><br><br><br><br>
    <div class="input-container">
      <input type="text" required=""/>
      <label>Path</label>		
    </div><br><br>
      
  </form>	
  </div>
  
</body>

<center>
<br><br><br><br>
<button onclick="get_scrap()">Scrap!</button>
</center> 
  </body>
 
</html>
```
#### python script

```
# importing google_images_download module
from google_images_download import google_images_download
import sys

response = google_images_download.googleimagesdownload()

# Can add more keywords
key1 = sys.argv[1]
key2 = sys.argv[2]
search_queries = [key1, key2]

    arguments = {"keywords": query,
                 "format": "jpg",
                 "limit": 5,
                 "print_urls": True,                 
                 "aspect_ratio": "panoramic"}
    try:
        response.download(arguments)

    # Handling File NotFound Error
    except FileNotFoundError:
        arguments = {"keywords": query,
                     "format": "jpg",
                     "limit": 5,
                     "print_urls": True,
                     "size": "medium"}

        # Providing arguments for the searched query
        try:
            # Downloading the photos based
            # on the given arguments
            response.download(arguments)
        except:
            pass


# Driver Code
for query in search_queries:
    downloadimages(query)
    print()

sys.stdout.flush()
```

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
