### ISSUE TITLE
Make minidump upload optional

### ISSUE THREAD

**Issue by Therealnaxos** [electron/electron#23410]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

As the minidump can contain sensitive information that is subject to GDPR, I do not want this file to leave the clients computer at all. (the [Crash Report Payload](https://www.electronjs.org/docs/api/crash-reporter#crash-report-payload) is enough data to detect crashes among install base)

### Proposed Solution

Ability to make the upload of the minidump file optional, with a `boolean` under [crashReporter.options](https://www.electronjs.org/docs/api/crash-reporter#crashreporterstartoptions)

**Comment by codebytere** [comment]
cc @nornagon you've work on some `crashReporter` stuff of late - do you have thoughts here?

**Comment by nornagon** [comment]
I don't believe crashpad supports this.

Further, I'm not sure what you would be able to determine about crashes without the minidump. You would have no stack trace information.

You can configure crashpad not to upload any data by setting `uploadToServer: false`. You could read the database yourself to produce a report containing the data you feel comfortable uploading.
