### ISSUE TITLE
Focus on detached DevTools window

### ISSUE THREAD

**Issue by joespina** [electron/electron#2341]
I made a simple contextMenu inspectElement function for easier developing, but the detached DevTools window is not focused on when I call `BrowserWindow.inspectElement()`. Any ideas on how to focus on the detached DevTools window? Thanks

working on windows7 btw.

**Comment by joespina** [comment]
A simple fix I made for this was to close DevTools `BrowserWindow.closeDevTools();` first then call `BrowserWindow.inspectElement(x,y);` it does the trick but being able to focus on DevTools on call would be nicer. Cheers!

**Comment by zcbenz** [comment]
Unable to reproduce in 0.37.x anymore.
