### ISSUE TITLE
Handle custom protocol in filter of webRequest.onBeforeRequest

### ISSUE THREAD

**Issue by mahnunchik** [electron/electron#23413]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

I've faced with the issue that I couldn't catch request by `webRequest.onBeforeRequest` if custom protocol was used in `filter`.

```js
mainWindow.webContents.session.webRequest.onBeforeRequest({
    urls: ['myscheme://*/*'],
}, (details, cb) => {
    console.log('onBeforeRequest:', details.url);
    cb({ cancel: false });
});
```

* **Electron Version:**
  * v8.2.5
* **Operating System:**
  * macOS 10.15.4

### Expected Behavior

Message in console like:

```bash
onBeforeRequest: myscheme://action/foobar
```

### Actual Behavior

The error on `onBeforeRequest` a call.

```
Uncaught Exception:
TypeError: Invalid url pattern myscheme://*/*: Wrong scheme type.
```

### To Reproduce

```js
mainWindow.webContents.session.webRequest.onBeforeRequest({
    urls: ['myscheme://*/*'],
}, (details, cb) => {
    console.log('onBeforeRequest:', details.url);
    cb({ cancel: false });
});
```

### Additional Information

Original question: https://stackoverflow.com/questions/61610086/typeerror-invalid-url-pattern-myscheme-wrong-scheme-type

**Comment by deepak1556** [comment]
@mahnunchik can you explain why you would want to intercept custom protocol requests with webrequest module, you should be able to handle any request related to the protocol in the handler you have registered.

**Comment by mahnunchik** [comment]
@deepak1556 

1. Window related (local) protocol handler.
2. Inspect any requests in `onBeforeRequest`.

**Comment by deepak1556** [comment]
Thanks for the context,

> Window related (local) protocol handler.

These requests are not handled by the webRequest module

If its a protocol not registered by your app then you can use [session.setPermissionRequestHandler](https://github.com/electron/electron/blob/master/docs/api/session.md#sessetpermissionrequesthandlerhandler) and listen for the `openExternal` permission to reject or accept it.

If you want to register a protocol for your app then use [app.setAsDefaultProtocolClient](https://github.com/electron/electron/blob/master/docs/api/app.md#appsetasdefaultprotocolclientprotocol-path-args)

> Inspect any requests in onBeforeRequest.

Can you provide an example scenario for why you would like to inspect custom protocols using webrequest ?

**Comment by mahnunchik** [comment]
> Can you provide an example scenario for why you would like to inspect custom protocols using webrequest ?

The scenario is auth: oAuth or 2FA.

To handle redirect to `myapp://` without leaving the app.

**Comment by deepak1556** [comment]
If you have registered a protocol handler for `myapp` then whatever redirect request is made to that url will hit the handler, you don't need to intercept via webrequest module.

**Comment by vladimiry** [comment]
@deepak1556, a quick question, so I know if I have to place the issue. Is it intended that a handler set by `session.setPermissionRequestHandler()` doesn't' get triggered for custom protocol? If it's intended then it's confusing since not being covered in the documentation.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
