### ISSUE TITLE
Electron Apps are crashing in Ubuntu 18.04 had experienced with microsoft teams and Draw io

### ISSUE THREAD

**Issue by surapuramakhil** [electron/electron#23426]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
I started using electron desktop apps on ubuntu. Initially, I was facing this with ms teams but thought it was app issue, later I am facing the same issue with other apps like draw io electron version.
I either of the cases I am switching from an electron version to a web version. and in the web version, I am facing glitch, the screen hangs, etc and I have to perform forced shutdown and restart the machine

* **Electron Version:**

  * 
* **Operating System:**
  * 
* **Last Known Working Electron version:**
  *

**Comment by codebytere** [comment]
Please raise this issue with the apps themselves.
