### ISSUE TITLE
display-metrics-changed not working on Catalina

### ISSUE THREAD

**Issue by infinite3219** [electron/electron#23421]
### Issue Details

* **Electron Version:**
v8.2.5
* **Operating System:**
Mac OS 10.15.4
* **Last Known Working Electron version:**
N/A. Failed on 9.0.0 beta as well.

### Expected Behavior
display-metrics-changed should fire when the app doc hides and unhides. 

### Actual Behavior
No screen workArea changes detected when app doc hides/unhides. It doesn't change even when you examine the value of it by looking at the display properties. i.e. event doesn't fire and even if you periodically check the value of workArea, it does not change.

### To Reproduce

Run code below that registers for display-metrics-changed changes and also checks if workArea changes every second. Hide and unhide app doc. Same code works on Mojave and Windows 10. Hide and unhide dock by making an any app go into full screen mode or wait for dock to hide on its own when set to automatically hide. It does work if you go into preferences and explicitly toggle the hide/unhide state, but not if it happens when any app goes into full screen mode or auto hides.

```
app.on('ready', () => {
  let height = 0, width = 0;
  screen.on('display-metrics-changed', (event, display, changedMetrics) => {
    console.log(`Changed info in event: `, event, display, changedMetrics);
  });
  setInterval(() => {
    let d = screen.getPrimaryDisplay();
    if (d.workArea.height !== height || d.workArea.width !== width) {
      console.log(`Changed display info `, d);
      height = d.workArea.height;
      width = d.workArea.width;
    }
  }, 1000);
});
```

**Comment by codebytere** [comment]
Right now the event is emitted when `bounds`,
`workArea`, `scaleFactor` or `rotation` are changed - the app window being hidden is not intended to affect display metrics - i don't believe this to be a bug.

If i click the fullscreen button the event is properly emitted on my machine running Catalina, as I expected. It also emitted as expected when i right clicked on the dock and clicked "Turn Hiding On"
