### ISSUE TITLE
openssl version in electron is 1.1.0

### ISSUE THREAD

**Issue by shubhamyelekar** [electron/electron#23423]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
I checked the openssl version in electron by looking at `process.versions.openssl` in the debugging window. I used electron 8.2.5 and node 14. The openssl version I can see from `process.versions.openssl` is 1.1.0

### Proposed Solution
As 1.1.0 is near its EOL is there any plan to move to openssl 1.1.1? Or is there any other way I can tell electron to use particular openssl version?

### Additional Information
I am not sure whether to raise it as a feature request or issue, so I just raised it here.

**Comment by codebytere** [comment]
@shubham2892 we don't use OpenSSL - we actually use BoringSSL as a function of Chromium. BoringSSL doesn't have versions per se, so there's no way to specify this. A version of Electron will contain whatever version of BoringSSL is in the version of Chromium it's shipped with.

**Comment by shubhamyelekar** [comment]
@codebytere 
As per my understanding electron comes with node. What about the version of openssl that comes with this node?
