### ISSUE TITLE
Release name 'linux-arm' is too vague e.g. (armv7 vs armv8)

### ISSUE THREAD

**Issue by maxogden** [electron/electron#2343]
the new arm release is called `electron-v0.30.1-linux-arm.zip`, but there are many different arm types:  armv6, armv7, armv8 and also armhf vs armel

iojs uses the format `armv7l` and `armv6l`: https://iojs.org/dist/v2.4.0/. would that make sense to use?

**Comment by zcbenz** [comment]
Sounds reasonable to me, I'm :+1: on the names used by iojs.

**Comment by vikbez** [comment]
:+1:

**Comment by shaunmulligan** [comment]
:+1: armv8 or Aarch64 would be much appreciated... Want to get some electron apps running on the Dragonboard 410c :smile:

**Comment by dignifiedquire** [comment]
@zcbenz @maxogden I want to work on this, but just to be clear this issue is only about changing the name of the output file correct?

**Comment by zcbenz** [comment]
Yeah changing the output name should do the most work, some scripts may fail because of the name change so make sure every script still works after the change.

**Comment by miladsajjadi** [comment]
@jlord i'm justr wanted to build my electron app for arm target. i'am not clear is my problem related to this topic or not.
can anybody explain to me how renaming the output is related to build an electron app for arm. is there really a build script that i can use and get arm version of my app??

**Comment by jeanbruder** [comment]
Dear Team, Please provide a prebuild package for version 1.4.15 for an arm64 board : Pine64 running the Longsleep Ubuntu release. Many thanks in advance, Regards.
