### ISSUE TITLE
Images used as CSS background-images from the appData folder do not load on Windows

### ISSUE THREAD

**Issue by somebeaver** [electron/electron#23435]
* [x] I have read the [Contributing Guidelines]
* [x] I agree to follow the [Code of Conduct]
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** v7.2.3 in my actual project, and up to v9.0.0-beta.13 in the Fiddle
* **Operating System:** Windows 10 (1903)
* **Last Known Working Electron version:**  N/A

### Expected Behavior
The inline CSS background-image should load load on Windows, like it does on macOS.

### Actual Behavior
The CSS background-image does not load, and the Network tab shows status=(failed)

### To Reproduce
ELECTRON FIDDLE: https://gist.github.com/2d2c059b6d28f7d85374979775164b52

**The Fiddle has to be tested on Windows**

Fiddle instructions: Choose any **image** on your computer using the file picker. It will be copied to `app.getPath('appData')` under a temporary folder, and this copy will be injected into the DOM twice using the exact same file path: once as an `<img>`, and once as a `<div>` with an inline background-image. The `<img>` works fine, but the `<div>` background only works on macOS.

On Windows, even though the background-image path is correct, the console shows it trying to load some malformed path when used as a CSS background-image.

Here are three screenshots that demonstrate the issue, in case the Fiddle does not:

https://i.imgur.com/xYUFoWR.png (inline css)
https://i.imgur.com/Azsh8vs.png (error in Console)
https://i.imgur.com/u47JzRF.png (error in Sources tab with full malformed path)

Note that these screenshots are from my actual project, not the Fiddle.

Thank you

**Comment by ahallicks** [comment]
Interestingly it works if you change the `\` to `\\`. I'm guessing this is the way Windows/CSSOM handles paths. You could just replace any `\` with `\\` to get it working. I'm not sure whether this is a bug or not!

**Comment by somebeaver** [comment]
I can confirm that changing all of the slashes to double slashes works, thank you for the fix.

But it does certainly feel like a bug to me. If single slashes work in `<img>` they should work in `background-image`, like on macOS, and like on the web with HTTP urls.

**Comment by miniak** [comment]
You should use https://nodejs.org/api/url.html#url_url_pathtofileurl_path

**Comment by islam-farahat** [comment]
background-image: url("~/src/assets/imgs/bg.jpg");
