### ISSUE TITLE
Provide the DOM element on which context menu was opened in the params object.

### ISSUE THREAD

**Issue by amanharwara** [electron/electron#23437]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

I want to get the DOM element on which the user right-clicks to open the context menu, but there doesn't seem to be a straight-forward method to get it.

### Proposed Solution

Possibly provide an `element` value in the context menu event's `param` object.

### Alternatives Considered

I tried using the `x` and `y` values provided in the `params` object of the context menu event, but that seems to give the `x` and `y` value of where the user clicked after opening the context menu, not where it opened.

**Comment by Slapbox** [comment]
@amanharwara did you find a workaround? If not, why close the issue?

This would be a big improvement!
