### ISSUE TITLE
unable to debug preload.js

### ISSUE THREAD

**Issue by NishantShenoy** [electron/electron#23430]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v7.2.4

* **Operating System:**
  * Windows 10 (1909) 

### Expected Behavior
Ability to set breakpoints in preload.js when running with `--inspect-brk`

### Actual Behavior
Breakpoints are not hit when running with `--inspect-brk`

### To Reproduce
Launch app using vscode launch json and then set breakpoints in chrome dev tools.

**Comment by codebytere** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment. This issue will be closed in 7 days if the above is not addressed.
