### ISSUE TITLE
Add `removeWordFromSpellcheckerDictionary` API

### ISSUE THREAD

**Issue by ahallicks** [electron/electron#23439]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Currently, the lovely new Spellchecker API works great and allows me to add custom words to the dictionary where I see fit. However, it does not, then, allow me to later remove those words from the custom dictionary.

Looking at https://github.com/electron/electron/issues/22161 this becomes even more complicated because I wouldn't just be able to clear the current Custom Dictionary either.

### Proposed Solution

It would be nice to have an API to remove a word from the Custom Dictionary if one exists. I guess this would also need to know whether the word under the cursor exists in the Custom Dictionary to start with.

### Alternatives Considered

Clearing the Custom Dictionary would be one way to achieve this, but it would also be very destructive if a user had added a lot of custom words to their Custom Dictionary.

I think I could probably roll my own version of this by loading the Custom Dictionary into my app and parsing its words to get custom entries but it would be awful and might break if something changed in the way Custom Dictionaries are stored/created/updated.

**Comment by codebytere** [comment]
This exists: https://github.com/electron/electron/pull/22039

**Comment by ahallicks** [comment]
![image](https://user-images.githubusercontent.com/717299/81784609-06c9ac80-94f5-11ea-8ead-96f52f33f28d.png)

Thanks @codebytere for the reply and for finding the API! I swear I searched everywhere for it. The docs site doesn't seem to reflect that the API exists either. It doesn't appear in the search or on [the session docs](https://www.electronjs.org/docs/api/session).

**Comment by codebytere** [comment]
@ahallicks that's true! that's the case because the docs only show the information for the current stable release - we're working to better show upcoming changes on the website. I recommend checking docs on this repo as well when searching for potential features - in the meantime, you can check it out via our latest nightlies :)

**Comment by ahallicks** [comment]
@codebytere Awesome. Thanks for the information 😄
