### ISSUE TITLE
Problem with Tray Icon after sleep mode for Linux

### ISSUE THREAD

**Issue by trae-op** [electron/electron#23448]
Hi. I have a problem with the Tray icon.

* **Electron Version:**
  * 8.2.5
* **Operating System:**
  * Ubuntu 18.04
* **Last Known Working Electron version:**
  * 7.2.4

### Expected Behavior
The Tray Icon always display after go out from sleep mode

### Actual Behavior
After go out from sleep mode the tray icon is hidden.

### Screenshots
If just start app after `npm start` see screen https://prnt.sc/scnq37 then go to sleep mode.
After go out from sleep mode the tray icon is hidden see screen https://prnt.sc/scnu75

### Additional Information
The problem in versions 8.0.0-8.2.5.
I installed a less v7.2.4 and it works. After sleep mode icon is display
My example https://github.com/trae-op/test-electron-app

**Comment by vladimiry** [comment]
Looks like it's a duplicate of https://github.com/electron/electron/issues/22443.

**Comment by trae-op** [comment]
> Looks like it's a duplicate of #22443.
I saw the link, but the problem I see is still not resolved

**Comment by Thatoo** [comment]
Same for Riot : https://github.com/vector-im/riot-web/issues/13692

**Comment by codebytere** [comment]
Closed by https://github.com/electron/electron/pull/23674.
