### ISSUE TITLE
npm package downloading is extremely slow.

### ISSUE THREAD

**Issue by mpmadhuranga** [electron/electron#23442]
Package download is very slow it does not ever go beyond 50Kbps 
I already used a mirror given on the official site  
`ELECTRON_MIRROR="https://npm.taobao.org/mirrors/electron/"`
Still the same.

**Comment by vladimiry** [comment]
Npm keeps only a minimal portion of stuff. Actual Electron bundle gets downloaded from https://github.com/electron/electron/releases.

**Comment by codebytere** [comment]
We don't control that mirror sadly - regrettably there's not much we can do to speed it up if your local connection is having issues.

**Comment by mpmadhuranga** [comment]
No, I don't have any issue with my local connection its totally with the mirror. I hope you can find a good mirror server to support, never had an issue with any other packages.

**Comment by Leskur** [comment]
If you have proxy, you can try this.

macOS
```bash
export ELECTRON_GET_USE_PROXY=http://127.0.0.1:8080
```

Windows
```bash
set ELECTRON_GET_USE_PROXY=http://127.0.0.1:8080
```
