### ISSUE TITLE
A similar of BrowserWindow.setBackgroundColor to tray 

### ISSUE THREAD

**Issue by MateusSoares895** [electron/electron#23452]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

I'm creating a code tray in electron for open favorites projects in vscode but 
I've come across a problem: the Tray object don't have a prop or method to change easily your background color like in BroswerWindow object.

### Proposed Solution

Create a method that work like BrowserWindow.setBackgroundColor()
like this:

```js
  const {  Tray } = require('electron')
  const { resolve } = require('path')
  const mainTray = new Tray(resolve(__dirname, 'assets', 'myIcon.png'))
  mainTray.setBackgroundColor('#383838')
```

### Alternatives Considered

Create a prop that when set to true change tray background color to #383838 when system theme is set to dark
Like this:
```js
  const {  Tray } = require('electron')
  const { resolve } = require('path')
  const mainTray = new Tray(resolve(__dirname, 'assets', 'myIcon.png'),
    {
      updateBackgroundColorWhenSystemThemeIsDark: true
    }
  )
```

**Comment by miniak** [comment]
Changing background color for a tray icon does not make sense.

**Comment by MateusSoares895** [comment]
@miniak  It's Not  to change the color of tray icon its to change tray color 

this:
![image](https://user-images.githubusercontent.com/59037640/85954305-df1b9000-b94c-11ea-9252-151c4bdca82e.png)
to this:
![image](https://user-images.githubusercontent.com/59037640/85954312-f2c6f680-b94c-11ea-94f1-2a69d2aee065.png)
