### ISSUE TITLE
Preload script and page can execute code while the page has a breakpoint

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#23455]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
* **Electron Version:** 8.2.3
* **Operating System:** Windows 10

My main process intercepts the window close, cancels it, and sends a message up to the page loaded in the window. That page then sends something back to the main process through the preload script.

This page has a button that triggers some code on which I've set a breakpoint.

When I hit that button and the breakpoint gets hit, my understanding is that the executing thread is suspended until I continue.

However, if I try closing the window, the message still gets intercepted by my page and a response is sent back even while I'm on a breakpoint.

How is this happening? Is this a bug?

I would have expected that the code in the page won't run until I continue the breakpoint.

### To Reproduce
main.js:
```
const { app, BrowserWindow, ipcMain } = require('electron')
const path = require("path");

async function createWindow() {
  const mainWindow = new BrowserWindow({ webPreferences: { nodeIntegration: false, preload: path.join(__dirname, "./preload.js") } });
  await mainWindow.loadFile("./index.html");
  mainWindow.webContents.openDevTools({ mode: "detach" });

  ipcMain.on("message", (e, arg) => {
    console.log(arg);
  });

  mainWindow.on("close", (e) => {
    e.preventDefault();
    mainWindow.webContents.send("closing");
  });
}

app.on('ready', createWindow)
```

index.html:
```
<body>
	<button id="b">Navigate</button>
	<script src="./renderer.js">
	</script>
</body>
```

renderer.js:
```
var b = document.getElementById("b");
b.onclick = () => {
	location.href = "about:blank";
}

const onClosing = () => {
	__sendMessage("this code is running");
};
__setCallback(onClosing)
```

preload.js:
```
const { ipcRenderer } = require('electron');

global.__sendMessage = function (a) {
	ipcRenderer.send("message", a);
}

let callback = () => { };
global.__setCallback = (cb) => {
	callback = cb;
};

ipcRenderer.on("closing", () => {
	callback();
});
```

Start the app and put a breakpoint in the button's onclick handler and in the main script's `ipcMain.on("message", ...);` handler.

Click the button. When the breakpoint gets hit, close the window. Notice that the main process' breakpoint gets hit even while we have a breakpoint in the page.

Is this a devtools/Chrome quirk? Or an Electron issue?

**Comment by codebytere** [comment]
JS being paused on a breakpoint does not prevent any JS running, it simples pauses that line of execution.  If an external trigger (i.e. IPC messages, executeJavaScript, etc.) triggers JS it will still run. 

You can run code in devtools console while JS execution is paused - this is the same underlying mechanism and is not a bug.
