### ISSUE TITLE
Whether the browser kernel can be changed？

### ISSUE THREAD

**Issue by malongqi** [electron/electron#23468]
We have a  demand that is asked to user  other browser kernel  . 
Whether the browser kernel can be changed

**Comment by UtkarshBhatthere** [comment]
Electron uses chromium core, are you asking for a change in that ?

**Comment by nornagon** [comment]
Electron is heavily tied to Chromium and changing it is not possible.

There are some other Electron-like projects that use alternative engines, for example [nw.js](https://nwjs.io/). There was an experiment from Mozilla a few years ago to build an Electron-like project on top of Firefox (https://github.com/mozilla/positron), but it is now defunct.
