### ISSUE TITLE
Electron app slow startup and lag

### ISSUE THREAD

**Issue by goceee** [electron/electron#23471]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.5
* **Operating System:**
  *  Windows 10 (1803)
* **Last Known Working Electron version:**
  * 4.1.4

### Expected Behavior

The program should start smooth and button animations should not lag.
### Actual Behavior

Application starts sluggishly, there is a lag when the window appears and the hover animations on the buttons are laggy. After moving around and hovering all the buttons for 2s the smoothness returns. When running the app using v4.1.4 of Electron the issue does not happen it is smooth from the start.
### To Reproduce
I can send the full code to someone willing to test it out.
Here is a snippet:
```function boot(){
	let mainWin = new BrowserWindow({
		width: 500,
		height: 500,
		frame: false,
		resizable:false,
		transparent: true,
		webPreferences: { 			nodeIntegration: true 		  },
		icon: path.join(__dirname, appIconDir, 'icon.ico') // add app icon
	})
	mainWin.loadFile('main.html');
}

app.on('ready', boot);
app.on('window-all-closed', () => {
	app.quit();
});
```
Tried also with:
```
mainWin.once('ready-to-show', () => {  mainWin.show()  }) and show: false in BrowserWindow settings.
```

**Comment by codebytere** [comment]
@goceee i experienced no specific issues with this snippet, and as Electron is a toolbox it's more likely that this is a function of your app's architecture and not of Electron itself. As we are not able to provide support for issues which are not in Electron's scope, i'm going to close this. However, if you are able to produce a standalone sample of this issue demonstrating it to be a direct result of Electron, we can take another look.
