### ISSUE TITLE
window7 32-bit

### ISSUE THREAD

**Issue by mapleby** [electron/electron#23478]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.2.4
* **Operating System:**
  * windows10(1909)
* **Last Known Working Electron version:**
  * 

### Expected Behavior

In Windows 7 32-bit, opendevtools() is debugged normally, and WebView. Print() is printed normally
### Actual Behavior

Opendevtools() can't open debugging in Windows 7 32-bit. WebView. Print() will jam the printer and send no data

**Comment by codebytere** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the `blocked` label for the above reasons. After you've responded, please @ me in a followup comment.
