### ISSUE TITLE
'webview' is not a known element

### ISSUE THREAD

**Issue by avinashseth** [electron/electron#23470]
i'm creating a desktop app using electron. We have a requirement of loading webpages and interacting with the web pages.

as per the documentations, this is our **main.js** file configuration 

    mainWindow = new BrowserWindow({
        width: 800,
        height: 600,
        webPreferences: {
          nodeIntegration: true,
          webviewTag: true <--------------- as said by the documentation
        }
      })

now is our **webpage.component.html** file we have added this tag

    <webview src="https://www.github.com/"></webview>

this is our **web-page.component.ts** file

    import { Component, OnInit } from '@angular/core';
    
    @Component({
      selector: 'webpage',
      templateUrl: './webpage.component.html',
      styleUrls: ['./webpage.component.scss']
    })
    export class WebpageComponent implements OnInit {
    
      constructor() { }
    
      ngOnInit(): void {
      }
    
    }

but we are getting this error again and again, we don't know what we are doing wrong!

>     ERROR in src/app/webpage/webpage.component.html:1:1 - error NG8001: 'webview' is not a known element:
>     1. If 'webview' is an Angular component, then verify that it is part of this module.
>     2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
>     
>     1 <webview src="https://www.github.com/"></webview>
>       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     
>       src/app/webpage/webpage.component.ts:5:16
>         5   templateUrl: './webpage.component.html',
>                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~
>         Error occurs in the template of component WebpageComponent.

I don't know why it is not working!

  [1]: https://github.com/electron/electron/blob/master/docs/api/webview-tag.md

**Comment by Lee182** [comment]
I think this is angular related see
https://github.com/Napster2210/ngx-spinner/issues/6

**Comment by codebytere** [comment]
Closing as this is an Angular issue and not one with Electron.
