### ISSUE TITLE
ChildProcess doesn't work when i builded app

### ISSUE THREAD

**Issue by kdrmlhcn** [electron/electron#23481]
> const child_process = require('child_process');
> 
> const phpserver = child_process.exec('php ppp/server.php', function (error, stdout, stderr) {
> 
>   if (error) throw error;
> 
>   console.log('stdout: ' + stdout);
>   console.log('stderr: ' + stderr);
> 
> });
> 
> phpserver.on('exit', function () {
>   console.log('Work is done.');
> });

I shared the code block above. When I build the application, I get the following error.
It works with "npm start" but does not work after it is builded.

<img width="799" alt="Ekran Resmi 2020-05-09 18 03 21" src="https://user-images.githubusercontent.com/17956350/81477238-64bd7200-921f-11ea-8f21-a956a773ac6d.png">

**Comment by nornagon** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by MarshallOfSound** [comment]
By default on macOS Cocoa application do not have access to your shells `PATH` variable when launched normally.  This means that spawning `php` will not work as there is no `PATH` variable for it to find the `php` executable on.

Either use an absolute path to the `php` binary or use something like [`fix-path`](https://www.npmjs.com/package/fix-path)

**Comment by hiukky** [comment]
@MarshallOfSound sorry to be opening this again but i have a similar problem, and to tell the truth i saw several issues about it but no solution .. actually i even saw some indications about lib fix-path but i was not successful.

I use Arch Linux and in the development environment it works normally, but when I compile for production I only get an error when trying to run my shell script.

I have tried several times with exec, execFile and the spawn itself but all have errors when executing my script.

I even got to separate the script in simple sh and test with execFile to see if it was any directory problem, but I was not successful.

Disabling the asar and running the sh file at the app's installation location, the script works, but when calling the child process the error occurs.

It's like he can't access the executable, not even using which to get the full path works. I just get the command error not found.

I even got to test my PATH env from my machine directly in development to see if I got an error but everything worked.

system: Arch Linux
electron: 9.2.0
electron-builder: 22.8.0
node: 14.7.0

**Comment by yiqianglin** [comment]
> @MarshallOfSound很抱歉再次打开它，但我遇到了类似的问题，说实话，我看到了几个关于它的问题，但没有解决方案.. 实际上我什至看到了一些关于 lib fix-path 的迹象，但我没有成功。
> 
> 我使用 Arch Linux 并且在开发环境中它可以正常工作，但是当我为生产进行编译时，我只会在尝试运行我的 shell 脚本时遇到错误。
> 
> 我曾多次尝试使用 exec、execFile 和 spawn 本身，但在执行我的脚本时都有错误。
> 
> 我什至必须将脚本分离为简单的 sh 并使用 execFile 进行测试以查看是否有任何目录问题，但我没有成功。
> 
> 禁用 asar 并在应用程序的安装位置运行 sh 文件，脚本可以工作，但是在调用子进程时会发生错误。
> 
> 就像他无法访问可执行文件，甚至无法使用它来获取完整路径。我只是得到找不到命令错误。
> 
> 我什至必须直接在开发中从我的机器测试我的 PATH 环境，看看我是否遇到错误，但一切正常。
> 
> 系统：Arch Linux 电子：9.2.0 电子生成器：22.8.0 节点：14.7.0

is there any solution?
