### ISSUE TITLE
 protocol.registerStreamProtocol is dead one file:// scheme

### ISSUE THREAD

**Issue by mihaiav** [electron/electron#23484]
### Issue Details
I'm trying to add extra headers(e.g. cache-control) to local files. It seems   protocol.registerStreamProtocol is the only way you can intercept requests and provide a complete response(headers, content etc). The issue is that (as I just found out) it's not working on the file scheme. Why is that ? The code below never throws:

```
 protocol.registerStreamProtocol('file', (request, callback) => {
       throw("we got this request");
}
```

* **Electron Version:**
  8.2.5
* **Operating System:**
 MacOS
* **Last Known Working Electron version:**
  8.2.5

### Expected Behavior
intercept all file requests (i.e. fetch requests and resources (css) requests
### Actual Behavior
It intercepts nothing.
### To Reproduce
on app "ready" event add the register below:

  ```
protocol.registerStreamProtocol('file', (request, callback) => {
       throw("we got this request");
}
```

**Comment by MarshallOfSound** [comment]
You can't register a protocol that already exists, you would have to register a custom protocol E.g. `protocol.registerStreamProtocol('my-custom-protocol')`

**Comment by MarshallOfSound** [comment]
See https://github.com/electron/electron/issues/23482#issuecomment-626952983 for original response on your issue
