### ISSUE TITLE
systemPreferences.getAccentColor() returns a darker shade of AccentColor in Windows 10

### ISSUE THREAD

**Issue by studiochris** [electron/electron#23487]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
8.2.5 (and 9.0.0-beta.23)
* **Operating System:**
Windows 10 Version 1909 (Build 18363.778)
* **Last Known Working Electron version:**
N/A

### Expected Behavior
On Windows 10, `systemPreferences.getAccentColor()` should return the exact accent color set in Settings > Personalization > Colors

### Actual Behavior
A darker shade of the accent color is returned. (Is this intentional?)

### To Reproduce
Electron Fiddle: 
https://gist.github.com/783503dad74daf2b6c8cda0fe6511fdf

**Enable the Stylesheet Editor  in Electron Fiddle before loading the gist or required styles will not be included.**

#### Default Blue
![image](https://user-images.githubusercontent.com/750698/81486666-2d44ca80-920b-11ea-96be-ef9e14b3b29a.png)

#### Yellow Gold
![image](https://user-images.githubusercontent.com/750698/81486693-611ff000-920b-11ea-9f00-52890b1c4f90.png)

#### Seafoam
![image](https://user-images.githubusercontent.com/750698/81486752-e5727300-920b-11ea-8cec-8e196cbf4209.png)

#### Automatic from Wallpaper
![image](https://user-images.githubusercontent.com/750698/81486726-a3e1c800-920b-11ea-8ea4-843138dc47c8.png)

**Comment by ahallicks** [comment]
Interestingly I see the same issue, but I also don't get my Windows Titlebar style any colour but white. Is there an extra setting for that somewhere in Windows?

The multiple firing is quite jarring too when selecting a different colour.

**Comment by studiochris** [comment]
The setting for colored title bars is in the Windows 10 Settings app.

Personalization > Colors

Then scroll to the bottom. The settings is "Show accent color on the following surfaces" — "Title bars and window borders" should be checked.

The color is only applied when the window is focused.

**Comment by MarshallOfSound** [comment]
@studiochris Are you sure that Electron's color is wrong?  Can you set the accent color to a specific hex code and then use a color picker to determine which color is correct.  I wouldn't be surprised if Windows used a slightly lighter color for the titlebar to allow for some contrast.

**Comment by studiochris** [comment]
@MarshallOfSound Thanks for taking a look at this. I am sure that Electron's color is wrong.

For the rest of the comment, let's work with Default Blue (`#0078d7`). Some screenshots may include a screen color picker showing hex color values.

**Screenshots from Windows 10's Settings app for Default Blue**

![image](https://user-images.githubusercontent.com/750698/81613947-2ac1ac80-9394-11ea-83a2-63f5b13eb4fe.png)
Default Windows color swatches

![image](https://user-images.githubusercontent.com/750698/81613841-fb12a480-9393-11ea-8a85-cded4c970e2a.png)
Dialog for choosing a custom accent color, with Default Blue selected

### Where is the accent color stored?

The accent color is stored in 3 different places in the Windows Registry (I've seen references to two of the entries in Electron's code).

They entries are in: `HKEY_CURRENT_USER\Software\Microsoft\Windows\DWM\`

And the keys referenced in Electron are: `AccentColor` and `ColorizationColor`.

The third key is `ColorizationAfterglow`. Searching for how this one is used, the only reference I found dealt with Xbox controllers, so maybe it's related to Xbox, but it seems to always be the accent color.

**Screenshot of the registry entries with Default Blue set as the accent color**

![image](https://user-images.githubusercontent.com/750698/81613451-5a23e980-9393-11ea-8a5c-c28144bdccf1.png)

Entries are highlighted in yellow. Values relevant to Electron are highlighted in green.

### How is the accent color stored?

For `AccentColor` and `ColorizationColor`, because they seem to be the relevant entries for Electron, the value is stored two ways. In hex format, `AccentColor` is AABBGGRR while `ColorizationColor` is AARRGGBB. 

### Moving back to Electron

...with the fiddle: https://gist.github.com/783503dad74daf2b6c8cda0fe6511fdf

#### Title bar with a color picker

The title bar is `#0078d7`, which is the correct accent color.

![image](https://user-images.githubusercontent.com/750698/81615121-ee8f4b80-9395-11ea-81c4-027c902b7c8d.png)

#### `<body> background` set to result of `systemPreferences.getAccentColor();`

`<body>`'s `background` is `#006FC7`, which is obtained through a call to `systemPreferences.getAccentColor()` when the fiddle referenced above is loaded. 

The value is passed to the window and stored as a CSS custom property.

![image](https://user-images.githubusercontent.com/750698/81615228-1ed6ea00-9396-11ea-9b46-cd8ddbdfd78a.png)

After the initial load, the CSS custom property is updated by listening to the `accent-color-changed` event in `main.js`. The event handler passes `newColor` to the Renderer process through `ipc`.

![image](https://user-images.githubusercontent.com/750698/81615765-fc919c00-9396-11ea-8ec1-286b34ee8182.png)

### A few other accent color uses throughout Windows

The accent color is not modified for use on title bars.

**Non-Electron Title Bar**

![image](https://user-images.githubusercontent.com/750698/81616880-32378480-9399-11ea-8b94-0b2ec8bcada6.png)

It's also not modified in the following cases (perhaps not relevant to Electron, but useful to show that the accent color remains consistent where it's used).

**Start Menu Tiles, for now**

![image](https://user-images.githubusercontent.com/750698/81616237-ff40c100-9397-11ea-9602-3f710705af9b.png)

**Form Controls**

![image](https://user-images.githubusercontent.com/750698/81618469-45981f00-939c-11ea-9fe9-fef0c3185b0f.png)

![image](https://user-images.githubusercontent.com/750698/81616426-4cbd2e00-9398-11ea-8811-9775c9e80cb9.png)

![image](https://user-images.githubusercontent.com/750698/81616521-75ddbe80-9398-11ea-88b7-173106312286.png)

**List Selection Indicators**

![image](https://user-images.githubusercontent.com/750698/81616590-9d348b80-9398-11ea-855f-65269d7794f0.png)

**Icons in the Settings app**

![image](https://user-images.githubusercontent.com/750698/81616268-0b2c8300-9398-11ea-91e8-a3ca40e45d98.png)

**Comment by codebytere** [comment]
@studiochris i'll try to look at this soon!

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!

**Comment by wildone** [comment]
Same issue in latest 25.6.0. :( color dont match.

**Comment by wildone** [comment]
Same issue in latest 25.6.0. :( color dont match.
