### ISSUE TITLE
Renderer-triggered file dialog prevents app close after selecting a file

### ISSUE THREAD

**Issue by Lovinity** [electron/electron#23497]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.5 & 9.0.4 with Node 12.16.2
* **Operating System:**
  * Windows 10 (1909)
* **Last Known Working Electron version:**
  * Not applicable (v8 is a complete rewrite of my previous app, and it has not yet worked)

### Expected Behavior
After loading a file dialog from the renderer process (triggered by tinyMCE) and selecting a file, I should still be able to close the application from the X button.

### Actual Behavior
When opening a file dialog (eg. to select a picture) triggered by tinyMCE in the renderer process, selecting a file results in the application no longer able to be closed except forcefully (it is unresponsive to clicking the X button). Not selecting a file and simply closing the dialog does not cause the bug; a file has to be chosen.

### To Reproduce
1. git clone https://github.com/Lovinity/wwsu-dj-controls.git
2. git checkout v8
3. npm install
4. npm start
5. Comment **ONLY** the last 5 characters of the "host ID" so I can grant you access to use the app
6. Once I comment saying you have access, close and re-load with npm start
7. In the renderer window left menu, click "Announcements".
8. Click the green "new announcements" button.
9. In the modal, scroll to "content". Click in the tinyMCE editor and then click the picture icon that appears by the typing cursor.
10. Choose any picture file to add.
11. Now, try to close the application with the X button. It does not close (even after closing the modal).

### Screenshots

Step 9:
![image](https://user-images.githubusercontent.com/11471458/81560966-6c386480-9360-11ea-9739-63b828a17049.png)

### Additional Information
I am not sure if this is a bug with Electron, tinyMCE, or iziModal. I've tried electron --inspect with chrome, but nothing helpful showed up in logs for debugging this issue (the only thing that showed up was the deprecation warning for allowRendererProcessReuse).

Guidance at least on how to debug this to determine the issue would be appreciated.

I will have to grant admin app permissions on the server so you can access "Announcements" on your end. However, this does not pose any security threat because the app still asks for credentials if you actually try to change something. But for reproduction of this bug, that is not necessary.

**Comment by Lovinity** [comment]
This bug also exists in v9.0.4

**Comment by Lovinity** [comment]
Additional information: After some digging, I have determined the bug was caused by TinyMCE's "autosave" plugin. The plugin had its own onbeforeunload event, which was supposed to ask the user in a dialog they had unsaved changes and if they really wanted to close. Instead, Electron simply does not close and does not show the dialog.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
