### ISSUE TITLE
Screen is blank

### ISSUE THREAD

**Issue by fabricus** [electron/electron#23492]
Hi,
When I log into my wallet I can see the details of the wallet of like a split seconds and then the screen becomes blank. If I open up the dev tools I'm seing the attached error list (and the list goes on on 404). What's wrong? Is there something I can do?

![Capture](https://user-images.githubusercontent.com/344270/81509165-040a6400-9309-11ea-96fe-119c975b36f3.PNG)

Thanks in advance,

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

**Comment by fabricus** [comment]
Thanks for answering but I'm not sure you've read my comment nor saw my screenshot? If this is not a bug report I don't know what this is? I literally have included a screenshot which shows dozen of errors and yet you call that "customer support" instead of a bug?
