### ISSUE TITLE
browserWindow.getPosition() and browserWindow.getSize() report the wrong values when maximized on Windows 10

### ISSUE THREAD

**Issue by somebeaver** [electron/electron#23498]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.5
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
I expect `browserWindow.getPosition()` to return `[0, 0]` when the window is maximized.

### Actual Behavior
Instead it returns `[-7, -7]`

### To Reproduce
FIDDLE: https://gist.github.com/8bbf14da9576f8dd5b4dc183fa71e3da

1. Run the Fiddle on Windows 10.
2. Press the maximize button in the browserWindow frame then don't resize anymore.
3. Check the console back in the main Fiddle window, it will report that the browserWindow position is `[-7, -7]` (or something similar, I've also seen `[-8, -8]` on a different PC).

The values reported by `browserWindow.getSize()` are also incorrect. When the position is at `[-7, -7]`, the width and height are each 14px off.

I do **not** believe it's related to this: https://github.com/electron/electron/issues/10862

I have tested this in two environments: one is a Parallels VM with resolution of 3360x2100 and 350% scale factor (these are recommended Parallels settings for a Macbook Pro) and Electron reports `[-7, -7]`. The other environment is a regular Windows machine set to 2560x1440 and 100% scale factor, and here Electron reports `[-8, -8]`.

Everything works fine in macOS.

**Comment by pushkin-** [comment]
I'm pretty sure this is standard Windows behavior. you'll notice that moving the window to 0,0 actually places it in a different position than -8,-8 which is used when maximized. pretty sure I saw a related issue here.

**Comment by pushkin-** [comment]
possibly related to [this](https://github.com/electron/electron/issues/4045)

**Comment by somebeaver** [comment]
It may be related, yes. But I don't think it's standard Window's behavior because if I use `browserWindow.setPosition(0, 0)` it will correctly position the window in the exact top-left, instead of a little bit inset had -7, -7 be the real 0, 0.

**Comment by pushkin-** [comment]
oh, maybe I meant to say Chrome behavior? filed Chrome [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=576192)

**Comment by somebeaver** [comment]
That Chrome bug was filed in 2016 and was closed due to inactivity. In the issue you linked, it seems like someone from Discord has trying to bring it to the attention of the Electron devs for a year. Guess this isn't going to get addressed any time soon.

**Comment by codebytere** [comment]
This is, unfortunately, Chromium behavior and not something easily fixed on our end without assuming nontrivial maintenance burden we're not currently prepared to assume. You're free to comment on the linked crbug or open a new one and when it's fixed on their end it'll be fixed on ours.

**Comment by asd281533890** [comment]
Still repro in 22.3.27.
