### ISSUE TITLE
element.scrollTop on chromium 80 on Mac retina not synced with view

### ISSUE THREAD

**Issue by jerome-birembaut** [electron/electron#23502]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
8.0.0
* **Operating System:**
macOS 10.15.4
* **Last Known Working Electron version:**
7.2.4

### Expected Behavior
when scrolling, element.scrollTop value should be synced with view

### Actual Behavior
when scrolling, element.scrollTop value is not synced with view especially on high framerate usage
so you have some jiggle effect, 

### To Reproduce
it's related to chromium update ( 80 on electron 8 ) and retina screen display
just try to use scrollTop value to stick some element  and you'll see it's not working well
it's synced on non retina display 

https://codepen.io/Seraf_NSS/pen/QWjxwVb
this is a simple demo that can be used on chromium > 80  ( it's not working too on current version of chrome mac retina)

**Comment by MarshallOfSound** [comment]
>  it's not working too on current version of chrome mac retina

This should be raised on the Chromium bug tracker then so that the appropriate team over their can follow up and triage.  Electron will pick up the fix once it's landed upstream

**Comment by jerome-birembaut** [comment]
for those who are interested with this issue, 
it will not be fixed by chrome team, it was done on purpose, to me it's weird.
this is how you can disable it on electron 8 >
app.commandLine.appendSwitch('disable-threaded-scrolling','true');
