### ISSUE TITLE
Window server2003 R2 Support？

### ISSUE THREAD

**Issue by winsonfeng** [electron/electron#23513]
Window server2003 R2 Support？

Error after running the packaged 32-bit exe file:
无法定位程序输入点 AcquireSRWLockExclusive 于动态链接库 Kernel32.dll 上
![image](https://user-images.githubusercontent.com/39331674/81633139-9e1ff880-943e-11ea-8f22-03b2327868af.png)

**Comment by MarshallOfSound** [comment]
We do not support windows server 2003.  Minimum requirements is Windows 7 which 2003 does not even come close to (it is XP era)
