### ISSUE TITLE
setProxy with pacScript not working in a remote session.

### ISSUE THREAD

**Issue by llehn** [electron/electron#23523]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  Tried 6, 7, 8 and 9-beta
* **Operating System:**
  Windows Server 2016
* **Last Known Working Electron version:**
  Can't get it to work.

### Expected Behavior
setProxy with pacScript works

### Actual Behavior
it doesn't work

### To Reproduce
I'm working on that

I have a very weird issue with not being able to get to work setProxy with pacScript.
setProxy itself succeedes, but all attempts to access any website result in ERR_MANDATORY_PROXY_CONFIGURATION_FAILED

Also every 8 seconds (which is the refresh time for failed pac files as per documentation) there is a heavy CPU Usage Spike to 40-50% total (on a dual-core machine), lasting for about 3-4 seconds.

This only happens in a remote session on a server, the setup is like this:
<local machine> connected to Citrix server showing <Remote Desktop> connected to the actual machine (virtual) running windows server.

What does work: 
-in this very remote session, accessing the pac file. I can download this very file from the same electron without any problems.
-the same pac file (same as with same contents, i.e. a copy) accessed by the same binary running on my local machine, works as it should.
-Chrome 78 is running in the remote session just fine, it autodetects and uses proxy settings
-Using the proxy specified in the pac file (this is my current workaround). 

I also have the weird problem described here: https://github.com/electron/electron/issues/20069

This looks like some kind of compatibility issue, but I'm kinda clueless how to find the cause. I'd love to help find that issue, but I need some ideas where to look.

**Comment by llehn** [comment]
This is a known compatibility issue with citrix. In case someone has the same problem there is a workaround: 
https://support.citrix.com/article/CTX265011

**Comment by leohxj** [comment]
the link is 404, can you explain how to resolve this issue?

**Comment by nornagon** [comment]
https://web.archive.org/web/20200416233612/https://support.citrix.com/article/CTX265011

> **Symptoms or Error**
> Issue: Electron- and Chromium-based apps may crash when launched seamlessly. 
>
> Workaround: Identify the process name that is crashing and add the following key in the VDA:
HKLM\SOFTWARE\Citrix\CtxHook\AppInit_DLLs\SfrHook\[processname]
> 
> Note: Citrix is aware of the issue and is working to address this issue long term.
> **Problem Cause**
> Problem Cause: Electron uses a delay hooking mechanism and this clashes or interferes with the Citrix hooks.
