### ISSUE TITLE
Issue with live media audio: "No audio channel exists"

### ISSUE THREAD

**Issue by Sergey-Churilin** [electron/electron#23529]
### Issue Details
Error in console  when using WebRTC APIs. 

* **Electron Version:**
  * 9.0.0-beta.24
* **Operating System:**
  * Windows 10 

### Expected Behavior
No error in console

### Actual Behavior
[304:0512/163130.458:ERROR:audio_rtp_receiver.cc(89)] AudioRtpReceiver::OnSetVolume: No audio channel exists.

### Additional Information
How to reproduce and other details are here: https://github.com/electron/electron/issues/11112#issuecomment-517856363

**Comment by hudzenko** [comment]
Happens on mac os as well

**Comment by ckerr** [comment]
I've created a repro gist for this @ https://gist.github.com/ckerr/d77e6880e34fb7a5b15c7febc9ce9359. It's basically just electron-quick-start + @msach22's repro code from https://github.com/electron/electron/issues/11112#issuecomment-517856363 and does show the "No audio channel exists" error message.

Tested on Ubuntu 20.10 with Electron 11.0.3.

**Comment by lxAppDev** [comment]
I can also confirm this issue on macOs

**Comment by idoodler** [comment]
I can confirm this issue also affects macOS

**Comment by nornagon** [comment]
Does this have any effect other than printing the console error?

**Comment by PxlLoewe** [comment]
@nornagon It does, sometimes you cant connect to a peer randomly or it depends on if you connect to a peer or the connects to you
