### ISSUE TITLE
https://www.electronjs.org/headers is not found

### ISSUE THREAD

**Issue by oldmtn** [electron/electron#23522]
I want to use electron headers deps.
But when I try to visit the page 'https://www.electronjs.org/headers', it show a 404 error.

**Comment by codebytere** [comment]
@oldmtn that link is not incorrect -it's a redirect. https://electronjs.org/headers/v7.2.4/node-v7.2.4-headers.tar.gz for example works just fine

**Comment by oldmtn** [comment]
Yes, It is.
Thanks
