### ISSUE TITLE
A HTTP request is sometime delayed, or arrives with the next request.

### ISSUE THREAD

**Issue by masa-a** [electron/electron#23520]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.5
* **Operating System:**
  * Ubuntu 18.04 x64/macOS 10.14.6
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior

- Running a express server in the main process.
- Another HTTP client process sends a HTTP request to the server.
- The express server receives the request from the client almost immediately.

### Actual Behavior

- Sometime(Roughly once in 20,000 times on Ubuntu) the express server doesn't receive the request quickly.
- If the delay happens, the request arrive after a few seconds.
- If the delay happens and a new request is sent while the first request is delayed, the two requests arrive together.

### To Reproduce
I made a simple example to reproduce the problem. First, clone and install packages.
```sh
$ git clone https://github.com/masa-a/electron_http_request_delayed
$ npm install
```

Then run the main process.
```sh
$ npm start
```

And also run the client process.
```sh
$ node client.js
```

If you use Ubuntu, the problem will be reproduced within 30 minutes. See the client process's output as it will stop and print "Delayed!" if the problem happens.

### Additional Information
The reason why I post this problem here is that if I run exactly the same program not `electron .` but `node main.js`, this problem doesn't happen. So electron should be doing something but as you can see from the example, it doesn't use any features Electron provide.
You can reproduce this problem in both Ubuntu and macOS but it's easier to reproduce the problem if you use Ubuntu. In macOS, sometimes it takes a few hours to reproduce.

According to wireshark's log, the client successfully sends the packet when the request is delayed. Somehow the main process ignores the packet until the next request is sent or a few seconds pass.

I made same client programs by other languages such as Python but the result is the same.

**Comment by saurav-jaat** [comment]
I want to contribute. Can you please guide me?

**Comment by masa-a** [comment]
@saurav-jaat Thank you! Though I haven’t found what exactly is causing this problem, my wild guess is that Electron wraps/intercepts sockets and it causes this as no Electron specific function is used in the repro code.
Finding what Electron is doing when it receives a socket is a good start.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
