### ISSUE TITLE
event.preventDefault() in Event: 'new-window' can not work when use remote

### ISSUE THREAD

**Issue by nrz123** [electron/electron#23521]
i use the remote to create browserwindow in Renderer Process.
and use event.preventDefault() in Event: 'new-window' to prevent Electron from automatically creating a new BrowserWindow.
but it did not work
is it a bug?

**Comment by MarshallOfSound** [comment]
No, `event.preventDefault()` must be called syncronously from when the event is emitted.  `remote` by nature is async in one direction so it is impossible to do it like this.

You should avoid using remote completely as it is full of footguns like this:

See: https://github.com/electron/electron/issues/21408

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
