### ISSUE TITLE
Electron 9.0.0-beta.24 missing signature (macOS)

### ISSUE THREAD

**Issue by pfrazee** [electron/electron#23534]
When I attempt to build `9.0.0-beta.24`, codesign fails with `"Electron Framework: code object is not signed at all"`. This doesn't occur for beta.22 so I assume the published build is just missing its signature (?).

**Comment by nornagon** [comment]
Seems like this is likely related to the crashpad binary having changed name.

**Comment by dkadrios** [comment]
This seems to be happening still in the 9.0.0 release?  Getting 'code object is not signed at all' in subcomponent 'chrome_crashpad_handler'

**Comment by MarshallOfSound** [comment]
This isn't a problem with electron, this is a flaw in your codesigning logic, if you're using electron-osx-sign you must update to the latest, if you're using something else unfortunately you're on your own with that.

**Comment by vitalykarasik** [comment]
I have the same issue, started after upgrade to Electron 9.0.0.

- I upgraded to the latest "electron-osx-sign": "0.4.17"
- added '--deep' into node_modules/app-builder-lib/electron-osx-sign/sign.js 

without success.
Any ideas?


-

**Comment by troeggla** [comment]
This happened to me too after upgrading to Electron 9.1.0. Upgrading `electron-builder` to version 22.7.0 solved the issue though.
