### ISSUE TITLE
BrowserWindow webPreferences / additionalArguments problem

### ISSUE THREAD

**Issue by alexey-fr** [electron/electron#23547]
Hi there.
here is the problem I am stuck on.
In the app I have 2 windows (BrowserWindow), with one of them I would like to communicate over the Chrome DevTools Protocol.
In order to make it possible I need to provide as additional argument to the process the "--remote-debugging-port=9222".
For this to work this way there is obviously the usefull "webPreferences / additionalArguments" option I could use to specify the port, and this is what I am trying to do:

let win1 = new BrowserWindow({ width: 800, height: 600, webPreferences: {additionalArguments: ["--remote-debugging-port=9222"]} })

let win2 = new BrowserWindow({ width: 800, height: 600 })

The problem is, it does not work. While the electron correctly passes the argument, I see it by the one process in the end (at the last place):
electron.exe --type=renderer --enable-features=WebComponentsV0Enabled --disable-features=SpareRendererForSitePerProcess --lang=de --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=5 --no-v8-untrusted-code-mitigations --mojo-platform-channel-handle=2376 /prefetch:1 **--remote-debugging-port=9222**

by the second window/process the argument is not there and this is correct, I only need to debug/inspect the one window.

A side note. There is another option, to include the argument (--remote-debugging-port=9222) by calling the electron application itself. The problem is, the argument gets passed to both windows, and the last window wins (I can connect to the port, but the window is the wrong one). This way it works incorrectly, but at least it opens the port, the difference to the case above - where it does not work at all - is, the argument gets passed to the window processes not at the last place but in the beginning:
electron.exe --type=renderer **--remote-debugging-port=9222** --enable-features=WebComponentsV0Enabled .... --mojo-platform-channel-handle=2808 /prefetch:1 

So being able to pass the required "--remote-debugging-port=9222" using "webPreferences / additionalArguments", the thing does not work (due to the place where the argument appears?).

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 7 days if the above is not addressed.
