### ISSUE TITLE
Frameless window doesn't have window buttons in fullscreen

### ISSUE THREAD

**Issue by astoilkov** [electron/electron#23558]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.5
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron version:**
  * don't know

### Expected Behavior

Entering fullscreen with frameless window to have the three window buttons.

### Actual Behavior

There are no buttons when frameless window is in fullscreen.

### To Reproduce

- clone `electron-quick-start-guide`
- set `frame: false` to the window

### Screenshots

Actual:
![image](https://user-images.githubusercontent.com/884810/81807501-dac71f00-9526-11ea-896d-81f3243fc4a6.png)

Expected:
![image](https://user-images.githubusercontent.com/884810/81807566-fd593800-9526-11ea-9923-804dbe999c36.png)

**Comment by ahallicks** [comment]
I believe this is intentional. From the docs:

> Instead of setting frame to false which disables both the titlebar and window controls

See https://www.electronjs.org/docs/api/frameless-window#alternatives-on-macos for a way to have both (kinda).

**Comment by astoilkov** [comment]
Hmm, interesting. Thanks. Maybe this should be closed. I will let the Electron team decide.

**Comment by codebytere** [comment]
@astoilkov yes - we recommend that you instead specify `titleBarStyle` on macOS.
