### ISSUE TITLE
unable to build and launch electron in SLES 11 workstation

### ISSUE THREAD

**Issue by AbinayaDevarajan** [electron/electron#23567]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 6.0.0 ,9.0.0
  * 
* **Operating System:** SLES11
  * 
* **Last Known Working Electron version:**
  * 

### Expected Behavior

Electron fails with libgtk3.0 and glibc dependent libraries.
### Actual 

- [x] Behavior

### To Reproduce

```
downloaded electron linux 64 bit version from https://github.com/electron/electron/releases/download/v6.0.0/electron-v6.0.0-linux-x64.zip

getting the below issue:

bash-3.00$ ls
10.0.0_electron         chrome_100_percent.pak  electron-v1.0.0-linux-x64.zip  libGLESv2.so          massif.out.17269  master.zip         swiftshader
6.0.0                   chrome_200_percent.pak  electron-v8.2.3-linux-x64.zip  libffmpeg.so          massif.out.17271  master.zip.1       v8_context_snapshot.bin
9.0.0_beta_electron     chromium                electron1.0.0                  libvk_swiftshader.so  massif.out.20434  out.txt            version
LICENSE                 content_shell.pak       icudtl.dat                     locales               massif.out.20437  resources          vk_swiftshader_icd.json
LICENSES.chromium.html  crashpad_handler        index.html                     massif.out.13580      massif.out.27489  resources.pak
chrome-sandbox          electron                libEGL.so                      massif.out.13614      massif.out.27491  snapshot_blob.bin
bash-3.00$ cd 6.0.0/
bash-3.00$ ls
LICENSE                 chrome_100_percent.pak  electron-v6.0.0-linux-x64.zip  libGLESv2.so  natives_blob.bin  snapshot_blob.bin        version
LICENSES.chromium.html  chrome_200_percent.pak  icudtl.dat                     libffmpeg.so  resources         swiftshader
chrome-sandbox          electron                libEGL.so                      locales       resources.pak     v8_context_snapshot.bin
bash-3.00$ electron
electron: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory



```

**Comment by ckerr** [comment]
Electron migrated from GTK2 to GTK3 at the same time that upstream project Chrome did.

Electron is a small project and it's not feasible for us to continue GTK2 support when Chrome is not, so this issue will not be fixed. I don't know the specifics of your boxen, but you may be able to resolve the issue by installing GTK3 alongside GTK2.
