### ISSUE TITLE
Failed to codesigh on electron 9.0.0-beta.24  MacOs Mojave 10.14.6

### ISSUE THREAD

**Issue by Sergey-Churilin** [electron/electron#23565]
### Issue Details

* **Electron Version:**
  * 9.0.0-beta.24
* **Operating System:**
  *  macOS Mojave 10.14.6
* **Last Known Working Electron version:**
  * 7.1.11

### Expected Behavior
Application builds without issues

### Actual Behavior
Errors in console and build fails

### Additional Information
Only electron version was changed from  **7.1.11** to **9.0.0-beta.24**. This leads to failing in build process

Console build error:
 signing         file=dist/mac/App.app identityName=Apple Development: user@gmail.com (111111) identityHash=222222 provisioningProfile=none
  Command failed: codesign --sign 22222222 --force --timestamp --options runtime --entitlements /Users/user/<pathToEntitlements>/entitlements.mac.inherit.plist /Users/user/<path>/mac/App.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
/Users/user/<path>/mac/App.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework: code object is not signed at all
In subcomponent: /Users/user/<path>/mac/App.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler
stackTrace=                                                                                                                                                                                       Error: Command failed: codesign --sign 2222222 --force --timestamp --options runtime --entitlements /Users/user/<pathToEntitlements>/entitlements.mac.inherit.plist /Users/user/<path>/mac/App.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
/Users/user/<path>/mac/App.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework: code object is not signed at all
In subcomponent: /Users/user/<path>/mac/App.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler
 at ChildProcess.exithandler (child_process.js:289:12)
at ChildProcess.emit (events.js:182:13)
at maybeClose (internal/child_process.js:961:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
From previous event:
at runCallback (timers.js:693:18)
at tryOnImmediate (timers.js:664:5)
at processImmediate (timers.js:646:5)
From previous event:
at MacPackager.signApp (/Users/user/<path>/node_modules/app-builder-lib/src/macPackager.ts:329:27)
at MacPackager.doPack (/Users/user/<path>/node_modules/app-builder-lib/src/platformPackager.ts:244:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by MarshallOfSound** [comment]
Duplicate https://github.com/electron/electron/issues/23534

Update the version of `electron-osx-sign`.  If you aren't using that package to codesign, raise a bug with whatever package you are using and link them to the fix for electron-osx-sign

https://github.com/electron/electron-osx-sign/pull/228
