### ISSUE TITLE
When the URL changes, the page refresh effect is inconsistent with Chrome

### ISSUE THREAD

**Issue by mtrucc** [electron/electron#23583]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.5
* **Operating System:**
  * macOS 10.15.4
* **Last Known Working Electron version:**
  * 9.0.0

### Expected Behavior

After changing the URL, the page refresh effect is the same as Chrome

### Actual Behavior

![ezgif com-crop](https://user-images.githubusercontent.com/16724665/81887282-541b4c00-95d1-11ea-84a0-9cc221caef47.gif)

For example, the page is similar to aaa.com/page/1, and then becomes aaa.com/page/2. After replacing the electronics, the path will be refreshed
The performance of the browser is: refresh is not white, but the content of the page has changed
The performance of the electronic device is: the refresh becomes white, flashes, and the page content has changed

### To Reproduce

```js
 const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      nodeIntegration: true,
      plugins:true
    },
  });
  mainWindow.loadURL("https://www.electron.build/configuration/dmg");
```

### Screenshots

![ezgif com-crop](https://user-images.githubusercontent.com/16724665/81887282-541b4c00-95d1-11ea-84a0-9cc221caef47.gif)

### Additional Information

I add a index.html file
`<webview id="foo" src="https://www.electron.build/configuration/dmg" style="display:inline-flex; width:100%; height:480px"></webview>`
main.js
`mainWindow.loadURL("file://" + __dirname + "/index.html");`
Still can't solve the problem well

**Comment by MarshallOfSound** [comment]
As you noted Electron 9 works as expected.  In Electron 8 you can enable `app.allowRendererProcessReuse` to get the same effect.
