### ISSUE TITLE
'Version mismatch between V8 binary and snapshot' (Win 10)

### ISSUE THREAD

**Issue by pfrazee** [electron/electron#23584]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 9.0.0-beta.24
* **Operating System:** Windows 10 (1809)
* **Last Known Working Electron version:** 9.0.0-beta.22

### Issue

My built & installed Electron app fails with the following error during startup

```
#
# Fatal error in , line 0
# Version mismatch between V8 binary and snapshot.
#   V8 binary version: 8.3.110.7-electron.0
#    Snapshot version: 8.3.110.8-electron.0
# The snapshot consists of 170878 bytes and contains 3 context(s).
#
#
#
#FailureMessage Object: 000000C1478FE840
```

Possibly related: https://github.com/electron/electron/issues/22450

I was able to confirm this doesnt occur with 9.0.0-beta.22

**Comment by jkleinsc** [comment]
@pfrazee do you generate your own snapshot file?

**Comment by pfrazee** [comment]
@jkleinsc I don't *think* so, you can see my `electron-builder` settings here: https://github.com/beakerbrowser/beaker/blob/master/scripts/package.json

**Comment by jkleinsc** [comment]
@pfrazee what is the size (in bytes) of snapshot_blob.bin and v8_context_snapshot.bin?

**Comment by pfrazee** [comment]
```
snapshot_blob.bin: 50580
v8_context_snapshot.bin: 170878
```

**Comment by jkleinsc** [comment]
Hmm... If I download the 9.0.0-beta.24 release on Windows 10 and run electron-quick-start I don't see that error and it has the same file sizes
 50,580 snapshot_blob.bin
 170,878 v8_context_snapshot.bin

**Comment by pfrazee** [comment]
@jkleinsc Did you generate an installer and run the installed version?

I'm short on time or I'd do that myself -- I can wait to see if this resolves with the subsequent release and close if it does.

**Comment by jkleinsc** [comment]
@pfrazee I can try that
