### ISSUE TITLE
Multiple windows are opening while running Spectron script.

### ISSUE THREAD

**Issue by sddddfdfdf** [electron/electron#23586]
Pls check below code:-
this is happening for all most all the version 6.9.0,3.8.0 etc.
it('Launching the application',function () {
     const opts = {
 
  path: 'C:/Spectronexcecution/Postman/app-7.20.1/Postman.exe'

};

const app = new Application(opts);
return app.start(); 

  })

**Comment by miniak** [comment]
Please report to Spectron
