### ISSUE TITLE
`debugger` methods `Fetch.getResponseBody` and `Network.getResponseBody` do not work

### ISSUE THREAD

**Issue by Sentero-esp12** [electron/electron#23594]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.2.5
* **Operating System:**
  * Windows 7 64
* **Last Known Working Electron version:**
  * 

### Expected Behavior

Using `Fetch.getResponseBody` and `Network.getResponseBody` should return the response body of a request
### Actual Behavior

Nothing happens, the callbacks never fire
### To Reproduce

Here's my code:
```
 try {
      win.webContents.debugger.attach('1.3')
   } catch (err) {
      console.log('Debugger attach failed : ', err)
   }

win.webContents.debugger.sendCommand("Fetch.enable",
      {
         patterns: [{
            requestStage: "Response",
            resourceType: "Document"
         }]
      }, (e) => {
         console.log('fetch enabled')
      })

  win.webContents.debugger.on('message', (event, method, params, resourceType) => {

if (method === "Fetch.requestPaused") {   //request paused and ready to be intercepted
         console.log(method, params, params.request.url) //this gets printed

         win.webContents.debugger.sendCommand("Fetch.getResponseBody",
         { requestId: params.requestId }, (body, base64) => {
            console.log(body, 'got Response and modifying it') //nothing gets printed
})
})
```

I've also tried with `Network.getResponseBody`, 
```
if (method === 'Network.requestWillBeSent') {
          console.log(params, 'network') //this gets printed
         if (params.type === 'Document') {
           console.log('document', params.requestId) //this also gets printed
            win.webContents.debugger.sendCommand('Network.getResponseBody', { requestId: params.requestId }, (body, body64) => {
               console.log(body, 'got Response and modifying it') //this doesn't get printed


```
It works through a Chrome Extension (in Chrome), and the request body is received, but in Electron the request gets stuck in a paused state

**Comment by Sentero-esp12** [comment]
Here is a minimal reproducible example if someone could check if it works for them: https://github.com/Sentero-esp12/reproduce-fetch-network

**Comment by eran-broder** [comment]
following. 
any luck? @Sentero-esp12

**Comment by Sentero-esp12** [comment]
Doesn't seem to work in 10.1.3 either.

**Comment by Sentero-esp12** [comment]
It appears the problem might be that callbacks aren't getting fired.
For example:
win.webContents.debugger.attach('1.3', ()=>{ /* it doesn't go here */ })

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!

**Comment by im-sorry** [comment]
> It appears the problem might be that callbacks aren't getting fired. For example:
> 
> ```
> win.webContents.debugger.attach('1.3', ()=>{ /* it doesn't go here */ })
> ```
> 
> This seems to work:
> 
> ```
> let body = await win.webContents.debugger.sendCommand("Fetch.getResponseBody",
> { requestId: String(requestId) })
> console.log(body)
> ```

thanks for your answer🙏🏻🙏🏻🙏🏻,it`s very useful
