### ISSUE TITLE
offer the possibility to change destination folder AND to disable the update mechanism

### ISSUE THREAD

**Issue by ks1977** [electron/electron#23601]
Hello, 

I work as an application packager in a large financial company.  I noticed that applications packaged using electron, simply force themselves in the %LOCALAPPDATA% folder on Windows without notice and without giving the user/IT administrator the possibility to change this folder.

Problem 1: often large companies like ours have policies that prevent users from launching executables from other directories than %ProgramFiles% or %ProgramFiles(x86)%.

Problem 2: since there doesn't seem to be a way either to disable automatic updates (also often forbidden for users by the same policies), electron wrapped applications become virtually unusable in such companies.  I understand electron is quite easy for developers to wrap and distribute their apps, but could they please become aware of the fact that company users are not home users!  They don't have the rights to install/run/update from no matter which directory.

Suggestion: please make it possible (at least for IT admins) to change the destination directory AND to disable any form of automatic updates!  Trust me: the majority of installers have this.  E.g.: MSI technology, setup.exe + command line parameters, etc.

Thanks a million!

**Comment by MarshallOfSound** [comment]
Both of these are problems specific to various packaging systems that electron apps may use but are not built in to Electron core.  These issues have also been discussed at length elsewhere and Electron is not going to adjudicate or force decisions on app developers RE their packaging and updating decisions.

**Comment by Neustradamus** [comment]
There is a problem in several installers, there is no possibility to select the installation folder.
By default it is in %LOCALAPPDATA%, it must be replaced by %PROGRAMFILES%.

32-bit and 64-bit:
- "Program Files" on 32-bit or 64-bit OS: %ProgramFiles%
- "Program Files (x86)" for 32-bit applications on 64-bit OS: %ProgramFiles(x86)%

Important:
- The user profile must be in %APPDATA%
- The cache must be in %LOCALAPPDATA%

For example, Mozilla Firefox has:
- Install folder: %PROGRAMFILES%\Mozilla Firefox
- Profile folder: %APPDATA%\Mozilla\Firefox
- Cache folder: %LOCALAPPDATA%\Mozilla\Firefox

More informations about folders in Microsoft Windows:

1/ %PROGRAMFILES% is a folder first found in Microsoft Windows 95 and included in all later versions of Microsoft Windows that stores the software programs installed on the computer.

2/ %USERNAME%\AppData
- Local: This folder stores device-specific settings and temporary files. There is a separate %LOCALAPPDATA% environment variable for this folder that you can use in your batch files and scripts.
- LocalLow: Here, Windows mainly stores buffer data generated by various applications (Internet Explorer, Java, Adobe, etc.). It is also used by low-level access systems, for example, for your browser's temporary files when working in Protected View. This directory also cannot be moved to another computer.
- Roaming: You can transfer files from this folder to another computer. The Roaming folder stores browser data, bookmarks, etc. This directory allows users to always work with a familiar environment on any server in the Remote Desktop Services farm when using roaming profiles or user profile disks. The environment variable for this directory is %APPDATA%.

Thanks in advance.
