### ISSUE TITLE
Electron(6.1.7) crash at blink::protocol::DictionaryValue::~DictionaryValue()

### ISSUE THREAD

**Issue by oldmtn** [electron/electron#23604]
Build a nodejs addon and run an electron app, but it crashed sometime with below dmp.

> 
Operating system: Mac OS X
                  10.14.6 18G87
CPU: amd64
     family 6 model 142 stepping 9
     4 CPUs

GPU: UNKNOWN

Crash reason:  0x00000000 / 0x00000000
Crash address: 0x7fff7846a2c6
Process uptime: 55 seconds

Thread 0 (crashed)
 0  libsystem_kernel.dylib + 0x72c6
    rax = 0x0000000000000000   rdx = 0x0000000000000000
    rcx = 0x00007ffeeea7fa68   rbx = 0x000000010aaa45c0
    rsi = 0x0000000000000006   rdi = 0x0000000000000307
    rbp = 0x00007ffeeea7faa0   rsp = 0x00007ffeeea7fa68
     r8 = 0x0000000000000000    r9 = 0x00007ffeeea7f9c0
    r10 = 0x0000000000000000   r11 = 0x0000000000000206
    r12 = 0x0000000000000307   r13 = 0x0000000107e12000
    r14 = 0x0000000000000006   r15 = 0x000000000000002d
    rip = 0x00007fff7846a2c6
    Found by: given as instruction pointer in context
 1  libsystem_c.dylib + 0x5b6a6
    rbp = 0x00007ffeeea7fad0   rsp = 0x00007ffeeea7fab0
    rip = 0x00007fff783d46a6
    Found by: previous frame's frame pointer
 2  libsystem_malloc.dylib + 0xb077
    rbp = 0x00007ffeeea7fb30   rsp = 0x00007ffeeea7fae0
    rip = 0x00007fff784e3077
    Found by: previous frame's frame pointer
 3  libsystem_malloc.dylib + 0x23e0d
    rbp = 0x00007ffeeea7fc10   rsp = 0x00007ffeeea7fb40
    rip = 0x00007fff784fbe0d
    Found by: previous frame's frame pointer
 4  libsystem_malloc.dylib + 0x784b
    rbp = 0x00007ffeeea7fc40   rsp = 0x00007ffeeea7fc20
    rip = 0x00007fff784df84b
    Found by: previous frame's frame pointer
 5  libsystem_malloc.dylib + 0x521c
    rbp = 0x00007ffeeea7fcd0   rsp = 0x00007ffeeea7fc50
    rip = 0x00007fff784dd21c
    Found by: previous frame's frame pointer
 6  libsystem_malloc.dylib + 0x4d79
    rbp = 0x00007ffeeea7fd30   rsp = 0x00007ffeeea7fce0
    rip = 0x00007fff784dcd79
    Found by: previous frame's frame pointer
 7  Electron Framework!blink::protocol::DictionaryValue::~DictionaryValue() [new : 319 + 0x8]
    rbp = 0x00007ffeeea7fd60   rsp = 0x00007ffeeea7fd40
    rip = 0x000000010289cae8
    Found by: previous frame's frame pointer
 8  Electron Framework!<name omitted> [Protocol.cpp : 564 + 0x5]
    rbp = 0x00007ffeeea7fd80   rsp = 0x00007ffeeea7fd70
    rip = 0x000000010289cb7e
    Found by: previous frame's frame pointer
 9  Electron Framework!blink::protocol::Network::RequestWillBeSentNotification::serializeToBinary() [memory : 2338 + 0x9]
    rbp = 0x00007ffeeea7fdb0   rsp = 0x00007ffeeea7fd90
    rip = 0x00000001028bae4d
    Found by: previous frame's frame pointer
10  Electron Framework!blink::protocol::InternalResponse::serializeToBinary() [Protocol.cpp : 1173 + 0xd]
    rbp = 0x00007ffeeea7fe40   rsp = 0x00007ffeeea7fdc0
    rip = 0x000000010289f3b9
    Found by: previous frame's frame pointer
11  Electron Framework!blink::DevToolsSession::Notification::Serialize() [Forward.h : 83 + 0xa]
    rbp = 0x00007ffeeea7fed0   rsp = 0x00007ffeeea7fe50
    rip = 0x00000001058d1329
    Found by: previous frame's frame pointer
12  Electron Framework!blink::DevToolsSession::flushProtocolNotifications() [devtools_session.cc : 363 + 0x9]
    rbp = 0x00007ffeeea7ff30   rsp = 0x00007ffeeea7fee0
    rip = 0x00000001058d1194
    Found by: previous frame's frame pointer
13  Electron Framework!<name omitted> [devtools_session.cc : 198 + 0x6]
    rbp = 0x00007ffeeea7ff50   rsp = 0x00007ffeeea7ff40
    rip = 0x00000001058cefaa
    Found by: previous frame's frame pointer
14  Electron Framework!base::sequence_manager::internal::SequenceManagerImpl::NotifyDidProcessTask(base::sequence_manager::internal::SequenceManagerImpl::ExecutingTask*, base::sequence_manager::LazyNow*) [sequence_manager_impl.cc : 759 + 0x9]
    rbp = 0x00007ffeeea7ffe0   rsp = 0x00007ffeeea7ff60
    rip = 0x00000001035bbb9d
    Found by: previous frame's frame pointer
15  Electron Framework!base::sequence_manager::internal::SequenceManagerImpl::DidRunTask() [sequence_manager_impl.cc : 590 + 0xb]
    rbp = 0x00007ffeeea80040   rsp = 0x00007ffeeea7fff0
    rip = 0x00000001035bb4f1
    Found by: previous frame's frame pointer
16  Electron Framework!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::sequence_manager::LazyNow*, bool*) [thread_controller_with_message_pump_impl.cc : 381 + 0x6]
    rbp = 0x00007ffeeea80190   rsp = 0x00007ffeeea80050
    rip = 0x00000001035c448d
    Found by: previous frame's frame pointer
17  Electron Framework!non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() [thread_controller_with_message_pump_impl.cc : 265 + 0x8]
    rbp = 0x00007ffeeea801d0   rsp = 0x00007ffeeea801a0
    rip = 0x00000001035c4907
    Found by: previous frame's frame pointer
18  Electron Framework!base::MessagePumpCFRunLoopBase::RunWork() [message_pump_mac.mm : 489 + 0x6]
    rbp = 0x00007ffeeea80200   rsp = 0x00007ffeeea801e0
    rip = 0x0000000103623073
    Found by: previous frame's frame pointer
19  Electron Framework!base::mac::CallWithEHFrame(void () block_pointer) + 0xa
    rbp = 0x00007ffeeea80210   rsp = 0x00007ffeeea80210
    rip = 0x000000010355a90a
    Found by: previous frame's frame pointer
20  Electron Framework!base::MessagePumpCFRunLoopBase::RunWorkSource(void*) [message_pump_mac.mm : 463 + 0x5]
    rbp = 0x00007ffeeea80250   rsp = 0x00007ffeeea80220
    rip = 0x00000001036229df
    Found by: previous frame's frame pointer
21  CoreFoundation + 0x57683
    rbp = 0x00007ffeeea80260   rsp = 0x00007ffeeea80260
    rip = 0x00007fff4c3d5683
    Found by: previous frame's frame pointer
22  CoreFoundation + 0x57629
    rbp = 0x00007ffeeea80290   rsp = 0x00007ffeeea80270
    rip = 0x00007fff4c3d5629
    Found by: previous frame's frame pointer
23  CoreFoundation + 0x3afeb
    rbp = 0x00007ffeeea80300   rsp = 0x00007ffeeea802a0
    rip = 0x00007fff4c3b8feb
    Found by: previous frame's frame pointer
24  CoreFoundation + 0x3a5b5
    rbp = 0x00007ffeeea81010   rsp = 0x00007ffeeea80310
    rip = 0x00007fff4c3b85b5
    Found by: previous frame's frame pointer
25  CoreFoundation + 0x39ebe
    rbp = 0x00007ffeeea810a0   rsp = 0x00007ffeeea81020
    rip = 0x00007fff4c3b7ebe
    Found by: previous frame's frame pointer
26  Foundation + 0x1c7df
    rbp = 0x00007ffeeea810e0   rsp = 0x00007ffeeea810b0
    rip = 0x00007fff4e61c7df
    Found by: previous frame's frame pointer
27  Electron Framework!base::MessagePumpNSRunLoop::DoRun(base::MessagePump::Delegate*) [message_pump_mac.mm : 767 + 0x10]
    rbp = 0x00007ffeeea81120   rsp = 0x00007ffeeea810f0
    rip = 0x0000000103623581
    Found by: previous frame's frame pointer
28  Electron Framework!base::MessagePumpCFRunLoopBase::Run(base::MessagePump::Delegate*) [message_pump_mac.mm : 186 + 0xc]
    rbp = 0x00007ffeeea81160   rsp = 0x00007ffeeea81130
    rip = 0x00000001036223a8
    Found by: previous frame's frame pointer
29  Electron Framework!non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) [thread_controller_with_message_pump_impl.cc : 466 + 0x6]
    rbp = 0x00007ffeeea81190   rsp = 0x00007ffeeea81170
    rip = 0x00000001035c4dd8
    Found by: previous frame's frame pointer
30  Electron Framework!base::RunLoop::RunWithTimeout(base::TimeDelta) [run_loop.cc : 161 + 0xc]
    rbp = 0x00007ffeeea81220   rsp = 0x00007ffeeea811a0
    rip = 0x0000000103596b37
    Found by: previous frame's frame pointer
31  Electron Framework!content::RendererMain(content::MainFunctionParams const&) [renderer_main.cc : 208 + 0x5]
    rbp = 0x00007ffeeea812e0   rsp = 0x00007ffeeea81230
    rip = 0x00000001068b0e00
    Found by: previous frame's frame pointer
32  Electron Framework!content::ContentMainRunnerImpl::Run(bool) [content_main_runner_impl.cc : 873 + 0x5]
    rbp = 0x00007ffeeea81350   rsp = 0x00007ffeeea812f0
    rip = 0x00000001028f9e8f
    Found by: previous frame's frame pointer
33  Electron Framework!service_manager::Main(service_manager::MainParams const&) [main.cc : 422 + 0xa]
    rbp = 0x00007ffeeea81670   rsp = 0x00007ffeeea81360
    rip = 0x0000000104c92ab0
    Found by: previous frame's frame pointer
34  Electron Framework!content::ContentMain(content::ContentMainParams const&) [content_main.cc : 19 + 0x8]
    rbp = 0x00007ffeeea81700   rsp = 0x00007ffeeea81680
    rip = 0x0000000101b872b4
    Found by: previous frame's frame pointer
35  Electron Framework!AtomMain [atom_library_main.mm : 23 + 0x5]
    rbp = 0x00007ffeeea81780   rsp = 0x00007ffeeea81710
    rip = 0x00000001011c45d4
    Found by: previous frame's frame pointer
36  RTCDemo Helper (Renderer)!main [atom_main.cc : 232 + 0xb]
    rbp = 0x00007ffeeea81850   rsp = 0x00007ffeeea81790
    rip = 0x000000010117f705
    Found by: previous frame's frame pointer
37  libdyld.dylib + 0x163d5
    rbp = 0x00007ffeeea81868   rsp = 0x00007ffeeea81860
    rip = 0x00007fff7832f3d5
    Found by: previous frame's frame pointer
38  libdyld.dylib + 0x163d5
    rbp = 0x00007ffeeea81868   rsp = 0x00007ffeeea81868
    rip = 0x00007fff7832f3d5
    Found by: stack scanning

>

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 7.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.
