### ISSUE TITLE
FPS Meter

### ISSUE THREAD

**Issue by Nic01as** [electron/electron#23610]
Hello, 
I want to show or hide "FPS meter" when app is ready.
![image](https://user-images.githubusercontent.com/26201907/82073176-2ae5e300-96d9-11ea-8e0f-0d5c6d54073e.png)

I can start fps meter before app is ready with 
`app.commandLine.appendSwitch("show-fps-counter");`

but after, I don't find exemple. We can do that (show or hide "FPS meter" when page is open) with google chrome in rendering tab here : 
![image](https://user-images.githubusercontent.com/26201907/82073354-6bddf780-96d9-11ea-8a55-7b4b6b77aa82.png)

Thanks for your help!

**Comment by MarshallOfSound** [comment]
You can use the `webContents.debugger` API to send the [`Overlay.setShowFPSCounter`](https://chromedevtools.github.io/devtools-protocol/tot/Overlay/#method-setShowFPSCounter) message

**Comment by Nic01as** [comment]
thanks !!

working good with : `
var showFPS = false;

var toggleFps = function() {
    let win = remote.getCurrentWindow();

    try {
        win.webContents.debugger.attach("1.1");
    } catch (e) {
        // console.log(e);
    }
    showFPS = !showFPS;

    win.webContents.debugger.sendCommand("Overlay.setShowFPSCounter", { show: showFPS });
};
`
