### ISSUE TITLE
Add a way to prevent injecting extension `content_scripts` to certain `webContents`

### ISSUE THREAD

**Issue by sentialx** [electron/electron#23616]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

Ref #19447 

### Problem Description
Currently, extensions `content_scripts` are being injected into all `webContents` in a given session. There's no way to exclude certain `webContents` from injecting `content_scripts`.

### Proposed Solution
* Expose an API in `session` or a parameter in `session.loadExtension` which accepts an array of `webContents` excluded from `content_scripts` injection, or
* expose an event in `session` like `before-content-scripts` which passes `webContents` and `e.preventDefault()` would cancel the injection.

### Alternatives Considered
None.

**Comment by MarshallOfSound** [comment]
Exposing APIs for filtering things like certain features of chrome extensions from accessing specific webContents is a non-trivial quantity of work especially given the surface area of all the chrome extension APIs that could in theory touch a specific renderer / webContents.

My suggestion would be to put webContents you don't want to receive the content scripts in a different session.  The purpose of us using the upstream implementation of chrome extensions was to reduce the amount of patching and hackery we had around making this work, adding these events would add a large amount of complexity IMO

**Comment by sentialx** [comment]
@MarshallOfSound I wonder if making a different session just for a BrowserWindow uses more resources...

**Comment by MarshallOfSound** [comment]
It might end using slightly more disk as the cache for sessions is separate, but their shouldn't be any runtime penalty

**Comment by sentialx** [comment]
@MarshallOfSound I think it should be reopened. There's an another problem. What if I wanted to prevent content scripts from injecting to i.e URLs starting with app:// the same as Chrome does? Chrome extensions are not privileged to inject content_scripts to WebUI context. The same situation with my browser, I don't want to allow injecting content scripts to wexond:// pages.

**Comment by sentialx** [comment]
For reference:
Google Chrome with Dark Reader on `wexond://newtab`:
![image](https://user-images.githubusercontent.com/11065386/83352789-71307880-a34e-11ea-9a13-3ed09e12ab14.png)

Wexond with Dark Reader on `wexond://newtab`:
![image](https://user-images.githubusercontent.com/11065386/83352808-91603780-a34e-11ea-971c-166b77af64d6.png)

**Comment by nornagon** [comment]
I think it makes sense to be able to disable loading extensions on certain custom protocols. I'm unsure about doing it on a domain basis or on an individual webcontents basis, but that could plausibly make sense too (how does that interact with the domains that extensions request access to in their manifest files?)

**Comment by RangerMauve** [comment]
I think setting it for certain protocols would be sufficient, TBH. Maybe even a new option inside [registerSchemesAsPrivileged](https://www.electronjs.org/docs/api/protocol#protocolregisterschemesasprivilegedcustomschemes)?

**Comment by RangerMauve** [comment]
Seems like as of electron 9.0.5, the extension's content scripts are only running on `http` and `https` protocols. 🤔

I'm testing it with my [web-palette](https://github.com/RangerMauve/web-palette/blob/master/manifest.json) extension which should be matching `['<all-urls>']`

**Comment by sentialx** [comment]
I'm closing this issue in favor of #26812
