### ISSUE TITLE
No webPreferences and session in e.sender received from an extension background page

### ISSUE THREAD

**Issue by sentialx** [electron/electron#23615]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

Ref #19447

### Issue Details

* **Electron Version:**
  * 9.0.0-beta.24
* **Operating System:**
  * macOS 10.15, Windows 10
* **Last Known Working Electron version:**
  * none

### Expected Behavior
`e.sender` object received from an extension background page should have `webPreferences` and `session` initialized. It looks like `options` in `api::WebContents` constructor don't get initialized properly for an extension background page.

### Actual Behavior
`e.sender` object doesn't have `session` and `e.sender.getWebPreferences()` returns `null`.

### To Reproduce
https://github.com/sentialx/electron-quick-start/tree/extensions/no-session

Just run it and you will see something like this:
![image](https://user-images.githubusercontent.com/11065386/82097607-82994400-9703-11ea-8291-0eb987d8aca0.png)

### Additional Information
This is a real blocker for anyone who would want to provide own `chrome` APIs in background pages initialized from different sessions.

**Comment by nornagon** [comment]
Seems like [this constructor](https://github.com/electron/electron/blob/491caf59c114fb766732e14d01589b757b76ab28/shell/browser/api/electron_api_web_contents.cc#L391-L411) isn't setting the `session_` variable, so maybe that's the issue?
