### ISSUE TITLE
Argument with ? become %3F

### ISSUE THREAD

**Issue by SebCanet** [electron/electron#23627]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.5
* **Operating System:**
  * Windows 7 Pro x64
* **Last Known Working Electron version:**
  * 4.1.1

### Expected Behavior
When creating my mainWindow, it opens a file and take argument from it. Then it must launch an html in Electron app with this argument.

```
var fileSettings = "./Blockly@rduino.json";
var Settings = fs.readFileSync(fileSettings, 'utf8', (err, Settings) => {
                        if (err) {
                            console.log("An error occured reading the file :" + err.message);
                            return
                        }
                        console.log("The file Settings is : " + Settings);
                })
mainWindow.loadURL(path.join(__dirname, '/www/index_electron.html' + Settings));
```

Inside my fileSettings Blockly@rduino.json: "?font=O&lang=en"

### Actual Behavior
Electron app launches but cannot open index_electron.html, in console I can read:
Not allowed to load local resource: file:///F:/Logiciels/BlocklyArduino_AIO/www/index_electron.html%3Ffont=O&lang=en

### Additional Information
So the problem is about the '?' encoding, but I searched for hours on the web without no ideas how to resolve it.

Many thanks.

**Comment by AndrewMuise** [comment]
Looks to me like [`mainWindow.loadURL`](https://www.electronjs.org/docs/api/browser-window#winloadurlurl-options) is properly parsing the argument passed as a url. The behaviour you are experiencing is expected.

Explanation: 
Currently the function is not expecting any options and attempting to encode it as is, resulting in things like `?` turning into `%3f` and ` ` into `%20`. [Reference](https://www.w3schools.com/tags/ref_urlencode.ASP)

The key note from the docs I linked above is
> To ensure that file URLs are properly formatted, it is recommended to use Node's [`url.format`](https://nodejs.org/api/url.html#url_url_format_url_options) method

Meaning that the urlObject you are passing in is not in the correct format, the contents from `./Blockly@rduino.json` should be supplied as an `options` object. From your description, it appears that you are attempting to append search parameters, that might be a good place to look. 

As an aside, I would suggest using `win.loadFile` for loading local files as well.

**Comment by SebCanet** [comment]
Hi,
many thanks for your answer. I need `loadURL `and not `loadFile `because with the same it's online & offline, so I thought it's more compatible.
I think I waited too long to update Electron and the behavior of `loardURL `has changed.

From your link, I tried `.href`,` .toString()` and `url.format(myURL, { fragment: false, unicode: true, auth: false })` without success... I still have a conversion of '?'.
I also tried to use `path.join(__dirname, '/www/index_electron.html', Settings)`, it wokrs but with the conversion. There's something I must not understood correctly.

**Comment by miniak** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by ryanshahine** [comment]
This should work: https://stackoverflow.com/a/59347064
