### ISSUE TITLE
Custom sounds don't work in Electron 8.x

### ISSUE THREAD

**Issue by Suhail** [electron/electron#23620]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

I am using Electron 8.0.3 and I am trying to play a custom sound. Here's what I am doing:

```
  const notif = new Notification({
    title: 'Finished Download',
    body: 'test',
    sound: 'vapp/assets/sounds/mighty_sound.mp3',
  });

  notif.show();
```

It doesn't seem to play that sound but instead a default macOS sound. I've tried:

- Using a absolute path like `'/Users/<name>/Desktop/workspace/proj/vapp/assets/sounds/sound.mp3'`
- Packaging the application so that the sound is bundled
- Playing different file types: .wav, .mp3, .aiff
- Choosing other macOS sounds that might exist in `/System/Library/Sounds`

For whatever reason, it plays the same sound.

I have referenced this [documentation](https://www.electronjs.org/docs/api/notification#playing-sounds)

**Comment by codebytere** [comment]
@Suhail a working example is as follows:

```js
 const notif = new Notification({
    title: 'Finished Download',
    body: 'test',
    sound: 'Submarine',
  });

  notif.show();
```

The above would play the sound at `/System/Library/Sounds/Submarine.aiff` - I recognize though that it's not super intuitive you need to pass it that way though so might be worth adding a better example to docs. For a local file, you should pass:

```js
 const notif = new Notification({
    title: 'Finished Download',
    body: 'test',
    sound: 'my_local_file.aiff', // or wav or caf or whatever
  });

  notif.show();
```

the difference here though (with custom files) is that the name of the sound file must be *in the resources of the application bundle* to play when the notification is delivered. Please feel free to follow up if you experience more issues!

**Comment by Suhail** [comment]
How would you test this to work in development? In other words, not packaged.

**Comment by jiereal** [comment]
development mode sound not working

**Comment by devinbinnie** [comment]
This doesn't appear to work at all, actually. 

I wouldn't be surprised if I'm doing something wrong, but can we get some clearer documentation on how this should actually work? Like:
1) What file formats are supported?
2) Do you need to specify the entire path of the sound file, or just one relative to the `Resources/` folder?
3) Can the file be in a subpath of the resources folder?

I haven't been able to get the app to play anything except the default system sound.
