### ISSUE TITLE
Windows 10 : notification not show if app in full screen mode (f11 button)

### ISSUE THREAD

**Issue by x4080** [electron/electron#23626]
Like title, it seems notification not show if app in full screen mode (f11 button), I just create menu that show notification, it works when app is NOT in full screen mode, but NOT showing notification when app is in full screen mode

**Comment by konstantingross** [comment]
This is by design in Windows: https://thegeekpage.com/enable-notifications-while-in-full-screen-mode-in-windows-10/

**Comment by x4080** [comment]
@konstantingross Thanks man
