### ISSUE TITLE
 when minimize the window ,,,the htmlpage  would not recive the event  send from the webcontents's method 'sendInputEvent'  ,such as mouseMove   

### ISSUE THREAD

**Issue by suxianbaozi** [electron/electron#23632]
Electron Version: 8.3
Operating System: mac osx 10.15.3 

when minimize the window ,,,the htmlpage  would not recive the event  send from the webcontents's method 'sendInputEvent'  ,such as mouseMove

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
