### ISSUE TITLE
Support for aes-128-ccm

### ISSUE THREAD

**Issue by DavidMulder0** [electron/electron#23637]
With the switch from OpenSSL to BoringSSL by Chrome a bunch of ciphers were lost. In the main issue regarding this: https://github.com/electron/electron/issues/16195# it was suggested to open a new issue requesting other ciphers, so hereby was wondering whether there would be any way that Electron could support aes-128-ccm.

Justification for requesting this: Mostly that on IoT devices this is a very popular cipher as it's just more power efficient than alternatives. 

I don't really understand how BoringSSL relates to OpenSSL and I don't really understand if it's possible to even enable aes-128-ccm in BoringSSL, but I figured I would put the request out there regardless.

PS. This is to use node libraries that rely on `crypto` exposing this, so manually using a different solution isn't an option right now :(

**Comment by nornagon** [comment]
There are a couple of variants of aes-128-ccm that boringssl supports (but which we don't currently expose), both of which are bluetooth-related:

```
// EVP_aead_aes_128_ccm_bluetooth is AES-128-CCM with M=4 and L=2 (4-byte tags
// and 13-byte nonces), as decribed in the Bluetooth Core Specification v5.0,
// Volume 6, Part E, Section 1.
OPENSSL_EXPORT const EVP_AEAD *EVP_aead_aes_128_ccm_bluetooth(void);

// EVP_aead_aes_128_ccm_bluetooth_8 is AES-128-CCM with M=8 and L=2 (8-byte tags
// and 13-byte nonces), as used in the Bluetooth Mesh Networking Specification
// v1.0.
OPENSSL_EXPORT const EVP_AEAD *EVP_aead_aes_128_ccm_bluetooth_8(void);
```

However, BoringSSL doesn't seem to have support for EVP ciphers in CCM mode:

```
// The following flags do nothing and are included only to make it easier to
// compile code with BoringSSL.
#define EVP_CIPH_CCM_MODE (-1)
```

so I think some nontrivial work would have to be done in BoringSSL to support this cipher.

You might find some success with a third-party package that offers more direct access to openssl, for instance https://www.npmjs.com/package/openssl.js. If you're feeling adventurous you could try building the methods you need into a NodeJS native module that uses OpenSSL directly.

**Comment by codebytere** [comment]
Closing in agreement with the above - adding support for this would mean patching BoringSSL nontrivially which we generally avoid doing for maintainability purposes. However, should BoringSSL choose to support it we then would as well as soon as such an update rolled in with our dependencies.
