### ISSUE TITLE
Use sqlite3 in main process or render process

### ISSUE THREAD

**Issue by chengfang0911** [electron/electron#23630]
I have a question about using sqlite3, right now im performing CRUD operations on renderer process. What i would like to know is if this would be better than the Main process and using ipcMain on and send to constantly listen and send back data .

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
