### ISSUE TITLE
BrowserView doesn't resize on linux system

### ISSUE THREAD

**Issue by rochismo** [electron/electron#23647]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 8.2.3
  * 
* **Operating System:** Linux Ubuntu 20.04
  * 
* **Last Known Working Electron version:** None that i know of
  * 

### Expected Behavior

I expect that when i resize the BrowserWindow, the BrowserView resizes along with it too.
### Actual Behavior

It does not resize the BrowserView.
### Additional Information
It worked on my Windows 10 computer.
Initially i had the following auto resize options:
```
mainContents.setAutoResize({ width: true, height: true });
```
It didn't work, i have them like this now
```
mainContents.setAutoResize({ width: true, height: true, horizontal: true, vertical: true });
```
It still didn't work

**Comment by rochismo** [comment]
I fixed it by doing the following (sample code)
```javascript
import { BrowserWindow, screen, app} from 'electron';

let mainWindow;

function createWindow() {
    const mainScreen = screen.getPrimaryDisplay();
    mainWindow = new BrowserWindow({
        // Le settings
    });
    mainWindow.on("maximize", () => {
        mainWindow.setSize(mainScreen.workArea.width, mainScreen.workArea.height)
    });
}

app.on("ready", createWindow)
```

**Comment by ChALkeR** [comment]
This seems to be still an issue.

**Comment by FabioLucenaRibas** [comment]
up
