### ISSUE TITLE
Notification click listener not being entered / executing consistently 

### ISSUE THREAD

**Issue by lstrgar** [electron/electron#23654]
### Preflight Checklist

* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version: 8.0.3**
  * 
* **Operating System: macOS 10.15.2**
  * 
* **Last Known Working Electron version: unknown**
  * 

### Expected Behavior

We created a desktop banner notification (using `new Notification(..` to be shown upon the completed download of a file. A click listener is attached to the notification, which uses the `shell.showItemInFolder` method. We expect upon clicking the notification a finder window will open the folder the downloaded file is in, with the file highlighted.

### Actual Behavior

Behavior is inconsistent. Frequently, the feature works as expected. Often it does not. In these cases, we know the click listener is attached, but it is not entered/executed when the notification banner is clicked. So, when the listener does not run, nothing happens. 

### To Reproduce

This is the snippet of our code using the `Notification` and `shell` apis as described above --

```javascript
const notification = new Notification({
    title: 'Finished Download',
    body: `${file_name} has finished downloading.`,
});
notification.on('click', (event) => {
    shell.showItemInFolder(file_path);
});
notification.show();
```

**Comment by MarshallOfSound** [comment]
@lstrgar What you witnessing here is garbage collection mechanics at play.  Nothing is retaining your `notification` object so it is being garbage collected before you click it in some cases.

A common work around here is to maintain a global array of notification objects and retain notifications there until you are done with them.  E.g. `global.notifications.push(notification)`
