### ISSUE TITLE
crashReporter not working on x64 Windows

### ISSUE THREAD

**Issue by panbhatt** [electron/electron#2365]
Crash Reporter is unable to send the notification to the URL mentioned in the start() once the process is being crashes ( via process. crash()).

This includes : https://gist.github.com/zcbenz/9c75ccda4f925faf92ca 
https://github.com/hokein/electron-sample-apps/tree/master/crash-report 

This same thing is working fine on UBUNTU. Can anyone please see if this is really on issue or there is specific problem with the code mentioned in the above URL's. 
Alternatively we are receiving the following error too -> ERROR:crash_reporter_win.cc(75)] Cannot initialize out-of-process

**Comment by kamesh-a** [comment]
@panbhatt we did some mock test to see whether crash reports are generating. we are able to generate them. will upload a git sample so you could test see if it  works.

**Comment by kamesh-a** [comment]
Check this out https://github.com/kamesh-a/electron-samples/tree/master/CrashReporter
sample log in mac, windows8 also we tested
Spec :

node --version : v2.3.3 ( iojs )
npm --version : 2.11.3

node 12.7 has same module version should be equivalent to this version.

Hope this helps !!!

```
crashreporter =============== START
 Headers :  { host: '127.0.0.1:3000',
  'content-type': 'multipart/form-data; boundary=---MultipartBoundary-sezuGs3Jd5YbbtEU0cg4wIbwJy12OkjM---',
  accept: '*/*',
  'transfer-encoding': 'Chunked',
  cookie: 's_pers=%20s_fid%3D27123FF0A10925B1-3B1EDD6A1790CD5C%7C1479058412411%3B%20s_vs%3D1%7C1415901812411%3B%20s_nr%3D1415900012412-New%7C1447436012412%3B',
  'user-agent': 'crashpad_handler (unknown version) CFNetwork/673.3 Darwin/13.4.0 (x86_64) (MacBookPro11%2C3)',
  'accept-language': 'en-us',
  'accept-encoding': 'gzip, deflate',
  connection: 'keep-alive' }
****** Parsing formdata *****
{ fields: 
   { _companyName: 'GitHub, Inc',
     _productName: 'crash-report-demo',
     _version: '0.1.0',
     guid: '690dbc1e-33c3-419c-924a-d5dc81f5bb4d',
     platform: 'darwin',
     process_type: 'renderer',
     prod: 'Electron',
     ver: '0.30.2' },
  files: 
   { upload_file_minidump: 
      { domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        size: 237472,
        path: '/var/folders/wk/qvmk0tkj34d2lgn42rsdy_1m0000gn/T/upload_94a1794ed7cf2114937ebcbe0bbf71ee',
        name: 'a253b92e-d292-4047-afa7-2ed4f912fe1d.dmp',
        type: 'application/octet-stream',
        hash: null,
        lastModifiedDate: Wed Aug 05 2015 15:12:49 GMT+0530 (IST),
        _writeStream: [Object] } } }
 crashreporter =============== END

```

**Comment by panbhatt** [comment]
@kamesh-a Tried to clone your repo and start it with "electron ." . sorry to say it is not working. here is my env details
npm : 2.11.3
node : V0.12.7

Errror while starting the program> 

[87248:0805/113829:ERROR:crash_reporter_win.cc(75)] Cannot initialize out-of-process crash handler
[96688:0805/113830:INFO:renderer_main.cc(200)] Renderer process started
[71596:0805/113830:INFO:renderer_main.cc(200)] Renderer process started

on click on Crash in the HTML window i receive the following. 
![image](https://cloud.githubusercontent.com/assets/1473470/9090107/95c54a36-3b66-11e5-9a90-348e444ff612.png)

I am running windows 8.1. seems like there is some problem in starting CRASH HANDLER whilethe app is start. or may be i am doing something which is wrong here.

**Comment by thughes** [comment]
I'm also having problems with the crash-reporter on Windows. I tried both Windows 10 and Windows 7 with node v0.12.7 + electron v0.32.2 and the simple `crash-reporter-test` gist: https://gist.github.com/zcbenz/9c75ccda4f925faf92ca.

The crash is not reported:
```
 node .\node_modules\electron-prebuilt\cli.js .
[1040:0914/154400:INFO:renderer_main.cc(200)] Renderer process started
```

Here's what it looks like when it does work with the same code and versions of node and electron on Mac:
```
node ./node_modules/electron-prebuilt/cli.js .
[6579:0914/153922:ERROR:file_io.cc(30)] read: expected 40, observed 0
[6583:0914/153922:INFO:renderer_main.cc(200)] Renderer process started
{ _companyName: 'GitHub, Inc',
  _productName: 'crash-reporter-test',
  _version: '',
  guid: '0045a572-db57-45fc-9abd-d4eff6ea4536',
  platform: 'darwin',
  process_type: 'renderer',
  prod: 'Electron',
  ver: '0.32.2' }
[0914/153923:ERROR:http_transport_mac.mm(186)] The network connection was lost. (NSURLErrorDomain -1005)
```

**Comment by thughes** [comment]
Ok, so after looking at the `crash-reporter` code, it looks like this is user error on my part. On Windows the crash reporter [spawns a new process based on the path of the original process](https://github.com/atom/electron/blob/cd1c331112360ded924830bcc07ab54ccaff9207/atom/common/api/lib/crash-reporter.coffee#L38), so you shouldn't run electron with [node `cli.js`](https://github.com/mafintosh/electron-prebuilt/blob/master/cli.js) that comes with `electron-prebuilt`.

When I use the `electron.exe` executable, crash reports work. @panbhatt You might want to see if you were doing the same thing I was.

**Comment by thughes** [comment]
Ok, some more debugging... The [32-bit version](https://github.com/atom/electron/releases/download/v0.32.2/electron-v0.32.2-win32-ia32.zip) works, but not the [64-bit version](https://github.com/atom/electron/releases/download/v0.32.2/electron-v0.32.2-win32-x64.zip).

Also, despite what the [documentation says](https://github.com/atom/electron/blob/ae776b523c94091f10c159fb8ae3c4233aae3388/docs/api/crash-reporter.md#crashreporterstartoptions), you need to start crash-reporter in the renderer process on Windows too.

**Comment by thughes** [comment]
Appears that the crash reporter being broken on 64-bit windows is a known issue: https://github.com/atom/electron/blob/f1787d747afbfcc9e6c416b298d7bf32a366241d/spec/api-crash-reporter-spec.coffee#L19

**Comment by zcbenz** [comment]
Reopening this since is broken again after the upgrade to Chrome 50.
