### ISSUE TITLE
Electron 9.0.0 webSecurity option no longer disables CORS

### ISSUE THREAD

**Issue by wesflynn** [electron/electron#23664]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**  9.0.0
  
* **Operating System:** Windows 10 (1904)
  
* **Last Known Working Electron version:** 8.2.0
  

### Expected Behavior

Setting BrowserWindow webPreferences: { webSecurity: false } should disable the CORS policy

### Actual Behavior

Although I am receiving the electron security warnings for "Disabled webSecurity","allowRunningInsecureContent" and "Insecure Content-Security-Policy" in the console I am still getting COR policy errors on my requests.

**Here is an example:**

Access to XMLHttpRequest at 'http://localhost:8080/users/login' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by yy923683900** [comment]
I have the same problem

**Comment by koczko** [comment]
I also have this problem.
My temporary solution:
app.commandLine.appendSwitch('disable-features', 'OutOfBlinkCors');

**Comment by xland** [comment]
Meet this bug too.

**Comment by mafortier-nexapp** [comment]
Same here !

**Comment by chinaqiao** [comment]
same problem~

**Comment by ishowshao** [comment]
same problem~

**Comment by vitto32** [comment]
same problem in 9.0.3

**Comment by vitto32** [comment]
> I also have this problem.
> My temporary solution:
> app.commandLine.appendSwitch('disable-features', 'OutOfBlinkCors');

I needed both `webSecurity : false` and the command line switch to get rid of CORS errors when using dev-server and trying to access `file://` protocol. 
But now I need another workaround to solve #23757

**Comment by lmx-Hexagram** [comment]
i meet  the same problem

**Comment by lmx-Hexagram** [comment]
> app.commandLine.appendSwitch('disable-features', 'OutOfBlinkCors');

i add this code in main.js(electron) and it works fine

but i still want to know why `Websecurity : false` don't work

**Comment by amwtxgt** [comment]
same problem in 9.0.5

**Comment by YouLiLiao** [comment]
> I also have this problem.
> My temporary solution:
> app.commandLine.appendSwitch('disable-features', 'OutOfBlinkCors');

Thanks, it works to me.

**Comment by YouLiLiao** [comment]
same problem in 9.1.0, `app.commandLine.appendSwitch('disable-features', 'OutOfBlinkCors');` is works to me, but i wish somebody fix it.

**Comment by Bug-Reaper** [comment]
This is also a problem for me.

**Comment by danutzcodrescu** [comment]
The same behavior happens on MacOS. It is not specific to Windows only.

**Comment by khuzema786** [comment]
Same behaviour

**Comment by Quenos** [comment]
Same on mac, for https

**Comment by china-net-meng** [comment]
Same behaviour
mac os

**Comment by china-net-meng** [comment]
> 我也有这个问题。
> 我的临时解决方案：
> app.commandLine.appendSwitch（'disable-features'，'OutOfBlinkCors'）;

thank hou

**Comment by vedaprakashms** [comment]
Is this fixed now?

**Comment by FengfanHu** [comment]
Same problem, not fixed yet. MacOS

**Comment by flotwig** [comment]
> app.commandLine.appendSwitch('disable-features', 'OutOfBlinkCors');

This works for me, but it applies equally to all BrowserWindows. For my application, we need to set `webSecurity` on a per-BrowserWindow basis, but the usual route of using `webPreferences.disableBlinkFeatures` is not working:

```js
// this does not work, even though it is analogous to the app.commandLine.appendSwitch workaround
options.webPreferences.disableBlinkFeatures = 'OutOfBlinkCors'
```

**Comment by flotwig** [comment]
Okay, it's weird, but here's how you can disable `webSecurity` on a per-`BrowserWindow` basis:

1. On app startup, disable the Blink feature globally: `app.commandLine.appendSwitch('disable-features', 'OutOfBlinkCors')`
2. Then, whenever you want to create a `BrowserWindow` WITHOUT `webSecurity` disabled (the default), pass: `options.webPreferences.enableBlinkFeatures = 'OutOfBlinkCors'`

Inverting the options in this manner seems to work. Not sure why the original approach of just using `disableBlinkFeatures` doesn't work.

**Comment by flotwig** [comment]
Would like to note that this bug does not seem to be platform-specific - we are experiencing this on Linux and macOS in addition to Windows.

**Comment by ColorfulHorse** [comment]
same problem, version 10.1.1

**Comment by galaxode** [comment]
The label on this issue shouldn't be limited to `Platform/Windows`.  It's happening for macOS too.

**Comment by daltonmenezes** [comment]
For me only works if I set `webSecurity: false,` and
`app.commandLine.appendSwitch('disable-site-isolation-trials')`

**Comment by Bug-Reaper** [comment]
@daltonmenezes thanks! By any chance, do you have a link to all of the magic incantations that can be set with ` app.commandLine.appendSwitch()`?


I feel like people frequently solve problems with these but I couldn't find a list of them easily. See the [official docs](https://www.electronjs.org/docs/api/command-line-switches#supported-command-line-switches)  which only list a few.

**Comment by daltonmenezes** [comment]
@Bug-Reaper It's chromium flags, so you can find it [here](https://peter.sh/experiments/chromium-command-line-switches/)

**Comment by gormonn** [comment]
It seems to me that this was done on purpose.
Based on this recommendation:
https://www.electronjs.org/docs/tutorial/security#5-do-not-disable-websecurity

This is probably done so that people would not thoughtlessly turn off all policies at once.

PS:
Can you tell me the chrome policy that is responsible for adding the domain name to image paths on the local filesystem?)

Now, I am migrating an old kiosk project (Electron + VanilaJS) to Electron + Vue.js. However, without this policy, the transfer would be too expensive.

**Comment by flotwig** [comment]
> For me only works if I set `webSecurity: false,` and
> `app.commandLine.appendSwitch('disable-site-isolation-trials')`

@daltonmenezes This was reported here: https://github.com/electron/electron/issues/18214 It no longer works for me as of 9.0.0, hence this issue. Does `webSecurity: false` work for you in 9.0.0?

> It seems to me that this was done on purpose.

@gormonn I don't think so, or else it would have been documented by the Electron team. That doc has been around for a while, if they were going to remove the API on purpose they would have said something

**Comment by daltonmenezes** [comment]
@flotwig I've tested on v10.1.1

**Comment by davidchalifoux** [comment]
> It seems to me that this was done on purpose.
> Based on this recommendation:
> https://www.electronjs.org/docs/tutorial/security#5-do-not-disable-websecurity
> 
> This is probably done so that people would not thoughtlessly turn off all policies at once.

Sure, but the problem is still that we can't use it for development purposes. Without it we can't develop using local backend servers.

**Comment by zcbenz** [comment]
The `webSecurity` option controls the web security inside blink, but recently the control of CORS has been moved out of blink and thus the option no longer controls CORS.

I can add a new option to disable CORS, but it would be session-wide, Chromium no longer provides a way to disable CORS per WebContents.

**Comment by Bug-Reaper** [comment]
> @Bug-Reaper It's chromium flags, so you can find it [here](https://peter.sh/experiments/chromium-command-line-switches/)


Thanks for the link @daltonmenezes  :) perhaps [official docs](https://www.electronjs.org/docs/api/command-line-switches#supported-command-line-switches)  should list all chrome flags or link and explain those are available options at least.


> The `webSecurity` option controls the web security inside blink, but recently the control of CORS has been moved out of blink and thus the option no longer controls CORS.
> 
> I'll see if there is another way to disable CORS, but it seems that Chromium no longer provides a way to disable CORS per WebContents so we might end up with adding a new session-side option.


 @zcbenz thank you for the explanation, this makes a lot of sense! Really happy to have some more insight about what's going on here. Also saw you made a PR, thanks a million!

**Comment by SantiiRepair** [comment]
Anyone here alive?

**Comment by Bandonker** [comment]
I hit this exact issue when Electron started enforcing CORS but I needed to access external audio APIs.

I ended up building [desktop-audio-proxy](https://www.npmjs.com/package/desktop-audio-proxy) to handle CORS. The idea is to keep webSecurity enabled and use a local proxy for selective CORS bypass.

  Here's how I set it up:

  ```typescript
  // main.js - Keep security enabled!
  const { startProxyServer } = require('desktop-audio-proxy/server');

  app.whenReady().then(async () => {
    // Start CORS proxy server
    const server = await startProxyServer({
      port: 3002,
      corsOrigins: ['https://yourdomain.com'],  // Control which domains
      enableLogging: process.env.NODE_ENV === 'development'
    });

    const win = new BrowserWindow({
      webPreferences: {
        webSecurity: true,     // Keep this enabled!
        nodeIntegration: false,
        contextIsolation: true
      }
    });
  });

  // renderer.js - CORS-free access
  import { ElectronAudioService } from 'desktop-audio-proxy/browser';

  const audioService = new ElectronAudioService({
    proxyUrl: 'http://localhost:3002'
  });

  // Now external audio APIs work without CORS errors
  const audioUrl = await audioService.getStreamableUrl('https://cors-restricted-api.com/audio.mp3');
  audioElement.src = audioUrl; // Works perfectly

  ```

  This way you get CORS bypass for specific media URLs without the security risks of disabling webSecurity entirely. I've been using this approach in Electron apps for podcast/music streaming.

  Check out the [DAP](https://github.com/bandonker/desktop-audio-proxy): it has examples for different Electron setups.
