### ISSUE TITLE
setTrafficLightPosition fails when both arguments are 0

### ISSUE THREAD

**Issue by PalmerAL** [electron/electron#23668]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 8.3.0
  * 
* **Operating System:** macOS 10.14.6
  * 
* **Last Known Working Electron version:**
  * 

Creating a new window with `titleBarStyle: "hidden"`, and running this:
```
  mainWindow.setTrafficLightPosition({x: 50, y: 50})
  mainWindow.setTrafficLightPosition({x: 0, y: 0})
```

Results in the traffic lights being located at (50, 50), when they should be located at (0, 0). However, this does work:

```
  mainWindow.setTrafficLightPosition({x: 50, y: 50})
  mainWindow.setTrafficLightPosition({x: 0, y: 1})
```

I'm guessing that these lines in RedrawTrafficLights could be the cause of the issue: https://github.com/electron/electron/blob/fea3366bc7d702b3cbff46fd5fa2791d2fb5bc99/shell/browser/native_window_mac.mm#L526-L528

**Comment by MarshallOfSound** [comment]
@PalmerAL `0, 0` is not the default position of the traffic lights.  If you want to restore the position you want `7, 7`

**Comment by PalmerAL** [comment]
I actually was trying to move them all the way to the upper-left corner, and make them more compact than the default. (I do agree that in most cases, you probably wouldn't want to do this though).
