### ISSUE TITLE
Clarify what triggers 'second-instance'

### ISSUE THREAD

**Issue by Slapbox** [electron/electron#23691]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
I just spent the day trying everything under the sun to determine HOW Electron determines an app is an instance of the same app. I've changed every field in the `package.json`, electron-builder config (https://github.com/electron-userland/electron-builder/issues/4995), and in my code - every thing I can conceive of - and yet Electron recognizes it's the same app.

We want to package the app under another name so it can run alongside our main application for development/demo purposes - but this is proving impossible.

I even downloaded the Electron source code and tried to determine how in god's name this works.

### Proposed Solution
A way to run the same application under a different `name`, `productName`, `appId`, or what have you - so that we can deliberately circumvent the instance lock for this single purpose. Currently not one of those works to achieve this.

### Alternatives Considered
Giving up

**Comment by MarshallOfSound** [comment]
@Slapbox The process lock is acquired inside the `userData` directory for your app.  So if your two instances use the same userData directory then they will use the same lock and notify each other of their existence.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
