### ISSUE TITLE
Setting cookies in DefaultSession returns a TypeError

### ISSUE THREAD

**Issue by austtn** [electron/electron#23708]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  8.3.0
* **Operating System:**
  MacOS 10.15.4

### Expected Behavior
Electron to set cookies normally, no issues.

### Actual Behavior
```
TypeError: Cannot read property 'defaultSession' of undefined
```

Throws an error. Running the command inside of a vuex store file.
### To Reproduce
Inside vuex store file:

```
        session.defaultSession.cookies.set({
          token: token,
          expires: 365,
        })
```

### Additional Information
using electron-nuxt library, shouldn't make a difference.

**Comment by MarshallOfSound** [comment]
`session` is `undefined` in your code for whatever reason.  This isn't an issue with electron, it's an issue with your code / usage.  I'd suggest checking in your code with some logging what `session` is set to.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
