### ISSUE TITLE
[bug] electron v9.0.0 in not compatible with @types/node v13+

### ISSUE THREAD

**Issue by saostad** [electron/electron#23701]
I am opening this issue because the [original issue](https://github.com/electron/electron/issues/21612) is closed without providing any solution.
type def that coming with electron is has problem and is not compatible with @types/node v13+ when using electron with typescript.
Error: 
```
7585   class TouchBarSegmentedControl extends NodeJS.EventEmitter {
                                              ~~~~~~

node_modules/electron/electron.d.ts:7598:32 - error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?
```

in order to make electron run with typescript I should use @types/node v^12.x.x but latest version at this point is v14.0.4

**Comment by codebytere** [comment]
This is not a bug - we bundle Node.js v12 and it would be incorrect for us to bundle types that do not match the version we have.

**Comment by saostad** [comment]
so how long we should stuck with that old @types/node dependency? 
I have other packages that are not compatible with this version! 
is it because electron bundles with node LTS version? if so there is no way to have latest version of that package!

**Comment by vladimiry** [comment]
Btw v10 is still based on node v12 but definitions got the update.

https://github.com/electron/electron/blob/e3c2ec9f7c442742ac8e8a6ff260ebfb34a4cb1f/yarn.lock#L43-L44

https://github.com/electron/electron/releases/download/v10.0.0-beta.1/electron.d.ts
