### ISSUE TITLE
electron.asar

### ISSUE THREAD

**Issue by pjebs** [electron/electron#23704]
### Preflight Checklist
* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * Electron 9
* **Operating System:**
  * macOS

There use to be two asar files: `app.asar` and `electron.asar` (amongst resources) when distributing.
The `electron.asar` file has disappeared. When and why did this happen? 

**It's very important to me because I analyse both files to ensure that no-one has tampered with my application.**

It wasn't listed in the breaking changes.

**Comment by codebytere** [comment]
This was done intentionally here: https://github.com/electron/electron/pull/18577. See that PR for more context and details.
