### ISSUE TITLE
webSecurity parameter invalid？

### ISSUE THREAD

**Issue by okuc** [electron/electron#23703]
I have a program based on electron8.2.5, read the local pictures dragged and previewed, everything works fine. But after upgrading to electron9.0.0 today, the picture preview does not show up. It looks as if the parameter ‘webSecurity: false’ does not work.

**Comment by ChALkeR** [comment]
Is this a duplicate of #23664, perhaps?

**Comment by MarshallOfSound** [comment]
Duplicate of #23664
