### ISSUE TITLE
executeJavaScript throw "Error: An object could not be cloned."

### ISSUE THREAD

**Issue by geekduck** [electron/electron#23722]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v9.0.0
* **Operating System:**
  * macOS 10.15.4
* **Last Known Working Electron version:**
  * v8.3.0

### Expected Behavior
executeJavaScript doesn't throw an error.

### Actual Behavior
executeJavaScript  throw an error.
```sh
$ npm start
> electron-quick-start@1.0.0 start /PATH/TO/electron-quick-start
> electron .

(node:63766) UnhandledPromiseRejectionWarning: Error: An object could not be cloned.
    at EventEmitter../lib/renderer/ipc-renderer-internal.ts.exports.ipcRendererInternal.send (electron/js2c/renderer_init.js:2324:20)
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:2286:26)
(node:63766) UnhandledPromiseRejectionWarning: Error: An object could not be cloned.
    at EventEmitter../lib/renderer/ipc-renderer-internal.ts.exports.ipcRendererInternal.send (electron/js2c/renderer_init.js:2324:20)
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:2286:26)
(node:63766) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:63766) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:63766) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:63766) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### To Reproduce

https://github.com/geekduck/electron-bug-report/commit/99bfc2489b5d4435084f20309c9257bb6ae9d26c

index.html
```html
<!DOCTYPE html>
<html>
  <body>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  </body>
</html>
```

main.js
```javascript
  mainWindow.loadFile('index.html')
  mainWindow.webContents.executeJavaScript(`
      $(function() {
          console.log(123);
      });
  `);
```

```sh
$ git clone https://github.com/geekduck/electron-bug-report -b master
$ npm install
$ npm start
```

### Additional Information
workaround

```javascript
  mainWindow.loadFile('index.html')
  mainWindow.webContents.executeJavaScript(`
    (function($) {
      $(function() {
          console.log(123);
      });
    })(window.$);
  `);
```

**Comment by ChALkeR** [comment]
Add `;0` to the end of the original script, otherwise the resulting value is attempted to be cloned and used as a result of executeJavaScript.

That's basically why the work-around above helps – it hides the return value.

**Comment by vladimiry** [comment]
Expected to happen as Structured Clone Algorithm is used for IPC and the returned stuff/jquery-wrapper is not serializable.

**Comment by codebytere** [comment]
Closing as the above two comments are correct!

**Comment by geekduck** [comment]
I understand.
Thank you!

**Comment by fpsantos86** [comment]
I'm having the same error with a component VFileInput and Electron:  
 -> Error in v-on handler: "Error: An object could not be cloned."

**Comment by pimentaro** [comment]
> I'm having the same error with a component VFileInput and Electron:
> -> Error in v-on handler: "Error: An object could not be cloned."

me too

**Comment by appurist** [comment]
For anyone googling this error, this can happen if a formerly synchronous function is suddenly made asynchronous, without the corresponding `await` in the caller. If the result was then sent via IPC, the serializer may not be able to handle this. It isn't a problem with Electron and the IPC, it's effectively the missing `await` before the IPC. I ran into this with the undocumented breaking changes made in `electron-settings` in its 4.0 major update (e.g. `get` and `set` are now async).

**Comment by camhart** [comment]
For anyone else running into this, I had this occur due to using electron-log and logging objects that would cause the error to throw.

**Comment by somebeaver** [comment]
> For anyone googling this error, this can also happen if a formerly synchronous function is suddenly made asynchronous, without the corresponding await in the caller. [...] I suspect the IPC is having trouble serializing a promise...

It's simpler than that. Forgetting an `await` in your code, at any point, means your variable will be equal to the `Promise` itself instead of the results of the promise. Sending that over IPC in [Electron 8 and later](https://www.electronjs.org/docs/breaking-changes#behavior-changed-sending-non-js-objects-over-ipc-now-throws-an-exception) will throw the error.

**Comment by m4heshd** [comment]
Electron is awesome. But this is one of the most awful things about being multi-processed. Hope deno would arrive at a better approach.

**Comment by roryok** [comment]
IPC wasnt involved in my case. I'm running a vue app in electron. I have a computed returning an array of menu items, which are then rendered. Clicking on each one invokes a generic handler which is passed the item as a value 


```
    <button
        v-for="item in menu" :key="name"
        @click="doClick(item)">
    </button>
```
```
    computed: {
        menu() {
            return [
                { name: 'stats', action: () => { alert('hi') } },
                { name: 'about' },
            ];
        }
    },
    methods: {
        doClick(item) {
            if (item.action) {
                item.action();            
            } else {
                // handle generic click
            }
        },
    }
```     

If the item contains an action, I get the error `[Vue warn]: Error in v-on handler: "Error: Uncaught Error: An object could not be cloned."`

if I just did this

```
    <button
        v-for="item in menu" :key="name"
        @click="item.action">
    </button>
```

Didnt find a solution in the end. I tried everything I could think of including destructuring the item before passing in, which I was _sure_ would work. 

```
@click="doClick({ ...item })"
```

but it didnt. In the end I just had to refactor my code

**Comment by deleoeduardo** [comment]
> IPC wasnt involved in my case. I'm running a vue app in electron. I have a computed returning an array of menu items, which are then rendered. Clicking on each one invokes a generic handler which is passed the item as a value
> 
> ```
>     <button
>         v-for="item in menu" :key="name"
>         @click="doClick(item)">
>     </button>
> ```
> 
> ```
>     computed: {
>         menu() {
>             return [
>                 { name: 'stats', action: () => { alert('hi') } },
>                 { name: 'about' },
>             ];
>         }
>     },
>     methods: {
>         doClick(item) {
>             if (item.action) {
>                 item.action();            
>             } else {
>                 // handle generic click
>             }
>         },
>     }
> ```
> 
> If the item contains an action, I get the error `[Vue warn]: Error in v-on handler: "Error: Uncaught Error: An object could not be cloned."`
> 
> if I just did this it would work:
> 
> ```
>     <button
>         v-for="item in menu" :key="name"
>         @click="item.action">
>     </button>
> ```
> 
> But I wanted to be able to handle items with no action too.
> 
> Didnt find a solution in the end. I tried everything I could think of including destructuring the item before passing in, which I was _sure_ would work.
> 
> ```
> @click="doClick({ ...item })"
> ```
> 
> but it didnt. In the end I just had to refactor my code

Try to fetch an array of items with the actions and clone the array items to show them like a menu. When you access to the menu, call a function that finds the original item and execute the action binded to it. You should have some items for showing like a menu and another array of items with the actions. Use the item key to find them in the actions array. 
Hope this work for you, if you'd found a better solution, please post it here!
