### ISSUE TITLE
Enabling nodeIntegration doesn't work

### ISSUE THREAD

**Issue by EnderAdel** [electron/electron#23731]
Files loaded within a window can't use node when I enable *nodeIntegration* in a *BrowserWindow*.

For example if I were to require a module within a JS file that is loaded using a `<script>` tag within the page, it would return an error saying that **require isn't a function**.

**Comment by MarshallOfSound** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by EnderAdel** [comment]
@MarshallOfSound , Here are the project files...
*main.js* (The main file):
```
app.on('ready', () => {
  win = new BrowserWindow({
    width: 1080,
    height: 640,
    show: false,
    icon: iconPath,
    webPreferences: {
        devTools: true,
        nodeIntegration: true,
        nodeIntegrationInWorker: true,
        nodeIntegrationInSubFrames: true,
        preload: path.join(__dirname, 'preload.js'),
        sandbox: true,
        enableRemoteModule: true,
        javascript: true,
        webSecurity: true,
        allowRunningInsecureContent: false,
        images: true,
        textAreasAreResizable: false,
        webgl: true,
        plugins: true,
        experimentalFeatures: false,
        offscreen: false,
        contextIsolation: false,
        nativeWindowOpen: false,
        autoplayPolicy: "no-user-gesture-required",
        spellcheck: false
    },
    resizable: true,
    maximizable: true,
    minimizable: true,
    closable: true,
    fullscreenable: true,
    minHeight: 640,
    minWidth: 1080
  });
  win.setMenu(null);
  win.loadURL(url.format({
    //pathname: path.join(__dirname, 'window.html'),
    pathname: path.join(__dirname, 'window.html'),
    protocol: "file",
    slashes: true
  }));
  win.on('closed', () => {
    win = null;
  });
});
```
*Window.html*:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Name</title>
    <!-- start the engine -->
    <script type="text/javascript" src="./engine/start.js"></script>
    <!-- start the engine -->
  </body>
</html>
```
*engine/start.js*:
```
var NoaEngine = require('noa-engine');
```

**Comment by MarshallOfSound** [comment]
`sandbox: true` and `nodeIntegration` are mutually exclusive.  You can't be both sandboxed **and** have node in the renderer
