### ISSUE TITLE
ERR! Failed at the electron@9.0.0 postinstall script.

### ISSUE THREAD

**Issue by cer-cer** [electron/electron#23739]
This is my system: 
Mac OS: 10.14.5
When i run :
npm install --save-dev electron --verbose
after i set :
npm config set proxy/http-proxy/https-proxy
npm config set strict-ssl false
The failed log as:
....
npm info lifecycle utf8-byte-length@1.0.4~postinstall: utf8-byte-length@1.0.4
npm info lifecycle truncate-utf8-bytes@1.0.2~postinstall: truncate-utf8-bytes@1.0.2
npm info lifecycle sanitize-filename@1.6.3~postinstall: sanitize-filename@1.6.3
npm info lifecycle util-deprecate@1.0.2~postinstall: util-deprecate@1.0.2
npm info lifecycle readable-stream@2.3.7~postinstall: readable-stream@2.3.7
npm info lifecycle concat-stream@1.6.2~postinstall: concat-stream@1.6.2
npm info lifecycle wrappy@1.0.2~postinstall: wrappy@1.0.2
npm info lifecycle once@1.4.0~postinstall: once@1.4.0
npm info lifecycle end-of-stream@1.4.4~postinstall: end-of-stream@1.4.4
npm info lifecycle pump@3.0.0~postinstall: pump@3.0.0
npm info lifecycle get-stream@5.1.0~postinstall: get-stream@5.1.0
npm info lifecycle cacheable-request@6.1.0~postinstall: cacheable-request@6.1.0
npm info lifecycle get-stream@4.1.0~postinstall: get-stream@4.1.0
npm info lifecycle got@9.6.0~postinstall: got@9.6.0
npm info lifecycle yauzl@2.10.0~postinstall: yauzl@2.10.0
npm info lifecycle @electron/get@1.12.2~postinstall: @electron/get@1.12.2
npm info lifecycle @types/node@12.12.42~postinstall: @types/node@12.12.42
npm info lifecycle extract-zip@1.7.0~postinstall: extract-zip@1.7.0
npm info lifecycle electron@9.0.0~postinstall: electron@9.0.0

> electron@9.0.0 postinstall /Users/**/prj/js/helloJs/node_modules/electron
> node install.js

RequestError: unable to get local issuer certificate
    at ClientRequest.<anonymous> (/Users/**prj/js/helloJs/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/Users/**/prj/js/helloJs/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:463:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
npm verb lifecycle electron@9.0.0~postinstall: unsafe-perm in lifecycle true
npm verb lifecycle electron@9.0.0~postinstall: PATH: /Users/**/.nvm/versions/node/v14.2.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/**/prj/js/helloJs/node_modules/electron/node_modules/.bin:/Users/**/prj/js/helloJs/node_modules/.bin:/Users/**/.nvm/versions/node/v14.2.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/**/flutter/flutter_macos_v1.12.13+hotfix.5-stable/bin
npm verb lifecycle electron@9.0.0~postinstall: CWD: /Users/allen.chen/prj/js/helloJs/node_modules/electron
npm info lifecycle electron@9.0.0~postinstall: Failed to exec postinstall script
npm timing action:postinstall Completed in 3718ms
npm verb unlock done using /Users/allen.chen/.npm/_locks/staging-8ac73131855670ff.lock for /Users/allen.chen/prj/js/helloJs/node_modules/.staging
npm timing stage:rollbackFailedOptional Completed in 379ms
npm timing stage:runTopLevelLifecycles Completed in 10574ms
npm WARN hellojs@1.0.0 No repository field.

npm verb stack Error: electron@9.0.0 postinstall: `node install.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/Users/**/.nvm/versions/node/v14.2.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:315:20)
npm verb stack     at ChildProcess.<anonymous> (/Users/**/.nvm/versions/node/v14.2.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:315:20)
npm verb stack     at maybeClose (internal/child_process.js:1051:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
npm verb pkgid electron@9.0.0
npm verb cwd /Users/**/prj/js/helloJs
npm verb Darwin 18.6.0
npm verb argv "/Users/**/.nvm/versions/node/v14.2.0/bin/node" "/Users/**/.nvm/versions/node/v14.2.0/bin/npm" "install" "--save-dev" "electron" "--verbose"
npm verb node v14.2.0
npm verb npm  v6.14.4
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@9.0.0 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@9.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 10845ms

npm ERR! A complete log of this run can be found in:

Please help~

**Comment by linxux** [comment]
Same issue,

```
2673 verbose stack Error: electron@11.0.3 postinstall: `node install.js`
2673 verbose stack Exit status 1
2673 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
2673 verbose stack     at EventEmitter.emit (events.js:315:20)
2673 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
2673 verbose stack     at ChildProcess.emit (events.js:315:20)
2673 verbose stack     at maybeClose (internal/child_process.js:1048:16)
2673 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
2674 verbose pkgid electron@11.0.3
2675 verbose cwd /home/me
2676 verbose Linux 4.15.0-123-generic
2677 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "electron@latest"
2678 verbose node v14.15.1
2679 verbose npm  v6.14.8
2680 error code ELIFECYCLE
2681 error errno 1
2682 error electron@11.0.3 postinstall: `node install.js`
2682 error Exit status 1
2683 error Failed at the electron@11.0.3 postinstall script.
2683 error This is probably not a problem with npm. There is likely additional logging output above.
2684 verbose exit [ 1, true ]

```

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
