### ISSUE TITLE
BrowserWindow show() is slow

### ISSUE THREAD

**Issue by ivanalejandro0** [electron/electron#23730]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v9.0.0
* **Operating System:**
  * Ubuntu 18.04.4 LTS (Kubuntu) x64
* **Last Known Working Electron version:**
  * v5.0.13

### Expected Behavior

Calling `browserWindow.show()` shows the window fast.

### Actual Behavior

Calling `browserWindow.show()` takes about 2 seconds to show the window.

### To Reproduce

I've created a small reproducible example of the problem using a tray icon to show the window.
See: https://github.com/ivanalejandro0/electron-slow-show

```sh
git clone https://github.com/ivanalejandro0/electron-slow-show.git
cd electron-show-slow
yarn
yarn start
```

Use the tray icon to hide/show the window, which takes around 2 seconds to show.

Trying it out with Electron v5.0.13

```sh
sed -i -e 's/9.0.0/5.0.0/' package.json  # replaces electron version on `package.json`
yarn
yarn start
```

Use the tray icon to hide/show the window, which shows immediately.

### Screenshots

Here's a 40s video showing the problem happening on Electron v9.0.0 and not happening on Electron v5.0.13, https://www.youtube.com/watch?v=fVU_zfFH-6w

### Additional Information

It seems that the initial display for the browser window is not slow, but every other time after the window has been hidden is slow.

**Comment by ivanalejandro0** [comment]
I just gave this a try with Electron 10 and I experience the same problem.

```
Node.js 12.16.3
Chromium 85.0.4183.121
Electron 10.1.3
```

**Comment by ivanalejandro0** [comment]
I tried this with Electron 11 and now the window shows as quickly as expected :)

```
Node.js 12.18.3
Chromium 87.0.4280.88
Electron 11.1.0
```

**Comment by nornagon** [comment]
Glad to hear it! I'll close this issue then :)

**Comment by timlindnet** [comment]
This issue reappeared in electron 34
Using electron 33.3.2 works fine, upgrading to 34.0.2 causes a 2 second delay from the show command is run to the window actually appearing. 

Issue present when using:
- node versions 20.18.0 and 22.13.1

On:
- OS: Nobara Linux 41 (KDE Plasma) x86_64
- Kernel: Linux 6.12.11-204.nobara.fc41.x86_64
