### ISSUE TITLE
app crash on macbook air(os: 10.15.1) _platform_bzero$VARIANT$Haswell

### ISSUE THREAD

**Issue by StitchC** [electron/electron#23738]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.1.4
* **Operating System:**
  * macOS 10.15.1
* **Last Known Working Electron version:**
  * 2.0.13

### Expected Behavior
app start normally no crash

### Actual Behavior
app crash when start

### To Reproduce

just launch the app

download: https://cdn.vipthink.cn/app/pc/student/vipthink_mac_2.1.0.dmg

### Additional Information

here is some dump file info

-------------------------------------- 1st -------------------------------------------
18
-[NSApplication
‎/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
19
-[NSApplication run]
‎/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
20
…::Parser::BuildIteratorCloseForCompletion
‎/Applications/VIPThink-test-online.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
21
…::Parser::BuildIteratorCloseForCompletion
‎/Applications/VIPThink-test-online.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
22
…::Parser::BuildIteratorCloseForCompletion
‎/Applications/VIPThink-test-online.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
23
AtomInitializeICUandStartNode
‎/Applications/VIPThink-test-online.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
24
AtomInitializeICUandStartNode
‎/Applications/VIPThink-test-online.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
25
AtomInitializeICUandStartNode
‎/Applications/VIPThink-test-online.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
26
AtomInitializeICUandStartNode
‎/Applications/VIPThink-test-online.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
27
…::Parser::BuildIteratorCloseForCompletion
‎/Applications/VIPThink-test-online.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
28
…::Parser::BuildIteratorCloseForCompletion
‎/Applications/VIPThink-test-online.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
29
…::Parser::BuildIteratorCloseForCompletion
‎/Applications/VIPThink-test-online.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
30
AtomMain
‎/Applications/VIPThink-test-online.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
31
0x1005e7f10
‎/Applications/VIPThink-test-online.app/Contents/MacOS/VIPThink-test-online
32
0x7fff63d0f7fd
‎/usr/lib/system/libdyld.dylib
33
0x7fff63d0f7fd
‎/usr/lib/system/libdyld.dylib

---------------------------------------------------------------------------

--------------------------------------- 2rd -------------------------------------------

56
…::MessagePumpCFRunLoopBase::RunWorkSource
‎/Users/distiller/project/src/out/Default/./../../base/message_loop/message_pump_mac.mm:461
57
__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
‎/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
58
__CFRunLoopDoSource0
‎/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
59
__CFRunLoopDoSources0
‎/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
60
__CFRunLoopRun
‎/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
61
CFRunLoopRunSpecific
‎/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
62
-[NSRunLoop
‎/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
63
…::MessagePumpNSRunLoop::DoRun
‎/Users/distiller/project/src/out/Default/./../../base/message_loop/message_pump_mac.mm:765
64
…::MessagePumpCFRunLoopBase::Run
‎/Users/distiller/project/src/out/Default/./../../base/message_loop/message_pump_mac.mm:185
65
…::RunLoop::Run
‎/Users/distiller/project/src/out/Default/./../../base/run_loop.cc:150
66
content::RendererMain
‎/Users/distiller/project/src/out/Default/./../../content/renderer/renderer_main.cc:233
67
…::ContentMainRunnerImpl::Run
‎/Users/distiller/project/src/out/Default/../../content/app/content_main_runner_impl.cc:871
68
service_manager::Main
‎/Users/distiller/project/src/out/Default/../../services/service_manager/embedder/main.cc:461
69
content::ContentMain
‎/Users/distiller/project/src/out/Default/../../content/app/content_main.cc:19
70
AtomMain
‎/Users/distiller/project/src/out/Default/../../electron/atom/app/atom_library_main.mm:23
71
0x10790f905
‎/Applications/VIPThink.app/Contents/Frameworks/VIPThink Helper.app/Contents/MacOS/VIPThink Helper
72
start
‎/usr/lib/system/libdyld.dylib
REGISTERS
rax
0x0
rdx
0x1123b3000
rcx
0x17800
rbx
0x7fd49bf54bd0
rsi
0x0
rdi
0x1123c1000
rbp
0x7ffee82eb590
rsp
0x7ffee82eb590
r8
0x7ffee82eb55c
r9
0x49bf54c7
r10
0xffffff80
r11
0x0
r12
0x1
r13
0x7ffee82ebb01
r14
0x1123b3000
r15
0x7ffee82eb5e0
eflags
["PF","IF","RF"]

----------------------------------------------------------------------------------

anyone can help me ?

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests. You provided a built dmg app, and in order to triage this we need a reproducible sample with something like [fiddle](https://github.com/electron/fiddle), so that it's clear this is actually a problem with Electron and not your app.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.
