### ISSUE TITLE
Renderer process remote is undefined electron v10.0.0-beta.1

### ISSUE THREAD

**Issue by mashafomasha** [electron/electron#23740]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.0.0-beta.1
* **Operating System:**
  * macOS 10.15.4, windows 10
* **Last Known Working Electron version:**
  * 9.0.0

### Expected Behavior
```js 
// renderer.js
const { remote } = require('electron');
console.log(typeof remote !== 'undefined') // true;
```

### Actual Behavior
```js 
// renderer.js
const { remote } = require('electron');
console.log(typeof remote !== 'undefined') // false;
```

**Comment by miniak** [comment]
https://medium.com/@nornagon/electrons-remote-module-considered-harmful-70d69500f31

**Comment by miniak** [comment]
https://github.com/electron/electron/blob/master/docs/breaking-changes.md#default-changed-enableremotemodule-defaults-to-false
