### ISSUE TITLE
Documentation update required for Rebranding with Downloaded Binaries

### ISSUE THREAD

**Issue by pjebs** [electron/electron#23745]
https://www.electronjs.org/docs/tutorial/application-distribution#macos

The documentation instruct us to rename/modify Info.plist for `Electron Helper` which is fine.

But in Activity Monitor I see `Electron Helper (GPU)` as well.

In the actual `Frameworks` directory I see:
* Electron Helper (GPU)
* Electron Helper (Plugin)
* Electron Helper (Renderer)
* Electron Helper

Do I have to rename all of those?

**Comment by codebytere** [comment]
@pjebs yes - if you look in Activity Monitor for currently running Electron apps you'll see that there as well :)

![Uploading Screen Shot 2020-05-26 at 9.17.51 PM.png…]()
