### ISSUE TITLE
Windows Firewall Warning on Electron 7+ using WebRTC

### ISSUE THREAD

**Issue by jleongDialpad** [electron/electron#23756]
### Preflight Checklist

* [/] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [/] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [/] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  7.2.3 =<
* **Operating System:**
  * Windows 10 
* **Last Known Working Electron version:**
  * 6.1.11

### Expected Behavior
Version of app before or after Electron 7 should not bring up a firewall warning.

When opening up a new WebRTC process after testing out of app with Electron 7 or 8 the corresponding UDP port that opens should not be picked up by Windows Firewall

### Actual Behavior
When a new UDP port opens through WebRTC the Windows Firewall warning would appear. The app can continue to function with or without allowing access.

However the warning will continue to appear after each subsequent call after an app update.

### To Reproduce
This is our companies product so it is hard to create the smallest example to reproduce, but would be happy to be on an email/communication exchange to further explain what is going on or walk through our app code privately.

For other info looking at Slack and Discords apps, since their apps are similar to ours regarding WebRTC. Slack is on Electron 8 while Discord is on Electron 7, for new calls they do not experience this firewall issue.

### Screenshots
![firewall_warning_LI](https://user-images.githubusercontent.com/54045554/82848813-101a2800-9eaa-11ea-9a68-f5a66e7e7c0c.jpg)

### Additional Information
We don't experience <= Electron 6 so we wonder if there were some chromium changes under the hood pertaining to the networking code that doesn't sit well with Windows.

**Comment by jleongDialpad** [comment]
Actually a coworker found a solution to this. As we suspected to get rid of this darn warning all it took was a one line code fix... but my coworker went into a deep rabbit hole into old chromium issues.

References for the issue we found:
https://bugs.chromium.org/p/chromium/issues/detail?id=297208

https://groups.google.com/g/discuss-webrtc/c/6stQXi72BEU/m/7qVwleLiBwAJ

The fix we had were disabling the command line switches for 
SpareRendererForSitePerProcess
WebRtcHideLocalIpsWithMdns

After Electron 7 chromium v 78 turned this flag on which doesn't play nicely with windows defender.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!

**Comment by NoelDavies** [comment]
> Actually a coworker found a solution to this. As we suspected to get rid of this darn warning all it took was a one line code fix... but my coworker went into a deep rabbit hole into old chromium issues.
> 
> References for the issue we found:
> https://bugs.chromium.org/p/chromium/issues/detail?id=297208
> 
> https://groups.google.com/g/discuss-webrtc/c/6stQXi72BEU/m/7qVwleLiBwAJ
> 
> The fix we had were disabling the command line switches for 
> SpareRendererForSitePerProcess
> WebRtcHideLocalIpsWithMdns
> 
> After Electron 7 chromium v 78 turned this flag on which doesn't play nicely with windows defender.

How do you disable command line switches? It doesn't appear to be a thing for me
