### ISSUE TITLE
Rendering crashes (white screen) when FontAwesome is used (raspbian lite)

### ISSUE THREAD

**Issue by cinderblock** [electron/electron#23761]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.2.4
* **Operating System:**
  * Raspbian GNU/Linux 10 (buster)
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
Some sort of error message

### Actual Behavior
Exactly like #4513, the renderer crashes with a white screen when adding `font-awesome`.

Additionally, the `--remote-debugging-port` does not respond to HTTP requests.

### To Reproduce

1. Install raspbian lite onto a Raspberry Pi
2. Run this [setup.sh](https://github.com/electron/electron/files/4679610/setup.txt) script
   - Notably I have only these packages installed:
      ```
      apt-get install -y \
        nodejs yarn \
        screen git \
        build-essential libudev-dev libcurl4-gnutls-dev \
        libpigpio-dev \
        libgtk-3-0 libxss1 libgconf2-dev libnss3 \
        xserver-xorg x11-xserver-utils xinit xinput
      ```
3. Run Electron without window manager in a project that uses `font-awesome`.
   ```
   xinit /full/path/to/node_modules/.bin/electron ...
   ```

### Thoughts

I'm not quite sure how to turn on the debugging symbols that are referenced in #4513 and am otherwise at a loss of how to debug this further.

My suspicion is that I'm just missing a package that might be installed automatically on desktop distros. All the ones referenced in the related issues are installed. (`libharfbuzz-dev`, `libfreetype6`)

I've tried installing a handful of packages just guessing. Notably, I asked what would be installed if I "upgraded" my "lite" raspbian to "desktop" raspbian and installed all of the packages that started with `lib`.

Any suggestions on packages to try installing that might fix this would be greatly appreciated.

I've also been presuming that Electron would not need to get "reinstalled" after installing these `lib`s. Maybe that's my problem?

In any case, thank you very much for taking the time to read this. Any ideas would be greatly appreciated. I'm not sure where else to turn to.

**Comment by cinderblock** [comment]
Well, I've tried installing and running in a desktop environment (Raspbian PIXEL) and still get this problem

**Comment by mduclehcm** [comment]
I guess you are run out of memory. Raspberry pi don't have enough memory to run chromium base project.  When run out of memory, render process crash will cause "white screen" .

**Comment by cinderblock** [comment]
@mduclehcm Interesting idea. However I'm running on a Raspberry Pi 4 with 2GB of ram and 128MB allocated to video memory. (maybe that could be higher?) While running, I can see that I'm only using 200MB for the whole system (according to `htop`). So, I don't think what you're suggesting is true.

If that is true, I still expect some sort of error telling me that electron is out of RAM. This completely unresponsive interface is rather debilitating.

I have noted that all 7 electron sub-processes stay running when the crash happens. I'm not clear on if/how I might get more detailed error outputs from those processes.

----

I've also recently tried adding sounds to my UI. Calling `useBoop()` crashes the renderer (or at least causes the white screen).
```
import useSound from 'use-sound';
import BaBoop from '../assets/BaBoop.mp3';

export function useBoop() {
  const [play] = useSound(BaBoop);
  return play;
}
```

**Comment by mduclehcm** [comment]
@cinderblock 
You can setup a crash reporter to see what error in chromium.
https://www.electronjs.org/docs/api/crash-reporter
I guess this is **'anonymous namespace'::OnNoMemory**.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
