### ISSUE TITLE
new-window event postBody argument is undefined when form target is _blank

### ISSUE THREAD

**Issue by eli0shin** [electron/electron#23780]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
9.0.0
* **Operating System:**
macOS 10.15.4
* **Last Known Working Electron version:**
unknown

### Expected Behavior
When a `webContents` instance emits a `new-window` event as a result of a form with method="post" and target="_blank" being submitted, the event handled should receive the `postBody` data as the 8th argument. This behavior is documented here: https://github.com/electron/electron/blob/master/docs/api/web-contents.md#event-new-window

### Actual Behavior
`postBody` is always `undefined`.

### To Reproduce
* load https://gist.github.com/eli0shin/9edacf8a4bff2d794fdec8ab49fcb7a3 in electron fiddle.
* start the app
* click submit
* a new window is created with a post request and the formData is displayed in the page
* the `postBody` value in the console is `undefined`

The fiddle includes a basic form and an express server to handle the form submit.

**Comment by FrankWangZY** [comment]
same problem in electron 9.3.4, 10+ . is there any workaround?

**Comment by panther7** [comment]
I need postBody on webview `new-window`. Actually is not change to catch post request.

**Comment by lzdyes** [comment]
webview "new-window" need postBody

**Comment by Carlween** [comment]
Seems BrowserWindow "new-window" can now receive the postBody data in electron 13+.
We need the postBody on webview too.

**Comment by lzdyes** [comment]
in webview, you can try this:

`      const webContents = remote.webContents.fromId(webview.getWebContentsId())

      webContents.on('new-window', (event, url, frameName, disposition, options, additionalFeatures, referrer, postBody) => {
        event.preventDefault()

        const loadOptions: LoadURLOptions = { httpReferrer: referrer }
        if (postBody) {
          const { data, contentType, boundary } = postBody
          loadOptions.postData = data
          loadOptions.extraHeaders = `Content-Type: ${contentType}; boundary=${boundary}`
        }

        webContents.loadURL(url, loadOptions)
      })`

**Comment by nornagon** [comment]
This is fixed in ^13.0.0.
