### ISSUE TITLE
Excessive memory consumption when leaving the system on for a few hours on Windows

### ISSUE THREAD

**Issue by maple-leaf** [electron/electron#23783]
### Preflight Checklist

* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.2.3
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * N/A

We create an Electron app that works great on most machines but consumes lots of memory on a PC, it's above 7G+.
![image](https://user-images.githubusercontent.com/3980995/82982945-d704c380-a021-11ea-911d-3e2cdf65ae31.png)
We record the process's memory information on this PC, and it shows that the RSS is consistently growing and seems will never end. Please see the below chart and attached file.
![image](https://user-images.githubusercontent.com/3980995/82984274-6ad78f00-a024-11ea-86f5-dbb29fdbe387.png)
[excessive-memory-consumption-memory-records.txt](https://github.com/electron/electron/files/4686790/excessive-memory-consumption-memory-records.txt)

Then we create a demo app to check if this is our problem, but it seems it is an electron problem. The below chart shows the memory consumption of the demo app.
![image](https://user-images.githubusercontent.com/3980995/82984901-a030ac80-a025-11ea-8a2f-60d0c20532d0.png)
The demo app consumes unnecessary memory very quickly. Because the PC runs a heavy building task at a middle time, the memory drops down very quickly but later it goes up again. And about this, memory consumption of our real app will drop down quickly too when the user opens some heavy apps or do some heavy tasks.
And one more thing about the demo app, it creates some background processes unexpectedly on the problem PC, but not on others.
![image](https://user-images.githubusercontent.com/3980995/82985501-b4c17480-a026-11ea-86c1-004f29de0dd2.png)
it is normal on others:
![image](https://user-images.githubusercontent.com/3980995/82985478-a83d1c00-a026-11ea-8643-78e95527f8db.png)
The demo app logs memory usage across time and content tracing information. Here are the two logs.
[electron-memory-issue-content-tracing.txt](https://github.com/electron/electron/files/4686865/electron-memory-issue-content-tracing.txt)
[electron-memory-issue-process-infos.txt](https://github.com/electron/electron/files/4686866/electron-memory-issue-process-infos.txt)
And the demo app repo: https://github.com/maple-leaf/electron-bug-repo/tree/memory-issue-demo

### Expected Behavior

The memory should not increase crazy on the real app, normally it use about 1 Gb. For the demo app, it should take about 40 Mb. And the background processes should not exist.
### Actual Behavior

The memory goes crazy on the real app. 
### To Reproduce

Currently, this only happens on a PC. We can't reproduce this on most of the others.

If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone https://github.com/maple-leaf/electron-bug-repo.git -b memory-issue-demo
$ npm i
$ npm run publish
```

### Additional Information
Device specifications of the problem PC
![image](https://user-images.githubusercontent.com/3980995/82986731-f2270180-a028-11ea-9e6c-3a4122623f70.png)

**Comment by xudafeng** [comment]
I encountered the same problem when dev a software. I will pay attention to this issue for a long time.

**Comment by nornagon** [comment]
The version of Electron you're using is [no longer supported](https://www.electronjs.org/docs/tutorial/support#currently-supported-versions).

If you're experiencing this on a supported version of Electron, please comment with the version you're seeing the issue on and we can re-open.
