### ISSUE TITLE
Electron 9.0.0: Mac App Store rejection - ITMS-90332: Invalid Symbolic Link

### ISSUE THREAD

**Issue by thomasdao** [electron/electron#23828]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 9.0.0
* **Operating System:** MacOS
* **Last Known Working Electron version:** Electron 8

Release to Mac App Store failed with below error:

ITMS-90332: Invalid Symbolic Link - The symbolic link 'com.my.app.pkg/Payload/MyApp.app/Contents/Frameworks/Electron Framework.framework/Helpers' resolves to an invalid location. Make sure that the symbolic link does not resolve to itself, and that the location exists and is contained within the app bundle.

I've checked `electron-v9.0.0-mas-x64.zip` file from `~/Library/Caches/electron`, open the package content of `Electron.app` and I found it contains an invalid alias at `Electron.app/Contents/Frameworks/Electron Framework.framework/Helpers`. I am not sure if this file is added on purpose - it is not in electron 8 release.

### Expected Behavior

App should be able to release to App Store

### Actual Behavior
Apple rejected the build

**Comment by wnajar** [comment]
Hi! I'm a product manager at Facebook working on Messenger for MacOS and Windows, which uses Electron. Apple rejected our latest submission to the Mac App Store with 9.0.0 and specifically mentioned this issue as the problem. tl;dr this also repros for us and I can imagine blocks any app distributing via the Mac App Store.

Made a comment on https://github.com/electron/electron/pull/23831 so hopefully we can get this resolved ASAP. We've been stung by a few surprise rejections due to Electron changes in the last 6 months and are invested in reducing that risk. Issues like this make us less eager to upgrade to the latest version.

**Comment by nornagon** [comment]
@wnajar we'd love to have an automated process that could flag issues like this ahead of time, but unfortunately we don't have the available engineers to build it, and further, it's not clear that Apple would allow such automation to exist.

Perhaps Facebook could help out with this? We'd love to get this happening as part of our release process so we can catch these issues early!

**Comment by sagar-winjit** [comment]
**I am able to resolve the issue: ITMS-90332: Invalid Symbolic Link using following steps:**

1. Follow electron steps: https://www.electronjs.org/docs/tutorial/mac-app-store-submission-guide
2. npm install
3. npm start
4. Add embedded.provisionprofile & entitlements.mas.plist in build folder
5. Made required changes in package.json file
6. Enter this command to generate .app “npx electron-builder --mac”
7. If .pkg doesn’t work (issue: ITMS-90332: Invalid Symbolic Link) then do following additional steps
8. Goto package content and execute following command: “unlink /yourpath/Electron\ Framework.framework/Helpers”
9. Add bash file (ref: https://www.electronjs.org/docs/tutorial/mac-app-store-submission-guide) “scriptFile.sh”
10. Execute command: “chmod 755 scriptFile.sh”
11. Execute command: “./scriptFile.sh”
12. Now try with new generated .pkg file, hope that will work
