### ISSUE TITLE
setAboutPanelOptions doesn't support ico iconPath on Windows

### ISSUE THREAD

**Issue by mahnunchik** [electron/electron#23833]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  *  v8.3.0
* **Operating System:** 
  *  Windows 10.0.18363 
* **Last Known Working Electron version:**
  *  -

### Expected Behavior

`app.setAboutPanelOptions` shows `.ico` icon.

### Actual Behavior

`app.setAboutPanelOptions` shows default icon instead of provided.

### To Reproduce

```js
app.setAboutPanelOptions({
  iconPath: 'icon.ico',
  // iconPath: 'icon.png', - works as expected
});
```
https://www.electronjs.org/docs/api/app#appsetaboutpaneloptionsoptions

### Additional Information

Both icons ico/png are included in the build.

**Comment by mahnunchik** [comment]
It seems the method `PopulateImageSkiaRepsFromPath` doesn't support `.ico`: https://github.com/electron/electron/blob/e74daf2d195f4380aa1ad683fd25322db60b7d86/shell/common/skia_util.cc#L138-L152

**Comment by codebytere** [comment]
Skia currently doesn't support `.ico` nor is it likely to - you should specify your iconPath for an icon with a `.jpg` or `.png` extension. Should something change on the Chromium end to make this possible, i'll gladly reopen this.

**Comment by mahnunchik** [comment]
@codebytere Thank you for the clarification. I think documentation may be updated. PR attached.
