### ISSUE TITLE
Sequelize module not working in rendrer process in windows

### ISSUE THREAD

**Issue by indikaur** [electron/electron#23839]
I'm using Sequelize with MariaDB in my desktop app windows 7. However the renderer process cannot access sequelize or any models defined in the model files.

This problem does not occur in Linux. I only have to create the sequelize object in the main process and authenticate there only once. After that this it is available for any page in the renderer process.

When I do the debugging, I found that the main page (index.html) loaded into the renderer has to re-authentcate the sequelize connection. But the problem here is when I browse to another page through the main page links, sequelize connection not available again. Also I can't re-authenticate since renderer already authenticated once.

I'm not sure this is an issue or a bug to post here. But I don't see any answer for this kind of problem elsewhere. I'm putting my original code here.
**main process:**
```

const {app, BrowserWindow} = require('electron')
const Sequelize = require('sequelize')

const connectStr = 'xxxxxx' //hidden for security purpose
const sequelize = new Sequelize(connectStr)

function createWindow() {
    sequelize.authenticate().then(promise => {
          console.log('Connection has been established successfully.')
          let mainWindow = new BrowserWindow({
              webPreferences: {
                  nodeIntegration: true,
                  zoomFactor: 1.0
              }
          })
      
          mainWindow.loadFile('index.html')
          // mainWindow.webContents.openDevTools()
    }).catch(err => {
          console.error('Unable to connect to the database:', err)
    })
}

app.allowRendererProcessReuse = true
app.whenReady().then(createWindow)
```

**renderer process (works with linux, but not windows)**
```

const {remote} = require('electron')
const mainProcess = remote.require('./main')
const Bank = require('../models').Bank

$(document).ready(() => {
    Bank.findAll({}).then(banks => { //code })
})
```

Here is the debug code I put in js file in index.html.
```
const Sequelize = require('sequelize')
const Bank = require('../models').Bank

const connectStr = 'xxxxxx' //hidden for security purpose
const sequelize = new Sequelize(connectStr)

//following will work here only once. Once visited another page this also fails.
sequelize.authenticate().then(promise => {
    console.log('Connection has been established successfully.')
    Bank.create({
        name: 'CBL'
    }).then(done => {
        console.log('OK')
    })
})
```

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 7 days if the above is not addressed.
