### ISSUE TITLE
Electron crashes with BSOD or freeze on video settings

### ISSUE THREAD

**Issue by anthoniussk** [electron/electron#23834]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * all versions
* **Operating System:**
  * Windows 7 Home Premium
* **Last Known Working Electron version:**
  * none

### Expected Behavior
App works without crashes

### Actual Behavior
Apps like Skype, MS Teams, Zoom crashes on opening video settings in nonstandard environment with more video devices like video capture cards. App crashes to BSOD or it must be killed by task manager, but there is still 2 non-killable processes that locks video device. Restart is required to "unload" this processes.

### To Reproduce
Insert and install an USB video capture card, like this one (EasyCap):

https://www.ebay.com/itm/Card-of-Capture-Video-Easycap-Grabber-USB-Audio-for-TV-PC-Containing-VHS-a-HD/263969471849

or this one:

https://www.ebay.com/itm/HDMI-To-USB2-0-Playback-Game-Record-Live-Streaming-Adapter-Video-Capture-Card/254590978899

Then open Skype, MS Teams or Zoom, open Settings and go to Video settings. App freezes or BSOD appears.

It could by good if electron select only web cameras or nothing or fix this bug with nonstandard video devices handling.

**Comment by codebytere** [comment]
These issues should be reported to the apps themselves - Zoom isn't even an Electron app. If it can be demonstrated that this is in fact an Electron issue, we'll potentially look back into this.
