### ISSUE TITLE
Older electron (v2.xx to v4.xx) support for flash

### ISSUE THREAD

**Issue by plirof2** [electron/electron#23832]
First of all I'm interested old electron versions electron-v2.0.18 and electron-v4.2.11 (because that chromium core versions are more flash-friendly -especially v2.0.xx)
I have a website (exists both on web and on localhost) with flash educational games. All are stripped of external calls and are trusted & secured (so I don't care about sandbox or other security issues).
I have a debian 64bit system with _libpepflashplayer.so_ installed on **_all_** the correct paths (chromium,  google chrome,opera, vivaldi etc all can run flash).

What I want is to run this website via electron instead of an old version of chromium. I would prefer libpepflashplayer.so to be inside the folder of electron. I tried running electron like this :

```
electron --ppapi-flash-path=/opt/electron2/libpepflashplayer.so --ppapi-flash-version=32.0.0.101 --always-authorize-plugins http://mysite/index.html
but it says "couldn't load plugin"
```

I can't modify the website I must only play with command line options (like above) . Any suggestions?

**Comment by codebytere** [comment]
Unfortunately no - we no longer support those versions per our [support policy](https://www.electronjs.org/docs/tutorial/support).
