### ISSUE TITLE
How to disable keyboard shortcuts ‘Alt + F4’ in Electron

### ISSUE THREAD

**Issue by e404r** [electron/electron#23862]
Hi

**not working**
const { app, BrowserWindow, globalShortcut, path, url} = require('electron')

app.on('ready', () => {
  const ret = globalShortcut.register('alt+f4', function () {
    win.show()
  })
})
==========
also global shortcut not working
 
Please help

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
