### ISSUE TITLE
Electron cannot see imported modules.

### ISSUE THREAD

**Issue by ruslanDeveloperGit** [electron/electron#23873]
Hello, I'm building my project with electron and typescript. 

I have the **main.html** file, and **index.js** file _connected_ to my HTML file. 

_I want to import some module in my index.js_, my IDE can see this export and suggests me autocomplete. But when I start the app, I see this error: 
![image](https://user-images.githubusercontent.com/61386270/83392212-6680ec80-a3fd-11ea-82a2-856700d0a13b.png)

And I get this in app sources. As you see, there's no **exports** folder:

![image](https://user-images.githubusercontent.com/61386270/83423625-e9bd3500-a433-11ea-8d12-7ad96d9dd235.png)

For some reason _electron cannot see my  exports._

Here's tree of my project. It contains three main folders:

**src** - folder where .ts files is contained. 
**public** - folder where .html/.css files is contained.
**dist** - folder where compiler should compile .ts files and copy public folder. Also **electron** _starts_ _here_.

![image](https://user-images.githubusercontent.com/61386270/83392427-beb7ee80-a3fd-11ea-9b5f-e1b2c76c4d74.png)

In src I have **publicScripts** folder, this folder contains scripts for public(I mean, only for frontend).

I have this line of code in the header of my main.html(this path goes from dist/public directory, not from the root):

`<script defer src="../../publicScripts/index.js"></script>`

In index.ts(which will be compiled to index.js) I have this line:
` import {  generateScramble } from './exports/scrambleGenerator'; `

So in my scrambleGenerator I have 1 exported function: 
`export function generateScramble(scrambleLen: number): string { // some code here }`

It is my **tsconfig.json**(I used .txt because I can't attach .json here).
This is pretty default(I have made it with tsc --init), except that I changed **outDir** value to **"./dist"** and **rootDir** value to **"./src"**

[tsconfig.txt](https://github.com/electron/electron/files/4710371/tsconfig.txt)

Here's my **package.json**. It has 2 scripts. **1st** for compiling my .ts files and copying public folder to dist. **2nd** runs first script and starts electron app in dist folder. Also it hase 2 devDependencies(electron and typescript):

[package.txt](https://github.com/electron/electron/files/4710463/package.txt)

So this is my problem. I tried to connect  _scrambleGenerator_ to my html, but I have the same problem - my index.js cannot see this module and throws an error again.

**Comment by ruslanDeveloperGit** [comment]
I forgot to add this photo. This is sourses in app, as you can see, there's **no 'exports'** folder for some reason: 
![image](https://user-images.githubusercontent.com/61386270/83400095-f6796300-a40a-11ea-9471-28eb1f16f6c2.png)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions or app-specific configuration issues since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
