### ISSUE TITLE
app.getPath("documents") in a MAS build directs to the wrong dir

### ISSUE THREAD

**Issue by vanejung** [electron/electron#23877]
In a dev build, `getPath("documents")` is correctly directing to `~/Documents`
However, my (approved) MAS build is instead directing to `~/Library/Containers/<bundle_id>/Data/Documents/`

In my code, this is how I'm using `getPath("documents")`.
`const documentsPath = window.require("electron").remote.app.getPath("documents")`

Not sure if this is a bug, or it's me doing it wrong... 😢

Thanks in advance and stay safe!

**Comment by MarshallOfSound** [comment]
Actually that's the correct directory. by default MAS applications do not have unlimited file system access so your app doesn't have access to the entire `Documents` folder the user sees.  macOS creates fake little virtual folders for a number of things inside your sandbox container.  You should write documents files to the path that API returns 👍
