### ISSUE TITLE
[Win] libuv loop stops working in a native addon after page reload.

### ISSUE THREAD

**Issue by jphw** [electron/electron#23910]
### Issue Details

* **Electron Version:** 9.0.0 (beta versions of 9.0.0 too)
* **Operating System:** Windows 10 1903
* **Last Known Working Electron version:** 7.2.4

### Repro steps
1. **require** a native module in a Renderer process (on a page)
2. call libuv function **uv_queue_work** 5 times
3. get **uv_after_work_cb** invoked 5 times
4. reload the page 
5. call libuv function **uv_queue_work** 5 times once more

### Expected Behavior
6. get **uv_after_work_cb** invoked 5 times

### Actual Behavior
6. get **uv_after_work_cb** invoked 1 or 2 times, remaining ones never get invoked by libuv

### To Reproduce
I prepared a sample project with minimal code that demonstrates the problem:
>>> https://github.com/jphw/libuv_problems

Please read the README.MD and check src/libuv_problems_module.cpp sources.

### Additional Information
**app.allowRendererProcessReuse = false;**  works as a workaround for this issue

**Comment by aabuhijleh** [comment]
I think this is causing the same issue I'm having #24173. Regression in Node.js APIs in preload script after page reload.

**Comment by nornagon** [comment]
Related: #25314

**Comment by ckerr** [comment]
This is still an issue in master & in the back branches even after the uv threading issue that was resolved in #25332. This appears to be an unrelated issue.

**Comment by Jiahui-Yan** [comment]
This problem also exists in electron 12.0.0, but not in 9.4.4.
