### ISSUE TITLE
Flash support 

### ISSUE THREAD

**Issue by plirof2** [electron/electron#23946]
This is actually the same issue as this : https://github.com/electron/electron/issues/23832
but it is for the latest electron v9 .

Since many good educational software is made in flash I want to keep using it. I am doing this now with older browsers but the electron solution might be a better one.
My problem is that I can't make flash work.

I tried this :
```
electron --ppapi-flash-path=/opt/electron9/libpepflashplayer.so --ppapi-flash-version=32.0.0.101 --always-authorize-plugins http://mysite/index.html
but it says "couldn't load plugin"
```

I can't modify the website I must only play with command line options (like above) . 
Any suggestions ? 
The "main.js" solution suggested in other issues can't be used by me.

Thanks in advance

**Comment by codebytere** [comment]
Given that this isn't currently on our roadmap, is being phased out of many major browsers, and in the interest of our issue tracker more closely reflecting our workstreams, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be potentially open to accepting a PR!

**Comment by plirof2** [comment]
Yes, thanks.
I don't wont to fix or add support for anything.
I am just trying to find out how to use flash (even in the older version of electron).
If anyone can help me in that direction I would be grateful.

Thanks

**Comment by miniak** [comment]
https://www.adobe.com/products/flashplayer/end-of-life.html
