### ISSUE TITLE
Accessibility prompts for Downloads/Document/Desktop folders in MacOS Catalina

### ISSUE THREAD

**Issue by ajayaa** [electron/electron#23968]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  7.1.0
* **Operating System:**
  *  MacOS 10.15.2
* **Last Known Working Electron version:**
  * 

### Expected Behavior

We don't ever try to read/access these folders. Hence these accessibility prompts are unexpected.
### Actual Behavior

Even if I revoke these permissions after giving them once, the app works just fine.
### Screenshots

![image](https://user-images.githubusercontent.com/1562748/83768614-a285ad00-a69c-11ea-9092-5f3256bfcf64.png)
![image](https://user-images.githubusercontent.com/1562748/83769354-5be48280-a69d-11ea-9d79-5fe086e803b9.png)

**Comment by codebytere** [comment]
@ajayaa it's not clear what code was run here, as you have provided no repro steps. By default, it should not ask you for access to all three folders, and when i run a simple default app with [`fiddle`](https://github.com/electron/fiddle) it does not ask me for any access of this nature.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
