### ISSUE TITLE
[Mac] BrowserWindow's setPosition does not position window under dock since 9.0.0

### ISSUE THREAD

**Issue by yunyu** [electron/electron#23969]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
9.0.2
* **Operating System:**
MacOS Catalina 10.15.5
* **Last Known Working Electron version:**
8.3.1

### Expected Behavior
This issue affects Mac users with multimonitor setups and a bottom-positioned dock. When you try to spawn a enableLargerThanScreen window with `setAlwaysOnTop(true, "popup-menu")`, the window should be positioned underneath the dock. This is the behavior in Electron 8.3.1 (the window bounds are designated by the red border):

![](https://i.imgur.com/XRDnOsV.jpg)

### Actual Behavior
This is the behavior in Electron 9.0.2:

![](https://i.imgur.com/xyqyM2Z.jpg)

Observe that the window is positioned above the dock.

### To Reproduce
Here is an Electron fiddle gist: https://gist.github.com/yunyu/e33519abe6ea74e851b36f1ab5bc00c1

### Additional Information

This issues requires BOTH a multimonitor setup and a bottom-positioned dock to occur. If the dock is left or right-positioned, OR the user is on a single monitor, it will not replicate.

**Comment by rahulgs12** [comment]
I can repro this on a single monitor.

**Comment by MarshallOfSound** [comment]
Will be fixed by https://github.com/electron/electron/pull/23976
