### ISSUE TITLE
rendering bug on Windows 10 Build 1909

### ISSUE THREAD

**Issue by bassbenberlin** [electron/electron#23983]
Hi.
My OS is Windows 10 Build 1909.
I use Visual Studio code.
That's where the problem is most severe. 
But sometimes the errors occur in Figma or Rocket Chat.

When a view does not have the focus, recursive disturbances build up around the objects to be rendered.

If I move the mouse over the interference, it disappears for a while.

Work is still possible, but the disturbances are annoying.

Here I have a screenshot of the problem.
[https://atelier-grinda.de/assets/ElectronRenderBug.png](https://atelier-grinda.de/assets/ElectronRenderBug.png)

I added the 2 black squares to make company names unrecognizable. I do not mean them.

Thank you

**Comment by shaderbytes** [comment]
i have rendering issues as well , this is very very bad , windows 10 , 64bit , dont know what version, but im using the latest electron and npm etc.

This is a development the renders perfectly normal in chrome outside of electron. While in electron vector items like my fonts and icons which are , svg are rendering as mangled bitmaps. on small fonts you cant even read the text.

![electron_rendering_bug](https://user-images.githubusercontent.com/2153214/83953894-94729080-a844-11ea-8348-f2a2acc9d2e4.jpg)

![electron_rendering_bug2](https://user-images.githubusercontent.com/2153214/83953897-9b999e80-a844-11ea-86f8-db48c5daae20.jpg)

**Comment by bassbenberlin** [comment]
![Unbenannt](https://user-images.githubusercontent.com/66467960/84414855-51346b00-ac12-11ea-8c69-bc367503b0e5.png)
another example. there is all day long something like this

**Comment by bassbenberlin** [comment]
hello?

please help me,

whatsapp desktop now makes trouble too.

thank you

**Comment by woutervmertens** [comment]
hey, have the same issue.
Do you have a NVIDIA gpu?

**Comment by bassbenberlin** [comment]
yes, i have a NVIDIA GeForce MX250

**Comment by bassbenberlin** [comment]
I have changed the rendering to the Intel UHD Graphics 620 gpu. 
after a reboot everything looks great. let's see what the day brings.
i will contact you this afternoon (in 5 - 6 hours).

**Comment by bassbenberlin** [comment]
https://github.com/electron/electron/issues/24424

**Comment by woutervmertens** [comment]
I removed the drivers for my gpu with device manager (tick the delete drivers box) and then reinstalled the latest one. This seemed to work, I'll test some more today

**Comment by bassbenberlin** [comment]
I also removed my NVIDIA driver, and then reinstalled the latest one.
Since then I haven't had any problems.

The driver was actually up to date but the reinstallation helped anyway.
