### ISSUE TITLE
Bad window resize performance in electron 9.0.0

### ISSUE THREAD

**Issue by crazytoucan** [electron/electron#23980]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.0
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron version:**
  * 8.x

### Expected Behavior

Resizing a window is smooth

### Actual Behavior

Resizing a window is unexpectedly laggy, even when the window is completely empty and there are no other active listeners

### To Reproduce

The following simple program exhibits the poor behavior:

```sh
$ electron index.js
```

```js
// index.js
const BrowserWindow = require("electron").BrowserWindow;
const app = require("electron").app;

app.on("ready", () => {
  new BrowserWindow();
})
```

### Screenshots

![slow-resize](https://user-images.githubusercontent.com/3346671/83829285-5f750b00-a697-11ea-849f-a4abe1dfc609.gif)

### Additional Information

Notes:

- To the best of my knowledge, this worked well in previous versions of Electron
- Interestingly, at super tiny sizes, like making the window 80px x 60px, resizing works just fine. The resizing performance degrades _significantly_ starting at about 600 x 400.

Thanks much for such an awesome technology. Let me know if there's anything I can do to help diagnose potential confounding issues here!

**Comment by nornagon** [comment]
I can repro. Looks like it was introduced with the first beta of v9, so it's likely related to a Chromium roll.

**Comment by johnsusek** [comment]
Also seeing this on MacOS 10.15.3, iMac Pro

**Comment by zcbenz** [comment]
Closed with https://github.com/electron/electron/pull/24642.
