### ISSUE TITLE
Unable to follow the steps to create an electron app through website or electron-forge

### ISSUE THREAD

**Issue by abhinavluv** [electron/electron#23991]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
* **Operating System:**
  * 
* **Last Known Working Electron version:**
  * 

### Additional Information

While installing electron using npm using npm install electron --save, I get the following error:

$ npm install electron --save

> core-js@3.6.5 postinstall C:\Users\abhinsha\OneDrive - AMDOCS\Backup Folders\Desktop\Study\Electron\myApp\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> electron@9.0.2 postinstall C:\Users\abhinsha\OneDrive - AMDOCS\Backup Folders\Desktop\Study\Electron\myApp\node_modules\electron
> node install.js

RequestError: getaddrinfo ENOTFOUND github.com
    at ClientRequest.<anonymous> (C:\Users\abhinsha\OneDrive - AMDOCS\Backup Folders\Desktop\Study\Electron\myApp\node_modules\got\source\request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:418:26)
    at ClientRequest.emit (events.js:323:22)
    at ClientRequest.origin.emit (C:\Users\abhinsha\OneDrive - AMDOCS\Backup Folders\Desktop\Study\Electron\myApp\node_modules\@szmarczak\http-timer\source\index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@9.0.2 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@9.0.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\abhinsha\AppData\Roaming\npm-cache\_logs\2020-06-05T18_18_56_859Z-debug.log

On trying to clone the repository or use npx create-electron-app, I get the same error. This has been since quite a few days where I am unable to create a new electron app.

Even after creating an empty node package and installing electron, it doesn't work.

**Comment by codebytere** [comment]
I haven't seen anything like this but it's definitely not an issue Electron. At the top of the error stack, you can see:
```
C:\Users\abhinsha\OneDrive - AMDOCS\Backup Folders\Desktop\Study\Electron\myApp\node_modules\got\source\request-as-event-emitter.js:178
```

which is an error originating from an external package (`got`) we do not have control over.

**Comment by abhinavluv** [comment]
Unable to initialise Electron app in any way. Doesn't it work on Windows 10?

**Comment by dishubagga** [comment]
anybody got fix for this?

**Comment by abhinavluv** [comment]
I had to upgrade the node version after which I was able to do it... Not sure if this was actually the issue back then.
