### ISSUE TITLE
__dirname is not defined

### ISSUE THREAD

**Issue by ricardoracki** [electron/electron#24005]
When I import electron into my App vue and try to access electron.ipcRenderer.send() it generates:
![image](https://user-images.githubusercontent.com/36777788/83979651-4d3cdc00-a8e6-11ea-95fc-1e10cb79f54c.png)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions or application-specific problems since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by airplayx** [comment]
I also encountered the same error, but I don’t know how to do it.

**Comment by Yurematias** [comment]
I having the same problem. Somone solved?

**Comment by airplayx** [comment]
please forgive if my English is poor.
There is a temporary solution here:
1.Set `createWindow->win->webPreferences->nodeIntegration: true` in `background.js`
2. Use `const {ipcRenderer} = window.require('electron')` in the rendering process.

**Comment by FlavioAssis** [comment]
Solved! Thaanks

**Comment by Yurematias** [comment]
I fixed, thanks!!

**Comment by SantosbrDev** [comment]
> I fixed, thanks!!

hello, i am trying to fix but i cant. Can you take a print screen?
this is my project test, i am running electron v7.  i made the changes in issue, but no result.
![image](https://user-images.githubusercontent.com/64033791/85178524-13a89100-b255-11ea-84db-af9aa31400fe.png) 
![image](https://user-images.githubusercontent.com/64033791/85178541-1f945300-b255-11ea-89b2-3b32a6062ef7.png)

thanks!!



> please forgive if my English is poor.
> There is a temporary solution here:
> 1.Set `createWindow->win->webPreferences->nodeIntegration: true` in `background.js`
> 2. Use `const {ipcRenderer} = window.require('electron')` in the rendering process.

**Comment by Yurematias** [comment]
@SantosbrDev In my project, the __dirname problem came from inside a library that I used in the Vue part. I resolved by placing the ```nodeIntegration: true``` in the background.js and registering the library in the file ```vue.config.js``` at the root of my project.
![HELP GITHUB](https://user-images.githubusercontent.com/43214648/85181150-9b919980-b25b-11ea-9f20-c85670fc5c32.png)

**Comment by codebytere** [comment]
`__dirname` is a Node.js global: https://nodejs.org/docs/latest/api/globals.html#globals_dirname.

You cannot use it without access to the Node.js APIs.

**Comment by SantosbrDev** [comment]
thanks 😄 !! @codebytere @yuredev

**Comment by zkx349113864** [comment]
@airplayx thank you very much , i resolve my question by your answer

**Comment by Nisthar** [comment]
@codebytere so why do they disable `nodeIntegration` by default? also can i enable it in production?

**Comment by wsmPanda** [comment]
and why `window.require('electron')`,its about loader,i guess

**Comment by soletan** [comment]
> 
> 
> `__dirname` is a Node.js global: https://nodejs.org/docs/latest/api/globals.html#globals_dirname.
> 
> You cannot use it without access to the Node.js APIs.

So don't do it. ;)

This exception appears [following instruction](https://www.electronjs.org/docs/tutorial/application-architecture#using-electron-apis) by doing this in renderer process:

    const { ipcRenderer } = require( "electron" );

If I go there:

![grafik](https://user-images.githubusercontent.com/48088/94368314-ba69bc80-00e3-11eb-808d-e746d0eb9623.png)

I find this:

![grafik](https://user-images.githubusercontent.com/48088/94368319-c3f32480-00e3-11eb-91d3-812d3637244d.png)

If I try to find the package this code belongs to, the only match is in **node_modules/electron/index.js**. If this doesn't work without enabling node integration in renderer process, does it make any sense to consider security implications on enabling nodeIntegration at all? I thought disabling it from the beginning is a good start to improve my application's security. Maybe I've misread your documentation.

For the sake of testing it, I've enabled nodeIntegration, this time there is a different error in same piece of code:

![grafik](https://user-images.githubusercontent.com/48088/94368503-9fe41300-00e4-11eb-8fd0-acd0e9c37279.png)

So, without knowing Electron's architecture something seems to be pretty broken, maybe due to webpack used, which is: there might be an issue with another package breaking webpack in the way it handles that renderer-side import of "electron".

My setup is roughly electron + vue (using CLI) + vuetify (using the electron-builder) + trying to inject CKEditor (following manual on Vue-integration from source to have Markdown plugin in editor).

**Comment by soletan** [comment]
Ok, I see my case is pretty identical to the one of airplayx and others ... https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/guide.html#preload-files ... missed that either.

**Comment by burzum** [comment]
I have the same issue as @soletan

background.js (excerpt):

```js
    webPreferences: {
      // Use pluginOptions.nodeIntegration, leave this alone
      // See nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#node-integration for more info
      // nodeIntegration: process.env.ELECTRON_NODE_INTEGRATION
      // https://github.com/electron/electron/issues/24005#issuecomment-643705734
      nodeIntegration: true
    }
```

![image](https://user-images.githubusercontent.com/162789/94600294-fcd0fc00-0291-11eb-9651-dced89aae9b4.png)

Code from MainMenu.vue:

```js
import {app} from 'electron'

export default {
  name: 'MainMenu',
  methods: {
    close: function () {
      app.exit(0);
    }
  }
}
```

My packages.js:

```json
{
  "name": "lohnsteuerrechner",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "electron:build": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve",
    "postinstall": "electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps"
  },
  "main": "background.js",
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.30",
    "@fortawesome/free-solid-svg-icons": "^5.14.0",
    "@fortawesome/vue-fontawesome": "^3.0.0-1",
    "autoprefixer": "^10.0.0",
    "axios": "^0.20.0",
    "bootstrap": "5.0.0-alpha1",
    "bootstrap-icons": "^1.0.0",
    "chartist": "^0.11.4",
    "core-js": "^3.6.5",
    "css-loader": "^4.3.0",
    "currency.js": "^2.0.3",
    "install": "^0.13.0",
    "node-sass": "^4.14.1",
    "postcss-loader": "^4.0.2",
    "sass-loader": "^10.0.2",
    "style-loader": "^1.2.1",
    "url-loader": "^4.1.0",
    "v-calendar": "^1.0.8",
    "vee-validate": "^3.4.0",
    "vue": "^3.0.0-0",
    "vue-chartist": "^2.3.1",
    "vue-currency-input": "^1.22.3",
    "vue-router": "^3.4.4"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0-0",
    "babel-eslint": "^10.1.0",
    "cypress": "^5.2.0",
    "electron": "^9.0.0",
    "electron-devtools-installer": "^3.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0-0",
    "vue-cli-plugin-electron-builder": "~2.0.0-rc.4"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/vue3-essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}
```` 

Any ideas whats going on? :(

**Comment by burzum** [comment]
So is there any proper solution to make this work without node integration? 😞

**Comment by soletan** [comment]
> So is there any proper solution to make this work without node integration?

It is, just follow the link provided by airplayx above and read the box carefully. There is a preload which is applied to prior disabling node integration in BrowserWindow. I've missed that part before, but now it's working.

**Comment by zhch-hong** [comment]
> > `__dirname` is a Node.js global: https://nodejs.org/docs/latest/api/globals.html#globals_dirname.
> > You cannot use it without access to the Node.js APIs.
> 
> So don't do it. ;)
> 
> This exception appears [following instruction](https://www.electronjs.org/docs/tutorial/application-architecture#using-electron-apis) by doing this in renderer process:
> 
> ```
> const { ipcRenderer } = require( "electron" );
> ```
> 
> If I go there:
> 
> ![grafik](https://user-images.githubusercontent.com/48088/94368314-ba69bc80-00e3-11eb-808d-e746d0eb9623.png)
> 
> I find this:
> 
> ![grafik](https://user-images.githubusercontent.com/48088/94368319-c3f32480-00e3-11eb-91d3-812d3637244d.png)
> 
> If I try to find the package this code belongs to, the only match is in **node_modules/electron/index.js**. If this doesn't work without enabling node integration in renderer process, does it make any sense to consider security implications on enabling nodeIntegration at all? I thought disabling it from the beginning is a good start to improve my application's security. Maybe I've misread your documentation.
> 
> For the sake of testing it, I've enabled nodeIntegration, this time there is a different error in same piece of code:
> 
> ![grafik](https://user-images.githubusercontent.com/48088/94368503-9fe41300-00e4-11eb-8fd0-acd0e9c37279.png)
> 
> So, without knowing Electron's architecture something seems to be pretty broken, maybe due to webpack used, which is: there might be an issue with another package breaking webpack in the way it handles that renderer-side import of "electron".
> 
> My setup is roughly electron + vue (using CLI) + vuetify (using the electron-builder) + trying to inject CKEditor (following manual on Vue-integration from source to have Markdown plugin in editor).

I ran into the same problem

**Comment by rafalimaz** [comment]
You can apply the solution described on this post How to import ipcRenderer in vue.js ? __dirname is not defined

In this way you can call window.ipcRenderer.send(channel, args...) from vue files.

Just make sure you configure preload.js on vue.config.js:

// vue.config.js - project root
module.exports = {
  pluginOptions: {
    electronBuilder: {
       preload: 'src/preload.js'  //make sure you have this line added
    }
  }
}

**Comment by rafalimaz** [comment]
You can apply the solution described on this post How to import ipcRenderer in vue.js ? __dirname is not defined

In this way you can call window.ipcRenderer.send(channel, args...) from vue files.

Just make sure you configure preload.js on vue.config.js

**Comment by TheAutomaTom** [comment]
It's distressing that the workaround listed as the closing argument seems to include a lot of deprecated code practices, and it's definitely not explained in a manner that one would expect from professional documentation.  In 2 years a lot has changed, and there are no work arounds published for Electron, Vite, Vue 3 to operate.  I don't believe you should be promoting this as compatible with Vue 3 (or perhaps Vite, idk where the failure really is).

**Comment by juanmait** [comment]
I solved the problem with a preload script:

```ts
import { contextBridge } from 'electron'
import { electronAPI } from '@electron-toolkit/preload'

// Custom APIs for renderer
const api = {}

// Use `contextBridge` APIs to expose Electron APIs to
// renderer only if context isolation is enabled, otherwise
// just add to the DOM global.
if (process.contextIsolated) {
  try {
    contextBridge.exposeInMainWorld('electron', electronAPI)
    contextBridge.exposeInMainWorld('api', api)
  } catch (error) {
    console.error(error)
  }
} else {
  // @ts-ignore (define in dts)
  window.electron = electronAPI
  // @ts-ignore (define in dts)
  window.api = api
}

```

Then in the render side you can access `ipcRender` from `window.electron.ipcRender`.

I asume that this would not work out of the box for third party libraries from npm that use the legacy require `require('electron)`. You can read more about the hows and whys of preload scripts here: https://www.electronjs.org/docs/latest/tutorial/tutorial-preload

**Comment by AriJing** [comment]
> please forgive if my English is poor. There is a temporary solution here: 1.Set `createWindow->win->webPreferences->nodeIntegration: true` in `background.js` 2. Use `const {ipcRenderer} = window.require('electron')` in the rendering process.
> 
> there have more infos : https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/security.html#node-integration

Uncaught TypeError: window.require is not a function
