### ISSUE TITLE
BrowserWindow with level `screen-saver` stopped going over the tray bar

### ISSUE THREAD

**Issue by momakes** [electron/electron#24000]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
 v9.0.2
* **Operating System:**
 macOS 10.15
* **Last Known Working Electron version:**
Worked fine on 8.3.0 (I think #22828 has caused it)

### Expected Behavior
Windows with level higher than screen-saver should be able to go over the menubar.

### Actual Behavior
It doesn't go above 22px of the tray bar.

### To Reproduce
Try moving a BrowserWindow over the menubar with levels above the tray level.

**Comment by Xapphire13** [comment]
Hitting the same problem.

This bug will break screen capture apps such as [Kap](https://github.com/wulkano/Kap)

**Comment by codebytere** [comment]
This will be closed in https://github.com/electron/electron/pull/23976
