### ISSUE TITLE
Extensions don't work with file:// protocol since 9.0.0

### ISSUE THREAD

**Issue by ChALkeR** [electron/electron#24011]
Extracted from #23662, https://github.com/electron/electron/issues/23662#issuecomment-632344005, per https://github.com/electron/electron/issues/23662#issuecomment-637077040 (cc @nornagon).

Extensions get loaded for `http://` and `https://` protocols, but don't work for `file://` protocol, which is commonly used.

This also affects devtools extensions.

Appears to be an undocumented regression from 8.x.

Chrome by default behaves the same, but it has an `Allow access to file URLs` switch (the `fileAccess` flag) on extension page at `chrome://extensions/`, which enables the extension to run on `file://` urls (which can be verified on `Content scripts` tab).
Any hint how to do that in Electron?
React-devtools works on `file://` protocol in Chrome with that flag enabled, but does not work in Electron since 9.0.0, as there are no ways to toggle that setting.

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.0, 9.0.2
* **Operating System:**
  * `Linux xps 5.6.14-arch1-1 #1 SMP PREEMPT Wed, 20 May 2020 20:43:19 +0000 x86_64 GNU/Linux`
* **Last Known Working Electron version:**
  * 8.3.1

### Expected Behavior

Installed extensions should load for `file://` protocol automatically, or/and there should be an opt-in/out-out for that (like opt-in in Chrome).

Extension content script present in `Content scripts` tab.

### Actual Behavior

Extensions are not loaded if the for pages requested over `file://` protocol.

No extension content script present in `Content scripts` tab.

### To Reproduce

`index.js`:
```js
const { app, session, BrowserWindow } = require('electron');
const path = require('path');

(async () => {
  await app.whenReady()
  await session.defaultSession.loadExtension(path.join(__dirname, 'extensions/test'))
  const bw = new BrowserWindow({webPreferences: {sandbox: true}})
  //await bw.loadURL('about:blank')
  //await bw.loadURL('https://example.org/')
  await bw.loadURL(`file://${path.resolve('simple.html')}`)
  bw.show()
  bw.openDevTools()
})()
```

Put anything in `simple.html`.

Example extension (but you can use any other, e.g. https://github.com/electron/electron/tree/master/spec-main/fixtures/extensions/chrome-api or `react-devtools`)

`extensions/test/main.js`
```js
console.log('extension loaded')
```

`extensions/test/manifest.json`
```json
{
  "name": "test",
  "version": "1.0",
  "content_scripts": [
    {
      "matches": ["<all_urls>"],
      "js": ["main.js"],
      "run_at": "document_start"
    }
  ],
  "permissions": [ "file:///*", "http://*/*", "https://*/*" ],
  "manifest_version": 2
}
```

### Screenshots
`https://`:
![Screenshot_20200608_142638](https://user-images.githubusercontent.com/291301/84025366-18875e00-a994-11ea-8762-259236998f65.png)

`file://`:
![Screenshot_20200608_142102](https://user-images.githubusercontent.com/291301/84024876-52a43000-a993-11ea-9ac5-e44ef60ad616.png)

### Additional Information

This breaks devtools extension and is a part (if not the main reason) behind #23662.

**Comment by danielweck** [comment]
Yep, "store not found" with Redux DevTools.
https://github.com/electron/electron/issues/24638

**Comment by RangerMauve** [comment]
I'd like to take a shot at this. Is there somewhere in the code where there's a decision being made on whether a particular content script should get injected or not?

**Comment by nornagon** [comment]
@RangerMauve I'd probably start by searching for `kFileScheme` in the extensions code: https://source.chromium.org/search?q=kFileScheme%20f:extensions

From [here](https://source.chromium.org/chromium/chromium/src/+/master:extensions/common/manifest_handlers/permissions_parser.cc;l=150;drc=a8faae057698a771cc47079c80f8f25303a71496) it looks like maybe if the extension requests access to `file://` urls it might be allowed? There's also a constant called `Extension::ALLOW_FILE_ACCESS` that looks like it might be relevant.

Hopefully that's enough to get you started!

**Comment by RangerMauve** [comment]
Sweet. Also, do you think this would be at all related to the issue I saw with extensions not loading for custom protocol handlers? https://github.com/electron/electron/issues/23616#issuecomment-648492463

**Comment by nornagon** [comment]
Seems plausible!

**Comment by ChALkeR** [comment]
[ExtensionPrefs::SetAllowFileAccess](https://source.chromium.org/chromium/chromium/src/+/master:extensions/browser/extension_prefs.h;l=517?q=ExtensionPrefs) is likely related.

In Electron: https://github.com/electron/electron/search?q=ExtensionPrefs

**Comment by ChALkeR** [comment]
`extension->creation_flags() & Extension::ALLOW_FILE_ACCESS` seems to be false.

Flipping 4 (Extension::ALLOW_FILE_ACCESS) on creation_flags makes this work.

**Comment by ChALkeR** [comment]
https://github.com/electron/electron/pull/25151 seems to be a fix, but I'm unsure if this _should_ be the path forward.
Refs: https://github.com/electron/electron/issues/24011#issuecomment-674316115

**Comment by nornagon** [comment]
> @nornagon do you think that should be enabled unconditionally or via an opt-in when an extension is added?

IMO opt-in makes sense.

**Comment by nornagon** [comment]
Some more context: Chrome allows file access to all unpacked extensions by default ([ref](https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/extensions/unpacked_installer.cc;l=224-239;drc=e478821787f8edf4e32bb1263e75c929d99776ac)). There's a preference that controls file access for specific extensions. Since we only ever load unpacked extensions currently, I think it makes sense for us to expose this to the app.

**Comment by bedney** [comment]
Incredibly interested in this fix! Thank you @ChALkeR for working on it (and, of course, @nornagon for all of your work on the Chrome Extension API).

**Comment by petef19** [comment]
+1 thank you for working on this fix !

**Comment by bedney** [comment]
@ChALkeR - any chance this fix might be finished before the next 10.X. series release? It's a blocker for us.

Thank you!

**Comment by raksooo** [comment]
Great that this is being worked on! What's the current status?

By looking at the historical duration between major releases I get the impression that Electron 11 isn't to far away, which will result in Electron 8, the last version with this working, unsupported. This is a blocker for me and it would be nice to not have to use an unsupported version after Electron 11 has been released.

**Comment by samuelmaddock** [comment]
There's currently more work to be done regarding persisting the option in the event that an extension is reloaded.

Also, just going to mention that posting a bounty to [BountySource](https://www.bountysource.com/teams/atom) is another option for folks eager to see this get fixed.

**Comment by rwwagner90** [comment]
I would be happy to sponsor this work, if someone thinks they can fix it.

**Comment by 0501814314** [comment]
mosa.alhonadi2013@gmail.com

**Comment by bedney** [comment]
I can also back this bug with some cash. Can someone speak to the level of effort required here? Given that Electron apps are really meant to run from the file system, this is a pretty severe limitation.

**Comment by m4heshd** [comment]
Looking forward to a fix. Currently writing an unfair amount of scripts to compensate for this issue. Glad It's being worked on.

**Comment by rlaranjeira** [comment]
Thank you @nornagon!!

**Comment by btzsoft** [comment]
in 2021 the same issue. it's strange, does someone use react, mobx extensions in electron 11, 12 ?

**Comment by m4heshd** [comment]
@btzsoft works fine with Vue devtools.

**Comment by rwwagner90** [comment]
Works fine with Ember Inspector as well.
