### ISSUE TITLE
Clipboard `writeBuffer`, `readBuffer`, and `has` methods don't work in Electron 8.0.0

### ISSUE THREAD

**Issue by helen-dikareva** [electron/electron#24029]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.0 and upper
* **Operating System:**
  * Windows, Mac
* **Last Known Working Electron version:**
  * 7.1.14

### Expected Behavior

I expect that [clipboard's methods](https://www.electronjs.org/docs/api/clipboard#clipboardreadbufferformat-experimental) `writeBuffer` and `readBuffer` works properly according to the documentation.

### Actual Behavior

They don't work. I try to use them, but it has no effect.

### To Reproduce
The problem can e easily reproduced with [electron-quick-start] (https://github.com/electron/electron-quick-start). Just call e.g.
```js
clipboard.writeBuffer('opa123', Buffer.from('text-test'));
console.log(clipboard.has('opa123'))
console.log(clipboard.readBuffer('opa123').toString());
```
in 7.1.14 - there will be `true` and `text-test` in the console
in 8.0.0  - there will be `false` and an empty string in cosole.

**Comment by codebytere** [comment]
Just ran that exact code and experienced no issues:

<img width="229" alt="Screen Shot 2020-06-09 at 9 41 41 AM" src="https://user-images.githubusercontent.com/2036040/84175879-71f39980-aa35-11ea-8724-4c9b49b0bcfa.png">

**Comment by helen-dikareva** [comment]
I've tried to reproduce this behavior in Electron fiddle and still got the same result
![image](https://user-images.githubusercontent.com/12034551/84634740-f002e500-aefa-11ea-9bd5-0a7e06161c63.png)
What do I do wrong or there is a real problem?

**Comment by codebytere** [comment]
@helen-dikareva i think this is likely a system issue. This is the code i ran to produce the correct result: https://gist.github.com/016b069b752255234f60643128fe5bbf.

I'm closing this for now as non-reproducible but am happy to open should more info come to light.

**Comment by helen-dikareva** [comment]
I found out some more details:
- this works as you describe on macOS but don't work on Windows (I tried only Windows before)
- the exact version with this problem in `v8.0.0-beta.3`
