### ISSUE TITLE
inAppPurchase receipt file "_MASReceipt/receipt" not found

### ISSUE THREAD

**Issue by wgqzlj** [electron/electron#24025]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.3
* **Operating System:**
  * macOS Catalina 10.15.5 Beta 
* **Last Known Working Electron version:**
  * 

### Expected Behavior

Read the receipt file data after the iAP finished.

### Actual Behavior

When I the inAppPurchase.getReceiptURL(), it returns the receipt file path. but the file "_MASReceipt/receipt" is not found on the disk.

### To Reproduce
1.  `"electron:dev": "concurrently \"cross-env BROWSER=none yarn start\" \"wait-on http://localhost:3000 && cross-env NODE_ENV=development electron . \"",`
2.  call the inAppPurchase.getReceiptURL() in the transactions-updated / purchased event listener.
3. `var receiptRaw = fs.readFileSync(receiptURL)`

### Screenshots
<img width="420" alt="iap" src="https://user-images.githubusercontent.com/511052/84132541-9755c700-aa78-11ea-9d0b-89baad9b125d.png">

**Comment by wgqzlj** [comment]
Maybe the Electron.app not enable the iAP capability in XCode. @sofianguy

**Comment by phongtt12** [comment]
@wgqzlj do you have any solution for this issue?

**Comment by luokunman** [comment]
> @wgqzlj do you have any solution for this issue?

Did you solve the problem?

**Comment by aryan1107** [comment]
did anyone solve?
