### ISSUE TITLE
App Crash while generating from electron-builder

### ISSUE THREAD

**Issue by akbarbashakm** [electron/electron#24036]
**Issue Details**

**Version:**
"electron": "6.0.12",
"electron-builder": "^21.2.0"
 os: macOS Catalina 10.15.5

**Expected Behaviour**
User should be prompted to grant microphone access.

**Actual Behaviour**
Application crashes

**Replication Procedure**

1. git clone 'https://github.com/akbarbashakm/electron-issue.git'
2. npm run start (it may crash if you are run in vsCode so better run in terminal it will work)
3. npm run package
4. open dist -> mac -> sample (Application crash)

Ya mostly lot of people reported the same is in a while... Please resolve asap else can you guyz suggest me how to resolve it...

While running app through vsCode (using npm run start) also it crash that's not a matter i am ok to run the app in terminal. 
But i am facing the same issue while while generating the build using electron-builder...

**Comment by codebytere** [comment]
Please open this issue on electron-builder - this team is not responsible for its maintenance.

**Comment by akbarbashakm** [comment]
@codebytere why did u closed without checking the sample... this is happen because of when my code has systemPreferences.askForMediaAccess in my app....
