### ISSUE TITLE
Tray menu creates taskbar item

### ISSUE THREAD

**Issue by zarubond** [electron/electron#24049]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
9.0.2
* **Operating System:**
  Windows 10
* **Last Known Working Electron version:**
9.0.1
### Expected Behavior
Opening tray icon should not create taskbar item

### Actual Behavior
Empty taskbar item is created when tray icon menu is opened

### To Reproduce
Create tray menu and open it

### Screenshots

![tray](https://user-images.githubusercontent.com/6961047/84270140-85346100-ab2a-11ea-9b75-45a40f4c2470.png)

**Comment by MarshallOfSound** [comment]
For now if we don't have an immediate solution I think a revert makes sense.  Let's go back to the state we were in which is arguably better than having this thing appear

**Comment by ckerr** [comment]
I'm going to keep look at this. I don't see an immediate solution but we need an answer that doesn't have visual artifacts *and* doesn't break tray menus for a11y users.
