### ISSUE TITLE
blocked a frame with origin cannot, use disable-site-isolation-trials to resolve

### ISSUE THREAD

**Issue by Nawbc** [electron/electron#24044]
### Issue Details
Version:
"electron": "9.0.3",
"os": window10

webSecurity is closed
`app.commandLine.appendSwitch('disable-site-isolation-trials') ` is not useful in electron9.0.3
and i disabled all the options about isolation and cross-origin in chrome://flags,  sitll invalid

#prefetch-main-resource-network-isolation-key
#strict-origin-isolation
#site-isolation-trial-opt-out
#enable-portals-cross-origin
#prefetch-main-resource-network-isolation-key

**Comment by inu1255** [comment]
maybe a bug in electron@9.0.3? I resolve it by 
`app.commandLine.appendSwitch('--disable-web-security')`

**Comment by sewerganger** [comment]
@inu1255 可能 我用了你的方法 但是没效果 ，  我在chromium 78 的electron 版本里可以用app.commandLine.appendSwitch('disable-site-isolation-trials')
