### ISSUE TITLE
Create flag to help with IPC serialization deprecation

### ISSUE THREAD

**Issue by MRayermannMSFT** [electron/electron#24086]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Electron recently introduced a new IPC serialization technique. It is faster, which is great! 🎉 It also does not serialize things which were previously serializable, which is...troublesome? In Electron 8, that problem is addressed by outputting a message to stdout which warns that in Electron 9, the old technique will fully go away and attempts to send anything not serializable will result in an exception.

My problem with the Electron 8 behavior is that it can be hard to track down what is causing the warning. The app I work on uses IPC a lot, and it's taking a lot of effort to find out what IPC calls are causing the warnings. In fact, my current technique for finding the bad calls is to upgrade to 9, and use the exceptions that are now being thrown to help me find things. I would rather develop against 8 though since that's what I'm shipping right now, and have better tools/techniques with that version to help me find our bad IPC calls.

### Proposed Solution
What I would like to see is a way to turn on the exception in Electron 8. Maybe something like:

```js
app.structuredCloneSerializationOnly = true;
```

Turning on this flag would result in an exception being thrown if something is not serializable with structured clone. That way, I can turn on this flag today in my debug/testing builds, to help me track down the things which in the future will definitively cause exceptions.

### Alternatives Considered

Alternatively, I think it'd be great if Electron didn't get rid of falling back to the old serialization algorithm. I can understand why y'all would choose to get rid of it though, so I'm not going to really argue for this. Just please understand that from the view of an app writer the current behavior of electron 9 is...scary. For my product, we've been sending things across IPC in the way we have since 2015ish, and now all of a sudden doing so might cause very visible exceptions/errors. But again, I'm not here to try and change y'all's mind about that. I just want to create something that helps us app writers adjust to the change.

### Additional Information
N/A

**Comment by nornagon** [comment]
Seems reasonable. Would an environment variable also serve your purpose here?

**Comment by MRayermannMSFT** [comment]
Yes. Though it would be a big help if it didn't need to be set prior to launching the app. We do many of our test passes on clean VMs, and it would be annoying to have to remember to keep setting the env var whenever we make the VM. Or in other words, whatever turns on the exceptions is ideally something we can do programmatically. If that isn't possible, then I guess we'll have to live with that.

**Comment by MarshallOfSound** [comment]
We apparently missed doing this completely and Electron 8 is very much a version of the past 😆

**Comment by MRayermannMSFT** [comment]
🤷🤣
