### ISSUE TITLE
When printing, set silent: true, you need to provide print settings. How to provide paper size?

### ISSUE THREAD

**Issue by chenlin19970520** [electron/electron#24095]
When printing, set silent: true, you need to provide print settings. How to provide paper size?
{
          silent: true,
          printBackground: false,
          deviceName: "TX 80 Thermal",
}
Because the paper size printed at this time is wrong.

**Comment by codebytere** [comment]
This can be accomplished by specifying `pageSize` as specified in [docs](https://github.com/electron/electron/blob/27d629abb983fca5b0943ffba9564d9d7e31b8a5/docs/api/web-contents.md#L1308-L1309)
