### ISSUE TITLE
Windows: Electron crashes when parameter contains "tp:" followed by another

### ISSUE THREAD

**Issue by cachius** [electron/electron#24099]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9
  * 8
  * 7
  * 6
  * 5
* **Operating System:**
  * Windows
* **Last Known Working Electron version:**
  * ?

### Expected Behavior
The application should start.

### Actual Behavior
The application does not start.

### To Reproduce
`electron --i tp: 2`

### Additional Information
This makes it hard to pass http URLs as parameters.

**Comment by MarshallOfSound** [comment]
@cachius This is expected behavior, Electron will not launch on windows if a URL parameters is provided **without** a proceeding `--` argument.

i.e.

```
// Good
electron --i -- tp: 2

// Bad
electron --i tp: 2
```

**Comment by cachius** [comment]
@MarshallOfSound Electron will launch fine as long the URL parameter is the last one:
<pre>
// Good
electron index.js param https://www.electronjs.org/
electron index.js launch https://🚀.ws

// Bad
electron index.js https://www.electronjs.org/ param
electron index.js https://🚀.ws 💥
</pre>
You dev and test on macOS, works. You test on win, fails with %ERRORLEVEL% -1.

**Comment by cachius** [comment]
It is not only tp: but any parameter of the form _starting with a letter, colon at position 3 or more_ (roughly `[A-Za-z][\S:]+:\S*`)(e.g. `re:subject B4:I8 obj::method f1:x+2 d-:`)  that stops electron silently.

**Comment by MarshallOfSound** [comment]
Yes, this is expected behavior for windows.
