### ISSUE TITLE
nativeTheme updated event not emit

### ISSUE THREAD

**Issue by Fndroid** [electron/electron#24092]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  9.0.2
* **Operating System:**
  *  macOS 10.15.5
* **Last Known Working Electron version:**
  *  None

### Expected Behavior

updated event of nativeTheme emit when system theme changed

### Actual Behavior

nothing happened

### To Reproduce

```js
app.on('ready', () => {
  nativeTheme.on('updated', () => {
    global.isDarkMode = !nativeTheme.shouldUseDarkColors
  })
}
```

### Screenshots

None

### Additional Information

I try using systemPreferences instead, and it works, like this:

```js
systemPreferences.subscribeNotification('AppleInterfaceThemeChangedNotification', () => {
    global.isDarkMode = systemPreferences.isDarkMode()
})
```

**But ``isDarkMode()`` function is not returning the right value when notification emit**, it only works after I put a delay of getting that value with a ``setTimeout``

**Comment by codebytere** [comment]
@Fndroid i ran https://gist.github.com/9222eec91cb58cfad3ebf3e67f98d1a3 and saw the following:

<img width="812" alt="Screen Shot 2020-06-11 at 9 37 47 PM" src="https://user-images.githubusercontent.com/2036040/84465442-db3cfd80-ac2b-11ea-8170-dbbd7617f6f1.png">

Which i believe to be correct. I'm not sure i understand what the issue is here 🤔

**Comment by Fndroid** [comment]
@codebytere thank you for the testing. What macOS version do you use? I’m using 10.15.5 and not sure if this break my code 🤔

**Comment by Fndroid** [comment]
@codebytere I tried your code and it works. Thank you again. I will check my code and this issue is closing.

**Comment by codebytere** [comment]
@Fndroid i'm on 10.15.5 too :) Lmk if anything else comes up!
