### ISSUE TITLE
macOS: powerMonitor 'shutdown' event is emitted when quitting from the dock icon

### ISSUE THREAD

**Issue by jwonderly** [electron/electron#24105]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.
    * Issue https://github.com/electron/electron/issues/15022 reports the same issue, but it was closed without a satisfying resolution

### Issue Details

* **Electron Version:**
  * 8.1.1
* **Operating System:**
  * macOS 10.15.4
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
The [powerMonitor shutdown event](https://www.electronjs.org/docs/api/power-monitor#event-shutdown-linux-macos) description says that it is emitted when "the system is about to reboot or shut down". Based on the description I would expect this event to be emitted only when the OS is about to shut down or reboot.

### Actual Behavior

The powerMonitor shutdown event is also emitted on macOS when the user quits the app from the dock icon (right click on dock icon > Quit).

https://github.com/electron/electron/issues/15022 reports the same issue, but it was closed as "expected behavior", but that does not seem correct to me because the behavior does not match the documentation. If this really is expected behavior then I think the documentation should be updated to reflect the actual behavior.

### To Reproduce
Electron Fiddle gist link: https://gist.github.com/jwonderly/25681d6dd6cd4b4af590cb2f30f8ecac

Run the Fiddle on macOS and quit the app from the dock icon. A dialog box will pop up when the powerMonitor 'shutdown' event is emitted.

### Additional Information

Electron might be able to use [NSWorkspaceWillPowerOffNotification](https://developer.apple.com/documentation/appkit/nsworkspacewillpoweroffnotification?language=objc) as the trigger for the powerMonitor shutdown event on macOS.

**Comment by Yovaniteo** [comment]
teo

**Comment by codebytere** [comment]
@jwonderly after thinking about this for a bit i agree with your perspective, i think. When macOS shuts down, Cocoa will send an `NSWorkspaceWillPowerOffNotification` followed by `-[NSApplication terminate:]` - the original PR that added this on mac hooked into the latter instead of the former, but created the side effect that it would also be called when the app itself terminated. I think it should be possible to hook into the former as you suggest for better DX, so ill look into swapping this around (but no timeline promises) :)

**Comment by jwonderly** [comment]
@codebytere that's great, thank you!

**Comment by codebytere** [comment]
@jwonderly it was simpler than i assumed, just popped up a PR.

**Comment by jwonderly** [comment]
@codebytere wow, that was fast! Thanks!
