### ISSUE TITLE
nativeWindowOpen causes all connected renderers to crash when multiple chained child BrowserWindows are opened

### ISSUE THREAD

**Issue by Stimshots** [electron/electron#24129]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
When enabling the 'nativeWindowOpen' setting for a BrowserWindow, chaining multiple child browsers together (running window.open inside a child window) results in BrowserWindows immediately closing without reason. It reproduces far more often which switching between a URL and a custom file protocol but has occurred when using purely URLs. I have created a basic application for reproducing the crash https://github.com/Stimshots/electron-window.open-crash

* **Electron Version:**
  * 8.2.0, 9.0.0, 9.0.3
* **Operating System:**
  * Windows 10 (1909)
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
Using window.open with 'nativeWindowOpen' enabled should open a new BrowserWindow without crashing.

### Actual Behavior
Using window.open multiple times in a row with 'nativeWindowOpen' enabled will close out all BrowserWindows related to the same session.

### To Reproduce
1. git clone https://github.com/Stimshots/electron-window.open-crash
2. npm install
3. npm run start
4. In the debug tools panel paste window.open('https://youtube.com');
5. In the child window's debug tools panel paste window.open('testing://index.html');
6. All BrowserWindows will close unexpectedly

**Comment by pushkin-** [comment]
@Stimshots Can you repro this if the second window you open is an https site (like google.com, say)? I couldn't repro this issue. Is it specific to using the custom `testing:` protocol? Is something just crashing in your new-window handler?

**Comment by Stimshots** [comment]
@pushkin- I updated the repo with some changes to make it much easier to test. Give this a try:

1. npm run start
2. In the debug tools panel paste window.open('http://github.com');
3. In the child window's debug tools panel paste window.open('http://github.com');
4. The new child window will immediately close

From my testing it looks like it's something to do with the protocol handling because github will immediately redirect to https then the browser window explodes. Similar behavior happens when opening a child window with a custom protocol.

**Comment by pushkin-** [comment]
@Stimshots Haven't tested yet, but this seems peculiar:

```
event.preventDefault()
const win = createWindow(options.webContents);
win.loadURL(url);
event.newGuest = win;
```

Can't you just modify `options` to have the `nativeWindowOpen: true` (if that's not already the case), and then let Electron handle the rest?
Why do you need to do this?

**Comment by aquade** [comment]
This is a minimal example but I also need to setup many different event handlers beyond what modifying the options allows (ex: setup input event handlers for shortcuts).

**Comment by Stimshots** [comment]
This is a minimal example but I also need to setup many different event handlers beyond what modifying the options allows (ex: setup input event handlers for shortcuts).

**Comment by pushkin-** [comment]
You could do all of that in the browser-window-created handler probably.

But anyway, I can repro this, and opening windows to an https site works fine. It's http that's struggling for some reason.
