### ISSUE TITLE
integrate the core ui admin template into electron

### ISSUE THREAD

**Issue by asad-amjad** [electron/electron#24125]
Hi i am trying to include the core-ui admin template into the electron, any ideas how can i integrate the admin template into this?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
