### ISSUE TITLE
Custom secure hostnames

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#24124]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.3.1 
* **Operating System:**
  * macOS 10.14
* **Last Known Working Electron version:**
  * n/a/

### Expected Behavior

I'm debugging the app locally, querying a custom hostname for loading the renderer process, and `crypto.subtle` should be available.

### Actual Behavior

`crypto.subtle` is undefined.

### To Reproduce

My setup is a little weird but it's extremely convenient for debugging across OSes:

- I have the app running on my machine, where the renderer process queries `localhost:port`.
- I have a virtual machine active.
- I think the virtual machine program I'm using maps my actual localhost to a custom IP address inside the virtual machine.
- I have mapped that custom IP address to `localhostmac` inside the virtual machine.
- I then run the app from the virtual machine too, this time making the renderer process query `localhostmac:port`.
- Everything seems to work, but now `crypto.subtle` is undefined because electron thinks that's not a safe context while I'm actually truly just querying localhost.

I haven't found a way to override this behavior, or maybe more appropriately add "localhostmac" to a list of safe hostnames.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!

**Comment by fabiospampinato** [comment]
Can this be reopened? It's still relevant in v12 and I'm not aware of a decent workaround for it. Debugging the app that way across operating system should be made easier if anything.

**Comment by nornagon** [comment]
there are several workarounds for this, including [`--host-rules`](https://www.electronjs.org/docs/api/command-line-switches#--host-rulesrules), disabling web security, or setting up a custom protocol with `secure: true`.

**Comment by fabiospampinato** [comment]
@nornagon I'll have to spend some more time with those but I'm not sure those are workarounds for what I need. First of all disabling web security shouldn't be necessary and that affects other things too. Setting up a custom protocol I don't think matters, I need to load the app served on the host OS in a guest OS by loading the app at "http://localhostmac:port", what can I use a custom protocol for if I still need to go through that address and that address will cause the app to consider the environment insecure? Host rules seem to just be a way to map addresses onto other addresses, but like I don't need to map "http://localhostmac:port" onto anything, I need the app to treat that as a secure address, if I map it onto localhost I think the app from the guest OS will just be querying the guest OS rather than the host OS.
