### ISSUE TITLE
HTML fullscreen API not working with Electron

### ISSUE THREAD

**Issue by timothylui** [electron/electron#24136]
### Issue Details

* **Electron Version:**
  * 8.3.0
* **Operating System:**
  * macOS 10.15.5
* **Last Known Working Electron version:**
  * unknown

### Expected Behavior
Using the HTML5 fullscreen API, I expect to be able to enter and exit fullscreen mode.

### Actual Behavior
This works fine on windows 10 2004 and ubuntu 20.04, but on mac, it successfully makes the window fullscreen, but exit fullscreen does nothing (the log line is printed, so it is definitely firing the function).

### To Reproduce
Add a button with the below in a function to toggle between fullscreen and exiting fullscreen.

eg 

```
            if (!document.fullscreenElement) {
                console.log("requestFullscreen")
                document.documentElement.requestFullscreen();
            } else {
                if (document.exitFullscreen) {
                console.log("exitFullscreen")
                document.exitFullscreen();
                }
            }
```

**Comment by codebytere** [comment]
@timothylui i ran https://gist.github.com/a6bd70b11010144e1b25da3d93fd6fb1 and experienced no issues.

**Comment by timothylui** [comment]
> @timothylui i ran on macOS and Catalina https://gist.github.com/a6bd70b11010144e1b25da3d93fd6fb1 and experienced no issues. Are you sure it's an issue with Electron?

@codebytere You're right, your example does work. It must be something else in my project that is causing it. Just a bit weird that it only affects electron on macOS. Thanks for the help
