### ISSUE TITLE
is_component_build in testing.gn cannot be set true

### ISSUE THREAD

**Issue by bigben0123** [electron/electron#24132]
I want to set 
     is_component_build = true
in testing.gn. 

but when do
      gn gen out/Testing --args="import(\"//electron/build/args/testing.gn\")"
It outputs:

`Generating files...
ERROR at //electron/BUILD.gn:305:1: Dependency not allowed.
source_set("electron_lib") {
^---------------------------
The item //electron:electron_lib
can not depend on //third_party/webrtc/modules/desktop_capture:desktop_capture
because it is not in //third_party/webrtc/modules/desktop_capture:desktop_capture's visibility list: [
  //third_party/webrtc/*
  //third_party/webrtc_overrides/*
]
`
What do I need to define?

**Comment by MarshallOfSound** [comment]
`is_component_build` is not supported in Electrons build system

**Comment by kromain** [comment]
You might want to update your public-facing documentation then: https://www.electronjs.org/docs/development/build-system-overview#component-build

> Since Chromium is quite a large project, the final linking stage can take quite a few minutes, which makes it hard for development. In order to solve this, Chromium introduced the "component build", which builds each component as a separate shared library, making linking very quick but sacrificing file size and performance.
Electron inherits this build option from Chromium. In Debug builds, the binary will be linked to a shared library version of Chromium's components to achieve fast linking time; for Release builds, the binary will be linked to the static library versions, so we can have the best possible binary size and performance.

As of August 2021, `is_component_build = true` is still not working, for no good reason.

Assuming I don't just give up on Electron right away and go back to CEF, let's say I decide to spend the time on trying to fix this so I can hack on Electron without wasting hours on linking time. What would be my chances of getting the fix upstreamed? Is it a  straight "no we don't care about this option and won't accept any effort to make it work", or is it a "we'll gladly take the fix if you contribute it?"

**Comment by z4lem** [comment]
> `is_component_build` is not supported in Electrons build system
Are there plans to include this in future releases?

**Comment by ylqhust** [comment]
> 



> > > `is_component_build` is not supported in Electrons build system
> > > Are there plans to include this in future releases?
> 
> I'm not speaking on behalf of the project owers/maintainers, but my sense is that there's no interest in it so it's very unlikely to happen in the foreseeable future.
> 
> To be fair, after spending a few months working on Electron/Chromium, the only use I see for component builds is when doing "full" debug builds (which aren't officially supported either btw) when you're working on the internals of it. This is arguably not the case for most users of Electron.
> 
> The good news is I got it working, and as of 17-x-y it's not that many fixes to make, just a couple of patches and adding a few missing dependencies in `BUILD.gn`. I'm in the final stage of getting approval from my employer to contribute these changes, hopefully this week. I'll update this thread when the changes are up. Hopefully some will be simple enough to be upstreamed, but otherwise I'll just keep them in a fork and will share the link here.



> > > `is_component_build` is not supported in Electrons build system
> > > Are there plans to include this in future releases?
> 
> I'm not speaking on behalf of the project owers/maintainers, but my sense is that there's no interest in it so it's very unlikely to happen in the foreseeable future.
> 
> To be fair, after spending a few months working on Electron/Chromium, the only use I see for component builds is when doing "full" debug builds (which aren't officially supported either btw) when you're working on the internals of it. This is arguably not the case for most users of Electron.
> 
> The good news is I got it working, and as of 17-x-y it's not that many fixes to make, just a couple of patches and adding a few missing dependencies in `BUILD.gn`. I'm in the final stage of getting approval from my employer to contribute these changes, hopefully this week. I'll update this thread when the changes are up. Hopefully some will be simple enough to be upstreamed, but otherwise I'll just keep them in a fork and will share the link here.



> > > `is_component_build` is not supported in Electrons build system
> > > Are there plans to include this in future releases?
> 
> I'm not speaking on behalf of the project owers/maintainers, but my sense is that there's no interest in it so it's very unlikely to happen in the foreseeable future.
> 
> To be fair, after spending a few months working on Electron/Chromium, the only use I see for component builds is when doing "full" debug builds (which aren't officially supported either btw) when you're working on the internals of it. This is arguably not the case for most users of Electron.
> 
> The good news is I got it working, and as of 17-x-y it's not that many fixes to make, just a couple of patches and adding a few missing dependencies in `BUILD.gn`. I'm in the final stage of getting approval from my employer to contribute these changes, hopefully this week. I'll update this thread when the changes are up. Hopefully some will be simple enough to be upstreamed, but otherwise I'll just keep them in a fork and will share the link here.

hi, can you share the patch to make is_component_build working

**Comment by kromain** [comment]
Hi @ylqhust,

I've created a PR https://github.com/electron/electron/pull/36745 with the patch we've used for our debug builds. But be aware that it's based on the almost-year-old Electron 17 release, unfortunately we haven't kept it updated with the newer releases. But the principle should be the same at least.

I've also rebased the changes on top of the latest `main` at https://github.com/kromain/electron/tree/main-debug-build just to remove the fixes that have been merged to upstream Chromium in the meantime. However I haven't tested it at all, I haven't even tried building it, so don't expect it to be usable as-is (I don't have access to a proper build machine at the moment). But again, that should give you an idea of what's required to make it work.

Hope that helps,
Romain

**Comment by ylqhust** [comment]
> Hi @ylqhust,
> 
> I've created a PR #36745 with the patch we've used for our debug builds. But be aware that it's based on the almost-year-old Electron 17 release, unfortunately we haven't kept it updated with the newer releases. But the principle should be the same at least.
> 
> I've also rebased the changes on top of the latest `main` at https://github.com/kromain/electron/tree/main-debug-build just to remove the fixes that have been merged to upstream Chromium in the meantime. However I haven't tested it at all, I haven't even tried building it, so don't expect it to be usable as-is (I don't have access to a proper build machine at the moment). But again, that should give you an idea of what's required to make it work.
> 
> Hope that helps, Romain

thanks very much, this is very helpful!

**Comment by reitowo** [comment]
It takes forever to link on is_debug=true, errr.
