### ISSUE TITLE
clearStorageData doesn't clear localStorage in some situations

### ISSUE THREAD

**Issue by PalmerAL** [electron/electron#24130]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 9.0.4
  * 
* **Operating System:** tested on macOS 10.13.6 and 10.14.6
  * 
* **Last Known Working Electron version:**
  * 

### Expected Behavior

`session.clearStorageData({origin: 'https://'})` should clear all storage for the matching origins.

### Actual Behavior

* `clearStorageData({origin: 'file://'})` clears both cookies and localStorage for file:// pages.
* However, `clearStorageData({origin: 'https://'})` clears only cookies for HTTPS pages, but not localStorage.
* If I set a specific origin, `clearStorageData({origin: 'https://example.com'})`, then both cookies and localStorage are cleared.

### To Reproduce

```
git clone https://github.com/palmerAL/electron-quick-start.git
cd electron-quick-start
git checkout storage-data
```

The testcase contains two parts: 1) a frame that loads https://www.manifest.app/, which is a simple page that saves what you type in the textbox into localStorage, and 2) a textbox directly inside the electron app that does the same thing. Below that, the "clear local data" button calls `clearStorageData({origin: 'file://'})`, and the "clear remote data" button calls `clearStorageData({origin: 'https://'})`.

To reproduce:

1. Type something in the first textbox (inside the frame), and type something else inside the second textbox (outside the frame). Restart the app, and verify that what you typed re-appears in both textboxes (because they were saved in local storage).
2. Click the "clear local data" button, and restart the app.
3. The content of the second textbox should have disappeared.
4. Now click "clear remote data", and restart the app again.
5. At this point, the content of the first textbox should have been erased, but it will re-appear instead - this is the bug.
6. Click "clear data for manifest.app", and re-open the app.
7. This time, localStorage will be cleared correctly.

The documentation isn't very clear about whether passing `https://` to `origin` is supposed to be supported, but since it works for clearing cookies, I'm assuming it is. If it isn't, then I suppose this is a feature request - what I'm trying to do is clear localStorage from http:// and https:// pages, but not file:// ones.

Let me know if there's anything else I can provide!

**Comment by JoahTheron** [comment]
I am having the same issue with Ubuntu 14.04, Ubuntu 16.04, Ubuntu 18.04.

It is a bit extended on my side, because it freezes the Website on some occations and the 'unresponsive' Event is thrown.

After some minutes I just do clearStorageData again and it clears the storage afterwards.
