### ISSUE TITLE
Could electron add support for the --user-data-dir Command Line Switch?

### ISSUE THREAD

**Issue by FoonkG** [electron/electron#24151]
### Problem Description
I would like to use this feature to make a browserwindow more human-like.
The ability to use chromium/chrome user profiles makes a browser appear more natural.

![image](https://user-images.githubusercontent.com/54715823/84784887-1ef88400-afeb-11ea-9143-2a74f44a5b45.png)

### Proposed Solution
Add support for the --user-data-dir Command Line Switch and user profiles in browser windows.

**Comment by cachius** [comment]
It does already via `app.setPath('userData', pathToYourProfileDirectory)`
Citation from [app.md](https://github.com/electron/electron/blob/master/docs/api/app.md#appsetpathname-path)
> By default, web pages' cookies and caches will be stored under the userData directory. If you want to change this location, you have to override the userData path before the ready event of the app module is emitted.
