### ISSUE TITLE
Regression in Node.js APIs in the preload script because of allowRendererProcessReuse after page reload

### ISSUE THREAD

**Issue by aabuhijleh** [electron/electron#24173]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  9.0.4
* **Operating System:**
  *  Windows 10
* **Last Known Working Electron version:**
  *  Not sure

### Expected Behavior

Node.js APIs to work normally like when `app.allowRendererProcessReuse` is set to `false`

### Actual Behavior

Node.js APIs callbacks never trigger when `app.allowRendererProcessReuse` is set to `true`

### To Reproduce

```sh
$ git clone https://github.com/aabuhijleh/allowRendererProcessReuse-reload-issue.git
$ npm install
$ npm start
```

* Reload the page
* `fs.readdir`'s callback for example in the preload script never triggers

```ts
  document.getElementById("readdirBtn").addEventListener("click", async () => {
    await ipcRenderer.invoke("createWindow");
    console.log("before readdir");
    fs.readdir(path.dirname(process.execPath), async (err, items) => {
      console.log("readdir", err, items); // never reached after reload <------
      await ipcRenderer.invoke("closeWindow");
    });
  });
```

### Screen Recording

![reproduce issue](https://user-images.githubusercontent.com/42934634/84900914-6e09ec00-b0b3-11ea-8c19-b9c9d8de44fb.gif)

**Comment by longsoft-au** [comment]
This is exactly what I found out in the past few days too. I had to set app.allowRendererProcessReuse to false so that the fs.readdir callback or Promise can work after page refresh/reload.

**Comment by aabuhijleh** [comment]
Closing as a duplicate of #22119
