### ISSUE TITLE
Error: Error invoking remote method 'ELECTRON_GUEST_VIEW_MANAGER_CALL': Error:  (-3) loading 'https://www.baidu.com/'

### ISSUE THREAD

**Issue by elmeet** [electron/electron#24171]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  9.0.2 
* **Operating System:**
  * macOS 10.15.4
* **Last Known Working Electron version:**
  * 9.0.4

### Expected Behavior
Expect console not to output error messages.

### Actual Behavior
The console outputs the following error:
```
ipc-renderer-internal.ts:29 Uncaught (in promise) Error: Error invoking remote method 'ELECTRON_GUEST_VIEW_MANAGER_CALL': Error:  (-3) loading 'https://www.baidu.com/'
    at EventEmitter../lib/renderer/ipc-renderer-internal.ts.exports.ipcRendererInternal.invoke
```

### To Reproduce
When using Webview, when dynamically changing SRC to 'http://baidu.com', Webview automatically jumps to 'https://www.baidu.com', the effect is as expected, but the console output is wrong.

### Additional Information
Here's my code, and this is what happens when I dynamically change the SRC value to 'http://baidu.com'.
```
    <webview
      ref="webview"
      :src="src"
      :allowpopups="allowpopups"
      webpreferences="allowRunningInsecureContent=yes"
      enableremotemodule="false"
      style="display: flex; height: 100%; width: 100%;"
    ></webview>
```

**Comment by hk304551556** [comment]
Got the same problem ,any idea?

**Comment by jcolemn3** [comment]
I am also having the same issue.

**Comment by IProudNoob** [comment]
I have this bug too.

**Comment by tday0501** [comment]
Anyone come up with a solution?

**Comment by hellofarhan** [comment]
'enableremotemodule' must be true. Check this for more details. https://www.electronjs.org/docs/api/remote
`enableremotemodule="true"`

**Comment by tday0501** [comment]
Mmm that solution doesn't seem to have worked for me, but I get a slightly different error message... Error occurred in handler for 'ELECTRON_GUEST_VIEW_MANAGER_CALL': Error: ERR_ABORTED (-3) loading

**Comment by twitharshil** [comment]
The same exists for electron v7.3.2

**Comment by Nashorn** [comment]
Same error, any solution

**Comment by pranav-pkasthana** [comment]
I had same issue, but the the main issue was in the loaded web page.(some of the script files were not found with error 404). 
After fixing that the Electron error was resolved.

**Comment by Nashorn** [comment]
This has to do with using the electron app over VPN

**Comment by Wonder233** [comment]
The same exists for electron v10.0.1

**Comment by femiveys** [comment]
I have the same problem. Any news on this?

**Comment by nornagon** [comment]
Unfortunately without any steps to reproduce this issue we can't debug further. Please provide a small example that reproduces the issue you're seeing, preferable using [Electron Fiddle](https://github.com/electron/fiddle).

Thanks!

**Comment by elmeet** [comment]
I reproduced the issus on electron fiddle. 
Electron Version: 9.0.2

https://gist.github.com/elmeet/f9f22280cf9e5bfbe3d3357f70ddb6f7

**Comment by elmeet** [comment]
```
Uncaught (in promise) Error: Error invoking remote method 'ELECTRON_GUEST_VIEW_MANAGER_CALL': Error:  (-3) loading 'https://www.npmjs.com/'
```

This error will occur when using react or vue to dynamically set the attribute src, which is similar to the following code.
```javascript
function onDidNavigate(e) {
  if(e.url !== webview.src){
    webview.setAttribute('src', e.url)
  }
}

webview.addEventListener('did-navigate', onDidNavigate);
webview.setAttribute('src', 'http://npmjs.com')
```

**Comment by Nashorn** [comment]
Happens while on VPN

**Comment by Yashwanth1** [comment]
I had same error, Resolved with below lines of code. It might help someone. Thanks

const app = electron.app;
app.commandLine.appendSwitch('ignore-certificate-errors', 'true');

**Comment by asd281533890** [comment]
I got same error when i call webview.reload() or webview.reloadIgnoringCache()

**Comment by Sami-Hedhli** [comment]
I got the same error when  I call webview.load("some url")

**Comment by KorbsStudio** [comment]
This issue is all of sudden happening me, but it worked fine before.
I've tested this one v9.4.3 and v9.4.4.

The following error occurs:
```
Error occurred in handler for 'ELECTRON_GUEST_VIEW_MANAGER_CALL': Error:  (-3) loading 'https://panel.falixnodes.net/auth/login'
    at rejectAndCleanup (electron/js2c/browser_init.js:225:1288)
    at WebContents.failListener (electron/js2c/browser_init.js:225:1505)
    at WebContents.emit (events.js:228:7) {
  errno: -3,
  code: '',
  url: 'https://korbsstudio.com/'
}
```

**Comment by KorbsStudio** [comment]
For me, the problem was found.
The controls were targeting the wrong webview I had listed in the code.

**Comment by theArina** [comment]
I fixed this issue adding catch to `webview.loadURL` .
#28208 related.

**Comment by MounicaChanda0809** [comment]
> @zyzski Thankyou so much!!!!! Solved

Curious to know how you fixed it. Could you please post the snippet here?

**Comment by JustTheCoolest** [comment]
Electron version: npm electron@26.3.0
OS: Ubuntu 22.04.3 LTS (WSL2)

I got the same bug when redirecting to another URL while the previous redirect has not finished. I have no control on the first redirect as it originates from the third party webpage itself. I fixed it by catching exceptions from the second redirect I'm making though

> Error: Error invoking remote method 'GUEST_VIEW_MANAGER_CALL': Error:  (-3) loading 'https://www.merriam-webster.com/dictionary/test'

(URL is from first reload's but error comes only if second redirect is made soon after)

Fixed code:
```js
webview.loadURL(this.url)
.catch(e => {
console.log(e);
});
```

Repository commit: https://github.com/JustTheCoolest/GodMode-Search-Integration/commit/c7ed9a2edc8be0031d244bf553ebd1c8519b5375
