### ISSUE TITLE
Error: No such module was linked: atom_browser_v8_util

### ISSUE THREAD

**Issue by lutzroeder** [electron/electron#24189]
### Preflight Checklist
* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**: 9.0.4
* **Operating System:** macOS 10.15.5 (19F101)

### Expected Behavior
Debugging with `All Exceptions` and `Uncaught Exceptions` enabled should not break in the debugger during load.

### Actual Behavior
```
Error: No such module was linked: atom_browser_v8_util
    at _linkedBinding (internal/bootstrap/loaders.js:118:34)
    at process.electronBinding (electron/js2c/browser_init.js:7570:20)
    at Object../lib/browser/api/menu.js (electron/js2c/browser_init.js:1788:24)
    at __webpack_require__ (electron/js2c/browser_init.js:20:30)
    at loader (electron/js2c/browser_init.js:2087:35)
    at Object.Menu (electron/js2c/browser_init.js:7536:19)
    at App../lib/browser/default-menu.ts.exports.setDefaultApplicationMenu (electron/js2c/browser_init.js:4914:29)
    at Object.onceWrapper (events.js:313:26)
    at App.emit (events.js:228:7)
```

### To Reproduce
1. Install Visual Studio Code
2. Install Debugger for Chrome extension
3. `git clone https://github.com/lutzroeder/netron.git`
4. `npm install`
5. Open in Visual Studio Code
6. Debugger > `Launch Application`
7. Enable `All Exceptions` and `Uncaught Exceptions` under `Breakpoints`
8. <kbd>F5</kbd>

### Screenshots

<img width="1057" alt="screenshot" src="https://user-images.githubusercontent.com/438516/84973748-b2f34a00-b0d6-11ea-909b-2c7a0654d658.png">

@codebytere @tarruda

**Comment by codebytere** [comment]
@lutzroeder i'm not sure i understand what the issue is here 🤔 this is an expected error - `v8_util` is a `common` module which is why this is wrapped in a try/catch to fall back onto `electron_common_v8_util` (which is what's actually linked)

**Comment by lutzroeder** [comment]
Ideally `try`/`catch` in system code that runs in a common startup code path should be avoided. Anyone debugging their app will break with this exception during <kbd>F5</kbd> every single time. Is there a way to accomplish the same without `try`/`catch`?

**Comment by codebytere** [comment]
@lutzroeder i'm not sure what the best path here is ultimately but i kicked up a PR so let's see where it goes.

**Comment by lutzroeder** [comment]
microsoft/vscode#41721
