### ISSUE TITLE
Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source

### ISSUE THREAD

**Issue by lutzroeder** [electron/electron#24188]
### Preflight Checklist
* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version**: 9.0.4
* **Operating System:** macOS 10.15.5 (19F101)

### Expected Behavior
Debugging with `All Exceptions` and `Uncaught Exceptions` enabled should not break in the debugger during load.

### Actual Behavior
After restricting `Content-Security-Policy` to  `<meta http-equiv="Content-Security-Policy" content="script-src 'self' 'unsafe-inline';">` the code below will break in the debugger if `All Exceptions` and `Uncaught Exceptions` is enabled.
```
Exception has occurred: EvalError
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'".

    at new Function (<anonymous>)
    at <anonymous>:3:13
    at <anonymous>:9:7
    at WebFrame../lib/renderer/api/web-frame.ts.WebFrame.<computed> [as executeJavaScript] (electron/js2c/renderer_init.js:1495:33)
    at isUnsafeEvalEnabled (electron/js2c/renderer_init.js:2532:32)
    at warnAboutInsecureCSP (electron/js2c/renderer_init.js:2610:5)
    at logSecurityWarnings (electron/js2c/renderer_init.js:2709:5)
    at loadHandler (electron/js2c/renderer_init.js:2725:13)
```

### To Reproduce

This issue does not reproduce reliably. It happens sporadically when launching the debugger after these steps:

1. Install Visual Studio Code
2. Install Debugger for Chrome extension
3. `git clone https://github.com/lutzroeder/netron.git`
4. `npm install`
5. Open in Visual Studio Code
6. Debugger > `Debug Renderer Process`
7. Enable `All Exceptions` and `Uncaught Exceptions` under `Breakpoints`
8. <kbd>F5</kbd>

### Screenshots
<img width="1090" alt="screenshot" src="https://user-images.githubusercontent.com/438516/84971735-39f1f380-b0d2-11ea-985f-d14a410151ba.png">

@miniak, @codebytere

**Comment by codebytere** [comment]
@lutzroeder can you please fill the template?

**Comment by lutzroeder** [comment]
@codebytere Unfortunately this is not a reliable repro. Will keep looking for consistent steps.

#24189 is related and repros reliably.

**Comment by lutzroeder** [comment]
@codebytere with the new JavaScript debugger in Visual Studio Code 1.47.1 this now repros reliably:

1. Install Visual Studio Code 1.47.1
2. Install Debugger for Chrome extension
3. `git clone https://github.com/lutzroeder/netron.git && cd netron`
4. `npm install`
5. Open in Visual Studio Code
6. Debugger > `Debug Renderer Process`
7. Enable `Caught Exceptions` and `Uncaught Exceptions` under `Breakpoints`
8. <kbd>F5</kbd>
9. Press <kbd>F5</kbd> 8 times to step over other breaks addressed in #24189

<img width="1209" alt="Screen Shot 2020-07-14 at 8 58 11 PM" src="https://user-images.githubusercontent.com/438516/87501852-fa58f180-c614-11ea-9de2-9334919b54e3.png">

**Comment by lutzroeder** [comment]
@felixrieseberg do you have any insights how this check should be changed to not raise an exception in each debug session?

**Comment by codebytere** [comment]
good q - i have some time today and will dig into it!
