### ISSUE TITLE
use electron depot-tools sync code need winsdk

### ISSUE THREAD

**Issue by bigben0123** [electron/electron#24190]
I just want download source code.

> 1,

config file is : .electron_build_tools\configs\evm.electron7.json
{
"goma": "none",
"root": "D:\dev\electron-master\electron",
"origin": {
"electron": "git@github.com:electron/electron.git",
"node": "git@github.com:electron/node.git"
},
"gen": {
"args": [
"import("//electron/build/args/testing.gn")"
],
"out": "Testing"
},
"env": {
"CHROMIUM_BUILDTOOLS_PATH": "D:\dev\electron-master\electron\src\buildtools",
"DEPOT_TOOLS_WIN_TOOLCHAIN": 0,
"GIT_CACHE_PATH": "C:\Users\zhibin\.git_cache"
}
}
>2 update the .gclient
solutions = [
  { "name"        : 'src/electron',
    "url"         : 'https://github.com/electron/electron@7-3-x',
    "deps_file"   : 'DEPS',
    "managed"     : False,
    "custom_deps" : {
    },
    "custom_vars": {},
  },
]
>3 
after do: e sync

Does the error mean I have to install vs2019 sdk? I just want to get code and not to build.
It seems if not set 
"DEPOT_TOOLS_WIN_TOOLCHAIN": 0
. It can download success. but in that case, goole will download sdk for me? I don't need sdk.

________ running 'vpython.bat src/tools/clang/scripts/update.py' in 'C:\dev\electron7'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Win/clang-371202-8455294f-1.tgz .......... Done.
Traceback (most recent call last):
File "src/tools/clang/scripts/update.py", line 336, in 
sys.exit(main())
File "src/tools/clang/scripts/update.py", line 332, in main
return UpdateClang()
File "src/tools/clang/scripts/update.py", line 270, in UpdateClang
CopyDiaDllTo(os.path.join(LLVM_BUILD_DIR, 'bin'))
File "src/tools/clang/scripts/update.py", line 230, in CopyDiaDllTo
GetWinSDKDir()
File "src/tools/clang/scripts/update.py", line 204, in GetWinSDKDir
win_sdk_dir = vs_toolchain.SetEnvironmentAndGetSDKDir()
File "C:\dev\electron7\src\build\vs_toolchain.py", line 518, in SetEnvironmentAndGetSDKDir
SetEnvironmentAndGetRuntimeDllDirs()
File "C:\dev\electron7\src\build\vs_toolchain.py", line 85, in SetEnvironmentAndGetRuntimeDllDirs
os.environ['GYP_MSVS_OVERRIDE_PATH'] = DetectVisualStudioPath()
File "C:\dev\electron7\src\build\vs_toolchain.py", line 173, in DetectVisualStudioPath
version_as_year = GetVisualStudioVersion()
File "C:\dev\electron7\src\build\vs_toolchain.py", line 163, in GetVisualStudioVersion
' Supported versions are: %s.' % supported_versions_str)
Exception: No supported Visual Studio can be found. Supported versions are: 15.0 (2017), 16.0 (2019).
Error: Command 'vpython.bat src/tools/clang/scripts/update.py' returned non-zero exit status 1 in C:\dev\electron7

**Comment by codebytere** [comment]
You should use [`build-tools`](https://github.com/electron/build-tools) and open subsequent issues there.

See https://github.com/electron/electron/issues/24169#issuecomment-645742590.
