### ISSUE TITLE
Change icon programmaticaly when app is launched via exe shortcut.

### ISSUE THREAD

**Issue by Amaurgit** [electron/electron#24209]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
6.13.14
* **Operating System:**
Windows 10 (1803)

### Expected Behavior
When the app is launched via an app shortcut, I expect that the icon of the taskbar changes the same way it does with the original app exe when using the setIcon() api

### Actual Behavior
When the app is launched via a shortcut, the setIcon() api doesn't change the taskbar icon. Is there something I'm missing ? I'm aware that this is a marginal usecase and I'm surely doing something wrong.

Is there some cache with the shortcut ?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 7.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
