### ISSUE TITLE
Support for using Segment Heap on Win 10

### ISSUE THREAD

**Issue by pshah123** [electron/electron#24215]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
RAM usage is high because of Chromium and difficult to slash at a general level.

### Proposed Solution
I'm submitting a feature request for enabling the use of the Segment Heap on Windows 10 as it would improve memory usage on Windows devices by an enormous amount, which would also mitigate one of the largest criticisms of Electron (the crazy high RAM usage of Chromium).

### Additional Information
On Windows 10 there is a feature called the Segment Heap which significantly cuts down RAM usage with a new heap implementation -- it supposedly cuts down memory usage by 27% in the Chromium flavor of Edge and Chrome is slated to enable it in their next release.

**Comment by TylerBurnett** [comment]
I'm curious about this myself, if it's implemented in with chrome wouldn't that mean it would be coupled in with the next update by default? Not sure if there's any effort required by electron maintainers outside of updating.

**Comment by nornagon** [comment]
We'll inherit this from Chromium if and when they enable it. It's not something we can control in Electron.
