### ISSUE TITLE
[Error] Image could not be created from ...

### ISSUE THREAD

**Issue by SentoxAIO** [electron/electron#24221]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** ^9.0.4
* **Operating System:**  Windows 10
* **Last Known Working Electron version:** ^9.0.4

### Expected Behavior
The icon should be created normally like it did before but since I changed the picture it fails to create the image.

### Actual Behavior
The electron app doesn't get started/build and I get this error:
`Error: Image could not be created from ./../html/assets/images/logo.png` when trying to start it.

### Screenshots
![image](https://user-images.githubusercontent.com/57367608/85209476-a837ef80-b338-11ea-849e-8c21eb0973e8.png)
![image](https://user-images.githubusercontent.com/57367608/85209485-bd148300-b338-11ea-9dcb-f11fa398f2e5.png)
![image](https://user-images.githubusercontent.com/57367608/85209480-b5ed7500-b338-11ea-9625-7ab0a7b5adbe.png)

**Comment by codebytere** [comment]
Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

**Comment by fabiospampinato** [comment]
@codebytere Here you go: https://gist.github.com/0dcad6c93d264477c604b880750980bc

Broken in v9.0.4, works in v8.3.3.

Btw data-url favicons are broken too, same in latest Chrome, so the folks at Chrome might have broken this.

**Comment by codebytere** [comment]
@fabiospampinato thanks! it actually crashes on latest nightlies, so i'll poke into it as soon as i can.

**Comment by fabiospampinato** [comment]
@codebytere That works for me too, thanks for the suggestion. I'm just not setting an icon explicitly anymore for now, that seemed like the best solution for me.

**Comment by Blightysoft** [comment]
We have the same issue. Sadly, even using `nativeImage.createFromPath()` (since we're using a standard file path) didn't resolve it for us. And we need the icon for the Linux distro. So we'll just wait for a bug fix and not upgrade for now.

**Comment by SentoxAIO** [comment]
```
	browserWindow.setIcon(
		nativeImage.createFromPath(
			path.join(__dirname, "ICON_PATH")
		)
	);
```

@Blightysoft If you need to get it working asap, this worked for me and fixed my issue

**Comment by NilSet** [comment]
I am also seeing issues when providing the string absolute path to a .icns file in the `icon` arg to BrowserWindow, and it works when i replace it with `icon: nativeImage.createFromPath(pathToTheAppIcon`

**Comment by alienzhangyw** [comment]
> I am also seeing issues when providing the string absolute path to a .icns file in the `icon` arg to BrowserWindow, and it works when i replace it with `icon: nativeImage.createFromPath(pathToTheAppIcon)`

This works for me too!

**Comment by FrancescoBorzi** [comment]
I can confirm this is still an issue in electron `9.3.1`, a **regression** since electron `8.x.x`.

I can also confirm that replacing:

```typescript
icon: pathToTheAppIcon
```

with

```typescript
icon: nativeImage.createFromPath(pathToTheAppIcon)
```

fixes the issue.

**Comment by xiaorongliu** [comment]
> nativeImage.createFromPath(pathToTheAppIcon)



> I am also seeing issues when providing the string absolute path to a .icns file in the `icon` arg to BrowserWindow, and it works when i replace it with `icon: nativeImage.createFromPath(pathToTheAppIcon)`

This works for me,too.thank you!

**Comment by eric-burel** [comment]
@FrancescoBorzi is this fix definitive or temporary? From the API it seems that file path should be accepted, so I guess it's actually a bug, but using nativeImage is an ok, future-proof fix? I experience this upgrading from v7 to v9

**Comment by FrancescoBorzi** [comment]
> @FrancescoBorzi is this fix definitive or temporary? From the API it seems that file path should be accepted, so I guess it's actually a bug, but using nativeImage is an ok, future-proof fix? I experience this upgrading from v7 to v9

I'm not sure, I haven't looked into it again.
