### ISSUE TITLE
child_process execFile and spawn hang on Windows

### ISSUE THREAD

**Issue by kripper** [electron/electron#24222]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.14.4
* **Operating System:**
  * Windows 10 (with latest updates)
* **Last Known Working Electron version:**
  * Unknown

### Expected Behavior
Process should not hang.

### Actual Behavior
Running the attached test case (clicking the Test button) the process hangs the second time it is executed.
It works again the third time and fails again once in a while.

### To Reproduce
Run the attached test case and click the Test button multiple times.
In my environment, it fails always the second time and then again once in a while.

[electron-bug.zip](https://github.com/electron/electron/files/4808725/electron-bug.zip)

### Additional Information
The bug only happens when running via win.loadURL (hosted).
When loading via win.loadFile (locally) it seems to work fine (can't be reproduced).

**Comment by nornagon** [comment]
Electron 6 is [no longer supported](https://www.electronjs.org/docs/tutorial/support#currently-supported-versions).

**Comment by kripper** [comment]
Sorry, I informed a wrong (npm) version (6.14.4).
I confirm tested electron version is: electron@9.0.4
I updated the issue report.
Please reopen.

**Comment by kripper** [comment]
> Electron 6 is [no longer supported](https://www.electronjs.org/docs/tutorial/support#currently-supported-versions).

Hi @nornagon 
I confirm tested electron version is: electron@9.0.4.
Should we reopen or recreate the issue?

**Comment by kripper** [comment]
Nevermind. I recreated the issue.
