### ISSUE TITLE
Error invoking remote method 'ELECTRON_GUEST_VIEW_MANAGER_CALL'

### ISSUE THREAD

**Issue by EnderAdel** [electron/electron#24223]
I keep getting this error message whenever this code runs:
```
webview.addEventListener('dom-ready', function (){
  try{
    if(_menuContent.type == "top")
      content.executeJavaScript("document.body.insertBefore(document.createElement('space'), document.body.firstChild);");//This line causes the error to occur
  }catch{
    alert("Something went wrong!");
    showSrrorScreen();
  }
});
```

The full message:
```
ipc-renderer-internal.ts:29 Uncaught (in promise) Error: Error invoking remote method 'ELECTRON_GUEST_VIEW_MANAGER_CALL': Error: An object could not be cloned.
    at EventEmitter../lib/renderer/ipc-renderer-internal.ts.exports.ipcRendererInternal.invoke (ipc-renderer-internal.ts:29)
./lib/renderer/ipc-renderer-internal.ts.exports.ipcRendererInternal.invoke @ ipc-renderer-internal.ts:28
async function (async)
./lib/renderer/ipc-renderer-internal.ts.exports.ipcRendererInternal.invoke @ ipc-renderer-internal.ts:26
(anonymous) @ web-view-impl.ts:241
(anonymous) @ _content.js:89
dispatchEvent @ web-view-impl.ts:120
dispatchEvent @ guest-view-internal.ts:59
(anonymous) @ guest-view-internal.ts:77
emit @ events.js:223
onMessage @ init.ts:50
```

And I also get this error message every time the program starts:
```
Uncaught (in promise) Error: Error invoking remote method 'ELECTRON_GUEST_VIEW_MANAGER_CALL': Error: An object could not be cloned.
    at EventEmitter../lib/renderer/ipc-renderer-internal.ts.exports.ipcRendererInternal.invoke (ipc-renderer-internal.ts:29)
```

**Comment by nornagon** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by nornagon** [comment]
The reason this is happening is that `document.body.insertBefore` returns the DOM element, which cannot be serialized and returned over IPC. To fix this, instead call `content.executeJavaScript('{ document.body.insertBefore(...) }')`. The additional `{}` wraps the expression in a scope and returns `undefined`, which is serializable.

**Comment by Nashorn** [comment]
might be related, but i am using not executeJavaScript(), and it happens on reload of a page that previously loaded without error. It throws this in terminal console:

> electron .

[63920:1023/065529.084421:ERROR:gles2_cmd_decoder.cc(7062)] [.RendererMainThread-0x7fc4e6026e00]GL ERROR :GL_INVALID_OPERATION : glGetIntegerv: incomplete framebuffer
[63920:1023/065529.084527:ERROR:gles2_cmd_decoder.cc(7062)] [.RendererMainThread-0x7fc4e6026e00]GL ERROR :GL_INVALID_OPERATION : glGetIntegerv: incomplete framebuffer
[63920:1023/065529.085584:ERROR:gles2_cmd_decoder.cc(7062)] [.RendererMainThread-0x7fc4e6026e00]GL ERROR :GL_INVALID_OPERATION : glGetIntegerv: incomplete framebuffer
[63920:1023/065529.085647:ERROR:gles2_cmd_decoder.cc(7062)] [.RendererMainThread-0x7fc4e6026e00]GL ERROR :GL_INVALID_OPERATION : glGetIntegerv: incomplete framebuffer
[63920:1023/065529.097773:ERROR:gles2_cmd_decoder.cc(4968)] [.RendererMainThread-0x7fc4e6026e00]GL ERROR :GL_INVALID_FRAMEBUFFER_OPERATION : glDrawArrays: framebuffer incomplete
Error occurred in handler for 'ELECTRON_GUEST_VIEW_MANAGER_CALL': Error: ERR_FAILED (-2) loading '[PRIVATE URL HERE]'
    at rejectAndCleanup (electron/js2c/browser_init.js:201:1288)
    at WebContents.stopLoadingListener (electron/js2c/browser_init.js:201:1673)
    at WebContents.emit (events.js:322:22) {
  errno: -2,
  code: 'ERR_FAILED',
  url: '[PRIVATE URL HERE]'
}

**Comment by RHeynsZa** [comment]
@Nashorn did you ever find a fix? I'm having the same issue

**Comment by theArina** [comment]
@RHeynsZa, hi, what are you trying to do ?

**Comment by RHeynsZa** [comment]
@theArina I'm trying to reload the webview

**Comment by theArina** [comment]
@RHeynsZa, is it happening with any url or a specific one ?

**Comment by theArina** [comment]
So i got this error when i tried to close/reload url with the prompt on leave. I guess i must make some custom prompt handler now.

**Comment by RHeynsZa** [comment]
@theArina, ah exactly my issue. Im trying to reload or navigate from a page that has the confirm to leave. Thanks for figuring it out

**Comment by theArina** [comment]
@RHeynsZa, could you share your url, if it's not private or anything, please ?

**Comment by theArina** [comment]
@RHeynsZa, hey, i guess this is what you need.
https://www.electronjs.org/docs/api/web-contents#event-will-prevent-unload

**Comment by RHeynsZa** [comment]
> @RHeynsZa, could you share your url, if it's not private or anything, please ?

It is unfortunately a private internal company site

**Comment by maynewong** [comment]
node version: v15.4.0
electron version: v11.1.0
mac m1 cpu，cannot run ` webview.addEventListener('dom-ready', () => {}`
```
    addWebviewListener() {
      for (const shop of this.shops) {
        const webview = document.getElementById(shop.id)
        webview.addEventListener('dom-ready', () => {
          // Add ipc message event
          this.addIPCMessageListener(webview)
        })
      }
    }
  
```

background.js  ERROR
```
Error occurred in handler for 'ELECTRON_GUEST_VIEW_MANAGER_CREATE_GUEST': TypeError: Cannot read property 'on' of undefined
    at App.eval (webpack:///./src/background.ts?:311:30)
    at App.emit (events.js:327:22)
    at App.EventEmitter.emit (domain.js:483:12)
    at App.emitter.emit (webpack:///./node_modules/@sentry/electron/esm/main/integrations/electron.js?:70:25)
    at Object.b._init (electron/js2c/browser_init.js:157:11670)
    at Object.create (electron/js2c/browser_init.js:157:12373)
    at electron/js2c/browser_init.js:177:2680
    at electron/js2c/browser_init.js:177:3904
    at electron/js2c/browser_init.js:177:2217
    at electron/js2c/browser_init.js:189:579
```
devtools console ERROR
```
electron/js2c/renderer_init.js:103 Uncaught (in promise) Error: Error invoking remote method 'ELECTRON_GUEST_VIEW_MANAGER_CREATE_GUEST': TypeError: Cannot read property 'on' of undefined
    at EventEmitter.o.invoke (electron/js2c/renderer_init.js:103)
```

**Comment by lonelypx** [comment]
The error message indicates that win.addEventListener is not a function, which suggests that win is not an instance of Window or does not have the addEventListener method. In your case, win is actually contents which is of type webContents and does not have the addEventListener method.

The electron-context-menu module expects a BrowserWindow instance, not a webContents instance. You can get the BrowserWindow from the webContents using the electron module's BrowserWindow.fromWebContents(contents) method


`const { BrowserWindow } = require('electron');

app.on("web-contents-created", (e, contents) => {
  if (contents.getType() == "webview") {
    // get the BrowserWindow from the webContents
    let win = BrowserWindow.fromWebContents(contents);

    // set context menu in webview
    contextMenu({
      window: win,
    });
  }
});`
