### ISSUE TITLE
enableLargerThanScreen not work on Electron9.0.3

### ISSUE THREAD

**Issue by WangYuLue** [electron/electron#24228]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  *  9.03
* **Operating System:**
  * macOS Mojave 10.14.6
* **Last Known Working Electron version:**
  * 8.3.3

### Expected Behavior

I am using frameless window to build a screenshot tool, and I want the tool cover the whole screen.

on Electron 8.3.3 , it works fine：

<img width="1440" alt="屏幕快照 2020-06-22 下午7 03 21" src="https://user-images.githubusercontent.com/19245919/85280642-17d5e800-b4bb-11ea-873c-d41174bb5b9b.png">

### Actual Behavior

but on Electron 9.0.3, the same config ,it can not cover head bar:

<img width="1440" alt="屏幕快照 2020-06-22 下午6 32 30" src="https://user-images.githubusercontent.com/19245919/85280784-671c1880-b4bb-11ea-9f8f-5202fcacdb16.png">

I view the [breaking changes](https://www.electronjs.org/docs/breaking-changes)  log, but do not find relative message。

### To Reproduce

here is my `BrowserWindow` config:

```js
const win = new BrowserWindow({
      fullscreen: isWin(),
      width: this.bounds.width,
      height: this.bounds.height,
      x: this.bounds.x,
      y: this.bounds.y,
      transparent: true,
      frame: false,
      movable: false,
      resizable: false,
      enableLargerThanScreen: true,
      hasShadow: false,
      webPreferences: {
        devTools: false,
        nodeIntegration: true,
        enableRemoteModule: true
     }
  });
win.setAlwaysOnTop(true, 'screen-saver');
win.setVisibleOnAllWorkspaces(true);
win.setFullScreenable(false);
```

I guess it is a problem of enableLargerThanScreen

### Screenshots

<img width="1440" alt="屏幕快照 2020-06-22 下午6 32 30" src="https://user-images.githubusercontent.com/19245919/85281684-02fa5400-b4bd-11ea-83df-8857033bb535.png">

**Comment by daltonmenezes** [comment]
Same issue on Electron 11.2.3

**Comment by daltonmenezes** [comment]
@WangYuLue I just tried now on Electron 11.2.3 with the following configuration and it works:
```js
window = await createWindow({
  id: 'Crop',
  options: {
    titleBarStyle: 'customButtonsOnHover',
    frame: true,
    hasShadow: false,
    focusable: false,
    transparent: true,
    alwaysOnTop: true,
    enableLargerThanScreen: true,
  },
})

window.setAlwaysOnTop(true, 'screen-saver')
window.setVisibleOnAllWorkspaces(true)
```

**Comment by nornagon** [comment]
This works for me on all currently supported versions of Electron (10.x, 11.x, 12.x) as well as in the beta and nightly versions (13.x, 14.x).

```
  const cursor = screen.getCursorScreenPoint()
  const display = screen.getDisplayNearestPoint(cursor)
  const w = new BrowserWindow({
    frame: false,
    movable: false,
    titleBarStyle: 'customButtonsOnHover',
    resizable: false,
    alwaysOnTop: true,
    fullscreenable: false,
    hasShadow: false,
    skipTaskbar: true,
    acceptFirstMouse: true,
    enableLargerThanScreen: true,
    transparent: true,
    width: display.bounds.width,
    height: display.bounds.height,
    x: display.bounds.x,
    y: display.bounds.y
  })
  w.setAlwaysOnTop(true, "pop-up-menu")
```

Closing this as the option seems to be working as expected.
