### ISSUE TITLE
Accelerator 'CommandOrControl+<' not working for global Hotkey

### ISSUE THREAD

**Issue by borsTiHD** [electron/electron#24227]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.11
* **Operating System:**
  * Windows 10 Build 17763

### Expected Behavior
I want to register the following accelerator <kbd><</kbd> as a global hotkey.

### Actual Behavior
Hotkey register function returns true, but it didn't react to the hotkey if I press it.
Is there a way to investigate it further?

### To Reproduce
```
// Register a 'CommandOrControl+<' shortcut listener.
const hotkey = globalShortcut.register('CommandOrControl+<', () => {
    console.log('Hotkey pressed')
})
console.log('Hotkey Register:', hotkey)
```

### Additional Information
Oh forgot to mention... I use a `qwertz` keyboard layout.
Thanks for your help.
I hope this is possible. :)

**Comment by codebytere** [comment]
@borsTiHD unfortunately i don't believe so. We pipe through Chromium's hotkey functionality without altering it too much, so what i recommend you do is try to replicate it on Chrome itself by changing a shortcut to `CommandOrControl+<`. If you succeed, you'll want to open a bug on crbug.com - if not, we can reopen and take another look at this.
