### ISSUE TITLE
Unable to remove 'Pin to Taskbar' and 'Electron' right-click option

### ISSUE THREAD

**Issue by kaushikchaubal** [electron/electron#24233]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.2
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * Not sure if this ever worked

### Expected Behavior
There should be a way to remove the 'Pin to Taskbar' and 'Electron' icon on right-clicking on an Electron app. I also looked if  there was more explanation here: https://www.electronjs.org/docs/tutorial/windows-taskbar but no joy.

### Actual Behavior
The two icons ( 'Pin to Taskbar' and 'Electron') cannot be removed as right-click options.

### To Reproduce
1. Clone https://github.com/electron/electron-quick-start and run it locally on Windows 10
2. Right click on the electron app icon on the taskbar
3. You see 3 options 'Electron', 'Pin to Taskbar', 'Close Window'. I want to remove the first two options - namely 'Electron', 'Pin to Taskbar'.

### Screenshots
<img width="255" alt="electron-right-click-menu" src="https://user-images.githubusercontent.com/808515/85289810-e5fb5c00-b48f-11ea-9259-6bc8f0ab623c.png">

### Additional Information
No other details

**Comment by MarshallOfSound** [comment]
@kaushikchaubal Those options are provided by Windows itself.  Electron has 0 control over those

**Comment by kaushikchaubal** [comment]
Thanks @MarshallOfSound for confirming. I assumed that’s the case with “Pin to Taskbar” icon.

But is that true with the “Electron” option too? I assumed that I would be able to remove that option somehow, no?

**Comment by jgomez109** [comment]
> @kaushikchaubal Those options are provided by Windows itself. Electron has 0 control over those

So why  vscode made with electron js does not have it ???
