### ISSUE TITLE
class Napi::Env has no member named SetInstanceData

### ISSUE THREAD

**Issue by manuel-arguelles** [electron/electron#24248]
Not sure if this is a bug or my fault. I'm following the examples for rebuilding a node c/c++ addon with node-addon-api and noticed that what seems to be the recent example doesn't compile with electron (works fine with node).
 
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.0
* **Operating System:**
  * Ubuntu 18
* **node-gyp:**
  * 7.0.0

### Expected Behavior
The rebuild of the node native module should success as described in https://www.electronjs.org/docs/tutorial/using-native-node-modules 

### Actual Behavior
Fails when SetInstanceData of Napi::Env is in use.

### To Reproduce

For the object wrap example:

```sh
$ git clone git@github.com:nodejs/node-addon-examples.git
$ cd node-addon-examples/6_object_wrap/
$ yarn install
$ HOME=~/.electron-gyp npx node-gyp rebuild --target=9.0.0 --arch=x64
```

There's a similar example for wrapping objects that gets compiled fine in the directory object-wrap-demo. However, I believe the preferred way is as described on the 6_object_wrap (since it's the one linked in the documentation (readme))

### Additional Information
It semes that the methods SetInstanceData and GetInstanceData depends of NAPI_VERSION > 5, however it seems that electron 9.0.0 has 6.

**Comment by qxred** [comment]
Same problem here, my solution is replace engines section in package.json with

`  "engines": {
    "node": ">= 14.0.0"
  },
`

then run npm install again.

reference [https://github.com/nodejs/node-addon-examples/pull/137](https://github.com/nodejs/node-addon-examples/pull/137)

**Comment by Rafi993** [comment]
This [commit](https://github.com/nodejs/node-addon-examples/commit/dc86a662c27c5732e069e1c19d3b7a8e74e86d29) caused this issue going one commit before that and examples works with node 12.x
