### ISSUE TITLE
Honor /tmp being mounted with noexec

### ISSUE THREAD

**Issue by darkdragon-001** [electron/electron#24242]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.5
* **Operating System:**
  * Ubuntu 20.04 x64
* **Last Known Working Electron version:**
  * _I don't know_

### Expected Behavior
Having `/tmp` mounted with `noexec` should not affect regularly installed application.

### Actual Behavior
Crash
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.WVtpuO: Fehler beim Mappen des Shared Objects
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/Signal/resources/app.asar/node_modules/@journeyapps/sqlcipher/lib/sqlite3.js:4:15)
    at Object.<anonymous> (/opt/Signal/resources/app.asar/node_modules/@journeyapps/sqlcipher/lib/sqlite3.js:190:3)
```

### To Reproduce
See signalapp/Signal-Desktop#2595.

### Additional Information
For implementation details @scottnonnenberg-signal will happily answer your questions.

**Comment by nornagon** [comment]
Unfortunately the full Signal app is too large of a repro case to be useful. Can you perhaps replicate the behavior using [Fiddle](/electron/fiddle)?

**Comment by pahhur** [comment]
> Unfortunately the full Signal app is too large of a repro case to be useful. Can you perhaps replicate the behavior using [Fiddle](/electron/fiddle)?

I don't know anything about electron, other than that I have some apps on my desktop that use it.
The problem can easily be replicated by the assignee of the above bug by just entering 

`sudo mount -o remount,noexec /tmp`
 
and running any electron app after that.

**Comment by pahhur** [comment]
Jeremy,

additionally to what I said:

    at Object.<anonymous> (/opt/Signal/resources/app.asar/node_modules/@journeyapps/**sqlcipher/lib/sqlite3.js:190:3)**

"suggests" that using the sqlite3 module would be a good starting point. I cannot install electron-sqlite3 on my system (npm cannot be installed for some weird reason, it depends on node-gyp >= 0.10.9, which does not exist in my distro yet),  but from what I read, something like

var sqlite3 = require('sqlite3').verbose();
var db = new sqlite3.Database(':memory:');

and then using that database might be enough to reproduce the behaviour. I'm not a JS programmer, though ...

**Comment by MarshallOfSound** [comment]
This issue is solvable (and should be solved) on the apps side of things.  The issue is the app in question is packaging their native modules _into_ an ASAR file (normally `app.asar`).  You can't load a native module from an ASAR so Electron tries to help you out by extracting the native module (effectively a shared library) to the temporary directory and load it from there.  In the case where `/tmp` has `noexec` this isn't going to work.

Each app should ensure that native modules aren't packed into the ASAR and are instead stored / shipped in `app.asar.unpacked`.

**Comment by scottnonnenberg-signal** [comment]
@MarshallOfSound It might be good to put that information here: https://www.electronjs.org/docs/tutorial/using-native-node-modules

We had no idea where the `/tmp` behavior was coming from.

**Comment by matacino** [comment]
same problem here:  https://github.com/UltimateHackingKeyboard/agent/issues/1491
It appears while the app tries to access the USB-device or tries to run "modules" which should access the USB-device
