### ISSUE TITLE
Mac App Store Rejection, Symbols: _vDSP_deq22D, _vDSP_vsma

### ISSUE THREAD

**Issue by semireg** [electron/electron#24247]
I just received a MAS rejection for an app using Electron 8.3.0. The app I submitted was a small feature bump - no major changes. Moreover the last review was just a few days ago.

From MAS review:
```
Your app includes a version of an SDK from Electron that violates the App Store Review Guidelines. The version of the Electron SDK you are using in your app attempts to hide the use of private APIs. This is a violation Section 2.5.1 of the App Store Review Guidelines.

Symbols: _vDSP_deq22D, _vDSP_vsma

Guideline 2.5.1: Apps may only use public APIs.
```

**Comment by alex-paterson** [comment]
Always an uphill battle with this stuff. Same thing happened to me after submitting a app using electron 8.0.2.

**Comment by codebytere** [comment]
This is very weird - 
https://developer.apple.com/documentation/accelerate/1450271-vdsp_vsma?language=objc
https://developer.apple.com/documentation/accelerate/1450534-vdsp_deq22d?language=objc

these are both public functions?

**Comment by MarshallOfSound** [comment]
Can one of you brave souls experiencing this issue appeal the rejection with the two links above and something like.  "Both of these APIs are public APIs in the Accelerate framework in Apples documentation.  Can you double check that these APIs are in fact private and this isn't some kind of bug in your private API detection system?"

Ensure you provide the two links that @codebytere gave above, include any response you get in this thread and we can take it from there.

**Comment by maxime-guyot** [comment]
Same problem for me with electron version 8.2.1 :/

**Comment by alex-paterson** [comment]
I've sent an appeal to their app review board with links two those two pieces of documentation - thank you @codebytere. I'll post any replies I receive.

**Comment by alex-paterson** [comment]
I haven't heard back from the app review board but after submitting my app for the third time it has now been accepted.
I included the following app review notes:

```
My app was rejected due to "private API usage". Sounds like this may affect all electron apps. Please see this GitHub issue and reconsider whether these APIs are actually private and whether this app is worth rejecting: https://github.com/electron/electron/issues/24247

Here are links to the supposedly private API's in the Apple's public documentation:

https://developer.apple.com/documentation/accelerate/1450271-vdsp_vsma?language=objc
https://developer.apple.com/documentation/accelerate/1450534-vdsp_deq22d?language=objc
```

**Comment by alicerunsonfedora** [comment]
I just filled out a survey to Apple regarding the App Store and their platforms for development and figured I'd share my thoughts on the private API rejection situation:

> It would be awesome for the App Store team to work more closely with the Electron team to make sure Electron apps work as intended without private API usage. Rejections due to private API usage is a bit weird, but I understand that most of this is typically caused by stuff Google does and not necessarily the Electron team; however, it doesn't seem as efficient for the Electron team to be guessing where there are private APIs and for Apple to check them blindly. I feel that cooperating in analyzing and ensuring that future Electron builds would be much better in the long run.

**Comment by semireg** [comment]
7 days after appeal, the app build went from Rejected, to In Review, to Ready for Sale. 🤷‍♂️ 

Must have been a mistake on Apple’s side.

**Comment by vijayamin83** [comment]
Does this Issue solved now?
