### ISSUE TITLE
powerMonitor does not fire 'suspend" event 

### ISSUE THREAD

**Issue by gupta-shivam** [electron/electron#24244]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.2
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 

### Expected Behavior
electron.remote.powerMonitor should have fired the 'suspend' event and eventually 'The system is going to sleep' should have been printed in the console.

### Actual Behavior
No event is received.

### To Reproduce
Try to put your computer on sleep from the Start menu of windows.
And then check the logs after unlocking the computer after some time.

[Github Gist link](https://gist.github.com/gupta-shivam/d364e186dfc0a2cd177c9078c9a576eb)

**Comment by gupta-shivam** [comment]
I have tried it again after your changes, but this issue has not been fixed for me

**Comment by codebytere** [comment]
@gupta-shivam a version of 9 with the changes has not been released yet.

**Comment by gupta-shivam** [comment]
I tried with a local electron build which has these changes by taking help from @alexeykuzmin
