### ISSUE TITLE
setSize/setBounds not working as expected on Windows & macOS

### ISSUE THREAD

**Issue by slashinfty** [electron/electron#24258]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v9.0.4
* **Operating System:**
  * Windows 10 (1903), macOS 10.15.5, SparkyLinux 5.11 (Debian Buster)
* **Last Known Working Electron version:**
  * Unknown

### Expected Behavior
Use either `setSize` or `setBounds` to resize a window to the dimensions of the background image (explicit dimensions passed).

### Actual Behavior
In Linux, this behavior works as expected. In Windows and macOS, it does not work as expected. When running `getBounds`, it matches what is set with `setBounds`, however, the background image (which has identical dimensions) is cut off.

### To Reproduce
Occurs in my repo [here](https://github.com/slashinfty/nincid). The code is specifically:
```js
const win = require("electron").remote.BrowserWindow.getFocusedWindow();
win.setMinimumSize(skinJson.width, skinJson.height)
win.setBounds({width: skinJson.width, height: skinJson.height})
```
Where `skinJson.width` and `skinJson.height` are the dimensions of the background image.

### Screenshots
[Here is an example](https://clips.twitch.tv/ThankfulNastyDonutAMPTropPunch) of it working correctly in Linux.

[Here is an example](https://clips.twitch.tv/ComfortableImportantSwallowOneHand) of not working correctly in Windows and [an example in macOS](https://clips.twitch.tv/VibrantCredulousGooseDoritosChip).

### Additional Information
This is closest to [#16711](https://github.com/electron/electron/issues/16711), but it was closed for being a duplicate of [#15560](https://github.com/electron/electron/issues/15560), but that's not the case. With regards to the latter, the workaround of `setMinimumSize` works to resize smaller. However, `setSize` and `setBounds` (tested both) work differently in Windows and macOS than it does in Linux. Having `resizeable` be true or false has no impact on it's functionality (however I ended up setting it to true just to allow users to fit the background image, but that's not a desirable outcome).

**Comment by MarshallOfSound** [comment]
`setBounds` sets the bounds of the window, the actual paintable content bounds are _smaller_ than those values.  E.g. On windows / macOS the "bounds" includes the window border, titlebar, etc.

You should look at using `setContentBounds` or other content size APIs to achieve what you are trying to do

**Comment by slashinfty** [comment]
First, it is not very intuitive which method will yield predictable results, based on the documentation.

Second, `setContentSize` worked, but `setContentBounds` did not.
