### ISSUE TITLE
Electron 8: clipboard.writeBuffer is broken

### ISSUE THREAD

**Issue by bpasero** [electron/electron#24253]
### Issue Details

* **Electron Version:**
  * `8.3.3`
* **Operating System:**
  * Windows 10 2004
* **Last Known Working Electron version:**
  * `7.x`

### Expected Behavior
You can write and read from clipboard via `Buffer`.

### Actual Behavior
You can write but not read.

### To Reproduce

```js
setTimeout(() => {
  clipboard.writeBuffer('code/file-list', Buffer.from("Hello World"));
  console.log("did write")
}, 1000);

setTimeout(() => {
  const res = clipboard.readBuffer('code/file-list');
  console.log(res.toString());
}, 2000);
```

The output is empty with Electron 8 but filled with Electron 7.

//cc @deepak1556

**Comment by codebytere** [comment]
Looks windows-specific - not seeing this on macOS
