### ISSUE TITLE
How to access document element of a new window?

### ISSUE THREAD

**Issue by s-a** [electron/electron#2425]
I do the following to load a new window trying to access document elements.

    this.window.loadUrl('file://' + __dirname + '/toaster.html');
    this.window.show();
    this.window.webContents.on('did-finish-load', function() {
    	debugger;
    	var window = this; // HERE!
    	window.document.addEventListener("click", this.window.close);
    	/*document.getElementById("description").innerHtml = "helo";
    	document.getElementById("details").innerHtml = "helo";*/
    	//document.getElementById("title").innerHtml = "helo";
    });	

```did-finish-load``` and ```dom-ready``` events are running in context of the "old" original main window. Is this correct? And how to access new window document?

**Comment by OlsonDev** [comment]
I'm not sure about your specific issue but `innerHtml` isn't a thing; [`innerHTML`](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML) is however.

**Comment by s-a** [comment]
TY I recognized this :smiley:

**Comment by zcbenz** [comment]
Currently there is no API to do that.

**Comment by s-a** [comment]
OK. So far I do not see any connection at this point. So far I work around with simple ```GET``` parameters to send data to new page. 

Not really beautiful but it works.

```this.window.loadUrl('file://' + __dirname + '/toaster.html?foo=bar&title=title&description=description&details=details');```

**Comment by etiktin** [comment]
You could do it with a `preload` script or with `WebContents.executeJavaScript`.

**Comment by s-a** [comment]
@etiktin ty this is nice to know :+1: 

It confused my that ```this``` is the context of a different window as expected :smiley: .

I also figured out that https://github.com/atom/electron/blob/master/docs/api/ipc-main-process.md could be use full.

**Comment by zcbenz** [comment]
To achieve this we have to run all windows in one renderer process, which is against Electron's design, so I have to close this as won't fix.
