### ISSUE TITLE
8.2.1 -> 9.0.5 libgbm.so.1: cannot open shared object file

### ISSUE THREAD

**Issue by ldeveber** [electron/electron#24265]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.5
* **Operating System:**
  * Debian 10 / Jenkins 1.23.2 
* **Last Known Working Electron version:**
  * 8.2.1 

### Expected Behavior

Electron should start.

### Actual Behavior

It does not start.

```
yarn run v1.22.0

$ eslint ./electron && electron ./electron

/home/jenkins/agent/workspace/PR-1688/node_modules/electron/dist/electron: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory

error Command failed with exit code 127.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Sending interrupt signal to process

Killing processes

kill finished with exit code 0
```

We installed the `libgbm-dev` package as part of the jenkins setup of the container, but still get this error.

**Comment by ldeveber** [comment]
This somehow resolved itself (I have no idea how)

**Comment by max-programming** [comment]
@ldeveber I get this error a lot
