### ISSUE TITLE
Electron net hangs when making a request after many thousands of requests

### ISSUE THREAD

**Issue by xssc** [electron/electron#24276]
### Preflight Checklist

* [ x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.5
* **Operating System:**
  * macOS 15.1.2
* **Last Known Working Electron version:**
  * 6.1.12

### Expected Behavior
Should be able to make requests over and over via electron net no issues

### Actual Behavior
After making many thousands of requests, electron net simply fails to give any response through error, close, or end on a request, this also results in 100% cpu usage over time

### To Reproduce
Make requests in a loop to any website, I will try to get an example repo up later, as this is an issue at scale I understand it can be difficult to test, my request constructor params are simply
```
electron.net.request({
        method: method,
        url: url,
        cache: false
      });
```

### Additional Information

Everything works as normal on electron 6 and earlier, electron 7.0.0-7.1.x i was having issues using net to send requests at all, and in 7.2.0-9.0.5 requests at scale lag significantly and eventually completely stall out with high cpu usage over time, this issue seems to be present on linux as well, not sure about windows but I can only assume

**Comment by walmat** [comment]
Could this be a underlying TCP issue? I'm wondering if TCP sockets aren't being properly closed/reused when a session either requests to be freed up or reused. I'll do some more digging but it sounds to me like it's a connection issue to begin with. @nornagon

**Comment by nornagon** [comment]
Unfortunately without any steps to reproduce this issue we can't debug further. Please provide a small example that reproduces the issue you're seeing, preferable using [Electron Fiddle](https://github.com/electron/fiddle).

Thanks!

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
