### ISSUE TITLE
Typescript bindings for 'File' prevent other packages from building.

### ISSUE THREAD

**Issue by burtonator** [electron/electron#24270]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
9.0.5
* **Operating System:**
MacOS but n/a
* **Last Known Working Electron version:**
None I think

### Expected Behavior

Typescript bindings for 'File' are wrong.

Electron adds a 'path' of type string to File, without a namespace, so you've augmented the 'dom' File with a type.

This is breaking other packages now including react-dropzone.  

It implements File but since you've added a property it doesn't know about it breaks.

A solution is to move File into a namespace so that you're not augmenting the default File.

### Actual Behavior

Other libraries shouldn't break just because you're using Electron

### To Reproduce
npm install react-dropzone in an electron project and it won't build.

**Comment by MarshallOfSound** [comment]
> Electron adds a 'path' of type string to File, without a namespace, so you've augmented the 'dom' File with a type.

This is expected and intended.  Electron actually **does** augment the `File` type the DOM exposes
