### ISSUE TITLE
NewWindowWebContentsEvent type missing sender  [typescript]

### ISSUE THREAD

**Issue by sgil-carecloud** [electron/electron#24287]
* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version: 
   v10.0.0-beta.4
* **Operating System: 
  MacOs10.15.5 
* **Last Known Working Electron version:**
 N/A
### Expected Behavior
When using typescript and trying to type out a BrowsersWindow.webContents.on('new-window') event Handler, the event param, which is of type NewWindowWebContentsEvent, contains a sender variable.

### Actual Behavior
error is displayed saying Property 'sender' does not exist on type 'NewWindowWebContentsEvent'.

### To Reproduce
in a .ts  file

const mainWindow = new BrowserWindow({
  width: 800,
  height: 600,
  webPreferences: {
    nativeWindowOpen: true
  }
})
mainWindow.webContents.on('new-window', (
  event: Electron.NewWindowWebContentsEvent,
  url: string,
  _frameName: string,
  _disposition: 'default' | 'foreground-tab' | 'background-tab' | 'new-window' | 'save-to-disk' | 'other',
  _options: Electron.BrowserWindowConstructorOptions,
  _additionalFeatures: string[],
  _referrer: Electron.Referrer,
  _postBody: Electron.PostBody
) => {
  console.log(event.sender.session)
})

you should receive an error saying Property 'sender' does not exist on type 'NewWindowWebContentsEvent'.

### Screenshots
![Screen Shot 2020-06-24 at 1 34 47 PM](https://user-images.githubusercontent.com/7902883/85604658-7d42e980-b61f-11ea-994e-da5bd9aebcd2.png)

### Additional Information
if someone could point me the right way i can make the change myself so i can start contributing to this project

**Comment by sgil-carecloud** [comment]
also looked at NewWindowEvent but no sender was found as well

**Comment by codebytere** [comment]
@sgil-carecloud hey! We generate types from docs, so you want to add that property here: https://github.com/electron/electron/blob/27d629abb983fca5b0943ffba9564d9d7e31b8a5/docs/api/web-contents.md#L137
