### ISSUE TITLE
Ctrl - causes unrecoverable zoom out in electron

### ISSUE THREAD

**Issue by sgd2z** [electron/electron#24289]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.0, 9.0.4
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 

### Expected Behavior
- Ctrl - should not zoom out the window (preferred) OR
- Ctrl - (using the minus that is not on the numpad) zoom out should be reversible with Ctrl + to zoom in

### Actual Behavior
When you hit `Ctrl` + `-` (using the - on the keyboard, not the one on the numpad), electron causes the zoom factor to change.

### To Reproduce
Run electron.exe
Click `Ctrl` + `-` (use the minus on the main keyboard, not the numpad)
The window will zoom out and you cannot zoom back in with `Ctrl` + `+`

### Screenshots
Default:
![image](https://user-images.githubusercontent.com/18012933/85618072-3ad4d900-b62e-11ea-9e4c-dc9d75efe752.png)

Clicked `Ctrl` + `-` a few times:
![image](https://user-images.githubusercontent.com/18012933/85618222-71aaef00-b62e-11ea-896d-f76606fe6fe7.png)

### Additional Information
After some debugging in the browser, I discovered that `Ctrl` + `-` on the keyboard actually seems to trigger a `Ctrl` + `Shift` + `-`. This might be the problem.

Potentially Related Issues:
https://github.com/electron/electron/issues/15496

**Comment by codebytere** [comment]
Yep - you'll need to do `Ctrl` + `Shift` + `+` to zoom back in i believe. Closing this as the underlying issue is the one you're referencing.

**Comment by sgd2z** [comment]
@codebytere The other issue only talks about MacOS and shortcuts in the menu. We did not have this problem in 7.1.14 - it is possible that was because we used setLayoutZoomLevelLimits (which is unavailable in 9.x) but I'm not certain. This is in Windows and only affects us on electron 9. Currently we are working around this by polling for Zoom factor changes, which is a terrible hack.
