### ISSUE TITLE
Invalid Metadata Document when calling a OData service in SAP

### ISSUE THREAD

**Issue by prateekjsingh** [electron/electron#24288]
### Issue Details

I trying to create an electron app where i am supposed to fetch data from SAP OData service.

The Application fetched the metadata correctly but the response in the Application is "Since your browser does not support JavaSxript, You must press the Continue button once to " .

I can see the error message as "Invalid Metadata Document" in the console.

When I use the OData service link in the Chrome browser, the metadata is loaded correctly.

* **Electron Version:**
  * v5.0.13
* **Operating System:**
  * macOS Catalina 10.15.5 (19F101)
* **Last Known Working Electron version:**
  * None

### Expected Behavior
The Electron browser should be able to decode the Javascript response.

### Actual Behavior
An error is returned.

### Screenshots
![image](https://user-images.githubusercontent.com/67387382/85609364-d7857f80-b60a-11ea-8716-89667ac54477.png)
![image](https://user-images.githubusercontent.com/67387382/85609417-e5d39b80-b60a-11ea-85c8-0f9ceac1603d.png)

### Additional Information
I have already tried out following solution for this issue:

1. Set NodeIntegration to true and execute  script in index.html to delete windows variable for require, module, exports.
2. Set NodeIntegration for Browser to false.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions about app-specific implementation details since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by vtebano13** [comment]
I have the same issue from which I can't seem to find a solution.  The links you provided bring me right back to the electron support.  The issue does not arise when I just use chrome only when I use debugging on electron.

Can you give some more assistance or a resolution?

**Comment by prateekjsingh** [comment]
Hello,
Our toke wasn't getting stored by the SSO call. hence the subsequent call to fetch the metadata resulted in error.
ThanksPrateek
    On Wednesday, 17 February, 2021, 05:40:56 am GMT-8, vtebano13 <notifications@github.com> wrote:  
 
 


I have the same issue from which I can't seem to find a solution. The links you provided bring me right back to the electron support. The issue does not arise when I just use chrome only when I use debugging on electron.

Can you give some more assistance or a resolution?
