### ISSUE TITLE
Taskbar icon does not update based on asar file loaded

### ISSUE THREAD

**Issue by VaishakVk** [electron/electron#24296]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.5
* **Operating System:**
  Windows 10 (1803)
* **Last Known Working Electron version:**

### Expected Behavior
I have multiple asar files and I have built an Electron app where each of the asar is loaded based on condition. Apps are loading properly but the icons are grouped as one in the taskbar.

### Actual Behavior
Based on the asar file loaded, the corresponding icon should be displayed on the taskbar. If two apps are opened with different icons, then there should be two different icons on the taskbar.

### To Reproduce
- Create Multiple asar files
- Create an Electron main.ts file that loads these asar files and build the app.
- Create shortcut for these apps and add a command line argument so that different asar files can be loaded
- Try opening the shortcuts. The taskbar icon will be the icon of the first app even if the second app has a different icon.

**Comment by MarshallOfSound** [comment]
Windows groups icons in the taskbar based on the executable that is running, if you want multiple distinct icons you need to have multiple distinct executables.  This is an OS limitation and not something Electron can work around
