### ISSUE TITLE
fs.readdir(sync) inside asar does not work with withFileTypes after "fix"

### ISSUE THREAD

**Issue by xssc** [electron/electron#24292]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.5
* **Operating System:**
  * macOS 10.15.2

### Expected Behavior
fs.readdirsync should return an array of dirents

### Actual Behavior
always returns an empty array in asar after https://github.com/electron/electron/pull/24062

### To Reproduce
call fs.readdir/sync on any dir inside an asar

**Comment by codebytere** [comment]
Are you sure you're calling it correctly? I ran the following: https://gist.github.com/a19c56fece174de46486f4d4a2934dfb

and saw: 
<img width="369" alt="Screen Shot 2020-06-24 at 9 21 19 PM" src="https://user-images.githubusercontent.com/2036040/85652845-a9cb2580-b660-11ea-948e-c6bf9e5de97b.png">

With the following test fixture: 
[test.asar.zip](https://github.com/electron/electron/files/4829070/test.asar.zip)

**Comment by xssc** [comment]
Strange, it works fine with the asars you sent, however it does not work with any asar I make myself, I tried asar versions 2 & 3  and both simply log empty array when adding withFileTypes, where as without withFileTypes, it logs the correct array of names in the dir

**Comment by codebytere** [comment]
@xssc would you be willing to send an example of a fixture that fails for you? I of course want to make it work for you/others but it's hard if i can't repro it over here 😅

**Comment by codebytere** [comment]
Closing this out as it appears to work - i'll reopen should more info come to light.

**Comment by Kjplay** [comment]
@codebytere I have the same problem -  with archive created by `electron-forge` (I tried re-packing it with `asar3` too)
things like withe-space, underscores etc. seem to not affect the final result
I modified your main.js file (from gist in this issue):
> Are you sure you're calling it correctly? I ran the following: https://gist.github.com/a19c56fece174de46486f4d4a2934dfb
```js
  console.log("KJ's test (test_app.asar/data/html_assets)")
  const p = path.join(__dirname, "test_app.asar", "data/html_assets");
  const dirs = fs.readdirSync(p, { withFileTypes: true });
  const entries = fs.readdirSync(p);
  console.log("With file types:", dirs);
  console.log("Without file types:", entries);
  console.log("codebytere's test (a.asar/dir1)")
  const p1 = path.join(__dirname, 'test.asar', 'a.asar', 'dir1');
  const dirs1 = fs.readdirSync(p1, { withFileTypes: true });
  console.log("With file types:", dirs1)
```
 and received the following:
```
KJ's test (test_app.asar/data/html_assets)
With file types: []
Without file types: [
  'block_data',
  'dialog-scripts',
  'dialogs',
  'fatal_error.html',
  'html_panels',
  'icons',
  'logo-canvas.mjs',
  'main'
]
codebytere's test (a.asar/dir1)
With file types: [
  Dirent { name: 'file1', [Symbol(type)]: 1 },
  Dirent { name: 'file2', [Symbol(type)]: 1 },
  Dirent { name: 'file3', [Symbol(type)]: 1 },
  Dirent { name: 'link1', [Symbol(type)]: 3 },
  Dirent { name: 'link2', [Symbol(type)]: 3 }
]
```
Tested archive (test_app.asar - mine, zipped) 
[test_app.zip](https://github.com/electron/electron/files/4944839/test_app.zip)

* Electron version: **9.1.0**
* OS: **Windows 10 2004**
Thanks in advance!

**Comment by SAKryukov** [comment]
I confirm it: still can see this problem for ***Electron 37.4.0***, ***node.js 22.18.0***, Windows.
When the application is packaged without `--asar`, everything works correctly.

The behaviour is exactly the same as without `{ withFileTypes: true }` — the entries are strings, the base file names.
