### ISSUE TITLE
Include requesting origin in onBeforeRequest details

### ISSUE THREAD

**Issue by mjbvz** [electron/electron#24303]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
We are using `onBeforeRequest` to rewrite requests to `localhost` that are made inside iframes. The rewriting depends on which iframe made the request.

At the moment, there is no way I have found to identify which iframe made the request that `onBeforeRequest` handles

### Proposed Solution
In the details object passed to `onBeforeRequest `, include the origin of the requester. This would let us identify which iframe made a given request 

### Alternatives Considered
If you use webviews, the details in `onBeforeRequest` includes a `webContentsId`. If every webview has its own `webContentsId`, we can map from request -> webview.  

However I have not found a way to do the same for normal iframes

/cc @deepak1556

**Comment by samuelmaddock** [comment]
This should be solved by #27078

**Comment by deepak1556** [comment]
Closing per above comment.
