### ISSUE TITLE
Electron on Apple Silicon / macOS Big sur?

### ISSUE THREAD

**Issue by christianscheuer** [electron/electron#24306]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
With Apple's announcement at WWDC this week, it's now clear that they will start shipping Macs running on their own, ARM-based "Apple Silicon" chips, to consumers as soon as late 2020.
AFAIK, Electron currently does not have an option to build for a Mac ARM-target (since this is a wholly new architecture), so any app using Electron as their platform would be limited to working on top of the Rosetta 2 x86->ARM translation.

### Proposed Solution
Electron should eventually be able to natively target MacOS "Universal Apps" (the new type of fat binary that can include both x86 and Apple Silicon/ARM architectures).

### Alternatives Considered
A temporary workaround might be to use the Rosetta 2 translation, but it's unclear at this point how functional this will be for various apps.

**Comment by nornagon** [comment]
Check the [platforms state of the union](https://developer.apple.com/videos/play/wwdc2020/102/), around 20:15.

![image (3)](https://user-images.githubusercontent.com/172800/85884848-20b70a00-b798-11ea-9f5c-73088fb5f486.png)

Apple's apparently been working on getting Electron and Chromium to work on the new architecture, so hopefully we'll see the results of that sooner rather than later.

**Comment by MarshallOfSound** [comment]
Closing as per #24319

**Comment by christianscheuer** [comment]
Thank you @MarshallOfSound  :) Great to see that Apple have already done some work on this.

**Comment by jdjingdian** [comment]
Is there anyways that we can at least run the app, with some arguments?

**Comment by gcadmes** [comment]
According to the WWDC 2020 SOTUA, Apple said they're working on helping the Open Source community and will have patches in the coming days. Vague, no?

In this screenshot, here are the 5 current open source communities that are already supported, the others greyed out are not yet supported. 
So my question is, has anyone actually ordered the Quick Start Kit from Apple and tested Electron? How can you close this if it hasn't been fully tested.
<img width="1034" alt="wwdc-2020-sotu" src="https://user-images.githubusercontent.com/7306719/94748704-e4bfb200-034f-11eb-9344-ef0dd1376dc5.png">

**Comment by ni-binada** [comment]
Has there been any progress on adapting Electron to run via Rosetta 2? It seems that Chromium has recently enabled itself to run under Rosetta binary translation: https://chromium-review.googlesource.com/c/chromium/src/+/2361202
