### ISSUE TITLE
Electron 9+: Native form controls have gone

### ISSUE THREAD

**Issue by alexgreenland** [electron/electron#24317]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

Native form controls have gone in Electron 9 as Chromium as of [v83](https://blog.chromium.org/2020/03/updates-to-form-controls-and-focus.html) uses platform-independent form controls. I'm not even sure about this change for the Web, but it affects apps that use web technologies. This is an opinionated change and it doesn't work for apps that want to look native, important for apps running on Electron. 

There is also no opt-in to the new style. While some controls, like buttons and textboxes, are commonly restyled by developers; others, like radio buttons and checkboxes, are typically left native. It would be simpler to CSS style buttons and textboxes; radio buttons and checkboxes are harder, and harder to get to platform native.

My current workaround is to apply the command line switch:
`app.commandLine.appendSwitch('disable-features', 'FormControlsRefresh')`

* **Electron Version:**
  * 9.0.5
* **Operating System:**
  * macOS 10.15.5
* **Last Known Working Electron version:**
  * 8.3.4

A side effect of the change in Chromium v83 is shown in https://github.com/electron/electron/issues/23768, where Mac accent colours on form controls are not supported.

### Expected Behavior

OS-native form controls are expected — see screenshot 1.

### Actual Behavior

Platform-independent form controls are displayed — see screenshot 2.

There's a double whammy here. I think quite a few who see these controls will immediately know it's a webpage so it looks off, or won't necessarily recognise the control if it's not what they're used to on their OS.

### To Reproduce

Electron Fiddle:
https://gist.github.com/816403716f075ceaa44a67a95a03d4dc

#### Screenshot 1 (as expected): Electron 8.3.4 (Chromium 80), macOS

![image](https://user-images.githubusercontent.com/2202625/85884862-3568c180-b7db-11ea-9592-8247021f254b.png)

#### Screenshot 2 (actual): Electron 9.0.5 (Chromium 83), macOS

![image](https://user-images.githubusercontent.com/2202625/85884903-47e2fb00-b7db-11ea-99bf-b5311e6be01a.png)

Thanks

**Comment by nornagon** [comment]
We can't change this, we inherit it from Chromium.

**Comment by alexgreenland** [comment]
I'd appreciate more detail.

I think we should go further to provide a great native experience, so the UI matches the OS. A desktop app isn't the Web, it should be native.

If I managed to utilise native form controls with the one-line Chromium flag, surely this can be made in Electron as a default, or offered as a higher-level Electron option?

**Comment by nornagon** [comment]
Chromium's controls have never been native. If you prefer the old look, you're welcome to use that flag for as long as it's supported in Chromium. Electron won't commit to supporting a Chromium feature that Chromium doesn't support.

**Comment by alexgreenland** [comment]
I understand the potential flakiness of flags, but IMO it's about doing what we can to help developers, so this could be a holdover until a more solid approach is worked out (flags tend to last quite a while). I'm sure I'm not the only one who wants native-looking platform-specific controls, getting them out of the box.

But, these controls were previously delegated to the OS, or at least did a great job of making them look native — they're identical. As shown here in Safari, the radio buttons and checkboxes in Electron 8 are the same as the macOS platform. Even if they're not coded natively, it's about them looking native, that's my point.

![image](https://user-images.githubusercontent.com/2202625/85891774-a6ae7180-b7e7-11ea-927f-938ab15fec20.png)
