### ISSUE TITLE
electron openssl 1.1.0 should be upgrade？

### ISSUE THREAD

**Issue by redabc** [electron/electron#24337]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version: 6.1.10
  * 
* **Operating System: windows 10
  * 
* **Last Known Working Electron version:**
  * 

### Expected Behavior

electron depends on openssl， but the Version too old， the version is v1.1.0；
could you please upgrade the version of openssl！

**Comment by codebytere** [comment]
@redabc we actually do not bundle OpenSSL at all. Electron uses BoringSSL under the hood, as a result of constraints imposed on us by Chromium. We therefore use whatever the latest version of BoringSSL is that corresponds to our bundled version of Chromium.
