### ISSUE TITLE
Electron and simulation accuracy

### ISSUE THREAD

**Issue by Roger-Hlls** [electron/electron#24331]
Hi all!

   I'm very pleased with the software, it nearly fulfills all my expectations! However, the accuracy-of-results, it's an issue for me. I'd like to help making electron more accurate by furnishing various real-life results obtained by experimenting with a number of circuits I built by using a circuit implementing device, oscillator, frequency generator, and multimeters. Those lab experiments are being implemented by students through a-year (two semesters) course on Electronics 101. What do you say?

   My apology should I've missed the proper issue,

Roger-Hlls

**Comment by fabiospampinato** [comment]
I think you might be talking about another kind of "electron" here 🤔 Electron is basically a browser, not a physics simulator.

**Comment by Roger-Hlls** [comment]
Well, Fabio,

 

                I’m talking about the MS-Windows version... Scusami, ma sei Italiano? Mia madre era Italiana ed io son nato a Cagliari! Tante belle cose,

 

Roger-Hlls
