### ISSUE TITLE
Cannot disable built-in PDF viewer in Electron 9

### ISSUE THREAD

**Issue by mmmkkaaayy** [electron/electron#24334]
### Issue Details

* **Electron Version:**
  * 9.0.5
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 8

In version 8, I couldn't get the built-in PDF viewer to work at all. Some sources on Google suggested trying `plugins: true` for `webPreferences`, but it didn't work. In version 9, I can't figure out how to disable the built-in PDF viewer. 

My objective is to intercept .pdf downloads and display them using a custom build of pdfjs instead. In v8, I could do that by checking the `will-download` event for MimeType `application/pdf`. In v9, this event is not triggering.

### Expected Behavior
Loading a URL to a `.pdf` file should not use the built-in PDF viewer.

### Actual Behavior
Loading a URL to a `.pdf` file uses the built-in PDF viewer.

### To Reproduce
```
import {app, BrowserWindow} from "electron";

app.whenReady().then(() => {
    let rootAppWindow = new BrowserWindow({
        webPreferences: {
            plugins: false
        },
    });

    rootAppWindow.loadURL('https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf');
});
```

**Comment by MarshallOfSound** [comment]
You can intercept pdf load requests using `will-navigate` or `did-start-loading`

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

**Comment by PalmerAL** [comment]
@MarshallOfSound I don't think `will-navigate` or `did-start-loading` are a complete replacement for the `will-download` event. `will-download` allows checking files based on the mime type, which is necessary because not all PDF files have URLs ending in ".pdf". The navigation events only provide a URL, so it isn't possible to detect every file.

**Comment by mmmkkaaayy** [comment]
I've found that trying to make this work with navigate/loading events is quite painful. I also have to listen on `did-redirect-navigation` event (eg when opening PDFs in arxiv). To further complicate matters, I need to parse the URL to determine the extension of the file being requested. This isn't trivial; see how many different answers there are in this [stackoverflow post](https://stackoverflow.com/questions/6997262/how-to-pull-url-file-extension-out-of-url-string-using-javascript).

**Comment by PalmerAL** [comment]
I ended up writing a workaround for this using `onHeadersReceived`: minbrowser/min@42fefc3eb534d819197643bead4f269bd4f8b384

It's more complicated than checking the URL (and much more complicated than the old `will-download` event), but it should be more reliable.
