### ISSUE TITLE
GSCheck--safe compilation options

### ISSUE THREAD

**Issue by HWliwenyong** [electron/electron#24347]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.1.12
* **Operating System:**
  *  Windows 10 (1803)
* **Last Known Working Electron version:**
  * unknown

### Expected Behavior

Binary file meet GSCheck safe compilation options
### Actual Behavior

Binary file(d3dcompiler_47.dll、elevate.exe、Uninstall exe) does not meet GSCheck safe compilation options
### Screenshots

![image](https://user-images.githubusercontent.com/42129564/86002749-5cc1c780-ba43-11ea-9d6a-3ace22890327.png)

**Comment by nornagon** [comment]
Electron 6 is [not a currently supported version](https://www.electronjs.org/docs/tutorial/support#currently-supported-versions).
