### ISSUE TITLE
Electron stopped working randomly.

### ISSUE THREAD

**Issue by uAliFurkanY** [electron/electron#24340]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * Tested on 9.0.5, 10.0.0-beta-4, nightly-4.0.0 in order
* **Operating System:**
  * Kubuntu 20.04 LTS 64-bit
* **Last Known Working Electron version:**
  * Every version started failing, but 9.0.5
* **Node Version:**
  * v12.18.1

### Expected Behavior
Electron window should show up

### Actual Behavior
Fails to open window, KSysGuard shows all the electron processes running, including GPU process.

### To Reproduce
I have 0 idea. It started failing randomly. Even doesn't work with `win.loadFile` commented out. This is an electron bug.

The git repository won't probably reproduce the bug as it worked with the exact same code and version before.

```sh
$ git clone https://github.com/uAliFurkanY/notes.git -b develop
$ npm install
$ npx electron .
OR
$ node . # detaches electron process
```

### Screenshots
Nothing shows up

### Additional Information
I created an exception in my application. It exited with code `1` and showed the "Reload The Page To Show DevTools" screen and never worked again.

Also some software updated in the background after the crash happened.

I did the same before and it never did this.

##### ~~If there is a temporary fix, I'll be happy to learn it.~~ See edit 3.

Edit: grammar a -> an

Edit 2: It actually worked after the crash once. I ran it twice in different terminals and it opened the window. Worked only once.

Edit 3: Temporary fix: rename your main folder.

**Comment by uAliFurkanY** [comment]
You wouldn't believe this. I renamed my main folder and it worked...

Renamed it back and crashed again.

And that confirms that it is either a nodejs bug (probably not) or an electron bug (most likely)

**Comment by MarshallOfSound** [comment]
> I renamed my main folder and it worked...

What folder are you referring to here? What path was it originally and what path did you rename it to?

**Comment by uAliFurkanY** [comment]
The main project folder.
I renamed it from notes to note and it worked

**Comment by codebytere** [comment]
Closing as this seems to have been solved.
