### ISSUE TITLE
Webcontents 'login' even callback does not have expected outcome.

### ISSUE THREAD

**Issue by mattlm0831** [electron/electron#24349]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
* **Operating System:**
  * 
* **Last Known Working Electron version:**
  * 

### Expected Behavior

While setting a browser window proxy with a user:pass authenticated proxy, the callback should authenticate the proxy with provided proxy authentication parameters.

### Actual Behavior

When the 'login' event is called, all the code executes, the callback is called, yet the browser window is blank. What seems to be happening is the auth fails, but no reason is given through the callback. I have gone through and tested to make sure auth is correct, and the authentication is parsed and input correctly.

### To Reproduce

`win.webContents.session.setProxy({
                proxyRules:  `${proxy.ip}:${proxy.port}`
            })
            if ( proxy.auth ){
                win.webContents.on(
                    'login',
                    ( event, authenticationResponseDetails, authInfo, callback ) => {
                        if (authInfo.isProxy) {
                            event.preventDefault()
                            callback( proxy.user, proxy.pass )
                        }
                    }
                )
            }`
Important notes: this browser window is being spawned from the renderer process using remote.BrowserWindow. the rest of the code is proprietary but simply includes opening of a new BrowserWindow and attempting to load a url. This works correctly whenever a proxy is not present.

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks for understanding and meeting us half way 😀

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
