### ISSUE TITLE
goBack() and goForward() doesn't update window title

### ISSUE THREAD

**Issue by ewu02** [electron/electron#24357]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.3.1
* **Operating System:**
  * macOS 10.15.5
* **Last Known Working Electron version:**
  * n/a

### Expected Behavior

Going forward or back a page using webContents.goBack() or webContents.goForward() should set window title to DOM header title element's value by default.

### Actual Behavior
window title is not updated

### To Reproduce
invoke goBack(), then compare the window title to DOM's header title element. They do not match.

**Comment by codebytere** [comment]
I ran the following:

```
const { app, BrowserWindow, Menu } = require('electron')

app.on('ready', () => {
  const mainWindow = new BrowserWindow({ height: 600, width: 600 })
  mainWindow.loadURL('https://wikipedia.com')

  function goForward() {
    if(mainWindow.webContents.canGoForward())
      mainWindow.webContents.goForward();
  }

  function goBack() {
    if(mainWindow.webContents.canGoBack())
      mainWindow.webContents.goBack();
  }

  const template = [
    {
      label: 'Hello From Electron!',
      submenu: [
        {
          label: 'Back',
          accelerator: 'CmdOrCtrl+[',
          click () { goBack(); }
        },
        {
          label: 'Forward',
          accelerator: 'CmdOrCtrl+]',
          click () { goForward(); }
        }
      ]
    }
  ]

  const menu = Menu.buildFromTemplate(template)
  Menu.setApplicationMenu(menu)
})
```

And saw no issues - the window header updated correctly. Are you sure you were correctly invoking the APIs?

**Comment by ewu02** [comment]
Thanks for looking into this. Perhaps it was something else in the app that was causing it. I'll investigate it more and will close the issue in the meantime.
