### ISSUE TITLE
webview.print  error(An object could not be cloned)

### ISSUE THREAD

**Issue by haliuhei** [electron/electron#24364]
System: windows10 1909
Electron version: 9.0.0

[https://www.electronjs.org/docs/api/web-contents#contentsprintoptions-callback](https://www.electronjs.org/docs/api/web-contents#contentsprintoptions-callback)

```
const options = { silent: true, deviceName: 'My-Printer' }
win.webContents.print(options, (success, errorType) => {
  if (!success) console.log(errorType)
})
```
error: Uncaught (in promise) Error: **An object could not be cloned.**

I want to get  **callback**，but something went wrong

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 7 days if the above is not addressed.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by jiyarong** [comment]
same error for me, is there any solution?

**Comment by acecoder1997** [comment]
it also the same for me too!!!! i'm follow the official document like this
```
                const webview = document.querySelector("webview")
                webview.addEventListener('ipc-message', (event) => {
                    if (event.channel === 'webview-print-do') {
                        let options = {
                            silent: true,
                            copies: 2,
                            printBackground: true,
                            deviceName: 'MyPrinterName'
                        }
                        webview.print(options, (success) => {
                            console.log('callback', success);
                        })
                    }
                })
```
![image](https://user-images.githubusercontent.com/60084325/90601731-37735d80-e22b-11ea-850e-222001188abd.png)
if i change the options object params into an Array like this  [options ].
it work but the slient printing and callback is still not work............
is anybody konw the reason why???

**Comment by haliuhei** [comment]
> it also the same for me too!!!! i'm follow the official document like this
> 
> ```
>                 const webview = document.querySelector("webview")
>                 webview.addEventListener('ipc-message', (event) => {
>                     if (event.channel === 'webview-print-do') {
>                         let options = {
>                             silent: true,
>                             copies: 2,
>                             printBackground: true,
>                             deviceName: 'MyPrinterName'
>                         }
>                         webview.print(options, (success) => {
>                             console.log('callback', success);
>                         })
>                     }
>                 })
> ```
> 
> ![image](https://user-images.githubusercontent.com/60084325/90601731-37735d80-e22b-11ea-850e-222001188abd.png)
> if i change the options object params into an Array like this [options ].
> it work but the slient printing and callback is still not work............
> is anybody konw the reason why???

maybe webview  no callback

**Comment by RoamIn** [comment]
me too...

**Comment by RoamIn** [comment]
It works without callback!
