### ISSUE TITLE
localStorage not preserved

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#24365]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.5
* **Operating System:**
  * macOS 10.14
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior

localStorage should be preserved across restarts.

### Actual Behavior

It isn't, it's only preserved if the window is reopened while keeping the app as a whole active.

### To Reproduce

Fiddle gist: https://gist.github.com/e1a82bad78d00f40f4b9075005fc1da7

**Comment by codebytere** [comment]
@fabiospampinato are you experiencing this in your app or just fiddle during testing? Fiddle deletes used data intentionally, so that is working as expected.

**Comment by fabiospampinato** [comment]
@codebytere I'm experiencing this with the app too. The only difference that I can see is that on production builds I'm loading a file via the "file://" scheme, which I had to register a custom handler for after upgrading to v9 because that broke it (https://github.com/electron/electron/issues/23757#issuecomment-640146333):

```
    protocol.registerFileProtocol ( 'file', ( request, callback ) => {

      const filePath = path.normalize ( decodeURI ( request.url.slice ( 7 ) ) );

      callback ({ path: filePath });

    });
```

While in development builds I'm querying a regular `http://` endpoint. I'm not sure if that helps 🤔 

Also I've tried to build the gist with the Fiddle app but the built app just exits immediately, no errors, no error codes, there's probably something broken with that too.

**Comment by bouncyball02** [comment]
@fabiospampinato is this with a packaged app or `npm start`? I don't think the latter preserves data, but I've packaged apps with localStorage on my PC and they work fine.

**Comment by fabiospampinato** [comment]
@bouncyball02 packaged app.

**Comment by bouncyball02** [comment]
In your Fiddle script, try using `! localStorage.foo` and see if that makes any difference?
`localStorage.getItem` returns the value of the item, not a true/false statement.

**Comment by fabiospampinato** [comment]
@bouncyball02 that's useless considering how the fiddle seems to reset localstorage on purpose anyway and my code for checking `foo`'s existence is correct.

**Comment by daltonmenezes** [comment]
Same here using Electron v10.1.1

**Comment by daltonmenezes** [comment]
It seems to work only if you add:

```
webPreferences: {
  partition: 'persist: something',
},
```

**Comment by fabiospampinato** [comment]
No stale.

**Comment by fabiospampinato** [comment]
Still interested in this

**Comment by fabiospampinato** [comment]
Still interested

**Comment by MarshallOfSound** [comment]
Testing on Electron 20,21,22,23,24 this does not appear to be an issue anymore (Assuming you disable the fiddle feature that resets app data on relaunch).

E.g. in fiddle on E24
![image](https://user-images.githubusercontent.com/6634592/231047619-9f366dfd-f8d1-47c3-ae0f-1499e0cdfa43.png)

If you can still reproduce this issue on a supported version of Electron in Fiddle with app data removal disabled please comment below with an up-to-date repro gist 👍
