### ISSUE TITLE
Calling IsWindows10TabletMode crashes Electron

### ISSUE THREAD

**Issue by zarubond** [electron/electron#24366]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
7.3.1
* **Operating System:**
  Windows 10
* **Last Known Working Electron version:**
?

### Expected Behavior
App should not crash

### Actual Behavior
App crashed on startup in https://chromium.googlesource.com/chromium/src/+/master/base/win/win_util.cc on line 221
with EXCEPTION_IN_PAGE_ERROR_EXEC / STATUS_DEVICE_DATA_ERROR
### Additional Information
**Stack trace:**
    combase.pdb
    0x76bde9bc + 1894844
    combase.pdb
    0x76abe55f + 714079
    twinapi.appcore.pdb
    0x6e5b4d82 + 478594
    combase.pdb
    0x76ae944a + 889930
    combase.pdb
    0x76ae71d1 + 881105
    twinapi.appcore.pdb
    0x6e5a4580 + 411008
    twinapi.appcore.pdb
    0x6e5a0b4d + 396109
    twinapi.appcore.pdb
    0x6e5a0c27 + 396327
    twinapi.appcore.pdb
    0x6e5b8400 + 492544
    twinapi.appcore.pdb
    0x6e6a8c84 + 1477764
    electron.exe.pdb
    base::win::IsWindows10TabletMode(HWND__ *) win_util.cc:221
    electron.exe.pdb
    ui::MaterialDesignController::Initialize() material_design_controller.cc:78
    electron.exe.pdb
    electron::AtomBrowserMainParts::ToolkitInitialized() atom_browser_main_parts.cc:410
    electron.exe.pdb
    content::BrowserMainLoop::InitializeToolkit() browser_main_loop.cc:1497
    electron.exe.pdb
    content::BrowserMainRunnerImpl::Initialize(content::MainFunctionParams const &) browser_main_runner_impl.cc:112
    electron.exe.pdb
    content::BrowserMain(content::MainFunctionParams const &) browser_main.cc:43
    electron.exe.pdb
    content::RunBrowserProcessMain(content::MainFunctionParams const &,content::ContentMainDelegate *) content_main_runner_impl.cc:556
    electron.exe.pdb
    content::ContentMainRunnerImpl::RunServiceManager(content::MainFunctionParams &,bool) content_main_runner_impl.cc:963
    electron.exe.pdb
    content::ContentMainRunnerImpl::Run(bool) content_main_runner_impl.cc:871
    electron.exe.pdb
    content::ContentServiceManagerMainDelegate::RunEmbedderProcess() content_service_manager_main_delegate.cc:52
    electron.exe.pdb
    service_manager::Main(service_manager::MainParams const &) main.cc:423
    electron.exe.pdb
    content::ContentMain(content::ContentMainParams const &) content_main.cc:19
    electron.exe.pdb
    wWinMain atom_main.cc:177
    electron.exe.pdb
    static int __scrt_common_main_seh() exe_common.inl:288
    wkernel32.pdb
    0x75346359 + 90969
    wntdll.pdb
    0x77947b74 + 424820
    wntdll.pdb
    0x77947b44 + 424772

**Comment by codebytere** [comment]
@zarubond this API didn't exist in v7? It was added here: https://github.com/electron/electron/pull/25209/files and is only in 12. Can you please clarify version?

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
