### ISSUE TITLE
printToPDF hangs after changing dataurl

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#24370]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.5
* **Operating System:**
  * macOS 10.14
* **Last Known Working Electron version:**
  * 8.3.3

### Expected Behavior

Printing to PDF should work.

### Actual Behavior

It's so broken. 

In particular in this new issue printing to PDF doesn't work anymore after changing data-url. It works though if different html files are being loaded rather than data-urls.

### To Reproduce

Gist: https://gist.github.com/365258e7b0c627146fb746866f01ec48

**Comment by kevinwang89** [comment]
I met exactly same issue with electron 13.2 on win10.
call printToPDF. It works 
Reload the page (Cmd+R)
call printToPDF again. promise never resolved.

**Comment by fabiospampinato** [comment]
No stale.

**Comment by fabiospampinato** [comment]
Still interested in this
