### ISSUE TITLE
Display only blank page when i use electron-builder

### ISSUE THREAD

**Issue by a-ditucalan** [electron/electron#24377]
### Preflight Checklist

* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
    "^9.0.5"
* **Operating System:**
  * 
mac os 10.14.6 
* **Last Known Working Electron version:**
  * 

### Expected Behavior

     should show my actual app
### Actual Behavior

  just display blank page after I run electron-builder
### To Reproduce

this is a react. app
code structure

public
   - main.js
pakacge.json

### Screenshots

 
![image](https://user-images.githubusercontent.com/58244709/86188976-d6a49e80-bb72-11ea-92a5-5a33125a870c.png)
![image](https://user-images.githubusercontent.com/58244709/86189138-487ce800-bb73-11ea-95a6-3bcffc5e955f.png)

**Comment by bouncyball02** [comment]
Try using this:
`mainWindow.loadUrl('../build/index.html);`

I think what may have happened is that the path module has joined `folder/app/../build/index.html` instead of `folder/build/index.html`.

**Comment by a-ditucalan** [comment]
![image](https://user-images.githubusercontent.com/58244709/86437754-c2f66500-bd37-11ea-9c5c-1407e50cffe3.png)
it shows like this when i tried  mainWindow.loadUrl('../build/index.html);

**Comment by a-ditucalan** [comment]
"main": "public/main.js",
  "homepage": "./",
  "build": {
    "extends": null,
    "appId": "oneoften",
    "files": [
      "build",
      "*.js",
      "public"
    ],
    "dmg": {
      "contents": [
        {
          "x": 110,
          "y": 150
        },
        {
          "x": 240,
          "y": 150,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },
    "linux": {
      "target": [
        "AppImage",
        "deb"
      ]
    },
    "win": {
      "target": "squirrel",
      "icon": "build/favicon.ico"
    },
    "directories": {
      "buildResources": "assets"
    }
  }

here is my code in package json and this is my script
![image](https://user-images.githubusercontent.com/58244709/86437847-fa651180-bd37-11ea-8cc7-53eaaabdb0e7.png)

**Comment by bouncyball02** [comment]
I've just consulted [the documentation](https://www.electronjs.org/docs/tutorial/first-app#electron-development-in-a-nutshell), try `win.loadFile`. I think this may solve your problem.

**Comment by marc2332** [comment]
@a-ditucalan You are just missing a ' before closing the ).

Yours: `mainWindow.loadUrl('../build/index.html);`

Fixed: `mainWindow.loadUrl('../build/index.html');`

**Comment by sofianguy** [comment]
try @marc2332's suggestion
