### ISSUE TITLE
PDF viewer doesn't work in partitions without 'persist'

### ISSUE THREAD

**Issue by iwiedenm** [electron/electron#24378]
Hi Electron team. Was really excited to try the new addition of the PDF viewer but unfortunately cannot get it work  in all cases. It seems to work fine in the `electron-quick-start` using this sample PDF: https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf

However, the PDF does not load (and also does not throw any errors) when using a partition **other than one beginning with `persist:`**.

Example:
Working: `persist:this-works`
Not working: `this-doesnt-work`

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.0 - 9.0.5
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron version:**
  * n/a

### Expected Behavior
Open PDF should work in persistent and non-persistent partitions

### Actual Behavior
PDF only loads in persistent partitions.

### To Reproduce
Fiddle: https://gist.github.com/iwiedenm/ae323d691a5fbd8bcf1c0315f944e0b2
Code:
```js
const mainWindow = new BrowserWindow({
  width: 800,
  height: 600,
  webPreferences: {
    nodeIntegration: true,
    // partition: 'persist:this-does-work',
    partition: 'this-doesnt-work',
  }
})

mainWindow.loadURL('https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf')
```

**Comment by MarshallOfSound** [comment]
This is currently expected behavior.  The PDF viewer only works in sessions with Extension support, and Extension support requires `persist:` sessions

**Comment by iwiedenm** [comment]
@MarshallOfSound where in the documentation is this noted? Thanks
