### ISSUE TITLE
Shell openItem is not declared in electectron.d.ts

### ISSUE THREAD

**Issue by ceonizm** [electron/electron#24386]
Hello,

with the update of the latest electron on my app I've got this typescript error at build time 

> openItem' does not exist on type 'Shell'

As far I can read on the online documentation (cf. https://www.electronjs.org/docs/api/shell#shellopenitemfullpath) it seems this method should still exists isn't it ? 

Is it a documentation problem or a typescript declaration one ?

**Comment by pushkin-** [comment]
the method was replaced with `openPath`. It's not listed in the docs anymore

**Comment by ceonizm** [comment]
Thanks for your answer . 

> the method was replaced with `openPath`. It's not listed in the docs anymore
In that case the website documentation has to be updated because [it is still listed there](https://www.electronjs.org/docs/api/shell#shellopenitemfullpath)
