### ISSUE TITLE
TypeError: Error processing argument at index 1, conversion failure

### ISSUE THREAD

**Issue by thomasdao** [electron/electron#24380]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
When I build a menu with icon in menu item, or use an icon in TouchBarButton, it runs mostly ok in my dev build, but once in a while I also see this error `TypeError: Error processing argument at index 1, conversion failure` like below.  However I am still unable to reproduce it reliably. This problem happens a lot more frequent in Electron 9.0.5 than previous versions of Electron. I can confirm that the image exists and it usually runs without problem.

Bug report when icon is in menu item:

```
TypeError: Error processing argument at index 1, conversion failure from /Users/user/Documents/project/build/mac/AppName.app/Contents/Resources/app.asar/dist/electron/static/images/highlight/red.png
  at Array.forEach (<anonymous>)
  at Array.forEach (<anonymous>)

Error: Could not call remote method 'buildFromTemplate'. Check that the method signature is correct. Underlying error: Error processing argument at index 1, conversion failure from /Users/user/Documents/project/build/mac/AppName.app/Contents/R...
```

Bug report when icon is in TouchBarButton:
```
Error: Image could not be created from /Applications/AppName.app/Contents/Resources/app.asar/dist/electron/static/images/touchbar/settings.png
Error: Could not call remote method 'getPath'. Check that the method signature is correct. Underlying error: Image could not be created from /Applications/UpNote.app/Contents/Resources/app.asar/dist/electron/static/images/touchbar/settings.png
```

* **Electron Version:** 9.0.5
* **Operating System:** Mac
* **Last Known Working Electron version:** I think previous versions of Electron also have this problem.

### Expected Behavior
Should be able to use icon in Menu and TouchBarButton without any problem

### Actual Behavior
Error `TypeError: Error processing argument at index 1, conversion failure`

### To Reproduce
I'll keep trying but still not sure how to get it reproduced. I just received a lot of these from Sentry bug reports.

**Comment by thomasdao** [comment]
I just noticed that if I set icon of menu item with an NativeImage instead of string, this error will disappear, even if the url is invalid. If a menu item with invalid url, the icon is simply not displayed, but other menu item with valid icon will not be affected, and `Menu.buildFromTemplate` does not show error.

If I set icon to a string and that string does not point to a valid file, `Menu.buildFromTemplate` will result in error like above and the whole menu cannot be popped up.

So I'm converting my code to set icon menu item with NativeImage instead of string. Below is the helper module in case someone might find it useful.

```javascript
const remote = require('electron').remote
const { Menu, nativeImage } = remote

export class MenuHelper {
  static flattenMenuItems (template) {
    if (!template || !Array.isArray(template)) {
      return []
    }

    const arr = []
    for (const menuItem of template) {
      arr.push(menuItem)
      if (menuItem.submenu) {
        const subArr = MenuHelper.flattenMenuItems(menuItem.submenu)
        arr.push(...subArr)
      }
    }
    return arr
  }

  static popup (template) {
    const menuItems = MenuHelper.flattenMenuItems(template)

    try {
      for (const item of menuItems) {
        const icon = item.icon
        if (icon && typeof(icon) === 'string') {
          item.icon = nativeImage.createFromPath(icon)
        }
      }
      const menu = Menu.buildFromTemplate(template)
      menu.popup(remote.getCurrentWindow())
      return menu
    } catch (error) {
      console.error('popup menu error', error)

      // Some error happens with icon, delete it
      for (const item of menuItems) {
        delete item.icon
      }
      const menu = Menu.buildFromTemplate(template)
      menu.popup(remote.getCurrentWindow())
      return menu
    }
  }
}
```

I apply the same fix for TouchBarButton, instead of passing string to icon, now I use a nativeImage. I am suspecting something wrong when passing string to icon. I'm releasing this fix now and will be monitoring this issue in upcoming weeks.

**Comment by vladimiry** [comment]
There were similar issues placed before. As far as I remember you will get ` Error processing argument at index 1, conversion failure` error message in the case of invalid image use (like a file with PNG extension file but actually is not at image) or the path to image is incorrect (maybe try full path just to test the case).

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
