### ISSUE TITLE
Offscreen transparent window cause app crashing

### ISSUE THREAD

**Issue by blackart** [electron/electron#24384]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.0 - 9.0.5
* **Operating System:**
  * maxOS 10.15.5, windows 10 x64
* **Last Known Working Electron version:**
  * 8.3.4

### Expected Behavior

The app should not crash. And the window should be transparent in offscreen mode.

### Actual Behavior

The app going to crash after the start.

### To Reproduce
Minimal code example to reproduce:
```
const { app, BrowserWindow } = require('electron');

app.disableHardwareAcceleration()

let win

app.whenReady().then(() => {
    win = new BrowserWindow({
        transparent: true,
        webPreferences: {
            offscreen: true
        }
    })

    win.loadURL('http://github.com');
})
```

**Comment by Dunklheit** [comment]
@MarshallOfSound potential regression in Electron 9.2.0 on Windows 10 x64 2004 Build 19041.450.
Using the following `BrowserWindow` options causes Electron to close immediately with no errors. Hardware acceleration on/off displays same behavior.
```js
{
  width: 854,
  height: 480,
  transparent: true,
  webPreferences: {
    offscreen: true,
    devTools: true,
    nodeIntegration: true,
    contextIsolation: false,
  },
}
```

**Comment by blackart** [comment]
@MarshallOfSound Why did you close the issue? It is still not working.

9.3.1 - now the offscreen transparent window and app close without error immediately after running.
10.1.2 - the app closes with signal SIGSEGV and error

**Comment by Dunklheit** [comment]
@MarshallOfSound Will you consider reopening this issue to investigate our findings?

**Comment by PieterVanZyl-NWU** [comment]
I would like to confirm that this breaks for me too

I was running Electron 10.0.0

And electron would crash when declaring a BrowserWindow with 
offscreen: true,
show:false,
transparent:true

Changing electron versions instantly fixed the problem 

Currently 8.3.1 Works.

I have resorted to downgrading as I don't even get error messages logs or info on the crash even if I put it in a try catch block.

**Comment by vulture** [comment]
I saw that this was merged to `master` but not to `9-x-y` nor `10-x-y`, only `11-x-y`, which is probably will it still crashes in Electron 9 and 10. It would either need to get "backported" to 9 and 10, or you would have to apply the fix and recompile yourselves (which is what we're opting to do for now).

**Comment by ajmetal** [comment]
I'm seeing this bug. It seems to crash as soon as you call any of 

`BrowserWindow.loadFile, BrowserWindow.loadURL, webContents.loadURL, webContents.loadFile`
