### ISSUE TITLE
Can't access location

### ISSUE THREAD

**Issue by almostindented** [electron/electron#24383]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.5
* **Operating System:**
  * Windows 10 1909 (64-bit)

I am developing a weather app using OpenWeatherMap and [this tutorial](https://enlight.nyc/projects/weather). I tried getting the user's location using `navigator.geolocation.getCurrentPosition` in the new Microsoft Edge and it worked fine, but when I compiled it with Electron and ran it, it seemed to automatically deny the permission. [This issue](https://github.com/electron/electron/issues/3268#issuecomment-152249479) says that Electron should automatically accept, so I'm wondering if I'm missing something. Thanks

I've put the code on a gist [here](https://gist.github.com/almostindented/a00409d980c3a8182696862a8a3b12d9).

**Comment by ayandebbarman** [comment]
Facing something similar

**Comment by aws0me** [comment]
the same on mac,when i visit https://www.googleapis.com/,it came a 400 code
