### ISSUE TITLE
Webview not able to load some websites / their dependencies

### ISSUE THREAD

**Issue by vsvanshi** [electron/electron#24395]
### Issue Details

* **Electron Version:**
  *  5.06
* **Operating System:**
  *  macOS 10.15.5

### Expected Behavior

Electron's webview tag should load the website without similar to normal browser

### Actual Behavior

Some particular websites are not being able to load correctly on the electron's webview
e.g try opening the following the website inside webview tag
https://myevicoreportal.medsolutions.com/

if we see the devtools console, we can see that all dependant scripts are not loading and website is throwing error
However if we open the same on a normal browser, it does not throw any error.

### To Reproduce

You should have an electron app with a webview embedded in it.
my Code is like : 
`
<webview 
                        className="webv"
                        ref={this.webview}
                        nodeintegration="true"
                        allowpopups="true"
                        webpreferences="allowRunningInsecureContent=true"
                        useragent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"
                        />
`
Open the site : https://myevicoreportal.medsolutions.com/
check devtools console

### Screenshots

Screenshots of the devtools console and network tab
![Consoletab](https://user-images.githubusercontent.com/8156467/86348448-4f901d00-bc7d-11ea-898d-39c7c2089b55.png)

![networktab](https://user-images.githubusercontent.com/8156467/86348553-73536300-bc7d-11ea-986a-23b7bea9dc72.png)

### Additional Information

Its not happening with all the sites only few of them.

Will be glad to share any more info on this if required.

**PS: I tried opening the same website in BrowserView, and there was no problem. 
The only thing is that i cannot use browserview in my app due to lack of documentation on it. Because I need to control the content inside the webview and interact with my code in renderer process. Whatever docs I saw on Browserview, all mention it being used in main process only.**

**Comment by bouncyball02** [comment]
For jQuery, try this:
Enable nodeIntegration in your electron's index.js:
`webPreferences: {
nodeIntegration: true
}`

Add in the script tag:
`<script src="path/to/jquery.min.js"></script>`

Then define it with require:
`<script>window.$ = window.jQuery = require('path/to/jquery.min.js');</script>`

If that doesn't work, try defining $ and jQuery seperately. Hope this solves part of your problem.

**Comment by vsvanshi** [comment]
@bouncyball02 thanks for getting back.
Although the scenario is a bit different. The problem is not that jQuery is not defined. The problem is that some websites are not able to load all of their resources when loaded in electron's webview.
Any idea what might cause that? Are there any specific flags or settings that I can try for webview tag?

Thanks in advance!

**Comment by bouncyball02** [comment]
![error1](https://user-images.githubusercontent.com/47083178/86451742-43ef3580-bd13-11ea-8ae5-862613d7f493.JPG)
I don't think it's just your webview.

**Comment by vsvanshi** [comment]
@bouncyball02 exactly!
Would be great to know why webview is behaving like this for some websites

**Comment by bouncyball02** [comment]
@vsvanshi Taken with html `iframe`

![error2](https://user-images.githubusercontent.com/47083178/86460733-d3e7ac00-bd20-11ea-998e-edbd1a2fe7d6.JPG)

> Its not happening with all the sites only few of them.

Some websites block embeds, and I think that is the problem

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!
