### ISSUE TITLE
electron-packager notarize issues

### ISSUE THREAD

**Issue by elmcapp** [electron/electron#24392]
I am trying to code sign and notarize our electron app. I know how to code sign using electron-osx-sign however my issue come with using electron-notarize. I am not 100% sure how to use the tool and would like to know if someone could help. I have packaged the app using the Electron-Packager lib. My package.json file is as follow. Could someone provide help on what needs to be added and where to notarize this app. 

{
  "name": "ERER",
  "version": "2.1.1",
  "description": "controller using Midi Data.",
  "main": "src/main.js",
  "build": {
    "extraFiles": [
      "./assets/**",
      "./app.sqlite3"
    ]
  },
  "scripts": {
    "postinstall": "install-app-deps",
    "start": "electron .",
    "build": "electron-packager ./ ERER --platform=darwin --icon=./assets/icons/erer.icns --asar"
  },
  "devDependencies": {
    "asar": "^3.0.3",
    "electron": "^7.0.1",
    "electron-packager": "^14.1.1"
  },
  "dependencies": {
    "braintree-web": "^3.62.2",
    "dialogs": "^2.0.1",
    "electron-builder": "^22.5.1",
    "electron-store": "^5.1.1",
    "firebase": "^7.14.2",
    "is-online": "^8.4.0",
    "lodash": "^4.17.15",
    "node-notifier": "^7.0.0",
    "smalltalk": "^4.0.6",
    "sortablejs": "^1.10.1",
    "sqlite3": "^4.1.1"
  }
}

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
