### ISSUE TITLE
shell.openItem(fullPath) in Chinese doc，but it not work

### ISSUE THREAD

**Issue by mtrucc** [electron/electron#24401]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.5
* **Operating System:**
  *  Windows 10 (1803) 
* **Last Known Working Electron version:**
  * 9.0.5

### Expected Behavior

![image](https://user-images.githubusercontent.com/16724665/86425776-9e3ec500-bd18-11ea-9bc5-a0940da6ba9f.png)

shell.openItem(fullPath) in Chinese doc，but it not work
In English documents, it is displayed as shell.openPath(path)
I have submitted a translation suggestion, please fix it as soon as possible
I learned that in a certain version shell.openItem(fullPath)
It was removed, but there was no update in the Chinese document. I submitted a translation suggestion. no change

### Actual Behavior

Failure to update the documentation in a timely manner, resulting in incorrect call releaseI learned that in a certain version shell.openItem(fullPath)
It was removed, but there was no update in the Chinese document. I submitted a translation suggestion. no change

### To Reproduce

https://www.electronjs.org/docs/api/shell
![image](https://user-images.githubusercontent.com/16724665/86425388-9cc0cd00-bd17-11ea-979c-661a113da43f.png)
![image](https://user-images.githubusercontent.com/16724665/86425416-b3ffba80-bd17-11ea-84c9-2fb404b43e19.png)
I learned that in a certain version shell.openItem(fullPath)
It was removed, but there was no update in the Chinese document. I submitted a translation suggestion. no change

### Screenshots

![image](https://user-images.githubusercontent.com/16724665/86425520-ff19cd80-bd17-11ea-9f76-9d3824b761b2.png)

### Additional Information

Sorry for the translation error. I don’t know where I should submit the issue and which category I should submit it. May cause you trouble, sorry

**Comment by SMLVG** [comment]
shell.openItem isn't removed yet.
You can require shell from your main.js yet.

**Comment by mtrucc** [comment]
> shell.openItem isn't removed yet.
> You can require shell from your main.js yet.

Electron Version:9.0.5

I guess in the new version, it may be replaced

https://github.com/electron/electron/blob/16a3f41fd39cee412fee8f4375ddc834351cf152/docs/breaking-changes.md#api-changed-shellopenitem-is-now-shellopenpath

> The shell.openItem API has been replaced with an asynchronous shell.openPath API. You can see the original API proposal and reasoning here.

**Comment by SMLVG** [comment]
For me it works great. Anyway if you downgrade it will work
