### ISSUE TITLE
Vanilla Build via Shell Script

### ISSUE THREAD

**Issue by Zacharys-Hackery** [electron/electron#24400]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Unrelated to a problem, but begs the question, *"Can Electron be used without npm?"*

### Proposed Solution

I would like to help (or try myself) to write a shell (either `sh` or `bash`) script that goes through the npm build process. As you may know, `bash` is available to users on all three main operating systems in the CLI.

### Alternatives Considered

Hunted and searched for other repositories that would accomplish the goal, but they involve other back-end languages besides JavaScript/Node.js/Deno.

### Additional Information

If this idea is approved, it would be beneficial to know which files are involved, as they appear to be somewhat separated among different directories (but mainly the `build`, obviously). In addition, where shall this file be added?

**Comment by MarshallOfSound** [comment]
Building Electron from source is quite complicated, you can see our build instructions in the `docs` folder or follow the directions in the `build-tools` directory.

If you just want to use prebuilt Electron binaries you can download them from GitHub Releases.  That's exactly what our NPM package does.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
