### ISSUE TITLE
BrowserWindow.isEnabled() return void

### ISSUE THREAD

**Issue by eisonwoo** [electron/electron#24409]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  9.0.5
* **Operating System:**
  *  mac os 10.15.5
* **Last Known Working Electron version:**
  *  9.0.5

### Expected Behavior
in electron.d.ts, why BrowserWindow.isEnabled() return void.

### Screenshots

![image](https://user-images.githubusercontent.com/16627047/86461938-59894d00-bd5d-11ea-8a1f-943a236764d0.png)

**Comment by samccone** [comment]
Notes:
```
yarn create-api-json
```

yields this in electron-api.json

![image](https://user-images.githubusercontent.com/883126/86994156-950b8900-c15a-11ea-968c-29a69dd43268.png)

Where we expect something more like this:

```
"returns": {
           "collection": false,
          "type": "Boolean"
        },
```

**Comment by samccone** [comment]
By comparing a working boolean example and a non-working, we can see that we are missing backticks *``* after the returns statement.

![image](https://user-images.githubusercontent.com/883126/86995019-ca18db00-c15c-11ea-87ff-93d89ac9ab1e.png)

By adjusting the documentation the correct api interface is now generated
![image](https://user-images.githubusercontent.com/883126/86995111-077d6880-c15d-11ea-982e-c3e770b23f0d.png)

Tracing this back to the docs parser code
https://github.com/electron/docs-parser/blob/e0d4379f3a63c3b4c39240cd1d0c047517da02d0/src/markdown-helpers.ts#L444-L448 we can see where it is looking for `\`` characters in the following token.

There could be an argument made where additional improvements to the linter could be made to error loudly when this sort of formatting issue is found :)
