### ISSUE TITLE
Multiple app dock icons shown

### ISSUE THREAD

**Issue by CyrusRoshan** [electron/electron#24407]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  9.0.5
* **Operating System:**
  *  macOS 10.15.5
* **Last Known Working Electron version:**
  *  not sure

### Expected Behavior

With the example program at [https://github.com/CyrusRoshan/electron-multiple-dock-icon](https://github.com/CyrusRoshan/electron-multiple-dock-icon), I would expect the dock icon to be hidden after the initial click, or multiple quick clicks in succession.

### Actual Behavior

If clicking once, dock icon behaves as expected, and disappears. If quickly clicking multiple times, dock icons are quickly added. These dock icons persist after app shutdown.

### To Reproduce

Clone and run this [electron-quick-start fork](https://github.com/CyrusRoshan/electron-multiple-dock-icon), then quickly click the dock icon.

### Screenshots

![image](https://user-images.githubusercontent.com/8443502/86441896-c3ecaf80-bcc1-11ea-8fda-619506d19331.png), can also upload a video if that'd help.

### Additional Information

This may have something to do with the following lines:

```
win.show();
win.setVisibleOnAllWorkspaces(true);
win.setAlwaysOnTop(true, 'pop-up-menu');
win.hide();
```

which are used for keeping BrowserWindows always on top [over fullscreen apps](https://github.com/electron/electron/issues/10078#issuecomment-331581160).

**Comment by SMLVG** [comment]
Try deleting 'pop-up-menu'

**Comment by CyrusRoshan** [comment]
The point is more that `app.dock.hide()` `app.dock.show()` should just [show and hide the app dock icon](https://www.electronjs.org/docs/api/dock#dockhide-macos), whereas this example results in multiple icons. Changing the window positioning isn't supposed to affect that.

**Comment by bpasero** [comment]
We have seen this issue in VSCode and our only workaround was to never call any dock related API.
