### ISSUE TITLE
session.removeExtension() crashes the app

### ISSUE THREAD

**Issue by zikosichi** [electron/electron#24421]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
9.0.0
* **Operating System:**
MacOS Catalina 10.15.5 

### Expected Behavior
The app should not crash after session.removeExtension()

### Actual Behavior
So the problem is that whenever I call session.removeExtension() the app crashes immediately without any exception. The main problem is that it does not happen in development. Only happens on the packed app.

Here's the screenshot of the exception
![image](https://user-images.githubusercontent.com/16005795/86489853-dcaea100-bd65-11ea-8524-cf6e056e10f3.png)

**Comment by zcbenz** [comment]
According to the crash report in the screenshot, it is caused by some packaging mistake, it seems that `icudtl.dat` was not included in the final app bundle.
