### ISSUE TITLE
Prevent HTML video lazy buffering / playing when the window is not focused or visible

### ISSUE THREAD

**Issue by Deveosys** [electron/electron#24442]
Hey, 

I want to send a video stream got from a file througt a RTCPeerConnection, here is how I do it, and it "works" : 

```
const videoElement = document.createElement("video");
videoElement.loop = true;
videoElement.muted = true;
videoElement.onplay = () => {
	const stream: MediaStream = videoElement.captureStream();
	onGetMediaStream(stream);
};
videoElement.src ="/.../.../video.mp4";
videoElement.play();
```

So far it's alsmost ok, but since i don't display le video element, the video is getting stuttering (the audio is fine).
If I display the video element, it's ok as long as I keep it visible.

I want to prevent that lazy playback when I don't display the video element, or if I display it, when the window is not visible.
I understand the need of that behaviour in a browser, but in my case it's a pain.

Setting backgroundThrottling to false in the BrowserWindow webPreferences doesn't help.

Maybe I should get the stream in a different way that I don't know ? 

Electron v5

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 7.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by Deveosys** [comment]
Hello,

Upgrading Electron to version 9 solved this. Thank you !
