### ISSUE TITLE
requestSingleInstanceLock does not report a running instance for a different user

### ISSUE THREAD

**Issue by ForesightImaging** [electron/electron#24447]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.3
* **Operating System:**
  * Windows 10 (1809)
* **Last Known Working Electron version:**
  * nope

### Expected Behavior
requestSingleInstanceLock  should only obtain the lock if there are no running instances of the app, regardless of who launched them... or it should take an optional dir that the developer can to pass that can be override the user data dir. 

### Actual Behavior
requestSingleInstanceLock  will report that you obtained the lock when there is another instance of the application running, provided that the other instance was launched by a different user.
### To Reproduce
Use the example code in the requestSingleInstanceLock documentation to only allow a single instance.
```
const { app } = require('electron')
let myWindow = null

const gotTheLock = app.requestSingleInstanceLock()

if (!gotTheLock) {
  app.quit()
} else {
  app.on('second-instance', (event, commandLine, workingDirectory) => {
    // Someone tried to run a second instance, we should focus our window.
    if (myWindow) {
      if (myWindow.isMinimized()) myWindow.restore()
      myWindow.focus()
    }
  })

  // Create myWindow, load the rest of the app, etc...
  app.whenReady().then(() => {
  })
}
```

- launch the app
- switch users
- launch the app

### Additional Information
The problem appears to be in electron_api_app.cc::RequestSingleInstanceLock

It's using the **_DIR_USER_DATA_** so it doesn't care about multiple users.

```
bool App::RequestSingleInstanceLock() {
  if (HasSingleInstanceLock())
    return true;

  base::FilePath user_dir;
  base::PathService::Get(DIR_USER_DATA, &user_dir);

  auto cb = base::BindRepeating(&App::OnSecondInstance, base::Unretained(this));

  process_singleton_ = std::make_unique<ProcessSingleton>(
      user_dir, base::BindRepeating(NotificationCallbackWrapper, cb));

  switch (process_singleton_->NotifyOtherProcessOrCreate()) {
    case ProcessSingleton::NotifyResult::LOCK_ERROR:
    case ProcessSingleton::NotifyResult::PROFILE_IN_USE:
    case ProcessSingleton::NotifyResult::PROCESS_NOTIFIED: {
      process_singleton_.reset();
      return false;
    }
    case ProcessSingleton::NotifyResult::PROCESS_NONE:
    default:  // Shouldn't be needed, but VS warns if it is not there.
      return true;
  }
}

```

**Comment by MarshallOfSound** [comment]
This is currently expected behavior.  If you want to change the directory the lock / token is stored in you can use `app.setPath('userData')` and override the user-data dir

**Comment by troppoli** [comment]
It would appear that changing the userData path does make the RequestSingleInstanceLock work with multiple users, but the 'second-instance' event does not fire.

Any thoughts there?
