### ISSUE TITLE
Save as PDF from PDF Viewer Print dialog fails

### ISSUE THREAD

**Issue by rgarcia1990** [electron/electron#24458]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.1.0
* **Operating System:**
  * macOS Mojave 10.14.6
* **Last Known Working Electron version:**
  * just v9. Because in electron version 9 was introduce "pdf viewer", but now it cant print pdf.

### Expected Behavior
just print correctly the pdf...

### Actual Behavior
when you try to print with "window.print()" a page that load a PDF electron do not respond.... sometimes crash...

### To Reproduce
just clone "electron-quick-start" and replace this line :
 mainWindow.loadFile('index.html') 
 for 
 mainWindow.loadURL('http://www.africau.edu/images/default/sample.pdf')
and replace all content script "preload.js" for:

window.addEventListener('DOMContentLoaded', () => {
  window.print();
});

this is a example repo to reproduce the error: 
https://github.com/rgarcia1990/electron-quick-start

just do the normal setup

$ git clone https://github.com/rgarcia1990/electron-quick-start
$ npm install
$ npm start || electron .

and when the app electron start will popup print dialog, just try to print!

that is all!

**Comment by Lawrence0528** [comment]
I has same problem in MacOS 10.15.5 ,but I not call window.print()
I just click the print button, electron window will crash
and I click the download button hasn't any response

**Comment by KasperSommer** [comment]
+1 - I get the print dialog but the print is never sent/enqueued to the printer.

**Comment by KaminoRyo** [comment]
I have same problem in Windows10. I use <a> tag to open PDF.
Pressing the print button shows the settings, but the app hangs when trying to print.
and the download button hasn't any response.

**Comment by michel-smarticket** [comment]
We have the same issues in both windows (tested in 7, 10) and MacOS (10.15 & 10.14.6).
The issue happens in electron 9.1, 10.0.0-beta11 & 11.0.0-nightly.20200708

The only way around it we found is to download the PDF and print with the default OS app.

**Comment by mfmatt** [comment]
I think I've been experiencing this same issue, on macOS 10.15.3 with every 9.x release. When using the print button in the viewer, the app hangs and the print job never reaches the OS printer queue. If I use window.print() in the devtools console, the print job reaches the OS printer queue, but the app still hangs.

**Comment by fulfillrite** [comment]
We are also experiencing the issue. Even tried 11.0.0-nightly.20200717.

**Comment by rjlfurtado** [comment]
I am using Vuejs with electron-builder electron 9.0.0.
The problem occurs when pressing the button to print from the browser.
The electron simply locks or ignores the pressure command.
which load is any page like electron.com it prints normal.
but when loading a pdf file and ordering the print it doesn't work.
does this have any solution today?

const win2 = new BrowserWindow({
      webPreferences: {
        plugins: true
      }
    })

    win2.loadURL(__dirname + '/file.pdf', {})
    win2.webContents.once('did-finish-load', async function() {
      try {
        const pdfData = await win2.webContents.printToPDF({})
        const outPath = __dirname +'/snotas.pdf'
        fs.writeFile(outPath, pdfData, (error) => {
          if (error) throw error
          console.log(`Wrote PDF to: ${outPath}`)
        })
      } catch(e) {
        console.error(e)
      }

    })
  })
The code above is only a third of the many I have tried.

Fortunately I have a workaround for this problem.
I'm using PDFtoPrinter with Electron-dl in my APP to download and print the PDF.
This is a temporary solution until this problem is actually resolved.
Below is my code.

```
import { download } from  'electron-dl';
const exec = require('child_process').exec;

const wins = BrowserWindow.getFocusedWindow();
  function execute(command, callback) {
    exec(command, (error, stdout) => {
      callback(stdout);
    });
  }

download(wins, url.url,{directory: app.getPath('userData')+'/notas',openFolderWhenDone:true}).then(result =>{

    execute('PDFtoPrinter.exe '+app.getPath('userData')+'/notas/'+url.fileName, (output) => {
      console.log(output);
    });
  })
```
I hope this helps someone as well as saved me.
It is worth mentioning that this is only a temporary solution for those who are in fact continuing their work.
I still look forward to the solution.

**Comment by Phillips126** [comment]
I am experiencing the same issue.  

I am generating a PDF with [PDFMake](http://pdfmake.org/#/), saving it to a local destination and opening it in a new BrowserWindow after the successful write.  The PDF opens and displays fine, but clicking any of the buttons (print for example) causes the window to hang until closed.

My workaround is instead to use:
```
const {shell} = require('electron')
shell.openExternal(pathToPDF)
```

This opens it in Chrome (as that's my default) and I can print from there.  
I'd love to keep everything inside Electron.

Windows 10, version 1909, build 18363.1082
Electron 10.1.2

**Comment by squalle0nhart** [comment]
Same here, app crash after i'm trying to print pdf from native previewer. Electron 9.3.1 and electron 10.1.3. MacOS 10.15.7

**Comment by githubBrandon** [comment]
Also seeing this issue. Window freezes when trying to print from a PDF preview. Printing anything else is working fine. Using Electron 10.1.3.

**Comment by rjlfurtado** [comment]
> Mesmo aqui, o aplicativo travou depois de tentar imprimir o PDF do visualizador nativo. Elétron 9.3.1 e elétron 10.1.3. MacOS 10.15.7

Yes, this is one of the bugs that has not yet been fixed.

**Comment by rjlfurtado** [comment]
> Same here, app crash after i'm trying to print pdf from native previewer. Electron 9.3.1 and electron 10.1.3. MacOS 10.15.7

Yes, this is one of the bugs that has not yet been fixed.

**Comment by codebytere** [comment]
I've put up a fix for this issue at https://github.com/electron/electron/pull/25959

**Comment by FrankWangZY** [comment]
It works when i use the print button at the top in the pdfview , but dosent work while  using window.print(),   win10 and electron 9.3.4,  can you help to fix this @codebytere

**Comment by geesen** [comment]
Can confirm that with electron 9.3.5 on Windows 10. The Windows printing dialog is shown, but the window freezes after clicking the print button within the printing dialog. using the chromium print button. 
The aim is that the native dialog for printing appears immediately after opening or displaying the PDF so that the user does not have to click a button again.

**Comment by aidanjacobson** [comment]
Can confirm both window.print() and webContents.print() both cause electron to crash on win10 and electron 9.3.5.

**Comment by LFdeWeb** [comment]
> I am using Vuejs with electron-builder electron 9.0.0.
> The problem occurs when pressing the button to print from the browser.
> The electron simply locks or ignores the pressure command.
> which load is any page like electron.com it prints normal.
> but when loading a pdf file and ordering the print it doesn't work.
> does this have any solution today?
> 
> ```
> const win2 = new BrowserWindow({
>       webPreferences: {
>         plugins: true
>       }
>     })
> 
>     win2.loadURL(__dirname + '/file.pdf', {})
>     win2.webContents.once('did-finish-load', async function() {
>       try {
>         const pdfData = await win2.webContents.printToPDF({})
>         const outPath = __dirname +'/nameMyFileSaved.pdf'
>         fs.writeFile(outPath, pdfData, (error) => {
>           if (error) throw error
>           console.log(`Wrote PDF to: ${outPath}`)
>         })
>       } catch(e) {
>         console.error(e)
>       }
> 
>     })
>   })
> ```
> 
> The code above is only a third of the many I have tried.
> 
> Fortunately I have a workaround for this problem.
> I'm using PDFtoPrinter with Electron-dl in my APP to download and print the PDF.
> This is a temporary solution until this problem is actually resolved.
> Below is my code.
> 
> ```
> import { download } from  'electron-dl';
> const exec = require('child_process').exec;
> 
> const wins = BrowserWindow.getFocusedWindow();
>   function execute(command, callback) {
>     exec(command, (error, stdout) => {
>       callback(stdout);
>     });
>   }
> 
> download(wins, url.url,{directory: app.getPath('userData')+'/mydirectory',openFolderWhenDone:true}).then(result =>{
> 
>     execute('PDFtoPrinter.exe '+app.getPath('userData')+'/mydirectory/'+url.fileName, (output) => {
>       console.log(output);
>     });
>   })
> ```
> 
> I hope this helps someone as well.
> It is worth mentioning that this is only a temporary solution for windows for those who are in fact continuing their work.
> I still look forward to the solution.


Is there another way to achieve it
