### ISSUE TITLE
Missing "visible-on-all-workspaces-changed" event

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#24451]
### Problem Description

The internal states that apps keep of whether each window is visible on all workspaces or not can't be kept in sync with the actual state of the window (assuming polling is not acceptable) because there currently doesn't seem to be a way to detect when the "visibleOnAllWorkspaces" property changes from outside the app, e.g. like by manually toggling this from macOS' dock.

### Proposed Solution

There should be a "visible-on-all-workspaces-changed" event, like there is a "always-on-top-changed" event.

### Alternatives Considered

Polling? But it's unclear whether the `BrowserWindow#visibleOnAllWorkspaces` is even kept synchronized with external changes, and polling would be an unreasonable strategy for this anyway.

**Comment by codebytere** [comment]
Seems reasonable. I'll try to add it sometime soon.

**Comment by codebytere** [comment]
See PR for why this ended up being closed - apologies!
