### ISSUE TITLE
Built-in spellchecker on mac, params.dictionarySuggestions always empty array

### ISSUE THREAD

**Issue by eugene-pr** [electron/electron#24455]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.1.0
* **Operating System:**
  * macOS Mojave 10.14.6
* **Last Known Working Electron version:**
  * -

### Expected Behavior
On context-menu event, params.dictionarySugestions should be an array of suggested words for a misspelled word.
### Actual Behavior
params.dictionarySugestions always return an empty array

### To Reproduce
1. install electron-quick-start
2. set spellcheck:true in webPreferences
3. Add textarea to the index.html
4. Add context-menu listener to the created browserWindow.webContents

### Screenshots

![image](https://user-images.githubusercontent.com/9944915/86895601-62876f00-c10d-11ea-9646-fa5e3315786a.png)
* Screenshot from the Notes.app, you can see a list of suggestions for the misspelled word "twer".
![image](https://user-images.githubusercontent.com/9944915/86895742-9a8eb200-c10d-11ea-991c-41bcc69fb4d6.png)

**Comment by EtienneLem** [comment]
FWIW; Tried all the versions from **9.1.0** to **8.0.0** and I could never* get any suggestions. 

\* Actually, the first time I tried **8.0.0** I did get suggestions. Then tried a more recent version and since then **8.0.0** has stopped giving me suggestions as well. 🤷 

I also noticed that `ses.getSpellCheckerLanguages` returns `['ru']` even though I haven’t set Russian in my system languages. It returns `['en-US']` if I set it although it’s advertised as being no-op on macOS. Suggestions always empty regardless of this.

Just in case this could give some pointers.

**Comment by MarshallOfSound** [comment]
What is your spelling language set to in system preferences?

![image](https://user-images.githubusercontent.com/6634592/90043965-c0b1ef80-dc81-11ea-894d-9046372ccb2a.png)

**Comment by eugene-pr** [comment]
This is my spelling language set

![image](https://user-images.githubusercontent.com/9944915/90107376-62544200-dd51-11ea-88e3-f030932bc713.png)

**Comment by MarshallOfSound** [comment]
@eugene-pr If you change "Spelling" from "Automatic by Language" to your preferred language can you see if the spellchecker works?

**Comment by eugene-pr** [comment]
@MarshallOfSound , same behavior.

![image](https://user-images.githubusercontent.com/9944915/90328909-008e1500-dfa9-11ea-8e41-013559d5520b.png)

**Comment by EtienneLem** [comment]
On my end changing Spelling from Automatic to a language did work (after restarting electron). And now even when setting Spelling back to Automatic I do get suggestions. I also made sure I would still get suggestions after rebooting, I do. I also tried to re-install the native dependency ([`atom/node-spellchecker`](https://github.com/atom/node-spellchecker)), `electron-rebuild` and go back to the new built-in spellchecker (without native dependencies), I still get suggestions.

Looks like suggestions always work now. I’m just not 100% sure I can trust that it will be the case for all our users on macOS. Having to ask them to go through the changing Spelling setting steps would be a bit of a blocker.

**Comment by eugene-pr** [comment]
It seems that it's also working for me now. But it didn't work after restarting electron, then I rebooted my laptop and it does work. Also If it can help, chrome browser also did not show any spellcheck suggestions before and now it does. Unfortunately can't reproduce it back to not working.

**Comment by EtienneLem** [comment]
Interesting. Now that you mention it, I remember not having suggestions on Chrome and now I do.

**Comment by aabuhijleh** [comment]
I can reproduce this reliably in Electron 9.3.0 on macOS Catalina in my application

* When Spelling = "Automatic by language"
<img width="376" alt="Screen Shot 2020-11-04 at 8 56 45 PM" src="https://user-images.githubusercontent.com/42934634/98156686-ce71bc80-1ee0-11eb-9ccf-20cd40fbdbe9.png">
<img width="378" alt="Screen Shot 2020-11-04 at 8 57 03 PM" src="https://user-images.githubusercontent.com/42934634/98156689-cfa2e980-1ee0-11eb-9fda-dad66ed3f51c.png">

* When Spelling = "U.S. English" + restarting the app
<img width="433" alt="Screen Shot 2020-11-04 at 8 58 20 PM" src="https://user-images.githubusercontent.com/42934634/98156695-d0d41680-1ee0-11eb-82bf-c2294f2f8ef4.png">

If I change the setting back to automatic (and restart the app), the same issue will happen

Google Chrome spell checking was fine in both cases

From my testing, it seems that Electron spell checking on macOS will be very inconsistent unless the language to be spell checked is explicitly defined in system preferences

Of course, most users will have the default preference "automatic", so this is a big problem for us. Can anyone please suggest a workaround?

**Comment by aabuhijleh** [comment]
Any updates on this issue?

**Comment by benjaminfrombe** [comment]
+1 

still having to change languages manually everytime I change language ...
