### ISSUE TITLE
Windows: recentDocuments menu role item does not show any items

### ISSUE THREAD

**Issue by Sakari369** [electron/electron#24457]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.0
* **Operating System:**
  * Windows 10.0.18363
* **Last Known Working Electron version:**
  * 8.2.0 works on macOS perfectly.

In my application, when I open and save files, I add them to the recentDocuments with:

```
app.addRecentDocument(path)
````

When I create the menus, I have this menu item in the menus

```
		{
			label: 'Open Recent',
			role: 'recentDocuments',
			submenu: [
				{ role: 'clearRecentDocuments' }
			]
		},
```

This recentDocuments menu is perfectly populated on macOS: 

<img width="686" alt="Screenshot 2020-07-08 at 14 29 44" src="https://user-images.githubusercontent.com/1212726/86913645-9cfe0580-c127-11ea-80c4-2cb73dd575f7.png">

but on Windows, it stays empty:

<img width="494" alt="Screenshot 2020-07-08 at 14 28 39" src="https://user-images.githubusercontent.com/1212726/86913658-a12a2300-c127-11ea-81bc-b577996bcf10.png">

I have registered the application in the Windows registry as instructed in: 
https://docs.microsoft.com/en-us/windows/win32/shell/app-registration

In my electron-builder NSIS installation script I run this:

```
!macro customInstall
  DetailPrint "Register application"
  DeleteRegKey HKEY_CURRENT_USER "SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\${APP_EXECUTABLE_FILENAME}"
  WriteRegStr HKEY_CURRENT_USER "SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\${APP_EXECUTABLE_FILENAME}" "" "$INSTDIR\${APP_EXECUTABLE_FILENAME}"
!macroend
```

I have also tried to register the application under HKEY_LOCAL_MACHINE, to no effect in making the recentDocuments menu item work.

The Recent items work when right clicking on the application icon in the taskbar:

<img width="494" alt="Screenshot 2020-07-08 at 14 29 13" src="https://user-images.githubusercontent.com/1212726/86915491-ba809e80-c12a-11ea-851a-a6a6bb941938.png">

I don't understand why this does not work on Windows. 

### Expected Behavior

When calling app.addRecentDocument and adding the recentDocuments in the menu, the recentDocuments entry should contain those paths in it.

### Actual Behavior

The recentDocuments stays empty.

### Additional Information

Any help is appreciated. The documents should probably also make it more clear how to perform the application windows registry process.

**Comment by inDigiNeous** [comment]
Updating: Tested this with Electron@latest, 9.1.0 also, not working there either.
Will try to later provide a minimal test case, or is there perhaps a test case where this works ? Tried to look at VSCode, but it seems to handle the recents menu a bit differently.

**Comment by inDigiNeous** [comment]
I have made a minimal electron-quick-start based application where you can test this. It does not work on Windows, just tested with macOS 10.14.6 and Windows 10 version 1909.

Here is the repository with minimal code to add support for opening ".txt" files and adding them to the recents menu. Tested with latest Electron 9.1.2.

Maybe someone can take a look at this ? Thanks.

https://github.com/inDigiNeous/electron-quick-start

**Comment by tobeyfox** [comment]
I still encounter the same issue with Electron 17.1.0 - Is there any workaround?

**Comment by mmarczell-graphisoft** [comment]
This behaviour is strictly speaking not a bug in Electron. On macOS, a recent documents menu is automatically populated by an OS API called NSDocumentController. Electron simply sits atop this API and calls into it when user code calls `addRecentDocument` etc.

On Windows, the system API only manages the taskbar jump list, but doesn't provide a way to automatically populate a menu. So Electron says "I'm only giving you a JS API for the functionality the OS provides". And indeed in the [documentation](https://www.electronjs.org/docs/latest/tutorial/recent-documents#macos-notes) this menu item role is only mentioned under a macOS section.

I agree that it is annoying to have to build this menu manually on other platforms, and it would be great if Electron implemented this for the other OS's.
