### ISSUE TITLE
Printing hangs with pageSize Object

### ISSUE THREAD

**Issue by TheSinding** [electron/electron#24456]
* **Electron Version:**
v9.0.1
* **Operating System:**
Linux 5.7.4-arch1-1
### Expected Behavior
I expect it to print.

### Actual Behavior
The printing hangs.

### To Reproduce
```javascript
const { remote } = require ('electron');

const { BrowserWindow } = remote;
const win = new BrowserWindow();

win.loadURL('https://google.com');

win.webContents.on('did-finish-load', () => {
  win.webContents.print({ pageSize: { height: 88.6, width: 35.7 } }, (success, error) => {
    if(!success) console.error(error);
  })
})
```
Here is a fiddle of the error `https://gist.github.com/81597c2a1f33779c7083194b4590f55c`

**Comment by codebytere** [comment]
@TheSinding i see the error - i'll try to get this patched up soon :)

**Comment by TheSinding** [comment]
@codebytere - Arh okay that's great.
It would be great it the documentation were more detailed.

Right now it looks like this:
`pageSize` String | Size (optional) - Specify page size of the printed document. Can be `A3`, `A4`, `A5`, `Legal`, `Letter`, `Tabloid` or an Object containing `height`.

It should properly look like this.
`pageSize` String | Size (optional) - Specify page size of the printed document. Can be `A3`, `A4`, `A5`, `Legal`, `Letter`, `Tabloid` or an Object containing `height` and `width` measured in **microns**.


Second:
I would be awesome if I could enter the actual paper name in the PPD driver as well. I my case I'm trying to print with a DYMO LabelWriter 450, which uses the `30321 Large Address` in the driver, but I can't specify it in the `pageSize`. 

I don't know if that would be useful to anyone other. :)

**Comment by TheSinding** [comment]
This GIST still wont work in my system, is it my setup ? 
`https://gist.github.com/81597c2a1f33779c7083194b4590f55c`

**Comment by codebytere** [comment]
@TheSinding what does "won't work" mean in this context? are you seeing errors?

**Comment by TheSinding** [comment]
There is not error or any output, it just hangs until I close the BrowserWindow.
