### ISSUE TITLE
Null characters in certain UI control text input are invisible, zero-width

### ISSUE THREAD

**Issue by wesinator** [electron/electron#24465]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.13 (atom --version)
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron version:**
  * 

### Expected Behavior

null characters (`0x00`) should be visibly displayed in electron text on macOS with a nul or unicode symbol, as they are in Chrome, Firefox, VS code on macOS

### Actual Behavior

null characters are displayed as invisible (zero-width) in Electron apps on macOS only. 

Most Electron apps on other platforms seem to display the null characters correctly

### To Reproduce
Text containing a null character : 
[trailing_null_char_text.txt](https://github.com/electron/electron/files/4892871/trailing_null_char_text.txt)

Select all text, copy and paste into Chrome and/or Firefox on mac, then paste text into an electron app (e.g. atom , Slack).

Firefox: 
<img width="81" alt="image" src="https://user-images.githubusercontent.com/5124946/86963028-dc315400-c131-11ea-9aa8-923cf9a4fd18.png">

Chrome: 
<img width="70" alt="image" src="https://user-images.githubusercontent.com/5124946/86963069-ed7a6080-c131-11ea-9377-2b4a56a43577.png">

-------
Slack app:
<img width="91" alt="image" src="https://user-images.githubusercontent.com/5124946/86963096-f703c880-c131-11ea-97b4-5643ab7a2a26.png">
hitting backspace removes the char so it's still there just not visible (zero-width)

Atom (showing column width):
<img width="215" alt="image" src="https://user-images.githubusercontent.com/5124946/86963978-60d0a200-c133-11ea-8024-21a5f046ed36.png">

This was [reported to atom](https://github.com/atom/atom/issues/19307), but it affects all Electron apps I've tested on macOS:
atom
insomnia.rest
Slack

On Linux, the characters are displayed as boxes in Atom, but are zero-width in Slack app (snap package)

I believe this is an electron issue

While not super common for 'normal' users, null characters can be encountered by developers

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 7.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by wesinator** [comment]
I can still reproduce this in Electron 8.0.2 via Electron Fiddle UI control input text on macOS, using the text that contains a null character from https://github.com/electron/electron/files/4892871/trailing_null_char_text.txt 

To reproduce:
 - Select all of text containing null char 
 - Paste text containing null char into the Electron Fiddle text box for "Load Fiddle"
 - Hit backspace button to erase text, notice the backspace button is pressed twice before the first visible character is deleted, because of the null character being invisible zero-width in the Electron UI control text input. 
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/5124946/87332201-3e5ed000-c509-11ea-954e-af6e780d3a03.png">

The edit fields in Fiddle do show the null character as a visible `?` hexagon 

It seems this is an issue with certain text input controls in the Electron UI, the editor fields used by VS Code and Fiddle don't have this issue, but the text input other places in the apps and in Atom's editing UI do.

VS Code is the same as Fiddle where the UI input controls display the null char invisibly, but the characters are visible in the editor :
<img width="821" alt="image" src="https://user-images.githubusercontent.com/5124946/87332952-6ac71c00-c50a-11ea-86d5-abd5c044df64.png">

**Expected:** null characters are displayed visibly in all Electron UI text input controls

**Comment by zcbenz** [comment]
Does the same issue happen in Chrome browser? This looks like an upstream rendering issue.

**Comment by wesinator** [comment]
> Does the same issue happen in Chrome browser? This looks like an upstream rendering issue.

No not in Chrome address bar, but yes it seems like macOS native UI input controls issue. 
But also encountered in Slack app on other platforms. 

Going to close this
