### ISSUE TITLE
webgl-insight chrome extension could not work in electron 9.1.0

### ISSUE THREAD

**Issue by zombieyang** [electron/electron#24478]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.1.0
* **Operating System:**
  * macOS 10.15.4

### Expected Behavior
Webgl-insight could run in electron.

### Actual Behavior
The 'enable' button in devtool panel show a button "click the button to enable the plugin". I clicked it, the page refreshed but the plugin still disabled. 

I modified some code(delete some chrome.storage code) and enable the plugin by default. but It still not work. And I could not found any content-script code in source panel.

### To Reproduce
my demo:
https://github.com/xosuperpig/electron-extension-webgl-insight

### Additional Information
I tried the backbone devtool. It looks like the same.

**Comment by xosuperpig** [comment]
maybe is same as #24011
