### ISSUE TITLE
onBeforeSendHeaders applies for all windows

### ISSUE THREAD

**Issue by AlexSmorchkov** [electron/electron#24484]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  9.1.0
* **Operating System:**
   macOS 10.15.5 / Windows 7-10
* **Last Known Working Electron version:**
  7.0.0

### Expected Behavior
Adding BrowserWindow.webContents.session.webRequest.onBeforeSendHeaders modifier, I expect that this will modify only headers only on that window

### Actual Behavior
Headers of all windows are modified

### To Reproduce
```javascript
const { app, BrowserWindow } = require('electron');

app.on('ready', () => {
	// First window:
	const win1 = new BrowserWindow({ title: 'WIN 1' });
	win1.on('page-title-updated', event => event.preventDefault() );
	win1.webContents.toggleDevTools();
	win1.loadURL('https://www.wikipedia.org');

	setTimeout(() => {
		// Second one:
		const win2 = new BrowserWindow({ title: 'WIN 2' });
		win2.on('page-title-updated', event => event.preventDefault() );
		win2.webContents.toggleDevTools();
		win2.loadURL('https://www.wikipedia.org');

		// Modify headers for win2 only:
		win2.webContents.session.webRequest.onBeforeSendHeaders((details, callback) => {
			callback({ cancel: false, requestHeaders: {
				...details.requestHeaders,
				'X-User-Agent': 'TEST'
			} });
		});
	}, 1000);
	
	// Then, observe network tab of both devtools and see x-user-agent field inside of the both windows,
	// But it is expected to see x-user-agent inside only win2!
});
```

### Screenshots
![IMG_0077 2](https://user-images.githubusercontent.com/68071195/87058375-ae6f0c80-c210-11ea-8505-6ac216cd13ee.JPG)
![IMG_0077](https://user-images.githubusercontent.com/68071195/87058438-bfb81900-c210-11ea-87cf-98abb60ef265.JPG)

**Comment by nornagon** [comment]
This is working as intended. `webContents.session` is not unique per-WebContents, it's a reference to the session in which the WebContents was created (probably `session.defaultSession` unless otherwise overridden).

Use the `webContentsId` property of the `details` parameter to the event to determine which WebContents the event came from.
