### ISSUE TITLE
Systray crash during destruction aura::WindowEventDispatcher::UpdateCapture

### ISSUE THREAD

**Issue by zarubond** [electron/electron#24481]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
7.3.1
* **Operating System:**
Windows 10
* **Last Known Working Electron version:**
none

### Expected Behavior
From our crash logs we have found that on some computers the System tray icon crashes during destruction

### Actual Behavior
Systray should destroy itself without crash

### To Reproduce
    electron.exe.pdb
    aura::WindowEventDispatcher::UpdateCapture(aura::Window *,aura::Window *) window_event_dispatcher.cc:409
    electron.exe.pdb
    views::DesktopCaptureClient::SetCapture(aura::Window *) desktop_capture_client.cc:79
    electron.exe.pdb
    views::DesktopCaptureClient::ReleaseCapture(aura::Window *) desktop_capture_client.cc:105
    electron.exe.pdb
    aura::Window::ReleaseCapture() window.cc:712
    electron.exe.pdb
    views::MenuHost::HideMenuHost() menu_host.cc:197
    electron.exe.pdb
    views::SubmenuView::Hide() submenu_view.cc:421
    electron.exe.pdb
    views::MenuController::CloseMenu(views::MenuItemView *) menu_controller.cc:2034
    electron.exe.pdb
    views::MenuController::CommitPendingSelection() menu_controller.cc:1968
    electron.exe.pdb
    views::MenuController::SetSelection(views::MenuItemView *,int) menu_controller.cc:1365
    electron.exe.pdb
    views::MenuController::Cancel(views::MenuController::ExitType) menu_controller.cc:563
    electron.exe.pdb
    views::internal::MenuRunnerImpl::Release() menu_runner_impl.cc:74
    electron.exe.pdb
    views::internal::MenuRunnerImplAdapter::Release() menu_runner_impl_adapter.cc:27
    electron.exe.pdb
    views::MenuRunner::~MenuRunner() menu_runner.cc:29
    electron.exe.pdb
    void std::unique_ptr<views::MenuRunner,std::default_delete<views::MenuRunner> >::~unique_ptr() memory:2296
    electron.exe.pdb
    electron::NotifyIcon::~NotifyIcon() notify_icon.cc:42
    electron.exe.pdb
    void electron::NotifyIcon::~NotifyIcon() notify_icon.cc:36
    electron.exe.pdb
    electron::NotifyIconHost::~NotifyIconHost() notify_icon_host.cc:83
    electron.exe.pdb
    static int <lambda_f03950bc5685219e0bcd2087efbe011e>::operator()() onexit.cpp:204
    electron.exe.pdb
    static int __crt_seh_guarded_call<int>::operator()<<lambda_69a2805e680e0e292e8ba93315fe43a8>,<lambda_f03950bc5685219e0bcd2087efbe011e> &,<lambda_03fcd07e894ec930e3f35da366ca99d6> >(class __acrt_lock_and_call::__l2::<lambda_69a2805e680e0e292e8ba93315fe43a8> *, class _execute_onexit_table::__l2::<lambda_f03950bc5685219e0bcd2087efbe011e> & const, class __acrt_lock_and_call::__l2::<lambda_03fcd07e894ec930e3f35da366ca99d6> *) internal_shared.h:204
    electron.exe.pdb
    _execute_onexit_table onexit.cpp:160
    electron.exe.pdb
    static void <lambda_6e4b09c48022b2350581041d5f6b0c4c>::operator()() exit.cpp:232
    electron.exe.pdb
    static void __crt_seh_guarded_call<void>::operator()<<lambda_03b1d95aef87969028cfba75ccab2455>,<lambda_6e4b09c48022b2350581041d5f6b0c4c> &,<lambda_22bdf7517842c4b3e53723af5aa32b9e> >(class __acrt_lock_and_call::__l2::<lambda_03b1d95aef87969028cfba75ccab2455> *, class common_exit::__l2::<lambda_6e4b09c48022b2350581041d5f6b0c4c> & const, class __acrt_lock_and_call::__l2::<lambda_22bdf7517842c4b3e53723af5aa32b9e> *) internal_shared.h:224
    electron.exe.pdb
    static void common_exit(const int, const _crt_exit_cleanup_mode, const _crt_exit_return_mode) exit.cpp:201
    electron.exe.pdb
    exit exit.cpp:293
    electron.exe.pdb
    static int __scrt_common_main_seh() exe_common.inl:295
    wkernel32.pdb
    0x756e6359 + 90969
    wntdll.pdb
    0x770b7c24 + 424996
    wntdll.pdb
    0x770b7bf4 + 424948

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
