### ISSUE TITLE
How to make disabled button in electron dialog

### ISSUE THREAD

**Issue by vasyl-shumskyi** [electron/electron#24482]
I would like to make a disabled button in electron dialog with countdown. And make button active once countdown finished.

So the questions are:

- Is it possible to make a disabled button in electron dialog?
- Is it possible to change button text dynamically in dialog?

I know that separate window can be created to represent dialog but I would really want to use operating systems native dialogs in single window process and don’t invoke ipc communication if possible.

Thanks!

**Comment by codebytere** [comment]
@vasyl-shumskyi it's not right now for either unfortunately - system dialogs by and large currently do not have that capability and in the interest of maintaining platform parity it's not something we'll likely do until it becomes possible on a majority of OSes
