### ISSUE TITLE
powerMonitor does not fire 'suspend" event, Re:open 24244

### ISSUE THREAD

**Issue by gupta-shivam** [electron/electron#24499]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.4.0
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 

### Expected Behavior
Again opening issue [24244](https://github.com/electron/electron/issues/24244) as its not working even after the new changes.

electron.remote.powerMonitor should have fired the 'suspend' event and eventually 'The system is going to sleep' should have been printed in the console.

### Actual Behavior
No event is received.

### To Reproduce
I tried both the scenarios, but it is not working
1) to explicitly put the computer on sleep and hibernate
2) to wait for some time as selected in power options, and let it automatically go to sleep.
Try using this Gist link

[Gist URL link](https://gist.github.com/gupta-shivam/d364e186dfc0a2cd177c9078c9a576eb)

**Comment by alexeykuzmin** [comment]
@codebytere FYI

**Comment by alexeykuzmin** [comment]
@gupta-shivam , is the bug happening on a physical machine or on a virtual machine, or both?

**Comment by gupta-shivam** [comment]
@alexeykuzmin , I have tried on a few physical machines and it is happening there. I don't know about virtual machines.

**Comment by alexeykuzmin** [comment]
@codebytere FYI ^

**Comment by zcbenz** [comment]
It is interesting that on a virtual machine the suspend/resume events were emitted, while on a Surface the lock-screen/unlock-screen events were emitted.

@gupta-shivam Did the lock-screen/unlock-screen events emit on your machines?
