### ISSUE TITLE
Keyboard when Screen Reader is enabled on Ubuntu 20.04

### ISSUE THREAD

**Issue by chaynes-ws** [electron/electron#24506]
### Issue Details

* **Electron Version:**
  * Various.  Proglem is exhibited by recent installs of Slack, Spotify, and VSCode
* **Operating System:**
  * Ubuntu 20.04 x64

### Expected Behavior
After enabling the Screen Reader in Ubuntu (in Settings -> Universal Access -> Screen Reader) all electron apps should accept all keyboard input as normal.

### Actual Behavior
For all electron applications installed (VSCode, Slack, and Spotify), only a limited set of key presses are recognized by the application.  The following keys work, all others produce no result:
fjnwz7890-[];'./

### To Reproduce
1. Open VSCode, open a new file, type normally to verify keys are working.
2. Open the Ubuntu Settings application
3. Click Universal Access in the left-hand pane
4. Click the `Screen Reader` item in the Seeing category
5. In the modal click the toggle to enable the reader
6. Close the modal
7. Close the Settings application
8. Switch back to VSCode and attempt to type in the file as before

**Comment by rbarzic** [comment]
I can confirmed the issue (but not sure it is related to Screen Reader). A colleague of mine as the same issue on Ubuntu 20.04 LTS
