### ISSUE TITLE
setZoomLevel updates multiple windows' zoom level

### ISSUE THREAD

**Issue by Jokerwolf** [electron/electron#24505]
I'm calling set zoom level on a particular window from the main process. I have another window opened. Both windows change their zoom level. (see gist for repro).

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.3.4
  * 9.0.2
  * 10.0.0-beta.4
* **Operating System:**
  * Windows 10 (10.0.19041)

### Expected Behavior
I'd expect only the window on which setZoomLevel was called to change it's zoom

### Actual Behavior
Both windows change their zoom level

### To Reproduce
Gist: https://gist.github.com/Jokerwolf/da2f6b00566c1ac5f3f37f675625fe16

### Additional Information
I've found a closed issue https://github.com/electron/electron/issues/16018

**Comment by codebytere** [comment]
This is because zoom policy on chrome is same-origin, meaning that the zoom level for a specific domain propagates across all instances of windows with the same domain e.g. microsoft.com. Changing the URL will make that work again - we can add docs to clarify this.

**Comment by michael-hamilton** [comment]
I can add docs for this one and submit a PR

**Comment by ketulrudani** [comment]
Can I work on this issue?

**Comment by codebytere** [comment]
Sure! Anyone is free to open a PR :)
