### ISSUE TITLE
Submit to Apple app store, Binary file rejected

### ISSUE THREAD

**Issue by caoyongfeng0214** [electron/electron#24519]
* **Electron Version:**
  9.0.5
* **Operating System:**
 macOS

Use the way to build .pkg:
https://www.electronjs.org/docs/tutorial/mac-app-store-submission-guide

Submit to apple app store, received be rejected message after 2 day:
Binary file rejected

**Comment by JCBsystem** [comment]
exact what reject messade did you get ?

**Comment by caoyongfeng0214** [comment]
> exact what reject messade did you get ?

thanks for your reply.

i recived follow message:

> Binary file rejected
>
> Hello,
> 
> The review of your app is taking longer than expected. Once we have completed our review, we will notify you via Resolution Center.
> 
> If you would like to inquire about the status of this review, you may file a request via the Apple Developer Contact Us page. 

but, the status of my app is Rejected, not Waiting.
