### ISSUE TITLE
Duplicate CORS and Missing Cookie Headers on NodeJS HTTP requests within Electron Context

### ISSUE THREAD

**Issue by sushant-t** [electron/electron#24521]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.5
* **Operating System:**
  * macOS 10.15.5
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
When making a request through NodeJS using request-promise, I get an output with the following headers. 
<img width="1288" alt="Screen Shot 2020-07-11 at 5 57 14 PM" src="https://user-images.githubusercontent.com/13423028/87236580-0e47ed80-c3a0-11ea-904b-773541b7ed1d.png">

This is the output that I expect to see, where there are two cookies in "Set-Cookie", the "Access-Control-Allow-Headers" header only contains "Content-Type", and the "Access-Control-Allow-Origin" header is specific. 

### Actual Behavior

However, when I run the same exact script within an Electron context, where the same function is called from the frontend, I get different behavior. The following response headers are from when run in an Electron context.

<img width="745" alt="Screen Shot 2020-07-11 at 5 52 46 PM" src="https://user-images.githubusercontent.com/13423028/87236640-739bde80-c3a0-11ea-97c9-de3ba6ed3eff.png">

There are significant discrepancies between the two, and, most importantly, one of the cookies in the 'set-cookie' header is missing, when run from an Electron context. I am unable to find an explanation as to why this is happening. Interestingly enough, when I used Electron's native Net module, I was able to get the correct HTTP response, so I have narrowed it down to some sort of NodeJS issue from within an Electron context.

**UPDATE**
I have been able to narrow it down even further. It looks like the request is working perfectly within an electron context, _until I create a BrowserWindow _instance__. At that point, the response headers start going missing, as in the second picture.
### To Reproduce
Since this is a company project, I am unable to provide source code. However, my question still stands: is there some sort of difference in NodeJS when running natively versus in an electron context, and can that different be detected in an HTTP request?

**Comment by twitharshil** [comment]
@sushant-t I am not able to reproduce this at my end. Can you share a standalone test to reproduce the issue? You can also use [Electron fiddle](https://www.electronjs.org/fiddle) to share a minimal code to reproduce this issue
