### ISSUE TITLE
compile using ninja -C out/Release electron:electron_dist_zip error

### ISSUE THREAD

**Issue by bigben0123** [electron/electron#24525]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.3.2
* **Operating System:**
  * Ubuntu 19  x64
* **Last Known Working Electron version:**
  * electron 11 has not this problem.

### Expected Behavior

gn gen out/Testing --args="import(\"//electron/build/args/testing.gn\")"
ninja -C out/Testing electron:electron_dist_zip 

They can be executed normally.
### Actual Behavior

Compile error because include version header conflict. There is a version file under out/Testing, which is included by clang. However it should includ from:
 ./third_party/libc++/trunk/include/version.

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by bigben0123** [comment]
There is also a problem when excuting in order:
    ninja -C out/Testing electron:electron_dist_zip
    update a cpp
    ninja -C out/Testing electron

It'll report a error:
In file included from gen/third_party/blink/renderer/modules/clipboard/clipboard_jumbo_1.cc:5:
In file included from ./../../third_party/blink/renderer/modules/clipboard/clipboard.cc:5:
In file included from ../../third_party/blink/renderer/modules/clipboard/clipboard.h:8:
In file included from ../../buildtools/third_party/libc++/trunk/include/utility:199:
In file included from ../../buildtools/third_party/libc++/trunk/include/__tuple:14:
In file included from ../../buildtools/third_party/libc++/trunk/include/cstddef:37:
./version:1:1: error: expected unqualified-id
7.3.2
^

It need to remove out/Release/version before comipling.

**Comment by codebytere** [comment]
@bigben0123 there are fundamental differences between 7 and 11 that prevent them from being built to the same out directory. This should work if you try to build only 7 in a new location.
