### ISSUE TITLE
DOM Element Highlighter doesn't work in 10.0.0

### ISSUE THREAD

**Issue by govizlora** [electron/electron#24523]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.0.0-beta.10
* **Operating System:**
  * Windows 10 Pro 20H2 (19042.330)
* **Last Known Working Electron version:**
  * 9.1.0

### Expected Behavior

When inspecting the browser window using DevTools, hovering on the elements should highlight the corresponding DOM Element
### Actual Behavior
DOM elements are not highlighted
### To Reproduce

1. Clone https://github.com/electron/electron-quick-start
2. Run `npm i` then `npm start`. The DOM Element Highlighter works as expected.
3. Run `npm I -D electron@beta`, which installs `10.0.0-beta.10`
4. Run `npm start`, and DOM elements are no longer highlighted

**Comment by erickzhao** [comment]
This occurs for me on macOS as well. It worked in beta 4 and is broken in beta 8. (Betas 5-7 seem to not have been published correctly?)
