### ISSUE TITLE
Source maps don't work in production build (i.e. when app.asar is used): DevTools failed to parse SourceMap: file:///private/...

### ISSUE THREAD

**Issue by dko-slapdash** [electron/electron#24537]
Electron 9.1.0, a production build (with app.asar file).

Should source maps work seamlessly from app.asar file? (They work when running `electron <build_folder>`.)

Although all of the resources are perfectly loadable from this asar file, source maps are not available to dev tool for some reason, although they can be reached in e.g. dev tool console via fetch() - which means that the files are really there:

![image](https://user-images.githubusercontent.com/46383452/87421053-321b5700-c58b-11ea-90dc-cea3877b7baf.png)

-----

We can see that the manual fetch() for *.map file succeeded:

![image](https://user-images.githubusercontent.com/46383452/87421077-39426500-c58b-11ea-80c4-8951ba2cb51a.png)

-----

And here:

![image](https://user-images.githubusercontent.com/46383452/87421108-41020980-c58b-11ea-8638-1803bc0cc87e.png)

**Comment by shrinktofit** [comment]
Here is my conclusion, on Windows(Electron `v5.0.9`):

Electron accepts source maps with restrictions on items of `sources` field of source map:
- Absolute file path, in UNIX style: `C:/a/b/c.js`;
- Relative file path. Note:
  - The path should be in Windows Style, i.e. back-slashed. **forward-slash** is not allowed.
  - The path should be prefixed with `.\\`;
  - the `sourceRoot`  can be either file URL or absolute file path;
- `null`.

**Comment by CaseyLeeMurphy** [comment]
Having the same issue on 11.2.0 as well. And just like you, I can fetch the resource without issue, but devtools can't seem to load it
