### ISSUE TITLE
Problem : Running Application ( npm start )

### ISSUE THREAD

**Issue by webstrucs** [electron/electron#24535]
### Preflight Checklist

 [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
 [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
[ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * Electron 9.1.0
* **Operating System:**
  * Linux Debian 10 Bluster
* **Last Known Working Electron version:**
  * 

### Expected Behavior
Open application window

### Actual Behavior
Generating the following error after the npm start command :

> dash@1.0.0 start /.... /Projects/Dash
> electron .

> [32294:0713/230219.543245:FATAL:electron_main_delegate.cc(264)] Running as root without --no-sandbox is not supported. > See https://crbug.com/638180.

**Comment by jkleinsc** [comment]
@webstrucs as the error message printed out says, if you are running as root, you will need to pass the `--no-sandbox` flag in order to run.  Another option would be to run as a non-root user.

**Comment by webstrucs** [comment]
> @webstrucs as the error message printed out says, if you are running as root, you will need to pass the `--no-sandbox` flag in order to run. Another option would be to run as a non-root user.

`
I didn't run as root, see the output of the npm start command: 

`
 :~$ npm start
`

`
/usr/bin/env: “node”: No file or directory
`

`
Obs : The same output happens when you go to the application directory where I try to run the electron
`
