### ISSUE TITLE
%APPDATA%/project-name folder still being created after setting userData path

### ISSUE THREAD

**Issue by mweiczorek** [electron/electron#24536]
Hi,

First off, kudos the the developers and maintainers for creating such a great GUI tool. According to your documentation, we can customize the location of the Chromium user data and logging using:

```
app.setPath('userData', path.join(appDataDir, 'udata'))
app.setPath('logs', path.join(appDataDir, 'logs'))
```
This was to avoid having this data being stored in `%APPDATA%/project-name`, and instead keeping this data with the rest of my custom cache and application settings in a folder under app data with a more friendly name than the one specified in the `name` property of `package.json` - for example, on a Windows machine:

C:\Users\User\AppData\Roaming\Awesome App\

instead of
C:\Users\User\AppData\Roaming\awesome-app

The same thing happens when I run the app on my Ubuntu and Manjaro machines. I'll assume it acts the same on MacOS.

This currently works as far as where this data is stored, **however**, that folder with the `package.json` name is still being created, with only a subfolder named `Dictionaries` being created inside. As far as I can tell, it gets added during application startup.

So, this is more of a question than a bug report, as I could not find a definitive answer after spending a reasonable time searching. Is there another path that I need to set in order to keep this folder from being created (or having it created where I prefer)? I know this is possible, since VSCode and Slack (which use Electron) do not have these folders generated.

I was using version **5.0.12**, so I upgraded to **9.1.0**, and the same thing is happening.

* **Electron Version:**
  * 5.0.12, 9.1.0
* **Operating System:**
  * Windows10, Ubuntu 18.04, Manjaro
* **Last Known Working Electron version:**
  * Same issue persists

### Expected Behavior
`%APPDATA%/project-name` folder is not being created

### Actual Behavior
`%APPDATA%/project-name` folder **is** being created

### To Reproduce
Install electron, and immediately create your preferred folders and subfolders under `%APPDATA%`, then set the paths:
```
app.setPath('userData', path.join(appDataDir, 'udata'))
app.setPath('logs', path.join(appDataDir, 'logs'))
```
I also added this line before calling the above, but no change
```
app.setAppLogsPath(path.join(appDataDir, 'logs'))
```
Which is correct? `app.setAppLogsPath()` or `app.setPath('logs', ...)`? Or are they analogs of one another?

Then proceed as normal using `await app.whenReady()`, launch your services, windows, etcetera.

Thanks for any help!

**Comment by jkleinsc** [comment]
@mweiczorek are you calling `app.getPath('logs') before calling app.setAppLogsPath()? From the [docs](https://www.electronjs.org/docs/api/app#appgetpathname):

`If app.getPath('logs') is called without called app.setAppLogsPath() being called first, a default log directory will be created equivalent to calling app.setAppLogsPath() without a path parameter.`

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by mweiczorek** [comment]
Hi. As stated in my post, I called `app.setAppLogsPath()` **before** `app.setPath('logs', logPath)` as required. The `Dictionaries` folder is still being created in this unwanted directory.

**Comment by rafma0** [comment]
@jkleinsc Hey, if you could please take another look into this, I'm experiencing the same issue. I'm setting the userData folder as one of the first things I do, not doing any app.getPath(), and still %APPDATA%/project-name is created with an empty Dictionaries folder. Electron 10.1.0.

**Comment by Maple512** [comment]
@jkleinsc  Hey, I'm experiencing the same issue.

**Comment by Fargard** [comment]
@jkleinsc Same here!

At the very top of main.ts file:
```
if (process.platform === 'win32') {
  app.setPath('appData', process.env.LOCALAPPDATA);
  app.setPath('userData', path.join(process.env.LOCALAPPDATA, app.name));
  app.setAppLogsPath(path.join(process.env.LOCALAPPDATA, app.name, 'logs'));
}
```

But still get %APPDATA%/project-name with empty Electron and Dictionaries folders inside.
