### ISSUE TITLE
--no-sandbox is not supported ?

### ISSUE THREAD

**Issue by webstrucs** [electron/electron#24548]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  Electron 9.1.0

* **Operating System:**
  Debian GNU/Linux 10 (buster)

### Expected Behavior
Rotate the electron after the npm start command

### Actual Behavior
[17300:0714/163809.183079:FATAL:electron_main_delegate.cc(264)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

### To Reproduce
Just follow the documentation to install electron and create the application.

<!--
If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone $YOUR_URL -b $BRANCH
$ npm install
$ npm start || electron .
```

**Comment by nornagon** [comment]
This is working as intended. Don't run Electron as root.

**Comment by webstrucs** [comment]
> This is working as intended. Don't run Electron as root.

I didn't run as root, see the output of the npm start command: 

`. . :~$ npm start
/usr/bin/env: “node”: No file or directory
`
Obs : The same output happens when you go to the application directory where I try to run the electron

**Comment by nornagon** [comment]
Please don't open duplicate issues.

**Comment by webstrucs** [comment]
> Please don't open duplicate issues. #24535 is the same issue as this.

Sure, I will be deleting this post.

**Comment by webstrucs** [comment]
> Please don't open duplicate issues. #24535 is the same issue as this.

Okay, delete and how can I fix the problem?
