### ISSUE TITLE
VueDevtools Load Failed

### ISSUE THREAD

**Issue by GuoSirius** [electron/electron#24553]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  9.1.0
* **Operating System:**
  Windows 10
* **Last Known Working Electron version:**
  8.4.0

```javascript
    // 必须 Ready 之后执行
    if (isDevelopment && fs.existsSync(process.env.DSW_DEV_TOOLS_PATH)) {
      try {
        BrowserWindow.addExtension(process.env.DSW_DEV_TOOLS_PATH)
        BrowserWindow.addDevToolsExtension(process.env.DSW_DEV_TOOLS_PATH)
      } catch {
        session.defaultSession.loadExtension(process.env.DSW_DEV_TOOLS_PATH)
        mainWindow.webContents.session.loadExtension(process.env.DSW_DEV_TOOLS_PATH)
      }
    }
```

All of the above methods have been tried, but none of the VueDevtools extensions that work only on 8.4.0, 9.x.x will load。

**Comment by Y2zz** [comment]
I also encountered this problem
