### ISSUE TITLE
--no-sandbox is not supported ?

### ISSUE THREAD

**Issue by webstrucs** [electron/electron#24576]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  Electron 9.1.0

* **Operating System:**
  Debian GNU/Linux 10 (buster)

### Expected Behavior
Rotate the electron after the npm start command

### Actual Behavior
[17300:0714/163809.183079:FATAL:electron_main_delegate.cc(264)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

Example of running without root, see the output of the npm start command:

:~$ npm start
/usr/bin/env: “node”: No file or directory

Obs : The same output happens when you go to the application directory where I try to run the electron
### To Reproduce
Just follow the documentation to install electron and create the application.

<!--
If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
$ git clone $YOUR_URL -b $BRANCH
$ npm install
$ npm start || electron .
```

**Comment by MarshallOfSound** [comment]
As per https://github.com/electron/electron/issues/24548#issuecomment-658451343 do not open duplicate issues, continuing to do so will be considered a violation of Electrons Code of Conduct
