### ISSUE TITLE
why electron has vulnerabilities ?

### ISSUE THREAD

**Issue by redabc** [electron/electron#24580]
Hi Electron team,

A few days ago，we make a new issue about this，but the problem is not solved,  you can see this issue:
https://github.com/electron/electron/issues/24443

Recently, we have scanned both BoringSSL and Chromium, but both of them have no vulnerabilities .

so could you please help us .
Looking forward your soon feedback.

Thank you in advance.

**Comment by MarshallOfSound** [comment]
Please do not spam or open duplicate issues
