### ISSUE TITLE
`editFlags.canPaste` is set to true when there's only an image in the clipboard and one right-clicks an input

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#24609]
### Issue Details

* **Electron Version:**
  * 9.1.0
* **Operating System:**
  * macOS 10.14
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior

`editFlags.canPaste` should be set to `false` when right-clicking a textual input with no text in the clipboard.

### Actual Behavior

It can happen that it's set to `true`.

### To Reproduce

This gist partially illustrates the issue: https://gist.github.com/8c0cd6867a2ccdd12de7487360463edb, but for some reason there `canPaste` is `false`, but if you then open up an image with Preview, select a portion of it, copy it, and then right-click the input from the gist again then `canPaste` will be set to true, even though there still won't be any text in the clipboard to paste.

**Comment by codebytere** [comment]
Interesting! We copy this straight from Chromium, so it seems likely be an upstream issue 🤔 

https://github.com/electron/electron/blob/dc72f74020eb64afff7f01f8a9f13db69546724a/shell/common/gin_converters/blink_converter.cc#L373-L380

I'll try to poke around though

**Comment by codebytere** [comment]
Yep, so this is the [Chromium logic](https://source.chromium.org/chromium/chromium/src/+/master:ui/base/clipboard/clipboard_x11.cc;l=542-549;drc=957083cdc6ab64009a99570cf9c57dc8a1931c5b;bpv=1;bpt=1?originalUrl=https:%2F%2Fcs.chromium.org%2F):

```
  if (target_list.ContainsText())
    types->push_back(base::UTF8ToUTF16(kMimeTypeText));
  if (target_list.ContainsFormat(ClipboardFormatType::GetHtmlType()))
    types->push_back(base::UTF8ToUTF16(kMimeTypeHTML));
  if (target_list.ContainsFormat(ClipboardFormatType::GetRtfType()))
    types->push_back(base::UTF8ToUTF16(kMimeTypeRTF));
  if (target_list.ContainsFormat(ClipboardFormatType::GetBitmapType()))
    types->push_back(base::UTF8ToUTF16(kMimeTypePNG));
```

it takes into account png and jpg files

**Comment by fabiospampinato** [comment]
If it's of any use I discovered this issue while playing with [`copyImageAt`](https://www.electronjs.org/docs/api/web-contents#contentscopyimageatx-y), images put in the clipboard that way also trip the logic behind `canPaste`, I'm not sure why just calling directly `clipboard.writeImage` doesn't have the same effect.

**Comment by codebytere** [comment]
Well, i'm not sure this is really a bug then - it's documented as whether the renderer believes it can paste, which, when there which, when there is text, html, png, or rtf data in the clipboard, it thinks it can. 

This is expected behavior, especially since you can intercept the paste event with [`onpaste`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/onpaste) and scope to text content only

**Comment by fabiospampinato** [comment]
@codebytere I see 🤔 shouldn't then the renderer process believe that it can paste with the code in my gist too given that I'm explicitly putting an image in the clipboard there?
