### ISSUE TITLE
Rotrics Studio - Internal Error Occurred Please restart the app

### ISSUE THREAD

**Issue by Bobwords** [electron/electron#24613]
Hello!

When trying to connect to the arm, getting the below error.

![image](https://user-images.githubusercontent.com/3914254/87745196-e814ba00-c7b2-11ea-868e-dbf1a11ff037.png)

Spent time dialing in my com port, updated/installed drivers to no avail.

![image](https://user-images.githubusercontent.com/3914254/87745255-07134c00-c7b3-11ea-8800-0c881d921ecf.png)

In discord a user who was helping everyone said to send a 3 command from terminal on coolterm. That is met with an unknown command echo. 

![image](https://user-images.githubusercontent.com/3914254/87745310-2dd18280-c7b3-11ea-9c10-59adc9783f26.png)

Opened the unit, as some users were having issues with their device being reachable and an wire was disconnected when they opened the case. I did so, and everything looks kosher to me. 

![image](https://user-images.githubusercontent.com/3914254/87745385-62ddd500-c7b3-11ea-9b72-10b0f5910d14.png)

Also tried to test with the test and boot0 buttons, but nothing worked from there either. 

Any idea what is going on? Not sure if it's of use, but dropping in a DX diag so you get my basic system info.

[DxDiag.txt](https://github.com/electron/electron/files/4935589/DxDiag.txt)

**Comment by DataMike78** [comment]
I got the same issue, even after installing on 2 different PC's with Windows 64bit.  I allowed windows and Norton to give permission to run the file. I also don't see an installer file. I just ran the .exe directly after extracting the zip.

**Comment by Bobwords** [comment]
Welp, I figured it out. When I uncompressed the file, I moved it to my program files folder and linked it on my desktop/and failed to run as an administrator. As soon as I did that I got the firewall permission requests and the app has started normal. Here's what my console looked like:

![image](https://user-images.githubusercontent.com/3914254/87794737-b03a6080-c80c-11ea-8f8f-2b0f84b467bb.png)

My assumption is the "EPERM Operation Not Permitted" was to do with it not being allowed to access the location, which cleared the issue.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
