### ISSUE TITLE
Invalid document.visibilityState on webview unloading

### ISSUE THREAD

**Issue by drivron** [electron/electron#24630]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
v10.0.0-beta.12
* **Operating System:**
Ubuntu 20.04 x64

### Expected Behavior
The value of document.visibilityState should be 'hidden' on a webview unloading.

### Actual Behavior
The visibilitychange event is triggered between the beforeunload and unload event but document.visibilityState remains 'visible'.

### To Reproduce
I have attached an example to compare the behavior between Electron and a browser : [webview-visibilitystate-unload.zip](https://github.com/electron/electron/files/4938374/webview-visibilitystate-unload.zip)

Chromium output (webview.html) : 
```
visibilityState beforeunload visible
visibilityState visibilitychange hidden
visibilityState unload hidden
```
Electron output (main) : 
```
visibilityState beforeunload visible
visibilityState visibilitychange visible
visibilityState unload visible
```

**Comment by ckerr** [comment]
Gist copy of repro @ https://gist.github.com/ckerr/315d7b9da1ac0202b72cbe2dff745953
