### ISSUE TITLE
window.setPosition() coordinates not the same as the returned values from window.getPosition() 

### ISSUE THREAD

**Issue by ionalexandrusecara** [electron/electron#24637]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  3.0.2
* **Operating System:**
  Windows 10 Pro 10.0.18362 Build 18362

### Expected Behavior
When using `setPosition()` to position a window on the screen, I expect the window to be positioned at that exact coordinates.

### Actual Behavior
I'm using the `setPosition()` function to set the postition of the window to {x= -1560; y= -76} and in the next line of code I print out the result of `getPosition()` to check that those are indeed the coordinates at which the window is located. However the result from the `getPosition()` function is {x= -1950, y= -311}.

### To Reproduce
Just setup any electron app and use the following code snippet.
![image](https://user-images.githubusercontent.com/15220854/87863667-270d5180-c912-11ea-9923-bd276c9b2dde.png)

As explained above, the set of coordinates differ from setPosition() to getPosition(), as seen below.
![image](https://user-images.githubusercontent.com/15220854/87863674-41dfc600-c912-11ea-9bb4-14b87c5f7348.png)

### Additional Information
Please note that I am using the monitor of my laptop and another external monitor connected with HDMI to the laptop, hence the negative coordinate values.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
