### ISSUE TITLE
Electron 9.x: spell checker is enabled by default?

### ISSUE THREAD

**Issue by bpasero** [electron/electron#24639]
### Issue Details

* **Electron Version:**
  * 9.1.0
* **Operating System:**
  * macoS 10.15.x
* **Last Known Working Electron version:**
  * 8.x

### Expected Behavior
A renderer should not have the `--enable-spellcheck` switch unless `spellcheck: true` is provided when creating the window.

### Actual Behavior
A window has `--enable-spellcheck` as switch by default.

### To Reproduce
Just open a window with Electron 9 and print `process.argv` to find `"--enable-spellcheck"`

//cc @deepak1556

**Comment by MarshallOfSound** [comment]
This is documented as the default in Electron 9.  It was disabled by default in electron 8 as it was flagged as experimental

https://www.electronjs.org/docs/api/browser-window#new-browserwindowoptions
