### ISSUE TITLE
Windows and electron9.0.0 + cannot use the download file

### ISSUE THREAD

**Issue by 670133189** [electron/electron#24641]
Version: electron 9.0.0 and above (including 9.0.0)
Computer system: window8, 10 (MAC no problem)
Action: download file, use (https://www.npmjs.com/package/request-progress) or use http.get ()。
Error: run electron for the first time, then download: unstable. After refreshing HTML: unable to download.
Prediction problem: chromium causes the above problems.

**Comment by ckerr** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unneccessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you've responded, please link to the test case and @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info.
