### ISSUE TITLE
electron rss memory keep rising when heapUsed/heapTotal does not

### ISSUE THREAD

**Issue by jackple** [electron/electron#24646]
I'm running an IM app which is using indexedDB. When I switch a chat, I have to get some large objects like messages and chatroom mambers from indexedDB or http request. I found that the heapUsed/heapTotal memory in main/renderer is perfectly normal, but the rss memory keep rising.

similar issues:
[https://spectrum.chat/electron/general/debugging-high-memory-usage-in-electron~80057ff2-a51c-427f-b6e1-c297d47baf5b](https://spectrum.chat/electron/general/debugging-high-memory-usage-in-electron~80057ff2-a51c-427f-b6e1-c297d47baf5b)

[https://github.com/nodejs/help/issues/1518](https://github.com/nodejs/help/issues/1518)

[http://seenaburns.com/debugging-electron-memory-usage/](http://seenaburns.com/debugging-electron-memory-usage/)

I have tested all the possible solutions, but still could not fix it...
I want to know that is there anyone facing this problem like this!!

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
7.1.4
* **Operating System:**
macOS 10.15.5
* **Last Known Working Electron version:**
10.x

### Expected Behavior
The memory usage return to normal

### Actual Behavior
The memory usage keep rising

### Screenshots
![image](https://user-images.githubusercontent.com/6183232/87940859-d42bc980-cacc-11ea-8d30-ac0e244dce7d.png)

**Comment by ckerr** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unneccessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you've responded, please link to the test case and @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by jackple** [comment]
@ckerr 
Here is the demo  [https://github.com/jackple/electron-quick-start](url)

The memory in renderer is stable, but the app's memory have risen and will not be back to normal.
![image](https://user-images.githubusercontent.com/6183232/91640923-a2a30800-ea53-11ea-97a1-221e244d653d.png)

**Comment by Kyi-Moe-Min** [comment]
Have you found the solution? I'm facing the same issue.

**Comment by jackple** [comment]
no

**Comment by haoxi911** [comment]
I need to deal with a similar issue too, what interesting to me is it only happens on macOS, not Windows.
