### ISSUE TITLE
Change default path of .electron-gyp directory

### ISSUE THREAD

**Issue by petef19** [electron/electron#24640]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
The default path on Windows for the .electron-gyp directory is `C:\Users\<user_name>\.electron-gyp`. This is visible in the final built .asar file, where many node modules reference the full system file path. This potentially poses as a security risk and/or reveals sensitive information about the Windows user.

### Proposed Solution
Allow to specify the default location of the .electron-gyp directory.

**Comment by MarshallOfSound** [comment]
This repository doesn't set any default like that, you _might_ be looking for https://github.com/electron/electron-rebuild but just FWIW if your node module / build system is including the absolute system path that's not an issue with the thing doing the building, that's an issue with your module
