### ISSUE TITLE
All child windows have active title bar

### ISSUE THREAD

**Issue by zarubond** [electron/electron#24647]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  6,7,8,9
* **Operating System:**
  Window 10
* **Last Known Working Electron version:**
5.0.13

### Expected Behavior
Only one window should have active title bar at one time.

### Actual Behavior
All electron windows have active titlebar.

### To Reproduce
**index.html**
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
  </head>
  <body>
    <script>
      // You can also require other files to run in this process
      function openWin() {
        let modal = window.open(\'\',\'modal\');
        modal.document.write('<h1>Hello</h1>');
      }
    </script>
    <button onclick="openWin()">Open window</button>
  </body>
</html>
```
**main.js**
```
// Modules to control application life and create native browser window
const {app, BrowserWindow} = require('electron')

function createWindow () {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nativeWindowOpen: true
    }
  })

  mainWindow.webContents.on('new-window', (event, url, frameName, disposition, options, additionalFeatures) => {
  if (frameName === 'modal') {
    // open window as modal
    event.preventDefault()
    Object.assign(options, {
      width: 300,
      height: 300
    })
    event.newGuest = new BrowserWindow(options)
  }
})

  // and load the index.html of the app.
  mainWindow.loadFile('index.html')

  // Open the DevTools.
  // mainWindow.webContents.openDevTools()
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow)

// Quit when all windows are closed.
app.on('window-all-closed', function () {
  // On OS X it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', function () {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow()
  }
})

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.
```

### Screenshots

How it looks:
![image](https://user-images.githubusercontent.com/6961047/87950514-aaac7700-caa7-11ea-8559-8b681ad69b30.png)

How it should look like:

![image](https://user-images.githubusercontent.com/6961047/87950689-eb0bf500-caa7-11ea-9dd0-02dd09ee0267.png)

**Comment by zcbenz** [comment]
This is an upstream bug, I can reproduce with Chrome too.
<img width="486" alt="Screen Shot 2020-08-05 at 15 55 30" src="https://user-images.githubusercontent.com/639601/89381453-23603400-d734-11ea-85ee-db9ba809dfdb.png">
