### ISSUE TITLE
Misleading Project Lincense Statements

### ISSUE THREAD

**Issue by erlenmayr** [electron/electron#24665]
There was an issue about it before, but since it was locked I have to open a new one.
https://github.com/electron/electron/issues/3449

Not only small parts of ffmpeg are GPL-licensed. Chromium is a fork of WebKit, which is a fork of KHTML. KHTML is part of the KDE project, WebKit was developed in a cooperation of KDE and Apple. A lot of code in these is licensed with a variety of licenses from GNU, Mozilla, Apache and others, including GPL and LGPL.

>If you still have more questions, I suggest bringing it up on Chromium's issues list, Electron's license is compatible with Chromium's one, and I believe Google's lawyers have solved the license problems perfectly.

This is only partly correct. This is true for code written by the Chromium project, but Chromium contains a lot of code from other sources. For all of this sources, separate license statements exist in the source code.
Chrome is legal because the source code of Chrome is completely published. This is what the Chromium project is. By this, they are satisfying the license requirements for all components including GPL'd components.
The same also applies to Electron as such. Since the code for Electron is published, it is satisfying the license requirements of all components.

However, I am not sure that the statement that one can use Electron to build non-free apps is correct. Apps like Microsoft Teams are possibly illegal. I am picking Teams as a particular example because it is not only using Electron as a web view for proprietary pages, it is also linking a lot of proprietary stuff into the code for the native functionality.

**Comment by MarshallOfSound** [comment]
We are not lawyers, if you have legal concerns around your use of certain software and / or frameworks you should contact a lawyer familiar with software licensing.
