### ISSUE TITLE
electron-updater do not emit "error" event, on network disconnect with VPN on macOS

### ISSUE THREAD

**Issue by kirille** [electron/electron#24661]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
 *  electron 9.0.3, electron-updater 4.2.5
* **Operating System:**
 *  macOS 10.15

### Expected Behavior

Environment:
Electron app works with the server available only via VPN (OpenVPN client was used).
electron-updater detects new update and start downloading version.
During the load of the new version, turn off the internet, wait few seconds turn it on again.

electron-updater expected to emit an "error" event and stop downloading or resume downloading after VPN reconnected.

### Actual Behavior

Nothing happens. Download stuck and never resume. No error event posted.

Works fine without VPN.

enabling electron-log, for autoUpdater, shows nothing:

[2020-07-21 15:06:01.567] [info] Checking for update
[2020-07-21 15:06:06.442] [info] Found version 37.0.0 (url: )
[2020-07-21 15:06:06.444] [info] Downloading update from
[2020-07-21 15:06:06.453] [info] No cached update info available

**Comment by codebytere** [comment]
Please open this issue on https://github.com/electron-userland/electron-builder/tree/master/packages/electron-updater - that is not maintained by this team.
