### ISSUE TITLE
setImmediate not fiering after few usages

### ISSUE THREAD

**Issue by zarubond** [electron/electron#24669]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
9.1.0
* **Operating System:**
  only Windows 10 (tested on Ubuntu 20.04 and MacOSX 10.15.3 without problem)
* **Last Known Working Electron version:**
8

### Expected Behavior
setImmediate should always fire

### Actual Behavior
setImmediate after some time stops working

### To Reproduce
Unfortunately I have no repro outside of our application. But in our case it fails after four calls, right after accessing database.

**Comment by codebytere** [comment]
@zarubond without a repro or stack dump (not applicable here) we unfortunately cannot triage this. Please provide one for this issue to remain open, or it will be closed.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
