### ISSUE TITLE
Critical error in fetching "favicon"

### ISSUE THREAD

**Issue by JoshMcCullough** [electron/electron#24689]
### Preflight Checklist

* [ x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 7.1.x, possibly others in the 7.2+ range
* **Operating System:** Windows, Mac OS, others likely
* **Last Known Working Electron version:** 6.0.12 but possibly others before 7.1

### Expected Behavior

Electron, at least v7.1.x, is making a _massive number_ of requests for the favicon. We are seeing literally hundreds of thousands of requests for the favicon _per hour_, from only a dozen or so users using these versions of the desktop app.

This can easily overwhelm servers. We have specifically blocked these requests with the user-agent containing `Electron/7.1` and the path (in our case) `/assets/favicon.svg` at our Web Application Firewall (WAF) so that our servers farther in are not overloaded with these superfluous requests.

This issue was noticed in the Rocket.Chat desktop app, **please see this ticket for more information**: https://github.com/RocketChat/Rocket.Chat.Electron/issues/1658

### Actual Behavior

Electron should not make hundreds of thousands of requests for the favicon.

### To Reproduce

Not 100% sure how easy it will be to reproduce. If you setup an RC server and use the RC desktop app (v2.17.x), you should see your server being flooded with requests for the favicon.

### Screenshots

This chart shows requests for the favicon by Rocket.Chat (RC) / Electron (E) version:

![image](https://user-images.githubusercontent.com/4859660/88188076-59b29500-cc05-11ea-8614-31ff8d582c80.png)

### Additional Information

This is a pretty serious bug, and we are _assuming_ this is in Electron, not Rocket.Chat, based on our own research.

**Comment by ckerr** [comment]
Hi @JoshMcCullough! Thanks for reporting this, but I'm not sure how to proceed with this -- It sounds like the suggested steps are that we start debugging through RocketChat's codebase?

I'd love to meet you halfway on this, but would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you've responded, please link to the test case and @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by JoshMcCullough** [comment]
Sorry, I know it isn't straightforward, but I think the issue was fixed in Election 7.3.2, at least. I think this can be closed.
