### ISSUE TITLE
White screen on macOS when switch to fullscreen using flash plugin.

### ISSUE THREAD

**Issue by flunardelli** [electron/electron#24685]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v9.1.0
* **Operating System:**
  *  tested on macOS 10.13 
* **Last Known Working Electron version:**
  * 

### Expected Behavior
Go to full screen, asking for keyboard control

### Actual Behavior
Keeps current screen size and displays a completely white background
### To Reproduce
Just open a flash content that switches to interactive fullscreen on macOS

### Screenshots

![fullscreen-electron](https://user-images.githubusercontent.com/682036/88172482-73e57680-cbf7-11ea-89d8-08f2c325ed14.gif)

**Comment by upjersdave** [comment]
Odd. We had the exact same problem at the exact same time yesterday! Flash crashes when going to full screen. It will go white or black or whatever the background colour is behind the flash content.

We're using Electron 7. It doesn't work in earlier versions either.

To reproduce: add any flash content in a browser window and switch it to fullscreen. We're not talking about HTML5 fullscreen, or maximising the window using native OSX-fullscreen, but rather native flash fullscreen. You can see this in the demo above. Flash fullscreen works on windows correctly.

There are no errors that we can see in the console/in electron. It just crashes. It doesn't matter if directly loaded inside the BrowserWindow, or if the flash content is inside a webview, or even if it is packaged as a standalone exe. Every constellation on a mac causes the crash. This also happens on previous OSX versions. We have tried different flash versions to no avail.

Can someone help?

Thanks!

**Comment by upjersdave** [comment]
Still having the problem. Anyone have an idea?

**Comment by upjersdave** [comment]
@flunardelli Did you manage to fix this in any way?

**Comment by flunardelli** [comment]
I haven't found a solution yet.

**Comment by flunardelli** [comment]
> @flunardelli Did you manage to fix this in any way?

I haven't found a solution yet.
