### ISSUE TITLE
docs on contents.print pageRanges "Record<string, number>" is unclear: what values should be used?

### ISSUE THREAD

**Issue by barbalex** [electron/electron#24684]
I have tried to set pageRanges. But it does not seem to work.

Probably that is due to me not knowing how to add this option. Unfortunately the docs are not clear to me: https://github.com/electron/electron/blob/master/docs/api/web-contents.md#contentsprintoptions-callback

What does "Record<string, number>" mean? I have tried:

- an object with properties from and to
- a string like this: `1-1`

I do not understand what a `Record` is. It is not a JavaScript concept I think.

So to put this a bit more clearly:

- please explain what a record is
- please add where counting begins: Is the first page 0 or 1?

**Comment by ckerr** [comment]
Hi @barbalex, yes I agree the documentation could be a little clearer.

I believe it works like this:

```js
const options = {
  pageRanges: {
    from: 0,
    to: 1
  }
}
```

to print the first two pages. So it's zero-based, and the entire `pageRanges` object specifies a single [begin..end] range.
