### ISSUE TITLE
Zoom web SDK Captcha verification not opening

### ISSUE THREAD

**Issue by huzoorbux** [electron/electron#24690]
I have created a desktop app from my website, integrated zoom websdk and i am unable to verify captcha before joining session. When i click on captcha verify it shows something like this: 
![Screenshot 2020-07-22 at 7 26 35 PM](https://user-images.githubusercontent.com/1098035/88189190-3a8e2480-cc52-11ea-86cf-ddf23cb7fd6c.png)

**Comment by huzoorbux** [comment]
not opening captcha popup window

**Comment by ckerr** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unneccessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you've responded, please link to the test case and @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by huzoorbux** [comment]
@ckerr Thanks for the quick response

I have fork app here: [https://github.com/huzoorbux/electron-quick-start](url) and it's working fine let me check my original app and try to fix it.
