### ISSUE TITLE
Border radius on my window (Operating system : Windows 10)

### ISSUE THREAD

**Issue by ThomasLeconte** [electron/electron#24697]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  v9.1.0
* **Operating System:**
  Windows 10 19041

### Expected Behavior
I wanted to get a window with rounded edges

### Actual Behavior
I'm actually trying to set a border radius on my main project window but it's seems don't work... I have set transparent : true and frame : false, but nothing.

### To Reproduce
**index.js**:  
  const mainWindow = new BrowserWindow({
    transparent: true,
    frame: false,
    width: 1280,
    minWidth:1024,
    height: 720,
    resizable: true,
    webPreferences:{
      nodeIntegration: true
    },
    backgroundColor: '#00FFFFFF'
  });

**index.html**:  
"<!DOCTYPE html>
<html style="border-radius: 5px;">
  <head>
    <meta charset="UTF-8">
    <title>MyConfig - Admin</title>
    <link rel="stylesheet" href="index.css">
    <link rel="stylesheet" href="bulma-0.6.2/css/bulma.css">
    <script defer src="render.js"></script>
  </head>
  <body>
</html>"

### Screenshots
[](https://nsa40.casimages.com/img/2020/07/22//20072210593525373.png)

**Comment by ThomasLeconte** [comment]
It's work finally, don't understand why ... Problem of cache ?

**Comment by Toxic48** [comment]
I'm having this exact issue in the latest version, how did you fix it?

**Comment by ThomasLeconte** [comment]
> I'm having this exact issue in the latest version, how did you fix it?

Hello ! I never fixed this issue unfortunally... Border radius was only affecring Web page rendering, not window view element. I'm going to check that and reply again if I found a solution, 2 years later 😂 !

**Comment by ThomasLeconte** [comment]
> I'm having this exact issue in the latest version, how did you fix it?

Re,
I think this tutoriel could help you ! This guy has just removed the default window frame rendered, and there is only Web page render element so you can apply border-radius on it 😉
Check this out : https://bobby-valenzuela.medium.com/electron-js-how-to-create-a-beautiful-frameless-window-8ee9ef9d1280

**Comment by Toxic48** [comment]
> Re, I think this tutoriel could help you ! This guy has just removed the default window frame rendered, and there is only Web page render element so you can apply border-radius on it 😉 Check this out : https://bobby-valenzuela.medium.com/electron-js-how-to-create-a-beautiful-frameless-window-8ee9ef9d1280

Thank you for responding after 2 years. That tutorial is pretty useful in some cases but not in mine. My body element needs to have a background color, but not outside the border outline. I opened another issue for this #35870, you can see a screenshot of my problem there.

**Comment by ThomasLeconte** [comment]
You could make a global div or section which apply border-radius, and put inside it your main content div with background color applied on it ? 
This tutorial apply my (potential) solution : https://youtu.be/gcy7yatasio?t=132

**Comment by ThomasLeconte** [comment]
> > Re, I think this tutoriel could help you ! This guy has just removed the default window frame rendered, and there is only Web page render element so you can apply border-radius on it 😉 Check this out : https://bobby-valenzuela.medium.com/electron-js-how-to-create-a-beautiful-frameless-window-8ee9ef9d1280
> 
> Thank you for responding after 2 years. That tutorial is pretty useful in some cases but not in mine. My body element needs to have a background color, but not outside the border outline. I opened another issue for this #35870, you can see a screenshot of my problem there.

You could make a global div or section which apply border-radius, and put inside it your main content div with background color applied on it ?
This tutorial apply my (potential) solution : https://youtu.be/gcy7yatasio?t=132

**Comment by Toxic48** [comment]
> You could make a global div or section which apply border-radius, and put inside it your main content div with background color applied on it ? This tutorial apply my (potential) solution : https://youtu.be/gcy7yatasio?t=132

Unfortunately, in my case, I'm rendering a remote page, which is selected by user (so it could be any webpage on the internet). That's why I can't do that much customisation, and I only want to apply the border to the body through a preload JS file

**Comment by ThomasLeconte** [comment]
> > You could make a global div or section which apply border-radius, and put inside it your main content div with background color applied on it ? This tutorial apply my (potential) solution : https://youtu.be/gcy7yatasio?t=132
> 
> Unfortunately, in my case, I'm rendering a remote page, which is selected by user (so it could be any webpage on the internet). That's why I can't do that much customisation, and I only want to apply the border to the body through a preload JS file

Do you want to send me your project ? I think solution should be very interesting for other people, but it need more work than a simple anwser on this issue 😂
