### ISSUE TITLE
A way to get the tray icons position without click

### ISSUE THREAD

**Issue by jenslind** [electron/electron#2469]
For instance when you have a menubar app and you want to trigger `window.show()` with a global shortcut or any other way that does not involves clicking on the tray icon. :)

**Comment by zcbenz** [comment]
It is possible on Windows, but I doubt whether it is possible on OS X.

**Comment by jenslind** [comment]
Okey, thanks!

**Comment by nickbytes** [comment]
@jenslind have you found any way around this? I'm trying to solve the same thing, whenever I use a global-shortcut the window appears in the upper right corner. I tried using `.move()` but don't know how I would get the `trayBounds`.

**Comment by Silvercast** [comment]
+1

**Comment by ssreekanth** [comment]
+1

**Comment by magalhaespaulo** [comment]
+1

**Comment by Silvercast** [comment]
+1

**Comment by mikaelharsjo** [comment]
+1

**Comment by Piot** [comment]
+1

**Comment by aaronransley** [comment]
+1

**Comment by wiziple** [comment]
+1

**Comment by T-Specht** [comment]
+1

**Comment by b-connect** [comment]
+1

**Comment by javiergarmon** [comment]
+1

**Comment by z-ax** [comment]
+1!

**Comment by brian-mann** [comment]
Screenhero does exactly what everyone is asking for in OSX.

If you launch screenhero it will immediately pop up as if the tray icon had been clicked.

**Comment by guatedude2** [comment]
+1
This would be extremely useful when clicking on a notification and wanting to show the window from the tray

**Comment by fukajun** [comment]
:+1:

**Comment by tex0l** [comment]
+1

**Comment by CHENGP618** [comment]
+1

**Comment by danawoodman** [comment]
@zcbenz why has this been closed? Is it now possible to get tray position without click? If so, where can we learn about it?

**Comment by baconface** [comment]
@danawoodman The closing of this issue is mentioned in PR https://github.com/electron/electron/pull/6159 which was merged 10 days ago. The PR appears available in the 1.2.4 release.

**Comment by danawoodman** [comment]
Awesome, thanks @baconface for the update!
