### ISSUE TITLE
Win 7 crash “Internal D3D11” “LoadLibrary failed to load D3D Compiler DLL”

### ISSUE THREAD

**Issue by adammeyer** [electron/electron#24723]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
8.4.0
* **Operating System:**
win 7 64bit
* **Last Known Working Electron version:**
5

### Actual Behavior
Shows blank, white browser window.  No elements are drawn.

### To Reproduce
Hard to pin point.  I can't replicate this behavior with all win 7 64bit machines, just some.  Launch an empty hello world browser window to see the issue.

It looks like an out of memory issue, but the machine stats still show memory available.

### Screenshots
![](https://i.stack.imgur.com/wh0eJ.png)

### Additional Information
Issues doesn't happen with Electron 5.

**Comment by ckerr** [comment]
Thanks for the report.

I hear where you're coming from about this being difficult to pinpoint -- without context, this will be difficult to reproduce / to debug. Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

**Comment by little-tomorrow** [comment]
> Thanks for the report.
> 
> I hear where you're coming from about this being difficult to pinpoint -- without context, this will be difficult to reproduce / to debug. Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

This should be the same problem as https://github.com/electron/electron/issues/24434

**Comment by codebytere** [comment]
Closing as dup of https://github.com/electron/electron/issues/24434
