### ISSUE TITLE
Electron Quitting on Raspberry Pi Zero W

### ISSUE THREAD

**Issue by Marcus-C137** [electron/electron#24726]
Running electron app on Raspberry Pi Zero W just exits with code 0. Alot of people would like to run electron on the raspberry pi zero w, but there hasn't been much success. Chromium runs, Node runs, I think it's possible to get this up and running with a little love.

What had happened was: 

Electron installed successfully ( with arch=-armv7l )

Running `npm run start_pi`

(start_pi command)
`"start_pi": "export ELECTRON_ENABLE_LOGGING=true && ELECTRON_ENABLE_STACK_DUMPING=true && electron ./src/ElectronJS/electron.js"`

with node logging returns: 
```
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start_pi' ]
npm info using npm@6.7.0
npm info using node@v11.15.0
npm verb run-script [ 'prestart_pi', 'start_pi', 'poststart_pi' ]
npm info lifecycle cessabit-rasp@1.0.0~prestart_pi: cessabit-rasp@1.0.0
npm info lifecycle cessabit-rasp@1.0.0~start_pi: cessabit-rasp@1.0.0
cessabit-rasp@1.0.0 start_pi /home/pi/Cessabit_RaspPi
export ELECTRON_ENABLE_LOGGING=true && ELECTRON_ENABLE_STACK_DUMPING=true && electron ./src/ElectronJS/electron.js
npm verb lifecycle cessabit-rasp@1.0.0~start_pi: unsafe-perm in lifecycle true
npm verb lifecycle cessabit-rasp@1.0.0~start_pi: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/Cessabit_RaspPi/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
npm verb lifecycle cessabit-rasp@1.0.0~start_pi: CWD: /home/pi/Cessabit_RaspPi
npm sill lifecycle cessabit-rasp@1.0.0~start_pi: Args: [ '-c',
npm sill lifecycle   'export ELECTRON_ENABLE_LOGGING=true && ELECTRON_ENABLE_STACK_DUMPING=true && electron ./src/ElectronJS/electron.js' ]
npm sill lifecycle cessabit-rasp@1.0.0~start_pi: Returned: code: 0  signal: null
npm info lifecycle cessabit-rasp@1.0.0~poststart_pi: cessabit-rasp@1.0.0
npm verb exit [ 0, true ]
npm timing npm Completed in 4614ms
npm info ok 
```

running my code on raspberry pi 3 an app pops up and the process doesn't exit

**Comment by ckerr** [comment]
Is it specific applications, or does *no* Electron app  run on the Zero W?

For example, if you clone https://github.com/electron/electron-quick-start and run it, does it work?

**Comment by ckerr** [comment]
One other point -- it looks like Raspberry Pi Zero is a 32 bit machine. Electron discontinued 32-bit Linux support about a year and a half ago for reasons that Felix detailed [in this blog post](https://www.electronjs.org/blog/linux-32bit-support). Based on that, I'm going to close this ticket as wontfix.
