### ISSUE TITLE
Just-in-time app menu

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#24724]
### Problem Description

Keeping the app menu updated seems a particularly wasteful operation. 

In my use case I'm having to refresh the entire menu most of the times a user does something with the app, since the menu is generated in a pretty dynamic way and which items are active or which shortcuts are displayed depend on a the state of the app essentially.

Also debouncing app menu updates may lead to the user seeing a slightly incorrect menu if he/she can manage to open it before the debouncing timeout kicks in.

Lastly most of the times the app menu is refreshed that's completely wasted time because the user is probably not going to open it anyway.

### Proposed Solution

Ideally what I would want is to generate an app menu at the exact time the user requests it. Like maybe the app could initially provide the top-level labels only and then Electron could ask the app to provide the rest once the user actually requests it?

### Alternatives Considered

This is kind of implementable under Windows already if one uses a custom menubar.

Under macOS and Linux I don't see any APIs for implementing this sort of thing, the custom menubar approach doesn't really work because usually there are no window-level menubars in the first place there.

**Comment by fabiospampinato** [comment]
Does anyone know if this is implementable at all?

For my use case having this would give my app a significant performance boost, as the app menu I'm using is highly dynamic and it changes all the time.

**Comment by fabiospampinato** [comment]
It's kind of crazy, but potentially one could plot the movement of the cursors on screen, hardcode a height for the menubar (or retrieve it with some API), and update the menu only when the cursor goes over it, or something like that.

**Comment by Slapbox** [comment]
I'm not seeing any issues from this personally, but I think this is a good idea and should be addressed eventually.

**Comment by codebytere** [comment]
While I agree this is potentially useful in some instances it's not something that our team will be able to implement in the near (or medium-term) future, and also isn't currently possible to implement cross-platform owing to cross-platform limitations.

If you'd like to make a PR for this request we would welcome that but in the meantime I'm going to go ahead and close this out.
