### ISSUE TITLE
Mac OS Big Sur spawn mkdir failed

### ISSUE THREAD

**Issue by zinne** [electron/electron#24729]
Hi all,
 I discovered in forthcoming Mac OS Big Sur that creating a folder in the userData path is not working anymore (Catalina works). Has anybody experienced the same? (electron version 4.1.4)

`spawn('mkdir', [someFolderName])`

**Comment by ckerr** [comment]
Thanks for the report!

@MarshallOfSound has an umbrella ticket for [macOS Big Sur / Electron](https://github.com/electron/electron/issues/24319), so I've added this item to that list so that it can be tracked there.

**Comment by ckerr** [comment]
Also, Electron 4.1.4 is no longer supported -- in fact, it's *really* far past [end-of-life](https://www.electronjs.org/docs/tutorial/support#currently-supported-versions). You should consider upgrading to a newer version of Electron :slightly_smiling_face:

**Comment by cj506817364** [comment]
i need mkdir /data, help
system os: mac big sur
