### ISSUE TITLE
fix_remove_unused_llhttp_variables.patch is wrong

### ISSUE THREAD

**Issue by PF4Public** [electron/electron#24721]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.1.*

### Expected Behavior
Electron compiles successfully

### Actual Behavior
Electron compilation fails

### To Reproduce
The patch [fix_remove_unused_llhttp_variables.patch](https://github.com/electron/electron/blob/v9.1.0/patches/node/fix_remove_unused_llhttp_variables.patch) removes some of the blobs, but they are needed for compilation.
For example:
https://github.com/electron/electron/blob/a822d2639a9c9c2c670e91d73f78e921865ce38e/patches/node/fix_remove_unused_llhttp_variables.patch#L33-L35

Is used below:
https://github.com/nodejs/node/blob/9622fed3fb2cffcea9efff6c8cb4cc2def99d75d/deps/llhttp/src/llhttp.c#L1685

Thus compilation fails.

Proper fix would have been to enclose these blobs in `#ifdef __SSE4_2__ #endif`

### Additional Information
@codebytere

**Comment by codebytere** [comment]
@PF4Public can you please elaborate on what you mean? Provide a reproducible version? Operating system? Electron compiles and passes tests on 9 per CI, so i'm not sure what you mean here.

**Comment by PF4Public** [comment]
> what precisely is "compilation fails" means

It means that compiling electron on a system with a CPU that does support SSE4.2 this part of sources gets enabled:

```
      #ifdef __SSE4_2__
      if (endp - p >= 16) {
        __m128i ranges;
        __m128i input;
        int avail;
        int match_len;
      
        /* Load input */
        input = _mm_loadu_si128((__m128i const*) p);
        ranges = _mm_loadu_si128((__m128i const*) llparse_blob7);
```

and fails the compilation due to the patch mentioned.

**Comment by codebytere** [comment]
ah - it transpires that does not get tested on our end automatically.  Thanks for the clarity - i'll get a fix up soon!

**Comment by PF4Public** [comment]
Just for a reference
In a recent version of node, that file looks like [this](https://github.com/nodejs/node/blob/master/deps/llhttp/src/llhttp.c):
```c
#ifdef __SSE4_2__
static const unsigned char ALIGN(16) llparse_blob7[] = {
  0x9, 0x9, ' ', '~', 0x80, 0xfe, 0x0, 0x0, 0x0, 0x0, 0x0,
  0x0, 0x0, 0x0, 0x0, 0x0
};
#endif  /* __SSE4_2__ */
```
and so on

**Comment by codebytere** [comment]
yep - i'm going to apply this: https://github.com/nodejs/llparse/commit/7da43fb9af14a16124bcb9d2c9f700a4f3d5fee0.patch

**Comment by PF4Public** [comment]
Reopening issue, which was not fixed; self-assigning and marking as fixed.
Brilliant!
