### ISSUE TITLE
self.module.paths is not set in Worker when loading via loadURL

### ISSUE THREAD

**Issue by lgrahl** [electron/electron#24735]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.1.1
* **Operating System:**
  * Linux x64

### Expected Behavior

`self.module.paths` should be set in a Worker by its parent (the renderer).

`require` should be able to load modules in the same way as the parent.

### Actual Behavior

`self.module.paths` in the Worker is not set when loading it from a renderer that has been loaded via `loadURL`. Hence, `require` cannot find any modules.

However, `self.module.paths` is set correctly in the Worker when loading it from a renderer that has been loaded via `loadFile`.

### To Reproduce

```sh
$ git clone https://github.com/lgrahl/electron-node-integration-service-worker-crash -b worker-module-paths
$ npm install
$ npx http-server
$ npm start
```

Commit https://github.com/lgrahl/electron-node-integration-service-worker-crash/commit/14a53e7162058574b2238d1c896a7bb6f554d36f

**Comment by Obi-Dann** [comment]
Also having the same problem when running electron with electron-webpack in dev mode. It looks like `paths` are never set in worker init when protocol is not `file:///`
https://github.com/electron/electron/blob/ba55aaa53b26c5aed9d4b3f07a0ba795d33d6c91/lib/worker/init.ts#L30-L34
but they're set in renderer using `appPath`
https://github.com/electron/electron/blob/ba55aaa53b26c5aed9d4b3f07a0ba795d33d6c91/lib/renderer/init.ts#L145-L148
Maybe something similar can be done in worker?

**Comment by lgrahl** [comment]
Hi. Just wanted to let you know, this is still an issue in 13.1.4. The workaround we're using is a bit unfortunate because it requires a dynamic import but it works at least:

```ts
import * as path from 'path';

// TODO: Remove workaround for
//       https://github.com/electron/electron/issues/24735
const parts = __dirname.split(path.sep);
let part: string | undefined;
while ((part = parts.pop()) !== undefined) {
    if (part === 'node_modules') {
        parts.push(part);
        break;
    }
}
if (parts.length === 0) {
    throw new Error('Unable to determine base path!');
}
self.module.paths = [parts.join(path.sep)];

// We need to use a dynamic import here because `self.module.paths` needs to
// be set prior to the import chain
const {main} = await import('../backend-worker');
main();
```

**Comment by codebytere** [comment]
@lgrahl just popped up a PR for this - should be fixed before long!
