### ISSUE TITLE
print and printToPDF don't work on Windows local network

### ISSUE THREAD

**Issue by EricExm** [electron/electron#24734]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * Tried version 9.1.0, 9.1.1
* **Operating System:**
  * Windows 10 pro (1909) x64 
* **Last Known Working Electron version:**
  * 4.0.6

### Expected Behavior
Prints window's web page or Prints window's web page as PDF.

### Actual Behavior
On Hard Disk (D:\DirName\electron.exe) : print is ok and PDF is created
On local network (\\WindowsServer\ShareName\DirName\electron.exe):
- print -> open choose printer dialog, choose a printer then nothing happens
- pdf -> error reported : Failed to generate PDF

### To Reproduce
**PRINT**

```js
const electron = require('electron')
const {dialog} = require('electron')
const app = electron.app
const BrowserWindow = electron.BrowserWindow
const fs = require('fs')

let mainWindow

function createWindow () {
	mainWindow = new BrowserWindow({width: 800, height: 600, fullscreen: false,  center: true,
			webPreferences: {
            nodeIntegration: true
        }})
	mainWindow.loadURL('http://github.com')

	mainWindow.webContents.on('did-finish-load', () => {
		  // Use default printing options
		mainWindow.webContents.print({}, (success, errorType) => {
			if (!success) {
				dialog.showErrorBox("Print error", errorType.message)
			} else dialog.showMessageBox({ type: 'info', title: 'Print', message: 'ok' })
		})
	})
	mainWindow.on('closed', function () {
		mainWindow = null
	})
}
app.on('ready', createWindow)

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', function () {
  if (mainWindow === null) {
    createWindow()
  }
})
```

**PRINT TO PDF**

```js
const electron = require('electron')
const {dialog} = require('electron')
const app = electron.app
const BrowserWindow = electron.BrowserWindow
const fs = require('fs')

let mainWindow

function createWindow () {
	mainWindow = new BrowserWindow({width: 800, height: 600, fullscreen: false,  center: true,
			webPreferences: {
            nodeIntegration: true
        }})
	mainWindow.loadURL('http://github.com')

	mainWindow.webContents.on('did-finish-load', () => {
	  // Use default printing options
	  mainWindow.webContents.printToPDF({}).then(data => {
		fs.writeFile('print.pdf', data, (error) => {
		  if (error) throw error
		  dialog.showMessageBox({ type: 'info', title: 'PDF', message: 'Fichier PDF ok.' })
		})
	  }).catch(error => {
        dialog.showErrorBox("Erreur", error.message)
	  })
	})
	mainWindow.on('closed', function () {
		mainWindow = null
	})

}
app.on('ready', createWindow)

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', function () {
  if (mainWindow === null) {
    createWindow()
  }
})
```

**Comment by codebytere** [comment]
@EricExm does this occur if you open Chrome on that network share and try to print to pdf there? This simply pipes through that existing logic.

**Comment by EricExm** [comment]
I'm not sure to understand (Maybe because I'm French and my English is not good). Do you mean: change `mainWindow.loadURL('http://github.com')` to `mainWindow.loadURL('file://' + __dirname + '/index.html')` ?
The result is the same.

**Comment by codebytere** [comment]
@EricExm it's like that this is not an issue with Electron, but with your local network and Chromium. What i mean is: if you open the Chrome app in your network share, _not Electron_, and try to print something, does it work?

**Comment by EricExm** [comment]
@codebytere I Don't know how open the Chrome app in my network share. Chrome is not portable.
However, this example works fine in my network share with electron 4.0.6:
`	mainWindow.loadURL('http://github.com')
	mainWindow.webContents.on('did-finish-load', () => {
		mainWindow.webContents.printToPDF({}, (error, data) => {
			if (error) throw error
			fs.writeFile('print.pdf', data, (error) => {
			  if (error) throw error
			  dialog.showMessageBox({ type: 'info', title: 'PDF', message: 'Fichier PDF ok.' })
			})
		})
	})
`

**Comment by EricExm** [comment]
After copying "C:\Program Files (x86)\Google\Chrome" directory on my network share and launching the "chrome.exe", I can't open any URL. Chrome doesn't work. **It is not portable**.
![Annotation 2020-07-31 100732](https://user-images.githubusercontent.com/68843154/89014423-c7ea0c80-d315-11ea-81a2-cbdb1c450841.png)

**Comment by EricExm** [comment]
No one has the same problem?
I have to return my project in a week but I'm stuck because I can't print from the network.
I tried at home and at work: the result is the same. Help please !

**Comment by battilo** [comment]
> No one has the same problem?
> I have to return my project in a week but I'm stuck because I can't print from the network.
> I tried at home and at work: the result is the same. Help please !

I have the same problem ... When I print from an electronic application started from local disk, it works fine.
When I print from the same application started from the local network, the print remains on "spooling in progress" and ends when I close the application... but print is empty

**Comment by booscaaa** [comment]
> > No one has the same problem?
> > I have to return my project in a week but I'm stuck because I can't print from the network.
> > I tried at home and at work: the result is the same. Help please !
> 
> I have the same problem ... When I print from an electronic application started from local disk, it works fine.
> When I print from the same application started from the local network, the print remains on "spooling in progress" and ends when I close the application... but print is empty

I'm to. Exactly the same problem...

**Comment by studiochris** [comment]
I've noticed this issue as well. If the application is launched from a local disk, things work the way they're supposed to. If the application is launched from a network share (or mapped drive), printing no longer works whether it's using `webContents.print()` or `webContents.printToPDF()`. 

In older versions of Electron (5.0.0 specifically) the callback is never called (no error or data). In 10.1.3, the promise is never resolved or rejected, so `then` and `catch` don't run.

**Comment by SammyAbukmeil** [comment]
> I've noticed this issue as well. If the application is launched from a local disk, things work the way they're supposed to. If the application is launched from a network share (or mapped drive), printing no longer works whether it's using `webContents.print()` or `webContents.printToPDF()`.
> 
> In older versions of Electron (5.0.0 specifically) the callback is never called (no error or data). In 10.1.3, the promise is never resolved or rejected, so `then` and `catch` don't run.

This was the cause of the issue for me.

I was launching my application directly from a 

1. Mapped drive (between my host and the VM) on a Windows 7 VirtualBox VM
2. Network drive on an actual windows 7 machine

Both of which, print jobs got stuck in "Spooling" status.

Moving the electron app off the mapped/network drive, onto the local disk (e.g. Desktop) fixes the issue. Thanks @studiochris

**Comment by codebytere** [comment]
Our printing functionality simply pipes through that existing logic from Chromium, so if it is not possible to run Chromium than printing functionality will not work. You should expect that you need to un from local disk and not from a mapped or network drive.
