### ISSUE TITLE
Color input should show a modal dialog

### ISSUE THREAD

**Issue by duanyao** [electron/electron#2473]
In Electron, `<input type=color>` presents a non-modal color chooser dialog (at least on Windows). This behavior is not only inconsistent with other UAs (Chrome, firefox), it can also cause a real problem.

In Chrome and Electron, if an `<input type=color>` is hidden (via `hidden` attribute or `display:none`) after its color chooser dialog is shown, it won't receive `change` event (this is probably a blink's bug). 

In one of my app, an `<input type=color>` lives in a menu, which will be hidden on a `mouseleave` event. So if the color chooser dialog is non-modal, after the dialog is shown user moves mouse to the dialog and leave the menu, the menu hides and the `<input type=color>` won't receive `change`.

This problem can be reproduced by the following code:

```html
<input type="color" style="position:absolute; right:0"></input>

<script>
var input = document.querySelector('input');

input.onchange = function(ev) {
	document.body.style.backgroundColor = ev.target.value;
};
input.onmouseleave = function(ev) {
	//ev.target.hidden = true;
	ev.target.style.display = 'none';
}
</script>
```

You can change the background color of the page by using the color input in Chrome and Firefox, but not Electron.

**Comment by Tyriar** [comment]
Cannot reproduce on Ubuntu on master; the dialog is modal.

**Comment by zcbenz** [comment]
Unable to reproduce on 0.37.x anymore.
