### ISSUE TITLE
dark mode titlebar not honored on Linux in Electron 10.0.0-beta.1 and up

### ISSUE THREAD

**Issue by ckerr** [electron/electron#24741]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.0.0-beta.1
* **Operating System:**
  * Ubuntu 19.10
* **Last Known Working Electron version:**
  * 9.1.1

### Expected Behavior

Window titlebar should honor the desktop theme settings.

### Actual Behavior

Window titlebar does not honor the desktop theme settings.

### To Reproduce

Reproduces with electron-quick-start.

### Screenshots

Screenshot includes electron-quick-start running on 9.1.1, 10.0.0-beta.1, and a non-Electron app for comparison.

Description for users not familiar with this desktop: all three titlebars should have the same background color, with the focused one having brighter text color. The 10.0.0-beta.1 window should be black, not grey.

![2020-07-27T12:38:34-Screenshot-675x935](https://user-images.githubusercontent.com/70381/88573834-f9599400-d006-11ea-8693-2660f05ff6a6.png)

**Comment by MarshallOfSound** [comment]
Refs: https://github.com/electron/electron/pull/20138
