### ISSUE TITLE
focus() not working

### ISSUE THREAD

**Issue by pjebs** [electron/electron#24751]
* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  9.1.1
* **Operating System:**
  mac 10.13.6 (High Sierra)
* **Last Known Working Electron version:**
  no idea

I have a browserwindow that is already open but not focussed.
When I call `.focus()` on it, it doesn't do anything.
When I changed it to `.show()` it works.

See: https://github.com/rocketlaunchr/electron-alert/blob/master/src/alert.js#L327

**Comment by ckerr** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unneccessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you've responded, please link to the test case and @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by pjebs** [comment]
i already provided a "example" project: https://github.com/rocketlaunchr/electron-alert/blob/master/src/alert.js#L327

Just npm install `electron-alert` on any project and you will see the issue.
