### ISSUE TITLE
Packages cannot be selected in <input file="type"> file selector on macOS

### ISSUE THREAD

**Issue by simoncozens** [electron/electron#24755]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** v9.0.4
* **Operating System:** mac OS 10.14.6
* **Last Known Working Electron version:**:  2.0.2

### Expected Behavior

[Document packages](https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/DocumentPackages/DocumentPackages.html#//apple_ref/doc/uid/10000123i-CH106-SW1) should be selectable in an `<input type="file">`. (As they are in Firefox, Safari and Chrome.)

### Actual Behavior

Packages cannot be selected in an `<input type="file">`.

### Additional Information

This is the exact opposite of #13219. Sometimes you *do* want the user to be able to choose a package file - not for apps, perhaps, but certainly for `.pkg`, old-style or large `.pages`, `.keynote` and `.numbers` files, or in the case I'm working with, `.ufo` font source files. Currently, if I have `<input type="file" accept=".ufo"/>`, I can't select the package itself because the dialog opens it as a directory and shows the contained files, and if I have `<input type="file" accept=".ufo" directory/>`, I can't select the package itself because the dialog treats it as a file and not a directory! 🤷

#13220, which addressed #13219, decided to "patch out the broken behavior and look into getting the optimum behavior later". But I don't think it was ever looked into.

**Comment by ckerr** [comment]
(Am I reading between the lines correctly that you're upgrading an app from Electron 2 to Electron 9?! That's impressive! :1st_place_medal:)

TBH I am not very familiar with this piece of the code. It looks like @miniak and @MarshallOfSound did the work on #13219 / #13220, so pinging them here for eyeballs, but I @simoncozens I also wanted to ask you if it would be possible to write an isolated test case, e.g. from a fork of [electron-quick-start](https://github.com/electron/electron-quick-start).

Ordinarily a repro request gets the `blocked/needs-repro` label but I'd like @miniak or @MarshallOfSound to have a chance to sound off on whether the existing info is enough.

**Comment by simoncozens** [comment]
> (Am I reading between the lines correctly that you're upgrading an app from Electron 2 to Electron 9?! That's impressive! 🥇)

No, I just meant that it would have worked as of #9834. 

> TBH I am not very familiar with this piece of the code. It looks like @miniak and @MarshallOfSound did the work on #13219 / #13220, so pinging them here for eyeballs, but I @simoncozens I also wanted to ask you if it would be possible to write an isolated test case, e.g. from a fork of [electron-quick-start](https://github.com/electron/electron-quick-start).
> Ordinarily a repro request gets the `blocked/needs-repro` label but I'd like @miniak or @MarshallOfSound to have a chance to sound off on whether the existing info is enough.

Happy to do that but it seems like overkill. Paste this into the index.html of Electron Fiddle:

```
<h2>This doesn't work</h2>
<input type="file" accept=".ufo"/>
<h2>But equally neither does this</h2>
<input type="file" accept=".ufo" directory webkitdirectory/>
```

and try to open a .ufo file on OS X. You can get a UFO font from here: https://github.com/fonttools/ufoLib2/tree/master/tests/data/UbuTestData.ufo

**Comment by codebytere** [comment]
@simoncozens i'll take a look soonish when i can!

**Comment by simoncozens** [comment]
Thank you very much!
