### ISSUE TITLE
My window isn't loading

### ISSUE THREAD

**Issue by DeltaStudioApp** [electron/electron#24767]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  9.1.1 (also tested in 8.2.4 and 9.0.4)
* **Operating System:**
  Windows 10 2004
* **Last Known Working Electron version:**
  

### Expected Behavior
The window loads fine, and the devtools too

### Actual Behavior
The window doesn't load, i can't write to the devtools.

### To Reproduce
Clone https://github.com/DeltaStudioApp/Delta-Studio

git clone REPO
npm install
npm start

### Additional Information
The other windows load fine, and the HTML file can be loaded just fine in the browser. Also if i load the file in other window, the same happens

**Comment by nornagon** [comment]
Can you reproduce this using [electron fiddle](/electron/fiddle)? Unfortunately a whole app is too large for us to spend time to track down what might be going wrong.

**Comment by DeltaStudioApp** [comment]
I'll try!

**Comment by DeltaStudioApp** [comment]
No, I can't reproduce. My app has too many assets and dependencies, so I can't :(
