### ISSUE TITLE
Attempting to call a function in a renderer window that has been closed or released

### ISSUE THREAD

**Issue by kaysonwu** [electron/electron#24772]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  9.1.0

* **Operating System:**
  Windows 10

* **Last Known Working Electron version:** 
 9.1.0

### Expected Behavior

No warn.

### Actual Behavior

Has warn.

### To Reproduce

1.  First, get the bug replay code:

```sh
$ git clone https://github.com/kaysonwu/electron-quick-start -b master
$ yarn install
$ yarn dev
```

2. When the program is running, modify the window event callback function in the `index.tsx` file

```tsx
...
useEffect(() => {
    currentWindow.on('maximize', () => {
      // ...
      console.log('maximized', 'true');
    });
  }, []);
```

3. Double click the window title bar

4. Return to the vscode terminal and see the warning

### Screenshots
![QQ截图20200729110017](https://user-images.githubusercontent.com/14865584/88751888-2afb6800-d18b-11ea-9230-761d32cf5416.png)

### Additional Information

Same: #6247, #15676, #6247

**Comment by kaysonwu** [comment]
This warning will only appear when I modify the file and then trigger the event.

**Comment by VerteDinde** [comment]
Hey @kaysonwu, thanks for reporting this issue. It looks like you have both the Current Electron Version and Last Working Version as the same (Electron 9.1.0). Is this correct, or do you know the last working version?

**Comment by kaysonwu** [comment]
I don't quite understand what you mean @VerteDinde

**Comment by icecream17** [comment]
bump

**Comment by icecream17** [comment]
bump

**Comment by icecream17** [comment]
It doesn't seem like this issue happens with newer versions of electron (I don't know if that's the actual reason, just that the error doesn't appear here:)
https://github.com/pulsar-edit/github/actions/runs/3856736375/jobs/6573306353
