### ISSUE TITLE
Adding a MenuItem with a CommandOrControl+W accelerator will prevent "About AppName" to close on macOS

### ISSUE THREAD

**Issue by dmnsgn** [electron/electron#24777]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.5
* **Operating System:**
  * macOS 10.15.6

### Expected Behavior

[MenuItem](https://www.electronjs.org/docs/api/menu-item#new-menuitemoptions ) docs says:

> browserWindow BrowserWindow | undefined - This will not be defined if no window is open.

Any opened and focused window created by Electron should be closable with accelerator.

### Actual Behavior

An error occurs and the About window can't be closed with keyboard shortcut (clicking red x works). In other words, the **Menu item click callback doesn't receive the About window as focused window in its second argument.**

### To Reproduce

See Electron Fiddle: https://gist.github.com/087a1cb3564c9ece5047b57fc9626872

Setup the following menu:
```js
  const APP_NAME = 'APP_NAME'
  Menu.setApplicationMenu(Menu.buildFromTemplate([
    {
      label: APP_NAME,
      submenu: [
        {
          label: `About ${APP_NAME}`,
          role: 'about',
        },
      ]
    },
    {
      label: 'File',
      submenu: [
        {
          label: 'Close',
          // Don't use role custom in order to handle close logic manually
          // role: 'close',
          accelerator: 'CommandOrControl+W',
          click(_, focusedWindow) {
            // Issue: focusedWindow is undefined when trying to close "About APP_NAME" with keyboard accelerator
            focusedWindow.close()
          },
        },
      ],
    },
  ]))
```

### Screenshots

<img width="800" alt="Screenshot 2020-07-29 at 11 30 39" src="https://user-images.githubusercontent.com/1636460/88789715-f8536e80-d18e-11ea-82c3-bf5d2c250ccb.png">

**Comment by codebytere** [comment]
@dmnsgn this is to some extent expected behavior - the About window is _not_ a BrowserWindow. I'll see what i can do about it but per our documentation this is, technically speaking, not a bug.

**Comment by dmnsgn** [comment]
Out of curiosity, what kind of window is it then?
Is making it a BrowserWindow or tracking its focus state something you could consider as feature request though?
