### ISSUE TITLE
Issue with saving crash reports for node child processes with breakpad

### ISSUE THREAD

**Issue by deepak1556** [electron/electron#24779]
This is follow-up to https://github.com/electron/electron/pull/24778

1) There is no path service in the node child process, so we can't extract the preferred crash path from `DIR_CRASH_DUMPS` and will default to `/tmp` https://source.chromium.org/chromium/chromium/src/+/master:components/crash/core/app/breakpad_linux.cc;l=814. A solution here would be to add a `crashDirectory` parameter for `process.crashReporter.start`.

2) When the process is forked with `silent: true` or spawned with io fds piped to parent the local crash dumping won't work, since we treat `node` process as a standalone browser process type for crash dumping. We should instead treat the process nature depending on the type of io available. In which case, under these scenarios it would be similar to how other chromium child process dump crashes using `CrashHandlerHostLinux`

**Comment by vyunikov** [comment]
I am not sure whether it's a correct issue to post in, but in electron 10.1.3 `crashReporter` is not monitoring crashes in a child process created using `child_process` module. 
Is there a way to make it work? 
Is there any ongoing work with regards to the above?

Thanks in advance

**Comment by vyunikov** [comment]
For anybody having a similar problem, in my case the issue was that I specified environment variables which I expected to be set like this:
```
childProc = fork(path.join(__dirname, '../..', 'child'), null, {
            env: { ELECTRON_RUN_AS_NODE: 'true' },
          });
```

This way parent process env vars don't get passed to a child, but electron passes a pipe name with env. 
This works for me:
```
childProc = fork(path.join(__dirname, '../..', 'child'), null, {
            env: { ...process.env, ELECTRON_RUN_AS_NODE: 'true' },
          });
```
