### ISSUE TITLE
How to send video stream(front-end render processes) to node.js (main processes)? (Video recording)

### ISSUE THREAD

**Issue by tak40548798** [electron/electron#24776]
### Problem Description
I implemented the recording function in my application

I get the video stream from the video element tag(MediaRecorder api) of the front-end (renderer processes)

How to send video stream(front-end render processes) to node.js (main processes)

When the "video stream" received by "node.js (main processes)" accumulates to a certain size, it is written into the filesystem

sorry i used translation
my english is bad

**Comment by sheminanto** [comment]
async function writeStream(stream) {
  var options = {
    mimeType: "video/webm; codecs=vp9",
  };
  mediaRecorder = new MediaRecorder(stream, options);

  mediaRecorder.ondataavailable = handleDataAvailable;
  mediaRecorder.onstop = handleStop;

  const startBtn = document.getElementById("startBtn");
  startBtn.onclick = (e) => {
    mediaRecorder.start();
    startBtn.classList.add("is-danger");
    startBtn.innerText = "Recording";
  };

  const stopBtn = document.getElementById("stopBtn");
  stopBtn.onclick = (e) => {
    mediaRecorder.stop();
    startBtn.classList.remove("is-danger");
    startBtn.innerText = "Start";
  };

  // Captures all recorded chunks
  async function handleDataAvailable(e) {
    console.log("video data available");
    recordedChunks.push(e.data);
  }

  async function handleStop(e) {
    const blob = new Blob(recordedChunks, {
      type: "video/webm; codecs=vp9",
    });

    const buffer = Buffer.from(await blob.arrayBuffer());

    const filePath = "./test3.webm";

    console.log(filePath);

    writeFile(filePath, buffer, () => console.log("video saved successfully!"));

    stream.getTracks().forEach((track) => {
      track.stop();
      console.log("hello finished");
    });
  }
}

**Comment by tak40548798** [comment]
Thanks for your answer
But when the video file is too large (recorded blocks)
Does the writeFile() method take up a lot of memory?

So I use fs.createReadStream() method and call wite() to write the file

But I found a problem
When I call writerStream.end() method

I can no longer use the writerStream object to write files
I cannot use it even if I re-declare it

The code snippet is as follows
![code](https://i.imgur.com/Ow245xK.png)

**Comment by sheminanto** [comment]
async function writeStream(stream) {


  var options = {
    mimeType: "video/webm; codecs=vp9",
  };
  mediaRecorder = new MediaRecorder(stream, options);

  mediaRecorder.ondataavailable = handleDataAvailable;
  mediaRecorder.onstop = handleStop;

  const startBtn = document.getElementById("startBtn");
  startBtn.onclick = (e) => {
    streamsav = fs.createWriteStream("file.webm");
    mediaRecorder.start(1000);
    startBtn.classList.add("is-danger");
    startBtn.innerText = "Recording";
  };

  const stopBtn = document.getElementById("stopBtn");
  stopBtn.onclick = (e) => {
    try {
      mediaRecorder.stop();
    } catch (error) {
      console.log(error);
    }

    startBtn.classList.remove("is-danger");
    startBtn.innerText = "Start";
  };

  // Captures all recorded chunks
  async function handleDataAvailable(e) {
    console.log("video data available");
    recordedChunks.push(e.data);
    const blob = new Blob(recordedChunks, {
      type: "video/webm; codecs=vp9",
    });

    const buffer = Buffer.from(await blob.arrayBuffer());
    streamsav.write(buffer);
    recordedChunks = [];
  }

  async function handleStop(e) {

    console.log("hello finished");
  }
}

//  createwritestream will automatically close by default
