### ISSUE TITLE
webgl is null in webview but exist in browserWindow

### ISSUE THREAD

**Issue by cadiron** [electron/electron#24789]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  * v8.3.0

* **Operating System:** 
  * windows 7 / windows10

* **Last Known Working Electron version:** 
  * v4.x.x

### Expected Behavior

i hope open webgl in webview

### Actual Behavior

i debug in devtool and input document.createElement('canvas').getContext("webgl").but i get null

### Screenshots

![lALPBFRybphhjyrNA8vNBcw_1484_971](https://user-images.githubusercontent.com/18716986/88877899-2d2bf800-d259-11ea-9d1e-27b0507770a8.png)

**Comment by miniak** [comment]
Cannot reproduce this
