### ISSUE TITLE
Close child BrowserWindow after open a file selector in it, changes the z-order of the mainWindow

### ISSUE THREAD

**Issue by etobdc** [electron/electron#24795]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.1.2
* **Operating System:**
  * Windows 10 (2004)
* **Last Known Working Electron version:**
  * 

### Expected Behavior

After open and close the file selector in a child BrowserWindow and close it , don't change the z-order of the mainWindow

### Actual Behavior

When you close the child BrowserWindow after open a file selector in the child,  the z-order of mainWindow is changed and if you have another program open in the desktop the mainWindow will go behind it

### To Reproduce

To see and test the example, open this with Electron Fiddle:
https://gist.github.com/c374eab58db751c6154ea7ee8ce65be8

Steps to reproduce from zero:
- Set a child BroserWindow for the mainWindow
- Include a input type file - file selector - in the child
- Start the electron
- Open the child
- Open the file selector (is indifferent if you select something or not)
- Close the file selector
- Close the child
- You will see the mainWindow changes the z-order - if have another program open in the desktop the mainWindow will go behind it

### Additional Information

I have tried to set alwaysOnTop on the mainWindow and it works, but is only a workarround and is not a sollution for the problem.
I have tried call the function moveTop to the mainWindow after close the child, it works too but you can "see" the mainWindow going behind the another program and then back to the top of the desktop, if you try to set the child as a modal the same thing happen

- You can see more about the alwaysOnTop here https://www.electronjs.org/docs/api/browser-window#new-browserwindowoptions
- And more about moveTop() here https://www.electronjs.org/docs/api/browser-window#winmovetop

**Comment by axelkovacki** [comment]
The same here :S

**Comment by shelontwo** [comment]
I have the same problem!
