### ISSUE TITLE
The power monitoring callback function will be triggered twice, in electron 8.4.0

### ISSUE THREAD

**Issue by renhaoweixiao** [electron/electron#24793]
`const { app, powerMonitor } = require('electron')

app.on('ready', () => {
  powerMonitor.on('suspend', () => {
    console.log('The system is going to sleep')
  })
})`

The system is going to sleep
The system is going to sleep

**Comment by sevilen** [comment]
the same #24803

**Comment by codebytere** [comment]
Closing as duplicate of https://github.com/electron/electron/issues/24803
