### ISSUE TITLE
Cant use WHATWG URL as path for fs functions in the renderer

### ISSUE THREAD

**Issue by VVishion** [electron/electron#24794]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.1.2
* **Operating System:**
  * Windows 10 (1903)
* **Last Known Working Electron version:**
  * 

### Expected Behavior
In the renderer process `fs` functions (such as `fs.readFile` or `fs.createReadStream`) should work with `WHATWG URL`s with "file://" protocol as path argument.

### Actual Behavior
Works fine in the main process.
Throws `Uncaught TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type object` in the renderer.

### To Reproduce
Fiddle Gist: https://gist.github.com/7cc7f0c54eef26ad5239e7f0712b605c

**Comment by codebytere** [comment]
@VVishion i'll look into this but for now just adding `const { URL } = require('url')` fixes the issue in the renderer.
