### ISSUE TITLE
Frameless Window On MACOS11 (BigSur) closed by hidden titlebar.

### ISSUE THREAD

**Issue by bsxz0604** [electron/electron#24792]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
Electron 9.1.1 
* **Operating System:**
macos11 (BigSur) 

### Expected Behavior
can not close page when titlebar is hidden。

### To Reproduce
Just use Quick Start app demo to change `frame: false` when new BrowserWindow.

### Screenshots
![Screen Recording 2020-07-28 at 17 54 55_pOioiiB7J0](https://user-images.githubusercontent.com/16715798/88888463-eea23780-d270-11ea-8a17-c1d6b4de9d85.gif)

**Comment by VerteDinde** [comment]
Hey @bsxz0604, thanks for reporting this issue and leaving clear repro steps. Are you also seeing this issue in newer versions of MacOS, such as Catalina and Mojave, or is this restricted to Big Sur?
