### ISSUE TITLE
Allow us to discover what window opened the current window

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#24807]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
When a window is opened, I would like to know what window opened it.

For example if the window with ID 1 triggered a `window.open` call, I'd like to know that the window with ID 2 was opened by window 1.

Currently, the `referrer` information passed to the `new-window` handler only contains a URL property (which in my case is always `''` for some reason).

### Proposed Solution
Can the `referrer` argument get an additional property that tells us the ID of the window that's making the `window.open` call?
(I'm not sure how this will fit into the new `setWindowOpenOverride` mechanism)

Alternatively, maybe the `BrowserWindow` class can have an `openerWindowId` type of property that gives us this information. That would maybe be preferable.

### Alternatives Considered
I can work around it by passing in the window ID like so:

```
// ... inside of the browser-window-created handler
window.webContents.addListener("new-window", function (): void {
	[].push.call(arguments, window.id);
	newWindowHandler.apply(null, arguments);
});
```

**Comment by Plastikmensch** [comment]
If I'm understanding correctly, you can already do that by combining the browser-window-created and new-window event
Example:
```
app.on('browser-window-created', (event, win) => {
    win.webContents.on('new-window', () => {
        console.log('${win.id} opened a new window`)
    }
}
```
You can also get the id of the new window by creating it yourself.
Opening new windows by default is not a good idea.

**Comment by pushkin-** [comment]
@Plastikmensch Yes, that's solution I proposed at the end. But I would prefer a simple property that would tell me the opener window rather than doing what I did.

In my situation, I do want to allow windows to open windows by default.
