### ISSUE TITLE
Review code signing guidance

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#24806]
Apparently we may not need `com.apple.security.cs.allow-unsigned-executable-memory` anymore in recent versions of Electron.

Someone should validate whether thats correct and update the document accordingly

Refs: https://www.electronjs.org/docs/tutorial/code-signing#:~:text=allow-unsigned-executable-memory

**Comment by kewde** [comment]
We were able to run the latest version of electron 14.1.1 without the `allow-unsigned-executable-memory` on Mac OS Monterey.
