### ISSUE TITLE
powerMonitor "lock-screen" event not firing on Ubuntu 20.04.

### ISSUE THREAD

**Issue by johannesjo** [electron/electron#24800]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 9.1.2
* **Operating System:** Ubuntu 20.04 x64 

### Expected Behavior
```
powerMonitor.on('lock-screen') 
```
should fire when lock screen is triggered.

### Actual Behavior
it does not.

### To Reproduce
```
appIN.on('ready', () => {
  powerMonitor.on('lock-screen', () => {
    console.log('PLEASE SAY SOMETHING');
  });
});
```

### Additional Information
Full failing example can be found here:
https://github.com/johannesjo/super-productivity/blob/cea16a0f5cbddac2ff7fda8b391dea16e03c5f39/electron/main.ts#L140

**Comment by codebytere** [comment]
This is not a bug - it's not supported per our documentation:

https://github.com/electron/electron/blob/4290555a0d9dacc4ba46650cd2b1d5baca0e2467/docs/api/power-monitor.md#L34-L41

**Comment by johannesjo** [comment]
Oh. You're right. Didn't catch that. Is this a limitation brought by chromium?
