### ISSUE TITLE
Automatic update

### ISSUE THREAD

**Issue by mprofit-host** [electron/electron#24813]
// Step 1: Use `publishConfig` option in your package.json
"publishConfig": { "registry": "https://npm.pkg.github.com/" }
// Step 2: Authenticate
$ npm login --registry=https://npm.pkg.github.com/

// Step 3: Publish
$ npm publish

**Comment by diala-star** [comment]
> // Step 1: Use `publishConfig` option in your package.json
> "publishConfig": { "registry": "https://npm.pkg.github.com/" }
> // Step 2: Authenticate
> $ npm login --registry=https://npm.pkg.github.com/
> 
> // Step 3: Publish
> $ npm publish
