### ISSUE TITLE
Add support for sha3_224, sha3_256, sha3_384 and sha3_512

### ISSUE THREAD

**Issue by CodeDead** [electron/electron#24812]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
[#16195](https://github.com/electron/electron/issues/16195#issuecomment-460380616) and [#issuecomment-636437206 ](https://github.com/electron/electron/issues/19327#issuecomment-636437206) indicates that if we require more cryptographic algorithms in the `crypto` module, we should open a feature request.

If possible and feasible, could the following algorithms be added to the `crypto` module:
* sha3_224
* sha3_256
* sha3_384
* sha3_512

### Proposed Solution
Making the specified algorithms available in the `crypto` module in electron.

### Alternatives Considered
N/A

### Additional Information
Electron v9.1.2 supports the following algorithms out of the box:
* md4
* md5
* ripemd160
* sha1
* sha224
* sha256
* sha384
* sha512

It might be time to phase out MD4 in favour of the SHA3 family.

**Comment by prettydiff** [comment]
There isn't any good reason for Electron to fail on use of SHA3 in 2022.

**Comment by CodeDead** [comment]
bump

**Comment by nornagon** [comment]
BoringSSL doesn't support SHA-3 and isn't likely to (see [this blog post by Adam Langley, one of the core BoringSSL developers](https://www.imperialviolet.org/2017/05/31/skipsha3.html)), so I'm closing this as "won't fix". If BoringSSL changes their stance and implements SHA-3 then we can reconsider.

**Comment by tranquilpuma830** [comment]
bump

I encountered an error while launching my application on an electron
(node:68017) UnhandledPromiseRejectionWarning: Error: Digest method not supported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at shake256
    
    crypto.createHash('shake256', { outputLength: outputBytes }).update(data).digest('hex');
    
Is there any information on how to fix it?

**Comment by prettydiff** [comment]
@tranquilpuma830 It seems you have to drop shake256 because it is not supported by BoringSSL, which is the crypto utility used by Electron or you are forced to drop Electron in favor of an alternative that does support shake256.  See the list of supported hash algorithms at top of this issue.

**Comment by CodeDead** [comment]
In that regard, we decided to drop Electron and move over to Tauri. No regrets.
