### ISSUE TITLE
Error messages related to typescript with electron.d.ts

### ISSUE THREAD

**Issue by marcoippolito** [electron/electron#24829]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

I first created a brand new vue.js project with @vue/cli : https://vuejs.org/v2/guide/typescript.html

      vue create newproject

during the creation process, I chose typescipt option.

Then, I installed electron-builder plugin: https://nklayman.github.io/vue-cli-plugin-electron-builder/guide/#installation

    vue add electron-builder

executing yarn electron:serve the brand new app seems working:

![image](https://user-images.githubusercontent.com/3073209/89306720-8b4d4680-d670-11ea-94a8-e02d16fc8789.png)

but I get tens of errors which seem to be related to typescript with electron.d.ts :  
[vue-cli-typescript-electronErrorMessages.txt](https://github.com/electron/electron/files/5022728/vue-cli-typescript-electronErrorMessages.txt)

    (base) marco@pc01:~/webMatters/electronMatters/ggc-new$ vue info
    vue info

    Environment Info:

      System:
        OS: Linux 5.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
        CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
      Binaries:
        Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
        Yarn: 1.22.4 - /usr/bin/yarn
        npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
      Browsers:
        Chrome: 84.0.4147.105
        Firefox: 79.0
      npmPackages:
        @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
        @vue/babel-plugin-transform-vue-jsx:  1.1.2 
        @vue/babel-preset-app:  4.4.6 
        @vue/babel-preset-jsx:  1.1.2 
        @vue/babel-sugar-functional-vue:  1.1.2 
        @vue/babel-sugar-inject-h:  1.1.2 
        @vue/babel-sugar-v-model:  1.1.2 
        @vue/babel-sugar-v-on:  1.1.2 
        @vue/cli-overlay:  4.4.6 
        @vue/cli-plugin-babel: ~4.4.0 => 4.4.6 
        @vue/cli-plugin-e2e-cypress: ~4.4.0 => 4.4.6 
        @vue/cli-plugin-eslint: ~4.4.0 => 4.4.6 
        @vue/cli-plugin-router: ~4.4.0 => 4.4.6 
        @vue/cli-plugin-typescript: ~4.4.0 => 4.4.6 
        @vue/cli-plugin-unit-mocha: ~4.4.0 => 4.4.6 
        @vue/cli-plugin-vuex: ~4.4.0 => 4.4.6 
        @vue/cli-service: ~4.4.0 => 4.4.6 
        @vue/cli-shared-utils:  4.4.6 
        @vue/component-compiler-utils:  3.2.0 
        @vue/eslint-config-typescript: ^5.0.2 => 5.0.2 
        @vue/preload-webpack-plugin:  1.1.2 
        @vue/test-utils: ^1.0.3 => 1.0.3 
        @vue/web-component-wrapper:  1.2.0 
        eslint-plugin-vue: ^6.2.2 => 6.2.2 
        typescript: ~3.9.3 => 3.9.7 
        vue: ^2.6.11 => 2.6.11 
        vue-class-component: ^7.2.3 => 7.2.5 
        vue-cli-plugin-electron-builder: ~2.0.0-rc.4 => 2.0.0-rc.4 
        vue-eslint-parser:  7.1.0 
        vue-hot-reload-api:  2.3.4 
        vue-loader:  15.9.3 
        vue-property-decorator: ^8.4.2 => 8.5.1 
        vue-router: ^3.2.0 => 3.3.4 
        vue-style-loader:  4.1.2 
        vue-template-compiler: ^2.6.11 => 2.6.11 
        vue-template-es2015-compiler:  1.9.1 
        vuex: ^3.4.0 => 3.5.1 
      npmGlobalPackages:
        @vue/cli: 4.4.6

How to solve the problem?
Looking forward to your kind help.
Marco

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
