### ISSUE TITLE
Inconsistent behavior of nativeTheme update event

### ISSUE THREAD

**Issue by Artemyanen** [electron/electron#24828]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.3.1
  * 9.1.2
* **Operating System:**
  *  macOS 10.15.3
  * Windows 10 19041

### Expected Behavior
Consistent behavior for ```nativeTheme.on('update')``` across different platforms.

### Actual Behavior
Subscription to ```nativeTheme.on('update')``` has different trigger conditions on macOS and Windows.
It seems like on Windows if you change between `light` and `system` themes and your system theme is light,
electron doesn't fire theme `update` event.
While on macOS it works fine and fires an `update` when switching between `light` and `system` themes

### To Reproduce

```ts
  nativeTheme.on('updated', () => console.log('updated'))

  nativeTheme.themeSource = 'light';
  nativeTheme.themeSource = 'system';
  nativeTheme.themeSource = 'light';
```
Run this code on macOS with theme set to light, the output is:
```ts
updated
updated
updated
```
When running same code on Windows with theme set to light, the output is empty:
```ts
```

**Comment by MarshallOfSound** [comment]
This is expected behavior, that event is emitted when the OS tells the application the theme has changed.  On macOS the OS follows a loopback behavior where if we say "plz be light mode" the OS then dispatches an event to say "you are now light mode".   Windows only dispatches the event for OS level changes, not per-app changes.
