### ISSUE TITLE
Upgrading electron from version 4

### ISSUE THREAD

**Issue by le0n229** [electron/electron#24834]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * from 4.x.x to 6.0.0 and upper 

* **Operating System:**
  * Catalina, Win 10

* **Last Known Working Electron version:** 
  * 5.0.13

I upgraded electron from 4.1.3 to latest 9.1.2 and everything seems like was working on my laptop, but after building it in my CI(gitlab) a got builds for mac and win with blank white screen and errors in devtools:
1)Win .tmp.node is not a valid Win32 application.
2)Mac no suitable image found.  Did find:
see attached screenshots with full text.

I started to test with different versions and found that problem starts from electron 6.0.0, all upper versions getting such errors.

### Screenshots

![image](https://user-images.githubusercontent.com/46005917/89338588-72ab5380-d6a5-11ea-8db8-3de741d78d1b.png)
![image](https://user-images.githubusercontent.com/46005917/89338637-822a9c80-d6a5-11ea-811a-f72b3844dd22.png)

### Additional Information

for CI i use simple docker file:
FROM electronuserland/builder:wine-chrome
RUN mkdir /app
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ["package.json", "yarn.lock", "/app/"]
COPY . /app
RUN yarn

and simple script
docker run \
  --env API_URL \
  --rm -v $PWD/release:/app/release -t imagename /bin/bash -c "yarn package-win && yarn package-mac"

Tried with different versions of electron builder and result is the same.
Code signing is not used.

It must be small mistake somewhere, but i didn't find it.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
