### ISSUE TITLE
Electron using Chrome color picker instead of operating system default

### ISSUE THREAD

**Issue by msavin** [electron/electron#24830]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 9.X.X. + 
* **Operating System:** macOS 10.15.3
* **Last Known Working Electron version:** 8.X.X

### Expected Behavior
Whenever a color input is clicked on, Electron used to open the systems native color picker. 

For macOS, it used to be: https://developer.apple.com/documentation/appkit/nscolorpanel 

### Actual Behavior
Now, it appears to be using a less capable one that ships with Google Chrome.

### To Reproduce
Simply create the following field: <input type="color">

### Screenshots
<img width="252" alt="Screen Shot 2020-08-04 at 9 33 08 PM" src="https://user-images.githubusercontent.com/2031235/89317191-ab91fb00-d69a-11ea-9652-ea3e3ab90075.png">

![unnamed](https://user-images.githubusercontent.com/2031235/89317409-eeec6980-d69a-11ea-9e62-356ffb1d010a.png)

**Comment by codebytere** [comment]
@msavin i'm not sure if this was intentional but:

<img width="305" alt="Screen Shot 2020-08-04 at 10 15 49 AM" src="https://user-images.githubusercontent.com/2036040/89324073-86ba6b00-d63b-11ea-9862-6e9812b83494.png">

is not a sufficient repro. Please provide more details and some code that may be run in order for us to triage this further.

**Comment by msavin** [comment]
@codebytere looks like GitHub caught my code injection 😅

Just the following element should help display the issue. Thank you.
```
<input type="color">
```

**Comment by codebytere** [comment]
@msavin thanks! will try to poke soon :)

**Comment by t57ser** [comment]
I see the same happening in v10 and v11

**Comment by codebytere** [comment]
Looks like it got introduced here: https://chromium-review.googlesource.com/c/chromium/src/+/1694930

**Comment by msavin** [comment]
In terms of supporting native UX, I would say it’s better to revert to the native widgets, especially as they have many system integrated features

**Comment by codebytere** [comment]
Having done some more research, this was introduced in the [Form Control Refresh](https://blog.chromium.org/2020/03/updates-to-form-controls-and-focus.html#:~:text=The%20chrome%3A%2F%2Fflags%2F%23,roll%20out%20later%20this%20year.) and cannot be separated from it. That said, the form control refresh is controlled by Chrome's feature flag `form-controls-refresh` which, while currently enabled by default, can be disabled. Electron will not be turning this off by default, as it is an important new feature of Chromium, but you can do:

```js
app.commandLine.appendSwitch('disable-features', 'FormControlsRefresh')
```

to enable previous behavior.

**Comment by msavin** [comment]
Thanks Shelley I am amazed!
