### ISSUE TITLE
Proposal: Allow BrowserView to be a newGuest in new-window

### ISSUE THREAD

**Issue by subzey** [electron/electron#24833]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

The `BrowserView` is much like `BrowserWindow`, but it cannot be used as a "window" for the `new-window` event.

Imagine a tabbed layout with several `BrowserView`s, much like the regular browser window. The `webPreferences.nativeWindowOpen` is enabled.

*Use-case 1:* The page inside one `BrowserView` tries to open a new window via `window.open()`. There's no way to handle `new-window` and create a new `BrowserView` such that the `window.opener` JavaScript property refers to its opener.

*Use-case 2:* A `<form target="_blank" method="POST">` inside `BrowserView` is submitted. A new `BrowserView` can be created and its `WebContents` `loadURL()` method can be used to navigate using `POST` method. But AFAIK there's no way to know what exactly `postData` that form was going to POST.

It works fine if the `new-window` is default-prevented and a new `BrowserWindow` is created with the `options.webContents` as a constructor option. But it is ignored for a `BrowserView`

### Proposed Solution

- Allow setting `webContents` in a `BrowserView` constructor options.
- Allow `BrowserView` to be a `e.newGuest` in a default-prevented `new-window` event.

**Comment by mahnunchik** [comment]
Yep, I think it should be possible to set `BrowserView` as `newGuest`.

Related tread: https://github.com/electron/electron/issues/15040

**Comment by pOoOf** [comment]
Hey guys any idea if this is getting implemented or not?

**Comment by pOoOf** [comment]
Hey guys, any idea if this is getting implemented, i wanted to use a BrowserView instance as a newGuest window,
Will that be possible?
