### ISSUE TITLE
BrowserWindow on Windows Caches My Website, Even Loads With Network Cable Unplugged

### ISSUE THREAD

**Issue by semireg** [electron/electron#24842]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.4.1
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * Unknown

### Expected Behavior
I load a remote URL in a BrowserWindow and it accesses my website over the network.

### Actual Behavior
Something is broken with session caching on Windows. I load a remote URL in a BrowserWindow and it loads a previous version of my website.  I turn off Wifi and it still loads my remote website...

### To Reproduce
I'm guessing this is easy for someone to quickly reproduce.

### Additional Information
Here's my workaround:

```
 this.licenseWindow.webContents.session
      .clearCache()
      .then(() => {
        // For some odd reason, Windows BrowserWindow aggressively caches... ugh!
        win.loadURL(`${LLL_LOGIN}/${url}`);
        return null;
      })
      .catch(log.error);
```

**Comment by MarshallOfSound** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
