### ISSUE TITLE
Add new boilerplate to the electron docs (react + typescript)

### ISSUE THREAD

**Issue by jchengjr77** [electron/electron#24841]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

There is no simple way for typescript developers to use their familiar React development setup with Electron. Electron documentation doesn't cover typescript react support. Youtube only has one or two videos on this setup, and these videos do not complete the setup process, nor do they seem to follow best practices as listed out by some other text-based guides on the internet. The problem with existing guides is that they are either outdated or the code instructions do not work (I am pretty sure there are typos in the code they write).

### Proposed Solution

I have studied and tested various electron-react-typescript boilerplates. Taking various pieces from different guides, I have compiled a ready-to-go boilerplate repo specifically for React, Typescript, and Electron. This boilerplate can start the app in Electron, in the web (via. react-scripts), and all distribution and packaging scripts are included.

My solution: add a link to this boilerplate to Electron documentation, under boilerplates.
The boilerplate is here: https://github.com/jchengjr77/electron-react-typescript

### Alternatives Considered

Prior to trying to create my own boilerplate, I was thinking about creating a simple guide on how to set up such a project. However, this would be more work for the users and also harder to find, since other guides already exist.

### Additional Information

This boilerplate is not perfect, so I am not expecting it to get pulled in immediately. Please let me know what issues exist with it and I will try to improve it. I have modified the code as little as possible.

**Comment by jchengjr77** [comment]
Hi, sorry, this is my first time attempting to contribute to a major open source project. Should I go ahead and make a PR for this change? Or should I wait for an admin's feedback?

**Comment by jchengjr77** [comment]
I tried to visit that link above, but there was no repository there (gave me 404). I see that you are a member of Electron. Should I make a PR now or wait for a green light?

**Comment by Kilian** [comment]
Hi @jchengjr77, we encourage people to submit boilerplates to the [awesome-electron](https://github.com/sindresorhus/awesome-electron#boilerplates) repository. That is linked from our [boilerplates documentation](https://www.electronjs.org/docs/tutorial/boilerplates-and-clis). Thanks!

**Comment by jchengjr77** [comment]
@Kilian Thank you for the direction! Really appreciate it. I'll go do that now
