### ISSUE TITLE
webview uploadfile net::ERR_ACCESS_DENIED 

### ISSUE THREAD

**Issue by lmh14790** [electron/electron#24850]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  electron 9.1.2
* **Operating System:**
   macOS 10.13.6 / Windows 10 
* **Last Known Working Electron version:**

### Expected Behavior

when upload file  in webview  report error net::ERR_ACCESS_DENIED 
 upload success in chrome or other Browser
electron 8.0.0 can upload success
### Screenshots

![image](https://user-images.githubusercontent.com/19796972/89410684-c6c24080-d756-11ea-9ba9-27ac48534d0d.png)
![image](https://user-images.githubusercontent.com/19796972/89410716-d3469900-d756-11ea-9336-e6210d84748e.png)
![image](https://user-images.githubusercontent.com/19796972/89410960-333d3f80-d757-11ea-9c62-3ded7e4d0e85.png)
![image](https://user-images.githubusercontent.com/19796972/89410788-f1ac9480-d756-11ea-8326-bd695166f056.png)

**Comment by VerteDinde** [comment]
Hey @lmh14790, thanks for reporting this!

Would you be able to create a self-contained repro using [Electron Fiddle](https://github.com/electron/fiddle), and we can take a look? I wasn't able to repro just with the information you provided.

**Comment by ranahemantkumar** [comment]
i can confirm this issue exist in electron 9.x

@lmh14790  were you able to resolve it or any workaround?

**Comment by lanxikun** [comment]
<webview disablewebsecurity/>

**Comment by lanxikun** [comment]
`<webview disablewebsecurity/>`

**Comment by ranahemantkumar** [comment]
i tried using disablewebsecurity but that didn't helped. still facing the same error.
Plus don't think its good approach due to security issues as suggested in electron documentation.

**Comment by blazkablatnik** [comment]
I had the same problem on `9.0.x`. **Updating to `10.1.3`** fixed the issue for me.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment [above](https://github.com/electron/electron/issues/24850#issuecomment-669439500). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

Also as @blazkablatnik mentioned, please try upgrading to Electron 10.1.3 for a fix.

**Comment by ranahemantkumar** [comment]
@blazkablatnik Thanks, that resolved the problem.
