### ISSUE TITLE
Native PDF plugin does not support custom protocol

### ISSUE THREAD

**Issue by lishid** [electron/electron#24859]
When using a custom protocol to render `my-app://dummy.pdf`:

- The PDF plugin can detect the PDF file (as seen from screenshot 2), which return a `Content-Type: application/pdf` along with an HTML response containing an `<embed type='application/pdf'>`.
- The PDF plugin **seems unable to access the file data, thus rendering a blank PDF** (as seen from bottom left of screenshot 3).
- `my-app://dummy.pdf` is valid seen from an XMLHttpRequest (as seen from right of screenshot 3)
- The same file using `file:///dummy.pdf` renders properly.

![image](https://user-images.githubusercontent.com/609710/89467702-19463180-d744-11ea-8ecc-9fc2be6589e3.png)

#### This is what the request looks like in developer console:
![image](https://user-images.githubusercontent.com/609710/89467439-8a391980-d743-11ea-8d56-5e6359442491.png)

#### Top left: `file:///dummy.pdf`. Bottom left: `my-app://dummy.pdf`. Right: `my-app://dummy.pdf` as seen from an XMLHttpRequest.
![image](https://user-images.githubusercontent.com/609710/89466844-8b1d7b80-d742-11ea-80b7-aae58c0bfe59.png)

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.1.2
* **Operating System:**
  * Windows 10 1909
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
PDF renders with `my-app://dummy.pdf`

### Actual Behavior
PDF plugin shows up, but is empty.

### To Reproduce

- Clone `electron-quick-start`.
- Download a testing PDF file to the repo root: https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf

main.js
```
const {app, BrowserWindow, protocol} = require('electron')
const path = require('path')

protocol.registerSchemesAsPrivileged([
  {scheme: 'my-app', privileges: {standard: true, secure: true}},
]);

function createWindow () {
  protocol.registerFileProtocol('my-app', (req, callback) => {
    let url = req.url;
    url = decodeURIComponent(url.substr('my-app://'.length));
    url = path.resolve(url);
    callback({path: url});
  });

  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      plugins: true,
    }
  })

  mainWindow.loadFile('index.html')

  mainWindow.webContents.openDevTools()
}

app.whenReady().then(() => {
  createWindow()
  
  app.on('activate', function () {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})
app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})
```

Add to index.html
```
    <style>
      body, html {
        width: 100%;
        height: 100%;
      }
      iframe {
        width: 100%;
        height: 50%;
      }
    </style>
    <iframe id="file" src="file:///dummy.pdf"></iframe>
    <iframe id="custom" src="my-app://dummy.pdf"></iframe>
```

For extra debugging, add to renderer.js
```
var request = new XMLHttpRequest();
request.open('GET', 'my-app://dummy.pdf', true);
request.onload = function(response) {
	console.log(request);
	console.log(request.response);
};
request.onerror = console.error;
request.send();
```

**Comment by lishid** [comment]
I'm guessing this might be due to plugin processes not implementing scheme configurations the same way renderers do.

**Comment by lishid** [comment]
Oops, I think this is a duplicate of https://github.com/electron/electron/issues/24011

**Comment by lishid** [comment]
This may be related to https://github.com/electron/electron/issues/24011

**Comment by pat-flew** [comment]
I ran into this issue and found that the PDF does render if CSP is disabled with `bypassCSP: true` in the scheme privileges. Not sure if there's a more granular way to address.

Perhaps related to the discussion at https://bugs.chromium.org/p/chromium/issues/detail?id=271452

**Comment by gscholer** [comment]
I am using beaker browser, it has a similar problem https://github.com/beakerbrowser/beaker/issues/1687, do you know how to bypass the CSP to make PDF render? @pat-flew

**Comment by pat-flew** [comment]
@gscholer To test this, it would need to be added to the scheme privileges of the protocol being used. Where is best asked of someone over there, but it's probably https://github.com/beakerbrowser/beaker/blob/63dd71e3cd0ae151ec6160b5b02d10afe483614f/app/main.js#L75. 

If it is the same issue, this is a clumsy solution as you likely don't want to completely disable CSP. The real resolution may need to come upstream from chromium but idk.

**Comment by gscholer** [comment]
@pat-flew Thank you, that worked. I have add `basspassCSP: true` to the `registerSchemesAsPrivileged` of `hyper` scheme, it is the file of `main.build.js` under the folder `resources/app` of the beaker-browser. now the PDF file can render.

**Comment by knownasilya** [comment]
Has there been any movement on the chromium side? If not, would `basspassCSP: true` be a security issue (I'm assuming yes)?

**Comment by lishid** [comment]
This actually seems to be already fixed. Not exactly sure when though. (Tested in 18.3.5)

**Comment by aicioara** [comment]
@lishid, I am still experiencing issues even on `v24.4.0`. Should this work out of the box? If not, what are the necessary configs to allow both:
- File protocols via `protocol.registerFileProtocol`
- PDFs loaded as `<iframe>` (or `<object>` or `<embed>`) inside the `BrowserWindow`

**Comment by XDean** [comment]
This issue still exist with electron 26.1.0 `protocol.handle`
