### ISSUE TITLE
Can't right call back on localhost

### ISSUE THREAD

**Issue by ztmhsj1024** [electron/electron#24852]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.1.2
* **Operating System:**
  *  Windows 10 
* **Last Known Working Electron version:**
  * 8.4.1

this code cant right running in 9.0.0-9.1.2 on localhost, cant get event 'data' 'end' ,but is ok in 8.4.1.
 
const net = require('net')
const client = net.createConnection( { port: 65535 }, () => {
    //'connect' listener
    console.log('connected to server!');
});
client.on('data', (data) => {
    console.log(data.toString());
});
client.on('end', () => {
    console.log('disconnected from server');
});

https://gist.github.com/0301b75d8e64af8243befc79ea48ae17

**Comment by nornagon** [comment]
Would you be able to create a self-contained repro using [Electron Fiddle](/electron/fiddle)?

**Comment by ztmhsj1024** [comment]
[repo.zip](https://github.com/electron/electron/files/5031988/repo.zip)

**Comment by ztmhsj1024** [comment]
the problem occur when the browser reload(ctrl+r) .

**Comment by ztmhsj1024** [comment]
https://gist.github.com/0301b75d8e64af8243befc79ea48ae17
The problem occur when the browser reload(ctrl+r) .
It can't get event except connected.

**Comment by canning-duck** [comment]
Hello, I have the exact same issue. I would add that:
- the missing events are dispatched when the browser is reloaded (check "Preserve Log" in the Console Settings).
- after a few reloading, even the 'ready' event is not dispatched, while the connection is visible from the server. Same for the 'error' event if the server is not running.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
