### ISSUE TITLE
ready-to-show event is never fired after calling browserWindow.hide() on Windows

### ISSUE THREAD

**Issue by dannyharding10** [electron/electron#24855]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.1.2
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 4.2.8 (Not sure if it was happening from 5 - 8)

### Expected Behavior
Calling `browserWindow.hide()` after creating a `new BrowserWindow()` on windows should not preclude the ready-to-show event from being fired.

### Actual Behavior

In Windows, after creating a BrowserWindow and calling `browserWindow.hide()`, the ready-to-show event is never fired.

### To Reproduce

** ON WINDOWS **

Either use this [Electron Fiddle](https://github.com/electron/fiddle): https://gist.github.com/dannyharding10/7b38139009012817608c0ea8a2ba29bc

Or simply clone the [Electron Quick Start](https://github.com/electron/electron-quick-start) repo and make the following changes in main.js

![image](https://contattafiles.s3.us-west-1.amazonaws.com/tnt23364/NPClNmVBbJIDcUR/Pasted%20Image%3A%20Aug%205%2C%202020%20-%201%3A14%3A10pm)

### Additional Information
This does not happen on Mac. I did not test on Linux. As far as I understand, if the window is showing then the `ready-to-show` event will never fire, as described [in the docs](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#using-ready-to-show-event) where it says "the ready-to-show event will be emitted when the renderer process has rendered the page for the first time ***if the window has not been shown yet.***". However calling `window.hide()` does not show the window, so `ready-to-show` should still fire.

I could imagine how this *might* be intended behavior if it were consistent between operating systems, but the fact that it is specific to Windows makes me think it is indeed a bug in electron.

**Comment by codebytere** [comment]
Potentially fixed by https://github.com/electron/electron/pull/25448

**Comment by codebytere** [comment]
Confirmed closed in https://github.com/electron/electron/pull/25448
