### ISSUE TITLE
Cannot write a file with FS in build version (Can in dev mode)

### ISSUE THREAD

**Issue by oscareawork** [electron/electron#24879]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  v9.1.2 and using electron-builder to build
* **Operating System:**
  MacOS Catalina 10.15.6
* **Last Known Working Electron version:**
  N/A

### Expected Behavior
I am trying to create a text file with a string in it using Node FS on my frontend code like this:

const fs = window.require("fs");
`fs.writeFile("../myfile.txt", data, (err) => { if (err) {alert(err)} else {alert('success')}`

This works perfectly fine when in dev mode but not when running the app after building it.

### Actual Behavior
The built app launches fine, and everything works up until the step of creating the file, at which point I get what look like permission errors like so: Error: EROFS: read-only file system, open '../myfile.txt'

### To Reproduce
Use fs to writefile to either "textfile.txt", "./textfile.txt" or "../textfile.txt" on a built app. I even tried other paths like "~/Desktop/textfile.txt" but it says that doesnt exist.

### Additional Information
I dont think it matters, but I am using React as the frontend and loading the localhost:3000 when "isDev" is true, and loading the html in the build folder when building.
Here are what I consider to be the relevant code:
**My electron code:**
```js
const { app, BrowserWindow } = require("electron");
const path = require("path");
const isDev = require("electron-is-dev");

function createWindow() {
  const win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true,
    },
  });

  win.loadURL(
    isDev
      ? "http://localhost:3000"
      : `file://${path.join(__dirname, "../build/index.html")}`
  );

  win.webContents.openDevTools();
}

app.whenReady().then(createWindow);

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

```
**My fs function:** 
```js
const fs = window.require("fs");

const makeBook = (data, setStatus) => {
  fs.writeFile("../myfile.txt", data, (err) => {
    if (err) {
      alert(err);
    } else {
      alert("File written successfully");
    }
  });
};
```

**Comment by nornagon** [comment]
Thanks for reaching out!

Because we treat our issues list as [the team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by nornagon** [comment]
I suspect the issue you're encountering is due to the relative file path, which might not be the same between packaged and unpackaged. Consider resolving the path before writing to it.

**Comment by oscareawork** [comment]
> I suspect the issue you're encountering is due to the relative file path, which might not be the same between packaged and unpackaged. Consider resolving the path to an absolute path before writing to it.

I will look into this more, but the reason I dont think that is an issue is that it gives a different error when the path cant be found, like if I put "~/Desktop/" as the path.

**Comment by nornagon** [comment]
`~` is not an absolute path—it's normally expanded by your _shell_, not the OS itself, so writing `~` in your JS code won't do what you expect.
