### ISSUE TITLE
ITMS-90237: The product archive package's signature is invalid. Ensure that it is signed with your '3rd Party Mac Developer Installer' certificate.

### ISSUE THREAD

**Issue by ajaycallhippo** [electron/electron#24871]
I am facing this issue can you please help to fix this issue.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

**Comment by Vladimir-Nn** [comment]
In my case, expired certificates were not removed from the Keychain. (New ones were automatically generated by XCode)
