### ISSUE TITLE
Running `electron --version` on windows times out

### ISSUE THREAD

**Issue by connor4312** [electron/electron#24877]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  * 11.0.0-nightly.20200805
* **Operating System:** 
  * Windows 10 
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior

Running `./node_modules/.bin/electron.cmd --version` outputs the version number of electron

### Actual Behavior

The command appears to hang indefinitely.

### To Reproduce

Reported by https://github.com/microsoft/vscode/issues/103545, seems to happen consistently. @wolfgangWS please help root cause here 🙂 

### Screenshots

N/A

### Additional Information

N/A

**Comment by nornagon** [comment]
Seems to work fine on macOS 🤔

**Comment by connor4312** [comment]
Yea, it works fine for me across platforms, but not for this user.

**Comment by dscalzi** [comment]
Related https://github.com/electron/electron/issues/26527
Causing https://github.com/electron/electron/issues/24918

Impossible to debug with VS Code on windows until we can get this fixed...
