### ISSUE TITLE
PowerPC Linux and OS X Tiger support?

### ISSUE THREAD

**Issue by RetroSoftwareRepository** [electron/electron#24878]
I'm looking to port the Discord client to PowerPC hardware. I'm aware that it is heavy but I think electron would be quicker than a TenFourFoxBox in this regard with the right optimizations. Hope I can make this happen.

**Comment by nornagon** [comment]
Good luck! We don't support ppc, because Chromium doesn't support ppc.

**Comment by RetroSoftwareRepository** [comment]
Actually building Chromium should be relatively easy, as there is a port of V8 to PowerPC.
