### ISSUE TITLE
Fullscreen mode doesn't hide Mac toolbar, but hide the green dot (close button)

### ISSUE THREAD

**Issue by lori99-data** [electron/electron#24888]
My electron version is 9. The function I want to achieve is when I hover the top of app, not showing Mac default tool bar. But still has the green dot (the close button).

I am currently using this:

mainWindow.once('ready-to-show', () => {
    mainWindow.show();
    mainWindow.maximize();
    mainWindow.setFullScreen(true);
    app.dock.hide();
  }
  );

But it did opposite way. 

Anyone know how to solve this issue?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
