### ISSUE TITLE
When downgrading from electron v9 to electron v8 the IndexedDB data gets deleted

### ISSUE THREAD

**Issue by rafeca** [electron/electron#24882]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v9.x
* **Operating System:**
  * macOS 10.15.6
* **Last Known Working Electron version:**
  * 8.4.0

### Expected Behavior

An electron application should maintain its `IndexedDB` database state between Electron versions, even when downgrading between versions.

### Actual Behavior

If an application that uses IndexedDB on electron v9 gets rebuilt with electron v8, when users open the application all the IndexedDB contents get erased.

### To Reproduce

Steps to reproduce this using [`electron-quick-start`](https://github.com/electron/electron-quick-start):

1. Clone the `electron-quick-start` project (its current default branch points to electron v9 already).
2. Run `npm install && npm start` to build and start the app.
3. Create a dummy IndexedDB database by executing the following in the chrome devtools terminal: `indexedDB.open("test_db", 2)`
4. Check that the database has been created by checking the "Application" tab on the chrome devtools.
5. Now rebuild and open again the `electron-quick-start` app using an electron version older than v9: `git checkout 41c57ef && npm i && npm start` (this checkouts https://github.com/electron/electron-quick-start/commit/41c57ef3717329e1729d0e5f93caeafeeda77ff3 which points to electron v8.3.0).
6. Check that the database does not exist anymore by checking the "Application" tab on the chrome devtools.

**Comment by zcbenz** [comment]
Chromium does not consider downgrading as a valid use case, so they would not consider this as a bug. I'm afraid we are unable to provide a fix in Electron as supporting downgrading is almost an impossible task.
