### ISSUE TITLE
Can't loadURL

### ISSUE THREAD

**Issue by tpikachu** [electron/electron#24884]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.2
* **Operating System:**
  * macOS 10.15.5 / Windows 10
* **Last Known Working Electron version:**
  * never

### Expected Behavior
Just wanna wrap the webapp. Wanna make browserWindow loads one URL.

### Actual Behavior
Not showing anything while this url is accessible and working fine on any browsers.

### To Reproduce

Gist link has been attached

### Additional Information
https://gist.github.com/b0f467b4e8a7e7e26739574b24938227

**Comment by nornagon** [comment]
The page in question is quite complex and appears to include Electron-specific code. In order to determine whether or not there is an Electron bug, we'll need a smaller reproduction case.

**Comment by tpikachu** [comment]
I've shared the gist that generates from `Electron-fiddle`

**Comment by nornagon** [comment]
@tpikachu that gist includes a reference to a web page with many thousands of lines of code. The issue is probably in there.

**Comment by tpikachu** [comment]
Well, please consider this. I can load this URL from any browsers even puppeteer.

**Comment by tpikachu** [comment]
@nornagon Would you help me to resolve this?

**Comment by nornagon** [comment]
@tpikachu I'm not able to spend the time debugging your specific, very large app. If you want help, you'll need to provide a reduced repro case, as I requested. There are thousands of open issues in this project and I unfortunately can't justify spending hours investigating each one.

Alternatively, if you're not willing to create a reduced repro case, you're welcome to email me to discuss hiring my service as a contractor.

**Comment by tpikachu** [comment]
Dear @nornagon Thanks for your time. As I shared before, this web app is working well on every browser. As far as I know, the Electron has an embedded chromium-browser but not sure why this website can't be loaded on only Electron.

Btw, I will try to find another approach.
Best wishes.

**Comment by nornagon** [comment]
Best of luck.
