### ISSUE TITLE
Support opening a custom context menu when right-clicking a draggable region of the app under Windows

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#24893]
### Problem Description

Under Windows regions of the app that have `-webkit-app-region: drag` applied to them come also with a special context menu that can't be overridden.

### Proposed Solution

I think it might be best to not show that default context menu at all, as it makes it impossible to provide a custom one. Also for whatever reason that context menu under Windows doesn't even look like the regular ones, I think it would be better to be able to provide users with consistent context menus.

### Alternatives Considered

Reimplementing `-webkit-app-region: drag`? That'd be a bit crazy, if it's even possible to do at the app level.

### Additional Information

Video showcasing the problem: https://i.imgur.com/FTGdWw0.mp4

**Comment by zcbenz** [comment]
Technically draggable regions work on Windows by marking the area as titlebar, so in theory we can support custom menu by support setting menu for titlebar. I don't think anyone in the team would be interested in implementing this, but I'm leaving this issue open.

**Comment by Kenhuey** [comment]
I think this is a great enhancement, sometimes we need to drag window, but cannot disable the right-click menu. I am sad :(

**Comment by samuelmaddock** [comment]
It's now possible to prevent the system menu from appearing and display your own `Menu` in its place. This is thanks to the `system-context-menu` event added to the BrowserWindow in #25795

**Comment by fabiospampinato** [comment]
@samuelmaddock is that working for you? Last time I tried it wasn't working for me 🤔

**Comment by samuelmaddock** [comment]
> 
> 
> @samuelmaddock is that working for you? Last time I tried it wasn't working for me 🤔

Ah, looks like there's a known bug #26726. I was able to get the `system-context-menu` event to appear only when right-clicking on a framed window's title bar.

**Comment by qjl1569** [comment]
👍👍👍👍👍

`
// https://docs.microsoft.com/en-us/windows/win32/menurc/wm-initmenu?redirectedfrom=MSDN
const WM_INITMENU = 0x0116;

const menu = Menu.buildFromTemplate([
  {
    label: "Test",
  }
]);

win.hookWindowMessage(WM_INITMENU, () => {
  win.setEnabled(false);
  win.setEnabled(true);

  menu.popup();
});
`

**Comment by qjl1569** [comment]
`// https://docs.microsoft.com/en-us/windows/win32/menurc/wm-initmenu?redirectedfrom=MSDN
const WM_INITMENU = 0x0116;

const menu = Menu.buildFromTemplate([
{
label: "Test",
}
]);

win.hookWindowMessage(WM_INITMENU, () => {
win.setEnabled(false);
win.setEnabled(true);

menu.popup();
});`

**Comment by qjl1569** [comment]
// https://docs.microsoft.com/en-us/windows/win32/menurc/wm-initmenu?redirectedfrom=MSDN
const WM_INITMENU = 0x0116;

const menu = Menu.buildFromTemplate([
{
label: "Test",
},
{
label: "Test",
}
]);

win.hookWindowMessage(WM_INITMENU, () => {
win.setEnabled(false);
win.setEnabled(true);

menu.popup();
});


![GIF](https://user-images.githubusercontent.com/27790417/165213730-420c5e38-2da4-42bc-a50a-aed2f22df913.gif)

**Comment by wheezard** [comment]
@qjl1569 your solution works, thank you!

**Comment by vdegenne** [comment]
Anyone knows how to prevent opening that contextual menu at all?
I tried @qjl1569 solution without any element but I get that 

<img width="86" alt="image" src="https://user-images.githubusercontent.com/2827383/210132934-9e6cd9c0-73ce-49eb-8edb-a763c6e798c6.png">
