### ISSUE TITLE
How to enable “Allow site to play protected content”?

### ISSUE THREAD

**Issue by huzoorbux** [electron/electron#24902]
The website works properly on chrome but with the electron app, I am getting this message its a video player page.

Please ALLOW from Chrome settings > Site settings > Protected Content.

How to enable this setting?

**Comment by huzoorbux** [comment]
Here is the code repository: github.com/huzoorbux/electron-quick-start

**Comment by zcbenz** [comment]
You have to make DRM work which needs some extra work:
https://www.electronjs.org/docs/tutorial/testing-widevine-cdm

**Comment by vanminhquangtri** [comment]
Hi @huzoorbux , have you fix the problem. I got the same with you. DRM work fine very ok on Chrome but on Electron App it's not work when call api DRM widevine it throw error 400. I already added this: https://github.com/castlabs/electron-releases

**Comment by huzoorbux** [comment]
Hello @vanminhquangtri, issue not resolved :(
