### ISSUE TITLE
Maximize event is not triggered for un-resizable window

### ISSUE THREAD

**Issue by kaysonwu** [electron/electron#24906]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  9.1.0

* **Operating System:**
  Windows 10

* **Last Known Working Electron version:** 
 9.1.0

### Expected Behavior

Should trigger

### Actual Behavior

No trigger

### To Reproduce

1.  First, get the bug replay code:

```sh
$ git clone https://github.com/kaysonwu/electron-quick-start.git -b v9.x-event
$ yarn install
$ yarn dev
```

2. Click the `Toggle Resizable` button, and then click the `maximize` button on the title bar

3. You will see output without event messages

### Additional Information

Happens when I change `resizable`

**Comment by zcbenz** [comment]
I'm merging this to https://github.com/electron/electron/issues/20151 since they are essentially the same bug.

**Comment by kaysonwu** [comment]
@zcbenz  Can you solve this bug?

**Comment by kaysonwu** [comment]
@zcbenz  This issues is still not solved.
