### ISSUE TITLE
Unable to login to gmail account

### ISSUE THREAD

**Issue by huzoorbux** [electron/electron#24900]
I am trying to login with google on my website but it's not allowing me to log in on Gmail.

here is my sample forked code: https://github.com/huzoorbux/electron-quick-start

**Comment by huzoorbux** [comment]
I have fixed it with this I don't know its recommended or not, please guide.

`mainWindow.loadURL('https://accounts.google.com/login', { userAgent: 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:46.0) Gecko/20100101 Firefox/79.0' })`

**Comment by zcbenz** [comment]
There are some third party solutions for this, please check:
https://pragli.com/blog/how-to-authenticate-with-google-in-electron/
https://github.com/getstation/electron-google-oauth2
