### ISSUE TITLE
Blank page after reload, cuz nedb find() not wroks

### ISSUE THREAD

**Issue by Phreshhh** [electron/electron#24903]
Hi

Somewhere between v8.5.0 and v9.0.0 electron local page reload get back blank db content.

[neDB](https://github.com/louischatriot/nedb) find() not work. The db load run successfully, but the find function not run without error message.

**Comment by zcbenz** [comment]
Can you please provide a simple app that can reproduce the problem?

**Comment by Phreshhh** [comment]
OMG, sorry it's my fail.

I can't reproduce the problem in the sample app with electron v8.5.0 - v9.2.0.

I tried upgrade my older app to a newer version, but the app jam at db loading without any error message. I thinked it's a neDB compatibility problem, but seems like i was wrong..

Sorry about that. U can close this issue.
