### ISSUE TITLE
submitting login form in iframe redirects to blank in chromium browser in electron

### ISSUE THREAD

**Issue by jitenverma1** [electron/electron#24914]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
I have embed chromium browser in electron app. While i submit login form which is iframe embeded in website it gets blank, does not load anything..Iam geting the errors snapshot attached below

### Additional Information
This workd fine in normal browser mode like in chrome etc.There are no errors and issues.
![flow-error](https://user-images.githubusercontent.com/51030601/89751001-fcb34c00-daeb-11ea-9fa8-1ece4824a323.png)

**Comment by jsonwu5** [comment]
Encountered the same problem

**Comment by zcbenz** [comment]
Some websites would force the top page to redirect, and they do it intentionally to avoid being embedded in iframe. I suggest using `webview` tag to embed the page instead.
