### ISSUE TITLE
Strange close delay when using beforeunload on a borderless window

### ISSUE THREAD

**Issue by RealAlphabet** [electron/electron#24910]
* **Electron Version:**
Electron 9.2.0
* **Operating System:**
Windows 10 (2004, build 19041.388)

### Expected Behavior
Instant closing of the borderless window after `beforeunload` event.

### Actual Behavior
The window takes 2 seconds before closing.

### To Reproduce

1\. Create a borderless window that load a random website.
2\. Use a preload file.

    new BrowserWindow({
        width: 600,
        height: 900,
        frame: false,
        webPreferences: {
            preload: path.join(__dirname, 'preload.js'),
        }
    }).loadURL('https://google.fr');

3\. Add a `beforeunload` event in the preload file.  

    window.addEventListener('beforeunload', function () {
        console.log("This message is instantly printed into the console. Notice the delay after, before the window close.");
    });

4\. Right click on the taskbar icon and click close.  
5\. Notice the delay.

### Additional informations

The bug only appears when using a borderless window. A simple window closes instantly.

**Comment by erikjalevik** [comment]
For me the window doesn't close at all, if I have a `beforeunload` event listener registered. Calling `app.quit()` or `getCurrentWindow().close()` has no effect either. It is impossible to close the app with the `beforeunload` listener present, regardless of its return value.

Context is the same as the OP. Windows 10 using a frameless window.

**Comment by erikjalevik** [comment]
If downgrading Electron from 9 to 8.5.0, this problem goes away and I can close the app again.

**Comment by wsjhdwzq** [comment]
> For me the window doesn't close at all, if I have a `beforeunload` event listener registered. Calling `app.quit()` or `getCurrentWindow().close()` has no effect either. It is impossible to close the app with the `beforeunload` listener present, regardless of its return value.
> 
> Context is the same as the OP. Windows 10 using a frameless window.

+1, Electron 10.1.1 can still reproduce this bug

**Comment by dannymcgee** [comment]
I was experiencing this issue without a `beforeunload` event on secondary windows (maybe Electron implicitly adds a `beforeunload` event to additional windows that are opened?). In any event, I worked around it by just calling `window.setOpacity(0)` in my event handler before calling `window.close()`. The icon in the taskbar still takes a moment to disappear, but the visible window disappears immediately which is a much nicer UX.

Alternatively, if you're using `transparent: true` on the `BrowserWindow` you could have the render process set its body opacity to 0 with a short CSS transition for a nice fade-out effect.

**Comment by JannisX11** [comment]
I am experiencing the same issue, plus when the dev tools are opened, the window doesn't close at all (#25012).
I will have to stay on Electron 8.5 for now.

**Comment by JohnLouderback** [comment]
I am also experiencing this issue without a `beforeunload` event. I have to programmatically close dev tools if I want my window to close and even when the dev tools are closed, there's a delay before the window will close.

**Comment by lociero** [comment]
This may help, but I'm not really sure if its ok, also works with opened devTools.
```js
mainWindow = new BrowserWindow({
// some code...
mainWindow.on('close', mainWindow.destroy);
```

**Comment by Alexandre2006** [comment]
> ```js
> ```js
> mainWindow.on('close', mainWindow.destroy);
> ```
> 
> 
>       
> ```

This works great, though it is annoying that we do have to run this. Thank you for your help @lociero (even if I am not the one who started this thread).
