### ISSUE TITLE
Unable to debug main process in VS Code as of Electron 9.

### ISSUE THREAD

**Issue by dscalzi** [electron/electron#24918]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.2.0
* **Operating System:**
  * Windows 10 (2004)
* **Last Known Working Electron version:**
  * Unknown, either Electron 8 or initial version of Electron 9.

### Expected Behavior
Following the guide posted here (https://github.com/electron/electron/blob/master/docs/tutorial/debugging-main-process-vscode.md), I should be able to debug the main process of the application using Visual Studio Code. This was working for a long time.

### Actual Behavior
The application does not start and Visual Studio Code hangs indefinitely. A Node.js process is started in the background, however no electron processes are started. Debugging the renderer process using the debugger for chrome appears to still work. **The issue is only with debugging the main process.**

### To Reproduce
Make an electron app and try to debug the main process using visual studio code with the configuration documented on this repository (linked above). This issue is present on the quickstart repo, if you want to just use that.

### Additional Information
I was thinking about making an issue in Visual Studio Code, but this seems to be Electron specific. Any insights as to why this is happening would be appreciated. Everything was working fine until recent updates to both vs code and electron.

**Comment by zcbenz** [comment]
Does debugging without VS Code work on your machine?
https://github.com/electron/electron/blob/master/docs/tutorial/debugging-main-process.md

**Comment by dscalzi** [comment]
@zcbenz Yes, I'm able to debug through Chrome Devtools (Chrome/ new Edge)

**Comment by long0621** [comment]
@dscalzi  I hava same problem for debug, if have any new process, please let me know, thanks!

**Comment by dscalzi** [comment]
This still isn't working. The Node.js process starts and nothing afterwards. Latest VS Code as of 11/16/2020. Node.js 14.15.1.

I can start with npm start. Is this an issue with electron.cmd?

**Comment by dscalzi** [comment]
So in summary VS code is attempting to verify the node version by appending `--version` to the runtime executable. Since the electron process never terminates from that call, it is unable to proceed and also hangs.

**Comment by dscalzi** [comment]
Workaround while awaiting a fix:

In `node_modules/electron/cli.js` add the following before spawning the child process:

```js
if(process.argv.includes('--version') || process.argv.includes('-v')) {
  process.stdout.write('v14.15.1')
  process.exit(0)
}
```

Replace the version with your node version. This will allow the debugger to get past the point of failure. (https://github.com/microsoft/vscode-js-debug/blob/master/src/targets/node/nodeBinaryProvider.ts#L244)
