### ISSUE TITLE
Grey Screen upon editing message and other actions, freezing the webview

### ISSUE THREAD

**Issue by manavmehta** [electron/electron#24920]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  9.1.1
* **Operating System:**
  *  macOS Catalina (no specific release)
* **Last Known Working Electron version:**
  *  NA

### Actual Behavior
In [Zulip Desktop](https://www.github.com/zulip/zulip-desktop), we are seeing this issue whereupon editing a message, a grey screen appears which freezes the entire webview. For some, a reload works, whereas, for the others, a restart is needed.

### To Reproduce
No confirmed steps.
Reported Steps: 
1. [Conversation Link](https://chat.zulip.org/#narrow/stream/16-desktop/topic/crash.20on.20edit.20message)
* Use Zulip desktop app for a couple of hours
* Open a stream where they have written something
* Press left arrow to edit the last message
* It crashes - Greyed out

2. [Conversation Link](https://chat.zulip.org/#narrow/stream/9-issues/topic/Greyscreen.20of.20death)
* Receive a message/ message notification.
* Greyed out

3. [Conversation Link](https://chat.zulip.org/#narrow/stream/9-issues/topic/Grey.20Window.20on.20macOS)
* Send a message, OR
* Reply to a message, OR
* Start Zulip app.

The commands required to clone/setup/run zulip-desktop repo:
```sh
$ git clone https://www.github.com/zulip/zulip-desktop.git
$ cd zulip-desktop
$ npm install
$ npm start
```

### Screenshots

![Greyed-out](https://user-images.githubusercontent.com/31139861/89797175-3d40b300-db48-11ea-8c14-c6870f9c584f.png)

![Grey-window](https://user-images.githubusercontent.com/31139861/89797179-3dd94980-db48-11ea-8017-6b300e367be1.png)

**Comment by zcbenz** [comment]
I believe it is some bug causing webview to crash, but we do not have resources to debug the users' apps to find out a bug, I suggest making a minimal app that can reproduce the issue, otherwise we are unable to investigate further.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by Gambitboy** [comment]
This issue is still happening. Not sure if this can help find the issue but here are some comments on this issue in the zulip repo. 
https://github.com/zulip/zulip-desktop/issues/1016
