### ISSUE TITLE
Electron app sends a network request even set spellcheck as false in web preference. 

### ISSUE THREAD

**Issue by darwinye** [electron/electron#24931]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
As screenshot, electron sends out a http request to get dictionary even if spellcheck is disabled. 
![image](https://user-images.githubusercontent.com/2561486/89850546-2b4d2780-dbbd-11ea-804b-e6b6c984d8e3.png)
* **Electron Version:**
  * 9.0.5
* **Operating System:**
  * 
* **Last Known Working Electron version:**
  * latest

### Expected Behavior

There is no any request out if spellcheck is disabled

**Comment by MarshallOfSound** [comment]
Duplicate https://github.com/electron/electron/issues/22995
