### ISSUE TITLE
load more messages

### ISSUE THREAD

**Issue by AirhitCombo** [electron/electron#24935]
Hello! I have an issue that there is everytime "LOAD MORE MESSAGES".

I already restarted my pc and reinstalled it but it doesnt work. I hope the Bug is simple and is already fixed!

"MEHR NACHRICHTEN LADEN" means basically "load more messages".
this is what i see:
![#『💬』global-chat - Discord 11 08 2020 14_28_50](https://user-images.githubusercontent.com/69514939/89897315-1d100300-dbdf-11ea-88e4-8e7dc9f2f5bf.png)
and this is what the Bot sees:
![#『💬』global-chat 11 08 2020 14_37_12](https://user-images.githubusercontent.com/69514939/89897963-2a79bd00-dbe0-11ea-8c1c-28a50acba6b4.png)

**Comment by HashimotoYT** [comment]
This issue is not with the Electron, that problem in Discord application, please report to the [Discord support](https://support.discord.com/).
