### ISSUE TITLE
Sandbox is breaking the App

### ISSUE THREAD

**Issue by tpikachu** [electron/electron#24936]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.

### Issue Details

* **Electron Version:**  : 9.2.0
* **macOS Version:**  :  10.15.5
* **Electron-builder Version:**  :  22.8.0
### Rejection Email

Guideline 2.3 - Performance

Your app does not achieve the core functionality described in your marketing materials or release notes.

Specifically,

The application window will launch and no binary is displayed. Please revise the application so the binary will display features/content for review.

1.) downloaded app
2.) launched app
3.) blank white window displayed
4.) quit application and relaunched, issue persisted (screenshot attached)

Please see attached screenshot for details.
### Additional Information

1. By enabling sandbox: I can upload pkg to app store using `Transporter` but mas file is not working
2. By disabling sandbox: App is working fine but can't upload pkg to app store.

The above reject email that I've received after submitting pkg by enabling sandbox.

Here is the entitlements.

`entitlements.mas.plist`

```
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
       <!-- THIS SANDBOX IS REALLY KILLING ME --> 
        <key>com.apple.security.app-sandbox</key>
        <true/>
        <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
        <true/>
        <key>com.apple.security.cs.allow-jit</key>
        <true/>
        <key>com.apple.security.cs.disable-library-validation</key>
        <true/>
        <key>com.apple.security.cs.allow-dyld-environment-variables</key>
        <true/>
        <key>com.apple.security.application-groups</key>
        <array>
            <string>XXXX.</string>
        </array>
        <key>com.apple.security.network.client</key>
        <true/>
    </dict>
</plist>
```

`resign.sh`

```
#!/bin/bash
# Name of your app.
APP="App  Name"
# The path of your app to sign.
APP_PATH="release/mas/$APP.app"
# The path to the location you want to put the signed package.
RESULT_PATH="release/mas/$APP-mac.pkg"
# The name of certificates you requested.
APP_KEY="3rd Party Mac Developer Application: XXXXXXXX (XXXXXXXXX)"
INSTALLER_KEY="3rd Party Mac Developer Installer: XXXXXXXX (XXXXXXXXX)"
# The path of your plist files.
PARENT_PLIST="build/entitlements.mas.plist"
CHILD_PLIST="build/entitlements.mas.inherit.plist"
LOGINHELPER_PLIST="build/entitlements.mas.loginhelper.plist"
FRAMEWORKS_PATH="$APP_PATH/Contents/Frameworks"

codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Electron Framework"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Libraries/libffmpeg.dylib"

codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper.app/Contents/MacOS/$APP Helper"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper.app"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (Renderer).app/Contents/MacOS/$APP Helper (Renderer)"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (Renderer).app"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (GPU).app/Contents/MacOS/$APP Helper (GPU)"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (GPU).app"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (Plugin).app/Contents/MacOS/$APP Helper (Plugin)"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (Plugin).app"

codesign -s "$APP_KEY" -f --entitlements "$LOGINHELPER_PLIST" "$APP_PATH/Contents/Library/LoginItems/$APP Login Helper.app/Contents/MacOS/$APP Login Helper"
codesign -s "$APP_KEY" -f --entitlements "$LOGINHELPER_PLIST" "$APP_PATH/Contents/Library/LoginItems/$APP Login Helper.app/"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$APP_PATH/Contents/MacOS/$APP"
codesign -s "$APP_KEY" -f --entitlements "$PARENT_PLIST" "$APP_PATH"

productbuild --component "$APP_PATH" /Applications --sign "$INSTALLER_KEY" "$RESULT_PATH"
```

**Comment by tpikachu** [comment]
Especially, when I set sandbox to the /Contents/Frameworks/XXXX Helper then it's freezing just blank screen after running the application.

**Comment by yanikus** [comment]
Hey, @tpikachu. I'm facing the same issue for now. Not only the latest version of Electron but I've used the lower version as well. v5.0.13 which is known as good version for app publishing.

Plus, why do we need to resign the app? I think the electron-builder is handling codesigning

**Comment by electronWeb** [comment]
I have faced the same issue which made me to give up to upload the app to the app store.
More likely to be an electron-builder issue?

**Comment by true-eye** [comment]
Well, if you are running an issue with MAS. You can use MacGap to publish Mas as Slack is using MacGap for mac app

**Comment by tpikachu** [comment]
@yanikus yes you are right. But I've noticed that I need to make some manual signs for extra binaries inside the electron app. like helpers.
Not sure what is the best method to achieve this

**Comment by tpikachu** [comment]
@MarshallOfSound Would you have a look at this issue?

**Comment by zcbenz** [comment]
Does this work for older versions of Electron?

**Comment by tpikachu** [comment]
Unfortunately, nope.

**Comment by tpikachu** [comment]
![Screen Shot 2020-08-16 at 22 39 40](https://user-images.githubusercontent.com/46133358/90352455-6e6e2700-e011-11ea-9169-321a76eb4fb2.png)
I wonder how Slack publish their app without enabling the sandbox.

**Comment by zcbenz** [comment]
Thanks for the information. Slack does have sandbox enabled, and so are other Electron apps on Mac App Store. Since with your configurations older versions of Electron did not work neither, I believe this problem is not a bug of Electron, but some mistake in your configuration.

I suggest trying signing your app with `electron-builder` or `electron-packager`, they have every step setup automatically and you shouldn't need any manual script to sign.

**Comment by tpikachu** [comment]
@zcbenz Sorry. 
Whenever I remove this `<key>com.apple.security.app-sandbox</key>
        <true/>` then every thing works fine.

**Comment by yanikus** [comment]
I've also tried with both electron-builder and electron-packager.
Without this `<key>com.apple.security.app-sandbox</key>` then everything is working like a magic. Codesigning is perfect and the app works perfectly as well.
But codesinging with this `<key>com.apple.security.app-sandbox</key>` then everything get messy.

I think @zcbenz is trying to say this is not an electron issue but codesigning issue...

**Comment by philipTepia** [comment]
This is happening to everyone, I tried to upload the app without enabling the sandbox. But apple rejects this app.
Whatever you'd like to be, you MUST enable the `sandbox` if you are going to publish to the app store.
As far as I know, while running in the sandbox mode, electron can't use full chromium APIs. Maybe this is the reason why they just show blank pages and crash?

**Comment by aabuhijleh** [comment]
Which version of Electron does Slack use?

**Comment by tpikachu** [comment]
version 9

**Comment by AliKarpuzoglu** [comment]
I have the same issue - the app doesn't work with the sandbox entitlement in it @zcbenz  why was this issue closed? 

there's hundreds of comments about this issue over at https://github.com/electron-userland/electron-builder/issues?q=is%3Aissue+mas+is%3Aopen

**Comment by uffou** [comment]
Having this issue as well in 2021 

Once the sandbox entitlement is added the plist formatting changes, slack formatting is OK with sandbox in it 

![image](https://user-images.githubusercontent.com/2581788/116504378-cce9e580-a8c0-11eb-8e53-085217388d61.png)

**Comment by sgammon** [comment]
@zcbenz why did you close this?

**Comment by fatemehmarzoughi** [comment]
Same here (

**Comment by SolijonovDev** [comment]
same problem
