### ISSUE TITLE
Why visibleOnFullScreen is deprecated, it works fine on my mac 10.15.4

### ISSUE THREAD

**Issue by wyqpzm** [electron/electron#24939]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

My electron version is 6.1.11, and I can't update because visibleOnFullScreen option on setVisibleOnAllWorkspaces is deprecated. It works fine on mac 10.15.4 and newer version.
To code like this:

  app.dock.hide()
  window.setAlwaysOnTop(true, 'floating')
  window.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: true })

The visibleOnFullScreen option is very important to my electron app and I'm so appreciate if you can check this feature again!

**Comment by codebytere** [comment]
Huh, you're right. We removed it because it doesn't work without `app.dock.hide()`, but i can see about reinvigorating it.

**Comment by wyqpzm** [comment]
Thank you so much! I'm looking forward to the new version!
