### ISSUE TITLE
Call electron outsite directory cause error

### ISSUE THREAD

**Issue by littpi** [electron/electron#24940]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.2.0
* **Operating System:**
  * macOS 10.15.6
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior

The app should run without any error occured.

### Actual Behavior

The app prompted an error showing an array is not iterable which is get from ```fs.readdir```.

### To Reproduce

1. Create a Electron project.
2. Create a folder for Nodejs to read with ```fs```.
3. Use the following code and call the function.
```javascript
let foo = {
    bar: function() {
        fs.readdir('folder', (error, files) => {
            for (let file of files) { console.log(file); }
        });
    }
};
```
4. Setup like normal Electron app and run command outsite the folder (e.g. electron /home/user/electron-app/).

### Screenshots

* Using absolute path.
<img width="1792" alt="螢幕截圖 2020-08-12 上午12 08 01" src="https://user-images.githubusercontent.com/17842734/89923302-f8457b00-dc32-11ea-93fc-e2981257be1d.png">

* Using ```electron .```
<img width="1792" alt="螢幕截圖 2020-08-12 上午12 08 50" src="https://user-images.githubusercontent.com/17842734/89923374-1317ef80-dc33-11ea-873f-47aca46d25ca.png">

### Additional Information

When I check with ```__dirname```, it is under the project folder.

**Comment by zcbenz** [comment]
When passing relative paths to APIs like `fs.readdir`, the system would try to read filesystem from current working directory, instead of `__dirname`.
