### ISSUE TITLE
When proxy login fails, a dialog of "Error: net::ERR_TUNNEL_CONNECTION_FAILED" is displayed even if the error was catched

### ISSUE THREAD

**Issue by hoangph271** [electron/electron#24948]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  9.1.2
* **Operating System:**
  Windows 10 2004

### Expected Behavior
Error dialog is NOT shown if error captured

### Actual Behavior
Error dialog is shown if error captured

### To Reproduce

https://gist.github.com/617c8c6596c269df002996da38d39350
Just run the fiddle under a password protected proxy

### Screenshots

![image](https://user-images.githubusercontent.com/39024711/89985613-8e19ee00-dca5-11ea-8e28-606245c0d452.png)

**Comment by kiendo90** [comment]
Me too...!
How can I disable this dialog?

**Comment by rahul-dutt-sharma** [comment]
this is causing sentry to explode into infinite logs.

**Comment by rahul-dutt-sharma** [comment]
I have also observed that proxy set via `session.setProxy({ proxyRules: `${dataReceived.host}:${dataReceived.port}`,})`
used to work only for http but they are applied to both http and https
so currently I am using `session.setProxy({ proxyRules: `http=${dataReceived.host}:${dataReceived.port}`,})`

**Comment by nornagon** [comment]
Here's a self-contained fiddle which produces `net::ERR_TUNNEL_CONNECTION_FAILED` without requiring any external proxy configuration: https://gist.github.com/d0862945288b2340e98b6b5da9cf26dd

I am not able to reproduce the error dialog box described in the top post on either macOS or Windows, on any version of Electron I tried (8.x, 9.x, 10.x, 11.x).

**Comment by nornagon** [comment]
Aha, actually, I tweaked the fiddle a bit and now I'm able to reproduce the error.

**Comment by nornagon** [comment]
Just leaving a note that @VerteDinde and I tracked this down to the fact that the `res` stream is emitting an `'error'` event. From what we can tell, that's different to Node's `http` module, which seems to never emit `'error'` on a response stream (we think. maybe.)

As a workaround, you can register an event listener for `res.on('error')` inside the `on('response')` handler.
