### ISSUE TITLE
Possibility to disable external links

### ISSUE THREAD

**Issue by lainz** [electron/electron#24943]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Proposed Solution

I'm using Electron in a machine that don't have any browser, and I want to restrict the web pages that are loaded. For example, showing a third party website (services). These webpages usually have links to Facebook and any other social media. What I want to do is to:

- Run electron.exe https://thirdpartywebsite.com
- Disable links that are outside https://thirdpartywebsite.com

So all I need is an option to pass to electron to disable external links.

### Alternatives Considered

I can't find any alternative, normal browsers executed with the -app parameter can as well open any URL like Facebook.

Embedding chromium on my executable is not feasible, since in Pascal where my application is made, there is not working well and runs slower than Electron.

### Additional Information

The electron.exe process will be executed by a Point of Sale application that will send the URL to electron to run it.

**Comment by fabcotech** [comment]
You must intercept https and http stream protocols

`session.protocol.interceptStreamProtocol('https', (request, callback) => { ... }`

SO basically you will override default http and https protocol handling, and filter which request can go through, or is canceled.

https://www.electronjs.org/docs/api/protocol#protocolinterceptstreamprotocolscheme-handler-completion

**Comment by lainz** [comment]
Thanks. Solved.
