### ISSUE TITLE
worldSafeExecuteJavaScript persists, even though option is set

### ISSUE THREAD

**Issue by barbalex** [electron/electron#24950]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Forge Version:**
  * 6.0.0-beta.50
* **Electron Version:**
  * 10.0.0-beta.21
* **Operating System:**
  * Windows 10 (2004) 

### Expected Behavior

adding `worldSafeExecuteJavaScript` to `webPreferences` should prevent the following warning:

```
Security Warning: webFrame.executeJavaScript was called without worldSafeExecuteJavaScript enabled. This is considered unsafe. worldSafeExecuteJavaScript will be enabled by default in Electron 12.
```

### Actual Behavior

The warning persists.

### To Reproduce

See Electron Fiddle: https://gist.github.com/b32f9a2e213745f91a49cbd6530f2076

**Comment by barbalex** [comment]
I tested it with different electron versions:

- 10.0.0-beta.21: warning appears
- 9.2.0: warning appears
- 8.5.0: warning disappears

**Comment by pjbatista** [comment]
Yeah, up until version `9.1.2` there was no warning. Starting with version `9.2.0` the warning began to appear.

**Comment by codebytere** [comment]
This is expected behavior, per documentation:
```
* `worldSafeExecuteJavaScript` Boolean (optional) - If true, values returned from `webFrame.executeJavaScript` will be sanitized to ensure JS values can't unsafely cross between worlds when using `contextIsolation`.  The default
is `false`. 
```

You also need to enable `contextIsolation.`

**Comment by barbalex** [comment]
Uups, seems that I can't read - missed that contextIsolation is needed. Sorry for bugging you
