### ISSUE TITLE
Possibility to disable file upload

### ISSUE THREAD

**Issue by lainz** [electron/electron#24957]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Hi, I want to prohibite file upload and file download. File download is already disabled using this

```
  win.webContents.session.on('will-download', (event, item, webContents) => {
    item.cancel()
  })
```

But as well I want to prevent file upload elements in any web page to work.

### Proposed Solution

An option to disable file upload, or a code that can achieve this.

### Alternatives Considered

Nothing. The list of third party websites in our application is limited, but that doesn't prevent that sites with file upload capabilities are added by our users.

### Additional Information

This is intended for a limited browser to open limited web apps, in a printer hardware with linux for a Point Of Sale System. The idea is to allow to open some websites in that hardware, but prevent some interaction like uploads or downloads to prevent the damage of the system.

**Comment by BoyWULiWei** [comment]
Any progress?

**Comment by ashkan21** [comment]
no answer

**Comment by sebakerckhof** [comment]
I've requested this before, but seems this ain't gonna happen: https://github.com/electron/electron/issues/10967

**Comment by MarshallOfSound** [comment]
Similar to https://github.com/electron/electron/issues/10967 this isn't the kind of "protection" that Electron should get into the business of supporting directly.

Specifically the correct way to prevent file uploads is at the network level (as a proxy) or at the filesystem level (prevent the app / user even having read access to the protected files)
