### ISSUE TITLE
Proxy Electron Releases through electronjs.org

### ISSUE THREAD

**Issue by Zayelion** [electron/electron#24958]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

`github.com` and other public code repositories are (rightfully) blocked as a security threat for institutions that work in military, finance, and medical fields due to regulations and risk avoidance. This has slowed the adoption of Electron at larger businesses but they do see the value in it.

### Proposed Solution

As a compromise proxy Electron binary downloads from the main Electron website. This would allow security personnel to authorize that domain for developers to use.

### Alternatives Considered

Provide separate module that builds Electron from source when it is downloaded from NPM that would work in lieu of not having access to `github.com`. This would require more of a community effort.

**Comment by ckerr** [comment]
Thanks for the suggestion, but please report it to https://github.com/electron/electronjs.org rather than here; this isn't something that can be achieved in the Electron repo
