### ISSUE TITLE
No Window Shadow When Set To Transparent

### ISSUE THREAD

**Issue by alexdobson** [electron/electron#24952]
I'm trying to create a window with rounded corners using Electron. I've managed to achieve this by setting the BrowserWindow setting transparent to true, and then creating a div the size of the body with a border radius of 10px.

However, the issue is that setting the transparent setting to true seems to remove the shadow that Windows 10 applies to the window. The issue doesn't seem to be present on macOS, as the shadow is applied regardless of the transparency setting.

I've tried also setting the BrowserWindow setting hasShadow to true, but it makes no difference.

Is there any way to create a rounded window in electron, without loosing the window shadow in the process?

**Comment by zcbenz** [comment]
The native window shadow on Windows works differently from macOS that, it would always be a rectangle shadow regardless of the window shape, so it is disabled for transparent windows.

Implementing native window shadow in Electron, would however be too much work, and I recommend using CSS to implement shadow instead.

**Comment by oltreseba** [comment]
What is someone actually would be fine with having a rectangle shadow as the window is only half-transparent?
Is this a platform limitation or an electron choice?
