### ISSUE TITLE
Creating a folder in the showOpenDialog hides the native dialog behind the app (macOS Catalina only)

### ISSUE THREAD

**Issue by ThomasSzabo** [electron/electron#24959]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.2.0
* **Operating System:**
  * macOS 10.15.6

### Expected Behavior
After clicking the "Create" button, the dialog should stay focused

### Actual Behavior
After clicking the "Create" button, the dialog the app main window is focused and hides the native dialog

### To Reproduce
* Install the latest [electron API demos](https://github.com/electron/electron-api-demos) app
* Run the app
* Navigate to "Use system dialogs"
* Expand the "Save Dialog" section
* Click View Demo
* In the file picker dialog, click the "New Folder" button
* Enter a name and click the "Create" button

### Screenshots
![2020-08-12 14 20 48](https://user-images.githubusercontent.com/11858527/90052576-54e27d80-dca7-11ea-976e-73a654feaf10.gif)

### Additional Information
We tested on macOS 10.13 without any issues, seems a Catalina issue.

**Comment by zcbenz** [comment]
The "electron API demos" app is using Electron 7, I'm unable to reproduce the problem with newer versions of Electron using following code.

```js
const {app, dialog, BrowserWindow} = require('electron')

app.on('ready', () => {
  const win = new BrowserWindow({})
  dialog.showOpenDialogSync()
})
```

Please let me know if you can reproduce the problem on newer versions of Electron.

**Comment by ThomasSzabo** [comment]
@zcbenz thanks for testing. Yes, the "electron API demos" repo is using electron 7 but in my tests I used to bump the version number in the packages.json, so that it is using the latest version 9.2.1. Sorry, I forgot to mention this to the repro steps.
I just downloaded and tested it again, the problem still persists.

Have you used macOS Catalina? Other macOS versions work fine.
I used the exact same code as you posted and I the issue is reproducible 100% every time. Not just for me but to all our users and my colleagues on macOS Catalina.

Also make sure that the save-dialog is above the main window. Once you click the "Create" button, the main-window focuses and hides the save-dialog behind the window.

This behavior is highly confusing to our users and we get a lot of support requests for it.
Could you please double check?

**Comment by zcbenz** [comment]
Thanks for verifying, it seems that on my machine I can only reproduce when using the async API.

```js
const {app, dialog, BrowserWindow} = require('electron')

app.on('ready', () => {
  const win = new BrowserWindow({})
  dialog.showOpenDialog()
})
````

**Comment by zcbenz** [comment]
From macOS Catalina, the file dialogs are running in separate processes, which seems to be the cause of this bug. Unfortunately I don't think there is a way to work around this bug on users' side, since we have no control of the window of file dialog.

So I suggest passing the window to the API for now, which would show the dialog as a sheet and it shouldn't suffer from this bug. And it is actually the recommended way of showing file dialogs on macOS>

```js
  const win = new BrowserWindow({})
  dialog.showOpenDialog(win)
```

**Comment by twitharshil** [comment]
Able to reproduce the same issue on electron v7.3.2
