### ISSUE TITLE
enableRemoteModule: default not respected?

### ISSUE THREAD

**Issue by barbalex** [electron/electron#24951]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron-userland/electron-forge/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Forge Version:**
  * 6.0.0-beta.50
* **Electron Version:**
  * 10.0.0-beta.21
* **Operating System:**
  * Windows 10 (2004)

### Expected Behavior

If `enableRemoteModule` is not set in `webPreferences` it should be set to it's default, which is `true`, according to the docs: https://github.com/electron/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions

### Actual Behavior

In my App I get this error:

```
Uncaught TypeError: Cannot read property 'dialog' of undefined
    at Module../src/components/Navbar/Berichte.js (Berichte.js:19)
    at __webpack_require__ (bootstrap:789)
    at fn (bootstrap:100)
    at Module../src/components/Navbar/index.js (index.js:190475)
    at __webpack_require__ (bootstrap:789)
    at fn (bootstrap:100)
    at Module../src/components/App.js (App.js:1)
    at __webpack_require__ (bootstrap:789)
    at fn (bootstrap:100)
    at Module../src/index.js (index.js:193243)
```

Where Berichte.js is:
```jsx
import React, { useContext, useCallback } from 'react'
import {
  UncontrolledDropdown,
  DropdownToggle,
  DropdownMenu,
  DropdownItem,
  Button,
} from 'reactstrap'
import { observer } from 'mobx-react-lite'
import styled from 'styled-components'
import { FaPrint, FaRegFilePdf } from 'react-icons/fa'
import { remote, shell, ipcRenderer } from 'electron'

import storeContext from '../../storeContext'
import filterForFaelligeGeschaefte from '../../src/filterForFaelligeGeschaefte'
import filterForVernehmlAngek from '../../src/filterForVernehmlAngek'
import filterForVernehmlLaeuft from '../../src/filterForVernehmlLaeuft'

const { dialog } = remote

...more
```

All works well when I add `enableRemoteModule: true` to `webPreferences`.

**Comment by HashimotoYT** [comment]
See #21408, from Electron 10 the default value for `enableRemoteModule` changed from `true` to `false`, this is the expected behaviour here.

**Comment by barbalex** [comment]
Thanks. Would be nice if the docs explained that.
