### ISSUE TITLE
MacOS High Sierra: Tray icon is not highlighted when clicked

### ISSUE THREAD

**Issue by robskie** [electron/electron#24969]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version: v9.2.0**
* **Operating System: macOS 10.13.6**
* **Last Known Working Electron version: v6.1.7**

### Expected Behavior
Tray icon should be highlighted when clicked.

### Actual Behavior
Tray icon color changes but is not highlighted.

### Screenshots
![tray_bug](https://user-images.githubusercontent.com/11606363/90133469-1d0c3080-dda2-11ea-8676-5779ae0607ef.png)

### Additional Information
This bug doesn't happen on macOS Catalina (10.15.6).

**Comment by MarshallOfSound** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by robskie** [comment]
@MarshallOfSound I've created a simple test application that demonstrates the issue. You can check it here: https://github.com/robskie/macos-tray-bug

**Comment by nornagon** [comment]
FWIW I do not observe the same issue on Catalina:

![Screen Shot 2020-08-17 at 3 08 23 PM](https://user-images.githubusercontent.com/172800/90449096-91451d80-e09b-11ea-9564-9b5bb579ab5a.png)

Also, it seems like your test app does not retain a reference to the `Tray` object, meaning that it will be garbage-collected. Unfortunately, due to an awkward API design decision a while ago, you'll need to retain a reference to `tray`. For example:

```js
const { app, Menu, Tray } = require('electron')

let tray

app.whenReady().then(() => {
    let iconpath = 'assets/tray.png'
    if (process.platform === 'darwin') {
        iconpath = 'assets/trayTemplate.png'
    }
    tray = new Tray(iconpath)
    const contextMenu = Menu.buildFromTemplate([
        { label: 'Item1', type: 'radio' },
        { label: 'Item2', type: 'radio' },
        { label: 'Item3', type: 'radio', checked: true },
        { label: 'Item4', type: 'radio' }
    ])
    tray.setToolTip('Test tray application')
    tray.setContextMenu(contextMenu)
})
```

**Comment by zcbenz** [comment]
I'm unable to reproduce on macOS 10.12, I'll try to setup a 10.13 VM.

**Comment by zcbenz** [comment]
I'm unable to reproduce on macOS 10.13.6.
<img width="314" alt="Screen Shot 2020-09-10 at 16 11 11" src="https://user-images.githubusercontent.com/639601/92693283-5d9aa200-f380-11ea-8942-261c823fb546.png">

**Comment by robskie** [comment]
@zcbenz Can you check if we have the same system version, macOS 10.13.6 (17G14019)? I'll try to reproduce this on a freshly installed macOS 10.13.6, and post an update later.

**Comment by robskie** [comment]
I can reproduce the bug on a freshly installed macOS 10.13.6 (17G66) on mac mini (mid 2011).

**Comment by zcbenz** [comment]
@robskie Yeah I'm using macOS 10.13.6 (17G66), but I'm running it in a virtual machine.

And to confirm, are you reproducing the bug with the https://github.com/robskie/macos-tray-bug app?

**Comment by robskie** [comment]
Yes, I'm using https://github.com/robskie/macos-tray-bug to reproduce the bug.

**Comment by ValentinSteiner** [comment]
I can reproduce the problem on 10.13.6 (17G14042) using Electron 13.0.1 and the provided reproducer (https://github.com/robskie/macos-tray-bug).
