### ISSUE TITLE
Cannot read property 'show' of undefined on startup

### ISSUE THREAD

**Issue by jan-scorl** [electron/electron#24967]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 8.2.3
  * 
* **Operating System:** macOS Catalina 10.15.6
  * 
* **Last Known Working Electron version:**
  * 

### Expected Behavior

I would expect the build to run on someone else's machine as well.

### Actual Behavior

If I build the app (dmg), it runs flawlessly on my machine (macOS Catalina). However, if I send it to my friend (same version of macOS), he gets the following error when trying to open it (screenshot)

### To Reproduce

I've attached the link to the release so you can see if you receive the same error when opening it.

https://github.com/kollektive-technology/awake/releases/download/v0.0.4/Awake-0.0.4.dmg

### Screenshots

![WhatsApp Image 2020-08-13 at 10 00 11](https://user-images.githubusercontent.com/17554280/90115323-34243180-dd54-11ea-8148-25c08f761e47.jpeg)

**Comment by zcbenz** [comment]
Errors like this are usually caused by mistakes in the app, please try to find out the root cause of the issue yourself, we unfortunately do not have too much resources to debug users' apps.

**Comment by jan-scorl** [comment]
What do you mean with 'mistake in the app'? 

The build runs perfectly fine on my own machine. It also runs fine on my own machine using a different user account that doesn't have node, electron or any other dependency installed. However, every person that I have sent the build, gets this error on startup. The app is signed and notarised. I can't reproduce this error on my own machine. Does anyone have a clue what it could be related to?
