### ISSUE TITLE
Print dialog doesn't close when the window that's being printed closes

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#24961]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 9.0.4
* **Operating System:** Windows 10 (1909)
* **Last Known Working Electron version:** not sure

### Expected Behavior
When the print dialog is showing for a window, I expect that it be dismissed when the window closes (programmatically or via clicking X)

### Actual Behavior
The dialog doesn't close. Seems like selecting a printer though causes it to go away without doing anything. The print callback does get called however.

### To Reproduce
1. npm start the app below
2. In the devtools, open a window (`window.open("https://google.com")`)
3. Close the window
4. Observe that the the print dialog doesn't close

main.js:

```
(async () => {
  const {app, BrowserWindow} = require("electron");

  await app.whenReady()

  const window = new BrowserWindow({ webPreferences: { nativeWindowOpen: true }});
  await window.loadURL("https://google.com");
  window.webContents.openDevTools();

  app.on("browser-window-created", (e, win) => {
    win.webContents.print({}, () => {
      console.log("called");
    });
  });
})();
```

**Comment by pushkin-** [comment]
Even when doing an `app.quit()`, the print dialog stays up and the application doesn't quit:

```
(async () => {
  const {app, BrowserWindow} = require("electron");

  await app.whenReady()

  const window = new BrowserWindow({ webPreferences: { nativeWindowOpen: true }});
  await window.loadURL("https://google.com");
  window.webContents.print();

  setTimeout(() => {
    app.quit();
  }, 5000);
})();
```

**Comment by pushkin-** [comment]
repros in Electron 21

**Comment by pushkin-** [comment]
repros in v22. [gist](https://gist.github.com/f539c83d87f747357b504d9b63ecbe5f)

**Comment by codebytere** [comment]
@pushkin- this is not a bug unfortunately - it's intended behavior and matches Chromium. We'd prefer to match upstream printing behavior (we mostly shell out to upstream logic) but if this changes upstream i'm happy to reconsider.
