### ISSUE TITLE
Menu item can not display whole sublabel 

### ISSUE THREAD

**Issue by webarchymeta** [electron/electron#24974]
We use a `Tray` in one of our projects. The `MenuItem` inside of it has a `label` and `sublabel` with the `sublabel` assigned a relatively long text string.

In the pre-10.x versions of the **electron**, the popup menu will auto resize itself so that the longest `sublabel` content is visible. However the current beta version (10.x) has a default size for the popup menu of its own and it will clip the `sublabel` texts by default.

The question is: is there any way that the auto-resizing behavior of previous versions be restored or is there aditional parameters the one can set to make it happen?

**Comment by zcbenz** [comment]
Which operating systems are having this issue? And can you provide some screenshots?

**Comment by webarchymeta** [comment]
OS: Windows 10 (1909)

The following is a screenshot:

![screen-shot-1](https://user-images.githubusercontent.com/3250215/90385349-8f885380-e0b5-11ea-8f14-fd5c7fc16149.png)

**Comment by nornagon** [comment]
This seems like it might be an OS limitation. Have you tried any other versions of Windows 10?

**Comment by webarchymeta** [comment]
I don't have earier version of Windows any more. For newer versions, I tested on a machine with Windows 10 (2004) installed and it still is cliping the sublabels ...

**Comment by cln650** [comment]
any updates?
