### ISSUE TITLE
A 'moved' event on Windows

### ISSUE THREAD

**Issue by reinhold-b** [electron/electron#24979]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

On the Electron docs I found a ['moved'](https://www.electronjs.org/docs/api/browser-window#event-moved-macos) event, which is only available on MacOS. I want to save the window position of my app in a config file, so that it loads at the same position when it is created the next time. As there only is a 'move' event available for Windows, I have to save the position while the window is moving, which can lead to small lags and unnecessary computations.

### Proposed Solution

A similar ['moved'](https://www.electronjs.org/docs/api/browser-window#event-moved-macos) event (MacOS) would be extremely helpful for Windows machines, as you could use it to save the window position once after moving it rather than saving multiple times while moving the window.

### Additional Information

System: Windows 10

**Comment by MarshallOfSound** [comment]
> as you could use it to save the window position once after moving it rather than saving multiple times while moving the window.

Just as a temporary workaround you could use the `move` event but debounce your `fs.write` call so that it only writes it once it hasn't moved for ~300ms or whatever value you choose.

**Comment by reinhold-b** [comment]
@MarshallOfSound Yes that's a good work-around! Perhaps a `moved` event would be a bit more intuitive and quicker to implement in your apps.

**Comment by locomoco28** [comment]
I am looking for the same feature so I can detect when the window stopped moving so I can get the current position and move it to the edge (I want to make an overlay that sticks to the edge of the screen only)

**Comment by BenRussert** [comment]
> save the position while the window is moving, which can lead to small lags and unnecessary computations

@reinhold-b  Another thing to try would be storing the last position in a variable (memory not on disc) during the `move` callback, then writing the config file to disk whenever the window is hidden/destroyed, app quit, etc to fit your needs.

**Comment by locomoco28** [comment]
> 
> 
> > save the position while the window is moving, which can lead to small lags and unnecessary computations
> 
> @reinhold-b Another thing to try would be storing the last position in a variable (memory not on disc) during the `move` callback, then writing the config file to disk whenever the window is hidden/destroyed, app quit, etc to fit your needs.

I actually discovered a library for that: [electron-window-state](https://github.com/mawie81/electron-window-state)

I solved my problem using https://github.com/electron/electron/issues/1354#issuecomment-404348957
Not having the OS's window drag features like fullscreen on double click etc was helpful bcz it was just bugging my overlay smh

**Comment by reinhold-b** [comment]
@MarshallOfSound @BenRussert @locomoco28 Thank you for your solutions, I think I will stick to using the variable one though, which sounds pretty simple to implement. If that doesn't work using a library as mentioned by @locomoco28 might be a good idea! Anyways thank you!
