### ISSUE TITLE
Crash when use mangifier in Windows10 with electron 9.2.0

### ISSUE THREAD

**Issue by breakinferno** [electron/electron#24978]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  * 9.2.0
* **Electron-builder Version:** 
  *  latest
* **Operating System:**
  *  Windows 10 (1903) 
* **Last Known Working Electron version:**
  *  Electron 8.5.0

### Expected Behavior

When I started the app and used the built-in magnifying glass in Windows, both ran well at the same time

### Actual Behavior

When I zoom in and out of the Windows magnifier, the application exits, and give me 3221226525 exit  status

### To Reproduce

```javascript
// main.js
let win;

app.whenReady().then(() => {
    win = new BrowserWindow({
        width: 800,
        height: 600
    }).loadURL('https://www.google.com');
    const view = new BrowserView({
        webPreferences: {}
    })
    // win.view = view. // If I comment this line of code, everything works fine, but if I use this line of code, the app crashes when i use mangifier
})

```

### Additional Information

I found it reproduce in windows 10 (190x) and electron 9.2.0。 when downgrade to electron 8.5.0, it's won't crash.

**Comment by nornagon** [comment]
Can you collect a crash dump by any chance? Either using `crashReporter` or through WER: https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps

**Comment by StaZhu** [comment]
facing same issue....

**Comment by pushkin-** [comment]
I can't repro this myself, but you can get a crash dump by adding this code early on in your main method:

```
const { crashReporter, app } = require("electron");
app.setPath("crashDumps", "<some path>");
crashReporter.start({ submitURL: "http://nowhere", uploadToServer: false });
```
