### ISSUE TITLE
ide=vs2017 error

### ISSUE THREAD

**Issue by mih30vip** [electron/electron#24972]
os: win10
msvc: vs2017

>gn gen out/Debug-x86 --ide=vs2017 --args="import(\"//electron/build/args/all.gn\") target_cpu=\"x86\""
ERROR at //electron/BUILD.gn:302:1: Dependency not allowed.
source_set("electron_lib") {
^---------------------------
The item //electron:electron_lib
can not depend on //third_party/webrtc/modules/desktop_capture:desktop_capture
because it is not in //third_party/webrtc/modules/desktop_capture:desktop_capture's visibility list: [
  //third_party/webrtc/*
  //third_party/webrtc_overrides/*
]

why?

**Comment by MarshallOfSound** [comment]
@mih30vip You have set `is_component_build` to `true`, we do not support that build configuration

**Comment by mih30vip** [comment]
> @mih30vip You have set `is_component_build` to `true`, we do not support that build configuration

It seems not work!!!


gn gen out5/all --args="import(\"//electron/build/args/all.gn\") target_cpu=\"x86\" is_component_build=true" --ide=vs2017
ERROR at //electron/BUILD.gn:302:1: Dependency not allowed.
source_set("electron_lib") {
^---------------------------
The item //electron:electron_lib
can not depend on //third_party/webrtc/modules/desktop_capture:desktop_capture
because it is not in //third_party/webrtc/modules/desktop_capture:desktop_capture's visibility list: [
  //third_party/webrtc/*
  //third_party/webrtc_overrides/*
]

**Comment by mih30vip** [comment]
@MarshallOfSound 

It seems not work!!!

gn gen out5/all --args="import("//electron/build/args/all.gn") target_cpu="x86" is_component_build=true" --ide=vs2017
ERROR at //electron/BUILD.gn:302:1: Dependency not allowed.
source_set("electron_lib") {
^---------------------------
The item //electron:electron_lib
can not depend on //third_party/webrtc/modules/desktop_capture:desktop_capture
because it is not in //third_party/webrtc/modules/desktop_capture:desktop_capture's visibility list: [
//third_party/webrtc/*
//third_party/webrtc_overrides/*
]
