### ISSUE TITLE
Fix ESM Usage

### ISSUE THREAD

**Issue by frank-dspeed** [electron/electron#24971]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
Current master
dynamic import is not supported while it is supported in NodeJS Modules and CJS

* **Electron Version:**
  * 
* **Operating System:**
  * 
* **Last Known Working Electron version:**
  * 

### Expected Behavior

import('') loads ESM and CJS

### Actual Behavior

Does Error when loading ESM and CJS
### To Reproduce

use import('./your-url.js')

**Comment by MarshallOfSound** [comment]
Duplicate #21457
