### ISSUE TITLE
how to debug with vs2017

### ISSUE THREAD

**Issue by mih30vip** [electron/electron#24989]
os: windows10
ide: vs2017

I want to debug electron by single step.
make the sln by "is_component_build=false, symbol_level = 1".

But, when I debug by single step, I can not watch locate variable value.

How do you debug by single step with vs???

**Comment by zcbenz** [comment]
I think you probably need to set `is_debug=true`.

**Comment by mih30vip** [comment]
> I think you probably need to set `is_debug=true`.

I set `is_component_build=false symbol_level=1 is_debug=true` and it not work also. ( in vs2017 single step, I can not watch locat e variable).

`symbol_level=1` , it not include all symbos information, (not full symbol).

But, `is_component_build=false` and `symbol_level=2` are conflict.

So, how to do ?

**Comment by bigben0123** [comment]
On electron 9,  build and Step debug is ok.

```
import("all.gn")
is_debug = true
is_component_build = false
is_component_ffmpeg = true
is_official_build = false
dcheck_always_on = true
symbol_level = 1
```
