### ISSUE TITLE
Bug with .d.ts file

### ISSUE THREAD

**Issue by DeltaStudioApp** [electron/electron#24986]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.2.0
* **Operating System:**
  * Windows 10 2004
* **Last Known Working Electron version:**
  * 9.2.0

### Expected Behavior
Just work.

### Actual Behavior
This: node_modules/electron/electron.d.ts(3689,26): error TS2689: Cannot extend an interface 'NodeJS.EventEmitter'. Did you mean 'implements'?

### To Reproduce
Remove lodash from your project and install it again. Also update electron and other dependencies

https://github.com/electron/electron-quick-start

**Comment by MarshallOfSound** [comment]
You are depending on the incorrect version of @types/node.  Ensure you are depending on ^12

**Comment by DeltaStudioApp** [comment]
I'll try. Thanks Marshall!
