### ISSUE TITLE
Calls to ref-napi ref.reinterpretUntilZeros fail after upgrading to Electron 8.5.0 from 7.3.0

### ISSUE THREAD

**Issue by Antelope-IT** [electron/electron#24981]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.5.0
* **Operating System:**
  * Windows 10 (2004)
* **Last Known Working Electron version:**
  * v7.3.0

### Expected Behavior
When running Electron v8.5.0 when I call the method `ref.reinterpretUntilZeros(windowTextBuffer, wchar.size)` from the ref-napi library with valid parameters I expect the call to succeed as per v7.30

### Actual Behavior
When run Electron v8.5.0 when the method above executes the Electron app crashes and is closed. An error message is written to the console log
```
#
# Fatal error in , line 0
# ignored
#
#
#
#FailureMessage Object: 000000A41535C3D0 
```
### To Reproduce

1. On Windows create a default Electron App v7.3.0
2. Add a reference to the npm active-win library v6.1.0
3. In main add a call to activeWin.sync()

This should return the details of the active window.

4. Upgrade the version of Electron to v8.5.0 version of ref-napi are expected to be the same after the upgrade v1.4.3?
5. Run the code - expected to fail at line 92 (see screenshot below)

### Screenshots

![image](https://user-images.githubusercontent.com/16248321/90273033-353d8780-de56-11ea-912c-e53cda616dd7.png)

### Additional Information
The issue was first identified here sindresorhus/active-win#68,  Since when you upgrade to Electron 8.5.0 the versions of ref-napi and activeWin are the same as before the upgrade and as stated in the issue reference the code works in Node but not Electron and in Electron v7 and not Electron v8 this would seem to indicate that a change in the Electron ecosystem between v7 and v8 is the likely cause.

**Comment by zcbenz** [comment]
Can you provide a simple app that can reproduce this issue, I'm not quite sure from your descriptions.

**Comment by Antelope-IT** [comment]
As requested - Unzip  each quick-start-electron app (attached below) on a Windows machine and run.

```
npm i
npm start
``` 

This will work with the version using Electron v 7.3.0 and fail when using Electron v 8.5.0 . The error is shown in the image below. 

![image](https://user-images.githubusercontent.com/16248321/90367551-ddbf3780-e060-11ea-8da5-133e8326387d.png)

To create these example apps, I did the following:
* Cloned the electron quick start app 
* Installed electron v7.3.0 
* Added an npm reference to active-win and electron-rebuild 
* npm run electron-rebuild 
* In main.js required('active-win') and added a call to activeWin.sync() in main.js on line 30. 

The app works - Zipped as  (**It_Works_With_Electron_v_7_30**). 

Next: 
* Upgrade the version of Electron to v 8.5.0 

The app now fails - Zipped as (**It_Fails_With_Electron_v_8_50**)

If you debug this you should see that the app fails when it calls actveWin.sync() in main.js line: 30 - Because the call to ref.reinterpretUntilZeros fails in ./node_modules/active-win/lib/windows.js line 92 as shown in the image above (in the original issue description) and as described here https://github.com/sindresorhus/active-win/issues/68.

Since the only thing that changes between the two apps is the version of Electron it seems to be an issue with Electron.
   
[It_Works_With_Electron_v_7_30.zip](https://github.com/electron/electron/files/5082625/It_Works_With_Electron_v_7_30.zip)
[It_FAILS_With_Electron_v_8_50.zip](https://github.com/electron/electron/files/5082626/It_FAILS_With_Electron_v_8_50.zip)

**Comment by Antelope-IT** [comment]
Just to add further  to this - quick testing with versions 9.3 and 10.1.1 of Electron seem to fail also with the same error. In version 10 the error output seems to be  more descriptive as it outputs the following with line 10 naming the offending function.

```
#
# Fatal error in , line 0
# ignored
#
#
#
#FailureMessage Object: 000000C8EDCFCF00
 1: 00007FF6976146AF node::Buffer::New+128031
 2: 00007FF69735E9BA IsSandboxedProcess+641274
 3: 00007FF6957CCDF1 v8::Platform::SystemClockTimeMillis+414209
 4: 00007FF695513CA1 v8::ArrayBuffer::New+497
 5: 00007FF695513B7E v8::ArrayBuffer::New+206
 6: 00007FF6975F5487 node::Buffer::New+503
 7: 00007FF6975F5372 node::Buffer::New+226
 8: 00007FF6984652E8 napi_create_external_buffer+216
 9: 00007FFD6D5A2AF0 `anonymous namespace'::WrapPointer+128 [c:\tmp\electron-quick-start\node_modules\ref-napi\src\binding.cc]:L106
10: 00007FFD6D5A3F0F `anonymous namespace'::ReinterpretBufferUntilZeros+207 [c:\tmp\electron-quick-start\node_modules\ref-napi\src\binding.cc]:L423
11: 00007FFD6D5A7969 Napi::details::WrapCallback<<lambda_4b130013be4a466940e6fe08d32cda83> >+73 [c:\tmp\electron-quick-start\node_modules\ref-napi\node_modules\node-addon-api\napi-inl.h]:L76
12: 00007FFD6D5A7873 Napi::details::CallbackData<Napi::Value (__cdecl*)(Napi::CallbackInfo const &),Napi::Value>::Wrapper+51 [c:\tmp\electron-quick-start\node_modules\ref-napi\node_modules\node-addon-api\napi-inl.h]:L99
13: 00007FF6990E647A napi_create_function+1082
14: 00007FF69555B0DE v8::CFunction::CFunction+233422
15: 00007FF69555A53B v8::CFunction::CFunction+230443
16: 00007FF695559BE0 v8::CFunction::CFunction+228048
17: 00007FF695559867 v8::CFunction::CFunction+227159
18: 00007FF695F7707C v8_inspector::V8StackTraceId::ToString+3453836
19: 00007FF695F0B975 v8_inspector::V8StackTraceId::ToString+3013765
20: 00007FF695F029DF v8_inspector::V8StackTraceId::ToString+2977007
21: 00007FF695F0B975 v8_inspector::V8StackTraceId::ToString+3013765
22: 00007FF695F0B975 v8_inspector::V8StackTraceId::ToString+3013765
23: 00007FF695F0B975 v8_inspector::V8StackTraceId::ToString+3013765
24: 00007FF695F029DF v8_inspector::V8StackTraceId::ToString+2977007
25: 00007FF695FC0FD8 v8_inspector::V8StackTraceId::ToString+3756776
26: 00007FF695F2BFFA v8_inspector::V8StackTraceId::ToString+3146506
27: 00007FF695F0932C v8_inspector::V8StackTraceId::ToString+3003964
28: 00007FF69561AF81 v8::Unwinder::PCIsInV8+2705
29: 00007FF69561BA1F v8::Unwinder::PCIsInV8+5423
30: 00007FF69561BB26 v8::Unwinder::PCIsInV8+5686
31: 00007FF69563FBB3 v8::Unwinder::PCIsInV8+153283
32: 00007FF69563F98F v8::Unwinder::PCIsInV8+152735
33: 00007FF6975D0DDD node::InternalCallbackScope::Close+285
34: 00007FF6975D10F2 node::InternalCallbackScope::Close+1074
35: 00007FF6975D14E5 node::MakeCallback+229
36: 00007FF6975D13CE node::MakeCallback+158
37: 00007FF6975D12FA node::MakeCallback+138
38: 00007FF694953318 v8::internal::OSROptimizedCodeCache::OSROptimizedCodeCache+206488
39: 00007FF694815A30 cppgc::Platform::PostJob+7584
40: 00007FF694815911 cppgc::Platform::PostJob+7297
41: 00007FF69480B412 node::InternalCallbackScope::MarkAsFailed+2706
42: 00007FF69480B376 node::InternalCallbackScope::MarkAsFailed+2550
43: 00007FF6948B48CC v8::CpuProfile::GetSamplesCount+1052
44: 00007FF6948C940F v8_inspector::V8InspectorClient::memoryInfo+37327
45: 00007FF6962BB01B v8_inspector::V8StackTraceId::ToString+6877995
46: 00007FF6966A3E7F v8_inspector::V8StackTraceId::ToString+10977679
47: 00007FF6962B9FC5 v8_inspector::V8StackTraceId::ToString+6873813
48: 00007FF6962BC824 v8_inspector::V8StackTraceId::ToString+6884148
49: 00007FF6962B8861 v8_inspector::V8StackTraceId::ToString+6867825
50: 00007FF69619626F v8_inspector::V8StackTraceId::ToString+5678463
51: 00007FF696195DC3 v8_inspector::V8StackTraceId::ToString+5677267
52: 00007FF69732812B IsSandboxedProcess+417899
53: 00007FF69542A99E v8::Location::GetColumnNumber+781934
54: 00007FF69480149F Ordinal0+5279
55: 00007FF69A899BD2 uv_random+16902610
56: 00007FFD99856FD4 BaseThreadInitThunk+20
57: 00007FFD9B5DCEC1 RtlUserThreadStart+33
```
So it might be worth adding the 9-x-y and 10-x-y tags also. 

For reference repeat of the above for Electron 9 and 10. - the version 10 has the latest version of electron-builder also because I rebuilt the project from scratch just in case. 

[It_FAILS_With_Electron_v_9_30.zip](https://github.com/electron/electron/files/5209297/It_FAILS_With_Electron_v_9_30.zip)
[It_FAILS_With_Electron_v_10_1_1.zip](https://github.com/electron/electron/files/5209299/It_FAILS_With_Electron_v_10_1_1.zip)

**Comment by geekuillaume** [comment]
I'm having the same problem with https://github.com/geekuillaume/soundsync. Did anyone found a fix?
