### ISSUE TITLE
Frameless application covers buttons on the edge of the screen

### ISSUE THREAD

**Issue by J-Bollie** [electron/electron#24985]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.5
* **Operating System:**
  * Windows 10 (1803)
* **Last Known Working Electron version:**
  * None

### Expected Behavior
When hovering the button setting the cursor to pointer and being able to click the button

### Actual Behavior
The bottom 20px of the button are not clickable because of an invisible border, happens to the buttons close to the top as well.

### To Reproduce
![ee](https://user-images.githubusercontent.com/48119536/90315439-e3f7cb80-df1b-11ea-9686-8ff0d47c3034.png)

### Additional Information
The red box in the screenshot is the part that is not registered within this application, when making the height of the window larger, this whole button becomes usable like it should

**Comment by zcbenz** [comment]
It is a bit hard to understand the issue, can you provide a simple app that can reproduce this issue?

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
