### ISSUE TITLE
webContents‘s will-prevent-unload event is helpless for true use

### ISSUE THREAD

**Issue by xland** [electron/electron#24994]
When developers use webContents‘s `will-prevent-unload` event,
They want to ask the user to confirm something most of the time.
Like this:
```javascript
win.webContents.on('will-prevent-unload', event => {
    let choice = dialog.showMessageBoxSync({
      title:'do you want to close',
      buttons:['cancel','yes']
    });
    if(choice === 1)  event.preventDefault();
    //...
  })
```
Actually,They can not use `dialog.showMessageBoxSync`,
because `dialog.showMessageBoxSync` is synchronous,
It will block the main process event loop, and cause some unpredictable problems.

But They can not use the asynchronous method `dialog.showMessageBox` either,
because `dialog.showMessageBox` can not prevent the `will-prevent-unload` event
Code:
```javascript
  win.webContents.on('will-prevent-unload', async event => {
    let choice = await dialog.showMessageBox({
      title:'do you want to close',
      buttons:['cancel','yes']
    });
    if(choice === 1) event.preventDefault();  //this code is useless
    //...
  })
```

**Comment by zcbenz** [comment]
I agree the API design is wrong. We should provide a callback to pass the result asynchronously.

**Comment by SimplyAhmazing** [comment]
@zcbenz I'm new to contributing to Electron, so I'd like to work on this

**Comment by aboutdevz** [comment]
good

**Comment by ashikvarma11** [comment]
@zcbenz  @SimplyAhmazing  Is anybody working on this issue now? If not, I would like to try this.

**Comment by SimplyAhmazing** [comment]
@ashikvarma11 I attempted to work on this issue but got stuck as I don't have Electron development experience and couldn't figure out an existing pattern to model a solution for this. Feel free to take it. I'd also be happy to pair with you on it if you know how to do it and can impart some knowledge.

**Comment by adilanchian** [comment]
Taking a look at this issue, I have some thoughts:

> I agree the API design is wrong. We should provide a callback to pass the result asynchronously.

Digging through the code I do see that `showMessageBox` I see this on the native side

```cpp
void ShowMessageBox(const MessageBoxSettings& settings,
                    MessageBoxCallback callback)
```
It looks as though there is already a callback in this method that can be passed in that looks like this:

```cpp
typedef base::OnceCallback<void(int code, bool checkbox_checked)>
    MessageBoxCallback;
```

With this information, I'm not actually sure what the full ask is here. Any insight on this would be awesome! Thanks in advance :)

**Comment by imrahul361** [comment]
@SimplyAhmazing If anyone has not taken this issue. I like to know how to do it. Please help

**Comment by nicktz1408** [comment]
Hello, what's the status of this? Is anyone working on it? I would love to give a helping hand!

**Comment by babapart** [comment]
thanks [باباپارت](https://babapart.com/)

**Comment by pushkin-** [comment]
bump

**Comment by AlexandraChibisov** [comment]
Hi, a new contributor, and I'd love to give this a try. Does anyone who has worked on this have any advice on where to look/start/read up on documentation?

**Comment by felipedejes** [comment]
``7933852@30940485// SPDX-License-Identifier: MIT
``

**Comment by pushkin-** [comment]
bump

**Comment by ddt313** [comment]
This is my workaround

``` javascript
// global variable
let allowReload = false;

win.webContents.on('did-finish-load', () => {
    allowReload = false;
})
win.webContents.on('will-prevent-unload', async event => {
  if (allowReload) {
    event.preventDefault();
    return;
  }

  let choice = await dialog.showMessageBox({
    title:'do you want to close',
    buttons:['cancel','yes']
  });
  if(choice === 1) {
    allowReload = true;
    win.webContents.reload();
  }
})
```

**Comment by xland** [comment]
@ddt313 老兄，你的方案和我知乎上发的方案很像。
https://zhuanlan.zhihu.com/p/415537267

**Comment by aromaG-hub** [comment]
Instead of relying on event.preventDefault(), we can close the window programmatically or perform any necessary actions after receiving the user's choice in the dialog. For example, we can use win.close() to close the window if the user confirms.

**Comment by aromaG-hub** [comment]
Instead of relying on event.preventDefault(), we can close the window programmatically or perform any necessary actions after receiving the user's choice in the dialog. For example, we can use win.close() to close the window if the user confirms.
Also, we use try-catch block to handle the possible errors.

`win.webContents.on("will-prevent-unload", async (event) => {
  event.preventDefault();

  try {
    const choice = await dialog.showMessageBox({
      title: "Do you want to close?",
      buttons: ["Cancel", "Yes"],
    });

    if (choice.response === 1) {
      win.close(); // Close the window if the user confirms
    }
  } catch (error) {
    console.error("Error displaying message box:", error);
  }
});
`

**Comment by aromaG-hub** [comment]
Instead of using event.preventDefault(), we can close the window programmatically or perform any necessary actions after receiving the user's choice in the dialog. For example, we can use win.close() to close the window if the user confirms.
Also, we use try-catch block to handle the possible errors.

```javascript
win.webContents.on("will-prevent-unload", async (event) => {
event.preventDefault();

try {
const choice = await dialog.showMessageBox({
title: "Do you want to close?",
buttons: ["Cancel", "Yes"],
});

if (choice.response === 1) {
  win.close(); // Close the window if the user confirms
}
} catch (error) {
console.error("Error displaying message box:", error);
}
});
``` 
I hope this helps.
