### ISSUE TITLE
Not able to detect if the application is running on Electron in debugger mode

### ISSUE THREAD

**Issue by prateekjsingh** [electron/electron#24990]
Hello ,

We are using an electron app where we want to determine if the application is running on Electron or not.

For this we are using the following code :
 
**const userAgent = navigator.userAgent.toLowerCase();
return userAgent.indexOf(' electron/') > -1;** 

When the application developer tools are switched on, the application resolves userAgent as below:

**mozilla/5.0 (linux; android 6.0; nexus 5 build/mra58n) applewebkit/537.36 (khtml, like gecko) chrome/73.0.3683.121 mobile safari/537.36**

![image](https://user-images.githubusercontent.com/67387382/90346884-744c1400-dfe1-11ea-8542-11ff8155f263.png)

 The above value doesn't have an electron reference.

When the application developer tools are switched off, the application resolves userAgent as below:

**mozilla/5.0 (macintosh; intel mac os x 10_15_6) applewebkit/537.36 (khtml, like gecko) chrome/73.0.3683.121 electron/5.0.1 safari/537.36**

![image](https://user-images.githubusercontent.com/67387382/90346892-8928a780-dfe1-11ea-9e80-73c141666ee8.png)

We want to trigger different logics for different device types using the same shared Component checking the Device type.
Since this behaves incorrectly in debugger, we have to now use process variable to determine if electron is being used.

Thanks
Prateek

**Comment by ckerr** [comment]
Hi, thanks for reaching out!

https://github.com/electron/electron/issues/2288 has some ideas on how an app can sniff out whether it's running in an Electron environment. I hope this helps!
