### ISSUE TITLE
The window's edges become transparent after restore SOMETIMES

### ISSUE THREAD

**Issue by o-oasis** [electron/electron#24992]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  8.1.1
* **Operating System:**
  * win7
* **Last Known Working Electron version:**
  * 8.1.1

### Expected Behavior
The window should always be normal after restore.

### Actual Behavior
The window's edges become transparent after restore SOMETIMES.

### To Reproduce
We can't find a certain way to reproduce it.Some computers never have this issue,but some computer often reproduce it.

### Screenshots
Normal:
![TIM截图20200817144018](https://user-images.githubusercontent.com/45780568/90365057-d6675080-e097-11ea-8a31-78b96139f617.png)

With issue:
![TIM图片20200817143823](https://user-images.githubusercontent.com/45780568/90364820-5b059f00-e097-11ea-9d6a-929725ae3138.png)

### Additional Information
The options for create window:
```
    mainWindow = new BrowserWindow({
        minHeight: 434,
        minWidth: 280,
        width: 280,
        height: 434,
        backgroundColor: 'white',
        titleBarStyle: 'hidden',
        title: '焦谈 - FocusTalk',
        frame: 'darwin' === process.platform,
        icon: path.join(__dirname, '/assets/icon.png'),
        show: false,
        acceptFirstMouse: true,
        center: true,
        resizable: true,
        maximizable: false,
        minimizable: false,
        hasShadow: true,
        id: 1,
        autoHideMenuBar: true,
        webPreferences: {
            webSecurity: false,
            nodeIntegration: true,
            preload: path.join(__dirname, '/script/preload.js'),
        },
    });
```

**Comment by zcbenz** [comment]
Hmm I'm afraid there is nothing we can do if there is no reliable way to reproduce the problem.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
