### ISSUE TITLE
Simple Mac App Store builds fail to run

### ISSUE THREAD

**Issue by bkervaski** [electron/electron#25005]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.2.0
* **Operating System:**
  * macOS 10.15.6
* **Last Known Working Electron version:**
  * 9.2.0 (darwin package, npm start)

### Expected Behavior

After running:

electron-packager MyApp MyApp --app-bundle-id=com.somewhere.myapp --helper-bundle-id=com.somewhere.myapp--platform=mas --icon=icons.icns --overwrite --osx-sign

And signing:

```
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Electron Framework"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib"
#codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Libraries/libnode.dylib"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Libraries/libEGL.dylib"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Libraries/libswiftshader_libEGL.dylib"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Libraries/libswiftshader_libGLESv2.dylib"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Libraries/libvk_swiftshader.dylib"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper.app/Contents/MacOS/$APP Helper"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper.app/"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (GPU).app/Contents/MacOS/$APP Helper (GPU)"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (GPU).app/"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (Plugin).app/Contents/MacOS/$APP Helper (Plugin)"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (Plugin).app/"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (Renderer).app/Contents/MacOS/$APP Helper (Renderer)"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (Renderer).app/"
codesign -s "$APP_KEY" -f --entitlements "$LOGINHELPER_PLIST" "$APP_PATH/Contents/Library/LoginItems/$APP Login Helper.app/Contents/MacOS/$APP Login Helper"
codesign -s "$APP_KEY" -f --entitlements "$LOGINHELPER_PLIST" "$APP_PATH/Contents/Library/LoginItems/$APP Login Helper.app/"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$APP_PATH/Contents/MacOS/$APP"
codesign -s "$APP_KEY" -f --entitlements "$PARENT_PLIST" "$APP_PATH"
```

MyApp.app should run as expected.

### Actual Behavior
Crashes with:

```
Crashed Thread:        23  ThreadPoolSingleThreadForegroundBlocking0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Trace/BPT trap: 5
Termination Reason:    Namespace SIGNAL, Code 0x5
Terminating Process:   exc handler [97307]
```

### To Reproduce

Using the steps from https://www.electronjs.org/docs/tutorial/mac-app-store-submission-guide

Simple app in which main.js only has winObject.loadFile() or winObject.loadURL().

```
const {app, BrowserWindow} = require('electron')

function createWindow () {
  // Create the browser window.
  const win = new BrowserWindow({
    title: 'MyApp',
    backgroundColor: '#000000',
    width: 350,
    height: 675,
    minWidth: 350,
    minHeight: 675,
    webPreferences: {
      devTools: false,
      // zoomFactor: 0.9,
    }
  })

  // win.loadURL('https://any.url/index.html') 
  win.loadFile('www/index.html')
  // win.webContents.openDevTools()
}

app.whenReady().then(() => {
  createWindow()
  app.on('activate', function() {
    if(BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', function () {
  app.quit()
})
```

I've spent about 3 days on this, any help would be greatly appreciated :)

**Comment by bkervaski** [comment]
I also cloned [](https://github.com/electron/electron-quick-start), same process, same result.

**Comment by MarshallOfSound** [comment]
So full disclosure, I tried this thinking you were probably missing something.  But I ran into the exact same issue, tried various methods but I know for sure that MAS builds like, work, because as you've pointed out there are Electron apps in the store (Slack, Etc.)

Gonna look into this some more this week, I'm probably missing something obvious but our docs are *definitely* missing whatever it is too 😄

**Comment by MarshallOfSound** [comment]
Well actually my crash is slightly different, I get `EXC_CRASH (code signature invalid)` which is fun too I guess

**Comment by bkervaski** [comment]
Thanks @MarshallOfSound 👍 

I'm digging in again today attempting to build [electron-quick-start](https://github.com/electron/electron-quick-start) for mas, I'll share anything new.

**Comment by bkervaski** [comment]
Progress, appears to be related to this entitlement:

```
<key>com.apple.security.application-groups</key>
    <array>
      <string>YOUR_TEAM_ID.com.some.app</string>
    </array>
```

I didn't have "com.some.app" set to our bundle.  I did initially, but got sidetracked chasing code signing around the binaries and at some point must have set it back to the template.  

I *think* that if you just update the docs signing script with mine above it will fix it.

Submitting to the app store now and will follow up.

**Comment by bkervaski** [comment]
Approved! So yea, the docs just need updated.  Thanks for the help 👍

**Comment by MarshallOfSound** [comment]
@bkervaski Would you be down to try make a PR to update that doc?

**Comment by bkervaski** [comment]
Sure! Although I've never done it.  I have a couple other changes as well.  Testing 9.2.1, I'll attempt my first PR after Apple publishes.

**Comment by tylerveen** [comment]
https://github.com/electron/electron/issues/new/choose

**Comment by rudyrichter** [comment]
@MarshallOfSound did this get sorted out? i'm still actively failing to produce a sandboxed, hardened, code signed MAS and Developer ID binary using the electron-quick-start sample project.

**Comment by pauljonescodes** [comment]
@rudyrichter While it was my initial bias too based on Apple's usual behavior (I thought to myself, _of course_ MAS builds runtimes must be hardened), as it turns out this is not true, which is good, because I believe that it has something to do with JIT, which Electron may need. I'm sorry that's not more precise, but I can tell you that I have gotten a valid build submitted that does not have a hardened runtime.

https://developer.apple.com/documentation/security/hardened_runtime

For those who are having issues with signing and have found this thread as I did, you might benefit from the information here:

https://github.com/electron-userland/electron-builder/issues/4553#issuecomment-1967527022
