### ISSUE TITLE
webContents.print()'s pageRanges property is not honored

### ISSUE THREAD

**Issue by Linbubin** [electron/electron#25013]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.2.0
* **Operating System:**
  * win10
* **Last Known Working Electron version:**
  * 

### Expected Behavior
[this is config](https://www.electronjs.org/docs/api/web-contents#contentsprintoptions-callback)
The saved PDF has a custom `header`, and the `pageRanges` is work.

### Actual Behavior

`header` and `pageRanges` is not work.
### To Reproduce

[my electron fiddle](https://gist.github.com/36d96e2fe459dab8ffed2a764d751528)

### Screenshots

![image](https://user-images.githubusercontent.com/19225429/90504323-7d74e680-e183-11ea-86df-6f6925e77616.png)

### Additional Information

Finally, who can tell me how to determine the total number of pages generated by the printer system of Chrome?

**Comment by ckerr** [comment]
I'm seeing the same thing when running the gist in Fiddle on Windows 10 build 19041 with Electron 9.2.0 and Electron 10.0.0-beta.23

Options is

```js
{
silent: true,
deviceName: 'Microsoft Print to PDF',
pageRanges: { from: 0, to: 0 },
hander: 'headerrrrr',
footer: 'footerrrrr'
}
```

but all pages are added to the PDF instead of just the first one.

**Comment by Linbubin** [comment]
@codebytere  I copy the [code](https://gist.github.com/0c1c8affb9262ae83bde4d08d3401f0c) in my workspace, and click print, the app is exit.
![image](https://user-images.githubusercontent.com/19225429/91693122-21578c80-eb9d-11ea-8df8-412314d49d6f.png)

Also,when i add the options `silent: true`, the `print` is not work.

**Comment by carchrae** [comment]
it appears pageRanges is no longer (or was it ever?) working on ubuntu (20.04, and also 22.04)

i have tried with both electron `31.0.0` and `30.0.1` and electron builder `24.13.3`

my specific webcontents.print options:
```js
{
            pageSize: {
              width: 352 * 150,
              height: 352 * 300,
            },
            scaleFactor: 90,
            margins: {
              marginType: 'none'
            },
            silent: true,
            // NOTE: this does not appear to work!  :/
            pageRanges: [{from: 0, to: 0}],
}
```
