### ISSUE TITLE
Can't close browser window when detached devtools window is opened (electron 10)

### ISSUE THREAD

**Issue by Treverix** [electron/electron#25012]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
v10.0.0-beta.21
* **Operating System:**
  * 
Windows 10 (1909)
* **Last Known Working Electron version:**
  * 
v9.1.0

### Expected Behavior

If I have a browser window and a detached devtools window for that opened, then I can close the browser window and the devtools window closes also.

### Actual Behavior

I can't close the browser window. I have to manually close the detached devtools window first, then I can close the browser window.

**Comment by zcbenz** [comment]
I'm unable to reproduce this issue with following steps:
1. Open default app
2. Open devtools and detach it
3. Close the main window

Does this issue only happen within your app?

**Comment by Treverix** [comment]
Well. The quick-start application works for me too (updated to 10.0.0-beta.21)

But my application still has that effect and, maybe it's related, the DOM element hightlighting does not work anymore in my app. Like when I hover over a node in the Elements view in inspect mode, there's no highlighting, no tooltips on the browser window.

I try to replicate it now on the quick start by adding code that I use in my app one by one, checking if that cause the trouble but I'm pretty lost this time, as I don't really know which feature/API could potentially block the communication between browser window and devtools. Could be some electron code or it could also be an incompatible npm module.

At least, it's on all of my browser windows, of which some have svelte apps and some (most) simply show web pages from our external intranet applications. So it's one thing all browser windows have in common or it's something with the general electron app setup.

**Comment by zcbenz** [comment]
Thanks for debugging this issue, I can confirm it is a bug of Electron.

**Comment by zcbenz** [comment]
Also confirmed it is a Windows-only bug, it can be reproduced with this app:
https://gist.github.com/zcbenz/d8a36146cf57706959cf00252746d4a1

**Comment by rpsfonseca** [comment]
I may look into this, is that ok for you?

**Comment by RedHoodJT1988** [comment]
So this is an issue only for the Windows OS or does this happen on other OS's as well? I wouldn't mind helping out if it's Windows only as I use Windows daily. Let me know.

**Comment by bakhtiyorjon367** [comment]
hello

**Comment by pravichandran15** [comment]
In case if you are handling the close in Windows may be below can help,

 const currentWindow = window.require('electron').remote.getCurrentWindow();
                                if (currentWindow.isDevToolsOpened()) {
                                    currentWindow.closeDevTools();
                                }
                                currentWindow.close();

**Comment by PandaTsui** [comment]
> In case if you are handling the close in Windows may be below can help,
> 
> const currentWindow = window.require('electron').remote.getCurrentWindow();
> if (currentWindow.isDevToolsOpened()) {
> currentWindow.closeDevTools();
> }
> currentWindow.close();

Wow. This is an excellent solution in a temporary development environment

**Comment by backboy** [comment]
I am new to electron but have C++ and Java experience. Can I take this issue?

**Comment by willium** [comment]
> In case if you are handling the close in Windows may be below can help,
> 
> const currentWindow = window.require('electron').remote.getCurrentWindow();
> if (currentWindow.isDevToolsOpened()) {
> currentWindow.closeDevTools();
> }
> currentWindow.close();

It seems these methods aren't documented/typed anywhere. Is there a good place to look them up?

**Comment by stanleyxu2005** [comment]
Thank you for bringing this up. I can confirm this bug exists in v11.0, v11.1, v11.2 on Windows and this is the major reason prevents me to upgrade projects to latest Electron. 

Here is my version of workaround.
```
function fixBrowserWindowCannotCloseWhenDevToolsIsOpened(win) {
  // bug that main browser window cannot close, if devtools window is showing
  // https://github.com/electron/electron/issues/25012
  win.on('close', () => {
    if (win.webContents.isDevToolsOpened()) {
      win.webContents.closeDevTools()
    }
  })
}
```

Include it, call it and enjoy it!

**Comment by bromix** [comment]
Same issue for me with Electon 11.3.0 and frame = false. I used also the function to fix the problem...but I also need to call window.destroy().
If I create the electron application in staging or production, this problem doesn't occur.

**Comment by kutu** [comment]
fix for me was to set `show: false`, and then on `ready-to-show` event show the window, after that if devtools opened window closes as expected  and without delay

**Comment by cawa-93** [comment]
I can confirm this issue. **Electron v12.0.5**. Windows.

BrowserWindow with `autoHideMenuBar: true` or `frame: false` doest close if devTools opened (detached or attached). 

The window does not close either with native system controls or on call `require('@electron/remote').getCurrentWindow().close()`.

Workarounds that work for me:
1. I see a delay (about a second) between clicking the "close" button and actually closing the window.
```js
// main.js
  win.on('close', () => {
    if (win.webContents.isDevToolsOpened()) {
      win.webContents.closeDevTools()
    }
  })
```
2. The window closes instantly
```js
// main.js
  mainWindow = new BrowserWindow({ show: false });
  mainWindow.addListener('ready-to-show', () => mainWindow?.show());
```

**Comment by Migushthe2nd** [comment]
I am also unable to close the browser window with `autoHideMenuBar: true` set, but in my case even with `frame: true`. 
Electron version 12.0.2-12.0.7

**Comment by cawa-93** [comment]
This Issue Still relevant for v13.0.1

**Comment by ksshim86** [comment]
> In case if you are handling the close in Windows may be below can help,
> 
> const currentWindow = window.require('electron').remote.getCurrentWindow();
> if (currentWindow.isDevToolsOpened()) {
> currentWindow.closeDevTools();
> }
> currentWindow.close();

thank you!!

**Comment by asakiasako** [comment]
> fix for me was to set `show: false`, and then on `ready-to-show` event show the window, after that if devtools opened window closes as expected  and without delay
> 
> 
> 
> electron version 12.0.2

I think this is a better workaround, it works for my version 12.0.0

**Comment by quenchaman** [comment]
Can’t we fix this? These work-arounds cost time and money to our guild.

**Comment by hgouveia** [comment]
> fix for me was to set `show: false`, and then on `ready-to-show` event show the window, after that if devtools opened window closes as expected and without delay
> 
> electron version 12.0.2

this worked for me, this is still happening on electron version 13.1.6

**Comment by bjdash** [comment]
Wasted a lot of time trying to figure out why my window is not closing. Is there any plan to fix this?

**Comment by cawa-93** [comment]
Does this seem to have been fixed in 13.2.1? Can anyone check?

**Comment by stanleyxu2005** [comment]
> It seem to have been fixed in 13.2.1. Can anyone check?

I can confirm the bug is fixed with 13.2.1

**Comment by JoCat** [comment]
Very strange, but I got this error (and several others) just when upgrading to version 13
In package.json
```
"electron": "^13.2.2",
```

**Comment by gknapp** [comment]
This bug also exists in electron 11.5.0 (released August 31st 2021). @pravichandran15 workaround resolved `win.close()` not working.

**Comment by tekkimariani** [comment]
`"electron": "15.3.0",`

Still there.
