### ISSUE TITLE
Unable to to use the '&' character literally in menu labels

### ISSUE THREAD

**Issue by craxal** [electron/electron#25028]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.3.4
* **Operating System:**
  * All
* **Last Known Working Electron version:**
  * Unknown

### Expected Behavior
Some sort of way to escape the ampersand character when creating menu items.

### Actual Behavior
No (documented) way to escape ampersand characters. Electron always interprets ampersands as accelerators and strips them out of the label.

### To Reproduce
1. Create a menu item with "&" as the label.

**Comment by craxal** [comment]
Following up on this issue. Has anyone been able to look into this?

**Comment by mlaurencin** [comment]
The linked PR should contain the information you are looking for. This is an update to the Menu documentation which will be visible [here](https://www.electronjs.org/docs/api/menu). The PR also includes a gist of an example that can be run in Electron Fiddle or copy-pasted into electron-quick-start. You should be able to see the escaped and unescaped `&`s in different scenarios.
