### ISSUE TITLE
ipcRender is not working or ipc is null

### ISSUE THREAD

**Issue by southorange1228** [electron/electron#25035]
when i use ipcRender in render process,i find it doesnot work and get some error.
env: 
- macos 10.15.6
- electron 9.1.2
- webpack 4.44.1

now,start react app with webpack-dev-server and start electron app with child_process.spawn. And then 
```typescript
//   render process code
import React from 'react';
import { ipcRenderer } from 'electron';

const MockData = () => {
  const handleMockServer = () => {
    console.log(ipcRenderer.sendSync('synchronous-message', 'ping')); // prints "pong"
    ipcRenderer.on('asynchronous-reply', (event, arg) => {
      console.log(arg); // prints "pong"
    });
    ipcRenderer.send('asynchronous-message', 'ping');
  };
  return (
    <div>
      <h3>
        <button onClick={handleMockServer}>ok</button>
      </h3>
    </div>
  );
};

export default MockData;

```
click the button and get some error:
![image](https://user-images.githubusercontent.com/32590310/90605657-3fce9700-e231-11ea-9f59-cdba22669c8e.png)
![image](https://user-images.githubusercontent.com/32590310/90606023-cb482800-e231-11ea-87fa-9ec36d2b27ad.png)

i find some code in source code.
```typescript
//  electron/lib/render/api/ipc-renderer.ts
import { EventEmitter } from 'events';

const { ipc } = process._linkedBinding('electron_renderer_ipc');

const internal = false;

const ipcRenderer = new EventEmitter() as Electron.IpcRenderer;
ipcRenderer.send = function (channel, ...args) {
  return ipc.send(internal, channel, args);
};

//  ipc is null ???
ipcRenderer.sendSync = function (channel, ...args) {
  return ipc.sendSync(internal, channel, args)[0];
};

ipcRenderer.sendToHost = function (channel, ...args) {
  return ipc.sendToHost(channel, args);
};

ipcRenderer.sendTo = function (webContentsId, channel, ...args) {
  return ipc.sendTo(internal, false, webContentsId, channel, args);
};

ipcRenderer.invoke = async function (channel, ...args) {
  const { error, result } = await ipc.invoke(internal, channel, args);
  if (error) {
    throw new Error(`Error invoking remote method '${channel}': ${error}`);
  }
  return result;
};

ipcRenderer.postMessage = function (channel: string, message: any, transferables: any) {
  return ipc.postMessage(channel, message, transferables);
};

export default ipcRenderer;
```
what i should do? please help.

**Comment by southorange1228** [comment]
more info:
when i compiler source code and then package electron app. it will be ok.
i think my webpack config or electron config is wrong？？

**Comment by nguyenj** [comment]
Can you share your webpack config? Please provide as much as you can for others to attempt a reproduction of the issue.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by southorange1228** [comment]
ok.i think i canot start electron app with child_process.
And i try to start electron app with npm script. evenything is ok  :)
thinks
