### ISSUE TITLE
webcontents.print(options,callback) An object could not be cloned

### ISSUE THREAD

**Issue by acecoder1997** [electron/electron#25033]
### Preflight Checklist

* [√ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ √] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [√ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.2.0
* **Operating System:**
  *  Windows 10
* **Last Known Working Electron version:**

### Expected Behavior
 call the webcontents.print(options,callback) then work like the official document say

### Actual Behavior
throw exception electron/js2c/renderer_init.js:126 Uncaught (in promise) Error: An object could not be cloned.
    at EventEmitter.t.ipcRendererInternal.send.t.ipcRendererInternal.invoke

### To Reproduce
![image](https://user-images.githubusercontent.com/60084325/90603165-71ddfa00-e22d-11ea-8b64-27eaa729fdd4.png)

### Detail
official document 
```
const options = { silent: true, deviceName: 'My-Printer' }
win.webContents.print(options, (success, errorType) => {
  if (!success) console.log(errorType)
})
```
me
```
                const webview = document.querySelector("webview")
                webview.addEventListener('ipc-message', (event) => {
                    if (event.channel === 'webview-print-do') {
                        let options = {
                            silent: true,
                            copies: 2,
                            printBackground: true,
                            deviceName: 'MyPrinterName'
                        }
                        webview.print(options, (success) => {
                            console.log('callback', success);
                        })
                    }
                })
```
when i change the options object params into an Array like this [options ].
it work but the slient printing and callback is still not work(it also the same in version 4.0.0)

**Comment by codebytere** [comment]
@acecoder1997 you shouldn't use the webview tag to do this for now. This is a result of our move to the structured clone algorithm - plain object cannot be serializied across IPC.

**Comment by acecoder1997** [comment]
> @acecoder1997 you shouldn't use the webview tag to do this for now. This is a result of our move to the structured clone algorithm - plain objects cannot be serialized across IPC.

thank u for ur reply. and  how should i ues it ?

**Comment by acecoder1997** [comment]
@codebytere  thank u for ur reply. and how should i ues it ?

**Comment by jiyarong** [comment]
same issue with version 11, I need this callback, any solution?

**Comment by codebytere** [comment]
To further work on this, i'd need a reproducible piece of code that reliably generates the error, e.g a github Gist i could run in [Fiddle](https://github.com/electron/fiddle).

**Comment by zhangxu924** [comment]
> To further work on this, i'd need a reproducible piece of code that reliably generates the error, e.g a github Gist i could run in [Fiddle](https://github.com/electron/fiddle).

It seems that this problem is very easy to reproduce. Simply use webview.print(option, callback). Without the callback param it works. But we need the callback function to know if the printing has finished. The printing API is one of the major reason we are using electron now. Could you please fix it.

**Comment by codebytere** [comment]
Folks, if you look at documentation you see that this was converted to [use Promises](https://github.com/electron/electron/blob/46f3491c7d5d2ec669fac28298280129c449561e/docs%2Fapi%2Fwebview-tag.md#L569) several versions ago. There is no longer a callback. Using something like:

```js
const wv = document.getElementById('wv')

const emittedOnce = (element, eventName) => new Promise(resolve => {
      element.addEventListener(eventName, event => resolve(event), { once: true })
    })

emittedOnce(wv, 'dom-ready').then(() => {
  wv.print({
    copies: 2,
  }).then((success) => {
    console.log('callback', success);
  })
})
```

works just fine.
