### ISSUE TITLE
document.referrer is undefined on popup window

### ISSUE THREAD

**Issue by danielrea** [electron/electron#25061]
* **Electron Version:**
  * 9.1.0
* **Operating System:**
  * macOS catalina 10.15.6

### Expected Behavior
External site is loaded via window.loadURL, when a popup is opened from this external site, the popup window document.referrer set as the initial external site.

### Actual Behavior
Popup does not have document.referrer. This remains true even if I hijack the webRequest.onBeforeSendHeaders and set the referer header there, the header is correctly sent to the popup but document.referrer is still undefined.

### To Reproduce
- Load external site
- Open a popup from this site
- Check document.referrer on the popup

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

**Comment by danielrea** [comment]
No problem, I have attached a minimal reproduction of the issue https://github.com/danielrea/electron-referrer-popup-issue

**Comment by PhABC** [comment]
Any update on this @sofianguy ?
