### ISSUE TITLE
Application crashes when using setCertificateVerifyProc with axios

### ISSUE THREAD

**Issue by IFormiga** [electron/electron#25067]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  "electron": "^8.2.5",
* **Operating System:**
  *  Windows 10
* **Last Known Working Electron version:**
  * 

### Expected Behavior

The application not to crash when using axios.
### Actual Behavior

When callback is anything different than 0 all I get is the application crashing.
### To Reproduce

We set in the setCertificateVerifyProc this method for certificate validation. But when I get anything other than 0 using axios the application crashes.
```
public certificateVerifyCallback(certificate: string) {
		let cert1= certificate || config.cert1;
		let cert2= certificate || config.cert2;

		return (request, callback) => {

			const { hostname } = request;

			if (hostname.includes('whatever.com') && hostname.includes('anotherThing')) {
				if ((hostname.includes('oneMoreThing') &&
					cert2=== request.certificate.fingerprint) || cert1=== request.certificate.fingerprint) {
					callback(0);
				}
				else {
					if (mainHelper.loadedPage !== 'offline') {
						logger.error("Server Certificate is invalid. Service is unavailable !");
						this.eventHelper.showOfflinePage();
					} else {
						logger.warn("Server Certificate is invalid. But service could still be available.");
					}
					callback(-2);
				}
			} else {
				callback(0);
			}
		};
	}
```
In appOnReadyHandler we use a connectivity check that hits a backend every ten seconds using axios to do the request. We set the prov

**Comment by codebytere** [comment]
@IFormiga 

> In appOnReadyHandler we use a connectivity check that hits a backend every ten seconds using axios to do the request. We set the prov

i think this may be missing some information you intended to add? Additionally, can we please get some more information about the crash? a report or dump?
