### ISSUE TITLE
clarification requested: nodeIntegration within contextIsolation (v9.2.1)

### ISSUE THREAD

**Issue by ericmandel** [electron/electron#25066]
When nodeIntegration and contextIsolation are both turned on, the render process does not appear to have access to Node features such as __dirname, require, and process. For example, under MacOS 10.14.6, running this command:
````
// using Electron v9.2.1
$ /Applications/Electron.app/Contents/MacOS/Electron main.js
````
with this simple test:
````
// main.js
const electron = require('electron');
const path = require('path');

electron.app.on('ready', () => {
    win = new electron.BrowserWindow({
        width:  400,
        height: 400,
        webPreferences: {
            nodeIntegration: true,
            contextIsolation: true,
        },
    });
    win.loadURL(`file://${path.join(__dirname, 'window.html')}`);
    win.webContents.once('dom-ready', () => {
        win.webContents.openDevTools({mode: 'detach'});
    });
    win.on('closed', () => {
        win = null;
    });
});

// window.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Electron Window</title>
  </head>
  <body>
    <p>
    <h3>This is an Electron Window</h3>
    <script type="text/javascript" src="./start.js"></script>
  </body>
</html>

// start.js
console.log(`process: ${typeof process}`)
console.log(`require: ${typeof require}`)
````
outputs 'undefined' for both process and require. Is this the expected behavior inside contextIsolation?

My problem is that, having dutifully turned on contextIsolation in my "local web pages only" app, I still need the underlying Emscripten environment to have access to all of the Node.js api. I am using contextBridge to pass info needed by my app, but I am confused about what to feed Emscripten.

Obviously, this all works fine without contextIsolation turned on, but my understanding is that this feature is strongly recommended and will soon be the default, so ... thanks!
````

**Comment by nornagon** [comment]
Yes, this is expected behavior.

With `contextIsolation` enabled, there are two JS worlds at play: one "privileged" world that runs the preload script, and another "unprivileged" or "main" world which runs the web page itself. When `contextIsolation` and `nodeIntegration` are both enabled, only the privileged world, i.e. the preload script, has access to the NodeJS globals.

This is intentional, in order to prevent web content from accessing NodeJS APIs.

**Comment by ericmandel** [comment]
Thanks for clarifying this! (I thought perhaps both "worlds" would have access to their own set of NodeJS globals.)
