### ISSUE TITLE
window.open doesn't work correctly in child window

### ISSUE THREAD

**Issue by CezaryKulakowski** [electron/electron#25079]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.0.0-nightly.20200814
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * unknown

### Expected Behavior
`window.open` called in child window opens new window with requested url

### Actual Behavior
If speculative render view host is deleted during naviagation to page we try to open with call to `window.open` window is destroyed right after it is created.

### To Reproduce
1. Create main window with web preference `nativeWindowOpen` set to `true`
1. Create child window with call to `window.open('about:blank')` in the main window's dev tools console
3. Create second child window with call to `window.open('http://www.google.com')` in the child's window dev tools console

Third window will be destroyed right after it is created.

### Additional Information
I attached an example application which reproduces the problem.
[window-open-app.zip](https://github.com/electron/electron/files/5107974/window-open-app.zip)

**Comment by codebytere** [comment]
Closed by https://github.com/electron/electron/pull/25080
