### ISSUE TITLE
Incorrect IME behavior since v6.0.0-beta.1

### ISSUE THREAD

**Issue by hoangph271** [electron/electron#25078]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.0.0-beta.1
* **Operating System:**
  * Windows 10 (2004)
* **Last Known Working Electron version:**
  * 5.0.13

### Expected Behavior

Input with Japanese IME on Windows 10 should work as in other apps, like Chrome after the `BrowserWindow` is `show`ed

### Actual Behavior

If `BrowserWindow` is init with `show: false`, after invoking `show()`, type anything in the input box with Japanese Hiragana IME show this weird IME panel: 
![image](https://user-images.githubusercontent.com/39024711/90872227-83a6d500-e3c6-11ea-84cb-5767ff5c877c.png)
(Sorry for the poor quality picture, I can't use screen capture because the IME panel will dissapear)    
Even more, if I stop using `show()`, and change the code to use `setOpacity()`, the IME panel shows correctly but typing doesn't work anymore

### To Reproduce

https://gist.github.com/6ff60c6116bba8d93ec81b2460ee170c
Run this Electron Fiddle, with Japanese Hiragara IME enabled.
![image](https://user-images.githubusercontent.com/39024711/90871913-04190600-e3c6-11ea-841c-4adf26fe20e8.png)
It behaves weirdly on v6+, and works correctly previous versions  

https://gist.github.com/056ac6e78c71388f67c792d34add6a5f
Repeat the same steps with this fiddle for the bug on using `setOpacity()`

### Screenshots
(Included in the description)  
### Additional Information
If you guys need anymore information, please comment.

**Comment by jhlee8804** [comment]
+1

**Comment by kiendo90** [comment]
+1.
It seems Japanese IME cannot correct the first time, because of the focus problem.  
Have a workaround below:  
```javascript
browserWindow.show();
browserWindow.blur();
browserWindow.focus();
```
After that, the input can be focus exactly, but  typing doesn't work if you have more than one input language type.  
![image](https://user-images.githubusercontent.com/24307628/91374432-62207000-e842-11ea-9114-c126b1f7c8da.png)

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If you're still experiencing this issue in Electron 8.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by hoangph271** [comment]
> Thank you for taking the time to report this issue and helping to make Electron better.
> 
> The version of Electron you reported this on has been superseded by newer releases. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).
> 
> If you're still experiencing this issue in Electron 8.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.
> 
> I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.
> 
> Thanks in advance! Your help is appreciated.

Thanks for your reply...!  

As I mentioned, the issue occurs in every version after v5x, so yeah...!  
I'm still experiencing this issue in Electron 8.x.y or later

**Comment by felixrieseberg** [comment]
I could reproduce, our focus changes in 10.1.2 sadly didn't help.

**Comment by jhlee8804** [comment]
Still has problem.
