### ISSUE TITLE
Auto launch to system tray on system startup - Electron + Ionic app

### ISSUE THREAD

**Issue by meghajayakumar** [electron/electron#25081]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
 v8.4.1
* **Operating System:**
Windows 10

### Expected Behavior
What I need is to auto launch the app upon system startup like Slack or Skype in the system tray and not as a window.

### Actual Behavior
The window shows up on system startup and not as hidden.

### To Reproduce
```
app.setLoginItemSettings({
  openAtLogin: true,
  path: updateExe,
  openAsHidden : true,
  args: [
  '--processStart', `"${exeName}"`,
  '--process-start-args', `"--hidden"`
]
})
```
Upon system startup the window shows up and not as hidden

### Additional Information
Also tried the node auto-launch option with isHidden:true, which also did not hide the window upon startup
```
let autoLaunch = new AutoLaunch({
    name: 'App',
    path: app.getPath('exe'),
    isHidden: true
  });

  autoLaunch.enable();

autoLaunch.isEnabled()
.then(function(isEnabled){
    if(isEnabled){
        return;
    }
    autoLaunch.enable();
})
.catch(function(err){
    // handle error
}); 
```

I tried to incoporate the 'wasOpenedAtLogin' property to hide the window upon startup as well. Again no luck.

  ```
 mainWindow.loadURL(`file://${__dirname}/app/index.html`);
    mainWindow.webContents.on('dom-ready', () => {
      if(app.getLoginItemSettings().wasOpenedAtLogin) {
        console.log('Opened upon login')
        mainWindow.hide();
      }
      else {
      console.log('Opened upon click')
      mainWindow.show();
      }
    });

```

My system tray is set like:

```
tray = new Tray(path.join(__dirname, 'favicon_tray.ico'));

  tray.setContextMenu(Menu.buildFromTemplate([
    {
      label: 'Show App', click: function () {
        mainWindow.show();
      }
    },
    {
      label: 'Quit', click: function () {
        isQuiting = true;
        app.quit();
      }
    }
  ]));
```

**Comment by sediq-khan** [comment]
@meghajayakumar  has the issue been solved? @codebytere  I guess the issue is not resolved why did you close it?

**Comment by meghajayakumar** [comment]
@sediq-khan Since its not an issue at the electron team end, they have closed the ticket. The attribute 'openAsHidden' from the app.setLoginItemSettings is only available in MAC. But I need some way to open as hidden in windows too like how slack or skype does upon startup. Referred a lot of online materials but none seems helpful. Have asked the same in the electron community group as well but haven't got a response yet.

**Comment by ufukomer** [comment]
It is like a secret. I've passed arguments such as `--hidden` and check it with commandLine.hasSwitch() then tried to set `show` as false but somehow cannot prevent window from being shown at startup. Waiting for the fairy godmother...

**Comment by agrear** [comment]
> I've passed arguments such as `--hidden` and check it with commandLine.hasSwitch() then tried to set `show` as false but somehow cannot prevent window from being shown at startup.

Any arguments you pass to `setLoginItemSettings()` end up in `process.argv`.

```
// Set autostart
app.setLoginItemSettings({
  openAtLogin: true,
  args: ['--hidden']
});
```

```
// Check command line arguments
if (!process.argv.includes('--hidden')) {
  window.show();
}
```

**Comment by ufukomer** [comment]
> > I've passed arguments such as `--hidden` and check it with commandLine.hasSwitch() then tried to set `show` as false but somehow cannot prevent window from being shown at startup.
> 
> Any arguments you pass to `setLoginItemSettings()` end up in `process.argv`.
> 
> ```
> // Set autostart
> app.setLoginItemSettings({
>   openAtLogin: true,
>   args: ['--hidden']
> });
> ```
> 
> ```
> // Check command line arguments
> if (!process.argv.includes('--hidden')) {
>   window.show();
> }
> ```

That does not work. Windows and Linux shows up the non-frameless window no matter what.

**Comment by agrear** [comment]
> That does not work. Windows and Linux shows up the non-frameless window no matter what, even if you don't call show() function and set `show` to `false`.

This 100% works for me on Windows; however there are a couple of things that can break the desired behavior.

1. Check the autostart entry:
    On Windows it's under `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`. Look for `electron.app.{package-name}` and ensure it has `--hidden` set correctly.
2. Check options passed to `BrowserWindow` constructor:
    You need to set `show` to `false` in the options since by default it's `true`.
3. Do not show the window by accident:
    Calling `window.maximize()` _will_ show the window regardless of whether or not it was created with `show: false`.

**Comment by ufukomer** [comment]
> > That does not work. Windows and Linux shows up the non-frameless window no matter what, even if you don't call show() function and set `show` to `false`.
> 
> This 100% works for me on Windows; however there are a couple of things that can break the desired behavior.
> 
> 1. Check the autostart entry:
>    On Windows it's under `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`. Look for `electron.app.{package-name}` and ensure it has `--hidden` set correctly.
> 2. Check options passed to `BrowserWindow` constructor:
>    You need to set `show` to `false` in the options since by default it's `true`.
> 3. Do not show the window by accident:
>    Calling `window.maximize()` _will_ show the window regardless of whether or not it was created with `show: false`.

@agrear Omg that worked. You are a god, thank you so much! Combination of 1 and 3 was the solution for me.

**Comment by codedeamon1** [comment]
I currently have an issue with my electron app where when I use tray function and build it into nsis exe the auto start wont work!!
Anyone who faced the same problem and solved it??

**Comment by darshitshah8** [comment]
in my case it work perfect but i can see another some electron window is openining with the my electron application , can anyone know how to stop that extra window opening 

```javascript
app.setLoginItemSettings({
            openAtLogin: true,
            path: app.getPath('exe'),
            args: []
        });
```

**Comment by Thomas-QCD** [comment]
> I currently have an issue with my electron app where when I use tray function and build it into nsis exe the auto start wont work!! Anyone who faced the same problem and solved it??

I was having this issue as well. I am using nsis. When logging out and back in, (Win + L does NOT log you out btw) Windows runs a suite of executables, some of which you can locate in the registry editor at `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run`. 
If you see your app there, 👌 you are on the right track. It was the case for me that the value there, which is the exe path, was not actually the correct path. I was using 
```
const appFolder = path.dirname(process.execPath);
const appName = path.basename(process.execPath);
const stubLauncher = path.resolve(appFolder, '..', appName);

app.setLoginItemSettings({
  openAtLogin: true,
  path: stubLauncher,
  args: ['--hidden'],
  enabled: true,
});
```
The problem there is that that may work for squirrel, but is actually one folder level off for me because I was using nsis  
 Here is my main process code now: 
```
app.setLoginItemSettings({
			openAtLogin: true,
			path: process.execPath,
			args: ['--hidden'], // custom arg to detect hidden launch
			enabled: true,
		});
```
If this doesn't help, try downloading [Autoruns](https://learn.microsoft.com/en-us/sysinternals/downloads/autoruns). After downloading and running `Autoruns.exe`, switch to the `Logon` tab. In my case, my electron app was highlighted in yellow, saying `File not found`, which is why my electron app did not run at startup.
