### ISSUE TITLE
Documentation DID NOT MENTION that you should remove a BrowserView before destroying it

### ISSUE THREAD

**Issue by lockieluke** [electron/electron#25095]
I recently found out if you don't do `win.removeBrowserView(browserView)` before `browserView.destroy()` your app will crash afterward when you move or resize it.  However, the documentation has never mentioned that, please add that in the documentation thanks

**Comment by codebytere** [comment]
`browserView.webContents.destroy()` is undocumented API intentionally - you shouldn't need to use it. You should only be calling add and remove.
