### ISSUE TITLE
Websocket client connection fails to connect to server (Windows only, Mac works fine)

### ISSUE THREAD

**Issue by SkiBum326** [electron/electron#25099]
### Issue Details

* **Electron Version:**
  * 9.0.5
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
I have a Websocket server running on my local network. From my desktop computer, I attempt to open a Websocket client connection (using the ws package), which should connect and remain connected.

### Actual Behavior
On mac, my app works perfectly. The client properly connects to the server.

On Windows, I observe  the following:
-The client remains in a connecting state.
-The server sees a connection open and close immediately.

Additional Note:

I tried my client code from a raw JS file on Windows, and it also worked perfectly, so the issue is only happening within Electron on Windows.

I'm not a Websocket expert, so if there are any steps to produce more useful debugging information please let me know and I am happy to follow!

Here is my client code:

`

const WebSocket = require('ws')
const assert = require('assert');
const log = require('electron-log');

class Pi {
    constructor(core) {
        this.rpi = null
        // Tracks whether a connection has been opened, regardless of a successful handshake.
        this.isConnectionOpenState = false
        // Flags
        this.currOperation = currOperation.neutral
        this.dataLengthCheck = -1
    }

    connect = function(url, board, callBackFunc) {
        this.isConnectionOpenState = true
        this.board = board
        var self = this
        var options = { "handshakeTimeout": 1000 }

        function cleanupOnClose() {
            self.isConnectionOpenState = false
            self.rpi = null
            $("#piStat").text("❌")
            clearInterval(self.interval)
        }

        function noop() {}

        function pingFunc() {
            if (self.rpi == null) return
            if (self.rpi.isAlive === false) {
                self.rpi.terminate();
                cleanupOnClose()
                return
            }

            self.rpi.isAlive = false;
            self.rpi.ping(noop);
        }

        try {
            this.rpi = new WebSocket(url, options);
        } catch (error) {
            alert("Error on connection" + String(error))
            log.error("Cirkit Error: ", error)
            cleanupOnClose()
            return
        }

        this.rpi.on('open', function(event) {
            console.log("Connection Opened")
            $("#piStat").text("✅")
            self.rpi.isAlive = true;
            self.interval = setInterval(pingFunc, 5000);
            callBackFunc()
        });

        this.rpi.on('pong', function(event) {
            self.rpi.isAlive = true;
            console.log("Server Pong Received")
        })

        this.rpi.on('ping', function(event) {
            self.rpi.isAlive = true;
            console.log("Ping Received from Server")
        });

        this.rpi.addEventListener('close', function(event) {
            cleanupOnClose()
            console.log("Connection Closed")
        });

        // onclose is always called after onerror.
        // No need to do anything other than logging here.
        this.rpi.onerror = function(event) {
            console.log("Websocket error.");
            console.log("Connection Closed due to error")
        }

        // Listen for messages.
        this.rpi.addEventListener('message', function(event) {
            self.rpi.isAlive = true;
            console.log('Message from server ', event);

           if (typeof event.data === 'string') {
                try {
                    
                } catch (e) {
                    log.error("Error Parsing the command!!", event.data)
                }
            } else {
                log.error("Error Parsing Server Input!", event.data)
            }
        });
    }

    isConnectionOpen = function() {
        return this.isConnectionOpenState
    }

    isConnected = function() {
        return this.rpi != null && this.rpi.readyState === WebSocket.OPEN
    }

    send = function(msg) {
        if (this.isConnected()) {
            this.rpi.send(msg)
        } else {
            alert("Not Connected to RavenBoard!")
        }
    }
}

`

**Comment by Knautiluz** [comment]
Same problem here with Electron 9.x.x (i need test 8.x.x) works fine in Linux, but fails to connected (stuck) in Windows

```Javascript
WebSocket = require('ws')
//running in 443 (wss)
const ws = new WebSocket('wss://subdomain.mydomain.net')
```
Clearly its cannot translate hostname to IP Address, because works with IP Only.
Facing this problem only with Electron.

**Comment by SkiBum326** [comment]
Ping, can someone take a look at this issue?
It looks like others are encountering the same problem.

**Comment by Knautiluz** [comment]
I maybe find what is causing the issue: ``app.allowRendererProcessReuse = false`` this property is default true, in electron 9.x.x
When this is set true in Linux, all still beautifully, but in Windows cause stuck at connecting state.

**Comment by sawDandelion** [comment]
`app.commandLine.appendSwitch('ignore-certificate-errors');`

[https://stackoverflow.com/questions/57476284/cant-connect-to-web-socket-from-electron-when-using-self-signed-cert](url)

so good~

**Comment by SkiBum326** [comment]
@Knautiluz Good find! I set app.allowRendererProcessReuse = false to false, and as you said, it works perfectly.
I've posted this to the Websocket repo, since I think this is an issue on their end (supporting the new Electron behavior).

**Comment by ryankashi** [comment]
Has there been any updates for this? I am currently using the app.allowRendererProcessReuse = false workaround for my Windows build, however would like to not have to do this as I believe I am taking a performance hit.

Is this fixed in later versions of electron at least?

**Comment by nornagon** [comment]
Closing this as 9.x is no longer supported. Happy to reopen if someone can provide a stand-alone repro case that shows the issue occurring on a [supported version](https://www.electronjs.org/docs/tutorial/support#currently-supported-versions).
