### ISSUE TITLE
Get source code error by previous version.

### ISSUE THREAD

**Issue by mih30vip** [electron/electron#25096]
os:win10
ide:vs2017

I want to build electron v4.2.12 by source code.
```
solutions = [
  { "name"        : 'src/electron',
    "url"         : 'https://github.com/electron/electron@v4.2.12',
    "deps_file"   : 'DEPS',
    "managed"     : False,
    "custom_deps" : {
    },
    "custom_vars": {},
  },
]
```

and execute the command `gclient sync --with_branch_heads --with_tags`

the command line tips:
`2>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin" "69.0.3497.128"' in D:\electron_4.2.x\electron\src failed; will retry after a short nap...`

at last the command line tips:
```
[0:11:23] fatal: couldn't find remote ref 69.0.3497.128
[0:11:24] fatal: couldn't find remote ref 69.0.3497.128
[0:11:25] fatal: couldn't find remote ref 69.0.3497.128
[0:11:27] fatal: couldn't find remote ref 69.0.3497.128
----------------------------------------
Error: Command 'git -c core.deltaBaseCacheLimit=2g fetch origin 69.0.3497.128' returned non-zero exit status 128 in D:\electron_4.2.x\electron\src
```

But, I can download source code of the latest version. My network is okey!
I test the version of v8.x is okey!

Why???

**Comment by MarshallOfSound** [comment]
Electron 4 is no longer supported and we can not guarantee nor attempt to fix missing dependencies or other build failures.
