### ISSUE TITLE
dialog.showMessageBox should block parent if passed

### ISSUE THREAD

**Issue by hoangph271** [electron/electron#25104]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.2.1
* **Operating System:**
  * Windows 10 2004
* **Last Known Working Electron version:**
  * 4.2.12

### Expected Behavior

`dialog.showMessageBox` should block parent `BrowserWindow` if passed

### Actual Behavior

`dialog.showMessageBox` DOESN'T block parent `BrowserWindow` if passed

### To Reproduce

https://gist.github.com/410f031d378bffc1a8a55edbe1ac4245

Just run this Electron Fiddle, after version 4.2.12, the input keep being updated even the modal was `show`ed
Every earlier version block the parent, so the input isn't updated

### Screenshot

![image](https://user-images.githubusercontent.com/39024711/91024338-02e41500-e622-11ea-890a-bb82287c7b6e.png)

The time changed even though modal is still showing...!

![image](https://user-images.githubusercontent.com/39024711/91024351-07a8c900-e622-11ea-83dd-9484dc099788.png)

**Comment by muhonglong** [comment]
And `dialog.showOpenDialog` cannot open directories.

**Comment by kiendo90** [comment]
Can anyone fix it 😥
