### ISSUE TITLE
renderer-browser-process IPC communication sometimes fails if started early enough

### ISSUE THREAD

**Issue by bpasero** [electron/electron#25119]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * `9.2.1`
* **Operating System:**
  * `macOS 10.15.6`
* **Last Known Working Electron version:**
  * `unknown`

### Expected Behavior
Sending an IPC message from a sandboxed window preload script should work.

### Actual Behavior
The IPC message does not work unless some timeout is added.

### To Reproduce

`main.js`
```js
// Modules to control application life and create native browser window
const {app, BrowserWindow, ipcMain} = require('electron')

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
let mainWindow



function createWindow () {

  mainWindow = new BrowserWindow({
    width: 1800,
    height: 1600,
    webPreferences: {
     // spellcheck: false,

      //
      // CONTEXT ISOLTATION
      //
      contextIsolation: true,

      //
      // SANDBOX
      //
      sandbox: true,

      //
      // PRELOAD
      //
      preload: '<path to>/renderer.js'
    }
  })

  mainWindow.loadFile('index.html')

  // Open the DevTools.
  // mainWindow.webContents.openDevTools()

  // Emitted when the window is closed.
  mainWindow.on('closed', function () {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null
  })
}

ipcMain.on('vscode:fetchShellEnv', async (event) => {
	const webContents = event.sender;

	webContents.send('vscode:acceptShellEnv', {});
});

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow)

// Quit when all windows are closed.
app.on('window-all-closed', function () {
  // On OS X it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', function () {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (mainWindow === null) {
    createWindow()
  }
})

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.
```

`preload.js`
```js
const { ipcRenderer, contextBridge, clipboard, shell } = require('electron')

const handle = setTimeout(function () {
  console.warn('Preload: Unable to resolve shell environment in a reasonable time');
}, 3000);

ipcRenderer.once('vscode:acceptShellEnv', function (event, shellEnv) {
  clearTimeout(handle);

  console.log('Preload succeeded');
});

ipcRenderer.send('vscode:fetchShellEnv');
```

`index.html`
```html
<!--
//
//  ### THIS IS SANDBOXED RENDERER ###
//
-->

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
  </head>
  <body>
    <h1>Hello World!</h1>
  </body>
</html>
```

When you run this sample you will notice how the IPC message is never received in the preload script. You will see this in the devtools: `Preload: Unable to resolve shell environment in a reasonable time`

//cc @deepak1556 @MarshallOfSound

**Comment by bpasero** [comment]
Actually I just reproduced the same issue with `sandbox: false` so I think this must be an issue with preload scripts in general.

**Comment by poiru** [comment]
See https://github.com/electron/electron/issues/8663

You can workaround this by queueing `webContents.send` until the `dom-ready` event.

**Comment by bpasero** [comment]
Is there an example?

**Comment by bpasero** [comment]
To clarify, I see this also in VSCode when the IPC connection is started from the renderer JS files, will update the title.

**Comment by bpasero** [comment]
To be honest, this should be handled by Electron and not every client. Imho this behaivour asks for a lot of trouble. Electron should wait before delivering IPC messages if it knows that the renderer needs to be DOM-ready first. That is internal knowledge that should not be exposed to customers.

**Comment by deepak1556** [comment]
This is fixed starting with `12-x-y` in https://github.com/electron/electron/pull/27591 where the ipc messages to the renderer will be queued up and delivered after document load.
