### ISSUE TITLE
executeJavaScript warning issues

### ISSUE THREAD

**Issue by lishid** [electron/electron#25118]
Two small issues related to the security warning for executeJavaScript, introduced by https://github.com/electron/electron/commit/b500294c1d3140be21908c0cd19d98d15110e621

1. Warning is shown even if no code uses `webFrame.executeJavaScript`. This is due to the use of `executeJavaScript` from `warnAboutInsecureCSP ` => `isUnsafeEvalEnabled`
https://github.com/electron/electron/blob/5d657dece4102e5e5304d42e8004b6ad64c0fcda/lib/renderer/security-warnings.ts#L80

2. Warning is shown even if `worldSafeExecuteJavaScript` is set to true. One must set `contextIsolation` to true as well to suppress the warning. This is caused by this check:

https://github.com/electron/electron/blob/b500294c1d3140be21908c0cd19d98d15110e621/lib/renderer/api/web-frame.ts#L52 https://github.com/electron/electron/blob/b500294c1d3140be21908c0cd19d98d15110e621/lib/renderer/api/web-frame.ts#L60

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.2.0
* **Operating System:**
  * Windows 10

**Comment by Sergey-Churilin** [comment]
The same for me in **Electron 10.0.0**, **Windows 10**

**Comment by MecDog** [comment]
+1
