### ISSUE TITLE
electron9 on windows system webview.print() content is null.

### ISSUE THREAD

**Issue by yanyunchangfeng** [electron/electron#25116]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
    when I use webview API webview.print(),webview content is not null,however,print content is null !
* **Electron Version:**
  * 9.1.0
* **Operating System:**
  *  Windows 10
* **Last Known Working Electron version:**
  *  (3.0.0) 

### Expected Behavior
    on windows system webview API can print content

**Comment by lech-code-monkey** [comment]
It's OK on the mac.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

**Comment by yanyunchangfeng** [comment]
It's ok on build a .exe file ,however, on dev server ,It print null

**Comment by codebytere** [comment]
Closing as no repro was provided.
