### ISSUE TITLE
desktopCapture audio capture include application audio on Window 10

### ISSUE THREAD

**Issue by tanphamanhh** [electron/electron#25120]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
I'm developing an Webrtc video conference application and using electron.desktopCapturer to capture system audio,  the other participent voice is recorded to screen sharing audio cause loop issue.
I tried with Chrome with `navigator.mediaDevices.getDisplayMedia` API, this issue doesn't happen, all system audio was recorded without my webpage audio
Here is the code I'm using
```
desktopCapturer
	.getSources({
		types: ['screen', 'window', 'audio'],
		thumbnailSize: {
			width: 500,
			height: 500
		}
	})
	.then((inputSources) => {
		//...show select source UI..
	});

function onSelectedSouce(arg) { //arg is {sourceId: ..., audio: true || false}
	if (process.platform == "win32") {
		const constraints = {
			audio: arg.audio
				? {
					mandatory: {
						chromeMediaSource: "desktop",
					},
				}
				: false,
			video: {
				mandatory: {
					chromeMediaSource: "desktop",
					chromeMediaSourceId: arg.sourceId,
					minWidth: 800,
					maxWidth: 800,
					minHeight: 600,
					maxHeight: 600,
				},
			},
		};
		//navigator.mediaDevices.getDisplayMedia
		navigator.mediaDevices
			.getUserMedia(constraints)
			.then((stream) => {
				//got stream with audio
			})
			.catch((err) => {
				console.log(err);
			});
	} else {
		//for macos
	}
}
```
* **Electron Version:**
  * 9.2.1
* **Operating System:**
  * Windows 10 (1909)
* **Last Known Working Electron version:**
  * 

### Expected Behavior
Audio track from `navigator.mediaDevices.getUserMedia` API dont include this application app (or other participent voice)

### Actual Behavior
 the other participent voice is recorded to screen sharing audio

**Comment by CapOM** [comment]
Hi, interesting issue, you said it does not happen with `navigator.mediaDevices.getDisplayMedia` on Chrome, which version ?
Also please try on Chrome with `navigator.mediaDevices.getUserMedia `to know if this is something around getUserMedia in general or if electron is missing something.

**Comment by tanphamanhh** [comment]
> Hi, interesting issue, you said it does not happen with `navigator.mediaDevices.getDisplayMedia` on Chrome, which version ?
> Also please try on Chrome with `navigator.mediaDevices.getUserMedia `to know if this is something around getUserMedia in general or if electron is missing something.

Thanks for reading,
I tried at Chrome 84 but I think the older version is working too.
The problem here is electron don't have `navigator.mediaDevices.getDisplayMedia`, I tried to call `navigator.mediaDevices.getDisplayMedia` on electron and the promise callback is `DOM Exception: Permission denied`.
Since chrome (edge too) has `navigator.mediaDevices.getDisplayMedia` to capture screen and don't have to install any additional extensions I think this issue is fixed

**Comment by UzEE** [comment]
Actually, `navigator.mediaDevices.getDisplayMedia()` in electron does work when audio is not requested. For example:

```js
const stream = await navigator.mediaDevices.getDisplayMedia({ video: true });
const videoTrack = stream.getVideoTracks()[0];
```

This will get you the video track. However, if you try to include audio, you will get the Permission denied exception as you pointed out. You also don't get a screen picker UI and it only returns your first screen (label `screen:0:0`) and so far I haven't been able to figure out how to specify which screen to capture.

**Comment by barisinanc** [comment]
Electron-based Microsoft Teams application seems to be achieved this issue, but since their source code is private we cannot learn how they did it exactly.

**Comment by AndryGabry01** [comment]
any solution was found?

**Comment by ryankashi** [comment]
I am running into this same issue. I am unable to use electron to capture the specific audio from only a single application.

For example, if I would like to record the video and audio of my Electron application, my Electron application will successfully record the video, HOWEVER, if I have music playing in the background, this will be recorded as well which is not desired or acceptable for my use case.

Thanks!

**Comment by Yaniv-Benhaim** [comment]
Still looking for a solution :(

**Comment by korayrubicoda** [comment]
do you have a solution ?

**Comment by mcjambi** [comment]
I have the same problem! No way to fixed at this time

**Comment by AndryGabry01** [comment]
Has anyone found a solution?

**Comment by Psyjakes** [comment]
I have this issue, but also I am not even able to record audio from my desktop as a whole:
            constraints.audio = {
                mandatory: {
                    chromeMediaSource: 'desktop',
                    chromeMediaSourceId: this.source.id
                }
            }
If I only use the chromeMediaSource property set then I also get the Exception that the audio cannot be started

**Comment by yutokawasaki** [comment]
Has anyone found a solution?

**Comment by obaid-marv** [comment]
has anyone found it?

**Comment by MimikFc7** [comment]
same issue
