### ISSUE TITLE
v10.0.0: cannot compile wasm when contextIsolation is enabled

### ISSUE THREAD

**Issue by ericmandel** [electron/electron#25127]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  10.0.0
* **Operating System:**
  *  macOS 10.14.6
* **Last Known Working Electron version:**
  *  9.2.1

### Expected Behavior

Wasm should be allowed to compile when contextIsolation is enabled, as it did in v9.2.1.

### Actual Behavior

Wasm compilation fails:

<img width="1125" alt="Screen Shot 2020-08-25 at 4 24 19 PM" src="https://user-images.githubusercontent.com/3028875/91225978-63db1e00-e6f2-11ea-9a70-7595d51969f9.png">

Turning off contextIsolation fixes the problem.

### Additional Information

Note that this error is different from #25066, in which it was clarified that Node is not available to the web page and emscripten when contextIsolation is turned on. In this case, it looks like the browser is not permitting wasm compilation at all.

**Comment by quanglam2807** [comment]
I have the same problem when loading Figma with Electron 10.x

<img width="912" alt="Screen Shot 2020-08-27 at 9 15 43 PM" src="https://user-images.githubusercontent.com/1548835/91453900-81eb7e80-e8aa-11ea-896b-7d8674c636e0.png">

**Comment by codebytere** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by ericmandel** [comment]
@codebytere A stand-alone test is attached in hello.zip that instantiates wasm successfully using v9.2.1 but not v10. To run, unzip and:
````
/Applications/Electron.app/Contents/MacOS/Electron main.js false    # turn off contextIsolation => success in 9.2.1, 10
/Applications/Electron.app/Contents/MacOS/Electron main.js true     # turn on contextIsolation => fail 10, success 9.2.1
````
The output will be found in the debugger console window. For success:

<img width="1109" alt="Screen Shot 2020-09-04 at 1 07 55 PM" src="https://user-images.githubusercontent.com/3028875/92268067-bb764800-eeaf-11ea-915a-8d9b22c93cf9.png">

For failure:

<img width="1127" alt="Screen Shot 2020-09-04 at 1 07 40 PM" src="https://user-images.githubusercontent.com/3028875/92268081-c03afc00-eeaf-11ea-8c48-41b69e103d90.png">

Let me know if I can help further ...

[hello.zip](https://github.com/electron/electron/files/5176098/hello.zip)

**Comment by codebytere** [comment]
Thanks! Reproed successfully. What's happening here is that `contextIsolation`, which makes it such that Node.js is run in the preload script and the renderer no longer has access to Node.js, is that the `AllowWasmCodeGeneration` callback (added in a more recent version of Node.js) is no longer being set properly by Node.js in the renderer. I'll try to get a fix up soon :)

**Comment by ericmandel** [comment]
@codebytere Thanks for your quick response ... though I gladly would exchange that quickness for a world in which weekends called us to something other than quiet debugging sessions!

**Comment by saghul** [comment]
👋  We are also running into this, with a small difference: we load a website on an iframe. The only way I found to make it work was to both disable contextIsolation **and** enable nodeIntegration, but that's not something I'm keen on doing. Is there any other way around this?

**Comment by nornagon** [comment]
@saghul do you have a repro case? If your app doesn't require `nodeIntegration`, you should strongly consider enabling `sandbox`, which should make wasm work identically to Chrome.

**Comment by saghul** [comment]
@nornagon I'll try modify the hello example to use an iframe and reproduce our case.

**Comment by codebytere** [comment]
@nornagon there's something wild going on here - when `contextIsolation` is on the `v8::Local<v8::Value>` representing whether Wasm codegen should be enabled is registering as a `v8::Function` and not a `v8::Boolean`

**Comment by codebytere** [comment]
e.g 
```
static bool AllowWasmCodeGenerationCallback(Local<Context> context,
                                            Local<String>) {
  Local<Value> wasm_code_gen =
      context->GetEmbedderData(ContextEmbedderIndex::kAllowWasmCodeGeneration);
  printf("wasm_code_gen->IsUndefined() is: %s\n", wasm_code_gen->IsUndefined() ? "true" : "false");
  printf("wasm_code_gen->IsTrue() is: %s\n", wasm_code_gen->IsTrue() ? "true" : "false");
  printf("wasm_code_gen->IsFalse() is: %s\n", wasm_code_gen->IsFalse() ? "true" : "false");
  printf("wasm_code_gen->IsFunction() is: %s\n", wasm_code_gen->IsFunction() ? "true" : "false");
  return wasm_code_gen->IsUndefined() || wasm_code_gen->IsTrue();
}
```

Logs
```
false
false
false
true
```
(and returns false)

**Comment by ericmandel** [comment]
@codebytere Thanks very much for fixing this!

**Comment by saghul** [comment]
Cheers! I'll give it a go as soon as it gets on a release!

**Comment by poiru** [comment]
@codebytere Seems like this didn't make it onto `10.x` yet — just double-checking that you're planning to backport it there?

**Comment by quanglam2807** [comment]
It’s been backported. We just need wait for the release. :)

**Comment by codebytere** [comment]
@quanglam2807 it hasn't yet - it needs manual as you can see by the label on the original PR :) I do plan to do it when i have time soon tho!

**Comment by akshaydeo** [comment]
I am getting the same issue in electron 17.1.
<img width="859" alt="Screenshot 2022-02-27 at 5 47 46 PM" src="https://user-images.githubusercontent.com/1050029/155882837-79a3dc9c-5fb0-4f2a-8974-4b762a4a3f33.png">
0
