### ISSUE TITLE
nightly tag stuck on 4.0.0-nightly.20181010

### ISSUE THREAD

**Issue by v-kpheng** [electron/electron#25123]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
Running `npm install electron@nightly` doesn't install the latest nightly build.

### Expected Behavior
The latest nightly build should be installed: Electron 11.0.0-nightly.20200824.

### Actual Behavior
Instead of the latest nightly build, a previous build, 4.0.0-nightly.20181010, gets installed.

### To Reproduce
To reproduce, run `npm install electron@nightly` on the command line.

### Screenshots
Looks like the `nightly` tag needs updating.  Please see https://www.npmjs.com/package/electron.

![image](https://user-images.githubusercontent.com/49660118/91209124-1b0a7180-e6c0-11ea-8436-d35d2ee07e7b.png)

**Comment by MarshallOfSound** [comment]
Nightlies do not live in the "electron" package.  As per our website front page to install a nightly use

```
npm install electron-nightly
```

**Comment by v-kpheng** [comment]
Thanks, @MarshallOfSound, for your response -- much appreciated!

FYI, per https://www.electronjs.org/releases/nightly, another way of installing it would be `npm install electron@nightly`.  Don't know if the instructions are still valid though...possibly not?

![image](https://user-images.githubusercontent.com/49660118/91211078-054a7b80-e6c3-11ea-95e2-3d762f8173c7.png)
