### ISSUE TITLE
Electron 10.0.0 is rejected from Mac App Store

### ISSUE THREAD

**Issue by thomasdao** [electron/electron#25138]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.

### Issue Details

* **Electron Version:** 10.0.0

### Rejection Email

Your app links against the following non-public framework(s):

• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_CGFontRenderingGetFontSmoothingDisabled

**Comment by MarshallOfSound** [comment]
Duplicate #25115
