### ISSUE TITLE
API desktopCapturer.getSources on WIndows can't get the child BrowserWindow who has a parentWindow

### ISSUE THREAD

**Issue by ChangJi** [electron/electron#25136]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**9.1.2
  * 
* **Operating System:**windows
  * 
* **Last Known Working Electron version:**
  * 

### Expected Behavior

get the child BrowserWindow
### Actual Behavior

no child BrowserWindow
### To Reproduce

desktopCapturer.getSources(options, function(error, sources) {})

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.
