### ISSUE TITLE
Dependency not allowed - Trying to build electron on Scientific Linux release 6.5

### ISSUE THREAD

**Issue by EcuDrugWash** [electron/electron#25144]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
* **Operating System:**
Scientific Linux release 6.5 

I am tyring to build electron on Scientific Linux release 6.5. I read https://www.electronjs.org/docs/development/build-instructions-gn

First of all I did it:
$ mkdir electron && cd electron
$ gclient config --name "src/electron" --unmanaged https://github.com/electron/electron
$ gclient sync --with_branch_heads --with_tags

Next step:
$ cd src
$ export CHROMIUM_BUILDTOOLS_PATH=`pwd`/buildtools
$ gn gen out/Testing --args="import(\"//electron/build/args/testing.gn\")"

and after that I got next message:

ERROR at //third_party/dawn/scripts/dawn_component.gni:110:3: Dependency not allowed.
  static_library("${name}_static") {
  ^---------------------------------
The item //third_party/dawn/src/dawn_wire:dawn_wire_static
can not depend on //third_party/dawn/src/common:dawn_internal
because it is not in //third_party/dawn/src/common:dawn_internal's visibility list: [
  //third_party/dawn/src/common:*
]

How i can fix it?

**Comment by nornagon** [comment]
@EcuDrugWash that `gn gen` command looks wrong as the internal `"` aren't escaped.

Can you paste the contents of `out/Testing/args.gn` here?

**Comment by nornagon** [comment]
Also, closing this issue as it doesn't represent something for Electron to fix, but I'm happy to continue discussion here.

**Comment by EcuDrugWash** [comment]
> @EcuDrugWash that `gn gen` command looks wrong as the internal `"` aren't escaped.
> 
> Can you paste the contents of `out/Testing/args.gn` here?

cat out/Testing/args.gn
import("//electron/build/args/testing.gn")

**Comment by nornagon** [comment]
What commit of Electron are you building?

**Comment by EcuDrugWash** [comment]
> What commit of Electron are you building?

How can I get it?

**Comment by EcuDrugWash** [comment]
As I can see 

ail -f out.log 
    
    git-svn-id: svn://svn.chromium.org/blink/trunk@2 bbb929c8-8fbe-4397-9dbb-9b2b20218538

commit a5068f5fa11005232bc4383c54f6af230f9392fb
Author: (no author) <(no author)@bbb929c8-8fbe-4397-9dbb-9b2b20218538>
Date:   Fri Aug 24 14:11:42 2001 +0000

    New repository initialized by cvs2svn.
    
    git-svn-id: svn://svn.chromium.org/blink/trunk@1 bbb929c8-8fbe-4397-9dbb-9b2b20218538

**Comment by nornagon** [comment]
`cd electron; git rev-parse HEAD`

**Comment by EcuDrugWash** [comment]
git rev-parse HEAD
be8db589ebe2858af76d698b097416b554311355

**Comment by EcuDrugWash** [comment]
```
git rev-parse HEAD
be8db589ebe2858af76d698b097416b554311355

```

**Comment by nornagon** [comment]
It looks like this is an upstream issue that's been fixed already: https://dawn.googlesource.com/dawn/+/9aed03dcb02f8e21387d571902380e0f13d549ab

So we'll have to wait until we roll in the fix, which should happen with this PR: https://github.com/electron/electron/pull/24984

It's odd that this isn't failing on our CI, though...

**Comment by nornagon** [comment]
In the mean time, the easiest workaround for you for now would be to apply the above linked patch manually.

Change the file `third_party/dawn/src/common/BUILD.gn` as follows:


```diff
diff --git a/src/common/BUILD.gn b/src/common/BUILD.gn
index c924a16..85d63d1 100644
--- a/src/common/BUILD.gn
+++ b/src/common/BUILD.gn
@@ -84,8 +84,9 @@
   }
 
   # Only internal Dawn targets can use this config, this means only targets in
-  # this BUILD.gn file.
-  visibility = [ ":*" ]
+  # this BUILD.gn file and related subdirs.
+  visibility = [ "../*" ]
+
   cflags = []
 
   # Enable more warnings that were found when using Dawn in other projects
```

**Comment by EcuDrugWash** [comment]
Thanks a lot it works, but I got next issue 

ERROR at //v8/gni/v8.gni:199:3: Dependency not allowed.
  source_set(target_name) {
  ^------------------------
The item //v8/src/inspector:inspector_test_headers
can not depend on //v8:features
because it is not in //v8:features's visibility list: [
  //v8:*
]

**Comment by nornagon** [comment]
looks like a GN bug got fixed and bit a few places.

here's the fix on the V8 side: https://chromium.googlesource.com/v8/v8/+/7c182bd65f424db19dc3e3d9aca601030af30d7e

**Comment by EcuDrugWash** [comment]
what should I do?

**Comment by EcuDrugWash** [comment]
How can I update for latest?

**Comment by nornagon** [comment]
@EcuDrugWash you have a few options.

One, wait. This problem will be fixed in Electron in a week or so.

Two, build a slightly older version of Electron. Try v11.0.0-nightly.20200814, which is just before the most recent Chromium upgrade which likely introduced this issue.

Three, find and patch in all the fixes yourself.

**Comment by EcuDrugWash** [comment]
> Two, build a slightly older version of Electron. Try v11.0.0-nightly.20200814, which is just before the most recent Chromium upgrade which likely introduced this issue.

1. How can I switch to this version?
2. How get gn version for Scientific Linux release 6.5/ I build it myself for Scientific Linux release 6.5 because when I run gclient sync -f I got new gn for SL7.x whicjh needed 
`/develop/src/buildtools/linux64/gn: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /develop/src/buildtools/linux64/gn)
/develop/src/buildtools/linux64/gn: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /develop/src/buildtools/linux64/gn)
/develop/src/buildtools/linux64/gn: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /develop/src/buildtools/linux64/gn)
`

**Comment by nornagon** [comment]
1. `git checkout` the appropriate branch and run `gclient sync` again.

I can't comment on how to fix your custom build of GN.

**Comment by EcuDrugWash** [comment]
> 1. `git checkout` the appropriate branch and run `gclient sync` again.
cd src && git get 11.0.0-nightly.20200814
bash: cd: src: No such file or directory


> I can't comment on how to fix your custom build of GN.
How get gn version for Scientific Linux release 6.5? My custom build works but from git I got new whic depend from new verson glibc.

**Comment by EcuDrugWash** [comment]
Is it possible to get full command for getting stable version of all components for building on SL65? Wher can I find such infromation?

**Comment by EcuDrugWash** [comment]
I can not fix it 

`ERROR at //v8/gni/v8.gni:182:3: Dependency not allowed.
  target(link_target_type, target_name) {
  ^--------------------------------------
The item //v8/third_party/inspector_protocol:crdtp_platform
can not depend on //v8/third_party/inspector_protocol:crdtp_config
because it is not in //v8/third_party/inspector_protocol:crdtp_config's visibility list: [
  //v8/src/inspector:*
]
`

Al so after update from git :(

**Comment by nornagon** [comment]
Seems like you're headed for option one, then: wait until we fix this in master :)

**Comment by EcuDrugWash** [comment]
> Seems like you're headed for option one, then: wait until we fix this in master :)

how long?
