### ISSUE TITLE
Webview: the 'console-message' event doesn't have the appropriate properties when contextIsolation is true

### ISSUE THREAD

**Issue by AmarBouchibane** [electron/electron#25143]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.0.0
* **Operating System:**
  * Windows 10 (1909)
* **Last Known Working Electron version:**
  * unknown

### Expected Behavior
When listen to the 'console-message' event of a webview element the event should have a 'message' property.

### Actual Behavior
This works perfectly when contextIsolation is set to 'false' (or not at all in 10.0.0).

### To Reproduce
* Create a BrowserWindow with contextIsolation: false in webPreferences.
* Create a webview in the BrowserWindow.
* Add a 'console-message' listener to the webview.
* Load an URL in webview and print something in the console from the guest page.
* The console message should appear as a property of the event (event.message).
* Now set contextIsolation: true.
* Load the URL in the webview.
* The 'console-message' event will be fired, but the event.message property isn't available anymore.

https://gist.github.com/AmarBouchibane/80b89651d776f0b1cdf11748e6a2d090

**Comment by vladimiry** [comment]
Referencing possibly related issue #22085.

**Comment by AmarBouchibane** [comment]
Still open in Electron 10.1.5.

**Comment by nornagon** [comment]
can repro in all current versions of Electron (and as far back as 6.x at least).

**Comment by nornagon** [comment]
Here's the code which returns a different wrapper for the `Event` object if accessed in a different world: https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/platform/bindings/dom_data_store.h;l=85-90;drc=f8a50cecbdeec78553325d9996dc14ab31e21b20 (invoked from [here](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/bindings/core/v8/js_based_event_listener.cc;l=117;drc=f8a50cecbdeec78553325d9996dc14ab31e21b20)).
