### ISSUE TITLE
x64 Electron crashes renderer process right after start on Big Sur Beta 4 ARM

### ISSUE THREAD

**Issue by zarubond** [electron/electron#25159]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9, 10
* **Operating System:**
  * macOS 11.0 Beta 4 - ARM
* **Last Known Working Electron version:**
  * none

### Expected Behavior
Electron should be able to run without crash

### Actual Behavior
Electron render process crashes right after start of app.

### To Reproduce
Get ARM based MAC mini and run Electron on it

### Additional Information
 Chrome x64 v85 runs on the same device without problem

**Comment by MarshallOfSound** [comment]
Electron x64 is not intended to work on DTKs.  It will work on true apple-silicon hardware, specifically though you should be using the 11.0.0-beta.1 macOS arm builds.

Please don't raise apple silicon related issues, we have a pinned tracking issue for this: https://github.com/electron/electron/issues/24319
