### ISSUE TITLE
Save dialog: cannot provide a extension to pick when specifying multiple

### ISSUE THREAD

**Issue by bpasero** [electron/electron#25152]
### Issue Details

* **Electron Version:**
  * `9.2.1`
* **Operating System:**
  * `macOS 10.15`

### Expected Behavior
I can specify an extension to pick in the save dialog when multiple are provided.

### Actual Behavior
A random extension is picked from the list.

### To Reproduce
Bring up a dialog on macOS like this:

```js
dialog.showSaveDialog(mainWindow, {
    filters: [
      {
        name: 'Python',
        extensions: [
          'py',  'rpy',
          'pyw', 'cpy',
          'gyp', 'gypi',
          'pyi', 'ipy'
        ]
      },
    ]
  });
```

I would expect that the first extension is picked (`py`) and not `gyp`.

### Screenshots
![image](https://user-images.githubusercontent.com/900690/91400284-ac542200-e83f-11ea-81bb-2f987099b6d7.png)

**Comment by bpasero** [comment]
Thanks for the prompt fix, is this being backported to Electron 9?

**Comment by codebytere** [comment]
@bpasero already done, it'll be out in the next release!

**Comment by bpasero** [comment]
@codebytere thanks a lot 👍
