### ISSUE TITLE
Error (message) in main when using session.setPreloads(...)

### ISSUE THREAD

**Issue by Joe-Kerr** [electron/electron#25158]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version: *10.0.0* and *9.2.0*
  * 
* **Operating System: *Win7*
  * 
* **Last Known Working Electron version:**
  * 

Windows system console logs following errors:
```
[4504:0828/133824.557:ERROR:CONSOLE(130)] "Unable to load preload script: ...\src\preload2.js", source: electron/js2c/sandbox
_bundle.js (130)
[4504:0828/133824.557:ERROR:CONSOLE(130)] "Error: contextBridge API can only be
used when contextIsolation is enabled", source: electron/js2c/sandbox_bundle.js
(130)
```

The error message occurs whenever I use 

```javascript
win.webContents.session.setPreloads([pathToPreload]);
```
[https://github.com/Joe-Kerr/temp-electron001/blob/d894d9578e33892ef8611f781feff63735206ea6/src/main.js#L30](repo)

However, I did not notice any script termination. Both preload scripts inject a global variable the index.html can access.

"contextIsolation" is set to true.

### Expected Behavior

No error message in system log.

### Actual Behavior

Error message as above.

### To Reproduce

```sh
$ git clone https://github.com/Joe-Kerr/temp-electron001.git
$ npm install
$ npx electron .
```

**Comment by Joe-Kerr** [comment]
Please ignore this for second. There is something else going on in my test setup.

**Comment by Joe-Kerr** [comment]
Updated issue.

**Comment by MarshallOfSound** [comment]
@Joe-Kerr I believe that your devtools window is running in the same "session" as your main window.  This means when you add your preload scripts to your session object the preload script will run when you open devtools and **that** window does not have contextIsolation enabled.  You can detect this and stop your preload script running on `devtools://` URLs

**Comment by Joe-Kerr** [comment]
Intriguing. 

Apologies though because I really should have commented the "toggleDevTools" call. Then I would have noticed.
