### ISSUE TITLE
v10.0.1 missing from NPM

### ISSUE THREAD

**Issue by C-Lodder** [electron/electron#25154]
Electron 10.0.1 has been tagged: https://github.com/electron/electron/releases/tag/v10.0.1
However [NPM](https://www.npmjs.com/package/electron) is still showing 10.0.0 as the latest version

Would you mind publishing it please?

**Comment by MarshallOfSound** [comment]
Until it appears on npm the release isn't final. The release process for electron is exceedingly complicated and certain actions such as the GitHub release being available can occur significantly earlier or later than the release being final on npm.

All going to plan this release should be available on npm later today PST

**Comment by C-Lodder** [comment]
Ah fair enough. Thanks for the information @MarshallOfSound
