### ISSUE TITLE
[v10.0.0] Failure of transparent in Linux

### ISSUE THREAD

**Issue by yodagg** [electron/electron#25153]
### Preflight Checklist
* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
Transparent failed in v10.0.0 and v11.0.0-beta. 1, but normal in v4-v9.
```js
const onAppReady = () =>{
  let parent = new BrowserWindow({
    width: 300,
    height: 300,
    transparent: true,
    frame: true
  })
  parent.loadFile('main.html')
}

app.on('ready', () =>setTimeout(onAppReady, 500))
```

* **Electron Version:**
v10.0.0 and v11.0.0-beta.1
* **Operating System:**
x86_64 Linux version 5.4.50-amd64-desktop (deepin@deepin-PC)
(gcc version 8.3.0 (Uos 8.3.0.3-3+rebuild))

* **Last Known Working Electron version:**
v9.2.1

### Screenshots
v9.2.1
![image](https://user-images.githubusercontent.com/24741025/91416281-c151a500-e881-11ea-862c-730e7fb769f4.png)
v10.0.0
![image](https://user-images.githubusercontent.com/24741025/91416474-02e25000-e882-11ea-96d4-a5a60e2e4c73.png)

### Additional Information
I have tested v4/v5/v9 are normal, only v10 - v11 failed.

**Comment by so-diao** [comment]
After several tests between V9 and V10, it is found that:

v10.0.0-beta.4 correct.
v10.0.0-beta.8 failed.

**Comment by AryToNeX** [comment]
I can confirm this behaviour on KDE Plasma (x11). My test application is at https://github.com/AryToNeX/Glasstron
My team is confirming this to happen also on GNOME Shell on both Wayland and X11.

**Comment by nikitalita** [comment]
@so-diao thank you very much for regression testing this. 

In between 10.0.0-beta.4 and 10.0.0-beta.8, Electron upgraded its chromium from 85.0.4161.2 to 85.0.4181.1. 

In between those Chromium versions, Chromium apparently changed the X11 rendering code in anticipation of switching to OZone; it looks like most of it was just refactoring. I'm currently trying to track it down.

**Comment by ckerr** [comment]
I'm seeing the same behavior descirbed by @so-diao: this worked in 10.0.0-beta.4 and is broken in v10.0.0-beta.8. I haven't done any bisection yet to find the offending commit. @nikitalita you mentioned you were trying to track it down -- did you get anywhere with this?

Tested with https://gist.github.com/ckerr/a77275329bb53e78e229ab178f7a4b58 on Ubuntu 20.04.1 LTS, FWIW.

**Comment by so-diao** [comment]
@ckerr  These are the screenshots from my test.   (Linux-deepin v20)

10.1.3
We are using Node.js 12.16.3, Chromium 85.0.4183.121, and Electron 10.1.3.
![20201009105304](https://user-images.githubusercontent.com/24741025/95536672-1c002400-0a1e-11eb-8b32-0a83e1f76db4.png)

10.0.0-beta.4
We are using Node.js 12.16.3, Chromium 85.0.4161.2, and Electron 10.0.0-beta.4.
![20201009105428](https://user-images.githubusercontent.com/24741025/95536733-494cd200-0a1e-11eb-95db-8b6923f8850e.png)

![20201009111729](https://user-images.githubusercontent.com/24741025/95539442-0fc99600-0a21-11eb-9743-d3831baa975f.png)

**Comment by nikitalita** [comment]
@ckerr unfortunately not; compiling electron/chromium is a giant pain in the ass and I never figured out a way to get it to an acceptable speed to do any sort of effective regression testing.

**Comment by DimPaDev** [comment]
Just wanted to mention that NW.js had this problem/regression too , but recently they updated chromium to version 86.0.4240.75 and the transparency in linux now works correctly

**Comment by bundyo** [comment]
Seems the only way to fix this is by stopping HW acceleration before the app is ready. Something in the lines of:

```js

app.disableHardwareAcceleration();

app.on('ready', () => {
  setTimeout(() => {
    createWindow();
    autoUpdater.checkForUpdatesAndNotify();
    createMenu();
  }, 50);
});
```

_Originally posted by @andredezzy in https://github.com/electron/electron/issues/2170#issuecomment-736223269_

**Comment by shubham-root** [comment]
on the lines of @bundyo 's solution, something line this [https://github.com/electron/electron/issues/15947#issuecomment-784864041](url) worked for me in Electron 11.2.3 on Ubuntu 18.04.

**Comment by AryToNeX** [comment]
> on the lines of @bundyo 's solution, something line this [#15947 (comment)](https://github.com/electron/electron/issues/15947#issuecomment-784864041) worked for me in Electron 11.2.3 on Ubuntu 18.04.

This will disable hardware acceleration and it is not ideal if the application you are trying to develop is rather heavy in content. Nobody wants laggy applications. This should be solved regardless of workarounds imo

**Comment by marius851000** [comment]
I can confirm that I have this issue with electron 12.0.1 (from nixos). One difference (both on 10/11/12) is that it doesn't display corrupted graphics, just a black background (with some visual problem related to text being a bit transparent until scrolling is finished in vscode). I'll try to bisect electron (and chromium if needed) to figure what exactly caused the problem.

**Comment by marius851000** [comment]
Did'nt fully finished this regression, but I was able to find this was between bump of chromium from 85.0.4168.1 (included) and bump of chromium 85.0.4178.4 (included)

**Comment by Xaryphon** [comment]
I was trying to get vscode transparency working without `--disable-gpu` and decided to try `--use-gl=desktop` and to my surprise it worked.
I couldn't get it to work on a smaller test project though and I didn't have to patience to start debugging.
Just decided to share this is it happens to help anyone!

And below are chrome://gpu from with and without `--use-gl=desktop` (may be of some use so might as well share them)
With: https://gist.github.com/Xaryphon/8e881d7beccc88c2ba27fe3bdb271c38
Without: https://gist.github.com/Xaryphon/282f8ec13d291b626db95bec5d59a497

**Comment by bundyo** [comment]
Seems to be working for me.

**Comment by marius851000** [comment]
whoa, work for me too (lost faith in having an up-to-date codium) ! _updating my package for transparent codium/vscode_

**Comment by davidcann** [comment]
I can confirm this workaround on Electron 12.0.8, Ubuntu 18.04, Nvidia Jetson TX2 (arm64) with apparently no performance issues. Excellent find! I suggest that this ticket could be closed and a note added to documentation.

**Comment by sudo-bcli** [comment]
2021-7: Confirm following code works on 
* **Ubuntu 20.04.2LTS 64bit**
* GNOME v3.36.8
* Window System X11
* GeForce GTX 1080Ti
* **Nvidia Driver 455 (proprietary)**
* **Electron v13.1.4**
* Node v14.16.1

Code: 

```javascript
const createWindow = () => {
    const mainWindow = new BrowserWindow({
      height: 800,
      width: 600,
      transparent: true
    });
    mainWindow.loadFile("index.html");
  };
  
if(process.platform === "linux") {
    app.commandLine.appendSwitch('use-gl','desktop');
    // app.disableHardwareAcceleration();
    app.on('ready', () => setTimeout(createWindow, 500))
 }
 else{
    app.on('ready', createWindow)
 }
```
Observations:
1. Opening DevTools will disable window transparency
2. By uncommenting `app.disableHardwareAcceleration();`, I can reduce `createWindow` delay **to** about 20 (ms).
3. By commenting `app.disableHardwareAcceleration();`, I can reduce `createWindow` delay **to** about 120 (ms).
4. Following code are key to make a transparent window on Ubuntu
    1. `transparent: true`
    2. `app.commandLine.appendSwitch('use-gl','desktop');`
    3. `app.on('ready', () => setTimeout(createWindow, 500))`

**Comment by shady-xia** [comment]
My app's transparent settings are fine on ubuntu, but not on Kylin OS
