### ISSUE TITLE
window.setSize effects minimized windows on Ubuntu 18.04, but not Windows 10

### ISSUE THREAD

**Issue by marvinirwin** [electron/electron#25173]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.5.0

* **Operating System:**
  * Microsoft Windows 10 Home 10.0.19041 / Ubuntu 18.04 x64

* **Last Known Working Electron version:**
  * N/A

### Expected Behaviour
On Ubuntu 18.04 you can set the size of minimised windows and when you restore the window, its size will be the dimensions that you specified.  On Windows 10 setting a windows' dimensions while its minimised does nothing. 

### Actual Behaviour

Since the [documentation](https://www.electronjs.org/docs/api/browser-window#browserwindowsetsizewidth-height-animate) says nothing about the minimised status of the window, it's perhaps reasonable to expect that setting the size would always work?  If it's a Windows error then perhaps the documentation should be updated to note it.

### To Reproduce

Electron fiddle gist: https://gist.github.com/marvinirwin/38950750cbef707e1cea5e0d308b3185

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If you're still experiencing this issue in Electron 8.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by marvinirwin** [comment]
I have reproduced this issue on electron 8.5.0 in the same fiddle

**Comment by klren0312** [comment]
electron 9.3.4 
windows 10

when window minimize, setSize not work
