### ISSUE TITLE
electron6.0.0版本在部分win7系统的电脑上运行黑屏

### ISSUE THREAD

**Issue by 15164367531** [electron/electron#25186]
您好，我们项目使用vue+ electron6.0.0开发的桌面应用，但是最近发现我们应用在部分win7 64位操作系统中运行黑屏请问能提供解决方法吗？

**Comment by StaZhu** [comment]
win7SP1 或者win8请安装KB4019990即可解决（注：非SP1需要升级SP1才可安装）

**Comment by StaZhu** [comment]
this is because the lack of patch below
Windows6.1-KB4019990-x86.msu
Windows6.1-KB4019990-x64.msu
Windows8-RT-KB4019990-x64.msu

here is my installer.nsh, just for reference.

!macro customInit
    Var /GLOBAL WIN_VERSION
    Var /GLOBAL ARCH
    ClearErrors
        ReadRegStr $WIN_VERSION HKLM "Software\Microsoft\Windows NT\CurrentVersion" "CurrentBuild"
        ReadRegStr $ARCH HKLM "SYSTEM\CurrentControlSet\Control\Session Manager\Environment" "PROCESSOR_ARCHITECTURE"
        SetOutPath "$TEMP\your_app_name"
        SetOverwrite on
        ${if} $WIN_VERSION < 7600
            MessageBox MB_OK "The installation cannot continue as the operating system is not supported by Desktop Application."
            Abort
        ${elseif} $WIN_VERSION == 7600
            MessageBox MB_OK "Windows 7 Service Pack 1 required. You will be directed to download Windows 7 Service Pack 1 now. Please install it manually before you proceed."
            ${if} $ARCH == "x86"
                ExecShell "open" "https:://path/to/your/cdn/windows6.1-KB976932-x86.exe"
            ${elseif} $ARCH == "AMD64"
                ExecShell "open" "https:://path/to/your/cdn/windows6.1-KB976932-x64.exe"
            ${else}
                ExecShell "open" "https:://path/to/your/cdn/windows6.1-KB976932-ia64.exe"
            ${endIf}
            Abort
        ${elseif} $WIN_VERSION == 7601
            ExpandEnvStrings $1 %COMSPEC%
            ExecShellWait "" "$1" "/c $SysDir\systeminfo.exe | findstr KB4019990 > $TEMP\version" SW_HIDE
            FileOpen $2 $TEMP\version r
            FileRead $2 $3
            FileClose $2
            Delete $TEMP\version
            ${if} $3 == ""
                MessageBox MB_OK "Patch KB4019990 required. Will install it now."
                ${if} $ARCH == "x86"
                    File "..\..\..\..\statics\patches\Windows6.1-KB4019990-x86.msu"
                    ExecShellWait "open" "$TEMP\your_app_name\Windows6.1-KB4019990-x86.msu"
                ${elseif} $ARCH == "AMD64"
                    File "..\..\..\..\statics\patches\Windows6.1-KB4019990-x64.msu"
                    ExecShellWait "open" "$TEMP\your_app_name\Windows6.1-KB4019990-x64.msu"
                ${endIf}
                Goto done
            ${else}
                Goto done
            ${endif}
        ${elseif} $WIN_VERSION == 9200
            ExpandEnvStrings $1 %COMSPEC%
            ExecShellWait "" "$1" "/c $SysDir\systeminfo.exe | findstr KB4019990 > $TEMP\version" SW_HIDE
            FileOpen $2 $TEMP\version r
            FileRead $2 $3
            FileClose $2
            Delete $TEMP\version
            ${if} $3 == ""    
                ${if} $ARCH == "AMD64"
                    MessageBox MB_OK "Patch KB4019990 required. Will install it now."
                    File "..\..\..\..\statics\patches\Windows8-RT-KB4019990-x64.msu"
                    ExecShellWait "open" "$TEMP\your_app_name\Windows8-RT-KB4019990-x64.msu"                  
                ${endIf}
                Goto done
            ${else}
                Goto done
            ${endif}
        ${else}
            Goto done
        ${endif}
    done:
        RMDir /r "$TEMP\your_app_name"
!macroend

**Comment by jackple** [comment]
尝试安装.net 4.7.1+ 以修复

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If you're still experiencing this issue in Electron 8.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by StaZhu** [comment]
> Thank you for taking the time to report this issue and helping to make Electron better.
> 
> The version of Electron you reported this on has been superseded by newer releases. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).
> 
> If you're still experiencing this issue in Electron 8.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.
> 
> I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.
> 
> Thanks in advance! Your help is appreciated.

9.0 still having this issue

**Comment by 15164367531** [comment]
> 感谢您抽出宝贵的时间报告此问题并帮助改善Electrolect。
> 
> 您报告此问题的电子版本已被更旧的新版本取代。请参见我们[支持的版本文档](https://www.electronjs.org/docs/tutorial/support#supported-versions)。
> 
> 如果您在Electron 8.xy或更高版本中仍然遇到此问题，请添加注释以指定要测试的版本以及尝试重现此问题的维护人员应了解的其他任何新信息。
> 
> `blocked/need-info`由于上述原因，我正在设置标签。如果没有回应，此问题将在10天后关闭。
> 
> 提前致谢！感谢您的帮助。

**Comment by 15164367531** [comment]
> 这是因为
> Windows6.1-KB4019990-x86.msu下一组补丁
> Windows6.1-KB4019990-x64.msu
> Windows8-RT-KB4019990-x64.msu
> 
> 这是我的installer.nsh，如果您使用的是Electro-builder，则可以参考此内容。
> 
> ```
> !macro customInit
>     Var /GLOBAL WIN_VERSION
>     Var /GLOBAL ARCH
>     ClearErrors
>         ReadRegStr $WIN_VERSION HKLM "Software\Microsoft\Windows NT\CurrentVersion" "CurrentBuild"
>         ReadRegStr $ARCH HKLM "SYSTEM\CurrentControlSet\Control\Session Manager\Environment" "PROCESSOR_ARCHITECTURE"
>         SetOutPath "$TEMP\your_app_name"
>         SetOverwrite on
>         ${if} $WIN_VERSION < 7600
>             MessageBox MB_OK "The installation cannot continue as the operating system is not supported by Desktop Application."
>             Abort
>         ${elseif} $WIN_VERSION == 7600
>             MessageBox MB_OK "Windows 7 Service Pack 1 required. You will be directed to download Windows 7 Service Pack 1 now. Please install it manually before you proceed."
>             ${if} $ARCH == "x86"
>                 ExecShell "open" "https:://path/to/your/cdn/windows6.1-KB976932-x86.exe"
>             ${elseif} $ARCH == "AMD64"
>                 ExecShell "open" "https:://path/to/your/cdn/windows6.1-KB976932-x64.exe"
>             ${else}
>                 ExecShell "open" "https:://path/to/your/cdn/windows6.1-KB976932-ia64.exe"
>             ${endIf}
>             Abort
>         ${elseif} $WIN_VERSION == 7601
>             ExpandEnvStrings $1 %COMSPEC%
>             ExecShellWait "" "$1" "/c $SysDir\systeminfo.exe | findstr KB4019990 > $TEMP\version" SW_HIDE
>             FileOpen $2 $TEMP\version r
>             FileRead $2 $3
>             FileClose $2
>             Delete $TEMP\version
>             ${if} $3 == ""
>                 MessageBox MB_OK "Patch KB4019990 required. Will install it now."
>                 ${if} $ARCH == "x86"
>                     File "..\..\..\..\statics\patches\Windows6.1-KB4019990-x86.msu"
>                     ExecShellWait "open" "$TEMP\your_app_name\Windows6.1-KB4019990-x86.msu"
>                 ${elseif} $ARCH == "AMD64"
>                     File "..\..\..\..\statics\patches\Windows6.1-KB4019990-x64.msu"
>                     ExecShellWait "open" "$TEMP\your_app_name\Windows6.1-KB4019990-x64.msu"
>                 ${endIf}
>                 Goto done
>             ${else}
>                 Goto done
>             ${endif}
>         ${elseif} $WIN_VERSION == 9200
>             ExpandEnvStrings $1 %COMSPEC%
>             ExecShellWait "" "$1" "/c $SysDir\systeminfo.exe | findstr KB4019990 > $TEMP\version" SW_HIDE
>             FileOpen $2 $TEMP\version r
>             FileRead $2 $3
>             FileClose $2
>             Delete $TEMP\version
>             ${if} $3 == ""    
>                 ${if} $ARCH == "AMD64"
>                     MessageBox MB_OK "Patch KB4019990 required. Will install it now."
>                     File "..\..\..\..\statics\patches\Windows8-RT-KB4019990-x64.msu"
>                     ExecShellWait "open" "$TEMP\your_app_name\Windows8-RT-KB4019990-x64.msu"                  
>                 ${endIf}
>                 Goto done
>             ${else}
>                 Goto done
>             ${endif}
>         ${else}
>             Goto done
>         ${endif}
>     done:
>         RMDir /r "$TEMP\your_app_name"
> !macroend
> ```

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
