### ISSUE TITLE
Second socket on a session does not send Proxy-Authenticate for ntlm

### ISSUE THREAD

**Issue by lukeapage** [electron/electron#25184]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
* 9.0.0, 9.2.0, 9.2.1 0 All broken

* **Operating System:**
  * Windows 10 (1809)
* **Last Known Working Electron version:**
  * 8.5.0

### Expected Behavior
When requesting url's and having a socket connect, when it is rejected with proxy authentication required, consistently try again with the proxy authentication credentials.

### Actual Behavior
See logs - good and bad.
In the good logs, electron always makes a 2nd socket request with the proxy authentication headers and succeeds. In the bad logs, electron does not make a 2nd socket request.
Note that for the first socket request on a web page, it works, but when a second socket is opened to make requests it seems to fail.

### To Reproduce
Be behind a NTLM proxy that requires authentication for a domain
Visit a website that makes multiple requests so that multiple sockets are opened.

**Comment by lukeapage** [comment]
[netlog-921.txt](https://github.com/electron/electron/files/5140765/netlog-921.txt)
[netlog-850.txt](https://github.com/electron/electron/files/5140784/netlog-850.txt)

**Comment by lukeapage** [comment]
using https://netlog-viewer.appspot.com/#events

9.2.1: At the start it works:
![image](https://user-images.githubusercontent.com/309321/91536210-a9773100-e914-11ea-84d0-b914b4868e53.png)

but later on down.. there is no new socket with the authorization:

![image](https://user-images.githubusercontent.com/309321/91536344-e0e5dd80-e914-11ea-80ff-30f2256f76bb.png)

**Comment by lukeapage** [comment]
I've tried setting

```
browserWindow.webContents.session.allowNTLMCredentialsForDomains('*');
```

and

```
session.defaultSession.allowNTLMCredentialsForDomains('*');
```

but it makes no difference

**Comment by lukeapage** [comment]
and the effect in the devtools btw is that requests fail:
![image](https://user-images.githubusercontent.com/309321/91539431-987cee80-e919-11ea-9eaa-ecc57c0105a4.png)

we're in the process of seeing if the error occurs with 10.0. We're happy to provide any additional information or try anything.

**Comment by Priyanka1709** [comment]
Checked on electron 10.1.0 and the same error occurs there too.

**Comment by nornagon** [comment]
Unfortunately without any steps to reproduce this issue we can't debug further. Please provide a small example that reproduces the issue you're seeing, preferable using [Electron Fiddle](https://github.com/electron/fiddle).

Additionally, would you be able to confirm that Chrome works as you expect? If Chrome exhibits the same behavior, then unfortunately we can't take on fixing this issue—in that case, we would close this issue and direct you to report it to Chromium at https://crbug.com/new.

Thanks!

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by cifratila** [comment]
@lukeapage any luck on this one? Seems we are also seeing similar issues on Electron 10.

**Comment by lukeapage** [comment]
No, we haven’t upgraded, we were waiting to see if it stops happening in a new release.

**Comment by cifratila** [comment]
@lukeapage do you have a minimal repro of this issue?

**Comment by cifratila** [comment]
@lukeapage  Also just to understand you still see this issue on E12 or 13?

**Comment by lukeapage** [comment]
I have no repro because I have no public ntlm proxy and this happens against our proxy and specific domains - I’m afraid our team doesn’t have resources to help with this right now but we would love it to be fixed

**Comment by miniak** [comment]
I have a Fiddle repro, it's caused by the network request interceptors `session.webRequest.onXyz`
```js
const {app, BrowserWindow} = require('electron')

// we must remove the Electron token from the user-agent
app.userAgentFallback = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36'

// provide proxy credentials
app.on('login', (event, contents, details, info, callback) => {
  console.log('login')
  callback('authproxy', 'authproxy')
})

function createWindow () {
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      enableRemoteModule: false,
      contextIsolation: true,
      sandbox: true
    }
  })

  mainWindow.webContents.session.webRequest.onErrorOccurred(() => {
    console.log('onErrorOccurred')
  })

  mainWindow.loadURL('https://teams.microsoft.com/')
}

app.whenReady().then(() => {
  createWindow()

  app.on('activate', function () {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})
```

**Comment by miniak** [comment]
I've did a bisect of nightly builds and found the PR which broke it #21521

**Comment by miniak** [comment]
@lukeapage are you using the `webRequest` API?

**Comment by cifratila** [comment]
@groundwater @zcbenz @ckerr could we get you to prioritise this issue, it is a very major blocker for Teams to upgrade past Electron 8 (as this is reproduce-able on all 9+ versions)

**Comment by jkleinsc** [comment]
@miniak I can see an error on 11.4.8 with your repro, but I don't see it in 12 - nightly.  On 11, I see this error as soon as the Microsoft login appears:
```
onErrorOccurred: {
id: 4,
url: 'https://login.live.com/Me.htm?v=3',
method: 'GET',
timestamp: 1623342798218.125,
resourceType: 'other',
ip: '20.190.151.69',
fromCache: false,
statusLine: 'HTTP/1.1 200 OK',
statusCode: 200,
responseHeaders: {
'Cache-Control': [ 'max-age=315360000' ],
'Content-Encoding': [ 'deflate' ],
'Content-Length': [ '1114' ],
'Content-Type': [ 'text/html; charset=utf-8' ],
Date: [ 'Thu, 10 Jun 2021 16:33:18 GMT' ],
Expires: [ 'Sun, 08 Jun 2031 16:33:18 GMT' ],
P3P: [ 'CP="DSP CUR OTPi IND OTRi ONL FIN"' ],
PPServer: [ 'PPV: 30 H: BL02PF66CE3B1D2 V: 0' ],
'Referrer-Policy': [ 'strict-origin-when-cross-origin' ],
'Set-Cookie': [
'uaid=10b0b45d46c74d6bbc6be6f5c8587b5a; domain=login.live.com; Secure; path=/; SameSite=None; HttpOnly',
'MSPRequ=id=N&lt=1623342798&co=1; domain=login.live.com; Secure; path=/; SameSite=None; HttpOnly'
],
'Strict-Transport-Security': [ 'max-age=31536000' ],
Vary: [ 'Accept-Encoding' ],
'X-Content-Type-Options': [ 'nosniff' ],
'X-XSS-Protection': [ '1; mode=block' ],
'x-ms-request-id': [ 'f79b30a9-1740-43d8-ac01-c856749cca3d' ],
'x-ms-route-info': [ 'R3_BL2' ]
},
webContentsId: 1,
referrer: 'https://login.microsoftonline.com/',
error: 'net::ERR_ABORTED'
}
```

But in 12 - nightly that error message doesn't fire.  Do I need to login to see the error on newer versions?

**Comment by miniak** [comment]
I was told #29266 might be fixing this. Testing it out right now.

**Comment by lukeapage** [comment]
Yes we use webRequest api. So glad this is being fixed.
