### ISSUE TITLE
Cookie cannot be set after electron:build

### ISSUE THREAD

**Issue by Liupeng8** [electron/electron#25182]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.2.1
* **Operating System:**
  * windows10 x64
* **Last Known Working Electron version:**
  * unknown

### Expected Behavior
js-cookie at develop and build can be used normally.

### Actual Behavior
Cookie cannot be set after electron:build when I use js-cookie,but at the develop-env is normally.

### To Reproduce
$ vue create demo
$ cd demo
$ npm i
$ vue add electron-builder
$ choose electron 9.0 version
$ npm i js-cookie -S
$ at the vue page use [js-cookie](https://github.com/js-cookie/js-cookie) usage
$ npm run electron:build or npm run electron:serve
Or you can check [here](https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/1005)

### Screenshots
![91407878-821d5700-e875-11ea-8397-be3e803ac7a6](https://user-images.githubusercontent.com/23046680/91512062-b21b3780-e913-11ea-8460-e58d52e6c685.png)
![91408086-d6283b80-e875-11ea-9843-e34ae810beb8](https://user-images.githubusercontent.com/23046680/91512066-b3e4fb00-e913-11ea-8aa6-589c14ad7ec6.png)

**Comment by Liupeng8** [comment]
hava the same problem when i use electron session API

**Comment by Liupeng8** [comment]
@nornagon

**Comment by codebytere** [comment]
Please open this issue on [`electron-builder`](https://github.com/electron-userland/electron-builder) - this team does not maintain it.

**Comment by paramula** [comment]
it not working, js-cookie not working. what i do need?
