### ISSUE TITLE
openssl version returned from `process.versions.electron` is different than that of nodejs

### ISSUE THREAD

**Issue by shubhamyelekar** [electron/electron#25187]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *10.0.0
* **Operating System:**
  * macOS Mojave
* **Last Known Working Electron version:**
  * 
### Expected Behavior
`process.versions.electron` should return 1.1.1 with node 12.16.3
### Actual Behavior
It returns 1.1.0

### To Reproduce
Execute `process.versions.electron`  in dev console.

### Additional Information
As per release notes for [v10.0.0](https://www.electronjs.org/releases/stable#release-notes-for-v1000), electron uses nodejs 12.16.3. 
v12.16.3 [release notes](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#12.16.3) mentions that it uses openssl 1.1.1g. As `process` of electron is extended from `process` object of nodejs, why is `process.versions.electron`  returning `1.1.0` and not `1.1.1`?

Also as  1.1.1 is not FIPS compliant is there any plan to move it to openssl 3.0?

**Comment by MarshallOfSound** [comment]
@shubhamyelekar Electron does not use OpenSSL, we instead replace it with BoringSSL which is at least [partially FIPS validated](https://boringssl.googlesource.com/boringssl/+/master/crypto/fipsmodule/FIPS.md).  The version number in `process.versions.openssl` is a "fake" OpenSSL compatibility version number that boringssl exposes

**Comment by shubhamyelekar** [comment]
@MarshallOfSound 
Thanks for the response!
Can you please confirm the following things
1. Electron comes with node, when you said "Electron does not use OpenSSL", does this mean that openssl of node has been replaced with boringssl? 
2. How can I check the version of boringssl used in electron?
We need this info for FIPS validation.

-Shubham
