### ISSUE TITLE
Terminated Worker_Thread cause Electron app crush

### ISSUE THREAD

**Issue by linonetwo** [electron/electron#25199]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

The log is here https://pastebin.com/S4zMwUpG

* **Platform**: MacOS
* **Subsystem**: None

Electron Version: 9.1.2

Node Version: 12.14.1

Chromium Version: 83.0.4103.122

### What steps will reproduce the bug?

Use https://github.com/tiddly-gittly/TiddlyGit-Desktop/releases to create a workspace, and press Cmd+Q to quit it

### How often does it reproduce? Is there a required condition?

Always, if I start a server in the worker_thread inside Electron, and terminate it and quit the Electron app.

To start that worker_thread inside Electron, you may need to create an workspace inside this app.

If no workspace (with a http server) is running ,quitting app will not cause this crush.

### What is the expected behavior?

Silently terminate and quit.

### What do you see instead?

Open a MacOS App Crush dialog.

### Additional information

I have properly terminated the thread:

https://github.com/tiddly-gittly/TiddlyGit-Desktop/blob/ab603694b36a1e6f692599e3a02f87cee0025662/public/libs/wiki/wiki-worker-mamager.js#L87-L104

https://github.com/tiddly-gittly/TiddlyGit-Desktop/blob/ab603694b36a1e6f692599e3a02f87cee0025662/public/libs/wiki/wiki-worker.js#L32-L36

**Comment by codebytere** [comment]
@linonetwo Electron does not support `worker_threads` outside the main process - you should use web workers in this context.

**Comment by linonetwo** [comment]
Actually I'm using it from the main thread.

It works during development, and in production, until I quit the app (which is succeeded, too) but later after half a minute, there is a crash report.

**Comment by linonetwo** [comment]
Oh, this should be reopened...

**Comment by linonetwo** [comment]
Same as https://github.com/electron/electron/issues/23315

**Comment by linonetwo** [comment]
It has /dist/Electron.app/Contents/MacOS/Electron exited with signal SIGSEGV
