### ISSUE TITLE
electron-builder,productName in chinese Not showing correctly

### ISSUE THREAD

**Issue by bzsj** [electron/electron#25203]
Version: 22.8.0
Electron Version:10.0.1
Electron Type (current, beta, nightly):current
Target: NISI
"nsis": {
  "oneClick": false,
  "perMachine": true,
  "allowToChangeInstallationDirectory": true,
  "installerIcon": "./pic/dyb.ico",
  "uninstallerIcon": "./pic/dyb.ico",
  "installerHeaderIcon": "./pic/dyb.ico",
  "createDesktopShortcut": true,
  "createStartMenuShortcut": true,
  "artifactName":"${productName}${version}-setup.${ext}",
  "shortcutName": "电影"
}
shortcutName in chinese Random code After packing,app name on desktop is ��Ӱ��

If this isn't bug ，there settings solve the problem??? thanks very much !

**Comment by codebytere** [comment]
Please open this issue on [`electron-builder`](https://github.com/electron-userland/electron-builder) - this team does not maintain it.
