### ISSUE TITLE
electron rss memory keep rising when heapUsed/heapTotal does not

### ISSUE THREAD

**Issue by jackple** [electron/electron#25208]
I'm running an IM app which is using indexedDB. When I switch a chat, I have to get some large objects like messages and chatroom mambers from indexedDB or http request. I found that the heapUsed/heapTotal memory in main/renderer is perfectly normal, but the rss memory keep rising.

similar issues:
[https://spectrum.chat/electron/general/debugging-high-memory-usage-in-electron~80057ff2-a51c-427f-b6e1-c297d47baf5b](https://spectrum.chat/electron/general/debugging-high-memory-usage-in-electron~80057ff2-a51c-427f-b6e1-c297d47baf5b)

[https://github.com/nodejs/help/issues/1518](https://github.com/nodejs/help/issues/1518)

[http://seenaburns.com/debugging-electron-memory-usage/](http://seenaburns.com/debugging-electron-memory-usage/)

I have tested all the possible solutions, but still could not fix it...
I want to know that is there anyone facing this problem like this!!

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
12.x
* **Operating System:**
macOS 10.15.5
* **Last Known Working Electron version:**
7.x

### Expected Behavior
The memory usage return to normal

### Actual Behavior
The memory in renderer is stable, but the app's memory have risen and will not be back to normal.

### To Reproduce
https://github.com/jackple/electron-quick-start

### Screenshots
![image](https://user-images.githubusercontent.com/6183232/91640923-a2a30800-ea53-11ea-97a1-221e244d653d.png)

**Comment by jackple** [comment]
Is there any solution or advice?

**Comment by jackple** [comment]
Is there any solution or advice?

**Comment by nornagon** [comment]
It looks like this is (almost) entirely using Chromium APIs. Can you reproduce this issue in Chromium?

**Comment by jackple** [comment]
I think this is a problem that team of Electron should provide some solutions for improvement

**Comment by jackple** [comment]
Is there any mitigation option?

**Comment by nornagon** [comment]
@jackple hey there, still wondering if this is reproducible in Chrome itself. If so, it should be filed against https://crbug.com/new.
