### ISSUE TITLE
Environment variables set during runtime are now persisted after reload

### ISSUE THREAD

**Issue by lukehaas** [electron/electron#25200]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 9.2.1
* **Operating System:** MacOS 10.14.6
* **Last Known Working Electron version:** 8.2.3

### Expected Behavior
After reloading an instance of BrowserWindow any properties that were dynamically added to `process.env` should not longer be present.

### Actual Behavior
All previously added `process.env` properties are still present after reload.

### To Reproduce
Inside BrowserWindow instance:

`process.env.example = 'Hello World'`

Then reload with `browserWindowInstance.webContents.reload()`.

`process.env.example` is still defined. This was previously not the case.

**Comment by MarshallOfSound** [comment]
This is the new expected behavior, as of Electron 9 renderer process reuse is enabled by default (as per the changelog and breaking changes document).  This means when you reload it uses _the same process_.  If you modified the env before the reload it will be modified after the reload as well.
