### ISSUE TITLE
Dynamically enable/disable spellcheck

### ISSUE THREAD

**Issue by ccorcos** [electron/electron#25228]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

I'm replacing my custom spellcheck implementation with the native implementation: https://github.com/electron/electron/pull/20692

And one thing I am not able to do is dynamically enable/disable spellcheck.

### Proposed Solution

It looks like you cannot change webPreferences dynamically for good reasons: https://github.com/electron/electron/issues/10080

So maybe we can save this state somewhere else?

**Comment by ccorcos** [comment]
Hmm. `setSpellCheckerLanguages([])` seems to disable. To re-enabled, I tried `setSpellCheckerLanguages([...navigator.languages])` and I get the following error:

```
Invalid language code provided: "en" is not a valid language code
```

**Comment by ccorcos** [comment]
Hmm. This appears to work:

```
		session.setSpellCheckerLanguages(
			languages.filter(language =>
				session.availableSpellCheckerLanguages.includes(language)
			)
		)
```

**Comment by ccorcos** [comment]
So this solution works, but I'll leave this open in case ya'll want to add another API that does this under the hood.

**Comment by codebytere** [comment]
Given that it's possible to do right now and in the interest of keeping the core API thin where possible, we're going to close this out for now, but if more info arises we can definitely take another look and consider another solution :)

**Comment by jessep** [comment]
@codebytere Would you accept a PR adding this to [the spellchecker documentation](https://www.electronjs.org/docs/tutorial/spellchecker)? Would have saved me some time to have it there. Is there anywhere else in the docs that would make sense to references?
