### ISSUE TITLE
TouchBar Suggestions Enabled when autocomplete=off and spellcheck=false

### ISSUE THREAD

**Issue by bancona** [electron/electron#25234]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.2.0
* **Operating System:**
  * MacOS 10.15.5
* **Last Known Working Electron version:**
  * Unknown

### Expected Behavior

When autocomplete=off and spellcheck=false is set for an `<input>` or `<textarea>` element, no suggestions should appear on the Mac touchbar.

### Actual Behavior

When autocomplete=off and spellcheck=false is set for an `<input>` or `<textarea>` element, suggestions appear on the Mac touchbar.

### To Reproduce

Load the following in an Electron window: `"data:text/html,<textarea autocorrect=off spellcheck=false>"`

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.
