### ISSUE TITLE
A way to keep the multiple-language doc updated

### ISSUE THREAD

**Issue by hokein** [electron/electron#2524]
In Electron's repo,  there are some kinds of other foreign languages' documents translated by some contributors(Thanks all for them). 

It's quite nice for the native beginner, but there is an out-of-date issue of them. As the project developed, many new-added features and changes will cause the document updated. Right now we only keep the official document(English) updated.

I think we should figure out a way to keep all the translated document updated. I post a discussion here.

**Comment by jlord** [comment]
> I think we should figure out a way to keep all the translated document updated.

That would be great, do you have any ideas on how? I'm not sure if this is a problem that has been solved really? I'm involved in a couple of other projects that face this as well.

In [nodeschoo.io](http://nodeschool.io) we have a [system set up for supporting all the translations](https://github.com/nodeschool/nodeschool.github.io#translations) but it's also not ideal perhaps there are other ways?

**Comment by sotayamashita** [comment]
> I think we should figure out a way to keep all the translated document updated. I post a discussion here.

I agree w/ it

**Comment by etiktin** [comment]
Maybe we should add a banner to the start of each file that says what was the current version when it was edited and the time it was edited. That way, when someone looks at the document he/she will be able to figure out if it's outdated. If in doubt the user can go to the original and see when it was last edited. Something like:
```
Last updated: 2015-08-19
Release: v0.29.1
Original: <link to the original English file - this is only relevant to translations>
Translations: <links to each translation of the file - this should appear only in the English file>
```

I also think that translations should be put in a separate folder per language (currently the Korean translations are just thrown together with the English files). Something like `translations/ko/`.

When you search for something in the repository using GitHub and it's listed in the documentation, you will get duplicate matches from the translations (e.g. if you look for "BrowserWindow", every markdown file that mentions it appears twice, one for English and one for Korean). Maybe it's better if we move the translations to another repository. We can include the repository when building/developing using git submodules.

**Comment by OlsonDev** [comment]
+1 for putting the translations in separate folders. I was going to suggest that a while ago but didn't want to step on toes.

**Comment by jlord** [comment]
> for putting the translations in separate folders

Yeah, I'm thinking that too. It also messes up the [electron.atom.io/docs/all](http://electron.atom.io/docs/all) page because there are multiples of each doc and it gets looooooong.

I'm currently working on the Electron docs so I just assigned myself :sparkles:

**Comment by zcbenz** [comment]
> Maybe we should add a banner to the start of each file that says what was the current version when it was edited and the time it was edited.

You can get that information from GitHub's website, and the commit's page also shows the tag names.

> I also think that translations should be put in a separate folder per language (currently the Korean translations are just thrown together with the English files). Something like translations/ko/.

I'm strongly :+1: on this, and we should probably do it sooner than later. Another good thing of it is that translators no longer need to translate the URLs.

For the folder's name, `docs-translations` could probably be a better name, `translations` indicates they are translations of strings in the source code, which is common for i18n-ed projects.

**Comment by zeke** [comment]
🇨🇳 🇹🇼 🇧🇷 🇪🇸 🇰🇷 🇯🇵 🇷🇺 🇫🇷 🇹🇭 🇳🇱 🇹🇷 🇮🇩 🇺🇦 🇨🇿 🇮🇹

We are moving forward with [Crowdin](https://crowdin.com/project/electron), a third-party translation service that facilitates crowdsource translations. It's pretty nifty.

Anyone is welcome to join in the translation effort. For more details and info on how to help out, see this [electron/electron-i18n](https://github.com/electron/electron-i18n) repo.

As for the `docs-translations` directory: Even though it is incomplete and perpetually out of date, it is definitely still useful. I think we should leave that directory intact until we have a more complete alternative.
