### ISSUE TITLE
ready-to-show event is not fired and app window doesn't show

### ISSUE THREAD

**Issue by alexdevero** [electron/electron#25253]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.1
* **Operating System:**
  * Windows 10 (20H2)
* **Last Known Working Electron version:**
  * 9.0.0

### Expected Behavior

Calling `mainWindow.once('ready-to-show' ...)` and inside it `mainWindow.show()` after creating a new BrowserWindow() on windows shouldshow the main window when it is ready to show.

### Actual Behavior

The `mainWindow.once('ready-to-show' ...)` is not fired and window doesn't show.

### To Reproduce

- Clone my [boilerplate](https://github.com/alexdevero/electron-react-webpack-boilerplate).
- Update electron to +10.0.0
- Start the app with `npm run`

### Additional Information

Content of `main.js`.

```
'use strict'

// Import parts of electron to use
const { app, BrowserWindow } = require('electron')
const path = require('path')
const url = require('url')

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
let mainWindow

// Keep a reference for dev mode
let dev = false

// Broken:
// if (process.defaultApp || /[\\/]electron-prebuilt[\\/]/.test(process.execPath) || /[\\/]electron[\\/]/.test(process.execPath)) {
//   dev = true
// }

if (process.env.NODE_ENV !== undefined && process.env.NODE_ENV === 'development') {
  dev = true
}

// Temporary fix broken high-dpi scale factor on Windows (125% scaling)
// info: https://github.com/electron/electron/issues/9691
if (process.platform === 'win32') {
  app.commandLine.appendSwitch('high-dpi-support', 'true')
  app.commandLine.appendSwitch('force-device-scale-factor', '1')
}

function createWindow() {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    width: 1024,
    height: 768,
    show: false,
    webPreferences: {
      nodeIntegration: true
    }
  })

  // and load the index.html of the app.
  let indexPath

  if (dev && process.argv.indexOf('--noDevServer') === -1) {
    indexPath = url.format({
      protocol: 'http:',
      host: 'localhost:8080',
      pathname: 'index.html',
      slashes: true
    })
  } else {
    indexPath = url.format({
      protocol: 'file:',
      pathname: path.join(__dirname, 'dist', 'index.html'),
      slashes: true
    })
  }

  mainWindow.loadURL(indexPath)

  // Don't show until we are ready and loaded
  mainWindow.once('ready-to-show', () => {
    mainWindow.show()

    // Open the DevTools automatically if developing
    if (dev) {
      const { default: installExtension, REACT_DEVELOPER_TOOLS } = require('electron-devtools-installer')

      installExtension(REACT_DEVELOPER_TOOLS)
        .catch(err => console.log('Error loading React DevTools: ', err))
      mainWindow.webContents.openDevTools()
    }
  })

  // Emitted when the window is closed.
  mainWindow.on('closed', function() {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null
  })
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow)

// Quit when all windows are closed.
app.on('window-all-closed', () => {
  // On macOS it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  // On macOS it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (mainWindow === null) {
    createWindow()
  }
})
```

**Comment by andmm** [comment]
Same problem here on Windows 7 since updating to the latest 10.1.x  version. It happens intermittently, most of the time it will fire but sometimes it wont. It was fine in 9.2.1 and always fired using the same code.

**Comment by zcbenz** [comment]
I have tried a few times on my machine and could not reproduce, this seems to be machine dependent.

**Comment by quanglam2807** [comment]
It's likely that this bug also affect Electron 9.x. My app is using Electron 9.3.0 and a few users have reported that the window doesn't show up (but the app processes still show up in Task Manager). I couldn't reproduce the bug on my machine so I don't know if it's related to this.

**Comment by quanglam2807** [comment]
One important point: The 2 users who reported the bug both used Windows 10 2004. One user reported that the bug only occurred after updating from Windows 10 1909 to 2004. @alexdevero is using 20H2. So it's likely that this bug only affects newer versions of Windows 10.

**Comment by andmm** [comment]
> It's likely that this bug also affect Electron 9.x. My app is using Electron 9.3.0 and a few users have reported that the window doesn't show up (but the app processes still show up in Task Manager). I couldn't reproduce the bug on my machine so I don't know if it's related to this.

Well, that is exactly what is happening here and I'm running an old version of Win 7. Haven't tried with 9.3.0 though, up until 9.2.0 it always worked ok. 

I can reproduce this problem frequent enough that I'm going to make a video to illustrate. 

It's kinda frustrating since this event should always fire and not having window in a GUI application is obviously a problem. Something recently added to the codebase is making this event not fire in Windows and I don't believe the Windows version is related since it happens in both 7 and 10.

@zcbenz  I'll gladly help run any tests from my end if it helps figuring this out cause this is kind of a major bug and doesn't always happens.

**Comment by andmm** [comment]
Ok, here's the problem happening: 
https://www.youtube.com/watch?v=_zAP9HGUYrw

and here's the code creating the window: 

```const electron = require('electron');
const { app, BrowserWindow, Menu, dialog }  = require('electron');

let appWindow :any;

function createWindow() :void
{
 
   let { width, height } = electron.screen.getPrimaryDisplay().workAreaSize;
   let config = require('./config_file');
  
   let platformConfig :any = config.getPlatformConfig();
   platformConfig.width = width;
   platformConfig.height = height;

   appWindow = new BrowserWindow(platformConfig);
   appWindow.setMenu(null);
   let filePath :string =  __dirname + '\\main.html';

   appWindow.loadFile(filePath);     
             
   appWindow.once('ready-to-show', function(data)
   {   
      appWindow.maximize();
   });
};

app.on('ready', createWindow);
```

**Comment by BlessonKu** [comment]
I'm getting this issue too, except it'll fire randomly for me.
It works as expected on Electron v8.2.5 but not v10.1.1

I'm running Windows 10
![image](https://user-images.githubusercontent.com/45913736/93012503-a3b15a80-f566-11ea-8f89-419f43d2a9de.png)

I used [electron-forge](https://www.electronforge.io/) to create the project.
https://youtu.be/3yqDxhR2XxE?t=130

Here's the code


Index.js
```js
const {app, BrowserWindow} = require('electron');
const path = require('path');

if (require('electron-squirrel-startup')) { // eslint-disable-line global-require
  app.quit();
}

const createWindow = (WindowName,properties) => {
    properties = properties || {}
    
    properties.show = properties.show || false
    properties.frame = properties.frame || false
    
    if (!properties.webPreferences)
        properties.webPreferences= {
            nodeIntegration: true
        }
	
    var Window = new BrowserWindow(properties);
	
    Window.once('ready-to-show',function(){
        console.log('sending window to load')
        Window.show();
        Window.webContents.send('loadWindow', WindowName)
    });
    
    Window.loadFile(path.join(__dirname, '/window.html'));
    
    return Window
};

const createMainWindows = () => {
    
    mainWindow = createWindow('Main')//,{fullscreen:true});
	
    toolbarWindow = createWindow('Tools',{
        parent:mainWindow,
        width: 200,
        height: 400,
        fullScreenable: false,
        maxWidth: 300,
        x: 10,
        y: 60
    });
};

app.on('ready', createMainWindows);

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createMainWindows();
  }
});
```

**Comment by ArtimesT** [comment]
in my case, put mainWindow.once('ready-to-show', ...)  before  mainWindow.loadURL(indexPath) will be ok.

**Comment by grovesNL** [comment]
Possibly related to #42409 for people using title bar overlays
