### ISSUE TITLE
App crashes after printing using webContents.print()

### ISSUE THREAD

**Issue by paronix** [electron/electron#25254]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.0.1
  * 10.1.0
  * 10.1.1
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 9.2.1
  * 10.0.0

### Expected Behavior
Printing is succesful and the application does not crash after printing.

### Actual Behavior
Printing is succesful but immediately after the application closes with Exit status 3221225477

### To Reproduce
Use web Contents.print() in affected versions. See Fiddle at https://gist.github.com/3f840923e139cf11121a46e9bec3f5f9

### Additional Information
It does not seem to affect the V11 Beta's (tested in Electron Fiddle).

**Comment by bjbk** [comment]
Confirmed same for macOS. 
Electron v10.1.1
OS Version:            Mac OS X 10.15.6
Crashed Thread:        0  CrBrowserMain

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000018
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [23587]
