### ISSUE TITLE
Chrome Extension Support

### ISSUE THREAD

**Issue by sauliuspaukstys** [electron/electron#25250]
In documentation [Electron Documentation](https://www.electronjs.org/docs/api/extensions) it says chrome.runtime is supported in v10.1.0
When installing Electron (v10.1.0 or beta) window.chrome is still empty object.

**Comment by MarshallOfSound** [comment]
@sauliuspaukstys That documention is for Chrome Extensions.  You need to use `session.loadExtension` to load a chrome extension from disk and _that_ code will have access to that API

**Comment by tangYinPeng** [comment]
Extension load can succeed, but using chrome. Runtime. ConnectNative connection not only on local applications, but use the Google browser is ok. Is there a reason
