### ISSUE TITLE
Electron is creating more then 30 processes due to which CPU usage is very high

### ISSUE THREAD

**Issue by rush2arjun** [electron/electron#25260]
Hi Team,

Electron Version - 2.0.2
Operating System: Windows 10 64bit
Node version: 12.17.0

I am facing similar kind of error, electron is creating more then 30 processes due to which CPU usage is very high

Below screen shot shows multiple processes created by electron,
![image](https://user-images.githubusercontent.com/7426061/91874800-4a107c80-ec98-11ea-86bd-1a0ec4b51717.png)

Also, below is the backtrack,
ntoskrnl.exe!KeSynchronizeExecution+0x5b46
ntoskrnl.exe!KeWaitForSingleObject+0x1c2d
ntoskrnl.exe!KeWaitForSingleObject+0xab4
ntoskrnl.exe!KeWaitForSingleObject+0x255
ntoskrnl.exe!RtlClearBitsEx+0x15a7
ntoskrnl.exe!KeWaitForSingleObject+0x3828
ntoskrnl.exe!KeSynchronizeExecution+0x3120
ntdll.dll!RtlGetCurrentServiceSessionId+0xba8
ntdll.dll!RtlFreeHeap+0x51
ucrtbase.dll!free_base+0x1b
CTI-Endpoint.exe!GetHandleVerifier+0x9ac58
CTI-Endpoint.exe!GetHandleVerifier+0xe1c134
CTI-Endpoint.exe!GetHandleVerifier+0xe1cfaf
CTI-Endpoint.exe!GetHandleVerifier+0xe1c4d5
CTI-Endpoint.exe!GetHandleVerifier+0xe1bc85
CTI-Endpoint.exe!GetHandleVerifier+0xea3195
CTI-Endpoint.exe!GetHandleVerifier+0x121ea75
CTI-Endpoint.exe!IsSandboxedProcess+0x3b746a
CTI-Endpoint.exe!GetHandleVerifier+0x11c6640
CTI-Endpoint.exe!IsSandboxedProcess+0x16769d0
CTI-Endpoint.exe!IsSandboxedProcess+0x9c58f
CTI-Endpoint.exe!IsSandboxedProcess+0x3139ca
CTI-Endpoint.exe!IsSandboxedProcess+0x1dad3
CTI-Endpoint.exe!IsSandboxedProcess+0x1c631
CTI-Endpoint.exe!IsSandboxedProcess+0x3139ca
CTI-Endpoint.exe!IsSandboxedProcess+0xa4999
CTI-Endpoint.exe!IsSandboxedProcess+0xa4784
CTI-Endpoint.exe!GetHandleVerifier+0x35ea6
CTI-Endpoint.exe!IsSandboxedProcess+0x3cdea9
CTI-Endpoint.exe!IsSandboxedProcess+0x3cd704
CTI-Endpoint.exe!IsSandboxedProcess+0x3cdfa2
CTI-Endpoint.exe!GetHandleVerifier+0x71d35
CTI-Endpoint.exe!GetHandleVerifier+0x29a45
CTI-Endpoint.exe!GetHandleVerifier+0x2a533
CTI-Endpoint.exe!GetHandleVerifier+0x722a1
CTI-Endpoint.exe!GetHandleVerifier+0x71f14
CTI-Endpoint.exe!GetHandleVerifier+0x245ef
CTI-Endpoint.exe!IsSandboxedProcess+0x16f348
CTI-Endpoint.exe!IsSandboxedProcess+0x170716
CTI-Endpoint.exe!IsSandboxedProcess+0x321ed2
CTI-Endpoint.exe!IsSandboxedProcess+0x5d50e8
CTI-Endpoint.exe!IsSandboxedProcess+0x30725d
CTI-Endpoint.exe!IsSandboxedProcess+0x307150
CTI-Endpoint.exe!IsSandboxedProcess+0x107d91e
CTI-Endpoint.exe!GetHandleVerifier+0x10eb5a0
CTI-Endpoint.exe+0xdbc85
CTI-Endpoint.exe!IsSandboxedProcess+0x1673333
KERNEL32.DLL!BaseThreadInitThunk+0x14

Request to please help in resolving this issue.

_Originally posted by @rush2arjun in https://github.com/electron/electron/issues/13772#issuecomment-684954319_

**Comment by pushkin-** [comment]
Electron 2 isn't supported anymore. Secondly, we'd need to see the code that you're running.

**Comment by nornagon** [comment]
Closing as Electron 2 is not supported.
