### ISSUE TITLE
Android errors with building electron

### ISSUE THREAD

**Issue by RossComputerGuy** [electron/electron#25278]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** n/a
* **Operating System:** Arch Linux
* **Last Known Working Electron version:** n/a

### Expected Behavior
Electron should compile for Linux

### Actual Behavior
Android components compile as well

### To Reproduce
Build Electron and use Buildroot's clang

### Screenshots
![Screenshot from 2020-09-02 09-01-43](https://user-images.githubusercontent.com/19699320/92007547-f1be9680-ecfa-11ea-85ae-d5fe00d488e5.png)

**Comment by MarshallOfSound** [comment]
> use Buildroot's clang

We do not support any build system that isn't exactly what we / chromium use.  They use a very exact version of clang and we can't support third party clang builds as they may have different sets of flags / feature support

**Comment by RossComputerGuy** [comment]
But I don't think this is compiler related because it's ninja that was told to compile that file.

**Comment by RossComputerGuy** [comment]
I've identified the file being included in `src/components/payments/core/BUILD.gn`, so whatever dependency adds that also has this:
```
# Copyright 2017 The Chromium Authors. All rights reserved. 
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.                               
                                                           
static_library("core") {                        
  sources = [                           
    "android_app_description.cc",  
    "android_app_description.h",
    "autofill_card_validation.cc",
    "autofill_card_validation.h", 
....
```
So is this still a Buildroot related issue even though Android components are included on non-Android targeted builds?

**Comment by RossComputerGuy** [comment]
Ok so my little fix of running `sed -i -e '/android_app_description/ d' src/components/payments/core/BUILD.gn` worked. If upstream could be patched, that'll be nice.
