### ISSUE TITLE
Hunspell missing reference when enabling WinUseHybridSpellChecker

### ISSUE THREAD

**Issue by zarubond** [electron/electron#25276]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
We are currently detecting multiple Hunspell issues, where the reference is missing to it. This started happening after enabling native spellchecker on Windows.

` electron.exe.pdb
base::subtle::RefCountedThreadSafeBase::HasOneRef() ref_counted.cc:24
electron.exe.pdb
base::internal::WeakReferenceOwner::GetRef() weak_ptr.cc:70
electron.exe.pdb
base::WeakPtrFactory<DesktopMediaListBase>::GetWeakPtr() weak_ptr.h:328
electron.exe.pdb
SpellcheckHunspellDictionary::SpellCheckPlatformSetLanguageComplete(bool) spellcheck_hunspell_dictionary.cc:503
electron.exe.pdb
static void base::internal::Invoker<base::internal::BindState<void (SpellcheckHunspellDictionary::*)(bool) __attribute__((thiscall)),base::internal::UnretainedWrapper<SpellcheckHunspellDictionary> >,void (bool)>::RunOnce(class base::internal::BindStateBase *, bool) bind_internal.h:653
electron.exe.pdb
static void base::internal::Invoker<base::internal::BindState<base::OnceCallback<void (bool)>,bool>,void ()>::RunOnce(class base::internal::BindStateBase *) bind_internal.h:640
electron.exe.pdb
base::TaskAnnotator::RunTask(char const *,base::PendingTask *) task_annotator.cc:142
electron.exe.pdb
base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::sequence_manager::LazyNow *,bool *) thread_controller_with_message_pump_impl.cc:365
electron.exe.pdb
base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoSomeWork() thread_controller_with_message_pump_impl.cc:218
electron.exe.pdb
base::MessagePumpForUI::DoRunLoop() message_pump_win.cc:217
electron.exe.pdb
base::MessagePumpWin::Run(base::MessagePump::Delegate *) message_pump_win.cc:74
electron.exe.pdb
base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool,base::TimeDelta) thread_controller_with_message_pump_impl.cc:463
electron.exe.pdb
base::RunLoop::Run() run_loop.cc:156
electron.exe.pdb
content::BrowserMainLoop::MainMessageLoopRun() browser_main_loop.cc:1535
electron.exe.pdb
content::BrowserMainLoop::RunMainMessageLoopParts() browser_main_loop.cc:1062
electron.exe.pdb
content::BrowserMainRunnerImpl::Run() browser_main_runner_impl.cc:150
electron.exe.pdb
content::BrowserMain(content::MainFunctionParams const &) browser_main.cc:47
electron.exe.pdb
content::RunBrowserProcessMain(content::MainFunctionParams const &,content::ContentMainDelegate *) content_main_runner_impl.cc:527
electron.exe.pdb
content::ContentMainRunnerImpl::RunServiceManager(content::MainFunctionParams &,bool) content_main_runner_impl.cc:960
electron.exe.pdb
content::ContentMainRunnerImpl::Run(bool) content_main_runner_impl.cc:868
electron.exe.pdb
content::ContentServiceManagerMainDelegate::RunEmbedderProcess() content_service_manager_main_delegate.cc:52
electron.exe.pdb
service_manager::Main(service_manager::MainParams const &) main.cc:423
electron.exe.pdb
content::ContentMain(content::ContentMainParams const &) content_main.cc:19
electron.exe.pdb
wWinMain electron_main.cc:177
electron.exe.pdb
static int __scrt_common_main_seh() exe_common.inl:288
wkernel32.pdb
0x75056359 + 90969`

`electron.exe.pdb
base::TaskRunner::PostTask(base::Location const &,base::OnceCallback<void >) task_runner.cc:45
electron.exe.pdb
bool base::`anonymous namespace'::PostTaskAndReplyTaskRunner::PostTask(const class base::Location & const, class base::OnceCallback<void ()>) task_runner.cc:39
electron.exe.pdb
base::internal::PostTaskAndReplyImpl::PostTaskAndReply(base::Location const &,base::OnceCallback<void >,base::OnceCallback<void >) post_task_and_reply_impl.cc:138
electron.exe.pdb
base::TaskRunner::PostTaskAndReply(base::Location const &,base::OnceCallback<void >,base::OnceCallback<void >) task_runner.cc:51
electron.exe.pdb
bool base::PostTaskAndReplyWithResult<OnceCallback,SpellcheckHunspellDictionary::DictionaryFile,SpellcheckHunspellDictionary::DictionaryFile,void>(class base::TaskRunner *, const class base::Location & const, class base::OnceCallback<SpellcheckHunspellDictionary::DictionaryFile ()>, class base::OnceCallback<void (SpellcheckHunspellDictionary::DictionaryFile)>) task_runner_util.h:53
electron.exe.pdb
SpellcheckHunspellDictionary::PlatformSupportsLanguageComplete(bool) spellcheck_hunspell_dictionary.cc:483
electron.exe.pdb
static void base::internal::Invoker<base::internal::BindState<void (SpellcheckHunspellDictionary::*)(bool) __attribute__((thiscall)),base::internal::UnretainedWrapper<SpellcheckHunspellDictionary> >,void (bool)>::RunOnce(class base::internal::BindStateBase *, bool) bind_internal.h:653
electron.exe.pdb
static void base::internal::Invoker<base::internal::BindState<base::OnceCallback<void (bool)>,bool>,void ()>::RunOnce(class base::internal::BindStateBase *) bind_internal.h:640
electron.exe.pdb
base::TaskAnnotator::RunTask(char const *,base::PendingTask *) task_annotator.cc:142
electron.exe.pdb
base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::sequence_manager::LazyNow *,bool *) thread_controller_with_message_pump_impl.cc:365
electron.exe.pdb
base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoSomeWork() thread_controller_with_message_pump_impl.cc:218
electron.exe.pdb
base::MessagePumpForUI::DoRunLoop() message_pump_win.cc:217
electron.exe.pdb
base::MessagePumpWin::Run(base::MessagePump::Delegate *) message_pump_win.cc:74
electron.exe.pdb
base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool,base::TimeDelta) thread_controller_with_message_pump_impl.cc:463
electron.exe.pdb
base::RunLoop::Run() run_loop.cc:156
electron.exe.pdb
content::BrowserMainLoop::MainMessageLoopRun() browser_main_loop.cc:1535
electron.exe.pdb
content::BrowserMainLoop::RunMainMessageLoopParts() browser_main_loop.cc:1062
electron.exe.pdb
content::BrowserMainRunnerImpl::Run() browser_main_runner_impl.cc:150
electron.exe.pdb
content::BrowserMain(content::MainFunctionParams const &) browser_main.cc:47
electron.exe.pdb
content::RunBrowserProcessMain(content::MainFunctionParams const &,content::ContentMainDelegate *) content_main_runner_impl.cc:527
electron.exe.pdb
content::ContentMainRunnerImpl::RunServiceManager(content::MainFunctionParams &,bool) content_main_runner_impl.cc:960
electron.exe.pdb
content::ContentMainRunnerImpl::Run(bool) content_main_runner_impl.cc:868
electron.exe.pdb
content::ContentServiceManagerMainDelegate::RunEmbedderProcess() content_service_manager_main_delegate.cc:52
electron.exe.pdb
service_manager::Main(service_manager::MainParams const &) main.cc:423
electron.exe.pdb
content::ContentMain(content::ContentMainParams const &) content_main.cc:19
electron.exe.pdb
wWinMain electron_main.cc:177
electron.exe.pdb
static int __scrt_common_main_seh() exe_common.inl:288
wkernel32.pdb
0x76d06359 + 90969`

`electron.exe.pdb
base::internal::WeakReferenceOwner::GetRef() weak_ptr.cc:73
electron.exe.pdb
base::WeakPtrFactory<DesktopMediaListBase>::GetWeakPtr() weak_ptr.h:328
electron.exe.pdb
SpellcheckHunspellDictionary::SpellCheckPlatformSetLanguageComplete(bool) spellcheck_hunspell_dictionary.cc:503
electron.exe.pdb
static void base::internal::Invoker<base::internal::BindState<void (SpellcheckHunspellDictionary::*)(bool) __attribute__((thiscall)),base::internal::UnretainedWrapper<SpellcheckHunspellDictionary> >,void (bool)>::RunOnce(class base::internal::BindStateBase *, bool) bind_internal.h:653
electron.exe.pdb
static void base::internal::Invoker<base::internal::BindState<base::OnceCallback<void (bool)>,bool>,void ()>::RunOnce(class base::internal::BindStateBase *) bind_internal.h:640
electron.exe.pdb
base::TaskAnnotator::RunTask(char const *,base::PendingTask *) task_annotator.cc:142
electron.exe.pdb
base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::sequence_manager::LazyNow *,bool *) thread_controller_with_message_pump_impl.cc:365
electron.exe.pdb
base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoSomeWork() thread_controller_with_message_pump_impl.cc:218
electron.exe.pdb
base::MessagePumpForUI::DoRunLoop() message_pump_win.cc:217
electron.exe.pdb
base::MessagePumpWin::Run(base::MessagePump::Delegate *) message_pump_win.cc:74
electron.exe.pdb
base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool,base::TimeDelta) thread_controller_with_message_pump_impl.cc:463
electron.exe.pdb
base::RunLoop::Run() run_loop.cc:156
electron.exe.pdb
content::BrowserMainLoop::MainMessageLoopRun() browser_main_loop.cc:1535
electron.exe.pdb
content::BrowserMainLoop::RunMainMessageLoopParts() browser_main_loop.cc:1062
electron.exe.pdb
content::BrowserMainRunnerImpl::Run() browser_main_runner_impl.cc:150
electron.exe.pdb
content::BrowserMain(content::MainFunctionParams const &) browser_main.cc:47
electron.exe.pdb
content::RunBrowserProcessMain(content::MainFunctionParams const &,content::ContentMainDelegate *) content_main_runner_impl.cc:527
electron.exe.pdb
content::ContentMainRunnerImpl::RunServiceManager(content::MainFunctionParams &,bool) content_main_runner_impl.cc:960
electron.exe.pdb
content::ContentMainRunnerImpl::Run(bool) content_main_runner_impl.cc:868
electron.exe.pdb
content::ContentServiceManagerMainDelegate::RunEmbedderProcess() content_service_manager_main_delegate.cc:52
electron.exe.pdb
service_manager::Main(service_manager::MainParams const &) main.cc:423
electron.exe.pdb
content::ContentMain(content::ContentMainParams const &) content_main.cc:19
electron.exe.pdb
wWinMain electron_main.cc:177
electron.exe.pdb
static int __scrt_common_main_seh() exe_common.inl:288
wkernel32.pdb
0x763c6359 + 90969`

* **Electron Version:**
8
* **Operating System:**
  Windows 10
* **Last Known Working Electron version:**
7

### Expected Behavior
Should not crash.

### Actual Behavior
Crashed on undefined reference to Hunspell

### To Reproduce
Enable native spellchecking with `app.commandLine.appendSwitch('enable-features', 'WinUseBrowserSpellChecker,WinUseHybridSpellChecker');`

**Comment by miniak** [comment]
Electron 8 is not supported anymore.
