### ISSUE TITLE
setImmediate works only on first page load, but not after subsequent reloads.

### ISSUE THREAD

**Issue by marcus13345** [electron/electron#25314]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  * 10.1.0
* **Operating System:** 
  * windows 10
* **Last Known Working Electron version:** 
  * unknown

### Expected Behavior

`setImmediate` works the same regardless of whether you have loaded a page for the first time, or after a reload.

### Actual Behavior

`setImmediate` does execute on first page load, and does not after reloads.

### To Reproduce

I've created an [electron fiddle gist](https://gist.github.com/affedc59a009210f18d3d396bb9cc425) which shows the problem. The essence is that on first page load, setImmediate properly executes the given function, however, after reloading the page, with the same code, the invocation gets lost internally and never happens.

**Comment by nornagon** [comment]
I can reproduce this on Windows, but not on macOS. 🤔

**Comment by nornagon** [comment]
As a temporary workaround, `app.allowRendererProcessReuse = false` fixes this.
