### ISSUE TITLE
App crashes when printing the content

### ISSUE THREAD

**Issue by Suroor-Ahmmad** [electron/electron#25327]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.0
* **Operating System:**
  * Windows 7
* **Last Known Working Electron version:**
  * Didn't tried with any previous versions

### Expected Behavior
Main process shouldn't crash when printing any content in the render process.

### Actual Behavior
Main process crashes when trying to print `div` content

### To Reproduce
Angular application running over Electron, and triggering `window.print()` from new window (using `window.open()`)

**Comment by Suroor-Ahmmad** [comment]
I have came across many similar issues, and most of them tagged as Closed.

**Comment by hmt** [comment]
same here on macos 10.15.6

**Comment by hmt** [comment]
I created a fiddle with the code that makes electron crash. After testing a bit it seems the callback function causes the segfault:
https://gist.github.com/64b8970062113ce8db7d25722dcba46d

**Comment by Suroor-Ahmmad** [comment]
Were you able to fix this issue? @hmt

**Comment by Suroor-Ahmmad** [comment]
Yes, callback is causing issue, but my requirement slightly different, if you can suggest something here, I'll be grateful. I'm trying to print from angular app which is running over the electron, so I'm not calling `webContents.print(options)` from main process. Now app doesn't crash when I click Print but it crashes when I try to close the new window opened which has content to print.

    printFees() {
        var prtContent = document.getElementById('print-section');
        var WinPrint = window.open('', '_blank', 'left=0,top=0,width=800,height=900,toolbar=0,scrollbars=0,status=0');
        WinPrint.document.open();
        WinPrint.document.write(prtContent.innerHTML);
        WinPrint.document.close();
        const browser = this.electronService.remote.BrowserWindow; 
        let win = browser.getFocusedWindow();
        win.webContents.print();
        WinPrint.close(); //app crashes here, if I remove this everything works fine but even if I close the window manually, main process also closes

        //WinPrint.setTimeout(function () {
        //    WinPrint.close();
        //}, 1000);
    }

**Comment by hmt** [comment]
Not sure but I think the remote call makes it pretty much the same to electron. You could try to set up an ipc channel to let the main process handle the print?

**Comment by MaiconLeffa** [comment]
When I try to open a PDF in the integrated PDF viwer It Works Fine, but when I click to print, the preview window crashes. I am using reactjs. Some idea How to fix this issue?

**Comment by Suroor-Ahmmad** [comment]
> Not sure but I think the remote call makes it pretty much the same to electron. You could try to set up an ipc channel to let the main process handle the print?

I tried this way, but there's catch here, I want to print the content of newly opened window and not main window, so to achieve this I can't create `remote` object in `main.js` or pass `browser.getFocusedWindow()` object as `arg` in `ipcRenderer.send('print',window)`

**Comment by hmt** [comment]
Sorry, can't think of a solution

**Comment by codebytere** [comment]
Closing in favor of https://github.com/electron/electron/issues/25397

**Comment by Suroor-Ahmmad** [comment]
> When I try to open a PDF in the integrated PDF viwer It Works Fine, but when I click to print, the preview window crashes. I am using reactjs. Some idea How to fix this issue?
> 
> Using windows 10

Were you able to fix this?
