### ISSUE TITLE
warning in default repo

### ISSUE THREAD

**Issue by moje01konto** [electron/electron#25336]
`electron/js2c/renderer_init.js:14 (electron) Security Warning: webFrame.executeJavaScript was called without worldSafeExecuteJavaScript enabled. This is considered unsafe. worldSafeExecuteJavaScript will be enabled by default in Electron 12.
`
I delete renderer.js, preload etc. and still have this warning

**Comment by Slapbox** [comment]
Confirming this issue. Reproducible by creating a default Electron Fiddle with version `10.1.1`.

![image](https://user-images.githubusercontent.com/6835891/92417783-fbe4f880-f131-11ea-9bec-5c3340bdf448.png)

**Comment by Kenneth-Markus-Williams** [comment]
Right now it looks like `executeJavaScript` is called for every window opened by Electron to test `worldSafeExecuteJavaScript`, which if you don't have enabled will trigger the warning regardless if you're using it or not in your code.

**Comment by Slapbox** [comment]
@Kenneth-Markus-Williams is that a hypothesis or is there some code you can point to showing that's the cause?

**Comment by nornagon** [comment]
This is fixed by https://github.com/electron/electron/pull/25692, looks like we need to backport to 10.

**Comment by rosshamish** [comment]
Looks like this is already backported to 10. This issue can probably be closed.
- https://github.com/electron/electron/pull/25692#issuecomment-705752946
- #25827

**Comment by RogueXiaoxi** [comment]
这太麻烦了
