### ISSUE TITLE
.isMaximized() always false with transparent:true

### ISSUE THREAD

**Issue by barkermn01** [electron/electron#25348]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.
*I found one but it's been closed since 2017 athough updates are still happening on it either close this issue and reopen that or make this the new issue #9092* 

### Issue Details

* **Electron Version:**
  * v10.1.1
* **Operating System:**
  * Windows 10 18363
* **Last Known Working Electron version:**
  * unknown

### Expected Behavior
calling `isMaximized()` to respond if the window is maximized 

### Actual Behavior
`isMaximized()` always returns false when transparent is set to true on BrowserWindow

### To Reproduce
https://gist.github.com/293ffab750b019714f12d8e1f203e611

### Additional Information
#9092 is a closed issue with people still reporting this problems but since it's closed I don't think admins are looking hence creating this issue.

**Comment by arevi** [comment]
This has been an ongoing issue for years, it's possible to track this locally in your application and bypass the "isMaximized" method. Not a good solution, but it works.

**Comment by barkermn01** [comment]
> This has been an ongoing issue for years, it's possible to track this locally in your application and bypass the "isMaximized" method. Not a good solution, but it works.

this is not a correct method, because a Maximized window when dragged should normalize it's size to then be moved, so the local state will come out of sync.
