### ISSUE TITLE
[ASAR] fs.readdir/readdirSync with withFileTypes:true returns empty array

### ISSUE THREAD

**Issue by darron1217** [electron/electron#25349]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v10.1.1

* **Operating System:**
  * Windows 10 (2001)
* **Last Known Working Electron version:**
  * None

### Expected Behavior
Even when enabling `asar` option, `fs.readdirSync(dir, { withFileTypes: true })` should return an array of files.
Because the pull request(https://github.com/electron/electron/pull/24062) had already merged into master

### Actual Behavior
`fs.readdirSync(dir, { withFileTypes: true })` returns empty array `[]`

### To Reproduce
```js
const dir = 'dist\win-unpacked\resources\app.asar\config';
const fs = require('fs');
fs.readdirSync(dir, { withFileTypes: true }); // results []
```

**Comment by hatpick** [comment]
archive.stats return true/false instead of actual stats
