### ISSUE TITLE
(Devtools) Bug Color Picker CSS

### ISSUE THREAD

**Issue by helple** [electron/electron#25352]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
Electron Version: All Version
Operating System: macOS 10.15.3
Last Known Working Electron version: Never

### Bug
The color picker in devtools does not work.
In devtools if you want to change the colors of the CSS code. When you click on a color a color picker is supposed to appear but it does not appear.

### Screenshots
<img width="1013" alt="Capture d’écran 2020-09-07 à 11 42 44" src="https://user-images.githubusercontent.com/70572698/92374841-988ea280-f100-11ea-96be-afc93f6dd645.png">

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Standalone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

**Comment by helple** [comment]
This bug is present on Mac on Windows and Linux. It does not matter the version of electron.  

I will explain the problem to you again and I would like you on your side to try to see it. It’s not a bug my fault, it’s an electron bug. 
In the devtools when you want to change a color at the css level the chromium devtool color picker does not appear. 
Please try your side you will see.
This bug is present on all versions of electron on Mac, Window and Linux.  

Please take the time to see it instead of classifying this issue.

**Comment by codebytere** [comment]
By adding:

```
  mainWindow.loadURL('https://github.com/electron/electron/issues/25352')
  mainWindow.webContents.openDevTools()
```

to a simple Electron app and clicking into a CSS color to change it, the color picker appears just fine. As such i do not believe this to be an Electron bug and am closing it out.

<img width="1204" alt="Screen Shot 2020-09-23 at 7 40 56 PM" src="https://user-images.githubusercontent.com/2036040/94094679-eda30780-fdd4-11ea-9bbb-21c8aa65e12c.png">

<img width="1204" alt="Screen Shot 2020-09-23 at 7 40 36 PM" src="https://user-images.githubusercontent.com/2036040/94094683-f09df800-fdd4-11ea-9430-e932d4dde490.png">

<img width="1209" alt="Screen Shot 2020-09-23 at 7 40 14 PM" src="https://user-images.githubusercontent.com/2036040/94094692-f4317f00-fdd4-11ea-888d-7fd11ed8b48b.png">

**Comment by m4heshd** [comment]
@codebytere I think this issue is misinterpreted. It's the color picker tool that doesn't work. Not the color chooser popup. 

![image](https://user-images.githubusercontent.com/6711514/122121496-59d50800-ce49-11eb-9ad8-147c661338e4.png)

Try the picker to pick a color from the page. It never worked on any version of Electron including the latest.

**Comment by nornagon** [comment]
I can reproduce this on macOS on all versions that I tried (at least from 9.x until present.)

**Comment by m4heshd** [comment]
@nornagon Thank you. I hope it gets fixed. Not a huge issue but a minor inconvenience that can be irritating in very specific scenarios.

**Comment by codebytere** [comment]
@m4heshd i had a small window to investigate this this morning and put up a PR so it'll be fixed soon
