### ISSUE TITLE
Show PDF in iframe

### ISSUE THREAD

**Issue by cproduct** [electron/electron#25350]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

I try to view a PDF in iframe, but without success. Instead of showing the PDF, a file save dialog opens.

Found some closed / related tasks #12337, #16185, but no solution.

### Additional Information

Electron version: 10.1.1

### Test project
My test projects is very simple.

index.html:
`<html><body><iframe src="PDFSample.pdf"></iframe></body></html>`

main.js
`app.whenReady().then(() => {
  const w = new BrowserWindow({
    webPreferences: {
      plugins: true
    }
  })
  w.loadFile('index.html')
})`

(Requires PDFSample.pdf file in project root.)

**Comment by MarshallOfSound** [comment]
This works in latest Electron (as of today)
