### ISSUE TITLE
Uncaught Exception when trying to access several members of Session object received from 'session-created' event

### ISSUE THREAD

**Issue by thomasLechaptois** [electron/electron#25356]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.2 (was already failing with 10.0.0-beta1)
* **Operating System:** 
  * Windows 10 (2004) and macos 10.15.5
* **Last Known Working Electron version:**
  * 9.3.1

### Expected Behavior
All members of the session object can be accessed.

### Actual Behavior
An error popup appears:
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
TypeError: Illegal invocation: Function must be called on an object of type Session
    at App.<anonymous> (G:\git\electronSession\main.js:6:29)
    at App.emit (events.js:310:20)
    at App.init (G:\git\electronSession\main.js:9:22)
    at App.emit (events.js:310:20)

### To Reproduce
```sh
$ git clone https://github.com/thomasLechaptois/electronSessionIssue
$ npm install
$ npm start || electron .
```

**Comment by sprgchma** [comment]
Same here, it looks like instead of a `session` electron gives an `Event` as the first parameter of the `session-created` event handler.
`console.log(session)` gives such output - i can see `.sender` and `.preventDefault()` of the `Event` object.

```
Session {
  preventDefault: [Function: preventDefault],
  sender: App {
    _events: [Object: null prototype] {
      'certificate-error': [Function],
      'select-client-certificate': [Function],
      quit: [Function],
      'window-all-closed': [Array],
      'session-created': [Function: bound contSubscribeToSession],
      'web-contents-created': [Array],
      ready: [Array],
      activate: [Function],
      'open-url': [Function: bound contWithUrl],
      'second-instance': [Function: bound contWithExternal]
    },
    _eventsCount: 10,
    _maxListeners: undefined,
    commandLine: {
      hasSwitch: [Function: hasSwitch],
      getSwitchValue: [Function: getSwitchValue],
      appendSwitch: [Function: appendSwitch],
      appendArgument: [Function: appendArgument]
    },
    _setDefaultAppPaths: [Function],
    [Symbol(kCapture)]: false
  }
}
```

**Comment by lmancel** [comment]
Hi there,

Similar issue here, almost every member of Session items are impossible to access and throw the same error (as reported above).
Is it possible that the issue comes from what was done in https://github.com/electron/electron/pull/23569 ?

**Comment by lmancel** [comment]
Might already be taken care of in #25457
