### ISSUE TITLE
Hiding a maximized window does not work

### ISSUE THREAD

**Issue by t57ser** [electron/electron#25367]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.1
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 8

### Expected Behavior
The window should hide

### Actual Behavior
The window stays visible but appears blank, if the window is restored from the maximized state it gets black

### To Reproduce
```
	let browserWindow = new BrowserWindow({
		show: true
	});
	browserWindow.maximize();
	browserWindow.hide();

	browserWindow.loadURL("http://www.google.com").then(() => {
	});
```
### Screenshots
![grafik](https://user-images.githubusercontent.com/10595986/92474422-196e9c80-f1dc-11ea-928e-1161bb607645.png)

**Comment by pushkin-** [comment]
FWIW, this happens when you call `hide` immediately after `maximize`. Doing the `hide` call on a `setTimeout(..., 50)` makes it work. (A delay of 10ms is too short)

**Comment by t57ser** [comment]
I can no longer reproduce with electron 17
