### ISSUE TITLE
WebContents `canGoBack` and `canGoForward` return incorrect values starting from Electron v10.0.0 

### ISSUE THREAD

**Issue by taras-slapdash** [electron/electron#25360]
### Issue Details

* **Electron Version:**
  * v10.0.0
* **Operating System:**
  * macOS 10.15.6
* **Last Known Working Electron version:**
  * v9.3.0

### Expected Behavior

`WebContents.canGoBack()` and `WebContents.canGoForward()` must return correct values when the browser can go back or forward.

### Actual Behavior

- `WebContents.canGoBack()` returns `true` after the first in-page navigation and then never changes again.
- `WebContents.canGoForward()` always returns `false`. 

### To Reproduce

- Load the gist in Electron Fiddle https://gist.github.com/taras-slapdash/5f7302cc72c05bfbc8f6372ae04e5050
- Run the app
- In the app window, open Console in Developer Tools 
- Execute `history.pushState(null, null, '#foo');`
- Execute `history.back()` 
- Execute `history.forward()` 
- Check the logs in Electron Fiddle Console and notice that for Electron v10.0.0 `canGoBack()` and `canGoForward()` always return the same values (which is different from Electron v9.3.0).

### Screenshots

v9.3.0 (**GOOD**)
![image](https://user-images.githubusercontent.com/57078134/92467334-54b3a000-f1c9-11ea-8d6c-42d43ffe27ac.png)

v10.0.0 (**BAD**)

![image](https://user-images.githubusercontent.com/57078134/92467482-9f351c80-f1c9-11ea-9c84-278dee3d4a1f.png)

**Comment by taras-slapdash** [comment]
From the [changelog](https://www.electronjs.org/releases/stable#release-notes-for-v1000), this https://github.com/electron/electron/pull/22202 might be related ("Fixed issue where navigating with the mouse buttons 4/5 would result in full page loads instead of in-page popstate navigations"). cc @MarshallOfSound

**Comment by taras-slapdash** [comment]
FYI: this is still the issue in Electron v11.1.1

**Comment by taras-slapdash** [comment]
Also, the issue in v11.2.0.

**Comment by patchkov** [comment]
Can confirm the issue in v11.2.0. Did you find any solution or workaround?

**Comment by taras-slapdash** [comment]
@patchkov , sort of. We built history tracking and used it to define `canGoBack` and `canGoForward`. Alternatively, you can keep navigation buttons always enabled and then sometimes they will be a no-op (obviously not a great UX). 

Haven't tried v12, maybe it has the fix?

**Comment by lxmou666** [comment]
Also, the issue in v12.0.0.

**Comment by wilkerlucio** [comment]
I can confirm this still an issue on Electron `12.0.8`

**Comment by nornagon** [comment]
This is fixed in Electron 14. For complicated and boring reasons, the fix isn't easily backportable. I'm closing this as fixed.
