### ISSUE TITLE
alwaysOnTop + showInactive() are not working properly together

### ISSUE THREAD

**Issue by aabuhijleh** [electron/electron#25388]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.3.0
* **Operating System:** 
  * Windows 10
* **Last Known Working Electron version:**
  * Not sure

### Expected Behavior

If a browserWindow is created with the options `{alwaysOnTop: true, show: false}` and then is shown with `showInactive()` while another full screen application is running, the browserWindow should be on top of the full screen application

### Actual Behavior

If a browserWindow is created with the options `{alwaysOnTop: true, show: false}` and then is shown with `showInactive()` while another full screen application is running, the browserWindow is not shown on top, in fact, it is on "bottom" (see the attached screen recording)

### To Reproduce

```sh
$ git clone https://github.com/aabuhijleh/alwaysOnTopAndShowInactiveIssue.git
$ npm install
$ npm start
```
* Open another full screen app before the browserWindow is shown
* When the browserWindow is finally shown, it won't be on top!

### Screen recording

![KULFJYTV9m](https://user-images.githubusercontent.com/42934634/92563346-20e78180-f280-11ea-8f91-e66c57cfa316.gif)

### Additional Information

`browserWindow.show()` works but it steals focus form other applications and I don't want that to happen

**Comment by twitharshil** [comment]
Facing the same issue, able to reproduce it with electron v8, v9, v10 on Mac os.  Any workarounds will help here !!
Not able to reproduce the issue for electron v7

**Comment by aabuhijleh** [comment]
`.show()` works for me but some users still report that they still have this issue after this bad "workaround"...

**Comment by aabuhijleh** [comment]
Using `win.setAlwaysOnTop(true, "screen-saver", 1);` works
