### ISSUE TITLE
[Bug]: Electron segmentation fault on CentOS7 aarch64(arm64)

### ISSUE THREAD

**Issue by itas109** [electron/electron#25387]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.4
  * 10.1.1
* **Operating System:**
  * centos 7.6  aarch64

### Expected Behavior
Electron running normal

### Actual Behavior
Electron failing with segmentation fault.

### To Reproduce
```
wget https://github.com/electron/electron/releases/download/v10.1.1/electron-v10.1.1-linux-arm64.zip
unzip electron-v10.1.1-linux-arm64.zip
./electron
segmentation fault
```

**Comment by itas109** [comment]
I think it is linux kernel's PAGESIZE problem.
PAGESIZE = 64k on cetos 7 aarch64 (redhat 7)
but, 
PAGESIZE = 4K on other linux(such debian aarch64)
PAGESIZE = 4K on centos 7 x86_64
```
$ getconf PAGESIZE
65535
```

---
i think two way can resolve it : 
* recompile centos 7 aarch64 linux kernel, change PAGESIZE 64K to PAGESIZE 4K
* recomplire electron on centos 7 aarch64 with PAGESIZE 64K

**Comment by bigben0123** [comment]
In build/config/compiler
`
    if (current_cpu == "arm64") {
      # Reduce the page size from 65536 in order to reduce binary size slightly
      # by shrinking the alignment gap between segments. This also causes all
      # segments to be mapped adjacently, which breakpad relies on.
      ldflags += [ "-Wl,-z,**max-page-size=4096**" ]
      print(ldflags)
    }
`
Changing max page size  from 4096 to 65536, does it fix this error?

**Comment by nornagon** [comment]
Can you attach a crash dump? A core dump will do.

**Comment by abnerlee** [comment]
seems same error on 13.1.7

**Comment by zachberger** [comment]
Same issue on Asahi linux which uses 16K pages

**Comment by jesse-savary** [comment]
Also running into this w/ CentOS 8: Output of `uname -a`:
`Linux [redacted] 5.4.17-2136.302.7.2.1.el8uek.aarch64 #2 SMP Tue Jan 18 12:11:39 PST 2022 aarch64 aarch64 aarch64 GNU/Linux`.

**Comment by flotwig** [comment]
This still seems to be an issue on CentOS 8 / RHEL 8 / Oracle Linux Server 8.6, with Electron 18.3.0, and the latest stable (19.0.0), and the latest beta (v20.0.0-beta.8).

Cypress users are affected by this as they try to use the `linux-arm64` builds to test inside of A1 Ampere, more info: https://github.com/cypress-io/cypress/issues/22820

@deepak1556 do you have any additional context on this issue? I see #34385 refs this

**Comment by Lemmingh** [comment]
[^1]: <https://dev.to/aws-heroes/postgresql-on-arm-default-page-size-matters-2n7a>

[^2]: <https://chromium-review.googlesource.com/c/chromium/src/+/3545665>

It's said that:

> Distributions, like **CentOS**, **RedHat**, or **Oracle Linux**, set the default page size to **64k** [^1]

However, Chromium seems to show no interest in 64 Ki page size in the foreseeable future:

> The rare 64kb case is still **not supported** due to further changes needed [^2]

**Comment by zebrapurring** [comment]
Bump

**Comment by ZhengXL1988** [comment]
Bump

**Comment by ZhengXL1988** [comment]
same error, I tried to compile, but failed。Has anyone compiled the electron on arm64 and PAGESIZE=64K，give me a compiled copy，tks

**Comment by yueming408892434** [comment]
I also encountered a problem. On the arrch service version, there is a segment error. What is the solution，thank you

**Comment by zebrapurring** [comment]
Bump

**Comment by Z-eddy** [comment]
Bump,the same error

**Comment by codebytere** [comment]
Per https://github.com/electron/electron/issues/25387#issuecomment-1193169058 - this isn't something Chromium currently supports correctly. Should they do so, we can revisit this, but i'm closing this out for now.

**Comment by chenamy2017** [comment]
Bump,the same error.

**Comment by chenamy2017** [comment]
Bump,the same error.
Has anyone compiled the electron on arm64 with PAGESIZE=64K ? How to compile.

**Comment by itas109** [comment]
> Bump,the same error. Has anyone compiled the electron on arm64 with PAGESIZE=64K ? How to compile.

email to itas109#qq.com

**Comment by Rtoax** [comment]
I got SIGTRAP dump when compiled chromium on Linux+ARM64 with 4kiB PAGESIZE, and run chromium on Linux+ARM64 with 64kiB PAGESIZE. 

> I think it is linux kernel's PAGESIZE problem. PAGESIZE = 64k on cetos 7 aarch64 (redhat 7) but, PAGESIZE = 4K on other linux(such debian aarch64) PAGESIZE = 4K on centos 7 x86_64
> 
> ```
> $ getconf PAGESIZE
> 65535
> ```
> 
> i think two way can resolve it :
> 
> * recompile centos 7 aarch64 linux kernel, change PAGESIZE 64K to PAGESIZE 4K
> * recomplire electron on centos 7 aarch64 with PAGESIZE 64K

I got SIGTRAP dump when compiled chromium on Linux+ARM64 with 4kiB PAGESIZE, and run chromium on Linux+ARM64 with 64kiB PAGESIZE.  If i compile chromium on Linux+ARM64 with 64kiB PAGESIZE, it'll not success, and i don't know way, have you ever meet this before?

```
[headless_shell:16128/41761] ACTION //net/data/ssl/chrome_roo...:gen_root_store_inc(//build/toolchain/linux/unbundle:default)
FAILED: gen/net/data/ssl/chrome_root_store/chrome-root-store-inc.cc gen/net/data/ssl/chrome_root_store/chrome-ev-roots-inc.cc 
/usr/bin/python3 ../../build/gn_run_binary.py root_store_tool --root-store=../../net/data/ssl/chrome_root_store/root_store.textproto --certs=../../net/data/ssl/chrome_root_store/root_store.certs --write-cpp-root-store=gen/net/data/ssl/chrome_root_store/chrome-root-store-inc.cc --write-cpp-ev-roots=gen/net/data/ssl/chrome_root_store/chrome-ev-roots-inc.cc
root_store_tool failed with exit code -5
```

**Comment by liuhann** [comment]
> In build/config/compiler
> 
> ```
>     if (current_cpu == "arm64") {
>       # Reduce the page size from 65536 in order to reduce binary size slightly
>       # by shrinking the alignment gap between segments. This also causes all
>       # segments to be mapped adjacently, which breakpad relies on.
>       ldflags += [ "-Wl,-z,**max-page-size=4096**" ]
>       print(ldflags)
>     }
> ```
> 
> Changing max page size from 4096 to 65536, fixed my issue.

Hi  do you have a compiled version of electron,  Thanks for your share

**Comment by liuhann** [comment]
> > In build/config/compiler
> > ```
> >     if (current_cpu == "arm64") {
> >       # Reduce the page size from 65536 in order to reduce binary size slightly
> >       # by shrinking the alignment gap between segments. This also causes all
> >       # segments to be mapped adjacently, which breakpad relies on.
> >       ldflags += [ "-Wl,-z,**max-page-size=4096**" ]
> >       print(ldflags)
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Changing max page size from 4096 to 65536, fixed my issue.
> 
> Hi do you have a compiled version of electron, Thanks for your share


Simple change compile scripts does not work. I had find there are quite a lot of code with 4096 hard code on it . but the code are not belong to electron, mybe chrominum

I had changed some of the code, and got a binary, it can simply run by with error when running https pages or call importCertificate
