### ISSUE TITLE
TypeError cannot read property exposeInMainWorld of undefined

### ISSUE THREAD

**Issue by Yuri6037** [electron/electron#25409]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v10.1.0

* **Operating System:**
  * Linux Pop!_OS 20.04
* **Last Known Working Electron version:**
  * Not applicable

### Expected Behavior

No errors.

### Actual Behavior

The error "TypeError cannot read property exposeInMainWorld of undefined" is not expected.

### To Reproduce

```TypeScript
import { contextBridge, app, BrowserWindow } from "electron";
import {ContextBridge} from "./ContextBridge";

function main() {
    const win = new BrowserWindow({
        title: "Test",
        width: 800,
        height: 600,
        minWidth: 800,
        minHeight: 600,
        webPreferences: {
            worldSafeExecuteJavaScript: true,
            contextIsolation: true
        }
    });
    contextBridge.exposeInMainWorld("electron", new ContextBridge());
    win.loadFile("index.html");
}

app.on("ready", main);
```

**Comment by MarshallOfSound** [comment]
`contextBridge` is an API that can only be used in the renderer process as per our documentation.

**Comment by Yuri6037** [comment]
How useful is that? It would be much more useful to allow a bridge in the other direction!
