### ISSUE TITLE
Exit from HTML fullscreen and enter native fullscreen leads to appearance of unclickable fantom window image.

### ISSUE THREAD

**Issue by kirille** [electron/electron#25427]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v10.1.1
* **Operating System:**
  * macOS 10.15.6
* **Last Known Working Electron version:**
  * 

### Expected Behavior
consecutive exit from HTML fullscreen and enter native fullscreen do not create unclickable and indestructible fantom window image.

### Actual Behavior
consecutive exit from HTML fullscreen and enter native fullscreen create unclickable and indestructible fantom window image.

### To Reproduce

Modified electron quick-start project:

[kirille/electron-fullscreen-fantom-issue](https://github.com/kirille/electron-fullscreen-fantom-issue)

on start, opens app in html-fullscreen, on click on Do Bug button, exit html-fullscreen, wait for exit, enter native fullscreen.

### Screenshots

<img width="1143" alt="Screenshot 2020-09-11 at 18 19 32" src="https://user-images.githubusercontent.com/6457945/92944398-97d97180-f45c-11ea-973f-58cf68c9dd42.png">

**Comment by hovancik** [comment]
Hi @codebytere ,

I am having similar issue with electron 9 on macOS

I have a fullscreen window and when I close it, in CMD+Tab I can still see it as an option. When I "open it", there is a phantom fullscreen window, like in a screenshot: (you can see that top and bottom bar are hidden by that window)

<img width="256" alt="image" src="https://user-images.githubusercontent.com/4745859/93663353-9cf37d80-fa67-11ea-9abf-61ac3d428862.png">

I did some digging and: 
- both versions 9.1 and 9.3 are broken
- version 9.1 with `app.dock.hide()` works fine

**Comment by kirille** [comment]
Hi @codebytere,

The issue is still reproducible with electron 11.

Updated project to reproduce: https://github.com/kirille/electron-fullscreen-fantom-issue

Is there any hope to fix this in near future? It brings pretty terrible UX.

**Comment by kirille** [comment]
Reproducible with electron version 12.0.0-beta.24 as well

**Comment by codebytere** [comment]
hey folks - https://github.com/electron/electron/pull/25470 closes this :) It'll be merged soon!

**Comment by kirille** [comment]
Hi @codebytere, 
it looks like https://github.com/electron/electron/pull/25470 got stuck again, is there any progress on this?

**Comment by kirille** [comment]
Hi @codebytere,
#25470  still not merged due to failed tests. Please assist.
