### ISSUE TITLE
BrowserView unusable

### ISSUE THREAD

**Issue by AlexandraK** [electron/electron#25423]
I don't understand why is this feature available in production if it's completely unusable?
I just spent hours trying to debug it, when in fact the problem is that the class is poorly written and throws errors when multiple views are created, but nowhere is that mentioned.

**Comment by pushkin-** [comment]
this is more of a rant than an issue report. what specific code leads to a crash.

**Comment by AlexandraK** [comment]
Ok sorry, it seems to work fine in stable version Electron 10.
I had Electron 11 that apparently is not stable. But still you should warn people about this stuff :/

**Comment by pushkin-** [comment]
I don't work on the Electron team, and Electron 11 isn't a stable release anyway - it's in beta. You should post the code that causes the issue so the team can look into it.
