### ISSUE TITLE
搭建vue + electron环境，多次尝试，在mac系统，windows系统，均卡在了安装

### ISSUE THREAD

**Issue by flying-birds-do** [electron/electron#25424]
![image](https://user-images.githubusercontent.com/20589366/92939037-dd5b6600-f47f-11ea-9e19-02826de6597a.png)
尝试过^8.00 和^9.00 的，但是不知道什么原因总是卡住无法安装成功。
分别尝试用yarn 的淘宝镜像，npm 的淘宝镜像，npm 安装，均无法在最后一步成功，不知如何解决。 vue add electron-builder 这个命令一直无法成功，忘得到解决方案

**Comment by dongasai** [comment]
网络原因,部分安装包下载地址被墙了

**Comment by dongasai** [comment]
卡在那个包上旧百度搜,xx包 下载慢

**Comment by Yuppiezero** [comment]
在根目录 新建记事本 取名 .npmrc  然后 复制粘贴
`
electron_mirror=https://npm.taobao.org/mirrors/electron/
chromedriver_cdnurl=https://npm.taobao.org/mirrors/chromedriver`

就这样就好了 ，然后删掉node 包 从新 npm i  百试百灵

**Comment by zhouyangit** [comment]
[解决Electron安装很慢的办法
](https://juejin.im/post/6855526489904349198)
100%可以解决

**Comment by lopo12123** [comment]
你好，我想请问一下解决了吗，我也遇到了这个问题但是楼上两位说的方法还是不行

**Comment by nornagon** [comment]
Unfortunately, we can't fix these network issues. We're not responsible for the taobao npm mirrors.
