### ISSUE TITLE
Twitter does not load inside Webview

### ISSUE THREAD

**Issue by zikosichi** [electron/electron#25421]
### Issue Details

Twitter does not load inside Webview anymore.

It's broken in 9+ versions

![image](https://user-images.githubusercontent.com/16005795/92921576-9005d700-f434-11ea-93e4-63376eb4ca9b.png)
![image](https://user-images.githubusercontent.com/16005795/92921592-97c57b80-f434-11ea-89af-90d843cb28a9.png)

Even though if I load twitter directly into BrowserWindow it works:
![image](https://user-images.githubusercontent.com/16005795/92921646-bcb9ee80-f434-11ea-85db-b8ddef64c0b6.png)

* **Electron Version:**
  9.0.0 +

### Expected Behavior
Twitter should load inside the webview

### Actual Behavior
Twitter does not load in webview. There is no error, neither in root renderer nor in Twitter devtools.

### To Reproduce
Just this:
<webview src="https://www.twitter.com/"></webview>

**Comment by agata** [comment]
@zikosichi 

As a workaround, you may be able to show Twitter by setting allowRendererProcessReuse to false. I still don't understand why this is happening.

https://www.electronjs.org/docs/api/app#appallowrendererprocessreuse

Are the following comments relevant to this issue?

https://github.com/electron/electron/issues/18397#issuecomment-687894189

**Comment by zikosichi** [comment]
@agata,

Huge thanks for the answer. Hunting this issue already 2 days :))

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 7 days if the above is not addressed.

**Comment by nornagon** [comment]
I can repro this with the following gist: https://gist.github.com/753eb9029696cb879fcc08be95b95b6c

Bisected to https://github.com/electron/electron/compare/v9.0.0-beta.10...v9.0.0-beta.12

**Comment by botzill** [comment]
Having the same issue.

**Comment by praneetrohida** [comment]
Facing the same issue. The allowRendererProcessReuse workaround doesn't work for me

**Comment by nornagon** [comment]
I'm still not sure what's going on here, but here's a possible hint: when I inspect the twitter.com web contents (using `--remote-debugging-port=9222` and `about:inspect`), I find that `document.documentElement.getBoundingClientRect()` reports that the width and the height of the embedded document are both 0. So perhaps a size isn't getting properly passed somewhere?

**Comment by holmberd** [comment]
The only changes I can see related to webContents in your bisect are the ThreadPool changes.
- https://github.com/electron/electron/compare/v9.0.0-beta.10...v9.0.0-beta.12#diff-dfc7167e9726f5a243731cf073be2c33R1968
- https://github.com/electron/electron/compare/v9.0.0-beta.10...v9.0.0-beta.12#diff-dfc7167e9726f5a243731cf073be2c33R1968

`allowRendererProcessReuse=false` resolves it on one of my machines but not the other.

**Comment by nornagon** [comment]
@holmberd my suspicion is that the chromium roll is responsible for this change in behavior.

**Comment by holmberd** [comment]
@nornagon Ok. I ran the gist from your other issue [thread](https://github.com/electron/electron/issues/25469) and it seems quite random, but once the crash happens it keeps happening.

**Comment by codebytere** [comment]
Closing in favor of https://github.com/electron/electron/issues/25469
