### ISSUE TITLE
Invalid Electron Application Architecture documentation

### ISSUE THREAD

**Issue by constup** [electron/electron#25443]
Page: Electron Application Architecture
Repo link: https://github.com/electron/electron/blob/master/docs/tutorial/application-architecture.md
Section: Using Electron APIs (https://github.com/electron/electron/blob/master/docs/tutorial/application-architecture.md#using-electron-apis)

The section describes how to exchange information between main and renderer process with the following piece of code:

```javascript
// In the renderer process:
const { ipcRenderer } = require('electron')
```

However, NodeJS has been disabled by default in the renderer process and if you put `require` in it, the following error will show: `Uncaught ReferenceError: require is not defined at renderer.js`.

The whole section is, thus, useless and only adds confusion, especially for new Electron users.

**Comment by vladimiry** [comment]
> const { ipcRenderer } = require('electron')

This needs to be done in a preload script which runs in a renderer process. Then you expose only a minimal/limited API to the pure web process preferably having contextIsolation flag enabled in combination with https://www.electronjs.org/docs/api/context-bridge

**Comment by codebytere** [comment]
The above is correct - our documentation is not incorrect in this instance.
