### ISSUE TITLE
"session-created" event is emitted with a weird Event-Session hybrid object

### ISSUE THREAD

**Issue by nornagon** [electron/electron#25457]
Electron version: v10.1.1
Not present in v9.x, v11.x, v12.x

To repro:

```
app.on('session-created', (session) => {
  console.log('session.preventDefault???', session.preventDefault) // prints: [Function: preventDefault]
  session.loadExtension('') // segfaults
})
```

**Comment by nornagon** [comment]
Introduced here: #23569
Fixed here: #24651

**Comment by ChALkeR** [comment]
> Fixed here

That seems to be an old PR?
This still happens on 10.1.3.

**Comment by nornagon** [comment]
https://github.com/electron/electron/commit/7ae4b2b5597430b163229887aa8cb1999cf5bf9f fixes this in 10.x
