### ISSUE TITLE
Attempting to mock a BrowserWindow object results in 'TypeError: _electronApp.browserWindow is not a constructor'

### ISSUE THREAD

**Issue by tecknetdev** [electron/electron#25451]
Preflight Checklist
 I have read the Contributing Guidelines for this project.
 I agree to follow the Code of Conduct that this project adheres to.
 I have searched the issue tracker for an issue that matches the one I want to file, without success.

Issue Details
Electron Version: 9.3
Operating System: Windows 10 Pro
Last Known Working Electron version: unknown

To Reproduce
Within test file named 'Main.test.ts'
```
import { BrowserWindow } from 'electron';
const mockBroswerWindow = new BrowserWindow();
```

Expected Behavior
A new browser window to be instantiated

Actual Behavior
 The following error is presented: TypeError: _electron.BrowserWindow is not a constructor

Additional Information
The test file is along side the main entry point to the electron app. Both are typescript files using Jest framework.

**Comment by MarshallOfSound** [comment]
This sounds like a bug in jests auto-mock rather than an issue with electron itself

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
