### ISSUE TITLE
TouchBar: emoji button appears and cannot be removed

### ISSUE THREAD

**Issue by bpasero** [electron/electron#25465]
### Issue Details

* **Electron Version:**
  * `9.x`
* **Operating System:**
  * `macOS 10.15.x`
* **Last Known Working Electron version:**
  * `7.x`

### Expected Behavior
All touchbar buttons can be controlled by the app.

### Actual Behavior
An emoji picker appears on the touchbar that cannot be removed taking valuable space.

### To Reproduce
Start Electron Fiddle on a macBook with touchbar.

**Comment by bpasero** [comment]
I just verified that this emoji button does not appear with Electron 7. It seems to be showing up for any `<input type="textarea">` element.

**Comment by codebytere** [comment]
@bpasero looks like that happens here: https://source.chromium.org/chromium/chromium/src/+/master:content/app_shim_remote_cocoa/render_widget_host_view_cocoa.mm;l=2219-2238?q=emoji%20touchbar&ss=chromium

I'll try to figure out how to get rid of it or make it opt-in 🤔

**Comment by bpasero** [comment]
Thanks a lot for the prompt PR!

**Comment by deepak1556** [comment]
This has been handled in our fork as a patch to bring back https://github.com/microsoft/vscode/issues/106541#issuecomment-693433419, hence closing.
