### ISSUE TITLE
process.execPath is undefined

### ISSUE THREAD

**Issue by trusktr** [electron/electron#25460]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * `process.versions`:
  ```
  ares: "1.16.0"
  brotli: "1.0.7"
  chrome: "85.0.4183.93"
  electron: "10.1.1"
  http_parser: "2.9.3"
  icu: "67.1"
  llhttp: "2.0.4"
  modules: "82"
  napi: "5"
  nghttp2: "1.41.0"
  node: "12.16.3"
  openssl: "1.1.0"
  unicode: "13.0"
  uv: "1.34.2"
  v8: "8.5.210.20-electron.0"
  zlib: "1.2.11"
  ```
* **Operating System:**
  * Manjaro Linux
* **Last Known Working Electron version:**
  * 4 (upgraded a project from v4 to v10 today)

### Expected Behavior

`process.execPath`, which is used by a third-party dependency, should not be `undefined`?

### Actual Behavior

It is `undefined`.

### To Reproduce

I don't have a public repro yet, but I installed `zeromq@6.0.0-beta.6`. When I run my Electron app, the `zeromq` package tries to read `process.execPath` and the value is `undefined`.

### Screenshots

Hovering on `process.execPath` in devtools while the code is paused on the uncaught exception show the value is `undefined`:

![Screenshot from 2020-09-14 14-55-18](https://user-images.githubusercontent.com/297678/93142199-65b55300-f69a-11ea-9fac-61ec6f37a738.png)

**Comment by trusktr** [comment]
Ah, nevermind, it was because the module was being handled by Webpack, and it needed to be set to "external" so that it would not be bundled, and thus would be able to import and use native Node APIs.

**Comment by Fsunroo** [comment]
Same problem here, 
trying to use `browserify` to bundle `ftdi-js`. problem is process.execPath returning undefined. how did you solve the problem to get the path when the env is not node?
