### ISSUE TITLE
Error: Error invoking remote method 'ELECTRON_GUEST_VIEW_MANAGER_CALL': Error:  (-3)

### ISSUE THREAD

**Issue by nikitaulshin** [electron/electron#25467]
Hello!

I keep getting errors like the one in the title. But today something strange happened - webview doesn't load the link I've provided. 

I'm using react and my webview looks like this:

      <webview
        className={`profile-webview-${profile.id}`}
        data-testid={`profile-webview-${profile.id}`}
        src={link}
        enableremotemodule
      />

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.2.1
* **Operating System:**
  * macOS 10.15.6
* **Last Known Working Electron version:**
  * None

### Expected Behavior
No error

### Actual Behavior
Keep getting Error: Error invoking remote method 'ELECTRON_GUEST_VIEW_MANAGER_CALL': Error:  (-3) loading 'https://twitter.com/kittypurrzog'

### To Reproduce
Just navigate to the twitter frm

**Comment by codebytere** [comment]
Duplicate https://github.com/electron/electron/issues/25421

**Comment by nornagon** [comment]
I'm not sure this is a duplicate? The fiddle in https://github.com/electron/electron/issues/25421#issuecomment-692327691 doesn't produce any error messages.

**Comment by nornagon** [comment]
ah, I see, -3 is ERR_ABORTED so maybe that's a red herring and this is in fact the same as #25421.
