### ISSUE TITLE
Enable deletion of cache

### ISSUE THREAD

**Issue by reZach** [electron/electron#25480]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

I'd like to be able to delete cached files my app generates in `%APPDATA%`. These files continue to grow and I'd like a way to reset the memory footprint of the app.

### Proposed Solution

_Ideally_, there could be an API off of `app` that could clear the cache, ie `app.clearCache()`. Other properties that offer this functionality may also be ideal locations for the api.

### Alternatives Considered

This _sometimes_ works, and is only Windows-specific so it isn't a full solution.
```javascript
const { spawn } = require("child_process");

...

app.on("quit", () => {
  const folder = path.join(app.getPath("appData"), app.name);
  const cmd = `pushd "${folder}" && (rd /s /q "${folder}" 2>nul & popd)`;
  const process = spawn(cmd, { shell: true, stdio: "ignore", detached: true });
  process.unref();
});
```

**Comment by MarshallOfSound** [comment]
This already exists.  session.clearStorageData

https://www.electronjs.org/docs/api/session#sesclearstoragedataoptions

**Comment by reZach** [comment]
@MarshallOfSound is there an ability for us to request that API be available in the `app` lifecycle methods? As of today we cannot call session.clearStorageData since it returns a promise.

**Comment by reZach** [comment]
**Edit**

You can find code that functionally works here.
```javascript
const { spawn } = require("child_process");

...

app.on("will-quit", async (event) => {
  const folder = path.join(app.getPath("appData"), app.name);

  // Wait 3 seconds, navigate into your app folder and delete all files/folders
  const cmd = `ping localhost -n 3 > nul 2>&1 && pushd "${folder}" && (rd /s /q "${folder}" 2>nul & popd)`;
  
  // shell = true prevents EONENT errors
  // stdio = ignore allows the pipes to continue processing w/o handling command output
  // detached = true allows the command to run once your app is [completely] shut down
  const process = spawn(cmd, { shell: true, stdio: "ignore", detached: true });

  // Prevents the parent process from waiting for the child (this) process to finish
  process.unref();
});
```
