### ISSUE TITLE
electron@8.5.2 is not installing as dependency

### ISSUE THREAD

**Issue by Syed-Umair** [electron/electron#25487]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.5.2
* **Operating System:**
  * Mac OS 10.15.6
* **Last Known Working Electron version:**
  * v8.5.1

### Expected Behavior
npm i electron@8.5.2 should work

### Actual Behavior
It says package doesn't exist but its released https://github.com/electron/electron/releases/tag/v8.5.2

### To Reproduce
npm i electron@8.5.2

### Screenshots
![image](https://user-images.githubusercontent.com/31096792/93330413-6128a000-f83c-11ea-8a44-6950a4c3dbfa.png)

### Additional Information
* npm version: v6.12.0
* it fails even in yarn v1.22.5
* node version: v12.13.0

**Comment by codebytere** [comment]
Just ran Electron Fiddle with 8.5.2 and verified locally so this is likely a network issue and not an issue with the publish.

<img width="689" alt="Screen Shot 2020-09-17 at 4 38 52 PM" src="https://user-images.githubusercontent.com/2036040/93535468-49b4ea00-f904-11ea-9abe-26ea1c7b73a4.png">

**Comment by dpeukert** [comment]
I don't think this is a network issue, as I am also able to reproduce this and 8.5.2 is not in the version list on https://www.npmjs.com/package/electron?activeTab=versions.
![image](https://user-images.githubusercontent.com/3451904/93537746-ab994200-f94c-11ea-92b1-e1ba4b441852.png)

**Comment by sambhare** [comment]
I agree with dpeukert. This is still an open issue. 

https://www.npmjs.com/package/electron/v/8.5.2 returns a 404
while 
https://www.npmjs.com/package/electron/v/8.5.1 works correctly.

**Comment by sambhare** [comment]
@codebytere Any chance of looking into this? Yes, 8.5.2 seems to download correctly using Electron Fiddle but things ares still broken on npmjs.com. For the 8.x.y series, it looks like the last published version is 8.5.1.
