### ISSUE TITLE
ChromeDriver crashes when trying to start the exe program

### ISSUE THREAD

**Issue by kellyshang** [electron/electron#25486]
### Issue Details

* **Electron Version:**
  * Desktop app based on Electron 9.1.2, and UI automation test with chromedriver-v9.1.2-win32-x64
* **Operating System:**
  * Windows Server 2019, os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
* **Last Known Working Electron version:**
  * Desktop app based on Electron 7.1.14, and UI automation test with chromedriver-v7.1.11-win32-x64

### Expected Behavior
Start the desktop app normally

### Actual Behavior
With chromedriver-v9.1.2-win32-x64, when running UI automation test it always failed, below is the error stack related to the ChromeDriver:
(**PS.** I also tried the chromedriver-v9.0.2-win32-x64, it fails frequently but sometimes success, it's weried)
```
[INFO] Running TestSuite
OS is: windows server 2019
The current git commit id is: fd7dca80
Starting ChromeDriver 83.0.4103.94 (8bd9e77c4b04cfdc0d98ce2ab9f1af8e6e457869-refs/heads/master@{#759982}) on port 11376
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.

[TestRunnerListener] Running 31 tests in 'Neuron UI Tests' using 1 threads
....
....
....

[ERROR] com.cryptape.neuron.CreateWalletTest.globalSetup  Time elapsed: 47.775 s  <<< FAILURE!
org.openqa.selenium.WebDriverException: 
unknown error: Chrome failed to start: crashed.
  (unknown error: unable to discover open pages)
  (The process started from chrome location C:\Users\Administrator\AppData\Local/Programs/Neuron/Neuron.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'EC2AMAZ-BU3BFBB', ip: '172.31.34.110', os.name: 'Windows Server 2019', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
	Ordinal0 [0x00007FF711D322E2+3220194]
	Ordinal0 [0x00007FF711BFFD12+1965330]
	Ordinal0 [0x00007FF711AC1B15+662293]
	Ordinal0 [0x00007FF711A3156D+71021]
	Ordinal0 [0x00007FF711A57B70+228208]
	Ordinal0 [0x00007FF711A54DCF+216527]
	Ordinal0 [0x00007FF711A3658F+91535]
	Ordinal0 [0x00007FF711A3774E+96078]
	Ordinal0 [0x00007FF711C18311+2065169]
	GetHandleVerifier [0x00007FF711E80FB9+1233401]
	GetHandleVerifier [0x00007FF711E80D40+1232768]
	GetHandleVerifier [0x00007FF711E8C09C+1278684]
	GetHandleVerifier [0x00007FF711E815C8+1234952]
	Ordinal0 [0x00007FF711C0F00A+2027530]
	Ordinal0 [0x00007FF711C19AF6+2071286]
	Ordinal0 [0x00007FF711C3280D+2172941]
	BaseThreadInitThunk [0x00007FFEB1CE7974+20]
	RtlUserThreadStart [0x00007FFEB3CBA261+33]
```

### To Reproduce
Run UI automation test with chromedriver-v9.1.2-win32-x64 for desktop which based on Electron 9.1.2

**Comment by codebytere** [comment]
@kellyshang please open this issue on https://github.com/electron/chromedriver

**Comment by michael-lam** [comment]
Hi @kellyshang , I would like to ask you which Electron version and ChromeDriver version you are using for running the automation tests for the Neuron app? Thanks in advance

**Comment by kellyshang** [comment]
> Hi @kellyshang , I would like to ask you which Electron version and ChromeDriver version you are using for running the automation tests for the Neuron app? Thanks in advance

As mentioned in the issue, I was using Electron 9.1.2, and UI automation test with chromedriver-v9.1.2-win32-x64 but it always failed, and as in the issue https://github.com/electron/chromedriver/issues/69 mentioned, I also tried the chromedriver-v9.0.2-win32-x64, it fails frequently but sometimes success, it's weried.

**Comment by michael-lam** [comment]
Thank you for your response. Currently, I can run electron 10.1.3 and
chrome 85 and chromedriver 85.
