### ISSUE TITLE
npm install is failing intermittently with 404 error.

### ISSUE THREAD

**Issue by shubhamyelekar** [electron/electron#25481]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  10.1.1
* **Operating System:**
  * Windows Server 2012
* **Last Known Working Electron version:**
  * 5.x

### Expected Behavior

npm install should pass
### Actual Behavior

npm install fails intermittently

### To Reproduce

Run npm i

### Additional Information

When I run npm install, it fails sometimes with the error

```
[exec] > electron@10.1.1 postinstall <path>\node_modules\electron
[exec] > node install.js

HTTPError: Response code 404 (Not Found) for http://<custom_repo>/@electron/get/-/v10.1.1/electron-v10.1.1-win32-ia32.zip

```
I tried the same thing with the default npm repo as well, the URL `https://registry.npmjs.org/@electron/get/-/v10.1.1/electron-v10.1.1-win32-ia32.zip` returns "resource not found error".
`{"code":"ResourceNotFound","message":"/@electron/get/-/v10.1.1/electron-v10.1.1-win32-ia32.zip does not exist"}`

What is the correct URL for this and is there any way to tell @electron/get to download from that URL? Also, it is not clear why this happens intermittently. 70% of the time it works as expected.

Electron v10.1.1
Electron packager v15.0.0

**Comment by codebytere** [comment]
This is not an issue with Electron itself. Please feel free to follow up with `electron-packager` or `@electron/get`
