### ISSUE TITLE
Please consider static builds for Linux prebuilt binaries.

### ISSUE THREAD

**Issue by mceachen** [electron/electron#25495]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v9.3.1, v10.1.1, (all versions, afaik)

* **Operating System:**
  * All linux builds (Ubuntu 18.04 x64, 20.04, ...)
* **Last Known Working Electron version:**
  * (Never? I believe electron has always linked to system libraries on Linux)

### Expected Behavior

Compiling and running with native modules (especially modules with several external library dependencies, like [sharp](https://sharp.pixelplumbing.com/)) should run, with reasonably self-contained dependencies, on different versions of Linux.

### Actual Behavior

Non-compatible versions of system libraries cause run time errors due to missing symbols.

### To Reproduce

Compile a fiddle that requires the current version of `sharp`, and try to run the binary on an older version of linux. You'll see an error from either glibc or libcairo (see https://github.com/lovell/sharp/issues/371 and related errors).

### Additional Information

Thanks, y'all, for all your work on Electron! Open source projects never get enough kudos. :1st_place_medal:

**Comment by nornagon** [comment]
Electron compiles against a system image designed to be broadly compatible: see https://github.com/electron/debian-sysroot-image-creator. Can you compile your native modules against the same sysroot?

**Comment by mceachen** [comment]
I'll try that, thanks.

**Comment by mceachen** [comment]
sry plz send halp

I've cloned that repo, ran `./build/linux/sysroot_scripts/build_and_upload.py` (I have a wonderful collection of ancient .debs now), but... now what? https://www.electronjs.org/?q=sysroot is empty, and https://github.com/electron/electron/issues?q=is%3Aissue+sysroot is similarly unfruitful.

How do I 

1. build out a sysroot using these ancient .debs, and

2. tell node-gyp or electron-rebuild to use this sysroot path?

Thanks!
