### ISSUE TITLE
electron crashes when calling importCertificate

### ISSUE THREAD

**Issue by notNotDaniel** [electron/electron#25506]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
10.1.2
9.3.1
8.5.1

* **Operating System:**
Ubuntu 18.04.05 x64
Also under Ubuntu 16, 14, 12, and Fedora

* **Last Known Working Electron version:**
7.3.3

### Expected Behavior

Calling importCertificate should call the provided function with an error code indicating whether the certificate was successfully imported.

### Actual Behavior
Calling `importCertificate` results in a crash (segmentation fault usually) under linux. This appears to happen across all versions of electron back to 7.x, on Ubuntu 12-18 and Fedora (tested in VirtualBox, and 18 on a bare-metal server). This appears to happen regardless of whether the cert and password are valid (or even specified).

### To Reproduce

```
./node_modules/.bin/electron -i <<< "const {app} = require('electron'); app.importCertificate({},console.log);"
# Segfault
```

### Screenshots

<img width="1433" alt="Screen Shot 2020-09-16 at 3 13 51 PM" src="https://user-images.githubusercontent.com/1534774/93397859-4e5b9e80-f82f-11ea-9597-90156aac2221.png">

**Comment by concreted** [comment]
The fix for this issue appears to be in 10.1.5, but I am still seeing segfaults with Electron 10.1.5 on Ubuntu 20.04 LTS:

```
aric@aric-Surface-Go-2:~/src/photon$ electron -i <<< "const {app} = require('electron'); app.importCertificate({},console.log);"
> const {app} = require('electron'); app.importCertificate({},console.log);
/usr/local/share/.config/yarn/global/node_modules/electron/dist/electron exited with signal SIGSEGV
aric@aric-Surface-Go-2:~/src/photon$ electron --version
v10.1.5
```

Will try some other versions also.

**Comment by concreted** [comment]
v9.3.3 works correctly for me.

**Comment by notNotDaniel** [comment]
After the fix I was still seeing segfaults under some versions if you call importCertificate immediately, however it does work now if you wait until the app is ready.

**Comment by codebytere** [comment]
if y'all are still seeing segfaults and can reproduce them at least somewhat reliably, feel free to open a new issue and ping me :) It's reasonable to wait until the app is ready, but we shouldn't be segfaulting even if you don't!

**Comment by concreted** [comment]
Ah, tried doing it after app ready and it doesn't segfault for me in 10.1.5. Can repro the segfault in 10.1.5 with @notNotDaniel's original repro steps (which do the import immediately) reliably though, will open a new issue. Thanks!
