### ISSUE TITLE
DevTools mostly broken for SharedWorker

### ISSUE THREAD

**Issue by krisdages** [electron/electron#25512]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.1
* **Operating System:**
  * Ubuntu 18.04 x64
* **Last Known Working Electron version:**
  * n/a

### Expected Behavior

On a page with a SharedWorker, after opening the dev tools using:
```
const wc = require("electron").remote.getCurrentWebContents();
wc.inspectSharedWorkerById(wc.getAllSharedWorkers()[0].id);
```
Should be able to set functional breakpoints.
Should be able to see the results of network requests. 

### Actual Behavior

Commands in the devtools console are still functional; I can tell that the execution context is actually the worker, but:
Breakpoints are not hit, nothing appears in the Network Tab, Application Tab is unusable.
Autocomplete in the devtools console does not work (and every keystroke emits one of the error lines below in the terminal)

This output appears in the terminal output:
```
[679136:0916/193016.942813:ERROR:CONSOLE(2143)] "Runtime agent is not enabled", source: devtools://devtools/bundled/sdk/sdk.js (2143)
[679136:0916/193022.030246:ERROR:CONSOLE(2143)] "Runtime agent is not enabled", source: devtools://devtools/bundled/sdk/sdk.js (2143)
[679136:0916/193022.112573:ERROR:CONSOLE(2143)] "Runtime agent is not enabled", source: devtools://devtools/bundled/sdk/sdk.js (2143)
```

### To Reproduce

Will edit shortly to add a Fiddle.

**Comment by Core-commits** [comment]
Yup having same issue while trying to sue the chrome devtools console.
![image](https://user-images.githubusercontent.com/65451703/95000686-4471c380-05c3-11eb-8eda-21f0b935925a.png)

**Comment by masterkidan** [comment]
I am noticing this in e8 as well.

**Comment by chandrachivukula** [comment]
This bug has been reported on E10 and E8 on Win, Mac platforms as well.

**Comment by krisdages** [comment]
Unfortunately still seems to be happening with E12 as well.
