### ISSUE TITLE
MAC App Store Submit issues

### ISSUE THREAD

**Issue by vijayamin83** [electron/electron#25528]
My apple store application for the MAC OS is getting rejected with the following reason:

**Specifically, App still launches to no UI; user is unable to use the app.
Note: No main window appears on launch, menu and icon on Dock only.**

version of the electron: 9.0.5

How I do check the mas or mas-dev version in my local, what are the setting required in the package.json file?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

**Comment by vijayamin83** [comment]
Specifically, App still launches to no UI; user is unable to use the app.
Note: No main window appears on launch, menu and icon on Dock only.

I am getting the above issues in the MAC Store submission. I would like to fix this.
