### ISSUE TITLE
app.quit() and app.exit() do not work on Windows 10

### ISSUE THREAD

**Issue by mehrbat** [electron/electron#25527]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:*10.1.2*
  * 
* **Operating System:*Windows 10 Enterprise*
  * 
* **Last Known Working Electron version:**
  * 

### Expected Behavior

I am trying to stop the second instance under special circumstances (which is not being over the registered protocol/scheme). 
### Actual Behavior

I identify the second instance and call app.quit() but the application window still appears. I tried app.exit() instead with no luck. 
The application continues to open up (new windows). I also notice no calls made to these events after calling quit() or exit():

app.on('window-all-closed', () => {
  console.log('window-all-closed ', process.platform);

});

app.on('before-quit', () => {
  console.log('before-quit');
  mainWindow.close();
});

app.on('activate', () => {
  console.log('activate is called');
  if (mainWindow === null) {
    mainWindow = windowLauncher.createWindow();
  }
});

as the console.log does not write anything in the output. 

### To Reproduce

call app.requestSingleInstanceLock() and try to quit the app if no lock could be gained from the call. 

### Additional Information

here is my code:

`const gotTheLock: boolean = app.requestSingleInstanceLock();
  if (!gotTheLock) {
    console.log('second instance identified, closing the app');
    app.quit();
    console.log('quit() was called');
  }`

**Comment by mehrbat** [comment]
I am so frustrated that I have not found the cause of this issue in two days so far. There are some similar issues but not exactly the same as this on the net, but I do not want to face some brilliant jerks calling this duplicate, so I close it to raise later if I cannot really find a solution.

**Comment by OhPool** [comment]
Did you ever find a solution, as this is still affecting me on Windows 11

**Comment by Nbib** [comment]
No

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
