### ISSUE TITLE
Screensharing through Electron BrowserWindow does not work on Mac or Windows

### ISSUE THREAD

**Issue by emaciel10** [electron/electron#25534]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * version 9.2.1
* **Operating System:**
  * macOS 10.15.6  and Windows 10?
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
If you open https://us02web.zoom.us/wc/join/6515709131 in browser and turn on screen sharing you will notice that it works with no issues. 

I would expect that given the appropriate permissions, opening this same link and screensharing in an Electron BrowserWindow would work.

### Actual Behavior
In an Electron BrowserWindow screen sharing seems to be broken for this same link.
I have tried this even from an application that has the appropriate screen recording permission
![image](https://user-images.githubusercontent.com/11020939/93629700-b4266280-f9b6-11ea-88a8-1c935ead6fc0.png)
And with the following plist
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>
    <key>com.apple.security.device.audio-input</key>
    <true/>
    <key>com.apple.security.device.camera</key>
    <true/>
  </dict>
</plist>
``` 

### To Reproduce

I've created an electron fiddle where I can reproduce the issue:

https://gist.github.com/emaciel10/248364905a771222ba42d07c3f621b9d

I've also created a small reproduction repo with this issue here with steps to reproduce in the readme

https://github.com/emaciel10/zoom-websdk-reproduction

**Comment by emaciel10** [comment]
Just to post an update here, we have upgraded to electron 11.0.3 and this is still an issue

**Comment by MurzNN** [comment]
Same problem is on Linux too.

**Comment by SimonBrandner** [comment]
I think I have some solutions/workarounds [here](https://www.reddit.com/r/electronjs/comments/kazhum/hey_electronjs_i_built_meetinone_a_mac_app_for/gh3gm6h?utm_source=share&utm_medium=web2x&context=3).

**Comment by nornagon** [comment]
This is quite a lot of code under test. Is there any chance you could produce a smaller repro case that only uses the relevant screen-sharing APIs (e.g. `getUserMedia`) and exhibits the issue?

**Comment by iMonZ** [comment]
Anything new here?

**Comment by SimonBrandner** [comment]
Depending on what exactly you're trying to do you can use [#16513 (comment)](https://github.com/electron/electron/issues/16513#issuecomment-602070250) (a polyfill). Or something a little nicer - [#5525](https://github.com/matrix-org/matrix-react-sdk/pull/5525). The second method exposes a method from the `main` process that retrieves the streams to the `render` process using a context bridge.

**Comment by Kemal48** [comment]
Hello![image](https://user-images.githubusercontent.com/47145614/108688924-215b9800-7501-11eb-8e58-1d5091734490.jpeg)

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our [comment above](https://github.com/electron/electron/issues/25534#issuecomment-772085408). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by MurzNN** [comment]
Hey, what is the question that not answered??

**Comment by SimonBrandner** [comment]
> This is quite a lot of code under test. Is there any chance you could produce a smaller repro case that only uses the relevant screen-sharing APIs (e.g. getUserMedia) and exhibits the issue?

@MurzNN, I think it was this

**Comment by tommygaessler** [comment]
Hey @emaciel10 , @MurzNN , @SimonBrandner , @nornagon , @iMonZ , @electron-triage , and everyone wanting to accomplish this with Zoom Meetings/Webinars.

If you use our [Meeting SDK](https://marketplace.zoom.us/docs/sdk/native-sdks/introduction/) for web (instead of the [Zoom Web Client](https://support.zoom.us/hc/en-us/articles/214629443-Getting-started-with-the-Zoom-web-client)) inside an Electron BrowserWindow, screensharing is now supported in [Client View](https://marketplace.zoom.us/docs/sdk/native-sdks/web/client-view/) version [2.9.5](https://www.npmjs.com/package/@zoomus/websdk)+.

https://devforum.zoom.us/t/meeting-sdk-web-2-9-5-release/79555
