### ISSUE TITLE
BrowserWindow transparency/vibrancy is lost after refresh when `app.allowRendererProcessReuse = false`

### ISSUE THREAD

**Issue by KishanBagaria** [electron/electron#25547]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 10.1.1
* **Operating System:** macOS 10.15
* **Last Known Working Electron version:** None

### Actual Behavior
Vibrancy and transparency is lost after refreshing (⌘ R) when `app.allowRendererProcessReuse = false`

This also happens in certain unknown cases without refreshing.

It doesn't happen when `app.allowRendererProcessReuse = true`

### Screencast

![electron-vibrancy-bug](https://user-images.githubusercontent.com/1093313/93717408-46835d80-fb93-11ea-914d-8b6ad1232c5f.gif)

### To Reproduce

`main.js`:
```js
const {app, BrowserWindow} = require('electron')

app.allowRendererProcessReuse = false

function createWindow () {
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    // titleBarStyle: 'hiddenInset',
    // vibrancy: 'sidebar',
    transparent: true,
    backgroundColor: '#00000000',
    webPreferences: {
      nodeIntegration: true
    }
  })
  mainWindow.loadFile('index.html')
}
app.on('ready', createWindow)

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', function () {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow()
  }
})
```

`index.html`:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <style>
      html { -webkit-app-region: drag; height: 100% }
      body { margin: 2em }
    </style>
  </head>
  <body>
    We are using Node.js <script>document.write(process.versions.node)</script>,
    Chromium <script>document.write(process.versions.chrome)</script>,
    and Electron <script>document.write(process.versions.electron)</script>.
  </body>
</html>
```

### Additional Information

Likely related to #8310.

I'd keep `allowRendererProcessReuse = true` but then I encounter #25311

**Comment by TanninOne** [comment]
This also happens on windows in electron 11.4.1

**Comment by waterbang** [comment]
this problem still exists，In macos 13.2.1, if window is to small, will lose the special effect of Gaussian blur

**Comment by codebytere** [comment]
@waterbang `app.allowRendererProcessReuse` was removed as an option in v14, which has not been psupported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines) in quite some time.
