### ISSUE TITLE
how to use 'ExStyle' in electron

### ISSUE THREAD

**Issue by MainSilent** [electron/electron#25565]
I`m making a program like 'on-screen keyboard' so when my program get focus it should return the focus to the previous window, i found out that there is a code in c# that returns the focus to the previous window:

    protected override CreateParams CreateParams
    {
        get
        {
            CreateParams param = base.CreateParams;
            param.ExStyle |= 0x08000000;
            return param;
        }

    }
how can i use this code in my electron program?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
