### ISSUE TITLE
Remote Debugger does not work

### ISSUE THREAD

**Issue by andyboyne** [electron/electron#25570]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v10.1.2
* **Operating System:**
  * Windows 10 (1809)
* **Last Known Working Electron version:**
  * 5.0.1  (have not tested others)

### Expected Behavior
From a console, start electron with a remote-debugging-port.  E.g. 

```
$ electron --remote-debugging-port=9092
```

Now navigate to localhost:9092. We would expect to see devtools remotely attached.

### Actual Behavior
A scrambled mess appears. (output is shortened below)
```��Tmo�0��.......```

### To Reproduce
```
$ electron --remote-debugging-port=9092
```

### Additional Information
If you navigate to `http://localhost:9092/json/list`, and then scrape the URL out of `devtoolsFrontendUrl`, you can access them that way. Although this works, it is somewhat of a chore.

**Comment by nornagon** [comment]
I can reproduce this. Seems to have been introduced in the range https://github.com/electron/electron/compare/v10.0.0-nightly.20200423...v10.0.0-nightly.20200427
