### ISSUE TITLE
Documentation for ELECTRON_GUEST_VIEW_MANAGER_CALL

### ISSUE THREAD

**Issue by mehrbat** [electron/electron#25581]
Is this method documented anywhere on the net? Google search does not return anything. Would you mind directing me please to where I can read more detail about to know what exactly it does. 

I need this to investigate an issue, but that issue looks like a problem with the web site I have wrapped up in Electron, but this method name comes up when Electron throws an error. There are a few other issues already raised similar to mine, so I do not think I should raise a new one.

**Comment by nornagon** [comment]
This is an internal Electron implementation detail, not a public API.
