### ISSUE TITLE
Specific error code for a case with webview.loadURL and a blocking dialog box from navigating away from a page

### ISSUE THREAD

**Issue by mehrbat** [electron/electron#25588]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

If the wrapped webapp confirms leaving the application when a new url is loaded to webview (or even the main window), electron returns Error code -2 at calling ELECTRON_GUEST_VIEW_MANAGER_CALL. 
If there is a better code for this special case, that would save days of investigation for everyone who come across the same problem. 
### Proposed Solution

Specific error code when a modal dialog (like javascript alert or confirm or prompt) has blocked navigating to a new url
### Alternatives Considered

the workaround in my case was to inject a piece of javascript into webview: window.onbeforeunload = null
but it took me a few days of research and investigation
### Additional Information

My operating system is Windows 10
Electron version 10.1.2

**Comment by codebytere** [comment]
This is the feature request template. Please fill out the bug report template.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
