### ISSUE TITLE
npm run start crash with no error details

### ISSUE THREAD

**Issue by avivsalman** [electron/electron#25594]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.3.1
* **Operating System:**
  * Windows 10 (1803)
* **Last Known Working Electron version:**
  * 

### Expected Behavior
run the "uareu-node" library like node command running

### Actual Behavior
[2020-09-23T13_04_02_505Z-debug.log](https://github.com/electron/electron/files/5268307/2020-09-23T13_04_02_505Z-debug.log)

when I am running the command
"npm run start" (electron .) => I got an error with no details, I attached the log

but when I am running "node main.js" it works.

so something with the electron / npm command doesn't work with this node module

**Comment by avivsalman** [comment]
after some testings "uareu-node" library work only in electron 7.X

anyone can help me and tell me why electron crash on version 8.X, 9.X, 10.X?? 

it's very urgent for me, thanks :)

**Comment by MarshallOfSound** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.
