### ISSUE TITLE
Backspacing changes keyboard layout back to english

### ISSUE THREAD

**Issue by VoQZHD** [electron/electron#25614]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v10.1.2
* **Operating System:** 
  * ubuntu (kubuntu)

### Expected Behavior

When I backspace I must remain in the used before language layout
### Actual Behavior

When I press backspace I always get kicked into English layout
### To Reproduce

Write something; backspace; the layout has been set to English
<!--

(apps tested: SimpleNotes; Discord)

**Comment by VerteDinde** [comment]
Hey @VoQZHD, thanks for reporting an issue! Could you please provide a standalone test that a tester could run to reproduce the issue, possibly in Electron Fiddle? This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label until we have a repro case. After you've responded, please @ me in a followup comment. Thanks so much!

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
