### ISSUE TITLE
Window title does not match top panel title on Ubuntu Gnome

### ISSUE THREAD

**Issue by markibanez** [electron/electron#25616]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
v10.1.1
* **Operating System:**
Ubuntu 19
* **Last Known Working Electron version:**
Not applicable

### Expected Behavior
For the app window title to match top panel title 

### Actual Behavior
Titles do not match

### To Reproduce
Set window title to different title than the string in the name field in package.json

### Screenshots

![image](https://user-images.githubusercontent.com/7534847/94106940-05c76500-fe6f-11ea-8bc7-4a5044664329.png)

### Additional Information

I have also tried adding title option in BrowserWindow constructor, as well as calling setTitle method

**Comment by feugy** [comment]
Some additional information:
- the string displayed in Activities bar is the application name.
- it can be changed with [app.setName()](https://www.electronjs.org/docs/api/app#appsetnamename), and default to package.json 's `productName` which itself default to package.json's `name`
- it can not contain accentuated characters: My application is named `Mélodie`, and the outcome is terrible
- it seems to be set in stone, changing it later (when your BrowserWindow will open) doesn't update it.

Considering that both Windows and OSX are always displaying the BrowserWindow's title, it would be great to have the same experience on Linux
