### ISSUE TITLE
Less memory-usage

### ISSUE THREAD

**Issue by Milo123459** [electron/electron#25624]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Less memory usage
### Proposed Solution

N/A
### Alternatives Considered

N/A
### Additional Information

Not sure if electron can do anything about it, but making electron apps with less memory usage would be amazing.

**Comment by codebytere** [comment]
This is a constant work in progress, and we are always working to improve this! However, this is not at present something that should be a standalone issue of this kind.
