### ISSUE TITLE
Media Access Update Event

### ISSUE THREAD

**Issue by Syed-Umair** [electron/electron#25633]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
I would like to know if the application is having the camera and microphone permission all the time when it is running. To do that currently, I am checking every 10 mins by hitting the following API ```systemPreferences.getMediaAccessStatus(mediaType)```

### Proposed Solution
It would be really great to have an event whenever the permission for media access is changed or updated for the electron application. Based on this certain application capabilities can be altered for better user experience.

**Comment by Syed-Umair** [comment]
UseCase: 

Sometimes users accidentally clear permissions for productive electron applications unknowingly since some third party apps ask them to review permissions without giving clarity on why it's using. We get lot of support chats saying the applications are not working. It would be great to have this feature in Electron. I believe it will be useful for lot of applications out there.

**Comment by MarshallOfSound** [comment]
There is no such event provided by the OS, polling that API is probably the best thing you can do
