### ISSUE TITLE
Offscreen transparent window causes immediate app closing and error.

### ISSUE THREAD

**Issue by blackart** [electron/electron#25639]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.3.1 and 10.1.2
* **Operating System:**
  * macOS 10.15.6
* **Last Known Working Electron version:**
  * 8.5.2

### Actual Behavior

**In the 9.3.1 app just closes immediately after the run without some error in a console.** 
![image](https://user-images.githubusercontent.com/1162974/94345345-c1e38400-0057-11eb-8cec-e6f34f672954.png)
But causes MacOs error:
![image](https://user-images.githubusercontent.com/1162974/94345366-e9d2e780-0057-11eb-9691-654cf07ee801.png)
Full error log [here](https://gist.github.com/blackart/efce917c83d6b9fb712686ce517c25fd)

**In the 10.1.2 app closes with console error**
![image](https://user-images.githubusercontent.com/1162974/94345526-1b987e00-0059-11eb-8a39-b723f5259dc9.png)

### To Reproduce
```
const { app, BrowserWindow } = require('electron');

app.disableHardwareAcceleration()

let win

app.whenReady().then(() => {
    win = new BrowserWindow({
        transparent: true,
        webPreferences: {
            offscreen: true
        }
    })

    win.loadURL('http://github.com');
})
```

**Comment by codebytere** [comment]
This no longer happens on all supported versions.
