### ISSUE TITLE
opener is null inside of secondary window when canceling the new-window event and awaiting something before creating the window and setting newGuest

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#25634]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 9, 10
* **Operating System:** Windows 10
* **Last Known Working Electron version:** not sure

### Expected Behavior
I expect that when I open a window via window.open, the opener is accessible from within the window

### Actual Behavior
opener is null

### To Reproduce
1. npm start below script
2. in the devtools of the window, open a window to a page (e.g. https:/google.com)
3. in the devtools of that window, execute `opener`. Observe that it's null.

It happens only when you prevent the initial `new-window` event and then `await` some operation before setting `newGuest` and creating the window.

If you remove the `await`, or move it after creating the window and setting `newGuest`, the problem goes away.

```
(async () => {
  const {app, BrowserWindow} = require('electron');

  await app.whenReady();

  const mainWindow = new BrowserWindow({webPreferences: {nativeWindowOpen: true}});
  await mainWindow.webContents.loadURL("https://google.com");
  mainWindow.webContents.openDevTools();

  mainWindow.webContents.on("new-window", async (e, url, framename, disp, opts) => {
    e.preventDefault();
    await new Promise(r => setTimeout(r, 1000)); // commenting this out solves the problem
    const win = new BrowserWindow(opts);
    e.newGuest = win;
    win.webContents.loadURL(url);
  });

  app.on("browser-window-created", (e, win) => {
    win.webContents.openDevTools({mode: "bottom"});
  });
})();
```

**Comment by MarshallOfSound** [comment]
This is currently expected behavior, as `window.open` is synchronous all handling of that command must be synchronous too.  Setting `event.newGuest` in an async way is not supported, nor will it be.  You'll need to refactor your code to be sync or create the window before your async work is done and put it in a "pending" state.
