### ISSUE TITLE
Unable to install electron on Mac OS

### ISSUE THREAD

**Issue by robjermy** [electron/electron#25630]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.2
* **Operating System:**
  * macOS 10.15.6
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
Executing `npm i -D electron@latest` should install electron

### Actual Behavior
When I attempt to install electron I get the following error:
Error: Generated checksum for "electron-v10.1.2-darwin-x64.zip" did not match expected checksum.

I am behind a company proxy so I have added the certificates to NPM so it does not error. The actual command I end up running is: `NODE_TLS_REJECT_UNAUTHORIZED=0 zsh -c 'npm i -D electron@latest'` to stop node complaining about the self-signed certificates that my company installs.

### To Reproduce
```bash
mkdir testProj
cd testProj
npm init -y
NODE_TLS_REJECT_UNAUTHORIZED=0 zsh -c 'npm i -D electron@latest'
```

### Screenshots
![Screenshot 2020-09-25 at 09 04 02](https://user-images.githubusercontent.com/7982964/94242542-17ac1500-ff0e-11ea-8d25-daf7e2372090.png)

### Additional Information
* **Node Version:**
  * v12.16.3
* **NPM Version:**
  * 6.14.4

I have tried multiple versions of Node and Electron. I've also seen other issues related to sum-checker versions and deleting the checksum file from electron cache. None of those have worked for me.

**Comment by MarshallOfSound** [comment]
Whatever proxy your company is running is modifying the ZIP file that is being downloaded so it doesn't match our required checksums.  You should talk to whoever is running that proxy and figure out what exactly it's changing in-flight
