### ISSUE TITLE
mouse events in 'drag' and 'no-drag' unaligned after 10.1.1

### ISSUE THREAD

**Issue by rafma0** [electron/electron#25649]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  10.1.2
* **Operating System:**
  Windows 10 (2004)
* **Last Known Working Electron version:**
  10.1.0

### Expected Behavior
mouse events aligned to the element

### Actual Behavior
elements with 'drag' and 'no-drag' inside a 'drag' region are 'vertically unaligned' by 8 pixels for mouse hover, click, etc when window is maximized

### To Reproduce
https://gist.github.com/rafma0/e7bc9ad86c17e79b25130b4399d72506
double click any appbar to maximize
move your mouse to the bottom of any button, it wont change color until you go 8 pixels up
you can also click and drag from 8 pixels outside the top of the middle or bottom appbar and it will unmaximize

**Comment by nornagon** [comment]
potentially related to https://github.com/electron/electron/pull/25052. cc @deepak1556
