### ISSUE TITLE
Browser Window becomes unresponsive at some moment

### ISSUE THREAD

**Issue by blackart** [electron/electron#25640]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.5.2
* **Operating System:**
  * macOS 10.15.6 / Windows 10 (1803)

### Actual Behavior

At some moment BrowserWindow of our app becomes unresponsive throws the 'unresponsive' event after 30 seconds or more.

### Additional Information

We have a web application that works fine on a web page in any usual browser but when it loads in the BrowserWindow in the Electron app it makes BrowserWindow unresponsive. It happens for a large number of our users but not for everybody. We don't know how to reproduce it. The Sentry reports don't contain clear information about what is cause hang a window.

![image](https://user-images.githubusercontent.com/1162974/94346572-1a1e8400-0060-11eb-8cea-8f899099819f.png)

Maybe someone faced that problem and can advise something to us?

**Comment by MarshallOfSound** [comment]
The `unresponsive` event is fired when Chromium detects that your webContents is not responding to input messages for > 30 seconds.  That normally means your app is stuck in some kind of infinite loop, unfortunately we can't help you debug that 😄

**Comment by ramaralo** [comment]
@MarshallOfSound 
Is there any way we can configure those 30 seconds?

**Comment by axetroy** [comment]
Are there some ways to extend the time?

For some machines with lower performance, I hope it helps

**Comment by codeingforcoffee** [comment]
@MarshallOfSound 
Is there any way we can configure those 30 seconds? We have lots of lower performance machines... such as win7(no mean)
