### ISSUE TITLE
 Disable Inspection in Production Runtime

### ISSUE THREAD

**Issue by lewisxy** [electron/electron#25651]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Apps build with Electron can be inspected when running with debug flag `--inspect-brk` (tested on MacOS) and debugged by a remote debugger (e.g. `chrome://inspect` in a chrome browser). This allows the users to view and modify the JavaScript source code of the program that they should not.

### Proposed Solution

Add an option to disable command line flag `--inspect` and `--inspect-brk` in production code and remove the corresponding debugging feature in the production runtime of Electron.

**Comment by MarshallOfSound** [comment]
> This allows the users to view and modify the JavaScript source code of the program that they should not.

Debatable 😆  There is no way to protect your app from a physically-local attacker.

[Physically local](https://chromium.googlesource.com/chromium/src/+/master/docs/security/faq.md#Why-arent-physically_local-attacks-in-Chromes-threat-model) and are excluding from the _typical_ threat model for Electron apps.

That said there are [features in flight](https://github.com/electron/electron/pull/24241) that could achieve a certain level of the hardening your are asking for.  Going to close this out though as there is no official plan to "harden" Electron against physically local attacks, any work we do that might benefit that goal is happy coincidence 😄

**Comment by lewisxy** [comment]
> Debatable 😆 There is no way to protect your app from a physically-local attacker.

I agree with your point here. But I am more talking about the issue from a developer's perspective rather than the user. You see, developer cares about their intellectual work, and don't want unauthorized people to tamper with their source code. The existence of `--inspect` in production build of Electron is almost equivalent of having `-g` in your `CFLAGS` and not strip the debug symbol in your binary before releasing them. I bet no company would want to do that in reality.

Hope you can reconsider the idea. I am sure private companies would implement something like that to protect their intellectual property if they were to use Electron as a development framework. It would be better and more convenient for everyone if it is supported officially.

**Comment by nornagon** [comment]
Your JS is just as accessible as any JS on the Web. Standard JS obfuscation techniques apply, along with their caveats.

**Comment by phamminhvu** [comment]
@MarshallOfSound  https://github.com/electron/electron/pull/24241
We are using electron version 12.0.1 But I am really confuse how to use fuses inside the application follow the instruction here: 
https://www.electronjs.org/docs/tutorial/fuses
require('@electron/fuses').flipFuses(
  // Path to electron
  require('electron'),
  // Fuses to flip
  {
    runAsNode: false
  }
)

Because It does not available yet in electron modules.
or I am mis-understanding.!
Please guide me how to use fuse to avoid the debugger to the electron app.

Thank you
