### ISSUE TITLE
Detached dev tools always on primary display

### ISSUE THREAD

**Issue by OlsonDev** [electron/electron#2565]
So, I opened #2263 and it was closed with atom/brightray#131. My issue is with commit atom/brightray@507bc4886a48064bbc4d87ac8d7f95b638935d47.

Every time I open my app, the dev tools open in front of my app. Why? Because I almost always drag it to one of my other displays. This slows me down because sometimes I don't need the dev tools to see if my recent code change was effective; I just want to open my app, click a button or something, close my app, modify code, repeat.

Prior to these commits, it felt like the dev tools were opening outside the bounds of all my displays. I do have an irregular setup though:

![image](https://cloud.githubusercontent.com/assets/308072/9428706/0ce02d38-497d-11e5-9a65-7c647b6b849b.png)

The yellow arrow points in the direction of where the dev tools used to open. It seemed like it was offscreen in that direction. I generally drag the dev tools window to screen 3, FWIW.

`nwjs` [allows the dev tools window to be manipulated](https://github.com/nwjs/nw.js/wiki/Window#windowshowdevtoolsid--iframe-headless) just like any other window. I don't *think* this is possible with Electron but it would alleviate my issues because then I could just say "Go to screen 3 & maximize, thanks"

**Comment by etiktin** [comment]
I'm not sure if this will work but you can try to do the following:
- Get the devtools webcontents using `BrowserWindow.devToolsWebContents`.
- Use `BrowserWindow.fromWebContents(webContents)` to get the devtools BrowserWindow from the webcontents you got in the previous stage.
- Use `BrowserWindow.setPosition(x, y)` to move the window.

**Comment by OlsonDev** [comment]
Thanks, but... it didn't work. I had to wrap it in a timeout to get `devToolsWebContents` to not be `undefined`. But then `BrowserWindow.fromWebContents(webContents)` returned `undefined`.

**Comment by etiktin** [comment]
Bummer. It would be cool if we could treat devtools like any other window. I wonder what is preventing that.

**Comment by zcbenz** [comment]
Currently if devtools window is not within the same display of the inspected window, Electron will move it to. I think removing this "feature" should be able to fix it for you?

> Bummer. It would be cool if we could treat devtools like any other window. I wonder what is preventing that.

The devtools in Electron supports being attached to window, so we can not simply implement it as a BrowserWindow.

**Comment by OlsonDev** [comment]
I believe it should fix it for me, I'm just worried about a regression to pre- #2263 behavior when the dev tools were offscreen.

**Comment by etiktin** [comment]
> The devtools in Electron supports being attached to window, so we can not simply implement it as a BrowserWindow.

If the devtools are attached, I would expect `BrowserWindow.fromWebContents(webContents)` to return the `BrowserWindow` it's attached to. If it's detached, I would expect it to return the window in which it's running.
