### ISSUE TITLE
electron requires an unexpected NODE_MODULE_VERSION, 82 instead of 83

### ISSUE THREAD

**Issue by lxcodev** [electron/electron#25650]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
When I integrate llvm-node with the electron to my application, it always reports an error caused by different NODE_MODULE_VERSION. The detailed message cab be found below.
The llvm-node is a project wraps llvm as a native node module. Since the public version llvm-node is outdated, I cloned a local repo and fixed several compatible issues. And then installed the module locally, the error reported when the app running.
I noticed in the official release the module version is 83 instead of 82(the previous version is 79), so it looks weird electron requires NODE_MODULE_VERSION 82.
https://nodejs.org/en/download/releases/
I also tried some solutions from the internet, like clean-reinstall, or using electron-rebuild, but all of them not working.

Any suggestion?

* **Electron Version:**
I tried stable release and beta release, v10.1.2, v9.3.1, and v11.0.
on v9.3.1, the required NODE_MODULE_VERSION is 72.
 
* **Operating System:**
  macOS 10.13.6
* **Last Known Working Electron version:**
  

### Expected Behavior
Run llvm successfully.

### Actual Behavior
Get error in log
**Uncaught Error: The module '/path_to_my_project/build/llvm-node.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 82. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).**

**Comment by nornagon** [comment]
https://www.electronjs.org/docs/tutorial/using-native-node-modules

**Comment by Githubber2021** [comment]
Hi, I just did run into this issue. Does that mean this is fixed in a nightly build? At the same time, I didn't do any updates of electron, why did it just pop up on my machine?
