### ISSUE TITLE
netLog not available in electron@10

### ISSUE THREAD

**Issue by timdp** [electron/electron#25669]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.2
* **Operating System:**
  * Ubuntu 20.04.1
* **Last Known Working Electron version:**
  * 9.3.1

I'm using `netLog` in my main process. Per [the docs](https://www.electronjs.org/docs/api/net-log), I'm not accessing its methods until after `app.whenReady()` has resolved.

However, after upgrading from v9.3.1 to v10.1.2, `netLog.startLogging` and `netLog.stopLogging` are always undefined.

Interestingly, v11.0.0-beta.8 doesn't have this issue, so it's only on v10.x.

I looked for `netLog`-related issues and PRs, but everything I could find seemed to be from before work started on v10.x. The most recent invasive change to `netLog` appears to be #22732, so that's the best I've got.

### To Reproduce

```js
const { app, netLog } = require('electron')

;(async () => {
  await app.whenReady()
  console.log(netLog.startLogging, netLog.stopLogging)
  process.exit()
})()
```

v9.3.1: `[Function] [Function]`

v10.1.2: `undefined undefined`

v11.0.0-beta.8: `[AsyncFunction: startLogging] [AsyncFunction: stopLogging]`

**Comment by nornagon** [comment]
Bisected to https://github.com/electron/electron/compare/v10.0.0-nightly.20200318...v10.0.0-nightly.20200320

Seems to have been fixed in this range https://github.com/electron/electron/compare/v11.0.0-nightly.20200619...v11.0.0-nightly.20200701

**Comment by nornagon** [comment]
You should be able to work around this by using `session.defaultSession.netLog.{start,stop}Logging`.

**Comment by timdp** [comment]
Thanks for the quick response!

Confirming that the workaround is effective.

**Comment by codebytere** [comment]
Think it might be this: https://github.com/electron/electron/commit/b87b5011615d17e0dcec5c71832d7b3d1d2ebc72
