### ISSUE TITLE
Non modal dialog box / message box is created on linux

### ISSUE THREAD

**Issue by dimdin** [electron/electron#2566]
I am calling dialog. showOpenDialog or dialog.showMessageBox providing remote.getCurrentWindow() as first parameter (browserWindow).
On Mac OS X and on Windows I am getting modal windows, but on Linux I am getting a modeless window (I can focus back on the browser window while the message box / open dialog is open).
I am expecting a modal dialog box on linux also.

**Comment by hokein** [comment]
Indeed, the Electron's dialog window is a modal window already, but user can still interact with the parent window, e.g. changing position, changing window's size.

I believe it's a bug of Chromium. I verified that we can still interact with Chromium's window with system print dialog opens on Linux, while on OS X we can't.

A related bug on Chromium: https://code.google.com/p/chromium/issues/detail?id=286441
