### ISSUE TITLE
why i can't use link.import in electron 10.1.2

### ISSUE THREAD

**Issue by fw23t9** [electron/electron#25664]
in my js code i use 

const links = document.querySelectorAll('link[rel="import"]')

// Import and add each page to the DOM
Array.prototype.forEach.call(links, (link) => {
  let template = link.import.querySelector('.task-template')
  let clone = document.importNode(template.content, true)

like this to import my htmls. 
it could work when electron@9.3.1, but it can't work in electron@10.1.2, how could i load my htmls now

console tells me the link.import is undefined

**Comment by nornagon** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by fw23t9** [comment]
thx for your reply

I made an app with many tabs, each tab has a unique html like tab-A.html, and the app could load special tabs in main process.
In the end of **index.html** I use `<script>require('./tabs/imports')</script>`

and in **imports.js** codes is like this
```
const links = document.querySelectorAll('link[rel="import"]')

// Import and add each page to the DOM
Array.prototype.forEach.call(links, (link) => {
  let template = link.import.querySelector('.task-template')
  let clone = document.importNode(template.content, true)
  
  if (link.href.match('tab-A.html')) {
    document.querySelector('.tab-A-content').appendChild(clone)
  } 
}
```

and **tab-A.html**
```
<template class="task-template">
    <section id="tab_A" class="section tab-A">
        <!-- A -->
        <div class = "tab-pane modal-content panel panel-default" id = "A">
            <div class = "panel-heading">
                <h4 class = "panel-title">
                    TODO
                </h4>
            </div>
            <div class = "panel-body">
                AAA                  
            </div>                        
        </div>
    </section>
</template>

```

My codes is like above

I learned that HTML import is obsolete since Google Chrome 73, is this the reason? 
And how can I load tabs dynamically under electron@10.1.2

**Comment by volodymyrmakarchuk-okta** [comment]
@fw23t9   link.import works for me with electron ^7.2.4 and not working In ^10.1.3, seems that is a bug or something  that not supported by the new electron version

**Comment by nornagon** [comment]
Closing this issue as the issue template still has not been filled out. Please open a new issue at https://github.com/electron/electron/issues/new?template=Bug_report.md and make sure to fill out the template.
