### ISSUE TITLE
MediaStream streaming desktop window starts to freeze when other window is on top of it

### ISSUE THREAD

**Issue by iGoodie** [electron/electron#25673]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v10.1.2
* **Operating System:**
  * Windows 10, version 2004
* **Last Known Working Electron version:**
  * *Didn't try on other versions*

I am currently trying to develop a program to capture a desktop window and display a mini controller window on top of it.
Since I have 2 windows piled up, I need MediaRecorder to record only one window. Everything is fine, I can capture a window by querying with the `chromeMediaSourceId` of that window. However, whenever that second window is on top of that main window, FPS of the MediaSource representing the main window starts to decrease.

### Expected Behavior
MediaSource representing a desktop window not to decrease fps when another window is on top of it.

### Actual Behavior
The FPS of the MediaStream went from ~40-50 to ~15-20 immediately once another window collide with the main window

### To Reproduce
1. Open up a Video Player and play a video that is at least in 60 FPS (Need high FPS for testing purposes)
2. On your Renderer process, get media stream of that Video Player window (By following the steps shown at https://www.electronjs.org/docs/api/desktop-capturer)
3. Store the stream queried on Step 2 within a HTMLVideoElement.
4. Run the Electron app and check out the HTMLVideoElement node displaying the video at 60 FPS
5. Now put another window on top of it by moving the window.
6. And see how FPS decreases on the HTMLVideoElement node.

### Additional Information
I noticed that, this issue only occurs when the main screen is Maximized or in Fullscreen mode

**Comment by AndyQsmart** [comment]
Do you solve the problem?

**Comment by iGoodie** [comment]
> Do you solve the problem?

Nope the issue is still relevent when the MediaStream is targetted to a Fullscreen or Maximized window

**Comment by qian-jiang** [comment]
Have you found a solution to this problem?

> > 你解决问题了吗？
> 
> 不，当 MediaStream 定位到全屏或最大化窗口时，该问题仍然相关
Have you found a solution to this problem?
