### ISSUE TITLE
dialog.showOpenDialog can not show up in the front window in  some windows 7 operating systems

### ISSUE THREAD

**Issue by Cqy11223344** [electron/electron#25676]
Issue Details

dialog.showOpenDialog(win, { properties: ['openFile', 'multiSelections'] })

In some windows 7 operating systems, the file dialog box cannot be displayed normally in the front window, which seems to be minimized. I have to click once to show up in the front window.

Electron Version:
  10.1.2
Operating System:
 Windows 7

**Comment by VerteDinde** [comment]
Hey @Cqy11223344, thanks for reporting an issue! Could you please provide a standalone test that a tester could run to reproduce the issue, possibly in Electron Fiddle? This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label until we have a repro case. After you've responded, please @ me in a followup comment. Thanks so much!

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
