### ISSUE TITLE
Add additional information about `contextIsolation` in the warning regarding `worldSafeExecuteJavaScript`

### ISSUE THREAD

**Issue by CynicalBusiness** [electron/electron#25677]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
When using `webFrame.executeJavaScript` without `worldSafeExecuteJavaScript`, the following warning appears:
```
(electron) Security Warning: webFrame.executeJavaScript was called without worldSafeExecuteJavaScript enabled. This is considered unsafe. worldSafeExecuteJavaScript will be enabled by default in Electron 12.
```

This led me to add `worldSafeExecuteJavaScript: true` to my `webPreferences`, however, the warning persisted anyway. So, I believed it was a bug for some time before eventually managing to locate #24950, where it is pointed out that `contextIsolation` must also be used, per docs.

However, I actually need `contextIsolation` off because I need `nodeIntegration: true`. Per #11608, this must be `false` or the node APIs, namely `require`, don't make it to the main context. My scripts are all locally loaded and need the node and electron APIs to function.

### Proposed Solution
Add some mention of also needing `contextIsolation` in the warning and perhaps hide the warning completely when explicitly using `contextIsloation: false`.

### Additional Information
I would've just PR'ed myself, but unsure of exactly what to change the warning to and/or when not to display it.

**Comment by maleeeei** [comment]
me too with the version 10.1.2

**Comment by alchaplinsky** [comment]
@CynicalBusiness Using `nodeIntegration: true` is not recommended, see https://www.electronjs.org/docs/tutorial/security#2-do-not-enable-nodejs-integration-for-remote-content 
If you need to use node and electron API, use the preload script as described in the link above.

**Comment by nornagon** [comment]
Possibly related: #25692

**Comment by CynicalBusiness** [comment]
> Using `nodeIntegration: true` is not recommended, see https://www.electronjs.org/docs/tutorial/security#2-do-not-enable-nodejs-integration-for-remote-content
> If you need to use node and electron API, use the preload script as described in the link above.

@alchaplinsky This `BrowserWindow` does not use any remote content at all, not even images; everything is entirely served locally and it has a simple `default-src: self;` CSP to help enforce that. The link you gave describes a use case with *remote* content.

Is a preload script the desired way to do this for local-only content? It seems unnecessary.

**Comment by MarshallOfSound** [comment]
`worldSafeExecuteJavaScript` has long since been removed from Electron as it was only temporary during a deprecation process
