### ISSUE TITLE
How to distinguish between page closing and dock exit in macOS

### ISSUE THREAD

**Issue by southorange1228** [electron/electron#25680]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  * 9.1.2 
* **Operating System:** 
  *  macOS 
* **Last Known Working Electron version:**
  * 

### Actual Behavior

when page closing or dock quit option has been called , elecctron will use same hooks ( BrowserWindow.on('close') ).
How to distinguish between page closing and dock exit in macOS?

**Comment by oltreseba** [comment]
Maybe this event and the two previous: https://www.electronjs.org/docs/api/app#event-quit ?

**Comment by southorange1228** [comment]
![image](https://user-images.githubusercontent.com/32590310/94632922-6b4ba380-02fe-11eb-8626-b0a273f4d63a.png)
![image](https://user-images.githubusercontent.com/32590310/94632936-769ecf00-02fe-11eb-8ed6-c011b2e683c8.png)

they use the same hooks (` BrowserWindow.on('close') `).and i try to use ` app.on('quit') `. it doesnot work.

**Comment by southorange1228** [comment]
Is there any solution？ @oltreseba

**Comment by oltreseba** [comment]
When the user closes the app from the dock the app.on('quit') event is triggered. (and i guess also the close event of each windows)

When the user closes a window, only the close event of that window is triggered, and not the app quit. In fact the app stays open.

**Comment by zcbenz** [comment]
You can use the `before-quit` event to prevent the default behavior of dock exit, and then use custom logics to close windows. There is no direct way to distinguish why the window is closed.
https://www.electronjs.org/docs/api/app#event-before-quit

**Comment by southorange1228** [comment]
> When the user closes the app from the dock the app.on('quit') event is triggered. (and i guess also the close event of each windows)
> 
> When the user closes a window, only the close event of that window is triggered, and not the app quit. In fact the app stays open.

when all windows are closed, app.on('quit') event is triggered. And it is triggered where dock exit.

**Comment by southorange1228** [comment]
> You can use the `before-quit` event to prevent the default behavior of dock exit, and then use custom logics to close windows. There is no direct way to distinguish why the window is closed.
> https://www.electronjs.org/docs/api/app#event-before-quit

but the application window close can't be customized, so i don't know how to use custom logics to close windows.this button can be customized?
![image](https://user-images.githubusercontent.com/32590310/96202636-4ad44800-0f92-11eb-99f0-1bef99c558a7.png)

**Comment by LinuxSuRen** [comment]
Using `before-quit` can fix my problem.
