### ISSUE TITLE
Why same Electron app that works perfectly in Linux crashes in Windows 10 (after a reload) ?

### ISSUE THREAD

**Issue by wasimaftab** [electron/electron#25696]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.2
* **Operating System:**
  * Windows 10 Enterprise (1909) 
* **Last Known Working Electron version:**
  * none

### Expected Behavior
I should be able to see the first line of the uploaded file in the browser's console every time I upload the file.

### Actual Behavior
Once I reload the app, I do not see the first line of the uploaded file in the browser's console in the subsequent uploads.

### To Reproduce
1. Download the app folder from the following ftp link:
ftp://ftp.lrz.de/transfer/bug/test_Electron/
2. Install the dependencies as:
`npm install`
3. launch the app using the following command:
`npm start`
4. click **Upload File** button and upload the file **sample.txt** from **test_Electron/assets** folder.
6. In the browser's console you should see the following output:
    `First line of the file: abc` (highlighted using red rectangle in the first screenshot)
7. Now reload the app by pressing `CTRL + SHIFT + R`
8. click **Upload File** button and upload the file **sample.txt** from **test_Electron/assets** folder.
9. you will **NOT** see  `First line of the file: abc` in the browser's console (see the second screenshot)

### Screenshots
* **Expected Behavior**
![electron_win_file_upload_expected](https://user-images.githubusercontent.com/29901809/94623819-5e569200-02b5-11eb-89ad-f777f1969811.PNG)

* **Behavior After Reload**
![electron_win_file_upload_bad](https://user-images.githubusercontent.com/29901809/94623917-95c53e80-02b5-11eb-8f4d-13e4bb6e0e35.PNG)

### Additional Information
The same app (with exactly the same electron version) works perfectly when I run it on 64-bit Ubuntu 18.04 and 20.04

**Comment by VerteDinde** [comment]
Hey @wasimaftab, thanks for reporting this issue! Two questions for you, so we can start to triage this:

1) I saw that you included a link to your full app on FTP - is it possible for you to repro a simple version of this using Electron Fiddle?: https://www.electronjs.org/fiddle This may help us narrow down the problem.
2) I notice you have Electron 12.16.3 as your version. Electron 11 is currently in beta, with Electron 10 being our latest stable version - can you confirm which version of Electron you're using?

Thanks!

**Comment by wasimaftab** [comment]
Hi @VerteDinde 
1. Here is the gist https://gist.github.com/wasimaftab/6bd20e0ec4540ddc855d2744115bdb42
2. The electron version I used was 10.1.2, my apologies for mentioning the wrong version earlier. I have now corrected it in the issue.

Thanks for your time!

> Hey @wasimaftab, thanks for reporting this issue! Two questions for you, so we can start to triage this:
> 
> 1. I saw that you included a link to your full app on FTP - is it possible for you to repro a simple version of this using Electron Fiddle?: https://www.electronjs.org/fiddle This may help us narrow down the problem.
> 2. I notice you have Electron 12.16.3 as your version. Electron 11 is currently in beta, with Electron 10 being our latest stable version - can you confirm which version of Electron you're using?
> 
> Thanks!

**Comment by wasimaftab** [comment]
Hi @VerteDinde 
I have provided the electron fiddle gist and corrected the electron version in the issue but, the issue still shows **blocked/need-info** label. Could you kindly look into this? 
Thank you

**Comment by marc2332** [comment]
This is probably related to https://github.com/electron/electron/issues/22119

**Comment by codebytere** [comment]
Closing as duplicate to https://github.com/electron/electron/issues/22119 - the underlying issue is the same
