### ISSUE TITLE
Installation stuck at node install.js

### ISSUE THREAD

**Issue by max-programming** [electron/electron#25698]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  10.1.3
* **Operating System:**
  *  Windows 10 (2004)
* **Last Known Working Electron version:**
  *  

### Expected Behavior

I expected that `electron` gets installed correctly
### Actual Behavior

I noticed that `electron` installation got stuck at `node install.js`

### To Reproduce

run `npm i electron -D` or `npm i electron` to see this

### Screenshots

![image](https://user-images.githubusercontent.com/51731966/94659527-0f931180-0322-11eb-8d4f-ed2e51399e4e.png)
### Additional Information

I cloned [Basic Electron React Boilerplate](https://github.com/pbarbiero/basic-electron-react-boilerplate) and changed the version in the from 7.x to 10.1.3 in the `package.json`. And after running `npm i --verbose`, I was stuck.

**Comment by zcbenz** [comment]
I'm afraid this is caused by your network environment, I'm sorry this is not something we can fix.

**Comment by max-programming** [comment]
My internet was working fine on that day. Ok when I will get a problem, I will let you knpo.
