### ISSUE TITLE
Datalist's styling is inconsistent with Chrome's

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#25713]
### Issue Details

* **Electron Version:**
  * 10.1.3
* **Operating System:**
  * macOS 10.14
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior

Datalist elements should look like they do in Chrome.

### Actual Behavior

They differ. Here's electron:

![image](https://user-images.githubusercontent.com/1812093/94744905-a5a25880-0371-11eb-8009-21a8ece03b60.png)

Here's chrome:

![image](https://user-images.githubusercontent.com/1812093/94744927-b05ced80-0371-11eb-9bbb-ef9ad958525d.png)

both apps should use chromium 85 under the hood.

### To Reproduce

Gist: https://gist.github.com/e4cea1bc59a49e397cf66c57a4dc416b

### Additional Information

It'd be useful if datalist elements were customizable with CSS, currently it doesn't look like that's the case.

**Comment by miniak** [comment]
@fabiospampinato does this still reproduce with currently supported Electron versions?

**Comment by fabiospampinato** [comment]
@miniak I don't know I don't use that component anymore, I had posted a fiddle that should reproduce the issue.
