### ISSUE TITLE
BrowserView's setAutoResize no longer works (since Electron 10.1.3)

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#25728]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 10.1.3
* **Operating System:** Windows 10
* **Last Known Working Electron version:** 10.1.2

### Expected Behavior
I expect that a BrowserView that's set up to auto resize, will do so

### Actual Behavior
No auto-resizing happens

### To Reproduce
1. start the app below
2. when the page loads in the browserview, resize the window
3. notice the black background. browser view doesn't resize

main.js:
```
const { app, BrowserWindow, BrowserView } = require('electron')

async function createWindow() {
  const mainWindow = new BrowserWindow({ backgroundColor: "#000" });
  const view = new BrowserView();
  mainWindow.setBrowserView(view);

  const contentBounds = mainWindow.getContentBounds();
  view.setBounds({ x: 0, y: 0, width: contentBounds.width, height: contentBounds.height });
  view.setAutoResize({ width: true, height: true });

  await view.webContents.loadURL("https://google.com");
}

app.on('ready', createWindow)
```

**Comment by pejman1** [comment]
> ### Preflight Checklist
> * [x]  I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
> * [x]  I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
> * [x]  I have searched the issue tracker for an issue that matches the one I want to file, without success.
> 
> ### Issue Details
> * **Electron Version:** 10.1.3
> * **Operating System:** Windows 10
> * **Last Known Working Electron version:** 10.1.2
> 
> ### Expected Behavior
> I expect that a BrowserView that's set up to auto resize, will do so
> 
> ### Actual Behavior
> No auto-resizing happens
> 
> ### To Reproduce
> 1. start the app below
> 2. when the page loads in the browserview, resize the window
> 3. notice the black background. browser view doesn't resize
> 
> main.js:
> 
> ```
> const { app, BrowserWindow, BrowserView } = require('electron')
> 
> async function createWindow() {
>   const mainWindow = new BrowserWindow({ backgroundColor: "#000" });
>   const view = new BrowserView();
>   mainWindow.setBrowserView(view);
> 
>   const contentBounds = mainWindow.getContentBounds();
>   view.setBounds({ x: 0, y: 0, width: contentBounds.width, height: contentBounds.height });
>   view.setAutoResize({ width: true, height: true });
> 
>   await view.webContents.loadURL("https://google.com");
> }
> 
> app.on('ready', createWindow)
> ```
have same issue with electron 10.1.3 in windows 10

**Comment by codebytere** [comment]
cc @mlaurencin 👆🏻 might be related

**Comment by ChALkeR** [comment]
Also affects v9.3.2, v9.3.1 was fine.

**Comment by codebytere** [comment]
Yep, likely related to https://github.com/electron/electron/pull/25411

**Comment by ChALkeR** [comment]
> zcbenz added 10-x-y 11-x-y

@zcbenz 9.x is also affected. :-)
