### ISSUE TITLE
Instances of a class A derived from Tray are not instances of class A (since Electron 10.0.0)

### ISSUE THREAD

**Issue by PetaSoft** [electron/electron#25721]
Since Electron 10.0.0 when I derive a class `AppTray` from class `Tray` in the main process, and create an instance `tray` of the class `AppTray`, I get that `tray instanceof AppTray` is `false`. That was not the case for Electron 9.3.1, and it contradicts the normal behaviour of classes. Example:
```javascript
const { Tray, app } = require('electron');
class AppTray extends Tray {
  constructor(icon) {
    super(icon);
  }
}
app.on('ready', () => {
  const tray = new AppTray('<path/to/ison>');
  console.log(tray instanceof AppTray);   // returns false for Electron >= 10.0.0 but true for Electron 9.3.1
});
```
Furthermore, since Electron 10.0.0 I get that `Object.getOwnPropertyDescriptors(Tray.prototype)`  only contains the property `constructor` but `Object.getOwnPropertyDescriptors(tray)` contains all the instance properties of class `Tray`. This can only be the case if `Tray` is a `Proxy`, or the `constructor` function of class `Tray` returns an object different from that with which it was called.

The main problem with that all is that I cannot call any instance methods of class `AppTray` using the instance `tray` any longer (`tray.instanceMethod` is undefined for any `instanceMethod` which I add to class `AppTray`).

**Comment by MarshallOfSound** [comment]
Quoting from another comment I made elsewhere

> Though worth noting, we neither attempt to support nor recommend that you extend built in classes in Electron. It can result in very unexpected behavior

As per #10019 and #23 we do not support extending built in classes in Electron.  You should create a wrapper class that has the window as an instance variable rather than extending the class as that does not work correctly nor will we attempt to make it work correctly in all cases.
