### ISSUE TITLE
My menu renders with curly braces

### ISSUE THREAD

**Issue by leni1** [electron/electron#25720]
Hi. I have an issue where my menu doesn't render correctly.

* Electron version: `^4.2.12` (From my `package.json`)
* Operating system: [KDE Neon](https://neon.kde.org/)

### Expected behavior

Menu should render `Some Text`

### Actual behavior
Menu renders `{{_(Some Text Here)}}`

**Comment by VerteDinde** [comment]
Hey @leni1, thanks for reporting an issue! Two questions for you, so we can start to triage this:

1. Is it possible for you to repro a simple version of this using Electron Fiddle?: https://www.electronjs.org/fiddle This may help us narrow down the problem. If we don't have a specific repro case, we risk wasting a lot of maintainer time on trying to solve the wrong issue.
2. I notice you have Electron 4.2.12 as your version. Electron 11 is currently in beta, with Electron 10 being our latest stable version, so Electron 4 is quite old and no longer in our long-term supported versions. Could you try updating to a newer version of Electron and seeing if that fixes the issue?

Thanks!

**Comment by leni1** [comment]
Hey @VerteDinde thanks for responding.
Unfortunately I am no longer following this issue because it seems the project's dependencies (the one I was trying to build) are more complex than I have time for at the moment 😅 . However the answers to your questions are:

1. I don't think so
2. It is not possible to update the version of Electron at the moment.

Sorry about the late response 🙃. You can close the issue and I'll reopen (having tried #1 properly) when I can. Thanks again 😇
