### ISSUE TITLE
Windows -> Frameless Window -> Having resizing initially set to false causes a white bar at the top when maximized 

### ISSUE THREAD

**Issue by smithalan92** [electron/electron#25746]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  10.1.3
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * Not sure.

### Expected Behavior
When you create a frameless browser window with `resize: false` , and at a later time call `window.setResizable(true)` , double clicking on the titlebar ( with -webkit-drag-region: drag ) should maximize without adding any extra borders/outlines.

### Actual Behavior
When you create a frameless browser window with `resize: false` , and at a later time call `window.setResizable(true)` , double clicking on the titlebar ( with -webkit-drag-region: drag ) to maximize the window causes a white bar at the top of the window. This only happens when double clicking whatever element that has been styled with `-webkit-app-region: drag`. If you have manual buttons to maximise the window using `window.maximize()`, the white bar does not appear.

### To Reproduce
1. Create a browser window with `resizable: false` and `frame: false` as options.
2. Create a titlebar in the renderer process html file, and style it with `-webkit-app-region: drag`
3. Call `window.setResizable(true)` at a later time (eg. in the `ready-to-show` event handler)
4. Double click the titlebar when the app is running to maximise the window and observe results.

**Electron fiddle example: ** https://gist.github.com/smithalan92/d96fea96183aa1f699da6726e54c48d2

### Screenshots
**Double clicking the titlebar**
![image](https://user-images.githubusercontent.com/17986423/94932786-70a51b80-04c1-11eb-8308-e841288bf5ef.png)

**Calling window.maximize() directly**
![image](https://user-images.githubusercontent.com/17986423/94932857-887c9f80-04c1-11eb-8632-d55f51217ede.png)

**Comment by pejman1** [comment]
same issue that I have reported already 
https://github.com/electron/electron/issues/25610#issue-707716500

**Comment by Slapbox** [comment]
We're seeing this issue without `resizable: false`, and regardless of how the window is maximized. Double-clicking a drag region, dragging the window to the top of the screen and letting the OS maximize it, or calling `win.maximize()` all result in the same.

Also, we're generally seeing this issue on the right edge of the screen, not the top. 

[Link to my findings on another thread for the same issue.](https://github.com/electron/electron/issues/25610#issuecomment-698591092)

### Issue Details

- Electron Version: 8.5.1
- Operating System: Windows 7
- Last Known Working Electron version: 8.2.5

**Comment by Realybig** [comment]
官方不打算修复这个问题吗？
