### ISSUE TITLE
File input doesnt work with long file paths

### ISSUE THREAD

**Issue by BrendM** [electron/electron#25769]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  * 7.1.2
* **Operating System:**
  *  Windows 10

### Expected Behavior
Selecting a file with a long path should trigger the onChange event on the file input element. This currently works in firefox/chrome.

### Actual Behavior
With long file paths the file selection dialog opens and the user can select the file but it is not selected on the element and the onChange event is not triggered.

### To Reproduce

1. Name file with a large amount of characters such as
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.jpeg

2. file:
![aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/6525197/95074804-0ed5f300-0707-11eb-8339-7b7e863e399d.jpg)

3. Place file in folder with a long path such as 
D:\aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

4. Attempt to select this file with an file input in electron, no event triggered.

**Comment by nornagon** [comment]
I can't reproduce this on Win 10 on any supported version of Electron (8.x+).

**Comment by MarshallOfSound** [comment]
I tested all my windows boxes too, none of them could repro

**Comment by BrendM** [comment]
Tried both 10.1.3 and 11 beta, still happens for me. Im thinking then it might be related to the native dialog electron opens and the long file path setting in windows. Ill see if I can turn that on though I don't have a lot of access on these machines

**Comment by BrendM** [comment]
Tested it again with longFilePaths enabled no change. Tried this on my other win 10 pc and it works as expected, very strange issue. The file dialog also looks to be the same structure as the one opened by firefox but that works as expected. Is there anything odd about the way electron uses that file dialog that could be causing issues in a specific win 10 environment?

**Comment by zcbenz** [comment]
I'm also unable to reproduce, could it possibly be related to your code? I'm using the code from 
https://developer.mozilla.org/en-US/docs/Web/API/File/Using_files_from_web_applications

**Comment by BrendM** [comment]
I have tried it on a bare electron install jsut using the input on the mdn page and it still happens. Im thinking it has something to do with our company pcs they are very locked down lots of anti virus stuff

**Comment by BrendM** [comment]
<img width="338" alt="none_selected" src="https://user-images.githubusercontent.com/6525197/95761720-a3f75f80-0ca4-11eb-8363-84f2082053dc.PNG">
<img width="915" alt="select_long_name" src="https://user-images.githubusercontent.com/6525197/95761725-a48ff600-0ca4-11eb-8c1a-53588f9bbdfb.PNG">
<img width="763" alt="all_is_well_selected" src="https://user-images.githubusercontent.com/6525197/95761728-a48ff600-0ca4-11eb-9df9-f07c5d0dd903.PNG">
<img width="908" alt="initial" src="https://user-images.githubusercontent.com/6525197/95761730-a5288c80-0ca4-11eb-9ba7-84ca324d20fd.png">
