### ISSUE TITLE
electron net when setProxy first request will lost cookie second time working fine

### ISSUE THREAD

**Issue by LiQingLeo** [electron/electron#25764]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
electron net when setProxy first time request will lost cookie set in the header second time working fine,if not set a new proxy this not happen but when set a new proxy this issue 100% happen at first reqest time
* **Electron Version:**
  * 10.1.3
* **Operating System:**
  * Windows 10 x64
* **Last Known Working Electron version:**
  * no

### Expected Behavior
use the cookie i set in the request header every time

### Actual Behavior
electron net when setProxy first time request will lost cookie set in the header second time working fine,if not set a new proxy this not happen but when set a new proxy this issue 100% happen at first reqest time, and if i am not setProxy this also working fine

### To Reproduce
```
const {net, session} = require('electron')
var express = require('express');
var app = express();
var bodyParser = require('body-parser');
var querystring = require('querystring');
app.use(bodyParser.json({limit: '1mb'}));
app.use(bodyParser.urlencoded({
    extended: true
}));
app.post('/test', function (req, res) {
    var cookie = req.body.cookie;
    var url = req.body.url;
    var proxy = req.body.proxy;
    var data = JSON.stringify(req.body.data);
    var proxyRules = "";
    if (proxy) {
        proxyRules = proxy.split(':')[0] + ":" + proxy.split(':')[1]
    }
    session.defaultSession.setProxy({
        proxyRules: proxyRules
    });
    const request = net.request({
        method: 'POST',
        url: url
    });
    request.setHeader("Cookie", cookie);
    request.write(data)
    request.on('response', (response) => {
        response.on('data', (chunk) => {
            res.status(response.statusCode);
            res.end(chunk);
        })
    });
    request.on('login', (authInfo, callback) => {
        callback(proxy.split(':')[2], proxy.split(':')[3])
    });
    request.end()
});

app.listen(3000, function () {
    console.log('server start at 127.0.0.1:3000')
})
```

### Screenshots
![image](https://user-images.githubusercontent.com/17948150/95017017-528a1780-0689-11eb-8a97-01d93a7bca05.png)

**Comment by nornagon** [comment]
perhaps `await ses.setProxy`? it returns a promise.

**Comment by LiQingLeo** [comment]
> perhaps `await ses.setProxy`? it returns a promise.

hi i try for this but still the same issue

**Comment by LiQingLeo** [comment]
anyone can help?

**Comment by LiQingLeo** [comment]
any update for this issue?
