### ISSUE TITLE
macOS TouchBar Popover should scroll

### ISSUE THREAD

**Issue by dgmid** [electron/electron#25771]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.3
* **Operating System:**
  * macOS 10.15.6
* **Last Known Working Electron version:**
  * unknown

### Expected Behavior
When opening a touchbar popover that contains many items, it should be scrollable

### Actual Behavior
The popover remains fixed with only the first x items visible that fill the space

### To Reproduce

Here is an Electron Fiddle example:

https://gist.github.com/dd34cb5ce74556a580b13646e52a344e

### Additional Information

I don't think this is a bug particular to 10x - I think it's most likely always been this way.
I tried the same gist using 11.0.0 beta and the popover is completely empty with NO items visible

**Comment by MarshallOfSound** [comment]
`NSPopoverTouchBarItem`'s do not scroll, you need to wrap it in a scroll view or a Scrubber item in order for it to scroll.

**Comment by dgmid** [comment]
I see no way in the TouchBar api to wrap a popover in a scroll view.
Using a scrubber does not produce the same functionality.
Buttons loose their appearance and become either text with no background or if they are icons the icons get stretched to the full height of the touchbar. Also it does not scroll when swiping like in other apps with scrolling popovers.

https://gist.github.com/dd34cb5ce74556a580b13646e52a344e

**Comment by 1zilc** [comment]
any progress? 👀
