### ISSUE TITLE
webContents.print: missing default header/footer

### ISSUE THREAD

**Issue by Joe-Kerr** [electron/electron#25785]
### Preflight Checklist

* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version: 9.2.0**
  * 
* **Operating System: Windows 10**
  * 
* **Last Known Working Electron version:**
  * 

### Expected Behavior
The printed pages contain the date and page title in th header as well as the web page and page numbers in the footer.

### Actual Behavior
The printed pages have no default headers/footers.

### To Reproduce
Open this page in Chrome. Hit "Ctrl+p". In the preview you should see the default header/footer. If not, there is a checkbox under advanced options.

**I use a non-english version. Not sure how the UI labels are called in specific.

### Additional Information

The webContents.print function has properties "header" and "footer" each accepting a string value. I did not set either of them hoping it would fall back to the default.

**Comment by codebytere** [comment]
This is not expected behavior for our implementation - if you would like a header and footer you must explicitly set them.

**Comment by Joe-Kerr** [comment]
So I guess if I want current page numbers, I do have to set them in html while predicting page breaks. Bummer :(

**Comment by chihai-chuck** [comment]
`webContents.print({
    footer: " "
});`
just a space

**Comment by Hedwig188** [comment]
Explicitly set header footer won't work when {silent: false}.
[see this issue as an example](https://github.com/electron/electron/issues/28270)
