### ISSUE TITLE
I'VE LOST ALL MY STELLAR

### ISSUE THREAD

**Issue by langigf** [electron/electron#25787]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
* **Operating System:**
  * 
* **Last Known Working Electron version:**
  * 

### Additional Information

have you closed the app : BLOCKEQ?
I had also the app on iphone but now it disapper from the store and i had also the software on my pc and now i don't have anything, what i have to do?

**Comment by James-Livesey** [comment]
Hi! I don't think that your issue pertains to this repository. **Electron** is a platform that can be used by developers to make cross-platform apps using HTML5 technologies, and is _not_ a cryptocurrency wallet.

Judging by what you've put you may have better luck closing this issue and opening a new one on https://github.com/Block-Equity/stellar-ios-wallet, though I believe that BlockEQ isn't a thing anymore as the the BlockEQ website no longer exists and the repository for BlockEQ's iOS client was last updated in November 2019.

I should imagine that BlockEQ is no longer supported and is dead.

Hope this helps 😀
