### ISSUE TITLE
BrowserWindow.close() takes time when frame is true

### ISSUE THREAD

**Issue by GreepTheSheep** [electron/electron#25793]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.0 
* **Operating System:**
  * Windows 10 1909 

### Expected Behavior
Window closes instantly 

### Actual Behavior
Window closes 2 sec after calling window.close()

### To Reproduce
Create new window with frame option set to true
Create something that calls window.close() in the render file
Then test calling the function

**Comment by nornagon** [comment]
I'm not able to reproduce this.

Here's the example I'm trying: https://gist.github.com/5b7da70874d6733775f05f83309e984a

Could you provide a small test case that reproduces the behavior you're seeing, preferably using [Electron Fiddle](/electron/fiddle)?

**Comment by NathanielPather** [comment]
I'm also not able to reproduce this.

Here's my example (using ipc to communicate with main and renderer processes): https://gist.github.com/NathanielPather/15af0f6363dcf0ebcd332cc845021da3

**Comment by GreepTheSheep** [comment]
I tried with frame false because I have a custom titlebar. Here's my repo: https://github.com/GreepTheSheep/electron-tests

**Comment by NathanielPather** [comment]
Where are you calling window.close()? I looked around and can't find it.

**Comment by GreepTheSheep** [comment]
It's from  custom-electron-titlebar module

Le jeu. 8 oct. 2020 à 08:21, Nathaniel Pather <notifications@github.com> a
écrit :

**Comment by nornagon** [comment]
I'm also not able to reproduce this with `frame: false`.

**Comment by zcbenz** [comment]
I'm also unable to reproduce, can you try to make a minimal reproducible app? The problem might be inside the dependencies you use.

**Comment by GreepTheSheep** [comment]
I think this problem is in the unpackaged version of the app. Because when it is packaged it works normally. I give you the app: https://github.com/ArendelleOdyssey/web-app Maybe it's fixed, I haven't tested unpacked yet for a week.

**Comment by NathanielPather** [comment]
I've reproduced this error by cloning the earlier version of your app. The lag only occurs when the frame option is set to false. When the frame is set to true, the lag isn't there.

> ### To Reproduce
> Create new window with frame option set to true

@GreepTheSheep Is this a misquote from you?

**Comment by GreepTheSheep** [comment]
Oups okay i said when frame is set to false, it's a misquote. Sorry

**Comment by NathanielPather** [comment]
I am new to chrome://tracing so what I say could be wrong.

The CrRendererMain track seems to have the most activity around closing the app: https://i.imgur.com/zAqYz5g.png
In comparison the CrBrowserMain and CrGpuMain tracks have less activity.
CrBrowserMain: https://i.imgur.com/26jNpQp.png
CrGpuMain: https://i.imgur.com/WtC7lBP.png
(All images are zoomed the same).

I suspect the issue is either a paint, layout, or gpu issue (according too: http://www.chromium.org/developers/how-tos/trace-event-profiling-tool/trace-event-reading#TOC-Investigation-strategy).

I would like a copy of the files for: https://arendelleodyssey.com so I can do further testing.

**Comment by pushkin-** [comment]
I can't repro this, and my GPU is disabled.

Could you try disabling the GPU via the workaround [here](https://github.com/electron/electron/issues/20702#issuecomment-637156596) and see if that solves it?

**Comment by GreepTheSheep** [comment]
> I would like a copy of the files for: https://arendelleodyssey.com so I can do further testing.

@NathanielPather It was a Wordpress installation. You can host your own Wordpress.


> Could you try disabling the GPU via the workaround here and see if that solves it?

@pushkin- I can check this.
