### ISSUE TITLE
Major crash of Slack Desktop app on macOS Catalina

### ISSUE THREAD

**Issue by Maxime3469** [electron/electron#25797]
### Preflight Checklist

* [ X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.10.0 (Slack version from AppStore on MacOS).
* **Operating System:**
  * macOS Catalina 10.15.7
* **Last Known Working Electron version:**
  * 4.9.0 (Slack version from AppStore on MacOS).

### Expected Behavior
I expected Slack to start like it does every time I click on the desktop app button.

### Actual Behavior
The app crashes and shows a critical error (Javascript error in the main process).

### To Reproduce
To reproduce that issue, simply upload to Slack 4.10.0 on MacOS through AppStore and observe the major crash.

### Screenshots
<img width="412" alt="Capture d’écran 2020-10-06 à 16 53 01" src="https://user-images.githubusercontent.com/66638743/95259467-3c996580-07f5-11eb-9e87-5e861326929e.png">

### Additional Information
None that I can provide unfortunately.

**Comment by MarshallOfSound** [comment]
This issue is specific to Slack Desktop, if you reach out to slack support they can try to assist you
