### ISSUE TITLE
Nullish Coalescing Operator (??)

### ISSUE THREAD

**Issue by Ephellon** [electron/electron#25791]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * `5.0.13`
* **Operating System:**
  * `Windows 10`
* **Last Known Working Electron version:**
  * **N/A**

### Expected Behavior

1. The JavaScript syntax highlighter should distinguish between `??` ([Nullish Coalescing Operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator)) and `? ...: ...`
2. The highlighter should also allow the correct code-folding for `??`

### Actual Behavior

1. The syntax highlighter ignores `??` and treats it as `? ...: ...`
2. Code-folding currently mismatches `{}` `[]` and `()` due to it thinking `??` &rArr; `? ...: ...`

### To Reproduce

1. Use the JavaScript syntax highlighter
2. `Copy/Paste`
```javascript
// ...
// Notifications
NOTIFICATIONS = $('[data-test-selector="onsite-notifications-toast-manager"i] [data-test-selector^="onsite-notification-toast"i]', true).map(
    element => {
        let streamer = {
            live: true,
            href: $('a', false, element)?.href,
            icon: $('figure img', false, element)?.src,
            name: $('figure img', false, element)?.alt,
        };

        if(!defined(streamer.name))
            return;

        element.setAttribute('draggable', true);
        element.setAttribute('twitch-tools-streamer-data', JSON.stringify(streamer));
        element.ondragstart ??= event => {
            let { currentTarget } = event;

            event.dataTransfer.setData('application/twitch-tools-streamer', currentTarget.getAttribute('twitch-tools-streamer-data'));
            event.dataTransfer.dropEffect = 'move';
        };
    }
);
// ...
```
3. Attempt to fold *line 17* (it should be matched with *line 22* but isn't)

### Screenshots

> ### Incorrect pair being matched (*line 17* highlighted)
> ![image](https://user-images.githubusercontent.com/8632548/95227581-82393c80-07bb-11eb-9e33-53040229f281.png)

> ### Correct pair being matched (*line 22* highlighted)
> ![image](https://user-images.githubusercontent.com/8632548/95227047-de4f9100-07ba-11eb-9145-5d8b69aa0099.png)

### Additional Information

**None**

**Comment by James-Livesey** [comment]
It looks like you're reporting an issue for **Atom** in the **Electron** repository and I think you're going to be better off closing this issue and opening a new one at https://github.com/atom/atom.

* **Electron** is the web-based engine which hasn't got anything to do with Atom's code parser that you're having issues with.
* **Atom** — the editor you're using — is built on Electron, and issues for Atom should reside on the Atom repo.

You _should_ be able to copy and paste this issue's markdown into an issue for Atom, although I think the issue template/style for the Atom repo is slightly different from the Electron one.

Hope this helps! 😀

**Comment by Ephellon** [comment]
Thanks
