### ISSUE TITLE
Web links in Electron apps open up multiple windows

### ISSUE THREAD

**Issue by igbjnI05bF** [electron/electron#25790]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

This has been tested with multiple electron apps, Element and Hyper. When I click on a web link, multiple browser windows open. In my case it is 3 Qutebrowser windows and one Firefox window.

xdg-settings get default-web-browser returns Qutebrowser (which is what I want)
xdg-open https://github.com opens up once in Qutebrowser (which is what I want)
Clicking on links in any other program on my desktop opens up in Qutebrowser once (which is what I want)
Clicking on links from within an Electron app opens up 3 Qutebrowser windows and 1 Firefox window (do not want)

* **Electron Version:**
v10.1.2 and forward
* **Operating System:**
Gentoo Linux amd64 kernel 5.8.12
* **Last Known Working Electron version:**
  * 

### Expected Behavior
I want the Electron app to respect my default program defined by xdg-settings set default-web-browser

### Actual Behavior
Electron apps open up web links in four separate windows, 3 in Qutebrowser and 1 in Firefox

### To Reproduce
Click on a web link in an electron app

**Comment by zcbenz** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you've responded, please link to the test case and @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
Closing as no response given.
