### ISSUE TITLE
Cannot open app on Mac after updating

### ISSUE THREAD

**Issue by brandonclayton** [electron/electron#25809]
![Screen Shot 2020-10-07 at 9 49 29 AM](https://user-images.githubusercontent.com/43416175/95366985-2f868000-08a2-11eb-8977-caaa9d39c8d9.png)

**Comment by nornagon** [comment]
This issue is Slack-specific, not an issue with Electron. You should be able to reach out to Slack support for assistance. (But try updating to 4.10.1 in the store!)
