### ISSUE TITLE
Performance lost

### ISSUE THREAD

**Issue by theArina** [electron/electron#25800]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.1
* **Operating System:**
  * Windows 10 (1809)

### Expected Behavior
Small difference between chrome and electron performance.

### Actual Behavior
The difference is over 7 times.

### To Reproduce
[Chrome extension](https://github.com/theArina/chrome-performance-test)
[Small electron app](https://github.com/theArina/electron-performance-test)

### Additional Information
I've tested it on virtual machine. Here is my results:

(average time till the event 'DOMContentLoaded' in milliseconds)

**chrome**
 468 

**electron**
3519

**Comment by nornagon** [comment]
It looks like you're comparing the time to load an Electron view from scratch against opening a new tab in Chrome. This is an apples-to-oranges comparison. In the Chrome case, all Chrome's code will already be in memory, whereas all Electron's loading and initialization is included in your Electron measurement.

A fairer comparison would be loading a second (or third, or fourth) window in Electron.

I'm closing this for now as the comparison is invalid, but if the performance difference remains on subsequent loads there might be something more we can look into and we'll consider reopening.

**Comment by theArina** [comment]
@nornagon, thank you for the answer. I should've mention this, but i tried to test it with windows as well and tried different windows number. The average result was even longer.

**Comment by theArina** [comment]
@nornagon, i've updated my test examples, please take a look.
The average result for the 5 windows is 8 seconds per 1 window. For 5 tabs in chrome chrome it's 1.4 seconds per 1 tab without "active" mode and 4 seconds with active mode.

**Comment by theArina** [comment]
Here is machine details.
![image](https://user-images.githubusercontent.com/32187787/95323517-f997ca80-08a6-11eb-86d5-2816b4451cf3.png)

**Comment by nornagon** [comment]
It looks like your updated Electron test is opening 5 new windows at once, so you're still including initialization time and code loading in your measurement.

I've modified your example to measure something that I think is a closer comparison to your Chrome extension: https://gist.github.com/a75f0c4c198517b8fd1abe6c6fafcf6f. Note that this benchmark "warms up" the app by creating two windows before beginning measurement. This is to simulate the fact that in the Chrome example, Chrome has already loaded all the renderer code into memory for other tabs.

On my machine, on Electron v10.1.3, this gives an average time to dom-ready of 866 ms. With `sandbox: true` the time is even lower, around 800 ms.

**Comment by theArina** [comment]
@nornagon, thank you for your example. So, relaying on your answer, i assume that Chrome is creating process pool that allows it open tabs fast, is that right? If it is, do you suggest using same pattern in Electron if i need to create a lot of tabs/windows fast?

**Comment by nornagon** [comment]
Chrome does do that, and it's certainly an option you can explore. However, my example does not do that. I was simply showing that the first page loaded will necessarily take longer than subsequent loads. This is also true in Chrome.

**Comment by theArina** [comment]
@nornagon, what approach using process pool whould you suggest choosing from BrowserView and BrowserWindow to acheive best multi tab experience? Now we're using WebView and want to change it.
