### ISSUE TITLE
Will-move event listener newBounds parameter incorrect value

### ISSUE THREAD

**Issue by bohdanzhylavskyi** [electron/electron#25811]
I have created simple window and add `will-move` listener. After moving window little bit down (few pixels only in vertical direction), `will-move` listener is called with `newBounds` parameter object, that contains incorrect values (`x`, `width`, `height` changed). Please look at simple demonstation:

Script:
```
mainWindow.once('will-move', (e, newBounds) => {
   console.log('Window current bounds: ', mainWindow.getBounds());
   console.log('Window newBounds', newBounds);
})
```
Result (logs in terminal after moving window little bit down (few pixels only in vertical direction)):

![image](https://user-images.githubusercontent.com/12056012/95378841-28d12a80-08ed-11eb-9722-40d4df087953.png)

As you can see, here `x` property changed (but it should not, because i'm moving window only in vertical direction), `height` and `width` also changed (but it should not, because i'm not resizing window, i'm just moving it).

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.1
* **Operating System:**
  * Windows 10 (version 1903, 18362.1082)
* **Last Known Working Electron version:**
  * -

### Expected Behavior
`newBounds` parameter value should have `x`, `width` and `height` values same as in bounds returned by `mainWindow.getBounds()` but only `y` value should be different (because i'm moving window little bit down).

### Actual Behavior

As you can see, here after moving window little bit down (few pixels only in vertical direction), `x`, `width` and `height` properties values in `newBounds` is not same as the corresponding properties values in bounds object returned by `mainWindow.getBounds()`.

### To Reproduce
I have created demo branch from quick start repo: [demo commit](https://github.com/bohdanzhylavskyi/electron-quick-start/commit/fa8f3ef0713b6476eb18d47ad762fc47f2fb0f22). To reproduce please run application `npm start`, try to move window and look at terminal log.

**Comment by samuelmaddock** [comment]
Confirmed that this occurs with both `will-resize` and `will-move`. The issue has to do with the display having a scale factor. Typically this will be found with any 4k displays.

Here's a Fiddle gist which shows the problem with `will-resize`:
https://gist.github.com/samuelmaddock/b2089a6088e07ba139f92ee7b093ee48
![image](https://user-images.githubusercontent.com/1656324/118185486-93f65880-b40a-11eb-9e4d-5b289c268223.png)

The `RECT` parameter emitted on events like `will-resize` will need to be scaled according to the display scale factor.
https://github.com/electron/electron/blob/9cf71d72abf97c7583b200063915aa9c8fb23e15/shell/browser/native_window_views_win.cc#L263-L264

I'll update the OP with newly found info.
