### ISSUE TITLE
Simple way to use minimal Electron features without opening security holes.

### ISSUE THREAD

**Issue by burtonator** [electron/electron#25847]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

We're redesigning our Electron app to lock out any potential security holes by disabling node module require, ipc, etc. Basically we're trying to turn it into just a basic browser.

The problem is I still need a FEW items like it would be nice to call shell.openExternal to open a URL in the user's default browser.

In order to do this though I have to enable require() and I don't want to do that.  

It might be nice if there was just an implicit 'electron' global variable with a few minimal functions like this where there's VERY little opportunity for security issues.

### Proposed Solution

Create an 'electron' variable in global scope like 'window' with specific functionsl

### Alternatives Considered

none I think.

**Comment by pushkin-** [comment]
Isn't this the point of the preload script? Just expose a single method that tells the main process to execute `openExternal()`

**Comment by MarshallOfSound** [comment]
@pushkin- is correct, you should expose these yourself over IPC via your preload script.  Here as a minimal secure example of how you'd expose `openExternal` in a relatively safe way.

https://gist.github.com/ad19a8846c06033cb07a8b203ebda7f6
