### ISSUE TITLE
Double click on the icon in titlebar cause app quit

### ISSUE THREAD

**Issue by gfafei** [electron/electron#25849]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 8.5.0
  * 
* **Operating System:** win10
  * 
* **Last Known Working Electron version:**
  * 

### To Reproduce

open a normal window with titlebar

### Screenshots

![image](https://user-images.githubusercontent.com/12234890/95549717-5b3c6e00-0a3a-11eb-92c8-6e0c89f24085.png)

### Additional Information

I don't sure it is a bug. But I cannot understand where the dbclick event hanlder come from, can I chang the handler of the dbclick event?

**Comment by nornagon** [comment]
this is expected behavior on windows.
