### ISSUE TITLE
Mouse events from graphics tablet are wrong when debugging with VSCode.

### ISSUE THREAD

**Issue by Nukiloco** [electron/electron#25850]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v10.1.2

* **Operating System:**
  * Windows 10

* **Last Known Working Electron version:**
  * v10.1.2

### Expected Behavior

Mouse down should be activating when the pen touches the screen, and mouse up should be activating when the pen is released from the screen.

### Actual Behavior

Mouse down and mouse up events are both called at the same time. However in a built electron app, mouse down and mouse up events work correctly.

### To Reproduce

```
document.addEventListener('mouseup', function() {
console.log('mouseup')
})

document.addEventListener('mousedown', function() {
console.log('mousedown')
})
```

### Additional Information

Im debugging the electron app with VSCode.

**Comment by zcbenz** [comment]
I'm not exactly sure what VSCode does to your app when debugging with it, can you open a issue in VSCode's repo to see if it is a bug of VSCode?

**Comment by Flairieve** [comment]
```
{
        "name": "Debug Main Process",
        "type": "node",
        "request": "launch",
        "cwd": "${workspaceRoot}",
        "runtimeExecutable": "${workspaceRoot}/src/node_modules/.bin/electron",
        "windows": {
          "runtimeExecutable": "${workspaceRoot}/src/node_modules/.bin/electron.cmd"
        },
        "program": "${workspaceRoot}/src/electron.js",
        "protocol": "inspector",
        "outputCapture": "std"
      },
      {
        "name": "Debug Renderer Process",
        "type": "pwa-chrome",
        "request": "launch",
        "sourceMaps": false,
        "runtimeExecutable": "${workspaceRoot}/src/node_modules/.bin/electron",
        "windows": {
          "runtimeExecutable": "${workspaceRoot}/src/node_modules/.bin/electron.cmd"
        },
        "runtimeArgs": [
          "${workspaceRoot}/src/electron.js",
          "--remote-debugging-port=9222"
        ],
        "webRoot": "${workspaceRoot}"
      }
```
This is a snippet of the launch configuration that i use in vscode. I don't think it would be an issue with vscode but I guess I can open an issue on the VSCode repo just to make sure.

**Comment by Flairieve** [comment]
The issue was closed on VSCode which they said that it is probably an issue with Electron.
Like I said on the VSCode issue, I launched it manually in the VSCode powershell terminal and then in powershell without debugging with VSCode. The same issue occurred on both of them.

**Comment by Flairieve** [comment]
I have just found out both issues with Electron now of why my graphic tablet wasn't responding when debugging it and why file drop wasn't working at all. First check if the Node.js exe is not running as administrator, then check to see if your ide is not running in administrator mode (aka if your running VSCode as administrator). If you turn off Run As Administrator on NodeJS and/or VSCode, then you won't get the graphics tablet issue and file dragging and dropping will also work again.
