### ISSUE TITLE
Setting BrowserView to fit the parent window behaves unexpectedly

### ISSUE THREAD

**Issue by lockieluke** [electron/electron#25868]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  10.1.2
* **Operating System:**
  *  Windows (1903) x64
* **Last Known Working Electron version:**
  *  Unknown

### Expected Behavior

The BrowserView should fit the parent window size(This issue only appears when the parent window is in maximized mode and frameless mode)
### Actual Behavior

When I set the bounds of the BrowserView to the parent window size, it exceeded the parent window size. (Look at screenshot provided).  However, on other operating systems like Linux, we did not see this problem.
### To Reproduce

Just set the bounds to fit the parent window and voila!

[Fiddle Gist](https://gist.github.com/469ffcce77d4e9aa1c9c35a715d8b901)

### Screenshots

When the parent window is not maximized...
![image](https://user-images.githubusercontent.com/25424409/95642027-88d7f480-0ad8-11eb-878a-d1420f2fd55f.png)

When the parent window is maximized... (Scrollbar disappeared)
![image](https://user-images.githubusercontent.com/25424409/95642051-a60cc300-0ad8-11eb-9e4f-6199d9a9e326.png)

**Comment by zcbenz** [comment]
I'm merging this to https://github.com/electron/electron/issues/25728.
