### ISSUE TITLE
autoUpdater saves previous version. Adds up to big folder size.

### ISSUE THREAD

**Issue by plusflabby** [electron/electron#25875]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
When using the autoUpdater it saves the new version and the old version. This adds up to a really big folder over time.

### Proposed Solution
Add an option to remove previous versions.

### Alternatives Considered
Writing my own code to remove the previous version folder.

**Comment by zcbenz** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you've responded, please link to the test case and @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by plusflabby** [comment]
@zcbenz Figured out this issue was Squirrel and updating it resolves the issue and it only saves current and previous versions. Seen in https://github.com/Squirrel/Squirrel.Windows/issues/589
