### ISSUE TITLE
Non-draggable children with draggable parent sometimes lose ability to interact

### ISSUE THREAD

**Issue by courtney-regis** [electron/electron#25885]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.2
* **Operating System:**
  * Windows 10

### Expected Behavior
A non-draggable child of a draggable element should always be responsive to mouse events. 

### Actual Behavior
When creating dynamic non-draggable children (e.g dynamic tabs) in a draggable parent, sometimes the children become draggable and lose interactivity. 
This is resolved by resizing the screen or causing the child element to be re-rendered (adjusting height)

### To Reproduce
* Create a div with css: -webkit-app-region: drag
* Dynamically add anchor links inside the parent with -webkit-app-region: no-drag (using a button or something)
* At some point, one or all the anchor links with the right css property will lose interactivity

### Additional Information

**Comment by zcbenz** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you've responded, please link to the test case and @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
