### ISSUE TITLE
Not allowed to load local resource

### ISSUE THREAD

**Issue by kolaente** [electron/electron#25884]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * `9.1.0`
* **Operating System:**
  * `NixOS 20.03, Kernel 5.4.69`
* **Last Known Working Electron version:**
  * `none`

### Expected Behavior

I created a new electron project (see "To reproduce" for more details) to package my existing web application.
When running locally for development it works fine. However, when I build the app for release and try to run it on my windows vm  I get this error in the dev tools: 
![image](https://user-images.githubusercontent.com/13721712/95676650-e2671e80-0bbf-11eb-9f05-8521a1ef8a4d.png)

### To Reproduce

The repo is available here: https://kolaente.dev/vikunja/desktop

To setup:

```bash
git clone https://kolaente.dev/vikunja/desktop.git
cd desktop
# Download and prepare the actual app files
wget https://dl.vikunja.io/frontend/vikunja-frontend-master.zip
unzip vikunja-frontend-master.zip -d frontend
sed -i 's/\/fonts/file\:\/\/fonts/g' frontend/index.html
sed -i 's/\/js/file\:\/\/js/g' frontend/index.html      
sed -i 's/\/css/file\:\/\/css/g' frontend/index.html    
sed -i 's/\/images/file\:\/\/images/g' frontend/index.html
sed -i "s/\/'images/'file\:\/\/images/g" frontend/js/*
# Dependency installation
yarn
# Build the app
docker run -it -v $PWD:/project  electronuserland/builder:wine # Using the docker image to cross compile and for better reproducability
yarn dist --win --linux
```

### Additional Information

There have been other issues like this: https://github.com/electron/electron/issues/13528 https://github.com/electron/electron/issues/5107 https://github.com/electron/electron/issues/4867 

I've tried their solutions without luck. Even disabling websecurity does not work.

I was able to verify the `app.asar` contains all files for my app:

```
asar list dist/win-unpacked/resources/app.asar
/package.json
/src
/src/index.js
/frontend
/frontend/favicon.ico
/frontend/index.html
/frontend/manifest.json
/frontend/precache-manifest.f920ae24cd5e3b4acac0aca80dc14ad0.js
/frontend/robots.txt
... even more files from my app
```

Other things I observed:

When I try to load my app with `path.normalize` it tries to load from the asar, with `path.resolve` it tries to load directly.

Disabling asar does not work either.

I also tried `win.loadURL(file://<path>)` instead of `win.loadFile` with does not work either.

**Comment by zcbenz** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself?

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you've responded, please link to the test case and @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by kolaente** [comment]
It looks like it works with just the hello-world app and electron builder - I'll add my application files next and see if it's still working.

**Comment by kolaente** [comment]
So after some more investigating, it seems like this is the fault of my custom file protocol which I used to serve the files without having to start a local web server: https://kolaente.dev/vikunja/desktop/src/commit/e5774d4553eae5166fa1d3f02e744c7189d64980/src/index.js#L38

I'll probably end up just using a local express to host the app files but would've liked to avoid that.
Maybe someone has an idea why the file protocol did not work?

**Comment by codebytere** [comment]
Closing as this issue seems resolved.

**Comment by szv** [comment]
Hi,
I am able to load a local file like this:
```javascript
const electron = require("electron");
const path = require("path");
const url = require("url");
let window;
electron.app.on("ready", createWindow);
electron.app.on("activate", () => {
    if (window === null)
        createWindow();
});
function createWindow() {
    window = new electron.BrowserWindow({ width: 800, height: 600 });
    window.loadURL(url.format({
        pathname: path.join(__dirname, "../../dist/index.html"), // relative path to the HTML-file
        protocol: "file:",
        slashes: true
    }));
    window.webContents.openDevTools();
    window.on("closed", () => {
        window = null;
    });
}
```

Maybe this helps 😃

**Comment by PoojaDaredi** [comment]
I had similar issue and by adding below code in "`build`" this is fixed:-

    "files": [
        "**/*",
        "!**/*.ts",
        "!*.map",
        "!package.json",
        "!package-lock.json",
        {
          "from": "../dist",
          "filter": ["**/*"]
        }
      ],

Mainly 

            {
              "from": "../dist",
              "filter": ["**/*"]
            }

And remove  "`extraResources`" if present.

And in winloadurl add dist like this:-

 

    win.loadURL(path.join(__dirname,'../dist/index.html'));

I am using Electron-24, Node-18 and Angular-16

**Comment by sytolk** [comment]
I have the same issue but in development only. In production build works. This my url to index.html: https://github.com/electron-react-boilerplate/electron-react-boilerplate/blob/main/src/main/util.ts#L6
![Screenshot 2023-11-23 114902](https://github.com/electron/electron/assets/1415463/96ee0d0d-6a24-4dd2-b7b8-8bb7bfd58ad0)
