### ISSUE TITLE
AutoUpdater documentation lacks explanation of purpose

### ISSUE THREAD

**Issue by NathanielPather** [electron/electron#25887]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

As a graduate developer I have little experience with automated deployment. While learning autoUpdater the guide didn't explicitly say what autoUpdater is and what it is used for.

### Proposed Solution

AutoUpdater guide should explain:
- what an autoUpdater is,
- why I should use an autoUpdater,
- advantages of using an autoUpdater

### Example
An autoUpdater is an automated deployment system that regularly updates your users with the latest version of your application. The advantages of using an auto updater include:
- Automating the update of your user applications,
- Removing the need to download a new setup file for each update

### Alternatives Considered

If the guide isn't edited, then new documentation should be added.

### Additional Information

autoUpdater API documentation: https://www.electronjs.org/docs/api/auto-updater
autoUpdater guide: https://www.electronjs.org/docs/tutorial/updates
autoUpdater guide code: https://github.com/electron/electron/blob/master/docs/tutorial/updates.md

**Comment by jayantchaudhary002** [comment]
I would like to work on this issue

**Comment by 4tex** [comment]
I would like to work on this issue

**Comment by PurvaT** [comment]
Please assign it to me for updation of documentation

**Comment by vipulmaheshwari09042001** [comment]
I would like to work on this issue.

**Comment by BharatiSukanya** [comment]
Can I work on this issue?

**Comment by KishkinJ10** [comment]
please assign me this issue

**Comment by VerteDinde** [comment]
Hey @KishkinJ10, thanks for volunteering! I see you have a commit that references this issue, could you open a PR and we can review it for you? If you need help doing that, please tag me in a comment here 🙂

**Comment by steel9209** [comment]
VerteDinde, I tag you, but I don't see a tag anywhere. But I need help doing it. If you can come through.

**Comment by includestdlibrary** [comment]
Is this issue still open?
