### ISSUE TITLE
`intercept*Protocol` Methods Break Redirect Handling Routines

### ISSUE THREAD

**Issue by allfro** [electron/electron#25894]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * `<=v10.1.3`
* **Operating System:**
  * All
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
Redirect handling for non-GET requests in scenarios where HTTP/HTTPS requests are intercepted using the `interceptHttpProtocol` and `interceptStreamProtocol` handlers should follow the same standards as non-intercepted requests. This should be true for `BrowserWindow`, `BrowserView` and `webview`. For example, the following is an example of `GET` request being redirected and the subsequent request thereafter:

```http
client> GET / HTTP/1.1
client> Host: foo.com
client> 
client> 
server> HTTP/1.1 302 OK
server> Location: http://foo.com/new
server> Content-Length: 0
server>
server>
client> GET /new HTTP/1.1
client> Host: foo.com
client>
client>
```
The same should be true for non-GET requests that result in redirections (with exceptions listed here: [https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections](https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections)):

```http
client> POST /form HTTP/1.1
client> Host: foo.com
client> Content-Length: 3
client> Content-Type: application/x-www-form-urlencoded
client> 
client> a=b
server> HTTP/1.1 302 OK
server> Location: http://foo.com/new
server> Content-Length: 0
server>
server>
client> GET /new HTTP/1.1
client> Host: foo.com
client>
client>
```

Furthermore, the developer tools should display all the requests and responses that occurred (1 entry per request/response pair).

### Actual Behavior
Redirect handling for non-GET requests in scenarios where HTTP/HTTPS requests are intercepted using the `interceptHttpProtocol` and `interceptStreamProtocol` handlers are NOT following the same standards as non-intercepted requests. This is what happens, instead, with all 3xx responses:

```http
client> POST /form HTTP/1.1
client> Host: foo.com
client> Content-Length: 3
client> Content-Type: application/x-www-form-urlencoded
client> 
client> a=b
server> HTTP/1.1 302 OK
server> Location: http://foo.com/new
server> Content-Length: 0
server>
server>
client> POST /new HTTP/1.1
client> Host: foo.com
client> Content-Length: 3
client> Content-Type: application/x-www-form-urlencoded
client> 
client> a=b
```

This breaks interaction with a lot of websites; especially in scenarios where client authentication is being processed. For example, logging into Github.com successfully results in a 302 in scenarios where two factor authentication is required. The current implementation (without introducing some awful hacks) would break this interaction. 

Furthermore, it appears that 3xx responses are expected to be resolved prior to returning data to the interceptor callback. This creates an inconsistency in the Developer Tools network tab where 3xx responses automatically resolve to the final response code (i.e. 200) if the interaction resulted in a successful redirection. Meaning, the redirect request, response pair is lost in the log.

### To Reproduce

TBD

### Screenshots

The following screenshots demonstrate the issue using a login sequence on GitHub. After initial login request, the server redirects me to the 2FA form which is at `/sessions/two-factor`. The following is what happens when I don't implement redirection detection hacks:

![Failed Login Without Redirection Hack](https://user-images.githubusercontent.com/618125/95768170-e65c7480-0c83-11eb-9c2c-7afe7f9b1bf5.png)

As can be seen, the redirect returns a 422 because the method and body remained unchanged during in the redirecting handling routine.

And the following demonstrates the proper result in the GUI with redirect detection hacks to modify the original request into a `GET` without a body, however, the developer tools network tab does not show an entry for the redirect/response pair to `/sessions/two-factor`:

![Login With Redirection Hack but No Developer Tools Network Entry](https://user-images.githubusercontent.com/618125/95767909-7fd75680-0c83-11eb-8bcc-59a9cf56a06d.png)

As can be seen in the image above, the only request is to `/session` and the redirect gets handled internally and resolved to a 200 once the redirect has completed successfully.

### Additional Information

TBD

**Comment by allfro** [comment]
I've resorted to using the Chrome Debug Protocol to do what I needed to do. However, this is far from ideal as the API is very involved. The API that Electron offers is much more elegant if it were to work properly :(

**Comment by dsanders11** [comment]
@allfro, can you give an example of code you'd use in `interceptHttpProtocol`? And possibly your 'redirect detection hacks'?

**Comment by allfro** [comment]
@dsanders11 I've abandoned this approach for the more reliable CDP implementation. But my expectation when using `interceptHttpProtocol` would be to allow me to modify elements of the HTTP request/response without impacting the usual flow of how HTTP is handled by WebView un-intercepted; similar to how other interception frameworks work for middling HTTP/HTTPS traffic (i.e. mitmproxy, pymiproxy, etc.). Instead, this implementation is making it very difficult to deal with interception as the developer has to manually update the cookie store, manage redirects, and manage upload data serialization. The API presented by the CDP is closer to what I would have loved to see with this API:

```
Request Intercepted --> Requires Modification? -- No --> Continue Request as-is
                                              `-- Yes --> Modify in handler --> Continue or Return Response
```

```
Response Intercepted --> Requires Modification? -- No --> Continue Request as-is
                                               `-- Yes --> Modify in handler --> Continue or Return Response
```

What I've noticed, however, is that Chrome does not provide CDP clients with the body of 3xx responses (unfortunate). This would be nice to have in intercept*Protocol handlers.

**Comment by dsanders11** [comment]
@allfro, do you only need to modify headers for the request, or the body? The [WebRequest class](https://www.electronjs.org/docs/api/web-request) would allow modifying headers.

**Comment by allfro** [comment]
All parts of the request and response pair should be modifiable. WebRequest doesn't allow for that. CDP does.

**Comment by cuixiping** [comment]
Electron Version:  >=v22.3.5
Operating System: All

I don't think it is fixed.

```
session.defaultSession.interceptHttpProtocol("http", (request, callback) => {
    callback({...request, session: null});
});
```

When window load `http://a.com/`,  if server redirect to `http://b.com/` with "Location" header, the window url will keep  `http://a.com/` and content is from `http://b.com/`.  We expect the window url become `http://b.com/` which match the content.

**Comment by XieJiSS** [comment]
@cuixiping consider providing `redirect: "manual"` as request options to callback.

**Comment by DaniGuardiola** [comment]
@XieJiSS that results in "Error: Redirect was cancelled" (using the new `protocol.handle` method though)

**Comment by XieJiSS** [comment]
> @XieJiSS that results in "Error: Redirect was cancelled" (using the new `protocol.handle` method though)

@DaniGuardiola I also uses the new `protocol.handle`. AFAIK If you are using https://www.electronjs.org/docs/latest/api/client-request then according to the docs you need to tell electron whether you'd like to follow redirect or not by conditionally invoking `https://www.electronjs.org/docs/latest/api/client-request#requestfollowredirect`.

Another approach is to specify `redirect: "manual"` to `net.fetch`, which follows the WHATWG fetch spec - https://developer.mozilla.org/en-US/docs/Web/API/fetch#redirect. e.g.

```js
protocol.handle('http', (request) => {
    return net.fetch(request.url, { redirect: "manual" });
});
```

**Comment by DaniGuardiola** [comment]
@XieJiSS I've tried that but it fails with "Error: Redirect was cancelled" as I said. Not sure if I'm missing something else.

Your exact same code, when loading `google.com` in an iframe (to put an example), crashes with a redirect response.
