### ISSUE TITLE
Can't compile Wasm with contextIsolation

### ISSUE THREAD

**Issue by xinaesthete** [electron/electron#25892]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

The nearest issue I have found is https://github.com/electron/electron/issues/23252, but I haven't investigated use of that environment variable (which would need to be set in a different way to work on Windows).

### Issue Details

* **Electron Version:**
10.1.3
* **Operating System:**
Windows 10 (19041.508)
* **Last Known Working Electron version:**
9.0.0

### Expected Behavior
To be able to compile WebAssembly, as long as appropriate `Content-Security-Policy` conditions are met.

### Actual Behavior
An error `Wasm code generation disallowed by embedder` is thrown if `contextIsolation = true`.

### To Reproduce
There is a minimal reproduction [here](https://github.com/xinaesthete/electron-wasm-issue), derived from that provided in relation to the aforementioned issue.

```
git clone https://github.com/xinaesthete/electron-wasm-issue
cd electron-wasm-issue
npm install
npm start
```
Should display an alert indicating the compilation was successful, or giving an error message.

As per the readme: on my machine, I am finding that running electron 9.0.0 works as expected, as does unsetting `contextIsolation` in `BrowserWindow` configuration.

**Comment by codebytere** [comment]
This was fixed by https://github.com/electron/electron/pull/25777, i will backport it shortly

**Comment by xinaesthete** [comment]
Ah, apologies for missing the issue (I suspect I neglected to include closed issues in search).  Anyway, great that it's fixed.
