### ISSUE TITLE
Electron 7 - autoUpdater.quitAndInstall fails to relaunch on MacOS 11

### ISSUE THREAD

**Issue by nbashkankov** [electron/electron#25912]
Since https://github.com/electron/electron/issues/25626 just closed without ability to ask any question about how to get fix bundled into other electron versions - I open new issue

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.2.1
* **Operating System:**
  * MacOS 11 BigSur Beta (20A5384c)
* **Last Known Working Electron version:**
  * n/a

### Expected Behavior
App relaunched after execute quitAndInstall

### Actual Behavior
App not relaunched

### To Reproduce

There is issue #25626 - but it closed and there no info how to get patched Squirrel into Electron 7.
@MarshallOfSound - please describe how to get https://github.com/Squirrel/Squirrel.Mac/pull/253 bundled into Electron 7 version

**Comment by MarshallOfSound** [comment]
Electron 7 is unsupported and the only version of electron that can viably support both Apple Silicon and macOS Big Sur is Electron 11

**Comment by olistic** [comment]
> Electron 7 is unsupported and the only version of electron that can viably support both Apple Silicon and macOS Big Sur is Electron 11

@MarshallOfSound Just double-checking, does this mean that versions of electron prior to v11 are not going to get the fixed Squirrel.Mac?
