### ISSUE TITLE
In Rdp session can not copy/paste image between local and RDP machine

### ISSUE THREAD

**Issue by bcburak** [electron/electron#25920]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
 3.0.10
* **Operating System:**
   Windows 10 (1803) 

### Expected Behavior
Should transfer images.

### Actual Behavior
I'm connecting my remote machine, by using loadURL method (**BrowserWindow.LoadUrl(url)**)
I can copy/paste texts between remote machine and my local computer. But when I try to copy an image, it does nothing.
Also when I click the PrintScreen button I can not take screenshot from remote machine. I tried to use clipboard library but it can not do anything

### To Reproduce
just do remote session using loadUrl with any windows machine

**Comment by baconbrad** [comment]
This appears to be a limitation of RDP itself. RDP has a file transfer implementation to allow files to be dragged/transmitted between explorer/desktop and allows the copy and paste of text. But if you try to copy and paste or drag images into Chrome, MS Word, MS Paint, or any application from the local machine to the RDP machine it is not possible. You'll have to first send the file to explorer/desktop on one machine and then send it to the Electron application.

**Comment by bcburak** [comment]
> This appears to be a limitation of RDP itself. RDP has a file transfer implementation to allow files to be dragged/transmitted between explorer/desktop and allows the copy and paste of text. But if you try to copy and paste or drag images into Chrome, MS Word, MS Paint, or any application from the local machine to the RDP machine it is not possible. You'll have to first send the file to explorer/desktop on one machine and then send it to the Electron application.

What do you mean "send the file to explorer/desktop on one machine and then send it to the Electron application."
Should I use file transfer between RDP client and local machine? Is it possible using Electron?

Btw other case that I wondered is; when I use CTRL +TAB combination in remote device I can change explorer tabs, but if I user ALT + TAB combination or "PrintSc" my local device is triggered. Do you think is it RDP issue also ?

Thanks

**Comment by baconbrad** [comment]
> What do you mean "send the file to explorer/desktop on one machine and then send it to the Electron application."
Should I use file transfer between RDP client and local machine? Is it possible using Electron?

Unless there is a method unbeknownst to me I mean you manually have to copy it over to the other machine your Electron app is running on for it to handle it with the normal copy/paste/drag behavior. Unfortunately you can't programically do this behavior with the official RPD client for Windows. But there are alternative RPD clients that may allow this behavior. Either way the functionality would have the be implemented into the RPD client itself and this will likely be a "can't fix" for Electron.

**Comment by ckerr** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is no longer supported, so this issue will be closed.

If you're still experiencing this issue on a supported version of Electron and would like this issue to remain open, please file a new issue with that version of Electron.

Thanks in advance! Your help is appreciated.
