### ISSUE TITLE
`nativeTheme` not receiving `updated` event respecting Linux system preference change

### ISSUE THREAD

**Issue by davidwinter** [electron/electron#25925]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * ~10.1.3~ 11.0.1
* **Operating System:**
  * Ubuntu 20.04 x64

### Expected Behavior

When switching "Window theme" preference between Light and Dark modes on Ubuntu, the `updated` event should be triggered for `nativeTheme`.

### Actual Behavior

The `updated` event is never triggered when alternating between window themes.

### To Reproduce

See: https://github.com/davidwinter/electron-native-theme/blob/master/main.js

```sh
$ git clone https://github.com/davidwinter/electron-native-theme.git
$ yarn
$ ./node_modules/.bin/electron main.js
```

### Screenshots

![image](https://user-images.githubusercontent.com/9681/95895482-a3cd9180-0d82-11eb-8ef2-a5871cb5bd06.png)

**Comment by ckerr** [comment]
I _think_ this is fixed as a side-effect of https://github.com/electron/electron/issues/23479

**Comment by davidwinter** [comment]
This is still broken with 11.0.1.

Example repo updated.

**Comment by shiftkey** [comment]
I'm seeing similar behaviour on Ubuntu 20.04 with Electron 11.1.1 while working with GitHub Desktop's Linux fork. I can put together a better repro but the short version:

 - changing from Yaru-light to Yaru-dark does update the default chrome of the app
 - querying from the console for `nativeTheme.shouldUseDarkColors` shows the correct value
 - but the `updated` event on `nativeTheme` doesn't fire, so the app content itself is unable to switch from light to dark as the OS changes

This limits us being able to emulate the "Automatically switch theme to match system theme" behaviour that macOS and Windows now allow us to do in the app.

**Comment by julian-fairfax** [comment]
Hopefully this can be resolved somehow. I use an extension to change my theme automatically depending on time of day, and Electron apps (most of my apps) use the system theme when launching, but as mentioned don't update it after the theme has been changed, and they require a relaunch.

**Comment by LEBATRUNG** [comment]
Tkanhs

**Comment by ffflorian** [comment]
Also doesn't work with 11.4.1 and 12.0.1, but seems to be fixed with 13.0.0-beta.7. :tada:

**Comment by julian-fairfax** [comment]
> Also doesn't work with 11.4.1 and 12.0.1, but seems to be fixed with 13.0.0-beta.7. 🎉

Is there any indication of when version 13 will be released? And will the electron apps I use have to each be individually updated by their developer?

**Comment by ffflorian** [comment]
@julian-fairfax
> Is there any indication of when version 13 will be released?

Electron 13 stable release is [scheduled](https://www.electronjs.org/docs/tutorial/electron-timelines) for 2021-05-25.

> And will the electron apps I use have to each be individually updated by their developer?

Yes.

**Comment by Slapbox** [comment]
Any hope for a backport on this fix, to at least `11.x`?

**Comment by Slapbox** [comment]
Anybody on the team know what PR may have resolved the issue for @ffflorian and whether it might be backport-able?

**Comment by nornagon** [comment]
Closing this as fixed, but feel free to continue discussing backports.

**Comment by aykevl** [comment]
Unfortunately, this doesn't appear to be working on KDE (current Arch Linux ARM / Asahi Linux, KDE Plasma 5.25.5). Most other applications do automatically update when the theme changes, including all tested KDE apps, Firefox, and Inkscape (GIMP and Chromium don't).
