### ISSUE TITLE
Exit code passed through app.exit gets truncated to an 8-bit integer on macOS

### ISSUE THREAD

**Issue by NinjaManatee** [electron/electron#25934]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.3
* **Operating System:**
  * macOS 10.15.6
* **Last Known Working Electron version:**
  * none

### Expected Behavior
When exiting an Electron application using `app.exit(exitCode)`, the application should close with the provided exit code. 

### Actual Behavior
On Windows 10, the Electron application closes with the provided exit code.
On macOS, the Electron application truncates the exit code to an 8-bit integer before closing (e.g. 0-255 exit with the provided number, 256 exits with 0, 3375 exits with 47).

### To Reproduce
1. On macOS, create a new Electron Fiddle. 
1. Replace the provided `'window-all-closed'` handler with:
    ```js
    app.on('window-all-closed', function () {
      app.exit(3375)
    })
    ```
1. Run Electron Fiddle
1. Close open windows
1. Observe that Electron exits with code 47 instead of 3375

**Comment by nornagon** [comment]
posix exit codes are 8 bits.
