### ISSUE TITLE
Cannot  step through in a debugger by testing builder

### ISSUE THREAD

**Issue by bigben0123** [electron/electron#25935]
When I use electron 7 with debug build, debug locally is ok. However after uprading to 9, only testing builds is left. 
Testing builds are optimized so there's a ton of inlined code that makes it really hard to step through in a debugger. 

![image](https://user-images.githubusercontent.com/11641180/95936171-8e4e7b00-0e07-11eb-954a-8864b93eeb53.png)

If set is_debug true,  electron cannot build successfully. So  there is no way to debug locally?

**Comment by nornagon** [comment]
Give `symbol_level = 2` a try

**Comment by bigben0123** [comment]
1, build like this
```
import("all.gn")
is_debug = true
is_component_build = false
is_component_ffmpeg = true
is_official_build = false
dcheck_always_on = true
symbol_level = 2
```
Build failed:
```
ninja: Entering directory `out/mydebug'
[1/1] Regenerating ninja files
FAILED: build.ninja
../../buildtools/win/gn.exe --root=../.. -q gen .
ERROR at //build/config/compiler/compiler.gni:267:3: Assertion failed.
  assert(symbol_level != 2 || current_toolchain != default_toolchain ||
  ^-----
Can't do non-component debug builds at symbol_level=2
See //BUILD.gn:11:1: whence it was imported.
import("//build/config/compiler/compiler.gni")
^--------------------------------------------
ninja: error: rebuilding 'build.ninja': subcommand failed
```
2, build successfully with is_debug = false, but still cannot step debug.

Bug should not be closed.

same with bug #24989

**Comment by bigben0123** [comment]
Modify the file in build/config/compiler/compiler.gni:
Changed from:
forbid_non_component_debug_builds = build_with_chromium
to
forbid_non_component_debug_builds = false

Skip the check.
