### ISSUE TITLE
Disable native drop icon on Mac OS Tray

### ISSUE THREAD

**Issue by alexpelan** [electron/electron#25942]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

When I drag a file over the Tray in Mac OS, I see a green plus sign, indicating that dropping the file will cause something to happen. Because we don't support dragging files into our application, we would like to disable this icon, which is misleading. I cannot seem to get a screenshot of this icon, I think taking a screenshot makes the dragged file lose focus. 

### Proposed Solution

A way to disable this icon via a configuration flag. Perhaps this flag could disable all drag and drop related functionality in addition to the icon. 

### Alternatives Considered

I tried to use the existing events like `drag-enter` and `drop-files` to prevent default but the icon still appears. We are able to have our application just ignore dragged files using these events but not to disable the icon.

**Comment by vedkribhu** [comment]
Any update here?

**Comment by jviotti** [comment]
See https://stackoverflow.com/a/24072081
