### ISSUE TITLE
Add support to pin an app to taskbar using electron API

### ISSUE THREAD

**Issue by henriquemc** [electron/electron#25955]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

I'm trying to create an electron app (exported as appx) with one button that pins the app in the taskbar.

### Proposed Solution

const { TaskBar } = require('electron') 
TaskBar.requestPin(); //call windows dialog 
TaskBar.isPinned(); // if app is pinned
TaskBar.isPinSupported(;) //
TaskBar.flashFrame(flag); //current win.flashFrame(flag)

### Alternatives Considered

Try to use @nodert-win10-rs4/windows.ui.shell

```
 const tm = require('@nodert-win10-rs4/windows.ui.shell').TaskbarManager;
  const taskbarManager = tm.getDefault();

  taskbarManager.requestPinCurrentAppAsync((err, result) => {
    if (err) {
      console.log(err)
      return
    }
  
    console.log(result)
  });
```

**Comment by MarshallOfSound** [comment]
> Try to use @nodert-win10-rs4/windows.ui.shell

This IMO is a better solution, Electron can't add APIs for everything and the winrt native modules unlock this quite easily

**Comment by henriquemc** [comment]
The electron has already API for the taskbar, however, lacks the functionality of to pin. Using node-rt  I'm having an interface not registered error. I think it's because they need to run a UI thread. Has anyone ever experienced this?  @MarshallOfSound

**Comment by gaodeng** [comment]
NodeRT doesn’t seem to be maintained for a long time  https://github.com/electron/electron/issues/15982
