### ISSUE TITLE
session.defaultSession.webRequest.onBeforeSendHeaders

### ISSUE THREAD

**Issue by mapleby** [electron/electron#25957]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.3
* **Operating System:**
  * windows10(1909)
* **Last Known Working Electron version:**
  * 

### Expected Behavior

Listen for requests and change request header information

### Actual Behavior

Failed to use seisson instance. The request header operation cannot be changed for a custom protocol.
### To Reproduce

const { app, BrowserWindow, session } = require("electron");
const { RouterServer } = require("../dist/index");

function createWindow() {
    const win = new BrowserWindow({
        width: 800,
        height: 600,
        webPreferences: {
            nodeIntegration: true
        }
    })

    const filter = {
        urls: ['https://*.github.com/*', '*://electron.github.io']
    }

    session.defaultSession.webRequest.onBeforeSendHeaders(filter, (details, callback) => {
        details.requestHeaders['User-Agent'] = 'MyAgent'
        callback({ requestHeaders: details.requestHeaders })
    })

    //win.loadFile('index.html')
    win.loadURL("http://github.com")
    win.webContents.openDevTools();

}

app.whenReady().then(createWindow)

app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit()
    }
});

### Screenshots

![131](https://user-images.githubusercontent.com/45815225/96075630-0e471480-0ede-11eb-9878-06be22d85fbb.png)

**Comment by bigben0123** [comment]
> '*://electron.github.io'

You need to change it into  '*://electron.github.io/'
It will work ok.

**Comment by mapleby** [comment]
TThank you!

发送自 Windows 10 版邮件应用

发件人: bigben0123
发送时间: 2020年10月22日 15:16
收件人: electron/electron
抄送: 枫沐纭; Author
主题: Re: [electron/electron]session.defaultSession.webRequest.onBeforeSendHeaders (#25957)

'*://electron.github.io'
You need to change it into '*://electron.github.io/'
It will work ok.
