### ISSUE TITLE
Support Tray.setTitle on Linux

### ISSUE THREAD

**Issue by johannesjo** [electron/electron#25953]
A while back I already opened up an issue about this https://github.com/electron/electron/issues/4742

I am curious if anything changed. I recently read somewhere that electron changed how it deals with indicators.

Also here is a [link to the Chromium Issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1016125&can=2&q=Tray%20Title&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified)

**Comment by MarshallOfSound** [comment]
We still use libappindicator, so nothing has changed here
