### ISSUE TITLE
how to enable CORS when webSecurity=true

### ISSUE THREAD

**Issue by ioriandy4** [electron/electron#25962]
how to enable CORS when webSecurity=true?

webPreferences: {
      nodeIntegration: true,
      webSecurity: true
      webviewTag: true
    },

**Comment by ioriandy4** [comment]
help!

**Comment by vladimiry** [comment]
`webRequest.onBeforeSendHeaders` + `webRequest.onHeadersReceived`

**Comment by ioriandy4** [comment]
> `webRequest.onBeforeSendHeaders` + `webRequest.onHeadersReceived`

I don't understant it , can you tell me more information? thank you

**Comment by vladimiry** [comment]
At this time I'm not ready to share anything but a way to solve the issue which I did in previous message.

**Comment by shuaiqichengzi** [comment]
> > `webRequest.onBeforeSendHeaders` + `webRequest.onHeadersReceived`
> 
> I don't understant it , can you tell me more information? thank you

you can try:             
           res.header("Access-Control-Allow-Credentials", true);       
            res.header("Access-Control-Allow-Origin", req.headers["origin"] || "*");
            res.header("Access-Control-Allow-Headers", "X-Requested-With");
            res.header("Access-Control-Allow-Methods", "PUT,POST,GET,DELETE,OPTIONS");
            res.header("Content-Type", "application/json;charset=utf-8");

**Comment by ckerr** [comment]
GitHub issues are for feature requests and bug reports. Please visit https://github.com/electron/electron#community for a list of resources that are better oriented for questions and help. Thank you!

**NB:** We've just added a Discord server for help & community discussion! It's not listed in the above link yet (there is a [PR](https://github.com/electron/electron/pull/26048) that will fix that), you can join now at https://discord.com/invite/electron !

**Comment by ashe2333** [comment]
> `webRequest.onBeforeSendHeaders` + `webRequest.onHeadersReceived` (you would use these handlers to manipulate CORS-related headers).

webRequest.onHeadersReceived is not work
