### ISSUE TITLE
Extending BrowserView "erases" class functions

### ISSUE THREAD

**Issue by lmancel** [electron/electron#25965]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
* **Electron Version:**
  * 11.0.0-beta.12
* **Operating System:**
  * macOS 10.15.2
* **Last Known Working Electron version:**
  * 10.1.3

Hello !

We have encountered a really strange issue when working with BrowserView in one of our projects.
When creating a class that extends BrowserView, every function declared on the class "disappears" from the instantiated object.

### Expected Behavior
Be able to use the functions declared on the class that extends BrowserView.

### Actual Behavior
Not a single function exists on the instantiated object.

### To Reproduce
Create a class that extends BrowserView and attempt to use one of its functions.

Sample code can be found here:
https://gist.github.com/lmancel/987ccb2ac6416954770d518a879fa35f

Complete sample project here:
[electron-browserview.zip](https://github.com/electron/electron/files/5384174/electron-browserview.zip)

### Screenshots
![Screenshot 2020-10-15 at 12 31 50](https://user-images.githubusercontent.com/5877409/96112486-f7ef8780-0ee2-11eb-8bf4-f1ea1af553ea.png)

**Comment by nornagon** [comment]
We don't support extending Electron's built-in classes.

**Comment by lmancel** [comment]
Hmmmmm alright, so the fact that everything was working fine until v10.1.3 is mere coincidence then...
