### ISSUE TITLE
camera & audio permission mistake

### ISSUE THREAD

**Issue by javaxiu** [electron/electron#25966]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**

9.3.2 and above

**Operating System:**

windows10

**Last Known Working Electron version:**

  1.x

### Expected Behavior
- shutdown micorophone permission in windows10 system setting,

- open a Browser window, and load some html page, which use this code to open camera 

`window.navigator.mediaDevices.getUserMedia({{ video: true, audio: false }});`

it was suppose to work normally open camera only

### Actual Behavior

acually, i got this error ` NotReadableError: Could not start video source`.
but what if i open the microphone agan in system setting, it work as expect

### To Reproduce

- shutdown micorophone permission in windows10 system setting,

- open an BrowserWindow with any version of Electron

- and load this page [https://dev.g.alicdn.com/it-service/media_test/0.0.1/index.html](https://dev.g.alicdn.com/it-service/media_test/0.0.1/index.html) with this BrowserWindow, click Check Camera button

- this page will show you `NotReadableError: Could not start video source`. 

### Screenshots
![image](https://user-images.githubusercontent.com/4281225/96113009-14f17e00-0f16-11eb-80ad-73d1bb364fd4.png)

### Additional Information
that is weird, i turn off microphone permission, but why is that  block camera permission?

https://stackoverflow.com/questions/60837628/js-video-domexception-could-not-start-video-source

**Comment by HyperClockUp** [comment]
same problem
