### ISSUE TITLE
electron crash when using setTimeout on node vm

### ISSUE THREAD

**Issue by CaiHuan** [electron/electron#25964]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
 9.3.1
* **Operating System:**
 Windows 10 (1904)

### Expected Behavior
 print error on dev devtools 

### Actual Behavior
 electron crash
### To Reproduce

1: git clone https://github.com/electron/electron-quick-start
2: cd electron-quick-start
3: Install dependencies
4: npm install
5: add nodeintegration=true webPreferences(main.js)
``` javascript
const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      nodeIntegration: true,
      sandbox: false,
    }
  })
```
5: add script to renderer.js
``` javascript
const vm = require('vm');
timers = require('timers');
var scriptData = "
function print() {\
  console.log(ss);\
}\
setTimeout(print, 1000);\
";
const script = new vm.Script(scriptData);

const sandbox = {setTimeout: timers.setTimeout, console: console};

const contetifiedSandbox = vm.createContext(sandbox);

const result = script.runInContext(contetifiedSandbox);
```

### Screenshots
![image](https://user-images.githubusercontent.com/3890047/96102550-3ac45600-0f09-11eb-9f7f-a4f612c07fa1.png)

### Additional Information

1: pass web setTimeout also crash (check context world fail)
2: console.log print undefined object

**Comment by CaiHuan** [comment]
![image](https://user-images.githubusercontent.com/3890047/96144402-b688c780-0f36-11eb-850e-71e4708d6aed.png)
if setTimeout callback post exception，the async stack will not pop async id.
 emitAfter(asyncId) must be the final key word

**Comment by garethbaars** [comment]
Having same issue. Electron 10.1.4

**Comment by CaiHuan** [comment]
> Having same issue. Electron 10.1.4

nodejs bug for all electron version

**Comment by nornagon** [comment]
Unfortunately, we don't support using the `vm` module in the renderer. Node and Blink have incompatible ideas about how fresh contexts should work, and it's infeasible for us to mesh those ideas together.

Eventually, [ES Realms](https://github.com/tc39/proposal-realms) will be the way to do `vm`-like things in the renderer.
