### ISSUE TITLE
Port is invalid

### ISSUE THREAD

**Issue by RGSevOne** [electron/electron#25968]
The project only accept port 1024 or over, not allowing ports like 80 or 443. The message issued is The port is invalid.

![image](https://user-images.githubusercontent.com/63416146/96162499-84646f00-0f10-11eb-9346-e5a4d1161c86.png)

![image](https://user-images.githubusercontent.com/63416146/96162532-8dedd700-0f10-11eb-8b3f-a99bbe214a16.png)

**Comment by nornagon** [comment]
This issue tracker is for bugs with Electron. You'll have to report that bug to whatever app it is you're using.
