### ISSUE TITLE
tray.setToolTip doesn't work on Linux with 9.0.3-10.1.3 versions

### ISSUE THREAD

**Issue by irevenko** [electron/electron#25976]
### Issue Details

* **Electron Version:**
  * 10.1.3
* **Operating System:**
  * Linux Kubuntu 20.04.1 KDE
* **Last Known Working Electron version:**
  * 9.0.2 (checked all versions)

### Expected Behavior
When hover on icon expect to display ```setToolTip``` text
<img src="https://i.imgur.com/8PZEdni.png">

### Actual Behavior
When hover on icon displays ```electron``` instance instead of ```setToolTip``` text
<img src="https://imgur.com/oFtC9Ne.png">

### To Reproduce
```javascript
const { app, Menu, Tray } = require('electron');
const path = require('path');

let tray = null;

app.on('ready', () => {
  const contextMenu = Menu.buildFromTemplate([
    { label: 'Emojis' },
    { label: 'Quit', click: () => { app.quit() } },
  ]);

  tray = new Tray(path.join(__dirname, '123.png'));
  tray.setToolTip('Emoji Picker');
  tray.setContextMenu(contextMenu);
  
});
```

### Additional Information
The LATEST working version is ```9.0.2```. Tried ```11 latest beta``` Also doesn't work

**Comment by erik-404err** [comment]
Having the same issue. Even though the [electron docks](https://www.electronjs.org/docs/api/tray#traysetpressedimageimage-macos) state that it should work on Linux (no MacOS or Windows tag)
Im on Linux Mint 20 and electron 11.1.1. After building with electron-builder for Windows, `settooltip()` works as expected, building for Linux it just shows the App Name (before building it just shows 'electron')
