### ISSUE TITLE
Apple rejected build: The experience that your app provides is not sufficiently different from a web browsing experience.

### ISSUE THREAD

**Issue by ahmadwaliesipick** [electron/electron#25987]
Apple rejected build with below reason.
I have used many native features like;
1- Tray
2- In-App purchase
3- Shortcut keys
4- Dock
5- Welcome screen
6- Notifications
and more

Guideline 4.2.2 - Design

The experience that your app provides is not sufficiently different from a web browsing experience.

We advise incorporating additional substantive native macOS features into your application to better differentiate it from the Safari experience.

any suggestion to resolve this issue?

**Comment by MarshallOfSound** [comment]
> any suggestion to resolve this issue?

This is for you to deal with Apple.  I'd suggest filing an appeal and pointing out the list of feature you referenced here.  We have no say / power over the mac app store 🤷
