### ISSUE TITLE
DevTools Extensions list

### ISSUE THREAD

**Issue by etiktin** [electron/electron#2598]
I think it would be helpful if we would maintain a list of devtools extensions that are known to work with electron and a list of extensions that are known NOT to work with electron.

The point of this is to save time for other developers.

I just wasted half and hour, trying to install `AngularJS Batarang` and `ng-inspector` to no avail (altough `addDevToolsExtension` didn't return any error). I don't know if it used to work and now it doesn't (which might be an electron bug), or if it never worked. From going over some other issues it also seems that `react-devtools` and `Ember Inspector` are not working.

What do you think?
Do you have any helpful extensions to recommend?

Related issues: #2404, #915, #250

**Comment by OlsonDev** [comment]
The only extension I've ever tried installing is [`CSS Diff`](https://github.com/kdzwinel/CSS-Diff) but it didn't seem to work. `addDevToolsExtension` returned the string `CSS Diff` so I figured it did something but the panel didn't show up in dev tools, even if I restarted dev tools/my app.

**Comment by jlord** [comment]
This could be definitely added to the docs :+1:

**Comment by etiktin** [comment]
@OlsonDev, that's exactly what happened to me. The fact that `addDevToolsExtension` returns the extension name instead of an error, is really confusing.

// cc @deepak1556

**Comment by etiktin** [comment]
@jlord, sure. We'll add it to the docs, once we get some recommendations (so far all the posts were about extensions that don't work).

**Comment by mrzmyr** [comment]
Same problem over here.

**Comment by etiktin** [comment]
Does anyone know of extensions that actually work in Electron?

**Comment by FliiFe** [comment]
> @OlsonDev, that's exactly what happened to me. The fact that addDevToolsExtension returns the extension name instead of an error, is really confusing.
> 
> // cc @deepak1556

Does this means if it returns the extension name then it was unsuccessful ?

**Comment by etiktin** [comment]
No. I meant that it returns the name even if the extension won't really work since we don't support some of it's APIs. It would be a better user experience if it would scan the extension manifest and figure out if it uses stuff that we don't currently support, and throw an appropriate error (e.g. "Failed to register extension. Reason: The 'chrome.runtime.connect' API is not currently supported.").

**Comment by FliiFe** [comment]
:+1:

**Comment by darwin** [comment]
> I think it would be helpful if we would maintain a list of devtools extensions that are known to work with electron and a list of extensions that are known NOT to work with electron

With such pace how blink, devtools, chrome and electron are moving? On all platforms? Under different configurations? Frankly, this is mission impossible. The list would be outdated the day it was published.

I would recommend referring docs to individual devtools extensions. If they don't mention Electron compatibility, assume it is not compatible. If you try and it works, it is just a pure luck :)

**Comment by etiktin** [comment]
@darwin, I think you are over estimating the amount of devtools extensions and their popularity. The number of devtools extensions that people are actually using (or trying to use) is pretty low. If you search the issues, you'll see most just want to use some framework inspector (AngularJS Batarang, React Developer Tools or Ember Inspector) and currently all of them are not working (see #915).

Lists are helpful (take for example the [awesome](https://github.com/sindresorhus/awesome) lists project). The list doesn't have to contain information about every single extension, but if they do contain it for something that you are interested in, it can save you time. A list might also help you discover some cool extensions you didn't know existed.

It would be great if Extension authors would mention their support for Electron in their docs, but currently they don't. It's also customary to say what you support and not what you don't support, so I doubt all the framework inspectors will want to currently state in their docs that they don't support Electron.

**Comment by Jax0rz** [comment]
Maybe no extension works,I tried React devtool,Vue devtool,Angular devtool,but no one works
