### ISSUE TITLE
The electron v7.3.3 app.setBadgeCount is not working!

### ISSUE THREAD

**Issue by yyccQQu** [electron/electron#26000]
### Issue Details

* **Electron Version:**
  *  v7.3.3 
* **Operating System:**
  *  macOS 10.15.4 (19E287)
* **Last Known Working Electron version:**
  * don`t know

-- the code 
-- The comment method also doesn’t work
```
import {
  app
} from "electron";

mainWindow.on('blur', () => {
    if (process.platform === 'darwin') {
      app.dock.setBadge('5');
      app.setBadgeCount(5);
      // const badgeString = app.dock.getBadge();
      // console.log(badgeString,'badgeString')

      // if (badgeString === '') {
      //   app.dock.setBadge('1');
      //   console.log(badgeString,'2333badgeString')
      // } else {
      //   app.dock.setBadge((parseInt(badgeString) + 1).toString());
      // }
    }
}

```
### Expected Behavior

![1](https://user-images.githubusercontent.com/32674176/96297000-42ffbc80-1001-11eb-8828-435f19b85ade.png)

**Comment by ckerr** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is no longer supported, so this issue will be closed.

If you're still experiencing this issue on a supported version of Electron and would like this issue to remain open, please file a new issue with that version of Electron.

Thanks in advance! Your help is appreciated.
