### ISSUE TITLE
Apple continuously reject app with reason; The experience that your app provides is not sufficiently different from a web browsing experience.

### ISSUE THREAD

**Issue by ahmadwaliesipick** [electron/electron#26027]
The experience that your app provides is not sufficiently different from a web browsing experience.

Please note that the additional items that your have added (i.e. welcome screen, Dock options, Menu Bar Extra, etc.) are not considered core features that differentiate the app from the Safari experience.

Next Steps

While your app content may differ from your web site, the experience it provides does not differ significantly from the general experience of using Safari.

For app design information, see the macOS Human Interface Guidelines. The Human Interface Guidelines provide in-depth guidance on the characteristics of a great Mac OS X app and describe appropriate technologies and interface elements of a Mac OS X app.

You may also want to review Programming with Objective-C, a guide to getting started with the Objective-C programming language.

I am using angular material theme and using lot of native features like notifications, icon badge, welcome screen, In-APP purchase, Dock, Menu bar etc. But i am not clear why apple is continuously reject, they want to me to change the whole app design? Anyone has any experience with this issue?

**Comment by ckerr** [comment]
GitHub issues are for feature requests and bug reports. Please visit https://github.com/electron/electron#community for a list of resources that are better oriented for questions and help. Thank you!

**NB:** We've just added a Discord server for help & community discussion! It's not listed in the above link yet (there is a [PR](https://github.com/electron/electron/pull/26048) that will fix that), you can join now at https://discord.com/invite/electron !
