### ISSUE TITLE
Backdrop-filter property on HTML elements on top of transparent BrowserWindow

### ISSUE THREAD

**Issue by AramAnd** [electron/electron#26029]
### Issue Details

* **Electron Version:**
  * v10.1.2
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  
### Expected Behavior
I have multiple HTML elements which have backdrop-filter: blur(5px) property on top of transparent BrowserWindow and the expected behavior is to blur the desktop content, whatever is being seen through.

### Actual Behavior
When I add backdrop-filter: blur(5px) property to elements and it also adds black background to it

### To Reproduce
1. adding backdrop-filter: blur(5px) to any element
2. create BrowserWindow with transparent: true property.
3. check the element background effect

### Screenshots
![image](https://user-images.githubusercontent.com/7838312/96429154-ab24ed00-1211-11eb-8d3b-95f928f62ca0.png)
![image](https://user-images.githubusercontent.com/7838312/96429179-b37d2800-1211-11eb-848e-c6f2e085df23.png)
![image](https://user-images.githubusercontent.com/7838312/96429303-dad3f500-1211-11eb-8cdc-bdd41a9ee7ac.png)

### Additional info
When i use the same property in the chrome browser, it works ok.

**Comment by ckerr** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Would it be possible for you to fork [electron-quick-start](https://github.com/electron/electron-quick-start) for a small app that reproduces the issue by itself? That would be faster than me transcribing your screenshot into a test case.

I'm adding the `blocked/needs-repro` label for this reason. After you've responded, please link to the test case (e.g. in a [gist](https://gist.github.com/) or a forked repo) followup comment.

Thanks in advance! Your help is appreciated.

**Comment by AramAnd** [comment]
Thank you @ckerr for the reply. Please see below the forked repo link.

https://github.com/AramAnd/electron-quick-start

If you check the application, you will see the issue with BOX-3 and BOX-4. Please let me know if you need more clarification.

**Comment by AramAnd** [comment]
@ckerr is the above provided info ok or you need more info ?
