### ISSUE TITLE
The empty folder Dictionaries is always created in %Appata%\Electron\

### ISSUE THREAD

**Issue by gdavidkov** [electron/electron#26039]
Hello,
I want to change the per-user application data directory, which by default points to %APPDATA% on Windows. According to the documentation, I've tried with app.setPath("appData", "c:\\myAppData") and also with the same path but the other path's name "userData" but without a result. All Electron's files are moved into the new path except the folder Dictionaries, which is created in %AppData%/Electron

### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.3.1 and 10
* **Operating System:**
  * Windows 10 10.0.19041.572

### Expected Behavior
Not to create any folder outside of the defined path.

### Actual Behavior
The folder is created in %AppData%\Electron\

### To Reproduce
Just override the userData and appData path
Make sure that there isn't a folder in %AppData% called Electron

**Comment by ckerr** [comment]
Yep, this happens on Linux too. I'm seeing _many_ empty `~/.config/$foo/Dictionaries/` folders on my Linux box.

**Comment by vladimiry** [comment]
#22995 might be a related issue.

**Comment by probablykasper** [comment]
The `Dictionaries` folder seems to be created in both the custom `userData` folder and in `${appData}/Electron`

**Comment by probablykasper** [comment]
On macOS, I tried setting my `userData` to `${appData}/${app.name}/Electron Data`. It created `${appData}/Electron/Dictionaries`, `${appData}/${app.name}/Dictionaries` and `${appData}/${app.name}/Electron Data/Dictionaries`.

After building the app, it did not create `${appData}/Electron/Dictionaries`, but it did create the other two.

**Comment by quanglam2807** [comment]
It seems like `${appData}/${app.name}/Dictionaries` is always created, regardless of what `userData` is

**Comment by cdetamble** [comment]
> 
> 
> It seems like `${appData}/${app.name}/Dictionaries` is always created, regardless of what `userData` is

Noticed the same behavior today.

**Comment by MatejKafka** [comment]
I think the path setup code is here: https://github.com/electron/electron/blob/e46446e7e4b0b435cd3764cd0913d2fb5b52f98a/shell/browser/electron_browser_context.cc#L124

I don't know about about electron internals to dive into this, but from the look of things, it shouldn't be too hard to fix.

**Comment by grunde** [comment]
happens on version 11.4.6 too

**Comment by nornagon** [comment]
#29649 might fix this, does it happen in v15.0.0-nightly.20210615 or newer?

**Comment by asv7c2** [comment]
I have checked v15 version, no empty electron/dictionaries is created. Looks like fixed.

**Comment by nornagon** [comment]
Great, I hope to backport that fix to older versions too. I'm going to mark this fixed.
