### ISSUE TITLE
did-change-theme-color tests are flaky on WOA

### ISSUE THREAD

**Issue by jkleinsc** [electron/electron#26045]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * master
* **Operating System:**
  * Windows on ARM
* **Last Known Working Electron version:**
  * ?

### Expected Behavior

`webContents module did-change-theme-color event is triggered with correct theme color` and `<webview> tag did-change-theme-color event emits when theme color changes` tests should pass on Windows on ARM.

### Actual Behavior

The tests timeout, eg:
```
not ok 397 <webview> tag did-change-theme-color event emits when theme color changes
  Error: Timeout of 180000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\vsts-agent-win-x86-2.166.4\_work\1\s\src\electron\spec\webview-spec.js)
```
and 
```
not ok 1344 webContents module did-change-theme-color event is triggered with correct theme color
  Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\vsts-agent-win-x86-2.166.4\_work\1\s\src\electron\spec-main\api-web-contents-spec.ts)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

### To Reproduce

Run the did-change-theme-color tests on WOA.

### Additional Information

See https://github.visualstudio.com/electron/_test/analytics?definitionId=41&contextType=build for statistics on the flaky failures

**Comment by ckerr** [comment]
Data point: it doesn't seem to be exclusive to WOA. For example I got the same test failure in https://ci.appveyor.com/project/electron-bot/electron-ljo26/builds/35900922 for a docs change PR :slightly_smiling_face:

**Comment by ckerr** [comment]
I did a little bit of testing on this. Disclaimer: I found it pretty easy to reproduce on an Ubuntu 20.04 box so this may or may not be the same issue that's triggering the WOA failures.

It looks like everything is going fine until we reach `WebContentsImpl::OnThemeColorChanged` in [content/browser/web_contents/web_contents_impl.cc](https://source.chromium.org/chromium/chromium/src/+/master:content/browser/web_contents/web_contents_impl.cc;drc=22e394d113f4d5daf86baacaefe56bfadb841213;l=5381) where we have

```cc
void WebContentsImpl::OnThemeColorChanged(RenderViewHostImpl* source) {
  OPTIONAL_TRACE_EVENT1("content", "WebContentsImpl::OnThemeColorChanged",
                        "render_view_host", source);
  if (source->did_first_visually_non_empty_paint() &&
      last_sent_theme_color_ != source->theme_color()) {
    observers_.ForEachObserver([&](WebContentsObserver* observer) {
      observer->DidChangeThemeColor();
    });
    last_sent_theme_color_ = source->theme_color();
  }
}
```

The method `source->did_first_visually_non_empty_paint()` is returning false, which  prevents the observers from being told that the theme color has changed.

Tested with master 554ad93d45beb8f565b788afb3e3e27c74c1a144 on Ubuntu 20.04.
