### ISSUE TITLE
Session wide preload script

### ISSUE THREAD

**Issue by zcbenz** [electron/electron#2605]
As per #2522, it would be good to allow setting preload script for all pages under the same session, so child windows opened by `window.open` can also be managed.

**Comment by inca** [comment]
Is there any work planned for this? I'm interested in session-wide preload scripts particularly because of #5115, having this implemented would allow one to interact with iframes and child windows without disabling web security.

**Comment by codebytere** [comment]
Closing on merge of https://github.com/electron/electron/pull/10430

**Comment by iffy** [comment]
@codebytere so is 10430 in a released version of electron?

**Comment by carsonwright** [comment]
@codebytere based on the creators of #10430 it appears that they do not intend to create support for iframes all others will be supported but not iframes.
