### ISSUE TITLE
setImmediate crash

### ISSUE THREAD

**Issue by hxkuc** [electron/electron#26055]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
8-,9-,10-
* **Operating System:**
  * 
windows
* **Last Known Working Electron version:**
  * 
no

### Expected Behavior

console error

### Actual Behavior

crash

### To Reproduce

example code 

```
setImmediate(function () {
  aaa
})
```
Expected Behavior:
aaa is not defined

Actual Behavior:
crashed

**Comment by ckerr** [comment]
gist of @hxkuc's test case: https://gist.github.com/ckerr/a0bbfb980262a38d4f6a5957d09720cd

**Comment by ckerr** [comment]
I'm not able to reproduce this with the gist above when testing with Electron v10.1.4 on Windows 10 and Linux: the script errors out with the parse error, but Electron does not itself crash.

If you're able to reproduce this crash, could you provide more information on the crash itself and how to reproduce it? For example a crash backtrace would be helpful, as would a test case that reliably crashes.

**Comment by hxkuc** [comment]
> I'm not able to reproduce this with the gist above when testing with Electron v10.1.4 on Windows 10 and Linux: the script errors out with the parse error, but Electron does not itself crash.
> 
> If you're able to reproduce this crash, could you provide more information on the crash itself and how to reproduce it? For example a crash backtrace would be helpful, as would a test case that reliably crashes.

i use your example and it crashed
![image](https://user-images.githubusercontent.com/17510186/96694366-f9c1bb00-13ba-11eb-9424-daf205896045.png)

**Comment by codebytere** [comment]
@hxkuc I also cannot reproduce this. Can you please provide specific version numbers you're seeing this with?

**Comment by hxkuc** [comment]
i don't know why you can't reproduce, i think it is very easy to reproduce, just use `electron-quick-start` and `npm i electron@v10.1.4`
openDevtools in the console write this 
```
setImmediate(function () {aaa})
```

**Comment by ckerr** [comment]
<img width="912" alt="Screen Shot 2020-10-22 at 2 35 27 PM" src="https://user-images.githubusercontent.com/70381/96921410-12da7280-1474-11eb-9d88-0c98cb3832e3.png">

**Comment by ckerr** [comment]
![2020-10-22T14:26:13-Screenshot-665x350](https://user-images.githubusercontent.com/70381/96921492-3a313f80-1474-11eb-8d32-f6517f1ee554.png)

**Comment by ckerr** [comment]
> i don't know why you can't reproduce, i think it is very easy to reproduce, just use `electron-quick-start` and `npm i electron@v10.1.4`

Thanks for this -- the recipe is straightforward and fast to test! Unfortunately there seems to be some other factor going on here that the three of us aren't seeing, since I'm still not able to reproduce the issue (screenshots above with macOS and Ubuntu). :thinking: @hxkuc could you paste that full stack as text here?

**Comment by hxkuc** [comment]
@ckerr  
![image](https://user-images.githubusercontent.com/17510186/96961419-31ee0880-1537-11eb-9828-1fb02650d54d.png)
![image](https://user-images.githubusercontent.com/17510186/96961448-429e7e80-1537-11eb-8c3c-147826224641.png)
![image](https://user-images.githubusercontent.com/17510186/96961481-55b14e80-1537-11eb-8f38-c2b291c6c3d2.png)
![image](https://user-images.githubusercontent.com/17510186/96961503-682b8800-1537-11eb-8960-8180cb167112.png)
![image](https://user-images.githubusercontent.com/17510186/96961669-bccf0300-1537-11eb-9d8b-f24884c938b4.png)

**Comment by hxkuc** [comment]
$ npm start

> electron-quick-start@1.0.0 start D:\User\Desktop\electron-quick-start
> electron .


[18556:1023/135856.545:VERBOSE1:CONSOLE(31)] "Main._createAppUI: 19.716064453125
 ms", source: devtools://devtools/bundled/main/main.js (31)
[18556:1023/135856.740:VERBOSE1:CONSOLE(31)] "Main._showAppUI: 16.81591796875 ms
", source: devtools://devtools/bundled/main/main.js (31)
[18556:1023/135856.741:VERBOSE1:CONSOLE(31)] "Main._initializeTarget: 7.89697265
625 ms", source: devtools://devtools/bundled/main/main.js (31)
[18556:1023/135856.796:VERBOSE1:CONSOLE(31)] "Main._lateInitialization: 1.347656
25 ms", source: devtools://devtools/bundled/main/main.js (31)
[18556:1023/135910.323:INFO:CONSOLE(1)] "Uncaught ReferenceError: aaa is not def
ined", source:  (1)
Error: async hook stack has become corrupted (actual: 3, expected: 0)
 1: 00007FF6B9174C45 public: void __cdecl node::InternalCallbackScope::Close(voi
d) __ptr64+613
 2: 00007FF6B9174A82 public: void __cdecl node::InternalCallbackScope::Close(voi
d) __ptr64+162
 3: 00007FF6B9174D85 public: void __cdecl node::InternalCallbackScope::Close(voi
d) __ptr64+933
 4: 00007FF6B9175205 class v8::MaybeLocal<class v8::Value> __cdecl node::MakeCal
lback(class v8::Isolate * __ptr64,class v8::Local<class v8::Object>,class v8::Lo
cal<class v8::Function>,int,class v8::Local<class v8::Value> * __ptr64,struct no
de::async_context)+229
 5: 00007FF6B918CCC8 void __cdecl node::EmitAsyncDestroy(class node::Environment
 * __ptr64,struct node::async_context)+84568
 6: 00007FF6B9F27FD6 uv_check_stop+150
 7: 00007FF6B91C4411 uv_run+993
 8: 00007FF6B64F9FD1 public: virtual enum v8::OutputStream::WriteResult __cdecl
v8::OutputStream::WriteHeapStatsChunk(struct v8::HeapStatsUpdate * __ptr64,int)
__ptr64+17361
 9: 00007FF6B895BCBC uv_mutex_unlock+2521420
10: 00007FF6B920BCE4 uv_gettimeofday+278804
11: 00007FF6B920B9C8 uv_gettimeofday+278008
12: 00007FF6B91FC23B uv_gettimeofday+214635
13: 00007FF6B920C2DE uv_gettimeofday+280334
14: 00007FF6B8945B6C uv_mutex_unlock+2430972
15: 00007FF6B908B994 IsSandboxedProcess+2252532
16: 00007FF6B7D382E1 public: class std::__1::unique_ptr<class v8_inspector::Stri
ngBuffer,struct std::__1::default_delete<class v8_inspector::StringBuffer> > __c
decl v8_inspector::V8StackTraceId::ToString(void) __ptr64+5677153
17: 00007FF6B8ECBB0B IsSandboxedProcess+417899
18: 00007FF6B6FCCDEE public: unsigned int __cdecl v8::CpuProfilingOptions::max_s
amples(void)const __ptr64+784398
19: 00007FF6B63A149F Ordinal0+5279
20: 00007FF6BC43EE12 uv_random+16903298
21: 00007FFD0AA87974 BaseThreadInitThunk+20
22: 00007FFD0B5FA271 RtlUserThreadStart+33
Renderer process killed - see https://www.electronjs.org/docs/tutorial/applicati
on-debugging for potential debugging information.

**Comment by codebytere** [comment]
Dug into this a bit - this is happening because we're throwing an exception from a finalizer. This causes the following stacktrace:

```
1: 0x10dfe1329 node::AsyncHooks::pop_async_context(double) [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]

2: 0x10dfe114c node::InternalCallbackScope::Close() [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]

3: 0x10dfe186f node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]

4: 0x10dfe1b35 node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]

5: 0x10e034135 node::Environment::CheckImmediate(uv_check_s*) [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]

6: 0x1029835fd uv__run_check [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]

7: 0x10297d1c1 uv_run [/Users/codebytere/Developer/electron-gn/src/out/Testing/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]

8: 0x102b531d5 electron::NodeBindings::UvRunOnce() [/Users/codebyte
```
