### ISSUE TITLE
Screen Shot

### ISSUE THREAD

**Issue by Kamran95** [electron/electron#26060]
## Taking continuous Screenshots
I want to take screen shot after each interval of time. But after each time screenshot method is called system becomes slower and slower
## Technology
Electron
## Method 
desktopcapturer
## Code
interval= setInterval(()=>{screenshots()},6000)

function screenshots(){
    
    // console.log('token is',token
    desktopCapturer.getSources({types:['window', 'screen'], thumbnailSize : {width:800,height:480}},async (error,sources)=>{
        if(error) return console.log(error.message)
        sources.forEach((source)=>{
                if(source.name =="Entire Screen" || source.name =="Screen 1" ){
                    
                    const screenshotpath = path.join(os.tmpdir(),'screenshot.jpeg')
                    axiosRequest(source.thumbnail)
                    console.log("image is",source.thumbnail)
                    fs.writeFile(screenshotpath,source.thumbnail.toJPEG(100),(err)=>{
                            if(err) return console.log(err.message)
                            // shell.openExternal('file://'+screenshotpath ) 
                            console.log("screen shot saved to "+screenshotpath )
                    })
                }
        })
    })
}
## target
take screen shots after each ten minutes without creating new instance each time of desktop capturer

**Comment by ckerr** [comment]
Thanks for reaching out!

Please fill out the template when filing new issues and pull requests. This is necessary so that we can be certain we have all the information we need to address your submission efficiently and correctly.

Thanks for understanding and meeting us half way :grinning:

**Comment by codebytere** [comment]
Closing due to no response.
