### ISSUE TITLE
Electron >=10 does not work on Ubuntu 18 under Parallels vm 16

### ISSUE THREAD

**Issue by bpasero** [electron/electron#26061]
### Issue Details

* **Electron Version:**
  * 10 & 11
* **Operating System:**
  * Ubuntu 18
* **Last Known Working Electron version:**
  * 9.x

### Expected Behavior
I can run Electron 10 and 11 on Ubuntu 18.

### Actual Behavior
Running a hello world Electron in 10 or 11 does not appear properly on Ubuntu 18.

### To Reproduce
Install Electron Fiddle on Ubuntu 18 and just run Electron 10 or 11.

### Screenshots

**Electron 9 (working)**
![image](https://user-images.githubusercontent.com/900690/96597524-3c699180-12ee-11eb-9a07-3f09a5ebb0d0.png)

**Electron 10/11**
![image](https://user-images.githubusercontent.com/900690/96597550-44293600-12ee-11eb-9426-3d68f011f7a9.png)

My guess is that this is GPU related.

**Comment by deepak1556** [comment]
After a little bit investigation, this turned out to be an issue only when running on Parallels vm 16. Works fine on Parallels 15 tho. Current workaround is to launch app with `--disable-gpu`.

I don't have parallels 16, looking to update the version and investigate the issue further.

**Comment by nornagon** [comment]
https://crbug.com/936551

**Comment by deepak1556** [comment]
Nice, thanks!

**Comment by weinand** [comment]
Instead of running VS Code with the `--disable-gpu` flag, you can disable "3D accelaration" in Parallels.
