### ISSUE TITLE
window.open does not accept size values with "px" at the end

### ISSUE THREAD

**Issue by t57ser** [electron/electron#26077]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.4
* **Operating System:**
  * Windows
* **Last Known Working Electron version:**
  * 9.3.2

### Expected Behavior
The window should open with the correct size

### Actual Behavior
The size is ignored

### To Reproduce
Use nativeWindowOpen and do: window.open("", "", "width=300px")

### Additional Information
This is working in chrome and firefox and was working in electron 9. If the event is intercepted via webContents.on("new-window") then the value is shown as NAN,

**Comment by nornagon** [comment]
Looks like this was caused by https://github.com/electron/electron/pull/23130, and should be fixed by using `parseInt()` instead of `Number()` here: https://github.com/electron/electron/blob/22cb3cd18b1b771364edada515a4c138a8dddc6d/lib/common/parse-features-string.ts#L41

**Comment by Code-Blooded-Human** [comment]
Hello, I would like to solve this issue.

**Comment by codebytere** [comment]
@Code-Blooded-Human in the future, please note when someone is assigned to an issue that means it's already being worked on - this causes collided work.
