### ISSUE TITLE
[ubuntu] shell.openPath renders the interface unworkable

### ISSUE THREAD

**Issue by tsoil** [electron/electron#26074]
### Issue Details

* **Electron Version:10.1.1
* **Operating System:Ubuntu 18.04 x6

When I opened the Doc file with shell.openPath(), electron interface could not be operated. However, if I opened WPS first and then shell.openPath(), Electron had no impact

**Comment by nornagon** [comment]
Thanks for the report. I'm not sure what you mean by "electron interface could not be operated". Can you explain further?

**Comment by tsoil** [comment]
> Thanks for the report. I'm not sure what you mean by "electron interface could not be operated". Can you explain further?
The render process cannot click as it loses response

**Comment by tsoil** [comment]
> Thanks for the report. I'm not sure what you mean by "electron interface could not be operated". Can you explain further?


The render process cannot click as it loses response

**Comment by tsoil** [comment]
> Thanks for the report. I'm not sure what you mean by "electron interface could not be operated". Can you explain further?
In Linux shell.openPath seems to block and resolve() when the default application is closed

**Comment by tsoil** [comment]
> Thanks for the report. I'm not sure what you mean by "electron interface could not be operated". Can you explain further?


In Linux shell.openPath seems to block and resolve() when the default application is closed

**Comment by gebner** [comment]
I've run into the same issue; indeed `shell.openPath` is blocking on linux.  This seems to be a regression introduced in #20682 here: https://github.com/electron/electron/pull/20682/files#diff-45f588eb3b173144c0442abdf4347dc02acdc2fd0c72045dfcbb82cdf569657aR90

**Comment by xmedeko** [comment]
It's working for me in Electron 10.3.0 and Electron 11.2.1 - I have opened eog and evince and the Electron window is not blocked.

**Comment by xmedeko** [comment]
@link2xt Try to use [Electron Fiddle](https://github.com/electron/fiddle) to create a test case and to publish it as a [GitHub gist](https://gist.github.com). Then open a new issue and and put the gist URL there. This is **the best way** to ensure this issue is triaged quickly.
