### ISSUE TITLE
navigator.clipboard.read() requests 'unknown' permission

### ISSUE THREAD

**Issue by samuelmaddock** [electron/electron#26089]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.0.0-beta.13
  * 10.0.1
* **Operating System:**
  * Windows 10 (2004)

When calling [`navigator.clipboard.read()`](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/read) in the renderer process, the session's permission handler receives a request for the permission "unknown".

### Expected Behavior
The permission handler should receive a request for "clipboard-read" permission.

### Actual Behavior
The permission handler receives a request for "unknown" permission.

### To Reproduce
Electron Fiddler: https://gist.github.com/5046d997fb4648edd08ad8a2645e84a0

**Comment by ckerr** [comment]
gist repros gives the error message as advertised on v11.0.0-beta.13. 

WfM on v10.1.4

**Comment by ckerr** [comment]
Looks like this broke sometime between v11.0.0-beta.7 and v11.0.0-beta.8.

**Comment by ckerr** [comment]
Update: I was wrong, this is broken in 10 as well. There _is_ a new error message in v11.0.0-beta.8 but it's this:

> "Uncaught TypeError: Cannot read property 'setDockSide' of undefined", source: devtools://devtools/bundled/devtools_app.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@9fb8ba8dac0dc84c4cc69619665339e125bbf25d/&can_dock=true&toolbarColor=rgba(223,223,223,1)&textColor=rgba(0,0,0,1)&experiments=true (1)

In testing, this shows up in v11.0.0-beta.8 and higher, but not in v11.0.0-beta.7 or lower.

@samuelmaddock as you're the one most familiar with this test -- DYK if that's related to this issue, or whether it's a separate issue, or if it's just a red herring?

**Comment by samuelmaddock** [comment]
@ckerr The "Cannot read property 'setDockSide' of undefined" appears to be unrelated. I've seen that as well and I think it appears when devtools are opened.

Also, checking this again, I first encountered the issue testing on a build of 10.0.1.

**Comment by jkleinsc** [comment]
FWIW... this issue happens on all supported branches.
