### ISSUE TITLE
How to use NODE_OPTIONS in  the packaged Electron application

### ISSUE THREAD

**Issue by redabc** [electron/electron#26101]
Hi, Electron team:

Recently we encountered a problem，we use the latest version of electron , we do not know how to use NODE_OPTIONS --max-http-header-size=81920 in  the packaged Electron application；
"main": "backend/main.js",
  "scripts": {
    "start": "set NODE_OPTIONS=--max-http-header-size=819200 && electron .",
    "lint": "grunt lint",
    "flint": "grunt flint",
    "blint": "grunt blint",
    "test": "./node_modules/.bin/mocha test/{,**/}*.{js,jsx} --timeout 18000 --reporter mochawesome",
    "help": "electron-builder help",
    "rebuild": "electron-rebuild -f -w sqlite3",
    "build": "electron-builder build --config=pkg/build.yaml",
    "buildmac": "electron-builder build --config=pkg/buildMac.yaml",
    "postinstall": "electron-builder install-app-deps"
  },
it work well, we use npm start in commond-line
But, it does not work , after we build my electron application to an NSIS for windows.  we use electron-builder to build our app.

So, could you please give us some suggestions，how to use  NODE_OPTIONS --max-http-header-size=81920  in  the packaged Electron application, without setting environment variables manually.

Looking forward your soon feedback.

Thank you in advance.

**Comment by ckerr** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://github.com/electron/electron#community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

Good luck! I hope this helps!
