### ISSUE TITLE
ipcRenderer wont listen while BrowserWindows is hidden

### ISSUE THREAD

**Issue by exegonmar** [electron/electron#26105]
When launching an external process with spawn (const {spawn} = require ('child-process')) this process periodically communicates with the renderer from electron through ipc events. But sometimes it stops listening to ipc events from electron. All of this happens while the main window is hidden.

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.1.6
* **Operating System:**
  * Windows 10 (1803

### Expected Behavior
While the main window is hidden it continues to accept messages from ipcMain to ipcRenderer

### Actual Behavior
The main window while hidden in a moment stops listening to messages from ipcMain

**Comment by ckerr** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is no longer supported, so this issue will be closed.

If you're still experiencing this issue on a supported version of Electron and would like this issue to remain open, please file a new issue with that version of Electron.

Thanks in advance! Your help is appreciated.
