### ISSUE TITLE
Spellchecker doesn't work in nested webviews.

### ISSUE THREAD

**Issue by ccorcos** [electron/electron#26117]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 10.1.4
  * 
* **Operating System:** MacOS BigSure Beta 10
  * 
* **Last Known Working Electron version:**
  * 

I've created a repro:

```sh
git clone git@github.com:ccorcos/electron-spellchecker-bug.git
cd electron-spellchecker-bug
npm install
npm start
```

You will see that I have a WebView rendered inside another WebView and the spellchecker only works on the top-level WebView.

**Comment by codebytere** [comment]
@ccorcos `webPreferences` are comma-separated values as documented [here](https://github.com/electron/electron/blob/46f3491c7d5d2ec669fac28298280129c449561e/docs/api/webview-tag.md#L221-L233) - to fix this you need just to do:

```html
    <webview
      id="notion"
      src="../../../../../../Users/codebytere/Desktop/inner.html"
      webpreferences="spellcheck=yes,enableremotemodule=yes"
    />
```

**Comment by ccorcos** [comment]
Oh boy, this sent me down a very deep rabbit hole. I think it would make sense for Electron to surface some kind of error when webpreferences isn't able to be parsed!

**Comment by codebytere** [comment]
@ccorcos the issue is that it _does_ parse it, just incorrectly. 

your original version would have parsed to `{ spellcheck: 'yes;enableremotemodule' }`

**Comment by ccorcos** [comment]
I see, but `yes;enableremotemodule`doesn't parse to a valid value
