### ISSUE TITLE
Drag Region does not work with BrowserView and titleBarStyle: 'hiddenInset'

### ISSUE THREAD

**Issue by ccorcos** [electron/electron#26114]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** v10.1.4
* **Operating System:** MacOS Big Sur

I've created a complete repro for you. Download the repo:

```
git clone git@github.com:ccorcos/electron-browser-view-drag.git
cd electron-browser-view-drag
npm install
```

(1) On the `main` branch, you will see a `BrowserView` rendered and the `preload.js` script sets up a drag region. It doesn't work at all. If you checkout the `base-case` branch, you will see that the same code rendering into the `mainWindow.webContents` and no `BrowserView` works just fine. You can see the diff with `git diff main base-case`.

(2) One solution mentioned in https://github.com/electron/electron/issues/21621 is to render the drag region inside `mainWindow.webContents` and still have a the `BrowserView`. You can try it out with the `webview-workaround` branch and you'll notice that moving the window around is super janky. Observe the diff with `git diff main webview-workaround`.

From here, you'll notice if we comment out `titleBarStyle: 'hiddenInset',` or `mainWindow.setBrowserView(view)`, then dragging works smoothly. Clearly there's something wonky going on here...

### Screenshots

![](https://recordit.co/VSoWiQmMB2)

**Comment by ckerr** [comment]
The sample repro works (or rather, doesn't work) as advertised. Same behavior in master as well.

**Comment by ccorcos** [comment]
@codebytere thanks for picking up this issue! There's [one other issue relating to BrowserView](https://github.com/electron/electron/issues/26116) that is blocking Notion from upgrading. I'd really appreciate if you took a look at it! You'd be a hero! 🙏

**Comment by codebytere** [comment]
@ccorcos i'll see what i can do! also ty for the great repros, extremely appreciated!

**Comment by ccorcos** [comment]
@codebytere I updated my repo's `main` and `base-case` branch `electron-browser-view-drag` to `electron@11.0.0-beta.19` which supposedly has this fix and it and things are better, but still has some issues:

1. When trying to drag the window around, if you grab near the top of the window and move around quickly, when the mouse exists the window, the window stops moving which feels a bit janky. You can repro this on the `main` branch and see the correct behavior on the `base-case` branch.

2. Even with `pointer-events: none;` the drag region still captures the mouse interactions with the page. On the `main` branch, you'll notice that the `<button>` is not clickable where as on the `base-case` branch, the button is clickable.

Let me know if you think I should open up a separate issue ticket for these.

Thanks, 

Chet

**Comment by ccorcos** [comment]
Another possibly related issue https://github.com/electron/electron/issues/26355
