### ISSUE TITLE
Electron crashes when trying to open external browser window with malformed URL

### ISSUE THREAD

**Issue by Draginfable** [electron/electron#26133]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  * 10.1.4 (also reproducible with 9.3.2) 
* **Operating System:** 
  * Windows 10 (1909) / macOS 10.15.7

### Expected Behavior
When clicking  a malformed URL (http://https%3B//github.com), Electron should not crash while trying to open it on an external browser.

### Actual Behavior
Electron crashes when a malformed URL (http://https%3B//github.com) is clicked that should be opened on an external browser.

### To Reproduce

To reproduce download the sample provided in GitHub.
https://github.com/Draginfable/Electron-samples/tree/malformedURLCrash

```sh
git clone https://github.com/Draginfable/Electron-samples.git -b malformedURLCrash
cd Electron-samples
npm i
npm start
```

### Additional Information

The crash only happens when:

1) `app.allowRendererProcessReuse = false;`
2) `nativeWindowOpen: true` in the webPreferences of BrowserWindow
```javascript
win = new BrowserWindow({
    width: 600,
    height: 600,
    show: true,
    webPreferences: {
        nativeWindowOpen: true,
        nodeIntegration: true
    }
});
````
3)  `rel="noopener noreferrer"` attribute in the **a** tag of the malformed URL
```html
<a href="http://https%3B//github.com" target="_blank" rel="noopener noreferrer">http://https%3B//github.com</a>
```
4) e.preventDefault(); is called
```javascript
win.webContents.on('new-window', (e ,url) => {
    e.preventDefault();
    shell.openExternal(url);
});
```

**If any of the four is changed the crash does not occur.**

**Comment by ckerr** [comment]
Gist copy of @Draginfable's repro code: https://gist.github.com/ckerr/590c60135fa3e969a53aeea7c545d1ab

**Comment by mlaurencin** [comment]
@Draginfable The fix for this issue was just backported [here](https://github.com/electron/electron/pull/26442) and in the chore mentioned above. I suggest updating to the latest release of whichever version you are using when that is next released.
