### ISSUE TITLE
Error: EACCES: permission denied, mkdir '/home/user/.cache/electron/httpsgithub.comelectronelectronreleasesdownloadv9.3.2SHASUMS256.txt'

### ISSUE THREAD

**Issue by Zel9278** [electron/electron#26139]
They tell me I don't have enough permissions, I've tried everything, but all to no avail.

### Issue Details

* **Electron Version:**
9.3.2
* **Operating System:**
Ubuntu 18.04 x64
* **Last Known Working Electron version:**
idk

### To Reproduce
```sh
npm i 
```

### Screenshots
![image](https://user-images.githubusercontent.com/43949163/97058653-5bf00b00-15c9-11eb-8b87-5942ca83acda.png)

**Comment by djpeach** [comment]
@Zel9278 What did u do i am having the same issued. Tried everything I can find
