### ISSUE TITLE
macOS help menu keyboard shortcut doesn't work

### ISSUE THREAD

**Issue by tallerthenyou** [electron/electron#26137]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.4
* **Operating System:**
  * macOS 10.15.7
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
Pressing Cmd-shift-? should open the help menu.

https://support.apple.com/en-us/HT201236

> - Shift–Command–Question mark (?): Open the Help menu.

### Actual Behavior

Pressing Cmd-shift-? has no effect.

### To Reproduce

- Open any Electron based application
- Press `Cmd-Shift-?`

### Additional Information

This is an extremely handy macOS shortcut because when using it the help menu search box is activated first and you can start typing the name of any other menu item to quickly execute it.

**Comment by codebytere** [comment]
I'm not sure what you're doing or what accelerators you have registered, but this works perfectly fine for me with the default quick start on 10.1.4 and macOS 10.15.7. You'll need to provide a reproducible sample for us to triage this further, or it will be closed.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
