### ISSUE TITLE
Closing a desktopCapture'd window that is being simulcast over WebRTC crashes the renderer

### ISSUE THREAD

**Issue by alexciarlillo** [electron/electron#26136]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.5.1 / 10.1.4
* **Operating System:**
  * Windows 10 (various builds)
* **Last Known Working Electron version:**
  * n/a

### Expected Behavior

When screen sharing a specific application window via WebRTC (and simulcast is enabled), when you close the window the output should freeze on the last sent frame. Or go black? Anything but crashing the application.

### Actual Behavior

When screen sharing an application window, and using a simulcast setup, when you close the window the renderer process will crash.

### To Reproduce

This is tricky to reproduce as it requires some fairly involved RTC setup to get simulcast working. I made an example repo here with a single dependency (sdp-transform so I didnt have to manually munge SDP to set this up):

https://github.com/alexciarlillo/electron-capture-bug

Most of the RTC code can probably be ignored - it works, and I am seeing this same repro in our real application using more sophisticated libraries to perform this negotiation. I specified H264 in this example, but I have also confirmed this occurs with VP8.

You should be able to capture a window from a dropdown - any window should work, and see the fullsize capture (source) and 1/2 size output on the "receiver" side (this all local-host loopback) which indicates we are simulcasting, and receiving one of the simulcast encodings. Close the window and it should crash.

```sh
$ git clone https://github.com/alexciarlillo/electron-capture-bug
$ npm install
$ npm start
```

### Screenshots

![image](https://user-images.githubusercontent.com/656039/97048196-09223f00-1548-11eb-9086-f0abb1e1163a.png)

![image](https://user-images.githubusercontent.com/656039/97048169-fe67aa00-1547-11eb-9c9d-6aa5813ffabe.png)

### Additional Information

Besides some line numbers the debug call stack looks identical from 8.5.1 to 10.1.4, here is 10.1.4:

![image](https://user-images.githubusercontent.com/656039/97050340-2c022280-154b-11eb-80f5-8e2aa58634a5.png)

Running with ` ELECTRON_ENABLE_LOGGING=true ELECTRON_ENABLE_STACK_DUMPING=true` gives the following output:
```
[7028:1023/155508.933:WARNING:dxgi_adapter_duplicator.cc(108)] Cannot initialize any DxgiOutputDuplicator instance.
[7028:1023/155508.933:WARNING:dxgi_duplicator_controller.cc(260)] Failed to initialize DxgiAdapterDuplicator on adapter 1
[7028:1023/155513.912:WARNING:dxgi_duplicator_controller.cc(81)] Count of references reaches zero, DxgiDuplicatorController will be unloaded.
Renderer process crashed - see https://www.electronjs.org/docs/tutorial/application-debugging for potential debugging information.
```

**Comment by ckerr** [comment]
gist of @alexciarlillo's test case is at https://gist.github.com/ckerr/b0dac5f28cf5c8e7baa987cb79716d69
