### ISSUE TITLE
How WebView communicates？？

### ISSUE THREAD

**Issue by livelyPeng** [electron/electron#26130]
// 在页面
const webview = document.querySelector('webview')
webview.addEventListener('ipc-message', (event) => {
console.log(event.channel)
// Prints "pong"
})
webview.send('ping')

// 在webview
const {ipcRenderer} = require('electron')
ipcRenderer.on('ping', () => {
ipcRenderer.sendToHost('pong')
})

Then WebView page reports an error

index.js:7 Uncaught TypeError: fs.existsSync is not a function
    at getElectronPath (index.js:7)
    at Object.<anonymous> (index.js:18)
    at Object../node_modules/electron/index.js (index.js:18)
    at __webpack_require__ (bootstrap:832)
    at fn (bootstrap:129)
    at Module../node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/index.js?!./src/App.vue?vue&type=script&lang=js& (main.js:3752)
    at __w

**Comment by ckerr** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by livelyPeng** [comment]
@ckerr Can you tell me how to solve it? Is there a link to the method?

**Comment by livelyPeng** [comment]
@ckerr I don't understand. Do you know the answer? Where can I find the answer，  I am in a hurry， thank you
