### ISSUE TITLE
Retrieving webview from the DOM too fast breaks some functions

### ISSUE THREAD

**Issue by FuriousTurtle** [electron/electron#26132]
Hello !

I'm having an issue with my electron app. 
My renderer is made in angular and it has quite some interactions with the webview of my app. One of them being retrieving the webview from the DOM as soon as possible, using querySelector() function on document, and to execute some javascript on it, using executeJavascript() function.

Unfortunately, sometimes I end up with the following error : 
    "The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called."

So I looked into your code but it didn't help me that much. So here I am.

Can somebody give me more informations about how this particular stuff works ?

Note : This is where I end up with this error in your code

lib/renderer/web-view/web-view-impl.ts
```js
  WebViewElement.prototype.getWebContentsId = function () {
    const internal = v8Util.getHiddenValue<WebViewImpl>(this, 'internal');
    if (!internal.guestInstanceId) {
      throw new Error('The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.');
    }
    return internal.guestInstanceId;
  };
```

**Comment by ckerr** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
