### ISSUE TITLE
Create up to 3 instances？？

### ISSUE THREAD

**Issue by livelyPeng** [electron/electron#26144]
How to create up to three instances?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

**Comment by livelyPeng** [comment]
@MarshallOfSound ？？？I don't understand. Do you know the answer? Where can I find the answer
