### ISSUE TITLE
Alt+Click Toggles Menu Bar

### ISSUE THREAD

**Issue by ceiphr** [electron/electron#26149]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.2.12
* **Operating System:**
  * Ubuntu 20.04 x64

### Expected Behavior

Using <kbd>Alt</kbd> toggles the electron menu bar. 

Holding <kbd>Alt</kbd> + any other key results in the electron menu bar **not** being toggled. 
This logic should apply to mouse clicks. Holding <kbd>Alt</kbd> + any mouse click should result in the electron menu bar **not** being toggled.

### Actual Behavior

Holding <kbd>Alt</kbd> + any mouse click results in the electron menu bar being toggled.
The menu toggle can be annoying when <kbd>Alt</kbd> + a mouse click is necessary for interacting with a site.

### To Reproduce

1. Create a browser window with `autoHideMenuBar: true`
2. Hold <kbd>Alt</kbd> and right or left click. The electron menu bar is toggled.

This is my first issue on a big project, please let me know if I need to elaborate or fix any problems with this issue.

**Comment by ckerr** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/tutorial/support#supported-versions), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.
