### ISSUE TITLE
Hide maximize window, off screen => on screen => the window reappears

### ISSUE THREAD

**Issue by devildant** [electron/electron#26148]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.5
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 9.2.1
bug appear from 9.3.0

### Expected Behavior
when i hide the window and turn my screen off and on again, I expect the application to remain hidden

### Actual Behavior
when I hide (win.hide) my application (close the window, app reduce inside the system tray), and I turn off my screen and turn it back on, the window reappears, nothing is clickable. inside the window only the window buttons responds, no event is emitted on the win.on (' show ', function (event)

### To Reproduce
run app
maximise window
close window
off your computer screen (i have 3 screen on my computer), on your screen
the electron window reappears :(
for reproduce :
use this code inside main.js (electron quick start)

```
const electron = require('electron')
const {app, BrowserWindow} = require('electron');

let win;


function createWindow() {

    win = new BrowserWindow({
        webPreferences: {
            nodeIntegration: true,
            enableRemoteModule: true,
        },
        show: false,
        title: "test",
        fullscreenable : false,
        fullscreenWindowTitle : true,
        autoHideMenuBar: true,
        backgroundColor: '#000000',
        'minHeight': 600,
        'minWidth': 800,
    });
    win.setMenu(null);

    app.win = win;
    win.loadFile('index.html')
    win.once('ready-to-show', function (e) {
        win.show()

    })
    win.on('close', function (event) {
        event.preventDefault()
        win.hide();
        return false;
    });
}

function appReadyLaunch() {
    console.log("BB");
    createWindow();

}

app.on('ready',  () => {
appReadyLaunch()

});
```

**Comment by ckerr** [comment]
Possible duplicate of #25367

**Comment by yossizahn** [comment]
Possibly related to #26899

**Comment by grocal** [comment]
It's easy to reproduce this bug with any application that uses Electron and have ability to minimize to tray: Slack, Discord, Yak-Yak for example. And you don't have to turn monitors of or anything. Just maximize the app, send it to tray and then resize viewport by... resizing taskbar (for example from one row to two rows mode or vice versa). Then any of those app and I assume any simple Electron app will display fullscreen "ghost" of the app that you can't interact with.
