### ISSUE TITLE
Alt+Click Toggles Menu Bar

### ISSUE THREAD

**Issue by ceiphr** [electron/electron#26154]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v10.1.5
* **Operating System:**
  * Ubuntu 20.04 x64

### Expected Behavior

Using <kbd>Alt</kbd> toggles the electron menu bar. 

Holding <kbd>Alt</kbd> + any other key results in the electron menu bar **not** being toggled. 
This logic should apply to mouse clicks. Holding <kbd>Alt</kbd> + any mouse click should result in the electron menu bar **not** being toggled.

### Actual Behavior

Holding <kbd>Alt</kbd> + any mouse click results in the electron menu bar being toggled.
The menu toggle can be annoying when <kbd>Alt</kbd> + a mouse click is necessary for interacting with a site.

### To Reproduce

1. Create a browser window with `autoHideMenuBar: true`
2. Hold <kbd>Alt</kbd> and right or left click. The electron menu bar is toggled.

This is my first issue on a big project, please let me know if I need to elaborate or fix any problems with this issue.

**Comment by ckerr** [comment]
Confirmed that alt + mouse click does activate the menubar.

I don't use this feature often and am not sure what correct behavior for Alt + Mouse Click is; but at a minimum, the current behavior contradicts our docs which state:

> [win.autoHideMenuBar is a `Boolean` property that determines whether the window menu bar should hide itself automatically. Once set, the menu bar will only show when users press the single `Alt` key.

**Comment by ceiphr** [comment]
Thank you for the swift reply! 

As an example, in https://github.com/KryDos/todoist-linux the correct behavior would be for Alt + Mouse Click to be ignored. Otherwise, when editing tasks, the page is shifted up and down anytime the user alt-clicks.

**Comment by mikkovedru** [comment]
@ckerr 
> I don't use this feature often and am not sure what correct behavior for Alt + Mouse Click is
The correct behavior should be to ignore the Alt signal; exactly the same way as Alt is ignored when pressed with another key. 

Let's say there is a menu:
![image](https://user-images.githubusercontent.com/2521942/97116814-78469180-1708-11eb-8c51-f89924b09eb0.png)
And I want to select the `History` menu option. Therefore I:
1. press `Alt` and hold it
2. press and release `S` (`History` menu opens)
3. release `Alt` (menu is kept open)

It would a clear bug to close the whole menu after releasing the `Alt` button in stage 3. The same logic should apply to the mouse click.
