### ISSUE TITLE
Changes to the proxy config are not immediately reflected by resolveProxy at session creation time

### ISSUE THREAD

**Issue by nornagon** [electron/electron#26166]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * All current versions of Electron (8.x, 9.x, 10.x, 11.x and main branch)
* **Operating System:**
  * Tested on macOS, but probably all platforms
* **Last Known Working Electron version:**
  * 6.1.12

### Expected Behavior
The result of session.resolveProxy should immediately reflect proxy config updated by session.setProxy once the promise returned by `setProxy` resolves.

### Actual Behavior
When invoked shortly following session creation, resolveProxy returns `DIRECT` instead of using the configured proxy options.

### To Reproduce
https://gist.github.com/5daeaf25587086e09f13f218d1de2bf6

The first `resolveProxy` call returns `DIRECT`, but subsequent calls return the correct value.

Uncommenting the `setTimeout` delay after creating the session causes the first `resolveProxy` call to return the correct value, so this appears to be related to session startup.

Possibly related: https://source.chromium.org/chromium/chromium/src/+/master:components/proxy_config/pref_proxy_config_tracker_impl.cc;l=116;drc=5bafbb92230ad5f59e1fc6e1d3f5d638c34b9dad

**Comment by walmat** [comment]
Any progress on this?
