### ISSUE TITLE
Implement keyboard actions to avoid beeps on certain key bindings

### ISSUE THREAD

**Issue by nathansobo** [electron/electron#2617]
When `ctrl-cmd-down`, `ctrl-cmd-left`, or `ctrl-cmd-right` are pressed in any Electron (or Chrome) `input` or `textarea`, an audible beep occurs. I believe I've tracked this down to the following methods not being implemented in [bridged_content_view.mm](https://chromium.googlesource.com/chromium/src/+/47.0.2494.2/ui/views/cocoa/bridged_content_view.mm) in the `NSResponder Action Messages` section starting at line 351.
- `- (void)makeBaseWritingDirectionNatural:(id)sender`
- `- (void)makeBaseWritingDirectionRightToLeft:(id)sender`
- `- (void)makeBaseWritingDirectionLeftToRight:(id)sender`

They do delegate up the responder chain in their implementation of `doCommandBySelector` on line 579. This leaves me unsure if there's any way to implement these methods via the content API or whether we'll need to add a patch. Either way, it would be great to implement them to avoid the beeping sound when moving lines down in Atom.

Refs atom/atom https://github.com/atom/atom/issues/1669

/cc @zcbenz

**Comment by zcbenz** [comment]
Awesome, I'll see if we can implement those methods in Electron, and if it doesn't work we can always patch libchromiumcontent.

**Comment by zcbenz** [comment]
Hmm I have overridden those methods in Chromium and I'm sure they are on the right place since other methods like `copy:` and `paste:` are also there, but the beep is still there.

I also tested whether `ctrl-cmd-alt-down` would cause beep in Atom, and it does. The `ctrl-cmd-alt-down` maps to `makeTextWritingDirectionNatural:` and it is implemented in Chromium, so the problem is not we didn't implement the `makeBaseWritingDirectionNatural:` method, but something else.

I looked into the key handling code of Chromium and tried to comment out different parts of code, however the beep is always there, I'm out of ideas now.

**Comment by nathansobo** [comment]
That is frustrating. Thanks for trying. I wonder if we could dtrace into the API doing the beeping and figure out what is causing it. It drives me bonkers that this key binding has such a bad experience.

**Comment by alexmalik** [comment]
Hello,

I would like to open dialogue on this issue again please. I'm open to trying to fix it myself with my limited knowledge but has anyone taken this any further by any chance?

Thanks for the efforts so far! 👍

**Comment by hedefalk** [comment]
@alexmalik I'm cheering you on from afar! Pretty please, I'd love a fix.

The workaround mentioned on the atom issue here:
https://github.com/atom/atom/issues/1669#issuecomment-135503562

does not work on my 10.12.5.

**Comment by klvs** [comment]
@hedefalk That workaround didn't work for me on OSX 10.12.5 either but I did learn that you can disable those sounds globally in system prefs -> sound which is fine by me though I'm sure someone wants it.

**Comment by paralel-github** [comment]
It was really bugging me too and I found a fix...
Just create a shortcut for ctrl-cmd-down in Keyboard/Shortcuts and disable it afterward.
No more whump sound for me in Atom! 😎
On macOS Sierra 10.12.6 with Atom 1.19.3.

![whump_fix](https://user-images.githubusercontent.com/16340194/29730622-eb9cdcc4-89ae-11e7-874d-d0ac08cde1a0.png)

**Comment by karlhorky** [comment]
@paralel-github tried it, but didn't help. Tried restarting Atom to make sure. Sound it still there though.

**Comment by paralel-github** [comment]
@karlhorky You're right... when I quit Atom, it doesn't work anymore. 😳 

But I've figured out why it did work for me and here's the sequence you need to do. Will require to repeat steps each time you restart Atom. This is not the perfect fix but it works as long as you don't quit Atom.

1. Quit Atom

2. Open Keyboard/Shortcuts
3. Enable the shortcut you've assigned crtl-cmd-down
4. Quit Keyboard/Shortcuts

5. Open Atom

6. Open Keyboard/Shortcuts again
7. Disable the shortcut
8. Quit Keyboard/Shortcuts

Then it works!

**Comment by karlhorky** [comment]
Heh, yep, like that it works! Good find 😄

**Comment by mikedpad** [comment]
@paralel-github Thanks for that temporary solution. My sanity thanks you! 😄

**Comment by jstr** [comment]
For anyone still frustrated by this I've found the fix described here: https://github.com/atom/atom/issues/1669#issuecomment-135503562 does work but requires a restart to take effect.

**Comment by codebytere** [comment]
Given that this is likely a problem upstream in Chromium, and that this isn't currently on our roadmap, i'm going to go ahead and label this a `wontfix`. However, should someone determine a workable solution we would be very open to accepting a PR!

**Comment by hanguokai** [comment]
I reported this issue to Chromium on Dec 19, 2018 , and they confirmed it now.  To vote up and follow it, Star this [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=916460).

**Comment by sentience** [comment]
Here's a work-around, which I've also posted to @hanguokai's Chromium issue (https://github.com/electron/electron/issues/2617#issuecomment-452284890):

You can establish system-global key bindings for the key combinations ^⌘←, ^⌘↓, and ^⌘→ that are mapped to no operation ("noop"). Simply having these declared as valid keystrokes at the OS level eliminates the system beep that occurs even when a Chromium app accepts and handles the keystroke.
 
In order to establish this, you need to create a ~/Library/KeyBindings/DefaultKeyBinding.dict – note that you'll probably need to create the directory as well, and that the directory name is plural (Bindings), but the file name is singular (Binding). This should be in your user Library folder, not the /Library folder or the /System/Library folder.

The file should be a text file with these contents:
 
```
{
  "^@\UF701" = "noop";
  "^@\UF702" = "noop";
  "^@\UF703" = "noop";
}
```

`^` means Ctrl, `@` means Command, and `\UF701`, `\UF702`, and `\UF703` are the codes for the three arrow keys. There's a nice reference Gist for this file's syntax here: https://gist.github.com/trusktr/1e5e516df4e8032cbc3d I have attached a copy of my file in case that's easier for folks.
 
Once you have created this file, restart any applications where you want to use these keystrokes (or just reboot your system), and you should find that the system beeps are gone. I have successfully applied this tweak on macOS Catalina (10.15.2) to use the default keyboard shortcuts for the “View: Move Editor into Next Group” and “View: Move Editor into Previous Group” commands without hearing system beeps each time.

**Comment by Stakker** [comment]
Ahh thank you for the fix. This was driving me crazy :-)

**Comment by nornagon** [comment]
fwiw if you add the Arabic input mode in Keyboard > Input Sources, then remove it, the beeps also go away.

**Comment by AliAbbasDev** [comment]
I tried the fix from https://github.com/electron/electron/issues/2617#issuecomment-571447707
but it doesn't work on MacOS Ventura. The error sound is still there.

**Comment by sentience** [comment]
> I tried the fix from [#2617 (comment)](https://github.com/electron/electron/issues/2617#issuecomment-571447707)
> but it doesn't work on MacOS Ventura. The error sound is still there.

I hadn't applied the fix on my current machine, which is running macOS Ventura 13.1. I just applied the fix it and it worked as advertised. In your position, I would double-check the spelling of all the file/directory names, and ensure that if I had downloaded the DefaultKeyBinding.dict.zip file I had extracted it to DefaultKeyBinding.dict.

Finally, make sure restart any apps to allow the fix to take effect. In my case, I created the KeyBindings folder in /Users/kyank/Library, dropped the DefaultKeyBinding.dict.zip file into it, double-clicked it to extract the DefaultKeyBinding.dict file, and then deleted the ZIP. Once I had done that, I quit VS Code, then relaunched it after a few seconds. The beeps were gone.

**Comment by LeonardoRick** [comment]
hey @sentience I'm struggling to make the sound stop when pressing `Ctrl + Option + Cmd + DownArrow`

I even tried to add on every arrow to see if this works and also change the order.

This is my file for now:

```
{
  "^@\UF701" = "noop";
  "^@\UF702" = "noop";
  "^@\UF703" = "noop";
  "^@~\UF701" = "noop";
  "^@~\UF702" = "noop";
  "^@~\UF703" = "noop";
}
```

Am I doing something wrong? Any advice on that? I feel that's a silly detail that is holding me back

**Comment by LeonardoRick** [comment]
Found the solution finally, just for reference, the right `noop` for `Ctrl + Option + Cmd + DownArrow` is:

```
"@^~\UF701" = "noop";
```

**Comment by jrab** [comment]
@sentience thank you!! this worked perfectly (required a restart of vscode) -- was driving me up a wall

**Comment by didierbrouwers** [comment]
It looks like the custom keysBindings no longer work in macOS 14.4. When moving a line up or down with control + command  + upArrow / downArrow the annoying sound effect is back again.

**Comment by LeonardoRick** [comment]
@didierbrouwers  Don't know what happened with Sonoma 14.4 but I finally found a solution that is currently working for me:

```
{
    "@^\UF701" = "noop:";
    "@^\UF702" = "noop:";
    "@^\UF703" = "noop:";
    "@~^\UF701" = "noop:";
}
```


Basically I needed to add the `:` at the end of `noop` and invert the order for the `Ctrl + Option + Cmd + DownArrow`

**Comment by didierbrouwers** [comment]
@LeonardoRick yes, your solution stops the sound effect again! Thanks!

**Comment by dannypernik** [comment]
> @didierbrouwers Don't know what happened with Sonoma 14.4 but I finally found a solution that is currently working for me:
> 
> ```
> {
>     "@^\UF701" = "noop:";
>     "@^\UF702" = "noop:";
>     "@^\UF703" = "noop:";
>     "@~^\UF701" = "noop:";
> }
> ```
> 
> Basically I needed to add the `:` at the end of `noop` and invert the order for the `Ctrl + Option + Cmd + DownArrow`

Victory! Today was the first time I was trying to implement the keybinding, so I'm grateful that I found this post so quickly. Also feeling fortunate that you guys use the same custom keyboard shortcuts for moving tabs as I do!

**Comment by cpbotha** [comment]
> [@didierbrouwers](https://github.com/didierbrouwers) Don't know what happened with Sonoma 14.4 but I finally found a solution that is currently working for me:
> 
> ```
> {
>     "@^\UF701" = "noop:";
>     "@^\UF702" = "noop:";
>     "@^\UF703" = "noop:";
>     "@~^\UF701" = "noop:";
> }
> ```
> 
> Basically I needed to add the `:` at the end of `noop` and invert the order for the `Ctrl + Option + Cmd + DownArrow`

Confirmed to work on macOS 26 Tahoe as well, thank you so very much @LeonardoRick !

**Comment by geon** [comment]
OMG, thanks so much! It's been driving me crazy.

> [@alexmalik](https://github.com/alexmalik) I'm cheering you on from afar! Pretty please, I'd love a fix.
> 
> The workaround mentioned on the atom issue here: [atom/atom#1669 (comment)](https://github.com/atom/atom/issues/1669#issuecomment-135503562)
> 
> does not work on my 10.12.5.

Works for me in vscode on macos 15.6 (24G84)
