### ISSUE TITLE
BrowserView doesn't use constructor options

### ISSUE THREAD

**Issue by mahnunchik** [electron/electron#26225]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  v8.5.2
* **Operating System:**
  *  macOS 10.15.7
* **Last Known Working Electron version:**
  * 

### Expected Behavior

Options in constructor:

```js
const view = new BrowserView({
  x: 0, y: 0, width: 300, height: 300
})
```

Produces correct view with 300x300 dimensions.

### Actual Behavior

Produces invisible view.

### To Reproduce

```js
const view = new BrowserView({
  x: 0, y: 0, width: 300, height: 300
})

mainWindow.setBrowserView(view);
```

### Additional Information

This code works as expected:

```js
const view = new BrowserView(); // without options
view.setBounds({ x: 0, y: 0, width: 300, height: 300 });

mainWindow.setBrowserView(view)
```

**Comment by codebytere** [comment]
That's intended behavior. Docs clearly specify available options, of which bounds are not one:

https://github.com/electron/electron/blob/c8a0b2b71d8622bbb848e364a842ea12bd5966fb/docs/api/browser-view.md#L26-L29
