### ISSUE TITLE
Setting taskbar thumbnail image

### ISSUE THREAD

**Issue by hhammoud01** [electron/electron#2623]
Hey all,

When something is being played on media player for example, when one hovers the mouse over media player's icon on the taskbar, he can see what is being played and not the entire window of media player (including everything), the only things that show are the cover art of the music, the title and the buttons to be clicked (previous, play/pause, next).

When one uses the setThumbarButtons() from the atom/electron library, it only adds the buttons under the image of the entire window.

How can we set the image to show when we hover the mouse over the taskbar's application icon ? (and do something like media player).

Thank you for your time,
Best Regards,
Hussein Hammoud.

**Comment by zcbenz** [comment]
Refs https://msdn.microsoft.com/en-us/library/windows/desktop/dd391701(v=vs.85).aspx.
