### ISSUE TITLE
app.commandLine.hasSwitch on windows return false if switch has a capital letter

### ISSUE THREAD

**Issue by Dmitrylolo** [electron/electron#26257]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  v.9.1.0
* **Operating System:**
  Windows
* **Last Known Working Electron version:**
  no

### Expected Behavior
app.commandLine.hasSwitch('anySwitchWithCapitalLetter') should give **true**

### Actual Behavior
app.commandLine.hasSwitch('anySwitchWithCapitalLetter') return **false**
app.commandLine.hasSwitch('anyswitchwithcapitalletter') return **true**

### To Reproduce
try to run electron application with any switch with capital letters on windows

### Screenshots

![Capture](https://user-images.githubusercontent.com/20141579/97597434-7d5c5700-1a0e-11eb-9c3b-6f9a53dece61.PNG)
![Capture2](https://user-images.githubusercontent.com/20141579/97597451-83523800-1a0e-11eb-98db-46385f7effb5.PNG)

**Comment by nornagon** [comment]
This is intentional. The `hasSwitch` API is a direct wrapper of the Chromium CommandLine class, which behaves this way on purpose. https://source.chromium.org/chromium/chromium/src/+/master:base/command_line.h;l=145;drc=036150cfca14e4f91b7f06855b19462575aed37f
