### ISSUE TITLE
Restore the functionality of disable-x-frame-options

### ISSUE THREAD

**Issue by adel-sbeh** [electron/electron#26258]
`disable-x-frame-options` is not working anymore. (https://github.com/electron/electron/issues/426)
```html
<iframe name="disable-x-frame-options"></iframe>
```
It would be really nice to reintroduce this feature. Or, maybe, you can make it possible to create custom elements that share the same functionality of a `webview`.

**Comment by nornagon** [comment]
This can be accomplished with the `webRequest` API, e.g.: https://github.com/electron/electron/pull/573#issuecomment-520083828

**Comment by adel-sbeh** [comment]
No, I don't want to disable this in all of the `<iframe>`-s in the window. I only want to target specific `<iframe>`-s.

**Comment by nornagon** [comment]
Fair enough, here you go: https://github.com/electron/electron/pull/27078
