### ISSUE TITLE
`win.show` has problems with focus in some cases

### ISSUE THREAD

**Issue by EthianWong** [electron/electron#26277]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  >=9.1.0
* **Operating System:**
  *  macOS 10.15.7 (19H2)
* **Last Known Working Electron version:**
  *  9.0.4

### Expected Behavior

The focus can be handled correctly when `win.show()` is executed

### Actual Behavior

The focus is a bit weird after executed `win.show()`

### To Reproduce

1. Open a electron app
2. Focus on textarea or input
3. Click other applications or use `command + tab` go to other applications (electron window not min & hide)
4. Click electron app tray to execute `win.show()`
5. Press key 'i'

### Screenshots

When electron version >= 9.1.0:
<img src="https://user-images.githubusercontent.com/12590228/97688653-62084f00-1ad5-11eb-87f9-9f6d9865aa8a.png" width="400"/>

The application name is displayed in the taskbar so electron app should be focused, but the window control buttons do not light up as normal and input candidate area move to lower left

When electron version < 9.1.0:
<img src="https://user-images.githubusercontent.com/12590228/97688233-cf67b000-1ad4-11eb-8666-57f73c111cf2.png" width="400"/>

### Additional Information

In 9.1.0 upgrade log: https://github.com/electron/electron/pull/24354
I don't know if it is related to this, but i try a lot of times, v9.0.4 is ok

**Comment by kenan2002** [comment]
Same issue here. win.show() called from tray click, cursor seems focused but traffic lights are gray and keyboard events not fired in window.

Electron 11.1.1
macOS 10.14.6/10.15/11.0.1
