### ISSUE TITLE
App prevent reinstall

### ISSUE THREAD

**Issue by nuryagdym** [electron/electron#26279]
Hello,
My electron app is reinstalling app every time I click on .exe.
How can I prevent it from reinstalling?

here my `package.json` build configuration
```json
  "build": {
    "win": {
      "target": [
        {
          "target": "nsis-web",
          "arch": [
            "ia32"
          ]
        }
      ]
    },
    "nsisWeb": {
      "oneClick": false,
      "differentialPackage": true,
      "perMachine": false,
      "runAfterFinish": false
    },
    "publish": [

    ],
    "asar": false,
    "npmRebuild": true,
    "nodeGypRebuild": false,
    "electronCompile": false,
    "removePackageScripts": true,
    "files": [
    ]
  },
  "devDependencies": {
    "electron": "^10.1.5",
    "electron-builder": "^22.8.1"
  },
```
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v10.1.5
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * same issues was with electron v3.1

**Comment by nornagon** [comment]
This looks like an issue with https://github.com/electron-userland/electron-builder, which is not maintained by this team. Best to report the issue there!
