### ISSUE TITLE
Background process / daemon

### ISSUE THREAD

**Issue by petersolimine** [electron/electron#26288]
#25708 # Problem Description

- Not related to a problem, but my application needs to be able to run scripts in the background occasionally
### Proposed Solution

- perhaps a browser tht runs in the background? This sounds very resource intensive though.

### Alternatives Considered

- N/A
### Additional Information

- Looking to create a UI-controlled cron

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
