### ISSUE TITLE
Youtube video playback from an iframe

### ISSUE THREAD

**Issue by minthaka** [electron/electron#26282]
Hello. I am writing an Angular 10 application, which is then wrapped into an Electron desktop application.
I use an iframe with dynamic src variable binding, which accepts url-s. I use to replace the "watch?v=" part with "embed/" and the video's preview frame loads in. 
When I try to play, I am getting Video Is Not Available error message.

I am working on LinuxMint, and i would like to play those videos. Thank for any solutions.

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
