### ISSUE TITLE
Breaking change in session.resolveProxy is not documented

### ISSUE THREAD

**Issue by torywheelwright** [electron/electron#26290]
At some point, [this function](https://www.electronjs.org/docs/api/session#sesresolveproxyurl) changed to return a promise rather than accepting a callback as a second argument. I would have expected that to be documented [here](https://www.electronjs.org/docs/breaking-changes). I discovered this while updating an app from Electron 1.8.8. You can see the old API in the docs for that version [here](https://github.com/electron/electron/blob/v1.8.8/docs/api/session.md).

**Comment by nornagon** [comment]
It's documented here: https://www.electronjs.org/docs/api/modernization/promisification

but that doesn't seem to be linked from the breaking changes document...

**Comment by torywheelwright** [comment]
Ahh, ok, thanks! I never found my way to that page; linking it from the breaking changes document would probably be a worthwhile change.
