### ISSUE TITLE
Open Dev Tools error: Uncaught TypeError: Cannot read property 'setDockSide' of undefined

### ISSUE THREAD

**Issue by softwarecreations** [electron/electron#26300]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
`webContents.openDevTools();` produces error:
`[12703:1102/100312.745262:ERROR:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'setDockSide' of undefined", source: devtools://devtools/bundled/devtools_app.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@1eb8474cd7e4fccfbfa8048eceda1eab8b4d394/&can_dock=true&toolbarColor=rgba(223,223,223,1)&textColor=rgba(0,0,0,1)&experiments=true (1)`

Opening dev tools via these methods also produces the same error:
* Right click background > Inspect element
* Ctrl-Shift-I

* **Electron Version:**
  * 11.0.0-beta.18
* **Operating System:**
  * Debian 10 Buster x64, KDE Plasma
* **Last Known Working Electron version:**
  * 10.1.4

### Expected Behavior
Dev tools should open without error.

### Actual Behavior
Above error appears in the terminal.

### To Reproduce
Running this code will probably do it, although I'm opening a URL, but that shouldn't matter.
https://www.electronjs.org/docs/tutorial/quick-start#create-a-basic-application

### Additional Information
I need the beta because the stable version's node is too old.

**Comment by ckerr** [comment]
This is working in 11.0.0-beta.7 and is broken in 11.0.0-beta.8
