### ISSUE TITLE
Frameless browserview gets bigger size while it is set to fullscreen 

### ISSUE THREAD

**Issue by pejman1** [electron/electron#26306]
### Issue Details
While you have a browser view with setAutoResize true , if you set the mainwindow or browser view to mazimize state. the browser view gets bigger size of the fullscreen res. 

* **Electron Version:**
 * 10.1.5
* **Operating System:**
  * Windows 10 (1803) 

### Expected Behavior

the browser view in maximize state should be the same size as mainwindow 

### Actual Behavior

in maximize state it does not set its size correctly 

### Screenshots

![Screen Shot 2020-11-03 at 00 22 12 AM](https://user-images.githubusercontent.com/11601344/97919275-c55fde80-1d6c-11eb-81b1-f387827432c6.png)
main window in maximize state 

![Screen Shot 2020-11-03 at 00 22 08 AM](https://user-images.githubusercontent.com/11601344/97919501-225b9480-1d6d-11eb-81e2-3902e413355b.png)
browser view which is attached to main windows after setting in maximize state gets wrong size

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
Closing as no response was given.

**Comment by pejman1** [comment]
> Closing as no response was given.
sample project 

https://gist.github.com/pejmanpesyan/8540aad65e7c6980c45f23e5eaafafb9

**Comment by pejman1** [comment]
> Thanks for reporting this and helping to make Electron better!
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a followup comment.
> 
> Thanks in advance! Your help is appreciated.

https://gist.github.com/pejmanpesyan/8540aad65e7c6980c45f23e5eaafafb9

**Comment by pejman1** [comment]
@ckerr @codebytere 
the exact problem has come back on latest versions 19.0 and 18.2.4
