### ISSUE TITLE
Plug in / Plug out headphone multiple times might cause no audio

### ISSUE THREAD

**Issue by jimmyxu1985** [electron/electron#26302]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  7.2.3
* **Operating System:**
  Mac OS 10.15.6
* **Last Known Working Electron version:**
  N/A

### Expected Behavior
Audio should work fine

### Actual Behavior
There's no microphone input audio level after plugin / plugout headphone multiple times

### To Reproduce
1. Use appr.tc
2. connect with someone else
3. plugin / plugout headphone multiple times
4. Check on remote side if he can still hear sound

### Additional Information
1. On same machine, Chrome, and chromium edge doesn't have this issue
2. When this issue happened, it will impact all further microphone usage on this electron, reload page won't help fix it. Only restart electron can fix it.

**Comment by ckerr** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/tutorial/support#supported-versions), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron. And if so -- would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

Thanks in advance! Your help is appreciated.
