### ISSUE TITLE
Browserview is not draggable after setting   -webkit-app-region: drag;  

### ISSUE THREAD

**Issue by pejman1** [electron/electron#26308]
### Issue Details
While set browserview style to draggable by webkit-app-region : drag. but the area won't be draggable after that 

* **Electron Version:**
  * 10.1.5
* **Operating System:**
  *  Windows 10 (1803) 
* **Last Known Working Electron version:**
  * not found

### Expected Behavior
Browser view moves the main window while I set the style of the body or one of the area to 
  -webkit-app-region: drag;

### Actual Behavior

nothing happen in browserview after styling   -webkit-app-region: drag;

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
Closed by https://github.com/electron/electron/pull/26145
