### ISSUE TITLE
webContents.print not accepting page size

### ISSUE THREAD

**Issue by ashokbhayal** [electron/electron#26317]
Hi,

I want to print small stickers of 3 in x 2 in. I am able to print the stickers but the page size is always A4. This way I would be wasting a lot of stickers. I tried to set the pageSize object in options, but it doesn't work. How can I set the page height any example will be helpful?

**Comment by jkleinsc** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
