### ISSUE TITLE
Session setProxy not working with http

### ISSUE THREAD

**Issue by samfrm** [electron/electron#26319]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  * 3.0.9
* **Operating System:**
  * macOS 10.15.7

### Expected Behavior
It should set the proxy and work as the `socks v4/v5` is working but it fails.

I am using this code for socks and it is working:
`webContents.session.setProxy({proxyRules:'socks5://xxx.xxx.xxx.xxx:xxxx'}, function() {})`

And this code for `http/https` not working (not opening urls)
`webContents.session.setProxy({proxyRules:'http://xxx.xxx.xxx.xxx:xxxx'}, function() {})`

Any reason or the syntax for `http` is wrong?

**Comment by jkleinsc** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
