### ISSUE TITLE
The discord bot client opens real discord

### ISSUE THREAD

**Issue by LuckyTop1337** [electron/electron#26315]
When I try to log in as a bot with a special token it just shows me a member login with password right after I insert the token.
How do I fix this?

**Comment by ckerr** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
