### ISSUE TITLE
[macOS] app upgrade over installer fails

### ISSUE THREAD

**Issue by MaxBolotnyi** [electron/electron#26316]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 3.x (3.1.13 the one I tested)
  * 9.x / 10.x (9.3.3 / 10.1.5 the ones I tested)
* **Operating System:**
  * macOS 10.15.7

### Expected Behavior
When package, then install a clean electron app of electron version 3.x and then upgrade it with absolutely the same app but with the electron version 9.x or 10.x the installation will be succeeded and the app will be upgraded.

### Actual Behavior
When package, then install a clean electron app of electron version 3.x and then upgrade it with absolutely the same app but with the electron version 9.x or 10.x the installation will fail.

### To Reproduce
1. Get clean electron app. ( electron version 3.1.13 )
2. package it to .pkg with any packager ( **electron-packager**, electron-builder, electron-forge) 
3.  Install the app on macos via the bundled .pkg file.
4. Bump the electron version in package.json to 9.x or 10.x ( tested with 9.3.3 and 10.1.5 )
5. Repeat step 2
6. Repeat step 3
7. See the same error as on the screenshot

### Screenshots
<img width="732" alt="Screenshot 2020-11-03 at 16 17 12" src="https://user-images.githubusercontent.com/36646205/97996102-0b11bb00-1df0-11eb-99a8-695ff5fa9aba.png">

**Comment by jkleinsc** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
