### ISSUE TITLE
Using pageRanges print option with Microsoft Print to PDF returns failed status

### ISSUE THREAD

**Issue by Linbubin** [electron/electron#26318]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  v10.1.5
* **Operating System:**
  * win10
* **Last Known Working Electron version:**
  * 

### Expected Behavior

use the [`print options`](https://www.electronjs.org/docs/api/web-contents#contentsprintoptions-callback) capture the number of pages you want to print and work like chrome.

### Actual Behavior

sometimes print failed,and sometimes not work.

### To Reproduce

I use the [fiddle](https://gist.github.com/d04ce9925d93b562eea2f152c7d9a7db).

### Screenshots

I type `window.print()` in console, and change the pageRanges, it works.
![image](https://user-images.githubusercontent.com/19225429/98004684-2ea62700-1e2b-11eb-96f1-fcd2b9eecbf6.png)

But I click the print button in the web, it default use `pageRanges: { from: 1, to: 10 }` or `pageRanges: [{ from: 1, to: 10 }]`, but the pdf is all the pages.

### Additional Information

Please change the default pageRanges to test the api.

Maybe can give more detail failed reason to improve user type.

**Comment by jkleinsc** [comment]
@Linbubin pageRanges is 0 based, so for example if you want pages 1 - 3, you should specify:
`pageRanges: [{ from: 0, to: 2 }]`
I tested with that setting on Electron 10.1.5 and it worked correctly.  Please let me know if that solves your problem.

**Comment by Linbubin** [comment]
@jkleinsc 
When I use the `pageRanges: [{ from: 0, to: 2 }]`, the callback `failureReason` show `failed`

![image](https://user-images.githubusercontent.com/19225429/98112182-b5670c80-1edc-11eb-8b3a-daa2bbc784f7.png)

**Comment by jkleinsc** [comment]
@Linbubin this is working for me.  Do you see this a Window like this appear?
<img width="814" alt="Screen Shot 2020-11-04 at 10 42 45 AM" src="https://user-images.githubusercontent.com/609052/98132661-aeafa980-1e8a-11eb-9c37-92b6a07ba954.png">

If you click Cancel on this Window it will return failed - that is by design.

**Comment by Linbubin** [comment]
![show](https://user-images.githubusercontent.com/19225429/98253872-8ae98200-1fb6-11eb-960c-3112bd41b3e4.gif)

When I use  `[{ from: 0, to: 2 }]`, I can get the path choose too. But I type the save, the console say `failed`

**Comment by jkleinsc** [comment]
@Linbubin thank you for the update.  I can now reproduce the problem.

**Comment by sunchanglong** [comment]
@jkleinsc  electron 15.3.1 still has the problem.
eg. There is  5 pages in total, print silent  set `pageRanges: [{from: 0, to: 2}]`, the pdf produced by print is broken , can't be opened. it won't create system print task when print to real printers.

**Comment by sunchanglong** [comment]
@codebytere any update ? When will the bug assigned to some one? Thanks.

**Comment by kevin100702** [comment]
bump
