### ISSUE TITLE
 node-pre-gyp ERR! Tried to download(404): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v3.0.8-electron-v1.6 -win32-ia32.tar.gz

### ISSUE THREAD

**Issue by Jaikub97** [electron/electron#26310]
构造低版本的electron的时候发现了lzma-native的下载源已经缺少了我要下载的那个版本
### Preflight Checklist

Error: C:\Program Files\nodejs\node.exe exited with code 1
Output:

> lzma-native@6.0.1 install D:\project\PC_IM\electron_vplus_gd\node_modules\lzma-native
> node-pre-gyp install --fallback-to-build && rimraf build

[lzma-native] Success: "D:\project\PC_IM\electron_vplus_gd\node_modules\lzma-native\binding-v6.0.1-n-api-win32-ia32\lzma
_native.node" is installed via remote

> realm@2.1.0 install D:\project\PC_IM\electron_vplus_gd\node_modules\realm
> node-pre-gyp install --fallback-to-build

[realm] Success: "D:\project\PC_IM\electron_vplus_gd\node_modules\realm\compiled\electron-v1.6_win32_ia32\realm.node" is
 installed via remote

> lzma-native@3.0.8 install D:\project\PC_IM\electron_vplus_gd\node_modules\decompress-tarxz\node_modules\lzma-native
> node-pre-gyp install --fallback-to-build && node node_modules/rimraf/bin.js build

Failed to execute 'C:\Program Files\nodejs\node.exe D:\project\PC_IM\electron_vplus_gd\node_modules\node-gyp\bin\node-gy
p.js configure --fallback-to-build --module=D:\project\PC_IM\electron_vplus_gd\node_modules\decompress-tarxz\node_module
s\lzma-native\binding-v3.0.8-electron-v1.6-win32-ia32\lzma_native.node --module_name=lzma_native --module_path=D:\projec
t\PC_IM\electron_vplus_gd\node_modules\decompress-tarxz\node_modules\lzma-native\binding-v3.0.8-electron-v1.6-win32-ia32
' (7)

Error output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
node-pre-gyp verb cli   'D:\\project\\PC_IM\\electron_vplus_gd\\node_modules\\lzma-native\\node_modules\\node-pre-gyp\\b
in\\node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@8.0.0 | win32 | x64
node-pre-gyp verb command install []
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp http GET https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-win32-ia32.tar.gz
node-pre-gyp http 200 https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v6.0.1-n-api-win32-ia32.tar.gz
node-pre-gyp info install unpacking binding-v6.0.1-n-api-win32-ia32/liblzma.dll
node-pre-gyp info install unpacking binding-v6.0.1-n-api-win32-ia32/lzma_native.node
node-pre-gyp info tarball done parsing tarball
node-pre-gyp info ok
node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
node-pre-gyp verb cli   'D:\\project\\PC_IM\\electron_vplus_gd\\node_modules\\realm\\node_modules\\node-pre-gyp\\bin\\no
de-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@8.0.0 | win32 | x64
node-pre-gyp verb command install []
node-pre-gyp http GET https://static.realm.io/node-pre-gyp/2.1.0/realm-v2.1.0-electron-v1.6-win32-ia32.tar.gz
node-pre-gyp http 200 https://static.realm.io/node-pre-gyp/2.1.0/realm-v2.1.0-electron-v1.6-win32-ia32.tar.gz
node-pre-gyp info install unpacking realm.node
node-pre-gyp info tarball done parsing tarball
node-pre-gyp info ok
node-pre-gyp ERR! Tried to download(404): https://node-pre-gyp.addaleax.net/lzma-native/lzma_native-v3.0.8-electron-v1.6
-win32-ia32.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for lzma-native@3.0.8 and electron@1.6.5 (electron-v1.6 ABI, unknown) (fa
lling back to source compile with node-gyp)
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack D:\project\PC_IM\electron_vplus_gd\node_modules\node-gyp\node_modules\mkdirp\lib\opts-arg.js:7
gyp ERR! stack     opts = { mode: 0o777, fs, ...opts }
gyp ERR! stack                               ^^^
gyp ERR! stack
gyp ERR! stack SyntaxError: Unexpected token ...
gyp ERR! stack     at createScript (vm.js:74:10)
gyp ERR! stack     at Object.runInThisContext (vm.js:116:10)
gyp ERR! stack     at Module._compile (module.js:533:28)
gyp ERR! stack     at Object.Module._extensions..js (module.js:580:10)
gyp ERR! stack     at Module.load (module.js:503:32)
gyp ERR! stack     at tryModuleLoad (module.js:466:12)
gyp ERR! stack     at Function.Module._load (module.js:458:3)
gyp ERR! stack     at Module.require (module.js:513:17)
gyp ERR! stack     at require (internal/module.js:11:18)
gyp ERR! stack     at Object.<anonymous> (D:\project\PC_IM\electron_vplus_gd\node_modules\node-gyp\node_modules\mkdirp\i
ndex.js:1:79)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\project\\PC_IM\\electron_vplus_gd\\node_modules\\node-gyp\\b
in\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\project\\PC_IM\\electron_vplus_gd\\node_modules\\decomp
ress-tarxz\\node_modules\\lzma-native\\binding-v3.0.8-electron-v1.6-win32-ia32\\lzma_native.node" "--module_name=lzma_na
tive" "--module_path=D:\\project\\PC_IM\\electron_vplus_gd\\node_modules\\decompress-tarxz\\node_modules\\lzma-native\\b
inding-v3.0.8-electron-v1.6-win32-ia32"
gyp ERR! cwd D:\project\PC_IM\electron_vplus_gd\node_modules\decompress-tarxz\node_modules\lzma-native
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v7.1.2
gyp ERR! Node-gyp failed to build your package.
gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe D:\project\PC_IM\electron_vplus_gd\no
de_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\project\PC_IM\electron_vplus_gd\node_modul
es\decompress-tarxz\node_modules\lzma-native\binding-v3.0.8-electron-v1.6-win32-ia32\lzma_native.node --module_name=lzma
_native --module_path=D:\project\PC_IM\electron_vplus_gd\node_modules\decompress-tarxz\node_modules\lzma-native\binding-
v3.0.8-electron-v1.6-win32-ia32' (7)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\project\PC_IM\electron_vplus_gd\node_modules\decompress-tarx
z\node_modules\lzma-native\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:125:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:887:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
node-pre-gyp ERR! System Windows_NT 10.0.18363
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\project\\PC_IM\\electron_vplus_gd\\node_modules\\de
compress-tarxz\\node_modules\\lzma-native\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build
"
node-pre-gyp ERR! cwd D:\project\PC_IM\electron_vplus_gd\node_modules\decompress-tarxz\node_modules\lzma-native
node-pre-gyp ERR! node -v v8.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lzma-native@3.0.8 install: `node-pre-gyp install --fallback-to-build && node node_modules/rimraf/bin.js build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lzma-native@3.0.8 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-11-03T02_48_31_878Z-debug.log

    at ChildProcess.childProcess.once.code (D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder\node_module
s\builder-util\src\util.ts:241:14)
    at Object.onceWrapper (events.js:312:19)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
From previous event:
    at spawn (D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder\node_modules\builder-util\src\util.ts:200
:3)
    at D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder\node_modules\electron-builder-lib\src\util\yarn.
ts:171:5
From previous event:
    at rebuild (D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder\node_modules\electron-builder-lib\out\u
til\yarn.js:93:22)
    at D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder\node_modules\electron-builder-lib\src\util\yarn.
ts:20:11
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at installOrRebuild (D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder\node_modules\electron-builder-
lib\out\util\yarn.js:31:21)
    at D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder\node_modules\electron-builder-lib\src\packager.t
s:442:7
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder\node_modules\el
ectron-builder-lib\out\packager.js:496:11)
    at D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder\node_modules\electron-builder-lib\src\packager.t
s:356:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder\node_modules\electron-builder-
lib\out\packager.js:432:11)
    at D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder\node_modules\electron-builder-lib\src\packager.t
s:308:52
    at Generator.next (<anonymous>)
    at D:\project\PC_IM\electron_vplus_gd\node_modules\graceful-fs\graceful-fs.js:144:16
    at D:\project\PC_IM\electron_vplus_gd\node_modules\graceful-fs\graceful-fs.js:61:14
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder\node_modules\electron-builder-l
ib\out\packager.js:376:11)
    at D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder\node_modules\electron-builder-lib\src\packager.t
s:270:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Packager.build (D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder\node_modules\electron-builder-li
b\out\packager.js:332:11)
    at D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder\src\builder.ts:310:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder\out\builder.js:61:21)
    at Object.build (D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder\src\builder.ts:280:10)
    at buildTarget (D:\project\PC_IM\electron_vplus_gd\ele-build.js:122:13)
    at build (D:\project\PC_IM\electron_vplus_gd\ele-build.js:86:13)
    at Object.<anonymous> (D:\project\PC_IM\electron_vplus_gd\ele-build.js:76:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

### Issue Details

Electron Version:1.6.5
npm：8.0

**Comment by jkleinsc** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/tutorial/support#supported-versions), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.
