### ISSUE TITLE
BrowserWindow background color sometimes bleeds through to the BrowserView

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#26328]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 9.0.4, 10.1.5
* **Operating System:** Windows 10

### Expected Behavior
I expect that the browser window's background color doesn't affect BrowserViews that are positioned over it

### Actual Behavior
In some cases, the color bleeds through to the site

### To Reproduce
sites like google.com / facebook.com don't have this problem, but I found one site (stripped down below) that does.

main.js:

```
const { app, BrowserWindow, BrowserView } = require('electron')
const path = require("path");

async function createWindow() {
  const mainWindow = new BrowserWindow();
  const view = new BrowserView();
  mainWindow.setBrowserView(view);
  mainWindow.setBackgroundColor("#ccc")
  view.setBounds({x: 0, y: 0, width: mainWindow.getContentBounds().width, height: mainWindow.getContentBounds().height });

  await view.webContents.loadURL(path.join(__dirname, "./index.html"));
  // view.webContents.openDevTools(); // uncommenting works around this
}

app.on('ready', createWindow)
```

index.html:
```
<html>
	<body>
		<h1>Welcome</h1>
	</body>
</html>
```

The issue doesn't reproduce when devtools is enabled.

Seemed somewhat similar to [this issue](https://github.com/electron/electron/issues/16212) though in my case, my background color isn't transparent.

![image](https://user-images.githubusercontent.com/6374473/98048408-3ea21480-1df3-11eb-9005-871f764a60a1.png)

**Comment by codebytere** [comment]
Collapsing into https://github.com/electron/electron/issues/33374
