### ISSUE TITLE
token error

### ISSUE THREAD

**Issue by asadsadsad1251** [electron/electron#26327]
once i put paste the token it legit takes me to the login screen

**Comment by asadsadsad1251** [comment]
what i mean by login screen is Email and Password thingy

**Comment by jkleinsc** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
