### ISSUE TITLE
Error: An object could not be cloned

### ISSUE THREAD

**Issue by rasgo-cc** [electron/electron#26338]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.5
* **Operating System:**
  * Windows 10

### Expected Behavior
The object should be serialized. In case the error is thrown, it should show what object it was trying to serialize

### Actual Behavior
Throws error with apparently valid object. It becomes quite difficult to debug what object is causing the exception.

### Screenshots
(an example of what I'm experiencing)
```
    console.log(`DB_${name}`, ...args);
    const result = await ipcRenderer.invoke(`db_${name}`, ...args);
```
![](https://pouch.jumpshare.com/preview/GUpGRLZlrgW85p2OxR26TH1CaT_BRKulZLH2dYiIuSPv10YEJHRaMVTjyHr_S_ckNa_oG9WAhwgS7ZXVOzhVQDJprjKJn4snkOQIlHyX-Do)

Similarly, this is what I get in the main process (console.log just before returning from an ipc handler):
![](https://pouch.jumpshare.com/preview/MEcRnLzMqZq_hyaWFp1o4Of2zl5rUUYXwJJfzf0mDU_sbJ-lg7MbVFGtSUCqSov6pm77hnzy-yMPCLy5bMEqkzJprjKJn4snkOQIlHyX-Do)

### Additional Information
The exception is actually thrown in the main process (and then sent to renderer). Still I can't understand why the object it's trying to send can't be cloned.

**Comment by rasgo-cc** [comment]
JSON.stringifing/parsing the result works. It's still not clear to me why V8 serializer can't serialize the object.

**Comment by jkleinsc** [comment]
This is an intentional error message.  There was  a breaking change that happened in Electron 9:
https://www.electronjs.org/blog/electron-9-0#breaking-changes.

The documentation here states this fact as well: https://www.electronjs.org/docs/api/ipc-renderer#ipcrendererinvokechannel-args.  If you have further questions about this, you can ask at [the Electron Discord server](https://discord.com/invite/electron).

**Comment by KaKi87** [comment]
Hi,

I'm encountering this issue even using `JSON.stringify`, though not systematically.

Is there something else than the variable type that triggers this error ?

Here's my main process code :

```js
mainWindow.webContents.send(
    'someEvent',
    JSON.stringify({
        someStringKey: someStringValue
    })
);
```

And here's my renderer code :

```js
ipcRenderer.on('someEvent', (_, data) => {
    try {
        doSomethingWith?.(data);
        console.log(data);
    }
    catch(error){
        console.log(error, data);
    }
});
```

For example, here I'm sending data regarding HTTP requests, one row is processed successfully, the other isn't :

![](https://github.com/user-attachments/assets/d2400e57-f91e-47c2-afa2-663df528499c)

Here's the raw string that works :

```
{"requestId":"484600.124","responseStatus":200,"responseHeaders":{"accept-ranges":"bytes","access-control-allow-origin":"*","age":"83460","cache-control":"public, max-age=31536000, immutable","content-encoding":"br","content-length":"4528","content-type":"text/css","cross-origin-resource-policy":"cross-origin","date":"Thu, 04 Dec 2025 14:33:39 GMT","etag":"\"0x8DE311E0482BB2E\"","last-modified":"Mon, 01 Dec 2025 21:10:12 GMT","server":"Windows-Azure-Web/1.0 Microsoft-HTTPAPI/2.0","vary":"Accept-Encoding","via":"1.1 varnish, 1.1 varnish","x-cache":"HIT, HIT","x-cache-hits":"17, 7","x-fastly-request-id":"866b4224060895af341ad205189522e16569f0c9","x-served-by":"cache-iad-kjyo7100153-IAD, cache-par-lfpg1960026-PAR"}}
```

And here's the raw string that doesn't work :

```
{"requestId":"484600.250","responseStatus":200,"responseHeaders":{"accept-ranges":"bytes","access-control-allow-origin":"*","age":"1789439","cache-control":"public, max-age=31536000, immutable","content-encoding":"br","content-length":"569","content-type":"text/css","cross-origin-resource-policy":"cross-origin","date":"Thu, 04 Dec 2025 14:30:10 GMT","etag":"\\"0x8DE22F062EF5439\\"","last-modified":"Thu, 13 Nov 2025 20:08:18 GMT","server":"Windows-Azure-Web/1.0 Microsoft-HTTPAPI/2.0","vary":"Accept-Encoding","via":"1.1 varnish, 1.1 varnish","x-cache":"HIT, HIT","x-cache-hits":"58, 32459","x-fastly-request-id":"b852cef2eebb2464a98386aeaeb7daa0aa9e519a","x-served-by":"cache-iad-kjyo7100057-IAD, cache-par-lfpg1960056-PAR"}}
```

Thank you
