### ISSUE TITLE
How to update the differences？i use electron-squirrel-startup

### ISSUE THREAD

**Issue by chenqianwen** [electron/electron#26339]
How to update the differences？
copy app-1.0.0 to app-1.0.1 and replace app.asar ，Is that right?
i use electron-squirrel-startup

**Comment by jkleinsc** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
