### ISSUE TITLE
can't run preload script twice or in multiple webview, 

### ISSUE THREAD

**Issue by IliyaBrook** [electron/electron#26340]
### Expected Behavior
when running 2 WebView the preload script runs only on the first webview

### Actual Behavior
preload script must run second time when WebView call the script again

**Comment by IliyaBrook** [comment]
the method that run to send data to preload 

  onLoad(webViewSelect, userID, pass) {
    const webview = document.querySelector(webViewSelect)
    webview.addEventListener('dom-ready', () => {
      const url = webview.getURL()
      if (url === 'http://centrex.bezeq.com/Login/') {
        webview.send('changeUser', {
          elementName: 'EnteredUserID',
          value: userID
        })
        webview.send('changePass', {
          elementName: 'Password',
          value: pass
        })
        webview.addEventListener('did-stop-loading', () => {
          webview.send('logIn')
          webview.openDevTools()
        })
        webview.send('log-in', window.submitForm)
      }
    })
  }



first webview

import React, { Component } from 'react'
import './Cluster1-window.css'
const WebView = require('react-electron-web-view')

export default class Cluster1Window extends Component {
  componentDidMount() {
    // eslint-disable-next-line react/prop-types
    this.props.onLoad('WebView', '123123', '123123')
    console.log('1')
  }

  render() {
    const preloadPath = `file:${require('path').resolve(__static, './preload.js')}`
    return (
      <div className="webViewBody" id="webViewBody">
        <WebView src="http://centrex.bezeq.com"
          useragent="Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; AS; rv:11.0) like Gecko"
          className="webView"
          contextIsolation='no'
          preload={preloadPath}
          partition="class1"
          nodeIntegration
          nodeintegrationinsubframes
        />
      </div>

    )
  }
}


second webview 


import React, { Component } from 'react'
import './Cluster2-window.css'
const WebView = require('react-electron-web-view')

export default class Cluster2Window extends Component {
  componentDidMount() {
    // eslint-disable-next-line react/prop-types
    this.props.onLoad('WebView', '890120495', 'A@123456')
    console.log('2')
  }

  render() {
    const preloadPath = `file:${require('path').resolve(__static, './preload2.js')}`
    return (
      <div className="webViewBody" id="webViewBody">
        <WebView src="http://centrex.bezeq.com"
          useragent="Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; AS; rv:11.0) like Gecko"
          className="webView"
          preload={preloadPath}
          partition="class2"
          nodeintegrationinsubframes
          nodeIntegration
        />
      </div>
    )
  }
}

**Comment by jkleinsc** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
