### ISSUE TITLE
Critical typo in the German translation of `quick-start`

### ISSUE THREAD

**Issue by s9ferech** [electron/electron#26343]
In the German translation of `electron/docs/tutorial/quick-start.md`, the command `node -v` was incorrectly translated as `knode -v`.

**Comment by s9ferech** [comment]
There are also many other errors in the code snippets of the German translation of this file.

**Comment by MarshallOfSound** [comment]
Should this be moved over to the i18n repo, there's nothing anyone can do in this repo to fix this? @electron/wg-ecosystem

**Comment by erickzhao** [comment]
All internationalization copy errors should be over at CrowdIn. I don't think tracking them on any of the GitHub repos is that helpful, since there's no PR that can be made for the docs.

The file in question: https://crowdin.com/translate/electron/174660/en-de?filter=basic&value=18

**Comment by Dharmesh78** [comment]
Hello, I am very new to open source contributions. 
**There's an issue in the german translation of quick-start in Run your application.**
I want to fix this issue.
**Can someone please guide me on how to proceed?**

**Comment by erickzhao** [comment]
Hi @Dharmesh78, check out the instructions over at: https://github.com/electron/i18n/blob/master/contributing.md

**Comment by KishkinJ10** [comment]
can i contribute on this ? can you tell what i have to do?

**Comment by obrmao** [comment]
@KishkinJ10 I went through the document and its links at https://github.com/electron/i18n/blob/master/content/10-x-y/de-DE/docs/tutorial/quick-start.md and I believe this issue is no longer a problem, there were commits in middle of november that seemed to take care of the issue.

Please close or provide an updated description

**Comment by xemovie** [comment]
This is a best movie https://www.xemovie.com/movies/godzilla-vs-kong-2021
Click link to watch more
