### ISSUE TITLE
Unexpected error 'Electron failed to install correctly' when use esbuild to bundle typescript

### ISSUE THREAD

**Issue by gz-wangxm** [electron/electron#26342]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
* **Electron Version:**
  * 10.1.5
* **Operating System:**
  * Windows 10 (2004) (19041.572)
* **Last Known Working Electron version:**
  * Not tried out yet

### Expected Behavior
I used esbuild to bundle my typescript. The command went:

    esbuild ./src/renderer.ts --bundle --platform=node > ./src/renderer.js

And then I launched the app with

    electron ./src/main.js

I expect the application to work properly.

### Actual Behavior
In the console of the BrowserWindow it immediately gave me this error:
![image](https://user-images.githubusercontent.com/50190888/98112981-f4499200-1edd-11eb-8eb5-7b43617d7d0d.png)

### To Reproduce
I'm sorry that because of poor Internet connection, I cannot use Fiddle.

The repository is at https://github.com/gz-wangxm/electron-quick-start.

Clone it and run

    npm install
    npm start

And press Ctrl+Shift+I. Switch to Console and you'll see:

![image](https://user-images.githubusercontent.com/50190888/98117914-5bb71000-1ee5-11eb-83a7-a180877ba363.png)

### Screenshots
![image](https://user-images.githubusercontent.com/50190888/98113497-b4cf7580-1ede-11eb-817c-21ca89afc4f1.png)

### Additional Information

**Comment by jkleinsc** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
