### ISSUE TITLE
Spellchecker tutorial docs do not mention how to disable spellchecker after the browser window is created 

### ISSUE THREAD

**Issue by aabuhijleh** [electron/electron#26349]
In `/docs/tutorial/spellchecker.md` and `/docs/api/session.md`

Passing an empty array like this `browserWindow.webContents.session.setSpellCheckerLanguages([])` works for disabling spellchecking on Windows and macOS

The docs say `Note: On macOS the OS spellchecker is used and will detect your language automatically. This API is a no-op on macOS.` which is not accurate

You can re-enable spellchecking by `session.setSpellCheckerLanguages(yourLanguageCodes)`. On macOS, the languages you set here don't matter but spellchecking will be re-enabled

I think this is useful to know. In my case, I add an option in the context menu to let users disable/enable spellchecking on the fly
<img width="231" alt="disable" src="https://user-images.githubusercontent.com/42934634/98216916-65c32800-1f52-11eb-9f4e-5835b1cb4ed4.png">

**Comment by MarshallOfSound** [comment]
I don't think we want to document this as it is currently a _side effect_ and not actually intended as a feature, it's a performance optimization that should not be applied on macOS and in fact we will probably go with our documentation and make it a noop on macOS.  Toggling spellcheck on / off correctly is a feature that I believe we have a PR open for right now that does it properly

**Comment by aabuhijleh** [comment]
Thanks for the clarification
