### ISSUE TITLE
Error app undefined in preLoad with contextIsolation true

### ISSUE THREAD

**Issue by plusflabby** [electron/electron#26345]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
10.1.5
* **Operating System:**
Windows 10 x64
* **Last Known Working Electron version:**

### Expected Behavior
App relaunches and exits current app.

### Actual Behavior
app is undefined
```
Uncaught Error: Uncaught TypeError: Cannot read property 'relaunch' of undefined
```
### To Reproduce
Use preLoad.js
```
const { contextBridge, app } = require('electron');
contextBridge.exposeInMainWorld(
    'electron',
    {
        UpdateNow: () => {
            app.relaunch();
            app.exit();
        },
    }
  );
```
Call this with javascript
```
window.electron.UpdateNow()
```
repo with error
https://github.com/plusflabby/electron-quick-start

**Comment by MarshallOfSound** [comment]
`app` is a main process only API, you can't (and have never been able to) access it from the renderer process.  You'll have to use IPC to ask the main process to call `app.relaunch()`
