### ISSUE TITLE
Cannot click a button in a BrowserView -- MouseEvents are captured by drag?

### ISSUE THREAD

**Issue by ccorcos** [electron/electron#26355]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** v11.0.0-beta.19
  * 
* **Operating System:** macOS 11.0.1
  * 
* **Last Known Working Electron version:**
  * 

I've created a minimal repro for you. Download the repo:

```sh
git clone git@github.com:ccorcos/electron-browser-view-drag.git
cd electron-browser-view-drag
git checkout side-browser-view
npm install
npm start
```
There's a the default index.html inside the window's webview, and what I did is add a `BrowserView` to render `search.html` and you'll notice that button is not clickable. However, you can drag the whole window when you click in there...

### Expected Behavior
Should be able to click the button inside a BrowserView.

**Comment by poiru** [comment]
It seems like there has been a regression in Electron 11. The BrowserView seems to always be a draggable region regardless of `-webkit-app-region`. Electron 10 works fine. cc @codebytere

**Comment by codebytere** [comment]
Gist version: https://gist.github.com/060ad478da5b628726da4b4ea94a16a6

**Comment by codebytere** [comment]
@poiru i'm not sure what you mean and did not see drag behavior in frameless windows where none was enabled 🤔 Do you have a specific repro in mind? 

@ccorcos PR is up to address this one
