### ISSUE TITLE
electron 11.0.0-beta.19 and  better-sqlite3  7.1.1  macOS build issue

### ISSUE THREAD

**Issue by gaodeng** [electron/electron#26364]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * electron 11.0.0-beta.19
* **Operating System:**
  * macOS 11.0.1 Beta (20B5022a)
* **Last Known Working Electron version:**
  * electron 11.0.0-beta.11

### Expected Behavior
better-sqlite3 build without issue
### Actual Behavior
```
electron-rebuild -f --arch=arm64

⠙ Building module: better-sqlite3, Completed: 0  TOUCH b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
⠹ Building module: better-sqlite3, Completed: 0  ACTION deps_sqlite3_gyp_locate_sqlite3_target_extract_sqlite3 b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
⠴ Building module: better-sqlite3, Completed: 0  TOUCH Release/obj.target/deps/locate_sqlite3.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o
⠹ Building module: better-sqlite3, Completed: 0  LIBTOOL-STATIC Release/sqlite3.a
⠙ Building module: better-sqlite3, Completed: 0  CXX(target) Release/obj.target/better_sqlite3/src/better_sqlite3.o
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
⠴ Building module: better-sqlite3, Completed: 0In file included from ../src/better_sqlite3.cpp:4:
In file included from ./src/better_sqlite3.lzz:10:
In file included from /Users/gaodeng/Documents/work/moonfm/moonfmelectron/node_modules/better-sqlite3/11.0.0-beta.19/include/node/node.h:67:
In file included from /Users/gaodeng/Documents/work/moonfm/moonfmelectron/node_modules/better-sqlite3/11.0.0-beta.19/include/node/v8.h:30:
/Users/gaodeng/Documents/work/moonfm/moonfmelectron/node_modules/better-sqlite3/11.0.0-beta.19/include/node/v8-internal.h:418:38: error: 
      no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
            !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                ~~~~~^~~~~~~~~~~
                                     remove_cv
/Users/gaodeng/Desktop/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:697:50: note: 
      'remove_cv' declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
                                                 ^
⠧ Building module: better-sqlite3, Completed: 01 error generated.
make: *** [Release/obj.target/better_sqlite3/src/better_sqlite3.o] Error 1
rm b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
✖ Rebuild Failed


```

### To Reproduce
install electron beta and install better-sqlite3 
build with electron-rebuild

**Comment by gaodeng** [comment]
I don’t know much about node gyp, but it seems that it can be compiled by changing the xcode_settings -std=c++11 in the binding.gyp file of better-sqlite3 to -std=c++14

**Comment by MarshallOfSound** [comment]
Yeah you're building the native module with a version of the std library that doesn't support what V8 now requires.  As you determined, you need to bump your `-std` flag 👍

**Comment by Githubber2021** [comment]
Hi, could you elaborate that? I just got the same issue with Xcode 12. I am hesitant to modify the binding file manually since I am using it in a pipeline

**Comment by ahmadwaliesipick** [comment]
> Yeah you're building the native module with a version of the std library that doesn't support what V8 now requires. As you determined, you need to bump your `-std` flag 👍
@MarshallOfSound @gaodeng 
Can you please explain more which std version require? i am using Apple Silicon Big Sur machine.
