### ISSUE TITLE
Is there a way to display the UI when launching the app as SYSTEM process?

### ISSUE THREAD

**Issue by 20matan** [electron/electron#26383]
Hey,
In my company we are trying to create an application which needs an admin privileges in order to launch some other processes from the electron.
Also, we don't want to display the UAC to the users.
In order to bypass the UAC, we created a scheduled task, which points to the installed exe file, so when user wants to launch the application he actually click on a shortcut that launches the scheduled task, and ta-dah, no UAC.
But, the issue we are currently having is that there are some customers who have a non-administrate user, so they can't install nor launch the application.
We are looking for a solution which an admin user will install the application for them, and they will be able to launch it and the application will be able to launch sub-processes with admin rights.
We tried to use a SYSTEM windows service which is running in the background, and when user logs in to the system, the application will be launched for him, but, if we launch the application as SYSTEM, there is no UI; and if we launch the application as we impersonate to the logged-in user, the process privilege is not admin so the sub-processes will not be launched.

The solution we thought about is to separate the electron processes - the renderer process and the gpu-process, and then launch the renderer process with the user privilege (so he will see the UI), and the gpu-process will be launched with SYSTEM privilege (and the sub-processes will be able to run with system/admin privilege)

The questions are:
1. Do you have any alternative suggestions which are the "best practice" for this scenario?
2. If not, then do you think that our suggested solution can work? Is it practical?
the UI and the gpu process are communicating using the IPC, so, will it work "as is"? or will we need (as i assume) to customize some things in order to make the communication work?

Thanks :)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
