### ISSUE TITLE
getSystemVersion returns wrong version for Big Sur 

### ISSUE THREAD

**Issue by idanwork** [electron/electron#26419]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.5
* **Operating System:**
  * macOS 10.16 
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
On Big Sur, Apple changed the versioning from 10.x.y to 11.x.y
https://en.wikipedia.org/wiki/MacOS_Big_Sur

Expected to get 11.0.1 from calling  _getSystemVersion_ 

### Actual Behavior
Calling  _getSystemVersion_  returns 10.16

This is true for an Intel based machine,  I haven't tried it with Apple Silicon which requires electron v11.

### To Reproduce

On Big Sur system, run electron and call to  _getSystemVersion_  

### Screenshots
N/A

### Additional Information
N/A

**Comment by ckerr** [comment]
Upstream bug: https://crbug.com/1108832

Electron's `getSystemVersion()` uses [SysInfo::OperatingSystemVersion], which ultimately winds up calling the macOS function `operatingSystemVersion()`:

https://source.chromium.org/chromium/chromium/src/+/master:base/system/sys_info_mac.mm;l=56

```cc
  NSOperatingSystemVersion version =
      [[NSProcessInfo processInfo] operatingSystemVersion];
  *major_version = version.majorVersion;
  *minor_version = version.minorVersion;
  *bugfix_version = version.patchVersion;

  // TODO(https://crbug.com/1108832): If an app is built against a pre-macOS
  // 11.0 SDK, macOS will lie as to what version it is, saying that it is macOS
  // "10.16" rather than "11.0". The problem is that the "IsOS/IsAtLeastOS/
  // IsAtMostOS" functions are driven from the Darwin version number, which
  // isn't lied about, and therefore the values returned by this function and
  // those functions are inconsistent. Therefore, unlie about these values.
```

**Comment by idanwork** [comment]
Thanks for the quick response and the info!

**Comment by ckerr** [comment]
Oh, I've misread the comment and the code that came _after_ the comment. The Chromium code in [Electron 11 ... master] has an upstream short-term workaround for this issue that should also be backported to older supported versions:

```diff
+  if (*major_version == 10 && *minor_version >= 16) {
+    *major_version = *minor_version - 5;
+    *minor_version = *bugfix_version;
+    *bugfix_version = 0;
+  }
```

Upstream change id: https://chromium-review.googlesource.com/#/q/I2ca92478d76bf572cc55875cba443f4978482d10

**Comment by nornagon** [comment]
Can this be marked fixed?

**Comment by idanwork** [comment]
Sorry forgot about this since I've updated to v11.
I tested it now with 10.4.0 and it works
