### ISSUE TITLE
Segfault when calling app.quit in 'did-navigate' event handler

### ISSUE THREAD

**Issue by JOT85** [electron/electron#26423]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v10.1.5
* **Operating System:**
  * Arch Linux
* **Last Known Working Electron version:**
  * Can't find a working version, I've tried v6.1.12, v9.3.4, v10.1.5 (from the Arch repo) and v11.0.0-beta.20 from github. Notably, the error for v11 was SIGTRAP.

### Expected Behavior
The window to open and, upen navigation, to immediately quit.

### Actual Behavior
`“electron test.js” terminated by signal SIGSEGV (Address boundary error)`

### To Reproduce
```js
const { app, BrowserWindow } = require('electron')

app.whenReady().then(() => {
    const win = new BrowserWindow()
    win.webContents.on("did-navigate", () => app.quit())
    win.loadURL("https://example.com/")
})
```
Then run `electron test.js`

**Comment by ckerr** [comment]
gist version of @JOT85's repro:

https://gist.github.com/ckerr/d6c4cb50635d1d2dca939ce51df84b92

**Comment by JOT85** [comment]
Thanks so much!

**Comment by DonAtMabl** [comment]
I'm seeing segfaults from this when a user selets a menu item with a role of `quit` as well. I haven't simplified the problem down, yet.

**Comment by codebytere** [comment]
This has been resolved in recent versions of Electron
