### ISSUE TITLE
Google Analytics 4 can not work with Electron

### ISSUE THREAD

**Issue by Brijeshlakkad** [electron/electron#26421]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

Hello,

I wanted to use Google Analytics 4 in my electron app, but it seems that because `file://` protocol I can not use it as expected.

### Proposed Solution
We can open an application on HTTP protocol with a defined available port. Or developers can configure this to use dependencies that need some defined environment like here, GA4.

Please look into this.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

**Comment by tombertrand** [comment]
If you find a solution for this issue, please let us know. Tried using this https://www.simoahava.com/analytics/run-google-tag-manager-google-analytics-local-files/, publishing a GTM container with disabled protocol check without success. The collect endpoint is not being called and the GA4 event report remains empty.

**Comment by Amethystafyy282** [comment]
> If you find a solution for this issue, please let us know. Tried using this https://www.simoahava.com/analytics/run-google-tag-manager-google-analytics-local-files/, publishing a GTM container with disabled protocol check without success. The collect endpoint is not being called and the GA4 event report remains empty.

Hi, have you found a solution for this?

**Comment by tombertrand** [comment]
Yes, we're using a slightly modified version of this class and the events are being sent correctly https://gist.github.com/IjzerenHein/df3f65093038dd70ad871f926be6f45e/6b50659729b0acd8c80eabb30bc01df0d5a47d0a

**Comment by leohxj** [comment]
https://developers.google.com/analytics/devguides/collection/protocol/ga4

gtag does not work with `file://`

**Comment by fpolowood** [comment]
> 

@tombertrand Do you mind sharing the modified class, or point to the modifications?  Thanks

**Comment by hajeonghun** [comment]
I have created a library dedicated to GA4 that currently supports the event function.

https://www.npmjs.com/package/electron-google-analytics4

**Comment by pavan-singh-iphtech** [comment]
I am still trying to connect my electron app to google analytics but I can't, I am using electron version:     "electron": "^26.0.0",

**Comment by pavan-singh-iphtech** [comment]
> https://developers.google.com/analytics/devguides/collection/protocol/ga4
> 
> gtag does not work with `file://`

> I think, gtag is only work in context of run server in browser in context of electron it is not working

**Comment by pavan-singh-iphtech** [comment]
> I have created a library dedicated to GA4 that currently supports the event function.
> 
> https://www.npmjs.com/package/electron-google-analytics4

>No, this library is not working fine when we use electron v:30 and Angular v:16
