### ISSUE TITLE
LC_ALL set to invalid value

### ISSUE THREAD

**Issue by lights0123** [electron/electron#26443]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.3.4
* **Operating System:**
  * Arch Linux
* **Last Known Working Electron version:**
  * 9.3.3

### Expected Behavior
```
❱ echo lang: $LANG lc_all: $LC_ALL
lang: en_US.UTF-8 lc_all:
❱ electron9 -i                    
> process.env.LC_ALL
undefined
```

### Actual Behavior
```
❱ echo lang: $LANG lc_all: $LC_ALL
lang: en_US.UTF-8 lc_all:
❱ electron9 -i                    
> process.env.LC_ALL
'en_US'
```

`en_US` is not a valid locale—it has to be `en_US.UTF-8`, however, Electron overrides this, even if `--lang=en_US.UTF-8` is passed or `LC_ALL` is set correctly when invoking Electron. With this invalid value, many C programs fail to run.

### To Reproduce
Run the above commands.

### Additional Information
Problem introduced in  #26242

**Comment by codebytere** [comment]
cc @zcbenz ☝🏻

**Comment by klarkc** [comment]
It broke VSCode terminal for some reason, `locale` in bash is reporting strange 'pt-BR' nonexistent locale.

**Comment by angelsl** [comment]
Why is Electron playing with the locale environment variables? That is typically a system-wide setting, and Electron shouldn't be overriding it for itself.

**Comment by jorgelaranjo** [comment]
Downgrade Electron https://github.com/microsoft/vscode/issues/110322#issuecomment-726426703
