### ISSUE TITLE
before-input-event

### ISSUE THREAD

**Issue by tony2016-0608** [electron/electron#26445]
Before-input-event, the event window keyboard input is fine, but the input field in the window with the iFrame open is going to collide with the event input field. Only the input field in the iFrame works, so the input field in the iframe cannot be used
I installed several Window machines, some without conflict, some without conflict

**Comment by tony2016-0608** [comment]
Windows 10 17763.1518 can
Windows 10 18362.30  can
Windows 10 18362.959  can
Windows10 18362.1139 does not work

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 10 days if the above is not addressed.

**Comment by tony2016-0608** [comment]
### Preflight Checklist


* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.2.1
* **Operating System:**
  * windows10
* **Last Known Working Electron version:**
  * 

### Expected Behavior
Before-input-event listens for this event, and I want each of the two functions to keep their own behavior, to pop up a window when I type on a page, and to type characters when I type in an iframe
Don't interfere with each other

### Actual Behavior
Before-input-event listening for this event, I need to capture the keyboard input event, and when I capture the input it pops up a window, which works really well,
But I have an iframe on my render page that's embedded in a web page, and there's an input field on the page, and when I type in a character, it opens the window of the window.


### To Reproduce


### Screenshots


### Additional Information

**Comment by tony2016-0608** [comment]
#
