### ISSUE TITLE
webContents.print() don't work when load pdf

### ISSUE THREAD

**Issue by Jan307** [electron/electron#26448]
### Issue Details

* **Electron Version:*^10.1.5*
  * 
* **Operating System:*macOs 10.15.6 *
  * 
* **Last Known Working Electron version:**
  * 

### Actual Behavior

after click print button, don't sent task to printer

### To Reproduce

```sh
let win: BrowserWindow | null = null;
  win = new BrowserWindow({
    ...MAIN_WIN_SIZE,
    show: false,
    frame: true,
    webPreferences:
      {
            webviewTag: true,
            nodeIntegration: true,
            webSecurity: false,
            allowRunningInsecureContent: true,
            plugins: true,
            enableRemoteModule: true,
          }
       
  });

  win.loadURL('file:///Users/Downloads/test.pdf');

  win.webContents.on('did-finish-load', () => {
    if (!win) {
      throw new Error('"win" is not defined');
    }
    win.show();
    win.webContents.print(
      { deviceName: '_23f__f_3e_0f__', pageSize: 'A4' },
      (success, errorType) => {
        if (!success) {
          console.log('printError', errorType);
        } else {
          console.log('print success');
        }
      }
    );
  });
```

**Comment by codebytere** [comment]
That's expected behavior at present - our PDF viewer is implemented via Chromium's extensions handling and cannot be printed via `webContents.print()`.

**Comment by LFdeWeb** [comment]
Is there any method to print a pdf ?

**Comment by LFdeWeb** [comment]
> That's expected behavior at present - our PDF viewer is implemented via Chromium's extensions handling and cannot be printed via `webContents.print()`.



> That's expected behavior at present - our PDF viewer is implemented via Chromium's extensions handling and cannot be printed via `webContents.print()`.


Is there any way to achieve it

**Comment by LFdeWeb** [comment]
> ### Issue Details
> * **Electron Version:_^10.1.5_
>   
>   *
> * **Operating System:*macOs 10.15.6 *
>   
>   *
> * **Last Known Working Electron version:**
>   
>   *
> 
> ### Actual Behavior
> after click print button, don't sent task to printer
> 
> ### To Reproduce
> ```shell
> let win: BrowserWindow | null = null;
>   win = new BrowserWindow({
>     ...MAIN_WIN_SIZE,
>     show: false,
>     frame: true,
>     webPreferences:
>       {
>             webviewTag: true,
>             nodeIntegration: true,
>             webSecurity: false,
>             allowRunningInsecureContent: true,
>             plugins: true,
>             enableRemoteModule: true,
>           }
>        
>   });
> 
>   win.loadURL('file:///Users/Downloads/test.pdf');
> 
>   win.webContents.on('did-finish-load', () => {
>     if (!win) {
>       throw new Error('"win" is not defined');
>     }
>     win.show();
>     win.webContents.print(
>       { deviceName: '_23f__f_3e_0f__', pageSize: 'A4' },
>       (success, errorType) => {
>         if (!success) {
>           console.log('printError', errorType);
>         } else {
>           console.log('print success');
>         }
>       }
>     );
>   });
> ```
> 
> ### Screenshots
> ### Additional Information


Is there any way to achieve it

**Comment by afif-malghani** [comment]
There is the pdf-to-printer module which can send the print job
