### ISSUE TITLE
Electron App cann't start on Apple Silicon （MacOS 11.0.1 beta）

### ISSUE THREAD

**Issue by ljy-xian** [electron/electron#26458]
### Preflight Checklist

* [ ☑️] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [☑️ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [☑️ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
V11.0.0-beta18
* **Operating System:**
Apple Silicon MacOS 11.0.1 beta
* **Last Known Working System version:**
MacOS 11.0 beta

I'm a developer. Our product is adapting to Apple silicon. we are doing as the following step:
1.update the electron version from 8.2.5 to 11.0.0-beta18
2. build the electron app on platform darwin arch x64
3. run the electron app on apple silicon, MacOS big sur 11.0 beta version. The app works 
4. update the big sur version from 11.0 beta to 11.0.1 beta . The app can not  work
![image](https://user-images.githubusercontent.com/10915655/98910598-60d81880-24fe-11eb-9981-595d3dd47c7f.png)
5. download original image and run , it can not work too
![image](https://user-images.githubusercontent.com/10915655/98910538-49009480-24fe-11eb-9137-84717ee52b83.png)

 How can I fix it ? Thank you

**Comment by Pharlon** [comment]
any progress here?
same problems on MacOS 11.0.1 with Electron v11 stable release
