### ISSUE TITLE
Add powerMonitor IsOnBatteryPower method

### ISSUE THREAD

**Issue by Ricket** [electron/electron#26457]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
[powerMonitor](https://www.electronjs.org/docs/api/power-monitor) triggers events when the computer goes on AC or on battery. But there's no way to know on app startup whether the system is already on battery or AC. An event isn't triggered until the state change happens.

I learned from [this comment](https://github.com/electron/electron/issues/18457#issuecomment-496628006) that Electron inherits powerMonitor from Chromium. Well, Chromium's `PowerMonitor` class has a [IsOnBatteryPower](https://chromium.googlesource.com/chromium/src/+/master/base/power_monitor/power_monitor.h#52) method.

### Proposed Solution
Add an `isOnBatteryPower` method to the [powerMonitor](https://www.electronjs.org/docs/api/power-monitor) module.

### Alternatives Considered
Alternatively, Electron could fire the `on-ac` or `on-battery` event on app startup. In fact, perhaps this should also be the case. (I verified it does not currently do this)

### Additional Information
n/a

**Comment by Ricket** [comment]
Thank you @nornagon !

**Comment by nornagon** [comment]
Thanks @Ricket for the suggestion and the helpful research!
