### ISSUE TITLE
App is crashed when I set nativeWindowOpen and nodeIntegration is true in version 7.3.2

### ISSUE THREAD

**Issue by cuonghx** [electron/electron#26459]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * `7.3.2`
* **Operating System:**
  *  `Windows 10`
* **Last Known Working Electron version:**
  * `8.0.0`

### Expected Behavior

My app is working on Electron version 7.3.2
### Actual Behavior

Currently, I'm trying to open external URL from renderer process by using window.open. To do that, I set nodeIntegration and nativeWindowOpen is true when I create new BrowserWindow. It will work, if I use electron version at least 8.x, but Electron 7.x will be crashed.
### To Reproduce

This is demo source code to reproduce bug: 
[window-open-app.zip.zip](https://github.com/electron/electron/files/5529219/window-open-app.zip.zip)

**Comment by codebytere** [comment]
@cuonghx 7.x is [no longer supported by Electron](https://www.electronjs.org/docs/tutorial/support#supported-versions) - you should be using 8.x or newer

**Comment by cuonghx** [comment]
> @cuonghx 7.x is [no longer supported by Electron](https://www.electronjs.org/docs/tutorial/support#supported-versions) - you should be using 8.x or newer

Thanks for answering me back.
