### ISSUE TITLE
Bluescreen UNEXPECTED_KERNEL_MODE_TRAP

### ISSUE THREAD

**Issue by oledid** [electron/electron#26453]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * ?
* **Operating System:**
  * Windows 10 Pro (20H2)
* **Last Known Working Electron version:**
  * ?

### Expected Behavior

When I use an electron app, like Visual Studio Code or Microsoft Teams, and press `WIN` + `SHIFT` + `LEFT` multiple times so that the entire app moves to the next screen (left), I do not get a bluescreen.

### Actual Behavior

When I use an electron app, like Visual Studio Code or Microsoft Teams, and press `WIN` + `SHIFT` + `LEFT` multiple times so that the entire app moves to the next screen (left), I get a blue screen UNEXPECTED_KERNEL_MODE_TRAP.

### To Reproduce

Use an electron app, like Visual Studio Code or Microsoft Teams, and press `WIN` + `SHIFT` + `LEFT` multiple times so that the entire app moves to the next screen (left), until there are no more screens to the left, then appears at the rightmost screen, and jumps leftward. Repeat 3 times * [number of screens] and you should get the bluescreen.

### Screenshots

Not possible.

### Additional Information

I am aware that this is probably not the right place to post this, but MAYBE it is, so I'm going for it.

I have 3 screens where the leftmost is flipped 90 degrees, so they look like this: | - -

**Comment by oledid** [comment]
Current workaround: Remap Windows keyboard shortcuts to disable `WIN` + `SHIFT` + `LEFT` and `WIN` + `SHIFT` + `RIGHT`

**Comment by ckerr** [comment]
@oledid, if you take a "hello world" style Electron app e.g. https://github.com/electron/electron-quick-start, do you see the same behavior there?

```sh
$ git clone https://github.com/electron/electron-quick-start
$ cd electron-quick-start
$ npm install
$ npm start
```

**Comment by oledid** [comment]
Hi

Thanks.

I just managed to get the bluescreen with a non-electron app. So I am closing the issue.

This comment is posted from my smartphone 😄
