### ISSUE TITLE
App crashes after entering first character in debug console

### ISSUE THREAD

**Issue by niedzielski** [electron/electron#2645]
Electron v0.31.1
Linux Mint 17.1
1. Launch the app via `node_modules/.bin/electron .`
2. Open Developer Tools.
3. Set a breakpoint on bar.
4. Refresh the app so the breakpoint hits.
5. Open the console and type b.

The debugger crashes at this point. The issue is also present on v0.31.0 but not v0.30.6.

The app is almost nothing. My main.js is pretty bare bones and can be supplied upon request but here's the index.html:

```
<!doctype html>
<html>
  <head>
    <meta charset='utf-8'>
    <title>foo</title>
   </head>

  <script>
    var bar = 1;
    var baz = 2; // set a breakpoint here
  </script>

</html>
```

The crash log is as follows:

```
[13144:0829/220835:ERROR:browser_main_loop.cc(185)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[13170:0829/220836:INFO:renderer_main.cc(200)] Renderer process started
[13187:0829/220848:INFO:renderer_main.cc(200)] Renderer process started
[13198:0829/220856:INFO:renderer_main.cc(200)] Renderer process started
[13170:0829/220856:WARNING:channel.cc(549)] Failed to send message to ack remove remote endpoint (local ID 1, remote ID 1)
Failed to get crash dump id.
Report Id:
```

**Comment by zcbenz** [comment]
I'm not able to reproduce on Ubuntu 14.04, does this still happens to you if you open the default app and  set breakpoint in `index.html`?

**Comment by niedzielski** [comment]
@zcbenz, yes. I've simplified the repro case to that below. I launch the app, open dev tools, refresh the app, open the console, and type "f".

package.json

    {
      "name": "crash-test",
      "version": "0.0.0",
      "main": "main.js",
      "dependencies": {
        "electron-prebuilt": "~0.31.1"
      }
    }

index.html

    <!doctype html>
    <html>
      <head>
        <meta charset='utf-8'>
      </head>

      <script>
          debugger;
      </script>

    </html>

main.js

    var app = require('app');  // Module to control application life.
    var BrowserWindow = require('browser-window');  // Module to create native browser window.

    // Report crashes to our server.
    require('crash-reporter').start();

    // Keep a global reference of the window object, if you don't, the window will
    // be closed automatically when the JavaScript object is GCed.
    var mainWindow = null;

    // Quit when all windows are closed.
    app.on('window-all-closed', function() {
      // On OS X it is common for applications and their menu bar
      // to stay active until the user quits explicitly with Cmd + Q
      if (process.platform != 'darwin') {
        app.quit();
      }
    });

    // This method will be called when Electron has finished
    // initialization and is ready to create browser windows.
    app.on('ready', function() {
      // Create the browser window.
      mainWindow = new BrowserWindow({width: 800, height: 600});

      // and load the index.html of the app.
      mainWindow.loadUrl('file://' + __dirname + '/index.html');

      // Emitted when the window is closed.
      mainWindow.on('closed', function() {
        // Dereference the window object, usually you would store windows
        // in an array if your app supports multi windows, this is the time
        // when you should delete the corresponding element.
        mainWindow = null;
      });
    });

**Comment by zcbenz** [comment]
Seems to be a distribution specific problem.

**Comment by niedzielski** [comment]
Nuts, I'll hang back on v0.30.6 until we can gather more insight. I will add that I'm on a high DPI display which seems to have some surprisingly odd and bad interactions with Atom.

**Comment by niedzielski** [comment]
It seems like I'm still the only person with this issue. The issue is still present for me on v0.32.2.

**Comment by LukeCarrier** [comment]
I'm able to reproduce this on Fedora 22, x64 with Electron 0.33.0.

**Comment by mo** [comment]
I hit this crash as well using 0.33.7 running on ubuntu 15.04 x64

**Comment by inukshuk** [comment]
I'm also affected by this on 0.33.4 on Arch Linux.

**Comment by xeronimus** [comment]
Can confirm this on 0.33.7 and 0.35.1  on ubuntu 14.04 (64bit)

**Comment by niedzielski** [comment]
Same issue on Ubuntu 15.10 64b with electron-prebuilt v0.34.3 and v0.35.1.

**Comment by iofjuupasli** [comment]
```
{ http_parser: '2.5.0',
  node: '4.1.1',
  v8: '4.5.103.29',
  uv: '1.7.4',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '46',
  openssl: '1.0.2d',
  electron: '0.35.4',
  'atom-shell': '0.35.4',
  chrome: '45.0.2454.85' }
```

xubuntu 14.04 (i3wm)
electron v0.35.4

It crashes when stopped on breakpoint, and trying to type anything to console

Also code uses sourceMaps and originally written on es6. However with sourcemap disabled it crashes also.

**Comment by niedzielski** [comment]
Here's an example[0] using electron-quick-start as a base on Ubuntu 15.10 64b:

1. `git clone -b bug/console-crash https://github.com/niedzielski/electron-quick-start.git`
1. `cd electron-quick-start`
1. `npm i && npm start`
1. (Electron window launches.)
1. Press control / command-R to refresh.
1. Type `a` in the debug console.
1. (Electron window crashes.)

[0] https://github.com/atom/electron-quick-start/compare/master...niedzielski:bug/console-crash

**Comment by piascikj** [comment]
The same thing is happening for me on ubuntu 14.10

**Comment by asherkin** [comment]
FWIW, this is quite easy to work-around if this is stopping you from working:

1. Start Electron in GDB: `gdb --args /usr/lib/node_modules/electron-prebuilt/dist/electron .`
2. Set a breakpoint on the broken function: `b TtsPlatformImplLinux::GetVoices`
3. Run the app: `r`
4. When it dumps you back to the GDB shell (when it would have crashed), return from the function: `return`
5. Continue the app: `c`

The dev tools console will now work fine until you restart Electron.

That said, I was getting this crash, and it's working fine since updating to Electron 0.36.0.

**Comment by bendavis78** [comment]
Thanks @asherkin, that tip worked for me when working with Atom. I used `gdb /usr/share/atom/atom` as the gdb command.

**Comment by james-lawrence** [comment]
still seeing this with beta version on arch linux

**Comment by rahatarmanahmed** [comment]
I'm seeing this happen sometimes in electron 1.4.14 on OS X Sierra

**Comment by luchillo17** [comment]
Same behavior in OS X Sierra with:
Electron:  1.6.5 (current beta).
Electron-debug: 1.1.0
Electron-devtools-installer: 2.1.0

**Comment by vxsx** [comment]
Seeing same behaviour in OS X Sierra with Electron 1.6.11

**Comment by ecnepsnai** [comment]
I am also having this problem on macOS 10.12.6 on Electron 1.6.2. Any updates on this? Makes debugging damn near impossible.

**Comment by jdestefx** [comment]
Happening for me on electron v1.8.2-beta.3.   Crashes as soon as I type a single letter into the console.

**Comment by Tomas-M** [comment]
Happening for me too, Windows 64bit.

Electron v1.8.2-beta.3
Chromium v59.0.3071.115
Node v8.2.1v8 v5.9.211.38

As soon as a character is typed into the developer console, electron crashes. Clicking to the console works.

**Comment by jefftimlin** [comment]
I'm also having this issue with Electron v1.8.2-beta3

I downgraded to the current latest (1.7.9) and it's working fine.

**Comment by 3AHAT0P** [comment]
I'm too having this issue with Electron v1.8.2-beta3 on Ubuntu 16.10, 64 bit.

On the current latest (1.7.9) working fine.

**Comment by Mithrilhall** [comment]
Is this still an issue?

OS: Mint 18.2 (KDE 64-bit)
Chrome: Version 63.0.3239.108 (Official Build) (64-bit)

**Comment by Tomas-M** [comment]
I just tested again with latest electron beta3, windows 8.1 64bit, still
the same problem,
app crashes on keypress in developer console.
Enter key or Ctrl+V works fine, but letters like a b c make it crash.


Tomas M

**Comment by rob10e** [comment]
Had same problem, downgrading to 1.7.9 fixed it.
WIndows 10, electron-forge 4.2.0.
Thanks for the tip guys, really hard to debug when you can evaluate code.

**Comment by nickstew** [comment]
I'm having the same issue on Windows:
Electron 1.8.2-beta.4
Windows10 x64
node 8.9.4

Any key in chrome dev console produces this stack trace:
```bash
 ==== C stack trace ===============================
[1]
[1]     GetHandleVerifier [0x00007FF782E8A4AF+182447]
[1]     GetHandleVerifier [0x00007FF782E89175+177525]
[1]     GetHandleVerifier [0x00007FF782E896F0+178928]
[1]     (No symbol) [0x00007FF782DCE530]
[1]     (No symbol) [0x00007FF782C237A5]
[1]     (No symbol) [0x00007FF782C01B01]
[1]     (No symbol) [0x00007FF782BFFF9B]
[1]     (No symbol) [0x00007FF782C1FD42]
[1]     GetHandleVerifier [0x00007FF782F8D8BC+1244348]
[1]     GetHandleVerifier [0x00007FF782FCB8FA+1498362]
[1]     IsSandboxedProcess [0x00007FF78320841E+213902]
[1]     IsSandboxedProcess [0x00007FF783344D48+1510584]
[1]     GetHandleVerifier [0x00007FF782F04268+681576]
[1]     GetHandleVerifier [0x00007FF782EA52B6+292534]
[1]     GetHandleVerifier [0x00007FF782EA3DA0+287136]
[1]     GetHandleVerifier [0x00007FF782F05541+686401]
[1]     GetHandleVerifier [0x00007FF782F05D04+688388]
[1]     GetHandleVerifier [0x00007FF782EA131E+276254]
[1]     IsSandboxedProcess [0x00007FF7832D6CA8+1059864]
[1]     IsSandboxedProcess [0x00007FF7832D8276+1065446]
[1]     IsSandboxedProcess [0x00007FF7835B50B2+4067362]
[1]     IsSandboxedProcess [0x00007FF783968D78+7949544]
[1]     IsSandboxedProcess [0x00007FF7835969FD+3942765]
[1]     IsSandboxedProcess [0x00007FF7835968EC+3942492]
[1]     IsSandboxedProcess [0x00007FF784765EF2+22617698]
[1]     GetHandleVerifier [0x00007FF782F68678+1092216]
[1]     (No symbol) [0x00007FF782B6BF67]
[1]     IsSandboxedProcess [0x00007FF785FA0407+48022391]
[1]     BaseThreadInitThunk [0x00007FF98B3C1FE4+20]
[1]     RtlUserThreadStart [0x00007FF98BBDEFB1+33]
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 3221225477
```

Don't know how to get a better stack trace or handle on why this is happening, but I'm happy to try if you have suggestions.

**Comment by beyondlimits** [comment]
Playing with electron for the first time and even no need to set a breakpoint - it crashes right after typing first character in console.

electron-v1.8.2-beta.4-linux-x64
Ubuntu 16.04.3 (live) with i3wm.

**Comment by jacobq** [comment]
@beyondlimits This issue is open to track exactly the problem you describe. I recommend using 1.7.x until it is fixed.

**Comment by impaler** [comment]
Seems like [beta.5](https://github.com/electron/electron/releases/tag/v1.8.2-beta.5) has fixed the issue for me, no crashing when using the console in devtools for BrowserWindows or webviews. Tested on ubuntu xenial :)

**Comment by jacobq** [comment]
Seems like [Murphy's Law](https://en.wikipedia.org/wiki/Murphy%27s_law) that just after I wrote that a new beta release that fixes the issue would come out... :rocket:  :tada:
