### ISSUE TITLE
Electron is breaking locale environment variables on Linux.

### ISSUE THREAD

**Issue by paeolo** [electron/electron#26464]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  9.3.4
* **Operating System:** 
  *  ArchLinux 5.9.8-arch1-1
* **Last Known Working Electron version:**
  *  9.3.3

### Expected Behavior

Running the command `locale` on a vscode terminal should match `locale` on a terminal. For instance, using the locale `fr_FR.UTF-8` the command should output something like:
```sh
[someone@somewhere ~]$ locale
LANG=fr_FR.UTF-8
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=
```
### Actual Behavior

The vscode terminal issue a warning repeatedly and the `locale` output is not correct.
```sh
bash: warning: setlocale: LC_ALL: cannot change locale (fr)
[someone@somewhere ~]$ locale
LANG=fr_FR.UTF-8
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=C
```
### To Reproduce

* Go on your favorite Linux distribution
* Install `vscode` and `electron 9.3.4`
* Open a terminal in `vscode`, you will see the warning
* Type `locale`, you will see wrong output

### Additional Information

* If I downgrade `electron9` (`9.3.4 -> 9.3.3`) without touching `vscode`, the issue is gone.

**Comment by Thalley** [comment]
I suppose this is the same issue as https://github.com/electron/electron/issues/26443.

**Comment by paeolo** [comment]
I'm closing to avoid duplicates.
