### ISSUE TITLE
Display Refresh Rate

### ISSUE THREAD

**Issue by JamesHannon** [electron/electron#26460]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Would it be possible to add the display refresh rate to the display object?

### Proposed Solution

Adding Refresh rate to the display object https://www.electronjs.org/docs/api/structures/display

### Alternatives Considered

We did look at doing the FPS tracker described in a couple of places but doesn't work with windows that band over multiple displays.

Exec platform-specific executables/plist and parse response

**Comment by codebytere** [comment]
The Display object's properties mirror those [in Chromium](https://source.chromium.org/chromium/chromium/src/+/master:ui/display/display.h;bpv=0) and they do not currently have a refresh rate. Should they add one we will update our properties accordingly, but for now this is not unfortunately something we're able to do.

**Comment by JamesHannon** [comment]
It will indeed, many thanks
