### ISSUE TITLE
How to perform some tasks when windows is shut down or restarted？

### ISSUE THREAD

**Issue by ysbreh** [electron/electron#26481]
How to perform some tasks when windows is shut down or restarted？

Windows10，electron-version=10.1.3

Event: 'shutdown' is not valid for Windows，how to implement it in Windows？

**Comment by pushkin-** [comment]
I guess you mean, when Windows is *about* to shut down. There's a PR [here](https://github.com/electron/electron/pull/24261) that you can follow.

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
