### ISSUE TITLE
Message box missing a close button on Ubuntu

### ISSUE THREAD

**Issue by stevenjoezhang** [electron/electron#26482]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.
(I have found similar issues on Windows: https://github.com/electron/electron/issues/2293 and https://github.com/electron/electron/pull/2556)

### Issue Details

* **Electron Version:**
  *  10.1.5
* **Operating System:**
  *  Ubuntu 20.04.1 LTS x86_64
* **Last Known Working Electron version:**
  *  N/A

### Expected Behavior

The message box created by `dialog.showMessageBox` should contain a close button, e.g. on macOS
<img width="798" alt="截屏2020-11-13 下午5 24 49" src="https://user-images.githubusercontent.com/16272760/99056813-d5ca5180-25d5-11eb-843b-987f40a54941.png">

### Actual Behavior

Message box missing a close button on Ubuntu
![2020-11-13 17-33-01屏幕截图](https://user-images.githubusercontent.com/16272760/99057145-56894d80-25d6-11eb-855f-a72efff66bb7.png)

### To Reproduce

```sh
$ git clone https://github.com/stevenjoezhang/electron-quick-start -b master
$ npm install
$ npm start || electron .
```

### Additional Information

```
:~/electron-quick-start$ screenfetch
                          ./+o+-       
                  yyyyy- -yyyyyy+      OS: Ubuntu 20.04 focal
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 5.4.0-53-generic
           .++ .:/++++++/-.+sss/`      Uptime: 1h 52m
         .:++o:  /++++++++/:--:/-      Packages: 2103
        o:+o+:++.`..```.-/oo+++++/     Shell: bash
       .:+o:+o/.          `+sssoo+/    Resolution: 3640x1920
  .++/+:+oo+o:`             /sssooo.   DE: GNOME 3.36.4
 /+++//+:`oo+o               /::--:.   WM: Mutter
 \+/+o+++`o++o               ++////.   WM Theme: Adwaita
  .++.o+++oo+:`             /dddhhh.   GTK Theme: Yaru [GTK2/3]
       .+.o+oo:.          `oddhhhh+    Icon Theme: ubuntu-mono-dark
        \+.++o+o``-````.:ohdhhhhh+     Font: Cantarell 11
         `:o+++ `ohhhhhhhhyo++os:      Disk: 58G / 1.2T (6%)
           .o:`.syhhhhhhh/.oo++o`      CPU: Intel Core i7-9700 @ 8x 4.7GHz [42.0°C]
               /osyyyyyyo++ooo+++/     GPU: Intel Corporation UHD Graphics 630 (Desktop 9 Series) (rev 02)
                   ````` +oo+++o\:     RAM: 6407MiB / 15794MiB
                          `oo++.      
```

**Comment by pushkin-** [comment]
I think you have to explicitly specify the `buttons` property on Linux for the OK button to appear.

**Comment by ckerr** [comment]
@pushkin has it right, you need a buttons array :smiley:

**Comment by ckerr** [comment]
As an aside, Electron now has a [Discord server](https://discord.com/invite/electron) where app devs can share ideas and information. If that sounds interesting to you, take a look!

**Comment by stevenjoezhang** [comment]
Thanks for your reply! I tried to fix this issue so that the message box has the same behavior on Linux as it does on macOS and Windows: https://github.com/electron/electron/pull/26857
