### ISSUE TITLE
app.getPath() returns wrong paths on macOS Big Sur

### ISSUE THREAD

**Issue by elvinaspredkelis** [electron/electron#26487]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.5
* **Operating System:**
  * MacOS Big Sur (11.0.1)
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
Running `app.getPath('userData')` should return something like _**"/Library/Application Support/Electron"**_

### Actual Behavior
Running `app.getPath('userData')` returns _**"var/root/Library/Application Support/Electron"**_

### To Reproduce

Run `app.getPath()` wherever while using macOS Big Sur.

### Screenshots
N/A

### Additional Information
Same happens using `app.getPath('appData')`.

**Comment by MarshallOfSound** [comment]
Can't reproduce on the latest Bug Sur release 🤔 

![image](https://user-images.githubusercontent.com/6634592/99124903-e7046580-25b7-11eb-825a-2ff87715f782.png)

**Comment by elvinaspredkelis** [comment]
@MarshallOfSound tried restarting my computer a bunch of times, but I still get **var/root/** attached to the paths. It was working perfectly before I've updated to Big Sur.

I attach the screenshot too: ( os.version() throws an error for me, so I've omitted it)


<img width="366" alt="Screenshot 2020-11-14 at 19 15 01" src="https://user-images.githubusercontent.com/6149049/99152949-dafacf80-26ad-11eb-8f2c-98538328ed17.png">

**Comment by MarshallOfSound** [comment]
What error does os.version throw? Also where are your running electron from? Is it your downloads directory?

**Comment by elvinaspredkelis** [comment]
1. `Uncaught TypeError: os.version is not a function at <anonymous>:1:4`. All of the other documented `os` functions appear to be working though.
2. ~/repositories/electron_app
3. No.

**Comment by ckerr** [comment]
> os.version() throws an error for me

This sounds a lot like an installation issue, especially with os.version() throwing.

What happens if you try with a clean install of Electron, e.g.

```sh
$ which electron
electron not found
$ ELECTRON_RUN_AS_NODE=1 npx electron@11.0.1 -p 'process.versions'
$ ELECTRON_RUN_AS_NODE=1 npx electron@11.0.1 -p 'os.version()'
```

**Comment by elvinaspredkelis** [comment]
In the end, it seems like an issue with a boilerplate I was using (electron-vue) rather than an issue with Electron itself.

Not exactly sure what's causing it, but the error has never occurred after I stopped using the boilerplate. Closing. 👏
