### ISSUE TITLE
No handler registered for "channelName" when launch application from windows installer

### ISSUE THREAD

**Issue by akash-sethiya** [electron/electron#26495]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.5.2

* **Operating System:**
  * Windows 10

* **Nodejs Version:**
  * v12.16.1

* **Last Known Working Electron version:**
  * 

### Expected Behavior
Should not throw this error, and should register the IPC channels properly and communication between handle/invoke should work when app launch from the installer

### Actual Behavior
Receiving error "No handler registered for 'channel-name' at EventEmitter../lib/renderer/api/ipc-renderer.ts.ipcRenderer.invoke (electron/js2c/renderer_init.js:1163:19)". IPC handle is not registered and the communication between renderer and main process is not working as expected.

### To Reproduce
* Create a windows installer with target - **nsis**.
* Enable "Launch app" in the installer
* After installing the application, check the launch app checkbox and run the application
* Observe the IPC handler is not registered. Not Updating the UI of the first window. A blank screen appears.

### Additional Information
In the Main process (Main.ts)
```
import {ipcMain} from 'electron';
private registerIpcChannels(ipcChannels: IpcChannelInterface[]) {
        try {
            for(const channel of ipcChannels) {
                ipcMain.handle(channel.getName(), async (event, request) => await channel.handleInvoke(event, request))
            }
        } catch (err) {
            log.error(`Unable to register IPC channels: ${err.message}`, err);
        }
    }

```

In Renderer Process (renderer.js):
```
import electron from 'electron';
sendMessage(msg) {
        let ipc = electron.ipcRenderer;
        ipc.invoke(channelName, msg);
}
```

**Note**: This issue is occurring only when the application is launched from the installer for the first time, after refresh the IPC communication works fine.

**Comment by nornagon** [comment]
Unfortunately without any steps to reproduce this issue we can't debug further. Please provide a small example that reproduces the issue you're seeing, preferable using [Electron Fiddle](https://github.com/electron/fiddle).

Thanks!

**Comment by akash-sethiya** [comment]
Electron Fiddler doesn't seem to have options to create an installer, I just wanted to know that the approach I followed to use IPC handle/invoke is correct or not, and in what circumstances this error occured?

**Comment by nornagon** [comment]
Without a repro, I can't help you. The small amount of code you posted isn't sufficient to determine whether you're using the API correctly. This is why we ask for a full, but minimal working example that exhibits the issue. It doesn't have to be with Fiddle. Another good option for providing an example is to start from [electron-quick-start](/electron/electron-quick-start) and fork it.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
