### ISSUE TITLE
Issue with loading messages

### ISSUE THREAD

**Issue by Gemcord** [electron/electron#26503]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
* **Operating System:**
  * 
* **Last Known Working Electron version:**
  * 

### Additional Information

![image](https://user-images.githubusercontent.com/74492159/99183610-ff4dbf00-2734-11eb-9ea8-ae7581895633.png)

**Comment by Gemcord** [comment]
What is happening with this, i login to bot and all i see is the image above, when you click load messages, nothing happens. What is it?

**Comment by codebytere** [comment]
Please file an issue with Discord - you are welcome to open a new issue if Discord determines it's an upstream issue but this is a consumer issue at present.
