### ISSUE TITLE
missing window close/minimie/maximize button

### ISSUE THREAD

**Issue by madipta** [electron/electron#26502]
OS: POP OS 20.10 64 bit
Node: 12.14.1

missing window close/minimize/maximize button and the window also not movable and not resizable

application tested:
- Postman
- Insomnia Core 2020.4.2 (electron: 9.1.1)
- Vs Code 1.51.0 (electron: 9.3.3)

on the VsCode can be fix on setting "Title Bar Style" to "custom"

**Comment by codebytere** [comment]
This looks to be a problem with individual apps, and not with Electron itself. If this is a problem with Electron itself, please open a new issue with the issue template filled out and a minimum _non app-specific_ reproducible piece of code provided.
