### ISSUE TITLE
Error sending ImageBitmap over ipc

### ISSUE THREAD

**Issue by taltened** [electron/electron#26510]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.3.2 
* **Operating System:**
  * macOS 10.15.7 
* **Last Known Working Electron version:**
  * Unknown 

### Expected Behavior

An `ImageBitmap` object can be sent over ipc, since it [supports structured clone](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm), and all objects supporting structured clone can be sent over ipc as per [electron docs](https://www.electronjs.org/docs/api/ipc-renderer#ipcrendererinvokechannel-args).

### Actual Behavior

Sending an `ImageBitmap` over ipc results in error "An object could not be cloned".

### To Reproduce

https://gist.github.com/25479aa8f0b21401d19ae4642557bfe3

**Comment by nornagon** [comment]
The main process doesn't have DOM support—it's closer to a vanilla Node.js environment, which doesn't have `ImageBitmap`. So unfortunately we can't support sending those DOM objects to the main process as the main process has no way to manipulate them.
