### ISSUE TITLE
cli.js / main.js hangs after execution

### ISSUE THREAD

**Issue by dscalzi** [electron/electron#26527]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.0.0
* **Operating System:**
  * Windows 10 (20H2)
  * Windows 10 (2004)
* **Last Known Working Electron version:**
  * Unknown, issue present since at least early 2020.

### Expected Behavior
Once a call to main.js has completed, the process should terminate. Currently, it hangs until SIGINT signal is sent.

### Actual Behavior
If I say run `node cli.js --version`, the version will be printed and the process will never exit.

### To Reproduce
Run `node cli.js --version`. The process never exits.

### Screenshots
![image](https://user-images.githubusercontent.com/9703873/99329605-98232e00-284c-11eb-9a32-dcdf5765de95.png)
I put in the last logging message as a sanity check. The process does not exit.

### Additional Information
I am running Node.js 14.15.1. This has not worked with Node.js 12.x.x for the past few months either. I'm not sure if this is a windows specific issue. Due to this bug, the following guide is not working https://www.electronjs.org/docs/tutorial/debugging-main-process-vscode

The call to process.exit(0) is having no effect. https://github.com/electron/electron/blob/master/default_app/main.ts#L250

This is the issue causing https://github.com/electron/electron/issues/24918

**Comment by dscalzi** [comment]
`process.kill(process.pid)` kills the process, `process.exit(0)` does not. Unsure if there are any on exit listeners blocking the call to exit from completing?

**Comment by ckerr** [comment]
Possibly windows-specific? `node node_modules/electron/cli.js -v` exits for me on Linux.

Tested w/Electron 10 + Ubuntu 20.04

**Comment by dscalzi** [comment]
It does appear to be specific to windows. I had my friend test it as well.

* It works on his machine (Windows 10 1909)
* **It hangs on my machine (Windows 10 2004)**

**Comment by dscalzi** [comment]
Still an issue on the fall update (Windows 10 20H2)

**Comment by dscalzi** [comment]
Appears to be working on Windows 11, although I am on a new machine. Going to close this.
