### ISSUE TITLE
upgrade electron to 9.x but the types still old 

### ISSUE THREAD

**Issue by dtboy1995** [electron/electron#26529]
```
npm i electron@9
```

> shell.openItem -> shell.openPath

but 

![image](https://user-images.githubusercontent.com/19227547/99364587-1afdc480-28f1-11eb-8f71-c2a3f59f5fdd.png)
![image](https://user-images.githubusercontent.com/19227547/99364614-24872c80-28f1-11eb-983b-d667a3d37824.png)

**Comment by ckerr** [comment]
Looks like the issue doesn't lie in the electron release itself.

https://github.com/electron/electron/releases/download/v9.3.4/electron.d.ts is correct -- it has `openPath()` and not `openItem()`

**Comment by MarshallOfSound** [comment]
If the release is correct this will be an issue with your local development environment which is outside of the realm of things we can help with.  I'd recommend ensuring you don't have multiple copies of Electron installed in your `node_modules` folder and you definitely don't have `@types/electron` installed.
