### ISSUE TITLE
Support putting an HTML element of the BrowserWindow above BrowserView. Support changing the z-order of multiple BrowserView.

### ISSUE THREAD

**Issue by toyanghong** [electron/electron#26532]
Support putting an HTML element of the BrowserWindow above BrowserView.
Support changing the z-order of multiple BrowserView.

**Comment by MarshallOfSound** [comment]
This by nature of native views is not technically feasible, BrowserViews are in a completely separate view heirachy to the webContents in the BrowserWindow and therefore any kind of z-index applied to an element in one webContents _can not_ draw over the webContents in the other view.

**Comment by toyanghong** [comment]
If I want to use BrowserView, is there any solution? The label webview does not have this problem, but the documentation says it is not recommended. can you help me

**Comment by toyanghong** [comment]
> This by nature of native views is not technically feasible, BrowserViews are in a completely separate view heirachy to the webContents in the BrowserWindow and therefore any kind of z-index applied to an element in one webContents _can not_ draw over the webContents in the other view.

If I want to use BrowserView, is there any solution? The label webview does not have this problem, but the documentation says it is not recommended. can you help me

**Comment by MarshallOfSound** [comment]
A `webview` is implemented behind the scenes as an `iframe` (it's substantially more complicated but that's the gist).  A `BrowserView` is fundamentally backed by a different native view.  If you want to put content on top of a BrowserView from a different page, you'll have to use a second browser view

**Comment by toyanghong** [comment]
> A `webview` is implemented behind the scenes as an `iframe` (it's substantially more complicated but that's the gist). A `BrowserView` is fundamentally backed by a different native view. If you want to put content on top of a BrowserView from a different page, you'll have to use a second browser view

  mainWindow = new BrowserWindow({
    width: 1500,
    height: 780,
  });
  mainWindow.loadURL(`index.html`);

 view = new BrowserView();
  mainWindow.BrowserView(view);
  view.setBounds({x: 0, y: 180, width: 1100, height: 600});
 view.webContents.loadURL(arg);


**I made an html menu in BrowserWindow, and it was blocked by BrowserView when I clicked it.
Can you provide a simple sample code, I have been troubled by this for two days. Hope help me**

**Comment by toyanghong** [comment]
> A `webview` is implemented behind the scenes as an `iframe` (it's substantially more complicated but that's the gist). A `BrowserView` is fundamentally backed by a different native view. If you want to put content on top of a BrowserView from a different page, you'll have to use a second browser view

hi  Hope help me
