### ISSUE TITLE
Not showing map drives on Windows 10

### ISSUE THREAD

**Issue by maxigroldan** [electron/electron#26539]
Hi all.
I am running an app built with Electron (version 4.2.10) that opens a web site with chromium. Inside the web site there is a file upload dialog that it is not showing the mapped drives on Windows 10.

Is there any misconfiguration? Or an workaround?

Thanks in advance

Regards.

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
