### ISSUE TITLE
how work with pkcs11  (event select-client-certificate not fire )

### ISSUE THREAD

**Issue by abdalahshaban** [electron/electron#26541]
event select-client-certificate not fire 
os :win10

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
