### ISSUE TITLE
WebCodecs: ReferenceError: AudioDecoder is not defined

### ISSUE THREAD

**Issue by adminy** [electron/electron#26566]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v10.1.5

* **Operating System:**
  * MacOS Catalina 10.15.5 

### Expected Behavior

Audio Frame should be decoded by [WebCodecs](https://github.com/WICG/web-codecs) with --enable-blink-features=WebCodecs enabled Starting with Chrome 86.
### Actual Behavior
ReferenceError: AudioDecoder is not defined

### To Reproduce
Get the latest electron, 
Start a blank project and add 
`app.commandLine.appendSwitch('enable-blink-features', 'WebCodecs')`
then define this in your main code anywhere
`const audioDecoder = new AudioDecoder({ output: frame => {}, error: e => console.error(e) })`

### Screenshots

<img width="799" alt="Screenshot 2020-11-18 at 14 41 58" src="https://user-images.githubusercontent.com/22717869/99544534-53aea400-29ac-11eb-80c9-d8e158eb7fca.png">

### Additional Information

I have another chrome flag:
`app.commandLine.appendSwitch('autoplay-policy', 'no-user-gesture-required')`
Also this is my browser window config:
`{ width: 800, height: 600,  webPreferences: { nodeIntegration: true, allowRunningInsecureContent: true} }`

**Comment by ckerr** [comment]
Marking as confirmed that I'm seeing the same audiodecoder-not-defined after starting Electron 11 with  `--enable-blink-features=WebCodecs` to opt in to these experimental features, but I have not confirmed that the same behavior works  in Chrome

**Comment by adminy** [comment]
I downloaded latest chromium (Version 89.0.4330.0 (Developer Build) (x86_64)) out of curiosity.
<img width="1201" alt="Screenshot 2020-11-18 at 21 29 14" src="https://user-images.githubusercontent.com/22717869/99590524-58dc1500-29e5-11eb-9de9-639602d14e1e.png">
