### ISSUE TITLE
BrowserView draggable area not working in windows exclusively on BrowserViews

### ISSUE THREAD

**Issue by pejman1** [electron/electron#26562]
### Issue Details
in frameless windows 
While setting browserview style to draggable by webkit-app-region : drag. the area won't be draggable after that
and it can not move main window 
### Electron Version:
11.0.1
### Operating System:
Windows 10 (1803)
Last Known Working Electron version:
not found
### Expected Behavior
Browser view moves the main window while I set the style of the body or one of the area to
-webkit-app-region: drag;

### Actual Behavior
nothing happen in browserview after styling -webkit-app-region: drag;

I know it is mention that in 11 version it is fixed. but it still dosn't work 

### To Reproduce
https://gist.github.com/pejmanpesyan/8540aad65e7c6980c45f23e5eaafafb9

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by pejman1** [comment]
> Thanks for reporting this and helping to make Electron better!
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a followup comment.
> 
> Thanks in advance! Your help is appreciated.

https://gist.github.com/pejmanpesyan/8540aad65e7c6980c45f23e5eaafafb9

**Comment by codebytere** [comment]
@pejman1 i ran your provided repro on Windows 10 and it worked perfectly fine for me on 11.0.1. No exception was thrown on quit, either.

**Comment by pejman1** [comment]
> @pejman1 i ran your provided repro on Windows 10 and I'm not quite sure that your repro is demonstrating what you're intending - what _specific_ issue are you experiencing? `index2.html` does not exist. No exception was thrown on quit, either.

https://gist.github.com/pejmanpesyan/8540aad65e7c6980c45f23e5eaafafb9
could you please redownload the repo the index2.html is provided . close exception is gone. it might be because of an error in my windows , However, the other issues that I mentioned are still, major problems in electron, I would appreciate if you could check them, thank you .

**Comment by codebytere** [comment]
@pejman1 i've now seen the issue - i've worked out how to solve it and there will be a PR up to do so tomorrow when my workday begins.

**Comment by pejman1** [comment]
> @pejman1 i've now seen the issue - i've worked out how to solve the draggability aspect and there will be a PR up to do so tomorrow when my workday begins.

Thank you so much
