### ISSUE TITLE
Uncaught TypeError: Cannot read property 'forEach' of undefined in dispatchEvent on render process crash

### ISSUE THREAD

**Issue by andersk** [electron/electron#26561]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.0.0
* **Operating System:**
  * NixOS 21.03 x86_64
* **Last Known Working Electron version:**
  * 9.0.5?

### Expected Behavior

A `<webview>` render process crash is handled gracefully.

### Actual Behavior

When a `<webview>` render process crashes, this `TypeError` shows up in the developer console:

```
Uncaught TypeError: Cannot read property 'forEach' of undefined
    at dispatchEvent (electron/js2c/renderer_init.js:119)
    at electron/js2c/renderer_init.js:119
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:103)
    at EventEmitter.emit (events.js:315)
    at Object.onMessage (electron/js2c/renderer_init.js:91)
```

### To Reproduce

Minimal example at andersk/electron-quick-start@41af45c0237680ca9c88bc202fb20eaa964d6f1d:

```sh
$ git clone https://github.com/andersk/electron-quick-start.git -b webview-crash
$ npm install
$ npm start
```

Then observe the error in View → Toggle Developer Tools.

### Additional Information

The `forEach` in question is this one:

https://github.com/electron/electron/blob/387a15f5829f623c9366d0a4625cc33f5a4758d4/lib/renderer/web-view/guest-view-internal.ts#L55-L57

I think the problem is that the `render-process-gone` event was added in v10.0.0 (#23560) and backported to v9.1.0 and v8.4.0, but it was not added to [`WEB_VIEW_EVENTS`](https://github.com/electron/electron/blob/387a15f5829f623c9366d0a4625cc33f5a4758d4/lib/renderer/web-view/guest-view-internal.ts#L7-L41) until #25697, which is not in any release and has not been backported.

**Comment by ckerr** [comment]
fiddle-friendly gist of @andersk's testcase repro: https://gist.github.com/ckerr/d81823f630b603d2e7b7aa40adc3fb36

**Comment by ckerr** [comment]
@miniak's fixes have been merged into the [8..11]-x-y branches, and was already in master, so I think this issue is done?

Closing as fixed.
