### ISSUE TITLE
app throws exception on quit() function in electron version 11

### ISSUE THREAD

**Issue by pejman1** [electron/electron#26567]
* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
electron in version 11. frameless window after closing all windows and quit app with this event
app.on("window-all-closed", () => {
  app.exit(0); // or app.quit()
});
electron throws an exception : object has been destroyed   

* **Electron Version:**
  * 11.0.1
* **Operating System:**
  *  Windows 10 (1803)
* **Last Known Working Electron version:**
  * 10.1.5 and all 10,9,8 versions

### Expected Behavior
quit app without throwing any error

### Actual Behavior
in version 11 app crashes

### Screenshots
![Screen Shot 2020-11-18 at 15 48 40 PM](https://user-images.githubusercontent.com/11601344/99554736-c92e6a80-29d4-11eb-82da-3b6ab45ee4f8.png)

### To Reproduce
https://gist.github.com/pejmanpesyan/8540aad65e7c6980c45f23e5eaafafb9

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by pejman1** [comment]
> Thanks for reporting this and helping to make Electron better!
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a followup comment.
> 
> Thanks in advance! Your help is appreciated.
I'have checked it in fiddle 
I found the reason. if I remove the app.quit() method in    "window-all-closed" event the app doesn't throw exception . this problem was not in the order version of electron 10,9,.. but in version 11 it has

**Comment by ckerr** [comment]
Hey @pejman1, thanks for the update!

Since you have a test case there in Fiddle, could you publish it as a gist and link to the gist here so that it's easier for team members to reproduce the issue?

**Comment by pejman1** [comment]
> Hey @pejman1, thanks for the update!
> 
> Since you have a test case there in Fiddle, could you publish it as a gist and link to the gist here so that it's easier for team members to reproduce the issue?

https://gist.github.com/pejmanpesyan/8540aad65e7c6980c45f23e5eaafafb9

**Comment by ckerr** [comment]
Hi, thanks for the gist on top of the original update!

Unfortunately I need to ask again for more information -- I've tested this with Electron 11.0.1 on both Windows 10 and Ubuntu 20.04 -- I start up the application and just click the close button -- and I'm not seeing the exception; it just exits cleanly. Are there other steps that I need to follow to reproduce this issue?

**Comment by pejman1** [comment]
> Hi, thanks for the gist on top of the original update!
> 
> Unfortunately I need to ask again for more information. I've tested this with Electron 11.0.1 on both Windows 10 and Ubuntu 20.04: I start up the application and just click the close button. This doesn't result in an exception; it just exits cleanly. Are there other steps that I need to follow to reproduce this issue?

Hi and thank you for checking. You are right. I don't know why but the exception has gone . maybe it was because of a bug in windows and after windows update this issue is solved .
However the other bugs are still major problems in electron

**Comment by XRenSiu** [comment]
I have the same issue.
electron 11.0.3
Reproduce:
https://gist.github.com/XRenSiu/5067f741488ce45063b9c06fbf458f48

**Comment by pejman1** [comment]
> I have the same issue.
> electron 11.0.3
> Reproduce:
> https://gist.github.com/XRenSiu/5067f741488ce45063b9c06fbf458f48

and even in version 11.0.4 . app.quite with browserview throws an exception

**Comment by kalachevmax** [comment]
This problem also relevant for Mac OS 10.14.6

**Comment by kalachevmax** [comment]
if you call the app.exit() in the "will-quit" event handler, then this message will be appeared.

**Comment by kalachevmax** [comment]
@ckerr Hi! Please clarify, do you plan to fix this issue? We use BrowserWindow with many BrowserView's and we have problems with it. Maybe there is some workaround?

**Comment by XRenSiu** [comment]
> @ckerr Hi! Please clarify, do you have plans to fix this issue? We use BrowserWindow with many BrowserView's and we have problems with it. Maybe there is some workaround?

Just workaround:
You can manually clear `objects-registry` for BrowserView.
```
webContents.emit('render-view-deleted', {}, webContents.getProcessId())

webContents.listeners('render-view-deleted').forEach(l =>
     webContents.off('render-view-deleted', l)
  )
```

**Comment by nornagon** [comment]
I'm able to repro with https://gist.github.com/XRenSiu/5067f741488ce45063b9c06fbf458f48, here's the exception:

```
TypeError: Object has been destroyed
    at getOwnerKey (electron/js2c/browser_init.js:209:191)
    at ObjectsRegistry.clear (electron/js2c/browser_init.js:209:735)
    at Object.listener (electron/js2c/browser_init.js:209:1285)
    at Object.emit (events.js:315:20)
```

It looks like the WebContents is getting destroyed before the ObjectsRegistry has a chance to clean it up.

**Comment by MehediH** [comment]
@nornagon Thank you for the PR! Is there any temporary workaround for the time being?
