### ISSUE TITLE
Microsoft Office Sharepoint Files getting locked even after Closing from Electron browser but works fine with Chrome/Firefox Browser

### ISSUE THREAD

**Issue by SharikSaigal87** [electron/electron#26579]
### Preflight Checklist

* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v11.0.1
* **Operating System:**
  * Windows (Pro 10 - 1809) & Linux (Ubuntu 20.04)
* **Last Known Working Electron version:**
  *  Never worked in lower versions

### Expected Behavior

Close of Microsoft Office Files launched from Electron or Electron based browser should be detected immediately by Microsoft Office , we should  be able to work on Microsoft Office Files and do operations like delete/upload after Closing from Electron or Electron based browsers similar to how we are able to work with Microsoft office cloud files opened and closed using Chrome or Firefox Browser
### Actual Behavior
Microsoft Office Sharepoint Files getting locked and complaining that it is still open even after Closing from Electron or Electron based browsers for about 15 minutes .

### To Reproduce

**Operation using Electron Browser or electron based browser like Min, Wexond  etc**

1. Copy the link of sharepoint file and Launch  the file file eg: a word document Microsoft Office shared copied link using Electron or Electron Based Browser (eg:**electron.exe "<shared_web_url_of_word_file>"** or  **mainWindow.loadURL("shared_web_url_of_word_file"))**
2. Close the Launched file window using same Electron or Electron Based Browser
3. Go to Microsoft Office SharePoint  and try to delete the file
4. Have observed that the Microsoft Office Files  are getting locked after Closing from Electron browser  for about 15 minute and it says that the file is still opened ,even though it is closed as seen in below screenshot

Have observed app.quit() is being called on electron close window but still it is considered open  from Microsoft Office for around 15 minutes but it considers it closed immediately  when closed using Chrome/Firefox Browsers

**Operation using Chrome/Firefox Browsers**

1. Copy the link of sharepoint file and Launch  the  cloud file eg: a word document Microsoft Office copied link using Chrome or Firefox Browser
2. Close the Launched file tab or window using Chrome/Firefox Browser
3. Go to Microsoft Office SharePoint and try to delete the file
4. Observed that we are able to delete the file without any warning

As I understand Electron is based on Chromium and cloud files launched using Electron should behave same as Chrome and not get Locked .
Can you please fix the issue or help with a workaround so that files are forcefully or immediately  detected closed when electron browser window is closed for office launched files?
This is blocking us from doing any new operation on file like upload ,delete 

### Screenshots

- **Copying the link of file from Sharepoint**  

![image](https://user-images.githubusercontent.com/43027475/99574325-4077f480-29fd-11eb-93de-fa622f893306.png)

- **Now we launch the link using electron and close the electron launcher** 
![image](https://user-images.githubusercontent.com/43027475/99577480-6b644780-2a01-11eb-9a67-e0de900e9af0.png)

- **After trying to delete the file from Sharepoint we see below error**

![image](https://user-images.githubusercontent.com/43027475/99572424-a8790b80-29fa-11eb-9d03-b08141685c19.png)

**Comment by MarshallOfSound** [comment]
This sounds like an issue in Sharepoint.  Given we can't debug Sharepoint to determine what the issue is there's nothing we can do here.  If you can provide a _minimal_ code repro of what sharepoint is expecting to work then we might be able to look into it, but currently "sharepoint doesn't work" is not a thing we can help you with
