### ISSUE TITLE
Release notes contain an actual input widget

### ISSUE THREAD

**Issue by andersk** [electron/electron#26583]
The [11.0.0 release notes](https://www.electronjs.org/releases/stable#11.0.0) and the [10.1.6 release notes](https://www.electronjs.org/releases/stable?version=10#10.1.6) include this actual `<input file="type">` widget instead of the code for `<input file="type">`:

![screenshot](https://user-images.githubusercontent.com/26471/99601785-f834e400-29b4-11eb-8f25-c6966802b99e.png)

Introduced by #26217 and #26555.

**Comment by ckerr** [comment]
I've fixed the notes for 11.0.0 and 10.1.6 at https://github.com/electron/electron/releases -- I think the electronjs.org pages will take a little longer depending on how long it takes to sync up with GitHub.

Also, I'll take a TODO item to sanitize inputs when generating release notes... I'll admit, I didn't write the script with Little Bobby Tables in mind. :1st_place_medal:

**Comment by ckerr** [comment]
https://github.com/electron/clerk/pull/51
