### ISSUE TITLE
electron app crash and leaves many dead processes

### ISSUE THREAD

**Issue by maple-leaf** [electron/electron#26589]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
![image](https://user-images.githubusercontent.com/3980995/99625680-b61aa980-2a6b-11eb-95c0-9cb8ecb6647e.png)

All dead processes in read box is caused by a unepxected crash. And all other processes below are created after I restart the app.
All dead processes' command is empty.

* **Electron Version:** 
  * Electron/9.3.1
* **Operating System:** 
  * Windows 10(1903)
* **Last Known Working Electron version:** 
  * n/a

### Expected Behavior

All processes should be exited after crash.

### Actual Behavior

many dead processes remain.
### To Reproduce

unkonwn

**Comment by nornagon** [comment]
Unfortunately without any steps to reproduce this issue we can't debug further. Please provide a small example that reproduces the issue you're seeing, preferable using [Electron Fiddle](https://github.com/electron/fiddle).

Thanks!

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
