### ISSUE TITLE
Draggable region in BrowserWindow causes BrowserView to become draggable

### ISSUE THREAD

**Issue by quanglam2807** [electron/electron#26588]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 10.1.6
  * 
* **Operating System:** macOS Big Sur 11.0.1
  * 
* **Last Known Working Electron version:** 10.1.5
  * 

### Expected Behavior

`BrowserView` is not draggable.

### Actual Behavior

`BrowserView` is draggable. 

### To Reproduce

From my test, if I creates a draggable region on the left side of `BrowserWindow` (let's say with width 100px), and then add a `BrowserView` to the right side of the window, the 100px part on the right side of BrowserWindow/BrowserView will become draggable. 

You can reproduce the bugs using the following code (modified from `electron-quick-start`).
[electron-1015.zip](https://github.com/electron/electron/files/5564422/electron-1015.zip) (electron@10.1.5)
[electron-1016.zip](https://github.com/electron/electron/files/5564423/electron-1016.zip) (electron@10.1.6)

The files have identical code, except for the Electron version. It works properly in v10.1.5 but doesn't in v10.1.6

### Additional Information

Potentially related to https://github.com/electron/electron/pull/26145

**Comment by ckerr** [comment]
Gist link of @quanglam2807's testcase: https://gist.github.com/ckerr/9261213d7edaadc590f8400c79ab9118

**Comment by ckerr** [comment]
I'm not able to reproduce this bug on Ubuntu 20.04, which would be consistent with the suggestion that #26145 may be involved -- that commit does have some platform-specific changes

**Comment by MonkingStand** [comment]
check that whether bind click on window, like the following sample
```javascript
window.addEventListener('click', evt => {
    const $target = evt.target;
    console.info('do somethings here');
});
```
i've solved this issue by modifying the code like the following
```javascript
window.addEventListener('click', evt => {
    const $target = evt.target;
    console.info('do somethings here');
});
```
