### ISSUE TITLE
Segmentation fault when webContents.fromId() for non existing id

### ISSUE THREAD

**Issue by larssvensby** [electron/electron#26599]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
webContents.fromId() for non existing id (e.g. removed webview) causes segmentation fault in Electron 11.
In Electron 9 & 10 null was returned.
Same problem on Windows and macOS Catalina 

* **Electron Version:**
  * 11.0.1
* **Operating System:**
  * macOS 11.0.1
* **Last Known Working Electron version:**
  * 10.1.6

### Expected Behavior

webContents.fromId() returns null for non existing id

### Actual Behavior

Segmentation fault

### To Reproduce
https://gist.github.com/larssvensby/071353ec109c4975fd28b5a4b1dc7ad5

**Comment by ckerr** [comment]
Reproduced testing w/ https://gist.github.com/larssvensby/071353ec109c4975fd28b5a4b1dc7ad5 using Electron 11 on Ubuntu 20.04.

trace:

```
Received signal 11 SEGV_MAPERR 000000000010
#0 0x562a068904e9 base::debug::CollectStackTrace()
#1 0x562a067de443 base::debug::StackTrace::StackTrace()
#2 0x562a0689003b base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7f0ea2f833c0 (/lib/x86_64-linux-gnu/libpthread-2.31.so+0x153bf)
#4 0x562a08457144 gin::WrappableBase::GetWrapperImpl()
#5 0x562a02d74f82 gin_helper::Invoker<>::DispatchToCallback<>()
#6 0x562a02d74ec8 gin_helper::Dispatcher<>::DispatchToCallback()
#7 0x562a040a7be7 v8::internal::FunctionCallbackArguments::Call()
#8 0x562a040a6435 v8::internal::(anonymous namespace)::HandleApiCallHelper<>()
#9 0x562a040a465a v8::internal::Builtin_Impl_HandleApiCall()
#10 0x562a040a413a v8::internal::Builtin_HandleApiCall()
#11 0x562a051c20bf Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
  r8: 00000000000003e7  r9: 0000000000000001 r10: 00000931080423b1 r11: 0000000000000002
 r12: 00007fff7671fff0 r13: 0000093100000000 r14: 0000093100000000 r15: 00007fff7671ffe8
  di: 0000000000000000  si: 0000093100000000  bp: 00007fff7671ff90  bx: 00007fff76720010
  dx: 0000562a0b5ccee8  ax: 0000000000000000  cx: 0000000000000000  sp: 00007fff7671ff30
  ip: 0000562a08457144 efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000010
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```
