### ISSUE TITLE
MAS build crashes after code sign, Helper sandbox issue

### ISSUE THREAD

**Issue by Ralph-Juke** [electron/electron#26602]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
v11.0,1
* **Operating System:**
  * macOS 11.0.1
* **Last Known Working Electron version:**

### Expected Behavior
After code signing the app launches and works

### Actual Behavior
After code signing the app takes longer to load, shows a blank window and crashes

### Additional Information

- Using Electron Forge to build the app
- Add ElectronTeamID manually after build in info.plist
- Codesign manually

Entitlement files:
parent.plist
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.app-sandbox</key>
	<true/>
	<key>com.apple.security.application-groups</key>
	<array>
		<string>WBT68YKARR.nl.juke.music</string>
	</array>
	<key>com.apple.security.files.user-selected.read-only</key>
	<true/>
	<key>com.apple.security.files.user-selected.read-write</key>
	<true/>
</dict>
</plist>`

child.plist
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.security.app-sandbox</key>
	<true/>
	<key>com.apple.security.inherit</key>
	<true/>
</dict>
</plist>`

Codesigning part:
- first fix the opening of the app for changing the info.plist with the ElectronTeamID
- Define some variables
- make sure all plist files are XML
- code signing
- build pkg and sign

`xattr -cr out/JUKE-darwin-x64/JUKE.app                                  
APP="JUKE"
APP_PATH="out/JUKE-darwin-x64/JUKE.app"
RESULT_PATH="$APP.pkg"
APP_KEY="EDC60C1F20C18B7016355E2CAA4489A1D2927E66"
INSTALLER_KEY="91176729F8A146B3244E976A4E3A2894E875C7CC"
CHILD_PLIST="src/child.plist"
PARENT_PLIST="src/parent.plist"
FRAMEWORKS_PATH="$APP_PATH/Contents/Frameworks"

plutil -convert xml1 "src/child.plist"
plutil -convert xml1 "src/parent.plist"
plutil -convert xml1 "src/loginhelper.plist"
plutil -convert xml1 "$FRAMEWORKS_PATH/$APP Helper (GPU).app/Contents/Info.plist"
plutil -convert xml1 "$FRAMEWORKS_PATH/$APP Helper (Plugin).app/Contents/Info.plist"
plutil -convert xml1 "$FRAMEWORKS_PATH/$APP Helper (Renderer).app/Contents/Info.plist"
plutil -convert xml1 "$FRAMEWORKS_PATH/$APP Helper.app/Contents/Info.plist"
plutil -convert xml1 "$FRAMEWORKS_PATH/Mantle.framework/Versions/A/Resources/Info.plist"
plutil -convert xml1 "$FRAMEWORKS_PATH/Squirrel.framework/Versions/A/Resources/Info.plist"
plutil -convert xml1 "$FRAMEWORKS_PATH/ReactiveObjC.framework/Versions/A/Resources/Info.plist"
plutil -convert xml1 "$APP_PATH/Contents/Info.plist"

codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Electron Framework"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Libraries/libffmpeg.dylib"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Libraries/libEGL.dylib"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Libraries/libswiftshader_libEGL.dylib"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Libraries/libswiftshader_libGLESv2.dylib"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/A/Libraries/libvk_swiftshader.dylib"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework/Versions/Current/Helpers/chrome_crashpad_handler"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Electron Framework.framework"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/ReactiveObjC.framework"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Squirrel.framework/Versions/A/Resources/ShipIt"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Squirrel.framework"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/Mantle.framework"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (GPU).app/Contents/MacOS/$APP Helper (GPU)"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (GPU).app/"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (Plugin).app/Contents/MacOS/$APP Helper (Plugin)"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (Plugin).app/"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (Renderer).app/Contents/MacOS/$APP Helper (Renderer)"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper (Renderer).app/"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper.app/Contents/MacOS/$APP Helper"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$FRAMEWORKS_PATH/$APP Helper.app/"
codesign -s "$APP_KEY" -f --entitlements "$CHILD_PLIST" "$APP_PATH/Contents/MacOS/$APP"
codesign -s "$APP_KEY" -f --entitlements "$PARENT_PLIST" "$APP_PATH"

productbuild --component "$APP_PATH" /Applications --sign "$INSTALLER_KEY" "$RESULT_PATH"`

After laughing the app I get the following errors:
`error	15:49:23.254580+0100	kernel	Sandbox: JUKE(18767) deny(1) file-read-data /private/etc
error	15:49:24.014146+0100	kernel	Sandbox: JUKE Helper (GPU(18769) deny(1) file-write-create /private/var/folders/z9/3ymf4gj53l7b36wgg328lhjc0000gp/C/nl.juke.music.helper/nl.juke.music.helper
fault	15:49:24.014245+0100	JUKE Helper (GPU)	Failed to get cache main folder: mkdir failed to create cache path (errno = 1)
fault	15:49:24.030865+0100	JUKE Helper (GPU)	Failed to get cache main folder: mkdir failed to create cache path (errno = 1)
error	15:49:24.665096+0100	kernel	Sandbox: JUKE Helper (GPU(18769) deny(1) forbidden-sandbox-reinit
error	15:49:25.375003+0100	kernel	Sandbox: JUKE Helper (GPU(18771) deny(1) file-write-create /private/var/folders/z9/3ymf4gj53l7b36wgg328lhjc0000gp/C/nl.juke.music.helper/nl.juke.music.helper
fault	15:49:25.375155+0100	JUKE Helper (GPU)	Failed to get cache main folder: mkdir failed to create cache path (errno = 1)
fault	15:49:25.391443+0100	JUKE Helper (GPU)	Failed to get cache main folder: mkdir failed to create cache path (errno = 1)
error	15:49:25.623979+0100	kernel	Sandbox: JUKE Helper(18772) deny(1) forbidden-sandbox-reinit
error	15:49:26.101331+0100	kernel	Sandbox: JUKE Helper (GPU(18771) deny(1) forbidden-sandbox-reinit
error	15:49:26.700056+0100	kernel	Sandbox: JUKE Helper (GPU(18775) deny(1) file-write-create /private/var/folders/z9/3ymf4gj53l7b36wgg328lhjc0000gp/C/nl.juke.music.helper/nl.juke.music.helper
fault	15:49:26.700161+0100	JUKE Helper (GPU)	Failed to get cache main folder: mkdir failed to create cache path (errno = 1)
fault	15:49:26.716732+0100	JUKE Helper (GPU)	Failed to get cache main folder: mkdir failed to create cache path (errno = 1)
error	15:49:27.321558+0100	kernel	Sandbox: JUKE Helper (GPU(18775) deny(1) forbidden-sandbox-reinit
error	15:49:27.914915+0100	kernel	Sandbox: JUKE Helper (GPU(18777) deny(1) file-write-create /private/var/folders/z9/3ymf4gj53l7b36wgg328lhjc0000gp/C/nl.juke.music.helper/nl.juke.music.helper
fault	15:49:27.914998+0100	JUKE Helper (GPU)	Failed to get cache main folder: mkdir failed to create cache path (errno = 1)
fault	15:49:27.936590+0100	JUKE Helper (GPU)	Failed to get cache main folder: mkdir failed to create cache path (errno = 1)
error	15:49:28.487929+0100	kernel	Sandbox: JUKE Helper (GPU(18777) deny(1) forbidden-sandbox-reinit
error	15:49:29.202410+0100	kernel	Sandbox: JUKE Helper (GPU(18779) deny(1) file-write-create /private/var/folders/z9/3ymf4gj53l7b36wgg328lhjc0000gp/C/nl.juke.music.helper/nl.juke.music.helper
fault	15:49:29.202590+0100	JUKE Helper (GPU)	Failed to get cache main folder: mkdir failed to create cache path (errno = 1)
fault	15:49:29.218456+0100	JUKE Helper (GPU)	Failed to get cache main folder: mkdir failed to create cache path (errno = 1)
error	15:49:29.865778+0100	kernel	Sandbox: JUKE Helper (GPU(18779) deny(1) forbidden-sandbox-reinit
error	15:49:30.649517+0100	kernel	Sandbox: JUKE Helper (GPU(18783) deny(1) file-write-create /private/var/folders/z9/3ymf4gj53l7b36wgg328lhjc0000gp/C/nl.juke.music.helper/nl.juke.music.helper
fault	15:49:30.649635+0100	JUKE Helper (GPU)	Failed to get cache main folder: mkdir failed to create cache path (errno = 1)
fault	15:49:30.664357+0100	JUKE Helper (GPU)	Failed to get cache main folder: mkdir failed to create cache path (errno = 1)
error	15:49:31.163647+0100	kernel	Sandbox: JUKE Helper (GPU(18783) deny(1) forbidden-sandbox-reinit
error	15:49:31.609252+0100	kernel	Sandbox: JUKE Helper (GPU(18785) deny(1) file-write-create /private/var/folders/z9/3ymf4gj53l7b36wgg328lhjc0000gp/C/nl.juke.music.helper/nl.juke.music.helper
fault	15:49:31.609396+0100	JUKE Helper (GPU)	Failed to get cache main folder: mkdir failed to create cache path (errno = 1)
fault	15:49:31.632592+0100	JUKE Helper (GPU)	Failed to get cache main folder: mkdir failed to create cache path (errno = 1)
error	15:49:31.803891+0100	imklaunchagent	IMKLaunchAgent -requestIMKXPCEndpointInvalid: received notification Request for Endpoint Invalid (from pid_t: 18767) for bundleID: <private>
error	15:49:31.807082+0100	imklaunchagent	IMKLaunchAgent -requestIMKXPCEndpointInvalid: received notification Request for Endpoint Invalid (from pid_t: 18767) for bundleID: <private>
error	15:49:a1825242+0100	kernel	Sandbox: JUKE Helper(18786) deny(1) forbidden-sandbox-reinit
error	15:49:32.435798+0100	kernel	Sandbox: JUKE Helper (GPU(18785) deny(1) forbidden-sandbox-reinit
error	15:49:32.552663+0100	kernel	Sandbox: JUKE Helper(18789) deny(1) forbidden-sandbox-reinit`

From what I read here is that the Helper apps do not get correctly sandboxed and try to create files (presumably for caching), fail and the try to reinitialise the sandbox and fail again.

**Comment by MarshallOfSound** [comment]
Please use `electron-osx-sign` to codesign your applications, it is _known_ to work in particular with sandboxed applications.  We can't help out with every custom codesigning configuration
