### ISSUE TITLE
Heavy CPU usage with tray.setImage

### ISSUE THREAD

**Issue by johannesjo** [electron/electron#26603]
### Issue Details

* **Electron Version:**
  * 10.1.5
* **Operating System:**
  *  several different Linux OS

Several of my users seem to experience heavy CPU usage with the tray icon:
https://github.com/johannesjo/super-productivity/issues/675

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by johannesjo** [comment]
Would checking out the repository provided above work as well?

**Comment by johannesjo** [comment]
Might also be an issue of the appindicator extension:
https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-appindicator/+bug/1849142
ubuntu/gnome-shell-extension-appindicator#236

**Comment by johannesjo** [comment]
bump

**Comment by zcbenz** [comment]
Checking out the pasted repo would require us to debug into the repo's code, which our team does not have time to do. If you could reproduce the problem with some simple code like below it would be much more practical for us to look into it, otherwise we have to close this issue as most of other Electron apps do not have this issue.

```js
const {app, Tray} = require('electron')
let tray
app.once('ready', () => {
  tray = new Tray('/path/to-icon')
})
```

**Comment by johannesjo** [comment]
This should reproduce the issue.

```
const {app, Tray} = require('electron')
let tray

app.once('ready', () => {
  tray = new Tray('/path/to-icon')

 setInterval(()=>{
        tr.setImage('path/to-icon);
 }, 500);
})
```
