### ISSUE TITLE
Frameless browserview gets bigger size while it sets app to maximize

### ISSUE THREAD

**Issue by pejman1** [electron/electron#26614]
### Issue Details
Frameless window in windows =>  browser view with setAutoResize true , if you set the mainwindow or browser view to mazimize state. the browser view gets bigger size of the fullscreen res. and part of it's window will be cropped 

* **Electron Version:**
 * 11.0.1
* **Operating System:**
  * Windows 10 (1803) 

### Expected Behavior

the browser view in maximize state should be the same size as mainwindow 

### Actual Behavior

in maximize state it does not set its size correctly 

### Screenshots

![Screen Shot 2020-11-03 at 00 22 12 AM](https://user-images.githubusercontent.com/11601344/97919275-c55fde80-1d6c-11eb-81b1-f387827432c6.png)
main window in maximize state 

![Screen Shot 2020-11-03 at 00 22 08 AM](https://user-images.githubusercontent.com/11601344/97919501-225b9480-1d6d-11eb-81e2-3902e413355b.png)
browser view which is attached to main windows after setting in maximize state gets wrong size
### Sample project 
https://gist.github.com/pejmanpesyan/8540aad65e7c6980c45f23e5eaafafb9

**Comment by pejman1** [comment]
Do you have any intention to fix this issue?

**Comment by pejman1** [comment]
The issue still has not been solved in new versions. 
11.1.2

**Comment by ItsRealmy** [comment]
I'm having the same problem, I just did this for now:
`window.on("maximize", function () {
    view.setBounds({ x: 0, y: 0, width: window.getSize()[0] - 17, height: window.getSize()[1] - 17 });
})`

**Comment by pejman1** [comment]
the issue has not fixed yet even in the latest version 13.1.4

**Comment by weifeiyue** [comment]
@nornagon how about this bug?

**Comment by pejman1** [comment]
this issue has not been resolve yet even in version 14.0.0

@ckerr PRO
Charles Kerr

@codebytere

**Comment by codebytere** [comment]
@pejman1 this repository has over a thousand issues and a small maintainer team working as hard as it can. Please be patient.
