### ISSUE TITLE
NativeImage couldn't load CMYK format image.

### ISSUE THREAD

**Issue by tsminh** [electron/electron#26613]
---
name: NativeImage couldn't load CMYK format image.
about: NativeImage createFromPath and createFromDataURL for cmyk images.

---

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.2.0
* **Operating System:**
  * macOS 10.15.7
* **Last Known Working Electron version:**
  * no

### Expected Behavior
- CMYK images should be load, img.isEmpty() should be false. the CMYK could be converted into RGB as well (optional).

### Actual Behavior
- CYMK images couldn't be loaded. img.isEmpty() returns true

### To Reproduce

Create an CMYK image from Photoshop or GIMP. then save as jpg.

```
const image = nativeImage.createFromPath(...)

console.log(image.isEmpty())
```

I also convert the image into base64, but it still didn't work.

```
const image = nativeImage.createFromDataURL(...)

console.log(image.isEmpty())
```

### Additional Information

* Here is the sample CMYK image file: https://drive.google.com/file/d/18GeDHOectys8RnZo3Q_vJb5LLRZ5Y-dJ/view?usp=sharing

**Comment by ckerr** [comment]
Thanks for reaching out!

Please provide the information that was requested by the [issue template](https://github.com/electron/electron/tree/master/.github/ISSUE_TEMPLATE) that was presented when you first filled out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information.

Thanks for understanding and meeting us half way :grinning:

**Comment by tsminh** [comment]
> Thanks for reaching out!
> 
> Please provide the information that was requested by the [issue template](https://github.com/electron/electron/tree/master/.github/ISSUE_TEMPLATE) that was presented when you first filled out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information.
> 
> Thanks for understanding and meeting us half way 😀

Hi thanks for information, i updated the ticket.

**Comment by ckerr** [comment]
Hi again @tsminh, that cmyk file that you linked to is not accessible. Also, the version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If you're still seeing this problem in Electron 9 or higher, would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests. In this case, for example, anyone on the team wanting to triage this ticket wouldn't have to ask for access to your CMYK file or install a CMYK plugin on Gimp, and also wouldn't have to write any scaffolding around the code snippet.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a folloup comment.

Thanks in advance! Your help is appreciated.

**Comment by tsminh** [comment]
Hello ckerr again, thank you for instruction. I update the electron to version 11. and the issue is still there.

Here is the repo to reproduce the issue: https://github.com/tsminh/electron_cmyk_rgb_image


Expected the two console.log should be true.
But result:

```
true
false
```

**Comment by tkleinke** [comment]
I'm experiencing the same issue with Electron 9.3.5 and createFromBuffer. Happens e.g. with this CMYK example image from Wikipedia: https://en.wikipedia.org/wiki/File:Channel_digital_image_CMYK_color.jpg

**Comment by popod** [comment]
@ckerr This issus is still present in electron 19 !

This will be nice if this bug could be fixed :)

The image provided by @tkleinke could be used to reproduce the bug : 
https://en.wikipedia.org/wiki/File:Channel_digital_image_CMYK_color.jpg

Thank you

**Comment by popod** [comment]
This is still an issue.. Will it not be resolved ? Thank you
