### ISSUE TITLE
Methods on remote.screen are not defined

### ISSUE THREAD

**Issue by andersk** [electron/electron#26610]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.0.2
* **Operating System:**
  * NixOS 21.03 x86_64
* **Last Known Working Electron version:**
  * 10.1.6

### Expected Behavior
`remote.screen.getPrimaryDisplay()` works.

### Actual Behavior
`Uncaught TypeError: remote.screen.getPrimaryDisplay is not a function`

### To Reproduce
Electron Fiddle: https://gist.github.com/andersk/6158c0016c56e52c58cec4aa4cd8317e

### Additional Information
This broke between 11.0.0-nightly.20200724 and 11.0.0-nightly.20200729, probably in #24677. Cc @nornagon.

See also electron-userland/spectron#771, webtorrent/webtorrent-desktop#1896.

**Comment by Augus** [comment]
Both macOS11 and Windows 10 will have this problem.

**Comment by ckerr** [comment]
Also confirmed on Linux as having broken between v10.1.6 and v11.0.2.

This is an Electron regression and should get fixed, but just a heads-up that [remote is deprecated](https://github.com/electron/electron/issues/21408) and in the long term you'll want to migrate away from this API.
