### ISSUE TITLE
Support alpha values in systemPreferences.getColor()

### ISSUE THREAD

**Issue by jcarpenter** [electron/electron#26628]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.2.5
* **Operating System:**
  * macOS 10.15.4

### Expected Behavior
On macOS, [systemPreferences.getColor(color)](https://www.electronjs.org/docs/api/system-preferences#systempreferencesgetcolorcolor-windows-macos) should return 8-digit RGBA values. As-is, they return as 6-digit RGB. 

Many of the macOS [Dynamic System Colors](https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/color/#dynamic-system-colors) use alphas. Labels, for example, are always black or white and vary only by alpha. 

For comparison's sake, I wrote a bit of Swift code to query the actual label values. As follows (for light mode, w/o high contrast enabled, and converted here to css values):

```css
labelColor: rgba(0, 0, 0, 0.847);
secondaryLabelColor: rgba(0, 0, 0, 0.498);
tertiaryLabelColor: rgba(0, 0, 0, 0.247);
quaternaryLabelColor: rgba(0, 0, 0, 0.098);
```

Without alphas, the returned values from these APIs aren't useful, unfortunately.

**Comment by jcarpenter** [comment]
My swift gist for getting system colors, in case it's useful: https://gist.github.com/jcarpenter/5f9dab8736155849bcb0703fd7cb478f

And an example of the System and Dynamic System colors (dark mode, w/o high contrast or reduce transparency, macOS 10.15.4): 

```
/* -------------- System Colors -------------- */

systemBlue: 10, 132, 255, 1.0
systemBrown: 172, 142, 104, 1.0
systemGray: 152, 152, 157, 1.0
systemGreen: 50, 215, 75, 1.0
systemIndigo: 94, 92, 230, 1.0
systemOrange: 255, 159, 10, 1.0
systemPink: 255, 55, 95, 1.0
systemPurple: 191, 90, 242, 1.0
systemRed: 255, 69, 58, 1.0
systemTeal: 100, 210, 255, 1.0
systemYellow: 255, 214, 10, 1.0

/* -------------- Dynamic System Colors -------------- */


/* Labels */

labelColor: 255, 255, 255, 0.847
secondaryLabelColor: 255, 255, 255, 0.549
tertiaryLabelColor: 255, 255, 255, 0.247
quaternaryLabelColor: 255, 255, 255, 0.098

/* Text */

textColor: 255, 255, 255, 1.0
placeholderTextColor: 255, 255, 255, 0.247
selectedTextColor: 255, 255, 255, 1.0
textBackgroundColor: 30, 30, 30, 1.0
selectedTextBackgroundColor: 63, 99, 139, 1.0
keyboardFocusIndicatorColor: 26, 169, 255, 0.298
unemphasizedSelectedTextColor: 255, 255, 255, 1.0
unemphasizedSelectedTextBackgroundColor: 70, 70, 70, 1.0

/* Content */

linkColor: 65, 156, 255, 1.0
separatorColor: 255, 255, 255, 0.098
selectedContentBackgroundColor: 0, 88, 208, 1.0
unemphasizedSelectedContentBackgroundColor: 70, 70, 70, 1.0

/* Menus */

selectedMenuItemTextColor: 255, 255, 255, 1.0

/* Tables */

gridColor: 255, 255, 255, 0.098
headerTextColor: 255, 255, 255, 1.0

/* Controls */

controlAccentColor: 0, 122, 255, 1.0
controlColor: 255, 255, 255, 0.247
controlBackgroundColor: 30, 30, 30, 1.0
controlTextColor: 255, 255, 255, 0.847
disabledControlTextColor: 255, 255, 255, 0.247
selectedControlColor: 63, 99, 139, 1.0
selectedControlTextColor: 255, 255, 255, 0.847
alternateSelectedControlTextColor: 255, 255, 255, 1.0

/* Windows */

windowBackgroundColor: 50, 50, 50, 1.0
windowFrameTextColor: 255, 255, 255, 0.847

/* Highlights & Shadows */

findHighlightColor: 255, 255, 0, 1.0
highlightColor: 180, 180, 180, 1.0
shadowColor: 0, 0, 0, 1.0
```

**Comment by ckerr** [comment]
Yep, looks like Electron has returned `#RRGGBB` for that ever since the feature [was first introduced](https://github.com/electron/electron/pull/16248/files#diff-3c215b0423b78100db1335a4fc3ecb3fa9a2640743ba66bd7d9a6b363febcf32R116). Chromium has supported `#RRGGBBAA` since [Chrome 62](https://caniuse.com/css-rrggbbaa) and IMO we could support them here.

This is arguably a bugfix for the label use case that Josh cites; but since adding alpha could possibly change colors in shipping apps in ways their developers didn't expect, IMO this is a breaking change. So to play it safer I've added `semver/major` and `enhancement` labels.

**Comment by jcarpenter** [comment]
Edited to refer to `getColor`. Originally referred (incorrectly) to `getSystemColor`. Solution may be the same as @ckerr [describes](https://github.com/electron/electron/issues/26628#issuecomment-732546923) tho: return as `RGBAValue` instead of `hexadecimalValue`.

**Comment by jcarpenter** [comment]
Just checking in on this. Am currently working around it by hard coding the values into my app, but that's obviously a brittle workaround.

**Comment by nornagon** [comment]
_Ideally_ we wouldn't make this change in a way that would break apps. Would it be worth introducing this as something like `systemPreferences.getSystemColor(color, { includeAlpha: true })` to make it non-breaking?

That said, this feature seems lightly used, so maybe breaking it is OK.

**Comment by inukshuk** [comment]
I'd argue that this is going to be a fix rather than a breaking change. In our case too, we've been trying to use this API but have resorted to hard-coded values and even spawning a child process to query `defaults`, because the current values without alpha are not useful for us.

**Comment by jcarpenter** [comment]
This is still open, I believe? 

#30055 added alphas to the values returned from `getSystemColor`, but we actually need alphas for `getColor()` values. 

The confusion may be my fault. When I opened this issue I confused the two functions, then [edited the issue](https://github.com/electron/electron/issues/26628#issuecomment-746838575) and title to correctly refer to `getColor`.

For the time being, without alphas from `getColor()`, I'm still resorting to hard-coding my OS color values.
