### ISSUE TITLE
On dual monitor with different DPI settings per monitor, Dialog boxes are not scaled correctly (too big)

### ISSUE THREAD

**Issue by Jawz84** [electron/electron#26622]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * Electron 9.3.3 (for VSCode 1.51.1)
* **Operating System:**
  * Windows_NT x64 10.0.19042
* **Last Known Working Electron version:**
  * unknown

### Expected Behavior
When I open a dialog box like Save, SaveAs or Open, I expect it to be scaled according to the DPI setting of the monitor the dialog box was opened on. 

### Actual Behavior
I have two monitors, primary display: 3840 x 2160 @ 225% scaling and a secondary display 2560x1440 @ 100% scaling. When I use my Electron app (VSCode in this case), the main window of the application is scaled to the right size (and displayed crisp and clear). The dialog boxes are scaled correctly on the 225% scaled monitor, but on the 100% scaled monitor, the dialog boxes are rendered way too big. As if they were drawn with the 225% scale which applies to the other monitor. The same goes for the context menu of the title bar, it is drawn too big on the 100% monitor.

### To Reproduce
Have your primary display set to 225% scaling, and a secondary display to 100%. Open an Electron app (VSCode, MSTeams), and right-click the title of the window. The context menu will be drawn in the scale of the primary display, whether its parent is on the primary or on the secondary display.

### Screenshots

![image](https://user-images.githubusercontent.com/26464885/99878238-4f7cc380-2c04-11eb-8f7d-a60fa6d392aa.png)

![image](https://user-images.githubusercontent.com/26464885/99878254-6a4f3800-2c04-11eb-9437-fc48e39d8c1c.png)
![image](https://user-images.githubusercontent.com/26464885/99878268-7d620800-2c04-11eb-882b-b1f393da8594.png)

**Comment by warpdesign** [comment]
Any update on this one? I stubbled upon this in latest (1.60.1) VSCode today, opened an issue to find out it had already been filled two years ago :/

**Comment by kwinz** [comment]
This has been plaguing apps like Atom and VSC for many years now.
It breaks essential dialogs such as "Open File".
Is this still not being triaged?

**Comment by rzhao271** [comment]
I have confirmed this issue still occurs in Windows 10 using Electron 17.1.2.
Here is a gist: https://gist.github.com/rzhao271/274a89722a9ff77f72239a3da177e138

Repro steps with gist above:
1. Launch the program.
2. Press Ctrl+O or Cmd+O to open the open file dialog. Note its size. Close the dialog.
3. Move the main window to a second monitor of a different size. It should automatically resize to the second monitor's proportions. In my case, I have my Surface laptop attached to a larger display monitor.
4. Repeat step 2. :bug: There is a mismatch in size between the main window and the open file dialog.

**Comment by kwinz** [comment]
This finaly appears to be fixed for me. Tested in Visual Studio Code `VSC 1.68.1` with `Electron 17.4.7`, `Windows_NT x64 10.0.19044`. The native file picker does not have crisp font on the HiDPI screen. So the font looks upscaled from whatever low DPI screen you are using. But at least it's the right size now. And it is usuable even if you drag the dialog from a HiDPI to a low DPI screen or vice versa.

**Comment by kwinz** [comment]
This finally appears to be resolved for me. Tested in Visual Studio Code `VSC 1.68.1` with `Electron 17.4.7`, `Windows_NT x64 10.0.19044`. It's not perfect as the native file picker does not use a crisp font on the HiDPI screen. It looks upscaled from whatever low DPI screen you are using. But at least it's the right size now. And it is usuable even if you drag the dialog from a HiDPI to a low DPI screen or vice versa.

**Comment by kwinz** [comment]
It seems to work with Windows 11 Version 21H2 (Build 22000.978). Still not a fix if you want to stay on Windows 10.
