### ISSUE TITLE
How to change two screens on  duplicate screens in electron

### ISSUE THREAD

**Issue by Ruslan27032000** [electron/electron#26645]
Hello everyone. I have some issues that i can't find in the internet. I have two screen on the extends mode and i want to change it in the electron on duplicate mode in time. Does electron has this properties.

**Comment by ckerr** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
