### ISSUE TITLE
Green layer glitch on computer wakeup

### ISSUE THREAD

**Issue by jooola** [electron/electron#26641]
### Issue Details
* **Electron Version:** v6.1.12 (atom 1.53) and v10.1.3 (element-desktop 1.7.13)
* **Operating System:**  Debian buster 64bit

### Expected Behavior
Should not print weird green layer in the electron application.

### Actual Behavior
Prints a weird green layer in the electron application after waking the computer from sleep.

### To Reproduce
This is rather difficult to predict, but here a some requirements to reproduce this :
- Use NVIDIA proprietary driver
- Let the computer go to sleep while having Atom or Element-dekstop running.
- Wake the computer and login

### Screenshots
![image](https://user-images.githubusercontent.com/19195485/99913928-a6fd5b00-2cfa-11eb-8128-de0951b46715.png)
![image](https://user-images.githubusercontent.com/19195485/99913942-b67ca400-2cfa-11eb-94c7-e49870e06c8a.png)
![image](https://user-images.githubusercontent.com/19195485/99913944-bb415800-2cfa-11eb-88ab-1c3a070315c6.png)

### Additional Information
I can fix this partially by moving the windows around and rerender some parts of the window.

**Comment by ckerr** [comment]
Hi @jooola, thanks for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/tutorial/support#supported-versions), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.

**Comment by jooola** [comment]
Please reopen, this also happen with the software element-desktop which uses electron v10.1.3 (element-desktop 1.7.13)
