### ISSUE TITLE
Last version of Electron creates error : "bash: warning: setlocale: LC_ALL: cannot change locale (fr)" in Visual Studio Code Terminal

### ISSUE THREAD

**Issue by Luk313** [electron/electron#26649]
Hello,
I don't exactly know the solution to this, bu it seems that your last electron update creates a new problem in Visual Studio Code Terminal, for Linux (but also other OS-es)
"**bash: warning: setlocale: LC_ALL: cannot change locale (fr)**" (in fact, any other language seems problematic)
Could you please solve this problem ?
Many thankxx, by advance :)

**Comment by zcbenz** [comment]
This has been fixed with https://github.com/electron/electron/pull/26507.
