### ISSUE TITLE
Document which system libraries are required on Linux

### ISSUE THREAD

**Issue by GChuf** [electron/electron#26673]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
11.0.3
* **Operating System:**
Minimal Raspberry OS - August 20th 2020

### Expected Behavior
Electron starts

### Actual Behavior
Electron gives an error message:
`/usr/local/lib/node_modules/electron/dist/electron: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory.`

The folder `electron `under `dist` does not exist.

### To Reproduce
It does this every time I run "electron" or "node cli.js"

### Additional Information

**The solution:** 

In order to run startx on minimal OS, I've installed the following:
`sudo apt-get install xserver-xorg-video-all xserver-xorg-input-all xserver-xorg-core xinit x11-xserver-utils`
This was not enough to run electron, though.

To solve all the problems with shared libraries, I've run the following:
`sudo apt install libnss3-dev libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0`

**Comment by nornagon** [comment]
It seems like you've solved the problem by installing the missing libraries. Electron requires those libraries to function and will not start on an OS that lacks them.

**Comment by GChuf** [comment]
Yes, I've figured that much ...
I'm reporting this for anyone who might encounter similar problems. It would save me some time if this was mentioned somewhere, but since it was not, I opened this issue.

**Comment by nornagon** [comment]
Ah, thanks, that wasn't clear from the description! I'll update the issue title to reflect that.

**Comment by max-programming** [comment]
I got this error when I ran `electron .`. But I am installing whatever @GChuf mentioned. SO let's see what happens now.

I am using WSL Ubuntu.

![image](https://user-images.githubusercontent.com/51731966/105281773-e3eaae80-5bd2-11eb-8b09-d2c326ad979c.png)

**Comment by andredezzy** [comment]
@max-programming do you found a solution?

**Comment by max-programming** [comment]
> @max-programming do you found a solution?

Sadly no. Now I don't use WSL

**Comment by andredezzy** [comment]
> > @max-programming do you found a solution?
> 
> Sadly no. Now I don't use WSL

Ah, thanks. I found a relative solution that is: Install the libraries with de Windows bash/CMD, and later can use the WSL run the Yarn or NPM commands, but never run `yarn install` or `npm install` on WSL.

**Comment by max-programming** [comment]
> > > @max-programming do you found a solution?
> > 
> > 
> > Sadly no. Now I don't use WSL
> 
> Ah, thanks. I found a relative solution that is: Install the libraries with de Windows bash/CMD, and later can use the WSL run the Yarn or NPM commands, but never run `yarn install` or `npm install` on WSL.

yep! That's the only solution possible! Forgot it completely.
I didn't like switching so now I am completely on Powershell 😅

**Comment by yeasin72** [comment]
![image](https://user-images.githubusercontent.com/47134306/131941784-9caf1215-8970-4b25-a096-5e8d0cc37149.png)

**Comment by U-DI-Page** [comment]
> > > > @max-programming do you found a solution?
> > > 
> > > 
> > > Sadly no. Now I don't use WSL
> > 
> > 
> > Ah, thanks. I found a relative solution that is: Install the libraries with de Windows bash/CMD, and later can use the WSL run the Yarn or NPM commands, but never run `yarn install` or `npm install` on WSL.
> 
> yep! That's the only solution possible! Forgot it completely. I didn't like switching so now I am completely on Powershell 😅

How do you install the libraries with de Windows bash/CMD, I try to install it on powershell, but got failed,"UNC path is not support"

**Comment by popuguytheparrot** [comment]
any updates?

**Comment by aliasadidev** [comment]
any updates?

**Comment by marcospgp** [comment]
Looking for this info as well, trying to run electron in a node docker container

Version in package.json: `"electron": "^22.0.3"`

The list of dependencies that fixed it for me is:

```text
# Electron runtime (non-build) dependencies.
# Discovered by trial & error.
# See more: https://github.com/electron/electron/issues/26673
# Build dependencies: https://www.electronjs.org/docs/latest/development/build-instructions-linux
RUN apt-get update \
    && apt-get install -y \
    libnss3 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libdrm2 \
    libgtk-3-0 \
    libgbm1 \
    libasound2
```

I went through the process of installing one by one and looking for the next error related to a missing dependency.

It would really help to include this in documentation, similarly to how build dependencies are listed here: https://www.electronjs.org/docs/latest/development/build-instructions-linux
