### ISSUE TITLE
Electron 11 breaks Error stack in a loaded iframe

### ISSUE THREAD

**Issue by sergeyd63** [electron/electron#26677]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  11.0.3
* **Operating System:**
  * All
* **Last Known Working Electron version:**
  * 10.1.6

### Expected Behavior

Should send a full Error stack

### Actual Behavior
In an iframe the error stack = "Error"

### To Reproduce
Website has an iframe. On load the stack is not loaded

### Screenshots
In a Browser (Chrome)
![image](https://user-images.githubusercontent.com/4738739/100126873-804f3980-2e4c-11eb-9d08-b56a53664c87.png)

In Electron 11
![image](https://user-images.githubusercontent.com/4738739/100127013-a8d73380-2e4c-11eb-8885-212aa8ec222f.png)

**Comment by jnises** [comment]
I'm getting the same issue. No iframes involved though.
In electron 10.1.6 i get this in the devconsole: 
![image](https://user-images.githubusercontent.com/1059884/100872677-722f9780-34a2-11eb-848e-206bb94fd68e.png)
In electron 11.0.3 I get this: 
![image](https://user-images.githubusercontent.com/1059884/100872719-84113a80-34a2-11eb-8a26-ae847621549b.png)

This breaks my Sentry integration for example.

**Comment by codebytere** [comment]
It would be helpful if either of you could please provide a reproducible sample. I can reproduce this with `contextIsolation` but not otherwise, and it's important for better triage that I know the _exact_ conditions under which you see this so I'm not forced to make guesses.

**Comment by jnises** [comment]
Yes. Only with contextIsolation.
Here is a minimal example: https://github.com/jnises/electron_stack_test

**Comment by codebytere** [comment]
thanks @jnises! I'll see what i can do.

**Comment by codebytere** [comment]
@jnises @sergeyd63 I've located the error and a fix is up

**Comment by jnises** [comment]
great :)
that was quick

**Comment by Raynos** [comment]
When will we have a new version of electron 11 that we can use that fixes this bug ?
