### ISSUE TITLE
Electron app stuck on loading on Windows Server

### ISSUE THREAD

**Issue by promatik** [electron/electron#26675]
* **Electron Version:**
  * 10.1.6 / 11.0.3
* **Operating System:**
  * Windows Server 2019
* **Last Known Working Electron version:**
  * 9.3.5

### Issue Details

After upgrade Electron from v9 to v10 or v11, my app stucks while loading.

I use `electron-packager@latest` to build the app for (win/mac/linux) and `electron-winstaller@latest` to build the windows setup installer.
This **happens only** with the setup version, on windows server (not on my windows/home/pro), only on production.

This only happens if I use Electron 10 or 11.

### Screenshots

![image](https://user-images.githubusercontent.com/1838187/100102700-e099a780-2e5b-11eb-86d8-6060333e7d01.png)

If I run the source code on the windows server even the prod build `npm run prod`, everything works, it just don't work with the built setup.

**Is there a way I can debug this?**

**Comment by VerteDinde** [comment]
Hey @promatik, thanks for reporting this issue. Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, Electron Fiddle is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/needs-repro label for this reason. After you make a test case, please link to it in a follow up comment. Thanks!

**Comment by viral98** [comment]
Same here, updated from electron 9.x to 11.x and I am facing the same intermittent issue quite a lot more than normal

**Comment by promatik** [comment]
Hi, today I tested a build with electron **v11.3.0**, and it works 🙌 finally.
I don't know if anyone focused on solving this or not, but it is now working for me, I'll close the issue for now.
