### ISSUE TITLE
Input fields does not focus when I clicked by mouse

### ISSUE THREAD

**Issue by aytacg26** [electron/electron#26678]
I created a from in electronjs and checked every single explanation about this subject and applied but none of them has figured out the problem. In the end I started to test on BrowserWindow web preferences and options one by one, to find out if any of them cause this problem and hence, I found that when I use the window with frame:false, it was not possible to click on them and when I made it true, everything started to work as expected. I think there is something wrong with frame option of the framework. 

**dependencies :** 
"electron-menubar": "^1.0.2",
    "electron-squirrel-startup": "^1.0.0",
    "jquery": "^3.5.1" _(Not using jquery)_

**All devDependencies :**
   "@electron-forge/cli": "^6.0.0-beta.54",
    "@electron-forge/maker-deb": "^6.0.0-beta.54",
    "@electron-forge/maker-rpm": "^6.0.0-beta.54",
    "@electron-forge/maker-squirrel": "^6.0.0-beta.54",
    "@electron-forge/maker-zip": "^6.0.0-beta.54",
    "electron": "11.0.2"

System Info : 
Windows 10 Pro

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  Electron Version : 11.0.2
* **Operating System:**
 Windows 10 Pro
* **Last Known Working Electron version:**
  *

**Comment by ariesjia** [comment]
I met same issue， is there any solutions?

**Comment by aytacg26** [comment]
I found that when I use the window with frame:false, it was not possible to click on them and when I made it true, everything started to work as expected.

**Comment by aytacg26** [comment]
> I met same issue， is there any solutions?

I found that when I use the window with frame:false, it was not possible to click on them and when I made it true, everything started to work as expected.
