### ISSUE TITLE
default userData directory is created in the default location when using app.setPath()

### ISSUE THREAD

**Issue by etiktin** [electron/electron#2668]
I'm using `app.setPath` to change the location where `userData` and `cache` are stored and it works (data is saved to the new location). The problem is that even due I set the paths before the `ready` event, the default location (`%APPDATA%/productName`) is still created.

To test this, I deleted the default path and added to the top of my main.js the following lines:
```javascript
var fs = require('fs');
console.log('Exists?', fs.existsSync('C:/Users/eran.t/AppData/Roaming/foo'));
```
The output was `Exists? true`, which means the directory was created by some initialization code (it looks like it comes from [here](https://github.com/atom/electron/blob/c441dd143690aab71a925f0b941a6d9760768fa5/atom/browser/lib/init.coffee#L88-L89)).

Is it possible to move the creation of the directories to when we actually need them (lazy creation), which will give the developer time to change them?

To circumvent the issue, one can simply delete the old path using `fs.rmdir` after changing the path to the new location, but it's not ideal.

**Comment by leshow** [comment]
Also seeing this bug on windows/osx
