### ISSUE TITLE
browserView.setBounds causes issues with focus and clicks if position is not x=0, y=0

### ISSUE THREAD

**Issue by mchataigner** [electron/electron#26681]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.x, 10.x, 11.x
* **Operating System:**
  * macOS 11.0.1 (was on macOS 10.15.7 with same issue before BigSur upgrade) (no issue on GNU/Linux, and not tested on Windows)
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
When a BrowserView is set to a position other than x=0, y=0, the whole viewable view should be focusable/clickable.

### Actual Behavior
When I set a BrowserView with bounds { x=0, y=150, width=window.width, heigth=window.height-150}, there is a rectangle at the bottom of the window of 150 pixels high where I cannot click.

### To Reproduce
I’ve create a small project to reproduce https://github.com/mchataigner/electronsample

```sh
$ git clone https://github.com/mchataigner/electronsample.git -b main
$ npm install
$ npm start
```

### Screenshots

<img width="800" alt="Screenshot 2020-11-24 at 22 27 05" src="https://user-images.githubusercontent.com/2926444/100153867-07c89700-2ea5-11eb-92fe-eecd35dceb31.png">
<img width="800" alt="Screenshot 2020-11-24 at 22 27 13" src="https://user-images.githubusercontent.com/2926444/100153871-0b5c1e00-2ea5-11eb-8a8c-d4ebe159499f.png">

**Comment by praneetrohida** [comment]
Did not have this issue on v10.1.5. It started happening after I upgraded to v11.0.3.

**Comment by sirtimid** [comment]
@codebytere This issue was caused by this PR https://github.com/electron/electron/pull/26322 It has to do with draggable regions, they are not calculated properly. There is a region at the end of the BrowserView that is the height of the top offset.

**Comment by andycreeth** [comment]
We are also experiencing this issue with [stream-labs/streamlabs-obs](https://github.com/stream-labs/streamlabs-obs).  We use a `BrowserView` positioned on the right side of the window.  On version `9.3.4`, the entire `BrowserView` is being treated as a drag region, and is not interactable.  We are downgrading to `9.3.3` on `macOS` for now, which resolves the issue.

The top post in this issue seems pretty complete, but happy to provide any additional details.

**Comment by sirtimid** [comment]
@codebytere So I see this was fixed for mac on https://github.com/electron/electron/pull/26690 and for windows on https://github.com/electron/electron/pull/26738 Can you backport the fixes on 9.x.x please?

**Comment by codebytere** [comment]
hey @sirtimid 9.x.x is mostly security now but i can try :)

**Comment by sirtimid** [comment]
> hey @sirtimid 9.x.x is mostly security now but i can try :)

thank you!! :)

**Comment by praneetrohida** [comment]
Is there any update on this issue? This has been blocking us from upgrading to 11

**Comment by codebytere** [comment]
@praneetrohida oops thanks for the ping! i already fixed this actually, in https://github.com/electron/electron/pull/27147 - latest 11 should contain it :)

**Comment by sirtimid** [comment]
@codebytere but it wasn't backported on 9.x.x :(
