### ISSUE TITLE
Mac Big Sur reports serveral crashes

### ISSUE THREAD

**Issue by showgoodjiang** [electron/electron#26687]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
8.5.0

* **Operating System:**
macOS 11.0.1

* **Last Known Working Electron version:**
Before upgrade to Big Sur, everthing is ok. 

### Expected Behavior
The electron application works

### Actual Behavior
There are 3 crashes after run several minutes.

### To Reproduce
Open the electron application in Mac Big Sur, after a while, get 3 different crashes.

### Additional Information

**Three crashes:**

1. Crashed Thread:        3  Chrome_IOThread

2. Crashed Thread:        0  CrGpuMain  Dispatch queue: com.apple.main-thread

3. Crashed Thread:        2  ThreadPoolForegroundWorker

**Crashes details:**

----------------------------------------------------------------------

1. Crashed Thread:        3  Chrome_IOThread

Date/Time:             2020-11-25 10:30:10.826 +0800
OS Version:            macOS 11.0.1 (20B50)
Report Version:        12
Anonymous UUID:        271D1432-5AA7-D5D5-1C5E-BB6C9DEBA243

Sleep/Wake UUID:       64BEC6BF-C275-4CCB-B616-4CB3B257CD6F

Time Awake Since Boot: 6700 seconds
Time Since Wake:       5800 seconds

System Integrity Protection: enabled

Crashed Thread:        3  Chrome_IOThread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Trace/BPT trap: 5
Termination Reason:    Namespace SIGNAL, Code 0x5
Terminating Process:   exc handler [2658]

Thread 3 Crashed:: Chrome_IOThread
0   com.github.Electron.framework 	0x000000010543fc47 0x103223000 + 35769415
1   com.github.Electron.framework 	0x0000000104e57232 0x103223000 + 29573682
2   com.github.Electron.framework 	0x0000000104e547ef 0x103223000 + 29562863
3   com.github.Electron.framework 	0x0000000104e5d5f4 0x103223000 + 29599220
4   com.github.Electron.framework 	0x0000000104e5edd1 0x103223000 + 29605329
5   com.github.Electron.framework 	0x0000000104c847b7 0x103223000 + 27662263
6   com.github.Electron.framework 	0x0000000105ac914a 0x103223000 + 42623306
7   com.github.Electron.framework 	0x000000010578aae8 0x103223000 + 39221992
8   com.github.Electron.framework 	0x0000000105accf57 0x103223000 + 42639191
9   com.github.Electron.framework 	0x0000000105ace18d 0x103223000 + 42643853
10  com.github.Electron.framework 	0x000000010578645f 0x103223000 + 39203935
11  com.github.Electron.framework 	0x000000010579f44e 0x103223000 + 39306318
12  com.github.Electron.framework 	0x000000010579f72a 0x103223000 + 39307050
13  com.github.Electron.framework 	0x000000010579ebc3 0x103223000 + 39304131
14  com.github.Electron.framework 	0x0000000103d57239 0x103223000 + 11747897
15  com.github.Electron.framework 	0x0000000103d56b5c 0x103223000 + 11746140
16  com.github.Electron.framework 	0x0000000103d534ed 0x103223000 + 11732205
17  com.github.Electron.framework 	0x0000000103d4a36e 0x103223000 + 11694958
18  com.github.Electron.framework 	0x00000001054792ff 0x103223000 + 36004607
19  com.github.Electron.framework 	0x000000010548967a 0x103223000 + 36071034
20  com.github.Electron.framework 	0x0000000105489417 0x103223000 + 36070423
21  com.github.Electron.framework 	0x00000001054e78c7 0x103223000 + 36456647
22  com.github.Electron.framework 	0x0000000105489f37 0x103223000 + 36073271
23  com.github.Electron.framework 	0x0000000105461707 0x103223000 + 35907335
24  com.github.Electron.framework 	0x0000000104caa6c4 0x103223000 + 27817668
25  com.github.Electron.framework 	0x00000001054a08a4 0x103223000 + 36165796
26  com.github.Electron.framework 	0x00000001054d2447 0x103223000 + 36369479
27  libsystem_pthread.dylib       	0x00007fff20318950 _pthread_start + 224
28  libsystem_pthread.dylib       	0x00007fff2031447b thread_start + 15

----------------------------------------------------------------------

2. Crashed Thread:        0  CrGpuMain  Dispatch queue: com.apple.main-thread

Date/Time:             2020-11-25 09:49:14.870 +0800
OS Version:            macOS 11.0.1 (20B50)
Report Version:        12
Anonymous UUID:        271D1432-5AA7-D5D5-1C5E-BB6C9DEBA243

Sleep/Wake UUID:       64BEC6BF-C275-4CCB-B616-4CB3B257CD6F

Time Awake Since Boot: 4200 seconds
Time Since Wake:       3300 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrGpuMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [2042]

VM Regions Near 0:
--> 
    __TEXT                      106c41000-106c7b000    [  232K] r-x/r-x SM=COW  /Applications/XXXXX.app/Contents/Frameworks/XXXXX Helper (GPU).app/Contents/MacOS/XXXXX Helper (GPU)

Thread 0 Crashed:: CrGpuMain  Dispatch queue: com.apple.main-thread
0   com.github.Electron.framework 	0x000000010f4d965a 0x10c1ab000 + 53667418
1   com.github.Electron.framework 	0x000000010fc76a5a 0x10c1ab000 + 61651546
2   com.github.Electron.framework 	0x000000010cce6f79 0x10c1ab000 + 11779961
3   com.github.Electron.framework 	0x000000010e1eb00f 0x10c1ab000 + 33816591
4   com.github.Electron.framework 	0x000000010e1eb167 0x10c1ab000 + 33816935
5   com.github.Electron.framework 	0x000000010cd123a0 0x10c1ab000 + 11957152
6   com.github.Electron.framework 	0x000000010e711bf6 0x10c1ab000 + 39218166
7   com.github.Electron.framework 	0x000000010ea55495 0x10c1ab000 + 42640533
8   com.github.Electron.framework 	0x000000010ea55583 0x10c1ab000 + 42640771
9   com.github.Electron.framework 	0x000000010e4012ff 0x10c1ab000 + 36004607
10  com.github.Electron.framework 	0x000000010e41167a 0x10c1ab000 + 36071034
11  com.github.Electron.framework 	0x000000010e411417 0x10c1ab000 + 36070423
12  com.github.Electron.framework 	0x000000010e460261 0x10c1ab000 + 36393569
13  com.github.Electron.framework 	0x000000010e45baaa 0x10c1ab000 + 36375210
14  com.github.Electron.framework 	0x000000010e45fb3f 0x10c1ab000 + 36391743
15  com.apple.CoreFoundation      	0x00007fff204109fc __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
16  com.apple.CoreFoundation      	0x00007fff20410964 __CFRunLoopDoSource0 + 180
17  com.apple.CoreFoundation      	0x00007fff204106df __CFRunLoopDoSources0 + 248
18  com.apple.CoreFoundation      	0x00007fff2040f111 __CFRunLoopRun + 890
19  com.apple.CoreFoundation      	0x00007fff2040e6be CFRunLoopRunSpecific + 563
20  com.apple.Foundation          	0x00007fff21198fa1 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
21  com.github.Electron.framework 	0x000000010e460771 0x10c1ab000 + 36394865
22  com.github.Electron.framework 	0x000000010e45f4d2 0x10c1ab000 + 36390098
23  com.github.Electron.framework 	0x000000010e411f37 0x10c1ab000 + 36073271
24  com.github.Electron.framework 	0x000000010e3e9707 0x10c1ab000 + 35907335
25  com.github.Electron.framework 	0x00000001117cb3a0 0x10c1ab000 + 90309536
26  com.github.Electron.framework 	0x000000010dac3cbc 0x10c1ab000 + 26315964
27  com.github.Electron.framework 	0x000000010fd0bce4 0x10c1ab000 + 62262500
28  com.github.Electron.framework 	0x000000010cd80bd4 0x10c1ab000 + 12409812
29  com.github.Electron.framework 	0x000000010c1ad4d4 ElectronMain + 84
30  com.skytech.octopuscloudMac.helper.GPU	0x0000000106c41f85 0x106c41000 + 3973
31  libdyld.dylib                 	0x00007fff20333631 start + 1

----------------------------------------------------------------------

3. Crashed Thread:        2  ThreadPoolForegroundWorker

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: in dlopen_preflight()
abort() called
XXXXX Helper (GPU)(2983,0x70000fa86000) malloc: Incorrect checksum for freed object 0x7fd05b622508: probably modified after being freed.
Corrupt value: 0x73656372756f7365

Thread 2 Crashed:: ThreadPoolForegroundWorker
0   libsystem_kernel.dylib        	0x00007fff20302462 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff20330610 pthread_kill + 263
2   libsystem_c.dylib             	0x00007fff20283720 abort + 120
3   libsystem_malloc.dylib        	0x00007fff20164430 malloc_vreport + 548
4   libsystem_malloc.dylib        	0x00007fff20178702 malloc_zone_error + 183
5   libsystem_malloc.dylib        	0x00007fff20159502 tiny_malloc_from_free_list + 1805
6   libsystem_malloc.dylib        	0x00007fff20158876 tiny_malloc_should_clear + 233
7   libsystem_malloc.dylib        	0x00007fff20157793 szone_malloc_should_clear + 66
8   com.github.Electron.framework 	0x0000000111a92495 0x10f7d6000 + 36422805
9   com.github.Electron.framework 	0x0000000111a92495 0x10f7d6000 + 36422805
10  libsystem_malloc.dylib        	0x00007fff20170dfe _malloc_zone_malloc + 118
11  libc++abi.dylib               	0x00007fff202f6daa operator new(unsigned long) + 26
12  libc++.1.dylib                	0x00007fff202c7023 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__grow_by_and_replace(unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, char const*) + 137
13  libc++.1.dylib                	0x00007fff202c7c5f std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::append(char const*, unsigned long) + 93
14  com.apple.Metal               	0x00007fff282eec38 getCompilerTimeStampHash(int, MTLUINT256_t*) + 98
15  com.apple.Metal               	0x00007fff2837256e invocation function for block in getLibrariesCache(int) + 42
16  libdispatch.dylib             	0x00007fff201857c7 _dispatch_client_callout + 8
17  libdispatch.dylib             	0x00007fff2018696b _dispatch_once_callout + 20
18  com.apple.Metal               	0x00007fff282eebca getLibrariesCache(int) + 149
19  com.apple.Metal               	0x00007fff28361c52 MTLLibraryBuilder::initLibraryContainerWithRequestData(MTLLibraryContainer*, void*, unsigned long, MTLBuildRequestType, MTLCompileOptions const*, MTLCompilerFunctionRequest const*, unsigned int, bool, void () block_pointer) + 140
20  com.apple.Metal               	0x00007fff283630d4 MTLLibraryBuilder::newLibraryWithRequestData(void*, unsigned long, MTLBuildRequestType, MTLCompileOptions const*, MTLCompilerFunctionRequest const*, unsigned int, bool, void (id<MTLLibrary>, NSError*) block_pointer) + 254
21  com.apple.Metal               	0x00007fff28364bbc MTLLibraryBuilder::newLibraryWithSource(id<MTLDevice>, NSString*, MTLCompileOptions*, bool, void (id<MTLLibrary>, NSError*) block_pointer) + 5952
22  com.apple.Metal               	0x00007fff2833c121 -[_MTLDevice newLibraryWithSource:options:completionHandler:] + 75
23  com.github.Electron.framework 	0x0000000112aacf17 0x10f7d6000 + 53309207
24  com.github.Electron.framework 	0x0000000112aad51b 0x10f7d6000 + 53310747
25  com.github.Electron.framework 	0x0000000111a2c2ff 0x10f7d6000 + 36004607
26  com.github.Electron.framework 	0x0000000111a47262 0x10f7d6000 + 36115042
27  com.github.Electron.framework 	0x0000000111a46d38 0x10f7d6000 + 36113720
28  com.github.Electron.framework 	0x0000000111a84f8d 0x10f7d6000 + 36368269
29  com.github.Electron.framework 	0x0000000111a46884 0x10f7d6000 + 36112516
30  com.github.Electron.framework 	0x0000000111a4e3da 0x10f7d6000 + 36144090
31  com.github.Electron.framework 	0x0000000111a4e204 0x10f7d6000 + 36143620
32  com.github.Electron.framework 	0x0000000111a85447 0x10f7d6000 + 36369479
33  libsystem_pthread.dylib       	0x00007fff20330950 _pthread_start + 224
34  libsystem_pthread.dylib       	0x00007fff2032c47b thread_start + 15

**Comment by jiangjianping** [comment]
@showgoodjiang 

My electron application encountered with "GPU crashed" alert in "Mac Big Sur", the electron version is  8.5.2 and 11.0.x. Could you tell me how to get the crash details as yours?

**Comment by jiangjianping** [comment]
Got the following crash info from the command line. 

(https://user-images.githubusercontent.com/14144270/100215616-2c2b7e80-2f4c-11eb-816b-9d2340c05a01.png)

**Comment by nornagon** [comment]
The version of Electron you're using is [no longer supported](https://www.electronjs.org/docs/tutorial/support#currently-supported-versions).

**Comment by showgoodjiang** [comment]
> @showgoodjiang
> 
> My electron application encountered with "GPU crashed" alert in "Mac Big Sur",before "MAC Big Sur", everything is ok. the tested electron version is 8.5.2 and 11.0.x. Could you tell me how to get the crash details as yours?

Finder, Right Click, Go to Folder..., Enter:
~/Library/Logs/DiagnosticReports/

**Comment by jiangjianping** [comment]
Thank you very much!

**Comment by tuxianchao** [comment]
same issure,do you fix it?

**Comment by tuxianchao** [comment]
my env:
# electron:
* 11.0.3
#  Operating System
* MacOS bigsur 11.0.1(macbook pro 2017)
* MacOS bigsur 11.1(macbook air 2020)

**Comment by showgoodjiang** [comment]
> same issue ,do you fix it?

Updated to the latest Electron version, solved our issues.

**Comment by tuxianchao** [comment]
> > same issue ,do you fix it?
> 
> Updated to the latest Electron version, solved our issues.
 the latest version is refer to Electron 12.0.0beta or 13.0.0nightly？I get latest version is 11.1.1 in Electron Official website.can you tell me detail version. Thanks

**Comment by skylingfly** [comment]
> > same issue ,do you fix it?
> 
> Updated to the latest Electron version, solved our issues.

can you tell us the details, should we modify the entitlements.mac.plist file.

**Comment by wenssh** [comment]
> Thank you very much!
same issue,
do you fix it ?

**Comment by wenssh** [comment]
> Thank you very much!
same issue,
do you fix it ? @jiangjianping

**Comment by wenssh** [comment]
https://chromium-review.googlesource.com/c/chromium/src/+/2526161 chromium fix it

**Comment by tuxianchao** [comment]
> https://chromium-review.googlesource.com/c/chromium/src/+/2526161 chromium fix it

We checked this commit in our src of electron, which the chromium src is "HEAD detached from 87.0.4200.67".
The modifications mentioned by "2526161" are already in 87.0.4200.67.
So the GPU crash is caused by other reason not yet discovered
The same program running on Chromium of version "87.0.4200.67" will not crash at all,
even if the chromium is build directly from src at tag "87.0.4200.67".
So maybe the crash is not related to chromium.
