### ISSUE TITLE
Changing Window to 'visibleOnFullScreen' doesn't work unless you click on the window after the change

### ISSUE THREAD

**Issue by jetlej** [electron/electron#26683]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
10.1.3 - 11.0.0-beta.20
* **Operating System:**
Mac OS Catalina + Big Sur (tried on both)

### Expected Behavior
If I update a Window to be visible over full-screen apps (`win.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: true })`) and then switch to a full-screen app, it should show on top of it. 

### Actual Behavior
Instead, if I update a Window with the above code, I then need to click on the window again to make it focused or else it will not show on top of full-screen apps. 

### To Reproduce
Run this Electron Fiddle: https://gist.github.com/jetlej/a9656acb4a84fc590dc814ab4c6ec576
After 1 second, it will change the Window to be visible on full-screen apps. Don't click the window, and switch to a full-screen app. 

### Video of it happening

https://www.loom.com/share/e7a6eebdbf8f4d5f8916fc5c4513c7a5

**Comment by jetlej** [comment]
Can someone look at this? I provided all documentation

**Comment by jetlej** [comment]
Hello?

**Comment by nmalzieu** [comment]
Hi @jetlej , did you ever manage to make this work?

**Comment by Deuscx** [comment]
same issue. any update?
