### ISSUE TITLE
Renderer process crashes when Electron is launched by VSCode debugger

### ISSUE THREAD

**Issue by aabuhijleh** [electron/electron#26691]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *   11.0.3, 13.1.4
* **Operating System:**
  *  Windows 10
* **Last Known Working Electron version:**
  *  10.1.6

### Expected Behavior

If Electron is launched using VSCode's debugger as seen [here](https://www.electronjs.org/docs/tutorial/debugging-vscode) in Electron's documentation about debugging the main process, the renderer process should not crash when loading "https://github.com/"

### Actual Behavior

If Electron is launched using VSCode's debugger, the renderer process crashes when loading "https://github.com/"

### To Reproduce

```sh
$ git clone https://github.com/aabuhijleh/electron-typescript-quick-start
```

Edit `src/main.ts`: load a remote URL instead of `mainWindow.loadFile(...)`

```ts
mainWindow.webContents.on("crashed", () => {
  console.log("renderer process crashed"); // this will be called
});

mainWindow.loadURL("https://github.com/");
```

The `.vscode/launch.json` file is already configured in that repo

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug Main Process",
      "type": "node",
      "request": "launch",
      "cwd": "${workspaceFolder}",
      "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron",
      "windows": {
        "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron.cmd"
      },
      "args" : ["."],
      "outputCapture": "std"
    }
  ]
}
```

Open the project in VSCode and press F5 to run the app using the debugger

The renderer process will crash

### Screenshots

![image](https://user-images.githubusercontent.com/42934634/100203302-16e23000-2f0b-11eb-8372-0143b92fab69.png)

### Additional Information

* I tried on several Windows 10 64-bit machines and they all had the same issue. I tried both 32 and 64 bit Electron binaries. I also tried on macOS 11.0.1 but it looks like this issue is not present there.

* I noticed that the process does not crash if I uncomment this line `mainWindow.webContents.openDevTools()` in `src/main.ts`

**Comment by mlaurencin** [comment]
Are you able to reproduce this with urls other than `github.com`, @aabuhijleh? I am similarly able to reproduce the issue with the steps you provided (and also with `mainWindow.webContents.openDevTools()` uncommented), but I have not had it crash with urls to other sites.

**Comment by aabuhijleh** [comment]
The actual site I want to load in my app is "https://web.openrainbow.com". I noticed strange behaviour when loading that with Electron 11. I think I'm getting a blank page (and maybe a crash) if I remember correctly (I'm using a mac right now, I will let you know exactly what happens once I try it). It loads normally with Electron 10

The main point, I noticed something is broken with "https://web.openrainbow.com" & "https://github.com" with Electron 11

I tried a few others but they appear to be ok

Unfortunately, I'm not sure what makes these two websites break Electron while others are fine

If it helps, I know that when you load https://web.openrainbow.com you are redirected (you get something like a page reload), so maybe that is causing a strange behavior?

**Comment by mlaurencin** [comment]
Unfortunately, this seems to be an edge case of some kind. However, I will keep this issue open in case someone else wants to take a look. 

From what I have tried, I have not had any luck recreating this with other pages that generate HTTP redirects. It could possibly be related to page reloading or domain forwarding, but I have not been able to recreate it with sites that utilize these either.

**Comment by nornagon** [comment]
If possible, would you be able to collect a crash report from the renderer and attach it here?

You can do so by adding the following to the main process:

```js
const { crashReporter, app } = require('electron')
crashReporter.start({
  submitURL: "https://example.com",
  uploadToServer: false,
})
console.log(`Crash dumps directory: ${app.getPath('crashDumps')}`)
```

Trigger the crash, and then look in the crash dumps directory. You should see a `.dmp` file in one of the subdirectories—please attach it as a comment in this issue!

**Comment by aabuhijleh** [comment]
@nornagon 

Unfortunately, there's no crash dump file generated at the crash dump directory `C:\Users\aabuhijleh\AppData\Roaming\electron-typescript-quick-start\Crashpad`, there's just an empty `reports` directory and an empty `metadata` file and `settings.dat` file

Even though the events `render-process-gone` and `crashed` are fired

![image](https://user-images.githubusercontent.com/42934634/102768836-70af0c00-438a-11eb-896f-5ae938490d1c.png)

**Comment by aabuhijleh** [comment]
@nornagon Maybe I'm doing something wrong. @mlaurencin are you able to get a crash dump `.dmp` file from this crash?

**Comment by aabuhijleh** [comment]
Issue seems to be fixed with Electron 11.3.X and 12.X so I'm closing this.

**Comment by aabuhijleh** [comment]
@nornagon @mlaurencin I can reproduce this crash 100% of the time with `13.1.4` when I set the BrowserWindow option `contextIsolation` to `false`. 

If I set `contextIsolation` to `true`, I can debug without crashing. I still can't get a crash dump. The `crashDump` directory is always empty

**Comment by nornagon** [comment]
@aabuhijleh hmm, that's a bit troubling that the crash reporter wouldn't be able to capture the crash. Do you see any evidence of the crash in the Windows Event Viewer?

**Comment by aabuhijleh** [comment]
@nornagon I used [`GFlags` to monitor the electron process exists](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/registry-entries-for-silent-process-exit)

![image](https://user-images.githubusercontent.com/42934634/124712688-4f69d380-df08-11eb-8af6-82a0468c26d3.png)

First of all, according to the Windows Event Viewer and the `details` object in the Electron `render-process-gone` event, the exist code of the renderer process is **134** (not sure how helpful this information is)

Second, I got an exist dump from the Windows Silent Process monitor
[electron.exe-(PID-12232)-65923859.zip](https://github.com/electron/electron/files/6774986/electron.exe-.PID-12232.-65923859.zip)

I hope this helps

**Comment by nornagon** [comment]
Exit code 134 appears to be [SIGABRT](https://source.chromium.org/chromium/chromium/src/+/main:tools/metrics/histograms/enums.xml;l=15986;drc=32b9d3fd2015b21fa27b3832fbda0a5f9e56785c), for what it's worth.

**Comment by aabuhijleh** [comment]
It **IS** troubling that `crashReporter` is not able to capture these logs **BUT** losing the ability to debug the main process code is also a big issue for me. I don't understand how this issue is not more widespread

**Comment by nornagon** [comment]
FWIW, I'm successfully able to debug main process code with the Chrome devtools by passing `--inspect` to the Electron app and attaching via opening `about:inspect` in Chrome. I'm not sure what VS Code is doing differently.
