### ISSUE TITLE
No built-in 'About' dialog on Linux

### ISSUE THREAD

**Issue by VictorioBerra** [electron/electron#26694]
### Preflight Checklist

* [ X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * Tested with 11.0.0-beta-20 and 6
* **Operating System:**
  * **Kubuntu 20.04 x64**

### Expected Behavior
```javascript
{ label: "About", type: "normal", role: "about" },
```

Should open About dialog.

### Actual Behavior
About dialog does not work.

### To Reproduce
Open Electron Fiddle in Kubuntu, try using `'about` role for `Menu`. Nothing happens.

### Additional Information
Nothing ion console or developer console output.

**Comment by ckerr** [comment]
Confirmed.

On Windows, the automatic 'About' dialog is created by https://github.com/electron/electron/blob/bb3fb548d817c101b11ed54af1eb77f3ee7ccc6e/lib/browser/api/menu-item-roles.ts#L28

On Mac, the automatic 'About' dialog is created by NSApp sendAction via sendActionToFirstResponder.

On Linux, there's currently no default About dialog. We could probably take an approach similar to how it's done on Windows.

**Comment by vraravam** [comment]
ping for freshness
