### ISSUE TITLE
Webview Bypassing sytem proxy in ubuntu

### ISSUE THREAD

**Issue by snjv42** [electron/electron#26697]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
I have created a customized browser app using webview.it is working perfectly fine but when i apply any proxy setting in the system then it detects in windows but it bypass the system proxy settings in Linux(Ubuntu) OS.
* **Electron Version:**
3.0.2
  * 
* **Operating System:**
Ubuntu 16
  * 

### Expected Behavior
Should not bypass the system proxy settings in Linux(Ubuntu) OS.

### Actual Behavior
bypassing the system proxy settings in Linux(Ubuntu) OS.
In webview

### To Reproduce
1.Go to network setting add manually any proxy addresse or invalid proxy (111.0.0.0) 
2.Try to open any website from browser of OS, it will not open in case of invalid proxy that means installed browser detecting proxy settings 
3. Now if you will open the website from webview through electron it will open the website in case of invalid proxy that means it is bypassing system proxy

**Comment by nornagon** [comment]
The version of Electron you're using is [no longer supported](https://www.electronjs.org/docs/tutorial/support#currently-supported-versions).
