### ISSUE TITLE
Mac child browserwindow with setIgnoreMouseEvents(true, {forward:false}), mousemove event only fires when mouse button held down

### ISSUE THREAD

**Issue by jollySwag** [electron/electron#26718]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.0.3 & 9.3.5
* **Operating System:**
  * macOS High Sierra / macOS catalina / macOs big sur
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior

On Child Window, if setIgnoreMouseEvents(true, {forward:false}), window.addEventListener("mousemove") should fire on moving the mouse over the window area.

### Actual Behavior

On Mac the mousemove event only fires when mouse button is also simultaneously held down over child window area when moving mouse.
While on windows it works as expected.

### To Reproduce

Here is an example repo using electron-quick-start
https://github.com/jollySwag/MacOsOverlayTest

$ git clone https://github.com/jollySwag/MacOsOverlayTest.git
$ npm install
$ npm start 

### Additional Information

It works as expected on windows, haven't tested on linux.

**Comment by jollySwag** [comment]
Here is a preview of it working correctly on windows.


![childWindowIssue](https://user-images.githubusercontent.com/72866943/100456311-e1f0fb80-310b-11eb-86b9-1d34a7346a2b.gif)

**Comment by jollySwag** [comment]
Here is a preview of it working incorrectly on mac

![macmouseoverissue](https://user-images.githubusercontent.com/72866943/100489722-cca6bc00-3161-11eb-8ffc-8a151f2932c3.gif)

**Comment by ckerr** [comment]
I tested on Big Sur + Electron 11.0.3 and got the same results as in the screenshots above wrt the mouse events in the left-hand square.

Behavior on Ubuntu 20.10 + Electron 11.0.3 was broken in a way that is off-topic to this issue, the overlay appeared to dominate the entire window s.t. only the single "Click me" box was visible. :1st_place_medal:

**Comment by wapgear** [comment]
Any updates on this one? Still facing issue on latest MacOS
