### ISSUE TITLE
Strange behavior with name resolution and event loop

### ISSUE THREAD

**Issue by charlag** [electron/electron#26719]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
Issuing network requests to localhost make request stuck after TCP handshake for a few (2-20) seconds. Does *not* happen with just Node.js. Does *not* happen with IP address instead of domain name. Does *not* happen if there's a `console.log()` executed while it's stuck (what?).

This sounds very unlikely but I've spent 3 days debugging this and I don't see any explanation so far. 

* **Electron Version:**
  v11.0.3
* **Operating System:**
  Ubuntu 20.04.1 LTS
* **Last Known Working Electron version:**
  N/A

### Expected Behavior
Requests do not get delayed for random periods of time.

### Actual Behavior
Requests do get delayed/time out.

### To Reproduce
```
git clone https://github.com/tutao/electron-bug
npm ci
node server &
npm start
```
Observe that after some requests they get delayed. For me it looks like this:
```
starting 0
request
finished 0 in 138
starting 1
request
finished 1 in 4045
starting 2
request
finished 2 in 7821
```

If you uncomment this line
```js
setImmediate(() => console.log("Uncomment me to make requests go fast!!"))
```
it becomes fast again.

If you change `localhost` to `127.0.0.1` it becomes fast again.
If you run it with `node` instead of `electron` (same version, 12.18.3, yes) it becomes fast again.

Thank you.

**Comment by ckerr** [comment]
I'm seeing the same behavior.  Tested with Electron 11.0.3 and Ubuntu 20.10.

Initial run:

```
> test-electorn-app@1.0.0 start
> electron .

starting 0
request
finished 0 in 158
starting 1
request
finished 1 in 4048
starting 2
request
finished 2 in 7796
starting 3
request
finished 3 in 8214
```

With the line uncommented:

```
> test-electorn-app@1.0.0 start
> electron .

starting 0
request
Uncomment me to make requests go fast!!
finished 0 in 165
starting 1
request
Uncomment me to make requests go fast!!
finished 1 in 2
starting 2
request
Uncomment me to make requests go fast!!
finished 2 in 4
starting 3
request
Uncomment me to make requests go fast!!
finished 3 in 5
```
