### ISSUE TITLE
Display local PDF with cmd switch "disable-site-isolation-trials"

### ISSUE THREAD

**Issue by simann** [electron/electron#26714]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  10.1.5
* **Operating System:**
  *  Windows 10 x64
* **Last Known Working Electron version:**
  * 

### Expected Behavior

Render a local PDF (PDF file in the app root) in a BrowserWindow with cmd switch 'disable-site-isolation-trials'
### Actual Behavior

Opens a BrowserWindow but the PDF is not loaded and the window stays grey. Besides that there is no error message saying what went wrong.

### To Reproduce

Minimal example to reproduce

```
#################main.js##############
const { app, BrowserWindow, session } = require('electron');
const { join } = require('path');

// uncomment this line to break the PDF Viewer
//app.commandLine.appendSwitch('disable-site-isolation-trials');
async function ready() {
  const mainWindow = new BrowserWindow({
    x: 0,
    y: 0,
    width: 800,
    height: 800,
    show: true,
  });
  mainWindow.loadURL(join("file://", __dirname, "main.html"));
}

app.whenReady().then(ready);

#################main.html##################
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
</head>
<body>
    <embed src="test.pdf" style="width:100%;height:400px">
</body>
</html>
```

### Screenshots
With cmd switch "disable-site-isolation-trials"
![pdf_not_working](https://user-images.githubusercontent.com/28533890/100439191-81c66f00-30a3-11eb-852c-b854978fe406.png)

Without cmd switch "disable-site-isolation-trials"
![pdf_working](https://user-images.githubusercontent.com/28533890/100439193-825f0580-30a3-11eb-85b2-045cf68225be.png)

### Additional Information

The PDf File "test.pdf" is in the root of my application.

Any help or hint would be appreciated :)

Greetings Simon

**Comment by asiercamara** [comment]
Same problem using "electron": "11.0.3"

**Comment by gdavidkov** [comment]
I have the same problem using the latest Electron 11.2.1. This issue is not observed in Chrome when it is started with --disable-site-isolation-trials.

**Comment by ckerr** [comment]
Gist form of @simann's testcase: https://gist.github.com/ckerr/7985be12498d49847bc2055723ecee1e

Tested on Ubuntu 20.10 with Electron 11.2.1. In that gist's package.json, `start` and `start2` are the scripts to run to see the difference in whether the command-line switch is passed.

**Comment by m4heshd** [comment]
The issue is still present in Electron `v12.0.0`.

**Comment by nornagon** [comment]
Updated gist, since the previous one stopped working due to X-IFrame-Options: https://gist.github.com/c98992fbd090d8fbaf9077e30db6d846

I see this log message which might provide a clue:

```
11:28:35 AM [84778:0708/112835.836391:INFO:CONSOLE(6)] "Not allowed to load local resource: chrome://resources/css/text_defaults_md.css", source: chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/index.html (6)
```

**Comment by wingsico** [comment]
Any progress?

**Comment by phablulo** [comment]
I'm having the same issue with versions `15-x-y` and `16-x-y`.

**Comment by BishopOoma** [comment]
Same issue and it's preventing functionality in combination with this issue:
[https://github.com/electron/electron/issues/18214](https://github.com/electron/electron/issues/18214)
ref: [Jitsi notes](https://github.com/jitsi/jitsi-meet-electron-sdk#note)

If we use `disable-site-isolation-trials` option then Jitsi screen-sharing works but we lose the ability to display PDFs.
If don't use `disable-site-isolation-trials` then we can display PDFs but Jitsi screen-sharing is broken.

Has anyone found a solution for this?

**Comment by BishopOoma** [comment]
bump

**Comment by deiucanta** [comment]
bump

**Comment by biology-w** [comment]
bump

**Comment by pioupia** [comment]
bump

**Comment by xiaoxiaocoder** [comment]
bump

**Comment by phucsang0spt** [comment]
bump
