### ISSUE TITLE
First wheel event not fired after focus got

### ISSUE THREAD

**Issue by backdround** [electron/electron#26715]
* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to find, without success.

### Issue Details

* **Electron Version:**
  v13.0.0-nightly.20201126
* **Operating System:**
  Archlinux 5.9.8-arch1-1
* **Last Known Working Electron version:**
  * 

### Expected Behavior
After window (application) got focus, wheel events works properly

### Actual Behavior
First wheel event not fired

### To Reproduce
```html
<head>
  <script>
    document.addEventListener('DOMContentLoaded', () => {
      document.onwheel = (event) => {
        console.log(event)
      }
    })
  </script>
</head>
```
or
https://github.com/backdround/electron_first_mouse_scroll_event_bug

**Comment by ckerr** [comment]
Confirmed: if you move the mouse scroll wheel slowly, the first click does not trigger an onwheel event. subsequent clicks do and trigger the `console.log()` code as expected:

```
<head>
  <script>
    document.addEventListener('DOMContentLoaded', () => {
      document.onwheel = (event) => {
        console.log(event)
      }
    })
  </script>
</head>
```

**Comment by charbelnicolas** [comment]
I reported this to chromium a few days ago:

[Chromium bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=1252801#c7)

**Comment by charbelnicolas** [comment]
It's actually a GTK 3 bug?

It's not getting fixed, ever, by the way.

https://gitlab.gnome.org/GNOME/gtk/-/issues/558
