### ISSUE TITLE
Apple Silicon Universal Support

### ISSUE THREAD

**Issue by lutzroeder** [electron/electron#26710]
### Problem Description

The [Apple Silicon Support](https://www.electronjs.org/blog/apple-silicon) document contains:

> In the future, we will release a package that allows you to "merge" your arm64 and x64 apps into a single universal binary, but it's worth noting that this binary would be huge and probably isn't ideal for shipping to users.

Is there further information, context, schedule or an issue available tracking this universal binary work?

### Proposed Solution

One approach seems to be to provide a `universal` Electron wrapper that could be targeted in parallel to `x64` and `arm64`. The other approach would be tooling to merge `x64` and `arm64` which would lead to questions how this would integrate with [electron-builder](https://github.com/electron-userland/electron-builder) (the initial focus seems to be on [electron-packager](https://github.com/electron-userland/electron-packager) and [electron-forge](https://github.com/electron-userland/electron-forge) which at this point are not used by the majority of Electron apps).

@MarshallOfSound @nornagon

**Comment by MarshallOfSound** [comment]
> Is there further information, context, schedule or an issue available tracking this universal binary work?

This package already exists, there's work outstanding to turn that blog post into a living document and update it with the universal information.  But you can find / use the `@electron/universal` package here --> https://github.com/electron/universal

Basically it takes your `x64` app and your `arm64` app and `lipo`'s them together into a single universal app.  This will all be documented better once we've taken that blog post and put it into the `guides` section of the electron docs.

> One approach seems to be to provide a universal Electron wrapper that could be targeted in parallel to x64 and arm64.

This is not a viable solution right now as it would require a bunch of ecosystem changes in particular to `node-gyp` to support targeting "universal" native node addons.  Currently it is single-arch targeting. 

>  which would lead to questions how this would integrate with electron-builder (the initial focus seems to be on electron-packager and electron-forge which at this point are not used by the majority of Electron apps).

Honestly speaking, `electron-builder` is **not supported** by the Electron maintainers, there is nothing we can do to support that package and `electron-builder` has actively moved off of tooling that we provide and support.  Things like `electron-osx-sign`, `electron-packager` and `electron-forge` are all effectively guaranteed to work with the Latest Electron things like structure changes and new architectures / features, we can't make any guarantees about `electron-builder`.

If you want to use `electron` provided and supported tooling, `electron-builder` isn't the right path for you.

**Comment by lutzroeder** [comment]
@MarshallOfSound are there some good sample apps using `electron-forge` on GitHub? Hours of searching on seem to point towards most apps using `electron-builder` and few using `electron-forge` and often older versions than the 6.0 bits described in the documentation. Since switching is likely an expensive path losing users to auto update not working, it would be great if there was some more context why there is this much of a disconnect between what the community is using, few samples that are available and what is officially supported.

**Comment by MarshallOfSound** [comment]
I don't personally understand the "losing users to auto update not working" comment because every electron app I've ever worked on uses electrons built in auto updater perfectly fine, in fact I've only seen and heard stories of that updater being flawed / not being enterprise appropriate / bricking users and making their apps not update.  The only thing the engineering efforts of electron support and ensure work for every version of electron is our built in updater.

I believe it's effectively misinformation from builders docs and good SEO for the name "electron builder" that results in people using it.  I don't have enough words in a github comment to truly explain why I avoid electron builder and advise users do too.  Maybe I'll write a blog post one day 😅

For now though, just know that all electron designed and built tooling isn't locking you into to using the rest of it.  I.e. `@electron/universal` just takes in two paths and returns a promise, super simple and easy to compose into any build system.

**Comment by lutzroeder** [comment]
> I don't personally understand the "losing users to auto update not working" comment because every electron app I've ever worked on uses electrons built in auto updater perfectly fine

Is it possible to switch from `electron-builder` to `electron-forge`, publishing exactly the same files with the same names in the right locations so existing `electron-builder` apps running on users machines would successfully pick up the new bits on all platforms?

> I believe it's effectively misinformation from builders docs and good SEO for the name "electron builder" that results in people using it.

I disagree. Having tried both the verdict is `electron-builder` gets the job done and that's why it's successful. `electron-forge` not so much, harder to get started, lots of things to stumble on, it's hard to find complex sample apps on GitHub using it successfully, it seems to be a moving target. Maybe it would go a long way taking a complex `electron-builder` project and converting it to `electron-forge` as often it's details that get in the way. Hence the question if there are such apps out there?

> For now though, just know that all electron designed and built tooling isn't locking you into to using the rest of it. I.e. @electron/universal just takes in two paths and returns a promise, super simple and easy to compose into any build system.

Understood, before digging into that I'm trying to understand if anything can be done to avoid reinventing the wheel to have the library that is broadly used by the community trying to catch up with the library that is officially supported.

**Comment by lutzroeder** [comment]
> I don't personally understand the "losing users to auto update not working" comment because every electron app I've ever worked on uses electrons built in auto updater perfectly fine

Is it possible to switch from `electron-builder` to `electron-forge`, publishing exactly the same filesin the right locations so the existing `electron-builder` app running on users machines would successfully pick up the new bits on all platforms through an auto-update?

> I believe it's effectively misinformation from builders docs and good SEO for the name "electron builder" that results in people using it.

Having tried both, `electron-builder` gets the job done and that's why it's successful. `electron-forge` not so much. Harder to get started, lots of little stumbling blocks, not easy to find real sample apps on GitHub using it successfully, seems to be a moving target. Maybe it would go a long way taking a complex `electron-builder` project and converting it to `electron-forge` as it's often details that get in the way.

Hence the question if there are such an app repo out there?

> For now though, just know that all electron designed and built tooling isn't locking you into to using the rest of it. I.e. @electron/universal just takes in two paths and returns a promise, super simple and easy to compose into any build system.

Understood, before digging into that I'm trying to understand if anything can be done to avoid reinventing the wheel to have the library that is broadly used by the community trying to catch up with the library that is officially supported.

**Comment by andy-asana** [comment]
Hello! I tried to merge my x64 and arm64 apps but I'm running into this error: 

```
Error: Expected all non-binary files to have identical SHAs when creating a universal build but "Contents/CodeResources" did not
    at Object.exports.makeUniversalApp (node_modules/@electron/universal/src/index.ts:110:15)
```

I first built the `x64` and `arm64` `.dmg` files using `electron-forge make`, then double-clicked them to get the `.apps` files to input into `electron/universal`.

Is that the correct way to do this?

**Comment by sherlock1982** [comment]
`electron-forge` in the first place packages your app to `out/something.app` folder. 

Theoretically you don't have to make `.dmg` and `.zip` for both platforms. But you need to package the app twice, join with `electron/universal` and then run `electron-forge` to create `.dmg` and `.zip` from the joined folder. 

Though configuration will be quite sophisticated and i guess you will have to create two electron-forge configurations.

**Comment by timeowilliams** [comment]
If using electron-forge, you can run this command:

```bash

npm run make -- --arch=universal --platform=mas

```
