### ISSUE TITLE
Menubar not clickable on Electron 12

### ISSUE THREAD

**Issue by coolsurfer** [electron/electron#26717]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 12.0.0-beta.1 to 12.0.0-beta.6
* **Operating System:**
  * Windows 10 (2004) 
* **Last Known Working Electron version:**
  * 11.x.x (all of them)

### Expected Behavior
Click on Menu Item opens the submenu of this item

### Actual Behavior
Clicking on menu set with Menu.setApplicationMenu(Menu.buildFromTemplate(topLevelItems)); is not possible. Pressing "ALT" Highlights the menu but nothing more happens

### To Reproduce
Build Application with menu

**Comment by ckerr** [comment]
Hey @coolsurfer, thanks for reporting this!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by coolsurfer** [comment]
This is as easy as it can be :-) // works in electron 11, but not in electron 12

`
const {app, BrowserWindow, Menu} = require('electron');

let mainWindow;

app.on('ready', () => {
    mainWindow = new BrowserWindow();
    mainWindow.loadURL('https://www.google.de');

    createMenu();
});

function createMenu() {
    const topLevelItems = [
        {
            label: 'Application',
            submenu: [
                {
                    label: 'Load Other Site',
                    accelerator: 'F1',
                    click() {
                        mainWindow.loadURL('https://www.spiegel.de');
                    }
                }
            ]
        }
    ];

    Menu.setApplicationMenu(Menu.buildFromTemplate(topLevelItems));
    mainWindow.setMenuBarVisibility(true);
}
`
