### ISSUE TITLE
opening developer tools first time messes with background color

### ISSUE THREAD

**Issue by yilmazdurmaz** [electron/electron#26724]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  
  * v11.0.0-beta.20, v11.0.2, v11.0.3 and v12.0.0-beta.3
* **Operating System:**
   
  *  Windows 10 (1909)
* **Last Known Working Electron version:**
   
   * haven't tried below v11.0.0-beta.20, but I have VS-Code 1.47.1 that uses an old v7.3.2 that doesn't seem to have this problem
### Expected Behavior

Opening developer tools should not break the look of the page other than resizing mechanism if responsive

### Actual Behavior

Opening developer tools the first time an app starts breaks the background color,  to dark grey as menu bar and dev tools have. this happens only the first time and closing dev tools then reopening wont have the same effect.

### To Reproduce

clone, install, run "https://github.com/electron/electron-quick-start" , then open developer tools.

### Additional Information

I noticed this first when using Fiddle and even posted in its issues https://github.com/electron/fiddle/issues/536 .  Then tried it with electron-quick-start as suggested there to see the problem actually is with electron itself.

**Comment by AqilCont** [comment]
This happens with my app too...

**Before opening devtools(It's a base starter app):**
![image](https://user-images.githubusercontent.com/32044067/100487924-21522480-30d9-11eb-835d-66b6b75946f1.png)

**After opening devtools(as the author said, it only happens in the first time opening it):**
![image](https://user-images.githubusercontent.com/32044067/100487947-3e86f300-30d9-11eb-94a9-abcc5fe1b81c.png)

**Comment by MarshallOfSound** [comment]
The default background color of the `webContents` is "transparent".  Please specify a `backgroundColor` when constructing your window to ensure the background isn't affected like this

**Comment by yilmazdurmaz** [comment]
@MarshallOfSound 
honestly I am amazed how you see a workaround to be a solution and close the issue.
