### ISSUE TITLE
Draggable region behavior varies between two Windows 7 machines (Virtual machine versus physical)

### ISSUE THREAD

**Issue by Slapbox** [electron/electron#26725]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 8.5.3
* **Operating System:** Windows 7 & Windows 10
* **Last Known Working Electron version:** Unknown

**More specifically:**
| Machine |Status |
|---|---|
|Physical Windows 7 machine| Works
| Physical Windows 10 machine | TBD
| Windows 7 VMware machine | Bugged
| Windows 10 VMware machine | Bugged

### Expected Behavior
Draggable region behavior should be uniform no matter what machine the code runs on.

### Actual Behavior
Scrolling a list so that its contents appear beneath the drag region leads to a third element that is beneath both of the others becoming the element that receives mouse events.

You can see in this video that the first context menu clicks occur on a draggable region, but after scrolling the clicks go straight through it.

https://recordit.co/THHvufn6MY

The behavior is the same whether the application is running in development or from a packaged built with Electron-Builder.

### To Reproduce
Wish I knew. Any ideas about the cause? I'd be happy to investigate further but could use some insight into what might be going on behind the scenes.

### Additional Information
I'm pretty familiar with the quirks and limitations of drag regions and I feel pretty confident that this weird click-through behavior is not intended - although I can't know what I don't know.

I haven't encountered any other discrepancies in behavior like this between physical and virtual machines, which makes me think the fact it's a VM isn't likely to be the cause.

**Comment by Slapbox** [comment]
Also, I just remembered that the underlying `contentEditable` that the mouse events go through to is itself supposed to be a drag region. The property is set, but has no effect in this particular scenario.

**Comment by Slapbox** [comment]
Actually, I guess no matter where I set the style to be draggable, no matter how high in the hierarchy, I continue to see the issue. Maybe an issue with the calculations of the drag region coordinates? I'm not sure what's going on behind the scenes there besides what I've gleaned from some posts from @MarshallOfSound.

**Comment by Slapbox** [comment]
After further testing, this does appear to be a virtual machine specific issue that occurs on Windows and macOS (which is not an officially supported OS in VMware Workstate 14.1.2.) I haven't been able to test Linux yet. 

**I was able to "fix" the problem with `app.disableHardwareAcceleration()`**

I'm going to leave this open so that the relevant members of the Electron team can determine whether this bug is worth investigating or addressing. If it's a VMware thing, probably not, but for all I know it might hint at some underlying issue in Electron.

**Comment by Slapbox** [comment]
Actually, the issue has mysteriously come back and is not remedied by `app.disableHardwareAcceleration()` anymore. Strangest thing...

**Comment by ckerr** [comment]
Hey @Slapbox, thank you for reaching out and reporting this!

Electron 8.5.3 has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/tutorial/support#supported-versions). Do you still experience this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron?

**Comment by Slapbox** [comment]
Hey @ckerr thanks for your reply. It will be a few weeks before I'm able to give that a test, but my suspicion is that the issue remains.

I have found, at least part of, the cause - using `contain: layout` or `contain: paint` on the non-draggable area that underlays a drag region leads to the drag region becoming undraggable.

Does this sound like intentional behavior? If so, perhaps the documentation would benefit from some mention of this. If not, I'll try to reproduce this on a supported version of Electron when I have a chance.
