### ISSUE TITLE
macOS: `logname` can be incorrect depending on how one launches an electron app

### ISSUE THREAD

**Issue by bramus** [electron/electron#26721]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * Electron: 9.3.3
* **Operating System:**
  * macOS 11.0.1 (but also happened on 10.15)
* **Last Known Working Electron version:**
  * Unknown

### Bug Description

I'm hopping over from over from [this VSCode issue](https://github.com/microsoft/vscode/issues/96463) where I've noticed this behavior:

> Depending on how you launched VSCode, the output of `logname` in the built-in terminal will be different:
> 1. VSCode is launched from the CLI (using `code`): `logname` will yield your username (cfr. `whoami`).
> 1. VSCode is launched from the macOS Dock / Spotlight / Finder: `logname` will yield `root`.

I've come to know that [Vercel's Hyper also behaves like this](https://github.com/vercel/hyper/issues/3762).

Since both apps use Electron under the hood, I'm thinking this is a Electron issue …

### To Reproduce / Actual Behavior

1. Build an Electron app that features a Terminal (😅)
1. Place this script on disk somewhere
    ```
    echo "\$USER: $USER"
    echo "logname: $(logname)"
    echo "whoami: $(whoami)"
    ```
1. Launch your app from (1) from the CLI, to see the correct behavior:
    ```
    $USER: bramus
    logname: bramus
    whoami: bramus
    ```
1. Launch your app from (1) from the macOS Dock / Spotlight / Finder, to see the wrong behavior:
    ```
    $USER: bramus
    logname: root
    whoami: bramus
    ```

### Expected Behavior 

I expect the output for `logname` to yield the same output as `$USER` and `whoami`, independent of how I launched my Electron based app.

### Additional Information

- VSCode Issue: https://github.com/microsoft/vscode/issues/96463
- Hyper Issue: https://github.com/vercel/hyper/issues/3762

**Comment by MarshallOfSound** [comment]
This is not an electron issues, this is fundamentally how Cocoa apps works, you can check by making a simple swift app that just exec's `logname` and comparing.  Whether it's a bug in Cocoa / macOS is up to your interpretation, but it's definitely not an Electron specific issue 😄
