### ISSUE TITLE
system-context-menu prevents the default behavior from being invalid

### ISSUE THREAD

**Issue by Linkontoask** [electron/electron#26726]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.0.3
* **Operating System:**
  * Windows 10 (1803)
* **Last Known Working Electron version:**
  * 

### Expected Behavior
Prevent the default menu context from being displayed

### Actual Behavior

![image](https://user-images.githubusercontent.com/26475695/100495655-9466a400-3188-11eb-919b-c525e543630b.png)

### To Reproduce

+ Set frame to true
+ Set `-webkit-app-region: drag`
+ Finally write the following code
```
win.on('system-context-menu', e => {
    e.preventDefault()
})
```

### Screenshots

![image](https://user-images.githubusercontent.com/26475695/100495655-9466a400-3188-11eb-919b-c525e543630b.png)

**Comment by MarshallOfSound** [comment]
> To Reproduce

Can you provide complete repro steps, the current steps won't open that menu so it's unclear how you're opening it.

**Comment by Linkontoask** [comment]
Reproduce the warehouse
https://github.com/Linkontoask/electron-system-context-menu

**Comment by ckerr** [comment]
Gist copy @ https://gist.github.com/ckerr/3116ae2362ef785c99e6909579f9e07e

**Comment by ckerr** [comment]
The Electron code that delegates to NativeWindowObserver looks fine, but for some reason  NativeWindowViews::PreHandleMSG isn't getting any WM_CONTEXTMENU messages, so that event handler + delegation code is never being reached

**Comment by ckerr** [comment]
`frame: false` is a prerequisite for triggering this bug.

Electron never sees the WM_CONTEXTMENU message because hwnd_message_handler.cc uses its own custom event handling for WM_RBUTTONUP [here](https://source.chromium.org/chromium/chromium/src/+/master:ui/views/win/hwnd_message_handler.cc;l=3038;drc=db9ae7941adc1d95c943accce9e0151d265fd640). The invocation of SendMessage() in that paragraph returns HTCAPTION, so ShowSystemMenuAtScreenPixelLocation() is called.

That block of code is reached in the first place because is_right_mouse_pressed_on_caption_ is set to true [here](https://source.chromium.org/chromium/chromium/src/+/master:ui/views/win/hwnd_message_handler.cc;l=3078;drc=db9ae7941adc1d95c943accce9e0151d265fd640).

**Comment by fabiospampinato** [comment]
The "system-context-menu" event is never triggered for me under Electron 11.0.3 and Windows 10, I'm using `frame: false`.

**Comment by ericblade** [comment]
frame false system-context-menu is not triggered in 12.0.0, either, when right clicking on the draggable region, opposed to the documentation on the pull request for the feature.  

I cannot speak for any other configurations at this time.

**Comment by fabiospampinato** [comment]
"system-context-menu" is still broken for me under Electron v12.

**Comment by grunde** [comment]
Still reproduces in v13.

**Comment by liuyike98** [comment]
still reproduces , 2021.12.03!!!

**Comment by Poosicle** [comment]
this jawn still broken idk what day it is

**Comment by developerhb** [comment]
Using Electron 16.0.4. This issue still persists. With `frame: false` the `system-context-menu` event is not triggered.

**Comment by Mosquito13** [comment]
> Using Electron 16.0.4. This issue still persists. With `frame: false` the `system-context-menu` event is not triggered.

Same here.

**Comment by Seraphli** [comment]
> Using Electron 16.0.4. This issue still persists. With `frame: false` the `system-context-menu` event is not triggered.

Same here.

**Comment by Joursion** [comment]
any fix ? 

and i find a sideway , it works for me (just works and i didn't know why )

```
const WM_INITMENU = 0x0116;
win.hookWindowMessage(WM_INITMENU, () => {
    win.setEnabled(false);
    win.setEnabled(true);
});
```
refers:  `https://github.com/electron/electron/issues/24893#issuecomment-1109262719`

**Comment by fabiospampinato** [comment]
I think a proper solution to this should still be provided.

**Comment by fabiospampinato** [comment]
Still interested in this

**Comment by ferreira-tb** [comment]
Still persists in 23.1.4 when `frame: false`.

**Comment by stalker8610** [comment]
Still interested in this

**Comment by yangsen9608** [comment]
> any fix ?
> 
> and i find a sideway , it works for me (just works and i didn't know why )
> 
> ```
> const WM_INITMENU = 0x0116;
> win.hookWindowMessage(WM_INITMENU, () => {
>     win.setEnabled(false);
>     win.setEnabled(true);
> });
> ```
> 
> refers: `https://github.com/electron/electron/issues/24893#issuecomment-1109262719`

This setting masks the system menu, but the custom right-click menu is also masked. Is there a way to block only Windows system menu operations because I want to customize the right-click menu

**Comment by wheezard** [comment]
@yangsen9608, you're supposed to add the custom menu popup code inside the event handler, after the `win.setEnabled(true);` line. This works for me on the latest Electron version.

**Comment by yangsen9608** [comment]
> 
Thank you for your help, I have completed the effect I want, thank you!

**Comment by aronCiucu** [comment]
Bump

**Comment by pagoru** [comment]
Fix this

**Comment by Vaneeyo** [comment]
Bump

**Comment by boiboif** [comment]
Bump

**Comment by eXhumer** [comment]
> `frame: false` is a prerequisite for triggering this bug.
> 
> Electron never sees the WM_CONTEXTMENU message because hwnd_message_handler.cc uses its own custom event handling for WM_RBUTTONUP [here](https://source.chromium.org/chromium/chromium/src/+/master:ui/views/win/hwnd_message_handler.cc;l=3038;drc=db9ae7941adc1d95c943accce9e0151d265fd640). The invocation of SendMessage() in that paragraph returns HTCAPTION, so ShowSystemMenuAtScreenPixelLocation() is called.
> 
> That block of code is reached in the first place because is_right_mouse_pressed_on_caption_ is set to true [here](https://source.chromium.org/chromium/chromium/src/+/master:ui/views/win/hwnd_message_handler.cc;l=3078;drc=db9ae7941adc1d95c943accce9e0151d265fd640).

Can't the `NativeWindowViews::PreHandleMSG` not be used to intercept this behaviour for `WM_RBUTTONUP` message and check if the current view is frameless and considering that as a system context menu message? This comment seems to indicate this method is called before HWNDMessageHandler to trying to handle messages.

https://github.com/electron/electron/blob/c670e38b4b14d0286e0ae04cb7f63987beb5e044/shell/browser/native_window_views.h#L153-L158

I don't have access to any Windows machine to test this on, but I would appreciate if someone who can build Electron on Windows can add this switch case inside [`NativeWindowViews::PreHandleMSG`](https://github.com/electron/electron/blob/c670e38b4b14d0286e0ae04cb7f63987beb5e044/shell/browser/native_window_views_win.cc#L237-L435) and trying checking if you can `console.log` inside the [`system-context-menu`](https://www.electronjs.org/docs/latest/api/browser-window#event-system-context-menu-windows) event.

```cpp
    case WM_RBUTTONUP: {
      if (!has_frame()) {
        bool prevent_default = false;
        NotifyWindowSystemContextMenu(GET_X_LPARAM(l_param),
                                      GET_Y_LPARAM(l_param), &prevent_default);
        return prevent_default;
      }
      return false;
    }
```

**Comment by xXTurnerLP** [comment]
v31.1.0
i have the issue as well
