### ISSUE TITLE
[RFC] context bridge terminology

### ISSUE THREAD

**Issue by bennymeg** [electron/electron#26728]
I would like to propose a new terminology for the context bridge [docs](https://github.com/electron/electron/blob/master/docs/api/context-bridge.md):

- Replace `world` with `context` and `main` with `renderer`:
   I do not the the the words 'world' and 'main' are descriptive enough for that matter.
   - Isolated World => Isolated Context
   - Main World => Renderer Context

- Replace `exposeInMainWorld()` to `expose()`:
   I think that in that case the long function name is redundant and little confusing. 

What so you think?

**Comment by nornagon** [comment]
While I agree with you that these terms are confusing, they are consistent with other code and documentation discussing the same concepts (e.g. https://developer.chrome.com/extensions/content_scripts#isolated_world). IMO using a different term than others in the industry for the same concept has the potential to be _more_ confusing.

Further, I'm against changing the name of an API for aesthetic reasons. Changing the name of an API requires apps to change their source code to update. In general we prefer to avoid breaking changes wherever possible, and only introduce such changes with good reason. I don't feel that a terminology change is a good enough reason to break an app.

**Comment by bennymeg** [comment]
I was not aware that this is how google describes these contexts regions.
Thank you for clarifying that.
