### ISSUE TITLE
webContents.history is undefined

### ISSUE THREAD

**Issue by iwiedenm** [electron/electron#26727]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.0.3
* **Operating System:**
  * macOS, Windows
* **Last Known Working Electron version:**
  * 10.x.x

### Expected Behavior
The history property of a webContents should be an array of the history.

### Actual Behavior
The history property of a webContents is now `undefined`. Is this intended?

### To Reproduce
Just do `wc.history` where `wc` is any webcontents.

**Comment by MarshallOfSound** [comment]
`webContents` doesn't have a documented `history` property? If it ever existed it was an implementation side-effect and not an actual API / feature.

Docs: https://www.electronjs.org/docs/api/web-contents
