### ISSUE TITLE
Rebuilding Native Apps with Node v15.0.1

### ISSUE THREAD

**Issue by kzaiwo** [electron/electron#26734]
How can I rebuild native modules for Electron when using Node v15.0.1?

I am always getting the node version mismatch error when rebuilding native libraries.
However, when I checked the Electron version compatible with Node v15.0.1, I can't seem to find any.

**So from NodeJS (https://nodejs.org/en/download/releases/):**

Version | LTS | Date | V8 | npm | NODE_MODULE_VERSION[1]
Node.js 15.0.1 |   | 2020-10-21 | 8.6.395.17 | 7.0.3 | **88** | Downloads Changelog Docs

So the ABM version is "**88**"

**Then from https://github.com/electron/releases:**

Tag	Published	npm	Prerelease	Module Version	Node	Chrome	Downloads
v13.0.0-nightly.20201127	2020-11-27	nightly	yes	**89**	14.15.1	89.0.4328.0	73
v13.0.0-nightly.20201126	2020-11-26		yes	**89**	14.15.1	89.0.4328.0	98
v13.0.0-nightly.20201124	2020-11-24		yes	**89**	14.15.1	89.0.4328.0	124
v13.0.0-nightly.20201123	2020-11-23		yes	**87**	14.15.1	89.0.4328.0	99
v13.0.0-nightly.20201119	2020-11-19		yes	**87**	14.15.1	89.0.4328.0	177
v12.0.0-nightly.20201116	2020-11-17		yes	**87**	14.15.0	88.0.4324.0	126
v12.0.0-nightly.20201112	2020-11-12		yes	**87**	14.15.0	88.0.4306.0	271
v12.0.0-nightly.20201111	2020-11-11		yes	**87**	14.15.0	88.0.4306.0	109
v12.0.0-nightly.20201106	2020-11-06		yes	**87**	14.15.0	88.0.4306.0	233
v12.0.0-nightly.20201105	2020-11-05		yes	**87**	14.15.0	88.0.4306.0	101
v12.0.0-nightly.20201104	2020-11-04		yes	**87**	14.15.0	88.0.4306.0	116
v12.0.0-nightly.20201103	2020-11-03		yes	**87**	14.15.0	88.0.4306.0	104
v12.0.0-nightly.20201102	2020-11-02		yes	**87**	14.15.0	88.0.4306.0	116
v12.0.0-nightly.20201030	2020-10-30		yes	**87**	14.15.0	88.0.4306.0	150
v12.0.0-nightly.20201026	2020-10-26		yes	**87**	14.14.0	88.0.4292.0	360
v12.0.0-nightly.20201023	2020-10-23		yes	**87**	14.14.0	88.0.4292.0	229
v12.0.0-nightly.20201015	2020-10-15		yes	**87**	14.13.1	87.0.4268.0	371
v12.0.0-nightly.20201014	2020-10-14		yes	**87**	14.13.1	87.0.4268.0	187
v12.0.0-nightly.20201013	2020-10-13		yes	**87**	14.13.1	87.0.4268.0	193
v12.0.0-nightly.20200914	2020-09-14		yes	**82**	12.18.3	86.0.4234.0	953
v12.0.0-nightly.20200911	2020-09-11		yes	**82**	12.18.3	86.0.4234.0	92
v12.0.0-nightly.20200910	2020-09-10		yes	**82**	12.18.3	86.0.4234.0	205
v12.0.0-nightly.20200907	2020-09-07		yes	**82**	12.18.3	86.0.4234.0	99
v12.0.0-nightly.20200903	2020-09-03		yes	**82**	12.18.3	86.0.4234.0	335
v12.0.0-nightly.20200902	2020-09-02		yes	**82**	12.18.3	86.0.4234.0	110
v12.0.0-nightly.20200831	2020-08-31		yes	**82**	12.18.3	86.0.4234.0	138
v12.0.0-nightly.20200827	2020-08-27		yes	**82**	12.18.3	86.0.4234.0	182
v12.0.0-beta.4	2020-11-26	beta, beta-12-x-y	yes	**87**	14.15.1	89.0.4328.0	727
v12.0.0-beta.3	2020-11-23		yes	**87**	14.15.1	89.0.4328.0	1039
v12.0.0-beta.1	2020-11-19		yes	**87**	14.15.1	89.0.4328.0	1014
v11.0.3	2020-11-24	latest, 11-x-y	no	**85**	12.18.3	87.0.4280.67	15822

**There is nothing that matches ABM version 88.**

I am not allowed to update the NodeJS version since it is restricted by our system admin. No choice but to use v15.0.1. 

Help!

**Comment by MarshallOfSound** [comment]
The `NODE_MODULE_VERSION` that Electron uses is completely separate from Node's.  Please use [`electron-rebuild`](https://github.com/electron/electron-rebuild) to rebuild things
