### ISSUE TITLE
ClientRequest get complete response data issue

### ISSUE THREAD

**Issue by cool-firer** [electron/electron#26756]
`data` event triggered multi times  when having many data, but `end` event not triggered.  event  trigger sequence is this:
```
data event multi times -> end event;
data event multi times -> no end event;
data event one time -> no end event;
```
Is this situation normal ?

Tried `close` event、`finish` event, none of them effect,  How can I get the complete data? 

My code is this:
```
function requestData() {
  const requestUrl = remote.getGlobal('REQ_URL');
  const request = net.request(requestUrl);
  request.on('response', (response) => {
    console.log(`STATUS: ${response.statusCode}`)
    console.log(`HEADERS: ${JSON.stringify(response.headers)}`)
    let datas = '';
    response.on('data', (chunk) => {
      console.log(`BODY: ${chunk}`);
      datas += chunk;
      try {
        const jsonArr = JSON.parse(chunk);
        // to do with jsonArr
        // ....
      } catch(e) {
        console.log(e);
      }
    });

    response.on('end', () => {
      console.log('No more data in response.')
    });

    response.on('close', () => {
      console.log('close');
    });

    response.on('finish', () => {
      console.log('finish');
    });
  });

  request.end();
}
```

**Comment by nornagon** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
