### ISSUE TITLE
Destroying BrowserView produces error telling you that it's already destroyed

### ISSUE THREAD

**Issue by James-Livesey** [electron/electron#26763]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 11.0.3
  
* **Operating System:** Google Chrome OS 86.0.4240.198 (Official Build) (64-bit), with Crostini Linux (Beta) container running Debian GNU/Linux 10 (Buster)
  
* **Last Known Working Electron version:** 8.2.4
  

### Expected Behavior

The following code should run without errors:
```javascript
var embed = new BrowserView({ /* ... */ });
// Later on in the code
console.log(embed.webContents.isDestroyed()); // -> false
embed.webContents.destroy(); // Error is thrown here but it shouldn't be
```

### Actual Behavior

The following error is thrown:
```
Uncaught Error: Could not call remote method 'destroy'. Check that the method signature is correct. Underlying error: Object has been destroyed
Underlying stack: TypeError: Object has been destroyed
    at getOwnerKey (electron/js2c/browser_init.js:209:191)
    at ObjectsRegistry.clear (electron/js2c/browser_init.js:209:735)
    at Object.listener (electron/js2c/browser_init.js:209:1285)
    at Object.emit (events.js:315:20)
    at electron/js2c/browser_init.js:213:8529
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:213:4964)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:157:9393)
    at Object.emit (events.js:315:20)

    at electron/js2c/browser_init.js:213:8557
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:213:4964)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:157:9393)
    at Object.emit (events.js:315:20)
```

The `BrowserView` object is clearly visible before the `.destroy()` method is called. The functionality of the method still works, and so a workaround is to wrap the `.destroy()` method in a `try` and empty `catch` block.

### To Reproduce

Please refer to the code written above.

### Screenshots

![Textual screenshot of error copied above.](https://i.ibb.co/mHghjT1/Screenshot-2020-12-01-at-17-15-11.png)

### Additional Information

It _could_ be the case that another script (that uses IPC communication) is throwing this error, however I doubt it since there doesn't appear to be any references to `BrowserView` instances in my code (or not at least directly, anyway). The error doesn't give me a traceback far enough to reference my own code (it seems to only reference internal Electron code).

**Comment by ckerr** [comment]
Hey @James-Livesey, thanks for reaching out and reporting this.

I tried making a quick testcase from your sample code at https://gist.github.com/ckerr/59c54de15f4616c6e3852566d1ced1a9. Perhaps it lost something in translation, but I'm not able to reproduce the issue with this testcase using Electron 11.0.3 on Ubuntu 20.10.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Thanks in advance! Your help is appreciated.

**Comment by James-Livesey** [comment]
Hi! Thanks for writing a fiddle. I think the example code I gave wasn't too clear, but it looks like your fiddle code is a good representation of what I meant when writing the example code. I'll quickly download and run the fiddle that you wrote onto my Chromebook to see if the issue persists.

Again, it might just be the case that it's just an internal error with my project code. Just a bit of a shame that the traceback couldn't tell me where the `BrowserView` was being referenced at the time of error!

**Comment by James-Livesey** [comment]
Doesn't seem to reproduce in the fiddle on my system, but the code is indeed representative of what seemed to be the bug. I think it's best to close this issue as I think it's probably an error on my part to be honest! If anybody else has the same issue on a much smaller scale than my own project, then they can comment on this issue for it to be reopened.

**Comment by quanglam2807** [comment]
`BrowserView.destroy()` API has been removed with this PR: https://github.com/electron/electron/pull/23578
