### ISSUE TITLE
Electron dev-tools not working on Raspberry PI & Ubuntu 20.04

### ISSUE THREAD

**Issue by fbstj** [electron/electron#26760]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Versions:** 
  * node 10.x (from Ubuntu) & electron 7.3.3
  * node 10.x (from Ubuntu) & electron 11.0.3
  * node 14.15.1 (from nodesource) & electron 11.0.3
* **Operating System:**
  * Ubuntu 20.04 armhf (Raspbery Pi 4)
* **Last Known Working Electron version:** unknown

### Expected Behavior
opening the dev-tools with the key combo or from the menu shows the dev-tools

### Actual Behavior
`../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0403`

### To Reproduce
my project has the following in the `package.json`:

```
  "scripts": {
    "start": "electron .",
    "install": "electron-rebuild"
  },
  "devDependencies": {
    "electron": "11.x",
    "electron-rebuild": "2.x"
  },
  "dependencies": {
    "serialport": "9.x",
    "simple-git": "2.x",
    "spi-device": "3.x"
  }
```

when running normally (from `.dekstop` icons, or with `npm start` in the directory) my applications all operate successfully, talk over the serial port, perform SPI communications and use the git library successfully. I can show/hide the menu with ALT and can use most of the menu functionality (mainly fullscreen toggling) but asking for dev tools results in the above syscall failure appearing in the terminal. it does not otherwise affect operation of my applications.

when running `./node_modules/.bin/electron` the default window fails to open and the app shows the above warning after the usage message is shown

**Comment by deepak1556** [comment]
This is fixed by https://chromium-review.googlesource.com/c/chromium/src/+/2785131 , electron >= 13 should work. Please give it a try, thanks!

**Comment by prasnala** [comment]
in package.json, their are two electron in dependecies and dev dependencies. I remove electron from dependecies and keep in dev depenecies. and it works
