### ISSUE TITLE
<webview webpreferences="contextIsolation=true"> incorrectly warns “The default of contextIsolation is deprecated”

### ISSUE THREAD

**Issue by andersk** [electron/electron#26785]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.0.3
  * 11.3.0
* **Operating System:**
  * NixOS 21.03 x86_64
* **Last Known Working Electron version:**
  * 10.1.6

### Expected Behavior

`<webview webpreferences="contextIsolation=true">` should not warn that the `contextIsolation` default is deprecated, since I’m not relying on the default (as verified by the `will-attach-webview` event).

### Actual Behavior

`(node:30472) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information`

### To Reproduce

Electron Fiddle: https://gist.github.com/f801279c49c96bed5636fa9196350d64

### Additional Information

General issue for `contextIsolation` default deprecation: #23506.

**Comment by MarshallOfSound** [comment]
This was fixed at one point recently, I just can't find the PR, tested on `main`
