### ISSUE TITLE
"Click to load more messages" messages not loading bug

### ISSUE THREAD

**Issue by Patrickmorris123Productions** [electron/electron#26786]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
unk
* **Operating System:**
  * 
W10 20H2
* **Last Known Working Electron version:**
  * 
unk
### Expected Behavior

Messages load
### Actual Behavior

Messages not loading
### Screenshots

![image](https://user-images.githubusercontent.com/59210526/100815626-65636300-3412-11eb-93c9-319c7a185dd5.png)

### Additional Information

It wont do anything but load the message above

**Comment by codebytere** [comment]
This is a bug with Discord and should be filed with them appropriately.
