### ISSUE TITLE
window.location.reload and many other electron BrowserWindow functions broken

### ISSUE THREAD

**Issue by Yuri6037** [electron/electron#26798]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 10.1.0
  * 
* **Operating System:** Pop! OS 20.10
  * 
* **Last Known Working Electron version:** None
  * 

### Expected Behavior

The functions should be working

### Actual Behavior

When setMenu(null) has been called most functions of BrowserWindow and window contents becomes useless and have absolutely no effect at all!
Current list of impacted functions:
- window.location.reload
- remote.getCurrentWebContents().toggleDevTools()
- remote.getCurrentWebContents().openDevTools()
- remote.getCurrentWebContents().closeDevTools()

### To Reproduce
Just call window.setMenu(null) in the Main process main.ts/js, this will elliminate the menu bar like in old WinXP-.
Then add bootstrap rendered buttons and enjoy not working functions. For the remote based functions put them in preload.ts/js then expose them to the rendering context and same deal call the exposed functions from bootstrap enjoy no effect!

EDIT: After some more research you need to have a global mouse event, a local mouse event and reactjs setState.
With all these conditions reunited you have a random chance that the global mouse click handler breaks the local mouse click handler and will cause the local mouse click (also the reload button) to never get called. Even weirder this bug does not appear without setMenu.
As a workarround `document.elementFromPoint` can be used.

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
