### ISSUE TITLE
App crash/BrowserWindow not shown, can't reach dom-ready event

### ISSUE THREAD

**Issue by Lemao81** [electron/electron#26801]
### Issue Details

* Electron Version: 11.0.3
* Operating System: WindowsServer 2012 R2

### Expected Behavior
Application start

### Actual Behavior
Browserwindow does not appear although 4 electron processes keep running in the background. Problem seems to be in the renderer process, happens when executing BrowserWindow.loadFile(). Last recevied event logs are:
WEBCONTENTS - did-start-loading
WEBCONTENTS - did-start-navigation
WEBCONTENTS - did-navigate

Then it completely aborts, a logging right after calling the loadFile method is not executed anymore. Event 'render-process-gone' is registered as well, but seems not to be triggered. In another WindowServer 2012 system (setup as VM) it's working, the following event 'dom-ready' is logged and should follow.
After a period of time a windows error message pop's up -> Event log: 

Faulting application name: xxx.exe, version: xxx, time stamp: 0x5e851aee
Faulting module name: ntdll.dll, version: 6.3.9600.19678, time stamp: 0x5e82c88a
Exception code: 0xc0000005
Fault offset: 0x0000000000030837
Faulting process id: 0x1328
Faulting application start time: 0x01d6c6f79ac95ba4
Faulting application path: C:\Program Files\xxx\xxx.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: df851e05-32ea-11eb-8114-cd109560b927
Faulting package full name: 
Faulting package-relative application ID: 

### Additional Information
The server is accessed and application started by RDP/Citrix (multiple RDP sessions enabled). EV-code signing of the app has not happened yet, but SmartScreen is disabled. The Browserwindow is created with following code:

```
new BrowserWindow({
    width,
    height,
    webPreferences: {
      nodeIntegration: true,
      enableRemoteModule: true,
      allowRunningInsecureContent: false,
      devTools: true,
      webSecurity: false,
      preload: join(__dirname, 'preload.js')
    },
    useContentSize: true,
    frame: false,
    show: false,
    backgroundColor: '#00aec2'
  });
```

**Comment by VerteDinde** [comment]
Hey @Lemao81, thanks for reporting this and helping to make Electron better! I wasn't able to reproduce your issue in Electron Fiddle with just the BrowserWindow code you provided - would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, Electron Fiddle is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/needs-repro label for this reason. After you make a test case, please link to it in a follow up comment. Thanks!

**Comment by Lemao81** [comment]
I could deliver a trimmed version of my main.js (needed to be transferred from TS to JS first), but it most likely will work totally fine on your side as on all of our various machines except the one on customer side, is nothing special that I'm doing there, creating a window and spinning up a web project created by angular with window.loadFile(index.html). Seems to be related to a feature of that respective system. Was more hoping for hints what it COULD be related to and recommendations what should be further examined regarding the step where it stops to work as expected.

**Comment by Lemao81** [comment]
Problem could be solved by building the executable with win32 instead of win64 option

**Comment by muhammetalay** [comment]
@Lemao81 hey hey, we seem to be experiencing a similar problem with couple of our users. Did this issue happen when your users tried to use 64bit app on a 32bit PC? 

If you have time, can you elaborate what this mean a bit more?

>Problem could be solved by building the executable with win32 instead of win64 option

Thank you

**Comment by Lemao81** [comment]
The server itself was a 64bit machine but anything about the Citrix environment/setup seemed to be tied to 32bit, judged by dll names etc. We did not really investigated any further after realizing that the 32bit build worked perfectly fine
