### ISSUE TITLE
When I use worker_threads in the main process of Electron, an error will be reported

### ISSUE THREAD

**Issue by 1111mp** [electron/electron#26816]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.4.1
* **Operating System:**
  * Windows 10 
* **Last Known Working Electron version:**
  * n/a

### Expected Behavior
Register some events with ipcMain through worker_threads
```
const { Worker } = require('worker_threads');
  const workerFile =
    process.env.NODE_ENV === 'production'
      ? 'worker.js'
      : path.resolve(__dirname, 'worker.js');

  const worker = new Worker(path.resolve(__dirname, workerFile));

  worker.on('close', (exitcode: any) => {
    /* ... */
    console.log('exitcode:', exitcode);
  });
```
worker.js:
```
const { ipcMain } = require('electron');
ipcMain.on('asynchronous-message', (event, arg) => {
  console.log(arg); // prints "ping"
  event.reply('asynchronous-reply', 'pong');
});

```

### Actual Behavior
An error is reported when executing the on method of ipcMain
![image](https://user-images.githubusercontent.com/31227919/100992989-ca909300-358f-11eb-9222-3d7ccc9e0feb.png)

### To Reproduce
main.ts：
```
const { Worker } = require('worker_threads');
  const workerFile =
    process.env.NODE_ENV === 'production'
      ? 'worker.js'
      : path.resolve(__dirname, 'worker.js');

  const worker = new Worker(path.resolve(__dirname, workerFile));

  worker.on('close', (exitcode: any) => {
    /* ... */
    console.log('exitcode:', exitcode);
  });
```
worker.js:
```
const { ipcMain } = require('electron');
ipcMain.on('asynchronous-message', (event, arg) => {
  console.log(arg); // prints "ping"
  event.reply('asynchronous-reply', 'pong');
});

```

**Comment by ckerr** [comment]
Hi @1111mp, thanks for reaching out!

If I'm understanding your report correctly, what's happening is the worker is running in a thread inside the main process; thus, inter-process-communication to the main process does not make sense. https://medium.com/swlh/how-to-run-background-worker-processes-in-an-electron-app-e0dc310a93cc has a writeup that might be useful of one way to use Workers in the main process.

Also, you might want to check out [the new Electron Discord server](https://discord.com/invite/electron). It's a place for authors of Electron apps to share ideas, questions, and answers, and it might be useful for this!

**Comment by 1111mp** [comment]
@ckerr Thank you very much for your reply. It works for me.Thanks again.

**Comment by SC-FH** [comment]
How do I import the worker.js module that I cannot import using a worker thread
