### ISSUE TITLE
webContents.mainFrame can be undefined

### ISSUE THREAD

**Issue by nornagon** [electron/electron#26824]
### Issue Details

* **Electron Version:**
  * 13.0.0-nightly.20201203
* **Operating System:**
  * macOS
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
`WebFrameMain.frames` should never contain undefined

### Actual Behavior
```
Uncaught Exception:
TypeError: Cannot read property 'processId' of undefined
    at id (/private/var/folders/_7/jm5cr84j7jd4v7btf2d3bqwm0000gn/T/tmp-59557-p4DTr3KWOsNk/main.js:4:38)
    at pft (/private/var/folders/_7/jm5cr84j7jd4v7btf2d3bqwm0000gn/T/tmp-59557-p4DTr3KWOsNk/main.js:6:36)
    at Timeout._onTimeout (/private/var/folders/_7/jm5cr84j7jd4v7btf2d3bqwm0000gn/T/tmp-59557-p4DTr3KWOsNk/main.js:27:5)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

### To Reproduce
Run https://gist.github.com/f46823470955034b4a456b6275862bfb for a short while and you'll observe the above error.

cc @samuelmaddock

**Comment by nornagon** [comment]
@codebytere i'd be surprised if this was mac-specific.

**Comment by miniak** [comment]
@nornagon there is no way the code can return an `undefined` frame in the array
https://github.com/electron/electron/blob/9baca911a1d00a37a4b04415746b2b4e5525ba08/shell/browser/api/electron_api_web_frame_main.cc#L272-L284

it's actually the `webContents.mainFrame` property being `undefined`

**Comment by ckerr** [comment]
Testcase failed ~3 minutes in for me in v13.0.0-nightly.20201203 on Linux (since that's the day this was reported) and is still present in v13.0.0-nightly.20210127.

So, still present, and agreed with the discussion above that it's not specific to macOS.

**Comment by nornagon** [comment]
@miniak makes sense. should we just document this as possibly-undefined?

**Comment by samuelmaddock** [comment]
There's something wrong with the `WebFrameMain` destructor. Modifying @nornagon's fiddle to hold all frame references fixes the problem.
```diff
+const frameSet = new Set()

function id(frame) { return `${frame.processId}:${frame.routingId}` }
function pft(frame, indent = 0) {
+  frameSet.add(frame)
  console.log('-'.repeat(indent) + id(frame))
  for (const child of frame.frames) {
    pft(child, indent + 2)
  }
}
```

Is it possible that `g_render_frame_map.Get().erase(render_frame_);` actually deletes the render frame?
https://github.com/electron/electron/blob/72127b2916d450a7a734b348df00b4487d81f37e/shell/browser/api/electron_api_web_frame_main.cc#L55-L62

**Comment by nornagon** [comment]
> Is it possible that `g_render_frame_map.Get().erase(render_frame_);` actually deletes the render frame?

I don't think so, the values are just pointers, std::unordered_map doesn't do anything special with pointers on `erase`.

**Comment by samuelmaddock** [comment]
The cause seems to be that v8 handles for `WebFrameMain` are getting garbage collected too early. The first handle for a `WebFrameMain` instance needs to be pinned until the corresponding `RenderFrameHost` is deleted. I should have a PR up in the next couple days.
