### ISSUE TITLE
Running as root without --no-sandbox is not supported in Linux distribution ( CentOS Linux 7 (Core))

### ISSUE THREAD

**Issue by siva68533** [electron/electron#26828]
I tried yarn start as "electron . --no-sandbox" electron app is opened up. but installed rpm in Linux (centos) m/c and tried to launch installed electron APP, it was not opened up due to below error. 

 [12170:1204/064742.756272:FATAL:electron_main_delegate.cc(211)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
 kernel: traps:  APP [12170] trap int3 ip:55d6a90ddcd3 sp:7ffd7bbfaae0 error:0
 abrt-hook-ccpp: Process 12170 (APP) of user 0 killed by SIGTRAP - dumping core
 abrt-server: Package 'APP' isn't signed with proper key
 post-create' on '/var/spool/abrt/ccpp-2020-12-04-06:47:42-12170' exited with 1
 abrt-server: Deleting problem directory '/var/spool/abrt/ccpp-2020-12-04-06:47:42-12170'

Is there any way to run an electron app without passing --no-sandbox flag as a root mode?

The tried electron versions are 8.x, 10.x, and even the latest 11.0.3,  everywhere am getting same issue mentioned above.

**Comment by nornagon** [comment]
No. As the error message says, running as root without --no-sandbox is not supported.

This is inherited from Chromium and is not something we can change in Electron.

I recommend against running any Electron app as root.
