### ISSUE TITLE
【错误】使用npm install安装项目依赖electron@9.2.1出现TLS错误

### ISSUE THREAD

**Issue by mrluffya** [electron/electron#26827]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.2.1
  * 9.3.0
  * 9.3.5
  * 10
  * 11
* **Operating System:**
  * macOS 10.13.6 (High_Sierra)
* **Last Known Working Electron version:**
  * 暂未发现

### Expected Behavior

问题消失

### Actual Behavior

使用npm install安装项目依赖electron@9.2.1出现TLS错误。
~Client network socket disconnected before secure TLS connection was established.~

### To Reproduce
```sh
$ # 请参阅：Additional Information: *****nodejs-bigquery#624*****
$ git clone https://github.com/oldj/SwitchHosts
$ cd SwitchHosts
$ npm install
$ # 报错后尝试重新安装
$ npm cache clean -f && rm -rf -v node_modules
$ npm install electron@9.2.1
```
_例子@9.2.1（electron@9.2.1）：_
mrluffya ~/Documents/workspaces/git/20201201/SwitchHosts % npm i                  
......
.> electron@9.2.1 postinstall /Users/mrluffya/Documents/workspaces/git/20201201/SwitchHosts/node_modules/electron
.> node install.js

RequestError: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (/Users/mrluffya/Documents/workspaces/git/20201201/SwitchHosts/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/Users/mrluffya/Documents/workspaces/git/20201201/SwitchHosts/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
......

---

_例子@11（electron@11）：_
mrluffya ~/Documents/workspaces/git/20201201/SwitchHosts % npm i electron@11 
......
.> electron@11.0.3 postinstall /Users/mrluffya/Documents/workspaces/git/20201201/SwitchHosts/node_modules/electron
.> node install.js

Downloading electron-v11.0.3-darwin-x64.zip: [==========================] 100% ETA: 0.0 seconds
RequestError: Client network socket disconnected before secure TLS connection was established
    at ClientRequest.<anonymous> (/Users/mrluffya/Documents/workspaces/git/20201201/SwitchHosts/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/Users/mrluffya/Documents/workspaces/git/20201201/SwitchHosts/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm WARN eslint-config-standard@14.1.1 requires a peer of eslint-plugin-import@>=2.18.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-standard@14.1.1 requires a peer of eslint-plugin-node@>=9.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-codemirror@1.0.0 requires a peer of react@>=15.5 <16 but none is installed. You must install peer dependencies yourself.
npm WARN react-codemirror@1.0.0 requires a peer of react-dom@>=15.5 <16 but none is installed. You must install peer dependencies yourself.
......

### Screenshots
<img width="1440" alt="屏幕快照 2020-12-04 下午12 54 20" src="https://user-images.githubusercontent.com/23006292/101123764-80abb980-3630-11eb-8361-4d268697ab0d.png">

### Additional Information
- [x] [nodejs-bigquery#624](https://github.com/googleapis/nodejs-bigquery/issues/624#issuecomment-587940329)
[SwitchHosts#518](https://github.com/oldj/SwitchHosts/issues/518#issue-756033469)
[Postman#8968](https://community.postman.com/t/could-not-get-a-response-error-client-network-socket-disconnected-before-secure-tls-connection-was-established/8968/4)

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a folloup comment.

Thanks in advance! Your help is appreciated.

**Comment by ckerr** [comment]
This appears to be a problem with downloading Electron from the npm repositories, not a bug in Electron's code itself.

Those kinds of outages usually resolve themselves within a couple of hours. If the problem persists, please report it to npm.

If I've misunderstood this issue and you feel it actually _is_ a bug with Electron's code, please re-open it in a new issue. Thank you!

**Comment by kefeibuhuifei** [comment]
how to do?

**Comment by Symbolk** [comment]
> how to do? i try all,but this error still exists

You can try to downgrade the Electron version, like 7.2.4 or a more recent version.
