### ISSUE TITLE
Servers

### ISSUE THREAD

**Issue by HazyPlayz** [electron/electron#26835]
I Cant Join Servers Without Using My Account Witch Sucks :/ Please Make It So U Can

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
