### ISSUE TITLE
BrowserWindow#setBackgroundColor doesn't work

### ISSUE THREAD

**Issue by fabiospampinato** [electron/electron#26842]
### Issue Details

* **Electron Version:**
  * 11.0.3
* **Operating System:**
  * macOS 10.14
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior

It should work.

### Actual Behavior

It doesn't do anything, as far as I can tell. When resizing the window like a lunatic actually _sometimes_ you can kind of see the new background color, but it's as if it's applied only to the portion of the window the app doesn't occupy yet.

By the way vibrancy isn't working for me either, perhaps the two issues are related.

### To Reproduce

Fiddle: https://gist.github.com/753fe49cec47bfa46e06cd77d16053b0

**Comment by jcarpenter** [comment]
Here's what I'm seeing (Electron 11.0.3, macOS 11.1)

* Don't set backgroundColor: white background
* Set background color to any value: black background. Have tried all sorts of values: 6-digit hex, 8-digit hex, even `#FFF`; nothing makes a difference.

Transparency and Vibrancy are off.

**Comment by charlag** [comment]
For us it works the first time we set it but not afterwards. Both 11.4.0 and 12.0.10.

**Comment by yarinsa** [comment]
@nornagon @zcbenz @jcarpenter @fabiospampinato @charlag 
Hey, I encountered the same issue, did any of you managed to solve it? From my experience with electron.js sometimes it could be unrelated flags that prevent some behaviors.

**Comment by fabiospampinato** [comment]
I haven't looked into it again, whatever flag may or may not conflict with it I need it so I can't just toggle it to have the background color working.

**Comment by garrettm** [comment]
> For us it works the first time we set it but not afterwards. Both 11.4.0 and 12.0.10. `getBaackgroundColor()` returns new color but it's not actually applied.

I'm seeing the same behavior @charlag -- though I am able to get one set to go through right after creating my browserWindow (maybe sets before show() go through?)

**Comment by bpasero** [comment]
Confirmed also for VSCode.

//cc @deepak1556

**Comment by bpasero** [comment]
I think this actually works starting with Electron 15 from my testing with a Fiddle.

**Comment by deepak1556** [comment]
This is fixed by https://github.com/electron/electron/pull/30777, please check `>=v14.0.1` or `>=15.0.0`
