### ISSUE TITLE
Windows 10 Compatibility Issues

### ISSUE THREAD

**Issue by ryanrocket** [electron/electron#26845]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v10.1.3
* **Operating System:**
  * macOS Catalina v10.15.7
* **Last Known Working Electron version:**
  * Not Applicable

### Expected Behavior
When using the .exe installer provided by my `electron-builder` to install my app on windows, the installer should open and install the software.

### Actual Behavior
Nothing happens when opening the installer file, even when opening as administrator, and I have to troubleshoot it and then run it under "Windows 8 compatibility mode"

### To Reproduce
The repository is at <a href="https://github.com/ryanwans/TestCapletFront/">https://github.com/ryanwans/TestCapletFront/</a> <br>
To Clone It:
`git clone https://github.com/ryanwans/TestCapletFront.git`<br>
`cd TestCapletFront`<br>
`npm run start` (will install and start app)

### Screenshots
Not Applicable 

### Additional Information
The installer works perfectly fine on macOS, even on a foreign machine. Any help is appreciated.

**Comment by MarshallOfSound** [comment]
`electron-builder` is not official Electron tooling and we do not directly support it.  Please raise any issues you have with it on it's repository, not here.
