### ISSUE TITLE
Tray icon not displayed in Ubuntu with Snap

### ISSUE THREAD

**Issue by panuhorsmalahti** [electron/electron#26854]
### Preflight Checklist
* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
v9.3.5, also tested v10.1.6 and v11.0.3

* **Operating System:**
Ubuntu 20.10

### Expected Behavior
The tray icon should be displayed.

### Actual Behavior
A default tray icon with three dots are displayed instead.

### To Reproduce
Create Electron application with tray icon, package it as Snap and launch the application on Ubuntu.

### Additional Information
There have been earlier problems with tray on Linux, see e.g. #21445.

The icon works fine on Windows and Mac. It also works fine on Linux/Ubuntu using AppImage distribution and also in the dev environment. It's only a problem with a Snap-based package. We use electron-builder to package the application.

The issue is tracked in our GitHub in https://github.com/lensapp/lens/issues/1632.

**Comment by elsiehupp** [comment]
The third-party Snap distribution for Joplin has what seems to be a fairly simple workaround:

https://github.com/MrCarroll/joplin-snap/commit/428d39046ba3e49076a6b1fb9a50a8262914f309

AppIndicators being broken seems to be a larger issue on Ubuntu:

https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/74

**Comment by soloturn** [comment]
@elsiehupp this is no ubuntu issue, this is an electron issue. there are linux systems which do not have a tray, gnome one of them, and with it ubuntu, see their reasoning here:
https://blogs.gnome.org/aday/2017/08/31/status-icons-and-gnome/

it would be great that electron has a way that a client app can check programmatically "if a tray exists then *.

**Comment by elsiehupp** [comment]
FWIW the de facto solution for “Status Icons” or “AppIndicators” in GNOME seems to be [Ayatana Indicators](https://ayatanaindicators.github.io/), which have an unclear historical development relationship with Canonical. Ayatana Indicators are an implementation of an XDG standard spearheaded by KDE, [StatusNotifierItem](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/).

There are presumably a variety of ways that Electron could check to see if the graphical shell provides a “tray” area. The simplest and most direct would probably be to run a `bash` shell that queries all of the “tray” libraries that Electron is designed to work with. Electron could then provide a higher-level API for delivering this information to the application.
