### ISSUE TITLE
Windows JumpList empty when a single entry has a long description

### ISSUE THREAD

**Issue by bpasero** [electron/electron#26862]
### Issue Details

* **Electron Version:**
  * 11.0.3
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 

### Expected Behavior
An invalid entry to the `JumpList` does not cause other entries to disappear.

### Actual Behavior
A single invalid `JumpList` entry makes all other entries disappear.

### To Reproduce

```ts
// Modules to control application life and create native browser window
const { app, BrowserWindow } = require('electron')

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
let mainWindow

function createWindow() {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true
    }
  })

  // and load the index.html of the app.
  mainWindow.loadFile('index.html')

  // Open the DevTools.
  // mainWindow.webContents.openDevTools()

  // Emitted when the window is closed.
  mainWindow.on('closed', function () {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null
  })
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow)

app.setJumpList([
  {
    type: "custom",
    name: "Recent Workspaces",
    items: [
      {
        type: "task",
        title: "Title",
        description: "Description",
        program: process.execPath
      },
      {
        type: "task",
        title: "Long Title",
        description: "DescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescriptionDescription",
        program: process.execPath
      }
    ]
  }
])

// Quit when all windows are closed.
app.on('window-all-closed', function () {
  // On OS X it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', function () {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (mainWindow === null) {
    createWindow()
  }
})

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.
```

### Additional Information
It looks like this happens when the `description` property exceeds 255 characters length?

**Comment by Udbhavbisarya23** [comment]
I would like to work on this issue. Can someone please guide me as this would be my first contribution

**Comment by zg3d** [comment]
Could I try to contribute to this issue.

**Comment by codebytere** [comment]
hey @zg3d - sure! i'd be happy to give you some pointers. So what's happening here is that is looks like when the [SetDescription](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishelllinka-setdescription) method is called with a too-long parameter, it causes the `IShellLink` to not show up. [`SetJumpList`](https://github.com/electron/electron/blob/cffb51e141deb2b81b28e5a1aaf06f6a40e1ad59/shell%2Fbrowser%2Fapi%2Felectron_api_app.cc#L1246-L1281) is implemented here, which in turn invoked methods from [this file](https://github.com/electron/electron/blob/1c99a9b425dd026b4be939486b48bd48022fee82/shell%2Fbrowser%2Fui%2Fwin%2Fjump_list.cc#L1-L351). I'd start by digging into [this line](https://github.com/electron/electron/blob/1c99a9b425dd026b4be939486b48bd48022fee82/shell%2Fbrowser%2Fui%2Fwin%2Fjump_list.cc#L28).

**Comment by MarcoDotIO** [comment]
Hi there,

I'm a complete beginner for developing on the Electron platform. Do you guys have any resources for getting started with solving issues with this type of platform?

**Comment by ankushduacodes** [comment]
Hi @codebytere, I would love to work on this issue if no one is. 
Please let me know if I may.

Thank you!... 🚀

**Comment by rohit306-bit** [comment]
i also wants to try to fix it

**Comment by codebytere** [comment]
As this is an open source project, you do not need my permission to work on available issues :)

**Comment by SushiJackal** [comment]
Hey! I am currently looking into this issue, to maybe propose a solution, as a first time contributor. I am asking myself what the best approach to fixing this would be. Is the goal the rejection of JumpList items whose descriptions are too long while keeping others displayed, displaying of those in question with their long description, or the preprocessing of the evoked description to not exceed a certain char limit (i.e. "DescriptionDescription" to "DescriptionDesc...")?

The SetDescription function as defined by Microsoft's specification (from the attached website a few comments up) only accepts strings with sizes smaller than INFOTIPSIZE. By my current understanding, this is an OS-specific constant, so displaying the JumpList items with their full description (exceeding this constant) would be very difficult (if not impossible).

**Comment by SushiJackal** [comment]
Hello! I'm a first time contributor, and trying my hands at this issue. I see the "LOG" function being called a lot, to, probably, log errors and warnings into a file somewhere, but I couldn't find out how to access these logs/where they are saved. Could someone give me a pointer on this?

**Comment by SushiJackal** [comment]
After running some tests to determine the source of the issue, I've come to the conclusion that the `SetDescription` function returns `S_OK`, so 0, even if the description is too long to function as expected.

Since this behaviour is part of a Windows function (as far as I can see), in my opinion the best solution would be to keep the if-statement checks intact (`FAILED(link->SetDescription...` and such), and, after, check the `item.description.c_str()` string against a predetermined maximum length (the above suggested 255?), returning `false` if it should exceed it, like what is done with the `if`-checks within `AppendTask`. Would this be good practice? Is there a more elegant way?

**Comment by erickzhao** [comment]
@SushiJackal I'm personally unfamiliar with the code, but if you have a working fix, I'd suggest submitting a PR to show your solution and getting feedback there.
