### ISSUE TITLE
Electron crashes when closing a window with loading webviews

### ISSUE THREAD

**Issue by t57ser** [electron/electron#26864]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.6
* **Operating System:**
  * Windows
* **Last Known Working Electron version:**
  * unknown

### Expected Behavior
No crash

### Actual Behavior
electron crashes
![grafik](https://user-images.githubusercontent.com/10595986/101370185-79431500-38a9-11eb-8b35-c24565a56097.png)

### To Reproduce
Note: the crash doesnt always happen, so a few tries might be necessary, but it happens fairly often.
However the crash does not happen if webContents.stop(); is called before closing the window.

This issue could be related: https://github.com/electron/electron/issues/26863
I believe there is a general issue that electron crashes when trying to close a webContent that is still loading.
```
const { app, BrowserWindow } = require("electron");
const path = require("path");

const init = () => {
	for (let i = 0; i < 50; i++) {
		let browserWindow = new BrowserWindow({
			show: true,
			webPreferences: {
				sandbox: true,
				nodeIntegration: true,
				webviewTag: true,
				nativeWindowOpen: true,
			}
		});
		browserWindow.webContents.on("did-attach-webview", (event, webContents) => {
			browserWindow.close();
		});
		browserWindow.webContents.loadURL(path.join(app.getAppPath(), "index.html"));
	}
};

app.on("ready", () => {
	init();
});
```
index.html
```
<!DOCTYPE html>
<html>
<style>
    body {
        background: black;
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
    }
    webview {
        position: absolute;
        height: 500px;
        width: 500px;
        border: 1px solid black;
    }
    webview:active {
        border-right: 5px solid yellow;
    }
</style>
<body>
<webview id="webview" src="https://www.google.com"></webview>
</body>
<script>
    setTimeout(() => {
        document.getElementById("webview").openDevTools();
    }, 100);
</script>
</html>
```

**Comment by codebytere** [comment]
Fixed in recent versions - above gist doesn't crash.
