### ISSUE TITLE
Both openFile and openDirectory doesn't work on Windows / Linux

### ISSUE THREAD

**Issue by vasyl-shumskyi** [electron/electron#26885]
`electron 6.0.10`

I need to be able to open both files and folders with electron `showOpenDialog`

But I can't accomplish this on Windows or Linux. Maybe this issue is related https://github.com/electron/electron/issues/8075 

```javascript
dialog.showOpenDialog({ properties: [ 'openDirectory', 'openFile', 'multiSelections' ] })
```
opens only directories but **not** files. 

```javascript
dialog.showOpenDialog({ properties: [ 'multiSelections' ] })
```
opens only files but **not** directories

----

**UPDATE**: 

Docs saying 

> Note: On Windows and Linux an open dialog can not be both a file selector and a directory selector, so if you set properties to ['openFile', 'openDirectory'] on these platforms, a directory selector will be shown.

Is there any workaround for this?

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
