### ISSUE TITLE
Accelerators in menus no longer reflect keyboard layout on Windows

### ISSUE THREAD

**Issue by alexdima** [electron/electron#26888]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * `3.0.0-beta.1` and above
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * `2.0.18`

### Expected Behavior
* When using a keyboard layout like German (QWERTZ) on Windows, `VKEY_OEM_2` should be rendered as `#` in the menu, not as `/` (like on the US keyboard layout)

### Actual Behavior
* `VKEY_OEM_2` is always renderer as `/` even if pressing `VKEY_OEM_2` produces `#`

### To Reproduce
* Electron Fiddle that uses `ctrl+/` as an accelerator: https://gist.github.com/eda6786c4f94483bf58aaa3147f1548f
* Switch the keyboard layout to German (QWERTZ) on Windows

relevant code snippet:
```
const template = [
  {
    label: 'Edit',
    submenu: [
      { label: 'Test', accelerator: 'Ctrl+/' },
    ]
  }
]

const menu = Menu.buildFromTemplate(template)
Menu.setApplicationMenu(menu)
```

### Screenshots
* `2.0.18` (last known good version):
![image](https://user-images.githubusercontent.com/5047891/101508514-0f457100-3978-11eb-9338-f258ee13738e.png)

* `3.0.0-beta.1` (first bad version):
![image](https://user-images.githubusercontent.com/5047891/101508406-ec1ac180-3977-11eb-84b4-bc7d6a0ef370.png)

### Additional Information
* From what I can tell, `ctrl+/` is parsed [here](https://github.com/electron/electron/blob/462de5f97a302987dc5fa5c222781ceed040f390/shell/common/keyboard_util.cc#L289-L290) as `ui::VKEY_OEM_2` correctly.
* Another example is `ctrl+\` which should be rendered as `Ctrl+â` on the Romanian keyboard layout.

**Comment by VerteDinde** [comment]
Hey @alexdima! Electron 3 is unfortunately no longer in our supported versions - could you see if this issue persists for you in Electron 10 or later?

**Comment by alexdima** [comment]
@VerteDinde Yes, this issue is affecting VS Code, which is on Electron 11. I mentioned Electron 3 in order to save you some time in tracking down when the breaking change was introduced.
