### ISSUE TITLE
Eyedropper does not work 

### ISSUE THREAD

**Issue by robhil** [electron/electron#26883]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 12.0.0-beta.7
* **Operating System:**
  * macOS / Window
* **Last Known Working Electron version:**
  * 8

### Expected Behavior

1. Add `<input type="color" />` in HTML code
2. Run the app
3. Click on input - color picker is opening
4. Pick color by Eyedropper
5. Input should be updated by selected color

### Actual Behavior
The eyedropper is not started

### To Reproduce
For reproduce you can use electron fiddle and simply add `<input type="color" />`  in HTML code
 
### Screenshots
![5ZqhvTeI95](https://user-images.githubusercontent.com/8972979/101465241-fa4ceb80-393f-11eb-950f-152f736e127e.gif)

**Comment by mlaurencin** [comment]
Example repro can be found here: https://gist.github.com/mlaurencin/cb0f0b2d6b075e67721c41474c0f17da
