### ISSUE TITLE
Crash with dialog.showMessageBox(Sync) on macOS Big Sur

### ISSUE THREAD

**Issue by poiru** [electron/electron#26884]
We're getting lots of crash reports from users on macOS Big Sur. The crashing line is either

https://github.com/electron/electron/blob/e3c4bbd21fb0ea2a79d8572add78e4b8c07c64a8/shell/browser/ui/message_box_mac.mm#L117

or

https://github.com/electron/electron/blob/e3c4bbd21fb0ea2a79d8572add78e4b8c07c64a8/shell/browser/ui/message_box_mac.mm#L128

The crash report is annotated with:

>Crashing on exception: -[NSApplication runModalForWindow:] may not be invoked inside of transaction begin/commit pair, or inside of transaction commit (usually this means it was invoked inside of a view's -drawRect: method.)
>ViewBridge hint(s): (
>     "bridge key: most-recent-completion"
>)

This is on Electron 10.1.6, I have not tested other versions.

cc @zcbenz

**Comment by poiru** [comment]
It seems like this happens when

```js
await dialog.showOpenDialog(browserWindow, options)
```

is immediately followed with

```js
await dialog.showMessageBox(null, options)
```

I'll try to work on a reduced test case when I have more time.

**Comment by danikyyzz** [comment]
ok

**Comment by Dotnaught** [comment]
> It seems like this happens when
> 
> ```js
> await dialog.showOpenDialog(browserWindow, options)
> ```
> 
> is immediately followed with
> 
> ```js
> await dialog.showMessageBox(null, options)
> ```

I encountered a crash on macOS Big Sur in a when trying to implement a file overwrite check using two dialog objects, the second of which had no browser window parameter supplied:

```js
dialog.showSaveDialog(mainWindow, {
			properties: ["openFile", "openDirectory"],
			filters: [{ name: "JSON", extensions: ["json"] }],
			buttonLabel: "Export Feeds",
			defaultPath: defaultPath,
		})
		.then((result) => {
			if (result.filePath === undefined || result.canceled) {
				console.log("No file path defined or cancelled");
				return;
			}
			if (fs.existsSync(result.filePath)) {
				dialog.showMessageBox(
                    **//no window reference**
					{
						type: "info",
						buttons: ["Yes", "No"],
						message: "Are you sure you want to overwrite this file?",
					},
					(resp) => {...
```

Adding a window reference prevented the crash.

It turns out macOS Big Sur handles overwrite confirmation with a native window so it's redundant to do so in code. I don't recall this happening in prior versions of macOS as I used this code in a previous Electron app.

**Comment by Sakari369** [comment]
Yeah I'm seeing this same behaviour on macOS Big Sur. Using Electron 11.4.10.
When opening showOpenDialog, then after that opening dialog.showMessageBox with no window reference, the application quits with SIGILL.

Adding a window reference to showMessageBox seems to fix the crashing.

**Comment by nornagon** [comment]
Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by Sakari369** [comment]
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.
> 
> Thanks in advance! Your help is appreciated.

I should be able to do it, yes. 
I will look into it, get back to this thread later.

Thanks for the reply.

**Comment by Sakari369** [comment]
Just wanted to do a quick update, I tested this with Electron Fiddle and could not reproduce it quickly there. Will try to look at this at some point to see if I can get it to reproduce.
