### ISSUE TITLE
Frozen window appears when app is closed to tray and resolution is changed

### ISSUE THREAD

**Issue by devinfoley** [electron/electron#26899]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.0.4 and 12.0.0-beta.7
* **Operating System:**
  * Windows 10 and 8.1
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
Window does not re-open itself or become unusable.

### Actual Behavior
When you maximize and then close an Electron App to the system tray, and then change the display resolution in Settings, the Electron app will re-open the app window, and that window will be unusable. 

### To Reproduce
Here's a gist: https://gist.github.com/devinfoley/7888802bc7f6597f703646a5263d4662

1. Start the application.
2. Maximize the window.
3. Close the window with X.
4. Enter Settings and change your display resolution.

You may need to change the application icon referenced in the above fiddle. It's hardcoded to a location on my machine.

### Screenshots

Open and maximize the app, then close it to system tray by clicking the X button.
<img width="1241" alt="Maximized App" src="https://user-images.githubusercontent.com/139239/101559151-6564e500-3975-11eb-985e-f33a309b9af2.png">

Go into settings and change your resolution.
<img width="1241" alt="Changing Resolution in Settings" src="https://user-images.githubusercontent.com/139239/101559149-6433b800-3975-11eb-820c-919c376b452b.png">

After the resolution is changed, an unusable Electron window will be displayed fullscreen.
<img width="1264" alt="A Broken Window Appears!" src="https://user-images.githubusercontent.com/139239/101559142-6138c780-3975-11eb-81a3-84a4ec72e0ee.png">

### Additional Information
I was able to repro this issue in Parallels, but not VirtualBox.

**Comment by graphixillusion** [comment]
@devinfoley It's happening to me too with two different apps: Joplin and Discord. Actually if i minimize the app, open the taskbar settings and enable "auto hide taskbar", the Joplin's window auto appear maximized in the background. Same thing happens with Discord after i logon into Windows from the lock screen: Discord's window will stay freezed and maximized. At first i thought it was a Joplin (or Discord) problem but when i saw the same scenario in both apps i start to think that maybe it was an electron's problem itself, and i found this issue on here.

**Comment by yossizahn** [comment]
I am having a similar issue whenever my laptop changes from wired to battery or vice versa.
I believe this has the same root cause since the display's refresh rate changes and a [WM_DISPLAYCHANGE ](https://docs.microsoft.com/en-us/windows/win32/gdi/wm-displaychange)gets broadcasted to all windows.
