### ISSUE TITLE
Opening devtools while wasm is being loaded hangs the process

### ISSUE THREAD

**Issue by ChALkeR** [electron/electron#26903]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  * v11.0.4, v10.1.7
* **Operating System:**
  * `Linux workstation 5.9.11-arch2-1 #1 SMP PREEMPT Sat, 28 Nov 2020 02:07:22 +0000 x86_64 GNU/Linux`

### Expected Behavior
Hang should not happen, there shouln't be a race there.
The situation should be identical to either opening the devtools before or after loading wasm file.

### Actual Behavior
The renderer process hangs and becomes unresponsive.
Not possible to evaluate anything in devtools.

### To Reproduce

_Or just skip to the full setup section below._

1. Obtain any sufficiently large wasm file (tried with 1 MiB or above, reproducible).
    I'll use http://wasm.continuation-labs.com/d3demo/d3wasm.wasm from [d3wasm](https://github.com/gabrielcuvillier/d3wasm) for this demonstration.

2. Load CPU.
    `sysbench cpu --time=10000000 --threads=96 run` (adjust for your number of threads) will do.
    This is not a required step, but with this it happens about 50% times for me, and without it it's a rare case which takes a long time to reproduce/debug.

3. Use the following code for reproduction:
   `main.js`:
    ```js
    const { BrowserWindow, app, ipcMain } = require('electron')
    const path = require('path')

    let win
    const run = async () => {
      console.log('Run at:', Date.now())
      const window = new BrowserWindow({ show: false })
      window.webContents.openDevTools({ mode: 'bottom' })
      window.loadURL(`file://${path.resolve('index.html')}`)
      win = window
      setTimeout(() => {
        if (win === window) {
          console.log('Hanged!')
          win.show()
        }
      }, 5000)
      win.on('close', (event) => {
        // or just let it quit and run with: for i in `seq 10000`; do electron ./main.js; done
        // app.quit(); return
        setTimeout(run, 100)
        event.preventDefault()
      })
    }

    app.on('ready', run)
    ```
    `index.html`:
    ```html
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="utf-8">
      </head>
      <body>
        <button>Button just to check renderer responsiveness</button>
        <script>
          "use strict";
          console.error('instantiateAsync')
          const wasmBinaryFile = new URL('d3wasm.wasm', document.location.href).toString()
          fetch(wasmBinaryFile, { credentials: "same-origin" }).then(
            (response) => {
              console.log('fetch finished')
              WebAssembly.instantiateStreaming(response, {}).then(() => {
                console.log('instantiateStreaming finished, this is fine')
                window.close()
              }).catch(() => {
                console.log('instantiateStreaming failed, this is fine')
                window.close()
              })
            }
          );
          console.log("waiting...");
        </script>
      </body>
    </html>
    ```
   js code from html can be extracted to a separate script file, that is not significant.
   `d3wasm.wasm`: see step 1, obtained from https://wasm.continuation-labs.com/d3demo/d3wasm.wasm, but any sufficiently large file should do.

4. Launch with `./node_modules/.bin/electron --enable-logging main.js` to observe the logs.
   
   If `done` handler is altered to just call `app.quit()` and return, use `for i in `seq 10000`; do ELECTRON_ENABLE_LOGGING=true ./node_modules/.bin/electron main.js; done` instead.

#### Full setup

```sh
$ git clone https://github.com/ChALkeR/electron-wasm-issue
$ sysbench cpu --time=10000000 --threads=96 run & # or on a separate tab
$ cd electron-wasm-issue
$ npm it
```

### Screenshots
![Screenshot_20201209_125559](https://user-images.githubusercontent.com/291301/101614345-e4adf380-3a1d-11eb-848e-a7f6f2719852.png)
Button unresponsive, devtools responsive but don't execute anything (pressing Enter does nothing).

### Additional Information
Manual CPU load is not required. This was reproduced with normal conditions, just happens less frequently.

This also smells like a Chromium issue, but I didn't create a testcase for it yet, and didn't find anything relevant at https://bugs.chromium.org/p/chromium/issues/list.

**Comment by ChALkeR** [comment]
I succeeded creating a testcase that can be reproduced on Chromium without Electron.

Available here: https://github.com/ChALkeR/electron-wasm-issue#to-reproduce-on-chromium.

It also doesn't need putting CPU under pressure anymore.

**Comment by deepak1556** [comment]
I am able to repro the hang on latest canary. @ChALkeR can you open an issue in chromium with your repro ? Thanks!

**Comment by ChALkeR** [comment]
@deepak1556 Yeah, was at it, just needed a bit more confirmations that the reproduction code is solid.

Upstream bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1158570

**Comment by ChALkeR** [comment]
The upstream issue is closed. This seems fixed.
