### ISSUE TITLE
Electron App not listed in Notification settings in Win 10 

### ISSUE THREAD

**Issue by nikhell86** [electron/electron#26902]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.6
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * Does not even work with latest electron version

### Expected Behavior
The app should get listed in notification settings in Windows 10

### Actual Behavior
App is not present in notification settings

### To Reproduce
 Use electron Notification module. trigger a notification. From the notification tile, turn off notifications. Try to enable them back by going to notifications settings. The app is not found there.
![image](https://user-images.githubusercontent.com/58811413/101597374-a237e700-3a1c-11eb-92b4-898b75805950.png)

### Screenshots
![image](https://user-images.githubusercontent.com/58811413/101597600-ed51fa00-3a1c-11eb-97e2-9c73382a81e6.png)

### Additional Information
We have written an electron app. It shows notifications (Win10). Once the app was spamming with a lot of notifications so I switched them off from the notification tile.

I wanted to enable them back. So I went to notification settings and I could not find my app in the list.

PS: We are using electron Notification module and we are also calling app.setAppUserModelId("OurAppName")

**Comment by ckerr** [comment]
Hey @nikhell86, thanks for reaching out.

One issue that immediately stands out is the use of 5.0.6 -- that version of Electron's been end-of-lifed for some time now and is [no longer supported](https://www.electronjs.org/docs/tutorial/support#supported-versions). The first thing I'd suggest is to try upgrading your version of Electron to a [supported version](https://www.electronjs.org/releases/stable) and see if that changes anything.

If the issue persists, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.
