### ISSUE TITLE
<webview>.getWebContentsId is not a function with contextIsolation enabled

### ISSUE THREAD

**Issue by andersk** [electron/electron#26904]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.0.0 through 16.0.0-beta.2
* **Operating System:**
  * NixOS 21.11 x86_64
* **Last Known Working Electron version:**
  * none

### Expected Behavior
Within a preload script, I should be able to get the WebContents ID of a `<webview>` element using `webview.getWebContentsId()` (after the `dom-ready` event fires), whether `contextIsolation` is enabled or disabled.

### Actual Behavior
This only works if `contextIsolation` is disabled. With `contextIsolation` enabled, I get `Uncaught TypeError: webview.getWebContentsId is not a function`.

(Some other way to do this would be fine too, but I haven’t found one.)

### To Reproduce
Electron Fiddle: https://gist.github.com/5a21657fe926111ad18026905d1ed81d

Observe the error in the console, then change `contextIsolation` to `false` and observe that there’s no error.

**Comment by codebytere** [comment]
It looks like this is specific to initial load. For example, in your fiddle, if you go to devtools console and try:
```
const webview = document.querySelector("webview");
webview..getWebContentsId()
```
it correctly prints a number.

likewise, if in your fiddle preload you instead have:
```
window.addEventListener("DOMContentLoaded", () => {
  const webview = document.querySelector("webview");
  console.log("webview =", webview);
  webview.addEventListener("dom-ready", () => {
    const webview = document.querySelector("webview");
    console.log("WebContents devtools focused", webview.isDevToolsFocused());
  });
});
```

you then get:
![Uploading Screen Shot 2020-12-09 at 7.40.11 PM.png…]()

**Comment by andersk** [comment]
I don’t think it’s specific to the initial load. If I change the preload to

```js
const {contextBridge} = require("electron");
contextBridge.exposeInMainWorld("foo", {
  foo() {
    const webview = document.querySelector("webview");
    console.log("webview =", webview);
    console.log("WebContents ID =", webview.getWebContentsId());
  },
});
```

and then type `foo.foo()` into the devtoools console, I get the same error.

**Comment by codebytere** [comment]
@andersk yeah - it's this:

> This is happening because when contextIsolation is enabled, the webview tag isn't set up until after the preload scripts run, so the functions don't exist yet. I'll try to figure out the best fix here.

**Comment by andersk** [comment]
In my `foo.foo()` example, the error occurs well after any setup would be finished.

**Comment by xmedeko** [comment]
I would be happy to have `webContentsId` available in the preload script right away (to set up logging).

As a workaround it's possible to ask for `webContentsId` the main process:
```js
// main.js
ipcMain.handle('get-id', (event) => event.sender.id);

// preload.js
const { ipcRenderer } = require("electron");
(async () => {
    const webContentsId = await ipcRenderer.invoke('get-id');
    console.log("webContentsId", webContentsId);
    // ...
})();
```

**Comment by andersk** [comment]
@xmedeko That gives you the `webContentsId` for the current `WebContents`, not for a `<webview>` element.

**Comment by Aaronphy** [comment]
Oh! same issue , hope someone give some suggestions or a workaround!!!😄

**Comment by Aaronphy** [comment]
MacOS also has the same issue

**Comment by Aaronphy** [comment]
> @xmedeko That gives you the `webContentsId` for the current `WebContents`, not for a `<webview>` element.

Any suggestions? It blocks me....

**Comment by Aaronphy** [comment]
@andersk  any suggestions ?  😊

**Comment by andersk** [comment]
Although this is labeled 11-x-y, it still reproduces in all supported versions. Can someone label this 12-x-y, 13-x-y, and 14-x-y so this doesn’t get auto-closed by the triage bot?

**Comment by jampy** [comment]
Any solution to this problem?

**Comment by andersk** [comment]
Still a bug in 21.0.1, 22.0.0-alpha.1, and 23.0.0-nightly.20221004.

**Comment by andersk** [comment]
Still an issue in 22.0.3, 23.0.0-beta.4, and 24.0.0-nightly.20230120.

**Comment by andersk** [comment]
Stilll an issue in 25.3.2, 26.0.0-beta.7, and 27.0.0-nightly.20230726.

**Comment by codebytere** [comment]
@andersk does this not work for you?

```js
// renderer process
const wv = document.querySelector('webview')
wv.addEventListener('dom-ready', () => {
  console.log(wv.getWebContentsId()) // prints a number
})
```

this works fine for me on latest stable with contextIsolation enabled.

**Comment by andersk** [comment]
@codebytere It doesn’t work for me *in the preload script*. See the Fiddle from my original report.

**Comment by codebytere** [comment]
Yes - i understand that. I'm asking if this workaround satisfies your needs.
