### ISSUE TITLE
Electron Crash on calling a native addon which is using window's uiautomation library to detect button in another window

### ISSUE THREAD

**Issue by AtiqGauri** [electron/electron#26919]
### Preflight Checklist

* [ X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.0.1
* **Operating System:**
  * windows 10
* **Last Known Working Electron version:**
  * 

### Expected Behavior
napi naitve addon works perfectly as standalone, So it should work in electron too...

### Actual Behavior
Napi native addon crash electron...

### To Reproduce
Call windows uiautomation library function in any native addon and try to run it with electron app

#### But when I try to run that native addon in electron it crash electron app.

here is native addon c++ code which detect element:
```
void ListDescendants(IUIAutomationElement* pParent, int indent)
{
  if (pParent == NULL)
      return;

  IUIAutomationTreeWalker* pControlWalker = NULL;
  IUIAutomationElement* pNode = NULL;
  
  
  g_pAutomation->get_ControlViewWalker(&pControlWalker);
  if (pControlWalker == NULL)
      goto cleanup;

  
  pControlWalker->GetFirstChildElement(pParent, &pNode);
  if (pNode == NULL)
      goto cleanup;
  
  while (pNode)
  {
      BSTR sName;
      pNode->get_CurrentName(&sName);
      //std::wcout << sName << L"\n";
      std::wstring strName(sName, SysStringLen(sName));
      if (strName.find(L"currently unmuted") != std::string::npos)
      {
        std::cout<<"####### UNMUTE"<<"\n";
      }else if(strName.find(L"currently muted") != std::string::npos){
        std::cout<<"####### MUTE"<<"\n";
      }
      SysFreeString(sName);

      ListDescendants(pNode, indent+1);
      IUIAutomationElement* pNext;
      pControlWalker->GetNextSiblingElement(pNode, &pNext);
      pNode->Release();
      pNode = pNext;
  }
cleanup:
  if (pControlWalker != NULL)
      pControlWalker->Release();

  if (pNode != NULL)
      pNode->Release();

  return;
}
```

**Comment by nornagon** [comment]
Unfortunately without any steps to reproduce this issue we can't debug further. Please provide a small example that reproduces the issue you're seeing, preferable using [Electron Fiddle](https://github.com/electron/fiddle).

Thanks!

**Comment by AtiqGauri** [comment]
This was related to cmake build process...
I was building native-addon using [cmake.js](https://www.npmjs.com/package/cmake-js) and we can OPTIONALLY mention [runtime](https://www.npmjs.com/package/cmake-js#runtimes) in cmake.js.         
Which I was not doing, so by mentioning electron runtime this error went away.
