### ISSUE TITLE
app.getFileIcon get buggy image when scale is not 1.0

### ISSUE THREAD

**Issue by wildwind3325** [electron/electron#26918]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.3.5
* **Operating System:**
  * Windows 10 (2004)
* **Last Known Working Electron version:**
  * none

### Expected Behavior
It(app.getFileIcon) works when display scale set to 100% and other values.

### Actual Behavior
Only works under 1.0, got buggy image when set to any other value.

### To Reproduce
Set your display scale to any non-1.0 value.

### Additional Information
According to this [post](https://github.com/electron/electron/issues/8767#issuecomment-284515209), I thought it was solved already, but codes below actually doesn't work

```
var electron = require('electron');
var fs = require('fs');

let img = await electron.remote.app.getFileIcon('yourfile', { size: 'normal' });
image.src = img.toDataURL({ scaleFactor: 1.25 });
```

The scaleFactor doesn't effect at all (1.0/0.8/1.25), I think it's because when the image is generated by getFileIcon, it's already corrupted, so pass scaleFactor to toDataURL doesn't make any sense.
I don't know if it's been fixed by latest release but I'm using "vue-cli-plugin-electron-builder" and it only supports 9.x.

**Comment by TanninOne** [comment]
Same on electron 11.0.4 I think, at least I'm also getting broken icons.
