### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DestroyerXyz** [electron/electron#26923]
Is there a way that multiple Electron apps on a system can use the same instance of Chromium?

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
