### ISSUE TITLE
Renderer crash when selection contains ContentEditable and regular text

### ISSUE THREAD

**Issue by lishid** [electron/electron#26939]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.0.3
* **Operating System:**
  * Windows 10 1909
* **Last Known Working Electron version:**
  * Not sure

When HTML contains a contenteditable followed by regular text, selecting (backwards) from the regular text to the contenteditable, then pressing right click, will crash the renderer.

### To Reproduce

Open page with the following code
```html
<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Hello World!</title></head>
<body><div contenteditable="true">Content Editable</div><p>Regular Text</p></body></html>
```

Select from "Regular Text" to "Content Editable", then right click on the selection with the cursor on "Regular Text".

### Screenshots

![test](https://user-images.githubusercontent.com/609710/101853199-38f3c900-3b2d-11eb-9b86-49b9bbc613cb.gif)

### Additional Information

Seems to be a chromium bug. I've filed a separate report at https://bugs.chromium.org/p/chromium/issues/detail?id=1157684

Filing an issue here to keep track. Probably not actionable and just going to wait for the upstream fix. Feel free to close if unnecessary.

**Comment by nornagon** [comment]
Thanks for the report but the chromium bug should be sufficient to track this! We'll receive the fix when chromium ships it and we roll automatically.
