### ISSUE TITLE
net.request ---> Set-Cookie is not coming in redirect response 

### ISSUE THREAD

**Issue by jkpadmanapan** [electron/electron#26942]
### Preflight Checklist

* [ I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project. ]
* [ I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to. ]
* [ I have searched the issue tracker for an issue that matches the one I want to file, without success.]

### Issue Details

* **Electron Version:**
  * Electron  v11.0.4
* **Operating System:**
  * Windows 10
 

### Expected Behavior
I am using net.request. usually net.request will return set-cookie in the response only in 200 response. In case of redirect response like 301, 304, the set-cookie header will not be returned even though it exists on the header. It should be returned. 

### Actual Behavior
set-cookie response header is not coming in the response

Please check this link. Already someone asked the same issue.. 
https://github.com/electron/electron/issues/23865

**Comment by ckerr** [comment]
This appears to be a restatement of #23865, so I'm closing it as a duplicate issue.

If this is in error -- that is, if this is a separate issue -- please open a new issue explaining that. Thank you!

**Comment by jkpadmanapan** [comment]
@ckerr  Hi. Thank you for reply.  #23865, this issue is open for long time and I don't know whether this will be fixed. This is important bug in net.request.  can you please help me ?

**Comment by Zen33** [comment]
This issue is still existed in Electron 24+
