### ISSUE TITLE
Audio output disabled on <video> elements

### ISSUE THREAD

**Issue by javan** [electron/electron#26946]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** v10.1.{6,7}
* **Operating System:** All
* **Last Known Working Electron version:** v10.1.5

### Expected Behavior

Playing a `<video>` should output its audio.

### Actual Behavior

No audio is output.

### To Reproduce

1. Run this Fiddle using Electron v10.1.6: https://gist.github.com/javan/fb642fcd32a13723710cd76898eaf159
1. Click ▶️ and observe that audio *is not* output
1. Change Electron version to v10.1.5 and run again
1. Click ▶️ and observe that audio *is* output

### Additional Information

Looking over https://github.com/electron/electron/compare/v10.1.5...v10.1.6, https://github.com/electron/electron/pull/26196 stands out as a likely culprit: https://github.com/electron/electron/blob/994d835c689c836dcdfa6ac04b85ddcc3663511c/patches/chromium/cherry-pick-88f263f401b4.patch#L297-L312 /cc @nornagon

**Comment by nornagon** [comment]
Thanks for the report, I can repro.

**Comment by nornagon** [comment]
Seems to have been fixed since this was reported.
