### ISSUE TITLE
Simple Fullscreen: after exited simple fullscreen, traffic lights were now missing

### ISSUE THREAD

**Issue by RoderickQiu** [electron/electron#26945]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.1.7
* **Operating System:**
  * macOS 10.15.7
* **Last Known Working Electron version:**
  * Electron 8 (don't know if Electron 9 works, because I skipped that)

### Expected Behavior
1. I have a window, **with `titleBarStyle: "hiddenInset"` or `titleBarStyle: "hidden"`**.
1. Enter simple fullscreen.
2. Exit simple fullscreen.
3. The traffic lights are back.

### Actual Behavior
1. I have a window, with `titleBarStyle: "hiddenInset"` or `titleBarStyle: "hidden"`.
1. Enter simple fullscreen.
2. Exit simple fullscreen.
3. The traffic lights are **gone**.

### To Reproduce

- main.js:
```javascript
const { app, BrowserWindow, ipcMain } = require('electron')
let mianWindow = null

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    titleBarStyle: "hiddenInset", // or: hidden"
    webPreferences: {
      nodeIntegration: true
    }
  })

  mainWindow.loadFile('index.html')
}

app.whenReady().then(createWindow)
app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})
app.on('activate', function () {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow()
  }
})

ipcMain.on("simple-fullscreen", () => {
  if (mainWindow.isSimpleFullScreen()) mainWindow.setSimpleFullScreen(false);
  else mainWindow.setSimpleFullScreen(true);
})
```

- index.html: Call `ipcRenderer.send("simple-fullscreen")` twice.

### Additional Information

If `titleBarStyle` is `default`, things are all right.

**Comment by codebytere** [comment]
@RoderickQiu please provide a complete repro for https://github.com/electron/fiddle - the fewer assumptions we have to make when seeking to triage the better we are able to address it.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
