### ISSUE TITLE
--require missing in NODE_OPTIONS exception

### ISSUE THREAD

**Issue by Githubber2021** [electron/electron#26948]
Hi,

I am using Visual Studio Code to debug my electron app. I recently noticed the following error message:

```
'[43649:1211/120337.296135:ERROR:node_bindings.cc(210)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.',
'[43649:1211/120337.296187:ERROR:node_bindings.cc(210)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.',
'[43649:1211/120337.296197:ERROR:node_bindings.cc(210)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.',
'[43649:1211/120337.296201:ERROR:node_bindings.cc(210)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.',
'[43649:1211/120337.296207:ERROR:node_bindings.cc(210)] Most NODE_OPTIONs are not supported in packaged apps. See documentation for more details.',
```

I noticed the application is started with the following `NODE_OPTIONS` when executed through Visual Studio Code:

```
NODE_OPTIONS: '--require "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js" --inspect-publish-uid=http',
```

Is the `--require` option missing in the file below or is there an issue on my end?

https://github.com/electron/electron/blob/cc09da6233b945de3a7c8ec3da107aa1edbf21cd/shell/common/node_bindings.cc#L197-L204

Thanks!

**Comment by ckerr** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
