### ISSUE TITLE
Enable WebGPU in Electron/Beta releases

### ISSUE THREAD

**Issue by maierfelix** [electron/electron#26944]
To enable WebGPU in electron there are 2 simple steps involved:
 - Include dawn in the build process with the `use_dawn` compile flag
 - Users then can enable WebGPU by passing the runtime flag `--enable-unsafe-webgpu`

I propose adding WebGPU at least to beta releases of Electron. There is a raising demand of developers using WebGPU as a new graphics API and Electron is a great way to learn, prototype or even build early applications with it.

Regarding security, using WebGPU isn't considered safe yet, but since users have to take an additional step to actually enable WebGPU in their browser (see `--enable-unsafe-webgpu` flag), this should be fine.

In my opinion, the only downside argument to this is a larger build size.

CC @Kangz

**Comment by pjoe** [comment]
I second this :)

While waiting for webgpu to be fully supported in browsers, electron is a great way to make something here and now, and e.g. bundle up for easy installation, to share with 'friends and family'

**Comment by nornagon** [comment]
Seems to work fine in v12, and also in Chrome Canary with `--enable-unsafe-webgpu`.

https://gist.github.com/56433ba9d1b11745809607cf7ed3f9a1

**Comment by jhurliman** [comment]
I just tried this on Windows and did not have any luck (`navigator.gpu.requestAdapter()` promise resolves to null). Has anyone gotten this working, and on which platform(s)?

**Comment by ScatteredRay** [comment]
I'm seeing the same problem as @jhurliman If I add `electron.app.commandLine.appendSwitch('enable-unsafe-webgpu');` the object function `navigator.gpu.requestAdapter` appears, and is able to be called, but the result of that future resolves as `null`

@nornagon Can you confirm that you were able to get an adapter, and on which platform, otherwise can we reopen this issue?

**Comment by nornagon** [comment]
Hm, weird, I can't get it working in v12 any more but it works in v14.0.0-nightly.20210305 and later. Seems it was fixed somewhere in https://github.com/electron/electron/compare/v14.0.0-nightly.20210304...v14.0.0-nightly.20210305, probably something to do with the chromium update.

**Comment by geolehmann** [comment]
I tried it too with the latest nightly (Electron 14.0.0-nightly.20210330) , but had no success.... :-(

**Comment by geolehmann** [comment]
Hm, acutally it doesnt work for me in v14.0.0-nightly.20210305 too. I used the same code as in @nornagon ´s gist, however I am on windows...

**Comment by nornagon** [comment]
@geolehmann I won't reopen this issue, because there's nothing to do from our end. Either it works in Chromium or it doesn't. We don't do anything special to disallow or allow this feature. The `use_dawn` flag mentioned in the top post is already enabled by default on mac, windows and linux: https://source.chromium.org/chromium/chromium/src/+/master:ui/gl/features.gni;l=21;drc=de839f65fc73dd2ba0236857cd63f9c006d20b6e

**Comment by geolehmann** [comment]
Of course, I undestand this, thanks.

**Comment by CirilBohak** [comment]
I just tested it on Windows 10, with electron-nightly-14.0.0-nightly.20210430, and it works.
![image](https://user-images.githubusercontent.com/3185466/116815001-35a4bc80-ab64-11eb-85c8-3822e740416c.png)

**Comment by markus-wa** [comment]
for those of you who had success with this - are there any working examples out in the wild?

I've been trying this on and off for weeks now iwthout success. I've also been getting the `Warning: Couldn't open libvulkan.so.1` errors.

I've tried setting it up myself as well as https://github.com/James226/webgpu-electron/commits/main

**Comment by geolehmann** [comment]
I switched from electron to Rust combined with webview, which already supports WebGPU, so I did not investigate this further.

**Comment by jamieyello** [comment]
The latest version of chrome doesn't have a [chrome://flags/#enable-unsafe-webgpu](chrome://flags/#enable-unsafe-webgpu) flag anymore, downloading the beta version of Chrome makes it work by default.

I think maybe [forcing a beta version of Chrome to be used by electron](http://man.hubwiz.com/docset/electron.docset/Contents/Resources/Documents/docs/development/upgrading-chromium.html) would allow WebGPU to work, but I haven't tried yet.

**Comment by luciedefraiteur** [comment]
Hey guys, i'm really wanting to have both webxr/webgpu into an electron build, i know how to build electron from sources, and how to enable webxr on it, but could someone give me actualized guidelines to build it with support for webgpu?

I tried the link from @jamieyello to "force a beta version of chrome to be used by electron", but the link seem really outdated.

**Comment by jamieyello** [comment]
For what it's worth, it looks like Chrome now supports webgpu by default.
