### ISSUE TITLE
Electron symbol server missing libGLESv2.dll.pdb

### ISSUE THREAD

**Issue by poiru** [electron/electron#26961]
`electron-v10.1.7-win32-x64-pdb.zip` contains `libGLESv2.dll.pdb`, but they are missing from the symbol server:

* https://symbols.electronjs.org/libGLESv2.dll.pdb/dc9b50f68734d5954c4c44205044422e1/libGLESv2.dll.pdb
* https://symbols.electronjs.org/libGLESv2.dll.pdb/dc9b50f68734d5954c4c44205044422e1/libGLESv2.dll.sym

See also getsentry/sentry-electron#283

cc @MarshallOfSound

**Comment by nornagon** [comment]
https://github.com/electron/electron/blob/28ae68d66cdc1f8149437793b1f6c732c4b9108f/script/release/uploaders/upload-symbols.py#L28-L30

**Comment by poiru** [comment]
@nornagon Ah! Thanks for the pointer, I'll fix that! 😊
