### ISSUE TITLE
* **Electron Version:**

### ISSUE THREAD

**Issue by 0501814314** [electron/electron#26979]
* **Electron Version:**
Electron 9.2.0
* **Operating System:**
Windows 10 (2004, build 19041.388)

### Expected Behavior
Instant closing of the borderless window after `beforeunload` event.

### Actual Behavior
The window takes 2 seconds before closing.

### To Reproduce

1\. Create a borderless window that load a random website.
2\. Use a preload file.

    new BrowserWindow({
        width: 600,
        height: 900,
        frame: false,
        webPreferences: {
            preload: path.join(__dirname, 'preload.js'),
        }
    }).loadURL('https://google.fr');

3\. Add a `beforeunload` event in the preload file.  

    window.addEventListener('beforeunload', function () {
        console.log("This message is instantly printed into the console. Notice the delay after, before the window close.");
    });

4\. Right click on the taskbar icon and click close.  
5\. Notice the delay.

### Additional informations

The bug only appears when using a borderless window. A simple window closes instantly.

_Originalmente postado por @RealAlphabet em https://github.com/electron/electron/issues/24910_

**Comment by pushkin-** [comment]
Why are you creating a new issue if there already is one for it?
