### ISSUE TITLE
mediaDevices issue on macOS Catalina

### ISSUE THREAD

**Issue by AxelRothe** [electron/electron#26977]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.0.4
* **Operating System:**
  * macOs 10.15.7 (19H2)

### Expected Behavior
We call navigator.mediaDevices.getUserMedia() with the approriate constraints, say a SDI or HDMI to USB converter, it should capture the signal up to 1080p and return a MediaStream Object.

### Actual Behavior
We call navigator.mediaDevices.getUserMedia() with the appropriate constriants, if selecting anything but a USB Webcam or integrated Webcam (Facetime HD), the mediaDevices.getUserMedia() function will return a overConstraintError.

Only way to fix this is to force the navigator.mediaDevices to accept the source is to, call a getUserMedia with a impossible constraint like {video: {height: {exact: 9999}, width: {exact: 9999}},audio:true }

Then when you call it again, it will work flawlessly. As well as any subsequent call.

### To Reproduce
Try and getUserMedia from any USB source, that isn't a Webcam. I used this: https://www.amazon.de/-/en/gp/product/B07SRSNLLX/ref=ppx_yo_dt_b_asin_title_o09_s00?ie=UTF8&psc=1

I made a very simple site to test this and ensure its not a fault in my larger architecture. All I created was a Window with a basic setup with a html video tag and a Vue Component.

The constraints used where: exact 1280x720 25fps

I tried this without electron, directly in chrome and did not encounter this issue.

### Additional Information
I'm happy to assist in fixing this issue.

**Comment by AxelRothe** [comment]
*with a <video> tag and a Vue.component() to select the source.

**Comment by AxelRothe** [comment]
I'd like to add that it's possible to capture the source at 640x480 if you let the navigator try without any constraints. The image will be squished.

**Comment by codebytere** [comment]
@AxelRothe Electron v6 is no longer supported - in order for us to triage this you'll need to demonstrate that it occurs on a [supported version](https://www.electronjs.org/docs/tutorial/support)

**Comment by AxelRothe** [comment]
Sry, this was my mistake. The correct version number was: 11.0.4

**Comment by AxelRothe** [comment]
This issue is persistent on Big Sur and Apple Silicon Big Sur. Please advise?
