### ISSUE TITLE
With I Start Discord Bot Client The Bot Client Is a White Screen And It Does Not Work

### ISSUE THREAD

**Issue by farokomar** [electron/electron#26978]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  4.0.3
* **Operating System:**
  *  Windows 10 (1803) 
* **Last Known Working Electron version:**
  *  IDK

**Comment by Officialstrike** [comment]
The discord   ##bot client you are talking about is no longer maintained
![image](https://user-images.githubusercontent.com/42299518/102005552-d4746d80-3cd6-11eb-8bee-76a321db8451.png)
 https://github.com/Flam3rboy/discord-bot-client - just scroll down and you will find it. You are also commenting on the repo of electron which can't really do anything like the issue you are having is on a different repo. It is also against discord ToS see https://discord.com/terms. Please close this issue @farokomar.
