### ISSUE TITLE
Crash on startup when running headless in Docker

### ISSUE THREAD

**Issue by GeorgDangl** [electron/electron#26974]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.1.0
* **Operating System:**
  * Debian 9 (stretch), via Docker
* **Last Known Working Electron version:**
  * ~9

### Expected Behavior
Electron should start inside Docker with the `--headless` flag so that I can run E2E tests via Spectron.

### Actual Behavior
Starting Electron in a Docker container as a headless instance crashes right on startup.

### To Reproduce

*Summary*: I'm using end-to-end (E2E) tests on an Electron app, this is done in a Docker container via Spectron in headless mode. This stopped working since I upgraded to Electron v11.

First, I'm using the Dockerfile below:

    FROM node:14 AS node
    
    FROM node AS headless
    RUN apt-get update && \
        apt-get install -y xvfb \
        libgbm1 \
        libxss1 \
        libnss3 \
        libgtk-3-dev \
        libasound2-dev \
        unzip \
        dos2unix \
        && rm -rf /var/lib/apt/lists/*
    
    FROM headless AS final
    WORKDIR /app
    ADD docker-entrypoint.sh /docker-entrypoint.sh
    RUN chmod +x /docker-entrypoint.sh
    RUN dos2unix /docker-entrypoint.sh
    EXPOSE 9515
    ENV ELECTRON_ENABLE_STACK_DUMPING=true
    ENV ELECTRON_ENABLE_LOGGING=true
    ENTRYPOINT [ "/docker-entrypoint.sh" ]

With `docker-entrypoint.sh` as this:

    #!/bin/bash
    
    echo "Starting Xvfb"
    Xvfb :99 -ac &
    sleep 2
    
    export DISPLAY=:99
    export ELECTRON_SPECTRON_HEADLESS=true
    echo "Executing command $@"
    
    exec "$@"

Basically, I'm using _xvfb_ to facilitate headless E2E testing of an Electron app. It's actually used in combination with other Docker images for a database and a web server backend, but the problem can be reproduced without the test infrastructure by simply trying to run this command to start Electron in Docker:

    docker run -v C:\Users\Georg\Git\myappuidirectory:/app/src --rm dockertag:dev sh -c "cd src && npx electron --no-sandbox --headless --whitelisted-ips= ."

Which outputs the following error message to the console and then exits:

        > docker run -v C:\Users\Georg\Git\myappuidirectory:/app/src --rm dockertag:dev sh -c "cd src && npx electron --no-sandbox --headless --whitelisted-ips= ."

    Starting Xvfb
    Executing command sh -c cd src && npx electron --no-sandbox --headless --whitelisted-ips= .
    Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
    [26:1212/204738.841170:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
    [26:1212/204738.863172:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
    Received signal 11 SEGV_MAPERR 000000000000
    #0 0x558051111979 (/app/src/node_modules/electron/dist/electron+0x3faa978)
      r8: 0000000000000001  r9: 0000000000000010 r10: 000000000000009b r11: 0000000000000136
     r12: 000010c1ef3db780 r13: 00007ffd9bb25601 r14: 000010c1ef689730 r15: 000010c1ef689720
      di: 0000000000000000  si: 0000000000000000  bp: 00007ffd9bb25410  bx: 0000000000000000
      dx: 000010c1ef3db788  ax: 0000000000000000  cx: 0000000000000000  sp: 00007ffd9bb253c0
      ip: 0000558053db9f1c efl: 0000000000010246 cgf: 002b000000000033 erf: 0000000000000004
     trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
    [end of stack trace]
    Calling _exit(1). Core file will not be generated.
    [51:0100/000000.868710:ERROR:angle_platform_impl.cc(43)] Display.cpp:805 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
    [51:0100/000000.877907:ERROR:gl_surface_egl.cc(773)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
    [51:0100/000000.877924:ERROR:gl_surface_egl.cc(1322)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
    [51:0100/000000.878008:ERROR:angle_platform_impl.cc(43)] Display.cpp:805 (initialize): ANGLE Display::initialize error 12289: glXQueryExtensionsString returned NULL
    [51:0100/000000.878025:ERROR:gl_surface_egl.cc(773)] EGL Driver message (Critical) eglInitialize: glXQueryExtensionsString returned NULL
    [51:0100/000000.878036:ERROR:gl_surface_egl.cc(1322)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
    [51:0100/000000.878044:ERROR:gl_initializer_linux_x11.cc(160)] GLSurfaceEGL::InitializeOneOff failed.

The latter part looks like some GUI initialization errors, so we can append the `--disable-gpu` argument and shrink the error message down to this:

    
    > docker run -v C:\Users\Georg\Git\myappuidirectory:/app/src --rm dockertag:dev sh -c "cd src && npx electron --no-sandbox --headless --whitelisted-ips= --disable-gpu ."

    Starting Xvfb
    Executing command sh -c cd src && npx electron --no-sandbox --headless --whitelisted-ips= --disable-gpu .
    Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
    [27:1212/205019.170968:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
    [27:1212/205019.190038:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
    Received signal 11 SEGV_MAPERR 000000000000
    #0 0x563fb54cf979 (/app/src/node_modules/electron/dist/electron+0x3faa978)
      r8: 0000000000000001  r9: 0000000000000010 r10: 000000000000009b r11: 0000000000000136
     r12: 000006664f532780 r13: 00007ffe91abff01 r14: 000006664f6756d0 r15: 000006664f6756c0
      di: 0000000000000000  si: 0000000000000000  bp: 00007ffe91abfd40  bx: 0000000000000000
      dx: 000006664f532788  ax: 0000000000000000  cx: 0000000000000000  sp: 00007ffe91abfcf0
      ip: 0000563fb8177f1c efl: 0000000000010246 cgf: 002b000000000033 erf: 0000000000000004
     trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
    [end of stack trace]
    Calling _exit(1). Core file will not be generated.

### Additional Information

I'm way out of my comfort zone with this one😀 I'm a Windows guy, just using Docker for E2E tests and hosting, so I've got very little actual Linux experience.
I'm not sure what the error actually is, and would be very grateful if I could be pointed in the right direction.

I've searched extensively for the last few days, and have found very few resources about running Electron headless via Docker, so I failed to find any examples using the most recent version.

Initially, the problem surfaced in my CI pipeline when trying to run Docker E2E tests via Spectron in the container. There, the output basically came from Spectron stating that the Electron process unexpectedly exited. However, I'm suspecting that when we manage to get Electron itself running, Spectron should probably work, too.

**Comment by ELR12** [comment]
Just by taking a quick glance at your error output, the first thing I'd troubleshoot is making sure this directory is located on your Linux machine (it seems that it's not created on your machine and this is why an error is being thrown):  ``` /var/run/dbus/system_bus_socket ```

**Comment by GeorgDangl** [comment]
Hey @ELR12, thank you very much for the input!

I've been able to install `dbus` in the Docker image and start it. It's still not working, but the error output in the log is shrinking😀 Now it seems to find the file, but still fails to connect to the bus:

    Starting Xvfb
    Executing command sh -c mkdir -p /var/run/dbus && dbus-daemon --config-file=/usr/share/dbus-1/system.conf --print-address && cd src && npx electron --no-sandbox --headless --whitelisted-ips= --disable-gpu .
    unix:path=/var/run/dbus/system_bus_socket,guid=4214ee941babe578c4b1a6cc5fd622d1
    [33:1213/141858.113009:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
    Received signal 11 SEGV_MAPERR 000000000000
    #0 0x55aea13a0979 (/app/src/node_modules/electron/dist/electron+0x3faa978)
      r8: 0000000000000001  r9: 0000000000000010 r10: 000000000000009b r11: 0000000000000136
     r12: 000030c4c9812780 r13: 00007ffca22ecd01 r14: 000030c4c9b99be0 r15: 000030c4c9b99bd0
      di: 0000000000000000  si: 0000000000000000  bp: 00007ffca22ecb60  bx: 0000000000000000
      dx: 000030c4c9812788  ax: 0000000000000000  cx: 0000000000000000  sp: 00007ffca22ecb10
      ip: 000055aea4048f1c efl: 0000000000010246 cgf: 002b000000000033 erf: 0000000000000004
     trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
    [end of stack trace]
    Calling _exit(1). Core file will not be generated.

**Comment by vladimiry** [comment]
Maybe try to trigger the dbus by `eval $(dbus-launch --sh-syntax)`-like shell command.

**Comment by GeorgDangl** [comment]
Hey @vladimiry,

thank you, too, for the input!
Unfortunately, that doesn't solve it either. I've added the `NO_AT_BRIDGE=1` environment variable and ensured that dbus is running, but the error message stays the same:

    docker run -v C:\Users\Georg\myappdir:/app/src --rm mydockername:dev sh -c "mkdir -p /var/run/dbus && dbus-uuidgen --ensure && dbus-daemon --config-file=/usr/share/dbus-1/system.conf --print-address && cd src && npx electron --no-sandbox --headless --whitelisted-ips= --disable-gpu ."
    
	Starting Xvfb
    Executing command sh -c mkdir -p /var/run/dbus && dbus-uuidgen --ensure && dbus-daemon --config-file=/usr/share/dbus-1/system.conf --print-address && cd src && npx electron --no-sandbox --headless --whitelisted-ips= --disable-gpu .
    unix:path=/var/run/dbus/system_bus_socket,guid=08cd49447c6ef83002d4b05d5fd66a86
    [35:1213/192454.744219:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
    Received signal 11 SEGV_MAPERR 000000000000
    #0 0x56100fdb6979 (/app/src/node_modules/electron/dist/electron+0x3faa978)
      r8: 0000000000000001  r9: 0000000000000010 r10: 000000000000009b r11: 0000000000000136
     r12: 00003e9f63120780 r13: 00007ffd1ff90c01 r14: 00003e9f63494e20 r15: 00003e9f63494e10
      di: 0000000000000000  si: 0000000000000000  bp: 00007ffd1ff90a40  bx: 0000000000000000
      dx: 00003e9f63120788  ax: 0000000000000000  cx: 0000000000000000  sp: 00007ffd1ff909f0
      ip: 0000561012a5ef1c efl: 0000000000010246 cgf: 002b000000000033 erf: 0000000000000004
     trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
    [end of stack trace]
    Calling _exit(1). Core file will not be generated.

I'm really at a loss here...  
However, there's a budget available to fix that, so if there's someone who has a working E2E setup I'd be very glad to get some help in fixing this.

**Comment by nmeisenzahl** [comment]
Hey @GeorgDangl,

based on `Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
Received signal 11 SEGV_MAPERR 000000000000` I assume that the process does not know where to find the socket.
 
Maybe you can try to export it upfront:
`export DBUS_SYSTEM_BUS_ADDRESS='unix:path=/var/run/dbus/system_bus_socket'`

**Comment by GeorgDangl** [comment]
Hey @nmeisenzahl, thank you for the input! That still doesn't solve it, unfortunately. But if I set both of these exports, the warnings regarding the bus stop:

    export DBUS_SYSTEM_BUS_ADDRESS='unix:path=/var/run/dbus/system_bus_socket'
    export DBUS_SESSION_BUS_ADDRESS='unix:path=/var/run/dbus/system_bus_socket'

However, I just launched Electron on a bare metal server with Ubuntu 18.04, which gave me the same error output:

    npx electron --no-sandbox --headless --disable-gpu --disable_splash_screen .

    Received signal 11 SEGV_MAPERR 000000000000
    #0 0x55bb88856009 (/myappdirectory/node_modules/electron/dist/electron+0x3fb7008)
      r8: 0000000000000001  r9: 00007fff093a28a8 r10: 0000000000000300 r11: 00007fff093a29fc
     r12: 00001ba87ce8f780 r13: 00007fff093a2901 r14: 00001ba87d6f8a00 r15: 00001ba87d6f89f0
      di: 0000000000000000  si: 0000000000000000  bp: 00007fff093a2760  bx: 0000000000000000
      dx: 00001ba87ce8f788  ax: 0000000000000000  cx: 0000000000000000  sp: 00007fff093a2710
      ip: 000055bb8b5902ec efl: 0000000000010246 cgf: 002b000000000033 erf: 0000000000000004
     trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
    [end of stack trace]
    Calling _exit(1). Core file will not be generated.

However, I noticed that Electron can start when I remove the `--headless` argument. So, I just removed the `--headless` argument and the CI pipeline just finished the build, all green and the E2E tests ran successfully. I was worrying for two weeks about this, and it was just a single line to remove😀

Thank you all for the input!

Further info:
In my testing, I could start Chromium with the `--headless` command, but not Electron. So I'll leave this issue open until we know more about why we're getting this error.

**Comment by GeorgDangl** [comment]
Another bit of info: This issue seems to not be related to my project setup, I've received the same error when I just tried https://github.com/electron/electron-quick-start.

**Comment by ckerr** [comment]
@GeorgDangl I agree with your comment from https://github.com/electron/electron/issues/26974#issuecomment-744522412 about just running it without `--headless` -- if you've got xvfb running it shouldn't be necessary, and AFAIK running `--headless` isn't not a common use case for Electron.

In fact as per discussion with @jkleinsc we may want to consider removing the argument from Electron to remove the implication that we support it?

**Comment by jkleinsc** [comment]
Electron does not support `--headless`.
