### ISSUE TITLE
Cannot create a GN build config

### ISSUE THREAD

**Issue by lydev** [electron/electron#26976]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * git pull from master branch with HEAD at b41866ba4feab4c5b1a778b9bf54b47a8b4ea0c0.
* **Operating System:**
  * Win10 x64 1909
* **Last Known Working Electron version:**
  * 

### Expected Behavior
Running "gn gen --ide=vs2019 out\my-First-Electron-Build" should create a x64 debug build config for me.

### Actual Behavior
Running "gn gen --ide=vs2019 out\my-First-Electron-Build" and gets below error:

ERROR at //electron/BUILD.gn:318:1: Dependency not allowed.
source_set("electron_lib") {
^----------------------------
The item //electron:electron_lib
can not depend on //third_party/webrtc/modules/desktop_capture:desktop_capture
because it is not in //third_party/webrtc/modules/desktop_capture:desktop_capture's visibility list: [
  //third_party/webrtc/*
  //third_party/webrtc_overrides/*
]

### To Reproduce
Just run "gn gen --ide=vs2019 out\my-First-Electron-Build".

**Comment by codebytere** [comment]
@lydev please use [`build-tools`](https://github.com/electron/build-tools) and report further issues there.
