### ISSUE TITLE
electron-v9.0.5-win32-ia32 version   crash

### ISSUE THREAD

**Issue by wanghua2717** [electron/electron#26981]
FAULTING_IP: 
KERNELBASE+1144c2
750844c2 8b4c2454        mov     ecx,dword ptr [esp+54h]

EXCEPTION_RECORD:  ffffffff -- (.exr 0xffffffffffffffff)
ExceptionAddress: 750844c2 (KERNELBASE+0x001144c2)
   ExceptionCode: e0000008
  ExceptionFlags: 00000001
NumberParameters: 1
   Parameter[0]: 00000000

DEFAULT_BUCKET_ID:  WRONG_SYMBOLS

PROCESS_NAME:  WeLink.exe

ADDITIONAL_DEBUG_TEXT:  
Use '!findthebuild' command to search for the target build information.
If the build information is available, run '!findthebuild -s ; .reload' to set symbol path and load symbols.

MODULE_NAME: WeLink

FAULTING_MODULE: 77710000 ntdll

DEBUG_FLR_IMAGE_TIMESTAMP:  5ef0f577

ERROR_CODE: (NTSTATUS) 0xe0000008 - <Unable to get error code text>

EXCEPTION_CODE: (NTSTATUS) 0xe0000008 - <Unable to get error code text>

EXCEPTION_PARAMETER1:  00000000

FAULTING_THREAD:  00004b90

PRIMARY_PROBLEM_CLASS:  WRONG_SYMBOLS

BUGCHECK_STR:  APPLICATION_FAULT_WRONG_SYMBOLS

LAST_CONTROL_TRANSFER:  from 02ae370d to 750844c2

STACK_TEXT:  
WARNING: Stack unwind information not available. Following frames may be wrong.
00cfca2c 02ae370d e0000008 00000001 00000001 KERNELBASE+0x1144c2
00cfca48 0210a29f 00000000 00cfca5c 0210a148 WeLink!base::internal::OnNoMemoryInternal+0x1d [C:\projects\src\base\process\memory.cc @ 34]
00cfca54 0210a147 00cfca78 01848c7c 059d94cb WeLink!`anonymous namespace'::OnNoMemory+0xf [C:\projects\src\base\allocator\partition_allocator\oom.h @ 22]
00cfca5c 01848c7c 059d94cb 00000001 00cfeeb7 WeLink!blink::BlinkGCOutOfMemory+0x7 [C:\projects\src\third_party\blink\renderer\platform\heap\page_memory.cc @ 60]
00cfca78 01848c08 0d0b0df8 059d94cb 00000001 WeLink!v8::Utils::ReportOOMFailure+0x3c [C:\projects\src\v8\src\api\api.cc @ 516]
00cff194 0199a813 0d0b0df8 059d94cb 00000001 WeLink!v8::internal::V8::FatalProcessOutOfMemory+0x1e8 [C:\projects\src\v8\src\api\api.cc @ 475]
00cff1a8 019dbeaf 059d94cb 0d1c0000 1d83261c WeLink!v8::internal::Heap::FatalProcessOutOfMemory+0x13 [C:\projects\src\v8\src\heap\heap.cc @ 5646]
00cff1e0 019c95cc 544c00b9 00000064 00000000 WeLink!v8::internal::EvacuateNewSpaceVisitor::Visit+0x33f [C:\projects\src\v8\src\heap\mark-compact.cc @ 1415]
00cff298 019c925e 544c0000 0d12c9cd 1d832630 WeLink!v8::internal::LiveObjectVisitor::VisitBlackObjectsNoFail<v8::internal::EvacuateNewSpaceVisitor,v8::internal::MajorNonAtomicMarkingState>+0x2bc [C:\projects\src\v8\src\heap\mark-compact.cc @ 3289]
00cff300 019c8fc2 544c0000 00cff350 127f5e85 WeLink!v8::internal::FullEvacuator::RawEvacuatePage+0x15e [C:\projects\src\v8\src\heap\mark-compact.cc @ 3034]
00cff36c 019dd7bb 544c0000 00000000 63060090 WeLink!v8::internal::Evacuator::EvacuatePage+0x122 [C:\projects\src\v8\src\heap\mark-compact.cc @ 2946]
00cff3f0 019acafe 00000000 00cff408 00cff470 WeLink!v8::internal::PageEvacuationTask::RunInParallel+0x32b [C:\projects\src\v8\src\heap\mark-compact.cc @ 3091]
00cff400 019ace5e 654e7170 00cff538 00000001 WeLink!v8::internal::ItemParallelJob::Task::RunInternal+0xe [C:\projects\src\v8\src\heap\item-parallel-job.cc @ 35]
00cff470 019ca861 00cff4ec 00000002 0b0f0000 WeLink!v8::internal::ItemParallelJob::Run+0x24e [C:\projects\src\v8\src\heap\item-parallel-job.cc @ 81]
00cff508 019ca38b 0d12a680 00cff538 00000000 WeLink!v8::internal::MarkCompactCollectorBase::CreateAndExecuteEvacuationTasks<v8::internal::FullEvacuator,v8::internal::MarkCompactCollector>+0x261 [C:\projects\src\v8\src\heap\mark-compact.cc @ 3133]
00cff568 019baafb 0d12a680 0d0b5f90 00000000 WeLink!v8::internal::MarkCompactCollector::EvacuatePagesInParallel+0x15b [C:\projects\src\v8\src\heap\mark-compact.cc @ 3221]
00cff624 019b8a2f 00000017 0d0b5800 0d0b5800 WeLink!v8::internal::MarkCompactCollector::Evacuate+0x34b [C:\projects\src\v8\src\heap\mark-compact.cc @ 3356]
00cff640 0199a9ea 000810dc 000fb940 000ea3d0 WeLink!v8::internal::MarkCompactCollector::CollectGarbage+0xbf [C:\projects\src\v8\src\heap\mark-compact.cc @ 551]
00cff678 0199807c 01364d68 0d0b5800 00672008 WeLink!v8::internal::Heap::MarkCompact+0xda [C:\projects\src\v8\src\heap\heap.cc @ 2262]
00cff738 019965c7 00000001 00000040 0d0b7a28 WeLink!v8::internal::Heap::PerformGarbageCollection+0x4bc [C:\projects\src\v8\src\heap\heap.cc @ 2030]
00cff7d4 0199d7ac 00000002 00000009 00000040 WeLink!v8::internal::Heap::CollectGarbage+0x417 [C:\projects\src\v8\src\heap\heap.cc @ 1589]
00cff7f4 019a8842 00000009 0d0b5800 00000002 WeLink!v8::internal::Heap::FinalizeIncrementalMarkingIfComplete+0x8c [C:\projects\src\v8\src\heap\heap.cc @ 3433]
00cff854 02af73d7 61e12d80 00000000 0d05c7c0 WeLink!v8::internal::IncrementalMarkingJob::Task::RunInternal+0x192 [C:\projects\src\v8\src\heap\incremental-marking-job.cc @ 119]
00cff8c0 031a0ca6 05d95096 0d0ca868 00000000 WeLink!base::TaskAnnotator::RunTask+0xe7 [C:\projects\src\base\task\common\task_annotator.cc @ 142]
00cff944 031a09f1 00cff960 00cff968 00cff987 WeLink!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl+0xe6 [C:\projects\src\base\task\sequence_manager\thread_controller_with_message_pump_impl.cc @ 325]
00cff9a4 03194397 00cff9c0 01cff9d4 0d040830 WeLink!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork+0x91 [C:\projects\src\base\task\sequence_manager\thread_controller_with_message_pump_impl.cc @ 250]
00cff9e4 031a12a6 0d04997c 00cffa48 ffffffff WeLink!base::MessagePumpDefault::Run+0x57 [C:\projects\src\base\message_loop\message_pump_default.cc @ 41]
00cffa14 02ae6136 00000001 ffffffff 7fffffff WeLink!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run+0xf6 [C:\projects\src\base\task\sequence_manager\thread_controller_with_message_pump_impl.cc @ 437]
00cffa60 0307e7d1 00f93494 0d03f501 00cffa68 WeLink!base::RunLoop::Run+0x176 [C:\projects\src\base\run_loop.cc @ 126]
00cffb1c 021ea507 00cffb50 0d03eaf0 00cffb64 WeLink!content::RendererMain+0x2a1 [C:\projects\src\content\renderer\renderer_main.cc @ 227]
00cffb34 021eab6d 00cffb64 00cffb50 00cffce8 WeLink!content::RunOtherNamedProcessTypeMain+0x68 [C:\projects\src\content\app\content_main_runner_impl.cc @ 555]
00cffb80 017bf983 00000000 00000003 00cffc74 WeLink!content::ContentMainRunnerImpl::Run+0xed [C:\projects\src\content\app\content_main_runner_impl.cc @ 882]
00cffb90 02f389fe 00cffc84 00000000 ffffffff WeLink!content::ContentServiceManagerMainDelegate::RunEmbedderProcess+0x13 [C:\projects\src\content\app\content_service_manager_main_delegate.cc @ 52]
00cffc74 017c009b 00cffc80 00cffc84 0599ba70 WeLink!service_manager::Main+0x3e6 [C:\projects\src\services\service_manager\embedder\main.cc @ 454]
00cffcb4 00e7132b 00cffccc 0b14d438 00000000 WeLink!content::ContentMain+0x33 [C:\projects\src\content\app\content_main.cc @ 19]
00cffd50 05731a5a 00e70000 00000000 0b1121f0 WeLink!wWinMain+0x21d [C:\projects\src\electron\shell\app\electron_main.cc @ 210]
00cffd9c 75de6359 00beb000 75de6340 00cffe08 WeLink!__scrt_common_main_seh+0xf8 [d:\agent\_work\4\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 288]
00cffdac 77777c24 00beb000 86a46c19 00000000 kernel32+0x16359
00cffe08 77777bf4 ffffffff 77798fe4 00000000 ntdll+0x67c24
00cffe18 00000000 05731ae0 00beb000 00000000 ntdll+0x67bf4

FOLLOWUP_IP: 
WeLink!base::internal::OnNoMemoryInternal+1d [C:\projects\src\base\process\memory.cc @ 34]
02ae370d ??              ???

SYMBOL_STACK_INDEX:  1

SYMBOL_NAME:  WeLink!base::internal::OnNoMemoryInternal+1d

FOLLOWUP_NAME:  MachineOwner

IMAGE_NAME:  WeLink.exe

STACK_COMMAND:  ~47s; .ecxr ; kb

BUCKET_ID:  WRONG_SYMBOLS

FAILURE_BUCKET_ID:  WRONG_SYMBOLS_e0000008_WeLink.exe!base::internal::OnNoMemoryInternal

WATSON_STAGEONE_URL:  http://watson.microsoft.com/StageOne/WeLink_exe/0_1_0_0/5ef0f577/KERNELBASE_dll/10_0_18362_1049/c4675baa/e0000008/001144c2.htm?Retriage=1

Followup: MachineOwner
---------

i dont known how to fix it ,does anyone can help me ？

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by nornagon** [comment]
This is an out of memory crash, btw.
