### ISSUE TITLE
Developer tools console autocomplete broken in Electron 11+

### ISSUE THREAD

**Issue by lishid** [electron/electron#26980]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.0.0-11.1.0
* **Operating System:**
  * Windows 10 1909
* **Last Known Working Electron version:**
  * 10.2.0

- Auto-suggestion box keeps suggesting `window` after typing `.`
- No suggestions for anything after `.`
- If you press ESC, then you will never have auto suggestion again, unless you clear and start over.
- Auto-type (grey'd out ghost characters you can press `tab` to choose) no longer available after `.`

### Expected Behavior (Recorded in v10.2.0)
![test](https://user-images.githubusercontent.com/609710/102037168-8886fe80-3d92-11eb-94fb-d16b38ba86b1.gif)

### Actual Behavior (Recorded in v11.0.0)

![test](https://user-images.githubusercontent.com/609710/102037058-465dbd00-3d92-11eb-9be1-1c5348cf9795.gif)

### Additional Information

Developer tools console works fine in Chrome 87.0.4280.88

**Comment by ilyagelman** [comment]
Same issue on macOS (Big Sur on Intel processor)

**Comment by nornagon** [comment]
Bisected to https://github.com/electron/electron/compare/v11.0.0-nightly.20200721...v11.0.0-nightly.20200723

**Comment by lishid** [comment]
Upon further investigation, it seems that the debugger is also broken. I believe it's related but it's also possible it's unrelated. Let me know if I should file a separate issue for this.

### Scope variables don't show up.

Expected (Chrome):
![image](https://user-images.githubusercontent.com/609710/102717777-83561200-42b2-11eb-804e-d181438f51e4.png)

Broken (Electron v11):
![image](https://user-images.githubusercontent.com/609710/102717992-a503c900-42b3-11eb-94bf-901be5967cc3.png)


### Additionally, these are also broken in Electron v11, severely limiting the debugging experience

Hover over variables in Chrome:
![image](https://user-images.githubusercontent.com/609710/102717835-db8d1400-42b2-11eb-956a-08955e3d25f9.png)

Execute line by line and see inline variable contents in Chrome:
![image](https://user-images.githubusercontent.com/609710/102717911-37f03380-42b3-11eb-84f0-66292876870a.png)

**Comment by MarshallOfSound** [comment]
Fixed in #27102
