### ISSUE TITLE
Can "@electron/remote" package be used safely in the long run?

### ISSUE THREAD

**Issue by gmantri** [electron/electron#27008]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.1.0
* **Operating System:**
  * macOS Big Sur
* **Last Known Working Electron version:**
  * 6.0.1

Not technically a bug report but there was no option to ask for clarification questions hence asking it here.

I have a working application that is currently using Electron version 6.0.1 and I am in the process of migrating it to use Electron version 11 (yeah, I know ... late to the party). One of the biggest stumbling block is the removal of `remote` in renderer process. Read [Deprecate the 'remote' module and move it to userland](https://github.com/electron/electron/issues/21408) for reasoning and comments. I may not 100% agree with the reasoning but there's no point arguing about it as the decision has already been made.

From what I understand, there are two ways to go about it:

1. Change the existing code and use IPC to make use of things that are now only available in main process (like menu, dialog, browser windows etc.).
2. Use @electron/remote package.

Unfortunately option 1 is not a viable option for us for many reasons. Ours is a pretty complex application (I think) with lots of context menus and dialogs (including browser windows) spread throughout the application and switching to IPC would not only bloat our main.js file but also will complicate application code in order to handle messages exchanged between main and renderer process via IPC.

That leaves us with option option 2 (BTW, thank you for giving this as an option). I have looked through the documentation and it looks like a better option than option 1 with considerably lesser code changes (at least in our case).

What is not clear to me is if using this package is a stop-gap arrangement and somewhere down the road this package will be deprecated/unsupported and we have to use option 1.

So my questions are:

1. Can "@electron/remote" package be used safely in the long run without worrying about making the changes again in the short run (say in next 12 months)?

2. I am also curious about how the community is dealing with this change. Are they rewriting their applications to make use of IPC or are they modifying their applications to make use of this package?

Any insights will be highly appreciated.

**Comment by nornagon** [comment]
There is no plan to remove `@electron/remote`. It will remain usable for as long as there are people interested in maintaining it.

However, note that it poses the exact same security and performance issues that `remote` has. My recommendation remains that you refactor away from using `remote`.
