### ISSUE TITLE
What's the documented way to delete a session created with fromPartition with persistence?

### ISSUE THREAD

**Issue by josephernest** [electron/electron#27018]
Thanks to https://github.com/electron/electron/blob/master/docs/api/session.md, I use 

    sess = session.fromPartition('persist:sessionD76Z687AX789W', { cache: true });

which creates a directory

    C:\Users\User\AppData\Roaming\<electron-app-name>\Partitions\sessionD76Z687AX789W

What is the appropriate way to **delete such a session** and remove this directory when, say, 10 days later, we don't need it anymore?

I tried [`clearCache()`](https://github.com/electron/electron/blob/master/docs/api/session.md#sesclearcache) but it does not remove this dir.

Or should we manually access the filesystem and delete this directory and its subdirectories with this method [Remove directory which is not empty](https://stackoverflow.com/a/32197381/1422096)?

The latter would be a little-bit a hack...

**Comment by ckerr** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by josephernest** [comment]
Thank you for your answer. I think this can be catalogued as 'feature
request' because there seems to be no documented way to achieve this
correctly.

Can I set the issue label myself, or is it you who have to do it?

**Comment by josephernest** [comment]
Thank you for your answer. I think this should be catalogued as 'feature request' because there seems to be no documented way to achieve this correctly.

Can I set the issue label myself, or is it you who have to do it @ckerr?

**Comment by josephernest** [comment]
@ckerr I've already looked on https://www.electronjs.org/community, and also discussed it in the past in the Discord channel.

Since this undocumented feature would be helpful, can we reopen this issue?

As mentioned on https://www.electronjs.org/community:

> Request features by opening issues on the electron/electron repository.
