### ISSUE TITLE
setBounds does not ignore minWidth/minHeight values on Mac

### ISSUE THREAD

**Issue by johnnybenson** [electron/electron#27025]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10, 11
* **Operating System:**
  * Mac
* **Last Known Working Electron version:**
  * Unknown

### Expected Behavior
The [docs](https://www.electronjs.org/docs/api/browser-window) indicate that it should be possible to programmatically apply a window size that is smaller than minimum values.

> When setting minimum or maximum window size with minWidth/maxWidth/ minHeight/maxHeight, it only constrains the users. It won't prevent you from passing a size that does not follow size constraints to setBounds/setSize or to the constructor of BrowserWindow.

### Actual Behavior
Calling `setBounds` or `setSize` with values smaller than minWidth / minHeight are ignored and the window is resized to the minimum value instead

### To Reproduce
[Electron Fiddle Gist](https://gist.github.com/fbf718aab630d3cfdeb9c37e42a269ad)

Fiddle attempts to resize the window smaller than minWidth/minHeight

### Screenshots
N/A

### Additional Information
The behavior appears to work as expected on Windows

**Comment by coryellcp** [comment]
the same behavior manifests when using setSize() as well.

**Comment by YXDay** [comment]
the same behavior with 13.6.3，Is there any new progress？

**Comment by pushkin-** [comment]
That seems to be the case based on [this PR](https://github.com/electron/electron/pull/6363). So I think the docs just need to be cleaned up. though this is sad :(
