### ISSUE TITLE
<audio> not playing from redirected url

### ISSUE THREAD

**Issue by zarubond** [electron/electron#27020]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

If the audio tag has src URL which redirects with "Location" header to actual file, the sound it not played. I can see in the devtools that the file is downloaded and I see that it is loaded because it reports a track length. When I input the redirected URL directly it works fine. It just does not produce any sound when it is redirected. I have also tested it in Chrome where it works fine.

* **Electron Version:**
 Electron 8.5.3 and any after that
* **Operating System:**
Windows 10
* **Last Known Working Electron version:**
8.5.2

### Expected Behavior
Should output sound

### Actual Behavior
Everything works except no sound is produced.

### To Reproduce
Create an audio tag which points to file which has a redirect with "Location" http header.

**Comment by nornagon** [comment]
The version of Electron you're using is [no longer supported](https://www.electronjs.org/docs/tutorial/support#currently-supported-versions).

This was fixed in Electron 9 here: https://github.com/electron/electron/pull/26969

**Comment by alexeykuzmin** [comment]
@nornagon, the commit you cherry-picked in #26969 ([5dc1b1bc](https://chromium.googlesource.com/chromium/src/+/5dc1b1bce3d19309b937af96723584351186bead)) seems to be only [present in Chromium 86+](https://storage.googleapis.com/chromium-find-releases-static/5dc.html#5dc1b1bce3d19309b937af96723584351186bead), it mean that Electron 10 is still affected. Shouldn't the fix be backported to `10-x-y` too?

**Comment by nornagon** [comment]
@alexeykuzmin see https://github.com/electron/electron/pull/26963
