### ISSUE TITLE
BrowserWindow title set to window name by default (from window.open(url, name))

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#27036]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
* **Electron Version:** Electron 11, 10
* **Operating System:** Windows 10
* **Last Known Working Electron version:** 9.4.0

### Expected Behavior
I expect that the window name doesn't get set into the title

### Actual Behavior
When opening windows via window.open passing in a window name, the title of the window gets defaulted to the window name.

*edit by @ckerr*: since this ticket's caused a little confusion, to restate this: Calling something like `window.open("https://example.com/", "aaa")` creates a window with a default title that is replaced with the real title when example.com's html is parsed and its `<title>` is used. Electron 10 introduced a change where that default title is the window.open() windowName parameter (`aaa` in the example). According to the [window.open() documentation](https://developer.mozilla.org/en-US/docs/Web/API/Window/open#parameters) this parameter "will NOT be used as the window's title", so Electron is in error by using it as the default title.

### To Reproduce
1. npm start -> main.js
2. click "Open Window"
3. Observe that the window title gets set to the window name ("aaa") before being replaced with the <title> of the web page. This didn't used to happen

main.js:
```
const { app, BrowserWindow } = require('electron')

function createWindow() {
  const mainWindow = new BrowserWindow({
    webPreferences: {
      nodeIntegration: true,
      nativeWindowOpen: true
    }
  })

  mainWindow.loadFile('index.html')

  mainWindow.webContents.on("new-window", (e, url, f, d, op) => {
    console.log(op.title);
  })
}

app.whenReady().then(() => {
  createWindow()
})

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})
```

index.html:
```
<!DOCTYPE html>
<html>

<body>
  <button id="b">Open window</button>
  <script src="./renderer.js"></script>
</body>

</html>
```

renderer.js:
```
document.getElementById("b").onclick = () => {
    window.open("https://google.com", "aaa");
};
```

**Comment by pushkin-** [comment]
Looks like this was caused by [this commit](https://github.com/electron/electron/pull/23130/commits/498f9db4b65b293d8173cc0667e11fe43b823639)

**Comment by ckerr** [comment]
gist form of testcase: https://gist.github.com/ckerr/60e0abec2f1dc3f92127b875b8c2393e
