### ISSUE TITLE
window.open - default options.x/y are no longer set when opening from BrowserView. Used to be set to 0

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#27051]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 11
* **Operating System:** Windows 10
* **Last Known Working Electron version:** 9 (possibly in 10 too)

### Expected Behavior
I expect that windows opened by window.open will always have x/y coordinates defined.

### Actual Behavior
x/y are undefined.

### To Reproduce
Seems caused by [this PR](https://github.com/electron/electron/pull/23130).

It used to be that when opening windows from a BrowserView, options.x/y were set to 0. Now, they're not set at all.

1. npm start the below app
2. click the open window button
3. notice the log. x/y are undefined. They used to be 0. This doesn't seem to happen when opening directly from a BrowserWindow instead of from a BrowserView

main.js:
```
const {app, BrowserWindow, BrowserView} = require('electron')

function createWindow () {
  const mainWindow = new BrowserWindow({
    webPreferences: {
      nativeWindowOpen: true,
      nodeIntegration: true
    }
  })

  const v = new BrowserView({
    webPreferences: {
      nativeWindowOpen: true,
      nodeIntegration: true
    }
  });
  mainWindow.setBrowserView(v);

  const bounds = mainWindow.getContentBounds();
  v.setBounds({ x: 0, y: 0, width: bounds.width, height: bounds.height });
	v.setAutoResize({ width: true, height: true });

  v.webContents.loadFile('index.html')

  v.webContents.on("new-window", (e, url, framename, disp, options) => {
    console.log(`x: ${options.x}, y: ${options.y}`)
  });
}

app.whenReady().then(() => {
  createWindow()
})

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})
```

index.html:
```
<!DOCTYPE html>
<html>
  <body>
    <button id="b">Open Window</button>

    <script src="./renderer.js"></script>
  </body>
</html>
```

renderer.js:
```
document.getElementById("b").onclick = () => {
	window.open("https://google.com");
};
```

**Comment by nornagon** [comment]
Hm, I think the new behavior is better. It more clearly preserves what was specified by the `window.open` call: passing `"left=0,top=0"` in the 3rd argument to `window.open` results in the x/y values being 0 as before.

**Comment by pushkin-** [comment]
@nornagon Yeah I guess I don't necessarily mind. I wanted to report it since I noticed the change and wanted to make sure it was intentional. My code started crashing, because of some assumptions I was making, but I can easily fix it on my end. Feel free to close it if you want.

**Comment by nornagon** [comment]
Alright. It's kind of an obscure case so I'm not sure it makes sense to list it in breaking-changes. I'll close this out.
