### ISSUE TITLE
[Big Sur] Transpearent Window Corners

### ISSUE THREAD

**Issue by moloch--** [electron/electron#27061]
### Issue Details

Possibly related to https://github.com/electron/electron/issues/24319 and https://github.com/electron/electron/pull/24642

* **Electron Version:**
  * v11.1.0
* **Operating System:**
  * MacOS 11.1 (20C69)

### Expected Behavior

Platform normalized corners

### Actual Behavior

The corners of the window are off by a few pixels

### To Reproduce

```javascript
    return new BrowserWindow({
      titleBarStyle: 'hidden',
      transparent: true,
      hasShadow: true,
      vibrancy: 'ultra-dark',
    });
```

### Screenshots

<img width="141" alt="Screen Shot 2020-12-16 at 10 34 13 PM" src="https://user-images.githubusercontent.com/875022/102444569-20812400-3fef-11eb-8eab-3a00d50da2c9.png">

<img width="674" alt="Screen Shot 2020-12-16 at 10 39 54 PM" src="https://user-images.githubusercontent.com/875022/102444806-aac98800-3fef-11eb-9366-0ac59c05fa6e.png">

**Comment by Xiphe** [comment]
can confirm this with
```ts
new BrowserWindow({
  titleBarStyle: 'hiddenInset',
  vibrancy: 'sidebar',
});
```

**Comment by EriKWDev** [comment]
It seems like VSCode does not have this issue. Are they doing something special there?

**Comment by HelipengTony** [comment]
> It seems like VSCode does not have this issue. Are they doing something special there?

Probably because they don't use transparent window. Window corners are rounded properly if you set vibrancy option to false.

**Comment by inukshuk** [comment]
Big Sur uses a different corner radius, so my guess is that [the hard-coded corner radius for this mask here](https://github.com/electron/electron/blob/master/shell/browser/native_window_mac.mm#L1274) is causing this.

**Comment by davej** [comment]
> Big Sur uses a different corner radius, so my guess is that [the hard-coded corner radius for this mask here](https://github.com/electron/electron/blob/master/shell/browser/native_window_mac.mm#L1274) is causing this.

Looks like you're right.

I guess a quick fix would be to detect OS and hardcode the correct radius for Big Sur. A better fix would be to use an API to request the corner radius from the OS (I'm not sure if that API exists though).

**Comment by KishanBagaria** [comment]
Will something like this work:

```objc
if (@available(macOS 11, *)) {
  CGFloat radius = 9.0f;
} else {
  CGFloat radius = 5.0f;
}
```
