### ISSUE TITLE
WebContents leaks after destroying it

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#27071]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 11, 10, 9
* **Operating System:** Windows 10

### Expected Behavior
I expect that a WebContents instance is garbage collected after destroying it.

### Actual Behavior
WebContents sticks around

### To Reproduce
1. put a breakpoint at `console.log(wcs)`
2. Start main.js
3. Click the "open window" button. This will create a window with a BrowserView in it. The BrowserView's WebContents will be stored in a WeakMap. (maybe we can repro without the BrowserView, but this mimics my original code that exposed this)
4. Close the window. The close code will destroy the webcontents
5. After some time, you can click the "Check..." button to hit your breakpoint.
6. Inspecting the `wcs` structure reveals that the webcontents entries are still there.  (I've waited at least 10 minutes and they are still not garbage collected)

main.js:
```
const { app, BrowserWindow, BrowserView, ipcMain } = require('electron')

const wcs = new WeakMap();
const webContentsIds = {};

function createWindow() {
    const mainWindow = new BrowserWindow({
        webPreferences: {
            nativeWindowOpen: true,
            nodeIntegration: true
        }
    });
    mainWindow.loadFile("index.html");

    handleNewWindows(mainWindow);

    ipcMain.on("checkWebcontents", () => {
      console.log(wcs);
    });
}

function handleNewWindows(mainWindow) {
  mainWindow.webContents.on("new-window", (e, url, frameName, disposition, options) => {
    e.preventDefault();

    const win = new BrowserWindow(options);
    e.newGuest = win;

    // create BrowserView
    const bv = new BrowserView({ 
      webPreferences: {
        sandbox: true
      }
    })

    win.setBrowserView(bv);
    const bounds = win.getContentBounds();
    bv.setBounds({x: 0, y: 0, width: bounds.width, height: bounds.height});

    wcs.set(bv.webContents, true);
    webContentsIds[win.id] = bv.webContents.id;

    bv.webContents.loadURL(url);
  });

  app.on("browser-window-created", (e, win) => {
    win.on("close", () => {
      win.setBrowserView(null);
    });

    const windowId = win.id;
    win.on("closed", () => {
      const { webContents } = require("electron");

      const webContentsId = webContentsIds[windowId];
      const wc = webContents.fromId(webContentsId);
      if (wc) {
        wc.destroy();
      }

      delete webContentsIds[windowId];
    });
  });
}

app.on('ready', createWindow)
```

index.html:
```
<!DOCTYPE html>
<html>
  <body>
    <button id="openWindow">Open Window with BrowserView</button>
    <button id="check">Check if webcontents has been garbage collected</button>

    <script src="./renderer.js"></script>
  </body>
</html>
```

renderer.js:
```
const {ipcRenderer} = require("electron");

document.getElementById("openWindow").onclick = () => {
	window.open("https://google.com");
};

document.getElementById("check").onclick = () => {
	ipcRenderer.send("checkWebcontents");
}
```

**Comment by pushkin-** [comment]
I wonder if this is the same issue as [this](https://github.com/electron/electron/issues/21586)

**Comment by nornagon** [comment]
It looks to me like the issue is the same as https://github.com/electron/electron/issues/26929#issuecomment-772003008 — the WebContents is never explicitly destroyed (since it belongs to a BrowserView), so it sticks around. This doesn't happen for WebContents that belong to a BrowserWindow, because BrowserWindow forces cleanup of its associated WebContents on destruction: https://github.com/electron/electron/blob/b31217a889134620d0763e65d62ae1dc5f53c6fd/shell/browser/api/electron_api_browser_window.cc#L450

**Comment by pushkin-** [comment]
@nornagon I'm not really following what issue is mentioned in that comment - it sounds like it's just telling someone to call the `destroy` method.

But sure, if you're saying that when you add the `close` method, it will cleanup references, then I'm fine closing this.

**Comment by nornagon** [comment]
@pushkin- `BrowserView.destroy()` went away, but you still need to manually manage the lifetime of the WebContents, which currently is done by an undocumented method, `WebContents.destroy()`. I don't think BrowserView has ever automatically cleaned up after itself.

**Comment by pushkin-** [comment]
@nornagon yeah that's what I was saying. The comments seems to just say to call `webContents.destroy()`, which I'm doing above, but is still causing the leak. If the `close` method you're adding will fix the memory leak, we can close this issue.

**Comment by nornagon** [comment]
ah sorry, i missed that you were calling `destroy` in the example! this might be a different issue, then.

**Comment by nornagon** [comment]
🤔  I wonder if it's the inspector that's retaining a reference to the WebContents?

Without the inspector attached, I only see `WeakMap { <items unknown> }` in the console, so it's hard to tell whether or not there's anything in there.

Here's a gist version of your repro for easy Fiddle use: https://gist.github.com/6bc058538697314da3a4dc5f37ded335

**Comment by pushkin-** [comment]
@nornagon related issue [here](https://stackoverflow.com/questions/62502224/es6-console-log-on-weakset-gives-item-unknown)

**Comment by nornagon** [comment]
@pushkin- Ah, thanks, I can see the contents when calling `console.log(require('util').inspect(wcs, {showHidden: true}));`. 

However, the WebContents seems to be GC'd correctly. I added an explicit invocation of `gc()`, and the WeakMap shows as empty.

Here's an updated fiddle that shows the correct GC behavior: https://gist.github.com/5e8568100aa3aa4101956636eafa3c3c

**Comment by pushkin-** [comment]
@nornagon You're right. Seems like Node is holding on to the objects for some reason. Running from command line and calling `gc()` directly confirms that the objects get garbage collected. Thanks
