### ISSUE TITLE
Notification click callback called when pressing "Close"

### ISSUE THREAD

**Issue by raksooo** [electron/electron#27088]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.1.0
* **Operating System:**
  * Windows 10

### Expected Behavior
Notification click callback shouldn't be called when clicking the "Close"-button on notifications with `timeoutType: 'never'`.

### Actual Behavior
The callback is **sometimes** called.

### To Reproduce
test.js:
```
const { app, Notification } = require('electron');

app.whenReady().then(() => {
  const notification = new Notification({
    title: 'title',
    timeoutType: 'never',
  });
  notification.on('click', () => console.log('click'));
  notification.show();
});
```
Run this code a bunch of times and click the "close"-button each time.
```electron test.js```

Or use this Electron Fiddle gist:
https://gist.github.com/65507a116b68a5ab61663fe6aed22f08

### Additional Information
It doesn't happen every time the "close"-button is clicked, but for me it happens fairly often.

**Comment by marchaos** [comment]
Still present in electron 16.0.7

**Comment by raksooo** [comment]
This is still an issue in Electron 21.1.0. I reproduced it on Windows 11.
