### ISSUE TITLE
Globalshotcuts not working on fedora

### ISSUE THREAD

**Issue by haffoudhi** [electron/electron#27089]
We have installed our electronJs app on fedora 33.
the application have few globalshortcuts, that trigger other modules.
Issue: globalshortcuts work when app is on foreground, or with chrome only. When I open any text editor or firefox, my globalshortcuts does not trigger, but if I return my app to foreground, shortcuts are working.
We tried multiple virtual machines and physical machines. We have the same problem.
Does anyone know how to fix the problem?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

**Comment by haffoudhi** [comment]
globalshortcut is not working on fedora, is this not a bug?
I tried globalshortcut on other operating systems, it's working everywhere on the system, but not on fedora. globalshortcut is working as localshortcut, not working from other systems apps, such as text editor.
