### ISSUE TITLE
[Big Sur] window corners are not rounded when using vibrancy effects

### ISSUE THREAD

**Issue by dgmid** [electron/electron#27080]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11x
* **Operating System:**
  * macOS 11.1 [Big Sur]
* **Last Known Working Electron version:**
  * 

### Expected Behavior
when using BrowserWindow vibrancy effects eg: `vibrancy: 'sidebar'`, the corners of the window are squared.

### To Reproduce
Create a new BrowserWindow with vibrancy effects eg: `vibrancy: 'sidebar'`.

https://gist.github.com/262108f4d281d9aa780ecc18f7ade2ba

### Screenshots
<img width="454" alt="squared-corners" src="https://user-images.githubusercontent.com/1267580/102683285-fcc90400-41cf-11eb-84af-e379d4aba23b.png">

### Additional Information
Adding `titleBarStyle: 'hidden'` rounds the corners, but the corner radius is smaller that normal windows in Big Sur.
<img width="114" alt="small-radius" src="https://user-images.githubusercontent.com/1267580/102683360-b6c07000-41d0-11eb-9dac-59d882f38422.png">
Which seems to be the issue shown here: https://github.com/electron/electron/issues/27061

**Comment by will-stone** [comment]
I've tried many combinations of window settings and found the only way to remove the corner glitch is to use `titleBarStyle: 'customButtonsOnHover',`.

**Comment by dgmid** [comment]
@will-stone both `titleBarStyle: 'hidden'` and `titleBarStyle: 'customButtonsOnHover'` seem to get rid of the squared corner - but the corners still have the small corner radius of Mojave / Catalina instead of the larger corner radii of Big Sur.
Its annoying as the window background seems to have the proper radius - but the window border not, and so there is a strange transparent gap in each corner.

<img width="604" alt="corners" src="https://user-images.githubusercontent.com/1267580/102783733-ad373380-439b-11eb-88a0-0e18f1a6b7fd.png">

**Comment by jcarpenter** [comment]
Semi-related: am noticing pretty serious performance regressions using vibrancy under Big Sur (at least, I _think_ that was the trigger). 

* Perceived scrolling perf dropping to single digits, with lots of jank. 
* Stuttering CSS animations
* Event responsiveness

.... Etc. The Glasstron package also seems to be be [broken](https://github.com/AryToNeX/Glasstron/issues/54). 

Mentioning here as it seems to suggest widespread vibrancy problems w/ Electron + Big Sur.

**Comment by robin-fowler** [comment]
The corner radius Big Sur issue doesn't seem to happen when hasShadow: false. Perhaps related to the shadow?

**Comment by shatyuka** [comment]
That's because the shadow does not fit the window.
The round radius in Big Sur is larger than before, maybe this is the reason.

**Comment by philmorley** [comment]
Any updates on this?

**Comment by QuiiBz** [comment]
Having the same issue here, with `titleBarStyle` set to`hidden`.
<img width="142" alt="Screenshot 2021-03-16 at 14 45 17" src="https://user-images.githubusercontent.com/43268759/111319490-56718b00-8666-11eb-9fb6-58ca177ac5e9.png">

**Comment by acue** [comment]
Having the same issue still with all titleBarStyles. Only way I've found to get rid of it is turning `hasShadow: false` as described above but that has some obvious large downsides. 

Any update on this? Would be amazing to have usable vibrancy effects but this pretty much kills it for our app.

**Comment by KishanBagaria** [comment]
Feedback from one of our users:

<img width="634" alt="Screenshot 2021-04-06 at 1 50 14 PM" src="https://user-images.githubusercontent.com/1093313/113680921-045cdc00-96df-11eb-8bce-b3fd575991c3.png">

**Comment by gabrielecirulli** [comment]
Hello, this appears to still be an issue on Electron 13 on macOS Big Sur 11.4 (20F71).

**Comment by paulrosania** [comment]
We are seeing this too. It's intermittent -- a relaunch fixes it temporarily.

**Comment by 1zilc** [comment]
When the app is moved to another screen, window rectangle borders reappear
