### ISSUE TITLE
Electron menuItems created from standard roles are not responsive on Windows app tray menu

### ISSUE THREAD

**Issue by danielpm1982** [electron/electron#27093]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.0.3
* **Operating System:**
  * Windows 10 (20H2 19042.685 compilation)
* **Last Known Working Electron version:**
  * not applicable

### Expected Behavior
When clicked by the user, role-based tray menuItems, as those from Edit and View roles, should respond... even on Windows.

### Actual Behavior
For one same Menu object, created from a same MenuItemConstructorOptions array, 3 menu types have been created: a topBar standard menu, a right-click context-menu, and a tray menu. All three work fine on linux. But the tray menu menuItems, specifically the ones created from Electron roles (e.g. Edit and View), are unresponsive on Windows 10. The custom menuItems, created with click event listeners (instead of roles), work fine though. The top-bar menu as well as the right-click context-menu also work fine on Windows 10 (including their role menuItems). The problem is only with the tray menu role-based menuItems.

### To Reproduce
Just clone, install, compilate and start the app at:
https://github.com/danielpm1982/exchange-rate-client on Windows 10 and try to use Edit or View tray menus menuItems. On the README.md of the project I tell what project's scripts to use to run the app after cloning. They're different for Linux and Windows.

### Commands required to clone/install/run/package the app on Windows
```sh
$ git clone https://github.com/danielpm1982/exchange-rate-client.git
$ npm install
$ npm run tsc-compilate-project-win
$ npm run start
$ npm run package-win
```

### Screenshots
![c0t84](https://user-images.githubusercontent.com/5318273/102889487-84fe1200-4439-11eb-936a-2c13294c1bea.png)

### Additional Information
On Linux all works fine.
I've not tested on Mac.

**Comment by marc2332** [comment]
Might be related to https://github.com/electron/electron/issues/22797

**Comment by danielpm1982** [comment]
I created a minimum project that reproduces the same unresponsive behavior for tray menu role menuItems and a video test of 15MB showing how it works when on the standard topBar menu but not on the tray. On Linux ALL menu types work, including ALL role menuItems on the tray. On Windows almost none (only Exit role menuItem worked so far - I've not tested all possible roles menuItems yet). The same bug appeared until Electron v.7, at least.

Mininal test project:
https://github.com/danielpm1982/test-electron-role-menuItems.git

Use:
git clone <link above>
npm install
npm run start

Video test:
https://drive.google.com/file/d/1Sh35VJrwPrsMkeeCxGi4oeYimIhI9oj_/view?usp=drivesdk

**Comment by danielpm1982** [comment]
> 
> 
> Might be related to #22797

Yeah, it's the same issue, but that one only mention 1 role menuItem.

My issue states and shows on the code run, if tested, that the bug applies to basically ALL role menuItems I've tested so far (except Exit), if on Windows tray.

I'll later make a test with ALL roles to see which menuItems work and which don't.

Beyond toggleFullScreen, ALL menuItems from Edit and View are unresponsive on windows tray, although work on Linux and probably on mac.

But later I'll leave here the FULL LIST of what role menuItems work on Windows tray and which do not.

And then Electron team could leave it clear at the documentation any limitation in case this cannot be fixed for Windows.

**Comment by danielpm1982** [comment]
Haven't tested all role built menuItems yet, but the ones I tested on linux work if I click the tray icon with the window focused, but NOT if with windows unfocused. On linux the window doesn't lose focus when the tray icon is clicked, so you can click on the tray icon with or without the window focused. But this indicates it's a matter of focus. The role default event handlers work with the windows focused, but not with the windows unfocused (if I click the desktop area and only then on the tray icon).

On Windows, any windows ALWAYS lose focus when clicking on the tray icon or calling the role menuItem.  Even if I put a click event for getting the mainWindow focus right before the role, when it executes the focus is lost again.

MAYBE, at the internal implementation of the roles, it would be possible to get the focus of the last focused window, in order to the roles to be able to execute on it.

I managed to implement some of the unworking roles manually, only with Electron API, by creating custom menuItems and event handlers, including for zooming in and out, and setting a different zoomFactor for example, so that it worked on both Operating Systems. It proves it's possible to use these functionalities at the tray icon even on Windows.

Maybe something similar could be done with the internal implementation of the default roles, so that we could use these roles, Edit and View, for instance, both on linux/iOS and also on Windows at the tray icon, without having to implement manually each similar functionality. At the windows menu itself, these default roles are pretty functional on all systems. Only not at the Windows OS tray, and I guess because of lack of focus on the window we want as the target for that role action.
