### ISSUE TITLE
N-API `finalize_cb` never called for `napi_create_external_buffer` when called from a renderer process, causing memory leak

### ISSUE THREAD

**Issue by jsonfry** [electron/electron#27091]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v11.1.0
* **Operating System:**
  * Ubuntu 20.04 x64
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
In my application I generate data using some native C code, which is placed in a queue and then pulled out of that queue in the JS layer using N-API functions, specifically `napi_create_external_buffer` ([ref](https://nodejs.org/docs/latest-v12.x/api/n-api.html#n_api_napi_create_external_buffer)). 

This N-API function has a callback (see the `finalize_cb` param) so you can free the memory that's backing your buffer when the JS layer garbage collects the JS object.

I'd expect this callback to be called fairly regularly, whenever a garbage collection happens.

### Actual Behavior

However this callback is never called if you call your function via an electron renderer process (in preload.js or renderer.js). The app will keep running until the OS runs out of memory and freezes.

I believe this is a problem in Electron rather than Node.js as the callback _is_ called regularly if you call via the main process (main.js).

### To Reproduce
See this example repo: https://github.com/jsonfry/renderer-napi-leak

This is a fork of the electron quickstart project, with the example added in [one commit](https://github.com/jsonfry/renderer-napi-leak/commit/a71e8c704e05442f9fa7467c9bd461c80f918572).

```sh
$ git clone git@github.com:jsonfry/renderer-napi-leak.git
$ npm install
$ npm run build
$ npm start
```

You'll start to see your memory usage climb until your system runs out, ideally don't let it do that to your computer as it doesn't always recover well.

If you move the code in `renderer.js` to `main.js` you'll see logs in stdout that show the memory being freed regularly, and the memory usage of the app will stay stable.

**Comment by ggreco** [comment]
I think this bug is really important, it happens also on macOS (tested on both catalina and bigsur), not only in Linux.

I tested it both with electron 10.2.x and electron 11.2.3 and the behaviour is the same, @sofianguy can you please add the tags?

Here is my test program to reproduce the issue.

https://github.com/ggreco/testNapi.git

... it is similar to the one provided by @jsonfry , I've found this issue in github was already opened after I built my test program to verify it!

I tried also passing to the application --expose-gc and forcing the garbage collection by hand in the inspector and also in this way the memory is not released.

**Comment by ggreco** [comment]
@codebytere or @MarshallOfSound can you look at this? I see you fixed a few leaks in 13.0 and this issue is causing **huge** memory leaks since usually native modules use a node buffer when they need to move big memory chunks from the native world to the javascript world without copying.

**Comment by ggreco** [comment]
It's fixed in electron 12 or 13 (not sure which one, we are currently using 13 and it doesn't happen)

**Comment by ggreco** [comment]
> Any progress on this issue? I'm using node 12.18.3, Chrome 87.0.4280.141, and Electron 11.3.0 and I can reproduce this issue too.

I fear you need to upgrade electron to 12 or better to get the fix.

**Comment by kohillyang** [comment]
I found AddFinalizer also has the same problem, the finalizer is never called in Electron 11.3.0. but it is normal in 13.6.9. Not sure how electron fixes it.

**Comment by codebytere** [comment]
Closing as all supported versions now contain this fix.
