### ISSUE TITLE
preventDefault on new-window event on webview does not prevent default anymore.

### ISSUE THREAD

**Issue by Kilian** [electron/electron#27090]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 10.0.0-beta.1 and newer (also confirmed for 11.1 and 12.0.0-beta.1)
* **Operating System:** all
* **Last Known Working Electron version:** 9.4.0 (any of the 9.x series)

### Expected Behavior
when running the following code:
```js
document.getElementById("webview").addEventListener("new-window", e => {
  e.preventDefault();
});
```
middle-clicking or ctrl/cmd-clicking on a link should result in nothing happening.

### Actual Behavior

From 10.0.0-beta.1, despite the preventDefault and regardless of anything else in the `new-window` listener, a popup gets opened. 

### To Reproduce
Fiddle: https://gist.github.com/9c87895f429db5d52859a05c8f673865

Open it with anything from 10.0.0-beta.1 or newer and middle click or ctrl/cmd click on the button in the middle of the window. A new window opens.

Open it with any 9.x version and middle click or ctrl/cmd click on the button in the middle of the window. Nothing happens because the event is `preventDefault`ed.

**Comment by MarshallOfSound** [comment]
@Kilian I'm not sure how this _ever_ worked but it's a technically nightmare to make it work reliably.  Effectively that listener is attached in the renderer process but that callback needs a synchronous response from the main process.  The _correct_ way to handle this is to add that `new-window` listener inside the `did-attach-webview` event in the main process.

**Comment by pdc4444** [comment]
I found this issue while searching the internet to figure out how to prevent my webview from opening a new window when I middle mouse clicked on a link inside of it.

Here's how I solved the problem via a line of code in main.js:

`mainWindow.webContents.on('did-attach-webview', (_, contents) => {
    contents._events["-new-window"] = () => {
      return false;
    };
  });`

At some point it looks like the event was changed from 'new-window' to '-new-window' additionally, this did NOT work:

`contents.on('-new-window', (e) => {
      e.preventDefault();
    });`

This code does fire off when a new window is opened, but preventDefault() does nothing.
