### ISSUE TITLE
window.print and webContents.print cause app to crash

### ISSUE THREAD

**Issue by aidanjacobson** [electron/electron#27106]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.1.1
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 

### Expected Behavior
Calls to window.print and webContents.print with no options should open a print dialogue.

### Actual Behavior
Calls to both window.print and webContents.print cause the app to stop responding and crash with no error messages in the console.

### To Reproduce
Call window.print or webContents.print from anywhere in the program.

https://gist.github.com/d784328df29ad9162c714493f269607e

**Comment by codebytere** [comment]
I ran this repro and did not experience a crash.

**Comment by aidanjacobson** [comment]
> I ran this repro and did not experience a crash. We're going to need more information in order to proceed.

My apologies. Shortly after I discovered it was a system-wide printer issue on my computer and forgot this post. Didn't do the proper testing :(

I won't delete it unless you guys want me to, just in case someone else runs in to this same issue?
