### ISSUE TITLE
[BUG, QUESTION] Titlebar does not update when using dark mode

### ISSUE THREAD

**Issue by ANF-Studios** [electron/electron#27100]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
* **Electron Forge Version:**
Electron-Forge version: `6.0.0-beta.54`
* **Electron Version:**
Electron version: `v11.0.3`
* **Operating System:**
[From VS Code (Help > About)] OS: Windows_NT x64 10.0.19042
[From winver] OS: Microsoft Windows 10 20H2 (OS Build: 19042.630)
* **Last Known Working Electron Forge version:**:
null

### Expected Behavior
Title should *out of the box* update the title when in dark mode in system settings and/or manually via code.
### Actual Behavior
Title bar does not update the color -- small note that the menu bar updates its color to dark mode.
### To Reproduce
1. Install Electron and Electron-Forge
2. Create a template app (in my case, I used plain TypeScript)
3. Set the preferred theme to dark mode in any way like `nativeTheme.themeSource = 'dark'`
4. Menu bar would become black, but not titlebar

### Screenshots
![image](https://user-images.githubusercontent.com/68814933/102821436-0fe0fd00-43a5-11eb-8a9e-896c557ebfa0.png)

### Additional Information
A workaround I found to that is using an npm package called `custom-electron-titlebar`.
This issue was created earlier at #23479 but still doesn't seem to be fixed.
I haven't tested this issue on other operating systems, just Windows 10.

**Comment by MarshallOfSound** [comment]
What you have described here as expected behavior is unfortunately not how the Windows OS works.  That titlebar is not themable and win32 apps do not have the ability to toggle it into dark/light mode without calling a very complex set of private APIs.

Closing out as something that isn't a bug and isn't implementable in a sustainable way

**Comment by ANF-Studios** [comment]
Oh, that's so sad to hear - good to know however that a [workaround](https://www.npmjs.com/package/custom-electron-titlebar) exists. Thanks for the help!
