### ISSUE TITLE
Is there a alticon in tray like nw.js

### ISSUE THREAD

**Issue by yorululu** [electron/electron#27105]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Normally, even if the macOS theme is light, the tray icon will change according to the color of the wallpaper.
nw can work normally.
But electron did not find the relevant interface

### Proposed Solution

https://nwjs.readthedocs.io/en/latest/References/Tray/#trayalticon-mac
like this, add alticon prop.

### Additional Information

this issue mentioned it, but not work.
https://github.com/electron/electron/issues/795

**Comment by dragonDScript** [comment]
It doesn't work? Can you detail a bit?

**Comment by yorululu** [comment]
@dragonDScript 
When the macOS theme is set to right, change the wallpaper. When a darker wallpaper is applied, most of the app icons will change to lighter colors, and vice versa.
But electron tray does not have this feature, nw.js tray has alticon that can be set, and the color of the wallpaper will also change.

**Comment by dragonDScript** [comment]
> @dragonDScript
> When the macOS theme is set to right, change the wallpaper. When a darker wallpaper is applied, most of the app icons will change to lighter colors, and vice versa.
> But electron tray does not have this feature, nw.js tray has alticon that can be set. and the icon color will change according the wallpaper color.

Is your icon in blackscale?

**Comment by yorululu** [comment]
> > @dragonDScript
> > When the macOS theme is set to right, change the wallpaper. When a darker wallpaper is applied, most of the app icons will change to lighter colors, and vice versa.
> > But electron tray does not have this feature, nw.js tray has alticon that can be set. and the icon color will change according the wallpaper color.
> 
> Thank you for explaining. I'm not a MacOS user
> Is your icon in blackscale?

I tried blackscale and whitescale, but it does not change according to the wallpaper.
Hope to have an `alticon` similar to nw.js, otherwise for general purpose, only the gray icon can be used. : )

**Comment by JiaoXin2005** [comment]
I have the same problem on MacOS Big Sur。🙁
The color of the menubar in Big Sur does not depend on dark or light mode, but depends on the wallpaper.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
