### ISSUE TITLE
Cannot read property 'getCurrentWindow'

### ISSUE THREAD

**Issue by stereo18** [electron/electron#27104]
Hi, 
This is my code :
```js
 require('electron').remote.getCurrentWindow().close()
```
And this is my error :
```console
Cannot read property 'getCurrentWindow'
```

Does anyone know what's wrong and could help me please ? Thank you in advance

**Comment by hackape** [comment]
```js
new BrowserWindow({
  webPreferences: {
    nodeIntegration: true,
    enableRemoteModule: true, // make sure you switch on these two options
  }
})
```

Please, this is not an "issue", a [google search](https://www.google.com/search?q=electron+Cannot+read+property+%27getCurrentWindow%27) would've easily answered your question.

**Comment by stereo18** [comment]
I don't find anything on google, but, thanks, its works !
