### ISSUE TITLE
AcornJS (Chrome DevTools) incompatibility

### ISSUE THREAD

**Issue by nmggithub** [electron/electron#27103]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
v11.1.1
* **Operating System:**
5.9.14-arch1-1
* **Last Known Working Electron version:**
N/A

### To Reproduce
Hello. I am trying to build an Electron application. When I use the Chromium DevTools to debug my application, the autocomplete features of the console do not work. Instead I get this error printed twice to the terminal in which I started the application:

`"Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.", source: devtools://devtools/bundled/third_party/acorn/package/dist/acorn.mjs`

I tried opening an issue with acornjs and it was closed.

**Comment by MarshallOfSound** [comment]
Fixed in the `11-x-y` branch and will go out in the next release
