### ISSUE TITLE
Support for few Chrome APIs-Electron 11.0.3

### ISSUE THREAD

**Issue by Jenifer-TheCoder** [electron/electron#27117]
Electron and OS details:

- Electron Version-11.0.3
- Operating System: Windows 10(1909)

###Proposed request"
Electron to support below mentioned chrome APIs:
1. chrome.tabs.query
2. chrome.tabs.onActivated
3. chrome.tabs.onUpdated
4. chrome.windows.onFocusChanged
5. chrome.webNavigation

### Actual Behavior
Currently I am not able to those APIs been working

To reproduce:
- I am trying to hook into the events related Electron UI elements very similar to Chrome like clicking on button, checkbox etc.
- In chrome we had developed an extension which uses chrome APIs ,will listen to events on the chrome tabs.
- Had looked into list of supported APIs in:https://www.electronjs.org/docs/api/extensions.The above mentioned APIs aren't found in the link.

### Alternatives Considered
- Not yet decided but have to go in hard of way of listening to all keyboard and mouse events which might be bit costlier.

**Comment by codebytere** [comment]
Folding this into https://github.com/electron/electron/issues/37876
