### ISSUE TITLE
HTTP2 POST requests in electron11 get stuck in pending state

### ISSUE THREAD

**Issue by hxkuc** [electron/electron#27118]
### Preflight Checklist

* [*] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [*] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [*] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.0.0
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * no

### Expected Behavior

http2 not pending

### Actual Behavior

http2 request pending 

use clear browser cache can resolve this problem

**Comment by pratyushFilter** [comment]
@hxkuc were you able to solve this?
