### ISSUE TITLE
net.Socket.connect often fails from the renderer process until the window is reloaded. Ubuntu 20.04 (Win/Mac seem fine)

### ISSUE THREAD

**Issue by koush** [electron/electron#27127]
* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

Using net.Socket.connect from a renderer process does often not work until the renderer has been reloaded (ie, window.reload). Subsequent connect calls work fine. The connect event is never emitted. Neither is the connection failure or error events.

* **Electron Version:**
  * 10.x+ (tested up to 12.x)
* **Operating System:**
  * Ubuntu 20.04
* **Last Known Working Electron version:**
  * 9.4.0

### Expected Behavior
The connect event should be emitted. The socket should connect.

### Actual Behavior
The socket hangs waiting for connect.

### To Reproduce

Connect to a localhost socket (in another process) from the renderer process on Ubuntu 20.04

### Screenshots
None

### Additional Information

This seems to happen fairly reliably, and does NOT happen on 9.4.0 I tried switching app.allowRendererProcessReuse to false, but that did not seem to fix it.

**Comment by pgherveou** [comment]
👋  we are noticing similar behaviors on mac running latest electron version (12.0.5)
Did you have more success running these sockets directly in the main thread instead? 

One thing I noticed from users reporting the bug is that  `lsof -i tcp:443 | grep <app-name>`
Report connection in CLOSED or CLOSE_WAIT status.

Apart from that, I am not sure yet what the best way to debug these issues...

**Comment by koush** [comment]
I'm still on 9.4.0 unfortunately. Can't upgrade until this is fixed. It's too severe for my app.

**Comment by koush** [comment]
Revisited this, and in my case lsof is showing the localhost connection as established, but the connection event on the node socket has never fired. I can check the state of the socket, and it remains at "connecting".

> electron 8962 koush   57u  IPv4 228454      0t0  TCP localhost:59830->localhost:5037 (ESTABLISHED)

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/73924/120912138-a9455800-c641-11eb-9cd0-43a24fe66d5c.png">

**Comment by koush** [comment]
After some further poking, initiating another connection seems to push the pending events through, as if the event loop is stuck?

**Comment by koush** [comment]
I've managed to "fix" this issue by having a socket connect to a server, and just periodically sending ping packets. This seemingly prevents the net loop from hanging for whatever reason.

**Comment by nornagon** [comment]
Is this still happening on 12.0.12 or 13.1.3?

**Comment by koush** [comment]
It was still happening in 13.1.2. I'll check 13.1.3 shortly.

**Comment by koush** [comment]
Was there a change you think addressed this issue or are you just asking for an update?

**Comment by nornagon** [comment]
There were a few libuv changes that happened recently-ish, so I wanted to get a sense for whether any of those might have had an effect.

**Comment by pgherveou** [comment]
Did the nodejs version changed in the latest 13.x electron releases? If not these libuv changes would not be picked up right?

**Comment by koush** [comment]
I can confirm this still occurs on 13.1.4 (which apparently was released today).

**Comment by pgherveou** [comment]
@koush have you been able to test whether or not webworker with Node integration suffer from the same issue.
I ran some quick tests with our users experiencing this, and it seems that webworker can still open socket when the renderer thread fails to do so.

**Comment by koush** [comment]
> @koush have you been able to test whether or not webworker with Node integration suffer from the same issue.
> I ran some quick tests with our users experiencing this, and it seems that webworker can still open socket when the renderer thread fails to do so.

I tried enabling node in web worker, and was getting renderer (native?) crashes, so I disabled it.
