### ISSUE TITLE
`mandatory` property missing from `MediaTrackConstraints`

### ISSUE THREAD

**Issue by jameshfisher** [electron/electron#27139]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** v11.1.0
* **Operating System:** macOS 11
* **Last Known Working Electron version:** -

### Expected Behavior
TypeScript compiles with no type errors.

### Actual Behavior

```
error TS2322: Type '{ mandatory: { chromeMediaSource: string; chromeMediaSourceId: string; }; }' is not assignable to type 'boolean | MediaTrackConstraints | undefined'.
  Object literal may only specify known properties, and 'mandatory' does not exist in type 'MediaTrackConstraints'.
```

### To Reproduce
In a TypeScript project, [use the desktopCapturer API as described in its docs](https://www.electronjs.org/docs/api/desktop-capturer), e.g. just use the example code on that page, or:

```ts
const screenCaptureStream = await navigator.mediaDevices.getUserMedia({
  audio: false,
  video: {
    mandatory: {
      chromeMediaSource: 'desktop',
      chromeMediaSourceId: source.id,
      // etc
    }
  }
});
```

### Additional Information

It looks like this API is part of Chrome rather than part of Electron, and are [parsed somewhere here in `media_constraints_impl.cc`](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/modules/mediastream/media_constraints_impl.cc;l=269?q=kMediaStreamSourceId). It also looks like this `mandatory` section is part of some old/deprecated `getUserMedia` API. It would be great if we could use `desktopCapturer` API with the modern `getUserMedia` API - maybe we can, but the docs don't say how.

It would also be great to know what other constraints we can pass in this `mandatory` section. For example, can we set the frame rate for desktop capture?

**Comment by codebytere** [comment]
@jameshfisher pretty sure this is just a docs update - you should be able to use the new syntax just fine

**Comment by jameshfisher** [comment]
Hey, thanks @codebytere - however when I try using these properties using the modern `getUserMedia` API, they're ignored: I get the default camera video stream instead of a screen capture. Here's what I've tried:

```ts
// This works as expected - gets a screen capture
screenCaptureStream = await navigator.mediaDevices.getUserMedia({
  audio: false,
  video: {
    mandatory: {
      chromeMediaSource: 'desktop',
      chromeMediaSourceId: source.id,
    }
  }
});

// But this just gets the default camera stream instead of the screen -
// same behavior as if these params were not present
const screenCaptureStream = await navigator.mediaDevices.getUserMedia({
  audio: false,
  video: {
    chromeMediaSource: 'desktop',
    chromeMediaSourceId: source.id,
  }
});

// Similarly, using `ConstrainDOMStringParameters` long form -
// same behavior, gets the default camera stream instead of the screen
const screenCaptureStream = await navigator.mediaDevices.getUserMedia({
  audio: false,
  video: {
    chromeMediaSource: { exact: 'desktop' },
    chromeMediaSourceId: { exact: source.id },
  }
});
```

So it seems like this API really is stuck in the dark ages of `getUserMedia`. It would be lovely if it were updated to use the modern API, but I think that's a separate problem to the lack of type definitions for the current API.

**Comment by codebytere** [comment]
@jameshfisher hmm ok i'll check into it and see what i come up with :)

**Comment by kevin-protopie** [comment]
I want to know the progress of this

**Comment by alexciarlillo** [comment]
I just started looking into this myself. Specifically because I would like to try passing some additional flags such as `googCpuOveruseDetection` and `googScreencastMinBitrate` but it looks like no matter where I put them they are ignored. It seems like electron should just be passing these off directly to the underlying browser `getUserMedia` implementation but that doesn't appear to be the case or the new API would work. But I cannot find in the electron sources where any type of translation might be occurring.

**Comment by adampah** [comment]
Has there been any resolution that allows using the getUserMedia function with a specific sourceId? I found the following two threads which contain a similar issue: [[1]](https://stackoverflow.com/questions/62077085/how-to-do-screen-sharing-in-electron-app) and [[2]](https://github.com/microsoft/TypeScript/issues/22897) but no further luck.

**Comment by Icehunter** [comment]
Any update on this at all?

**Comment by nornagon** [comment]
Seems relevant to https://github.com/electron/electron/pull/30702

**Comment by ch1ny** [comment]
It seems this bug has not been fixed yet.
I'm not sure would this helped, but I found a weird way to implement this feature.

I write my React source code in TypeScript and write a preload script in JavaScript.
And here is my code:
```js
// preload.js
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('captureDesktop', function () {
	return new Promise((resolve) => {
		ipcRenderer.invoke('DESKTOP_CAPTURE').then((source) => {
			navigator.mediaDevices
				.getUserMedia({
					audio: {
						mandatory: {
							chromeMediaSource: 'desktop',
							chromeMediaSourceId: source.id,
						},
					},
					video: {
						mandatory: {
							chromeMediaSource: 'desktop',
							chromeMediaSourceId: source.id,
						},
					},
				})
				.then((stream) => {
					console.log(stream);
					const video = document.createElement('video');
					video.srcObject = stream;
					resolve(video);
					// If we resolved MediaStream directly, we could only get an empty object.
				});
		});
	});
});
```

```tsx
// TypeScript
(window as any).captureDesktop().then((videoDOM: HTMLVideoElement) => {
	console.log(videoDOM.srcObject); // MediaStream
})
```

I guess this is not the best way to implement this feature, but it does work.

**Comment by Goldiserv** [comment]
Based on this https://stackoverflow.com/questions/37613981/how-to-use-a-typescript-cast-with-jsx-tsx
Seems like TS follows the latest WebRTC specification. Each browser can have differences in API as WebRTC specification is not an official standard yet. 
Hence TS code needs to cast to any, which worked for me:
`const stream = await (navigator.mediaDevices as any).getUserMedia(constraints)`

**Comment by Jeshvenkatesh** [comment]
Hi @codebytere Any update on this issue ?

**Comment by neobyteUK** [comment]
Would also like some updates on this as have the same questions as OP, can we get this ticket reopened?

**Comment by aziz-boudi4** [comment]
Any update on this issue ?

**Comment by chris0203** [comment]
From @Goldiserv solution work as well.

```typescript
const stream = await (navigator.mediaDevices as any).getUserMedia(constraints)
``` 


but in my problem, `Unsafe return of an any typed value.`
For some one still looking for this.

Just change code below, cast whole object to `MediaStreamConstraints`
```typescript
const stream = await navigator.mediaDevices.getUserMedia({
      audio: false,
      video: {
          mandatory: {
              chromeMediaSource: 'desktop',
              chromeMediaSourceId: source.id,
          },
      },
  } as MediaStreamConstraints);
  return stream;
```

**Comment by MadcowD** [comment]
lmao any update here?

**Comment by Katsuri-dev** [comment]
i found solution:

./interface.d.ts

declare global {
    interface Window {
        electronAPI: ElectronAPI;
    }

    interface MediaTrackConstraints {
        mandatory: any; // lol
    }
}

now you can use 'mandatory' propertie :D
