### ISSUE TITLE
Top right part of BrowserView in frameless BrowserWindow is not clickable

### ISSUE THREAD

**Issue by quanglam2807** [electron/electron#27131]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
Top right part of BrowserView in frameless BrowserWindow is not clickable

* **Electron Version:** 11.1.1 (broken with >= 11.0.4)
* **Operating System:** Windows & Linux (tested on Windows 10 20H2, reported by a Linux Mint user)
* **Last Known Working Electron version:** 11.0.3

### Expected Behavior

Buttons in `BrowserView` should be clickable.

### Actual Behavior

Buttons in `BrowserView` are not clickable.

### To Reproduce

Replace `main.js` in `electron-quick-start` with the following code.
```js
// Modules to control application life and create native browser window
const {app, BrowserWindow, BrowserView} = require('electron')
const path = require('path')

function createWindow () {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    frame: false,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js')
    }
  })

  const view = new BrowserView({})
  view.webContents.loadURL('https://discordapp.com/login')
  mainWindow.setBrowserView(view)
  view.setBounds({
    x: 0,
    y: 0,
    height: 600,
    width: 800,
  })
  view.setAutoResize({ width: true, height: true })


  // Open the DevTools.
  view.webContents.openDevTools({ mode: 'detach' })
}


// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(() => {
  createWindow()
  
  app.on('activate', function () {
    // On macOS it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.
```

Login with your Discord account. The top right part of the UI won't be clickable (see screenshot).

Downgrade to Electron 11.0.3 and it will work normally. Upgrade to Electron 11.0.4 and it will break.

### Screenshots

![Capture](https://user-images.githubusercontent.com/1548835/103154871-567f8e80-47cd-11eb-99c0-08e9c31cc3db.PNG)

### Additional Information

Likely to be regression of https://github.com/electron/electron/pull/26738
@codebytere

**Comment by quanglam2807** [comment]
Also, it seems like this only happens with certain websites. I attempted to create a simple HTML page with some buttons and they were all clickable. But somehow, this bug occurs with Microsoft Teams & Discord. 

Refs:
https://github.com/webcatalog/webcatalog-app/issues/1254
https://github.com/webcatalog/webcatalog-app/issues/1237

**Comment by codebytere** [comment]
It's most likely related to this: https://github.com/electron/electron/pull/26738

**Comment by codebytere** [comment]
hey @quanglam2807 - turned out to be a pretty simple fix, PR is up at https://github.com/electron/electron/pull/27143
