### ISSUE TITLE
Uncaught ReferenceError: require is not defined - December 2020

### ISSUE THREAD

**Issue by ShlomiRex** [electron/electron#27136]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  v11.1.1
* **Operating System:**
  *  Windows 10 20H2
* **Last Known Working Electron version:**
  * 

### Expected Behavior
My JS script inside HTML:
```
<script>
	const electron = require("electron")
	const ipcRenderer = electron.ipcRenderer;

	ipcRenderer.on("test", (e, data) => {
		console.log("ipcRenderer on ", e, data);
	});
</script>
```
The output should not contain any exceptions or error

I do have `nodeIntegration` set to true:
```
	const mainWindow = new electron.BrowserWindow({
		width: 1600,
		height: 800,
		webPreferences: {
			nodeIntegration: true,
			webviewTag: true,
			nodeIntegrationInWorker: true
		},
	});
```

### Actual Behavior
The output is:

> Uncaught ReferenceError: require is not defined

**Comment by codebytere** [comment]
The provided code produces no errors. If you would like for us to triage further, you will need to provide a reproducible sample.

**Comment by ShlomiRex** [comment]
> The provided code produces no errors. If you would like for us to triage further, you will need to provide a reproducible sample.

I successfuly managed to fix this by using preload script that loads required file :D

**Comment by cawoodm** [comment]
Electron guys this is indeed an issue: the official [docs](https://www.electronjs.org/docs/faq) say that`require` (and other node objects like `process`) should be available in the renderer process if `nodeIntegration: true` but that is not or no longer the case.

## main.js
```javascript
const { app, BrowserWindow } = require('electron')
const url = require('url')
const path = require('path')
let win
function createWindow() {
  win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true
    }
  })
  win.loadURL(url.format({
    pathname: path.join(__dirname, 'index.html'),
    protocol: 'file:',
    slashes: true,
  }))
}
app.on('ready', createWindow) 
```
## index.html
```html
<html>
<body>
  Process: <script>document.write(typeof process)</script>
  <br>
  Require: <script>document.write(typeof require)</script>
</body>
</html>
```

## output
```
Process: undefined
Require: undefined
```

**Comment by sgehrman** [comment]
Spent 3 hours and still can't get this working.  This is why I switched to Flutter. I'm trying to recompile an old electron project and your instructions are worthless.  nothing works.
