### ISSUE TITLE
How to speed up build electron speed

### ISSUE THREAD

**Issue by wuzhiming** [electron/electron#27145]
Hello, I was build electron myself and it can build success.
But, I need change some code for electron

when I change some code and rebuild electron it take a long time for linking (maybe half an hour) electron framework (both MacOS and Windows). so it is hard for me to customize electron.

It's there any way to speed up the linking electron framework?
 
How did your team develop electron?

**Comment by MarshallOfSound** [comment]
> It's there any way to speed up the linking electron framework?

If you just want to test changes locally ensure you're using the `testing.gni` configuration, it will have faster link times than release builds.  Building Electron locally is heavily dependent on your machines specs and it's a very intensive process, there's not a lot we can do to make linking faster.

Actual compilation can be sped up by using [`build-tools`](https://github.com/electron/build-tools) which will automatically pull from our compilation cache, linking is always done locally and without high end hardware (in particular large amounts of memory) linking will take a long time

**Comment by wuzhiming** [comment]
ok thanks~
