### ISSUE TITLE
-webkit-app-region "drag" vs "non-drag" problem

### ISSUE THREAD

**Issue by josephernest** [electron/electron#27149]
Here is how to quickly reproduce the bug: Electron fiddle: https://gist.github.com/josephernest/f3db7d319af407b2dcef04c7c1c514ee

____

I have a `#topleft` red title bar containing multiple "tab" buttons that should fill all the available space *except* a `#topright` blue block.  
It is possible to move the main Electron window by click-and-dragging on `#topleft`'s red background, thanks to `-webkit-app-region: drag;`. This works.

[![enter image description here][1]][1]

**Problems**: 

1. clicks on `#topright` are ignored: `alert()` is not triggered  (same problem for child elements of this block)
2. `#topright span:hover { background-color: black; }` is ignored 
3. `#topright { -webkit-app-region: no-drag; }` is ignored: we can still move the window by click-and-dragging on `#topright` whereas it should not

However if we run the same HTML code *in a browser*, all is working correctly.

  [1]: https://i.stack.imgur.com/ZZPsJ.png

**Comment by StaZhu** [comment]
I have tested many electron versions, so far (11.1.1) the bug still exits, which started from 10.1.6 (and all 11 version) related to a browser view not draggable fix
