### ISSUE TITLE
VSCODE code snippets: <webview> == 'Element' not 'webviewTag'?

### ISSUE THREAD

**Issue by SleepyCatGuy** [electron/electron#27153]
DISCLAIMER/Info: I am using VSCODE/ESLint which I believe to be the issue but I'm not sure how to fix this issue. When I say 'return/s' I mean the code snippets. I'm using electron-react-boilerplate.

`const webv = document.querySelector('webview');`
In vscode this ^ returns a `Element` how do I make it return `webviewTag` (`import { webviewTag } from 'electron';`).

I want to know this so I can have code snippets of `webviewTag` (not `Element`) and do not have a refer to the documentation every step of the way.

thank you.

Edit:
![Image for more clarity](https://user-images.githubusercontent.com/32443069/103383806-fd537b80-4aa8-11eb-9a70-ffc90a84e8fd.png)

**Comment by SleepyCatGuy** [comment]
1: In the Image `const webv = document.querySelector('webview') || webviewTag;` should be `const webv = document.querySelector('webview');` I forgot to remove it, I was testing things to see if that would fix my problem.

2: I actually did fix my problem by changing it to `const webv: WebviewTag | null = document.querySelector('webview');`

should probably add it to the docs.

**Comment by SleepyCatGuy** [comment]
I'm reopening this because I keep running into problems. it's still very touchy and can break at any moment, so I'm reopening this to see if anyone has any feedback on this.

**Comment by jkleinsc** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
