### ISSUE TITLE
How to share object between 2 renderer processes that is TIME CRITICAL?

### ISSUE THREAD

**Issue by ShlomiRex** [electron/electron#27155]
Title
How can I sync instance of object between 2 renderer processes?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
