### ISSUE TITLE
 open sandbox start launching application process crash on macos

### ISSUE THREAD

**Issue by Leafcat801** [electron/electron#27152]
### The configuration is as follows： 
```
     macOs: 10.15.6
     "electron": "11.0.0",
     "electron-builder": "^22.9.1", 
```

```
 "mas": {
        "gatekeeperAssess": false, 
        "hardenedRuntime": false, 
        "provisioningProfile": "build/XXX.provisionprofile",
        "entitlementsInherit": "build/child.plist",
        "entitlements": "build/parent.plist",
        "asarUnpack": []
    },
```
### parent.plist: 
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple/DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>com.apple.security.app-sandbox</key>
    <true/>
    <key>com.apple.security.application-groups</key>
    <array>
       <string>XXXXXXXXXXX</string>
    </array>
    <key>com.apple.security.network.server</key>
    <true/>
    <key>com.apple.security.network.client</key>
    <true/>
    <key>com.apple.security.device.usb</key>
    <true/>
    <key>com.apple.security.files.user-selected.read-write</key>
    <true/>
    <key>com.apple.security.cs.allow-jit</key>
    <true/>
    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
    <true/>
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>
    <key>com.apple.security.get-task-allow</key>
    <true/>
    <key>com.apple.security.files.bookmarks.app-scope</key>
    <true/>
    <key>com.apple.security.files.bookmarks.document-scope</key>
    <true/>
  </dict>
</plist>
```
#### Here's the log：

Process:               XXX Helper (Renderer) [13668]
Path:                  /Applications/XXX.app/Contents/Frameworks/XXXX Helper (Renderer).app/Contents/MacOS/XXXX Helper (Renderer)
Identifier:            XXXX Helper (Renderer)
Version:               3.300.0
Code Type:             X86-64 (Native)
Parent Process:        XXXX [13665]
Responsible:           XXXX [13665]
User ID:               501

Date/Time:             2020-12-30 16:50:55.371 +0800
OS Version:            Mac OS X 10.15.6 (19G73)
Report Version:        12
Bridge OS Version:     4.6 (17P6065)
Anonymous UUID:        FDF3686B-3E30-D9B0-9891-0A008B3FA626

Sleep/Wake UUID:       B949DBA2-0C50-4E67-B42E-E95A2CCC98CE

Time Awake Since Boot: 27000 seconds
Time Since Wake:       25000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [13668]

Application Specific Information:
dyld: launch, running initializers
/usr/lib/libSystem.B.dylib
Could not set sandbox profile data: Operation not permitted (1)

Application Specific Signatures:
SYSCALL_SET_PROFILE

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread: .......

### As I understand, key error logs is : 
```
Application Specific Information:
dyld: launch, running initializers
/usr/lib/libSystem.B.dylib
Could not set sandbox profile data: Operation not permitted (1)
```

**Comment by codebytere** [comment]
We require the template (which you had to delete in order to fill it out as you did) to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in  7 days if the above is not addressed.
