### ISSUE TITLE
More Documentation on ContextIsolation Enabled

### ISSUE THREAD

**Issue by havind** [electron/electron#27150]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Comment by codebytere** [comment]
This is an insufficiently filled issue that does not indicate specific concerns nor adhere to our required template. If you have specific queries, you are welcome to **_fill out the template completely_** in a new issue.
