### ISSUE TITLE
BrowserWindow could make it easier to find WebContents via BrowserView

### ISSUE THREAD

**Issue by Mr-Wallet** [electron/electron#27158]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
`BrowserWindow.fromWebContents()`, at first glance doesn't seem like an _especially_ helpful method. This is a small improvement over Electron-based projects individually creating a helper function that iterates over the results of `BrowserWindow.getAllWindows()` manually:
```javascript
function getBrowserWindowFromWebContents(webContents) {
  return BrowserWindow.getAllWindows().find((win) => win.webContents === webContents) || null;
}
```

However, this method becomes much more helpful when `BrowserView` enters the picture. When receiving a message over IPC, the `event.sender` is a WebContents that could be unrelated to a given window, or directly attached to the window, _or_ attached to the sole BrowserView attached to the window (`win.setBrowserView()`), _or_ attached to one of possibly multiple BrowserViews attached to the window (`win.addBrowserView()`). Now the helper method is a little more involved:
```javascript
function getBrowserWindowFromWebContents(webContents) {
  const allWindows = BrowserWindow.getAllWindows();
  let result = allWindows.find((win) => win.webContents === webContents);

  if (!result) {
    result = allWindows.find((win) => {
      return win.getBrowserViews().some(
        (view) => view.webContents === webContents
      );
    });
  }

  return result || null;
}
```

If we could replace all of the above with a simple `BrowserWindow.fromWebContents()`, that would be very convenient. However, as far as I can tell, the current implementation is more along the lines of the `let result` line above; it simply looks for directly-attached WebContents, without regard for hierarchy.

### Proposed Solution
`BrowserWindow.fromWebContents` should be able to find any WebContents _directly or indirectly_ attached to the BrowserWindow. In the case that a programmer chooses to use this method and the WebContents is attached to a BrowserView that is itself attached to a BrowserWindow, it seems unlikely to me that the programmer would typically expect, and/or desire, that the BrowserWindow containing the BrowserView not be returned. In such an unlikely case, the programmer could simply use the smaller code block above to explicitly search _only_ for `win.webContents` results.

Technically this would be a breaking change, but as BrowserView is still an experimental feature, hopefully it would be seen as a relatively benign one.

### Alternatives Considered
BrowserView and WebContents are currently subject to memory leak concerns (see discussion in #23578 and #27071). If, in an effort to reduce problematic references to these leaking objects, maintainers anticipate that the `webContents` property may be removed from BrowserWindow and/or BrowserView, or that `.getBrowserViews()` will be removed from `BrowserWindow` instances, then this proposed change may be premature and inadvisable.

**Comment by nornagon** [comment]
I believe this was addressed in September with https://github.com/electron/electron/pull/25408.

Let me know if this is erroneous.
