### ISSUE TITLE
Entire word no longer auto-selected on right click on Mac

### ISSUE THREAD

**Issue by sachinrekhi** [electron/electron#27154]
### Issue Details

* **Electron Version:**
11.1.1
* **Operating System:**
macOS 10.15.7
* **Last Known Working Electron version:**
10.2.0

### Expected Behavior
Normally when you right click on text in an Electron app on Mac, the entire word at your cursor position becomes selected.

### Actual Behavior
In Electron 11.1.11, this behavior stopped happening. Now when you right-click, the entire word is no longer auto-selected. It works as expected in 10.2.0, which is the last Electron version I have been using.

### To Reproduce
Fire up an Electron app using version 11.1.11
Right click on any text and notice that the entire word is no longer selected

Is there any workaround to bring back the previous behavior? Recent versions of Chrome continue to auto-select the whole world, like it is expected to do. I assume this is a bug since this is standard Mac behavior.

**Comment by codebytere** [comment]
@sachinrekhi i am unable to reproduce this with the default [fiddle](https://github.com/electron/fiddle). Are you sure you didn't just change a system setting?

![right_click_word](https://user-images.githubusercontent.com/2036040/103703991-60d42200-4f5d-11eb-9793-2784a2d8d73e.gif)

**Comment by codebytere** [comment]
Closing as no response was given. Happy to consider reopening should more information come to light.
