### ISSUE TITLE
Crash on Electron App Startup

### ISSUE THREAD

**Issue by mastergberry** [electron/electron#27161]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  * 11.1.0
* **Operating System:** 
  * Windows 10 x64 Bit (lots of different builds)
* **Last Known Working Electron version:** 
  * Unknown

### Expected Behavior

Not to throw errors on boot.

### Actual Behavior

Throwing errors on startup.

### To Reproduce

No idea how to...I pushed an update to our users, and it seems like there was some kind of outage from our CDN for 10 minutes or so at the same time I pushed out the update.

### Screenshots

https://i.gyazo.com/thumb/1200/5210051076f1b041e7335ff180fcab67-png.jpg

### Additional Information

Logs showing the error from one user:

```
2021/01/01 17:13:02:459 Error: net::ERR_CONNECTION_RESET
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6497)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
2021/01/01 17:14:23:446 Error: net::ERR_CONNECTION_RESET
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6497)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
2021/01/01 17:14:24:933 Cannot download differentially, fallback to full download: Error: net::ERR_CONNECTION_RESET
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6497)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
```

I cannot find the code anywhere in the repo, but I guess it has something to do with the way things are packaged. Anyways it definitely seems like some kind of internet outage issue coupled with logic that does not handle connection errors? I don't see any of my code in the stack trace here, which is the weird part....or I would just catch and handle it myself.

**Comment by batching-svg** [comment]
Hi!

Could you check if this: https://github.com/electron-userland/electron-builder/issues/2398#issuecomment-413117520 works for you?

**Comment by MarshallOfSound** [comment]
Duplicate #27172, the above comment looks useful
