### ISSUE TITLE
npm node-ping fails; child-process not allowed to open socket.

### ISSUE THREAD

**Issue by JamesNewton** [electron/electron#27168]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.
https://github.com/electron/electron/issues?q=is%3Aissue+%22node-ping%22
https://github.com/electron/electron/issues?q=is%3Aissue+isAlive

### Issue Details

* **Electron Version:**
  * v5.0.13
* **Operating System:**
  * Ubuntu 18.04 x64 and Ubuntu 16.04 x64
* **Last Known Working Electron version:**
  * 4.0.0 (I think)

### Expected Behavior
The node-ping package should return isAlive or error in electron, and fail after timeout, just as it does under node. 

### Actual Behavior
node-ping instantly returns isAlive==false, even though the specified IP is online and pingable from the command line or from a node only test program. It when given an IP which is not online, it returns this same false value (correct), with no error code (correct), _instantly_ even though `{timeout: 10}` has been specified (timeout is in second, per the package). 

### To Reproduce
The following test program:
````
let ping = require('ping') //https://www.npmjs.com/package/ping
ping.sys.probe("192.168.0.142"
        , function(isAlive, err){
                var msg = isAlive ? 'Dex is alive' : 'Dex is dead:'+err;
                console.log(msg);
                }
        , {timeout: 10}
        );

````
with the IP changed to something that does ping on your network, should log Dex is alive, or when changed to something that is NOT on the network, should _wait 10 seconds_ and then log Dex is dead with an error (normally null, unless the IP is illegal or the network disconnected, etc...). Instead, it always logs 'Dex is dead:null' and does so instantly.

To narrow this down, I use the source code of node-ping to write code that does the same thing, in a very minimal version inside the electron app. "out" is just console log, but it goes to a special text box which is easy to see while the program is running.

````
var cp = require('child_process');
ping = cp.spawn("ping", ["192.168.0.142"]);
ping.stdout.on('data', (data) => {
  out(`stdout: ${data}`);
});

ping.stderr.on('data', (data) => {
  out(`stderr: ${data}`);
});

ping.on('close', (code) => {
  out(`child process exited with code ${code}`);
});
````

the stderr message comes back as stderr: ping: icmp open socket: Operation not permitted
and the child process exited with code 2.

So for some reason, the app doesn't give the child process the rights to open a socket? But the npm package get-page works just fine in the same app, getting a web page. 

The electron app is DDE:
https://github.com/cfry/dde
and you can simply paste in the code example above to the editor window, and press the "Eval" button to reproduce the issue.

Wonder if it's related to this:
electron/electron#18521

**Comment by MarshallOfSound** [comment]
Electron 5 is no longer supported, please update to a supported version of Electron (9,10,11).  This issue iirc was actually fixed in recent versions of Electron, it is due to child process sandboxing rules.
