### ISSUE TITLE
Distributing Application with API Key

### ISSUE THREAD

**Issue by fwiwDev** [electron/electron#27163]
Hi, thanks so much for all the work that has gone into this project. It is amazing!

What is the recommended way of distributing an application that includes an API key since the source code is not private?

How can I protect the key from someone easily unwrapping the source and misusing the key for ill-advised actions?

Thank you for your thoughts.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
