### ISSUE TITLE
crypto.scryptSync is not a function

### ISSUE THREAD

**Issue by joelcieslar** [electron/electron#27167]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v11.1.1
* **Operating System:**
  * elementary OS 5.1.7 Hera
* **Last Known Working Electron version:**
  * not applicable, first time to use Electron

### Actual Behavior
I am trying to use the `scrypt` and `scryptSync` functions from Node.js Crypto in my React app, running inside Electron v11.1.1.

I am faced with the error `TypeError: nodeCrypto.scryptSync is not a function`

There is a [StackOverflow post](https://stackoverflow.com/questions/54738225/electronjs-and-nodejscrypto-crypto-scryptsync-is-not-a-function#54784584) and a [GitHub issue](https://github.com/electron/electron/issues/17015) about this: both seem to be resolved by updating Electron. However, as I understand it, I am using the latest version of Electron.

`crypto.scryptSync` was [added to Node.js in version v10.5.0](https://nodejs.org/api/crypto.html#crypto_crypto_scryptsync_password_salt_keylen_options).

### Expected Behavior

`nodeCrypto.scryptSync` *should* be a function.

`nodeCrypto.scrypt` *should* be a function.

### To Reproduce

```
const nodeCrypto = require('crypto');

// does not work
const kek = nodeCrypto.scryptSync('password', 'salt', 64).toString('hex');
```

### Additional Information

I am able to use `randomBytes` from Node.js Crypto just fine:
```
// works fine
nodeCrypto.randomBytes(32).toString("hex");
```

I chose to assign `crypto` to the constant `nodeCrypto`  because [Chrome already contains a global called _crypto_](https://stackoverflow.com/questions/61529247/how-to-use-crypto-in-electron), but this didn't improve the situation.

As ever, I am most grateful for your assistance.

**Comment by ckerr** [comment]
Hey @joelcieslar, thanks for reaching out.

I tried to reproduce this in 11.1.1 and wasn't able to:

```sh
$ cat main.js
const nodeCrypto = require('crypto');

// does not work
const kek = nodeCrypto.scryptSync('password', 'salt', 64).toString('hex');
console.log(kek)
$ yarn list --pattern electron
yarn list v1.22.10
├─ @electron/get@1.12.2
└─ electron@11.1.1
Done in 0.09s.
$ yarn start
yarn run v1.22.10
$ electron .
745731af4484f323968969eda289aeee005b5903ac561e64a5aca121797bf7734ef9fd58422e2e22183bcacba9ec87ba0c83b7a2e788f03ce0da06463433cda6
```

Could you confirm the prerequisite setup needed to reproduce this issue? If you're able to isolate it, could you create a test repo or to codify those prerequisites? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

**Comment by codebytere** [comment]
@joelcieslar I also tried with https://gist.github.com/9cca3217ac89abc3301fa805ef8cac76 and experienced no issues

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.

**Comment by jasjamjos** [comment]
If someone comes across this problem the solution is to update your types/node version to 16 up.. 
eg ("@types/node": "^16.11.12")
