### ISSUE TITLE
The text of the web page loaded in Electron on Pinephone appears blurry

### ISSUE THREAD

**Issue by Occhioverde** [electron/electron#27169]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 11.1.1
* **Operating System:** Manjaro-ARM 20.12 (Kernel Linux Pinephone 5.10.4-1)
* **Last Known Working Electron version:** N/A

### Expected Behavior

The text on the page opened in the Electron window should appear clear and defined.

### Actual Behavior

The text on the page loaded by Electron looks blurry and ill-defined, as if it belongs to a small, enlarged image (in the screenshot section I put side by side the images of the same web page ([start.nexxontech.it](https://start.nexxontech.it)) shown by Electron and by the browser (Angelfish)).

### To Reproduce

To notice the problem, simply open a Electron window on Pinephone. The text of the application menu buttons (File, Edit, etc) will also appear blurred.

### Screenshots

**Screenshot taken in Angelfish**
<img src="https://user-images.githubusercontent.com/18429412/103487712-b26a9880-4e07-11eb-8357-70f677899bb1.png" width="500" />
**Screenshot taken in Electron**
<img src="https://user-images.githubusercontent.com/18429412/103487716-b5658900-4e07-11eb-893d-a19803c0d3c2.png" width="500" />

**Comment by RangerMauve** [comment]
Getting this on Electron 11.1.1

**Comment by RangerMauve** [comment]
Adding the following flags seems to help:

`electron --enable-features=UseOzonePlatform --ozone-platform=wayland ./example.js`

**Comment by RangerMauve** [comment]
For some reason I can't add these flags using [commandLine.appendSwitch](https://www.electronjs.org/docs/api/command-line#commandlineappendswitchswitch-value) 

🙃

**Comment by nornagon** [comment]
> simply open a Electron window on Pinephone

This is quite the repro instruction 🤣   feel like shipping me a phone?

It seems like a bug with pinephone's setup though if this works under wayland and not under X11, so I'm going to close this as blocked/upstream. If we learn that there's some action we can take here to make things better I'm happy to reopen.
