### ISSUE TITLE
How to generate pdf from window contents when contextIsolation is 'true'?

### ISSUE THREAD

**Issue by awalariansyah** [electron/electron#27174]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

When the contextIsolation is enabled, and also passing DOM is Deprecated. How can we generate PDF from a window?

I have a button
<button onclick="window.run.print()">Print</button>

Renderer process
ipcRenderer.send('print')

Main process
ipcMain.on('print', (event) => {
  // do the web content print
})

It throw an error cannot clone an object.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
