### ISSUE TITLE
Electron console window (--enable-logging) does not show colors on Windows

### ISSUE THREAD

**Issue by nmggithub** [electron/electron#27170]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * Electron v11.1.1
* **Operating System:**
  * Windows 10 (20H2 19042.685)
* **Last Known Working Electron version:**
  * Never

### Expected Behavior
The Electron command prompt windows shows colors.

### Actual Behavior
The Electron command prompt windows does not show colors.

### To Reproduce
1. Develop Electron app that logs colored output from the main process
2. Build to a portable Windows exe via `electron-builder`:

`electron-builder build -w -c electron-builder.config.js` where `electron-builder.config.js` contains:
```javascript
var config = {
    win: {
        target: 'portable',
    }
};
exports.default = config;
```
3. Run the given exe with the flag `--enable-logging` from the Windows Command Prompt
4. Observe the lack of color in the logs.

### Additional Information
This issue appears to be referenced both in issue #11488 and issue #15727. The former appears to reference a fix that was implemented, but this does appear to still be an issue.

**Comment by sofianguy** [comment]
What electron version are you experiencing this issue on?

**Comment by nmggithub** [comment]
> What electron version are you experiencing this issue on?

I was sure I included this in my original post, but apparently it slipped. I am experincing this on electron v11.1.1

**Comment by xmedeko** [comment]
I have same issue when running in debug mode and **Electron 12.0.2** , too. E.g.
```js
const console = require("console")
console.log('\x1b[0;32m test \x1b[0m')//yellow
```
and then `npx electron index.js` have no colors. When using `npx electron index.js | more` then I got the colored output.

**Comment by xmedeko** [comment]
It's working for me with **v21.1.0**.
