### ISSUE TITLE
Error: net:ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by visenLu** [electron/electron#27172]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

Suddenly all our computer  appeared this problem.
when render process try to send message to main process. App comes out a error dialog:
A JavaScript error occurred in main process
Uncaught Exception:
Error: net: ERR_CONTENT_LENGHTH_MISMATCH
at SimpleURLLoaderWrapper.<anonymous>
(electron/js2c/brower_init.js:97:6400)
at SimpleURLLoaderWrapper.emit(events.js: 310:20)
and we cann't fixed it even restart the app. But if we restart the computer, this problem gono

* **Electron Version:**
  * 10.0.0
* **Operating System:**
  * windows MacOS
* **Last Known Working Electron version:**
  * 

### Screenshots

![Image_20210104150624](https://user-images.githubusercontent.com/19523252/103509596-733b5680-4e9e-11eb-81d5-ccb007eafb6f.jpg)

**Comment by MarshallOfSound** [comment]
Your app is sending a network request via the `net` module and isn't handling the `error` event or the `uncaughtException` event on the `process` object so this error is falling back to the default handler.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

**Comment by visenLu** [comment]
> Your app is sending a network request via the `net` module and isn't handling the `error` event or the `uncaughtException` event on the `process` object so this error is falling back to the default handler.

thank you, we will try this to fix it.
