### ISSUE TITLE
Using window.history.back() and window.history.forward() does not update BrowserWindow titles.

### ISSUE THREAD

**Issue by eengoron** [electron/electron#27188]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  
  * 8.1.1
  * 11.1.1
* **Operating System:**
  * macOS 10.14, macOS 10.15
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior

When using `window.history.back()` or `window.history.forward()`, the title of the BrowserWindow should update to the title of the page you're navigating to. 

### Actual Behavior

When using `window.history.back()` or `window.history.forward()`, the title of the BrowserWindow does not update to the title of the page you're navigating to. 

### To Reproduce

1) Download and start the `electron-quick-start` example
2) Open Devtools > Console
3) Enter `window.location = 'https://www.google.com'` to get to Google (The window title will update to Google)
4) Enter `window.history.back()` to go back to the page that was originally opened. 

The window title will still say `Google` instead of `Hello World!` as it's supposed to. 

### Screenshots

Here's a gif where I navigate to two websites and then use `window.history.back()` to show this issue:
![title_doesnot_update](https://user-images.githubusercontent.com/2817521/103596854-dc39c300-4ecc-11eb-88a3-18d7bb209018.gif)

### Additional Information:
This does work in the normal Chrome browser, so this looks to be an Electron specific issue.

**Comment by ckerr** [comment]
Confirmed. I don't think this is platform-specific; FWIW I'm seeing it on Linux as well

**Comment by gdavidkov** [comment]
It is still an issue. Please repeat the steps in the description. The title isn't being updated.
