### ISSUE TITLE
Sending value returned by v8.serialize to a WebSocket connection crashes

### ISSUE THREAD

**Issue by KishanBagaria** [electron/electron#27199]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.1.1
* **Operating System:**
  * macOS 11.1

### To Reproduce

```js
const v8 = require('v8')

const bufferToArrayBuffer = (b) =>
  b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength)

const ws = new WebSocket("ws://echo.websocket.org")

ws.binaryType = 'arraybuffer'
ws.onopen = () => {
  console.log('ws open')
  const serialized = v8.serialize([1,2,3])
  ws.send(Buffer.from(serialized)) // works
  ws.send(bufferToArrayBuffer(serialized)) // works
  ws.send(serialized) // crashes
}
ws.onmessage = ev => {
  console.log('ws message', ev)
}
ws.onerror = ev => {
  console.log('ws error', ev)
}
ws.onclose = ev => {
  console.log('ws close', ev)
}
```

Posted as a gist to load in Fiddle: https://gist.github.com/KishanBagaria/7ec26d3733a83a2fbd792eef4571011b

### Screenshots

https://user-images.githubusercontent.com/1093313/103656306-7281ed80-4f8e-11eb-86af-a9a9beae86ee.mov

**Comment by codebytere** [comment]
@KishanBagaria might take me a while to get to a solution for this one but i _can_ at least tell you the issue is gone in v12 and beyond

**Comment by KishanBagaria** [comment]
Ah that's good to know! This is low priority for us, bufferToArrayBuffer works well so we can just wait for v12 to be out on stable. (Feel free to close)

**Comment by codebytere** [comment]
Closing as all supported versions now contain this fix.
