### ISSUE TITLE
'will-quit' event seems to terminate early before the promise resolves

### ISSUE THREAD

**Issue by andresmejia3** [electron/electron#27201]
I'm using Electron 11.0.1 on OS x Catalina

I'm running an app that spawns a server during the app's splash page and kills the server while trying to exit. My code looks like this, but when I quit the app only 'will-quit triggered' gets printed out. Nothing inside of the findProcess() promise call gets printed out. The killServer() function works, I've tested it by calling event.preventDefault() in 'will-quit' and all messages are printed out (also confirmed by running `ps aux` to see that the process was kill). It appears that 'will-quit' might be terminating before findProcess has a chance to be executed. Any chance on how to resolve this? 

<img width="368" alt="Screen Shot 2021-01-05 at 2 20 41 PM" src="https://user-images.githubusercontent.com/31969347/103710299-b3740500-4f82-11eb-92ab-b98ae219abcb.png">

<img width="484" alt="Screen Shot 2021-01-05 at 2 20 01 PM" src="https://user-images.githubusercontent.com/31969347/103710312-b8d14f80-4f82-11eb-99d3-e5c0ff190df9.png">

![](https://cdn.discordapp.com/attachments/761937430713597972/796100140372852827/Screen_Shot_2021-01-05_at_2.37.39_PM.png)

**Comment by pushkin-** [comment]
seems like it's by design based on [this code](https://github.com/electron/electron/blob/462de5f97a302987dc5fa5c222781ceed040f390/shell/browser/browser.cc#L229)

the event handler doesn't support asynchrony.

You'd have to cancel the quit, do your async thing, and then retrigger it, skipping the cancel the second time

**Comment by MarshallOfSound** [comment]
> You'd have to cancel the quit, do your async thing, and then retrigger it, skipping the cancel the second time

This is correct, event handlers are supposed to be synchronous.  If you want to do async work, prevent the quit and force a quit manually once your work is done
