### ISSUE TITLE
Writing to TEMPORARY with FileSystem API doesn't respect app.getPath

### ISSUE THREAD

**Issue by carlosperate** [electron/electron#2721]
I'm testing this using v0.31.2-32bit on Windows 8.1 64 bit.

I'm using `app.getPath` to successfully move the `appData` directory. However the `temp` and `cache` directory do not seem to be changing as expected.

I am using the [FileSaver.js](https://github.com/eligrey/FileSaver.js/) library to save text files in the user computer. Every time I use this library to save a file under Electron, it creates a temporary file in my user directory `Downloads` folder. When I try to change the `temp` directory using `app.getPath`, these temporary files are still created in my `Downloads` folder.

The [documentation](https://github.com/atom/electron/blob/master/docs/api/app.md#appgetpathname) does not indicate what's the default directory for the `temp` folder, so I am assuming that using the user `Downloads` folder, instead of a folder inside the default `appData` directory, is not another bug in itself.

The `cache` folder also does not change correctly when set using `app.getPath`. However, as indicated in the documentation, a `Cache` folder is now being created inside the `appData` directory, which has been successfully changed. So, it is no saved any longer in `%APPDATA%`, but it is not using the expected path set in `app.getPath`.

In both cases, the new directory set in `app.getPath` has been created, it is just not being used.

**Comment by carlosperate** [comment]
On a side note, I've also experienced issue https://github.com/atom/electron/issues/2668. I'm relating the issues here as it might have a similar nature, or it will probably be fixed around the same time as this one.

**Comment by zcbenz** [comment]
The FileSave.js is using filesystem API for creating temporary file, it seems that it is writing to the downloads directory instead of temporary directory.

For the cache directory, you should probably set `userCache` instead of `cache`.

**Comment by carlosperate** [comment]
> For the cache directory, you should probably set userCache instead of cache.

Sorry I didn't mention it in my original post, but I had also tried to set the `userCache` to a different folder and it had the same issue (new folder created, but not used). I did not think that the application was using the `userCache` because a folder named `Cache` is created with all the Electron cache, and from the documentation I would have expected a different folder name if this was the `userCache`.

> `userCache ` The directory for placing your app's caches, by default it is the cache directory appended with your app's name

Is there a simple way to trigger a normal temporary file (that does not use the File System API) to be created to check it is working correctly?

**Comment by zcbenz** [comment]
> Sorry I didn't mention it in my original post, but I had also tried to set the userCache to a different folder and it had the same issue (new folder created, but not used).

It is probably the same bug with #2668, but I'm not sure, Chrome seems to store all browser cache into hard-coded paths under `userData` and only uses `userCache` for other kinds of caches. I'll look into it in future.

> Is there a simple way to trigger a normal temporary file (that does not use the File System API) to be created to check it is working correctly?

It is a hint to Chrome's internal functions, there is no guarantee that all Chrome APIs will use it.

**Comment by carlosperate** [comment]
Thanks for looking into it once you get the chance @zcbenz.

Just to clarify the situation, I have something along the lines of:

```
app.setPath('appData', 'newAppData');
app.setPath('userData', 'newAppData');
app.setPath('cache',  'newAppData/GenCache');
app.setPath('userCache',  'newAppData/UserCache'));
app.setPath('temp',  'newAppData/temp'));
```

Which creates the `newAppData` directory with the following folders:

```
 newAppData/GenCache (created, but does not seem to be used)
 newAppData/UserCache (created, but does not seem to be used)
 newAppData/Cache (used by Electron instead of GenCache)
 newAppData/GPUCache (there is no option for such directory app.getPath but it is pretty self explanatory)
 newAppData/temp (empty, but cannot really test if it is used by Electron)
```

The rest of the `appData` files seem to be created correctly inside the `newAppData` directory (cookies, dev tool extensions, preferences, etc).

Exactly as described in https://github.com/atom/electron/issues/2668 the `%APPDATA%/productName` is still created, but no files are saved in that directory.

Hopefully this should make the issue more clear and help debugging.

**Comment by zcbenz** [comment]
Unfortunately Chromium just writes everything to `userData` directory, the logic is hard-coded everywhere and it is impossible to easily patch it. Plus we have removed the `userCache` directory from `getPath`, so I'm closing this as won't fix.

**Comment by RayLew001** [comment]
> Unfortunately Chromium just writes everything to `userData` directory, the logic is hard-coded everywhere and it is impossible to easily patch it. Plus we have removed the `userCache` directory from `getPath`, so I'm closing this as won't fix.

When use loadUrl,the app will write temporary files in C:\Users\{username}\AppData\Local\Temp on windows.how can i use setPath('temp',newPath) to change the temporary folder?Does setPath('temp',newPath)  works?
