### ISSUE TITLE
Download of electron-v11.1.1-darwin-x64.zip very slow / fails

### ISSUE THREAD

**Issue by MarMun** [electron/electron#27214]
### Preflight Checklist
* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * electron v11.1.1
* **Operating System:**
  * macOS Big Sur 11.1
* **Last Known Working Electron version:**
  * electron v11.1.1

### Expected Behavior
`npm install electron` is successful. 

### Actual Behavior
`npm install electron` fails / hangs on asset download. 

```
> electron@11.1.1 postinstall /Users/me/Dev/vue3/node_modules/electron
> node install.js

Downloading electron-v11.1.1-darwin-x64.zip: [================----------------------------------] 31% ETA: 4166.1 seconds
```

### To Reproduce
`npm install electron`

### Additional Information
20 - 40 KB/sec download speed on manual asset download via
https://github.com/electron/electron/releases/download/v11.1.1/electron-v11.1.1-darwin-x64.zip

**Comment by codebytere** [comment]
Feel free to open this on the website repo, but this is not an issue with Electron core and not one we are directly responsible for - it's hosted on AWS.

**Comment by MarMun** [comment]
Understood. Thx for the clarification.

btw: Download seems to be up and running again.

**Comment by Leskur** [comment]
If you have proxy, you can try this.

macOS
```bash
export ELECTRON_GET_USE_PROXY=http://127.0.0.1:8080
```

Windows
```bash
set ELECTRON_GET_USE_PROXY=http://127.0.0.1:8080
```

**Comment by MarMun** [comment]
@Leskur Thx for your reply.

The problem was located at my ISP / my IP at that time. After restarting my router (which prompted my ISP to assign me a new IP), the problem was gone...
