### ISSUE TITLE
globalShortcuts' behaviour is not actually "global". And it is not reliable.

### ISSUE THREAD

**Issue by luvyana** [electron/electron#27240]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
11.1.1
* **Operating System:**
Windows 10

**Problem :** 

globalShortcuts as it is will straight out **won't work with games at all**, for example League of Legends will completely block Electron's globalShortcuts. While that's another problem, Electron will also **override shortcuts of the other applications**, for example; let's say you created a globalShortcut on **"Ctrl+Shift+i" which is used for opening console.** Now if you go and try to use this shortcut while your Google Chrome or Discord is open, your **Electron application will override this shortcut**, and you **won't be able to open the console using that shortcut**, as long as the electron app is running. This makes it unreliable and not really "global"

**How it should be :** 

globalShortcuts, technically should be able to **"work" with** everything. **It shouldn't overrule.** For example Discord application has actual global shortcuts, which doesn't block any other apps using those shortcuts. **It works with them without blocking them.** And also manages to work in games, which is really important. I should be able to mute unmute my audio/microphone etc.. I can count lots of uses for it to work with games.

### To Reproduce

```javascript

const {app, BrowserWindow, globalShortcut } = require("electron")
const path = require("path")

function createWindow() {
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
    },
  })

  mainWindow.loadFile("index.html")
}

app.whenReady()
  .then(() => {
    createWindow()

    globalShortcut.register("CmdOrCtrl+Shift+i", () => {
        console.log(
          "CmdOrCtrl+Shift+i is pressed"
        )
  })

    app.on("activate", function() {
      if (BrowserWindow
        .getAllWindows()
        .length === 0)
        createWindow()
    })
  })

app.on("window-all-closed", function() {
  if (process.platform !== "darwin")
    app.quit()
})
```

**Comment by Kilian** [comment]
This is by design, from the docs: 

> Note: The shortcut is global; it will work even if the app does not have the keyboard focus.

Discord actually uses Electron so they are using globalShortcuts too (I would guess). What you need to do, and what most desktop apps do, is registering their globalShortcuts on window focus, then releasing them again on window blur. Example code here:

https://github.com/Kilian/fromscratch/blob/master/app/main.dev.js#L210-L216

**Comment by luvyana** [comment]
Did you even bothered to read the issue ? I refuse to be you did.

Also your info is about Discord using "globalShortcuts" is absolutely wrong as well. They are not using it literally because of the things i've said that you didn't bother to read.

**Comment by luvyana** [comment]
I believe you misunderstood the issue here, I'll try to explain bit more carefully;

Discord's globalShortcut is "global" by design, but it is not working reliably to be able to actually call it "global". An actual "global" shortcut would work in a game, or work with other app's hotkey without blocking them. If that's design as well, that's actually insanely bad design. Hope that helps.

**Comment by Kilian** [comment]
That's the opposite of what you initially wrote:

> For example Discord application has actual global shortcuts, which doesn't block any other apps using those shortcuts. It works with them without blocking them.

This is because Discord disables them on blur, as I explained. There can only be one app attached to a global shortcut at any given time. That's a limitation by the operating system level APIs provided by Windows, MacOS etc, not a choice made by Electron.

**Comment by luvyana** [comment]
How is that "opposite" of what i write? What is the point of calling a system "global" that doesn't work globally. Electron globalShortcuts straight out won't work if you are in a game, making it "not global". I really don't understand why this is so hard to understand. 

Also discord doesn't uses globalShortcuts as well, literally because of these problems i've mentioned. They have their own library for handling this.

> There can only be one app attached to a global shortcut at any given time. That's a limitation by the operating system level APIs provided by Windows, MacOS etc, not a choice made by Electron.

This is absolutely not true. You can have Same hotkey on Discord and have that hotkey on a different application/game as well and if you press that both will work, as it should be. globalHotkeys, if in game, doesn't work, if in another app like for example chrome, will block chrome's hotkey.

**Comment by luvyana** [comment]
Hello, can i get an update on this?

I checked your example, not only it has literally nothing to do with my issue it literally disables your "shortcut" when your window is not on focus, at this point i even doubt you bothered to read my issue. I could get the same result through just front end using a keyboard listener, if i wanted to have a shortcut that works when only the app is in focus.

Actual global shortcuts, "should" work no matter the app is focused, without blocking their own shortcuts. Your example would be extremely useless/pointless if i wanted to have a microphone mute button, and have it work in a game since It wouldn't because not only you disable them when your window is not on focus, it also can't work with games)

You could easily make this behaviour in python with couple lines of code it will work in every situation, without blocking any other application's hotkey, as it should be.

**Comment by lacymorrow** [comment]
Global shortcuts work in games, I use them in a crosshair app. If it isn't working it's either not registered or conflicting with another program

**Comment by StenniHub** [comment]
> Global shortcuts work in games, I use them in a crosshair app. If it isn't working it's either not registered or conflicting with another program

I have developed a savefile manager primarily targeted for the Dark Souls series, and had issues using globalShortcut in those games when they run in fullscreen, like the OP mentions. I attempted to update to electron 18.2.0 and still could not get them to work when for example playing Dark Souls 3. When testing the portable version of your crosshair application it does seem to work (at least when I tested centering), but I can't seem to figure out why. I assume you have made a lot of tweaks to keep your application in the foreground and interactable. Anything you have done to the window, process or keybind registration that you think contribute to them working while in fullscreen?

For the time being I have gotten around the issue by using iohook instead of globalShortcut, but I would like to get rid of that dependency permanently so I can stick to the latest electron version.

**Comment by luvyana** [comment]
> Global shortcuts work in games, I use them in a crosshair app. If it isn't working it's either not registered or conflicting with another program

Global Shortcuts do not work in games. Global Shortcuts can't work in games that's the problem and "conflicting with another program" is the reason. 

You should be able to use a simple shortcut like just "CTRL" it should still run without blocking the game or whatever application is running. Discord has this and they have their own thing for this. They don't use "Global Shortcuts" for this exact reason.

https://www.npmjs.com/package/node-global-key-listener I just use this, which is the behaviour i was looking for.

**Comment by chlebon** [comment]
[luvyana](https://github.com/luvyana) - I can confirm that `node-global-key-listener` is working well, even when some game like LoL have a focus and is on top, BUT when I use this package, Windows Defender just put it in Quarantine and flag it like Trojan.
