### ISSUE TITLE
[enhancement] Add Support For Libraries Import

### ISSUE THREAD

**Issue by Bellisario** [electron/electron#27244]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  alls
* **Operating System:**
  alls
* **Last Known Working Electron version:**
  alls

### Expected Behavior

I'd like that coding with Electron, it's possible to import Electron modules and not forced to import alls. I am saying that because, generally, package or compile an Electron app can take 100MB and more, but there are a lot of apis and modules that normally, users don't use. Many languages, uses command "import" to import modules, or, another way, can be an Electron config file when you can put all "libraries" that you need, and not more...
### Actual Behavior

Actually, Electron's packages can take 100MB and more, because it imports, ever, all libraries.
### To Reproduce

?

**Comment by miniak** [comment]
This is by design
