### ISSUE TITLE
The resized event doesn't fire when maximizing/unmaximizing the window

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#27246]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 11.1.1
* **Operating System:** Windows 10

### Expected Behavior
I expect that the window's resized event fires when the window is maximized or unmaximized

### Actual Behavior
`resized` never fires, only `resize` fires

### To Reproduce
1. npm start main.js and wait until the window is maximized
2. seconds later you'll see a message box telling you that the resized event never fired

main.js:
```
const {app, BrowserWindow, dialog} = require('electron')

function createWindow () {
  const mainWindow = new BrowserWindow()

  mainWindow.loadURL('https://google.com')

  let resizeFired = false;
  mainWindow.on("resize", () => {
    resizeFired = true;
  })
  let resizedFired = false;
  mainWindow.on("resized", () => {
    resizedFired = true;
  });

  setTimeout(() => {
    mainWindow.maximize();
    setTimeout(() => {
        dialog.showErrorBox("", `resize: ${resizeFired}; resized: ${resizedFired}`);
    }, 2000);
  }, 5000)
}

app.whenReady().then(createWindow)

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})
```

**Comment by pushkin-** [comment]
same for unmaximizing, minimizing, and restoring

**Comment by codebytere** [comment]
This is intended behavior. If you inspect [documentation](https://github.com/electron/electron/blob/b531123b4d58c13d8ee1d222f5ab170d973b4a38/docs%2Fapi%2Fbrowser-window.md#L544-L552) you'll see:

> This is usually emitted when the window has been resized manually.

You're calling `maximize` manually so `resize` will be emitted, correctly, after the window has finished resizing, but `resized` will not. You can verify this by manually resizing the window quickly before `maximize()` is called and noting that the event is fired.
