### ISSUE TITLE
Transparent window is showing black background

### ISSUE THREAD

**Issue by iamisti** [electron/electron#27253]
Can someone explain me what exactly is the problem with the transparent windows? I know if we disable the hardware acceleration with ```app.disableHardwareAcceleration()``` then the problem goes away.
But I could not find an explanation why it is happening. Also I have a relatively new video card (2080ti) and I'm pretty sure it does support anything that you need for transparent window rendering.

So the issue must be somewhere else. I need hardware acceleration in my electron app, otherwise the user experience is very poor.
Please help me, I'm digging several days the answer but no luck. Documentation is almost nothing about this topic.
Would really appreaciate some help.

Electron Version I'm using: 6

**Comment by jkleinsc** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps
