### ISSUE TITLE
electron login event only accept callback once

### ISSUE THREAD

**Issue by vorpax** [electron/electron#27259]
I have multiple electron webviews and i would like to login a different proxies on each diferent webview. 

The thing is that when i'm awaiting 'login' event and when i'm using the callback to provide username and pass to the proxy, the login event is never called again and i can't provide a different username and pass.  Electron is always using this specific login and pass and it is never called twice, even for a different webcontent login method.

    webContents.on('login', (event, details, authInfo, callback) => {
                        event.preventDefault()
                        console.log('ProxyLogin   ' + webContents.id)
                        callback(proxyobj[2], proxyobj[3])

                    })

this event handler is called when a new webview is attached to a specific browser window.

https://gist.github.com/vorpax/6210f7e3621f344323cf0fd3f2a9fa3d

^^  Here is a fiddle, you only need to provide a proxy array, ipify is used to show the ip

To log throught my proxy i've also tried to use webrequest and to add a custom header but obviously I can't do it on https request so it is not a viable solution.

My electron version is "electron": "^11.1.1"

**Comment by jkleinsc** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
