### ISSUE TITLE
Transparent windows are opague if created hidden and there is a delay between creation and `show()` [Windows]

### ISSUE THREAD

**Issue by carterbs** [electron/electron#27265]
### Preflight Checklist

* [ x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.1.1
* **Operating System:**
  * Windows 10 1909

### Expected Behavior
A BrowserWindow created with `transparent: true` should be transparent, regardless of when the window is shown.

### Actual Behavior
GIVEN hardware acceleration is disabled
AND a window is created with `transparent: true; show: false`
AND there is a delay between creation and `win.show()`
THEN the window has an opague background.

If `win.show()` is invoked immediately after window creation, the window is transparent.

### To Reproduce
https://gist.github.com/69cc92347ffb08a3c4020b40a13f2002

### Screenshots
![Screen Shot 2021-01-11 at 10 41 04 AM](https://user-images.githubusercontent.com/16466430/104203058-b2672b80-53f9-11eb-81da-d064c57326c9.png)

**Comment by friksa** [comment]
You see the same issue when creating it visible followed by hide() and show().  All goes well until you show() it the 2nd time at which time the transparency is lost.

Using this workaround instead of hiding the window:
```
function hide(w) {
  w.setIgnoreMouseEvents(true);
  w.setOpacity(0);
}
function show(w) {
  w.setIgnoreMouseEvents(false);
  w.setOpacity(1);
}
```
