### ISSUE TITLE
Native module does not write to stdout (but if it loads a dynamic library, the library does)

### ISSUE THREAD

**Issue by artus9033** [electron/electron#27260]
### Issue Details
Writing to standard output does not work at all in a custom native module, but works from calls in a dynamic library loaded by this module.

* **Electron Version:**
  11.1.1
* **Operating System:**
  Windows 10 (1803)

### Expected Behavior
`std::cout`, `printf`, `fprintf(stdout, ...)` or `fwrite(..., stdout)` should write output to the main electron process's `stdout`, that would be visible in console (like `console.log`'s is).

### Actual Behavior
All the calls do nothing (although they are executed, as other logical operations execute properly) - nothing is written to the terminal.
On the other hand, if the same module loads a dynamic library that does use `std::cout`, only the calls from the library take effect and properly write text to the terminal. This also happens if I call `std::cout` both directly from the addon code and from the library (that is, only the library calls work properly).

### Additional Information
I am developing using `electron-forge` and the addon is written on top of N-API.
Compilation systems tried: `node-gyp`, `cmake-js` (both reproduce the problem)

**Comment by artus9033** [comment]
Seems like this is a problem with piped standard streams, after a few hours of research I managed to fix this (at least on Windows) by attaching the console and reopening all streams, like this:
```cpp
#if defined(WIN32)
    AttachConsole(ATTACH_PARENT_PROCESS);

    FILE *placeholder;
    freopen_s(&placeholder, "CON", "w", stdout);
    freopen_s(&placeholder, "CON", "w", stderr);
    freopen_s(&placeholder, "CON", "r", stdin);
#endif
```
Anyway, this seems to present a very irritating and completely undocumented problem. Moreover I can't yet think of a fix for that for UNIX-es.
I am not quite sure where to suspect a location of the reason why this happens. Is there any contributor who could shed some more light on this?

**Comment by jkleinsc** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by artus9033** [comment]
Seems like this issue is no more present on UNIXes with `electron` >= 12.X. On Windows, my fix above works well, with an additional step required to fix `std::cout` and friends: `std::ios::sync_with_stdio();`.
