### ISSUE TITLE
mac os big sur GPU process frequently crash on electron 8.2.3

### ISSUE THREAD

**Issue by NearLife** [electron/electron#27278]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  8.2.3
* **Operating System:**
  mac os 11
* **Last Known Working Electron version:**

### Expected Behavior
gpu process no crash

### Actual Behavior
gpu process crash

### Screenshots
![Snipaste_2021-01-12_16-10-00](https://user-images.githubusercontent.com/38059014/104287184-0d2f7e80-54f1-11eb-9f4c-69f3db9e4aef.png)

### Additional Information
abort() called
知音楼 Helper (GPU)(10320,0x70000a595000) malloc: Incorrect checksum for freed object 0x7fe59ed7b300: probably modified after being freed.
Corrupt value: 0x2020227365637275

**Comment by NearLife** [comment]
libsystem_c
+0x0080720
<unknown> 
libsystem_malloc
+0x000f430
<unknown> 
libsystem_malloc
+0x0023702
<unknown> 
libsystem_malloc
+0x0007182
<unknown> 
libsystem_malloc
+0x00067aa
<unknown> 
libsystem_malloc
+0x00061f9
<unknown> 
Metal
+0x0017c88
<unknown> 
Metal
+0x009b56e
<unknown> 
libdispatch
+0x00037c7
<unknown> 
libdispatch
+0x000496b
<unknown> 
Metal
+0x0017bca
<unknown> 
Metal
+0x008ac52
<unknown> 
Metal
+0x008c0d4
<unknown> 
Metal
+0x008dbbc
<unknown> 
Metal
+0x0065121
<unknown> 
Electron Framework
+0x32cfc86
metal::(anonymous namespace)::TestShaderWithDeviceNow test_shader.mm:165
Electron Framework
+0x32d028a
base::internal::Invoker<T>::RunOnce bind_internal.h:398
Electron Framework
+0x2250afe
base::TaskAnnotator::RunTask callback.h:98
Electron Framework
+0x226af41
base::internal::TaskTracker::RunSkipOnShutdown task_tracker.cc:778
Electron Framework
+0x226aa17
base::internal::TaskTracker::RunTask task_tracker.cc:796
Electron Framework
+0x22a8c6c
base::internal::TaskTrackerPosix::RunTask task_tracker_posix.cc:23
Electron Framework
+0x226a563
base::internal::TaskTracker::RunAndPopNextTask task_tracker.cc:512
Electron Framework
+0x22720b9
base::internal::WorkerThread::RunWorker worker_thread.cc:321
Electron Framework
+0x2271ee3
base::internal::WorkerThread::RunPooledWorker worker_thread.cc:223
Electron Framework
+0x22a9126
base::(anonymous namespace)::ThreadFunc platform_thread_posix.cc:81
libsystem_pthread
+0x0006950
<unknown> 
libsystem_pthread
+0x000247b
<unknown>

**Comment by jkleinsc** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases -- the latest in that series is [11.2.0](https://github.com/electron/electron/releases/tag/v11.2.0).

If you're still experiencing this issue in the latest version of Electron, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
