### ISSUE TITLE
Fullscreen not working on MacOS

### ISSUE THREAD

**Issue by thegnuu** [electron/electron#27283]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 12.0.0-beta.14
* **Operating System:**
  * macOS 11.0.1
* **Last Known Working Electron version:**
  * 11.1.1

### Expected Behavior
The fullscreen button should be enabled and work, see this image from electron 11.1.1

![Screenshot 2021-01-12 at 17 02 51](https://user-images.githubusercontent.com/5129086/104339611-14a65600-54f8-11eb-82d9-a7e00aa28643.png)

### Actual Behavior
The fullscreen button is disabled and does not work, see this image from electron 12.0.0-beta.14.

![Screenshot 2021-01-12 at 17 10 10](https://user-images.githubusercontent.com/5129086/104340509-0c9ae600-54f9-11eb-8aa5-38d95b6f77cc.png)

### To Reproduce
Simply take any project and update to Electron 12.0.0-beta.14

**Comment by codebytere** [comment]
I am unable to reproduce this with what you have so far specified.

<img width="894" alt="Screen Shot 2021-01-12 at 7 52 11 PM" src="https://user-images.githubusercontent.com/2036040/104404539-b7b69a00-550f-11eb-9503-b764d6bf53fa.png">

Please provide us with a more complete reproducible sample if you would like for us to attempt to triage further.

**Comment by thegnuu** [comment]
Of course, I played around with a fiddle and just realized that the issue only happens with `titleBarStyle: 'hiddenInset'`. Sorry I missed that before.

Here is an Electron Fiddle: https://gist.github.com/8cb381dc37fcad24cd25dedcb3b118a9

With this you should be able to reproduce it by switching between v11 and v12 (I only tested beta.14)

**Comment by jkleinsc** [comment]
I can verify this issue happens on 12.0.0-beta.14 with the gist above.  FWIW it works in the latest nightly

**Comment by codebytere** [comment]
Probably this: https://github.com/electron/electron/commit/558bcc65bc5615866fdd6bdfe72be0ca42675b90

**Comment by jkleinsc** [comment]
According to #27318, it appears that 
`titleBarStyle: 'hidden'` will also cause this behavior.
