### ISSUE TITLE
Fullscreen transparent windows are opaque

### ISSUE THREAD

**Issue by brhenrique** [electron/electron#27286]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  11.0.4
* **Operating System:**
  *  Windows 10 (20H2, Build: 19042)
* **Last Known Working Electron version:**
  *  11.0.3

### Expected Behavior

Setting the `transparent` attribute when creating a fullscreen `BrowserWindow` should display a transparent window.

### Actual Behavior
 The window is opaque (black background)

### To Reproduce

Fiddle: https://gist.github.com/brhenrique/f653a0d968c492e649712b561a820677

### Screenshots

Electron 11.0.4

![image](https://user-images.githubusercontent.com/6992723/104380057-2e03ce00-5509-11eb-9d49-6ad119701156.png)

Electron 11.0.3

![image](https://user-images.githubusercontent.com/6992723/104380393-b4b8ab00-5509-11eb-8e73-a11d93acb075.png)

### Additional Information

The problem happens either when `fullscreen: true` is specified or when the `width` and `height` attributes are equal or greater than the dimensions of the display.

One workaround is to set `fullscreen: false` and to subtract `2` pixels from both `width` and `height` values.

**Comment by alectrocute** [comment]
+1

**Comment by ahallicks** [comment]
I'm having a similar issue with v12.0.{3/4}. Using fullscreen my app's window turns completely white and doesn't render anything. The only thing that fixes it is removing fullscreen and simply setting the app's width and height to the screen width and height - 1.

I can only find [this commit](https://github.com/electron/electron/commit/8046f0560afa50ca3980fdd5efe40aa2f0d95e25) that seems to do anything with BrowserWindows that might have made a difference between v12.0.2 (which works) and v12.0.3.

**Comment by stevenjoezhang** [comment]
This issue seems to be resolved in Electron v15
