### ISSUE TITLE
[Feature] Add on-tab-close event for macOS

### ISSUE THREAD

**Issue by dmnsgn** [electron/electron#27282]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 11.1.0
* **Operating System:** macOS

### Expected Behavior

On macOS when using tabs with the system option[ "Prefer tabs when opening documents"](https://support.apple.com/en-gb/guide/mac-help/mchla4695cce/mac#:~:text=Specify%20when%20to%20open%20documents,System%20Preferences%2C%20then%20click%20General.&text=Click%20the%20%E2%80%9CPrefer%20tabs%20when,in%20full%20screen%2C%20or%20always.) our BrowserWindow instances can be grouped as tabs. However, it seems there is no way to handle tab close click event and that prevents us to know where the [BrowserWindow 'close' event](https://www.electronjs.org/docs/api/browser-window#event-close) originated from.

### Actual Behavior

By setting custom menu items and listening for local keyboard shortcuts we can determine where the user tried to close a browser window. If clicking the Tab cross icon (see screenshot below), we can't.

### To Reproduce

Create BrowserWindows with tabbingIdentifier so they are grouped.

### Screenshots

<img width="387" alt="Screenshot 2021-01-12 at 13 56 57" src="https://user-images.githubusercontent.com/1636460/104323554-35fa4880-54de-11eb-8533-5ae227a0d8f1.png">

**Comment by codebytere** [comment]
Unfortunately Apple doesn't currently make this information available - when a user clicks the primary red traffic light button and when they click the tab close button the same `windowWillClose` event handlers are triggered, with no real way to differentiate between them. If that changes, happy to reconsider, but i'm closing this out now for that reason.
