### ISSUE TITLE
--remote-debugging-pipe does not work

### ISSUE THREAD

**Issue by eugeneo** [electron/electron#27287]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v11.1.1
* **Operating System:**
  * macOs 11.1
* **Last Known Working Electron version:**
  * n/a

### Expected Behavior
The code below should be able to connect to exchange devtools protocol messages through the pipes.
Electron application should start.

### Actual Behavior
Electron application does not start.
No response received when a message is sent through the pipe.

### To Reproduce

This code works with Chrome but not with Electron:

```
const message = { id: 1, method: 'Target.getTargets'};

function run(electronPath: string, script: string) {
    return new Promise((res, rej) => {
        const electron = paths.join(electronPath, 'electron');

        const electronProcess = spawn(electron, [script, '--remote-debugging-pipe'], {
            stdio: ['inherit', 'inherit', 'inherit', 'pipe', 'pipe']
        }).on('error', rej).on('exit', res);
        const [pipeIn, pipeOut] = electronProcess.stdio.slice(3);
        console.log(electronProcess.stdio.length);
        pipeOut.on('data', (buf) => console.log(2, buf.toString()))
            .on('end', () => console.log('out closed'));
        if (pipeIn instanceof Writable) {
            setTimeout(() => {
                console.log(pipeIn.write(`${JSON.stringify(message)}\0`,
                    (err) => console.log('Wrote 1', err)))
            }, 5000);
        }
    });
}
```

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 7 days if the above is not addressed.

**Comment by eugeneo** [comment]
Updated original description.

**Comment by codebytere** [comment]
@eugeneo this is still not enough code for us to run without making several assumptions. Please provide something that I can run in Fiddle for example.

**Comment by eugeneo** [comment]
I decided to take a different approach in my project so I don't have a repro. Feel free to close the bug if there's noone other interested in this feature.
