### ISSUE TITLE
Error: Invalid header: Does not start with Cr24

### ISSUE THREAD

**Issue by thedoublejay** [electron/electron#27297]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.2.0
* **Operating System:**
  * Windows 20H2
* **Last Known Working Electron version:**
  * 11.1.1

### Expected Behavior
Using the latest Electron 11.2.0 build, with `electron-devtools-installer 3.1.1`, the app should build successfully.

### Actual Behavior
Using the latest Electron 11.2.0 build, with `electron-devtools-installer 3.1.1`, the build fails. There's an error `Error: Invalid header: Does not start with Cr24` when running the build. Previously using Electron 11.1.1, this error is also displayed but the build still works.

### To Reproduce
Just run `electron` and build of app will fail.

### Screenshots
![image](https://user-images.githubusercontent.com/25013382/104402201-bb3e3580-5590-11eb-9eee-d32314bceffe.png)

**Comment by jkleinsc** [comment]
This appears to be an issue with [electron-devtools-installer](https://github.com/MarshallOfSound/electron-devtools-installer), not electron itself.  Please file an issue there.

**Comment by partnerinflight** [comment]
@jkleinsc it appears they think it's an Electron issue: https://github.com/MarshallOfSound/electron-devtools-installer/issues/141

**Comment by thoni56** [comment]
I have this issue too, on Electron 7.3.3. In my case [this googled comment](https://gitmemory.com/issue/frappe/books/190/792656616) helped me to at least get past the problem. But for me it was

    await installVueDevtools();

that needed commenting out. Maybe that gives another clue to the root cause of this.
