### ISSUE TITLE
Traffic light icons are not visible when focus is lost

### ISSUE THREAD

**Issue by DaveTryon** [electron/electron#27295]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

  With macOS, if I set `BrowserWindow.titleBarStyle` to `hidden` to create a custom title bar, the traffic lights are visible when the app has the focus, as expected. The traffic lights disappear, however, as soon as the app loses the focus. They seem to still exist, since they appear on mouse hover. The same behavior occurs with or without actually creating a custom title bar.

* **Electron Version:**
  * 11.1.1
* **Operating System:**
  * macOS 11.1
* **Last Known Working Electron version:**
  * Unknown

### Expected Behavior
When the app is in the non-focused, non-hover state, I would expect the traffic lights to appear in grey, like they do if `titleBarStyle` is set to `default`.

### Actual Behavior
The traffic lights disappear completely.

### To Reproduce
1. git clone https://github.com/DaveTryon/electron-quick-start.git
2. git checkout origin/DisappearingIcons
3. npm install
4. npm start
5. Notice that the traffic lights appear
6. Click on another app that doesn't obscure the traffic lights of the demo app. Look at where the traffic lights should be. They don't appear at all.
7. While keeping the focus on another app, hover over the space where the traffic lights should be. They appear on hover.

### Screenshots
Here are screenshots to show what I mean

State | Image
--- | ---
Focused | ![image](https://user-images.githubusercontent.com/45672944/104395098-d65f6580-54fc-11eb-91c7-d7d3a97156d4.png)
No focus or hover | ![image](https://user-images.githubusercontent.com/45672944/104395173-fdb63280-54fc-11eb-86b9-a630710dcc28.png)
Hover without focus | ![image](https://user-images.githubusercontent.com/45672944/104395317-51c11700-54fd-11eb-933f-b06261f87b45.png)

**Comment by zcbenz** [comment]
This is because you are using dark mode and the unfocused traffic light icons are using a light color, if you turn the page's background color to black then you can see the icons.

<img width="165" alt="Screen Shot 2021-01-26 at 11 19 22" src="https://user-images.githubusercontent.com/639601/105790951-8c7c8200-5fc8-11eb-9937-132eb147e936.png">

**Comment by LANMIN-X** [comment]
I also encountered this problem. In dark mode, the light background cannot be displayed. focus is lost.
