### ISSUE TITLE
electron启动报错，不能正常下载安装

### ISSUE THREAD

**Issue by xiaoxiao0203** [electron/electron#27299]
![image](https://user-images.githubusercontent.com/25219989/104415085-50025c80-55ac-11eb-982d-bd017e1928b9.png)
![image](https://user-images.githubusercontent.com/25219989/104415106-5a245b00-55ac-11eb-9638-ec87edb36a50.png)

**Comment by jkleinsc** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

感谢您与我们联系！

问题跟踪器用于功能请求和错误报告，因此您可能会在[项目的社区页面]（https://www.electronjs.org/community）上的链接之一上拥有一个更好的运维问题。特别是，请务必尝试[Electron Discord服务器]（https://discord.com/invite/electron）。

我希望这有帮助！
