### ISSUE TITLE
[Feature Request]: support apple silicon on every version

### ISSUE THREAD

**Issue by zimengle** [electron/electron#27304]
**Preflight Checklist**

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Problem Description**

I want to support the Apple m1 chip in my application, but I don’t want to update the electron version because the compatibility workload is very large. I am currently using electron 7.3.0

**Proposed Solution**

Each version provides a new build version that supports Apple's m1 chip

**Alternatives Considered**

Give a solution to build support for Apple's m1 chip on old version

**Additional Information**

_No response_

**Comment by baconbrad** [comment]
This can only be offered at the very least for every supported version of Electron. These versions of Electron are 9, 10, and 11. Working on the your app to bring it up to compatibility will be less of a workload than trying to make version 7 branch work natively with the Apple m1 chip. Especially in the event that Chromium and/or Node needs to be updated for that old branch to make compiling to the architecture possible.

The good news is your old Electron app should run on newer Apple devices. On Apple silicon, apps built for the x86_64 architecture run under the Rosetta translation environment for backwards compatibility.

**Comment by miniak** [comment]
Apple Silicon is supported by Chromium included in Electron 11, it's not feasible to backport this into older versions.

**Comment by miniak** [comment]
Also Electron < 9 is not supported anymore, which means that it's not getting security fixes as well.
