### ISSUE TITLE
Electron doesn't show content-scripts of loaded extension

### ISSUE THREAD

**Issue by Jenifer-TheCoder** [electron/electron#27301]
Description:

- I am trying to make chrome extension to work with Electron application.
-  Using session.loadExtension i was able to load the extension.
- Not able to see content-scripts of loaded extension in the inspect window

Environment:

Electron version-11.0.3

Is it a bug?

**Comment by jkleinsc** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by freekingg** [comment]
How do I load native Chrome extensions
