### ISSUE TITLE
How to disable dragging the right border to resize the window but retain the bottom right corner?

### ISSUE THREAD

**Issue by asd281533890** [electron/electron#27300]
![image](https://user-images.githubusercontent.com/46190356/104426424-e2126100-55bc-11eb-943b-a9a49e9d6912.png)

My English is bad, I hope you understand.

It is a frameless application, the scrollbar is in a webview.
The right border of the application is too closed to the scrollbar. When I close to the scrollbar the mouse become double arrow then I can't drag the scrollbar. I want to do something to fix this.
I have try to add an style `border-right: 4px solid #fff` to the webview but it is too ugly.
I wouldn't like to use the `resizable: false` option in creating the BrowserWindow.
Is there any way to disable dragging the right border to resize the window or reduce the trigger area but retain the bottom right?

![image](https://user-images.githubusercontent.com/46190356/104426801-5fd66c80-55bd-11eb-826f-3de84ae6e288.png)
![image](https://user-images.githubusercontent.com/46190356/104426804-64028a00-55bd-11eb-81ed-adb84717dac1.png)

**Comment by jkleinsc** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
