### ISSUE TITLE
App crashes when icon is set after updating to electron 11.2

### ISSUE THREAD

**Issue by idanwork** [electron/electron#27303]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v11.2.0
* **Operating System:**
  * macOS 10.15.7
* **Last Known Working Electron version:**
  * v11.1.1
  
### Expected Behavior
Application should open when icon is set, if failed to load icon file I expect to get an exception and not SIGSEGV

### Actual Behavior
Application is terminated on the BrowserWindow constructor when _icon_ is supplied

### To Reproduce

* Update to electron v11.2
* Make sure to have the _icon_ property set when creating new instance of _BrowserWindow_
* In the example below I used VSCode icon as an example, I've also tried to copy the file to the project dir, it has no affect.
   This happens with other icns files so the file itself is not important.

```javascript
const { app, BrowserWindow } = require('electron')

function createWindow () {
  const win = new BrowserWindow({
    icon: "/Applications/Visual Studio Code.app/Contents/Resources/Code.icns", // <-- comment to avoid crash, or use electron 11.1.1
    /**
     * Jan 13 13:44:22  Electron Helper[26232] <Error>: read failed
       Jan 13 13:44:22  Electron Helper[26232] <Error>: SeatbeltExecServer: failed to read buffer length.
       Failed to initialize sandbox.
       /Users/idanwork/Projects/electron-icon/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron exited with signal SIGSEGV
     */
   // icon: `${__dirname}/Code.icns`, // Tried to copy the icon locally, didn't help
  })

  win.loadURL('https://www.electronjs.org/docs/api/browser-window');
}

app.whenReady().then(createWindow)
app.on('window-all-closed', () => app.quit())
app.on('activate', () => BrowserWindow.getAllWindows().length === 0 && createWindow());
```

package json
```json
{
  "name": "electron-icon",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "run": "electron ."
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "electron": "^11.2.0"
  }
}
```

### Additional Information

The example assumes you have _Visual Studio Code_ in the _Applications_ folder, you can alter it to use any other icon file.
Reverting the same code to electron v11.1.x works
Error can't be caught and the application is terminated
I've tried using other icon files and put the files in the project dir, the issue persists.

_Edited text in comment_

**Comment by quanglam2807** [comment]
```js
const win = new BrowserWindow({
    icon: undefined
  })
```

crashes Electron as well (after upgrading to electron 11.2.0)

**Comment by ckerr** [comment]
Gist version of the testcase above: https://gist.github.com/ckerr/d43fad3e4419b796a08c39ec394ad94a

**Comment by johnnyapol** [comment]
Reproducible on Linux as well. Arch just got 11.2 in the repositories sometime earlier today, started getting bug reports for this issue as well.

`const { app, BrowserWindow } = require('electron')

function createWindow () {
  const win = new BrowserWindow({
    icon: undefined,
  })

  win.loadURL('https://www.electronjs.org/docs/api/browser-window');
}

app.whenReady().then(createWindow)
app.on('window-all-closed', () => app.quit())
app.on('activate', () => BrowserWindow.getAllWindows().length === 0 && createWindow());`

Saving this as test.js and running
`electron test.js`

reproduces the issue.

**Comment by ckerr** [comment]
*(breadcrumb)* Not many commits in [v11.1.1...v11.2.0] to choose from. :slightly_smiling_face:  122d8910d54f31ce6596f3b888933c079670fe0f for #27217 looks like the best bet.

**Comment by quanglam2807** [comment]
Another info: 
```js
const win = new BrowserWindow({
  icon: undefined,
})
```
crashes the app on macOS.

but 
```js
const win = new BrowserWindow({
  icon: path.join('icon.png'),
})
```
does not.

**Comment by ckerr** [comment]
Yep, 122d891 is the one. Patch RSN.

**Comment by MikaelX** [comment]
I can confirm this on my Mac M1, Electron 11.2.1, having a faulty(missing) icon crashed the application as above states. Setting it to a existing icon fixes the issue. Thank you for the above examples and explanations!

**Comment by idanwork** [comment]
Thanks @MikaelX on Intel based machine I still get this error even with 11.2.1

**Comment by Kodehawa** [comment]
11.2.1 still crashes.

**Comment by ckerr** [comment]
Fixed in 11-x-y here https://github.com/electron/electron/pull/27478, this fix should roll out in the next 11.x.y release

**Comment by capc0** [comment]
I can confirm that 11.2.2 fixes this issue.
