### ISSUE TITLE
loadFile not working if path contains a folder with a dot (".")

### ISSUE THREAD

**Issue by sinedied** [electron/electron#27306]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** v11.2.0
  * 
* **Operating System:** macOS 10.15.7
  * 
* **Last Known Working Electron version:** v9
  * 

### Actual Behavior

Trying to load the app entry point from a folder with a dot `.` does not work, for example:
```js
mainWindow.loadFile('dist.electron/index.html');
```
Changing it to:
```js
mainWindow.loadFile('dist-electron/index.html');
```
Make it work. It used to work with previous Electron version (if I recall well, v9 was working fine).

### To Reproduce

Move the UI part into a subfolder `dist.electron` and try to load `index.html` from there.

### Screenshots

If folder contains a dot, nothings loads. What's even stranger is that if I hit CMD+R (refresh) then it loads correctly.
![image](https://user-images.githubusercontent.com/593151/104468638-f869ee00-55b7-11eb-8f08-f8116da24099.png)

**Comment by aabuhijleh** [comment]
I think I'm suffering from the same issue on Windows too. I'm getting `ERR_FILE_NOT_FOUND (-6)` errors that I was not getting with Electron v9.

The issue happens sporadically and not sure how to reproduce it consistently yet. The file path indeed includes a dot though.

```sh
ERR_FILE_NOT_FOUND (-6) loading 'file:///D:/something/app.asar/ui/page.html'
    at rejectAndCleanup (electron/js2c/browser_init.js:205:1493)
    at Object.failListener (electron/js2c/browser_init.js:205:1706)
    at Object.emit (events.js:315:20)
```
