### ISSUE TITLE
Unable to embed a website with `frame-ancestors *` on `chrome-extension` scheme

### ISSUE THREAD

**Issue by sentialx** [electron/electron#27324]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.0 - master
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
`<iframe>` loads a website with `frame-ancestors *` in Chrome within a `chrome-extension` scheme.
![image](https://user-images.githubusercontent.com/11065386/104615921-05571200-568a-11eb-9ca4-cba00ae9057b.png)

### Actual Behavior
Hello world is not showing in an `<iframe>` in Electron.

### To Reproduce

git clone -b frame-ancestors https://github.com/sentialx/electron-quick-start
cd electron-quick-start
npm start

**Comment by zdnk** [comment]
same issue here
