### ISSUE TITLE
setContentProtection not working on MacOS，when used QucikTime player

### ISSUE THREAD

**Issue by aizhimin** [electron/electron#27331]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  * 11.1.1
* **Operating System:** 
  * macOS Catalina  10.15.7
* **Last Known Working Electron version:** 
  * 11.1.1

### Expected Behavior

I want to protection my content.  when I use QucikTime Player, 

### Actual Behavior

"setContentProtection(true)"  is not working.  QucikTime Player can record my content.

### To Reproduce

我们设置了防止捕获屏幕内容：setContentProtection(true)。但是用QucikTime Player软件，却可以录制我们的屏幕。

**Comment by codebytere** [comment]
In order to triage this, we are going to need a standalone piece of code we could, for example. run in [Fiddle](https://github.com/electron/fiddle). If this is not addressed this issue will be closed in 7 days.

**Comment by miniak** [comment]
This is a macOS limitation, nothing we can do about it I am afraid.
