### ISSUE TITLE
hardcrash when closing a window that used to have a BrowserView in it

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#27330]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 11.2.0
* **Operating System:** Windows 10

### Expected Behavior
I expect that closing a window after having detached its BrowserView and destroyed it will not hard crash Electron.

### Actual Behavior
Electron hard crashes and my app dies

### To Reproduce
I haven't yet found a minimal example that repros this but the gist is that I have a window with a BrowserView, and I want to close the window. The logic I run is:

```
const win: Electron.BrowserWindow = browserWindowFromWebContentsId(wcID);

// We need to unset the BrowserView before destroying the webContents to avoid an Electron crash
win.setBrowserView(null);
(browserViewFromWebContentsId(wcID).webContents as any).destroy();

win.close();
```
We get to the `win.close()` statement and execute it without issue, but my window's `close` handler doesn't even run and it hard crashes.

The weird thing is that when I'm focused on the BrowserView and hit the hotkey (I added) to close the window, it works fine. But when I'm focused on the BrowserWindow, but not the BrowserView and hit the hotkey, I get a hardcrash.

I get two crash dumps:

[dumps.zip](https://github.com/electron/electron/files/5817812/dumps.zip)

**Comment by pushkin-** [comment]
It seems like this could be fixed by [this PR](https://github.com/electron/electron/pull/27315)

**Comment by codebytere** [comment]
@pushkin- can you please provide a gist for Fiddle to verify?

**Comment by pushkin-** [comment]
@codebytere This is basically my minimal example:

main.js:
```
const { app, BrowserWindow, BrowserView, ipcMain } = require('electron')
const { join } = require("path");

let view, mainWindow, win;
async function createWindow() {
  mainWindow = new BrowserWindow({ webPreferences: { nodeIntegration: true, nativeWindowOpen: true } });
  mainWindow.removeMenu();

  await mainWindow.loadFile('index.html')

  mainWindow.webContents.on("new-window", async (e, url, frameNAme, disp, opts) => {
    e.preventDefault();
    opts.webPreferences.nodeIntegration = true;
    opts.webPreferences.sandbox = false;
    opts.backgroundColor = "#000";

    view = new BrowserView({ webPreferences: { sandbox: true } });
    win = new BrowserWindow(opts);

    e.newGuest = win;

    await new Promise(r => setTimeout(r, 1000)); // necessary for the index.html to get loaded properly into the window

    win.setBrowserView(view);
    win.removeMenu();

    await win.loadFile(join(__dirname, "index.html"));

    const bounds = win.getContentBounds();
    view.setBounds({ x: 0, y: 50, width: bounds.width, height: bounds.height - 50 });

    view.webContents.on("before-input-event", (e, details) => {
      if (details.type === "keyDown" && details.control && details.key === "w") {
        setTimeout(() => {
          closeWindow();
        }, 500);
      }
    });

    await view.webContents.loadURL(url);
  });

  ipcMain.on("closeWindow", () => {
    closeWindow();
  });
}

function closeWindow() {
  win.setBrowserView(null);
  view.webContents.destroy();
  win.close(); // doing this in a setTimeout works around the crash
}

app.whenReady().then(createWindow)

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})
```

index.html:
```
<!DOCTYPE html>
<html>
<body>
  <button onclick="window.open('https://google.com', 'a')">Open Window</button>
  <script>
    const { ipcRenderer } = require("electron");
    window.addEventListener("keydown", (e) => {
      if (e.ctrlKey && e.key === "w") {
        ipcRenderer.send("closeWindow");
      }
    })
  </script>
</body>
</html>
```

1. start main.js
2. click Open Window
3. If you focus in the BrowserView and hit Ctrl+W, the window closes (notice we already do the close asynchronously. If we removed the setTimeout we would also get a crash [same exit code I believe])
4. If you open a window and focus on the 50 pixel area at the top (that contains the button), and then hit Ctrl+W, Electron will hard crash.
5. Wrapping `win.close()` in a `setTimeout` will work around this

**Comment by codebytere** [comment]
Yep - fixed in https://github.com/electron/electron/pull/27315!
