### ISSUE TITLE
The publisher of the Windows Control Panel is blank

### ISSUE THREAD

**Issue by KazukiSugiyama107** [electron/electron#27347]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.2.3
* **Operating System:**
  *  Windows10
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
Can be displayed to the publisher

### Actual Behavior
The publisher will be blank

### To Reproduce
I have added the following property to `module.exports` of `vue.contig.js` and confirmed the operation.
・publisherName
・owner

・module.exports 
```
win: {
  icon: 'build/icons/xxx.ico',
  target: [
    {
      target: 'nsis-web',
      arch: [
        'x64',
        'ia32'
      ]
    }
  ],
  publish: {
    provider: 'generic',
    url: 'https://download.xxx.com/win',
    owner: ‘publisher name’
  },
  publisherName: 'publisher name',
},
```

### Screenshots
![Publisher](https://user-images.githubusercontent.com/70558785/104893494-d822a080-59b6-11eb-8641-2cd031ec48f7.png)

**Comment by codebytere** [comment]
@KazukiSugiyama107  Electron 8 is [no longer supported](https://www.electronjs.org/docs/tutorial/support). For us to continue triaging this, it must be reproducible on a supported version.

**Comment by KazukiSugiyama107** [comment]
@codebytere 
Thank you for your reply.
I changed the version of Electron to 9, but I'm having the same problem.

**Comment by miniak** [comment]
This seems to be an issue with your packager, not Electron itself.
