### ISSUE TITLE
DesktopCapture - Recording a single window autio

### ISSUE THREAD

**Issue by pl4yradam** [electron/electron#27343]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 6.14.6
* **Operating System:**
  * Windows 10 -->
* **Last Known Working Electron version:**
  *  Unknown

### Expected Behavior

When specifying the **chromeMediaSourceId** with the correct id, the stream would only record that audio

### Actual Behavior

The whole desktop audio records

### To Reproduce
To reproduce setup exactly the same as the docs:
```
 const gameConstraints = {
            audio: {
                mandatory: {
                    chromeMediaSource: 'desktop',
                    chromeMediaSourceId: this.selectedWindow.value.id,
                }
            },
            video: {
                mandatory: {
                    chromeMediaSource: 'desktop',
                    chromeMediaSourceId: this.selectedWindow.value.id,
                    minWidth: 1280,
                    maxWidth: 1280,
                    minHeight: 720,
                    maxHeight: 720
                }
            }
        };

```
Use the above as an example for the constraints

### Additional Information
I have tried varied ways of setting the options using 'screen' removing chromeMediaSource, I have also tried just recording the audio track.

I'm hoping I'm missing something as I would prefer not to go down a custom ffmpeg route. If anyone needs further details let me know.

**Comment by codebytere** [comment]
@Jonexuan Electron 6 is [no longer supported](https://www.electronjs.org/docs/tutorial/support). For us to continue triaging this, it must be reproducible on a supported version.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
