### ISSUE TITLE
Showing initially hidden window containing BrowserView displays blank view until window is moved or unfocused

### ISSUE THREAD

**Issue by pingviini** [electron/electron#27353]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 12.0.0-beta14, 11.2.0, 11.1.1
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 10.3.0

### Expected Behavior
Hidden BrowserWindow containing BrowserView with web page contents loaded should display the web page when BrowserWindow.show() -method is called.

### Actual Behavior
Blank window is displayed. Content is displayed only after triggering some external action e.g. resizing the application window, moving window or unfocusing window by e.g. activating Windows start menu or some other application

### To Reproduce
Following Electron Fiddle gist contains example where there are two BrowserWindows - first one is a "loader window" and the second window is main window containing BrowserView with www.electronjs.org page opened. Loader view contains two buttons - first button closes the loader and shows the main BrowserWindow where the issue can be investigated. Second button does the same, but has short (500ms) sleep between closing the loader window and opening the main window - this seems to fix the issue.

https://gist.github.com/2faffe95a51640da8c0e19545f2f6ce9

**Comment by hatsantos** [comment]
Same issue... my app uses a splashscreen in the initial load (a window with no frame and a image) while the main window loads... The main windows is hidden by default. After the main windows is ready, the splashscreen window is hidden and the main window is presented, but this results in a white screen until a move/drag the main window, resize it or minimize/maximize it.

The apps works with no problems in version 10.3.0, and presents this issue in current version 11.2.0.

**Comment by MRayermannMSFT** [comment]
I am seeing this as well on 11.3.0, and I am coming from 8.5.5. I also initially use a splash screen, and then show a main window.

**Comment by 255kb** [comment]
I can reproduce this issue on v12.0.1
The content and the dev tools appears frozen until I move the window: 
![image](https://user-images.githubusercontent.com/7489814/111761750-873d0480-88a0-11eb-9d49-c097ceb4727a.png)
This happens erratically, half of the time I would say. Dev tools opened or not. 
I also have a splash screen that I close when I get the `dom-ready` or `did-finish-load` event (one or the other, it doesn't make a difference). 

```
mainWindow.webContents.on('dom-ready', () => {
  if (splashScreen) {
    splashScreen.close();
  }
  mainWindow.show();
});
```

Adding a delay between the closing of the splash screen and the `mainWindow.show` solves the issue: 
```
mainWindow.webContents.on('dom-ready', () => {
  if (splashScreen) {
    splashScreen.close();
  }
  setTimeout(() => {
    mainWindow.show();
  }, 1000);
});
```

**Comment by pushkin-** [comment]
Hmm somewhat [similar](https://github.com/electron/electron/issues/28255). I have a window that focuses the webcontents in the `dom-ready` event (and your `show() `call will focus the window), and I get a blank view until I move the window. Though for me this is happening when a navigation happens (which triggers the `dom-ready`) while the machine is locked.

**Comment by Avlyssna** [comment]
As I mentioned in my issue #29050, you may have luck calling `destroy` on the splash screen _after_ the call to `show` on your main window - instead of the other way around. It seems that when I do it that way in my application, the renderer doesn't freeze-up.

**Comment by MRayermannMSFT** [comment]
I believe this is still reproducing in v13 as well....

**Comment by mor-o** [comment]
Try using `backgroundThrottling = true` when creating the BrowserWindow.
worked for me.

**Comment by dotMortis** [comment]
Ran into the same issue

**Comment by codebytere** [comment]
This was fixed in https://github.com/electron/electron/pull/29919 - I just opened a PR to v13.
