### ISSUE TITLE
WebAuthn authentication prompt does not work on macOS

### ISSUE THREAD

**Issue by CBMasri** [electron/electron#27355]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

The authentication prompt for public key credentials is not working/supported in electron on macOS. Platform authenticators (eg. Windows Hello, TouchID) do not appear to be supported for any o/s.

* **Electron Version:**
  * 11.1.1
* **Operating System:**
  * macOS 11.0.1 (M1)
* **Last Known Working Electron version:**
  *  n/a

### Expected Behavior

Call to `navigator.credentials.create({ publicKey: ... })` opens an authentication prompt on macOS.

### Actual Behavior

Call to `navigator.credentials.create({ publicKey: ... })` times out and no prompt is displayed.

### To Reproduce

1. Load fiddle: https://gist.github.com/0e76ea8515d171c3e747c8814a8a659b
2. Type a username
3. Click "Register"
4. Request times out after ~1m

### Screenshots

Request timeout:

![image](https://user-images.githubusercontent.com/10861443/104972104-a523e100-59a5-11eb-9fe1-4dd1f56a9083.png)

On Windows, the authentication prompt is displayed:

<img width="618" alt="explorer_D7xRi9J9eM" src="https://user-images.githubusercontent.com/10861443/104971759-9852bd80-59a4-11eb-9231-df44cd4b3c13.png">

It also works on Chromium (macOS):

![image](https://user-images.githubusercontent.com/10861443/104971521-def3e800-59a3-11eb-9a05-0c07359f64bc.png)

### Additional Information

Related Issues:
- https://github.com/electron/electron/issues/15404
- https://github.com/electron/electron/issues/24573

**Comment by fix** [comment]
Hi, I have not tested, but from my recent experience might be that user interaction is REQUIRED before performing credentials create/get request

See https://developer.apple.com/forums/thread/651669

I had no choice but do a popup clicked by the user before so it does not timeout.

**Comment by fix** [comment]
ok i have made some test.

On macOS, actually, there is no popup, BUT the request is being made on your key (Hit your yubikey and it works)!

Sounds the interface to communicate (asking for pin for instance) is not bound into macOS build.

I have the following errors in the console:

```
[42622:0406/171907.136506:ERROR:device_event_log_impl.cc(214)] [17:19:07.136] FIDO: fido_request_handler_base.cc:183 Cannot test Bluetooth power status because process is not self-responsible. Launch from Finder to fix.
[42622:0406/171919.350892:ERROR:device_event_log_impl.cc(214)] [17:19:19.350] FIDO: get_assertion_request_handler.cc:648 Failing assertion request due to status 46 from usb-1050:0402
```

**Comment by danyg** [comment]
This still an issue
Electron 25.2.0
Mac OSX: 13.4.1 (Apple Silicon, M1 Pro)

**Comment by Binomi0** [comment]
This still an issue
Electron 22
Mac OSX: 13.4.1 (Apple Silicon, M1 Pro)

**Comment by SagaciousLittle** [comment]
any update about this? it's not work in electron@^26.1.0 in mac

**Comment by mahnunchik** [comment]
Why it is closed? It is still present in electron 28

**Comment by mahnunchik** [comment]
> The workflow is not valid. .github/workflows/issue-commented.yml (Line: 13, Col: 9): Unexpected symbol: '"Bot"'. Located at position 190 within expression: contains(github.event.issue.labels.*.name, 'blocked/need-repro') && !contains(fromJSON('["MEMBER", "OWNER"]'), github.event.comment.author_association) && github.event.comment.user.type != "Bot"

https://github.com/electron/electron/actions/runs/6201050660

**Comment by WyattMufson** [comment]
Still an issue

**Comment by vikram1992** [comment]
Is there any plan to fix this issue?

**Comment by shengliang74** [comment]
It is still present in electron V33.2.1, I hope it can be fixed.

**Comment by gavan1** [comment]
@fix did you manage to get it to work I have the following error on macos.

```
[75159:0328/142735.584924:ERROR:device_event_log_impl.cc(201)] [14:27:35.584] FIDO: fido_discovery_factory.cc:70 Cannot start caBLE because process is not self-responsible. Launch from Finder to fix.
[75159:0328/142735.585025:ERROR:device_event_log_impl.cc(201)] [14:27:35.584] FIDO: fido_request_handler_base.cc:294 Cannot test Bluetooth power status because process is not self-responsible. Launch from Finder to fix.
```
so no dialog prompt shows up

**Comment by SagaciousLittle** [comment]
dump

**Comment by emiosproj** [comment]
bump, still an issue in electron 36.2.0. Can be tested with https://webauthn.io/

**Comment by pavlo-liapin** [comment]
We've released an open-source add-on that fills in the missing behavior by calling Apple's lower-level APIs directly - https://github.com/vault12/electron-webauthn-mac.

Just be aware that macOS requires a bit more setup than a browser environment - there are a few platform-specific configurations to add. Our README covers everything this step-by-step.

Feedback, issue reports, and pull requests are very welcome.
