### ISSUE TITLE
Electron default app freezes when run from a network shared drive

### ISSUE THREAD

**Issue by Gregg8** [electron/electron#27356]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.1.1
* **Operating System:**
  * Windows 10 Pro (2004)
* **Last Known Working Electron version:**
  * 5.0.13

### Expected Behavior

The Electron default app should start, no matter where it is run from

### Actual Behavior

Under Windows...
 - When run from a local drive (drive C/D or a USB drive), the app starts as expected
 - When run from a network shared drive (tested on QNAP NAS but our clients have issues in Windows Server, various versions), the app does not start (no window is seen).

No issues when run on Linux.

Don't have access to a Mac.

### To Reproduce

Steps:
 - Latest Electron is here: https://github.com/electron/electron/releases/tag/v11.1.1
 - Download the zip for your platform
 - I downloaded this Windows one: https://github.com/electron/electron/releases/download/v11.1.1/electron-v11.1.1-win32-x64.zip
 - Extract the files 
 - Run `electron.exe` - it works
 - Copy this unzipped folder to a network/NAS shared drive (not a USB drive)
 - Run `electron.exe` - it fails to start

### Additional Information

Although the steps to reproduce are for the default Electron app, our actual client app is having a number of issues after upgrading to version `11.1.1` (listed below).

Our app, which currently uses Electron `1.6.10` (yes, yes, very old, just getting around to upgrading now) is installed on our client network shared drives so we cannot upgrade until this issue is resolved.

After a lot of bisecting, I found that Electron version `5.0.13` is the latest version that works.

From `6.0.0-beta.1` on, it fails (although I only tested a small sample).

When it works, four instances of `electron.exe` are instantiated. Apart from the initial one, the other types are `utility`, `gpu-process` and `renderer`. They all start immediately.

When it doesn't work, we only get two (for `11.1.1` and sometimes one for other versions) . Unsurprisingly, the missing ones are `gpu-process` and `renderer`. I noted that the `utility` instance doesn't appear instantly. It appears around one second later.

I see that version `6.0.0-beta.1` was released on May-2019 and on searching for issues sometime after that, I found the following that looked related:
 - https://github.com/electron/electron/issues/19589 - we also experience not being able to get Devtools running
 - https://github.com/electron/electron/issues/20069 - DevTools again (note it happens from v6)
 - https://github.com/electron/electron/issues/21029 - one of our clients also experience a crash
 - https://github.com/electron/electron/issues/21713 - haven't experienced this one but it's network share related

And they are all still open.

The issues we experience when our app is upgraded to `11.1.1 `are various:
 - On my machine, the app starts from a network shared drive, but I get the DevTools issue and our Flash plugin (yeah, still using it) fails to load
 - Client 1 - app crashes on startup
 - Client 2 - app shows blank screen on startup when anti-virus is enabled (and even when the directory is whitelisted) but runs when turned off
 - Client 3 - blank screen on startup

In all the above cases:
 - The app works on the C drive
 - The original version (using Electron `1.6.10`) runs fine on the network shared drive

**Comment by miniak** [comment]
It's somehow related to the sandbox. Running `electron.exe --no-sandbox` works.

**Comment by mmasdivins** [comment]
It happens with electron 13.1.4, is there any workaround or solution apart of running our app with --no-sandbox?

**Comment by nornagon** [comment]
Unfortunately this is a Chromium limitation: https://bugs.chromium.org/p/chromium/issues/detail?id=103902#c27

**Comment by slimhk45** [comment]
This issue seems to affect [Obsidian.md](https://obsidian.md/) too.
