### ISSUE TITLE
"gl_out_of_memory crash" on windows 7 And my Solution

### ISSUE THREAD

**Issue by Jonexuan** [electron/electron#27365]
### Preflight Checklist

* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  8.1.1
* **Operating System:** 
  *  windows 7
* **Last Known Working Electron version:**
  *  5.0.0

### Expected Behavior

My Application use WebGL to display mounts of moving targets on the screen,I hope it could be smoothly.
### Actual Behavior

My Production Application seems pretty good on most of the PC,but they run into blank screen or black screen on a few PC.
I start the app with commandLine,the error goes like "l_out_of_memory crash" repeatedly.
### To Reproduce

window 7 && Application with useage of WebGL such as [Pixi.js](https://www.pixijs.com/)

### Screenshots

![image](https://user-images.githubusercontent.com/6253700/105048550-aab52000-5aa6-11eb-9011-7cfb10bb770f.png)
the same image as #21500

### Additional Information

I hava test my application without WebGL, It worls fine.So i believe something wrong with the GPU relate API.
My solution is to replace the "d3dcompiler_47.dll" with the same file from newest Chrome Browser, and then my application works.I dont know much about .dll file,so i figure out the maybe can help improve this great REPOSITORY.
I'll be glad  to help if you want more information.
OtherWise there's a relation issuse   #21500 , which is not totally resolved.

**Comment by codebytere** [comment]
@Jonexuan Electron 8 is [no longer supported](https://www.electronjs.org/docs/tutorial/support). For us to continue triaging this, it must be reproducible on a supported version.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
