### ISSUE TITLE
BrowserView: flickers when switching between view

### ISSUE THREAD

**Issue by kevinlinv** [electron/electron#27378]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 10.1.7 and beyond (I tested on latest 11.2.0 too)
* **Operating System** macOS 10.15.7
* **Last Known Working Electron version:** 10.1.6

NOTE: tested in windows, the bug is not present.

### Expected Behavior

Switching browser view should **not flickers**.

### Actual Behavior

Switching browser view **flickers**.

### To Reproduce

Load electron fiddle friendly gist here https://gist.github.com/kevinlinv/eada1e5bdd1282db338971c4c42c671e

<details>
<summary>Collapse here for the code in case gist is not loading</summary>

`index.html`
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
    <link rel="stylesheet" type="text/css" href="./styles.css">
  </head>
  <body>
    <div style="display:flex">
      <p style="margin:0px; padding: 5px">MyApp</p>
      <button id="tab1">tab1</button>
      <button id="tab2">tab2</button>
    </div>
    <script>
      // You can also require other files to run in this process
      require('./renderer.js')
    </script>
  </body>
</html>
```

`main.js`
```js
const {app, ipcMain, BrowserView, BrowserWindow} = require('electron')

function createWindow () {
  const mainWindow = new BrowserWindow({
    width: 1080,
    height: 720,
    webPreferences: { nodeIntegration: true }
  })
  

  const views = [
    createView({ backgroundColor: '#ddd', url: 'https://www.youtube.com/watch?v=RDfjXj5EGqI' }),
    createView({ backgroundColor: '#000', url: 'https://electronjs.org' }),
  ];
  const focusView = (id) => {
    const { width, height } = mainWindow.getContentBounds();
    const windowContentHeight = 40;
    mainWindow.setBrowserView(views[id]);
    views[id].setBounds({
      x: 0,
      y: windowContentHeight, 
      width,
      height: height - windowContentHeight,
    });
  }
  ipcMain.handle('onTabClick', (_, id) => focusView(id))

  focusView(0)
  mainWindow.loadFile('index.html')
}

function createView({ backgroundColor, url }) {
  const browserView = new BrowserView();
  browserView.setBackgroundColor(backgroundColor);
  browserView.setAutoResize({
    width: true,
    height: true,
    horizontal: false,
    vertical: false,
  });
  browserView.webContents.loadURL(url);
  return browserView;
}
app.whenReady().then(createWindow)

app.on('window-all-closed', app.quit)
```

`renderer.js`
```js
const {ipcRenderer} = require('electron')
const handleClick = id => ipcRenderer.invoke('onTabClick', id)

document.getElementById('tab1').addEventListener('click', () => handleClick(0))
document.getElementById('tab2').addEventListener('click', () => handleClick(1))
```

</details>

### Screenshots

The first part: the problem
The second part: expected behavior

https://user-images.githubusercontent.com/44967897/105120572-93b61280-5b26-11eb-8a18-0846939d0625.mp4

**Comment by ckerr** [comment]
Possibly mac-only.

When testing on Ubuntu 20.10 + Electron 11.2.0 I am not seeing flicker when I switch between views in @kevinlinv's testcase gist

**Comment by kevinlinv** [comment]
Thank you for the quick action on this @codebytere Much appreciated 🙌

**Comment by poisonReact** [comment]
a similar bug reappeared https://github.com/electron/electron/issues/34169
