### ISSUE TITLE
Is there any method to print a pdf, with silent.

### ISSUE THREAD

**Issue by LFdeWeb** [electron/electron#27383]
That's expected behavior at present - our PDF viewer is implemented via Chromium's extensions handling and cannot be printed via `webContents.print()`.

_Originally posted by @codebytere in https://github.com/electron/electron/issues/26448#issuecomment-725598179_

**Comment by nick318** [comment]
@LFdeWeb Do you know the way how to print pdf?

**Comment by LFdeWeb** [comment]
> @LFdeWeb Do you know the way how to print pdf silently?

yes. I use it, https://www.npmjs.com/package/node-pdf-printer.
