### ISSUE TITLE
Cookies: Not possible to set cookie with domain not starting with "."

### ISSUE THREAD

**Issue by M0rious** [electron/electron#27392]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v.11.2.0
* **Operating System:**
  * Windows 10

### Expected Behavior
If I set a cookie with the following details:
`{
                    domain: "google.de",
                    httpOnly: true,
                    name: "testcookie",
                    path: "/",
                    url: "https://www.google.de",
                    value: "cookie.value",
                    secure: true,
                    sameSite: "unspecified"
  }`
I expect the domain in the Dev-Tools to be google.de
### Actual Behavior
The domain set is .google.de

### To Reproduce
https://gist.github.com/8eb5f5031774f445bbc1e74277cdf553

### Screenshots
![image](https://user-images.githubusercontent.com/9660882/105166865-3fa43180-5b18-11eb-939e-d71b582e91d7.png)

### Additional Information
Why is this a problem?
We use Electron to automate login in a corporate environment.
The target application is hosted on IBM Websphere which assigns the user a cookie named LtpaToken2 which is used for some WAS internal caching - without or with an invalid LtpaToken2 the user and its permissions get checked against the configured authentication provider - suffice to say, having a valid LtpaToken2 is needed for a smooth operation of the system.
The LtpaToken2 is backed up by the electron application to be reused later.
This does not work at the moment, since WAS sets the LtpaToken2 Cookie without the leading "." in the domain, with electron we can only set a cookie with a leading ".".
This leads to two LtpaToken2 Cookies being present -> which leads to the caching not working:
![image](https://user-images.githubusercontent.com/9660882/105167862-8e9e9680-5b19-11eb-9ef5-533b05f238de.png)
The cookie with the "." in the beginning is the "restored" cookie by Electron - the one without the "." is the one set by WAS.

**Comment by t57ser** [comment]
This is still an issue. Can this be reopened?
