### ISSUE TITLE
os.cpus() return an empty array on Mac Silicon

### ISSUE THREAD

**Issue by gmantri** [electron/electron#27404]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.1.0
* **Operating System:**
  * macOS BigSur (Apple Silicon)
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
`os.cpus()` should return an array of logical processors in an Electron app running natively on Apple Silicon platform.

### Actual Behavior
`os.cpus()` returns an empty array in an Electron app running natively on Apple Silicon platform. This works well on x64 based Mac machines.

### To Reproduce
const os = require('os');
const cpus = os.cpus();
console.log(cpus);//prints empty array

### Additional Information
When I run the code above in a node file, it works well on Apple Silicon platform. Only inside an Electron app, I am getting an empty array.

Please let me know if more information is needed from my side.

**Comment by miniak** [comment]
@gmantri are you running the arm64 or x64 build of Electron?

**Comment by gmantri** [comment]
> @gmantri are you running the arm64 or x64 build of Electron?

@miniak Thanks. I am running arm64 build of Electron.

**Comment by wizebin** [comment]
This seems to work just fine in electron v12.x

![Screen Shot 2021-01-26 at 12 43 16 PM](https://user-images.githubusercontent.com/18584095/105882796-154ceb00-5fd4-11eb-9b8b-bd9de9d73a0a.png)

But fails in 11.x

![Screen Shot 2021-01-26 at 12 44 04 PM](https://user-images.githubusercontent.com/18584095/105882867-2e559c00-5fd4-11eb-9dc2-e50f4a78d23a.png)

I tried 11.0.0, 11.1.1, 11.2.1 which all just show a blank array
12.0.0-beta.1, 12.0.0-beta.9, 12.0.0-beta.18 all show the correct information

**Comment by gmantri** [comment]
Thanks @wizebin for checking this out. It is very much appreciated. I guess we will just have to wait for version 12 to be generally available. In the meantime, I have used the following workaround:

```
const os = require('os');
const getProcessorsCount = () => {
  let processorsCount = 8;//Let's assume 8 logical processors by default.
  const cpus = os.cpus();
  if (typeof cpus !== 'undefined' && typeof cpus === 'object' && Array.isArray(cpus) && cpus.length > 0) {
    processorsCount = cpus.length;
  }
  return processorsCount;
};
```

I am going to close this issue now. Thanks to everyone who participated.
