### ISSUE TITLE
Unmaximizing hidden window leaves it in a non-responsive rendering state

### ISSUE THREAD

**Issue by samuelmaddock** [electron/electron#27429]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.5.5
  * 9.4.1
  * 10.3.0
  * 11.2.0
  * 12.0.0-beta.16
* **Operating System:**
  * Windows 10 (2004)
* **Last Known Working Electron version:**
  * None? 🤔

### Expected Behavior
Unmaximizing a hidden window should ideally unset the maximized state without revealing the window. This is the behavior seen on macOS.

### Actual Behavior
Upon unmaximizing the hidden window, it is revealed in a state where interaction is disabled and no updates are painted.

### To Reproduce
1. Load https://gist.github.com/3ebea5ed1d5057b49eb4f910d41b53c5 in Electron Fiddle.
2. Smash that Run button.

### Screenshots
![2021-01-20_23-25-58](https://user-images.githubusercontent.com/1656324/105280031-e0c1d500-5b76-11eb-8ce3-4d30b236fe25.gif)

**Comment by ckerr** [comment]
Confirmed with Electron 12.0.0-beta.16 and 11.2.1. When resizing, I'm seeing the same behavior as in @samuelmaddock's screenshot.

Appears to be Windows-only. WfM on Linux and the original description mentions it working on macOS.

**Comment by samuelmaddock** [comment]
Repros in v21.1.0
