### ISSUE TITLE
interceptHttpProtocol introduces random data corruption

### ISSUE THREAD

**Issue by lucybythec** [electron/electron#27426]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v11.1.1
* **Operating System:**
  * Linux 5.10.7 / Windows 10 (1803)
* **Last Known Working Electron version:**
  * unknown

### Expected Behavior
Using `interceptHttpProtocol` should not introduce random data corruption.

### Actual Behavior
Apparently, when `interceptHttpProtocol` is used (by itself), it introduces random corruption in transfered data.

### To Reproduce
Enable `interceptHttpProtocol` with no other behavior, e.g.:

```js
  protocol.interceptHttpProtocol('http', (request, callback) => {
    console.log('interceptHttpProtocol:', request)
    request.session = null
    callback(request)
  })
```

Then load a large file. I noticed this issue with JavaScript scripts, possibly other file types are affected.

Full test case can be found here:
https://github.com/lucybythec/electron-intercept-bug/blob/master/main.js

```sh
$ git clone https://github.com/lucybythec/electron-intercept-bug
$ cd electron-intercept-bug
$ npm install
$ npm start
```

In the example, the loaded page should print the MD5 of data contained in a big file.
However, very often the data corruption results in a syntax error instead.
(Check the "Console" tab in the Dev Tools).

I reproduce the problem on Windows and Linux.
Due to the random nature of the problem, it may not reproduce the first time. The application may need to be restarted several times.

### Screenshots
Example of corruption:
![image](https://user-images.githubusercontent.com/75380261/105265976-02c45300-5b89-11eb-821e-7fc9f99a7c1e.png)
![image](https://user-images.githubusercontent.com/75380261/105265500-cdb80080-5b88-11eb-95a8-28b134609998.png)

### Additional Information

Tested on different machines, so this is not a hardware defect.

**Comment by ckerr** [comment]
Confirmed with v11.2.1 on Linux.

I haven't read the test code yet or determined the source of the issue.

I _can_ confirm the behavior reported that the contents of test.js are getting mangled for me in the same way described above. It happened 2 times out of 3 test runs for me, in different places each time. Since it seems to be random data being dropped from the file's contents, you might get a syntax error (I did) that prevents you from even checking the checksum.

**Comment by lucybythec** [comment]
Thank you for looking at this.

> I haven't read the test code yet

It might be easier to look at the changes (compared to the electron-quick-start base). The changes are very simple:

https://github.com/lucybythec/electron-intercept-bug/commits/master

**Comment by dsanders11** [comment]
Here's a [Fiddle gist](https://gist.github.com/51f61c0fae16268cc27cb957fcf6cf5f) which reproduces the bug. I trimmed all the unnecessary stuff, you just need the large file to reproduce. I'm not sure why `session` needs to be set to `null` to trigger reproducing, though.
