### ISSUE TITLE
[Feature Request]: remote property  dosn't exit in require('electron')

### ISSUE THREAD

**Issue by binvb** [electron/electron#27432]
**Preflight Checklist**

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Problem Description**

i can't found remote property in require('electron'), here is my electron property list: 
```
clipboard: [Getter],
  shell: [Getter],
  app: [Getter],
  autoUpdater: [Getter],
  BaseWindow: [Getter],
  BrowserView: [Getter],
  BrowserWindow: [Getter],
  contentTracing: [Getter],
  crashReporter: [Getter],
  dialog: [Getter],
  globalShortcut: [Getter],
  ipcMain: [Getter],
  inAppPurchase: [Getter],
  Menu: [Getter],
  MenuItem: [Getter],
  MessageChannelMain: [Getter],
  nativeImage: [Getter],
  nativeTheme: [Getter],
  net: [Getter],
  netLog: [Getter],
  Notification: [Getter],
  powerMonitor: [Getter],
  powerSaveBlocker: [Getter],
  protocol: [Getter],
  screen: [Getter],
  session: [Getter],
  systemPreferences: [Getter],
  TouchBar: [Getter],
  Tray: [Getter],
  View: [Getter],
  webContents: [Getter],
  WebContentsView: [Getter],
  desktopCapturer: [Getter],
  ImageView: [Getter]
```

my electron version is electron@11.2.0, can somebody help? or just not update the document yet?

**Proposed Solution**

not yet

**Alternatives Considered**

not yet

**Additional Information**

_No response_

**Comment by lucybythec** [comment]
https://www.electronjs.org/docs/api/remote says "Process: Renderer"

Maybe you are trying to access it in the wrong (main) process?

**Comment by codebytere** [comment]
You need to pass the [documented](https://github.com/electron/electron/blob/c3091c3a7074b2eef03a14dc4b44b7b05a9248ac/docs%2Fapi%2Fbrowser-window.md#L276-L277) `enableRemoteModule` property to your BrowserWindow constructor.
