### ISSUE TITLE
Renderer entirely hangs with "uncaught illegal access" when loading page with 2 iframes, nodeIntegrationInSubFrames, and node-ipc

### ISSUE THREAD

**Issue by Patronics** [electron/electron#27457]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.2.1, also verfied on Electron 10.2.x and 9.0.0
* **Operating System:**
  * verified on MacOS 10.14.6, MacOS 11.1, Debian 4.19.160-2, and Debian 5.9.15
* **Last Known Working Electron version:**
Electron 8.5.5 works.

### Expected Behavior
Page sucessfully loads and js continues running normally.

### Actual Behavior
The render window completely hangs partway through loading, is unresponsive to all input including the developer console, and can only be killed from the main process, or by killing the main process. When loading for the first time, there's no output in the developer console, but when reloading an intermittent form of the bug (by wrapping the node-ipc connectTo call in an async function with a delay) following stack trace is sometimes displayed: 
![Screen Shot 2021-01-15 at 5 45 55 PM](https://user-images.githubusercontent.com/9359101/105620751-076d4f00-5db5-11eb-99bf-336a2e12f99f.png). Although the error is displayed as being on line 1 of my html file, line 1 is simply `<html>`, so that's obviously not correct. 

### To Reproduce

Install [this minimal example project. ](https://github.com/Patronics/example-electron-hang) by runing

```sh
$ git clone https://github.com/Patronics/example-electron-hang.git
$ npm install
$ npm start
```
Notice that when running the app, the big iframe's contents never load, and the app is unresponsive to the normal keyboard shortcuts to interact with it (Quit, open the, dev tools, etc.). Look at the source code (especially index.html) to see that the JS abruptly stops running, unlike it expected behavior. The comments describe which lines seem necessary to trigger the bug, and which are just to demonstrate the behavior.

### Additional Information

I'm submitting the issue here as well as node-ipc's repository, as the issue seems to be in the interaction of the two codebases. However, the set of unique circumstances in the electron configuration needed to cause this, as well as the fact that the normal debugging tools like the developer console are rendered non-functional, would seem to indicate that the issue is primarly regarding electron, and not node-ipc. The fact that electron 8.5.5 and eariler don't have this issue would seem to confirm that conclusion.

**Comment by ckerr** [comment]
@Patronics, thanks for reaching out and making this testcase.

When running https://github.com/Patronics/example-electron-hang.git on Linux with Electron 11.2.1, I'm seeing the same hang as reported above. There is also a helpful message saying "hello! If JS didn't hang, you wouldn't have time to read this."  :laughing:

**Comment by codebytere** [comment]
Gist version: https://gist.github.com/8bc74b33bfdc5f99a5b14f2ec6b720dd

**Comment by Patronics** [comment]
@codebytere this still seems to be an issue in the lastest nightly release, at least partially. When running my sample repo, as the page loads you still encounter that "Uncaught illegal access" error messsage in the developer console, identically to the screenshot in my original post. Also, in that situation (which is still able to be made intermittent utilizing a delayed asynchronous function), some longer running aspects of the script stop working (in my company's repo, I haven't yet  added something to demonstrate that in the sample repo).

**Comment by gpetrov** [comment]
@codebytere is this really fixed? As I'm experiencing exact the same error after a few frequent iframe creations.
on Electron 12.0.5

**Comment by Patronics** [comment]
@gpetrov, yeah, same here, that I'm getting continued error messages and breaking JS from this bug, even if it's not as broken as it was initially. I attempted to raise a new issue for it in #27995, but it doesn't seem to have received any attention towards fixing the issue, unfortunately. 

@codebytere, this issue is not entirely fixed, any chance you could take another look at it?

**Comment by codebytere** [comment]
Closing in favor of https://github.com/electron/electron/issues/27457

**Comment by gpetrov** [comment]
@codebytere why is this closed and referenced to the same issue as continued? Mistake maybe?

**Comment by ntbosscher** [comment]
You might find this helpful: https://github.com/electron/electron/pull/29093
