### ISSUE TITLE
WHEN BUILDING ELECTRON-REACT APP WITH Devias Kit Pro theme AND WANT TO BUILD FOR BOTH MAC AND WINDOWS. APP IS INSTALLING BUT FAILED TO LOAD WITH ERROR

### ISSUE THREAD

**Issue by nabajyotitechnoexponent** [electron/electron#27450]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.1.1
* **Operating System:**
  * macOS 10.13.6 / Windows 10
* **Last Known Working Electron version:**
  * 

### Screenshots

![image](https://user-images.githubusercontent.com/77392430/105492264-ade62100-5cdd-11eb-856b-8e0e064b5b06.png)

![Screenshot 2021-01-22 at 6 20 15 PM](https://user-images.githubusercontent.com/77392430/105492880-9fe4d000-5cde-11eb-98e6-8789f2645f03.png)

### Additional Information
My package.json
{
  "name": "@devias-io/material-kit-pro-react",
  "author": "DeviasIO",
  "licence": "UNLICENSED",
  "version": "3.1.0",
  "private": true,
  "proxy": "https://doctorscan.com.au/",
  "scripts": {
    "react-start": "react-scripts start",
    "react-build": "react-scripts build",
    "react-test": "react-scripts test --env=jsdom",
    "react-eject": "react-scripts eject",
    "electron-build": "electron-builder",
    "release": "yarn react-build && electron-builder --publish=always",
    "build": "yarn react-build && yarn electron-build",
    "start": "concurrently \"cross-env BROWSER=none yarn react-start\" \"wait-on http://localhost:3000 && electron .\""
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "ie 11",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "ie 11",
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "dependencies": {
    "@auth0/auth0-spa-js": "^1.11.0",
    "@date-io/core": "^2.8.0",
    "@date-io/moment": "^1.3.13",
    "@fullcalendar/core": "^4.4.2",
    "@fullcalendar/daygrid": "^4.4.2",
    "@fullcalendar/interaction": "^4.4.2",
    "@fullcalendar/list": "^4.4.2",
    "@fullcalendar/react": "^4.4.2",
    "@fullcalendar/timegrid": "^4.4.2",
    "@fullcalendar/timeline": "^4.4.2",
    "@material-ui/core": "^4.11.0",
    "@material-ui/icons": "^4.9.1",
    "@material-ui/lab": "^4.0.0-alpha.56",
    "@material-ui/pickers": "^3.2.10",
    "@material-ui/styles": "^4.10.0",
    "@mdx-js/react": "^1.6.14",
    "@react-pdf/renderer": "^1.6.10",
    "@reduxjs/toolkit": "^1.4.0",
    "apexcharts": "^3.19.3",
    "awesome-phonenumber": "^2.40.0",
    "aws-s3": "^2.0.5",
    "axios": "^0.19.2",
    "axios-mock-adapter": "^1.18.2",
    "change-case": "^4.1.1",
    "chart.js": "^2.9.3",
    "chroma-js": "^2.1.0",
    "clsx": "^1.1.1",
    "create-react-class": "^15.7.0",
    "draft-js": "^0.11.7",
    "firebase": "^8.1.1",
    "formik": "^2.1.5",
    "history": "^4.10.1",
    "immer": "^6.0.9",
    "immutable": "^4.0.0-rc.12",
    "js-cookie": "^2.2.1",
    "jsonwebtoken": "^8.5.1",
    "jss": "^10.3.0",
    "jss-rtl": "^0.3.0",
    "jwt-decode": "^2.2.0",
    "lodash": "^4.17.19",
    "material-ui-phone-number": "^2.2.6",
    "material-ui-time-picker": "^1.3.0",
    "moment": "^2.28.0",
    "notistack": "^0.9.17",
    "nprogress": "^0.2.0",
    "prismjs": "^1.20.0",
    "prop-types": "^15.7.2",
    "react": "^16.13.1",
    "react-add-to-calendar": "^0.1.5",
    "react-apexcharts": "^1.3.7",
    "react-app-polyfill": "^1.0.6",
    "react-beautiful-dnd": "^13.0.0",
    "react-chartjs-2": "^2.9.0",
    "react-dom": "^16.13.1",
    "react-draft-wysiwyg": "^1.14.5",
    "react-dropzone": "^10.2.2",
    "react-feather": "^2.0.8",
    "react-helmet": "^5.2.1",
    "react-markdown": "^4.3.1",
    "react-modal-image": "^2.5.0",
    "react-moment": "^0.9.7",
    "react-pdf": "^5.1.0",
    "react-perfect-scrollbar": "^1.5.8",
    "react-quill": "^1.3.5",
    "react-redux": "^7.2.0",
    "react-router": "^5.2.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^3.4.1",
    "react-select": "^3.1.0",
    "react-webcam": "^5.2.1",
    "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.8",
    "redux-form": "^8.3.6",
    "redux-thunk": "^2.3.0",
    "socket.io-client": "^2.3.1",
    "sweetalert": "^2.1.2",
    "sweetalert2": "^10.3.0",
    "twilio-client": "^1.12.5",
    "twilio-video": "^2.7.2",
    "uuid": "^7.0.3",
    "yup": "^0.28.5",
    "cross-env": "^7.0.3",
    "electron-is-dev": "^1.2.0",
    "electron-updater": "^4.3.5"
  },
  "devDependencies": {
    "eslint": "^6.8.0",
    "eslint-config-airbnb": "^18.2.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-mdx": "^1.7.1",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "^7.20.3",
    "eslint-plugin-react-hooks": "^2.5.1",
    "mdx-loader": "^3.0.2",
    "numeral": "^2.0.6",
    "prettier": "^1.19.1",
    "typescript": "^3.9.7",
    "concurrently": "^5.3.0",
    "electron": "^11.1.1",
    "electron-builder": "^22.9.1",
    "electron-mocha": "^10.0.0",
    "electron-rebuild": "^2.3.4",
    "wait-on": "^5.2.1"
  },
  "main": "public/electron.js",
  "homepage": "./"
}

**Comment by miniak** [comment]
@nabajyotitechnoexponent please don’t use ALL CAPS

**Comment by miniak** [comment]
This does not seem like an issue with Electron itself, but rather your packager
