### ISSUE TITLE
update electron11.0.0 ,when platform is Windows , and use electron-builder build project， input type "file" cannot remember before open file path

### ISSUE THREAD

**Issue by Leafcat801** [electron/electron#27470]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X]  I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to. 

### Issue Details

* **Electron Version:**  11.0.0
  * 
* **Operating System:** Windows 10
  * 
* **Electron-builder  Version:** 22.9.1
  * 

### Expected Behavior

 input type is "file", can remember before file path when electron11.0.0  at Windows.
I use electron11.0.0, electron-builder22.9.1 , and I nom run dev , input file upload files can remember before file path; But, when I npm run build a project, and install the project, it cannot remember before open file path.
### Actual Behavior

 I hope that  not only npm run dev can remember before open files path, but also npm run build can remember too!

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by Leafcat801** [comment]
###  And then, I had build a small demo about electron11.0.0,  I find,  this small demo has not these question, input type "file", upload file, and then upload file again,  it can remember first open the files path. So, I don’t know. Is there anything to set up between our company's project and Electron11.0.0 ???

#### DOM element input，like this:
```
 <input  type="file" accept="image/*" />
```

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our [comment above](https://github.com/electron/electron/issues/27470#issuecomment-766987598). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
