### ISSUE TITLE
"Open file" scrolling buttons not working

### ISSUE THREAD

**Issue by sweettyler** [electron/electron#27479]
This bug was suggested to report to Electron team by VScode developers.
https://github.com/microsoft/vscode/issues/114789

**Comment by ckerr** [comment]
@sweettyler what distro / version is that? E.g. if you run `lsb_release -a` what does the system say?

**Comment by sweettyler** [comment]
Here is the output:

LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.4.1708 (Core) 
Release:	7.4.1708
Codename:	Core

Please let me know if you need more information.

**Comment by ckerr** [comment]
This appears to not be unique to Electron. Upstream Chrome is showing the same behavior for me when I try the file-open dialog in Chrome.

Tested by installing Chrome 88.0.4324.96 on CentOS Linux release 7.9.2009, clicking ctrl-f to open the "open file" dialog, going to a test directory, and then trying to navigate up or down with the arrowbuttons in @sweettyler's screenshot.

@sweettyler, check to see if this has already been filed upstream and, if not, file a new issue there. https://bugs.chromium.org/p/chromium/issues/list

**Comment by sweettyler** [comment]
@ckerr Thanks. Reported.
