### ISSUE TITLE
Why electron takes too long to install? what is exactly happening? 

### ISSUE THREAD

**Issue by Graham1384** [electron/electron#27476]
I want to install electron in my project locally but it takes too long to install and I can't wait for that

I entered 'npm install --save electron' and I had to wait 10 minutes for it to reach 4%!

`Downloading electron-v11.2.1-linux-x64.zip:
 Downloading electron-v11.2.1-linux-x64.zip:
 Downloading electron-v11.2.1-linux-x64.zip:
 Downloading electron-v11.2.1-linux-x64.zip:
 Downloading electron-v11.2.1-linux-x64.zip:
 Downloading electron-v11.2.1-linux-x64.zip:
 Downloading electron-v11.2.1-linux-x64.zip:
 [] 4% ETA: 3528.5 seconds`

and every time I want to install it globally with this command 

sudo npm install -g electron 

I will get this error: Failed at the electron@11.2.1 postinstall script.
here is the image

![Screenshot from 2021-01-25 21-11-23](https://user-images.githubusercontent.com/62774242/105744042-eaba4e00-5f51-11eb-9e2f-fdc7c7e4ffd8.png)

**Comment by ckerr** [comment]
Hi,

**Comment by ckerr** [comment]
Hi @Graham1384, thanks for reaching out!

What did /root/.npm/_logs/2021-01-25T17_34_48_272Z-debug.log say?

**Comment by Graham1384** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'electron',
1 verbose cli   '-g' ]
2 info using npm@6.14.11
3 info using node@v10.19.0
4 verbose npm-session aef0f8613fd26519
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/electron 874ms (from cache)
8 silly pacote tag manifest for electron@latest fetched in 898ms
9 timing stage:loadCurrentTree Completed in 924ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 2ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule electron@11.2.1 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/@electron%2fget 336ms (from cache)
<17_34_48_272Z-debug.log" [readonly] 2776L, 179750C           1,1           Top

here is the full log file

**Comment by Graham1384** [comment]
excuse me 

the log file length is about 3000 lines. that was not the full log file

2637 timing stage:rollbackFailedOptional Completed in 377ms
2638 timing stage:runTopLevelLifecycles Completed in 19092ms
2639 verbose stack Error: electron@11.2.1 postinstall: `node install.js`
2639 verbose stack Exit status 1
2639 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
2639 verbose stack     at EventEmitter.emit (events.js:198:13)
2639 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
2639 verbose stack     at ChildProcess.emit (events.js:198:13)
2639 verbose stack     at maybeClose (internal/child_process.js:982:16)
2639 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
2640 verbose pkgid electron@11.2.1
2641 verbose cwd /home/parham
2642 verbose Linux 5.8.0-40-generic
2643 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "install" "electron" "-g"
2644 verbose node v10.19.0
2645 verbose npm  v6.14.11
2646 error code ELIFECYCLE
2647 error errno 1
2648 error electron@11.2.1 postinstall: `node install.js`
2648 error Exit status 1
2649 error Failed at the electron@11.2.1 postinstall script.
2649 error This is probably not a problem with npm. There is likely additional logging output above.
2650 verbose exit [ 1, true ]
 

this are the ending line

**Comment by Graham1384** [comment]
will using VPN cause any errors?
I live in Iran and I always connect to a VPN because everything is blocked here

**Comment by ckerr** [comment]
This doesn't appear to be an issue with Electron itself, but with the npm install.

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try. My guess is that you can find an answer there.

I hope this helps!
