### ISSUE TITLE
No way to set extra options for a webview compared to a BrowserWindow

### ISSUE THREAD

**Issue by sedwards2009** [electron/electron#2749]
The constructor for a BrowserWindow has the option to turn on things like 'experimental-features' etc. The webview tag is missing most of these options. It would be nice if webview offered the same options as a normal browser window.

I would specifically like to turn 'experimental-features' on for a webview to get CSS grid support.

**Comment by zcbenz** [comment]
We need to map every property of `web-preferences` of `BrowserWindow` to `<webview>`'s attributes.

**Comment by Kilian** [comment]
I would also like more options for the webview, specifically the web-preferences.

**Comment by romaincointepas** [comment]
+1, interested as well.

**Comment by RangerRick** [comment]
Adding a +1 for this as well.

I'm running into the need for this in [electron-mattermost](https://github.com/yuya-oc/electron-mattermost), which is a wrapper app for a remote site and fails to do things like [load HTTP images](https://github.com/yuya-oc/electron-mattermost/issues/35) when the remote server is HTTPS.  Setting `disablewebsecurity` is a pretty big hole just to allow (presumably &lt;g&gt;) safe resources.

**Comment by zcbenz** [comment]
As mentioned in #6484, we can probably add 2 events to WebContents: `webview-created` and `will-create-webview`. The `will-create-webview` event can be used to strip out the `preload` option, and `webview-created` event can be used to add a listener to the `will-navigate` event of webview's `WebContents` to decide whether to navigate to a page.

**Comment by enlight** [comment]
I think `did-create-webview` would be a better event name than `webview-created`.

**Comment by chandrachivukula** [comment]
Hey folks (@zcbenz @felixrieseberg et al) - its not clear if the events based control of webview creation still continues to require that the parent BrowserWindow have nodeintegration enabled.

1. There are many requests/issues asking for enabling webview when parent BrowserWindow nodeintegration is turned off. Is there an architectural/design issue with enabling webview when parent BrowserWindow has disabled nodeintegration?

2. Many apps built on Electron render third party content, and/or user generated content. The proposed alternative (for my issue #6157) is enabling nodeintegration on the BrowserWindow and disabling node symbols in BW preload -  is there some discussion/doc on how secure this approach is? would enabling nodeintegration on BW and just removing the node symbols in preload make the BW process behavior identical to when BW has nodeintegration turned off?

Thanks much in advance folks.

**Comment by laramies** [comment]
Hi all, seconding Chandra, I would like to see 1) where we can enable webviews while BW has nodeintegration off.  I think there is many people requiring the same, and everyone is doing workarounds in order to have this.   Why is not possible to reenable Webviews while nodeintegration is off?  If it is because  the Preload danger, that can be overcome with protocol filters (not letting people load JS files from the network for example), or the proposed will-create-webview and striping the Preload.

Thanks,
Chris

**Comment by chandrachivukula** [comment]
@zcbenz @jlord @felixrieseberg hey folks - any update on this work to add the webview creation events (will-create-webview & did-create-webview)?
