### ISSUE TITLE
Not able to access contents of an IFRAME in OOPIFs

### ISSUE THREAD

**Issue by wayvad** [electron/electron#27503]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
Electron version: 10.2
OS: Windows
Last known working Electron version: 8.2

### Expected Behavior
Be able to use DevTools or webdriver to view / automate contents in an out-of-process iframe.

### Actual Behavior
Starting with Electron 9, no longer to use DevTools to inspect elements inside OOPIF. Please see this Fiddle for repro: https://gist.github.com/81a58bffae7d48d2f1a4c4cb7300c86c

More info from Deepak:
      Definitely a bug in electron not seeing the same issue with chrome, used a local http server to load the above html file in chrome and electron, chrome displays the contents for the OOPIF. 

  I just started to narrow down the version this first regressed, it is somewhere between 9.0.0-beta.9 and 9.0.0-beta.12

### To Reproduce
Please use this Fiddle: https://gist.github.com/81a58bffae7d48d2f1a4c4cb7300c86c

### Screenshots

![image](https://user-images.githubusercontent.com/40037392/105921292-85b43600-5fed-11eb-919c-66006c447749.png)

### Additional Information

I contacted Milan Burda and Deepak Mohan to confirm that this is indeed an Electron bug.

**Comment by ckerr** [comment]
@wayvad can you walk me through this? I think I might be looking at the wrong behavior in your test if you're seeing the breakage somewhere in [9.0.0-beta.9..9.0.0-beta.12].

When I test in the latest 8 version (8.5.5) I am able to click the inspector's "Select an element in the page to inspect it" button, then mouseover the items inside iframe, and the elements are highlighted and inspected. When I try this in 9.0.0-beta.1, I no longer see those items highlighted and the element tree stops at `<iframe></iframe>`. Which sounds like what you're describing, but appears to have been introduced sometime before `9.0.0-beta.1`.

So if I'm looking at the wrong thing, help me out so I can look at the right behavior.

Or if this is the right thing, can you double-check your versions to confirm the beta 9 & 12 numbers?

**Comment by ckerr** [comment]
Screenshots of https://gist.github.com/81a58bffae7d48d2f1a4c4cb7300c86c tested in [fiddle](https://github.com/electron/fiddle) w/8.5.5 and 9.0.0-beta.1

![27503-test-v8 5 5](https://user-images.githubusercontent.com/70381/105926988-a938aa00-6008-11eb-81a6-7f148323054f.png)

![27503-test-v9 0 0-beta 1](https://user-images.githubusercontent.com/70381/105926997-accc3100-6008-11eb-99e6-2d7489476d8b.png)

**Comment by ckerr** [comment]
Oh, re-reading the description I realize that Way may have been quoting @deepak1556 on that, so mentioning him by name for the same question :slightly_smiling_face:

**Comment by wayvad** [comment]
@ckerr, the behavior that you saw matches mine. I was strictly testing this between version 8.5.5 and 10.2 (and did not personally test anything in between) -- apologies if I got it wrong.

The bottom line is in version 10, I cannot inspect elements inside the iframe.

**Comment by ckerr** [comment]
v9.0.0-nightly.20191121: works

v9.0.0-nightly.20200121: broken

**Comment by ckerr** [comment]
Electron v9.0.0-nightly.20200117: works

Electron v9.0.0-nightly.20200119: broken

**Comment by ckerr** [comment]
`$ git log --pretty=oneline v9.0.0-nightly.20200117..v9.0.0-nightly.20200119`
64a2490efe38493e46dc1bbae0567f699837d4fc (tag: v9.0.0-nightly.20200119) Bump v9.0.0-nightly.20200119
48b9c7df84885b45c0db29c7cbd89dcb61201f6b (tag: v9.0.0-nightly.20200118) Bump v9.0.0-nightly.20200118
9636acb90721b6a4970a3a334ceb9e9886a63d6c docs: update setAspectRatio documentation (#19945)
42d8933d66b18e08b54b87554146fec80ef2f063 fix: crash when restoring minimized hidden window (#21813)
bf6e4b1247f3a48e8926080b1852ec5d739f0888 chore: bump chromium to 279aeeec3c9fe2237bc31f776f269 (master) (#21521)
5c6f9a6947cafe34ac03b9225d096b72a7a4ce79 feat: add mouse-down & mouse-up to Tray (#21795)

Looks like it might be that Chromium roll.

**Comment by deepak1556** [comment]
@ckerr sorry I should have been clear in my original message about what I had tested, the broken behavior between 9.0.0-beta.9 and 9.0.0-beta.12 is for regular oopif embedded in a page and not for iframe embedded inside webview as in above test case which is also definitely broken but earlier. Can you confirm the following

Load the page over an origin thats not `www.bing.com` , `file` scheme or `http://localhost`

```
<!DOCTYPE html>
<html>
  <body>
    IFRAME <b>not</b> hosted in Webview:<br>
    <iframe id="myiframe" src="https://www.bing.com/images" sandbox="allow-forms allow-scripts allow-same-origin allow-downloads" />'></iframe>

  </body>
</html>
```
