### ISSUE TITLE
 How to enable SOP?

### ISSUE THREAD

**Issue by Zhxhh** [electron/electron#27529]
According to the official doc, "websecurity:true" is the default setting.

However, in my app, the SOP seems like not working.

"electron": "^11.2.1"

macos:10.15.5

I downloaded the example "electron-quick-start".

I create the browserWindow :

```
mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
    }
  })
```
In my electron app, cross-domain request works and shows that doesn't violate SOP image
![image](https://user-images.githubusercontent.com/32181911/106081560-1016aa00-6154-11eb-905c-38bf7742f668.png)

However, in chrome, cross-domain request doesn't works. image 
![image](https://user-images.githubusercontent.com/32181911/106081586-19a01200-6154-11eb-9796-fe1dd7c23367.png)

So, what did "websecurity:true" do? how can I use SOP to protect my app?

**Comment by ckerr** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
