### ISSUE TITLE
[Feature Request]: libayatana-appindicator1 as a replacement/alternative to libappindicator1

### ISSUE THREAD

**Issue by vali-um** [electron/electron#27527]
**Preflight Checklist**

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Problem Description**

The package libappindicator1 is not available in the upcoming debian release (bullseye) anymore [1]. also other debian based distributions will maybe switch.
as far as i can tell this is the library to handle tray icons in linux that is suported right now now and is also set as a default deb dependency by electron builder[2].
This leads to a situation in which an electron app with the default dependencies from electron builder can not be installed on debian bullseye. with the dependency removed it can be installed but the tray icon might not work without changes.

**Proposed Solution**

Use libayatona-appindicator1 as an alternative for libappindicator1 either by default or optional.
See https://ayatanaindicators.github.io/about/ for more information.

**Alternatives Considered**

Making libappindicator1 an optional dependency by default. this would enable installation on debian bullseye but may still leave the installations without a working system tray icon.

**Additional Information**

references:
[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895037
[2] https://www.electron.build/configuration/linux#debian-package-options

**Comment by vali-um** [comment]
a sample electron application with this issue is signal-desktop, see https://github.com/signalapp/Signal-Desktop/issues/4761

**Comment by ckerr** [comment]
Agreed, this would be a Good Thing.

**Comment by mimi89999** [comment]
I think that the correct place to report this is https://github.com/develar/app-builder/issues/51

**Comment by hilga007** [comment]
Just ran into this issue on Debian testing (12). Without investigating, I figured it had to be something broken in Testing. 

Reformat and re-installed with Debian Stable (11)

Issue persists in Debian bullseye. 
amd64 architecture. 

Can some sort of (if / then) statement be included so that a .deb file can contain versions for pre-bullseye and post-bullseye? 

[Looks like snarky has a decent start](https://github.com/o1-labs/snarky/blob/master/scripts/depends.sh)
