### ISSUE TITLE
Print multiple printer at the same time

### ISSUE THREAD

**Issue by yuniit** [electron/electron#27526]
Hello, How can I manage to print multiple printer at the same time.
I've try some like this:

```js
webview.addEventListener('ipc-message',  (event) => {
   if (event.channel == "startPrint") {
        let printers = ['Printer80','Epson TM-T88VI']

        for (let printer of printers) {
           webview.print({
             copies: 1,
             silent: true,
             printBackground: true,
             deviceName: printer
          })
       }
    }
})
```
But 1 of the printers got to print.

**Development environmen:**
Node version: v14.9.0
NPM version: 6.14.8
Electron version: 10.1.3
Operating System: Ubuntu 18.04

**Comment by codebytere** [comment]
@yuniit `<webview>.print` returns a promise - you should handle it accordingly and it'll work properly.
