### ISSUE TITLE
no-drag app region ignores scrollable element occlusion

### ISSUE THREAD

**Issue by samuelmaddock** [electron/electron#27528]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 10.3.1
  * 11.2.0
  * 12.0.0-beta.18
* **Operating System:**
  * Windows 10 (2004)
* **Last Known Working Electron version:**
  * None

Using `-webkit-app-region: no-drag` within a scrollable element will cause the region to still affect dragging even while occluded outside of the scrollable area.

### Expected Behavior
'no-drag' region does not affect draggable regions when occluded by scroll area.

### Actual Behavior
'no-drag' region prevents dragging even while it's occluded in a scrollable region.

### To Reproduce

1. Load https://gist.github.com/12c196a2c70b29c8dca7d3a3e2ceb8b9
2. Confirm that dragging works on white border of the window.
3. Use mousewheel to scroll down in green region.
4. Attempt to scroll in the top of the frame in the white region.

### Screenshots

![2021-01-27_20-29-28](https://user-images.githubusercontent.com/1656324/106076841-5fba8e80-60de-11eb-8932-3fa0b3b7e717.gif)

**Comment by samuelmaddock** [comment]
I did some research into this issue. Draggable regions of the app come from what's called "annotated regions" in the Blink codebase. Certain events will trigger updating them which then get sent to Electron via a Mojo IPC message.
https://github.com/electron/electron/blob/6edf6c6a957e4f2c2d1f2bdd4ddb7d39ecacc37e/shell/common/api/api.mojom#L77-L78

The annotated regions in Blink don't seem to have a concept of z-index or scroll area occlusion. Each box model with `-webkit-app-region: drag/no-drag;` are simply collected in a vector using an in-order traversal of the DOM tree (see [LocalFrameView::CollectAnnotatedRegions](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/frame/local_frame_view.cc;l=4316-4328;drc=62ed285cc8715be55d14e614d38fdd61612a9f6b)).

The later the DOM node appears in the tree, the higher priority it will have in calculating whether a region is draggable or not. This can be abused as a workaround—place which DOM nodes you want to be draggable further in the tree.

A proper solution would be to patch [LayoutObject::AddAnnotatedRegions](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/layout/layout_object.cc;l=4051-4069;drc=62ed285cc8715be55d14e614d38fdd61612a9f6b) to occlude regions within any overflowed scroll areas.

**Comment by Linefate** [comment]
I had the same problem, and I solved it.

I found that it is because the DOM or sub elements of the green area have attributes:  

`- WebKit app region: no drag;`

When the green area scrolls, the drag of the head will fail

**Comment by nornagon** [comment]
@samuelmaddock this would seem to be an upstream bug then, yes?

**Comment by samuelmaddock** [comment]
> @samuelmaddock this would seem to be an upstream bug then, yes?

I think that's a fair assessment.
