### ISSUE TITLE
[Bug]: One webview paused by debugger prevents all webviews from receiving click events

### ISSUE THREAD

**Issue by Karine91** [electron/electron#27523]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 11.0.1
* **Operating System:** macOS 10.14.6

### Expected Behavior
Devtools should be interactive and the user can control debugging process

### Actual Behavior
Devtools not interactive and the user unable to click on any tabs or buttons. Only scroll works.

### To Reproduce
I created a repo to reproduce this behavior - https://github.com/Karine91/devtools-webview
To install:
```sh
$ git clone https://github.com/Karine91/devtools-webview.git
$ yarn
$ yarn start
```
After running the project go to the source of preload.js file
![image](https://user-images.githubusercontent.com/26932594/106044114-f9d30480-60e7-11eb-840a-17b9407b9751.png)
Add debugger breakpoint
![image](https://user-images.githubusercontent.com/26932594/106044238-1cfdb400-60e8-11eb-9ba1-82fdc45a4e22.png)

Reload the page by clicking on github logo
![image](https://user-images.githubusercontent.com/26932594/106045246-61d61a80-60e9-11eb-8f79-8215a88f9462.png)
After that debugger paused but you not able to click on any buttons in webview, but scroll works

**Comment by ckerr** [comment]
Hey @Karine91, I just clicked through to your testcase and it seems to have a lot of dependencies in it. Would it be possible for you to make a standalone testcase with only the code and dependencies necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

**Comment by Karine91** [comment]
@ckerr Thank you for answering. I created gist - https://gist.github.com/Karine91/fde47936591772adc77e4f1d3e999b8b

**Comment by Slapbox** [comment]
Sounds like the same issue as https://github.com/electron/electron/issues/20383 only affecting WebViews instead of BrowserViews.

**Comment by christlee1989** [comment]
I have same issue

**Comment by christlee1989** [comment]
When this problem happen, click the select button of the debugger in BrowserWindow, and then return to the embedded debugger, which will restore。

![image](https://user-images.githubusercontent.com/10151385/116366320-c1eb7280-a838-11eb-8cd1-43de7c50d2fe.png)

**Comment by Tyreal** [comment]
I have the same issue, it became not interactive when debugger stops on breakpoint.but when i reload the remote-debugging-port of the devtools webview in Chrome,it will be interactive.

**Comment by Tyreal** [comment]
changing the webview to browserview, it will be interactive when debugger stops on breakpoint,Maybe it is the problem with webview.

**Comment by Karine91** [comment]
the same happen with simple iframe

**Comment by Karine91** [comment]
one workaround I found - it's set checkbox in devtools settings for 'Disable paused state overlay'

**Comment by nornagon** [comment]
@Karine91 interesting that this also happens with an iframe—do you happen to have a gist example showing that behavior?

**Comment by clavin** [comment]
I've generalized this problem into a smaller repro: https://gist.github.com/clavin/236e0943ef72525a573bfb81d1739647

That gist shows two webviews, one on top of the other. The top one has its dev tools open automatically. When the `debugger` button is pressed in the top webview it should pause. From there, neither the top nor bottom webviews can be clicked on--even though the bottom one is still running and updating.

Further, other interactions like selecting text and keyboard events still make their way into the second webview, just not clicks. This means that the paused top webview cannot be resumed from the debug "paused" overlay on the webview, only from the devtools window.

**Comment by Shenfq** [comment]
When can it fixed？

**Comment by Shenfq** [comment]
bump

**Comment by praneetrohida** [comment]
bump

**Comment by zhaomenghuan** [comment]
bump

**Comment by bacy** [comment]
bump
