### ISSUE TITLE
The value of input.key is different, when listening before-input-event

### ISSUE THREAD

**Issue by updaterupdater** [electron/electron#27530]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.2.1
  * 11.2.1
* **Operating System:**
  * Windows 10 (1903)
* **Last Known Working Electron version:**
  

### Expected Behavior

On all Windows computers, when focusing on the input box, the value of input.key is ’Process‘.

### Actual Behavior
The value of input.key on some computers is Process, and the value of input.key on some computers is equal to the value of input.code

### To Reproduce

[https://gist.github.com/f15cad98e9e6aab6c0ff574aab1b68f8](https://gist.github.com/f15cad98e9e6aab6c0ff574aab1b68f8) 

I wrote a demo using electron fiddle. 

The value of input.key is process on a normal machine.

```javascript
win.webContents.on('before-input-event',(event,input)=>{
    colsole.log(input)
}
```

### Screenshots

![image](https://user-images.githubusercontent.com/74588403/106101455-e3c15480-6178-11eb-8cc8-9f9e187f27b8.png)
![image](https://user-images.githubusercontent.com/74588403/106101570-08b5c780-6179-11eb-813e-745f84f34fe7.png)

### Additional Information
This bug appeared on some Windows machines. So you may not see this bug on your machine. If it does not appear, please try a few more machines.

**Comment by ckerr** [comment]
Hi @updaterupdater, thanks for reaching out and reporting this issue.

I appreciate the gist, but I'm a little confused on what you're reporting and how to go about reproducing it. Could you walk through the exact steps you used to trigger this issue, and what happened each step along the way, with all the information needed so that a tester can try to reproduce it? 

Also, the message about "if it does not appear, please try a few more machines" is a bit concerning. Is there anything special about the configurations of the machines where this failed? Testing this on random machines doesn't seem like a deterministic plan.

**Comment by Mandymoore680** [comment]
![ACHIEVEMENTS_ICON](https://user-images.githubusercontent.com/78269241/106396812-6562ed80-63d8-11eb-8fbb-776ce9975f09.png)

**Comment by Mandymoore680** [comment]
Goog

**Comment by Mandymoore680** [comment]
![FRIENDS_ICON](https://user-images.githubusercontent.com/78269241/106396829-73187300-63d8-11eb-884b-1a0e2621e66e.png)

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
