### ISSUE TITLE
just remove icon of  maximizable or minimizable 

### ISSUE THREAD

**Issue by lixiaohulee** [electron/electron#27549]
how can i remove icon of maximizable or minimizable  from titleBar

**Comment by ckerr** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
