### ISSUE TITLE
electron v11.2.1 node version error ,72 not 85

### ISSUE THREAD

**Issue by hustzju** [electron/electron#27550]
electron v11.2.1 use  the node which's version is  v12.18.3
but the  NODE_MODULE_VERSION of node with  v12.18.3 is 72 ,and electron -a shows 85,
this sames like  a bug

**Comment by ckerr** [comment]
https://www.electronjs.org/docs/tutorial/using-native-node-modules#using-native-node-modules

**Comment by hustzju** [comment]
@ckerr thanks ,  I have got it
