### ISSUE TITLE
Packaged apps allow --require in NODE_OPTIONS on Windows

### ISSUE THREAD

**Issue by tosmolka** [electron/electron#27551]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.3.5
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior

According to https://www.electronjs.org/docs/api/environment-variables#node_options or https://github.com/electron/electron/issues/26101 or https://github.com/electron/electron/pull/22539/files it seems packaged electron apps (where executable is not named electron.exe) should not allow --require option in NODE_OPTIONS env variable. 

### Actual Behavior

It seems packaged apps such as latest version of Visual Studio Code permit using --require in NODE_OPTIONS and execute the provided script. 

### To Reproduce

Download latest VS Code and run following:
```cmd
echo console.log('Hello world!');process.exit(0); > c:\temp\test.js
set NODE_OPTIONS="--require=c:/temp/test.js"
code.exe
```
VS code will print Hello world! and exit. 

### Screenshots

![image](https://user-images.githubusercontent.com/37370256/106260530-c9db4c80-6220-11eb-9a96-eed21567f3d0.png)
![image](https://user-images.githubusercontent.com/37370256/106260585-d95a9580-6220-11eb-9428-ab0885d1940b.png)

### Additional Information

Issue is reproducible also with v11.2.1 downloaded from npmjs.com.

**Comment by tosmolka** [comment]
After initial investigation it seems that Electron is setting updated NODE_OPTIONS using `SetEnvironmentVariable` and Node is retrieving them via `getenv`. 

Value returned from `getenv` is the original one and filtering that was done in Electron seems to be completely ignored. I wonder whether this feature ever worked or not and if yes what change caused this issue.

**Comment by miniak** [comment]
This issue does not reproduce anymore on Electron 12+, which has node 14 including this fix
https://github.com/nodejs/node/commit/a16f0f427eb7bc8c31d8f93fd37bc42cdcf594f8
