### ISSUE TITLE
Some sites began to crash with out of memory error

### ISSUE THREAD

**Issue by dafivius** [electron/electron#27559]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * ^10.3.1
* **Operating System:**
  * macOS(11.0.1) 
* **Last Known Working Electron version:**
  * 10.3.1

### Expected Behavior
Opened via webContents.loadUrl [site](https://bet365.com) is working correct.

### Actual Behavior
Systems hangs up with error stack trace
`[84368:0x1800000000]    98325 ms: Mark-sweep 1993.2 (2068.4) -> 1993.1 (2068.4) MB, 6444.1 / 0.0 ms  (average mu = 0.348, current mu = 0.074) allocation failure scavenge might not succeed
[84368:0x1800000000]   106419 ms: Mark-sweep 2000.8 (2068.4) -> 2000.8 (2084.4) MB, 7744.9 / 0.0 ms  (average mu = 0.200, current mu = 0.043) allocation failure scavenge might not succeed
`

### To Reproduce
Simple load site with browserWindow.webContents.loadUrl. Increasing memory doesn't have effect.

Was trying to update electron to latest, was trying beta and nightly releases - no effect. Just hanging with white screen.

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
