### ISSUE TITLE
[Feature Request]: Explain the rule of requestSingleInstanceLock more clearly

### ISSUE THREAD

**Issue by LongTengDao** [electron/electron#27556]
**Preflight Checklist**

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Problem Description**

I want to figure out how the API distinguishes two different programs, the path of `electron.exe` or `main.js` or `Electron` (the name of `electron.exe`)?

I did not search for relevant information in the source code. Isn't it an implementation written in JS (it's C++)?

**Proposed Solution**

Hope it is clearly stated in the document.

For example,
- the case of booted by multiple system users;
- the case of being packaged into a standalone `exe` vs not being packaged and started by a shared `electron.exe`.

**Alternatives Considered**

Noop.

**Additional Information**

_No response_

**Comment by ckerr** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by LongTengDao** [comment]
> αιτορ.asar
> if the program is started with electron \<script file\>, the process is electron.exe
> if the program is packaged, then the executable name is up to you. Portable is also considered 'packaged'

> erick
> It seems like there's a process_singleton_ variable being tracked here https://github.com/electron/electron/blob/d6019634f9ac1d30a8beb55390a45a94881df60c/shell/browser/api/electron_api_app.h#L241
> The implementation for the logic is inside the Chromium source code https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/process_singleton.h

**Comment by LongTengDao** [comment]
by my test:

on Windows:

It only depends on the productName or name field in pakage.json (default is Electron; case-insensitive).

I'm not sure if it is same on Linux or MaxOS.
