### ISSUE TITLE
Run node-gyp from Electron Main process

### ISSUE THREAD

**Issue by hrueger** [electron/electron#27553]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.2.1
* **Operating System:**
  * Windows 10 20H2
* **Last Known Working Electron version:**
  * none

### Actual Behavior
I am using npm's arborist module to install npm packages into a folder at runtime. Those packages are then required and used. When I install a package which requires native addon modules to be rebuilt using `node-gyp`, I encounter the following error:
```
Unhandled Rejection at: Promise Promise {
  <rejected> Error: command failed
      at ChildProcess.<anonymous> (C:\Users\Hannes\AppData\Local\Programs\glue\resources\app.asar\node_modules\@npmcli\promise-spawn\index.js:64:27)
      at ChildProcess.emit (events.js:315:20)
      at maybeClose (internal/child_process.js:1021:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
    cmd: 'C:\\WINDOWS\\system32\\cmd.exe',
    args: [
      '/d',
      '/s',
      '/c',
      'prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild'
    ],
    code: 1,
    signal: null,
    stdout: '',
    stderr: 'Der Befehl "node-gyp" ist entweder falsch geschrieben oder\r\n' +
      'konnte nicht gefunden werden.\r\n',
    event: 'install',
    script: 'prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild',
    pkgid: '@serialport/bindings@8.0.8',
    path: 'C:\\Users\\Hannes\\AppData\\Roaming\\glue\\data\\features\\node_modules\\@serialport\\bindings'
  }
} reason: Error: command failed
    at ChildProcess.<anonymous> (C:\Users\Hannes\AppData\Local\Programs\glue\resources\app.asar\node_modules\@npmcli\promise-spawn\index.js:64:27)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  cmd: 'C:\\WINDOWS\\system32\\cmd.exe',
  args: [
    '/d',
    '/s',
    '/c',
    'prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild'
  ],
  code: 1,
  signal: null,
  stdout: '',
  stderr: 'Der Befehl "node-gyp" ist entweder falsch geschrieben oder\r\n' +
    'konnte nicht gefunden werden.\r\n',
  event: 'install',
  script: 'prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild',
  pkgid: '@serialport/bindings@8.0.8',
  path: 'C:\\Users\\Hannes\\AppData\\Roaming\\glue\\data\\features\\node_modules\\@serialport\\bindings'
}
```
The german (sorry for that, but my windows is set to German) translates to `The command "node-gyp" is either misspelled or could not be found`. 
All of this happens in the Main process. 

How can I fix this? Is this even possible?
I think I need to ship node-gyp with Electron somehow as the end user won't have Node installed. 

### Expected Behavior
It finds node-gyp and rebuilds. 

### To Reproduce
If you need a test case repo, please tell me.

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
