### ISSUE TITLE
_nit_ s/Noitfy/Notify/ for these two methods

### ISSUE THREAD

**Issue by gitiafsaneh** [electron/electron#27569]
_nit_ s/Noitfy/Notify/ for these two methods

_Originally posted by @ckerr in https://github.com/electron/electron/pull/27489#discussion_r564665321_

**Comment by ckerr** [comment]
Hi @gitiafsaneh, this got fixed before the PR was merged: https://github.com/electron/electron/blob/master/shell/browser/native_window_mac.h#L145
