### ISSUE TITLE
[Feature Request]: Singleton (object) sharing across processes (main, renderer(s))

### ISSUE THREAD

**Issue by ShlomiRex** [electron/electron#27567]
**Preflight Checklist**

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Problem Description**

First of all is it possible to share a true singleton class (written in typescript) across main and renderer processes?

**Proposed Solution**

If not, is it possible to impliment? 

**Alternatives Considered**

If not, how can one overcome this challenge and impliment a system that enables 1 single instance of a class and renderers and main have access to it?

**Additional Information**

_No response_

**Comment by ckerr** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by ShlomiRex** [comment]
> Thanks for reaching out!
> 
> The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.
> 
> I hope this helps!

Thanks! I will update if I find a solution.
