### ISSUE TITLE
process loop when loading https://www.bet365.it

### ISSUE THREAD

**Issue by btzsoft** [electron/electron#27577]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.2.1
* **Operating System:**
  * windows 10
* **Last Known Working Electron version:**
  * 10

### To Reproduce
```js
win.loadURL('https://www.bet365.it')
```

### Additional Information
loading this website will make the the process to go in a loop, high CPU and the page is white.

**Comment by ckerr** [comment]
@btzsoft just to confirm we're talking the same thing, can you confirm for me that this is just creating a browser window & loading that URL, e.g something like this from [electron-quick-start](https://github.com/electron/electron-quick-start):

## main.js

```js
// Modules to control application life and create native browser window
const {app, BrowserWindow} = require('electron')

function createWindow () {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true
    }
  })

  mainWindow.loadURL('https://www.bet365.it')

  // Open the DevTools.
  // mainWindow.webContents.openDevTools()
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(createWindow)

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', function () {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow()
  }
})

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.
```

**Comment by btzsoft** [comment]
@ckerr yes, I cloned last version of `electron-quick-start`  and called `.loadURL('https://www.bet365.it')`

**Comment by ckerr** [comment]
I see the same white screen when testing with Electron 10 so I don't think this is a new regression, but I am definitely seeing the described behavior in 11 as reported.

Tested with 11.2.1, 11.0.0, and 10.0.0.

**Comment by btzsoft** [comment]
I did the same test in `puppeteer` and the same issue, also used `firefox` in `puppeteer` and the same, but in `firefox` when I do reload it works. On all browsers we have high CPU load.

**Comment by nornagon** [comment]
This is an issue with the JavaScript on the site, and not an Electron bug.

I was able to attach a debugger while the site was running, and the JS is caught in this loop:

```js
while (!![]) {
  try {
    if (j[au('0x228')](j[au('0x287')], j[au('0x287')])) {
      function a4() {
        var aC = function(c, d) {
          return au(c - '0x30f', d);
        };
        j[aC('0x4f0')](Z, 0x3, !![]);
      }
    } else
      !!a1 && !(!!window[au('0x289')] && !!document[au('0x18f')]) && (a1 += j[au('0x272')]);
  } catch (a5) {}
}
```

This is obfuscated, here's my rough deobfuscation based on live evaluation, which I believe is functionally identical to the above in this particular situation:

```js
while (true) {
  try {
    if (false) {
      // ...
    } else {
      if (a1 && !(window.MSInputMethodContext && document.documentMode)) {
        a1 += "MP=";
      }
    }
  } catch (a5) {}
}
```

`(window.MSInputMethodContext && document.documentMode)` is essentially a check for Internet Explorer, which fails, so this loop is basically:

```js
while (true) {
  a1 += "MP=";
}
```

and it is unsurprising that the app hangs.

I'm closing this as I don't believe this is an Electron bug, but rather a logic error in the website under test.
