### ISSUE TITLE
Crash occurs when entering a date directly in <input type='date'/>

### ISSUE THREAD

**Issue by fly1397** [electron/electron#27573]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 1.6.x - 9.4.1
* **Operating System:**
  * Windows 10 
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior

* user can enter a date directly in the input (type = date)
### Actual Behavior

* the application crashed

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
I'm unable to reproduce this by adding `<input type='date'/>` to the default fiddle on Windows with 9.4.1 and clicking the dropdown to change the date

**Comment by fly1397** [comment]
> I'm unable to reproduce this by adding `<input type='date'/>` to the default fiddle on Windows with 9.4.1 and clicking the dropdown to change the date

yes, click the dropdown to change the date, it's works fine.
you can try enter the date with keyborad.

**Comment by codebytere** [comment]
@fly1397 please address https://github.com/electron/electron/issues/27573

**Comment by fly1397** [comment]
i add listener for the input box when change the date, maybe the bounce cause the crash. 
when remove the listener, it works fine.
