### ISSUE TITLE
loadUrl error "ERR_ABORTED (-3) error" can't be catched

### ISSUE THREAD

**Issue by benoittgt** [electron/electron#27574]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v10.1.1
* **Operating System:**
  * v10.15.7

### Expected Behavior

`Uncaught (in promise) Error: ERR_ABORTED (-3)` raised by https://github.com/electron/electron/blob/c41b8d536b2d886abbe739374c0a46f99242a894/lib/browser/navigation-controller.ts#L77-L86 can be catched by `win.webContents.on('did-fail-load', () => {})`

### Actual Behavior

Error thrown by https://github.com/electron/electron/blob/c41b8d536b2d886abbe739374c0a46f99242a894/lib/browser/navigation-controller.ts#L77-L86 cannot be catched in context of a redirect.

```js
  const { remote } = require('electron');
  const win = new remote.BrowserWindow({
    width: 800,
    height: 600,
    show: false,
    webPreferences: {
      partition: LOGIN_PARTITION,
      nodeIntegration: false,
    },
  });
  win.webContents.on('did-finish-load', () => {
    console.log('finish-load'); // triggered twice
  });
  win.webContents.on('did-fail-load', () => {
    console.log('fail-load'); // never triggered
  });
  try {
    win.loadURL(urlThatContainsAutoRedirect);
  } catch (error) {
    console.log('catch loadUrl'); // never triggered
  }
  win.show();
```

<img width="541" alt="Screenshot 2021-02-01 at 18 06 01" src="https://user-images.githubusercontent.com/8417720/106492611-68cda600-64b8-11eb-8f39-828a86dd4542.png">

### Reproduce

Sadly the flow I use is based on Auth0 login page, that automatically redirect to a page behind authentication if we have the same partition. I cannot provide a way to reproduce.

### Related:
  - https://github.com/electron/electron/issues/17526

**Comment by benoittgt** [comment]
Error can be catched. Do not forget `loadUrl` return a promise.

```js
  win.loadURL(url).catch((error: any) => {
    if (error.code === 'ERR_ABORTED') return;
    throw error;
  });
```

**Comment by OldManMeta** [comment]
I'm getting this error - am calling loadURL exactly how @benoittgt is showing in the last comment.

**Comment by OldManMeta** [comment]
Correction - I just spotted where I was not handling this in another loadURL

**Comment by Lordfirespeed** [comment]
I'm getting this error using `try ... catch` syntax in an async function. I can't get it to go away even using `.catch()`
