### ISSUE TITLE
ffmpeg.dll and LGPL

### ISSUE THREAD

**Issue by OmarJay1** [electron/electron#27578]
Hello, sorry for this rather arcane question.  I built a Windows version of my electron app and noticed that ffmpeg.dll is a dependency.  Does that make any apps I distribute subject to the LGPL license?  I know this is an arcane legal question, but I was wondering if anybody knew the answer off the top of their head. 

There seem to be plenty of Electron apps that don't seem to implement the "object code" distribution requirements of LGPL, so maybe I'm just being weird and/or not understanding LGPL.

Thanks.

**Comment by nornagon** [comment]
Consult your lawyer. We cannot give legal advice on a GitHub issue.

**Comment by ckerr** [comment]
Previous discussion on this topic: https://github.com/electron/electron/issues/3449
