### ISSUE TITLE
WTF::PartitionsOutOfMemoryUsing512M

### ISSUE THREAD

**Issue by zhaoxiaolei519109457** [electron/electron#27586]
### Issue Details
The current process has canvas and video. But I'm not sure which side is the problem
* **Electron Version:**
  * electron 5.0.8

[9b066fbf-e9f2-43ca-b31b-b8b7b48c0e46.zip](https://github.com/electron/electron/files/5909833/9b066fbf-e9f2-43ca-b31b-b8b7b48c0e46.zip)

* Windows 10.0.18363

### Screenshots

![image](https://user-images.githubusercontent.com/43021784/106575004-8b25f900-6576-11eb-9a71-abcf1e311454.png)

Provide the corresponding dump

**Comment by ckerr** [comment]
Thank you for reaching out!

Electron 5 reached [end-of-life](https://www.electronjs.org/blog/electron-8-0#end-of-support-for-5xy) in February 2020 and is [no longer supported](https://www.electronjs.org/docs/tutorial/support#supported-versions), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/docs/tutorial/support#currently-supported-versions) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.
