### ISSUE TITLE
WebContents background color is not set early enough in some cases.

### ISSUE THREAD

**Issue by marekharanczyk** [electron/electron#27592]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 13.0.0-nightly.20210129
* **Operating System:**
  * any
* **Last Known Working Electron version:**
  * 

### Expected Behavior
Child window content background color set early before page loads.

### Actual Behavior
Child window is white, then switch to background color, then page background color.

### To Reproduce

https://gist.github.com/6710c5cd8ed5810fb5c796854d726c3a
Just click "Open child" button and look at what is displayed.

**Comment by ckerr** [comment]
Confirmed: when I press the `Open child` button in the gist, a new white window pops up, _then_ changes to the background color specified in the BrowserWindow constructor options object's `backgroundColor` property, _then_ the URL is loaded.

Tested with 9.0.0, 11.0.0, and 12.0.0-beta.20 on Ubuntu 20.10

**Comment by vadim-termius** [comment]
I think the related changes added a blink of white color for `app.allowRendererProcessReuse = false`.

If you add the `app.allowRendererProcessReuse = false` line here: https://gist.github.com/marekharanczyk/6710c5cd8ed5810fb5c796854d726c3a#file-main-js-L3, the parent window will blink with white color.

This is reproducible in electron 11.4.x, but not in electron 11.3.0.

I know, that `allowRendererProcessReuse` was removed recently in the upstream, but this is still important for previous electron versions that support `allowRendererProcessReuse`.

cc @codebytere
