### ISSUE TITLE
Autoupdater event "update-not-available" is never called on Windows

### ISSUE THREAD

**Issue by mahnunchik** [electron/electron#27604]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

Autoupdater event "update-not-available" is never called on Windows.

* **Electron Version:**
  *  v8.5.5
  * v9.4.2
* **Operating System:**
  *  Windows 10
* **Last Known Working Electron version:**
  *  -

### Expected Behavior

One of `update-available` or `update-not-available` are called after `checking-for-update` event.

### Actual Behavior

No from both events `update-available` or `update-not-available` are emitted.

### To Reproduce

```
    autoUpdater.on('checking-for-update', () => {
      log.log('checking-for-update');
    });

    autoUpdater.on('update-available', () => {
      log.log('update-available; downloading...');
    });

    autoUpdater.on('update-not-available', () => {
      log.log('update-not-available');
    });
```

**Comment by ckerr** [comment]
Hi @mahnunchik, thank you for reaching out!

Electron 8.5.5 has reached end-of-life and is [no longer supported](https://www.electronjs.org/blog/electron-11-0#end-of-support-for-8xy), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/docs/tutorial/support#currently-supported-versions) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.

**Comment by mahnunchik** [comment]
Hi @ckerr electron 9.4.2 has the same issue

**Comment by MarshallOfSound** [comment]
Those events are only emitted if your server and updates are configured correctly.  Please also add listeners for the `error` event and log any uncaught exceptions in your app.  I just tested manually and those events are definitely emitted, or the `error` event is emitted explaining what went wrong.

If you can provide a minimal sample (potentially as a [fiddle](http://electronjs.org/fiddle)) that reproduces what you are seeing someone might be able to look at this and revisit it.

**Comment by mahnunchik** [comment]
I find the root of the issue, `update-available` or `update-not-available` not fired if `autoUpdater.setFeedURL(feedURL)` called **before** app `ready` event.

**Comment by TakumiPT** [comment]
Why does 204 give an error instead of update-not-available?

**Comment by kbib0002** [comment]
A checklist to ensure that events emitted by the stock **Electon** _autoUpdater_ module are always captured in the main process and by a _BrowserWindow_ instance:

1. Event listeners (obviously) must be attached before any _autoUpdater_ method is called, such as `setFeedURL` or `checkForUpdates`.
2. Event listeners must be attached after the `ready` event is emitted by the **Electron** _app_ instance.
3. Event listeners must be attached after the `did-finish-load` event is emitted by the _BrowserWindow_ instance.
