### ISSUE TITLE
Calling printToPDF with cross origin iframe blocks all calls to printToPDF

### ISSUE THREAD

**Issue by t57ser** [electron/electron#27605]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.2.2
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * Unknown

### Expected Behavior
printToPDF should finish

### Actual Behavior
Calling printToPDF in a window that contains a cross origin iframe will never resolve.
**Additionally all other calls to printToPDF never resolve as well, even for other windows and other partitions**

### To Reproduce
```
const electron = require("electron");
function init() {
	let browserWindow3 = new electron.BrowserWindow({
		show: true,
		x: 500,
		y: 100,
		width: 900,
		height: 900,
		webPreferences: {
			partition: "persist:test1"
		}
	});
	let browserWindow2 = new electron.BrowserWindow({
		show: true,
		x: 500,
		y: 100,
		width: 900,
		height: 900,
		webPreferences: {
			partition: "persist:test2"
		}
	});
	browserWindow2.webContents.loadURL("http://www.google.com")
	browserWindow3.webContents.loadURL("http://localhost:9000/index.html").then(() => {
		setTimeout(() => {
			console.log("calling print to pdf");

			// Comment out this one to make the other one work
			browserWindow3.webContents.printToPDF({
			}).then(() => {
				console.log("done 1");
			})

			setTimeout(() => {
				browserWindow2.webContents.printToPDF({
				}).then(() => {
					console.log("done 2");
				})
			}, 2000);
		}, 2000);
	});
}
electron.app.on("ready", () => {
	init();
});
```
**index.html**
```
<!DOCTYPE html>
<html>
<body>
    <iframe src="http://www.orf.at"/>
</body>
<script>
</script>
</html>
```

**Comment by ckerr** [comment]
gist form of above snippets: https://gist.github.com/ckerr/ee185d9555ecebdde611eb347eb7d212

**Comment by mikkorantalainen** [comment]
Is anybody working on this issue?
