### ISSUE TITLE
Can't trigger the mousemove event when use `setIgnoreMouseEvents(true, { forward: true })` on a specific scene

### ISSUE THREAD

**Issue by zquancai** [electron/electron#27600]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  8.2.0
* **Operating System:**
  *  MacOS 10.15.7
* **Last Known Working Electron version:**
  *  8.2.0

### Expected Behavior

support `window.addEventListener('mousemove', onMouseMove);` event

### Actual Behavior

can not trigger the mousemove event.

### To Reproduce

https://gist.github.com/zquancai/c2fd37ed7b5c065b853fe28a3c6db590

Steps:

1. Open above one in Electron Electron Fiddle
2. Click Run
3. Move your mouse to `Clickable Area`
4. You will see the background color is changed to green
5. Click the `open` button
6. Focus on the new window you open on 5 step
7. Move your mouse to `Clickable Area` again
8. the background color hasn't changed.

### Screenshots

https://www.loom.com/share/cb2402545ff14ff19c5fd50841c01941

**Comment by zquancai** [comment]
seems the newest beta version(12.0.0-beta.20) also the same issue.

**Comment by VerteDinde** [comment]
Hey @zquancai, thanks for reporting this issue! Could you provide us with a bit more information about the behavior you're expecting to see here? It looks like your original window isn't registering mouse move/mouse events when the secondary window is focused - I'm assuming you want the window to register those events even if the overlay window is not focused?

When I pull your Fiddle and try to reproduce the issue in your screen capture, I'm unfortunately getting multiple console errors - if you want to link the `electron-mouse-forward-example` repo in your Loom video or adjust the Fiddle, I can take a closer look.

**Comment by zquancai** [comment]
> Hey @zquancai, thanks for reporting this issue! Could you provide us with a bit more information about the behavior you're expecting to see here? It looks like your original window isn't registering mouse move/mouse events when the secondary window is focused - I'm assuming you want the window to register those events even if the overlay window is not focused?
> 
> When I pull your Fiddle and try to reproduce the issue in your screen capture, I'm unfortunately getting multiple console errors - if you want to link the `electron-mouse-forward-example` repo in your Loom video or adjust the Fiddle, I can take a closer look.

Hi, @VerteDinde , thanks for your reply! 

my expected behavior:  
This event should be triggered regardless of whether the window is focused.

In addition, I found a strange behavior, when the mouse is moving from outside to the inside window, it can trigger this event always whether the window is focused. So I think this event should not be affected by focus. Seems the dev tools affect the behavior.

Have you loaded this code on Electron Fiddle: https://gist.github.com/zquancai/c2fd37ed7b5c065b853fe28a3c6db590 ?  Seems it is ok for my side. If you can not, I can provide a repo for you.

**Comment by Deuscx** [comment]
Any follow ups? Have the same problem, cant find a proper solution
