### ISSUE TITLE
crashReporter doesn't create dump files

### ISSUE THREAD

**Issue by vladimiry** [electron/electron#27602]
* **Electron Version:** v12.0.0-beta.21
* **Operating System:** Linux
* **Last Known Working Electron version:** unknown

### Expected Behavior
Dump file created.

### Actual Behavior
- The following message printed to console and no dump file created:
```
Unexpected crash report id length
Failed to get crash dump id.
Report Id:
```
- I can see `<app data path>/Crash Reports/client_id` file created only.

### To Reproduce

No minimal repro project available. I guess any app that exists with SIGSEGV should trigger the issue.

**Comment by nornagon** [comment]
@vladimiry you should be able to simulate a crash with `process.crash()`.

It would be useful to know which process is crashing — main, renderer, utility, or some node child process?

**Comment by vladimiry** [comment]
@nornagon, I just did more testing and realized that the dump gets created if I do `electron.crashReporter.start({submitURL: "https://00.00/", uploadToServer: false})` but the reported issue takes place in the case of `electron.crashReporter.start({submitURL: "https://00.00/"})` call use (no `uploadToServer: false` flag added).

> @vladimiry you should be able to simulate a crash with process.crash().

Yes it makes the main process crash and the originally reported issue takes place if the crash reporter initialized in the `electron.crashReporter.start({submitURL: "https://00.00/"})` way.

**Comment by nornagon** [comment]
I think this is intended behavior—when crashes are intended to be uploaded to the server, they aren't retained in breakpad. (I think Crashpad behaves differently). See https://source.chromium.org/chromium/chromium/src/+/master:components/crash/core/app/breakpad_linux.cc;l=1632;drc=6ba5e52941b711d4cc68ad0c928b0b407f9e4610 and https://source.chromium.org/chromium/chromium/src/+/master:components/crash/core/app/breakpad_linux.cc;l=1260;drc=adcc1b456a8129bfa26eda97e3210c2068b42924 for breadcrumbs in the source.

**Comment by vladimiry** [comment]
The doc says `Crash reports are stored temporarily before being uploaded in a directory underneath the app's user data directory` so I expected the dump to be stored since uploading was not completed. But I'm ok closing the issue since I got the dump file created.

**Comment by vladimiry** [comment]
Dump posted in #27616.

**Comment by diegogangl** [comment]
Any chance we can re open this? I'm having the same issue, it goes away with `uploadToServer: false` but I need them to be uploaded to the crash server. I'm on Fedora 34

**Comment by diegogangl** [comment]
Seems like the temp file is actually being written to `/tmp`, but it immediately gets deleted.

**Comment by vladimiry** [comment]
@diegogangl #30726.
