### ISSUE TITLE
Download dialogs recreates the last saved folder

### ISSUE THREAD

**Issue by guilhermedelucas** [electron/electron#27601]
### Issue Details

* **Electron Version:**
11.0.0
* **Operating System:**
Windows 10

### Expected Behavior
When download an item using ```<a href="...filepath">``` will trigget session will-download event.
I set the download default path before opening the Save dialog as:
```
const documentsFolderPath = path.join(app.getPath('documents'), item.getFilename());
item.setSaveDialogOptions({ defaultPath: documentsFolderPath });
```
- Opens the save dialog on the specified path. 
- Create a new folder on the dialog and save the file on this folder.
- File is saved.
- On windows explorer, I delete the previous saved folder.
- Try to save same or other file again.
- It opens the save dialog on the default folder. The deleted folder is not on the folder.

### Actual Behavior
- Electron recreates the last saved folder (the one was deleted on window explorer). This is not ok.
It seems the save dialog always remember the last path, and always recreates it.

### To Reproduce
Follow the expected behavior steps, and will result in the actual behavior on the last step.

This is my save dialog options before saving:
```
{
  window: null,
  title: '',
  message: '',
  buttonLabel: '',
  nameFieldLabel: '',
  defaultPath: 'C:\\Users\\guilherme\\Documents\\download(3).pdf',
  filters: [],
  showsTagField: false,
  securityScopedBookmarks: false
}
```

Is it a bug, a feature, or I'm missing some setup?

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by guilhermedelucas** [comment]
First time using Fiddle, can you check if it works?
https://gist.github.com/d23cc1802f479896cbbf927046b582f4

**Comment by guilhermedelucas** [comment]
I tested also on MAC OSX 11.1 (Big Sur), it has the same behavior as windows.

**Comment by ckerr** [comment]
I'm seeing the same behavior on Electron 11.2.1 on Ubuntu 20.10 when running the test gist and following the instructions listed in the main page of the app.
