### ISSUE TITLE
Web Bluetooth API calls crashes Electron

### ISSUE THREAD

**Issue by JakobOffersen** [electron/electron#27618]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 
  * v11.2.2 
* **Operating System:** 
  * macOS 11.0.1 
* **Last Known Working Electron version:**
  *  v10.x.y (but only on Mojave, see "Additional Information") 

### Expected Behavior

When I call `navigator.bluetooth.requestDevice({ acceptAllDevices: true})` I expect a promise to be returned, as described in the [documentation](https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API).

### Actual Behavior

When I call `navigator.bluetooth.requestDevice({ acceptAllDevices: true})` (or any other Web Bluetooth API call) electron crashes with the following error trace from the terminal: 
![Screenshot 2021-02-04 at 10 24 12](https://user-images.githubusercontent.com/35025032/106872043-2df38a00-66d3-11eb-879f-c1210a9daf55.png)
The log can be seen here, but nothing in it stands out to me: 
[electron crash log.txt](https://github.com/electron/electron/files/5924542/electron.crash.log.txt)

### To Reproduce

I've added a small example for you to try out here: https://github.com/JakobOffersen/electron-bluetooth-issue
Steps: 
- Clone the project: `git clone https://github.com/JakobOffersen/electron-bluetooth-issue.git`. There is only the `main` branch. 
- Run `npm install`
- Run `npm start`
- Click the "Use Web Bluetooth" button 

### Additional Information

I've run the sample project on 2 macOS versions and I found the following: 
- On MacOS Big Sur (11.0.1): Electron `beta`, `v11`, `v10` and `v9` all lead to crashes.
- MacOS Mojave (10.14.6): Electron `v9` and `v10` works as expected, but `v11` lead to crash.

**Comment by andrewrt** [comment]
I'm seeing this with Electron 16.0.6 - any chance this has resurfaced / didn't get integrated into the 16.x branch?
