### ISSUE TITLE
use 'desktopCapturer' and 'navigator.mediaDevices.getUserMedia' to capture screen and the cursor flickering

### ISSUE THREAD

**Issue by JeryZeng** [electron/electron#27617]
Enviroment : Windows10 18363.1316
Electron Version : 11.2.1
Description:
I‘m using electron to capture screen and save to file . I'm use `desktopCapturer.getSources` to get a screen video source then use `navigator.mediaDevices.getUserMedia` to generate a `MediaStream` and finally i use `MediaRecorder` to generate blobs and save them to local file , when i open the video file ,i see the cursor is flickering (cursor has some copy ) it's like a graphics drawing  problem? please see attachment video to get more information

https://user-images.githubusercontent.com/5037826/106837905-49ac5f80-66d6-11eb-9ea5-a54f615fc07b.mp4

**Comment by ckerr** [comment]
Possibly related: https://github.com/electron/electron/pull/27585

**Comment by JeryZeng** [comment]
@ckerr it's not only flickering in the `BrowserWindow` or `BrowserView` and also in other application like `photoshop` etc

**Comment by JeryZeng** [comment]
this is a new video to show how it occur in the chrome but not only in the electron app

https://user-images.githubusercontent.com/5037826/107013552-785d2f80-67d5-11eb-891a-a6c62cac2628.mp4

**Comment by danielehrhardt** [comment]
Is this fixed?

**Comment by CloudInSkyJY** [comment]
v38.4.0 still has this problem

**Comment by CloudInSkyJY** [comment]
> this is a new video to show how it occur in the chrome but not only in the electron app
> 
>  output.mp4

how do you fix this problem， buddy？
