### ISSUE TITLE
[Feature Request]: Allow passing values to executeJavaScript

### ISSUE THREAD

**Issue by Mstrodl** [electron/electron#27634]
**Preflight Checklist**

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Problem Description**

Currently, my application exposes a few native APIs to the renderer process via `contextBridge` and loads some native code which needs to touch the main world via `executeJavaScript`. I would like to make this a little safer by passing the native APIs directly to the code being called in `executeJavaScript` instead of using `contextBridge`. My first instinct was to have my `executeJavaScript` call return a function which took the native APIs as a parameter, but this doesn't work under `worldSafeExecuteJavaScript:true`.

**Proposed Solution**

Add an additional optional parameter to `executeJavaScript` which exposes the passed variables only to the evaluated script using a new scope.

For example:
```js
electron.webFrame.executeJavaScript("console.log(life)", {
  life: 42,
});
```
Will work something like this:
```js
(function(life) {
  console.log(life);
}); // <- Internal magic to call this
```

This way, our potentially dangerous values can be kept contained to just the pieces of code we want to share it with.

**Alternatives Considered**

* Perhaps simply allowing functions to be returned by `executeJavaScript` would be reasonable? It's already possible to send functions to the isolated world (like callbacks or event listeners)
* I briefly considered having my code simply unset a value added by `contextBridge` once it executes, but it's certainly not ideal because an attacker can simply: `Object.defineProperty(window, "life", {set: value => {/*evil*/})`

**Additional Information**

_No response_

**Comment by MarshallOfSound** [comment]
> I would like to make this a little safer by passing the native APIs directly to the code being called in executeJavaScript instead of using contextBridge.

Interested in why you think this is safer, `executeJavaScript` in inherently an even-less-safe version of unsafe-eval and should be avoided.

Passing arguments into `executeJavaScript` isn't possible as the code and all return values are passed through a serializer, so this won't do what you expect it to.

`contextBridge` is the only safe way to get bidirectional normal-js communication between the isolated world and the main world.

I'll keep an eye on this issue for answers to my above question, but closing out as it isn't a thing we can / should implement

**Comment by Mstrodl** [comment]
@MarshallOfSound I say 'safer' because it means the web-hosted code running in the main world can't (easily, anyway) touch the code I need to execute inside of the main world. Does this make sense? In other words, the dangerous remote code is further distanced from the privileged APIs. My architecture is a little bizarre, but it's kind of the best thing I have for keeping everything safe.
