### ISSUE TITLE
Electron SIGSEGV in Docker with spectron, jest, chromedriver

### ISSUE THREAD

**Issue by danhoffman699** [electron/electron#27631]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v12.0.0-beta.22 (although problem persists on latest v11)
* **Operating System:**
  * Ubuntu 20.04 in Docker
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
I'm attempting to run some tests in `spectron` with `chromedriver` in a Docker container. I should see the test cases in my `__tests__` fully execute (they should pass as well, as I've tested this locally outside of Docker).

### Actual Behavior
`chromedriver` reports that `node_modules/electron/dist/electron exited with signal SIGSEGV` and `spectron`/`jest` assume that `chromedriver` has crashed, as it has not received a response

Relevant `chromedriver` output

```
1612500128.804][INFO]: Launching chrome: /root/repo/node_modules/spectron/lib/launcher.js --disable-background-networking --disable-client-side-phishing-detection --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-gpu --disable-hang-monitor --disable-infobars --disable-popup-blocking --disable-prompt-on-repost --disable-sync --enable-automation --enable-blink-features=ShadowDOMV0 --enable-logging --headless --log-level=0 --no-first-run --no-sandbox --no-service-autorun --password-store=basic --remote-debugging-port=0 --spectron-arg0=/root/repo --spectron-arg1=-no-sandbox --spectron-arg2=--verbose --spectron-path=./node_modules/.bin/electron --start-minimized --test-type=webdriver --use-mock-keychain --user-data-dir=/tmp/.org.chromium.Chromium.Ig3WAg data:,
/root/repo/node_modules/electron/dist/electron exited with signal SIGSEGV
```

Relevant `spectron`/`jest` output
```
yarn run v1.22.10
$ jest
 FAIL  __tests__/AppTest.js (17.138 s)
  _ Displays App window (7 ms)

  _ Displays App window

    Timeout - Async callback was not invoked within the 15000 ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 15000 ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:27:45)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        18.168 s
Ran all test suites.
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
(node:11266) UnhandledPromiseRejectionWarning: Error: Caught error after test environment was torn down

Failed to create session.
unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /root/repo/node_modules/spectron/lib/launcher.js is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
(node:11266) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11266) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### To Reproduce
Build a Docker container with the following Dockerfile
```
FROM ubuntu

RUN apt-get update
RUN apt-get --no-install-recommends -y install nodejs npm

RUN apt-get --no-install-recommends -y install libglib2.0-dev libnss3-dev libx11-dev libx11-xcb-dev
RUN apt-get --no-install-recommends -y install libatk1.0-dev libatk-bridge2.0-dev libgdk-pixbuf2.0-dev libgtk-3-0 libdrm-dev libgbm-dev libasound2-dev
RUN apt-get -y install xvfb
RUN npm install -g yarn || true
RUN echo "PATH=$PATH:/usr/local/lib/node_modules/yarn/bin" >> /root/.bashrc

ENV DBUS_SYSTEM_BUS_ADDRESS='unix:path=/var/run/dbus/system_bus_socket'
ENV DBUS_SESSION_BUS_ADDRESS='unix:path=/var/run/dbus/system_bus_socket'

RUN apt-get -y install git tmux nano

RUN apt-get -y install dbus
RUN mkdir /var/run/dbus
```

Run the following within the Docker container on boot
```
dbus-daemon --print-address --system
```

Run the following to start `chromedriver` independently of `spectron`/`jest`
```
xvfb-run ./node_modules/electron-chromedriver/bin/chromedriver --no-sandbox --headless --disable-extensions --disable-gpu --disable-infobars --start-minimized --disable-dev-shm-usage --verbose
```

Run the following to start `spectron`/`jest`
```
xvfb-run -a yarn test
```

### Additional Information
`__tests__/AppTest.js`
```
const Application = require("spectron").Application;
const path = require("path");

let app;

beforeAll(() => {
    app = new Application({
        path: './node_modules/.bin/electron',
        chromeDriverArgs: [
            '--no-sandbox',
            '--headless',
            '--disable-extensions',
            '--disable-gpu',
            '--disable-infobars',
            '--start-minimized',
            '--disable-dev-shm-usage'
        ],
        args: [path.join(__dirname, ".."), "--no-sandbox"]
    });

    return app.start();
}, 15000);

afterAll(function () {
    if (app && app.isRunning()) {
        return app.stop();
    }
});

test("Displays App window", async function () {
    expect(1).toBe(1);
});

```

**Comment by ckerr** [comment]
@danhoffman699 did the sigsegv generate and crashfiles that you can use to get a meaningful crash report?

**Comment by danhoffman699** [comment]
It didn't by default, but I can generate and post a core file by the end of the day. What other crashfiles/telemetry can I enable?

Thanks

**Comment by danhoffman699** [comment]
I've uploaded the corefile [here](https://drive.google.com/file/d/1o_6dKxlEbyPSSzwks_QEzapGpEZ9Gban/view?usp=sharing). This corefile was reproduced outside of Docker, not sure if that's relevant here.

Let me know if there's anything else you need. Thanks

**Comment by VerteDinde** [comment]
Hey @danhoffman699, thanks for reporting this issue. Using the current latest version of Spectron with the 12 betas is probably not going to work - we'd need to cut a new version that has the correct version of Chromedriver for Electron 12.

Since this is also happening in Electron 11 (which should work with latest Spectron), would you mind opening an issue in the Spectron repo and linking it here? I'll close this one once you do, and we can continue the conversation there. That way others who might also be experiencing this with Spectron can find their solution more easily, and it won't get lost in Electron Core's larger issue tracker 🙂 Thanks!
