### ISSUE TITLE
The standard 'View' menu does not reflect the correct window state

### ISSUE THREAD

**Issue by nkavian** [electron/electron#27646]
### Preflight Checklist
* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.2.2
* **Operating System:**
  * macOS10.14.6
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior

When closing all windows, the `View` menu should dim/disable all of the submenu items since they are no longer applicable. Other menus such as `File`, `Edit`, and `Window` function correctly.

### Actual Behavior

The `View` menu only disables the menu `Toggle Full Screen`, the other menu items are not disabled as expected.

![image](https://user-images.githubusercontent.com/1127421/107130907-f88f9d80-6886-11eb-9e2f-d72550973e59.png)

### To Reproduce

Clone the existing/standard electron quick start, launch it, close the main window, then click on the `View` menu.

https://github.com/electron/electron-quick-start

```sh
$ git clone git@github.com:nkavian/electron-quick-start.git
$ cd electron-quick-start
$ git checkout window-menu-bug
$ npm install
$ npm start
```

**Comment by ckerr** [comment]
gist form of repo: https://gist.github.com/ckerr/02c1ada5a066dedcf77f9b099dadf6e7

**Comment by nkavian** [comment]
"bump"

**Comment by nkavian** [comment]
"bump"

**Comment by nkavian** [comment]
"bump"

**Comment by nkavian** [comment]
"bump"
