### ISSUE TITLE
Menu 'role' of 'window' does not work

### ISSUE THREAD

**Issue by nkavian** [electron/electron#27645]
### Preflight Checklist
* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.2.0
* **Operating System:**
  * macOS10.14.6
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior

When using a Menu `role` of `window` it should show a list of BrowserWindows exactly the same as when using a `role` of `windowMenu`. This screenshot shows it correctly working with `windowMenu`.

![image](https://user-images.githubusercontent.com/1127421/107130556-79e53100-6883-11eb-9b79-dfc917ac2903.png)

### Actual Behavior

When using a `role` of `window`, it simple displays a single submenu item labeled `Window` as seen in the picture below. You should instead see "Hello World!" listed 3 times.

![image](https://user-images.githubusercontent.com/1127421/107130591-ea8c4d80-6883-11eb-82b2-3578103191ef.png)

### To Reproduce

A very simple commit provided on the electron-quick-start: https://github.com/nkavian/electron-quick-start/commit/78a244bf79d939ab9109dbb718b6f743ad1b9c3e

The example creates 3 windows and the relevant menu entries to show it works in `windowMenu` ("Window Menu 1") but broken with `window` ("Window Menu 2").

```sh
$ git clone git@github.com:nkavian/electron-quick-start.git
$ cd electron-quick-start
$ git checkout window-menu-bug
$ npm install
$ npm start
```

**Comment by ckerr** [comment]
gist copy of repro, for easier triage: https://gist.github.com/ckerr/5a614cd82d6236a7bae011d9035994f5

nb:`role: 'window'` is a mac-only feature so this test must be run on macOS

**Comment by wolfoo2931** [comment]
I might have a related problem. 

When I'm starting the app in development mode I can cycle through the open windows by pressing `[cmd]+[<]`.
When I'm building the app for MacOS and start the build the `[cmd]+[<]` key combination does not work anymore.

This worked before and stopped working at some point. Also, I tried to modify the menu to add all kinds of roles to it. It did not solve the problem.

**Comment by ericestes** [comment]
This is still an issue, v16.0.7.

**Comment by nkavian** [comment]
"bump"

**Comment by nkavian** [comment]
"bump"

**Comment by nkavian** [comment]
"bump"

**Comment by nkavian** [comment]
"bump"
