### ISSUE TITLE
[Feature Request]: Consider publishing typescript definitons to seperate (zero dependency) npm package.

### ISSUE THREAD

**Issue by Raynos** [electron/electron#27682]
**Preflight Checklist**

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Problem Description**

I want to install the type definitions for `electron` without installing 98+ transative dependencies

```
~/optoolco/temp
$ npm ls | wc -l
99
raynos at raynos-Precision-5530  
~/optoolco/temp
$ npm ls --depth 0
temp@1.0.0 /home/raynos/optoolco/temp
└── electron@11.2.3
```

**Proposed Solution**

Dual Publish the typescript dependencies as a seperate package.

I'm currently using this 4 year old package ( https://www.npmjs.com/package/@types/electron/v/1.4.37 ) which has zero dependencies and is only typescript definitions

**Alternatives Considered**

Manually do it by copying the files and publishing it as `electron-typedefs`

**Additional Information**

Very similar to https://github.com/electron/electron/issues/16327

The proposed solution there does not work because i'd still have 99 dependencies

**Comment by MarshallOfSound** [comment]
As mentioned in that issue we can't publish to `@types/*` and I don't think there is a good way (that wouldn't cause type conflicts) to ship a secondary package with just the type definitions.

I suspect your best option for anyone wanting a solution is to manually pull the `electron.d.ts` from unpkg.com or something similar and manually keep it up to date in your version control
