### ISSUE TITLE
webPreferences not working in BrowserViews

### ISSUE THREAD

**Issue by laranjaquadrada** [electron/electron#27698]
### Preflight Checklist

* [ X ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ X ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ X ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
v11.2.3
* **Operating System:**
macOS 10.14.6
* **Last Known Working Electron version:**
Unknown...

### Expected Behavior
`BrowserView` should inherit `BrowserWindow` properties. I am able to use use `webPreferences` `preload` option to inject a script when using only 1 `BrowserWindow` but if I set 1 `BrowserWindow` and then add `BrowserViews` using `addBrowserView` method the `webPreferences` options don't seem to be respected. 

I can't have the `preload` to work and even if I put the js in my local html render file the node `require` and other node apis are not available/not found, and even if the js file only has a `console.log` or `alert` nothing happens, the `preload` file or `script src` file is not loaded correctly.

And setting `nodeIntegration` to true does not work either, it seems that `webPreferences` are just not respected in `BrowserView`.
### Actual Behavior
`BrowserView` options, specifically `webPreferences` should be respected. One should be able to use `preload` and `nodeIntegration` options in any `BrowserWindow` or `BrowserView`.
### To Reproduce
https://github.com/laranjaquadrada/electron-quick-start/blob/master/main.js
https://github.com/laranjaquadrada/electron-quick-start/blob/master/preload.js

### Additional Information
This issue was reported previously as `preload not working in BrowserView` and closed due to issues in the preload file reference location. 
But I confirmed that is not the issue since the exact same options definition works in a project with only 1 `BrowserWindow`.

To me never works when set in one attached `BrowserView`, or multiple added `BrowserViews`.

This bug was also mentioned in `stackoverflow` in November, last year: https://stackoverflow.com/a/64676851/4561667

**Comment by ckerr** [comment]
gist of @laranjaquadrada's testcase: https://gist.github.com/ckerr/d467fb8d1c884b306b0c5fc0f4d36fd5

**Comment by laranjaquadrada** [comment]
Thanks @ckerr ! What are the next steps from this? Do you think this bug can be addressed soon?

Currently my work around in my app is to use two distinct `BrowserWindows` that open separately but I really would like to have it all in just one application window using the layout split with `BrowserViews`...

Any expectation to when the dev team can pick this up and when should I expect it to be solved in a new electron release?

**Comment by Shu-Ji** [comment]
My browser view doesn't work either, only the `partition` param works:

```typescript
const view = new BrowserView({
            webPreferences: {
                partition: `persist:${args.id}`,  // this works
                nodeIntegration: true,  // not work
                contextIsolation: false,  // not work
                preload: '/tmp/preload.js',  // now work
            },
        });
```

**Comment by nornagon** [comment]
I'm confused about the example, which includes this snippet:

```
  mainView.setBounds({
    x: 0,
    y: 0,
    width: 961,
    height: 800,
    minWidth: 665,
    webPreferences: {
      preload: path.join(__dirname, '/preload.js'), //this does not work!
      nodeIntegration: true //This does not seem to work either
    }
  });
```

[`setBounds()`](https://www.electronjs.org/docs/api/browser-view#viewsetboundsbounds-experimental) does not take `webPreferences` as an option, so it's not surprising that this has no effect.
