### ISSUE TITLE
Speech-to-text inside electron, work arround?

### ISSUE THREAD

**Issue by rzfzr** [electron/electron#27690]
Hello there,
I'm trying to implement speech-to-text, I tried IBM's and Google's api, however both of them fail with similar problems, authentication/connection issues, [my issue on IBM's](https://github.com/watson-developer-cloud/node-sdk/issues/1083).
[Electron-speech](https://www.npmjs.com/package/electron-speech) does not work anymore... 
Running a vanilla node instance to converse with my electron app seems like a terrible solution, can somebody think of something else?

I'm running latest everything, I don't think it matters as looking around I can see it's a very popular issue

**Comment by ckerr** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
