### ISSUE TITLE
Pdf viewer not displaying chars correctly

### ISSUE THREAD

**Issue by mvaliani** [electron/electron#27707]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.2.3
* **Operating System:**
  * Windows 7 (we tried the iso 90-day trial from Microsoft)
* **Last Known Working Electron version:**
  * none 

### Expected Behavior
The pdf should display all characters correctly

### Actual Behavior
Opening some pdfs (one of them is attached) with the pdf viewer of electron, chars don't display correctly

### To Reproduce
Save the attached pdf in a local folder. 
Write a simple electron project creating a BrowserWindow that opens the pdf. 
Reboot the machine and launch the electron project. 
Result: electron pdf viewer doesn't display any chars in the pdf. 

It happens only with few pdfs, apparently only on Windows 7. With other pdfs it works fine. 
It is weird because if you open the same pdf with Chrome or Chromium, then it works fine also in electron, but ony until you reboot the pc.

This is a pdf example which causes the issue:
[getsimplepdf.pdf](https://github.com/electron/electron/files/5966369/getsimplepdf.pdf)

### Screenshots
PDF displaying with no chars:
![pdfNochars](https://user-images.githubusercontent.com/78218109/107656947-f2cdf980-6c84-11eb-9be2-dc5fcc217389.png)

After opening the pdf with chrome, then also pdf viewer of electron displays all chars:
![pdfWithchars](https://user-images.githubusercontent.com/78218109/107657029-0aa57d80-6c85-11eb-98a0-a76044b9ded2.png)

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by mvaliani** [comment]
As required a standalone gist testcase:
https://gist.github.com/mvaliani/f9a3529edaf480f127ebc9a05515cfa9

In attachment another pdf sample:
[getsimplepdf2.pdf](https://github.com/electron/electron/files/5978686/getsimplepdf2.pdf)

Steps to reproduce sistematically the issue (it happens on Win7 machines, also using the standard microsoft 90-days trial):
- copy the pdf file into c: drive
- copy the fiddle executable 
- reboot the machine 
- launch the fiddle exe
- it opens the pdf in the electron browserwindow but the pdf viewer doesn't display any chars

**Comment by smilejp** [comment]
have the same issue. 
i tested Windows 8.1 Pro K (just installed, cause same problem after rebooting) and electron v10.1.5.

**Comment by smilejp** [comment]
this problem is characters cannot be displayed correctly with electron native pdf viewer when the internal font is 'helvetica' in pdf.

font properties of `getsimplepdf.pdf` file (confirmed by Adobe Acroba Reader)
![image](https://user-images.githubusercontent.com/3704914/110297469-db412100-8036-11eb-8877-af7a88a5b978.png)


If pdf uses built-in fonts (Helvetica, Courier), characters will not be displayed on Win7 / Win8.1. 
(Always until you view the PDF in your browser)

**Comment by CommonLoon102** [comment]
![electron-pdf-works](https://user-images.githubusercontent.com/321850/231984305-c5ef33ab-7fcd-43da-99f4-6d96b7177dea.png)
For me it works. I have even restarted my computer.
Maybe the problem is that you are using the "N" version of Windows. That is missing some codecs and media related stuff.
