### ISSUE TITLE
Content of a webview inside of an iframe doesn't render

### ISSUE THREAD

**Issue by rzhao271** [electron/electron#27720]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 12.0.0-beta.21 (though as early as 5.0.13)
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
1. Place a webview inside of an iframe. The webview should contain a body of text within it.
2. Run the app. The text within the webview is visible.

### Actual Behavior
For step 2, the text within the webview is not visible. The webview almost seems to be minimized, size-wise.

### To Reproduce
Check the "webview inside iframe" case of the following minimal repro:
[fiddle.zip](https://github.com/electron/electron/files/5968860/fiddle.zip)

### Screenshots
The red circle surrounds the webview, which has a green border:

![webview-inside-iframe-not-render](https://user-images.githubusercontent.com/7199958/107709173-aa5d0e80-6c79-11eb-9f54-310324d398c1.PNG)

**Comment by miniak** [comment]
@rzhao271 you need to enable `nodeIntegrationInSubFrames`

**Comment by rzhao271** [comment]
Just tried adding that, but it didn't seem to work.
Here's a more minimal repro:

[smaller-repro.zip](https://github.com/electron/electron/files/5974314/smaller-repro.zip)

For this repro, I added `nodeIntegrationInSubFrames` to both `webPreferences` and to the webview tag. Here's a screenshot of the result I got when trying it with 9.3.5, though I also tried it with 11.2.0 and 12.0.0-beta.21, with the same result:

![spikeframe](https://user-images.githubusercontent.com/7199958/107823605-ef924680-6d34-11eb-9727-bd120a027763.PNG)

**Comment by zcbenz** [comment]
We have never tested loading webview tag in iframe, and I believe lots of webview code assumes it is being loaded in the main frame.

**Comment by miniak** [comment]
https://github.com/electron/electron/blob/95a867b795574689c9b6e93e3d327ccc8171eb56/lib/renderer/init.ts#L109-L113

**Comment by miniak** [comment]
@zcbenz would it make sense to allow `<webview>` in iframes, assuming that we fix any issues there?

**Comment by miniak** [comment]
we assume the main frame here for example
https://github.com/electron/electron/blob/95a867b795574689c9b6e93e3d327ccc8171eb56/lib/browser/guest-view-manager.ts#L132-L136

**Comment by zcbenz** [comment]
I'm totally fine enabling webview in iframes if there are tests added.

**Comment by rzhao271** [comment]
Just a note that VS Code is now using nested iframes so this issue isn't applicable to us anymore.

**Comment by ronpfeifle** [comment]
Has there been any progress on this?

**Comment by ronpfeifle** [comment]
still curious as to whether this is being addressed.  Obviously it's still open.

**Comment by StefanRadisavcevic** [comment]
@zcbenz Can i load webview into iframe? I really need it, but i can not do it. I can see webview as tag inside iframe when i open develop tools (inspect element), but in preview it is empty space. Please help me :/

Thanks in advance!

**Comment by StefanRadisavcevic** [comment]
@rzhao271 i didn't understand exactly what you said?
