### ISSUE TITLE
Chrome OS split-screen functionality broken

### ISSUE THREAD

**Issue by maucaro** [electron/electron#27737]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.2.3
* **Operating System:**
  * Chrome OS Version 88.0.4324.109
* **Last Known Working Electron version:**
  * 10.3.2

### Expected Behavior
Split-screen functionality working as was the case in previous versions of Electron.
 

### Actual Behavior
Split-screen functionality does not work. For reference see: https://support.google.com/chromebook/answer/177891?hl=en
(See two windows at the same time)
Error displayed by Chrome OS when attempting to use this functionality: "App does not support split-screen" 

### To Reproduce

"Hello World!" app using Electron 11.2.3 does not work (as described above). The same app using v10.3.2 works as expected.

https://gist.github.com/maucaro/f83fd6dd6490c5e6b042929a5d45d322

### Screenshots

![Screenshot 2021-02-15 5 53 02 PM](https://user-images.githubusercontent.com/4775834/108009130-dbf61280-6fb6-11eb-94a3-fe72c6496f06.png)

**Comment by VerteDinde** [comment]
Hey @maucaro, thanks for reporting this issue! Electron doesn't officially support ChromeOS, unfortunately. We'd accept PRs for this issue, but since we use this issue tracker as our team's triage board and the OS isn't officially supported, I'm going to close this for now. So sorry.
