### ISSUE TITLE
Handling class instanceof across process boundaries

### ISSUE THREAD

**Issue by ccorcos** [electron/electron#27736]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** v11.2.3
* **Operating System:** macOS 11.0.1
* **Last Known Working Electron version:** ???

### Expected Behavior

When I create a new instance of a class in the main process and pass it to the renderer process through the preload script, I want to be able to use `instanceof` to determine the type of class.

In the following example, I create a new class from the main process, pass it over to the renderer process and call `instanceof`.

```js
// shared.js
class MyValue {
  constructor(value) {
    this.value = value
  }
}
module.exports = { MyValue }

// main.js
const { MyValue } = require('./shared')
ipcMain.on('getMyValue', (event) => {
  event.returnValue = new MyValue(1)
})

// preload.js
const { ipcRenderer } = require('electron')
const { MyValue } = require('./shared')

console.log(ipcRenderer.sendSync('getMyValue') instanceof MyValue) // ❌ this is false
```

I've tried something similar using Date and verifies that Date objects do work correctly:

```js
// main.js
ipcMain.on('getDate', (event) => {
  event.returnValue = new Date()
})

// preload.js
const { ipcRenderer } = require('electron')

console.log(ipcRenderer.sendSync('getDate') instanceof Date) // ✅ this is true
```

So clearly it is possible to create an instance of a class where `instanceof` works across the process boundary. My question is how can I do this with a custom defined object?

### To Reproduce

```
git clone https://github.com/ccorcos/electron-instanceof-bug
cd electron-instanceof-bug
npm install
npm run build
npm start
```

### Additional Information

Just to explain why I'm doing this -- I'm building a database that has some internal datatypes. For example, an ID is fundamentally different from a string and I don't want a user to be able to create an ID by typing into a string input. Thus, I am representing an ID as `class Id { constructor( private uuid: string ) {} }`. That said, my database also accepts arbitrary plain JSON objects so inspecting the object structure doesn't exactly work for my needs either because `{uuid: string}` is a valid JSON object but *not* an instance of an Id class...

**Comment by MarshallOfSound** [comment]
As per the docs of all our IPC methods --> https://github.com/electron/electron/blob/master/docs/api/web-contents.md#contentssendchannel-args all things sent over IPC are serialized using the Structured Clone algorithm which means that the class and prototype information is stripped.  This is expected behavior and there is no way to "fix" or "change" that behavior.

**Comment by ccorcos** [comment]
Any comment on why this works for `Date` then? Is this manually accounted for somehow?

**Comment by MarshallOfSound** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm#supported_types

You can see in the docs for the structured clone alogirthm the support JS types. `Date` is one of them

**Comment by ccorcos** [comment]
Ah, interesting. Thanks for the link.
