### ISSUE TITLE
Process hangs on uncaught exception with BrowserWindow({show: false})

### ISSUE THREAD

**Issue by ConradIrwin** [electron/electron#27735]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v11.1.0
* **Operating System:**
  * macOS 11.2
* **Last Known Working Electron version:**
  * unknown

### Expected Behavior
When an uncaught exception happens with an invisible window, the error should be logged somewhere, and the process should either remain in a valid state or immediately exit.

### Actual Behavior
The process gets into an invalid state, and no error is reported.

### To Reproduce

Here is an electron Fiddle link: https://gist.github.com/ConradIrwin/bdcafe60f680b6013d76dc3266b9c25d

Running this code with `yarn run electron example.js` will hang indefinitely, because `app.exit(1)` in this context throws an error. Further calls to electron APIs will result in the process eventually crashing with `Error: async hook stack has become corrupted (actual: 49, expected: 0) `. I suspect this is because the uncaughtException handler added by Electron fails to work when the browser window has `show: false`.

```javascript
const { app, BrowserWindow } = require('electron')

app.on('ready', () => {
  let window = new BrowserWindow({show: false})

  window.webContents.on('did-fail-load', () => {
    app.exit(1)
  })
  window.webContents.loadURL('invalid')
})
```

To avoid the problem, and crash cleanly, adding a listener to on uncaughtException fixes the problem:

```javascript
const { app, BrowserWindow } = require('electron')

process.on('uncaughtException', e => { console.log(e) })

app.on('ready', () => {
  let window = new BrowserWindow({show: false})

  window.webContents.on('did-fail-load', function () {
    app.exit(1)
  })
  window.webContents.loadURL('invalid')
})
```

**Comment by pushkin-** [comment]
can't repro in electron 21, but I also can't repro in Electron 11.1 where you said the issue is. Process exits with exit code 1 on Windows 10
