### ISSUE TITLE
App freezes when video capturing app with Windows "Xbox Screen Recorder"

### ISSUE THREAD

**Issue by eugene-pr** [electron/electron#27733]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.2.3
* **Operating System:**
  * MS Windows Pro 10.0.19041
* **Last Known Working Electron version:**
  * 9.1.2

### Expected Behavior
When trying to video capture app using windows tool "Xbox Screen Recorder" the app should behave normally, not to freeze and be clickable.

### Actual Behavior
App freezes while recording video using Windows tool "Xbox screen recorder"

### To Reproduce

1. Install electron-quick-start
2. run it
3. Winkey + G, "xbox screen recorder" should open up
4. Click on the record button
5. Try to select text. It won't work only after stopping record

**Comment by alimuddins** [comment]
hello,
This is exactly same issue I am facing, any update on this issue?
@eugene-pr did you find any solution for this?
