### ISSUE TITLE
Require inside iframe

### ISSUE THREAD

**Issue by ShlomiRex** [electron/electron#27743]
I just want to run simple typescript in renderer context, inside iframe.
Is there a way to do this?

For example. in `index.html`:
```
...
<!-- A complex GUI / renderer element -->
<iframe src="test.html"></iframe>
...
<!-- Use typescript compiled output(JS) for index.html -->
<script>
require("../dist/renderer.js")
</script>
...
```
And in `test.html`:
```
...
<!-- Use renderer code for ONLY this file (test.html, unrelated to index.html) -->
<script>
	require("../dist/test.js")
</script>
...
```

Or is everything must be inside huge bloated code in `renderer.ts`?

If not then how can you seperate HTML elements to "iframe"s and each one has diffirent renderer code?
What is going on with electron?

**Comment by zcbenz** [comment]
There is an experimental `nodeIntegrationInSubFrames` option to enable it.

**Comment by ShlomiRex** [comment]
> There is an experimental `nodeIntegrationInSubFrames` option to enable it.

Thanks man! Sorry for being rude! It's frustrating :\
