### ISSUE TITLE
Discord Bot Client Broke my bot !

### ISSUE THREAD

**Issue by Nutelaspaceman** [electron/electron#27755]
So as all of you know bots have discord nitro i tried to change my pfp to a gif it did but it wasnt live i didnt had a problem with that so i tried to change it again the first time said claim your acc i closed the app and re-launched it and the pfp was there i tried again to change the pfp but it didnt did anything so i logged out and logged in again but when i pasted my bots token it told me to put my real discord acc and now im stuck with an ugly pfp plz someone help

**Comment by AndrewDaGuy** [comment]
@Nutelaspaceman :/ What does "discord bot client" have to do with electron itself  You should be posting issues in the repository that you found the client which is pretty much common sense .-. .

As a side note discord bots do not have nitro, they have there "special perks" which does not include animated profiles.
