### ISSUE TITLE
Custom File Protocols Result in Request Failure

### ISSUE THREAD

**Issue by Catlinz** [electron/electron#27762]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * Appears to be affecting v10.1.3 -> 12.0.0-beta.26, so seems to be introduced in v10.1.3
  * Also affects v9.3.2 -> v9.4.3
* **Operating System:**
  * Windows 10 (1909)
* **Last Known Working Electron version:**
  * v10.1.2 and v9.3.1

### Expected Behavior
When registering two (standard scheme) custom file protocols on the same Session (e.g., app-file:// and app-cache://) requests made from a page loaded using one of the protocols should not cause a page loaded using the other protocol to fail the request.

### Actual Behavior
When registering two (standard scheme) custom file protocols on the same Session (e.g., app-file:// and app-cache://), if a request is made from a page loaded using the app-cache:// protocol and then the same request is made from a page using the app-file:// protocol, the second request fails with CORS error message.

### To Reproduce
https://gist.github.com/41b354766240ff8854f8f362a0870576

Using the electron fiddle gist above, run it, then in the dev tools for file loaded with the app-cache:// protocol, run the following in the console: 
`fetch('https://media.sproutsocial.com/uploads/2017/02/10x-featured-social-media-image-size.png')`

Then, in the console for the app-file:// protocol, run the same code in the console.  The request should fail with some CORS error.

If you run the gist, and instead just execute the above fetch in the dev tools for the the app-file:// protocol page, it will succeed.

It appears that when first fetching the request via the app-cache:// protocol page, the request is cached, then when the app-file:// protocol page attempts to fetch it, it seems to have an issue thinking that it is cached, but not really, since if you disable the cache for that page in the dev tools, the fetch will then work properly again.

Also, the order is important, it has to be the app-cache:// page first and then the app-file:// page, for some reason.

### Screenshots
First, successful request:
![image](https://user-images.githubusercontent.com/11395871/108240226-7fead580-70ff-11eb-98a5-d1234d94142e.png)

Second, failed request:
![image](https://user-images.githubusercontent.com/11395871/108240335-998c1d00-70ff-11eb-8aac-e63cbeebdf7c.png)

### Additional Information
Since v9.3.2 and 10.1.3 both contained the fix for CORS not being disabled by `webSecurity: false`, maybe has something to do with caching and the first page / context having `webSecurity: false`, and then the second one having `webSecurity: true`?

**Comment by ckerr** [comment]
Confirmed on Ubuntu 20.10.

Steps: as described above, run `await fetch('https://media.sproutsocial.com/uploads/2017/02/10x-featured-social-media-image-size.png')` in first the `app-cache://` window's devtools console, then the `app-file://` window's devtools console.

In Electron 10.0.0, both windows yield `Response {type: "basic", url: "https://media.sproutsocial.com/uploads/2017/02/10x-featured-social-media-image-size.png", redirected: false, status: 200, ok: true, …}`

In Electron 11.0.0, the latter (app-file) yields

```
Access to fetch at 'https://media.sproutsocial.com/uploads/2017/02/10x-featured-social-media-image-size.png' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
VM154:1 GET https://media.sproutsocial.com/uploads/2017/02/10x-featured-social-media-image-size.png net::ERR_FAILED
(anonymous) @ VM154:1
Uncaught TypeError: Failed to fetch
```

**Comment by Catlinz** [comment]
Just confirming that this is still an issue on the latest Electron versions (14.0.0 and 15.0.0-beta.1)

**Comment by Catlinz** [comment]
Just updating that this is still an issue on the latest Electron versions (18.2.1 and 19.0.0-alpha.5)

**Comment by AZforyo** [comment]
I have the same problems Electron v21.1.1 
My app's page has a <iframe> ,and this iframe loading a other website page, in this page has a action that is calling the parent page's object such as : parent.window.Object, but an CORS error has occurred.
**DOMException: Blocked a frame with origin "http://xx.xx.com.cn/" from accessing a cross-origin frame.**
So what should I do for resolving this problem?
The following methods are unable for this Electron 21.1.1 version.

    app.commandLine.appendSwitch('disable-features', 'OutOfBlinkCors');
    app.commandLine.appendSwitch("disable-site-isolation-trials");
