### ISSUE TITLE
Using CDP Fetch domain via webContents.debugger with auto-attached targets stops working in 11.x, causes crash in 12.x

### ISSUE THREAD

**Issue by ikreymer** [electron/electron#27768]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

The runnable example below uses use the debugger API and enables the Fetch domain to intercept requests on the main frame, as well as any attached iframes. The goal is to be able to intercept requests via Fetch.requestPaused on the top frame, and automatically attach and also enable request interception on any iframe.

This example works perfectly in Electron 10.2.3
In 11.2.3, the iframe seems to stop loading (the Fetch.continueRequest doesn't go through?)
In 12.0.0 beta, this causes a crash altogether.

**Electron Version:**
* 11.2.3
* 12.0.0-beta.26

**Operating System:** 
* MacOS 10.14.6
  
**Last Known Working Electron version:**
* 10.3.2

### Expected Behavior

The app should not crash, and the youtube video should load. Clicking play should start playing,
and the intercepted urls will be logged to the console.

### Actual Behavior

In 11.2.3, the youtube video does not show up at all, just a black box, but the app does not crash.
In 12.0.0-beta.26, the app crash immediately on load.

### To Reproduce

Gist: https://gist.github.com/ckerr/2f264a9ae74ea876e98490b7288857f5

This example uses `https://oembed.link/https://www.youtube.com/watch?v=M7lc1UVf-VE`, which just loads a single iframe with a youtube video, but I suspect the issue repros on any page that has an iframe. (Tried it on a few others, including non-youtube).

```javascript
const {app, BrowserWindow} = require('electron');
const path = require('path');

var mainWindow;

async function init(url) {
   // load about:blank first, just in case, before attaching debugger
   // (doesn't seem to make a difference)
  await mainWindow.loadURL("about:blank");
  
  mainWindow.webContents.debugger.attach("1.3");

  await initTarget();

  mainWindow.webContents.debugger.on('message', async (event, method, params, sessionId) => {
    if (method === 'Fetch.requestPaused') {
      console.log("url", params.request.url);
      await send("Fetch.continueRequest", {requestId: params.requestId }, sessionId);
    }
    if (method === "Target.attachedToTarget") {
      await initTarget(params.sessionId);

      if (params.waitingForDebugger) {
        await send('Runtime.runIfWaitingForDebugger', null, params.sessionId);
      }
    }
  });

  await mainWindow.loadURL(url);
}

async function initTarget(sessionId) {
  await send("Fetch.enable", {patterns: [{urlPattern: "*", requestStage: "Response"}]}, sessionId);

  await send("Target.setAutoAttach", {autoAttach: true, waitForDebuggerOnStart: true, flatten: true }, sessionId);
}

async function send(method, params, sessionId) {
  if (sessionId) {
    await mainWindow.webContents.debugger.sendCommand(method, params, sessionId);
  } else {
    await mainWindow.webContents.debugger.sendCommand(method, params);
  }
}

app.whenReady().then(() => {
  mainWindow = new BrowserWindow({
    width: 1024,
    height: 768,
    webPreferences: {
      contextIsolation: true,
    }
  });

  init("https://oembed.link/https://www.youtube.com/watch?v=M7lc1UVf-VE");
});
```

### Console Output on 10.3.2:

Iframe URLs loaded:
```
url https://oembed.link/https://www.youtube.com/watch?v=M7lc1UVf-VE
url https://www.youtube.com/embed/M7lc1UVf-VE?feature=oembed
url https://www.youtube.com/s/player/6eebf7aa/www-player-webp.css
url https://www.youtube.com/s/player/6eebf7aa/www-embed-player.vflset/www-embed-player.js
url https://fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2
url https://www.youtube.com/s/player/6eebf7aa/player_ias.vflset/en_US/base.js
url https://www.youtube.com/s/player/6eebf7aa/fetch-polyfill.vflset/fetch-polyfill.js
url https://www.youtube.com/s/player/6eebf7aa/player_ias.vflset/en_US/remote.js
url https://www.google.com/js/bg/KMBS0uYb27SoXpRfeqhVXCVI9MZcOZ5lTWsq5C5IQSA.js
url https://static.doubleclick.net/instream/ad_status.js
url https://googleads.g.doubleclick.net/pagead/id
url https://www.youtube.com/s/player/6eebf7aa/player_ias.vflset/en_US/embed.js
url https://yt3.ggpht.com/ytc/AAUvwngOju7AKiAvKEs1wtsZN366tyNPyMq3nD8eFkMF7bE=s68-c-k-c0x00ffffff-no-rj
url https://i.ytimg.com/vi_webp/M7lc1UVf-VE/sddefault.webp
url https://www.gstatic.com/cv/js/sender/v1/cast_sender.js
```

### Console Output on 11.2.3
Iframe requests not being loaded -- Fetch.continueRequest doesn't seem to be happening...
```
url https://oembed.link/https://www.youtube.com/watch?v=M7lc1UVf-VE
url https://www.youtube.com/embed/M7lc1UVf-VE?feature=oembed
```

### Console Output on 12.0.0-beta.26
Iframe requests not being loaded followed by instant segfault
```
url https://oembed.link/https://www.youtube.com/watch?v=M7lc1UVf-VE
url https://www.youtube.com/embed/M7lc1UVf-VE?feature=oembed
<segfault>
```

**Comment by ikreymer** [comment]
Partial stack trace from 12.0.0 in case helpful:

```
Process:               Electron [42158]
Path:                  /Users/USER/*/Electron.app/Contents/MacOS/Electron
Identifier:            com.github.Electron
Version:               12.0.0-beta.26 (12.0.0-beta.26)
Code Type:             X86-64 (Native)
Parent Process:        ??? [42157]
Responsible:           Electron [42158]
User ID:               501

Date/Time:             2021-02-17 17:23:11.330 -0800
OS Version:            Mac OS X 10.14.6 (18G103)
Report Version:        12
Anonymous UUID:        AB528F3B-DAEC-9F6A-427D-27FD594C11BB

Sleep/Wake UUID:       1CEA915E-40DD-4C87-84B4-5EE0E706123F

Time Awake Since Boot: 530000 seconds
Time Since Wake:       9700 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000000000000000c
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [42158]

VM Regions Near 0xc:
--> 
    __TEXT                 000000010c8d3000-000000010c927000 [  336K] r-x/r-x SM=COW  /Users/USER/*/Electron.app/Contents/MacOS/Electron

Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   com.github.Electron.framework 	0x0000000114ae9ea6 v8::internal::  (v8::internal::Heap*) + 3410038
1   com.github.Electron.framework 	0x0000000114ae9310 v8::internal::SetupIsolateDelegate::SetupHeap(v8::internal::Heap*) + 3407072
...
``

**Comment by ikreymer** [comment]
Attaching the debugger to a webview instead of a BrowserWindow does seem to work in all versions.



Here's the equivalent:

```javascript
const {app, BrowserWindow} = require('electron');

var mainWindow;

app.commandLine.appendSwitch('disable-features', 'CrossOriginOpenerPolicy');

async function init(contents, url) {
  // load about blank first, just in case
  await contents.loadURL("about:blank");

  contents.debugger.attach("1.3");

  await initTarget(contents);

  contents.debugger.on('message', async (event, method, params, sessionId) => {
    if (method === 'Fetch.requestPaused') {
      console.log("url", params.request.url);
      await send(contents, "Fetch.continueRequest", {requestId: params.requestId }, sessionId);
    }
    if (method === "Target.attachedToTarget") {
      await initTarget(contents, params.sessionId);

      if (params.waitingForDebugger) {
        await send(contents, 'Runtime.runIfWaitingForDebugger', null, params.sessionId);
      }
    }
  });

  await contents.loadURL(url);
}

async function initTarget(contents, sessionId) {
  await send(contents, "Fetch.enable", {patterns: [{urlPattern: "*", requestStage: "Response"}]}, sessionId);

  await send(contents, "Target.setAutoAttach", {autoAttach: true, waitForDebuggerOnStart: true, flatten: true }, sessionId);
}

async function send(contents, method, params, sessionId) {
  if (sessionId) {
    await contents.debugger.sendCommand(method, params, sessionId);
  } else {
    await contents.debugger.sendCommand(method, params);
  }
}

app.on("web-contents-created", (event, webContents) => {
  webContents.on("did-attach-webview", (event, webContents2) => {
    init(webContents2, "https://oembed.link/https://www.youtube.com/watch?v=M7lc1UVf-VE");
  });
});

app.whenReady().then(() => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    width: 1024,
    height: 768,
    webPreferences: {
      contextIsolation: false,
      webviewTag: true,
    }
  });

  mainWindow.loadFile("index.html");
});
```

With `index.html`:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
    <style>
    head, body {
      width: 100vw;
      height: 100vh;
    }
    </style>
  </head>
  <body>
    <webview src="about:blank" style="width: 100vw; height: 100vh"></webview>
  </body>
</html>
```

For my use case, webview is fine, so am using that as an alternative for now.

**Comment by ikreymer** [comment]
One more update, if the Page domain is also enabled, eg:

```
async function initTarget(contents, sessionId) {
  await send(contents, "Page.enable");

  await send(contents, "Fetch.enable", {patterns: [{urlPattern: "*", requestStage: "Response"}]}, sessionId);

  await send(contents, "Target.setAutoAttach", {autoAttach: true, waitForDebuggerOnStart: true, flatten: true }, sessionId);
}
```

then:
- 11.2.3 sometimes works like 10.3.2, sometimes iframe doesn't load as before. possibly a race condition somewhere?
- 12.0.0-beta.26 still crashes 100% of the time.

**Comment by ckerr** [comment]
Gist copy of original testcase: https://gist.github.com/ckerr/2f264a9ae74ea876e98490b7288857f5

I've confirmed the behavior in the original report on Ubuntu 20.10: the testcase works for me when tested on Electron 10.3.2, is nonfunctional in 11.0.0, and flat-out crashes in 12.0.0-beta.29.

**Comment by VerteDinde** [comment]
@ikreymer Sorry, would you happen to have the full dump/crash file that the stack trace came from? We may be able to get some more information from it, but it unfortunately cuts off a bit early 🙂 Thanks again for reporting!

**Comment by VerteDinde** [comment]
Looks like the crash itself began in 12.0.0-beta.21, likely as part of the Chromium upgrade here: https://github.com/electron/electron/pull/27280 Prior to that, it behaves the same as 11.2.3 (showing a black box with no crash)

**Comment by uihoh0** [comment]
> Looks like the crash itself began in 12.0.0-beta.21, likely as part of the Chromium upgrade here: #27280 Prior to that, it behaves the same as 11.2.3 (showing a black box with no crash)

Do not work in 13.1.0 too. When the first Fetch.requestPaused that triggered by a iframe comes in, any other iframe-request just pending forever, seems like the Fetch.continueRequest didn't go through.

**Comment by uihoh0** [comment]
> Looks like the crash itself began in 12.0.0-beta.21, likely as part of the Chromium upgrade here: #27280 Prior to that, it behaves the same as 11.2.3 (showing a black box with no crash)

Do not work in 13.1.0 too. When the first Fetch.requestPaused that triggered by a iframe comes in, any other iframe-request just pending forever, seems like the Fetch.continueRequest didn't go through.

**Comment by nornagon** [comment]
Please attach a crash dump. You can collect them by adding the following snippet to your main process code, before app.whenReady:

```js
const { app, crashReporter } = require('electron')

console.log(app.getPath('crashDumps'))
crashReporter.start({ submitURL: '', uploadToServer: false })
```

Then reproduce the crash, zip up the crash dumps directory and attach it here.

**Comment by ikreymer** [comment]
It appears that adding `app.commandLine.appendSwitch("disable-site-isolation-trials");` fixes the error and behavior in both BrowserWindow and webview approaches. Unfortunately, that brings additional issues such as #28316 and #26714
