### ISSUE TITLE
PowerMonitor incorrectly omits Linux for suspend, resume events

### ISSUE THREAD

**Issue by trae-op** [electron/electron#27761]
https://www.electronjs.org/docs/api/power-monitor#powermonitor
Previously used to be 'suspend, resume' events also for linux. 
Why you remove it? 
Are there alternative solutions?
I need to after sleep mode "resume" event returns sleep time.
And now if update electron, it will not work.

**Comment by ckerr** [comment]
Implemented in https://github.com/electron/electron/pull/11306

Looks like this was an accidental omission in https://github.com/electron/electron/pull/11306. That PR correctly noted that `on-ac` and `on-battery` are not currently supported on Linux but `suspend` and `resume` were added by https://github.com/electron/electron/pull/25149 and seem to still be there.

The docs should be updated accordingly.
