### ISSUE TITLE
Q: How to open non-fullscreen windows from the fullscreen main window?

### ISSUE THREAD

**Issue by clicliclick** [electron/electron#27773]
Hello.

I'm making a game using Electron and I want the level editor to open in a separate window. The `fullscreen` is set to `true`. But I want the editor to open in non-fullscreen mode!

Please help. I'd like to use Web JS built-in tools like `window.open`, but if it's impossible I will use anything else.

**Comment by ckerr** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps. Good luck!
