### ISSUE TITLE
Sometimes all clicks have to be done twice in entire app to perform any action

### ISSUE THREAD

**Issue by SnehalJ1509** [electron/electron#27784]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.0
* **Operating System:**
  * MacOS 10.13.6, Windows 10 Pro
* **Last Known Working Electron version:**
  *  not known

### Expected Behavior
When Electron app is build for both MacOS and Windows and published to MS App Center and downloaded from it, the app should work without any problem.

### Actual Behavior
When Electron app is build for both MacOS and Windows and published to MS App Center and downloaded from it, sometimes all the clicks have to be done twice in entire app to perform any action. It is sporadic, so not reproducible all the time.

### To Reproduce
Currently I do not have an example ready but soon will try to provide one. Otherwise if time provides, you can try publishing the app in MS App Center, download it and then run the app.

**Comment by ckerr** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life in November 2020 and is [no longer supported](https://www.electronjs.org/blog/electron-11-0#end-of-support-for-8xy), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/docs/tutorial/support#supported-versions) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.
