### ISSUE TITLE
will-continue-activity and continue-activity events are not being triggered

### ISSUE THREAD

**Issue by lesleyandreza** [electron/electron#27783]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.2.3
* **Operating System:**
  * macOS 10.15.7

### Expected Behavior
During a handoff activity (with the App closed), it opens automatically and the events [`will-continue-activity`](https://www.electronjs.org/docs/api/app#event-will-continue-activity-macos) and [`continue-activity`](https://www.electronjs.org/docs/api/app#event-continue-activity-macos) should be triggered.
### Actual Behavior
During a handoff activity (with the App closed), it opens automatically, but the events `will-continue-activity` and `continue-activity` are not being triggered.
### To Reproduce
If the App is open the problem does not happen.
With a closed App, continue a handoff activity, then the App will open, but the events `will-continue-activity` and` continue-activity` will not be triggered.
After the app is opened automatically, if you try to trigger the handoff again, the events are not triggered either. So the problem persists after the App has been opened automatically. The events are only triggered again in the case of closing the App completely and opening it manually.

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
