### ISSUE TITLE
File downloads using electron.net requests piped to writable streams silently stops

### ISSUE THREAD

**Issue by andreasdj** [electron/electron#27805]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 12.0.0-beta.26
* **Operating System:**
  * Windows 10 (2004)
* **Last Known Working Electron version:**
  * 11.2.3

### Expected Behavior
When piping a file response stream initiated by an `electron.net.request` to a writable file stream, I expect it to successfully download and save the file using a stable internet connection.

### Actual Behavior
The download stops randomly and most often never completes.

### To Reproduce
The following gist includes an example of how the issue can be reproduced:
https://gist.github.com/c940aa29e51685fe0a7fe5b68ca247ad

### Additional Information
I've tried to find the root cause for this intermittent issue but without success so far. It seems to be a combination of the buffering inside the node Stream `pipe` method and the `electron.net.request`. Adding a couple of tests made that might give some more insight:

- By skipping buffering and using something like `response.on('data', (chunk: Buffer) => fileStream.write(chunk))` directly I cannot reproduce the issue.
- By increasing the highWaterMark (>512kb) for the writable target stream the issue happens more rarely.
- By adding an extra delay after the app ready event the issue happens more rarely.
- By using an external library (`got`) not using electron.net for making the request I'm able to pipe the response to the target stream without any issues.
- By using another session than the `defaultSession` the issue happens more rarely

**Comment by khwaaj** [comment]
I debugged this today and found a race condition related to the resume callback in [IncomingMessage](https://github.com/electron/electron/blob/dfed04b71b91b92a6018d421d9d3319f6153e83e/lib/browser/api/net.ts#L38). Apparently the `resume` callback can trigger `_storeInternalData` before the stored value is [overwritten with `null`](https://github.com/electron/electron/blob/dfed04b71b91b92a6018d421d9d3319f6153e83e/lib/browser/api/net.ts#L125), causing the new value to be overwritten instead, and thus stalling the download.

This is the pattch I applied to our fork to fix the issue:

```diff
commit 6c6c068535ff18cb582c7a962c9be631a33d104d (HEAD -> castlabs/12-x-y-wvvmp)
Author: Emil Pettersson <khwaaj@gmail.com>
Date:   Wed Feb 24 17:29:47 2021 +0100

    Fix potential race-condition in electron.net (see https://github.com/electron/electron/issues/27805)

diff --git a/lib/browser/api/net.ts b/lib/browser/api/net.ts
index c50395668f..8c19fb7ada 100644
--- a/lib/browser/api/net.ts
+++ b/lib/browser/api/net.ts
@@ -119,10 +119,13 @@ class IncomingMessage extends Readable {
       this._shouldPush = this.push(chunk);
     }
     if (this._shouldPush && this._resume) {
-      this._resume();
       // Reset the callback, so that a new one is used for each
-      // batch of throttled data
+      // batch of throttled data. Do this before calling resume to avoid a
+      // potential race-condition
+      const resume = this._resume;
       this._resume = null;
+
+      resume();
     }
   }
```

**Comment by ckerr** [comment]
I'm not able to reproduce the bug locally; but given the description that it only occurs some of the time, perhaps that's to be expected.

Looks like that code in question changed about 5 months ago with https://github.com/electron/electron/pull/25531. Pinging @zcbenz who authored that PR and @nornagon who reviewed; does the diff in https://github.com/electron/electron/issues/27805#issuecomment-785225399 seem reasonable?

Actually @khwaaj even better, could you submit a new PR against the master branch in Electron containing this diff, with a description pointing back to this issue URL?

**Comment by khwaaj** [comment]
@ckerr, sure, just submitted the PR.

Yes, my conclusion is also that #25531 introduced the race, but it doesn't seem to trigger easily in normal use so it probably went mostly unnoticed until now.

I would expect reproducibility varies depending on the executing environment. On my particular test system I have effectively 100% reproducibility if I execute the download immediately on receiving the `ready` event, piping it to a file much like the example gist does.

**Comment by VerteDinde** [comment]
@ckerr @khwaaj Sorry, I think I introduced the original change that led to the race condition 😅 Your change looks good to me! We had added a test to ensure the download continued correctly, and it seems to be passing here - I'll let nornagon also take a look, but this change seems safe.

**Comment by marcoancona** [comment]
Thanks for fixing this. We spent quite some time understanding what was causing `electron-updater` to fail completing the download. Fyi, this was happening ~100% of the time on Apple M1.
