### ISSUE TITLE
Cannot find module 'x' when required inside web worker

### ISSUE THREAD

**Issue by m4heshd** [electron/electron#27802]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 11.2.3
* **Operating System:** Windows 10 20H2

### Expected Behavior
Node modules being able to load in a web worker if `nodeIntegrationInWorker` is set to true. _(I also have `nodeIntegration` for my renderer set to true)_

### Actual Behavior
Throws the following error when trying to load an installed node module. Works fine with inbuilt node modules.

![image](https://user-images.githubusercontent.com/6711514/108420070-50e87700-7259-11eb-8459-0ce3c9f88891.png)

### To Reproduce
Simply require any installed module from inside the web worker.

### Additional Information
All the require calls works fine outside the web worker.

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by m4heshd** [comment]
Hi @ckerr,
Thank you for the response. Unfortunately I don't have the code I've used to test it anymore. I switched to Electron 12 + worker threads. It's much more reliable and stable. But have to run it in the main process which most of the time is an inconvenience. This definitely is a bug. Also mentioned [here](https://stackoverflow.com/questions/54414691/cannot-require-node-modules-in-electron-worker-process).

As I've said, simply just start an empty worker with a require for an external module. It'll fail. Hope this get fixed. Much better if worker threads can function in the renderer.

**Comment by bendan321** [comment]
I had the same problem， Have you solved it？

**Comment by m4heshd** [comment]
@bendan321 Web worker in Electron is way too unstable to use with anything critical. I didn't manage to solve this particular issue. Tried everything. No help either. I think people aren't actually using web worker because then they all must be running into this issue. So as a workaround I've gone ahead with worker threads in the main process. I suggest you go with the same strategy. The word **"workaround"** is a constant when it comes to working with Electron rather than **"fix"** or **"solution"**.

**Comment by LeonanCarvalho** [comment]
@ckerr 

I'm facing the same issue, also opened an issue at electron-builder ( https://github.com/electron-userland/electron-builder/issues/5706) before seeing this issue.

I made a gist and also now a demo of how to test it.
https://github.com/LeonanCarvalho/electron-quick-start

It will work on dev (electron .) but not for the packed one.

**Comment by nornagon** [comment]
@LeonanCarvalho that example seems to be using Node's `worker_threads` module, not [Web Workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API), unless I'm missing something? If it's about worker_threads, then it's a different issue to the one being evaluated here.

**Comment by caocong1** [comment]
I have the same issue, and using WebPack 5 https://webpack.js.org/guides/web-workers/ like this.
Is there any better ways to Multithreading with 3rd modules?

**Comment by LeonanCarvalho** [comment]
> @LeonanCarvalho that example seems to be using Node's `worker_threads` module, not [Web Workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API), unless I'm missing something? If it's about worker_threads, then it's a different issue to the one being evaluated here.

Yes and no, the issue is the same for different approaches as you can see in details here https://github.com/electron-userland/electron-builder/issues/5706
