### ISSUE TITLE
ffmpeg crashes in electron mac apple store build

### ISSUE THREAD

**Issue by MartinBarker** [electron/electron#27829]
**UPDATE**
I found the command `otool -L ffmpeg-mac/ffmpeg | grep /usr/local` which shows me which dynamicly linked files are in my ffmpeg build, it was point to 3 files so I moved them to my desktop and then built my mac apple store build, uploaded it to the app store, downloaded it, and tried to run it again but got a new less-descriptive error:
```
/Users/martinbarker/Documents/projects/digify-new/dist/mas/Digify.app/Contents/Resources/app.asar/node_modules/execa/lib/error.js:59 Uncaught (in promise) Error: Command failed with exit code 1: /Users/martinbarker/Documents/projects/digify-new/dist/mas/Digify.app/Contents/Resources/ffmpeg -i /Users/martinbarker/Downloads/Felix Lebarty - Bobo/06. Special Lady.mp3 -y -filter_complex concat=n=1:v=0:a=1 -c:a libmp3lame -b:a 320k /Users/martinbarker/Downloads/Felix Lebarty - Bobo/output-887564.mp3
ffmpeg version N-101191-g51a9f487ae-ntd_20150128 Copyright (c) 2000-2021 the FFmpeg developers
  built with Apple LLVM version 10.0.1 (clang-1001.0.46.4)
  configuration: pkg_config='pkg-config --static' --pkg-config-flags=--static --libdir=/usr/local/lib --extra-version=ntd_20150128 --disable-shared --disable-lzma --enable-gpl --enable-pthreads --enable-nonfree --disable-libass --enable-libfdk-aac --enable-libmp3lame --enable-libx264 --enable-static --enable-filters --enable-runtime-cpudetect
  libavutil      56. 65.100 / 56. 65.100
  libavcodec     58.125.100 / 58.125.100
  libavformat    58. 68.100 / 58. 68.100
  libavdevice    58. 12.100 / 58. 12.100
  libavfilter     7.107.100 /  7.107.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
[mp3 @ 0x7f9ba4802800] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from '/Users/martinbarker/Downloads/Felix Lebarty - Bobo/06. Special Lady.mp3':
  Metadata:
    comment         : 
    album           : Bobo
    artist          : Felix Lebarty
    title           : Funkytown Eklablog
    genre           : Boogie
    date            : 1984
  Duration: 00:03:35.33, start: 0.000000, bitrate: 320 kb/s
  Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 320 kb/s
/Users/martinbarker/Downloads/Felix Lebarty - Bobo/output-887564.mp3: Operation not permitted
    at makeError (/Users/martinbarker/Documents/projects/digify-new/dist/mas/Digify.app/Contents/Resources/app.asar/node_modules/execa/lib/error.js:59)
    at handlePromise (/Users/martinbarker/Documents/projects/digify-new/dist/mas/Digify.app/Contents/Resources/app.asar/node_modules/execa/index.js:114)
    at async file:/Users/martinbarker/Documents/projects/digify-new/dist/mas/Digify.app/Contents/Resources/app.asar/src/js/newindex.js:1151
```
The error says `command failed with exit code 1 Operation not permitted`, am I missing some entitlements for saving files on my computer in the final mac apple store build that gets uploaded to the app store?

_____

I am trying to release an electron app on the Mac Apple Store (mas), my electron app uses ffmpeg to render videos. In order to release my app on the mac apple store, It needs to be sandboxed, and by default ffmpeg makes calls to external libraries so I need to statically build ffmpeg and package it with my app. I have successfully built my app, submitted it to the app store, had it approved, and downloaded/used it but my ffmpeg fails with this errir:

```
Uncaught (in promise) Error: Command was killed with SIGABRT (Aborted): /Users/martinbarker/Documents/projects/digify-new/dist/mas/Digify.app/Contents/Resources/ffmpeg -i /Users/martinbarker/Downloads/Steve Leach With The Crystal Grass Orchestra – Ocean Potion/9. Get Out In The Sun.flac -i /Users/martinbarker/Downloads/Steve Leach With The Crystal Grass Orchestra – Ocean Potion/10. Golden Hues.flac -y -filter_complex concat=n=2:v=0:a=1 -c:a libmp3lame -b:a 320k /Users/martinbarker/Downloads/Steve Leach With The Crystal Grass Orchestra – Ocean Potion/output-261020.mp3
dyld: Library not loaded: /usr/local/opt/libass/lib/libass.9.dylib
  Referenced from: /Users/martinbarker/Documents/projects/digify-new/dist/mas/Digify.app/Contents/Resources/ffmpeg
  Reason: no suitable image found.  Did find:
    file system sandbox blocked open() of '/usr/local/opt/libass/lib/libass.9.dylib'
    /usr/local/opt/libass/lib/libass.9.dylib: stat() failed with errno=1
    file system sandbox blocked open() of '/usr/local/lib/libass.9.dylib'
    file system sandbox blocked open() of '/usr/local/Cellar/libass/0.15.0/lib/libass.9.dylib'
    at makeError (/Users/martinbarker/…eca/lib/error.js:59)
    at handlePromise (/Users/martinbarker/…/execa/index.js:114)
    at async file:/Users/ma…js/newindex.js:1151
```
I think this line is important; `file system sandbox blocked open() of '/usr/local/opt/libass/lib/libass.9.dylib'` but I'm not sure what I should change with my static ffmpeg build so that it works in production and so that I can avoid the above error.

My code is available on the branch mas-attempt-after-redesign here: https://github.com/MartinBarker/digify/tree/mas-attempt-after-redesign

Inside my package.json I have the command download-ffmpeg which clones the ffmpeg repo, runs a configure command with some flags, and then builds ffmpeg into a folder called 'ffmpeg-mac', this folder gets packaged with the app for the mac apple store build.
```
git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg-mac && cd ffmpeg-mac && ./configure pkg_config='pkg-config --static' --pkg-config-flags='--static' --libdir=/usr/local/lib --extra-version=ntd_20150128 --disable-shared --disable-lzma --enable-gpl --enable-pthreads --enable-nonfree --enable-libass --enable-libfdk-aac  --enable-libmp3lame  --enable-libx264 --enable-static --enable-filters --enable-runtime-cpudetect && make && cd ..
```
You can see in the above ffmpeg command the flag --enable-libass, but even though I have that flag included, after I build and sign my mac apple store build by running sudo rm -rf dist/mas/ && npm run build-mas && sh mas-sign-script.sh, the production build (once approved) fails with the above included error.

**Comment by ckerr** [comment]
Hi Martin,

I'm not sure what to do this this -- it sounds more like a custom build issue than it is an Electron bug, so unless I'm misunderstanding the issue I don't think this is an issue that we can track and fix in this bug tracker. On the other hand, I'm sympathetic and would like to point you in the right direction. You may have luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

Good luck! I hope this helps!
