### ISSUE TITLE
Error when using Remote to configure fullscreen from the frontend

### ISSUE THREAD

**Issue by ZaunSupremoXV** [electron/electron#27822]
I am trying to leave the application in fullscreen when clicking on a button. The electron is running a project in Vue JS. I get an error when importing the Electron Remote.

My code page Vue:

```
<template>
  <div class="home">
    <img alt="Vue logo" src="../assets/logo.png" />
    <HelloWorld msg="Welcome to Your Vue.js App" />
  </div>
</template>

<template>
  <button id="fullscreen" @click="fullscreen()">Full Screen</button>
</template>

<script>
// @ is an alias to /src
import HelloWorld from "@/components/HelloWorld.vue";
import { Remote } from 'electron';

export default {
  name: "Home",
  components: {
    HelloWorld,
  },
  methods: {
    fullscreen: function () {
      const button = document.getElementById("fullscreen");
      const win = Remote.getCurrentWindow();
      // Determine whether the current window is on full screen
      if (win.isFullScreen()) {
        win.setFullScreen(false);
        button.innerText = "Go full screen";
      } else {
        win.setFullScreen(true);
        button.innerText = "Exit full screen";
      }

      
    },
  },
};
</script>
```

### Screenshots

Error:

![Captura de Tela (229)](https://user-images.githubusercontent.com/67069017/108549255-a6f60280-72cb-11eb-8c60-91c9f6fbe57d.png)

### Additional Information
Vue version: 4.4.6
Electron: 11.0.0

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
