### ISSUE TITLE
Electron 10.1.1 and higher, including Electron 11.0.0, will not start on Enterprise Windows 10's 1809 and 1903 builds

### ISSUE THREAD

**Issue by AceAZhe** [electron/electron#27830]
electron的10.1.1版本以上包括electron 11.0.0版本在企业版window10的1809和1903上无法启动运行。
1. 基于http://www.electronjs.org/docs/tutorial/quick-start#prerequisites搭建项目：
2. 项目的package.json：

```
{
  "name": "my-electron-app",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "electron .",
    "dist": "electron-builder"
  },
  "build": {
    "appId": "com.example.yourapp",
    "asar": true,
    "afterPack": "./build/afterPack.js",
    "directories": {
      "buildResources": "build",
      "output": "dist"
    },
    "win": {
      "target": [
        {
          "target": "nsis"
        }
      ],
      "icon": "build/icon.ico",
      "asarUnpack": [
        "src/**",
        "README.md"
      ]
    },
    "nsis": {
      "oneClick": false,
      "allowElevation": true,
      "allowToChangeInstallationDirectory": true,
      "installerIcon": "build/icon.ico",
      "uninstallerIcon": "build/icon.ico",
      "createDesktopShortcut": true,
      "createStartMenuShortcut": true
    }
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "electron": "11.0.0",
    "electron-builder": "22.9.1",
    "electron-packager": "15.2.0",
    "electron-winstaller": "5.0.0"
  }
}
```

3. 文件/build/afterPack.js：

```
const fs = require("fs");
const path = require("path");
async function afterPack(context){
    // 删除 README 文件，使其不加入 Setup 包中。
    let readmePath = path.join(context.appOutDir,"resources/app.asar.unpacked/README.md");
    if(fs.existsSync(readmePath)){
        fs.unlinkSync(readmePath);
    }
}
module.exports = afterPack;
```

（1） 以下是这是在非企业版window10的1809和1903上启动的截图
![image](https://user-images.githubusercontent.com/37918142/108584108-91d7ad00-7379-11eb-9474-471fa559699f.png)
（2）以下是在企业版window10的1809和1903上启动的截图。
![image](https://user-images.githubusercontent.com/37918142/108584118-b3d12f80-7379-11eb-9319-b4a2c52780ef.png)
（3）将electron降到6.0.8上，其他不改动，在企业版window10的1809和1903上启动的可以正常运行。截图如下
` "devDependencies": {
    "electron": "6.0.8",
    "electron-builder": "22.9.1",
    "electron-packager": "15.2.0",
    "electron-winstaller": "5.0.0"
  }

![image](https://user-images.githubusercontent.com/37918142/108584173-2fcb7780-737a-11eb-81a0-29f724778712.png)

以下是electron11.0.0测试git源码地址
https://github.com/AceAZhe/electron11-0-0-test.git

**Comment by AceAZhe** [comment]
看源码electron-master\shell\browser\api\electron_api_web_contents.cc 中 存在这个
auto weak_this = GetWeakPtr();
if (!weak_this)
    return;
什么情况会造成!weak_this的条件满足？

**Comment by ckerr** [comment]
I've changed the subject from the original text,

> electron的10.1.1版本以上包括electron 11.0.0版本在企业版window10的1809和1903上无法启动运行

to an English equivalent to make triage easier for the Electron team.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
