### ISSUE TITLE
Incorrect types and documentation for ProtocolRequest

### ISSUE THREAD

**Issue by 6XGate** [electron/electron#27834]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * `11.3.0`
* **Operating System:**
  * Ubuntu 20.04

### Expected Behavior

The documentation and type definitions would be correct.

### Actual Behavior

Documentation for [ProtocolRequest](https://www.electronjs.org/docs/api/structures/protocol-request) and its type definition in `electron.d.ts` incorrectly type the `uploadData` member as `undefined|UploadData[]`. Based on clean room testing requests send to callbacks in the `registerXXXScheme` set of function; it would appear it is actually `undefined(UploadData|UploadFile|UploadBlob|UploadRawData)[]`. Also, it would seem `type` is not documented for `UploadData`, if it is meant to be there.

Also to help with identifying which is being sent and facilitate type narrowing; the type fields should be typed as string literals, ex for `UploadRawData` should be
```ts
  interface UploadRawData {

    // Docs: https://electronjs.org/docs/api/structures/upload-raw-data

    /**
     * Content being sent.
     */
    bytes: Buffer;
    /**
     * `rawData`.
     */
    type: "rawData";
  }
```

### To Reproduce

- Register a custom protocol handler with the `protocol` object.
- Log any request that is sent to the console.
- Send a POST request with JSON data to the faux end-point with the `fetch` API.

### Screenshots

```
  uploadData: [
    {
      type: 'rawData',
      bytes: <Buffer 7b 22 64 61 74 61 22 3a 22 64 61 74 61 22 7d>
    }
  ]
```

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by 6XGate** [comment]
Need to check
