### ISSUE TITLE
OnNoMemory

### ISSUE THREAD

**Issue by zhaoxiaolei519109457** [electron/electron#27852]
### Preflight Checklist

*  I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
*  I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
*  I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.8
* **Operating System:**
  *  Windows 6.1.7601(Service Pack 1)

### Additional Information
base::`anonymous namespace'::OnNoMemory(memory_win.cc:52)
malloc(allocator_shim_override_ucrt_symbols_win.h:53)
v8::internal::AllocWithRetry(allocation.cc:119)
v8::internal::AccountingAllocator::GetSegment(accounting-allocator.cc:77)
v8::internal::Zone::NewExpand(zone.cc:157)
std::deque<T>::push_back(deque:1541)
v8::internal::compiler::LoopFinderImpl::PropagateForward(loop-analysis.cc:310)
v8::internal::compiler::LoopFinder::BuildLoopTree(loop-analysis.cc:520)
v8::internal::compiler::LoopPeelingPhase::Run(pipeline.cc:1277)
v8::internal::compiler::PipelineImpl::Run<T>(pipeline.cc:1009)
v8::internal::compiler::PipelineImpl::OptimizeGraph(pipeline.cc:1983)
v8::internal::compiler::PipelineCompilationJob::ExecuteJobImpl(pipeline.cc:955)

I have been struggling with this problem for a long time. I hope the author can give me some ideas or debugging steps. I want to solve this problem based on the existing version. Looking forward to the author's reply

**Comment by MarshallOfSound** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/tutorial/support#supported-versions), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.
