### ISSUE TITLE
BrowserWindow 'maximize' and 'unmaximize' events not firing when calling maximize()/unmaximize() with thickFrame: false

### ISSUE THREAD

**Issue by markleutloff** [electron/electron#27851]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.3.0
  * 12.0.0-beta.27
* **Operating System:**
  * Windows 10

### Expected Behavior
maximize and unmaximize events should be fired.

### Actual Behavior
maximize and unmaximize events are not fired.

### To Reproduce
Gist: https://gist.github.com/2b3846eb9e357acb8137efe5ee6d0a52

Create a window with thickFrame set to false and attach event listeners to "maximize" and "unmaxmize", then call window.maximize() dns window.unmaximize()

 ```
const mainWindow = new BrowserWindow({
  thickFrame: false
})

mainWindow.on("maximize", () => console.log("maximized"));
mainWindow.on("unmaximize", () => console.log("unmaximized"));

setInterval(() => {
  if (mainWindow.isMaximized())
    mainWindow.unmaximize();
  else
    mainWindow.maximize();
}, 2000);
```

**Comment by Liupeng8** [comment]
have the same issue

**Comment by suedama1756** [comment]
I believe this is related to this issue: https://github.com/electron/electron/issues/27838 as electron is not properly calling the the win32 API showWindow which in turn not fire the event.

**Comment by adel-sbeh** [comment]
Yup, the window events are kinda messed up on Windows... https://github.com/electron/electron/issues/26076

**Comment by codebytere** [comment]
cc @mlaurencin

**Comment by kochelmonster** [comment]
I have the same issue, with a frameless BrowserWindow, but in Linux/Gnome.
electron version: 12.0.1

**Comment by mlaurencin** [comment]
Hi @markleutloff [this PR](https://github.com/electron/electron/pull/28207) may have fixed your issue. Can you try upgrading to either version 11.4.3 or 12.0.3 and see if you the events are firing for you now?

**Comment by kochelmonster** [comment]
Tried it out with Linux/Gnome
version 12.0.5: No maximize/unmaximize events.
version 11.4.3: maximize/unmaximize events are send.

**Comment by markleutloff** [comment]
@mlaurencin Thank you, I did test it with 11.4.3, 12.0.3 and 12.0.5, all fired the events for me. Tested on my Win10 machine.

**Comment by mlaurencin** [comment]
@markleutloff  Great to hear. 

@kochelmonster  Since you are experiencing this issue on a different version number and OS than was originally reported, could you open a new issue with your specific situation? This can ensure that the right things are being tested, and allow other maintainers to understand the situation more clearly.

I will close this issue for now, but if someone is still experiencing this on Windows 10, even after testing the versions in [this comment](https://github.com/electron/electron/issues/27851#issuecomment-825307165), then it may be considered for reopening.
