### ISSUE TITLE
how to open an another applicaton use the electron?

### ISSUE THREAD

**Issue by watermelon-brother** [electron/electron#27878]
I want to open the APP Store in my electron application, automatic input the username and password ,How do I get there？

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
