### ISSUE TITLE
The force-fieldtrials command line swtich does not work.

### ISSUE THREAD

**Issue by saghul** [electron/electron#27877]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.3.0 / 12.0.0-beta28
* **Operating System:**
  * macOS 10.15.7
* **Last Known Working Electron version:**
  * None

### Expected Behavior

Chrome supports the `--force-fieldrials` commadn line switch in order to force certain field trials. Passing them as follows should work: `app.commandLine.appendSwitch('force-fieldtrials', 'WebRTC-Audio-Red-For-Opus/Enabled/');`

### Actual Behavior

This doesn't seem to work in Electron. The field trial is not activated.

### To Reproduce

Check the following fiddle: https://gist.github.com/saghul/a11bc277523e55d0401c7ca4b418483d it should print true.

This can be verified by launching Chrome with `--force-fieldtrials=WebRTC-Audio-Red-For-Opus/Enabled/` and checking the output of `RTCRtpReceiver.getCapabilities("audio").codecs` - it should contain an item with `mimeType` set to `audio/red`.

### Screenshots

N/A

### Additional Information

https://github.com/electron/electron/issues/25529 and https://github.com/electron/electron/issues/13731 reported the same problem, but they are closed with no way to validate if Electron is behaving correctly. The fiddle in this issue allows to validate if field trials are properly processed.

**Comment by nornagon** [comment]
Hm, it looks like WebRTC doesn't use the base::Feature system, only base::FieldTrials. That's unfortunate.

Here's where WebRTC checks the field trial: https://source.chromium.org/chromium/chromium/src/+/master:third_party/webrtc/media/engine/webrtc_voice_engine.cc;l=260;drc=56d4a9a9deb30be73adcee8737c73bcb2a5ab64f

**Comment by saghul** [comment]
Thanks for taking a look! Does that mean that some extra work is needed in Electron to pass those field trials to Chromium?

**Comment by codebytere** [comment]
@saghul yep - we currently only support `base::Feature`, the code for which can be found [here](https://github.com/electron/electron/blob/4588a411610ee4095ab2a47e086f23fa4730e50e/shell/browser/feature_list.cc#L20-L51)

**Comment by saghul** [comment]
Gave this a try at https://github.com/electron/electron/pull/28305 My C++ is not great, can someone take a quick look to see if I'm going in the right direction? It does work with the fiddle, which is encouraging :-)

**Comment by LEBATRUNG** [comment]
Tkanhs
