### ISSUE TITLE
TS definitions of NativeImage static methods are wrong. (Please reopen #22167)

### ISSUE THREAD

**Issue by dperetti** [electron/electron#27885]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 8.0.0+
* **Operating System:**
  * any
* **Last Known Working Electron version:**
  * (not sure)

### Expected Behavior
```js
import { NativeImage } from 'electron'
const nativeImage = NativeImage.createFromPath(imagePath)
```
**Type checking should warn that NativeImage in undefined.**

### Discussion
In `electron.d.ts`, `createFromPath` and other methods are defined as static methods of `NativeImage`, but the exported module is `nativeImage`, not `NativeImage`. 

Typescript is probably confused with this:
<img width="297" alt="image" src="https://user-images.githubusercontent.com/845612/74332226-95fbe280-4d95-11ea-8226-de65f454a11f.png">

The workaround is currently to:
```js
import { nativeImage as NativeImage } from 'electron'
```

PLEASE CHECK DISCUSSION of #22167.

The original issue was definitely closed by mistake.

**Comment by VerteDinde** [comment]
@dperetti Reopened the original issue, so I'm closing this one if that's alright 🙂 Thanks for the catch!
