### ISSUE TITLE
Electron apps stop redrawing

### ISSUE THREAD

**Issue by richvdh** [electron/electron#27889]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.2.3
* **Operating System:**
  * Ubuntu 20.04 x64 
* **Last Known Working Electron version:**
  * 10.4.0 (I think?)

### Actual Behavior

Sometimes, when resizing a window for an electron app, it seems to get stuck in a state where it is not being redrawn. See the following screenshot, which is the result of dragging a "hello world" application around in front of an electron-fiddle window:

![Screenshot_2021-02-24](https://user-images.githubusercontent.com/1389908/108991061-8513cb80-768f-11eb-922c-9f0a4b89b652.png)

To be clear: this is **not** a transient effect during the resize: no redraws happen to this window until I resize it again. Resizing the window a bit more wakes it up and normality is restored.

While the window is in this state, I can interact with the application as normal, if I can guess where the controls are - I just can't see them!

Some applications seem more prone to this problem than others. The electron-fiddle app is awful; VSCode and [element-desktop](https://github.com/vector-im/element-web/issues/15869) also suffer. The "Hello world" app supplied with electron-fiddle suffers rarely, but as per the screenshot, still fails occasionally. (This leads me to speculate that the problem may be related to the amount of work being done by the app during the redraw.)

### To Reproduce

While this is easy to reproduce on my system, I'm not aware of any foolproof ways of reproducing it elsewhere :/

### Additional Information

I imagine my desktop environment is somehow relevant, though I've tried a few things in an attempt to pin this down:
 * both Ubuntu 18.04LTS and 20.04LTS
 * both XFCE/XFWM and GNOME3/Mutter

**Comment by thraizz** [comment]
Same for me under Arch Linux with Gnome, electron version is v11.3.0 and kernel is 5.10.16-arch1-1. Xorg and Wayland both produce this. VSCode and GitKraken are unusable at the moment for me

**Comment by ckerr** [comment]
Hard to know how to move forward on this, since it's not something that happens consistently and, if it's happening in VSC and Fiddle and Hello World, probably not dependent on a particular code path in the client application.

Since you're using Fiddle already, any chance you could bisect through the Electron versions and see if there's a particular release where this behavior first appears? Maybe that would give a clearer path on how to move this issue forward.

**Comment by richvdh** [comment]
The difficulty I have here is that it's quite hard to reproduce with the simple "hello world" app, so it's hard to be certain that the behavior *doesn't* occur on any given Electron version. It's much easier to reproduce on a more complex app like VSCode or Fiddle itself.

What I could try is building Fiddle itself against a variety of Electron versions, if that would be helpful.

**Comment by richvdh** [comment]
So, I built Fiddle with a range of electron versions. I found that electron@10.4.0 was fine, while electron@11.0.0-beta.1 was not - so this seems to have been introduced with Electron 11.

Is there anything I can do to narrow this down further?

**Comment by richvdh** [comment]
Huh; for completeness, I tried testing with Electron 12 and 13 - I can't reproduce it there. So it may be that my bug only affects the Electron 11 series...

**Comment by nornagon** [comment]
@richvdh you could use the Bisect feature of [Electron Fiddle](/electron/fiddle) to try to narrow down where it was fixed. Be sure to enable Nightly versions in the preferences (under the Electron tab)

**Comment by richvdh** [comment]
@nornagon sorry, I'm not that familiar with some of this tooling, so I could use a bit of help here.

I've using the Fiddle app itself to test with because I can't reliably reproduce the bug with a simple "Hello World" app. Can you give me any pointers for getting Fiddle set up to build a non-trivial application, so that I can use its bisect feature?

**Comment by richvdh** [comment]
to confirm: I've not had any problems with apps based on Electron 12, so this seems to be limited to Electron 11.

**Comment by nornagon** [comment]
Great, glad to hear it's fixed in Electron 12.

Electron 11 is now accepting security fixes only, so I'm going to close this out.

**Comment by ell1e** [comment]
I'm seeing this in what appears to be Electron 30.3.1 using Phosh 0.39.0 and Phoc 0.39.0 which I think is a wlroots-based compositor, when using the DeltaChat Desktop App. Would therefore recommend you reopen.

Screenshots:

![](https://private-user-images.githubusercontent.com/64124388/375761771-3027b2e6-2b22-4115-b632-d78b33abc1ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMzY0MjQsIm5iZiI6MTcyOTEzNjEyNCwicGF0aCI6Ii82NDEyNDM4OC8zNzU3NjE3NzEtMzAyN2IyZTYtMmIyMi00MTE1LWI2MzItZDc4YjMzYWJjMWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDAzMzUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4YzM5MzU0MzRmYjQ2NzE4Yjc1ZWQyMjkwZGI1MDI3ZDk3MzI5MzNkODhmNDZiYjQ3MjQzMTkwNDllOGY4ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UmWxuB9nhOX80YCjebCjok1HM9i0TXhKRaeQrVZkscw)

![](https://private-user-images.githubusercontent.com/64124388/375761974-577acdab-740c-4390-be3a-234057c2e8e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMzY0MjQsIm5iZiI6MTcyOTEzNjEyNCwicGF0aCI6Ii82NDEyNDM4OC8zNzU3NjE5NzQtNTc3YWNkYWItNzQwYy00MzkwLWJlM2EtMjM0MDU3YzJlOGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDAzMzUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNzI1Mjc1M2RjMDNmMGZlNjdjNWQyNDQ5NWViODE3ZDcxNWJmNzRlZDcwMTkyNjAxZDE4NTM1Y2I1NGRhMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.z9f8z5Yn2q0cu1linYc5aFOVxqd0lnmFbCvSK_D8A0w)
