### ISSUE TITLE
net.request is losing custom headers from webRequest

### ISSUE THREAD

**Issue by themadtitanmathos** [electron/electron#27894]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
10.1.7
* **Operating System:**
Windows 10 Enterprise 1909

When making a request with `net.request`, I can see (and modify) the headers received in `electron.session.defaultSession.webRequest.onHeadersReceived`.

```
electron.session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
  details.responseHeaders['my-custom-header'] = 'my-custom-value';
  callback({ responseHeaders: details.responseHeaders });
});
```

But by the time the `net.request` `request.on('response')` handler receives the headers, my custom header is gone.

```
request.on('response', (response) => {
  /* 
  response.headers === {
    // no my-custom-header present
  };
  */
});
```

I haven't tested if this is an issue in all types of responses, but I can tell you this is occurring without fail for the case when the `response.statusCode === 200`, but the `response.headers.status === 304`.

### Expected Behavior
For `net.request` response handler to receive the same headers that are shipped out by `webRequest.onHeadersReceived` handler.

### Actual Behavior
`net.request` response handler is receiving what seems to be a cached set of headers (or something?), which do not match what is sent out in `webRequest.onHeadersReceived`.

### To Reproduce
1. Find/get a response from an API where the `statusCode` of the response is `200`, but the headers.status is `304`.

2. Modify the `headers` in `webRequest.onHeadersReceived`.

3. Observe the `headers` received by `net.request` response handler are completely different.

**Comment by codebytere** [comment]
Closing with no follow up.

**Comment by themadtitanmathos** [comment]
@codebytere This will still be reachable by people looking at #27895 right? It seems very closely related.

**Comment by Mr-Wallet** [comment]
I suspect it's exactly the same problem, so multiple issues/repros are probably not necessary unless this persists after that issue is resolved.
