### ISSUE TITLE
mainWindow.webContents.print({silent:true}) doesn't work on Windows 10

### ISSUE THREAD

**Issue by rajan995** [electron/electron#27890]
mainWindow.webContents.print({silent:true}) 
not working silent printing 

async function createWindow () {
  // Define our main window size
  mainWindow = new BrowserWindow({
    height: 920,
    width: 1600,
    show: false,
  autoHideMenuBar:true,
    webPreferences: {
      nodeIntegration: true,
      preload: path.join(__dirname, 'node_modules', '@capacitor', 'electron', 'dist', 'electron-bridge.js'),
      nativeWindowOpen: true, 
      nodeIntegration: true,
    devTools:false,
    
    },
  
  });

I try following code but do not work 

1.
mainWindow.webContents.print({silent:true}) 

2 
let  getDefaultPrinter =  mainWindow.webContents.getPrinters().filter(x =>x.isDefault == true);
mainWindow.webContents.print({deviceName:getDefaultPrinter.deviceName,silent:true,printBackground:true,copies:2});

Please help

Thanks

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 5 days if the above is not addressed.

**Comment by ckerr** [comment]
@rajan995 specifically, please provide the information that was requested by the [issue template](https://github.com/electron/electron/tree/master/.github/ISSUE_TEMPLATE) that was presented when you first filled out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information.

Thanks for understanding and meeting us half way :grinning:

**Comment by rajan995** [comment]
Operating Syatem : Window 10
electron -v  : v11.3.0
Package.json in electron project :
{
  "name": "jaapudchakul",
  "version": "1.0.0",
  "description": "An Amazing Capacitor App",
  "main": "index.js",
  "scripts": {
    "electron:start": "electron ./"
  },
  "dependencies": {
    "@capacitor/electron": "^2.4.6",
    "electron-is-dev": "^1.1.0"
  },
  "devDependencies": {
    "electron": "^8.0.0"
  },
  "keywords": [
    "capacitor",
    "electron"
  ],
  "author": "",
  "license": "ISC"
}

Package.json in ionic project:
{
  "name": "jaapudchakul",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~10.0.0",
    "@angular/core": "~10.0.0",
    "@angular/fire": "^6.1.4",
    "@angular/forms": "~10.0.0",
    "@angular/platform-browser": "~10.0.0",
    "@angular/platform-browser-dynamic": "~10.0.0",
    "@angular/router": "~10.0.0",
    "@capacitor/core": "2.4.6",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.0.0",
    "@ngrx/store": "^10.1.2",
    "firebase": "^8.2.6",
    "lottie-web": "^5.7.6",
    "mqtt": "^4.2.6",
    "ngx-lottie": "^6.4.0",
    "ngx-webcam": "^0.3.2",
    "promptpay-qr": "^0.4.4",
    "qrcode": "^1.4.4",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "uuid": "^8.3.2",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.0",
    "@angular/cli": "~10.0.5",
    "@angular/compiler": "~10.0.0",
    "@angular/compiler-cli": "~10.0.0",
    "@angular/language-service": "~10.0.0",
    "@capacitor/cli": "2.4.6",
    "@ionic/angular-toolkit": "^2.3.0",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "electron-installer-windows": "^3.0.0",
    "electron-wix-msi": "^3.0.6",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.5"
  },
  "description": "An Ionic project"
}
![Capture](https://user-images.githubusercontent.com/30840037/109096722-10e72f80-7744-11eb-904e-97a6126017c9.PNG)


Please check thanks

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
