### ISSUE TITLE
electron autoUpdater  （old shortcut is not remove when productname changed  in windows platform）

### ISSUE THREAD

**Issue by accountOfAnqi** [electron/electron#27905]
electron version ： 5.0.8
platform：windows
description：
as we use electron autoUpdater，and modify productname and icon。
but after the client is updated，old shorcut is not removed，and create a new shorcut。
how to remove autolly  the old shorcut  in desktop？

**Comment by ckerr** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
