### ISSUE TITLE
[Feature Request]: Reduce app size by using an installed browser

### ISSUE THREAD

**Issue by gonsolo** [electron/electron#27904]
**Preflight Checklist**

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Problem Description**

I use Signal (https://github.com/signalapp) and the (for every update) download is 100MB and the installed size is 345MB.
This is insane.

**Proposed Solution**

The already installed browser could be used like this project did: https://github.com/pojala/electrino.
Is it possible to provide an option to remove the web engine, use the installed one, and load it only when necessary?

**Alternatives Considered**

The alternative is to do nothing. This is of course possible. But I think it would provide much value to shrink app sizes.

**Additional Information**

https://github.com/signalapp
https://github.com/pojala/electrino

**Comment by MarshallOfSound** [comment]
This as an idea goes against some of the use case for electron (a stable consistent browser engine) and also is not technically possible given electrons architecture and dependencies on Chromium and the //content layer
