### ISSUE TITLE
The WebGL environment of Electron 11 is unstable

### ISSUE THREAD

**Issue by VisualSJ** [electron/electron#27903]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 11.2.0
  * 
* **Operating System:** windows 7 | windows 10
  * 
* **Last Known Working Electron version:** 5.0.8
  * 

### Expected Behavior

WebGL works fine

### Actual Behavior

WebGL often gets lost

### Screenshots

![](https://forum.cocos.org/uploads/default/original/3X/4/3/43280a49e467d2285b546bb457eff0b64f952137.png)

### Additional Information

https://forum.cocos.org/t/topic/106515

We upgraded Electron to 11.2
A large number of users had problems
The WebGL environment is lost when switching scenarios

**Comment by pandamicro** [comment]
The WebGL Context is lost while failing compiling a couple of shaders, it work normal on same hardware environment with windows 10. The gl shader fails to compile because gl.createShader failed, it's not related to any specific shader, it could fail on any shader. It's often happening when switching scene because we compile shader during scene loading process

**Comment by VisualSJ** [comment]
@sofianguy Is this problem being followed up?
We continue to receive feedback that many people on the Windows platform are experiencing WebGL startup failures.

**Comment by kefeibuhuifei** [comment]
I have the same situation, but if you disable gpu or turn off hardware acceleration, webgl will not be lost.

**Comment by miniak** [comment]
Electron 11 is going to be unsupported soon. Please create a new report if you are still having this issue on Electron 12 or higher.
