### ISSUE TITLE
Webpack full-reloads cause blank screens in Electron >= v9

### ISSUE THREAD

**Issue by rathboma** [electron/electron#27919]
* **Electron Version:**
  * 9.x, and 11.x
* **Operating System:**
  * Mac, Ubuntu 20.04, Windows 8, and Windows 10

### Expected Behavior
- Webpack hard-reloads should work fine, it's using a http webpack server, not a file url (which I know has its own issues)

### Actual Behavior
- Webpack hard-reloads cause a blank screen and cause devtools to disconnect

### To Reproduce [outdated, see first comment]
1. Check out [Beekeeper Studio](https://github.com/beekeeper-studio/beekeeper-studio)
2. yarn install
3. yarn run electron:serve
4. Change `postgresql.ts`, just add a newline somewhere
5. Watch the app reload but not actually reload

### Screenshots
![screenshot](https://user-images.githubusercontent.com/279769/108582764-da9c5100-72fa-11eb-8515-11085c4bf205.gif)

**Comment by rathboma** [comment]
So after some more digging with the Vue community, this looks related to native modules. [1]

So this happens when:
- Node Integration is on
- Native modules are used

Here's a link to a minimal repo set up with Vue and electron builder that replicates the issue:
- https://github.com/rathboma/electron-hotreload-example

Replicating:
```bash
yarn install
yarn run electron:serve
# edit src/main.js and add a console.log

```
The page will now attempt a full-reload and fail.

This was created using:

```bash
vue create electron-example
cd electron-example
vue add electron-builder
yarn add sqlite3
```
Then I enabled native modules and added sqlite3 to main.js


[1]: https://github.com/nklayman/vue-cli-plugin-electron-builder/issues/1257

**Comment by rathboma** [comment]
@sofianguy please let me know if there's more information I can add to make this easier to debug. Happy to do some work here to fix this, but need some direction as I'm woefully unaware of Electron internals.

**Comment by nornagon** [comment]
> blank screen and cause devtools to disconnect

This sounds like a renderer-process crash. Can you try attaching `crashReporter` like so?


```js
const { crashReporter, app } = require('electron')
crashReporter.start({
  submitURL: '',
  uploadToServer: false
})
console.log(`Crash reports directory: ${app.getPath('crashDumps')}`)
```

then run your test and see if anything turns up in the crash reports directory?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
