### ISSUE TITLE
[Feature Request]:

### ISSUE THREAD

**Issue by Madscientist792** [electron/electron#27932]

**Comment by bsam1212** [comment]
From 5c595d0a2073bbb33c6470e76c5bb247aaf7f453 Mon Sep 17 00:00:00 2001
From: Julian Verdurmen <julian.verdurmen@outlook.com>
Date: Wed, 17 Feb 2021 23:06:32 +0100
Subject: [PATCH] Added support for record types in C#.

Records are added in C# 9 - see https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/exploration/records

Signed-off-by: Julian Verdurmen <julian.verdurmen@outlook.com>
---
 userdiff.c | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/userdiff.c b/userdiff.c
index 3f81a2261c5e9..2803683c3117a 100644
--- a/userdiff.c
+++ b/userdiff.c
@@ -212,7 +212,7 @@ PATTERNS("csharp",
 	 /* Properties */
 	 "^[ \t]*(((static|public|internal|private|protected|new|virtual|sealed|override|unsafe)[ \t]+)*[][<>@.~_[:alnum:]]+[ \t]+[@._[:alnum:]]+)[ \t]*$\n"
 	 /* Type definitions */
-	 "^[ \t]*(((static|public|internal|private|protected|new|unsafe|sealed|abstract|partial)[ \t]+)*(class|enum|interface|struct)[ \t]+.*)$\n"
+	 "^[ \t]*(((static|public|internal|private|protected|new|unsafe|sealed|abstract|partial)[ \t]+)*(class|enum|interface|struct|record)[ \t]+.*)$\n"
 	 /* Namespace */
 	 "^[ \t]*(namespace[ \t]+.*)$",
 	 /* -- */
