### ISSUE TITLE
Notification timeoutType ignored on Windows 7

### ISSUE THREAD

**Issue by Slapbox** [electron/electron#27934]
### Preflight Checklist
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 11.3.x
* **Operating System:**
  * Windows 7
* **Last Known Working Electron version:**
  * Unknown

### Expected Behavior
`timeoutType: 'never'` should result in the notification persisting

### Actual Behavior
Notificiation is cleared in less than 6 seconds.

### To Reproduce
```js
new remote.Notification({ title: 'hello', body: 'world', timeoutType: 'never', silent: true }).show()
```

**Comment by mlaurencin** [comment]
Hello @Slapbox  I am having a bit of trouble reproducing your issue with the code provided. I have been using this repro gist

**Comment by Slapbox** [comment]
Hey @mlaurencin thanks for your reply. 

You should be able to reproduce it with this repro Fiddle - https://gist.github.com/74089c1da6ab4f9d82132b14fe58a115 - _but_ I am able to reproduce it with your Fiddle too.

You're testing on Windows 7? I'm not sure what might be the source of the discrepancy in timeout behavior if so.

**Comment by Slapbox** [comment]
This issue persists at least through `Electron@20.3.x`.

@codebytere, I saw that you mentioned in #22192 that this was being worked on, but #25820 closes that issue and does not fix the issue on Windows 7.

**Comment by Slapbox** [comment]
Whoops forgot to mention, here's an updated repro: https://gist.github.com/4ab6040dc005d4ef35bd723b27f9406f

**Comment by miniak** [comment]
https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice

**Comment by Slapbox** [comment]
Thanks for the reminder to close this @miniak.
