### ISSUE TITLE
GPU crashed with exitCode: -1073741819

### ISSUE THREAD

**Issue by replace5** [electron/electron#27935]
When I use remote.app.on("child-process-gone", callback) capture the process crash info and send it to server, It collects a lot of GPU crash logs with exitCode: -1073741819。
Version:
     electron: 11.2.1
    chrome: 87.0.4280.141
    v8: 8.7.220.31-electron.0
    node: 12.18.3
AppMetrics(app.getAppMetrics() with formated): {"type":"Tab","pid":2036,"sandboxed":false,"integrityLevel":"high","cpuUsage":"0.00%","RAM":"92.74MB","peakRAM":"130.6MB","privateRAM":"63.07MB","lifetime":"0.28min"}
{"type":"Tab","pid":13524,"sandboxed":false,"integrityLevel":"high","cpuUsage":"0.60%","RAM":"106.74MB","peakRAM":"118.21MB","privateRAM":"73.13MB","lifetime":"5.66min"}
{"type":"Utility","pid":6232,"name":"Network Service","sandboxed":false,"integrityLevel":"high","cpuUsage":"0.08%","RAM":"27.14MB","peakRAM":"27.91MB","privateRAM":"14.17MB","lifetime":"5.66min"}
{"type":"Tab","pid":5152,"sandboxed":false,"integrityLevel":"high","cpuUsage":"0.00%","RAM":"85.55MB","peakRAM":"85.55MB","privateRAM":"76.19MB","lifetime":"0.03min"}
{"type":"Browser","pid":5372,"sandboxed":false,"integrityLevel":"high","cpuUsage":"0.52%","RAM":"75.6MB","peakRAM":"79.48MB","privateRAM":"44.11MB","lifetime":"5.67min"}
SystemInfo: 
    platform: win32
    arch: x64
    type: Windows_NT
    version: Windows 7 Professional Service Pack 1
    release: 6.1.7601
    username: Administrator
    homedir: C:\Users\Administrator
    cpus: Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz, Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz, Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz, Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
    cpuUsage: undefined
    memory: 
        total: 7.7GB
        free: 4.98GB

**Comment by codebytere** [comment]
We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

We will be able to more closely look at your issue once you do so. This issue will be closed in 5 days if the above is not addressed.

**Comment by ckerr** [comment]
Also, please note that [the remote module is deprecated](https://github.com/electron/electron/issues/21408), so if you're having an issue with your use of `remote` your best bet is to consider migrating. See [this code example](https://github.com/electron/electron/issues/21408#issuecomment-564184702) and [this blog post](https://medium.com/@nornagon/electrons-remote-module-considered-harmful-70d69500f31#d978) by @nornagon to see an example of replacement code for many uses of `remote`.

**Comment by codebytere** [comment]
Closing as there was no response to https://github.com/electron/electron/issues/27935#issuecomment-788625615

**Comment by mqliutie** [comment]
> We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.
> 
> We will be able to more closely look at your issue once you do so. This issue will be closed in 7 days if the above is not addressed.

This error is not easy to reproduce, it occurs susuddenly
