### ISSUE TITLE
Exit status 4294967295 when arguments like this

### ISSUE THREAD

**Issue by andy627** [electron/electron#27933]
when i start with arguments like this, electron couldn't start, and tips like:
```
yarn start auth_key:fafdsafds uid:4321432 extend:fdsk,v5
yarn run v1.22.10
$ electron . auth_key:fafdsafds uid:4321432 "extend:fdsk v5"
error Command failed with exit code 4294967295.
```

when i start whit argument like this, electron can start normal:
```
yarn start --auth_key:fafdsafds --uid:4321432 --extend:fdsk,v5
```

**Comment by MarshallOfSound** [comment]
The usage of an argument matching the pattern `.+:.*` is not allowed without a prefixed `--` for security reasons.

i.e. this would work

```
yarn start -- --auth_key:fafdsafds --uid:4321432 --extend:fdsk,v5
```
