### ISSUE TITLE
How can I parse the form-data send by crashReporter

### ISSUE THREAD

**Issue by cgy1314521** [electron/electron#27936]
Electron version: 11.3.0

I start crashReporter  with
`crashReporter.start({
      submitURL: 'http://localhost/api/application/crashReport',
      compress: true,
      uploadToServer: true,
      productName: 'App Test',
    });`

when I trigger process.crash(), I received the request。But when I try to parse the form-data send by crashReporter with formidable（I've tried many libraries），I got the same error：
<img width="569" alt="image" src="https://user-images.githubusercontent.com/19278170/109471968-80df1800-7aac-11eb-9c74-5d73163ea6a6.png">

I checked the Crashpad folder, and sure .dmp file exists：
<img width="770" alt="image" src="https://user-images.githubusercontent.com/19278170/109472531-35793980-7aad-11eb-8174-616ca21ad55c.png">

what should I do to parse the crash reports？

**Comment by MarshallOfSound** [comment]
Using `compress: true` means the request body will be gzip encoded, you'll have to decompress before parsing the body as form data.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
