### ISSUE TITLE
[Feature Request]: support HEVC/H.265 codec

### ISSUE THREAD

**Issue by kaatt** [electron/electron#27943]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Electron doesn't play videos that are encoded in HEVC.

### Proposed Solution

Add support for HEVC videos natively.

### Alternatives Considered

https://github.com/AAAhs/electron-hevc is a fork that supports it

**Comment by nornagon** [comment]
We can only support what Chrome supports, unfortunately. It looks like the fork you linked includes a 5,000+-line patch, which is far larger than we can reasonably consider including in mainline.

**Comment by kaatt** [comment]
is there an alternative i can use to add support that doesn't involve using a forked electron version?

and is it possible that you can add a dependency to ffmpeg/something so you won't have to deal with big patches?

**Comment by aza547** [comment]
It seems chrome now supports this as of Sept 2022. https://bitmovin.com/google-adds-hevc-support-chrome/

What does that means for electron? Will it be supported one day?

Thanks

**Comment by chienweiluo** [comment]
I am facing the same issue. Could we support HEVC or any workarounds now?
