### ISSUE TITLE
Windows system is set to zoom, setBounds or setPosition method  will be problems.

### ISSUE THREAD

**Issue by zshuaia** [electron/electron#27959]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.1.3
* **Operating System:**
  * Windows(1903)
* **Last Known Working Electron version:**
  * 11

### Expected Behavior

My needs are:
Create a new ToolsBar window, Transparent and no frame. You can slide along the X-axis, but you're not allowed to slide along the Y-axis.
So, I listened for 'will-move' events

```js
    let toolbarWindow;
    toolbarWindow = new BrowserWindow({
      width: width,
      minWidth: width,
      maxWidth: width,
      maxHeight: height,
      minHeight: height,
      height: height,
      frame: false,
      transparent: true,
      resizable: false,
})

    toolbarWindow.on("will-move", (event, newBounds)=>{
      event.preventDefault();

      let bounds = screen.screenToDipPoint(newBounds);

      // toolbarWindow.setPosition(newBounds.x, 0);
      /**
       * You can't use `setPosition` here.
       * You Must use the `setBounds` and you must have `width` and `height` parameters, 
       * because on Windows OS: it's affected by system zoom, causes the window to automatically grow larger
       * 
       *  >> 
       */
      toolbarWindow.setBounds({ x: newBounds.x, width, height})
)}
```

You can't use `setPosition` here.
You Must use the `setBounds` and you must have `width` and `height` parameters, because on Windows OS: it's affected by system zoom, causes the window to automatically grow larger.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If you're still experiencing this issue in Electron 9.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
