### ISSUE TITLE
First Get Request of my app results in Cross-Origin Read Blocking or CORS error. After closing and opening, the get request goes through successfully.

### ISSUE THREAD

**Issue by ryankashi** [electron/electron#27955]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.2.0
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
I boot up my computer, open my electron app, and conduct a get request. In turn receive a response from the requested servers.

### Actual Behavior
I instead receive "Cross-Origin Read Blocking (CORB) blocked cross-origin response <my_url such as https://twitch.tv> with MIME type text/html.

After closing my app and reopening, this request will then work successfully.

### To Reproduce

I use Axios to conduct my get requests. I turn off my computer, turn it back on, then start up the developer version of my Electron app using npm start (I am using electron-forge). Next, in the console I enter:

`response = await axios.get('https://twitch.tv/')`

Which will then return me the error message. When I close and start back up my application, however, this call will be successful.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If you're still experiencing this issue in Electron 9.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by ryankashi** [comment]
Upgraded to version 9.4.3 and I am still receiving the issue

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
