### ISSUE TITLE
Cannot get basic app in Quick Start Guide to work. process is not defined error.

### ISSUE THREAD

**Issue by NoelSMartin** [electron/electron#27957]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
v12.0.0 
* **Operating System:**
Windows 10 Enterprise
* **Last Known Working Electron version:**
None

### Expected Behavior
        We are using node <script>document.write(process.versions.node)</script>,
        Chrome <script>document.write(process.versions.chrome)</script>,
        and Electron <script>document.write(process.versions.electron)</script>.

### Actual Behavior
We are using node , Chrome , and Electron .

### To Reproduce
npm init -y
npm i --save electron
Copy and paste code from Quick Start Guide into main.js and index.html
npm start

And receive the following errors with my app starts

Uncaught ReferenceError: process is not defined
    at index.html:11
index.html:12 Uncaught ReferenceError: process is not defined
    at index.html:12
index.html:13 Uncaught ReferenceError: process is not defined
    at index.html:13

package.json
{
  "name": "mea",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "electron": "^12.0.0"
  }
}

main.js
const { app, BrowserWindow } = require('electron')

function createWindow () {
  const win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
        nodeIntegration: true,
        nodeIntegrationInWorker: true,
        enableRemoteModule: true
    }
  })

  win.loadFile('index.html')
}

app.whenReady().then(createWindow)

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow()
  }
})

index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
    <meta http-equiv="Content-Security-Policy" content="script-src 'self' 'unsafe-inline';" />
</head>
<body style="background: white;">
    <h1>Hello World!</h1>
    <p>
        We are using node <script>document.write(process.versions.node)</script>,
        Chrome <script>document.write(process.versions.chrome)</script>,
        and Electron <script>document.write(process.versions.electron)</script>.
    </p>
</body>
</html>

![image](https://user-images.githubusercontent.com/79912980/109645311-a9364780-7b7c-11eb-991e-f970818388de.png)

**Comment by nornagon** [comment]
Ah, looks like the example needs to be updated. The default of `contextIsolation` has switched from `false` to `true` in Electron 12. #27970 should fix this example. Also, [electron-quick-start](/electron/electron-quick-start) is generally the best way to start out!

**Comment by RaynerLim** [comment]
How is it you just close this. There should be a solution that works with nodeIntegration set to false and contextIsolation set to false. It cant be documentation states in generate this is for security reason yet on start of learn tell us just ignore it. I cannot do so as I am in process on learning to take on a project which many end up having componets linked to third party sites and thus I may need the added security yet now I been stuck for 2 days trying to figure this out

**Comment by martpie** [comment]
I'd like to weigh in here, I'm migrating a decently complex app to be more secure, but the fact it is not possible to migrate each flag `nodeIntegration`/`contextIsolation` / `sandbox` separately makes it a real pain.

If it's not possible to enable one without disable the other, shouldn't these be one single flag?
