### ISSUE TITLE
Uncaught ReferenceError: require is not defined when using version 12.*

### ISSUE THREAD

**Issue by dima-g7** [electron/electron#27964]
### Preflight Checklist

* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 12.0.0
* **Operating System:**
  * MacOS 10.15,7
* **Last Known Working Electron version:**
  * 9.04

### Expected Behavior
I should not get error when call `require`

### Actual Behavior
Uncaught ReferenceError: require is not defined

### To Reproduce
1. Create a js file and use require there.  `const fs = require('fs')`;
2. In index html, link the source file `<script async src=myfile.js>`
3. In main.js, 
```
set webPreferences: {
      nodeIntegration: true
}
```

NOTE: Once switched to 9.04, everything works as expected

**Comment by ckerr** [comment]
So, under a typical electron-quick-start, having a renderer.js of:

```
// This file is required by the index.html file and will
// be executed in the renderer process for that window.
// All of the Node.js APIs are available in this process.
const fs = require('fs');
```

Is silent all the way up through v12.0.0-beta.31 but is broken in v12.0.0 :roll_eyes:

**Comment by ckerr** [comment]
@dima-g7 this is related to the changing of the default value of `contextIsolation` as  described in https://www.electronjs.org/docs/breaking-changes#planned-breaking-api-changes-120. In the short term, you can get up & running again by explicitly setting contextIsolation to false in webPreference as per https://www.electronjs.org/docs/tutorial/context-isolation .

I'm not certain that's the entire story though? Even https://www.electronjs.org/docs/tutorial/context-isolation#migration shows the "After: With context isolation enabled" code snippet using require(), so leaving this issue open for the moment.

**Comment by ckerr** [comment]
> I'm not certain that's the entire story though? Even https://www.electronjs.org/docs/tutorial/context-isolation#migration shows the "After: With context isolation enabled" code snippet using require(), so leaving this issue open for the moment.

Oh of course, I see what's going on -- this is being loaded in renderer rather than preload.js. Yes, this is intentional because contextIsolation is going to block access to Node.js. If you want to expose Node.js to arbitrary scripts, turn off context isolation. But more useful would be to move this code into the preload script and then just selectively expose wrapped functionality to mitigate against any rogue code from gaining access to Node.

**Comment by dima-g7** [comment]
@ckerr Thanks for the prompt response. Could you please point me to an example of` preload script` you mentioned above?
