### ISSUE TITLE
v12.0.0 - Wayland backend not showing application

### ISSUE THREAD

**Issue by mb-karo** [electron/electron#27979]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 12.0.0
* **Operating System:**
  * Custom Yocto built Linux xwayland Distro with Weston Desktop on ARM64 i.MX8M Mini Processor
* **Last Known Working Electron version:**
  * none before with wayland backend
  * just working with X11 backend

### Expected Behavior
Starting Chromium/electron App on Wayland Backend with success - supporting GPU.

### Actual Behavior
Application starts, can view application via Remote Debugger, but not on device's display.

Log output:

```
[     1] Failed EGL API GetProcAddress: eglLockSurfaceKHR !
[     2] Failed EGL API GetProcAddress: eglUnlockSurfaceKHR !
[     3] Failed EGL API GetProcAddress: eglBindWaylandDisplayWL !
[     4] Failed EGL API GetProcAddress: eglUnbindWaylandDisplayWL !
[     5] Failed EGL API GetProcAddress: eglQueryWaylandBufferWL !
[     6] Failed EGL API GetProcAddress: eglUpdateWaylandBufferWL !
[     7] Failed EGL API GetProcAddress: eglSetDamageRegionKHR !
[     8] Failed EGL API GetProcAddress: eglSwapBuffersWithDamageEXT !
[     9] Failed EGL API GetProcAddress: eglQueryDmaBufFormatsEXT !
[    10] Failed EGL API GetProcAddress: eglQueryDmaBufModifiersEXT !
[    11] Failed EGL API GetProcAddress: eglPatchID !
[    12] Failed ES_Common API GetProcAddress: forward_glActiveTexture !                        
[    13] Failed ES_Common API GetProcAddress: forward_glBindBuffer !
[    14] Failed ES_Common API GetProcAddress: forward_glBindTexture !
[    15] Failed ES_Common API GetProcAddress: forward_glBlendFunc !
[    16] Failed ES_Common API GetProcAddress: forward_glBufferData !
[    17] Failed ES_Common API GetProcAddress: forward_glBufferSubData !
[    18] Failed ES_Common API GetProcAddress: forward_glClear !
[    19] Failed ES_Common API GetProcAddress: forward_glClearColor !
[    20] Failed ES_Common API GetProcAddress: forward_glClearDepthf !
[    21] Failed ES_Common API GetProcAddress: forward_glClearStencil !
[    22] Failed ES_Common API GetProcAddress: forward_glColorMask !
[    23] Failed ES_Common API GetProcAddress: forward_glCompressedTexImage2D !
[    24] Failed ES_Common API GetProcAddress: forward_glCompressedTexSubImage2D !
[    25] Failed ES_Common API GetProcAddress: forward_glCopyTexImage2D !
[    26] Failed ES_Common API GetProcAddress: forward_glCopyTexSubImage2D !
[    27] Failed ES_Common API GetProcAddress: forward_glCullFace !
[    28] Failed ES_Common API GetProcAddress: forward_glDeleteBuffers !
[    29] Failed ES_Common API GetProcAddress: forward_glDeleteTextures !
[    30] Failed ES_Common API GetProcAddress: forward_glDepthFunc !
[    31] Failed ES_Common API GetProcAddress: forward_glDepthMask !
[    32] Failed ES_Common API GetProcAddress: forward_glDepthRangef !
[    33] Failed ES_Common API GetProcAddress: forward_glDisable !
[    34] Failed ES_Common API GetProcAddress: forward_glDrawArrays !
[    35] Failed ES_Common API GetProcAddress: forward_glDrawElements !
[    36] Failed ES_Common API GetProcAddress: forward_glEnable !
[    37] Failed ES_Common API GetProcAddress: forward_glFinish !
[    38] Failed ES_Common API GetProcAddress: forward_glFlush !                                
[    39] Failed ES_Common API GetProcAddress: forward_glFrontFace !
[    40] Failed ES_Common API GetProcAddress: forward_glGenBuffers !
[    41] Failed ES_Common API GetProcAddress: forward_glGenTextures !
[    42] Failed ES_Common API GetProcAddress: forward_glGetBooleanv !
[    43] Failed ES_Common API GetProcAddress: forward_glGetBufferParameteriv !
[    44] Failed ES_Common API GetProcAddress: forward_glGetError !
[    45] Failed ES_Common API GetProcAddress: forward_glGetFloatv !
[    46] Failed ES_Common API GetProcAddress: forward_glGetIntegerv !
[    47] Failed ES_Common API GetProcAddress: forward_glGetPointerv !
[    48] Failed ES_Common API GetProcAddress: forward_glGetString !
[    49] Failed ES_Common API GetProcAddress: forward_glGetTexParameterfv !
[    50] Failed ES_Common API GetProcAddress: forward_glGetTexParameteriv !
[    51] Failed ES_Common API GetProcAddress: forward_glHint !
[    52] Failed ES_Common API GetProcAddress: forward_glIsBuffer !
[    53] Failed ES_Common API GetProcAddress: forward_glIsEnabled !
[    54] Failed ES_Common API GetProcAddress: forward_glIsTexture !
[    55] Failed ES_Common API GetProcAddress: forward_glLineWidth !
[    56] Failed ES_Common API GetProcAddress: forward_glPixelStorei !
[    57] Failed ES_Common API GetProcAddress: forward_glPolygonOffset !
[    58] Failed ES_Common API GetProcAddress: forward_glReadPixels !
[    59] Failed ES_Common API GetProcAddress: forward_glSampleCoverage !
[    60] Failed ES_Common API GetProcAddress: forward_glScissor !
[    61] Failed ES_Common API GetProcAddress: forward_glStencilFunc !
[    62] Failed ES_Common API GetProcAddress: forward_glStencilMask !
[    63] Failed ES_Common API GetProcAddress: forward_glStencilOp !
[    64] Failed ES_Common API GetProcAddress: forward_glTexImage2D !                            
[    65] Failed ES_Common API GetProcAddress: forward_glTexParameterf !
[    66] Failed ES_Common API GetProcAddress: forward_glTexParameterfv !
[    67] Failed ES_Common API GetProcAddress: forward_glTexParameteri !
[    68] Failed ES_Common API GetProcAddress: forward_glTexParameteriv !
[    69] Failed ES_Common API GetProcAddress: forward_glTexSubImage2D !
[    70] Failed ES_Common API GetProcAddress: forward_glViewport !
[    71] Failed ES_Common API GetProcAddress: forward_glMapBufferOES !
[    72] Failed ES_Common API GetProcAddress: forward_glUnmapBufferOES !
[    73] Failed ES_Common API GetProcAddress: forward_glEGLImageTargetTexture2DOES !
[    74] Failed ES_Common API GetProcAddress: forward_glEGLImageTargetRenderbufferStorageOES !
[    75] Failed ES_Common API GetProcAddress: forward_glMultiDrawArraysEXT !
[    76] Failed ES_Common API GetProcAddress: forward_glMultiDrawElementsEXT !
[    77] Failed ES_Common API GetProcAddress: forward_glTexDirectVIV !
[    78] Failed ES_Common API GetProcAddress: forward_glTexDirectInvalidateVIV !
[    79] Failed ES_Common API GetProcAddress: forward_glTexDirectVIVMap !
[    80] Failed ES_Common API GetProcAddress: forward_glTexDirectTiledMapVIV !
[    81] Failed GLES32 API GetProcAddress: glMultiDrawArraysEXT !
[    82] Failed GLES32 API GetProcAddress: glMultiDrawElementsEXT !
[    83] Failed GLES32 API GetProcAddress: glTexDirectVIV !
[    84] Failed GLES32 API GetProcAddress: glTexDirectInvalidateVIV !
[    85] Failed GLES32 API GetProcAddress: glTexDirectVIVMap !
[    86] Failed GLES32 API GetProcAddress: glTexDirectTiledMapVIV !
[    87] Failed GLES32 API GetProcAddress: glMultiDrawArraysIndirectEXT !
[    88] Failed GLES32 API GetProcAddress: glMultiDrawElementsIndirectEXT !
[    89] Failed GLES32 API GetProcAddress: glGetTexImage !
[    90] Failed ES Common GLES2X API GetProcAddress: glMultiDrawArraysEXT !

EGL: Warning: No default display support on wayland
```

### To Reproduce

`electron main.js --no-sandbox --enable-features=UseOzonePlatform --ozone-platform=wayland`

### Screenshots
\-

### Additional Information

Already tried some things:

* Setting `XDG_RUNTIME_DIR` or `WAYLAND_DISPLAY` environment variable - no success.
* Adding `--in-process-gpu` to Electron start parameters - Getting a white screen and app is not displayed.

Not sure if this is an issue with electron or chromium on i.MX8.

Thanks for any help!

**Comment by PRGWITHSTYLE** [comment]
I'm still experiencing this issue with electron 25.9.4, does anyone have a workaround for this issue?

**Comment by PRGWITHSTYLE** [comment]
Custom Yocto built Linux Distro based on Fedora on ARM64 i.MX8M Processor

**Comment by mb-karo** [comment]
Have you tried with

_"start": "electron . --no-sandbox --ozone-platform=wayland --ignore-gpu-blacklist --in-process-gpu --enable-accelerated-video-decode"_

in _package.json_ ?

**Comment by PRGWITHSTYLE** [comment]
./hello-world-linux-electron-                                                                     app --no-sandbox --ozone-platform=wayland --ignore-gpu-blacklist --in-process-gp                                                                     u --enable-accelerated-video-decode
[     1] Failed EGL API GetProcAddress: eglBindWaylandDisplayWL !
[     2] Failed EGL API GetProcAddress: eglUnbindWaylandDisplayWL !
[     3] Failed EGL API GetProcAddress: eglQueryWaylandBufferWL !
[     4] Failed EGL API GetProcAddress: eglUpdateWaylandBufferWL !
[     5] Failed EGL API GetProcAddress: eglQueryDevicesEXT !
[     6] Failed EGL API GetProcAddress: eglSwapBuffersWithDamageEXT !
[     7] Failed EGL API GetProcAddress: eglPatchID !
[     8] Failed ES_Common API GetProcAddress: forward_glActiveTexture !
[     9] Failed ES_Common API GetProcAddress: forward_glBindBuffer !
[    10] Failed ES_Common API GetProcAddress: forward_glBindTexture !
[    11] Failed ES_Common API GetProcAddress: forward_glBlendFunc !
[    12] Failed ES_Common API GetProcAddress: forward_glBufferData !
[    13] Failed ES_Common API GetProcAddress: forward_glBufferSubData !
[    14] Failed ES_Common API GetProcAddress: forward_glClear !
[    15] Failed ES_Common API GetProcAddress: forward_glClearColor !
[    16] Failed ES_Common API GetProcAddress: forward_glClearDepthf !
[    17] Failed ES_Common API GetProcAddress: forward_glClearStencil !
[    18] Failed ES_Common API GetProcAddress: forward_glColorMask !
[    19] Failed ES_Common API GetProcAddress: forward_glCompressedTexImage2D !
[    20] Failed ES_Common API GetProcAddress: forward_glCompressedTexSubImage2D                                                                      !
[    21] Failed ES_Common API GetProcAddress: forward_glCopyTexImage2D !
[    22] Failed ES_Common API GetProcAddress: forward_glCopyTexSubImage2D !
[    23] Failed ES_Common API GetProcAddress: forward_glCullFace !
[    24] Failed ES_Common API GetProcAddress: forward_glDeleteBuffers !
[    25] Failed ES_Common API GetProcAddress: forward_glDeleteTextures !
[    26] Failed ES_Common API GetProcAddress: forward_glDepthFunc !
[    27] Failed ES_Common API GetProcAddress: forward_glDepthMask !
[    28] Failed ES_Common API GetProcAddress: forward_glDepthRangef !
[    29] Failed ES_Common API GetProcAddress: forward_glDisable !
[    30] Failed ES_Common API GetProcAddress: forward_glDrawArrays !
[    31] Failed ES_Common API GetProcAddress: forward_glDrawElements !
[    32] Failed ES_Common API GetProcAddress: forward_glEnable !
[    33] Failed ES_Common API GetProcAddress: forward_glFinish !
[    34] Failed ES_Common API GetProcAddress: forward_glFlush !
[    35] Failed ES_Common API GetProcAddress: forward_glFrontFace !
[    36] Failed ES_Common API GetProcAddress: forward_glGenBuffers !
[    37] Failed ES_Common API GetProcAddress: forward_glGenTextures !
[    38] Failed ES_Common API GetProcAddress: forward_glGetBooleanv !
[    39] Failed ES_Common API GetProcAddress: forward_glGetBufferParameteriv !
[    40] Failed ES_Common API GetProcAddress: forward_glGetError !
[    41] Failed ES_Common API GetProcAddress: forward_glGetFloatv !
[    42] Failed ES_Common API GetProcAddress: forward_glGetIntegerv !
[    43] Failed ES_Common API GetProcAddress: forward_glGetPointerv !
[    44] Failed ES_Common API GetProcAddress: forward_glGetString !
[    45] Failed ES_Common API GetProcAddress: forward_glGetTexParameterfv !
[    46] Failed ES_Common API GetProcAddress: forward_glGetTexParameteriv !
[    47] Failed ES_Common API GetProcAddress: forward_glHint !
[    48] Failed ES_Common API GetProcAddress: forward_glIsBuffer !
[    49] Failed ES_Common API GetProcAddress: forward_glIsEnabled !
[    50] Failed ES_Common API GetProcAddress: forward_glIsTexture !
[    51] Failed ES_Common API GetProcAddress: forward_glLineWidth !
[    52] Failed ES_Common API GetProcAddress: forward_glPixelStorei !
[    53] Failed ES_Common API GetProcAddress: forward_glPolygonOffset !
[    54] Failed ES_Common API GetProcAddress: forward_glReadPixels !
[    55] Failed ES_Common API GetProcAddress: forward_glSampleCoverage !
[    56] Failed ES_Common API GetProcAddress: forward_glScissor !
[    57] Failed ES_Common API GetProcAddress: forward_glStencilFunc !
[    58] Failed ES_Common API GetProcAddress: forward_glStencilMask !
[    59] Failed ES_Common API GetProcAddress: forward_glStencilOp !
[    60] Failed ES_Common API GetProcAddress: forward_glTexImage2D !
[    61] Failed ES_Common API GetProcAddress: forward_glTexParameterf !
[    62] Failed ES_Common API GetProcAddress: forward_glTexParameterfv !
[    63] Failed ES_Common API GetProcAddress: forward_glTexParameteri !
[    64] Failed ES_Common API GetProcAddress: forward_glTexParameteriv !
[    65] Failed ES_Common API GetProcAddress: forward_glTexSubImage2D !
[    66] Failed ES_Common API GetProcAddress: forward_glViewport !
[    67] Failed ES_Common API GetProcAddress: forward_glMapBufferOES !
[    68] Failed ES_Common API GetProcAddress: forward_glUnmapBufferOES !
[    69] Failed ES_Common API GetProcAddress: forward_glEGLImageTargetTexture2DO                                                                     ES !
[    70] Failed ES_Common API GetProcAddress: forward_glEGLImageTargetRenderbuff                                                                     erStorageOES !
[    71] Failed ES_Common API GetProcAddress: forward_glMultiDrawArraysEXT !
[    72] Failed ES_Common API GetProcAddress: forward_glMultiDrawElementsEXT !
[    73] Failed ES_Common API GetProcAddress: forward_glTexDirectVIV !
[    74] Failed ES_Common API GetProcAddress: forward_glTexDirectInvalidateVIV !
[    75] Failed ES_Common API GetProcAddress: forward_glTexDirectVIVMap !
[    76] Failed ES_Common API GetProcAddress: forward_glTexDirectTiledMapVIV !
[    77] Failed GLES32 API GetProcAddress: glMultiDrawArraysEXT !
[    78] Failed GLES32 API GetProcAddress: glMultiDrawElementsEXT !
[    79] Failed GLES32 API GetProcAddress: glTexDirectVIV !
[    80] Failed GLES32 API GetProcAddress: glTexDirectInvalidateVIV !
[    81] Failed GLES32 API GetProcAddress: glTexDirectVIVMap !
[    82] Failed GLES32 API GetProcAddress: glTexDirectTiledMapVIV !
[    83] Failed GLES32 API GetProcAddress: glGetTexImage !
[    84] Failed ES Common GLES2X API GetProcAddress: glMultiDrawArraysEXT !
[43350:1110/101524.670942:ERROR:object_proxy.cc(590)] Failed to call method: org                                                                     .freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop:                                                                      org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desk                                                                     top was not provided by any .service files
lTexDirectTiledMapVIV !
[    83] Failed GLES32 API GetProcAddress: glGetTexImage !
[    84] Failed ES Common GLES2X API GetProcAddress: glMultiDrawArraysEXT !
[43350:1110/101524.670942:ERROR:object_proxy.cc(590)] Failed to call method: org                                                                     .freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop:                                                                      org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desk                                                                     top was not provided by any .service files
lTexDirectTiledMapVIV !
[    83] Failed GLES32 API GetProcAddress: glGetTexImage !
[    84] Failed ES Common GLES2X API GetProcAddress: glMultiDrawArraysEXT !
[43350:1110/101524.670942:ERROR:object_proxy.cc(590)] Failed to call method: org                                                                     .freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop:                                                                      org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desk                                                                     top was not provided by any .service files
: forward_glEGLImageTargetTexture2DO                                                                     ES !
[    70] Failed ES_Common API GetProcAddress: forward_glEGLImageTargetRenderbuff                                                                     erStorageOES !
[    71] Failed ES_Common API GetProcAddress: forward_glMultiDrawArraysEXT !
[    72] Failed ES_Common API GetProcAddress: forward_glMultiDrawElementsEXT !
[    73] Failed ES_Common API GetProcAddress: forward_glTexDirectVIV !
[    74] Failed ES_Common API GetProcAddress: forward_glTexDirectInvalidateVIV !
[    75] Failed ES_Common API GetProcAddress: forward_glTexDirectVIVMap !
[    76] Failed ES_Common API GetProcAddress: forward_glTexDirectTiledMapVIV !
[    77] Failed GLES32 API GetProcAddress: glMultiDrawArraysEXT !
[    78] Failed GLES32 API GetProcAddress: glMultiDrawElementsEXT !
[    79] Failed GLES32 API GetProcAddress: glTexDirectVIV !
[    80] Failed GLES32 API GetProcAddress: glTexDirectInvalidateVIV !
[    81] Failed GLES32 API GetProcAddress: glTexDirectVIVMap !
[    82] Failed GLES32 API GetProcAddress: glTexDirectTiledMapVIV !
[    83] Failed GLES32 API GetProcAddress: glGetTexImage !
[    84] Failed ES Common GLES2X API GetProcAddress: glMultiDrawArraysEXT !
[43350:1110/101524.670942:ERROR:object_proxy.cc(590)] Failed to call method: org                                                                     .freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop:                                                                      org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desk                                                                     top was not provided by any .service files
lTexDirectTiledMapVIV !
: forward_glEGLImageTargetTexture2DO                                                                     ES !
[    70] Failed ES_Common API GetProcAddress: forward_glEGLImageTargetRenderbuff                                                                     erStorageOES !
[    71] Failed ES_Common API GetProcAddress: forward_glMultiDrawArraysEXT !
[    72] Failed ES_Common API GetProcAddress: forward_glMultiDrawElementsEXT !
[    73] Failed ES_Common API GetProcAddress: forward_glTexDirectVIV !
[    74] Failed ES_Common API GetProcAddress: forward_glTexDirectInvalidateVIV !
[    75] Failed ES_Common API GetProcAddress: forward_glTexDirectVIVMap !
[    76] Failed ES_Common API GetProcAddress: forward_glTexDirectTiledMapVIV !
[    77] Failed GLES32 API GetProcAddress: glMultiDrawArraysEXT !
[    78] Failed GLES32 API GetProcAddress: glMultiDrawElementsEXT !
[    79] Failed GLES32 API GetProcAddress: glTexDirectVIV !
[    80] Failed GLES32 API GetProcAddress: glTexDirectInvalidateVIV !
[    81] Failed GLE

**Comment by PRGWITHSTYLE** [comment]
I tried it and it still seems to be crashing for some reason

**Comment by PRGWITHSTYLE** [comment]
I have discovered a workaround for the issue with 25.9.4, used this set of commands ./electron-app --ozone-platform=wayland --disable-features=WaylandFractionalScaleV1 --disable-gpu
