### ISSUE TITLE
install on x86_64 Raspian Desktop fails 

### ISSUE THREAD

**Issue by sdetweil** [electron/electron#27972]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
*  8.5.5.  and 11.3.0
  * 
* **Operating System:**  
  * 
* **Last Known Working Electron version:**
  * 

### To Reproduce
install raspian x86 on some intel hardware, 
https://www.raspberrypi.org/software/raspberry-pi-desktop/

install MagicMirror 
https://github.com/MichMich/MagicMirror

git clone
npm install 
boom

install error message
```
Official Linux/ia32 support is deprecated.
For more info: https://electronjs.org/blog/linux-32bit-support
Segmentation fault
```
node_modules/electron folder is not created

uname -a 
Linux raspberry 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

```
grep flags /proc/cpuinfo | grep " lm "
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm pti ssbd ibrs ibpb stibp tsc_adjust arat md_clear flush_l1d arch_capabilities
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm pti ssbd ibrs ibpb stibp tsc_adjust arat md_clear flush_l1d arch_capabilities
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm pti ssbd ibrs ibpb stibp tsc_adjust arat md_clear flush_l1d arch_capabilities
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm pti ssbd ibrs ibpb stibp tsc_adjust arat md_clear flush_l1d arch_capabilities
```

**Comment by ckerr** [comment]
Hard to say without more information, but if we're never even reaching the point where electron is starting, this bug report probably belongs in whatever's installing Electron rather than in `electron/electron`'s bug tracker.

The "Official Linux/ia32 support is deprecated" warning comes from [`electron/get`](https://github.com/electron/get/blob/master/src/index.ts#L91), so you might get more traction there, but it's likely that whatever script is calling electron/get is what's really crashing.

@electron/wg-ecosystem where should this bug report be routed to?

**Comment by ckerr** [comment]
@sdetweil this is what I got back from wg-ecosystem:

> I suspect this person is using a 32-bit Node.js. By default @electron/get uses process.arch & process.platform, which are compiled in values
￼
So my advice is to check & confirm that you're using 64-bit Node. If the problem persists with 64-bit node, please re-file this issue to `electron/get`. Thank you!
