### ISSUE TITLE
screen.getAllDisplays() function returns "false data" on HiDPI screen resolutions

### ISSUE THREAD

**Issue by Draginfable** [electron/electron#27978]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 12.0.0
* **Operating System:**
  * macOS 11.2.1 (Big Sur)
* **Last Known Working Electron version:**
  * This issue is reproducible for versions >=9, probably older ones too

### Expected Behavior
screen.getAllDisplays() function returns the displays with correct data. Original height and width along with the scale factor.
eg. width: 896, height: 560, scaleFactor: 2

### Actual Behavior
screen.getAllDisplays() function returns the displays with "false data". Height and width have the scale factor applied.
eg. width: 1792, height: 1120, scaleFactor: 2

### To Reproduce
In order to reproduce you need a mac that supports HiDPI resolutions. If the OS is Catalina you can choose between resolutions. In my case on Big Sur the options are predefined and all of them are HiDPI with a scaleFactor of 2. To change your resolution go to System Preferences > Displays.

I have prepared a small example that prints the output of screen.getAllDisplays(). I hope it helps.
https://github.com/Draginfable/Electron-samples/tree/electron12-hidpi-mac

```sh
git clone https://github.com/Draginfable/Electron-samples.git -b electron12-hidpi-mac
cd Electron-samples
npm i
```

### Screenshots
![Screenshot 2021-03-03 at 12 08 10 PM](https://user-images.githubusercontent.com/22166661/109791046-b4d84b80-7c1a-11eb-9bcf-e103a5b6251a.png)

### Additional Information
I have noticed this problem on our application that implements screen control. In normal screen resolutions everything works fine. In HiDPI though due to the fact that height and width are not the original values (without scaling applied) every movement is doubled again as the scaleFactor is applied once more.

In the screenshot I have shared, you can see that mac indicates that the screen resolution "Looks like 1792x1120" which is the resolution returned by the function as well. However, this resolution has the scaling already applied.

**Comment by Draginfable** [comment]
I have also tested this on electron 13.1.1 and macOS 11.3.1 and the problem still exists.

Here is the example: 
https://github.com/Draginfable/Electron-samples/tree/electron13-hidpi-mac

```sh
git clone https://github.com/Draginfable/Electron-samples.git -b electron13-hidpi-mac
cd Electron-samples
npm i
```

**Comment by nornagon** [comment]
We are directly reporting the values provided by the underlying APIs in Chromium, so I think this is working as intended. The values aren't "false", they're reporting the size of the pixel buffer, as opposed to the physical size. You'll have to account for this in your app.

**Comment by Draginfable** [comment]
The problem seems to be that on HiDPI screens it does not report the correct size. It reports the actual size. If I connect an external screen everything works fine. 

Take this screen for example, which is not HiDPI. The actual screen resolution is 1920x1080 and the scaling to 1.25

```
{
   ...
    bounds: { x: 0, y: 0, width: 1536, height: 864 },
    workArea: { x: 0, y: 0, width: 1536, height: 864 },
    colorDepth: 24,
    depthPerComponent: 8,
    size: { width: 1536, height: 864 },
    workAreaSize: { width: 1536, height: 864 },
    scaleFactor: 1.25,
    ...
}
```

As you see it reports 1536 x 864 as expected.

**Comment by nornagon** [comment]
Hm, perhaps we also need to expose [sizeInPixels](https://source.chromium.org/chromium/chromium/src/+/main:ui/display/display.h;l=203;drc=eed0b26b8bdcf59bf1c6b572cb8b42ca905f3b82)?
