### ISSUE TITLE
Unable to read files from asar after 10+ hours of runtime

### ISSUE THREAD

**Issue by zarubond** [electron/electron#27982]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
11.2.3, 11.2.3, 11.3.0
* **Operating System:**
Windows 10
* **Last Known Working Electron version:**
8.5.5

### Expected Behavior
Electron should correctly load resource from asar with file protocol.

### Actual Behavior
After some runtime any file you try to load from asar fails to load with net::ERR_FILE_NOT_FOUND

### To Reproduce
Run the Electron for 10+ hours and from time to time try to read file from asar. After some time will start getting errors net::ERR_FILE_NOT_FOUND on all files.

**Comment by MarshallOfSound** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by giancarlokc** [comment]
We started to see something similar on our electron app (v11). The issue seems to happen after running the app for a few minutes. We are working on a `electron-quickstart` reproduction.

**Comment by zarubond** [comment]
@MarshallOfSound  @ckerr  I have been debugging the code and here is what I found: 

The problem happens in https://github.com/electron/electron/blob/11-x-y/shell/common/asar/archive.cc where in he constructor Archive::Archive the method file_.Initialize return false. The reason why it returns false is that in file https://github.com/chromium/chromium/blob/87.0.4264.1/base/files/memory_mapped_file_win.cc inside method MemoryMappedFile::MapFileRegionToMemory a Windows function ::MapViewOfFile is called and it returns NULL or it just fails to mmap the file.

This feature was introduced in Electron 11 with https://github.com/electron/electron/pull/24470 @nornagon 

My best guess is that it is failing because it runs out of memory/handlers because in asar_util.cc there is a global variable g_archive_map_tls which creates a new instance of Archive for every thread, which seems to be happening quite often from what I have seen in debugger.

You can test this problem on Skype insiders on Windows https://www.skype.com/en/insider/ . You just need to log in, let it run for about 10hours, and then you can observe in settings menu that icons are missing which is a sign that Skype is not able to load them from asar. Unfortunately Skype is using private build of Electron so public symbols will not work, but I can send you correct one of you are Microsoft employee.

**Comment by stewartlord** [comment]
@zarubond Nice work! We've started to zero in on that mmap code as well. For what it's worth we are only seeing the issue on Windows builds. With our usage the problem occurs within about 10 minutes. If we can get a tight reproduction we will share it here.

**Comment by cschear** [comment]
We also just got bit by this one. You can see the javascript file failed to load after using the app for a short amount of time. Once this happens all requests for files under the asar path fail until you restart the application.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/1541940/110725397-c4d0cc00-81d4-11eb-9ab9-f327c144fc7c.png)

**Comment by nornagon** [comment]
Would love to get this fixed properly w/ mmap working, but in the meantime #28137 reverts the offending commit.

**Comment by knaos** [comment]
I am experiencing this problem only on 32 bit version of the app on Windows 10 32 bit. Electron version: **11.1.1**

**Comment by stewartlord** [comment]
@knaos If you update to v11.4.1 the problem should be resolved 👍

**Comment by knaos** [comment]
@stewartlord Thank you! This fixes the problem!
