### ISSUE TITLE
Uncaught Illegal access error in circumstances of #27457

### ISSUE THREAD

**Issue by Patronics** [electron/electron#27995]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
This issue is closely related to #27457, which seems to have been partially, but not entirely fixed by #27582. Specifically, the renderer no longer entirely hangs as it used to, but still reports the error `Uncaught illegal access`, and this prevents the execution of some of the asynchronous scripts on the page.
* **Electron Version:**
  * Any version that's recieved the partial fix of #27582, including the 12.0.0 release, the 13.0.0 nightly releases, and the current master branch of 10.x and 11.x. The issue in its original, worse, form affects every other version of electron from 9.x on.
* **Operating System:**
  * Verified on MacOS 10.14.6, 10.15.7, 11.2, and on Linux Debian 4.19.160-2, and Debian 5.9.15
  
* **Last Known Working Electron version:**
  * Electron 8.5.5 did not experience this issue. 

### Expected Behavior

The app runs normally.
### Actual Behavior

The app runs, but reports `Uncaught illegal access` on line 1 of the html page it's loading, and some script execution stops, such as receiving messages from node-ipc.
### To Reproduce

The [original bug's example repo](https://github.com/Patronics/example-electron-hang) has been updated to use the new releases of electron, and to better demonstrate the current issue. It also demonstrates the error message in the console. The comments in index.html describe which lines are specifically related to the bug, and which are just to better demonstrate its effects.

### Screenshots

The screenshot in #27457 may still be relevant, but the current version of the issue only outputs the error `Uncaught illegal access` on line 1, without a similar stack trace
### Additional Information

To clarify, commit #27582 did not 'cause' this issue per se, but did not fully fix the issue either.

**Comment by codebytere** [comment]
Here's a simpler reproducible sample: https://gist.github.com/04e984266d625f94b3a46b6ffd91e212
