### ISSUE TITLE
Namespace 'NodeJS' has no exported member 'Require'.

### ISSUE THREAD

**Issue by sun293529884** [electron/electron#27996]
## I build my project with Angular 11
Error: Error: node_modules/electron/electron.d.ts:6594:21 - error TS2694: Namespace 'NodeJS' has no exported member 'Require'.
![image](https://user-images.githubusercontent.com/10268233/109921999-ad3aa480-7cf7-11eb-8a07-0d2cbcd3b1f1.png)

![image](https://user-images.githubusercontent.com/10268233/109922093-d3604480-7cf7-11eb-93d0-47e4a82601e7.png)

## Package Info
    - "electron": "^12.0.0"
    - "typescript": "~4.1.5"
    - "@angular/cli": "~11.2.3"

## When I rollback the to "electron": "^11.3.0" will be build successfully.

**Comment by MarshallOfSound** [comment]
What version of `@types/node` do you depend on?

**Comment by juanrgm** [comment]
`Require` interface is available from `@types/node: ^13.0.0` , previosly it was named `NodeRequire`.

**Comment by sun293529884** [comment]
> What version of `@types/node` do you depend on?

 My type node:   "@types/node": "^12.20.4"

**Comment by MarshallOfSound** [comment]
Electron 12 uses node 14, so you should update your `@types/node` dependency 👍
