### ISSUE TITLE
[Feature Request]: add crashReporter.addGlobalExtraParameter() similar to addExtraParameter, but for all processes

### ISSUE THREAD

**Issue by dko-slapdash** [electron/electron#27990]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

The docs say that crashReporter.addExtraParameter() does it only for the current process, which is a little inconvenient: e.g. I have user_id parameter which I want to be included in ALL crash dumps (including all process types like utility, gpu-process etc.), but I can't do that, because user_id becomes known only at a later stage, when crashReporter is already initialized, and the page is rendered (it actually comes from inside the renderer).

### Proposed Solution

Add crashReporter.addGlobalExtraParameter() which modifies global parameters.

### Alternatives Considered

Currently I'm partially working it around by preserving user_id in a file in user's directory and then reading this file when crashReporter.start() is called. But it's a hack, and also it doesn't apply until the app is actually rebooted at least once with the user being logged in.

### Additional Information

https://www.electronjs.org/docs/api/crash-reporter#crashreporteraddextraparameterkey-value

**Comment by nornagon** [comment]
Unfortunately this isn't possible due to the design of crashpad. Global annotations can only be set when the crashpad process is booted.
