### ISSUE TITLE
installation stuck on reify:core-js: timing reifyNode:node_modules/lodash Complet

### ISSUE THREAD

**Issue by rismantrdr** [electron/electron#27997]
node v14.16.0
npm v7.6.0

I tried installing electrons several times with the command in the documentation ("npm i --save-dev electron"), but it always freezes on ("reify: core-js: timing reifyNode: node_modules / lodash Complete"),

![image](https://user-images.githubusercontent.com/68155110/109925308-2a641a80-7cf4-11eb-8257-43400c97c3e8.png)

**Comment by MarshallOfSound** [comment]
This sounds like an issue with `npm` not with Electron itself.  You should follow their bug reporting procedure.

**Comment by ffrmns** [comment]
firstly I also face this issue with node v10, then trying with node v16 and it succeed in about 5 minutes.
