### ISSUE TITLE
[Feature Request]: [Electron 12] Turn off high-contrast

### ISSUE THREAD

**Issue by AxelTerizaki** [electron/electron#28000]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

I'd like to know if it's possible to disable the high-contrast rendering of the pages in the rendered window.

I suppose it's a new chromium feature...

To sum it up, I have to use different windows colors for my eyes on Windows as the dark mode there is fairly incomplete and thus unusable for visually impaired people. I've built my app with accessibility in mind already and it's fairly contrasted in that regard by design. However, since Electron 12, the rendered pages are forced to use the Windows high-contrast, which ruins usability on my app and make it a headache to dev for since I can't see which real colors are being used in the UI.

And I don't see myself returning to normal colors on Windows as it'll be highly uncomfortable for me (my eyesight is sensitive to large patches of light.)

### Proposed Solution

Add a boolean to switch high contrast mode off regardless of system preferences.

### Alternatives Considered

A command-line flag would probably work as well, if there's one.

### Additional Information

I searched through chromium's command line flags but there's only one to force to enable the high contrast mode, not disable it (unless I've missed it?)

Thanks in advance for your help, because this is really frustrating as a disabled dev and user when these things are forced on me.

**Comment by VerteDinde** [comment]
Hey @AxelTerizaki, thanks for requesting this! If it's no trouble, would it be possible for you to make a small repro of this issue for us, preferably in Electron Fiddle? Having a repro to work from saves us a lot of time asking for clarifications and lets us fix and test the issue much more quickly - the Fiddle would also let us switch easily between versions of Electron like 11 and 12 and more clearly see what you're seeing.

No worries if no, I understand that's now always possible. Thanks!

**Comment by AxelTerizaki** [comment]
@VerteDinde thanks for letting me know about Electron Fiddle, it made a lot of things easier on how to explain the issue I have.

So first things first, you need to enable high contrast mode in Windows in the accessibility panel. Open the configuration panel and type in "high contrast" in the search bar to find it easily.

Here it's disabled (sorry, screenshots are in french)

![ApplicationFrameHost_61MCSCymcu](https://user-images.githubusercontent.com/4531597/110087543-17a12280-7d94-11eb-9823-2ea3d04c8ccd.png)

Here it's enabled : 

![ApplicationFrameHost_88NNVmBOxr](https://user-images.githubusercontent.com/4531597/110087569-1e2f9a00-7d94-11eb-8851-fdeb5ca06060.png)

Note that visually impaired people on Windows don't use the dark mode because contrary to macOS, W10's dark mode doesn't extend to all apps, especially those who still use win32 APIs. Usually they'll use the high contrast mode.

So I tried out Electron Fiddle and didn't make any modifications on the Hello world project.

Thanks to the many versions available and how easy it was to switch between them I was able to pinpoint that **this behavior started with version 12.0.0 beta 27**.

Launching the Hello World app with Electron < 12.0.0-beta27 gives us a normal looking Hello World page :

![electron_WPphcmgLo0](https://user-images.githubusercontent.com/4531597/110087986-9b5b0f00-7d94-11eb-8763-46a324eb8601.png)

Starting it with any version above 12.0.0-beta26 gives this :

![electron_D4pG5s09Qb](https://user-images.githubusercontent.com/4531597/110088063-ae6ddf00-7d94-11eb-9e84-45800d1cc96a.png)

Looking through the release notes for beta 27, I suppose the culprit is `Updated Chromium to 89.0.4389.47.`

I'd like to know how we could disable this behavior (using chromium's high contrast mode) on demand, via some kind of boolean for example.

Any app should look usable in high contrast mode but depending on how the app is built it can render things worse actually, as it strips many items on screen of color for example. Some visually impaired people might like this better, but others do not, especially when an app already has a high-contrast friendly theme. Moreso, it makes development more difficult for those using the system's high contrast mode as we can't see anymore how the app really looks like without disabling it beforehand.

I hope I made my explanation clear ^^

I wasn't sure if I had to make it a bug or a feature request, though. Maybe it should be considered a bug ?

Thanks in advance for your help!

**Comment by VerteDinde** [comment]
@AxelTerizaki Wow, thanks for the detailed repro and for taking the time to step through the different versions of Electron, this is very helpful! 

I've added this issue to our 13-x-y beta project board - since it does look like it regressed with the Chromium upgrade, a fix may take a little time, but we'll see if we can find a fix similar to what you suggested. Thanks again for taking the time to report this and provide such detailed feedback, it helps us out a lot 🙇‍♀️

**Comment by Kilian** [comment]
@AxelTerizaki Workaround: while it would be good to support forced colors, you can turn them off by setting `forced-colors-adjust: none` on the html or body. More info at MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/forced-color-adjust

We already have support for detecting windows high contrast mode: https://www.electronjs.org/docs/api/native-theme#nativethemeshouldusehighcontrastcolors-macos-windows-readonly

Chromium recently got support for `forced-colors` (which responds to windows high contrast mode) due to work done by the Edge team. What I think happens here is that Chromium sets all the colors to forced colors internally, but after that Electron sets the windows background color (to the default white). A flag to turn it off makes sense to me, but ideally Electron internal would also work well with high contrast by default (in this case, setting the expected black background)

**Comment by AxelTerizaki** [comment]
@Kilian Sorry for replying so late, life has been busy. :)

I've finally got to test your idea, and it indeed worked on Electron 13 at least. 

```CSS
* {
	forced-color-adjust: none;
}
```

So I don't know if this issue is still relevant as a result. People might want to be aware of this trick though because it's not immediately obvious that you need to do this.

I'll leave it up to the devs to decide if this issue should be considered as resolved or not.

**Comment by nornagon** [comment]
@AxelTerizaki glad you found a workaround! It does seem like we should be setting the default background color according to the system's theme. Given there's a CSS-based way to achieve the result you wanted, I'm going to close this issue. I've opened a new issue to track the wrong background-color: https://github.com/electron/electron/issues/29853

**Comment by craxal** [comment]
I also used `forced-color-adjust` seems to work fine in regular browser windows, but it doesn't seem to work in embedded webviews.
