### ISSUE TITLE
Incorrect "Mixed Content" error when changing image URL to a non-secure `src`

### ISSUE THREAD

**Issue by davej** [electron/electron#28001]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 11.2.3
* **Operating System:** macOS 10.15.7

### Expected Behavior

It should be possible to change an image URL `src` attribute to a non-secure `src`. This currently works in Chrome with no flags needed, see here: https://codepen.io/DaveJ/pen/abBKQba

### Actual Behavior

If I load the same URL in Electron then I get a mixed content warning and the image appears as broken. Even adding the following options to `BrowserWindow` **doesn't** fix the issue:
```js
webPreferences: {
  allowRunningInsecureContent: true,
  webSecurity: false,
}
```

### To Reproduce

https://gist.github.com/davej/fb0cdfd906ed3710d5426d970a856284

### Screenshots

![image](https://user-images.githubusercontent.com/26971/109954820-b0269c80-7cd9-11eb-9184-fa374de5f452.png)

**Comment by ckerr** [comment]
Confirmed using v11.2.3 on Ubuntu 20.04:

> Mixed Content: The page at 'https://codepen.io/' was loaded over HTTPS, but requested an insecure image 'http://res.cloudinary.com/djp21wtxm/image/upload/v1608721831/qkz03ayywyjlpqss545o.png'. This request has been blocked; the content must be served over HTTPS.

However, FWIW @davej you may want to consider using the newer Electron 12 for this. When I run the testcase there (and also in a 13 beta) I get this instead:

> Mixed Content: The page at 'https://cdpn.io/DaveJ/fullpage/abBKQba' was loaded over HTTPS, but requested an insecure element 'http://res.cloudinary.com/djp21wtxm/image/upload/v1608721831/qkz03ayywyjlpqss545o.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html

**Comment by davej** [comment]
Thanks @ckerr. I'm happy for this issue to be closed. I don't think it's an important enough issue to be backported.
