### ISSUE TITLE
[Feature Request]: Add vendors versions to dist package

### ISSUE THREAD

**Issue by cawa-93** [electron/electron#28006]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Working with some bundlers or transpiles I can set the exact target version of Chrome and Node environment.

But to do this you need get the exact versions of the vendors libraries from the currently installed electron. At the moment it is possible only in runtime `proccess.versions` and it is not possible to get in build scripts or elsewhere. 

### Proposed Solution

I propose to introduce a separate simple function that would return an object with versions of vendors. For example: 
```js
const { getVendors } = require('electron')
getVendors() // {"node":"14.16.0","v8":"9.0.85-electron.0","chrome":"90.0.4402.0" ... } 
```

Alternatively, at the build stage, you can add a file with all vendors to the source package. For example: 
```js
const vendors = require('electron/vendors.json')
vendors  // {"node":"14.16.0","v8":"9.0.85-electron.0","chrome":"90.0.4402.0" ... } 
```

### Alternatives Considered

I try [electron-releases](https://www.npmjs.com/package/electron-releases). However, because the new version of the electron comes out faster than the updated electron-releases, it often breaks the CD pipeline. 

Also I try request data from `https://electronjs.org/headers/index.json`, However, this greatly increases the build time. In addition, it is quite difficult to integrate the execution of some asynchronous operations and transfer the result of their execution to transpiler config. 

I was looking for something like 'postupdate' hook in npm. But did not find. 

### Additional Information

Being able to get information about vendors from the currently installed electron would be extremely useful. Thank you.

**Comment by vladimiry** [comment]
> At the moment it is possible only in runtime proccess.versions and it is not possible to get in build scripts or elsewhere.

`ELECTRON_RUN_AS_NODE=1 npx electron -p "console.log(process.versions)"`

**Comment by cawa-93** [comment]
@vladimiry Wow. This is an interesting workaround. But with this there are some problems:
- It's still not as efficient as just load json file if it was in the package.
- It seems that it does not return the version of Chrome.

**Comment by BlackHole1** [comment]
I'll be submitting a PR for this feature one of these days

**Comment by BlackHole1** [comment]
@sofianguy @codebytere  request closed this issue.

see: https://github.com/electron/electron/pull/32853 discussion

**Comment by cawa-93** [comment]
> What's wrong with using `./node_modules/.bin/electron test.js` where `test.js` is
> 
> ```js
> console.log(process.versions);
> process.exit();
> ```
> 
> ? It doesn't take much time on my MBP:
> 
> ```js
> time ./node_modules/.bin/electron test.js
> {
>   node: '14.16.0',
>   v8: '9.1.269.40-electron.0',
>   uv: '1.40.0',
>   zlib: '1.2.11',
>   brotli: '1.0.9',
>   ares: '1.16.1',
>   modules: '89',
>   nghttp2: '1.41.0',
>   napi: '7',
>   llhttp: '2.1.3',
>   openssl: '1.1.1',
>   icu: '68.1',
>   unicode: '13.0',
>   electron: '13.6.9',
>   chrome: '91.0.4472.164'
> }
> ./node_modules/.bin/electron test.js  0.15s user 0.04s system 91% cpu 0.211 total
> ```
Execution time. Since the creation of this question, I came to your proposed solution (run an instance of the electron and get versions of it). However, it seems excessive to run an electron instance for something so simple. It still looks like a hack, not a solution.

It seems to me that solving this problem would be easier on the electron side: Just look at the current versions of the built-in libraries and include this information in the release in an accessible format. 

My primitive benchmark shows that on average it takes 80-100ms to get versions from an electron instance, while 0.003-0.010ms is spent reading a finished file. Of course, it's still fast enough. But if it is possible to do it faster, why not? Moreover, my original idea is to look in real build-time at the version of chromium for which the application is compiled and pass this information to all utilities (browserlist, esbuild, etc.). And in such scenarios, the extra delay of 100ms is very noticeable.

**Comment by RaisinTen** [comment]
No follow-up in 7 months, closing. Also, see Samuel's suggestion in https://github.com/electron/electron/pull/32853#issuecomment-1255905212.
