### ISSUE TITLE
Required not defined BUT NODEINTEGRATION SET TO TRUE

### ISSUE THREAD

**Issue by ShlomiRex** [electron/electron#28003]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details
I'm using electron-forge to create electron boilerplate
I then added webPrefrences to main window and added nodeIntegration and test if required works, but it doesn't (See screenshots)

`Uncaught ReferenceError: require is not defined` even though nodeIntegration set to true

### To Reproduce
index.js:
```
const { app, BrowserWindow } = require('electron');
const path = require('path');

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) { // eslint-disable-line global-require
	app.quit();
}

const createWindow = () => {
	// Create the browser window.
	const mainWindow = new BrowserWindow({
		webPreferences: {
			nodeIntegration: true,
			webviewTag: true
		}
	});

	// and load the index.html of the app.
	mainWindow.loadFile(path.join(__dirname, 'index.html'));

	// Open the DevTools.
	mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
	if (process.platform !== 'darwin') {
		app.quit();
	}
});

app.on('activate', () => {
	// On OS X it's common to re-create a window in the app when the
	// dock icon is clicked and there are no other windows open.
	if (BrowserWindow.getAllWindows().length === 0) {
		createWindow();
	}
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
```

index.html:
```
<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
	<title>Hello World!</title>
	<link rel="stylesheet" href="index.css">
</head>

<body>
	<h1>💖 Hello World!</h1>
	<p>Welcome to your Electron application.</p>
	<script>
		const electron = require("electron")
	</script>
</body>
</html>
```

### Screenshots

![1pdpv8x2e0l61](https://user-images.githubusercontent.com/17744127/109967757-acc5ed80-7ca6-11eb-9f94-0e83e0e18cd3.png)

### Additional Information

Everyone in google says nodeIntegration set to true. But it doesnt work!

**Comment by AxelTerizaki** [comment]
You actually need to set `contextIsolation: true` as well now. But it's not recommended unless you're sure your code runs in a controlled environment and you're not displaying pages from elsewhere (or so I understand)

**Comment by codebytere** [comment]
@ShlomiRex this is [expected](https://github.com/electron/electron/blob/master/docs/tutorial/context-isolation.md) with the `contextIsolation` default change.

**Comment by sgehrman** [comment]
doesn't work.
