### ISSUE TITLE
Where is sync shell.openItem?

### ISSUE THREAD

**Issue by MRayermannMSFT** [electron/electron#28024]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 9.0.0 and greater
* **Operating System:** any
* **Last Known Working Electron version:** N/A

The release notes for 9.0.0 say:

> Split shell.openItem(path) into synchronous and asynchronous methods. #20682

But when I look:
- at the linked PR
- the typings for `shell`
- the docs for `shell`

I cannot find any mention of a synchronous version of `openItem`. Is this just a typo/miscommunication in the releases notes or am I missing something?

**Comment by pushkin-** [comment]
I'm pretty sure that function doesn't exist anymore. It was replaced with openPath. [notes](https://github.com/electron/electron/blob/master/docs/breaking-changes.md#api-changed-shellopenitem-is-now-shellopenpath)

**Comment by MRayermannMSFT** [comment]
Ya, I understand `shell.openItem` is gone. I'm just trying to understand if the release notes for [9.0.0](https://www.electronjs.org/releases/stable?version=9&page=5#9.0.0) are wrong or if I'm misreading them.
![image](https://user-images.githubusercontent.com/21112697/110183692-446d2e00-7dc4-11eb-8b69-5efc9cf5f560.png)

They make it sound like a sync version still exists.

**Comment by MarshallOfSound** [comment]
The notes are incorrect and will be updated, the PR title and description is accurate.

https://github.com/electron/electron/pull/20682
