### ISSUE TITLE
Dialogs aren't centered to the window when calling showMessageBox(win, ...)

### ISSUE THREAD

**Issue by tangjfn** [electron/electron#28033]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  12.0.0
* **Operating System:Windows 10**
  Windows 10
* **Last Known Working Electron version:**
  11.x.x

**Comment by pushkin-** [comment]
dupe of [this](https://github.com/electron/electron/issues/23001)

**Comment by sofianguy** [comment]
Duplicate issue. Please follow https://github.com/electron/electron/issues/23001 for updates
