### ISSUE TITLE
webContents.options Do not have an effect (on webContents.print)

### ISSUE THREAD

**Issue by fwiwDev** [electron/electron#28041]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  v11.3.0
* **Operating System:**
  *  Windows 10 (2004)
* **Last Known Working Electron version:**
  *  N/A

### Expected Behavior

With these settings, I am expecting the page to be scaled to 50%, and no margins to be used:
```
  const optionsPrint = {
    scaleFactor: 50,
    printBackground: true,
    margins: { marginsType: 'none' },
    pageSize: 'Letter'
  }
  console.log(optionsPrint)
  e.sender.print(optionsPrint)
```
I am using this as the documentation: https://www.electronjs.org/docs/api/web-contents#contentsprintoptions-callback

### Actual Behavior

These options have no effect. When printing equivalent content to PDF (via webContents.printPDF) it is successful.

### To Reproduce

```
  const optionsPrint = {
    scaleFactor: 50,
    printBackground: true,
    margins: { marginsType: 'none' },
    pageSize: 'Letter'
  }
  console.log(optionsPrint)
  e.sender.print(optionsPrint)
```

**Comment by pushkin-** [comment]
bump

**Comment by etlweather** [comment]
Still an issue

**Comment by popod** [comment]
bump
