### ISSUE TITLE
Native Node Modules for Electron 11 and above do not compile with async cleanup behavior

### ISSUE THREAD

**Issue by implausible** [electron/electron#28043]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 11 and 10
* **Operating System:** Windows
* **Last Known Working Electron version:** Never, it was a new feature of Node patched into Electron 11/10

### Expected Behavior
When compiling a native node module that does not leverage NAPI, if the module attempts to use `node::AddEnvironmentCleanupHook`, the module will compile.

### Actual Behavior
The module does not compile, this is because Windows Electron leverages its own internally compiled version of the standard library, so unique_ptr cannot be leveraged in this way.

### To Reproduce
You can use this repository to reproduce:
https://github.com/implausible/electron-abi-issue-demo

### Additional Information
Issue can be solved by taking these 2 patches https://github.com/nodejs/node/commit/1fe571aa0c55814e58f6efefedf69da8d358034b and https://github.com/nodejs/node/commit/bf79987433e8b2457007a8f531e4a0b3112ed466

**Comment by deepak1556** [comment]
Looks simple enough to backport, thanks for getting this upstreamed.

@ckerr I have updated the labels to reflect the node versions that need this patch.
