### ISSUE TITLE
Top edge visible on frameless transparent window (MacOS)

### ISSUE THREAD

**Issue by jlmakes** [electron/electron#28042]
MacOS `10.14.6` (Mojave)

Electron `12.0.0`
Node `14.16.0`
Chrome `89.0.4389.69`

I setup a frameless transparent window ([API reference](https://github.com/electron/electron/blob/master/docs/api/frameless-window.md)) with these parameters:

```js
const win = new BrowserWindow({
  width: 800,
  height: 450,
  frame: false,
  resizable: false,
  transparent: true,
  webPreferences: {
    contextIsolation: false,
    nodeIntegration: true,
  },
});
```

I've noticed the "shine" along the top edge of the window is still visible. (See below)

![electron_macos_transparent_window](https://user-images.githubusercontent.com/2044842/110273652-dc644680-7f81-11eb-82d1-894097400ec6.gif)

Bug or user error?

**Comment by ckerr** [comment]
Likely macOS-only. Could not reproduce using https://gist.github.com/5f0518f6205aab60fa879545cd0669ef on Ubuntu 20.10 and Electron 12.0.0
