### ISSUE TITLE
alwaysOnTop is not always respected

### ISSUE THREAD

**Issue by CezaryKulakowski** [electron/electron#28052]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 13.0.0-nightly.20210223
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * I didn't check

### Expected Behavior
Window which was set to be alwaysOnTop always stays on top.

### Actual Behavior
Window which was set to be alwaysOnTop may loose its ability to stay on top.

### To Reproduce
1. Launch following application:
```
const { app, BrowserWindow } = require('electron')

function startTest() {
  let win = new BrowserWindow();
  win.setAlwaysOnTop(true);
  win.webContents.loadURL('https://www.example.com');
}

app.on('ready', startTest)
```
2. Launch Zoom
3. Start new Zoom Meeting and select `Share Screen`
4. Try to focus the window belonging to Electron's app.
Window loose it's ability to stay on top. It's also not possible to put window on top when it's covered behind another window.

### Additional Information
This issue is caused by this change: https://github.com/electron/electron/pull/18982. Reverting this change fixes the issue.

**Comment by CezaryKulakowski** [comment]
We may consider reverting https://github.com/electron/electron/pull/18982 as in my opinion this issue is more severe than a problem with window which doesn't hide behind the task bar.

**Comment by Slapbox** [comment]
Related to #20933?

Could this be remedied with `window.setAlwaysOnTop(true, 'normal')`? Could the second argument be defaulted to `'normal'`? I think the additional flexibility is good - I just didn't realize that the option had begun to apply to Windows so I was at a loss about what the issue was.

Or am I misunderstanding this issue?

**Comment by CezaryKulakowski** [comment]
Yes, setting level to `normal` fixes the issue. And it seems that that's the same issue as https://github.com/electron/electron/issues/20933 (it started to show in Electron 7 when this pr was integrated). Do you think that changing default level from `floating` to `normal` is the way to go?

**Comment by Slapbox** [comment]
Changing the default to `normal` would be my preference definitely. `floating` leads to nothing but unintended troubles. But I don't know if `floating` is the default on macOS or what other implications this would have.

**Comment by VerteDinde** [comment]
Hey @CezaryKulakowski and @Slapbox, we discussed this issue in the Releases Working Group - it looks like this is currently working as expected. When I tested the issue, it looks like it was staying on top for every window except for Zoom's "Share Screen" options - which, as you mentioned, is itself is also designed to stay on top of every other screen.

You should be able to use the existing API to override the "Share Screen" window: https://www.electronjs.org/docs/api/browser-window#winsetalwaysontopflag-level-relativelevel As you mentioned above, setting the level to "normal" should override this. Given this is the existing behavior and seems to be working as intended on macOS, we're hesitant to introduce a breaking change to defaults within the API (one that could potentially have implications on existing apps) if the solution exists within the API already. I'll leave this issue open for a few days for discussion, though. Also happy to add documentation around this so it's more clear in the future, if that would help.

Thanks for filing the issue!

**Comment by Slapbox** [comment]
@VerteDinde when did Windows begin supporting the levels option? Was it mentioned as a breaking change in the changelog? I think no because I don't recall seeing it and I spent a while confused over why it didn't work the same way.

I think the existence of this issue is sufficient to allow people to fix their issues themselves, and most people who would have encountered this would have already hit it since most new projects aren't going to start on old versions of Electron. But ideally this would be mentioned as a breaking change in the changelog.

**Comment by VerteDinde** [comment]
This is a fair point - I'll find which version of Electron the levels options changed in, and add it to our breaking changes document and changelog so it's easier to track for others updating. Thanks!
