### ISSUE TITLE
Failed to create Win-Installer due to large application size

### ISSUE THREAD

**Issue by christopherGr** [electron/electron#28070]
Hello,

I am trying to create windows installer (nsis, squirrel, msi) for my large application which size is about more than 4gb (i had to embed many mp4 files into asar file) but i cannot, the setup.exe that is created is corrupted..if i delete embedded mp4 files everything is ok...
So far I have tried electron-builder, electron-forge, electron-winstaller, electron-installer-windows...
Is there any solution?

**Comment by jkleinsc** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
