### ISSUE TITLE
When productName is not ASCII characters, app.getName() got wrong encoding

### ISSUE THREAD

**Issue by LongTengDao** [electron/electron#28079]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 12.0.0
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * 

### Expected Behavior

```
中文
```

### Actual Behavior

```
涓枃
```

### To Reproduce

```
electron .
```

./package.json

```json
{ "productName": "中文" }
```

./index.js

```js
console.log(require('electron').app.getName());
```

**Comment by nornagon** [comment]
Hm, I can't reproduce this. Can you verify that your package.json is UTF-8 encoded? Also, does the same thing happen if you call `app.setName("中文")`?

**Comment by LongTengDao** [comment]
@nornagon
- Yes, the package.json is UTF-8 encoded, and one more thing: `C:\Users\<userName>\AppData\Roaming\中文` exists correctly.
- Yes, after `setName`, the same thing still happen, it seems that the problem is at `getName` level? I found when an `utf-8` html file includes `中文` has wrong charset `gb2312`, it display `涓枃`.

**Comment by nornagon** [comment]
@LongTengDao I'm still learning things about the Windows console, is it possible that the terminal itself is misinterpreting the bytes?

What happens if you try `console.log(Buffer.from(app.getName()))` to see the exact bytes returned from `app.getName()`?
