### ISSUE TITLE
TypeError: Cannot read property 'landscape' of undefined

### ISSUE THREAD

**Issue by Vanessa219** [electron/electron#28071]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 12.0.0
* **Operating System:**
  *  Windows 10
* **Last Known Working Electron version:**
  * 12.0.0

### Expected Behavior

Export PDF success.

### Actual Behavior

print:
```
webContents export pdf error:TypeError: Cannot read property 'landscape' of undefined
```

### To Reproduce

```
mainWindow.webContents.on("did-finish-load",async ()=> {
    writeLog('webContents export did-finish-load')
    try {
      let buffer = await mainWindow.webContents.printToPDF({landscape: false});
      writeLog("webContents export pdf start" );
      await fs.promises.writeFile('/Users/Vanessa/Downloads/a.pdf', buffer);
      writeLog("webContents export pdf done" );
    } catch (error) {
      writeLog("webContents export pdf error:" + error );
    }
  })
```

**Comment by nornagon** [comment]
I've adapted the repro into a standalone [Fiddle](/electron/fiddle): https://gist.github.com/db1a6f2227def4ba88133167c5290609, but unfortunately this does not reproduce for me on Mac on Electron 12 or 13.

@Vanessa219, does the gist above produce the same error for you?

**Comment by Vanessa219** [comment]
Thank you very much, after using this [code](https://gist.github.com/db1a6f2227def4ba88133167c5290609), it will only print
```
webContents export did-finish-load
```

My computer is windows10 home edition.

**Comment by codebytere** [comment]
Closing as fixed in latest versions.
