### ISSUE TITLE
Flashing menus on linux

### ISSUE THREAD

**Issue by user414** [electron/electron#28073]
### Preflight Checklist

* [ x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v11.3
* **Operating System:**
  *  Ubuntu 18.04 LTS x64 
* **Last Known Working Electron version:**
Would have to dig in deeper as this started in one of the version of VS Code but unknown at this time exactly which and to which version of electron it maps. 

### Expected Behavior
Menu not flashing when switching

### Actual Behavior
Menu flashes when switching between menus

### To Reproduce

Same issue as https://github.com/electron/electron/issues/20520 which still exist with Vscode 1.54 using electron 11. As described in this VS Code issue https://github.com/microsoft/vscode/issues/76850

**Comment by user414** [comment]
@jkleinsc Thanks for your reply. Please note that I was not presented with an issue template and that the issue template referred to here https://www.electronjs.org/docs/development/issues#submitting-a-bug-report gives a 404. Nevertheless, I will copy from the old issue.

**Comment by jkleinsc** [comment]
Thanks for updating @user414!

**Comment by user414** [comment]
This issue is still present in the Electron version I'm using 13.5.2.

**Comment by jkleinsc** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.
