### ISSUE TITLE
can electron-triage bot reopen old issues if deemed appropriate rather than forcing us to create new issues?

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#28078]
Not sure where to post this exactly, but can the electron-triage bot that's been closing all of the old issues, reopen them if we comment saying that the supported Electron versions still have the bug?

There are plenty of comments/suggestions/ideas in the old issue reports that could be helpful to know that is inconvenient to have to copy over to the new report, and it's not clear what we gain from having to recreate the issue anyway.

**Comment by jkleinsc** [comment]
@pushkin- thanks for the suggestion.  We will take it under consideration. 

I'm going to close this issue as we have [the Electron Discord server](https://discord.com/invite/electron) as a platform for discussions.  Please feel free to continue the conversation over there.

**Comment by pushkin-** [comment]
@jkleinsc I posted it on Discord [here](https://discord.com/channels/745037351163527189/745037351725826080/818884063141560350) and was suggested to post here. Is there a better place?
