### ISSUE TITLE
[Bug]: Linux Electron 12 always unnecessary opens BrowserWindow menu on every keyboard layout switch via Alt+Shift & Alt+Ctrl hotkeys

### ISSUE THREAD

**Issue by MurzNN** [electron/electron#28088]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

20.04

### What arch are you using?

x64

### Last Known Working Electron version

5.x

### Expected Behavior

When user change keyboard layout via Alt+Ctrl or Alt+Shift hotkeys, it should just change keyboard layout and have no effect on any focused Electron input elements.

### Actual Behavior

At every layout changing on any input element (textarea, input, etc) - it lose focus, so users can't continue typing text, and need manually click on input element to restore focus and continue typing. This is very annoying for all non-English users!

### Testcase Gist URL

https://github.com/geeksesi/time_reminder

### Additional Information

**How to reproduce:**

1. Add any second keyboard layout in KDE settings, default hotkey for switch will be "Alt+Shift".

2. Open any app, using Electron 12.0 version, for example "Quick start" app.

3. Make focus on any input element, start typing some text.

4. Press "Alt+Shift" and try continue typing, you will can't, because element lose focus! Via "Alt" key press Electron activates app menu, and you can press "Esc" for deactivate it and continue typing, or click via mouse on element.

Screenshot of problem:
![](https://user-images.githubusercontent.com/28778964/54477533-03b62c00-481e-11e9-8c63-3c1f7402eaa5.png)

**How to workaround:**

Downgrade Electron application to 5.x or earlier versions of Electron, and this issue will not reproduced! 

# Right solution
**Please investigate source of this issue and fix this regression on fresh Electron versions!**

P.S. Here is the clone of #22213 that is closed without any reasons! Also some Electron 4.x apps was have similar issue, that can be fixed via workaround with adding keyboard shortcuts to all menu elements (here is example of fix: https://github.com/vector-im/riot-web/issues/4345), but this workaround stops working on Electron 6.x+ versions.

**_Similar reports, depending on this issue:_** 
- https://github.com/microsoft/vscode/issues/85405
- https://github.com/notable/notable/issues/557 
- https://github.com/RocketChat/Rocket.Chat.Electron/issues/1355
- https://github.com/vector-im/element-web/issues/4345
- https://github.com/electron/electron/issues/17418
- https://github.com/laurent22/joplin/issues/3345
- https://github.com/signalapp/Signal-Desktop/issues/4744
- https://github.com/electron/electron/issues/11106
- https://github.com/typora/typora-issues/issues/3366
- https://github.com/sindresorhus/caprine/issues/628
- https://github.com/klaussinani/tusk/pull/197
- https://github.com/meetfranz/franz/issues/1366
- https://github.com/meetfranz/franz/issues/1088
- https://github.com/signalapp/Signal-Desktop/issues/3621
- https://github.com/microsoft/vscode/issues/85444
...and many more affected apps!

**Comment by MurzNN** [comment]
**Possible places in code where this can be fixed:**

Maybe commenting out this https://github.com/electron/electron/blob/master/shell/browser/ui/views/root_view.cc#L24-L26 section can help with workaround for this issue? I can't produce compiled Electron from source on my machine to test this, does anybody can do this test?

Other possible places are:
1. https://github.com/electron/electron/blob/master/shell/browser/ui/accelerator_util.cc#L46-L48

2. https://github.com/electron/electron/blob/master/shell/common/keyboard_util.cc#L32

3. https://github.com/electron/electron/blob/master/shell/browser/ui/views/global_menu_bar_x11.cc#L283

4. https://github.com/electron/electron/blob/master/shell/browser/ui/views/menu_bar.cc#L224

5. https://github.com/electron/electron/blob/master/shell/browser/ui/accelerator_util.cc#L46

6. https://github.com/electron/electron/blob/master/shell/browser/ui/views/root_view.cc#L25

7. https://github.com/electron/electron/blob/master/shell/common/keyboard_util.cc#L33

**Comment by hotsezus** [comment]
There's also another issue closed
https://github.com/electron/electron/issues/11106#event-4439298753

**Comment by geeksesi** [comment]
i found something.
if you press alt (first and don't release ) + shift ( pres and release then release alt ). there is no problem.

but my habit is this : press alt ( first and don't release ) + press shift and release alt then release shift.

we should change shift action  to press ( now will act to shift when you release it ).

**Comment by isaacvonaaron** [comment]
Just want to upvote on this and say it's very important and affects users from most of the world except north America and part of western Europe. The rest of the world needs to switch between input methods quite often.

**Comment by koshelevdk** [comment]
Same issue is relevant for Slack (messenger) and Atom (text editor). For slack we have web version at least. But other applications are completely useless.

**Comment by wlwl2** [comment]
> Just want to upvote on this and say it's very important and affects users from most of the world except north America and part of western Europe. The rest of the world needs to switch between input methods quite often.

This Alt key ambiguity can affect all Alt- key shortcuts as well (I've had to remove my old shortcuts), and I'm working primarily in English right now. I've raised some points here: 

https://github.com/atom/atom/issues/21825#issuecomment-816982301

One solution might be to separate Electron/Atom Alt key from the operating system Alt key. I'm also not sure at which point KeyDown, KeyUp and KeyPress is currently controlled. I wonder if that is done in Electron or Atom's codebase.

**Comment by MurzNN** [comment]
Still the very annoying issue on Electron 13.0 beta for all users, that user more than one keyboard layouts with default switch hotkey!

**Comment by PanosFirmpas** [comment]
Commenting to add pressure for the issue to be fixed.

**Comment by vetash** [comment]
This is noncence, after all these years there is no any reaction for this bug! Just great. I decided to remove all menu in any electron based app on my desktop becaouse of this rubbish, thank you opensource, great job, Still not have any clue for how this can been happen AGAIN after some devs workaround this bug in 2017. https://github.com/vector-im/element-web/pull/5000/commits/0cf16be38a66b9f5e1df40f8f8997e1c0518fb88

**Comment by MurzNN** [comment]
@zcbenz Can you please commend in which Electron release this PR is included? I testing app with Electron 13.0/1 (Chrome 91.0.4472.69) - the problem is still persist.

**Comment by MurzNN** [comment]
Seems this fix is included in 13.1.0 version only: https://www.electronjs.org/releases/stable?page=1#13.1.0 - will wait...
