### ISSUE TITLE
[Bug]: shell.openPath stopped working for URLs on Linux

### ISSUE THREAD

**Issue by xmedeko** [electron/electron#28095]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.2.1

### What operating system are you using?

Ubuntu

### Operating System Version

18

### What arch are you using?

x64

### Last Known Working Electron version

10.3.0

### Expected Behavior

`shell.openPath('https://www.electronjs.org')` should open the URL in the default browser.

### Actual Behavior

`shell.openPath('https://www.electronjs.org')` does nothing, it returns `''` - i.e. no error. 

### Additional Information

In Electron 10.3.0 (and prior to it), `shell.openPath('https://www.electronjs.org')` has opened the default browser with the URL. Since I have upgraded to v11.2.1, then it does nothing. I have `xdg-open` installed and `xdg-open 'https://www.electronjs.org'` opens the default browser.

Workaround: use `shell.openExternal()`
Why it's not a good solution:
*  In my app, links are entered by a user and do not know if they are a local file or external URL - I have to guess it.
*  Also, `shell.openPath()` returns an error message if the file or link cannot be opened.
* And `shell.openExternal()` is not recommended for user data, see  https://www.electronjs.org/docs/tutorial/security#14-do-not-use-openexternal-with-untrusted-content

Note: Electron 11.2.1 on Windows works OK, on MacOSX same problem.

**Comment by xmedeko** [comment]
Reading the docs, it seems to me, that `shell.openPath()` is for opening file paths only, while URLs has to be opened with `shell.openExternal()`. Is that true? If so, I think the doc could be improved to be clearer.

Also, I would welcome some explanation, how it works on Windows, Linux and Mac. It seems to me, that both of them run `xdg-open` on Linux, so it's unclear, why not to use both URL and file path `openPath`.

**Comment by nornagon** [comment]
This is working as expected, `shell.openPath` is not intended for opening URLs, and indeed it does not behave that way on mac/windows.

The docs for [`shell.openPath`](https://www.electronjs.org/docs/api/shell#shellopenpathpath) say:
> Open the given file in the desktop's default manner.

The docs for [`shell.openExternal`](https://www.electronjs.org/docs/api/shell#shellopenexternalurl-options) say:
> Open the given external protocol URL in the desktop's default manner.

I think this is fairly clear, but if you have suggestions for improvements I'd happily review a PR!

**Comment by xmedeko** [comment]
@nornagon Thanks for the reply. Confusing is, that on Windows `openPath()` works for URLs, too. And also confusing is, that no error is thrown when URL is used for `openPath()` on Linux.

What about the security warning https://www.electronjs.org/docs/tutorial/security#14-do-not-use-openexternal-with-untrusted-content is that valid for `shell.openPath()`, too?

In regards of doc improvement, I would like to make PR, but do not know how the `shell.openPath()` and `shell.openExternal()` works, so cannot make PR. I just can sketch some outline what should be in doc.

**Comment by nornagon** [comment]
Here's the relevant code:

### openPath
#### mac
https://github.com/electron/electron/blob/09d7b2bc91009ae794e45142d064b4e8c5462022/shell/common/platform_util_mac.mm#L69-L73
#### linux
https://github.com/electron/electron/blob/462de5f97a302987dc5fa5c222781ceed040f390/shell/common/platform_util_linux.cc#L167
#### win
https://github.com/electron/electron/blob/09d7b2bc91009ae794e45142d064b4e8c5462022/shell/common/platform_util_win.cc#L309-L312

### openExternal
#### mac
https://github.com/electron/electron/blob/09d7b2bc91009ae794e45142d064b4e8c5462022/shell/common/platform_util_mac.mm#L45-L49
#### linux
https://github.com/electron/electron/blob/462de5f97a302987dc5fa5c222781ceed040f390/shell/common/platform_util_linux.cc#L182-L189
#### win
https://github.com/electron/electron/blob/09d7b2bc91009ae794e45142d064b4e8c5462022/shell/common/platform_util_win.cc#L248-L250

**Comment by xmedeko** [comment]
@nornagon That's not all relevant code, but got you point that I should check the code by myself. So, I am sorry, I do not understand this low level C code in such depth and do a security audit. My primary concern now is: What about the security warning https://www.electronjs.org/docs/tutorial/security#14-do-not-use-openexternal-with-untrusted-content is that valid for `shell.openPath`, too? Or is `shell.openPath` safe for any user entered path string? (That was the reason why I have used it for URLs, too, because the security warning was just about the `openExternal`).

**Comment by nornagon** [comment]
That depends on your use case. `openPath` will run the system's default handler for the file, which may not necessarily be safe.

**Comment by xmedeko** [comment]
@nornagon thanks for the answer. 

I have one more think about the Linux behaviour. I have spied how Electron executes `xdg-open` with `openPath` on Linux:
```
shell.openExternal('sms:123456') -> xdg-open sms:123456
shell.openPath('sms:123456') -> xdg-open sms:123456
shell.openExternal('svn://server/path') -> xdg-open svn://server/path
shell.openPath('svn://server/path') -> nothing, xdg-open not executed and openPath returns '' - no error.
```

So, Electron prevents executing `openPath('svn://server/path')` silently. It should return an error (string) or a rejected promise instead.
