### ISSUE TITLE
[Bug]: 'electron .' randomly stops working for no reason

### ISSUE THREAD

**Issue by KadenBiel** [electron/electron#28096]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

9.4.4

### What operating system are you using?

Windows

### Operating System Version

10

### What arch are you using?

x64

### Last Known Working Electron version

9.4.4

### Expected Behavior

In my package.json I have a script where I can type "yarn start" in my command line, and it will run the 'electron .' command. I expected it to run the application I made so that I can test it.

### Actual Behavior

The command works for a little while, then out of nowhere I will try and run the command and it will return
```
yarn run v1.22.10
$ electron .

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Additional Information

I have found with some playing around that this will happen unexpectedly, I don't need to do anything other than run the command for this issue to occur. Once this starts happening the only way to fix it is to copy my application folder and delete the old one then run 'yarn install' in the new one. As I said, I don't have to change anything in my application, I have tested my application then walked away for a few minutes and tried testing again without changing anything and the issue will occur. I don't think it's the way I'm closing the test, as I use the same method every time (ctrl+c to close the batch job).

**Comment by jkleinsc** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/tutorial/support#supported-versions), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
