### ISSUE TITLE
[Bug]: BrowserView does not auto-resize on maximize/minimize

### ISSUE THREAD

**Issue by binyamin** [electron/electron#28106]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

20.04

### What arch are you using?

x64

### Last Known Working Electron version

N/A

### Expected Behavior

If I set the BrowserView to autoResize on it's width or height, it should do so on maximize and minimize just like it does on resize.

### Actual Behavior

Nothing changes.

### Testcase Gist URL

https://gist.github.com/binyamin/d4a5d84045d841885adac74a75d02bb7

**Comment by devinbinnie** [comment]
I'm also experiencing a similar issue. I've been just manually calling `setBounds` on the BrowserView when the `mainWindow` is resized.

Works perfectly fine on macOS and Windows, but on Linux if I maximize I get a window that looks like this:
![image](https://user-images.githubusercontent.com/52460000/110841203-9c4bdf00-8273-11eb-8bb4-2d1e9e6f31f4.png)

**Comment by matheusfillipe** [comment]
I have the same problem. When I resize by dragging calling setContentBounds on the browserView works fine but when i maximize the window the browserView doesn't resize.
![Peek 2021-05-08 02-15](https://user-images.githubusercontent.com/24435787/117527578-77d65f80-afa3-11eb-9c17-a9dad4668d0c.gif)

This is what I am trying:

```javascript
       (....)
        win.setBrowserView(view)  // win is the main window and view a BrowserView
        view.setBounds({ x: 0, y:250, width: win.getBounds().width, height: win.getBounds().height-250 })
        view.setAutoResize({horizontal: true, vertical: true})
        view.webContents.loadURL(url)
        view.webContents.openDevTools({mode:'undocked'});
    })

    win.on('resize', function () {  //This is always getting called
        view.setBounds({ x: 0, y:250, width: win.getBounds().width, height: win.getBounds().height-250 })
    });
    const mainScreen = screen.getPrimaryDisplay();
    win.on("maximize", () => {  // This nevers get called
        win.setSize(mainScreen.workArea.width, mainScreen.workArea.height)
        view.setBounds({ x: 0, y:250, width: win.getBounds().width, height: win.getBounds().height-250 })
        console.log("maximized")
    });

```

**Comment by matheusfillipe** [comment]
I have a workaround though:

```javascript
  win.on('resize', function () {
    view.setBounds({x: 0, y: 250, width: win.getBounds().width, height: win.getBounds().height - 250})
    console.log("resize")
    if(win.isMaximized() || win.isFullScreen()){
      win.setSize(mainScreen.workArea.width, mainScreen.workArea.height)
      view.setBounds({x: 0, y: 250, width: mainScreen.workArea.width, height: mainScreen.workArea.height - 250})
    }
  });

```

**Comment by safinaskar** [comment]
I suggest this workaround: https://github.com/electron/electron/issues/22174#issuecomment-1183050589 . It seems cleaner. Simply remove all other workaround code and add provided `mainWindow.on("resize", ...)`. Works with current stable (20.0.2)

**Comment by safinaskar** [comment]
bump

**Comment by safinaskar** [comment]
bump

**Comment by safinaskar** [comment]
bump

**Comment by antonio-coimbra** [comment]
bump

**Comment by antonio-coimbra** [comment]
Encountered this issue on Ubuntu

**Comment by safinaskar** [comment]
[GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)

**Comment by safinaskar** [comment]
[GitHub stale bot considered harmful](https://drewdevault.com/2021/10/26/stalebot.html)

**Comment by binyamin** [comment]
I'm sick of getting these "stale" notifications. I'm closing this issue. Feel free to open your own issue.

BTW, I haven't used electron in years. [Tauri](https://tauri.app/) is my go-to these days. It's smaller, more performant, and uses native webviews instead of chromium.
