### ISSUE TITLE
[Feature Request]: add loadExtension support for in-memory session

### ISSUE THREAD

**Issue by LongTengDao** [electron/electron#28103]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

currently, loadExtension is not supported for in-memory session

### Proposed Solution

add loadExtension support

### Alternatives Considered

-

### Additional Information

-

**Comment by nornagon** [comment]
This is complicated for a variety of reasons. "In-memory sessions" in Electron are roughly similar to incognito profiles in Chromium, which have complex logic for how extensions behave, see e.g. https://developer.chrome.com/docs/extensions/mv2/manifest/incognito/

I personally have no plans to work on this, but if anyone is interested in working up a PR I'd be happy to review it.
