### ISSUE TITLE
[Bug]: Electron does not pass unrecognized locales through to the application

### ISSUE THREAD

**Issue by savannidgerinel** [electron/electron#28119]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

 12.0.1

### What operating system are you using?

Other Linux

### Operating System Version

NixOS 20.09

### What arch are you using?

x64

### Last Known Working Electron version

none

### Expected Behavior

`app.getLocale()` should allow locales such as "eo" (Esperanto) through the the running application.

In general, I would expect `app.getLocale()` to accurately report back all ISO 639 language codes.

### Actual Behavior

`app.getLocale()` return "en-US" if my LANG and LC_ALL environment variables are set to "eo".

### Testcase Gist URL

https://gist.github.com/savannidgerinel/997949efadf18279b761c412fb5b9e4f

### Additional Information

I am using the locale system from the Linux command line, dependent on the LC_ALL and LANG variables.

LANG=eo, LC_ALL=eo, app.getLocale returns en-US
LANG=eo.UTF8, LC_ALL=eo.UTF8, app.getLocale returns en-US
LANG=de-DE,LC_ALL=de_DE, app.getLocale returns de

**Comment by joeyhusky** [comment]
I'm trying to support French Canadian in my Electron application and seeing similar behavior. `app.getLocale()` returns "fr" instead of "fr_CA". I'm using Electron version 15.2.0
