### ISSUE TITLE
Add "fullscreen" role for MenuItem and add shortcuts for entering fullscreen

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#2811]
Fullscreen works fine, but there are some details missing.

### Fullscreen enter/exit keyboard shortcuts don't work.

Electron should by default enter fullscreen on <kbd>⌃</kbd><kbd>⌘</kbd><kbd>F</kbd> and exit on <kbd>⌃</kbd><kbd>⌘</kbd><kbd>F</kbd> or <kbd>Esc</kbd>. This is the default behavior for other apps.

### Enter fullscreen menu item

Many apps comes with a `View` => `Enter Full Screen` menu. There should be a menu `role` for this so it's handled automatically. This is important as the menu label needs to be `Exit Full Screen` when in fullscreen.

<img width="214" alt="screen shot 2015-09-17 at 10 36 31" src="https://cloud.githubusercontent.com/assets/170270/9924317/671fbeda-5d28-11e5-9c99-fe4d62522dc6.png">

<img width="202" alt="screen shot 2015-09-17 at 10 36 43" src="https://cloud.githubusercontent.com/assets/170270/9924316/671a0a80-5d28-11e5-9b9d-ec4d8fc9996b.png">

I want to be able to do:

```js
{
        role: 'fullscreen'
}
```

In the menu template, and have `label` and `accelerator` handled for me: https://github.com/atom/electron/issues/2812.

-

Relevant: https://github.com/atom/electron/commit/2d940b7df7ca7e842eec94769f451afe88fab542

**Comment by boneskull** [comment]
:+1:
