### ISSUE TITLE
[Feature Request]: support persistent session to specify storage path

### ISSUE THREAD

**Issue by LongTengDao** [electron/electron#28122]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

If I am not mistaken, the `cookie`, `localStorage`, `indexedDB` and resource cache of the programs based on Electron store in the following locations currently:

- Windows: `C:\Users\<userName>\AppData\Roaming\<productName>`
- Linux: `/home/<userName>/.config/<productName>`
- OS X: `/Users/<userName>/Library/Application Support/<productName>`

But when we use software in portable devices on different computers, we probably want to be able to freely specify the storage location to the portable device self, to **use it anywhere continuously**, or do not leave persistent traces in the temporary computer (maybe through in-memory session it's possible, but `loadExtension` is not supported in this case).

In addition, we may also have multiple programs based on Electron **developing** (or just using). Even if we are careful to avoid duplication of names, we will encounter problems when different versions of the same software coexist.

### Proposed Solution

```js
session.setPath(`<customPath>`);
```

### Alternatives Considered

```js
session.fromPartition('persist:name', {
    path: `<customPath>`,
});
```

```js
session.fromPartition('persist:<customPath>', {
    path: true,
});
```

### Additional Information

no

**Comment by nornagon** [comment]
you're looking for `app.setPath('userData', '...')`.
