### ISSUE TITLE
MenuItem `label` and `accelerator` should be optional when `role` is specified

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#2812]
To reduce boilerplate it would be useful if default values were used for `label` and `accelerator` if `role` were specified.

So instead of:

```js
var template = [
  {
    label: 'Edit',
    submenu: [
      {
        label: 'Undo',
        accelerator: 'CmdOrCtrl+Z',
        role: 'undo'
      },
      {
        label: 'Redo',
        accelerator: 'Shift+CmdOrCtrl+Z',
        role: 'redo'
      }
    ]
  }
];
```

I could just do:

```js
var template = [
  {
    label: 'Edit',
    submenu: [
      {
        role: 'undo'
      },
      {
        role: 'redo'
      }
    ]
  }
];
```

-

`submenu` should also be optional. Would be useful for the `services` role.

-

This would also have the benefit of those menu items being automatically localized for you.

**Comment by zcbenz** [comment]
I'm :+1: on this, the major problem is the localization of the labels, we can probably copy and use the resources from Chromium.

**Comment by sindresorhus** [comment]
// @danhp In case you're interested. This would significantly reduce the required boilerplate for menus.

**Comment by dogancelik** [comment]
Can we override accel values, for example some X application needs a custom accel for redo and have to use <kbd>Shift+Ctrl+Z</kbd> for something else.

Can I do `{ role: 'redo', accelerator: 'CmdOrCtrl+Y' }`, to get local Redo text and accel but new accel will override.
