### ISSUE TITLE
[Bug]: Set an BrowserView  instance object to null， can't be destroyed,  how to destroy a BrowserView ?

### ISSUE THREAD

**Issue by 82318179** [electron/electron#28123]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Windows

### Operating System Version

win10

### What arch are you using?

x64

### Last Known Working Electron version

9.0.0

### Expected Behavior

Set an BrowserView  instance object to null， can't be destroyed,  how to destroy a BrowserView ?

### Actual Behavior

Set an BrowserView  instance object to null， can't be destroyed,  how to destroy a BrowserView ?

Set an BrowserView  instance object to null， can't be destroyed,  how to destroy a BrowserView ?

`  const view = new BrowserView();
  mainWindow.setBrowserView(view);
  view.setBounds({ x: 0, y: 0, width: 300, height: 300 });
  view.webContents.loadURL('https://haokan.baidu.com/v?vid=922345307482523763&pd=bjh&fr=bjhauthor&type=video');
  view = null;`
Run the program and find that the BrowserView   still exists .then how to destroy a browserview?

**Comment by nornagon** [comment]
---
action:
 - add 'discussion' label
 - close issue
---

Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by bei-yang** [comment]
How do you solve this

**Comment by kevinlinv** [comment]
Hi, there is a memory leak issue with `BrowserView` starting from Electron v11, the only way to workaround that is to call an undocumented `browserView.webContents.destroy()` function.

You can see this issue for more details.
https://github.com/electron/electron/issues/26929
