### ISSUE TITLE
How to send Post Data in electron net request

### ISSUE THREAD

**Issue by umarpucitian** [electron/electron#28124]
How can I send Data in my Post request? Which parameter to use and how please let me know..

Here is my code
const requestt = net.request({
            method: 'POST',
            protocol: 'http:',
            hostname: 'localhost',
            port: 8000,
            path: '/testing',
        })
        requestt.on('response', (response) => {
            response.on('data', (chunk) => {
                console.log(`${chunk}`)
            })

        })
        requestt.write(postData)
        requestt.end()

**Comment by umarpucitian** [comment]
Also how can we send an image on POST request in base64 string format??

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
