### ISSUE TITLE
[Bug]: setUserTasks/setJumpList don't work after window was created

### ISSUE THREAD

**Issue by TanninOne** [electron/electron#28125]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Home (19042)

### What arch are you using?

x64

### Expected Behavior

calling app.setJumpList or app.setUserTasks sets the list of tasks on an application.

### Actual Behavior

If the BrowserWindow was already created, the call does nothing.
It does affect all windows created after the call to setJumpList though.

### Additional Information

To reproduce:

```
// before creating the window
    app.setJumpList([
      {
        name: 'before',
        type: 'tasks',
        items: [
          {
            type: 'task',
            title: 'before',
            description: 'before',
            program: 'cmd.exe',
          },
        ],
      },
    ]);
// create window
setTimeout(() => {
    app.setJumpList([
      {
        name: 'after',
        type: 'tasks',
        items: [
          {
            type: 'task',
            title: 'After',
            description: 'After',
            program: 'cmd.exe',
          },
        ],
      },
    ]);
}, 5000);
// observe how the jump list still says "Before" after the timeout expires
```

I don't really know the windows api in the background so I can't 100% rule out this is a windows issue or limitation but I find that very unlikely.
It may be that electron is simply missing a change notification to let the windows shell know something has changed, probably
SHChangeNotify(SHCNE_UPDATEITEM,

This may be relevant:
https://devblogs.microsoft.com/oldnewthing/20150903-00/

This is a re-report of #23025
I have verified that it still happens in 11.3.0

**Comment by The-MAZZTer** [comment]
I can verify this happens in 12.0.4,

It looks like calling app.setUserTasks clears all tasks regardless of arguments passed in.

If I create a sample app that does this before showing a window, this works fine:

app.setUserTasks([{
        program: "cmd.exe",
        arguments: "",
        title: "Task Title",
        description: "Task Description",
        iconPath: "C:\\Windows\\System32\\shell32.dll",
        iconIndex: 5,
        workingDirectory: null
      }]); 

If I change this code to force it to wait, it clears the task list instead:

    app.whenReady().then(() => {
      setTimeout(() => {
        app.setUserTasks([{
          program: "cmd.exe",
          arguments: "",
          title: "Task Title",
          description: "Task Description",
          iconPath: "C:\\Windows\\System32\\shell32.dll",
          iconIndex: 5,
          workingDirectory: null
        }]);    
      }, 5000);
    });

I can put together a test project if needed but this is pretty simple to reproduce.

**Comment by The-MAZZTer** [comment]
I can confirm setJumpList has the same problem as OP reported.

Also both APIs return true/"ok" indicating they've succeeded. This suggests to me Electron is calling the Windows API correctly and getting a success return value but not passing in the jump list properly.

(As a side bug, the .d.ts for setJumpList incorrectly indicates it returns void rather than the actual return type.)

**Comment by TanninOne** [comment]
This issue is still relevant afaict

**Comment by TanninOne** [comment]
This issue is still relevant

**Comment by TanninOne** [comment]
Still relevant as of electron 24.1.2

**Comment by KosmosisDire** [comment]
I am having the same issue, it would be very helpful if this was fixed or changed

**Comment by KosmosisDire** [comment]
bump

**Comment by KosmosisDire** [comment]
bump

**Comment by sham601** [comment]
OK thanks for you
