### ISSUE TITLE
MenuItem should have a `quit` role on OS X

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#2813]
There's already many other useful roles: http://electron.atom.io/docs/v0.32.0/api/menu-item/

`Quit AppName` is something that all apps have an should be a role, instead of having to manually implement it. It's [not much code](https://github.com/sindresorhus/caprine/blob/cba6a1b3d1864901b13cb16d67e7792d861af488/menu.js#L67-L73) to manually implement it, but would still be nicer if it were a `role`. Would be especially useful with #2812, so that you only have to specify `{role: 'quit'}` to get the menu item.

**Comment by sindresorhus** [comment]
Many Linux apps have a `Quit` menu item in the `File` menu, so might be a good idea to support Linux on this one too.

**Comment by bj7** [comment]
Are you specifically referring to the `AppName` in this context? Electron already has a `Quit` functionality in the OS X tray, just not a specified `AppName`.

**Comment by sindresorhus** [comment]
@bj7 I'm referring to the menubar.

<img width="241" alt="screen shot 2016-05-31 at 21 49 42" src="https://cloud.githubusercontent.com/assets/170270/15678748/9ca4ec08-2779-11e6-9a56-4b4e465d2bd1.png">

**Comment by bj7** [comment]
Yes, I was wondering if you meant the name, "Caprine" immediately following the "Quit". Currently, Electron has the "Quit". Sorry for not being more specific.
![image](https://cloud.githubusercontent.com/assets/1395096/15678890/e7fada98-271d-11e6-8a4c-00d44792b65a.png)

**Comment by sindresorhus** [comment]
Pretty much illustrating why this `role` is needed. Even the default Electron menu couldn't get it right, and use `Quit` on OS X instead of the correct `Quit Electron`.

**Comment by bj7** [comment]
Thank you for clarifying. I'll take some time and look into this.

**Comment by bj7** [comment]
This has been addressed: 
![image](https://cloud.githubusercontent.com/assets/1395096/15943977/65430092-2e59-11e6-85f1-b4fb554b7a36.png)

It was quite trivial; all that was needed was to append `app.getName()` to the label name as indicated by @sindresorhus:

`{
label: 'Quit ' + app.getName(),
accelerator: 'Command+Q',
click () { app.quit() }
}` 
So now, as long as the application sets the name, it will appear appropriately. I'll submit a PR for this.
