### ISSUE TITLE
Use default menu items for `Edit` and `Window` when `role` is specified but not `submenu` on OS X

### ISSUE THREAD

**Issue by sindresorhus** [electron/electron#2814]
Many apps never have the need to change `Edit` or `Window`. Would be useful if they were filled out with default menu items when the correct `role` is specified, but `submenu` is not specified.

<img width="196" alt="screen shot 2015-09-17 at 11 17 20" src="https://cloud.githubusercontent.com/assets/170270/9924846/bed4b2b6-5d2d-11e5-96a2-10443a41dbde.png">
<img width="231" alt="screen shot 2015-09-17 at 11 17 28" src="https://cloud.githubusercontent.com/assets/170270/9924847/bedb1890-5d2d-11e5-8a51-0064ae5561b6.png">
## 

This would let me remove a lot of [boilerplate](https://github.com/sindresorhus/caprine/blob/cba6a1b3d1864901b13cb16d67e7792d861af488/menu.js#L88-L148).

**Comment by tonyganch** [comment]
Taking the issue 🐙
