### ISSUE TITLE
[Bug]: can't listen drag events  in iframe in the production environment

### ISSUE THREAD

**Issue by litterye** [electron/electron#28148]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Windows

### Operating System Version

10

### What arch are you using?

x64

### Last Known Working Electron version

11.2.1

### Expected Behavior

As before, electron can listen for drag and drop events in production

### Actual Behavior

can't listen drag events  in iframe in the production environment

**Comment by codebytere** [comment]
@litterye you must provide a reproducible sample for us to proceed. Please add one to this issue or it will be closed in 5 days.
