### ISSUE TITLE
[Bug]: shell.openPath executed from renderer thread shows error dialog not on top on Windows

### ISSUE THREAD

**Issue by xmedeko** [electron/electron#28157]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.1

### What operating system are you using?

Windows

### Operating System Version

10

### What arch are you using?

x64

### Expected Behavior

When `shell.openPath` is called with error path and from renderer thread, then it should show error dialog on top.

### Actual Behavior

`openPath` error dialog is minimized, so hard to spot for the user on Windows.

### Testcase Gist URL

https://gist.github.com/xmedeko/b2f8bca876f73f7c1269bd9b7c05d9ad

### Additional Information

Run the fiddle and press the "Open path" button. An error dialog is shown minimized in the Windows taskbar.

Change the code in `preload.js`: comment `shell.openPath(filePath)` and uncomment `ipcRenderer.send('app-open-path', filePath)`, so the `shell.openPath` is called from the main thread. Then, the error dialog shows on the top properly.

Note: Linux `shell.openPath` does not show any error dialog, it just returns error. It would be great, if Windows `openPath` would do the same.

**Comment by c3er** [comment]
This error is still in 13.0.1

**Comment by xmedeko** [comment]
Problem still in **v21.1.0**. 

Note: I have updated the Gist to enable `nodeIntegration: true`.

**Comment by xmedeko** [comment]
Opened new #37239 because this was auto-closed.
