### ISSUE TITLE
[Bug]: autoUpdater.checkForUpdates() throws "Can not find Squirrel" when app is installed on windows

### ISSUE THREAD

**Issue by randomgithubuser1** [electron/electron#28158]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise

### What arch are you using?

x64

### Expected Behavior

Auto updater should find squirrel when the app is packaged and installed on windows.

### Actual Behavior

autoUpdater.checkForUpdates() throws "Can not find Squirrel" when  app is packaged and installed on windows.

**Comment by sofianguy** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone test case with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by randomgithubuser1** [comment]
I am using electron-builder to create the build.

It looks like there is an option to use a squirrelWindows target but I am using the NSIS target because it says:
> "Squirrel.Windows target is maintained, but deprecated. Please use nsis instead."

I'm using the pattern described in this post: https://github.com/electron/electron/issues/5020#issuecomment-477636990

I download the update from a secure s3 bucket and save it to the local machine.
Then write a feed.json file and set feed url to a local filepath.

```
const { autoUpdater } = require('electron');
autoUpdater.setFeedURL( feedURL )
```

I think maybe I am confused by the different update methods on windows...  Since I build using the nsis target is that why it complains about missing squirrel?  Does the built in autoUpdater in electron not support updating nsis targets?

**Comment by fabiospampinato** [comment]
I think this should be addressed, it doesn't make a lot of sense to me that the auto updater throws.

**Comment by MarshallOfSound** [comment]
Electron builder is not an official project and is not accurate or correct.  Squirrel windows is the officially supported updating mechanism, nsis is unsupported
