### ISSUE TITLE
[Bug]: Unable to debug child processes

### ISSUE THREAD

**Issue by MRayermannMSFT** [electron/electron#28167]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

10.3.0

### What operating system are you using?

Other (specify below)

### Operating System Version

Windows and macOS

### What arch are you using?

x64

### Last Known Working Electron version

8.3.4

### Expected Behavior

I should be able to debug child processes them with the `--inspect` flag. 

### Actual Behavior

I cannot debug child processes them with the `--inspect` flag. 

### Testcase Gist URL

https://gist.github.com/MRayermannMSFT/a44d94c48dcf9155c0bdf462b2062481

### Additional Information

- I have tried using `--inspect`
- I have tried using `--inspect=[port]`
- I have tried using `--inspect-brk`
- I have tried using `--inspect-brk=[port]`
- I have tried on both macOS and Windows
- I have tried debugging with VS Code
- I have tried debugging with Chrome
- I have tried debugging with the Node CLI debugger

**Comment by deepak1556** [comment]
The inspect flag should be passed via `execArgv` so that the executable receives it.

`fork(filePath, {execArgv: ["--inspect=5888"]});`

**Comment by MRayermannMSFT** [comment]
That did indeed work.
