### ISSUE TITLE
Post form with “target” attribute sending GET request instead of POST

### ISSUE THREAD

**Issue by ValeryEliseev** [electron/electron#2816]
After submitting form with method='post' and target='_blank' (or target='windowname') Electron open new window with GET request instead of POST. Form data will not be sent.

For example, in main.js:
mainWindow.loadUrl('https://some.external.domain..../electron-submit.php');

electron-submit.php:

&lt;html&gt;
&lt;form method='post' id='form1' name='form1' target='_blank' action='electron-submit.php'&gt;
&lt;textarea id='data1' name='data1'&gt;Some text&lt;/textarea&gt;&lt;br&gt;
&lt;input type='submit' value='Submit'/&gt;
&lt;/form&gt;
&lt;?php echo $_SERVER['REQUEST_METHOD']; print_r($_POST); ?&gt;
&lt;/html&gt;

REQUEST_METHOD => GET
$_POST contains no data

PS. Similar issue in nw.js project
https://github.com/nwjs/nw.js/issues/3806

**Comment by deepak1556** [comment]
@zcbenz target attribute triggers `window.open` and our browser initiated navigation (`loadURL`) sends only GET request. We could generate the post data from form element and trigger a POST navigation with `loadURL`, would that be fine ?

**Comment by zcbenz** [comment]
> We could generate the post data from form element and trigger a POST navigation with loadURL, would that be fine ?

It sounds good to me if we can get the form data, but it seems that the content API didn't expose that?

**Comment by deepak1556** [comment]
yeah thats the problem, we have to work with `WebFormElement` to generate the post data.

**Comment by zcbenz** [comment]
The form data can be modified by JavaScript so reading `WebFormElement` is not reliable.

**Comment by deepak1556** [comment]
After some investigation, we do have a reliable source for extracting form request data and whole other information using the `WebFrame::provisionalDataSource` in `WillSubmitForm` event. But the problem we need to solve in our current architecture is how to pass one webframes' datasource to another newly created frame.
One solution is to set the opener of a frame in native side and during `LoadURL` first give renderer a chance for navigation (if it has POST data).
* guest.LoadURL
* Send IPC to renderer to give chance for POST navigation
* Get the opener of the frame and check if it has POST dataSource
* Use `WebFrame::Load` to navigate and return IPC result whether to continue browser navigation.

Any other implementaion ideas ?

**Comment by zcbenz** [comment]
We can probably add options for  `loadUrl` to send POST data, and then do al the things on browser side.

**Comment by deepak1556** [comment]
Initially statrted with this approach but there was a problem with handling POST data on browser side is, a `WebHTTPBody` gets [constructed](https://code.google.com/p/chromium/codesearch#chromium/src/content/renderer/render_frame_impl.cc&sq=package:chromium&l=4687&rcl=1444131269) for navigation request and it has a few different [types of data] (https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/public/platform/WebHTTPBody.h&sq=package:chromium&l=52&rcl=1444131269), currently `LoadURLParams.browser_initiated_post_data` are extracted into only one type [here](https://code.google.com/p/chromium/codesearch#chromium/src/content/browser/frame_host/navigation_entry_impl.cc&l=460&cl=GROK&gsn=ConstructCommonNavigationParams), this might be problem for file upload. So we might need to patch chromium to change the type of `browser_initiated_post_data` similar to the one in this quite old but relevant [CL](https://codereview.chromium.org/11193051/) which tries to handle cross process POST navigations. If patching the type is fine then can proceed with your suggestion.

**Comment by zcbenz** [comment]
Patching Chromium is not an one-off job, we have to maintain the patch when upgrading Chromium in future and it is not an easy work, so generally we should only patch Chromium when it is an urgent issue, or requested by many users. I think this issue may not deserver all the work for now.

A more maintainable way to fix this is to propose the patch to upstream Chromium and wait them to merge it, and then fix the problem in Electron.

**Comment by mkaz** [comment]
> We can probably add options for loadUrl to send POST data, and then do al the things on browser side.

:+1: this would be a useful option

**Comment by paulot** [comment]
+1 This would be very useful.

**Comment by dertuxmalwieder** [comment]
^ Any progress on that? I could need it.

**Comment by hackeram6** [comment]
+1 
A fix / workaround would be very helpful.

**Comment by jackyq2015** [comment]
+1. still no fix for this?

**Comment by syntien** [comment]
This is also a problem for the web app I'm responsible for. Would like to see a solution.

**Comment by kevinmprince** [comment]
I've been running into a similar issue. When I set the method="post" on a form with target="_blank", it ends up using GET instead. However when I set the target as a named frame such as target="foo", it makes the POST call as expected. This works fine outside of electron.
I've observed this with electron-prebuilt-compile 1.7.5 & 1.7.11

**Comment by psicounterman** [comment]
What is the status of this?  Exactly what did "webContents: handle POST navigation for new windows #7540" fix?

**Comment by evaughn** [comment]
This is still in issue. I'm working on a project using `1.8.8`. When creating a new named frame and setting the target to that named window, the POST still sends as a GET.

**Comment by shrknt** [comment]
Is this still an issue? When a new window is opened via form POST with target="_blank", will the new window open with POST request to the input URL with all the params (form data). Also, what is the behavior when the new-window event is explicitly handled, will form data (params) be available inside the event handler?

**Comment by coder963** [comment]
is this issue resolved?

**Comment by AdrianDroid** [comment]
no

**Comment by aarthofer** [comment]
is there a plan to fix this issue in any further release?
or is there something like a workaround?

**Comment by amigup** [comment]
Is there any update on this? Can this be fixed? Or is there a workaround for the problem?
