### ISSUE TITLE
[Bug]:  Dialogs on Windows 10 have insufficient left-padding for window title

### ISSUE THREAD

**Issue by mmis1000** [electron/electron#28180]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.3.0

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

There is sufficient padding on dialog titles.

### Actual Behavior

There is no padding on the left of dialog titles.
![No padding](https://user-images.githubusercontent.com/6561887/55820443-fc4a1180-5aaf-11e9-87b2-1c6d78b7fdda.png)

Use dialog.showMessageBox and see that Electron has no space to the left of the message box title.

This is a reopened old issue
https://github.com/electron/electron/issues/17736#issuecomment-794338626

**Comment by pushkin-** [comment]
repros in Electron 21

**Comment by mmis1000** [comment]
I believe the bug is still there

**Comment by pushkin-** [comment]
repros in v24

**Comment by pushkin-** [comment]
bump
