### ISSUE TITLE
[Bug]: Bluetooth requestDevice not working on 12.0.0/12.0.1

### ISSUE THREAD

**Issue by Inari-Whitebear** [electron/electron#28185]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.1

### What operating system are you using?

Windows

### Operating System Version

Version: Home 2004 / OS build: 19041.867

### What arch are you using?

x64

### Last Known Working Electron version

11.3.0

### Expected Behavior

`navigator.bluetooth.requestDevice({acceptAllDevices: true});` in a renderer JS file should trigger the `select-bluetooth-device` event registered in an electron/main JS file.

### Actual Behavior

Does not trigger the event.

### Testcase Gist URL

https://gist.github.com/910403defe0696032c1f5ccb1a9b1d7e

**Comment by jkleinsc** [comment]
@Inari-Whitebear can you go to https://googlechrome.github.io/samples/web-bluetooth/device-info.html?allDevices=true in either Chrome or Edge, select All Devices and then click on Get Bluetooth Device Info on your Windows Machine?  That should bring up a prompt to pick a bluetooth device.   Does that prompt say "No compatible devices found" or do you see a list of bluetooth device(s)?  There were changes made in Electron 12/Chromium 89 for Web Bluetooth and if there are no devices to return, `select-bluetooth-device` will not fire.

**Comment by Pign** [comment]
I do have an issue where select-bluetooth-device never gets triggered although I have devices that should be shown. This is on Windows 10 too.

**Comment by illysky** [comment]
I also have this issue. I can see the devices if I follow @Inari-Whitebear, but in my example app, I don't get any popup. 
Windows 10 also. : (

**Comment by mlynch** [comment]
Adding on to this, the link provided by @jkleinsc works great in Chrome and I see many devices, but in Electron running the latest nightly, `select-bluetooth-device` is never called on Windows 10. However, it *is* called on Mac OS.

**Comment by mlynch** [comment]
Here's a gist that shows the issue where `select-bluetooth-device` doesn't trigger on Windows 10: https://gist.github.com/7dd425b9027d463823cd674241380cdd

**Comment by jkleinsc** [comment]
@mlynch thanks for the update.  Out of curiosity what kind of device are you (or others on this thread) trying to connect to?  I want to do some of my own testing and I plan on testing against a bluetooth speaker but I was wondering what kind of devices folks are trying to connect to.

**Comment by mlynch** [comment]
@jkleinsc This test here I built a mini bluetooth device using an ESP32 microcontroller (happy to share source for that which works in the Arduino IDE if interested), but even just seeing the device list I should be seeing all the random bluetooth devices around me (like my bose headphones or Apple TV), which I see fine on Chrome but not in Electron. So you really don't need any special device to test this specific issue.

**Comment by bierzorutas** [comment]
Hi,
I dont think is the same case than the one has been given as reason to close.. 
For me is not been called the event 'select-bluetooth-device' even in the first call, it works in a website but not when built with electron, so USB device is not the reason.. 
And it works fine same code in MacOS, but not in Windows.
Electron Version 13.1.2

**Comment by piyushrathodIn** [comment]
> Hi,
> I dont think is the same case than the one has been given as reason to close..
> For me is not been called the event 'select-bluetooth-device' even in the first call, it works in a website but not when built with electron, so USB device is not the reason..
> And it works fine same code in MacOS, but not in Windows.
> Electron Version 13.1.2

Hi @bierzorutas, you need to upgrade Electron to ^13.1.3. They have recently resolved this issue for Windows.
