### ISSUE TITLE
[Bug]: A JavaScript error occurred in the main process, Error: The specified module could not be found.

### ISSUE THREAD

**Issue by alokmahor** [electron/electron#28181]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.1.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

My electron app which is using native module `obs-studio-node` should work

### Actual Behavior

On some computer electron app is working but on some computer I am getting error

```
A JavaScript error occurred in the main process
 
Uncaught Exception:
Error: The specified module could not be found.
\\?C:\some\path\My-Electron-App\node_modules\obs-studio-node\obs_studio_client.node
```
 I have checked it. `C:\some\path\My-Electron-App\node_modules\obs-studio-node\obs_studio_client.node` file is present.

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by alokmahor** [comment]
@nornagon Yes I posted this on Discord but did not get any reply.

**Comment by iceyxx222** [comment]
Have you solved this problem？I have the same problem。
