### ISSUE TITLE
[Bug]: MacOS shell.openExternal url hash encode

### ISSUE THREAD

**Issue by xqin** [electron/electron#28191]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.1

### What operating system are you using?

macOS

### Operating System Version

Darwin xxxx 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

### What arch are you using?

x64

### Last Known Working Electron version

i do not know

### Expected Behavior

open the correct url, like windows.

```
http://example.com/#/hello/world#ping
```

### Actual Behavior

```
http://example.com/#/hello/world%23ping
```

```
const {
  app,
  shell,
} = require('electron')


app.whenReady().then(() => {
  shell.openExternal("http://example.com/#/hello/world/#ping")

  setTimeout(() => {
    app.quit()
  }, 1000)
})
```

relate issue(maybe):

https://github.com/electron/electron/issues/3891
https://github.com/electron/electron/issues/2768

**Comment by xqin** [comment]
https://github.com/electron/electron/issues/2768#issuecomment-151381904

**Comment by Rokixy** [comment]
@xqin Hi, I got the same problem. Could you please share something about how you fix it?
