### ISSUE TITLE
[Bug]: webContents.print() fails on macOS with failureReason "no valid printers available"

### ISSUE THREAD

**Issue by caffeinatedbits** [electron/electron#28192]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.1

### What operating system are you using?

macOS

### Operating System Version

macOS Mojave 10.14.6

### What arch are you using?

x64

### Expected Behavior

Calling webContents.print() should show the system print dialog.

### Actual Behavior

Calling webContents.print() returns an error (via its callback, argument 2, failureReason) "no valid printers available" because I have no printers installed.

I have a BrowserWindow which contains "print" button, and multiple BrowserViews. I tried calling view.webContents.print() (where view == the currently active BrowserView) when the print button is clicked, however, because I have no printers installed, the callback is immediately called with success == false and failureReason == "no valid printers available".

I am aware of the following issues which have been closed **but not fixed**:

https://github.com/electron/electron/issues/25498
https://github.com/electron/electron/issues/24664

In the meantime, as a workaround, I am sending a message to the main script using ipcRenderer in the BrowserWindow preload script like so:

```
const { ipcRenderer } = require('electron');
ipcRenderer.send("print");
```

In the main script, I am listening for that message using ipcMain, and then redirecting it to the appropriate BrowserView using view.webContents.send() like so:

```
const { ipcMain } = require('electron');
let currentBrowserView; // stores reference to the currently active BrowserView
ipcMain.on("print", (event) => {
    currentBrowserView.webContents.send("print");
});
```

Finally, in the preload script for the BrowserView, I am listening for that message using ipcRenderer, and then calling window.print() like so:

```
const { ipcRenderer } = require('electron');
ipcRenderer.on("print", (event) => {
    window.print();
});
```

This gets me the system print dialog which, _despite not having any installed printers_, offers me additional macOS features such as: Open in Preview, Save as PDF, Save as PostScript, Send in Mail, Add to Apple Books, Send via Messages, Save to iCloud Drive, Save to Web Receipts, and Save to Adobe PDF. As I do not have a printer installed, all of these other options are the only way I have to achieve "print" capability.

Thus, I believe that BrowserView.webContents.print() should do the same thing as calling window.print() from within that BrowserView: show me my system print dialog even though I have no physical printers installed.

**Comment by CBMasri** [comment]
Alternative workaround without IPC:

```js
webContents.executeJavaScript('window.print()')
```

**Comment by bobber205** [comment]
@CBMasri This doesn't allow options like `webContents.print` does -- do you know of any workaround?
