### ISSUE TITLE
When does DesktopCapturer support hiding the mouse cursor?

### ISSUE THREAD

**Issue by Wlitsoft** [electron/electron#28194]
When does DesktopCapturer support hiding the mouse cursor?

**Comment by jkleinsc** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
