### ISSUE TITLE
[Bug]: Crash when Using mpv.js on Latest Version of Electron

### ISSUE THREAD

**Issue by NADESHIKON** [electron/electron#28200]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 2020

### What arch are you using?

x64

### Last Known Working Electron version

11.3.0

### Expected Behavior

The app works perfectly fine with an embedded video player.

### Actual Behavior

The app crashes when creating an element with an embedded video player.

### Testcase Gist URL

https://github.com/pavladan/mpv.js-on-react

Change the version of electron to 12.0.1 to see the crash, 11.3.0 works perfectly fine.

Note: In order to see the crash on 12.0.1, adjustments to the settings must be made
```
const win = new BrowserWindow({
    width: 1280,
    height: 574,
    autoHideMenuBar: true,
    useContentSize: process.platform !== "linux",
    title: "mpv.js example player",
    webPreferences: {
      nodeIntegration: true,
      plugins: true,
      enableRemoteModule: true,
      nodeIntegrationInSubFrames: true,
      contextIsolation: false,
      worldSafeExecuteJavaScript: false
    },
  });
```

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by NADESHIKON** [comment]
Sorry, I think merely a gist cannot actually reproduce the issue as mpv.js is a node.js binding.

**Comment by NADESHIKON** [comment]
To reduce your workload, I've created a sample repository that is able to reproduce the issue indicated.
https://github.com/NADESHIKON/electron-crash-reproduce

**Comment by nornagon** [comment]
Thanks @NADESHIKON, this is helpful! One more thing, could you collect a crash dump? Add the following to your minimized test case:

```js
const { app, crashReporter } = require('electron')

crashReporter.start({ submitURL: '', uploadToServer: false })
console.log(app.getPath('crashDumps'))
```

then reproduce the crash and check in the crash dumps directory. You should see a `.dmp` file in one of the subdirectories—please zip it up and attach it to this issue!

**Comment by NADESHIKON** [comment]
[be3f332f-6f4a-4200-b964-115a570e43af.zip](https://github.com/electron/electron/files/6152841/be3f332f-6f4a-4200-b964-115a570e43af.zip)

@nornagon Here you go.

**Comment by nornagon** [comment]
Thanks for that crash dump @NADESHIKON, that gives me everything I need to solve this issue :)

Here's the symbolicated stack trace:

```
Crash reason:  EXCEPTION_BREAKPOINT
Crash address: 0x7ff6d42e9bff
Process uptime: 1 seconds

Thread 9 (crashed)
 0  electron.exe!content::PluginServiceImpl::FindOrStartPpapiPluginProcess(int,url::Origin const &,base::FilePath const &,base::FilePath const &,base::Optional<url::Origin> const &) [plugin_service_impl.cc : 202 + 0x0]
    rax = 0x00000000000000ff   rdx = 0x00000001053fe720
    rcx = 0x00002254001a0000   rbx = 0x00000001053fe720
    rsi = 0x00000001053fe770   rdi = 0x000022540006e800
    rbp = 0x0000000000000004   rsp = 0x00000001053fe3d0
     r8 = 0x00002254000f8788    r9 = 0x0000000000000004
    r10 = 0x00002254000bb2d0   r11 = 0x00002254000b4e70
    r12 = 0x00000001053fe788   r13 = 0x00000001053fe770
    r14 = 0x00000001053fe788   r15 = 0x00002254000f8788
    rip = 0x00007ff6d42e9bff
    Found by: given as instruction pointer in context
 1  electron.exe!content::PluginServiceImpl::OpenChannelToPpapiPlugin(int,url::Origin const &,base::FilePath const &,base::FilePath const &,base::Optional<url::Origin> const &,content::PpapiPluginProcessHost::PluginClient *) [plugin_service_impl.cc : 245 + 0xa]
    rbx = 0x00000001053fe720   rbp = 0x0000000000000004
    rsp = 0x00000001053fe5e0   r12 = 0x00000001053fe788
    r13 = 0x00000001053fe770   r14 = 0x00000001053fe788
    r15 = 0x00002254000f8788   rip = 0x00007ff6d6e7406f
    Found by: call frame info
 2  electron.exe!content::RenderFrameMessageFilter::OnOpenChannelToPepperPlugin(url::Origin const &,base::FilePath const &,base::Optional<url::Origin> const &,IPC::Message *) [render_frame_message_filter.cc : 173 + 0x27]
    rbx = 0x00000001053fe720   rbp = 0x0000000000000004
    rsp = 0x00000001053fe640   r12 = 0x00000001053fe788
    r13 = 0x00000001053fe770   r14 = 0x00000001053fe788
    r15 = 0x00002254000f8788   rip = 0x00007ff6d6e930cd
    Found by: call frame info
 3  electron.exe!bool IPC::MessageT<FrameHostMsg_OpenChannelToPepperPlugin_Meta,std::tuple<url::Origin,base::FilePath,base::Optional<url::Origin> >,std::tuple<IPC::ChannelHandle,unsigned long,int> >::DispatchDelayReply<content::RenderFrameMessageFilter,void,void (content::RenderFrameMessageFilter::*)(const url::Origin &, const base::FilePath &, const base::Optional<url::Origin> &, IPC::Message *)>(const class IPC::Message *, class content::RenderFrameMessageFilter *, void *,  *) [ipc_message_templates.h : 223 + 0x1f]
    rbx = 0x00000001053fe720   rbp = 0x0000000000000004
    rsp = 0x00000001053fe6b0   r12 = 0x00000001053fe788
    r13 = 0x00000001053fe770   r14 = 0x00000001053fe788
    r15 = 0x00002254000f8788   rip = 0x00007ff6d42ebe0a
    Found by: call frame info
 4  electron.exe!content::RenderFrameMessageFilter::OnMessageReceived(IPC::Message const &) [render_frame_message_filter.cc : 121 + 0x4c]
    rbx = 0x00000001053fe720   rbp = 0x0000000000000004
    rsp = 0x00000001053fe830   r12 = 0x00000001053fe788
    r13 = 0x00000001053fe770   r14 = 0x00000001053fe788
    r15 = 0x00002254000f8788   rip = 0x00007ff6d6e92b89
    Found by: call frame info
[...]
```

That's a `CHECK` on this line: https://source.chromium.org/chromium/chromium/src/+/refs/tags/89.0.4389.82:content/browser/plugin_service_impl.cc;l=202

My best guess is that the actual `CHECK` being hit is in `origin_lock.value()` ([optional.h:648](https://source.chromium.org/chromium/chromium/src/+/refs/tags/89.0.4389.82:base/optional.h;l=648;drc=e6ae3b112e62e356133539114a1d78ce2c229dd4)), i.e. `origin_lock` is empty. This would be the case if `IsOriginIsolatedPepperPlugin` returned false ([render_frame_impl.cc:2687](https://source.chromium.org/chromium/chromium/src/+/refs/tags/89.0.4389.82:content/renderer/render_frame_impl.cc;l=2687;drc=e6ae3b112e62e356133539114a1d78ce2c229dd4)), which [is the case for everything except the PDF plugin](https://github.com/electron/electron/blob/fc7f2042ecb6bd43b39dd93649de0de736d4829a/shell/renderer/renderer_client_base.cc#L367). This code should only be getting hit if the plugin is [requesting the PDF permission](https://source.chromium.org/chromium/chromium/src/+/refs/tags/89.0.4389.82:content/browser/plugin_service_impl.cc;l=173;drc=37893bf803b256be100b1bd1805abcd069c33140), but I think [command-line plugins request all permissions](https://source.chromium.org/chromium/chromium/src/+/refs/tags/89.0.4389.82:content/common/pepper_plugin_list.cc;l=122;drc=7f5a8953f42e12194870ec6f0bf6d41c66663a36).

This change seems to have been introduced by https://source.chromium.org/chromium/chromium/src/+/37893bf803b256be100b1bd1805abcd069c33140, which states in the commit message:
> This change requires that FindOrStartPpapiPluginProcess always sees a
   non-null `origin_lock` - this is accomplished by isolating all
   non-NaCl plugins in IsOriginIsolatedPepperPlugin (also avoiding
   isolation in presence of the --ppapi-in-process switch used by some
   tests).

That change also started returning `true` from IsOriginIsolatedPepperPlugin for almost everything. We should probably follow suit.
