### ISSUE TITLE
[Bug]: console.log encoding problem

### ISSUE THREAD

**Issue by kot-shrodingera** [electron/electron#28204]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

output is "Тест"

### Actual Behavior

output is "╨в╨╡╤Б╤В"

I have installed powershell 7 and set it as deafult in VSCode
I have simple project with electron
`index.js` is my entry point and it contains only one line
`console.log('Тест')`
When I execute `node index.js` output is "Тест" as expected
When I execute `electron .` output is "╨в╨╡╤Б╤В"

**Comment by nornagon** [comment]
Related: https://github.com/electron/electron/issues/28079

**Comment by LongTengDao** [comment]
```
chcp 65001 | electron .
```

Thing will be right.

But I wonder why `node` do not need this...

**Comment by kot-shrodingera** [comment]
@LongTengDao yes, it helps. But it's strange that `chcp` is required every run. It really looks like some bug

**Comment by viiskies** [comment]
still experiencing same
