### ISSUE TITLE
[Bug]: BrowserWindow#loadURL() throw an error when I load same page with different location hash

### ISSUE THREAD

**Issue by eternalharvest** [electron/electron#28208]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.2.3

### What operating system are you using?

Other (specify below)

### Operating System Version

Windows10 Pro Version 1909 (Build 18363.1440), MacOS Big Sur 11.2.3 (20D91), Probably not depend on OS

### What arch are you using?

Other (specify below)

### Last Known Working Electron version

N/A

### Expected Behavior

BrowserWindow#loadURL() must finish without throwing any error

### Actual Behavior

BrowserWindow#loadURL() throw an error as below when load same page with different location hash

```
Error: ERR_FAILED (-2) loading 'asset:///test.html#section2'
    at rejectAndCleanup (electron/js2c/browser_init.js:205:1493)
    at Object.stopLoadingListener (electron/js2c/browser_init.js:205:1868)
    at Object.emit (events.js:327:22) {
  errno: -2,
  code: 'ERR_FAILED',
  url: 'asset:///test.html#section2'
}
```

### Testcase Gist URL

https://gist.github.com/eternalharvest/e6b26f8e20d3ebf6048bd50ef8c3eb63

It is not mentioned in the official document, it seems there is option `reloadIgnoringCache`.
And when I call loadURL method with option which reloadIgnoringCache set to true, It seems this error is not happen.

```javascript
// this code works correct (error is not happen)
mainWindow.loadURL('asset:///test.html#section2', { reloadIgnoringCache: true })
    .then(() => console.log('ok'))
    .catch(console.error);
```

Related Issues
* #24113

**Comment by nornagon** [comment]
Ah, I think this is because the `loadURL` promise handling expects either `did-finish-load` or `did-fail-load` to have been emitted before `did-stop-loading` is emitted, which doesn't happen for in-page navigations. We should be able to detect the in-page nature of the navigation and avoid emitting the error.

Relevant code: https://github.com/electron/electron/blob/da9261497eeaed116d84f460303f1872ae00cc9d/lib/browser/api/web-contents.ts#L452-L462

**Comment by lzdyes** [comment]
Can this problem be fixed?

**Comment by Rodeoclash** [comment]
I was tearing my hair out today with this bug getting Electron to play nicely with Keycloak. Does anybody have a workaround?

**Comment by Rodeoclash** [comment]
One very crude workaround is to trigger a reload from the main thread after the attempted redirect. This will at least load the intended page with the anchors on it.

**Comment by nbabanov** [comment]
I've just ran into the same error...
@MarshallOfSound Could you please have a look?

I reproduce it with Electron v16

**Comment by RecuencoJones** [comment]
Instead of calling `browserWindow.webContents.reloadIgnoringCache()` after getting `ERR_FAILED (-2)` I'm using `browserWindow.webContents.session.clearCache()` before `browserWindow.loadURL()` and it seems to work fine.
