### ISSUE TITLE
 [Bug]: The terminal will have a transparent background

### ISSUE THREAD

**Issue by qibing147147** [electron/electron#28211]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

9.4.3

### What operating system are you using?

macOS

### Operating System Version

macOS Catlina 10.15.7

### What arch are you using?

x64

### Expected Behavior

The window should not be transparent.

### Actual Behavior

It is easier to appear when the focus is not in the current window, and no transparent block will be seen in the Performance of Chrome’s Devtool, so I guess it’s a window problem, but I don’t know how to troubleshoot the problem.

![E335A650-D7D7-4C2A-A2FC-E5EF23FF48F2](https://user-images.githubusercontent.com/22902191/111277166-17960200-8673-11eb-8a21-f7cfd1ee4753.png)

**Comment by nornagon** [comment]
Hi, thanks for the bug report. Unfortunately I'm not sure what you mean—are you saying that the console section of the DevTools window is transparent? If so, I don't observe the same behavior on macOS 10.15.7. The console window looks opaque to me.

Does this behavior happen in a blank Electron app, e.g. the default [Electron Fiddle](/electron/fiddle) app or [electron-quick-start](/electron/electron-quick-start)?

**Comment by qibing147147** [comment]
> Hi, thanks for the bug report. Unfortunately I'm not sure what you mean—are you saying that the console section of the DevTools window is transparent? If so, I don't observe the same behavior on macOS 10.15.7. The console window looks opaque to me.
> 
> Does this behavior happen in a blank Electron app, e.g. the default [Electron Fiddle](/electron/fiddle) app or [electron-quick-start](/electron/electron-quick-start)?

Hello, thanks for the reply. As you can see in the picture, the black border part is our page, and the part that shows the Chrome Devtool transparently is caused by the form becoming transparent.
Our app is packaged based on the blank Electron App.

**Comment by nornagon** [comment]
Sorry, I still don't quite understand what I'm looking at in the picture 😅 

Did you make any modifications to the electron-quick-start app in order to trigger this behavior?

This is what devtools looks like on my machine (also macOS Catalina 10.15.7, using Electron 9.4.3). I don't see any transparent blocks.

![image](https://user-images.githubusercontent.com/172800/112035246-96b88980-8afc-11eb-82c0-0dd0f03bda1e.png)

**Comment by qibing147147** [comment]
Sorry, maybe I didn't describe it clearly, let me try to describe my problem again.
As shown in the figure, the blue part is our page, and a part is missing in the middle, which causes the Chrome Devtool to be exposed on the page. This is an occasional problem that occurs at runtime.
I used Performance to record the situation of my page, and then used the screen recording software to record the situation of my screen. Then I found that there was no missing piece in the page results recorded by Performance, but the browser window that hosted the page was missing one piece.
When a lot of software is opened on my computer, this phenomenon occurs particularly frequently, so I guess it is because the rendering ability of electron cannot carry my page, and I don't know how to solve it.
I don’t know if I have expressed my question clearly this time. Thank you very much for your attention to my question.
<img width="972" alt="3C443385-1F97-44D2-A307-29DE59CFB3F2" src="https://user-images.githubusercontent.com/22902191/112069204-61687600-8ba6-11eb-953a-470dc4d046c6.png">

**Comment by nornagon** [comment]
Does your app use transparent windows?

**Comment by qibing147147** [comment]
Yes, we use a transparent window on the macOS version. Is it because of this problem?

**Comment by qibing147147** [comment]
Our page will always accept the push of Websocket and update the table data. When the update is frequent and the CPU usage of the PC is relatively high, the following situations will occur. The following are three consecutive pictures. The first and third pictures are normal. The second picture is the problem I want to describe. Sometimes the entire Web page cannot be drawn completely. We have checked the problem that is not a Web page. , We suspect it is the problem of Electron’s Browser Window, but we don’t know how to troubleshoot the problem. Hope to help us.
![image](https://user-images.githubusercontent.com/22902191/119148367-fd1b4300-ba7e-11eb-928f-5c6ac6c9afb8.png)
![image](https://user-images.githubusercontent.com/22902191/119148396-06a4ab00-ba7f-11eb-8c4a-63449fdf0b70.png)
![image](https://user-images.githubusercontent.com/22902191/119148501-20de8900-ba7f-11eb-8b0a-a57d97bd50c1.png)
