### ISSUE TITLE
[Bug]: CSS cursor:pointer not work on window not focused

### ISSUE THREAD

**Issue by eternalharvest** [electron/electron#28210]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.2.3

### What operating system are you using?

macOS

### Operating System Version

MacOS Big Sur 11.2.3 (20D91)

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

N/A

### Expected Behavior

When hover on the element which style has `cursor` definition, change mouse cursor same as on windows machine.

### Actual Behavior

Mouse cursor is not changed when the window is not focused.

**Comment by nornagon** [comment]
This also doesn't happen with e.g. TextEdit, so I think this is an OS limitation.
