### ISSUE TITLE
[Bug]: BrowserView still has a hidden dragging area while y is non-zero

### ISSUE THREAD

**Issue by gucheen** [electron/electron#28228]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.x 13.x

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.2.2

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

12.x

### Expected Behavior

BrowserView with non-zero y bound setting should not being able to drag in the bottom area.

### Actual Behavior

If set BrowserView with bounds `{ x: 0, y: 40, width: 300, height: 100 }`.
This BrowserView will has a hidden dragging-area in its bottom.
Problem occurred while the `y` is non-zero.

### Testcase Gist URL

https://gist.github.com/c138020abbb7d949608c3c11b1cad253

As in https://github.com/electron/electron/issues/27884, the dragging problem in BrowserView still exists.
Have tested in v12.x and v13.x.
The dragging area is actually 2x of the BrowserView's `y` setting (red area in test case).

**Comment by codebytere** [comment]
@gucheen still looking into this but it looks like the css being handled incorrectly as drag regions somehow - if you just add `-webkit-app-region: no-drag;` to `.bottom` the issue goes away
