### ISSUE TITLE
[Bug]: Cannot find electron-navigation module

### ISSUE THREAD

**Issue by raulchiorean** [electron/electron#28232]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.1

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.2.3

### What arch are you using?

x64

### Expected Behavior

I should be able to install the electron-navigation module

### Actual Behavior

But when i npm i electron module, it says that the module is not found and it worked like 4 days ago

Don't know what to do

**Comment by itsananderson** [comment]
The `electron-navigation` package isn't an official Electron package. It looks like it was created by another developer who appears to have deleted the npm package and its repository 😦
