### ISSUE TITLE
[Bug]: On WSL, quick-start, npm start fails with "The futex facility returned an unexpected error code."

### ISSUE THREAD

**Issue by splashsky** [electron/electron#28244]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12,0,1

### What operating system are you using?

Other (specify below)

### Operating System Version

Windows 10 20H2, WSL-1 Ubuntu 20.04 LTS

### What arch are you using?

x64

### Expected Behavior

When running `npm start` per the quick start guide, I expected the Electron app to build and run.

### Actual Behavior

When executing `npm start` from the `electron-quick-start` repo, it fails with the error

```shell
The futex facility returned an unexpected error code.
/home/skylear/Projects/rodeo/node_modules/electron/dist/electron exited with signal SIGABRT
```

I attempted to get started with Electron with the following steps:

```shell
# Clone the quick start repo
git clone https://github.com/electron/electron-quick-start

# cd into the repo
cd electron-quick-start

# Attempt to run the project
npm start
```

but was met with

```shell
The futex facility returned an unexpected error code.
/home/skylear/Projects/rodeo/node_modules/electron/dist/electron exited with signal SIGABRT
```

I have installed Electron globally as well as locally to no success. I have deleted `node_modules` and `package_lock.json` and reran `npm i` to no success.

```shell
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

$ node --version
v15.11.0

$ npm --version
7.6.0

$ electron --version
v12.0.1
```

My Ubuntu is through WSL-1 on Windows 10 20HS, using the Windows Terminal Preview. I also tested using the kernel terminal (Ubuntu 20.04 LTS application) to no success.

I have seen issue #24211 and attempted the fixes outlined there, but it still isn't working - it produces the same error.

Any advice?

**Comment by Renesauve** [comment]
Running into this exact issue, any updates? :)

**Comment by akkad-abraham** [comment]
I can confirm the same issue on WSL-2 with same configurations as original issue.

**Comment by akkadaska** [comment]
If you use GUI on WSL2, X-Server is required.

Without X-Server, the same error occurred on my PC, but with X-server it works well.

There are some X-Server apps for WSL2 including free ones.
I use VcXsrv Windows X Server.

Microsoft announced that in the recent future, GUI is officially supported. [Announcement article here.](https://devblogs.microsoft.com/commandline/the-initial-preview-of-gui-app-support-is-now-available-for-the-windows-subsystem-for-linux-2/)

**Comment by iammati** [comment]
And I really thought I'd need to install / setup a X-Server now..
Just switched from Windows Terminal to Git Bash quickly, executed `npm run start` and guess what, it worked like a charm
