### ISSUE TITLE
[Feature Request]: topFrame attribute for iframes loaded in the main window (make iframes behave more like tabs).

### ISSUE THREAD

**Issue by mckravchyk** [electron/electron#28246]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

As we know, the WebView tag is not usable anymore. The only alternatives are iframes and BrowserView. The problem with BrowserView is that it's not possible to use it to build a rich UI with HTML/CSS the way it was possible with WebView.

Iframes can be a viable alternative to Webview in some cases. They don't have process isolation and isolated cookies, however, other than that they behave almost like a browser tab, with the contents being sandboxed.

There's a problem with iframes though, and that problem is that some websites deny being loaded in an iframe. While X-Frame-Origins header can be easily filtered out in an Electron app, there is secondary JavaScript validation that involves checking if `window.top !== window.self` or `window.top !== window`. So for example, if a website detects on the JS side that it's loaded in an iframe - it will not load.

### Proposed Solution

The proposed solution is to add a special argument i.e. topFrame="true". The JS runtime in these iframes would think it's the top window, thus any website will load 'thinking' it's loaded in a normal browser tab.

As for communication with the real parent frame, since it would not be possible to use `window.top` or `window.parent` for obvious reasons - a new property could be added to store it - i.e. `window.realParent` . (Of course, a website could check for this to bust the iframe - but they wouldn't have a strong reason to block it and/or even being aware of this niche feature in the first place).

### Alternatives Considered

I had this working with a Chrome extension. The idea was to inject a content script very early (for Chrome it's `document_start`) and run: `self = top; parent = top;`  I'm not sure, but it's probably possible to do something like this with Electron API as well.

Most websites check `top !== parent` or `top !== self`, so this hack can cover many websites - but it wouldn't prevent a `top !== window` - both `window.top` and `window` are impossible to override. E.g. Facebook works with this, Slack doesn't work.

### Additional Information

This feature would be only available when the iframe is embedded directly in BrowserWindow or BrowserView. An additional consideration is ensuring that the attribute cannot be invoked by a remote website loaded in BrowserView. E.g. limit usage only to local file URLs, or (if possible) provide means to invoke the iframe only by mechanism exclusive to the desktop app - so a remote page cannot invoke it by itself.

**Comment by issacgerges** [comment]
👋🏼 Hey @mckravchyk. 

I've wondered about something like this as well! I think I would worry about exposing something like `realParent` since, as you said, it could be used to circumvent some intentional security boundaries. I'm sure the obscurity of that property name would prevent a lot of use, but I'd be more worried it could be targeted maliciously. I'd be curious if node enabled preloads and the ability to `executeJavascript` would be enough to avoid needing actual access to a `realParent`. Also would be curious if you'd expect control in the other direction, I believe you'd be cross domain limited from calling forward/back from JS as the frame parent (since the domain may differ)

**Comment by mckravchyk** [comment]
Hi @issacgerges,

that's a good idea about injecting a script to get the reference to the real frame, then there would be no need to add `realParent`.

We can communicate cross-domain using `window.postMessage`.

On another note, as for security - obviously, iframes provide much less isolation than BrowserView. However, one can create an app in a BrowserWindow or BrowserView with nodeIntegration disabled that has these iframes to display remote content. In the event of a security bug where iframe sandbox could be broken - the filesystem would still be protected by the isolation of BrowserWindow / BrowserView. The only bad scenario would be if the security bug allowed an attacker to get credentials/cookies from a sibling iframe - however, as iframes are a core feature of Chrome - such a scenario is not very likely.

**Comment by nornagon** [comment]
This should be doable with a preload script; support from Electron itself isn't required.

> iframes provide much less isolation than BrowserView

I'm not sure what you're getting at here, but cross-origin iframes are loaded in a separate process (known as "OOPIF", or out-of-process iframes), so they're just as isolated as a BrowserView from an OS perspective.

I'm going to close this as I don't think it needs support from Electron core to implement.
