### ISSUE TITLE
[Feature Request]: Electron should use dns.lookup with verbatim=true for IPv6 compatibility

### ISSUE THREAD

**Issue by treysis** [electron/electron#28254]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Can't connect to IPv6 hosts if A record exists.

### Proposed Solution

Set `verbatim=true` for NodeJS' `dns.lookup`

### Alternatives Considered

No alternatives. IPv6 is the future.

### Additional Information

We need to push IPv6 adoption.

**Comment by nornagon** [comment]
This sounds like an issue that should be raised with Node.JS.

**Comment by treysis** [comment]
Nah, it will be changed to `true` by default at some point. But to move forward projects should already do it themselves.
