### ISSUE TITLE
[Bug]: setImmediate does not make a new task

### ISSUE THREAD

**Issue by aslushnikov** [electron/electron#28261]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

macOS

### Operating System Version

macos catalina 10.15.7

### What arch are you using?

x64

### Expected Behavior

Run the following snippet in renderer process with Node.js enabled:

```js
let resolve;
const promise = new Promise(x => resolve = x);
promise.then(() => console.log('task1: promise resolved'));

setImmediate(() => {
  console.log('task1: setimmediate');
  resolve();
});
setImmediate(() => console.log('task2: setimmediate'));
```

In Node.js v14, this returns the following - and this is **EXPECTED BEHAVIOR**:

```
task1: setimmediate
task1: promise resolved
task2: setimmediate
```

### Actual Behavior

In electron v12 in renderer process with node.js and context isolation disabled, this returns the following:

```
task1: setimmediate
task2: setimmediate
task1: promise resolved
```

### Testcase Gist URL

~~https://gist.github.com/aslushnikov/ab5045bf485389136e03e72360bcae33~~
https://gist.github.com/codebytere/6dbecc4f8e142e893454f8fe9d07cb6c

**Comment by codebytere** [comment]
@aslushnikov ty for the gist but typically what we mean is a gist that you can load and run in Fiddle - like this: https://gist.github.com/codebytere/6dbecc4f8e142e893454f8fe9d07cb6c

**Comment by aslushnikov** [comment]
@codebytere ooops sorry, I wasn't sure and was in a hurry to file this. Thank you for helping out with the gist! I updated issue description

**Comment by pisal-rath** [comment]
i really don't understand all of you have problems with my account what is
going on please tell me reason i'm really tried to protected it we never
know each other before i don't my account have in your team kindly removed
my account from your team i don't to play like that i'm really really tried
please stop. are you happy for play that don't try looking down yourself
coz my date i hope you understand thank you for your game ๅ

**Comment by codebytere** [comment]
@aslushnikov this is fixed by https://github.com/electron/electron/commit/a4c590e2883870a507692b10a8a2bfb6645a2fca starting in v12.0.7 :D
