### ISSUE TITLE
[Bug]: window.close from inside a page in a BrowserView will close the entire window

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#28260]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 v1909

### What arch are you using?

x64

### Expected Behavior

when executing window.close() in web page in a BrowserView, the window won't close.

### Actual Behavior

The window is closed

This is a continuation of [this closed issue](https://github.com/electron/electron/issues/19194)

1. run main.js
2. execute `window.close()` inside of web page's devtools
3. observe that the window closes

main.js:
```
(async () => {
	const { app, BrowserWindow, BrowserView } = require("electron");
	app.on("window-all-closed", async () => {
		app.quit();
	});

	await app.whenReady();
	const mainWindow = new BrowserWindow();
	const view = new BrowserView();
	view.setBounds({x: 0, y: 0, width: 800, height: 600});
	mainWindow.setBrowserView(view);

	await view.webContents.loadURL("https://google.com");
	view.webContents.openDevTools();
})();
```

Some notes form the closed issue:

>I think the issue is that if you have a BrowserWindow with a BrowserView attached to it, calling window.close from inside the view will close the parent window, which isn't what I would expect to happen. Since the close event on BrowserWindow doesn't provide a way to tell whether the window itself or just the view is closing, there's no way to prevent this behavior without also making it impossible to close the window.

>I think the expected behavior would be that calling close() from inside a BrowserView doesn't do anything to the window, and the view would emit a close event to let you destroy the view (like how webviews work).

[This PR](https://github.com/electron/electron/pull/19813) was opened to address this but never landed.

**Comment by pushkin-** [comment]
The secondary issue in the close issue mentions something about `onbeforeunload` not firing when in the BrowserView. I have this separate [issue](https://github.com/electron/electron/issues/27722) for that, which may or may not be a dupe. Though now I wonder if that issue is really just a consequence of [this issue](https://github.com/electron/electron/issues/20746)

**Comment by pushkin-** [comment]
It looks like (at least as of Electron 16.0.4), the window doesn't close if the `BrowserView` is configured with `sandbox: true`

**Comment by sohobloo** [comment]
I have the same issue as I use BrowserView to build a chrome-like tab-browser-window. The BrowserWindow closed, which is unexpected, when `window.close` is called on that web contents.

**Comment by pushkin-** [comment]
repros with Electron 21. But note my [comment](https://github.com/electron/electron/issues/28260#issuecomment-990043355)

**Comment by pushkin-** [comment]
seems like the webcontents will now close correctly when sandbox is true or false.
