### ISSUE TITLE
[Bug]: child_process execFile performance on macOS degraded

### ISSUE THREAD

**Issue by larssvensby** [electron/electron#28269]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.1

### What operating system are you using?

macOS

### Operating System Version

macOs Big Sur 11.2.3

### What arch are you using?

x64

### Last Known Working Electron version

11.3.0

### Expected Behavior

In development mode.
If I call require('child_process').execFile("df", ["-h"]) multiple times, it should return quickly.
Same with other commands like execFile("cd", ["."])

Expect to be similar performance as Node or at least as Electron 11.3.0

### Actual Behavior

If run multiple times (either async/await or in parallel) on OSX & Electron 12.0.1 performance has degraded since Electron 11.3.0.
We don't see this problem on Windows.

In our real-world case in which we only do a single execFile("df", ["-h"]) call it can take as long as 2s, compared to ~25 ms in 11.3.0.
It seems related to app size since the difference wasn't as noticeable with only one call in the gist template. 

### Testcase Gist URL

https://gist.github.com/larssvensby/34fdb3297716533a591010f5d519e031

I don't think it's related to https://github.com/electron/electron/issues/26143 since this is in development mode.

Some measures (using attached gist), 5 calls (time per call)
**Electron  12.0.1**
Main (Parallel): 413 - 1674 ms
Main (async/await): 278 - 453 ms
Renderer (Parallel): 325 - 1486 ms
Renderer (async/await): 270 - 354 ms
Total time for 5 calls is about the same for parallel & async/await.
Renderer and main are similar.

**Electron  11.3.0**
Main (Parallel): 259 -279 ms
Main (async/await): 8 - 363 ms
Renderer (Parallel): 23 - 35 ms
Renderer (async/await): 3 - 24 ms
Renderer is faster than main, much faster than 12.0.1

**Node  14.16.0**
Parallel: 10 - 18 ms
async/await: 2 - 11 ms
Node is much faster

**Comment by marcello3d** [comment]
It's likely this is related to #26143. We determined that (then nightly) Electron 12 had the same bug in the main process: https://github.com/electron/electron/issues/26143#issuecomment-729393664

Running the patched electron resolves the issue for us

**Comment by deepak1556** [comment]
The memory allocator in the main process was switched to match the renderer process with versions > 12 https://github.com/electron/electron/pull/26331. The root issue is same https://github.com/electron/electron/issues/26143, merging to it.
