### ISSUE TITLE
[Bug]: webview with nodeintegration can not work

### ISSUE THREAD

**Issue by jackple** [electron/electron#28267]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.1

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina 10.15.7

### What arch are you using?

x64

### Expected Behavior

alert `function`

### Actual Behavior

alert `function`

When I set the attribute `webpreferences="contextIsolation=no"`, it will alert `function`

### Testcase Gist URL

https://github.com/jackple/electron-quick-start

```
<webview id="webview" nodeintegration></webview>
```
```
alert(typeof require)
```
Can not use `require`

**Comment by nornagon** [comment]
This is intended behavior. https://www.electronjs.org/docs/breaking-changes#default-changed-contextisolation-defaults-to-true
