### ISSUE TITLE
[Bug]: setInterval is inconsistent with chrome when document.visibilityState is hidden

### ISSUE THREAD

**Issue by replace5** [electron/electron#28293]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.2.1

### What operating system are you using?

macOS

### Operating System Version

MacOs Catalina 10.15.7

### What arch are you using?

x64

### Expected Behavior

Consistent with chrome

### Actual Behavior

setInterval inconsistent with chrome

run code in devtools 
`var a = Date.now()
setInterval(() => {console.log(Date.now() - a, document.visibilityState); a= Date.now()}, 1e3)`
chrome tab(not front), the log:
![image](https://user-images.githubusercontent.com/3085490/111780085-e24b1780-88f1-11eb-9f98-b894be8b41d3.png)
electron render process minimize, the log: 
![image](https://user-images.githubusercontent.com/3085490/111780145-f1ca6080-88f1-11eb-9fe7-4372ff42e231.png)

**Comment by Prinzhorn** [comment]
Maybe the `backgroundThrottling` option is what you're looking for https://www.electronjs.org/docs/api/browser-window

**Comment by replace5** [comment]
@Prinzhorn not BrowserWindow, my app renderer process has many webview，it likes chrome tab，when I set webview hidden, webview will not throttling  setInterval，even if I minimize the window, setInterval always different from chrome
