### ISSUE TITLE
The 'ready-to-show' event is not triggered under MacOS

### ISSUE THREAD

**Issue by bromix** [electron/electron#28290]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.3.0

### What operating system are you using?

macOS

### Operating System Version

Big Sur 11.2.1

### What arch are you using?

x64

### Last Known Working Electron version

9.4.3

### Expected Behavior

The 'ready-to-show' should be be triggered.

### Actual Behavior

The event 'ready-to-show' is not triggered under MacOS (Windows 10 and Unbuntu Mate is working).

### Additional Information

We are working on a project for more than a year and used the example from the electron page [Using ready-to-show event](https://www.electronjs.org/docs/api/browser-window#using-ready-to-show-event). With Electron 9.X it worked with Windows, Ubuntu Mate (18.X) and MacOS. But since we upgraded to electron 11.3.0 this isn't the case anymore. Under MacOS the event is never triggered. Only Windows 10 and Linux are working right now for us.

### To Reproduce

```
win = new BrowserWindow({
minWidth: 970,
    minHeight: 620,
    width: 1280,
    height: 800,
    show: false,
    frame: false,
    resizable: true,});
win.once('ready-to-show', () => {
        console.log('ready-to-show is called');
        win.show();
   });
```

**Comment by ShlomiRex** [comment]
I have mac 2020 intel big sur and it works for me
maybe it's related to M1 chip? although i doubt it

**Comment by eternalharvest** [comment]
@bromix

I don't think this behavior is not a bug of electron.
You need to call `BrowserWindow#loadURL()` so that window triggers `ready-to-show` event.

**Comment by bromix** [comment]
I am aware that I also have to call Load ;) that was also just a simplified example. But the problem exists on 2 of our developer systems and did not happen with version 9 of Electron.

But here otherwise an example project:
[vue-electron-app](https://github.com/bromix/vue-electron-app/tree/bug-ready-to-show)
Branch:  **bug-ready-to-show**

**Comment by eternalharvest** [comment]
I wrote a simple test case below.

```javascript
const { app, BrowserWindow } = require('electron');

app.whenReady()
.then(() => {
	const win = new BrowserWindow({
		show: false,
		frame: false,
		resizable: true,
	});
	win.once('ready-to-show', () => {
		console.log(`It's works! on ${process.platform}-${process.arch}`, app.runningUnderRosettaTranslation);
		app.quit();
	});
	win.loadURL('about:blank');
});
```

And when I run this test case in my environments it returns following results.

```
It's works! on darwin-x64 with Rosetta
```

```
It's works! on win32-x64
```

I'm not sure about MacOS Intel without Rosetta or any other environment.
I hope this helps debugging this issue.

**Comment by ckerr** [comment]
@bromix, I'm trying to nail down exactly what to test and on what platform. Can you run @eternalharvest's testcase on the system you're seeing this issue on (Big Sur 11.2.1 + Electron 11.3.0) and report back what you get?

@eternalharvest thank you for writing a standalone testcase. https://github.com/bromix/vue-electron-app/tree/bug-ready-to-show involves more third-party code and so I'd prefer to test with your standalone :D

**Comment by ckerr** [comment]
Gist of @eternalharvest's testcase:

https://gist.github.com/493110ec8941e45e22caa5bd76d8850c

**Comment by bromix** [comment]
The branch **bug-ready-to-show** [vue-electron-app](https://github.com/bromix/vue-electron-app/tree/bug-ready-to-show) is ready for debugging. The settings for vscode are in there. After _npm install_ you can start debugging by pressing F5 in vscode. I have to admit, I wouldn't know how to start the project (from gist) in JavaScript with Electron.

**Comment by bromix** [comment]
Good news. We just updated to electron-11.4.0 and on both of our MacOS development systems everything works as bevor. The only thing we can think of is if this PR https://github.com/electron/electron/pull/27987 is responsible for the fix. Because we use a frameless window and make use of a draggable region to move the window. One of our developer mentioned that dragging never work in electron-9.X.X and 11.3.0 for him on MacOS, but know works with 11.4.0.
