### ISSUE TITLE
[Bug]: <template> in html electron not working

### ISSUE THREAD

**Issue by ShlomiRex** [electron/electron#28304]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

v11.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

<template> tag element should work

### Actual Behavior

<template> tag element not working

Just a simple example:
```
	<template id="template_test">
		<p>
			Test
		</p>
	</template>
```

And then I want to use the template:
```
<template_test></template_test>
```

But it doesn't show anything. By looking at the chrome dev tools, the element is empty, with dimensions 0.

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by ShlomiRex** [comment]
Never mind, template is dynamically used, not statically. I'm dumb
