### ISSUE TITLE
[Bug]: nodeIntegration : true not working on 12.0.1

### ISSUE THREAD

**Issue by PennyroyalTea** [electron/electron#28300]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.1

### What operating system are you using?

macOS

### Operating System Version

macOS catalina

### What arch are you using?

x64

### Last Known Working Electron version

11.2.3

### Expected Behavior

When button is clicked, alert "Hi" appears

### Actual Behavior

When button is clicked, nothing happens. Debugging console shows error "Uncaught ReferenceError: require is not defined"

### Testcase Gist URL

https://gist.github.com/cbc1dc8bbd99674b1d3f9a3b90cb3a06

I'm running simple script in Electron Fiddle to test node.js environment access from webpage. 

It works as expected on Electron v11.2.3, but on Electron v.12.0.1 node.js doesn't work on webpage context even though `nodeIntegration: true` property is set. In fact, even default electron fiddle sample code won't work on this version -- versions of Node.js, Chromium and Electron don't show.

Sample page on electron 11.2.3:
<img width="207" alt="Снимок экрана 2021-03-19 в 18 39 36" src="https://user-images.githubusercontent.com/27580209/111805837-757c5100-88e2-11eb-99f0-0f9df40c17a3.png">

Sample page on electron 12.0.1:
<img width="240" alt="Снимок экрана 2021-03-19 в 18 41 50" src="https://user-images.githubusercontent.com/27580209/111806182-c68c4500-88e2-11eb-9dca-2062ff21663a.png">

**Comment by pushkin-** [comment]
see [this](https://github.com/electron/electron/issues/28034). ContextIsolation is now enabled by default which is causing node to be off
