### ISSUE TITLE
[Bug]: icudtl.dat not found

### ISSUE THREAD

**Issue by mindfullsilence** [electron/electron#28308]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.1

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina 10.15.5 (19F101)

### What arch are you using?

x64

### Expected Behavior

Running `electron-forge start` (`npm start`) should open a new electron window. Using boilerplate electron forge app with no additional code (just started the project).

### Actual Behavior

Command provides following output:
```
✔ Checking your system
✔ Locating Application
✔ Preparing native dependencies
✔ Launching Application
```
But no window is opened.

Running the command: `electron-forge start --enable-logging`
Produces the following output:
```
✔ Checking your system
✔ Locating Application
✔ Preparing native dependencies
✔ Launching Application
[20188:0319/190524.475118:ERROR:icu_util.cc(178)] icudtl.dat not found in bundle
[20188:0319/190524.475194:ERROR:icu_util.cc(242)] Invalid file descriptor to ICU data received.
```

Though I'm setting up an electron-forge scaffolding, this issue appears to be related more to electron and chromeum so posting here. If this is not an electron issue, let me know and I'll instead request help on electron-forge repo.

**Comment by codebytere** [comment]
@mindfullsilence is this a deterministic issue? i'm not able to reproduce it with the information you've provided, running:

```sh
$ yarn create electron-app my-app
$ cd my-app
$ yarn start -- --enable-logging
```

**Comment by mindfullsilence** [comment]
@codebytere Looks like my assumption was wrong. Running `electron .` works as expected, so it's something specific to the electron-forge command. I'll move this issue over to the appropriate repository.
