### ISSUE TITLE
[Bug]: "disable-site-isolation-trials" Causes Chrome & Devtools Extensions No Longer Working

### ISSUE THREAD

**Issue by NADESHIKON** [electron/electron#28316]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 2020

### What arch are you using?

x64

### Last Known Working Electron version

None

### Expected Behavior

Extensions load correctly even with 
``app.commandLine.appendSwitch('disable-site-isolation-trials');``

### Actual Behavior

When loading an extension, electron throws an error and those extensions ended up not loading correctly
```[140992:0320/215701.392:ERROR:CONSOLE(0)] "Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.", source: chrome-extension://hgmoikfalepijdjkkfjegcabhmeapdin/main.html (0)
[140992:0320/215701.399:ERROR:CONSOLE(36402)] "Uncaught Error: Attempting to use a disconnected port object", source: chrome-extension://hgmoikfalepijdjkkfjegcabhmeapdin/build/main.js (36402)
[140992:0320/215701.416:ERROR:CONSOLE(36402)] "Uncaught Error: Attempting to use a disconnected port object", source: chrome-extension://hgmoikfalepijdjkkfjegcabhmeapdin/build/main.js (36402)
[140992:0320/215708.040:ERROR:CONSOLE(36402)] "Uncaught Error: Attempting to use a disconnected port object", source: chrome-extension://hgmoikfalepijdjkkfjegcabhmeapdin/build/main.js (36402)
```

**Comment by NADESHIKON** [comment]
Uhh.. Bump

**Comment by phablulo** [comment]
I'm having the same issue with version 16.0

**Comment by dtychshenko** [comment]
We're still having this issue using Electron 22.3.15. What I've found is that there is a way to get the extensions to work without removing the `disable-site-isolation-trials` or the `nodeIntegration` flags. For anyone still experiencing this problem, you can try this:
```typescript
app.commnadLine.appendSwitch('enable-features', 'ProcessSharingWithDefaultSiteInstances')
```
However, there's not a lot of information about this feature, so I'm not sure if it could have any unintended side-effects.
