### ISSUE TITLE
[Bug]: Cannot access webview preload globals from page

### ISSUE THREAD

**Issue by theArina** [electron/electron#28317]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 19042.867

### What arch are you using?

x64

### Last Known Working Electron version

11.0.0

### Expected Behavior

Preload globals are accessible from page.

### Actual Behavior

Preload globals are not accessible from page.

### Testcase Gist URL

https://gist.github.com/theArina/3956d7ef31119559d4219ade2bc4cd74

I've upgraded to v12 from v11.
I've read about [changes](https://www.electronjs.org/releases/stable#breaking-changes) and assumed that setting `contextIsolation` explicitly to `false` will solve the issue, but the issue remains. 

In my gist try to access the property `preloadTest` of a `window` manually, you will see that it is `undefined` instead of an actual value that I've set. I was able to do that in v11 and earlier.

**Comment by codebytere** [comment]
@theArina im not able to reproduce with the above code:

<img width="1183" alt="Screen Shot 2021-03-22 at 11 35 24 AM" src="https://user-images.githubusercontent.com/2036040/111977158-ae255180-8abf-11eb-98bf-e5797cd30f44.png">

**Comment by theArina** [comment]
@codebytere, hello, thank you for the answer. I noted in the description that you need to access `window.preloadTest` manually after. The log you are seeing is a log from preload itself that demonstrates that this property accessible from preload (but I need to access it from the page after).

**Comment by codebytere** [comment]
@theArina can you please update the gist to reflect the actual bug then? Also - you need to name `index.js` -> `main.js` for it to load properly in Fiddle

**Comment by theArina** [comment]
@codebytere, here you go. I've updated my gist and this is what I get in log:

![image](https://user-images.githubusercontent.com/32187787/111981845-48fe4a00-8b19-11eb-90d4-f578e91a05a5.png)

**Comment by codebytere** [comment]
This is not a bug - this is a consequence of the default change. You will now need to explicitly enable it on the webview too -

**Comment by MarshallOfSound** [comment]
Instead of disabling context isolation, please read our documentation to understand why it's so important you leave it enabled and use the contextBridge to expose your API.

For example in your case

```
// In your preload script
const { contextBridge } = require('electron')

contextBridge.exposeInMainWorld('preloadTest', 'hello')
```

**Comment by stclairdaniel** [comment]
> This is not a bug - this is a consequence of the default change. You will now need to explicitly enable it on the webview too:
> 
> ```
> <webview
>     src="about:blank"
>     preload="preload.js"
>     nodeintegrationinsubframes="true"
>     webpreferences="contextIsolation=no"
> />
> ```

Thank you. This just ended about eight hours of frustration after upgrading to Electron 12





> Instead of disabling context isolation, please read our documentation to understand why it's so important you leave it enabled and use the contextBridge to expose your API.
> 
> For example in your case
> 
> ```
> // In your preload script
> const { contextBridge } = require('electron')
> 
> contextBridge.exposeInMainWorld('preloadTest', 'hello')
> ```

I could not get this to work - I get an error that `window.require` is not a function in my renderer process.
