### ISSUE TITLE
[Bug]: Focus of the window lost after selection with Alt keyword pressed

### ISSUE THREAD

**Issue by ficristo** [electron/electron#28314]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 2004

### What arch are you using?

x64

### Last Known Working Electron version

4.x

### Expected Behavior

When you use mouse to select something with Alt key pressed the focus should remain in the window.

### Actual Behavior

The focus goes to the menubar.

### Testcase Gist URL

https://github.com/electron/electron-quick-start

This is basically same bug reported in https://github.com/electron/electron/issues/18151 and https://github.com/electron/electron/issues/26149

**Comment by pushkin-** [comment]
Isn't it expected that pressing Alt focuses the menu bar? That's how it works in other applications. What do you expect pressing "Alt" would do?

**Comment by ficristo** [comment]
If you press only <kbd>Alt</kbd> you are right. But if you press <kbd>Alt</kbd> + mouse click the focus should remain in the Window without opening the menu bar.

**Comment by zcbenz** [comment]
This is a duplicate of https://github.com/electron/electron/issues/26154.

**Comment by andersk** [comment]
@zcbenz #26154 was reported on Linux, and I can confirm it was fixed on Linux by #29318 between 14.0.0-beta.2 and 14.0.0-beta.3.

However, this report is on Windows 10, and still reproduces on Windows 10 in every version I tested, including 14.0.0-beta.3, 22.0.3, 23.0.0-beta.5, and 24.0.0-nightly.20230124. Can you please reopen this?

**Comment by zcbenz** [comment]
@andersk I'm unable to reproduce this.

In the video below, I did:
1. Press and release Alt
2. Press Alt, select text, and then release Alt
3. Press and release Alt

https://user-images.githubusercontent.com/639601/214815509-f326cd3a-e8c5-4707-b871-84fe2588e86a.mov

It seems that Alt can only focus on main menu when I did no mouse clicking.

**Comment by andersk** [comment]
Okay, but I can still reproduce. Here I’m just doing press Alt, select text, release Alt:

https://user-images.githubusercontent.com/26471/217166735-c6773e46-99a5-4dbe-b18a-c2a0b504315c.mp4

This is on Windows 10 22H2 19045.2486. I can also reproduce on Windows 11 22H2 22621.1194.

@zcbenz Can you reopen this in any case? Thanks!

**Comment by zcbenz** [comment]
@andersk What is your keyboard layout?

**Comment by andersk** [comment]
English US QWERTY. (If I switch to English United States–International QWERTY, I can reproduce using the left Alt key.)

**Comment by andersk** [comment]
Still reproduces on Windows with Electron 24.2.0, 25.0.0-beta.3, and 26.0.0-nightly.20230508.

**Comment by andersk** [comment]
Still reproduces on Windows with Electron 25.5.0, 26.0.0-beta.12, and 27.0.0-nightly.20230808.

**Comment by andersk** [comment]
Still reproduces on Windows with Electron 27.0.4, 28.0.0-beta.4, and 29.0.0-nightly.20231110.
