### ISSUE TITLE
[Bug]: Window height cannot be lower than 39 on Windows

### ISSUE THREAD

**Issue by virtuecoder** [electron/electron#28320]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.2.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Enterprise 1809

### What arch are you using?

x64

### Expected Behavior

Should be able to set window height below 39

### Actual Behavior

Window height becomes 39 when setting it to 25

### Testcase Gist URL

https://gist.github.com/virtuecoder/a5ede415619b4b75ea41c8c386e1f9dc

**Comment by codebytere** [comment]
This is not an issue with Electron - see https://github.com/electron/electron/issues/5053.

**Comment by virtuecoder** [comment]
The person who closed #5053 explained that you can set the size of the window after creation to less than 39 height with `setSize` however in the repro that I created `win.setSize(400, 25)` does not work.
