### ISSUE TITLE
[Bug]: Opening a file opens a new window instead of a tab when the app is in full-screen mode

### ISSUE THREAD

**Issue by RA80533** [electron/electron#28323]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.3.0

### What operating system are you using?

macOS

### Operating System Version

macOS 10.14.6

### What arch are you using?

x64

#### Preconditions

- In full-screen mode
- Contains an opened document
- Window not in focus

1. *Preconditions are met*
2. An additional document is opened
3. A new tab is created in the full-screen window for the opened document

#### Preconditions

- In full-screen mode
- Contains an opened document
- Window not in focus

1. *Preconditions are met*
2. An additional document is opened
3. A new window is created for the opened document

Related #9094
Related microsoft/vscode#115469

**Comment by codebytere** [comment]
@RA80533 please add a Fiddle testcase. This makes it easier for us to triage your issue in a timely manner.

**Comment by codebytere** [comment]
Closed as no response was provided.
