### ISSUE TITLE
[Bug]: "Uncaught Error:" added to message of errors thrown in a function defined in preload script

### ISSUE THREAD

**Issue by raksooo** [electron/electron#28327]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.1

### What operating system are you using?

macOS

### Operating System Version

11.2

### What arch are you using?

x64

### Expected Behavior

`error.message` shouldn't be prefixed with "Uncaught Error:"

### Actual Behavior

`error.message` is prefixed with "Uncaught Error:" when an error is thrown in a function defined in the preload script and caught in the renderer process. This only happens when `contextIsolation` is enabled.

### Testcase Gist URL

https://gist.github.com/f11c77f9bc2cbf98d42a9fcaf477c80a

**Comment by codebytere** [comment]
This is probably related to the fact that Errors aren't serializable at present over the `contextBridge` - we pull the message out and re-construct it in the destination context. I'll see what i can do here.

**Comment by MarshallOfSound** [comment]
@codebytere This was solved specifically for `webFrame.executeJavaScript`.  You could extract that logic into the context bridge methods --> https://github.com/electron/electron/pull/26889/files#diff-678990291ce65586b9e4e509f021d2d699ba5ca164b2a0569c5342c60ab548b4R276-R287
