### ISSUE TITLE
electron have 2 types ???

### ISSUE THREAD

**Issue by maajja** [electron/electron#28344]
is this a different electron or just a different version of electron 
![electron](https://user-images.githubusercontent.com/79619000/112100024-0f8c1400-8bd7-11eb-9eb4-b14434e8b9df.jpg)

**Comment by MarshallOfSound** [comment]
Different version, that's the old icon from a few years ago

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
