### ISSUE TITLE
Enable inspecting the devtools window

### ISSUE THREAD

**Issue by etiktin** [electron/electron#2835]
In Google Chrome if you want to debug a devtools extension you can do that by opening the devtools in a page where the extension is supposed to work and then open a second devtools window from the first one by clicking on CTRL+SHIFT+J ([reference](http://stackoverflow.com/questions/19875605/debugging-chrome-extension-with-access-to-chrome-devtools-api)). So the second devtools is actually for debugging the first devtools.
How can I open the second devtools in Electron?

**Comment by deepak1556** [comment]
you can use remote debugging to achieve that in Electron, visit the debugging url and you should see the devtools url ready for inspection.

**Comment by etiktin** [comment]
Thanks @deepak1556. I managed to open the second devtools from the remote debugging url, but it seems there's no way to debug the extension load.
I'm trying to debug the issues with running Angular Batarang (#915). The extension starts by loading a file called devtoolsBackground.js . If I put a breakpoint on the first line of the file, it doesn't break. If I do the same in Google Chrome, I can reload the first devtools and then the breakpoint in the second devtools fires. Is there any way to get it to work when using remote debugging?

It seems that remote debugging works using websockets, so maybe reconnecting doesn't block, which means the script is loaded before the connection was re-created and that's why I'm missing the first breakpoint.

**Comment by parro-it** [comment]
Any news on this feature?

**Comment by inklesspen** [comment]
@etiktin I was poking around with this today for React devtools, and I suspect the problem you're having with the debugger is simply that the scripts to be injected into the page aren't injected, and thus are never run, because Electron hasn't implemented this yet.

**Comment by codebytere** [comment]
Closing due to abandonment.
