### ISSUE TITLE
[Feature Request]: Update v12.0.0 release notes and add the deprecation of `new-window`

### ISSUE THREAD

**Issue by Prinzhorn** [electron/electron#28375]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

By chance I just noticed that v12 deprecated `new-window`. It is only listed under the "Additions" (as a subclause of a new feature) but it should be added to "Removed/Deprecated". At the same time the deprecation of `remote` is listed under "Breaking change" (which it isn't _yet_) and additionally under "Removed/Deprecated".

### Proposed Solution

Add "deprecate new-window event" to "Removed/Deprecated" https://github.com/electron/electron/releases/tag/v12.0.0 so that others upgrading from v11 don't miss the change like I did. I like to always be at the edge and migrate away from deprecated stuff immediately.

### Alternatives Considered

-

### Additional Information

-

**Comment by Prinzhorn** [comment]
"Deprecated the use of the vm module in the renderer process" is only listed under "Fixes" as well

**Comment by VerteDinde** [comment]
Hey @Prinzhorn, thanks for calling this out! I've updated both the new-window event deprecation and the vm module deprecation in the 12 release notes here: https://github.com/electron/electron/releases/tag/v12.0.0 

We're also updating our breaking changes doc to reflect this - will close this issue once that doc has been updated 🙂
