### ISSUE TITLE
[Bug]: Destroying BrowserView doesn't close its dev tools when docked out

### ISSUE THREAD

**Issue by MehediH** [electron/electron#28378]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H1

### What arch are you using?

x64

### Last Known Working Electron version

N/A

### Expected Behavior

When a `BrowserView` is destroyed with `win.setBrowserView(null)` or `win.removeBrowserView()`, the `BrowserView`'s dev tools should also be destroyed. 

### Actual Behavior

When a `BrowserView` is destroyed, its dev tools are not destroyed when docked out. 

### Testcase Gist URL

https://gist.github.com/c99c9b1b2740e7e855f5f5bd9aa7c11f

Steps to repro:

1. Open the repro gist with Electron Fiddle
2. Wait for the `BrowserView`'s dev tools to open
3. Dock the dev tools outside of the BrowserView
4. Kill the browser view
5. Observe the dev tools is still open

**Comment by pushkin-** [comment]
That doesn't destroy the BrowserView. It just unset it. Don't remember if there's a better way of doing this in Electron 12, but try `browserView.webContents.destroy()`

**Comment by MehediH** [comment]
Hmm, you are right, that does the trick. But in that case, I think it'd be helpful to clarify the docs.
