### ISSUE TITLE
[Bug]: 12.0.0 broke 'new-window' event when using preventDefault + newGuest

### ISSUE THREAD

**Issue by erikolofsson** [electron/electron#28374]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur

### What arch are you using?

x64

### Last Known Working Electron version

11.4.1

### Expected Behavior

window.open in the browser should return a window object

### Actual Behavior

window.open returns null

### Testcase Gist URL

https://gist.github.com/erikolofsson/11490eb09591313ac682bae83dd7e8fb

In electron 12 the deprecated new-window event doesn't work when you use the preventDefault + event.newGuest = x method to create the window yourself.

In the browser window.open returns null.

**Comment by pushkin-** [comment]
possibly related [issue](https://github.com/electron/electron/issues/27977)

**Comment by MarshallOfSound** [comment]
@erikolofsson We introduced the new API because due to architectural changes and new technical limitations the `new-window` event is no longer maintainable.  It's currently deprecated and is slated for removal in an upcoming version of Electron.

It's possible we can look into this and find a workaround but your best bet is to move to the new `setWindowOpenHandler` API.  Any issues with _that_ API we can definitely work on.

**Comment by erikolofsson** [comment]
Maybe the function should be removed in that case, as it's not working at all now?

I looked into `setWindowOpenHandler` and it doesn't seem to support changing the URL to be loaded in the new window?

**Comment by pushkin-** [comment]
@erikolofsson I'm not sure that `new-window` did either based on my findings [here](https://github.com/electron/electron/issues/27367). Electron already loads the URL for you automatically even if you make a `loadURL` call. You'd have to make the call asynchornously.

In this case, I imagine you can change load a different URL in the did-create-window handler.

**Comment by pushkin-** [comment]
@erikolofsson The BrowserView has nothing to do with it. I can reproduce the behavior you're describing when `nativeWindowOpen` is disabled. (which is the default, so I guess that's your test case). When it's enabled though, Electron loads the URL for you it seems

**Comment by erikolofsson** [comment]
Ok, then it remains to be seen if Electron 12 setWindowOpenHandler can be used without actually loading anything in the new window. 

My use case right now is to run an OAuth authentication flow in an external browser and get the result back to the Electron application. To do this with a "popup" flow I create the window so the browser code gets a handle, instead load the URL in an external browser, and then later load a result of a OAuth authentication in the empty window from a custom protocol handler.

**Comment by gucheen** [comment]
It would be very helpful if `setWindowOpenHandler` could set `newGuest` as `new-window` event did.
Also, It will be nice if a `BrowserView` could to set as `newGuest`.

**Comment by nornagon** [comment]
@gucheen we do sort of support that, see https://github.com/electron/electron/pull/26802

**Comment by gucheen** [comment]
> @gucheen we do sort of support that, see #26802

@nornagon thanks! Really helps a lot

**Comment by TheCleric** [comment]
> @gucheen we do sort of support that, see #26802

@nornagon can you explain to me how this support works? For example if in the `setWindowOpenHandler` how can I `deny` and set a newGuest to be returned to the browser's `window.open` event?
