### ISSUE TITLE
[Bug]: process.electronBinding is not a function

### ISSUE THREAD

**Issue by jackple** [electron/electron#28385]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

macOS

### Operating System Version

macOS Bug Sur 11.2.3

### What arch are you using?

x64

### Expected Behavior

process.electronBinding is a function

### Actual Behavior

Throw error: process.electronBinding is not a function

Is there some configurations I have missed??

**Comment by MarshallOfSound** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

Please provide a standalone test that a tester could run to reproduce the issue. This makes fixing issues go more smoothly: not only does it ensure the right thing is tested, but it also prevents triage from bottlenecking on making testers write new tests for each new issue.

I'm setting the more-information-needed label for the above reasons. After you've responded, please @ me in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by jackple** [comment]
https://github.com/jackple/electron-quick-start

```ts
app.whenReady().then(() => {
  dialog.showMessageBox({ message: 'process.electronBinding type is: ' + typeof process.electronBinding })
})
```

![image](https://user-images.githubusercontent.com/6183232/112564773-d2ae6000-8e16-11eb-81d6-1f8e647d3024.png)

@MarshallOfSound

**Comment by codebytere** [comment]
This is expected behavior per https://github.com/electron/electron/pull/24191 - we removed `electronBinding` intentionally.
