### ISSUE TITLE
Why electron app looking for system DLLs from the electron app installed location?

### ISSUE THREAD

**Issue by TulasiramRajanna** [electron/electron#28384]
The following system DLLs are trying load from electron app installed location “C:\Users\AppData\Local\Programs” and “C:\Users\AppData\Local” where all these DLLs are doesnot exists.

Any reason for this behavior ? and we are informed to Implement proper search order paths when the application searches for Windows DLL files and do validate before executing by the application.

How to proceed with this ?

If this behavior is expected then please provide few information links.

MSIMG32.dll
WINMM.dll
USERENV.dll
DWrite.dll
WINMMBASE.dll
OLEACC.dll
WINMMBASE.dll
IPHLPAPI.DLL
dbghelp.dll
UIAutomationCore.DLL
VERSION.dll
Bcp47Langs.dll
NTASN1.dll
dxgi.dll
ncrypt.dll
VERSION.dll
wininet.dll
dbghelp.dll
iphlpapi.dll
dwmapi.dll
USP10.dll
netapi32.dll
netutils.dll
wkscli.dll
srvcli.dll
mscms.dll
ColorAdapterClient.dll
devobj.dll
UxTheme.dll
oleaccrd.dll
uiautomationcore.dll
netapi32.dll
netutils.dll
wkscli.dll
srvcli.dll

**Comment by audibleblink** [comment]
Could there be a way to specify electron wants certain dlls from the system directory. I know there's a flag to specify this in the LoadLibraryEx winapi call, just not sure if relevant here. 

This behavior introduces ubiquitous DLL search order hijacking.

**Comment by xsq007** [comment]
+1 here. 
We received the security risk (DLL hijacking) from security team.
Is it possible to load system dlls only from system32 directory? Or validate the signature of dlls?

**Comment by hakusaro** [comment]
This is probably going to become a fairly common security issue revealed by penetration testers. Search order hijacking is really not ideal.

**Comment by skinner2401** [comment]
Bump.

Wondering if any other issues are tracking solutions to this in a non-standard way.

**Comment by zhoumh1988** [comment]
+1 here.
We received the security risk (DLL hijacking) from security team.
Is it possible to load system dlls only from system32 directory?

**Comment by rethink-BergsonJunior** [comment]
+1 here.
My DLLs are loading from SysWOW64, not from my locally directory, what i suppose to do?

**Comment by OmgImAlexis** [comment]
Someone should report this via https://github.com/electron/electron/security/advisories/new

**Comment by MarshallOfSound** [comment]
These DLL loads come from Chromium and they do not change them per their threat model:

https://chromium.googlesource.com/chromium/src.git/+/master/docs/security/faq.md#why-arent-physically_local-attacks-in-chromes-threat-model
