### ISSUE TITLE
[Bug]: CSS cursor style isn't respected on the very right and bottom edge of the application

### ISSUE THREAD

**Issue by kujukuju** [electron/electron#28387]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

9.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 19041

### What arch are you using?

x64

### Last Known Working Electron version

9.0.1

### Expected Behavior

I expect the cursor to be the stylized cursor across the whole window.

### Actual Behavior

When I style the cursor using this css style:
```
html, body {
    cursor: url('../assets/cursor/cursor.cur'), default;
}
```
the cursor goes back to back to the default when my mouse approaches the RIGHT and BOTTOM edge of the electron window.

See example video of this bug:
https://i.imgur.com/9ZlAAOw.mp4

When I style the cursor using this css style:
```
html, body {
    cursor: url('../assets/cursor/cursor.cur'), default;
}
```
the cursor goes back to back to the default when my mouse approaches the RIGHT and BOTTOM edge of the electron window.

See example video of this bug:
https://i.imgur.com/9ZlAAOw.mp4

**Comment by kujukuju** [comment]
Updated to electron 12.0.2 and confirmed the issue still exists.

**Comment by kujukuju** [comment]
Final note is that when I host this same website and access it through chrome, the cursor works as expected.

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by kujukuju** [comment]
Here's my gist. However it's missing the .cur file for the cursor.

https://gist.github.com/kujukuju/20a79792324a94afae4c733ed24f17c9

Extract this file into the root folder (with index.html) to properly repro.

[cursor.zip](https://github.com/electron/electron/files/6257410/cursor.zip)

**Comment by kujukuju** [comment]
Also, I couldn't get the cursor file to load with the electron fiddle program. I had to explicitly `npm start` to repro.

I'd be surprised if this is a legitimate bug, but it definitely repros very consistently. If you have any advice for how to fix this please let me know.

**Comment by kujukuju** [comment]
hey @nornagon should I change the tags somehow to remove the blocked/need-repro tag? This hasn't been updated in a while. Thanks!

**Comment by nornagon** [comment]
I can reproduce this.

**Comment by kujukuju** [comment]
By the way I've found the issue. Your cursor must be something like 32 pixels maximum in both dimensions. My cursor had a height of 34 pixels iirc. With a small enough cursor icon this bug no longer reproduces, and I think that's the correct behavior, so closing this out.
