### ISSUE TITLE
[Docs/Bug?]: showMessageBoxSync return value does not contain checkboxChecked 

### ISSUE THREAD

**Issue by gsouquet** [electron/electron#28394]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.1

### What operating system are you using?

macOS

### Operating System Version

macOs Catalina 10.15.7

### What arch are you using?

x64

### Expected Behavior

The `dialog.showMessageBoxSync` function documentation specify that we can pass the `checkboxLabel` and `checkboxChecked` argument.
I would expect the function return value to be of the same type as the one `dialog.showMessageBox` resolves to

### Actual Behavior

`dialog.showMessageBox` returns an `Integer`. It is therefore impossible to know the state of `checkboxChecked`

I appreciate that this might be the correct behaviour after the changes made as part of #17298 

If that is the case I would suggest making changes to the documentation to remove the references to the checkbox options parameters as they suggest this is a feature for synchronous dialogs
Would be more than happy to volunteer making documentation changes if needed

**Comment by MarshallOfSound** [comment]
This is working exactly as documented / intended.  If you want the state of the checkbox you have to use the async API (you should lean towards using the async API anyway).

I agree it's confusing that there is an option that can be used but whose result can not be read but at this time making a breaking change int he dialog API is exactly what we wanted to avoid and therefore we won't be changing the return type.
