### ISSUE TITLE
[Bug]: Renderer spellcheck API does not work on Windows

### ISSUE THREAD

**Issue by lishid** [electron/electron#28404]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 1909

### What arch are you using?

x64

### Expected Behavior

renderer.js
```js
let element = document.createElement('textarea');
element.spellcheck = true;
element.value = 'testt';
document.body.appendChild(element);
element.focus();

setInterval(() => {
  console.log(require('electron').webFrame.isWordMisspelled('testt'))
}, 1000);
````

Expected: Console log repeatedly print "true"

### Actual Behavior

Actual: Console log repeatedly prints "false"

### Testcase Gist URL

*(edit ckerr):* https://gist.github.com/ckerr/91b84f22d5beeef1506174b495720dd7

Concerning the API released in https://github.com/electron/electron/pull/25060

@zcbenz Noticed you were working on spellcheck related tests. It seems that the tests for this API don't run on Windows so it wasn't caught:
https://github.com/electron/electron/blob/f08b67f2fa916e066c23c3255fe9f1d86752e9d7/spec-main/spellchecker-spec.ts#L84

This seems to work on Linux for me, but not on Windows.

**Comment by lishid** [comment]
This comment might be related:
https://github.com/electron/electron/pull/25060/files#r496156887

**Comment by ckerr** [comment]
Confirmed works on Linux. Tested with Electron 12.0.2 on Ubuntu 20.10.

Electron fiddle test: https://gist.github.com/ckerr/91b84f22d5beeef1506174b495720dd7

**Comment by codebytere** [comment]
@lishid this is not a bug - if you take a look at https://github.com/electron/electron/blob/45c4dd529fb1b94a4e8e50a8f775027317b152e2/docs/api/session.md#L691-L699 you'll see that only macOS detects your language automatically. On Windows, you need to first call e.g. in the main process `session.defaultSession.setSpellCheckerLanguages(['en-US'])`. Once I added this your Fiddle passed for me.

**Comment by codebytere** [comment]
This is because by default the spellchecker only automatically detects language on macOS - see: https://github.com/electron/electron/blob/45c4dd529fb1b94a4e8e50a8f775027317b152e2/docs/api/session.md#L691-L699

If you add `session.defaultSession.setSpellCheckerLanguages(['en-US'])` to your Fiddle before you create the window the test will pass.

**Comment by lishid** [comment]
I have added `session.defaultSession.setSpellCheckerLanguages(['en-US'])` in my fiddle right before `new BrowserWindow` and I can still repro this issue.

An observation is that Electron correctly spellchecks the textarea with English, without having to set the language, but the API still returns `false` on the identically misspelled word.

![image](https://user-images.githubusercontent.com/609710/113127858-3a81f380-91e7-11eb-9ec4-9d2966bffd0b.png)

**Comment by lishid** [comment]
@codebytere Can you verify/repro this on Windows?

**Comment by lishid** [comment]
@ckerr Any chance we can have this re-opened?
