### ISSUE TITLE
[Bug][macOS]: browser window drag for non-zero x,y browser view bounds 

### ISSUE THREAD

**Issue by b3ll00z** [electron/electron#28405]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.2.1

### What arch are you using?

x64

### Last Known Working Electron version

11.3.0

### Expected Behavior

Despite the `x, y` bounds provided for a browser view, the whole browser window should not be draggable by clicking inside its browser view itself

### Actual Behavior

For browser views with both `x, y` bounds coordinates, such that `x > 0` or `y > 0`, if I click inside the browser view the entire browser window starts dragging

### Testcase Gist URL

https://github.com/b3ll00z/electron-quick-start-typescript

### To Reproduce
```
$ git clone https://github.com/b3ll00z/electron-quick-start-typescript
$ cd electron-quick-start-typescript
$ npm install ; npm start
```
https://user-images.githubusercontent.com/16275841/112603502-654dff80-8e15-11eb-8d97-c142adc46afd.mov

**Comment by Kilian** [comment]
Here's a test fiddle: https://gist.github.com/b9c5a45bf59f6ba748041d000414e571 This shows devtools inside a `browserView`.

On launch, the devtools are offset to the right. You can click + drag the window when clicking into the devtools. Additionally, it can not receive keyboard input. When you switch the position to {x: 0, y: 0} this does not happen: the window is not dragged and it can receive text input. This behavior shows in any version after 11.3.0. (11.3.0 does not have this issue)

This seems very related to https://github.com/electron/electron/pull/28268,  but it should be noted that fix (which is in 12.0.2) does not fix this issue. Additionally, changing either the x or the y value triggers this dragging behavior.

Other related issues seem https://github.com/electron/electron/issues/28057, https://github.com/electron/electron/issues/28228 and https://github.com/electron/electron/pull/27143.
