### ISSUE TITLE
[Bug]: menuItem.label not being set

### ISSUE THREAD

**Issue by sdegutis** [electron/electron#28408]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

Latest

### What operating system are you using?

macOS

### Operating System Version

macOS 10.15.7

### What arch are you using?

x64

### Expected Behavior

I have a MenuItem, and inside setInterval I run menuItem.label = 'test', but it's not changing the label. I can verify that setting .enabled works, so I have a valid handle to the menu item. It was created via the buildFromTemplate factory function, and I got a handle on it from menu.items.find().

### Actual Behavior

The label is not set.

**Comment by Prinzhorn** [comment]
https://github.com/electron/electron/issues/21504

**Comment by sdegutis** [comment]
So basically it's had known incorrect documentation for a year.

Thanks @Prinzhorn.

**Comment by MarshallOfSound** [comment]
Closing per #21504
