### ISSUE TITLE
[Feature Request]: To use ELECTRON_NO_ASAR alone without checking type whether 'browser' or 'renderer' 

### ISSUE THREAD

**Issue by packlikez** [electron/electron#28406]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I want to test copying .asar file using jest and @jest-runner/electron as a test suite. Despite of using process.env.ELECTRON_NO_ASAR or process.noAsar, it doesn't work.

because...
- when using process.noAsar: It can't passes process.noAsar to electron when it's spawned as a child process.
- when using process.env.ELECTRON_NO_ASAR: it doesn't work also, because process.type is 'browser' so isAsarDisabled will return false. I'm aware that it has to use with ELECTRON_RUN_AS_NODE, but it's going to break the test runner.

### Proposed Solution

I need a way to set no support asar without checking any other conditions through process.env

### Alternatives Considered

Remove the checking process.type at envNoAsar constant

### Additional Information

I'm using fs-extra to copy files.

**Comment by MarshallOfSound** [comment]
@packlikez Adding ad-hoc new conditional for this isn't something that we're probably going to do.  If you can't make the existing ways to disable ASAR support work then I'd suggest configuring `fs-extra` to use the `original-fs` package (which is the literal "fs" package but without `asar` support injected)

**Comment by packlikez** [comment]
Thanks for your reply.
Do you have any suggestion on configuring fs-extra to use the original-fs package? Even if it works, do I have to keep maintain the original-fs package forever?

Instead, I would prefer to have process.env.noAsar or if you have any idea to pass process.noAsar when spawn the child process please let me know.
