### ISSUE TITLE
[Feature Request]: Bikeshed: contextBridge.exposeInMainWorld is confusingly named

### ISSUE THREAD

**Issue by Kilian** [electron/electron#28410]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

The `contextBridge.exposeInMainWorld` lets you expose properties from the "preload" world to the "main" world, both of which are part of the renderer. 

But "main" is an overloaded term, since it's already widely used to describe the _Main process_ and is usually in a file called _main.js_[1]. I understand that this is a nice way to split the "preload" from the "global" context, so really only take issue with the "main" naming.

This means that "exposeInMainWorld" is highly likely to be interpreted as exposing properties from the preload script to the _Main process_, not the "main world" in the Renderer.

[1] For example, in our own quick start: https://www.electronjs.org/docs/tutorial/quick-start

### Proposed Solution

Rename `exposeInMainWorld` to something that does not use "Main".

* just `expose`
* `exposeInRenderer`
* `exposeToGlobal`
* `exposeInWindow`/`exporeInBrowserWindow`

are directions I think we should consider. 

### Alternatives Considered

n/a, this is bikeshedding.

### Additional Information

n/a

**Comment by Kilian** [comment]
Previous related ticket: https://github.com/electron/electron/issues/26728

The linked extension resources don't mention "main" anywhere. I think the "isolated world" concept is good to keep but would really like to prevent Electron having a concept called "Main" that can mean either the renderer process or the ..eh, main process depending on the, eh, context.

**Comment by nornagon** [comment]
I'm 👎  on this for the same reasons I mentioned in #26728.

Putting that aside, I think all the names proposed above have similar problems to `exposeInMainWorld` with the possible exception of just `expose`:

- `exposeInRenderer` — both the isolated and main worlds are in the renderer, so this is confusing
- `exposeToGlobal` — there's a global object in both the main and the isolated world, so this is confusing
- `exposeInWindow` — there's a `window` object in both the main and the isolated world, so this is confusing
- `exposeInBrowserWindow` — preload scripts can run in iframes, or BrowserViews, or webviews, so this is confusing

**Comment by Kilian** [comment]
Yeah good points. Maybe `exposeInSharedContext`? All of this with all the caveats that changing an existing API should have a very good reason, and not be done on a whim, but:

* I think having "main" mean different things is going to confuse developers new to Electron when they've already had to learn the terms "main" and "renderer" in the context of Electron, only for that term "main" then to be used in a completely different way, in an area where "just set contextIsolation to false" is a much easier solution in the same way that remote.getGlobal was. 
* I think for contextBridge we're probably early enough where there isn't widespread usage yet, and we can also keep the old name around as a reference for a little longer so it doesn't break. (like we did for the extension APIs.)

**Comment by Prinzhorn** [comment]
Input from a regular Electron user that's using `contextIsolation`:

Since this is already scoped to (and the only property of the) `contextBridge` import, why not `contextBridge.expose()`? Or is (will?) there a use-case other than exposing stuff from preload to the page?

The terminology on https://www.electronjs.org/docs/api/context-bridge#contextbridge is very technical, like an order of magnitude more than most of the API/docs. I understand that these are concepts from Chrome but to a user this is a lot to digest:

> Create a safe, bi-directional, synchronous bridge across isolated contexts

How about

> Expose APIs from a preload script to the page when using `contextIsolation`

The technical details about different worlds etc. could still be at the bottom of the page. I think both of you have a completely different view of these things than a user does. And now you're trying to force these internal terminologies on the user (I believe) and you might forget that these details are not important to us, only the result is. This isn't meant negative in any way, just how brains work I guess.

I'm going to hijack this thread for one more related thing: can you please expose the `999` somewhere? I'm currently doing `const ISOLATED_WORLD_ID = 999;` but this feels super weird. I (as a user) shouldn't care about this magical number (or fear that it will change). This is another place that shows that `contextIsolation` usage doesn't seem widespread and that the API is somewhat rough.

**Comment by Kilian** [comment]
I like `expose()` as well, and take the point on technical documentation. I'll see what we can do to improve that.

**Comment by miniak** [comment]
cc @MarshallOfSound

**Comment by miniak** [comment]
Closing this one due to lack of activity

**Comment by Allasso** [comment]
Wow do I understand the confusion, as I am so confused on this.  Someone please tell me the difference between "exposeInMainWorld" and "exposeInIsolatedWorld".  I hate to be critical, but the docs are terrible on this.  There is no explanation as to what the arguments mean.  "exposeInIsolatedWorld" seems to include a label of some kind? (number - 1001 in the example.)

**Comment by MarshallOfSound** [comment]
@Allasso https://www.electronjs.org/docs/latest/api/context-bridge#glossary

Going from Preload -> Main is what 99.9999% of folks need, main world is where your website runs. The isolated world is where your preload script runs

**Comment by Allasso** [comment]
@MarshallOfSound Thanks.  Forgive me if this shamelessly unkosher to seek help here, but I've been pulling my hair out for 2 days trying to be able to send messages to/from <webview> content (js which I've injected actually) and the renderer process (or main or _somewhere_ else.)  I am importing `ipcRenderer,` and  `contextBridge` into the <webview> preload script, but it seems that anything I attempt to get the <webview> injected js to recognize always turns up `undefined`.  All the gory details are here: https://stackoverflow.com/questions/78672729/unable-to-send-message-from-javascript-injected-into-webview-ipcrenderer-undef

**Comment by Allasso** [comment]
@MarshallOfSound regarding the link, thanks.  I never would have expected to check a glossary to find out what the args mean.  They still leave a lot to be explained though.

**Comment by MarshallOfSound** [comment]
```
const { ipcRenderer, webContents } = require('electron');

window.sendData = (data) => {
  ipcRenderer.send("ping");
}

alert("webview_preload.js has been loaded into webview");
```

This is your problem, `window.sendData` needs to use `contextBridge.exposeInMainWorld`

```
const { contextBridge, ipcRenderer, webContents } = require('electron');

contextBridge.exposeInMainWorld('api', {
  sendData: (data) => {
    ipcRenderer.send("ping");
  },
});

alert("webview_preload.js has been loaded into webview");
```

Then call `window.api.sendData` in your try-catch series and you should be good.

For future help your best bet is our community discord

**Comment by Allasso** [comment]
Thanks, that worked.  I thought I had been trying what you suggested, but apparently I miscoded somewhere.

Okay, thanks.  I'll check that out.

**Comment by Allasso** [comment]
It may not be important to you, but if you care to paste that into an answer on SO, I'll choose it as accepted.  If you don't want to bother, I'll provide the answer and give you mention.
