### ISSUE TITLE
[Bug]: shell.trashItem crashes the main process

### ISSUE THREAD

**Issue by mau-io** [electron/electron#28415]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

shell.trashItem should just work.

### Actual Behavior

shell.trashItem not work only crashes the process.

`const {
  shell
} = require('electron');
(async()=>{
  await shell.trashItem('C:/Users/User/Desktop/folder/file.jpg');
})();`

**Comment by codebytere** [comment]
If you run what you have, you likely see: `Error: failed to parse path`. This is because your path is incorrect - it should have been `C:\Users\User\Desktop\folder\test.png`.

In the future, you can do something like:
```js
const filePath = path.join(app.getPath('desktop'), 'folder', 'test.png')
await shell.trashItem(filePath);
```

in order to not need to worry about this.
