### ISSUE TITLE
[Question] How do I stop Electron from throwing devtools extension errors to main console?

### ISSUE THREAD

**Issue by m4heshd** [electron/electron#28417]
_Didn't use an issue template since there's no template for a simple question._

How isn't there an option to stop this from happening?

![image](https://user-images.githubusercontent.com/6711514/112711913-fe524880-8ef1-11eb-8db4-7bb5d509dfc7.png)

This is from Vue devtools. Thousands of errors being spit out to the main process console. Hard to find any useful information in middle of all that. How do I stop this without messing with devtool's source?

**Electron version:** 12.0.0
**Platform:** Windows 10 x64

**Comment by Prinzhorn** [comment]
> _Didn't use an issue template since there's no template for a simple question._

I think the templates are there for a reason to make it easier for the maintainers. This could have been opened as either a feature request to have "an option to stop this from happening" or a bug report. In either case you didn't provide clear steps to reproduce this issue. If it's a simple question then this is probably the wrong place, see https://www.electronjs.org/docs/development/issues#asking-for-general-help 

With the limited information you've provided I assume this is an issue/bug in https://github.com/vuejs/vue-devtools and not a problem with Electron.

**Comment by m4heshd** [comment]
I can save time coding a fix myself rather than wasting time on "rule following" in this mute community. Closing.

**Comment by Prinzhorn** [comment]
> coding a fix myself

A pull request will be very much appreciated in which ever repository you end up making the fix :+1:
