### ISSUE TITLE
Problems with the complte Launcher

### ISSUE THREAD

**Issue by youngZimbel** [electron/electron#28413]
Hey, i have a Discord Server and there im managing the bots but since 2 hours i cant any message in all channels and i cant send messages( yes i have the permissions to do this).
![Screenshot 2021-03-26 192601](https://user-images.githubusercontent.com/74208706/112676782-28abf380-8e69-11eb-9527-3a3002505eeb.png)

https://user-images.githubusercontent.com/74208706/112676868-4a0cdf80-8e69-11eb-8b48-0d691ec3d9bc.mp4

**Comment by MarshallOfSound** [comment]
This does not appear to be an issue with Electron rather with discord.  Please contact discord support
