### ISSUE TITLE
[Bug]: img tag src http forward https

### ISSUE THREAD

**Issue by cjahv** [electron/electron#28416]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2,12.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10 20H2, Big Sur 11.2.3 (20D91)

### What arch are you using?

x64

### Last Known Working Electron version

11.4.1

### Expected Behavior

~~Both systems have the same results~~

Loading HTTP images

`document.createElement('img').src='http://electron.com'` actual request address `http://electron.com`

### Actual Behavior

`document.createElement('img').src='http://electron.com'` actual request address `https://electron.com`

### Testcase Gist URL

[electron.zip](https://github.com/electron/electron/files/6215571/electron.zip)

```
location.href
"https://localhost:54603/public/setup/index/index.html"
```

**Comment by JacobLiou** [comment]
real bug

**Comment by cjahv** [comment]
@Prinzhorn 
[electron.zip](https://github.com/electron/electron/files/6215571/electron.zip)

use `yarn start-11` test electron 11

use `yarn start-12` test electron 12

**Comment by cjahv** [comment]
@Prinzhorn 

After the second test, we found that the two platforms have the same behavior. HTTP images can be loaded at HTTPS electron11, but HTTP images cannot be loaded at electron12

**Comment by ckerr** [comment]
This broke sometime between v12.0.0-nightly.20201026 and v12.0.0-nightly.20201030. The commits between those releases:

https://github.com/electron/electron/compare/v12.0.0-nightly.20201026...v12.0.0-nightly.20201030

**Comment by nornagon** [comment]
The only relevant commit in that range is the chromium bump.

@cjahv can you confirm whether this behavior is different from Chrome itself?

**Comment by cjahv** [comment]
@nornagon Right, use chrome `88.0.4324.192` get same result as electron 12.

**Comment by xland** [comment]
@cjahv 

So what do you to about this probolem?

**Comment by cjahv** [comment]
> @cjahv
> 
> So what do you to about this probolem?

这应该是chrome上游的问题，我选择使用老版本11.1.1

**Comment by xland** [comment]
老哥，我感觉这很明显是Electron的`allowRunningInsecureContent`这个配置项失效了导致的

**Comment by cjahv** [comment]
@xland 不是，chrome浏览器88.0.4324.192 有相同的bug，electron继承了它，需要上游chrome修复
