### ISSUE TITLE
[Bug]: setResizable(false) and setResizable(true) then window cannot snap to the side of the screen

### ISSUE THREAD

**Issue by WildXBird** [electron/electron#28424]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 1809 17763.316

### What arch are you using?

x64

### Expected Behavior

frameless window ,
Select the area(WebkitAppRegion: "drag") of the window, and drag it to the edge of screen. An outline indicates where the window will snap to once drop it. The window will resize and take up half of the screen space.

### Actual Behavior

nothing

This demo can reproduce this problem：

`const { BrowserWindow, app } = require('electron')

function createWindow() {
    mainWindow = new BrowserWindow({
        width: 800,
        height: 600,
        frame: false,
        webPreferences: {
            contextIsolation: false,
            nodeIntegration: true,
        },
    })
    mainWindow.loadURL('http://localhost:8000/mainUI')
    mainWindow.setResizable(false)
    mainWindow.setResizable(true)
}
app.whenReady().then(() => {
    createWindow()
})`

**Comment by codebytere** [comment]
@WildXBird please provide a proper Fiddle we can load and run.

**Comment by codebytere** [comment]
Closed as no response was provided.
