### ISSUE TITLE
[Bug]: Mas build application crashes on launch when codesigned with "com.apple.security.app-sandbox" enabled 

### ISSUE THREAD

**Issue by str4nge-4ttr4ctor** [electron/electron#28428]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

10.3.2
10.4.1
11.3.0
12.0.1
9.4.4

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina 10.15.7

### What arch are you using?

x64

### Related bug
[27319](https://github.com/electron/electron/issues/27319)

### Expected Behavior

Application to launch without crashing when code-signed with entitlement "com.apple.security.app-sandbox" enabled 

### Actual Behavior

Application crashes on launch when code-signed with entitlement "com.apple.security.app-sandbox" enabled. 

Tried the following electron releases:
https://github.com/electron/electron/releases/download/v10.3.2/electron-v10.3.2-mas-x64.zip
https://github.com/electron/electron/releases/download/v10.4.1/electron-v10.4.1-mas-x64.zip
https://github.com/electron/electron/releases/download/v11.3.0/electron-v11.3.0-mas-x64.zip
https://github.com/electron/electron/releases/download/v12.0.1/electron-v12.0.1-mas-x64.zip
https://github.com/electron/electron/releases/download/v9.4.4/electron-v9.4.4-mas-x64.zip

### To Reproduce

When sandbox permissions are turned off, application launches without any issues. The crash only occurs when sandbox permissions are turned on.

**Crash report when launching the app:**

```
Crashed Thread:        26  ThreadPoolSingleThreadForegroundBlocking0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Trace/BPT trap: 5
Termination Reason:    Namespace SIGNAL, Code 0x5
Terminating Process:   exc handler [77030]
```

**Error when running code-signed electron binary:**

` FATAL:mach_port_rendezvous.cc(142)] Check failed: kr == KERN_SUCCESS. bootstrap_check_in com.my.app.MachPortRendezvousServer.78398: Permission denied (1100)`

### Additional Information

**parent.plist:**
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>com.apple.security.app-sandbox</key>
  <true/>
  <key>com.apple.security.application-groups</key>
  <array>
    <string>XXXXXXXXXX.com.my.app</string>
  </array>
  <key>com.apple.application-identifier</key>
  <string>XXXXXXXXXX.com.my.app</string>
  <key>com.apple.developer.team-identifier</key>
  <string>XXXXXXXXXX</string>
  <key>com.apple.security.device.camera</key>
  <true/>
  <key>com.apple.security.device.audio-input</key>
  <true/>
  <key>com.apple.security.automation.apple-events</key>
  <true/>
  <key>com.apple.security.cs.allow-jit</key>
  <true/>
  <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
  <true/>
  <key>keychain-access-groups</key>
  <array>
    <string>XXXXXXXXXX.com.my.identity.universalstorage</string>
  </array>
</dict>
</plist>
```
**loginhelper.plist:**
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>com.apple.security.app-sandbox</key>
  <true/>
</dict>
</plist>
```
**child.plist:**
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>com.apple.security.app-sandbox</key>
  <true/>
  <key>com.apple.security.inherit</key>
  <true/>
  <key>com.apple.security.device.camera</key>
  <true/>
  <key>com.apple.security.device.audio-input</key>
  <true/>
  <key>com.apple.security.automation.apple-events</key>
  <true/>
  <key>com.apple.security.cs.allow-jit</key>
  <true/>
  <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
  <true/>
</dict>
</plist>
```

**Comment by zcbenz** [comment]
Was it working in 9.x?

**Comment by str4nge-4ttr4ctor** [comment]
> Was it working in 9.x?

@zcbenz  We didn't have a mas release before. I tried 9.4.4 and the same issue occurs.

**Comment by zcbenz** [comment]
I think this is very likely caused by some mistakes when signing the app, at least the mac app store version of Slack runs with sandbox and Electron 12:

```bash
$ env ELECTRON_RUN_AS_NODE=true /Applications/Slack.app/Contents/MacOS/Slack -e "console.log(process.versions.electron)"
12.0.1
$ codesign -d --entitlements :- /Applications/Slack.app
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>com.apple.security.app-sandbox</key>
  <true/>
  <key>com.apple.security.application-groups</key>
  <array>
    <string>BQR82RBBHL.com.tinyspeck.slackmacgap</string>
    <string>BQR82RBBHL.slack</string>
  </array>
  <key>com.apple.security.files.downloads.read-write</key>
  <true/>
  <key>com.apple.security.files.user-selected.read-write</key>
  <true/>
  <key>com.apple.security.files.bookmarks.app-scope</key>
  <true/>
  <key>com.apple.security.network.client</key>
  <true/>
  <key>com.apple.security.network.server</key>
  <true/>
  <key>com.apple.security.print</key>
  <true/>
  <key>com.apple.security.device.camera</key>
  <true/>
  <key>com.apple.security.device.microphone</key>
  <true/>
  <key>com.apple.security.device.usb</key>
  <true/>
</dict>
</plist>
```

But whatever the reason is, it should be noted in our docs. I'll try to do a codesign and check what is missing.

**Comment by zcbenz** [comment]
@str4nge-4ttr4ctor It turns out that Electron's "Mac App Store Submission Guide" has been outdated very much, Electron's directory layout and Apple's signing procedures have been changed a lot and the guide has not been updated.

Currently the updated way to sign Electron app is to use https://github.com/electron/electron-osx-sign, can you try it instead?

**Comment by str4nge-4ttr4ctor** [comment]
> @str4nge-4ttr4ctor It turns out that Electron's "Mac App Store Submission Guide" has been outdated very much, Electron's directory layout and Apple's signing procedures have been changed a lot and the guide has not been updated.
> 
> Currently the updated way to sign Electron app is to use https://github.com/electron/electron-osx-sign, can you try it instead?

@zcbenz Signing the app with https://github.com/electron/electron-osx-sign results in a 'Code Signature Invalid' crash report:
```
Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1
```

**Comment by zcbenz** [comment]
It seems that this module requires provisioning profiles to be present when signing the app, other it won't run, according to its documentation. There is one guide I found that explains how things work: https://epxx.co/artigos/electronsign.html.

Apple's latest singing mechanism is out of my knowledge, I'll have some learnings of it and update our documentation.
