### ISSUE TITLE
[Feature Request]: globalShortcuts Improvements (Why current system is not that useful)

### ISSUE THREAD

**Issue by luvyana** [electron/electron#28423]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

globalShortcuts, doesn't have proper ability to work as a global shortcut, because it uses system level APIs, which only allows single application to be assigned to a hotkey. This either blocks Electron (Games doesn't allow Electron) or other applications from using that hotkey while Electron's globalShortcut is registered.

### Proposed Solution

The solution I thought is to have a keyboard listener, that only listens for keyboard press instead of registering a hotkey using system level api that's only limited to single application.

### Alternatives Considered

Proposed solution has an alternative.

### Additional Information

More context is on the repository that I've created for this problem.

Please refer to my repo on this : https://github.com/luvyana/electron-globalShortcuts_PROBLEMS

**Comment by MarshallOfSound** [comment]
The issues you are described are architectural choices, the library you reference in that repository `iohook` uses techniques that many anti-virus tools will detect as malicious.  Intercepting / claiming key combinations at the OS level is the _correct_ way to take global shortcuts to avoid anti-virus tools detecting you as malicious.  We won't be changing our globalShortcut strategies from how they currently work.  You are free to use native modules or `iohook` if you wish
