### ISSUE TITLE
[Bug]: Missing permissions dialog for FileSystem API.

### ISSUE THREAD

**Issue by RangerMauve** [electron/electron#28422]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

Linux meerkat 5.8.0-7642-generic #47~1614007149~20.10~82fb226-Ubuntu SMP Tue Feb 23 02:59:01 UTC  x86_64 x86_64 x86_64 GNU/Linux

### What arch are you using?

x64

### Last Known Working Electron version

n/a

### Expected Behavior

When using the [File System Access API](https://web.dev/file-system-access/), attempting to write to a file using the FileSystemWritableFileStream API should cause a permission prompt to pop up that the user can accept or deny.

In Electron's case, it should probably trigger the [setPermissionRequestHandler](https://www.electronjs.org/docs/api/session#sessetpermissionrequesthandlerhandler) handler with a `permission` set to something like `filesystem` and a path to the file being requested.

### Actual Behavior

When invoking `fileHandle.createWritable()`, the following error gets thrown:

> Uncaught DOMException: The request is not allowed by the user agent or the platform in the current context.

### Testcase Gist URL

https://github.com/RangerMauve/electron-filesystem-prompt-example

Continuation of #23608

**Comment by codebytere** [comment]
@RangerMauve when you provide a Fiddle, you need to provide something that can be _loaded and run_ with Electron Fiddle. Yours has no main.js file, no index.html, or other necessary pieces of Electron app scaffolding.

**Comment by RangerMauve** [comment]
Thank you @codebytere I've created a repo that can be cloned and run and updated the issue.

https://github.com/RangerMauve/electron-filesystem-prompt-example

**Comment by Jaifroid** [comment]
I also need support for the File System Access API (aka Native File System API). However, we don't need the permissions dialogue to show, since we have File Access in Electron apps. We simply need the system to grant access automatically to read the filesystem if we have the file or directory handle (which can be serialized to IndexedDB and re-used across app launches)

**Comment by Starwort** [comment]
Still an issue on v13 (13.1.9) and v14 (14.0.0)

**Comment by Fiorello** [comment]
Hi,
any news about? 
Is there a workaroud to make it work?

**Comment by Jaifroid** [comment]
I've just tested with 15.3.0 on Windows 11, and the bug is *still* unresolved. You can use the File System Access API to open and read the contents of a directory, and to pick a single file, and that all works well, but as soon as you try to use the filesystem handle that you serialized to indexedDB, the access is denied and no verify prompt is issued.

The way NWJS does it is simply always to return true when you run `fileHandle.queryPermissions()`. No prompt is shown, access is simply granted. The beauty of this is that you don't need to code special use of Node APIs, you can simply code once, and it'll work both in a PWA and in Electron, with the latter acting the same way as if you had used Node APIs.

The only workaround is to use Node APIs to get the path to a file or folder, and store that instead of the `fileSystemHandle`. But this is clunky.

**Comment by Jaifroid** [comment]
And there's another (related) issue. When you successfully use the File System Access API to pick a file, and you convert the file handle to a File API object, the path is empty in Electron. If you pick the same file with the old bog-standard FilePicker, Electron hacks the File object and gives the actual filesystem path. So, using this API, you can't even get the file path to be able to open the file with Node's `fs.open`.
```
entry.getFile().then(function(file) {
    console.log(file.path); // file.path is ""
})
```

**Comment by Jaifroid** [comment]
@ckerr Can you kindly add 15-x-y label to this issue, and also add platform/windows or platform/all, because it relates to a Chromium API that is not properly supported and the issue is present on Windows and Linux at least (I confirm the bug persists on both OS's with 15.3.0).

**Comment by altjz** [comment]
I tried  Electron `16.0.4` version in my mac: `12.0.1`, Must add below line to enable the experimental feature

`app.commandLine.appendSwitch("enable-experimental-web-platform-features");`

then the permission will alway be true (won't prompt the window)

**Comment by Jaifroid** [comment]
> I tried Electron `16.0.4` version in my mac: `12.0.1`, Must add below line to enable the experimental feature
> 
> `app.commandLine.appendSwitch("enable-experimental-web-platform-features");`
> 
> then the permission will alway be true (won't prompt the window)

That's very helpful. I'll try. It would be great to be able to remove the Electron-specific code I've had to put in to work around this.

**Comment by altjz** [comment]
> > I tried Electron `16.0.4` version in my mac: `12.0.1`, Must add below line to enable the experimental feature
> > `app.commandLine.appendSwitch("enable-experimental-web-platform-features");`
> > then the permission will alway be true (won't prompt the window)
> 
> That's very helpful. I'll try. It would be great to be able to remove the Electron-specific code I've had to put in to work around this.

can get the permission, but can not get real path of the file

```
entry.getFile().then(function(file) {
    console.log(file.path); // file.path is '' empty
})
```

**Comment by RayDawn** [comment]
> I tried Electron `16.0.4` version in my mac: `12.0.1`, Must add below line to enable the experimental feature
> 
> `app.commandLine.appendSwitch("enable-experimental-web-platform-features");`
> 
> then the permission will alway be true (won't prompt the window)

Holy hell this was a lifesaver. I've been searching for what feels like ages, I was beginning to think I was the only person having this problem. 

To add to this:
Verified that this is still a problem on Electron version 17.0.0, platform is macOS.

**Comment by Jaifroid** [comment]
It's good to know! Unfortunately for me, I already worked around this by using Electron APIs, complicating my codebase when I was hoping to simplify it. I'll definitely look to revert at some point to the File System Access API: it's much better IMHO.

**Comment by Cirras** [comment]
Still a problem in 17.1.0 - this issue recently bit me.

I've enabled the `enable-experimental-web-platform-features` flag as suggested above, but this triggered some other unexpected behavioral changes in relation to overflowed divs being focusable. I expect there are other fun little surprises of this nature when using the flag.

The File System Access API makes code-sharing between web and electron much more convenient. It would be neat to see some movement towards better support for it.

**Comment by serbboy23** [comment]
Just commenting so that the team knows another person would like to see the File System Access API to be supported by electron. Not only do I need to complicate my code base by having BOTH Electrons API and Web API, but Electrons dialog API does not provide an easy way to create a Writable File Stream as the Web API does.. Hoping for support in the future!

**Comment by RangerMauve** [comment]
This is still an issue as of v19.0.0

**Comment by Jaifroid** [comment]
I only need to be able to read files. @RayDawn's tip above, to use `app.commandLine.appendSwitch("enable-experimental-web-platform-features");` works very well for my purpose. Obviously it would be good if someone else could verify whether this also enables writing to picked files (and re-using a serialized file handle). There is no permissions dialogue, by the way, it simply returns permission granted as if the user had given permission. It works (for reading) on picked files and picked folders.

**Comment by el3um4s** [comment]
Just commenting so that the team knows another person would like to see the File System Access API to be supported by electron.

**Comment by RangerMauve** [comment]
This is still an issue in Electron 20

**Comment by brianppoole** [comment]
> I only need to be able to read files. @RayDawn's tip above, to use `app.commandLine.appendSwitch("enable-experimental-web-platform-features");` works very well for my purpose. Obviously it would be good if someone else could verify whether this also enables writing to picked files (and re-using a serialized file handle). There is no permissions dialogue, by the way, it simply returns permission granted as if the user had given permission. It works (for reading) on picked files and picked folders.

I can confirm that adding the `app.commandLine.appendSwitch("enable-experimental-web-platform-features");` line also works for writing.

@codebytere This is still happening on 21.3.0

**Comment by RayDawn** [comment]
Leaving another comment because I've been credited twice now for the workaround which @altjz mentioned here: https://github.com/electron/electron/issues/28422#issuecomment-987504138. 
Can't believe this API is still locked behind experimental web platform features after all this time.

**Comment by RangerMauve** [comment]
Still an isssu in 23+

**Comment by bradisbell** [comment]
Hello from Electron 25.0.1.  Not stale.  :-)

**Comment by TigerHix** [comment]
This issue is still relevant!

**Comment by Andrew-web-coder** [comment]
Still waiting!

**Comment by zbynek** [comment]
Not a solution, just a workaround: it's possible to write your own polyfill for `showSaveFilePicker` using ipc and Node's `fs` API -- a simple example in https://gist.github.com/zbynek/f0d3bca71db9cbfd9ec30873ab04a45e .

**Comment by epferrari** [comment]
Our team would also like this feature enabled. Thank you.

**Comment by codebytere** [comment]
Making some progress:

<img width="822" alt="Screenshot 2024-02-22 at 5 28 26 PM" src="https://github.com/electron/electron/assets/2036040/6062338c-db5a-4fb0-966d-7bd64fba160c">

**Comment by codebytere** [comment]
Hey folks - i've opened a draft PR. Feedback welcome.

**Comment by JuerGenie** [comment]
> I tried Electron `16.0.4` version in my mac: `12.0.1`, Must add below line to enable the experimental feature
> 
> `app.commandLine.appendSwitch("enable-experimental-web-platform-features");`
> 
> then the permission will alway be true (won't prompt the window)

You saved my life! Thank you very much!

**Comment by Jaifroid** [comment]
Unfortunately in Electron 30.0.1 this seems broken. Even using "enable-experimental-web-platform-features" now no longer enables the user to open a file automatically on opening the app. Console.log shows `DOMException: Failed to execute 'requestPermission' on 'FileSystemHandle': User activation is required to request permissions.`

This is now the worst of both worlds. The Permissions dialogue doesn't show AND access is blocked. Prior to this (at least in 22.3.25, I didn't test releases in-between) we could bypass all such permissions by adding the "enable-experimental-web-platform-features" option.

To be clear, if a user provides a gesture, then access is granted. But as we don't get the Persistent Permissions prompt (no prompt at all), this means that auto-opening of a file on startup is now blocked!

@codebytere Can you re-open?

**Comment by Jaifroid** [comment]
Apologies, I see the new implementation is in alpha, and it requires explicitly setting the permissions wanted, like:

```
session.defaultSession.setPermissionRequestHandler((webContents, permission, callback, details) => {
      console.log(permission) // 'fileSystem'
      console.log(details) 
      /*
      {
          accessType: 'writable',
          isDirectory: false,
          isMainFrame: true,
          path: '/path/to/my/file',
          requestingUrl: 'some_url.html'
        }
      */
      callback(true);
    }
);
````
I'll try this and report back.

**Comment by Jaifroid** [comment]
So, I added this code to `main.cjs`:
```
// Set default File System Access permissions
mainWindow.webContents.session.setPermissionRequestHandler((webContents, permission, callback, details) => {
    console.log('Setting permission for: ' + permission); // 'fileSystem'
    console.log('File System Access details:', details); 
    callback(true);
});
```
It is called when I pick a file. **But it is not called when I attempt to access the file on startup of the app.**

On startup, I retrieve the file handle and call `fileHandle.queryPermission(opts)`. Instead of going through the broker in `main.cjs`, this merely returns 'prompt' instead of 'granted' for the permission. When I try to do 'fileHandle.requestPermission(opts)` the broker isn't called either, and I get the error `DOMException: Failed to execute 'requestPermission' on 'FileSystemHandle': User activation is required to request permissions.`.

@codebytere Is this a known issue? Is there a workaround? Should I open a separate issue?

**Comment by codebytere** [comment]
hey @Jaifroid - yes, the API added doesn't support Persistent Permissions. I can look to address this is a follow-up but it would involve far more considerations and design decisions than the original PR so i excluded it from scope.

**Comment by Jaifroid** [comment]
> hey @Jaifroid - yes, the API added doesn't support Persistent Permissions. I can definitely look to address this is a follow-up but it would involve far more considerations and design decisions than the original PR which is why it was not included in the original PR's scope

Thank you very much @codebytere. I'll open a separate issue and link it to this one. But it strikes me that the spirit of Electron is to allow file system access by default, and a simple (?) or interim solution would be to continue with the behaviour in 29.x of bypassing permissions (including the startup user gesture requirement) if `enable-experimental-web-platform-features` is set. I realize this may conflict with the new permissions feature you coded, so may not be easy or desirable.

**Comment by bradisbell** [comment]
@codebytere This new API seems to contain a regression.  Before v30, this code worked:

```javascript
const baseDir = /* Get previously-granted FileSystemDirectoryHandle from IndexedDb */
await baseDir.getDirectoryHandle('sub-dir', { create: true } )
```

Now, when I try to create that sub-directory:

> DOMException: The request is not allowed by the user agent or the platform in the current context.

What can be done?  Any workaround?  Thank you.

**Comment by dsanders11** [comment]
@bradisbell, please create a separate issue with a minimal repro. You can reference this issue in the new issue.
