### ISSUE TITLE
[Bug]: Full sized transparent 'overlay' window - lagging screen despite high fps in game 

### ISSUE THREAD

**Issue by iamisti** [electron/electron#28439]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

9.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

Transparent window renders smoothly with high fps.

### Actual Behavior

Transparent window renders seemingly with low fps.

- I'm using app.disableHardwareAcceleration() to make the electron app using much less CPU.
- When I create a full-sized window (not fullscreen) which is transparent (i do it to have some overlays for a specific game running behind the transparent window), the screen start lagging like I have 20 fps. 
The game is running with 120 fps, but because of the overlay window it feels like 20fps.
- The problem is going away when I don't use app.disableHardwareAcceleration(false), everything is smooth then. But CPU spikes up significantly, so I'd prefer not to use this way.

How do I eliminate the lagging behavior?
Here is what I’ve tried but did not help:
- tried to set backgroundThrottling to false
- tried to set setFramerate (although i know it only works in offline paint mode)

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

**Comment by iamisti** [comment]
But this is a bug! @nornagon 
It's not a discussion or feature request. IT's clearly a bug!

**Comment by iamisti** [comment]
It's still a big @nornagon , you can't just close it and forget about it!

**Comment by dragonDScript** [comment]
You should reduce the quantity of DOM that you work with - like in any web app. Btw, does this happen when transparent: false? And when hardware acceleration is enabled?

**Comment by iamisti** [comment]
I'm sorry but did you read my report?
"The problem is going away when I don't use app.disableHardwareAcceleration(false), everything is smooth then. But CPU spikes up significantly, so I'd prefer not to use this way."

It's not about the DOM elements. It's about the fact that it's lagging despite there is no reason to.

**Comment by dragonDScript** [comment]
> I'm sorry but did you read my report?
> "The problem is going away when I don't use app.disableHardwareAcceleration(false), everything is smooth then. But CPU spikes up significantly, so I'd prefer not to use this way."
> 
> It's not about the DOM elements. It's about the fact that it's lagging despite there is no reason to.

There is. Hardware acceleration smooths things a lot.

**Comment by iamisti** [comment]
> > I'm sorry but did you read my report?
> > "The problem is going away when I don't use app.disableHardwareAcceleration(false), everything is smooth then. But CPU spikes up significantly, so I'd prefer not to use this way."
> > It's not about the DOM elements. It's about the fact that it's lagging despite there is no reason to.
> 
> There is. Hardware acceleration smooths things a lot.

And what the reason is? Even without any element there is a lag. Just a simple transparent window as big as the screen and behind the game running.
