### ISSUE TITLE
[Bug]: {"reason":"crashed","exitCode":-1073740791}

### ISSUE THREAD

**Issue by ezailWang** [electron/electron#28430]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.1

### What operating system are you using?

Windows

### Operating System Version

Window 10 家庭中文版 1709 16299_371

### What arch are you using?

x64

### Expected Behavior

Electron invokes the write file operation in the main process and runs normally

### Actual Behavior

Electron calls the write file operation in the main process, tries to call it several times, and {"reason":"crashed","exitCode":-1073740791}  errors occur

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by ckerr** [comment]
Google says -1073740791 (0xC0000409) is a stack buffer overrun

>STATUS_STACK_BUFFER_OVERRUN is a /GS exception. They are thrown when Windows detects 'tampering' of a security cookie protecting a return address. It is probable that you are writing something past the end of a buffer, or writing something to a pointer that is pointing to the wrong place. However it is also possible that you have some dodgy memory or otherwise faulty hardware that is tripping validation code.

**Comment by ezailWang** [comment]
Thanks for your quick reply. We are trying to use Electron Fiddle

**Comment by Auxxxxlx** [comment]
Any update?

**Comment by mor-o** [comment]
Hi, this happened to me as well, anyone has an idea why this is happening?

**Comment by dtanzer** [comment]
Just happened to me as well, after updating an electron-based app to the newest version (using the auto-updater)

**Comment by nornagon** [comment]
I'm closing this as there's no repro and no further details. If you can reproduce this with a minimal test case using Electron Fiddle or otherwise, please open a new issue.
