### ISSUE TITLE
[Bug]: Electron process becomes unresponsive to SIGINT

### ISSUE THREAD

**Issue by Androbin** [electron/electron#28437]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04.2

### What arch are you using?

x64

### Expected Behavior

Sending a SIGINT signal to the Electron process kills the process.

### Actual Behavior

Sending a SIGINT signal to the Electron process does not kill the process.

`package.json`
```json
{
  "name": "test",
  "main": "main.js",
  "scripts": {
    "postinstall": "electron-builder install-app-deps",
    "start": "electron ."
  },
  "dependencies": {
    "puppeteer": "^8.0.0",
    "puppeteer-extra": "^3.1.16",
    "puppeteer-extra-plugin-stealth": "^2.7.6"
  },
  "devDependencies": {
    "electron": "^12.0.2",
    "electron-builder": "^22.10.5"
  }
}

```

`main.js`
```js
const puppeteer = require('puppeteer-extra')
const StealthPlugin = require('puppeteer-extra-plugin-stealth')
puppeteer.use(StealthPlugin())
puppeteer.launch().then(browser => browser.close());
```

**Comment by VerteDinde** [comment]
Hey @Androbin, thanks for reporting this and helping to make Electron better!

Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's. Based on the code you have in your `main.js` file snippet above, I'm wondering if this is primarily an issue with Puppeteer. Can you confirm whether or not this issue is only happening when you're using Puppeteer?

**Comment by Androbin** [comment]
@VerteDinde It's happening only when both `puppeteer.use` and `browser.close` are used. I should note that `puppeteer-extra` is not maintained by the Puppeteer team.

**Comment by Androbin** [comment]
It seems like the cause has been found in `puppeteer-extra-plugin-user-data-dir`
