### ISSUE TITLE
Windows 10:  Elecrtron requests don't go to the proxy server when “Automatically detect settings” is set, but Chrome browser works

### ISSUE THREAD

**Issue by gujinku** [electron/electron#28434]
One of our customers set its network proxy in their company. They find that our Electron app has different behaviors from browsers, like Chrome. Our app's network traffic can go through the proxy on browsers but not the Electron app.

It happens on Windows but not verified on Mac since they only use Windows PC.
They can reproduce the issue when “Automatically detect settings” or “use setup script” is turned on.
When they choose “Use a proxy server” under the “Manual setup proxy”, the issue disappears.

Our app is using Axios which is based on the XMLHttpRequest library, all network requests are all based on the renderer process. Per our understanding, chromium within the Electron will automatically handle the proxy auto-detection and redirect all the network requests will go to the proxy server.  So based on the Electron document, all the requests should be proxied automatically. 

We are using Electron 9.3.1 and we tried 11.2.3 as well. Both fail.

We have been struggling with this issue for almost one month.

Could anyone please help?  Much appreciated!

<img width="500" alt="Screen Shot 2021-03-29 at 11 03 28 PM" src="https://user-images.githubusercontent.com/6347795/112914300-3e057400-912e-11eb-957a-23eb5f9f8e9d.png">

**Comment by VerteDinde** [comment]
Hey @gujinku, thanks for reporting this issue! It's difficult to say exactly what's failing with the proxy without seeing your code. Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, Electron Fiddle is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

One other thing you could look at: you mention that you're using Axios, but it would be helpful to know what proxy your customer is using. Depending on their proxy, you may need to explicitly set allows for us. I would check how you're setting up a session - you can see an example of doing this allow for NTLM here: https://www.electronjs.org/docs/api/session#sesallowntlmcredentialsfordomainsdomains

Thanks in advance! Your help is appreciated.

**Comment by gujinku** [comment]
Hi @VerteDinde , thank you for the update.  We tried the NTLM in our app, it turns out NOT work.  We'll provide the demo app as requested
