### ISSUE TITLE
[Bug]: navigator.geolocation.getCurrentPosition isn't working (GeolocationPositionError:Timeout expired)

### ISSUE THREAD

**Issue by hardi00000** [electron/electron#28443]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.2.3

### What arch are you using?

x64

### Last Known Working Electron version

10.4.2

### Expected Behavior

Calling of `navigator.geolocation.getCurrentPosition()` is returning coordinates (latitude and longitude) and not disabling provided access to Location Services in case of any platform (macOS / Windows / Linux). 

### Actual Behavior

Calling of `navigator.geolocation.getCurrentPosition()` is disabling provided access to Location Services (macOS: System settings -> Security & Privacy -> Privacy -> Location Services). Looks like it's a reason why the app is getting  as response: `GeolocationPositionError (code: 3, message: Timeout expired)`. Geolocation isn't working in case of any platform (macOS / Windows / Linux) since Electron **11.0.0**.

### Testcase Gist URL

https://gist.github.com/3e1667de4e59b5ddd9caf8b5c5711515

Before using gist, please be sure, that:
1) you have `GOOGLE_API_KEY`
2) `GOOGLE_API_KEY` is having right set-up:
- isn't having any application restriction
- restricted by Geolocation API
- linked to billing account, which is validated by Google
5) `GOOGLE_API_KEY` added to: `main.js, line 3` of the gist

**Comment by ttibau** [comment]
I've the same problem. 

Any updates? 

Thanks

**Comment by quanglam2807** [comment]
Confirmed. It doesn't work.

**Comment by castroCrea** [comment]
Any news ?

**Comment by salmanSOFTECH** [comment]
@castroCrea Same is happening for me as well. If I enable the Location service by myself for the app then it works. Otherwise it doesn't come in callback. Working perfectly on windows. Let me know if you have completed this task.

**Comment by castroCrea** [comment]
@salmanSOFTECH yes it work but this is not user friendly. The autorisation pop up need to show up.

**Comment by raphaelschaad** [comment]
I couldn't quite verify this, but allegedly it did pop up on older Electron/macOS versions, but in the latest combination (latest Electron, macOS Big Sur) this isn't working (anymore).

**Comment by salmanSOFTECH** [comment]
@raphaelschaad @castroCrea After downgrading to 10.4.2 it is working now. Looks like the new version is not supported yet with latest macOS.

**Comment by raphaelschaad** [comment]
bump

**Comment by SadakVali** [comment]
bump

**Comment by Naman-pokhriyal** [comment]
bump

**Comment by thucvu97** [comment]
bump

**Comment by thucvu97** [comment]
add the env.GOOGLE_API_KEY , it works <3
