### ISSUE TITLE
[Bug]: Updated color mode (dark or light) doesn't work when install in machine Windows

### ISSUE THREAD

**Issue by alissonmene** [electron/electron#28444]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

9.3.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

Updating theme by windows

### Actual Behavior

When event updated theme  (dark or light) system on dev works but creating a appx and install in machine doesn't work.

nativeTheme.on("updated", (event) => {
  win.webContents.send("update-theme", 'dark' or 'light');
});

**Comment by gaodeng** [comment]
Hi @nornagon ，can you reopen this issue, I tried electron 11 also has problems. When the app is packaged in appx format, the updated event of nativeTheme is not triggered after installation, but strangely enough, the updated event can be triggered normally by opening exe and running

**Comment by nornagon** [comment]
@gaodeng would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm reopening this but adding `blocked/need-repro`.

**Comment by gaodeng** [comment]
hi @tekxi , I'm afraid I can't reproduce this problem with Electron Fiddle. As mentioned above, this problem only occurs with apps installed in appx format. If you unzip the appx, run the exe directly and switch the system theme, the updated event will be triggered normally.

**Comment by gaodeng** [comment]
hi @nornagon  , I'm afraid I can't reproduce this problem with Electron Fiddle. As mentioned above, this problem only occurs with apps installed in appx format. If you unzip the appx, run the exe directly and switch the system theme, the updated event will be triggered normally.
