### ISSUE TITLE
[Bug]: Attached browserView having an invisible draggable top bar (buggy draggable region inheritance)

### ISSUE THREAD

**Issue by nomagick** [electron/electron#28440]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

macOS

### Operating System Version

11.2.3 (20D91)

### What arch are you using?

x64

### Expected Behavior

BrowserView should not be draggable when not positioned in the dragable region of parent window.

### Actual Behavior

BrowserView could be used to drag parent window around.

This unwanted dragable reagion could be overridden by `-webkit-app-region: no-drag;` from inside the browserView inner content;

The browserView was positioned right under the draggable top bar of the parent window.

It seems the browserView inherited the draggable paramaters of the parent. Which is unwanted behavior.

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
Closing as no response was provided. We are happy to re-open this issue should more information be provided.
