### ISSUE TITLE
[Bug]: calling BrowserWindow.setBounds() or setSize() before show(), makes a flash between previous size and new one

### ISSUE THREAD

**Issue by xpirt** [electron/electron#28442]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 20H2 - build 19042.870

### What arch are you using?

x64

### Expected Behavior

Calling `BrowserWindow.setBounds()` (or `BrowserWindow.setSize()`) before calling `BrowserWindow.show()` should show the window with correct size without showing transition flashing between previous size and the new size.

### Actual Behavior

The window _flashes_ from the previous lower size to the new higher size (not viceversa).

### Testcase Gist URL

https://gist.github.com/xpirt/4e3e92fcd866fcf812c49d8439b6f6d2

This has been tested on Windows 10 and macOS (although here seems to be less noticeable, more with transparency enabled).

The window show a flash tranisition between previous size (`height: 200`) to new one (`height: 600`). This seems to happen only from a lower size to a higher one. In fact, from `height: 600` to `height: 200` the transition flash does not seem to occur.
The gist test I've created registers a global shortcut `Ctrl(Cmd)+Shift+T` that shows/hides the window changing its bounds before toggling the visibility.

(For flash I mean a few milliseconds you can see the previous window size and right after the new size gets applied)

**Comment by pushkin-** [comment]
I wonder if this is basically a dupe of [this one](https://github.com/electron/electron/issues/28084)

**Comment by xpirt** [comment]
@pushkin- Not sure if that issue happens also on macOS, they may have the same root cause but definitely not a duplicate.
