### ISSUE TITLE
[Bug]: Updated color mode (dark or light) doesn't work when install in windows machine

### ISSUE THREAD

**Issue by raonybarbosa** [electron/electron#28460]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

Updating theme by windows.

### Actual Behavior

When event updated theme (dark or light) system on dev works but creating a appx and install in machine doesn't work.

nativeTheme.on("updated", (event) => {
win.webContents.send("update-theme", 'dark' or 'light');
});

**Comment by VerteDinde** [comment]
Thanks for reporting this issue! I unfortunately wasn't able to repro the issue with just the snippet you provided in Electron Fiddle. Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, Electron Fiddle is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
Closing as no response was provided. Should more come to light, we can re-open.

**Comment by gaodeng** [comment]
Hi @codebytere ，can you reopen this issue, I tried electron 11 also has problems. When the app is packaged in appx format, the updated event of nativeTheme is not triggered after installation, but strangely enough, the updated event can be triggered normally by opening exe and running
