### ISSUE TITLE
[Bug]: Frameless windows do not trigger drop, dragover, dragenter, and dragleave events

### ISSUE THREAD

**Issue by jmkd3v** [electron/electron#28464]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 20H2

### What arch are you using?

x64

### Expected Behavior

Frameless windows should still trigger `drop`, `dragover`, `dragenter` and `dragleave` events.

### Actual Behavior

None of these events are triggering when the window has no frame. All of these events trigger as expected when the frame is shown.

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by jmkd3v** [comment]
Oddly, I'm unable to reproduce the issue in Electron Fiddle. Even with the exact same code and electron version, it seems to work fine inside of Electron Fiddle but not outside. I'll have to keep looking into this.

**Comment by jmkd3v** [comment]
Update - I was only able to reproduce this issue when I set the `width` and `height` property body and html elements to `100%`.
