### ISSUE TITLE
Electron fails to start: npm ERR! code ELIFECYCLE 

### ISSUE THREAD

**Issue by JROhara-rsl** [electron/electron#28476]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina version 10.15.7

### What arch are you using?

x64

### Expected Behavior

start my app successfully with :
cd my-app
npm start

### Actual Behavior

When running npm start I get the following error:

sh: electron-forge: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! my-app@1.0.0 start: `electron-forge start`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the my-app@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/imac12/.npm/_logs/2021-04-01T17_03_07_957Z-debug.log
imac12@iMac-de-Imac my-app % 

Hi, 

I'm starting with electron so I'm a beginner. 
At the beginning, I could start successfully my app and I searching to build a package for mac and pc with electron-builder. 
But after try that, I have this error then after clear cache, reinstalle node, homebrew and electron, I don't know what to do. 

Thank you

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!

P.S. It looks like you might have forgotten to run `npm install`.
