### ISSUE TITLE
[Bug]: Version mismatch between V8 binary and snapshot.

### ISSUE THREAD

**Issue by xland** [electron/electron#28490]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.2.1,12.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 7

### What arch are you using?

ia32

### Last Known Working Electron version

11.x.x

### Expected Behavior

run correctly

### Actual Behavior

When start app. this bug appread frequently

```
#
# Fatal error in , line 0
# Version mismatch between V8 binary and snapshot.
#   V8 binary version: 8.7.220.31-electron.0
#    Snapshot version: 8.9.255.19-electron.0
# The snapshot consists of 164724 bytes and contains 3 context(s).
#
#
#
#FailureMessage Object: 0016F0E4
 1: 03ACE68F node::Buffer::New+109887
 2: 03845642 IsSandboxedProcess+657522
 3: 02179C3F v8::internal::TickSample::print+781343
 4: 01D2EC59 v8::Isolate::Initialize+201
 5: 03851E14 IsSandboxedProcess+708676
 6: 011DC70C v8::WasmModuleObjectBuilderStreaming::GetPromise+60108
 7: 011D50CF v8::WasmModuleObjectBuilderStreaming::GetPromise+29839
 8: 028BCB56 uv_handle_set_data+4125958
 9: 028C0B57 uv_handle_set_data+4142343
10: 028BC2FD uv_handle_set_data+4123821
11: 027C7976 uv_handle_set_data+3121958
12: 027C75FD uv_handle_set_data+3121069
13: 01C4E7B1 uv_backend_fd+194577
14: 01C4EA6F uv_backend_fd+195279
15: 0112143C Ordinal0+5180
16: 066E6A9A uv_random+15761482
17: 7678343D BaseThreadInitThunk+18
18: 77979812 RtlInitializeExceptionChain+99
19: 779797E5 RtlInitializeExceptionChain+54
```

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by xland** [comment]
Sorry , I can not
This issue appears not regularly.

**Comment by hxkuc** [comment]
i have same crash 

STACK_TEXT: 
0dbcf3f8 003f2322 _____!v8::WasmModuleObjectBuilderStreaming::GetPromise+0x1232
 STACK_COMMAND: .ecxr ; kb ; ** Pseudo Context ** Pseudo ** Value: 24b1171e9a0 ** ; kb SYMBOL_NAME:
