### ISSUE TITLE
[Bug]: print() doesn't respect deviceName if silent==true

### ISSUE THREAD

**Issue by k2s** [electron/electron#28502]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Home Single Language 20H2 19042.867

### What arch are you using?

ia32

### Last Known Working Electron version

11.4.2

### Expected Behavior

This script should print to all existing printers. The printers "Microsoft XPS Document Writer" and "Microsoft Print to PDF" should block the loop and ask for file name.

### Actual Behavior

All prints will return success, but print will happen always only to print set as default in system.

### Testcase Gist URL

https://gist.github.com/fc8b4a9fbf986965c51e8f92b8ddb39f

Good way to run the test is to set printer "Microsoft Print To PDF" as default printer.

**Comment by pedromoraisf** [comment]
Up, happened to me too

**Comment by pedromoraisf** [comment]
Another thing that prevented the debugging of the bug was the return of the error in the callback of the "print" method.
In my case, it just returned "failed" 🤦🏽‍♂️

**Comment by almassapargali** [comment]
Happened to us too, is there any ETA for fix? We have some critical logic tied to this API.

**Comment by almassapargali** [comment]
I've tried different versions of Electron, and printing to specific device works correctly on 11.4.6, and broken on 12.0.0. @codebytere could #27225 cause this issue?

**Comment by matschek** [comment]
I can confirm this bug for 12.0.7 and 13.0.0-beta.26

**Comment by almassapargali** [comment]
Is there any ETA?

**Comment by k2s** [comment]
last working is 11.4.9
versions 12,13,14 don't work

**Comment by pushkin-** [comment]
that suggests it may be an issue with the Chromium rollout. To be clear the latest 11 patch version works, but it's broken in 12.0.0? Is it broken with the earliest 12 beta?

**Comment by k2s** [comment]
@pushkin- I am testing it with Electron Fiddle, Gist Test case is in the ticket. 

v11.4.9 - works
v12.0.0-beta.1 - doesn't work
v12.0.0 - doesn't work

**Comment by codebytere** [comment]
Duplicate https://github.com/electron/electron/issues/29334

**Comment by jaovitubr** [comment]
ETA?

**Comment by jbool24** [comment]
Any updates?
