### ISSUE TITLE
[Bug]: gap css property does not work in electron (flexbox)

### ISSUE THREAD

**Issue by iamisti** [electron/electron#28503]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

9.0.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

Electron should also respect gap css property in flexbox elements

### Actual Behavior

Electron does not respect 'gap' css property in flexbox elements.
It doesn't matter what gap value you specify, it won't change anything.

**Comment by miniak** [comment]
Electron 9 is not supported anymore. Please check if it reproduces on latest Electron 12.

**Comment by Prinzhorn** [comment]
`gap` is supported since Chrome 84. Electron 9 shipped with Chrome 83.

https://caniuse.com/?search=gap

**Comment by iamisti** [comment]
Wow thanks @Prinzhorn ! Did not realize that. That's a great help!
