### ISSUE TITLE
[Bug]: backdrop-filter blur does not remove elements behind

### ISSUE THREAD

**Issue by qt-autumn** [electron/electron#28506]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.3.0

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux

### What arch are you using?

x64

### Expected Behavior

When using the backdrop-filter blur effect with a transparent window, any elements (text, images, etc.) behind the element with the filter are removed before the blur is drawn, leaving just the blur of the elements.

### Actual Behavior

Elements behind the element with the filter will still be drawn, along with the blur as well. Normally this wouldn't be a problem, but when transparency is involved, the elements behind will show through.

along with the description above, I've also mocked up (in GIMP) what I'm attempting to achieve, and what is currently happening as a visual aid
What I want to achieve
![image](https://user-images.githubusercontent.com/31020691/113512041-3159a380-95a6-11eb-8c7f-a80b3ce803df.png)
What I'm getting
![image](https://user-images.githubusercontent.com/31020691/113512081-58b07080-95a6-11eb-8634-6e8e4930bd50.png)
What it looks like in my project
![image](https://user-images.githubusercontent.com/31020691/113512142-a7f6a100-95a6-11eb-96e6-19d9b11f154d.png)

**Comment by Prinzhorn** [comment]
Can you please provide a simple test case with minimal code? Electron Fiddle is great tool to put something together https://github.com/electron/fiddle It's also useful to quickly experiment with different ideas and APIs instead of setting up a new project.

**Comment by qt-autumn** [comment]
@Prinzhorn No problem, here you go!
https://gist.github.com/c83bb60899d53d3ed3fdff5496be98b4

**Comment by zcbenz** [comment]
The algorithms of some filters would take the background of page into account when doing calculation, so when the background is transparent, the algorithm may fail to present expected rendering.

This result is the nature of the algorithm's implementation with transparent background, so I'm afraid this issue is not something we can fix, and I'm closing it as won't fix.
