### ISSUE TITLE
[Bug]: BrowserView position is wrong when redisplayed

### ISSUE THREAD

**Issue by convictss** [electron/electron#28508]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.3.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 1909

### What arch are you using?

x64

### Last Known Working Electron version

11.3.0

### Expected Behavior

When the window is hidden and then redisplayed, the position of the browserView is the same as before hiding.

### Actual Behavior

BrowserView position is wrong when redisplayed.

### Some key codes:
```
win.on('close', (e) => {
    win.hide();
    win.setSkipTaskbar(true);
    e.preventDefault();
});
win.loadFile('index.html');

view = new BrowserView();
win.setBrowserView(view);
view.setBounds({x: 0, y: 0, width: 300, height: 300});
view.setAutoResize({width: true, height: true, horizontal: true, vertical: false});
view.webContents.loadURL('https://www.google.com');
```

### Before hide:
![1](https://user-images.githubusercontent.com/39207692/113538468-eb382a80-960d-11eb-80d6-9534658688d6.png)

### Hide and redisplay:
![2](https://user-images.githubusercontent.com/39207692/113538518-030fae80-960e-11eb-9636-eefb2777eff6.png)

**Comment by codebytere** [comment]
@convictss we need a _reproducible sample_ we can load and run into [Fiddle](https://github.com/electron/fiddle/). Without that, we are forced to make guesses which makes triage more difficult. Please provide this for us to continue.

**Comment by convictss** [comment]
@codebytere 

Testcase Gist URL：[https://github.com/convictss/electron-bug-case](url)
1. ```npm install```
2. ```npm start```
3. Type ```CommandOrControl+Alt+y``` hide/show main window. 
4. When the main window was hid, if i type ```CommandOrControl+Alt+y```, then it will redisplay, and the BrowserView position was changed.

**Comment by convictss** [comment]
Hello? @codebytere

**Comment by codebytere** [comment]
Cannot reproduce with https://gist.github.com/491ee83dd5f0ba62c55b73a27d544072

**Comment by convictss** [comment]
```CommandOrControl+Alt+y```: show or hide BrowserWindow

That is the behavior I see. But after the second display, the position of the **BrowserView**(Not BrowserWindow) has changed relative to the first run, and since then the **BrowserView** has never been in the same position as it was when it first ran.

You can see the content of this issue.
