### ISSUE TITLE
[Bug]: Can't use electron with esbuild

### ISSUE THREAD

**Issue by dragonDScript** [electron/electron#28501]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 21.04

### What arch are you using?

x64

### Last Known Working Electron version

not applicable

### Expected Behavior

Electron installs correctly and runs the app

### Actual Behavior

Electron throws this error: `Uncaught Exception:
Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/mnt/sda1/Projects/electric-gui/dist/main.bundle.js:34:13)
    at /mnt/sda1/Projects/electric-gui/dist/main.bundle.js:37:21
    at /mnt/sda1/Projects/electric-gui/dist/main.bundle.js:8:45
    at Object.<anonymous> (/mnt/sda1/Projects/electric-gui/dist/main.bundle.js:41:34)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at loadApplicationPackage (/mnt/sda1/Projects/electric-gui/node_modules/electron/dist/resources/default_app.asar/main.js:110:16)
` even if I reinstalled the modules.

NOTE: Since this issue involves a bundler, I can't use Fiddle.
Instructions:
```bash
git clone https://github.com/dragonDScript/electron-esbuild
cd electron-esbuild
yarn # needs yarn to be installed. as an alternative, use npm
yarn dev
```

**Comment by vladimiry** [comment]
Looks like you need to enable proper https://webpack.js.org/configuration/externals/ alternative in "esbuild". See https://github.com/webpack/webpack/blob/b9519dcf013c717d598da06f535cee72eb93bf18/lib/electron/ElectronTargetPlugin.js for more details.

**Comment by dragonDScript** [comment]
Thanks, for anyone having the same issue I found out [this](https://github.com/pradel/esbuild-node-externals).
