### ISSUE TITLE
[Bug]: select-serial-port callback crashes when called with an invalid serial port ID

### ISSUE THREAD

**Issue by ntamas** [electron/electron#28500]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina 10.15.7

### What arch are you using?

x64

### Expected Behavior

Returning an invalid serial port ID in the callback of the `select-serial-port` event handler of `session` should not crash Electron.

### Actual Behavior

Returning an invalid serial port ID in the callback of the `select-serial-port` event handler of `session` crashes Electron with a SIGSEGV. Calling the callback with `"foo"` or any string that is clearly not a valid serial port ID is enough to trigger the bug. Valid serial port IDs and empty strings work as expected.

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by ntamas** [comment]
[Here is an Electron Fiddle](https://gist.github.com/36ce5ef35c2427180b157d2903263846) that reproduces the issue on my machine with Electron v13.0.0-beta.8
