### ISSUE TITLE
[Bug]: require not defined in renderer process

### ISSUE THREAD

**Issue by pabatribick** [electron/electron#28504]
### Electron Version

12.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro 10.0.19042 Build 19042

### What arch are you using?

x64

### Expected Behavior

Renderer process should be able to require the electron API

### Actual Behavior

After opening the App, in the Console, I get the error message "Uncaught ReferenceError: require is not defined
    at renderer.js:1". But it should be available here.

 I wanted to communicate between main and renderer process, but no provided demo is working from your sites.

**Comment by Prinzhorn** [comment]
> but no provided demo is working from your sites.

Could you point to some of those demos so they can be fixed?

> I wanted to communicate between main and renderer process

Like I said I'd rather see the examples you've mentioned updated. But it goes like this:

1. Use a preload script
2. Inside the preload script use `contextBridge` to expose functions to the page https://www.electronjs.org/docs/api/context-bridge#contextbridge
3. Inside those functions you can use `ipcRenderer` to communicate with the main process

I guess this should be included with https://github.com/electron/electron-quick-start

**Comment by sedwards2009** [comment]
I encountered the same problem on 12.0.2 even though I've got `nodeIntegration` turned on. I noticed that setting `contextIsolation` to false gets `require()` working again.

**Comment by MarshallOfSound** [comment]
This is expected behavior as of V12, as @Prinzhorn outlined please use preloads scripts / contextBridge to do things in your app in a more secure way
