### ISSUE TITLE
Make nativeWindowOpen: true the default

### ISSUE THREAD

**Issue by nornagon** [electron/electron#28511]
The native window.open system has been better for quite a while now, and it resolves a lot of issues. We should make it the default and deprecate the old `BrowserWindowProxy`-based method.

**Comment by xueqianz** [comment]
Hello, glad to see this default option, so is it needed for me to set ```webPreferences.nativeWindowOpen = true``` explicitly in electron v14.0.0? 
And even if I set this option to `true` both for the main window and the webviews, my application still says ``` electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15``` in the console.
So how to avoid this warning?
Thanks!

**Comment by xueqianz** [comment]
I found the code https://github.com/electron/electron/blob/5530497c8244caa2e4f5d31a40656f24f07359d0/shell/browser/web_contents_preferences.cc#L144-L152
which will detect the `nativeWindowOpen` option and throw the warning if not set, but I did set that option in all `webPreferences` objects in my application, but I still get that warning...
So strange.

**Comment by xueqianz** [comment]
OK sorry for my bother, I think I get the root cause of this warning.
I am using the <webview> tag to make my application in multiple threads mode, and the option checking seems before the creation of the dom, am I right? So even if I set the property of the <webview> tag, it is not so in time to change the `nativeWindowOpen` option.
So... could you give me some tips to avoid the warning? I am not willing to fall back to v13.x.

**Comment by nornagon** [comment]
@xueqianz set `nativeWindowOpen: true` in your app to avoid the warning.

**Comment by xueqianz** [comment]
> @xueqianz set `nativeWindowOpen: true` in your app to avoid the warning.

Yes, of course, I have set this one in the main window, but it seems not working when I am using the <webview> tag. I have already set it for <webview> tag both in the `webpreferences` property and `will-attach-webview` event, it still throws that warning before the `will-attach-view` event is emitted.

In HTML:
```html
<div className="class1">
          <webview className="class2"
                src="http://xxx"
                webpreferences="nativeWindowOpen=yes"
          />
</div>
```

In JS (`will-attach-webview` event):
```
o      webContents.on("will-attach-webview", (event, webPreferences, params) => {
               webPreferences.nodeIntegrationInWorker = true;
               webPreferences.sandbox = false;
               webPreferences.nativeWindowOpen = true;
        })
```

And I still get that warning before the breakpoint I set at the `o` position.

**Comment by theodoranice** [comment]
When I launch the electron server I always have this message that is displayed and the process does not continue


 Passthrough is not supported, GL is disabled

**Comment by tomprogers** [comment]
It's awful that this is the URL provided by the electron warning, since this thread does not provide a confirmed solution for migrating.

**Comment by Delagen** [comment]
> It's awful that this is the URL provided by the electron warning, since this thread does not provide a confirmed solution for migrating.
> 
> Here is how I fixed it:
> 
> ```js
> // in main thread, when instantiating a new renderer
> mainWindow = new BrowserWindow({
> 	webPreferences: {
> 		nativeWindowOpen: true // ADD THIS
> 	}
> })
> ```
> 
> Experimentation shows you don't need to define a handler for `will-attach-webview` to set this option, and in fact doing that alone did not eliminate the warning.

This solution make webContents.setWindowOpenHandler never trigger and does not open any browser window in case of external url

**Comment by xueqianz** [comment]
> It's awful that this is the URL provided by the electron warning, since this thread does not provide a confirmed solution for migrating.
> 
> Here is how I fixed it:
> 
> ```js
> // in main thread, when instantiating a new renderer
> mainWindow = new BrowserWindow({
> 	webPreferences: {
> 		nativeWindowOpen: true // ADD THIS
> 	}
> })
> ```
> 
> Experimentation shows you don't need to define a handler for `will-attach-webview` to set this option, and in fact doing that alone did not eliminate the warning.

This is the first step to solve the warning from the main webview, which I have already mentioned in my first post in this thread. But what if you use <webview> tag? I agree with you that the URL provided by the electron warning doesn't provide any solution.

**Comment by xueqianz** [comment]
> This solution make webContents.setWindowOpenHandler never trigger and does not open any browser window in case of external url

You can also set `nativeWindowOpen: false`, to use the `setWindowOpenHandler`, this warning is not telling you that this option is deprecated, it just infers that you need to set it explicitly if you don't want to use the native openhandler from electron 15.

**Comment by theodoranice** [comment]
Thanks both works, just that I can't load the data anymore which I will see

**Comment by nornagon** [comment]
Just to note, it is planned to remove `nativeWindowOpen: false` in an upcoming version of Electron. If you are experiencing issues with `setWindowOpenHandler` and `nativeWindowOpen: true`, please open a new issue so we can get it fixed!

**Comment by u2m4c6** [comment]
This issue is present in the latest quick start: https://www.electronjs.org/docs/latest/tutorial/quick-start

I definitely recommend that the documentation and/or warning is updated to be more clear on what is NOT depreciated. Having to trace down a Github issue about a depreciated issue is not a great first impression for a "Quick Start."

**Comment by theArina** [comment]
hello, @xueqianz, I'm experiencing the same issue, did you find the solution ?
