### ISSUE TITLE
[Bug]: Resources loaded over custom protocol bypass service worker

### ISSUE THREAD

**Issue by mjbvz** [electron/electron#28528]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.0.0-beta-11

### What operating system are you using?

macOS

### Operating System Version

11.2.3

### What arch are you using?

x64

### Last Known Working Electron version

NA

### Expected Behavior

The service worker should be invoked first, falling back to the custom protocol

In the example, you can see that resources from the custom protocol, such as `test-scheme://authority/inner-img.png`, do not seem to trigger a fetch event in the service worker. Instead I only see the `test-scheme` protocol being invoked.  You can see this in the main log as `Trying to load resource using protocol: test-scheme://authority/inner-img.png`

However resources outside of the custom protocol, such `http://example.com/img.png`, do go through the service worker, Here if you open the developer tools, you can see `fetching in worker http://example.com/img.png` is logged

### Actual Behavior

The requests on the custom protocol seem to bypass the service worker and go directly to the custom protocol

### Testcase Gist URL

https://gist.github.com/775d15105c18d704741f1e4a460e4c5e

**Example Explained**
1. Register a custom protocol (`test-scheme`)
2. Load an iframe using the custom protocol: `test-scheme://authority/index.html`
3. Inside the iframe, register a service worker
4. After the service worker is registered, try loading resources inside the iframe. In the example, I use setTimeout to make sure the worker is fully ready before writing two images into the iframe: one image that uses the `test-scheme` protocol and one that comes from a fake external endpoint (`http://example.com/img.png`)

**Comment by mjbvz** [comment]
/cc @deepak1556 For VS Code, this making adopting service workers a little more difficult but I don't think it blocks us.

Normally we'd try to load resources from the same endpoint where the webview itself is served from, for example:

```
vscode-webview://UUID/vscode-resource/path/to/resource
````

However because that does not go through the service worker, I am instead forcing webviews on desktop to use our `vscode-webview-test` endpoint for resources. We never expect to actually hit this endpoint, the entire purpose is to just make sure the service worker sees the request. 

This seems to work fine however I am a little weary about having the webview running on one original and the resources coming from another. I believe this could cause problems if javascript from extension is making assumptions about how we serve up webviews

**Comment by dsanders11** [comment]
@mjbvz, I've got a PR fixing the issue, after tracking it down it was just some missed plumbing in Electron so a fix is simple enough.
