### ISSUE TITLE
[Bug]: Electron 12 applications won't run on Mac OS 10.10

### ISSUE THREAD

**Issue by MarkBesseyLMI** [electron/electron#28520]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

macOS

### Operating System Version

MacOS 10.10

### What arch are you using?

x64

### Last Known Working Electron version

11.0

### Expected Behavior

According to the Supported Platforms documentation, Electron should support MacOS 10.10. The minimum system version in the Electron application is likewise set to 10.10 in the Info.plist.

### Actual Behavior

When run on MacOS 10.10, the application fails, with this error message in the console:
dyld: Symbol not found: ___NSArray0__

This is reproducible with the electron-quick-start project.

**Comment by nornagon** [comment]
I believe this is a case of the Info.plist and docs being wrong: https://github.com/electron/electron/pull/28480
