### ISSUE TITLE
[Feature Request]: Allow user-override of Chromium flags

### ISSUE THREAD

**Issue by zakius** [electron/electron#28537]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently it is impossible to change many settings as a user, in my case the offending one being inability to disable `enable-accelerated-2d-canvas` as the only solution to make text look right, there are also other flags affecting the look of text rendered by Blink and because of that some apps look less bad than others but personally I'd flip this one off in all of them anyway as I prefer sharp text over blurry

### Proposed Solution

Direct access to `chrome://flags` would probably be the easiest from user standpoint

### Alternatives Considered

Config file in user profile would work pretty fine as well

### Additional Information

I also thought of commandline switches but some apps use launchers that may not pass them to the main executable making it a bad idea as the only solution, though if it was one of available alternatives it would be useful

**Comment by solarkraft** [comment]
A possible solution would be an analog to `chrome-flag.conf` (`~/.config/chromium-flags.conf` on Linux), which lists all applied command line flags line by line.

**Comment by MarshallOfSound** [comment]
@zakius You should be able to toggle 99% of flags using `app.commandLine.appendSwitch('enable-features', 'BaseFeatureNameHere')`.  As long as you do that early during your apps initialization (before app ready) then they should work fine and be respected

**Comment by zakius** [comment]
and am I supposed to unpack and modify app every update? that's a great idea!

**Comment by solarkraft** [comment]
That's not a solution for system wide configuration, which is the request. The linked issue shows that the command line flag `--disable-smooth-scrolling` can massively improve user experience, but there is seemingly currently no way to apply it to all electron apps by default.

**Comment by offlinehacker** [comment]
Can this feature request get reopened, as it does not seem to be solved.
A way to set flags globally or per app without explicitly passing them on command line would be very useful for different cases like ozone for wayland support or to disable smooth scrolling and similar use cases. In these cases modifying original package sources or desktop files is not desired as they are platform specific.

**Comment by adonig** [comment]
I'm currently running into this issue with Fedora 37. VSCodium's user interface fonts are blurry on Wayland. I read in the Arch Linux wiki that you can simply add some flags to fix the issue. It works great when I pass the flags on the command line. I want this to happen automatically though. Arch Linux has a ` ~/.config/electron-flags.conf`. Electron on Fedora doesn't recognize that file though, which is kind of sad. There should be a system wide `/etc/electron.conf` where you can put stuff like that so electron works for all users.

**Comment by sepehr** [comment]
I can only second @adonig here as I'm exactly facing the same problem. It's a hassle to update these flags in the desktop shortcuts, flatpak overrides, etc. Would love to see this shipped.

**Comment by adonig** [comment]
Another great solution would be environment variables so you can pass the flags via `export ELECTRON_EXTRA_FLAGS=...` for all Electron apps like VSCode, Signal etc. in your .bashrc.

**Comment by sepehr** [comment]
If my understanding is correct, Shell-specific environment variables are not globally accessible to application that run outside that specific shell.

**Comment by adonig** [comment]
@sepehr I believe you can put system-wide environment variables in /etc/profile and the Gnome Shell should pick them up.
