### ISSUE TITLE
[Bug]: the new browerwindow can't show html until i move/max/min this new browerwindow

### ISSUE THREAD

**Issue by chenxiao1990** [electron/electron#28530]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

Windows

### Operating System Version

windows 10

### What arch are you using?

x64

### Expected Behavior

on render process click html button (use settimeout to run ipcRander.send is no problem), use ipcRander.send event,  main process hide this browerwindow and create a new browerwindow.  to show new html.

### Actual Behavior

the new browerwindow can't show html until i move/max/min this new browerwindow.

### Testcase Gist URL

https://github.com/chenxiao1990/electronissue

**Comment by zcbenz** [comment]
I can not reproduce it on my Windows 10 machine, it is very likely an issue that only happens on certain machines, I'm afraid there is nothing we can do with it with provided information.

**Comment by chenxiao1990** [comment]
I can reproduce this problem using the uploaded github.com/chenxiao1990/electronissue code. 
My three win10 computers have this problem.

**Comment by codebytere** [comment]
Closing in agreement with @zcbenz
