### ISSUE TITLE
[Bug]: upgrade to new version by electron-updater，but when I uninstall the app，it shows the old version

### ISSUE THREAD

**Issue by lingxiao-Zhu** [electron/electron#28538]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

9.3.0

### What operating system are you using?

Windows

### Operating System Version

win7 win10 

### What arch are you using?

ia32

### Expected Behavior

uninstall the app with correct version

### Actual Behavior

upgrade to new version by electron-updater，but when I uninstall the app，it shows the old version

**Comment by lingxiao-Zhu** [comment]
app.getVersion() returns 1.2.2，but uninstall shows 1.0.7

**Comment by lingxiao-Zhu** [comment]
![image](https://user-images.githubusercontent.com/22609330/113965192-7fe59700-985f-11eb-9ad2-63c3d5d87590.png)

**Comment by zcbenz** [comment]
It seems that the updater did not update Windows registry correctly, please report this bug to https://github.com/electron-userland/electron-builder instead, since the code of this repo is not responsible for updating the information of installed app.
