### ISSUE TITLE
[Bug]: getMediaAccessStatus of screen is 'denied', but it should be 'not determined'

### ISSUE THREAD

**Issue by asc0910** [electron/electron#28540]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.4.1

### What operating system are you using?

macOS

### Operating System Version

10.15.7

### What arch are you using?

x64

### Last Known Working Electron version

unknown

### Expected Behavior

`systemPreferences.getMediaAccessStatus('screen')` returns 'not determined'

### Actual Behavior

`systemPreferences.getMediaAccessStatus('screen')` returns 'denied'

Reproduce steps:
1. Add screen capture permssion to terminal
2. remove permission of terminal
3. run `tccutil reset ScreenCapture` to remove all permissions of screen capture
4. run electron in terminal
5. `systemPreferences.getMediaAccessStatus('screen') returns 'denied'

**Comment by codebytere** [comment]
This is not a bug - screen capture can never be non-determined as opposed to other permission types. It's [always allowed or denied](https://source.chromium.org/chromium/chromium/src/+/master:chrome/browser/media/webrtc/system_media_capture_permissions_mac.mm;l=142-151?q=CheckSystemVideoCapturePermission&ss=chromium)
