### ISSUE TITLE
Memory leak using Electron's Session

### ISSUE THREAD

**Issue by tstifxoxo** [electron/electron#28566]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.3

### What operating system are you using?

Windows

### Operating System Version

2010

### What arch are you using?

x64

### Expected Behavior

I want to create multiple partitions for each of my proxy i am testing. Expected behaviour for these partition to clear up in memory because they are too heavy after using them for my request. Because after using them, they no longer are needed. 

### Actual Behavior

I have need of using multiple different proxies that would map onto different sessions. The problem is after using these proxies my memory is really full and program crashes because garbage collector is not clearing partitions. My flow is to create new partition via (.fromPartition(name)) from https://www.electronjs.org/docs/api/session . After that, i simply do an HTTPs request and then program stops using this partition. Problem occurs that all these partitions are staying in memory and they never get cleared and they are very heavy which leads to my app crashing a lot.

```
var { session } = require('electron')
async function testProxy(proxy) {
    var name = 'persist:name' + proxy + ""
    var ses = session.fromPartition(name)   //this is causing a lot of memory usage and never gets cleared after using

    await ses.setProxy({
        proxyRules: proxy.split(':')[0] + ":" + proxy.split(':')[1],
        proxyBypassRules: "",
    });
    const request1 = net.request(
        {
            method: "GET",
            session: ses,
            url: 'https://RANDOMURL.COM/',
            headers: {
                'user-agent': "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36"
            }
        });
    request1.on('login', (authInfo, callback) => {
        callback(proxy.split(':')[2], proxy.split(':')[3])
    });
    request1.on('response', (response) => {
        response.on('data', (chunk) => {
        })
        response.on('end', () => {
            console.log(body)
        })
    });

    request1.end();
};
```

**Comment by Prinzhorn** [comment]
https://github.com/electron/electron/blob/968b30c9b4459e4f7030042b595f26926481e260/shell/browser/api/electron_api_session.cc#L1109-L1111

¯\_(ツ)_/¯

Depending on what makes your sessions "very heavy" maybe create sessions with cache disabled? Or rethink your architecture.

On the other hand, I'm not sure the code comment I've linked makes sense. I guess it optimized for a pattern where people keep doing `fromPartition` with the same string again and again without keeping a reference to the session. So Electron essentially caches the session for you and as we all know caching is one of the two main problems in CS :smile:

**Comment by tstifxoxo** [comment]
I am in need of using many proxies which can't really work under one partition. I sometimes have to add 100s of partitions and use 100 different proxies and this drains my memory a lot. One partition is like almost 1MB big. It creates huge problem. Only way i see doing this is to kill my process and restart again. I am not using old sessions thats problem, i only use them to rotate proxy but when i use same session and i try to import new proxy into it, the old one stays and it doesnt allow me to do it. That's why i have this
 ```
var name = 'persist:name' + proxy + ""
    var ses = session.fromPartition(name)   //this is causing a lot of memory usage and never gets cleared after using

    await ses.setProxy({
        proxyRules: proxy.split(':')[0] + ":" + proxy.split(':')[1],
        proxyBypassRules: "",
    });

```

**Comment by Prinzhorn** [comment]
So you need either of these two:

1. A `destroy` method on the session
2. A `proxy` option for `ClientRequest` that does not require a session

But whatever you are doing is an extremely rare use-case and thus probably very low priority to the Electorn team. However, I think option 1 is pretty useful and I'm surprised there is no method to destroy a session, at least in the docs.

**Comment by tstifxoxo** [comment]
How can i perform a destroy method on the session if there is no such method in first place?

Regarding 2. i am aware that you can't add proxies (that have authentication (username,pw)) if you don't use sessions. How can i utilize a proxy if i don't create a session before and pass it over to net request?

Im passing it in `session: ses` where ses contains that particular session initialized with a proxy.

**Comment by Prinzhorn** [comment]
> So you need either of these two:

This might have been confusingly worded, you read it as "You need to do either of these two". What I meant was: what you need is either of these two _added_ to Electron to solve your issue.

**Comment by tstifxoxo** [comment]
Ah ok, I understand now...

**Comment by tstifxoxo** [comment]
Or to allow me to use different proxies under same session... This is not possible now as using 
```
await ses.setProxy({
        proxyRules: proxy.split(':')[0] + ":" + proxy.split(':')[1],
        proxyBypassRules: "",
    });
```

Doesn't work if called twice on same session with different configuration @Prinzhorn

**Comment by Prinzhorn** [comment]
> Or to allow me to use different proxies under same session... This is not possible now as using

This option is asking for race-conditions in your application code though, because both `setProxy` and `net.request` are async. But it might be a valid solution.

I think we've laid out all option and maybe there is a workaround that I'm not aware of. Let's wait and see what someone from the Electron teams has to say.

**Comment by eddyedyy** [comment]
Interested to hear the solution as well.

**Comment by nornagon** [comment]
`Session` objects are never deleted due to complex internal requirements which we inherit from Chromium. I'd recommend against creating many `Session` objects in your app. Consider reusing them. You should be able to clear out a session and change its proxy settings as needed.

It's theoretically possible for these objects to be GCed, but there's a huge amount of highly complex code that needs to be written to support it, and the use case of creating many throwaway sessions is rare enough and work-around-able enough that it's not presently worth the time to do that refactor.

**Comment by mckravchyk** [comment]
@nornagon 

May I have a question about how Electron handles persistent sessions stored on disk? Does it load all persistent sessions to memory when the app starts or does it load them only on demand?

I expect a need to use many sessions to isolate cookie context. Over time, it may accumulate to even hundreds of sessions for some users. The thing is that it's hundreds of persistent sessions stored on disk, but only a dozen or 2 dozen would be used at the time (during app's runtime from window open to close). So would Electron preload them all or only those which are used by calling `session.fromPartition`?

If it's the former, I imagine I could create a session manager that would deal with storing cookies on disk without creating permanent sessions.

Thanks

**Comment by nornagon** [comment]
I'm pretty sure they are only loaded on demand, but you should be able to check that fairly easily!
