### ISSUE TITLE
Read at least the title of an issue before acting upon it

### ISSUE THREAD

**Issue by zakius** [electron/electron#28568]
@zakius You should be able to toggle 99% of flags using `app.commandLine.appendSwitch('enable-features', 'BaseFeatureNameHere')`.  As long as you do that early during your apps initialization (before app ready) then they should work fine and be respected

_Originally posted by @MarshallOfSound in https://github.com/electron/electron/issues/28537#issuecomment-815072372_

clearly shows this doesn't happen right now so you should fix that

**Comment by lee-dohm** [comment]
HI @zakius. I can understand your frustration with not having the Chromium flag you want supported directly by Electron. Before we continue, it is important to understand that this issue tracker and all other repos in electron are a workplace, and we expect workplace appropriate communication. You are welcome to this space, assuming you can abide by that.

I'm closing this as off topic.

Please wait 24 hours before re-engaging with any of the Electron properties. If, after that, you'd like to discuss this again, we'd be happy to discuss Chromium feature flags and how to best support them, in a friendlier tone.

**Comment by zakius** [comment]
I'm frustrated by that guy closing the issue without reading what it is about.

If you have no manpower to implement it or won't do it for any other reason it's your right but closing the issue with worthless comment like that is just low

**Comment by zakius** [comment]
and since there is no other way to report misbehaving organization member **to the organization** I had to use this form
