### ISSUE TITLE
[Bug]: Electron 11.4.1 crashes sporadically on Mac M1 hardware

### ISSUE THREAD

**Issue by Glebka** [electron/electron#28578]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.4.1

### What operating system are you using?

macOS

### Operating System Version

macOs Big Sur 11.2.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

N/A

### Expected Behavior

App is not crashing.

### Actual Behavior

App crashes sporadically.

### Testcase Gist URL

https://gist.github.com/Glebka/b4b50c4b4eeec40bcb32fac94d2d154c

I attached a crash report as gist.
Please have a look.

Our app is a corporate messenger with telephony and video meeting capabilities.
The version that is crashing was built for x64 arch and was running using Rosetta on Apple M1 hardware.

The crash I published were caught by Mac OS, despite we have a Sentry crash reporter configured.

Will appreciate any help on this. Thanks.

**Comment by nornagon** [comment]
Looks similar to https://github.com/electron/electron/issues/28577

**Comment by zcbenz** [comment]
Both crashes happen in ThreadPoolServiceThread so they are very likely the same crash, I'm merging this to https://github.com/electron/electron/issues/28577.
