### ISSUE TITLE
[Bug]: render process trigger a CHECK at message_pump_kqueue.cc(387) on M1 macos

### ISSUE THREAD

**Issue by yaohy0819** [electron/electron#28577]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.4.1

### What operating system are you using?

macOS

### Operating System Version

macOS 11.0 (20A2411)

### What arch are you using?

x64

### Expected Behavior

electron render may crash sometimes. I have found this issue was fixed by chromium, I hope electron could cherry pick this patch. 
Thanks.

https://bugs.chromium.org/p/chromium/issues/detail?id=1119292
https://bugs.chromium.org/p/chromium/issues/detail?id=1195337

### Actual Behavior

the crash looks like

```
Thread 1 Crashed:: ThreadPoolServiceThread
0   [Electron Framework]   logging::LogMessage::~LogMessage() (in Electron Framework) (logging.cc:878) [0x00000001094650e4] parsed
1   [Electron Framework]   logging::ErrnoLogMessage::~ErrnoLogMessage() (in Electron Framework) (logging.cc:1022) [0x000000010c89ebf0] parsed
2   [Electron Framework]   logging::ErrnoLogMessage::~ErrnoLogMessage() (in Electron Framework) (logging.cc:1016) [0x000000010c89ec2e] parsed
3   [Electron Framework]   base::MessagePumpKqueue::DoInternalWork(base::MessagePump::Delegate::NextWorkInfo*) (in Electron Framework) (message_pump_kqueue.cc:387) [0x00000001094e0819] parsed
4   [Electron Framework]   base::MessagePumpKqueue::Run(base::MessagePump::Delegate*) (in Electron Framework) (message_pump_kqueue.cc:170) [0x00000001094e0670] parsed
5   [Electron Framework]   base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) (in Electron Framework) (thread_controller_with_message_pump_impl.cc:454) [0x00000001094a0341] parsed
6   [Electron Framework]   base::RunLoop::Run() (in Electron Framework) (run_loop.cc:126) [0x000000010947ea79] parsed
7   [Electron Framework]   base::internal::ServiceThread::Run(base::RunLoop*) (in Electron Framework) (service_thread.cc:0) [0x00000001094a8e4d] parsed
8   [Electron Framework]   base::Thread::ThreadMain() (in Electron Framework) (thread.cc:385) [0x00000001094b82e9] parsed
9   [Electron Framework]   base::(anonymous namespace)::ThreadFunc(void*) (in Electron Framework) (platform_thread_posix.cc:89) [0x00000001094cd0e3] parsed
10  libsystem_pthread.dylib         0x00007fff20426950 _pthread_start + 224
11  libsystem_pthread.dylib         0x00007fff2042247b thread_start + 15
```

**Comment by zcbenz** [comment]
According to the Chromium issue backporting https://chromium.googlesource.com/chromium/src/+/162efe98330e8d243d472889db81dd78b691156f will fix this.

**Comment by Serena-zlh** [comment]
@zcbenz Will this fix cherry-pick into electron 11, I saw it merged into 12, but not  into 11

**Comment by nornagon** [comment]
Looks like this has been backported now.
