### ISSUE TITLE
[Bug]: The edges of the window turn black when using setResizable (false).

### ISSUE THREAD

**Issue by Sosupe** [electron/electron#28574]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

Windows

### Operating System Version

edition	Windows 10 Pro version	20H2 install day ‎2021/‎03/‎14 OS build	19042.867 expellience	Windows Feature Experience Pack 120.2212.551.0

### What arch are you using?

x64

### Expected Behavior

When the size of the window is fixed with "setResizable (false)", the edge becomes black when the window is moved.
Then minimize the window and restore it to eliminate the black edge.

### Actual Behavior

Normally, even if the size of the window is fixed, the edges of the window will not turn black.

Normal window

![image](https://user-images.githubusercontent.com/76240562/113978240-aebf3580-987e-11eb-956e-bf01393b9bcc.png)

Unhealthy window

![image](https://user-images.githubusercontent.com/76240562/113978317-cac2d700-987e-11eb-9be7-12a5bfbdd1e1.png)

**Comment by codebytere** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by Sosupe** [comment]
I tried to reproduce the bug, but for some reason I couldn't reproduce the bug.

However, as you can see in the picture, the edges of the entire software are black, so I thought that html was not the cause.

![image](https://user-images.githubusercontent.com/76240562/114646921-22e25900-9d17-11eb-9b45-49ea895fd389.png)
Here is the normal case.
![image](https://user-images.githubusercontent.com/76240562/114647062-63da6d80-9d17-11eb-8501-62b822fd0d1e.png)

Here is the source of the project with the bug.
https://github.com/Sosupe/Disapp
We apologize for not being able to reproduce the bug.

**Comment by nornagon** [comment]
I'm going to close this; as mentioned, we don't have the time to debug whole apps. If you're able to provide a standalone example which shows the issue, I'm happy to reopen.
