### ISSUE TITLE
BrowserWindow .setIcon is showing no effect on taskbar icon, if executed in built electron app

### ISSUE THREAD

**Issue by IITSTaron** [electron/electron#28581]
**Preflight Checklist**
I have read the Contributing Guidelines for this project.
I agree to follow the Code of Conduct that this project adheres to.
I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Electron Version**
electron 12.0.0
electron-builder 22.10.5

**What operating system are you using?**
Windows

**Operating System Version**
10.0.19041 Build 19041

**What arch are you using?**
x64

**Expected Behavior**
Taskbar-Icon is changed when setIcon is called 

**Actual Behavior**
Taskbar-Icon is not changed

**Description**
I am currently working on an electron app, whichs taskbar icon should be dynamically updated depending on the app state.
To achieve this I am using window.setIcon('path/to/icon.ico'), which is working fine if the app is runned locally on windows using "electron .".

Once the app is built using the electron-builder and executed via the installer, calling .setIcon has no effect on the appereance of the Taskbar Icon. Similar functions like .setOverlayIcon are working as expected.

However, when running the app using ./dist/win-unpacked/*.exe the issue is not occuring.

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by IITSTaron** [comment]
Hello @nornagon and thank you for your response!
I have created a reproduction of the bug. 
You can find it here: https://github.com/IITSTaron/electron_28581
Please see the readme.md for further information.

**Comment by nornagon** [comment]
It looks like the repro you've provided uses a lot of third-party dependencies such as Vue and Sass. Because of time constraints, triaging code with third-party dependencies is usually not feasible for a small team like Electron's.

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

**Comment by IITSTaron** [comment]
Hello @nornagon and thank you for your asstance!
I have updated the reproduction (https://github.com/IITSTaron/electron_28581) so be more simple and removed all dependencies, which are not necessary, to reproduce the issue.

The only remaining dependencies are now electron and electron-builder.

Please note, that the Electron Fiddle is unfortunately not applicable, as you explicitely have to trigger a build in order to reproduce the issue.

**Comment by asineth0** [comment]
Every Electron issue on this repo is literally just some devs asking for code to reproduce the issue, someone providing it, and then they entirely ghost the issue and close it later without actually fixing it. I guess it's no surprise that Electron is poorly maintained.
