### ISSUE TITLE
[BUG? FEATURE?] Webpack Overriding the BrowserWindow's title

### ISSUE THREAD

**Issue by angelhdz** [electron/electron#28584]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.0.0

### What operating system are you using?

Windows

### Operating System Version

10.0.19042 Build 19042

### What arch are you using?

x64

### Expected Behavior

Being able to try things as per the official documentation without it breaking because some injected or forced feature.
In this case, I expected to try Electron with Vue and TypeScript and being able to follow tutorials and getting the same results.

### Actual Behavior

I lost a lot of time trying to understand why the **window's title** won't change, either by calling setTitle() or setting the title parameter while building the **BrowserWindow**, and it turned out to be **Webpack** overriding the window's title reading it from the package.json. It's not practical because the name property in the package.json can't be Uppercase, and a page window's title requires it to be capitalized. 

### My Environment
I created a vue-cli app and then added electron to it.

### My Solution

I could solve this 4 ways:

1- Hardcoding the title in the index.html in the <title> tag.
2- Finding a Webpack configuration file (I didn't find any) and modifying how it injects the window's title.
3- Changing the window's title in the name property in the package.json, and ignoring the error that the name
is not following certain convention (it being capitalized and not **kebab-case**)
4- Removing the Webpack injectable template in the <title> tag of the index.html and being able to change the title as normally, in the BrowserWindow creation as a parameter inside the configuration object, or by calling setTitle in an instance of it.

I chose #4 because it felt the more organic, logical and obvious way.

But I still have a bitter feeling after this, because I hate when unknow plugins/dependencies are injecting things at runtime or at compiling time making the learning experience difficult. 
I'm yet to learn what this Webpack plugin is and how to work with it and how it benefits me.

### Last Words
I hope there's an explanation to this, and a better solution.

**Comment by erickzhao** [comment]
Does this not happen with your page title in the webapp running in a browser? Sounds like a vue-cli issue more than Electron to me.

**Comment by zcbenz** [comment]
You can use the 'page-title-updated' event to prevent web pages from updating title:
https://www.electronjs.org/docs/api/browser-window#event-page-title-updated

**Comment by angelhdz** [comment]
> You can use the 'page-title-updated' event to prevent web pages from updating title:
> https://www.electronjs.org/docs/api/browser-window#event-page-title-updated

Thank you so much for the solution. It's interesting, but I don't find it practical.

**Comment by angelhdz** [comment]
> Does this not happen with your page title in the webapp running in a browser? Sounds like a vue-cli issue more than Electron to me.

Thanks for the reply!

Your reply helped understand the issue better. I served a Vue CLI web application project, and the issue is also present there. 
So my understanding is, this is a Webpack issue. All the index.html files of all the projects I work with (Ionic + Vue, ReactNative, etc). have this template in the <title> tag: <title>**<%= htmlWebpackPlugin.options.title %>**</title>

So, it's just Webpack deciding how to set the web app's title (by picking it from the package.json).

So I will open an Issue in the Webpack repository because I think picking the title from the package.json name attribute is not practical, as it only allows for **kebab-case** and the title is supposed to be **Space Separated Pascal Case**.

Thank you everyone for your replies!
