### ISSUE TITLE
[Bug]: cannot reset camera and microphone access on windows

### ISSUE THREAD

**Issue by weiweian90** [electron/electron#28591]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.0.0

### What operating system are you using?

Windows

### Operating System Version

windows10

### What arch are you using?

x64

### Expected Behavior

can reset camera and microphone access and reapply

### Actual Behavior

when app apply camera access on windows, users not permissed, they cannot use camera any more

**Comment by nornagon** [comment]
I believe this is an OS limitation.
