### ISSUE TITLE
[Bug]: IsURLArg returns true for arguments that aren't URLs

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#28595]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.2.1 (also probably 12)

### What operating system are you using?

Windows

### Operating System Version

20H2, 1909

### What arch are you using?

x64

### Expected Behavior

I expect to be able to pass an argument with a colon that's not a URL (e.g. key=C:\\Path) as any argument to Electron.

It works if the argument starts with file path (e.g. an arg of `C:\\Path` will work), but not if there's some stuff before it.

This is because of this code:
https://github.com/electron/electron/blob/462de5f97a302987dc5fa5c222781ceed040f390/shell/app/command_line_args.cc#L9-L32

This issue was reported a while ago [here](https://github.com/electron/electron/issues/25270) and this is apparently done to mitigate against an old Windows security flaw.

However the function is called `IsURLArg`, and an arg like `key=C:\Path` is clearly not a URL. can this method be made more robust to accept non URL-like arguments?

### Actual Behavior

I can't pass an argument with a colon if it's not the last argument

**Comment by MarshallOfSound** [comment]
> I can't pass an argument with a colon if it's not the last argument

You can do this if you place a `--` argument before your path / url-like parameter.  As per #25270 this behavior is a security mitigation that we can't and won't be changing unfortunately.  It is very hard to determine what is potentially a URL scheme and the safest thing to do by far is to just identify `*:*`
