### ISSUE TITLE
How setAppDetails in macOS?

### ISSUE THREAD

**Issue by xiaohuoni** [electron/electron#28590]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

macOS

### Operating System Version

macOS Catalina 10.15.6

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

win.setAppDetails is work well
```
function createWindow() {
  const win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: join(__dirname, 'preload.js')
    }
  });

  // just support Windows
  if (process.platform === 'win32') {
    win.setAppDetails({
    appId: 'com.xxx.xxx',
    relaunchDisplayName: 'xxx',
    appIconPath: join(__dirname, 'logo.png')
  });
  }

  win.loadURL(getPath());
}
```

### Actual Behavior

(node:75095) UnhandledPromiseRejectionWarning: TypeError: electron.BrowserWindow.setAppDetails is not a function

### Testcase Gist URL

https://github.com/electron/electron-quick-start-typescript

**Comment by nornagon** [comment]
This method is only supported on Windows.
