### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by gametheworld** [electron/electron#28594]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

8.0.0

### What operating system are you using?

Windows

### Operating System Version

win7

### What arch are you using?

x64

### Last Known Working Electron version

8.0

### Expected Behavior

It works fine in the development environment, but when I run it after packaging it for release, it will report an error directly

![image](https://user-images.githubusercontent.com/6021628/114181063-9da42080-9973-11eb-9604-5c37962282e5.png)

### Actual Behavior

It works fine in the development environment, but when I run it after packaging it for release, it will report an error directly

**Comment by Prinzhorn** [comment]
Does this happen with a more recent version than 8.0.0?

**Comment by nornagon** [comment]
The version of Electron you're using is [no longer supported](https://www.electronjs.org/docs/tutorial/support#currently-supported-versions).
