### ISSUE TITLE
[Bug]: Invisible border (maybe resize frame) when you set fullscreen no-resize 

### ISSUE THREAD

**Issue by kartofelek007** [electron/electron#28596]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

none

### Expected Behavior

Cursor should work on entire screen

### Actual Behavior

This issue is relevant to https://github.com/electron/electron/issues/21929
and still exist in Electron 12.0.1 on Windows10

When I open my application on Chrome with fullscreen:
![chrome-fullscreen](https://user-images.githubusercontent.com/2007669/78909245-85a97080-7a83-11ea-9887-93e98c10f0aa.gif)

When I open the same aplication with Electron frameless fullscreen no-resize:
![electron-fullscreen](https://user-images.githubusercontent.com/2007669/78909275-8fcb6f00-7a83-11ea-8c98-bd439ac61f46.gif)

This is code for electron window:
```transparent: true,
frame: false,  
alwaysOnTop: true,  
fullscreen: true,  
resizable: false,
```

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by kartofelek007** [comment]
I create repo for this issue: 
https://github.com/kartofelek007/electron-issue-28596

In main.js I add lines (15-17) to change. 
Now I see that this issue is exist only if window is transparent: true

**Comment by exzolink** [comment]
Electron Nightly 14 still exists

only frame false

**Comment by nornagon** [comment]
Hm, I can't seem to reproduce this with that repo:

![Screen Recording 2021-07-13 at 9 26 58 AM](https://user-images.githubusercontent.com/172800/125490175-90bd6ebb-b9cd-44b4-b182-0adfb0b6bc80.gif)

(copied the example to a Fiddle for ease of use: https://gist.github.com/4f901c534006187394138056b58873f8)

**Comment by kartofelek007** [comment]
I download example repository. After update electron to **@13.2.3** (with _npx npm-check -y_) i don't see this issue any more.
