### ISSUE TITLE
[Feature Request]: MenuItem's icon placement options

### ISSUE THREAD

**Issue by Nokel81** [electron/electron#28599]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

If you specify an icon for a `MenuItem` it is prepended to the label. However this means that the start of text for items that have icons and those that don't are not vertically aligned.

However, if you specify that the `MenuItem` is `checked` then the check-mark is placed before the label such that both checked and non-checked labels are vertically aligned.

### Proposed Solution

And an option (that is mutually exclusive to `checked) for the placement of the icons to be placed before the label. Preferably in the "buffer" space to the left of the menu.

### Alternatives Considered

- Add a fake blank icon on those entries that don't have another one.

### Additional Information

I have tested this on macOS Catalina, but have seen this sort of behaviour on ubuntu 20.04 as well.

**Comment by zcbenz** [comment]
This is the default behavior of the operating system, to achieve the feature described, the only reliable way would be setting a blank icon, which is exactly the alternative you described.

So adding this new API would have little value, as it does not add something that can not be done with existing APIs, and I'm closing this as won't fix.
