### ISSUE TITLE
[MAS Rejection]: App rejected - Electron 12.0.1 

### ISSUE THREAD

**Issue by Foxhoundn** [electron/electron#28600]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.

### Electron Version

12.0.1

### Rejection Email

Your app uses or references the following non-public APIs:

• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/CAContext
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/NSAccessibilityRemoteUIElement
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/NSNextStepFrame
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/NSThemeFrame
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/CALayerHost
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__NSAppendToKillRing
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AudioDeviceDuck
• Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler/__kCFSystemVersionProductVersionExtraKey
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__kCFSystemVersionProductVersionExtraKey
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerGetBytePtr
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_CTFontDescriptorIsSystemUIFont
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__NSYankFromKillRing
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__NSInitializeKillRing
• Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler/__CFCopySystemVersionDictionary
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__CFCopySystemVersionDictionary
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerRangeCopyEndMarker
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_CGFontRenderingGetFontSmoothingDisabled
• Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler/__kCFSystemVersionProductNameKey
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__kCFSystemVersionProductNameKey
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerRangeCopyStartMarker
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__NSNewKillRingSequence
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_IOBluetoothPreferenceSetControllerPowerState
• Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler/__CFCopyServerVersionDictionary
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__CFCopyServerVersionDictionary
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__LSSetApplicationLaunchServicesServerConnectionStatus
• Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler/__kCFSystemVersionProductVersionKey
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__kCFSystemVersionProductVersionKey
• Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler/__kCFSystemVersionBuildVersionKey
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__kCFSystemVersionBuildVersionKey
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerCreate
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_NSTextInputReplacementRangeAttributeName
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerRangeGetTypeID
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerGetLength
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerRangeCreate
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_SetApplicationIsDaemon
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/__NSSetKillRingToYankedState
• Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework/_AXTextMarkerGetTypeID

The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change. 

### Additional Information

Using electron forge to build on the MAS platform with `pkg` maker. 

Simple app, does not use any special permissions and is 100% offline (not a single http call, no sensors used, no collection of data etc).

Any help / pointers very very much appreciated.

Thank you!

**Comment by MarshallOfSound** [comment]
These were all fixed a long time ago, I suspect you are building for the `darwin` platform and not for the `mas` platform.  I just double checked the MAS build and none of these symbols are present.

Old ref: https://github.com/electron/electron/issues/20027

Double check your packaging / build logic and you can use `otool` to verify if the symbols are there or not.

**Comment by Foxhoundn** [comment]
Hi, thank you! Could you give me an example how to check the private API with otool?

**Comment by Foxhoundn** [comment]
Fixed by properly targeting Electron Forge to `mas`
