### ISSUE TITLE
[Bug]: When using loadURL, the URL dependent JS file fails to load

### ISSUE THREAD

**Issue by bei-yang** [electron/electron#28606]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

8.5.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10.0

### What arch are you using?

x64

### Last Known Working Electron version

8.5.2

### Expected Behavior

JS files can be loaded normally without emptying the folder.

### Actual Behavior

When LoadURL is used to load the remote URL, and republishing a new JS using Webpack Hash, the URL dependent JS file will sometimes fail to load.Nor can reinstalling software. 
When the Electron cache folder is deleted and the software is reopened, the JS file will load successfully.

Delete the directory:
C:\Users\${userName}\AppData\Roaming\${appName}

This is an occasional occurrence that I cannot simulate.

**Comment by MarshallOfSound** [comment]
> This is an occasional occurrence that I cannot simulate.

Without a repro test case there is no chance of us being able to investigate or fix this

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
