### ISSUE TITLE
[Question] What library does Electron use for menus on Windows?

### ISSUE THREAD

**Issue by patr0nus** [electron/electron#28608]
On Windows Electron has a nice material-like menu style, which I would like to use in native applications. Is it implemented inside Electron or maybe from chromium? 

![electron_menu](https://user-images.githubusercontent.com/3612422/114311162-38d9f900-9b20-11eb-9f87-27b8dd8205ea.gif)

I tried to dig into the code to find out but it's too overwhelming for me. I'd appreciate it if someone could point it out. Thanks!

**Comment by MarshallOfSound** [comment]
Electron uses Chromiums Menu implementation on Windows and Linux

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
