### ISSUE TITLE
[Bug]: SSH Session Copy/Paste not working in BrowserWindow

### ISSUE THREAD

**Issue by bcburak** [electron/electron#28617]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

3.1.13

### What operating system are you using?

Windows

### Operating System Version

Wimdows 10

### What arch are you using?

x64

### Expected Behavior

I used "BrowserWindow" to display specific URL in electron project. When I copied some string from local computer and want to paste it to BrowserWindows, it happens nothing. Also I can not see right click menu on BrowserWindow.
But If I pass my specific URL in Chrome app, I can do copy/paste operations. I used this operation using by Java in Web Applications.
You can see screenshots.

In Java/Web
![image](https://user-images.githubusercontent.com/6598220/114390088-79785780-9b9e-11eb-9c54-c650b1fbda8b.png)

In Electron BrowserWindow ; I can not righ clicked and copy/paste operations

### Actual Behavior

Not copying text
Not display right click menu

**Comment by Prinzhorn** [comment]
If you want a context menu in your Electron app you need to do that yourself (https://www.electronjs.org/docs/api/menu#menupopupoptions) or use a project such as https://github.com/sindresorhus/electron-context-menu

If you think there is a bug in Electron regarding copy & paste then please provide steps to reproduce the problem. A screenshot doesn't help very much.

**Comment by bcburak** [comment]
Context menu is not priority for this issue. However I can use context menu if it would have capability of copy & paste actions.
My main purpose is paste ssh screen in electron that I copied from my local computer. I can use CTRL+C and CTRL+P, if it is possible
I'm using Electron-React Boilerplate. I'm sharing code that I call BrowserWindow and pass url.

main.dev.js (Creating BrowserWindow and  call tabModal.html)

`      tabsWindow = new BrowserWindow({
        autoHideMenuBar: true,        
        webPreferences: {
          webSecurity: false
        }
      });
      tabsWindow.loadURL(`file://${__dirname}/tabModal.html`);
 tabsWindow.webContents.send("open-tab", params);  **// params : include a local url to display webcontent inside BrowserWindow**
`
remoteHelper.js creates an url according to same conditions.Basically doing something like that.

` let url = `${scClient.server}/portal-ui/x/tool/saswre.cli/terminal.jsp?shell=relay&deviceId=${device.id}&`;
 const params = {
      title: device.name,
      src: url
    };
 ipcRenderer.send("open-tabs-window", params,screenSize);
`

**Comment by Prinzhorn** [comment]
Would it be possible to create a demo using Electron Fiddle? https://github.com/electron/fiddle

**Comment by bcburak** [comment]
Here it is : https://gist.github.com/c63bf97741853b2e52fefe5c9fd00983
I should say that; I reproduce it by using my internal url. It is using for create SSK device connection. So you probably can not reach that device. You should reproduce that issue with create new Linux device and SSH connection url
Thanks

**Comment by zcbenz** [comment]
The context menu has to be implemented by the user, so it is not a bug.

As for copy/paste with keyboard, since copy/paste already works for normal web pages (which you can verify simply by running something like `electron https://google.com`), the reason why copy/paste does not work in your web app, must be a compatibility issue between your web app and Electron.

Since your web app is available to us, and even if it does we could not possibly debug it for you, I'm afraid we can not help on with issue. You have to find out the root issue yourself, and if you verify it is a bug of Electron we would be happy to fix it.
