### ISSUE TITLE
[Bug]: window.open() -> overrideBrowserWindowOptions: {parent: null} still gets closed if "parent" is closed

### ISSUE THREAD

**Issue by hugoj-goncalves** [electron/electron#28629]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro Version 20H2

### What arch are you using?

x64

### Expected Behavior

As the window has no parent (null), it should remain open

### Actual Behavior

The child window gets closed with the parent window
Parent window calls close -> closed events
Child windows calls closed event only (skipping the close event)

**Comment by sofianguy** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone test case with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.

**Comment by nornagon** [comment]
Related to #11128 perhaps? cc @zcbenz

**Comment by hugoj-goncalves** [comment]
yeh, that's exactly it. 
gonna close it in favor of the existing one.
