### ISSUE TITLE
[Bug]:Electron net request proxy swap not working

### ISSUE THREAD

**Issue by tstifxoxo** [electron/electron#28631]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.3

### What operating system are you using?

Windows

### Operating System Version

10

### What arch are you using?

x64

### Expected Behavior

I expect that when i add new proxy to already existing partition from session object that it will really swap to that proxy and not use old one that i used till moment of swapping.

### Actual Behavior

When i do request towards to a site that can retrieve what my current IP is, the site shows im using same proxy all the time, even when i change it using 

```
await ses.setProxy({
        proxyRules: proxyparse,
        proxyBypassRules: "",
    });
```

This is my entire code of doing HTTPs request and changing proxies using parition1 as arguments.

```
const { session } = require('electron')
async function getIP(proxy, partitionName) {  


    var nextProxy = proxy;
    var proxyparse;

    proxyparse = nextProxy.split(':')[0] + ':' + nextProxy.split(':')[1];

    var name = 'persist:' + partitionName
    const ses = session.fromPartition(name)

    await ses.setProxy({
        proxyRules: proxyparse,
        proxyBypassRules: "",
    });

    const request1 = net.request(
        {
            method: "GET",
            session: ses,
            url: 'http://checkip.amazonaws.com/',
            headers: {
                "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36'
            }
        });
    request1.on('login', (authInfo, callback) => {
        callback(nextProxy.split(':')[2], nextProxy.split(':')[3]);
    });
    var body = '';
    request1.on('response', (response) => {

        response.on('data', (chunk) => {
            body += chunk.toString();
        })
        response.on('end', () => {
            console.log("ip: " + proxy + " ---> " + body)
        })
    });

    request1.end();
};
```

I call this function like this

```
getIP(data1[0], "part1")    // 144.168.191.25:8800:username:pw, "part1"
getIP(data1[1], "part1")    // 144.138.191.25:8800:username:pw, "part1"
```
and it outputs this

```
ip: 144.168.191.25:8800 ---> 144.168.191.25
ip: 144.138.191.25:8800 ---> 144.168.191.25
```
Notice that even tho i add new proxy to the function, it still returns the old proxy from IP checking site.

When i change to different partition, it works like charm, but because of previous bug post i posted related to garbage collector not existing for partitions, i now need to reuse 1 partition and rotate proxies under it. Unfortunately, it doesn't work.

**Comment by jakobjj0** [comment]
I was facing the same issue but solved it by clearing the sessions cache and reloading the proxy config


```
await ses.closeAllConnections()
await ses.clearAuthCache()
await ses.clearHostResolverCache()

await ses.setProxy({
    proxyRules: proxyparse,
    proxyBypassRules: "",
});
await ses.forceReloadProxyConfig()

```
