### ISSUE TITLE
[Feature Request]: Support deskbands on Windows

### ISSUE THREAD

**Issue by apuchitnis** [electron/electron#28630]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Windows supports deskbands, which are small windows that run in your task bar:

![image](https://user-images.githubusercontent.com/10189197/114526933-56ea4b00-9c3f-11eb-97a5-46a8e0b7387f.png)

These windows are interactive and can perform some pretty useful functionality. In this example it is control music, but they can also be used to display any information the user might want to see at a glance or offer quick access to some functionality.

The [win32 shell docs](https://docs.microsoft.com/en-us/windows/win32/shell/taskbar-extensions#deskbands) states that deskbands can still be implemented and are intended to complement thumbnail toolbars (which electron already supports).

My suggestion is for electron to support deskbands, which it does not do currently.

### Proposed Solution

Support desk bands.

I don't know what work would be required to do this. I'm new to electron development, but if someone is willing to direct me, I'd be happy to try adding them.

### Alternatives Considered

Not support desk bands.

### Additional Information

I couldn't find any examples of someone implementing a DeskBand in electron online.

**Comment by nornagon** [comment]
Hm, it looks like DeskBands are deprecated and should be replaced by thumbnail toolbars: https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src/shell/deprecated-api.md

This is also noted in the deskband docs: https://docs.microsoft.com/en-us/windows/win32/api/shobjidl/nn-shobjidl-ideskband2

I'm going to close this as there's not a lot of demand for this, and the feature is deprecated in the OS, so I don't think it's likely we'll implement them.

**Comment by apuchitnis** [comment]
That's fair enough - thanks for considering 👍
