### ISSUE TITLE
[Feature Request]: Dynamically switch out preload scripts, or communicate to them from the main process

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#28651]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

This might be impossible from an architectural standpoint, but I figured I'd ask.

I currently have a `BrowserWindow` that loads a local html page in a non-sandboxed context. That local page can be navigated to an external page, and when it is, since I want the external page to be secure and whatnot and I can't toggle `nodeIntegration`/`sandbox`/`contextIsolation`, I have to create a `BrowserView` with the more secure configurations and have it fill the entire window.

I was thinking recently if I could remove the `BrowserView` (one less process, and could delete some workarounds I have for `BrowserView` bugs) and just sandbox the local page instead.

The issue is that I can't dynamically switch out preload scripts, so the preload script that I'd load initially into the `BrowserWindow` for the local page, is the one that will be set for the external page.

So my first question is if it's even possible to support switching out the preload script. If not, read on.

Otherwise, I need to make my single preload script work for both the local and external page. There are however some things that I expose in the preload script for the external page currently that I don't want to expose to the local page and vice versa. This motivates coming up with some way to dynamically decide what the preload script exposes.

An idea I had was to listen for navigations and when I navigate to the external page, unexpose certain functions on the `global` object and expose others. However, I don't know of a way to listen for navigations in the preload script.

Normally, I'd do `webContents.on("did-navigate", (e, url) => ...)`, but I can't use `WebContents` in a Renderer. Thus, I can only listen for navigations in the main process, but then the question becomes, how can I notify the Renderer (re: the preload script) of this change and respond to it.

Is there something that can be added to Electron to allow this type of workflow?

### Proposed Solution

If toggling preload scripts is possible on navigation, that would be the best solution.

If not, some way of communicating to the preload script would be great. I'm not sure if `executeJavaScript` is what I want here, or if that will even work. I don't want to execute a function in the webpage, but one that's just in the preload script.

### Alternatives Considered

mentioned what I tried above. Not sure what else I can do

Well... I guess in my particular case, I could expose the functions I need for my local page in the preload script, and if the external page calls them, I can detect that in the main process and just ignore the message.

### Additional Information

n/a

**Comment by MarshallOfSound** [comment]
@pushkin- Preload scripts are run every single time the page loads / navigates.  You can just check `window.location` to determine what you should / shouldn't expose to a given URL.

That said, you really should do those kinds of security checks in the main process.  i.e. validate `event.sender.getURL()` when receiving IPC messages.

if you truly want to be able to swap preload scripts (I don't think you actually do) you can look at using `session.setPreloads` which sets session-wide preload scripts.

**Comment by MarshallOfSound** [comment]
As it stands I don't think this is a feature request rather a question on how to do something architecturally, closing this out as an answered question.
