### ISSUE TITLE
[Bug]: fail to debug in vscode in macOS

### ISSUE THREAD

**Issue by luhc228** [electron/electron#28653]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

macOS

### Operating System Version

macos 10.15.6

### What arch are you using?

x64

### Last Known Working Electron version

12.0.2

### Expected Behavior

Debug the electron in VS Code, the window can be appeared.

### Actual Behavior

I debug this example https://github.com/octref/vscode-electron-debug/tree/master/electron-quick-start in VSCode successfully. But after I change the electron version to 12.0.2 and reinstall the dependencies, the electron can't be debugged in vscode. The window doesn't appear.

**Comment by codebytere** [comment]
@luhc228 you should first open this on VSCode and see what they say - this is likely not a problem with Electron itself.
