### ISSUE TITLE
[Bug]: Can not print grayscale on Windows

### ISSUE THREAD

**Issue by NemoAlex** [electron/electron#28657]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

Using `color: false` in `contents.print`, the document printed in grayscale.

### Actual Behavior

The document still printed in color. Same printer and same source code works fine on MacOS. But on Windows it doesn't work.

**Comment by VerteDinde** [comment]
Hey @NemoAlex, thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, Electron Fiddle is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.

Thanks so much!

**Comment by NemoAlex** [comment]
> Hey @NemoAlex, thanks for reporting this and helping to make Electron better!
> 
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, Electron Fiddle is a great tool for making small test cases and makes it easy to publish your test case to a gist that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> I'm adding the blocked/need-repro label for this reason. After you make a test case, please link to it in a followup comment.
> 
> Thanks so much!

Sure.

```
const { app, BrowserWindow } = require('electron')

app.on('ready', () => {
  const window = new BrowserWindow({
    width: 800, 
    height: 600
  })
  window.loadURL('https://curl.se/docs/tooldocs.html')

  const contents = window.webContents
  contents.once('dom-ready', function () {  
    contents.print({
      margins: {
        marginType: 'custom',
        top: 0,
        left: 0,
        bottom: 0,
        right: 0
      },
      color: false
    }, (success, errorType) => {
      console.log(success, errorType)
    })
  })
})
```

**Comment by NemoAlex** [comment]
Any progress?
