### ISSUE TITLE
[Bug]: Debugger command Runtime.setCustomObjectFormatterEnabled doesn't work

### ISSUE THREAD

**Issue by jtbandes** [electron/electron#28668]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13 beta 13

### What operating system are you using?

macOS

### Operating System Version

11.2.3

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

I'd like to automatically enable custom devtools formatters in my app's dev tools window.

There's a DevTools Protocol command for this: [`Runtime.setCustomObjectFormatterEnabled`](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-setCustomObjectFormatterEnabled). But the command doesn't seem to do anything.

### Actual Behavior

The debugger command is accepted and doesn't throw an error, but it also doesn't enable custom formatters. The formatters are not enabled until I explicitly press F1 to open settings, and check the checkbox for custom formatters.

### Testcase Gist URL

https://gist.github.com/jtbandes/380db462f5f2807ba572e1908e3f0b6a

**Comment by deepak1556** [comment]
Thanks for the test case, this is actually expected behavior. Devtools and `webContents.debugger` are two different debugging sessions, modifying the setting in one does not affect the other. In your example, you can see the formatted result with the below event https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#event-consoleAPICalled

```
debug.on('message', (event, method, params) => {
  if (method === 'Runtime.consoleAPICalled') {
    if (params.args[1])
      console.log(params.args[1].customPreview)
  }
})
```

**Comment by jtbandes** [comment]
Thanks for the response. That explanation makes sense, but it doesn't really address my goal — how can I automatically enable custom formatters in dev tools?
