### ISSUE TITLE
Question: A problem with using the `electron` package

### ISSUE THREAD

**Issue by djalbat** [electron/electron#28663]
Hello!

I am not even sure how to couch this problem but let me try my best.

I have my bundled `client.js` file which is designed to work both in Chrome standalone and within electron. In order to do this, it relies on `shim.js` which differs for each of this platforms. Communication is via the global `window` object as the two are included by way of `script` elements:

```
    <script src="lib/shim.js"> </script>

    <script src="lib/client.js"> </script>
```

Now here is the shim for the browser...

```
'use strict';

function openExternal(url) {
	window.open(url);
}

window.__shim__ = {  ///
	openExternal
};
```

...and here is the shim for Electron:

```
"use strict";

const { shell } = window.require("electron");

const { openExternal } = shell;

window.__shim__ = {  ///
	openExternal
};
```
In previous versions of Electron I used to be able to get away with including the shims without bundling but now I am bundling the shim files.

Note the `window.require()` function. This is where the problem lies. With this in place, the bundled file is simply this:

```
// tmp/main.js
"use strict";
var ref = window.require("electron");
var shell = ref.shell;
var openExternal = shell.openExternal;
window.__shim__ = {
  openExternal
};
```

And everything works!

If I replace the `window.require()` call with the more normal `require()` call, the bundled file looks like this:

```
var __commonJS = (cb, mod) => () => (mod || cb((mod = {exports: {}}).exports, mod), mod.exports);

// node_modules/electron/index.js
var require_electron = __commonJS((exports2, module2) => {
  var fs = require("fs");
  var path = require("path");
  var pathFile = path.join(__dirname, "path.txt");
  function getElectronPath() {
    if (fs.existsSync(pathFile)) {
      const executablePath = fs.readFileSync(pathFile, "utf-8");
      if (process.env.ELECTRON_OVERRIDE_DIST_PATH) {
        return path.join(process.env.ELECTRON_OVERRIDE_DIST_PATH, executablePath);
      }
      return path.join(__dirname, "dist", executablePath);
    } else {
      throw new Error("Electron failed to install correctly, please delete node_modules/electron and try installing again");
    }
  }
  module2.exports = getElectronPath();
});

// tmp/main.js
"use strict";
var ref = require_electron();
var shell = ref.shell;
var openExternal = shell.openExternal;
window.__shim__ = {
  openExternal
};
```

This is more what I expect, but this fails when I run Electron. I get the error above in the console.

I can give you details of the bundler and transpiler settings if you want, but for the time being should probably just report that the module type is `commonjs` and the target platform is `node`.

So it seems that this `path.txt` file is missing, but I have no idea why.

Can you please advise?

Many thanks and kind regards,
James

**Comment by VerteDinde** [comment]
Hey James, thanks for reaching out! This looks like it may be a setup issue with your app, rather than an issue with Electron itself.

Because our team uses this issue tracker as a project board and backlog, I'm going to close this issue - but could you try posting your question/problem in our Electron Discord?: https://discord.gg/electron We have several help channels there, and you'll likely get a faster and more in-depth response to help with your issue. If you have any trouble joining, feel free to ping me in this issue.

Thanks, and best of luck on your project!
