### ISSUE TITLE
[Feature Request]: Native Call Notifications

### ISSUE THREAD

**Issue by BusinessDuck** [electron/electron#28669]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

At last year, a lot of applications based on Electron started using calls inside. I think we need native incoming call interface for all of it.

### Proposed Solution

 Electron must provide *Native* calls notifications.
![image](https://user-images.githubusercontent.com/10143411/114830544-fab92f80-9dd4-11eb-9133-0ebb7f286a85.png)

### Additional Information

Its may be depends on Chromium Notifications API, they are still not supported that as well

**Comment by miniak** [comment]
https://github.com/electron/electron/blob/main/docs/tutorial/notifications.md#advanced-notifications
