### ISSUE TITLE
[Feature Request]: Consider switching backgroundThrottling default to not throttle

### ISSUE THREAD

**Issue by ericandrewlewis** [electron/electron#28672]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I built a timer app for cooking with Electron. I had a bug in it that the timer would slow down when the app was backgrounded, which I didn't recognize as a bug for a while. 

Finally, I googled the right terms and found that I should set `backgroundThrottling` to `false` to avoid the JS engine slowing down my `setInterval()` calls.

### Proposed Solution

We could consider swapping the default of `backgroundThrottling` to `false`. In cases where developers want the performance boost, they can set it to true to avoid folks unknowingly getting this behavior.

### Alternatives Considered

This API option is a bit buried. We could add a warning about it to the [Quick Start doc](https://www.electronjs.org/docs/tutorial/quick-start).

### Additional Information

Thank you for all your work on Electron.

**Comment by samuelmaddock** [comment]
I believe this would increase resource consumption across all Electron apps if it were disabled by default. Considering the framework's current reputation online, I don't think this would do us any favors. 😅

In most cases, my understanding is that the Electron team tries to align with Chrome's defaults to avoid any unusual behavior only found in Electron. Considering this is the default behavior of web apps in Chromium browsers, I think it should remain enabled by default.

Perhaps folks more commonly contributing to the docs would have ideas on a place where this info could be presented with greater visibility?

**Comment by nornagon** [comment]
I concur with @samuelmaddock, I don't think enabling this by default is a good idea.
