### ISSUE TITLE
[Bug]: ipcRenderer connection to webview drops when viewing source

### ISSUE THREAD

**Issue by Jelmerro** [electron/electron#28673]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.4 and 13.0.0-beta.8

### What operating system are you using?

Other Linux

### Operating System Version

All

### What arch are you using?

x64

### Last Known Working Electron version

none

### Expected Behavior

When navigating a webview to the source of a page using `view-source:foo`, the ipcRenderer should keep receiving messages from the renderer.

### Actual Behavior

Once a webview navigates to `view-source:`, you can longer send of receive messages between the renderer and the webview. I ran into this when working on making a [source viewer for one of my projects](https://github.com/Jelmerro/Vieb/issues/151). I wanted to use `view-source:` for that, as I thought it might work for this, but because no messages can be send after doing this it's not an option right now, hence this bug report.

### Testcase Gist URL

https://gist.github.com/Jelmerro/58c79993841cbf749089da173ebfe78e

**Comment by nornagon** [comment]
`view-source` pages don't run preloads, unfortunately, which is the problem you're running into here. The navigation and initial load of `index.html` aren't required to exhibit this issue.

I'm going to close this as status/wontfix, because I don't have any plans to pursue changing this behavior myself. However, I'd happily review a PR.

**Comment by Jelmerro** [comment]
@nornagon That's too bad, but understandable. Is there any technical reason why this was disabled or is this part of how preloads are implemented in Electron?

**Comment by nornagon** [comment]
It's more that it wasn't considered than that there was an active decision made against it.

**Comment by Jelmerro** [comment]
Okay, in that case I'll have to build my own source viewer, because webviews without preloads are useless for my project.
