### ISSUE TITLE
[Bug]: Hidden windows don't seem to redirect (not fully featured?)

### ISSUE THREAD

**Issue by WasabiThumb** [electron/electron#28675]
### Preflight Checklist

I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.4

### What operating system are you using?

Windows

### Operating System Version

Windows 10 v1092 Build 19042 with WSL2

### What arch are you using?

x64

### Expected Behavior

Hidden windows should in theory act the same as an unhidden window, but not be rendered on the desktop. The functionality of electron code should not be connected to the "show" attribute in any way if I am not mistaken, otherwise no indication was given of the inverse. Redirects, or at least the will-navigate event, seem only to fire if the window is shown. This may be due to some underlying optimizations in chromium or electron. I have heard that **BrowserWindow#_setMinimizable(false)_** can fix this, but it has proven unsuccessful in my case.

### Actual Behavior

**In my development environment, the following script should reproduce the mentioned results**
```
const { BrowserWindow, app } = require("electron");

const main = (async (show) => {
	const win = new BrowserWindow({
		width: 640, height: 480, show,
		webPreferences: {
			nodeIntegration: false,
			contextIsolation: true
		}
	});
	// Create a promise that resolves when any navigation event fires
	let redirected = false;
	let hasRedirected = new Promise(async (res) => {
		while (!redirected) {
			await new Promise((r) => setTimeout(r, 1));
		}
	});
	win.webContents.on('will-navigate', (_,url) => {
		console.log("redirected to " + url);
		redirected = true;
	});

	console.log("loading");
	// Page source: <script>setTimeout(() => window.location.href = 'https://google.com/', 200)</script>
	win.loadURL('data:text/html;base64,PHNjcmlwdD5zZXRUaW1lb3V0KCgpID0+IHsgd2luZG93LmxvY2F0aW9uLmhyZWYgPSAnaHR0cHM6Ly9nb29nbGUuY29tJzsgfSwgMjAwKTwvc2NyaXB0Pg==');

	await new Promise((res) => {
		win.webContents.on('did-finish-load', res);
	})

	// Stop after 3 seconds or until a redirect happens
	await Promise.race([
		hasRedirected,
		new Promise((res) => setTimeout(res, 3000))
	]);

	win.destroy();
});

app.on('window-all-closed', e => e.preventDefault() );

app.on('ready', () => {
	console.log("running visibly");
	main(true).then(() => {
		console.log("done");
		setTimeout(() => {
			console.log("running hidden");
			main(false).then(() => {
				console.log("done");
				app.quit();
			});
		}, 3000);
	});
});
```

**Output**
```
running visibly
loading
redirected to https://google.com/
done
running hidden
loading
done
```

**EDIT:**
Using this instead of the will-navigate event works fine as a workaround
```
win.webContents.session.webRequest.onBeforeRequest({'urls': ['https://google.com/']}, function(details, callback) {
	console.log("request made to " + details.url);
	callback({ cancel: false });
});
```

### Testcase Gist URL

https://gist.github.com/WasabiThumb/80bcef287431200781844be8a5013721

**Comment by Prinzhorn** [comment]
With your edit the title is also not correct anymore, right? If I understand you correctly the redirect happens but you don't get a `will-navigate` event? This would have security implications. My first gut feeling was that `backgroundThrottling` is simply preventing your `setTimeout` setup from working as you expect. But you're saying `onBeforeRequest` does indeed catch the redirect? FWIW I cannot reproduce this on Ubuntu, I get the same output for the hidden window as well.
