### ISSUE TITLE
The discord site SSL certificate appears to be invalid

### ISSUE THREAD

**Issue by djalbat** [electron/electron#28670]
Hello!

I have been instructed to ask a question in an issue I raised on Discord. I am happy to do this, but there appears to be a problem with its SSL certificate. Is this a known issue?

Regards,
James
<img width="791" alt="Screenshot 2021-04-15 at 11 04 47" src="https://user-images.githubusercontent.com/17334729/114852682-e5470400-9dda-11eb-8b2e-5ac2e4fa5405.png">

**Comment by djalbat** [comment]
This is the issue:

https://github.com/electron/electron/issues/28663#issuecomment-819820141

**Comment by Prinzhorn** [comment]
The Electron team is not running Discord. Discord is run by Discord Inc.. The Electron team is _using_ Discord, because everyone can use Discord. The Discord desktop client is _coincidentally_ also based on Electron.

https://support.discord.com/hc/en-us

**Comment by djalbat** [comment]
I know Discord is not run by the Electron team. I was asking whether anyone else was having the same problem as me with the SSL certificate. Thanks for the clarification anyway.

**Comment by Prinzhorn** [comment]
My bad, sorry for making assumptions :heart:

**Comment by djalbat** [comment]
No worries. I think you are right about the rest of it, however. There is clearly something fishy going on with the `discord.gg` domain and my work flaptop. Strange that it doesn't affect any other websites but it's neither your problem nor Discord's.
