### ISSUE TITLE
[Bug]: Electron v12 has up to ~50x slower `child_process.{exec, execFile, spawn}` compared to Electron v11

### ISSUE THREAD

**Issue by KishanBagaria** [electron/electron#28683]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.4

### What operating system are you using?

macOS

### Operating System Version

macOS 11.2.3

### What arch are you using?

x64

### Last Known Working Electron version

11.4.3

### Expected Behavior

`execSync` should take ~10ms

### Actual Behavior

`execSync` takes around ~400ms

Repro: make a Fiddle with the following contents in `main.js`:
```js
console.time('exec')
require('child_process').execSync('ls')
// electron 11.4.3: 11.764ms
// electron 12.0.4: 400.92ms
console.timeEnd('exec')
```

```
Electron v11.4.3 execFile: 78.952ms
Electron v12.0.4 execFile: 432.513ms

Electron v11.4.3 spawnSync: 7.173ms
Electron v12.0.4 spawnSync: 378.55ms
```

This could be a Node.js issue.

**Comment by Prinzhorn** [comment]
Is this #28269 ?

**Comment by MarshallOfSound** [comment]
Duplicate #26143
