### ISSUE TITLE
[Bug]: roundedCorners: false and frame: false make Electron unable to quit

### ISSUE THREAD

**Issue by ghivert** [electron/electron#28686]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.0.0-beta14

### What operating system are you using?

macOS

### Operating System Version

macOS 11.2.3

### What arch are you using?

x64

### Expected Behavior

Start Electron with a `BrowserWindow` in frameless mode (`frame: false`), with `roundedCorners` to `false` and quit the program correctly with `Cmd + Q` or Menu > Electron > Quit.

### Actual Behavior

Start Electron with a `BrowserWindow` in frameless mode (`frame: false`), with `roundedCorners` to `false`. Quitting with `Cmd + Q` or Menu > Electron > Quit just make the app bug with bug sound, and make unable to quit Electron. We're force to kill it with force quit or `kill pid` or `ctrl-c` in CLI.

### Testcase Gist URL

https://gist.github.com/ghivert/5dea26ec97a73fcda55ddb069fccb459

**Comment by nornagon** [comment]
I'm able to reproduce this. cc @zcbenz who introduced the feature.

**Comment by timothylui** [comment]
I have this issue too

**Comment by BitesPotatoBacks** [comment]
I have actually seen this since ~13.0.2

**Comment by Maqsim** [comment]
I have the same issue with v15.2.0
