### ISSUE TITLE
[Bug]: Electron cannot start the GPU process

### ISSUE THREAD

**Issue by VisualSJ** [electron/electron#28693]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

All

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

11.2.0

### Expected Behavior

Start a WebGL program using Electron.

### Actual Behavior

Several of our computers were unable to load WebGL pages using Electron.
In addition we have a computer, open the ordinary page display white screen.

We use ProcessMonitor to capture the running of the electron.
The program loads D3D, but not libGLESv2.
But from the startup code, it looks like they're loaded together.

Is there any reason why libGLESv2 will not be loaded?

GPU information shows that WebGL is disabled.
Chrome works just fine on the same computer.

Once we try to query the GPU information(app.getGPUInfo()), we will receive an error message:
GPU access not allowed. Reason: GPU process crashed too many times with SwiftShader.

**Comment by VisualSJ** [comment]
We found that adding a -- no-sandbox enabled us to launch the WebGL environment

**Comment by nornagon** [comment]
Please attach a crash dump. You can collect them by adding the following snippet to your main process code, before app.whenReady:

```js
const { app, crashReporter } = require('electron')

console.log(app.getPath('crashDumps'))
crashReporter.start({ submitURL: '', uploadToServer: false })
```

Then reproduce the crash, zip up the crash dumps directory and attach it here.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
