### ISSUE TITLE
[Bug]: maximize and unmaximize events don't fire for browserwindow

### ISSUE THREAD

**Issue by Jelmerro** [electron/electron#28699]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.4

### What operating system are you using?

Other Linux

### Operating System Version

Fedora

### What arch are you using?

x64

### Last Known Working Electron version

11.4.3

### Expected Behavior

Events should fire for maximizing or unmaximizing a browserwindow.

### Actual Behavior

They don't, since the V12 release. It works fine in Electron 11 and below. See the fiddle console, it should log `max` and `unmax` when you toggle the maximization state, but it doesn't in Electron 12. One weird thing is, that when you maximize the window, and then go to fullscreen, it will emit `max`, but even when leaving fullscreen or unmaximizing the window, you will never see `unmax`. Not that fullscreen should have anything to do with the maximize event, but I noticed it does, so I thought I would mention that. You can see in the screenshot below that it only logs `max` (after going fullscreen), which shouldn't be possible if the events would fire correctly, as it should alternate `max`, `unmax`, `max` etc.
![image](https://user-images.githubusercontent.com/1696674/115083591-e75ab100-9f07-11eb-9334-5b65f80a0567.png)
And this is what happens in Electron 11.4.3:
![image](https://user-images.githubusercontent.com/1696674/115083718-1d983080-9f08-11eb-92af-ce8e6742b769.png)
When not entering fullscreen in V12, the logs remains empty, the ONLY way to make it trigger the `max` event is by maximizing and then going fullscreen, but it never triggers `unmax`.

### Testcase Gist URL

https://gist.github.com/Jelmerro/5a5a8b0cfcf69a24993b47bd7526d242

**Comment by ckerr** [comment]
Confirmed testing with 11.4.3 and 12.0.4 on Ubuntu 20.10.

**Comment by ckerr** [comment]
Looks like this broke in 12.0.0-beta.21. I'm seeing the `max, unmax` log messages in 12.0.0-beta.20 but not beta.21

**Comment by mlaurencin** [comment]
> Looks like this broke in 12.0.0-beta.21. I'm seeing the `max, unmax` log messages in 12.0.0-beta.20 but not beta.21

It looks like the only two things that occurred between these two betas was a [chromium bump](https://github.com/electron/electron/commit/0c5b6bfd30ee94f6f4e7ae244b14ce3269369f1e)

**Comment by PalmerAL** [comment]
Still happening in 13.0. This is a pretty significant issue for us, as it completely breaks our custom implementation of window controls on top of a frameless window.

**Comment by AlekEagle** [comment]
Also having the issue in 13.1.6. maximize is also not being emitted for me.

**Comment by kharratahmed** [comment]
same in v12.0.6

**Comment by davidwinter** [comment]
Can reproduce using Ubuntu 21.04 and Electron 13.1.9

**Comment by jsebean** [comment]
If this is the result of a chromium update, does this affect other chromium use cases, and if so are there any upstream bug reports that can be posted here? I'd like to see action on this, as being unable to bump electron up is a security risk for projects, yet if you do, client side decorations are pretty much unusable on linux without this functionality.

**Comment by yarinsa** [comment]
The same happens to me. It seems that the window state is updated but the event doesn't fire. I emulated the event using listening to 'resize' event and then comparing it to screen size. But that's an ugly solution

**Comment by ccreaper** [comment]
I can confirm on Electron 14. Maximize and unmaximize does not fire if the window is frameless and transparent, preventing implementation of frameless window controls. This is a very breaking bug.

**Comment by 1GMX1** [comment]
i did this and it works with me.

if (win.isMaximized() === true) {
   console.log('Maximize');
}else {
    console.log('Unmaximize');
};
