### ISSUE TITLE
[Bug]: app logs path does not include app name

### ISSUE THREAD

**Issue by jtkDvlp** [electron/electron#28701]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

macOS

### Operating System Version

macOS BigSur

### What arch are you using?

x64

### Expected Behavior

With an app name "MyApp" the app logs path should include "MyApp" e.g. /Users/.../Library/Logs/MyApp.

### Actual Behavior

The app logs path is wrong, it´s "/Users/.../Library/Logs/Electron". Calling "setAppLogsPath" with no args does not take any effect.

### Testcase Gist URL

https://gist.github.com/345aa856623a2f2b20dd12e034e0aa7d

**Comment by nornagon** [comment]
@jtkDvlp would you be able to check to see if this is still an issue in v15.0.0-nightly.20210615 or newer? (`npm install electron-nightly`)

**Comment by jtkDvlp** [comment]
I'll put it on the todo list XD

**Comment by jtkDvlp** [comment]
Sry for sooo late reply. I teste with 15.0.0 and 17.0.0 still seems not to work, still get "/Users/.../Library/Logs/Electron" instead of "/Users/.../Library/Logs/MyApp"
