### ISSUE TITLE
[Bug]: Electron apps like element-desktop only run om server 2012 console session, but not within RDP/ICA Session

### ISSUE THREAD

**Issue by gerhard-recher** [electron/electron#28708]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

Windows

### Operating System Version

server 2012 with citrix 

### What arch are you using?

x64

### Expected Behavior

electron app displays within a virtual rdp/ica session

### Actual Behavior

Application starts, is hidden in systemtray, but no interaction is possible within a rdp/ica session on windows server 2012

**Comment by mlaurencin** [comment]
Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com/) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm setting the `blocked/need-info` label for the above reasons. After you've responded, please @ me in a follow-up comment.

Thanks in advance! Your help is appreciated.

**Comment by gerhard-recher** [comment]
Dear Team,


this is easy to reproduce for you
no way, I downloaded Fiddle on Terminalserver 2012


start within a ICA/RDP Session displays only a blank frame



start on console as administrator, I cant even see the Hello world 
example! but Menue are showing but without any function

on windows 10 Workstation starting fiddle was no Problem, also not building a install package!



Gerhard Recher

Leitenweg 6
86929 Penzing

0171 4802507

Am 27.04.2021 um 02:10 schrieb Michaela Laurencin:

**Comment by gerhard-recher** [comment]
resubmit Pictures, email response did not show them ...

windows version:
![image](https://user-images.githubusercontent.com/78753276/116262572-f39d0480-a778-11eb-9f54-b3eb8bf2e0d1.png)

start within a ICA/RDP Session displays only a blank frame
![image](https://user-images.githubusercontent.com/78753276/116262354-c18ba280-a778-11eb-99e2-89e1a7737519.png)

start on console as administrator, I cant even see the Hello world example! but Menue are showing but without any function
![image](https://user-images.githubusercontent.com/78753276/116262480-dcf6ad80-a778-11eb-94c1-5b8a35f01ad6.png)

**Comment by gerhard-recher** [comment]
> Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com/) that Electron maintainers can use.
> 
> Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.
> 
> I'm setting the `blocked/need-repro` label for the above reasons. After you've responded, please @ me in a follow-up comment.
> 
> Thanks in advance! Your help is appreciated.

I may setup a windows 2012 server for you for testing  these issues

**Comment by mlaurencin** [comment]
Thank you for providing those screenshots.

> I may setup a windows 2012 server for you for testing these issues

And thank you, but I do not believe that will be necessary.

**Comment by mlaurencin** [comment]
I am seeing a similar occurrence when using a Windows 7 VM running on Azure. Not sure if this issue is limited to Windows though.

![image](https://user-images.githubusercontent.com/35157522/116631710-65588800-a90a-11eb-9ace-e109aed453be.png)

**Comment by gerhard-recher** [comment]
> I am seeing a similar occurrence when using a Windows 7 VM running on Azure. Chrome opens with no issue. Not sure if this issue is limited to Windows though.
> I just 1) started an RDP Session, 2) downloaded Electron Fiddle, 3) and launched it.
> 
> ![image](https://user-images.githubusercontent.com/35157522/116631710-65588800-a90a-11eb-9ace-e109aed453be.png)

any timeline to overcome this serious issue ?

regards 

Gerhard

**Comment by gerhard-recher** [comment]
> Thank you for providing those screenshots.
> 
> > I may setup a windows 2012 server for you for testing these issues
> 
> And thank you, but I do not believe that will be necessary.

Hi , any plans to make this work as expected ?

Regards Gerhard

**Comment by nornagon** [comment]
Does starting Electron with `--disable-gpu` alleviate the symptoms?

**Comment by gerhard-recher** [comment]
Nope this did not do the trick !


Gerhard Recher

Leitenweg 6
86929 Penzing

0171 4802507

Am 23.06.2021 um 01:19 schrieb Jeremy Rose:
