### ISSUE TITLE
[Bug]: skipTaskbar is not work when fullscreen is true in Win7

### ISSUE THREAD

**Issue by jackple** [electron/electron#28714]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.4

### What operating system are you using?

Windows

### Operating System Version

Windows 7 Version 6.1.7601

### What arch are you using?

x64

### Expected Behavior

skipTaskbar is work

### Actual Behavior

skipTaskbar is not work
After app launched, the third time I clicked the appIcon in taskbar, the other window with `skipTaskbar: true` is not work

### Testcase Gist URL

https://github.com/jackple/electron-quick-start

**Comment by jackple** [comment]
![image](https://user-images.githubusercontent.com/6183232/115177074-fbb5ce00-a100-11eb-9865-8553cae6bb10.png)

**Comment by jackple** [comment]
Any help?

**Comment by J4rvisW0ng** [comment]
> ![image](https://user-images.githubusercontent.com/6183232/115177074-fbb5ce00-a100-11eb-9865-8553cae6bb10.png)

Same problem in my Win7.

**Comment by zengdongbao** [comment]
you can try set fullscreen false when then window hidden.

**Comment by miniak** [comment]
https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice

**Comment by CommonLoon102** [comment]
@miniak I think this was closed prematurely. The link you shared contains:

> January 2023: Windows 7 & 8 related issues are accepted for all supported release branches.
also

> February 8 2023 - May 29 2023: Electron will continue to accept fixes for supported lines older than Electron 23.

**Comment by CommonLoon102** [comment]
Issue is still reproducible in electron 22.0.1.

> We are using Node.js 16.17.1, Chromium 108.0.5359.125, and Electron 22.0.1.

> Microsoft Windows [Version 6.1.7601]

If I use `mainWindow.setFullScreen(false);` instead of `mainWindow.setFullScreen(true);` then the taskbar icon is hidden properly.
When fullscreen is `true` and I press the Windows button on my keyboard, the app's icon is shown on the taskbar.
