### ISSUE TITLE
[Bug]: option title for the showSaveDialog is not displayed on Ubuntu

### ISSUE THREAD

**Issue by Tabea4** [electron/electron#28718]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.1.1

### What operating system are you using?

Ubuntu

### Operating System Version

20.04.

### What arch are you using?

x64

### Expected Behavior

Hi, 
I’m currently using Electron version 11.1.1 and I’m working on Ubuntu 20.04. I have a question concerning the method `showSaveDialog` (https://www.electronjs.org/docs/api/dialog#dialogshowsavedialogbrowserwindow-options):
On my OS, the title is not displayed in the dialog, even though it is set in the code.
For the `showOpenDialog` however, the title is displayed. (Also see attached screenshots)
Does `showSaveDialog` not support displaying the title, or is this only an issue on Ubuntu?

Thank you for your help!

ShowOpenDialog: title (`Select connection matrix to load`) is displayed as expected
![showOpenDialog](https://user-images.githubusercontent.com/34033202/115217328-b051ee80-a105-11eb-86a0-771402f8883d.jpg)
ShowSaveDialog: no title is displayed even though it is set in the code
![showSaveDialog](https://user-images.githubusercontent.com/34033202/115217333-b1831b80-a105-11eb-85b0-c40804b8f043.jpg)

### Actual Behavior

Title is not displayed (see above screenshot from `showSaveDialog`)

**Comment by Prinzhorn** [comment]
I'm using Ubuntu myself and I'm curious if this is just a limitation of the GtkFileChooserDialog? Where would the title be displayed when the input for the file name takes up the place?

**Comment by Tabea4** [comment]
@Prinzhorn Thanks for the hint. It seems like it is indeed a limitation of the GtkFileChooserDialog. Do you happen to know if the same “issue” exists on other desktop environments and/or other operating systems? 
Either way, it would be nice if this can be added to the documentation of the `showSaveDialog` (similar to `showMessageBoxSync` https://www.electronjs.org/docs/api/dialog#dialogshowmessageboxsyncbrowserwindow-options, where for the `title` option, a simple statement `some platforms will not show it` is provided.)

**Comment by Prinzhorn** [comment]
> Do you happen to know if the same “issue” exists on other desktop environments and/or other operating systems?

Nope, I'm using Ubuntu exclusively but will have to run Windows and mac soon for testing :smile: 

> Either way, it would be nice if this can be added to the documentation of the `showSaveDialog`

You can edit the docs here and make a PR https://github.com/electron/electron/edit/master/docs/api/dialog.md
