### ISSUE TITLE
[Bug]: allow application without tray

### ISSUE THREAD

**Issue by soloturn** [electron/electron#28713]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Other Linux

### Operating System Version

arch rolling

### What arch are you using?

x64

### Last Known Working Electron version

1.0.0

### Expected Behavior

an application is able to implement behaviour for desktop environments with and without tray with ease.

### Actual Behavior

https://www.electronjs.org/docs/api/tray is not clear enough that applications should not rely on a tray for linux - as it is a dying concept. some reasoning is here: https://blogs.gnome.org/aday/2017/08/31/status-icons-and-gnome/

this leads to people requireing strange features, like https://github.com/telegramdesktop/tdesktop/issues/16062.

**Comment by MarshallOfSound** [comment]
> allow application without tray

This is definitely not a requirement, you can build apps without even touching that `Tray` API.  We have documentation that you linked to that outlines the platform-specific limitations of that API (screened below).  PRs are welcome to add missing information to the docs but as it stands this it not a bug as described.

![image](https://user-images.githubusercontent.com/6634592/115163665-3c5d0b00-a05f-11eb-8442-5fe5499512f2.png)

**Comment by soloturn** [comment]
@MarshallOfSound how can you check with the api if the current platform has a tray or not?
