### ISSUE TITLE
[Bug]: BrowserWindow ID Mismatch

### ISSUE THREAD

**Issue by rroessler** [electron/electron#28715]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.2

### What operating system are you using?

Other (specify below)

### Operating System Version

Windows 10 version 1904

### What arch are you using?

x64

### Last Known Working Electron version

Unknown

### Expected Behavior

Suppose a system is set up to have a PRIMARY window where subsequent windows can be opened from. On opening a child/helper window, it would be expected that if they send an IPC request their sender information would have the same ID as a saved variable of their BrowserWindow (say through some handler in the main process).

On opening developer tools in ANY window, this should not alter BrowserWindows IDs.

### Actual Behavior

In the same scenario, the developer tools increments the ID of ALL sender items by 1 each time developer tools are opened. This results in a mismatch on opening new Windows between their sender ID and their created ID.

**Comment by rroessler** [comment]
Gist for proof. Although adding windows (before opening any developer tools), IDs of sender matches what is created. However AFTER opening dev tools, THEN creating a new BrowserWindow, the main process variable has a different ID to event sender ID.

https://gist.github.com/rroessler/c397b67f4e142d25e75c60d1e116377d

**Comment by MarshallOfSound** [comment]
@rroessler The `event.sender.id` property is not the ID of a **window** rather it is the id of the sending **webContents**.

i.e. See the documentation of [`IpcMainEvent`](https://www.electronjs.org/docs/api/structures/ipc-main-event#ipcmainevent-object-extends-event).  The `sender` property is a `webContents`.

What you're seeing is expected behavior.  To verify you can `console.log(event.sender)` and see the webContents object being logged.
