### ISSUE TITLE
[Bug]: NodeIntegration not working

### ISSUE THREAD

**Issue by Frostingly** [electron/electron#28732]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.4

### What operating system are you using?

Windows

### Operating System Version

10.0.19042 Build 19042

### What arch are you using?

x64

### Expected Behavior

When I have NodeIntegration set to true, it should allow me to use the required to function so I can require jquery for my functionality, it should then do the functionality set using jquery.

https://sourceb.in/rHTUj9xFBH - Main code.
https://sourceb.in/L6dsQb62GM - HTML code.
https://sourceb.in/Y9HtMU6NxK - JQuery code.

### Actual Behavior

It doesn't allow me to use the require function, it simply says that require is not defined and doesn't run the functionality.

**Comment by miniak** [comment]
https://github.com/electron/electron/blob/master/docs/breaking-changes.md#default-changed-contextisolation-defaults-to-true

**Comment by MarshallOfSound** [comment]
> You need to disable contextIsolation, it is enabled by default in Electron 12+

You should **not** disable contextIsolation, instead work to refactor your application logic to support the new default.  Context Isolation is a security measure, you shouldn't disable it purely out of developer convenience, it was enabled by default for a reason
