### ISSUE TITLE
[Bug]: DevTools disconnected from due to renderer process crash

### ISSUE THREAD

**Issue by YQOpenSource** [electron/electron#28759]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.2.0

### What operating system are you using?

macOS

### Operating System Version

Big Sur 11.2.1

### What arch are you using?

x64

### Expected Behavior

Renderer process should not crash when html page changed.

### Actual Behavior

when source code of an hot-load developing application is changed, the renderer process show out message like "Devtools was disconnected from the page, ...", as electron log show as following:
```
...
[40227:0421/181014.426211:WARNING:accelerator_util.cc(63)]  doesn't contain a valid key
[40227:0421/181014.427865:WARNING:accelerator_util.cc(63)]  doesn't contain a valid key
[40227:0421/181014.428097:WARNING:accelerator_util.cc(63)]  doesn't contain a valid key
[40227:0421/181014.428139:WARNING:accelerator_util.cc(63)]  doesn't contain a valid key
Renderer process crashed - see https://www.electronjs.org/docs/tutorial/application-debugging for potential debugging information.
...
```

**Comment by codebytere** [comment]
@YQOpenSource we need a reproducible sample, as stated in the template, to triage this. Please provide one or this issue will be closed in 5 days.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
