### ISSUE TITLE
Notify when the document.reload() is called

### ISSUE THREAD

**Issue by gdavidkov** [electron/electron#28754]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.4.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

We have internal logic when the page is refreshed but I cannot find a way how to handle location.reload().

### Actual Behavior

Nothing.

**Comment by mlaurencin** [comment]
Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com/) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm setting the `blocked/need-repro` label for the above reasons. After you've responded, please @ me in a follow-up comment.

Thanks in advance! Your help is appreciated.

**Comment by pushkin-** [comment]
Can you listen for the [`did-navigate`](https://www.electronjs.org/docs/api/web-contents#event-did-navigate) event to find this out (though this would be called in other cases too like `location = location.href` for example; not sure if that matters for you at all)

**Comment by codebytere** [comment]
Closing as no response was provided. However, we can always re-open this should more information come to light.
