### ISSUE TITLE
[Bug]: takeHeapSnapshot failed without reasons

### ISSUE THREAD

**Issue by ervinewell** [electron/electron#28758]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.4.2

### What operating system are you using?

macOS

### Operating System Version

macOS big sur 11.2.3

### What arch are you using?

x64

### Last Known Working Electron version

11.4.2

### Expected Behavior

Contents.takeHeapSnapshot works well

```
window.require('electron').remote.getCurrentWindow().webContents.takeHeapSnapshot('/Users/weirusong/Desktop/snapshot').then(console.log).catch(console.log)
```

### Actual Behavior

Error: takeHeapSnapshot failed
    at electron/js2c/browser_init.js:213
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:213)
    at IpcMainImpl.emit (events.js:315)
    at Object.<anonymous> (electron/js2c/browser_init.js:157)
    at Object.emit (events.js:315)

![Uploading image.png…]()

**Comment by mlaurencin** [comment]
Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com/) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm setting the `blocked/need-repro` label for the above reasons. After you've responded, please @ me in a follow-up comment.

Thanks in advance! Your help is appreciated.

**Comment by codebytere** [comment]
Closing as no response was provided.
