### ISSUE TITLE
After build electron printToPdf api not working.

### ISSUE THREAD

**Issue by dtboy1995** [electron/electron#28775]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

6.1.2

### What operating system are you using?

Windows

### Operating System Version

Windows10

### What arch are you using?

x64

### Last Known Working Electron version

9.3.4

### Expected Behavior

**se electron-vue template**

```
Node v12.18.3
OS windows10
```

```
    "electron": "^9.3.4",
    "electron-builder": "^20.38.5",
    "electron-debug": "^2.1.0",
    "electron-devtools-installer": "^2.2.4",
    "electron-rebuild": "^1.10.1",
```

### npm run dev (works well)
```js
win.webContents.printToPDF({
          marginsType: 1,
          landscape: false,
          printBackground: true,
          printSelectionOnly: false,
          scaleFactor: 100,
        })
```

### after npm run build  run exe got error

test on 6.1.12 & 9.3.4 all failed
6.1.12 not resolve or reject, never end
9.3.4 reject for [Error: Failed to generate PDF]

```error
[Error: Failed to generate PDF]
```

### Testcase Gist URL

https://gist.github.com/dtboy1995/208a3d9499c19bcb42fc8e8f7a460895

**Comment by mlaurencin** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If you’re still experiencing this issue in Electron 10.x.y or later, please add a comment specifying the version you’re testing with and any other new information that a maintainer trying to reproduce the issue should know.

I’m setting the `blocked/need-info` label for the above reasons. This issue will be closed 10 days from now if there is no response.

Thanks in advance! Your help is appreciated.
