### ISSUE TITLE
Is there a way to make electron desktop bundle size smaller

### ISSUE THREAD

**Issue by amolfasale** [electron/electron#28771]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently we are evaluating **electron-9.4.0** for desktop app development, and we have package size constraints while shipping the app, and I can see electron simple 'Hello, World!' app takes around 115MB for package, is there any way to reduce it under 40-45MB(app not installer), without compromising existing functionality? 

### Proposed Solution

Default application framework size should be minimum as possible.

### Alternatives Considered

NA

### Additional Information

NA

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).
