### ISSUE TITLE
[Bug]: BrowserWindow.getAllWindows returns closed windows in window-all-closed event

### ISSUE THREAD

**Issue by xmedeko** [electron/electron#28774]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

According to the doc [`BrowserWindow.getAllWindows`](https://www.electronjs.org/docs/api/browser-window#browserwindowgetallwindows): Returns `BrowserWindow[]` - An array of all opened browser windows. I expect that behaviour always.

### Actual Behavior

In the [`window-all-closed`](https://www.electronjs.org/docs/api/app#event-window-all-closed) event handler the `BrowserWindow.getAllWindows` is not empty, it returns the closed window.

Note: when running inside Electron Fiddle, the `console.error` from the `window-all-closed` does not appear in the Fiddle's console when the app quits. It appears in the Fiddle's console when you Run the app again.

### Testcase Gist URL

https://gist.github.com/8b63d0581b49793ce8bdddfe0aecaed3

**Comment by xmedeko** [comment]
Peering at the Electron Fiddle's code, seems to me that it has a workaround to this problem by keeping it's own list of `browserWindows` in [windows.ts#L9](https://github.com/electron/fiddle/blob/master/src/main/windows.ts#L9).

**Comment by nornagon** [comment]
Should be workaround-able by listening to `on('closed')` and filtering out closed windows from that list. That's a workaround we could probably build in to Electron itself though.

**Comment by Officialstrike** [comment]
The issue here seems to be that, the `browserWindows[]` is delayed when updated.
