### ISSUE TITLE
[Feature Request]: Provide API for auto toggling devtools when a key is pressed

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#28770]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I want to toggle devtools when I press F12.

I have code like this:
```
mainWindow.webContents.on("before-input-event", (e, input) => {
    if (input.type === "keyDown" && input.key === "F12") {
      mainWindow.webContents.toggleDevTools();
    }
});
```

When I press F12 and devtools opens up, focus goes to the devtools, and pressing F12 again doesn't do anything.

I tried adding the same `before-input-event` handler to `mainWindow.webContents.devToolsWebContents`, but it is `null` immediately after calling `toggleDevTools`.

I put the code on a `setTimeout(..., 1000)`, which worked (meaning the devtools webcontents is set; perhaps I should be using the devtools opened event), but none of the keys are intercepted in the handler.

This is mentioned [here](https://github.com/electron/electron/issues/1962) as a limitation.

### Proposed Solution

I'm not sure what can be done to solve this on my end. Seems like either Electron needs to allow detecting input, or provide an API like `mainWindow.webContents.toggleDevToolsOnKeyPress("F12")` that handles this for us.

### Alternatives Considered

listed attempted solution above, which didn't work. Full solution:

```
const {app, BrowserWindow } = require('electron')

async function createWindow () {
  const mainWindow = new BrowserWindow();
  await mainWindow.loadURL("https://google.com");
  mainWindow.webContents.on("before-input-event", (e, input) => {
    if (input.type === "keyDown" && input.key === "F12") {
      mainWindow.webContents.toggleDevTools();
      console.log(mainWindow.webContents.devToolsWebContents); // null right after opening, which perhaps makes sense

      setTimeout(() => {
        mainWindow.webContents.devToolsWebContents.executeJavaScript().on("before-input-event", (e, input) => {
          // no events are intercepted
          if (input.type === "keyDown" && input.key === "F12") {
            mainWindow.webContents.toggleDevTools();
          }
        });
      }, 1000);
    }
  });
}

app.whenReady().then(() => {
  createWindow()
  
  app.on('activate', function () {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})
```

### Additional Information

n/a

**Comment by pushkin-** [comment]
honestly, I'm somewhat doubtful that this API will be implemented by Electron, but maybe there be some way to have the key press be detected for devtools, so that I can toggle it myself?

**Comment by nornagon** [comment]
I think this is because the `toggleDevTools` menu role doesn't properly check for the 'parent' window of a devtools window. it would probably be possible to have the `toggleDevTools` menu role check to see if the currently focused window is a devtools window, and if so, call `toggleDevTools` on the webcontents for which the devtools is opened, instead of on the devtools window itself.

**Comment by pushkin-** [comment]
Well, actually now that I think about it, the problem is that we're not even calling `toggleDevTools` in the first place because we're not picking up the F12 key when we're focused in the devtools webcontents. Maybe I just didn't understand your comment though.

**Comment by 1j01** [comment]
Here's my hacky solution using `executeJavaScript`'s async nature:
```js
  // Toggle the DevTools with F12
  mainWindow.webContents.on("before-input-event", (e, input) => {
    if (input.type === "keyDown" && input.key === "F12") {
      mainWindow.webContents.toggleDevTools();

      // Can't use mainWindow.webContents.devToolsWebContents.on('did-finish-load') - devToolsWebContents doesn't exist yet.
      const iid = setInterval(() => {
        if (mainWindow.webContents.devToolsWebContents) {
          clearInterval(iid);
          // Can't use mainWindow.webContents.devToolsWebContents.on("before-input-event") - it just doesn't intercept any events.
          mainWindow.webContents.devToolsWebContents.executeJavaScript(`
            new Promise((resolve)=> {
              addEventListener("keydown", (event) => {
                if (event.key === "F12") {
                  resolve();
                }
              }, { once: true });
            })
          `)
            .then(() => {
              mainWindow.webContents.toggleDevTools();
            });
        }
      }, 50);
    }
  });
```

**Comment by 1j01** [comment]
Update: the above solution is not very reliable, especially when the page reloads. Maybe it could be improved by using the normal IPC APIs, but it would be nice if the `before-input-event` worked on the devtools webcontents!

**Comment by miniak** [comment]
you can assign shortcuts to menu items
