### ISSUE TITLE
[Bug]: macOS window shadow weirdness

### ISSUE THREAD

**Issue by robin-fowler** [electron/electron#28782]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.0.0-beta.16

### What operating system are you using?

macOS

### Operating System Version

macOS Big Sur 11.2.1

### What arch are you using?

x64

### Last Known Working Electron version

12.0.5

### Expected Behavior

When viewing a window in mission control the shadow shouldn't change.

### Actual Behavior

When viewing a window with vibrancy set to 'under-window' and titleBarStyle set to 'hidden' or 'hiddenInset' in mission control the shadow of the window is too small. 

It only seems to happen when the window is in focus and when there are multiple windows on the screen. The behaviour can sometimes persist when going from mission control to normal view. 

See the window at the bottom left in the screenshot.

<img width="1195" alt="Screenshot" src="https://user-images.githubusercontent.com/54709288/115758066-a397f980-a396-11eb-9ecc-c97e670b3b82.png">

**Comment by MarshallOfSound** [comment]
That shadow is rendered by macOS.  I'm not entirely sure what level of control we might even have over such things 🤷

**Comment by robin-fowler** [comment]
Hmm it doesn't happen in version 12 though, must have been some change in 13. I'm doing some more testing and it's only happening for windows with vibrancy set to 'under-window' and titleBarStyle set to 'hidden'.

**Comment by robin-fowler** [comment]
I wonder if it has something to do with this line https://github.com/electron/electron/blob/909bfde8168170fc3d1e244f8c123d2a40468e86/shell/browser/native_window_mac.mm#L1549

looks like it was removed in v13
