### ISSUE TITLE
[Bug]: DevTools not showing local variable values when "Paused in debugger", instead, displays "Not paused"

### ISSUE THREAD

**Issue by MarcusOy** [electron/electron#28789]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.1.0

### What operating system are you using?

macOS

### Operating System Version

10.15.4

### What arch are you using?

x64

### Last Known Working Electron version

n/a

### Expected Behavior

While the app is in state "Paused in debugger," local variables within scope show themselves and their values in Sources > Scope tab. Hovering over a valid variable symbol shows that variable's current value. Variable values are also shown inline.

![image](https://user-images.githubusercontent.com/16263577/115788835-cc65c200-a389-11eb-946c-f2ddf664e715.png)

### Actual Behavior

While the app is in state "Paused in debugger," the Sources > Scope tab displays "Not paused." Hovering over a variable does nothing. Variable values are not shown inline.

<img width="527" alt="Screen Shot 2021-04-22 at 5 31 23 PM" src="https://user-images.githubusercontent.com/16263577/115788862-da1b4780-a389-11eb-94a2-c2ecbe46f7af.png">

### Testcase Gist URL

Will do sometime this weekend.

### Additional Information

Problem seems to align with issues #27523 and #20383. Opening this issue since the latter seems to have been closed.

**Comment by nornagon** [comment]
I don't generally observe this, would love to have a reliable & small repro.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
