### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Zhuyb912** [electron/electron#28794]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

npx electron-forge import

### Actual Behavior

Get Error:

> npm ERR! code ENOENT
npm ERR! syscall symlink
npm ERR! path E:\workspace\else\expxls\node_modules\_extract-zip@1.7.0@extract-zip
npm ERR! dest E:\workspace\else\expxls\node_modules\_electron@12.0.5@electron\node_modules\extract-zip
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, symlink 'E:\workspace\else\expxls\node_modules\_extract-zip@1.7.0@extract-zip' -> 'E:\workspace\else\expxls\node_modules\_electron@12.0.5@electron\node_modules\extract-zip'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by baconbrad** [comment]
Electron Forge is in "userland" meaning it is third party maintained and not an Electron bug. [Here is the appropriate place](https://github.com/electron-userland/electron-forge) to report bugs for it.

**Comment by MarshallOfSound** [comment]
@baconbrad's comment is accurate
