### ISSUE TITLE
[Documentation] Links in official docs are broken

### ISSUE THREAD

**Issue by hovancik** [electron/electron#28795]
Hi team,

the links in docs are broken.

**Example**

Visit https://www.electronjs.org/docs/tutorial/installation and click "Electron versioning doc". 
It links to https://www.electronjs.org/docs/tutorial/electron-versioning.md but that returns 404. 

Removig `.md` fixes the issue: https://www.electronjs.org/docs/tutorial/electron-versioning

**One thing to consider**

When visit page on Github: https://github.com/electron/electron/blob/master/docs/tutorial/installation.md and clicking on the same link. It works.

**Comment by miniak** [comment]
It works now
