### ISSUE TITLE
[Feature Request]: Independent keyboard and mice capture

### ISSUE THREAD

**Issue by smartguy1196** [electron/electron#28805]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Capture the events of 2+ keyboards/mice in browser

as described in https://stackoverflow.com/questions/14959989/capture-the-events-of-2-or-more-keyboards-in-javascript-web-browser

### Proposed Solution

Add a property to `KeyboardEvent`/`MouseEvent` that identifies the hardware associated with the keypress/mouse movement

### Alternatives Considered

extending the gamepad api

### Additional Information

Intended and example usages:

keylogger
multiplayer html5 canvas games with split-screen support

**Comment by nornagon** [comment]
This is a feature request for Chromium, not Electron. Try your luck over here: https://crbug.com/new

**Comment by smartguy1196** [comment]
@nornagon you gave me the link for bug reporting
