### ISSUE TITLE
[Bug]: there is problem with ampersand "&" , when the project path include "&".

### ISSUE THREAD

**Issue by metalliclambda** [electron/electron#28825]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5

### What operating system are you using?

Windows

### Operating System Version

windows 7 x64

### What arch are you using?

x64

### Expected Behavior

a simple sample code in the Quick start, to run normal, when "&" character is in the project folder path address. for example E:\test2& .

### Actual Behavior

when there is "&" in the path of the project folder, for example "E:\test2&" , (i know mostly no one would choose a folder name with "&", but its does not make sense that a code crash, bcs of a "&" in the path of the project folder.
if i just remove the "&" from the folder name, it will work fine.
i tested it with simple sample code in the quick start, both with and without "&" in the folder name. 

E:\test2&>npm start

> test2@1.0.0 start E:\test2&
> electron .

'\node_modules\.bin\' is not recognized as an internal or external command,
operable program or batch file.
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'E:\electron\cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js
:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test2@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test2@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\my-PC\AppData\Roaming\npm-cache\_logs\2021-04-24T07_4
8_02_473Z-debug.log

**Comment by nornagon** [comment]
I can confirm this. Very strange! Thanks for the report.

**Comment by nornagon** [comment]
I think this is a bug in https://github.com/npm/cmd-shim. The app works correctly when run with `electron.exe` directly, it's only when executing it through `node_modules\.bin\electron` that the error occurs.

Closing as I don't think this is an Electron bug. I'd recommend reporting over at the cmd-shim repo.
