### ISSUE TITLE
[Bug]: Even though I set different partitions for BrowserWindows, they shared cookies 

### ISSUE THREAD

**Issue by pleasecheckhere2016** [electron/electron#28826]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

12.0.5

### What operating system are you using?

Windows

### Operating System Version

win7

### What arch are you using?

x64

### Expected Behavior

if a browserWindow  has a unique partition, it will not share the cookies,did them?

### Actual Behavior

they shared cookies

### Additional Information

The latter cookie of new BrowserWindow always overrides the front, so even though I have multiple Windows, hey display the same content
```
let counter = 0
ipcMain.on('createNewWindow', (event, arg) => {
    let abc = new BrowserWindow({
        height: 563,
        width: 350,
        webPreference: {
            session: session.fromPartition(`${counter++}`)
        }
    })
    let mysession = abc.webContents.session
    const cookie = {
        url: 'https://www.demo.com',
        expirationDate: 2471166135,
        domain: '.demo.com',
        name: 'name1',
        value:  arg.name
    }
    let p1 = mysession.cookies.set(cookie)

    const cookie2 = {
        url: 'https:///www.demo.com',
        expirationDate: 2471166135,
        domain: '.demo.com',
        name: 'name2',
        value:  arg.value
    }
    let p2 = mysession.cookies.set(cookie2)

    Promise.all([p1, p2]).then(value => {
        abc.loadURL('https://www.demo.com')
    })
})
```

**Comment by nornagon** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/need-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Thanks in advance! Your help is appreciated.
