### ISSUE TITLE
[Bug]: webContents.print() not working correctly

### ISSUE THREAD

**Issue by antiochtech** [electron/electron#28828]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

11.2.3

### What operating system are you using?

Ubuntu

### Operating System Version

18.04

### What arch are you using?

x64

### Expected Behavior

expected to print to hardware printers, as well as virtual printers, with margins and any other options as specified.

### Actual Behavior

does not print to hardware printer. instead device perpetually indicates that it is processing data.

prints to virtual pdf printer, ignoring specified options such as margintype and margins when margintype is custom.

### Additional Information

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
    </head>
    <body>
        <div style="position: absolute; top: 0in; left: 0in;">0</div>
        <div style="position: absolute; top: 0in; left: 1in;">1</div>
        <div style="position: absolute; top: 0in; left: 2in;">2</div>
        <div style="position: absolute; top: 0in; left: 3in;">3</div>
        <div style="position: absolute; top: 0in; left: 4in;">4</div>
        <div style="position: absolute; top: 0in; left: 5in;">5</div>
        <div style="position: absolute; top: 0in; left: 6in;">6</div>
        <div style="position: absolute; top: 0in; left: 6.5in;">6.5</div>

        <div style="position: absolute; top: 0in; left: 0in;">0</div>
        <div style="position: absolute; top: 1in; left: 0in;">1</div>
        <div style="position: absolute; top: 2in; left: 0in;">2</div>
        <div style="position: absolute; top: 3in; left: 0in;">3</div>
        <div style="position: absolute; top: 4in; left: 0in;">4</div>
        <div style="position: absolute; top: 5in; left: 0in;">5</div>
        <div style="position: absolute; top: 6in; left: 0in;">6</div>
        <div style="position: absolute; top: 7in; left: 0in;">7</div>
        <div style="position: absolute; top: 8in; left: 0in;">8</div>
        <div style="position: absolute; top: 9in; left: 0in;">9</div>
    </body>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            let win = BrowserWindow.getFocusedWindow();
            var options = {
                color: false,
                dpi: {
                    horizontal: 300,
                    vertical: 300
                },
                margins: {
                    marginType: "custom",
                    top: 300,
                    bottom: 300,
                    left: 300,
                    right: 300
                },
                pageSize: "Letter"
            };

            win.webContents.print(options, (success, failureReason) => {
                if (!success) console.log(failureReason);
                console.log('Print Initiated');
            });
        });
    </script>
</html>
```

**Comment by abnerlee** [comment]
I met the same issue on 13.1.7 on Ubuntu

execute "window.print()" directly in rendered works, though.

**Comment by antiochtech** [comment]
i eventually used printToPDF() then the pdf-to-printer module to both workaround it and provide a preview.

**Comment by codebytere** [comment]
Closing as this should be working in latest supported versions.
